### ISSUE TITLE
Coordinate Teams for VBA comms and location of assets 

### ISSUE THREAD

**Issue by dsinla** [department-of-veterans-affairs/va.gov-cms#10002]
## Acceptance Criteria
- [ ] Initial members of Team are defined
- [ ] Team is created and members invited
- [ ] GIthub repository directory structure is established, initial documents are uploaded 

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by dsinla** [comment]
I've created a Team and added:
David Shannon (Team Owner)
Roger Eagans
Val Runde
David Pickett
Aslan (David) French
Dave Conlon (assigned as Team Owner)

@swirtSJW I didn't see your va.gov email in the [team roster](https://va-gov.atlassian.net/wiki/spaces/VAGOV/pages/185270337/Team+Roster+2022) 

Next step is to check with Dave C and confirm VBA business personnel to add.

**Comment by RWEagans** [comment]
@dsinla Will this case go to the next sprint? Can you add some notes as to why?

**Comment by dsinla** [comment]
Sorry @RWEagans should have closed this earlier.

Team is created, members invited, initial files uploaded.
Link to Team: [VBA VA.gov modernization](https://teams.microsoft.com/l/team/19%3awtiHEMjyNO78gH8g3GRFMs-tqzOwqUuquYGP9Ke3MNE1%40thread.tacv2/conversations?groupId=b71ff2cf-0871-49a8-a9c7-7411bad6eb2f&tenantId=e95f1b23-abaf-45ee-821d-b7ab251ab3bf)
It was decided that collaboration assets/onging meeting notes will reside it Teams, rather than github. Github will be used to store more final deliverables, not for collaboration.
