### ISSUE TITLE
SPIKE: How to translate a page with entity references

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#10004]
## Description

We need to understand how to translate entity references on translated pages, for the bright future of translations.

## Acceptance Criteria
- [x] Understand plan, document 
  - https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10004#issuecomment-1435117996

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by jilladams** [comment]
SPrint planning: 
Can investigate.
Best / easiest path may be: input translations for PACT as a different node type that doesn't use reusable Q&A. 

Long-term: need a better way.

**Comment by jilladams** [comment]
Reframing from PACT-related to general use for future of translations.

**Comment by jilladams** [comment]
Can do mini refining / pull into sprint if we have capacity.

**Comment by timcosgrove** [comment]
@EWashb I'm keeping this one to track documenting this. It is (relatively) straightforward, provided the CMS and TMGMT are configured correctly.
