### ISSUE TITLE
Workflow notifications and assignments brainstorm for research plan

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#1000]
To do
- [x] Write research plan
   - [x] Conversation guide
   - [x] Consent form
- [x] Get Jeff Barnes caught up on this epic (with Kevin)
- [x] Get approval for research (Jeff Barnes)

**Comment by howardbrande** [comment]
Slack conversation / use case https://dsva.slack.com/archives/CDHBKAL9W/p1583177255114900
