### ISSUE TITLE
CM for deprecating hard coded isCerner data

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#10022]
The change represented by the epic # will remove the hard-coded `isCerner` "API" and any associated dead code, once all teams' apps/widgets have moved to Drupal as source of truth for Cerner content.

**Ticket that will unblock this CM ticket**: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9307
**Timeline**: EOY 2022 / Q1 2023

**1. Describe the change from the perspective of VA employees, in plain language. What is the employee going to experience with this change?**

Editors or engineers who modify Cerner React widgets will no longer use the `isCerner` value in the code as the source of truth for whether a facility has moved from VistA to Cerner. Instead, the source of truth will be in CMS, on VAMC Systems, VA Health Connect and Health Records System section, Electronic health records system field.

**2. Explain why the change is necessary from a CMS/platform and project goal perspective. Link to screenshots if that helps tell the story.**
The hard coded data path will, at the point we take action on this ticket, have been deprecated. All code, widgets, and systems that need to programatically know whether a VAMC System is Cerner or VistA will need to reference the Drupal value instead. 

**3. Select the role(s) impacted by the change.**
- [ ] All CMS users
- [ ] All CMS editors
- [ ] Vet Center editor
- [ ] VA Medical Center editor
- [ ] VA Outreach Hub editor
- [ ] VA Benefits Hub editor
- [ ] Campaign landing page editor
- [ ] VA Resources and Support editor
- [ ] Offices editor
- [ ] Supporting roles such as CMS account admin, Facilities or Public websites team member

This data doesn't broadly apply to editors. The specific stakeholders involved are: 
Teams interested in widgets, index.js
* VAOS (online scheduler) – Jeff Roof (PM)
  * Simi Adebowale, VAOS eng lead
* Authenticated Experience – Samara Strauss (OCTO lead), MyVA is the product 
  * Anastasia “AJ” Jakabcin (PM)
  * Taylor Mitchell (eng)
  * Erica Sauve (assoc PM)
* Health Apartment (?)
  * Tracey Mulrooney (PM)
  * Patrick Vinograd (eng)
  * Christopher Froehlich (eng)

**4. How will success be defined for this change?**
TBD

**5. How will success be measured for this change?**
- [X] No help desk support is needed, as measured through help desk tickets
- [ ] The content adheres to VA policies and standards for VA.gov, as measured through a dashboard tool and/or audit

**6. Does the change require new or updated:**
- [ ] Knowledge Base article(s)
If existing articles, list URLs:
- [ ] Training video(s)
If existing videos, list URLs:
- [ ] CMS UI support
- [ ] Announcement block

**7. Will the change be tested with users before release?**
- [ ] Yes
- [X] No

**8. Are there any known dependencies?**
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9307

## Key Dates (pre-event communications, preview with User Support, launch date, post-event tasks)
* Q3 2022 - Public websites will provide documentation that allows other teams to implement against the new data source
* EOY 2022 - Deadline to onboard to the new data source
* ~Q1 2023 - EOL hard coded Cerner data source & CM

**Comment by wesrowe** [comment]
Closing as a no-op. We published [documentation](https://depo-platform-documentation.scrollhelp.site/developer-docs/how-to-opt-in-to-drupal-as-the-source-of-truth-for) for VAOS and MyVA teams to follow, and they successfully moved off of the hard-coded API as of mid-Dec 2022.
