### ISSUE TITLE
PM: Build Lovell KB article(s)

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#10027]
As an editor, I want an article I can refer to for guidance on Lovell  

Likely need two separate articles.  One for editors and one for admin type stuff.

The ACs need refining, what is listed as ACs so far is likely incomplete.

- KB for editors
   - [ ] How do I create pages that only show up in Lovell VA?
   - [ ] How do I create pages that only show up in Lovell Tricare?
   - [ ] How do I create pages that appear in both Lovell VA and Lovell Tricare?
      - [ ] Four exceptions to the rule: Medical records, Register for care, Policies, & Billing and insurance - Note:I (swirt) do not think we need to call these out as no editors have permission to create these pages.  They were created automatically.  They can only edit.  On editing, consider whether to call out that the pages in Lovell VA are hardened pages, and the pages in Lovell TRICARE are detail pages.   This might be Too Much Information.  See how it reads.
   - [ ] How can I verify where my Lovell page will show up? _(check the URL in the info block)_
   - [ ] What if the Menu for Lovell Tricare seems mis-ordered?
   
- KB for content-admin / admin
   - [ ] What content gets pushed to the facility locator / what is exempt from push. (ex: status on John Lovell Tricare node.
   - [ ] does govdelivery  notifications work for Lovell
   - [ ] What if a new DOD facility needs to be created.
      - [ ] Process governance for how to create new tricare facility IDs

https://github.com/department-of-veterans-affairs/va.gov-cms/issues/new?assignees=&labels=Knowledge+Base%2C+Needs+refining&template=knowledge-base-article.md&title=Request+for+new+or+update+to+existing+KB+article+%3A+%3Cinsert+topic+here%3E

- [ ] Review with Dev team 
Insert into standard KB request process 

## ACs

- [ ] Request for new Article made to Support team

- [ ] Articles are created by Facilities team and submitted

**Comment by swirtSJW** [comment]
Production of this article(s) is blocked by being far enough along to be able to take good screenshots of the editorial experience.

**Comment by swirtSJW** [comment]
Some of the topics will depend on sticking points in the editorial experience.

**Comment by swirtSJW** [comment]
I added some more ACs but the list is incomplete.

**Comment by JayDarnell** [comment]
@swirtSJW do you feel we are far enough along now that this is unblocked and actionable?

**Comment by dsinla** [comment]
I've begun the scaffolding for these KB topics [here](https://docs.google.com/document/d/1wkeJNJxen_TNYnGqlzDzjFCSKq2vRxt_6dy6pkuspR0/edit#)
Reviewed with @JayDarnell today
Also shared with @stefaniefgray and @TroyA6 to begin discussing

**Comment by dsinla** [comment]
Met with @TroyA6 to discuss next steps.  @dsinla will create first draft of 3 KB's:

- Authoring content for Lovell
	Overview content and switcher description
- Creating content for Lovell 
	Assigning the proper section 
- Changing the assigned section for Lovell content 
	Checking for existence of content
	Changing/Assigning proper section 

Request for Editor-facing KBs
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11687

Request for Admin KBs (likely not this sprint)
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11689

Working [google doc with instructions](https://docs.google.com/document/d/1wkeJNJxen_TNYnGqlzDzjFCSKq2vRxt_6dy6pkuspR0/edit#)

**Comment by dsinla** [comment]
First draft of topics:

https://prod.cms.va.gov/lovell-federal-va-health-care/vamc/creating-content-for-lovell-federal-health-care
https://prod.cms.va.gov/lovell-federal-va-health-care/vamc/assigning-sections-for-lovell-federal-health-care-content 
https://prod.cms.va.gov/lovell-federal-va-health-care/vamc/changing-the-assigned-section-for-lovell-federal-health-care-care

**Comment by dsinla** [comment]
Articles have been created, reviewed by DEV, and submitted to Support Team
