### ISSUE TITLE
[CMS COLLAB CYCLE INTAKE] Public Websites, Resources & Support, add reusable Q&A

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#10043]
### What type of request are you making?

- [X] Update to an existing CMS feature (including product iterations, updating DS components or page layouts and nav changes)
- [ ] New CMS feature (New content types, DS components, workflows or products)
- [ ] Content audit (either one time audits or resuable tools)
- [ ] Change Management review (for any visible changes to the CMS, workflow or content model)
- [ ] Other

### Please choose the team that is requesting the Collab Cycle kickoff.

Public Websites

### When did/will you start working on this product/feature?

Q3 2022

### When will your feature need to launch?

Sprint 64

### Are you doing research with VA.gov users or editors?

No

### Will your work involve changes to...?

CMS content model, CMS features that span multiple products or work streams

### Please add a link to your product outline issue.

https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9737

### Additional Information

Scope of these changes: 
* Sitewide Content team-focused feature: make Q&A Single nodes reusable within Q&A groups (a la FAQ), on Resources & Support nodes
* Add a Description field to Q&A groups
* Within "Choose Q&A" modal, add filter to allow finding Q&A nodes by title

### Notify the Sitewide CMS team of this ticket in the cms-support Slack channel.

- [X] I acknowledge that I must notify `#cms-support` after submitting this issue.

**Comment by EWashb** [comment]
@jilladams who all needs to be involved in this convo? I foresee this not being as intense since you're so close to launch.

**Comment by jilladams** [comment]
@chri5tia and me, and @fmccaf1 optional probably, just for exposure to what sort of design considerations there may be in the CMS in future?  (@wesrowe optional, too)

**Comment by jilladams** [comment]
Florence flagged some questions that we'd like to talk through with you all when we meet: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9737#issuecomment-1206584983. 

@EWashb lemme know if you'd like me to work on scheduling

**Comment by EWashb** [comment]
Sorry for the delay @jilladams! It has been a crazy week. I don't mind if you schedule at all (if you have the time). You can invite @dawnpruitt @cjterdi @ndouglas and @edmund-dunn

**Comment by laflannery** [comment]
@jilladams and @wesrowe I found the [accessibility issue](https://github.com/department-of-veterans-affairs/va.gov-team/issues/30359) I was referring to but it's in the other repo and it could use some refining/more description based on some other instances I've found.  Do you still want me to assign it directly to you?  I know this relates to the discussion we plan on having later this week

**Comment by jilladams** [comment]
If you want to update it with your notes before you assign, then we can move it into our board when it's ready for us.

**Comment by EWashb** [comment]
Apologies for the delayed response on this @jilladams . We do recommend a midpoint review for this work. 

The deliverable for this review would be any prototypes, wireframes, etc. These design review docs can be delivered async

A tech review may need to be conducted as well at midpoint if you have a handle on the content model.

**Comment by jilladams** [comment]
Backend/CMS changes are merged; front end changes are in PR and on their way to merge.

**Comment by jilladams** [comment]
Front-end changes are launched as of today. Last step here is to re-expose the CMS fields that are now hooked up. Let me know what next steps are here for closing out?

**Comment by EWashb** [comment]
I don't think there's anything left for us for this. You've gone through the code and accessibility review, correct?

**Comment by jilladams** [comment]
Code review = done
Accessibility review = #10126  led to Discovery ticket, #10136 which closed in this sprint. The issue is broader than just this project, but is high priority and will keep moving to resolution.

**Comment by jilladams** [comment]
Launched! https://dsva.slack.com/archives/C01K37HRUAH/p1661898819583139
