### ISSUE TITLE
Add patch for Mapbox endpoint config

### ISSUE THREAD

**Issue by omahane** [department-of-veterans-affairs/va.gov-cms#10055]
## Composer Patch
This adds a composer patch that relates to the work done on the Geocoder module in https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/520

## Acceptance Criteria
- [ ] When the CMS is built, the Mapbox provider has a "Geocoding Mode" field on https://va-gov-cms.ddev.site/admin/config/system/geocoder/geocoder-provider/manage/mapbox
- [ ] The "Geocoding Mode" is populated with "mapbox.places" by default
- [ ] When changing the address of a Vet Center CAP, the geocode changes in accordance with the new address (verifiable as an admin).

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by swirtSJW** [comment]
Upstream issue https://www.drupal.org/project/geocoder/issues/3301383
