### ISSUE TITLE
Header folllow-on: Document current state of header build and distribution / injection / build

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#10059]
## Description

Follow-on to #9139.

The goal of this ticket is to write documentation for the header (both desktop and mobile) with dev audience in mind (i.e. other FE devs who will be joining PW team, devs on the Accelerated Publishing team) and to tie it back to existing documentation (see below).

There exists a product [brief](https://github.com/department-of-veterans-affairs/va.gov-team/blob/5e0f4d3c470ed2f32290ff1a6e2cc7c2c97f7847/products/public-websites/home-page/new-mobile-header/Initiative%20Briefing.md) and [outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/5e0f4d3c470ed2f32290ff1a6e2cc7c2c97f7847/products/public-websites/home-page/new-mobile-header/product-outline.md) for the **new mobile header**, with the intention of phasing out a better mobile navigation experience. 

## Acceptance Criteria
- [x] #10097
  - include caveats, challenges, and how to troubleshoot
  - [new-mobile-header directory from former PW team](https://github.com/department-of-veterans-affairs/va.gov-team/tree/5e0f4d3c470ed2f32290ff1a6e2cc7c2c97f7847/products/public-websites/home-page/new-mobile-header)
- [x] Include in documentation: [visualization of header code flow (Mural)](https://app.mural.co/t/friendsfromthecity8869/m/friendsfromthecity8869/1660149304804/1c40c67dd41f56cea5acdee9fef3a1de5423b0fc?sender=u38c7b8ac21f6cf2c1bd04203)
- [ ] Have at least 2 front-end developers to review and approve docs before merging PR: https://github.com/department-of-veterans-affairs/va.gov-team/pull/45662

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by allisonlu** [comment]
PR opened on `va.gov-team` repo: 

https://github.com/department-of-veterans-affairs/va.gov-team/pull/45662

since documentation is low-risk work, i'll be coming back and iterating/updating this when i come across new information

**Comment by wesrowe** [comment]
@dawnpruitt, I just added the Unplanned work label to this – it was created mid-sprint, so that label should have been there. (Jill and I both missed it till now.) It looks like it's carrying over to s65.

@allisonlu, can you please...
- Use the checkboxes on the ACs to clarify status. It says to run by 2 FE devs, I can't tell if you think the PR process will cover that AC.
- Edit the ACs to make sure they're clear and match the work you're delivering. For example, the 2nd AC suggests that one deliverable would be a Mural board. It would be clearer if that had its own checkbox. OR, if further additions to the mural you started previously are not required, link out to it in that AC. And you could reword the AC to something like "ensure that the documentation aligns with this Mural board."

**Comment by allisonlu** [comment]
PR merged! https://github.com/department-of-veterans-affairs/va.gov-team/pull/45662
