### ISSUE TITLE
Assess impact on documentation/KB/training

### ISSUE THREAD

**Issue by dsinla** [department-of-veterans-affairs/va.gov-cms#10058]
The change represented by #9357 is a new CMS design showing facility hours when "use facility's hours" is selected. 

**1. Describe the change from the perspective of VA employees, in plain language. What is the employee going to experience with this change?**
When editors are adding or changing hours for a non-clinical service location, they will see radio buttons instead of a dropdown list.

**2. Explain why the change is necessary from a CMS/platform and project goal perspective. Link to screenshots if that helps tell the story.**
Editors need a clearer way to show facility hours for their locations.

![image](https://user-images.githubusercontent.com/92043982/182917890-4704e7ab-a8a4-45ef-a98f-82cd6f2c33a1.png)

![image](https://user-images.githubusercontent.com/92043982/182917984-83452062-5a06-448b-828e-e650085bacd9.png)

**3. Select the role(s) impacted by the change.**
- [ ] All CMS users
- [ ] All CMS editors
- [ ] Vet Center editor
- [x] VA Medical Center editor
- [ ] VA Outreach Hub editor
- [ ] VA Benefits Hub editor
- [ ] Campaign landing page editor
- [ ] VA Resources and Support editor
- [ ] Offices editor
- [ ] Supporting roles such as CMS account admin, Facilities or Public websites team member

**4. How will success be measured for this change?**
- [x] No help desk support is needed, as measured through help desk tickets
- [ ] The content adheres to VA policies and standards for VA.gov, as measured through a dashboard tool and/or audit

**5. Does the change require new or updated:**
- [ ] Knowledge Base article(s) - none
- [ ] Training video(s) - none
- [ ] CMS UI support
- [ ] Announcement block

**6. Will the change be tested with users before release?**
- [ ] Yes
- [x] No

**7. Are there any known dependencies?**
Design review passed/accepted

**Comment by ContentBrewmaster** [comment]
Completed assessment Aug. 10, 2022. No evidence of this change impacting KB articles or training videos.
