### ISSUE TITLE
DSN: Change management preliminary research for VBA MVP

### ISSUE THREAD

**Issue by ContentBrewmaster** [department-of-veterans-affairs/va.gov-cms#10052]
As part of epic #[10276](https://app.zenhub.com/workspaces/vagov-cms-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/10276), we will conduct change management research with OCTO-DE and VBA staff to understand the:
- VBA stakeholder ecosystem
- Existing process issues when editors create facility content
- Current training process for new editors
- Impact of the introduction of Drupal CMS on day-to-day work among MVP editors
 
## Acceptance Criteria
- [x] Interview with Product Owner
- [x] Develop questions for VBA contacts in Office of Strategic Engagement
- [x] Interviews with VBA Office of Strategic Engagement contacts

**Comment by ContentBrewmaster** [comment]
Interview completed with Tanekwa Bournes Aug. 11. Interview scheduled with her colleague Kenyonna Power Aug. 15.

**Comment by RWEagans** [comment]
@ContentBrewmaster @dsinla Shall we mark this as Blocked for the Sprint Report? Waiting on contacts?

**Comment by ContentBrewmaster** [comment]
@RWEagans I put 2 sprints on this one (not sure if that's correct) in hopes I get interviews with all locations by Aug. 28.

**Comment by ContentBrewmaster** [comment]
@dsinla @RWEagans reassigning this issue to the new epic 10276.

**Comment by ContentBrewmaster** [comment]
@dsinla trying to link this to epic 10276 but not having any luck. Can you help?

**Comment by ContentBrewmaster** [comment]
Added "preliminary" to issue title to indicate further CM research will be conducted during MVP.

**Comment by ContentBrewmaster** [comment]
Interviews completed with VBA Office of Strategic Engagement:
- August 11, 2022 - Tanekwa Bournes
- August 17, 2022 - Kenyonna Power
