### ISSUE TITLE
Refactor VAMC product to use 6 content listing pages

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#1005]

**Comment by cmaeng** [comment]
@ethanteague Would be good to have Gibran to learn this process too yes? I'll reach out to Michelle Middaugh to help coordinate.

**Comment by brangi** [comment]
@mmiddaugh - can we create a detailed issue on - https://github.com/department-of-veterans-affairs/vets.gov-team/issues or our black-log zenhub regarding this.

**Comment by kevwalsh** [comment]
I just moved #1216 to a Preview epic, so we can close this.
