### ISSUE TITLE
Discovery: FE Alerts and analytic event triggers when PDF downloads fail

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#10061]
## Description

In #10042, Daniel's investigation into GA events cast doubt on the validity of our GA (Google Analytics) events. 

Background on GA: The GA event Wes is using to identify PDF download issues tracks an Alert in the ui. GA event: `Navigation - Alert Box - Link Click - error - This form link isn’t working - (not set) - email the forms managers`. Over time, spikes in this signal correspond anecdotally to VBA Forms Managers receiving emails from Veterans that a PDF download failed. We suspect that the Alert provides a way to email Forms managers, but need to verify.

GA provides the Form Detail pages where this event fired, and about 1/3 of them were from the subdomain `www.va.gov`, which he verified is an S3 bucket where such failures are extremely improbable. 

### Questions to investigate on the FE:

On Forms Detail pages:
- What does the UI Alert tracked by the GA event above actually look like?
- Does the Alert UI provide an "email someone" link/button that might be generating the emails to Forms Managers at VBA?
  - If so, how is the email address populated? (Hard-code, API payload, ...)
- How is the Alert triggered? Is that trigger reliable? (i.e., is it possible Vets are getting a false-positive that PDF is not available when it really is?)
- Does the GA event seem to be a reliable indicator that the Alert was displayed? Anything sketchy about the trigger?

On the [Find-a-form](va.gov/find-forms/) page (ie, list view), which also offers PDF Download links:
- Is there error handling code there? What does it trigger a UI change? 
- Do you see evidence of GA events being triggered on download failure? (and what is it)
- Are the answers to the above questions about detail pages different for this search page?

API Calls to investigate:

- Ask Steve: how does FE talk to Lighthouse? Passthru thru platform, just to get API keys added to headers?
- The spike in failures on 8/8/22, documented in #10096, was caused by a Forms API call that seemed to happen when the user clicks the Download link – which seems like weird timing for an API call.
  - Is the Forms API really getting called when a user clicks the download link? (And at which step?)

Monitoring setup:
Are key interactions being logged to sentry on failure? on success?
- Form Search page 
  - Forms API call (failure displays a red Alert component)
  - PDF download click
- Form Detail page
  - PDF download click
  - API failure on form download (we know failure is tracked in Sentry)

## Acceptance Criteria
- [x] Add screenshots to the [Mural](https://app.mural.co/invitation/mural/vagov6717/1659133365244?sender=u907f83e01e35bb04de6f8139&key=20990535-6902-47ad-9b45-60ec1f70d7cc) where we're tracking forms stuff
- [ ] Answer the questions carefully in this ticket 
- [ ] Make recommendations for improving monitoring for real-time alerts via Sentry
- [ ] Make recommendations for FE code/API-call changes to reduce Veteran-facing issues (e.g., removing extraneous API calls)

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by dsasser** [comment]
Follow up tickets created for this discovery work:
#10235
#10236
#10237
#10239

**Comment by dsasser** [comment]
Mural link with discovery findings: https://app.mural.co/t/vagov6717/m/vagov6717/1660150431569/27c80eaeeaedfd88c80322ae177b68c503345ba9?sender=u2cc9d7c4c6c0dea143b21411

Image for those unable to access Mural:
![VACMS-10061 - Discovery Form FE Workflow](https://user-images.githubusercontent.com/221539/184456006-212cd9b3-b74a-407d-9c51-346f11f566d2.png)

**Comment by jilladams** [comment]
@dsasser 2 follow up items on this: 
1. The modal has a fallback mode that points veterans to email Forms managers when it fails. Can we add that? 
2. The modal shows once per N (we think 24h) - can we add that too, or a guess about it?
