### ISSUE TITLE
Next-build server running per Tugboat environment

### ISSUE THREAD

**Issue by jkalexander7** [department-of-veterans-affairs/va.gov-cms#10068]
## Description
Tugboat CMS instances will need a next-build 'dev' server running in order to provide preview to the CMS. Note that "dev" in this context does not mean the dev environment, i.e. dev.cms.va.gov, but rather, a running next-build server running in 'dev' mode (`yarn dev`) that is available to provide preview of next-build output to the CMS. 

## Implementation details
The server must be available at a secure URL. next-build itself is responsible for starting itself as a secure server.

The CMS needs to be able to either construct the URL to the next-build preview server, or it needs to be provided that URL via an environment variable.

Preview servers should refresh according to the rules of the given environment. IOW:

* Tugboat preview servers should refresh on a nightly basis, along with the nightly rebuild process.

## Acceptance Criteria
- [ ] A next-build dev server is available at a secure domain for each environment
- [ ] The base url/domain is either known or can be provided to the corresponding CMS environment. 
- [ ] Environment variables are added to next-build in accordance to the environment it is running in

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [x] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by tjheffner** [comment]
This is complete as of #15936
