### ISSUE TITLE
[cms-ci][yaml-tests] Upstream tracking - Post multiple comments to GitHub when limit is reached 

### ISSUE THREAD

**Issue by ElijahLynn** [department-of-veterans-affairs/va.gov-cms#1006]
I opened this upstream issue for "Post multiple comments to GitHub when limit is reached"
https://github.com/provision-ops/yaml-tests/issues/52

**Comment by ElijahLynn** [comment]
And/or once we enable the "fail_fast" option in yaml-tests, we should consider just posting the tail, most recent log so we have a better chance of getting the full error in the comment.

**Comment by oksana-c** [comment]
this may be deprecated based on outcomes of #3303.

linking to Drupal 9 #1950 epic to keep track of.

**Comment by ElijahLynn** [comment]
Let's icebox this until we all regroup and discuss our overall testing architecture in https://github.com/department-of-veterans-affairs/va.gov-cms/issues/4109.

**Comment by acrollet** [comment]
closed in favor of go-task.
