### ISSUE TITLE
Create CMS Design System Style Guide

### ISSUE THREAD

**Issue by EWashb** [department-of-veterans-affairs/va.gov-cms#10064]
## Background

In an effort to encourage ease of use of the CMS design system, a basic style guide for the system should be created as a quick reference for product teams. This guide may be iterated on as we complete efforts for the #9672 
## Acceptance Criteria

- [x] basic design system components and styles (colors, padding, spacing, etc.) are captured and added to CMS design system documentation
- [x] Automated updates for token colors and fonts
- [x] Style guide is added to CMS Design System Documentation https://va-gov.atlassian.net/wiki/spaces/VAGOV/pages/edit-v2/1778843680

**Comment by dawnpruitt** [comment]
@cjterdi would you please point this? Thanks!
