### ISSUE TITLE
Create accessible error state for CMS fields with character limits

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#10072]
## Description
Within the CMS on the edit screens, fields that have a character limit enabled have a red indicator when the editor goes over the limit. This red color is used both on the border of the field and in the character count below the field.  In the character count text, the red (Hex ff0000) does not pass WCAG 2.0 AA color contrast requirements against the white background.

NOTE: The red border does pass the necessary contrast ratio requirements, it is only the text that must be updated.

## Screenshot
![image](https://user-images.githubusercontent.com/106678594/182946157-fc4fc87c-9074-4bf3-8637-b4367a8089f0.png)

## Accessibility Standard

WCAG version 2.0 AA, [Criterion 1.4.3](https://www.w3.org/WAI/WCAG21/Understanding/contrast-minimum.html)

## Acceptance Criteria
- [x] Determine if the red border and the red character count should both change to Red Darker (Hex 981b1e) or just the character count
- [x] Confirm field error state is documented correctly in Design System
- [x] Technical review for updating the color to Red Darker
- [x] Implementation ticket is created

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by EWashb** [comment]
@dawnpruitt this is one that we won't have capacity to complete this sprint due to PTEMS transition

**Comment by cjterdi** [comment]
- Change the error text color to B20D01 (red-dark) meets text contrast 7.11:1
- Keep the error border color E31C3D (red-bright) meets contrast for objects 4.66:1

**Comment by laflannery** [comment]
Implementation ticket created: #10865
