### ISSUE TITLE
PW Team chartering

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#10073]
In Sprint 65, PW team will charter.

**Comment by wesrowe** [comment]
BLOCKED – We decided to delay this activity since PTEMS is disrupting the team configuration again. Revisit in October.

**Comment by jilladams** [comment]
I think we can do this now! Will reboot with Dotti.

**Comment by wesrowe** [comment]
@jilladams, can this be closed?

**Comment by wesrowe** [comment]
Accomplished at on-site in DC, week of Jan 9, 2023.
