### ISSUE TITLE
Include fields in VBA migration

### ISSUE THREAD

**Issue by dsinla** [department-of-veterans-affairs/va.gov-cms#10087]
## Description
Include fields in VBA migration

from Dave C:

Hi David - can we add an issue to the Facilities backlog to include in the current VBA migration into the VBA facility content type:
- Address
- Phone number
- Hours
- 
- 
- ## Acceptance Criteria
- [ ] Testable_Outcome_X
- [ ] Testable_Outcome_Y
- [ ] Testable_Outcome_Z
- [ ] Requires design review

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by dsinla** [comment]
Closed as duplicate to VBA LH audit ticket

**Comment by davidmpickett** [comment]
Duplicate of https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10212
