### ISSUE TITLE
Write MVP UI copy for node links report

### ISSUE THREAD

**Issue by rachel-kauff** [department-of-veterans-affairs/va.gov-cms#1008]
## Description
As a content editor concerned about broken links, i want to know if any links in my content are redirected to a final destination, so that i can point those links to their final destination.
---
Related to Swirt's task Node Links Report -- #844 & #845 . This task is to stub out some MVP copy to use in the contrib module. I will add another epic to give it more holistic research eyeballs, as the whole user experience for this could use some more thought. 

## Acceptance Criteria
* Testable_Outcome_X
* Testable_Outcome_Y
* Testable_Outcome_Z

## Labels
- [/] Issue type (red) (defaults to task)
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [ ] CMS objective (orange)
- [x ] CMS-supported product (black)

## Artifacts
[Node Links report edited copy in Mural](https://app.mural.co/t/vagov6717/m/vagov6717/1582047974352/d8729998a7a3ea6cdd6aae90b83305f46bfa2483)

**Comment by rachel-kauff** [comment]
@swirtSJW I attached my edits in the "artifacts" section. Am curious to hear what you think about the placement of the node label.

**Comment by swirtSJW** [comment]
@rachel-kauff   I really like what you have created in artifacts.   Those are great improvements.  Thank you so much for putting these together.

**Comment by swirtSJW** [comment]
@rachel-kauff I can implement them pretty easily.  Testing is a little more problematic as this is a contrib module.

All the changes make sense and I have only one question related to the suggestion for making them collapsible.  What is it that we hope to achieve by making them collapsible?   I can make them collapsible easily enough, but then comes the question of persistence.  If it remembers my personal preference to collapse them, then I am likely to miss something on the next node I edit.   If it does not remember my preference, then it is kind of a repetitive workflow.

**Comment by rachel-kauff** [comment]
@swirtSJW cc: @kevwalsh Great question, which surely bears some more thought and user testing, and those are really good points about persistence. 

The thought behind making the messages collapsible is that in many cases, I'd expect there to be a lot of messages to scroll through in order to get to the content form.  If scrolling though a lot of messages annoys content editors, I expect it would actually make them less likely to pay attention to what they need to fix. Making the messages collapsible makes the screen more visually dense, and we've heard in testing that content editors prefer dense screens.

For the collapsible feature to be helpful, I think it would need to be something like:

- Default to expanded notices. After the user chooses to collapse them, I assume that persistently collapsed notices wouldn't necessarily prevent the warning from functioning if  the warning titles, colors, and icons remain visible (e.g. "7 broken links, 3 redirected links, 2 untested links"). I'll try to sketch out what that would look like in the mural.
- Editors would still have the option to expand the warning to get more information about the message or to see which links are affected

@jordanamello May also be interested in some of these problems too.

**Comment by rachel-kauff** [comment]
Added some ideas to the MURAL about what collapsible messages would look like
https://app.mural.co/t/vagov6717/m/vagov6717/1582047974352/d8729998a7a3ea6cdd6aae90b83305f46bfa2483

**Comment by swirtSJW** [comment]
I just created two issues on Drupal.org
1. Rewordng  https://www.drupal.org/project/node_link_report/issues/3116017
2. Making elements collapsible https://www.drupal.org/project/node_link_report/issues/3116023

**Comment by swirtSJW** [comment]
These issues have been resolved  ^^
