### ISSUE TITLE
Incorrectly titled VBA facility 

### ISSUE THREAD

**Issue by davidmpickett** [department-of-veterans-affairs/va.gov-cms#10098]
[This VBA facility](https://www.va.gov/find-locations/facility/vba_310h) seems to be incorrectly titled. It is called "Pre-Discharge Site at Joint Base McGuire-Dix-Lakehurst" but the address puts it on the Mountain Home Air Force Base.

There's also an actual [Pre-Discharge Site at Joint Base McGuire-Dix-Lakehurst](https://www.va.gov/find-locations/facility/vba_310b)

**Comment by dsinla** [comment]
The likely offending misnamed facility is vba_310h
@dsinla  Will talk to @davidconlon to update the source.

**Comment by davidconlon** [comment]
@dsinla @davidmpickett I stumbled across this issue today and was able to update it.
This should not have waited nearly 3 months to be escalated or identified as an issue.
