### ISSUE TITLE
Create a  directory and document prior knowledge and history of the header and injection process in

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#10097]

**Comment by allisonlu** [comment]
not sure if this issue was automatically created, but wanted to make note that this is in PR in the `va.gov-team` repo:

https://github.com/department-of-veterans-affairs/va.gov-team/pull/45662

**Comment by jilladams** [comment]
AMAZING. This was a placeholder for me to help migrate notes into github, so nice work deduping effort here, @allisonlu . My only question is whether "new mobile header" is accurate for all the notes there, since the injection using teamsites doesn't only apply to mobile. (Or does it?, and I am just still wrapping my head around it?)

**Comment by jilladams** [comment]
Injected header / footer documentation: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/public-websites#header--footer-injection, which further points out to the deeper docs for injecting / testing in [Proxy-rewrite README](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/proxy-rewrite/README.md) with implementation & testing details.

Header documentation: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/public-websites/header. (from Allison's PR above)
