### ISSUE TITLE
Generate copy for Description field helper text of newly-added Q&A content type 

### ISSUE THREAD

**Issue by fmccaf1** [department-of-veterans-affairs/va.gov-cms#10108]
## Description
When Christia enabled the Q&A content type for R&S pages, she added a Description field after the Title field (an AC for her work). Design review found the Description field lacked necessary direction to editors. Helper text should be added to give editors the direction they may need to know how to fill out field.

## Acceptance Criteria
- [x] [Review UX writing style guide](https://va-gov.atlassian.net/wiki/spaces/VAGOV/pages/1761312769/UX+writing)
- [x] Draft copy for Description helper text
- [x] Review copy with Suzanne
- [x] Handoff to Jill

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by fmccaf1** [comment]
These screenshots show a helper text pattern for this type of rich text field:

![Screen Shot 2022-08-10 at 9 47 31 AM](https://user-images.githubusercontent.com/106624475/183947581-67a23c19-2745-4eac-aa9d-ca9f5b212a57.png)
![Screen Shot 2022-08-10 at 9 46 31 AM](https://user-images.githubusercontent.com/106624475/183947585-0530bb04-4505-471c-8cea-3ad97e5aed2b.png)

**Comment by fmccaf1** [comment]
To follow above pattern, would recommend the following: 

- Change Section Header to "Section title" (make req'd)
- Change Description to "Section introduction" (make req'd)
- Add helper text under "Section introduction": "This is displayed directly beneath the section title, directly before the Q&A. This text should help a user figure out whether the information on this page is relevant to them and should be written in the 2nd person."

Screenshot of the editor experience created by [ticket 9737](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9737)
![Q A Group](https://user-images.githubusercontent.com/106624475/183950478-5638ef2e-f44d-4eaa-972a-6bba2c5ab632.png)

**Comment by fmccaf1** [comment]
@jilladams this is ready for hand-off to you.

**Comment by jilladams** [comment]
Ack. cc @chri5tia as FYI: 
1. Make "Section Header" req'd --iirc correctly from the sync with Danielle on how these are typically used, we don't want to require this, as Q&As are often also included on FAQ where section heads aren't used / necessary.  That isn't captured in our Notes doc, so: @wesrowe / @chri5tia do you recall differently? We can re-confirm with Danielle if we need. 
2. Change Description to "Section introduction" - noted, will add to a new implementation ticket
3. Add helper text under "Section introduction": "Add a summary that helps the user figure out whether this section is relevant to them. This should be written in the 2nd person." - nice, same

**Comment by jilladams** [comment]
Closing ticket. We can make any changes re: Section Header requirement etc on #10147 as needed.
