### ISSUE TITLE
Incorrect focus order on 3 column View screens in CMS

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#10119]
## Description
**Still an issue in D10**

On the View screens, the main body content (`<main>`) and the left column content (`<aside>`) are using the CSS order property to visually switch the display of these elements.  Within the DOM, the `<main>` comes first but visually this comes second.  This is causing the focus order of the page to be confusing and unexpected.

## Screenshot
![image](https://user-images.githubusercontent.com/106678594/183745937-4cee747a-2a97-4f12-a768-115ed3815945.png)

## Accessibility Standard

WCAG version 2.0 A, [Criterion 2.4.3](https://www.w3.org/WAI/WCAG21/Understanding/focus-order.html)

## Acceptance Criteria
- [x] Tab order of columns match visual presentation
- [ ] Accessibility Review

**Comment by ndouglas** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Accessibility-Issues-62b4be010177900017e82254/issues/department-of-veterans-affairs/va.gov-cms/10119?planning-poker) with Zenhub @edmund-dunn @tonytaylor
