### ISSUE TITLE
Heading levels incorrect for accordion web component

### ISSUE THREAD

**Issue by adamwhitlock1** [department-of-veterans-affairs/va.gov-cms#10126]
## Feedback framework

- **❗️ Must** for if the feedback must be applied 
- **⚠️ Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Definition of done

1. Review and acknowledge feedback.
1. Fix and/or document decisions made.
1. Accessibility specialist will close ticket after reviewing documented decisions / validating fix.

## Point of Contact

**VFS Point of Contact:** Josh or Adam

## User Story or Problem Statement

As a screen reader user, I expect heading levels to be consistent with the surrounding content when accessing accordions.

## Details

The original issue that brought this to light is here:
https://github.com/department-of-veterans-affairs/va.gov-team/issues/27619

There needs to be a way to ensure that accordion headings maintain the correct hierarchy level in relation to their surrounding content. 
![heading level mismatch example](https://user-images.githubusercontent.com/14154792/127920821-22d4d1e7-d86f-40bc-a5c9-8bc4435d330b.png)

## Related tickets
* [508 Discovery: can Accordion components be passed the appropriate heading level (accessibility) #10136](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10136) - DONE
* [508 Spike – Audit FE codebase for all accordion components #10380](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10380)
* [Content Audit: CMS instances of accordion #10486](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10486)

## Acceptance Criteria

- [ ] Accordions use the correct heading level

## Steps to Recreate

1. View accordions on https://www.va.gov/health-care/covid-19-vaccine/
2. Inspect accordion heading levels

## Proposed Solution

Detect the previous heading level in the document and set accordion headings based on this level.

**Comment by wesrowe** [comment]
Created issue #10136 for refinement

**Comment by jilladams** [comment]
FIndings complete on #10136 : 
> Accordion items default to <h2> and can be changed by [choosing the heading level and adding a slot="headline" attribute](https://github.com/department-of-veterans-affairs/content-build/blob/33d97c363c2d9f3d7296a4ad9a52431cded852ca/src/site/facilities/facility_health_service.drupal.liquid#L11-L13).

Assigning to @jtmst for estimate based on discovery.

**Comment by jilladams** [comment]
^ Filed https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10486 for CMS-level audit, so we can confirm the fix against existing content in prod, a la same work for Tables.

**Comment by jilladams** [comment]
Discovery headlines: 
- No accordion markup in the CMS, so no CMS changes. 
- File changes required in content-build, vets-website
- #10526 tracks implementation
