### ISSUE TITLE
Broken ARIA references within editorial screens of the CMS

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#10134]
## Description
**Still an issue in D10**

Within the edit screens of the CMS, there are multiple components that have an `aria-describedby` attribute with a value that does not corresponds to an ID anywhere on the page.

## Additional Context
List of components where this was found (may not be the full list of all tables within the CMS):

~~All Edit screen: Editorial workflow component
News Release Edit screen: Location component
News Release Edit screen: Media Contacts component
News Release Edit screen: Full Text of Press Release component
Story Edit screen: Body Text component
VAMC System Health Service Edit screen: VAMC system service description component
VAMC System Medical records Office Edit screen: Mail Address component
VAMC Detail Page Edit screen: Featured Content component
VAMC Detail Page Edit screen: Related Links component
VAMC System Banner Alert with Situation Updates Edit screen: Situation Updates component
VAMC System Banner Alert with Situation Updates Edit screen: Situation Information component
VAMC System Operating Status Edit screen: Facility Operating statuses component
VAMC System Operating Status Edit screen: Local emergency resources directory component
VAMC System Operating Status Edit screen: Patient resources component
VAMC System Operating Status Edit screen: Local emergency resources component
Vet Center - Locations List Edit screen: Display additional mobile vet centers
Vet Center - Locations List Edit screen: Nearby Vet Centers and Outstations
FAQs Page Edit Screen: Q&As
Image List Edit Screen: Phone Number within Contact Information
Resources and Support Detail Page Edit Screen: Main Content~~

~~**Checklist Edit Screen:**
Page Introduction
Calls to Action
Related Information
Other Categories where people may look for this article
**FAQs Page Edit Screen:**
Page Introduction
Calls to Action
Related Information
Other Categories where people may look for this article
**Image List Edit Screen:**
Page Introduction
Calls to Action
Related Information
Other Categories where people may look for this article
**Resources and Support Detail Page Edit Screen:**
Page Introduction
Calls to Action
Related Information
Other Categories where people may look for this article
**Step-by-Step Edit Screen:**
Page Introduction
Calls to Action
Related Information
Other Categories where people may look for this article~~

## Screenshot
![image](https://user-images.githubusercontent.com/106678594/183938825-6658955b-2d6f-4ae7-a17c-88f63792fe6f.png)

## Accessibility Standard

WCAG version 2.0 A, [Criterion 1.3.1](https://www.w3.org/WAI/WCAG21/Understanding/info-and-relationships.html)

## Acceptance Criteria
- [ ] Determine what the original intention of the ARIA reference was/is.  What additional context was it providing? Do we still need to provide that information in some other way?
- [ ] Interactive Designer to determine display of additional information if it is determined this is needed
- [ ] Update attribute based on above determination (remove attribute or update it)
- [ ] Accessibility review

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by ndouglas** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Accessibility-Issues-62b4be010177900017e82254/issues/department-of-veterans-affairs/va.gov-cms/10134?planning-poker) with Zenhub @edmund-dunn @tonytaylor

**Comment by edmund-dunn** [comment]
@ndouglas This one will need to be split out, products as appropriate to the associated teams. Others into a more organized fashion as we can group them if that is at all possible.

**Comment by ndouglas** [comment]
@edmund-dunn makes sense to me.

**Comment by laflannery** [comment]
Should I be creating those tickets?

**Comment by ndouglas** [comment]
@laflannery If you could, I'd massively appreciate it.
