### ISSUE TITLE
Run crisis number update scripts

### ISSUE THREAD

**Issue by JayDarnell** [department-of-veterans-affairs/va.gov-cms#10141]
## Description

The following scripts need to be run on production. These scripts will replace all instances of the old 800 crisis number with the new 988 number. **Timing for these scripts is important**. We need to be sure proper communications have been sent beforehand. Please coordinate with Denise Eisner.

## Acceptance Criteria
- [x] Run command: `drush scr ./scripts/content/VACMS-9714-paragraphs-crisis-to-988.php`
   - Copy and past the tail end of terminal output so we get the counts. 
- [x] Run command: `drush scr ./scripts/content/VACMS-9714-vamc-detail-page-crisis-to-988.php`
   - Copy and past the tail end of terminal output so we get the counts. 
- [x] Run command: `drush scr ./scripts/content/VACMS-9714-vamc-system-operating-status-crisis-to-988.php`
   - Copy and past the tail end of terminal output so we get the counts. 
   
### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [x] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by ElijahLynn** [comment]
I'm going to run these today. l am doing them on STAGING first. How can I verify they worked?

**Comment by ElijahLynn** [comment]
I ran this on STAGING first and all three completed successfully, I ran a second time to make sure and there were "Total update - 0" for all three. I then ran on PROD the same way and saved all output to a .txt file, attached. 
[tmux-1-3-1-20220810T130618.log](https://github.com/department-of-veterans-affairs/va.gov-cms/files/9303714/tmux-1-3-1-20220810T130618.log)
