### ISSUE TITLE
Q&A Group: update field names / descriptions

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#10147]
## Description
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10108

Within Q&A Groups:
1. Within Q&A Group, update label for "Section Header" to "Header"
2. Change "Description" to "Introduction" as it appears in the CMS UI. (Not required to change the machine name.)
3. Add helper text under "Introduction": `Add a summary that helps the user figure out whether this information is relevant to them. This should be written in the 2nd person.`

4. In Content Block > Other > Q&A Group description: update 
`For content formatted as a series of questions and answers in "FAQ - multiple Q&A" content type` to 
`Create a new group of existing Q&As`
![image](https://user-images.githubusercontent.com/5752113/184156127-20c4b541-21d8-4af4-9ee4-f9536f12ef04.png)

![image](https://user-images.githubusercontent.com/5752113/184156611-267508dc-f7b8-4ae9-baf9-9333b8558edd.png)

3. Within Q&A Group ui, update the description above Place Q&As button, to say `Select from existing Q&As. Drag and drop selected Q&As to re-order.`
![image](https://user-images.githubusercontent.com/5752113/184156914-3eff4b4b-f896-47a0-af3a-f6d13a178e8b.png)

## Acceptance Criteria
- [X] Draft copy & get it approved - @fmccaf1  -- copy is added to ticket body
- [x] Copy appears within CMS UI - @chri5tia 

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [X] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by jilladams** [comment]
Add;l considerations to cover in this ticket: https://github.com/department-of-veterans-affairs/va.gov-cms/pull/9746#issuecomment-1212063678

**Comment by jilladams** [comment]
Assigning to @fmccaf1 to follow up with Suzanne re: added copy here

**Comment by fmccaf1** [comment]
Just completed working with Suzanne and have received her sign-off

**Comment by jilladams** [comment]
This ticket was written up as a 2 parter -- Florence to get the copy, and Christia to implement. Florence added copy to ticket body -- I'm gonna reopen for the implementation part and update the ACs to make that clear.

**Comment by chri5tia** [comment]
PR: https://github.com/department-of-veterans-affairs/va.gov-cms/pull/10334
