### ISSUE TITLE
CMS: Lovell Menu display bifurcation

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#10167]
THis one needs some discussion about what the experience should be.
possiblities:
~A - one menu that shows all, with color codes for both, tricare and va~
B - Different display for each.  (filtering out VA or TRICARE based on setting within the menu item

Based on the section for the node we are on, filter the menu and only show the items that are currently applicable. 
- Tricare section only shows other tricare menu items or items for both
- VA section only shows other VA menu items or items for both
- When we are in one section, prepend a menu item to the top of the menu to switch to the other section

**Comment by dsinla** [comment]
Recommend only seeing the section you're in. Discouraging color coding

Do we want sitewide CMS to chime in? There's nothing reusable - Lovell only, very one-off specific.  If Lovell (shenanigans)
Is there an opportunity to reuse some of this?
