### ISSUE TITLE
DSN: Create Lovell UI artifacts for collab cycle Midpoint Review 

### ISSUE THREAD

**Issue by davidmpickett** [department-of-veterans-affairs/va.gov-cms#10163]
## Description
The Collab Cycle Midpoint Review has been scheduled: Thursday Aug 25, 2022 ⋅ 10:30am – 11am (Pacific Time - Los Angeles)

The associated ticket: 
https://github.com/department-of-veterans-affairs/va.gov-team/issues/45628

## Acceptance Criteria
- [x] Identify artifacts to be delivered
- [ ] Create design proposal 
- [x] Attach artifacts to ticket or provide links two days prior to review 

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by jcklpe** [comment]
Link to previous ticket here: [link](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9846)

**Comment by jcklpe** [comment]
New updated previous design artifact:

![](https://user-images.githubusercontent.com/9451726/184956674-c853ad07-1759-44c6-b99e-21daa67cb7ec.png)

**Comment by jcklpe** [comment]
Our recommended solution:   
 

![](https://user-images.githubusercontent.com/9451726/183702690-ac248d13-9ec6-4b04-b76b-cb56a773bc5f.png)

**Comment by davidmpickett** [comment]
Artifacts were attached to https://github.com/department-of-veterans-affairs/va.gov-team/issues/45628
