### ISSUE TITLE
Create research plan to evaluate content proofing usability

### ISSUE THREAD

**Issue by jordanamello** [department-of-veterans-affairs/va.gov-cms#1017]
## Description

Create Research Plan to evaluate content proofing usability

## Acceptance Criteria
- [x] GitHub repository created
- [ ] Research plan reviewed by CMS Design Pod
- [x] Research plan validated by Jeff Barnes

**Comment by kevwalsh** [comment]
Research plan: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/cms/authoring-experience/research/content-proofing-usability-study
