### ISSUE TITLE
FE: implement Lovell paths

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#10173]
When the two different paths for lovell va and lovell tricare have been defined and approved, the FE will implement building the right pages at the right path.

## ACs
- [ ] When a page is built for Lovell VA it has the starting path of ______.
- [ ] When a page is built for Lovell TRICARE it has the starting path of ______.

**Comment by RWEagans** [comment]
This has been completed
