### ISSUE TITLE
CMS: update page details block to account for Lovell

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#10171]
As an editor in the LOVELL system, I want to be able to see where my page lives if it is in two locations in the block block-entitymetadisplay
![image](https://user-images.githubusercontent.com/5752113/184225918-4403b5e1-e171-4cf1-b796-875880c61509.png)

## ACs
- [ ] When on a page with field_administration = Lovell fed health care, the block show separate FE links for VA and Tricare
Like this 
![image](https://user-images.githubusercontent.com/5752113/184226643-36cc9860-b146-4982-87d8-ec0adf43cdb4.png)
- [ ] When a page is only in Lovell tricare it should indicate TRICARE explicitly
- [ ] When the page is only in Lovell VA it should indicate Love VA explicitly

**Comment by dsinla** [comment]
@omahane  Is this a dupe of #10946 ?
