### ISSUE TITLE
CMS: implement lovell paths

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#10172]
When the two different paths for lovell va and lovell tricare have been defined and approved, the CMS will implement building the right pages at the right path.

## ACs
- [ ] When a page is built for Lovell VA  or Lovell Fed Health care, it has the starting path of ______.
- [ ] When a page is built for Lovell TRICARE it has the starting path of ______.

**Comment by dsinla** [comment]
Closing as accounted for in other Lovell tickets
