### ISSUE TITLE
Draft Research Plan & Conversation Guide for VBA Editor Research

### ISSUE THREAD

**Issue by davidmpickett** [department-of-veterans-affairs/va.gov-cms#10186]
### Research Questions

**VBA Editor Persona Questions**
- Number of potential editors (if each editor has a backup) and locations
- Reporting structure
  - Who they take direction from
- Level of understanding (high, medium, low) of web principles (accessibility, web writing, etc.)
  - This will relate to how hardened the content model is
- Other editor responsibilities and which take precedence, if any, over the website
- How editors view the purpose of the website in relation to other channels
- How work priorities are established and monitored
  - Estimated percentage of role that would be dedicated to the website
- Previous experience publishing web content
- Preferred way to learn how to use, or get support for, computer applications and tools at work
  - This will inform training approach
- Preferred way to get updates on changes or additions to the website CMS
  - This will inform change management approaches 

**Detailed VBA Facilities Content Questions for Editors**
- Is the service delivery the same across all locations nationally or locally nuanced? (What specifics would local editors want/need to adjust?)
- Is a list of Veteran Service Organizations (VSOs) located at that facility important?
- Are Events National? Local? Hybrid? And what is the maintenance load?
- Are Spotlights National? Local? Hybrid? And what is the maintenance load?
- Is a list of Veteran Service Organizations (VSOs) located at that facility important?
- Is there a need for timely situational updates related to things such as parking or COVID facility status? 
- Is there an easily identifiable Top Tasks for editors? Can we quantify: Here are the Top XX things I do most frequently when currently updating the site, these other tasks are much less frequent.

[WIP](https://docs.google.com/document/d/1EQGUSPccCNvNT1JN6p6x92tjCgh9Pkw6QNqEtB_P-iI/edit#) 
[Research folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/cms/research/VBA-discovery)

**Comment by ContentBrewmaster** [comment]
Sent links to draft research plan and conversation guide to @davidmpickett @jcklpe @dsinla @suzanne-gray for review by August 22.

**Comment by davidmpickett** [comment]
Due to VBA realignment yesterday, the work done on this ticket will be revisited at a future sprint when we are closer to starting editor research. Some of the work will be repurposed as part of https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10447
