### ISSUE TITLE
CMS Fields reset when creating new content of certain content types

### ISSUE THREAD

**Issue by omahane** [department-of-veterans-affairs/va.gov-cms#10184]
## Describe the defect
When **creating** content of the following content types, one or more fields is reset when clicking the triggering button.

| Content Type | Affected Field(s) | Triggering button |
| ------------- | ----------------- | ----------------- |
| VAMC Facility Health Service | Facility, VAMC system health service | Add new phone number, Add Service location |
| VAMC Facility Non-clinical Service | Facility | Add new phone number, Add new email address, Add another Service Location |
| Vet Center - Locations List | Vet Center | Select Mobile Vet Centers |
| Vet Center - Mobile Vet Center | Main Vet Center location |  Add media |
| Vet Center - Outstation | Main Vet Center location | Add media |

## To Reproduce
Steps to reproduce the behavior (general with examples):
1. Go to Create Content
2. Choose one of the above content types, e.g. _VAMC Facility Heath Service_
3. Choose a 'Section'
4. Select information for the affected field(s), e.g. _Facility_ and _VAMC system health service_
5. Click the triggering button, e.g. _Add a new phone number_

The affected fields should now be reset with the selected data removed.

## AC / Expected behavior
The affected fields should retain their selected values.

## Screenshots
![Screen Shot 2022-08-11 at 2 22 01 PM](https://user-images.githubusercontent.com/766573/184225086-47d0b7cc-df2f-4ff7-beeb-2aacb2f172d5.png)
![Screen Shot 2022-08-11 at 2 38 21 PM](https://user-images.githubusercontent.com/766573/184225110-7f0c68ca-e94a-4dfc-9c74-53b162bbea43.png)

## Desktop (please complete the following information if relevant, or delete)
 - OS: Mac
 - Browser: Chrome
 - Version: 103.0.5060

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Defect")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS workstream (orange) (not needed for bug tickets)
- [ ] CMS-supported product (black)

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by RWEagans** [comment]
Adding prefix
