### ISSUE TITLE
DSN: Conduct VBA Veteran research readout & document findings in research repo

### ISSUE THREAD

**Issue by davidmpickett** [department-of-veterans-affairs/va.gov-cms#10196]
## Description

**Crafting Recommendations**

Recommendations are key outputs of the research process. They connect your findings back to the product roadmap(s) and shape the experience of future users. Depending on the type of research conducted, recommendations might be narrowly focused on improving a specific interface component of your team's product, or they might have broad implications for multiple parts of the VA.gov ecosystem. Work with your Design team, Product Manager, & Product Owner to generate, refine, and categorize recommendations. PMs and POs also play a key role in socializing recomendations to other teams.

**Research Readout(s)**
- Work with PM & PO to determine audience(s) and meeting length(s)
- Default to a 30-min meeting with 20 min for presenting and 10 min for discussion
- [Research Presentation Template](https://docs.google.com/presentation/d/13G80avWGdY7tHU40PbP_l05W1yRpDr-opOk0u_AAhzQ/edit#slide=id.g892adcb623_0_141)
  - Consider slimming down this template based on your audience
  - Consider doing a pratice runthrough with Design Team or PM to ensure it flows
- After readout(s) with your immediate team(s) and stakeholder(s), consider presenting your research at Platform's weekly Design + Content + Research meeting
  - Message Naomi Marcussen on Slack to sign up

**Documenting Findings**
- Building off the Topline Report, fill out the [Research Findings Template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/sharing-research/research-findings-template.md) and add it to your Research Folder
- Once your findings are fully written up, make sure they are linked to from the relevant research repository
- Veteran-facing research: [How to add research to Platform Repo](https://github.com/department-of-veterans-affairs/va.gov-research-repository/issues/70)

**Destroying and Archiving Research Materials**
- Once your synthesis is complete, you should destroy any [session recordings](https://depo-platform-documentation.scrollhelp.site/research-design/recording-user-research-sessions) saved to your local machine
- Review your notes and synthesis materials to make sure they don't contain any PII. Then make sure they are added to your github Research Folder for archival purposes

## Acceptance Criteria
- [x] Craft recommendations
- [x] Conduct readout(s)
- [x] Document findings in Research Repo
- [ ] Destroy or archive research materials

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by davidmpickett** [comment]
FYI @jcklpe @dsinla @RWEagans 
@davidconlon has requested that the research findings template be complete as part of Sprint 69

**Comment by davidmpickett** [comment]
Dave C requested a follow up meeting, so this will definitely need sign off from him to be complete

**Comment by jcklpe** [comment]
We met and got feedback from Conlon again. I have scheduled a meeting for next week to discuss those changes and see if we can get sign off.

**Comment by jcklpe** [comment]
I don't know if this counts as done but I have performed the readout. I've received additional feedback from Conlon. I am not clear on what the plan going forward is supposed to be in terms of work.

**Comment by dawnpruitt** [comment]
Need to discuss details of resourcing with Program Manager and PO.

**Comment by dsinla** [comment]
Verify that we have PO approval, then @davidmpickett to update github

**Comment by dsinla** [comment]
Confirmed with @davidconlon 
Only step remains is placing in github/research library @davidmpickett

**Comment by davidmpickett** [comment]
Final readout deck uploaded to github:
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/regional-offices/research/2022-8-veteran-facing/VBA_research_readout.pptx
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/regional-offices/research/2022-8-veteran-facing/research-readout.pdf

**Comment by davidmpickett** [comment]
Research findings document in github has been updated: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/regional-offices/research/2022-8-veteran-facing/research-findings.md

**Comment by davidmpickett** [comment]
Findings added to research repository: https://github.com/department-of-veterans-affairs/va.gov-research-repository/issues/177

**Comment by davidmpickett** [comment]
@dsinla @dawn marking this as done!
