### ISSUE TITLE
DSN: Research Review Cycle prep for VBA Veteran research

### ISSUE THREAD

**Issue by davidmpickett** [department-of-veterans-affairs/va.gov-cms#10193]
**Acceptance Criteria**
- [x] Research plan and conversation guide are reviewed and approved by design team, PM & PO
- [x] Create tickets necessary for [research review process](https://depo-platform-documentation.scrollhelp.site/research-design/research-checklist#ResearchChecklist-2.Researchreview)
- [x] Make changes to research plan & conversation guide if needed
- [x] Once approved move on to Participant Recruitment

**Comment by jcklpe** [comment]
Ticket for research review can be found [here](https://github.com/department-of-veterans-affairs/va.gov-research-repository/issues/177).   
  
Research and Conversation guide can be found here: [https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/facilities/regional-offices/research/2022-8-veteran-facing](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/facilities/regional-offices/research/2022-8-veteran-facing)  
  
I will schedule a review with @davidconlon

**Comment by jcklpe** [comment]
Notes from Conlon meeting:

*   List out the different types of VBA facilities - be specific
*   Do they understand the difference between VBA facilities?
*   What was the benefit-related task they were trying to accomplish?
*   Veterans were able to accomplish the task at the facility?
    *   Did going physically to the facility allow them to accomplish their task?
    *   Was going to the facility required for the task?
*   Did they feel prepared for the visit? 
    *   Were they prepared?
*   Do they have a preference for doing this task in person or not?
*   Hypothesis - there are specific tasks that veterans prefer to do in-person
*   How did they travel to the facility?
*   What was the experience like getting to the appointment?
    *   Wayfinding within a building
*   We want representation within each of the regional districts
*   Urban, rural
*   Proximity to different offices
*   How did Veterans first learn about the facility they visited?

Action items that came out of the presentation to Conlon:

*    [ ]  Write a screener question for Perigean that lays out their eligibility based on recently visiting a regional/benefit office. Example: [https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/vet-centers/discovery/veteran-interviews/research-plan.md](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/vet-centers/discovery/veteran-interviews/research-plan.md)
*    [ ]  Use VA Recruitment checker to calculate secondary criteria for demographics: [https://docs.google.com/spreadsheets/d/1pq7TSHZonfpzAQBJj6B2geGHlNUwZEs4DzEvxcRgu0o/edit#gid=1440553662](https://docs.google.com/spreadsheets/d/1pq7TSHZonfpzAQBJj6B2geGHlNUwZEs4DzEvxcRgu0o/edit#gid=1440553662)
*   [ ] Add Conlon’s research questions
*   [ ] Rewrite hypothesis in a yes or no format

**Comment by jcklpe** [comment]
I have completed the revisions as per @davidconlon 's requests. Not sure if I close this story out @davidmpickett @dsinla but I can if that's the right thing to do.

**Comment by davidmpickett** [comment]
The ticket should stay open until @davidconlon  approves the updated documents

**Comment by davidmpickett** [comment]
Transferring assignment to me since I will be taking this over moving forward.

**Comment by davidmpickett** [comment]
Updated [Research Plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/regional-offices/research/2022-8-veteran-facing/research-plan.md) has been sent to Dave C for review

**Comment by davidmpickett** [comment]
Feedback from Dave C has been incorporated into research plan. Now switching attention to conversation guide.

**Comment by davidmpickett** [comment]
@dsinla Not sure if it warrants a ticket, but I leave it to you and Dave C to check with Tanekwa and Kenayana about their interest in observing some of these interviews.

**Comment by dsinla** [comment]
@davidmpickett Thanks! We'll bring it up in the next sync with Tanekwa, on Tues morning.

**Comment by davidmpickett** [comment]
Updated [Conversation Guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/regional-offices/research/2022-8-veteran-facing/conversation-guide.md) sent to PM & PO for approval

**Comment by davidmpickett** [comment]
Submitted to Platform for review

**Comment by davidmpickett** [comment]
Approved!

**Comment by dsinla** [comment]
@davidmpickett   OK that's a pretty quick turn-around!  Awesome!
