### ISSUE TITLE
Ignore *.md commits for CI and Deploys

### ISSUE THREAD

**Issue by ElijahLynn** [department-of-veterans-affairs/va.gov-cms#1019]
We should be able to push documentation changes without triggering tests to run for both CI PR environments and the CD to DEV/STAGING. 

- [ ] PR commits that are only *.md changes, are treated as a NOOP on DevShop (open upstream issue for the DevShop GitHub queue)
- [ ] Merged commits to master that are only *.md changes, are treated as a NOOP on BRD deploys, and do not trigger any builds or deploys. 

NOTE:
How do we handle this on PROD, because those commits won't have a passing commit status? e.g. 
1. Only deploy latest passing commit
1. Reach out to API and pass the commit

**Comment by ElijahLynn** [comment]
Ended up doing some work around this. The below _should_ work but isn't.

![image](https://user-images.githubusercontent.com/1504756/75924003-076e0480-5e1b-11ea-923c-746fe0672985.png)

We do have an example that is working here https://github.com/department-of-veterans-affairs/devops/blob/1d0c6b911f39e84581d52b4f644d4ffe02c4bb7a/ansible/deployment/config/jenkins-vetsgov/seed_job.groovy#L1037-L1041 on this job http://jenkins.vfs.va.gov/job/infrastructure/job/sshkeys/configure.

Not sure what is up yet.

**Comment by indytechcook** [comment]
I found a possible related issue on https://issues.jenkins-ci.org/browse/JENKINS-36836

> It is well known that you cannot use path exclusions when Git is configured to perform master-based polling, due to limitations in the Git network protocol. Would be solvable only by using a master repo cache the way the Mercurial plugin does, and in fact git already does for multibranch projects. I think this is already filed somewhere.

>Polling exclusions are not currently supported for multibranch projects under any circumstances. That is probably also already filed somewhere.

**Comment by ElijahLynn** [comment]
> I found a possible related issue on https://issues.jenkins-ci.org/browse/JENKINS-36836
I saw a comment in that issue that says:
> Path inclusions and exclusions (in a NON-MULTIBRANCH project) seem to work fine when there is a persistent workspace 

So, I noticed that the job that works, http://jenkins.vfs.va.gov/job/infrastructure/job/sshkeys/configure, doesn't run `cleanWs()` at the end of the pipeline run, in `ansible/Jenkinsfiles/infrastructure/sshkeys` (groovy file) and in our Jenkinsfile.cd we have:
https://github.com/department-of-veterans-affairs/va.gov-cms/blob/82637c5f7734afe0b987cc33cbf777014cbb2ad1/Jenkinsfile.cd#L76-L79

**Comment by ElijahLynn** [comment]
The working job, http://jenkins.vfs.va.gov/job/infrastructure/job/sshkeys/configure, is also using "GitHub hook trigger for GITScm polling" though it appears.

**Comment by indytechcook** [comment]
> Path inclusions and exclusions (in a NON-MULTIBRANCH project) seem to work fine when there is a persistent workspace

I saw this comment also, I also saw several comments in that issue and a related https://issues.jenkins-ci.org/browse/JENKINS-36195 saying it was all.  I'm testing now.

**Comment by indytechcook** [comment]
I tried a variety of different setups to try to get this to work.  The none of them worked even with removing the `cleanws`.  I set everything as close as possible to the working job and wasn't able to not trigger a job.

**Comment by ElijahLynn** [comment]
> I saw this comment also, I also saw several comments in that issue and a related https://issues.jenkins-ci.org/browse/JENKINS-36195 saying it was all.

I think something got truncated here, "saying it was all", did you mean to add more?

**Comment by ElijahLynn** [comment]
> I tried a variety of different setups to try to get this to work. The none of them worked even with removing the `cleanws`. I set everything as close as possible to the working job and wasn't able to not trigger a job.

Bummer, such a strange thing! I bet if we pair on this for an hour in real time we can figure it out together!

**Comment by ElijahLynn** [comment]
@indytechcook I know you tested removing the cleanWs() already. I would like to commit this change though for further testing of the ignore polling paths. https://github.com/department-of-veterans-affairs/va.gov-cms/pull/2720

**Comment by ElijahLynn** [comment]
We are going to need a way to mark commits as passed tests that are just docs changes. This might require making all the commit statuses as optional as just docs changes would never need to pass Behat tests for example.

**Comment by ElijahLynn** [comment]
> We are going to need a way to mark commits as passed tests that are just docs changes. This might require making all the commit statuses as optional as just docs changes would never need to pass Behat tests for example.

@indytechcook, @olivereri and I just discussed this and arrived at just deploying the latest passing commit and ignoring pending or null commit statuses. If a commit is null or pending it will go out the next day or in a manual deploy. This fixes issues we have with failures due to merging during the deploy window. We are still adhering to "main branch always deployable" this way.

**Comment by olivereri** [comment]
> @indytechcook, @olivereri and I just discussed this and arrived at just deploying the latest passing commit and ignoring pending, failed or null commit statuses. If a commit is null or pending it will go out the next day or in a manual deploy. This fixes issues we have with failures due to merging during the deploy window. We are still adhering to "main branch always deployable" this way.

This will go in conjunction with a Jenkins (tested, working) feature "Polling ignores commits with certain messages" so that PRs with a commit message starting with "[docs]" will not trigger a build. These commits will not pass tests since no tests will be run against the commit. Changing to the above functionality to find the last passing commit will make that irrelevant.

**Comment by ElijahLynn** [comment]
Nice, just tested the *.md commit only by commiting directly to `master` branch with 20f318000962e8a0742b934ce7ad1ab34aa3a0a6 and it works!!!
![image](https://user-images.githubusercontent.com/1504756/92820129-743ff980-f37e-11ea-9a1e-6838cc4a0e43.png)
