### ISSUE TITLE
DSN: Draft VBA Veteran Research Plan and Conversation Guide

### ISSUE THREAD

**Issue by davidmpickett** [department-of-veterans-affairs/va.gov-cms#10192]
- Participant definition 
  - Has visited a VBA facility in last 6 months 
  - 🛑 Limit to MVP sites?
- What other top task is available (e.g. Talk to someone online?) and do Veterans want that?
- How important to the Veteran is the relationship of "child" locations to the RO
- Do Veterans understand the different types of facilities (or does that matter?)
- What else do Veterans need in order to be prepared for a visit 
  - “What information do you wish you had before your last VBA visit?”
- What are the questions Veterans want answered by calling the phone number(s)?
- Is a list of Veteran Service Organizations (VSOs) located at that facility important?

**Comment by jcklpe** [comment]
Work on the research docs has begun here: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/facilities/regional-offices/vba-research

**Comment by jcklpe** [comment]
new location here: [https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/facilities/regional-offices/research/2022-8-veteran-facing](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/facilities/regional-offices/research/2022-8-veteran-facing)

**Comment by jcklpe** [comment]
This will be useful: https://app.mural.co/invitation/mural/vagov6717/1660588245137?sender=u4a3aab4befc428f9f54f8092&key=d191395b-5e8a-4b6f-bbbc-6f2a11f729e6

**Comment by davidmpickett** [comment]
While this drafts have not been fully reviewed & approved yet, much of the work has been done. I added the internal review & approval as acceptance criteria to the ticket for next sprint #10193
