### ISSUE TITLE
DSN: Synthesize VBA Veteran research & Create Topline Report

### ISSUE THREAD

**Issue by davidmpickett** [department-of-veterans-affairs/va.gov-cms#10195]
**Synthesis**
- Organize research notes in an [Affinity Diagram](https://miro.com/blog/create-affinity-diagrams/) to identify themes
- Rewatch session recordings to make additional notes & pull exact quotes
- Revisit the hypotheses from the Research Plan to see which can be confirmed

Topline Report:
- Use the [Topline Summary Template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/sharing-research/topline-summary-template.md) to summarize major findings
- Consult your Product Manager and Product Owner to see if a meeting should be scheduled to discuss the Topline Report
- Your PM and PO may have additional questions based on Topline Report that require additional synthesis
- This is just a summary of findings, no recommendations

Next Steps:
- The Research Lead should work with the Design Team & PM to create recommendations 
- The PM & PO should decide if a full research readout is required and who needs to be invited

## Acceptance Criteria
- [ ] Create Topline Report, share with PO, and update if needed 
- [ ] Schedule a full research readout (if PM & PO request)

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by davidmpickett** [comment]
Likely to span Sprints 68 and 69

**Comment by RWEagans** [comment]
Removed Sprint 68 since this is targeting the readout and synthesis.

**Comment by jcklpe** [comment]
![](https://user-images.githubusercontent.com/9451726/195719910-0cadb442-6963-43d1-8bdc-cd3fcb75c014.png)

https://app.mural.co/invitation/mural/vagov6717/1665513824757?sender=u4a3aab4befc428f9f54f8092&key=4bd6b12d-bcfd-4780-a0a9-06a449d84d91

**Comment by jcklpe** [comment]
Topline report completed here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/regional-offices/research/2022-8-veteran-facing/topline-report.md  
  
private team thread for discussing feedback found here: https://dsva.slack.com/archives/C0441RP7FDF/p1665699434236369
