### ISSUE TITLE
PM: Create VBA collab cycle intake ticket

### ISSUE THREAD

**Issue by dsinla** [department-of-veterans-affairs/va.gov-cms#10206]
Acceptance criteria

- [ ] Collab cycle ticket is created 
- [ ] Artifacts are identified

**Comment by dsinla** [comment]
Ticket created: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10241
No artifacts required for initial intake ticket

**Comment by EWashb** [comment]
@dsinla this still has sprint 65 on it. Should it be moved to the new sprint or deprioritized?

**Comment by davidmpickett** [comment]
Both tickets have been created 
- CMS Collab Cycle - https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10241
- Platform Collab Cycle - https://github.com/department-of-veterans-affairs/va.gov-team/issues/46029
