### ISSUE TITLE
Remove notice of modules not uninstalled

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#1020]
**Describe the defect**
I would like to not see notices like this
![image](https://user-images.githubusercontent.com/5752113/74977598-012e6000-53f9-11ea-8a67-d68126ed6cc1.png)

They stem from modules being disabled and removed without being uninstalled.
Using a query like this in a hook_update_n
  in vagov_db.install

```
 $query = \Drupal::database()->delete('key_value')
        ->condition('collection', 'system.schema')
        ->condition('name', 'module_name')
        ->execute();
```

**Comment by ethanteague** [comment]
PR: https://github.com/department-of-veterans-affairs/va.gov-cms/pull/1100

**Comment by swirtSJW** [comment]
THis has been merged but has some deploy steps  https://github.com/department-of-veterans-affairs/va.gov-cms/pull/1100
