### ISSUE TITLE
Discovery: Prep Translation next-steps workshop

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#10202]
### Background
In #9772 @dsasser explored the engineering-to-date of a Translation demo environment, and he documented his findings in that ticket.

### Ticket Details
In refinement on 8/11 the team determined the next step is to structure options and present them to an array of team members. 

## Acceptance Criteria

** Time box: 2 days**
To enable a meeting, we need:
- [x] An artifact to facilitate discussion around available options and associated tradeoffs
- [x] Schedule the workshop with: Danielle T, Steve W, Ryan K, Tim C, Wes & Jill, Christia... anyone else?

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by dsasser** [comment]
Update: I have been reviewing [previous research on translation options](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/content-localization). In doing so, I found a document that outlines nicely our options (and aligns with options I would have proposed organically had I not dug up the research).

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content-localization/development/Translation%20Management%20Diagram_%208_19_2021.pdf

I believe should limit ourselves to evaluating the tradeoffs of just these three options for the purposes of this ticket.

**Comment by dsasser** [comment]
[VAMC-10202_ Translation next-steps workshop prep.pdf](https://github.com/department-of-veterans-affairs/va.gov-cms/files/9376889/VAMC-10202_.Translation.next-steps.workshop.prep.pdf)
