### ISSUE TITLE
PM: Schedule VBA collab cycle meeting, identify stakeholders

### ISSUE THREAD

**Issue by dsinla** [department-of-veterans-affairs/va.gov-cms#10207]
- [ ] VBA collab cycle meeting is scheduled in Calendly
- [ ] Stakeholders are identified and added to invite

**Comment by EWashb** [comment]
@dsinla this still has sprint 65 on it. Should it be moved to the new sprint or deprioritized?

**Comment by davidmpickett** [comment]
Closing as redundant. Each collab cycle has it's own set of meetings which are governed on the respective tickets
