### ISSUE TITLE
Status page required views_ui, white screens

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#1021]
**Describe the defect**
Following the drupal 8.8 upgrade, visiting the status page results in a white screen.

This is a known issue with a tested patch
https://www.drupal.org/project/drupal/issues/3099364

Apply the patch in composer.

**To Reproduce**
1. Go to '/admin/reports/status' on staging and prod and see whitescreen

**Expected behavior**
Visitng /admin/reports/status on staging and prod should result in seeing the status page.

**Screenshots**

**Additional context**
To test this on local, dev and CI you will need to disable views_UI as it is enabled by default on those environments.

## Labels
- [/] Issue type (red) (defaults to "Defect")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [/] CMS objective (orange) (not needed for bug tickets)
- [ ] CMS-supported product (black)

**Comment by ethanteague** [comment]
PR: https://github.com/department-of-veterans-affairs/va.gov-cms/pull/1100
