### ISSUE TITLE
PM: Schedule Lovell Collab Cycle midpoint review 

### ISSUE THREAD

**Issue by dsinla** [department-of-veterans-affairs/va.gov-cms#10214]
## Acceptance Criteria
- [x] Collab cycle midpoint review is scheduled 
- [ ] Feedback received/incorporated

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by dsinla** [comment]
Currently scheduled for: 
Thursday Aug 25, 2022 ⋅ 10:30am – 11am (Pacific Time - Los Angeles)

https://github.com/department-of-veterans-affairs/va.gov-team/issues/45628

**Comment by dsinla** [comment]
All artifacts have been attached to the [Midpoint Review ticket ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/45628)
Async Midpoint Review Sitewide Facilities, Lovell VAMC/TRICARE - has been rescheduled
Mon 8/22 3:30PT/12:30 ET
NOTE: This is an asynchronous review. No meeting will take place

**Comment by dsinla** [comment]
3 new tickets were created today to deliver feedback from the Midpoint Review: 

- Accessibility Feedback: https://github.com/department-of-veterans-affairs/va.gov-team/issues/46049
- Research Feedback: https://github.com/department-of-veterans-affairs/va.gov-team/issues/46045
- IA Feedback: https://github.com/department-of-veterans-affairs/va.gov-team/issues/46042

**Comment by davidmpickett** [comment]
Might make sense to create a new ticket for responding to midpoint review for next sprint so this can close.

**Comment by dsinla** [comment]
## Summary of Feedback

Two reviews resulted in MUST recommendations

### MUST recommendations
**Accessibility Feedback** 
From the artifacts provided, it's unclear what the intended behavior is when using the "Switch to TRICARE" button in the alert, so I can't make a specific recommendation here. But you must maintain material honesty --- if it looks like a button, it needs to be a <button> and if it's a link it needs to be a` <a href="...">`. Links should be used if the interaction is navigational (the URL changes in the browser), and buttons should be used if it's an action involving the content on the current page (URL doesn't change but content changes on the current page).

**Design Feedback**
Since the button is navigational, it must be a link.
Warning alerts are reserved to warn a user, such as when there are negative consequences, or when something has gone wrong. Use an informational alert instead.
We have deprecated full-width alerts. Alerts should be the same size as the content on the page.

**Content Feedback**
Work with Sitewide Content to rework the verbiage on the buttons, with the overall intention of giving the user a clear idea of the intended usage of selecting VA vs Tricare.

### Thoughts/questions
**Accessibility Feedback** 
Between now and the Staging Review, I would recommend working with @laflannery to test the coded version for accessibility. In particular, we want to make sure that the alert is announced at an appropriate time for screen reader users, and that the action to switch between each version of the facility website makes sense.

**Content Feedback**
In the case of an informational alert, one must ensure that the language explains the benefit (the "why") of viewing the page via TRICARE vs VA. It is unclear what the intention is. I have reached out to Sitewide Content to discuss possible solutions, given the character limitations of the alert buttons. 

@davidmpickett with the summary above, I have responded to and closed the feedback tickets. I missed one of the MUSTs - regarding reworking the verbiage of the button (now link), and (not a MUST) the overall text of the alert.  @CherylEvans has stated in the [Content Feedback ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/46082)that she has reached out to the Sitewide Content team for guidance on verbiage.

I would consider responding to feedback closed, but I think there's a step 'incorporating feedback into the design which is handed off to dev' - I would see that as part of https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9847
