### ISSUE TITLE
CMS: Perform content audit of VBA data in LH 

### ISSUE THREAD

**Issue by dsinla** [department-of-veterans-affairs/va.gov-cms#10212]
## Description

As part of the VBA Facilities migration, we will retire the legacy "VBA Facility Database" and we will use Drupal as the source of truth for VBA Facility data

Perform an audit of VBA data in LH, with the goal of bringing the data into drupal. What do we need to add to the content model
_We're not doing services_ 

Cross walk what we want to bring in, taking over as source of data 
What is the data model inside drupal?

Jay: Regional offices vs everything else

## Acceptance Criteria
- [ ] Recommendation for organization 

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by JayDarnell** [comment]
Regional office example data from Lighthouse:

`{
            "type": "Feature",
            "geometry": {
                "type": "Point",
                "coordinates": [
                    -84.31071374,
                    33.80355659
                ]
            },
            "properties": {
                "id": "vba_316",
                "name": "Atlanta VA Regional Benefit Office",
                "facility_type": "va_benefits_facility",
                "classification": "Regional Benefit Office",
                "website": "https://www.benefits.va.gov/atlanta/",
                "time_zone": "America/New_York",
                "address": {
                    "mailing": {},
                    "physical": {
                        "zip": "30033",
                        "city": "Decatur",
                        "state": "GA",
                        "address_1": "1700 Clairmont Road",
                        "address_2": null,
                        "address_3": null
                    }
                },
                "phone": {
                    "fax": null,
                    "main": "800-827-1000"
                },
                "hours": {
                    "Friday": "8:00 a.m - 4:00 p.m.",
                    "Monday": "8:00 a.m - 4:00 p.m.",
                    "Sunday": "Closed",
                    "Tuesday": "8:00 a.m - 4:00 p.m.",
                    "Saturday": "Closed",
                    "Thursday": "8:00 a.m - 4:00 p.m.",
                    "Wednesday": "8:00 a.m - 4:00 p.m."
                },
                "operational_hours_special_instructions": null,
                "services": {
                    "benefits": [
                        "ApplyingForBenefits",
                        "BurialClaimAssistance",
                        "DisabilityClaimAssistance",
                        "eBenefitsRegistrationAssistance",
                        "HomelessAssistance",
                        "UpdatingDirectDepositInformation",
                        "VocationalRehabilitationAndEmploymentAssistance"
                    ]
                },
                "satisfaction": {},
                "wait_times": {},
                "mobile": null,
                "active_status": null,
                "operating_status": {
                    "code": "CLOSED",
                    "additional_info": "We're not open for in-person service at this time. Our staff are still available by phone and by our online customer service tool."
                },
                "detailed_services": null,
                "visn": null
            }
        }`

**Comment by JayDarnell** [comment]
The following is a VetSuccess example from Lighthouse

```
{
            "type": "Feature",
            "geometry": {
                "type": "Point",
                "coordinates": [
                    -97.8090211,
                    31.1201038
                ]
            },
            "properties": {
                "id": "vba_349p",
                "name": "VetSuccess on Campus at Central Texas College",
                "facility_type": "va_benefits_facility",
                "classification": "VetSuccess On Campus",
                "website": null,
                "time_zone": "America/Chicago",
                "address": {
                    "mailing": {},
                    "physical": {
                        "zip": "76549",
                        "city": "Killeen",
                        "state": "TX",
                        "address_1": "6200 W Central Texas Expressway",
                        "address_2": "Bldg 215, Room 119",
                        "address_3": null
                    }
                },
                "phone": {
                    "fax": null,
                    "main": "254-501-3094"
                },
                "hours": {
                    "Friday": "7:30 a.m. - 4:00 p.m.",
                    "Monday": "7:30 a.m. - 4:00 p.m.",
                    "Sunday": "Closed",
                    "Tuesday": "7:30 a.m. - 4:00 p.m.",
                    "Saturday": "Closed",
                    "Thursday": "7:30 a.m. - 4:00 p.m.",
                    "Wednesday": "7:30 a.m. - 4:00 p.m."
                },
                "operational_hours_special_instructions": null,
                "services": {
                    "benefits": [
                        "ApplyingForBenefits",
                        "EducationAndCareerCounseling",
                        "IntegratedDisabilityEvaluationSystemAssistance",
                        "UpdatingDirectDepositInformation",
                        "VocationalRehabilitationAndEmploymentAssistance"
                    ]
                },
                "satisfaction": {},
                "wait_times": {},
                "mobile": null,
                "active_status": null,
                "operating_status": {
                    "code": "CLOSED",
                    "additional_info": "We're not open for in-person service at this time. Our staff are still available by phone and by our online customer service tool."
                },
                "detailed_services": null,
                "visn": null
            }
        }
```

**Comment by JayDarnell** [comment]
The fields available for VBA facilities are nearly identical to those available for VAMC facilities. As such, many of the fields currently used for VAMC facilities should likely be added to the VBA facilities content model and migrations. The following link contains a breakdown of fields to add to the content model and migration for VBA facilities. 

https://docs.google.com/spreadsheets/d/1COh-XtBeA6IKmUyatmTPrFVhYoyqlH4PTjAttqbA7EI/edit#gid=0

One item I'm unsure of is the field_facility_classification field. Should a "new" field be used for the VBA facilities content type OR should additional options simply be added to the existing field. VBA facilities would need the following Classifications:

- IDES Site
- Pre-Discharge Site
- Regional Benefit Office
- Satellite Office
- Seamless Transition Integrated Care Clinic (STICC)
- Veteran Readiness and Employment Office
- VetSuccess On Campus

**Comment by swirtSJW** [comment]
Good question.   That is a bugger.   I don't think we want to pollute that field with additional values.  I think it makes sense to create a new field `field_facility_vba_classification`  That mimics the `field_facility_classification` in every way except its values.

**Comment by JayDarnell** [comment]
I'm created two new issues to handle adding these new fields to the content type and to the migration: 

#10421 and #10422

**Comment by JayDarnell** [comment]
@swirtSJW I'm assigning this to you for a look over. If the two issues I created above are sufficient to cover the findings in this ticket I think we can call this one closed.
