### ISSUE TITLE
DB Sanitize script should truncate content locks.

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-cms#10220]
## Description
A certain Cypress test – `content_editing.feature`, "Log in and confirm that System-wide alerts can be created and edited" – can be broken by the existence of a content lock on a certain node.  The flaky test will be addressed in a separate issue ( #10219 ), but it is probably not necessary to keep content locks in place when we perform database sanitization.  Therefore, we should consider truncating the table (or performing whatever action achieves the equivalent without damaging the integrity of the database).

## Acceptance Criteria
- [ ] Content locks are removed in the DB sanitize script.

**Comment by teeshe** [comment]
Sanitize DB job has a truncate database scripts with a list of tables to truncate when the job runs.
I added content_lock to list of tables to be truncated by the script.

**Comment by teeshe** [comment]
Dumps for the santize database in [s3 bucket](https://console.amazonaws-us-gov.com/s3/buckets/dsva-vagov-prod-cms-backup-sanitized?prefix=database/&region=us-gov-west-1) were reviewed and everything looks good.
