### ISSUE TITLE
Implement dynamic facility/system name on Get Medical Records page

### ISSUE THREAD

**Issue by ryguyk** [department-of-veterans-affairs/va.gov-cms#10229]
## Description
There is updated copy for the content on this page: https://staging.va.gov/health-care/get-medical-records/

Previously, when Mann-Grandstaff VA Medical Center was the only facility cut over to Cerner, that name was hard-coded here:

>If you receive care at both Mann-Grandstaff VA Medical Center and another VA facility, you may need to use both portals.

Now, we want that name to be dynamic. It should be based on the Cerner facilities that the authenticated user is associated with.

See [previous spike ticket](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9854) for more context and for insight into implementation path.

See [this slack thread](https://dsva.slack.com/archives/C52CL1PKQ/p1660321887780719?thread_ts=1660320049.136389&cid=C52CL1PKQ) about some UX/copy concerns.

## Acceptance Criteria
- [ ] VAMC System name(s) appear in this text 
  > If you receive care at both [dynamic name] and another VA facility, you may need to use both portals.

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by wesrowe** [comment]
Per [slack thread with Sitewide Content](https://dsva.slack.com/archives/C52CL1PKQ/p1660320049136389), decision was made to keep this wording generic instead of trying to customize it to a logged-in user's particular system affiliations.

**Comment by wesrowe** [comment]
cc @davidconlon
