### ISSUE TITLE
New KB article for “How Do I Update the Spotlight Links on the Homepage?”

### ISSUE THREAD

**Issue by EWashb** [department-of-veterans-affairs/va.gov-cms#10224]
## Background

A new article should be created in our Knowledge Base on the subject of "How Do I Update Spotlight Links on the Homepage?"

## User Story

As a CMS editor, I would like an article explaining how to update the spotlight links on the homepage so that I can relay important information to Veterans and stakeholders.

## Acceptance Criteria

- [ ] Article is drafted
- [ ] Article is reviewed my Sitewide CMS
- [ ] Article posted to KB

**Comment by laflannery** [comment]
@EWashb Can we close this? I believe this was a request from before the new homepage was create and we have an article for the [new page spotlights now](https://prod.cms.va.gov/help/vagov-homepage-product-guide/how-to-edit-the-homepage-news-spotlight) so I think this request is complete
