### ISSUE TITLE
UX Analysis of Forms Download Process

### ISSUE THREAD

**Issue by dsasser** [department-of-veterans-affairs/va.gov-cms#10239]
**NOTE: Probably not necessary after we reduce API calls and make Search and Detail experiences the same.**

# Description

As a veteran, I want to be able to directly download an available PDF, regardless of system issues.

Discovery of the technical events occurring during Forms downloads revealed a complex flow of interactions that can easily lead to the user never getting to a form which is actually available (ie, not failing).

Some concerns:
- Spinner or other "please wait" indicator – Clicking on a PDF link could result in many seconds of waiting, with no UX indication that any background process is in place. (depends on the performance/response of the Lighthouse API)
- False negatives (receiving the forms alert error) where Lighthouse has (incorrectly?) flagged a PDF as invalid, cause an alert to appear, but the link to the PDF is hidden inside a mailto: url.

![Screen Shot 2022-08-10 at 10.42.02 AM.png](https://images.zenhubusercontent.com/628fa5e0de11802be559ed62/d81deefc-26f3-49e6-b0d8-741030ac15d3)

**Note:** The modal on the Search page (on 8/30/22) has a less obvious CTA link (not the blue button in the shot above):
<img width="505" alt="image" src="https://user-images.githubusercontent.com/4054752/187511342-708d2c63-57c4-4e27-aac7-8d802b21e4f6.png">

## Acceptance Criteria

- [ ] Review user research that led to complexity of the flows (eg, having a modal appear with instructions)
- [ ] Document in Mural the PDF download UX for both the Search page and Detail page

**Comment by wesrowe** [comment]
This issue will not be necessary after we've cleaned up the javascript to eliminate extra API calls, which sometimes experienced high latency.

**Comment by jilladams** [comment]
@wesrowe we could close this, and then the Threat Space discovery epic is done & could also be closed in favor of the separate epic to take action on optimizing the UX? #10710

**Comment by wesrowe** [comment]
Agreed. closing issue.
