### ISSUE TITLE
How to notify editors of deploy commencement.

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#1023]
## Background 
When a deploy of the CMS happens, there is a window of at least 10 minutes where the site goes unresponsive and can leave editors with changes that do not get saved.

It would be nice to have something in place to notify them of this happening.  

## To do 

 - [x] Kauff and Swirt to map out daily deployments and how they impact users
 - [x] Survey existing contrib modules to see if any will suit our needs.
 - [x] Create an implementation plan and where the notification messaging fits in. 
 - [ ] Groom deploy stories in this epic. 

### Artifacts
- [Mapping deployments with a focus on user impact (AirTable)](https://airtable.com/tblulo3XrMLuh4N0l/viwL2poNtFAZMeS6Z?blocks=hide)
- [CMS product comms strategy (MURAL)](https://app.mural.co/t/vagov6717/m/vagov6717/1582651877361/793f249de54105ddf57fc2816e5be91ff8dafab4)

## Some implementation options

1. Slack is one option, but we can not count on all editors having access to slack
2. A deploy window that is outside of the business hours of the east coast would help, but would still catch editors in other time zones unaware.  This also increases the burden / risk of having fewer CMS team members on hand if something goes wrong.

**Comment by swirtSJW** [comment]
One idea that I really like is the idea that the CMS could notify logged in editors immediately of the any status with the cms (going down, is down don't save, free to proceed)

Spitballing here on Elijah's and Neil's idea:  A drupal contrib module that has:

1. An api endpoint to trigger a state of downtime coming (sets a var flag and time) (either an absolute time 2:52pm, or a relative time (15 min)  This might be just as easily handled, with less risk as a simple drush vset.
2. An ajax endpoint that returns a bit of detail about pending downtime (message text and a timestamp for when it should occur, type of message warning, error, status) It would have to be tolerant to keep state when the endpoint vanishes during the downtime.
3. A block that is placed on (in our case ) on all edit forms have an ajax item that polls every minute for a pending flag, if found, it unfurls a banner with information (message and countdown timer).
4. An api endpoint (probably same as trigger endpoint) to unset the message (which would cause the banner on edit forms to disappear.   Or again simpler and safer as a Drush vset.
5.  Bonus point for when the banner countdown by the JS banner reaches zero, it disables the save buttons and only re-enables when the ajax endpoint gives the all clear.


Possible names:

-  Live Alerts
- Emergency Broadcast System
- ?

**Comment by rachel-kauff** [comment]
@swirtSJW I'd love to hear more about this, and am eager to start mapping out what deployments are happening when + how they affect users. I'll get in touch shortly about getting started.

**Comment by rachel-kauff** [comment]
Met w/ Swirt. Working on an artifact to implement here.

**Comment by rachel-kauff** [comment]
Added a new task for mapping out where in-cms notifications go. But lost it somewheres.

**Comment by jefflbrauer** [comment]
@swirtSJW I like this idea too.  would be great to have logged in users notified in drupal at the top with a small alert banner say 60 minutes in advance like we do on slack today, then another notification 10 minutes out as a reminder to save their work, then at start and completion.

**Comment by swirtSJW** [comment]
I did a review of existing contrib modules to see if any will get us close.

Name | content/config | ajax | real-time | Full release | Notes
-- | -- | -- | -- | -- | --
sitewide_alert | content | yes | yes | Beta4 | Have to look into setting it by drush. as it uses a content type, rather than config setting.
bootstrap_site_alert | config | yes | no | Yes | We want the 1.x branch
site_alert | config | yes | no | Yes |  
alert_box | config | no | no | sandbox |  
emergency_alerts |   | no | no | sandbox |  
slack |   |   |   |   | Llimited by not all editors have avalability to va slack.
drupal_to_slack |   |   |   |   | Llimited by not all editors have avalability to va slack.
live_content |   |   | yes | Yes | Provides a web socket api to populate how we want.
notificationswidget |   |   | yes |   | Interesting for other content related work, but not this.
content_alerts |   | no | no |   | Not even close
sweet_alert |   | no | no |   | Not even close
sweet_alert2 |   |   |   |   | Not even close
igrowl |   |   |   |   | Not even close
site_status_message |   | no | no |   |  
simple_popup_blocks |   |   |   | RC1 | Not even close
message_notify |   | no | no |   | Can send sms messages.
web_push_notification |   | no | no | alpha | Interesting idea.
browser_push_notification |   |   |   | sandbox | Interesting idea but needs people to add the site as a web app on their device.
advanced_pwa |   | no | yes |   | Interesting idea but needs people to add the site as a web app on their device.
social_pwa |   |   | yes |   | Interesting idea but needs people to add the site as a web app on their device.
Simple cool message |   |   |   |   | Not even close


I think sitewide_alert is pretty close.   https://www.drupal.org/project/sitewide_alert    The only thing is seems to be lacking is a way to set and removed an alert with a single command, so we would need to contrib back a drush command(s). to create and destroy a specific alert.

**Comment by rachel-kauff** [comment]
@swirtSJW Do you think we're ready to work on the " Create an implementation plan and where the notification messaging fits in." step? If so I'll set us up to mind-meld.

**Comment by kevwalsh** [comment]
@rachel-kauff @swirtSJW  Is this a sprint 1 spike? do y'all have bandwidth to continue it, or should we add to Sprint 2? it currently is not assigned to any sprint.

**Comment by rachel-kauff** [comment]
@kevwalsh You're probably right. The second half of this ticket should probably be moved over to sprint 2, mostly because next week is full of personas and journey sesssions.

**Comment by swirtSJW** [comment]
In testing the module out, it does what we need it to.  Puts messages on the page with ajax and can update every 20 seconds. 
I added this issue to the site_alert module.   https://www.drupal.org/project/site_alert/issues/3118800 
so that I can make it do what we need.

**Comment by swirtSJW** [comment]
Patches are in https://www.drupal.org/project/site_alert/issues/3118800

**Comment by swirtSJW** [comment]
I just confirmed that the site alerts ajax still works even when the site is in maintenance mode... which is awesome.

**Comment by ethanteague** [comment]
> I just confirmed that the site alerts ajax still works even when the site is in maintenance mode... which is awesome.

That is awesome.

**Comment by rachel-kauff** [comment]
@ElijahLynn cc: @swirtSJW Could you let me know when the messages + Jenkins part is figured out, and when the deployment notifications will go live? I'll be including this work in a release note to let users know when they'll see this rolled out.
