### ISSUE TITLE
FE: Remove Fetch of Forms File HEAD during PDF Click Event

### ISSUE THREAD

**Issue by dsasser** [department-of-veterans-affairs/va.gov-cms#10236]
### BLOCKER(s)  

- See https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10562, the better approach may be to re-use the simpler javascript flow from the Form Search page
- Blocked on confirming the business logic for why this was added, and whether it should instead be applied to both VA and VBA forms

## Description

Update: This API call is unique to the download flow on Form Detail pages; the Form Search page doesn't have this extra API call.

During discovery performed under #10061, we identified a seemingly redundant HTTP call to fetch the HEAD of the linked Form PDF file, which is occurring during the PDF Click event. This only occurs if the PDF is hosted by www.va.gov (not vba.va.gov, or any other of the other domains).

Remove this HTTP call occurring during the PDF click event.

Here's where to find the [big Mural board](https://app.mural.co/t/vagov6717/m/vagov6717/1660150431569/27c80eaeeaedfd88c80322ae177b68c503345ba9?sender=u907f83e01e35bb04de6f8139) (pictured below).

![VACMS-10061 - Discovery Form FE Workflow.png](https://images.zenhubusercontent.com/628fa5e0de11802be559ed62/37f98a48-0f1e-4e8e-98f5-0f36cd4decbe)

## Acceptance Criteria
- [ ] Fully grok the entirety of the [Mural](https://app.mural.co/t/vagov6717/m/vagov6717/1660150431569/27c80eaeeaedfd88c80322ae177b68c503345ba9?sender=u907f83e01e35bb04de6f8139) created in #10061 for context of the extra API call (LINK TBD)
- [ ] Validate that it's a good idea to remove this fetch
- [ ] Remove the call
- [ ] QA against relevant [use cases](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-a-va-form/mvp/design/find-va-form-use-cases.md)

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by wesrowe** [comment]
Updated issue to reflect that spike https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10562 might be a better approach.

**Comment by FranECross** [comment]
Closing old iceboxed ticket.
