### ISSUE TITLE
Automated Find-a-form Sentry Alert Notifications

### ISSUE THREAD

**Issue by dsasser** [department-of-veterans-affairs/va.gov-cms#10237]
## Description
Forms issues discovery revealed that sentry logs are capturing failed reports, but these sentry reports are not notifying PW of incidents.

**Maybe a platform ticket?? How much control over Sentry notifications, and how that would be implemented, is likely outside of our bailiwick**

Identify a manual or automated process for catching early forms issues that are being reported (but not monitored) in Sentry..

## Acceptance Criteria

- [ ] Determine the UX scenario that most reliably indicates PDF an actual download failure for Veterans
- [ ] Ensure that that failure is being logged to Sentry
- [ ] Get a Sentry alert set up that contacts members of the PW team when those failures pass a reasonable threshold (Hopefully we can set it up ourselves, otherwise get someone to help)

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by wesrowe** [comment]
closing as duplicate
