### ISSUE TITLE
Event location Editor UX: Prepare for research

### ISSUE THREAD

**Issue by fmccaf1** [department-of-veterans-affairs/va.gov-cms#10248]
## Description
Get documents ready for testing Event location Editor UX prototypes so we can start sourcing editors.

## Acceptance Criteria
- [ ] Research plan complete
- [ ] Conversation guide complete
- [ ] Generate CMS collab cycle ticket
- [ ] Schedule review of research plan with Dave

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by davidmpickett** [comment]
@wesrowe @jilladams Given this isn't on the q4 roadmap, safe to icebox?

**Comment by wesrowe** [comment]
@davidmpickett, I would think we would make that decision about the entire epic. And it's fine with me if that helps you get organized.

**Comment by aklausmeier** [comment]
@FranECross @mmiddaugh We should consider how this fits into the Events 3.0 buckets.

**Comment by FranECross** [comment]
Closing old ticket; a new one can be created when needed.
