### ISSUE TITLE
Update path for CMS notifications email

### ISSUE THREAD

**Issue by EWashb** [department-of-veterans-affairs/va.gov-cms#10247]
## Description

From troubleshooting in #9585 it was determined that we would need config change for the CMS notifications email within the code. 

We also may be able to use +1 functionality (think google support). For example:

VADrupalCMS@va.gov
VADrupalCMS+1@va.gov

To verify that this works, we would need to send an email to both and verify that they both arrive in the inbox for: VADrupalCMS@va.gov

If that works then we can just set chatbot to VADrupalCMS+chatbot@va.gov Which would free us up to be able to use VADrupalCMS@va.gov as the master account.

Also see this [slack thread]( https://dsva.slack.com/archives/C03LFSPGV16/p1660154940349249) for more context. 

## Acceptance Criteria
- [x] Test +1 email option
- [ ] ~verify both emails arrive in the VADrupalCMS@va.gov inbox~ Failed 😞 
- [x] Complete any necessary code changes

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [x] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by EWashb** [comment]
per @cmaeng 

no bueno:

![image](https://user-images.githubusercontent.com/90111970/184662256-4c9999e8-1b9f-45b4-9487-4bab574a057c.png)

**Comment by swirtSJW** [comment]
Looks like plus email has to be enabled at the system administration level 
https://techcommunity.microsoft.com/t5/exchange/support-for-plus-addressing-in-office-365/m-p/1170418

**Comment by EWashb** [comment]
@ndouglas I left you as the sole assignee on this one. I know it is currently blocked by a CAG outage.
