### ISSUE TITLE
next-build export can be triggered from content-build and inserted into Metalsmith

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#10266]
## Description
In https://github.com/department-of-veterans-affairs/va.gov-cms/issues/8331, we prototyped triggered a second static build from a content-build run and inserting it into Metalsmith. Adapt this mechanism to work with next-build.

## Acceptance Criteria
- [x] A content-build branch exists that ensures next-build is available
- [x] content-build runs on this branch trigger a next-build export
- [x] The files output by the next-build export are inserted into Metalsmith for render & delivery.

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [x] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by cweagans** [comment]
I'm curious about the approach on this. It sounded like you were talking about running it in parallel with content build rather than as a step in the existing content build process. Is that right? Very interested in talking through this if it would be helpful.

**Comment by timcosgrove** [comment]
https://github.com/department-of-veterans-affairs/content-build/pull/1279
