### ISSUE TITLE
Discovery: study Sentry logging for Find-a-form and recommend approach

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#10268]
## Description

**Time box: 2 days of effort**

Follow-up to understand Veteran impact from the Forms API incident focused around Aug 8 & 9.
1. Understand what Sentry logged (8.7k users, 73k events, labeled by Sentry with Form 1010ez as an example form that had issues during this timeframe)
- Which specific measure(s) in Sentry (events, users, etc) is a better measure of Veteran impact?
- Is Sentry really just watching Form 1010EZ? or is it bucketing all forms errors under the most commonly downloaded form in example issue reports, e.g. http://sentry.vfs.va.gov/organizations/vsp/issues/17064/?project=4
2. Recommend an accurate logging approach
- Can we use Sentry more precisely?
- Can we configure Sentry to alert our team under specific conditions?

### Resources
- Platform Infra team's Confluence space has at least one [page about Sentry](https://vfs.atlassian.net/wiki/spaces/pilot/pages/590774316/Tracking+application+errors+with+Sentry)

**GA errors proxy (Veteran sees alert that “the form link isn’t working”):**
![image.png](https://images.zenhubusercontent.com/61a671f5fc46c2a311655f75/405aa2d0-f3d8-479d-8835-babcf2e35fe7)

**Sentry logs (`Find Forms - Form Detail - onDownloadLinkClick function error`) :**
![image.png](https://images.zenhubusercontent.com/61a671f5fc46c2a311655f75/e805a283-7335-47d2-b8e5-0f64be7dee25)
- Sentry report by time period: http://sentry.vfs.va.gov/organizations/vsp/discover/results/?cursor=0%3A400%3A0&display=default&field=title&field=event.type&field=project&field=user.display&field=timestamp&name=All+Events&query=Find+Forms&sort=-timestamp&statsPeriod=7d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1
- Sentry report for a specific form: http://sentry.vfs.va.gov/organizations/vsp/issues/17064/?project=4 --- when this report URL first popped up, it was in re: troubleshooting Forms API latency ([Wes vfs-platform-support thread](https://dsva.slack.com/archives/C52CL1PKQ/p1660066744533659?thread_ts=1659976483.935999&cid=C52CL1PKQ)

## Acceptance Criteria
- [x] Understand how Sentry logging currently works w.r.t. Forms issues (what it's logging)
- [x] Document specifics around what is being recorded currently in Sentry in the appropriate folder in github (perhaps in the find-a-form product folder?)
- [x] Draft your recommendation for a monitoring-and-alert scheme going forward, including both Sentry configuration and any changes to application code

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by jilladams** [comment]
@ryguyk (& @dsasser fyi) there's a latency event happening today: https://dsva.slack.com/archives/C03STQZ40DQ/p1661179921999599

We got a report from Forms managers that several forms were affected: 
21-4142a
21P-4706b
20-0998
20-0995

And those forms are showing an error at times when searching via Find a form: 
![image002](https://user-images.githubusercontent.com/85581471/185998103-e7bb4c78-c234-4057-a03f-9ba923bcb7df.png)

I'd love to take a look at Sentry related to this, but navigating to Discovery > searching for Find form doesn't reveal much, and I didn't find a report URL in #10061. Could either of you point me to a URL where I can see this report? (I have Sentry access.)

**Comment by davidconlon** [comment]
Covered in mid-sprint check-in that this may not land in Sprint 65 due to injected work (troubleshooting, unidentified priorities)

**Comment by ryguyk** [comment]
@jilladams Try this:

http://sentry.vfs.va.gov/organizations/vsp/discover/results/?end=2022-08-24T23%3A59%3A59&field=title&field=event.type&field=project&field=user.display&field=timestamp&name=All+Events&project=-1&query=Find+Form&sort=-timestamp&start=2022-08-22T00%3A00%3A00&utc=true&widths=451&widths=-1&widths=-1&widths=-1&widths=-1&yAxis=count%28%29

**Comment by jilladams** [comment]
From [slack convo today](https://dsva.slack.com/archives/C52CL1PKQ/p1661274831554739): this URL, http://sentry.vfs.va.gov/organizations/vsp/issues/17064/?project=4, is problematic. Just yesterday I had pulled it up and it was focused on 1010EZ. Today, it's about "/about-form-21-526ez". I'm not grokking how the "issue" link gets built, but note: the focal form URL of that particular report link URL can change. 

In general this issue is about understanding what we can & can't know from Sentry, and how we can configure the dashboard / issues / reports to hone in on issues for reporting / alerts moving forward. I would ignore references to 1010EZ, and explore the broad case. (Case in point re: 1010EZ just being an example of the outage on these dates: https://dsva.slack.com/archives/C52CL1PKQ/p1660580016365849). I think that thread best summarizes what Wes is trying to get at here.

**Comment by ryguyk** [comment]
(In progress...)
# Discovery Outcome

## Sentry as a tool
1. ["Issues" in Sentry](https://docs.sentry.io/product/issues/)
   - Sentry groups similar error events into "issues". 
   - Events within issues are _not_ identical. Issues are formed in Sentry by grouping events based on certain criteria. That grouping does not consider _all_ data in the events. For example, the issue shown below "Find Forms - Form Detail - onDownloadLinkClick function error" groups all events with that title. But each of those events has additional data passed with it (e.g. form id).
      - It appears, therefore, that if you view an issue today, the details shown will likely be different than the details from viewing that event yesterday. It seems that viewing an issue reveals specifics around the *most recent event in that issue*.

![image](https://user-images.githubusercontent.com/6863534/186488704-a37fed2d-ad79-4a50-815f-75d714eb737d.png)

2. ["Alerts" in Sentry](https://docs.sentry.io/product/alerts/)
   - From the original ticket description:  **"Can we configure Sentry to alert our team under specific conditions?".**
      - The answer to this question appears to be "Yes".
      - Per the Sentry documentation linked, we should be able to configure an alert triggered by "Issue frequency increasing".
      - The issues shown above are already being tracked (i.e. they are being grouped by Sentry into collections by label). It seems we should be able to set an alert that triggers when the frequency of events in those issues increases beyond a certain threshold.

## What are we passing to Sentry for Find-a-Form?
There are five (5) possible event messages sent to Sentry:
1. `Find Forms - Form Detail - onDownloadLinkClick function error`
2. `Find Forms - Form Detail - invalid PDF accessed`
3. `Find Forms - Form Detail - onDownloadLinkClick function error`
4. `Find Forms - Form Detail - invalid PDF accessed & invalid PDF link`
5. `Find Forms - Form Detail - invalid PDF link`

## What happened on Aug. 8 & 9
1. From the original ticket description: **"Understand what Sentry logged (8.7k users, 73k events...)"**
   - The numbers shown here actually appear to be from a much larger date range (90 days, it seems). 
   - [Querying only for Aug. 8 & 9](http://sentry.vfs.va.gov/organizations/vsp/discover/results/?end=2022-08-09T23%3A59%3A59.000&field=title&field=event.type&field=project&field=user.display&field=timestamp&name=All+Events&project=-1&query=Find+Forms+-+Form+Detail+-+onDownloadLinkClick+function+error&sort=-timestamp&start=2022-08-08T00%3A00%3A00.000&utc=true) shows about 5.3k events and roughly 2.2k users for "Find Forms - Form Detail - onDownloadLinkClick function error".

**Comment by jilladams** [comment]
@ryguyk rad. Can you just add a note re: why the user count may not be useful? 

Otherwise, I got excited and went for it: 

- "Discover > Find Forms errors" saved as a persistent report: http://sentry.vfs.va.gov/organizations/vsp/discover/results/?id=19&statsPeriod=7d
- Alert: http://sentry.vfs.va.gov/organizations/vsp/alerts/metric-rules/platform-web/7/

Based on what we've seen the past few weeks, I set: 
1. Warning level = 10 events in 15mins -- will email me, @wesrowe & @dsasser 
2. Critical level = 50 events in 15 mins -- will email the whole [VFS Public Websites team in Sentry](http://sentry.vfs.va.gov/settings/vsp/teams/vfs-public-websites/members/).

I'll warn the old members of that team that they may want to eject. Anyone should feel free to tweak Alert settings, esp if things go nuts with email unexpectedly.

**Comment by jilladams** [comment]
From 8/29 discussion: we can clean up code, but may not need to change what we're sending to Sentry.

**Comment by jilladams** [comment]
11/2022: https://dsva.slack.com/archives/CBU0KDSB1/p1668707111130899
> : Sentry Alerts do not generate notifications as configured. Could someone help us troubleshoot?  Example alert:  http://sentry.vfs.va.gov/organizations/vsp/alerts/metric-rules/platform-web/7/;   Alert settings: http://sentry.vfs.va.gov/settings/vsp/projects/platform-web/alerts/

https://dsva.slack.com/archives/CBU0KDSB1/p1668711436107429?thread_ts=1668707111.130899&cid=CBU0KDSB1
> It sounds like SMTP needs be setup if emails aren’t going out

https://dsva.slack.com/archives/CBU0KDSB1/p1668712360325519?thread_ts=1668707111.130899&cid=CBU0KDSB1
> Who owns Sentry? I thought it was devops. I just did a search in the devops repo and there are a couple of TF files for Sentry there - terraform/**/*sentry*.tf. [tf = terraform]

https://dsva.slack.com/archives/CBU0KDSB1/p1668717101597429?thread_ts=1668707111.130899&cid=CBU0KDSB1
> (can you confirm: as far as you know, [the other Sentry alerts](http://sentry.vfs.va.gov/organizations/vsp/alerts/rules/?project=4) do generate emails that people receive? It's unique to our Forms errors alert, that it's not emailing the listed team members?) they do, i get them all day everyday as does the identity team and i assume others

Never resolved.
