### ISSUE TITLE
Handling of ʻokina character in Hawaiʻi?

### ISSUE THREAD

**Issue by davidmpickett** [department-of-veterans-affairs/va.gov-cms#10282]
## Describe the defect
Not sure where this originates (data source vs Drupal vs FE) but the ʻokina is displaying as a ? in "VetSuccess on Campus at University of Hawai?i at Manoa"

## To Reproduce
1. Go to https://www.va.gov/find-locations/facility/vba_459a
2. Look at the H1

## AC / Expected behavior
Find cause and resolve

**Comment by dsinla** [comment]
Quick inspection by Jay - Lighthouse delivers the string with the question mark.

**Comment by JayDarnell** [comment]
Screenshot of the JSON object in Lighthouse. I suspect this error is coming over from VAST this way.

![Screen Shot 2022-09-13 at 11 59 05 AM](https://user-images.githubusercontent.com/21045418/189982105-af2c6b5d-5a80-49dd-b491-540646276bec.png)

**Comment by dsinla** [comment]
@dsinla to notify LH team -

**Comment by davidconlon** [comment]
This was coming from the upstream system (at the very least)
I've updated the upstream DB to be "VetSuccess on Campus at University of Hawaiʻi at Mānoa"

Hopefully LH will be able to accept these characters.

**Comment by davidconlon** [comment]
@JayDarnell @dsinla The VBA DB unfortunately does not support UTF-8.
I have now made the change to use "VetSuccess on Campus at University of Hawaii at Manoa"

This will propagate tonight through Lighthouse

**Comment by JayDarnell** [comment]
Thank you @davidconlon
