### ISSUE TITLE
Update the color of description text on Vet Center Cards

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#10299]
## Description
On the Vet Center Dashboard in the CMS, the description help text on the cards (HEX 757576) does not pass WCAG 2.0 AA color contrast requirements against the light gray background

### Changes:

 - This description text will be updated to be the same color as the standard text color. `#212121`
 - Increase size of description text from 13px to 14px.

## Screenshot
![image](https://user-images.githubusercontent.com/106678594/184974308-db9c7d4c-6611-4f1f-aad3-c35c096e193f.png)

## Accessibility Standard

WCAG version 2.0 AAA, [Criterion 1.4.6](https://www.w3.org/WAI/WCAG21/Understanding/contrast-enhanced)

## Acceptance Criteria
- [ ] Update text color to `#212121`
- [ ] Update text size to 14px
- [ ] Accessibility Review
- [ ] Design Review

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [x] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by laflannery** [comment]
@BlakeOrgan Looking at this ticket and knowing your recent recommendations for text color, should this text also be updated to the standard `#212121` color?

**Comment by BlakeOrgan** [comment]
@laflannery Yes!

**Comment by laflannery** [comment]
Thanks! Tied to #11397 (This can maybe get updated at the same time?)
