### ISSUE TITLE
Events list: Events in progress do not appear as Past or Upcoming

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#10307]
## Describe the defect

SPIKE: #10176 
(Is #10716 a dupe?)

https://dsva.slack.com/archives/C52CL1PKQ/p1660681413087369?thread_ts=1660266788.151129&cid=C52CL1PKQ

An event in progress (e.g. from 11am-12pm EST) will disappear from Upcoming events at 11:01am, and not appear in Past Events until 12:01pm. While in progress, the event effectively is not findable. 

**Update:** on 1/3/23 an Editor from VEO contacted CMS Help Desk. They thought their event had disappeared because it wasn't visible. 
- Example: Virtual PACT Act Symposium
  - Event page: https://www.va.gov/outreach-and-events/events/51525/
  - Event List (National): https://www.va.gov/outreach-and-events/events/

### Key issue

The event listing "goes missing" at the precise time it is most likely to be sought out by Veterans needing the information:
- For an online event, Veterans showing up "on time" (even 30 seconds past the published start) would not be able to find details. Participants have to open the page _early_ to get the details. 
- For an in-person event, a Veteran looking for the meeting location in real life might be unable to look up the address as soon as the posted start time has arrived.

**Complicating factor:**
There is no view of events that shows all events – it forces filtering for upcoming (default) or past.

**Impacted users:**
- Veterans who have heard of an event but are arriving late _or even just on time_
- Editors who are trying to connect Veterans to an event as it's starting or after its published start time

## AC / Expected behavior

- [ ] Events should appear in Upcoming until the end time has passed, then move to Past Events.
    - NOTE: Dave C indicated it would be fine with him if it didn't move to Past until the end of the day, if that's easier to implement. 
- [ ] Unit test is added to verify active events (in progress) are still displayed in Upcoming

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [X] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by wesrowe** [comment]
@jtmst, can you please look over the details and add your estimate.

**Comment by jilladams** [comment]
@apisandipas can you clarify the state of testing here? Is there a Review Instance or local somewhere with mock data that I can reference for review?

**Comment by jilladams** [comment]
Nevermind, saw slack update, thank you: 
> I've put in a platform support ticket to get help with the broken tugboat so we can set up some test data, but havent heard back yet

**Comment by jilladams** [comment]
Note from 1:1 with Daniel: he was able to use prod data locally to prove that the bug I identified in PR does happen with PR code changes, and doesn't happen without them. Daniel may be able to pick this up and help us get it fixed / over the line, with some FE support as needed.

**Comment by jilladams** [comment]
Note: today Daniel and I stubbed out https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12932 for thinking through how to make testing events easier/ feel less brittle. We can/should keep this in mind while finishing out this ticket, if there are ways to work any of those notes into our testing here.

**Comment by wesrowe** [comment]
Just refined #12932 to make better test data, that should probably be done first to make this ticket better/easier.

**Comment by wesrowe** [comment]
Dave C asked: what about just making the transition to past events happen overnight? Would that be easier?
(I feel like the original decision to do it in real time was driven by CMS team and previous iteration of PW team.)

**Comment by jilladams** [comment]
This could look like: run it at the same time as the Prod mirror, maybe? From 3am ET - 3am ET shows as Upcoming? 

It's sort of weird as a user, my 2 cents. If I show up on a page at 4pm and see "Upcoming events: 8am, 11am, 1pm, 2pm, 5pm" etc. But: does it matter enough to care about that, as long as they're not SUPER stale (1+ days)? Probably not?

**Comment by jilladams** [comment]
From planning: the goal is lower lift to solve the problem, vs. optimizing for top tier UX, in this case.

**Comment by dsasser** [comment]
Verified in prod:
<img width="981" alt="Screenshot 2023-06-30 at 3 23 24 PM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/221539/c7e6e1eb-ab10-4041-836d-fb26ecd40362">

**Comment by jilladams** [comment]
O M G 🏆 🎉 :shipit:
