### ISSUE TITLE
Discovery: Existing Homepage content model and how to leverage for new design

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#10302]
## Description

Document what parts of the existing VAgov Home Page are driven by the CMS, and speculate how those models could be adapted to [the new homepage design](https://staging.va.gov/homepage-test) we've been testing.

Elements of new home page to consider:
- Copy around the hero/sign-in CTA (with the Veteran portraits)
- Common tasks list
- News/blog spotlight
- Benefit Hubs - the 11 tiles below the news spotlight

## Acceptance Criteria
- [ ] Document in some combination of this ticket and a Mural board (if helpful for illustrating)

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by wesrowe** [comment]
@mmiddaugh, I started this issue based on a conversation with @davidconlon. Please have a look. The idea would be to prepare ourselves for production implementation when the design is finalized after the next round of usability testing.

**Comment by dsasser** [comment]
@wesrowe Where can I view the new homepage design?

**Comment by wesrowe** [comment]
[staging.va.gov/homepage-test](staging.va.gov/homepage-test), I'll add to details

**Comment by mmiddaugh** [comment]
This issue may be helpful @dsasser : Updates to VA.gov home page redesign deployment [#43137](https://github.com/department-of-veterans-affairs/va.gov-team/issues/43137)
Cindy is in the process of synthesizing the usability research ([research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/public-websites/home-page/research/redesign-usability/research-plan.md)) - these  findings will be very important in informing iterations to the new design.

**Comment by dsasser** [comment]
# Findings
The new homepage has three components are "new". Other components are either removed entirely, or used as-is. The existing homepage, and new homepage, are not governed by a single CMS node or other entity, so the pieces that combine to create the homepage come from different parts of the CMS. eg: blocks, menus, static text, etc. Which of these is necessary for a homepage is determined by the template which renders the homepage (home.drupal.liquid for the existing homepage or home-preview.liquid for the new homepage).

Visual guide to changes:
![VACMS-10302 - Homepage Discovery.pdf](https://github.com/department-of-veterans-affairs/va.gov-cms/files/9418502/VACMS-10302.-.Homepage.Discovery.pdf)

Source Mural:
https://app.mural.co/t/vagov6717/m/vagov6717/1661183899852/e50c35c05d4238404b3a4e8f3fa0c5b5363ef441?sender=u2cc9d7c4c6c0dea143b21411

## Benefits Hero
The ideal CMS content to control this hero is a Promo block. Promo blocks are already used on the homepage, so the existing query could be leveraged without much if any alteration on the FE.

## Hub / Common Tasks
The search box in this component is likely needs to be static template text, much like the search component in the header.

The common tasks can be driven by a menu, either by re-using the existing homepage menu, or creating one for this purpose.

## Promo Hero
The promo hero consists of an image, title, description/cta text, and two links. There doesn't appear to be an ideal candidate for controlling this info in the CMS at this time. It may make sense to create a new custom block type.

I will add that it is unclear the purpose of this component is to dynamically display "featured" promotional items of a single type (blog), multiple types (blog, news, etc), or an unchanging static list of links.

**Comment by jilladams** [comment]
@dsasser to cut tickets for the follow up work to implement & @ Jill to once-over
