### ISSUE TITLE
Create link to burial schedule on Facility Detail page 

### ISSUE THREAD

**Issue by dsinla** [department-of-veterans-affairs/va.gov-cms#10319]
# Draft 

## Acceptance Criteria
- [ ] Testable_Outcome_X
- [ ] Testable_Outcome_Y
- [ ] Testable_Outcome_Z
- [ ] Requires design review

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by Agile6MSkinner** [comment]
No content. Closing.
