### ISSUE TITLE
Some outreach hub materials are missing.

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#10312]
## Describe the defect
Not all outreach  materials are showing on the page https://www.va.gov/outreach-and-events/outreach-materials/
There should  be 179 showing but only 164 show.  No newly created ones are showing.

### Cause
A malformed query that dates back 3 years  (one missing bracket is all it was) 
![image](https://user-images.githubusercontent.com/5752113/185220731-16c5d4a1-19ac-4dce-8276-d5319d9e0c66.png)
was pulling in thousands of unrelated content that was not being rendered, because it had no matching fields.
![image](https://user-images.githubusercontent.com/5752113/185220285-313685fc-92a9-45ad-a1fd-cd9869168706.png)

However, all those empty results that included appropriate results, no longer had space to accommodate new outreach assets because it was limited to 10,000 results.   There are 179 outreach assets, but there are 40,000+ nodes that were also being included in this query.

[Investigation in slack](https://dsva.slack.com/archives/CJT90C0UT/p1660755190150279?thread_ts=1660754549.158759&cid=CJT90C0UT)
[Out of band deploy request](https://dsva.slack.com/archives/CBU0KDSB1/p1660762220286809) in Slack
[OOB github request issue](https://github.com/department-of-veterans-affairs/va.gov-team/issues/45854)

## To Reproduce
1. Go to https://www.va.gov/outreach-and-events/outreach-materials/
2. Filter for
![image](https://user-images.githubusercontent.com/5752113/185224002-1a3d6204-ba10-456a-ad57-5ceea9552c7e.png)

3. At least two items with PACT in the title should show.  They are missing.

## AC / Expected behavior
All recently created publications (outreach assets) should show on the page.

 ## Additional context
This defect has existed for years but was unnoticed becasue only new content was getting bumped due to the sort of the results being by node id.  So old items would show because the node ids were low, but new ones would not show.

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Defect")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS workstream (orange) (not needed for bug tickets)
- [ ] CMS-supported product (black)

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by jilladams** [comment]
@swirtSJW  Super curious- how did you become aware of this?

**Comment by swirtSJW** [comment]
@jilladams  It was raised by Stef in slack.    You'll be able to see the whole timeline of events shortly as I have to reconstruct them in the postmortem.

**Comment by swirtSJW** [comment]
@jilladams  here is the timeline, which is pretty much the only part of the postmortem I have completed yet.
https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/7e169cabffb92d85567e28756f23d04fd28594de/Postmortems/2022/2022-08-17-outreach-materials-missing-recent-assets.md#event-timeline
