### ISSUE TITLE
Content-Release GHA Fails During Build Steps Downloading CMS Content

### ISSUE THREAD

**Issue by olivereri** [department-of-veterans-affairs/va.gov-cms#10311]
## Description
The GHA workflow that releases CMS content has been failing intermittently while downloading content from the CMS.

Slack Threads: 
* https://dsva.slack.com/archives/C02HX4AQZ33/p1660685929245639
* https://dsva.slack.com/archives/C01512KN35G/p1660255313754339

Log output like `[MANUAL GC] heapUsed: 414.31mB (0.02mB collected) rss: 1851.2mB (0.77mB collected)` is known and not related.

![image.png](https://images.zenhubusercontent.com/5f04cf8f49978b1615fee8c2/5efce8fd-a4e1-47f7-8d9e-9e72da29e708)

## Acceptance Criteria
- [ ] Root cause(s) of content-release build failure to download CMS content is determined and defect is mitigated
- [ ] Create followup tickets for resolution
  - [x] Log Output for content-release is improved to make visible what is happening, i.e. retries, request information, suppress successful downloads. https://github.com/department-of-veterans-affairs/content-build/pull/1273
  - [x] Datadog monitoring that mimics content-release build requests implemented

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [x] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by ElijahLynn** [comment]
Related PR https://github.com/department-of-veterans-affairs/content-build/pull/1254

**Comment by ElijahLynn** [comment]
https://github.com/department-of-veterans-affairs/content-build/blob/6b9027f7ec3109a83e7e7cc06c147f63c3c9db35/src/site/stages/build/plugins/download-drupal-assets.js#L142

`NODE_ENV=production yarn build --buildtype=vagovprod --asset-source=local --pull-drupal --drupal-max-parallel-requests=15 --verbose`

**Comment by ElijahLynn** [comment]
Tim was able to reproduce with the content-build mirror on Tugboat, fwiw. He said the response code he saw was "gateway timeout". 

https://dsva.slack.com/archives/C02HX4AQZ33/p1660686414864789?thread_ts=1660685929.245639&cid=C02HX4AQZ33

**Comment by ElijahLynn** [comment]
Copied comment from a previous [PR](https://github.com/department-of-veterans-affairs/content-build/pull/1254#issuecomment-1212575762) I closed.

So, I just verified on the PROD EFS volume that the files are stored on that we aren't reaching any throughput limits:

https://console.amazonaws-us-gov.com/efs/home?region=us-gov-west-1#/file-systems/fs-1c9ba71d?tabId=monitoring

![image](https://user-images.githubusercontent.com/1504756/184256624-f3ae2ea5-51f1-4cb0-b8f1-d22eecac0473.png)

![image](https://user-images.githubusercontent.com/1504756/184256816-c88f6a4e-31ca-4c6e-9532-7b62d0d574b7.png)

![image](https://user-images.githubusercontent.com/1504756/184256859-d83381b3-2d6f-4c27-92d4-63745cd1f712.png)

**Comment by ElijahLynn** [comment]
I tried 50 parallel downloads from my local to the Tugboat instance and it completed in 252s (4m12s), and the whole build was done in 11424s (3h 10m 24s) (must be CPU bound on my laptop):

> Step 51 end [252917ms]: Download application assets

Side note: It seems safe enough to bump the parallel downloads from 5 to 50+.

**Comment by ElijahLynn** [comment]
I tried 50 parallel downloads (through SOCKS) from local to Tugboat instance and:

> Downloaded 21290 asset(s) from Drupal            
> 7 error(s) downloading assets from Drupal        
> Step 50 end [9914985ms]: Download Drupal assets

I don't see the errors in the output though, but it looks like the timeouts did happen because 9914985ms is 165m. Now I need to figure out how to isolate just the file download step to jump past the rest of the steps. Or maybe use curl against a file list and run it async.

**Comment by ElijahLynn** [comment]
I've created a DD Synthetic to pull some images & files from prod.cms.va.gov from the PROD EKS cluster. Set to notify in Slack `#cms-notificaitons`. Working on tweaking this a bit and then exporting to Terraform.

**Comment by ElijahLynn** [comment]
Testing all the different file types:

> GET [https://prod.cms.va.gov/s[...]9-09/family-caregiver.png](https://prod.cms.va.gov/sites/default/files/styles/3_2_medium_thumbnail/public/2019-09/family-caregiver.png)
> GET [https://prod.cms.va.gov/s[...]ng-Information-Card_0.pdf](https://prod.cms.va.gov/sites/default/files/2022-08/OCC-Billing-Information-Card_0.pdf)
> GET [https://prod.cms.va.gov/s[...]osketch-sampleformat.docx](https://prod.cms.va.gov/sites/default/files/2022-07/biosketch-sampleformat.docx)
> GET [https://prod.cms.va.gov/s[...]-08/main_facility_map.gif](https://prod.cms.va.gov/sites/default/files/2021-08/main_facility_map.gif)
> GET [https://prod.cms.va.gov/s[...]dra_Booth_.jpg?h=66302ab5](https://prod.cms.va.gov/sites/default/files/styles/1_1_square_medium_thumbnail/public/2022-01/Dedra_Booth_.jpg?h=66302ab5)
> GET [https://prod.cms.va.gov/s[...]/2022-01/Dedra_Booth_.jpg](https://prod.cms.va.gov/sites/default/files/styles/1_1_square_medium_thumbnail/public/2022-01/Dedra_Booth_.jpg)

Set the test to run from the same VPC that the GHA runner is in:

![image](https://user-images.githubusercontent.com/1504756/186783932-4f4511fc-c33f-422f-9334-56335b43af53.png)

**Comment by timcosgrove** [comment]
Added logging: https://github.com/department-of-veterans-affairs/content-build/pull/1273
