### ISSUE TITLE
SPIKE: Investigate adding graphQL linting to content-build pipeline

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#10322]
## Description
We were recently bitten by a [3 year old bug tied to a malformed GraphQL Query](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/pull/552) (#10312 ).  This defect **might** have been caught it the content-build repo performed a GraphQL linting step as part of its testing pipeline.

I am not certain whether this task lives with this team or the larger platform team.  This issue can be moved to another repo if needed.

## Acceptance Criteria
- [ ] GraphQL linters are investigated
- [ ] If a winner exists, it is identified and an issue is created to add it to the content-build repo's testing steps.
- [ ] Report out the findings to determine if we should actually do the work due to the planned deprecation of graphQL
- [ ] The PR should include both Facilities Frontend and Accelerated Publishing as reviewers
- [ ] If we beta test a linter during decision making and get a tentative scope of findings / changes that would be made as a result of implementing it, share that with Tim C and Tanner on this thread: https://dsva.slack.com/archives/C03LFSPGV16/p1700165656322289

**Comment by jilladams** [comment]
Proposal that PW own this ticket: https://dsva.slack.com/archives/C03LFSPGV16/p1660835428232319

**Comment by jilladams** [comment]
@timcosgrove this is a slightly older ticket for adding a GQL linter to content-build that PW is ok taking on if it hasn't already been handled conceptually elsewhere. Would this get in your way, in terms of c-b migration? Or any concerns about us moving ahead with it?

**Comment by jilladams** [comment]
Tim has no concerns unless we impelement and the linter makes massive changes to existing GraphQL queries. This ticket is only SPIKE, so that would apply more at implementation time. But if we get an early result based on our proposed solution, we can share that early. Noted in ACs.

**Comment by jilladams** [comment]
One note that may bite us: Daniel did some minor searches, found that most of the drop-in graphQL linters out there vet against schema, and in our case the schema is defined in the Drupal GraphQL module. This might make it difficult to hook something up effectively.

**Comment by Becapa** [comment]
A couple of tools that I've looked over very briefly so far:

- GraphQL-ESLint (The Guild): This one appears to have an option that allows for syntax validation without the need for a schema.
- eslint-plugin-graphql (Apollo): Looks like you can use additional plugins with this one that retrieve a remote graphQL schema (graphql-cli or apollo-codegen).

Just wanted to put these here for now in case it's a while before I get back to this or someone else gets to it first.

**Comment by Agile6MSkinner** [comment]
@dsasser @omahane @jilladams @FranECross This ticket has been hanging around forever and AP is imminent. If we didn't address it in the almost two years since it was filed, I don't think we're going to before GraphQL is gone. Recommend closing.

**Comment by jilladams** [comment]
Agree
