### ISSUE TITLE
Keep track of time since last error + number of release attempts since last success

### ISSUE THREAD

**Issue by cweagans** [department-of-veterans-affairs/va.gov-cms#10329]
## Description

It would be helpful to keep track of (and expose to datadog) the time since last content release error + the number of build attempts since the last successful build.

## Acceptance Criteria
- [ ] New metric is tracked and sent to datadog for time since last content release error
- [ ] New metric is tracked and sent to datadog for number of build attempts since last successful build

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [x] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by TheBoatyMcBoatFace** [comment]
Closing. This metric is tracked in Datadog.
