### ISSUE TITLE
Broken link: Remove VSO link from footer 

### ISSUE THREAD

**Issue by allisonlu** [department-of-veterans-affairs/va.gov-cms#10335]
## Describe the defect
Someone took down the www.va.gov/vso site recently. This was detected by a human, and the site seemed to have been deactivated on or about 8/10. In the short-term, we should remove the link for the next site deploy. 

Dave is reaching out to the web registry team to see if there is a new destination or redirect needed. 

- Slack thread from 8/19/2022 morning: https://dsva.slack.com/archives/C52CL1PKQ/p1660917668814859

## To Reproduce
1. Go to VA.gov
2. Scroll to footer
3. Click **Veterans Service Organizations (VSOs)** under More VA resources
4. See 404 page

## AC / Expected behavior
- [ ] remove link or add redirect depending on what Dave hears (after 11am ET)

 ## Some action items to consider
- How can we get the footer links to be managed in Drupal instead of the codebase?
- Why did this slip through by our broken link detector?

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Defect")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS workstream (orange) (not needed for bug tickets)
- [ ] CMS-supported product (black)

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by jilladams** [comment]
FYI ^ VSO office came through with an updated URL, so we'll want to put it back, with a new destination. Not clear if that's urgent, checking with Dave. https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10347
