### ISSUE TITLE
Edit "About VAMC alerts and operating statuses" KB article

### ISSUE THREAD

**Issue by EWashb** [department-of-veterans-affairs/va.gov-cms#10346]
## Background

The [current article](https://prod.cms.va.gov/help/vamc/about-locations-content-for-vamcs/about-alerts-and-operating-statuses) needs information about removing operating statuses and system banner alerts. It also lacks information about GovDelivery updates and when/how they go out (this topic is only mentioned in “How to create a situation update” and “How to add a system banner alert” but should be cross-referenced)

## Acceptance Criteria

- [ ] Article is updated on both points listed in the background
- [ ] Article is reviewed by Sitewide CMS
- [ ] Article is reviewed by Helpdesk
- [ ] Article posted to KB

**Comment by xiongjaneg** [comment]
closing due to subsequent updates to this content type
