### ISSUE TITLE
Edit "How to edit a VAMC facility operating status" KB article

### ISSUE THREAD

**Issue by EWashb** [department-of-veterans-affairs/va.gov-cms#10345]
## Background

The [current article](https://prod.cms.va.gov/help/vamc/about-locations-content-for-vamcs/about-alerts-and-operating-statuses/how-to-edit-a-vamc-facility-operating-status) needs information about how to remove an outdated operating status, for example, in the event of a power outage or power outage is over. 

## Acceptance Criteria

- [ ] Article is updated
- [ ] Article is reviewed by Sitewide CMS
- [ ] Article is reviewed by Helpdesk
- [ ] Article posted to KB

**Comment by xiongjaneg** [comment]
closing due to subsequent changes to this article
