### ISSUE TITLE
Audit feature toggles for opportunities to retire

### ISSUE THREAD

**Issue by dsinla** [department-of-veterans-affairs/va.gov-cms#10350]
## Description
Request from [@RachalCassity](https://github.com/RachalCassity):  
Console Services Team is evaluating site performance, and identified feature toggles in vets-api and vets-website repos.
Feature toggles endpoint is called multiple times per page, and causes Sentry errors / site latency.

8 of the 12 feature toggles on [this list ](https://docs.google.com/spreadsheets/d/1LZjJIKZ-cteRxqwFIAbnAR2Sa32liP-5Y3WQ_UqZCKk/edit#gid=0) explicitly identify facility_locator:

Feature Flag Name | Added to vets-website | Team | Removed
-- | -- | -- | --
enrollment_verification | 6 months ago | vsa-public-websites-frontend | No
facilities_ppms_suppress_all | 12 months ago | vsa-public-websites-frontend | No
facilities_ppms_suppress_community_care | 9 months ago | vsa-public-websites-frontend | No
facilities_ppms_suppress_pharmacies | 11 months ago | vsa-public-websites-frontend | No
facility_locator_lat_long_only | 9 months ago | vsa-public-websites-frontend | No
facility_locator_lighthouse_covid_vaccine_query | 11 months ago | vsa-public-websites-frontend | No
facility_locator_show_health_connect_number | 8 months ago | vsa-public-websites-frontend | No
facility_locator_predictive_location_search | 11 months ago | vsa-public-websites-frontend | No
facility_locator_rails_engine | 11 months ago | vsa-public-websites-frontend | No
facility_locator_restore_community_care_pagination | 9 months ago | vsa-public-websites-frontend | No
facility_locator_show_community_cares | 11 months ago | vsa-public-websites-frontend | No
facility_locator_show_operational_hours_special_instructions | 11 months ago | vsa-public-websites-frontend | No

Link to [Slack convo](https://dsva.slack.com/archives/C52CL1PKQ/p1660926072198639)
Related PW [ticket](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10342)

## Acceptance Criteria
- [ ]  Audit the list of FE flipper toggles and confirm which if any are owned by Sitewide Facilities team 
- [ ]  Audit the list of [CMS based feature toggles](https://prod.cms.va.gov/admin/config/system/feature_toggle) and confirm which if any are owned by Sitewide Facilities team 
- [ ]  Assess whether any / all can be removed, and summarize task steps & take a stab at effort

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by swirtSJW** [comment]
This should be done on a joint call with PWS, Facilites and Dave Conlon as well as a CMS engineer and a FE engineer from both teams.

On the call, engineers will need to search all three code bases for each flag to determine if they are used anywhere and can be removed.

**Comment by dsinla** [comment]
Meeting held today 08/30. @swirtSJW @jilladams who is doing the _summarizing task steps and taking stab at effort_?

**Comment by dsinla** [comment]
Closing - audit completed. Executing will be done next sprint https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10656
