### ISSUE TITLE
CMS Post-Deploy Test failure notifications should not alert @here

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-cms#10363]
## Description
IMHO.  @olivereri I think that these should alert `@cms-devops-engineers` and/or `@cms-qa-engineers`, whenever the latter group gets created in Slack.  Thoughts?

**Comment by cmaeng** [comment]
@ndouglas @EWashb @dawnpruitt Platform CMS team will take this on for sprint 67. removing the Sitewide CMS team label for now and will ping y'all once complete.

**Comment by ElijahLynn** [comment]
http://jenkins.vfs.va.gov/job/testing/job/cms-post-deploy-tests-staging/ and http://jenkins.vfs.va.gov/job/testing/job/cms-post-deploy-tests-staging/. File is here https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/Jenkinsfiles/cms/cms-post-deploy-tests.groovy#L46.

**Comment by ElijahLynn** [comment]
PR here https://github.com/department-of-veterans-affairs/devops/pull/11935

**Comment by ElijahLynn** [comment]
Merged, closing.
