### ISSUE TITLE
Drupal: implement Entityqueue module

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#10374]
## Description
SPIKE: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10327
Specific context: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10327#issuecomment-1221156445

CMS - ~1 day

1. Module install & config
2. Create queue / queue permissions
3. ~~Might require 2 releases (install, then generate content, as sometimes module install doesn't work correctly to also create the queue at the same time)~~ A single deploy is all that is necessary; the queue is a config entity, so it is deployable in a single release.

## Acceptance Criteria
- [ ] Entityqueue is installed & configured with permissions for Drupal Admins to create / configure queues (for now)
- [ ] A queue is created to manage nodes that should not publish to production
- [ ] Handoff final details to FE _on_ the front-end ticket

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [X] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by dsasser** [comment]
PR: https://github.com/department-of-veterans-affairs/va.gov-cms/pull/10376

This PR sets up a new entityqueue (the module itself was already enabled and in use). The following GraphQL query can be used to fetch the queue items for the FE:

```
fragment subQueue on EntitySubqueue {
  name
  items {
    targetId
  }
}

query myQuery {
  entitySubqueueQuery(filter:{
    conditions: [{field: "name", value: "staged_content"}]
  }) {
    __typename
    entities {
      ... subQueue
    }
  }
}
```
