### ISSUE TITLE
CMS Audit VAMC Contact Us pages for Support for Law Enforcement and First Responders or Support for first responders

### ISSUE THREAD

**Issue by dsinla** [department-of-veterans-affairs/va.gov-cms#10378]
## Description
We want to know all VAMC Contact Us pages that have a section 'Support for Law Enforcement and First Responders' or 'Support for first responders'.  Looks like these sections are in Facility Detail pages, inside RTFs, with H2 headlines.

Perhaps we search for any H2 that starts with or contains the string "Support" ? 

![image](https://user-images.githubusercontent.com/62269210/186013055-c0eb7fb9-a311-460a-89f6-976566d99bac.png)

## Acceptance Criteria
- [ ] A report is produced for all pages that match the criteria

The report should list:

- Facility Name,
- NodeID (?) 
- The text of the header: **Support for Law Enforcement and First Responders** or **Support for first responders**  - or possibly any H2 that starts with **Support** ?

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by JayDarnell** [comment]
I was unable to find this data using existing views but was able to quickly throw together a view locally to get the data. That said, I was surprised to only find three VAMC Detail pages containing a Rich Text paragraph with this text. Do we have a sense for how many of these there should be?

**Comment by JayDarnell** [comment]
[vamc_contact_us_support_audit.xlsx](https://github.com/department-of-veterans-affairs/va.gov-cms/files/9529671/vamc_contact_us_support_audit.xlsx)

**Comment by dsinla** [comment]
Thanks @JayDarnell 
From what I understand, this is the result of a campaign where all sites were trained to potentially create a QR code and link to this new "Support for..." section. The instigator of this request is using _this report_ to evaluate how many sites adopted - so he's looking to us to tell him.

For clarity, can you tell me your specific search criteria? Something like: _All Contact Us pages that contained the text "Support for" within an H2_   

Thanks!

**Comment by dsinla** [comment]
Sent table to requestor:  Wehrer, Michael
Marking closed
