### ISSUE TITLE
Front-end: implement EntityQueue module to prevent specified nodes from publishing to prod

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#10375]
## Description
SPIKE: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10327
Specific context: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10327#issuecomment-1221156445

**GraphQL notes**: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10375#issuecomment-1223019683

**FE** - 3-4 days
* Query the entity queue, gather the nodes we're ignoring
* Find a spot in the build logic to process this queue / entity data to pull it out of the prod build
* Code will be minimal, time spent will be more finding the right spot
* Testing + content-build 

1095B is scheduling UAT for 9/6-9/7: implication = this would need to be merged by Thurs 9/1 EOD. If that's not possible, let Jill know.
Blocked by #10374 

## Acceptance Criteria
- [ ] Nodes specified in the queue built in #10374 do not appear in production builds

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [X] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by jilladams** [comment]
Note: in Sprint 65, Ryan is assigned to a SPIKE ticket around sentry / forms, which takes priority. This ticket may get started toward end of week, but will not complete during S65 / will roll into S66.

**Comment by dsasser** [comment]
GraphQL example query for Queued Items:
```
fragment subQueue on EntitySubqueue {
  name
  items {
    targetId
  }
}

query myQuery {
  entitySubqueueQuery(filter:{
    conditions: [{field: "name", value: "staged_content"}]
  }) {
    entities {
      ... subQueue
    }
  }
}
```

**Comment by jilladams** [comment]
Since this didn't get rolling this sprint and was stretch anyway, not gonna report it in S65, and moving to S66.

**Comment by jilladams** [comment]
Launch steps, for the histories:

- @Khandelwal’s React widget code needs to be merged to main / deployed in vets-website. We believe that can happen now, assuming no other page is published that would call this app? It's advisable to have the app live prior to the other changes.
- Our entityqueue changes will complete code review tomorrow. If no blockers, changes will go out with content-build daily deploy on Tues 9/6, ~2pm ET finishing by ~3
- Once live, we need to add the 1095b node ID to the CMS configuration that allows publishing to Staging only
- Once added, 1095B team will need to publish the page. (Or we can do that for you, with your approval.)
- The page will go live to Staging in the next content-release (or we will trigger a content-release)
- And then: CMS node will be live, in Staging only, showing the React widget

This means that by Tuesday end of day, all of the CMS + content-build changes should be live & verifiable on Staging.

1095B work transitions on 9/7 to new team, comms with everyone here:
https://dsva.slack.com/archives/C52CL1PKQ/p1662072188434589?thread_ts=1661186508.027519&cid=C52CL1PKQ

**Comment by jilladams** [comment]
https://dsva.slack.com/archives/C52CL1PKQ/p1662560358964149?thread_ts=1661186508.027519&cid=C52CL1PKQ
