### ISSUE TITLE
Handle daylight savings for business hours calculation

### ISSUE THREAD

**Issue by cweagans** [department-of-veterans-affairs/va.gov-cms#10383]
Right now, any business hours calculation in va_gov_build_trigger doesn't care about DST at all. It needs to know about it and properly support it.

### Acceptance Criteria:
- [ ] Daylight saving time is properly handled for scheduled releases, continuous releases, and any business-hours-only metrics calculations that are done in va_gov_build_trigger

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [x] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by swirtSJW** [comment]
It would be good to have this prioritized so that it lands prior to Nov 6th
![image](https://user-images.githubusercontent.com/5752113/186273624-317102e9-1761-4bd9-94d8-e9f340d5fe65.png)

**Comment by ElijahLynn** [comment]
We discussed in refinement that maybe we can just run from 8-6 OR run it 24/7, then we don't need to add this complexity.

**Comment by cweagans** [comment]
This is a slightly higher estimate than you might expect because testing timezone-related things can be tricky. Better to have a little extra time to test this properly.

**Comment by ElijahLynn** [comment]
> This is a slightly higher estimate than you might expect because testing timezone-related things can be tricky. Better to have a little extra time to test this properly.

Truth. Time stuff is always harder than it appears.

**Comment by cmaeng** [comment]
this may be a non-issue based on the way we specify time-zone. it looks to have behaved as expected over this past weekend.

**Comment by timcosgrove** [comment]
This is not needed. Closing.
