### ISSUE TITLE
Create curriculum outline for VAMC system training

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#1038]
In mid-to-late August, we will be training VAMC staff from VISN 4, and 

AC
- [ ] Howie is familiar with current VAMC product
- [ ] We have a curriculum against which to design training modules 
- [ ] Curriculum parallels Rachel's VAMC system user guide
- [ ] Training approach is defined

**Comment by howardbrande** [comment]
Moving back to to-do due to Coronavirus impacting when the rest of VISN-4 facilities will be rolled out
