### ISSUE TITLE
Redirect Request for: flu-shot

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#10402]
### Instructions
- This issue will be used from initial request through implementation to ensure all individuals working on this are notified of status updates.  Please do not create multiple issues to track different steps.
- It is your responsibility to notify VA stakeholders as appropriate.
- Be sure to link the related facility closure / rename issue.
- Front end redirects are tracked in the [devops](https://github.com/department-of-veterans-affairs/devops) repo in `ansible/deployment/config/revproxy-vagov/vars/redirects.yml`

### Implementation date
When does this request need to be live:  TBD, Dave input

### Redirects 
| Current URL  |  Redirect Destination or New URL |
| ---  |  --- |
| /flu-shot | TBD |

It currently redirects to https://www.va.gov/initiatives/flu/, but VHA digital media wants to redirect to new destination, TBD: https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/revproxy-vagov/vars/redirects.yml#L2564

### Acceptance Criteria
- [ ] Redirect is updated to new URL
- [ ] Confirm redirect after prod deploy before closing ticket

## CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [X] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by wesrowe** [comment]
@jilladams, please comment anything you know about when this redirect request might be finalized. Or we can ping Dave if it's unknown.

**Comment by jilladams** [comment]
I haven't heard anything about timing. Will ask Dave.

**Comment by jilladams** [comment]
Per Dave sync today: Jenny H-L / @DanielleThierryUSDSVA  working on plan, so timing TBD their decisions.

**Comment by jilladams** [comment]
Dupe of #11036
