### ISSUE TITLE
Update footer link for "VA health care providers"

### ISSUE THREAD

**Issue by dsasser** [department-of-veterans-affairs/va.gov-cms#10405]
## Description
Update the link text and link destination for the "VA health care providers" footer link.

![image.png](https://images.zenhubusercontent.com/628fa5e0de11802be559ed62/21398004-1d7a-411a-8b18-15d85ddec64c)

New Link text: VA health care access and quality (SWC provided on [46237](https://github.com/department-of-veterans-affairs/va.gov-team/issues/46237))
New Link URL:  https://www.accesstocare.va.gov/

## Acceptance Criteria
- [ ] New footer link appears correctly on mobile
- [ ] New footer link appears correctly on desktop

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by jilladams** [comment]
Verified on prod: 
![Screen Shot 2022-09-16 at 2 38 54 PM](https://user-images.githubusercontent.com/85581471/190792375-693a94c8-31be-4acf-a579-b0b98afe6bc7.png)
