### ISSUE TITLE
Finalize questions for the Editors' satisfaction survey 

### ISSUE THREAD

**Issue by jordanamello** [department-of-veterans-affairs/va.gov-cms#1040]
## Description
Before writing the official survey content (crafted questions + scales), let's write down what we want to know/measure, considering Editors' satisfaction with _support_ and _content ops_.

## Acceptance Criteria
- [x] Rachel added questions
- [x] Howie added questions
- [x] Kevin added questions
- [x] Jordana added questions
- [x] We groomed the questions together
- [x] Questions sent to Kevin Hoffman for review
- [x] Questions updated. 

[Add your questions here!](https://docs.google.com/spreadsheets/d/13nWUY11A84c4WmC6vVmSE42OHaywPir5Eil4orBZz5Q/edit#gid=0)

**Comment by kevwalsh** [comment]
i feel like onboarding and training questions should definitely be asked, but not repeatedly.  Do we want to separate out the kinds of questions that we would want to ask once, vs ongoing?
