### ISSUE TITLE
[CONSIDER] Performance page changes

### ISSUE THREAD

**Issue by dsinla** [department-of-veterans-affairs/va.gov-cms#10406]
## Description
The Access to Care site relaunch has changed some things. The Performance page that is on each VAMC website (e.g. https://www.va.gov/boston-health-care/about-us/performance/) may soon no longer make sense. We will want to chart a path forward on this.

1.  Determine if we should repurpose the "Performance" page?
2.  Should we use Facility-level pages?
3.  Should we harden the page and swap out the existing pages with the new pages.

Specifically:

- The links to “get average VA appointment times” and “learn about veteran satisfaction…” should be replaced with a single link to ATC's  [facility performance page](https://www.accesstocare.va.gov/FacilityPerformanceData/FacilityData?stationNumber=558) with the selected facility displayed by default. Note: Facility IDs should be the same as we both use VAST IDs.
- Consider: Add a “find Providers” link to ATC [provider search](https://www.accesstocare.va.gov/OurProviders) with the selected facility and facility type set by default. Will likely require some collaboration between us and ATC's development teams and likely VAMC editors.
- The link to “compare quality of health care” should go to ATC's [Hospital Compare webpage](https://www.accesstocare.va.gov/Healthcare/HospitalCompareData) possibly with the specific facility selected. (Note: This likely won't work because the data is incomplete/mismatched)

## Acceptance Criteria
- [ ] Testable_Outcome_X
- [ ] Testable_Outcome_Y
- [ ] Testable_Outcome_Z
- [ ] Requires design review

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by davidconlon** [comment]
Assigning this to myself to work through details with JHL

**Comment by mmiddaugh** [comment]
closing this as a duplicate to #10910 (I moved over the pearls first)
