### ISSUE TITLE
Healthcare React widgets: Update Cerner CTA URLs to remove clear-session and url-encoded path

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#10417]
### Description
My VA Health now uses SLO. WIth that implementation, some React widget URLs need to update, for both Staging & Production URLs.  Current URLs include `/clear-session` and url-encoded path, which is causing issues with certain test scenarios involving 2 users  (test case details below). To resolve it, Public Websites has been asked to update the path for these CTAs. Cerner cutover testers will then verify in test environment.
  
Why: redirect URLs from VA.gov or My HealtheVet to My VA Health should not need clear-session (VA specific local logout) in a future state (due to VA implementing SLO), and the user would go directly to the URL requested.  This would assist with streamlining the redirects a user experiences during log in.

### Updates 
**Current URL construction:** 
e.g.
https://staging-patientportal.myhealth.va.gov/clear-session?to=https%3A%2F%2Fstaging-patientportal.myhealth.va.gov%2Fpages%2Fscheduling%2Fupcoming%3Fauthenticated%3Dtrue 

https://patientportal.myhealth.va.gov/clear-session?to=https%3A%2F%2Fpatientportal.myhealth.va.gov%2Fpages%2Fscheduling%2Fupcoming%3Fauthenticated%3Dtrue

[/src/platform/utilities/cerner/index.js#L36](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/platform/utilities/cerner/index.js#L36) 
```
  return `${host}/clear-session?to=${encodeURIComponent(
    `${host}${path}?authenticated=true`,
```
host = staging-patientportal.myhealth.va.gov/ or patientportal.myhealth.va.gov
path = pages/scheduling/upcoming

**Updated URL construction**
https://staging-patientportal.myhealth.va.gov/pages/scheduling/upcoming?authenticated=true, e.g. 

```
  return `${host}?authenticated=true`,
```

More info in comment: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10417#issuecomment-1226256948

### Widgets where this applies
Scheduling
Messaging
Lab Results
Pharmacy
get VA medical records
My VA Health Home Page -- this one was also listed but I'm not clear on where / how it appears. Presumably the same change will apply here and testers will confirm.

### Test cases, for reference
We currently do not have test users to verify this ourselves, but Anthony Diaz will test this flow in test instance once it's available from PR:

**Test case 1:**
1. Go to /health-care/refill-track-prescriptions
2. Click to login
3. Use ID.me
  - U: user 1 email (dm Jill for it)
  - P: (dm Jill for it)
4. Continue (skip 2fa code)
5. Continue (submit ID.me login, with dummy 2fa code)
6. Session security error - Send anyway
7. You get redirected to /health-care/refill-track-prescriptions/?postLogin=true
8. Go to My VA Health with user 1
9. Go back to [va.gov](http://va.gov/) and logout
10. Login to [va.gov](http://va.gov/) with user 2
11. Navigate to My VA Health and ensure user 1 is NOT still logged in.  Instead, user 2 should be logged in.

**Test case 2:**
1. Go to /health-care/refill-track-prescriptions
2. Click to login
3. Use ID.me
  - U: user 1 email (dm Jill for it)
  - P: (dm Jill for it)
4. Continue (skip 2fa code)
5. Continue (submit ID.me login, with dummy 2fa code)
6. Session security error - Send anyway
7. You get redirected to /health-care/refill-track-prescriptions/?postLogin=true
8. Login to My HealtheVet go to My VA Health with user 1
9. Go back to VA.gov and logout
10. Login to My HealtheVet with user 2
12. Navigate to My VA Health and ensure user 1 is NOT still logged in.  Instead, user 2 should be logged in. 

## Acceptance Criteria
- [x] CTAs are updated with correct URLs
- [x] Provide test instance to Jill for relay with testers, once change is up
- [ ] DO NOT MERGE until testers have verified the change

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [X] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by jilladams** [comment]
From discussions with @ryguyk  / @allisonlu : 
1. Cerner primary CTA button URLs are defined in `getCernerURL` function :  [src/platform/utilities/cerner/index.js#L31](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/platform/utilities/cerner/index.js#L31)
2. Paths are provided to that function from within the static-page for each React widget, e.g. [src/applications/static-pages/health-care-manage-benefits/get-medical-records-page/components/AuthContent/index.js#L32](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/static-pages/health-care-manage-benefits/get-medical-records-page/components/AuthContent/index.js#L32)

If the ask is to just remove `/clear-session` we think [/src/platform/utilities/cerner/index.js#L36](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/platform/utilities/cerner/index.js#L36)  & 37 becomes:
```
  return `${host}?to=${encodeURIComponent(
    `${host}${path}?authenticated=true`,
```

And if the ask is to redirect without /clear-session && no query params: 
```
  return `${host}/${path}`,
```


**Not immediately relevant, but stuff also learned:**
Secondary CTA in some Cerner widgets use MyHealthVet paths for deeplinking, from function `mhvURL`: [src/platform/site-wide/mhv/utilities.js#L21](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/platform/site-wide/mhv/utilities.js#L21)

And paths are passed in similary, e.g. [src/applications/static-pages/health-care-manage-benefits/get-medical-records-page/components/AuthContent/index.js#L31](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/static-pages/health-care-manage-benefits/get-medical-records-page/components/AuthContent/index.js#L31)

**Comment by jilladams** [comment]
Verified with Anthony that the intention is to end up with:
https://staging-patientportal.myhealth.va.gov/pages/scheduling/upcoming?authenticated=true, e.g. 
```
  return `${host}?authenticated=true`,
```
When we have code in a test environment, Tony is willing to help test. Ideally, we'd get this up for test first thing next week, in support of launch targets on their end. Updating ACs.

**Comment by allisonlu** [comment]
PR opened on `vets-website`: https://github.com/department-of-veterans-affairs/vets-website/pull/22037, but is failing one irrelevant unit test, which I think is preventing Github from spinning up a review instance.

**Comment by allisonlu** [comment]
@jilladams Here's the review instance! 

http://fb8379bb8f97237749ff98aa7311dac2.review.vetsgov-internal/

**Comment by jilladams** [comment]
Thanks! Emailed to Tony Diaz for testing.

**Comment by jilladams** [comment]
So, weird stuff. Did a demo with Tony, since he's not in Platform roster / no SOCKS / can't access Review Instances. (oops, someday I'll remember that)

## Repro: 
1. Go to /health-care/refill-track-prescriptions
2. Click to login
3. Use ID.me
  - U: ssoissoetesting+wallawalla@gmail.com
  - P: (dm Jill for this)
4. Continue (skip 2fa code)
5. Continue (submit ID.me login, with dummy 2fa code)
6. You get redirected to /health-care/refill-track-prescriptions/?postLogin=true
7. **Review instance behavior:** On this page, the React widget shows only the MyHealtheVet CTA.  
**Expected behavior:** It should look like Staging (logging in same steps/same user), where both MyHealtheVet and My VA Health CTAs show.

**http://fb8379bb8f97237749ff98aa7311dac2.review.vetsgov-internal/health-care/refill-track-prescriptions/**
![Screen Shot 2022-08-30 at 2 09 02 PM](https://user-images.githubusercontent.com/85581471/187545137-91976899-44d6-4ac7-aacd-6d7c7bf41f17.png)

vs.

**https://staging.va.gov/health-care/refill-track-prescriptions/?postLogin=true**
![Screen Shot 2022-08-30 at 2 08 56 PM](https://user-images.githubusercontent.com/85581471/187545119-820bb29a-48b3-4504-a2bb-a57337a7e027.png)

I can't imagine that any of the [changes in this PR](https://github.com/department-of-veterans-affairs/vets-website/pull/22037/files) would disappear the My VA Health CTA. Is there a chance that somehow the review instance data is out of sync with what's in Staging or something? Maybe worth chatting with Ryan about it, if there's no obvious smoking gun?

**Comment by jilladams** [comment]
Noted in mid-sprint check in: at risk due to timing / transition plans / ability to repro. Have asked Tony re; priority / timing for launch and haven't heard back.

**Comment by wesrowe** [comment]
I just took a deeper look at the comments above. Jill mentioned maybe the data is out of sync in the preview instance – that would be my first guess. The preview UI looks like what you'd expect for a Veteran who is not associated with any Cerner systems. So the first point of debugging I would recommend is to look at the systems in the user's data.

**Comment by jilladams** [comment]
From discussion with Ryan: 
* We realized other teams call this function and we don't know with confidence that this change should apply to them
* To mitigate: We will add a parameter to the function that our widgets can call to get the new behavior, but other widgets using this function won't be affected by it.
  * This creates an either/or approach that will be tech debt to remove once every widget that calls this code has adopted the new path without clear-session

We'll plan to review with Tony early next week.

**Comment by jilladams** [comment]
Staging test now that code has merged: 

**Test Case 1 passes first time:** 
* login in with User 1
* Enter ID.me creds, submit, skip 2fa, redirected to prescription page, logged in
* Click My VA Health, get redirected & logged in correctly
* logout of VA
* login with user 2
* My VA Health shows user 2 successfully logged in

**Test Case 1, second time:** 
* login in with User 1
* Enter ID.me creds, submit, skip 2fa
* Get redirected back to login: https://staging.va.gov/sign-in/?application=myvahealth&to=%2Fsession-api%2Frealm%2Ff0fded0d-d00b-4b28-9190-853247fd9f9d%3Fto%3Dhttps%253A%252F%252Fstaging-patientportal.myhealth.va.gov%252F%253FloginFailure%253D5c595f95dabac0da18733ab21dfe3a5f%2526errorCode%253Durn%25253Acerner%25253Aerror%25253Aidentity-federation%25253Asaml2%25253Asecurity%25253Asession-terminated-by-idp

This loop repeats several times. If I manually take myself to the Prescription page, I have been logged in. If I try to click through to My VA Health, I get sent back to the URL above.

**Test Case 1, third time:** 
* Closed tabs, cleared cache / hard reload, start again from a logged out state
* go to Rx page
* login in with User 1
* Enter ID.me creds, submit, skip 2fa, redirected to https://staging.va.gov/my-va/?postLogin=true
* Take myself back to Rx page
* Click through to My VA Health
* Land on https://sqa.eauth.va.gov/accessva/?cspSelectFor=https%3A%2F%2Fstaging-patientportal.myhealth.va.gov%2Fsession-api%2Fprotocol%2Fsaml2%2Fmetadata&ForceAuthn=false, do not appear to be logged in
* Login with ID.me, get put in the same login loop: https://staging.va.gov/sign-in/?application=myvahealth&to=%2Fsession-api%2Frealm%2Ff0fded0d-d00b-4b28-9190-853247fd9f9d%3Fto%3Dhttps%253A%252F%252Fstaging-patientportal.myhealth.va.gov%252F%253FloginFailure%253D7c268c2fda746501c7f8b15909b6fd5f%2526errorCode%253Durn%25253Acerner%25253Aerror%25253Aidentity-federation%25253Asaml2%25253Asecurity%25253Asession-terminated-by-idp



**Test Case 2: fail**
* Login with User 1
* go to My HealtheVet
* get sent to an auth screen after ID.me redirect, https://sqa.eauth.va.gov/mhv-portal-web/eauth?deeplinking=prescription_refill
* Login error with the provided credentials

**Comment by jilladams** [comment]
From review with Tony Diaz: 
* My HealtheVet may not have implemented the necessary auth pieces for Test Case 2 to work yet. Tony to follow up with Dimitar Tzvetanov (UAT tester / SQA manager, MyHealtheVet)
* Linday Lowery (Cerner / My VA Health portal) specified: 
  * If SLO is working correctly,  you should never need the clear-session added to the path.  My recollection is that it’s the “authenticated=true” parameter that will determine whether or not an unauthenticated user will see the AccessVA sign in page.  
  * If the user is not authenticated with an SSOe session, then do not send authenticated=true.  This will prevent the AccessVA sign in page from showing.  
  * If they are authenticated with an SSOe session, then send the authenticated=true param, and we will bypass a few unnecessary steps in the login process to make it faster.  Please let us know if that’s not what you are seeing.
* Our implementation matches the SSOe reco: 
  * Tony also verified that from staging, the login prompts use SSOe 
  * we are still sending `?authenticated=true` ([code](https://github.com/department-of-veterans-affairs/vets-website/pull/22037/files#diff-c1a951be638f03d2a97d627519f3960656a1016824f10577f29567ede82b4302R36))

So: should be working but isn't. Next step: Follow up with the Email thread, "My HealtheVet redirects to My VA Health with SLO" to request troubleshooting help.

**Comment by jilladams** [comment]
Email out to Cerner/MHV/MyVAHealth folks with report of our bugs. Joe Niquette's team to review with us on a call 10/12.

**Comment by jilladams** [comment]
Synced with Joe Niquette, who is VSP Identity. Their team isn't looped on the test cases we were provided, but had some general notes about auth scenarios. Ultimately: we have updated the path as requested, and logged-in users are now presented (on Staging, when Flipper is enabled) with the requested URL, so I've proposed handing this back to Tony & co for further testing.  Looped in Danielle Thierry [via Slack](https://dsva.slack.com/archives/C52CL1PKQ/p1665693968412469), since Dave is OOO for awareness.

**Comment by jilladams** [comment]
Moving to mark this blocked again til we hear back from Tony.

**Comment by jilladams** [comment]
Email out to Tony Diaz re: any updates here so we can get this off our board.

**Comment by jilladams** [comment]
This effort has fully died. Closing, and we can reopen if they ever revive.
