### ISSUE TITLE
Redirect Request

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-cms#10414]
### Type of request
- [X] We are retiring or taking down a page and need to redirect the URL (complete redirect section)
- [ ] We are changing the URL of an existing page (complete redirect section)
- [ ] We need a custom vanity URL (complete vanity URL section)

### Implementation date
When does this request need to be live: No hard deadline, but ideally within the next week or so.  
**Target: 1st week of Sprint 66**

### Redirects 
| Current URL  |  Redirect Destination or New URL |
| ---  |  --- |
| https://www.va.gov/COMMUNITYCARE/revenue_ops/billing.asp (and all casing variations) | https://www.va.gov/health-care/pay-copay-bill/ |
| https://www.va.gov/COMMUNITYCARE/revenue_ops/Financial_Hardship.asp (and all casing variations) | https://www.va.gov/health-care/pay-copay-bill/financial-hardship/ |
| https://www.va.gov/COMMUNITYCARE/programs/veterans/Health_Insurance.asp (and all casing variations) | https://www.va.gov/health-care/about-va-health-benefits/va-health-care-and-other-insurance/ |

## Acceptance criteria
- [ ] Redirects need to catch all casing variations of the sub-directories in the URL. Legacy pages are often live at different casing variations. For example, e.g.  /**COMMUNITYCARE**/revenue_ops/billing.asp and /**communitycare**/revenue_ops/billing.asp
- [ ] Verify redirects are working in production before closing ticket

### Process, Roles and Responsibilities
- [X] Requesting team: Above information is provided
- [X] Requesting team: All appropriate VA stakeholders are notified as appropriate
- [X] IA: Request is vetted and documented and implementation plan is clear 
- [X] IA: Request is assigned to appropriate team for implementation 
- [ ] Implementation team: Work is complete
- [ ] Implementation team: Validated in production
- [ ] Requesting team: Validates everything is correct in production and closes ticket

**Comment by allisonlu** [comment]
PR opened on `devops`: https://github.com/department-of-veterans-affairs/devops/pull/11843

**Comment by allisonlu** [comment]
PR is merged, they're holding off the deploy to prod until the other redirect PR gets merged too

**Comment by allisonlu** [comment]
Redirects are happening on prod 🎉

**Comment by DanielleThierryUSDSVA** [comment]
Yay! Thanks so much, @allisonlu!
