### ISSUE TITLE
Change management for COVID status post-launch effort

### ISSUE THREAD

**Issue by dsinla** [department-of-veterans-affairs/va.gov-cms#10410]
The change represented by the epic # will [copy selection from epic].
 
**1. Describe the change from the perspective of VA employees, in plain language. What is the employee going to experience with this change?**

Before the new use of Covid Status can roll out, it is important that the supplemental status terms contain the nationalized text

Below is the text, with "Low" and "Medium" updated from https://github.com/department-of-veterans-affairs/va.gov-team/issues/53555#issuecomment-1431982352 and "High" remaining the same.

Low
Everyone must wear a mask in most areas where Veterans are present. Check for signs when you arrive so you know what’s required.
Visitors are welcome.
Please self-screen. If you've had any COVID-19 symptoms in the past 48 hours, call first unless you need care now.
[Check COVID-19 symptoms on the CDC website](https://www.cdc.gov/coronavirus/2019-ncov/symptoms-testing/symptoms.html)
Check on Mondays for each facility’s latest guidelines.

Medium
Everyone must wear a mask in most areas where Veterans are present. Check for signs when you arrive so you know what’s required.
Your care partner is welcome (no other visitors).
Please self-screen. If you've had any COVID-19 symptoms in the past 48 hours, call first unless you need care now.
[Check COVID-19 symptoms on the CDC website](https://www.cdc.gov/coronavirus/2019-ncov/symptoms-testing/symptoms.html)
Check on Mondays for each facility’s latest guidelines.

High
Everyone must wear a mask and practice physical distancing.
We may screen you for COVID-19 symptoms at the entrance.
Approved visitors only. Ask your care team who can visit.
Ask your team about phone or video appointment options.

**2. Explain why the change is necessary from a CMS/platform and project goal perspective. Link to screenshots if that helps tell the story.**

**3. Select the role(s) impacted by the change.**
- [ ] All CMS users
- [ ] All CMS editors
- [ ] Vet Center editor
- [x] VA Medical Center editor
- [ ] VA Outreach Hub editor
- [ ] VA Benefits Hub editor
- [ ] Campaign landing page editor
- [ ] VA Resources and Support editor
- [ ] Offices editor
- [ ] Supporting roles such as CMS account admin, Facilities or Public websites team member

**4. How will success be measured for this change?**
- [x] No help desk support is needed, as measured through help desk tickets
- [ ] The content adheres to VA policies and standards for VA.gov, as measured through a dashboard tool and/or audit

**5. Does the change require new or updated:**
- [x] Knowledge Base article(s)
If existing articles, list URLs:
- [ ] Training video(s)
If existing videos, list URLs:
- [ ] CMS UI support
- [ ] Announcement block

**6. Will the change be tested with users before release?**
- [ ] Yes
- [x] No

**7. Are there any known dependencies?**

**Comment by davidmpickett** [comment]
Will need to add updating relevant KB articles

**Comment by Dottisea** [comment]
Juat waiting for the launch blocker to be remedied (
