### ISSUE TITLE
Ensure drupal assets defined in next-build are downloaded to content-build

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#10419]
## Description
Content-build identifies assets (images, pdfs, etc) that require downloading to by parsing the HTML content-build is creating for source URLs and adding them to the files that need to be built.

Next-build stores nearly all its content in a page-specific Javascript file. These files are not parsed when determining what files should be added to the build. Any assets contained in these files should be added to the list of files to download.

Note: if all the work done to move CMS image storage to public S3 is complete, this will no longer be necessary.

## Acceptance Criteria
- [ ] Any assets that are defined in a next-build page are downloaded along with other content-build assets, and included with eventual deployment
- [ ] Those assets are accessible by the next-build page when viewed via the content-build server

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by TheBoatyMcBoatFace** [comment]
Closing due to upcoming S3 Transition. Per @timcosgrove's [above comment.](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10419#:~:text=Note%3A%20if%20all%20the%20work%20done%20to%20move%20CMS%20image%20storage%20to%20public%20S3%20is%20complete%2C%20this%20will%20no%20longer%20be%20necessary.)
