### ISSUE TITLE
CMS Add additional VBA Facility fields from Lighthouse

### ISSUE THREAD

**Issue by JayDarnell** [department-of-veterans-affairs/va.gov-cms#10421]
## Description

The following fields need to be added to the VBA Facility content type. 
https://docs.google.com/spreadsheets/d/1COh-XtBeA6IKmUyatmTPrFVhYoyqlH4PTjAttqbA7EI/edit#gid=0

Use the VAMC Facility content type as a reference, reusing all fields except for field_facility_classification. For that field we'll want to create a new one: field_facility_vba_classification which is identical in every way except for the available values:

- IDES Site
- Pre-Discharge Site
- Regional Benefit Office
- Satellite Office
- Seamless Transition Integrated Care Clinic (STICC)
- Veteran Readiness and Employment Office
- VetSuccess On Campus

Behat tests for the content model will also need to be updated to reflect these new fields.

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by omahane** [comment]
@swirtSJW Do you have a sense of what you think the form display should be? I was starting to move the fields around when I realized I wasn't sure what made sense. I could make it look as much like VAMC as possible, but I wanted to be sure if that was the expectation. I'm including a screenshot that shows the differences right now before I've moved the new fields around.
![Screen Shot 2022-09-01 at 2 03 35 PM](https://user-images.githubusercontent.com/766573/187994341-219121ab-f0d8-466a-8b74-dbefbc653cef.png)

**Comment by omahane** [comment]
Form display for admins looks good now, judging from its similarity with VAMC Health Facility.
![Screen Shot 2022-09-07 at 9 00 15 AM](https://user-images.githubusercontent.com/766573/188901002-1bb529eb-c467-454f-918b-4efb32f40a36.png)
