### ISSUE TITLE
Inconsistent vhost config for demo environments

### ISSUE THREAD

**Issue by jonpugh** [department-of-veterans-affairs/va.gov-cms#1042]
New "docs" demo site does not return from apache (CMS or WEB)
http://docs.demo.ci.cms.va.gov/

Ethan's demo site does: http://ethan.demo.ci.cms.va.gov/

http://ethan.demo.ci.cms.va.gov/ and http://ethan.web.demo.ci.cms.va.gov/ work fine.

Domain                                             |    Status   
----------------------------------------|------------
http://weekend.demo.ci.cms.va.gov  | ❌ 
http://docs.demo.ci.cms.va.gov         |    ❌ 
http://howie.demo.ci.cms.va.gov       |   ❌

**Comment by ElijahLynn** [comment]
Is this intermittent? It is resolving now.
![image](https://user-images.githubusercontent.com/1504756/75214347-13cecf00-5742-11ea-82bd-29abbec6fe0c.png)

**Comment by jonpugh** [comment]
@ElijahLynn and I are debugging now.

**Comment by jonpugh** [comment]
@ElijahLynn That screenshot shows the problem: default apache vhost page.

**Comment by ElijahLynn** [comment]
Work was done to configure vhosts in DevShop. Need to know if that work was committed to devops repo branch.
