### ISSUE TITLE
Update to config_split 2.x

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-cms#10427]
## Description
[Config Split](https://www.drupal.org/project/config_split/) is in the RC stage for its 2.x release, and from glancing at the releases page, there are some non-trivial changes.

Config Split is a critical component of how we configure production, and unexpected behavior could cause huge issues, so we should vet this major version release pretty carefully.

## Acceptance Criteria
- [ ] Config Split 2 is tested on each environment by:
  - [ ] Importing and exporting config and not seeing any discrepancies
  - [ ] Spot-checking individual split config objects and confirming that they have the expected values
  - [ ] All tests (if any are configured for that environment) pass as expected
- [ ] The above criteria are validated on:
  - [ ] Tugboat (this was implied)
  - [ ] CMS-Test Dev
  - [ ] CMS-Test Staging
  - [ ] CMS-Test Prod

**Comment by ndouglas** [comment]
They've recently released a fifth release candidate. v1 is D10-ready, as I understand it. There's no need to work on this at this time.

**Comment by maortiz-27-80** [comment]
@ndouglas - Are we able to close this ticket?  cc: @BerniXiongA6

**Comment by ndouglas** [comment]
uh, sure!
