### ISSUE TITLE
Placeholder: continuous deployment for CMS

### ISSUE THREAD

**Issue by cweagans** [department-of-veterans-affairs/va.gov-cms#10420]
## Description

We should probably look at this at some point. 

## Acceptance Criteria
- [ ] Testable_Outcome_X
- [ ] Testable_Outcome_Y
- [ ] Testable_Outcome_Z
- [ ] Requires design review

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by EWashb** [comment]
@TheBoatyMcBoatFace this seems like a dupe of #10981

**Comment by TheBoatyMcBoatFace** [comment]
That it is @EWashb. Closing in favor of 
- #10891
