### ISSUE TITLE
Edit "Editorial Workflow" KB article

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#10430]
## Background
The [current article](https://prod.cms.va.gov/help/cms-basics/how-to-use-the-editorial-workflow) could use some updates to clarify content and add some missing content

## Suggested Updates

- "In Review" Heading
  - It should be clarified who has access to this status.  I do not believe this will show for everyone so if an editor is looking for this and does not see it, that should be explained
  - The content under this section is referring to status in the plural - "THESE aren't automated.." "THEY don't send notifications...". However, this section is only about 1 state so this seems misleading - what other state would this be referring to?
- "Archived" Heading
  - The content here discusses that there is no delete option, however the screenshot below shows a delete CTA.  This is a bit confusing.
- "Revision Log Message" Heading
  - This says the field is required, which is not the case (I save content on stage without adding a message). We should confirm with the team if this was ever the intention and should therefore be updated in the CMS or if not the article can be updated.
  - UPDATE - this will now be the case once #12449 is completed
- The article does not mention "Save Draft and Continue Editing" or "Unlock".  These options should be added 

## Acceptance Criteria

- [x] Article is updated
- [x] Article is reviewed by Helpdesk
- [x] Article ready to publish upon completion of #12449

**Comment by laflannery** [comment]
@EWashb I found [this article about archiving & deleting](https://prod.cms.va.gov/help/cms-basics/archiving-and-deleting-content) linked to the main one we are updating. I feel like I should be updating this one as well, but also do you think this is helpful? Just this giant list of content types? Or should I fold in the relevant info into the main article (which roles can do it, etc) and forgo this separate KB article?

**Comment by laflannery** [comment]
@EWashb Latest revision is here: https://prod.cms.va.gov/node/35029/latest 
If you don't mind taking a look and seeing if it makes sense

**Comment by EWashb** [comment]
This looks good to me @laflannery. Makes sense.

**Comment by EWashb** [comment]
Oh and about your question on the archiving and deleting, I don't really know who that is helpful to other than us. Editors will only see what they are allowed to see anyway.

**Comment by laflannery** [comment]
@EWashb I removed the reference to this other weird article.  I didn't archive it because maybe we will need it.  But I just don't think we need to confuse editors by linking over to it

This is ready to go and is magically linked to the code update and will be published when that goes live.
