### ISSUE TITLE
COVID Messaging: Work with Content Team to craft guidance and examples

### ISSUE THREAD

**Issue by dsinla** [department-of-veterans-affairs/va.gov-cms#10439]
## Description
As a VAMC Editor, I want standard, centralized guidance and examples how best to craft my facilities COVID policy, while having the flexibility to customize based on the operational reality of my site.  What is the visitation policy, what is the mask policy, etc?

How do we on the Facilities team best support the Content team as they develop these guidelines?

Refer to: 
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/45774

## Acceptance Criteria
- [ ] Content team provides a document/KB article that provides sufficient guidance to editors

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by jilladams** [comment]
Closing re: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13681
