### ISSUE TITLE
Edit "How to Manage Campaign Landing Pages" KB article

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#10434]
## Background
The [current article](https://prod.cms.va.gov/help/campaign-landing-pages/how-to-manage-campaign-landing-pages) could use some updates to clarify content

## Suggested Updates

- Under "What is a campaign landing page" heading, in the second paragraph the content has "Campaign Landing Page (CPL)". This correctly associates the abbreviation with the full form. This structure needs to be done the first time this is used - in the first paragraph, or even the heading, so that when just the abbreviation is used it is understood.
- Typo under "What is a campaign landing page" heading in the first bullet:  “1-page that links to deeper content which the already exists” - I think “the” shouldn’t be there
  - This also exists on the linked PDF
  ![image](https://user-images.githubusercontent.com/106678594/186683609-8377626f-de03-4711-8677-7159c25f0a1d.png)
- Typo under "What is a campaign landing page" heading in the second bullet:  “Governed and maintained by the digital communications teams at at VHA…” - remove second “at”
  - Also exists on the linked PDF
  ![image](https://user-images.githubusercontent.com/106678594/186683828-7faf63c6-a2a0-4541-aafe-e015cacf6295.png)
- "What is a campaign landing page" heading in the fourth bullet:  There is an extra space between the word navigation and the following comma
  ![image](https://user-images.githubusercontent.com/106678594/186684025-02072a5e-524b-4d81-be08-0b7536345cc6.png)
- The headings are currently broken up into Required and Optional sections. I understand this logic however it may be more logical structure this based on when the editor encounters the fields as they are editing, to be easier for an editor to use this article to follow along with.
  - The linked PDF does a good job with this, the order feels more logical
- FAQs section mentions a minimum of 3 - clarify if the content will not save if the editor only adds 2 or if this is more a suggested content guidance minimum from VA content guidelines
  - Minimum is not mentioned in the linked PDF
- Under the Editorial Workflow heading it mentions “In Review”, does every editor that has the ability to edit/create this content have this option? If this is not a universal option, this should be clarified
- Editorial Workflow also mentions “Preview”.  The “Preview” option is not here, it’s on the view screen so this is a bit confusing

## Acceptance Criteria

- [ ] Article is updated
- [ ] Article is reviewed by Sitewide CMS
- [ ] Article is reviewed by Helpdesk
- [ ] Article posted to KB

**Comment by FranECross** [comment]
@laflannery It looks like the page you audited and referenced no longer exists, and [this one](https://prod.cms.va.gov/help/campaign-landing-pages/how-to-edit-and-maintain-a-campaign-landing-page) replaced it. Do you want to audit the new one and edit this ticket, or should I just close this one? (I see an issue in the first paragraph) Thanks in advance!

**Comment by laflannery** [comment]
I did this 2 months after I started here, it was more from a CMS training standpoint than accessibility. If you see something that should be fixed, my opinion is that it should be fixed rather than a ticket be made. But as far as auditing articles I don't see a need for me to do that at this point

**Comment by FranECross** [comment]
Ticket is outdated; closing.
