### ISSUE TITLE
Edit "What is a CMS?" KB article

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#10437]
## Background
The [current article](https://prod.cms.va.gov/help/cms-basics/what-is-a-cms) could use some updates to clarify content

## Suggested Updates

- Incorrect heading structure, H2 is skipped
- In the intro headline, the more common format for abbreviations is "Content Management System (CMS)", rather than using commas
- Terms:
  - The section definition only refers to VAMCs but actually applies to everything.  Can we rewrite this to be more inclusive?
  - There are probably other terms that we could add here.  We should think about updating this with some other often used terms (i.e. node)
  - It could also be good to think about when it might be useful to link back to this section from other KB articles

## Acceptance Criteria

- [x] Article is updated
- [x] Article is reviewed by Helpdesk
- [x] Article posted to KB

**Comment by laflannery** [comment]
@stefaniefgray / @TroyA6 I updated [this ](https://prod.cms.va.gov/node/6788/revisions/689712/view) as well. Can you review, update if needed, and publish? This is the last one for spring 69, I tried not to do too many as to not overwhelm but let me know if you feel you won't be able to get it done during the sprint.  Thanks!

**Comment by TroyA6** [comment]
Hi Laura,
This looks good as well!

Thank you,
Troy

**Comment by laflannery** [comment]
@stefaniefgray Did you want to review as well or should I go ahead and publish?

**Comment by laflannery** [comment]
Confirmed with Stefanie this is good, published updated article
