### ISSUE TITLE
Edit "How to request a CMS Account" KB article

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#10443]
## Background
The [current article](https://prod.cms.va.gov/help/cms-basics/how-to-request-a-cms-account) could use some updates to clarify content

## Suggested Updates

- Incorrect heading structure, H2 is skipped
- The headings here are numbered, which is specific to this page. I understand the point because it’s a step-by-step but:
  - No other KB article has numbered headings so this is an anomaly
  - When numbers are used to indicate steps, a semantic numbered list should be used, so a screen reader user can understand the relationship between these items as well

## Acceptance Criteria

- [x] Article is updated
- [ ] Article is reviewed by Helpdesk
- [ ] Article posted to KB

**Comment by laflannery** [comment]
@stefaniefgray/ @TroyA6 I updated this [article](https://prod.cms.va.gov/node/6462/revisions/689710/view), can you review and publish if this looks good? Also, let me know if you feel you will not be able to complete this within this sprint just so I can let Dawn know.  Thanks!

**Comment by TroyA6** [comment]
That looks correct and accurate to me - Nice job!

Thank you,
Troy

**Comment by laflannery** [comment]
Confirmed with Stefanie this is good, published updated article
