### ISSUE TITLE
EPIC: VBA - Public Contact Team Research

### ISSUE THREAD

**Issue by ContentBrewmaster** [department-of-veterans-affairs/va.gov-cms#10447]
### Team
- Aslan French
- Dave Conlon

### Method
- Semi-structured interviews with VBA Public Contact staff

### Timeline / Dependencies
- 🛑 Regional Office point of contacts identifying appropriate contacts is a blocker

### Research Questions

- What are the common things Veterans ask for?
- When do Veterans ask for a benefit by phone vs. in person and typically why?
- What do Veterans typically try to accomplish during a facility visit? 
- What are the situations when Veterans don't feel successful getting a benefit at the facility?
- What do Veterans need to know or do to be adequately prepared for a visit?
- What are the unique characteristics of the benefits offered by that facility?
- How are the available services handled by the Public Contact team?
- How are Veteran Service Organizations (VSOs) located at that facility important and why?
- When should some benefits be encouraged or promoted to be done online?
- Does the Public Contact staff handle any aspect of the facility's website?

**Comment by ContentBrewmaster** [comment]
Updated epic with method, timeline and research questions.

**Comment by dsinla** [comment]
Thanks Denise!  
Some other suggestions:

- What is the top pain point/points Veterans express to you
  - Follow up: What one thing would you change on the website/want to see on the new website, to help serve Veterans better 
- How often if ever do you consult with PCO's or other staff at other ROs (goal: How isolated is current RO operation)

**Comment by ContentBrewmaster** [comment]
@dsinla Thank you for those contributions to our research questions. A couple of observations:
- I might rephrase the first suggestion so not to suggest that we will change the website based on an idea that might not be grounded in HCD principles. 
- I'm thinking your 2nd suggestion refers specifically to how, when and why service delivery might involve more than 1 RO? 
- I'm not sure for the 3rd suggestion that the Public Contact staff has a full understanding of the lift involved in delivering a service online.

**Comment by dsinla** [comment]
@ContentBrewmaster Good points, I trust you to use your best judgement, and always focus from the Veterans' PoV. 
For the 2nd bullet, I was more polling for "This is how we service loans for Veterans at my location, I do/do not know how it is done at other locations"
For the 3rd bullet I was looking for "Veterans can completely fill out their GI Bill, and register for Rehab, and qualify for their cemetery eligibility online without coming in the office."  Something like that

**Comment by ContentBrewmaster** [comment]
Thank you @dsinla will be putting the more detailed/follow-up questions in the conversation guide.

**Comment by ContentBrewmaster** [comment]
Sent to @mmiddaugh for feedback by noon Aug. 31.

**Comment by ContentBrewmaster** [comment]
Michelle's feedback received and to be incorporated before putting into GH for Dave's review.
