### ISSUE TITLE
Update the color of help text within CMS

### ISSUE THREAD

**Issue by cjterdi** [department-of-veterans-affairs/va.gov-cms#10442]
## Description

Reference design tickets [10070](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10070)

The following changes to the links are documented here: https://www.figma.com/file/ktDP1ISywa2Lc5q3GC8ezh/Changelog?node-id=27%3A2

- Help text color in MCS: Gray Cool Dark (Hex 525960)
- Change Help text in read only formats to Gray Base: (Hex 212121)
(note: We will address help text on hover states as a separate issue)

![white bg](https://user-images.githubusercontent.com/16213503/186717202-9614b784-da99-44e9-92dc-13dd91c7b67a.png)

![Read-only](https://user-images.githubusercontent.com/16213503/186717218-6d66946b-67da-4854-8b4b-0381f40ac97b.png)

## Acceptance Criteria
- [ ]  Implement the design changes listed above across CMS
- [ ] Add design and accessibility to the PR review

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [x] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by laflannery** [comment]
Reassigning to @BlakeOrgan for another review before implementation

**Comment by laflannery** [comment]
We also have an instance in a create node of a disabled field with help text: 
![image](https://user-images.githubusercontent.com/106678594/194411371-dad5dc2d-002e-4997-8639-f08aaff047b8.png)

I would like to include this as a variation to this ticket

**Comment by laflannery** [comment]
Closing this in favor of updated, more recent direction from Blake.  I will make a new implementation ticket
