### ISSUE TITLE
PM Work with Analytics for data on Contact Us anchor links 

### ISSUE THREAD

**Issue by dsinla** [department-of-veterans-affairs/va.gov-cms#10441]
## Description
Request to Analytics team to determine the previous page for people arriving on the Contact Us/Support for Law Enforcement anchor links

Refer to: https://github.com/department-of-veterans-affairs/va.gov-team/issues/45941#issuecomment-1224413256

## Acceptance Criteria
- [ ] Report is produced 

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by mmiddaugh** [comment]
The related analytics issues are closed: [Analytics Implementation or QA Support for Facilities Team - QR Code tracking #46365](https://github.com/department-of-veterans-affairs/va.gov-team/issues/46365) and [Analytics Implementation or QA Support for [Facilities - Custom report(s)] #45941](https://github.com/department-of-veterans-affairs/va.gov-team/issues/46365)
