### ISSUE TITLE
Edit "How to use the rich text editor" KB article

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#10451]
## Background
The [current article](https://prod.cms.va.gov/help/cms-basics/how-to-use-the-rich-text-editor) could use some updates to clarify content

## Suggested Updates

- "What you can do with the rich text editor" section:
  - Mentions that using the editor will add tags that meet section 508 standards - what exactly does this mean? Are these things the editor sees?
  - This section lists what is being discussed further down.  I think these should be anchor links to the content below, similar to a ToC
- The heading structure should be updated.  Bold and Italic, Link, etc. are structurally under “What we can do” so they should be h3 not h2
- Typo under "Link" heading in second bullet: “stand-along page” - should be stand-alone
![image](https://user-images.githubusercontent.com/106678594/186727321-29ae90b6-f46f-49c2-b827-5f6bfa6999a4.png)
- Under "Headings" section, the link for "Follow the VA Content Style Guide for headings" is broken.  It should to updated to [this](https://design.va.gov/foundation/typography#headings)

## Acceptance Criteria

- [x] Article is updated
- [ ] Article is reviewed by Helpdesk
- [ ] Article posted to KB

**Comment by laflannery** [comment]
@stefaniefgray and @TroyA6 Can you review this [article ](https://prod.cms.va.gov/node/34036/revisions/719254/view) and let me know if you have updates or if I can publish?

**Comment by laflannery** [comment]
Note from Stefanie: The only change I would make is asking Editors to always double-check the “Source” section when copying and pasting content into rich text fields

**Comment by TroyA6** [comment]
This looks good to me!

**Comment by laflannery** [comment]
Published!
