### ISSUE TITLE
Re-expose Q&A group fields on R&S from #9737

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#10464]
## Description
In #9737 we've added new fields that were hidden until front-end work was complete. 
As of today, 8/25, front-end PRs are merged, and the changes in https://github.com/department-of-veterans-affairs/va.gov-cms/pull/9746/commits/28320c08d9e4ab219e1a86f0fd1cde0907143c49 can be restored.

## Acceptance Criteria
- [x] Restore changes from [28320c08d](https://github.com/department-of-veterans-affairs/va.gov-cms/pull/9746/commits/28320c08d9e4ab219e1a86f0fd1cde0907143c49)
- [x] Stage in a Tugboat instance with content-build branch set to `main`, to verify that changes in Tugboat CMS appear in front-end templates correctly (I think this is valid, lemme know if not)

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [X] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by chri5tia** [comment]
Release this for Monday's deploy

**Comment by chri5tia** [comment]
PR https://github.com/department-of-veterans-affairs/va.gov-cms/pull/10483

**Comment by chri5tia** [comment]
Merged.
