### ISSUE TITLE
Broken link checking for next-build pages in content-build

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#10466]
## Description
Content-build parses all HTML it knows about, gathers any internal links and files it finds in there, and checks those URLs against what it is build, gathering those links into a broken link report and in some cases halting the build.

Next-build's content is structured different, and so the parsing to identify these links will possibly be different. We need to test this content as well and ensure we are finding broken links in it.

First thing will be to correct content-build's local broken link checking.

## Acceptance Criteria
- [ ] Broken links within content created with next-build are reported in the broken links report correctly
- [ ] content-build pages that link to next-build URLs that are missing are identified as broken

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [x] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

### Implementation tasks
- [x] Fix local broken link checking for content-build (run with --nosymlink to download assets.)
- [x] Baseline report of broken links on a local content-build
- [x] Baseline report of broken links while running next-build on a local content-build
- [ ] Point at local drupal instance, introduce a purposefully broken link and see it in the report
- [ ] Point at local drupal instance, introduce a purposefully broken link in a next-build rendered page
- [ ] Ensure the time-to-run for the next-build steps are appropriately logged and reported
- [ ] ???
- [ ] profit

**Comment by timcosgrove** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VAgov-CMS-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/10466?planning-poker) with ZenHub @tjheffner @amponce

**Comment by tjheffner** [comment]
ok - after pulling fresh drupal data i am seeing these baselines:

19 broken links with a standard content-build
33 broken links with a next-drupal enabled content-build, minus the 19 that were there, 14 new broken links. all appear to be from our demo pages.

Next I deleted the demo page and re-ran both types of builds for new baselines. 19 Broken links in the default content-build, 26 in the next-build-enabled content build.

There are 7 additional broken links in the next-build version, all stories that were published yesterday (likely not made it to the mirror yet). I checked prod.cms.va.gov and va.gov/<story url> and verified all were published and available. appears that the jsonapi endpoint picks them up but the content build doesn't, i guess?

Without including the demo pages, the message `Next build: build completed successfully. Log output is available in metalsmith.metadata().nextBuildLog.` appears about seven steps earlier in the process.

**Comment by tjheffner** [comment]
Need to add the following to any services.yml file in the va.gov-cms repo. I added it to va_gov_backend.services.yml locally.
This is hardcoded at 1000 by default, we may need to bump it higher until pagination is respected in the API calls.

```yml
parameters:
  next_jsonapi.size_max: 2000
```

Then running yarn export in next-build, or yarn build to verify that all news story nodes are picked up (without the serviecs yml update, it builds ~950 pages or so. Bumping the parameter it finds all ~1600 published nodes).

You may receive an error related to max http header size with the increased max size. To get around this, I ran the command like so:

in next-build:
`NODE_OPTIONS='--max-http-header-size=50000' yarn export`

in content-build:
`NODE_OPTIONS='--max-http-header-size=50000' yarn build --nosymlink --run-next-build`

This parameter probably needs added to the repos environment variables, or prepended to the package.json script itself. Wasn't sure the appropriate place for it, so I did it manually in my command line for now.

https://github.com/department-of-veterans-affairs/content-build/pull/1295
