### ISSUE TITLE
Discovery: VA Directive 6102 Guidelines for CMS Notifications MVP

### ISSUE THREAD

**Issue by EWashb** [department-of-veterans-affairs/va.gov-cms#10478]
## Background

Related to #10102 

In order to provide a CMS notification for editors to comply with [VA Directive 6102](https://www.va.gov/web/), we must first understand the guidelines. Along with the VHA Digital Media Team, we will explore what it means to be 6102 compliant and determine a path forward for both a CMS notification and editorial workflow. 

This ticket will only cover the discovery and editorial guideline creation that supports what is detailed in 6102. Once we have a good understanding of what the guidelines are in the directive, we will meet with VHA digital media to confirm these standards and create workflows around them

## Definition of Done
- [x]  Determination on what exactly 6102 compliance looks like for editors within an MVP iteration of CMS notifications

## Acceptance Criteria

- [x] Synthesize guidelines listed in [VA Directive 6102](https://www.va.gov/web/)
- [x] Determine what compliance would look like for an editor
- [x] Document findings/produce artifact to share with VHA Digital Media in a meeting for the week of 9/12

**Comment by EWashb** [comment]
Per PO: This is not blocking notification trigger tech solutions. They can happen concurrently.

**Comment by EWashb** [comment]
Need to follow up with Dave regarding the coordination of this. I'm having issues getting in touch with Blake Scates regarding another task, so not sure what's the best path to take to get this scheduled.

**Comment by EWashb** [comment]
@valerierunde I found [this](https://www.va.gov/web/). I'm pretty sure it's the same directive/handbook.

**Comment by EWashb** [comment]
@valerierunde after chatting with Dave, I've updated the description and ACs for this ticket. This ticket will produce a guidelines artifact that we will run by VHA digital media. We should look into the week of 9/12/22 to have that meeting.

**Comment by EWashb** [comment]
The next steps for this is to coordinate with Jenny HL and the VHA digital media team

**Comment by valerierunde** [comment]
https://app.mural.co/t/vagov6717/m/vagov6717/1662643881820/ad0f6da63dba4998516450701abca6ec1944ec74?sender=u0f6a693f731ee0b19ea13269

- Review pdfs, video, audio, images, and any other documents and ensure that they're meeting [accessibility standards](https://www.va.gov/web/standards/accessibility.cfm).
- Review content and ensure that it aligns with the [content style guide](https://design.va.gov/content-style-guide/).
- Review and test internal and external links for relevancy and accuracy and check to make sure that any necessary [link disclaimers](https://www.va.gov/web/standards/disclaimer.cfm) are present.
- Confirm that you aren't linking to the intranet or any sensitive or confidential information.
- Confirms that no personal or VA email addresses are present.
- Confirm that your content isn't intended for VA employees, unless appropriately justified.
- Confirm that you're not using any copyrighted materials without permission or payment of applicable fees.

**Comment by valerierunde** [comment]
[10478 6102 Compliance.pdf](https://github.com/department-of-veterans-affairs/va.gov-cms/files/9536574/10478.6102.Compliance.pdf)
