### ISSUE TITLE
Prep for VBA Midpoint review

### ISSUE THREAD

**Issue by davidmpickett** [department-of-veterans-affairs/va.gov-cms#10473]
## Description
- [Collaboration Cycle for Sitewide Facilities VBA Regional Offices](https://github.com/department-of-veterans-affairs/va.gov-team/issues/46029)

## Acceptance Criteria
- [ ] Main artifacts to create: **product design vision & decision overview**
  - [x] Contextualize VBA as iteration/extension of VAMC and Vet Centers
     - [x] Emphasize editor-driven content
  - [x] Clarify what we are trying to do and what & we want feedback on
     - [x] Collapsed accordions
        - [x] Top Tasks 
        - [x] Hours -> two sets of hours per day & time zone support
        - [x] Escape hatch for "can't find the service?"
     - [x] Expanded accordions
        - [x] Services -> combining Appointment info into Service Location
        - [x] Services -> improving semantic and visual separation for multiple Service Locations
        - [x] Services -> Adding modality / service delivery type (virtual/in-person/online-self service)
- [x] Artifacts for midpoint review have been agreed upon and approved by Facitilites Team / PO
   - [x] Collapsed accordion Sketch file - https://www.sketch.com/s/891d33ae-152d-471c-ab5d-9aedf89cf6ff/p/5712745E-0E95-47D2-9AAE-33F08EA3819E/canvas
   - [x] Accordion interior Sketch file
- [x] Midpoint review section of [collab cycle ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/46029) is complete
- [x] Midpoint review is requested - @jilladams to help

**Comment by davidmpickett** [comment]
The [collaboration cycle flow diagram](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/) implies that Design Intent should precede Research Reviews. But it also says that we should have a lo-fi prototype, so maybe this is more like "Research Intent" to talk about all the research we're planning to do? 

Just want to make sure we're clearing the path for #10193

**Comment by davidmpickett** [comment]
Looking back at Vet Centers as a model, it seems like they did a round of research before creating a lo-fi wireframe and scheduling Design Intent, so it doesn't seem like this is actually a blocker. Going to take this off this sprint.

**Comment by dsinla** [comment]
I think @RWEagans and I popped this back on the sprint yesterday when we reviewed all the issues, thinking it was accidentally left off.  It seems as @davidmpickett has said, this first collab cycle touchpoint will expect a lo-fi wireframe, and that will come after initial research, which is still a few sprints out.

**Comment by davidmpickett** [comment]
@kmariepat-cityfriends @mmiddaugh - flagging this for refinement tomorrow. This used to be a "prep for design intent" card, but likely to be more of a "prep for midpoint review" card now

**Comment by davidmpickett** [comment]
@kmariepat-cityfriends @mmiddaugh @jilladams 

In talking with @thejordanwood and @cindymerrill today we came up with a mini timeline for VBA Design and Usability Testing. Wanted to confirm this aligns with your expectations

- Get design close to final by end of this current sprint (Jun 6th)
- Have Midpoint Review early next sprint (Jun 8th?)
- Jordan could turn the VBA design into a clickable prototype by the end of next sprint (Jun 20th)
- As prototype is being finalized Cindy/Alexis would begin finalizing Research Plan + Conversation guide and map out timeline for recruitment and research sessions  
- Usability sessions take place in early July?

**Comment by cindymerrill** [comment]
Thanks for writing this up, @davidmpickett ! A few more updates to add:

- While I'm waiting for the design to get populated with content, I'm going to **review the new content from Dave** and start **drafting some potential user tasks** for the conversation guide. _(current sprint)_
- @thejordanwood thought it wouldn't take long to put together a prototype for this single page (much less than a sprint), and we should **talk about what screens we think we'll need** _(current sprint?)_
- I'll start thinking about a **timeline for the research**, which will only be a draft until we know the results of the Midpoint Review and what screens we need for the prototype. Hoping for June, not July, but we'll see how the design/content goes. _(current - next sprint; dependency on the completion of the design and prototype)_
- My understanding is that I'll be the one **finalizing the Research Plan and Conversation Guide**, not Alexis (who will be shadowing me). _(current - next sprint; dependency on the completion of the design and prototype)_

FYI I'm planning 1.5 weeks of PTO for late June / early July (specific dates TBD), which will affect the research timeline.
@jilladams @mmiddaugh @kmariepat-cityfriends

**Comment by thejordanwood** [comment]
@cindymerrill Correct, it won't take me long to put together a prototype for this. The prototype is very dependent on when content gets finalized and when midpoint review happens. I think June 20th is a good estimate for now, and we can possibly have it finished sooner if things go smoothly.

**Comment by cindymerrill** [comment]
@davidmpickett @thejordanwood IF the content gets finalized and the Midpoint Review happens on June 8, I would think that we wouldn't need 1.5 weeks to make changes and build the prototype? I'm trying to fit in the research sessions before I leave on vacation, which is likely during the last week of June.

**Comment by davidmpickett** [comment]
I want to note on this ticket that one of the major activities we undertook this sprint to prep for Midpoint review was to meet with the Sitewide Content team about ticket https://github.com/department-of-veterans-affairs/va.gov-team/issues/58511

**Comment by jilladams** [comment]
Lane was affected by the workflow integration with the Speedrun board. Moving back to Sprint backlog.

**Comment by kmariepat-cityfriends** [comment]
Per @davidmpickett's comment, met with the sitewide content team and are awaiting their feedback ahead of being unblocked for midpoint review

cc @jilladams

**Comment by jilladams** [comment]
- Slack thread re: changes to Service Accordion: https://dsva.slack.com/archives/C0FQSS30V/p1689623706719519
- Sketch file: [Sketch](https://sketch.com/s/891d33ae-152d-471c-ab5d-9aedf89cf6ff/p/DC11E46F-AF92-4DFD-AC0B-BEB9A9DD3C9A/canvas?annotation=627e85a4-52c9-4d0b-8172-68bd2f9d0926)
- VAMC Facility Health Service: [Pittsburgh healthcare Live example](https://www.va.gov/pittsburgh-health-care/locations/pittsburgh-va-medical-center-university-drive/#health-care-offered-here)
- VAMC Facility Non-clinical Service - [Pittsburgh register for care Live example](https://www.va.gov/pittsburgh-health-care/register-for-care/)

**Comment by davidmpickett** [comment]
Top

**Comment by davidmpickett** [comment]
Shared closed accordion artifacts with team for review: https://dsva.slack.com/archives/C0FQSS30V/p1690238772318379

**Comment by davidmpickett** [comment]
My magnum opus is complete https://www.sketch.com/s/891d33ae-152d-471c-ab5d-9aedf89cf6ff/p/578C3207-C5A3-4303-AB18-4AFC27AC54D2/canvas

**Comment by davidmpickett** [comment]
Artifacts were approved in #14087 today. Also @thejordanwood fixed my typos and reorganized the [Open service accordion page](https://www.sketch.com/s/891d33ae-152d-471c-ab5d-9aedf89cf6ff/p/DC11E46F-AF92-4DFD-AC0B-BEB9A9DD3C9A/canvas) and it's beautiful

**Comment by davidmpickett** [comment]
And I [messaged platform](https://dsva.slack.com/archives/CBU0KDSB1/p1690521410309859?thread_ts=1690233223.006099&cid=CBU0KDSB1) to let them know the artifacts are ready. DONEZO
