### ISSUE TITLE
Discovery: Current CMS Flags and Runbooks

### ISSUE THREAD

**Issue by EWashb** [department-of-veterans-affairs/va.gov-cms#10499]
## Background

As we think through the process of CMS Notifications, how to automate them, and how to surface them to editors in a way that helps them do an action, we should first determine what flags currently exist and what the runbooks are for them.

## Acceptance Criteria

- [ ] Schedule meetings with product teams to review processes for existing flags

**Comment by EWashb** [comment]
After completing this ticket the next steps are:

- Product teams have an understanding of how to make interacting with these flags better.
- Sitewide CMS determines path for flag automation.

**Comment by EWashb** [comment]
Meet with each team to determine who owns each flag. And then create runbooks for those that need them. Stef will need to be a part of this convo- what to do based upon each flag. 

Refresh what flags are there and then determine what to do about it. Be specific about the WE.

**Comment by EWashb** [comment]
@jilladams @wesrowe @dsinla @RWEagans 

We have a sprint task to go over flags that exist in the system for each of the teams. I'll be setting up a meeting with each team this sprint. Please let me know if you have questions about this. 

cc: @dawnpruitt

**Comment by ContentBrewmaster** [comment]
@EWashb I had notifications as a Q3 priority for change management. Judging from the new epic structure, it's feeling more like Q4. Would I be right?

**Comment by EWashb** [comment]
@ContentBrewmaster We will working on notifications this quarter, but it may not get completely over the finish line. Once I have more direction this sprint I'll get a meeting with you to discuss the implementation and CM aspects

**Comment by jilladams** [comment]
Some up front PW notes (cc @wesrowe ): PW references Flagged Content re: VA Forms (the other available flagged content types are all Facilities): https://prod.cms.va.gov/admin/content/flagged?type=va_form&workbench_access_section__section=All

Per prior discussion with Swirt around this, there used to be a workflow where Forms managers (I think) had some sort of rotation to monitor this list and modify content as needed. That rotation doesn't seem to be active anymore. 

We don't have a modern process for reviewing items in the list other than PW checking it when problems occur, e.g. https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10096#issuecomment-1209571645, and troubleshooting steps we perform are here: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/find-a-va-form#troubleshooting

**Comment by EWashb** [comment]
Thank you @jilladams! This is very helpful. Would you be interested in having this monitoring rotation back in the process?

**Comment by jilladams** [comment]
It's a good question. Dave's general impression is that Forms managers are overbooked / this is a small % of their jobs, so I'm doubtful they'll have bandwidth to actually engage with it, and we should probably assume no / have helpdesk or PW help own process here. We can confirm - do you know when you need to know?

**Comment by EWashb** [comment]
That makes sense! You don't have to alter the process just now for this effort. It is more about documenting the current state. If you want to explore that option you have time. I'm going to create a GitHub space that accounts for **all** flags across **all** Sitewide Crew products. We will also link to the runbooks.

**Comment by EWashb** [comment]
@dawnpruitt this is one that we won't have capacity to complete this sprint due to PTEMS transition.

**Comment by EWashb** [comment]
@dsinla I need to get some time with you to go over facilities flags. I'll look for something this week.

**Comment by dsinla** [comment]
@EWashb Got it. I have the highest-level understanding, but I haven't really seen the end to end flow. Would be great to see that in more detail.

**Comment by EWashb** [comment]
Meeting with facilities set for 9/19/22 at 11 am CST.

**Comment by dsinla** [comment]
FYI Meeting notes;
https://docs.google.com/document/d/1pQkkaTKp6Uif0xZMuiqqivKtn-N1qhQWoy6bz13Q6TI/edit#

**Comment by EWashb** [comment]
@jilladams @wesrowe I would love to set some time up to go over these forms flags if you have any time. Dave will attend these meetings so that we are all on the same page. If it is ok with you, I can look into the next sprint

**Comment by wesrowe** [comment]
@EWashb please do, and thanks!

**Comment by EWashb** [comment]
Public Websites meeting scheduled for 9/28
