### ISSUE TITLE
Edit "How to edit a VAMC Facility" KB article

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#10497]
## Background
The [current article](https://prod.cms.va.gov/help/va-medical-centers-vamcs/about-locations-content-for-vamcs/how-to-edit-a-vamc-facility) could use some updates to clarify content

## Suggested Updates

- Basic location data (mentioned throughout this article and others): It is confusing to me that while many things say I cannot edit this data, I can still actually type into many of these fields in the CMS.  Can we confirm what can and cannot be changed? And what would happen if I type in these fields and save my content?
   - And possibly explain why some fields are gray and some are white if it is true that editors cannot edit all these fields?
- Related content heading: Adding links to other KB articles for how to edit these related content types could be beneficial
- There is a typo under the "Veteran Satisfaction and wait time data" heading: “This data comes from a centralized database at VA and automatically added to this page” - is should say “and IS automatically added”
  - Also, why is this content not displayed in the CMS within the node in a read-only format, like other non-editable content is?

### Related Issue
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10226

## Acceptance Criteria

- [ ] Article is updated
- [ ] Article is reviewed by Sitewide CMS
- [ ] Article is reviewed by Helpdesk
- [ ] Article posted to KB

**Comment by xiongjaneg** [comment]
made edits, closing
