### ISSUE TITLE
Edit "How to create a situation update" KB article

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#10496]
## Background
The [current article](https://prod.cms.va.gov/help/vamc/how-to-create-a-situation-update) could use some updates to clarify content

## Suggested Updates

- Content Intent section:
  - In the second paragraph it says “You can have more than one situation update that display news-to-oldest…”  This should say displays, with an S.
- How we do it:
  - It seems as though very little of the CMS form/fields is mentioned here.  Shouldn't all fields be discussed and explained?

## Acceptance Criteria

- [x] Fixed typo
- [x] Linked to related prerequisite banner alerts article

**Comment by xiongjaneg** [comment]
made updates and closing
