### ISSUE TITLE
Edit "How to add other VA locations" KB article

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#10494]
## Background
The [current article](https://prod.cms.va.gov/help/vamc/about-locations-content-for-vamcs/how-to-add-other-va-locations) could use some updates to clarify content

## Suggested Updates

- Under Step 5 in the "Before you start" heading it mentions a way to find the facility ID. However,  I do not believe this method of finding the facility ID works with Vet Centers anymore, the ID is no longer in the URL.
- This page is a duplicate (but more detailed) of step 10 on the “How to edit a VAMC System Homepage” article.  Would it be at all beneficial to combine these? Or link to this page from step 10 in order to provide more detail?

## Acceptance Criteria
- [x] Replaced instructions for getting the ID with recommendation to contact their VAST coordinator as how to get IDs vary by facility type.
- [x] Linked to homepage article

**Comment by xiongjaneg** [comment]
updated and closing
