### ISSUE TITLE
Edit "About locations content - for VAMCs" KB article

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#10498]
## Background
The [current article](https://prod.cms.va.gov/help/vamc/about-locations-content-for-vamcs) could use some updates to clarify content

## Suggested Updates

- There are blank H2s above the existing h2s
- In discussing the Facility API, it is only called the “Facility API” vs. the “Lighthouse Facility API” (which is how it’s referred to in other places).  I think this should probably be referenced using the same terminology
- “Follow the process on this page” is a broken link. I’m not positive where this should go

## Acceptance Criteria
- [x] Removed blank H2s
- [x] ~~Updated Facility API~~ no longer applies
- [x] Fixed link to basic facility data article

**Comment by xiongjaneg** [comment]
made updates, closed
