### ISSUE TITLE
[cms-ci] ERROR: Failed to download Chromium r594312!

### ISSUE THREAD

**Issue by ElijahLynn** [department-of-veterans-affairs/va.gov-cms#1049]
I've seen this flicker a few times recently. Don't really want to add the `PUPPETEER_SKIP_CHROMIUM_DOWNLOAD` env var but we may have to. 

![image](https://user-images.githubusercontent.com/1504756/75196666-50360700-5711-11ea-8640-e2b3b9c36b02.png)

> ERROR: Failed to download Chromium r594312! Set "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD" env variable to skip download.
> { Error: self signed certificate in certificate chain
>     at TLSSocket.onConnectSecure (_tls_wrap.js:1051:34)
>     at TLSSocket.emit (events.js:189:13)
>     at TLSSocket._finishInit (_tls_wrap.js:633:8) code: 'SELF_SIGNED_CERT_IN_CHAIN' }
> Script cd web && yarn install handling the va:web:install event returned with error code 1
> Script @va:web:install was called via post-install-cmd

I think this is related to #1044.

**Comment by ElijahLynn** [comment]
Just got a new one 14 minutes ago:

> Error validating GitHub token: cURL error 7: Failed to connect to api.github.com port 443: Connection timed out 

![image](https://user-images.githubusercontent.com/1504756/75199183-3c8d9f00-5717-11ea-8cdb-def759e6ab4f.png)

**Comment by jonpugh** [comment]
See https://github.com/department-of-veterans-affairs/va.gov-cms/issues/1016

**Comment by ElijahLynn** [comment]
This happens intermittently and I think this error is not actually what is happening and instead it is a network issue with the firewall inspecting packets. 

> Error: self signed certificate in certificate chain

Related issue here suggests whitelisting a domain, but this isn't consistent. https://github.com/puppeteer/puppeteer/issues/2173
