### ISSUE TITLE
Discovery: Validate click events / pathway from Form Search

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#10509]
## Description

Add Form search page experience to Forms Mural :
https://app.mural.co/t/vagov6717/m/vagov6717/1660150431569/27c80eaeeaedfd88c80322ae177b68c503345ba9?sender=u252e7152800e3981889d1910

## Acceptance Criteria
- [x] Mural is updated to document the user flows & click events from the Forms Search page - https://www.va.gov/find-forms/

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by dsasser** [comment]
The mural has been updated. Some interesting findings related to the forms detail workflow:

No Forms API call on click
No HEAD fetch of file
No sentry logging
Little to no code sharing between search and detail page

There is definitely room to improve parity between the search and detail page workflows.

Attaching relevant mural for posterity:
![Form Search Page Download Technical FE Workflow - VACMS-10509](https://user-images.githubusercontent.com/221539/187528001-318d0911-f482-4dab-a6ad-0ce7ae2781de.png)

**Comment by jilladams** [comment]
Looks like #10562 captures follow up and this ticket can close at your leisure @dsasser
