### ISSUE TITLE
DSN: Submit Public Contact Research Plan draft for review and receive feedback

### ISSUE THREAD

**Issue by dsinla** [department-of-veterans-affairs/va.gov-cms#10506]
### Acceptance criteria

- [x] Feedback from Michelle Middaugh received and incorporated
- [x] Research plan in GH 
- [x] Internal review of research plan completed
- [x] Research plan shared with PO for review

[Research Plan for VBA MVP Public Contact Staff Discovery](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/facilities/regional-offices/research/2022-9-public-contact)

**Comment by ContentBrewmaster** [comment]
Reviewed research plan with Facilities team Sept. 22.

**Comment by davidmpickett** [comment]
The additional action item here is getting this in front of Dave Conlon in a working meeting.

**Comment by dsinla** [comment]
This is tracked in the wrong github folder - needs to move to correct folder.

**Comment by jcklpe** [comment]
Moved to the correct folder here: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/facilities/regional-offices/research/2022-9-public-contact

**Comment by jcklpe** [comment]
I've looked over the plan and I think it's worth taking to Conlon. I will schedule a meeting with him for next week.

**Comment by davidmpickett** [comment]
This seems complete. The draft was submitted and feedback was received.

**Comment by dsinla** [comment]
@dawnpruitt @dsinla  Verify with Dave C in sync

**Comment by dsinla** [comment]
@davidconlon sent feedback today
Closing
