### ISSUE TITLE
Discovery: [CMS Notification Trigger] Outdated content more than 1 year old

### ISSUE THREAD

**Issue by EWashb** [department-of-veterans-affairs/va.gov-cms#10500]
## Trigger Definition
A trigger is a flag in the CMS that indicates there is an action for a user to complete. For example, a user can be an editor or someone on the helpdesk team. 

**1. Is this an existing or proposed trigger?**
[ ] existing
[x] proposed

> This could be a new or existing product.

**2. When does this trigger occur in the CMS?** 
This would trigger after 365 days

**3. What is the technical solution/process for this trigger?** 
A flag once content has not been viewed in 365 days
  
**4. What is the editor solution for this trigger?** 
The editor must go in and review their content 

**5. How would a user clear this trigger or complete the action?**
Update content and publish. This should reset the clock on the year

**6. Are there any change management implications for this trigger?**
Yes. This would introduce a new workflow for editors

> All requests should be submitted to the Sitewide CMS team for prioritization. Please make sure to notify the Sitewide CMS team after you submit this issue on the #sitewide-cms team slack channel.

## Acceptance Criteria

- [ ] Tech options are determined

**Comment by EWashb** [comment]
We need to have a tech meeting for this with @edmund-dunn @ndouglas and/or @swirtSJW

**Comment by edmund-dunn** [comment]
https://www.drupal.org/project/outdated_content

older than 365 and not flagged outdated. Remove flag after n days? 
queue so no more than one email. 

view in dashboard of outdated content

email notification based on view containing outdated content
