### ISSUE TITLE
Income limits: User research

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#10505]
## Description

Following 8/29 stakeholder sync, we are cleared to start user research.

## Acceptance Criteria
- [ ] Initiate Perigean recruitment of research participants per the [research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/income-limits-app/research/research-plan.md)
- [ ] Conduct research interviews

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [X] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by wesrowe** [comment]
@jilladams, FYSA this ticket may be blocked in the current sprint. The stakeholder meeting on 8/29 left us clear to begin the research process as a next step, and I updated this ticket to reflect that. However, recruiting research participants is blocked until Florence's status is resolved (ptems).

**Comment by wesrowe** [comment]
Since we are losing design team members, this user research is blocked until design capacity is figured out.

**Comment by davidmpickett** [comment]
Duplicate with https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11167
