### ISSUE TITLE
Synthesize existing VBA "database" (spreadsheet) into improved content models

### ISSUE THREAD

**Issue by JayDarnell** [department-of-veterans-affairs/va.gov-cms#10504]
## Description

Digest the contents of email sent from David Conlon on August 25th, 2022 and the current VBA spreadsheet (which Lighthouse pulls from) to determine a more accurate data model. What content types? Do we need a hierarchy? Etc.

## Acceptance Criteria

1 or more content model suggestions

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by davidmpickett** [comment]
Commenting to tag myself for possible including in a working brainstorm

**Comment by davidmpickett** [comment]
Airtable where I started playing around with this: https://airtable.com/appftQ67nT0eopl4i/tblZgHTmtzAO3OXho/viwniC9GzrdylJPa0?blocks=hide

**Comment by JayDarnell** [comment]
Spreadsheet link from July 2022: https://docs.google.com/spreadsheets/d/1OOAPb2_HXuJD1bgedmK0FhuxehB5R-yj/edit?usp=sharing&ouid=110266615980766295586&rtpof=true&sd=true

**Comment by JayDarnell** [comment]
The following diagram suggests additional fields, content types and taxonomies based on a review of the VBA Facility source data and a comparison to existing Vet Center fields. This is a first draft for discussion and revisioning. 

![VBA Facilities](https://user-images.githubusercontent.com/21045418/189997007-bd96d991-a719-4814-b7f5-0b7f9fa6e6c7.png)

**Comment by davidmpickett** [comment]
@JayDarnell Re the Services Taxonomy question, when I discussed with Dave C a few sprints ago the working hypothesis is that it will be an expansion of the Service Taxonomy. Each Taxonomy term currently has separate fields for VAMC and for Vet Centers, the thought was that they might be a net set of fields for VBA

**Comment by JayDarnell** [comment]
Thank you for that @davidmpickett - we arrived at a similar conclusion during the mid/week check-in earlier today. 

Diagram: https://drive.google.com/file/d/1RP3Xiil6N1SrYVt5XqeImkSzm6cNqt5m/view?usp=sharing
VBA DB Spreadsheet (July 2022) https://docs.google.com/spreadsheets/d/1rqP4d163TtYULKL3H-CcNJinaDmHg22T/edit?usp=sharing&ouid=104875382415475763592&rtpof=true&sd=true

**Comment by dsinla** [comment]
Issue for next Sprint - Cross-walk wireframes with content model in a working session. Acknowledging high/low confidence items.
From the strictly data-focused view:  What can we leverage out of this database for formation of services?  Here's what we recommend bringing 

1. Do we intend to merge VBA services into the existing taxonomy model?
2. Are there any entries in these identified fields that are not valid data? Out of sync?

**Comment by dsinla** [comment]
@swirtSJW and Dave C to walk thru.

**Comment by swirtSJW** [comment]
I met with Dave C to go over the data mapping in Jay's diagram.  A couple notes came out of the meeting.

1) Not included in the diagram is the URL to external location   We would want to include that in the facility as well.
2) All connections to other facilities should be via entity reference, not just storing the facility id string.
3) The accuracy of service data may be questionable, so we may not want to migrate them in directly from the db, but maybe send out a form to gather the data and migrate that... or make it easy to add in the CMS and that becomes our connection.  This will need some more pondering.
