### ISSUE TITLE
DSN: Incorporate feedback and finalize VBA Public Contact Staff Research Plan

### ISSUE THREAD

**Issue by dsinla** [department-of-veterans-affairs/va.gov-cms#10507]
### Background
We are preparing for interviews with Public Contact staff identified as part of the VBA MVP in September/October 2022.

### Acceptance criteria
 - [x] Feedback received from PO
 - [x] Research plan updated to reflect feedback

[Research folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/facilities/regional-offices/research/2022-9-public-contact)

**Comment by dsinla** [comment]
Per discussions today 10/11 taking out of Sprint 69 and targeting sprint 70

**Comment by jcklpe** [comment]
Meeting to review has been scheduled with Conlon. Awaiting the closure of this ticket to proceed: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10506

**Comment by dawnpruitt** [comment]
From my 11/2 sync with Dave - notes on potential PCT questions:
Public Contact Center Team Research 
Dawn/Dave Sync 11-2, Dave’s thoughts
•	PCT Staff: another lens of the Veteran experience at the Regional office
•	Understand the services offered
•	Is there nuance (someone drives to the office to meet with a person but is then handed a phone)?
•	Services they see people using
•	Frequent problems they see
•	Veteran experience at regional office through the lens of the RO
•	Typical complains seen 
•	What do you wish they knew before coming in?
•	Common tasks performed
•	What do you see as a veterans experience coming in? (Less concerned about phone)
•	Busiest times are between ___ and ___?
•	Typical complaints about website from Veterans
•	What have you seen as wait times (emphasize no judgement on wait times, just want the observation)
•	What about the experience is frustrating?
•	How often are they walk-in vs appointments?
•	How often do you see people waiting?
•	   How long is wait?
•	   Do people get frustrated?
•	If this website could do one thing to make your life easier, what would it be?
•	What are the services around the benefits?
Wade through the reasonable questions that can be answered/discussed in about 45 minutes.

**Comment by EWashb** [comment]
document with feedback shared with @dsinla and @dawnpruitt. Will add final doc once we agree on direction

**Comment by davidmpickett** [comment]
Noting that I sent an updated version of the plan to Dave C for review last night
[Research Plan for VBA MVP Public Contact Staff Interviews.docx](https://github.com/department-of-veterans-affairs/va.gov-cms/files/10015088/Research.Plan.for.VBA.MVP.Public.Contact.Staff.Interviews.docx)

**Comment by davidmpickett** [comment]
Updated Research Plan is on GitHub: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/regional-offices/research/2022-9-public-contact/research-plan.md

**Comment by davidmpickett** [comment]
@dawnpruitt @dsinla This should be good to close

**Comment by dsinla** [comment]
Thanks @davidmpickett!
Closing with all AC's completed.
