### ISSUE TITLE
Type-ahead on the Find-a-form search page is not working

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#10518]
## Describe the defect
Type-ahead on the Find-a-form search page is not working.
This is a regression. Typeahead was known to be working in August 2022 when #10096 was reported.

## To Reproduce
1. Go to 'https://www.va.gov/find-forms/'
2. Start typing "disability"
3. Notice that no type-ahead options appear
4. See no network traffic associated with your typing

## AC / Expected behavior
I expect to see type-ahead behavior and associated network traffic.

## Related observations

I just noticed this using a GA debugging extension called AdSwerve. Suggests that typeahead may have been disabled programmatically – for me or for all users?
<img width="303" alt="image" src="https://user-images.githubusercontent.com/4054752/187745061-9df7d715-ee5f-4098-a672-92b371d24c00.png">

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by wesrowe** [comment]
Type-ahead comes with the [design system Search Input component](https://design.va.gov/components/search-input). As far as I can tell from the storybook page, adding typeahead would not be visible in the codebase unless you know exactly what you're looking for:

>     suggestions={[]}

It appears that TA was never implemented in FaF. The [epic](https://github.com/department-of-veterans-affairs/va.gov-team/issues/20255) is in New/Unrefined. And documentation that initially appeared to be about an existing feature turns out to be notes about a future implementation.

**Comment by jtmst** [comment]
Currently only the homepage search component uses the design system search input.  Investigation on gitLens file history in FaF doesn't indicate any previous implementation of type-ahead

**Comment by jilladams** [comment]
So sounds like this is not a defect, and instead we need to define / prioritize as future work. Any reason not to close?

**Comment by jilladams** [comment]
(Also sorry for stating it as fact that this was a regression. I would truly swear it was working, but it seems like it was just the "previous search" suggestions thing you get natively in browser, e.g. below)
![Screen Shot 2022-09-19 at 3 35 21 PM](https://user-images.githubusercontent.com/85581471/191131399-3266aad4-df40-4cf9-91ff-58fa95bcd997.png)

**Comment by jilladams** [comment]
To implement would mean:
* Refine the old wishlist tickets for Forms typeahead
* Would need to research available endpoints in search.gov to see if one exists we could use
* Fairly custom solution as this isn't a reusable component as far as we know
* Estimate: 8ish
