### ISSUE TITLE
EPIC: VBA Pilot MVP - Updates to VA Services Taxonomy

### ISSUE THREAD

**Issue by davidmpickett** [department-of-veterans-affairs/va.gov-cms#10517]
### User Story or Problem Statement

As a the Facilities Team, we need to make updates to the [VA Services Taxonomy](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/va-service-taxonomy/README.md) so we can build the VBA Regional Office MVP (#10514).

### Affected users and stakeholders

* Taxonomy Council
* Facilities Team
* VBA Stakeholders?

### Hypothesis

We believe that the VBA Regional Office MVP will have similar needs to the VAMC and Vet Center products from a service taxonomy perspective. 

We'll know that to be true when we have fully specified the [VBA RO MVP Definition](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/regional-offices/design/README.md)

### Reference
- [VA service taxonomy content model](https://app.mural.co/t/departmentofveteransaffairs9999/m/vagov6717/1658937741729/88cc653ce1bed251e60940c147867eb061496070?wid=0-1677268614480)

### Working document

- [VBA Services](https://dvagov.sharepoint.com/:x:/s/VBAVA.govmodernization/ET964xEqUFREirhtu34HQVIBbsNOu12QIUc-EVNF_aW98g) (requires VA network)

**Comment by xiongjaneg** [comment]
moving remaining tickets to Pilot MVP initiative for better tracking
