### ISSUE TITLE
Text validator to prevent fake absolute URLs without a scheme.

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-cms#10513]
## Description
Followup to address a nice-to-have from #7240.

Some broken links have the form `<a href="www.example.org/puppies.html">puppies</a>`.  This gets translated to `https://www.va.gov/www.example.org/puppies.html`, then trips the broken link detector.

With a recent explosion in TLDs, it's increasingly difficult to reliably detect hostnames, but I think we should be able to say that anything with a `.com`, `.net`, `.org`, `.gov`, `.us`, etc suffix is dramatically more likely to be a domain name than a proper top-level subdirectory on the website, and should block the edit.

## Acceptance Criteria
- [x] `string_long` and `text_long` plain and rich text should not accept URLs that don't have a scheme portion.

**Comment by ndouglas** [comment]
Similarly, `/www.va.gov/PACT` is not currently caught.

**Comment by swirtSJW** [comment]
Similar overlap with https://github.com/department-of-veterans-affairs/va.gov-cms/issues/8032
amd https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10579

**Comment by swirtSJW** [comment]
Though I also wonder if the specific cases of
//www.va.gov/foo
/www.va.gov/foo
/https://www.va.gov/foo
//https://www.va.gov/foo

all just should get replaced with /foo before validation.  ??

**Comment by ndouglas** [comment]
Oops, I just duped this and didn't see it.  This is a dupe of #12394.  Since I already opened a PR referencing the latter, I'll close this ticket.
