### ISSUE TITLE
Look into why `datadog/dd-trace` Dependabot PRs don't trigger deploys to Tugboat.

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-cms#10523]
## Description
See #10425.

`datadog/dd-trace` Dependabot PRs frequently (perhaps always) fail to trigger deploys to Tugboat.  We should determine whether this is a bug with Tugboat or an issue with our configuration.

## Acceptance Criteria
- [ ] Tugboat's relationship with deploying `datadog/dd-trace` PRs has been investigated.
- [ ] Followup issue(s) opened to remediate.

**Comment by TheBoatyMcBoatFace** [comment]
@ndouglas is this still happening or can we close it?

**Comment by ndouglas** [comment]
It's not specific to `datadog/dd-trace`.  It's happened on a few other PRs.  I'm not sure how frequent it is.  I think it just happened on this package a few times by chance, enough that I noticed it.

It's not common and it's not a massive issue, since we can just go to Tugboat and manually build the PR, but it's obv not great.  I can pinging this issue when I see it happen (latest was [this PR](https://github.com/department-of-veterans-affairs/va.gov-cms/pull/12131)), or perhaps we can rap with Tugboat and figure out how we can capture better troubleshooting data.

**Comment by ElijahLynn** [comment]
> perhaps we can rap with Tugboat and figure out how we can capture better troubleshooting data.

This is good, yes, when we see it happen next, let's ping #tugboat-support in Slack.

**Comment by ndouglas** [comment]
I figured this out at some point -- it's because the PR body would contain some snippet as code, which would be interpreted as an attempt to _inject_ code via an API call, and consequently the TIC or whatever would drop the request and respond with... an HTTP 200.
