### ISSUE TITLE
CMS:Adding a service location to a facility service  shows custom hours, even though use facility is the default

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#10537]
## Describe the defect

Verify this was fixed with Christian's recent updates

When you add a 2nd or 3rd facility service location, the hours come in with a default setting of "Use facility's hours" but the hours widget shows as though "custom hours" was chosen.
![image](https://user-images.githubusercontent.com/5752113/187551434-e6343bc2-98b0-4e6c-bdb1-aef1e5549812.png)

content types affected
* facility health service https://staging.cms.va.gov/node/11981/edit
* non-clinical service like this https://staging.cms.va.gov/node/44739/edit

It seems to work fine for the first entry.

## To Reproduce
1. Go to https://staging.cms.va.gov/node/11981/edit
2. Expand on Hours.   
3. See how the hours field shows up even though use facility's hours is selected.

## AC / Expected behavior
On both facility service nodes and non-clinical service nodes:
- [x] Should defualt to "Use facility's hours"
- [x] should not show hours widget initially.

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Defect")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS workstream (orange) (not needed for bug tickets)
- [ ] CMS-supported product (black)

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by omahane** [comment]
<img width="1840" alt="Screen Shot 2022-09-23 at 2 57 31 PM" src="https://user-images.githubusercontent.com/766573/192048111-700cdf48-a070-4cdd-b026-f3d7a6596577.png">
<img width="1840" alt="Screen Shot 2022-09-23 at 3 00 23 PM" src="https://user-images.githubusercontent.com/766573/192048119-ec9d6f05-90d6-4193-902d-e6aa98666b4a.png">
Both 2nd and 3rd for both types of content are working as expected.
