### ISSUE TITLE
Remove italics from KB articles

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#10544]
## Background
Using italics in texts breaks the VA content style guidelines. There are some KB articles using italics that should be updated.

## List of articles

- [How do I change the name of a health service?](https://prod.cms.va.gov/help/vamc/how-do-i-change-the-name-of-a-health-service)
- [How to add a VAMC facility health service](https://prod.cms.va.gov/help/vamc/how-to-add-a-vamc-facility-health-service)
- [How to edit an existing VAMC facility health service](https://prod.cms.va.gov/help/vamc/about-health-services/how-to-edit-an-existing-vamc-facility-health-service)

## Acceptance Criteria

- [x] Articles are updated
- [x] Articles posted to KB

**Comment by EWashb** [comment]
@stefaniefgray @TroyA6 the italics were removed and typos fixed in each article. Saved as draft for your review before publishing

**Comment by laflannery** [comment]
- How to change the name of a health service:
   - I think we should get rid of this entirely and fold this content into into these articles: [How to edit a health service](https://prod.cms.va.gov/help/va-medical-centers-vamcs/about-health-services/how-to-edit-a-vamc-system-health-service) and [How to add a health service]( https://prod.cms.va.gov/help/vamc/how-to-add-a-vamc-system-health-service) (which also should be combined into 1) 
- These other 2 articles should also be combined into 1, there is no reason edit and add, for the same content type, should be separated out in this way

**Comment by laflannery** [comment]
- Combined VAMC system health service articles: https://prod.cms.va.gov/help/vamc/how-to-add-or-edit-a-vamc-system-health-service
- Combined VAMC Facility health service articles: 

New ticket to redirect duplicate articles
https://prod.cms.va.gov/help/va-medical-centers-vamcs/about-health-services/how-to-edit-a-vamc-system-health-service
