### ISSUE TITLE
Edit "How do I add a facility to my health care system" KB article

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#10545]
## Background
The [current article](https://prod.cms.va.gov/help/vamc/about-locations-content-for-vamcs/how-do-i-add-a-facility-to-my-health-care-system) could use some updates to clarify content

## Suggested Updates

- Veteran-centered purpose content is italicized which breaks content style guidelines
- Under the “Instructions” Heading on step 3, there is a warning that says “do not save this content yet”.  It should perhaps be more specific as to what “this” is

## Acceptance Criteria

- [ ] Article is updated
- [ ] Article is reviewed by Sitewide CMS
- [ ] Article is reviewed by Helpdesk
- [ ] Article posted to KB

**Comment by stefaniefgray** [comment]
Created similar ticket without realizing: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11243

**Comment by laflannery** [comment]
Closed in favor of #11243 11243
