### ISSUE TITLE
Edit "How to edit local information on a billing and insurance VAMC page" KB article

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#10547]
## Background
The [current article](https://prod.cms.va.gov/help/vamc/how-to-edit-local-information-on-a-billing-and-insurance-vamc-page) could use some updates to clarify content

## Suggested Updates

- There is a typo on heading: “What is a the “Billing and insurance” top task page?” - choose either A or The
  - There is also a typo within this section: "...our research with Veterans and and continuous feedback..." - Remove duplicate and
- On the second heading - change the single quotes to double quotes for consistency 

## Acceptance Criteria

- [ ] Article is updated
- [ ] Article is reviewed by Helpdesk
- [ ] Article posted to KB

**Comment by laflannery** [comment]
[Draft ready for review](https://prod.cms.va.gov/node/44536/latest)

**Comment by TroyA6** [comment]
This KBA revision looks good to me. Thank you!

**Comment by laflannery** [comment]
Published
