### ISSUE TITLE
Edit "How to edit a VAMC System Policies page" KB article

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#10546]
## Background
The [current article](https://prod.cms.va.gov/help/vamc/how-to-edit-a-vamc-system-policies-page) could use some updates to clarify content

## Suggested Updates

- There is a typo under “About VAMC System Policies Page” Heading: …"under Visitation Policy, as well asl add other system-specific…”. - asl should just be as

## Acceptance Criteria

- [x] Article is updated
- [x] Article is reviewed by Helpdesk
- [ ] Article posted to KB

**Comment by EWashb** [comment]
@stefaniefgray @TroyA6 typos fixed and ready for your review before publishing

**Comment by TroyA6** [comment]
@laflannery This KBA is good to go! Thank you!!

**Comment by laflannery** [comment]
Published!
