### ISSUE TITLE
Links to frontend on rebuild request are wrong

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#1055]
**Describe the defect**
When you trigger a FE rebuild, the link provided to the front end site is malformed does not take you to the site when clicked.
![image](https://user-images.githubusercontent.com/5752113/75278721-61961680-57d8-11ea-91df-a69add5648a1.png)

**To Reproduce**
1. Go to '/admin/content/deploy'
2. The link to the environment target has a http://  followed by an https.

**Expected behavior**
The link should be properly formed and take you to the frontend.

**Additional context**

## Labels
- [/] Issue type (red) (defaults to "Defect")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [/] CMS objective (orange) (not needed for bug tickets)
- [ ] CMS-supported product (black)

**Comment by jonpugh** [comment]
FYI All CI and DEMO sites follow the pattern:

- pr123.ci.cms.va.gov => pr123.web.ci.cms.va.gov
- DEMOSITE.ci.cms.va.gov => DEMOSITE.web.ci.cms.va.gov

**Comment by oksana-c** [comment]
fixed
