### ISSUE TITLE
Edit "How to edit a leadership list" KB article

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#10550]
## Background
The [current article](https://prod.cms.va.gov/help/vamc/how-to-edit-a-leadership-list) could use some updates to clarify content

## Suggested Updates

- On Step 8 there is an additional 4
- The Leadership List Heading just has screenshots under it, this information should be described in plain text

## Acceptance Criteria

- [x] Fixed type
- [x] Added plain text

**Comment by xiongjaneg** [comment]
made updates and closing
