### ISSUE TITLE
Edit "How to edit or add a VAMC detail page" KB article

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#10551]
## Background
The [current article](https://prod.cms.va.gov/help/vamc/how-to-edit-or-add-a-vamc-detail-page) could use some updates to clarify content

## Suggested Updates

- Policies is listed as a page using the detail page, is this still accurate? I thought it was using a hardened content type?
- Screenshot for In-page alerts is not loading
- Under the "How to edit an existing content block" heading, there are both bullets and numbers, only one should be used - for consistency probably numbers.

## Acceptance Criteria

- [x] Removed reference to Policies
- [x] Removed screenshot for in page alerts
- [x] Changed bullets to numbers only

**Comment by xiongjaneg** [comment]
made updates, closing
