### ISSUE TITLE
Edit "About stories content  for VAMCs" KB article

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#10552]
## Background
The [current article](https://prod.cms.va.gov/help/vamc/about-stories-content-for-vamcs) could use some updates to clarify content

## Suggested Updates

- I believe there is a typo under the "Stories page on your VAMC site" heading: "There are two content types in the CMS that contribute to the events page on your VAMC site” - I think this should say “stories page”

## Acceptance Criteria

- [ ] Article is updated
- [ ] Article is reviewed by Sitewide CMS
- [ ] Article is reviewed by Helpdesk
- [ ] Article posted to KB

**Comment by laflannery** [comment]
@EWashb I do not see a point to this article and am leaning towards archiving it. We have a more detailed article for [stories ](https://prod.cms.va.gov/help/va-medical-centers-vamcs/about-stories-content-for-vamcs/how-to-add-a-story) as well as the [stories list](https://prod.cms.va.gov/node/6784/latest) (currently waiting for review) and I just don't see what additional info this is offering.  Thoughts?

**Comment by EWashb** [comment]
Yea, let's archive it @laflannery

**Comment by laflannery** [comment]
Excellent, I just removed every link I could find pointing to this, except for the Stories list article since it's already in draft (#10557). When that latest revision gets published, I will archive this article

**Comment by laflannery** [comment]
Archived
