### ISSUE TITLE
Add content for "How do I enable my VAMC Program landing page and section?" KB artice

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#10563]
## Background
The [current article](https://prod.cms.va.gov/help/vamc/how-do-i-enable-my-vamc-program-landing-page-and-section) does not have any content

## Suggested Updates

- Content should be added to the current article or if this is not ready for editors yet the link should be removed from the main VAMC page

## Acceptance Criteria

- [ ] Article is updated or archived and link is removed from main VAMC page if this should not be accessible
- [ ] Article is reviewed by Sitewide CMS
- [ ] Article is reviewed by Helpdesk
- [ ] Article posted to KB

**Comment by mmiddaugh** [comment]
This KB article is now available and this issue can be closed
