### ISSUE TITLE
St. Thomas Outstation is missing latitude and longitude

### ISSUE THREAD

**Issue by omahane** [department-of-veterans-affairs/va.gov-cms#10573]
## Describe the defect
St. Thomas Vet Center Outstation does not have geocode data.

## To Reproduce
1. Go to [Edit Vet Center - Outstation St. Thomas Outstation](https://prod.cms.va.gov/node/17526/edit)
2. Scroll down to 'Geolocation'
3. Validate that the "Latitude" and "Longitude" fields are empty

## AC / Expected behavior
The "Latitude" and "Longitude" fields should have geocoded data consistent with the address.

### Latitude and Longitude fields are empty
![Screen Shot 2022-08-31 at 3 17 43 PM](https://user-images.githubusercontent.com/766573/187774129-e6c1eb54-4de1-45e3-aebe-50d4914eaac9.png)

### It appears to have been removed from Lighthouse
![Screen Shot 2022-08-31 at 4 10 54 PM](https://user-images.githubusercontent.com/766573/187773602-2ec7d8b4-fe7b-428b-8736-52e1df5ee939.png)

 ## Additional context
Dave Conlon heard fom the director of the St. Thomas Vet Center about confusion around the location.

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Defect")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS workstream (orange) (not needed for bug tickets)
- [ ] CMS-supported product (black)

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by swirtSJW** [comment]
This was the result of one facility being removed from the Facility API and then a new one getting spun up and no-one noticed that the new one was not acted upon.  This has been resolved in the content.
