### ISSUE TITLE
Content block categories have started showing up in the paragraphs interface

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#1057]
**Describe the defect**
The paragraph group label provided by Paragraphs browser now appears, where it didn't before, and it's confusing for editors.  

**To Reproduce**
1. Go to /node/901/edit
2. Scroll to Main content.

**Expected behavior**
Here's what it _used_ to look like. (v0.0.56, before drupal 8.8 update?)

![Edit_Benefits_detail_page_File_a_VA_disability_appeal___VA_gov_CMS.jpg](https://images.zenhubusercontent.com/5d6e57ad330f64311395f08b/04e420f7-b478-43ca-904a-20dabf20f1f1)

**Screenshots**
Here's how it looks now.

![Edit_Benefits_detail_page_Manage_a_legacy_VA_appeal___VA_gov_CMS.jpg](https://images.zenhubusercontent.com/5d6e57ad330f64311395f08b/681bc777-0f67-447e-a4e3-e8110a1c2998)

## To do

1. [Apply this patch](https://www.drupal.org/project/paragraphs_browser/issues/3064852)?
2. CSS? 

Not sure why this just started appearing.

**Comment by ethanteague** [comment]
PR: https://github.com/department-of-veterans-affairs/va.gov-cms/pull/1100
