### ISSUE TITLE
Edit "How to fix broken links and redirects" KB article

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#10583]
## Background
The [current article](https://prod.cms.va.gov/help/cms-basics/how-to-fix-broken-links-and-redirects) could use some updates to clarify content

## Suggested Updates

- Under the heading "How do I know I have a broken link?" there is a link for "check out top causes of broken links".  However, this is actually split into 2 links - "check out" and "top causes of broken links".  This should be fixed.
- Typo under "Linking to an archived page":
  - "When you see a number of broken appear in various pieces.." - Need to add the word "links"
  - In the first bullet for "How to fix it": "You'l need to update or remove..." - Need to add second L in "You'll"

## Acceptance Criteria

- [x] Article is updated
- [ ] Article is reviewed by Helpdesk
- [ ] Article posted to KB

**Comment by laflannery** [comment]
[Draft ready](https://prod.cms.va.gov/node/44792/latest)

**Comment by TroyA6** [comment]
I would like to suggest making 'report the problem to the CMS helpdesk' a link...

![image](https://user-images.githubusercontent.com/108767736/214395635-30e6dabc-eaa2-42c3-8322-45deacb4d238.png)

**Comment by laflannery** [comment]
Updated with Troy's note and published!
