### ISSUE TITLE
Edit "When will my Vet Center pages be available in search results?" KB article

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#10580]
## Background
The [current article](https://prod.cms.va.gov/help/vet-centers/when-will-my-vet-center-pages-be-available-in-search-results) could use some updates to clarify content

## Suggested Updates

- Typo under the heading "When will the pages be visible in search results?": "Generally, you can expect to your new pages to appear above..." - Remove "to"
- Typo under the heading "What about the legacy pages?": "Generally, you can expect to those legacy pages to point to your newly published sites in a week or two." - Remove "to"

## Acceptance Criteria

- [x] Article is updated
- [x] Article is reviewed by Helpdesk
- [x] Article posted to KB

**Comment by EWashb** [comment]
@stefaniefgray ad @TroyA6, I fixed the typos in this article if you would like to review before publish.

**Comment by TroyA6** [comment]
@EWashb @laflannery @stefaniefgray  - This revision looks good - I have not published...

**Comment by laflannery** [comment]
Same thing, I will make sure formatting matches new template then publish

**Comment by laflannery** [comment]
Published
