### ISSUE TITLE
Edit "How to add, change or remove a community access point" KB article

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#10585]
## Background
The [current article](https://prod.cms.va.gov/help/vet-centers/how-to-add-change-or-remove-a-community-access-point) could use some updates to clarify content

## Suggested Updates

- Typo under Step 7 in the heading "How to add a new community access point": "If you choose to specify hours, please add specify Hours for each day of the week" - Change to "...please add specific hours..."
- Typo under Step 4 in the heading "How to remove a community access point": "This action can not be undone." - Cannot should be one word

## Acceptance Criteria

- [x] Article is updated
- [x] Article is reviewed by Helpdesk
- [x] Article posted to KB

**Comment by EWashb** [comment]
@stefaniefgray or @TroyA6 I fixed the typos in this article. Giving you the right to review before publishing!

**Comment by TroyA6** [comment]
This looks good to me:
https://prod.cms.va.gov/help/vet-centers/how-to-add-change-or-remove-a-community-access-point

Thank you!!
Troy

**Comment by TroyA6** [comment]
@EWashb @stefaniefgray @laflannery  -- I have reviewed this KBA; it looks good - I have NOT published...

**Comment by laflannery** [comment]
Thanks @TroyA6 I'm going to make some template updates, just formatting, and then I will publish!

**Comment by laflannery** [comment]
Format updated and article published
