### ISSUE TITLE
Edit "How do I update my Vet Center facility operating status?" KB article

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#10590]
## Background
The [current article](https://prod.cms.va.gov/help/vet-centers/how-do-i-update-my-vet-center-facility-operating-status) could use some updates to clarify content

## Suggested Updates

- Typo under the heading "About Operating Status": "Text entered in in the 'Operating status -more info' field.." - Remove duplicate "in"

## Acceptance Criteria

- [x] Article is updated
- [x] Article is reviewed by Helpdesk
- [x] Article posted to KB

**Comment by EWashb** [comment]
@stefaniefgray @TroyA6 I fixed the typo. Another one for review before publish

**Comment by TroyA6** [comment]
@EWashb @laflannery @stefaniefgray  - This one looks good as well - I have not published...

**Comment by laflannery** [comment]
Published
