### ISSUE TITLE
Automate rebuilding the training environment.

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-cms#10592]
## Description
The training environment hasn't been rebuilt in three months:

![Screen Shot 2022-09-01 at 8 47 16 AM](https://user-images.githubusercontent.com/1318579/187917358-002b489c-cd44-4a31-99f7-636fdae56799.png)

It should be rebuilt manually, but likely has been neglected as a result of recent departures; it should probably be rebuilt regularly and automatically and outside of business hours to avoid interference with training.

This may be causing issues with editors' ability to complete training.

## Acceptance Criteria
- [ ] Training environment is rebuilt regularly and automatically.

**Comment by TheBoatyMcBoatFace** [comment]
Discussed in refinement on 2022-12-29 and possible alternative solutions. Considering handling this env as a prod deployment.

**Comment by ElijahLynn** [comment]
The main issue here is not a technical thing but a procedural thing. The editors go through a training and then someone makes sure they have completed certain training steps to ensure they are competent in their skillset in the CMS. Then they get assigned a proper role on prod.cms.va.gov. If we automate this the way things are now, then that "editor training progress state" is blown away. So we need to preserver the state somehow, either in the CMS or store the state elsewhere. This should be a cross-team discussion with whomever is doing training.

**Comment by stefaniefgray** [comment]
^^ @ElijahLynn is correct; we cannot lose records of which editors have completed the training assignments
