### ISSUE TITLE
Edit "How do I edit Vet Center featured content?" KB article

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#10599]
## Background
The [current article](https://prod.cms.va.gov/help/vet-centers/how-do-i-edit-vet-center-featured-content) could use some updates to clarify content

## Suggested Updates

- The Veteran-centered purpose is using italics which breaks content style guidelines

## Acceptance Criteria

- [x] Article is updated
- [x] Article is reviewed by Helpdesk
- [x] Article posted to KB

**Comment by laflannery** [comment]
@stefaniefgray and/or @TroyA6  I updated this article and it's currently a draft [here](https://prod.cms.va.gov/node/19161/revisions/688433/view).  Based on the new process we are looking to use, would one of you be able to review the article? Making sure that:

- All functionality is correct as far as you know
- The article is understandable from the editors perspective

If you need anything else from me just let me know.  If this looks good can you publish the new article and then close this ticket?  Thanks!

**Comment by TroyA6** [comment]
Sure - I'd be happy to take a look!

Thank you,
Troy

**Comment by TroyA6** [comment]
Published KBA after HD reivew
