### ISSUE TITLE
Fix the drag-and-drop table row feature and then re-enable it. 

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#1059]
**Describe the defect**
The drag and drop table row feature that [was added in a few weeks ago](https://github.com/department-of-veterans-affairs/va.gov-cms/pull/902) has a bug where it prints a column of zero values. 

 This was reported by a member of Public websites team in [this Slack thread](https://dsva.slack.com/archives/CDHBKAL9W/p1582654284032800)

Seems like [the patch on this issue queue](https://www.drupal.org/project/tablefield/issues/3040358) still needs work.

**To Reproduce**
1. Patch tablefield with [the table-drag-and-drop row feature](https://github.com/department-of-veterans-affairs/va.gov-cms/pull/902)
2. Edit existing numbers. It's unclear if this happens with _every_ table, but it's occurred on /node/767/edit on February 25, before [the drag and drop patch was removed](https://github.com/department-of-veterans-affairs/va.gov-cms/pull/1056).
3. it will add a column with zeros, like in the screenshot below. 

**Expected behavior**
Table should appear as expected. 

**Screenshots**
![Servicemembers’_Group_Life_Insurance__SGLI____Veterans_Affairs](https://user-images.githubusercontent.com/643678/75299220-78516300-5802-11ea-8e2f-f25f16f17bdf.jpg)

**Comment by FranECross** [comment]
According to this Slack thread, the issue was resolved. https://dsva.slack.com/archives/CDHBKAL9W/p1582838506082400?thread_ts=1582654284.032800&cid=CDHBKAL9W
