### ISSUE TITLE
Implement tests for event location form-state conditionals

### ISSUE THREAD

**Issue by dsasser** [department-of-veterans-affairs/va.gov-cms#10605]
## Description
Form components in CMS are being manipulated for Events, but lack test coverage.

This issue covers conditional logic around event location.

This was originally [discussed in a related CMS PR](https://github.com/department-of-veterans-affairs/va.gov-cms/pull/10574#:~:text=without%20a%20hitch.-,Do%20you%20have%20a%20couple%20hours%20to%20spare%20writing%20Cypress%20tests%20that%20replicate%20your%20QA%20steps%3F,-Member).

## Spec
Scenario: As a content editor, when I create or edit an event and select the location type, new, relevant fields should be exposed depending on what event location type I chose.

Scenario: As a content editor, when I create or edit an event and change the event location type, any previously filled conditional fields should clear out.

## Acceptance Criteria
- [ ] Evaluate Drupal code for conditional logic around **event locations** that needs tests
- [ ] Implement tests

Note: Steve W recommends writing tests on the VAgov side as well. 

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by jilladams** [comment]
To be defined: test cases we want to cover

**Comment by wesrowe** [comment]
I added an epic and assigned to @dsasser for pre-refinement. (Issue was already in appropriate refinement-board column.)

**Comment by chri5tia** [comment]
From: https://github.com/department-of-veterans-affairs/va.gov-cms/pull/10574
QA Steps: 
> Go to /node/add/event
> Set the location type to "At a VA facility"
> Fill in the facility location
> Fill in the building number

Cypress translation:

Scenario: 
- [x]  Given I am logged in as a user with "content_admin" role
- [x]  And I am at "node/add/event"
- [ ]   And I set the location type to "At a VA facility"
- [ ]   I can see a field for "Facility location" and "Building, floor, or room"

Add the spec here:
[va.gov-cms/tests/cypress/integration/behavioral/content_editing.feature](https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/tests/cypress/integration/behavioral/content_editing.feature)

Use these and add to them here:
https://github.com/department-of-veterans-affairs/va.gov-cms/tree/main/tests/cypress/integration/behavioral/common

**Comment by chri5tia** [comment]
Conversely to my logic above, looking at [Steve's steps to reproduce the original problem](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9649#issue-1289602901), I might want to revise the test spec:

> Go to '/node/add/event'
> Fill in all required fields
> For location, choose online event.
> enter a url for the online event. (save the node or not)
> Change your mind and choose location for a facility or another address.
> Enter some values.
> Save the node, notice that data exists for more than one of the choices.
