### ISSUE TITLE
Edit "Process for publishing Vet Center pages" KB article

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#10601]
## Background
The [current article](https://prod.cms.va.gov/help/vet-centers/what-is-the-process-for-publishing-my-vet-centers-pages) could use some updates to clarify content

## Suggested Updates

- The format of this article is unlike all other articles.  Is there a reason for this change?

## Acceptance Criteria

- [x] Article is updated to use new template
- [x] Article is reviewed by Helpdesk
- [x] Article posted to KB

**Comment by laflannery** [comment]
[Draft article ready for review](https://prod.cms.va.gov/node/43971/latest)

**Comment by laflannery** [comment]
Get sitewide content to review after Stef does

**Comment by dawnpruitt** [comment]
Pending help desk and sitewide content review.

**Comment by TroyA6** [comment]
It looks like a correction might be needed here:


![image](https://user-images.githubusercontent.com/108767736/214394854-e371cc3c-d4a4-4ce4-9a14-a0e3fd8ab8ea.png)

**Comment by laflannery** [comment]
Typo fixed, Final step, I will need to get with Sitewide content to see if this is something they would like to review before publishing

**Comment by stefaniefgray** [comment]
Had originally reviewed with @laflannery back in late Dec. 2022

Article good to have in case future Vet Centers go live, but otherwise good to go

See latest Laura draft: https://prod.cms.va.gov/node/43971/latest

**Comment by laflannery** [comment]
Published!
