### ISSUE TITLE
Refactor GitHub Actions

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-cms#10619]
## Description
These share a lot of steps, variables (e.g. PHP version), etc.  Plus they're presumably consuming a lot of resources doing so.  Let's refactor our GHAs so they DRY.

## Acceptance Criteria
- [ ] GitHub Actions are well-factored.

**Comment by cweagans** [comment]
Related: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9416 and https://github.com/department-of-veterans-affairs/va.gov-cms/issues/8667
