### ISSUE TITLE
Archived Form Detail page for 10-10EZ (esp) showing in search results

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#10620]
## Describe the defect

In Find-a-form, results for a Form Search [search for form 10-10ez](https://www.va.gov/find-forms/?q=10-10ez) returns a Form Detail page for a form that has been archived, the Spanish version of 10-10EZ. 

Things to note:
- The Form Detail page for the Spanish version of 10-10EZ is [archived in Drupal](https://prod.cms.va.gov/node/5745/edit)
- The search result is not completely rendered, as its title/heading is not hyperlinked to the archived Detail page
- The CTA for the link to the online tool `Llene el formulario VA 10-10EZ (esp) en línea.` is in spanish – where is the code that does that, and how does it work?

## AC / Expected behavior

- [ ] Prevent this archived Form Detail page from showing in Form Search results
- [ ] Document how the CTA is translated to Spanish
- [ ] Write follow-up tickets for any further investigation that is suggested by discoveries

## Screenshots

![image.png](https://images.zenhubusercontent.com/61a671f5fc46c2a311655f75/e2c31065-9c66-4a7a-aec9-e37fbe87d961) 

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by jilladams** [comment]
Injected into Sprint 66 per 2:1 with Wes & Dave.

**Comment by jilladams** [comment]
Code changes not required. Findings: https://dsva.slack.com/archives/C52CL1PKQ/p1662655106201149

Randi will follow up to make the content changes. Closeable.
