### ISSUE TITLE
Discovery: Translation import/export options

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#10631]
## Description

As a Sitewide Content owner, I want the system to automate export (of English content) and import (of translations from partners) so that we don't suffer the inefficiency and error proneness of manual copy-pasting.

Daniel already studied a translation demo environment in another issue in this epic. 

In a follow-up meeting, stakeholders are very interested in what import/export capabilities would be available for us to use, either as core or contrib modules, once we've turned on Drupal's core translation capabilities.

Use cases for guidance:
- Content page (not menus, etc)
- Assume Benefits Hub related
- Export an xliff of English version, and import translated version into same node

## Acceptance Criteria
- [x] Investigate Adam's demo environment for import/export (Steve W thinks he saw this demonstrated)
- [x] Investigate other options and assess usefulness to stakeholders
- [x] Document in a well-named file in [this github directory](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/content-localization/translation-recommendation-project/2022-continuation-by-public-websites)
  - [Initial document](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content-localization/translation-recommendation-project/cms-export-import.md)

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by dsasser** [comment]
I would start by looking at this module which claims to support xliff import/export an other enhancements to the translation UX.

https://www.drupal.org/project/tmgmt

**Comment by timcosgrove** [comment]
Initial document created at https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content-localization/translation-recommendation-project/cms-export-import.md
