### ISSUE TITLE
php 8.1 related issues

### ISSUE THREAD

**Issue by edmund-dunn** [department-of-veterans-affairs/va.gov-cms#10643]
`PHP Parse error:  syntax error, unexpected token "match" in /var/www/html/docroot/vendor/caxy/php-htmldiff/lib/Caxy/HtmlDiff/HtmlDiff.php on line 699`

Update drush to v11.

drupal/styleguide `Deprecated function: strpos(): Passing null to parameter #1`

`Deprecated function: strtolower(): Passing null to parameter #1 ($string) of type string is deprecated in Drupal\node_link_report\Plugin\Block\NodeLinkReport->isAllowed() (line 895 of modules/contrib/node_link_report/src/Plugin/Block/NodeLinkReport.php).`

**Comment by EWashb** [comment]
You're working on this for Sprint 66 @edmund-dunn ?

**Comment by edmund-dunn** [comment]
@EWashb yes, this stemmed from the other PHP 8 ticket.

**Comment by edmund-dunn** [comment]
Fixed the issue for the Diff module. Just had to explicitly require `"caxy/php-htmldiff": "^0.1.14",` which is php 8.1 ready. It is a 3rd level dependency fo teh Diff module.

**Comment by edmund-dunn** [comment]
Updated drush to v11 which is php8.1 compatible.

**Comment by EWashb** [comment]
@dawnpruitt for your awareness for reporting

**Comment by edmund-dunn** [comment]
patched drupal/styleguide for php8.1 compatibility.
