### ISSUE TITLE
Next-build should use https when interacting with local Drupal

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#10665]
## Description
Currently if we point next-build at a DDEV installation for its API source, we need to do one of two things:
* point to http://va-gov-cms.ddev.site
* add NODE_TLS_REJECT_UNAUTHORIZED=0 to environment variables for Next.js

Ideally, next-build would be able to use a https local without issues or workarounds.

This should be as simple as pointing next-build at the mkcert CA that DDEV uses.

## Acceptance Criteria
- [ ] next-build is able to point at a local DDEV https URL without workaround or configuration

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [x] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by tjheffner** [comment]
Fixed in: https://github.com/department-of-veterans-affairs/next-build/pull/147
