### ISSUE TITLE
FE: Implement adding Veterans Crisis Line prompt in footer on screens 767px wide and smaller

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#10668]
## Description
Design discussion / proposal: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10348

Sketch file: https://www.sketch.com/s/3aa40506-4be2-46cc-876b-93f1a9f3a857

Screenshot: 
![VCL banner on bottom nav](https://user-images.githubusercontent.com/106624475/188723977-ba8ad502-38ad-4f46-9b50-ca368b231a5e.jpg)

## Acceptance Criteria
- [ ] VCL modal trigger appears in footer, as per Sketch file, with its own ID for 508 purposes, to distinguish it from the prompt in the header.
- [ ] Review on review instance with Wes or designer (Val Rundle?) before merge

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [X] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by wesrowe** [comment]
Design review: I checked it out in the review instance, it looks good. ✅
