### ISSUE TITLE
CMS: Vet Center Locations pages do not show mobile on node:view.

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#10667]
## Describe the defect
When I look at node:view on a Vet Center location page, I can see the "Main and satelite locations" but I can not see "Display additional mobile vet centers"
![image](https://user-images.githubusercontent.com/5752113/189230951-39c770ef-7903-4e83-9ac3-2fe16d497d6e.png)

Surfaced in [this slack thread](https://dsva.slack.com/archives/C02730UEZPS/p1662667671380849)
## To Reproduce
1. Go to '/node/28131/edit'
2. Notice that it has an entry for a mobile vet center
3. Click on the "View" tab and notice that the mobile vet center does not show.
4. It does show correctly on https://www.va.gov/dundalk-vet-center/locations and the preview server http://preview-prod.vfs.va.gov/preview?nodeId=28131

## AC / Expected behavior
- [ ] When on node view, the field and any entries for it are shown in a similar fashion as "Main and satelite locations"

## Screenshots
![image](https://user-images.githubusercontent.com/5752113/189231634-50c020eb-850e-415c-8489-20586024a7d6.png)

 ## Additional context
Add any other context about the problem here. Reach out to the Product Managers to determine if it should be escalated as critical (prevents users from accomplishing their work with no known workaround and needs to be addressed within 2 business days).

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Defect")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS workstream (orange) (not needed for bug tickets)
- [ ] CMS-supported product (black)

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by omahane** [comment]
What UI should the editors expect if this field is shown on the node:view?
Right now, when I enable the display, it uses the field template to render it, unlike the Main and Satellite locations. See attached.
<img width="1820" alt="Screen Shot 2022-09-28 at 10 29 39 PM" src="https://user-images.githubusercontent.com/766573/192932494-47f86030-0711-44b0-9b0d-d80ea8c3ed00.png">

The view is being set in the va_gov_vet_center.module, lines 90 - 125. (See attached).
![Screen Shot 2022-09-28 at 10 31 55 PM](https://user-images.githubusercontent.com/766573/192932593-16758472-71ec-4acd-87ac-4257adfa1efe.png)

If the editor expects the Additional Mobile Vet Centers to mirror the look of the Main and Satellite locations, it is more than a 1 point task, as it will involve rewriting the function that already exists, writing a new function, altering the view that is called, creating a new view display, or some combination of those.

**Comment by JayDarnell** [comment]
One potential way to address this would be to create a second view display to only display mobile vet centers referenced by the Locations node we're looking at (accomplished with a contextual filter) and then embed that new view display into the footer of the original.

Discussion with some screenshots here: https://dsva.slack.com/archives/C0FQSS30V/p1664570285652449
