### ISSUE TITLE
Adapt FE table component(s) to new heading-location attribute

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#10676]
## Description

As a Veteran using a screen reader, I want table headers to be labeled correctly in tables whether they're at the top, left, or both, so that I can understand the table content.

### Details:

Once #10675 is completed, Drupal will be able to provide data to the FE regarding where headers are positioned in a table. 

## Acceptance Criteria
- [ ] Table component defaults to top row (status quo) if Drupal doesn't provide data
- [ ] Table component adds appropriate accessibility attributes to top row, first column, or both based on Drupal data when present
- [ ] Add end-to-end tests (?)
- [ ] Testable_Outcome_Z
- [ ] Requires Accessibility review

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by jilladams** [comment]
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10800#issuecomment-1318650289
Closing
