### ISSUE TITLE
6102 handbook guidance readout 

### ISSUE THREAD

**Issue by EWashb** [department-of-veterans-affairs/va.gov-cms#10677]
## Description

Results from #10478 are to be shared with Sitewide CMS team and PO. 

## Acceptance Criteria
- [x] hold meeting with PO and Sitewide CMS team to go over findings from #10478
- [x] Determine next steps for the guidance as it relates to CMS notifications

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [x] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by EWashb** [comment]
@valerierunde would you like me to set up this meeting?

**Comment by valerierunde** [comment]
@EWashb I wasn't sure if you had a plan for this or not, so I didn't do anything with it yet. Is it the whole Sitewide CMS team and Dave?

**Comment by EWashb** [comment]
Yes, our Sitewide CMS team plus Dave. I didn't have a day planned yet, so you can feel free to book whatever you'd like for this

**Comment by valerierunde** [comment]
Meeting scheduled for Tuesday, 9/20/22.

**Comment by valerierunde** [comment]
https://app.mural.co/t/vagov6717/m/vagov6717/1662643881820/ad0f6da63dba4998516450701abca6ec1944ec74?sender=u0f6a693f731ee0b19ea13269

[10478 Section 6102 Compliance.pdf](https://github.com/department-of-veterans-affairs/va.gov-cms/files/9617292/10478.Section.6102.Compliance.pdf)
