### ISSUE TITLE
Runbook: Lovell Launch - Dual State

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#10670]
## Description
This is the runbook containing all necessary steps to move Lovell into Dual State.

##  Prep for Dual State
- [x] #12382 
- [x] #11635

## Launch into Dual State
These steps must be performed manually, on production, once the any prep items above have been completed and all code has been deployed to production. 

- [x] Publish all content in [section Lovell Federal health care ](https://prod.cms.va.gov/admin/content/bulk?title=&type=All&moderation_state=All&taxonomy_entity_index_tid_depth=347)
- [x] Archive Lovell umbrella system - add log message that says it can not be deleted and must never be published. https://prod.cms.va.gov/node/15007/
- [x] Update existing banner with details from 11635 above and move to Lovell VA AND Lovell Tricare subsystems - https://prod.cms.va.gov/node/40013/

**Comment by Dottisea** [comment]
For sprint 77 we are making sure the steps are correct - see 12374

**Comment by JayDarnell** [comment]
@Dottisea I believe this issue is now complete. I made very minor changes. We should keep this issue in mind as we get closer to having Lovell feature complete and update this issue if necessary with any additional steps.

**Comment by kmariepat-cityfriends** [comment]
- Editors will be informed today 3/9
- Though it will be launched on Monday 3/13

**Comment by JayDarnell** [comment]
What an epic achievement this is. Nice work everyone!
