### ISSUE TITLE
Spike: How to remove default-to-healthcare when header megamenu is opened

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#10678]
## Description

As a Veteran, I want the "VA Benefits and Health Care" mega-menu to only show the list of benefits hubs when I open the dropdown so that I can more easily discern that each of the hubs has its own sub-menu panel.

### Details

When a Veteran opens the Benefits megamenu by clicking in the header, the megamenu opens the Healthcare hub by default. This is confusing because it prevents the user from realizing that the large panel on the right is a sub-menu related only to the first Hub, Healthcare.

<img width="538" alt="image" src="https://user-images.githubusercontent.com/4054752/189418754-cabf78a1-147a-46ec-91b9-37ceb0f2d7b2.png">

**Desired behavior**

When the user opens the megamenu, they should see only the dropdown containing the benefit hub links. To open any Hub's sub-menu/panel, the user has to click on one of the first-level options.

## Additional context
The mobile header is in React, and introduces page weight/speed issues on slow/old devices. 
The header is not a web component, but could be, if we determine that's the correct path forward to A) fix this particular issue, and B) optimize the header / reduce duplicate code for the mobile header, etc.

## Acceptance Criteria
- [ ] Describe / understand the work required for a click on "VA Benefits and Health Care" in the header opens only the first level of menu options 
- [ ] Consider: given the lift, should we be rethinking the header as a web component?
- [ ] Create implementation ticket(s) for next steps & ping Wes/Jill with links

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by ryguyk** [comment]
This is likely going to be a significant lift to change this behavior, as it's currently implemented in a manner where the entire panel (menu on left and content pane on right) shares one "background".

As such, it's difficult to grab a screenshot of what things might look like by simply hiding some elements via css. Here's a rough idea of what it might look like by just copying/pasting (note: drop shadow stops because of cutting; though, again, implementing would be difficult).

![image](https://user-images.githubusercontent.com/6863534/189725477-13494126-0af0-476f-8cc3-b70410f3882f.png)

**Comment by jilladams** [comment]
![Screen Shot 2022-09-12 at 11 25 29 AM](https://user-images.githubusercontent.com/85581471/189729353-23935d11-054a-4117-be21-03952acbabf7.png)

**Comment by jilladams** [comment]
One note I just thought about: the header gets injected into legacy TeamSite pages (an old Microsoft CMS) using the [proxy-rewrite app](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/proxy-rewrite). There's duplicate code in there for the header, so we'll need to look at that as well, re: getting this same change working for sites that receive the injected header. Sorry we missed that in the original ticket write up!

**Comment by jilladams** [comment]
@apisandipas I went ahead and created an implementation ticket to track next steps here, #10811 . Closing the spike, and any work to close out the PR can happen / get documented on the implementation ticket.
