### ISSUE TITLE
Prototype Table UI with header-location checkboxes

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#10674]
## User story

As an Editor, I want to tell Drupal where table headers are so that Veterans using screen readers can understand table content.

## Background

We intend in this epic to add a Drupal tablefield patch that enables Editors to tell Drupal whether table headers are the top row, the first column, or both. 

See below for a screenshot of where the tablefield patch drops the checkboxes by default. Their meaning is not obvious. Place them and add content so that it will be immediately clear to Editors what these checkboxes do and why Editors should take the time.
<img width="674" alt="image" src="https://user-images.githubusercontent.com/4054752/189400531-460f908a-d909-498f-bdb7-ec97c83d7e4d.png">

## Acceptance Criteria
- [ ] Figma prototype 
  - [ ] linked from this issue and 
  - [ ] housed in a workspace that will be owned by the program in perpetuity

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by wesrowe** [comment]
@jilladams, note for sprint report that we injected this today (Fri) and Florence cranked it out. So I added the S66 and Unplanned work labels

**Comment by fmccaf1** [comment]
[And here's the Figma file](https://www.figma.com/file/GiUzUBdo7HJaRsoNdie38U/Tableview-Patch-UI?node-id=0%3A1)
