### ISSUE TITLE
Request content input/review for new header-location fields in CMS

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#10683]
## User story

As an Editor, I want to tell Drupal where table headers are so that Veterans using screen readers can understand table content.## Description

## Background

In #10674 Florence provided a design for how the checkboxes provided by the "tablefield patch" could be placed so that their function would be clear to Editors. We need to get copy input from Sitewide-CMS.

## Acceptance Criteria
- [ ] Copy ready for development

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by davidmpickett** [comment]
@wesrowe @jilladams - Is this the CMS Design task penciled in for Sprint 70 on q4 planning? Confirming the proposed wireframes and potentially editing /updating them? Or are there additional interactions to design?

**Comment by jilladams** [comment]
I believe so. What isn't represented here is 1) that we're going to do an audit that may yield a different direction for next steps, and 2) the notes on prior design feedback. Florence did do a design for this that was based on modifying what the Drupal TableField module does by default in a patch. But: the direction of that was problematic -- we have both design and eng feedback that we should summarize here as an input for what comes next. I can find the eng notes, and @wesrowe knows most about Val's feedback on that design.

**Comment by wesrowe** [comment]
Val pointed out the sighted-user and Editor sides of the equation. In a nutshell: if you let an Editor say "my headers are in the first column," you then need the FE to look that way and you need the Editor experience to consistently look that way. We had initially looked at it as an accessibility fix where we would just add a few attributes to html to identify headers. The visual design needs are far more impactful across Drupal and the FE templates, and could even require Platform Collab Cycle and possibly exceptions from or changes to the design system.

You can see why shoring up 508 compliance on the existing default (headers at top) is so attractive. Also, the Editor experience has basically steered/assumed top headers from the beginning, so we expect to find in the audit that most/all tables in the wild have top headers.

**Comment by davidmpickett** [comment]
Okay, starting to understand the problem space. Based on a [slack thread with Laura](https://dsva.slack.com/archives/C52CL1PKQ/p1665419064692469) I would also say from a design perspective that checkboxes are not the way to go for the patch (if we need to patch).

**Comment by jilladams** [comment]
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10800#issuecomment-1318650289
Closing
