### ISSUE TITLE
UX: Revisit FE design for multiple service locations per service

### ISSUE THREAD

**Issue by dsinla** [department-of-veterans-affairs/va.gov-cms#10687]
## Describe the defect
On a VAMC Facility page, Services with multiple locations display confusing location information

Additionally, I suspect some editors are misusing Add Location, when their intent may be to add custom hours or a custom phone number, resulting in 2 entries that are confusing to the Veteran visitor. 
https://www.va.gov/finger-lakes-health-care/locations/bath-va-medical-center/
![image](https://user-images.githubusercontent.com/62269210/189507445-97237506-7748-44c4-ae2c-fb376107c073.png)

## To Reproduce
1. Go to https://www.va.gov/portland-health-care/locations/portland-va-medical-center/
2. Scroll down to **Health services offered here**
3. Expand the Podiatry service accordion
4. After the descriptive text, several bold headers are displayed
5. It is unclear how many distinct service locations are listed, it is unclear how these headers are grouped, and which information relates to which location. 
6. Under the header Portland VA Medical Center, the word _Varies_ is displayed in italics. It's unclear what this applies to.

Refer to https://prod.cms.va.gov/node/25432/edit for the 

## AC / Expected behavior

- [ ] An audit of the current behavior for multiple service locations is performed
- [ ] The desired behavior is determined
- I would propose a very distinct visual indication of separate service locations. Better grouping/subordination. A shaded box? If Service Location > 1 - then a distinct label **Service Location 1, Service Location 2, Service Location 3**  ?
- What should be the display behavior when an editor selects _Use the facility's hours_?
-  What should be the display behavior when an editor enters a Building or Floor? Right now the text is shown with no labeling: "78 3rd Floor" rather than "Building 78 3rd Floor"
- What should be the display behavior when an editor selects _Use the facility's street address_? Seems like it's suppressed from being displayed, and the assumption is that the Veteran will understand the address
- What should be the display behavior when an editor selects  _Use the general facility phone number_?
- What should be the display behavior when an editor select _Do not specify hours_ and then enters descriptive text? Currently there's no indication that the descriptive text is related to hours.
- Does _Referral Required_ and _Walk-ins accepted_ span all service locations - right now it seems it does. Would walkins be accepted at one location but not another? 
- [ ] The editorial interface is modified with guidance for editors 
- [ ] The desired behavior is implemented 

## Screenshots
![image](https://user-images.githubusercontent.com/62269210/189506336-00e92ace-8003-4878-8ab8-0dccc283d0d5.png)
 ## Additional context
Add any other context about the problem here. Reach out to the Product Managers to determine if it should be escalated as critical (prevents users from accomplishing their work with no known workaround and needs to be addressed within 2 business days).

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Defect")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS workstream (orange) (not needed for bug tickets)
- [ ] CMS-supported product (black)

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by dsinla** [comment]
Links to previous reporting/documentation of this issue, and proposed design:

[VAMC service location headings #36933](https://github.com/department-of-veterans-affairs/va.gov-team/issues/36933)
[[DISCOVERY] for multiple VAMC health service locations #36934](https://github.com/department-of-veterans-affairs/va.gov-team/issues/36934)
[Implement design iteration for multiple VAMC health service locations #36566](https://github.com/department-of-veterans-affairs/va.gov-team/issues/36566)

**Comment by davidmpickett** [comment]
@thejordanwood Here's a relevant ticket to your ongoing VBA design work. The existing VAMC pattern for multiple service locations is confusing, how can we iterate in a way that improves this?

**Comment by davidmpickett** [comment]
And some notes from a previous designer https://preview.uxpin.com/c53f89d47dcf140eac97df4e70896be4f40877c2#/pages/147451739/documentation/no-panels?mode=i

**Comment by davidmpickett** [comment]
See also: https://github.com/department-of-veterans-affairs/va.gov-team/issues/18831

**Comment by davidmpickett** [comment]
A potential redesign from https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13791
![Service_Accordion_annotated](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/1fa03c77-eae9-41f3-a7a7-3708661cdaa1)

**Comment by jilladams** [comment]
@kmariepat-cityfriends I believe this got moved to the wrong lane automatically from the Speedrun board integration. I moved it back to In Progress - let me know if that's not correct, or feel free to put it back where it should go.

**Comment by kmariepat-cityfriends** [comment]
@jilladams this also wasn't in the sprint officially, it got added by a bulk change, this card was here for reference for @thejordanwood while working on VBA design of multiple service locations, see originally Sprint 86 plan here:Facilities Sprint Plan 86 #13873

I removed sprints from this card

**Comment by davidmpickett** [comment]
Feedback from VBA midpoint review may mean this becomes an experimental design request -https://github.com/department-of-veterans-affairs/va.gov-team/issues/63006

**Comment by davidmpickett** [comment]
@thejordanwood [resolved this in VBA design](https://www.sketch.com/s/891d33ae-152d-471c-ab5d-9aedf89cf6ff/p/DC11E46F-AF92-4DFD-AC0B-BEB9A9DD3C9A/canvas) using the card component

![Screenshot 2023-11-06 225924](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/5c91e7f2-9657-4b47-9425-7b688194f7de)

This will launch with the VBA Pilot. VAMC templates can also be updated to use this pattern. Closing this as the primary UX iteration cycle is done and we are approaching implementation
