### ISSUE TITLE
Implement tests for event registration form-state conditionals: call to action

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#10682]
## Description

Form state conditionals for the Events form need Cypress test coverage.
This issue covers conditional logic around the "Call to action" drop down which exposes a URL field when anything other than "none" is selected. 

<img width="877" alt="Screen Shot 2022-11-16 at 2 00 29 AM" src="https://user-images.githubusercontent.com/22764938/202150341-c71cc737-0b0d-4ae8-b0cd-1539adfd13a4.png">

This was originally [discussed in a related CMS PR](https://github.com/department-of-veterans-affairs/va.gov-cms/pull/10574#:~:text=without%20a%20hitch.-,Do%20you%20have%20a%20couple%20hours%20to%20spare%20writing%20Cypress%20tests%20that%20replicate%20your%20QA%20steps%3F,-Member).

Note: This story is a clone of #10605, per team's recommendation in refinement meeting.

## Acceptance Criteria
Tests should be written for va.gov-cms and ensure that:
- [ ] The URL field opens up if anything other than "None" is selected.
- [ ] The URL field is cleared out if it is filled out and then "None" is selected afterward.

Note: Steve W recommends writing tests on the VAgov side as well. 

## Spec

Scenario: As a content editor, while creating or editing an Event, I need to ensure that if I chose a call to action for event registration that there is a URL field available for more information.

Scenario: As a content editor, while creating or editing an Event, I need to ensure that if I had filled out the event call to action and URL and then change my mind, that that part of the form is cleared out.

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

_Updated by Christia on 11/16/22._

**Comment by chri5tia** [comment]
@wesrowe Can you explain what conditionals we are testing for event registration? I'm trying to fill this out so I can write something like this for the location conditionals, specifically the spec: 
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10605#issuecomment-1315445323

**Comment by wesrowe** [comment]
I'm not familiar with the logic and I know Daniel is underwater – @swirtSJW, can you help?

**Comment by jilladams** [comment]
I think we are talking here about if you specify Location: At a non-VA location. Selecting that radio button triggers exposing the full address fields: 

![Screen Shot 2022-11-15 at 2 27 02 PM](https://user-images.githubusercontent.com/85581471/202038305-caec10ea-d1d9-4c56-9c4d-733b97395f14.png)

**Comment by wesrowe** [comment]
What @jilladams said – and also, selecting Online makes a URL field show.

**Comment by wesrowe** [comment]
Oh wait... what's the difference between this one and  [Implement tests for event location form-state conditionals](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10605)?

**Comment by jilladams** [comment]
All of these test tickets started from [this PR](https://github.com/department-of-veterans-affairs/va.gov-cms/pull/10574), where folks requested Cypress tests to imitate his manual QA steps. @chri5tia if you consider the 3 tickets a batch, and those QA steps as the desired end result for Cypress coverage, does that help us through?

**Comment by chri5tia** [comment]
Yes @Jill, and @Wes that's what I am wondering. I thought maybe there were conditionals within the address section of non-VA facility, but I don't see it. I have a strong feeling this ticket is related to the work I've already scoped and am finishing up for the location one that you linked to. (#10605).

**Comment by chri5tia** [comment]
Cypress tests pass for:

  Scenario: Confirm that the event form registration checkbox reveals conditional form elements
    Given I am logged in as a user with the "content_admin" role
    And I am at "node/add/event"
    And I check the "Include registration information" checkbox
    Then I should see "Registration is required for this event"
    And I should see "Call to action"
    And I select option "Register" from dropdown "Call to action"
    Then I should see "URL"
