### ISSUE TITLE
Implement tests for event registration form-state conditionals

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#10681]
Note: This story is a clone of #10605, per team's recommendation in refinement meeting.

## Description

Form components in CMS are being manipulated for Events, but lack test coverage.

This issue covers conditional logic around event registration.

This was originally [discussed in a related CMS PR](https://github.com/department-of-veterans-affairs/va.gov-cms/pull/10574#:~:text=without%20a%20hitch.-,Do%20you%20have%20a%20couple%20hours%20to%20spare%20writing%20Cypress%20tests%20that%20replicate%20your%20QA%20steps%3F,-Member).

## Acceptance Criteria
- [ ] Evaluate Drupal code for conditional logic around **event registration** that needs tests
- [ ] Implement tests

Note: Steve W recommends writing tests on the VAgov side as well. 

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by wesrowe** [comment]
@chri5tia, I think you're on the right track. I noticed that there's a sort of nested set of tests – if I select something other than 'None' from the CtA dropdown, I expect to see a URL field.

**Comment by chri5tia** [comment]
@Wes, ah yeah and then those should clear out as well. I bet this is what the #10682 10682 ticket is supposed to be for. For now, I am going to reword the ticket to include this piece (URL instead of Addresss).

**Comment by chri5tia** [comment]
These tickets are all running together. As I posted in #10682,   Scenario: Confirm that the event form registration checkbox reveals conditional form elements
    Given I am logged in as a user with the "content_admin" role
    And I am at "node/add/event"
    And I check the "Include registration information" checkbox
    Then I should see "Registration is required for this event"
    And I should see "Call to action"
    And I select option "Register" from dropdown "Call to action"
    Then I should see "URL"
