### ISSUE TITLE
Create table headers inline content guidance 

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#10705]
## Background

While implementing a tablefield patch to remediate a 508 issue, we are aiming to improve the user experience of creating tables within the CMS, including improving the inline guidance regarding table headers. The aim of this guidance is to:

- Explain the purpose of table headers without overwhelming editors.
- Ensure the guidance is not too lengthy. Lengthy content is often ignored by editors.

## Acceptance Criteria

- [x] Create suggested inline guidance
- [x] Send to UX for review/approval
- [x] Update Figma file (if possible)
- [x] Update screenshot or add comment on #10675 to indicate approved guidance

**Comment by laflannery** [comment]
@valerierunde I was hoping you could assist with some more inline guidance, this time for tables.  I am looking to provide better guidance for both the table title and table headers. [This issue](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10675) has a screenshot of what the table field will look like, where the inline guidance will be.  Would you be able to take a look at what I have proposed below and let me know if you have any suggestions?

**Table Title**

> The table title should be clear and concise. The title helps to describe the purpose of the table data to the user.

**Choose Table Header(s)**

> Table headers are important for accessibility. They indicate to screen reader users which row and/or column the cell data is associated with as the table is read through. Correctly identifying the table headers will ensure that the data can be easily understood by site visitors.

**Comment by valerierunde** [comment]
@laflannery Thanks for reaching out! Here are my thoughts:

**Table Title**

> Add a clear and concise title that describes what information is in the table.

**Table Header(s)**

> Add table header(s) to help people understand the information in the table. People who use screen readers need headers to help them navigate through the table and understand the row and column they're in.

P.S. Laura, I'm writing this without much context, but I assume the tables we're talking about are for all users (those with and without screen readers) so I generalized the inline guidance to not be just about screen reader users but all users.

**Comment by laflannery** [comment]
Thanks @valerierunde! You are correct that all users will see these tables and the information provided.
