### ISSUE TITLE
CMS: Update how COVID status feature works on VAMC facilities

### ISSUE THREAD

**Issue by dsinla** [department-of-veterans-affairs/va.gov-cms#10708]
## Description

The current (Sep 2022) bulleted descriptive text for COVID status policies does not meet the operational reality at the facilities - it's not granular enough to give Veterans the variation of policies that are in place at each facility.

- The editorial interface should be updated to match the design from #10842
- Will also need to update the field that sends information to the COVID status
- May be intertangled with #11794

The content team is providing [guidance for editors](https://github.com/department-of-veterans-affairs/va.gov-team/issues/45774), which will need to be added to a new KB article that will be referenced from the COVID-19 status area of the editorial interface. 

## User Stories

As a Veteran, I want information about COVID policies that reflects the reality at the facility, in order to prepare for my visit.
As a VAMC editor, I want guidance on the best way to author content that accounts for the reality of the policies at my facility. 

## Acceptance Criteria
- [ ] ~The **COVID-19 status** descriptive text is rewritten and a link to the KB guidelines is provided.~ See Figma
- [ ] ~The **Guidelines** section is removed~  This section is not a section, it is content on the three taxonomy terms.  The solution is to https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12111
- [x] **Operating status** descriptive text is updated - ~it should instruct editors to use the open field for COVID status (perhaps link to the KB again in this area)~  follow Figma
- [x] New field field_supplemental_status_more_i is added to health_care_local_facility content type
   - Cardinality 1.
   - rich text limited 
   - required
   - 500 character count limit excluding html
 - [x] field layouts labels and guidance text matches [FIGMA](https://www.figma.com/file/IYpeP2ZAmBTT8jqhdtJklu/Covid-%2F-Facility-Status?node-id=128%3A32180&t=GcTmUSaSHKT2y5BN-0)
 - [x] When a selection in field_supplemental_status is made/changed, the  term facility_supplemental_status->description immediately populates the node's field_supplemental_status_more_i with the same html and content.
 - [x] Once populated, field_supplemental_status_more_i can be changed as needed by the editor.
 - [x] cypress test fails if field_supplemental_status_more_i is not populated on change of field_supplemental_status

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by swirtSJW** [comment]
I updated the Guidelines related AC

**Comment by dsinla** [comment]
Is this a good first ticket for Blake? Need to weigh in among priorities - consult with Erika

**Comment by omahane** [comment]
@davidmpickett Do we have locked down language and design for this issue?
I see areas of ambiguity here:
- "COVID-19 status descriptive text is rewritten"
  - What is the rewritten text?
-  "Operating status descriptive text is updated"
  - Do we have updated copy to use?
-  "Validation notification": ""During the COVID 19 pandemic you must select Facility notice and provide guidance for your facilities COVID policies in the Details section."
  - Is this language right or only an approximation?
 - The [figma design](https://www.figma.com/file/IYpeP2ZAmBTT8jqhdtJklu/Covid-%2F-Facility-Status?node-id=15%3A33336&t=mWMRJC1qGgx0Zv44-0) has 2 options. It's not clear to me which has been chosen.

**Comment by davidmpickett** [comment]
Tagging in @BlakeOrgan here as he was involved in these conversations more directly.

**Comment by omahane** [comment]
@davidmpickett @BlakeOrgan Does this only apply to VAMC facilities? I know we only have COVID status information on those, as opposed to Vet Centers and VBA facilities, but I want to make sure I understand the scope of the ticket.

**Comment by omahane** [comment]
- Should there be a configuration form for site admins to choose whether to have "Normal services and hours" unselectable?
	- Would it apply only to VACM facilities or others, too?
- Do we have forms like that elsewhere? If so, where? Perhaps under "Content Authoring"

**Comment by davidmpickett** [comment]
Jay noted that there will likely be a lighthouse implication

**Comment by JQuaggles** [comment]
@omahane Is this refined enough to do? And is 5 still accurate?

**Comment by omahane** [comment]
Here's the most recent design that @BlakeOrgan provided:
https://www.figma.com/file/IYpeP2ZAmBTT8jqhdtJklu/Covid-%2F-Facility-Status?node-id=128%3A32180&t=GcTmUSaSHKT2y5BN-0

**Comment by davidmpickett** [comment]
Per conversation in Refinement last week, the parts about "Normal services and hours" being unselectable are no longer the desired direction and I removed the ACs about them

**Comment by davidmpickett** [comment]
**Facility Supplemental Status Taxonomy Terms**

- No code changes needed here
- PM to confirm with VHADM that the descriptions for Low, Medium, & High are what we want to auto-populate in the fieldset for editors. Likely there's no change.

**VAMC System Operating Status Content Type**

- Inline Entity Form - can currently edit Operating Status Fieldset for VAMC Facility, but is inconsistent with editorial experience on Node Edit for VAMC Facility
- If COVID status is part of Operating status in the editor's mental models, then it should be here
- Alternative is cut the ability to edit VAMC Facility operating status here and build Bulk editing option instead
- Needs conversation with Product (Josh & Dave C)

**VAMC Facility Content Type**
- This is the place where the changes are most obvious - Figma is pretty clear

** Front End**
- Should probably build that ticket so they can be considered together

** Timing **
- This will be unmergeable until Change Management is ready

**Comment by swirtSJW** [comment]
I have scoped the ACs on this ticket to cover just the facility node content type.  If it is determined later that we will also alter the inline entity forms on the locations page then it should be a separate ticket.

**Comment by omahane** [comment]
@JQuaggles Can you help us address the implications for the System Operating Status edit pages?

**Comment by JayDarnell** [comment]
Adding myself so I can look at this while @omahane figures out his weird 502 bad gateway error

**Comment by BlakeOrgan** [comment]
I would also like to point out that since the Facilities team is making this update, any associated KB articles will also need to be updated to reflect this new way of doing things. It doesn't look like that is part of this ticket's AC's, but I'm also not finding an associated ticket where that work would be done.

**Comment by JayDarnell** [comment]
@BlakeOrgan @Dottisea I created an issue 12360 above

**Comment by omahane** [comment]
@BlakeOrgan In talking about the necessary front-end ticket to accompany this work, I realized that we may need to change the design.


https://user-images.githubusercontent.com/766573/217942817-33fb719d-d842-4457-9ba7-91eb70ee16d8.mov

We have 2 distinct types of content for the status:
- Status name
- Status description

The Status name is standardized, and gets a style distinct from the description on the front-end.
The Status description is now customizable, so it might include the boilerplate language from the term description or it may not.

<img width="624" alt="Screen Shot 2023-02-09 at 3 26 19 PM" src="https://user-images.githubusercontent.com/766573/217948200-4fb2b5b5-b826-48db-81a2-f6524a923ea5.png">

Therefore, I'm recommending that the WYSIWYG not include the Covid status name as a part of the content that is populated by choosing one of the statuses. Instead, only the description from the term is populated.

![Screen Shot 2023-02-09 at 3 58 28 PM](https://user-images.githubusercontent.com/766573/217949454-a57c0bcb-2c5b-49a8-a00c-ab3f8742d9dd.png)

On node:view, however, the content would show as it will appear on the front-end.
![Screen Shot 2023-02-09 at 4 05 30 PM](https://user-images.githubusercontent.com/766573/217950486-e6a2bfeb-3ecf-4727-bbfa-6efe251e46af.png)

**Comment by BlakeOrgan** [comment]
@omahane I updated [the Figma design](https://www.figma.com/file/IYpeP2ZAmBTT8jqhdtJklu/Covid-%2F-Facility-Status?node-id=236%3A32267&t=licZQFZEwGyeQ2Io-1) to remove the covid status name from the text input, however the default text that is being put in that text box is coming from a vocabulary so it will need to be updated [here](https://prod.cms.va.gov/admin/structure/taxonomy/manage/facility_supplemental_status/overview) if it hasn't already to reflect the new default text that gets pulled in based on the selected covid level. @swirtSJW Can correct me if I'm misspeaking here.

@davidmpickett also made a comment on Dec 23 that might be relevant to this. It might be worth double checking to see if the info that they want to auto-populate is still accurate.
> Facility Supplemental Status Taxonomy Terms
No code changes needed here
PM to confirm with VHADM that the current descriptions for Low, Medium, & High are what we want to auto-populate in the fieldset for editors. Likely there's no change. This is not a blocker for the dev work, just want to make sure we're 100% clear on what the default text should be for the 3 levels.

**Comment by omahane** [comment]
Thanks, @BlakeOrgan. I appreciate your flexibility. Regarding the text, I'll confirm what needs to be live when we roll this out with @davidmpickett  (CC: @Dottisea )
