### ISSUE TITLE
DSN Propose a wireframe graphic for what a VBA dashboard might look like

### ISSUE THREAD

**Issue by dsinla** [department-of-veterans-affairs/va.gov-cms#10701]
Targeting Q1 for design (Dev can build a VC duplicate dashboard to get started - but no design input )

Start with existing VC research/feedback <-provided by DS
Incorporate findings from #10504 where Jay has been modeling content 

Reference: https://prod.cms.va.gov/section/vha/vet-centers/lincoln-vet-center

@omahane Get Figma access

**Comment by davidmpickett** [comment]
Closing as duplicate of https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9954
