### ISSUE TITLE
Add h1 title block to a more logical position in the the content proofing experience

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#1072]
## User Story or Problem Statement

As a user reviewing content, i would like to see the h1 for my page in a more logical place, instead of the header. 

## Acceptance Criteria
* When looking at a node view in Drupal, the h1 appears above the intro text. See [prototype](https://xd.adobe.com/view/9db27da0-3d39-4f8c-4a0f-7a67ae527e83-eb83/screen/a50ca7e8-bcf6-468f-a8af-eb67b865389c/Assign)

## Implementation steps
* Add a block that's only visible on /node/* URLs, above the "main content"

**Comment by beeyayjay** [comment]
@kevwalsh what do you think of this for title display on all pages?
![Screen Shot 2020-06-25 at 12.55.04 PM.png](https://images.zenhubusercontent.com/5d7908d1fb288f0001ceb853/572dea2c-89d9-4498-8236-8d039bf68eba)
