### ISSUE TITLE
PM Investigate who should be able to publish and archive CAPs

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#10731]
## Describe the defect
Currently Vet Center Cap editors  have roles of "Content creator - Vet Center" and "Content Editor" do **not** have permission to either publish CAPs or archive them.  We need to first understand the desired business process to see if those permissions for either role need to be adjusted..  If they do, then we need to adjust them.

Workflow for publishing content is here https://prod.cms.va.gov/help/vet-centers/what-is-the-process-for-publishing-my-vet-centers-pages

Workflow specific to CAPs is here https://prod.cms.va.gov/help/vet-centers/how-to-add-change-or-remove-a-community-access-point

## Questions?
1. Should a user with the role of "Content Editor" be able to **publish** VC CAP's?
2. Should a user with the role of "Content Editor" be able to **archive** VC CAP's?
3. Should a user with the role of "Content creator - Vet Center" be able to **publish** VC CAP's?
2. Should a user with the role of "Content creator - Vet Center" be able to **archive** VC CAP's?
3. Should a user with the role of "Content publisher" be able to **publish** VC CAP's?
2. Should a user with the role of "Content publisher" be able to **archive** VC CAP's?

## AC / Expected behavior
- [x] Make AC's match the answers to the ^^ questions.  Either adjusting or validating the perms match the quesitons.
- [x] Make any adjustments to  https://prod.cms.va.gov/help/vet-centers/what-is-the-process-for-publishing-my-vet-centers-pages
- [x] Make any adjustments to  https://prod.cms.va.gov/help/vet-centers/how-to-add-change-or-remove-a-community-access-point

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by stefaniefgray** [comment]
Per related email thread with Dave Conlon, Tiffany Lever, Michelle Middaugh, Randi Hecht et. al:

**1. Should a user with the role of "Content Editor" be able to publish VC CAP's?**
No. They should not be able to publish anything.

**2. Should a user with the role of "Content Editor" be able to archive VC CAP's?**
No. They will need to contact the VA Drupal CMS Helpdesk for assistance.

**3. Should a user with the role of "Content creator - Vet Center" be able to publish VC CAP's?**
No. This permission is based on whether someone is a Content Editor or Content Publisher.

**4. Should a user with the role of "Content creator - Vet Center" be able to archive VC CAP's?**
No. This permission is based on whether someone is a Content Editor or Content Publisher.

**5. Should a user with the role of "Content publisher" be able to publish VC CAP's?**
Yes. Permissions have been updated on https://prod.cms.va.gov/ for users linked to published Vet Centers, and Content Publishers can now publish CAPs without needing outside approval.

**6. Should a user with the role of "Content publisher" be able to archive VC CAP's?**
Yes. Permissions have been updated on https://prod.cms.va.gov/ for users linked to published Vet Centers, and Content Publishers can now archive CAPs without needing outside approval.

See related thread: https://dsva.slack.com/archives/C01K37HRUAH/p1663271792192489

**Comment by stefaniefgray** [comment]
- **Updated:** https://prod.cms.va.gov/help/vet-centers/what-is-the-process-for-publishing-my-vet-centers-pages**
Added section about archiving content and how the "Draft" content moderation state works

- **Updated:** https://prod.cms.va.gov/help/vet-centers/how-to-add-change-or-remove-a-community-access-point
Removed information about deleting CAP pages, which is not possible for Vet Center users, and added how-to steps on archiving CAP pages

@swirtSJW Please let me know if this looks good and if this ticket can be marked as resolved. Thanks!
