### ISSUE TITLE
Run some checks on VA forms CSV file after downloading

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-cms#10735]
***Convert to spike? – discussion in comments suggests engineer investigation is needed***

## Description

The Forms DB exports nightly to a CSV that we use to import into Drupal. This CSV _could_ be corrupted or empty and we should validate that prior to attempting to import. 

As a Find-a-form stakeholder or maintainer, I want the Drupal migration to run sanity checks on the nightly Forms DB CSV so that we are more likely to catch upstream issues with CSV preparation and transfer.

Specific ideas:
- 200 response
- Ensure it's non-zero-length
- Check for valid CSV formatting/shape (not an HTML page)
  - https://www.php.net/manual/en/function.fgetcsv.php
  - Ensure the number of columns in the first (header) row is correct

### Background

On 9/15/22 we were notified that three new forms added by Forms Managers were not appearing on VAgov. On investigation, we discovered that an infrastructure change that redirected http to https had broken the upload mechanism on the WebOps side. This went undetected for several weeks.

## Acceptance Criteria
- [ ] Find CSV example to count number of header columns and use/modify for testing
- [ ] Run checks after file move, BUT **before** the migration
  - [ ] Ensure CSV is non-zero length
  - [ ] Ensure file is valid CSV
- [ ] CSV that doesn't conform to expectations
  - [ ] Fails the nightly migration job
  - [ ] Script writes brief text "Find-a-form: CSV validation failed; [dynamically populate reason]" to `stderr` and returns a non-zero exit code that will be notified in existing Slack notification with a link to the Jenkins job
- [ ] Request testing support from CMS-Platform team – if significant effort, consider writing new ticket

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by dsasser** [comment]
> Specific ideas:
200 response
Ensure it's non-zero-length
Check for valid CSV formatting/shape (not an HTML page)
Can we check for an expected date? (Wes)
?

Creating a CSV validator is possible, and can be achieved in many ways including:

1) An Event subscriber that fires immediately after the forms migration completes.
2) A regular scheduled task that fires immediately after the forms migration completes.
3) A Drush command that is triggered manually, or by scheduled task
4) Some combination of the above

Getting something together that can perform *some* validation is relatively easy and straightforward. However, the the job gets expensive to run, computationally, as we add more layers of validation.

So with that, I would recommend the following:
Implement 1). Keep the validation as lightweight as possible (ie: no row-level data parsing):
- Ensure non-zero length
- Ensure file is valid CSV

Some things to consider: what do we the CSV is *not* valid? Who is notified, and in what manner? What gets logged, and to where?

**Comment by ndouglas** [comment]
If the job fails, Slack gets notified with a link to the Jenkins job anyway, so IMHO you don't need to worry about that.  If you yeet some text to `stderr` and return a non-zero exit code that should be sufficient.  

Personally I agree that non-zero and valid CSV is sufficient.

**Comment by swirtSJW** [comment]
> An Event subscriber that fires immediately after the forms migration completes.
A regular scheduled task that fires immediately after the forms migration completes.

For the nature of this ticket, many of the proposed checks should happen after file move, BUT before the migration.   Checking after the migration is run is closing barn after horse has run all the way to Vegas.

**Comment by wesrowe** [comment]
@jilladams, we're kicking this back for refinement by team. @dsasser @chri5tia @swirtSJW @ndouglas to discuss ACs, plan.

**Comment by chri5tia** [comment]
The test should be added between lines 17 and 18 here in the `tasks-periodic.yml`:
https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/tasks-periodic.yml#L17-L18

The script or script call, etc., can be added further down (like at line 97, between `daily/migrate_copy` and `daily/migrate/va_forms`.

Could write a custom drush command that gets referenced, a bash script or a php script, etc.

Thanks @swirtSJW !

**Comment by jilladams** [comment]
@chri5tia this is the one ticket in current sprint that will need an update re: whether it will make it by Tuesday EOD or need more time.

**Comment by chri5tia** [comment]
@jilladams Unfortunately it is looking like I will need more time, with a goal of finishing it this week still. Let me know if you want to discuss.

**Comment by jilladams** [comment]
@chri5tia ok - can you add some notes re: where things stand by end of sprint? That'll help with reporting.

**Comment by chri5tia** [comment]
Bytes

- [ ] Add a task here, between lines 17 & 18: https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/tasks-periodic.yml#L17-L18 and further here:

```
  va/background/daily/migrate_copy/va_forms_csv_source:
    desc: This is because we cannot access the server on the SOCKS proxy right now.
    cmds:
      - |
        cd docroot/sites/default/files/migrate_source
        curl https://vaww.webdevi.va.gov/vaforms/VAForms_DataExtract/VAForms_FormsData.txt -L --output 
```

CSV check operation goes here.

```
va_forms_data.csv
  va/background/daily/migrate/va_forms:
    desc: Migrate va forms.
    cmds:
      - drush $DRUSH_ALIAS migrate:reset-status va_node_form
      - drush $DRUSH_ALIAS migrate:import va_node_form
 ```

- [ ] Create a custom drush command(s) in the `va_gov_migrate` custom module (`drush.services.yml`, `va_gov_migrate/src/Commands/Commands.php`, etc.) for jenkins to use. Drush commands should use php to acomplish these checks:
- - [ ] 200 response
- - [ ] Ensure it's non-zero-length
- - [ ] Check for valid CSV formatting/shape (not an HTML page): 
- - - [ ] https://www.php.net/manual/en/function.fgetcsv.php
- - - [ ] Ensure the number of columns in the first (header) row is correct

**Comment by jilladams** [comment]
Per [conversation with Dave](https://dsva.slack.com/archives/C52CL1PKQ/p1676317532081709?thread_ts=1676317266.330149&cid=C52CL1PKQ), rather than hold PR feedback for Christia to address on return from PTO, in the spirit of sprint boundaries, we'd like to reassign and ask for Daniel or Steve's help to finish the changes. 

Daniel's out sick this morning / might be all day, so: if Daniel comes back and is able to take a look yay. And if not, Steve has agreed to help knock out changes. Apologies for the unexpected turn here, and thanks for the support on this.

**Comment by dsasser** [comment]
> Per [conversation with Dave](https://dsva.slack.com/archives/C52CL1PKQ/p1676317532081709?thread_ts=1676317266.330149&cid=C52CL1PKQ), rather than hold PR feedback for Christia to address on return from PTO, in the spirit of sprint boundaries, we'd like to reassign and ask for Daniel or Steve's help to finish the changes.

I'm happy to take this on today/tomorrow.

**Comment by swirtSJW** [comment]
I created a followup test that should be added at some point ^^
