### ISSUE TITLE
CMS: Account blocked from selecting site section on VAMC Detail Pages unless cache is cleared

### ISSUE THREAD

**Issue by stefaniefgray** [department-of-veterans-affairs/va.gov-cms#10739]
## Describe the defect
As a VA Drupal CMS Helpdesk admin, I am often editing and updating VAMC Detail Pages -- such as when broken links have been added to the site.

However, every couple of days or so, I am blocked from being able to edit rich text fields or save changes to VAMC Detail Pages because the “Related office or health care system” field is missing, as shown in the screenshots attached below.

When I try to fill in this field, the dropdown is completely grayed out, and I cannot proceed. This happens across multiple sections when attempting to edit existing VAMC Detail Pages, until I flush the site cache.

Flushing the site cache allows me to edit VAMC Detail Pages once more. 

**Slack thread:** https://dsva.slack.com/archives/CT4GZBM8F/p1662054884604009

## To Reproduce
1. Log into https://prod.cms.va.gov/ as stefanie.gray
2. Go through your usual workday until you suddenly and randomly cannot edit a VAMC Detail Page or any rich text fields contained within it, due to the lack of a site section shown in the above screenshots.
3. Observe the Datadog error message displayed in #cms-notifications on the DSVA Slack
4. Flush the site cache in order to be able to edit the VAMC Detail Page.

**Datadog error message displayed in #cms-notifications whenever this happens:** https://dsva.slack.com/archives/CJT90C0UT/p1663263300628259

## AC / Expected behavior
- [ ] I should be able to edit VAMC Detail Pages without running into this issue.

## Screenshots
**Grayed out 'section' field on VAMC Detail Page when this issue occurs:**

![image](https://user-images.githubusercontent.com/9059428/190473645-c403c7ff-a06b-481b-85aa-2cc8d1b63e62.png)

**Drupal error message:**
![image](https://user-images.githubusercontent.com/9059428/190473758-c32caa3e-755e-4c9b-8ffe-cfdfcf17d772.png)

**Screenshot of Datadog error message displayed in #cms-notifications when this happens:** 
![Screen Shot 2022-09-15 at 11 45 01 AM](https://user-images.githubusercontent.com/9059428/190474317-ebf6b42f-36bc-4545-9546-f502404a1264.png)

 ## Additional context
See the following Slack threads (also linked above):
- https://dsva.slack.com/archives/CT4GZBM8F/p1662054884604009
- https://dsva.slack.com/archives/CJT90C0UT/p1663263300628259

## Desktop (please complete the following information if relevant, or delete)
 - OS: MacOS Big Sur 11.6.8
 - Browser: Chrome
 - Version: 104

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Defect")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS workstream (orange) (not needed for bug tickets)
- [ ] CMS-supported product (black)

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by omahane** [comment]
@stefaniefgray Can you note the last time this has happened? Or, if you can't recall that, the next time this happens?

**Comment by stefaniefgray** [comment]
@christianmburk The crazy thing is that the last time it happened was when we discussed it directly last week! You were there. Hasn't happened since then. 😵‍💫

**Comment by dsinla** [comment]
@stefaniefgray Can you pull a list of accounts in Drupal who have access to both a VAMC and Vet Center sections? 
Note: To what extent will this risk increase when we add VBA editors/sections?
Related to the 'winnower' which reduces pages that are exposed to an editor - the items that can get winnowed get cached for that user, the problem is it doesn't cache the Vet Center list and VAMC list separately  - whichever one gets cached first stays.

**Comment by omahane** [comment]
@dsinla @swirtSJW The issue that I've seen when it's been replicated is not that one winnowed list is cached. It's that no values show at all from either content type, only the content type names themselves. I am not sure the cause of it, but it's not a winnowing issue. 
![va-gov-cms ddev site_admin_structure_types_manage_health_care_region_detail_page_fields_node health_care_region_detail_page field_office](https://user-images.githubusercontent.com/766573/196746886-933c29d3-f7c9-4bdd-8f0b-e9aa7480d368.png)

I was thinking that the issue has to do with the UserPermsService:
`/docroot/modules/custom/va_gov_user/src/Service/UserPermsService.php`

![Screen Shot 2022-10-19 at 11 17 07 AM](https://user-images.githubusercontent.com/766573/196750814-e98c261d-e561-433a-837c-0707189d8f1d.png)

**Comment by omahane** [comment]
@stefaniefgray Have you had this happen again?

**Comment by stefaniefgray** [comment]
@omahane Apologies for delayed response; this has only happened once throughout the past month, though it was during a training screenshare that I was presenting so I did not have a change to log the occurrence

**Comment by dawnpruitt** [comment]
@omahane have you had any progress in determining the root cause? Do you need @swirtSJW's eyes too? Thanks!
