### ISSUE TITLE
Inventory "content blocks" components (aka paragraphs) for content proofing

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#1074]
## Description

For benefits hubs content proofing, paragraphs are used extensively within three fields:
* Featured content (the blue block on the FE)
* Main content
* Related content

To design an improved content proofing experience, we'll need to understand the diversity of use of various paragraph types, and what they currently look like in the proofing experience. 

## Acceptance Criteria
* We have an inventory in Mural of all paragraph types (see [high level content model](https://whimsical.com/PyatLZVHkA8QPxzuAqUEe8)) against which to create a backlog of content proofing improvements at the paragraph level, including: 
  * nesting rules 
  * field labels 
  * optional vs required fields
  * other aspects of paragraphs that might fit into patterns for improvement. 
* screenshots of 
  * the form and 
  * the current content proofing experience (paragraph display), including enough diversity to consider design improvements. 
  * the front
* schema.org considerations (optional)

**Comment by kevwalsh** [comment]
Here's an example of the complexity of some of this content, and where proofing fits (middle column), in between the editing experience and the front end. 
![Hearing_Aid_Batteries___Prosthetic_Socks___Veterans_Affairs_and_Hearing_Aid_Batteries___Prosthetic_Socks___Veterans_Affairs_and_Edit_Benefits_detail_page_Order_hearing_aid_batteries_and_prosthetic_socks_from_VA___VA_gov_CMS_and_Slack_____An](https://user-images.githubusercontent.com/643678/75391461-1bb07f80-58b8-11ea-8867-6b2902bd9c93.jpg)

**Comment by beeyayjay** [comment]
![dfc8c633-8e4e-4bc2-9ac7-1bfe4ff24a1e](https://user-images.githubusercontent.com/7660109/75582660-0fecc680-5a3a-11ea-9fdf-a03bfd554580.png)

**Comment by beeyayjay** [comment]
Updated tree view:
![c6ab9904-f614-49e0-8eff-e37d0fd110a4](https://user-images.githubusercontent.com/7660109/75797331-049fe080-5d43-11ea-8c47-cfe31aa383fd.png)

Structures:
![VA gov Paragraphs](https://user-images.githubusercontent.com/7660109/75797420-24cf9f80-5d43-11ea-8dea-bdc0bf2ddaf7.png)
