### ISSUE TITLE
New Facility: North Oklahoma City VA Clinic

### ISSUE THREAD

**Issue by stefaniefgray** [department-of-veterans-affairs/va.gov-cms#10749]
## Background

*What triggered this runbook?*
Brandy Sims, VISN 19
https://va-gov.atlassian.net/browse/VAHELP-4821

*Please attach Facility Locator link and https://prod.cms.va.gov/ link to this ticket*
https://www.va.gov/find-locations/facility/vha_635GL
https://prod.cms.va.gov/oklahoma-city-health-care/locations/north-oklahoma-city-va-clinic

*Please also include link to Jira help desk ticket, if applicable*
See above

### VAMC
Please refer to the Knowledge Base article titled "How do I add a facility to my health care system?" for more information: https://prod.cms.va.gov/help/vamc/about-locations-content-for-vamcs/how-do-i-add-a-facility-to-my-health-care-system

#### CMS help desk steps
- [x] 1. Become aware that the new facility is now on the Facility API (typically, via a Flag, but this may come in as a helpdesk ticket).
- [x] 2. If the editor has followed the steps from the above Knowledge Base article and included which section and VAMC the facility belongs to (i.e. VA Pittsburgh), great! **Proceed to step 3.** If not, please check with the editor or VHA digital media regarding what section and VAMC it belongs to.
- [x] 3. Updates the Section (default is "VAMC facilities", but it should be a VAMC system in a VISN) and VAMC system field accordingly.
- [x] 4. Communicate with editor (cc VHA Digital Media) to give them go-ahead to complete the content, with this [KB article](https://prod.cms.va.gov/help/vamc/about-locations-content-for-vamcs/how-do-i-add-a-facility-to-my-health-care-system).
- [x] 5. When editor has prepared content and let help desk know, reassign this issue to appropriate CMS engineer on Product Support team, for bulk publishing.

    #### Sample notification email:
    Hello! You should now be able to edit the currently un-published draft page for this facility, located at [LINK TO NEW FACILITY DRAFT PAGE ON PROD]

    Important: Please make sure that all relevant steps listed within the “How do I add a facility to my health care system?” Knowledge Base article have been completed: https://prod.cms.va.gov/help/vamc/about-locations-content-for-vamcs/how-do-i-add-a-facility-to-my-health-care-system
    
    Once finished, please save this page as a “Draft”, and do not save it as “Published.”

    Please let us know once your draft is complete, so that we can wrap up the technical process from our end and ensure that the new facility publishes to the live site as intended. Thanks!

#### CMS engineer
- [x] 6. CMS engineer bulk publishes nodes and facility.
- [x] 7. CMS engineer edit facility node and remove `New facility` flag and save node.
- [x] 8. Let help desk know this has been done.

#### CMS Help desk
- [x] 9. HD notifies editor and any other stakeholders.

## CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [x] `⭐️ User support`

**Comment by stefaniefgray** [comment]
@JayDarnell @omahane Hi guys! The current new facility runbook says to tag the "appropriate engineer" but will definitely need to be updated to help helpdeskers tag the right people/channel/etc

cc @EWashb given our discussion yesterday -- this is Step 5 of the process listed above, the editor said that her draft and the draft health services attached to this facility are good to go ([VAHELP-4821](https://va-gov.atlassian.net/browse/VAHELP-4821))

**Comment by EWashb** [comment]
@stefaniefgray let's def look at the runbooks in our sync to account for the scenarios when editors notify and when they don't notify us. Maybe we can knock out the "when they do notify us" scenario pretty easily. @JayDarnell was the point person on updating the runbooks, but now the three of us may need to sit down again to fine-tune the process.

**Comment by stefaniefgray** [comment]
@JayDarnell @omahane Sorry to bug you guys late in the day on a Friday! VA Oklahoma City just pinged us and asked once more for this location to be published

**Comment by stefaniefgray** [comment]
Tagging @TroyA6 for awareness in case there is motion on this ticket while I'm out of office

Troy -- once this facility homepage is published, we'll need to update the editors within the following tickets:
- https://va-gov.atlassian.net/browse/VAHELP-4821 (Brandy S. - VISN 19)
- https://va-gov.atlassian.net/browse/VAHELP-4861 (Tyler M. - VA Oklahoma City)

**Comment by omahane** [comment]
@TroyA6 The facility and health service nodes are now published.

**Comment by stefaniefgray** [comment]
Notified editors in Jira tickets linked above

Closing

**Comment by stefaniefgray** [comment]
Reopening because redirect needed
"New Facility" flag can be removed once redirect is completed/closed 

Redirect ticket: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10749

**Comment by omahane** [comment]
@stefaniefgray The CSV has been deployed and Facility Locator updated: 
https://www.va.gov/find-locations/?page=1&address=oklahoma%20city%2C%20ok&facilityType=health&serviceType&latitude=35.472989&longitude=-97.517054&radius=35&bounds%5B%5D=-98.267054&bounds%5B%5D=34.722989&bounds%5B%5D=-96.767054&bounds%5B%5D=36.222989&context=Oklahoma%20City%2C%20Oklahoma%2C%20United%20States

Please confirm.

**Comment by stefaniefgray** [comment]
Looks great! Closing
