### ISSUE TITLE
FE: Resolve massive amounts of blank lines in template

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#10754]
## Describe the defect
When looking at a page like this
https://www.va.gov/resources/how-to-download-and-open-a-vagov-pdf-form/

If I view the source, I see 
blank lines starting from  here (line 348)
![image](https://user-images.githubusercontent.com/5752113/191107023-56fa76c3-207e-4bf6-b13b-43a25191f31d.png)

to here (line 2474)
![image](https://user-images.githubusercontent.com/5752113/191107253-aec22c51-4185-4230-855e-e8b9f9c53ec0.png)

That is an indication something is up with the template and that may be having a performance impact on page download (2,000 carriage returns add up)

## AC / Expected behavior
- [ ] There should be no unnecessary line breaks in the banner section of the web pages.

## Additional context
Add any other context about the problem here. Reach out to the Product Managers to determine if it should be escalated as critical (prevents users from accomplishing their work with no known workaround and needs to be addressed within 2 business days).

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Defect")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS workstream (orange) (not needed for bug tickets)
- [ ] CMS-supported product (black)

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by swirtSJW** [comment]
This seems to me like a similar problem we saw on resource materials where the query was not properly filtered to the content type so it was returning a bunch of results that ended up just generating empty lines.

**Comment by jilladams** [comment]
Moved to "ready for indiv estimate" in PW Backlog Refinement board - I don't think this needs product input, and a front-end person could estimate points / add any relevant notes.

**Comment by ryguyk** [comment]
I believe this problem is appearing on _every_ page generated from Drupal, and it's due to looping through all nodes of type `full_width_banner_alert` in [a template included in header.html](https://github.com/department-of-veterans-affairs/content-build/blob/main/src/site/components/fullwidth_banner_alerts.drupal.liquid). There are over 300 nodes of this type, and, the loop through all of them generates for each one either:
- The banner markup, if the banner is assigned to the page in questionor generates one or more blank lines. We need to clean up the logic in the linked file so that it doesn't generate blank lines when no banners match the page in question.

**Comment by swirtSJW** [comment]
Might be related... or at least figures into the mix.  full_width_banner_alert do not have a moderation state.  They either have a status=1 or status=0   It may be possible that the grapql for them does not adequately account for this difference.

**Comment by swirtSJW** [comment]
disreguard my comment about status.  It is covered in the query 
![image](https://user-images.githubusercontent.com/5752113/191369078-50c80a5f-26af-4f91-a30f-3f0bc5300fa3.png)


https://github.com/department-of-veterans-affairs/content-build/blob/f7bafff44f67aea4cffa94ee343d31bbd8784231/src/site/stages/build/drupal/graphql/bannerAlerts.graphql.js
