### ISSUE TITLE
Discovery: why are some CMS pages missing from internal search (search.gov)

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#10756]
**Blocked: get robots.txt fixed, maybe that will help this**

## Description

It was brought to our attention, that internal search is behaving badly for some pages in ways that, so far, can not be explained.
Related [slack thread](https://dsva.slack.com/archives/CDHBKAL9W/p1663273842399269)

Example: a FE search for 
`How to download and open a VA.gov PDF form` does not surface [the page that has that as a title](https://www.va.gov/resources/how-to-download-and-open-a-vagov-pdf-form/).  It shows up on page 5.

The page is confirmed to be in the sitemap 
![image](https://user-images.githubusercontent.com/5752113/191124073-c15a22df-15a7-4464-855f-5ca4d43f3f34.png)

And it appears higher in the search results if you search for something less common, like the first sentence. `We encourage you to download PDFs to your computer or other device instead of opening them`

### Background and potential causes

Search.gov documentation around indexing: https://search.gov/indexing/indexing-with-searchgov.html

So the question becomes why does this page not show up in search as expected?  Some possible thoughts:
* the page title is full of stop words "How to **download** and **open** a VA.gov **PDF** **form**"  Bolded are the non stop words.
* The section is not allowed in robots.txt addressed here https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10755
* There may be some directive within the search.gov admin. DaveC is the admin & can provide credentials. 
* NOTE: There are two "competing" `sitemap.xml` files, see these slack threads:
  * in [cms-support](https://dsva.slack.com/archives/CDHBKAL9W/p1663273842399269)
  * in [vfs-support](https://dsva.slack.com/archives/CBU0KDSB1/p1663274894958349)

## Acceptance Criteria
- [ ] Understand why the page https://www.va.gov/resources/how-to-download-and-open-a-vagov-pdf-form/  is not showing up in va.gov search when searched for its name.
- [ ] Identify all other pages or page types that are impacted by the same phenomenon.
- [ ] Create ticket(s) for fixing the issue as appropriate

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by jilladams** [comment]
An additional question: What is the process for adding things to the autocomplete list that shows up when you type search strings on [VA.gov](http://va.gov/)? Or: how does autocomplete work? (Maybe this should be its own ticket?) cc @wesrowe 
https://dsva.slack.com/archives/C52CL1PKQ/p1663711918184369

**Comment by jilladams** [comment]
https://search.gov/indexing/sitemaps-to-search-sites.html
https://search.gov/indexing/indexing-workflow.html
https://search.gov/indexing/sitemaps.html

Search.gov API docs require sign in: https://search.gov/developer/. DaveC is admin and can add users / provide credentials.

Typeahead API: https://open.gsa.gov/api/searchgov-suggestions/

**Comment by chri5tia** [comment]
I took a look at the search.gov settings via admin account and there isn't a simple "Please reindex the site" option. Reindexing interval is controlled by the site map: 

I also see that we need to email them to request re-indexing: search@gsa.gov
<img width="321" alt="Screen Shot 2022-10-12 at 9 59 19 AM" src="https://user-images.githubusercontent.com/22764938/195403943-e86da48f-af98-4282-826a-67720f7cd1fa.png">

Other resources:
https://search.gov/indexing/what-searchgov-indexes.html

Workflow: https://search.gov/indexing/sitemaps-to-search-sites.html

Help manual: https://search.gov/admin-center/

**Comment by chri5tia** [comment]
- [ ] Find out how our site map is generated, if it needs to be updated, and if it includes the last modified date (`<lastmod>`).

**Comment by chri5tia** [comment]
ranking info https://search.gov/indexing/ranking-factors.html

**Comment by chri5tia** [comment]
@swirtSJW @jilladams 
Would you like me to go ahead and email them to have the site re-indexed [per my above comment](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10756#issuecomment-1276483738)?

**Comment by jilladams** [comment]
Is it worth requesting reindex before we've solved the open Sitemap question?

**Comment by chri5tia** [comment]
@jilladams Can you pint to that question so I make sure I know specifically?

**Comment by jilladams** [comment]
Ah yes - I meant your open todo re: 
 Find out how our site map is generated, if it needs to be updated, and if it includes the last modified date (<lastmod>).

Will that impact what gets reindexed if we go ahead and reindex now?

**Comment by chri5tia** [comment]
The paths I added were on the site map, but I need to look at that further. Good call.

**Comment by chri5tia** [comment]
The site map is here:
https://www.va.gov/sitemap.xml

It does appear to keep track of when a page was last built:

```
...snip...
<url>
<loc>https://www.va.gov/beaumont-vet-center/</loc>
<lastmod>2022-10-13</lastmod>
</url>
<url>
<loc>https://www.va.gov/biloxi-vet-center/</loc>
<lastmod>2022-10-13</lastmod>
...snip...
```

This seems to be based on the content build, which is at least daily, so I'm not sure anything needs to be done here. Seems like the search engine, if it works the way they say it will, would reindex it every day.

From Steve's screenshot, the page in question is already in the sitemap:

```
<url>
<loc>https://www.va.gov/resources/how-to-download-and-open-a-vagov-pdf-form/</loc>
<lastmod>2022-10-13</lastmod>
</url>
```

I am not sure how to tell when the last time the site was indexed, but this page still doesn't show up within the first several pages of search results.


I just added `/resources/` and that comes up now, so I can assume it's been indexed recently:

<img width="341" alt="Screen Shot 2022-10-13 at 12 14 31 PM" src="https://user-images.githubusercontent.com/22764938/195689254-c9034255-1fc3-4994-ad16-60c7372d0f66.png">

More work is needed to find out why this page isn't coming up.

**Comment by chri5tia** [comment]
This is annoying:
<img width="930" alt="Screen Shot 2022-10-13 at 12 16 37 PM" src="https://user-images.githubusercontent.com/22764938/195689782-9bd844f3-cc30-4a4e-bd35-d881a7e452ed.png">

**Comment by chri5tia** [comment]
It is the first result if you specify to  look within resources and support:

<img width="835" alt="Screen Shot 2022-10-13 at 12 20 51 PM" src="https://user-images.githubusercontent.com/22764938/195690395-598bbc70-a993-4c06-9e2d-8d300f448bb1.png">

So that rules out a couple things but makes this even weirder.

**Comment by chri5tia** [comment]
Here it is on page 3:

<img width="842" alt="Screen Shot 2022-10-13 at 12 22 39 PM" src="https://user-images.githubusercontent.com/22764938/195690730-9ed5c568-a7cb-430f-8458-d6bf1f0c6fe1.png">

**Comment by chri5tia** [comment]
Conclusion so far:

* the site map doesn't need any work related to this, that I can tell
* we probably don't need to submit for reindexing, it seems to be keeping it current
* we need to understand more how the results are ranked and how to prioritize title matches

**Comment by wesrowe** [comment]
@chri5tia, can you tell if R&S search is also using search.gov?

**Comment by jilladams** [comment]
Based on convo with @FranECross today, I tested this again to see if it repros. Steps: 
* load va.gov
* Search for "How to download and open a VA.gov PDF form"
* Land on https://www.va.gov/search/?page=1&query=How+to+download+and+open+a+VA.gov+PDF+form&t=true
* The page in question is the 2nd search result: 
![Screenshot 2023-12-04 at 4 06 49 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/85581471/a8249e73-5db6-4eb2-8a5c-e0cc7bfbb126)

If i just search "Download PDF", the page is the 5th search result: https://www.va.gov/search/?page=1&query=download+PDF&t=true

So officially this doesn't repro anymore. I suspect this might've been fixed by https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11637, where we changed robots.txt to allow by default.
