### ISSUE TITLE
Robots.txt: Add search.gov allows that match top level directories

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#10755]
## Description
[related slack discussion](https://dsva.slack.com/archives/CDHBKAL9W/p1663273842399269) (it's a long one)
search.gov reference https://search.gov/indexing/robotstxt.html

The current [robots.txt](https://www.va.gov/robots.txt) is trying to manipulate what pages search.gov has access to.  However it is not doing it correctly or completely.  It is blocking all and only allowing specific paths.
Originally this was probably done so that the 140 VAMC facilities could be kept out of internal site search until they were official.  Now there is only one remaining, Lovell... which will be removed soonish.  This history of robots.txt use especially around search.gov is murky at best.

**example of incorrect:**
`Allow: /communitycare`  only allows that one entry, does not allow its children.  It should be `Allow: /communitycare/`

Though some of those may be covering redirects or includes of some kind from the legacy sites.  So probably they should not all be fixed.  Might need an audit of them all.

**example of incomplete**
Does not include our top level paths
/burials-memorials/
/careers-employment/
/decision-reviews/
/disability/
/education/
/family-member-benefits/
/health-care/
/housing-assistance/
/initiatives/
/life-insurance/
/pension/
/records/
/resources/
/service-member-benefits/

## Acceptance Criteria
- [ ] all top level directories from the CMS are listed as allows in the search.gov section.
- [ ] validate that updates appear in prod
- [ ] ticketed next steps/recommendations
- [ ] re-index request sent to search.gov (ping Dave)
- [ ] process for re-indexing documented in github product folder for Search

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by swirtSJW** [comment]
Ultimately. we [probably need to back out of the pattern of block all, then allow specific.  That is generally an unmaintainable pattern.    But that could be for a follow-up issue.

**Comment by swirtSJW** [comment]
The list of the allows on this ticket is now complete.

**Comment by chri5tia** [comment]
> The current [robots.txt](https://www.va.gov/robots.txt) is trying to manipulate what pages search.gov has access to. However it is not doing it correctly or completely. It is blocking all and only allowing specific paths.

I am not seeing where this occurs. Everything is allowed except what is listed.

```
User-agent: *
# CSS, JS, Images
Allow: /core/*.css$
Allow: /core/*.css?
Allow: /core/*.js$
Allow: /core/*.js?
Allow: /core/*.gif
Allow: /core/*.jpg
Allow: /core/*.jpeg
Allow: /core/*.png
Allow: /core/*.svg
Allow: /profiles/*.css$
Allow: /profiles/*.css?
Allow: /profiles/*.js$
Allow: /profiles/*.js?
Allow: /profiles/*.gif
Allow: /profiles/*.jpg
Allow: /profiles/*.jpeg
Allow: /profiles/*.png
Allow: /profiles/*.svg

# Directories
Disallow: /core/
Disallow: /profiles/
# Files
Disallow: /README.txt
Disallow: /web.config
# Paths (clean URLs)
Disallow: /admin/
Disallow: /comment/reply/
Disallow: /filter/tips
Disallow: /node/add/
Disallow: /search/
Disallow: /user/register
Disallow: /user/password
Disallow: /user/login
Disallow: /user/logout
# Paths (no clean URLs)
Disallow: /index.php/admin/
Disallow: /index.php/comment/reply/
Disallow: /index.php/filter/tips
Disallow: /index.php/node/add/
Disallow: /index.php/search/
Disallow: /index.php/user/password
Disallow: /index.php/user/register
Disallow: /index.php/user/login
Disallow: /index.php/user/logout
```

But ah, I see that there are two different files. Why is https://www.va.gov/robots.txt different than https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/docroot/robots.txt? The later looks better in my opinion, more correct and more maintainable.

**Comment by chri5tia** [comment]
It really would make sense to cut a new ticket to discuss the strategy of disallowing everything and then allowing all the public paths, instead of simply disallowing certain paths, which is the usual strategy. I'd like to know why we are doing it this way:

```
Disallow: /
Allow: /about_va
Allow: /accountability
Allow: /adr
...snip...
```

**Comment by chri5tia** [comment]
It really would make sense to cut a new ticket to discuss the current strategy of disallowing everything from usasearch and allowing only certain public paths, with perspective to how things are *now* and what we may want to do moving forward. And also, how to know which paths should only be the top level path and which should include all the sub-level pages.

User-agent: usasearch
Disallow: /
Allow: /about_va
Allow: /accountability
Allow: /adr
...snip...

**Comment by chri5tia** [comment]
https://github.com/department-of-veterans-affairs/content-build/pull/1314/files

**Comment by chri5tia** [comment]
PR is being reviewed by platform support.

**Comment by chri5tia** [comment]
PR was approved and merged.

**Comment by jilladams** [comment]
Reopened bc Christia noted it looks like despite merge, the old robots.txt is still in operation.

**Comment by wesrowe** [comment]
Is it still recommended that we investigate the whole disallow-allow approach? @chri5tia @jilladams

**Comment by jilladams** [comment]
That was originally a business decision rather than a technical one, and feels like a business decision to change it. The underlying Q being: are there strong reasons _not_ to allow new content to be indexed automagically once live on Prod?

**Comment by wesrowe** [comment]
Okay, this needs a consult from Dave C on whether to prioritize. It's not urgent so I'll add it to our sync agenda for when he's back in town.

**Comment by chri5tia** [comment]
I recommend running this by Dave C. It's so easy to miss ensuring that veterans are able to find the content they need and there isn't a good approach for tracking the creating of new top level URLs. This seems like tech debt that we could get rid of without any heavy lifting.

**Comment by wesrowe** [comment]
Thanks @chri5tia - It's on our agenda for Dave when he's back in town.

**Comment by jilladams** [comment]
Next step per Dave: PW needs to close the loop with Sitewide Content team re: strategy. Dave noted we may need to talk to other Platform folks, not sure who.
