### ISSUE TITLE
Inline content guidance twig groundwork and setup

### ISSUE THREAD

**Issue by edmund-dunn** [department-of-veterans-affairs/va.gov-cms#10766]
## Description
Laying the groundwork for Inline Guidance. Adding theme suggestions for form elements which will allow us to work in the twig files for those elements.

## Acceptance Criteria

- [ ] locate areas where help text strings can be supplemented by twig and update the path for our inline guidance markup 

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [x] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by EWashb** [comment]
@dawnpruitt this was unplanned work for sprint 67, but critical to our iteration of inline guidance work. @edmund-dunn has already completed the first step of #10652, so this is the next step.

**Comment by EWashb** [comment]
@dawnpruitt actually this didn't come into sprint 67 as unplanned. I'm adding it to sprint 68
