### ISSUE TITLE
Search: document or update documentation about infrastructure

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#10768]
## Description
The Public Websites team are the owners of site search, so we need to ramp up on understanding. Two main items have emerged to have in mind as you review: 

1. Search uses third-party search.gov product. We should dig into our search.gov account and see how it's configured, how we tap into its API etc, in order to understand if the API has evolved / our implementation against the API needs a refresh. 

2. We know that when vets-api is experiencing latency, Search is affected. Per Dave, this is an artifact of a Platform stance that all VA.gov API implementations should route through vets-api. It would be helpful to document or update documentation about the API call / architecture used, to understand these dependencies and where there may be opportunity to optimize / remove unnecessary API calls.

## Access to search.gov account
Dave is an admin & can provide credentials

## Other technical info
Some initial digging @chri5tia did in the fall, with some implementation notes as a starting point: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10756#issuecomment-1276483738

## Acceptance Criteria
- [ ] Review documentation in https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/on-site-search & compare to implementation to confirm if documentation is accurate or behind build
- [ ] Update documentation as needed 
~~- [ ] Identify any opportunities to update architecture to remove reliance on vets-api~~ Non-starter bc Platform dictates that vets-api handles all outside api routing for VA.gov.
- [ ] Update [PW Product overview: Search section](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/public-websites#va-site-search-using-searchgov) with pointers to any new documentation
- [ ] File tickets and share with PM for any recommended follow up actions

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [X] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by jilladams** [comment]
Some initial digging @chri5tia did in the fall, with some implementation notes as a starting point: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10756#issuecomment-1276483738

**Comment by jilladams** [comment]
Josh is looking into some Search sentry errors under https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12625, which may end up with findings we can bring in here as well.

**Comment by randimays** [comment]
@jilladams @FranECross Noting that the [product outline for On Site Search](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/on-site-search/product-outline.md) is WIP; is it expected that this be complete/updated for this ticket?

Also, the [README](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/on-site-search#readme) for the product folder points to an Off Site Search outline that does not exist in the folder. Should one of these be created (as a future ticket - I wouldn't know where to begin here) as well?

**Comment by FranECross** [comment]
@randimays Thanks for your questions! I have a few comments/questions to Jill in order for me to understand the ask better...

@jilladams Regarding Randi's first question/comment, I don't believe an ask of her is to complete the Product Outline, but would it be accurate to say that she should review the parts of the outline that discuss or provide information on current behavior/architecture/code for Search so that the outline is up to date? 

@randimays @jilladams I'm not sure about the second question. If the README provides all necessary information, without an outline, would that suffice? If not, then I can create a ticket to address creation of an outline.

Thanks!

**Comment by jilladams** [comment]
1. The WIP was leftover from the previous team. I think it's fair to assume that any product brief is perpetually WIP, so i removed that. And I agree with Fran: no expectation that you complete that, and that yes: the guiding principle here is to get documented what we know, and make sure that anything else that is already documented is technically accurate / we get rid of old cruft that's no longer accurate.  
2. Offsite search: fixed the broken link.  We inherited this / I don't know much about it, and we haven't been asked to deal with it, so ignore for now.

**Comment by jilladams** [comment]
(I'm mainly concerned with making sure the Engineering info is accurate / captures what we know: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/on-site-search/engineering)

**Comment by randimays** [comment]
PR for updates: https://github.com/department-of-veterans-affairs/va.gov-team/pull/69907
