### ISSUE TITLE
Forms: Create Forms audit view to help determine which are sufficiently populated to publish

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#10776]
## Description
When forms are migrated into the CMS from the Forms DB, a draft node is created. We need to audit these nodes and work with Sitewide Content to develop governance for reviewing each node, determining if it has the necessary data required for a standalone Form detail page. 

First step, understand existing VA Form nodes, and their contents. 
Forms: https://prod.cms.va.gov/admin/content?title=&type=va_form&owner=All   (includes Draft & Published)

### Description 

**Follow the pattern of views under Facilities content, where each view has a tab**

Create a content audit view in the VA Forms area (https://prod.cms.va.gov/admin/content/va-forms) that: 
* displays each VA form
* can be filtered by moderation status
* shows "form name" column
* shows "When to use" column
* shows "Online tool" column
* shows "Issue date"
* shows "Revision date"

## Additional context
To put tabs under tabs may be funny, and Jay Darnell has notes on how to make it work. 

## Acceptance Criteria
- [ ] Content audit VA Form table exists with columns above

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [X] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by jilladams** [comment]
Marking blocked til we get the scope here updated from [10/4 Flagged Content meeting] notes (https://docs.google.com/document/d/1zEDbfR0CAHyCoHh_1uk3T2bwVmV4D8Yl3EARGWKM2-Y/edit#heading=h.oek99rkrbej) with Dave / Erika / Swirt.

**Comment by wesrowe** [comment]
10/4 meeting didn't impact this ticket; new tickets were written for flag views. Unblocking.

**Comment by wesrowe** [comment]
@dsasser, note that I just added two additional columns to the audit so that the audit view can assist with the PDF certificate expiration work

**Comment by jilladams** [comment]
This is great! https://prod.cms.va.gov/admin/content/va-forms/audit

@dsasser 2 questions / changes I'd like to request: 
* Can column order be modified easily? If so, can we do: 
  * Title
  * Form name
  * Moderation State
  * Issue date
  * Revision date
  * When to Use
  * Link to online tool
  * Changed
  * Section
* Can Moderation Issue date column be modified to make it click-sortable? (Revision date already is)

**Comment by jilladams** [comment]
Daniel clarified that column order in some cases is dictated by the [CMS Views Style guide](https://va-gov.atlassian.net/wiki/spaces/VAGOV/pages/1740472321/CMS+Views+Style+Guide). After reviewing that, here's state of affairs and row 4 is my proposed update. I'll ticket separately: 

![Screen Shot 2022-10-18 at 1 21 00 PM](https://user-images.githubusercontent.com/85581471/196536060-46a193c0-58ac-4c9c-baf5-1d3c58eb691f.png)
