### ISSUE TITLE
Featured Story Checkmarks Behave Differently than expected

### ISSUE THREAD

**Issue by TroyA6** [department-of-veterans-affairs/va.gov-cms#10771]
## To Reproduce
1. Go to 'Stories'
2. Click on a story to select/edit
3. Scroll down to 'Feature' select 1st and check the box
4. Edit a second story, repeat the Feature selection using the '2nd' option
5. Publish
6.

## AC / Expected behavior
If two stories are featured, then both should appear (in order) on the VAMC home page.

## Screenshots
Minneapolis Homepage 9/16/2022
![image](https://user-images.githubusercontent.com/108767736/191329281-cb19c583-5f2f-4cd5-9a24-e4241019f57f.png)

Houston VAMC Homepage 9/16/2022
![image](https://user-images.githubusercontent.com/108767736/191329074-601ec2d7-3b86-4db4-ad6c-91be5882490c.png)

Minneapolis Story/Edit 
![image](https://user-images.githubusercontent.com/108767736/191329474-3a0d421f-dd76-49e5-8fc1-a8497ab4e848.png)

 ## Additional context
NOTE: Minneapolis VAMC first reported this issue: In researching, we found that Houston showed two featured stories, and Minneapolis showed one.

Until some time between 9/16 and 9/20/22, Houston VAMC was displaying TWO featured stories on the homepage, but now also shows only one as well.

## Desktop (please complete the following information if relevant, or delete)
 - OS: Windows/IOS
 - Browser Chrome
 - Version 105.0.5195.127

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Defect")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS workstream (orange) (not needed for bug tickets)
- [ ] CMS-supported product (black)

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by stefaniefgray** [comment]
**VA Asheville currently has two stories listed on their homepage:**

![Screen Shot 2022-09-20 at 1 51 16 PM](https://user-images.githubusercontent.com/9059428/191352090-c411d368-0699-4694-86b7-3ae42daf37f7.png)

The story "A Photo is Worth a Thousand Words," published 9/15/2022 is marked off as such:

![Screen Shot 2022-09-20 at 1 54 48 PM](https://user-images.githubusercontent.com/9059428/191352177-e5e6c48f-3e31-4209-82b4-843aadabc036.png)

Whereas here's how the story "Five West team on track for Pathways to Excellence survey," published 9/15/2022 is marked:

![Screen Shot 2022-09-20 at 1 55 38 PM](https://user-images.githubusercontent.com/9059428/191352285-043cdf02-7053-45b2-90b3-37e433bdfb9b.png)

None of their other stories have the "Featured" checkmark though some have 1st or 2nd selected

**Comment by mmiddaugh** [comment]
Related or duplicate issue: VACMS System Featured stories are not limited in number #13687

**Comment by stefaniefgray** [comment]
Still an issue per https://va-gov.atlassian.net/browse/VAHELP-6140

**Comment by mmiddaugh** [comment]
Closing as a duplicate to [Feature function for Story content types only allows one Featured story #11221](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11221)
