### ISSUE TITLE
Label and route KB articles for product teams 

### ISSUE THREAD

**Issue by EWashb** [department-of-veterans-affairs/va.gov-cms#10802]
## Description

After completing the KB article audit, there were many articles found that needed to be edited for consistency and accuracy. Now that the fixes have been highlighted, we need to route these to the proper teams to make the updates. We also need to create a documented process for doing this going forward that includes Sitewide CMS, product teams, and the helpdesk working in unison. 

## Acceptance Criteria
- [x] Go through issues in the [KB article epic](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10157) and add appropriate team label
- [x] Notify product managers about the new items in their backlog
- [x] Document the KB process 

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [x] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by EWashb** [comment]
Notes from 9/21 refinement

- Laura has a template ready to go; does each article need to be updated to follow the template?
- Majority of articles had broken link or incorrect directions.
- Who reviews after Laura fixes KB articles? Stefanie said that she could be a fact checker
- Swirt said that KBs do not have a path set up and should

Potential Process:
- Should be thinking of capacity and how close people are to the thing
- Recommend that when Laura finds a problem, she flags the problem and sends the article to whoever the product owner is
- Facilities would fix or update, then send to Stefanie for final approval and QA that it actually works for our users.
- Laura: what if we have general content (alt text article)? There is no single article on how to upload images; would have to find several places to replace text on how to upload images. The CMS would be the owner. Update the article to link to ours? (Confirm with Laura)
- Is there duplication of information? If yes, find out if there is a legitimate reason, if not, determine if it makes sense to combine/consolidate topics.
- Erika and Laura to label by product and then reach out to the product owners
- Stefanie can look at any that have functionality questions or errors to confirm if there is a functionality issue
- Dave suggested that we are judicious to fix small things on the editors’ behalf when it would take more time to do a ticket than make the change.
- Stefanie has been working on a KB audit and suggested we fiind a mechanism to track on how to make changes across the board.

**Comment by laflannery** [comment]
- Edit issues in the epic are labelled with appropriate team label
- If label is `Sitewide CMS`, they have also been assigned to me to be updated
- Create issues have not yet been assigned - some requested are over a year old and we may want to reevaluate if these are still needed

**Process for updating these articles:**

1. Individual team makes requested updates. Sends to Sitewide CMS once complete
2. Sitewide CMS/I will update article to match standard template and formatting.  Will send to Helpdesk
3. Helpdesk team will review for accuracy and to ensure editors will understand.
4. Updated article will then get published

**Comment by EWashb** [comment]
Those seem like the highlights to me @laflannery. We might consider documenting this process somewhere in our internal docs or even within the Github documentation

**Comment by laflannery** [comment]
I updated the KB article request template.  I updated the process section at the bottom and I also updated the KB content writing guide I found in confluence (linked in the template) to include the guidelines from the article template I created.  I think with that we can hopefully direct people on how to request new articles as well as how to write them a bit better going forward.
