### ISSUE TITLE
Discovery for VBA Operating Status 

### ISSUE THREAD

**Issue by dsinla** [department-of-veterans-affairs/va.gov-cms#10808]
## Description
Determine if existing model for status applies for VBA - Initial discovery 
Tease out what would be the best presentation based on several alternatives.
Consider how Operating status and Supplemental status are to be used.

If possible get ahead of dependencies on LH, Facility Locator, etc

## Acceptance Criteria
- [ ] Testable_Outcome_X
- [ ] Testable_Outcome_Y
- [ ] Testable_Outcome_Z
- [ ] Requires design review

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by davidmpickett** [comment]
Good next step might be a short meeting with @dsinla @swirtSJW @davidconlon to draw out the scope

**Comment by davidmpickett** [comment]
@cindymerrill Tagging you as this is a example of where we could potentially collaborate to define a small research project. Might be mostly synthesizing some previous research.

**Comment by davidmpickett** [comment]
Closing in favor of https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13598
