### ISSUE TITLE
Fayetteville vet center redirect: facility.asp

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#10815]
## Description
A leftover from #9640  

Current URL  |  Redirect Destination or New URL
---  |  ---
https://www.va.gov/directory/guide/keystaff.cfm?id=5706 | https://www.va.gov/fayetteville-ar-vet-center/

## Acceptance Criteria
- [ ] After deploy, check original URLs on production to confirm that each properly redirects and resolves to the requested URL before closing ticket
- [ ] Remove code added https://github.com/department-of-veterans-affairs/devops/pull/11931/files#diff-210d4e3cc66d2111cf746e2de539bf44ec3523f6f800640bbeebfc99b71a6953R2352 - this was incorrect for Fayetteville, and the 619 > Missoula line elsewhere in the file should remain

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [X] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by wesrowe** [comment]
Something seems wrong with the linked issue that this is "leftover" from. It's taking me to a PR: VACMS-40703: Add referenced nodes to alert content audit.

**Comment by jilladams** [comment]
Good catch, #9640. Fixed in ticket description.
