### ISSUE TITLE
SPIKE2: FE: Search pagination: shows results for previous search

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#10819]
## Description

As a Veteran, I want to be able to use the pagination arrows to see more pages of my current search, not my previous search.

Defective behavior: in front-end, search pagination UI will pull up results for previous search.

A comment on the previous discovery ticket contains pointers to previous tickets / PRs related to search pagination that may offer clues: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9425#issuecomment-1234782063 

While investigating Part 1 under #9425, Allison wasn't able to replicate the bug locally but did observe that React state isn't updating correctly. 

### To Reproduce as a user
1. Go to VA.gov and enter any keyword/s (e.g. **message doctor**) in Search drop-down in the header. Note you will arrive at the Search Results page with no issues.
3. Enter a different keyword in the search field on the current Search Results page (e.g. **refill prescription**). Note you will arrive at page 1 with no issues. 
4. Scroll down and click on any page after 1. 
5. Note that you will be redirected to page 1 of the previous search (i.e. **message doctor**)

### To repro locally:
1. On your local `vets-website` repo, go to the following file: **src/platform/utilities/api/index.js**
1. Change line 57 from:
    ``` const baseUrl = `${environment.API_URL}/${apiVersion}`; ```
  to
    ``` const baseUrl = `https://api.va.gov/${apiVersion}`; ```
1. After spinning up your local server, perform a search and try to replicate the bug.  (Allison was unable to repro locally)

## Additional context
Search uses third-party search.gov product. Dave has invited people (by their VA emails) to join our account.

## Acceptance Criteria
- [ ] Verify or disprove React state change report
- [ ] Document findings
- [ ] Recommend path forward to fix pagination bug
- [ ] Write implementation ticket

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by wesrowe** [comment]
@jtmst, I assigned to you for a glance-over before refinement, if you have time.

**Comment by jtmst** [comment]
Implementation notes here: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11282
