### ISSUE TITLE
Homepage prototype: Implement search results version of search input

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#10814]
## Description
Homepage iteration mobile designs indicate using a search input that displays a full width button under the input. This work is broken out of #10648 for follow up.

![191373793-5b8afe9c-cf2a-429d-b104-ca1ca79b3e9e](https://user-images.githubusercontent.com/85581471/191863313-a47ba86a-f2a4-4e0b-99c7-356f0b8bfae9.png)

On va.gov, if you search, land on search results, then the search input on the results page does show a la RyanT's designs: input over full width button, with both magnifying glass + Search text in button. e.g. https://www.va.gov/search/?query=test&t=false

This is one very big component rather than one split into atomic components. However, styles can be applied to mimic it, but need some additional work to be a full match style-wise. Typeahead suggestions need investigation. (From Brian: if I were able to point the API_URL to a known working instance of the API endpoint and test against that, adding the missing pieces as needed, could work.)

## Acceptance Criteria
- [ ] Search button floats full-width below search input on smallest mobile screens
- [ ] Typeahead works the same way as on Header search input (and if not: let's discuss / document differences)

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [X] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by apisandipas** [comment]
@jilladams @mmiddaugh After experimenting with the Search Component more, I'm thinking we may be better off using the existing implementation rather than building a one-off implementation with custom styling and duplicate functionality (both search and suggestion box) just to gain a small amount of pay off in the form of a wrapping button. I think it may make more sense effort / time-wise to just use the existing component and use the search Icon  + "Search" text on larger screens, then just the search Icon on small screens.

**Comment by jilladams** [comment]
Adding: One note Bryan raised in Slack is that the custom implementation would lose the typeahead/lookup functionality, which seems like the biggest downside.

**Comment by jilladams** [comment]
Reviewed with Michelle in homepage sync. Decisions: 
* Don't want to lose typeahead
* Will leave both mobile and desktop with just magnifying glass, no "Search" included, to align with header.

Closing this as no-op & adjusting points to just reflect effort spent so far.
