### ISSUE TITLE
Implement changes to remove default-to-healthcare when header megamenu is opened

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#10811]
## Description
In #10678, @apisandipas determined the implementation method to get the megamenu open without opening the Healthcare benefit area by default. 

![189729353-23935d11-054a-4117-be21-03952acbabf7](https://user-images.githubusercontent.com/85581471/191800577-06ac777e-599d-47ec-b3c6-7ed927c6e51a.png)

This implementation is in PR: https://github.com/department-of-veterans-affairs/vets-website/pull/22184
Outstanding work is to test as an injected header to confirm that everything works as expected, before merging. Testing steps in https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/proxy-rewrite.

## Acceptance Criteria
- [x] Megamenu opens with only top level menu exposed
- [x] For 508 purposes, markup is not present for expanded benefit menu either
- [ ] Injected header implementations work the same as VA.gov 

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [X] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by jilladams** [comment]
@apisandipas looks like this is live? Ok to close?

**Comment by apisandipas** [comment]
Yes, its live. Okay to close. @jilladams

**Comment by jilladams** [comment]
Verified also on m.va.gov & benefits.va.gov re: injection. Closing.
