### ISSUE TITLE
New Facility: Knox West VA Clinic

### ISSUE THREAD

**Issue by stefaniefgray** [department-of-veterans-affairs/va.gov-cms#10826]
## Intake
- [x] What triggered this runbook? (Flag in CMS, Help desk ticket, Product team, VHA Digital Media)
Flag in CMS, 
- [x] Link to associated help desk ticket (if applicable)
https://va-gov.atlassian.net/browse/VAHELP-4849
- [x] Name of submitter (if applicable)
editor = cory.chapin@va.gov
- [x] If the submitter is an editor, send them links to any relevate KB articles for the VAMC Facility product.
KB articles: https://prod.cms.va.gov/help/vamc/about-locations-content-for-vamcs/how-do-i-add-a-facility-to-my-health-care-system
- [x] Link to facility in production:
Prod link: https://prod.cms.va.gov/locations/knox-west-va-clinic 
Facility Locator link: https://www.va.gov/find-locations/facility/vha_621QG 

### New VAMC Facility
Please refer to the Knowledge Base article titled "How do I add a facility to my health care system?" for more information: https://prod.cms.va.gov/help/vamc/about-locations-content-for-vamcs/how-do-i-add-a-facility-to-my-health-care-system

#### CMS help desk steps
- [x] 1. Become aware that the new facility is now on the Facility API (typically, via a Flag, but this may come in as a helpdesk ticket).
- [x] 2. If the editor has followed the steps from the above Knowledge Base article and included which section and VAMC the facility belongs to (i.e. VA Pittsburgh), great! **Proceed to step 3.** If not, please check with the editor or VHA digital media regarding what section and VAMC it belongs to.
- [x] 3. Updates the Section (default is "VAMC facilities", but it should be a VAMC system in a VISN) and VAMC system field accordingly.
- [x] 4. Communicate with editor (cc VHA Digital Media) to give them go-ahead to complete the content, with this [KB article](https://prod.cms.va.gov/help/vamc/about-locations-content-for-vamcs/how-do-i-add-a-facility-to-my-health-care-system).
[@TODO: Update email template]

<details><summary>Email template </summary>

```
Hello! You should now be able to edit the draft page for this facility, located at [LINK TO NEW FACILITY DRAFT PAGE ON PROD]

Important: Please make sure that all relevant steps listed within the “How do I add a facility to my health care system?” Knowledge Base article have been completed: https://prod.cms.va.gov/help/vamc/about-locations-content-for-vamcs/how-do-i-add-a-facility-to-my-health-care-system

Once finished, please save this page (and all related VAMC Facility Health Service pages) in the moderation state “Draft." Please do not save them as “Published.”

Please let us know when your draft content is complete, so that we can wrap up the technical process from our end before publishing the new facility to VA.gov. Thanks!
```
</details>
- [ ] 5. Create a URL change request, changing the entry from the old facility URL to the new facility URL: 

https://github.com/department-of-veterans-affairs/va.gov-cms/issues/new?assignees=&template=runbook-facility-url-change.md&title=URL+Change+for%3A+%3Cinsert+facility+name%3E
(**Note: The URL change request ticket blocks the completion of this ticket.**)

https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13378

(Redirects deploy weekly on Wed. at 10am ET, or by requesting OOB deploy (of the revproxy job to prod) in #vfs-platform-support. Coordinate the items below and canonical URL change after URL change ticket is merged, deployed, and verified in prod.)

- [x] 6. When editor has prepared content and let help desk know, reassign this issue to appropriate CMS engineer on Product Support team, for bulk publishing.

#### CMS engineer steps
- [x] 7. CMS engineer executes the steps of the URL change request ticket from step 5.
- [x] 8. CMS engineer bulk publishes nodes and facility.
- [x] 9. CMS engineer edit facility node and remove `New facility` flag and save node.
- [x] 10. Let help desk know this has been done.

#### CMS Help desk (wrap up)
- [ ] 11. Notify editor and any other stakeholders.

## CMS Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [ ] `Public Websites`
- [x] `Facilities`
- [x] `User support`

**Comment by JQuaggles** [comment]
Waiting on editors to finish.

**Comment by stefaniefgray** [comment]
Created new "Waiting for editor" label and edited title to reflect status

**Comment by JayDarnell** [comment]
@stefaniefgray following up to see if we are still waiting for the editor.

**Comment by stefaniefgray** [comment]
Followed up on March 10th, still waiting on response

**Comment by stefaniefgray** [comment]
Followed up with editors on March 10th and March 23rd

**Comment by jilladams** [comment]
Note: updated ticket body to use latest runbook steps. After looking at several of these, I'm now convinced the Vet Center steps were leftover from a previous era of runbook steps, so have **removed the Vet Center new facility steps.** @stefaniefgray @TroyA6 , if this is incorrect, please let me know!

**Comment by stefaniefgray** [comment]
@jilladams Lol yup you were correct, the old runbooks were truly in need of renovation

Thanks for deleting the extraneous Vet Center runbook steps! 

Ultimately, VAMCs and Vet Centers = apples 🍎 and oranges 🍊 and will rarely ever be mentioned within the same ticket unless it's to fix a shared content type

**Comment by stefaniefgray** [comment]
The “Downtown West VA Clinic” is located at 1521 Downtown West Boulevard, while the new “Knox West VA Clinic” is located at number 1612 Downtown West Boulevard. 

Editor believes they may count as one and the same -- however, Google Maps shows each of these addresses located across the street from one another, about a 3 minute drive.

There are also two separate pages for each facility listed within the Facility Locator:

Downtown West: https://www.va.gov/find-locations/facility/vha_621QE 
Knox West: https://www.va.gov/find-locations/facility/vha_621QG 

Waiting for editor to check with his team regarding next steps

**Comment by stefaniefgray** [comment]
Followed up with editors in https://va-gov.atlassian.net/browse/VAHELP-4849 and escalated to VHA Digital Media

We had originally emailed them about this facility back in Sept. 2022 and still don't have an answer on whether this location is separate from the nearby downtown location -- see above comment for details

**Comment by stefaniefgray** [comment]
Homepage is ready: https://prod.cms.va.gov/mountain-home-health-care/locations/knox-west-va-clinic

- Changed alphabetical order of VA Mountain Home "Locations" menu
- Checked over and bulk-published facilities and nodes
- Removed "New Facility" and "Awaiting Editor" flags and added "Awaiting CSV" flag

Will reach out to editor and close this ticket after the CSV is updated in https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13378

**Comment by stefaniefgray** [comment]
@omahane Ready! 🚀

**Comment by omahane** [comment]
The CSV has been deployed. This change is now live.

**Comment by stefaniefgray** [comment]
@omahane Looks good! Closing. Thanks for your help
