### ISSUE TITLE
Whitescreen on user/SELF/edit

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#1082]
**Describe the defect**
When you go to edit yourself, results in white screen
`The website encountered an unexpected error. Please try again later.`
Attempting locally, I get
`The website encountered an unexpected error. Please try again later.
Error: Call to a member function getComponent() on null in hide_revision_field_form_user_form_alter() (line 45 of modules/contrib/hide_revision_field/hide_revision_field.module).`

Seems to be a known issue with a patch but may need to be re-rolled.
https://www.drupal.org/project/hide_revision_field/issues/3018160

**To Reproduce**
1. Login
2. Go /user  to take you to yourself (/user)
3. Click on 'edit' tab
4. Behold the glory of the whitescreen

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/5752113/75393900-10138780-58bd-11ea-8cd7-a7b07b401a36.png)

**Desktop (please complete the following information if relevant, or delete):**

**Additional context**

## Labels
- [/] Issue type (red) (defaults to "Defect")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [/] CMS objective (orange) (not needed for bug tickets)
- [ ] CMS-supported product (black)

**Comment by swirtSJW** [comment]
As I feared.  The patch is not applying.   Working on re-rolling now.

**Comment by rachel-kauff** [comment]
@swirtSJW cc: @kevwalsh Does this ticket address an issue users were having, or give them abilities they didn't have before (such as being able to reset their own password?). In other words, does this get a release note?
