### ISSUE TITLE
Audit unauthed experience for React FileInputs that should transition to design system component

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#10820]
## Description
https://dsva.slack.com/archives/C52CL1PKQ/p1663697448906149

> The Design System has added a File input web component va-file-input. The React FileInput component has been deprecated so please plan to migrate to the  new web component. Specifically, the additionalClass and additionalErrorClass properties will no longer be available and the input change event structure has been modified as well. For more details on usage, review the [component documentation](https://design.va.gov/components/form/file-input). If you have questions, contact us on Slack in [#platform-design-system](https://dsva.slack.com/archives/C01DBGX4P45).

We need to confirm that we don't have any FileInputs in the unauthed experience and plan migration if we do.

## Acceptance Criteria
- [x] Audit FE for FileInputReact component
- [x] Document which files include them
- [x] Write implementation ticket to migrate them to design system component, and send link to Wes/Jill for prioritization

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [X] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by jtmst** [comment]
Working on writeup and recommendations on how to to proceed. Should be done by oct 12

**Comment by jtmst** [comment]
There are 4 instances of the old fileInput component used in vets-website

1 of whiles in secure-messaging, is under PW domain and should be able to easily be swapped out for the new component

1 is in the COE status widget, is not under PW domain, and will require some additional work to change over given its use of deprecated props. This should be left for the team that owns this code

the remaining two (financial status and claims status) are not necessarily owned by PW, but should be easiliy swapped for the new component with no additional code.
