### ISSUE TITLE
New Facility: Pine Ridge VA Compensated Work Therapy/Transitional Residence

### ISSUE THREAD

**Issue by stefaniefgray** [department-of-veterans-affairs/va.gov-cms#10832]
See redirect ticket: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13392

## Intake
- [x] What triggered this runbook? (Flag in CMS, Help desk ticket, Product team, VHA Digital Media)
Flag in CMS
- [x] Link to associated help desk ticket (if applicable)
https://va-gov.atlassian.net/browse/VAHELP-4855
- [x] If the submitter is an editor, send them links to any relevate KB articles for the VAMC Facility product.
KB articles: https://prod.cms.va.gov/help/vamc/about-locations-content-for-vamcs/how-do-i-add-a-facility-to-my-health-care-system
- [x] Link to facility in production:
Prod link: https://prod.cms.va.gov/locations/pine-ridge-va-compensated-work-therapytransitional-residence 
Facility Locator link: https://www.va.gov/find-locations/facility/vha_568PC 

### New VAMC Facility
Please refer to the Knowledge Base article titled "How do I add a facility to my health care system?" for more information: https://prod.cms.va.gov/help/vamc/about-locations-content-for-vamcs/how-do-i-add-a-facility-to-my-health-care-system

#### CMS help desk steps
- [x] 1. Become aware that the new facility is now on the Facility API (typically, via a Flag, but this may come in as a helpdesk ticket).
- [x] 2. If the editor has followed the steps from the above Knowledge Base article and included which section and VAMC the facility belongs to (i.e. VA Pittsburgh), great! **Proceed to step 3.** If not, please check with the editor or VHA digital media regarding what section and VAMC it belongs to.
- [x] 3. Updates the Section (default is "VAMC facilities", but it should be a VAMC system in a VISN) and VAMC system field accordingly.
- [x] 4. Communicate with editor (cc VHA Digital Media) to give them go-ahead to complete the content, with this [KB article](https://prod.cms.va.gov/help/vamc/about-locations-content-for-vamcs/how-do-i-add-a-facility-to-my-health-care-system).

[@TODO: Update email template]

<details><summary>Email template </summary>

```
Hello! You should now be able to edit the draft page for this facility, located at [LINK TO NEW FACILITY DRAFT PAGE ON PROD]

Important: Please make sure that all relevant steps listed within the “How do I add a facility to my health care system?” Knowledge Base article have been completed: https://prod.cms.va.gov/help/vamc/about-locations-content-for-vamcs/how-do-i-add-a-facility-to-my-health-care-system

Once finished, please save this page (and all related VAMC Facility Health Service pages) in the moderation state “Draft." Please do not save them as “Published.”

Please let us know when your draft content is complete, so that we can wrap up the technical process from our end before publishing the new facility to VA.gov. Thanks!
```

</details>
- [ ] 5. Create a [URL change request](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/new?assignees=&template=runbook-facility-url-change.md&title=URL+Change+for%3A+%3Cinsert+facility+name%3E), changing the entry from the old facility URL to the new facility URL. (**Note: The URL change request ticket blocks the completion of this ticket.**)

https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13392

(Redirects are released Wednesday afternoons, so coordinate the following items below and canonical URL change around that timeframe.)
- [x] 6. When editor has prepared content and let help desk know, reassign this issue to appropriate CMS engineer on Product Support team, for bulk publishing.

#### CMS engineer steps
- [ ] 7. CMS engineer executes the steps of the URL change request ticket from step 5.
- [ ] 8. CMS engineer bulk publishes nodes and facility.
- [ ] 9. CMS engineer edit facility node and remove `New facility` flag and save node.
- [ ] 10. Let help desk know this has been done.

#### CMS Help desk (wrap up)
- [ ] 11. Notify editor and any other stakeholders.

## CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [x] `⭐️ User support`

**Comment by JQuaggles** [comment]
Waiting on editors to finish.

**Comment by JayDarnell** [comment]
@stefaniefgray do we have a status update from the editors for this one?

**Comment by stefaniefgray** [comment]
Still no update on draft homepage

**Comment by jilladams** [comment]
Note: ticket body has been updated to use the latest New VAMC Facility runbook steps. I also updated the New Vet Center runbook steps -- same question here: do Vet Center steps appear in this ticket because Pine Ridge is a Vet Center? Or is that leftover from a time where we had combined runbook steps for New VAMC & Vet Center facility, and the Vet Center steps here should be removed?

**Comment by stefaniefgray** [comment]
@jilladams Vet Center runbook steps are now deleted! They were completely irrelevant

**Comment by stefaniefgray** [comment]
We originally asked the editors to edit this facility homepage back in September 2022 -- it is now May 24th, 2023

Asked editors once more in https://va-gov.atlassian.net/browse/VAHELP-4855 to please edit the homepage and add health services

Also escalated this to VHA Digital Media

**Comment by stefaniefgray** [comment]
Closing; see linked Jira ticket for details

Not a true VAMC facility
