### ISSUE TITLE
New Facility: Walzem VA Clinic

### ISSUE THREAD

**Issue by stefaniefgray** [department-of-veterans-affairs/va.gov-cms#10835]
## Background

*What triggered this runbook?*
Flag in CMS

*Please attach Facility Locator link and https://prod.cms.va.gov/ link to this ticket*

Prod link: https://prod.cms.va.gov/locations/walzem-va-clinic 
Facility Locator link: https://www.va.gov/find-locations/facility/vha_671GT

*Please also include link to Jira help desk ticket, if applicable*
https://va-gov.atlassian.net/browse/VAHELP-4859

**Redirect request:** https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12651

### VAMC
Please refer to the Knowledge Base article titled "How do I add a facility to my health care system?" for more information: https://prod.cms.va.gov/help/vamc/about-locations-content-for-vamcs/how-do-i-add-a-facility-to-my-health-care-system

#### CMS help desk steps
- [x] 1. Become aware that the new facility is now on the Facility API (typically, via a Flag, but this may come in as a helpdesk ticket).
- [x] 2. If the editor has followed the steps from the above Knowledge Base article and included which section and VAMC the facility belongs to (i.e. VA Pittsburgh), great! **Proceed to step 3.** If not, please check with the editor or VHA digital media regarding what section and VAMC it belongs to.
- [x] 3. Updates the Section (default is "VAMC facilities", but it should be a VAMC system in a VISN) and VAMC system field accordingly.
- [x] 4. Communicate with editor (cc VHA Digital Media) to give them go-ahead to complete the content, with this [KB article](https://prod.cms.va.gov/help/vamc/about-locations-content-for-vamcs/how-do-i-add-a-facility-to-my-health-care-system).
- [x] 5. When editor has prepared content and let help desk know, reassign this issue to appropriate CMS engineer on Product Support team, for bulk publishing.

    #### Sample notification email:
    Hello! You should now be able to edit the currently un-published draft page for this facility, located at [LINK TO NEW FACILITY DRAFT PAGE ON PROD]

    Important: Please make sure that all relevant steps listed within the “How do I add a facility to my health care system?” Knowledge Base article have been completed: https://prod.cms.va.gov/help/vamc/about-locations-content-for-vamcs/how-do-i-add-a-facility-to-my-health-care-system
    
    Once finished, please save this page as a “Draft”, and do not save it as “Published.”

    Please let us know once your draft is complete, so that we can wrap up the technical process from our end and ensure that the new facility publishes to the live site as intended. Thanks!

#### CMS engineer
- [x] 6. CMS engineer bulk publishes nodes and facility.
- [x] 7. CMS engineer edit facility node and remove `New facility` flag and save node.
- [x] 8. Let help desk know this has been done.

#### CMS Help desk
- [ ] 9. HD notifies editor and any other stakeholders.

## CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [x] `⭐️ User support`

**Comment by JQuaggles** [comment]
Not open yet, no open date set.

**Comment by stefaniefgray** [comment]
Still waiting on editors to tell us when the clinic is opening

**Comment by stefaniefgray** [comment]
Per https://va-gov.atlassian.net/browse/VAHELP-5339

Walzem is opening soon and draft homepage has been passed to editor (Step 4)

Waiting on editor to finish draft homepage and add health services

**Comment by stefaniefgray** [comment]
Just removed icebox label since editor is currently working on this one

**Comment by stefaniefgray** [comment]
@JayDarnell @omahane @Dottisea Walzem is ready to go! 🚀 

Homepage and health services nodes are all saved as drafts and ready for publishing

**Comment by stefaniefgray** [comment]
@ryguyk Good example of a basic new facility ticket

**Comment by stefaniefgray** [comment]
@kmariepat-cityfriends @JayDarnell @omahane Flagging as a facility that's good to go and needs be prioritized per the editor since the clinic has been open for some time -- please see above update from Feb. 7th. 😬

**Comment by JayDarnell** [comment]
I may have cycles to do this today. I need to wrap the updates to the runbooks first but if I have time later I can knock this out. @kmariepat-cityfriends @stefaniefgray

**Comment by omahane** [comment]
@stefaniefgray @kmariepat-cityfriends I have published the facility and services and have removed the New Facility flag.

**Comment by kmariepat-cityfriends** [comment]
@omahane sounds good, thanks for the update! Anything else needed before closing this issue? If not, feel free to close it. I'm also asking under the context of learning definition of done to see if there are any additional actions we take before closing an issue

**Comment by stefaniefgray** [comment]
<img width="600" alt="Screen Shot 2023-03-13 at 3 46 00 PM" src="https://user-images.githubusercontent.com/9059428/224839393-cf51d6e7-4493-4079-8dc5-77b935d02eff.png">

Editor is notified -- closing! Thank you for all your help @omahane 🎸 

cc: @kmariepat-cityfriends Always good to confirm that all is well with the editor before closing! I'd like to add that to the definition of done, just in case they notice anything amiss on their end post-publishing. Thanks for your help as well! 💃

**Comment by omahane** [comment]
@stefaniefgray I have created this PR for the Facility locator:
https://github.com/department-of-veterans-affairs/lighthouse-facilities/pull/425
