### ISSUE TITLE
Automation discovery for CMS metrics

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-cms#10843]
## Description
It'd be good to automate delivery of scheduled reports to Dave for certain metrics that I think we're currently keeping in DataDog:
- [ ] Total number of accounts on https://prod.cms.va.gov/: 1,450
- [ ] Total number of currently active accounts on https://prod.cms.va.gov/: 1,019
- [ ] Total number of users who are not administrators, API accounts, or “ghost” accounts (accounts created by folks eager to use their PIV card login before an actual account has been created for them): 880
- [ ] Total number of active Drupal users who have logged in within the past 60 days (since 6/2/2022): 356
- [ ] Total number of active Drupal users who have logged in within the past 6 months (since 2/1/2022): 555

I think we can create a dashboard, keep that in Terraform, and then automate delivery of that via email without much trouble.

## Acceptance Criteria
Tickets to create:
- [x] #10989
- [x] #10988
- [x] #10990

**Comment by EWashb** [comment]
@ndouglas did you decide on an email to send this to? I wouldn't mind getting a copy if it's possible to add other emails.

**Comment by ndouglas** [comment]
I thought you were going to tell me the email, lol.

But yeah, I'm sure this can (and likely should) go to multiple addresses 🙂

**Comment by EWashb** [comment]
Insert spidey pointing emoji lol 

@dawnpruitt what all emails should this go to?

**Comment by EWashb** [comment]
Ok @ndouglas the emails we will need are:

erika@cityfriends.tech
dawn.pruitt@agile6.com
clarence.maeng@agile6.com
david.conlon@va.gov
troy.griffin@agile6.com
stefanie.gray@agile6.com
