### ISSUE TITLE
Redirect Request 9/27: CareerScope assessment page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-cms#10844]
### Instructions
- Requests must be submitted **AT LEAST** 2 weeks in advance.  Some requests take a significant amount of time and coordination to implement, so start the process as soon as you know you will need one. 
- This issue will be used from initial request through implementation to ensure all individuals working on this are notified of status updates.  Please do not create multiple issues to track differnt steps.
- It is your responsibility to notify VA stakeholders as appropriate.  

### Type of request
- [x] We are retiring or taking down a page and need to redirect the URL (complete redirect section)
- [ ] We are changing the URL of an existing page (complete redirect section)
- [ ] We need a custom vanity URL (complete vanity URL section)

### Implementation date
9/27/22

### Redirects 
Current URL  |  Redirect Destination or New URL (**use 302**)
---  |  ---
https://www.va.gov/careers-employment/careerscope-skills-assessment/ |https://www.va.gov/careers-employment/veteran-resources/ <br>
Please implement as a temporary redirect

### Vanity URLs 
Vanity URL  |  Landing page
---  |  ---
requested URL | landing page URL

**Link to campaign landing page request issue:**

### Process, Roles and Responsibilities
- [ ] Requesting team: Above information is provided
- [ ] Requesting team: All appropriate VA stakeholders are notified as appropriate
- [ ] IA: Request is vetted and documented and implementation plan is clear 
- [ ] IA: Request is assigned to appropriate team for implementation 
- [x] Implementation team: Work is complete
- [ ] Implementation team: Validated in production
- [ ] Requesting team: Validates everything is correct in production and closes ticket

**Comment by jilladams** [comment]
@RLHecht Has a target date of Tuesday, but URL is TBD. Is this a hot one, meaning: should we be expected to quick turn to make sure we get the change merged Mon for Tuesday 9/27 deploy? Or is timing actually more flexible?

**Comment by jilladams** [comment]
https://dsva.slack.com/archives/C52CL1PKQ/p1663953783919489

**Comment by mnorthuis** [comment]
Just updated the redirect to include the destination at the top of the issue.  **Also note that this should be implemented as a 302 temporary redirect, as we will likely be updating this redirect in the near future.**
