### ISSUE TITLE
Review existing design documentation for Income Limits

### ISSUE THREAD

**Issue by davidmpickett** [department-of-veterans-affairs/va.gov-cms#10847]
## Description
As the UX Lead, I need to understand the design work that has been done so far on Income Limits so I can prioritize how design resources are allocated to it during Q4

## Acceptance Criteria
- [x] Read all the things
  - [x] [Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/income-limits-app)
  - [x] [Existing website](https://www.va.gov/healthbenefits/apps/explorer/AnnualIncomeLimits/HealthBenefits)
  - [x] [Mural of Existing App](https://app.mural.co/t/vagov6717/m/vagov6717/1657807571797/ee2497db0a9c637538f51e38546ffe3eaea508c0?sender=u20829d1b64855e281dde2585)
  - [x] [Research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/income-limits-app/research/research-plan.md) 
  - [x] [Conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/income-limits-app/research/conversation-guide.md)
  - [x] [Design Intent](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/income-limits-app/research/design-intent-notes.md)
  - [x] [Research Repo ticket](https://github.com/department-of-veterans-affairs/va.gov-research-repository/issues/168)
- [x] Have a meeting with Wes and Jill to discuss my understand and craft a path forward

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by davidmpickett** [comment]
@wesrowe @jilladams - just pulled together this simple ticket for what I expect to do in Sprint 68

**Comment by wesrowe** [comment]
Confirming that I'm happy to support you in this. Since you labeled it for PW I'll move it to the stretch/next sprint column for planning into the sprint.

**Comment by davidmpickett** [comment]
@wesrowe @jilladams I filled this ticket out a little more with my intended reading list. My plan is to basically be dedicated to Public Websites and this ticket for the 2nd Half of Sprint 68.

**Comment by davidmpickett** [comment]
Meeting schedule for Wednesday to discuss with @wesrowe & @jilladams

**Comment by davidmpickett** [comment]
Outcome from today's meeting @wesrowe and @jilladams are going to try and connect with Cindy Merrill tomorrow about possible involvement. Results of that convo will then be brought to Dave C to determine path forward.

**Comment by davidmpickett** [comment]
Moving this to done for Sprint reporting

**Comment by davidmpickett** [comment]
I crunched some [numbers](https://www.va.gov/vetdata/docs/Utilization/Number_of_Veteran_Patients_by_HC_Priority_Groups_2000_2017.pdf) and as of 2017:

-  19% of Veterans enrolled in Health Care are in Priority Group 7 or 8 where Income is definitely a factor
- 20% of Veterans enrolled in Health Care are in Priority Group 5 where Income may be a factor
- So, we’re probably talking about roughly between 20% - 30% of the Veteran population that might have direct insight into the income limits part of eligibility.
