### ISSUE TITLE
Discovery: Tech options for CMS Analytics

### ISSUE THREAD

**Issue by EWashb** [department-of-veterans-affairs/va.gov-cms#10849]
## Background

To enhance data collection in the CMS, we should look into analytics options that work within the VA infrastructure. 

## Acceptance Criteria

- [x] research analytics options that are open source
- [x] provide list of best options for our needs

**Comment by EWashb** [comment]
Feel free to add your suggestions/findings in the notes of this ticket @ndouglas and @edmund-dunn

**Comment by ndouglas** [comment]
Is it possible that we can leverage DataDog/DataDog APM for this rather than spinning up a new application and infrastructure?

**Comment by EWashb** [comment]
Would it be able to give us GA-type analytics on individual pages? I'm open DataDog absolutely if it can give us what we need!

**Comment by ndouglas** [comment]
I don't know -- it was just an idea that occurred to me.

I think RUM might be what we'd be looking at: https://docs.datadoghq.com/real_user_monitoring/browser/data_collected/  

It looks at first glance like this might be sufficient for our purposes, depending on what info we want to gather.

And it looks like we can [modify the event](https://docs.datadoghq.com/real_user_monitoring/browser/modifying_data_and_context/?tab=npm) to provide additional helpful information mirroring the info we currently provide to GA/GTM.

**Comment by EWashb** [comment]
Honestly, at a quick first glance, RUM looks like it's checking all the basic boxes.

**Comment by EWashb** [comment]
After researching, the dev team has found that DataDog will be pretty basic, but could have benefit. However, PostHog will be the top recommendation for our use. It is well documented, open source, active community support, and has lots of resources for Drupal. Also, PostHog provides us with:

- Event-based analytics at a user level
- Product data visualizations
- Complete control over your data
- Session recording
- Automatically capture
- Heatmaps
- Plugins to integrate your product with other systems
- Ready-made libraries for JS, Python, Ruby, Node, Go, Android, iOS, PHP, Flutter, React Native, Elixir + API

However, this will require infrastructure support from the Platform CMS team

**Comment by EWashb** [comment]
Also, there is no limit to the number of users that we can have in-house.
