### ISSUE TITLE
CMS: Update runbooks and KBs for adding, renaming, retiring Facilities - both for VAMC and VC

### ISSUE THREAD

**Issue by dsinla** [department-of-veterans-affairs/va.gov-cms#10845]
Make sure current runbook issues properly account for VC and VAMC facilities. We want to split the existing runbooks for new facilities, updated facilities and removed facilities by facility type to help keep the steps involved for each clean and concise.

Make sure KBs are aligned once runbook issues are revised. (This should probably be in a separate ticket @dsinla )

**Comment by JayDarnell** [comment]
Lets convert this into an epic with sub issues for each individual runbook we need. Devs should make an initial draft in each case and then cowork with helpdesk to refine the steps so they make sense to all parties involved and take into account steps needed to clearly communicate these things with editors.
