### ISSUE TITLE
Facility System Change + Redirect Request for Stockton VA Clinic - Moving from VA Palo Alto to VA Northern California on 10/9/2022

### ISSUE THREAD

**Issue by stefaniefgray** [department-of-veterans-affairs/va.gov-cms#10852]
### Instructions
- This issue will be used from initial request through implementation to ensure all individuals working on this are notified of status updates.  Please do not create multiple issues to track different steps.
- It is your responsibility to notify VA stakeholders as appropriate.
- Be sure to link the related facility closure / rename issue.
- Front end redirects are tracked in the [devops](https://github.com/department-of-veterans-affairs/devops) repo in `ansible/deployment/config/revproxy-vagov/vars/redirects.yml`

### Implementation date
When does this request need to be live: October 9th, 2022

### Redirects 
| Current URL  |  Redirect Destination or New URL |
| ---  |  --- |
| https://prod.cms.va.gov/palo-alto-health-care/locations/stockton-va-clinic | https://prod.cms.va.gov/northern-california-health-care/locations/stockton-va-clinic |

## **Note:** All associated pages and VAMC Facility Health Services linked to the Stockton VA Clinic must also be re-assigned from VA Palo Alto to VA Northern California.

See: https://prod.cms.va.gov/admin/content?title=stockton&type=All&moderation_state=All&owner=235

For more information about the clinic reassignment, see: https://www.va.gov/palo-alto-health-care/programs/east-bay-community-based-outpatient-clinic-realignments/

## CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [x] `⭐️ User support`

**Comment by stefaniefgray** [comment]
Added Facilities folks @omahane and @JayDarnell

**Comment by JayDarnell** [comment]
Redirect request created here: https://github.com/department-of-veterans-affairs/devops/pull/12033

**Comment by JayDarnell** [comment]
@stefaniefgray @TroyA6 I'll get this over the finish line today after demo.

**Comment by JayDarnell** [comment]
![Screen Shot 2022-10-07 at 12 30 16 PM](https://user-images.githubusercontent.com/21045418/194602789-525e1553-be05-4e80-be78-e6c6bb0c8d98.png)

The draft copy of the Stockton VAMC Facility has been published (this draft places it in the Northern California system) All 16 VAMC Facility health services for this facility have been updated to the Northern California system as well.

**Comment by stefaniefgray** [comment]
@JayDarnell Reopening -- sorry!

The menu link breadcrumbs on the Stockton VA Clinic pages still show VA Palo Alto. Should this be part of this ticket or should I open a new one?

Proof: https://www.va.gov/northern-california-health-care/locations/stockton-va-clinic/

![Screen Shot 2022-11-29 at 10 19 19 AM](https://user-images.githubusercontent.com/9059428/204598252-7f2f72fb-3fc3-4050-8ddc-1728858b215f.png)

**Comment by JayDarnell** [comment]
Sorry @stefaniefgray I was out of office when you tagged me on this so I'm just now seeing it. I'll take a look today.

**Comment by stefaniefgray** [comment]
@JayDarnell No problem, sounds good! Just showed @omahane what's going on

Turns out Stockton is also still listed under VA Palo Alto's "Locations" menu instead of VA Northern California's 

![Screen Shot 2022-12-01 at 12 38 41 PM](https://user-images.githubusercontent.com/9059428/205144292-f73ae923-99e6-4888-a54f-2f86f9802ce6.png)

**Comment by JayDarnell** [comment]
@stefaniefgray I have fixed this issue. When I went in to investigate it is true that the original Stockton VA Clinic was still listed in the menu for Palo Alto. To complicate matters, that node was marked as removed from source (no longer in lighthouse). When I investigated further I discovered a new copy of Stockton VA Clinic that was added to the CMS from lighthouse only recently. 

- I archived the original Stockton VA Clinic and deleted the menu item for it from the Palo Alto system
- I updated the new Stockton VA Clinic by adding it to the Northern California system
- I then updated all the facility health services for the original Stockton VA Clinic by assigning them to the new one

You will likely run into a similar issue with Sonora, only in this case there are two copies of Sonora in the CMS, both published and both still existing in Lighthouse. The process, however, should be quite similar. Sing out if you need assistance tomorrow and I can help you tackle that one as well.

**Comment by stefaniefgray** [comment]
@JayDarnell THANK YOU!!!

**Comment by omahane** [comment]
@stefaniefgray We have an issue with Psychiatry, in that there's [no VAMC Facility Health Service for Psychiatry in Northern California](https://prod.cms.va.gov/admin/content?title=&type=regional_health_care_service_des&moderation_state=All&owner=233). There is one for Palo Alto. I am not sure what to do about this service. I'll change all the others that I can, though.
