### ISSUE TITLE
Develop plan of attack and RACI with VHADM for Lovell

### ISSUE THREAD

**Issue by dsinla** [department-of-veterans-affairs/va.gov-cms#10853]
Dave C, Roger, David S have a meeting to level set on how much of the Lovell work can be mapped to previous runbooks vs what has to be recreated custom for Lovell. 
Have some spelunking done in advance

Review:
https://dsva.slack.com/archives/C0FQSS30V/p1661988263230359
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/medical-centers/Dual-State_RunBook_2020.1.21_Final.xlsx

Notes:  Figure out what we have vs what we need, 

- Have plan by end of sprint for getting Lovell TRICARE up and running
- Gap analysis of VA lovell - 
- To support meeting at end of sprint to come to consensus with VHADM for going forward.

**Comment by dsinla** [comment]
Waiting for Dave C availability after his PTO and Onsite - targeting Sprint 70

**Comment by dsinla** [comment]
Uploaded to va.gov SharePoint and made available to the org. Not quite a RACI with ownership, but a plan of attack to discuss with VHADM, and questions to address:
https://dvagov-my.sharepoint.com/:x:/g/personal/david_shannon_va_gov/ER7X5Y1Lq6xOmhdzLtjfoQgBNjgCS55TMPINOUC7t_NiTQ?e=xM1VRw

**Comment by dsinla** [comment]
Not quite a RACE, but a content-driven sitemap to drive discussions with VHADM, and a list of questions and issues to be investigated. Next step would be a meeting with Blake and Justin from VHADM to walk through this together, make sure we're all on the same page, and assign action items: _VHADM will audit existing Teamsite pages, David S will investigate menu functionality_ 
We have a big questions around VA services vs TRICARE services, which I expect will have to be answered by the Lovell editors.

**Comment by JayDarnell** [comment]
@dsinla is there anything you need from the Dev team for this?

**Comment by dsinla** [comment]
@JayDarnell  We determined that previous runbooks didn't really have a plan that could be adapted, so we're documenting our plan on the similar ticket: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11357

Again, I think the next step is a review with DEV when I've got the plan in a solid draft.  Thanks!

**Comment by dsinla** [comment]
The final steps for Lovell, and owners and projected timeline, is documented in this ticket https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11357
