### ISSUE TITLE
PM: Facilitate the team testing Lovell in testing environment and create location to collect any punchlist issues

### ISSUE THREAD

**Issue by dsinla** [department-of-veterans-affairs/va.gov-cms#10854]
When dev is complete on the basic Lovell framework, provide an environment for the team to test, and a place for all to centrally capture any defects.

- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11026
- [Tugboat](https://tugboat.vfs.va.gov/6335bde25121c36516d47d17)
   - [CMS](https://cms-liqqgmzl7tsyfbwyulbkuborufuuttav.demo.cms.va.gov) 
   - [Web](https://web-liqqgmzl7tsyfbwyulbkuborufuuttav.demo.cms.va.gov/lovell-federal-va-health-care/)

**Comment by dsinla** [comment]
Setting up meeting with @maxx1128 to get instructions on how non-devs can access the environment and key items to look for in their exploration.

**Comment by davidmpickett** [comment]
FYI - I was able to get in following these steps: https://prod.cms.va.gov/help/how-to-access-and-manage-demo-environments

**Comment by dsinla** [comment]
Google doc with initial instructions https://docs.google.com/document/d/1-BNjcEnrKuv1F0Ics78aGWp441qg8D_XN-_5TvOaGLY/edit#heading=h.ok2nh2f09zf5

**Comment by dsinla** [comment]
Verified with @swirtSJW that the env should be a demo environment, without continuing merging of fixes. We want this environment to be up and stable for a week or so for documentation and testing.

**Comment by dsinla** [comment]
Google doc updated with context info and key steps to test:
https://docs.google.com/document/d/1-BNjcEnrKuv1F0Ics78aGWp441qg8D_XN-_5TvOaGLY/edit#heading=h.ok2nh2f09zf5
