### ISSUE TITLE
"Text" link href has "tel:" instead of "sms:" (Secure-messaging page)

### ISSUE THREAD

**Issue by ryguyk** [department-of-veterans-affairs/va.gov-cms#10868]
## Timing of Design System update
Per Josh's comment below, DS team is enabling SMS during our Sprint 69

### Background
On the [secure-messaging page](https://staging.va.gov/health-care/secure-messaging/), there is a phone number that directs a veteran to "Text":

![image.png](https://images.zenhubusercontent.com/5e274ecde33c5e16549a9361/f665f4a0-fb95-4f3c-8c2d-8d90350c5f1d)

Here is the existing code in production:
![image](https://user-images.githubusercontent.com/6863534/192322307-d58ad529-4e98-41f9-ae1d-d49dc3cab288.png)

### The Problem
There is a new eslint rule, `@department-of-veterans-affairs/prefer-telephone-component`, that requires use of the `<va-telephone>` web component.

There is another new eslint rule, `@department-of-veterans-affairs/telephone-contact-3-or-10-digits`, that requires phone numbers to be either 3 or 10 digits when using the `<va-telephone>` web component. This phone number does not meet that requirement. 

In order to move forward without this issue blocking the other changes, I added the `eslint-disable` statement, as shown here:
![image](https://user-images.githubusercontent.com/6863534/192331857-ab43aa32-b592-4022-b37e-d09ac6042c85.png)

### Action item
The `<va-telephone>` web component does not seem to be flexible enough to allow for these non-standard text-only numbers. We should take this up with the design-system team to ask about this use case. Depending on their response, we'll have to do one of the following:
~~1. Do nothing **OR**~~
2. Update call to `<va-telephone>` to accommodate any changes implemented by that team **OR**
3. ~~Use another approach, perhaps like the one shown in the [comment below](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10868#issuecomment-1258257938) by Wes.~~

## Acceptance Criteria

- [x] Update presentation of the SMS number to have colon after label, e.g. Text: [838255]()
- [x] change the href on this text link on the [secure-messaging page](https://staging.va.gov/health-care/secure-messaging/) to `sms:838255`. [Per [design system notes](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1246#issuecomment-1298566047), `Text: <a href="sms:838255" aria-label="8 3 8 3 5 5.">838255</a>`]
- [x] verify whether the disable-eslint comment that Ryan added is still necessary; remove if appropriate
- [x] search codebase for `838255` to make sure there aren't other instances of the number with `tel`
  - [x] fix any you find (within reason)
- [ ] test page in staging to confirm that tapping the number opens your SMS app instead of phone app
- [ ] recommend (and ticket) whether the main VCL (Crisis Line) modal should be updated to use `<va-telephone>` also _whilst ensuring that component is made available to injected headers_

**Comment by jtmst** [comment]
Design team is working to incorporate this into the va-telephone component.  Once they make that change we will be able update the sms numbers across vets-website

**Comment by jtmst** [comment]
blocked pending an update to the design system va-telephone component which is planned for next sprint

https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1246

**Comment by jilladams** [comment]
That design system ticket is now iceboxed. :/

**Comment by wesrowe** [comment]
The DST is closer to finalizing this... see [this comment](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/).

> We had a bit of back and forth on this. We resolve to leave TTY alone and keep the "TTY:" label as part of the link. Thus TTY stays the same:
>
>`<a href="tel:+711" aria-label="TTY. 7 1 1.">TTY: 711</a>`
>
> For text we decided to handle it as we do telephone numbers and not include any label or text. That's left up to the caller to decide on (though our guidance will instruct them NOT to put "text" in the URL). Thus:
> 
> `text <a href="sms:838255" aria-label="8 3 8 3 5 5.">838255</a>`
> 
> There are some current instances of "text" being within the URL but adding SMS to this component, and guidance, should help us resolve those.

I'm a little confused, as I thought we were talking about the `va-telephone` component. But I'm not close to this whole exchange.

@jtmst, does this unblock us? Or, per something @jilladams  pointed out elsewhere, do we need to confirm with the DST that the component is ready for 6-digit numbers?

**Comment by wesrowe** [comment]
Confirmed: DST closed the ticket earlier today.

**Comment by wesrowe** [comment]
Aaand... Here is the [Storybook](https://design.va.gov/storybook/?path=/docs/components-va-telephone--default#sms) with update for SMS. Per Matt Dingee, the component docs will be updated shortly.

Unblocking.

**Comment by jilladams** [comment]
@jtmst can you add update for where this sits currently? I know there was a blocking eslint test that design system was updating -- do we have any update on timing / a PR up?

**Comment by jtmst** [comment]
> @jtmst can you add update for where this sits currently? I know there was a blocking eslint test that design system was updating -- do we have any update on timing / a PR up?

I'll verify that the lint rule is updated if that's the case I'll PR this morning
