### ISSUE TITLE
Map possible CMS incidents for mangement plan

### ISSUE THREAD

**Issue by EWashb** [department-of-veterans-affairs/va.gov-cms#10867]
## Background

Before we can create an incident management plan we must first understand the types of incidents this plan should account for. Also, we should define what accounts for an incident for the CMS team(s).

## Acceptance Criteria

- [ ] Map out scenarios that could affect the CMS
- [ ] Define "incident" in terms of incident management planning for CMS teams

**Comment by EWashb** [comment]
@TroyA6 @stefaniefgray would you like to link your doc in this ticket and close it?

**Comment by TroyA6** [comment]
I'd like to brainstorm one more time with Stefanie to make sure we've
covered as many scenarios as possible.
Then we can likely close that.

Thank you!
Troy

**Comment by EWashb** [comment]
That sounds good @TroyA6. Let me know what you think the best next step is too and I can make sure there's a ticket and it's accounted for in the next sprint :)
