### ISSUE TITLE
Discovery: All areas that need to be tested or checked for PHP upgrade

### ISSUE THREAD

**Issue by edmund-dunn** [department-of-veterans-affairs/va.gov-cms#10871]
## Background

In order to upgrade to PHP 8.1, we need to do some discovery on all the areas that need to be tested or checked.

## Possible Implementation

Identify areas that will need to be tested and/or checked as part of the PHP 8.1 upgrade and add them to the "Tests and areas that need to be checked." area in the Epic description. 

## Acceptance Criteria

- [ ] Identify areas to be tested or checked as part of PHP 8.1 upgrade
- [ ] Add identified areas to the "tests and areas that need to be checked"

**Comment by cmaeng** [comment]
Platform CMS is looking to:
* #10874 
* #10877 
* test on content build

more conversations needed around any other areas to test and prioritization / timelines.

**Comment by EWashb** [comment]
@cmaeng do we need to coordinate a chat between sitewide cms and platform cms or do yall have everything you need from us?

**Comment by edmund-dunn** [comment]
Verify whether web gets built on test? 

Check test results, status reports, and logs.
