### ISSUE TITLE
Configure PHP 8.1 on test.prod for testing

### ISSUE THREAD

**Issue by cmaeng** [department-of-veterans-affairs/va.gov-cms#10872]
Change the number for the referenced build step to 8.1, observe any additional fixes or changes needed, stub out tickets for additional fixes targeted for next sprint.

Details for specific things to test to be driven by Sitewide CMS team.

Performance testing before and after needed to ensure that degradation doesn't occur. This will be timeboxed into a separate ticket.

**Comment by ElijahLynn** [comment]
I'm working on this on test.prod.cms.va.gov.

**Comment by ElijahLynn** [comment]
WIP PR here > https://github.com/department-of-veterans-affairs/devops/pull/12057

Testing builds here http://jenkins.vfs.va.gov/job/builds/job/cms-test/

php-sodium package isn't being found right now, need to figure out which repo to add for that, it isn't in Amazon's.

**Comment by ElijahLynn** [comment]
php-sodium package isn't being found right now, need to figure out which repo to add for that, it isn't in Amazon's. 

https://gist.github.com/davidalger/c19a53ed293291ec2e93b5227f9e0a2d

cc @ndouglas

**Comment by cmaeng** [comment]
Performance testing before and after needed to ensure that degradation doesn't occur. This will be timeboxed into a separate ticket.

**Comment by ElijahLynn** [comment]
`composer install` (via Ansible)

```
07:10:49    msg: 'Failed loading opcache.so: opcache.so: cannot open shared object file: No such file or directory PHP Warning: Module ''memcache'' already loaded in Unknown on line 0 No entry for terminal type "unknown"; using dumb terminal settings. > mkdir -p vendor > [ -f .env ] || cp .env.example .env Installing dependencies from lock file (including require-dev) Verifying lock file contents can be installed on current platform. Your lock file does not contain a compatible set of packages. Please run composer update. Problem 1 - lcobucci/jwt is locked to version 4.1.5 and an update of this package was not requested. - lcobucci/jwt 4.1.5 requires ext-sodium * -> it is missing from your system. Install or enable PHP''s sodium extension. Problem 2 - lcobucci/jwt 4.1.5 requires ext-sodium * -> it is missing from your system. Install or enable PHP''s sodium extension. - steverhoades/oauth2-openid-connect-server v2.4.0 requires lcobucci/jwt 4.1.5 -> satisfiable by lcobucci/jwt[4.1.5]. - steverhoades/oauth2-openid-connect-server
```
http://jenkins.vfs.va.gov/job/builds/job/cms-test/435/console

**Comment by ElijahLynn** [comment]
Maybe the DD thing is similar issue:

```
TASK [build/roles/cms-test/roles/php_setup : Install Datadog Trace PHP Extention] ***
 Thursday 06 October 2022  19:59:45 +0000 (0:00:01.669)       0:03:14.094 ****** 
 fatal: [ec2-3-30-120-133.us-gov-west-1.compute.amazonaws.com]: FAILED! => changed=true 
   cmd: |-
     php $(curl -w "%{filename_effective}" -LO $(curl -s https://api.github.com/repos/DataDog/dd-trace-php/releases | grep browser_download_url | grep 'setup[.]php' | head -n 1 | cut -d '"' -f 4)) --enable-profiling --php-bin=$(basename $(realpath $(which php)))
   delta: '0:00:06.167862'
   end: '2022-10-06 19:59:52.291925'
   msg: non-zero return code
   rc: 1
   start: '2022-10-06 19:59:46.124063'
   stderr: |2-
       % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                      Dload  Upload   Total   Spent    Left  Speed
       0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
     100 55600  100 55600    0     0   129k      0 --:--:-- --:--:-- --:--:--  129k
     Failed loading opcache.so:  opcache.so: cannot open shared object file: No such file or directory
     PHP Warning:  Module 'memcache' already loaded in Unknown on line 0
     No entry for terminal type "unknown";
     using dumb terminal settings.
```

**Comment by ElijahLynn** [comment]
Oh cool, I was able to connect to the bake instance and inspect the state and somehow the version of PHP getting installed is 5.4.16:

```
[root@ip-172-31-16-4 ~]# php --version
Failed loading opcache.so:  opcache.so: cannot open shared object file: No such file or directory
PHP Warning:  Module 'memcache' already loaded in Unknown on line 0
PHP 5.4.16 (cli) (built: Oct 31 2019 18:34:05) 
```

Which in the geerlingguy.php Ansible role, it says:

```
### OpCache-related Variables

The OpCache is included in PHP starting in version 5.5, and the following variables will only take effect if the version of PHP you have installed is 5.5 or greater.

    php_opcache_zend_extension: "opcache.so"
```

![image](https://user-images.githubusercontent.com/1504756/196805135-a97c8f93-3d69-4f64-828c-c61f17232f89.png)

**Comment by ElijahLynn** [comment]
Okay, so, I was able to install PHP 8.1 manually on the bake instance with the Remi repos AND also the php81-php-sodium module too! 

So somehow the geerlingguy.remi Ansible role either isn't installing the Remi repo correctly or another step isn't installing the right PHP version, which may be the more likely case and I am stepping through all that now.

> TASK [build/roles/cms/galaxy/geerlingguy.php : Set the default PHP version for Debian-based OSes.] ***
>  Wednesday 19 October 2022  23:13:01 +0000 (0:00:00.034)       0:06:39.098 ***** 
>  skipping: [ec2-160-1-131-61.us-gov-west-1.compute.amazonaws.com] => changed=false 
>    skip_reason: Conditional result was False

I might also look to see if there are updates to the geerlingguy.remi role, I already updated the geerlingguy.php role to the latest version. 

Anyways, making good progress and really close to nailing this.

**Comment by ElijahLynn** [comment]
I've opened an upstream issue to rubber duck the PHP 8.1 stuff in the Ansible geerlingguy.php role here > https://github.com/geerlingguy/ansible-role-php/issues/382.

**Comment by ElijahLynn** [comment]
Current issue is that the ini files aren't being loaded correctly, so sorting through that.

**Comment by ElijahLynn** [comment]
W00t! PHP 8.1 is mostly working on the BRD servers now, specifically test.prod.cms.va.gov. 

![image](https://user-images.githubusercontent.com/1504756/197653793-717ebc53-0405-4c88-9182-f66cd8fb2577.png)


Somehow Apache doesn't have mod_php loading right though (see screenshot above) and it is just serving the PHP file as text, so that is the next thing to tackle. So close!

**Comment by ElijahLynn** [comment]
Sweet, the module name has changed, so that should be straight forward > https://php.watch/versions/8.0/mod_php-rename.

> In PHP 8.0, the Apache module identifier is renamed to php_module.
>
> In PHP 7.x versions, it was named php7_module, and in PHP 5.x, it was named php5_module.

**Comment by ElijahLynn** [comment]
I was able to get mod_php working in Apache by also installing the package "php81-mod_php" which laid down a `/etc/httpd/modules/libphp81.so` file and then I did a `systemctl restart httpd` and got the front page loading:

![image](https://user-images.githubusercontent.com/1504756/197888295-ae028a12-439d-49de-8e43-e04d4a7bcff1.png)


However, logging in with user/pass (not SSO) results in a white screen, and there are no errors being reported on the login action with a `drush wd-show`. However, there are other errors with non-matching timestamps:

![image](https://user-images.githubusercontent.com/1504756/197888629-dc66954d-3b2d-42a1-9624-9f3d3247e102.png)


>   21   24/Oct 17:44   php    Error      Error: Class 'Drupal\twig_tweak\TwigTweakExtension' not found in
>                                         Drupal\Component\DependencyInjection\Container->createService() (line 262 of
>                                         /var/www/cms/docroot/core/lib/Drupal/Component

**Comment by ElijahLynn** [comment]
Also, during a `drush wd-show` I am noticing:
> PHP Warning:  Module "apcu" is already loaded in Unknown on line 0

So that _should_ be fixed too.

**Comment by ElijahLynn** [comment]
> Also, during a `drush wd-show` I am noticing:
> 
> > PHP Warning:  Module "apcu" is already loaded in Unknown on line 0
> 
> So that _should_ be fixed too, possibly a follow on ticket though.

I fixed this, the geerlingguy.php role was already laying down an apc.ini file, so I just used that and removed our custom override.

**Comment by ElijahLynn** [comment]
> However, logging in with user/pass (not SSO) results in a white screen, and there are no errors being reported on the login action with a `drush wd-show`. However, there are other errors with non-matching timestamps:

sweet, I enabled PHP error logging in settings.prod.php on test.prod.cms.va.gov and was able to see the error now...

> Additional uncaught exception thrown while handling exception.
> Original
> Error: Call to undefined function DDTrace\current_context() in Drupal\va_gov_backend\Service\DatadogContextProvider->getCurrentContext() (line 15 of /var/www/cms/docroot/modules/custom/va_gov_backend/src/Service/DatadogContextProvider.php).

![image](https://user-images.githubusercontent.com/1504756/198152476-e1500575-389d-4b9e-9d28-ccd77aa50438.png)


And I remembered I commented out an install of a Datadog thing temporarily. Fixing now.

**Comment by ElijahLynn** [comment]
Cool, I can log in now! I got it working by running the reverted commit which installs the Datadog trace PHP extension> https://github.com/department-of-veterans-affairs/devops/pull/12057/commits/dfca5a7d602ca16c1a0499076b145b0ad2bec919. See this sensitive comment here https://github.com/department-of-veterans-affairs/devops/pull/12057#issuecomment-1292748886. 

![image](https://user-images.githubusercontent.com/1504756/198154152-5d1b2fe0-dedb-473d-ae94-a8ba5d6d9ee5.png)


Gonna officially revert that commit now, and build and deploy it to test.prod!

**Comment by ElijahLynn** [comment]
@ndouglas noticed Opcache wasn't actually enabled, so I just pushed a fix for that `zend_extension = opcache.so` and also set `opcache.revalidate_timestamps=0` and we have it working on test.prod.cms.va.gov now! I'm deploying it again for assurance, but I did test manually already and it is live now until the deploy hits.

**Comment by ndouglas** [comment]
Copypasta from department-of-veterans-affairs/devops#12057

Same (intermittent) issue as on Tugboat when running CLI PHP commands:

```bash
$ composer install
Gathering patches for root package.
> mkdir -p vendor
> [ -f .env ] || cp .env.example .env
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Package operations: 0 installs, 0 updates, 0 removals
Package doctrine/reflection is abandoned, you should avoid using it. Use roave/better-reflection instead.
Package phpunit/php-token-stream is abandoned, you should avoid using it. No replacement was suggested.
Package simplesamlphp/simplesamlphp-module-authfacebook is abandoned, you should avoid using it. No replacement was suggested.
Package simplesamlphp/simplesamlphp-module-authwindowslive is abandoned, you should avoid using it. No replacement was suggested.
Package simplesamlphp/simplesamlphp-module-oauth is abandoned, you should avoid using it. No replacement was suggested.
Package simplesamlphp/simplesamlphp-module-riak is abandoned, you should avoid using it. No replacement was suggested.
Package symfony/debug is abandoned, you should avoid using it. Use symfony/error-handler instead.
Package twig/extensions is abandoned, you should avoid using it. No replacement was suggested.
Package webmozart/path-util is abandoned, you should avoid using it. Use symfony/filesystem instead.
Generating autoload files
113 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
PHP Fatal error:  Invalid opcode 137/1/0. in phar:///usr/local/bin/composer/vendor/composer/class-map-generator/src/PhpFileCleaner.php on line 168

Fatal error: Invalid opcode 137/1/0. in phar:///usr/local/bin/composer/vendor/composer/class-map-generator/src/PhpFileCleaner.php on line 168
```

See my comments [in this thread](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11315).  **TL;DR**: We should disable JIT or not upgrade.

It's not an issue with project code; if you run the following, you'll see errors:

```bash
cd /tmp 
composer create-project drupal/recommended-project test_dir
cd test_dir

for i in $(seq 1 100); do composer install && echo "SUCCESS" || echo "FAIL"; done;
```

Not frequently, but they will occur some percentage of the time.  

Further, it's not limited to Composer; if you run `drush status` in a loop, you'll see occasional segmentation faults and spurious errors that might be related to a cache failure or something else:

```
In ReorderFields.php line 70:
  The requested field, 'drush-script', is not defined.  
```

```
In ReorderFields.php line 70:                                           
  The requested field, 'root', is not defined.  
```

```
In ReorderFields.php line 70:
  The requested field, 'php-os', is not defined.  
```

```
In ReorderFields.php line 70:
  The requested field, 'drush-version', is not defined.  
```

That sort of thing.

**Comment by ElijahLynn** [comment]
This is done!
