### ISSUE TITLE
Testing api integrations on php 8.1

### ISSUE THREAD

**Issue by cmaeng** [department-of-veterans-affairs/va.gov-cms#10877]
- [ ] Github posts things to the CMS through runners (authentication token to ensure the call back still functions)
- [x] Facilities and Forms APIs
- [x] Content build
- [x] GovDelivery

**Comment by cmaeng** [comment]
@swirtSJW @edmund-dunn @JayDarnell we could use some insight into tests that might be off of our radar. will post in slack for advice too.

**Comment by swirtSJW** [comment]
Forms API external consumer uses GraphQL.    So risk is minimal there an easily surfaced.  However I don't know what they have in place to test their access from say the tugboat environment to make sure they are getting the same response.   We ought to be able to run their query (if we can find it) against our current environment and the php8 env and just diff the results to make sure there is no difference.

Gov Delivery.  That uses a queue, if the queue items fail to send to govdelivery we would get notified becasue we have a check that makes noise if something has been processed in the queue too many times.   For double testing before launch we would have to point tugboat at the staging version of GovDelivery then log in to that and make sure we see the message and it looks right.  (low risk of failure, but HIGH value so worth checking).

Successful content build is the best test we have against graphQL.  The most best would be diff the content build data object on php 7 and php 8 (using the same db)  they should  be identical.   I think Neil may have built something that did that kind of diff for something he was working on long ago.

Facilities API are all push and pulls on our side that will sqwawk if they fail so I think that is pretty well covered.

**Comment by JayDarnell** [comment]
Thank you very much for your response @swirtSJW

**Comment by TheBoatyMcBoatFace** [comment]
Removed Sprint 72 and Added Sprint 73 Label

Related to PHP performance investigation - #11469

ETA Dec 7, 2022

**Comment by timcosgrove** [comment]
I ran an example Forms API query on both Prod (PHP 7.4) and Test Staging (PHP 8.1) and there were no substantive differences. 

[forms_api_query.txt](https://github.com/department-of-veterans-affairs/va.gov-cms/files/10158453/forms_api_query.txt)

**Comment by TheBoatyMcBoatFace** [comment]
# Additional Testing

- [ ] #11800
