### ISSUE TITLE
ON HOLD: Extend continuous content releases from 9am-5pm ET to 8am-8pm ET

### ISSUE THREAD

**Issue by cmaeng** [department-of-veterans-affairs/va.gov-cms#10891]
## Description
Content releases are currently deployed continuously from 9am-5pm ET. This would be an extension of that to match our current helpdesk support hours of 8am-8pm ET.

One of the main problems that this is trying to solve is to extend the content release window for folks outside of ET. Editors in Hawaii for example, have to publish content by 11am Hawaii time in order for same day changes to reflect.

## Acceptance Criteria
- [x] Continuous releases are firing from 8am-8pm ET

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [x] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by cmaeng** [comment]
we will need to coordinate with VHA and other stakeholders on the messaging around this. from a technical standpoint, this is a light lift and the stability shown since moving to continuous releases 2 months ago has our confidence high that there will be little to no issues. the main thing to align on is that support for content release failures won't be available until 12pm ET as all of our DevOps engineers are west coast.

cc: @davidconlon @mchelen

**Comment by EWashb** [comment]
This is ready for you to prioritize in Sprint 74 @TheBoatyMcBoatFace
