### ISSUE TITLE
FE: Facility Health Service link to ATC Facility performance data

### ISSUE THREAD

**Issue by RWEagans** [department-of-veterans-affairs/va.gov-cms#10907]
## Description
ATC Data in the accordions should link to specific Facility performance data rather than the access to care

Example of both Facility level link and Service level link (in audiology) can be found here:
https://www.va.gov/chicago-health-care/locations/jesse-brown-department-of-veterans-affairs-medical-center/

Example of where we want to link to:  https://www.accesstocare.va.gov/FacilityPerformanceData/FacilityData?stationNumber=537

Example of facility detail page: https://www.va.gov/find-locations/facility/vha_537

**NOTE:** Station number is equal to facility_api_id removing the VHA_ string prefix 

## Acceptance Criteria
- [ ] On a VAMC Facility page, the current link to general ATC data is replaced with link to specific facility's ATC data
- [ ] Withing a VAMC Service on a Facility page, the current link to general ATC data is replaced with link to specific facility's ATC data

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [X] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by davidmpickett** [comment]
Example hyperlink ![access to care](https://user-images.githubusercontent.com/51967950/197564023-ca9e7217-60eb-4cca-8cee-c3d7866f5f5e.png)

**Comment by davidmpickett** [comment]
Example of service with ATC data ![screencapture-va-gov-chicago-health-care-locations-jesse-brown-department-of-veterans-affairs-medical-center-2022-10-24-10_28_11](https://user-images.githubusercontent.com/51967950/197566261-94eac6ae-8037-4955-97c8-11675da510d1.png)
