### ISSUE TITLE
CONSIDER: VA Provider Search

### ISSUE THREAD

**Issue by RWEagans** [department-of-veterans-affairs/va.gov-cms#10913]
## Description
ATC Provider search - https://www.accesstocare.va.gov/OurProviders/SearchResults#!#s=22&
Facility Locator has a Community Care provider search like this - [https://www.va.gov/find-locations/?page=1&address=21211&facilityType=provider&serv[…]01&context=Baltimore%2C%20Maryland%2021211%2C%20United%20States](https://www.va.gov/find-locations/?page=1&address=21211&facilityType=provider&serviceType=111N00000X&latitude=39.332501&longitude=-76.630577&radius=10&bounds%5B%5D=-77.380577&bounds%5B%5D=38.582501&bounds%5B%5D=-75.880577&bounds%5B%5D=40.082501&context=Baltimore%2C%20Maryland%2021211%2C%20United%20States)

Is there value in unifying them

## Acceptance Criteria
- [ ] Testable_Outcome_X
- [ ] Testable_Outcome_Y
- [ ] Testable_Outcome_Z
- [ ] Requires design review

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by mmiddaugh** [comment]
Closing as a duplicate to #10912
