### ISSUE TITLE
CMS: Add additional VBA fields to VBA Facilities 

### ISSUE THREAD

**Issue by JayDarnell** [department-of-veterans-affairs/va.gov-cms#10911]
## User Story or Problem Statement

#10504 identified additional fields we should add to the CMS to support the source VBA database. In this issue we will add the identified fields to pave the way for a migration which will ultimately bring that data into the CMS.

## Acceptance Criteria
- The fields (and content types) from the data model in #10504 have been added to the CMS
   - [ ] Services (field_vba_services)  (similar settings to field_vet_center_services) Entity reference to facility service,
   - [x] Page Introduction (field_intro_text)  plain text, just like vet center
   - [x] image (field_media) Similar setup to vetcenter 
   - [x] Shared VHA Location (field_shared_vha_location) (entity reference field autocomplete for VAMC and Vet Center facilities) Autocomplete.
   - [x] Parent Office (field_office) entity reference to vba facilities (select list)  Similar settings to field_office on vet center outstations (no winnowing logic needed at this time as they will be migrated.
   - [x] ~District (field_vba_district)~   This field is not needed and the value in the db will only be used to add facilities to the appropriate section:district in the migration.
   - [x] Non-VA Location Official Name (field_non_va_official_name)  plain text field
   - [x] Non VA Location URl  (field_non_va_location_external_url)  Link field with title.

## Design principles

Veteran-centered
- [x] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by swirtSJW** [comment]
Referrencing #10504

**Comment by swirtSJW** [comment]
I think we want to break this ticket into 3  This one should only address the facility fields and content type.  The other two should address the facility service and service taxonomy fields.

**Comment by omahane** [comment]
@swirtSJW 
<img width="1840" alt="Screen Shot 2022-10-12 at 2 20 01 PM" src="https://user-images.githubusercontent.com/766573/195429769-ecdd382c-82d2-4655-b996-c6cee1ab71dc.png">

**Comment by omahane** [comment]
Should I update the manage display and form display to mimic Vet Center as much as possible?
Also, should any of these fields be required?

Lastly, I was going to add Services when we create that content type, rather than as a part of this issue.

**Comment by JayDarnell** [comment]
@omahane I would say yes, try to update the display and form display to mimic Vet Centers as much as possible. I'm creating two spin-off tickets, one to add the new VBA Facility Services content type and another to update the taxonomy.
