### ISSUE TITLE
Change order of questions in Education How-to-apply wizard

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#10916]
## Description

9/26/22 – we heard from Dave/Beth that two steps in the Education How-to-apply wizard [on this page](https://www.va.gov/education/how-to-apply/) need to be switched. On 10/7 Wes met with stakeholders to validate that this ticket is correct.

[Mural board](https://app.mural.co/t/vagov6717/m/vagov6717/1664998387811/4be58c5f39967b921ca8cba2bfc77511b867eb00?sender=u907f83e01e35bb04de6f8139) showing current and new-state flows.

We're looking to switch the order of these 2:
- Is your sponsor deceased, 100% permanently disabled, MIA, or a POW?
- Has your sponsor transferred their benefits to you?

Note that these questions only display if previous questions are answered as depicted in the screenshot below.

So the logic will become:
- "Has sponsor transferred?"
  - Yes -> Stop and apply 
  - No -> Continue
- Is your sponsor deceased?
  - Yes -> Stop and Apply (i.e., widget displays the "Apply now" button)
  - No -> You need to transfer benefits warning
- On the "dead end" (if they answer No to the final question), we are going to remove the "Apply now" button that appears below the alert, as this points to an inappropriate action

### Existing react app screenshots:

Starts like this:
<img width="368" alt="image" src="https://user-images.githubusercontent.com/4054752/192384831-ac205d94-d3a0-4d5b-94bb-7ff732a97747.png">

Here, I answered some questions to get to the questions that need to be switched (bottom 2):
<img width="370" alt="image" src="https://user-images.githubusercontent.com/4054752/192384624-85f23f1e-a10e-4385-9467-74ba1f928b3e.png">

### Engineering Notes
`vets-website` file: `src/applications/edu-benefits/components/EducationWizard.jsx`.

These two `<RadioButtons>` components need to be swapped. Then, after swapping, the condition check (currently `sponsorDeceasedDisabledMIA === 'no' `) will need to be replaced to instead check `sponsorTransferredBenefits` since that control will now be the first of the two.
```
{serviceBenefitBasedOn === 'other' && (
  <RadioButtons
    additionalFieldsetClass="wizard-fieldset"
    name="sponsorDeceasedDisabledMIA"
    id="sponsorDeceasedDisabledMIA"
    options={[
      { label: 'Yes', value: 'yes' },
      { label: 'No', value: 'no' },
    ]}
    onValueChange={({ value }) =>
      this.answerQuestion('sponsorDeceasedDisabledMIA', value)
    }
    value={{ value: sponsorDeceasedDisabledMIA }}
    label="Is your sponsor deceased, 100% permanently disabled, MIA, or a POW?"
  />
)}
{sponsorDeceasedDisabledMIA === 'no' && (
  <RadioButtons
    name="sponsorTransferredBenefits"
    id="sponsorTransferredBenefits"
    options={[
      { label: 'Yes', value: 'yes' },
      { label: 'No', value: 'no' },
    ]}
    onValueChange={({ value }) =>
      this.answerQuestion('sponsorTransferredBenefits', value)
    }
    value={{ value: sponsorTransferredBenefits }}
    label="Has your sponsor transferred their benefits to you?"
  />
)}
```

## Acceptance Criteria
- [ ] The question about "transferred benefits to you" appears before "is sponsor deceased etc" question
- [ ] "Apply now" button is no longer present under the Alert at the "dead end" (if they answer No to the final question)
- [ ] Requires design/product review
- [ ] Loop back to EDU stakeholders to confirm fix and set KPI tracking cadence

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by laurwill** [comment]
Hi @wesrowe , just documenting some updates from the email chains with stakeholders Cinda and Tammy here. 
- Cinda noted that the problem isn't the order of the questions — it's that once the student says "yes" to either the TOE or DEA question, they're directed to a form with no awareness of a second option. We can't assume a student with dual eligibility would choose TOE over DEA.
- As you noted in your response, this work is blocked because switching the questions would shift pain from one group of unknown size to another.

**Comment by apisandipas** [comment]
@wesrowe @jilladams @ryguyk  I've completed the main ask of this ticket, e.g, the question reordering, hiding of the button on the final deadend etc. However, I'm blocked by a new Eslint rule asking us to migrate to the va-radio web component, as the RadioButton React component will be subset next month, as per https://dsva.slack.com/archives/C03R5SBELQM/p1666879267774979. I see we [have a ticket for auditing those radio buttons](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11358) in the unauth'd experience, but in the mean time, this ticket is a sprint priority. 

Shall we expand the scope of this ticket to include changing the radio buttons to use the web component? 
It's not an entirely trivial switch-out, as the component has a different API, including a sub-component that needs rendered for each option. It would likely at least double the points for the ticket to an 8.

**Comment by jilladams** [comment]
From scrum: 
* Leave Radio Buttons, to be addressed under #11358 
* Write an exception/override, to get this PR past that blocker

**Comment by wesrowe** [comment]
Reminder: notify stakeholders when this merges:

To: Randi, cc: Danielle, Dave; text: “Hi Tammy and Randi, Writing to let you know…”

**Comment by jilladams** [comment]
Post mortem draft: https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/pull/645

**Comment by jilladams** [comment]
This change was reverted from production. Restoring the change will happen via #11707 .
