### ISSUE TITLE
Security research and updates

### ISSUE THREAD

**Issue by cmaeng** [department-of-veterans-affairs/va.gov-cms#10924]
## Description
https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues?q=label%3Aincident+label%3Asecurity+label%3ACMS

need to be researched and addressed.

## Acceptance Criteria
- [ ] Testable_Outcome_X
- [ ] Testable_Outcome_Y
- [ ] Testable_Outcome_Z
- [ ] Requires design review

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [x] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by ElijahLynn** [comment]
I've left comments for the 4 issues needing research:
1. https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/589#issuecomment-1260011024
1. https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/581#issuecomment-1259782323
1. https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/583#issuecomment-1259777313
1. https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/582#issuecomment-1259777067

They are not current issues and do not need any further action.
