### ISSUE TITLE
Convert DataDog Alert Monitor CMS Time-Since-Last-Release to Terraform and Modify Downtime Window

### ISSUE THREAD

**Issue by olivereri** [department-of-veterans-affairs/va.gov-cms#10925]
## Description

Convert [CMS Time Since Last Content Release Monitor](https://vagov.ddog-gov.com/monitors/92535) to Terraform infrastructure code according to team best practice. Additionally, convert the 2 down time windows (weeday & weekend) that silence the alert to Terraform infrastructure code while narrowing the window to allow it to monitor failures from 8am to 8pm ET.

## Acceptance Criteria
- [ ] [CMS Time Since Last Content Release Monitor](https://vagov.ddog-gov.com/monitors/92535) is in Terraform
- [ ] Both [Downtime windows](https://vagov.ddog-gov.com/monitors/downtimes?q=%22cms%20time%20since%20last%20content%20release%20monitor%22&sort=-start_dt) are in Terraform
  - [x] Downtime Windows are adjusted to silence alerts ~~after 8pm ET and before 8am ET.~~
    - [x] Review [this slack thread](https://dsva.slack.com/archives/C03LFSPGV16/p1670443313333249?thread_ts=1670429469.566779&cid=C03LFSPGV16) for downtime configuration.

## Relations

https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10891

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [x] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by cmaeng** [comment]
holidays will not be considered under this work because the current paradigm has content releases running outside of the holiday code freeze schedule

**Comment by olivereri** [comment]
@timcosgrove Is there an other va.gov-cms issue that can be linked to this issue? One that has the final decision from @EWashb on adjusting content release alerting.

**Comment by EWashb** [comment]
@olivereri did you get what you need?

**Comment by olivereri** [comment]
> @olivereri did you get what you need?

Yes, thank you.
