### ISSUE TITLE
FE: Audit (technical) tables across VA.gov for 508 header considerations

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#10948]
## Description
Public Websites + Sitewide Content teams need identify all tables used in CMS & Front-end content.

#10793 tracks the CMS portion of the audit
This ticket represents the front-end work. 

## Scope
Once identified, SWC / PW will review the audit results to understand what tables:
1.  are misusing tables. PW will provide a list of tables, SWC identify which are in this list / are misusing, and will revise this content to stop using tables
2. are formatted correctly but have the wrong accessibility attributes
    * of these which ones are affected by / can be fixed by TableField patch vs.
    * can be fixed by template changes alone

This audit should include: 
* all tables present in the built VAgov website

This audit does not include: 
* CMS Paragraph tables, at any level of nesting - covered in #10793 
* WYSIWYG tables, if any

In the audit results, what we want to know about each table:
- Technical categories
  - FE template used for page
  - Does FE use [Design System table component](https://design.va.gov/components/table)?
    - If not, what if any reusable component does it leverage (or is it unique to the template)?
  - What products/content types each table is in (benefit hubs, VAMC, etc)?  Some may belong to Facilities.

## Acceptance Criteria
- [ ] Spreadsheet(s) (one or two) listing every FE hard-coded table on VAgov, along with the technical attributes listed above
  - [ ] When more than one table is present on a single page/URL, include each instance
  - [ ] Include some descriptive text if possible, perhaps there is a table header or caption you can grab?
- [ ] Insights about how many tables have each attribute (calculated by spreadsheet)
- [ ] Handoff meeting with @laflannery, who will do a subsequent content audit -- we should review the results of both FE / BE together, so this meeting should be scheduled only when both this ticket and #10793  are complete

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by wesrowe** [comment]
Decision in sprint 69 planning:
- This issue is probably not necessary. Ryan's notes in #10983 indicate where to look in vets-website. And the CMS audit view of #10793 should cover Drupal-driven tables.

**Comment by jilladams** [comment]
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10800#issuecomment-1318650289
Closing
