### ISSUE TITLE
Q&As F.E.: Add reusable Q&As to Benefit Details page template

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#10944]
### User story
 
**AS A** Veteran
**I WANT** Reusable Q&As to be available on Benefit Detail pages
**SO THAT** I benefit from the consistency of a single source of truth for answers to my questions.

## Acceptance criteria

- [x] Followed FE runbook created in #10937
- [x] Updated FE runbook to incorporate reusable Q&As in the order that they are entered in drupal (among content blocks)
- [x] Q&As entered into a new Q&A Group block in the list of Main Content blocks in the Benefit Details Drupal UI are displayed in the same order on Benefit Detail pages on FE
- [ ] Test coverage added as appropriate
- [ ] A11y review
- [ ] Verified that BE Q&As work is available (i.e., no longer hidden from Editors) in Prod

**Comment by chriskim2311** [comment]
For this ticket I have finished the code implementation. It is pending a code review and A11y review on the instance

**Comment by jilladams** [comment]
@chriskim2311 thanks for the update! I'm not seeing a PR link on here, weirdly - could you link to it? (PRs should get auto linked if you put "Relates to #10944" in the PR body.)

**Comment by chriskim2311** [comment]
@jilladams @wesrowe While @laflannery  was doing her A11y review she caught that the QA groups aren't displaying the accordions when checked off in the CMS. I saw that they were not set up to utilize the accordion option at all. Wondering if this is launch blocking or if we can cut a ticket for this feature?
![260790222-ba2b43c0-15e1-46b4-9705-9500ea8d1bb7.png](https://images.zenhubusercontent.com/64c007950ba949402482f884/90683b44-b94f-48d0-a3f3-59b5c2786997)?

**Comment by jilladams** [comment]
@chriskim2311 @laflannery Wes and I looked over this and need more detail. I _think_ you're saying: the FE isn't hooked up to handle the CMS preference to display these as accordions in the FE. If that's the case: that's a blocker. This same paradigm exists on Resources & Support, and FAQs, so there should be existing logic you can reference for handling it.  

If that's not what we're saying, can you share more detail about what's happening? Is it also not working in FAQ and R&S? Is this a higher level / component problem?

**Comment by chriskim2311** [comment]
Correct, FE was never set up to handle the accordions of the QA Groups. The change to allow the accordions will only need to happen in one place in the reusable template. I can have this completed this week, I was doing investigation today about implementation.

**Comment by jilladams** [comment]
Interesting! I feel like this already works on FAQs, but we'd need to find an example node where the Accordion box is checked on reusable Q&As to prove it. The examples I'm thinking of might all use old Q&A style and not reusables? 

To figure out if I'm wrong on FAQs, @dsasser  / @chri5tia might be able to help query for nodes where that box is checked, so you could cross-check in the FE.

**Comment by wesrowe** [comment]
Ticketed accordions as a follow-on, #14814.

**Comment by jilladams** [comment]
From planning: 
* Q&A Groups with reusable Q&A exist on FAQ, Resources & Support, and now Benefit Detail Pages
* Accordions were not implemented in the FE for R&S. Chris to confirm on FAQ. 
   * Change can be made in one place, and FAQ template may need refactored to account for one-stop editing this
* That's all tracked in #14814, so: this ticket could merge

**Comment by jilladams** [comment]
I let the content team know this is live! https://dsva.slack.com/archives/C01K37HRUAH/p1692223264477629
