### ISSUE TITLE
Cross team intake request: Sitewide CMS Table audits

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#10975]
## Overview
This is a template to be used by the Platform CMS, Accelerated Publishing, Public Websites, Facilities, Sitewide CMS, and CMS User Support teams in order to:
- help determine which team ought to do the work
- help any discussions at the PO or PM levels around scope and timeline
- help capture the needed information to make good decisions on prioritization by the intake team

Please be as detailed as possible knowing that any recommended path forward may change. This ticket will help give a baseline for discussions.

Please provide:

### Description of the problem / issue / enhancement
* https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10949
* https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10793

## Description of known dependencies
* Public Websites is doing the FE audit
* SItewide Content is doing the content audit from findings to remove tables that should no longer be tables

## Rough estimate of urgency and impact
* For PW, this is a 508 priority. The urgency of the audit needs to sit with Dave re: where Sitewide prioritizes the work relative to other things.
* Impact is for users with screen readers, where table rows are not clear.

## Acceptance Criteria
- [X] The Product Manager for the recommended intake team is pinged through Slack about the issue
- [ ] The Product Manager has discussed with the respective Product Owner to determine prioritization
- [ ] Any decisions made on prioritization or implementation are communicated back to the originating team

### CMS Team
Please check the team you project will do this work. If not sure, select "Program".

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [x] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by EWashb** [comment]
@jilladams the table audit from our end is complete. Are you ok if I remove myself as an assignee and remove the CMS label?

**Comment by jilladams** [comment]
AFAIK, everything here is done / no longer needed, and this can be closed.
