### ISSUE TITLE
Mega menu bottom padding missing on medium-sized screens.

### ISSUE THREAD

**Issue by ryguyk** [department-of-veterans-affairs/va.gov-cms#10977]
At the widest screen, the mega menu looks good:
![image.png](https://images.zenhubusercontent.com/5e274ecde33c5e16549a9361/5c08f153-415f-429d-a090-c76dc6220efd)

However, at smaller screen widths, things change:
![image.png](https://images.zenhubusercontent.com/5e274ecde33c5e16549a9361/95185cfe-8ece-4339-8bb8-e79b1bc35a3e
)

Here is the same issue shown with the new behavior of a non-expanded initial state (note that this defect is not a result of those changes):
![image.png](https://images.zenhubusercontent.com/5e274ecde33c5e16549a9361/30cd98c0-7dd6-4d5d-884b-cccd1ac1fb57)

**Comment by FranECross** [comment]
@randimays I closed the custom event ticket as we chatted about, and pulled this one in as an alternate for the current sprint. Thanks! cc @jilladams

**Comment by randimays** [comment]
Validated successfully in prod on va.gov and va.gov/health. Closing!
