### ISSUE TITLE
Redirect Request: Education rates pages

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-cms#10972]
### Instructions
- Requests must be submitted **AT LEAST** 2 weeks in advance.  Some requests take a significant amount of time and coordination to implement, so start the process as soon as you know you will need one. 
- This issue will be used from initial request through implementation to ensure all individuals working on this are notified of status updates.  Please do not create multiple issues to track differnt steps.
- It is your responsibility to notify VA stakeholders as appropriate.  

### Type of request
- [x] We are retiring or taking down a page and need to redirect the URL (complete redirect section)
- [ ] We are changing the URL of an existing page (complete redirect section)
- [ ] We need a custom vanity URL (complete vanity URL section)

### Implementation date
When does this request need to be live: We are hoping to launch the modernized rates pages the **week of 10/3** but we are still waiting for final stakeholder approval.

### Redirects 
Current URL  |  Redirect Destination or New URL
---  |  ---
https://www.benefits.va.gov/GIBILL/resources/benefits_resources/rates/ch33/ch33rates080122.asp | https://www.va.gov/education/benefit-rates/post-9-11-gi-bill-rates/
https://www.benefits.va.gov/GIBILL/resources/benefits_resources/rates/ch30/ch30rates100122.asp | https://www.va.gov/education/benefit-rates/montgomery-active-duty-rates/
https://www.benefits.va.gov/GIBILL/resources/benefits_resources/rates/ch1606/Ch1606rates100122.asp | https://www.va.gov/education/benefit-rates/montgomery-selected-reserve-rates
https://www.benefits.va.gov/GIBILL/resources/benefits_resources/rates/ch35/ch35rates100122.asp | https://www.va.gov/education/benefit-rates/chapter-35-rates
https://www.benefits.va.gov/gibill/resources/benefits_resources/rates/600_buyup.asp | https://www.va.gov/education/benefit-rates/montgomery-600-buy-up-rates
https://www.benefits.va.gov/GIBILL/resources/benefits_resources/rates/ch33/ch33rates080121.asp | https://www.va.gov/education/benefit-rates/post-9-11-gi-bill-rates/past-rates/
https://www.benefits.va.gov/GIBILL/resources/benefits_resources/rates/ch30/ch30rates100121.asp | https://www.va.gov/education/benefit-rates/montgomery-active-duty-rates/past-rates/
https://www.benefits.va.gov/GIBILL/resources/benefits_resources/rates/ch1606/Ch1606rates100121.asp | https://www.va.gov/education/benefit-rates/montgomery-selected-reserve-rates/past-rates/
https://www.benefits.va.gov/GIBILL/resources/benefits_resources/rates/ch35/ch35rates100121.asp | https://www.va.gov/education/benefit-rates/chapter-35-rates/past-rates/

### Vanity URLs 
Vanity URL  |  Landing page
---  |  ---
requested URL | landing page URL

**Link to campaign landing page request issue:**

### Process, Roles and Responsibilities
- [ ] Requesting team: Above information is provided
- [ ] Requesting team: All appropriate VA stakeholders are notified as appropriate
- [ ] IA: Request is vetted and documented and implementation plan is clear 
- [ ] IA: Request is assigned to appropriate team for implementation 
- [x] Implementation team: Work is complete
- [ ] Implementation team: Validated in production
- [ ] Requesting team: Validates everything is correct in production and closes ticket

**Comment by jilladams** [comment]
@RLHecht any news on this one?

**Comment by RLHecht** [comment]
@jilladams we got stakeholder feedback late last week so we are still making content changes. I should have a better sense after a meeting this afternoon and will post more here. Thanks!

**Comment by jilladams** [comment]
Beth confirmed this won't be ready this week. Punting back to Stretch, and adding to Sprint 69.

**Comment by jilladams** [comment]
@RLHecht @bethpottsVADEPO just checking in - any updates here re: education rates redirect?

**Comment by RLHecht** [comment]
@jilladams We are still on hold with the rates pages so there's nothing for Public Websites to handle at the moment with redirects. We are still working with stakeholders on several pages so there wouldn't be anything for you this sprint. Thanks for your patience with this one!

**Comment by RLHecht** [comment]
@jilladams We are getting a bit closer to publishing these rates pages though there are still some outstanding approvals from stakeholders. We may be able to get these live in the next couple weeks, so I wanted to get this redirect ticket back on your radar.

**Comment by jilladams** [comment]
Noted, just let us know when you're ready.

**Comment by RLHecht** [comment]
@jilladams We have a staging review set for 11/29 and are looking to publish the rates pages next week if all goes OK. Could you add this ticket into your next sprint?

**Comment by jilladams** [comment]
Yep! Whenever you're ready for it, we'll pull it in.

**Comment by RLHecht** [comment]
@jilladams our education rates pages are now live so these redirects are ready to go!

**Comment by jilladams** [comment]
Verified in prod.
