### ISSUE TITLE
Tugboat docker volume disk space at capacity

### ISSUE THREAD

**Issue by cmaeng** [department-of-veterans-affairs/va.gov-cms#10971]
## Description
We've been experiencing issues where disk space has run out for Tugboat. 

Verify any existing monitoring / sensors in Datadog that could alert for this and shore up as needed.

## Acceptance Criteria
- [ ] 

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by ElijahLynn** [comment]
This is resolved now. @q0rban provided some scripts to reclaim dangling docker images etc. in this [thread](https://dsva.slack.com/archives/C01A35JDH88/p1664470309927479). 

Before > After cleanup:
* 93% disk utilization (295GB free/4.11TB used) >> 59% (1.8TB free/2.6TB used)
* 594 images >> 252
* 432 containers >> 152

**Comment by ElijahLynn** [comment]
> Verify any existing monitoring / sensors in Datadog that could alert for this and shore up as needed.

**Comment by ElijahLynn** [comment]
Moved that part to a separate story: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10987
