### ISSUE TITLE
[tugboat] Disk space monitoring

### ISSUE THREAD

**Issue by ElijahLynn** [department-of-veterans-affairs/va.gov-cms#10987]
As a devops engineer, I need to know when Tugboat available disk space reaches 75% capacity so that I can take appropriate action to keep the service running for users without interruption. 

> Verify any existing monitoring / sensors in Datadog that could alert for this and shore up as needed.

_Originally posted by @ElijahLynn in https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10971#issuecomment-1263005202_

**Comment by EWashb** [comment]
@ndouglas am I wrong that you did some of this today with the fixes for the PHP issue? Wondering if this should still be open

**Comment by ndouglas** [comment]
No, it should be open. This is still an issue.

I think that what happens is that the base preview build will encounter an error, then attempt to rebuild _but leave an incomplete preview in place_, then repeat that until it fills up the disk.

The problem is that since we do the base preview early in the morning, it can fill up the disk by the time I get online 😵 and monitoring is thus not really sufficient by itself.

I need to think about it a bit.

**Comment by ElijahLynn** [comment]
I would still make this ticket about monitoring and alerting through PagerDuty once a threshold is reached. I think it should be 75% or lower. The alert should link to a runbook on action steps to take to free up the disk. 

You could still have another ticket to prevent this situation from happening. But regardless of this situation, an alert should be put into place because another situation could arise that causes runaway disk usage. In fact, it is probably only a matter of time.

**Comment by BerniXiongA6** [comment]
Hey @ariperez thanks for mentioning this at Team Scrum. Would you mind pointing this one (you can wait for @ndouglas if need be)? I added it as Ready for Sprint for S98. Thanks! cc: @maortiz-27-80

**Comment by ariperez** [comment]
@ndouglas , I believe this is g2g...https://vagov.ddog-gov.com/monitors/182018
<img width="1728" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/2553469/edfada60-09c2-4e15-b8cd-fd0b234fad53">

**Comment by BerniXiongA6** [comment]
Hey @ariperez @ndouglas I moved this over to Review/QA -- I think that's only 1 point left for review, yes? cc: @maortiz-27-80
