### ISSUE TITLE
Enable nightly facility migration

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#1099]
## User Story or Problem Statement

Facility data needs to be updated nightly. 

## Acceptance Criteria
- [x] Facilities are updated by migration on a regular basis, TBD. 
- [x] Slack notification fired for migration failures

## Implementation 
- [x] Nightly migration from Facility API
http://jenkins.vfs.va.gov/job/cms/job/cms-daily/
- [x] Facility status migrations every X from VHA asp files, NCA spreadsheet, etc.
http://jenkins.vfs.va.gov/job/cms/job/cms-periodic/

**Comment by kevwalsh** [comment]
@swirtSJW please confirm estimate with Elijah

**Comment by swirtSJW** [comment]
This is now done with both hourly and  nightly migrations running through jenkins
