### ISSUE TITLE
Automate delivery of Sitewide CMS ToT DataDog metrics

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-cms#10990]
## Description
I think I'll set up ToT metrics as a [scheduled report](https://docs.datadoghq.com/dashboards/scheduled_reports/).

This should be straightforward to set up in Terraform, but there's some risk.  It's also possible too that the format is undesirable, in which case this will need to be replaced by a new discovery ticket.

## Acceptance Criteria
- [ ] A scheduled report containing the Sitewide CMS ToT metrics is configured in Terraform to deliver to interested parties.

**Comment by ndouglas** [comment]
I lack the "Dashboard Report Write" permission, so I've asked for it [here](https://dsva.slack.com/archives/CBU0KDSB1/p1665506263296159).

**Comment by ndouglas** [comment]
Opened a ticket on the Max.gov Jira to discuss this [here](https://vajira.max.gov/servicedesk/customer/portal/1/DOTSD-19527).

**Comment by ndouglas** [comment]
Turns out I had the permission -- the problem arose because this isn't a feature yet on GovCloud :weary:

>(02:48:57 PM) Nathan Douglas: I'd like to send a scheduled report for a dashboard, but I don't see the option when I click the cog button on the dashboard. I've checked and my permissions include the "Dashboard Report Write" permission.

>(02:48:59 PM) Datadog Support: Please do not include sensitive system information or metadata in the chat feature with our Support team. Please use the ticketing system if you need to share system information to resolve your case.

>(02:49:09 PM) *** Walter Grebe joined the chat ***

>(02:49:37 PM) Walter Grebe: Hello, thanks for reaching out today! Please give me a few minutes to review your account and any existing tickets. In the meantime, can you share which dashboard this is?

>(02:49:46 PM) Nathan Douglas: yep, https://vagov.ddog-gov.com/dashboard/bsn-96m-ifn/sitewide-cms-tot-metrics?from_ts=1663512563185&to_ts=1666104563185&live=true

>(02:50:03 PM) Walter Grebe: Great, just give me a moment to take a look

>(02:59:45 PM) Walter Grebe: I took a look on my end and the reason the "Schedule a Report" option is not shown, is because this feature is currently not in Govcloud. I do see that there is a feature request for this at the moment, however there is no current timeline.

>If you would like, I can go ahead and make a new feature request on your behalf in order to show interest. Would this be something you would like to do?

>(03:00:34 PM) Nathan Douglas: That would be great!

>(03:01:13 PM) Walter Grebe: Of course! If possible, can you share the use case here?

>(03:02:50 PM) Nathan Douglas: Sure. It's pretty straightforward -- we're just using this dashboard (and ideally others) as ongoing background monitoring for things we're interested in, so getting a weekly dump of the data without having to log in is great. I was really excited to learn that this feature existed, since we're centralizing as much as possible of our metrics, events, etc in DD.

>(03:04:58 PM) Walter Grebe: Awesome! Thanks for the info here. I'll go ahead and open up the feature request, and follow up via email on the ticket thats automatically created.

>(03:05:10 PM) Nathan Douglas: Thanks, Walter. I appreciate that :-)

>(03:05:24 PM) Walter Grebe: No problem! Have a great day

**Comment by EWashb** [comment]
I'm going to move this back to refined since it is blocked
