### ISSUE TITLE
Implement PDF Cert Warning in Form Detail Page

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#11022]
***Must be deployed to Staging ONLY until collab cycle allows promotion to Prod***

## Description

As a Veteran, I want to be told that the form I'm looking at is at risk of not working correctly based on its issue_date, so that I can take appropriate action if it doesn't work right.

This alert is conditional on the `issue date` field, and should display for any form with issue date on or before 3/1/2022.

Background on how `last updated date` is calculated is available in [FaF docs here](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/find-a-va-form#date-contexts). (tl;dr: in front end we show the later of `Issue date` vs. `Revision date`. All banner calculations should use `issue date`.)

A [Mural](https://app.mural.co/invitation/mural/vagov6717/1664838770820?sender=u907f83e01e35bb04de6f8139&key=873b65dd-f04a-4c5a-bbbb-f8d668cdea90) covers the flow and analysis.

<img width="483" alt="image" src="https://user-images.githubusercontent.com/4054752/202323832-c97b4234-c0f3-46e8-8b71-aee9a8fa3831.png">

### Key implementation details

Use of Design System component `va-alert`:
- we're using the [va-alert web component](https://design.va.gov/storybook/?path=/docs/components-va-alert--default)?
- It is not dismissible
- Use the blue "info" type banner
- Copy provided via https://github.com/department-of-veterans-affairs/va.gov-team/issues/48458:
  - Heading: We’re updating this form
  - Body: If you download this form now, you won't be able to use it after January 7, 2023. You can download a new copy in January.

#### Accessibility note
We do NOT want a `role="alert"` attribute on our informational alert, as this would hijack reading order inappropriately (in this scenario) for screen readers. The design system docs reference it briefly [here](https://design.va.gov/components/alert#accessibility-considerations).
- example of how we want it: https://www.va.gov/records/download-va-letters/
- "don't" example: https://www.va.gov/disability/eligibility/

## Acceptance Criteria
- [ ] Flipper (same as for FaF Search page) prevents from showing in Prod
- [ ] Alert shows only if Flipper is set to true in the environment
- [x] Alert shows only if `issue date` is before <=3/1/22
- [x] Not dismissible
- [x] There is no `role="alert"` attribute
- [x] Requires design review - schedule meeting with Wes & @thejordanwood 
- [ ] Requires accessibility review by @laflannery. Can add her to the PR for awareness.

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by laurwill** [comment]
Hi @wesrowe ,
Just confirming a few details as we draft content:
- Will this alert show only on form detail pages with a "last updated" date before March 2022?
- Will the "last updated" date change when forms managers update the certificate?
- If the "last updated" date changes, will this alert then disappear?

Thank you!

**Comment by wesrowe** [comment]
Yes to all 3, @laurwill

**Comment by jtmst** [comment]
There are questions around whether or not a feature flag is appropriate for this work, or whether the collab cycle review can take place in the review instance.  For now the logic for gating this change from prod has been removed assuming that we can review from the PR review instance.

**Comment by wesrowe** [comment]
I tested with the two test forms that Josh posted. I want to review a few more forms but this will be stuck in PR for a wile anyway (Staging Review).

**Comment by wesrowe** [comment]
✅ Looks good in review instance – note that Jill and I discussed copy elsewhere. We'll go with this version so as not to commit to an unconfirmed Dec 15 deadline for Forms Managers to update all forms.

DO NOT MERGE, we want to hold this back for Staging Review etc.
