### ISSUE TITLE
Lovell Dev punch list

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#11026]
## Description
- [Tugboat](https://tugboat.vfs.va.gov/6335bde25121c36516d47d17)
   - [CMS](https://cms-liqqgmzl7tsyfbwyulbkuborufuuttav.demo.cms.va.gov) 
   - [Web Lovell VA](https://web-liqqgmzl7tsyfbwyulbkuborufuuttav.demo.cms.va.gov/lovell-federal-va-health-care/) 
   - [Web Lovell TRICARE](https://web-liqqgmzl7tsyfbwyulbkuborufuuttav.demo.cms.va.gov/lovell-federal-tricare-health-care/) 

The following punchlist items have been identified as items to be fixed with Lovell

## MVP
<details><summary>Completed Items</summary>

- [x] #11027
- [x] #11155
- [x] #11212
- [x] #11214
- [x] #11215
- [x] #11373
- [x] #11374
- [x] #11375
- [x] #11069
- [x] #11636
- [x] #11686
- [x] #11688
- [x] #11691
- [x] Some discrepancies with the menu.  Contact us, Policies page...  Compared the structure to other VAMCs and corrected the menu to match. --- Just disabled these two menu items to match other system menus.
- [x] “Operating status”  is listed in the left-nav for Lovell VA and Lovell Tricare — this is non-standard amongst VAMCs, These should be removed in a manner similar to how other systems are running.
- [x] CMS James A Lovell facility should have matching sub paths
- [x] #11850
- [x] CMS Lovell Federal Health Care should be unpublished - Added as step to runbook
- [x] #11557
- [x] #11832
 - [x] #11829
- [x] #11830
- [x] #11828
</details>

### Refined
- [x] #11940
- [x] #12011 
- [x] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12069
- [x] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12108

### Unticketed

- [ ] ~FE James A Lovell Facility should have switch links (possibly resolved by merge of #11691?)~ This looks to be resolved.
   - ~/lovell-federal-tricare-health-care/locations/captain-james-a-lovell-federal-health-care-center~
   - ~/lovell-federal-va-health-care/locations/captain-james-a-lovell-federal-health-care-center~

## Post MVP 
- [ ] #11939
- [ ] #11941

**Comment by davidmpickett** [comment]
Captain James A. Lovell Federal TRICARE Health Care Center & Captain James A. Lovell Federal VA Health Care Center should have a switch link to each other. This is one of the most important places for the link to appear as this is the location that serves both audiences.

The link isn't appearing because these locations have different end URLs. Propose renaming the TRICARE variant to match the VA version

captain-james-a-lovell-federal-health-care-center
captain-james-a-lovell-federal-tricare-health-care-center

**Comment by JayDarnell** [comment]
Potential future item (not MVP): 

For list pages (stories, events, etc) assigned to the parent system (Lovell Federal health care) we should hide the VA.gov URL notices from the node view (They are currently, perpetually, marked as pending)

**Comment by omahane** [comment]
On this page:
[lovell-federal-va-health-care/about-us](https://cms-liqqgmzl7tsyfbwyulbkuborufuuttav.demo.cms.va.gov/lovell-federal-va-health-care/about-us), the [https://web-liqqgmzl7tsyfbwyulbkuborufuuttav.demo.cms.va.gov/lovell-federal-tricare-health-care/about-us](https://web-liqqgmzl7tsyfbwyulbkuborufuuttav.demo.cms.va.gov/lovell-federal-tricare-health-care/about-us) page is not showing.
<img width="1728" alt="Screen Shot 2022-12-06 at 2 18 03 PM" src="https://user-images.githubusercontent.com/766573/206014477-fc88509e-2311-4f3c-b25b-7fbe885acdcf.png">

**Comment by JayDarnell** [comment]
Remove "Other nearby VA locations" from the bottom of the locations page for Lovell Federal TRICARE health care.

https://web-liqqgmzl7tsyfbwyulbkuborufuuttav.demo.cms.va.gov/lovell-federal-tricare-health-care/locations/
![Screenshot 2022-12-06 at 3 27 48 PM](https://user-images.githubusercontent.com/21045418/206015860-253dd580-2757-407a-bf16-ab004828eb91.png)

**Comment by davidmpickett** [comment]
> On tricare pages the menu item for Health services should come before locations. (validated it is right in the CMS, so this is FE issue)

Additional nuance for this bullet point is that Health Service is showing up as a sub-item of Locations

![Screenshot 2022-12-06 143328](https://user-images.githubusercontent.com/51967950/206017033-56c672ae-1067-49b6-8720-7689a88055ac.png)

**Comment by omahane** [comment]
Need to set the Operating Status for [Lovell Tricare](https://cms-liqqgmzl7tsyfbwyulbkuborufuuttav.demo.cms.va.gov/node/49011/edit)
<img width="976" alt="Screen Shot 2022-12-06 at 2 38 27 PM" src="https://user-images.githubusercontent.com/766573/206017959-adeed2bb-dc93-4f0b-82d3-d224e2858dba.png">

**Comment by JayDarnell** [comment]
New punch list item. We need to be sure the menu items for the system health services under both Lovell VA and Lovell TRICARE are disabled. In the following screenshot the suicide prevention health service is listed in the menu:

![Screenshot 2022-12-06 at 3 41 54 PM](https://user-images.githubusercontent.com/21045418/206018641-34cb1151-4345-4189-ab67-f53cee6c8f6f.png)

**Comment by maxx1128** [comment]
> > On tricare pages the menu item for Health services should come before locations. (validated it is right in the CMS, so this is FE issue)
> 
> Additional nuance for this bullet point is that Health Service is showing up as a sub-item of Locations
> 
> ![Screenshot 2022-12-06 143328](https://user-images.githubusercontent.com/51967950/206017033-56c672ae-1067-49b6-8720-7689a88055ac.png)

Also related to this, all the Locations menu links are also appearing as Health Services links. This could be some menu duplication issues.

<img width="1014" alt="Screen Shot 2022-12-06 at 3 41 28 PM" src="https://user-images.githubusercontent.com/10790736/206018975-997370a0-a4e4-4105-951a-add78d0f661f.png">

**Comment by davidmpickett** [comment]
TRICARE System Page - "Manage your health online" - should this whole thing be hidden for TRICARE since these are all hardcoded VA links?

**Comment by maxx1128** [comment]
Lovell federal pages should be checked if they have `va` in the CMS URL. This could potentially be creating a bug where federal pages aren't being properly cloned for the Tricare side, hence why so many of those pages have correct menu links but no actual pages.

**Comment by JayDarnell** [comment]
> On this page: [lovell-federal-va-health-care/about-us](https://cms-liqqgmzl7tsyfbwyulbkuborufuuttav.demo.cms.va.gov/lovell-federal-va-health-care/about-us), the https://web-liqqgmzl7tsyfbwyulbkuborufuuttav.demo.cms.va.gov/lovell-federal-tricare-health-care/about-us page is not showing. <img alt="Screen Shot 2022-12-06 at 2 18 03 PM" width="1728" src="https://user-images.githubusercontent.com/766573/206014477-fc88509e-2311-4f3c-b25b-7fbe885acdcf.png">

The subpages are also failing

**Comment by maxx1128** [comment]
I did a quick filter to see which cloned Tricare pages had the incorrect URL structure with `lovell-federal-va-health-care'` in it, and it was basically all of them (see titles below). I'm going to try and tweak the build process to catch and correct this bug, and see if it fixes the related switch link bug.

```
[
  'Make an appointment',
  'DAV vans: Transportation for Veterans',
  'Pharmacy',
  'Campus map',
  'Chaplain service',
  'Caregiver support',
  'Homeless Veteran care',
  'LGBTQ+ Veteran care',
  'Suicide prevention',
  'Mental health care',
  'Minority Veteran care',
  'Patient advocates',
  'Returning service member care',
  'Women Veteran care',
  'COVID-19 vaccines',
  'About us',
  'Work with us',
  'Contact us',
  'Programs',
  'Research',
  'Mission and vision',
  'History',
  'Jobs and careers',
  'Internships and fellowships',
  'Volunteer or donate',
  'Doing business with us',
  'Test Event 1 Both',
  'Test Event 2 Both',
  'Leadership',
  'Lovell Federal TRICARE health care Placeholder - Event',
  'TEST A press release for BOTH LOVELL',
  'TEST story for BOTH Lovell',
  'Kristina Naidicz',
  'Sarah Bognanno',
  'Jennifer Corrao',
  'Kim Jones',
  'Alfreda Rhodes-King',
  'Kristina Lecce',
  'Irma A. Sharp',
  'Robert Buckley',
  'Thomas J. Nelson',
  'Mamata Ravipati',
  'Jeremy Hawker',
  'Veronica L. Brittenum',
  'Sharee Taylor',
  'Michael Simmons',
  'Jeremy Pyles',
  'Kathleen Kennedy'
]
```

**Comment by swirtSJW** [comment]
> I did a quick filter to see which cloned Tricare pages had the incorrect URL structure with `lovell-federal-va-health-care'` in it, and it was basically all of them (see titles below). I'm going to try and tweak the build process to catch and correct this bug, and see if it fixes the related switch link bug.
> 
> ```
> [
>   'Make an appointment',
>   'DAV vans: Transportation for Veterans',
>   'Pharmacy',
>   'Campus map',
>   'Chaplain service',
>   'Caregiver support',
>   'Homeless Veteran care',
>   'LGBTQ+ Veteran care',
>   'Suicide prevention',
>   'Mental health care',
>   'Minority Veteran care',
>   'Patient advocates',
>   'Returning service member care',
>   'Women Veteran care',
>   'COVID-19 vaccines',
>   'About us',
>   'Work with us',
>   'Contact us',
>   'Programs',
>   'Research',
>   'Mission and vision',
>   'History',
>   'Jobs and careers',
>   'Internships and fellowships',
>   'Volunteer or donate',
>   'Doing business with us',
>   'Test Event 1 Both',
>   'Test Event 2 Both',
>   'Leadership',
>   'Lovell Federal TRICARE health care Placeholder - Event',
>   'TEST A press release for BOTH LOVELL',
>   'TEST story for BOTH Lovell',
>   'Kristina Naidicz',
>   'Sarah Bognanno',
>   'Jennifer Corrao',
>   'Kim Jones',
>   'Alfreda Rhodes-King',
>   'Kristina Lecce',
>   'Irma A. Sharp',
>   'Robert Buckley',
>   'Thomas J. Nelson',
>   'Mamata Ravipati',
>   'Jeremy Hawker',
>   'Veronica L. Brittenum',
>   'Sharee Taylor',
>   'Michael Simmons',
>   'Jeremy Pyles',
>   'Kathleen Kennedy'
> ]
> ```
@maxx1128   Nice work.  This is the related ticket  I think
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11828

I think it boils down to that we have to use field _administration (section) to be the source of truth on where a page should appear, and not the path it originally comes in with.

**Comment by omahane** [comment]
@davidmpickett Does Lovell have any other social media links that we know of?
We have:
Facebook: https://www.facebook.com/lovellfhcc
Twitter: https://twitter.com/lovellfhcc

Those are the only Lovell specific ones. 

The other two on [their current page](https://www.lovell.fhcc.va.gov/index.asp) are more general:
Flickr: https://www.flickr.com/photos/veteranshealth
Instagram: https://www.instagram.com/deptvetaffairs/
<img width="206" alt="Screen Shot 2022-12-09 at 9 25 46 AM" src="https://user-images.githubusercontent.com/766573/206736616-5e4bb5a9-8856-4dc3-97b5-52bc005d35b7.png">

Lastly, I don't suppose we know of any Lovell TRICARE or Lovell VA specific accounts, do we?

**Comment by davidmpickett** [comment]
@christianmburk  I don't have any particular insight into their social media. Quick glance seems like they might treat it as a unified presence. I see reposts of VA and DoD in their feed.

**Comment by omahane** [comment]
> Quick glance seems like they might treat it as a unified presence.
Do you think we should use those links that are on the current live Lovell system site and put them in both VA and TRICARE system pages?

**Comment by davidmpickett** [comment]
I just added some additional structure to the punchlist:
- Completed Items now hidden in a dooblydoo
- Uncompleted items now broken into three sections based on refinement

**Comment by davidmpickett** [comment]
Just uncovered a pretty concerning issue with VAMC Facility Health Services. There doesn't seem to be any logic preventing editors from mixing and matching Facilities, Systems, and Sections. 

I was able to save a Facility Health Service on staging as nickolas.sanchez@va.gov in a variety of mismatched ways

![Screen Shot 2022-12-15 at 4 33 39 PM](https://user-images.githubusercontent.com/51967950/207982001-ee09f465-7b39-47aa-b5ef-5859907225db.png)

![Screen Shot 2022-12-15 at 4 34 26 PM](https://user-images.githubusercontent.com/51967950/207982036-cf30edf5-be6f-4348-b3d6-06c3fe5bf1cd.png)

![Screen Shot 2022-12-15 at 4 36 43 PM](https://user-images.githubusercontent.com/51967950/207982061-6bf9d216-9fd5-4956-9224-02542626f2fb.png)

**Comment by maxx1128** [comment]
One refactor that should be tackled in the near future: the `getModifiedLovellPage` function has a lot of logic around changing the entity URL. This logic should be streamlined/separated to keep it cleaner and remove any unneeded conditions.
 
https://github.com/department-of-veterans-affairs/content-build/pull/1399#pullrequestreview-1218230040

**Comment by davidmpickett** [comment]
I am closing this as most of the issues have been resolved and the other issues have their own tickets
