### ISSUE TITLE
(Fallback) CMS Add PACT Act to list of Related Benefits on Publication

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#11037]
## Description
As an editor of a Publication I need to be able to classify it as "PACT Act" so that people can find it easily on VA.gov

![image](https://user-images.githubusercontent.com/5752113/193645403-e8d7df51-4c4f-4741-8267-11882ccfcfac.png)

Related conversation in [CMS Support slack](https://dsva.slack.com/archives/CDHBKAL9W/p1664557639118529)
related conversation in [PWS slack](https://dsva.slack.com/archives/C52CL1PKQ/p1664815998053199) 

## Related tickets
#11038 will update the front-end filter

## Acceptance Criteria
- [ ] /admin/structure/types/manage/outreach_asset/fields/node.outreach_asset.field_benefits/storage contains `pact_act|PACT Act` inbetween insurance and pension.
- [ ] List is alphabetized

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by swirtSJW** [comment]
This ticket is likely to be superceded by the Outreach materials epic.  It is kept around for now just in case we need a fast fix for PACT Act

**Comment by wesrowe** [comment]
Closing since we did this the "right" way.
