### ISSUE TITLE
Redirect Request: Flu vaccine CLP

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-cms#11036]
### Instructions
- Requests must be submitted **AT LEAST** 2 weeks in advance.  Some requests take a significant amount of time and coordination to implement, so start the process as soon as you know you will need one. 
- This issue will be used from initial request through implementation to ensure all individuals working on this are notified of status updates.  Please do not create multiple issues to track differnt steps.
- It is your responsibility to notify VA stakeholders as appropriate.  

### Type of request
- [ ] We are retiring or taking down a page and need to redirect the URL (complete redirect section)
- [x] We are changing the URL of an existing page (complete redirect section)
- [x] We need a custom vanity URL (complete vanity URL section)

### Implementation date
When does this request need to be live: As soon as the team can do it.

Danielle said this is going to be a temporary redirect of the vanity url.[Slack for background.](https://dsva.slack.com/archives/C01K37HRUAH/p1664544567372379)

Note that the current url listed below is already a vanity url and we are changing it to a different vanity url. 

### Redirects 
Current URL  |  Redirect Destination or New URL
---  |  ---
https://www.va.gov/flu-shot  | https://www.prevention.va.gov/flu/

### Vanity URLs 
Vanity URL  |  Landing page
---  |  ---
requested URL | landing page URL

**Link to campaign landing page request issue:**

### Process, Roles and Responsibilities
- [ ] Requesting team: Above information is provided
- [ ] Requesting team: All appropriate VA stakeholders are notified as appropriate
- [ ] IA: Request is vetted and documented and implementation plan is clear 
- [ ] IA: Request is assigned to appropriate team for implementation 
- [ ] Implementation team: Work is complete
- [ ] Implementation team: Validated in production
- [ ] Requesting team: Validates everything is correct in production and closes ticket

**Comment by heyjoni** [comment]
New vanity URL looks fine as a temporary redirect and was confirmed with Mikki, Dave, and Danielle per the Slack thread.

**Comment by jilladams** [comment]
This change has been deployed. Currently https://www.va.gov/flu-shot is landing on https://www.va.gov/initiatives/flu/, and not pointing to https://www.prevention.va.gov/flu/. This change was deployed 2 hours ago, so there's a chance that this is a DNS propagation issue and will resolve itself in the next ~24h. Will confirm if so or if not.

**Comment by jilladams** [comment]
Checked today, still not redirecting. If true tomorrow still, I'll reopen for investigation.

**Comment by jilladams** [comment]
We now have a true mystery: 
* Commit to remove the old redirect to https://www.va.gov/initiatives/flu/ has merged 
* And deployed: http://jenkins.vfs.va.gov/job/deploys/job/revproxy-vagov-prod/486/
* But https://www.va.gov/flu-shot is still redirecting to the Initiatives path

I looked in Drupal to see if maybe there's a path set on the node itself that is affecting things but I do not find a CLP or a Sitewide Content node for Flu shot. @heyjoni @mnorthuis could you point me to the Drupal node for this /flu-shot content, if it exists? If it's not a Drupal node, any tips on how this content originated would be helpful so we can try to sort out why this isn't working.

**Comment by jilladams** [comment]
Nevermind! Found it: https://prod.cms.va.gov/node/36787/edit

The path on this node is set to `/initiatives/flu`. So I _think_ what we need now is (sorry Bryan!) a 2nd redirect added: 


Current URL | Redirect Destination or New URL
-- | --
https://www.va.gov//initiatives/flu | https://www.prevention.va.gov/flu/

@mnorthuis @heyjoni could you confirm that makes sense to you?

**Comment by jilladams** [comment]
Nevermind it's working now. Boo, DNS.
