### ISSUE TITLE
Implement Character Limit on VAMC System Banner Alert with Situation Updates (full width banners on VAMC Product) 

### ISSUE THREAD

**Issue by JayDarnell** [department-of-veterans-affairs/va.gov-cms#11039]
## User Story or Problem Statement

The use of extremely long banner alerts can make for an unfavourable veteran experience. We need to take steps to keep these alerts as succinct as possible. There are currently no size limitations on the text fields for this content type. Looking at the Full  Width Alert content type as a comparison, the body field has a limit of 1000 characters. 

UPDATE: Our agreed upon character limit is 300 if HTML code is not counted as part of the character count, 500 if it is.

## Acceptance Criteria  
- [x] I expect the limited rich text editor is implemented on **Alert body** (field_body) field
- [x] I expect only limited rich text editor will be available and full rich text editor will be removed 
- [x] I expect the **Alert body** (field_body) field is limited to 300 characters (hard limit, meaning the editor cannot go over the 300 character limit)

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by dsinla** [comment]
Per @swirtSJW - the lift is minor, easy to implement when we want to flip the switch.  The big deal here is all the CM with VHADM.

**Comment by davidmpickett** [comment]
Definitely not happening in Sprint 70 given the huge CM dependency.

**Comment by kmariepat-cityfriends** [comment]
reference a tweet length for ideal character limit

**Comment by kmariepat-cityfriends** [comment]
![Screenshot 2023-04-27 at 2.48.19 PM.png](https://images.zenhubusercontent.com/63e52fa5902d473d543262ff/cc59d960-db3e-402a-9368-25382981fc90)

**Comment by kmariepat-cityfriends** [comment]
Validate that this remains specific to that, AC around ensuring the scope is just VAMC system banner alerts

**Comment by kmariepat-cityfriends** [comment]
Next steps: 
- confirm location of this PR; Update permissions so editors can no longer edit VAMC System Banner Alerts with Situation Updates once they have been archived~  unrelated and covered by #8141  I'm (swirt) not seeing a good reason to entangle these.
- update defect card to dis

**Comment by kmariepat-cityfriends** [comment]
The change management is not complete and planned for later this month of June, marking as do not merge

**Comment by omahane** [comment]
@kmariepat-cityfriends Are we at all concerned that this is a sprint goal that is blocked by change management?

**Comment by jilladams** [comment]
From scrum yesterday: Sprint goal can close as defined.

Need a follow up ticket to merge Implement Character Limit on VAMC System Banner Alert with Situation Updates (full width banners on VAMC Product) when VHADM approves, @kmariepat-cityfriends will make.

**Comment by jilladams** [comment]
Cut the follow up ticket, closing.
