### ISSUE TITLE
(Fallback) FE Filter on Outreach Materials needs PACT Act added.

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#11038]
## Description
Related to https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11037

As a Veteran, I need to be able to filter by "Pact Act" to easily surface materials that apply to me.

The pact_act|PACT Act selection is being added on the CMS side (#11037), this is the FE ticket to surface the filter value on https://www.va.gov/outreach-and-events/outreach-materials/

![image](https://user-images.githubusercontent.com/5752113/193647836-2d5cf2d4-3712-430d-a6b1-89ebc37de516.png)

Related conversation in [CMS Support slack](https://dsva.slack.com/archives/CDHBKAL9W/p1664557639118529)
related conversation in [PW slack](https://dsva.slack.com/archives/C52CL1PKQ/p1664815998053199) 

Template in question: `content-build/src/site/layouts/publication_listing.drupal.liquid`. This list is hard coded and currently not alphabetized - we should alphabetize in this ticket's work.

## Acceptance Criteria
- [ ] PACT Act shows as a filter option under "Select a topic" on https://www.va.gov/outreach-and-events/outreach-materials/
- [ ] List is alphabetized
- [ ] Bonus points for making it non-hardcoded BUT speed is important and it should not slow this ticket down.

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [X] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by jilladams** [comment]
@DanielleThierryUSDSVA the Outreach Materials filter dropdown list is not alphabetized and seems like it could / should be. Are there strong reasons from a content perspective, re: relevance etc, not to alphabetize while we are in here?

**Comment by DanielleThierryUSDSVA** [comment]
Hi @jilladams. I'm always in favor of alphabetizing lists like these. I haven't been involved in outreach hub to date so I don't know if there was a reason for the original ordering, but I'm not opposed at all to alphabetizing. Thanks!

**Comment by swirtSJW** [comment]
This ticket is likely to be superceded by the rest of the Outreach materials epic.  It is kept around for now just in case we need a fast fix for PACT Act

**Comment by wesrowe** [comment]
Closing as we did this work the "right" way.
