### ISSUE TITLE
CMS: limit the number of VAMC System Banner Alerts with Situation Updates per system

### ISSUE THREAD

**Issue by JayDarnell** [department-of-veterans-affairs/va.gov-cms#11040]
## User Story or Problem Statement

The use of multiple long banner alerts per system can make for an unfavourable veteran experience. We need to take steps to be sure banner alerts aren't misused. There are currently no limits in terms of how many banner alerts a given system can have and no notifications for editors to let them know how many they have.

## Proposed Solution

We have two potential paths we could take. 

**Limit the number of banners per system**

This path is potentially problematic. Assuming we can write the necessary logic to do this there are many things to consider:

- Do we simply show the most recently updated banner(s) - (a single banner? 1-3 banners)?
- Do we need to provide an interface to shuffle the available banners by priority?
- How do we prioritize banners added by an editor at the Facility level vs an editor at the System level? What if the system level item is "more important" but then the facility experiences an active shooter?

**Notify editors how many banners their system currently has**

Alternatively we could leave the responsibility in the hands of the editors and merely notify them. We could have some sort of CMS (backend) notification appear on their dashboard or on every page letting them know they have X number of active banners with some brief text and a link to a KB article discussing proper banner usage. Or we could simply display this sort of notification when they go to edit or add a banner.

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by swirtSJW** [comment]
This could largely be handled by applying "Allow only one" to the combination of `field_administration` and `field_banner_alert_vamcs`

However, in order for this to work.  Allow only one would have to apply and enforce published pages only.  Here is the upstream issue for that. https://www.drupal.org/project/allow_only_one/issues/3313753

This methodology would allow VISNs or higher to add a banner without blocking a system from adding a banner.

**Comment by JayDarnell** [comment]
@swirtSJW I've submitted a patch for the allow_only_one module: https://www.drupal.org/project/allow_only_one/issues/3313753#comment-14753603

Once this has been merged and a new version of the module has been made available and dependabot has updated our codebase with this new version I can take the final steps to set up the limitations for our alerts as outlined above.

**Comment by jilladams** [comment]
Patch was merged into 1.0.1: https://www.drupal.org/project/allow_only_one/issues/3313753#comment-14753603

**Comment by dsinla** [comment]
| Coranavirus Vaccine Available/Not Avail            | 68 |
| -------------------------------------------------- | -- |
| Website Coming Soon                                | 50 |
| Coronavirus Levels/Facilty Policy (service animal) | 36 |
| Non-Covid Vaccine                                  | 7  |
| Weather closing/opening                            | 7  |
| Coranavirus Testing availability                   | 5  |
| Phone  upgrade/outage/restored                     | 5  |
| Weather advisory - be prepared                     | 5  |
| Facility status/closure/waittimes (construction)   | 5  |
| Non Covid visitation policy                        | 2  |
| Holiday closure                                    | 2  |
| Facility status/closure (incident)                 | 2  |
| Recruiting/Hiring                                  | 2  |
| UNKOWN                                             | 2  |
| Location/address change                            | 1  |
| Quick and useful info                              | 1  |
| Happy Veterans Day                                 | 1  |
| In The Know - Various notices                      | 1  |
