### ISSUE TITLE
Forms: Update "Form last updated" label on Form search results & Form detail page; use only revision date to populate

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#11047]
## Status
**[2024-08-21] [Fran]** Added two sections "Problem to be Solved' and 'Solution', as well as updated the AC. Ready for refining.
**[2024-08-14] [Fran]** Added to Next Refinement per Michelle's feedback to my question: I think it's worth refining to understand what our options are and the effort needed, and agree that forms should not be rejected or denied for this reason, if we can do something to avoid that outcome.
**[2024-08-09] [Fran]** Added to the [Product Sync Slack list](https://dsva.slack.com/lists/T03FECE8V/F07BVDGCY8H?record_id=Rec07H00QB2E4) for Michelle to review and pinged her in a comment with short explanation.

## Problem to be Solved
The Form last updated field displaying on both the Find a form search results page, and on the Form detail page can be updated both by the actual form revision date, or by the date the form is uploaded, or reuploaded.

## Solution
The labels on both the Find a form search results page and the Form detail page will be updated to say 'Form revision date', and the date that populates this field will ONLY be the Revision date. 

## Description
We heard from Janel Keyes (Forms Mgr) that some field offices seem to be using the "Form last updated" field within [Find-a-form on VAgov](https://www.va.gov/find-forms/) to check the validity of forms they receive from Veterans. In so doing they are assuming the field means the "major version" date, which would be meaningful to them as a reason to reject an outdated form. 

Form search and Form detail pages currently show a "Form last updated" date as "month year". (See screenshots below)

Possible solutions to unnecessary form rejections:
- train VA internal users on how to correctly identify the validity of a form instead of relying on dates in Find-a-form
- update the label to be clearer to VA internal folks _without confusing Veterans_
- show both dates that are available from the Forms DB (issue date and revision date), _without confusing veterans_

If we choose to make a change, we would update both Find a Form search page and on Form detail pages.

## Additional context
Usage of Issue date / Revision date in the Forms DB, is documented here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-a-va-form/engineering/data/data.md#date-contexts

### Updated copy
TBD

### Screenshots of current implementation
<details> 
<summary>Find a form Search results</summary>

![Find a form search.png](https://images.zenhubusercontent.com/624dd6bb7d958ceb206d043b/57064792-4dd0-4ea2-b09a-e416461b6427)
</details> 

<details> 
<summary>Form detail page</summary>

![Form detail page.png](https://images.zenhubusercontent.com/624dd6bb7d958ceb206d043b/c8b35947-ba30-42ba-b304-83e9651ba89c)
</details> 

### **Data**
In terms of data that is presented, the Forms DB contains 2 dates that are migrated into the Drupal CMS: 
* Revision date 
* Issue date

In the front-end, we display the later/most-recent of those 2 dates: 
https://github.com/department-of-veterans-affairs/content-build/blob/main/src/site/layouts/va_form.drupal.liquid#L61

#### Relevant Data Logic (from Michelle M)
2 dates are migrated from DB to Drupal: 

- Revision date - the date when the form was created
  - this date is also shown on the form itself in the lower left hand corner this date is owned by the contractor who makes changes/edits to the actual form. Revision date is manually updated in the Forms DB. Veterans submitting a form using an old revision may be required to re-submit using the latest revision

- Issue date - the date that updated form is uploaded to the Form DB
  - increments anytime the Revision Date increments; may also increment for background changes that do not change the Revision Date, such as updating Adobe certificates for the PDF. Issue date is manually entered in Forms DB, so in some cases a PDF may get updated without Issue Date reflecting a change. 
  
- Front-end display - The Find a Form product displays a single date, with the label "Last updated date:". This date is a calculation of whichever date is later between Revision and Issue dates

```
{% assign revisionDateIsLatestUpdate = fieldVaFormRevisionDate.value | isLaterThan: fieldVaFormIssueDate.value %}
{% if revisionDateIsLatestUpdate %}
  {{ fieldVaFormRevisionDate.value | humanizeDate }}
{% else %}
  {{ fieldVaFormIssueDate.value | humanizeDate }}
{% endif %}
```

## Additional context 
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9607#issuecomment-1179352156 -- Backend assessment of date handling in Forms DB migration into Drupal

## Acceptance Criteria
- [ ] Label on Find a form search results is updated to say Form revision date
  - [ ] Date that populates this field is ONLY the Revision date field
- [ ] Label on Form detail page is updated to say Form revision date
  - [ ] Date that populates this field is ONLY the Revision date field
- [x] [Forms date context documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-a-va-form/engineering/data/data.md#date-contexts) is updated to reflect these changes

## Post-release
- [ ]  @FranECross to close the loop with Tricia Baker on this [Slack](https://dsva.slack.com/archives/C52CL1PKQ/p1724876064322999) thread
- [ ] @FranECross to inform Kayce White

**Comment by mmiddaugh** [comment]
Capturing relevant date logic here:
2 dates are migrated from DB to Drupal:

`Revision date` - the date when the form was created 
- this date is also shown on the form itself in the lower left hand corner
- this date is owned by the contractor who makes changes/edits to the actual form
- revision date is manually updated in the Forms DB
- Veterans submitting a form using an old revision may be required to re-submit using the latest revision
 
`Issue date` - the date that updated form is uploaded to the Form DB
- increments anytime the Revision Date increments
- may also increment for background changes that do not change the Revision Date, such as updating Adobe certificates for the PDF
- Issue date is manually entered in Forms DB, so in some cases a PDF may get updated without Issue Date reflecting a change

Front-end display - The Find a Form product displays a single date, with the label "Last updated date:". This date is a calculation of whichever date is later between Revision and Issue dates

**Comment by jilladams** [comment]
FYI: the Forms team (who are digitizing PDFs to make online submission forms for them) got feedback from someone who helps manage Form 21-4142 that they would prefer the Revision date be what's displayed on the FE. That aligns with where this is headed, so far.

**Comment by jilladams** [comment]
(Added an AC to update the Forms date info in docs: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-a-va-form/engineering/data/data.md#date-contexts)

**Comment by randimays** [comment]
[Forms date context documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-a-va-form/engineering/data/data.md) is updated via [this commit](https://github.com/department-of-veterans-affairs/va.gov-team/commit/aaa40cc9f9f280f4286934bbbf6151bf7344b087).

PRs for both VW and CB are up for review.

**Comment by jilladams** [comment]
I just accidentally verified this in prod! Did a spot-check of other forms, and they're looking good as well. Closing .

![Image](https://github.com/user-attachments/assets/121eb7e0-8ede-46f0-80fa-bd129438ed76)


![Image](https://github.com/user-attachments/assets/61f2346e-e68a-4393-a23d-b549bbd5cda8)

**Comment by randimays** [comment]
Also just successfully validated in production. This ticket got reopened though, @jilladams I'm assuming that was Zenhub weirdness so I'm closing. Feel free to reopen if you found an issue though!

**Comment by randimays** [comment]
@FranECross Just wanted to call out some post-release action items that needed to get done; wanted to make sure they were on your radar:

- @FranECross to close the loop with Tricia Baker on this [Slack](https://dsva.slack.com/archives/C52CL1PKQ/p1724876064322999) thread
- @FranECross to inform Kayce White

**Comment by FranECross** [comment]
- [ ] Closed the loop with Tricia Baker on this [Slack](https://dsva.slack.com/archives/C52CL1PKQ/p1724876064322999) thread
- [ ] Emailed Kayce White with cc to Jeana Clark, Tricia Baker, Randi M and Jill A. PDF of email attached[2024-10-01 - Email to Kayce White re - FW_ Form revision date change is live.pdf](https://github.com/user-attachments/files/17214082/2024-10-01.-.Email.to.Kayce.White.re.-.FW_.Form.revision.date.change.is.live.pdf)

**Comment by jilladams** [comment]
We discovered that: 
* Forms are not guaranteed to have a Revision date. 
* When no Revision date is available, Lighthouse Forms API will return the Issue date instead, for that field. 

https://dsva.slack.com/archives/C52CL1PKQ/p1740679508111569
https://dsva.slack.com/archives/CUB5X5MGF/p1740755074593239
