### ISSUE TITLE
Dashboard to make homepage controls easier to find for Editors

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#11086]
## Description

As an Editor of specific components of the homepage, I want to have all the controls I'm responsible for in a single view so that I can easily find what I need.

Controls for the new Drupal-managed homepage content are scattered across custom blocks, entity queues, and menus. Steve W proposed that a dashboard would enable us to pull all the controls into a single interface for Editors. And it can be section-specific so that e.g. OPIA Editors would see only their stuff.

Vet Centers have such a dashboard, and VBA will be getting one.

[Slack thread](https://dsva.slack.com/archives/C52CL1PKQ/p1664906131207969?thread_ts=1664906048.741409&cid=C52CL1PKQ).

## Acceptance Criteria
- [ ] Testable_Outcome_X
- [ ] Testable_Outcome_Y
- [ ] Testable_Outcome_Z
- [ ] Requires design review

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by wesrowe** [comment]
@mmiddaugh, when the time comes to consider this implementation, the ticket will need more definition around what we're trying to accomplish.

**Comment by jilladams** [comment]
Moved to post-MVP epic.

**Comment by jilladams** [comment]
Per sprint planning: Dave is not interested in investing in this dashboard for a minimal number of users, without research / data to prove that it's needed, due to expense of team's technical work to implement. 

If / when we want to take this on: we need to work with Dave on what sort of user research is required to get this done.

**Comment by FranECross** [comment]
Closing as a no op. Will reopen or create a new ticket if this issue bubbles up again.
