### ISSUE TITLE
Defect: 508 on injected headers: "skip link" for screen readers appearing after header

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#11085]
## Description

A stakeholder (John Edwards) outside OCTO-DE flagged an accessibility issue with injected headers. It is believed to be an issue with all injected headers in TeamSites. He believes this issue exists for all TeamSite sites with the injected header, but has been confirmed on [VHA](https://www.va.gov/wholehealth/), NCA and OPIA websites.

**Email from John Edwards to Jenny Heiland-Luedtke:**

> The injected VA header is placed directly below the <body> tag in TeamSite developed pages.  This has caused the skip navigation link that was part of the TeamSite templates to no longer be the first link in pages with the injected header.  The skip navigation link was the TeamSite templates means of satisfying the Web Content Accessibility Guideline (WCAG) 2.4.1 Bypass Blocks.  As currently rendered the TeamSite developed pages with the injected VA header are no longer in compliance with this guideline.
> 
> Below is a screen capture of the rendered source code from a page with the injected header.  The injected header (circled in red) appears between the body and “skiplink” elements (highlighted in yellow).
> 
> Would it be possible to have the injected VA header either repositioned below the TeamSite skip navigation link or have a new skip navigation link added as the first item in the injected code and then a new CSS style applied to hide the old TeamSite skip navigation link?

![image.png](https://images.zenhubusercontent.com/61a671f5fc46c2a311655f75/a4bb99d3-391f-48e8-8cd0-001881bef8d6)

### Engineering notes
The placement of the injected header is controlled with [this line of code](https://github.com/department-of-veterans-affairs/vets-website/blob/d1e5477ab409c0ca02a2e9aede0434db17019a35/src/applications/proxy-rewrite/proxy-rewrite-entry.jsx#L67). The fix boils down to not injecting after the `firstChild` but, rather, after the `skiplink` if it's present. If it's not present, it can be injected after the `firstChild` as is currently happening.

## QA steps
Refer to [proxy-rewrite/injected header documentation](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/proxy-rewrite) for testing procedure
- [ ] Test locally

## Acceptance Criteria
- [ ] Header is injected _after_ `skiplink` if present, otherwise at the top of `body`.
- [ ] Communicate fix to all stakeholders and ask John Edwards to validate (see comments!)

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by laflannery** [comment]
Reordering will resolve the issue, confirmed locally that if the HTML looks like this, the skip link will be the first focusable element: 
![image](https://user-images.githubusercontent.com/106678594/194118397-7f22eded-b8fb-49dd-a62d-6aff80ffbff8.png)

**Comment by jilladams** [comment]
When this is done, stakeholder comms from Wes / Jill should go back to "RE: Injected header's impact on skip navigation functionality" thread with JennyHL, Danielle, Blake Scates, John Edwards, Justin Warren.
