### ISSUE TITLE
Update Table UI helper text to require headers in the top row

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#11084]
### Dependency note
This work goes with fixing the existing version of tables, where the top row is always formatted by the FE as table headers. It will be "thrown away" when/if we enable Editors to select left-column headers.

## Description

This is a low-hanging way to attempt to prevent blank table header rows as documented in 508 defect https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11025.

Current helper text: "The first row will appear as the table header. Leave the first row blank if you do not need a header. "

New helper text (provided by @davidmpickett ): 
> The first row will be formatted as the table header. The labels in the first row should accurately describe the corresponding columns.

## Acceptance Criteria
- [ ] Helper text changed

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by davidmpickett** [comment]
This seems like a relatively small scope, I'm happy to take this on, but will need help understanding all the surrounding context. Depending on capacity, might be good to have Blake involved too just to continue building context for him. I leave that call to @EWashb

**Comment by EWashb** [comment]
@davidmpickett @wesrowe I agree that it would be good for @BlakeOrgan to sit in for context. Dave- I'm also available if you need me for additional editorial context. 

Once you have something written, @laflannery can review the interface as a whole.

**Comment by davidmpickett** [comment]
Okay. I think I have enough context now. I understand the larger project and how this is a small temporary solution. The goal is to educate editors that:
1) The first row should not be blank
2) The row will semantically coded as headers
3) If they were planning to use first-column-only headers, they should change their plan

**Comment by davidmpickett** [comment]
Just did a screenshare with @BlakeOrgan to show him a bit of the Drupal backend and build context.

**Comment by davidmpickett** [comment]
Can helper text include links?

**Comment by laflannery** [comment]
The short answer is yes. @dsasser should confirm the below two options though - 

**Option 1:** Short string with a link, I believe this would be include within the widget:
![image](https://user-images.githubusercontent.com/106678594/194944927-02cddd2c-43c0-45cf-b1d9-165339617beb.png)

**Option 2:** If you feel you need to provide more information we have the new inline guidance field and you can include a link within the expandable text. The inline guidance would be placed above the widget, I do not believe we can shove this into the middle where the help text currently sits.

**Comment by laflannery** [comment]
@davidmpickett The link you are providing is for the component in the style guide, something that is geared more towards developers rather than editors.  Only some of this seems like it would be useful for editors:

![image](https://user-images.githubusercontent.com/106678594/195093380-3d4a1933-a1c6-4eb1-b992-90038b91a592.png)

Everything else, the editor doesn't get a say in (alignment, sorting, code, the markup under accessibility concerns, etc.) That being said, is including this link going to cause confusion?  Could it be more helpful if we:

1. Create a KB article with the useful information and link to that? or
2. Include the useful information in the inline help text in what we are providing here?

**Comment by davidmpickett** [comment]
@laflannery Our only KB article about Tables also defers to that style guide. I agree that most of it is not particularly relevant for editors, but it's the only existing guidance. Given that this is a temporary patch, drafting new KB content seems out of scope. I already pulled the most relevant guidance in to the help text. I'm happy to just cut the link if you think it will only create confusion.

**Comment by laflannery** [comment]
@davidmpickett I took at look at the other guidance links and they are either for the KB or Content style guide so I think it would be better to be removed.

**Comment by davidmpickett** [comment]
@wesrowe @jilladams - Helper text rewrite is done. Ready for handoff

> The first row will be formatted as the table header. The labels in the first row should accurately describe the corresponding columns

**Comment by jilladams** [comment]
Updated ticket body and unassigned Dave since his piece is done.

**Comment by wesrowe** [comment]
@davidmpickett @laflannery, thank you for the collaborative effort
