### ISSUE TITLE
Income limits: High-fidelity prototype for internal review

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#11098]
## Description

Draft prototype for internal review (as a prelude to stakeholder review and usability research).

## Acceptance Criteria
- [x] Built in Sketch using Design System
- [ ] Enable simulated fill-in of inputs (i.e., starts blank, a click types a zip code)
- [x] Start from "Cost of care" or similar Benefit Hub page
- [x] Mobile layout only
- [x] Review with Dave Pickett and iterate if necessary
- [x] Schedule review with Dave Conlon

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by wesrowe** [comment]
@thejordanwood, checking in to see if you feel good about this or would like a meeting to discuss iteration?

**Comment by thejordanwood** [comment]
@wesrowe Yes, let's talk about this. I have a tentative flow for this, but am blocked on building an interactive prototype until we get more answers about what the result page should show and what we want to test during research sessions.

**Comment by thejordanwood** [comment]
Iterated on this and have a better idea on what the results page should show. Waiting to make an interactive prototype until UX research is better defined and more internal reviews take place.
