### ISSUE TITLE
Discovery: Google Analytics Editorial Security

### ISSUE THREAD

**Issue by EWashb** [department-of-veterans-affairs/va.gov-cms#11090]
## Background

Prior to rolling out CMS analytics to track editor behavior using GA4, we should confirm privacy and security with the Platform Analytics team. 

Also, the analytics team is requiring all users to upgrade to GA4.

## Acceptance Criteria

- [x] Meet with analytics team to determine security level and options to opt-out
- [x] Confirm differences between currently installed tag manager and what would be different with upgrading to GA4

**Comment by EWashb** [comment]
Messaged the analytics team again in slack

**Comment by EWashb** [comment]
Analytics team meeting scheduled for 10/27

**Comment by edmund-dunn** [comment]
Already on tag manager. Does this mean we are on GA3? 

What does GA4 mean for the existing GTM setup?

Editors can't opt out of existing GTM? 

Is this a privacy issue for editors?

Do we remove GTM and replace it with GA4 with the option to opt-out?

**Comment by EWashb** [comment]
Tag Manager is different from full GA. Editors cannot opt out of what is currently in place with Tag Manager. This shouldn't be an issue with editors, but GA4 gives us the ability to have them opt out if they so choose. CMS can opt out of going to GA4, but we probably don't want to do that. We should look at what we gain from going to GA4- this can help us track the editorial experience with the appropriate tags in place.

**Comment by EWashb** [comment]
In short, we can let editors opt out if we move to GA4.
