### ISSUE TITLE
Income limits: user research readout

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#11097]

**Comment by davidmpickett** [comment]
Not sure yet what the need for presentations / readouts for this will be. But leaving this as a placeholder in case those exceed the work @cindymerrill does in #11168.

**Comment by jilladams** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/income-limits-app/research/topline.md

**Comment by cindymerrill** [comment]
@wesrowe said no readout, unless he hears otherwise from Dave Conlon, and that my topline research findings report is all that's needed for now.
