### ISSUE TITLE
Form audit tool: Changed Filename

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#11115]
## Description

Add a tab to display all "Filename changed" form flags, similar to [existing flag audit table](https://prod.cms.va.gov/admin/content/flagged?type=va_form&workbench_access_section__section=All) filtered for "VA Form" content type, but with only one flag type. Include bulk ability to clear these flags.

## Developer Notes
This is achievable by:
- Cloning the existing flagged content view (or by creating a new display on the existing view.
- Adding a Views Bulk Operation field to the display (note: this is from the Global category, not the content category, see image below)
- Patching of the flag module is required to work with VBO. I have tested the [patch](https://www.drupal.org/files/issues/2020-07-25/flag-vbo-2893259-40.patch) [from this issue](https://www.drupal.org/project/flag/issues/2893259) and it is functional.

Configuring the VBO field is a bit tricky due to the naming of some of the flag's actions.
<img width="722" alt="Screen Shot 2022-10-06 at 10 44 32 AM" src="https://user-images.githubusercontent.com/221539/194383759-922a73be-b359-482f-9880-25d77d95efd4.png">
<img width="963" alt="Screen Shot 2022-10-06 at 10 48 19 AM" src="https://user-images.githubusercontent.com/221539/194383827-76e1c89f-2051-4688-a5ac-d2e21e2cc6ce.png">

## Acceptance Criteria
- [ ] New view should appear in VA Forms area: https://prod.cms.va.gov/admin/content/va-forms
- [ ] New view follows [CMS Views style guide](https://va-gov.atlassian.net/wiki/spaces/VAGOV/pages/1740472321/CMS+Views+Style+Guide)
- [ ] Display flags with columns
  - Title
  - Edit button
  - Content type
  - Updated (timestamp and author)
  - Moderation state
  - Section
  - Lock
  - <NEW> Form administration
- [ ] Bulk action to clear flags on selected items
- [ ] Requires PM/DM review

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by jilladams** [comment]
@chri5tia update! I'm proposing adding one additional field to this table at the end, Form Administration, as both a column and a filter. (That field exists).  Let me know if that changes the effort for this ticket. (GOing to add it to the other ticket as well.). FYI @wesrowe
