### ISSUE TITLE
Form audit tool: Deleted form

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#11117]
## Description

Add a tab to display all "Deleted" form flags, similar to [existing flag audit table](https://prod.cms.va.gov/admin/content/flagged?type=va_form&workbench_access_section__section=All) filtered for "VA Form" content type, but with only one flag type. Include bulk ability to clear these flags.

## Acceptance Criteria
- [ ] New view should appear in VA Forms area: https://prod.cms.va.gov/admin/content/va-forms
- [ ] New view follows [CMS Views style guide](https://va-gov.atlassian.net/wiki/spaces/VAGOV/pages/1740472321/CMS+Views+Style+Guide)
- [ ] Display flagged forms with columns
  - Title
  - Edit button
  - Content type (?)
  - Updated (timestamp and author)
  - Moderation state
  - Section
  - Lock
- [ ] Bulk action to clear flags on selected items
- [ ] Requires PM/DM review

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by chri5tia** [comment]
Added to https://github.com/department-of-veterans-affairs/va.gov-cms/pull/11251
