### ISSUE TITLE
Form audit tool: Changed Title

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#11118]
## Description

Add a tab to display all "Changed Title" form flags, similar to [existing flag audit table](https://prod.cms.va.gov/admin/content/flagged?type=va_form&workbench_access_section__section=All) filtered for "VA Form" content type, but with only one flag type. Include bulk ability to clear these flags.

## Acceptance Criteria
- [ ] New view should appear in VA Forms area: https://prod.cms.va.gov/admin/content/va-forms
- [ ] New view follows [CMS Views style guide](https://va-gov.atlassian.net/wiki/spaces/VAGOV/pages/1740472321/CMS+Views+Style+Guide)
- [ ] Display flagged items with columns
  - Title
  - Edit button
  - Content type (?)
  - Updated (timestamp and author)
  - Moderation state
  - Section
  - Lock
  - Flags
  - {NEW} Form Administration
- [ ] Bulk action to clear flags on selected items
- [ ] Requires PM/DM review

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by jilladams** [comment]
Also updated to propose adding one additional field to this table at the end, Form Administration, as both a column and a filter. (That field exists).

**Comment by jilladams** [comment]
Yep!

**Comment by chri5tia** [comment]
Merging these changes with the PR for #11115.

**Comment by jilladams** [comment]
Reopening ticket til we confirm that the 11115 PR is merged to main / shippable.
