### ISSUE TITLE
PM: Create a sitemap for the TRICARE and VA Healthcare pages and define author

### ISSUE THREAD

**Issue by dsinla** [department-of-veterans-affairs/va.gov-cms#11124]
## Description
Enumerate the expected pages - identify every clone, twin and solo, and define who authors.  What content is more central and would be written by VHADM, what content is specific to the facility and would be written by VA or TRICARE editors.

## Acceptance Criteria
- [ ] Produce a chart similar to this one:
![image](https://user-images.githubusercontent.com/62269210/194361242-a88e19e6-4a7b-4ebe-9e6b-968c9d81656d.png)

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by davidmpickett** [comment]
Reminder that I did a basic sitemap as part of the content model. Might save some time: https://airtable.com/appojvgFB7lvqgArz/tbljDFflQvxuHBWJK/viw0N9Q9DH5J3hjz5?blocks=hide

**Comment by davidmpickett** [comment]
@dsinla FYI I just made some updates to the Airtable sitemap based on the Tugboat environment. Probably worth building the RACI stuff into that Airtable rather than creating a separate document that is constantly at risk of being out of date. Let me know if you want me to help you set that up early next week

**Comment by dsinla** [comment]
This is basically @davidmpickett'S sitemap model.
A Solo or Twin page is assigned to the corresponding owner - VAMC or TRICARE
A Clone page - the same content shared between both sides - is proposed as VHADM owned content 


| Page nickname                                          | Suggested Page Name                                    | VHADM | TRICARE | VAMC |
| ------------------------------------------------------ | ------------------------------------------------------ | ----- | ------- | ---- |
| Lovell VA system                                       | Lovell Federal VA health care                          |       |         | X    |
| VA Health Services                                     | VA Health Services                                     |       |         | X    |
| VA Patient Advocates                                   | VA Patient Advocates                                   |       |         | X    |
| VA locations                                           | VA Locations                                           |       |         | X    |
| Captain Lovell VA                                      | Captain James A. Lovell Federal Health Care Center     |       |         | X    |
| Evanston VA Clinic                                     | Evanston VA Clinic                                     |       |         | X    |
| Kenosha VA Clinic                                      | Kenosha VA Clinic                                      |       |         | X    |
| McHenry VA Clinic                                      | McHenry VA Clinic                                      |       |         | X    |
| VA appointment                                         | Make a VA appointment                                  |       |         | X    |
| VA pharmacy                                            | VA Pharmacy                                            |       |         | X    |
| VA Register for care                                   | Register for VA care                                   |       |         | X    |
| VA Events                                              | Events                                                 |       |         |      |
| News releases                                          | News releases                                          | X     |         |      |
| Stories                                                | Stories                                                | X     |         |      |
| About Us                                               | About Us                                               | X     |         |      |
| Mission and vision                                     | Mission and vision                                     | X     |         |      |
| History                                                | History                                                | X     |         |      |
| Performance                                            | Performance                                            | X     |         |      |
| Leadership                                             | Leadership                                             | X     |         |      |
| Work with us                                           | Work with us                                           |       |         | X    |
| Jobs and Careers                                       | Jobs and careers                                       |       |         | X    |
| Internships and fellowships                            | Internships and fellowships                            |       |         | X    |
| Volunteer or donate                                    | Volunteer or donate                                    |       |         | X    |
| VA Policies                                            | VA Policies                                            |       |         | X    |
| VA Programs                                            | Programs                                               |       |         | X    |
| Research                                               | Research                                               |       |         | X    |
| VA Billing and insurance                               | VA Billing and insurance                               |       |         | X    |
| VA Medical records office                              | VA Medical records office                              |       |         | X    |
| Lovell TRICARE system                                  | Lovell Federal TRICARE health care                     |       | X       |      |
| TRICARE Health Services                                | TRICARE Health Services                                |       | X       |      |
| TRICARE Patient Advocates                              | TRICARE Patient Advocates                              |       | X       |      |
| TRICARE locations                                      | TRICARE Locations                                      |       | X       |      |
| Captain Lovell TRICARE                                 | Captain James A. Lovell Federal Health Care Center     |       | X       |      |
| USS Osborne Dental Clinic                              | USS Osborne Dental Clinic                              |       | X       |      |
| USS Red Rover                                          | USS Red Rover                                          |       | X       |      |
| USS Tranquility                                        | USS Tranquility                                        |       | X       |      |
| Zachary and Elizabeth Fisher Medical and Dental Clinic | Zachary and Elizabeth Fisher Medical and Dental Clinic |       | X       |      |
| TRICARE appointment                                    | Make a TRICARE appointment                             |       | X       |      |
| TRICARE pharmacy                                       | TRICARE Pharmacy                                       |       | X       |      |
| TRICARE Register for care                              | Register for TRICARE care                              |       | X       |      |
| TRICARE Events                                         | Events                                                 |       | X       |      |
| News releases                                          | News releases                                          | X     |         |      |
| Stories                                                | Stories                                                | X     |         |      |
| About Us                                               | About Us                                               | X     |         |      |
| Mission and vision                                     | Mission and vision                                     | X     |         |      |
| History                                                | History                                                | X     |         |      |
| Performance                                            | Performance                                            | X     |         |      |
| Leadership                                             | Leadership                                             | X     |         |      |
| TRICARE Policies                                       | TRICARE Policies                                       |       | X       |      |
| TRICARE Billing and insurance                          | TRICARE Billing and insurance                          |       | X       |      |
| TRICARE Medical records office                         | TRICARE Medical records office                         |       | X       |      |
