### ISSUE TITLE
DSN: Explore VA service taxonomy descriptions to understand and account for non-VA specific text

### ISSUE THREAD

**Issue by dsinla** [department-of-veterans-affairs/va.gov-cms#11123]
## Description
Some service descriptions specifically refer to Veterans. How do we account for non-veterans when these services are displayed/linked to from Lovell TRICARE (non-Veteran) pages. 

## Acceptance Criteria
- [ ] The problem space is understood and a plan for modifying the description taxonomy is proposed.

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by davidmpickett** [comment]
For a first step I identified 36 services that use the word "Veteran" or "VA" in the description or service name: https://airtable.com/shr9F9QFENjd8fZRS/tblPMm9VUNhQCpX8k 

Not sure that all of these services will be needed for Lovell TRICARE, but there's definitely a few key terms here like Pharmacy and Emergency Care.

[Grid view.csv](https://github.com/department-of-veterans-affairs/va.gov-cms/files/9749566/Grid.view.csv)

**Comment by davidmpickett** [comment]
I started by identifying 36 services that use the word Veteran or VA in their name or description:
https://airtable.com/shr9F9QFENjd8fZRS/tblPMm9VUNhQCpX8k
[Grid view.csv](https://github.com/department-of-veterans-affairs/va.gov-cms/files/9749618/Grid.view.csv)

**Comment by davidmpickett** [comment]
Will also need to revisit this ticket about possible additional taxonomy terms needed: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9770

**Comment by davidmpickett** [comment]
@RWEagans @dsinla flagging this as potentially high priority for sprint 69

**Comment by davidmpickett** [comment]
Updated potential conflicts list: https://airtable.com/shr9F9QFENjd8fZRS/tblPMm9VUNhQCpX8k

Put together a mural for discussion at taxonomy team meeting tomorrow: https://app.mural.co/t/vagov6717/m/vagov6717/1666039536221/0d45f7896d42a9aaad56752764787785452c31b8?sender=u20829d1b64855e281dde2585

**Comment by davidmpickett** [comment]
Proposal from meeting with @swirtSJW @JayDarnell and @dsinla:

On Lovell TRICARE Front End have a script to hide the VAMC Description Field on Services

**Comment by davidmpickett** [comment]
I updated the Lovell Content Model to have a field that indicates the part of the Taxonomy that is the source of the conflict. VAMC Description accounts for 26/40 of the potential conflicts, so hiding that will definitely help significantly. This is ready to take to Dave C / Taxonomy Council for discussion.
