### ISSUE TITLE
Recommendations for mitigating published node limit

### ISSUE THREAD

**Issue by cmaeng** [department-of-veterans-affairs/va.gov-cms#11130]
## Description
Based on investigative [findings from #10740](https://docs.google.com/presentation/d/1XXecTr0VrOnO299MrO1o1Bo88k8ikvGmPm0W7zog0mw/edit#slide=id.gef04f07fda_0_296), we need recommendations on how to mitigate with approximate LOEs.

Some initial ones to consider:
* Move to public S3 for Drupal asset storage
* Increase processing power on runner
* Investigate individual steps for optimization or removal (potential spike)
* Node archive policies
* Potentially parallelize some parts of the build (potential spike)
* Continue work on replacement for Content Build

## Acceptance Criteria
- [x] Stack ranked list of recommended paths forward with corresponding LOE and projected effect
  - Summarized in a comment below: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11130#issuecomment-1285991552

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [x] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by timcosgrove** [comment]
*Move to public S3 for Drupal asset storage*
Source: Multiple Content Release runs.

* The 'Download Drupal assets' step takes on average 105s
* The asset sync step of deploy takes on average 133s. 

Together this step takes just under 4 minutes. Therefore, completion of the public S3 epic would result in savings of 4 minutes, or a little over 10% of current total build time.

**Comment by timcosgrove** [comment]
We currently use m5.4xlarge instances. Looking at 3 alternate instance types:
* c5.4xlarge - less memory (32GB), faster proc speed (3.4), lower cost than m5.4xlarge
* c5d.4xlarge - same as above + SSD, lower cost than m5.4xlarge
* m6i.4xlarge - faster proc speed (3.5), faster network (12.5GB), same cost

**Comment by timcosgrove** [comment]
One simple thing we can do is remove some of the logging. Currently content-build logs two lines for each file downloaded, and the information is primarily there for diagnostics. Removing that logging could help reduce time.

**Comment by timcosgrove** [comment]
Steps we would look at for potentially parallelizing:
* Add permalinks
* Layout rendering collectively
* DOM tasks

Retrieving Drupal data and downloading Drupal assets are already parallelized. We might play with the number of parallel threads that are allowed to run.

**Comment by timcosgrove** [comment]
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11290 is created to provide better insight into variations in timing of individual steps.

**Comment by timcosgrove** [comment]
Node archive policies - this is primarily a product decision. If it were determined that there would nodes that we could safely archive, this would represent a reduction in nodes that need to be processed, which has already been shown to reduce content build time.

This is 100% a product decision and also subject to whatever legal requirements we may have for keeping older content accessible. It is not a decision for engineering to make.

Ideally if we were to implement a node archive policy, it would be automated rather than requiring human review. Still, a human review once a quarter of a set of nodes that are candidates for archiving could also yield performance gains.

The following suggestions should be read as hypothetical brainstorming ideas, rather than recommendations:

* non-recurring events, press releases, news items older than X months
* person profiles for individuals determined no longer to be at the facilities they're associated with

**Comment by timcosgrove** [comment]
| Mitigation | Potential gains | LOE | Confidence | Tickets or Epics | Notes | 
| --- | --- | --- | --- | --- | --- | 
| Public S3 asset storage | bar | thing | stuff | eonuth | foo | 
| Public S3 asset storage | bar | thing | stuff | eonuth | foo | 
| Public S3 asset storage | bar | thing | stuff | eonuth | foo | 
| Public S3 asset storage | bar | thing | stuff | eonuth | foo | 
| Public S3 asset storage | bar | thing | stuff | eonuth | foo | 
| Public S3 asset storage | bar | thing | stuff | eonuth | foo | 
| Public S3 asset storage | bar | thing | stuff | eonuth | foo | 
| Public S3 asset storage | bar | thing | stuff | eonuth | foo |

**Comment by timcosgrove** [comment]
Per a discussion with  @cweagans:
>  Continuous builds: current state: [https://mermaid.live/view/#eyJjb2RlIjoiZ2FudHRcbiAgICB0aXRsZSBDb250aW51b3VzIEJ1aWxkc1x[…]iI6dHJ1ZSwiYXV0b1N5bmMiOnRydWUsInVwZGF0ZURpYWdyYW0iOnRydWV9](https://mermaid.live/view/#eyJjb2RlIjoiZ2FudHRcbiAgICB0aXRsZSBDb250aW51b3VzIEJ1aWxkc1xuICAgIGRhdGVGb3JtYXQgIEhIOm1tXG4gICAgYXhpc0Zvcm1hdCAlSDolTVxuICAgIFxuICAgIHNlY3Rpb24gQnVpbGQgMVxuICAgIFN0YXJ0IFJ1bm5lciA6c3RhcnQsIDEzOjAwLCAybVxuICAgIFNldCBFbnYgVmFycyA6YWZ0ZXIgc3RhcnQsIDE1c1xuICAgIFZhbGlkYXRlIEJ1aWxkIFN0YXR1cyA6MTVzXG4gICAgQnVpbGQgOjE3bVxuICAgIEFyY2hpdmUgOjFtXG4gICAgQ3JlYXRlIFJlbGVhc2UgOjMwc1xuICAgIERlcGxveSA6NW1cblxuICAgIHNlY3Rpb24gQnVpbGQgMlxuICAgIFN0YXJ0IFJ1bm5lciA6MTM6MjYsIDJtXG4gICAgU2V0IEVudiBWYXJzIDoxNXNcbiAgICBWYWxpZGF0ZSBCdWlsZCBTdGF0dXMgOjE1c1xuICAgIEJ1aWxkIDoxN20gXG4gICAgQXJjaGl2ZSA6MW1cbiAgICBDcmVhdGUgUmVsZWFzZSA6MzBzXG4gICAgRGVwbG95IDo1bVxuIiwibWVybWFpZCI6IntcbiAgXCJ0aGVtZVwiOiBcImRhcmtcIlxufSIsInVwZGF0ZUVkaXRvciI6dHJ1ZSwiYXV0b1N5bmMiOnRydWUsInVwZGF0ZURpYWdyYW0iOnRydWV9)
Parallelized/overlapping builds: [https://mermaid.live/view/#eyJjb2RlIjoiZ2FudHRcbiAgICB0aXRsZSBQYXJhbGxlbCBCdWlsZHNcbiA[…]Ijp0cnVlLCJhdXRvU3luYyI6dHJ1ZSwidXBkYXRlRGlhZ3JhbSI6dHJ1ZX0](https://mermaid.live/view/#eyJjb2RlIjoiZ2FudHRcbiAgICB0aXRsZSBQYXJhbGxlbCBCdWlsZHNcbiAgICBkYXRlRm9ybWF0ICBISDptbVxuICAgIGF4aXNGb3JtYXQgJUg6JU1cbiAgICBcbiAgICBzZWN0aW9uIEJ1aWxkIDFcbiAgICBTdGFydCBSdW5uZXIgOnN0YXJ0LCAxMzowMCwgMm1cbiAgICBTZXQgRW52IFZhcnMgOmFmdGVyIHN0YXJ0LCAxNXNcbiAgICBWYWxpZGF0ZSBCdWlsZCBTdGF0dXMgOjE1c1xuICAgIEJ1aWxkLVRocm91Z2gtU3RlcC00OCA6MTJtXG4gICAgQnVpbGQtQWZ0ZXItU3RlcC00OCA6NW0gXG4gICAgQXJjaGl2ZSA6MW1cbiAgICBDcmVhdGUgUmVsZWFzZSA6MzBzXG4gICAgRGVwbG95IDo1bVxuXG4gICAgc2VjdGlvbiBCdWlsZCAyXG4gICAgU3RhcnQgUnVubmVyIDoxMzoxNSwgMm1cbiAgICBTZXQgRW52IFZhcnMgOjE1c1xuICAgIFZhbGlkYXRlIEJ1aWxkIFN0YXR1cyA6MTVzXG4gICAgQnVpbGQtVGhyb3VnaC1TdGVwLTQ4IDoxMm1cbiAgICBCdWlsZC1BZnRlci1TdGVwLTQ4IDo1bSBcbiAgICBBcmNoaXZlIDoxbVxuICAgIENyZWF0ZSBSZWxlYXNlIDozMHNcbiAgICBEZXBsb3kgOjVtXG4iLCJtZXJtYWlkIjoie1xuICBcInRoZW1lXCI6IFwiZGFya1wiXG59IiwidXBkYXRlRWRpdG9yIjp0cnVlLCJhdXRvU3luYyI6dHJ1ZSwidXBkYXRlRGlhZ3JhbSI6dHJ1ZX0)

> There is some room to further compact the parallelized version if we rearrange the build steps so that it gets data from external sources at the beginning and then does the rest of the processing on the local data. Skimming through the build summary in one of the actions outputs, it looks like there are three steps that get data from external sources (graphql, drupal assets, other assets). If those were all at the beginning, the build staggering could look like this: [https://mermaid.live/view/#eyJjb2RlIjoiZ2FudHRcbiAgICB0aXRsZSBDb21wYWN0ZWQgUGFyYWxsZWw[…]iI6dHJ1ZSwiYXV0b1N5bmMiOnRydWUsInVwZGF0ZURpYWdyYW0iOnRydWV9](https://mermaid.live/view/#eyJjb2RlIjoiZ2FudHRcbiAgICB0aXRsZSBDb21wYWN0ZWQgUGFyYWxsZWwgQnVpbGRzXG4gICAgZGF0ZUZvcm1hdCAgSEg6bW1cbiAgICBheGlzRm9ybWF0ICVIOiVNXG4gICAgXG4gICAgc2VjdGlvbiBCdWlsZCAxXG4gICAgU3RhcnQgUnVubmVyIDpzdGFydCwgMTM6MDAsIDJtXG4gICAgU2V0IEVudiBWYXJzIDphZnRlciBzdGFydCwgMTVzXG4gICAgVmFsaWRhdGUgQnVpbGQgU3RhdHVzIDoxNXNcbiAgICBCdWlsZC1UaHJvdWdoLVN0ZXAtMyA6MTQ1c1xuICAgIEJ1aWxkLUFmdGVyLVN0ZXAtMyA6ODc3c1xuICAgIEFyY2hpdmUgOjFtXG4gICAgQ3JlYXRlIFJlbGVhc2UgOjMwc1xuICAgIERlcGxveSA6NW1cblxuICAgIHNlY3Rpb24gQnVpbGQgMlxuICAgIFN0YXJ0IFJ1bm5lciA6MTM6MDUsIDJtXG4gICAgU2V0IEVudiBWYXJzIDoxNXNcbiAgICBWYWxpZGF0ZSBCdWlsZCBTdGF0dXMgOjE1c1xuICAgIEJ1aWxkLVRocm91Z2gtU3RlcC0zIDoxNDVzXG4gICAgQnVpbGQtQWZ0ZXItU3RlcC0zIDo4NzdzXG4gICAgQXJjaGl2ZSA6MW1cbiAgICBDcmVhdGUgUmVsZWFzZSA6MzBzXG4gICAgRGVwbG95IDo1bVxuIiwibWVybWFpZCI6IntcbiAgXCJ0aGVtZVwiOiBcImRhcmtcIlxufSIsInVwZGF0ZUVkaXRvciI6dHJ1ZSwiYXV0b1N5bmMiOnRydWUsInVwZGF0ZURpYWdyYW0iOnRydWV9) (the real constraint is that we don’t want the steps that download external data running in parallel and we don’t want the deploy step running in parallel)
