### ISSUE TITLE
PM: Outline the architecture for VBA roll-out with key order of operations as a team 

### ISSUE THREAD

**Issue by dsinla** [department-of-veterans-affairs/va.gov-cms#11139]
## Description

Define as a team the major high-level development (and associated DSN/PM) steps for how we plan to execute and deploy VBA. Focus on what is required for MVP, but account for known issues that must be addressed outside MVP scope.  

## Acceptance criteria
Epics and corresponding child tickets are created that represent the order of operations for Dev tasks to complete VBA

**Comment by davidmpickett** [comment]
Reminder about this [mural I made](https://app.mural.co/t/vagov6717/m/vagov6717/1661458485419/a573bc954d3e3bd30f8e2001fef9cb7a9770348f?sender=u20829d1b64855e281dde2585) - might be a good starting point

**Comment by davidmpickett** [comment]
I am updating those notes to 1) link to tickets that have been created and 2)indicate where tickets still need to be created

**Comment by dsinla** [comment]
Notes from Dev meeting where major steps were identfied:
https://docs.google.com/document/d/1OWs6X6vwfKoxL7Kobt9jM-kiUMPWjQs_eXCftTZeG7A/edit
The following tickets were created:
#11301 
#11302 
#11303 
#11304 
#11305 
#11306 
These were all added to the epic: #10514
