### ISSUE TITLE
Create "How to use the outdated content audit tool" KB article

### ISSUE THREAD

**Issue by EWashb** [department-of-veterans-affairs/va.gov-cms#11136]
## Background

We have implemented a new audit tool in the CMS that allows users to view outdated content, therefore we need a KB article explaining what it is and how to use it. This article will only be needed for our internal teams aka super admins.

[Outdated content tool ](https://prod.cms.va.gov/admin/content/outdated_content)

## Acceptance Criteria

- [ ] use KB article template to create the KB
- [ ] Accessibility review
- [ ] Helpdesk review

**Comment by laflannery** [comment]
Questions (things I was curious about when learning about this):

- What would be the purpose/use case for the “Over XX days past due” filters? I can't wrap my head around how this is set up, I keep getting confused.
- Do we need to have the text “This view is only available to admins”? You wouldn’t even be able to access this page unless you are an administrator so it seems unnecessary/duplicative.
- The CSV export does not list items in the same way the CMS display does. Do we know why that is and is there a way that can be fixed? I was confusing to me when I was trying to match the export with what I was seeing in the CMS - I'm also not sure if it matters that much, would there be use case for this needing to match? I wanted to at least bring it up just in case though

**Comment by EWashb** [comment]
@laflannery good questions. The filter names do get confusing (we are working on updating them in sprint 70). Those filters can help an admin see what is the most outdated, but they probably won't be used a lot. 

I do think we need some text about this being open to admin only. Right now it should only be used by our internal team. Happy to sync on this with you too. Edmund is updating the filters, so we might want to wait to publish this until he's done anyway.

**Comment by EWashb** [comment]
And I didn't realize the CSV wasn't matching. It prob should match....

**Comment by EWashb** [comment]
@laflannery the new filters are now up on the report.

**Comment by laflannery** [comment]
@EWashb Thanks! Can we do a quick regroup on this next week so I can get my head back around everything and hopefully wrap this up?

**Comment by EWashb** [comment]
yes please @laflannery

**Comment by laflannery** [comment]
Updated [draft article here](https://docs.google.com/document/d/1CrlwVLZpWjnvrpi1lZAc7UJ9vjomdYFI28yyRMbsZYE/edit#)

@edmund-dunn Can you review for correctness - making sure my explanation of the filters and all that makes sense and I didn't miss anything?

@EWashb could you review and see if the entire article make sense logically in how I presented it?

Thanks!

**Comment by laflannery** [comment]
[Published article here](https://prod.cms.va.gov/help/cms-basics/outdated-content-audit-tool)
