### ISSUE TITLE
CMS: Add new VBA fields to VA service taxonomy

### ISSUE THREAD

**Issue by dsinla** [department-of-veterans-affairs/va.gov-cms#11137]
As noted below, technically this ticket is blocked by #11249 - however, we can say with a fairly high degree of certainty that the VA Services taxonomy will need to be expanded to support VBA Services using most of the same fields we added to support Vet Centers. 

In addition, now that we're expanding this taxonomy to store VBA (and later NCA) services, we would like to add checkboxes to each facility type field set to specify if a given term is available to that facility type. This will make it easier to programmatically filter the terms by facility type in the long run. This work will require a content update to the taxonomy in the future to ensure the checkboxes are appropriately set before we can actually leverage them.

<img width="1705" alt="Screen Shot 2022-10-19 at 1 41 13 PM" src="https://user-images.githubusercontent.com/21045418/196768932-8a0a1dfc-a367-4926-9b7a-57f65af8f293.png">

**Update VAMC fieldset**
- [x] Add a checkbox: Show for VAMC Facilities

**Update Vet Center fieldset**
- [x] Add a checkbox: Show for Vet Centers

**New VBA fieldset**
- [x] New VBA field set
- [x] Checkbox: Show for VBA Facilities
- [x] Textbox: VBA Patient Friendly Name (similar to Patient friendly name - works like a subtitle for the term)
- [x] Textbox: VBA Common Conditions (similar to Common conditions - comma separated list of search terms)
- [x] Textarea: VBA Description (similar to service description for Vet Centers)

**Comment by davidmpickett** [comment]
Not sure what the scope of this ticket is, but is is probably blocked by some other tickets. For instance https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11123

**Comment by davidmpickett** [comment]
@JayDarnell is there a possibility this will complete in Sprint 69? Or should this be Sprint 70?

**Comment by JayDarnell** [comment]
@dawnpruitt this issue was originally completed by @omahane so it should really be assigned to him.
