### ISSUE TITLE
PM: Initiate work with Content Team to define text limit and guidance for VAMC System Banner Alert

### ISSUE THREAD

**Issue by dsinla** [department-of-veterans-affairs/va.gov-cms#11141]
## Description
Banners have the potential to be abused.  Some facilities have multiple banners, or even a single banner, that has more content than the facility page itself. Banners are being used for promotional/marketing content, for recruiting, for stories, for operational status, etc. How do we improve the Veteran experience by providing the best guidance to Editors for how to author and deploy banners.

## User Story
As an Editor, I want clear guideline on how banners should be used, how system and facility banners might interact, what is appropriate content for a banner, what is the text limit, how and when should I link to additional content. 

## Acceptance Criteria
- [ ] Testable_Outcome_X
- [ ] Testable_Outcome_Y
- [ ] Testable_Outcome_Z
- [ ] Requires design review

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [x] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by dsinla** [comment]
Next step DS to get a content collab request ticket on their radar.

**Comment by dsinla** [comment]
Content team intake ticket created: https://github.com/department-of-veterans-affairs/va.gov-team/issues/48331

**Comment by dsinla** [comment]
To what extent does guidance already exist? In the current design system.
Refer to: https://design.va.gov/components/banner/#content-considerations\
Banners were recently updated in Design System.
Make sure content is design system is updated and clear - are we creating links to the correct spot, make sure we're not duplicating anything in the KB.  What kind of CM is needed regarding KB content?

**Comment by EWashb** [comment]
@dsinla if there is an existing KB article there shouldn't be much other CM needed. We would just update the KB and then send it to the helpdesk for review.

**Comment by dsinla** [comment]
- https://prod.cms.va.gov/help/homepage-alerts-and-promo-banners/full-width-alerts 
This KB instructs how to create a banner but no guidance on why, how many, limiting the number of banners or the text in the banner
- https://prod.cms.va.gov/help/homepage-alerts-and-promo-banners/promo-banners 
This KB instructs and discusses the types of Promo banners.  Only Office of Public and Intergovernmental Affairs editors can create banners
- https://design.va.gov/components/banner/#content-considerations%5C
The design system component has guidance and examples. Do we link the KB to this guidance?

**Comment by dsinla** [comment]
Per convo with @davidconlon, we'll pivot on this and do our internal audit of how banners are currently being used, and take a first stab at recommendations. Then circle in the content team for polish and assistance in educating editors.  

Creating a new ticket to track: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11434
