### ISSUE TITLE
CMS Add fields to Resources and Support taxonomy

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#11146]
The crosswalk and discovery performed in #11144 will likely generate some fields that will need to be  added to the taxonomy for [Resources and Support Categories](https://prod.cms.va.gov/admin/structure/taxonomy/manage/lc_categories/) (lc_categories)

This issue is the placeholder for adding those fields

## Eng notes
- Is there a data migration required?
  - Per @swirtSJW it's not an automated migration; just copy-paste

## ACs
- [ ] field `Topic ID` added to lc_categories
   - [ ] machine name: field_topic_id
   - [ ] required
   - [ ] type: plain text
   - [ ] label: Topic ID
   - [ ] help text:  "A unique id for this topic used for analytics.  Must not be changed once created."
   - [ ] other notes about the field
- [ ] field `Enforce unique topic id` added to lc_categories
   - [ ] machine name: field_enforce_unique_value
   - [ ] type: allow only one (module; prevents dupes)
      - [ ] unique on:  field_topic_id
   - [ ] location in form: just above field_topic_id
   - [ ] help text: none

**Comment by jilladams** [comment]
Reassigning per https://dsva.slack.com/archives/C52CL1PKQ/p1666806625007439
