### ISSUE TITLE
Content: Add / edit Resources and support terms to Taxonomy

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#11148]
There will be terms coming out of #11144 that will need to be added or edited before the [Resources and support Categories taxonomy](https://prod.cms.va.gov/admin/structure/taxonomy/manage/lc_categories/overview) can be used to power Outreach materials.  This is the issue for carrying out the additions or edits

Unified list of terms from #11144
```
Burials and memorials
Careers and employment
Decision reviews and appeals
Disability
Education and training
Family member benefits
Health care
Housing assistance and home loans
General benefits information
Life insurance
**NEW: **PACT Act
Pension
Records
Service member benefits
VA account and profile
Other topics and questions
```

## Eng notes
- machine name from #11146 is required for this activity

## ACs
- [ ] add `PACT Act`
- [ ] add `Family member benefits`
- [ ] update `Housing assistance` to `Housing assistance and home loans`
- [ ] add `General benefits information`
- [ ] add `Service member benefits`
- [ ] alpha sort the taxonomy (exception: `Other topics and questions` is the last item in the alpha-sorted taxonomy)
- [ ] Enter data on Prod after code deploy

**Comment by davidmpickett** [comment]
Is this something we need to run through Sitewide Content? Or is this something I can sign off on from a Content perspective?

**Comment by wesrowe** [comment]
@davidmpickett, it's my understanding that the SW Content team generated the cross-walk of the terms along with Dave C (who provided the analysis to me). In the interest of building the collaborative tissue between our teams, do you want to figure out how to loop them in on this plan? TBH I'm realizing now that Dave C brought this up in our Refinement meeting and we never interacted directly with SWC about it (I don't think). I'll forward you his email.

**Comment by davidmpickett** [comment]
Re the last AC of "alpha sort the taxonomy," I think we'd still want "Other topics and questions" as the last item in the taxonomy though, correct?

**Comment by wesrowe** [comment]
good catch @davidmpickett

**Comment by jilladams** [comment]
Re: ownership of this task, per Randi: 
> I'm not familiar with this work but if it's a matter of updating the taxonomy in Drupal with an approved list it's OK for PW to do this.

**Comment by jilladams** [comment]
Reassigning per https://dsva.slack.com/archives/C52CL1PKQ/p1666806625007439

**Comment by jilladams** [comment]
Note: we may need to add PACT Act. I think it was an oversight that it's not in this list. TBD: 

https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11144#issuecomment-1293833109
https://dsva.slack.com/archives/C52CL1PKQ/p1666890993131729?thread_ts=1666810454.376559&cid=C52CL1PKQ

**Comment by davidmpickett** [comment]
Good catch @jilladams PACT Act is in the ACs, but not in the unified list.

**Comment by jilladams** [comment]
Confirmed: PACT Act should be in the list, https://dsva.slack.com/archives/C52CL1PKQ/p1666895988786299?thread_ts=1666810454.376559&cid=C52CL1PKQ

Added to the list here.
