### ISSUE TITLE
Meet with Accelerated Publishing team regarding NextJS vs current MetalSmith static site generator for VBA

### ISSUE THREAD

**Issue by dsinla** [department-of-veterans-affairs/va.gov-cms#11142]
## Description 
As we add VBA we'll be adding more nodes. We'll be coming up against the limit of hitting the1 hour build time. NextJS is being considered.

**Comment by JayDarnell** [comment]
@dsinla unless I'm mistaken, based on our conversation yesterday, I do not believe this is an actionable item for our team.

**Comment by davidmpickett** [comment]
@swirtSJW @omahane Is this about accelerated publishing?

**Comment by omahane** [comment]
@davidmpickett Yes, I believe so.

**Comment by davidmpickett** [comment]
@jilladams Why yes, you were correctly reading my mind in the meeting yesterday when we were talking with Accelerated Publishing about candidates for content types to be built in the new system

**Comment by davidmpickett** [comment]
Moving this to national rollout epic as this is not blocking for Staging Review.

**Comment by Agile6MSkinner** [comment]
@davidmpickett @dsasser Is this still relevant?

**Comment by davidmpickett** [comment]
Closing. We built VBA in Content Build (Metalsmith) vs Nextbuild (NextJS). It will move over during AP migration which is a whole separate initiative
