### ISSUE TITLE
FE Lovell menus no longer showing on FE

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#11155]
When I visit [Lovell TRICARE](https://web-liqqgmzl7tsyfbwyulbkuborufuuttav.demo.cms.va.gov/lovell-federal-tricare-health-care/) or [Lovell VA](https://web-liqqgmzl7tsyfbwyulbkuborufuuttav.demo.cms.va.gov/lovell-federal-va-health-care/) I no longer see the menus.  This is a regression
![image](https://user-images.githubusercontent.com/5752113/194541133-8b74f533-502e-4f90-b6bb-199ef45681ae.png)

## ACs
- [ ] When I visit Lovell VA I should see the sidebar menu
- [ ] When I visit Lovell TRICARE, I should see the sidebar menu

**Comment by swirtSJW** [comment]
There is a possibility this is due to the menu now having three root elements.  instead of two
* federal
* tricare
* va

That data pattern is now logged in, so the FE logic may need to account for three.  The 'federal' is a throwaway element that can be deleted, but is likely messing up the count logic.

**Comment by jilladams** [comment]
@maxx1128 is there an associated PR for this closed ticket? Figuring out if it should be included in Sprint 70 reporting or not.

**Comment by jilladams** [comment]
NM - found it - https://github.com/department-of-veterans-affairs/content-build/pull/1332. Adding Sprint 70.
