### ISSUE TITLE
Discovery: Create report on published PDFs

### ISSUE THREAD

**Issue by EWashb** [department-of-veterans-affairs/va.gov-cms#11158]
## Description

Currently, there is no easy way for editors to delete PDFs in the CMS. Therefore it results in inline workarounds for editors to replace PDFs currently in the system, such as the _0 and _1 are iterations/replacements of the same file and Drupal is appending those numbers to them.

[Slack thread for context](https://dsva.slack.com/archives/CT4GZBM8F/p1665061751675579)

We need to determine:

- what PDFs we have published (live)
- what PDFs aren't published 

## Acceptance Criteria
- [ ] create a report differentiating published PDFs from the total number of PDFs
- [ ] Bonus points for automated reporting

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by EWashb** [comment]
@ndouglas I'm thinking about getting you to take a look at this next sprint. It is a high priority. Feel free to add any preliminary thoughts!

**Comment by EWashb** [comment]
Entity usage module may help locate these. Longer term there may be contrib modules, but the issue is due to drupal core bug

**Comment by edmund-dunn** [comment]
This can be reviewed here https://pr11229-h9b7bf6iead1sxc39ukglskrbccknwvu.ci.cms.va.gov/

**Comment by EWashb** [comment]
Instead of automating, this report can be pulled in the CMS views
