### ISSUE TITLE
CMS Create CMS Feature Flag for Publications (outreach materials)

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#11150]
It looks to me (Swirt) [that publications are only edited by](https://prod.cms.va.gov/admin/content?title=&type=outreach_asset&moderation_state=editorial-published&owner=All&page=0) Randi  and Tim Hudak   These are both savvy users who might be able to handle seeing duplicate-ish looking fields for a short time.  If that is true, we might be able to skip the whole feature flag workflow as long as we communcate to them that they will need to keep both versions of the field in syn until we switch over completely.

**Comment by wesrowe** [comment]
Determined not necessary as only 2 editors
