### ISSUE TITLE
FE Make outreach material topic filters use field_lc_categories

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#11153]
The topic filter on [outreach materials](https://www.va.gov/outreach-and-events/outreach-materials/) is currently powered by a hardcoded list.
![image](https://user-images.githubusercontent.com/5752113/194467652-25284349-0c64-476e-8a88-2289ec2f9ac2.png)

And the topic list filters based on the data carrying the value of `field_benefits`   

To make these selection options more consistent `field_benefits, a single select list, will be converted to `field_lc_categories` which is a multi-select entity reference.  For improved capabilities that are content based rather than hardcoded, this filter should assemble its choices from the choices in the data.  The file type filter should also create its choices from the available data items, not from a hardcoded list.  

## Eng notes
- This should not be merged until BE is ready; see epic for release plan

Graphql queries coming out of #11147:

```graphql
# Updated outreachAssets query with new fieldLcCategories field.
query outreachAssets {
  nodeQuery(filter: {conditions: [
    { field: "type", value: "outreach_asset" },
    { field: "status", value: ["1"], enabled: true }
  ]}, limit: 10000) {
    entities {
      ... on NodeOutreachAsset {
        entityId
        title
        status
        changed
        fieldFormat
        fieldLcCategories {
          entity {
            ... on TaxonomyTermLcCategories {
              name
              fieldTopicId
            }
          }
        }
        fieldDescription
        fieldListing {
          targetId
        }
        fieldMedia {
          entity {
            ... on MediaImage {
              entityBundle
              image {
                entity{
                  filesize
                }
                url
                alt
              }
            }
            ... on MediaDocument {
              entityBundle
              fieldDocument {
                entity {
                  filesize
                  url
                }
              }
            }
            ... on MediaVideo {
              entityBundle
              fieldMediaVideoEmbedField
              thumbnail {
                derivative(style: LARGE) {
                  url
                }
              }
            }
          }
        }
      }
    }
  }
}

# Get all terms + topic id's from the Resources & Support Vocabulary:
query TermQuery {
  taxonomyTermQuery(filter: {conditions: [
    { field: "vid", value: "lc_categories" },
    { field: "status", value: ["1"]}
  ]}, limit: 10000) {
  	entities {
      ... on TaxonomyTermLcCategories {
        name
        fieldTopicId
      }
    }
  }
}
```

Use this tugboat from the [backend PR](https://github.com/department-of-veterans-affairs/va.gov-cms/pull/11352) as content-build source: https://cms-xqzwhjdu8iqvmcgg91mcyothppkp4pua.ci.cms.va.gov/

## ACs
- [ ] The topic filter options are powered by field_lc_categories from the data items on the page (this is a new field and will need to be added to the graphql.)
- [ ] ~~The file type filter options are powered by field_format  (this is not a new field)~~
- [ ] Topic filter and type filter select lists are alpha sorted
- [ ] A veteran should never be able to select a topic option that has no data. (example: Disability should not appear as a filter if there are no data items of topic Disability.)
- [ ] The field field_benefits is no longer referenced on the template and no longer in the graphQL 
- [x] Create future issue -  The two filters are aware of each other and self restrict the other's limits.  (example: If I select format = video, I should not see types in the filter that contain no videos. This would prevent from selecting a filter combination that has no results. – #11476 
 - [ ] Accessibility review - receives 508 approval 
 - [ ] PM/DM review

**Comment by swirtSJW** [comment]
Also keep in mind that Ourtreach materials is Publication listing page which just happens to be the only Publication listing page.  BUT in theory we should be able to create other publication listing pages around the site, so plan for any coding to not be so specific that it only works on this page.

**Comment by swirtSJW** [comment]
Also keep in mind that this page does an unusual thing where it contains all the data that is being filtered, then it just hides what is not supposed to show.

**Comment by wesrowe** [comment]
Additional ACs:
- [ ] UI tiles display all categories for a given item
- [ ] Filters evaluate all item categories present
