### ISSUE TITLE
FE: Outreach material filters support query parameters

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#11154]
As veteran searching the outreach materials page, when I select a combination of filters I should see that reflected in the url query parameters or path so that I can copy the url and share it with my buddy, and they will see the same results I do.

![image](https://user-images.githubusercontent.com/5752113/194474288-773a7e24-e658-42de-8025-ef42431c1ec0.png)

### Engineering Notes
The filtering of results is controlled by a [function named `libraryFilters`](https://github.com/department-of-veterans-affairs/vets-website/blob/0e98c4eb366b9ac1a59d805c4dbcd198a76afd1a/src/applications/public-outreach-materials/libraries/library-filters.js#L151). This function serves as the event handler for multiple clicks (topic dropdown, type dropdown, pager controls).

In order to have this form respect query parameters, we'll need to do at least two things:
1. Execute the logic in this event handler on page load. 
  - One way to accomplish this would be to read the query parameters on page load and then simulate clicks on the appropriate dropdown selections.
  - Another option would be to pull out the logic specific to setting these filters into a reusable function and then call that function on page load with the parameters from the query string.
2.   Update the URL query string when the filters are changed.

#### Note:
The query string is currently being updated with a `#{pageNumber}` when the pager is clicked. This is a pattern to possibly copy. *HOWEVER, a page number in the url is _not_ respected on page load*. We should consider changing this to behave like the others (i.e. `?topic={topic}&type={type}&page={pageNumber}`). The risk is in not knowing if anything is currently depending on the `#{pageNumber}` format.

## ACs
- [ ] When on https://www.va.gov/outreach-and-events/outreach-materials/ if I filter by topic pension, type poster, the url should become https://www.va.gov/outreach-and-events/outreach-materials/?topic=pension&type=poster  or perhaps https://www.va.gov/outreach-and-events/outreach-materials/pension/poster
- [ ] If somebody gives me the link https://www.va.gov/outreach-and-events/outreach-materials/?topic=pension&type=poster  I should see the filters set just as if I set them myself.

**Comment by wesrowe** [comment]
Returning to new/unrefined since we heard that the outreach material library is moving/being deprecated.

**Comment by FranECross** [comment]
closing as a no op; Outreach Materials deprecated in fall of 2022, as VEO moving the materials elsewhere.
