### ISSUE TITLE
Update Flagged Content view to be Facilities specific & move to Facilities section

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#11164]
## Description

The [Flagged Content view ](https://prod.cms.va.gov/admin/content/flagged?type=All&workbench_access_section__section=All) (`admin/content/flagged`) currently contains both VA Forms and Facilities content. Via the epic #11066, Forms now have their own section & views and can be removed from this more generic Flagged Content view, in order to make it Facilities specific.

## Acceptance Criteria
- [x] Remove VA Forms from /admin/content/flagged
- [x] Relocate this view to live under the Facilities section, tab name = "Facilities Flagged content": https://prod.cms.va.gov/admin/content/facilities
- [ ] Notify CMS Support and Facilities team that their tool has moved.
- [x] update links in /vagov/READMES/migrations-facility.md
- [ ] Update links in Knowledgebase article(s)

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by wesrowe** [comment]
@swirtSJW, according to my bookkeeping this is unblocked now. Do you concur?
cc @chri5tia

**Comment by jilladams** [comment]
This is really a Facillities task now, but if we have Drupal bandwidth in S72 we could knock it out.

**Comment by chri5tia** [comment]
So... the page and view implies that it's all content. But I should remove just "VA Form" from the view, right?
<img width="320" alt="Screen Shot 2022-11-29 at 3 05 50 PM" src="https://user-images.githubusercontent.com/22764938/204667943-da8c91d9-2329-4555-887f-dd51c4f1c4f4.png">

**Comment by jilladams** [comment]
Yep, so: 
* The difference between `/admin/content/flagged` and `/admin/content/facilities` is the flags. The Flagged view for managing flagged content doesn't exist in the Facilities area, and none of the existing Facilities views show flags or have Actions to manage flags. 
* To fix that, we're: 
  * relocating this Flagged view into the Facilities area as a new tab, e.g. "Flagged Facilities". (should've put this in ACs, I'll update)
  * removing Forms from it (now that Forms has separate views for managing Form flags). After Forms are removed, this view will be 100% facilities focused. 

Basic idea being this rando `flagged` view doesn't have clear ownership from any one team, so splitting Forms / Facilities out, and putting the views in specific areas, makes it more clear who owns dealing with the flags.

**Comment by swirtSJW** [comment]
Thanks for taking this on.  Probably should have been a Facilities ticket, but I appreciate the assist.

A could things in general to keep in mind.   Views are easy to edit and move things around.  However that does not mean we should do so without change management.   Both CMS support and Facilities team use the View pretty regularly so I added an AC to notify the appropriate teams that there cheese has been moved.  Creating a redirect is always a nice thing to do.

**Comment by swirtSJW** [comment]
I also added a AC about making sure to update documentation in READMEs and KB

**Comment by jilladams** [comment]
KBs that reference "Flag":   (https://prod.cms.va.gov/help/search?keyword=flag, 5 not relevant, 3 need updated): 
1. https://prod.cms.va.gov/help/vamc/how-to-know-when-facility-data-changed-in-the-facility-api
2. UPDATED - https://prod.cms.va.gov/help/va-forms/how-to-troubleshoot-broken-form-downloadsbad-pdf-links-from-find-a-form
3. UPDATED - https://prod.cms.va.gov/help/va-forms/how-to-know-when-a-va-form-changed-in-the-forms-db

**Comment by chri5tia** [comment]
This should be able to close today. PR is in review.

**Comment by jilladams** [comment]
Reopening til PR merges.

**Comment by jilladams** [comment]
https://prod.cms.va.gov/help/vamc/how-to-know-when-facility-data-changed-in-the-facility-api Updated.
