### ISSUE TITLE
Restore missing libraries

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#1116]
**Describe the defect**
After the D8.8 upgrade, modules that are still present but moved from the distribution into modules contrib are missing their associated libraries.

This is evident on the status page 

![image](https://user-images.githubusercontent.com/5752113/75587707-13397f80-5a45-11ea-8ae1-813540898b89.png)

![image](https://user-images.githubusercontent.com/5752113/75587734-21879b80-5a45-11ea-8397-b61118a5d088.png)

The following libraries need to be added to composer individually

- [ ]  Blazy - for lazy loading  https://github.com/dinbror/blazy

- [ ] Dropzone -  for drag and grop file uploads https://github.com/enyo/dropzone  

- [ ] imagewidgetcrop - for cropping https://github.com/fengyuanchen/cropper

- [ ] slick - for carousels?  https://github.com/kenwheeler/slick/  

**To Reproduce**
1. Go to '/admin/reports/status'
2. See errors

**Expected behavior**
These should not be flagged as missing.

**Comment by kevwalsh** [comment]
Slick can be disabled. 
Blazy may be used for media library UI. 
Keep Dropzone and imagewidgetcrop.

**Comment by ElijahLynn** [comment]
Related to #1179.

**Comment by swirtSJW** [comment]
dropzone uses the local drupal libraries location so had to route it by using 
``` lando composer require bower-asset/dropzone```

**Comment by swirtSJW** [comment]
![image](https://user-images.githubusercontent.com/5752113/76129726-2369d580-5fd6-11ea-825a-02ee354b9d5d.png)
