### ISSUE TITLE
FE: Menus should be covered by FE link checker

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#11173]
## User Story or Problem Statement

As a Veteran, I don't want to encounter broken links on the primary means of navigation (menus) on va.gov.

As a site reliability engineer, I want to know that high priority links in menus are covered by our link checking so that Veteran's are not encountering broken links on menus.

Currently the link checker that runs as part of the content-build does not scan the following

- Links in the header menu
- Links in the footer menu
- links in the ~200 sidebar menus

### Related notes: 
The CMS content link checking is only from internal page to internal page, it does not check external links.
Due to the high value/risk we might consider doing multi-curl to check external links  that appear in the header or footer menus.  It is a small amount that could easily be checked during the content build.

## Acceptance Criteria
- [ ] Header menu links are checked
  - [ ] including external links (could be a separate ticket)
- [ ] Footer links are checked
  - [ ] including external links (could be a separate ticket)
- [ ] internal links in the ~200 sidebar menus are checked

**Comment by EWashb** [comment]
@jilladams @wesrowe I found this in the CMS backlog, but this seems solely related to your products. also unsure if you already have something in place for the header/footer.

**Comment by wesrowe** [comment]
I agree, added PW label

**Comment by jilladams** [comment]
Noting: yesterday Tim Cosgrove the current broken link checker works won't work the same way after fast publishing ships. So: this may not be worth the effort til they've established the new model.

**Comment by jilladams** [comment]
Per discussion with @FranECross , moving to blocked. FYI @timcosgrove that if this can be solved by the AP link checker rework, we can close this.

**Comment by jilladams** [comment]
AP plans to address menu links via new link checker build. Related thread: https://dsva.slack.com/archives/C03LFSPGV16/p1702575451951519

Closing this ticket as a result. Once the new solution ships, if we have cleanup work required, we can file new tickets.

Description of the AP plan: 
* File in flight as of today: https://github.com/department-of-veterans-affairs/va.gov-team/blob/2afe96970777998f1fc823c4dd4ac97b8073279a/platform/cms/accelerated_publishing/rfc/broken-link-checking.md
* Where it will live in main once it merges: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/accelerated_publishing/rfc/broken-link-checking.md
