### ISSUE TITLE
Home page news promo block type: Add additional CTA options to dropdown

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-cms#11172]
## Description
The first homepage iteration uses a hard-coded CTA as the quickest solution but we know editors will need a way to be flexible while compliant with content and accessibility guidelines. 

We're considering a select within Drupal for the CTA with options such as "Read full article", "View event details", etc

## Tasks
- [ ] Define possible use cases for news promo spot
- [ ] Work with Laura/Danielle and team to define appropriate CTA link text
- [ ] Drupalize

**Comment by mmiddaugh** [comment]
I think you're right - thanks for catching that, @jilladams I updated #11171 for benefit promos

**Comment by FranECross** [comment]
Closing per the comments above.
