### ISSUE TITLE
[Homepage post-MVP] - Benefit promo CTA dropdown

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-cms#11171]
## Description
The first homepage iteration uses a hard-coded CTA as the quickest solution but we know editors will need a way to be flexible while compliant with content and accessibility guidelines. 

We're considering a select within Drupal for the CTA with options such as "Read full article", "View event details", etc

## Tasks
- [ ] Define possible use cases for benefit promo spot
- [ ] Work with Laura/Danielle and team to define appropriate CTA link text
- [ ] Drupalize

**Comment by jilladams** [comment]
For benefit promos, the CTA link text is configurable, e.g.
https://prod.cms.va.gov/block/208?destination=/admin/structure/block/block-content
![Screen Shot 2022-12-22 at 1 48 44 PM](https://user-images.githubusercontent.com/85581471/209231934-c76483cf-4799-40a4-b07b-c3b1a4758ec6.png)

This is only relevant for News promo. Closing.
