### ISSUE TITLE
Injected header postmortem: review & follow up 

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#11187]
## Description 
* Incident: https://dsva.slack.com/archives/C52CL1PKQ/p1665146147067899 -- The VSP Identity team converted a modal to use a web component. That web component wasn't processed for use in the injected header, so the modal was not hidden but displayed as text in the injected header. 

<img width="1448" alt="Screen Shot 2022-10-07 at 9 00 54 AM" src="https://user-images.githubusercontent.com/85581471/195161706-2cec4b1c-66df-4ea0-a6bb-84351b9caf55.png">

* Postmortem: https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Postmortems/2022/2022-10-07-web-component-breaks-teamsites.md

**Tasks:**
Owner of this ticket should 
* comb the postmortem and update it for accuracy where needed
* Review for where tickets should be created to close loop & guarantee a better future for the injected header

## Acceptance Criteria
- [ ] Tickets created for follow up
- [ ] Share links to new tickets with @wesrowe for prioritization / adding into an epic

**Comment by ryguyk** [comment]
Closing this issue with the result of its work being [a newly created epic to capture all of the future work](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11242) that specifically came out of this postmortem as it relates to the Public Websites team.
