### ISSUE TITLE
Migrate React Fileinputs to new VA design system components

### ISSUE THREAD

**Issue by jtmst** [department-of-veterans-affairs/va.gov-cms#11188]
Follow up to audit from issue: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10820

> The Design System has added a File input web component va-file-input. The React FileInput component has been deprecated so please plan to migrate to the  new web component. Specifically, the additionalClass and additionalErrorClass properties will no longer be available and the input change event structure has been modified as well. For more details on usage, review the [component documentation](https://design.va.gov/components/form/file-input). If you have questions, contact us on Slack in [#platform-design-system](https://dsva.slack.com/archives/C01DBGX4P45).

The following three instances of fileInput should be updated to new design system components:

src/applications/claims-status/components/AddFilesForm.jsx
src/applications/financial-status-report/components/FileUploader.jsx
src/applications/mhv/secure-messaging/components/ComposeForm/ComposeForm.jsx

## Acceptance Criteria
- [ ] Migrate FE components to new design system components
- [ ] Ensure functionality does not change
- [ ] Ensure code owners are alerted and review these changes for non PW owned files
- [ ] As a user, I can use the file input design system component on secure-messaging to upload a file while not logged in
- [ ] As a user, I can use the file input design system component on financial status to upload a file while not logged in
- [ ] As a user, I can use the file input design system component on claims status to upload a file while not logged in

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [X] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by wesrowe** [comment]
@jilladams, we think this might be a no-op. Confirm?

**Comment by jilladams** [comment]
True. from codeowners: 

1. src/applications/claims-status @department-of-veterans-affairs/benefits-team-1-frontend @department-of-veterans-affairs/vsa-debt-frontend
2. src/applications/financial-status-report @department-of-veterans-affairs/vsa-debt-frontend
3. src/applications/mhv/secure-messaging @department-of-veterans-affairs/vfs-mhv-secure-messaging
