### ISSUE TITLE
Evaluate the Claro drupal admin theme for our use case. 

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#1119]
## User Story or Problem Statement

* What would switching from Seven to Claro offer us? 
* Are there outstanding issues that would prevent us from adopting it?
* How much impact would this have on our users? What might be the pros of adopting it sooner than later? 

## Acceptance Criteria
* Claro is installed in a PR enviro for demo purposes
* A cross-disciplinary team has met to review it
* We have answered some of the questions above 
* We've evaluated the LOE for https://www.drupal.org/project/drupal/issues/3066007 and left some notes here about where we might get involved, if this was a direction we wanted to go in.

## Implementation steps
* install and enable and get up on a PR enviro for evaluation
* call a meeting
* document

**Comment by jefflbrauer** [comment]
@kevwalsh I think a more specific AC would be:  An evaluation of the Claro theme to our custom modules is completed, including an analysis/LOE of additional work to apply it to our custom modules

**Comment by kevwalsh** [comment]
My first thoughts 
- I like the approach to breadcrumbs and tabs on the content view pages. 
- Edit pages reveal a lot of bugs, especially with draggable elements and other form widgets.
- The screens are a lot less dense, which may be frustrating to our users who want to see a lot of information at once (such as on content listing screens like /admin/content) 
- We’d have to reconfigure blocks (not a lot of efort) 
- Very different approach to status messages (like errors and warnings)
- Definitely looks more modern
- might be a good basis for applying more of the VA Design system in the backend.

**Comment by kevwalsh** [comment]
PR environment: for evaluation: http://pr1173.ci.cms.va.gov/

**Comment by kevwalsh** [comment]
![Servicemembers’_Group_Life_Insurance__SGLI____Veterans_Affairs](https://user-images.githubusercontent.com/643678/76673050-1d489b80-6578-11ea-8920-f6fd093f7d40.jpg)

![Content___VA_gov_CMS](https://user-images.githubusercontent.com/643678/76673061-46692c00-6578-11ea-9b6b-7f8cba7f906c.jpg)

![Content___VA_gov_CMS](https://user-images.githubusercontent.com/643678/76673075-68fb4500-6578-11ea-9aa9-08893885b233.jpg)

![Edit_Benefits_detail_page_VA_blind_and_low_vision_rehabilitation_services_-_EDITED___VA_gov_CMS](https://user-images.githubusercontent.com/643678/76673118-ad86e080-6578-11ea-981b-88faf75709fe.jpg)


![Edit_Benefits_detail_page_VA_blind_and_low_vision_rehabilitation_services_-_EDITED___VA_gov_CMS](https://user-images.githubusercontent.com/643678/76673106-9c3dd400-6578-11ea-8bf8-1cb2e4da57bb.jpg)
