### ISSUE TITLE
CMS: Add VBA services content type 

### ISSUE THREAD

**Issue by dsinla** [department-of-veterans-affairs/va.gov-cms#11197]
## Description
#10504 identified additional fields we should add to the CMS to support the source VBA database. Using the diagram provided in 10504, and the Vet Center - Facility Service as references, add the new VBA Facility Service content type. **I believe we can reuse existing fields for all of these.**

## Acceptance Criteria
- [x] Facility (field_office)
- [x] Service Name (field_service_name_and_descripti) - this would be fed by a view (but the view doesn't exist yet)
  - [x] This is filtered by any services with the _display for VBA checkbox_
- [x] VBA Service Description (field_body)
- [x] Section (field_administration)
- [x] Enforce Unique Combo (field_enforce_unique_combo) _shouldnt be able to create a duplicate service at same facility_
   - [x] field_service_name_and_descripti
   - [x] field_office   

### Update to VBA Facility content type
- [x] Add Services (field_vba_services) field to VBA Facility (entity reference to VBA Facility Service)

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by swirtSJW** [comment]
There is not enough detail here to act on yet and it is blocked by #11198

**Comment by omahane** [comment]
TODO: Update behat tests

**Comment by omahane** [comment]
# Facility select list on the VBA Facility Service

it is unclear whether we need to winnow the facilities in the VBA Facility Service dropdown.

We have 462 facilities currently, which are available.

## Long list of facilities
<img width="1728" alt="Screen Shot 2022-10-24 at 4 18 35 PM" src="https://user-images.githubusercontent.com/766573/197633855-894df08e-7259-46a5-8f97-249a027fc193.png">

## Not too sections for winnowing the facilities
<img width="1714" alt="Screen Shot 2022-10-24 at 4 19 19 PM" src="https://user-images.githubusercontent.com/766573/197633848-826381b9-a3d0-4a09-aa4e-21096015079b.png">

The current list of sections is not likely to be useful for winnowing the facility select list, if we need to do that.

## Editor role for VBA missing
<img width="948" alt="Screen Shot 2022-10-24 at 4 30 18 PM" src="https://user-images.githubusercontent.com/766573/197633844-49d694d2-c447-4829-a3d0-b57cd7748960.png">

Right now, there is no role for an editor to create or edit the VBA services. Do we need one?

**Comment by omahane** [comment]
## TODO
Add Inline Entity Form for VBA Facility Service
