### ISSUE TITLE
Configure Tugboat to PHP 8.1 on a testable base preview on a new branch

### ISSUE THREAD

**Issue by edmund-dunn** [department-of-veterans-affairs/va.gov-cms#11191]
## Acceptance Criteria
- [x] Configure Tugboat to use PHP 8.1 with a testable base preview on a new branch
- [x] Link to testable environment is posted to this issue

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [x] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [x] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by ElijahLynn** [comment]
PR is here https://github.com/department-of-veterans-affairs/va.gov-cms/pull/11200 for now.

**Comment by ElijahLynn** [comment]
PHP 8.1 is on Tugboat with a base preview here and is ready for broader testing/review.

https://vacms-10870-php-8-upgrade-qrgd3pk2n13eoflyze9j06d32caiockw.ci.cms.va.gov/
https://vacms-10870-php-8-upgrade-qrgd3pk2n13eoflyze9j06d32caiockw.ci.cms.va.gov/admin/reports/status/php

**Comment by ElijahLynn** [comment]
Closing as the ACs are met and we are not going to merge yet.

**Comment by ElijahLynn** [comment]
Re-opening as, after this was merged to the `VACMS-10870-upgrade-to-php81` branch, the new base preview rebuild started throwing this error on `composer install`:

```
composer install
...
Generating optimized autoload files

Fatal error: Invalid opcode 137/1/0. in phar:///usr/local/bin/composer/vendor/composer/class-map-generator/src/PhpFileCleaner.php on line 168
2022-10-20T19:50:28.070Z - Command Failed (Tugboat Error 1064): Exit code (255)
````

**Comment by ElijahLynn** [comment]
Okay, after shelling in and doing a `composer nuke` then `composer install` then it works fine. If I do another `composer install` without doing a `composer nuke` then it gets the same error.

**Comment by ElijahLynn** [comment]
Interesting, on another attempt, an initial `composer nuke` resulted in the same error, and a second attempt worked.

**Comment by ElijahLynn** [comment]
Okay, after the `composer install` does work (after the nuke) then the next composer install fails with the same invalid opcode error.

**Comment by ElijahLynn** [comment]
If I change `"optimize-autoloader": true,` to `"optimize-autoloader": false,` in composer.json, then `composer install` works fine without nukes etc.

**Comment by ElijahLynn** [comment]
I'm closing this issue as done :heavy_check_mark: and taking care of this new bug "fatal error: invalid opcode" in a new issue. We have a working branch now with a live base preview and can still move forward while we fix this new issue in https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11315.
