### ISSUE TITLE
Content Audit: references to logon services that do not list Login.gov

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#11208]
## 1. Please provide any context around your audit
https://github.com/department-of-veterans-affairs/va.gov-team/issues/47192
> We recently discovered there are still benefit detail and R&S pages that don't list login.gov as an option for sign-in (with MyHealtheVet, DS Logon, and ID.me). We need to do an audit of our pages and add it as an option wherever it's missing.
  
## 2. What are the terms you are searching for within the CMS? Are there alternate spellings?
DS Logon, ID.me, MyHealtheVet: to see if [Login.gov](http://login.gov/) is missing from those mentions on pages.

e.g.  https://www.va.gov/claim-or-appeal-status/
 https://www.va.gov/resources/claim-status-tool-faqs/
 https://www.va.gov/education/gi-bill/post-9-11/ch-33-benefit/
 https://www.va.gov/resources/ask-va-replaces-iris-and-the-gi-bill-help-portal/

## 3. Are there components, elements or content types related to your search?
Sitewide, need to find all in-page content that mentions logging in without login.gov reference, specifically in deeper rich text fields past the intro.

## 4. Does a corresponding audit need to be run on the Veteran-facing website?  
  - [X] Yes - it's unlikely that there's hard-coded content matching this situation, vs. Drupal content, but we should confirm if we can. 
  - [ ] No

## 5. When do you need the audit to be completed
Not urgent, but when possible.

## CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [X] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by jilladams** [comment]
Per Steve: if it's limited to rich text fields, we have an audit tool that can help, but we believe it doesn't suffice here / didn't catch a few of these listed examples.

**Comment by EWashb** [comment]
So sorry I dropped the ball when I was out on this one @jilladams 

I'll take a look at incorporating this into our next sprint.

**Comment by jilladams** [comment]
@EWashb we're tracking this in our board for Sprint 71, and DaveC didn't flag that as a problem vs. sending it to you guys, so feel free to ignore, I think! (fyi @wesrowe )

**Comment by EWashb** [comment]
@jilladams @wesrowe this will likely be blocked by a content audit of "space force" content. However, that audit will inform this one. Edmund will be doing the space force audit this sprint (sprint 71)

**Comment by jilladams** [comment]
Ok. I'm going to remove Public Websites label, to de-confuse sprint reporting on this one.

**Comment by EWashb** [comment]
This will be taken care of as part of https://github.com/department-of-veterans-affairs/va.gov-cms/pull/11706. Once that search is implemented then the content team will be able to do a self-service audit in the CMS.

@jilladams this still may need some FE audting

**Comment by jilladams** [comment]
FYI @wesrowe

**Comment by wesrowe** [comment]
We'll keep an ear out for how the self-service audit goes. Notify me and Jill if further action is required from PW.

**Comment by EWashb** [comment]
This has been taken care of by the self-audit tool
