### ISSUE TITLE
DSN: Recruit and schedule participants for VBA Public Contact Staff research

### ISSUE THREAD

**Issue by davidmpickett** [department-of-veterans-affairs/va.gov-cms#11209]
## Description

**Editor-facing research**
* The Research Lead should work with Product Manager, Product Owner, and Business Stakeholders to identify a list of potential participants
  * The pool of potential participants should be at least 2-3 times larger than the desired # of participants
* The Research Lead contacts and schedules participants 
  * Using their VA.gov email address or the shared VADrupalCMS@va.gov email address
  * Consider using Calendly or Microsoft Bookings to set up timeslots so participants can pick slots
* Once participants are scheduled, the Research Lead invites other team members to official calendar events
* The Research Lead should schedule a [pilot session](https://depo-platform-documentation.scrollhelp.site/research-design/research-checklist#ResearchChecklist-4.Runapilotsession)
* The Research Lead should schedule 30-minute Daily Reseach Debrief meetings and invite Notetaker(s) & Observer(s)

## Acceptance Criteria
- [x] Ensure the target number(s) of participants have been recruited and scheduled (for overall & primary criteria)
  - Schedule 20-25% more sessions than the desired # of participants to account for no-shows & cancellations 
- [ ] Ensure that moderator(s), notetaker(s), and observer(s) are invited to research sessions
- [x] Schedule Pilot session
- [ ] Schedule Daily Research Debriefs and invite relevant team members 

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by davidmpickett** [comment]
@dawnpruitt @dsinla - Was there any expectation that this work will begin this sprint?

**Comment by dsinla** [comment]
@davidmpickett @dawnpruitt Originally we hoped the initial scheduling could have been started (not that the interviews would occur in this sprint, but that the scheduling of the interviews could have been started). We needed to identify the Research Lead who will be the interviewer, and the interviewer has to provide open windows, which we can then bring to the list of interviewees.
Having said that, all parties recognized that this was on pause given the loss of our research resource.

**Comment by davidmpickett** [comment]
Note that since we did not screen for length of time in position in the initial participant identification, we will need to layer that into the scheduling communications so we have that data and can judge whether we are getting the sample we want.

**Comment by EWashb** [comment]
Jay or Max to help with pilot?

**Comment by EWashb** [comment]
Keep Dave C in the loop with any challenges with recruitment. He will support or assist with a pivot.

**Comment by davidmpickett** [comment]
Pilot session scheduled with Jay

**Comment by davidmpickett** [comment]
Email sent to 19 public contact staff. Calendly slots available from Nov 28 - Dec 6.

Plan for non-responders
-I will send individual follow-up emails to non-responders next Tuesday afternoon. & give them a deadline of next Friday to sign up.
- I will let the team know how we are doing with scheduling at that point so we can determine how strongly to push on ROs POCs
- We can ask the RO POCs on Wednesday to remind their chosen contacts and reiterate a deadline of choosing a slot by Friday.

**Comment by davidmpickett** [comment]
12 sessions are scheduled. All MVP ROs are represented
