### ISSUE TITLE
Update St Petersburg URLs from #11035 to remove dot

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#11201]
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11035

In that ticket, 4 redirects were specified to point to: 
https://www.va.gov/st.-petersburg-vet-center/

That's not a functioning URL, so those are returning 404s. The correct URL for those redirects should be: 
https://www.va.gov/st-petersburg-vet-center/

Acceptance Criteria:
- [ ] www.va.gov/find-locations/facility/vc_0301V	redirects to https://www.va.gov/st-petersburg-vet-center/
- [ ] www.va.gov/directory/guide/facility.asp?ID=557&dnum=All redirects to https://www.va.gov/st-petersburg-vet-center/
- [ ] www.va.gov/directory/guide/keystaff.cfm?id=557 redirects to https://www.va.gov/st-petersburg-vet-center/

**Comment by dsasser** [comment]
@jilladams issue description says:

> In that ticket, 4 redirects were specified to point to:

It was actually 3 instances instead of the mentioned 4. See https://github.com/department-of-veterans-affairs/devops/pull/12040/files (the original PR) and https://github.com/department-of-veterans-affairs/devops/pull/12098/files (the latest PR for this bug).

**Comment by dsasser** [comment]
PR was merged. I'm not sure of the release schedule for the devops repo to know when we should expect to see changes on prod.

**Comment by jilladams** [comment]
Nice! It'll auto deploy Wed am.  (We learned this recently, and I added to [CMS & Front-end Build jobs google doc](https://docs.google.com/spreadsheets/d/164H07n4FChg-JxJZu964nfg2wAX0kPD0SjTfZMhzj_I/edit#gid=0) if you ever need for future ref.)

**Comment by dsasser** [comment]
@jilladams I tested these and they are working as expected. Closing.
