### ISSUE TITLE
DSN/CMS: Assess Lovell TRICARE implications for four VAMC centralized content nodes

### ISSUE THREAD

**Issue by davidmpickett** [department-of-veterans-affairs/va.gov-cms#11215]
## Description
This is a spin-off of #11212

In addition to whatever logic might be need to create separate instances of these pages for VA & TRICARE, we also need to think through how to adjust these nodes that are several branches up the section hierarchy.

- Medical records
- Register for care
- Policies
- Billing and insurance

![Screenshot 2022-10-24 160946](https://user-images.githubusercontent.com/51967950/197630085-3cf10c18-e5ce-4788-9d33-032cb5c55d5f.png)

## Proposed Solution
- [x] The Lovell VA version of these four nodes/pages should be set to use Solo logic rather than Clone logic
- [x] Four VAMC Detail Pages should be spun up on the Lovell TRICARE side with these names so all the links to these pages work
- [-] [Lovell KBs](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10027) should be updated to reflect that these pages are managed Nationally on Lovell VA and locally for Lovell TRICARE  Moved this to #10027

## Acceptance Criteria
- [x] Proposed solution is documented
- [ ] Proposed solution is approved by Dev & PM & PO
- [ ] Subsequent tickets created and added to Lovell Punchlist

**Comment by davidmpickett** [comment]
When we have an assessment of this and a plan, we can potentially communicate that + the Lovell Taxonomy suggestions from #11123 as a package

**Comment by dsinla** [comment]
Simplest alternative is to not use the national-content pages. TRICARE side will have to develop content that in not the hardened page.

**Comment by davidmpickett** [comment]
Proposed solution is outlined and ready for review. Call scheduled tomorrow with @JayDarnell @swirtSJW @dsinla

**Comment by swirtSJW** [comment]
I just moved the existing hardened pages to Lovell VA section and the old detail page version to the Lovell Tricare section.
Content team will have to adjust wording on the Tricare detail pages before publishing them.

The KB part is the only one that is not addressed at this time.

**Comment by swirtSJW** [comment]
Calling this done.
