### ISSUE TITLE
CMS: Lovell nodes/pages that should use Twin Logic, not Clone logic

### ISSUE THREAD

**Issue by davidmpickett** [department-of-veterans-affairs/va.gov-cms#11212]
## Description

In my very initial pass at poking around in the Lovell Tugboat environment, I found quite a few instances of pages that are using Clone logic that should be using twin logic. That is to say, these pages are currently in the parent "Lovell Federal health care" section rather than having separate instances in both Lovell VA and Lovell TRICARE sections. 

- Health Services
- Make an appointment
- Pharmacy
- Patient advocates

All of these pages were clearly marked as Twin types in the [Lovell Content model](https://airtable.com/appojvgFB7lvqgArz/tbljDFflQvxuHBWJK/viw0N9Q9DH5J3hjz5?blocks=hide) because they are pages where there will need to be different information for VA and TRICARE audiences.

Here's some screenshots for the Health Services page as an example

![Screen Shot 2022-10-13 at 1 48 28 PM](https://user-images.githubusercontent.com/51967950/195681113-2a420261-af3c-447a-b194-fc5a451b295a.png)

![Screen Shot 2022-10-13 at 1 52 44 PM](https://user-images.githubusercontent.com/51967950/195681990-c6c4fcaa-7851-4992-a189-ff7354a25663.png)

## Acceptance Criteria
~~- [ ] These pages all have two separate instances, one in Lovell VA and one in Lovell TRICARE~~
- [ ] Consult with VHADM on each page and determine whether the service has a presence on the TRICARE 
- [ ] For every TRICARE service, create a corresponding TRICARE-only page 

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by davidmpickett** [comment]
Not sure how much this will be intertwined with updating the Services Taxonomy to account for TRICARE https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11123

**Comment by davidmpickett** [comment]
Already found some other pages that have the exact same problem:
- Make an appointment
- Register for care
- Pharmacy
- Policies
- Patient advocates
- Medical records office
- Billing and insurance

Not sure why there is such a huge discrepancy here. If this was an oversight, that's fine. But if this was an intentional series of decisions to contradict the content guidance, that should have been a conversation.

**Comment by davidmpickett** [comment]
I'm aware that there were other places where the CMS build intentionally deviated from what I had in the Content Model. For instance: 
- Some nodes/pages I had marked as Solo got turned into Clones (e.g. Work with us). Make sense, and we discussed this as a possibility in advance. 
- Some nodes/pages I had marked as Clones got turned into Twins (e.g. New Releases). This also makes sense and was a huge technical accomplishment. Huzzah!
- But (intentionally) taking something I marked as Twins making them Clones is essentially a huge editorial/content design decision. We already know this content will need to have variations for VA and TRICARE. If there is a technical limitation, then we need to weigh the competing needs. 

Again, i recognize this may have just been an oversight rather than intentional, but I just wanted to document my concerns here so there's a clear trail to follow.

**Comment by davidmpickett** [comment]
Did some further poking. These four pages seem to have significant portions that are locked down nationally. That is, they are managed mostly as the VHA > VAMC section level 
- Medical records
- Register for care
- Policies
- Billing and insurance
The extent to which Lovell TRICARE pages will need to suppress / replace some of this content needs to be understood and scoped out.

**Comment by JayDarnell** [comment]
I suspect many of these items that are incorrectly categorized (twins vs clones) simply haven't been tackled yet. @swirtSJW is the only person (to my knowledge) who actively made content changes on production to pave the way for testing and I wasn't under the impression those changes were necessarily all encompassing.

**Comment by davidmpickett** [comment]
I updated the description to remove these four things
- Billing and insurance
- Medical records office
- Register for care
- Policies
They will be addressed in #11215

**Comment by swirtSJW** [comment]
Most of the pages in question are just the original pages that are still assigned to lovell federall (both).   They need to be edited and reassigned to lovell VA and in some cases have tricare versions created.

**Comment by dsinla** [comment]
@davidmpickett  @JayDarnell and @swirtSJW 
Weighing in here after a discussion with Swirt and Jay. We have questions around this set that we know are (legally?) required for VAMCs, but we're not sure if they exist on the TRICARE side. @swirtSJW's logic was "While we're indeterminant if it's going to both sides, let's not create two pages only to eliminate one later." 
I've put this question to VHADM about these 9 pages, and will continue to pursue with them. And am leaving these as clones (ie assigned to Lovell Federal health care) for now.

- VA Patient Advocates
- Caregiver support
- Homeless Veteran care
- LGBTQ Veteran care
- Mental health care
- Minority Veteran care
- Returning service member care 
- Suicide prevention
- Women Veteran care 
-

**Comment by dsinla** [comment]
We can create pages where we are uncertain, and just choose not to publish when the decision is made.
Main goal here on VA side is to provide contact info for a named individual.
We're basing this on the Required list for VA, but won't spin up special Service Description (detail) page for other services 
Programs page can used if Lovell wants to highlight a specific service.

**Comment by JayDarnell** [comment]
I'm going to take a first pass at this @dsinla and sync up with you after.

**Comment by dsinla** [comment]
As discussed today, we will focus on providing VHADM and the Editors all the tools they need to create content, and rely on them to make the best decisions on what content is best shared with VA visitors and with TRICARE visitors.

@JayDarnell attaching the XLS I've been using - noting that this is just a snapshot of the current understanding.

[LovellContentSitemap.xlsx](https://github.com/department-of-veterans-affairs/va.gov-cms/files/10015618/LovellContentSitemap.xlsx)

**Comment by dsinla** [comment]
As discussed in meetings with Dev and PO, it will be up to VHADM and the Lovell authors to determine if content is identical across both systems, similar, or if content only exists in one system.
If  a page is indeterminant, then we'll leave that page assigned to Lovell Federal health care section -rather than create two pages, one of which might have to be removed later. 

Latest sitemap: 
[LovellContentSitemap.xlsx](https://github.com/department-of-veterans-affairs/va.gov-cms/files/10051028/LovellContentSitemap.xlsx)
