### ISSUE TITLE
Some Operating Status pages are outputting Linky URLs

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#11216]
## Description
A rich text field on Operating Status pages is using the 'value' of its field rather than the 'processed' value.

## Example
https://www.va.gov/north-florida-health-care/operating-status/
* Health Chat App: https://www.va.gov/admin/content/linky/58

## Mitigation
Fix the GraphQL query

**Comment by swirtSJW** [comment]
I believe this is closed as a result of the merged PRs ^^.  Closing.
