### ISSUE TITLE
DSN: Conduct VBA Public Contact Staff Research Review Cycle

### ISSUE THREAD

**Issue by davidmpickett** [department-of-veterans-affairs/va.gov-cms#11210]
## Description

- Veteran-facing research must go through Platform's [Research Review Cycle](https://depo-platform-documentation.scrollhelp.site/research-design/research-checklist#ResearchChecklist-2.Researchreview)
- Editor-facing research must go through the [CMS Collaboration Cycle](https://va-gov.atlassian.net/wiki/spaces/VAGOV/pages/1791459333/CMS+Collaboration+Cycle)

Note: This step is a hard blocker for Veteran Recruitment, but less so for Editor Recruitment. 

## Acceptance Criteria
- [x] Create the necessary tickets for the Review Cycle
- [ ] Incorporate any feedback from the Review Cycle into the Research Plan and Conversation Guide
- [ ] If there are significant alterations, consult your Product Manager or Product Owner
- [ ] Once approved, move on to Participant Recruitment & Scheduling 

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by jcklpe** [comment]
@sstrassberg : Quick question. Do we need to engage Platform research review cycle for this work? We'll be talking with subset of Public Contact Staff at Veteran Benefit offices. Sitewide Crew has an internal research review cycle for CMS Editor research. This research will be with VA employees, but not editors, and specifically it is supposed to be giving us insight about the Veterans even though we won't directly engaging them as part of the research.

**Comment by sstrassberg** [comment]
@jcklpe I think you should still use the research plan and convo guide templates, then add to research repo, but they don't need to go through formal review since you are not recruiting veterans. There is an audience tag for internal VA. Also, you cannot compensate VA employees for their participation, which is what Dave Conlon's note might be referencing.

**Comment by dsinla** [comment]
Suggesting a review by @davidconlon @dsinla @dawnpruitt as sufficient.

**Comment by dsinla** [comment]
confirmed with @davidconlon . close with https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11580

**Comment by davidmpickett** [comment]
Conversation guide sent for review
