### ISSUE TITLE
New Facility: Sonora VA Clinic

### ISSUE THREAD

**Issue by stefaniefgray** [department-of-veterans-affairs/va.gov-cms#11231]
## Background

*What triggered this runbook?*
Sent by editor: https://va-gov.atlassian.net/browse/VAHELP-4953

*Please attach Facility Locator link and https://prod.cms.va.gov/ link to this ticket*
https://www.va.gov/find-locations/facility/vha_612GL
https://prod.cms.va.gov/northern-california-health-care/locations/sonora-va-clinic

*Please also include link to Jira help desk ticket, if applicable*
See above

### VAMC
Please refer to the Knowledge Base article titled "How do I add a facility to my health care system?" for more information: https://prod.cms.va.gov/help/vamc/about-locations-content-for-vamcs/how-do-i-add-a-facility-to-my-health-care-system

#### CMS help desk steps
- [x] 1. Become aware that the new facility is now on the Facility API (typically, via a Flag, but this may come in as a helpdesk ticket).
- [x] 2. If the editor has followed the steps from the above Knowledge Base article and included which section and VAMC the facility belongs to (i.e. VA Pittsburgh), great! **Proceed to step 3.** If not, please check with the editor or VHA digital media regarding what section and VAMC it belongs to.
- [x] 3. Updates the Section (default is "VAMC facilities", but it should be a VAMC system in a VISN) and VAMC system field accordingly.
- [x] 4. Communicate with editor (cc VHA Digital Media) to give them go-ahead to complete the content, with this [KB article](https://prod.cms.va.gov/help/vamc/about-locations-content-for-vamcs/how-do-i-add-a-facility-to-my-health-care-system). (See sample notification email below)
- [ ] 5. When editor has prepared content and let help desk know, reassign this issue to appropriate CMS engineer on Product Support team, for bulk publishing.

    #### Sample notification email:
    Hello! You should now be able to edit the draft page for this facility, located at [LINK TO NEW FACILITY DRAFT PAGE ON PROD]

    Important: Please make sure that all relevant steps listed within the “How do I add a facility to my health care system?” Knowledge Base article have been completed: https://prod.cms.va.gov/help/vamc/about-locations-content-for-vamcs/how-do-i-add-a-facility-to-my-health-care-system
    
    Once finished, please save this page (and all related VAMC Facility Health Service pages) in the moderation state “Draft." Please do not save them as “Published.”

    Please let us know once your draft is complete, so that we can wrap up the technical process from our end and ensure that the new facility and all linked health services publish to the live site as intended. Thanks!

#### CMS engineer

Redirect request:
- [x] Submit a [redirect request](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/new?assignees=&labels=Redirect+request&template=redirect-request-facility-url.md&title=Redirect+Request+for%3A+%3Cinsert+facility+name%3E) to the devops repo from the original URL for the Facility to the newly updated URL once it changes systems

(These are usually released Wednesday afternoons so you should coordinate the remaining items below around that timeframe)

Update the new facility node:
- [x] Change the Facility Locator API ID on the new facility, to the Facility Locator API ID for the old one.
- [x] Change the section to the old one
- [x] Change the VAMC system to the old one
- [x] Update the Menu link (Parent link) to the old system (unable to delete it)
- [x] Check the box under URL alias to **Generate automatic URL alias**
- [x] Archive the facility with good log message
- [x] Manually disable the menu link for this item directly in the system menu

Update the original facility node:
- [x] Change the Facility Locator API ID on the old facility, to the Facility Locator API ID for new one
- [x] Change the section to the new one
- [x] Change the VAMC system to the new one
- [x] Update the Menu link (Parent link) to the new system
- [x] Check the box under URL alias to **Generate automatic URL alias**
- [x] Publish changes with good log message

Update related content (VAMC Facility Health Services, VAMC Non-clinical Services, Events, Stories, etc)
- [x] Bulk edit the VAMC Facility Health Services for the original Facility (update the section to the new section)
- [x] Manually edit each VAMC Facility Health Service (updating the VAMC system health service to use the new system)
- [x] Bulk edit the VAMC Facility Health Services to **Update URL alias**
- [x] Bulk edit the VAMC Facility Health services to **Resave content** (now the urls will be correct)

In the production DB:
- [x] Remove the migrate_map entry for the new facility
- [x] Update the migrate_map entry for the old facility, updating the facility locator api id to the new one (sql command in drush)

**Scripts to run**

`drush sql:query "DELETE FROM migrate_map_va_node_health_care_local_facility WHERE sourceid1 = 'vha_612GL'"`

`drush sql:query "UPDATE migrate_map_va_node_health_care_local_facility SET sourceid1 = 'vha_612GL' WHERE sourceid1 = 'vha_640GB'"`

In [Lighthouse Facilties](https://github.com/department-of-veterans-affairs/lighthouse-facilities)
- [x] CMS engineer updates the [CSV in Lighthouse](https://github.com/department-of-veterans-affairs/lighthouse-facilities/blob/master/facilities/src/main/resources/websites.csv) with the changed URL, creating a PR, tagging the Lighthouse team and linking to it in Slack with an @mention to a Lighthouse team member 

PR created here: https://github.com/department-of-veterans-affairs/lighthouse-facilities/pull/408

- [ ] HD notifies editor and any other stakeholders.

#### CMS Help desk
- [ ] 9. HD notifies editor and any other stakeholders.

### Vet Center

CMS help desk steps
- [ ] 1. Become aware that the new facility is now on the Facility API (typically, via a Flag).
- [ ] 2. Check with RCS(?) what district it belongs to.
- [ ] 3. Move the section to the appropriate district.
- [ ] 4. Communicate with editor (do they need to be onboarded) @todo write sample email.
- [ ] 5. When editor has prepared content and let help desk know, reassign this issue to appropriate CMS engineer on Product Support team, for bulk publishing.

CMS engineer
- [ ] 6. CMS engineer bulk publishes nodes and facility.
- [ ] 7. CMS engineer edit facility node and remove `New facility` flag and save node.
- [ ] 9. Let help desk know this has been done.

CMS Help desk
- [ ] 9. HD notifies editor and any other stakeholders.

## CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [x] `⭐️ User support`

**Comment by stefaniefgray** [comment]
@JayDarnell @omahane Here's another instance where an editor decided to go ahead and publish the clinic homepage and all facility health services to the live site... instead of saving as "Draft" as instructed

Should I un-publish and save these nodes as Archived, or leave them as Published and then defer to Facilities for next steps?

Clinic homepage:
https://prod.cms.va.gov/northern-california-health-care/locations/sonora-va-clinic

All health services are linked at the bottom ^^

**Comment by JayDarnell** [comment]
Because this is essentially a facility changing systems @omahane and I have started working on a new runbook for this sort of work here: https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/.github/ISSUE_TEMPLATE/runbook-facility-section-change.md

**Comment by JayDarnell** [comment]
@stefaniefgray when we have a facility change systems again in the future, we need to have the editors wait and not create a bunch of health services. We should just make sure the existing health services are transfered to the new system along with the facility and then let the editors make adjustments after that. Now we have two sets of services for one facility and its just noise in the CMS.

**Comment by JayDarnell** [comment]
Redirect request for this Facility system change: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12046

**Comment by swirtSJW** [comment]
Those look right @JayDarnell

**Comment by JayDarnell** [comment]
The redirect request was merged yesterday but hasn't been deployed to production yet.

**Comment by JQuaggles** [comment]
@JayDarnell What is this Blocked by?

**Comment by JayDarnell** [comment]
This was blocked waiting for the redirect request from the old address to the new address to be live on production @JQuaggles but unfortunately it looks like there are now three copies of this facility in the system and I am currently stumped as to why. I'm going to need to bring Steve in to understand why this happened.

**Comment by JayDarnell** [comment]
A redirect request for this facility probably should have also been added to this issue: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11903

Redirecting from https://www.va.gov/find-locations/facility/vha_612GL to the new CMS URL https://www.va.gov/northern-california-health-care/locations/sonora-va-clinic/

**Comment by swirtSJW** [comment]
Threads where there was fallout from the changes
https://dsva.slack.com/archives/C0FQSS30V/p1672760890907879
New changes being run
https://dsva.slack.com/archives/C02HX4AQZ33/p1672780591065769?thread_ts=1671640128.574559&cid=C02HX4AQZ33

**Comment by JayDarnell** [comment]
I have deleted the unnecessary 3rd facility. Tomorrow morning I'll check to verify it was not readded. If that is the case I'll update the runbook to reflect the changes to the scripts we ran to get the desired result.

**Comment by JayDarnell** [comment]
This redirect has been deployed to production and the most recent migration has not added a third copy of the facility node. @stefaniefgray I believe this is ready for you to follow up.

**Comment by JayDarnell** [comment]
Second redirect for "go-live". This is not something I've done in the past and would normally be performed when Sonora first went live on va.gov but this step used to be handled by a different team and was missed: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12181

**Comment by stefaniefgray** [comment]
Everything looks good from my end per the original Jira tickets; closing
