### ISSUE TITLE
BE: Remove Office-Directory content type, build step, and associated tech debt for canceled product

### ISSUE THREAD

**Issue by ryguyk** [department-of-veterans-affairs/va.gov-cms#11233]
## Description
With ever-increasing content putting us on a track towards build times that exceed our limit, we should consider all potential wasted build time. Currently, there is logic in content build aimed specifically at building out the Office Directory. Since this feature/application is nowhere near usability and not in active development, it's a top candidate for removal.

### Engineering Notes
There are two places where code can be removed:
1. There is [a step in the content build](https://github.com/department-of-veterans-affairs/content-build/blob/7f65ad6b24fb2cfac55085f900ffdeb7a5f722c8/src/site/stages/build/index.js#L118) specifically directed at pulling data from the CMS for the Office Directory. It can be removed.
2. The actual work of that step is captured in [this file](https://github.com/department-of-veterans-affairs/content-build/blob/main/src/site/stages/build/plugins/create-office-directory-data.js). This file can be removed altogether.

It's useful to note that if/when this functionality needs to return, the creation of the data (i.e. the work being done in the file listed in step 2 above) should be replaced by instead generating the data via the [KISS data config](https://github.com/department-of-veterans-affairs/content-build/blob/7f65ad6b24fb2cfac55085f900ffdeb7a5f722c8/src/site/stages/build/drupal/static-data-files/config.js).

## Acceptance Criteria
- [ ] FE: Consolidate FE removal to a concise set of commits in content-build
- [ ] ~~List those commits here, for such time as we get unblocked and want to restore this work~~
- [ ] ~~Create issue for re-creating this step in a KISS pattern in the future and add to #7590~~
- [ ] ~~BE: Removed Offices [stuff - content type?] from CMS~~ _per [comment](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11233#issuecomment-1714216894) below, we need to leave the content type in Drupal for now, but should be able to remove it alongside retirement of the Outreach materials library_

**Comment by wesrowe** [comment]
@ryguyk, good call-out – can you please add a little detail so that this can be more easily estimated in Refinement?

**Comment by ryguyk** [comment]
@wesrowe Yes. This needs a lot more info. I just wanted to get it on paper first. I'll update here when I get a bit more time to iron out the necessary details.

**Comment by dsasser** [comment]
# Update 9/11/23

The FE work has been merged: https://github.com/department-of-veterans-affairs/content-build/pull/1705.

I'm working on the backend changes which I expect will be in PR mid afternoon today, and ideally mergable by COB or tomorrow morning.

**Comment by dsasser** [comment]
I'm not entirely sure we can remove the CMS data, as there are several Offices in the CMS, one of which is published: 

<img width="1699" alt="Screenshot 2023-09-11 at 8 48 35 AM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/221539/ab2330cf-61d6-4c60-b776-d29e6474bd43">

This produces the following page on the live site: https://www.va.gov/outreach-and-events/

**Comment by wesrowe** [comment]
We're going to have to change/retire the FE page where this Outreach and events node appears anyway when the Outreach Materials library moves to another platform. I'll make sure this AC gets transitioned to that work.

**Comment by dsasser** [comment]
Verified FE changes on Prod (ie: the build did not break);
