### ISSUE TITLE
Need to Revise Adding New VAMC Facility KB Article

### ISSUE THREAD

**Issue by stefaniefgray** [department-of-veterans-affairs/va.gov-cms#11243]
## Background context

**Topic**
The instructions that Editors receive when a new VAMC facility is added to Drupal (via VAST) do not stress the importance of saving the homepage as a **draft, not published** and **adding VAMC Facility Health Services.**

The instructions that Editors must follow once the new facility is available as a draft are buried under lots of introduction text and aren't simplified, stressed, or streamlined. Instructions should be boiled down to prominent, easy-to-follow bullet points.

Steps for draft homepage and instructions to add health services may even need a separate article vs. "How do I add a facility in the first place?"

Discussed with @TroyA6 on 10/18/2022 to brainstorm improvements

**Link to existing article:** https://prod.cms.va.gov/help/vamc/about-locations-content-for-vamcs/how-do-i-add-a-facility-to-my-health-care-system

**Specific updates needed for that article:**

- Veteran-centered purpose content is italicized which breaks content style guidelines
- Under the “Instructions” Heading on step 3, there is a warning that says “do not save this content yet”. It should perhaps be more specific as to what “this” is

**Vital step that must be linked:** https://prod.cms.va.gov/help/vamc/how-to-add-a-vamc-facility-health-service

**Person and team requesting the article:** 
- Stefanie Gray
- VA Drupal CMS Helpdesk team

**Associated SMEs/ stakeholders:** 
- [name them here]

**Audience:** 
Who is this intended for? Who would need this information? (i.e. Everyone, non-admins, etc.)
- VAMC Editors

**Related KB articles:** 
**Existing article:** https://prod.cms.va.gov/help/vamc/about-locations-content-for-vamcs/how-do-i-add-a-facility-to-my-health-care-system

**Vital step that must be linked:** https://prod.cms.va.gov/help/vamc/how-to-add-a-vamc-facility-health-service**

  
**Associated source of truth documentation:** 
- [for example, could be the VA content style guide]

**This article addresses:**
- [x] A business-driven need
- [x] A user-driven need

**Does this article have a deadline?**
- [ ] Yes: [name the deadline here]
- [x] No

**Is the article associated with change management initiatives?**
- [ ] Yes<br>
  [Change Management Epic](URL)
- [ ] No

**What parts of the interface will link to the article, if any?** 
- [list them here]

## Acceptance Criteria
- [ ] removed italics
- [ ] emphasized save as draft
- [ ] linked to facility services article

**Comment by stefaniefgray** [comment]
This is a ticket that I should personally take lead on, since I know how the Editors go through these steps, from their perspective

See also: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10545

@laflannery Should we keep this ticket, or keep the one you had created about this topic?

We can consolidate them and then close the other one out

**Comment by laflannery** [comment]
@stefaniefgray This is a product and should go to the product team - you would then review and revise it to be sure it can be understood by our editors but we really should try to have the product team do this to make sure we get all the possible product functionality into all product articles

**Comment by stefaniefgray** [comment]
Very fair! I should note that this is the article where editors currently have the most difficulty following the current steps (which is how we end up with prematurely published facilities lacking health services, a patient safety issue) -- so once I'm back I'd like to work with whoever is editing this article to make sure it makes sense from the editor's perspective 

Also, is it alright to keep both the Facilities and User Support labels? It helps this ticket show up on my and Troy's ZenHub board -- but if not and it's an either/or situation, that's okay too!

**Comment by xiongjaneg** [comment]
Made these updates, closing. Will create a new ticket for the KB article that will be needed post-CMS Team transition for process updates.
