### ISSUE TITLE
Draft Content Model for VBA Services

### ISSUE THREAD

**Issue by davidmpickett** [department-of-veterans-affairs/va.gov-cms#11250]
## Description

As a Facilities Team member, I need to understand the possible ways that VBA Service Content can be structured so that I can chose the one that aligns best with our goals for the Regional Office MVP.

As a CMS Platform team member, I need a document of the proposed content model to review as part of the CMS collaboration cycle for the Regional Office MVP. 

As a Regional Office MVP stakeholder, I need a high level summary of the plan so I can connect it to internal VBA resources.

Questions to consider
- What fields are needed in the VBA fieldset on the VA Service Taxonomy?
- What fields are needed in the VBA Service content type?
- What information is blobby vs hardened?
- What is national vs local?
- (stretch) How do VBA services connect to VBA Facilities content type(s)? 

Artifacts to produce
- Mural diagrams of relationships between content types / fields
- Spreadsheet of proposed fields & relationships
- Matrix of benefits vs tasks?
 
Area of [content model](https://app.mural.co/t/vagov6717/m/vagov6717/1658937741729/88cc653ce1bed251e60940c147867eb061496070?wid=0-1677268614480&outline=open) I will be focused on
![model](https://user-images.githubusercontent.com/51967950/221622002-01f13c46-45b0-4e5a-84e3-33e3893923bf.png)

## Acceptance Criteria
- [x] Draft content model for workshop
- [x] Hold first workshop with Dave C
- [ ] Revise content model based on workshop feedback
- [ ] Second workshop is scheduled

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by davidmpickett** [comment]
possible follow up for #9978

**Comment by kmariepat-cityfriends** [comment]
@Dottisea there were AC added to this card in sprint planning that I came back to see now and they are not there, you might have an unsaved edit hanging around, can you check?

**Comment by davidmpickett** [comment]
I believe the ACs were:
- Draft content model for workshop
- hold first workshop with Dave C
- Revise content model based on workshop feedback
- Second workshop is scheduled

**Comment by Dottisea** [comment]
Perfect @davidmpickett - added them above!

**Comment by davidmpickett** [comment]
Two quick IRL sketches 
![20230303_115621](https://user-images.githubusercontent.com/51967950/222794560-f924467a-d615-4772-ae32-43678b98d81b.jpg)

![20230303_115904](https://user-images.githubusercontent.com/51967950/222794585-924ded6f-e1a4-402d-83a2-80e51c7fc5e6.jpg)

**Comment by davidmpickett** [comment]
The Mural is going great https://app.mural.co/t/vagov6717/m/vagov6717/1677277602711/74cecb64b6eeb9558aa868240cd726b54fcb93a7?wid=0-1678215745064&outline=open

**Comment by davidmpickett** [comment]
New iteration of model added to Mural https://app.mural.co/t/vagov6717/m/vagov6717/1677277602711/74cecb64b6eeb9558aa868240cd726b54fcb93a7?wid=0-1678722022826&outline=open
