### ISSUE TITLE
Open linky admin to content-admin

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#11264]
## Description

The linky admin is currently only available to true admins.  We should consider opening it to content admins. 
 https://prod.cms.va.gov/admin/content/linky

This one is likely going to need some discussion... maybe with a few of our trusted content admins.
## Acceptance Criteria
- [ ] As a content_admin I can access https://prod.cms.va.gov/admin/content/linky
- [ ] As a content admin I can edit a linky
- [ ] There is an entry in the KB to guide me and call out the risks.

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [x] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by laflannery** [comment]
- UI Does not currently tell you everywhere the Linky Link is used
- Use case scenario at this time would most likely only be a broken link - 3rd party changed their URL and now we have multiple broken links throughout multiple nodes on our site.
- Troy and Dave C: A tool this powerful would be best left in the hands of fewer people
- Perhaps set up a runbook and request fulfillment process for this
  - Caveat: Safelinks could be fixed much more quickly using this tool but also we may have another way of doing this programatically.

**Next steps:**
- Make the tool known to folks with the Content team.  Make sure they know that this is available to be requested and create the runbook/process for requesting.
- Make a new KB article related to requesting a change

**Comment by laflannery** [comment]
We have decided not to open Linky up to more folks. Closing this issue in favor of next steps outlined in #11752
