### ISSUE TITLE
Create KB covering linky

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#11263]
## Description
Linky was recently introduced into the CMS however there was no explanation or direction given to the editors for Linky which is leading to some confusion.

Linky Notes:
- Purpose is to have a repository of external links
- Linky creates a "edit it once, fix it everywhere" situation for administrators to use
- How this works from Steve explaining this to someone in slack: 
  - "Linkies" get created anytime a link is made to an "external" place.  Unfortunately a link to [www.va.gov/anything](http://www.va.gov/anything)  looks like an external link because it is outside of the cms.
  - The idea is that if you create a link to https://someplace.com, linky will create a linky instance for that.  Then next time you create a link on some other page to someplace.com, linky will recognize that is already knows that link and will use the first one you created.   That way all the instances of the one link can be edited in one spot and fix it everywhere, if for example someplace.com becomes elsewhere.com.
  - You will never have to intentionally choose to use linky or not.
  - Now, if you ever need to change the link, just edit the link like you normally would:  Delete the entire linky path and put the address you want it to be.  Linky will decide automatically whether to create a new one or use an existing match.

We need to create a KB article:
- For editors to explain Linky, why they are seeing it and how to work with it
- For admins who also need to understand Linky and edit the Linky links

## Acceptance Criteria
- [x] Create new article (possibly 2 as there are 2 audiences)
- [x] Review for correctness/functionality with technical team
- [x] Helpdesk team Review
- [ ] Publish article(s)

**Comment by laflannery** [comment]
[Draft Article here](https://docs.google.com/document/d/13ujgIxH9ApQtk5HYU_bZeh-4Fj2GIVhFak1nK70wXx4/edit#)

@swirtSJW and /or @ndouglas Does one of you want to review this article for:

- Functionality/correctness - Is anything I said wrong about how Linky works?
- Anything I might be missing that editors and administrators would need to know?

**Comment by laflannery** [comment]
@stefaniefgray and @TroyA6 could you review [this draft](https://prod.cms.va.gov/help/cms-basics/linky-module) and make sure this has what you (or any new helpdesk member) would want in reference to Linky?  If it looks good go ahead and publish!

**Comment by TroyA6** [comment]
This looks good to me from a technical standpoint.
Thank you!!
Troy

**Comment by laflannery** [comment]
Thanks, published!
