### ISSUE TITLE
[TIMEBOX] Add new things to QA DataDog dashboard

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-cms#11281]
## Description
I'm pushing a lot more metrics and events to DataDog now, so it's time to update the QA Dashboard to reflect these additions.

I figure I can add a bunch of things in not very much time, and it'd duplicate effort to list them explicitly in this issue and then have to find them later, so I'll just call this a timebox issue and try and add as many new things as I can.

## Acceptance Criteria
- [ ] I've spent some time adding new items to the QA dashboard and the widgets are managed in Terraform.

**Comment by BerniXiongA6** [comment]
Let's close this since the work has been completed cc: @maortiz-27-80 @EWashb @ndouglas
