### ISSUE TITLE
Discovery: Outreach Hub from a Support Standpoint

### ISSUE THREAD

**Issue by stefaniefgray** [department-of-veterans-affairs/va.gov-cms#11292]
**As a Helpdesker, I need an understanding of:**

- What Outreach Hub is, and commonly reported issues/questions

- Who Outreach Hub's support audience is

- How Outreach Hub works (independent of and with other parts of the VA Drupal CMS)

in order to provide optimum support for its users.

----
Ticket originally created by @TroyA6: https://github.com/department-of-veterans-affairs/content-build/issues/1323

**Comment by EWashb** [comment]
Not sure if this is still a needed ticket?

**Comment by stefaniefgray** [comment]
@EWashb Nah I think we're good-to-go on this one

Closing!
