### ISSUE TITLE
Setting up self-hosted GHA runners on CMS and CMS-test to run Ansible

### ISSUE THREAD

**Issue by olivereri** [department-of-veterans-affairs/va.gov-cms#11293]
## Description
[[Spike] Audit CMS Build and Deployment Tasks](https://app.zenhub.com/workspaces/vagov-cms-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/9765) Listed out Build, Deploy and Runtime tasks executed on the CMS servers.  The Build Release Deploy CI/CD platform will be decommissioned over the coming fiscal quarters and with it Jenkins.

Our first steps will be to migrate the Run Time tasks identified but before we do that, we'll need self-hosted runners set up.

## Acceptance Criteria
- [x] GHA self-hosted runner set up on CMS
- [x] GHA self-hosted runner set up on CMS-test
- [x] Everything works through Ansible

### Implementation Details
Github Actions appears to be the best fit to replace Jenkins.

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [x] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by cmaeng** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VAgov-CMS-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/11293?planning-poker) with Zenhub @olivereri @timcosgrove @ElijahLynn

**Comment by olivereri** [comment]
- [ ] Create VA.gov-cms-test GHA self hosted runner
https://vfs.atlassian.net/wiki/spaces/OT/pages/1474595213/Self-Hosted+Runners

**Comment by olivereri** [comment]
- [ ] Create separate private repository for CMS configuration code
  - [ ] Docker Image creation and ECR commit GHA Workflows
  - [ ] Ansible configuration code
- [ ] Create GHA Workflows in CMS and CMS-Test repos
  - [ ] Use private ECR Images with customized toolingt to run Ansible plays

**Comment by cmaeng** [comment]
worth exploring what GH support might suggest to remediate the issues we're seeing.
