### ISSUE TITLE
Deploy php 8.1 to prod

### ISSUE THREAD

**Issue by cmaeng** [department-of-veterans-affairs/va.gov-cms#11295]
## Description
Roll out of tested changes onto prod so that we are up to date with security updates and performance is maximized.

## Acceptance Criteria
- [x] php 8.1 is deployed to prod.cms.va.gov
- [x] php 8.1 is deployed to Tugboat base images
- [x] rebuild any needed Tugboat environments
- [x] php 8.1 is communicated to developers in our program to restart ddev

**Comment by cmaeng** [comment]
with the holiday week being 11/21-25, we're proposing to install this on prod the week of 11/28.

**Comment by cmaeng** [comment]
will want to coordinate with where @edmund-dunn is at with testing and confidence

**Comment by timcosgrove** [comment]
This will roll over to the next sprint. Testing work is active. We are aiming for Wednesday December 7 as the roll out day.

**Comment by TheBoatyMcBoatFace** [comment]
Removed Sprint 72 and Added Sprint 73 Label - More time needed - Memcache and network investigations. 

ETA deploy Dec 7, 2022

**Comment by ElijahLynn** [comment]
I'll be merging https://github.com/department-of-veterans-affairs/va.gov-cms/pull/11833 and https://github.com/department-of-veterans-affairs/devops/pull/12251 and then monitoring the deploy to STAGING for tests to pass, to enable the deploy to PROD at 12:30pm PT today.

**Comment by ElijahLynn** [comment]
Rollback plan: 
* Replay last production deploy here http://jenkins.vfs.va.gov/job/deploys/job/cms-vagov-prod/744/replay (009af72ea553fcef58a635fe599d04df97eea36c)
* There don't appear to be any DB Schema changes or updates that would make rolling back to a prior DB snapshot required (screenshot)

![image](https://user-images.githubusercontent.com/1504756/206546603-2d10f9d1-8741-4d92-9965-e1a73d1d5156.png)

**Comment by ElijahLynn** [comment]
We are deployed to PROD!!! We are running manual smoke tests now. 
![image](https://user-images.githubusercontent.com/1504756/206564461-7aa0bcf5-3591-4cc9-96b5-0124ffc80fe0.png)

**Comment by ElijahLynn** [comment]
I just triggered Tugboat base preview rebuilds for Demo, PRs, and PROD Mirrors.

**Comment by ElijahLynn** [comment]
All Tugboat bases are rebuilt now. There was an issue with the VA-Chatbot environment and it was offline until about 2:18pm PT.
