### ISSUE TITLE
SPIKE: Investigate Prod Monitoring/Synthetic Testing

### ISSUE THREAD

**Issue by ryguyk** [department-of-veterans-affairs/va.gov-cms#11291]
## Description
This is a spike preceeding #11255 

## Acceptance Criteria
- [ ] Provide an estimate for #11255 
OR
- [ ] Determine #11255 is not feasible 

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by wesrowe** [comment]
not needed
