### ISSUE TITLE
Create runbook/checklist for VBA editors to complete pages for MVP

### ISSUE THREAD

**Issue by dsinla** [department-of-veterans-affairs/va.gov-cms#11304]
## Description
We need the checklist for VBA editors, including instructions/explanations for how to:

- Add services to their facility 
- Publish pages 
- Create banner on page “This is our beta” with link to official site
- Create Stories/events/PR
- Testing suggestions - here’s what you should exercise 

## Acceptance Criteria
- [ ] 1 pager checklist has been created for Editors
- [ ] Checklist has been shared in an Editor training session, and to VBA National leadership

**Comment by davidmpickett** [comment]
@mmiddaugh @laflannery - What are your thoughts on this ticket? Does the training documentation y'all have created cover these topics? Is there a easy consolidated place to find those materials?

I don't think this should be considered blocking for staging review, so it could likely roll into the National Rollout epic

cc @jilladams

**Comment by laflannery** [comment]
@mmiddaugh I put this on our agenda to discuss next week during our training sync. We can figure out if there's any specific action we want to do for this

**Comment by laflannery** [comment]
We will create a 1-pager checklist for editors

**Comment by jilladams** [comment]
Updated ACs. @laflannery could you estimate, based on what you know right now? Keeping this in Pilot epic, and removing from National, since we'll want that 1-pager handy to onboard the next batch of editors.

**Comment by laflannery** [comment]
I have it somewhat done. I'm trying to get it done by tomorrow to I can share with Michelle with a goal of maybe sharing it Tuesday in our training. If we can't we can't but I'm going to try

**Comment by laflannery** [comment]
[Draft](https://dvagov.sharepoint.com/:w:/r/sites/SitewideFacilitiesTeam/_layouts/15/Doc.aspx?sourcedoc=%7B46E719B2-6B35-4A78-B03E-642A63C8E67A%7D&file=VBA%20Regional%20Office%20Editor%20Checklist.docx&action=default&mobileredirect=true&DefaultItemOpen=1&login_hint=Laura.Flannery%40va.gov&ct=1712952576686&wdOrigin=OFFICECOM-WEB.START.EDGEWORTH&cid=ff360d09-11e7-409f-8d37-91ccab42e878&wdPreviousSessionSrc=HarmonyWeb&wdPreviousSession=bcf2e262-1df0-49b5-96e1-89b4a7564d93) sent to Michelle for review. It's in the Facilities Sharepoint

**Comment by davidmpickett** [comment]
@laflannery Can you confirm here if this is still pending review from Michelle or if it we can close ticket?
