### ISSUE TITLE
Update AWS instance type for Content release

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#11309]
## Description
Currently we use `m5.4xlarge` instances to run Content release. We may get better performance out of a different instance type. Three candidates found after some exploratory testing:

* `c5.4xlarge`
* `c5d.4xlarge`
* `m6i.4xlarge`

## Acceptance Criteria
- [x] The Content release instance type is updated, starting with the first instance in the above list
- [x] Data is captured for 3 buisness days
- [x] Move through each instance type
- [x] Comparisons between the 4 instance types' performance is collected
  - (https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11309#issuecomment-1332871291) 
- [x] The best-performing instance type is used
  - Per findings, we will use m6i.4xlarge as our default instance type.

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [x] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by cmaeng** [comment]
need at least a few days of data to make any determinations

**Comment by cmaeng** [comment]
something to keep in mind: clock speed may be different for each

**Comment by cmaeng** [comment]
testing of one instance type was accomplished in sprint 71. we'll need another sprint to test the other two.

**Comment by timcosgrove** [comment]
I laid out this Datadog Notebook looking at the differences between C5 and M5 instances for our use case: https://vagov.ddog-gov.com/notebook/975/content-build-c5-instances-vs-m5
[PDF version](https://github.com/department-of-veterans-affairs/va.gov-cms/files/10026084/c5_vs_m5.analysis.pdf)

Findings summary:
* moving to C5 saves approximately 100 seconds in the build phase
* moving to C5 currently is adding a little more than 100 seconds to the archive phase
* Content Release total time is slightly worse on C5
More investigation coming.

**Comment by timcosgrove** [comment]
This one is going to roll over; the timeframes we're working with require testing periods of 3-5 business days to gather sufficient information on timing. Will finish by end of next sprint and a final decision made.

**Comment by timcosgrove** [comment]
Notebook created to show findings: https://vagov.ddog-gov.com/notebook/1019/content-release-runner-instance-data?view=view-mode

[PDF version](https://github.com/department-of-veterans-affairs/va.gov-cms/files/10128036/content_release_instance_comparison.pdf)

The most salient finding is, we will move to m6i instances for the time being.
