### ISSUE TITLE
Bulk save script may have introduced some trailing spaces

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#11308]
## Describe the defect
We had report of 1 broken link that ended up with a space (%20) at the end of the url which resulted in a broken link.
https://dsva.slack.com/archives/CDHBKAL9W/p1666356409419839
source node https://prod.cms.va.gov/health-care/health-needs-conditions/military-sexual-trauma
The break was surfaced by the node link report 
![image](https://user-images.githubusercontent.com/5752113/197215800-761f9fbc-ab0c-4d36-818b-2e116a01be22.png)
However it was undetectable in the [linky element itself](https://prod.cms.va.gov/admin/content/linky/748/), but resaving the linky item in the UI  resolved the issue.

There may be more that either do not resolve to a 404 (because the server handled the trailing space) or they just have not been detected yet.

We should consider a bulk save of all linkies where we trim the destination

## AC / Expected behavior
- [ ] no destination uri in linky contains a trailing space

## Additional context
Add any other context about the problem here. Reach out to the Product Managers to determine if it should be escalated as critical (prevents users from accomplishing their work with no known workaround and needs to be addressed within 2 business days).

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Defect")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS workstream (orange) (not needed for bug tickets)
- [ ] CMS-supported product (black)

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by laflannery** [comment]
Nate did a query and confirmed there are none in the db, closing!
