### ISSUE TITLE
KB article explaining what Linky does

### ISSUE THREAD

**Issue by cmaeng** [department-of-veterans-affairs/va.gov-cms#11307]
## Description
Some editors are getting confused when they see Linky links and are renaming them which causes broken link nightmares. A KB article to explain what LInky is used for and what editors can expect to see would hopefully help to mitigate these types of situations.

[Slack thread](https://dsva.slack.com/archives/C030F5WV2TF/p1666301339585009) in reference to >200 broken links created by an editor who manually changed linky links.

## Acceptance Criteria
- [ ] A KB article is published that explains what Linky does and what editors can expect.
- [ ] Any users that have previously updated LInky links manually have been sent the KB article.

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [x] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by swirtSJW** [comment]
Duplicates https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11263
