### ISSUE TITLE
CMS: Support VBA MVP sites when Teamsite pages are retired

### ISSUE THREAD

**Issue by dsinla** [department-of-veterans-affairs/va.gov-cms#11305]
## Description
When we're given the notice that dual-state is ending, and the VBA team is retiring the Teamsite pages, 

## Acceptance Criteria
- [ ] Confirm Teamsite owner has created redirect
- [ ] Remove "This is a beta page" banner 
- [ ] Requires design review

**Comment by jilladams** [comment]
@mmiddaugh @xiongjaneg this old ticket presumes that we are launching in a dual state kind of way with a "this is a beta page" banner on the FE. I don't recall seeing that in designs so far, 
 (@thejordanwood correct me if I'm wrong.)

I think that means we need to either: 
1. Close this ticket as a no-op, if this is not how we'll launch. --OR--
2. Create the treatment for the "this is a beta page" banner in the designs and add a FE implementation ticket, --OR--
3. That treatment is standard bc we did it for Lovell maybe? And we _only_ need it queued in a FE ticket. 

I'm not sure which of those is right.

**Comment by davidmpickett** [comment]
@jilladams We are implementing banners on VBA in #14700 - the wording can be reused from Lovell. Doesn't need any special design. We could create a ticket to track setting up the banners for dual state. It's a small Site Building task.

Could also do this using a single Full Width Alert and just update the URLs it applies to (assuming no namespacing) if we wanna reserve VBA banners for emergencies

**Comment by jilladams** [comment]
Ahh, lovely. Thank you!

**Comment by jilladams** [comment]
Since this is legit, and re: dual state ending, moving it to National roll out, at min. May more likely be a fast-follow from National launch.

**Comment by mmiddaugh** [comment]
closing this as no longer needed - we are sunsetting legacy Teamsites as modernized pages are published
