### ISSUE TITLE
PHP 8.1 Tugboat - composer install - generating autoload - "Fatal error: Invalid opcode"

### ISSUE THREAD

**Issue by ElijahLynn** [department-of-veterans-affairs/va.gov-cms#11315]
See https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11191#issuecomment-1287025577_ for more context. 

```
composer install
...
Generating optimized autoload files

Fatal error: Invalid opcode 137/1/0. in phar:///usr/local/bin/composer/vendor/composer/class-map-generator/src/PhpFileCleaner.php on line 168
2022-10-20T19:50:28.070Z - Command Failed (Tugboat Error 1064): Exit code (255)
````

_Originally posted by @ElijahLynn in https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11191#issuecomment-1287025577_

**Comment by ndouglas** [comment]
Just rebuilt [this preview](https://tugboat.vfs.va.gov/635187ecda954ce95ff50431) to take a look.

The error message would lead me to think that the opcode cache is still hanging around from 7.4, and the virtual machine's different in 8.1 so it's trying to execute existing compiled scripts that reference the old instruction set and they're 💩 🩸 .  Think `drush eval 'opcache_reset();'`.  That's easy enough to add to the Tubgoat/BRD deployment stuff.

**Comment by ndouglas** [comment]
The [referenced source code](https://github.com/composer/class-map-generator/blob/main/src/PhpFileCleaner.php) seems innocuous, which does nothing to disconfirm my suspicion from earlier.  Think it's probably just getting compiled to different bytecode.  Surprised that the opcode cache wouldn't be getting flushed somewhere previous along the line, though.

**Comment by ndouglas** [comment]
```
🔔nathan.douglas@Belmore:~/Projects/va.gov-cms
$ tugboat shell 635187ecda954ce95ff50431
root@php:/var/lib/tugboat# composer va:theme:compile

Fatal error: Invalid opcode 137/1/0. in phar:///usr/local/bin/composer/vendor/composer/class-map-generator/src/PhpFileCleaner.php on line 168
root@php:/var/lib/tugboat# drush eval 'opcache_reset();'
root@php:/var/lib/tugboat# composer va:theme:compile
> cd bin && ln -sf ../docroot/libraries/yarn/bin/yarn yarn
> export NODE_EXTRA_CA_CERTS=/etc/pki/tls/certs/ca-bundle.crt PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=TRUE; cd docroot/core && yarn install
Warning: Ignoring extra certs from `/etc/pki/tls/certs/ca-bundle.crt`, load failed: error:02001002:system library:fopen:No such file or directory
```

**Comment by ndouglas** [comment]
Weirdly, opcode 137 itself seems to relate to the opcode cache itself, but it seems to be undocumented and possibly closed source, as part of the Zend VM parts 🤔   This is really getting out of my depth, but I found a few possibly related issues:

- Opcode 137/1/8 https://bugs.php.net/bug.php?id=30266
- Opcode 137/1/4 https://bugs.php.net/bug.php?id=35437
- Opcode 137/4/8 https://stackoverflow.com/questions/46065940/what-is-php-fatal-error-invalid-opcode-137-4-8

It was added to the main PHP source [here](https://github.com/php/php-src/commit/b1bd6f502faa546d575eb24adcd2c4ca69628614)... kinda struggling to find more information on it, not sure if poor ghoogle-fu or what.

Digging more:

https://www.npopov.com/2017/04/14/PHP-7-Virtual-machine.html

>As such, opcodes are essentially a “three-address code” instruction format. There is an opcode determining the instruction type, there are two input operands op1 and op2 and one output operand result.

>Not all instructions use all operands. An ADD instruction (representing the + operator) will use all three. A BOOL_NOT instruction (representing the ! operator) uses only op1 and result. An ECHO instruction uses only op1. Some instructions may either use or not use an operand. For example DO_FCALL may or may not have a result operand, depending on whether the return value of the function call is used. Some instructions require more than two input operands, in which case they will simply use a second dummy instruction (OP_DATA) to carry additional operands.

That `OP_DATA` is likely the `ZEND_OP_DATA` constant from above, so it looks like the instruction is being used to pass additional data for the previous opcode.  That explains, I guess, why I wasn't finding much documentation about the opcode itself.

**Comment by ndouglas** [comment]
Still looking into this, and it's... getting weirder.  I'm not getting deterministic results 🤔

**Comment by ndouglas** [comment]
```
React\Promise\CancellationQueue::drain:
     ; (lines=28, args=0, vars=3, tmps=13)
     ; (before optimizer)
     ; phar:///usr/local/bin/composer/vendor/react/promise/src/CancellationQueue.php:33-54
     ; return  [] RANGE[0..0]
0000 INIT_NS_FCALL_BY_NAME 1 string("React\Promise\key")
0001 CHECK_FUNC_ARG 1
0002 V3 = FETCH_OBJ_FUNC_ARG (ref) THIS string("queue")
0003 SEND_FUNC_ARG V3 1
0004 V4 = DO_FCALL
0005 ASSIGN CV0($i) V4
0006 JMP 0022
0007 T6 = FETCH_OBJ_R THIS string("queue")
0008 T7 = FETCH_DIM_R T6 CV0($i)
0009 ASSIGN CV1($cancellable) T7
0010 ASSIGN CV2($exception) null
0011 INIT_METHOD_CALL 0 CV1($cancellable) string("cancel")
0012 DO_FCALL
0013 JMP 0017
0014 CV2($exception) = CATCH string("Throwable") 0016
0015 JMP 0017
0016 CV2($exception) = CATCH string("Exception")
0017 V11 = FETCH_OBJ_UNSET THIS string("queue")
0018 UNSET_DIM V11 CV0($i)
0019 JMPZ CV2($exception) 0021
0020 THROW CV2($exception)
0021 PRE_INC CV0($i)
0022 T13 = FETCH_OBJ_IS THIS string("queue")
0023 T14 = ISSET_ISEMPTY_DIM_OBJ (isset) T13 CV0($i)
0024 JMPNZ T14 0007
0025 ASSIGN_OBJ THIS string("queue")
0026 OP_DATA array(...)
0027 RETURN null
EXCEPTION TABLE:
     0011, 0014, -, -
```

Possibly where the error is occurring.

**Comment by ndouglas** [comment]
f I record multiple runs and diff their output, the diffs do not appear to include `skipString`.  

So for runs that pass and runs that fail, the code is compiled to the same bytecode.  This would indicate to me that either 1) the generated opcodes are fine all of the time, and this is a bug in PHP, or that 2) different codepaths are exercised, so the problematic opcode/combination isn't executed.

I'm gonna step away from this a bit and tackle another issue and think about this in the background.

**Comment by ndouglas** [comment]
```
root@php:/var/lib/tugboat# drush eval 'opcache_reset();'

In CheckExceptionOnInvalidReferenceBehaviorPass.php line 86:
                                                                                     
  The service "renderer" has a dependency on a non-existent service "theme.manger".  
                                                                                     
```

what in sam hill

**Comment by ndouglas** [comment]
Running `drush eval 'opcache_reset();'` and then looping `composer install` still fails, which makes sense.  There shouldn't be cached entries in the opcache because no other version of PHP has executed or has even been installed.  `composer install` succeeded yesterday on the first run after I reset the opcache, so it was a false positive.

Weird thing is:

> If I change `"optimize-autoloader": true,` to `"optimize-autoloader": false,` in composer.json, then `composer install` works fine without nukes etc. So I think one of the files being included for autoloading is barfing on everything. How to determine what file that is?...

![Screen Shot 2022-10-26 at 10 18 56 AM](https://user-images.githubusercontent.com/1318579/198051200-6756af6e-2be8-458a-bad1-f8a5f92b7889.png)

But it's not.  This makes me wonder if @ElijahLynn encountered a false positive too trying to diagnose this.

**Comment by ndouglas** [comment]
I started removing chunks from the `composer.json` file and running `composer install`.  It continued to error with about the same frequency, even after I'd removed almost everything in the file (all packages, scripts, extra, etc).

So I changed to a separate directory and did:

```
composer create-project drupal/recommended-project my_site_name_dir
```

(copied and pasted from https://www.drupal.org/docs/develop/using-composer/manage-dependencies)

After that completed, I changed into the directory and ran `composer install` a few times.

I received:
```

root@php:/var/lib/tugboat/test/my_site_name_dir# composer install
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Nothing to install, update or remove
Package doctrine/reflection is abandoned, you should avoid using it. Use roave/better-reflection instead.
Package symfony/debug is abandoned, you should avoid using it. Use symfony/error-handler instead.
Generating autoload files

Fatal error: Invalid opcode 137/1/0. in phar:///usr/local/bin/composer/vendor/composer/class-map-generator/src/PhpFileCleaner.php on line 168
```

So this does not seem to be specific to our project, but something in the environment/PHP area.

**Comment by ndouglas** [comment]
I ran `composer nuke && composer install` a bunch of times, and found that I get the "Invalid opcode" error a nontrivial amount of the time even in that situation (both during the `composer nuke` and `composer install` operations).  So that would seem to confirm that it's not within the Composer project itself, nor within our codebase, but something at the Composer PHAR or PHP levels or in the interplay between the two.

**Comment by ndouglas** [comment]
test.prod is working, but test.prod does not appear to have the opcache enabled:

```
---
> Opcode Caching => Up and Running
> Optimization => Enabled
> SHM Cache => Enabled
> File Cache => Disabled
> JIT => On
> Startup => OK
> Shared memory model => mmap
> Cache hits => 0
> Cache misses => 0
> Used memory => 9257968
> Free memory => 124959760
> Wasted memory => 0
> Interned Strings Used memory => 304360
> Interned Strings Free memory => 5986632
> Cached scripts => 0
> Cached keys => 0
> Max keys => 16229
> OOM restarts => 0
> Hash keys restarts => 0
> Manual restarts => 0
> 
> Directive => Local Value => Master Value
> opcache.blacklist_filename => no value => no value
> opcache.consistency_checks => 0 => 0
> opcache.dups_fix => Off => Off
> opcache.enable => On => On
> opcache.enable_cli => On => On
> opcache.enable_file_override => Off => Off
> opcache.error_log => no value => no value
> opcache.file_cache => no value => no value
> opcache.file_cache_consistency_checks => On => On
> opcache.file_cache_only => Off => Off
> opcache.file_update_protection => 2 => 2
> opcache.force_restart_timeout => 180 => 180
> opcache.huge_code_pages => Off => Off
> opcache.interned_strings_buffer => 8 => 8
> opcache.jit => 1255 => 1255
> opcache.jit_bisect_limit => 0 => 0
> opcache.jit_blacklist_root_trace => 16 => 16
> opcache.jit_blacklist_side_trace => 8 => 8
> opcache.jit_buffer_size => 256M => 256M
> opcache.jit_debug => 0 => 0
> opcache.jit_hot_func => 127 => 127
> opcache.jit_hot_loop => 64 => 64
> opcache.jit_hot_return => 8 => 8
> opcache.jit_hot_side_exit => 8 => 8
> opcache.jit_max_exit_counters => 8192 => 8192
> opcache.jit_max_loop_unrolls => 8 => 8
> opcache.jit_max_polymorphic_calls => 2 => 2
> opcache.jit_max_recursive_calls => 2 => 2
> opcache.jit_max_recursive_returns => 2 => 2
> opcache.jit_max_root_traces => 1024 => 1024
> opcache.jit_max_side_traces => 128 => 128
> opcache.jit_prof_threshold => 0.005 => 0.005
> opcache.lockfile_path => /tmp => /tmp
> opcache.log_verbosity_level => 1 => 1
> opcache.max_accelerated_files => 10000 => 10000
> opcache.max_file_size => 0 => 0
> opcache.max_wasted_percentage => 5 => 5
> opcache.memory_consumption => 128 => 128
> opcache.opt_debug_level => 0 => 0
> opcache.optimization_level => 0x7FFEBFFF => 0x7FFEBFFF
> opcache.preferred_memory_model => no value => no value
> opcache.preload => no value => no value
> opcache.preload_user => no value => no value
> opcache.protect_memory => Off => Off
> opcache.record_warnings => Off => Off
> opcache.restrict_api => no value => no value
> opcache.revalidate_freq => 2 => 2
> opcache.revalidate_path => Off => Off
> opcache.save_comments => On => On
> opcache.use_cwd => On => On
> opcache.validate_permission => Off => Off
> opcache.validate_root => Off => Off
> opcache.validate_timestamps => On => On
```

I'm looking through the (many) other differences between test.prod and Tugboat configuration, but I figure given the subject that this is a reasonable place to start.

**Comment by ndouglas** [comment]
Disabling opcache via `opcache.enable_cli` works around the issue.

```bash
root@php:/var/lib/tugboat# nano -w /usr/local/etc/php/conf.d/php-cli.ini # disable CLI opcache
root@php:/var/lib/tugboat# for i in $(seq 1 20); do composer install > /dev/null 2>&1 && echo "PASS" || echo "FAIL"; sleep 1; done;
PASS
PASS
PASS
PASS
PASS
PASS
PASS
PASS
PASS
PASS
PASS
PASS
PASS
PASS
PASS
PASS
PASS
PASS
PASS
PASS
root@php:/var/lib/tugboat# nano -w /usr/local/etc/php/conf.d/php-cli.ini #enable CLI opcache
root@php:/var/lib/tugboat# for i in $(seq 1 20); do composer install > /dev/null 2>&1 && echo "PASS" || echo "FAIL"; sleep 1; done;
FAIL
FAIL
FAIL
FAIL
FAIL
FAIL
PASS
PASS
FAIL
PASS
PASS
PASS
PASS
FAIL
PASS
PASS
PASS
FAIL
PASS
FAIL
```

**Comment by ndouglas** [comment]
It appears to be related to JIT.  

- setting `opcache.jit` to 0 (was 1255) but keeping `opcache.enable_cli` set to 1 prevents failure.  
- retaining `opcache.jit` but setting `opcache.jit_buffer_size` to 0M (was 256M) prevents failure.
- retaining `opcache.jit` and `opcache.jit_buffer_size` but setting `opcache.jit_hot_loop` to 0 prevents failure.
- retaining `opcache.jit`, `opcache.jit_buffer_size`, and `opcache.jit_hot_loop`, but decreasing `opcache.jit_max_exit_counters` seems to decrease the frequency of failures.  However, it still fails at least occasionally, and will throw a segmentation fault occasionally as well.
- retaining all of the above settings, but setting `opcache.jit_max_root_traces` to 0 seems to prevent failures.

Modifying other settings, whether inside or outside of JIT, seem to have no effect.

**Comment by ndouglas** [comment]
Altering `opcode.jit` to `0205` _greatly_ reduces (to ~5%) the frequency of failures (in 40 executions of `composer install`), similar with `1205`.  Changing it to `function` almost eliminated them (2 of 100 trials).  Per [this comment](https://github.com/php/php-src/issues/7817#issuecomment-1084721699) and the apparent difficulty of completely eliminating these random failures, IMHO I think it just makes sense to disable `opcode.jit` completely.

**Comment by ndouglas** [comment]
As described in my comments on department-of-veterans-affairs/devops#12057, I see the same behavior on test.prod now that Opcache is enabled.

**Comment by audaki** [comment]
We got really burned by JIT failures on a production ecommerce shop and lost income. It seems like the JIT should be marked not production ready (no offense intended!) until all of this is ironed out.

**Comment by ElijahLynn** [comment]
This article suggests that disabling JIT also seems safe for other sites too. 

https://stitcher.io/blog/jit-in-real-life-web-applications

> As you can see: a case of the JIT performing worse. Like I said at the beginning of this post: I want to measure the relative impact the JIT has on real-life web projects. It's clear from these tests that sometimes there might be benefits, but it's in no way as noticeable as the fractal example we started out with. I admit I'm not really surprised by that. Like I wrote before: there's very little hot code to be optimised in real-life applications, we're only rarely doing fractal-like computations.
> 
> So am I saying there's no need for the JIT? Not quite, I think the JIT can open up new areas for PHP: areas where complex computations do benefit from JIT'ed code. I'm thinking about machine learning, AI, stuff like that. The JIT might give opportunities to the PHP community that didn't exist yet, but it's unclear to say anything with certainty at this point.
> 
> So, that concludes my JIT testing. As expected: the JIT probably won't have a significant impact on web applications, at least not right now.

And coincidentally, it is the same site that I used to setup JIT in the first place. 

https://stitcher.io/blog/php-8-jit-setup

**Comment by ElijahLynn** [comment]
Here is the admin/content/ view on test.prod.cms.va.gov and prod.cms.va.gov respectively. 

No noticeable differences with 8.1 w/jit disabled vs 7.4.

![image](https://user-images.githubusercontent.com/1504756/199537775-121d4490-f74f-40a8-b203-7a7d56727c3a.png)

**Comment by ElijahLynn** [comment]
#11417 is merged and I also put the same settings in devops code to deploy to test.prod.cms.va.gov as well, https://github.com/department-of-veterans-affairs/devops/pull/12057. This will be merged shortly too.
