### ISSUE TITLE
Add VA web components to injected header

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#11313]
### User story

**AS A** PO/PM
**I WANT** to ensure all web components are available to the injected header
**SO THAT** the injected header can't be broken by the accidental addition of a web component that's not properly imported.

### Engineering notes / background
Branch "draft": `injected-header-web-components` ([diff](https://github.com/department-of-veterans-affairs/vets-website/compare/main...injected-header-web-components)).

### Quality / testing notes
Daniel has extensive [functional testing notes in comments on Discovery ticket 11260](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11260#issuecomment-1544572868). 

Basic verification needed: 
* prove that `va-modal` works and doesn't break in the header of a TeamSite.
* Implement and use a flipper to turn on/off `va-modal` with visibility set to none in the header

## Acceptance criteria

- [ ] Injected header code has all VA web components available to it
- [ ] A flipper exists to control testing in prod, `injected_header_web_components`
- [ ] After merge/ deploy, and after timeframe for changes to propagate to TeamSites, flipper is used to verify in prod on a TeamSite with injected header, e.g. https://va.gov/health
- [ ] Performance benchmarking has been done and documented in this ticket's comments on prod TeamSite with injected header

**Comment by jtmst** [comment]
Issues with getting flipper logic to work in the proxy-redirect app are slowing this ticket down.  Its crucial that we have flippers in order to test this in prod, but the current config forces a 5 second render delay before it can appropriately load in the feature toggles.  More work needs done to ensure this is safe to merge

**Comment by jilladams** [comment]
@jtmst when you get a chance, could you update recent status? I know last week you mentioned in scrum, but I've lost mental track.

**Comment by jtmst** [comment]
I'm fairly confident that we won't be able to feature flag the functionality here, only the test data.  I'll need to make sure the team is confident in the proposed fix before merging and likely prep a revert PR just in case before merging. Will bring to up with team tomorrow

**Comment by jilladams** [comment]
Note from planning: let's vet our current state of affairs with Platform front-end for any potential insights.

**Comment by jilladams** [comment]
Launch plan: 

1. Prep a revert PR, just in case
2. Merge the original PR with tomorrow's daily deploy, to ship the web component package itself to injected header sites
3. Watch launch & propagation to injected sites - will tell us if the package itself causes any issue
4. If that causes problems: roll back with the revert PR
5. Then: enable a test feature flag to enable an invisible test VA modal component that will appear in the DOM, to confirm it all works.

**Comment by jilladams** [comment]
Merged/deployed today, headers no longer show on TeamSites, rolling back. 
Platform thread for OOB deploy: https://dsva.slack.com/archives/CBU0KDSB1/p1688067509766669
Postmortem will be forthcoming.

**Comment by humancompanion-usds** [comment]
@jilladams and @jtmst - The Design System Team and I might be able to help with Cypress tests for the injected header. Brooks had a way of doing this. Let me know if that is of use here.

**Comment by jilladams** [comment]
Thanks @humancompanion-usds ! You'll be tagged in on the [postmortem](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/pull/1049), and would appreciate any suggestions re: additional action items, etc. in this direction.

**Comment by jilladams** [comment]
Per post-mortem: we do not have a means of testing pre-prod. We need to regroup re: roll forward plan. Given FE staffing, with Josh moving to AP now / Chris joining, we are opting to move this out of sprint until a more fully staffed point to revisit that plan.

**Comment by jilladams** [comment]
From planning: DaveC proposal to verify with DS for buy-in: We will not try to add web components to injected header prior to the federal header. Notes in the federal header epic re: how we may be able to manage this moving forward.

**Comment by jilladams** [comment]
Anecdotally: Matt Dingee mentioned yesterday in context of federal header project that some DS folks have tried a couple times to get web components working for injected header and have hit walls each time. Right now the trending thought is that we try to deliver a flattened header for injection instead.

**Comment by FranECross** [comment]
Closing this ticket because the decision was made to provide a flattened header for injection.
