### ISSUE TITLE
Reduce logging written for Content build

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#11310]
## Description
Content releases in production print a lot of information to log. We can probably eke out small performance gains by reducing what gets printed, and also have much more manageable logs.

The output information should become available if the `debug` flag is passed to content build. This debug flag should respond to Github Action's 'run with debug' flag as well; it does not currently.

For the purposes of this ticket, 'non-essential logs' are defined as status information that does not provide significant value run-to-run. Examples of this are

* File download information
* reporting on individual GraphQL queries performing within bounds

A general performance report for build should be available with each run.

## Acceptance Criteria
- [x] Non-essential logs are not printed on production unless the --debug flag is set
- [x] If the 'run with debugging' flag is set in Github Actions, the --debug flag is set 
- [ ] After a week of being in place, timing data before and after the change is compared

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [x] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by cmaeng** [comment]
can't do at the same time as #11309 otherwise data will be messy

**Comment by TheBoatyMcBoatFace** [comment]
Removed Sprint 72 and Added Sprint 73 Label

Too many variables in play during Sprint 72 - Will address when other aspects of Content Build are resolved/not testing
