### ISSUE TITLE
Implement GA analytics for baselining current homepage

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#11324]
## Description

As a stakeholder, I want to capture specific historical data about user behavior for comparison after the new home page launches.

## Problems to solve
| Task | Pathway to completion | Current GA event | Problem
| ---|---|---|---
| Check your claim or appeal status  | Mega menu > Disability > Check your claim or appeal status link >  Check your VA claim or appeal status page |  Navigation - Header - Check your claim or appeal status - https://www.va.gov/claim-or-appeal-status | Easily confused with similar links for life insurance and housing
Check your claim or appeal status | Mega menu > Life insurance > Check your appeal status link >  Check your VA claim or appeal status page |  Navigation - Header - Check your appeal status - https://www.va.gov/claim-or-appeal-status | Indistinguishable from housing link and very similar to disability
Check your claim or appeal status |  Mega menu > Housing  > Check your appeal status link >  Check your VA claim or appeal status page |  Navigation - Header - Check your appeal status - https://www.va.gov/claim-or-appeal-status | Indistinguishable from life insurance link and very similar to disability
| View your payment history |  Mega menu > Disability > View your payment history link > View your VA payment history page | Navigation - Header - View your VA payment history - https://www.va.gov/va-payment-history | Indistinguishable from links in education and records
View your payment history | Mega menu > Education > View your VA payment history link > View your VA payment history page |  Navigation - Header - View your VA payment history - https://www.va.gov/va-payment-history | Indistinguishable from links in disability and records
View your payment history |  Mega menu > Records > View your VA payment history link  > View your VA payment history page |  Navigation - Header - View your VA payment history - https://www.va.gov/va-payment-history | Indistinguishable from links in education and disability
Compare GI Bill benefits by school |  Mega menu > Education > GI Bill comparison tool (box) <image src = "https://user-images.githubusercontent.com/55411834/197892499-bc1f6e10-6e45-4dbb-a570-229d67e74db8.PNG" ></image> | no identifiable event | no apparent tracking of this task
Download your benefit letters  | Mega menu > Records > Confirm your VA benefit status (box) <image src ="https://user-images.githubusercontent.com/55411834/197892900-a9268572-1a80-4919-81f7-8083b897f4de.PNG"></image> | no identifiable event | no apparent tracking of this task
Request your military records (DD214) | Mega menu > Records > Request your military records (DD214) | Navigation - Header - Request military records (DD214) - https://www.va.gov/records/get-military-service-records | Indistinguishable from Burials and memorials link
Request your military records (DD214)  | Mega menu > Burials and memorials > Request military records (DD214) |  Navigation - Header - Request military records (DD214) - https://www.va.gov/records/get-military-service-records | Indistinguishable from Records link
Find a facility | CTA below benefit hub <image src = "https://user-images.githubusercontent.com/55411834/197893256-0e001f94-534c-45e0-b40a-5d94f19c5e1c.PNG" ></image>   | no identifiable event | no apparent tracking of this task
Crisis Line | CTA below benefit hub <image src = "https://user-images.githubusercontent.com/55411834/197893319-bdfc0f70-8cfb-449e-9187-4e062b7a7f13.PNG" ></image>| Could be  <ul><li>Navigation - Jumplink Click - Veterans Crisis Line </li><li> Navigation - Jumplink Click - Talk to the Veterans Crisis Line now </li><li> Outbound Link Clicked: https://www.veteranscrisisline.net/get-help-now/chat/ </li><li>  Outbound Link Clicked: https://www.veteranscrisisline.net/ </li></ui> | There are some events which could be tracking events on this CTA but no way to know 
Sign in | Header |  could be <ul><li> Modal - Click - (not set) - (not set) - (not set) - (not set) - Sign in? (biggest event but also more than expected) </li><li> Modal - Click - (not set) - (not set) - (not set) - (not set) - Sign in or create an account to use more tools </li></ui> | No way to differentiate from other CTA
Sign in | CTA below benefit hub <image src = "https://user-images.githubusercontent.com/55411834/197893428-dae62d3a-e225-446f-a429-83080975d4fe.PNG" ></image>|  could be <ul><li> Modal - Click - (not set) - (not set) - (not set) - (not set) - Sign in? (biggest event but also more than expected) </li><li> Modal - Click - (not set) - (not set) - (not set) - (not set) - Sign in or create an account to use more tools </li></ui> | No way to differentiate from other CTA
PACT Act promo | Promo above footer <image src = "https://user-images.githubusercontent.com/55411834/197894299-7a8ab905-4132-46ef-b6e9-bcd7a78781b0.PNG" ></image> | Navigation - Footer - PACT Act | We can work with this but it isn't actually in the footer | 
PACT Act promo | banner alert <image src = "https://user-images.githubusercontent.com/55411834/197900645-629fe9fa-d942-4861-bfdb-f40596871415.PNG" ></image> | Could be Modal - Click - (not set) - (not set) - (not set) - (not set) - Learn what the PACT Act means for your VA benefits
Pathfinder promo  | Promo above footer <image src = "https://user-images.githubusercontent.com/55411834/197900739-f2f1f2b5-f5b2-42d1-a504-c2826ab31694.PNG"></image>| Navigation - Footer - Pathfinder: The front door for engaging with VA | We can work with this but it isn't actually in the footer | 
VA news promo |  Promo above footer <image src = "https://user-images.githubusercontent.com/55411834/197900795-d43e35c3-626c-4ae7-b2cb-e6edd01b9dc9.PNG"></image>| Navigation - Footer - Vantage Point is now VA News | Easily confused with other VA News link
VA news promo |  Promo above footer <image src = "https://user-images.githubusercontent.com/55411834/197900795-d43e35c3-626c-4ae7-b2cb-e6edd01b9dc9.PNG"></image> | Navigation - Footer - VA News | Easily confused with other VA News link and from that in footer <image src = "https://user-images.githubusercontent.com/55411834/197901074-75e2c8e4-8ab0-4530-8cdc-e6c1c15bf920.PNG"></image>

- Naming is up to team, reference precedent on page as needed

## Acceptance Criteria

**Note: Michelle has the analysis and details to answer any questions**

- Analytics team can help us test these once they are available in staging
-  Mega menu events identify the benefit program from which it was clicked 
   - Header - Disability - Check your claim or appeal status 
   - Header - Life insurance - Check your appeal status 
   - Header - Housing - Check your appeal status 
   - Header - Disability - View your payment history
   - Header - Education - View your payment history
   - Header - Records - View your payment history
   - Header - Records - Request your military records
   - Header - Burials and memorials - Request your military records
- Events on boxes at far right of mega menu are tracked and identified distinctly from other mega menu events
     - Header - Education - GI Bill comparison tool 
     - Header - Records - Confirm your VA benefit status
- CTAs below benefit hub are tracked and identifiable as interactions occurring on the CTAs, rather than elsewhere on the page
   - Homepage CTA - Find a location
   - Homepage CTA - Crisis Line
   - Homepage CTA - Sign In
- Sign in events on the header are uniquely identified as occurring in the header
  - Header - Sign in
- Events on OPIA promo spots are tracked and identifiable as interactions occurring on the promo spots, rather than elsewhere on the page
   - Homepage - [title] promo - for any OPIA promo above the footer on current homepage
- Events on PACT Act banner alert are tracked and identified as initiated on alert banner, rather than from a promo block or elsewhere
   - Footer alert - [title] 

### QA Steps
- [ ] Verify in AdSwerve that the events are firing
- [ ] Analytics team said they can assist via making sure the new event tagging/data layer works. Let @mmiddaugh know when changes are in PR and she'll ping Analytics for review, or can review herself

### Risks
* QA is a bit of a question mark here,  will be dependent on Analytics team
* Checking in Staging would require a flipper, which is overkill. So we will ship to prod for review; if anything is wrong, we will lose data for whatever's broken until it can be fixed. (Signed off by Michelle.)

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by jilladams** [comment]
Michelle confirmed that the Analytics team can help us validate: https://dsva.slack.com/archives/C03NSH4SLQY/p1667852540886539

Ideally, we'd be able to verify pre-prod. I'm not certain how to get these changes to Staging without going to Prod, so @apisandipas that may be a conversation to have with Ryan re: whether there's an efficient way he knows of. And if not, Analytics team has definitely dealt with this before I'm sure, and can give us tips.

**Comment by apisandipas** [comment]
@mmiddaugh  I had a question: What should the 'action key' be for the new events to be logged. Not sure if thats clear what I mean, so see below:

The Mega Menu items have an object with and event key and then a 'nav-header-action' key. The Mega Menu Block has an action key of 'nav-hub-action'.  Is there a specific 'action key' desired for the newly logged events, such as the Homepage CTA or Footer CTA Items? One idea would be `homepage-cta-action` or perhaps just a generic `action`.

 I've attempted to illustrate the question better below with the existing examples, the one in question with `???`. But the same would be in question for the other new events to be logged.

| Click Target | Current Object | Proposed Object |
|--|--|--|
| Mega Menu Items | `{ event: 'nav-header-link', 'nav-header-action': "Navigation - Header - Open Link - ${linkName}"}` | `{ event: 'nav-header-link', 'nav-header-action': "Header - ${currentSection} - ${linkName}"}` |
| Mega Menu Marketing Block (3rd column) | `{ event: 'nav-hub-containers', 'nav-hub-action': "${link.text}" }` | `{ event: 'nav-hub-containers', 'nav-hub-action': "Header - ${currentSection} - ${link.text}" }` |
| Homepage CTA | `{ event: 'nav-main-health'}` | `{ event: 'nav-main-health', '???': "Homepage CTA - ..." }` |

**Comment by mmiddaugh** [comment]
@apisandipas - for a given event, I'd like to be able to identify 1) what was clicked and 2) from where (assuming there might be several possible locations). 
I like the specificity of `homepage-cta-action` rather than the generic `action`. 
But unless I'm missing a piece of the bigger picture, I think we'll need at least a partial title or link text to differentiate one homepage CTA from another, such as Homepage CTA - Find a location vs Homepage CTA - Crisis Line. The same situation exists for OPIA promo spots (i.e. PACT Act vs Pathfinder vs VA News).

**Comment by apisandipas** [comment]
@mmiddaugh Understood, I was purposefully non specific in my example. Thanks for your response!

**Comment by jilladams** [comment]
One open question from QA, on the PR: https://github.com/department-of-veterans-affairs/vets-website/pull/22652#issuecomment-1317831053

Otherwise, that comment includes screenshots of successful ACs, using Google Analytics Debugger.
