### ISSUE TITLE
Create "How to Add Outreach Materials" KB Article

### ISSUE THREAD

**Issue by stefaniefgray** [department-of-veterans-affairs/va.gov-cms#11326]
## Background context
**Topic**
As a VA.gov Content Editor who wants to add items to the [Outreach Materials listing](https://www.va.gov/outreach-and-events/outreach-materials/), there is no Knowledge Base article to guide me through the process.

We will need to create a Knowledge Base article that guides Outreach Hub editors through using the "Publication" content type, available at: https://prod.cms.va.gov/node/add/outreach_asset

Publications that have been added to the site are available at: https://www.va.gov/outreach-and-events/outreach-materials/

**Person and team requesting the article:** 
- Stefanie Gray
- VA Drupal CMS Helpdesk team

**Associated SMEs/ stakeholders:** 
- Outreach Hub editors

**Audience:** 
Who is this intended for? Who would need this information? (i.e. Everyone, non-admins, etc.)
- Outreach Hub editors

**Related KB articles:** 
- https://prod.cms.va.gov/help/outreach-hub

Note that the Knowledge Base does not have any Outreach Hub dedicated articles aside from the homepage and how to add an Outreach Hub event
  
**Associated source of truth documentation:** 
- N/A

**This article addresses:**
- [x] A business-driven need
- [x] A user-driven need

**Does this article have a deadline?**
- [ ] Yes: [name the deadline here]
- [x] No

**Is the article associated with change management initiatives?**
- [ ] Yes<br>
  [Change Management Epic](URL)
- [x] No

**What parts of the interface will link to the article, if any?** 
- TBD

## Process
1. Sitewide CMS and Helpdesk teams will review request and confirm no current, applicable KB article/content exists.
2. Refine request and prioritize
3. Assign to appropriate product team
4. Draft article content 
5. Sitewide CMS team will review for formatting and writing style guidelines
6. Helpdesk team will review for functionality and editorial tone
7. Publish

## Acceptance Criteria
- [ ] Article is created using [KB content style guidelines](https://va-gov.atlassian.net/wiki/spaces/VAGOV/pages/1771831299/Knowledge+Base+content+style) 
- [ ] Article is reviewed by Sitewide CMS
- [ ] Article is reviewed by Helpdesk
- [ ] Article posted to KB 
- [ ] Article is assigned to a parent 
- [ ] Impacts on other KB articles have been considered and any necessary changes have been made
- [ ] Once published, the person requesting the article has been notified

**Comment by jilladams** [comment]
Today in Sprint planning, DaveC flagged that Public Websites should own this draft. Tagging / assigning.

**Comment by jilladams** [comment]
@stefaniefgray (cc @TroyA6 , @wesrowe , @EWashb ):  Draft how to create Publication article:  https://prod.cms.va.gov/how-to-create-outreach-materials-publications

**Comment by TroyA6** [comment]
Hi Jill -
Thank you for submitting the article!

I have reviewed it and found it to be complete and accurate.
However, I did find the following:

The link on Step 1 points to two different locations:
[image: image.png]

[image: image.png]

[image: image.png]

Please let me know if you have any questions.
Thank you,

Troy Griffin

VA Drupal CMS Helpdesk Support

**Comment by jilladams** [comment]
Fixed! Ok to publish.

**Comment by jilladams** [comment]
Approved: https://agilesix.slack.com/archives/C01DTUNHFE2/p1668639431097389
And published!
