### ISSUE TITLE
DSN/CMS Propose changes to Section Taxonomy for VBA Facilities

### ISSUE THREAD

**Issue by davidmpickett** [department-of-veterans-affairs/va.gov-cms#11333]
### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by davidmpickett** [comment]
Surfaced as a concern by @omahane https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11197#issuecomment-1289648669

**Comment by davidmpickett** [comment]
**Option A**
- VBA
   - VBA Facilities
      - Continental
      - Pacific
      - Northeast
        - Milwaukee Regional Office
            - VetSuccess in Milwaukee
      - Southeast

**Option B**
- VBA
   - VBA Facilities
      - Continental
      - Pacific
      - Northeast
        - Milwaukee Regional Office
        - VetSuccess in Milwaukee
      - Southeast

**Comment by swirtSJW** [comment]
**Option C**
- VBA
   - VBA Facilities
      - Continental
      - Pacific
      - Northeast
        - Milwaukee Regional Office
        - ~VetSuccess in Milwaukee~
      - Southeast

In the case where we don't need permissions to be granular down to the child facility level.

**Comment by dsinla** [comment]
Option C is chosen

**Comment by omahane** [comment]
@davidmpickett Would you agree that we've finished this?
https://prod.cms.va.gov/admin/structure/taxonomy/manage/administration/overview
![Screen Shot 2022-12-14 at 2 38 18 PM](https://user-images.githubusercontent.com/766573/207709240-b050543a-0d89-48df-b27f-d180d6a09ca2.png)

**Comment by davidmpickett** [comment]
Yes
