### ISSUE TITLE
Proposed plan for Lovell TRICARE & Services Taxonomy

### ISSUE THREAD

**Issue by davidmpickett** [department-of-veterans-affairs/va.gov-cms#11336]
## Description
There are some parts of VAMC services that are managed at a national level. Previous content modeling for Lovell TRICARE accounted for the need to have different information at the Facility and System level, but did not address the national pieces.

![Screenshot 2022-10-24 175830](https://user-images.githubusercontent.com/51967950/197645656-af7a463c-95c5-4df8-adec-c6dd8d0729b6.png)

Here are the potential sources of confusions / incorrect information:
![Screenshot 2022-10-24 180011](https://user-images.githubusercontent.com/51967950/197645748-fc054a02-7f43-4cd8-8ed6-ee0aec0a20e2.png)

Here are a few examples of places where the word veteran or VA is used in those national elements. Because the TRICARE system is for active duty service members / DoD, this is inaccurate.
![Screenshot 2022-10-24 185114](https://user-images.githubusercontent.com/51967950/197651278-c160b730-b845-47af-b467-a7d0774db321.png)

## Proposed Plan
Here is a break down of the 40 potential conflicts I identified [last sprint](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11123).

[VA Services - TRICARE Conflicts.xlsx](https://github.com/department-of-veterans-affairs/va.gov-cms/files/9856126/VA.Services.-.TRICARE.Conflicts.xlsx)

- [ ] CMS - Add new fields to the VAMC field bundle of the Service Taxonomy
   - [ ] A check box that can restrict certain terms to only show up for TRICARE 
   - [ ] TRICARE Name
   - [ ] TRICARE Patient Friendly Name
   - [ ] TRICARE Description
- [ ] CMS - Add logic to VAMC service winnower that restricts terms tagged with TRICARE only checkbox to only show up for editors assigned to the Lovell TRICARE section
- [ ] FE - Add logic for Lovell TRICARE that checks if a TRICARE override exists for each of the three new fields. If not, use the existing VAMC version

- [ ] Additional terms for Dave C / Taxonomy Council to review
   - [ ] The [distinction](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9770) between Primary care, Internal medicine, and Family Practice needs to be addressed. Can TRICARE use the same terms? Would adding Family Practice to the taxonomy create confusion for VAMC editors?
   - [ ] Operational Medicine & Pediatrics are likely additions
   - [ ] Patient Advocates - Would this be inclusive of DoD Case Management? Or should DoD Case Management be a new term?

- [ ] Once updates to Taxonomy are built and the Taxonomy council has made decisions on new terms, those terms are added to the Service Taxonomy

## Acceptance Criteria
- [x] Proposed solution is documented
- [ ] Proposed solution is approved by Dev & PM & PO
- [ ] Subsequent tickets created and added to Lovell Punchlist

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by davidmpickett** [comment]
Follow up to https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11123

**Comment by davidmpickett** [comment]
proposed solution documented for conversation with @swirtSJW @JayDarnell @dsinla tomorrow

**Comment by davidmpickett** [comment]
Just chatted with @davidconlon and got feedback on direction. Will update the plan and create the tickets

**Comment by davidmpickett** [comment]
Shared with the Facilities team for review via [slack](https://dsva.slack.com/archives/C0FQSS30V/p1666910014022029). @swirtSJW has concerns about the technical lift and tech debt for this new proposed plan.

**Comment by dsinla** [comment]
@dsinla and @dawnpruitt met to get our heads around the new proposal. Next proposed step is to meet with @swirtSJW in prep for discussion with Dave C. Questions for that meeting


Swirt questions:
- What is the estimated LOE for CMS and FE tasks proposed
- Who creates tickets and identifies AC

Likely Dave C questions
- Verify - is this being considered or is the trigger already pulled? 
- Better understand the why behind all of this - originally we were not going to spin up a new set of taxonomy for the limited TRICARE only facilities /services - is there broader impact?

**Comment by dsinla** [comment]
First questions: 

Do we want the source of this description coming from the national taxonomy when it's scope is local? Does the service taxonomy council want to be involved with the TRICARE descriptions? Confirm with @davidconlon 

1. TRICARE service description would be offered, but would show up for all service.  Dave C would maintain at the national level
2. Add a field that's specific to Lovell - less than 1/2 of 1 percent -> Larger lift "If I'm TRICARE add the TRICARE description". Still has problem that Dave C would maintain at the national level

**Comment by davidmpickett** [comment]
@JQuaggles @stefaniefgray FYI - here's some documentation around the TRICARE Health Service Taxonomy work
