### ISSUE TITLE
FE: URLs for Events Hosted Online Fail to Display on Published Event Page

### ISSUE THREAD

**Issue by stefaniefgray** [department-of-veterans-affairs/va.gov-cms#11346]
## User Story
As a VA.gov Editor creating an Event hosted online, I would like to include the URL where the event is taking place.

However, when creating a new Event ([link to "Add Event" page](https://prod.cms.va.gov/node/add/event)), if I select "Location type" = "Online" and add a URL, the URL is not shown in the front-end. This is very confusing to users who wish to attend the Event.

Instead of "Where: [LOCATION]" the page shows the default text "**Where:** This is an online event."

Please see attached screenshots for reference.

## To repro: 
**On existing content**
* Visit https://prod.cms.va.gov/node/33511/edit
* See that Location: Online: URL contains a [webex](https://veteransaffairs.webex.com/veteransaffairs/j.php?MTID=mbc82ccf823e2f70d52c7081eb539c860) URL: 

![Screen Shot 2022-10-25 at 2 08 00 PM](https://user-images.githubusercontent.com/85581471/197882295-73d46a0b-d165-43c8-a80a-f8fca6015b5b.png)
* Visit https://www.va.gov/outreach-and-events/events/webex-wednesdays-for-colorado-veterans-3/ and see that the webex URL is not present on the front end

**on new content**
1. Go to the **Add Event** page ( /node/add/event )
4. Add sample information in order to fill the required fields
5. Scroll down to the "Location" section.
6. Select "Location type" = "Online"
7. Add a URL for the Event location.
8. Click Save.
9. Go to the saved version of the page, or view it using the Preview option. You will not see the URL that you added for the Event location. You will only see the default text "**Where:** This is an online event."

### Proposed fix:
from DaveC:  Wrap the `This is an online event` text in the URL provided in the Event Location: Online: URL field.

## Additional detail
Issue submitted via email by Timothy Hudak @ VEO who is in charge of Outreach Hub events

### Current Site Behavior:
**The Event location is NOT displayed on the front-end when:** 
- User selects "Location type" = "Online" and adds a URL. ([prod cms example](https://prod.cms.va.gov/outreach-and-events/events/webex-wednesdays-for-colorado-veterans-3), [live example](https://www.va.gov/outreach-and-events/events/webex-wednesdays-for-colorado-veterans-3)) ❌

**The Event location is displayed properly when:**
- User selects "Location type" = "At a VA Facility" and selects a VAMC ([prod cms example](https://prod.cms.va.gov/fayetteville-arkansas-health-care/events/50529), [live example](https://www.va.gov/fayetteville-arkansas-health-care/events/50529/)) ✅
- User selects "Location type" = "At a non-VA Facility" and specifies a physical address. ([prod cms example](https://prod.cms.va.gov/augusta-health-care/events/50576), [live example](https://www.va.gov/augusta-health-care/events/50576/)) ✅

### Temporary Workaround:
At this time, the only way to display the URL for an online Event is to either: 
* add the link manually within the rich text field for the Event description, or
* add it under the "Registration" section by selecting "Include registration information" and entering the URL, and specifying a "Call to Action."

**Note:** This is not an ideal workaround because:
1. the Registration and Attendance links may be separate links;  
2. the "Registration" section is nested
3. users have no way of knowing that the Call to Action URL is only displayed if the "Include registration information" checkbox is checked

#### Example Events using the "Registration" section workaround in order to share the location URL:
- Event using the "Register" Call to Action field: ([prod link](https://prod.cms.va.gov/node/48085), [live link](https://www.va.gov/outreach-and-events/events/48085/))
- Event using the "More Details" Call to Action field: ([prod link](https://prod.cms.va.gov/outreach-and-events/events/43809/), [live link](https://www.va.gov/outreach-and-events/events/43809/))

It does not matter if the Call to Action URL is the same or different from the Location URL. If both are added, the site will still only display the Call to Action URL. 

**In summary:** At this time, there is no way to get the "Location type" = "Online" URL to display on the front end for Events.

------
## Screenshots
<details>
<summary>As an Editor creating a new Event, I have added the URL for Eventbrite.com as the virtual location:</summary>

![Screen Shot 2022-10-25 at 1 07 45 PM](https://user-images.githubusercontent.com/9059428/197860704-f3ef1630-f148-4cb2-a14e-134796bb9ffc.png)
</details>
<details>
<summary>Here is what the saved page looks like. The URL for the Event is nowhere to be seen:</summary>

![Screen Shot 2022-10-25 at 1 43 59 PM](https://user-images.githubusercontent.com/9059428/197867383-21ad8f06-6265-4a09-9623-658712695c57.png)
</details>
<details>
<summary>The current workaround, nested beneath the "Registration" section, which is hidden by default</summary>

![Screen Shot 2022-10-25 at 1 31 43 PM](https://user-images.githubusercontent.com/9059428/197868286-4b13bfa3-4f2d-49d3-b9ae-53d7ed1dc87e.png)
</details>

# AC / Expected behavior

- [ ] Events with Location: Online and a URL entered should show the "This is an online event" text in the front-end wrapped by the specified URL.
- [ ] Registration link, when present, should continue to be displayed as it does currently

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by jilladams** [comment]
Per Dave: high priority due to upcoming Veterans Day events, so pulling into Sprint 70. Will work with team on Slack to assign. 

Solution proposed: Wrap "This is an online event" Where text in the provided URL, if one exists. Makes this a front-end bug, re-editing ticket title, and will update ticket body.
