### ISSUE TITLE
PM: Create roadmap for what's required to get editors creating and publishing Lovell content 

### ISSUE THREAD

**Issue by dsinla** [department-of-veterans-affairs/va.gov-cms#11357]
## Description
List what needs to be done to get editors authoring and publishing 
Pages now exist in the CMS, with preliminary assignments of Twin, Clone, and Solo. 

- Dev work is complete 
- Editors are identified
- Define ownership - who authors #10853
  - VHADM, Sitewide, Lovell editor
  - Are there Lovell Tricare editors vs Lovell VA editors
  - Field_administration is defined, editors have not been associated corresponding section yet (?)
- Editors have proper access to CMS
  - Assign/verify section and proper roles - content creator, editor, publisher 
- Determine what content already exists 
  - No content has come from Lovell editors - some pages exist but have not been authored 
- KB articles are modified or new one written #10027
  - From editors point of view:
    - This content is for TRICARE only, 
    - this content if for VA only, 
    - this content is identical for both VA and TRICARE, 
    - this content is similar with some changes between VA and Tricare 
  - How do I add a facility, remove a facility, modify facility data <- only difference is for creating new TRICARE facility in the future 
  - How do I add a service, remove a service, modify service data  <- identical to non-Lovell
- Coordinate with CMS Support 
  - Editors are given Lovell-custom training?
- CM Coordinate expectations and timeline with VHADM
- Associated DEV tasks - 
  - Confirm we are in dual state/tri state now (once PRs are merged?) 
  - Dual state when we publish it and banner is placed on Teamsite 

Add link to dave pickett's airtable sitemap - add to existing airtable 

As a reference, here is @davidmpickett's airtable of the [Lovell sitemap](https://airtable.com/appojvgFB7lvqgArz/tbljDFflQvxuHBWJK/viw0N9Q9DH5J3hjz5?blocks=hide)

## Acceptance Criteria
- [ ] Plan is written with major steps and owners 

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by JayDarnell** [comment]
@dsinla is there anything you need from the Dev team for this item?

**Comment by dsinla** [comment]
@JayDarnell I'm currently refactoring the notes above into a more complete plan, and creating tickets. So the short answer is - Not now, but would like a review when I have that done in the next day or so.

**Comment by dsinla** [comment]
| TASK                                                               | Projected Date   | PM | DEV | SUPPORT | VHADM | Ticket |
|--------------------------------------------------------------------|------------------|----|-----|---------|-------|--------|
| Editors are identified                                             | 10/15/2022       |    |     |         | x     |        |
| Primary dev work complete                                          | 10/15/2022       |    | x   |         |       |        |
| Review current sitemap and section assignments with VHADM          | 11/14/2022       |    |     |         | x     |        |
| Coordinate with CMS Support                                        | 11/17/2022       | x  |     | x       |       |        |
| CM Coordinate expectations and timeline with VHADM                 | 11/21/2022       | x  |     |         | x     |        |
| Grant editors proper access to CMS                                 | 11/21/2022       | x  |     |         |       |        |
| Merge Lovell FE enviroment                                         | 11/21/2022       |    | x   |         |       |        |
| Schedule training and get commitment with Lovell Editors and VHADM | 11/23/2022       |    |     |         | x     |        |
| KB articles are modified or new ones written (KB Intake)           | 11/28/2022       | x  | x   | x       |       | #10027 |
| Prep for Lovell Editor training                                    | 11/28/2022       | x  |     | x       |       |        |
| Dry-run of training                                                | 11/29/2022       | x  |     | x       |       |        |
| Conduct Lovell Editor training                                     | 12/1/2022        |    |     | x       |       | #11633 |
| Configure "BETA SITE" Banner                                       | 12/5/2022        | x  |     |         | x     |        |
| Assign pages to owners                                             | TBD              |    |     |         | x     |        |
| Create timeline for pages per owner                                | TBD              |    |     |         | x     |        |
| Pages are edited/created/tested                                    | 12/5 - 1/15/2023 |    |     |         | x     |        |
| Go-Live (Teamsite admin redirects pages to modernized site )       | 1/15/2023        |    |     |         | x     |        |

**Comment by dsinla** [comment]
@dawnpruitt would like a review of the above plan in our meeting on Friday, thanks!
