### ISSUE TITLE
React RadioButtons should transition to design system component by 12/21

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#11358]
## Description
https://dsva.slack.com/archives/C03R5SBELQM/p1666879267774979
> The VA Design System Team has deprecated the RadioButtons React component. We encourage all teams using the RadioButtons React component to upgrade to the [va-radio web component](https://design.va.gov/storybook/?path=/docs/components-va-radio--default). We have changed the ESLint warning to an ESLint error and have removed the documentation about the React RadioButtons component from Storybook.

The audit of PW-owned code was performed in the process of refining this ticket, so ACs center on swapping out the radio buttons on the one app we own that is impacted by the deprecation: 
* ~~Education how to apply page 10916~~ _VFEP team took care of it_
* 10 instances, all in the `/discharge-wizard` app. vsa-frontend is the only codeowner listed for this file
  * https://www.va.gov/discharge-upgrade-instructions/

## Additional info
FYI this wizard has a flipper related: `discharge_wizard_features`, "Iteration of new features for discharge wizard". I don't have context for what it's doing / how long it's been there, but it's worth keeping an eye on as you make this change, to confirm that we get expected behavior relative to flipper.

**Complexity to keep in mind and de-risk when possible**
The "guidance" screen has many conditionally-displayed components that combine in many ways depending on Veteran inputs. We've created a [Mural board](https://app.mural.co/invitation/mural/vagov6717/1670355600942?sender=u252e7152800e3981889d1910&key=789998a8-498d-419f-be6d-aef09cbf2e23) to help identify the flows and guidance permutations.

## Testing plan
The flow chart in the Mural above should be used to identify manual use cases that touch all known configurations at least once:
- All ~10 of the questions display correctly
- All possible responses to the ~10 questions are summarized accurately in the "Review your answers" panel at bottom
- Each results variation identified in the Mural can be triggered by some combination of responses
  - Alerts/Warnings
  - Form possibilities
  - Extra Info-alert text triggered by "having paperwork"

## Acceptance Criteria
- [x] Audit FE for RadioButtons React component
  - [x] vets-api
  - [x] content-build
- [x] Document which files include them _**and which are in our products**_
- [x] Write implementation ticket to migrate them to design system component, and send link to Wes/Jill for prioritization
- [x] RadioButtons component is not present in the discharge app
- [x] UX around the content itself (questions, order, advice yielded by app) does not change; links are consistent, sequence of questions is consistent
- [x] UX and Accessibility improvements made
  - [x] Eliminate extra padding to left of questions, so that questions are aligned with H1 at top of page (desktop and mobile)
  - [x] Questions that use non-radio inputs (eg Year of discharge) are changed from H4s to regular, non-bold text (consistent with radio-input questions)
  - [x] Heading "Review your answers" is an H2 (changed from H4)
- [x] Design system component is used instead
- [ ] All IDs for radiobuttons are unique. ([context](https://dsva.slack.com/archives/C52CL1PKQ/p1671661367323609?thread_ts=1671649127.116519&cid=C52CL1PKQ))

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [X] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by jilladams** [comment]
@wesrowe Bryan flagged in scrum today that FE code is now throwing eslint errors where the old buttons are used, which becomes a merge blocking error that we have to override. Ideally, we'd pipeline this work and get the existing buttons swapped.

**Comment by wesrowe** [comment]
@jilladams, quesiton came up about what will happen when the eslint rule is changed – could drive urgency of this ticket

**Comment by jilladams** [comment]
Yep, that'll require follow up. I don't know the answer.

**Comment by jilladams** [comment]
Although: GovCIO is tracking against a Dec 7 deadline for updating theirs, now that I think about it. Asked https://dsva.slack.com/archives/C52CL1PKQ/p1669933182722849 where they got that date. If it's a real cliff, yes, will need to get this pulled in.

**Comment by jilladams** [comment]
Dang: https://dsva.slack.com/archives/C03R5SBELQM/p1666879267774979
> On Wednesday, December 7th, we will remove the React RadioButtons component from the component library.

**Comment by jilladams** [comment]
https://dsva.slack.com/archives/C52CL1PKQ/p1670001411736729?thread_ts=1669933439.333299&cid=C52CL1PKQ

10 instances, all in the /discharge-wizard app

Converting to implementation ticket.

**Comment by jilladams** [comment]
12/6 design system update: removing React component delayed to 12/21

**Comment by wesrowe** [comment]
## Wes testing comment (WIP)
_I'll add to this comments as I work through test cases_

### Method:
Identify test flows in Mural, ensuring each of the following is covered once
  - all reasons
  - all questions
  - all branches
  - all "end" points (i.e., test truncated flows too)
Label flows in mural using consistent convention, e.g. `[reason] - [branch] - [variants]`

For each labeled flow, test Prod and [review instance](http://84c468ba36327c50e78a3050ae5fc91a.review.vetsgov-internal/discharge-upgrade-instructions/) side-by-side, and screen-shot:
  - "review answers" section
  - results page
