### ISSUE TITLE
DSN: Design frontend operating status + covid status alert 

### ISSUE THREAD

**Issue by jcklpe** [department-of-veterans-affairs/va.gov-cms#11361]
## Description
Design the frontend for a combined alert that covers both general operating status needs and covid status alert

Related tickets: 
#10842
#10708

## Acceptance Criteria
**NOTE** this is aggressive with dependencies on review with JHL

- [ ] have a sketch wireframe 
- [ ] PM approve
- [ ] Tech review and approval
- [ ] PO approve

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by davidmpickett** [comment]
![Screen Shot 2022-10-27 at 1 57 03 PM](https://user-images.githubusercontent.com/51967950/198375412-62e259cc-4465-4d9c-a235-28facd3b6b56.png)

**Comment by davidmpickett** [comment]
![screencapture-va-gov-birmingham-health-care-locations-2022-10-27-13_58_16](https://user-images.githubusercontent.com/51967950/198375593-b5d3afb9-1959-4077-bdac-6b8ba911d3ac.png)

**Comment by jcklpe** [comment]
Relevant design system docs: [https://design.va.gov/components/alert-expandable](https://design.va.gov/components/alert-expandable)  
  
Example of context in production: 

*   [https://www.va.gov/birmingham-health-care/locations/bessemer-va-clinic/](https://www.va.gov/birmingham-health-care/locations/bessemer-va-clinic/)

![](https://user-images.githubusercontent.com/9451726/198375344-36fdb967-04d2-4dea-b417-e4bb2a2aa7a9.png)

**Comment by davidmpickett** [comment]
![screencapture-va-gov-birmingham-health-care-2022-10-27-13_58_53](https://user-images.githubusercontent.com/51967950/198375710-b94d2102-6d4f-4fd0-a7c1-a63c9155f34b.png)

**Comment by EWashb** [comment]
This is great. I recommend adding an AC for tech review just to make sure we don't get too far down the road before the next collab sesh.

**Comment by dsinla** [comment]
I know I missed the tail end our meeting last week Thurs where this was being discussed. @swirtSJW had some concerns about a Veteran preparing for their visit _next week_, who might not see COVID information if it was replaced by some other alert like a hurricane warning for that day.
Are we saying that COVID status will still be included in the alert - so in this case it would be both COVID and Hurricane alert?
@jcklpe @dawnpruitt

**Comment by jcklpe** [comment]
> This is great. I recommend adding an AC for tech review just to make sure we don't get too far down the road before the next collab sesh.

@EWashb  added. Do we have a specific person to take point for tech reviews? @swirtSJW perhaps?

**Comment by jcklpe** [comment]
> Are we saying that COVID status will still be included in the alert - so in this case it would be both COVID and Hurricane alert?

Yes that is the idea as I understand it. Instead of having multiple alerts there would be one big alert box with multiple pieces of information in it.   
  
Whether this is a good idea I think is sort of up in the air. It's based on editor feedback I believe. Is it actually necessary. Does it just look sort of weirdly patterned but it reflects a meaningful semantic distinction? IDK. I can go either way on the issue.   
  
I think a push towards a more generic solution to alerts is not a bad idea though.

**Comment by dsinla** [comment]
Blocked by completing the Content Model discussion which is owned by @davidconlon 
@dsinla to find Cont Model ticket and note dependency

**Comment by dsinla** [comment]
Meeting scheduled Tuesday, November 8 4pmET
Review COVID Protection Levels

**Comment by davidmpickett** [comment]
This might be a good candidate for Jordan to work on

**Comment by dsinla** [comment]
Option 1 - 2 free open text fields.
Operating status: Stays as is
COVID Health Protection Levels 
Keep High Medium Low
Adding limited RTF ~ 500 character 
Based on H, M, L - populate with policy language
No need to preserve state if they switch from M to L 
RTF does not need to go to Lighthouse
Do not surface policy language in FL, link to page .

**Comment by davidmpickett** [comment]
Wireframe for proposed FE updates to Facility Locator 
[Facility Locator search.pdf](https://github.com/department-of-veterans-affairs/va.gov-cms/files/10060492/Facility.Locator.search.pdf)
![Facility Locator Search Results](https://user-images.githubusercontent.com/51967950/203157363-c325b888-ec28-407f-8bfd-b84ad53f96fb.png)

**Comment by davidmpickett** [comment]
Sent to Facilities team channel on Slack for review

**Comment by swirtSJW** [comment]
Link to slack discussion https://dsva.slack.com/archives/C0FQSS30V/p1669064797811809

**Comment by laflannery** [comment]
Had a quick meeting with @davidmpickett  - He confirmed that we should add "Maps" back to the Directions link in the revised designs (it was just an oversite that it was removed)

**Comment by dsinla** [comment]
Thanks @davidmpickett. As discussed this morning, this looks like what we want - remove the expanding test in the Facility Locator results list. 👍

**Comment by davidmpickett** [comment]
@dsinla @swirtSJW To keep the ball rolling with this, would probably be good to get a follow up FE ticket stubbed out for Refinement this week.
