### ISSUE TITLE
FE: On VA system page, the toggle is set  to the wrong spot.

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#11373]
When on the Lovell VA system page https://web-liqqgmzl7tsyfbwyulbkuborufuuttav.demo.cms.va.gov/lovell-federal-va-health-care/  The toggle says you are on the TRICARE.
![image](https://user-images.githubusercontent.com/5752113/198677750-ff606130-5352-4cf0-86e4-1c97a726f980.png)

## AC
- [ ] When on Loveel VA system page, toggle indicates you are viewing as VA and has link to tricare.

**Comment by dawnpruitt** [comment]
@maxx1128 please point this ticket :) Thanks!
