### ISSUE TITLE
CMS work out updates block questions

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#11375]
There are some questions and some possible issues (depending on the answers) related to the "Get updates block" on the TRICARE system page
![image](https://user-images.githubusercontent.com/5752113/198681130-774fc120-0f3f-4a0a-8d98-35a951da7e6f.png)

AC
- [ ]Question asked and answered with VHADM/Lovell editors

**Comment by omahane** [comment]
@dsinla Who will determine the necessity of the "Get updates" block?

**Comment by dsinla** [comment]
1. What's going on with the link to Oper Status page - for Facilities to 
2. Lovell Editors - We have these for VA, but not sure where they should point for TRICARE

**Comment by JayDarnell** [comment]
@dsinla did we sort out the ACs for this? I feel like we talked about this as a group this week but I don't remember what was decided, if anything, and the ticket hasn't been updated.

**Comment by swirtSJW** [comment]
@JayDarnell  This ticket should be closed as the only outcome that needed action was 
![image](https://user-images.githubusercontent.com/5752113/201227938-add9083e-cf33-426a-be34-681c88c50aea.png)

**Comment by swirtSJW** [comment]
@dsinla If that ticket has been created, this can be closed.

**Comment by dsinla** [comment]
Thanks @JayDarnell for following up
I will 
1. Add the question for VHADM - do the links in the Update Block have analogs for TRICARE?
2. Create a ticket and add to punchlist ticket for correcting the link to Operating Status page.
