### ISSUE TITLE
Content-build self-hosted runners should use ASG-managed runners wherever possible

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#11402]
## Description
In #11400, we determined that running containerized jobs as root on a given runner instance can interfere with non-containerized jobs running on that same runner later on. 

Work is being done in https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12435 to set up creation of custom containers that will allow GHA & Docker to run as the runner user, rather than as root.

Once this is complete, we should be able to begin using the same runners for any self-hosted job that does not use an on-demand runner. Ideally, we should be able to use ASG-managed runners for everything that is not on-demand.

## Acceptance Criteria
- [x] The Continuous Integration and Accessibility workflows' containerized Cypress test jobs run successfully without specifying the root user
- [x] Containers which have previously run the containerized Cypress test jobs are later able to run other self-hosted jobs that use the `checkout` command
- [x] Provided the above two are true, all content-build workflows are converted to use ASG runners.

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [x] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by timcosgrove** [comment]
https://github.com/department-of-veterans-affairs/content-build/pull/1371 moved the validate build step to use the on-demand runner.

https://github.com/department-of-veterans-affairs/content-build/pull/1372 moves other jobs within the workflow to either Github Action runners or the on-demand runner, depending on what the jobs require and whether they are required to operate concurrently with another job.

We will deploy 1372 and observe. Previously, Github Action runners would at times be slow to spin up because of difficulty securing a runner from Github. We are experimenting to see if that is still the case.

**Comment by timcosgrove** [comment]
Moving runners to GHA-hosted runners failed most jobs because they require CMS access. We reverted this.

**Comment by timcosgrove** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/issues/50148

**Comment by timcosgrove** [comment]
Issue is blocked pending help/assistance from the Devops and/or Front End COPs.

**Comment by TheBoatyMcBoatFace** [comment]
Currently blocked. Moving to Sprint 75.

**Comment by timcosgrove** [comment]
This has been delayed due to unplanned critical defect work: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12543
