### ISSUE TITLE
Expand Flag / views bulk action permissions to Content Admins

### ISSUE THREAD

**Issue by chri5tia** [department-of-veterans-affairs/va.gov-cms#11404]
## Description
In the PR for #11285, https://github.com/department-of-veterans-affairs/va.gov-cms/pull/11335#event-7709281993, Christia started process to add Content Admin permissions; @swirtSJW requested we break permissions out into its own task for review / separate PR.

VA Forms has 4 audit views that include bulk actions (and a 5th that does not), and permissions for performing bulk actions vary by view (in order of tabs below). The Action dropdown menu items that relate to removing flags is driven by whether users have permissions to modify flags, **not** whether the user has global permissions on Views Bulk Actions.

So: Scope of the ticket is now: 
* Give Content Admins permission to modify flags. 
  * If that permission is flag specific, give them permission on Changed FIlename, Changed Title, New form, Deleted form.
* Make sure that as a Content Admin you can see the Actions dropdown on those 3 new views, & modify flags
 
View | Current roles that can see the bulk actions dropwdown on a view | Desired perms
--- | --- | --- 
[VA Forms](https://staging.cms.va.gov/admin/content/va-forms) | Content Admins, Drupal Admins, maybe other roles | Content Admins, Drupal Admins 
[Audit](https://staging.cms.va.gov/admin/content/va-forms/audit) | N/A, does not include any bulk actions | N/A
[Changed Filename](https://staging.cms.va.gov/admin/content/va-forms/changed-filename) | Drupal Admins | Content Admins, Drupal Admins 
[Changed Title](https://staging.cms.va.gov/admin/content/va-forms/changed-title) | Drupal Admins | Content Admins, Drupal Admins
[New/Deleted Forms](https://staging.cms.va.gov/admin/content/va-forms/new-deleted) | Drupal Admins | Content Admins, Drupal Admins

### Concerns to be investigated

Changing permissions on Forms Flags could change permissions in other areas as well. We need to understand those side effects before selecting a path forward. If giving permission to Content Admins

**Clarification:** The permission relates to _all bulk operations_, not just Flags.

**Open questions to decide before assigning:** 
- [x] 1. Who owns flagging/unflagging (related info in [Mural](https://app.mural.co/t/vagov6717/m/vagov6717/1666820558104/5b87095d4d16ad7c8e7825567bd84ff53be71724?sender=u252e7152800e3981889d1910))
- [x] 2. Do they/ should they have permission to this action in the form audit views for flagging and unflagging
  - Decision: in our current setup, Content Admins covers all the users who would need permission to clear Forms Flags and would not include anyone who shouldn't have permission; gut need to evaluate side effects before implementing that permission.
- [X] 3. Are there other places in the CMS where the flagging/unflagging action is performed?
- [X] 4. Do permissions need to be updated?

## Acceptance Criteria

- [X] Investigate questions 3 & 4 above:
  - [X] 3. Are there other places in the CMS where the flagging/unflagging action is performed?
  - [X] 4. Do permissions need to be updated? 
- [X] Share findings with Steve W, and others if needed
- [x] Update Content Admin permissions to allow flagging / unflagging
- [x]  As a Content Admin, I can see the Actions dropdown on Changed Filename, Changed Title, & New/Deleted views
  - [x] Can use Actions to remove flags

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [X] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by wesrowe** [comment]
Discussion ([Slack thread](https://dsva.slack.com/archives/C52CL1PKQ/p1667413840310219)) led to decision that Content Admins are the only group who needs permission to clear Forms Flags. Noted in ACs above.

**Comment by wesrowe** [comment]
So... Questions #3 and #4 need someone else's review, passing it back to @chri5tia .

**Comment by chri5tia** [comment]
PR: https://github.com/department-of-veterans-affairs/va.gov-cms/pull/11498
