### ISSUE TITLE
Clean up excess Content Build references and prevent them from accumulating

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#11405]
## Description
In #11402 and #11403 we set up ASGs to properly service self-hosted jobs that make use of containers. We have two ASGs that collectively provide a baseline of 10 instances (5 each), and spin up new instances if needed and then cull them. 

At time of writing, [there are 97 instances running that can service Content Build](https://console.amazonaws-us-gov.com/ec2/v2/home?region=us-gov-west-1#Instances:instanceState=running;search=:content-build;v=3;$case=tags:true%5C,client:false;$regex=tags:false%5C,client:false;sort=desc:launchTime). This is far in excess of what is needed. We should determine why extra instances are being created, and prevent that; set up rules that cull instances after some amount of time; and remove unneeded instances that are currently running.

Having all jobs use ASG-provided instances *should* take care of this automatically, but we should make sure this is happening.

## Acceptance Criteria
- [x] We identify why large number of instances are being created and not removed
- [x] Confirm ASGs will rotate instances out and retire them
- [x] Confirm instances in use will not be retired until they are not in use (don't interrupt a runner that is being used)
- [x] Excess instances are removed

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [x] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by olivereri** [comment]
* _We identify why large number of instances are being created and not removed._
The exact why isn't confirmed but there's an issue in the on-demand runner Github Action that is responsible for creating and terminating instances.  Related issue: https://github.com/department-of-veterans-affairs/va.gov-team/issues/44319

* _Confirm ASGs will rotate instances out and retire them_
Platform's implementation of GHA runner auto-scaling has policy in place to add elasticity.  Based on how busy the runner processes are on each server the ASG will add or remove instances. https://console.amazonaws-us-gov.com/ec2/home?region=us-gov-west-1#AutoScalingGroupDetails:id=dsva-vagov-content-build-gha-runners-asg;view=scaling

* _Confirm instances in use will not be retired until they are not in use (don't interrupt a runner that is being used)_
Platform's implementation of GHA runner auto-scaling adds scale in protection to EC2 Instances that have an active runner process.
https://github.com/department-of-veterans-affairs/devops/pull/9595

**Comment by olivereri** [comment]
Instances still running from July 2022:
![image](https://user-images.githubusercontent.com/31904439/224407997-4483822e-ba1b-41d8-a6e7-91449ca7c13d.png)

**Comment by olivereri** [comment]
Output of all running instances to be removed.
[AWS CLI Output.txt](https://github.com/department-of-veterans-affairs/va.gov-cms/files/10945595/AWS.CLI.Output.txt)

**Comment by olivereri** [comment]
Script used to terminate instances on AWS Cloud Shell.

```
#!/bin/bash

# Get all unneeded on-demand content-build runners. Filter by name, instance state, and importantly private I.P.
content_build_gha_runners=$(aws ec2 describe-instances \
  --filters \
  Name=tag:Name,Values=dsva-vagov-content-build-gha-runner* \
  Name=network-interface.addresses.private-ip-address,Values=100.* \
  Name=instance-state-name,Values=running \
  --query \
  "Reservations[*].Instances[*].InstanceId" \
  --output text )

# Make sure the string output from above is a BASH list.
content_build_gha_runners_array=($content_build_gha_runners)

# Get list count for sanity
echo ${#content_build_gha_runners_array[@]}

# Terminate all on-demand instances
for instance in "${content_build_gha_runners_array[@]}"
do
        aws ec2 terminate-instances \
                --instance-id $instance
done
```
