### ISSUE TITLE
Automated (time based) Content releases should not happen on lower environments

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#11413]
[Discussion in slack](https://dsva.slack.com/archives/C02HX4AQZ33/p1667336445457789) 

## Description
Automatic content releases are continuing to happen on lower environments
The one upside to it is that lower environments match the same behavior as prod, so we have environment parity.  However there are several problems created by this setup:

1. Performance issues on tugboat.    Every instance is constantly churning for no good reason.
2. Web is down as often as it is up.  on prod, while a new web is being built, the old one is still available until it is instantly replaced by the new version.  On tugboat the web environment is wiped out as the new one is being built.  It takes 30 min to build, and the build happens every 45ish minutes, so Web is down for 2/3 of the time.
3. May auto-rebuild with the wrong intended branch (have not fully confirmed this yet)

## ACs
- [ ] On tugboat and local environments, the auto releases should not happen.
- [ ] On tugboat and local environments, if a content release is requested in the UI, it should happen only once for each request.
- [ ] Make content releases on lower environments configurable with a default to auto = off

**Comment by swirtSJW** [comment]
Here is an example of the content releases running on an a PR environment.
![image](https://user-images.githubusercontent.com/5752113/199345957-3a272c7b-8e42-40c5-bf9b-a95988e41844.png)

**Comment by cmaeng** [comment]
consider timing configurations

**Comment by timcosgrove** [comment]
The following state value determines whether continuous content release is enabled:
```
va_gov_build_trigger.continuous_release_enabled
```
We can disable continuous release on Tugboat by setting that state to 0/FALSE. This should be done to the base preview. Currently looking for the best place to do this.
