### ISSUE TITLE
Discovery: Orphaned paragraphs

### ISSUE THREAD

**Issue by edmund-dunn** [department-of-veterans-affairs/va.gov-cms#11415]
## Description
While working on the table audit, I found some orphaned paragraphs. For this ticket, we need to surface all orphaned paragraphs. 

## Acceptance Criteria
- [x] Surface all orphaned paragraphs. 
- [x] Determine where the orphans are being created and note

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [x] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by EWashb** [comment]
Hypothesis: these originated from clones

**Comment by EWashb** [comment]
There is a paragraph de-orphaner in the CMS already. May want to test this beforehand to see if it's what we want to do.

**Comment by edmund-dunn** [comment]
Additional hypothesis: these originate from editors:
![CleanShot 2022-11-29 at 10 12 21](https://user-images.githubusercontent.com/109987005/204612907-6145b15a-745d-4d4b-bb68-4e5a29313186.png)
This is an orphan paragraph. 
![CleanShot 2022-11-29 at 10 10 35](https://user-images.githubusercontent.com/109987005/204612973-9e0c4744-42e9-4a20-b46a-118cd1f0e8bb.png)
This is the Diff of the revision for the node it belongs to. It appears the editor doesn't know how to take down the alert, so just deleted or attempted to delete all of the content, which resulted in an orphaned paragraph.

**Comment by laflannery** [comment]
Next steps:
- Make this report part of the admin reports dropdown to keep an eye on it (regular access)
- Discovery around the root cause of why this is occurring
   - Look at different content types
   - Possibly reach out to editors to see what happened, why they did what they did

**Comment by laflannery** [comment]
Spike ticket created #11754

**Comment by EWashb** [comment]
@edmund-dunn are you all done with this? I know you said there was an issue, but I want to make sure we address it before we close
