### ISSUE TITLE
FE: Add TRICARE fallback to Lovell Service descriptions

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#11422]
## Description
As a visitor to a TRICARE page, I want to see a TRICARE specific service taxonomy description if one exists, otherwise I want to see the VAMC service taxonomy description

These descriptions appear in two places
1) on the facility pages inside the services accordions /lovell-federal-tricare-health-care/locations/*
![image](https://user-images.githubusercontent.com/5752113/199581154-f96317b5-4f93-4eba-950a-7940a1c48508.png)

2) on the system services page /lovell-federal-tricare-health-care/health-services/
![image](https://user-images.githubusercontent.com/5752113/199581611-285ac707-6e45-4f41-9466-1cc4f75fc5de.png)

## Acceptance Criteria
- [ ] Tricare facility pages show the TRICARE descriptons when conditions are met.
- [ ] Tricare system services page shows the TRICARE descriptions when conditions are met.
- [ ] Conditions that must be met to see Tricare service taxonomy description
   - [ ] Service belongs to section Lovell - TRICARE
   - [ ] Service has a TRICARE description  (health_care_service_taxonomy->field_tricare_description not empty)

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by JayDarnell** [comment]
@maxx1128 I would be interested in taking this off your plate if you're currently overloaded and if I can get a primer for where this lives in the front end code.

**Comment by maxx1128** [comment]
@JayDarnell Sorry I should have been clearer here, I'm okay with you taking this ticket. I'm not hugely familiar with the accordian content here myself so likely can't give much of a primer unfortunately.

**Comment by dawnpruitt** [comment]
Can we remove the blocker showing above?
