### ISSUE TITLE
Move page to soft-launch/beta URL

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#11425]
## Description

The URL we used on Staging for usability testing: `/homepage-test`
That path was established here: https://github.com/department-of-veterans-affairs/content-build/pull/1081/files#diff-9d481a9d1d5399befb7b3d6424a262b6e38796b248c017c0f6bacddd4bd54814

We want to move to the URL `/new-home-page` that is a little more public-facing and relevant to beta testing.

## Acceptance Criteria
- [x] Nothing at `/homepage-test` on either Staging or Prod
- [x] New homepage available at `/new-home-page` on Staging and (on launch day) on Prod

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by jilladams** [comment]
Need to be mindful of URL change and publishing to Staging only until launch.
