### ISSUE TITLE
Table audits cleanup

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#11435]
## Description
There are a few issues with the Table audits.  
that should be cleaned up for consistency.

## Acceptance Criteria
- [ ] Tabs should be alpha sorted 
![image](https://user-images.githubusercontent.com/5752113/199657287-25a12e91-621f-4635-888f-61d31817a649.png)
- [ ] we don't have  (New) pattern on tabs anywhere.  That will become outdated fast. Can we remove it?
- [ ] The original Tables audit seems to not speak the truth about the number of tables.  Its only value seems to be that it has filters where the new one doesn't.  Can we implement the filters on the new one, and remove the old completely?
- [ ] One of the Views style guide criteria is that we use meaningful machine names on our View displays instead of the generic defaults.  Can we update the machine names to mimic the original View machine names?
![image](https://user-images.githubusercontent.com/5752113/199658058-36ad6e1a-7318-4808-aadb-8263cedc0df2.png)
- [ ] The View needs a Caption that tells us what we are looking at.
![image](https://user-images.githubusercontent.com/5752113/199658296-b0f5b112-49ac-4fe5-9cdd-2b5f84eb7dbe.png)

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [x] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by laflannery** [comment]
Randi and I discovered a [discrepancy ](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10793#issuecomment-1307552025) with the new table audit.  I wanted to mention it here so these could possible be looked at together

**Comment by edmund-dunn** [comment]
Not adding filters at this time. That will have to be a separate issue at a later time. This iteration will remove the old table audit, and make the other requested updates.
