### ISSUE TITLE
DSN/PM: Audit current use of VAMC System Banner Alerts to determine how best to educate and guide editors 

### ISSUE THREAD

**Issue by dsinla** [department-of-veterans-affairs/va.gov-cms#11434]
## Description
We want to limit VAMC System Banner Alerts to one per system, and impose a character limit. In parallel, we should conduct an audit of how VAMC System Banner Alerts are currently being used, and misused, to determine what editors are trying to accomplish and provide guidance and education on how to accomplish the same goals without using the banners.

Some initial audit of current KB: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11141

## Acceptance Criteria
- [ ] Produce an audit of currently used System Banner Alerts. screenshots? and notations - list Banners per System
- [ ] Create and enumerate categories/patterns of banner use: ie Promotion, Marketing, Recruiting 
- [ ] Produce report showing categories/examples

@dsinla  to spin up into new tix:
- [ ] Create draft of Content Strategy for each of the scenarios  _When you want to promote an event, use...When you want to list detailed COVID policies use..._
- [ ] Provide recommendations for each scenario

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by davidmpickett** [comment]
In sprint planning, I volunteered to support David S on this ticket

**Comment by dsinla** [comment]
Shared [google sheets link ](https://docs.google.com/spreadsheets/d/1UWX4bO8nBbGfgnL8HkFgF0W5iRczl-p8/edit?usp=sharing&ouid=110266615980766295586&rtpof=true&sd=true )with @davidmpickett for co-working. Thanks!

**Comment by dsinla** [comment]
Final counts:

| Banner topic                                                                           | Count |
| -------------------------------------------------------------------------------------- | ----- |
| Coranavirus Vaccine Available/Not Avail                                                | 114   |
| Website Coming Soon                                                                    | 78    |
| Coronavirus Levels/Facilty/Masks Policy                                                | 66    |
| Weather closing/opening/modified hours                                                 | 14    |
| Non-Covid Vaccine                                                                      | 12    |
| Weather advisory - be prepared (including fires/air quality)                           | 11    |
| Coranavirus Testing availability                                                       | 9     |
| Facility status/closure/waittimes (construction)                                       | 8     |
| Phone upgrade/outage/restored                                                          | 7     |
| Facility status/closure (incident/bomb threat)                                         | 3     |
| In The Know/Quick Info/Various notices/Link to multiple updates/Phone Numbers/Pact Act | 3     |
| Holiday closure                                                                        | 2     |
| Recruiting/Hiring                                                                      | 2     |
| Normal Operating status                                                                | 2     |
| Llimited hours/services - no reason                                                    | 2     |
| Location/address change                                                                | 1     |
| Non Covid visitation policy (eg Service Animal)                                        | 1     |
| Happy Veterans Day                                                                     | 1     |
| Updated Veterans Crisis Number                                                         | 1     |
| Electronic Health Record Letter                                                        | 1     |
| Bene-travel                                                                            | 1     |

**Comment by dsinla** [comment]
Reviewed with team this am. Marking closed. 
[BannerAlertsAuditFINAL.xlsx](https://github.com/department-of-veterans-affairs/va.gov-cms/files/10125396/BannerAlertsAuditFINAL.xlsx)
