### ISSUE TITLE
CMS Notifications Research: Create Email Prototype

### ISSUE THREAD

**Issue by EWashb** [department-of-veterans-affairs/va.gov-cms#11440]
## Background

We need something to test with users! The MVP for notifications is email, so let's think through a prototype of how an email would appear for editors.

## Acceptance Criteria

- [x] Let's prototype something for research- this should be email
- [x] Work with PO/PM to determine what the emails will say
- [x] Any other recommendations for the research plan are shared

**Comment by EWashb** [comment]
How do we surface outdated content and what should they be checking.

**Comment by EWashb** [comment]
work with VHA dig media to see the research plan

**Comment by EWashb** [comment]
This was deprioritized for sprint 71. Will pick back up possibly 72 or 73

**Comment by EWashb** [comment]
@BlakeOrgan can you post the figma link to your prototype? And then we can close this :)

**Comment by BlakeOrgan** [comment]
Here's the Figma link that we're using for user research interviews.
https://www.figma.com/file/fQl2Y2k9MDA2dc0xViC645/6102-Notification-Email?node-id=69%3A696&t=k3dFM0g0tvfFefIN-3

Per Dave C's request, I checked with @laflannery for any 508 issues and checked with @edmund-dunn to see what the level of effort to implement this design would be. He said that it shouldn't be too difficult and estimated that it should only take about 1-2 sprints worth of work.

This design might also be updated based on the feedback that we get during the user research interviews.
