### ISSUE TITLE
Redirect Request For online Form 22-1990n 

### ISSUE THREAD

**Issue by jsimonVA** [department-of-veterans-affairs/va.gov-cms#11444]
### Instructions
- Requests must be submitted **AT LEAST** 2 weeks in advance.  Some requests take a significant amount of time and coordination to implement, so start the process as soon as you know you will need one. 
- This issue will be used from initial request through implementation to ensure all individuals working on this are notified of status updates.  Please do not create multiple issues to track different steps.
- It is your responsibility to notify VA stakeholders as appropriate.  

### Type of request
- [x] We are retiring or taking down a page and need to redirect the URL (complete redirect section)
- [ ] We are changing the URL of an existing page (complete redirect section)
- [ ] We need a custom vanity URL (complete vanity URL section)

### Implementation date
When does this request need to be live: 
The current live date is supposed to be 25 Oct 2022. We can work with your schedule for the first release date.

### Redirects 
Not sure the best approach for this. Currently there is a link to the online form 22-1990n. The online version of this form is being removed and will no longer be accepted by the Education team. However, the PDF version of this form will remain online. I need to remove the URL or perhaps have it direct to the page with the downloadable PDF.

### OUTSTANDING in S82
Current URL | Redirect To
--- | ---
https://www.va.gov/education/apply-for-education-benefits/application/1990N/ | https://www.va.gov/education/other-va-education-benefits/national-call-to-service-program/ 

### COMPLETED in S71 -- NEEDS TO BE REMOVED
Current URL | Redirect To
--- | ---
https://www.va.gov/education/apply-for-education-benefits/application/1990N/introduction | https://www.va.gov/education/other-va-education-benefits/national-call-to-service-program/
### Vanity URLs 
Vanity URL  |  Landing page: none
---  |  ---
requested URL | landing page URL: none

**Link to campaign landing page request issue:**

### Process, Roles and Responsibilities
- [ ] Requesting team: Above information is provided
- [ ] Requesting team: All appropriate VA stakeholders are notified as appropriate
- [ ] IA: Request is vetted and documented and implementation plan is clear 
- [ ] IA: Request is assigned to appropriate team for implementation 
- [ ] Implementation team: Work is complete
- [ ] Implementation team: Validated in production
- [ ] Requesting team: Validates everything is correct in production and closes ticket

**Comment by jsimonVA** [comment]
@jilladams thanks for the update

**Comment by jilladams** [comment]
verified in prod

**Comment by mnorthuis** [comment]
@jilladams I need to reopen this ticket because this redirect was not correctly vetted.  The URL that needs to be redirected should always be the top level canonical URL of a form flow.  Unfortunately, what was requested here was the /introduction page, which means that the canonical URL https://www.va.gov/education/apply-for-education-benefits/application/1990N/ still appears in search and is still available to users.    We need to update our redirect to the following:

Redirect this URL: https://www.va.gov/education/apply-for-education-benefits/application/1990N/
To this URL:  https://www.va.gov/education/other-va-education-benefits/national-call-to-service-program/

My apologies that this wasn't caught before your team implemented. Can you please move this into your queue at your earliest convenience?

**Comment by jsimonVA** [comment]
@mnorthuis @jilladams, I just want to make sure that we are on the same page with this one. The online form was removed and should not be accessible so we shouldn't need a url for this.

**Comment by mnorthuis** [comment]
The online form hasn't actually been taken down and is still available online, and unfortunately, this redirect request captured a sub-directory of the URL, not the top level of it.  So if you go to the URL I have above, you can access the form and complete it. 

We need to update the redirect to capture it from the top level so users cannot get to the form at all, and are instead redirected to the static page and the PDF.  I believe that was the effect you were going after, correct?

**Comment by jilladams** [comment]
FYI @wesrowe : old redirect that needs an update, TBD scope once @jsimonVA confirms based on last comment from Mikki. I moved it back to top of Stretch. @mnorthuis  This sounds like we'd need to inject in sprint, vs. waiting 2 weeks to pick up in next sprint?

**Comment by jsimonVA** [comment]
@mnorthuis, you are correct. in the end the form should not be accessible.

**Comment by jilladams** [comment]
Thanks all. @mnorthuis should we be removing the intro redirect? Or ok to leave that in place and add the new one?

**Comment by mnorthuis** [comment]
@jilladams We need the redirect at the to level of the form, and have it capture all child pages of the form.  So you can remove the one that's there and replace it  with a redirect that captures https://www.va.gov/education/apply-for-education-benefits/application/1990N/  and all of its sub-pages.

**Comment by mnorthuis** [comment]
@jilladams You can work in at your convenience, I don't want to interrupt sprint flow, and this has already been out there incorrectly for awhile with no alarm bells.

**Comment by jilladams** [comment]
Top level page is now redirecting, but now the `/introduction` path isn't. I believe that's just a syntax fix. Will find otu and get it updated.

**Comment by mnorthuis** [comment]
Hi @jilladams please make sure all URLs under that top level URL are redirecting.  Thank you

**Comment by jilladams** [comment]
Change merged today that should deploy Wed 4/26, that will handle
   - `/education/apply-for-education-benefits/application/1990N/` (trailing slash)
   - `/education/apply-for-education-benefits/application/1990N` (no trailing slash)
   - `/education/apply-for-education-benefits/application/1990N/introduction` (subpages)

@ryguyk noted: the most recent change will stop working for the path with no trailing slash, if/when the original page goes away. We've entered the realm where it would be better for an engineer to pick up this piece, vs. me poking at it more. @wesrowe adding to Sprint 83 plan to get a final change here from the options below: 

1. **Remove trailing slash in the `src`:**
```
src: ^/education/apply-for-education-benefits/application/1990N
```
This would match:
   - `/education/apply-for-education-benefits/application/1990N`
   - `/education/apply-for-education-benefits/application/1990N/introduction`
   - `/education/apply-for-education-benefits/application/1990N2` (this might not be desirable)

2. **Add `?` to the end:**
```
src: ^/education/apply-for-education-benefits/application/1990N/?
```
This will have same effect as above.

3. **Have two rules:**
```
src: ^/education/apply-for-education-benefits/application/1990N$
```
```
src: ^/education/apply-for-education-benefits/application/1990N/
```
This would match:
   - `/education/apply-for-education-benefits/application/1990N`
   - `/education/apply-for-education-benefits/application/1990N/introduction`

This would _not_ match:
   - `/education/apply-for-education-benefits/application/1990N2`
   - `/education/apply-for-education-benefits/application/1990N2/introduction`
