### ISSUE TITLE
Defect: Pagination on Outreach materials missing page numbers previous to current page 

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#11442]
## Describe the defect
On [Outreach Materials](https://www.va.gov/outreach-and-events/outreach-materials/#pager-previous-click), as you click to next page of results the numbers for previous pages disappear:

![image.png](https://images.zenhubusercontent.com/61a671f5fc46c2a311655f75/b54e6af2-16f7-4f30-8e94-44effd857adc)

## Additional context
Add any other context about the problem here. Reach out to the Product Managers to determine if it should be escalated as critical (prevents users from accomplishing their work with no known workaround and needs to be addressed within 2 business days).

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by jilladams** [comment]
This is maybe not how design system intends things to act. 

Josh flag: https://dsva.slack.com/archives/C52CL1PKQ/p1668522628557179

Wes follow up with Design system: https://dsva.slack.com/archives/C01DBGX4P45/p1668536794031689
> Question about [va-pagination](https://design.va.gov/storybook/?path=/docs/components-va-pagination--default) – and pagination in general. "last-page" behavior is built in. But "first-page" behavior doesn't seem to be. I.e., if I'm deep into the pages, the only way back to 1 seems to be to hit "previous" a bunch of times. Is that desired? (Note: I tried playing around in Storybook but there seems to be a bug; it doesn't respect the max-page-list-length property.) Here's a screenshot where i'm on screen 6 and would have to click 5 times to return to page 1.

Marking Blocked.

**Comment by wesrowe** [comment]
It's a little unclear still whether this is behaving as the Design System intends with their `va-pagination` component. However, this page (and Search Results, and probably others) uses an older pagination component. 

- In some circumstances the DS component would continue to show page 1 as the user increments to higher pages – e.g., if there are only 5 pages, page 1 would always be visible in pagination. 
<img width="523" alt="image" src="https://user-images.githubusercontent.com/4054752/202030285-c5ea21c9-a18e-4a6b-8b30-cbb72d059db5.png">

- However, the DS component generally doesn't prioritize getting back to lower page numbers; you often can only do it by clicking the 'previous' button.

Lastly, @jilladams and I heard from Dave Conlon this morning that the Outreach library might be headed for more changes. So this minor enhancement isn't worthwhile at this time.

Closing as a no-op with my thanks to @jtmst for his research into how pagination is implemented elsewhere on the site, using what components.

**Comment by wesrowe** [comment]
Update: Matt Dingee said in this [comment](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1233#issuecomment-1258046629) (referenced in this [slack thread](https://dsva.slack.com/archives/C01DBGX4P45/p1668606657619829?thread_ts=1668536794.031689&cid=C01DBGX4P45)) that the DST is "going to adopt the [USWDS pagination](https://designsystem.digital.gov/components/pagination/) design. It solves for this."
