### ISSUE TITLE
DSN: Document Findings of Public Contact Regional Offices Research

### ISSUE THREAD

**Issue by jcklpe** [department-of-veterans-affairs/va.gov-cms#11454]
## Description

**Crafting Recommendations**

Recommendations are key outputs of the research process. They connect your findings back to the product roadmap(s) and shape the experience of future users. Depending on the type of research conducted, recommendations might be narrowly focused on improving a specific interface component of your team's product, or they might have broad implications for multiple parts of the VA.gov ecosystem. Work with your Design team, Product Manager, & Product Owner to generate, refine, and categorize recommendations. PMs and POs also play a key role in socializing recomendations to other teams.

**Documenting Findings**
- Building off the Topline Report, fill out the [Research Findings Template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/sharing-research/research-findings-template.md) and add it to your Research Folder
- Once your findings are fully written up, make sure they are linked to from the relevant research repository
- Veteran-facing research:[How to add reserach to Platform Repo](https://github.com/department-of-veterans-affairs/va.gov-research-repository/issues/70)
- Editor-facing research: [CMS Research Repository](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/cms/research)

## Acceptance Criteria
- [ ] Craft recommendations
- [ ] Document findings in Research Repo

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by davidmpickett** [comment]
12 interviews completed out of 13 scheduled (1 no show). All 7 MVPs RO were represented

**Comment by davidmpickett** [comment]
Closed the wrong ticket

**Comment by davidmpickett** [comment]
@JQuaggles I split out the Readout bits into a separate ticket: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12025

**Comment by davidmpickett** [comment]
Pretty good draft: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/regional-offices/research/2022-9-public-contact/research-findings.md

I scheduled a message to Dawn and Josh for next week to review while I'm out

**Comment by JQuaggles** [comment]
This is a great draft. 

I am curious about the "Beneficiaries" as appearing under services. I'd imagine that is more of a demographic that would also be looking to for many of the same services that are provided to Veterans.

**Comment by davidmpickett** [comment]
> This is a great draft.
> 
> I am curious about the "Beneficiaries" as appearing under services. I'd imagine that is more of a demographic that would also be looking to for many of the same services that are provided to Veterans.

The phrase "survivor's benefits" was used by multiple participants to describe a common service. This particular service crosses multiple benefits, tasks, and documents. I'm not saying that the beneficiary type is always a meaningful label for services, but there was at least one clear example where it was the most salient descriptor.

In the appendix, I listed any distinct groups of beneficiaries that came up anywhere in the interview.

**Comment by davidmpickett** [comment]
[vbapubliccontactresearch.pdf](https://github.com/department-of-veterans-affairs/va.gov-cms/files/10862367/vbapubliccontactresearch.pdf)
