### ISSUE TITLE
DSN: Synthesize VBA Public Contact Staff Research & Create Topline Report

### ISSUE THREAD

**Issue by jcklpe** [department-of-veterans-affairs/va.gov-cms#11453]
## Description

**Synthesis**
- Organize research notes in an [Affinity Diagram](https://miro.com/blog/create-affinity-diagrams/) to identify themes
- Rewatch session recordings to make additional notes & pull exact quotes
- Illustrate different paths participants took in prototypes (usability testing)
- Conduct statistical analysis
- Revisit the hypotheses from the Research Plan to see which can be confirmed

Topline Report:
- Use the [Topline Summary Template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/sharing-research/topline-summary-template.md) to summarize major findings
- Consult your Product Manager and Product Owner to see if a meeting should be scheduled to discuss the Topline Report
- Your PM and PO may have additional questions based on Topline Report that require additional synthesis
- This is just a summary of findings, no recommendations

Next Steps:
- The Research Lead should work with the Design Team & PM to create recommendations 
- The PM & PO should decide if a full research readout is required and who needs to be invited

## Acceptance Criteria
- [ ] Create Topline Report, share with PO, and update if needed 
- [ ] Schedule a full research readout (if PM & PO request)

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by davidmpickett** [comment]
Topline report: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/regional-offices/research/2022-9-public-contact/topline-summary.md

**Comment by davidmpickett** [comment]
Shared in Facilities Slack
