### ISSUE TITLE
Change colors of title text in CMS to Hex #212121

### ISSUE THREAD

**Issue by BlakeOrgan** [department-of-veterans-affairs/va.gov-cms#11455]
## Description
This is an implementation ticket for https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10071.

In the CMS on the view screen, there are read only blocks of text. Some blocks have titles as seen in "FAQs" and "Title" in the images below. These titles are currently `#757576` which does not pass WCAG 2.0 AA color contrast requirements against the light gray `#f1f1f1` background of the surrounding block or the red background `#f9dede` if the content is set to draft.

To ensure that this text is ADA compliant against all background colors that we use, the color of this text will need to be changed to  `#212121`.

![image](https://user-images.githubusercontent.com/113871419/199834490-87f9d219-8736-4566-be6d-9a7f1528b300.png)
![image](https://user-images.githubusercontent.com/113871419/199834523-02fbf3fd-5429-4eb7-a2c6-411641da9446.png)

## Acceptance Criteria
- [ ] Colors of title text are changed to `#212121`
- [ ] Requires design review
- [ ] Accessibility Review

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [x] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by laflannery** [comment]
Just for future/history reference:
- The current color `#757576` does currently pass WCAG 2.0 AA however we want all colors to pass WCAG 2.0 AAA. Therefore, even on white background these titles (they are actually field labels in the code) will be the new `#212121` color
