### ISSUE TITLE
Update Datadog Prod CMS Dashboard and move it to Terraform

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#11451]
## Description
We have a general dashboard for displaying CMS health metrics: https://vagov.ddog-gov.com/dashboard/vnk-g4s-fru

This dashboard is not in Terraform. Additionally, some of the widgets do not appear to be functioning, and others may not be useful.

We should review the dashboard, make any updates we feel are helpful, and put it into Terraform. This may involve splitting out the dashboard into multiple dashboards.

## Acceptance Criteria
- [ ] Discuss within Platform CMS what information would be useful on this dashboard (timebox: 2 hours)
- [ ] Discuss with Sitewide CMS eng and non-eng what information would be useful on the dashboard that is not there (timebox: 4 hours of work by assigned engineer maximum)
- [ ] Implement changes to main dashboard and/or split into multiple dashboards
- [ ] Implement the dashboard(s) in Terraform

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [x] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by EWashb** [comment]
With the current push to DataDog across the ecosystem, should we still consider Terraform or not?

**Comment by EWashb** [comment]
Do we still need to move to terraform?

**Comment by TheBoatyMcBoatFace** [comment]
TerraDog TerraDog TerraDog!

I'm honestly a little surprised that the VA doesn't have more GitHub comment spam, but don't worry @EWashb, I'm here doing my part.💪🫡

**Comment by ndouglas** [comment]
@EWashb Nope!
