### ISSUE TITLE
Discovery: Flag notifications architectural plan

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#11460]
ACs: 

- [ ] Workflow diagram. Feel free to use / add to the [existing Mural](https://app.mural.co/t/vagov6717/m/vagov6717/1666820558104/5b87095d4d16ad7c8e7825567bd84ff53be71724?sender=u252e7152800e3981889d1910) 
- [ ] Address how VA Form mgr email <>Form administration are associated in Drupal
- [ ] Summarize outcome of any discussions required with Platform around mail sending
- [ ] Cut implementation tickets for the work

**Comment by FranECross** [comment]
Closing iceboxed ticket.
