### ISSUE TITLE
Audit for White House VA Hotline on VA.gov pages

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-cms#11461]
### Describe your request

We recently learned that the White House VA hotline is being renamed to the VA hotline and it is being routed through MyVA 411. That means we need to remove any references to "White House VA hotline" and its phone number, [855-948-2311](tel:+18559482311), from VA.gov pages.

Our team removed it from the R&S article [Helpful VA phone numbers](https://www.va.gov/resources/helpful-va-phone-numbers/) but need to know if it shows up on any other VA.gov page.

<img width="318" alt="Screen Shot 2022-11-03 at 2 26 56 PM" src="https://user-images.githubusercontent.com/48728214/199804562-858fb806-a19f-4406-a8c6-c659ab6d277b.png">

### TIMING
This change went into effect immediately but this doesn't need to be high-priority for an upcoming sprint. 

### Your team name

Sitewide Content and IA

### Your product/team Slack channel

#sitewide-content-ia

### Your DEPO product owner

Beth Potts, Danielle Thierry

### Your Product Manager

Rlhecht, Randi Hecht

### Notify Sitewide Public Websites of this issue, and tag @Wes Rowe & @jilladams.

- [X] I acknowledge that I must notify `#sitewide-public-websites` in Slack after submitting this issue.

**Comment by jilladams** [comment]
Moving back to PW: https://dsva.slack.com/archives/CT4GZBM8F/p1671556206267679?thread_ts=1671485597.879709&cid=CT4GZBM8F

**Comment by wesrowe** [comment]
@jilladams, do we have a standard estimate for this content audit?

**Comment by jtmst** [comment]
I dont see this hard coded in either front end repo, would this be more of a cms audit?

**Comment by jilladams** [comment]
Using the new and very fancy CMS content audit tool, I think we can satisfy this audit: 
https://prod.cms.va.gov/admin/content/audit/search?search=White+House+VA+Hotline&title=&etype_op=or&etype=All&ms=All&published=All&section=

3 valid results from that list: 
1. https://prod.cms.va.gov/asheville-health-care/stories/1-800-myva411-800-698-2411-is-the-one-number-to-reach-va
2. https://prod.cms.va.gov/indiana-health-care/stories/1-800-myva411-800-698-2411-is-the-one-number-to-reach-va
3. https://prod.cms.va.gov/fayetteville-coastal-health-care/stories/1-800-myva411-800-698-2411-is-the-one-number-to-reach-va

@RLHecht apologies that this audit languished. Please let us know if you need any additional info here.

**Comment by RLHecht** [comment]
Thanks so much @jilladams. Since these results are all VAMC facilities, we would need another team to correct these. Would someone from the facilities team reach out to the editors of these VAMCs to update their pages?

**Comment by jilladams** [comment]
Great question - I'll check with @stefaniefgray / @TroyA6 how we get this moving.

**Comment by jilladams** [comment]
Confirmed - https://dsva.slack.com/archives/CDHBKAL9W/p1675962796497469

Helpdesk (@stefaniefgray / @TroyA6 ) will reach out to these editors. Adding User support label and reassigning!

**Comment by jilladams** [comment]
@stefaniefgray reminder here

**Comment by stefaniefgray** [comment]
Apologies for delay -- we've been completely slammed

- **VA Asheville** ([Link](https://prod.cms.va.gov/asheville-health-care/stories/1-800-myva411-800-698-2411-is-the-one-number-to-reach-va)) - Notified 3 editors in https://va-gov.atlassian.net/browse/VAHELP-5486
- **VA Indiana** ([Link](https://prod.cms.va.gov/indiana-health-care/stories/1-800-myva411-800-698-2411-is-the-one-number-to-reach-va)) - Notified 3 editors in https://va-gov.atlassian.net/browse/VAHELP-5487
- **VA Fayetteville Coastal health care** ([Link](https://prod.cms.va.gov/section/vha/vamc-facilities/va-fayetteville-coastal-health-care)) - Notified 1 editor in https://va-gov.atlassian.net/browse/VAHELP-5486

**Comment by stefaniefgray** [comment]
**Waiting on responses:**
- [ ] VA Asheville
- [ ] VA Fayetteville Coastal health care
- [ ] VA Indiana

@TroyA6 Please update if they reply while I'm out of office -- thank you!

**Comment by jilladams** [comment]
Thank you so much!

**Comment by stefaniefgray** [comment]
Number is removed from https://prod.cms.va.gov/indiana-health-care/stories/1-800-myva411-800-698-2411-is-the-one-number-to-reach-va

Waiting on Asheville and Fayetteville Coastal (same editor and ticket -- Corey Howard will likely need to edit both nodes): https://va-gov.atlassian.net/browse/VAHELP-5486

If he does not write back, @TroyA6 can follow up

**Comment by stefaniefgray** [comment]
@jilladams Editor ended up un-publishing page on Mar. 17th: https://prod.cms.va.gov/fayetteville-coastal-health-care/stories/1-800-myva411-800-698-2411-is-the-one-number-to-reach-va

Can ticket be marked as closed?

**Comment by jilladams** [comment]
Yep!
