### ISSUE TITLE
Outreach material filters should adapt dynamically to data and each other

### ISSUE THREAD

**Issue by jtmst** [department-of-veterans-affairs/va.gov-cms#11476]
## Description
Follow up to outreach topic filter work in #11153.  

The file type filter needs to be powered by the existing field_format values, and made to be aware of the topic filter so that there are no possible permutations that results in no files being shown.

**Product concern:** (Wes)
- Dynamically changing the options in the file-type filter could be confusing to the user
- Why do we think empty results are so bad?

## Acceptance Criteria
- [ ] The two filters are aware of each other and self restrict the other's limits. (example: If I select format = video, I should not see types in the filter that contain no videos. This would prevent from selecting a filter combination that has no results.
- [ ]  The file type filter options are powered by field_format (this is not a new field)

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by jilladams** [comment]
@jtmst any stab at an estimate here? From the language, I'm guessing this a Hard-ish Problem.

**Comment by wesrowe** [comment]
Outreach Materials has been deprecated in fall of 2022; VEO moving materials elsewhere.

**Comment by jilladams** [comment]
Note from discussion with Wes: Outreach Materials isn't yet fully deprecated / removed from the product, but we won't invest in it further / will eventually remove it.

**Comment by FranECross** [comment]
Closing as a no op; Outreach Materials deprecated in fall of 2022, as VEO moving the materials elsewhere.

**Comment by jilladams** [comment]
(@FranECross Closing this particular ticket is fine but FYI: Outreach Materials hasn't deprecated yet: https://www.va.gov/outreach-and-events/outreach-materials/. We still own / support it. Epic to deprecate is here: #14835 , still blocked on whatever other solution is happening for managing Outreach Materials. I haven't heard anything about it in ages.)
