### ISSUE TITLE
PM: Create Change Management plan for new Banner strategy

### ISSUE THREAD

**Issue by dsinla** [department-of-veterans-affairs/va.gov-cms#11489]
## Description
We want to limit VAMC System Banner Alerts to one per system, and impose a character limit.
The tech lift is relatively easy (and mostly already done as of 11/17/2022).
What are the steps to roll this out to editors, including but not limited to:

- Managing editors expectations, 
- Coordinate with VHADM
- Communicating, 
- Setting dates for when the switch is flipped, 
- Authoring supporting documentation, 
- Create RACI: VHADM, Support Desk, 

Related tickets:
#11434
#11141 

  
## Acceptance Criteria
- [ ] A Change Management strategy plan is reviewed and approved by PO

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by davidmpickett** [comment]
Reminder of the really thorough Change Management Runbook from Denise: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/facilities/change-management

**Comment by kmariepat-cityfriends** [comment]
Would like to have this implemented by July 1 2023

**Comment by kmariepat-cityfriends** [comment]
@jilladams this will roll into next sprint because according to the AC, the plan needs to additionally be approved by @davidconlon, a meeting is set for 5/15 to review this plan and this card will be able to be closed out then
