### ISSUE TITLE
CMS: Prevent first publish of a page where editors already have permission for a system.

### ISSUE THREAD

**Issue by dsinla** [department-of-veterans-affairs/va.gov-cms#11481]
## Description
When a new Facility is created, the current process does not grant permissions to an editor to publish the page without some approval first. Once approve, the editor's permissions are promoted to allow publishing.
This safeguard fails when an editor already has permissions to a system, since permissions for a system span all facilities in that system.
(Is this just VAMC?  And Vet Centers have Regions, VBA will have Districts)

## Acceptance Criteria
- [ ] Testable_Outcome_X
- [ ] Testable_Outcome_Y
- [ ] Testable_Outcome_Z
- [ ] Requires design review

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by stefaniefgray** [comment]
@swirtSJW @davidmpickett Is there a newer/duplicate/alternate version of this ticket with regards to blocking editors from prematurely publishing new facility homepages in the CMS? 

Would like to close in favor of other ticket or consolidate -- see linked tickets above as well

cc: @JayDarnell @omahane

**Comment by davidmpickett** [comment]
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13670
