### ISSUE TITLE
Current Covid-19 safety guidelines not working on php8.1

### ISSUE THREAD

**Issue by edmund-dunn** [department-of-veterans-affairs/va.gov-cms#11484]
## Description
The Guidelines section is not appearing as expected because the ID `covid-safety-guidelines-status-text` is not being rendered. We spotted this because of a console error: 
![CleanShot 2022-11-07 at 08.07.53.png](https://images.zenhubusercontent.com/62e017d215adbc33b1310f7b/0d66e877-c880-4d9b-8dc2-967f1469225b)

![CleanShot 2022-11-04 at 12.12.46.png](https://images.zenhubusercontent.com/62e017d215adbc33b1310f7b/046221c4-8fa2-4960-b52d-06787581d38e)![CleanShot 2022-11-07 at 08.07.18.png](https://images.zenhubusercontent.com/62e017d215adbc33b1310f7b/a059c98c-5275-4220-a6ba-f76ccd74dd0a)

## Acceptance Criteria
- [ ] Fix so that the ID `covid-safety-guidelines-status-text` is rendered on php8.1.

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by dsinla** [comment]
EOL for PHP 7.4 - moving to 8.1 - is Nov 28th.
Likely we can address this without waiting for the larger COVID status re-strategy.

**Comment by EWashb** [comment]
Talk to @edmund-dunn for context.

**Comment by omahane** [comment]
This is where the information was first added:
https://github.com/department-of-veterans-affairs/va.gov-cms/pull/9244
As soon as I have an environment, I was going to look at this.

**Comment by omahane** [comment]
This is also happening on my local dev environment, which is using php 7.4.30. 

It is not happening in a PR I recently built or in prod, though.

**Comment by omahane** [comment]
This not happening on local environments of @swirtSJW or @edmund-dunn, which, of course, makes it even stranger.

**Comment by omahane** [comment]
I'm looking into the render pipeline steps to see where I can set a breakpoint that will show me where the tooltip is not showing up when it should.
https://www.drupal.org/docs/8/api/render-api/the-drupal-8-render-pipeline

**Comment by swirtSJW** [comment]
I think since we can't trust the behavior on your local with 7.4 it makes it hard to say with certainty what we are fixing for php8.   I may have to take this on with my system but will likely not have bandwidth until Friday after demo.

**Comment by swirtSJW** [comment]
Loading php 8.1 on my system
![image](https://user-images.githubusercontent.com/5752113/205745417-a928b262-4659-4869-888e-360c25256f77.png)

This seems to be working fine.
![image](https://user-images.githubusercontent.com/5752113/205745547-79de1db2-300c-463c-b6a0-b11c08ae0938.png)


Now I have to figure out why it was failing on the tugboat demo

**Comment by swirtSJW** [comment]
Dirty fix as a fallback.  Not recommended.
![image](https://user-images.githubusercontent.com/5752113/205759477-3547a307-fa1b-47db-b766-c3ee00ae5dcb.png)

I still have not determined why this is failing on one env but not another.  This is way too bizarre for my taste.  I'm still looking into it.

**Comment by swirtSJW** [comment]
I think what we are seeing as a failed behavior is actually the outwardly desired from Drupal.  https://www.drupal.org/project/field_group/issues/3069365  
Of course that is not the disired behaviour from our use case.  So we will want to override it.   I still have not determined why this has ever worked and only fails sometimes.

**Comment by swirtSJW** [comment]
This was not an error related to php8  
It occurred on the php 8 branches for the following reason
1. ) This commit in the php8 branch removed a patch that had been merged upstream, but did not update the module https://github.com/department-of-veterans-affairs/va.gov-cms/commit/e3357d19e82aead9ed654169e8bb866bf84581f3
2) The field_group module since the day it was added to the repo in Jan 2019 had been mistakenly pinned to a commit of the dev branch, so this module never bumped to any tagged releases via human or dependabot actions.

The associated PR will free it from the pin, so it can be updated as new releases are made.
