### ISSUE TITLE
SPIKE: Plan to move footer language selector menu into Drupal

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#11492]
#11482 implements the footer navigation using a Drupal menu.

"Language Assistance" Links section of the footer menu involves a React component that has more going on than what it might appear on the surface. The links are generated from some configuration around supported languages, and, additionally, clicks on these links have effects that seem to extend outside the footer alone.

In order to move these links to Drupal / footer, we need to understand what the React component is achieving, and how to re-create that behavior via Drupal menu links.

**Comment by FranECross** [comment]
Closing as a no op.
