### ISSUE TITLE
Content Audit: Space Force Content Addition

### ISSUE THREAD

**Issue by EWashb** [department-of-veterans-affairs/va.gov-cms#11495]
Content audits can be performed by searching the codebase and compiled site for specific terms you're using an audit tool within drupal. 
Please provide any context for the audit, any related terms or alternate spellings, or and related components that could return content you are interested in. Please see the [collab cycle documentation](https://va-gov.atlassian.net/l/cp/U0DfKLfs) for more information.

## 1. Please provide any context around your audit

Space Force needs to be mentioned where any other military branches are mentioned throughout the website. This will also need to include rich-text fields. 

  
## 2. What are the terms you are searching for within the CMS? Are there alternate spellings?

Any terms including: military branches, Army, Navy, Marines, Air Force, etc. 

## 3. Are there components, elements or content types related to your search?

Rich-field fields (aka WYSIWYG) 

## 4. Does a corresponding audit need to be run on the Veteran-facing website?  
  - [ ] Yes 
  - [x] No

## 5. When do you need the audit to be completed

Sprint 71

## CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [x] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by EWashb** [comment]
This will definitely be a stretch for sprint 71.

**Comment by jilladams** [comment]
Hi - reminder this happened awhile ago: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9085

**Comment by EWashb** [comment]
@edmund-dunn you might want to take a look at #9085. I didn't realize we had a previous audit.

**Comment by EWashb** [comment]
We have conducted an initial review of the new search. Will share with PO during Sitewide CMS sync on 11/22

**Comment by EWashb** [comment]
This will be taken care of as part of #11706. Once that search is implemented then the content team will be able to do a self-service audit in the CMS

**Comment by EWashb** [comment]
Sitewide CMS has created a new content audit tool that takes care of this request for the Sitewide Content team
