### ISSUE TITLE
Design: Create UX helptext for using multi-select

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#11490]
Epic #11131 has added a new multi-select taxonomy field to Publications content type. Multi-select is a new paradigm and we don't have guidance for editors for how to use multi-select lists right now. 

We'd like CMS UX input / content for help text to add to this field.

https://prod.cms.va.gov/node/add/outreach_asset
There are now 2 Related Benefits fields on this form: a single select (old) and a multi-select (new). The multi-select will stay, and is the field that needs guidance. 
![Screen Shot 2022-11-07 at 11 32 40 AM](https://user-images.githubusercontent.com/85581471/200398333-208b75b7-489f-49a1-8cd2-5f4faa85b7bb.png)

## Additional materials
* KB article: https://prod.cms.va.gov/how-to-create-outreach-materials-publications

**Comment by davidmpickett** [comment]
@jilladams @wesrowe  I'm catching up on threads from when I was out and this surfaced. 

it seems like there are other problems to deal with before we get back to this point, but it would be good to proactively plan a meeting to bring Design up to speed on this problem space. I think the only piece of this I've previously seen is a list of Taxonomy terms.

**Comment by jilladams** [comment]
https://dsva.slack.com/archives/CT4GZBM8F/p1667849814426629

**Comment by jilladams** [comment]
@davidmpickett saw your comment after my other changes on this ticket (to move to stretch / assign to blake based on the above slack thread, fyi @EWashb @dawnpruitt). 

We can definitely chat. The tl;dr is: this is the first multi-select list available in the CMS as far as we know. So Dave flagged that fact (which we didn't realize til late in the implementation), thusly: this ticket. I'm not sure who'd need to be involved in a bigger discussion -- any recommendations from the peanut gallery?

**Comment by davidmpickett** [comment]
Okay, rereading the Slack thread it seems like @EWashb already has a good understanding of the scenarios this affects, so maybe her + Blake have enough context to handle this (if not the capacity). 

It also looks like the ticket that this is blocking is just a ticket to implement this guidance, so it's not like this is blocking any vital work.

**Comment by wesrowe** [comment]
The only thing I would add is: this is a terrible and unintuitive UX that Drupal has given us. To multi-select, you have to hold down Ctrl (on a mac anyway). So even a "skilled" user like we expect on this product may have trouble without help text.

**Comment by BlakeOrgan** [comment]
Agreed. This definitely needs more than just help text. UI updates would be needed before it would be intuitive that you are able to select multiple items. I've got ideas on how to update that, but I would just need to know when to work on this among other priorities. @EWashb or @dawnpruitt would be able to give better guidance on that.

**Comment by BlakeOrgan** [comment]
@productmike What are your thoughts on closing this ticket out in favor of ticket #13500?

**Comment by productmike** [comment]
@BlakeOrgan agree. Closing this in favor of #13500
