### ISSUE TITLE
Add last touched by a human datetime field to all content types

### ISSUE THREAD

**Issue by edmund-dunn** [department-of-veterans-affairs/va.gov-cms#11504]
## Description
We need to add a new datetime field to all content types. It will be automagically populated by functionality attached to the save button. This will allow us to track the last time a human reviewed/touched a node. 

## Acceptance Criteria
- [ ] Add datetime field to all content types. The field will be disabled but visible on the form and view in the CMS. 
- [ ] Update the Save button functionality to automatically populate the field with the date and time the node was saved. 

field to be called: Last Saved by an Editor

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [x] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by laflannery** [comment]
Duplicate Erika said to close
