### ISSUE TITLE
SPIKE: Review previous notes & create punchlist of header considerations for future iteration

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#11507]
## Description
We need a deep dive analysis of the header / footer, to start thinking about next iteration. 

What to consider: 
* Header megamenu
* Footer 
* Contexts:
  * Desktop 
  * Mobile
  * Injected into TeamSite
* User experience angles:
  * 508
  * Performance
  * Use of React

## Existing documentation to review
 * Header documentation: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/public-websites/header
 * Injection documentation:
   * https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/public-websites#header--footer-injection
   * [Proxy-rewrite README](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/proxy-rewrite/README.md) with implementation & testing details

## Acceptance Criteria

- [ ] Existing documentation is updated for accuracy with any findings
- [ ] Write up summary of findings / proposed updates in this ticket 
- [ ] Schedule meeting with Wes, Jill, LauraF, RyanK, design to review. Invite any other folks you consulted with during the research work, as interested parties.

**Comment by jilladams** [comment]
I wrote this ticket up based on a sync with Dave / Wes, re: opting to punt #10698 for now, and wrap it into a bigger iteration. BUT: this feels giant and gnarly, and maybe impractical to expect a single engineer to determine a comprehensive scope of header issues / problems / opportunities to optimize in a single sprint issue, across all these dimensions.

Assigning to @wesrowe as a start, to refine and we can think through: how can we practically chew on this and arrive at an assessment / plan.

**Comment by jilladams** [comment]
Further: we're now undertaking the Federal header project, so I'm not sure this ticket should stay alive at all, since that's definitively our next iteration. @aklausmeier @laflannery @thejordanwood do you all concur?

**Comment by aklausmeier** [comment]
@jilladams agree and FYA megamenu is out of scope for Federal Header/Footer work so if there are any known 508 issues to address we can work with @laflannery to spin up accessibility tickets
