### ISSUE TITLE
Update outdated content report with human-edited field 

### ISSUE THREAD

**Issue by EWashb** [department-of-veterans-affairs/va.gov-cms#11506]
## Description

After the completion of #11497 and #11505, we will need to update the outdated content report to reflect the new field. The outdated content report should only account for the last human-edited content. 

## Acceptance Criteria
- [ ] refactor outdated content report to only use the last-human edited date
- [ ] refactor CSV export of outdated content to only use the last-human edited date
- [ ] update the existing "1 year outdated" filter to say "All outdated content"

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [x] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by edmund-dunn** [comment]
Had to add patch #18 from this issue https://www.drupal.org/project/views_data_export/issues/3189135#comment-14818885 to fix csv downloads in chrome.

**Comment by swirtSJW** [comment]
Reopened because the code was reverted https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11924
