### ISSUE TITLE
Update email newsletter form with form action

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#11511]
Form action = `action="https://public.govdelivery.com/accounts/USVACHOOSE/subscribers/qualify"`
Based on implementation from https://www.choose.va.gov/. 

ACs: 

- [ ] verify successful submission (TBD how from @mmiddaugh )

**Comment by apisandipas** [comment]
* The Design System doesn't have an explicit email field
* The [Text Input](https://design.va.gov/storybook/?path=/docs/components-va-text-input--default) does accept 'type' and 'inputmode' attributes, which can be set to 'email' and provides with own validation UI. 
* Looking at the [forthcoming design iteration](https://www.sketch.com/s/3aa40506-4be2-46cc-876b-93f1a9f3a857/p/EAD305BC-3082-4F81-ADEC-C2486F7B6BEF/canvas), it seems that may have been taken into account and the UI now matches the standard form input as the Design System provides.

**Comment by jilladams** [comment]
Closing as dupe of #11389, and pasted over any special sauce from here into there.
