### ISSUE TITLE
[Search] DRY up SearchDropdownComponent typeahead handler

### ISSUE THREAD

**Issue by ryguyk** [department-of-veterans-affairs/va.gov-cms#11513]
## Status
* **[2024-09-13]** DST bug has shipped, now unblocked
* **[2024-08-01]** Blocked by DST bug: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3117
- **[2024-07-24]** Blocking DST ticket is now closed
- **[2024-05-30]** Still awaiting completion of ticket noted below
- **[2024-05-21]** Still awaiting completion of ticket noted below
- **[2024-05-15]** Still awaiting completion of ticket noted below
- **[2024-05-07]** Typehead was still having issues; Micah created https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2795 to fix

## Description
`SearchDropdownComponent` currently [accepts a function `fetchSuggestions` as a property](https://github.com/department-of-veterans-affairs/vets-website/blob/029faee6b4bcaffb97626167ac5e396b8494cae2/src/applications/search/components/SearchDropdown/SearchDropdownComponent.js#L91). This component is currently called in three places, each of which create a separate instance of a function to pass to this component:
- [src/applications/search/containers/SearchApp.jsx](https://github.com/department-of-veterans-affairs/vets-website/blob/029faee6b4bcaffb97626167ac5e396b8494cae2/src/applications/search/containers/SearchApp.jsx#L377)
- [src/platform/site-wide/header/components/Search/index.js](https://github.com/department-of-veterans-affairs/vets-website/blob/029faee6b4bcaffb97626167ac5e396b8494cae2/src/platform/site-wide/header/components/Search/index.js#L172)
- [src/platform/site-wide/user-nav/components/SearchMenu.jsx](https://github.com/department-of-veterans-affairs/vets-website/blob/029faee6b4bcaffb97626167ac5e396b8494cae2/src/platform/site-wide/user-nav/components/SearchMenu.jsx#L276)

It seems initially confusing why this logic is being passed in rather than defined inside the component, as this component is only used for site-wide search. It's conceivable, though, that this component might be used to search something else, and that the current architecture makes it flexible enough to do so.

Regardless, we need to DRY this up. The same code is repeated three times to be passed into the component in the three places indicated above. We have two options:
1. If it seems reasonable to keep this design whereby this component accepts the functionality as a property, we should move that functionality to a reusable function that can be imported in each of the three places noted above. 
2. Otherwise, we should move the functionality inside `SearchDropdownComponent`. 
  - We could define it as a default property that could be overridden.
  - We could remove it as a property and simply make this component more specific to site-wide search.

## Acceptance Criteria
- [ ] Code to fetch suggestions is either moved _into_ `SearchDropdownComponent`, or a reusable function is created to be passed in each case where it's currently being used.

**Comment by randimays** [comment]
Pulling in as stretch as it is a great companion ticket to #17176

**Comment by randimays** [comment]
Typeahead web component still has issues. I've reported to DST. Moving this back to Blocked.

Slack thread: https://dsva.slack.com/archives/C01DBGX4P45/p1714663661141389?thread_ts=1714054912.852109&cid=C01DBGX4P45

**Comment by randimays** [comment]
@FranECross @jilladams This ticket goes with https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17176; should we pull it into the current sprint?

**Comment by jilladams** [comment]
Seems like you prob have capacity, dST blocker is resolved -- I have no objections! (And defer to Fran)

**Comment by FranECross** [comment]
@randimays Sounds good, thanks for thinking of it!

**Comment by randimays** [comment]
I discovered a defect in the `va-search-input` web component that already exists in production in Find Forms. Slack thread: https://dsva.slack.com/archives/C01DBGX4P45/p1722438937787339

This defect is blocking the completion of this ticket unfortunately. Hopefully we can get some eyes on it soon: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3117

**Comment by randimays** [comment]
The [DST defect](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3117) has been resolved and a new release was put out. When possible, we can come back to this and see if it's fixed.

**Comment by jilladams** [comment]
Unblocked, moved to ready, added a note to ticket body.
