### ISSUE TITLE
SPIKE: Email sub field email validation

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#11512]
Email subscription form should ideally validate email structure before allowing submit, e.g. `@` and `.com` are present

## ACs

- [x] Check design system for options
- [x] Check HTML5 form validation / how far it extends re: browser support
- [x] Document how we could achieve this, with level of effort
- [x] Update #11511 with any notes

**Comment by jilladams** [comment]
@apisandipas closeable?

**Comment by apisandipas** [comment]
Yes
