### ISSUE TITLE
Table audit published column issues

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#11524]
## Describe the defect
On our new table audit View, the published column does not seem to reflect the expected results.

- issue A : Not descriptive of what "published" means.  Is this the parent node for the table paragraph?
- issued B: No unpublished nodes seem to be surfaced  Or if they are, column sort does now work because regardless of which way the sort it, unpublished never exist at the top of the list.
- Issue C:  Can't tell if sort is working. due to issue B

## To Reproduce
1. Go to '/admin/content/audit/tables'
2. Click on the sort header for the published column.  No never surfaces.
![image](https://user-images.githubusercontent.com/5752113/200895476-8783ef6c-767a-43b6-9f8b-3e13f4c9e1b4.png)

![image](https://user-images.githubusercontent.com/5752113/200895554-0d7c958e-4473-4fd9-9fae-12ea23ac9440.png)

## AC / Expected behavior
When a node is unpublished, the view should show the paragraph as unpublished.

## Screenshots
.

 ## Additional context
Add any other context about the problem here. Reach out to the Product Managers to determine if it should be escalated as critical (prevents users from accomplishing their work with no known workaround and needs to be addressed within 2 business days).

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Defect")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS workstream (orange) (not needed for bug tickets)
- [ ] CMS-supported product (black)

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by swirtSJW** [comment]
paragraph "publish" behavior is not parallel with published nodes.  It is not quite the same thing at all when workbench moderation is enabled.
https://www.drupal.org/project/paragraphs/issues/2949412

**Comment by laflannery** [comment]
I was going through the table audit and I found a real life example of this that I just wanted to document so we can be sure this is working properly later:

- Bedford Health Care - [Confined Space Information - BK-03-B004A-PRCS page](https://www.va.gov/bedford-health-care/work-with-us/doing-business-with-us/confined-space-information-bk-03-b004a-prcs) is archived, but the :
- This is [archived in the CMS](https://prod.cms.va.gov/bedford-health-care/work-with-us/doing-business-with-us/confined-space-information-bk-03-b004a-prcs)
- But the table is being displayed as [published in the table audit](https://prod.cms.va.gov/admin/content/audit/tables?page=77) (ID 113334)

**Comment by swirtSJW** [comment]
This problem is likely bigger than this ticket.  We ,ay want to just remove the published column and filter from the View as  it is meaningless and offers no functionality.

**Comment by laflannery** [comment]
@EWashb and @edmund-dunn I believe we handled this already with possibly some other table audit defect tickets.  Can you confirm if we can close this?

**Comment by EWashb** [comment]
Yes, this seems to be the same as the work @edmund-dunn did to identify orphann
