### ISSUE TITLE
Determine an approach for CMS every-minute tasks run on prod

### ISSUE THREAD

**Issue by cmaeng** [department-of-veterans-affairs/va.gov-cms#11544]
## Description
As part of the migration off of BRD, the first set of tasks we want to move are runtime tasks through the Ansible playbook. This is based on the spike done in https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9765

http://jenkins.vfs.va.gov/job/cms/job/cms-every-minute-prod/
Jenkins initiates the execution of the program (binary file) task on a CMS instance. Task takes a configuration file and a task name as a parameter. The configuration file defines in YAML what commands a named task should execute.

Every minute send metrics to Datadog and Process content release queues:

va/background/periodic/send_datadog_metrics
va/background/periodic/content_release_queues

`Build Trigger (Every 1 minute):`
`TZ=America/New_York`

## Acceptance Criteria
- [ ] a path forward is determined on how to handle this runtime task

**Comment by cmaeng** [comment]
@timcosgrove why isn't there a cron job on our servers that does this?

@ElijahLynn : everything was in this one container; eventual consistency, who's the leader that's going to be running the cron? this makes it easier and observable. architected to be able to modify individual tasks (declaration in the application repo). Argo workflows (?) could be a consideration if we think we're going to use Argo. Matt L would know.

@timcosgrove in GHA this could be bad. curious how other groups are doing on the minute tasks and enabling observability. going to make visibility for other jobs in the CMS repo difficult.

@olivereri we'll need to get creative in GHA because it won't allow sub-5 minute stuff. @ndouglas might have ideas on how to set up.

could we log the entire output?

this task is currently in the task periodic file.

**Comment by cmaeng** [comment]
more time is needed to think through an approach for this.

**Comment by TheBoatyMcBoatFace** [comment]
May no be applicable with projected post-jenkins plan. Will re-open if it becomes applicable #11554
