### ISSUE TITLE
CMS periodic tasks run on prod

### ISSUE THREAD

**Issue by cmaeng** [department-of-veterans-affairs/va.gov-cms#11545]
## Description
As part of the migration off of BRD, the first set of tasks we want to move are runtime tasks. This is based on the spike done in https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9765

http://jenkins.vfs.va.gov/job/cms/job/cms-periodic-prod/
Jenkins initiates the execution of the program (binary file) task on a CMS instance. Task takes a configuration file and a task name as a parameter. The configuration file defines in YAML what commands a named task should execute.

va/background/periodic/migrate/facility_status
va/background/periodic/check_content_release_stale
va/background/periodic/check_scheduled_content_release
va/background/periodic/cron

`Build Trigger (Every 15 minutes):`
`TZ=America/New_York`
`H/15 * * * *`

## Acceptance Criteria
- [ ] the tasks identified above are migrated from Jenkins to GHA successfully

**Comment by TheBoatyMcBoatFace** [comment]
May no be applicable with projected post-jenkins plan. Will re-open if it becomes applicable #11554
