### ISSUE TITLE
Backup EFS sites/default/files/ on prod.cms.va.gov

### ISSUE THREAD

**Issue by cmaeng** [department-of-veterans-affairs/va.gov-cms#11549]
## Description
As part of the migration off of BRD, the first set of tasks we want to move are runtime tasks. This is based on the spike done in https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9765

http://jenkins.vfs.va.gov/job/cms/job/cms-efs-backup-prod/
Jenkins initiates the execution of Ansible plays. The plays reference roles that have tasks to be carried out on the target device.

With the completion of the S3 Assets Files Bucket epic this will be obsolete. Elastic File System will no longer be necessary.

The EFS Backup play targets the local Jenkins server to run the role that has several tasks and an inline bash script.
Tasks:

- Prepares a temporary directory
- Mounts EFS Volume
- Unmount EFS Volume
- Bash Script:
- Archives/Compresses with gzip all asset files
- Uploads archive to S3
- Cleans up temp files

## Acceptance Criteria
- [ ] the tasks identified above are mirgrated from Jenkins to GHA successfully

**Comment by TheBoatyMcBoatFace** [comment]
May no be applicable with projected post-jenkins plan. Will re-open if it becomes applicable #11554
