### ISSUE TITLE
Backup database on prod.cms.va.gov

### ISSUE THREAD

**Issue by cmaeng** [department-of-veterans-affairs/va.gov-cms#11548]
## Description
As part of the migration off of BRD, the first set of tasks we want to move are runtime tasks. This is based on the spike done in https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9765

http://jenkins.vfs.va.gov/job/cms/job/cms-db-backup-prod/
Jenkins initiates the execution of Ansible plays. The plays reference roles that have tasks to be carried out on the target device.

The Database Backup play targets the local Jenkins server to run the role that has an inline bash script. The bash script:

- connects to the Prod RDS server
- mysqldumps the database
- Compress/Archives with gzip
- Uploads archive to S3
- Cleans up temp files
- Build Trigger:
- http://jenkins.vfs.va.gov/job/cms/job/cms-full-pipeline/

## Acceptance Criteria
- [ ] the tasks identified above are migrated from Jenkins to GHA successfully

**Comment by TheBoatyMcBoatFace** [comment]
May no be applicable with projected post-jenkins plan. Will re-open if it becomes applicable #11554
