### ISSUE TITLE
PHP 8.1 Testing: Empty related office dropdown

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#11555]
## Describe the defect
I am not sure if this is related to the PHP upgrade or not.

On VAMC Detail Pages, the dropdown for "Related office or health care system" has no available options beings populated in the select box. Normally, this shows all available VAMCs.

## To Reproduce
1. Go to https://vacms-10870-upgrade-to-php81-rh7pjindaxvyxvr35alvilr3mqpgaoko.ci.cms.va.gov/node/9383/edit
2. On the right side bar, under Section Settings there is a dropdown for "Related office or health care system"
3. Notice that the dropdown is empty and there are no available options

## AC / Expected behavior

- [ ] Investigate/Resolve error

## Screenshots
![image](https://user-images.githubusercontent.com/106678594/201202065-18637247-53e5-427c-9449-8b2c0f9f1314.png)

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [x] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by edmund-dunn** [comment]
This doesn't occur on my local or production. Appears to not be an issue.
![CleanShot 2023-01-03 at 13 57 09](https://user-images.githubusercontent.com/109987005/210448101-4da4b23c-80ee-4b7a-99c1-50f18928a2a1.jpg)
