### ISSUE TITLE
CMS: Lovell Federal TRICARE Operating Status page issues

### ISSUE THREAD

**Issue by dsinla** [department-of-veterans-affairs/va.gov-cms#11557]
## Description
In the demo environment, on the [Lovell Federal Tricare system page ](https://web-liqqgmzl7tsyfbwyulbkuborufuuttav.demo.cms.va.gov/lovell-federal-tricare-health-care/), in the Updates Block, the link to the Operating status points to the VA side when it should point to Lovell.

![image](https://user-images.githubusercontent.com/62269210/201233184-0ab5f4a5-0d97-464e-8a1b-72d3bb0c09bf.png)

Originally documented in https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11375

Also, right now the operating status page is assigned to the Lovell Federal health care section, so it should be duplicated to both sides. The VA page exists in the demo env: https://web-liqqgmzl7tsyfbwyulbkuborufuuttav.demo.cms.va.gov/lovell-federal-va-health-care/operating-status/
The TRICARE page does not: https://web-liqqgmzl7tsyfbwyulbkuborufuuttav.demo.cms.va.gov/lovell-federal-tricare-health-care/operating-status

Relates to #11848 

## Acceptance Criteria
- [ ] Link to Operating Status in the Updates Block on the TRICARE page points to va.gov/lovell-federal-**tricare**-health-care/operating-status/
- [x] An Operating Status page is published for both TRICARE and VA 

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by dsinla** [comment]
Poking around a bit further, looks like editors can enter an Operating Status and Link text in the System page, but it's blank in the demo env for Lovell TRICARE system.  Looking at a few other systems in production, it looks like we explictly denote the Operating Status page.

![image](https://user-images.githubusercontent.com/62269210/201234592-8f4fc309-0a65-4b85-a045-8df4a1700542.png)

Right now the operating status page is assigned to the Lovell Federal health care section, so it should be duplicated to both sides. 

The VA page exists in the demo env: https://web-liqqgmzl7tsyfbwyulbkuborufuuttav.demo.cms.va.gov/lovell-federal-va-health-care/operating-status/
The TRICARE page does not: https://web-liqqgmzl7tsyfbwyulbkuborufuuttav.demo.cms.va.gov/lovell-federal-tricare-health-care/operating-status

Updating the ticket to address looking into why the page is not published to both VA and TRICARE.

**Comment by swirtSJW** [comment]
> Right now the operating status page is assigned to the Lovell Federal health care section, so it should be duplicated to both sides.

That is a mistake.  Operating status pages reference specific facilities.  Since the facilities are split between VA and TRICARE, there is no way we can have one page that spans both.   The existing one should be set to section Lovell - VA and a new one needs to be created for Lovell - TRICARE.

**Comment by dsinla** [comment]
Thanks @swirtSJW!

I set the existing page that was **Lovell Federal health care** to **Lovell - VA**
https://prod.cms.va.gov/lovell-federal-tricare-health-care/operating-status

I created a new VAMC System Operating Status. assigned it **Lovell - TRICARE**
https://prod.cms.va.gov/lovell-federal-tricare-health-care/operating-status

I published nothing, saved as DRAFT.

Upon creating of the new Oper Sys page, I could select the section
![image](https://user-images.githubusercontent.com/62269210/202343833-39154a8c-820a-4a27-af04-beccb6238615.png)

So I chose Lovell Federal TRICARE

I can't seem to edit the title on the (now previously) Lovell Federal health care page, which I changed to Lovell - VA,

Not sure about the Menu Link Title and Parent Link settings - I could use some education there - I just set the TRICARE page to what was set on the original Lovell Federal health care page
![image](https://user-images.githubusercontent.com/62269210/202343438-2a8b104f-dc86-4991-b998-d3363ed2b9ef.png)

**Comment by dsinla** [comment]
It was determined that this is an edge case specific to Operating Status pages.
I deleted the original page - which couldn't have its title updated.
I created a new page which displays the correct title:
**Operating status | Lovell Federal VA health care**
https://prod.cms.va.gov/lovell-federal-va-health-care/operating-status

**Comment by EWashb** [comment]
Validate that this was fixed please @omahane

**Comment by dawnpruitt** [comment]
@omahane fair to move this to In Progress? :)

**Comment by omahane** [comment]
@maxx1128 Do know what this js error is about on the VA and TRICARE Operating Status pages:

> [Error] Warning: Encountered two children with the same key, `10`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.
ul
div
div
div
Footer@https://dev-va-gov-assets.s3-us-gov-west-1.amazonaws.com/generated/static-pages.entry.js:31550:20
Connect(Footer)@https://dev-va-gov-assets.s3-us-gov-west-1.amazonaws.com/generated/static-pages.entry.js:99644:68
Provider@https://dev-va-gov-assets.s3-us-gov-west-1.amazonaws.com/generated/static-pages.entry.js:99356:19
	(anonymous function) (static-pages.entry.js:9438)
	printWarning (static-pages.entry.js:69549)
	error (static-pages.entry.js:69525)
	warnOnInvalidKey (static-pages.entry.js:83102)
	reconcileChildrenArray (static-pages.entry.js:83133)
	reconcileChildren (static-pages.entry.js:86472)
	updateHostComponent (static-pages.entry.js:87114)
	beginWork$1 (static-pages.entry.js:93417)
	performUnitOfWork (static-pages.entry.js:92256)
	workLoopSync (static-pages.entry.js:92184)
	renderRootSync (static-pages.entry.js:92147)
	performSyncWorkOnRoot (static-pages.entry.js:91770)
	scheduleUpdateOnFiber (static-pages.entry.js:91358)
	updateContainer (static-pages.entry.js:94959)
	(anonymous function) (static-pages.entry.js:95498)
	unbatchedUpdates (static-pages.entry.js:91908)
	legacyRenderSubtreeIntoContainer (static-pages.entry.js:95497)
	startReactApp (static-pages.entry.js:32088)
	startVAFooter (static-pages.entry.js:31947)
	startSitewideComponents (static-pages.entry.js:27767)
	(anonymous function) (static-pages.entry.js:115968)
	(anonymous function) (static-pages.entry.js:7116)
	withScope (static-pages.entry.js:8581)
	(anonymous function) (static-pages.entry.js:115966)
	(anonymous function) (static-pages.entry.js:116060)
	Global Code (static-pages.entry.js:116061)

I'm seeing it in multiple browsers. It doesn't really block this ticket, but I don't know if it's something we've encountered before, either.

<img width="1718" alt="Screen Shot 2022-12-12 at 9 49 02 AM" src="https://user-images.githubusercontent.com/766573/207090682-a49181d7-9169-41a7-ba1e-5ec93eda0d59.png">

**Comment by maxx1128** [comment]
@omahane I'm not sure, but my best guess is there are alert components with the same key and each one needs to be unique. It could be the key values are determined by the type of alert instead of a kind of randomly generated number.

**Comment by JayDarnell** [comment]
@dawnpruitt @maxx1128 this doesn't look like a CMS ticket to me. This appears to be a front end issue. The URL currently being referenced for the Operating Status refers to the old Operating Status node for the Lovell umbrella system. This Operating Status page was deleted. The test environment currently has old data in that the operating status pages have not been explicitly set for the Lovell VA and Lovell TRICARE systems. The old Lovell Federal system is also still published in this environment. 

I think we need to rebuild this environment once https://github.com/department-of-veterans-affairs/content-build/pull/1399 has been merged with a refresh of data from prod and then see if this link is still broken. If it is I believe it will require a front end fix.

**Comment by JayDarnell** [comment]
This issue has been resolved. As suspected, once the front end was rebuilt with the appropriate CMS data these links are working fine.

- The original Lovell Federal health care system is unpublished
- The original Lovell Federal health care system operating status node was deleted
- A new system operating status page was added for Lovell - VA and another for Lovell - TRICARE

![Screenshot 2022-12-14 at 2 06 15 PM](https://user-images.githubusercontent.com/21045418/207690323-bd5a4506-496a-4e68-8e5f-a7480aa627db.png)

![Screenshot 2022-12-14 at 2 06 39 PM](https://user-images.githubusercontent.com/21045418/207690379-40cea629-4b0a-41af-9007-7dd4e2bd97a1.png)
