### ISSUE TITLE
PHP 8.1 Testing: Errors found on Benefits Hub Landing Page

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#11556]
## Describe the defect
Errors found on Benefits Hub Landing Page Edit screen when testing PHP 8.1:

> Deprecated function: parse_url(): Passing null to parameter #1 ($url) of type string is deprecated in Drupal\linkit\Plugin\Field\FieldWidget\LinkitWidget->formElement() (line 40 of modules/contrib/linkit/src/Plugin/Field/FieldWidget/LinkitWidget.php).

> Deprecated function: substr(): Passing null to parameter #1 ($string) of type string is deprecated in Drupal\linkit\Plugin\Field\FieldWidget\LinkitWidget->formElement() (line 41 of modules/contrib/linkit/src/Plugin/Field/FieldWidget/LinkitWidget.php).

## To Reproduce
1. Go to https://vacms-10870-upgrade-to-php81-rh7pjindaxvyxvr35alvilr3mqpgaoko.ci.cms.va.gov/node/74/edit
2. See errors being reporting at the top of the page

## AC / Expected behavior

- [ ] Investigate/Resolve errors

## Screenshots
![image](https://user-images.githubusercontent.com/106678594/201210711-3be2ce48-36fd-46f4-a8ea-04b6d4b0b465.png)

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [x] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by edmund-dunn** [comment]
Unable to replicate, this appears to no longer be an issue.
