### ISSUE TITLE
SSOi SAML certificate in Prod needs replacement

### ISSUE THREAD

**Issue by olivereri** [department-of-veterans-affairs/va.gov-cms#11566]
## Description
The IAM team will be replacing the SSOi SAML certificate in the Production environment on Thursday, December 9, 2021 at 9:00pm EST. This activity will impact SSOi SAML Partners only (NOT WebAgent Partners). Upon completion of the certificate update, Partners will be required to update the SSOi SAML certificate.

## Acceptance Criteria
- [x] Replace the existing SSOi SAML certificate with new certificate
- [x] Conduct post-replacement testing
- [x] Coordinate with IAM team for partner testing sessions (November 17th 9pm ET)
- [x] Set up some Slack reminders for before the certificate expires
- [x] Add cert expiration to shared team calendar in Confluence + reminder to update cert a few weeks beforehand

## Implementation Details

Relevant documentation:
https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/platform/cms/cms-sso-saml-iam-login-how-to.md

### CMS Team
Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [x] `Platform CMS Team`
- [ ] `Sitewide CMS Team`

**Comment by olivereri** [comment]
**logon.iam.va.gov** certificate

-----BEGIN CERTIFICATE-----
MIIFBTCCA+2gAwIBAgIHPQAAAACnDTANBgkqhkiG9w0BAQsFADBHMRMwEQYKCZIm
iZPyLGQBGRYDZ292MRIwEAYKCZImiZPyLGQBGRYCdmExHDAaBgNVBAMTE1ZBLUlu
dGVybmFsLVMyLUlDQTQwHhcNMjIxMTAxMTkxMzE1WhcNMjMxMTI1MTkxMzE1WjB2
MQswCQYDVQQGEwJVUzERMA8GA1UECBMIVmlyZ2luaWExEDAOBgNVBAcTB0FzaGJ1
cm4xJzAlBgNVBAoTHkRlcGFydG1lbnQgb2YgVmV0ZXJhbnMgQWZmYWlyczEZMBcG
A1UEAxMQbG9nb24uaWFtLnZhLmdvdjCCASIwDQYJKoZIhvcNAQEBBQADggEPADCC
AQoCggEBAMELIDluKeYd0eBij0QEjOcypDyvjYTX2klYRNYfVSCKeBctEUycYKBq
ispUo2H1t98eusdBgjjpAjLmj/dYm7ZQIsPNJHOu+FYW78TketlaPdFBCFr8+YEc
1vlA19sEMF81DAWKfaxkg7Q94BdWT8r58aAQcLwAJ8S8vy4qMio3PN/aO3KBMLbQ
EarYHhbtUIjER8aqfmXtprUMuvmq3M9jHOrnRv//zh5x8hAsm0absaNzFoTWxeiv
7WNd22r4nzR50TMiyeRwakjQRPA97S7o1F/fv8GccRcEZCDXj1qbwUWGuBSjVIzt
/bVtxo1Do9BGm4e5zzWH2z7RXpINo2ECAwEAAaOCAcUwggHBMBsGA1UdEQQUMBKC
EGxvZ29uLmlhbS52YS5nb3YwHQYDVR0OBBYEFIfPO3ByoMw5J8uZxJ6NGkW8GAbT
MB8GA1UdIwQYMBaAFGi3comeQurkUUUfWKIKJw9zYECjMEYGA1UdHwQ/MD0wO6A5
oDeGNWh0dHA6Ly9jcmwucGtpLnZhLmdvdi9wa2kvY3JsL1ZBLUludGVybmFsLVMy
LUlDQTQuY3JsMHgGCCsGAQUFBwEBBGwwajBEBggrBgEFBQcwAoY4aHR0cDovL2Fp
YS5wa2kudmEuZ292L3BraS9haWEvdmEvVkEtSW50ZXJuYWwtUzItSUNBNC5jZXIw
IgYIKwYBBQUHMAGGFmh0dHA6Ly9vY3NwLnBraS52YS5nb3YwDAYDVR0TAQH/BAIw
ADALBgNVHQ8EBAMCBPAwPQYJKwYBBAGCNxUHBDAwLgYmKwYBBAGCNxUIgcjDM4H5
8AaBpZ8NhOCBCIXCqksGgtrLEYHR8FYCAWQCASswHQYDVR0lBBYwFAYIKwYBBQUH
AwIGCCsGAQUFBwMBMCcGCSsGAQQBgjcVCgQaMBgwCgYIKwYBBQUHAwIwCgYIKwYB
BQUHAwEwDQYJKoZIhvcNAQELBQADggEBADztMS8r5aduq1Yr5YL8Sh/1wJeQ7kHA
t/MBu8EpoKuhSRv9VxhkvusT27oA4U6htfSpIQQVnZR6T1XzmdexMV1qeNeHhSKZ
Kq9QtCsH94OlLZn8+sqMx9CMI5x+7+adOqxK1yIK7RrDzb4hX6HQZk9fuxoIa1/s
5TAMJR5Uui1MBGAJDC0Y3vgLo7d6Bxbk+IA9K3Qe9iEkvnUa4DsgVpDIou+0SycV
mAyGDYajqS3K5w055jF9hYLs+vxCleIKf2CMU6Th1m6LyWf3Pn9pdKtfeC2pG68Z
qMVik/Zj54uQCCcPAaKzpaLYY51ZsDWLoDJLU8Ah95+ej2ZP14B0ctU=3D
-----END CERTIFICATE-----

**Comment by olivereri** [comment]
@cmaeng found last year's IAM cert update. Copied the contents here for this Thursdays cert replacement.
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/7026

**Comment by cmaeng** [comment]
perfect, thanks @olivereri !

**Comment by cmaeng** [comment]
@timcosgrove @ElijahLynn with Eric OOO, is there a way for us to verify that this was done?

**Comment by ElijahLynn** [comment]
The cert was merged in https://github.com/department-of-veterans-affairs/devops/pull/12255 but not deployed yet because the PROD deployment for Friday was skipped. It will go out with today's (Mon 21) deploy.
