### ISSUE TITLE
[Blocked] FE: Top pages menu: Make H2 dynamic /read from CMS menu title

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#11568]
**BLOCKED: the editable field in the CMS gets overwritten from code, so you cannot actually modify the menu name via editable CMS field**

## Menu title
#11654 will update the H2 name of this menu from `Popular on VA.gov` > `Top pages` 

Section title is currently hard coded: https://github.com/department-of-veterans-affairs/content-build/blob/main/src/site/includes/common-tasks.drupal.liquid#L48

The menu title can be edited in the CMS, and the change doesn't affect the machine name: https://prod.cms.va.gov/admin/structure/menu/manage/popular-on-va-gov

Dynamically populate this H2. Likely only Drupal Admins can save a menu name change, but dynamic H2 would need handled for line-wrapping / worst case line length, etc.

## Acceptance Criteria

- [ ] Top pages section H2 should = CMS menu title from https://prod.cms.va.gov/admin/structure/menu/manage/popular-on-va-gov

**Comment by jilladams** [comment]
Removing from scope: 


## Enabled vs. Disabled links

The front-end should only show enabled menu links:

![Screen Shot 2022-11-17 at 3 43 50 PM](https://user-images.githubusercontent.com/85581471/202584076-215e1de4-d353-4573-849b-53387171dcad.png)

This may require help from Drupal folk for updated graphQL to account for this?

## Menu Order
For several days, the Popular on VA.gov menu showed the last 2 links out of order, vs. what's in the Prod CMS.
Expected behavior: Order of Popular on VA.gov (and Homepage Hub List) menu links in the front-end should mirror the CMS order.

This no longer repros, but we want to confirm that in the code, order is set within the CMS and respected by the front-end.

**What was happening:** 
* Open Prod menu: https://prod.cms.va.gov/admin/structure/menu/manage/popular-on-va-gov - observe order of links
  * Open Staging CMS menu (which doesn't go to a front-end anywhere, but for reference, to confirm it is mirroring down to Staging): https://staging.cms.va.gov/admin/structure/menu/manage/popular-on-va-gov
* Look at Staging homepage prototype, https://staging.va.gov/homepage-test/, and see that the last 2 links are out of order

![Screen Shot 2022-11-14 at 12 13 54 PM](https://user-images.githubusercontent.com/85581471/201757521-28a30c34-1ab6-4c16-adec-bbcba54def03.png)



## why
We verified that: 
1. Disabled links: GraphQL doesn't send through disabled links to front end. The diff of why a disabled link continued to show, is likely due to lag from Prod data change > nightly CMS build > content releaase > mirror to Staging.
2. Order: same.

**Comment by FranECross** [comment]
Closing old iceboxed ticket.
