### ISSUE TITLE
Implement limit on number of "Top pages" links

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#11569]
## Description
As a Veteran, I want the number of links in "Popular on VAgov" to be strongly governed so that I can read them easily in the layout of the home page.

See [this comment](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10785#issuecomment-1270725161) on the original implementation ticket for context. The basic question: Should the FE template enforce this limit by displaying only the first X (10) of the links that come from drupal, or should the BE only send the allowed number of links in the first place?
- Drupal seems to have a nice "enabled" checkbox to help manage this
- There was some concern over whether Drupal might send non-enabled menu items to the FE, making the FE's counting job more difficult
- It sounds like typically business rules are better stored closer to the content to prevent mismatches and mistakes

## Acceptance Criteria
- [ ] Testable_Outcome_X
- [ ] Testable_Outcome_Y
- [ ] Testable_Outcome_Z
- [ ] Requires design review

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by FranECross** [comment]
Doesn't seem to be an issue any longer... Only ten links display, in two columns, and are easily viewed. Closing as a no op.
<img width="555" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeDNHQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--022f203b691140ca20c592419affac043a9a7dd2/image.png" alt="image.png" />
