### ISSUE TITLE
Errors found on Q&A Edit page

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#11578]
## Describe the defect
Errors found on Q&A- Single Edit screen when testing PHP 8.1:

> Deprecated function: parse_url(): Passing null to parameter #1 ($url) of type string is deprecated in Drupal\linkit\Plugin\Field\FieldWidget\LinkitWidget->formElement() (line 40 of modules/contrib/linkit/src/Plugin/Field/FieldWidget/LinkitWidget.php).

> Deprecated function: substr(): Passing null to parameter #1 ($string) of type string is deprecated in Drupal\linkit\Plugin\Field\FieldWidget\LinkitWidget->formElement() (line 41 of modules/contrib/linkit/src/Plugin/Field/FieldWidget/LinkitWidget.php).

## To Reproduce
1. Go to https://vacms-10870-upgrade-to-php81-rh7pjindaxvyxvr35alvilr3mqpgaoko.ci.cms.va.gov/node/44282/edit
2. See errors being reporting at the top of the page

## AC / Expected behavior

- [ ] Investigate/Resolve errors

## Screenshots
![image](https://user-images.githubusercontent.com/106678594/201991256-f4f3a290-24eb-4019-9273-6150296de01b.png)

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [x] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by edmund-dunn** [comment]
Unable to replicate. This appears to have been fixed.
