### ISSUE TITLE
Error found on Knowledge Base article

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#11579]
## Describe the defect
Error found on Knowledge Base article View and Edit screens when testing PHP 8.1:

>  User error: "attributes" is an invalid render array key in Drupal\Core\Render\Element::children() (line 98 of core/lib/Drupal/Core/Render/Element.php).

## To Reproduce
1. Go to https://vacms-10870-upgrade-to-php81-rh7pjindaxvyxvr35alvilr3mqpgaoko.ci.cms.va.gov/help/vet-centers/vet-center-website-development-status OR https://vacms-10870-upgrade-to-php81-rh7pjindaxvyxvr35alvilr3mqpgaoko.ci.cms.va.gov/node/27516/edit
2. See error being reported at the top of the page

## AC / Expected behavior

- [ ] Investigate/Resolve errors

## Screenshots
![image](https://user-images.githubusercontent.com/106678594/201992039-4aabbb98-b379-4b77-804a-c0610175c72b.png)

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [x] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by ndouglas** [comment]
Thanks @jilladams !  Yep, I'm working on this at this very moment in #11049.
