### ISSUE TITLE
Outdated Content Tool - Match CSV export columns to audit tool columns

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#11575]
## Description
In the CMS the [outdated content tool](https://prod.cms.va.gov/admin/content/outdated_content) is able to be exported as a CSV. However, the columns in the CSV exported are not quite the same as the tool displays in the CMS which is a bit confusing if you were using these together. It also is different from other exports as the CSV does tend to match the CMS display view.

### Differences
- ID column is in CSV export and not in tool
- Moderation state is in tool and not in CSV export
- CSV Export does not have a link to the node.  The tool has a link to the view node (title is linked) and the edit node (separate column)

### Screenshots
**CMS**
![image](https://user-images.githubusercontent.com/106678594/201955731-14f2e97a-f67f-4a93-b83a-ee59f63529c1.png)
**CSV**
![image](https://user-images.githubusercontent.com/106678594/201956430-c53de5ec-26e7-4a2c-8f3e-2be054c56d40.png)

## Acceptance Criteria
- [ ] CSV Export and audit tool match as closely as possible

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [x] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by laflannery** [comment]
@EWashb I found this issue I made when I was first reviewing the Outdated content report and I forgot about it.  I just retested it and everything in the description still applies - do you think any of this is:
1. needed for MVP for what we are doing for notifications now?
2. Needed at all ever so we would want to keep this open and eventually complete this or is it not important and we should close this?

**Comment by EWashb** [comment]
My hunch is that this is post-MVP but still important. I wonder if the ID in the CSV is really that useful. I don't think so (but I could be missing something) so I would say delete in the CSV. The other two- we should update that. It is useful IMO
