### ISSUE TITLE
Errors found on Delete tab for nodes

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#11585]
## Describe the defect
Errors found on the Delete tab for nodes when testing PHP 8.1:

> Deprecated function: reset(): Calling reset() on an object is deprecated in Drupal\entity_field_fetch\Access\DeleteAllowCheck->access() (line 91 of modules/contrib/entity_field_fetch/src/Access/DeleteAllowCheck.php).

> Deprecated function: reset(): Calling reset() on an object is deprecated in Drupal\entity_field_fetch\Access\DeleteAllowCheck->access() (line 91 of modules/contrib/entity_field_fetch/src/Access/DeleteAllowCheck.php).

## To Reproduce
1. Go to https://vacms-10870-upgrade-to-php81-rh7pjindaxvyxvr35alvilr3mqpgaoko.ci.cms.va.gov/node/51057/delete
2. See errors being reporting at the top of the page

## AC / Expected behavior

- [ ] Investigate/Resolve errors

## Screenshots
![image](https://user-images.githubusercontent.com/106678594/202016734-ba658d54-c404-4b7a-9e8f-8b204f4dc8a0.png)

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [x] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by edmund-dunn** [comment]
Unable to replicate locally, this appears to have been fixed.
