### ISSUE TITLE
Schedule participants for CMS Notification Research

### ISSUE THREAD

**Issue by davidmpickett** [department-of-veterans-affairs/va.gov-cms#11582]
## Description

**Editor-facing research**
* The Research Lead should work with Product Manager, Product Owner, and Business Stakeholders to identify a list of potential participants
  * The pool of potential participants should be at least 2-3 times larger than the desired # of participants
* The Research Lead contacts and schedules participants 
  * Using their VA.gov email address or the shared VADrupalCMS@va.gov email address
  * Consider using Calendly or Microsoft Bookings to set up timeslots so participants can pick slots
  * The Research Lead should create placeholder calendar events to block those time slots and invite other team members
  * Ensure that teleconferencing rooms connected to the calendar events have correct permissions for Moderator(s)
* The Research Lead should create placeholder calendar events to block those time slots and invite other team members 
* Ideally one of the Observers should be a Drupal developer so that they might be there to help answer technical questions or see defects in action
* Once participants are scheduled, the Research Lead invites other team members to official calendar events
* The Research Lead should schedule a [pilot session](https://depo-platform-documentation.scrollhelp.site/research-design/research-checklist#ResearchChecklist-4.Runapilotsession)
* The Research Lead should schedule 30-minute Daily Reseach Debrief meetings and invite Notetaker(s) & Observer(s)

## Acceptance Criteria
- [x] Ensure the target number(s) of participants (6 minimum) have been recruited and scheduled (for overall & primary criteria)
  - Schedule 20-25% more sessions than the desired # of participants to account for no-shows & cancellations 
- [x] Ensure that moderator(s), notetaker(s), and observer(s) are invited to research sessions
- [x] Recruit & Schedule Pilot session
- [x] Schedule Daily Research Debriefs and invite relevant team members 

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [x] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by laflannery** [comment]
Participants are chosen, Blake will reach out beginning of next week to schedule for interviews. He will do mocks up and have Dave C review first.

**Comment by EWashb** [comment]
@BlakeOrgan this is done, right?

**Comment by BlakeOrgan** [comment]
Yep! Closing this.
