### ISSUE TITLE
CMS Export System: Tar content on updates

### ISSUE THREAD

**Issue by indytechcook** [department-of-veterans-affairs/va.gov-cms#1158]
When content is updated and after the tome sync occurs the content needs to be tared up.

Related to https://github.com/department-of-veterans-affairs/va.gov-cms/issues/827

**Comment by ElijahLynn** [comment]
Update on this: Working through an issue with EFS volume mounts being crazy slow, which will affect this task.

**Comment by kevwalsh** [comment]
@ElijahLynn is that tracked in a separate ticket? or should this be moved back to in progress and have the AC updated?
