### ISSUE TITLE
FE: Establish criteria to remove flipper facilities_locator_mobile_covid_online_scheduling	

### ISSUE THREAD

**Issue by dsinla** [department-of-veterans-affairs/va.gov-cms#11588]
## Description
As we investigate each Facilities related Flipper, document the criteria and timeline for when it should be removed.

Refer to https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10656

## Acceptance Criteria
- [ ] Criteria for Flipper removal is created in this ticket 

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [X] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by maxx1128** [comment]
Here's the branch with the dead code removed: `va-11588-remove-mobile-covid-scheduling-flipper`

**Comment by kmariepat-cityfriends** [comment]
closed and implementation card is here: Implement Flipper #13484
