### ISSUE TITLE
Errors found on Vet Center page

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#11581]
## Describe the defect
Errors found on Vet Center View screen when testing PHP 8.1:

> Deprecated function: strip_tags(): Passing null to parameter #1 ($string) of type string is deprecated in Drupal\va_gov_backend\EventSubscriber\EntityEventSubscriber->appendHealthServiceTermDescriptionToVetCenter() (line 234 of modules/custom/va_gov_backend/src/EventSubscriber/EntityEventSubscriber.php).

> Deprecated function: strip_tags(): Passing null to parameter #1 ($string) of type string is deprecated in Drupal\va_gov_backend\EventSubscriber\EntityEventSubscriber->appendHealthServiceTermDescriptionToVetCenter() (line 234 of modules/custom/va_gov_backend/src/EventSubscriber/EntityEventSubscriber.php).

> Deprecated function: strip_tags(): Passing null to parameter #1 ($string) of type string is deprecated in Drupal\va_gov_backend\EventSubscriber\EntityEventSubscriber->appendHealthServiceTermDescriptionToVetCenter() (line 234 of modules/custom/va_gov_backend/src/EventSubscriber/EntityEventSubscriber.php).

> Deprecated function: strip_tags(): Passing null to parameter #1 ($string) of type string is deprecated in Drupal\va_gov_backend\EventSubscriber\EntityEventSubscriber->appendHealthServiceTermDescriptionToVetCenter() (line 234 of modules/custom/va_gov_backend/src/EventSubscriber/EntityEventSubscriber.php).

## To Reproduce
1. Go to https://vacms-10870-upgrade-to-php81-rh7pjindaxvyxvr35alvilr3mqpgaoko.ci.cms.va.gov/jupiter-vet-center
2. See errors being reporting at the top of the page

## AC / Expected behavior

- [ ] Investigate/Resolve errors

## Screenshots
![image](https://user-images.githubusercontent.com/106678594/201998270-2e021593-a894-4f33-8731-f365f4a59964.png)

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [x] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by edmund-dunn** [comment]
Unable to replicate locally, appears to be fixed.
