### ISSUE TITLE
[Homepage post-MVP] help-text and character limits for Homepage drupal fields

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-cms#11586]
## Description
As an Editor working on the new Homepage, I want to see helpful text with fields of custom blocks so that it's clear what I need to do to conform with governance.

This issue covers non-MVP areas which could benefit from Drupal help text, continuing the work done in [Implement help-text and character limits for all Homepage drupal fields #11119](https://app.zenhub.com/workspaces/vagov-cms-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/11119). 

There are other outstanding items from #11119 in which the guidance from Laura was not strictly implemented. These items will need to be prioritized. 

The menu fields are not editable in the UI like a field on a node would be, they are intentionally hidden from the manage fields UX by Drupal core. Adding additional help text likely will require custom code and should be evaluated accordingly. 

### Block description
As an editor, I need to understand that this will be seen only within Drupal and not on the front end. The block description isn't editable as seen on the block/add or block/edit pages.
- Suggested guidance: _This is used for identifying the block with the CMS. The description will not be shown on VA.gov.._ 
<details> 
<summary>Following #11119, this help text is seen in the "Add a custom block" menu UX, rather than inside the custom block UX. </summary>
 
![image](https://user-images.githubusercontent.com/55411834/202560707-06b962c0-9e10-4eaa-a467-bd3eee11319b.png)
![image](https://user-images.githubusercontent.com/55411834/202560877-cf81d42e-efd3-43c4-b227-862852e1cd36.png)
</details> 

---

### Link text
Decisions to add help text to this field should remember an existing CTA paragraph has been leveraged for this implementation and any help text which is added will be exposed anywhere else the paragraph is used. The purpose of the help text should be 
  - Suggested guidance: 
  - _This text should tell Veterans what to do next and include the intended purpose of the destination page. For more link tips, visit the [links page](https://design.va.gov/content-style-guide/links) of the VA content style guide._ 
  - _Choose an option from the dropdown to tell Veterans what to do next._

<details> 
<summary> Example in Benefit Promo custom block </summary>

![image](https://user-images.githubusercontent.com/55411834/202561186-9d606dfe-920f-4384-8fef-f9e53dbad7ea.png)
</details>

---

### Menus:
- Title - As an editor, I need to understand how many characters are allowed and that what I enter into this field will appear as the menu heading. - _Clarification: character limits are not yet implemented_
  - Something like: _x characters remaining_
- Add menu link > Menu link title - As an editor, I need to understand how many characters are allowed
  - Something like: _x characters remaining_
- Add menu link > Description - As an editor, I need examples of what should be entered so that the hover text is appropriate and 508 compliant.
  - _I'm not sure that hover text on links is considered accessible so perhaps this field should be discouraged?_
- Administration > Structure > Menus > list of links - As an editor, I need to know what checking/unchecking the "enabled box" means to the front end display. 
  - Something like: _Menu links which are marked as "Enabled" will be displayed in the menu._ 

<details>
<summary> Menu screenshot </summary>

![image.png](https://images.zenhubusercontent.com/5d8a47393ac3440001d1a2ed/6fbd7caf-a455-45b6-bee4-79d699ae81a1)

</details>

---
### Other
The following recommendations from @laflannery were not strictly implemented in #11119 but need to be evaluated for need and prioritization. 

- Changing “Promo Headline” and "Promo Text" labels to use lower case for "headline" and "text" to follow the standard pattern for field labels
- Help text for the promo headline does not include guidance for sentence capitalization and link to the content style guide. 
- Wrapping Benefit promo CTA elements together with a border 
- Removal of extraneous/irrelevant text for the Link field
- Help text referencing the dropdown for Link text

<details>
<summary> Screenshots from PR tugboat </summary> 

![custom block](https://user-images.githubusercontent.com/55411834/202560152-819346d7-3073-44ec-bbd4-42268069b477.PNG)
![image](https://user-images.githubusercontent.com/55411834/202559599-093ddae0-cdb4-4f6e-992e-0146f7936afa.png)
![image](https://user-images.githubusercontent.com/55411834/202559609-7d4872a3-93ce-4063-87ce-f2bc2ec4f114.png)

</details>

**Comment by jilladams** [comment]
Moved to Post-MVP epic.

**Comment by wesrowe** [comment]
De-prioritized for now, moved to homepage backlog epic.

**Comment by FranECross** [comment]
Closing old iceboxed ticket.
