### ISSUE TITLE
Linky issues

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#11584]
## Describe the defect
When testing PHP 8.1, it does not seem as though Linky is working as it should. Adding new links within nodes is not creating new Managed links and when I view the links within the Source view I see the true end destination, rather than a Linky reference.

## To Reproduce
1. Go to [Managed Links](https://vacms-10870-upgrade-to-php81-rh7pjindaxvyxvr35alvilr3mqpgaoko.ci.cms.va.gov/admin/content/linky)
2. In the **Title** field, search for a a term that probably does not already have an existing reference, perhaps "Shenanigans". Confirm that Linky does not already have a reference for your term.
3. Go to any node and create a new link with your term (i.e. Shenanigans) as the link text
4. Go back to Managed links and search for your term again
5. Confirm Linky still does not have a reference for this term

Second behavior:
1. Go to the node with the new link you just created above, view the source code of the rich text editor.
2. Confirm that the link is displayed as the end destination instead of the Linky reference

## AC / Expected behavior

- [ ] Investigate/Resolve errors

## Screenshots
![image](https://user-images.githubusercontent.com/106678594/202011070-847e73b8-8b8b-4c5c-a9d8-a4ad912ebe13.png)

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [x] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by ndouglas** [comment]
This works for me (see [here](https://vacms-10870-upgrade-to-php81-rh7pjindaxvyxvr35alvilr3mqpgaoko.ci.cms.va.gov/lovell-federal-va-health-care/events/51056)).  Linky only engages for external links, not local links using nodes, etc.  I suspect that's what you're seeing here.

**Comment by laflannery** [comment]
I totally forgot about the external link situation, I was 100% using a different node to test.  Closing this, thanks!

Also really glad you used my test suggestion of shenanigans :)
