### ISSUE TITLE
FE: Establish criteria to remove flipper  facility_locator_lighthouse_covid_vaccine_query                   

### ISSUE THREAD

**Issue by dsinla** [department-of-veterans-affairs/va.gov-cms#11592]
## Description
As we investigate each Facilities related Flipper, document the criteria and timeline for when it should be removed.

Refer to https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10656

## Acceptance Criteria
- [ ] Criteria for Flipper removal is created in this ticket 

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [X] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by maxx1128** [comment]
This flipper is being used in one component, `SearchControls` in the facility locator. Removing it would not affect the front-end since the flipper is already on, and removing it would only ensure it stays on. So it's easy to remove from the front-end as well as the back-end.

**Comment by maxx1128** [comment]
The branches for removing the flipper from the needed repos are below. No pull requests have been made with them yet, but can be once this flipper is approved for removal.

1. `vets-website` - `va-11592-remove-covid-vaccine-query-flipper`
2. `vets-api` - `va-11592-remove-covid-vaccine-query-feature`

**Comment by jilladams** [comment]
@maxx1128 same here - can this ticket be closed?

**Comment by maxx1128** [comment]
@jilladams I think it can if we're not waiting to hear back from anyone on any other factors that would prevent us from removing the flipper.

**Comment by kmariepat-cityfriends** [comment]
Closing this card, Implementation will be completed on #13239
