### ISSUE TITLE
Adding Inline guidance from UI doesn't show

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#11610]
## Describe the defect
Using the Drupal UI to add inline guidance is not working as expected.  I am not sure if this is a defect or it's just not set up to work but I wanted to mention just in case.

## To Reproduce
1. Go to Structure > Content Types > Full Width Alert > [Manage Form display](https://vacms-10870-upgrade-to-php81-rh7pjindaxvyxvr35alvilr3mqpgaoko.ci.cms.va.gov/admin/structure/types/manage/banner/form-display)
2. Click on "Add Field Group"
3. Choose "Inline Guidance" from the dropdown
4. Fill in the options for guidance for the Paths field
5. Make sure to save the form
6. Go to a Full Width Alert node and confirm that the new content you added is not displaying

## AC / Expected behavior

- [ ] Investigate/resolve error

## Screenshots
![image](https://user-images.githubusercontent.com/106678594/202222298-05a003a6-6d50-4f3b-be76-adbe020ab617.png)

![image](https://user-images.githubusercontent.com/106678594/202222086-ece36580-56a7-41ea-be0c-bcc1d1407742.png)

![image](https://user-images.githubusercontent.com/106678594/202222572-ce6b9df1-25cd-4c95-a3ea-a9557c1b039d.png)

 ## Additional context
I know that twig updates need to be made in order for this content to display which is why I only tested this with the Full Width Alert, because I thought these updates were already made for this content type.  However, that might not be the case and that may be way this is not displaying and therefore not related to PHP 8.1 at all.

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [x] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by edmund-dunn** [comment]
This works as expected. 
![CleanShot 2023-01-03 at 14 37 55](https://user-images.githubusercontent.com/109987005/210453024-bf7a48e6-3c79-4726-954c-6a28926063b2.jpg)
