### ISSUE TITLE
PM: Configure beta Banner alerts for Lovell pages 

### ISSUE THREAD

**Issue by dsinla** [department-of-veterans-affairs/va.gov-cms#11635]
## Description
As we publish Lovell pages, we want a banner on the top stating "This is a beta"

Look at the revision history for other alerts and the revision history for the old Lovell node itself to find potential language we might use for this.

## Acceptance Criteria
- [x] Review and refine wording of existing banner - DC to send to Dave C 
- [x] Does banner provide link to Teamsite page?
- [ ] ~~Banners appear on Lovell pages ~~ (Note: cannot be placed until the operating status for Lovell - VA and Lovell - TRICARE are published. This step has been moved to the Lovell Dual State issue.)

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by JayDarnell** [comment]
@Dottisea do we have an estimated ETA for this text?

**Comment by Dottisea** [comment]
I will prioritize it and let you know as soon as I do.

**Comment by davidconlon** [comment]
@Dottisea @JayDarnell it already exists

https://prod.cms.va.gov/lovell-federal-health-care-va/vamc-banner-alert/2023-01-30/website-coming-soon-not-the-official-lovell-federal-health-care-website

**Comment by davidmpickett** [comment]
Looking into this today it seems like there has possibly been a regression. The checkboxes for Lovell no longer appear on the Node Edit for VAMC System Banner Alert with Situation Updates.

This was resolved back in November - https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11726

![screencapture-staging-cms-va-gov-node-40013-edit-2023-02-23-09_25_32](https://user-images.githubusercontent.com/51967950/220954638-7e23b3a0-f500-49cd-993e-6f1824c1ac44.png)

![screencapture-prod-cms-va-gov-node-40013-edit-2023-02-23-09_33_41](https://user-images.githubusercontent.com/51967950/220954911-9d34200b-3a59-4d1c-9a77-87ee9be26912.png)

**Comment by omahane** [comment]
@davidmpickett Could you post a link to the page where you're seeing this?

**Comment by omahane** [comment]
Never mind, I found it here: https://staging.cms.va.gov/node/add/full_width_banner_alert

**Comment by JayDarnell** [comment]
This issue is complete. The banner alert is ready to go in terms of content and simply needs to be added to the appropriate locations once the operating status pages for Lovell - VA and Lovell - TRICARE have been published.
