### ISSUE TITLE
Conduct Lovell editor training 

### ISSUE THREAD

**Issue by dsinla** [department-of-veterans-affairs/va.gov-cms#11633]
## Description
Based on feedback and requirements from VHADM, deliver a Lovell-specific training.

## Acceptance Criteria
- [x] Training agenda/topics is agreed with VHADM
- [x] Training is scheduled
- [x] Training is delivered 

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [x] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [x] `⭐️ User support`

**Comment by EWashb** [comment]
Need to get with Stefanie/Troy @ Helpdesk

**Comment by EWashb** [comment]
Meeting scheduled with helpdesk to create the training plan on 11/28. create ticket for a training plan.

**Comment by stefaniefgray** [comment]
Closing because we did it, and it went well! 🎉
