### ISSUE TITLE
Determine existence of any legal requirement for Mental Health Phone number

### ISSUE THREAD

**Issue by dsinla** [department-of-veterans-affairs/va.gov-cms#11634]
## Description
Ask VHADM for explicit identification of legislation, if any, for "Mental health phone number is required" - anecdotal? 
Legal vs Policy
Ask VHADM/PAO to verify official phone number where there are discrepancies or multiple
Consult with Mental Health program office for some of these questions
Iteration on the content model 
Longer term - develop strategy for having editors define Primary MH phone number when there are multiple 

Audit performed: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11338

## Acceptance Criteria
- [x] Identify law/policy number, or acknowledge that there is no legal requirement. 

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by dsinla** [comment]
Sent email on 11/23 and follow-up today 12/1

_Please forgive the duplicate, I had previously sent from my Agile6 email on 11/23. Sending again from va.gov email, as per the best practice._

Hello Blake and Justin

I'm asking for your help to get to the bottom of this issue. We have heard that there is a legal requirement to display Mental Health phone numbers on the VAMC Facilities websites, but we don't have any specific legislation to point to.

Are you aware of the specific law or bill that dictates this requirement for Mental Health facilities? If not, could you point me to a contact in the Mental Health field office> We want to identify the legislation and understand its terms so we can all properly communicate the requirements to our editors.

Thanks and regards
David Shannon

**Comment by dsinla** [comment]
In discussions with Dave C, the first step here was to just verify the legal requirements, if any. 
This issue probably could be re-titled "Determine existence of any legal requirement for Mental Health Phone numbers" 
Even so, 2 emails have been sent with no response so far.

**Comment by EWashb** [comment]
@dsinla make sure to update the sprint label on this one.

**Comment by davidconlon** [comment]
https://www.congress.gov/bill/114th-congress/house-bill/203/text

SEC. 3.   PUBLICATION OF INTERNET
WEBSITE TO PROVIDE INFORMATION REGARDING
MENTAL HEALTH CARE SERVICES.

(a)   In General.--Using funds made available to
the Secretary of Veterans Affairs to publish the Internet websites of
the Department of Veterans Affairs, the Secretary shall survey the
existing Internet websites and information resources of the Department

[[Page 32]]

to publish an Internet website that serves as a centralized source to
provide veterans with information regarding all of the mental health
care services provided by the Secretary.

(b) Elements.--The Internet website published under subsection (a)
shall provide to veterans information regarding all of the mental health
care services available in the Veteran Integrated Service Network that
the veteran is seeking such services, including, with respect to each
medical center, Vet Center (as defined in section 1712A of title 38,
United States Code), and community-based outpatient center in the
Veterans Integrated Service Network--
(1) the name and contact information of each social work
office;
(2) the name and contact information of each mental health
clinic;
(3) a list of appropriate staff; and
(4) any other information the Secretary determines
appropriate.

(c)   Updated Information.--The Secretary shall
ensure that the information described in subsection (b) that is
published on the Internet website under subsection (a) is updated not
less than once every 90 days.

(d) Outreach.--In carrying out this section, the Secretary shall
ensure that the outreach conducted under section 1720F(i) of title 38,
United States Code, includes information regarding the Internet website
published under subsection (a).


From Jenny: "we should probably verify with our VHA mental health colleagues though that there is still the assumption that every location is a path to mental health services"

**Comment by kmariepat-cityfriends** [comment]
I sent an email to Blake and Justin on this today

**Comment by kmariepat-cityfriends** [comment]
Relates to future work with regards to lighthouse, potentially taking over as source of truth in lighthouse

**Comment by kmariepat-cityfriends** [comment]
I sourced the same legislation information the Dave Conlon references above. Ultimately we will be working with VHA digital media in our biweekly meeting to align on next steps for this work. The acceptance criteria on this card to `Identify law/policy number, or acknowledge that there is no legal requirement.` has been completed and I am closing the card.


Jenny mentioned you were looking for legislation regarding the listing of mental health phone numbers. This comes from the Clay Hunt Act. Full text is available via this link, but we’ve also included a more relevant excerpt below: Text - H.R.203 - 114th Congress (2015-2016): Clay Hunt SAV Act | Congress.gov | Library of Congress.

 

We believe every VHA health care location is required to serve as a way to access mental health services as an entry point. So, even if there is no “mental health clinic” at a CBOC, one should be able to get access to mental health care through that CBOC.
