### ISSUE TITLE
Record performance metrics for behavioral tests in DataDog.

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-cms#11630]
## Description
See #11629.

It'd be good to record performance metrics from our behavioral tests and report them upstream to DataDog, since they reflect significant aspects of the editorial experience.

For instance, almost every Cypress test currently involves logging in.  That gives us a reasonable metric, and happily some good code-injection points, for the responsiveness of the login experience as a whole.

There might be other operations that are performed multiple times in the behavioral tests that can be measured and reported upstream, but offhand nothing leaps into my mind.

## Acceptance Criteria
- [ ] Elapsed time for login operations is recorded and statistics (min, max, mean) are uploaded to DataDog.
- [ ] ???

**Comment by productmike** [comment]
@ndouglas @laflannery Is this something still useful? I see works like a11y and metrics, which makes me curious to determine the value -- especially considering the objectives we have for 3Q

**Comment by EWashb** [comment]
Per the statement above, I'm going to close this. The effort doesn't sound worth it at this time.
