### ISSUE TITLE
Change robots.txt to allow by default

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#11637]
[Robots.txt (content-build)](https://github.com/department-of-veterans-affairs/content-build/blob/main/src/site/assets/robots.txt) historically has been set to disallow everything (`Disallow: /`) from being crawled, and explicitly add / allow top level directories as they're added / approved. 

We will reverse the logic in order to allow by default / disallow by explicit decision. 

## Additional context
* Historically Platform has owned this file, but recently Dave & Mike Chelen have decided to transition ownership to Public Websites: https://dsva.slack.com/archives/CBU0KDSB1/p1668711036321659?thread_ts=1666819314.703079&cid=CBU0KDSB1

## Acceptance Criteria
- [ ] Update codeowners file to reflect that vsa-frontend now own [Robots.txt (content-build)](https://github.com/department-of-veterans-affairs/content-build/blob/main/src/site/assets/robots.txt)
- [ ] Robots.txt is updated to allow by default
- [ ] TBD: how to verify expected results pre-prod? (does this need a spike?)

**Comment by wesrowe** [comment]
@jilladams, do you think we got approval or need more meetings/outreach?

**Comment by jilladams** [comment]
Dave approval: https://dsva.slack.com/archives/CBU0KDSB1/p1668711036321659?thread_ts=1666819314.703079&cid=CBU0KDSB1

**Comment by dsasser** [comment]
@wesrowe @jilladams 
> TBD: how to verify expected results pre-prod? (does this need a spike?)

This will require a dev assist. It requires setting up https://github.com/google/robotstxt, which I have done.

**Comment by jilladams** [comment]
PR looks good. We don't have any explicit list of disallows that should be added with this reversal. I have been mulling that - for the front-end site, anything behind auth will automatically not be crawlable, and I can't think of any other paths that are publicly accessible that shouldn't be indexed. If anything comes to mind that seems prudent, holler. Otherwise, happy to have this merge when Platform approves.
