### ISSUE TITLE
Content Audit: references to the VRRAP program

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-cms#11647]
Content audits can be performed by searching the codebase and compiled site for specific terms ur using an audit tool within drupal. 
Please provide any context for the audit, any related terms or alternate spellings, or and related components that could return content you are interested in. Please see the [collab cycle doccumentation](https://va-gov.atlassian.net/l/cp/U0DfKLfs) for more information.

## 1. Please provide any context around your audit

The Veteran Rapid Retraining Assistance (VRRAP) Program will end taking new applicants starting December 11, 2022. There are several links and sections and a static page about this program we already know about. But we need to make sure there there aren't any others that we haven't found. 
  
## 2. What are the terms you are searching for within the CMS? Are there alternate spellings?
VRRAP, Veteran Rapid Retraining Assistance Program, Form 22 1990s

## 3. Are there components, elements or content types related to your search?
static pages, form pages

## 4. Does a corresponding audit need to be run on the Veteran-facing website?  
  - [ X ] Yes 
  - [ ] No

## 5. When do you need the audit to be completed
All references should be removed on 12/11/22

## CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [x] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by EWashb** [comment]
@RLHecht wanted to confirm that I've received your request. I'm going to bring this into sprint planning next week to see when we might be able to accommodate this request.

**Comment by RLHecht** [comment]
@EWashb Just wanted to check if this work is going to be pulled into your next sprint. We need to to make our VRRAP updates by December 11, which is the last day the program is accepting new applicants.

**Comment by EWashb** [comment]
This is one of the things I wanted to chat with you about tomorrow @RLHecht. I wanted to understand all of the parameters.

**Comment by EWashb** [comment]
This will be taken care of as part of https://github.com/department-of-veterans-affairs/va.gov-cms/pull/11706. Once that search is implemented then the content team will be able to do a self-service audit in the CMS.

@jilladams this is another that may need a FE audit.

**Comment by jilladams** [comment]
FYI @wesrowe

**Comment by wesrowe** [comment]
We'll keep an ear out for how the self-service audit goes. Notify me and Jill if further action is required from PW.

**Comment by EWashb** [comment]
@RLHecht how are you feeling about closing this ticket?

**Comment by RLHecht** [comment]
This is good to close. We used the new audit tool. Thanks!
