### ISSUE TITLE
Redirect Request: Vanity URL for covid + flu vaccine campaign landing page - ASAP target timing

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-cms#11649]
### Instructions
- Requests must be submitted **AT LEAST** 2 weeks in advance.  Some requests take a significant amount of time and coordination to implement, so start the process as soon as you know you will need one. 
- This issue will be used from initial request through implementation to ensure all individuals working on this are notified of status updates.  Please do not create multiple issues to track differnt steps.
- It is your responsibility to notify VA stakeholders as appropriate.  

### Type of request
- [ ] We are retiring or taking down a page and need to redirect the URL (complete redirect section)
- [ ] We are changing the URL of an existing page (complete redirect section)
- [x] We need a custom vanity URL (complete vanity URL section)

### Implementation date
When does this request need to be live: ASAP

### Vanity URLs 
Vanity URL  |  Landing page
---  |  ---
va.gov/covid-flu | va.gov/initiatives/covid-flu

**Note:** I'm putting in this ticket as a placeholder and have started discussions with Joni and Mikki around this. They'll post the info about the vanity URL once it's confirmed.

**Link to campaign landing page request issue:** I've submitted the request to the help desk, but I don't have the request issue yet. Will add once that's available.

### Process, Roles and Responsibilities
- [x] Requesting team: Above information is provided
- [x] Requesting team: All appropriate VA stakeholders are notified as appropriate
- [ ] IA: Request is vetted and documented and implementation plan is clear 
- [ ] IA: Request is assigned to appropriate team for implementation 
- [ ] Implementation team: Work is complete
- [ ] Implementation team: Validated in production
- [ ] Requesting team: Validates everything is correct in production and closes ticket

**Comment by stefaniefgray** [comment]
https://prod.cms.va.gov/initiatives/covid-flu is live, needs redirect

**Comment by jilladams** [comment]
Ok! We'll pull this into our sprint starting today.

**Comment by chri5tia** [comment]
https://github.com/department-of-veterans-affairs/devops/pull/12277

**Comment by jilladams** [comment]
Redirect is live in prod, verified. (Serves a 404 because the CLP node is still in draft: https://prod.cms.va.gov/initiatives/covid-flu)
