### ISSUE TITLE
Redirect VRAPP page - target 11 Dec

### ISSUE THREAD

**Issue by jsimonVA** [department-of-veterans-affairs/va.gov-cms#11642]
### Instructions
- Requests must be submitted **AT LEAST** 2 weeks in advance.  Some requests take a significant amount of time and coordination to implement, so start the process as soon as you know you will need one. 
- This issue will be used from initial request through implementation to ensure all individuals working on this are notified of status updates.  Please do not create multiple issues to track differnt steps.
- It is your responsibility to notify VA stakeholders as appropriate.  

### Type of request
- [x] We are retiring or taking down a page and need to redirect the URL (complete redirect section)
- [ ] We are changing the URL of an existing page (complete redirect section)
- [ ] We need a custom vanity URL (complete vanity URL section)

### Implementation date
When does this request need to be live: 11 Dec 2022

### Redirects 
Current URL  |  Redirect Destination or New URL
--- | ---
 https://www.va.gov/education/other-va-education-benefits/veteran-rapid-retraining-assistance/ <br>  Please ensure all child pages of this directory are captured in the redirect, this will ensure the corresponding form, and all pages within that form flow are also redirected.  | https://www.va.gov/education/other-va-education-benefits/

### Process, Roles and Responsibilities
- [x] Requesting team: Above information is provided
- [x] Requesting team: All appropriate VA stakeholders are notified as appropriate
- [x] IA: Request is vetted and documented and implementation plan is clear 
- [x] IA: Request is assigned to appropriate team for implementation 
- [ ] Implementation team: Work is complete
- [ ] Implementation team: Validated in production
- [ ] Requesting team: Validates everything is correct in production and closes ticket

**Comment by mnorthuis** [comment]
I believe we need to also capture the actual online form in this ticket.  Will need @jsimonVA to confirm...but for some reason I cannot tag him in this ticket any longer.

**Comment by jsimonVA** [comment]
@mnorthuis you are correct, I need to redirect or take down (which every method is better) these additional URLS 
(https://www.va.gov/education/other-va-education-benefits/veteran-rapid-retraining-assistance/apply-for-vrrap-form-22-1990s/introduction) and (https://www.va.gov/education/other-va-education-benefits/veteran-rapid-retraining-assistance/apply-for-vrrap-form-22-1990s/apply). 

Thank you for catching that

**Comment by mnorthuis** [comment]
@jilladams @wesrowe Per @jsimonVA's note above, please note additional details in the main issue description to redirect everything within the directory so that it captures the corresponding form and form flow pages, which are children to that directory.

**Comment by RLHecht** [comment]
@jilladams @wesrowe Is this redirect happening on Sunday 12/11 or would it happen Friday or Monday? We need to know when to publish our page that has the alert about the program going away.

**Comment by jsimonVA** [comment]
Hello, we need it to be on the 11th unfortunately. This is a program that has a hard cutoff date, and we cannot accept new applicants pass the cut off day. Please, let me know if this isn't feasible so I can relay to the Education team. 

The 10th is the last day for new applicants to apply, so we will need to make sure no one has the ability to apply on the 11th.

**Comment by RLHecht** [comment]
@jilladams @wesrowe Can redirects be scheduled for weekend days?

**Comment by jilladams** [comment]
Not as far as I know. The deployment for redirects runs automatically on Wednesday mornings at 7a PT / 10a ET. If we need something to deploy at any other time it must be done manually as an out of band deploy with Platform's help. So: doing this on the weekend would necessitate a post-mortem. Is it possible for us to deploy the redirect early? e.g. if we got it deployed last thing on Fri the 9th, does that cause problems? @jsimonVA @RLHecht 

@wesrowe FYI, we may need to consider reassigning - Christia hasn't gotten to this one yet and is out sick today. Will flag in our channel.

**Comment by jsimonVA** [comment]
I have a meeting with EDU in 20mins I will find out.

**Comment by jilladams** [comment]
I'm just speaking to the redirect on the URL. @RLHecht can speak to the content changes.

**Comment by jsimonVA** [comment]
@RLHecht Now that I have re-read my question, it wouldn't make sense to go through with the other ticket without the redirect. I am checking to see if it is possible to do on the 9th or the 12th. I'll have more information soon.

**Comment by RLHecht** [comment]
Thanks @jsimonVA . If this needs to be done before Sunday, we can amend the note we're putting on our page to say that the program is ending on December 11 (rather than having it say it already closed) and publish late in the day on Friday. Then we would adjust the content on Monday morning.

**Comment by RLHecht** [comment]
@jsimonVA we don't have staffing to do any publishing on Sunday so all the other pieces to this would need to happen on either the 9th or the 12th. Since the program is live until Sunday, it probably makes better sense to do on Monday. But let me know what you find out from the education team.

**Comment by jsimonVA** [comment]
@RLHecht @jilladams Cinda Quattrini has given the ok to make changes on the 12th as long as we are able to place a note of sorts on the page by end of day tomorrow, 9 Dec 2022, letting users know that no new applications will be accepted after 10 Dec 2022. She did say that she may need to verify this with someone else (don't have a name), but for now move forward with the 12th. Darla Van Nieukerk asked if we can get an early release on Monday 12 dec 2022, since this will be visible pass the program end date.

**Comment by jilladams** [comment]
We can have the PR up and merged for the redirect, and @jsimonVA then it just needs an OOB deploy, which we manage via Slack with the #vfs-platform-support team. Here's an example: https://dsva.slack.com/archives/CBU0KDSB1/p1669832697611149

I'm west coast, but the engineer who will get the PR merged is East coast. @jtmst , can you drive the request first thing Monday? Or, @jsimonVA if you're east coast, you could run with it as well, either way. Typically: Devops will deploy to dev so you can verify the redirect, then once you sign off, deploy to prod.

**Comment by jtmst** [comment]
> We can have the PR up and merged for the redirect, and @jsimonVA then it just needs an OOB deploy, which we manage via Slack with the #vfs-platform-support team. Here's an example: https://dsva.slack.com/archives/CBU0KDSB1/p1669832697611149
> 
> I'm west coast, but the engineer who will get the PR merged is East coast. @jtmst , can you drive the request first thing Monday? Or, @jsimonVA if you're east coast, you could run with it as well, either way. Typically: Devops will deploy to dev so you can verify the redirect, then once you sign off, deploy to prod.

Either is fine with me.  I can run it

**Comment by jsimonVA** [comment]
If you could @jtmst I would appreciate it. Just FYI, I am Central time. Thanks for the help with this.

**Comment by laurwill** [comment]
Hi @jilladams , Terry Warren, an edu stakeholder, is asking when the redirect will be live — do you have an estimate for when the OOB deploy will go through today? Thank you!

**Comment by jtmst** [comment]
> https://www.va.gov/education/other-va-education-benefits/veteran-rapid-retraining-assistance/

Request was made earlier and deploy just finished.  Redirect is now live

**Comment by jilladams** [comment]
Thanks Josh, closing.

**Comment by laurwill** [comment]
hi @jilladams and @jtmst , I see the note at top of ticket about redirecting all the child pages/form pages associated with this URL, but the [online form](https://www.va.gov/education/other-va-education-benefits/veteran-rapid-retraining-assistance/apply-for-vrrap-form-22-1990s/introduction) isn't redirecting yet — will this happen separately? Thanks!

**Comment by jsimonVA** [comment]
@jilladams @jtmst checking on this as well, do we know when all the redirects will be completed?

**Comment by jtmst** [comment]
pr addressing this is up pending approval

**Comment by jilladams** [comment]
Change is merged and deploy has been requested: https://dsva.slack.com/archives/CBU0KDSB1/p1670878883817459

**Comment by jilladams** [comment]
The change merged today is on Dev for review, but I think it may need a fix. Logging notes here for easier formatting vs. slack: 

**Prod URL:**
https://www.va.gov/education/other-va-education-benefits/veteran-rapid-retraining-assistance/apply-for-vrrap-form-22-1990s/introduction

**Dev URL:**
https://dev.va.gov/education/other-va-education-benefits/veteran-rapid-retraining-assistance/apply-for-vrrap-form-22-1990s/introduction

Redirects to https://dev.va.gov/education/other-va-education-benefits/ 
where I would expect it to land on https://dev.va.gov/education/other-va-education-benefits/apply-for-vrrap-form-22-1990s/introduction instead

**Comment by jilladams** [comment]
Clarified with Josh: app form traffic should all go to other edu benefits. (I got myself confused re: child pages of VRAPP via left sidebar behavior, sorry for churn.) Have gone ahead with request to push to prod. https://dsva.slack.com/archives/CBU0KDSB1/p1670888246156819?thread_ts=1670878883.817459&cid=CBU0KDSB1
