### ISSUE TITLE
Supporting Platform Crew efforts for vets-website on Tugboat

### ISSUE THREAD

**Issue by cmaeng** [department-of-veterans-affairs/va.gov-cms#11640]
## Description
As Platform Crew explores options for the future of review instances, they are looking at Tugboat as a specific solution. This ticket is to timebox to provide any needed support in their efforts.

## Acceptance Criteria
- [ ] Provide support to Platform Crew as needed

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [x] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by EWashb** [comment]
This is no longer its own initiative on platform. There is a preview project tech team and there are no cms dependencies
