### ISSUE TITLE
Income limits: technical strategy & architecture; prep questions for stakeholders

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#11643]
## Description

The original product had a database behind it.

### Design assumptions
- The UX will be wizard-like
- The wizard will collect a few pieces of information from the Veteran (eg, location, dependents, income)
- The app will then look up their income limit using the gathered information

### Eng questions
- Where does data come from?
- Will there be an API?
- What team will own data source of truth?
- ATO affected? or PPI?

FYI: The/a HUD data source that drives the app is an Excel spreadsheet located here: https://www.huduser.gov/portal/datasets/il/il22/Section8-FY22.xlsx 

### Ticket assumptions

- **Time-box: a couple meetings, then document**
- Involve:
  - Josh, Bryan, Ryan, Steve
- We need to get the data from the business and store it somewhere

## Acceptance Criteria
- [x] Engineering, product, and design meet about experience
- [x] Document technical questions for stakeholders at level of detail for that discussion
- [x] Write follow-up tickets for more detailed technical design

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by wesrowe** [comment]
@ryguyk, don't sweat much on pre-refining this. You probably don't have much context to bring to bear yet. But maybe it's worth thinking about what activities you would want to do to make progress on it.

**Comment by ryguyk** [comment]
Meeting of the minds tentatively scheduled for 12/12 at 12:00 ET.

**Comment by ryguyk** [comment]
- Data source
  - QUESTIONS
    - How often is this data updated?
    - How can we access updates? How can we be notified of updates?
- Data storage/transfer
  - Drupal?
  - API (REST or other) vs. JSON file(s) vs. other
  - QUESTIONS
    - What prevents us from hosting a live API?
    - Does Lighthouse play a part? Provide an example?
      - https://developer.va.gov/api-publishing
- Wizard UI
  - State management (Redux vs. React hooks)
  - QUESTIONS
    - Is there an existing wizard pattern that can/should be followed?

**Comment by ryguyk** [comment]
**Biggest takeaway from meeting:**

Can we make use of [this existing API](https://www.huduser.gov/portal/dataset/fmr-api.html)?

**Comment by wesrowe** [comment]
@swirtSJW and @ryguyk, I added my notes to the above. Also, DaveC endorsed the idea of using a HUD API. So the next step is to understand that API – how to get access, what queries does it support, traffic it can support, etc.

**Comment by jilladams** [comment]
Should this ticket become an epic?

**Comment by wesrowe** [comment]
hmm... I'm ambivalent. It could be its own epic. The current epic is scoped to planning, rather than implementation. So a few tech tickets would fit kinda, question-mark?

**Comment by ryguyk** [comment]
Next-step tickets coming out of this discovery:

https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11929
