### ISSUE TITLE
Remove last saved by editor field on KB article template

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#11656]
## Description
I noticed that the new "Last saved by an editor" field is also present on the KB article template however it's at the bottom since the right sidebar doesn't exist on this particular template. This is an odd placement and is this really needed here - do automated processes even touch KB articles? After speaking with @BlakeOrgan he felt it might be best to remove this entirely from this content type if possible.

### Screenshot
[Example article ](https://prod.cms.va.gov/help/outreach-hub/how-to-create-outreach-materials-publications)
![image](https://user-images.githubusercontent.com/106678594/202773428-83ebf931-4696-4e91-a2f1-c30fa1877c5a.png)

## Acceptance Criteria
- [ ] Remove last saved by editor from KB articles
- [ ] UX review

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [x] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by swirtSJW** [comment]
It makes sense to me to have it be "last updated".   As it may be relevant to the confidence of the reader.
We have on occasion had kb artilcles updated by an automated process.  We don't usually, but it could happen if we are fixing a paragraph or bulk changing a word or link.

I also like the idea of us eating our own dogfood on the process.

**Comment by BlakeOrgan** [comment]
If we already have last updated at the top, I don't think we would need it at the bottom too.

<img width="1470" alt="Screen Shot 2022-11-22 at 10 10 51 AM" src="https://user-images.githubusercontent.com/113871419/203364778-ea891b74-fbe9-45d6-9975-e931ba58f82d.png">

**Comment by laflannery** [comment]
@BlakeOrgan This appears to have moved:
![image](https://user-images.githubusercontent.com/106678594/221244247-4f6b0daf-49b4-4792-825c-f926f7ef545e.png)

What are your thoughts on this now? Is this better - do you still feel strongly that this should be removed entirely?

**Comment by EWashb** [comment]
I'm going to close this for now since we have not gotten any feedback on this being an issue
