### ISSUE TITLE
SPIKE Identify the Fragile bits of the Lovell FE that need tests.

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#11651]
As a maintainer of the FE website for Lovell,  I want to make sure the most fragile portions of Lovell are covered by some automated tests, so that regressions are caught before they are released to production.

This will essentially populate the [Lovell Testing Epic](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11650).

## Prioritized list of risks for FE Lovell
- [ ] #11995
- [ ] #11996
- [ ] #11997
- [ ] #11998

## AC s
- [x] A prioritized list of  risk points in the FE of Lovell that should be tested with automated tests.
- [ ] Tickets created for each item in the list assigned to epic https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11650

**Comment by EWashb** [comment]
There's a good bit of cleanup that will need to be considered via FE. What if anything can we do for automated checks for potential regressions? Let's see if there are any other product dependencies.

**Comment by maxx1128** [comment]
For the Switch links on Lovell Tricare and VA, the HTML is there but isn’t rendering for some reason. I don't see any styling that would be hiding it, so my best guess is it's something related to the `va-alert` component.

<img width="1461" alt="Screen Shot 2022-11-21 at 2 49 14 PM" src="https://user-images.githubusercontent.com/10790736/203348332-aac54c40-eab0-421c-a31c-0606484d5bf9.png">

**Comment by dawnpruitt** [comment]
@swirtSJW can you please take a look at Max's feedback? Thank you! :)

**Comment by maxx1128** [comment]
@dawnpruitt Steve already figured out [the issue here](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11686), it was thankfully just a local loading issue.

**Comment by swirtSJW** [comment]
Also unrelated to this spike.  This spike is about proposing tests and creating tickets for them.  Not for actually fixing the existing code.

**Comment by maxx1128** [comment]
Based on my past experience with Lovell and some extra testing, I think these are the most important fragile points to test for:

- [ ] Check both versions of the following pages to confirm they both have switch links and link to the correct page
    - [ ] Main health care page
    - [ ] Locations
    - [ ] Health Services
    - [ ] All Listings Pages (Events, News Releases, Stories)
- [ ] Check that all pages in the "About Lovell Federal" menu subsection do NOT have switch links
- [ ] Check that the location pages have the correct location listings (no VA locations in the Tricare listing, and vice versa)
- [ ] Check that the health services main pages have the correct offered services in the menu subsection (Tricare has several, VA only has one)
- [ ] Confirm both listing pages contain both federal events and events specific to either VA or Tricare.

cc: @swirtSJW

**Comment by swirtSJW** [comment]
Some thoughts around some of these:

-  Confirm both listing pages contain both federal events and events specific to either VA or Tricare.
    - This one is going to need some mocked data to test this logic as we can never guarantee at any point in time that there will be events in Lovell Federal and Lovell - VA
- Check that all pages in the "About Lovell Federal" menu subsection do NOT have switch links
   - I don't know if we can make that assumption.  There is nothing in the CMS or the design intent that says that for every page under about will have somthing in both systems to jump to.
- Check that the health services main pages have the correct offered services in the menu subsection (Tricare has several, VA only has one)
   - This one is hard, as it is hard to say what the source of truth is for "correct"
   - This may also need to use a mocked data approach.

**Comment by JayDarnell** [comment]
@swirtSJW @maxx1128 where do we go from here? Is this something we should maybe schedule a meeting for so we can get multiple minds in the room together and list out the tests together?

**Comment by dawnpruitt** [comment]
@maxx1128 @swirtSJW @JayDarnell - Can we finalize this ticket with the list created by Max and any additional inputs from Jay and Swirt? It looks like we may need some additional discovery around some of the tests.

**Comment by swirtSJW** [comment]
We don't need additional discovery as part of this ticket.  We just need to create the tickets. (second AC)

**Comment by swirtSJW** [comment]
I'll move Max's list  into the top of the ticket and create issues for each.

**Comment by dawnpruitt** [comment]
Thank you Swirt!

**Comment by swirtSJW** [comment]
Closing this.  I created issues from Max's list with some notes where I had thoughts or suggestions.  They are all fully labelled and assigned to the epic.    Some are complete with ACs, others will need some refinement from the team to fully spec with ACs.
