### ISSUE TITLE
Flipper: create flipper for exposing the modal on live homepage

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#11653]
This is necessary whether or not we use Announcement framework.

We do have the option to use an existing flipper, `va_home_preview`. That was instituted for user testing the updated homepage and is not used otherwise. 

## Acceptance criteria
- [ ] Flipper enabled should display the opt-in modal on the va.gov homepage 
- [ ] Flipper disabled should hide the opt-in modal on the va.gov homepage

**Comment by wesrowe** [comment]
@ryguyk, is it possible we don't need a Flipper if we use that Announcement framework you uncovered?

**Comment by jilladams** [comment]
@apisandipas added anote to ticket body that maybe we can use existing flipper `va_home_preview` for this. Will you update with notes here re: whether that does / doesn't work for our case, once you get to this ticket?

**Comment by jtmst** [comment]
> @apisandipas added anote to ticket body that maybe we can use existing flipper `va_home_preview` for this. Will you update with notes here re: whether that does / doesn't work for our case, once you get to this ticket?

No reason not to,  I'm going to update the name and description for clarity.  `va_home_preview_modal` will be the updated name
