### ISSUE TITLE
Static Data Files: Add support for caching - Phase two

### ISSUE THREAD

**Issue by ryguyk** [department-of-veterans-affairs/va.gov-cms#11658]
## Description
This is a follow-up to https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9179. The code implementing the changes in that issue require two separate pushes, as described in [the PR with those changes](https://github.com/department-of-veterans-affairs/content-build/pull/1363). 

This ticket largely amounts to removing some comments that change one line of code. It can be completed and merged once the code in the linked PR is merged and executed (i.e. a content-build is run). The big thing this phase of the process opens up is the creation of static data files on review instances. That piece should be the focus of testing.

## Acceptance Criteria
- [ ] Static data files are generated (from cache) on review instances.

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by wesrowe** [comment]
@ryguyk, should this be done ASAP or is it more of a "sometime in the next few sprints" sort of thing?

**Comment by wesrowe** [comment]
Sprint planning:

- notify dependent teams of possible delay
- notify Team of Teams
