### ISSUE TITLE
Publish Lovell specific KB articles 

### ISSUE THREAD

**Issue by dsinla** [department-of-veterans-affairs/va.gov-cms#11667]
## Description
Once KB articles are written and approved, publish them

## Acceptance Criteria
- [ ] Support team publishes KB articles

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [x] `⭐️ User support`

**Comment by stefaniefgray** [comment]
Ticket previously did not have `Knowledge Base` label

Added myself and @TroyA6 as Assignees so we can track it

**Comment by EWashb** [comment]
@stefaniefgray @TroyA6 has this work been completed? I know Lovell launched a while ago.

**Comment by stefaniefgray** [comment]
@EWashb Apologies for not seeing the notification sooner -- looks totally fine to close! https://prod.cms.va.gov/help/search?keyword=lovell

Closing now
