### ISSUE TITLE
Redirect Request: Camp Lejeune ads - 11/30 target timing

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-cms#11677]
### Instructions
- Requests must be submitted **AT LEAST** 2 weeks in advance.  Some requests take a significant amount of time and coordination to implement, so start the process as soon as you know you will need one. 
- This issue will be used from initial request through implementation to ensure all individuals working on this are notified of status updates.  Please do not create multiple issues to track differnt steps.
- It is your responsibility to notify VA stakeholders as appropriate.  

### Type of request
- [ ] We are retiring or taking down a page and need to redirect the URL (complete redirect section)
- [ ] We are changing the URL of an existing page (complete redirect section)
- [x] We need a custom vanity URL (complete vanity URL section)

### Implementation date
When does this request need to be live: 11.30.22

### Vanity URLs 
| Vanity URL  |  Landing page |
| ---  |  --- |
| https://va.gov/camplejeune  | https://www.va.gov/disability/eligibility/hazardous-materials-exposure/camp-lejeune-water-contamination/ |

**Link to campaign landing page request issue:** N/A - This is a link to an existing page. Mikki and I have discussed this already and are okay with this due to the need for VA to respond to a specific issue around this topic.

### Process, Roles and Responsibilities
- [x] Requesting team: Above information is provided
- [x] Requesting team: All appropriate VA stakeholders are notified as appropriate
- [x] IA: Request is vetted and documented and implementation plan is clear 
- [x] IA: Request is assigned to appropriate team for implementation 
- [ ] Implementation team: Work is complete
- [ ] Implementation team: Validated in production
- [ ] Requesting team: Validates everything is correct in production and closes ticket

**Comment by chri5tia** [comment]
https://github.com/department-of-veterans-affairs/devops/pull/12277

**Comment by jilladams** [comment]
Verified in prod!
