### ISSUE TITLE
Request for new or update to existing KB article : Admin-specific Lovell instructions for maintaining Lovell sites 

### ISSUE THREAD

**Issue by dsinla** [department-of-veterans-affairs/va.gov-cms#11689]
## Background context
**What is the request for?**
There are special considerations for Lovell TRICARE-only facilities that are exceptions to typical facilities. Though new facilities are rare, the special handling should be documented from the CMS support/admin perspective.

**Person and team of requester:** 
- David Shannon, Facilities 

**Priority or deadline for request**

  Choose either Deadline or a priority:
  
- [ ] Deadline: [name the deadline here]
- [ ] Priority:
  - [ ] Critical - Without this, there is a large negative impact on the majority of editors causing negative consequences within the CMS; Should be completed as soon as possible
  - [ ] High - Without this, there is negative impact on some editors causing negative consequences within the CMS; should be completed within the current sprint
  - [ ] Medium - Without this, there is confusion for editors but not causing negative consequences within the CMS; Should be completed within the next 1-2 sprints
  - [x] Low - This is not currently causing confusion for many editors but would be a nice to have or is something that may be more impactful in the future; Should be completed within the next 3-4 sprints
  

**Is the article associated with an ongoing product or feature update?**
- [x] Yes https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9655
- [ ] No

  
## If requesting a new article:

**Audience:**
Who is this intended for? Who would need this information? (i.e. All editors, only editors for a particular product, Internal use only, etc.)
- CMS Support/Admin

**Related KB articles, if applicable:** 
- [If you know that related KB articles already exist, link them here]

  
**Any other relevant documentation, if applicable:** 
- [for example, could be the VA content style guide]

## Process
1. Determine who the audience is
2. Determine the scope of the article

Then next ticket is to create the article  

1. Update KB article tracker to indicate that the article has been requested and is in progress
2. Draft article content 
3. Sitewide CMS team will review for formatting and writing style guidelines
10. Helpdesk team will review for functionality and editorial tone
11. Publish
12. Update KB article tracker to indicate that the article has been published

## Acceptance Criteria
- [ ] Article is created using [KB content style guidelines](https://va-gov.atlassian.net/wiki/spaces/VAGOV/pages/1771831299/Knowledge+Base+content+style) 
- [ ] Article is reviewed by Sitewide CMS
- [ ] Article is reviewed by Helpdesk
- [ ] Article posted to KB 
- [ ] Impacts on other KB articles have been considered and any necessary changes have been made
- [ ] Once published, the person requesting the article has been notified

**Comment by stefaniefgray** [comment]
**Existing KB article about how to add a new VAMC facility to your system:** https://prod.cms.va.gov/help/vamc/about-locations-content-for-vamcs/how-do-i-add-a-facility-to-my-health-care-system

Note that this article is aimed at existing content editors for them to follow the listed instructions -- it is NOT aimed at our admin team, as this ticket says the new Lovell facility-addition article should be

**Comment by ryguyk** [comment]
@stefaniefgray @TroyA6 I've created a few different KBs to accommodate this request. Effectively, it's a [top-level KB](https://prod.cms.va.gov/help/vamc/managing-lovell-sites-as-a-content-admin) that matches an[ existing structure](https://prod.cms.va.gov/help/vamc/managing-vamc-sites-as-a-content-admin), and then three linked KBs for the individual tasks/information that are useful to content admins.

**Comment by laflannery** [comment]
I updated the 3 articles for format. My only suggestion would be on the [TRICARE name article](https://prod.cms.va.gov/help/vamc/how-to-add-or-edit-tricare-specific-service-names)
- Under the Add heading, step 6 we have "In the VAMC field group, fill out the fields as you would for any service." but this isn't entirely clear - what if I don't know how to fill these out?  I also have a question on the Description vs TRICARE description - which do I fill out for a TRICARE specific service?

I think we should expand on this a bit more - or have we identified a place where we should have a "How to make a regular service for all VAMCs" article and then we can link over to it for this article?

**Comment by ryguyk** [comment]
@laflannery Thanks for the feedback. I agree what I have there is incomplete. As I am uncovering exactly what to include here, it's not immediately obvious to me what level of granularity is needed in these places. Since this is intended for admins (i.e. Help Desk), I was writing with a little less hand holding compared to if the audience were editors. That said, I wrote some of this to just get it on paper, knowing that it should be updated per quality feedback just like this. I'm happy to update as needed.

**Comment by TroyA6** [comment]
Although I agree with @ryguyk about writing with less hand holding, I can also see @laflannery 's point - the need for a little more guidance for step 6 -- as a newer HD member, I appreciate the additional information - it just gives me a little more confidence :)

**Comment by ryguyk** [comment]
@laflannery I made the requested changes. If all looks good to you and @TroyA6 and @stefaniefgray , I'm going to consider this completed! Thanks to all of you for your help. Laura, thanks for the heavy editing of my work to comply with formatting guidelines.

**Comment by laflannery** [comment]
Looks great! Are these allowed to be published once approved by Helpdesk? Or are they tied to a specific Lovell launch and should remain in draft until then?

**Comment by ryguyk** [comment]
That is a question I'll defer to somebody else. 

I'll add my two cents, though. I don't necessarily see why they shouldn't be published. I was, however, wondering about whether we need to somehow identify these as being specifically for Content Admin. We don't have a lot of KB articles directed at that audience, so I don't know how accustomed editors might be to filtering out things that might not apply to them.
