### ISSUE TITLE
[cms-ci] site rebuilds failing with `drush $DRUSH_ALIAS cr Drupal\Core\Extension\Exception\UnknownExtensionException: in /var/aegir/projects/cms/listings/docroot/core/lib/Drupal/Core/Extension/ExtensionList.php:265`

### ISSUE THREAD

**Issue by ElijahLynn** [department-of-veterans-affairs/va.gov-cms#1168]
Seeing this error on a specific CI build:

> drush $DRUSH_ALIAS cr Output:/path/to/fileDrupal\Core\Extension\Exception\UnknownExtensionException: The       [error]
> profile headless_lightning does not exist. in
> /var/aegir/projects/cms/listings/docroot/core/lib/Drupal/Core/Extension/ExtensionList.php:265

**Comment by kevwalsh** [comment]
@ElijahLynn i got another one here: http://devshop.cms.va.gov/node/14254

**Comment by ElijahLynn** [comment]
This was resolved, in a few other PRs but don't know which ones offhand, there were a lot of different errors that stemmed from the underlying issue.
