### ISSUE TITLE
Redirect Request: VHA /healthbenefits redirects - 11/30 target

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-cms#11680]
### Instructions
- Requests must be submitted **AT LEAST** 2 weeks in advance.  Some requests take a significant amount of time and coordination to implement, so start the process as soon as you know you will need one. 
- This issue will be used from initial request through implementation to ensure all individuals working on this are notified of status updates.  Please do not create multiple issues to track differnt steps.
- It is your responsibility to notify VA stakeholders as appropriate.  

### Type of request
- [x] We are retiring or taking down a page and need to redirect the URL (complete redirect section)
- [ ] We are changing the URL of an existing page (complete redirect section)
- [ ] We need a custom vanity URL (complete vanity URL section)

### Implementation date
When does this request need to be live: November 30, 2022 or before

### Redirects 

2 notes on these redirects:

- Some of these redirects are for directory levels (like /healthbenefits/access). We need the directory URL redirected, but the directory-level redirect should only redirect that page and not its child pages so we can redirect those child pages 1:1.
- All redirects need to work for all casing variations in all segments of the URLs. For example, https://www.va.gov/healthbenefits/vadip/ also needs to redirect https://www.va.gov/HEALTHBENEFITS/vadip/, https://www.va.gov/healthbenefits/VADIP/, and https://www.va.gov/HEALTHBENEFITS/VADIP/

| Current URL  |  Redirect Destination or New URL |
| ---  |  --- |
| https://www.va.gov/healthbenefits/vadip/ | https://www.va.gov/health-care/about-va-health-benefits/dental-care/dental-insurance/ |
| https://www.va.gov/healthbenefits/access/ | https://www.va.gov/health-care/ |
| https://www.va.gov/healthbenefits/access/mental_health_care.asp | https://www.va.gov/health-care/health-needs-conditions/mental-health/ |
| https://www.va.gov/healthbenefits/access/health_promotion.asp | https://www.va.gov/health-care/wellness-programs/ |
| https://www.va.gov/healthbenefits/access/kiosks.asp | https://www.va.gov/resources/how-to-check-in-with-your-smartphone-for-some-va-appointments/ |
| https://www.va.gov/healthbenefits/access/ancillary_services.asp | https://www.va.gov/health-care/about-va-health-benefits/ |
| https://www.va.gov/healthbenefits/access/specialty_care_services.asp | https://www.va.gov/health-care/about-va-health-benefits/ |
| https://www.va.gov/healthbenefits/access/active_duty.asp | https://www.va.gov/health-care/eligibility/active-duty/ |
| https://www.va.gov/healthbenefits/access/preventative_care_services.asp | https://www.va.gov/health-care/wellness-programs/ |
| https://www.va.gov/healthbenefits/access/family_members.asp | https://www.va.gov/health-care/family-caregiver-benefits/ |
| https://www.va.gov/healthbenefits/access/inpatient_care_services.asp | https://www.va.gov/health-care/about-va-health-benefits/  |
| https://www.va.gov/healthbenefits/cost/ | https://www.va.gov/health-care/about-va-health-benefits/cost-of-care/ |
| https://www.va.gov/healthbenefits/gateway/combat_vets.asp | https://www.va.gov/health-care/eligibility/active-duty/ |
| https://www.va.gov/healthbenefits/online/ | https://www.va.gov/health-care/apply/application/introduction |

### Vanity URLs 
Vanity URL  |  Landing page
---  |  ---
requested URL | landing page URL

**Link to campaign landing page request issue:**

### Process, Roles and Responsibilities
- [x] Requesting team: Above information is provided
- [x] Requesting team: All appropriate VA stakeholders are notified as appropriate
- [x] IA: Request is vetted and documented and implementation plan is clear 
- [x] IA: Request is assigned to appropriate team for implementation 
- [ ] Implementation team: Work is complete
- [ ] Implementation team: Validated in production
- [ ] Requesting team: Validates everything is correct in production and closes ticket

**Comment by chri5tia** [comment]
PR https://github.com/department-of-veterans-affairs/devops/pull/12277

**Comment by chri5tia** [comment]
PR: https://github.com/department-of-veterans-affairs/devops/pull/12277

**Comment by chri5tia** [comment]
https://github.com/department-of-veterans-affairs/devops/pull/12277

**Comment by jilladams** [comment]
@chri5tia reopening. We have 3 redirects with unexpected behavior: the redirects were implemented in code in a way that seems logical, but actual end landing page has `healthcare/access` inserted in the path, resulting in a 404 in prod. (That'll teach me to forego testing with a staging deploy for redirects.)

## broken redirects
| Current URL  |  Incorrect (live 404s) | Correction to make | 
| ---  |  --- | --- |
| https://www.va.gov/healthbenefits/access/ancillary_services.asp | https://www.va.gov/healthbenefits/access/health-care/about-va-health-benefits/ -- [**line 25**](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/revproxy-vagov/vars/redirects.yml#L25) | https://www.va.gov/health-care/about-va-health-benefits/ |
| https://www.va.gov/healthbenefits/access/active_duty.asp | https://www.va.gov/healthbenefits/access/health-care/eligibility/active-duty/ -- [**line 86**](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/revproxy-vagov/vars/redirects.yml#L86)| https://www.va.gov/health-care/eligibility/active-duty/ |
| https://www.va.gov/healthbenefits/access/family_members.asp | https://www.va.gov/healthbenefits/access/health-care/family-caregiver-benefits/ -- [**line 94**](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/revproxy-vagov/vars/redirects.yml#L94)| https://www.va.gov/health-care/family-caregiver-benefits/ |

## possible culprit?
spitballing, but does https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/revproxy-vagov/vars/redirects.yml#L17 maybe somehow have an impact here?

**Comment by chri5tia** [comment]
```
🐾 va.gov-cms: curl -sLIXGET https://www.va.gov/healthbenefits/access/ancillary_services.asp                                                 14:07
HTTP/1.1 301 Moved Permanently
Date: Wed, 30 Nov 2022 22:07:21 GMT
Content-Type: text/html
Connection: keep-alive
Location: health-care/about-va-health-benefits/
Content-Security-Policy-Report-Only: script-src 'self' 'unsafe-inline' 'nonce-S6XUhmwfWAxHwDBtYvemQmiupaafzXOu' http://www.google-analytics.com https://*.uservoice.com https://dap.digitalgov.gov https://designsystem.digital.gov https://maps.googleapis.com https://standards.usa.gov https://www.google-analytics.com https://www.googletagmanager.com https://tagmanager.google.com 'unsafe-eval' https://optimize.google.com https://gateway.foresee.com https://resources.digital-cloud-gov.voice.medallia.com https://resource.digital.voice.va.gov https://prod-va-gov-assets.s3-us-gov-west-1.amazonaws.com https://www.youtube.com https://*.ytimg.com https://cdn.botframework.com 'strict-dynamic' nonce-S6XUhmwfWAxHwDBtYvemQmiupaafzXOu; img-src 'self' data: blob: https://*.gstatic.com https://api.mapbox.com https://www.google-analytics.com https://www.googletagmanager.com https://stats.g.doubleclick.net https://*.va.gov https://optimize.google.com https://gateway.foresee.com https://static.foresee.com https://cdn-prod.kampyle.com https://prod-va-gov-assets.s3-us-gov-west-1.amazonaws.com https://s3-us-gov-west-1.amazonaws.com https://ok6static.oktacdn.com https://dvp-oauth-application-directory-logos.s3-us-gov-west-1.amazonaws.com https://i.ytimg.com ; frame-ancestors 'none' ; manifest-src 'none' ; default-src 'self' ; frame-src https://dap.digitalgov.gov https://resource.digital.voice.va.gov https://www.googletagmanager.com https://prod-va-gov-assets.s3-us-gov-west-1.amazonaws.com https://www.youtube.com ; child-src https://*.uservoice.com https://www.googletagmanager.com https://www.youtube.com https://optimize.google.com https://resources.digital-cloud-gov.voice.medallia.com ; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://tagmanager.google.com https://optimize.google.com https://fonts.googleapis.com https://gateway.foresee.com https://medallia.s3.amazonaws.com https://prod-va-gov-assets.s3-us-gov-west-1.amazonaws.com https://s3-us-gov-west-1.amazonaws.com ; connect-src 'self' http://localhost:4000 https://*.va.gov https://api.mapbox.com https://events.mapbox.com https://www.google-analytics.com https://stats.g.doubleclick.net http://*.vetsgov-internal https://secure.login.gov https://prod-va-gov-assets.s3-us-gov-west-1.amazonaws.com https://prod-va-gov-maintenance-windows.s3-us-gov-west-1.amazonaws.com https://analytics.foresee.com https://brain.foresee.com https://survey.foreseeresults.com https://device.4seeresults.com https://health.foresee.com https://gateway.foresee.com https://feedback.digital-cloud-gov.voice.medallia.com https://raw.githubusercontent.com wss://northamerica.directline.botframework.com https://northamerica.directline.botframework.com https://search.usa.gov https://rum.browser-intake-ddog-gov.com ; object-src 'self' blob: ; media-src 'none' ; font-src 'self' data: https://fonts.gstatic.com https://gateway.foresee.com https://medallia.s3.amazonaws.com https://prod-va-gov-assets.s3-us-gov-west-1.amazonaws.com ; block-all-mixed-content  ; form-action 'self' https://vicbdc.vba.va.gov https://vaww.vicbdc.ppd.vba.va.gov https://secure.login.gov https://feedback.digital-cloud-gov.voice.medallia.com ; base-uri http://*.vetsgov-internal https://*.va.gov https://optimize.google.com ;
Referrer-Policy: no-referrer-when-downgrade
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; report=/csp-report
Transfer-Encoding: chunked

HTTP/1.1 404 Not Found
Date: Wed, 30 Nov 2022 22:07:22 GMT
Content-Type: text/html
Connection: keep-alive
x-amz-id-2: aVqDfLAxVLlwRTuDabD53sk+RJ3OjuwYZWuNtI380d7t9XTLQ/c1Rwh4y3Spr/3n0UYNARL6HLU=
x-amz-request-id: DQ4FCMBAJC74GESM
Cache-Control: public, no-cache
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
Transfer-Encoding: chunked
```

**Comment by dsasser** [comment]
The issue is of 'relative' redirects. Each of the non-functional redirects share the same trait: they are missing a forward slash preceding the dest:

```
  - src: ^/healthbenefits/access/active_duty.asp$
    dest: health-care/eligibility/active-duty/
    matcher: "~*"

  - src: ^/healthbenefits/access/ancillary_services.asp$
    dest: health-care/about-va-health-benefits/
    matcher: "~*"

  - src: ^/healthbenefits/access/family_members.asp$
    dest: health-care/family-caregiver-benefits/
    matcher: "~*"
``` 

Without the preceding "/" results in a "relative redirect" by nginx.
