### ISSUE TITLE
Review existing design documentation for Income Limits

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#11695]
## Description
As the UX Lead, I need to understand the design work that has been done so far on Income Limits so I can prioritize how design resources are allocated to it during Q4

## Acceptance Criteria
- [x] Read all the things
  - [x] [Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/income-limits-app)
  - [x] [Existing website](https://www.va.gov/healthbenefits/apps/explorer/AnnualIncomeLimits/HealthBenefits)
  - [x] [Mural of Existing App](https://app.mural.co/t/vagov6717/m/vagov6717/1657807571797/ee2497db0a9c637538f51e38546ffe3eaea508c0?sender=u20829d1b64855e281dde2585)
  - [x] [Research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/income-limits-app/research/research-plan.md) 
  - [x] [Conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/income-limits-app/research/conversation-guide.md)
  - [x] [Design Intent](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/income-limits-app/research/design-intent-notes.md)
  - [x] [Research Repo ticket](https://github.com/department-of-veterans-affairs/va.gov-research-repository/issues/168)
  - [x] Review #11372 
- [x] Have a meeting with Wes, DaveP and Jill to discuss my understand and craft a path forward

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by jilladams** [comment]
Hiya @thejordanwood checking in here. I know you and @wesrowe  were going to meet on Income limits - wondering if you have any questions / if this ticket is feeling manageable among other paperwork tasks this week. @wesrowe also wondering if the goal is to kick off prototype design in next sprint?

**Comment by thejordanwood** [comment]
@jilladams Yes, this is feeling manageable! Meeting with Wes this week has been extremely helpful and I believe we should be able to kick of prototyping next sprint.

**Comment by wesrowe** [comment]
We have a ticket for next sprint's activities @jilladams, will refine today
