### ISSUE TITLE
Last-touched-by-an-editor field not always reflecting updates

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-cms#11698]
## Description
See e.g. this node: https://prod.cms.va.gov/san-diego-health-care/locations/oceanside-va-clinic

![Screen Shot 2022-11-23 at 12 14 37 PM](https://user-images.githubusercontent.com/1318579/203612102-06dfc235-ba21-437f-a797-134fba0a021f.png)

We should probably see a last-updated date here of November 23 2022 8:34am.

## Acceptance Criteria
- [ ] Last-touched-by-an-editor field updates reliably when the node is updated by a human.

**Comment by edmund-dunn** [comment]
I identified the issue and have a fix.
