### ISSUE TITLE
CMS: VAMC System Banner Alert with Situation Updates do not work for Lovell systems

### ISSUE THREAD

**Issue by JayDarnell** [department-of-veterans-affairs/va.gov-cms#11726]
## Describe the defect
The existing logic to handle the placement of Banner Alerts with Situation Updates does not work with Lovell. When we attempt to create one of these nodes we do not have the option to display the Banner on the Lovell - VA or Lovell - TRICARE subsystems. These systems are not listed as options ( see comments on #11636 )

## To Reproduce
1. Create a new VAMC System Banner Alert with Situation Updates node
2. For the field **Pages for the following VAMC systems** select **Lovell Federal health care**
3. For the section select **Lovell Federal health care**
4. Be sure to supply values for all additional required fields
5. Save the node
6. Trigger a content release: /admin/content/deploy
7. When the content release has finished, check the following pages on the front end: **/lovell-federal-tricare-health-care/** and **/lovell-federal-va-health-care/**
8. The Banner alert with situation updates is not present

## AC / Expected behavior
CMS:
- Editors should have the option to add one of these banners to Lovell Federal VA health care
- Editors should have the option to add one of these banners to Lovell Federal TRICARE health care
- The list of systems to choose from should be alpha sorted to make the selection process easier
Front End:
- A banner added to Lovell VA should show up on Lovell VA
- A banner added to Lovell TRICARE should show up on Lovell TRICARE

I suspect adding Lovell VA and Lovell TRICARE to the list of available systems will fix the issue with these not showing for those individual systems on the front end. 

## Screenshots
![Screen Shot 2022-11-23 at 4 24 44 PM](https://user-images.githubusercontent.com/21045418/204313312-32a8e866-ac92-4c16-b917-e610421d9429.png)

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by JayDarnell** [comment]
The checkboxes for selecting a VAMC system come from the following view: /admin/structure/views/view/vamc_operating_statuses

<img width="1761" alt="Screen Shot 2022-11-30 at 1 40 52 PM" src="https://user-images.githubusercontent.com/21045418/204881666-28a19cfd-3c96-4102-ba84-20297326e5bf.png">

For some reason this view is based on VAMC System Operating Status nodes and then grabs the referenced VAMC system rather than grabbing a list of published system nodes directly. I suspect there was a good reason for building it this way.

Once the VAMC System Operating Status pages were published for both the VA and TRICARE Lovell subsystems these options were available in the select list: 

<img width="1758" alt="Screen Shot 2022-11-30 at 1 46 36 PM" src="https://user-images.githubusercontent.com/21045418/204882696-ffa6fdd9-a5c9-428a-a5a4-5626315a7954.png">

I am working to fix the ordering issue with the view used to build this select list now but should this remain based on VAMC System Operating Status nodes or should I create a new view to use here based directly on the VAMC System health service nodes @swirtSJW

**Comment by swirtSJW** [comment]
Jay I think it makes sense to keep it as it is referencing the operating status page since that's where the situation updates appear.
