### ISSUE TITLE
Add a couple of exceptions to node link tests

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#1172]
**Describe the defect**

**To Reproduce**
1. Go to /node/37
2. See broken link reported for [VA appointment portal](https://eauth.va.gov/accessva/?cspSelectFor=mass)

1. Go to prod.cms.va.gov/health-care/health-needs-conditions/mental-health.
2. See broken link for [Military OneSource](https://www.militaryonesource.mil/mental-health)

**Expected behavior**
These reports should not be reported as broken. 

**Screenshots**
![image](https://user-images.githubusercontent.com/643678/75941438-aca9cc80-5e5d-11ea-9812-6a1a49d9814d.png)

**Comment by kevwalsh** [comment]
@swirtSJW  I went ahead and added this to Sprint 2 and estimated as a 1. 

Just a thought: should we allow this configuration to exist as content? if suppose that would treat ALL node link report configuration as content?

**Comment by swirtSJW** [comment]
@kevwalsh We could exclude just that one field, or a few fields from being part of the config.   I am not a big fan of having unique exceptions... but I can also see the speed benefit of it.    I do think there is benefit in actually checking the link out more deeply.   Like in this case, Rachel says the link works, but didn't catch that it actually redirects from
 https://access.va.gov/accessva/?cspSelectFor=mass
to 
https://eauth.va.gov/accessva/?cspSelectFor=mass

In looking deeper that system is blocking header only requests that are used in link checking.  It is  returning a  405 response  to our request.

**Comment by swirtSJW** [comment]
Investigated https://www.militaryonesource.mil/health-wellness/mental-health   It too is denying a header only curl.
I created this d.o issue that would resolve them both.  https://www.drupal.org/project/node_link_report/issues/3118060

**Comment by swirtSJW** [comment]
I just pushed up a fix for this https://www.drupal.org/project/node_link_report/issues/3118060
and triggered a release https://www.drupal.org/project/node_link_report/releases/8.x-1.13
