### ISSUE TITLE
Reënable va/tests/status-error test.

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-cms#11724]
## Description
As of today (11/28), PHP 7.4 is EOL.  We're still evaluating PHP 8.1, but `va/tests/status-error` is starting to fail on every PR.

I'm disabling this test for the time being to reduce confusion and friction in the PR process.  The following should indicate the steps necessary to reënable the test once PHP 8.1 is live in all environments.

## Acceptance Criteria
- [ ] Add `va/tests/status-error` to the branch protection rules [here](https://github.com/department-of-veterans-affairs/va.gov-cms/settings/branch_protection_rules/6199183)
- [x] Uncomment `- va/tests/status-error` from the `default` task in `/tests.yml`.
- [x] Replace `va/tests/status-error` in the [set-tugboat-tests-pending](https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/.github/workflows/set-tugboat-tests-pending.yml) GitHub workflow.

**Comment by TheBoatyMcBoatFace** [comment]
The 8.1 upgrade has been completed.

**Comment by TheBoatyMcBoatFace** [comment]
Reopening, @ndouglas
