### ISSUE TITLE
FE: VAMC System Banner Alert with Situation Updates do not work for Lovell systems

### ISSUE THREAD

**Issue by JayDarnell** [department-of-veterans-affairs/va.gov-cms#11727]
## Describe the defect
This issue will need to be refined as work in #11726 is completed. For now this is a placeholder. We simply want to be sure that VAMC System Banner Alert with Situation Updates nodes are displayed properly for Lovell systems... 

## Additional context
Add any other context about the problem here. Reach out to the Product Managers to determine if it should be escalated as critical (prevents users from accomplishing their work with no known workaround and needs to be addressed within 2 business days).

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Defect")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS workstream (orange) (not needed for bug tickets)
- [ ] CMS-supported product (black)

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by davidmpickett** [comment]
@JayDarnell to verify if this is still an issue

**Comment by JayDarnell** [comment]
This is no longer an issue. The work performed in #11726, which consisted of a content change (adding operating status pages for Lovell - VA and Lovell - TRICARE) and a small modification to the view used in the reference field (alpha sort), has made it so these are working. When a VAMC System Banner Alert with Situation Updates node is created, if we need it to show up in both Lovell - VA and Lovell - TRICARE we simply choose both checkboxes as the following screenshot demonstrates:

<img width="1753" alt="Screenshot 2022-12-19 at 11 33 20 AM" src="https://user-images.githubusercontent.com/21045418/208474885-2af3dc09-558c-4a6a-bef2-1f70374cda04.png">
