### ISSUE TITLE
CMS sitewide alerts not visible to editors

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#11736]
## Describe the defect
Admins are able to see sitewide alerts.
However, our shields and deploy warnings are not visible to everyone else.

Slack conversation https://dsva.slack.com/archives/CDHBKAL9W/p1669675816587709

This is incorrectly permed
It should be set for anonymous AND authenticated
![image](https://user-images.githubusercontent.com/5752113/204650526-dc35f5d1-6d2c-4224-af40-dd7d1965e2a7.png)

## To Reproduce
1. As an admin set a sitewide alert to display
2. Logout and login as a non-admin
3. See that you see no sitewide alert

## AC / Expected behavior
Sitewide alerts must be visible to ALL users!

 ## Additional context
Add any other context about the problem here. Reach out to the Product Managers to determine if it should be escalated as critical (prevents users from accomplishing their work with no known workaround and needs to be addressed within 2 business days).

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Defect")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS workstream (orange) (not needed for bug tickets)
- [ ] CMS-supported product (black)

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [x] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by swirtSJW** [comment]
QA on this one missed calling out testing as anyone other than admin
https://github.com/department-of-veterans-affairs/va.gov-cms/pull/9723
It replaced this PR which DID have a callout to test as kittywalsh.
https://github.com/department-of-veterans-affairs/va.gov-cms/pull/9079  :(

**Comment by ndouglas** [comment]
This should have behavioral tests, too.  Shouldn't be hard to add, just a couple of lines -- but if it happens at the same time as Behat or PHPUnit functional tests run, that might cause spurious test failures there.
