### ISSUE TITLE
Redirect Request for Vet Centers live as of 11/23/22 - no deadline

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-cms#11730]
### Instructions
- Requests must be submitted **AT LEAST** 2 weeks in advance.  Some requests take a significant amount of time and coordination to implement, so start the process as soon as you know you will need one. 
- This issue will be used from initial request through implementation to ensure all individuals working on this are notified of status updates.  Please do not create multiple issues to track differnt steps.
- It is your responsibility to notify VA stakeholders as appropriate.  

### Type of request
- [ ] We are retiring or taking down a page and need to redirect the URL (complete redirect section)
- [ ] We are changing the URL of an existing page (complete redirect section)
- [ ] We need a custom vanity URL (complete vanity URL section)

### Implementation date
When does this request need to be live: 

### Redirects 
Current URL  |  Redirect Destination or New URL
---  |  ---
www.va.gov/find-locations/facility/vc_0866MVC | https://www.va.gov/birmingham-vet-center/
www.va.gov/find-locations/facility/vc_0739V | https://www.va.gov/birmingham-vet-center/
https://www.va.gov/directory/guide/facility.asp?ID=392&dnum=All | https://www.va.gov/birmingham-vet-center/
https://www.va.gov/directory/guide/keystaff.cfm?id=392 | https://www.va.gov/birmingham-vet-center/
www.va.gov/find-locations/facility/vc_0307V | https://www.va.gov/san-juan-vet-center/
https://www.va.gov/directory/guide/facility.asp?ID=574&dnum=1 | https://www.va.gov/san-juan-vet-center/
https://www.va.gov/directory/guide/keystaff.cfm?id=574 | https://www.va.gov/san-juan-vet-center/
www.va.gov/find-locations/facility/vc_0221V | https://www.va.gov/columbus-oh-vet-center/
https://www.va.gov/directory/guide/facility.asp?ID=420&dnum=All | https://www.va.gov/columbus-oh-vet-center/
https://www.va.gov/directory/guide/keystaff.cfm?id=420 | https://www.va.gov/columbus-oh-vet-center/

### Vanity URLs 
Vanity URL  |  Landing page
---  |  ---
requested URL | landing page URL

**Link to campaign landing page request issue:**

### Process, Roles and Responsibilities
- [ ] Requesting team: Above information is provided
- [ ] Requesting team: All appropriate VA stakeholders are notified as appropriate
- [ ] IA: Request is vetted and documented and implementation plan is clear 
- [ ] IA: Request is assigned to appropriate team for implementation 
- [ ] Implementation team: Work is complete
- [ ] Implementation team: Validated in production
- [ ] Requesting team: Validates everything is correct in production and closes ticket

**Comment by chri5tia** [comment]
https://github.com/department-of-veterans-affairs/devops/pull/12333

**Comment by jilladams** [comment]
Verified in prod.
