### ISSUE TITLE
Redirect uppercase instances of http://www.va.gov/vre - Dec target

### ISSUE THREAD

**Issue by heyjoni** [department-of-veterans-affairs/va.gov-cms#11738]
### Type of request
- [ ] We are retiring or taking down a page and need to redirect the URL (complete redirect section)
- [ ] We are changing the URL of an existing page (complete redirect section)
- [x] We need a custom vanity URL (complete vanity URL section) - there's already an existing redirect for a vanity URL but it only works in lower case. We'd like to make sure uppercase and all combinations of cases will redirect.

### Implementation date
When does this request need to be live: ASAP

### Vanity URLs 
Vanity URL  |  Landing page
--- |  ---
http://www.va.gov/VRE (and all combinations of cases*) | https://www.va.gov/careers-employment/vocational-rehabilitation/

*There's already a correct redirect for all lower case

### Process, Roles and Responsibilities
- [x] Requesting team: Above information is provided
- [x] Requesting team: All appropriate VA stakeholders are notified as appropriate
- [x] IA: Request is vetted and documented and implementation plan is clear 
- [x] IA: Request is assigned to appropriate team for implementation 
- [ ] Implementation team: Work is complete
- [ ] Implementation team: Validated in production
- [ ] Requesting team: Validates everything is correct in production and closes ticket

**Comment by jilladams** [comment]
@heyjoni does ASAP mean when we get to it, e.g. in next sprint, or does that mean right away & we should inject into our current sprint?

**Comment by bethpottsVADEPO** [comment]
@jilladams This request originally came to me, so I can help with timing. I think the next sprint should be fine--no need to reprioritize your current sprint. Could you tell me when this work might be done in the next sprint, so I can make sure that will work for the stakeholder?

**Comment by jilladams** [comment]
It's hard to say til we've done sprint planning. Can I let you know on Monday? Or: we can just commit to doing this first thing in next sprint and trying to get it in before next Wed's deploy of redirects.

**Comment by bethpottsVADEPO** [comment]
I just communicated with the stakeholder about this, and he said if it gets done sometime in December, all's good. So no rush! Thanks so much for fitting it into an upcoming sprint.

**Comment by chri5tia** [comment]
https://github.com/department-of-veterans-affairs/devops/pull/12333

**Comment by jilladams** [comment]
Verified in prod.
