### ISSUE TITLE
EDU Wizard: Rewrite E2E tests

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#11749]
## Description

As a Developer, I want e2e tests to correspond clearly to discrete use cases so that the tests document the code and can be easily understood and maintained.

## Acceptance Criteria
- [ ] e2e tests cover discrete use cases, not all in one test that doubles back on itself

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by jilladams** [comment]
EDU team now owns this wizard. Closing.
