### ISSUE TITLE
Tugboat 8.1 base preview will not build

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#11743]
## Acceptance Criteria
- [ ] Testable_Outcome_X
- [ ] Testable_Outcome_Y
- [ ] Testable_Outcome_Z
- [ ] Requires design review

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by ElijahLynn** [comment]
This was fixed in https://github.com/department-of-veterans-affairs/va.gov-cms/commit/fc6b99206c48aa01f7994e78becd6a5da1016feb which I pushed earlier. Discussion here > https://dsva.slack.com/archives/C02HX4AQZ33/p1669846055788959?thread_ts=1669672986.328609&cid=C02HX4AQZ33.
