### ISSUE TITLE
CMS: Explore behavior where banners can be published but not assigned to a system. 

### ISSUE THREAD

**Issue by dsinla** [department-of-veterans-affairs/va.gov-cms#11742]
## Describe the defect
There are currently  ~100 banner alerts for "Website coming soon" that are published, but that are not assigned to a system (NOTE, I've only checked a few, the assumption is that this is the case for all.)  This shouldn't be possible since the assigned system is a required field. 

> Hunch from Swirt:
> Then my next hunch is that it is actually set, but something about the winnower or the view is not making it appear as set..... though if it were truly set, it would show on the FE.   This definitely needs a ticket for more investigation.   There is some logic on that select list that disables items that are not within your section.  It may run afoul for admins who have no section.

## To Reproduce
A couple examples:

http://prod.cms.va.gov/va-hines-health-care/vamc-banner-alert/2021-09-22/website-coming-soon-not-the-official-va-hines-health-care-website

http://prod.cms.va.gov/va-pittsburgh-health-care/vamc-banner-alert/2021-04-07/website-coming-soon-not-the-official-va-houston-health-care-website

## AC 
- [ ] A reason for this behavior is determined, and a fix is proposed if appropriate. 

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Defect")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS workstream (orange) (not needed for bug tickets)
- [ ] CMS-supported product (black)

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by swirtSJW** [comment]
I figured out how they did it.
They used Bulk Edit
![image](https://user-images.githubusercontent.com/5752113/204855860-7ce62b12-1771-4e64-a128-6ab279d8e9bc.png)
 
This way you can clear out the values of the field AND it bypasses node validation.
and unchecked "create new revision"  So the revision history  does not reflect the change at all.

I just set the location manually, saved it, then went to bulk edit and removed the value... and there is no evidence in the revision history
![image](https://user-images.githubusercontent.com/5752113/204856527-fd19ee66-ed05-47f1-baea-536f873a998b.png)


VAMC upgrage team made use of Bulk edit alot.

**Comment by swirtSJW** [comment]
Closing this as mystery solved.
