### ISSUE TITLE
Linky 404 report

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#11744]
## Description
Linky is able to provide a 404 report of broken links. By turning this on, we could provide a useful tool for the Sitewide Content team that could help to surface broken links and assist them in fixing these proactively rather than having to find out from a Veteran or another source that there is a broken link on their VA.gov page.

## Acceptance Criteria
- [ ] ~Turn on the 404 report tool~
- [ ] ~Configure the tool sensibly (raise questions if you have them about what is sensible)~
- [ ] Configure link checking to run  Linkychecker (/admin/config/linkychecker) to run on cron with a crawl interval of 7 days.
- [ ] Clone our existing Linky View display  "Managed links"  (/admin/content/linky) to "External Link Status"  (/admin/content/linky/status) 
  - [ ] title: External Link Status
  - [ ] machine name: external_link_status
  - [ ] access: admin only
  - [ ] caption: External link status results
  - [ ] Add  field Linky status  or whatever it is called by Linkychecker module
  - [ ] Add filter if one exists, to filter by link status.
  - [ ] Add field error (boolean)
  - [ ] Add field Error message
  -  ignore the normally Views Style guide requirements as this is just to see if the link checker is going to have too many false alarms, or if it gives us meaningful information.

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [x] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by swirtSJW** [comment]
Apparently, Linkychecker does not create a View of its own but adds the ability to have the status as a field into the View.
![image](https://user-images.githubusercontent.com/5752113/207128777-241ed2dc-e552-447e-ac90-45151f85e311.png)
I am updating the AC's to reflect this.
