### ISSUE TITLE
Limit VAMC System Banner Alert with Situation Updates to one, and add character limit

### ISSUE THREAD

**Issue by dsinla** [department-of-veterans-affairs/va.gov-cms#11759]
## Background

**[VAMC System Banner Alert with Situation Updates](https://prod.cms.va.gov/node/add/full_width_banner_alert): [Change Management Plan](https://docs.google.com/document/d/169z2nh9Lcr9XVHOhNR8FoR4u9R-WCD8aIXUjlsbPHRo/edit#heading=h.ok958fqgaoi3)**

We want to limit VAMC System Banner Alerts to one per system, and impose a character limit. We want to document the new policy so the proper criteria and use of Banners is clearly communicated. We want to determine how editors are currently using VAMC System Banners, and create recommendations for how the should accomplish the same goal (_COVID guidelines, Promoting recruitment_). We want to provide adequate advance communications that this change is coming, and coordinate with VHADM so editors have the info they need when the new policies are enforced. 

### User Story or Problem Statement

As an Editor, I want accurate information for what is and is not appropriate use for Banners, and I want recommendations for how to accomplish common Banner misuses. I also want proper notice to prepare for a change in how Banners will be enforced.

### Affected users and stakeholders

* CMS Editors of VAMC product
* VHADM 

### Hypothesis

We believe that enforcing a more limited use of Banners, and educating Editors, will provide less confusing, more reader-friendly to Veterans visiting Facility pages.

**Comment by dsinla** [comment]
- Perform Audit
- Determine valid/invalid uses from audit
- For valid uses, assure the cases are properly documented
- For misuses, create recommendations "For recruiting, create your content like this" "For COVID visitation, your policies go here"
- Bring first draft to working session with VHADM
- Short term vs Long term: Consider where we don't have a current model to support the use case
- Work with content team to polish recommendations
- Create/modify existing KBs - New (or newly enforced) banner policy, how to accomplish content goal without banners (ie recruiting/marketing)
- Coordinate with VHADM - determine timeline. comms schedule
- Determine behavior for existing banners (all removed/deleted?)
- Communicate new policy (1 banner, character limit) and next steps to editors "U have 30 days to remove banners and author new ones"
- Implement character limit
- Purge/delete/unpublish existing banners
- Flip the switch
- Post-flip remediation/responsiveness

**Comment by dsinla** [comment]
@dsinla to work with Dottie to refine this Epic.

**Comment by jilladams** [comment]
Old dupe epic to de-dupe: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/1392

**Comment by jilladams** [comment]
@davidmpickett Per @mmiddaugh  re: VHA DM timing: Justin said today that VHA DM are waiting on KB articles and then would send a message to editors. We can expect to launch one week later. I think we need to work out the timing needed to realistically cover the new KBs flagged in #14009, and can work launch timing out from there. Something like filling in these blanks w/ dates: 
* KB article review / updated drafts complete = 
* VHA DM review = 
    * +1 week = launch date = 
* Helpdesk review =
