### ISSUE TITLE
Design: Prepare for IncLim stakeholder meeting

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#11755]
## Description

As a product designer/manager, I want to ask stakeholders about previous implementations so that I can make the new experience as simple as possible without losing important information.

Diving deeper into how income limits have been presented to Veterans in the past (see [Mural](https://app.mural.co/invitation/mural/vagov6717/1657807571797?sender=u907f83e01e35bb04de6f8139&key=1f5995db-a767-49f9-a6a0-bbd572cdddb9)), a number of questions arose – being tracked for now in a [Google doc](https://docs.google.com/document/d/1tgyDHnGvBDbLaKQtGvzl-UeEqfrTYVRvNlHG1vlA_ws/edit?usp=sharing) for ease of collaboration.

## Acceptance Criteria
- [ ] Questions about implementation organized to enable an effective meeting
- [ ] Proposed user flow documented to spur discussion
  - In Mural or Sketch (TBD)
  - Start from one of the possible entry pages (eg Priority Groups page)
- [ ] Book meeting with stakeholders (include: DaveP, Jordan, DaveC, Wes, Jill, Ryan)

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by wesrowe** [comment]
@thejordanwood, I created this ticket as a draft and assigned to both of us for discussion of what we'll try to get done next sprint.

**Comment by jilladams** [comment]
@wesrowe @thejordanwood is this ticket ready to close? IF not, could you add an update for sprint reporting purposes? Thanks!

**Comment by thejordanwood** [comment]
I believe this ticket is complete! We had our scheduled stakeholder meeting on Friday 12/16.
