### ISSUE TITLE
[CMS] Put memcache nodes into same AZ for performance gains

### ISSUE THREAD

**Issue by ElijahLynn** [department-of-veterans-affairs/va.gov-cms#11756]
## Story
As a system, all the memcache nodes should be in the same AZ as all other services, so that performance is consistent across environments, and so that performance is consistently faster.

We will know that this is true when before/after tests show a quantified improvement.

## Description
https://docs.google.com/document/d/16XQxkOU-uqJiiK11O_PNiIHZaSYmC1X-5Tr_1Lt0tPg/edit#

Examples where putting memcache nodes in the same AZ would help:

`/admin/content` load with a cold cache (Content admin overview)
* when AZs for various services are not matched, load time is at least 10s.
* when AZs for various services are matched, load time is consistently 9s. 

GraphQL query with a cold cache
* when AZs are not matched, query time is ~5 minutes
* when AZs are matched, query time is ~4 minutes

## Acceptance Criteria
- [x] All memcache nodes for all environments are in AZ 1C
	- [ ] Apply terraform
- [ ] When testing Content admin overview load time & GraphQL query time, results are consistent from test to test across test.staging and staging
- [ ] When testing Content admin overview load time, results are improved from the previous state by at least 10%
- [ ] Old memcache nodes are deleted
- [ ] When testing GraphQL query time, results are improved from the previous state by at least 20%

**Comment by ElijahLynn** [comment]
PR for CMS-TEST is here https://github.com/department-of-veterans-affairs/devops/pull/12307

**Comment by ElijahLynn** [comment]
This seems to have moved to https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11781.

**Comment by ElijahLynn** [comment]
Re-opened per my comment in https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11781#issuecomment-1351824000. 

> I am closing this ticket. I think we should have another ticket to put the memcache cluster fully into the same AZ to make things faster, yet less reliable in another ticket. We don't have the ASG set to launch multiple instances now, so we really don't have the advanatage of being multi-AZ right now, and I don't see any risk to putting the whole memcache cluster in the same AZ, since a failure in 1C would bring RDS and EC2 down anyways. I'm looking for logical arguments that we should not do this, if I don't hear any objections then I'm going to move forward with this.

**Comment by TheBoatyMcBoatFace** [comment]
Pushing to Sprint 74

**Comment by olivereri** [comment]
There is an infrastructure configuration required for this work. Elasticache in Terraform was configured to be cross AZ. The desired state is single-AZ mode. The changed has been rolled up in[ this DevOps PR](https://github.com/department-of-veterans-affairs/devops/pull/12316) with other related changes to Auto-Scaling Group networking.

**Comment by TheBoatyMcBoatFace** [comment]
> There is an infrastructure configuration required for this work. Elasticache in Terraform was configured to be cross AZ. The desired state is single-AZ mode. The changed has been rolled up in[ this DevOps PR](https://github.com/department-of-veterans-affairs/devops/pull/12316) with other related changes to Auto-Scaling Group networking.

This is merged

**Comment by olivereri** [comment]
@ElijahLynn Updates?

**Comment by ElijahLynn** [comment]
When we rolled out these changes, I did some [tests ](https://docs.google.com/spreadsheets/d/1cS0_6Kz15GduMc2X-yzjiv3PE3xJioycLWhBNLhPkUc/edit#gid=313862821) and am still seeing some discrepancies in identical infra across TEST.STAGING vs STAGING which confused me and I couldn't track down the cause of this. 

Here are the avg. mean response times over 3 tests for TEST.STAGING and STAGING both using 2 memcache nodes in the 1C Availability Zone:
|                | test.staging (cold cache) MC nodes (1C/1C) | staging (cold cache) MC nodes (1C/1C) | staging(cold cache) MC nodes (1C/1A) | test.staging (warm cache) MC nodes (1C/1C) | staging (warm cache) MC nodes (1C/1C) |
|----------------|--------------------------------------------|---------------------------------------|--------------------------------------|--------------------------------------------|---------------------------------------|
| /graphql       | 239s                                       | 270s                                  | 318s                                 |                                            |                                       |
| /admin/content | 8.8s                                       | 5.0s                                  |                                      | 0.3s                                       | 0.3s                                  |


note to self: this tool is great > https://www.tablesgenerator.com/markdown_tables

We can see that cold cache response times improved for /admin/content from 8.8s to 5.0s (55% decrease) however /graphql times went down on staging from 318s to 270s (16%), yet on test.staging, they went down even further to 239s (28%), which is confusing why we didn't see similar response times on staging. 

All in all we are seeing an improvement and I am kinda thinking that we should just finish deleting the unused nodes and close this story, unless anyone else wants a stab at this.

**Comment by ElijahLynn** [comment]
We agreed in Scrum just now that we can close this story. I will delete the unused nodes and then close this story.

**Comment by EWashb** [comment]
want me to close @ElijahLynn ?

**Comment by ElijahLynn** [comment]
Okay, the nodes have been deleted. 
![image](https://user-images.githubusercontent.com/1504756/214756814-94eeba71-7f8f-46df-a1e5-70da48955da8.png)
