### ISSUE TITLE
EDU Wizard: Refactor EDU How-to-apply wizard React component code

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#11750]
## Description

As a Developer, I want the wizard component to be clearly structured so that it's easier to read, grok, and maintain.

## Acceptance Criteria
- [ ] Question text and related links are next to each other in the code for easy visual checking
- [ ] Logic of form is as easy to follow as possible

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by FranECross** [comment]
@dsasser @chriskim2311 @randimays Do you know if this is still needed? I'm not sure what it it. :) Thanks! cc @jilladams

**Comment by jilladams** [comment]
Noted to Fran: let's start at the epic level and review priority with Dave.

**Comment by jilladams** [comment]
PW no longer owns this product. The EDU team will handle refactors as needed. Closing.
