### ISSUE TITLE
PM: Assess results of Banner audit and draft initial recommendations 

### ISSUE THREAD

**Issue by dsinla** [department-of-veterans-affairs/va.gov-cms#11760]
## Description
Review the results of the Banner audit, 

- Determine valid/invalid uses from audit
- For valid uses, assure the cases are properly documented
- For unintended uses, create first draft of recommendations "For recruiting, create your content like this" "For COVID visitation, your policies go here"

Recognize that there are some use cases that the system might not provide.  What is a short term solution that doesn't involve a product change? Then in long term, what might be a product change to support such use cases? 

## Acceptance Criteria
- [x] All valid uses are properly documented in existing KBs
- [x] Schedule working meeting with Dave C (doesn't have to be in Sprint)

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by EWashb** [comment]
@dsinla I'm going to suggest putting this one into stretch and removing the sprint designation. Just to protect your sprint capacity

**Comment by dawnpruitt** [comment]
- Will add to agenda and review with Dave at Facilities check in 12/21
- After assessing the related or appropriate KBs, further discovery is needed to refine and/or split KBAs for alerts and operating status.  The KB is not clear on what should be used when.
      - KB reference that should be refined: https://prod.cms.va.gov/help/vamc/about-locations-content-for-vamcs/about-alerts-and-operating-statuses
-  Further discussion required on the definition of "Correct Use" or appropriate for Banners

[BannersandKBs.xlsx](https://github.com/department-of-veterans-affairs/va.gov-cms/files/10249291/BannersandKBs.xlsx)
