### ISSUE TITLE
Investigation: Content build Archive phase slower on c5, c5d instances

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#11766]
## Description
With [recent testing of different AWS instance types](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11309), we noticed that the Archive phase of Content build is significantly slower on c5 and c5d instances, when compared with m5 and m6i instances ([Datadog notebook](https://vagov.ddog-gov.com/notebook/1019/content-release-runner-instance-data?view=view-mode)) . This is unexpected, since to our knowledge the Archive phase mostly consists of copying a large compressed archive from the runner to an S3 bucket. The differences between the c5* runners and m* runners are primarily memory-based, and so it seems strange this would affect a network transfer.

This should be a timeboxed investigation (suggestion: 1 full day) into what might be causing that differential, with any findings reported into the ticket. If a clear course of action is suggested by the findings, a ticket should be created.

## Acceptance Criteria
- [ ] Research & investigate why the Archive phase might be slower on c5* instances, and document it.
- [ ] If a clear course of action is suggested, create follow-up tickets.

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [x] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by ElijahLynn** [comment]
I think we should open an AWS Chat Support ticket. They could probably tell us quickly what is up.

**Comment by TheBoatyMcBoatFace** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VAgov-CMS-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/11766?planning-poker) with Zenhub @timcosgrove

**Comment by TheBoatyMcBoatFace** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VAgov-CMS-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/11766?planning-poker) with Zenhub @ElijahLynn @olivereri

**Comment by TheBoatyMcBoatFace** [comment]
Closed per team discussion on Dec. 19, 2022

Unclear if currently necessary. Time to move on.
