### ISSUE TITLE
Discovery: Duplicated Modesto and Sonora VA Clinics (Palo Alto + Northern California)

### ISSUE THREAD

**Issue by stefaniefgray** [department-of-veterans-affairs/va.gov-cms#11768]
## Description
See: https://va-gov.atlassian.net/browse/VAHELP-4953
https://va-gov.atlassian.net/jira/servicedesk/projects/VAHELP/queues/custom/11/VAHELP-5164

See prior "new facility" Github tickets: 
- Sonora https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11231
- Modesto https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11464

## Background
There are two “Sonora VA Clinics” listed within the [VA.gov](http://va.gov/) Facility Locator, and in turn, there are two “Sonora VA Clinics” that have been pulled into our system. Same goes for the Modesto VA Clinic.

Please see the attached screenshot, from https://www.va.gov/find-locations/

### For the Sonora VA Clinic:

**1. The “Old” clinic page and Facility Locator entry:** ( `/palo-alto-health-care/` )
- Live link: https://www.va.gov/palo-alto-health-care/locations/sonora-va-clinic/ 
- Prod link: https://prod.cms.va.gov/palo-alto-health-care/locations/sonora-va-clinic
- Facility locator link: [https://www.va.gov/find-locations/facility/vha_640GB](https://www.va.gov/find-locations/facility/vha_612GL)

**2. The “New” clinic page and Facility Locator entry:** (  `/northern-california-health-care/` )
- Live link: https://www.va.gov/northern-california-health-care/locations/sonora-va-clinic/ 
- Prod link: https://prod.cms.va.gov/northern-california-health-care/locations/sonora-va-clinic
- Facility locator link: https://www.va.gov/find-locations/facility/vha_612GL

### For the Modesto VA Clinic:

For the Modesto VA Clinic:

1. **The current Modesto clinic page and Facility Locator entry:** ( `/palo-alto-health-care/` )
- Live link: https://www.va.gov/palo-alto-health-care/locations/modesto-va-clinic/
- Prod link: https://prod.cms.va.gov/palo-alto-health-care/locations/modesto-va-clinic
- Facility locator link: https://www.va.gov/find-locations/facility/vha_640HB

2. **The new draft Modesto clinic page and Facility Locator entry:** ( `/northern-california-health-care/` )
- Live link: (Not published yet)
- Prod link: https://prod.cms.va.gov/northern-california-health-care/locations/modesto-va-clinic
- Facility locator link: https://www.va.gov/find-locations/facility/vha_612GM

You can view the listing of Health Services for each location by scrolling down to the “Health services at [City Name] VA Clinic” section at the bottom of the prod link for each page.

## Questions we've asked the VA Palo Alto and VA Northern California editors:
Waiting on responses in Jira ticket linked above:

1. Which of the two entries for each clinic is the “correct” one? 
2. Which of the pages on the production site should we keep? Which one should be archived?
3. Which of the two VAST entries displayed within the Facility Locator is the “correct” one?

## Acceptance Criteria
- [ ] We figure out which prod node for this facility should be archived
- [ ] We figure out what to do in regards to the duplicate VAST entry
- [ ] The Sonora VA Clinic prod page that we've chosen to keep is published to VA Northern California and can be found under their Locations menu as intended
- [ ] The Sonora VA Clinic is no longer listed under the Locations menu for VA Palo Alto (see screenshot)
- [ ] The Modesto VA Clinic prod page that we've chosen to keep is published to VA Northern California and can be found under their Locations menu as intended
- [ ] The Modesto VA Clinic is no longer listed under the Locations menu for VA Palo Alto (see screenshot)

![Screen Shot 2022-12-01 at 12 54 30 PM](https://user-images.githubusercontent.com/9059428/205150806-826c3e8e-cd79-42e9-8927-332eec7b2291.png)

![Screen Shot 2022-12-01 at 12 38 41 PM](https://user-images.githubusercontent.com/9059428/205150821-955400cf-5890-4c6e-8b47-4c166e5162fd.png)

![Screen Shot 2022-12-02 at 4 21 06 PM](https://user-images.githubusercontent.com/9059428/205411429-cc246d8a-3880-4bea-affc-b93a986c0572.png)

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [x] `⭐️ User support`

**Comment by stefaniefgray** [comment]
The Modesto VA Clinic is also duplicated

For the Modesto VA Clinic:

1. The current Modesto clinic page and Facility Locator entry: ( /palo-alto-health-care/ )
- Live link: https://www.va.gov/palo-alto-health-care/locations/modesto-va-clinic/
- Prod link: https://prod.cms.va.gov/palo-alto-health-care/locations/modesto-va-clinic
- Facility locator link: https://www.va.gov/find-locations/facility/vha_640HB

2. The new draft Modesto clinic page and Facility Locator entry: ( /northern-california-health-care/ )
- Live link: (Not published yet)
- Prod link: https://prod.cms.va.gov/northern-california-health-care/locations/modesto-va-clinic
- Facility locator link: https://www.va.gov/find-locations/facility/vha_612GM

Waiting on response in https://va-gov.atlassian.net/jira/servicedesk/projects/VAHELP/queues/custom/11/VAHELP-5164

**Comment by JayDarnell** [comment]
Please let me know as soon as we hear from the editor for clarification @stefaniefgray. I believe it is likely safe to say the old one should be archived and the services moved to the new one. That being said, the old one needs to be removed from lighthouse but that is sorta out of our control.

**Comment by JayDarnell** [comment]
@stefaniefgray to keep the amount of noise when these items come up to a minimum, lets avoid making multiple tickets to address a single issue. The old Sonora VA Clinic was removed from vast on the 17th so I am moving forward with archiving it and publishing the new one.

**Comment by stefaniefgray** [comment]
@JayDarnell @omahane Is it okay to close this one in favor of https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11464 while we're waiting on the duplicate Facility Locator entry to be removed? 

That's the last thing we've been waiting on -- going to close for now and re-open if needed. (Also, please let me know if there's info I forgot to add before closing. I'm on a ticket cleanup spree!)
