### ISSUE TITLE
Veterans Crisis line 988 outage: 

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#11772]
## Description
https://dsva.slack.com/archives/C52CL1PKQ/p1669932773949509

Change the text highlighted in yellow to this (and we need to make sure we also change the telelink to go to the [877-267-6030](tel:8772676030) number as well).
 [Call 877-267-6030](tel:8772676030)

![image (21)](https://user-images.githubusercontent.com/85581471/205180132-29290287-6927-42d0-953d-23de9c993559.png)

## Acceptance Criteria
- [x] Randi Hecht needs to approve PR

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [X] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by ryguyk** [comment]
Closing this. Opening [new ticket](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11780) for eventual reversion.
