### ISSUE TITLE
Discovery for enforcing proper workflow for new Facility pages and services

### ISSUE THREAD

**Issue by dsinla** [department-of-veterans-affairs/va.gov-cms#11778]
## Description
The Support team has experienced multiple instances of editors publishing a new Facility page prematurely (sometimes without listing a single service) in a failure to follow the prescribed process. Per the current process, editors are supposed to save pages as DRAFT first, and then notify the Support team. 

How can we best implement some guardrails in the CMS to prevent this from happening?

- Prevent the publish of a Facility page if it has no services: Likely a valuable validation step, but doesn't provide the review that the Support team wants prior to publish.

[Slack thread](https://dsva.slack.com/archives/C02730UEZPS/p1669843643234229)

[How do I add a facility KB](https://prod.cms.va.gov/help/vamc/about-locations-content-for-vamcs/how-do-i-add-a-facility-to-my-health-care-system)

Related(duplicate?) ticket: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11481

## Acceptance Criteria
- [ ] Working meeting is held to determine the best course of action
- [ ] Enforcement plan is decided and corresponding tickets created 

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [x] `⭐️ User support`

**Comment by stefaniefgray** [comment]
@swirtSJW @davidmpickett Similar inquiry as in #11481 -- 

Is there a newer/duplicate/alternate version of this ticket with regards to blocking VAMC editors from prematurely publishing new facility homepages in the CMS? (This ticket's title is also pretty fuzzy when we have the specific task nailed down.)

Would like to close in favor of other ticket(s) or consolidate

cc: @JayDarnell @omahane

**Comment by stefaniefgray** [comment]
@kmariepat-cityfriends Hi! This is the one where we don't want editors publishing new facilities too early without any VAMC Facility Health Services added, i.e. https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12000

**Comment by davidmpickett** [comment]
I think we can close this specific ticket in favor of https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12911#issuecomment-1541267890

I have done discovery around the problem and proposed a solution over there
