### ISSUE TITLE
Facility name change: DuBois Mobile Vet Center → Roanoke Mobile Vet Center

### ISSUE THREAD

**Issue by stefaniefgray** [department-of-veterans-affairs/va.gov-cms#11787]
## Intake
- [x] Submitter: David Grey, DuBois Vet Center. Their MVC was transferred to the Roanoke Vet Center.
- [x] If the submitter is an editor, send them the link to the CMS Knowledge Base (KB) article on facility basic data for their product (VAMC or Vet Center). Let them know that facility changes can take between 75 days and 4 months after submitting a request, according to VAST administrators. **Name change already occurred within VAST**

**Prod link:** https://prod.cms.va.gov/dubois-vet-center/dubois-mobile-vet-center

**Redirect request:** https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11785

**Jira ticket:** https://va-gov.atlassian.net/browse/VAHELP-4981

## Acceptance criteria
- [ ] The former "DuBois Mobile Vet Center" is renamed to the "Roanoke Mobile Vet Center"
- [ ] The URL for this node is updated from `/dubois-vet-center/dubois-mobile-vet-center` to `/roanoke-vet-center/roanoke-mobile-vet-center` per https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11785

## Vet Center – facility name change

- [x] The H1 title change comes from Lighthouse to Drupal.
- Is the new official name plain language (Does it match the pattern <city> Vet Center)?
  - [x] If yes, update the common name to match (when #6955 Unlock title field on Vet Centers is handled).
- Is the Vet Center published?
  - If yes:
    - [x] CMS team submits [redirect request](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/new?assignees=&labels=Redirect+request&template=redirect-request-facility-url.md&title=Redirect+Request+for%3A+%3Cinsert+facility+name%3E), cc'ing Facilities team
    - [x] Once timing of Redirect going live is known, alert CMS engineers to carry out steps in **Update ready** section below
  - If no: CMS engineers may continue with **Update ready** section below

- Update ready
    - [x] CMS engineer: visit bulk operations page and filter by section = vet center name
    - [x] CMS engineer: update URLs for all content in that section by bulk operations.
    - [ ] CMS engineer: **if a new section was created** - update field value for section by bulk operations.
    - [x] CMS engineer: resave all content in that section by bulk operations.
    - [ ] CMS engineer edit Vet Center node and remove flag `Changed name` then save node.
- Is the Vet Center published?
  - [ ] If no, HD notifies Michelle Middaugh to bulk publish.
  - [ ] HD notifies editor and any other stakeholders.
  </details>

## CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [x] `⭐️ User support`

**Comment by JayDarnell** [comment]
This is now complete @stefaniefgray. Worth noting, the directions above do not exactly apply for mobile vet centers. We have an issue in the queue to expand our runbooks which should take care of this.
