### ISSUE TITLE
Revert VCL/988 change

### ISSUE THREAD

**Issue by ryguyk** [department-of-veterans-affairs/va.gov-cms#11780]
## Description
When 988 is back up and stable, we need to revert the temporary change done in [this PR](https://github.com/department-of-veterans-affairs/vets-website/pull/22834).

## Acceptance Criteria
- [ ] VCL number is 988
![image](https://user-images.githubusercontent.com/6863534/205321134-20785118-ac8b-42e6-8b1a-10461a5b8884.png)

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by jilladams** [comment]
Approved to go ahead with review / merge: https://dsva.slack.com/archives/C52CL1PKQ/p1670266260742239?thread_ts=1670262436.775959&cid=C52CL1PKQ
