### ISSUE TITLE
PM: Prep for Lovell Training 

### ISSUE THREAD

**Issue by dsinla** [department-of-veterans-affairs/va.gov-cms#11793]
## Description
- [x] Finalize KBs
- [x] Initial editor orientation
- [x] Coordinate schedules with VHADM
- [x]  Run-thru with Support
- [x] Verify training environment has been rebuilt with latest changes -> Support responsible

## Acceptance Criteria
- [ ] Support has all they need to conduct training on  12/8

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [x] `⭐️ User support`

**Comment by davidmpickett** [comment]
@dawnpruitt - pretty sure this can close, training was conducted last week, right?

**Comment by dsinla** [comment]
Training was conducted, PPT sent out, recording shared.
