### ISSUE TITLE
Update menu config with new menu names & summaries

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#11816]
## Description

Menu Title and Summary are editable CMS fields, but edited values don't persist and are overwritten by config on every build. So: we need to update these values in config. 

**Machine names should not change.**

| Menu | Current Title | New Title | New Admin Summary |
--- | --- | --- | --- 
| https://prod.cms.va.gov/admin/structure/menu/manage/popular-on-va-gov | `Popular on VA.gov` | `Home page - Top pages` | VA.gov homepage menu of links | 
| https://prod.cms.va.gov/admin/structure/menu/manage/footer | `Footer` | `CMS Footer` | Site information links that display in CMS global footer on CMS login page. |
| https://prod.cms.va.gov/admin/structure/menu/manage/footer-bottom-rail | `Footer bottom rail` | `VA.gov Footer bottom rail` | Displayed in VA.gov global & injected footer; horizontal list of links at the bottom of the page |
| https://prod.cms.va.gov/admin/structure/menu/manage/other-search-tools | `Other search tools` | `Home page - Other search tools` | VA.gov homepage menu of links, displayed below the in-page search form | 
| https://prod.cms.va.gov/admin/structure/menu/manage/va-gov-footer | `Footer VA.gov` | `VA.gov Footer` | Displayed in VA.gov global & injected footer; 3-column list of footer links |
| https://prod.cms.va.gov/admin/structure/menu/manage/header-megamenu | `Header megamenu` | N/A - title is fine | Displayed in VA.gov global & injected header; Links and promos for the site's header menu. |

### Notes
One note here: the VA.gov footer menu has a machine name, `va-gov-footer`, that puts it on a deeper pagination rather than the first page of menus. That's fine, and we can't change it; just noting it for others who may have trouble finding it.

## Acceptance criteria

- [x] @swirtSJW can you check this box when you've looked at this ticket? Want to avoid PR churn by making sure you're aware of the what and why before we start coding.
- [ ] Updated Title and Administrative Summaries are visible on the CMS edit screen for each menu
- [ ] Machine names are persistent and do not change
- [ ] FE build succeeds: this confirms FE GraphQL queries are functioning despite menu name changes (there have been instance of FE queries using the menu name rather than the machine name).

**Comment by swirtSJW** [comment]
I really like the ones that follow the pattern of prefixing VA.gov so that they are explicit
![image](https://user-images.githubusercontent.com/5752113/206194521-eda85133-70b6-453c-b291-7d1b9806e9b7.png)
Is there a reason not to prefix  the other FE menus with VA.gov as well?

Unfortunately the stock menu admin alpha sorts by machine name and not Title which leads to only a marginal benefit.


Other than that all looks fine.

**Comment by swirtSJW** [comment]
A consideration for the future https://www.drupal.org/project/drupal/issues/3070721

**Comment by jilladams** [comment]
I thought about that -- my main reason was to distinguish the 2 footers, since we have a CMS footer menu, vs. a VA.gov footer menu. For the others, we don't have competing CMS versions of menus, and the vast majority of _all_ the other menus are in VA.gov, and not declared that way. 

I could be argued either directions if it feels important.

**Comment by jilladams** [comment]
Sensible,updated. One annoying thing: menu list is alpha sorted by machine name, so user-friendly naming doesn't help with finding your menus. But: worth doing anyway.
