### ISSUE TITLE
Add once-per-session logic to Soft-launch homepage modal

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#11817]
## Description

As a Veteran, I want to only be shown the homepage soft-launch modal once each time I visit VAgov so that I can have the opportunity to provide feedback without being annoyed.

### Engineering notes

Hypothesis: local storage is the way to go, there's a type of local storage that is erased when the tab is closed. That seems to best correspond to how we want this to work.

## Acceptance Criteria
- [ ] The soft-launch modal shows once per browser tab/window, regardless of how the visitor exits the modal (ie, dismisses the modal or follows the link to see the new homepage)
- [ ] Requires product review

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by mmiddaugh** [comment]
This modal and our soft launch plan were presented and approved during Design Office Hours with VA.gov Platform on Tuesday, November 15
