### ISSUE TITLE
Request for new or update to existing KB article : Tables

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#11815]
## Background context
**What is the request for?**
- New article about when to use tables and how to create accessible tables

**Person and team of requester:** 
- Sitewide CMS, Dave C

**Priority or deadline for request**

  Choose either Deadline or a priority:
  
- [ ] Deadline: [name the deadline here]
- [x] Priority:
  - [ ] Critical - Without this, there is a large negative impact on the majority of editors causing negative consequences within the CMS; Should be completed as soon as possible
  - [ ] High - Without this, there is negative impact on some editors causing negative consequences within the CMS; should be completed within the current sprint
  - [x] Medium - Without this, there is confusion for editors but not causing negative consequences within the CMS; Should be completed within the next 1-2 sprints
  - [ ] Low - This is not currently causing confusion for many editors but would be a nice to have or is something that may be more impactful in the future; Should be completed within the next 3-4 sprints
  

**Is the article associated with an ongoing product or feature update?**
- [x] Yes: not an ongoing ticket but an ongoing initiative for 508 compliance
- [ ] No

  
## If requesting a new article:

**Audience:**
Who is this intended for? Who would need this information? (i.e. All editors, only editors for a particular product, Internal use only, etc.)
- All editors

**Related KB articles, if applicable:** 
- None existing

  
**Any other relevant documentation, if applicable:** 
- [Design Style guide](https://design.va.gov/components/table#usage)

## Process
1. Sitewide CMS and Helpdesk teams will review request and confirm no current, applicable KB article/content exists.
2. Refine request and prioritize
3. Update KB article tracker to indicate that the article has been requested and is in progress
4. Assign to appropriate product team
5. Draft article content 
6. Sitewide CMS team will review for formatting and writing style guidelines
7. Helpdesk team will review for functionality and editorial tone
8. Publish
9. Update KB article tracker to indicate that the article has been published

## Acceptance Criteria
- [x] Article is created using [KB content style guidelines](https://va-gov.atlassian.net/wiki/spaces/VAGOV/pages/1771831299/Knowledge+Base+content+style) 
- [x] Article is reviewed by Sitewide CMS
- [ ] Article is reviewed by Helpdesk
- [ ] Article posted to KB 
- [ ] Impacts on other KB articles have been considered and any necessary changes have been made
- [ ] Once published, the person requesting the article has been notified

**Comment by EWashb** [comment]
Well, I think this one is ok. You have the jump links and this isn't too terribly long. I think, yes, let's keep it short when we can, but there's a lot to say on this topic and you have all good info here @laflannery

**Comment by laflannery** [comment]
@stefaniefgray or @TroyA6 Would you like to review this new [KB article](https://prod.cms.va.gov/help/cms-basics/using-tables-in-the-cms) before I publish it? It's for how to create a good table in the CMS

**Comment by laflannery** [comment]
Talked to Stef, she pointed out the numbered bullets looked wild and confusing so I fixed those and then [published](https://prod.cms.va.gov/help/cms-basics/using-tables-in-the-cms)
