### ISSUE TITLE
FE: On tricare pages the menu item for Health services should come before locations

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#11830]
Additional nuance for this bullet point is that Health Service is showing up as a sub-item of Locations

![Screenshot 2022-12-06 143328](https://user-images.githubusercontent.com/51967950/206017033-56c672ae-1067-49b6-8720-7689a88055ac.png)

**Comment by swirtSJW** [comment]
I made one small tweak to the menu that MIGHT resolve this.    We'll know on the next time we rebuild the demo environment.

**Comment by JQuaggles** [comment]
**Acceptance Criteria:**
- [ ] Health Services link in left nav is the first link under SERVICES AND LOCATIONS on every page.
   - [ ] On Tricare pages Health Services links in left nav come before Locations link
   - [ ] On VA pages Health Services links in left nav come before Locations link
   - [ ] On Joint/VA-Tricare pages links in left nav come before Locations link

**Comment by davidmpickett** [comment]
Confirmed in Sprint Planning that this has been fixed 
![Screen Shot 2022-12-19 at 11 02 17 AM](https://user-images.githubusercontent.com/51967950/208480047-10d79e79-5cb2-4bfd-92c6-18d2415d5ee7.png)
