### ISSUE TITLE
PM Determine approach for manage your health on TRICARE

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#11832]
Question to bring to VHADM
TRICARE System Page - "Manage your health online" - should this whole thing be hidden for TRICARE since these are all hardcoded VA links?
![Screenshot 2022-12-06 145208](https://user-images.githubusercontent.com/51967950/206020681-dc727e9e-4b9c-44a7-86ef-b9f21d41e52d.png)

**Comment by davidconlon** [comment]
Answer: Yes they should be hidden for Lovell MVP as they are VA-only links.

**Comment by JayDarnell** [comment]
Closed now that 11967 has been created to perform updates outlined in this issue.
