### ISSUE TITLE
Support running complete test suite (local + GHA) with a single command.

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-cms#11842]
## Description
Depends on #11841 and #9416.  We should be able to execute a single command and run the full test suite.

## Acceptance Criteria
- [ ] Full test suite can be executed with a single command.

**Comment by EWashb** [comment]
This is blocked by two other issues. I added them to the ticket. Removing for this sprint due to those dependencies. I'll also move this to the blocked pipeline

**Comment by ndouglas** [comment]
Closed in #12192.
