### ISSUE TITLE
Check consistency and ease-of-use of DDEV commands.

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-cms#11845]
## Description
Some of the DDEV commands appear to require a `--` before passing arguments to the underlying operation, some don't appear to pass arguments at all, etc.  There's some inconsistency here, and I'd like to improve this.

Possibly part of #9416, or a followup.

## Acceptance Criteria
- [x] All custom DDEV commands have been audited and fixed (where necessary) to be consistent, well-documented, and easy to use, or
- [x] Followup issue(s) opened for thorny cases

**Comment by EWashb** [comment]
This will stretch into the next sprint.
