### ISSUE TITLE
Follow up with subdomain owners where proxy-rewrite-whitelist.json lists the subdomain as cookieOnly:true, to see if injected header could be enabled

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#11853]
## Description
The previous Public Websites team took a proactive approach to identify subdomains that would be good candidates for header/footer injection, and proactively whitelisted them:
https://github.com/department-of-veterans-affairs/vets-website/pull/12438

Those sites may or may not have completed testing and enabled the injected header in prod. 

Work remaining: 
* Review the list of domains whitelisted as `cookieOnly: true` in [proxy-rewrite-whitelist.json](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/proxy-rewrite/proxy-rewrite-whitelist.json) - these are in testing mode, with injection not enabled on prod
* Confirm with owners of the subdomains whether they want to pursue injected header

This is a backlog ticket filed because we found that vetcenter.va.gov is in this situation. Current priority for the work is not clear.

## Acceptance Criteria 
TBD

**Comment by FranECross** [comment]
@jilladams Considering that we'll be moving toward deprecating the injected header, what do you think about closing this ticket, or would it be something I should check with Dave about? Thanks!

**Comment by FranECross** [comment]
Adding to the next product sync meeting with Michelle.

**Comment by FranECross** [comment]
Closing as a no op; we'll create a new epic/tickets in the future if this becomes relevant again.
