### ISSUE TITLE
Remove cerner_override_463, 531, 648, 663 feature toggles

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#11859]
## Status:
- 2024-01-25: Per Dave C we should start whittling these down and work on them as when possible.

## Description
- These were preparatory for upcoming Cerner cutovers that got delayed. These flippers can be removed since Drupal is now the source of truth for cutovers.

cerner_override_463
cerner_override_531
cerner_override_648
cerner_override_663

## Acceptance Criteria

- [x] Confirm before touching code that flippers are off in staging & prod
- [x] All references to the flipper in vets-website, if any, are removed
- [x] Flipper code in vets-api, is removed

**Comment by randimays** [comment]
Noting here that there is mention of these feature toggles in [va.gov-team](https://github.com/department-of-veterans-affairs/va.gov-team/blob/b7a9a3309d983d5768c5f0367d104d16cf73b739/products/public-websites/healthcare-widget-support/how_to_set_up_vamc_cerner_within_va_health_care_portals.md?plain=1#L80) that we may need to remove/rewrite (but I'm not quite sure which).

**Comment by randimays** [comment]
vets-website is experiencing a lot of pipeline instability, and Platform has been triaging the situation for the past couple of days. Working on trying to get this one across the line, but may not be able to get through CI today. [PR here](https://github.com/department-of-veterans-affairs/vets-website/pull/27908)

**Comment by randimays** [comment]
Removed from both vets-website and vets-api. I also submitted a [Platform request](https://dsva.slack.com/archives/CBU0KDSB1/p1707944695031129) to have them removed from the staging and production flipper dashboards.
