### ISSUE TITLE
Update the Time Since Last Content Release monitor & alert to reflect expanded continuous content release window

### ISSUE THREAD

**Issue by TheBoatyMcBoatFace** [department-of-veterans-affairs/va.gov-cms#11857]
# Overview
The content release window was expanded, but the current monitoring and alert widows are not covering the additional timeframe. 

## Why This Matters
Monitoring the Content Release workflow is critical to ensuring timely site updates and a positive user experience.

# Acceptance Criteria
- [x] Add [#cms-support](https://dsva.slack.com/archives/CDHBKAL9W) as a destination alert for PagerDuty
- [x] Expand the alert window from 9am EST - 5PM EST to 8AM EST to 9PM EST 
- [x] Define alert caculations during the 1+- hour timeframe during the alert window

**Comment by EWashb** [comment]
@TheBoatyMcBoatFace are you finished with this ticket? We will need to close or remove the sprint label

**Comment by TheBoatyMcBoatFace** [comment]
The outcome of Sprint 74's planning/research will impact this issue. Will address in Sprint 75

**Comment by olivereri** [comment]
This work has been completed. Related issues:
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10891

Actual work that duplicate this ticket:
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10925
