### ISSUE TITLE
Discharge Wizard: Add E2E tests to guard against regression

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#11854]
## Description

As a Veteran, I want developers to know that the Discharge Upgrade Wizard has a regression defect as soon as it happens to that I don't have a trust-reducing/bad experience with VAgov.

Consult this [Mural board](https://app.mural.co/invitation/mural/vagov6717/1670355600942?sender=u252e7152800e3981889d1910&key=789998a8-498d-419f-be6d-aef09cbf2e23) to see a visual representation of the possible flows through the app.

## Acceptance Criteria
- [ ] Discuss with at least one other FE engineer what test cases to cover, goal being to maximize test coverage for the smallest reasonable effort; i.e., touch as many possible paths through the wizard with as few test cases as possible.
- [ ] Implement agreed-upon test cases e2e

### CMS Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [x] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`

**Comment by jilladams** [comment]
FE refinement: this ticket needs a real time for eng to dive into the Mural to come up with plan, vs. trying to do it live.

**Comment by jilladams** [comment]
Discussed with Wes: Since DUW rebuild is hoped for in Q4 priorities, this is probably not worth doing until after that rebuild.

**Comment by jilladams** [comment]
Iceboxing bc we won't take this on til we rebuild DUW.

**Comment by chriskim2311** [comment]
Closing this as we will take care of the E2E tests with the new rebuild
