### ISSUE TITLE
Remove cerner_allow_partial_facilities flipper

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#11861]
## Status:
- 2024-01-25: Per Dave C we should start whittling these down and work on them as when possible.

## Description
This allowed cerner facilities to be set to partially cerner or all cerner. We have confirmed that partial Cerner is no longer a paradigm that will be used, so this flipper can be removed: https://dsva.slack.com/archives/C52CL1PKQ/p1651003534292679?thread_ts=1651001729.083759&cid=C52CL1PKQ

## Acceptance Criteria

- [x] Confirm before touching code that flipper is off in staging & prod
- [x] All references to the flipper in vets-website, if any, are removed
- [x] Flipper code in vets-api, is removed

**Comment by randimays** [comment]
vets-website is experiencing a lot of pipeline instability, and Platform has been triaging the situation for the past couple of days. Working on trying to get this one across the line, but may not be able to get through CI today. [PR here](https://github.com/department-of-veterans-affairs/vets-website/pull/27906)

**Comment by randimays** [comment]
Removed from both vets-website and vets-api. I also submitted a [Platform request](https://dsva.slack.com/archives/CBU0KDSB1/p1707944695031129) to have them removed from the staging and production flipper dashboards.

**Comment by jilladams** [comment]
This flipper is appearing in Prod again. Filed a new support request to slay some zombies: https://dsva.slack.com/archives/CBU0KDSB1/p1718646185640249
