### ISSUE TITLE
Remove shift_vets_banner flipper

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#11863]
Shifts veteran banner position on the home page to a lower position. That position will become the default when homepage 
redesign ships.

To remove: we need to strip out the logic that references the flipper, as well.

## Acceptance Criteria

- [x] Confirm before touching code that flipper is off in staging & prod
- [x] All references to the flipper in vets-website, if any, are removed
- [x] Flipper code in vets-api, is removed

**Comment by maxx1128** [comment]
Closing this since https://github.com/department-of-veterans-affairs/vets-website/pull/23338 and https://github.com/department-of-veterans-affairs/vets-api/pull/11773 have both been merged.
