### ISSUE TITLE
Vendor Review: Cloudcraft

### ISSUE THREAD

**Issue by TheBoatyMcBoatFace** [department-of-veterans-affairs/va.gov-cms#11866]
# Overview
[**Cloudcraft**](https://www.cloudcraft.co/) is a web-based platform that allows the Platform CMS team and DVSA overall to design, visualize, and plan AWS Govcloud infrastructure in a collaborative and intuitive way. It will give our team an auto-updating cloud-infrastructure map with resource metadata.

We are accessing Cloudcraft as a possible solution to the infrastructure diagraming problem.

## Problem to Solve
The Platform CMS team needs better insight into their AWS Infrastructure to better troubleshoot issues.Also, non-DevOps Sitewide & Platform Crew Members need a visual representation of the infrastructure associated with the services they interact with. Initially, a static diagraming solution seemed to be a good solution, but concerns about maintaining the docs were raised.

An automated cloud diagraming solution solve these problems.

## Goal
To access and review the Cloudcraft platform to determine if it fits the Platform CMS Team use case

## Acceptance Criteria
- [x] Members of Platform CMS Team added as Cloudcraft Demo Users
- [ ] Define the review timeframe - How long do we need to review the platform before making a decision?
- [x] Cloudcraft connected to AWS
- [ ] List of diagrams and infrastructure groupings created
- [ ] "Public" Confluence diagram embeds created
- [ ] [API Docs](https://developers.cloudcraft.co/) reviewed
- [ ] Input sought from outside of the Platform CMS Team
- [ ] Platform CMS Team and interested parties held meeting to discuss platform at end of review period

**Comment by olivereri** [comment]
Regarding CloudCraft's poor UI performance: One way to improve this from our end is to craft a more specific IAM Role. Right now the role is Read Only on all resources.  We can however tailor the IAM Role permissions to pick up only things related to CMS.  This'll take some work to make sure we have complete coverage based on tags.

**Comment by TheBoatyMcBoatFace** [comment]
Cloudcraft eng team looking into scale issue

**Comment by TheBoatyMcBoatFace** [comment]
Moving to Sprint 74 - Waiting on feedback from vendor

**Comment by olivereri** [comment]
> Our engineering team was able to look into the issue and it was due to the large number of resources. We are working on performance improvements for large environments and I will keep you updated. In the meantime, I would suggest performing filtered live scans using tags. 

Cloudcraft responded back with the above regarding the UI slow performance.  The first filtered live scan is going to be slow because adding tags is super slow due to the sheer number of resources.  I can experiment with crafting a much more limited IAM role so Cloudcraft won't have to query as many resources.

**Comment by TheBoatyMcBoatFace** [comment]
Shifting to Sprint 75 due to scheduling issues. Possibly iceboxing due to contract/funding changing/concerns.

**Comment by olivereri** [comment]
We will not be pursuing Cloudcraft at this time.
