### ISSUE TITLE
Remove mega_menu_mobile_v2 flipper

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#11862]
Separates mobile mega menu from desktop mega menu. Requires small cleanup in vets-website.

## Acceptance Criteria

- [x] Confirm before touching code that flipper is off in staging & prod
- [x] All references to the flipper in vets-website, if any, are removed
- [x] Flipper code in vets-api, is removed

**Comment by jilladams** [comment]
Not sure how this ended up as a Facilities ticket -- PW owns the header. Prob fine, just @maxx1128 pls make sure to get code review from @jtmst before merging.

**Comment by jilladams** [comment]
@Dottisea for context, noticing that you had pulled it into Fac -- our team should prob keep any items from the [Google Doc ](https://docs.google.com/spreadsheets/d/1yQb5oDshNj7y0nvtF3PaZ9OLhtTuZ2aO8t4_n51YBWU/edit#gid=237722104&fvid=1552255965) that have PW in Column A.

**Comment by maxx1128** [comment]
@jilladams It got merged earlier today, but @jtmst was one of the first reviewers of the pull request beforehand 👍

**Comment by maxx1128** [comment]
Closing this since https://github.com/department-of-veterans-affairs/vets-website/pull/23337 and https://github.com/department-of-veterans-affairs/vets-api/pull/11769 have both been merged.
