### ISSUE TITLE
Remove va_global_downtime_notification flipper

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#11864]
Enables global downtime notification- do not use in production

Only mentioned in tests and fixtures, not in actual code. Owned by PW, "Caregiver" and "Other". We may need to track down additional reviewers from those groups at PR time.

## Acceptance Criteria

- [ ] Confirm before touching code that flipper is off in staging & prod
- [ ] All references to the flipper in vets-website, if any, are removed
- [ ] Flipper code in vets-api, is removed

**Comment by jilladams** [comment]
Moving to In Progress and adding to sprint, since it looks like this work is actually in progress and partially merged. (@smythe5 I think this should get reported in the PW section of our sprint report, rather than Facilities.)

**Comment by maxx1128** [comment]
Closing this since https://github.com/department-of-veterans-affairs/vets-website/pull/23345 and https://github.com/department-of-veterans-affairs/vets-api/pull/11770 have both been merged.
