### ISSUE TITLE
Remove sharable_link flipper

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#11877]
Toggles the availability of sharable links to deep link to content

## Acceptance Criteria

- [x] Confirm before touching code that flipper is off in staging & prod
- [x] All references to the flipper in vets-website, if any, are removed
- [x] Flipper code in vets-api, is removed

**Comment by randimays** [comment]
Code is removed from vets-website and vets-api. Request put in to Platform here to remove flippers from staging and production dashboard: https://dsva.slack.com/archives/CBU0KDSB1/p1708569300656239 Closing!
