### ISSUE TITLE
Remove show_header_v2 flipper

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#11875]
## Status:
- 2024-01-25: Per Dave C we should start whittling these down and work on them as when possible.

## Description

Enables the new header

## Acceptance Criteria

- [x] Confirm before touching code that flipper is off in staging & prod
- [x] All references to the flipper in vets-website, if any, are removed
- [x] Flipper code in vets-api, is removed

**Comment by randimays** [comment]
Both vets-website and vets-api changes have been merged. Platform removed the flippers from the [prod flipper dashboard](https://api.va.gov/flipper/features) and [staging flipper dashboard](https://staging-api.va.gov/flipper/features). Closing!
