### ISSUE TITLE
Remove yellow_ribbon_mvp_enhancement flipper

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#11873]
Enhances Yellow Ribbon MVP.

## Acceptance Criteria

- [ ] Confirm before touching code that flipper is off in staging & prod
- [ ] All references to the flipper in vets-website, if any, are removed
- [ ] Flipper code in vets-api, is removed

**Comment by FranECross** [comment]
@jilladams Since we don't own Yellow Ribbon anymore, should this ticket be moved to the team who now owns it? Thanks!

**Comment by jilladams** [comment]
Yep, good catch! Updated labels accordingly.

**Comment by jilladams** [comment]
Owned by IIR
