### ISSUE TITLE
Cannot change vets-website to a PR that's a couple weeks old

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#1187]
**Describe the defect**
I'm trying to change http://devshop.cms.va.gov/hosting_confirm/15303/ to use https://github.com/department-of-veterans-affairs/vets-website/tree/VAGOV-6425-refactor-listings-et (PR 11608)

**To Reproduce**
1. Go to http://devshop.cms.va.gov/hosting_confirm/15303/ 
2. Change the WEB version to #11608 (https://github.com/department-of-veterans-affairs/vets-website/tree/VAGOV-6425-refactor-listings-et)
3. note that the listing doesn't go past 111701 (as of March 9 2020)

**Expected behavior**
I should be able to access all unmerged PR branches from vets-website

**Screenshots**

![devshop_cms_va_gov_and_VAGOV-6425_listings_conversion_to_Drupal_by_ethanteague_·_Pull_Request__11608_·_department-of-veterans-affairs_vets-website](https://user-images.githubusercontent.com/643678/76217423-c8f49300-61e8-11ea-84a2-f7535eb486ae.jpg)

**Comment by kevwalsh** [comment]
@ElijahLynn [indicates](https://dsva.slack.com/archives/CT4GZBM8F/p1583778365243400?thread_ts=1583553607.208800&cid=CT4GZBM8F) that this is just the first page of results

**Comment by ElijahLynn** [comment]
Closing for now as we are likely moving off of DevShop and this functionality will be moved to the CMS on the Deploy Content page.
