### ISSUE TITLE
Remove show_new_secure_messaging_page flipper

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#11871]
## Status:
- 2024-01-25: Per Dave C we should start whittling these down and work on them as when possible.

## Description

Shows the non-Cerner-user and Cerner-user content for the page /health-care/secure-messaging/

Owned By PW. Mentioned in feature flags file and unit tests only.

## Acceptance Criteria

- [x] Confirm before touching code that flipper is off in staging & prod
- [x] All references to the flipper in vets-website, if any, are removed
- [x] Flipper code in vets-api, is removed

**Comment by randimays** [comment]
Code is removed from vets-website and vets-api. Request put in to Platform here to remove flippers from staging and production dashboard: https://dsva.slack.com/archives/CBU0KDSB1/p1708569300656239 Closing!
