### ISSUE TITLE
[Events] Remove show_events_v2 flipper

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#11876]
Enables the events v2 page

## Acceptance Criteria

- [x] Confirm before touching code that flipper is off in staging & prod
- [ ] ~All references to the flipper in vets-website, if any, are removed~
- [x] Flipper code in vets-api, is removed
- [x] Open a Platform support request to manually update the Flipper dashboard to remove that flipper, e.g. https://dsva.slack.com/archives/CBU0KDSB1/p1706215548005939

**Comment by randimays** [comment]
Flipper is not used anywhere so I disabled it in both staging and prod:

- https://staging-api.va.gov/flipper/features/show_events_v2
- https://api.va.gov/flipper/features/show_events_v2

Also crossed out the vets-website AC as it is not applicable.

**Comment by randimays** [comment]
This was pulled in as stretch for Sprint 10.

**Comment by randimays** [comment]
Code has been removed from vets-api, did not exist in vets-website. [Platform request](https://dsva.slack.com/archives/CBU0KDSB1/p1724082680153989) to remove from flipper dashboards is complete.

Verified in [staging flipper admin](https://staging-api.va.gov/flipper/features) and [prod flipper admin](https://api.va.gov/flipper/features) that the flipper is removed.

Closing as complete!
