### ISSUE TITLE
Remove show_new_view_test_lab_results_page flipper

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#11872]
Shows the non-Cerner-user and Cerner-user content for the page /health-care/view-test-and-lab-results/

Owned By PW. Mentioned in feature flags file and unit tests only.

## Acceptance Criteria

- [x] Confirm before touching code that flipper is off in staging & prod
- [x] All references to the flipper in vets-website, if any, are removed
- [x] Flipper code in vets-api, is removed

**Comment by randimays** [comment]
vets-website is experiencing a lot of pipeline instability, and Platform has been triaging the situation for the past couple of days. Working on trying to get this one across the line, but may not be able to get through CI today. [PR here](https://github.com/department-of-veterans-affairs/vets-website/pull/27909)

**Comment by randimays** [comment]
Removed from both vets-website and vets-api. I also submitted a [Platform request](https://dsva.slack.com/archives/CBU0KDSB1/p1707944695031129) to have them removed from the staging and production flipper dashboards.
