### ISSUE TITLE
Misleading occasional error message on Tugboat previews.

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-cms#11881]
## Description
![Screen Shot 2022-12-08 at 11 11 10 AM](https://user-images.githubusercontent.com/1318579/206499857-c6ef15e2-4d8b-4114-b523-3019cead66cb.png)

Causes confusion, don't think it does anything useful.  Probably just a matter of sprinkling a little `|| true` somewhere or something like that.

## Acceptance Criteria
- [ ] We don't see misleading error messages like this.

**Comment by ndouglas** [comment]
I believe this is occurring because we've dispatched a frontend build by this point, and that might be zapping the directory out from under us.  Changing the order of these commands should work.

**Comment by ElijahLynn** [comment]
:crossed_fingers: 

> I believe this is occurring because we've dispatched a frontend build by this point, and that might be zapping the directory out from under us. Changing the order of these commands should work.

**Comment by ndouglas** [comment]
I should note that the above suspicion is based on already having fixed a few bugs to do with the changing nature of the frontend build on Tugboat, and it looking familiar 🙂   Not wild conjecture.
