### ISSUE TITLE
Investigate upgrading to Debian Bullseye on Tugboat.

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-cms#11884]
## Description
I don't remember the details, but we're currently running Buster.  Buster's in LTS phase and we should probably shift to Bullseye sooner rather than later.

https://wiki.debian.org/LTS

Key phrase: 
>Debian LTS is not handled by the Debian Security team, but by a separate group of volunteers and companies interested in making it a success.

## Acceptance Criteria
- [ ] A quick stab has been taken at upgrading Docker images to Bullseye on Tugboat.
- [ ] Followup issue(s) opened with findings from above to guide the upgrade process or some alternative approach.

**Comment by ElijahLynn** [comment]
The issue was because of the version of Docker running on the Tugboat server. We need to update Docker on Tugboat to use Bullseye.

**Comment by ElijahLynn** [comment]
There are a few issues in the queue stating the precise issue and which dependency is actually the blocker. I'm too lazy to search them right now.

**Comment by ndouglas** [comment]
See #7667

**Comment by ElijahLynn** [comment]
We just upgraded to in #7667:
```shell
docker --version
Docker version 20.10.13, build a224086
```
