### ISSUE TITLE
Investigate PHP 8.1 Upgrade Errors

### ISSUE THREAD

**Issue by TheBoatyMcBoatFace** [department-of-veterans-affairs/va.gov-cms#11889]
# Overview
Once [PHP 8.1 was deployed to prod.cms.va.gov](#11295), @ElijahLynn noticed an increased number of errors in [Sentry](http://sentry.vfs.va.gov/). 

## Associated Issues
- #11295

## Why It Matters
PHP is important in Drupal because it is the language that Drupal is written in. PHP is a server-side scripting language, which means that it runs on the web server and generates the HTML that is sent to the user's web browser. PHP allows Drupal to store and retrieve data from a database, and to generate dynamic web pages that can display different content to different users. PHP's stability is critical when it comes to the website.

## Goal
To determine the cause of post-upgrade errors and define a path to their resolution

# Acceptance Criteria

- [x] Post-upgrade errors audited
- [ ] Source of errors determined
- [ ] Resolution defined

**Comment by ndouglas** [comment]
IMHO this isn't a DevOps responsibility.

**Comment by ndouglas** [comment]
I think this can be closed in favor of

- #11904 
- #11905 
- #11906 
- #11907 
- #11908

**Comment by ndouglas** [comment]
cc @EWashb @ElijahLynn

**Comment by ElijahLynn** [comment]
Thank you Nate!!!
