### ISSUE TITLE
Enable Table of Contents component for two new content types: page and documentation

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#1188]
## User Story or Problem Statement

As an editor of a `benefits detail page`, i want to enable a table of contents that automatically generates a TOCs from H2s on the page, so that i don't have to build it myself, and so that it follows the pattern in the design system. 

## Acceptance Criteria
* An editor replace the "manual" Toc on any benefits detail page, with an automatically generated one, just like on https://www.va.gov/pittsburgh-health-care/mission-vision/

## Implementation steps
- [ ] Add a field to each content type and arrange it in the form just like on Detail Page content type
- [ ] Update appropriate FE templates 

## Affected users and related research

A few slack threads about this
* https://dsva.slack.com/archives/C52CL1PKQ/p1583252828313500
* https://dsva.slack.com/archives/C52CL1PKQ/p1581690069149700

[9 month old analysis of anchor links (mural)](https://app.mural.co/t/vagov6717/m/vagov6717/1558063144267/d65e231126293ba483b6eeb3731976514fb47ca3)

**Comment by jenniferlee-dsva** [comment]
@kevwalsh - As @rtwell and I are doing initial template designs for learning center, we'd like to be able to use the TOC component on the learning center FAQs template as well. FYSA.
