### ISSUE TITLE
Redirect legacy pages for VALife to modernized VALife page - (client-side) Morning of Jan 4

### ISSUE THREAD

**Issue by heyjoni** [department-of-veterans-affairs/va.gov-cms#11892]
### Instructions
- Requests must be submitted **AT LEAST** 2 weeks in advance.  Some requests take a significant amount of time and coordination to implement, so start the process as soon as you know you will need one. 
- This issue will be used from initial request through implementation to ensure all individuals working on this are notified of status updates.  Please do not create multiple issues to track differnt steps.
- It is your responsibility to notify VA stakeholders as appropriate.  

### Type of request
- [x] We are retiring or taking down a page and need to redirect the URL (complete redirect section)
- [ ] We are changing the URL of an existing page (complete redirect section)
- [ ] We need a custom vanity URL (complete vanity URL section)

We are redirecting these legacy pages to a modernized version of the page.

### Implementation date
When does this request need to be live: morning of January 3, 2023.  **CAN DEPLOY ~~with weekly deploy on Jan 4~~. Should _not_ go live prior to Jan 3.**
**GOAL:** implement and get merged during code freeze, prior to NYE holiday.

### Redirects 
Current URL  |  Redirect Destination or New URL
---  |  ---
https://www.benefits.va.gov/insurance/valife.asp|https://www.va.gov/life-insurance/options-eligibility/valife
https://www.benefits.va.gov/insurance/valife-rates.asp| https://www.va.gov/life-insurance/options-eligibility/valife

**Link to campaign landing page request issue:**

### Process, Roles and Responsibilities
- [x] Requesting team: Above information is provided
- [x] Requesting team: All appropriate VA stakeholders are notified as appropriate
- [x] IA: Request is vetted and documented and implementation plan is clear 
- [x] IA: Request is assigned to appropriate team for implementation 
- [ ] Implementation team: Work is complete
- [ ] Implementation team: Validated in production
- [ ] Requesting team: Validates everything is correct in production and closes ticket

**Comment by laurwill** [comment]
Hi @jilladams ,
Just updating here that it's okay for these redirects to go live with the automatic deploy on Wednesday Jan 4 — we don't need to request an OOB deploy for these on Tuesday morning.
(We're redirecting legacy pages to a new page we're publishing on Tuesday morning, but it's okay if the legacy pages are still visible for another day.)

**Comment by jilladams** [comment]
Really helpful clarification. I actually moved this back a sprint, as we'll prob need to implement prior to NYE holiday in order to hit that deployment, in general.

**Comment by jilladams** [comment]
@apisandipas possible to put up a PR to revert these 2 changes temporarily? Timing note in ticket body: `When does this request need to be live: morning of January 3, 2023. **CAN DEPLOY with weekly deploy on Jan 4. Should _not_ go live prior to Jan 3.**`

**Comment by jilladams** [comment]
These redirects are live and verified in Prod.
