### ISSUE TITLE
Redirect Request for Vet Centers live as of 12/9/22 - no hard timing

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-cms#11903]
### Type of request
- [ ] We are retiring or taking down a page and need to redirect the URL (complete redirect section)
- [x] We are changing the URL of an existing page (complete redirect section)
- [ ] We need a custom vanity URL (complete vanity URL section)

### Implementation date
When does this request need to be live:  no hard timing

### Redirects 

Current URL | Redirect Destination or New URL
-- | --
www.va.gov/find-locations/facility/vc_0859MVC | https://www.va.gov/stark-county-vet-center/
www.va.gov/find-locations/facility/vc_0241V | https://www.va.gov/stark-county-vet-center/
https://www.va.gov/directory/guide/facility.asp?ID=6157&dnum=All | https://www.va.gov/stark-county-vet-center/
https://www.va.gov/directory/guide/keystaff.cfm?id=6157 | https://www.va.gov/stark-county-vet-center/
www.va.gov/find-locations/facility/vc_0416V | https://www.va.gov/st-paul-vet-center/
https://www.va.gov/directory/guide/facility.asp?ID=426&dnum=All | https://www.va.gov/st-paul-vet-center/
https://www.va.gov/directory/guide/keystaff.cfm?id=426 | https://www.va.gov/st-paul-vet-center/
www.va.gov/find-locations/facility/vc_0409V | https://www.va.gov/fort-wayne-vet-center/
https://www.va.gov/directory/guide/facility.asp?ID=437&dnum=All | https://www.va.gov/fort-wayne-vet-center/
https://www.va.gov/directory/guide/keystaff.cfm?id=437 | https://www.va.gov/fort-wayne-vet-center/
www.va.gov/find-locations/facility/vc_0816MVC | https://www.va.gov/clearwater-vet-center/
www.va.gov/find-locations/facility/vc_0339V | https://www.va.gov/clearwater-vet-center/
https://www.va.gov/directory/guide/facility.asp?ID=5902&dnum=All | https://www.va.gov/clearwater-vet-center/
https://www.va.gov/directory/guide/keystaff.cfm?id=5902 | https://www.va.gov/clearwater-vet-center/
www.va.gov/find-locations/facility/vc_0420V | https://www.va.gov/evanston-vet-center/
https://www.va.gov/directory/guide/facility.asp?ID=5048&dnum=All | https://www.va.gov/evanston-vet-center/
https://www.va.gov/directory/guide/keystaff.cfm?id=5048 | https://www.va.gov/evanston-vet-center/
www.va.gov/find-locations/facility/vc_0853MVC | https://www.va.gov/evanston-vet-center/

### Process, Roles and Responsibilities
- [ ] Requesting team: Above information is provided
- [ ] Requesting team: All appropriate VA stakeholders are notified as appropriate
- [ ] IA: Request is vetted and documented and implementation plan is clear 
- [ ] IA: Request is assigned to appropriate team for implementation 
- [ ] Implementation team: Work is complete
- [ ] Implementation team: Validated in production
- [ ] Requesting team: Validates everything is correct in production and closes ticket

**Comment by jilladams** [comment]
I may have jumped the gun here moving this ticket over to our board. This ticket still needs IA review from @heyjoni ?

**Comment by heyjoni** [comment]
Thanks for tagging me. There's a typo in the St. Paul Vet center links (the period in the URL needs to be removed). Other than that, these are good to go. I can't edit the ticket but here are the correct links:


Current URL | Redirect Destination or New URL
-- | --
www.va.gov/find-locations/facility/vc_0859MVC | https://www.va.gov/stark-county-vet-center/
www.va.gov/find-locations/facility/vc_0241V | https://www.va.gov/stark-county-vet-center/
https://www.va.gov/directory/guide/facility.asp?ID=6157&dnum=All | https://www.va.gov/stark-county-vet-center/
https://www.va.gov/directory/guide/keystaff.cfm?id=6157 | https://www.va.gov/stark-county-vet-center/
www.va.gov/find-locations/facility/vc_0416V | https://www.va.gov/st-paul-vet-center/
https://www.va.gov/directory/guide/facility.asp?ID=426&dnum=All | https://www.va.gov/st-paul-vet-center/
https://www.va.gov/directory/guide/keystaff.cfm?id=426 | https://www.va.gov/st-paul-vet-center/
www.va.gov/find-locations/facility/vc_0409V | https://www.va.gov/fort-wayne-vet-center/
https://www.va.gov/directory/guide/facility.asp?ID=437&dnum=All | https://www.va.gov/fort-wayne-vet-center/
https://www.va.gov/directory/guide/keystaff.cfm?id=437 | https://www.va.gov/fort-wayne-vet-center/
www.va.gov/find-locations/facility/vc_0816MVC | https://www.va.gov/clearwater-vet-center/
www.va.gov/find-locations/facility/vc_0339V | https://www.va.gov/clearwater-vet-center/
https://www.va.gov/directory/guide/facility.asp?ID=5902&dnum=All | https://www.va.gov/clearwater-vet-center/
https://www.va.gov/directory/guide/keystaff.cfm?id=5902 | https://www.va.gov/clearwater-vet-center/
www.va.gov/find-locations/facility/vc_0420V | https://www.va.gov/evanston-vet-center/
https://www.va.gov/directory/guide/facility.asp?ID=5048&dnum=All | https://www.va.gov/evanston-vet-center/
https://www.va.gov/directory/guide/keystaff.cfm?id=5048 | https://www.va.gov/evanston-vet-center/
www.va.gov/find-locations/facility/vc_0853MVC | https://www.va.gov/evanston-vet-center/

**Comment by jilladams** [comment]
Thanks! Updated ticket body

**Comment by chri5tia** [comment]
https://github.com/department-of-veterans-affairs/devops/pull/12402
