### ISSUE TITLE
Add pathauto to VAMC banner alerts and health services nodes

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#1191]
## User Story or Problem Statement

As a VAMC editor working on a VAMC nodes that don't have have FE stand-alone versions, i still want decent URL aliases, so that i know "where i am". 

## Acceptance Criteria
* VAMC banner alert pattern: `/[field_administration]/vamc-banner-alert/[date created]/[node title]`
* VAMC system health service `/[node:field_office]/health-services/[node:title]`
* VAMC facility health service `/[node:field_office]/[node:field_facility]/health-service/[node:title]`
* we have validated that no node types are missing pathauto. 

## Implementation steps
1. Update pathauto settings
2. Deploy to prod
3. Run pathauto updates on prod (consider an update hook for this too)

**Comment by oksana-c** [comment]
Revised patterns:

-  VAMC banner alert pattern `[node:field_administration:entity:name]/vamc-banner-alert/[node:changed:html_date]/[node:title]`
-  VAMC system health service `[node:field_administration:entity:name]/system-health-services/[node:title]`
-  VAMC facility health service `facility-health-services/[node:title]`
