### ISSUE TITLE
Redirect Request for 3 life insurance URLs - (client-side) target deploy before holiday code freeze

### ISSUE THREAD

**Issue by laurwill** [department-of-veterans-affairs/va.gov-cms#11918]
### Instructions
- Requests must be submitted **AT LEAST** 2 weeks in advance.  Some requests take a significant amount of time and coordination to implement, so start the process as soon as you know you will need one. 
- This issue will be used from initial request through implementation to ensure all individuals working on this are notified of status updates.  Please do not create multiple issues to track differnt steps.
- It is your responsibility to notify VA stakeholders as appropriate.  

### Type of request
- [x] We are retiring or taking down a page and need to redirect the URL (complete redirect section)
- [ ] We are changing the URL of an existing page (complete redirect section)
- [ ] We need a custom vanity URL (complete vanity URL section)

### Implementation date
When does this request need to be live: before end of year holiday code freeze

### Redirects 
Current URL  |  Redirect Destination or New URL
--- | ---
https://www.benefits.va.gov/insurance/choose.asp  |  https://www.va.gov/life-insurance/manage-your-policy/
https://www.benefits.va.gov/insurance/OPA.asp  |  https://www.va.gov/life-insurance/manage-your-policy/
https://www.benefits.va.gov/INSURANCE/tsgli-claim-questionnaire.asp  |  https://www.va.gov/life-insurance/options-eligibility/tsgli/

### Process, Roles and Responsibilities
- [x] Requesting team: Above information is provided
- [x] Requesting team: All appropriate VA stakeholders are notified as appropriate
- [x] IA: Request is vetted and documented and implementation plan is clear 
- [x] IA: Request is assigned to appropriate team for implementation 
- [ ] Implementation team: Work is complete
- [ ] Implementation team: Validated in production
- [ ] Requesting team: Validates everything is correct in production and closes ticket

**Comment by jilladams** [comment]
Update again: because this change happens in vets-website and not devops repo, this isn't subject to the weekly deploy, instead can deploy with any daily deploy, and therefore the original ask to deploy before the holiday code freeze stands.

**Comment by jilladams** [comment]
Change is merged, deployed to staging. Moved to PO Review, to verify in prod before closing. Should go out in today's daily deploy.

**Comment by jilladams** [comment]
Verified in Prod.
