### ISSUE TITLE
FE: Lovell Federal Health care System page should not exist 

### ISSUE THREAD

**Issue by dsinla** [department-of-veterans-affairs/va.gov-cms#11939]
## Description

There are some checks and balances in place to prevent this page from being published, but removing it from existence would prevent any unforeseen errors or someone from accidentally publishing it or linking to it somehow. 

POST MVP: not urgent 

## Acceptance Criteria
- [ ] Lovell Federal Health care System page no longer exists in the FE 

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by swirtSJW** [comment]
This ticket is already handled in the CMS that the page can not be edited or published.  This is just making sure the FE is following the same rules.  Not a required ticket but a nice fail-safe.

**Comment by Dottisea** [comment]
Iceboxed

**Comment by swirtSJW** [comment]
This ticket is a bit non-sensical and dangerous.  This page is critical to our three sections structure in the CMS and can not be removed.  This ticket should be closed.
