### ISSUE TITLE
Redirect Request: White Plains Vet Center is now Westchester Vet Center

### ISSUE THREAD

**Issue by stefaniefgray** [department-of-veterans-affairs/va.gov-cms#11933]
### Instructions
- This issue will be used from initial request through implementation to ensure all individuals working on this are notified of status updates.  Please do not create multiple issues to track different steps.
- It is your responsibility to notify VA stakeholders as appropriate.
- Be sure to link the related facility closure / rename issue.
- Front end redirects are tracked in the [devops](https://github.com/department-of-veterans-affairs/devops) repo in `ansible/deployment/config/revproxy-vagov/vars/redirects.yml`

See https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11931

### Implementation date
**When does this request need to be live?:** ASAP, per Tiffany Lever in https://va-gov.atlassian.net/browse/VAHELP-5125

### Redirects 
| Current URL  |  Redirect Destination or New URL |
| ---  |  --- |
| `va.gov/white-plains-vet-center` | `va.gov/westchester-vet-center` |

## CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [x] `⭐️ User support`

**Comment by stefaniefgray** [comment]
@JayDarnell Ticket just came in re: the Westchester Vet Center -> White Plains Vet Center name change and URL redirect — https://va-gov.atlassian.net/browse/VAHELP-5324

```
URL is down. "sorry cannot find that page."
URL was https://www.va.gov/white-plains-vet-center
I am wondering if it is being changed to match our new vet center name: Westchester Vet Center? 
Can't see either online, however I can log into CMS and edit and preview.
```

**Comment by JayDarnell** [comment]
@stefaniefgray this redirect was already performed here: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12059

The reason we see a 404 not found on the front end is because the name change hasn't been implemented on the CMS side.
