### ISSUE TITLE
PM: Create draft of KB for Listing page behavior

### ISSUE THREAD

**Issue by dsinla** [department-of-veterans-affairs/va.gov-cms#11936]
## Description
We need a KB for Lovell editors to address the special behavior of Listing pages

## User story
As a Lovell Editor, I want clear instructions for how to author and assign the following items:

- Event
- News Release
- Story

I want instructions for how I list these on Lovell - VA, on Lovell - Tricare, or how I can list an item on both.

## Acceptance Criteria
- [x] Draft is created and reviewed by Dev
- [ ] Feedback incorporated 
- [ ] Draft is handed over to Support for publishing 

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by JQuaggles** [comment]
@stefaniefgray I'm assuming we have a KB for regular VAMC Facilities. Can you throw me that if you have that handy? I want to make sure I use the same format. I also realized it will be difficult to do this without access to the CMS since I don't have that yet. :D

**Comment by JQuaggles** [comment]
Wondering if this overlaps with:
https://app.zenhub.com/workspaces/sitewide-facilities-639f5253e4b702a32376339e/issues/gh/department-of-veterans-affairs/va.gov-cms/11687

**Comment by stefaniefgray** [comment]
@JQuaggles 

**Events:**
https://prod.cms.va.gov/help/vamc/about-events-content-for-vamcs
https://prod.cms.va.gov/help/cms-basics/how-to-edit-an-event
https://prod.cms.va.gov/help/va-medical-centers-vamcs/about-events-content-for-vamcs/how-to-edit-an-events-list

**News Releases:**
https://prod.cms.va.gov/help/vamc/about-news-release-content-for-vamcs/how-to-add-a-news-release
https://prod.cms.va.gov/help/vamc/about-news-release-content-for-vamcs/what-is-a-news-releases-list
https://prod.cms.va.gov/help/vamc/about-news-release-content-for-vamcs

**Stories:**
https://prod.cms.va.gov/help/va-medical-centers-vamcs/about-stories-content-for-vamcs/how-to-add-a-story
https://prod.cms.va.gov/help/va-medical-centers-vamcs/about-stories-content-for-vamcs/how-to-edit-a-stories-list
https://prod.cms.va.gov/help/vamc/about-stories-content-for-vamcs
https://prod.cms.va.gov/help/vamc/how-do-i-feature-a-story-on-my-sites-homepage

This Lovell one will take lots of QAing though, to double-check expected listing behavior 😬

**Comment by JQuaggles** [comment]
https://app.zenhub.com/workspaces/sitewide-facilities-639f5253e4b702a32376339e/issues/gh/department-of-veterans-affairs/va.gov-cms/11687

Closing this issue. Will have devs review other ticket.
