### ISSUE TITLE
`drush updatedb` should return RC 1 on failure (current is 0)

### ISSUE THREAD

**Issue by ElijahLynn** [department-of-veterans-affairs/va.gov-cms#1193]
**Describe the defect**
`drush updatedb` is returning an RC of 0 right now on failures. Causing our yaml-tests to succeed. 

**To Reproduce**
1. `git checkout 17e1f9402`
2. Run `lando composer yaml-tests update`
3. Observe "Requirements check reports errors.`
4. Test is passed. 

**Expected behavior**
Test should fail 

**Screenshots**
![image](https://user-images.githubusercontent.com/1504756/76241904-f7776b80-61f2-11ea-913a-17afb8585d9c.png)

**Additional context**
There are multiple issues in Drush repo about this, most recent one appears to be https://github.com/drush-ops/drush/pull/3673. We should make sure the version is up to date and contains this code etc. 

## Labels
- [/] Issue type (red) (defaults to "Defect")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [/] CMS objective (orange) (not needed for bug tickets)
- [ ] CMS-supported product (black)

**Comment by ElijahLynn** [comment]
This should not be merged until #1183 is resolved otherwise all tests will start failing.

**Comment by acrollet** [comment]
The upstream issue is resolved well before our current version `10.4.0`, closing this out.
