### ISSUE TITLE
Facility name change: White Plains Vet Center is now Westchester Vet Center

### ISSUE THREAD

**Issue by stefaniefgray** [department-of-veterans-affairs/va.gov-cms#11931]
## Intake
- [x] Submitter: Tiffany Lever, Vet Centers team
- [x] If the submitter is an editor, send them the link to the CMS Knowledge Base (KB) article on facility basic data for their product (VAMC or Vet Center). Let them know that facility changes can take between 75 days and 4 months after submitting a request, according to VAST administrators.
- [x] If the change is a facility closure, send the editor a link to the operating status KB article and have them change the status to Facility notice and provide a description of the facility closure so that Veterans are aware of the future closure.
- [x] Other stakeholders to include on updates, if any: (See below)

See associated Slack thread: https://dsva.slack.com/archives/C02730UEZPS/p1670600494100799
Jira ticket: https://va-gov.atlassian.net/browse/VAHELP-5125

## Vet Center – facility name change

- [x] The H1 title change comes from Lighthouse to Drupal. _(Runbook note: I don't think this happens for Vet Center name changes.)_
- Is the new official name plain language (Does it match the pattern <city> Vet Center)?
  - [x] If yes, update the common name to match (when #6955 Unlock title field on Vet Centers is handled).
- Is the Vet Center published?
  - If yes:
    - [x] CMS team submits [redirect request](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/new?assignees=&labels=Redirect+request&template=redirect-request-facility-url.md&title=Redirect+Request+for%3A+%3Cinsert+facility+name%3E), cc'ing Facilities team
    - [x] Once timing of Redirect going live is known, alert CMS engineers to carry out steps in **Update ready** section below
  - If no: CMS engineers may continue with **Update ready** section below
- Update ready
    - [x] CMS engineer: visit bulk operations page and filter by section = vet center name
    - [x] CMS engineer: update URLs for all content in that section by bulk operations.
    - [x] CMS engineer: **if a new section was created** - update field value for section by bulk operations.
    - [x] CMS engineer: resave all content in that section by bulk operations.
    - [x] CMS engineer edit Vet Center node and remove flag `Changed name` then save node.
- Is the Vet Center published?
  - [ ] If no, HD notifies Michelle Middaugh to bulk publish.
  - [ ] HD notifies editor and any other stakeholders.

## Acceptance criteria
"White Plains Vet Center" is changed to "Westchester Vet Center" across the site and all sections/menus

## CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [x] `⭐️ User support`

**Comment by JayDarnell** [comment]
Redirect request: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12059

**Comment by JayDarnell** [comment]
Redirect is not yet live.

**Comment by JayDarnell** [comment]
This should be good to go now @stefaniefgray - the next content release should pick up the changes and push them to va.gov. Please check with the editor to be sure everything is okay. I'm updating the runbook for vet centers because I found these steps in the current runbook to be insufficient.

**Comment by stefaniefgray** [comment]
Confirmed resolved
