### ISSUE TITLE
PM: Bring Lovell to Collab Cycle Staging Review 

### ISSUE THREAD

**Issue by dsinla** [department-of-veterans-affairs/va.gov-cms#11935]
## Description
The final step in the Collab Cycle prior to launch of Lovell is to bring it to the Staging Review 

## Acceptance Criteria
- [x] Collab cycle is conducted (sync or async TBD)
- [x] Feedback is addressed 

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [ ] `⭐️ User support`

Collab Cycle Ticket:

https://github.com/department-of-veterans-affairs/va.gov-team/issues/52672#:~:text=Facilities%2C%20VAMC%2C%20Lovell%5D-,%23,-52672

**Comment by davidmpickett** [comment]
@JQuaggles Context for this ticket
- Process - https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/staging-review
- Previous collab cycle touchpoint for Lovell - https://github.com/department-of-veterans-affairs/va.gov-team/issues/45628

**Comment by Dottisea** [comment]
Collab cycle ticket https://github.com/department-of-veterans-affairs/va.gov-team/issues/52672#:~:text=Collaboration%20Cycle%20for%20%5BSitewide%20Facilities%2C%20VAMC%2C%20Lovell%5D%20%2352672
