### ISSUE TITLE
FE: Spotlight section is missing “In the spotlight” header

### ISSUE THREAD

**Issue by davidmpickett** [department-of-veterans-affairs/va.gov-cms#11940]
https://web-liqqgmzl7tsyfbwyulbkuborufuuttav.demo.cms.va.gov/lovell-federal-va-health-care/
https://web-liqqgmzl7tsyfbwyulbkuborufuuttav.demo.cms.va.gov/lovell-federal-tricare-health-care/

On both Lovell Tricare and Lovell VA system pages, the "In the spotlight" section is missing the header.

![Screen Shot 2022-12-06 at 2 50 22 PM](https://user-images.githubusercontent.com/766573/206020194-af113466-8db3-4bdf-b7d8-a4fb58c14d6b.png)

## Engineering notes
This is controlled in this template: `src/site/paragraphs/facilities/list_of_link_teasers_facility.drupal.liquid`:
```
    <h3 class="vads-u-margin-bottom--2">
        {% if regionNickname != empty %}
            In the spotlight at {{ regionNickname }}
        {% else %}
            {{ paragraph.fieldTitle }}
        {% endif %}
    </h3>
```
The `<h3>` is there, as expected, but it's empty. It seems that `regionNickname` is coming through empty. We'll need to nail down why that's the case and then fix that.

## Acceptance criteria
- [x] Lovell VA system page shows 'In the spotlight at Lovell Federal VA Health Care System"
- [x] Lovell Tricare system page shows 'In the spotlight at Lovell Federal Tricare Health Care System"

**Comment by davidconlon** [comment]
Are these links hardcoded for VAMCs or is there flexibility (I don't remember) because this may be related to #11832 as most of these links are also VA-only options.

May be a non-issue because they could all be editor controlled links?

**Comment by JQuaggles** [comment]
@davidmpickett Do you have a note where this issue is appearing? (ie which specific pages)

**Comment by davidmpickett** [comment]
This appears to be an issue on the 2 VAMC System homepages:

- https://main-liqqgmzl7tsyfbwyulbkuborufuuttav.demo.cms.va.gov/lovell-federal-tricare-health-care?_format=static_html
- https://main-liqqgmzl7tsyfbwyulbkuborufuuttav.demo.cms.va.gov/lovell-federal-va-health-care?_format=static_html

![spotlight](https://user-images.githubusercontent.com/51967950/208335294-8491b344-ee8a-4d39-afd9-6d2ff75f6b6e.png)

The spotlight block also shows up on individual location pages, but seems to be working fine there:

- https://main-liqqgmzl7tsyfbwyulbkuborufuuttav.demo.cms.va.gov/lovell-federal-va-health-care/locations/captain-james-a-lovell-federal-health-care-center?_format=static_html
- https://main-liqqgmzl7tsyfbwyulbkuborufuuttav.demo.cms.va.gov/lovell-federal-tricare-health-care/locations/captain-james-a-lovell-federal-health-care-center?_format=static_html
- https://main-liqqgmzl7tsyfbwyulbkuborufuuttav.demo.cms.va.gov/lovell-federal-va-health-care/locations/kenosha-va-clinic?_format=static_html
- https://main-liqqgmzl7tsyfbwyulbkuborufuuttav.demo.cms.va.gov/lovell-federal-tricare-health-care/locations/uss-red-rover?_format=static_html
- 
![spotlight2](https://user-images.githubusercontent.com/51967950/208335708-356b5712-79a5-4edf-bf6d-ff46d886c001.png)

**Comment by davidmpickett** [comment]
Another likely tanner ticket
