### ISSUE TITLE
Facility name change: Anaheim VA Clinic is now Placentia VA Clinic

### ISSUE THREAD

**Issue by stefaniefgray** [department-of-veterans-affairs/va.gov-cms#11952]
## Intake
- [x] Submitter: Soua Thao, VA Long Beach
- [x] If the submitter is an editor, send them the link to the CMS Knowledge Base (KB) article on facility basic data for their product (VAMC or Vet Center). Let them know that facility changes can take between 75 days and 4 months after submitting a request, according to VAST administrators.
- [ ] If the change is a facility closure, send the editor a link to the operating status KB article and have them change the status to Facility notice and provide a description of the facility closure so that Veterans are aware of the future closure.
- [ ] Other stakeholders to include on updates, if any: <insert name>

See https://va-gov.atlassian.net/browse/VAHELP-5225
Prod link: https://prod.cms.va.gov/long-beach-health-care/locations/anaheim-va-clinic

This facility came up during VHA DM office hours on 12/14/2022

## Acceptance criteria

- [x] The H1 title change comes from Lighthouse to Drupal.
- [x] Coordinate with Facilities team to create a [redirect request](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/new?assignees=&labels=Redirect+request&template=redirect-request-facility-url.md&title=Redirect+Request+for%3A+%3Cinsert+facility+name%3E)
- [x] CMS engineer locates the newly renamed VAMC Facility (https://prod.cms.va.gov/admin/content/bulk) Search by new name
- [x] CMS engineer updates URL alias for this facility
- [x] CMS engineer resaves this facility
- [x] CMS engineer makes bulk alias changes to facility service nodes. (https://prod.cms.va.gov/admin/content/bulk?type=health_care_local_health_service)
- [x] CMS engineer bulk saves fixed titles to facility service nodes. (https://prod.cms.va.gov/admin/content/bulk?type=health_care_local_health_service)
- [x] CMS engineer updates menu title for facility
- [ ] CMS engineer updates Alt text for facility image, if relevant.
- [x] CMS engineer updates Meta description (TBD: some backwards compatibility for SEM, by including something like ", formerly known as [previous name]".
- [x] CMS engineer edit facility node and remove flag `Changed name` then save node.
- [ ] HD notifies editor and any other stakeholders.
</details>

## CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [x] `⭐️ User support`

**Comment by JayDarnell** [comment]
Redirect request has been created: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12067

**Comment by JayDarnell** [comment]
Redirect request is not yet live.

**Comment by stefaniefgray** [comment]
Redirect request still not live

**Comment by JayDarnell** [comment]
Redirect request has gone live and dev tasks to support rename have been completed.
