### ISSUE TITLE
Drupal: Implement Drupal menu to manage new home page Hub list and add "12th Hub" menu item for "VA Departments" link

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#11968]
## User stories
As a VAgov visitor who is interested in _non-Veteran-facing_ topics, I want to see a link to the new VA Departments website on the homepage in the same area where Benfit Hubs are listed so that it's easy for me to find what interests me.

As a visitor to the new home page, I want to see the list of Benefit Hubs in order of relevance.

Daniel started the CMS backend work and is available [here](https://github.com/dsasser/va.gov-cms/tree/VACMS-11968-hub-list-as-menu). It creates the new menu and related fields, but needs another pass to confirm it aligns to the Figma design.

### Background
The current homepage of VA.gov displays a Benefit Hub List, set up right now as an EntityQueue that publishes Benefit Hub Landing Pages _only_. The icon, link, label, and teaser text are provided by the BHLP content type. 

The new home page design specifies: 
1.  A new order for Benefit Hubs in the list
2. A "12th Benefit Hub:" VA Dept Info. This item is not actually a Benefit Hub Landing Page, but a link out to a Wordpress site built on a VA subdomain. 
<img width="201" alt="image" src="https://user-images.githubusercontent.com/4054752/207937406-a906fc3c-0a60-4030-b111-7c61aac1f96a.png">

In order to accommodate these 2 changes, we must update how the Hub List data is managed. We will implement as a menu, with updated order, and with added 12th item for VA Dept Info.

How this implementation was defined:
- SPIKE: #11370 
- Problem and possible solution is captured in [this slack thread](https://dsva.slack.com/archives/C03NSH4SLQY/p1671125891943039). 
- CMS Collab Cycle approved menu approach: #12044 

### Implementation details
ACs describe hiding some default fields, one of which (Show as expanded checkbox) should be hidden from every role except Admin. 
  - Per [this Slack thread with Steve](https://dsva.slack.com/archives/C52CL1PKQ/p1675115086434309?thread_ts=1675112209.838239&cid=C52CL1PKQ), to implement this, we use the user perms service to check for admin.  The first line is only needed if doing it in a hook that does not support Dependency injection.

```
$perms_service = \Drupal::service('va_gov_user.user_perms');
if (!$perms_service->hasAdminRole(TRUE)) {
```

It should go in an event subscriber like this `docroot/modules/custom/va_gov_vet_center/src/EventSubscriber/EntityEventSubscriber.php`, in a new module `va_gov_home` rather than putting it in `va_gov_backend`.

- In the menu link field, we will not offer links to nodes/content as "entity references." ([comment](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11968#issuecomment-1402557097)).
we not do offer an additional entity ref field, for the following reasons:
- Character limits were provided [in Mural](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11968#issuecomment-1402621054) by Sitewide Content team

## Acceptance Criteria
- [x] Decision to drive this with menu is captured in [decision log](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/public-websites/home-page/home-page-redesign-initiative/decision-log.md) – in product outline (can point back to the epic/tickets)
- [x] Design follows result of #12304 ([Figma file](https://www.figma.com/file/nPSOXFJN41CZGmK2eXgvoy/HUB-List-Menu?node-id=46%3A1546&t=q4uq7AsNpchdE1FZ-1))
- [x] A new menu is created in Drupal, `VA.gov home page benefit hub list`, which can be queried to build the Hub List, which includes:
**Structure:**
  - [x] Menu Administrative summary: `Menu on VA.gov new home page that displays Benefit Hubs`
  - [ ] Default menu fields (Menu link title, Link, Description, Parent link, Weight)
    - [x] Remove (possible?) or hide`Attributes` accordion to prevent data entry in `target` or `class`
    - [x] Hide "Show as expanded" checkbox for this menu type
    - [ ] Hide "View mode" and "Parent link" fields for non-admins (role-based)
  - [x] New custom field: `Hub list icon` - select list that will not re-use any existing icon lists, and will include `VA Department Info`. Required field, with no "None" option.
  - [x] New custom field: `Link summary` - textarea, max 180 chars. Required.
  - [x] `Menu link title` limited to 25 characters (per SW Content team; same mural). Required.
  - [x] Helper text included per design
  - [ ] Requires design review
  - [x] GraphQL provided and added to #12351 
**Content:**
- [x] All 11 Hub list links from the current [entityqueue](https://prod.cms.va.gov/admin/structure/entityqueue/home_page_hub_list/home_page_hub_list?destination=/admin/structure/entityqueue), matching the order specified in the [Sketch file for new homepage design ](https://www.sketch.com/s/3aa40506-4be2-46cc-876b-93f1a9f3a857/p/EAD305BC-3082-4F81-ADEC-C2486F7B6BEF/canvas)(different than entityqueue/live homepage order)
- [x] New 12th item: `VA department information`, https://department.va.gov/,  summary = Learn more about the VA departments that manage our benefit and health care programs.

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by jilladams** [comment]
Per refinement with Dave on 12/15: 
* Site being linked to is a Wordpress site in dev by OPIA
* It is blocked on review / approval by the Secretary
* When it is approved / launched, it will not be a PW fire drill to publish this link out to it. 

Meaning: we have time to work out the correct solution.

**Comment by jilladams** [comment]
After #12044 for this project, this ticket needs updated for modernity, including: 
* What fields should appear in the Menu items
* Draft copy for the UI
* ACs (scope + 508 / design / Swirt on code review)

Assigning to @wesrowe  / moving to "Needs product definition."

**Comment by dsasser** [comment]
> Can/should we offer links ("entity references"?) to nodes/content? Or will links to drupal content (e.g., benefit hub landing pages) be hard-coded?

Is the idea behind using a separate entity ref field for referencing BHLP to ease in sharing icons and other fields?

I would suggest we not do offer an additional entity ref field, for the following reasons:

- UX would be impacted. We would end up with two ways to add hub list item, either as a ref to a BHLP, or by entering data in separate fields. Adding some code to help with the if/then scenario would probably create tech debt should the underlying core menu markup change.
- Additional work on the FE would be necessary to handle identifying the icon from a referenced entity or from distinct fields.
- The hub list items rarely change.

**Comment by dsasser** [comment]
> Should there be a character limit on description text?

There is a character limit of 255 characters on the description field, but it isn't exposed to the user in any way. Since this field is not "configurable" (no UI for managing the display of the field), we would need to add custom code to expose the field in the 'manage form' page, and then from there we would be able to use the maxLength module to add the relevant maximum length info which is found on many other fields in the CMS.

The lift to do this is in the small to medium range.

**Comment by wesrowe** [comment]
@dsasser, related question on character limits – Can we set a char limit on the menu link text? SW Content team requested a limit of 25 chars. But afaik the link text field is a default field – so would that be harder, maybe similar to your first case above?

**Comment by dsasser** [comment]
> @dsasser, related question on character limits – Can we set a char limit on the menu link text? SW Content team requested a limit of 25 chars. But afaik the link text field is a default field – so would that be harder, maybe similar to your first case above?

We could do that, but the same situation applies here as the core description field [as noted above](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11968#issuecomment-1402621054). There is a [Drupal contrib module](https://www.drupal.org/project/base_field_override_ui) which exposes these types of fields in the Admin UI, which I tested quickly to confirm it would work to allow us to easily add character limits to the link text (Title) field. So providing we are good to use that module (I haven't done a code review yet), the lift should be trivial.

**Comment by dsasser** [comment]
PR ready for review: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11968

**Comment by thejordanwood** [comment]
Looks good! This is approved and has design sign off.
