### ISSUE TITLE
Hold jam session to flesh out list of runbooks in epic

### ISSUE THREAD

**Issue by davidmpickett** [department-of-veterans-affairs/va.gov-cms#11966]
## Description
The existing Facilities runbooks need updates, and should be reviewed for process inefficiencies. There are also runbooks that currently do not exist, and should be created.

**Preliminary notes document:** https://docs.google.com/document/d/1FoOvOsX3oEg7dqT-A7pu6jvrmRPKjbkjfYsd3pWECrA/edit#

## Acceptance Criteria
- [ ] Tickets are created in epic

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by stefaniefgray** [comment]
See notes on runbooks that should exist: https://docs.google.com/document/d/1FoOvOsX3oEg7dqT-A7pu6jvrmRPKjbkjfYsd3pWECrA/edit#

**Comment by stefaniefgray** [comment]
Discussed with @TroyA6 and sent him above Google Doc to contribute ideas

**Comment by kmariepat-cityfriends** [comment]
Make sure this session includes dicussion around the redirect link process. (context on adjusting this process: It really needs to start with Content/IA team)

**Comment by kmariepat-cityfriends** [comment]
Make sure this session includes dicussion around the redirect link process. (context on adjusting this process: It really needs to start with Content/IA team)

**Comment by JayDarnell** [comment]
Preliminary changes to create an improved file structure and standardize runbook language ahead of the jam session can be found here: https://github.com/department-of-veterans-affairs/va.gov-cms/pull/12860/

**Comment by JayDarnell** [comment]
The following link contains my initial proposed revisions for these files to be used as a basis for the "jam session" https://github.com/JayDarnell/va.gov-cms/tree/VACMS-11966/.github/ISSUE_TEMPLATE
