### ISSUE TITLE
Bug: Analytics (GA) added to NEW home page are not visible in GA platform

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#11965]
**Currently BLOCKED on [Platform Analytics team implementation ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/50836)**

## Description

On both the existing homepage and the [new homepage](https://staging.va.gov/new-home-page/), additions to GA are not making it through to GA. Work was detailed in following stories:
- #11467
- #11324

**Expected behavior:**
New GA events should show in the GA platform, e.g.:
  - Header - Disability - Check your claim or appeal status
  - Header - Life insurance - Check your appeal status

**Actual behavior:**
These events are not visible in GA. At this point they should have data.

These new events are visible in browser console using both AdSwerve and GA Debugger plugins, and that's how they were QAed. However, in AdSwerve the new events don't have the yellow GA flag that we think indicates successful parsing by GA (or a GA equivalent parser in AdServe plugin).

_Example in AdSwerve of "old" event that's still making it through:_
![image](https://user-images.githubusercontent.com/4054752/207926852-e78f4998-0ed0-4607-b658-499966a2676a.png)

_Example in AdSwerve of new event that is not-yellow:_
![image](https://user-images.githubusercontent.com/4054752/207927106-255270b7-e47e-4e61-9a97-6848df180d8f.png)

## Acceptance Criteria
- [ ] TBD: remove any new standard events from #12065 / #12048
- [ ] All the new analytics events need are yellow-flagged in AdSwerve
- [ ] Requires product review

### List from #11324 
- [ ] Mega menu events identify the benefit program from which it was clicked
   - [ ] Header - Disability - Check your claim or appeal status
   - [ ] Header - Life insurance - Check your appeal status
   - [ ] Header - Housing - Check your appeal status
   - [ ] Header - Disability - View your payment history
   - [ ] Header - Education - View your payment history
   - [ ] Header - Records - View your payment history
   - [ ] Header - Records - Request your military records
   - [ ] Header - Burials and memorials - Request your military records
Events on boxes at far right of mega menu are tracked and identified distinctly from other mega menu events
   - [ ] Header - Education - GI Bill comparison tool
   - [ ] Header - Records - Confirm your VA benefit status
- [ ] CTAs below benefit hub are tracked and identifiable as interactions occurring on the CTAs, rather than elsewhere on the page
   - [ ] Homepage CTA - Find a location
   - [ ] Homepage CTA - Crisis Line
   - [ ] Homepage CTA - Sign In
- [ ] Sign in events on the header are uniquely identified as occurring in the header
   - [ ] Header - Sign in
- [ ] Events on OPIA promo spots are tracked and identifiable as interactions occurring on the promo spots, rather than elsewhere on the page
   - [ ] Homepage - [title] promo - for any OPIA promo above the footer on current homepage
- [ ] Events on PACT Act banner alert are tracked and identified as initiated on alert banner, rather than from a promo block or elsewhere
  - [ ] Footer alert - [title]

### List from #11467
- [ ] Analytics team can help us test these once they are available in staging
- [ ] Create an account events are tracked, distinctly from header sign-in events, such as `Homepage create an account CTA`
- [ ] Events on Benefit promo are tracked by title and as initiated on the body of the homepage, such as `Homepage benefit promo > The PACT Act and your VA benefits` 
- [ ] Search events are tracked and identifiable as interactions occurring on the body of the page, rather than from the header, such as `Homepage > Search`
- [ ] Events on "Other search tools" are tracked by link label, such as `Other search tools  > Find a VA location`
- [ ] Events on "Popular links menu" are tracked by link label, such as `Popular on VA.gov  > Check your claim or appeal status`
- [ ] Events initiated via the VA news promo title link are tracked by name and as initiated on the body of the homepage, such as `Homepage news promo > title > Pathfinder`
- [ ] Events initiated via the VA news promo CTA are tracked by name and as initiated on the body of the homepage, such as `Homepage news promo > CTA > Pathfinder`
- [ ] Events on the More VA news link are identified as initiated on the body of the homepage, such as `Homepage news promo > More VA News`
- [ ] Events on email signup are tracked, such as `Homepage email sign up`
- [ ] Benefit hub events are tracked by Hub title, such a `Benefit hub > VA department`
- [ ] Mega menu event tracking should be maintained
- [ ] Header event tracking should be maintained
- [ ] Footer event tracking should be maintained

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by jilladams** [comment]
https://dsva.slack.com/archives/C03NSH4SLQY/p1671141060371759
> My takeaway is that the work is on the GTM side. 

Marking blocked.

**Comment by jilladams** [comment]
This ticket is blocked by Platform analytics team. 
When they have resolved their issue https://github.com/department-of-veterans-affairs/va.gov-team/issues/50836, we may or may not have work remaining to do to get these GA events working.

**Comment by jilladams** [comment]
Removing from sprint, til their ticket is resolved.

**Comment by wesrowe** [comment]
Josh worked with Michelle Dooley to get GTM wired up. Notes and discussion in https://github.com/department-of-veterans-affairs/va.gov-team/issues/50835. Closing.

Note: We now have two different events firing on the new home page elements. We could clean this up in the future. I'll ticket.
