### ISSUE TITLE
Improve content search tools

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#1196]
### User Story or Problem Statement

As a CMS content editor or manager, i want to be able to see the big picture of my content. 

As a CMS user admin, i want be able to see the big picture of the users. 

### Background

As of March 2020 there are about 3000 nodes. We expect this to increase to 50,000 by the end of 2021. _(40K as of Feb 2022)_

As of March 2020 there are about 50 active users. We expect this to increase to about 1000 by the end of 2021. _(820 as of Feb 2022)_

Drupal core's search indexing tools are not performant for full content searches.  

### Affected users and stakeholders

* All CMS content users
* CMS user admins

### Hypothesis

1. We believe that content managers will more easily find the content they if they can do full text searches, and search with other facets/attributes.

2. We believe that faceted search may provide a useful means of creating dashboard screens that help users find content or users and accomplish their tasks quickly. We'll know this to be true when a variety of users provide feedback on a prototype. 

3. We believe that VA stakeholders, product designers (including CMS product designers) want to understand the big picture so that they can make product or business decisions. We'll know this to be true when a variety of product owners provide feedback on a prototype. 

### Assumptions
* That faceted search is feasible in our infrastructure that is can be built at VA, eg with Solr API or Elastic Search. 

## Acceptance Criteria
* Prototypes have been tested with users.

**Comment by oksana-c** [comment]
noting that Elasticsearch 7.6.x and Solr 8.x.x  are approved w/ constraints by VA OIT. TRM links below:

- [Elasticsearch decision](https://www.oit.va.gov/Services/TRM/ToolPage.aspx?tid=7305&tab=2)
- [Solr decision](https://www.oit.va.gov/Services/TRM/ToolPage.aspx?tid=7005&tab=2)

**Comment by jefflbrauer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VAgov-CMS-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/1196?planning-poker) with ZenHub @ElijahLynn @indytechcook @ndouglas @olivereri @timcosgrove

**Comment by jefflbrauer** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VAgov-CMS-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/1196?planning-poker) with ZenHub @cweagans

**Comment by EWashb** [comment]
Search is also causing content editor confusion around special characters. There are poor search results for title fields that include special characters. See #5885 for more context.
