### ISSUE TITLE
FE: Update "Manage your health online" block for Lovell VA/TRICARE

### ISSUE THREAD

**Issue by JayDarnell** [department-of-veterans-affairs/va.gov-cms#11967]
## User Story or Problem Statement

Design decisions made in #11832 

- Hide this entire block for Lovell TRICARE
- Update the heading for Lovell VA to **Manage your VA health online**

![manage_health_lovell](https://user-images.githubusercontent.com/21045418/207935182-4638f8bb-54e7-4789-be9e-f0f60abf904f.png)

## Acceptance Criteria
- [ ] When viewing the Lovell TRICARE system page the **Manage your health online** block should not be present
- [ ] When viewing the Lovell VA system page the heading for this block should read as **Manage your VA health online**
- [ ] When viewing any other system page the heading and block should still be present and unchanged

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [x] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by davidmpickett** [comment]
For Tanner we think
