### ISSUE TITLE
[Bug] Redesigned Homepage (R3) - Opt-in modal - Re-displayed upon returning to current/existing homepage using Back button

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-cms#11978]
## What happened?
On RI Redesigned Homepage, Opt-in modal displayed again when returning to existing/current homepage from new homepage.

## Specs
Device: Macbook Pro
Browsers: Chrome & Firefox

## Steps to Reproduce
- URL: RI http://a109d22ff3eebd5144235d7057fb577f.review.vetsgov-internal/ [requires SOCKS proxy]
- In **Try our new VA.gov homepage** opt-in modal, click **Try the new home page** link.
- On new homepage, click **VA logo** at top-left corner, or click browser **Back** button.
- On current/existing homepage, observe that Opt-in modal is displayed again.

## Engineering Note
Currently, the link to the new homepage isnt calling "dismiss" on the modal, which triggers the session logic. We'll need to wrap the onClick functionality of the link to also call "dismiss" function.

## Desired behavior
- [ ] Opt-in modal should not be displayed again when returning to current/existing homepage.

## Acceptance Criteria
[see **Desired behavior** above]

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Bug`**

**Comment by jilladams** [comment]
Verified fixed on staging.
