### ISSUE TITLE
Update the design file for COVID editorial interface

### ISSUE THREAD

**Issue by davidmpickett** [department-of-veterans-affairs/va.gov-cms#11970]
## Description
https://www.figma.com/file/IYpeP2ZAmBTT8jqhdtJklu/Covid-%2F-Facility-Status?node-id=15%3A33336&t=kfpzX6Lv2uZHeA0g-0

## Acceptance Criteria
- [x] Annotated wireframe
- [x] Meeting scheduled with Facilities dev & PM to discuss

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by BlakeOrgan** [comment]
The finalized and annotated design can be found at this Figma link.

https://www.figma.com/file/IYpeP2ZAmBTT8jqhdtJklu/Covid-%2F-Facility-Status?node-id=128%3A32180&t=OKJLA8OYGxTLsEq1-3
