### ISSUE TITLE
Facility locator fetching static data file for every result

### ISSUE THREAD

**Issue by ryguyk** [department-of-veterans-affairs/va.gov-cms#11977]
## Description
The facility locator is fetching the static data file `vamc-facility-supplemental-status.json` for every result displayed, every time a search is submitted. Things should be rearchitected to fetch the file _one time_. This is creating much wasted network traffic.

## Acceptance Criteria
- [ ] Testable_Outcome_X
- [ ] Testable_Outcome_Y
- [ ] Testable_Outcome_Z
- [ ] Requires design review

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by swirtSJW** [comment]
This no longer needs to be fetched at all once the FE change is made to remove display of the description that goes along with the supplemental status.

**Comment by ryguyk** [comment]
Closing in favor of https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12014. Capturing these changes within the context of some larger cleanup.
