### ISSUE TITLE
Update to existing KB article : When will my content be published live on VA.gov?

### ISSUE THREAD

**Issue by EWashb** [department-of-veterans-affairs/va.gov-cms#11982]
## Background context
**What is the request for?**

Content releases will now go out on a continuous basis, M-F from 8am-8pm. We need to update the article to include this new reality. 

**Person and team of requester:** 
- Erika Washburn, Sitewide CMS

**Priority or deadline for request**

  Choose either Deadline or a priority:
  
- [ ] Deadline: December 21, 2022
- [ ] Priority: 
  - [ ] Critical - Without this, there is a large negative impact on the majority of editors causing negative consequences within the CMS; Should be completed as soon as possible
  - [X] High - Without this, there is negative impact on some editors causing negative consequences within the CMS; should be completed within the current sprint
  - [ ] Medium - Without this, there is confusion for editors but not causing negative consequences within the CMS; Should be completed within the next 1-2 sprints
  - [ ] Low - This is not currently causing confusion for many editors but would be a nice to have or is something that may be more impactful in the future; Should be completed within the next 3-4 sprints
  

**Is the article associated with an ongoing product or feature update?**
- [X] Yes #10891
- [ ] No

  
## If requesting a new article:

**Audience:**
Who is this intended for? Who would need this information? (i.e. All editors, only editors for a particular product, Internal use only, etc.)
- All editors

**Related KB articles, if applicable:** 
- https://prod.cms.va.gov/help/cms-basics/content-release-to-vagov

  

## Process
1. Sitewide CMS and Helpdesk teams will review request and confirm no current, applicable KB article/content exists.
2. Refine request and prioritize
3. Update KB article tracker to indicate that the article has been requested and is in progress
4. Assign to appropriate product team
5. Draft article content 
6. Sitewide CMS team will review for formatting and writing style guidelines
7. Helpdesk team will review for functionality and editorial tone
8. Publish
9. Update KB article tracker to indicate that the article has been published

## Acceptance Criteria
- [x] Article is created using [KB content style guidelines](https://va-gov.atlassian.net/wiki/spaces/VAGOV/pages/1771831299/Knowledge+Base+content+style) 
- [x] Article is reviewed by Sitewide CMS
- [x] Article is reviewed by Helpdesk
- [x] Article posted to KB 
- [x] Impacts on other KB articles have been considered and any necessary changes have been made
- [x] Once published, the person requesting the article has been notified

**Comment by laflannery** [comment]
I think this might be a somewhat duplicate article: https://prod.cms.va.gov/help/cms-basics/when-will-my-content-be-published-live-on-vagov It's not identical, but the concept is the same.

Also, this is referenced here as well: https://prod.cms.va.gov/help/vet-centers/what-is-the-process-for-publishing-my-vet-centers-pages

**Comment by laflannery** [comment]
@EWashb Current status:

- Published [New article](https://prod.cms.va.gov/help/cms-basics/content-release-to-vagov) which should be the source of truth moving forward
- Archived [duplicate article](https://prod.cms.va.gov/help/cms-basics/when-will-my-content-be-published-live-on-vagov)
  - **Is a redirect necessary?**
- Updated link on the [CMS Basics landing page](https://prod.cms.va.gov/help/cms-basics) to point to the new article
- Updated content release section on [Vet Center publishing](https://prod.cms.va.gov/node/43971/latest) article as well

I don't know of any other references to the content release so I think this is everything for now.  Besides my question on the redirect, I think this can be closed once you review

**Comment by EWashb** [comment]
About the redirect...I'm conflicted. Since it's a dupe I'm leaning towards no redirect. 

Thank you for doing all of this!!!

**Comment by laflannery** [comment]
@EWashb We can close this right?

**Comment by EWashb** [comment]
This should have been closed a while ago..oops. Closing
