### ISSUE TITLE
Bump weitzman/drupal-test-traits from 1.6.0 to 2.0.1

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-cms#11984]
## Description
PR #11951 is failing:

```
  - Applying patches for weitzman/drupal-test-traits
    patches/weitzman-drupal-test-traits-forbid-connection-reuse.patch (Forbid connection reuse in PHPUnit tests)
   Could not apply patch! Skipping. The error was: Cannot apply patch patches/weitzman-drupal-test-traits-forbid-connection-reuse.patch

In Patches.php line 326:
                                                                               
  Cannot apply patch Forbid connection reuse in PHPUnit tests (patches/weitzm  
  an-drupal-test-traits-forbid-connection-reuse.patch)!                        
```

Likely a case where the patch was merged.  A re-roll at worst.

## Acceptance Criteria
- [ ] Above package can be cleanly updated.

**Comment by timcosgrove** [comment]
I did a pass at this: https://github.com/department-of-veterans-affairs/va.gov-cms/pull/11951

The trait in question was modified to BrowserKitTrait in the 2.x branch, but much of the code was effectively identical, and in particular still uses the Guzzle client in the same page. The patch was simply adapted to the new file.
