### ISSUE TITLE
Content proofing prototype for benefits detail page content 

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#1199]
Iterate on http://pr1228.ci.cms.va.gov/health-care/about-va-health-benefits/dental-care 

AC
* We have a prototype to use in usability testing, in a PR environment. 
* We have an understanding LOE to get this done. 

To do
- [ ] Create a PR environment with latest and share out to team
- [ ] Design crit end of Sprint 2 week 1 with design pod and one more drupal engineer
   - [ ] Decide if the prototype goes into production sooner than later as an MVP, or to a PR environment for user testing. Is this change too disruptive? 
   - [ ] 
- [ ] Iteration Sprint 2 week 2

**Comment by beeyayjay** [comment]
This test site has latest updates: http://pr1173.ci.cms.va.gov/

**Comment by kevwalsh** [comment]
Action items based on design crit and call March 23

- [ ] Margin / spacing
- [ ] Collapsed Q&A by default (paragraphs form display setting)
- [ ] Bitter h1
- [ ] “Edit” design affordance on paragraph links
- [ ] Hover - consider blue hover from paragraphs edit forms or nothing? 
   - [ ] Consider
- [ ] A bit more formation for certain content paragraph types - React, Number callouts, Alerts, 
   - [ ] Administrative box
   - [ ] Revision’s moderation state 
- [ ] Revision author
- [ ] Compare node/NID to node/NID/latest 
- [ ] Move the editorial workflow either to top right or top of page.
