### ISSUE TITLE
Income Limits FE Architectural Design

### ISSUE THREAD

**Issue by ryguyk** [department-of-veterans-affairs/va.gov-cms#11992]
## Description
In https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11643, we raised a number of questions around how to build the Income Limits app. A lot of the questions surround the _data_ (i.e. can we use an existing API). Those questions are critically important, but can and should be decoupled from the actual FE architectural approach. This ticket is aimed at coordinating an overarching design for the front-end architecture.

Needs refining, but some things that need consideration:
- State/Actions/Reducers
  - What are the possible states, and what can happen to change those states?
- Components
  - What sort of UI components do we need?
  - At this stage, we should attempt to nail down the big pieces of the puzzle, but leave some flexibility for the more granular decisions around how big/small our components might end up.
- More?

## Acceptance Criteria
- [ ] Testable_Outcome_X
- [ ] Testable_Outcome_Y
- [ ] Testable_Outcome_Z
- [ ] Requires design review

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by FranECross** [comment]
@dsasser With all the work you've done in automating Income Limits, can this ticket be closed, or was it for something different? Thanks!
