### ISSUE TITLE
Testing: Test that the Lovell location pages have the correct facilities listed

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#11997]
We should be testing the locations menus to make sure there are some facilities present. This can likely best be accomplished by a unit test that utilizes mock data. We can ensure that the menus are properly constructed after undergoing all of the Lovell-specific processing.

https://web-liqqgmzl7tsyfbwyulbkuborufuuttav.demo.cms.va.gov/lovell-federal-tricare-health-care/locations/
![image](https://user-images.githubusercontent.com/6863534/210436831-e3435d62-e4b9-41ea-841e-ad633b81f596.png)

https://web-liqqgmzl7tsyfbwyulbkuborufuuttav.demo.cms.va.gov/lovell-federal-va-health-care/locations/
![image](https://user-images.githubusercontent.com/6863534/210436914-a5048047-b80e-432a-bf26-51e7557a7e1f.png)

## ACs
- [ ] Test created confirming TRICARE system locations page (/lovell-federal-tricare-health-care/locations/) has proper facilities in the sidebar menu
- [ ] Test created confirming VA system locations page (/lovell-federal-va-health-care/locations/) has proper facilities in the sidebar menu

**Comment by ryguyk** [comment]
Completed but failing build. Investigating.
