### ISSUE TITLE
Standardize Resource Naming Convention

### ISSUE THREAD

**Issue by TheBoatyMcBoatFace** [department-of-veterans-affairs/va.gov-cms#12007]
## Overview

As our cloud infrastructure continues to grow and evolve, it is important that we have a consistent and organized naming convention in place for our resources, tags, and analytic metrics. 

Currently, we are seeing some inconsistency in how these are named, which can lead to confusion and difficulty in identifying and managing these assets, as well as interpreting and utilizing the data they generate.

## Proposed Tasks

- Research and evaluate different naming conventions to determine which would best suit our needs, with a focus on ensuring clear and meaningful names for analytic metrics.
- Develop a set of guidelines for naming cloud resources, tags, and analytic metrics, based on the chosen convention.
- Communicate the new naming convention to relevant teams and ensure that it is consistently followed going forward.

By standardizing our naming convention, we can improve the organization and management of our cloud assets and ensure that they are easily identifiable and searchable. This will also help us better interpret and utilize the data generated by our analytic metrics, allowing us to make more informed decisions about our cloud infrastructure and systems as a whole. 

## Acceptance Criteria

- [ ] Defined and Documented AWS Key|Value Naming Convention
- [ ] Access Platform Suggested Naming Conventions & how they impact our team/crew
- [ ] Standardized monitoring suites for the systems and tools our team uses
- [ ] Documented definitions and standards for the various metrics used by our team
- [ ] Defined _Areas of Concern_ of possible cross-team naming conflict

**Comment by olivereri** [comment]
Our team composition has change and priorities reassessed. Re-open if still necessary but currently not a priority.
