### ISSUE TITLE
[SSO] User allowlisted to STAGING cannot access

### ISSUE THREAD

**Issue by ElijahLynn** [department-of-veterans-affairs/va.gov-cms#1200]
User is getting below response when logging into staging.cms.va.gov with PIV card. 

![image](https://user-images.githubusercontent.com/1504756/76348343-468dd100-62c5-11ea-976e-b4ed5b68655e.png)

User is whitelisted in the SSO SQA environment [Internal screenshot](https://files.slack.com/files-pri/T03FECE8V-FV5PJCX0V/screen_shot_2020-03-10_at_12.51.21_pm.png).

## Acceptance Criteria

- [x] Cause is discovered and follow-on issue created to resolve
- [x] Allowlist process is documented in CMS repo and official docs are linked
- [x] CMS team engineers have been added to allowlists for dev & staging

**Comment by acrollet** [comment]
Let's add someone new and timebox investigation if the same error occurs.

**Comment by acrollet** [comment]
- Cause: this error occurs when a user is not correctly added to the "Pre-prdocution" allowlist.
- Documentation may be found here: https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/platform/cms/cms-sso-saml-iam-login-braindump.md#testing-tools
- Issues have been created for each team member without access to get it:
   - https://github.com/department-of-veterans-affairs/va.gov-cms/issues/5834
   - https://github.com/department-of-veterans-affairs/va.gov-cms/issues/5835
   - https://github.com/department-of-veterans-affairs/va.gov-cms/issues/5836

Resolving the last AC in favor of the linked issues.
