### ISSUE TITLE
New Facility: Corpus Christi West Point VA Clinic

### ISSUE THREAD

**Issue by stefaniefgray** [department-of-veterans-affairs/va.gov-cms#12000]
## Intake
- [x] What triggered this runbook? (Flag in CMS, Help desk ticket, Product team, VHA Digital Media)
Trigger: Help desk ticket
- [x] Link to associated help desk ticket (if applicable)
Help desk ticket: https://va-gov.atlassian.net/browse/VAHELP-5227
- [x] Name of submitter (if applicable)
Submitter: anaia.funtanilla@va.gov
- [x] If the submitter is an editor, send them links to any relevate KB articles for the VAMC Facility product.
KB articles: https://prod.cms.va.gov/help/vamc/about-locations-content-for-vamcs/how-do-i-add-a-facility-to-my-health-care-system
- [x] Link to facility in production:
Facility link: https://prod.cms.va.gov/texas-valley-health-care/locations/corpus-christi-west-point-va-clinic

Redirect request: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13379

*Please attach Facility Locator link to this ticket*
https://www.va.gov/find-locations/facility/vha_740QB

### VAMC
Please refer to the Knowledge Base article titled "How do I add a facility to my health care system?" for more information: https://prod.cms.va.gov/help/vamc/about-locations-content-for-vamcs/how-do-i-add-a-facility-to-my-health-care-system

#### CMS help desk steps
- [x] 1. Become aware that the new facility is now on the Facility API (typically, via a Flag, but this may come in as a helpdesk ticket).
- [x] 2. If the editor has followed the steps from the above Knowledge Base article and included which section and VAMC the facility belongs to (i.e. VA Pittsburgh), great! **Proceed to step 3.** If not, please check with the editor or VHA digital media regarding what section and VAMC it belongs to.
- [x] 3. Updates the Section (default is "VAMC facilities", but it should be a VAMC system in a VISN) and VAMC system field accordingly.
- [x] 4. Communicate with editor (cc VHA Digital Media) to give them go-ahead to complete the content, with this [KB article](https://prod.cms.va.gov/help/vamc/about-locations-content-for-vamcs/how-do-i-add-a-facility-to-my-health-care-system). (See sample notification email below)

[@TODO: Update email template]

<details><summary>Email template </summary>

```
Hello! You should now be able to edit the draft page for this facility, located at [LINK TO NEW FACILITY DRAFT PAGE ON PROD]

Important: Please make sure that all relevant steps listed within the “How do I add a facility to my health care system?” Knowledge Base article have been completed: https://prod.cms.va.gov/help/vamc/about-locations-content-for-vamcs/how-do-i-add-a-facility-to-my-health-care-system

Once finished, please save this page (and all related VAMC Facility Health Service pages) in the moderation state “Draft." Please do not save them as “Published.”

Please let us know when your draft content is complete, so that we can wrap up the technical process from our end before publishing the new facility to VA.gov. Thanks!
```

</details>
- [ ] 5. Create a [URL change request](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/new?assignees=&template=runbook-facility-url-change.md&title=URL+Change+for%3A+%3Cinsert+facility+name%3E), changing the entry from the old facility URL to the new facility URL. (**Note: The URL change request ticket blocks the completion of this ticket.**)

https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13379

(Redirects are released Wednesday afternoons, so coordinate the following items below and canonical URL change around that timeframe.)

- [x] 6. When editor has prepared content and let help desk know, reassign this issue to appropriate CMS engineer on Product Support team, for bulk publishing.

#### CMS engineer steps
- [x] 7. CMS engineer executes the steps of the URL change request ticket from step 5.
- [x] 8. CMS engineer bulk publishes nodes and facility.
- [x] 9. CMS engineer edit facility node and remove `New facility` flag and save node.
- [x] 10. Let help desk know this has been done.

#### CMS Help desk (wrap up)
- [x] 11. Notify editor and any other stakeholders.

## CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [x] `⭐️ User support`

**Comment by JayDarnell** [comment]
@stefaniefgray removing myself from this issue because it looks like it isn't ready for a CMS engineer (no facility health services added yet)

**Comment by stefaniefgray** [comment]
Homepage is still an unpublished draft -- waiting for editor in https://va-gov.atlassian.net/browse/VAHELP-5227

**Comment by jilladams** [comment]
Updated ticket body to use the most recent runbook steps for both New VAMC facility and New Vet Center facility. 

For my own learning: how does the Vet Center piece connect to this ticket? Is Corpus Christi clinic a Vet Center location?

**Comment by stefaniefgray** [comment]
Followed up with editor to ask when homepage will be ready -- reminded them that if the clinic is opened but not published yet, this is bad for folks seeking care there

@jilladams More old runbook leftovers, just scooped them into the trash 👍 (by deleting references to Vet Centers)

**Comment by stefaniefgray** [comment]
Editor hasn't responded, am considering escalating to VHA Digital Media because clinic opened December 12th and homepage and health services should be published already

**Comment by stefaniefgray** [comment]
Per https://va-gov.atlassian.net/browse/VAHELP-5227, editor published homepage instead of saving as "Draft" as requested

Editor also published homepage without any VAMC Facility Health Services added, which impacts patient safety

cc: @davidmpickett since this proves that stopgaps against this are still very much needed

Asked editor to add health services and noted Veteran impact

**Comment by stefaniefgray** [comment]
Reminded editor in [VAHELP-5227](https://va-gov.atlassian.net/browse/VAHELP-5227) that VAMC Facility Health Services must be added for this location; have also escalated to VHA Digital Media since this is a patient safety issue

cc: @jilladams @kmariepat-cityfriends for awareness

Also @davidmpickett this is a recent example of what we discussed having the CMS block from being possible (premature publication of new facility homepage + lack of health services added combo)

**Comment by stefaniefgray** [comment]
Editor has added 3 health services for this location as of today

Removing flags and confirming with editor that the 3 services added so far are all of the services that should be listed

If so, can close Github and Jira tickets

**Comment by stefaniefgray** [comment]
Editor added health services, awesome!

Marking as resolved -- cc: @kmariepat-cityfriends

**Comment by stefaniefgray** [comment]
Fixed menu alphabetical order from premature publishing

**Comment by omahane** [comment]
@stefaniefgray @TroyA6 The CSV has been deployed. This ticket can be closed after confirming with the stakeholders.

**Comment by stefaniefgray** [comment]
Confirmed complete -- closing!
