### ISSUE TITLE
Accessibility Audit for Lovell Facility pages

### ISSUE THREAD

**Issue by JQuaggles** [department-of-veterans-affairs/va.gov-cms#12003]
**1. What is this request for?**

An accessibility audit for Lovell facilities pages.

**2. What is the primary function and/or purpose of the product?**

The primary purpose/function of these pages is to provide facility information for Veterans, service members, caregivers, and others who want to locate either VA or DoD/Tricare facilities associated with the Lovell Medical Center. 

Lovell facilities are an outlier compared to other facilities as the main medical center functions as both a VA Medical Center and a Military Treatment Facility. They provide VA care and those that receive Tricare. Each side (VA/DoD) also have separate associated offshoot facilities based on whether they are VA or DoD. 

There are three page types for Lovell: VA/DoD specific pages (solo), pages that exist in both but with different information (Twin), and pages that exist and are the same for both (clone). 

When looking at a page from VA, there is a call out box that indicates the user is looking at a VA page and provides the option to switch to the Tricare pages (and vice versa). 

**3. Are there any known accessibility issues that have not yet been addressed? If so, please add GitHub links to those issues below.**

Currently, no. 
  
**4. Are there any specific testing requirements that should be noted?**

Currently, no. But potentially a close look at the switch call outs [may need to iterate on this later]. And possibly any cognitive burden from that. 

**5. Please provide anything needed to access and review the product.**
[Lovell Front end](https://web-liqqgmzl7tsyfbwyulbkuborufuuttav.demo.cms.va.gov/)
[Lovell CMS](https://cms-liqqgmzl7tsyfbwyulbkuborufuuttav.demo.cms.va.gov/user/4174)

- [Lovell Federal VA health care](https://web-liqqgmzl7tsyfbwyulbkuborufuuttav.demo.cms.va.gov/lovell-federal-va-health-care/) (VAMC system page)
- [Lovell Federal TRICARE health care](https://web-liqqgmzl7tsyfbwyulbkuborufuuttav.demo.cms.va.gov/lovell-federal-tricare-health-care/) (VAMC system page)
- [Evanston VA Clinic](https://web-liqqgmzl7tsyfbwyulbkuborufuuttav.demo.cms.va.gov/lovell-federal-va-health-care/locations/evanston-va-clinic/)
- [USS Red Rover](https://web-liqqgmzl7tsyfbwyulbkuborufuuttav.demo.cms.va.gov/lovell-federal-tricare-health-care/locations/uss-red-rover/)
- [Captain James A. Lovell Federal Health Care Center](https://web-liqqgmzl7tsyfbwyulbkuborufuuttav.demo.cms.va.gov/lovell-federal-va-health-care/locations/captain-james-a-lovell-federal-health-care-center/) (VA location)
- [Captain James A. Lovell Federal Health Care Center](https://web-liqqgmzl7tsyfbwyulbkuborufuuttav.demo.cms.va.gov/lovell-federal-tricare-health-care/locations/captain-james-a-lovell-federal-health-care-center/) (TRICARE location)

  
**6. When does the product need to launch?**

We're pushing for early Q1 [ie January]

> All requests should be submitted at least 1 sprint in advance so that it can be worked into the next sprint.  For requests needed sooner, please notify Laura Flannery in the cms-support channel.

**Comment by JQuaggles** [comment]
@laflannery Added to Sprint 74, thank you!

**Comment by laflannery** [comment]
@JQuaggles I have completed this (so for sprint tracking purposes I wanted to make sure you were aware) however this can't really be closed now since there are open issues attached to it

**Comment by JQuaggles** [comment]
Thanks @laflannery, we can move it to Done as opposed to closed, for sprint purposes.

**Comment by davidmpickett** [comment]
All issues have been addressed or switched to #12060
