### ISSUE TITLE
Update accessibility url in footer (from Sitewide Content and IA)

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-cms#12012]
## Description

Update footer bottom rail link for accessibility page: 
* **OLD URL**: https://www.section508.va.gov/
* **NEW URL**:  https://va.gov/accessibilty-at-va
* **DEADLINE:** 
  * Preferred: Published to prod prior to deploy freeze starting 12/23.  (aka: merge by daily deploy on Thurs 12/22)
  * If we aren't able to achieve that, have confirmed with Dave C that this can ship later if needed.

<img width="913" alt="Screen Shot 2022-12-19 at 1 12 54 PM" src="https://user-images.githubusercontent.com/48728214/208492210-eb1d5c1c-bea6-45f4-8e33-c96815fe0022.png">

### Time constraints / launch deadlines from IA

The page is going live the week of 12/19 so ideally this link would go live shortly after but it's OK to add to the next sprint.

### Your team name

Sitewide Content and IA

### Your product/team Slack channel

#sitewide-content-ia

### Your DEPO product owner

Danielle Thierry 

### Your Product Manager

Rlhecht, Randi Hecht

### Additional Information

IA doc: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/accessibility.md

Content team's ticket for work: department-of-veterans-affairs/va.gov-team#49797

## Acceptance Criteria
- [ ] Footer Accessibility link points correctly to https://va.gov/accessibilty-at-va in production

**Comment by jilladams** [comment]
Note [from Slack](https://dsva.slack.com/archives/CT4GZBM8F/p1671475303656269?thread_ts=1671471928.259009&cid=CT4GZBM8F): this will fix Accessibility in the VA.gov footer. 

This same Accessibility link needs to change in CMS footer, as well. The CMS footer is powered by the "CMS Footer" menu in Drupal.

**Comment by jilladams** [comment]
@RLHecht when will the new page be published, do you have a sense? Currently 404s: https://va.gov/accessibilty-at-va

**Comment by RLHecht** [comment]
@jilladams We are publishing today. I'll let you know once it's live!

**Comment by jilladams** [comment]
Page is live: https://dsva.slack.com/archives/C01K37HRUAH/p1671630468027429

PR to make this change in the VA.gov footer can/will merge today. 
@laflannery I went ahead and updated CMS footer: https://prod.cms.va.gov/admin/structure/menu/item/10320/edit?destination=/admin/structure/menu/manage/footer

**Comment by jilladams** [comment]
Mystery: https://dsva.slack.com/archives/C52CL1PKQ/p1671667805674719
> FE dash says it was deployed
> If you hover on Accessibility in the live footer, it still points to the 508 site.

(Sidebar: I did also update this int he CMS, Footer Bottom Rail menu that will become the new data backend when the footer is drupalized.)
