### ISSUE TITLE
FE: Lovell Tricare menu links going to VA

### ISSUE THREAD

**Issue by ryguyk** [department-of-veterans-affairs/va.gov-cms#12011]
## Description
Some of the menu items in the sidebar menu on Tricare pages are linking to VA pages.
- About us
- Work with us
- Contact us
- Programs

These should be pointing to their respective Tricare pages.

## Acceptance Criteria
Sidebar links on Tricare pages should point to their respective Tricare pages
- [ ] About us
- [ ] Work with us
- [ ] Contact us
- [ ] Programs

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by swirtSJW** [comment]
I am closing this as the pr is approved and just awaiting lifting of code freeze to be merged.  
https://github.com/department-of-veterans-affairs/content-build/pull/1409
