### ISSUE TITLE
SPIKE: "Create account" block content: plan / artifact

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#12019]
### User Story
As a Homepage Manager, I want to be able to manage the Create Account block in Drupal so that I can tweak it without a code change.

### Details
This ticket is a SPIKE on how to Drupalize the Create Account block content on the updated homepage. 
![image](https://user-images.githubusercontent.com/4054752/208554023-4038ecee-c916-4b65-ab5e-c82feeb5f504.png)

Questions that we need to resolve:
- What Drupal pattern should we follow? e.g., another custom block type displayed by an EntityQueue?
- What permissions framework should we use? (e.g., same as homepage promo blocks?) Any issues or tradeoffs w.r.t. permissions?
- What would the Drupal UX/UI experience look like out of the box?
- Any issues concerning the front-end implementation?

# SPIKE Results

## What Drupal pattern should we follow? e.g., another custom block type displayed by an EntityQueue?
<details>
  <summary>Click to expand</summary>

A new Block + entityqueue is likely the ideal solution, given we are already using blocks + entityqueue for other areas of the home page, so this would not break into a new pattern.

Do any of the existing blocks make sense to leverage?
|Block Type||Fields|
Alert - Alert body, Alert title, Alert type, Reusability, Section
Promo - Image, Link, Section 
CMS Announcement - Alert body, alert heading, Submission guidelines, Type
V2 Homepage benefit promo - Promo CTA, Promo Headline, Promo Text, Section
V2 Homepage news spotlight - Image, Link, Link Text, Promo Headline, Promo Text, Section

None of these really work. The required fields, and the field names/labels, do not lend themselves well to being used for other purposes, such as one as rigidly structured as this login block appears to be.

That said, there are reusability options for fields, such that we do not need to create all new fields for this new block, and instead leverage existing fields that perform similar/identical functions from other blocks. This helps reduce overall field/database bloat.

</details>

## What permissions framework should we use? (e.g., same as homepage promo blocks?) Any issues or tradeoffs w.r.t. permissions?
<details>
  <summary>Click to expand</summary>

Assuming homepage manager (Drupal role) is the owner/editor of this content, then we should follow the pattern of the new homepage blocks (v2 home page benefit promo, v2 home page news spotlight). Combined with the use of the Section access control, this gives us the same permissions framework as other blocks on the home page. This framework also applied to other home page elements such as menus, so keeping with that pattern is ideal.

To recap the framework:
Drupal Homepage Manager role is allowed create + edit permissions for new block types. Homepage Manager will assign the block to the `OPIA Home page` Section.
Section (workbench access) controls the permissions for editing blocks.
Homepage Manager is allowed to edit/add items to the new entityqueue.
</details>

## What would the Drupal UX/UI experience look like out of the box?
<details>
  <summary>Click to expand</summary>

** Note the below screenshots represent a quickly-thrown-together content model for the sake of demonstrating out-of-the-box experience. Content and CMS design will need to weigh in on their areas of concern before it is committed to code.

### Block form
![screencapture-va-gov-cms-ddev-site-block-add-login-block-2022-12-21-10_23_11 (2)](https://user-images.githubusercontent.com/221539/208980241-3bed46b7-5903-42d4-bbab-0e1d10a547b3.png)

### Entityqueue form
<img width="1910" alt="Screen Shot 2022-12-21 at 10 28 57 AM" src="https://user-images.githubusercontent.com/221539/208980333-677035b3-6aef-4e78-bc83-b4d14070ed22.png">

</details>

## Any issues concerning the front-end implementation?
<details>
  <summary>Click to expand</summary>

No FE concerns identified. The new entityqueue query can be added to the `homePage.graphql.js` script and injected into home page liquid template variables to replace static text strings in `hero.drupal.liquid`.
</details>

## Acceptance Criteria 
- [x] Develop a plan for implementation, permissions, role, editing
- [x] File [CMS Collab Cycle intake request](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/new?assignees=ewashb%2Cdawnpruitt&labels=%E2%AD%90%EF%B8%8F+Sitewide+CMS&template=sitewide-cms-collab.yml&title=%5BCMS+COLLAB+CYCLE+INTAKE%5D+%28Team+Name%2C+Product+Name%2C+Feature+Name%29) to review proposed plan
- [x] This ticket does not include any actual churn post-CMS team's involvement
- [ ] Implementation ticket = #11692, update with final plans

**Comment by dsasser** [comment]
This AC:

> Implementation ticket = https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11692, update with final plans

Is not possible to complete until we are through the CMS collab cycle and the implementation has been singed off by Dave Conlon. Given that, we will be unable to close this issue this sprint. unless we strike that from the required ACs.

I feel as though we have completed the essence of this ticket, which is to establish and propose a new plan to Drupalize the create account block. @wesrowe thoughts?

**Comment by wesrowe** [comment]
Works for me – due to delay of CMS collab review, I altered the AC and added the reference to the implementation ticket.
