### ISSUE TITLE
FE Tech Debt: Facility Locator Covid status cleanup

### ISSUE THREAD

**Issue by ryguyk** [department-of-veterans-affairs/va.gov-cms#12014]
## Description
#11794 changes the Covid status to no longer be expandable. [The PR to accomplish that](https://github.com/department-of-veterans-affairs/vets-website/pull/22973) makes a very simple change to move from an expandable alert to a standard alert. But this change actually has bigger implications. The information that we are no longer displaying was the result of a fair amount of processing that includes fetching a static data file and displaying information from that file according to the Covid status level at a particular facility.  That processing is no longer needed.

What needs to be done:
1. The static data file is no longer needed. The only thing still being used from it is the name field, and we can hard-code that (see step 2 below). All of the code that fetches and processes this data file should be removed.
2. Hard-code the alert message based on the status level.

## Acceptance Criteria
- [x] All code that fetches and processes static data file `vamc-facility-supplemental-status.json` is removed.
- [x] Status level message is hard-coded.
- [x] Alert shows appropriate message based on status level.
  - [ ] COVID-19 health protections: Levels **low**
  - [ ] COVID-19 health protections: Levels **medium**
  - [ ] COVID-19 health protections: Levels **high**

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by JQuaggles** [comment]
Pulled into the Sprint
