### ISSUE TITLE
Homepage Sketch: Update modal treatment to match ACs from implementation ticket

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#12010]
## Description
The Sketch file for homepage design of the modal has fallen behind actual ACs / 508 review / Collab Cycle approval. 

**Sketch Design:** 
https://www.sketch.com/s/3aa40506-4be2-46cc-876b-93f1a9f3a857/p/EAD305BC-3082-4F81-ADEC-C2486F7B6BEF/canvas

**Build**
Actual design from collab cycle that has been implemented: 
![Screen Shot 2022-12-19 at 9 53 48 AM](https://user-images.githubusercontent.com/85581471/208489260-ec6e3cbc-9304-4876-8f90-deca1c14ad74.png)

## ACs
- [x] Sketch file reflects design system modal (including style of close button)
- [x] Sketch reflects CTA link and secondary button style for links/actions

**Comment by thejordanwood** [comment]
Sketch file has been updated.

**Comment by jilladams** [comment]
BLESS. That was bothering me so much. ✅
