### ISSUE TITLE
CMS Update Lighthouse CSV for Lovell facility URLs

### ISSUE THREAD

**Issue by omahane** [department-of-veterans-affairs/va.gov-cms#12015]
## Description

Timing - coincide with end of dual-state (production) - necessary for production

This CSV needs to have Lovell facility links for the Facility Locator
https://github.com/department-of-veterans-affairs/lighthouse-facilities/blob/master/facilities/src/main/resources/websites.csv

## Dual State requirement
Having these links updated and merged is going to be necessary for Dual State.

Add the facilities to be added in the AC.
IDs:
vha_556
vha_556GC
vha_556GD
vha_556GA

Human readable names: 
- Captain James A. Lovell Federal Health Care Center
- Evanston VA Clinic
- Kenosha VA Clinic
- McHenry VA Clinic

## Acceptance Criteria
- [ ] Update the lighthouse with the VHA facility IDs attached to Lovell AND to update the URLs

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by davidmpickett** [comment]
@JayDarnell Can you confirm whether this ticket work is only for moving from Dual State -> Full State? The description is contradictory

**Comment by JayDarnell** [comment]
I do not believe having the lighthouse CSV updated with the new va.gov address for Lovell is a requirement for dual state. @swirtSJW please correct me if I'm wrong but I think the lighthouse CSV only needs to be updated when we move to full state (Lovell Teamsite is no longer the source of truth)

**Comment by omahane** [comment]
@kmariepat-cityfriends The CSV has been deployed and has been confirmed in Facility Locator. This can be closed.
