### ISSUE TITLE
Remove white space within visual focus indicator on Operating Status

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#12023]
## Description
In #11699 the visible focus indicator was added to the Operating Status link. However, there is some additional white space on the alert component that should ideally be removed to align with styles for the focus outline throughout the site.

## To Reproduce
1. Go to any VAMC locations page with an active operating status, example [Gainesville](https://www.va.gov/north-florida-health-care/locations/gainesville-twenty-third-avenue-va-clinic/)
2. Use the keyboard and the "Tab" key to navigate down the page
3. Notice that when you get to the operating status, there is space between the top of the alert and the gold focus outline
4. Conversely, notice that when you are focused on the covid status, this space does not exist

![image](https://user-images.githubusercontent.com/106678594/208526512-629603e7-6688-43b3-a065-ce95490b86a8.png)

## Additional context
To remove this additional space you can update the attribute on the <span> within the operating status link:
  - `<span class="operating-status-flag operating-status-flag-warning operating-status usa-alert usa-alert-warning background-color-only vads-u-margin-top--1 vads-u-padding-y--2 vads-u-padding-x--1p5">`
  - Change `vads-u-margin-top--1` to `vads-u-margin-top--0`

## AC / Expected behavior
- [ ] The focus state outline is flush with the operating status alert, matching the style of other elements
- [ ] Accessibility Lead review

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by dawnpruitt** [comment]
@JQuaggles @davidmpickett

**Comment by JQuaggles** [comment]
Pulled into the sprint

**Comment by JQuaggles** [comment]
Links to this PR: https://github.com/department-of-veterans-affairs/content-build/pull/1417

**Comment by CherylEvans** [comment]
This ticket was recreated in the va.gov-team repo Ticket # [64851](https://app.zenhub.com/workspaces/collaboration-cycle-reviews-61d89e9e5f4c120011a0ad37/issues/gh/department-of-veterans-affairs/va.gov-team/64851)
