### ISSUE TITLE
Prepare Research Readout for VBA Public Contact Staff 

### ISSUE THREAD

**Issue by davidmpickett** [department-of-veterans-affairs/va.gov-cms#12025]
## Description
Readout is scheduled for 2/15/2023

**Research Readout(s)**
- Work with PM & PO to determine audience(s) and meeting length(s)
- Default to a 30-min meeting with 20 min for presenting and 10 min for discussion
- [Research Presentation Template](https://docs.google.com/presentation/d/13G80avWGdY7tHU40PbP_l05W1yRpDr-opOk0u_AAhzQ/edit#slide=id.g892adcb623_0_141)
  - Consider slimming down this template based on your audience
  - Consider doing a pratice runthrough with Design Team or PM to ensure it flows
- After readout(s) with your immediate team(s) and stakeholder(s), consider presenting your research at Platform's weekly Design + Content + Research meeting
  - Message Naomi Marcussen on Slack to sign up

**Destroying and Archiving Research Materials**
- Once your synthesis is complete, you should destroy any [session recordings](https://depo-platform-documentation.scrollhelp.site/research-design/recording-user-research-sessions) saved to your local machine
- Review your notes and synthesis materials to make sure they don't contain any PII. Then make sure they are added to your github Research Folder for archival purposes

## Acceptance Criteria
- [x] Prepare readout materials to Conduct readout(s)

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by davidmpickett** [comment]
As discussed in Sprint Planning today, this issue is blocked by @davidconlon doing a full review of the [research findings](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/regional-offices/research/2022-9-public-contact/research-findings.md).

@smythe5 to schedule a 1-hour working meeting for next week (Jan 24-27) for us to review document and create an outline for the scope of readouts needed

**Comment by smythe5** [comment]
Readout scheduled for 1/27 at 1000 AM Eastern

**Comment by davidmpickett** [comment]
Follow up work from Friday's meeting ([slack thread](https://dsva.slack.com/archives/C0FQSS30V/p1675090345992719))

- I will update research report findings based on feedback from meeting
- Dave C provided async feedback on recommendations section - I will update those as well
- I will work on slides for a readout next sprint

**Comment by davidmpickett** [comment]
I may slightly revise this presentation after the presentation tomorrow before it's officially added to the GitHub repo, but sharing it here to prove this is done. [VBA_Public_Contact_Research_Readout.pptx](https://github.com/department-of-veterans-affairs/va.gov-cms/files/10739005/VBA_Public_Contact_Research_Readout.pptx)
