### ISSUE TITLE
Discharge Wizard: wrap question in semantic H2  / visual H4 tags for readability

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#12042]
## Description

With adoption of the RadioButton design system component in #11358 , question text in the wizard becomes less styled / less legible. 

The [Discharge wizard](https://www.va.gov/discharge-upgrade-instructions/questions) uses the Wizard format, which is headed for deprecation / is not best practices. Eventually, this page should move to use the Subtask type. The design system, therefore, is not interested in making changes to the component that specifically affect the Wizard layout. 

A11y folks suggested an alternate means of handling an accessible + visual update that makes questions more readable: 
> wrap all the elements which belong to “In which branch of service do you serve?” into a `<fieldset>` and make the question an `h2` and put it inside the legend like so: 
```
<legend>
  <h#>...</h#>
</legend>
```

* see slack thread: https://dsva.slack.com/archives/C0NGDDXME/p1671556707881819?thread_ts=1671471252.709569&cid=C0N

We need to confirm this is technically possible, given the way the RadioButton component works today.

## Acceptance Criteria
- [ ] All Discharge wizard questions use semantic header level (i.e., H2) and are thus are visually distinct from radio options beneath them
- [x] Requires design review / signoff from @thejordanwood 
- [ ] A11y review with @laflannery 

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by jtmst** [comment]
The work here seems relatively light but giving a 5 to allow for both 508 and design review / feedback

**Comment by wesrowe** [comment]
@laflannery, please review status quo for a11y.

**Comment by jilladams** [comment]
Front end refinement: 
* Re the Design System, asked for clarification here re: using fieldset somehow / if we can or if component needs updated: https://dsva.slack.com/archives/C0NGDDXME/p1677094399510059?thread_ts=1671471252.709569&cid=C0NGDDXME

**Comment by jilladams** [comment]
Team refinement: 
* We believe we can use the `label-header-level` to achieve this.
* 508: as wizard, multiple H2s on the page is a lot. Will be the right solution when we move to subtask pattern, where it makes more sense. 
* Design: best not to style as an H2. 

Final answers: semantic H2, styled as visual V4.

**Comment by thejordanwood** [comment]
The visual design here looks good to me!

**Comment by wesrowe** [comment]
Is this work in Prod yet? Jill and I happen to have discussed it with Dave today and I noticed some questions are bold, some aren't.

**Comment by jilladams** [comment]
teaching to fish: 
1. linked vets-website pr: https://github.com/department-of-veterans-affairs/vets-website/pull/25052
2. https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/frontend-support-dashboard/

![Screenshot 2023-08-03 at 5 19 32 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/85581471/db7a6e9f-35aa-4076-aec7-ecb6bf03fe07)

**Comment by chriskim2311** [comment]
@wesrowe @jilladams There was an issue with the design team component for radio buttons. It was weird that it was working before then once it hit prod the styling was not being applied correctly. Reached out to DST and they wanted me to override styles instead of fixing their heading issue.  PR for overrides https://github.com/department-of-veterans-affairs/vets-website/pull/25098

**Comment by chriskim2311** [comment]
Verified headers have correct styles in prod.
