### ISSUE TITLE
Update soft-launch modal GA events to fit existing GTM conventions

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#12048]
## Description

The GA implementation that PW did for the soft-launch modal used event actions/labels that GTM is not wired to accept. We need to evaluate how to adjust the three events on this modal to conform to patterns GTM is set up for.

To fix it, we will attempt to change the event action/label to use existing GTM wiring.

Platform Analytics team pointed me to these two resources for existing patterns:
- [Design System docs](https://design.va.gov/storybook/?path=/docs/components-va-modal--default) (scroll to Modal)
- [Analytics docs on Navigation events](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/navigation-events)

**Recommended approach: docs aren't great, so find a similar pattern in Prod code to follow.**

### 1. "Try the new home page" CTA link click
We get no usable GA event at all on this one.

Our custom event config in FE code (as seen in AdSwerve console):
`event: "new-homepage-modal-click",`
`modal-primaryButton-text: "try the new homepage"`

Example pattern:
[How to file a claim](www.va.gov/disability/how-to-file-claim/) page, see CTA link partway down page.
- Event sent to GA: `ec: Interactions ea: Primary Action Link CTA - File a disability compensation claim - green el: cta-action-link-click`
- **This is using the DataLayer pattern for **
- Object that sends it: `{
	event: "cta-action-link-click",
	action-link-type: "primary",
	action-link-click-label: "File a disability compensation claim",
	action-link-icon-color: "green"
}`
 
### 2. "Not today..." secondary button click
We do get a GA event "for free" on this one, but it's not specific.

- Our custom event config in FE code (as seen in AdSwerve console):
`event: "new-homepage-modal-click",`
`modal-secondary-link: "go to current homepage"`
  - _This event did not make it through to GA_

One event did make it through to GA; however, you can see that it doesn't capture some specific fields (`(not set)`) that would distinguish what the button actually is:
- Design-system automatic event tracking: `ec: Interactions ea: Secondary Button CTA - (not set) - (not set) el: cta-button-click`
  - Is this the object that generated that?: 
  - `{
	event: "cta-button-click",
	event-source: "component-library",
	component-library-version: undefined,
	button-type: "secondary",
	button-label: "Not today, go to the current homepage"
}`
  - I suspect the "not set" fields are because this object is not configured correctly – there's probably a clue here for us.

Example pattern: Secondary button click on "See all locations" on [Central Alabama MC](https://staging.va.gov/central-alabama-health-care/locations/):
<img width="281" alt="image" src="https://user-images.githubusercontent.com/4054752/208798830-f68a817e-8b61-46d7-b0cf-207ee9ceef0c.png">

- GA event (yellow): `ec: Interactions ea: Navigation - Secondary Button - See all locations el: nav-secondary-button-click`
- Object in console: `{
	event: "cta-button-click",
	button-type: "secondary",
	button-click-label: "\n              See all locations  \n            ",
	button-background-color: "rgb(220, 228, 239)"
}`
  - NOTE: Where did "Submit feedback" come from in GA event? 'label' in object is undefined...

### 3. `X` dismiss modal button click

- Our custom event config in FE code (as seen in AdSwerve console): `event: "new-homepage-modal-close`

Example pattern: dismiss X on the PDF Download modal
- GA event (yellow) in AdSwerve: `ec: Interactions ea: Modal - Click - closed - Download this PDF and open it in Acrobat Reader - (not set) - (not set) -  el: int-modal-click`
- Object that generates: `{
	event: "int-modal-click",
	modal-status: "closed",
	modal-title: "Download this PDF and open it in Acrobat Reader"
}`
  - Note: this `int-modal-click` was pointed out by Analytics team.

## Acceptance Criteria
- [ ] "Take me to new home page" event makes it to GA in staging
  - Proposed event in GA (based on pattern): `ec: Interactions ea: Primary Action Link CTA - soft-launch modal Take me to new home page - green el: cta-action-link-click`
- [ ] "Not today" event makes it to GA in staging
  - Proposed event in GA (based on pattern): `ec: Interactions ea: Navigation - Secondary Button - Modal Don't take me to new homepage el: nav-secondary-button-click`
- [ ] Dismiss 'X' event makes it to GA in staging
  - Proposed event in GA (based on pattern): `ec: Interactions ea: Modal - Click - closed - Dismiss new homepage modal - (not set) - (not set) -  el: int-modal-click`
- [ ] Verify in Staging before closing ticket

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by jilladams** [comment]
For the histories: the PR here removes the custom GA events originally scoped, and replaces them with events that we know can/will be successfully tracked in GTM. 

This approach is different than what we hope to do for homepage events in #12065 and #11965 .

**Comment by jilladams** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/23026

**Comment by wesrowe** [comment]
@jtmst, I confirmed that GA is coming through as expected in the actual GA interface for all events.
