### ISSUE TITLE
Homepage modal: manage focus on modal close / skip link

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#12045]
## Description
In #11535 the Skip to content link was made visible when closing the modal. DaveC has flagged that this should not happen, and we need to identify a solution that does not make the skip link visible to sighted users. (FYI @laflannery @jtmst ). 

For other modals, e.g. sign in modal and form download modal, if a user closes the modal, focus defaults back to the element they clicked in order to open the modal. Because the homepage modal appears on page load, when users close the modal, there is not a logical DOM element to default focus to.

### Current behavior 
* VA.gov page load
* Modal appears
* Click  or ESC to close modal
* Skip to content link appears above page header, in focus
* Any other click / change of focus causes Skip link to disappear

### Ideal Desired behavior
* VA.gov page load
* Modal appears
* Click  or ESC to close modal
* Screen reader focus moves to Skip to content link, not visible in front-end
* Skip to content link is not visible to sighted users

**Concerns for sighted users**
- Visible skip link could therefore introduce a higher burden on sighted users. Most sighted users have never seen a skip link before and do not know what it is. The concept of "skip to main content' is not intuitive.
- Dismissing a modal should not change the content behind the modal. Modals are specifically designed to prevent interaction with or change to content behind the overlay.

**Questions and considerations**
- Is there a difference here between WCAG 2.0 and 2.1? Per DaveC: if this informs the choice, how can we leverage that?
- Is it possible to provide screen readers a different experience than the visible experience (i.e., skip link announced on modal dismissal, but skip link not visible on page)?
- Does our Accessibility framework have a way of balancing screen reader accessibility against cognitive load? (Typically screen reader accessibility can be had without such a tradeoff.)

## Additional context
History of how we got here: [https://github.com/department-of-veterans-affairs/vets-website/pull/22942
In comments ](https://github.com/department-of-veterans-affairs/vets-website/pull/22942#issuecomment-1353702567)
> Discussed with Laura
> * Without the Skip to Content link: the modal sits in the DOM right above the footer. So when modal closes, screenreader / keyboard users will get bumped to the Footer as the next DOM element.
> * To counteract this: we need to send users to the skip link.
> * Per Laura, this is as intended and ok to ship as is, and meets the AC.

## Acceptance Criteria
- [ ] Skip to content link is not made visible in front-end upon modal dismissal
  - [ ] Skip to content link is present in the DOM
  - [ ] On modal close, screen reader focus lands on skip link
- [ ] Document in "docs" for Announcement framework

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [X] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by wesrowe** [comment]
@jilladams @laflannery, this issue's urgency rises to the level of sprint injection.

**Comment by jilladams** [comment]
https://dsva.slack.com/archives/C52CL1PKQ/p1671641137056349?thread_ts=1671572481.229729&cid=C52CL1PKQ
> Laura has a solution: adding a div at the very top of the page, above the skip link, with tab-index = -1 .

**Comment by jilladams** [comment]
@laflannery FYI that the modal has been moved above the skip link in the markup, in Josh's latest PR. That change is now available on Staging. Moving this to PO review to reflect that code is merged, and we can close once Laura has signed off. (Out sick today, likely tomorrow or later.)

**Comment by laflannery** [comment]
Sorry I missed this! This looks good and is approved on staging
