### ISSUE TITLE
Run SQL commands on production to support Sonora system change

### ISSUE THREAD

**Issue by JayDarnell** [department-of-veterans-affairs/va.gov-cms#12056]
## Description

Relates to #11231 

The Sonora VA Facility has moved from the Palo Alto system to the Northern California system. The original facility record was removed from VAST and a new record was added. The Facility Locator API IDs for each item are different. To preserve our revision history in CMS I've swapped the Facility Locator API IDs for the two nodes and need the following SQL commands run on production before the next migration so the next data pull from VAST will map correctly.

`drush sql:query "DELETE FROM migrate_map_va_node_health_care_local_facility WHERE sourceid1 = 'vha_612GL'"`

`drush sql:query "UPDATE migrate_map_va_node_health_care_local_facility SET sourceid1 = 'vha_612GL' WHERE sourceid1 = 'vha_640GB'"`

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [x] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [x] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by ndouglas** [comment]
```
$ drush sql:query "DELETE FROM migrate_map_va_node_health_care_local_facility WHERE sourceid1 = 'vha_612GL'"

$ drush sql:query "UPDATE migrate_map_va_node_health_care_local_facility SET sourceid1 = 'vha_612GL' WHERE sourceid1 = 'vha_640GB'"

```

No alarms, no surprises.
