### ISSUE TITLE
Migrate benefits for content modeling work XLS to Airtable

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#12058]
Per 12/21 sync with Dave, Danielle, Wes, Daniel, Jill: Airtable provides functionality that will help us work through content strategy. Dave / Danielle are on board with migrating to that tool, and Pickett has volunteered to lead the charge.

Current sheet: 
https://dvagov-my.sharepoint.com/:x:/r/personal/danielle_thierry_va_gov/Documents/Benefits%20for%20content%20modeling%20work.xlsx?d=wb36115531f894fdc87f64ba53d27576e&csf=1&web=1&e=UvIIuB

## ACs
- [x] Excel benefit data moved to Airtable in a way that leverages AT's strengths
  - Split certain fields into their own tables and linking between them (e.g. Beneficiaries). 
  - Crosswalk this with the AirTable where Dave has modeled benefits from VBA research. 
    - [Mural](https://app.mural.co/t/vagov6717/m/vagov6717/1660845137501/6eadf59a3f4d8dcd29da572a68115a22d6114fe4?sender=u20829d1b64855e281dde2585) Dave created for this ticket
- [ ] Follow-up meeting/workshop scheduled with Dave C, Danielle, Dave P, Wes

**Comment by davidmpickett** [comment]
I have requested access to the spreadsheet from Danielle ([slack message](https://dvagov-my.sharepoint.com/:x:/r/personal/danielle_thierry_va_gov/Documents/Benefits%20for%20content%20modeling%20work.xlsx?d=wb36115531f894fdc87f64ba53d27576e&csf=1&web=1&e=UvIIuB))

**Comment by davidmpickett** [comment]
I'm booked for Sprint 74, but might be able to make some progress on this in Sprint 75.

In addition to importing the main table, I'll be splitting certain fields into their own tables and linking between them (e.g. Beneficiaries). I also want to crosswalk this with the AirTable where I've been modelling benefits from VBA research.

**Comment by davidmpickett** [comment]
The Airtable in progress

Contributor link: https://airtable.com/invite/l?inviteId=invOnjHhGJyDe5VWI&inviteToken=66aa9d3dd492b6f1e7f1e36d8968b2a914b9c9e7b97e1cc7e867abd338eee47a&utm_medium=email&utm_source=product_team&utm_content=transactional-alerts

Public view link: https://airtable.com/shrGW4oHIwWHa17IC

**Comment by davidmpickett** [comment]
@wesrowe @jilladams - I think the Airtable is in a pretty good place for taking back to the working group to review. Just by implementing some basic interlinked tables, this has made it easier to identify areas that need more definition. 

I didn't do the crosswalk with my VBA Facility Airtable because that would have only added complexity that we're not ready for yet. 

Also linking to the Mural, as they go hand-in-hand in someways: https://app.mural.co/t/vagov6717/m/vagov6717/1660845137501/6eadf59a3f4d8dcd29da572a68115a22d6114fe4?sender=u20829d1b64855e281dde2585

Only remaining bit is scheduling the follow up meeting

**Comment by wesrowe** [comment]
I'm taking the "schedule meeting" AC. This can close.

**Comment by davidmpickett** [comment]
For those unable to directly manipulate the Airtable, I exported the tables to csv and quickly combined them into excel. The fields won't be interlinked, but it's gives access to the data:
[Benefit Content Model export 20230201.xlsx](https://github.com/department-of-veterans-affairs/va.gov-cms/files/10564545/Benefit.Content.Model.export.20230201.xlsx)
