### ISSUE TITLE
Incorrect heading order with accordions on locations pages

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#12068]
## Describe the defect
On VAMC locations pages, the health services accordions all have the same heading structure underneath "Contact information" and unfortunately a couple headings within this current structure are incorrect.

## To Reproduce
1. Go to either a VAMC location page, like [Evanston VA Clinic](https://web-liqqgmzl7tsyfbwyulbkuborufuuttav.demo.cms.va.gov/lovell-federal-va-health-care/locations/evanston-va-clinic/) or [Jamaica Plain VA Medical Center](https://www.va.gov/boston-health-care/locations/jamaica-plain-va-medical-center/)
2. Scroll down to Health services section
3. Expand one of the accordions
4. Use the dev tools inspector, or a headings browser plugin to identify the heading levels of the text within the Health services accordion section

## Additional context
The table displays the current structure of the health services accordions and indicates where the changes would need to occur.

| Text  | Current heading  | Correct Heading  |
|---|---|---|
|  Health services offered here | H2  | H2 - NO CHANGE  |
| [Accordion title] Example: Geriatrics  | H3  | H3 - NO CHANGE  |
|Contact information   |  H4 | H4 - NO CHANGE  |
| Hours  | H3  | H5  |
| Appointments | H4  |  H5 |
| Phone  | H5  | H5 - NO CHANGE  |

## AC / Expected behavior

- [ ] Update "Hours" heading to be an H5
- [ ] Update "Appointments" heading to be an H5
- [ ] Accessibility Review

## Screenshots
![image](https://user-images.githubusercontent.com/106678594/209005148-d81cb7a6-80c2-4c25-aed4-2d0557604450.png)

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by Dottisea** [comment]
Consider for Feb - fe eng

**Comment by CherylEvans** [comment]
This ticket was recreated in the va.gov-team repo Ticket # [64849](https://app.zenhub.com/workspaces/collaboration-cycle-reviews-61d89e9e5f4c120011a0ad37/issues/gh/department-of-veterans-affairs/va.gov-team/64849)
