### ISSUE TITLE
No locations appearing on Lovell TRICARE VAMC System page

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#12066]
## Describe the defect
On the Lovell Federal TRICARE Health Care page, there are no locations appearing under the Locations heading. A heading should only appear if there is content to go with it.

## To Reproduce
1. Go to [Lovell TRICARE](https://web-liqqgmzl7tsyfbwyulbkuborufuuttav.demo.cms.va.gov/lovell-federal-tricare-health-care/)
2. Scroll down to the Locations section
3. Notice that the "See all locations" button appears immediately after the heading

## AC / Expected behavior

- [ ] Add content to the "Locations" header so there is a purpose for this heading

## Screenshots
**Lovell TRICARE**
![image](https://user-images.githubusercontent.com/106678594/208996393-7f94637b-f065-499a-b008-dc220fb297f1.png)

**Lovell VA**
![image](https://user-images.githubusercontent.com/106678594/208996463-1d8d5da0-9f39-4860-9c35-6579d4dcad43.png)

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by swirtSJW** [comment]
This was due to the TRICARE instance of James A' Lovell not being marked as a main location. 
![image](https://user-images.githubusercontent.com/5752113/209219696-31ff660c-2555-47c7-a133-e4ef910ff755.png)


I fixed this in prod data.  It should fix itself in the demo env next time it is rebuilt.

**Comment by JQuaggles** [comment]
Can we get a confirmation on the FE?
