### ISSUE TITLE
[CMS COLLAB CYCLE INTAKE] (Public Websites, Home page, Create account block)

### ISSUE THREAD

**Issue by dsasser** [department-of-veterans-affairs/va.gov-cms#12062]
### What type of request are you making?

- [ ] Update to an existing CMS feature (including product iterations, updating DS components or page layouts and nav changes)
- [X] New CMS feature (New content types, DS components, workflows or products)
- [ ] Content audit (either one time audits or resuable tools)
- [ ] Change Management review (for any visible changes to the CMS, workflow or content model)
- [ ] Other

### Please choose the team that is requesting the Collab Cycle kickoff.

Public Websites

### When did/will you start working on this product/feature?

December 2022

### When will your feature need to launch?

No timeline has been established as of yet.

### Are you doing research with VA.gov users or editors?

No

### Will your work involve changes to...?

CMS content model

### Please add a link to your product outline issue.

TBD

### Additional Information

We are tasked with 'Drupalizing' the Create Account block content on the updated homepage. 
![image](https://user-images.githubusercontent.com/4054752/208554023-4038ecee-c916-4b65-ab5e-c82feeb5f504.png)

See https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12019#:~:text=front%2Dend%20implementation%3F-,SPIKE%20Results,-What%20Drupal%20pattern for context.

### Notify the Sitewide CMS team of this ticket in the cms-support Slack channel.

- [X] I acknowledge that I must notify `#cms-support` after submitting this issue.

**Comment by EWashb** [comment]
At first glance this does look like it will need at least some CMS design review. Do you have a timeline for when this will be live or is it already @dsasser?

**Comment by dsasser** [comment]
> At first glance this does look like it will need at least some CMS design review. Do you have a timeline for when this will be live or is it already @dsasser?

The current `create account` block is live on the new homepage. It is built using static text in the related content-build template. As far as the timeline for drupal-izing: I'm not aware of the priority/timeline. @jilladams @wesrowe can you help with that?

**Comment by jilladams** [comment]
No hard timing, this is just Drupal work that's available to do and prioritized.

**Comment by EWashb** [comment]
Sounds good. Would yall like to try to get something on the book for this week or Sprint 75?

**Comment by jilladams** [comment]
If you have capacity we could try to kick off this week. I'm here today / tomorrow (Tues/Wed), Wes is here all week, Daniel is here all week.

**Comment by EWashb** [comment]
@jilladams it just occurred to me that I will have no UX/design representation for this, and it seems like we will need that to have a successful kickoff. Both Blake and Dave P. are out. I would still be happy to have an impromptu chat if that would be helpful

**Comment by wesrowe** [comment]
@EWashb, I'll slack you about scheduling a chat for early Sprint 75

**Comment by jilladams** [comment]
@BlakeOrgan @EWashb / @dawnpruitt , FYI that @thejordanwood pulled together a design: https://www.figma.com/file/OJ6ncc4hAvABO6iX5Z1Aw6/Create-Account-content-block?node-id=0%3A1

I'll schedule collab cycle kickoff with the 5 of us plus Wes, Daniel, + Dave optional. Holler if anyone else should be added.

**Comment by jilladams** [comment]
## Notes: 
**Drupal:**
* Yes, worth it to Drupalize, despite the fac that currently this block type will only appear in 1 place: on the new home page. 
* But: can we do it in a more flexible way so this custom block type isn't _so_ bespoke. 
  * Assessed other custom block types available and all have requirements that do not apply to this case, so we can't reuse them.
  * Make a new block type, but we'll make it more flexible so it could be used for future instances.
    * Can use a Link field to support creating multiple buttons / link fields
    * 

**Design:**
* Separating fields within sections/outlines is fine, doesn't offend any CMS design principles. 
* Be consistent: use helptext on all fields (incl "Button text" and "Link text" fields)
* Block description: make it clear via helptext that this field won't be presented to veterans.
* Character limits: 
  * Fields should have character limits, hard limits, enforced.
  * Design system may have a suggested limit for buttons. 
* Need to add "Add more" buttons to CTA Button and Related info Link sections
  * **AR:** Determine a max # allowed for both buttons & links - @wesrowe / @thejordanwood 
    * 1 button
* Need to add Section settings section: including Section, Save As, Revision Log fields, e.g. https://prod.cms.va.gov/block/add/alert?destination=/admin/structure/block/block-content
  * **AR:** @dsasser  to send @thejordanwood  screenshot of Section fields

@BlakeOrgan @swirtSJW thanks for your input - please correct anything misstated here.

**Comment by wesrowe** [comment]
@jilladams @thejordanwood, do you recall hearing what the new block type could be called? In order to make it more reusable.

**Comment by thejordanwood** [comment]
@wesrowe I'm not sure we came up with a new name for it.

**Comment by thejordanwood** [comment]
I've made updates to this block page and added more fields to make it more flexible. I'm still waiting on the design system team to get back to me on what the character counts for buttons should be. 

What are next steps for this—do we meet again to review?

cc: @jilladams @wesrowe

**Comment by wesrowe** [comment]
Does the CMS CC team need to get back together? My intuition (based on Platform cycle) is "No" – we just need to address the issues raised in the review meeting. @EWashb, the key difference between Platform and you is that we really ran the review meeting and took our own notes. I don't see a framework for holding us accountable – e.g., Platform writes issues for product teams.

**Comment by wesrowe** [comment]
Re: how many buttons and links to allow:
I updated the notes comment to reflect my memory of our meeting. We said the max (cardinality) can always be increased later. So we can start with one CTA button and one related info link. Correct?

We need to settle on a block name. I'll slack about it.

**Comment by thejordanwood** [comment]
The [figma file](https://www.figma.com/file/OJ6ncc4hAvABO6iX5Z1Aw6/Create-Account-content-block?node-id=46%3A1754&t=yf7VyAnOcahTJJb1-1) for this has been updated based on changes that came out of the collab cycle meeting.

**Comment by wesrowe** [comment]
Char limits were provided by SWContent (Danielle) in the BE implementation ticket comments.

**Comment by wesrowe** [comment]
[Slack thread](https://dsva.slack.com/archives/C52CL1PKQ/p1676334824639489) settled requirements. Design will be updated shortly. I think this can close @EWashb @jilladams.
