### ISSUE TITLE
Empty heading in spotlight section on Lovell pages

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#12064]
## Describe the defect
On both Lovell VAMC system pages (VA and TRICARE), the spotlight section is missing the heading.

## To Reproduce
1. Go to either [Lovell VA](https://web-liqqgmzl7tsyfbwyulbkuborufuuttav.demo.cms.va.gov/lovell-federal-va-health-care/) or [Lovell TRICARE](https://web-liqqgmzl7tsyfbwyulbkuborufuuttav.demo.cms.va.gov/lovell-federal-tricare-health-care/)
2. Scroll down to the spotlight section (the light blue section in between "Manage your healthcare" and "Stories")
3. Notice that there is no heading within the light blue area, just a list of links

## Additional context
This is an H3 on existing VAMC pages, however it should be an H2. Should this be a separate task to update within the template?

## AC / Expected behavior

- [ ] Add heading to Spotlight section
- [ ] Update Spotlight heading to be an H2

## Screenshots
**Lovell page without heading**
![image](https://user-images.githubusercontent.com/106678594/208994121-11bcd1b4-7565-4f30-981e-657395d64fa7.png)

**Existing VAMC page with heading**
![image](https://user-images.githubusercontent.com/106678594/208994224-aac9354d-2d0a-4fbc-914f-176d48d570d9.png)

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by davidmpickett** [comment]
I believe this was resolved by #11940

It's possible that the Tugboat environment needs to be rebuilt for the fix to show up

**Comment by davidmpickett** [comment]
@tjheffner Can you you confirm if this issue has been resolved?

**Comment by tjheffner** [comment]
Confirmed resolved with the work done in #11940

**Comment by tjheffner** [comment]
Added a small PR to adjust the heading from h3 to h2

**Comment by laflannery** [comment]
@tjheffner Your heading adjustment, did that update only the Lovell pages or the entire template? Just want to know if I should create a new ticket for the remaining VAMC pages for the backlog, thanks!

**Comment by tjheffner** [comment]
@laflannery The whole template, no further ticket should be needed. It was merged this morning
