### ISSUE TITLE
FE: Patient wait times and satisfaction scores should not load on Lovell TRICARE locations

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#12069]
## Describe the defect
On Lovell TRICARE locations pages, patient satisfaction scores and wait times are not loading. The constant spinning icon is displaying instead.  

The problem comes from the TRICARE Facilities not being in the api where we lookup VA facilities so they will never get a valid response.  Tricare facilities have an field-facility-locator-api-id that is prefixed "tricare_"  unlike va facilities that would have a "vha_" prefix.   tricare_556  vs vha_556

## To Reproduce
1. Go to a Lovell TRICARE location page, like [Captain James A. Lovell Federal TRICARE Health Care Center](https://web-liqqgmzl7tsyfbwyulbkuborufuuttav.demo.cms.va.gov/lovell-federal-tricare-health-care/locations/captain-james-a-lovell-federal-health-care-center/) or [USS Red Rover](https://web-liqqgmzl7tsyfbwyulbkuborufuuttav.demo.cms.va.gov/lovell-federal-tricare-health-care/locations/uss-red-rover/)
2. Scroll down to the bottom
3. Confirm that in between the Spotlight section and the Get Updates section, the patient satisfaction scores are showing a spinner.

## Additional context
Lovell VA locations pages work as expected

## AC / Expected behavior

- [ ] Wait times and satisfaction scores for TRICARE facilities do not attempt to load (no spinner, no empty space on the page.
- [ ] Wait times within specific services should not load for services at TRICARE facilities.
- [ ] ~This is TBD based on VHADM feedback: If they want the Tricare variant of James A Lovell to display satisfaction and wait times, then we need to replace **tricare_556** with **vha_556** on the FE  (can not be changed in the cms for migration and status push reasons)~  This call was [made here](https://dsva.slack.com/archives/C0FQSS30V/p1671758057725019?thread_ts=1671735231.078939&cid=C0FQSS30V) so we will treat james A Lovell TRICARE no different from other TRICARE

## Implementation Details
 This could be achieved in either of two ways:
 A) Don't put the widget on the page if field_administration = Lovell - TRICARE  (this would specifically exclude only Lovell  tricare facilitities
 B) don't put the widget on the page for any field-facility-locator-api-id that does not begin with "vha_".  This would exlude any non-conformant api id and not be specific to Lovell.

## Screenshots
**Evanston VA Clinic**
![image](https://user-images.githubusercontent.com/106678594/209004084-3b422b67-3029-4d2b-8092-22857228ebec.png)

![image](https://user-images.githubusercontent.com/106678594/209004125-c797a414-45c6-47c6-a403-8db151189048.png)

**Comment by davidmpickett** [comment]
I believe TRICARE facilities do not have this data. So the actual fix is making this block not show up on TRICARE pages. I thought this was previously addressed.

**Comment by swirtSJW** [comment]
Lovell Tricare will never load that data because the data does not exist for those facilities.    Except James A Lovell.   We'll probably need to map tricare_556  (James A lovell Tricare) which does not exist in Facility API to vha_556  which does exist.

**Comment by JQuaggles** [comment]
If it does not exist, will it still try to load and spin or will it just not appear?

**Comment by swirtSJW** [comment]
Yes Jay raised a similar issue with Ryan about related locations where it was outputting a heading even through it had  no related location.  The FE access to care apps are not defensive enough.  I'll adjust the ACs on this ticket accordingly, but I am not sure if the part related to James A Lovell.  We need to discuss that a bit more.

**Comment by swirtSJW** [comment]
I just updated the ACs to reflect what we are certain of.  There is also an outstanding AC that is TBD for what to do with James A Lovell.  https://dsva.slack.com/archives/C0FQSS30V/p1671747126254259?thread_ts=1671735231.078939&cid=C0FQSS30V

**Comment by davidmpickett** [comment]
This spinner is also showing up on VAMC Facility Heath Services
![service](https://user-images.githubusercontent.com/51967950/209251923-fccf9561-ac7b-4c7f-9a31-4df95e9d880f.png)

Way back in October there was a ticket about Access to Care in which we said there was already FE logic not to display ATC data if a Facility doesn't have any. Perhaps that logic doesn't account for facility ids that aren't in its database? #11214

**Comment by JQuaggles** [comment]
Pulled into the sprint

**Comment by swirtSJW** [comment]
Closing this as the work is done and approved, just waiting on code freeze being lifted.
https://github.com/department-of-veterans-affairs/content-build/pull/1416
