### ISSUE TITLE
Add existing GA events to New Homepage

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#12065]
**NOTE: This is a temporary fix; #11965 tracks the desired long-term fix**

## Description
In #11467 we added homepage-specific events to the [New Home Page](https://staging.va.gov/new-home-page); however: they can't be tracked as written due to limitations in Google Tag Manager (GTM). A custom implementation is required on GTM. (Platform Analytics team has been asked to do it.)

As a temporary measure, we want to add GA events that work within the existing GTM scheme: 
1. Keep the existing custom events. (They will start working when https://github.com/department-of-veterans-affairs/va.gov-team/issues/50836 is resolved by the Plat Analytics team.)
2. Write new events to temporarily track the same info using existing (aka regular) GA events, until https://github.com/department-of-veterans-affairs/va.gov-team/issues/50836 is resolved.
   * New events should structurally mimic events created in https://github.com/department-of-veterans-affairs/vets-website/pull/23026/files, just don't remove the custom ones.

**New events detailed in [this Mural area](https://app.mural.co/t/vagov6717/m/vagov6717/1666210692984/3e6fbd399d485a7ca72df11518717c25bc515f06?wid=0-1672415649101)**
Screenshot of mural: 
<img width="979" alt="image" src="https://user-images.githubusercontent.com/4054752/210450273-dc91a5b4-68dc-409d-82b0-a15de05019f0.png">

## Acceptance Criteria
- [ ] Custom events implemented previously _are not altered nor removed_
- [ ] Possibly not documented elsewhere: GA event for the link in Create Account block, "Learn how an account helps you"
- [ ] Events detailed in "AC" text of Mural above:
  - [ ] "Create Account" button has a Primary Button Click event, e.g. the "Feedback" button on the existing HP: `ec: Interactions ea: Default Button CTA - [button text] - [optional: button color]`
  - [x] ~~Search input in-page gets same GA event as header search, e.g. `ec: Search ea: Search Results Returned ~ Type Ahead Enabled ~ All VA.gov ~ [search term input] el: view_search_results`~~ _No-op: Turned out to be already present_
  - [ ] Other search tools links get same GA as "zone one" links on existing HP (i.e., the 4 boxes): `ec: Interactions ea: Navigation - Zone One - ->[optional: path of destination] - [required: link text] - [optional/not defined]`
  - [ ] "Top pages" links get same GA as "zone one" links on existing HP (i.e., the 4 boxes): `ec: Interactions ea: Navigation - Zone One - ->[optional: path of destination] - [required: link text] - [optional/not defined]`
  - [ ] Random fix: changed "Top Pages" header text to "Top pages" (sentence case)
  - [ ] News promo ("Pathfinder...") links all tracked as "zone one" 
    - [ ] Block title
    - [ ] "read full article"
    - [ ] "More VA news"
  - [ ] "Sign up" button for newsletter gets "primary button click" similar to Feedback button: `ec: Interactions ea: Default Button CTA - [button text] - [optional: button color]` 

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by jilladams** [comment]
Per Dave sync today: not soft-launch blocking for turning on the modal, but is hard-launch blocking for cutting over to the new homepage / taking down the old.

**Comment by jilladams** [comment]
Search AC not valid, the rest may still be and need work. Rolling into next sprint.

**Comment by jtmst** [comment]
@wesrowe https://github.com/department-of-veterans-affairs/content-build/pull/1429

**Comment by wesrowe** [comment]
@jtmst, I just tested these fixes in staging. Most ACs are validated in GA interface (a few looked good in AdSwerve but there was no data in GA; likely because no one clicked in staging). 

However, one group of events was (mostly) missing from AdSwerve:

  - [ ] News promo ("Pathfinder...") links all tracked as "zone one" 
    - [ ] Block title – _missing any GA_
    - [ ] "read full article" – _missing any GA_
    - [ ] "More VA news" _present, but sending wrong link text; sends "read full article"_

**Comment by jilladams** [comment]
PR merged, in Review/QA to verify after deploy.

**Comment by wesrowe** [comment]
The above were solved around 1/31, forgot to close ticket. Closing.
