### ISSUE TITLE
Confusion regarding shared Lovell pages

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#12071]
## Describe the defect
Within Lovell, there is a "switch alert" at the top of the page so users are able to easily switch between the VA pages and the TRICARE pages.  I was within the Lovell VA About section (i.e. About Us, Work with us, etc.), and clicked on the switch link to view these pages on the TRICARE section and got a Not Found error.

I'm guessing that perhaps these pages are shared and the content wouldn't be different between the 2 systems? [Policies ](https://web-liqqgmzl7tsyfbwyulbkuborufuuttav.demo.cms.va.gov/lovell-federal-va-health-care/policies/)doesn't even have a switch link so it seems logical that this might be the case. 

However, if that is the case, I think the secondary nav is going to present an issue:
1. I come is as a Lovell TRICARE user, I navigate around, click on some things.
2. I want to dig a little deeper and read about Lovell so I click on About Us
3. I am now secretly, without my knowledge, moved over to the Lovell VA section of the site.
4. I read about some stuff and then I decide to go back to the health services page, using the secondary nav
5. But now, this brings me to the Lovell VA page. Yes there is a switch alert to inform me of where I am and get me back to where I need to be but that's confusing and odd and adds an extra step for the user.
6. Can we fix this?

## AC / Expected behavior

- [ ] Investigate shared pages, what should or should not have a switch alert
- [ ] Review the user case above and if it might present an issue or confusion for users

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by davidmpickett** [comment]
The specific instance you reference here seems to be connected to this existing issue: #12011

But still worth double-checking that all switch links are working as intended after that is resolved

**Comment by laflannery** [comment]
Possibly related to this and the switch links:

Missing TRICARE Pages, I'm not sure if these pages should be within the TRICARE section or not but there are link to them and they error when I try to go there:
- [Make an Appointment](https://web-liqqgmzl7tsyfbwyulbkuborufuuttav.demo.cms.va.gov/lovell-federal-tricare-health-care/make-an-appointment)
- [Pharmacy](https://web-liqqgmzl7tsyfbwyulbkuborufuuttav.demo.cms.va.gov/lovell-federal-tricare-health-care/pharmacy)

**Comment by davidmpickett** [comment]
@maxx1128 Can you confirm that the issues here are resolved?

**Comment by JayDarnell** [comment]
With the latest Lovell Demo environment build the two pages @laflannery linked above appear to be working:
- https://web-liqqgmzl7tsyfbwyulbkuborufuuttav.demo.cms.va.gov/lovell-federal-tricare-health-care/make-an-appointment/
- https://web-liqqgmzl7tsyfbwyulbkuborufuuttav.demo.cms.va.gov/lovell-federal-tricare-health-care/pharmacy/
