### ISSUE TITLE
VAMC Directions links SHOULD include sr-only text to indicate specific location

### ISSUE THREAD

**Issue by jenstrickland** [department-of-veterans-affairs/va.gov-cms#12085]
## Description

The Directions links should include text for screen readers to specifically indicate which location the link is providing directions for. Screen reader users may navigate pages by only focusable items, which means they only hear "link Directions (Google Maps)" without the surrounding context. 

Ideally all the directions links on the page should visually say "Get directions on Google Maps" as this is more clear and also consistent with what is being used in the Facility Locator.

This would include the directions link for locations under "Other nearby locations" also.

## Steps to Recreate

1. Go to a VAMC locations page, like [Lovell VA](https://web-liqqgmzl7tsyfbwyulbkuborufuuttav.demo.cms.va.gov/lovell-federal-va-health-care/locations/)
2. Start screen reading device listed in Environment
3. Navigate the page by tabbing through focusable areas
4. Verify that the Directions links are unclear where they provide directions to, without use of sight.

## Acceptance Criteria
- [ ] I expect screen reader only text is added:
`<a href="#">Get directions on Google Maps <span class="sr-only">to Erie Health Care Medical Center</span></a>`
- [ ] All directions links visually say "Get Directions on Google Maps"
- [ ] I expect this page is reviewed to see if changes to directions link are also updated according to the above mentioned logic: https://www.va.gov/maryland-health-care/ 
- [ ] Accessibility review 

## Possible Fixes (optional)

Add screen reader only text:
`<a href="#">Get directions on Google Maps <span class="sr-only">to Erie Health Care Medical Center</span></a>`

This is already done on the Facility Locator search results Directions links for reference 

## WCAG or Vendor Guidance (optional)

* [Ensure that links with the same accessible name serve a similar purpose](https://dequeuniversity.com/rules/axe/3.5/identical-links-same-purpose)

## Screenshots

![image](https://user-images.githubusercontent.com/106678594/209171394-9fbe9a76-006f-4b9c-addf-0daacf8bdec5.png)

**Comment by JQuaggles** [comment]
@laflannery assuming this got bumped as its still relevant :)

**Comment by laflannery** [comment]
Yes, this was in the other repo, I transferred it into here so I could clean it up track it in the VAMC epic

**Comment by briandeconinck** [comment]
This issue was identified during the Collaboration Cycle Staging Review for Lovell VAMC on 2/28/2023. Applicable Collaboration Cycle labels have been added to this ticket for tracking and dashboard purposes, rather than creating a duplicate ticket.

**Comment by mmiddaugh** [comment]
@laflannery when you have a moment, can you confirm if Vet Center pages use programmatically unique directions links? The labels appear to be correct. 

Examples: 

- [Cape Cod Vet Center main page](https://www.va.gov/cape-cod-vet-center/) 
- [Cape Cod Vet Center Location page](https://www.va.gov/cape-cod-vet-center/locations/)

**Comment by laflannery** [comment]
@mmiddaugh I just looked and while the Vet center pages do have unique links, these are using an aria-label rather than the sr-only solution recommended above. This solution could potentially create an issue for voice control uses as the visual link text is not the same as the label.  I would recommend opening a separate backlog issue to update the Vet center instances to use the sr-only solution.  If you agree I will go ahead and create a new issue.

**Comment by laflannery** [comment]
@mmiddaugh This ticket was originally for VAMCs which hasn't been updated yet ([Example page](https://www.va.gov/boston-health-care/locations/)). Can I reopen this? I will update the title to make this more specific to indiciate it's for VAMCs not Vet Centers

**Comment by mmiddaugh** [comment]
@kmariepat-cityfriends we may want to pull the feedback from #12072 into this

**Comment by CherylEvans** [comment]
This ticket was recreated in the va.gov-team repo Ticket #[64844](https://app.zenhub.com/workspaces/collaboration-cycle-reviews-61d89e9e5f4c120011a0ad37/issues/gh/department-of-veterans-affairs/va.gov-team/64844)
