### ISSUE TITLE
Lovell Header naming convention change

### ISSUE THREAD

**Issue by JQuaggles** [department-of-veterans-affairs/va.gov-cms#12092]
**Problem Statement:**
As a Lovell editor I want to ensure that our facility name is accurate in the headers so that we are branded correctly and it is clear to Veterans and service members the name of our location. 

**Background:**
Editors indicate they are not technically a VA site and not an MTF and are named Lovell FHCC and would like to keep the center in their naming convention

**Currently:**
Lovell Federal VA health care
Lovell Federal Tricare health care

**Desired state:**
Lovell Federal health care center - VA
Lovell Federal health care center - Tricare

**Comment by JQuaggles** [comment]
Decision point [JHL]

**Systems Level** 
Lovell Federal health care - VA
Lovell Federal health care - Tricare

H1 Title & the URL will need to be updated. 

For the actions we are injecting VA/Tricare into the names. 

**Facility level**
Medical Center Facility level, to not to have Tricare or VA on it. 
Official name of the facility is the name of the facility. 
Breadcrumbs should also have VA/Tricare at the end.

At no time should we be changing the Facility name coming from VAST. 

If it is a combined facility, unless it is one facility absorbing another, then we should not re-use the name of a facility.

**Comment by ryguyk** [comment]
**IMPORTANT**Changing this naming convention will break current Lovell-specific content-build processing. We will need to audit the current code and determine the surface area that is affected. A lot of the processing is built around the current naming.

**Comment by davidmpickett** [comment]
Moving this to unrefined because this ticket isn't currently actionable. This ticket should be a spike for identifying all the work that would need to be done to make this change (per @ryguyk's comment).
