### ISSUE TITLE
Improve sort order for satellite locations on Vet Center Locations pages

### ISSUE THREAD

**Issue by davidmpickett** [department-of-veterans-affairs/va.gov-cms#12096]
## Description
The sort order for Vet Center satellite locations was raised again by Jessica Schiefer (Vet Center RCS) during Vet Center Office Hours on December 14, 2022. 

**Background:** A Vet Center can have two types of satellite locations, although many have neither. These satellites are listed on the location page of the affiliated Vet Center. 

1. **Outstations** offer most or all services but do not quite have the maturity of a full Vet Center. They are located on VA owned/operated property with official VAST IDs and data. They can be promoted to a main Vet Center if need dictates. There are 18 outstations among the 300 Vet Centers nationwide. Some Vet Centers have two affiliated Outstations. 
2. **Community Access Points** (CAP) serve remote or underserved areas by delivering a subset of services from rented space in community locations at some regular weekly or monthly frequency. They do not have VAST IDs. There are 443 Community Access Points in Drupal currently but the number fluctuates as they open and close based on need, staffing, and other factors. 

We originally considered organizing satellite locations by their proximity to the main Vet Center but decided against it because that reference would be less meaningful than the proximity to the Veteran viewing the page. As a result, Outstations and Community Access Points are organized alphabetically under "Satellite locations". Because of naming conventions, this means a CAP offering limited services once a week may appear in the list above an Outstation which offers a broad group of services on a more full time basis. CAPs and Outstations have virtually identical displays on the page - the only indicator is the presence of  "Outstation" in the name, which could be easily missed in a lengthy list. 

At a minimum, Jessica asked if the **Outstations could be listed first** (in alpha order, if more than one is displayed) followed by an alpha list of CAPs. 

Two examples: 
[Elkton Vet Center](https://www.va.gov/elkton-vet-center/locations/) and [Great Falls Vet Center](https://www.va.gov/great-falls-vet-center/locations/)
I should note that more recently there has been an effort to standardize CAP naming (The Knowledge Base article on how to create a CAP covers this). Elkton's page reflects the naming conventions. Great Falls was one of the first 10 rolled out - before any CAP naming guidance was available. 

## Acceptance Criteria
- [ ] I expect `outstations`, `CAPs`, and `mobile` are listed in groups and displayed in this order
- [ ] I expect within each group the locations are alpha sorted 

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by maxx1128** [comment]
I would estimate this as a **2** since it seems like the two groups of satellite locations can be separated by an existing property, and then both of them can be sorted separately before being combined again. The logic for this shouldn't be too complex if it's done on the file processing side.

**Comment by davidmpickett** [comment]
Didn't we talk through all the design requirements for this with Dave C during refinement a couple weeks ago? Did something change? https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13262

**Comment by kmariepat-cityfriends** [comment]
We did, nothing has changed, but the designs are not complete, thus this is blocked by #13262 do you disagree?

**Comment by davidmpickett** [comment]
My understanding is that the decision from @davidconlon was no visual design is needed. The only decision was what order the three facility types (outstations, CAP, and mobile) should be listed under the existing **Satellite locations** heading.  I believe Dave Conlon messaged Jessica S during that meeting to confirm the order and you updated the ACs on this ticket to match. 

IMO The design ticket can be closed as not needed and this can be brought into a sprint

**Comment by kmariepat-cityfriends** [comment]
@davidmpickett gotcha, thanks for the context, ill add to upcoming sprint

**Comment by jilladams** [comment]
From scrum: should close loop with "Schiefer, Jessica L." <Jessica.Schiefer@va.gov>. Kamari will do that.
