### ISSUE TITLE
Document "Announcement" (modal) framework

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#12090]
## Description

As a developer in the VAgov ecosystem, I want to have a single source of documentation for the "Announcement" (modal) framework so that I can leverage it instead of creating something duplicate or one-off.

Notes:
- include new skip-link functionality in docs (ie, injection of extra div above skip link to catch focus)

## Acceptance Criteria
- [ ] Docs available in PW product folder
- [ ] Contact Platform team to explore more public place to include or link from? (eg Modal design system page)
- [ ] Make sure design system team knows about it, maybe invite them to own this

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by jtmst** [comment]
Documented here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/public-websites/README.md#announcement-framework
