### ISSUE TITLE
BUG: redirects from authenticated-experience links cause modal collision with soft-launch modal

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#12099]
## Describe the defect

If you try to reach an authenticated experience (url) but are not logged in, you are automatically redirected to the homepage with a query param that opens the login modal. The soft-launch modal opens over the sign-in modal, but you can't interact with the sign-in modal. You can close the underlying sign-in modal, but users are very unlikely to realize that, and this also prevents them from getting where they were supposed to go.

Example URLs that redirect to HP if use is not authenticated:
- https://staging.va.gov/track-claims/your-claims
- https://staging.va.gov/my-va/

## Reproduce behavior
- Try to reach auth url – e.g. [Track claims](https://staging.va.gov/track-claims/your-claims)
- See that you're redirected to home page
- See that Sign-in modal opens automatically
- See soft-launch modal open in front of Sign-in modal
- Notice that your mouse can't interact with any element of the soft-launch modal

![image.png](https://images.zenhubusercontent.com/61a671f5fc46c2a311655f75/09fb11d2-b450-4930-aedb-71dbc2b6cc30)

## Expected behavior of the redirect:
- Try to reach auth url – e.g. [Track claims](https://staging.va.gov/track-claims/your-claims)
- See that you're redirected to home page
- See that Login modal opens automatically
- Sign in (using test user from TUD)
- Upon successful sign-in, see that you're automatically taken back to your intended auth experience (eg Track claims)

 ## Additional context

This same issue is happening with the Medallia intercept modal. Issue and discussion [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/49518). A cause was identified in comments on that ticket.

**Note:** We may have more solutions available to us since the sign-in modal makes a visible change to the URL. It appears that all authenticated experiences that redirect add `?next=/path/to/auth/exp` to the root url. So if we can check that before displaying the soft-launch modal, that might be a viable solution.

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by wesrowe** [comment]
@jilladams, I'm watching [slack](https://dsva.slack.com/archives/C03NSH4SLQY/p1671746100280669?thread_ts=1671745134.209649&cid=C03NSH4SLQY) for Dave Conlon's response to this. I don't know if it's a launch-blocker to him or not. It's different from the Medallia collision in the sense that it's not the fault of a third party. But it isn't caused by our team, either.

**Comment by jilladams** [comment]
Post-deploy verification: 
* Set `show-homepage-soft-launch-modal` local storage var to a <25 value (`13`), meaning: homepage modal should appear (as verified via #12057 )
* Load https://staging.va.gov/?next=loginModal&oauth=true
* Login modal appears; homepage modal does not appear. 

Since modal won't go live on prod for awhile yet, considering this verified & closing.
