### ISSUE TITLE
Lovell Federal list pages (stories, events, news)  should show appropriate va.gov urls with links

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#12108]
List pages set to section Lovell Federal Health care have a FE urls that are always show as "pending".  Its list items are harvested and copied to Lovell VA and Lovell Tricare.  It correctly shows those as the urls, but shows them as pending.  But if you copy and paste them, they do resolve correctly.
~Therefore, either of two things should happen~
~A) The va.gov url should not be displayed, because there is none.~
~B) the dual links for the Lovell VA and Lovell Tricare variants should be shown.~ 

~Recommendation:  **Option A** is not only the easier choice, it is the least confusing for editors, and less likely to break as otherwise we have to hard code in the alternate listing pages.~

## ACs
- [x] on Lovell Federal Events list  node https://prod.cms.va.gov/lovell-federal-health-care/events the va.gov url should display 2 useable links in the right sidebar
- [ ]  on Lovell Federal news release list node https://prod.cms.va.gov/lovell-federal-health-care/news-releases the va.gov url should display 2 useable links in the right sidebar
- [ ] on Lovell Federal stories list node https://prod.cms.va.gov/lovell-federal-health-care/stories the va.gov url should display 2 useable links in the right sidebar
- [ ] separate curls should be made for each link showing in the right sidebar.

**Comment by swirtSJW** [comment]
Actually this is actually working correctly.   Option B is already in place 
![image](https://user-images.githubusercontent.com/5752113/209355097-6f34b7a3-c412-4388-817d-601a6d7d3d42.png)

The problem appears to be in what is being CURLed.  The curl is happening on the original URL and NOT the ones that Jay created to show the dual variants.

**Comment by swirtSJW** [comment]
This is no longer a post mvp, this is actually a bug.   
It is curling properly here https://main-liqqgmzl7tsyfbwyulbkuborufuuttav.demo.cms.va.gov/lovell-federal-va-health-care/about-us
![image](https://user-images.githubusercontent.com/5752113/209356001-198049bb-69ae-44fc-8d16-5bdec5083493.png)


This needs investigation.  I can not immediately tell whether this new dual display is CURLing one location or two.  It should be curling both.

**Comment by swirtSJW** [comment]
I adjusted the description and ACs of the ticket to accurately represent what is happening here.

**Comment by JQuaggles** [comment]
Pulling out of In Progress and back into the backlog.
