### ISSUE TITLE
Home page news promo: 508: move VA News section image to semantically follow section header

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#12100]
## Issue Details
https://github.com/department-of-veterans-affairs/va.gov-team/issues/51185

V2 home page: 
In the VA News section, the decorative image that accompanies the article comes before the "VA News" H2, meaning its alternative text is announced before the heading. Since the image goes with the article headline and teaser text, the image should follow the "VA News" H2 and article headline H3. For screen reader users navigating by headings, if they skip to the news section they'll never hear the alt text.

Right now, the image is pretty clearly a decorative image and the alt text doesn't contribute any real information. But if in the future an image is selected that's intended to communicate something more meaningful and the alt text contains actual content for screen reader users, this could be a bigger issue.

Link, screenshot or steps to recreate
As currently coded, the section looks like this:

```
<div class="vads-l-row">
      <!-- start first column-->
      <div ...>
        <div class="homepage-blog__image">
            <img ... alt="Pathfinder learn support engage" ...>
        </div>
      </div>
      <!-- end first column -->

      <!-- start second column -->
      <div ...>
        <div ...>
          <h2 ...>VA NEWS</h2>
            <h3 ...>
              <a href="..." ...>Pathfinder: The front door for engaging with VA</a>
            </h3>

          ...
        </div>
      </div>
      <!-- end second column -->
</div>
```

### Platform Recommendation
Two possible solutions:

1. Move the image so that it lives in the right place in the HTML markup, and then do some CSS layout work to visually move it to the left-hand column. This is probably a lot of CSS work, but this is the most correct solution.

2. If you're confident that the image will always be decorative, hard-code the template to have an empty alt attribute regardless of what value is entered in Drupal. This is technically not correct --- the image is in the wrong place in the document --- but there would be no real impact for screen reader users.

## AC / Expected behavior

- [ ] VA News promo image semantically follows the header
- [ ] Screen reader users hear image attributes read after hearing section header read
- [ ] When complete / verified, close https://github.com/department-of-veterans-affairs/va.gov-team/issues/51185 as well
- [ ] Accessibility review required

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by jilladams** [comment]
Changes in PR: 

![Screen Shot 2023-01-03 at 11 37 10 AM](https://user-images.githubusercontent.com/85581471/210429009-cc8f240a-f4bb-4ca5-8824-02705b964655.png)

**Comment by apisandipas** [comment]
@laflannery Can we get your review on this ticket to ensure it's working with NVDA / meets your approval ?

**Comment by laflannery** [comment]
@apisandipas The img is currently below the entire news block, not the header as stated in the description and ACs.  I completely understand why you did this however is moving it to directly after the header in the DOM not an option? Currently, not that it's below everything it seems like an after thought and also like it doesn't belong to anything.

I'm also on the fence about this even being necessary - when would this image be anything be decorative?

**Comment by apisandipas** [comment]
@laflannery It would not be possible using the conventions of the Design System Layout Grid to place the image immediately below the heading and before the other related copy. I don't think this image would ever be more than decorative for what it's worth. But I suppose that depends on the meaning of decorative in the context. Its content is not controlled by the regular content team, but by the OPIA team.

Would you agree that maybe we should shift the approach and instead make it so the alt-text is purposefully empty? That was the other suggested approach in the main body of the ticket. This seems like it would avoid any potential Screen Reader-user confusion that would potential exist with the current use of alt-text.

**Comment by laflannery** [comment]
@apisandipas Yes, let's go with the purposefully empty approach: `alt=""`.

I like this approach better, given the limitations of the design grid as well as the fact that since we are not showing this on mobile, we are already actively making the decision there that this is not very meaningful and most likely will not add to the information for this news item.
