### ISSUE TITLE
Competitive Analysis first pass - UX Writing

### ISSUE THREAD

**Issue by rachel-kauff** [department-of-veterans-affairs/va.gov-cms#1211]
**Background**
I'd like to know how other gov or public sector projects out there have solved for UX design and writing problems on the back end. 
* What kind of principles guided their design work?
* How did they organize their thinking around communication ecosystems and the back end experience for users?

AC
- [ ] We've identified other projects that have designed for an enterprise editorial experience
  - [ ] Potentially: mass.gov
  - [ ] Chat with Eileen
- [ ]  We've identified areas of overlap and difference in the design problems of those projects vs. ours
- [ ] We have a list of takeaways that will inform our project

**Comment by EWashb** [comment]
We have our own UX writing standards now.
