### ISSUE TITLE
Edit the Covid status descriptions before roll out

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#12111]
## Description
Before the new use of Covid Status can roll out, it is important that the supplemental status terms contain the nationalized text 

Below is the text, with "Low" and "Medium" updated from [this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/53555#issuecomment-1431982352) and "High" remaining the same.

### Low
- Everyone must wear a mask in most areas where Veterans are present. Check for signs when you arrive so you know what’s required.
- Visitors are welcome.
- Please self-screen. If you've had any COVID-19 symptoms in the past 48 hours, call first unless you need care now.
[Check COVID-19 symptoms on the CDC website](https://www.cdc.gov/coronavirus/2019-ncov/symptoms-testing/symptoms.html)

Check on Mondays for each facility’s latest guidelines.

### Medium
- Everyone must wear a mask in most areas where Veterans are present. Check for signs when you arrive so you know what’s required.
- Your care partner is welcome (no other visitors).
- Please self-screen. If you've had any COVID-19 symptoms in the past 48 hours, call first unless you need care now.
[Check COVID-19 symptoms on the CDC website](https://www.cdc.gov/coronavirus/2019-ncov/symptoms-testing/symptoms.html)

Check on Mondays for each facility’s latest guidelines.

### High
- Everyone must wear a mask and practice physical distancing.
- We may screen you for COVID-19 symptoms at the entrance.
- Approved visitors only. Ask your care team who can visit.
- Ask your team about phone or video appointment options.

Check on Mondays for each facility’s latest guidelines.

## Acceptance Criteria
- [x] Covid Low text is correct https://prod.cms.va.gov/taxonomy/term/1037
- [x] Covid Medium text is correct https://prod.cms.va.gov/taxonomy/term/1036
- [x] Covid High text is correct https://prod.cms.va.gov/taxonomy/term/1035
- [x] If the term descriptions change, Cypress tests are updated

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by omahane** [comment]
I asked that the suggested language for masking for Low and Medium levels be considered for the VAMC facility page context: https://dsva.slack.com/archives/C0FQSS30V/p1676488000347719?thread_ts=1675957843.562459&cid=C0FQSS30V

**Comment by omahane** [comment]
The above issue has been resolved and is reflected in the language of the description.

**Comment by omahane** [comment]
I have updated the taxonomy, as necessary, on prod.
