### ISSUE TITLE
[Spike] VAMC FE Testing Suite

### ISSUE THREAD

**Issue by JQuaggles** [department-of-veterans-affairs/va.gov-cms#12123]
**User Story**
As a product owner I want to know what new tests are needed to run on the VAMC FE Product Suite so that I can prioritize those tests to be built.  

**Acceptance Criteria**
1) FE Tests
- [ ] An understanding of what tests we currently are running for VAMC Facilities
  - [ ] The list of tests is documented within the product documentation
- [ ] A prioritized list of additional tests that can be run against the VAMC Facilities product

**Comment by eselkin** [comment]
Does this mean, outstanding un-"covered" code? Like what areas don't meet the 75% code coverage? Like what unit tests are there and what need to be added?
Or is this a README of tests?
Shouldn't outstanding untested code get an issue opened for them and then prioritized that way?

**Comment by xiongjaneg** [comment]
@eselkin Given the age of this and your questions, I'm inclined to icebox this for now. 

Would you please just elaborate on your comment "Shouldn't outstanding untested code get an issue opened for them and then prioritized that way?" and the current process, if any.

**Comment by xiongjaneg** [comment]
closing in favor of work being done in #15461
