### ISSUE TITLE
Create ATO Guidance Document

### ISSUE THREAD

**Issue by TheBoatyMcBoatFace** [department-of-veterans-affairs/va.gov-cms#12122]
## Overview
The Platform CMS team needs to create an ATO (Authority to Operate) summary document that outlines the requirements for retention of static site builds, image versioning retention, and media asset accessibility as it relates to external user hot linking.

### Details
- **Retention of static site builds:** It is important for the Platform CMS team to retain copies of static site builds in order to have a record of the site's history and to be able to roll back to previous versions if necessary. The ATO summary document should specify how long static site builds should be retained, and whether there are any specific storage requirements (e.g. location, security measures).

- **Image versioning retention:** It is also important for the Platform CMS team to retain versions of images in order to have a record of any changes made to the images and to be able to roll back to previous versions if necessary. The ATO summary document should specify how long image versions should be retained, and whether there are any specific storage requirements (e.g. location, security measures).

- **Media asset accessibility:** In order to ensure that external users have access to media assets (such as images and videos), it is important for the Platform CMS team to consider issues such as hot linking. The ATO summary document should outline any policies or procedures in place to prevent unauthorized hot linking of media assets.

### Additional Resources/References 
- [VA ATO Streamlining](https://www.oit.va.gov/reports/year-in-review/2018/eliminate-material-weaknesses/ato)

## Acceptance Criteria
- [ ] Feedback sought from A6 Contract team
- [ ] Feedback sought from CA Legal
- [ ] ATO Guidance Document exists in va-gov confluence
- [ ] Document approved by: A6 Contract/Legal
- [ ] Document approved by: CA Legal
- [ ] Document approved by: VA PO Team

**Comment by EWashb** [comment]
This is not within scope.
