### ISSUE TITLE
Discovery: Repeatable report of headings violations progress

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#12127]
## Description
As we are looking at ways in which we can begin to remediate the heading violations on Drupal CMS pages, we also want a way to see progress on if these remediation efforts are working. Is there a way that I can easily run the heading violations export? Or if not the current export, is there another measure/scan that I should look at that can be run by me?

We are consciously duplicating reports in order to make a more accurate report. 

### Additional context
If we do use the current scan, I think we should look at updating this script #11900 

## Acceptance Criteria
- [x] Determine the easiest/most efficient way to report on progress of remediating heading violations

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [x] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by ndouglas** [comment]
I feel like this should be probably be integrated into the current content-build process and reported to DataDog as a gauge metric.  It depends on a successful content build completing and nothing else, really.  It can also be dumped into the log for each content build so that you can see which files are affected.

The only alternatives I can think of to this approach are fairly painful, I think.

**Comment by EWashb** [comment]
Start with the actual number and the output of what the pages are as a first step. 2nd step- match them to the owner (prob need a second issue for this part).

**Comment by EWashb** [comment]
Should we only run this on the first content build of the day? The last? We do not want to slow the build down every single time.

**Comment by EWashb** [comment]
@laflannery this will need to stretch into the next sprint. Nate has been out sick. cc: @dawnpruitt

**Comment by laflannery** [comment]
This is the latest export Nate gave me: https://pr12191-07ub2sgt04vfeyszauoytvw3fqtwpy6z.ci.cms.va.gov/heading_order_violations.html

We are still working on it - it's not automated yet but it's definitely a solid start
