### ISSUE TITLE
Update PDF Cert Alert for post-Jan 7

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#12138]
**Content is now available, see ticket body below**

[SWContent intake ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/51357).

Note: [Adobe support doc here](https://experienceleague.adobe.com/docs/experience-manager-65/forms/administrator-help/configure-acrobat-reader-dc-extensions/updating-expired-reader-extension-certificates.html).

## Description

As a Veteran using Find-a-form, I want to see an informational alert on the FaF search page so that I'm aware of the old-PDF problem and everything should work well now.

### Copy changes

**Search page:**
Header: Use the latest version of Acrobat Reader
Body: Some VA forms may not work with older versions of Acrobat Reader. You may also need to download a new copy of the VA form.
[Get Acrobat Reader for free from Adobe](https://get.adobe.com/reader/)

**Detail page:**
_remove alert completely_

## Acceptance Criteria
- [ ] Search page – info alert updated
- [ ] Form Detail page – remove alert completely

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by jilladams** [comment]
@wesrowe https://github.com/department-of-veterans-affairs/va.gov-team/issues/51357 isn't resolved yet - can you clarify if the copy in this ticket body is final / can be merged? If not, @apisandipas pls block the PR til https://github.com/department-of-veterans-affairs/va.gov-team/issues/51357 provides final copy.

**Comment by wesrowe** [comment]
Content finalized, see ticket body
