### ISSUE TITLE
COVID Status - Hide inline entity forms on the locations page

### ISSUE THREAD

**Issue by JQuaggles** [department-of-veterans-affairs/va.gov-cms#12137]
## Description
Carry over from #10708
The COVID Status update entity is changing for individual facilities, however the operational status is also updatable from the inline entity at the systems level. The operational status matches the individual page status so the COVID Status update needs to be included within the inline entity forms to be editable by the systems level editor. 

As a VA Medical Systems editor, I want to be able to edit the COVID Status of a facility within my system just as I am able to do with Operational Status, so that I can provide complete facility updates if necessary

## Acceptance Criteria
- [ ] I expect that the COVID Status form is 
As a Systems Editor, within the inline entity forms on the locations page, I can update the COVID status of the facilities within my system. 
- [ ] When a Systems Editor updates the COVID Status of the facilities, it updates the facility Front End with those changes.
- [ ] When the COVID status of a facility is updated within the inline forms on the locations page for the system, that COVID status is stored and matches the COVID status when an editor views the specific facility page in the CMS.
- [ ] Requires design review
- [ ] Requires Accessibility review
- [ ] Create tests for the functionality

**Comment by kmariepat-cityfriends** [comment]
This enhancement did not occur and the decision to remove COVID health status means we will not implment what is outlined in this card
