### ISSUE TITLE
Contact HUD API owner for clarification and governance, particularly for Zip code

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#12141]
## Description

Based on Daniel's work with the API itself, we need to know:
- Is there a way to get the 10-digit "full FIPS code" from zip code? So far Daniel could only get a 5-digit code, which is not adequate to query the Income Limit data from HUD (either by API or in the spreadsheet of "section 8" data that we got from Steve Ward of the VistA team).

We also need to have a governance conversation about:
- What are the uptime and traffic specs on HUD APIs (zip code, income limits)?
- How do we get support when needed, e.g., if the API stops working as expected?
- How can we expect to be notified of any changes to the API?

## Acceptance Criteria
- [ ] Get contact details for those knowledgeable of info above
- [ ] Start discussion by email
- [ ] Write ticket for follow-on investigation as needed

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by jilladams** [comment]
Determined this info isn't necessary / we aren't likely to use the HUD API. Closing as no op.
