### ISSUE TITLE
Investigate arechitectural needs, governance guidance

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#12142]
## Description

Explore with Platform and OCTO-DE technical stakeholders: what sort of API can we build, accessed through vets-api, to serve the data to Veterans.
- Home for data – what are our options for storing the data that are accessible to vets-api?
  - We can continue to maintain it into the indefinite future
  - Ideally the business unit would be able to maintain it (again)
- Based on experience with Facility Locator, Veterans are comfortable with either zip-code or city,state input.

## Acceptance Criteria
- [ ] Make contact with OCTO / Platform guides
- [ ] Testable_Outcome_Y
- [ ] Testable_Outcome_Z
- [ ] Requires design review

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by FranECross** [comment]
closing older ticket; a new one will be created when this subject crops up again and we can move forward with the work.
