### ISSUE TITLE
Investigate old IncLim app's back-end, Platform requirements for Income Limits data storage and API architcture

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#12143]
### 1st choice: Figure out how to reuse the old app's API
Hypothesis: if we can find the original endpoint, maybe we could reuse part of it? e.g., the zip code lookup.
- Pursue the route that the existing app uses – looking for server that's at end of route `https://www.va.gov/healthbenefits/apps/explorer/AnnualIncomeLimits/HealthBenefits`. Nginx knows about it and is directing traffic. 
  - Not referenced in any VA code bases we can see
  - Server owner could point us to application or source code?

Stakeholder to start with: Eric Swain – he was the IT-side stakeholder who said "the keys were lost."

Per Steve: first place to ask is Platform Support.

### 2nd choice: Understand how to build something new
Explore with Platform and OCTO-DE technical stakeholders: 
- Home for data – what are our options for storing the data that are accessible to vets-api?
  - We can continue to maintain it into the indefinite future
  - Ideally the business unit would be able to maintain it (again)
- External APIs – what options do we have for calling external APIs, e.g. a zip-to-FIPS lookup? (e.g., HUD API)
  -  Note: Income Limits data is by county, and counties can be uniquely identified in that data set by the 10-digit FIPS number

## Acceptance Criteria
- [ ] Made contact with OCTO / Platform guides
- [ ] Tracked down server owner of old-app codebase
- [ ] Testable_Outcome_Z
- [ ] Requires design review

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by swirtSJW** [comment]
Great explainer doc for API's  https://dsva.slack.com/files/U016LS0Q802/F04HP4B41LJ/ecp-explainer-va.gov-lighthouseoverlap-050123-1801.pdf?origin_team=T03FECE8V&origin_channel=C02HX4AQZ33    Useful but does not addres the source code of this ap.p.

**Comment by swirtSJW** [comment]
Database is not directly accessible, but could be accessible through a clone https://dsva.slack.com/archives/C02HX4AQZ33/p1672943313646129?thread_ts=1672872917.082849&cid=C02HX4AQZ33

**Comment by swirtSJW** [comment]
Original platform support request https://dsva.slack.com/archives/CBU0KDSB1/p1672429202855089
I bumped the thread as it went cold around the holidays.

**Comment by jilladams** [comment]
Sought the info, determined it wasn't necessary for next steps. Closing as no-op, does not roll into S75.
