### ISSUE TITLE
Seek source code for old Income Limits app

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#12144]
## Description

We're particularly curious about how they:
- Stored / ingested data
- Made data available to FE
- Looked up zip code for a key to the HUD data (by FIPS or county/state)

## Acceptance Criteria
- [ ] Contact stakeholders, starting with Eric Swain
- [ ] Write ticket for actual code investigation (will be an engineer ticket)

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by swirtSJW** [comment]
Original platform support request https://dsva.slack.com/archives/CBU0KDSB1/p1672429202855089
I bumped the thread as it went cold around the holidays.

**Comment by jilladams** [comment]
Sought the info, determined it wasn't necessary for next steps. Closing as no-op, does not roll into S75.
