### ISSUE TITLE
Internal review and iteration cycle on Income Limits UX Design

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#12140]
## Description

Review UX design with Dave Conlon, Dave Pickett, and Cindy Merrill.

## Acceptance Criteria
- [x] Meet with Pickett & Cindy
- [x] Meet with Conlon
- [x] Iterate based on feedback
- [x] Stabilize Sketch to make interactive prototype in next ticket
- [x] Write ticket for creating clickable prototype for usability testing

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by thejordanwood** [comment]
Ready to move on to a clickable prototype.
