### ISSUE TITLE
Discovery: Technical considerations for requiring editorial revision log

### ISSUE THREAD

**Issue by EWashb** [department-of-veterans-affairs/va.gov-cms#12157]
## Description

As we look into proper workflows for editors updating outdated content, a required revision log will be a necessary step in the completion ask. We need to make a technical determination of what this means and how we can make a revision log required for all editors.

## Acceptance Criteria
- [x] technical discovery of revision log requirements
- [x] Coordinate with UX to determine what the best solution would be for the editorial process
- [x] Share findings with PM/PO

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [X] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by swirtSJW** [comment]
See the implementation already used on vet centers
It is basically a matter of making them a required field.   Relatively easy to do.

**Comment by EWashb** [comment]
@swirtSJW if I were to create the ticket to do the required field implementation do you think you could get to that in this sprint (sprint 77)?

**Comment by EWashb** [comment]
I'm going to close this one in favor of just creating an implementation ticket for requiring VAMC revision logs. This is extra work that's not needed
