### ISSUE TITLE
Architecture: Work with Platform Team to figure out where we can store Income Limits threshold data

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#12158]
### Considerations
- What would interface for data import look like?
- Who owns the data store (Platform or someone else)?
- (Cost might be something to ask Platform about)
- What would governance look like for the model?

Models to consider:
- Similar to Find-a-form – eg, Drupal + Lighthouse
  - This would be different/new in that it makes Drupal source of truth
- NCA Facilities - Lighthouse pulls a CSV from somewhere, serves it up
  - Does LH have a place/process where business can provide data in a format, LH provides it? Where can you pull data from? 
  - Clear: we're building this, not trying to make it a LH priority; just asking LH for "tips and ideas"
- Does Sharepoint have a database functionality available?

## Acceptance Criteria
- [ ] We have identified at least one database that can store the data to drive IncLim app and be accessed from the VAgov FE
  - [ ] If there's more than one option, establish pros and cons

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by dsasser** [comment]
Pertinent slack conversation: https://dsva.slack.com/archives/C02HX4AQZ33/p1672872917082849

**Comment by dsasser** [comment]
We have located a VA owned backend which could provide the data required to run the IL app.

The backend is using an AWS Oracle RDS in the [VAEC AWS gov-east VPC](https://dsva.slack.com/archives/C02HX4AQZ33/p1672954651211319?thread_ts=1672872917.082849&cid=C02HX4AQZ33).

The backend is owned by the VHA's Veterans Enrollment System. The point of contact is Joshua Faulkner (joshua.Faulkner@va.gov).

## What would interface for data import look like?
Data import is handled by the VHA. 

## Who owns the data store (Platform or someone else)?
VHA VES

## Cost
Unknown, but anecdotally trivial enough not to warrant any ATO.

## What would governance look like for the model?
Public Websites would own the API (vets-api)
Platform would own the connection to the backend
VHS would own the RDS server

**Comment by dsasser** [comment]
What remains to be done:

1) Build a rough architecture document for which to present to Platform.
2) Present architecture (via Platform slack issue) to Platform for the purpose of identifying the possibility of connecting from vets-website to the RDS.
3) Further actions are dependent on Platform's response.
4) While working with Platform with the initial draft architecture, development of the API design will begin.

**Comment by dsasser** [comment]
I'm attaching the initial draft of the architecture below. This is a draft of the expected architecture. Once the architecture is more solidified (via conversations with Platform), I'll add the information to the product space in the va.gov-teams (or the related sensitive) repo.

[[DRAFT] Income Limits Architecture_2023-01-18_22-40-06.pdf](https://github.com/department-of-veterans-affairs/va.gov-cms/files/10451753/DRAFT.Income.Limits.Architecture_2023-01-18_22-40-06.pdf)

**Comment by wesrowe** [comment]
Thresholds available in the VES database (other than GMT (zip) data, which is in another table):
![Screenshot 2023-02-28 at 7 16 00 AM](https://user-images.githubusercontent.com/4054752/221976656-3d8e9de8-b7d3-4d4b-adbf-f0536c77644f.png)
