### ISSUE TITLE
Enable preview for content listing node types (who owns it?)

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#1216]
## User Story or Problem Statement

as a creator of a listing page, i want to be able to preview my content. Inclusive of various list types: Stories, News, Events.

Original report: couldn't click preview at https://prod.cms.va.gov/pittsburgh-health-care/health-services and get a preview. As of May 2023, preview server is working for that particular URL. 

**5/3/23 check: List types:**
* https://prod.cms.va.gov/pittsburgh-health-care/health-services - Preview button appears / works
* https://prod.cms.va.gov/charlotte-vet-center/locations - Vet Center locations list - Preview button appears / works
* https://prod.cms.va.gov/columbia-missouri-health-care/events - event listing - no Preview button
* https://prod.cms.va.gov/kansas-city-health-care/about-us/leadership - Leadership list - no Preview button
* https://prod.cms.va.gov/columbia-missouri-health-care/news-releases - News release list - no preview button
* https://prod.cms.va.gov/atlanta-health-care/stories - Stories list - no preview button
* https://prod.cms.va.gov/clarksburg-health-care/locations - VAMC System locations list - no preview button
* 

**Next steps:** Verify repro on other listing types. 

## Acceptance Criteria

- [ ] I should be able to click Preview on a listing page and get a preview

**Comment by mmiddaugh** [comment]
@kevwalsh can this one be closed?
