### ISSUE TITLE
Write first draft of IncLim UX research plan

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#12163]
## Description

[no additional tasks needed here]

## Acceptance Criteria
- [x] Write first draft of user research plan ideas
- [x] Document the goal(s) of the user research
- [x] Document research questions
- [x] Document hypotheses
- [x] Record high-level schedule to align prototype and research preparation to target dates
- [x] Draft complete research plan in github
- [x] Share research plan with someone on UX team for feedback, and incorporate their feedback
- [x] Discuss session scheduling, notetaking, and synthesis with Jordan
- [x] (optional) Internal review of first draft of research plan with Jordan/DaveP/Wes

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by cindymerrill** [comment]
Drafted some parts of the research plan and discussed with team. Need to incorporate feedback and detail out more sections of the plan. Working document: https://docs.google.com/document/d/1bZJcWaTckpfpqksJUyfQ83idxe8j9fidoGXrISnFCQI/edit?usp=sharing

**Comment by cindymerrill** [comment]
Drafted research plan in github: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/income-limits-app/research/2023-01-income-limits-usability/research-plan.md

**Comment by cindymerrill** [comment]
Revised research plan, and then shared it with Dave Pickett and my larger UX team (asking for someone to review it).

**Comment by cindymerrill** [comment]
Incorporated feedback from Jordan and Dave P. Waiting for feedback from @wesrowe and potentially more discussion about participant recruiting.

**Comment by cindymerrill** [comment]
Incorporated feedback from another UX team member, and discussed recruitment backup plans.

**Comment by cindymerrill** [comment]
Wes had no feedback. Now waiting for updates from Content and IA feedback on prototype, and then will share with Dave Conlon.
