### ISSUE TITLE
Homepage modal: show modal to 100% of users, deprecate local storage mechanism for controlling rollout

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#12162]
The homepage modal will be set to show to 75% of users via #12161 .  We want to now make the modal visible to 100% of users, which effectively means: removing any control logic / use of the local storage var. 

Local storage var `show-homepage-soft-launch-modal` controls how many users will see the homepage modal on page load: 
https://github.com/department-of-veterans-affairs/vets-website/pull/23009/files#diff-bd506acc2fab742c1cca334e5ac7d1636e3887b8c96ae0f167ae72aaa023a070R18

## Acceptance Criteria

- [x] Positive: Modal should appear on the VA.gov homepage for any new session
- [x] `show-homepage-soft-launch-modal` is no longer set or used
- [x] `useStaggeredFeatureRelease` is preserved for future use in a way that is accessible by teams that want to use it
- [x] documented how other teams can use it - readme in the Announcement framework component (`src/platform/site-wide/announcements/README.md`) exists. Updates may be minimal.
- [x] handed off/ticketed publishing documentation in a place where it would be visible to other teams, e.g., Platform docs about how VA rolls out product iterations

**Comment by jilladams** [comment]
From DaveC in DM today: "Homepage modal to 100% is stretch for this sprint. If we don't get to it next week I'd like to get to that first thing next sprint."

**Comment by jilladams** [comment]
It's fine for this to go out in 2 PRs: 1 to move to 100% when we get the greenlight, and a follow up to address the remaining ACs to unset the local storage var at all, etc.etc. (Meaning: we shouldn't block moving to 100% on addressing the tech debt.)

**Comment by jilladams** [comment]
Talked to Daniel about the last AC here, and we determined: probably still wise to do, as a breadcrumb / link from https://depo-platform-documentation.scrollhelp.site/developer-docs/feature-toggles to a new page. 

To add a page to these docs requires a Platform ticket, e.g.: https://github.com/department-of-veterans-affairs/va.gov-team/issues/45017

**Comment by dsasser** [comment]
Platform docs request: https://github.com/department-of-veterans-affairs/va.gov-team/issues/57288

**Comment by wesrowe** [comment]
Looks good to me! closing.
