### ISSUE TITLE
Create public DataDog dashboards for CMS reporting needs

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#12172]
## Description
We periodically need to retrieve data from Datadog for various reports, for example our weekly Team of Teams report and monthly status reporting for the program. We should identify all places where we need to report data that is collected in Datadog, collect it in a publicly viewable dashboard, and clearly document the links to each dashboard and what its purpose is.

Example: This dashboard was constructed to satisfy the weekly reporting needs of the Platform CMS Team for the Team of Teams meeting. https://app.ddog-gov.com/sb/f327ad72-c02a-11ec-a50a-da7ad0900007-53c1ede411867ef7c08db0a94319b051

## Acceptance Criteria
- [ ] All known reporting needs are identified, including what metrics are needed and over what time period
- [ ] Dashboards are constructed to cleanly provide that data, if they don't exist
- [ ] Links to the dashboards are recorded in documentation that is known to the people who need the reports

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [x] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [x] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by timcosgrove** [comment]
(assigning to myself in sprint 76 mostly to not lose sight of the ticket)

**Comment by ndouglas** [comment]
See also #10990, which this might conceivably supplant.

**Comment by productmike** [comment]
closing in lieu of need diminishing.
