### ISSUE TITLE
PACT Act wizard: Artifact gathering across crews (Benefits, etc)

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#12171]
The content and outcomes of the PACT Act wizard will be decided in partnership with the Benefits teams, and the Sitewide Content team. First step: make contact, gather data.

**Comment by wesrowe** [comment]
Moving back to New/Unref since Dave C said it is awaiting stakeholder movement with no ETA.

**Comment by jilladams** [comment]
This is way out of date and closeable.
