### ISSUE TITLE
Lovell VA Facility Services showing on TRICARE VAMC Health System Service pages

### ISSUE THREAD

**Issue by omahane** [department-of-veterans-affairs/va.gov-cms#12182]
## Description
The TRICARE VAMC System Health Services are displaying the VA Facility Health Services on node:view.

### COVID-19
When there is both a TRICARE and a VA VAMC Facility Service of the same VAMC System Health Service type, they are both showing on the TRICARE page. (_Note: There's only one such example currently: COVID-19_)
![prod cms va gov_lovell-federal-tricare-health-care_health-services_covid-19-vaccines-at-lovell-federal-tricare-health-care](https://user-images.githubusercontent.com/766573/210879274-2e7048fd-3b76-4475-9018-3f8740a756e8.png)

### Addiction and substance abuse care
When there is only a VA VAMC Facility Service of a VAMC System Health Service type, it is showing on the TRICARE page. 
![prod cms va gov_lovell-federal-tricare-health-care_health-services_addiction-and-substance-abuse-care-at-lovell-federal-tricare-health-care (1)](https://user-images.githubusercontent.com/766573/210880281-0361cfdb-21e9-469f-9be5-dc5aa445a732.png)

## Conclusion 
It does not appear to be an issue with the code but in the database itself. 

I have tested this on the [Lovell Demo site](https://main-liqqgmzl7tsyfbwyulbkuborufuuttav.demo.cms.va.gov/lovell-federal-tricare-health-care/health-services/covid-19-vaccines-at-lovell-federal-tricare-health-care)
- Deleting the original Lovell VA "COVID-19 vaccines - Captain James A. Lovell Federal Health Care Center" node
- Creating a new "[COVID-19 vaccines - Captain James A. Lovell Federal Health Care Center](https://main-liqqgmzl7tsyfbwyulbkuborufuuttav.demo.cms.va.gov/lovell-federal-tricare-health-care/locations/captain-james-a-lovell-federal-health-care-center/covid-19-vaccines)" (TRICARE) node
- Creating a new "[COVID-19 vaccines - Captain James A. Lovell Federal Health Care Center](https://main-liqqgmzl7tsyfbwyulbkuborufuuttav.demo.cms.va.gov/lovell-federal-va-health-care/locations/captain-james-a-lovell-federal-health-care-center/covid-19-vaccines)" (VA) node

After doing so, when I visited the [COVID-19 vaccines at Lovell Federal TRICARE health care](https://main-liqqgmzl7tsyfbwyulbkuborufuuttav.demo.cms.va.gov/lovell-federal-tricare-health-care/health-services/covid-19-vaccines-at-lovell-federal-tricare-health-care) page, it only had the Lovell TRICARE VAMC Facility Service, not the VA listed.

Checking [COVID-19 vaccines at Lovell Federal VA health care](https://main-liqqgmzl7tsyfbwyulbkuborufuuttav.demo.cms.va.gov/lovell-federal-va-health-care/health-services/covid-19-vaccines-at-lovell-federal-va-health-care) to make sure there's no regression confirms that the VA VAMC Facility Health Service shows the correct VAMC Facility Health Service, too.

I did a similar test in the Lovell demo environment with the "Returning service member care" VAMC Facility Service.

## Suggested Implementation Steps
- [ ] Delete the current Lovell VA Facility Health Services
- [ ] Create new Lovell VA Facility Health Services

## Actual Implementation Steps
- [x] Delete the current TRICARE System Health Services
- [x] Create new TRICARE System Health Services
- [x] Add the system service to the appropriate TRICARE facility health service
- [x] Changes have been tracked on a [Google Sheet](https://docs.google.com/spreadsheets/d/1z5h6mnJUokRvrrxq_Un6cYMYd_GUIttBbyjlRQ-JXl0/edit?usp=sharing).

## Acceptance Criteria
- [x] Lovell TRICARE VAMC System Health Services show facility descriptions for the TRICARE facilities only.
- [x]  Lovell VA VAMC System Health Services show facility descriptions for the VA facilities only.

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by swirtSJW** [comment]
I think your solution of deleting and recreating is fine.   

I do think this is revealing a possible problem with the query that brings in the facility health services.  It is as though the CMS is not aware that the latest revision of that facility health service is not pointed at the facility.  It is as though the query is returning ANY facility health services that have ever been pointed at that facility.  I 
It could be the result of cloning (though I think that would be broken the other way around.
![image](https://user-images.githubusercontent.com/5752113/210896631-bc6ed4e2-9b93-4f49-abba-a2446293383b.png)

**Comment by swirtSJW** [comment]
My point is, this is not specific to Lovell not working right.  This is specific to moving a service to another system or facility or both.  It does not come up often, but I think we have seen this before.

**Comment by omahane** [comment]
That is exactly what I was thinking: that it either had something to do with cloning or moving it. I don't really know which, though.

**Comment by davidmpickett** [comment]
@swirtSJW @omahane It sounds like there's no Lovell-specific work left to complete here, correct? 

If so, I suggest either:
1) renaming this ticket to be about the underlying issue that is shared across VAMCs 
2) closing this ticket and creating a separate ticket stub for that issue

**Comment by omahane** [comment]
@davidmpickett Giving that we think we know (but are not entirely sure) as to the cause, I agree that a spike for investigating why this happens *should* be made.

The Lovell-specific issue of VA services showing TRICARE pages, though, could be fixed quickly with the implementation steps identified in this ticket. I don't think it's necessarily a development, task, though, but one for editors.

**Comment by omahane** [comment]
I created this spike around understanding what's actually happening and how to prevent it: #12232

**Comment by omahane** [comment]
@Dottisea There's no code to review. I have done the work and checked it over. Is there any one else who should look at it.

**Comment by davidmpickett** [comment]
In Lovell office hours today, one of the editors said they had noticed the changes and hadn't seen any additional instances of the problem (and would let us know if they did). I think that qualifies this as reviewed.

**Comment by omahane** [comment]
I should note here that I also asked @stefaniefgray to spot check over in Slack with this suggestion:
> **Checking the TRICARE health services:**
> https://prod.cms.va.gov/admin/content?title=&type=regional_health_care_service_des&moderation_state=All&owner=1039
>Open a handful to see if they have any VA facility service on them.

> **Checking the VA health services:**
> https://prod.cms.va.gov/admin/content?title=&type=regional_health_care_service_des&moderation_state=All&owner=1040
> Open a hanful to see if they have any TRICARE facility service on them.

**Comment by stefaniefgray** [comment]
@omahane Thanks for the @-mention -- here are my results:

###Tricare VAMC System Health Services:
Searched for "VA health"

**Mentions of VA health in system health service descriptions:** 

1. https://prod.cms.va.gov/lovell-federal-tricare-health-care/health-services/mental-health-care-at-lovell-federal-tricare-health-care
2. https://prod.cms.va.gov/lovell-federal-tricare-health-care/health-services/lgbtq-veteran-care-at-lovell-federal-tricare-health-care
3. https://prod.cms.va.gov/lovell-federal-tricare-health-care/health-services/returning-service-member-care-at-lovell-federal-tricare-health-care
4. https://prod.cms.va.gov/lovell-federal-tricare-health-care/health-services/laboratory-and-pathology-at-lovell-federal-tricare-health-care

###VA VAMC System Health Services:
Searched for "Tricare" on all pages -- found zero instances

--------
Anything else I should check? Should I also check VAMC Facility Health Services, @omahane ?

**Comment by omahane** [comment]
@stefaniefgray Thanks for looking at this. I should have been more descriptive in the issue, but this was specifically around the mismatch of VAMC System Health Services and the VAMC Facility Health Services that are listed on their pages. 

I see the issues you have described. They are related to the taxonomy, which is not yet been finished (see attached screenshot)
![prod cms va gov_taxonomy_term_54_edit_destination=_node_52730](https://user-images.githubusercontent.com/766573/214085161-41cc1e1f-82c7-4a1f-b887-f16c9059a35b.png)
, but is outside the scope of this ticket.

**Comment by omahane** [comment]
Based on today's standup and comments from @davidmpickett, @stefaniefgray and @TroyA6, I'm closing this ticket. Should other like issues arise, we'll address them in a new ticket.
