### ISSUE TITLE
Redirect Request for: Sonora VA Clinic from placeholder URL to CMS URL

### ISSUE THREAD

**Issue by JayDarnell** [department-of-veterans-affairs/va.gov-cms#12181]
### Implementation date
When does this request need to be live: as soon as possible

### Redirects 
| Current URL  |  Redirect Destination or New URL |
| ---  |  --- |
| /find-locations/facility/vha_612GL | /northern-california-health-care/locations/sonora-va-clinic/ |

## CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [x] `⭐️ User support`

**Comment by stefaniefgray** [comment]
Redirect of https://www.va.gov/find-locations/facility/vha_612GL to facility homepage has not gone through yet
