### ISSUE TITLE
Can't save or edit staff profiles without filling in the body field.

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-cms#12187]
## Describe the defect
The staff profile biography fields should be optional.

There is a submit function specified in `docroot/modules/custom/va_gov_backend/src/EventSubscriber/EntityEventSubscriber.php` that should unset the `required` status of the field when the checkbox is unchecked.

However, it is incorrectly specified and does not fire in the expected context.  As a result, the field behaves as though it is required even when the checkbox is not checked.

This was noticed recently as a result of a fix for [this bug in `auto_entitylabel`](https://www.drupal.org/project/auto_entitylabel/issues/2927959).  Previously, validators for these and other (not sure how many) fields were being bypassed completely.  Now that the bug has been fixed, and validation works, we encounter this error.

Solving this is likely to require a complete reimagining of the solution as implemented; I wasn't able to get it to work at all, and as far as I can tell it never has.

**Comment by swirtSJW** [comment]
> Solving this is likely to require a complete reimagining of the solution as implemented; I wasn't able to get it to work at all, and as far as I can tell it never has.

I am sure this worked when it was built.   Some of the FE logic about building separate pages checks to see if the body is empty,   It never would have worked if it had to have something in the field.

**Comment by ndouglas** [comment]
This is confusing and I didn't explain it well.  IIRC this happened in the middle of the day and we were fighting to revert the upgrade so it could go out in the day's deploy.

For a demo, check out this Tubgoat instance where I upgraded `auto_entitylabel`.

https://pr9985-md2mcx3l0miycwmefh5lz1vszw4pshdg.ci.cms.va.gov/

I'm positive you understand all of this ten times as well as I do, but I'll explain my reasoning anyway.

AFAICT, and I may be subtly mistaken or flat-out ignorant, but there are two validation systems.  One is an "early-warning" FE system in JS and the other is a BE system in PHP.  Guessing the idea there is to catch some obvious mistakes in client-side before we incur the expense of a BE request and all that machinery.

For instance, required fields in the main form are caught by the FE system:

![Screenshot 2023-03-10 at 12 02 10 PM](https://user-images.githubusercontent.com/1318579/224378585-b35d284c-a8a5-48ec-b9fe-b6ea3fcaaef4.png)

But some require form submission:

![Screenshot 2023-03-10 at 12 02 44 PM](https://user-images.githubusercontent.com/1318579/224378640-466287d0-5e3f-4efb-95a1-8ada45e708fc.png)

![Screenshot 2023-03-10 at 12 08 45 PM](https://user-images.githubusercontent.com/1318579/224378913-146002c3-1ca3-47d8-8c3b-76c86db97a31.png)

The FE logic that is supposed to catch the empty field iff the Bio field is checked works AFAICT perfectly.  I didn't do anything weird to test it, mind, just a normal runthrough, but it did what it was supposed to.

The issue is this code:

```php
  /**
   * Form alterations for staff profile content type.
   *
   * @param \Drupal\core_event_dispatcher\Event\Form\FormIdAlterEvent $event
   *   The event.
   */
  public function alterstaffProfileNodeForm(FormIdAlterEvent $event): void {
    $this->addStateManagementToBioFields($event);
  }

  /**
   * Add states management to bio fields to determine visibility based on bool.
   *
   * @param \Drupal\core_event_dispatcher\Event\Form\FormIdAlterEvent $event
   *   The event.
   */
  public function addStateManagementToBioFields(FormIdAlterEvent $event) {
    $form = &$event->getForm();
    $form['#submit'][] = $this->addStateManagementToBioFieldsSubmitHandler($event);
    $form['#attached']['library'][] = 'va_gov_backend/set_body_to_required';
    $selector = ':input[name="field_complete_biography_create[value]"]';
    $form['field_intro_text']['widget'][0]['value']['#states'] = [
      'required' => [
          [$selector => ['checked' => TRUE]],
      ],
      'visible' => [
            [$selector => ['checked' => TRUE]],
      ],
    ];
    $form['field_body']['#states'] = [
      'visible' => [
          [$selector => ['checked' => TRUE]],
      ],
    ];
    $form['field_complete_biography']['#states'] = [
      'visible' => [
          [$selector => ['checked' => TRUE]],
      ],
    ];
  }

  /**
   * Submit handler removes field body req when bio toggle is set to FALSE.
   *
   * @param \Drupal\core_event_dispatcher\Event\Form\FormIdAlterEvent $event
   *   The event.
   */
  public function addStateManagementToBioFieldsSubmitHandler(FormIdAlterEvent $event) {
    $form = &$event->getForm();
    $form_state = $event->getFormState();
    $bio_display = !empty($form_state->getUserInput()['field_complete_biography_create']['value']) ? TRUE : FALSE;
    if (!$bio_display) {
      $form['field_body']['widget'][0]['#required'] = FALSE;
    }
  }

```

It just doesn't work.  And can't work.

The second line of `addStateManagementToBioFields()` is the following:

```php
    $form['#submit'][] = $this->addStateManagementToBioFieldsSubmitHandler($event);
```

So it adds a new submit handler that is _the result of evaluating_ `$this->addStateManagementToBioFieldsSubmitHandler($event);`.  Not a function pointer, not a closure returned by that method -- because the latter doesn't return _anything_, but NULL, I guess.  (Also: why am I not surprised that Drupal blithely ignores a submit handler that is null and void?)

It looks like it should work, as long as you don't look closely.  And it appears to work well enough, because if you don't have a working version of `auto_entitylabel`, and the FE validation code works as designed, then you'll never be in a situation where you can submit a staff profile with that field configuration anyway.

**Comment by swirtSJW** [comment]
Circling back to this way too late.  In looking at the code @ndouglas I think it worked because the method was called, despite being incorrectly assigned to a #submit.

```php
$form['#submit'][] = $this->addStateManagementToBioFieldsSubmitHandler($event);
```
It worked but only because this would have done the same thing.
```php
$form['#submit'][] = NULL;
$this->addStateManagementToBioFieldsSubmitHandler($event);
```
Which could have been reduced to just
```php
$this->addStateManagementToBioFieldsSubmitHandler($event);
```
The form items in the $event are being altered by reference.

**Comment by omahane** [comment]
Just as a test in a month-old demo environment, I edited https://main-1ouqufuiwhqohaqnvgjjoaidpjpensj4.demo.cms.va.gov/node/2469/edit
with JavaScript turned off.

The "First sentence" and "Body text" fields didn't hide, of course. And of those two fields, only "Body text" actually threw a validation error.

When unchecked, both fields could be empty.
