### ISSUE TITLE
Invalid date on press release teasers

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#1219]
**Describe the defect**

**To Reproduce**
1. Go to /pittsburgh-health-care/news-releases 
2. See Invalid date 

![News_releases_DRUPAL___Veterans_Affairs.jpg](https://images.zenhubusercontent.com/5d6e57ad330f64311395f08b/7f4643e1-64c3-499d-9f98-8e96e7a1a25d)

**Expected behavior**

![VA_Pittsburgh_Health_Care___News_Releases___Veterans_Affairs.jpg](https://images.zenhubusercontent.com/5d6e57ad330f64311395f08b/cff558c7-9b73-4f88-9661-91eec4de903e)

**Comment by ethanteague** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/11876
