### ISSUE TITLE
Content-Build actions failing because they don't recognize the Tugboat TLS certificate.

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-cms#12206]
## Description
Fallout from #12203.  Various GitHub actions and related activities are failing because they rely upon successful connections to Tugboat instances.  These connections cannot take place because the client application does not recognize the validity of the TLS certificate.

## Acceptance Criteria
- [ ] `content-build` components accept the Tugboat TLS certificate.
- [ ] `content-build` actions pass.

**Comment by ndouglas** [comment]
I made a naïve attempt to fix this by basically doing a find-and-replace with cert names, but it fails apparently due to availability of certificates on the AMI.

**Comment by timcosgrove** [comment]
This is complete.
