### ISSUE TITLE
Events listing pagination and sorting is broken 

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#1220]
**Describe the defect**
Events pagination is whacked

Event sorting is all over the place for this one
https://staging.va.gov/outreach-and-events/events/
it seems to be date ASC on each page, but not across all 3 pages. 

Three pages exist here, but there should only be one: 
https://staging.va.gov/pittsburgh-health-care/events/

* A past featured event shows on all pages. 
* Pages 2 and 3 are empty except for the featured event

**To Reproduce**
1. Go to above URLs and click around

**Expected behavior**

**Screenshots**
![VA_Pittsburgh_Health_Care___Events___Veterans_Affairs.jpg](https://images.zenhubusercontent.com/5d6e57ad330f64311395f08b/50a6a842-c79b-484e-82af-dd8b0e6b47d6)

**Comment by kevwalsh** [comment]
i noticed that /news-releases sorting is borked too.

**Comment by ethanteague** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/11926

**Comment by kevwalsh** [comment]
@ethanteague can you get this up on a devshop PR environment for QA?

**Comment by ElijahLynn** [comment]
I just built this in CI at http://vacms1220.demo.ci.cms.va.gov/ and the FE build is failing with:

> Step 25 start: Build Webpack assets
> Browserslist: caniuse-lite is outdated. Please run next command `yarn upgrade`
> 
> /var/aegir/projects/demo/vacms1220/docroot/vendor/va-gov/web/src/site/stages/build/webpack/index.js:43
>       if (err) throw err;
![image](https://user-images.githubusercontent.com/1504756/77020523-4d5db900-6941-11ea-9816-41ff1fd77ffc.png)

**Comment by ElijahLynn** [comment]
Actually, here are the mo betta logs:

> ERROR in ./src/platform/utilities/feature-toggles/helpers.js
> Module not found: Error: Can't resolve 'js-cookie' in '/var/aegir/projects/demo/vacms1220/docroot/vendor/va-gov/web/src/platform/utilities/feature-toggles'
>  @ ./src/platform/utilities/feature-toggles/helpers.js 1:0-32 11:20-27 12:2-9
>  @ ./src/platform/utilities/feature-toggles/flipper-client.js
>  @ ./src/platform/utilities/feature-toggles/index.jsx
>  @ ./src/platform/startup/index.js
>  @ ./src/applications/burials/burials-entry.jsx
> 
> ERROR in ./src/applications/caregivers/config/form.js
> Module not found: Error: Can't resolve 'vets-json-schema/dist/10-10CG-schema.json' in '/var/aegir/projects/demo/vacms1220/docroot/vendor/va-gov/web/src/applications/caregivers/config'
>  @ ./src/applications/caregivers/config/form.js 9:0-67 22:24-34 23:28-38 32:28-38 92:9-19 128:117-127 177:130-140 200:606-616 216:606-616
>  @ ./src/applications/caregivers/routes.jsx
>  @ ./src/applications/caregivers/app-entry.jsx
> 
> ERROR in ./src/applications/caregivers/definitions/caregiverUI.js
> Module not found: Error: Can't resolve 'vets-json-schema/dist/10-10CG-schema.json' in '/var/aegir/projects/demo/vacms1220/docroot/vendor/va-gov/web/src/applications/caregivers/definitions'

**Comment by ethanteague** [comment]
@ElijahLynn A new dependency was added to src/platform/utilities/feature-toggles/helpers.js so yarn install  step needs to be added to the build process for it to be added to node_modules  I would add, but I don't think I can add a pr to the demo environments on devshop? Anyway, we need something like
```
        "va:web:server": [
            "cd web && yarn install && yarn build"
        ],
```
in composer.json

**Comment by ElijahLynn** [comment]
Thanks, so I _thought_ the Rebuild Environment task that rebuilds these DEMO ENVs ran `yarn install` but it doesn't, only the initial ENV creation does that, which runs on `master` the first time. I am adding it now in #1276.

**Comment by ElijahLynn** [comment]
K, #1276 is done now. Here are the ENVs. 

1. http://vacms1220.web.demo.ci.cms.va.gov/ 
1. http://vacms1220.demo.ci.cms.va.gov/
1. http://devshop.cms.va.gov/hosting/c/vacms1220.demo.ci.cms.va.gov
