### ISSUE TITLE
Draft IncLim discussion guide

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#12218]
## Acceptance Criteria
- [x] Draft discussion guide based on prototype
- [x] Iterate at least once in collaboration with Jordan to better match discussion guide to prototype
- [x]  Share research plan with someone on UX team for feedback, and incorporate their feedback
- [x]  (optional) Internal review of first draft of conversation guide with Jordan/DaveP/Wes 
- [ ] Ready for Dave C review

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by cindymerrill** [comment]
Created new document and started working on it: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/income-limits-app/research/2023-01-income-limits-usability/conversation-guide.md

**Comment by cindymerrill** [comment]
Finished drafting conversation guide, and then shared it with Dave Pickett and my larger UX team (asking for someone to review it).

**Comment by cindymerrill** [comment]
Incorporated feedback from Jordan and Dave P. Waiting for feedback from @wesrowe.

**Comment by cindymerrill** [comment]
Incorporated feedback from another UX team member.

**Comment by cindymerrill** [comment]
Wes had no feedback. Now waiting for updates from Content and IA feedback on prototype, and then will share with Dave Conlon.
