### ISSUE TITLE
Spike - Update WYSIWYG with user behavior

### ISSUE THREAD

**Issue by Dottisea** [department-of-veterans-affairs/va.gov-cms#12217]
To get the work done for #10708, the WYSIWYG field for COVID-19 Status details needs to be updated, which seemed like it would be the most difficult technical piece of the work, due to the nature of CKEditor and the `<iframe>`.

**Comment by omahane** [comment]
I started this work during this sprint. There's a lot of code in this PR: #12185 . I was running into a 502 bad gateway error when visiting the VAMC Facility node:add form as a content editor. I confirmed that it wasn't happening on main, so it seemed to be related to my code. @swirtSJW thought it might have something to do with the userPerms service (possibly). I'm still investigating.

**Comment by smythe5** [comment]
@omahane can you provide an update on this ticket that I can use for sprint reporting?  I need to provide a brief statement as to why it is not done and/or what all is needed to get this complete.  Thank you.

**Comment by omahane** [comment]
Bad gateway issue is resolved.
