### ISSUE TITLE
Listing page CSS issues 

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#1221]
## 1. No events results may need a div or a clear. 

To reproduce
1. Create a listing page with no events OR or to pittsburgh-health-care/events/page-2 (as of today)
2. 

*Current behavior:*
![VA_Pittsburgh_Health_Care___Events___Veterans_Affairs.jpg](https://images.zenhubusercontent.com/5d6e57ad330f64311395f08b/bbb91250-f92e-4d32-b07b-64e73d0ed5d9)

*Expected behavior* 

## 2. Leadership intro page needs some spacing

Some padding missing between intro text and people.

![Slack___Ethan_Teague___Digital_Service___VA](https://user-images.githubusercontent.com/643678/76531159-2c7dfb00-644b-11ea-8630-021ce4d38193.jpg)

**Comment by ethanteague** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/11926
