### ISSUE TITLE
Identify CMS Cypress e2e tests for form logic

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#12220]
## Description
We need to write cypress tests for cms forms that use conditional logic. To do so, we need to identify which conditional forms do not have tests and create tickets for each.

Note: Conditional forms are cms forms that use logic to show or hide form components depending on user input.

## Acceptance Criteria
- [ ] CMS Conditional forms that do not have tests are identified in a follow up comment on this ticket
- [ ] Individual tickets are written for each identified cms conditional form

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by chri5tia** [comment]
Breaking this out into specific forms. For this sprint, identifying the forms that need tests would be a good first step.

**Comment by chri5tia** [comment]
This seemed like a good idea at the time, but I am not finding any other forms that use conditional logic. Moving forward, it would be a good idea for anyone who creates content using conditional logic to implement a cypress test for it or get ahold of me for a walk through.

**Comment by jilladams** [comment]
From Slack with Steve: 
> I suggest searching docroot/modules/custom for _form_alter  You will find a lot of conditional stuff going on in various places. You'll find some oldish ones using hooks but mostly these should all be in event subscribers now.

**Comment by chri5tia** [comment]
```
🐾 va.gov-cms: cd docroot/modules/custom                         
🐾 custom: grep -rnw . -e 'form.alter'                           
./va_gov_consumers/va_gov_consumers.module:19:    case 'form_alter':
./va_gov_backend/va_gov_backend.module:1134: * Redirect form alter submit handler to store redirect Match Type.
./va_gov_backend/src/EventSubscriber/EntityEventSubscriber.php:503:   * Widget form alter Event call.
./va_gov_backend/src/EventSubscriber/ThemeEventSubscriber.php:32:   * Widget form alter Event call.
🐾 custom: grep -rnw . -e 'form_alter'                           
./va_gov_consumers/va_gov_consumers.module:19:    case 'form_alter':
```

**Comment by chri5tia** [comment]
Quick anatomy of node form conditional logic implementations, in two flavors.
Both methods use [The Hook Event Dispatcher module](https://www.drupal.org/project/hook_event_dispatcher)

1. Javascript
- Custom module declares the script in its `libraries.yml` file:
Such as a script `customModuleFormHelpers.js` in the `js` directory:

```
custom_module_form_states_helpers:
  js:
    js/customModuleFormHelpers.js: {}
```

- Library is then referenced in the `src/va_gov_custom_module/EventSubscriber/EntityEventSubscriber.php` file, such as:

```
  public function addDisplayManagementToEventFields(array &$form) {
    $form['#attached']['library'][] = 'va_gov_events/custom_module_form_states_helpers';
  }
```

2: PHP 
- Dependency declared in custom module's `.info` file, though I don't see it so I want to learn about why
- Class declared in public static function in `src/va_gov_custom_module/EventSubscriber/EntityEventSubscriber.php`. 
- This can alternatively be named in it's own file as something like `EventSubScriber/NameOfClassEventSubscriber.php`, but I don't think we do that on this project

```
  public function alterNameOfClassFormAlter(FormIdAlterEvent $event): void {
    ...instructions...
  }
```

- The function describes the alterations and is then referenced at the end of the file with a public static function `getSubscribedEvents`

```
- public static function getSubscribedEvents`(): array {`
    return [
      ...snip other stuff...
      FormHookEvents::FORM_ALTER => 'formAlter',
      'hook_event_dispatcher.form_node_name_of_form.alter' => 'alterNameOfClassFormAlter',
```

**Comment by chri5tia** [comment]
Knowing this, we can now make a list of which custom modules use the hook event dispatcher to alter a node add or edit form (lists public functions defined in `EntityEventSubscriber.php` by public function. 

If I search the custom modules for any entity event subscriber that does a form alter:

```
va.gov-cms: grep -rl docroot/modules/custom/ -e 'FORM_ALTER' |grep EntityEventSubscriber              
docroot/modules/custom//va_gov_backend/src/EventSubscriber/EntityEventSubscriber.php
docroot/modules/custom//va_gov_vet_center/src/EventSubscriber/EntityEventSubscriber.php
```

Hm, let's search the custom modules code for `form.alter` and in theory, we can get a base list to drill down:

```
va.gov-cms: grep -rl docroot/modules/custom/ -e 'form.alter' |grep EntityEventSubscriber              
docroot/modules/custom//va_gov_workflow/src/EventSubscriber/EntityEventSubscriber.php
docroot/modules/custom//va_gov_banner/src/EventSubscriber/EntityEventSubscriber.php
docroot/modules/custom//va_gov_events/src/EventSubscriber/EntityEventSubscriber.php
docroot/modules/custom//va_gov_workflow_assignments/src/EventSubscriber/EntityEventSubscriber.php
docroot/modules/custom//va_gov_backend/src/EventSubscriber/EntityEventSubscriber.php
docroot/modules/custom//va_gov_vamc/src/EventSubscriber/EntityEventSubscriber.php
docroot/modules/custom//va_gov_vet_center/src/EventSubscriber/EntityEventSubscriber.php
```

Turning that into some bites and notes:

- [x] Backend
Conditional form logic: none
Pre-conditional form alters:
- alterStaffProfileNodeForm
- alterCentralizedContentNodeForm
- alterVetCenterNodeForm
- alterRegionalHealthServiceNodeForm

- [x] Banner
Non-conditional form alters

- [x] Events
- alterEventNodeForm: Tests already written

- [x] VAMC
Conditional form alters: None
Non-conditional form alters:
- alterFullWidthBannerNodeForm: Sets menu title
- alterRegionalHealthCareServiceDesNodeForm: limit's VAMCS to workbench
- alterTopTaskNodeForm: Sets menu title
- alterFacilityNodeForm: Adds covid term text

- [x] Vet Center
Non-conditional form alters:
- alterVetCenterLocationsListNodeForm: Limits vet service selections
- alterVetCenterMvcNodeForm: Limits vet service selections
- alterVetCenterOutstationNodeForm:  Limits vet service selections
- alterVetCenterNodeForm: Organizes stuff

- [x] Workflows
None: Some stuff added by dependabot but no actual form alters that I can see.

- [x] Workflow Assignments
Non-conditional:
- alterAlertBlocksEditForm: Adds alert block treatment script
- alterAlertBlocksForm: Adds alert block treatment script
