### ISSUE TITLE
Update help email to include additional questions 

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#1223]
## User Story or Problem Statement

As a CMS user clicking the help button, the generated email has a template with a few questions or instructions 
Text: [WIP draft here](https://docs.google.com/document/d/19637dTqkfMBeOkVQ5hvsR4dn4OL-hgY0yPe_iRaLx3E/edit#)

Includes e-mailer link for template

## Acceptance Criteria
- [ ] When i click on Help, an email is generated that has a body full of questions based on the slack workflow 
- [ ] Dave Conlon is kept in the loop.

**Comment by rachel-kauff** [comment]
@kevwalsh The template text and e-mailer link is ready. Not sure who to pass this off to for implementation.
