### ISSUE TITLE
FE: Continue Lovell refactor to include name change.

### ISSUE THREAD

**Issue by ryguyk** [department-of-veterans-affairs/va.gov-cms#12236]
## Description
See https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12092
See https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12013

Lovell refactor needs to be continued to include the name change.

## Acceptance Criteria
- [ ] In-process refactor is complete.
- [ ] Refactor is updated to include the Lovell name change.
- [ ] Name-change refactor moves hard-coded name to a reusable constant.
- [ ] Existing Lovell tests pass.

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by maxx1128** [comment]
Marking this as closed since both related tickets have been completed.
