### ISSUE TITLE
Communicate name change to Sitewide Content

### ISSUE THREAD

**Issue by ryguyk** [department-of-veterans-affairs/va.gov-cms#12237]
## Description
As a Facilities team member, I need to know that the Sitewide Content Team has been informed of the official name change of the Lovell Health Systems before we implement the name change.
**from:** 
Lovell Federal VA health care
Lovell Federal and Tricare health care,
**to:** 
Lovell Federal health care - VA
Lovell Federal health care - Tricare

See #12092 for decision record

## Acceptance Criteria
- [x] Sitewide Content Team has been informed of the name change

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by Dottisea** [comment]
Send communication to Beth Potts re: name change via slack channel https://dsva.slack.com/archives/C01K37HRUAH on 1/19/23

**Comment by bethpottsVADEPO** [comment]
Just tracking in this ticket a slack note from @mnorthuis:

Have the Lovell facility pages launched, and if so, can you provide links to those?   With a name change, I believe you will also need to do a redirect, which for facility sites I believe is just handled by your team.  We would just like to look at how these changes might impact headings and URLs in the VAMC structure, so links to the live sites are needed.

**Comment by Dottisea** [comment]
Responded/commented to the slack message mentioned above -  directed to Mikki Northuis and Beth Potts:

The pages have not launched yet and there are no links to share - we will be feature complete at the end of this month, and will need to rely on the editors to populate their pages before content complete launch. Please let me know if this is what you are looking for and any next steps. Thanks!

**Comment by Dottisea** [comment]
Ryan Koch
  [30 minutes ago](https://dsva.slack.com/archives/C01K37HRUAH/p1674683422258509?thread_ts=1674139509.683289&cid=C01K37HRUAH)
[@Mikki Northuis](https://dsva.slack.com/team/U1W46RJKA)
 Thanks for the info here. I'm an engineer on Dotti's team. I'm jumping in to try to help get you the information you need.
First, it should be noted that the pages in question are not yet published. We should not need to worry about redirects, but, if we would, that is something we are familiar and comfortable with.
To get any sort of preview of these pages, we'd need to build them in a demo environment/Tugboat instance. That brings up two questions:
Are you familiar with our Tugboat instances? Do you know if you have access?
Is a Tugboat instance sufficient for what you would need to review? It seems to me that it should be sufficient given what you mention
We would just like to look at how these changes might impact headings and URLs in the VAMC structure
(edited)
 
Mikki Northuis
:heads-down:  [3 minutes ago](https://dsva.slack.com/archives/C01K37HRUAH/p1674684998026499?thread_ts=1674139509.683289&cid=C01K37HRUAH)
Thanks for the info, no need for me to get into Tugboat, wasn't sure if there was a drupal preview of the main health system page or not.  I don't foresee any issues with these names for the main landing pages, and given the pages are not live yet, I don't think there is anything you need from us to move forward.  Carry on!
