### ISSUE TITLE
Redirect Request: vanity URL, no hard timing

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-cms#12245]
### Instructions
- Requests must be submitted **AT LEAST** 2 weeks in advance.  Some requests take a significant amount of time and coordination to implement, so start the process as soon as you know you will need one. 
- This issue will be used from initial request through implementation to ensure all individuals working on this are notified of status updates.  Please do not create multiple issues to track differnt steps.
- It is your responsibility to notify VA stakeholders as appropriate.  

### Type of request
- [ ] We are retiring or taking down a page and need to redirect the URL (complete redirect section)
- [ ] We are changing the URL of an existing page (complete redirect section)
- [x] We need a custom vanity URL (complete vanity URL section)

### Implementation date
When does this request need to be live?
Choose one:
- [ ] On a specific date, connected to a program or publishing requirement. **DATE:**
- [ ] Any day prior to a deadline/latest possible date. **DEADLINE:** 
- [ ] Any day after an earliest possible date. **EARLIEST DATE:** 
- [ ] During a specific date range: ***EARLIEST DATE TO LATEST DATE:***
- [x] No hard timing requirements, publish when possible. We let the team know that it generally takes 2 weeks so should be able to implement by 1/26/23

### Redirects 
Current URL  |  Redirect Destination or New URL
---  |  ---
current URL | new URL

### Vanity URLs 
Vanity URL  |  Landing page
---  |  ---
va.gov/find-rep | https://www.va.gov/disability/get-help-filing-claim/

**Link to campaign landing page request issue:**

### Process, Roles and Responsibilities
- [ ] Requesting team: Above information is provided
- [ ] Requesting team: All appropriate VA stakeholders are notified as appropriate
- [x] IA: Request is vetted and documented and implementation plan is clear 
- [x] IA: Request is assigned to appropriate team for implementation 
- [ ] Implementation team: Work is complete
- [ ] Implementation team: Validated in production
- [ ] Requesting team: Validates everything is correct in production and closes ticket

**Comment by RLHecht** [comment]
@jilladams Just confirming that this will go live tomorrow. The team was coordinating their press release with the timing of this.

**Comment by jilladams** [comment]
Thanks - this PR will merge today, and we'll need to get an OOB deploy done today to have the URL live for tomorrow. I'll confirm here as soon as that's done.

**Comment by jilladams** [comment]
PR merged, deploy requested: https://dsva.slack.com/archives/CBU0KDSB1/p1674674308533599

**Comment by jilladams** [comment]
Redirect is live in Prod! @RLHecht closing, but pls reopen with any concerns.
