### ISSUE TITLE
Upgrade to Drupal 9.5

### ISSUE THREAD

**Issue by EWashb** [department-of-veterans-affairs/va.gov-cms#12250]
## Description
Upgrade Drupal to version 9.5 in preparation for the upgrade to Drupal 10. 

## Acceptance Criteria
- [ ] Upgrade `drupal/core-recommended` to `~9.5.0`
- [ ] Upgrade `drupal/core-composer-scaffold` to `~9.5.0`

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [x] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by laflannery** [comment]
Issues:
- CSS Changes: Elements are no longer using variables, examples
  - Heading is bigger
  - Button is bluer
  - Font is incorrect
(9.5 is on the left)
![image](https://user-images.githubusercontent.com/106678594/213554181-720db57c-c02b-46db-9e98-5fa22d41049d.png)
- Probably related to CSS issues above but just in case it's not - all the "buttons" are not styled:
![image](https://user-images.githubusercontent.com/106678594/213554916-f714017c-9a61-4b40-a2a0-d9c6e3cc0e3c.png)
![image](https://user-images.githubusercontent.com/106678594/213555851-d8241857-9319-4481-9d2c-9905795fb785.png)
- (I think this is also CSS) I am missing the caret to indicate that the warnings/alerts are expandable:
![image](https://user-images.githubusercontent.com/106678594/213556383-ac549d71-68b7-4161-8a32-6218d0bce44f.png)

**Comment by edmund-dunn** [comment]
The issues that @laflannery found have been fixed.
