### ISSUE TITLE
Create Tugboat instance with Drupal 10

### ISSUE THREAD

**Issue by EWashb** [department-of-veterans-affairs/va.gov-cms#12252]
## Description
Set up a tugboat with Drupal 10 on it to support discovery. 

## Acceptance Criteria
- [x] Create a branch for Drupal 10 upgrade.
- [ ] Get it working at MVP.
- [ ] Create tugboat instance. 

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [x] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by EWashb** [comment]
@edmund-dunn you're still expecting to get to this during sprint 76? If so I want to move it into the to-do pipeline

**Comment by EWashb** [comment]
There are dependencies found that will delay this being done. We need to work through those first. I'm going to remove the sprint label and add it to the blocked column

**Comment by edmund-dunn** [comment]
Removing:
```
"1091852 - Display Bug when using #states (Forms API) with Ajax Request": "https://www.drupal.org/files/issues/2023-01-17/1091852.patch",
```

**Comment by edmund-dunn** [comment]
Removed because Seven ws deprecated: 
```
                "2930508 - Seven inactive tabs do not meet WCAG AA 1.4.3 for contrast": "https://www.drupal.org/files/issues/2020-10-15/drupal-seven_inactive_tabs_do_not_meet_wcag_aa-2930508-36.patch",
```

**Comment by edmund-dunn** [comment]
New patch: https://www.drupal.org/project/entity_diff_ui/issues/3315629#comment-14899010

**Comment by edmund-dunn** [comment]
@EWashb Drupal 10 is live on https://vacms-12252-drupal-10-cne7edu0najqzzmwjbq3awbbjcxb40w3.ci.cms.va.gov
