### ISSUE TITLE
Iteration on Helpdesk infrastructure

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#1225]
### User Story or Problem Statement

Our current help desk infrastructure
* is not scaleable 
* doesn't collect the right information
* doesn't have a searchable data store for help requests
* doesn't triage into tiers very well. 

We want to start improving the help desk infrastructure to scale so we can provide the best possible support.

### Steps. 

**Sprint 15:** 

1. Eval and select a software tool

**Sprint 16**
1. Establish helpdesk workflow, processes, and procedures
2. Implement software tooling

**Sprint 17 & Beyond** 
1. Build help request interface into CMS Durpal site
2. Institute chat bot feature

### Affected users and stakeholders

* All CMS users

**Comment by joshworkscivicactions** [comment]
Created working document to build Help Desk Manager role requirements from an application usage perspective.  Moving to Github after completion https://docs.google.com/document/d/1ZGO_C7-wqpWGPujMoMQAoGgvFSQjP-vqY3ShLIG-4B0/edit?usp=sharing

**Comment by stefaniefgray** [comment]
Closing because our Helpdesk infrastructure has been working beautifully within JSD (Jira Service Desk)
