### ISSUE TITLE
Training request form

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#1227]
### User Story or Problem Statement

As a CMS user, I want access to the CMS and the training needed to use it.

- [x] Draft process flow (see https://app.mural.co/t/vagov6717/m/vagov6717/1605735264080/64a23a4e0bcff45cafebd576db9a787d54127dbc)
- [ ] Peer review
- [ ] PO review
- [ ] Build form(s)
- [ ] Peer review
- [ ] PO review
- [ ] Implement

**Comment by xiongjaneg** [comment]
Training request is built into the user account provisioning workflow which is documented in [#3128.](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/3128)

 Ad hoc requests will come through help desk and be put into above process.

**Comment by oksana-c** [comment]
This is a parent epic for standing up a training request form - currently not prioritized since we do have a process that works ATM - per Jane's comment above.

This epic needs a spike and issues should be broken down more granularly to achieve desired outcomes (TBD after a spike).

**Comment by xiongjaneg** [comment]
closing, currently training isn't upon request but through collaboration with POs and product teams
