### ISSUE TITLE
Audit current state of the CMS documentation in Github

### ISSUE THREAD

**Issue by EWashb** [department-of-veterans-affairs/va.gov-cms#12280]
## Background

As the CMS teams combine, we need to determine what documentation currently lives in Github so that we might make the appropriate updates. We have documentation in [Github](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/cms) that is over two years old that needs to be updated for the current state of the team and product. As we move to a more unified CMS team, it is imperative that our documentation is easier to use and reflects the decisions, processes, and abilities of the Drupal CMS team.

The initial work that moved our documentation to the platform site is tracked in this issue #5295 

## Assumptions

- The current Github documentation does not reflect the current state of how we work as a CMS team.
- There is duplicative information listed in the Github documentation.
- There is little to no information architecture in the current documentation, and it is unclear how to find the information you need.

## Definition of Done

An audit is completed that gives the CMS team an idea of the deficiencies of the current Github documentation. The auditor should also recommend improvements by way of deleting, updating, or adding information to make the process of using the documentation as easy as possible. 

## Acceptance Criteria

- [x] An audit is completed on the current state of the CMS documentation in the va.gov-team repo
- [x] Current documentation structures are documented in a google sheet or within this ticket. 
- [x] Areas of improvement are noted to share with PM

**Comment by laflannery** [comment]
[High level audit](https://docs.google.com/spreadsheets/d/1hT9b1ySVdHCBJrsvqfMlj5Ig7EuEiviIYRtrssHQatk/edit#gid=0)

**Comment by EWashb** [comment]
Next steps: Erika to create tickets based on the high-level audit. These tickets will include what to archive, what to update, and what to delete (? not sure if that's something we actually do, but will confirm with PO)
