### ISSUE TITLE
Redirect Request for Vet Centers published week of 1/9/23

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-cms#12288]
### Instructions
- Requests must be submitted **AT LEAST** 2 weeks in advance.  Some requests take a significant amount of time and coordination to implement, so start the process as soon as you know you will need one. 
- This issue will be used from initial request through implementation to ensure all individuals working on this are notified of status updates.  Please do not create multiple issues to track differnt steps.
- It is your responsibility to notify VA stakeholders as appropriate.  

### Type of request
- [ ] We are retiring or taking down a page and need to redirect the URL (complete redirect section)
- [ ] We are changing the URL of an existing page (complete redirect section)
- [ ] We need a custom vanity URL (complete vanity URL section)

### Implementation date
When does this request need to be live?
Choose one:
- [ ] On a specific date, connected to a program or publishing requirement. **DATE:**
- [ ] Any day prior to a deadline/latest possible date. **DEADLINE:** 
- [ ] Any day after an earliest possible date. **EARLIEST DATE:**
- [ ] During a specific date range: ***EARLIEST DATE TO LATEST DATE:***
- [x] No hard timing requirements, publish when possible.

### Redirects 
Current URL  |  Redirect Destination or New URL
---  |  ---
www.va.gov/find-locations/facility/vc_0822MVC | https://www.va.gov/springfield-il-vet-center/
www.va.gov/find-locations/facility/vc_0421V | https://www.va.gov/springfield-il-vet-center/
https://www.va.gov/directory/guide/facility.asp?ID=647&dnum=All | https://www.va.gov/springfield-il-vet-center/
https://www.va.gov/directory/guide/keystaff.cfm?id=647 | https://www.va.gov/springfield-il-vet-center/
www.va.gov/find-locations/facility/vc_0852MVC | https://www.va.gov/indianapolis-vet-center/
www.va.gov/find-locations/facility/vc_0413V | https://www.va.gov/indianapolis-vet-center/
https://www.va.gov/directory/guide/facility.asp?ID=439&dnum=All | https://www.va.gov/indianapolis-vet-center/
https://www.va.gov/directory/guide/keystaff.cfm?id=439 | https://www.va.gov/indianapolis-vet-center/
www.va.gov/find-locations/facility/vc_0820MVC | https://www.va.gov/fargo-vet-center/
www.va.gov/find-locations/facility/vc_0406V | https://www.va.gov/fargo-vet-center/
https://www.va.gov/directory/guide/facility.asp?ID=5132&dnum=All | https://www.va.gov/fargo-vet-center/
https://www.va.gov/directory/guide/keystaff.cfm?id=5132 | https://www.va.gov/fargo-vet-center/
www.va.gov/find-locations/facility/vc_0340V | https://www.va.gov/lakeland-vet-center/
https://www.va.gov/directory/guide/facility.asp?ID=6360&dnum=All | https://www.va.gov/lakeland-vet-center/
https://www.va.gov/directory/guide/keystaff.cfm?id=6360 | https://www.va.gov/lakeland-vet-center/
www.va.gov/find-locations/facility/vc_0433V | https://www.va.gov/saginaw-vet-center/
https://www.va.gov/directory/guide/facility.asp?ID=6219&dnum=All | https://www.va.gov/saginaw-vet-center/
https://www.va.gov/directory/guide/keystaff.cfm?id=6219 | https://www.va.gov/saginaw-vet-center/
www.va.gov/find-locations/facility/vc_0422V | https://www.va.gov/metro-east-vet-center/
https://www.va.gov/directory/guide/facility.asp?ID=643&dnum=All | https://www.va.gov/metro-east-vet-center/
https://www.va.gov/directory/guide/keystaff.cfm?id=643 | https://www.va.gov/metro-east-vet-center/

### Vanity URLs 
Vanity URL  |  Landing page
---  |  ---
requested URL | landing page URL

**Link to campaign landing page request issue:**

### Process, Roles and Responsibilities
- [ ] Requesting team: Above information is provided
- [ ] Requesting team: All appropriate VA stakeholders are notified as appropriate
- [ ] IA: Request is vetted and documented and implementation plan is clear 
- [ ] IA: Request is assigned to appropriate team for implementation 
- [ ] Implementation team: Work is complete
- [ ] Implementation team: Validated in production
- [ ] Requesting team: Validates everything is correct in production and closes ticket

**Comment by dsasser** [comment]
PR for review: https://github.com/department-of-veterans-affairs/devops/pull/12534 (contains both #12407 and #12288 redirects.

**Comment by dsasser** [comment]
Done but waiting for the weekly Wednesday deploy (02/15/2023) to verify.

**Comment by dsasser** [comment]
Tested the redirects today and received the following:

```bash
✅ Correct redirect from  https://www.va.gov/find-locations/facility/vc_0822MVC to https://www.va.gov/springfield-il-vet-center/
✅ Correct redirect from  https://www.va.gov/find-locations/facility/vc_0421V to https://www.va.gov/springfield-il-vet-center/
❌ Incorrect redirect from  https://www.va.gov/directory/guide/facility.asp?ID=647&dnum=All to https://www.va.gov/find-locations/?facilityType=vet_center
❌ Missing redirect from  https://www.va.gov/directory/guide/keystaff.cfm?id=647 to https://www.va.gov/springfield-il-vet-center/
✅ Correct redirect from  https://www.va.gov/find-locations/facility/vc_0852MVC to https://www.va.gov/indianapolis-vet-center/
✅ Correct redirect from  https://www.va.gov/find-locations/facility/vc_0413V to https://www.va.gov/indianapolis-vet-center/
❌ Incorrect redirect from  https://www.va.gov/directory/guide/facility.asp?ID=439&dnum=All to https://www.va.gov/find-locations/?facilityType=vet_center
❌ Missing redirect from  https://www.va.gov/directory/guide/keystaff.cfm?id=439 to https://www.va.gov/indianapolis-vet-center/
✅ Correct redirect from  https://www.va.gov/find-locations/facility/vc_0820MVC to https://www.va.gov/fargo-vet-center/
✅ Correct redirect from  https://www.va.gov/find-locations/facility/vc_0406V to https://www.va.gov/fargo-vet-center/
❌ Incorrect redirect from  https://www.va.gov/directory/guide/facility.asp?ID=5132&dnum=All to https://www.va.gov/find-locations/?facilityType=vet_center
❌ Missing redirect from  https://www.va.gov/directory/guide/keystaff.cfm?id=5132 to https://www.va.gov/fargo-vet-center/
✅ Correct redirect from  https://www.va.gov/find-locations/facility/vc_0340V to https://www.va.gov/lakeland-vet-center/
❌ Incorrect redirect from  https://www.va.gov/directory/guide/facility.asp?ID=6360&dnum=All to https://www.va.gov/find-locations/?facilityType=vet_center
❌ Missing redirect from  https://www.va.gov/directory/guide/keystaff.cfm?id=6360 to https://www.va.gov/lakeland-vet-center/
✅ Correct redirect from  https://www.va.gov/find-locations/facility/vc_0433V to https://www.va.gov/saginaw-vet-center/
❌ Incorrect redirect from  https://www.va.gov/directory/guide/facility.asp?ID=6219&dnum=All to https://www.va.gov/find-locations/?facilityType=vet_center
❌ Missing redirect from  https://www.va.gov/directory/guide/keystaff.cfm?id=6219 to https://www.va.gov/saginaw-vet-center/
✅ Correct redirect from  https://www.va.gov/find-locations/facility/vc_0422V to https://www.va.gov/metro-east-vet-center/
❌ Incorrect redirect from  https://www.va.gov/directory/guide/facility.asp?ID=643&dnum=All to https://www.va.gov/find-locations/?facilityType=vet_center
❌ Missing redirect from  https://www.va.gov/directory/guide/keystaff.cfm?id=643 to https://www.va.gov/metro-east-vet-center/
```

This indicates that the redirects which include query string parameters are not worked as expected. Some of them are incorrectly redirecting to https://www.va.gov/find-locations/?facilityType=vet_center while others are missing a redirect entirely.

**Comment by jilladams** [comment]
Looking at previous redirects for insight -- e.g. https://github.com/department-of-veterans-affairs/devops/pull/12453/files for #11246

It looks like the /facility and /keystaff entries are typically made in the code blocks that start on [1151](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/revproxy-vagov/vars/redirects.yml#L1151) and [2055](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/revproxy-vagov/vars/redirects.yml#L2055) respectively.  I don't have all of the background for why that's so, but I know that doing so has allowed redirects like the one in this ticket to work correctly in the past. @dsasser are you willing to rework that portion of the code you previously added, to integrate in those 2 spots? When that's done, we can ask Plat for a deploy to Dev to verify if that worked. 

If so - could I ask for one typo fix at the same time? Line [2942](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/revproxy-vagov/vars/redirects.yml#L2942) should be `oskaloosa` not `okaloosa`.

**Comment by RLHecht** [comment]
Just chiming in here that Okaloosa should stay spelled that way: https://www.va.gov/okaloosa-county-vet-center/

**Comment by jilladams** [comment]
Ah! You're right, sorry - good catch, Randi. The actual change we need is: 

s / okaloosa-vet-center / okaloosa-county-vet-center/. (Add -county, which is currently missing on Line [2942](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/revproxy-vagov/vars/redirects.yml#L2942) )

**Comment by dsasser** [comment]
> s / okaloosa-vet-center / okaloosa-county-vet-center/. (Add -county, which is currently missing on Line [2942](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/revproxy-vagov/vars/redirects.yml#L2942) )

Looks like someone already got to this. The latest redirect reads:
```
      - param_name: "id"
        param_value: ^6139$
        dest: /okaloosa-county-vet-center/
```

**Comment by dsasser** [comment]
PR for [these issues](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12288#issuecomment-1435088161) is here: https://github.com/department-of-veterans-affairs/devops/pull/12579

**Comment by jilladams** [comment]
Verified! Closing.
