### ISSUE TITLE
Update fallback behavior if no Benefit Promo is set in the entityqueue to display veteran images

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#12292]
## Background
The [2022 homepage refresh designs](https://www.sketch.com/s/3aa40506-4be2-46cc-876b-93f1a9f3a857/p/EAD305BC-3082-4F81-ADEC-C2486F7B6BEF/canvas) include 2 treatments for the top of the homepage: 
1. Features a Benefit Promo Block at page top (e.g. "The PACT Act and your VA benefits")
2. A fall-back treatment, displaying veteran images, if no Benefit Promo is present

**When a Benefit Promo vs. fallback treatment will display**
Benefit promo blocks are Drupal content. They get published to the homepage using the V2 Home page benefit promo entityqueue: https://prod.cms.va.gov/admin/structure/entityqueue/home_page_hero/home_page_hero?destination=/admin/structure/entityqueue

Homepage Manager editors have the power to add / remove promos. In the event that a benefit promo is removed, and a new one is not added, the original design intent was to display the veteran images treatment in that case. 

**Reality**
In V1 prototype build of the homepage, we built the V1 treatment of veteran images: https://www.sketch.com/s/3aa40506-4be2-46cc-876b-93f1a9f3a857/a/v8Ag388

In V2 prototype build, we built the Benefit Promo, and hooked it up to Drupal. 

Now we need to update the state of the veteran image treatment: 
1. Does it still exist in code? If not, restore it.
2. Does it match the V3 final treatment?  https://www.sketch.com/s/3aa40506-4be2-46cc-876b-93f1a9f3a857/p/2469A44A-7547-4801-BC97-B70864FBD231/canvas – "Round 4" tab
   * If not, we need to update the FE code to bring it into alignment with V3 designs, especially including using the newly specified Design System and UWSDS (?) background colors 
3. Veteran images should display by default if no Benefit promo is published to the proper entityqueue. This may require working with a CMS / Drupal engineer, to get a local or Tugboat instance configured correctly in order to test.
   * If not, we need to ticket the logic to make it so. (Could be added into a ticket created for #2, if needed)

Comp of final treatment:
<img width="405" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/4054752/a85b976d-3cc7-41ba-916c-272b9917a4c1">

Comp of final treatment (authenticated experience, per DaveC):
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/19175324/11626c8a-5135-4a91-b46b-5365a2d9190c)
Slack thread for context: https://dsva.slack.com/archives/C52CL1PKQ/p1686241696344489?thread_ts=1683140159.579789&cid=C52CL1PKQ

### Accessibility

Preserve a11y features present on promo block version:
- [ ] Add "Welcome to VA.gov" H1 header to Veteran portrait implementation
- [ ] Ensure H1 is announced and receives focus

## Acceptance criteria
- [x] Found old code for this component, which probably includes portrait randomizer
- [x] When no V2 Home page benefit promo block is published to the entityqueue, veteran images should display on the homepage, as per [V3 final design treatment](https://www.sketch.com/s/3aa40506-4be2-46cc-876b-93f1a9f3a857/a/WKW7xVA) – "Round 4" tab
- [x] 3 veterans shown are randomly chosen when page loads
- [x] Consider the visual/"snapshot" idea for e2e testing in #8879
- [x] Images have a null `alt` attribute (`alt=""`) because they are decorative
- [x] Ensured test coverage:
  - [x] This version shows when no benefit promo is published
  - [x] Veteran randomization code (if appropriate)
- [ ] Design review required

**A11y ACs** 
Laura to confirm the following function as expected:
- [ ] Homepage levels are logically ordered, starting with a single h1 - i.e., "Access and manage..." is an H2
- [ ] When a Veteran uses a mobile screenreader and swipes to browse to a heading, the heading identifies itself as a heading and the purpose and level are clear. 
   - (Randi) **Adding a note here**: This can only be demoed and seen locally until/unless we remove the PACT Act benefit promo banner from production. We cannot verify this on mobile at this time. 
- [ ] When a Veteran uses a desktop screenreader (NVDA, JAWS, VoiceOver) Aand uses the arrow key to browse to a heading, 
the heading it identifies itself as a heading and the purpose and level are clear. 
- [ ] When a Veteran uses the arrow key to browse to a heading, the heading comes into view.
- [ ] Once signed off, https://github.com/department-of-veterans-affairs/va.gov-team/issues/43898 is closed.

**Comment by jilladams** [comment]
@wesrowe we just observed that the Create Account block _also_ has an alternate treatment when veteran images appear, that wasn't factored into building that block as Drupal content. We need to re-refine this with that in mind.

**Comment by jilladams** [comment]
Noting: as a short stop, Wes agreed that we could say: build it hard coded and convert to Drupal later as needed. (Meaning: just don't show the Create Account drupal block we made for the standard treatment.) To clarify in planning and if so: this is a good Randi starter ticket.

**Comment by jilladams** [comment]
From planning: the left side treatment of "create account" with Veteran images here is not correct per DaveC. Punting til after Dave's PTO, and we'll need to regroup with @rtwell to work out what the treatment should look for the fall back treatment. ([sketch](https://www.sketch.com/s/3aa40506-4be2-46cc-876b-93f1a9f3a857/p/EAD305BC-3082-4F81-ADEC-C2486F7B6BEF/canvas))

**Comment by wesrowe** [comment]
Merged in ACs from a11y-oriented #10899 (and will close that as a dupe).

**Comment by wesrowe** [comment]
I added a link to #8879 in the ACs – that ticket has an idea for visual/"snapshot" e2e testing that I think made sense to the team at some point.

**Comment by jilladams** [comment]
Got confirmation in Slack: https://dsva.slack.com/archives/C52CL1PKQ/p1686239827957509?thread_ts=1683140159.579789&cid=C52CL1PKQ

* Round 4 version here is final: https://www.sketch.com/s/3aa40506-4be2-46cc-876b-93f1a9f3a857/p/2469A44A-7547-4801-BC97-B70864FBD231/canvas
    * The content is the same as Promo version, but styled differently.
    * The behavior is the same in the unauthenticated experience. Meaning the H2 "Access and manage...", "Learn how" text and link, "Create account" button all go away.
    * The photos of the Veterans are decorative per Laura and should have a alt="". That can be hard-coded.
* Authed version: 

![image (20)](https://github.com/department-of-veterans-affairs/va.gov-team/assets/85581471/f7e7580e-58f1-4c63-8003-0e230fbe2055)
* Per DaveC in slack: 
    * Yes we know it looks weird
    * We dont know how many people are returning to the homepage in the Auth state, so we'll want to check analytics on that.
    * Yes Dave already has ideas about how we might use that empty space if, in fact, this is a problem to be solved b/c  the data supports that Auth users care about the homepage after they signed in.

**Comment by jilladams** [comment]
@randimays saw you edited ticket body, thank you. - I just made one add'l AC re: Closing https://github.com/department-of-veterans-affairs/va.gov-team/issues/43898 when this is all said and done, which was an early Platform Collab Cycle ticket for a11y around the empty `alt=""` on the images.

**Comment by jilladams** [comment]
Noting re: ACs that we got a firm request from DaveC to rotate images on page load, vs. daily: https://dsva.slack.com/archives/C52CL1PKQ/p1686602323654379?thread_ts=1683140159.579789&cid=C52CL1PKQ

Discussed launch plans with Randi: 
* We can't stage this in Staging, bc it requires unpublishing Prod benefit promo content in the Prod DB in order to get that mirrored to Staging. No can do.
* We can't stage it in Tugboat, bc it requires changes in both content-build and in vets-website. So: 
* We can't  merge content-build, then preview vets-website changes in a Review Instance, because: Review Instances have no CMS (per [environments.md](https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/READMES/environments.md)). They use the latest every 15min snapshot of Prod data. So you can't modify the promo to remove it on a Review Instance.
* We _can_ demo locally. 

For the local test: 
* Mimic the CMS db with the promo banner unpublished. (Using Staging db, between prod mirrors, Randi has this worked out with Daniel already.)
* Test: remove promo, veteran images appear. 
* Restore the promo, veteran images disappear.
* Verify mobile treatment

FYI @wesrowe

**Comment by randimays** [comment]
Added several messages into the ongoing Slack thread: https://dsva.slack.com/archives/C52CL1PKQ/p1686755256026309?thread_ts=1683140159.579789&cid=C52CL1PKQ regarding needing more design comps for this banner treatment. We need a mobile comp of the authenticated experience and some midpoint (tablet-ish) comps to give some guidance for the sizing of the veteran photos.

**Comment by jilladams** [comment]
Chatted with Randi & filled in the new info re: RyanT's availability (working for a team other than Sitewide). We've summarized open questions, and can probably find a path forward shy of comps with his input, or can pull Jordan in for decisions if he flags that's best. Next steps are in the same slack thread.

**Comment by jilladams** [comment]
For the histories: decisions on mobile breaks from slack:

- tablets = shrink veteran images to 3, 2, 1 as screen gets narrower
- Mobile unauthed = when we drop the last veteran image, let text go full width, center the button
- Mobile authed = yes, just show Welcome to [Va.gov](http://va.gov/) banner

**Comment by jilladams** [comment]
https://www.loom.com/share/d76d5e30f0fd4c0582b8668a9c3b65b3 <-- nice work, @randimays

**Comment by randimays** [comment]
Thread for discussion & approval requests: https://dsva.slack.com/archives/C52CL1PKQ/p1686945812881089

**Comment by randimays** [comment]
Validated the correct behavior in staging as there is a Benefit Promo assigned:

<img width="1200" alt="Screenshot 2023-06-20 at 2 17 37 PM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/19175324/fcacd7c7-a696-4f49-928c-e87483440798">

**Comment by jilladams** [comment]
The work has all been deployed to prod, according to the FE dashboard. Promo still appears correctly in prod. We can't otherwise validate in prod without unpublishing the promo. Closing!

**Comment by randimays** [comment]
Loom walkthrough: https://www.loom.com/share/d76d5e30f0fd4c0582b8668a9c3b65b3
