### ISSUE TITLE
Spike: Determine LOE and Value add  - Preview button not working for some Lovell nodes

### ISSUE THREAD

**Issue by davidmpickett** [department-of-veterans-affairs/va.gov-cms#12293]
## Describe the defect
As a Lovell editor, I want to be able to preview content that is in the Lovell-VA or Lovell-TRICARE sections. 

This is currently broken for VAMC Detail Pages. The Preview button works if they are in the Lovell Federal section, but not if they are in the Lovell-VA or Lovell-TRICARE sections. I created a test page to investigate the cases in which this is true. I have not investigated other content types.

## To Reproduce
1. Go to [Revision log for this test page](https://prod.cms.va.gov/node/52805/revisions)
2. Revert to Revision #743400 or Revision #743399 (Section = Lovell - VA or TRICARE)
3. Confirm that Preview button leads to Internal Server Error
4. Revert to Revision #743398 (Section = Lovell Federal health care)
4. Confirm that Preview button magically works again

## AC / Expected behavior
Determine - Is this content blocking or can we use dual state to get us to launch?
AC: (once we do the work) The Preview button should work consistently for content types regardless of which Lovell section they are in.

## Screenshots
![screencapture-prod-cms-va-gov-chicago-health-care-programs-test-page-do-not-publish-2023-01-19-16_46_24.png](https://images.zenhubusercontent.com/62acf41e5be34fcdb6c44c0b/1d3bc79d-e759-400a-b620-ccb69cf3c665)

![screencapture-preview-prod-vfs-va-gov-preview-2023-01-19-16_46_30.png](https://images.zenhubusercontent.com/62acf41e5be34fcdb6c44c0b/bb2e24d2-860c-45ad-a74f-c24cbf31c06e)

![Screen Shot 2023-01-19 at 5.12.29 PM.png](https://images.zenhubusercontent.com/62acf41e5be34fcdb6c44c0b/87ef4525-3656-4334-a049-1396a908f710)

![screencapture-prod-cms-va-gov-node-52805-revisions-2023-01-19-17_04_37](https://user-images.githubusercontent.com/51967950/213584670-5eca5582-203a-4b42-adaf-f1c8e3cde7e9.png)

**Comment by davidmpickett** [comment]
Not sure if this is related, but the drop-down for the Parent Link is extra weird for Lovell:
![Screen Shot 2023-01-19 at 4 49 30 PM](https://user-images.githubusercontent.com/51967950/213584847-51c43e03-2002-45d4-8899-35d27a0bbc3a.png)

**Comment by TroyA6** [comment]
Adding documented 'Pass/Fail' results for a variety of content types and sections:
[Google Sheet with Results](https://docs.google.com/spreadsheets/d/1vEZVQFREnCkS0AC9zjsOC-vOsrwADzuKtaPIrHJsRZE/edit?usp=sharing)

**Comment by swirtSJW** [comment]
@davidmpickett 

> Not sure if this is related, but the drop-down for the Parent Link for Lovell is not preserving the section hierarchy

That is not a bug.  Those menu items can not be nested under the umbrella.  It will break menus in a bad way.  They have to be at the same level to support the juggling we do.

**Comment by swirtSJW** [comment]
I am pretty sure the reason the preview server is breaking for VA and TRICARE is because the preview server has not been updated to use the code added to content-build   It does not know how to look for a matching menu (because there is no matching menu if our new code is not there) so it blows up with a fatal error.

**Comment by davidmpickett** [comment]
> That is not a bug. Those menu items can not be nested under the umbrella. It will break menus in a bad way. They have to be at the same level to support the juggling we do.

Okay I broke that part out into a separate ticket: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12303

**Comment by Dottisea** [comment]
Sending to icebox -

**Comment by davidmpickett** [comment]
@ryguyk Given that you have an [implementation ticket](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13289) that would resolve this, is it safe to close this spike ticket?

**Comment by ryguyk** [comment]
Yes. My apologies. I didn't recall that we had this spike ticket.
