### ISSUE TITLE
Drush 10 Support

### ISSUE THREAD

**Issue by ElijahLynn** [department-of-veterans-affairs/va.gov-cms#1230]
Upgrade from Drush 8 to Drush 10. CI needs an improvement to support this, mainly replacing DevShop with something else since architecturally DevShop fundamentally runs on Drush 8 and is 100% incompatible with Drush 9/10. . 

Acceptance Criteria:
See #2217

**Comment by jefflbrauer** [comment]
O1-KR2

**Comment by oksana-c** [comment]
closing in favor of #3868
