### ISSUE TITLE
Add custom VA specific fields to documentation entity

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#12309]
The content_model_documentation entity will have some pre-existing default fields that are useful for all projects.
However there are some fields that will only be needed for VA so should not be part of the contrib 
Example:  the airtable has a column to track which fields we push to lighthouse.

## AC's
- [x] Audit airtable spectool for the custom columns that **do not** contain data that is already present in Drupal
- [ ] PM reviews content from audit
- [x] Add these fields from the audit to the documentation entity
   - [x] Label: Pushed to
      - data_pushed_to
      - entity reference: 
      - cardinality: unlimited
      - description: Choose the destination(s) where this data is pushed
   - [x] Label: Pulled from
       - data_pulled_from
      - entity reference: Taxonomy external_data
      - cardinality: unlimited
   - [x] link to design source (Figma? and other sources.. like issue history (maybe break this into two fields)
      - label: Design source
      - link_to_design
      - cardinality: unlimited
   - [x] link to cms design system (storybook)
      - label: CMS Design system
      - link_to_cms_design
      - cardinality: unlimited
   - [x] link to VA design system
      - VA Design system
      - link_to_va_design
      - cardinality: unlimited
   - [x] link to KB artiicles (cardinality multiple)
      - label: Related KB articles 
      - type: entity reference to KB article content type
      - cardinality: multiple
   - [x] supporting links  
      - label: Supporting links -This is more of a free form collection of links that are not as structured as the others
      - cardinality unlimited
   - [x] stakeholders / owned by
      - entity reference to product taxonomy 
      - label: Product stakeholder
      - description: What products own or utilize this?
      - cardinality: unlimited
   - [x]  screenshot ?
      - image field
   - [-] supporting modules https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12309#issuecomment-1425916141
   - [-] links to where it appears on FE - Decided the use of this could fall under "other"  since all nodes have a link to their FE counterpart.  In some cases this might be helpful but in most cases, the content may move, so better to stay with the links on the node.
   - [x] links to research findings
   - [ ] 

new feature related to number of editors????

**Comment by swirtSJW** [comment]
Needs for additional fields:

1. pushed to lighthous
2. links to CMS design system
3. links to VA design systtem
4. link to knowledgebase articles
5. supporting links (more freeform in nature)
6. product teams (entity reference to show which products own / use it

**Comment by swirtSJW** [comment]
As a result of the audit of the existing spec tool in airtable, I created 9 new issues in the upstream module https://www.drupal.org/project/issues/content_model_documentation?categories=3
Most are not needed for MVP or spec tool replacement because they are not fully covered by the spec tests to keep them uptodate

**Comment by swirtSJW** [comment]
@BlakeOrgan @thejordanwood how do you feel about an image upload on the documentation for adding the jpg/png of the design vs a link to the design figma / sketch or whatever?

I like the idea of an image upload because it truly captures the snapshot of the time the documentation was updated.  As compared with the Figmal link that may have shifted since the design was implemented.    ONe locks it in time, but cna become outdated, vs the other is up-to-date but floating.  Or should we have both a field to drop a link to the design and upload screen shots.

**Comment by davidmpickett** [comment]
I would vote for both. Have screenshots is helpful because it gives people a visual in the context of the documentation, they don't have to go anywhere else just to have a visual example. But screenshots are not detailed design documentation. They don't generate code or have semantic markup the way the actual Figma or Sketch files do. 

There's always going to be a need to refresh documentation so it doesn't become outdated and to manage how documentation that is split between multiple systems stays synced.

**Comment by thejordanwood** [comment]
I agree with Blake. From past experience, Figma/Sketch files should be the source of truth because screenshots tend to go out of date. I know on the VA design system/Sketch side, anyone that has access to Sketch could go in and alter any files. I've had to go back into files and update what a designer did previously. In these cases, multiple people working on files could result in screenshots not getting updated.

**Comment by swirtSJW** [comment]
Thanks @BlakeOrgan @thejordanwood  and @davidmpickett   for your time and thoughts on this.  I completely understand the part about Figma or Sketch being the source of truth.   The few caveats I see:

1.  Lots of the devs don't have access to the files or the software to read the files. So the reference does not help them.
2. I actually like the idea of files because they do get out of date.... or at least are capable of being out of date.  They represent a snapshot in time.  We often have regressions where something goes missing and we have no source of truth to compare it to so we don't know what went missing.   I am thinking of the image not being an export from the design, but an actual screencap from the implemented design at the time it was implemented.    I am thinking the responsibility  would be on the dev team to enter the images (one for the edit mode and one for the view mode)

**Comment by swirtSJW** [comment]
@edmund-dunn  made a great suggestion to have a field for referencing the module(s) used.  We don't have a field type for that yet unless we were doing free tagging so I created a separate upstream issue https://www.drupal.org/project/content_model_documentation/issues/3340905
