### ISSUE TITLE
SPIKE: Determine impact of breadcrumb generation happening on all pages (NON-ISSUE; CLOSED)

### ISSUE THREAD

**Issue by ryguyk** [department-of-veterans-affairs/va.gov-cms#12301]
## Description
See [here](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12107#issuecomment-1397573611), specifically:
>...it should be emphasized that [[the] code](https://github.com/department-of-veterans-affairs/content-build/blob/7a56d1bce5bd35e5bdb7304346b30cbf0b78cc08/src/site/stages/build/drupal/page.js#L355) appears to add a breadcrumb object to pages that didn't previously have one. [The] code adds a breadcrumb object to any page that doesn't have one passed over from Drupal. Before the addition of this code, some pages would simply not have breadcrumbs...

In the course of handling all the craziness of Lovell, code was introduced that seems to have had the (likely unintended) side effect of adding breadcrumbs to many pages that did not previously have them. One such example is Vet Center pages:

https://www.va.gov/des-moines-vet-center/
![image](https://user-images.githubusercontent.com/6863534/213793213-14fecc4f-528b-4f90-b058-69024a4b579e.png)

There are a few unknowns:
1. How many pages/content types/etc. have breadcrumbs that did not have them before this code was added?
2. Is the addition of the breadcrumbs problematic (i.e. is there any reason that these pages _shouldn't_ have breadcrumbs)?
3. Are the breadcrumbs accurate?

## Acceptance Criteria
- [ ] 
- [ ] 

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by Dottisea** [comment]
Did we not already verify that this IS happening on all pages (or did I make that up?)?

**Comment by ryguyk** [comment]
We know that it's happening on all pages, yes. But we don't know how many of those pages previously did not have it. The fact that it's showing on all pages is accidental. It might be a good accident. It might be bad. We're not quite sure.

**Comment by ryguyk** [comment]
Closing this issue. This is a non-issue.
