### ISSUE TITLE
Lovell UX debt - Parent Link dropdown has unclear hierarchy

### ISSUE THREAD

**Issue by davidmpickett** [department-of-veterans-affairs/va.gov-cms#12303]
## Describe the defect
As a CMS editor working on Lovell content, I need to assign the Parent Link for VAMC Detail Pages.

It is possible to nest menu items two levels under **Programs**, but because the TRICARE and VA sides are combined here, there are instances where there are two identically labelled items to chose between with no indication which is which.

![Screenshot 2023-01-20 121354](https://user-images.githubusercontent.com/51967950/213776425-da3037db-5d7f-4a99-b110-efc4b068dee4.png)

## To Reproduce
1. Go to https://staging.cms.va.gov/ and log in as Katie.Yearley@va.gov
2. Got to the edit view of this test node https://staging.cms.va.gov/node/52805/edit
3. Scroll down to Menu Settings in right navigation and expand the drop down menu for Parent link
4. See two Gynecology Clinics that could be parents and not know which is TRICARE and which is VA

## AC / Expected behavior
At the very least, we need to have documentation around if the order of identical items is meaningfully determined and consistent (i.e. is TRICARE always above Lovell) or how to verify that an item has been added to the intended Parent.

Ideally there would be a holistic review of the how this functionality is implemented so we could understand the possibilities and trade off between users and technical limitations.

## Screenshots

![screencapture-staging-cms-va-gov-node-52805-edit-2023-01-20-12_14_13](https://user-images.githubusercontent.com/51967950/213776389-9a0c39d4-0a41-4166-868f-5680c19e4970.png)

 ## Additional context

- #11790 also covers UX debt of the Parent Link field
- KB Article - https://prod.cms.va.gov/help/vamc/how-to-manage-vamc-navigation-aka-menus
- Similar to #11790, this dropdown is even more confusing and overwhelming for Drupal Content Admins
- Also note that Audiology and Speech TRICARE is currently nested under Audiology and Speech VA. That is a content error to address with the Lovell editors, but also demonstrates how confusing this whole experience is for users.

![Screenshot 2023-01-20 125430](https://user-images.githubusercontent.com/51967950/213782406-018daa72-b24c-47d5-8951-a85329f164ff.png)

![screencapture-staging-cms-va-gov-node-52586-edit-2023-01-20-12_05_04](https://user-images.githubusercontent.com/51967950/213781784-f4616d2d-9d3a-4a66-afc8-85525e09b453.png)

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Defect")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS workstream (orange) (not needed for bug tickets)
- [ ] CMS-supported product (black)

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [x] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [x] `⭐️ User support`

**Comment by davidmpickett** [comment]
From @swirtSJW  on [Slack](https://dsva.slack.com/archives/C0FQSS30V/p1674601683405989?thread_ts=1674168684.585109&cid=C0FQSS30V):
So there are two ideas being kicked around to address this:
1) Make the menu item name for detail pages say VA or TRICARE  (this could be done by hand or we could do it automagically).  This would however bleed to the FE menu too.  Which may be good, or bad.
2) We alter the parent widget to just in the display append VA or TRICARE or BOTH to the items in the selector so they can distinguish what is where. This would not bleed anywhere but in that parent selector.

**Comment by JayDarnell** [comment]
Reference: https://drupal.stackexchange.com/questions/226133/how-can-i-overwrite-existing-menu-tree-manipulators

**Comment by JayDarnell** [comment]
I believe I will need to create a custom class to override the functionality provided by `core/lib/Drupal/Core/Menu/MenuParentFormSelector.php` in order to do this efficiently.
