### ISSUE TITLE
[cms-ci] Move PR test runs from DevShop to GitHub Actions/Circle CI

### ISSUE THREAD

**Issue by ElijahLynn** [department-of-veterans-affairs/va.gov-cms#1231]
### Problem Statement

Currently when a Pull Request (PR) builds and tests it blocks all new PRs that came in after it until after it has finished, which can sometimes take up to 45 minutes per PR. If this stacks multiple PRs this means it can take hours to move through a few PRs which is a very frustrating experience both as a developer and as a Release Manager. 

We want to keep the builds on DevShop for now but move the test runs to GitHub Actions/Circle CI. This will allow DevShop to keep building the QA PR Review Instance environments but they will take around 5-10 minutes now and be ready for the next one. This will also allow for the parallelization of PR test runs in GitHub Actions or Circle CI and they will report back to the GitHub PR much faster. Then in a future epic, we will actually parallelize each individual test, making the test feedback loop happen very fast. 

### Affected users and stakeholders

* CMS Software Engineers
* CMS QA/Test Engineers

### Hypothesis

We believe that reducing the time for environments to build and tests to run will improve overall developer experience, defect fixing, and quality. We'll know that to be true when Steve is happier. 

## Acceptance Criteria

* CMS Build/Review Instance happens in DevShop
* WEB Build/Review Instance happens in DevShop
* Tests run happens in GitHub/CircleCI

## Possible tickets to create for this epic

1. Remove test runs out of Devshop
1. Configure DevShop to continue to run the initial web build (previously was in tasks/tests.yml)
1. Setup Base Docker ([DrupalVM](https://hub.docker.com/r/geerlingguy/drupal-vm/) is closest container right now) for builds
1. Setup SQL/Database Docker
1. Figure out where to host container images
1. Decide on CircleCI or GitHub Actions
    1. Get CircleCI account/login info
    1. Determine how to pay for more server resources on GitHub Actions - is it hard?
1. Write the GitHub Actions/CircleCI Scripts
     1. ...
1. Secrets management (manual, not automated)

**Comment by jefflbrauer** [comment]
O1-KR3

**Comment by ElijahLynn** [comment]
Story is outdated. DevShop is EOL and tests are in Tugboat now.
