### ISSUE TITLE
BE: Replace placeholder CMS help text with actual help text

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#12325]
## Describe the defect
Placeholder help text is present in two content types within Drupal. We should remove this replace with useful text:
- Q&A
- Benefit Hub Landing Page

### New help text
**Section Intro** 
An optional introduction that explains why these questions may be relevant to visitors. 

**Spokes**
Add a list of link teasers that will provide additional information that relates to the page topic.

**Support Services**
Add services that will be useful to veterans such as Health Benefits Hotline, My HealtheVet Help Desk, etc.

## Acceptance Criteria
- [ ] Help text updated per above:
  - [ ] Section intro
  - [ ] Spokes
  - [ ] Support Services

**Comment by jilladams** [comment]
@wesrowe we just need the text provided that should be used in these 2 spots, and then Christia has capacity maybe to pull this into sprint.

**Comment by wesrowe** [comment]
Has @thejordanwood looked at this? It's going to need to go through UX.

**Comment by thejordanwood** [comment]
@wesrowe I haven't looked at this. Would this be something Blake or I would need to review?

**Comment by wesrowe** [comment]
@thejordanwood, I'm assigning this to you for pre-refinement. I don't recall where the 2 points estimate came from. Note that the ACs are just to write the help text.

**Comment by thejordanwood** [comment]
@wesrowe This is my suggested help text for these areas. I'm not sure should approve this, @BlakeOrgan @laflannery? 

**Section Intro** 
An optional introduction that explains why these questions may be relevant to visitors. 

**Spokes**
Add a list of link teasers that will provide additional information that relate to the page topic.

**Support Services**
Add services that will be useful to veterans such as Health Benefits Hotline, My HealtheVet Help Desk, etc.

**Comment by thejordanwood** [comment]
@laflannery I edited my copy to fix the grammar. 

@wesrowe This is ready for next steps.

**Comment by jilladams** [comment]
(moved out of ticket body to this comment for clarity) 

## DEFECT description (for historical context)

See screenshots below.

## To Reproduce
Steps to reproduce the behavior:
1. Add a new Benefits detail page
2. Click on "Add Content block" within the main content
3. Add a new Q&A Section
4. Note the "[Help text goes here]" on the Section Intro field

This placeholder text is found in the code in 4 distinct locations, so should be possible to update with distinct help text per product: 

![Screenshot 2023-02-21 at 1 40 26 PM](https://user-images.githubusercontent.com/85581471/220465209-d73985ef-ab5e-4bff-8bdb-569ee2f24a15.png)

## Screenshots

Benefit detail page – "Q&A Section"
![image](https://user-images.githubusercontent.com/106678594/214323077-9c76a21f-6445-4506-93e3-471ff8b172b5.png)

Benefit hub landing page - "Spokes" UI:
![image](https://user-images.githubusercontent.com/106678594/219724770-7b971f95-88bc-499b-b0d5-2e569113fca9.png)

## Additional context
We will want to probably run this by UX first if we choose to replace this.


**Design:**
- [ ] Help text written for Benefit detail page – "Q&A Section" 
- [ ] Help text written for Benefit hub landing page - "Spokes" UI

**Comment by chri5tia** [comment]
What is the help text that we should put here? Do you want me to take a stab at it?

**Comment by thejordanwood** [comment]
@chri5tia Here's help text you can use:

**Section Intro**
An optional introduction that explains why these questions may be relevant to visitors.

**Spokes**
Add a list of link teasers that will provide additional information that relates to the page topic.

**Support Services**
Add services that will be useful to veterans such as Health Benefits Hotline, My HealtheVet Help Desk, etc.

**Comment by chri5tia** [comment]
Should be fixed with https://github.com/department-of-veterans-affairs/va.gov-cms/pull/14378

field.field.node.landing_page.field_spokes
field.field.node.landing_page.field_support_services
field.field.paragraph.q_a_section.field_section_intro

**Comment by jilladams** [comment]
I took a look at this for prod verification purposes for fun, and it's worth calling out: in refining, we didn't do a great job spelling out exactly what was going on here. @chri5tia solved it, but for the sake of future reference: 

* field.field.node.landing_page.field_spokes >> Only exists on Benefit Hub Landing pages
* field.field.node.landing_page.field_support_services >> I can't find any node creation form so far where this is exposed. ? But her PR did replace the placeholder text.
* field.field.paragraph.q_a_section.field_section_intro >> Visible on Benefit Detail Page forms, if you Main Content > add Q&A group. This text is different than the Help text used on FAQ & Resources & Support forms.

Screenshots:

**FAQ page form**
<details>

![FAQ page form](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/85581471/be869ec1-c758-4585-bf53-3dbee035aacc)</details>

**Benefit Detail page form**
<details>

![Benefit Detail page form](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/85581471/6a26d524-c62d-496d-9685-33e82cc7c249)</details>

**Resources and Support Detail Page form**
<details>

![Resources and Support Detail Page form](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/85581471/41ce6ae2-d218-4777-8b24-dc993e8f256c)</details>
