### ISSUE TITLE
Events: Inconsistent breadcrumb capitalization

### ISSUE THREAD

**Issue by ryguyk** [department-of-veterans-affairs/va.gov-cms#12326]
## Status
**[2024-12-30] [Fran]**Spike has been completed and a ticket created https://github.com/department-of-veterans-affairs/va.gov-cms/issues/20179 to implement the change to Easy Breadcrumb settings, which will fix this issue. Closing this as a no-op.
**[2024-07-22] [Fran]** Jill mentioned in Product Syn meeting today that this may be a DS Team issue to solve/provide guidance. Moving out of the Next Refinement and assigned to me for follow up.

## What's going on?
There is [code that generates breadcrumbs from a URL](https://github.com/department-of-veterans-affairs/content-build/blob/8aa1bf102f4fa621588730fef9e33cc042d8b915/src/site/stages/build/drupal/page.js#L142). This breadcrumb generation capitalizes only the first letter in each of the breadcrumbs. So, we end up with things like "Lovell federal va health care" instead of "Lovell Federal VA health care".

But there is some nuance. We don't see this on every page. Here are some pages where we do see it:

#### Event Detail Pages
This problem will exist on (almost) all event-detail pages, because [this code](https://github.com/department-of-veterans-affairs/content-build/blob/8aa1bf102f4fa621588730fef9e33cc042d8b915/src/site/stages/build/drupal/page.js#L292) makes it such that all event detail nodes have their breadcrumbs generated from the URL, even if the breadcrumb is already present. 

https://www.va.gov/central-iowa-health-care/events/52266/
![image](https://user-images.githubusercontent.com/6863534/213724433-ee5e9a69-768b-4bca-9580-3554d5ce9aa0.png)

https://www.va.gov/minneapolis-health-care/events/48210/
![image](https://user-images.githubusercontent.com/6863534/213551409-0689f781-2de6-45ba-99d3-49b6c4d82db5.png)

In the above examples, we see that only the first letter is capitalized, which is clearly problematic in the first case because "iowa" is not capitalized. In both the Central Iowa and Minneapolis examples, note that the breadcrumb does not include "VA" as a prefix. They _should_ behave like this Pittsburgh example:

https://www.va.gov/pittsburgh-health-care/events/52605/
![image](https://user-images.githubusercontent.com/6863534/213551769-55eb5453-c118-4325-bcdd-67e5f94c4355.png)

In fact, **ALL** event detail pages will have this problem _except_ events at Pittsburgh VA. This is due to seemingly very old code that specifically checks for Pittsburgh VA and handles as an exception. I imagine this is a remnant of the time when Pittsburgh was the first VAMC to be modernized.

### How to fix?
It is likely the case that Max's code negates the need for any specific processing for event nodes. Event-detail pages should not need a specific call to this breadcrumb-generation function since the newer code is conditionally calling that function for _all_ content that does not have a breadcrumb passed over from Drupal. If the event-specific call is removed, the problem would be fixed for event-detail pages because they are now coming over from Drupal with a breadcrumb object, so this generation function would not be called.

**Comment by mmiddaugh** [comment]
Related: #12125: Vet Center Breadcrumbs not matching H1

**Comment by FranECross** [comment]
Jill mentioned in Product Syn meeting today that this may be a DS Team issue to solve/provide guidance. Moving out of the Next Refinement and assigned to me for follow up.

**Comment by laflannery** [comment]
This is not resolved with V3 as the processing of the crumbs is separate. However this is resolved in the AP templates:
- Central Iowa:
![image](https://github.com/user-attachments/assets/e0c6e1c0-04ff-4f4a-b3b1-a956599d2b63)
- Minneapolis:
![image](https://github.com/user-attachments/assets/2377c6d5-59ad-4a12-82b1-ecca15ab9ca3)

**Comment by aklausmeier** [comment]
DST breadcrumb support ticket is complete and this capitalization issue persists. This should be unblocked and may need to be a spike. 

@FranECross
