### ISSUE TITLE
[cms-ci] CI Dashboard pages load in under 5 seconds

### ISSUE THREAD

**Issue by ElijahLynn** [department-of-veterans-affairs/va.gov-cms#1232]
- [x] Dashboard pages must load in under 5 seconds, no matter how many Pull Requests (PRs) are open or how many nodes are on the site
e.g. http://devshop.cms.va.gov/projects, http://devshop.cms.va.gov/project/project_cms and http://devshop.cms.va.gov/project/demo

**Comment by indytechcook** [comment]
Blackfire Profile on `/projects` page: https://blackfire.io/profiles/790d70f3-58b3-4f5c-b59e-c2258128d7a3/graph
