### ISSUE TITLE
BTSSS: re-discover possible flow improvements

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#12338]
## Description

As a Veteran, I want access to the travel reimbursement tool from the [unauth page](https://www.va.gov/health-care/get-reimbursed-for-travel-pay/) to be easier and faster so that I will be more likely to receive the travel reimbursement benefit to which I'm entitled.

We heard from Dave Conlon that an OCTODE team member and Veteran named Stephen Barrs has explored the flow for his own travel reimbursements. He has a theory that, after logging on once "the hard way," subsequent logins are smoother and may be more amenable to deep-linking.

(edit) Per Chris Johnston, here is the UX that he and Barrs think is achievable:

- Remove the link to Access VA 
- Replace that link with an appropriate version of the login widget
  - That widget will in turn open the standard sign in modal
- Upon successful authentication, redirect the user directly to the BTSSS app
  - https://dvagov-btsss.dynamics365portals.us/signin
  - Testing (by both Stephen and Chris) indicates that if already authenticated, this link will correctly take you to BTSSS

### Clarifications needed / implementation hypothesis
- Are we talking about a react widget similar to Cerner ones? 
  - If user is already authenticated, offer link directly to BTSSS. 
  - If not, offer "Sign in" button. Sign them in, then...?
    - Take them to BTSSS immediately on successful login?
    - Or widget then offers BTSSS link and they have to click that now

#### E.g., refill prescriptions widget
<details>
<summary> Screenshots </summary>
Unauthenticated user sees:
<img width="358" alt="image" src="https://user-images.githubusercontent.com/4054752/217622874-87881118-1df8-44d4-9a37-b03ab3188e9b.png">

After authenticating, user sees:
<img width="419" alt="image" src="https://user-images.githubusercontent.com/4054752/217623288-44f2f3ef-2ed5-4751-b499-dcc254eaa606.png">
</details>

### Background

Danielle Thierry originally called out the BTSSS login process as very painful for Veterans, and also highly trafficked. (This has been validated by the way Veterans talked about travel reimbursement in unrelated user research about the new home page.) The idea was using a deep-link. At the time, our discovery in #9206 indicated that the BTSSS resists deep-linking because of a series of required screens, e.g., accepting legal terms. 

### Necessary context
Please catch up by reading:
- The [epic](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9157)
- The comments on the earlier discovery ticket, #9206
- Mural of [existing BTSSS flow](https://app.mural.co/invitation/mural/vagov6717/1675275822734?sender=u907f83e01e35bb04de6f8139&key=d887714d-04ea-418a-ab0b-fdf2e8b2374b)
- [Notes (Google doc)](https://docs.google.com/document/d/184QkNtoKIaSBWOzt7DPLOmqQhrwIqGyBKqwF998Hcjg/edit#heading=h.or56slpxdj90) from original call with BTSSS

## Acceptance Criteria
- [x] Document Stephen Barrs's observations about how subsequent log-ins to BTSSS work
- [x] Find out if BTSSS team implemented OAuth in Fall 2022, which they thought might enable a logged-in Veteran to skip the login screens
  - Aaron Kauffman is the BTSSS SME who knows OAuth context at BTSSS
  - Josh has offered to give us access to the flow
- [ ] Write a new spike ticket for pursuing next steps/discovery, if applicable (e.g., contacting Platform about OAuth angle)

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by jilladams** [comment]
@wesrowe I found the old BTSSS invite, where aaron.kauffman@va.gov was our primary point of contact. He no longer shows up in the VA Outlook / Teams as a valid email address, so may have left. We probably will need to reach out to other folks on the BTSSS team to get modern contacts.

**Comment by wesrowe** [comment]
Per [this slack thread](https://dsva.slack.com/archives/C52CL1PKQ/p1675797952271179), Josh considered closing the ticket after a single conversation with Mark Dewey (Check-in Experience team). That didn't meet the ACs though, and Conlon and Chris Johnston got involved in slack to clarify the ask and make sure we follow through. Adding Chris J's summary of the hypothesized UX to the description above.

**Comment by jtmst** [comment]
The demo for this with Stephen Barr has been scheduled for the morning of 02/15/23. This ticket can be closed once findings from that demo have been documented.

**Comment by jtmst** [comment]
The current method of accessing the travel claim system involves users linking through 'Go to AccessVA to file a claim' link on https://www.va.gov/health-care/get-reimbursed-for-travel-pay/.  From there users are prompted to authenticate, irregardless of whether or not they are loggin in on VA.gov.  Stephen Barrs demoed that users who are logged in are able to acccess BTSSS without authenticating again by accessing this link: https://dvagov-btsss.dynamics365portals.us/signin, directly.    Previously this wasn't possible, but recent work from the BTSSS team allows that authed user bypass to happen.

The proposed change is to change the 'go to accessVA to file a claim' link to a react widget that sends the user straight to BTSSS if they are logged in, and prompt them to login with the standard login modal if they are not.

**Comment by jilladams** [comment]
Auth-wise: 
* AccessVA includes PIV login
* Otherwise, all the supported VA.gov login methods do work on BTSSS

No spike ticket required. Design is mocked up.
Next steps: Collab cycle (Plat) kickoff; Sitewide content (intake ticket created).

Closing.
