### ISSUE TITLE
Merge header level fix plugin

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#12346]
#12342 writes the plugin
#12345 benchmarks performance

When performance is benchmarked, PR from 12342 can be merged.

### Rollback criteria

- It's already bad, so it would have to get a lot worse to roll it back
- KPI: Nate's Heading Export report will help with accordion assessment
  - Laura confirmed in comment below that the report will run on all PRs starting 2/13
  - ~~So run report before release in review instance to confirm results as expected~~ - report can't run in RI, so Laura tested manually 
  - then run it after in Prod just to be sure
  - Increase of >5% is reason to consider rollback

### Clarifications needed:
- Can Nate's report be run in staging or a review instance? Yes: can be run against Staging

## ACs
- [ ] Do not merge on a Thursday or Friday
- [ ] Smoke test immediately on Prod using Nate's report

**Comment by laflannery** [comment]
@wesrowe I checked with Nate and the header report he said should be available and automatically running on all PRs Monday - he is finishing it up today.  So we should be able to use it to determine if we need to roll back.  If we have any further questions for him next week after this rolls out - if its not clear how it works, what it looks like, etc. we can follow back up.

**Comment by wesrowe** [comment]
Thanks @laflannery, description and ACs updated

**Comment by jilladams** [comment]
Pulled into sprint based on https://dsva.slack.com/archives/C52CL1PKQ/p1677791641887249

**Comment by wesrowe** [comment]
@jtmst @laflannery, this might be a good issue to update. I saw some slack convo but didn't track closely enough to update here with confidence.

**Comment by laflannery** [comment]
I believe this can be closed, it was merged yesterday (3/6) as planned and should reach prod today (3/7) with the normal release schedule. @jtmst should probably be the one to officially close it though just in case there is something I'm not thinking of

**Comment by jtmst** [comment]
Yep, I believe initial testing has shown enough to let this roll through to prod.  Will close.
