### ISSUE TITLE
Create article for Image upload

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#12347]
## Background

I think an article should be created for image upload. There are multiple other KBs that are about uploading a specific image (i.e. How to add a facility image) or an article where adding an image is a section within the article but the process is not different.  This causes a problem because now, if/when we need to update this process documentation we have to change it in quite a few places.

I propose we create one unifying article for uploading/adding an image and then link to it in all of these many places - specifying instructions when needed. 

## Acceptance Criteria

- [x] Article is created
- [x] Article is reviewed by CMS team
- [x] Article is reviewed by Help desk
- [x] Article is published
- [x] A list of other KBs that this would impact is created

**Comment by laflannery** [comment]
@EWashb Do you have thoughts/feelings/opinions on this - I already wrote a [draft article](https://docs.google.com/document/d/14zGUSUw2HzSi4hinWjrQ1E8M7Ou85vlIW2RpzJeOapM/edit#)

I have questions about functionality which I can track down the answers to, but in general do you think this would be good to add and might be on the right track?

**Comment by laflannery** [comment]
Places that should be updated to link to this new single source of truth (this is a lot of them, possibly not all):

- [How to add an image to a Mobile Vet Center affiliated with your Vet Center](https://prod.cms.va.gov/help/vet-centers/how-to-add-an-image-to-a-mobile-vet-center-affiliated-with-your-vet-center)
- [How to add a VAMC Facility image](https://prod.cms.va.gov/help/vamc/about-locations-content-for-vamcs/how-to-add-a-vamc-facility-image)
- [How to add or edit a Story](https://prod.cms.va.gov/help/va-medical-centers-vamcs/about-stories-content-for-vamcs/how-to-add-a-story)
- [How to edit a VAMC System homepage](https://prod.cms.va.gov/help/vamc/how-to-edit-a-vamc-system-homepage) (maybe?)
- [Alternative Text](https://prod.cms.va.gov/help/cms-basics/alternative-text)
- [How to create a help guide](https://prod.cms.va.gov/help/how-to-create-a-help-guide)
- [How to edit a VAMC Facility](https://prod.cms.va.gov/help/va-medical-centers-vamcs/about-locations-content-for-vamcs/how-to-edit-a-vamc-facility)
- [How to add, change or remove a community access point](https://prod.cms.va.gov/help/vet-centers/how-to-add-change-or-remove-a-community-access-point)
- [How to edit an event](https://prod.cms.va.gov/help/cms-basics/how-to-edit-an-event)
- [How to add a Vet Center facility photo](https://prod.cms.va.gov/help/vet-centers/how-to-add-a-vet-center-facility-photo)
- [How to edit or add a Staff Profile](https://prod.cms.va.gov/help/vamc/how-to-edit-or-add-a-staff-profile)

**Comment by EWashb** [comment]
@laflannery thank you for doing this. It was very much needed. I don't see anything that needs to be edited or added.

**Comment by laflannery** [comment]
@BlakeOrgan wants to review as well

**Comment by EWashb** [comment]
@laflannery I think that's a great idea. Appropriate help text could go a long way IMO. Do you have an idea of all the places where this new help text should live? If so, we can make a ticket.

**Comment by laflannery** [comment]
I sure do! I'll make a ticket

**Comment by laflannery** [comment]
[Draft Article](https://docs.google.com/document/d/14zGUSUw2HzSi4hinWjrQ1E8M7Ou85vlIW2RpzJeOapM/edit#)

**Comment by laflannery** [comment]
@TroyA6 I forgot to assign this to you but the article Just needs a review: [Draft Article](https://docs.google.com/document/d/14zGUSUw2HzSi4hinWjrQ1E8M7Ou85vlIW2RpzJeOapM/edit#)

**Comment by laflannery** [comment]
[Published](https://prod.cms.va.gov/help/how-to-upload-images)

Added new ticket to go through and update other articles to point to this: #13032 13032
