### ISSUE TITLE
Write plugin to rewrite accordion header levels after content-build

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#12342]
## Context
* #11205 describes a large-scale problem where accordion headers are not being assigned semantic header levels. 
* [Heading export](https://pr12191-07ub2sgt04vfeyszauoytvw3fqtwpy6z.ci.cms.va.gov/heading_order_violations.html) is a one-off manually generated report that describes current scale of found issues that we are seeking to resolve with work in this ticket. @ndouglas wrote and can run this report, or provide steps for assigned engineer to be able to run it yourself. 
* #12255 identified the work described here

## Description
Task in this ticket is to write a plugin that modifies the dom after the html files are built in content build.  Examples of this being done are in `src/site/stages/build/plugins/modify-dom`, and the most similar example the developer that works on this could reference would be in `src/site/stages/build/plugins/modify-dom/add-id-to-subheadings.js`. 

### Methodology
The plugin we create is going to run alongside the other plugins in `src/site/stages/build/plugins/modify-dom/index.js` where each html file is stored individually to have these modifications run against them.  We are going to need to create logic that finds va-accordion components with the data-template attributes we are targeting (eg collapsible_panel) and works backwards to find the closest previous div with a data-template of paragraph/wysiwyg that contains a header. We can reassign the accordion header levels based on that header.

### Potential Issues

- It is still possible for editors to create incorrect header levels on their own eg https://www.va.gov/albany-health-care/programs/covid-19-vaccines/index.html.  On this page there is an incorrect H4 header inserted that would result in our accordion header being an H5. 
- This approach will help assign levels to accordion components within some data-templates but may require some additional work to accommodate others.
- Some benchmarking and evaluation will need to be done to ensure this doesn't too negatively impact build times

### Dev Considerations

- Testing this won't be fun as it this logic will run at the end of content-build's build.
- Benchmarking of build times before and after will be required to make ensure we aren't adding a significant amount of build time
- Testing will need to be extensive, checking that accordions used in a variety of templates are accurate and that no currently correct header levels are changed

### Testing
New ticket #12352 for Laura F. Her testing will be manual – i.e., test with a representative sample of accordion content.
- [ ] Evaluate risks after implementation – "litmus test" in staging

## Acceptance Criteria
- [ ] Plugin is runnable in an environment where benchmarking can be performed (Review Instance, not local)
- [ ] Issues described in https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11205 are resolved by this change
- [ ] Code review _is_ performed in a draft PR or PR to an integration branch, and changes integrated, _prior_ to benchmarking
- [ ] Code is not merged to main until after benchmarking in # is complete

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [X] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`

**Comment by laflannery** [comment]
@apisandipas I had previously been talking with Josh about how this plugin would work and what exactly would be impacted.  I am putting together my test plan and I have questions on if other scenarios will be covered.  For background - the default case we had been working with was that this plugin would impact accordion cases where there was a `<div data-template="paragraphs/wysiwyg">` followed directly by a `<div data-template="paragraphs/collapsible_panel">`. Can you take a look at [my comment in the testing ticket](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12352#issuecomment-1406808458) and let me know if I should be looking at any of these other scenarios as well?

**Comment by jilladams** [comment]
Laura's test doc that flags incorrect additions where the plugin is grabbing more headers than it should: https://docs.google.com/spreadsheets/d/1j1FgW1D78gFpVjPYTjsd0DpiDfCATYUf9xG_09-BeOQ/edit#gid=132464158

**Comment by jilladams** [comment]
For the histories: this ticket ended up being more like a 8+.

**Comment by jilladams** [comment]
PR that merged: https://github.com/department-of-veterans-affairs/content-build/pull/1487
