### ISSUE TITLE
Update KB Article to reflect changes to COVID status feature 

### ISSUE THREAD

**Issue by JayDarnell** [department-of-veterans-affairs/va.gov-cms#12360]
## Description

Once the changes to the COVID status feature from #10708 have been deployed we will need to update our KB articles to reflect the changes to how this component behaves.

## Acceptance Criteria
- [x] VHA Digital Media drafts the "Heads up, this is changing" email for editors to include the KB article link: https://prod.cms.va.gov/help/vamc/about-locations-content-for-vamcs/about-alerts-and-operating-statuses/how-to-edit-covid-19-status-for-a-vamc-facility
- [x] Link to completed KB article is available for inclusion in the email to editors announcing the change
- [x] Sent to Help Desk for review

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [ ] `Public Websites`
- [X] `Facilities`
- [ ] `User support`

**Comment by omahane** [comment]
Here's the current video:
https://www.youtube.com/watch?v=BYwHFXa61C8

**Comment by laflannery** [comment]
@omahane I don't know if you are curious at all but I just edited your latest draft just with layout and formatting, so it matches more closely to our newer articles.  Wanted to let you know if you happened to see all those changes why that happened!

**Comment by omahane** [comment]
Current status: The KB article is done. There are ACs about the email going out, which can happen at any time today or tomorrow.

**Comment by omahane** [comment]
@Dottisea Do we know if the email has gone out?

**Comment by Dottisea** [comment]
waiting on the email to be sent
