### ISSUE TITLE
Update error states for character limits on input fields in the CMS based on design suggestions.

### ISSUE THREAD

**Issue by BlakeOrgan** [department-of-veterans-affairs/va.gov-cms#12378]
## Description
Within the CMS on the edit screens, some fields that have a character limit enabled have a red indicator when the editor goes over the limit. This red color is used both on the border of the field and in the character count below the field. 

## Screenshot
![image](https://user-images.githubusercontent.com/106678594/182946157-fc4fc87c-9074-4bf3-8637-b4367a8089f0.png)

## Additional Context
The original design suggestions can be found in #10865

Figma design can be referenced here:
https://www.figma.com/file/gCSCL6VSGZGmYCMT0bq1Uu/Character-Counters?node-id=4%3A977&t=srvqt5e29PlK5GAd-1

## Acceptance Criteria
- [ ] Update text color for character counter to always be `#212121`
- [ ] Update the border outline around the field to be to `#B20D01` when the number of characters exceeds the character limit
- [ ] Requires design review
- [ ] Requires accessibility review

### Team
Please check the team(s) that will do this work.

- [x] `CMS Team`
- [ ] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`

**Comment by EWashb** [comment]
removed sprint label since this is a stretch item
