### ISSUE TITLE
Update warning states for character limits on input fields in the CMS based on design suggestions.

### ISSUE THREAD

**Issue by BlakeOrgan** [department-of-veterans-affairs/va.gov-cms#12377]
## Description
Within the CMS on the edit screens, fields that have a character limit enabled have a gold indicator when the editor gets close to the limit, within 5 characters. This gold color is used both on the border of the field and in the character count below the field.  

## Screenshot
![image](https://user-images.githubusercontent.com/106678594/183948762-12138ac5-c375-4de0-84f2-b910fb38825f.png)

## Additional Context
The original design suggestions can be found in #10135

Figma design can be referenced here:
https://www.figma.com/file/gCSCL6VSGZGmYCMT0bq1Uu/Character-Counters?node-id=4%3A977&t=srvqt5e29PlK5GAd-1

## Acceptance Criteria
- [ ] Update text color for character counter to always be `#212121`
- [ ] Update the border outline around the field to `#C58702` when between 5 and 0 characters away from the character limit
- [ ] Requires design review
- [ ] Requires accessibility review

### Team
Please check the team(s) that will do this work.

- [x] `CMS Team`
- [ ] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`

**Comment by EWashb** [comment]
removed sprint label since this is a stretch item
