### ISSUE TITLE
Nodes that had a Staged revision cannot be viewed, or have their revisions deleted 

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#1237]
**Describe the defect**

At least one node, possibly more, have a revision with the now-deleted  `approved_by_reviewer` moderation state. 

For example, http://pr1203.ci.cms.va.gov/node-revisions/841 (or prod.cms.va.gov/node/841) creates the following error: 

```
InvalidArgumentException: The state 'approved_by_reviewer' does not exist in workflow. in Drupal\workflows\Plugin\WorkflowTypeBase->getState() (line 155 of core/modules/workflows/src/Plugin/WorkflowTypeBase.php).
The website encountered an unexpected error. Please try again later.
```

**To Reproduce**
1. Go to prod.cms.va.gov/node/841 then go to error log (or go to http://pr1203.ci.cms.va.gov/node-revisions/841 if it's still around)

**Expected behavior**
/node/841 and /node/841/revisions should load properly.

**Background**
Before deleting the moderation state, we checked if there were any nodes with that state, but didn't check any revisions. 

**Implementation**
Find all revisions with approved_by_reviewer moderation state.

Either delete any revision with that state or (ideally) change it to In review.

**Comment by indytechcook** [comment]
Here are the entities with `approved_by_reviewer`

content_entity_id | content_entity_revision_id | content_entity_type_id
----------------- | ------------------------- | -----------------------
841 | 9646 | node
992 | 11407 | node
2587 | 15111 | node
2628 | 15132 | node
