### ISSUE TITLE
CMS Design: VA Benefit Taxonomy UI

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#12383]
### User story

**AS A** Veteran
**I WANT** Editors to be able to enter benefits into the VA Benefit Taxonomy
**SO THAT** the same language is used to describe benefits and how to apply to them across all Veteran-facing products.

**AS AN** Editor
**I WANT** to enter benefits into the MVP version of the VA Benefit Taxonomy
**SO THAT** the BCM can be leveraged by Veteran-facing products.

The CMS design will be driven by the [BCM spec spreadsheet](https://docs.google.com/spreadsheets/d/1gP6x-QLFRrJlLWdCEE1COAZXU-kRRmFKSc0sIlc_tyM/edit?usp=sharing).

### Notes
* This ticket / points assumes 
  * initial review for sign off
  * delivery to Christia / Drupal eng as well as review cycles for any implementation questions

## Acceptance criteria

- [x] Kickoff call has been held with Jordan, Christia, and DaveP to orient to the spec sheet and Drupalness (Wes can help schedule)
- [ ] UI enables the creation of a new Benefit per ***only rows 4-17 of the spec spreadsheet*** (the ones finalized in the meeting on 3/29)

 spec spreadsheet
- [x] Requires Dave Pickett, Christia review

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [X] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`

**Comment by jilladams** [comment]
Marked as stretch for Sprint 81, ticket needs points once we've done the kickoff call and Jordan groks effort.

**Comment by wesrowe** [comment]
@chri5tia, I just added an AC above to reflect something DaveC said in the spec meeting. I don't think it was discussed how this would be implemented, hopefully a known thing in Drupal?
>The VA Benefit API ID can NOT be modified after a Benefit is published

**Comment by wesrowe** [comment]
Note that I focused the ACs on the fields that we reviewed in yesterday's meeting.

**Comment by chri5tia** [comment]
@thejordanwood Can you put your spec here? I am using this ticket to complete phase 2 this sprint.

**Comment by thejordanwood** [comment]
I've added the additional fields we discussed in our meeting yesterday to my [benefit content model mockup](https://www.figma.com/file/1xUGIKRiuVmYMUoXYTr0BI/Benefit-Content-Model?node-id=6%3A4791&t=u3erjDFKWpnZzWO5-1) for whenever you're ready to use it.

**Comment by jilladams** [comment]
Bookkeeping miss here -t his wasn't in S81. Complete.
