### ISSUE TITLE
CMS Collab cycle: Drupalize "create account" block content

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#12387]
## Description

As the Homepage PM, I want to bring the "Create account" content block proposal to CMS Collab Cycle so that the feature meets CMS standards.

## Acceptance Criteria
- [x] Schedule CMS-CC meeting
- [x] Hold meeting
- [ ] Ticket any follow-up steps required prior to implementation

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [x] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`

**Comment by jilladams** [comment]
Done: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12062#issuecomment-1424563203
