### ISSUE TITLE
Identify external IncLim stakeholders/approvers and validate final fields

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#12384]
## Description

As a VA PO, I want to know which external VA stakeholders have the knowledge and power to sign off on the Income Limits Web App business rules so that we can eliminate related risks before implementation.

The types of questions that have come up in technical design:
- The income limit/threshold for Veterans receiving Housebound benefits were different (higher) in the old wizard than for those not receiving Housebound (there was a separate row in the results table). Yet the Veteran Enrollment System (VES) doesn't have an entry for this threshold, and our SMEs (Josh Faulkner, Lindsey Peace) don't think that it actually affects Income Limits. Who is the stakeholder on the business side who can actually sign off on our app not taking housebound benefits into account?

## Acceptance Criteria
- [x] Consulted with SWContent: Who are your SMEs for cost of care?
- [x] Documented who can approve the thresholds we present and confirm that they are calculated correctly using the correct inputs?
- [x] Set a meeting with those stakeholders to discuss how we will obtain their approval
- [x] Confirm with Dave C that the documentation is adequate for OCTO-DE

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [x] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`

**Comment by wesrowe** [comment]
Danielle update from slack (DM with Wes) on 2/8:

> Hi. In my meetings today with VHA digital media, they recommended member services as the best SMEs for the income tool. I had been debating between member services or the copay rates revenue folks.
Jenny H-L recommended reaching out to the member services action email group as an entry point rather than a specific SME. So I think you can go ahead and do that.

I have asked Danielle to clarify where to look up the "member services action group email".

**Comment by wesrowe** [comment]
Have been trying to regroup stakeholders we know (Stacy Rine, Lindsey Peace) to come up with a plan to cover all content and functionality approvals. Documented the key questions we came up with internally (PW + SWContent). Meeting set for Wed 2/15, past end of S77. That meeting will probably not resolve ticket. Will carry over.

**Comment by jilladams** [comment]
@wesrowe I know you said we are down to only VHA and not including VBA -- any other notes you can add here re: next steps / timing expectations?

**Comment by wesrowe** [comment]
Team update on Income Limits: Research will be blocked through the end of the sprint (1 week from today). I made some progress with stakeholders last week, mainly establishing that we will not need to include any new ones from VBA (so we're sticking with VHA). I set up a meeting tomorrow that will hopefully clear up questions among our VHA stakeholders. But finalizing prototype design and content will be blocked until Danielle's return next week.

**Comment by wesrowe** [comment]
I will be creating a decision log in the Income Limits product folder today, and I'll detail stakeholders there. Suffice to say: Lindsey Peace (VHA HEC) is going to be the main one, and she'll defer to a couple people in EED (Enrollment Eligibility) for a few details if she's not clear herself.

**Comment by wesrowe** [comment]
Info is added to [product folder in github](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/income-limits-app)
