### ISSUE TITLE
Update 6102 notifications email based on research findings and feedback

### ISSUE THREAD

**Issue by EWashb** [department-of-veterans-affairs/va.gov-cms#12391]
## Background

Based on feedback received during 6102 notifications research, areas of opportunity were identified for updating the [notifications email](https://www.figma.com/file/fQl2Y2k9MDA2dc0xViC645/6102-Notification-Email?node-id=69%3A696&t=84NB75XtfBIgP57e-0). 

## Acceptance Criteria

- [x] Remove 30/60/90 day outdated differential on the email
- [x] Combine outdated content into one section 
- [x] Provide a link to the CMS where editors will see their outdated content list
- [x] Add "Action Required" to subject line
- [x] Accessibility review 
- [x] Create tech implementation ticket for dev build

**Comment by BlakeOrgan** [comment]
I've made updates and added a couple questions to the [Figma file](https://www.figma.com/file/fQl2Y2k9MDA2dc0xViC645/6102-Notification-Email?node-id=273%3A2548&t=8BgkgPR2pKBuLdxK-1).

**Comment by laflannery** [comment]
Based on some technical updates for MVP @laflannery and possibly @EWashb will be updating designs for V4

@EWashb will also add some more detailed notes regarding NVP

**Comment by laflannery** [comment]
@EWashb Can you take a look at V4 when you get a chance? https://www.figma.com/file/fQl2Y2k9MDA2dc0xViC645/6102-Notification-Email?node-id=0%3A1&t=RbphvYJX8mwKTfUd-0

There were only a couple updates to make this generic - so I may have missed something.  Also I have a couple questions in there

**Comment by EWashb** [comment]
After speaking with devs, it was determined that the outdated content view within the email would be very heavy lift that would require dymanic coding for each permission level. Also, showing the outdated content directly in the email would not be the source of truth. We should always lean into the current outdated content view to be the source of truth. However, we can update the outdated content report to show only 25 at a time. Those 25 (due to pagination) will, by default, always be the most outdated and what editors should focus on. 

We can iterate on the email as needed, but to ensure that all appropriate editors are notified AND we aren't overcomplicating the design, we have landed on this design below. I need to determine if two links are really needed because they essentially take you to the same place.

 
<img width="747" alt="Screenshot 2023-02-22 at 3 50 57 PM" src="https://user-images.githubusercontent.com/90111970/220767770-302a1b6f-ef2c-4c63-9b97-baa0237eeeda.png">

**Comment by EWashb** [comment]
[Email design](https://www.figma.com/file/fQl2Y2k9MDA2dc0xViC645/6102-Notification-Email?node-id=314%3A6147&t=CujT09G1qiI4aiAe-1)

**Comment by EWashb** [comment]
shared final design with Dave via Slack and Email on 2/23
