### ISSUE TITLE
Updates to Lighthouse push for COVID-19 status details change

### ISSUE THREAD

**Issue by JayDarnell** [department-of-veterans-affairs/va.gov-cms#12398]
## Description

Once we've completed the work outlined in #10708 we need to be sure we've accounted for any impact these changes may have on the datasets we send to lighthouse: va_gov_post_api module - PostFacilityStatus.php

## Acceptance Criteria
- [x] Test updating COVID-19 status on the current main branch and capture the JSON object prepared for lighthouse
```
{
  "nid": "1584",
  "uid": "facility_status_vha_573QK",
  "endpoint_path": "/services/va_facilities/v0/facilities/vha_573QK/cms-overlay",
  "payload": {
    "operating_status": {
      "code": "NORMAL",
      "additional_info": null,
      "supplemental_status": [
        {
          "id": "COVID_LOW",
          "label": "COVID-19 health protection: Levels low"
        }
      ]
    },
    "system": {
      "name": "VA North Florida/South Georgia health care",
      "url": "https://www.va.gov/north-florida-health-care",
      "covid_url": "https://www.va.gov/north-florida-health-care/programs/covid-19-vaccines",
      "va_health_connect_phone": "877-741-3400"
    }
  }
}
```
- [x] Test the the pre COVID-19 status on the branch for 10708 (by checking out the commit before that af1119b03) and capture the JSON object prepared for lighthouse
```
{
{
  "nid": "1584",
  "uid": "facility_status_vha_573QK",
  "endpoint_path": "/services/va_facilities/v0/facilities/vha_573QK/cms-overlay",
  "payload": {
    "operating_status": {
      "code": "NORMAL",
      "additional_info": null,
      "supplemental_status": [
        {
          "id": "COVID_LOW",
          "label": "COVID-19 health protection: Levels low"
        }
      ]
    },
    "system": {
      "name": "VA North Florida/South Georgia health care",
      "url": "https://www.va.gov/north-florida-health-care",
      "covid_url": "https://www.va.gov/north-florida-health-care/programs/covid-19-vaccines",
      "va_health_connect_phone": "877-741-3400"
    }
  }
}
```
- [x] If these datasets are identical we are good
The comparison of the two pushes are identical.
![image](https://user-images.githubusercontent.com/5752113/229616351-9850a292-03a0-45a1-ac96-ae12c76433a8.png)

- [ ] ~If the dataset for 10708 is missing data or an error is thrown during generation we need to update our code to account for the changes made in the 10708 branch~

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [ ] `Public Websites`
- [x] `Facilities`
- [ ] `User support`

**Comment by omahane** [comment]
While we didn't capture the JSON pre-10708 (which would have been great), having reviewed the Facilities API and looking at the front-end, it doesn't appear to have caused any regression.

For example, West Plains VA Clinic status is set to High [on prod](https://staging.cms.va.gov/node/2077/edit) which is reflected [on the front end](https://www.va.gov/poplar-bluff-health-care/locations/west-plains-va-clinic/).

@swirtSJW Do you think there's any work here?

**Comment by swirtSJW** [comment]
I think we want to prove that a **recent** change on prod results in an appropriate change in the results of the Facility API.   Existing data will only change when the data changes, so checking that existing data works is not enough.  Have to look at recent changes.

**Comment by swirtSJW** [comment]
In either case, we are sending the same thing... just an id so nothing really changed there.  Should be low risk.... and the should is why a recent change needs testings.

**Comment by swirtSJW** [comment]
I was able to checkout before the changes were made (commit af1119b03) and make a save that would push data.    Then compare it to the push from the new code.  All is right.

**Comment by swirtSJW** [comment]
@kmariepat-cityfriends The proof that there are no deviations with the old code and the new code is this
![image](https://user-images.githubusercontent.com/5752113/230632810-65160423-fd47-4f41-8646-f3d13e51b8a3.png)

The code was released a while back.  Ideally this test should have been done before the code was released.  So it is kind of weird that we are doing this after the fact.  However, the good news is, there as not change (regression) to the data being sent to Lighthouse.
