### ISSUE TITLE
URL Change for Bainbridge VA Clinic renamed to Oneonta VA Clinic

### ISSUE THREAD

**Issue by stefaniefgray** [department-of-veterans-affairs/va.gov-cms#12406]
See original ticket: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12405

### Instructions
- This issue will be used from initial request through implementation to ensure all individuals working on this are notified of status updates.  Please do not create multiple issues to track different steps.
- It is your responsibility to notify VA stakeholders as appropriate.
- Be sure to link the related facility closure / rename issue.
- Front end redirects are tracked in the [devops](https://github.com/department-of-veterans-affairs/devops) repo in `ansible/deployment/config/revproxy-vagov/vars/redirects.yml`

### Instructions for URL redirect
(Note: This issue will be used from initial request through implementation to ensure all individuals working on this are notified of status updates.  Please do not create multiple issues to track different steps.)
- [x] Notify VA stakeholders as appropriate.
- [x] Link the related facility closure / rename issue.
- [x] Create a URL redirect in the [devops](https://github.com/department-of-veterans-affairs/devops) repo in `ansible/deployment/config/revproxy-vagov/vars/redirects.yml`
- [x]  Validate that the URL redirect is deployed. (Note: In the event of a facility closure or a name change,  validate that this occurs before making the Lighthouse csv changes.)

### Redirects 
| Current URL  |  Redirect Destination or New URL |
| ---  |  --- |
| https://www.va.gov/albany-health-care/locations/bainbridge-va-clinic | https://www.va.gov/albany-health-care/locations/oneonta-va-clinic |

#### Redirect PR:
https://github.com/department-of-veterans-affairs/devops/pull/12857

### Instructions for canonical URL change
- [x] Verify that the new URL for the facility is published and accessible on VA.gov.
- [x] Update the [CSV in Lighthouse](https://github.com/department-of-veterans-affairs/lighthouse-facilities/blob/master/facilities/src/main/resources/websites.csv) with the changed URL, maintaining the sorted order of the Facility API IDs.
- [x] Create a PR in the [lighthouse-facilities repo](https://github.com/department-of-veterans-affairs/lighthouse-facilities), tagging the Lighthouse team.
- [x] Post a message in the #api-facilities channel in Slack, with an @mention to a Lighthouse team member.
- [x] Validate that the change has deployed by checking that the Facility Locator has been updated with the new url.

### URL change 
| Facility API ID  |  Full VA.gov URL |
| ---  |  --- |
| vha_528G3 | https://www.va.gov/albany-health-care/locations/oneonta-va-clinic/ |

### Implementation date
When does this request need to be live: Once the facility name-change has been updated within VAST

### Team
Please check the team(s) that will do this work.

- [x] `Facilities`
- [x] `User support`

**Comment by omahane** [comment]
Confirmed that https://www.va.gov/find-locations/facility/vha_528G3 is available:
<img width="2036" alt="Screen Shot 2023-04-17 at 8 23 57 AM" src="https://user-images.githubusercontent.com/766573/232497157-c19126c8-4ed4-4057-9e54-a9b68cc21d14.png">

**Comment by omahane** [comment]
@stefaniefgray The change has been deployed.
![Screen Shot 2023-04-20 at 3 56 32 PM](https://user-images.githubusercontent.com/766573/233486199-64d1bd5a-307c-4cf0-a38b-af70568ea602.png)
