### ISSUE TITLE
IncLim: Set up new app on vets-api for dummy data

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#12402]
## Description

We are setting up the API, but remain agnostic regarding where the data itself will be coming from (pending Platform verifying connect-ability to Oracle DB).

Most recent API design: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12584#issuecomment-1446629888

- Initiate the app
- Set up route
- See platform docs re error handling setup (if not auto-generated)

### Resources

- See Platform docs about how apps should be set up

## Acceptance Criteria
- [ ] Find Platform documentation
- [ ] Create new application folder in vets-api repo: `modules` folder
- [ ] API responds to request at new endpoint `https://api.va.gov/income_limits/{version}/limitsByZipCode/{zip}/{year}/{dependents}` with sample data
  - [ ] sample data is the json object in [comment](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12249#issuecomment-1406818162) 

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [x] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`

**Comment by jilladams** [comment]
Notes: 
1. Max is also starting work on a Ruby / vets-api piece of work for Fac in S81
2. 8 represents some ambiguity with vets-api setup. Make use of Max's learning as much as we can, since he has a head start.

**Comment by jilladams** [comment]
Something that hadn't really occurred to me til I saw Josh's PR here is that we're now actually supporting a versioned API. We should talk sometime about expectations for versioning / support / deprecation, etc. Right now we'll be our own consumers, so it doesn't matter much, but: that won't be always. I don't think VA has rigorous rules or enforcement around this, but we should have our own best practices figured out anyway. It'll save trouble in the long run. @wesrowe

**Comment by wesrowe** [comment]
if Josh set it up as /v0/etc then we are up to OCTO-DE standards afaik. We just saw that Search is still on v0...
