### ISSUE TITLE
VAMC Facility name change: Yakima VA Clinic is now Yakima Valley VA Clinic

### ISSUE THREAD

**Issue by stefaniefgray** [department-of-veterans-affairs/va.gov-cms#12400]
## Intake
- [x] Submitter: Linda Wondra, VA Walla Walla, via https://va-gov.atlassian.net/browse/VAHELP-5354
- [x] If the submitter is an editor, send them the link to the CMS Knowledge Base (KB) article on facility basic data for their product (VAMC or Vet Center). Let them know that facility changes can take between 75 days and 4 months after submitting a request, according to VAST administrators.
- [ ] If the change is a facility closure, send the editor a link to the operating status KB article and have them change the status to Facility notice and provide a description of the facility closure so that Veterans are aware of the future closure.
- [ ] Other stakeholders to include on updates, if any: <insert name>

**Link on production:** https://www.va.gov/walla-walla-health-care/locations/yakima-va-clinic/

**Acceptance criteria:** All instances/mentions of the "Yakima VA Clinic" are updated to say "Yakima Valley VA Clinic"

**Redirect request:** https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12401

## VAMC Facility name change

- [x] The title change comes from Lighthouse to Drupal.
- [x] Coordinate with Facilities team to create a [redirect request](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/new?assignees=&labels=Redirect+request&template=redirect-request-facility-url.md&title=Redirect+Request+for%3A+%3Cinsert+facility+name%3E)
- [x] CMS engineer locates the newly renamed VAMC Facility (https://prod.cms.va.gov/admin/content/bulk) Search by new name
- [x] CMS engineer updates URL alias for this facility
- [x] CMS engineer resaves this facility
- [x] CMS engineer makes bulk alias changes to facility service nodes. (https://prod.cms.va.gov/admin/content/bulk?type=health_care_local_health_service)
- [x] CMS engineer bulk saves fixed titles to facility service nodes. (https://prod.cms.va.gov/admin/content/bulk?type=health_care_local_health_service)
- [x] CMS engineer updates menu title for facility
- [x] CMS engineer may also need to directly edit the VAMC System menu to alpha sort the menu item after the title changes
- [x] CMS engineer updates Alt text for facility image, if relevant
- [x] CMS engineer updates Meta description (TBD: some backwards compatibility for SEM, by including something like ", formerly known as [previous name]".
- [x] CMS engineer edit facility node and remove flag `Changed name` then save node
- [ ] HD notifies editor and any other stakeholders
</details>

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [ ] `Public Websites`
- [x] `Facilities`
- [x] `User support`

**Comment by stefaniefgray** [comment]
Redirect request ticket: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12401

**Comment by JayDarnell** [comment]
A PR for the redirect request has been created: https://github.com/department-of-veterans-affairs/devops/pull/12517

Redirects typically go out on Wednesdays so we should revisit this Thursday, February 9th. (cc @stefaniefgray )

**Comment by JayDarnell** [comment]
Dev work on this is done @stefaniefgray - just waiting on content release to reflect the changes on the front end.
