### ISSUE TITLE
Connect IncLim API to DB and Implement endpoint

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#12404]
## Description

Get endpoint created with dummy data working with real database connection, #12402.

## Acceptance Criteria
- [ ] A request with valid year, zip, & dependents returns JSON in the expected shape per [API design](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12249#issuecomment-1406818162)
- [ ] API documentation is available via the vets-api Swagger page

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [x] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`

**Comment by jilladams** [comment]
Not refinable until we make the connection.

**Comment by wesrowe** [comment]
closing as dupe
