### ISSUE TITLE
Redirect Request for Yakima VA Clinic name change to Yakima Valley VA Clinic

### ISSUE THREAD

**Issue by stefaniefgray** [department-of-veterans-affairs/va.gov-cms#12401]
See linked issue https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12400

### Instructions
- This issue will be used from initial request through implementation to ensure all individuals working on this are notified of status updates.  Please do not create multiple issues to track different steps.
- It is your responsibility to notify VA stakeholders as appropriate.
- Be sure to link the related facility closure / rename issue.
- Front end redirects are tracked in the [devops](https://github.com/department-of-veterans-affairs/devops) repo in `ansible/deployment/config/revproxy-vagov/vars/redirects.yml`

### Implementation date
When does this request need to be live: As soon as possible

### Redirects 
| Current URL  |  Redirect Destination or New URL |
| ---  |  --- |
| https://www.va.gov/walla-walla-health-care/locations/yakima-va-clinic/ | https://www.va.gov/walla-walla-health-care/locations/yakima-valley-va-clinic/ |

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [ ] `Public Websites`
- [x] `Facilities`
- [x] `User support`

**Comment by JayDarnell** [comment]
Redirect request was merged today. I'll check back to be sure it went to production Wednesday.

**Comment by stefaniefgray** [comment]
**Yakima link on prod:** 
- https://prod.cms.va.gov/walla-walla-health-care/locations/yakima-va-clinic

**The following live VA.gov links were reported as broken by Yakima earlier today:**
- https://va.gov/walla-walla-health-care/locations/yakima-va-clinic
- https://va.gov/walla-walla-health-care/locations/yakima-valley-va-clinic 

@JayDarnell Bad news -- there might've been an issue with the re-direct :(
