### ISSUE TITLE
VAMC Facility name change: Bainbridge VA Clinic is now Oneonta VA Clinic [Ready to go]

### ISSUE THREAD

**Issue by stefaniefgray** [department-of-veterans-affairs/va.gov-cms#12405]
## Intake
- [x] What triggered this runbook? (Flag in CMS, Help desk ticket, Product team, VHA Digital Media)
Trigger: Help desk ticket
- [x] Link to associated help desk ticket (if applicable)
Help desk ticket: https://va-gov.atlassian.net/browse/VAHELP-5322
- [x] Name of submitter (if applicable)
Submitter: Peter Potter
- [x] If the submitter is an editor, send them links to any relevate KB articles for the VAMC product. Let them know that facility changes can take between 75 days and 4 months after submitting a request, according to VAST administrators.
KB articles: 
https://prod.cms.va.gov/help/vamc/how-do-i-update-my-vamc-facilitys-basic-location-data
**4/14:** the Helpdesk thread has crazy email footer emoji so I'm struggling, but I don't see that we've shared the helpdesk article re: requesting VAST update was shared. 
- [x] Link to facility in production:
Facility link: https://prod.cms.va.gov/albany-health-care/locations/bainbridge-va-clinic
**Facility locator entry:** https://www.va.gov/find-locations/facility/vha_528G3

## Acceptance criteria

- [ ]  Bainbridge VA Clinic is updated to Oneonta VA Clinic across all headers, menu links, breadcrumbs, etc.

#### CMS help desk steps
What happens: The name change is made in VAST, that syncs to Lighthouse which syncs to Drupal.
- [x] 1. Check that the title change in name field on the VACM node has shown up in Drupal.
- [x] 2. Create a [URL change request](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/new?assignees=&template=runbook-facility-url-change.md&title=URL+Change+for%3A+%3Cinsert+facility+name%3E), changing the entry from the old facility URL to the new facility URL. (**Note: The URL change request ticket blocks the completion of this ticket.**)

https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12406

(Redirects deploy weekly on Wed. at 10am ET, or by requesting OOB deploy (of the revproxy job to prod) in #vfs-platform-support. Coordinate the following items below and canonical URL change after URL change ticket is merged, deployed, and verified in prod.)

#### CMS engineer steps
- [x] 3. Execute the steps of the URL change request ticket from step 2.
- [x] 4. Locate the newly renamed VAMC Facility (https://prod.cms.va.gov/admin/content/bulk) Search by new name
- [x] 5. Updates URL alias for this facility
- [x] 6. Resave this facility
- [x] 7. Make bulk alias changes to facility service nodes. (https://prod.cms.va.gov/admin/content/bulk?type=health_care_local_health_service)
- [x] 8. Bulk save fixed titles to facility service nodes. (https://prod.cms.va.gov/admin/content/bulk?type=health_care_local_health_service)
- [x] 9. Update menu title for facility
- [x] 10. May also need to directly edit the VAMC System menu to alpha sort the menu item after the title changes
- [x] 11. Update Alt text for facility image, if relevant
- [x] 12. Update Meta description (TBD: some backwards compatibility for SEM, by including something like ", formerly known as [previous name]".
- [x] 13. Edit facility node and remove flag `Changed name` then save node (with moderation state = published)

#### CMS Help desk (wrap up)
- [ ] 14. Notify editor and any other stakeholders

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [ ] `Public Websites`
- [x] `Facilities`
- [x] `User support`

**Comment by stefaniefgray** [comment]
Name change has not come into Drupal yet: https://prod.cms.va.gov/albany-health-care/locations/bainbridge-va-clinic

**Comment by stefaniefgray** [comment]
Blocked until VAST updates

Waiting for VAST to update this clinic: https://prod.cms.va.gov/albany-health-care/locations/bainbridge-va-clinic

Once the header says Oneonta, can proceed

**Comment by stefaniefgray** [comment]
Still blocked as 3/10/23

**Comment by stefaniefgray** [comment]
Still blocked as of 3/10/23

**Comment by stefaniefgray** [comment]
@kmariepat-cityfriends @jilladams @omahane This is the one the editor mentioned a White House inquiry about -- and VAST has finally updated, so it's ready to go! Can we please prioritize this?

Re-direct request: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12406

**Comment by kmariepat-cityfriends** [comment]
DEV help should be timeboxed to a 1

**Comment by stefaniefgray** [comment]
Meet with @omahane 
- We'll have to make the CMS change Weds. morning directly before the re-direct URL gets deployed at 10 AM Eastern
- The timing is so that the redirect request launch and content release process are as timed with one another as closely as possible

**To do Wednesday morning 4/17/2023:**
- Gather up Christian/Troy/Stefanie to go through steps together
- Meeting planned for 10 AM Eastern to pull the switches altogether as a team

**Comment by jilladams** [comment]
Note that 10AM ET assumes all goes well. You'll be able to see here if/when the prod deploy job completes successfully: http://jenkins.vfs.va.gov/job/deploys/job/revproxy-vagov-prod/

**Comment by omahane** [comment]
@stefaniefgray 
The Facility Locator change has been made, see #12406 .

Please inform the editors and other stakeholders.

**Comment by stefaniefgray** [comment]
Informed editor in https://va-gov.atlassian.net/browse/VAHELP-5322

Closing! Great job, team 🚀
