### ISSUE TITLE
Catch up with Benefits content model conversations / artifacts

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#12408]
On return from Ecuador, Christia to review modern state of Benefits content model hardening, to get ready for next steps in Drupal. 

## Acceptance criteria

- [ ] Review any notes in #9313
- [x] Watch content model meeting from 2/13: 
    * https://us06web.zoom.us/rec/share/tKLFkjlEY0FWgp_RYtbx9QEINhAXPS5C7JCfv5UMiRQ0vnP9_T695QG1jYVI2VXb.5OHyAgquHd5zgdNH
    * Passcode: G#9QrHYH
- [x] Schedule time with @wesrowe to review state of Airtable / updates and any takeaways

**Comment by jilladams** [comment]
This was incorrectly added to S77 -- should be in S78 for when Christia returns for PTO. Moved.

**Comment by jilladams** [comment]
@wesrowe updating ACs here to add watching the recording from the How to Apply meeting. Not sure if there are other bits I'm forgetting that Christia should ramp up on, when she returns.

**Comment by chri5tia** [comment]
Scheduling with Dave instead of Wes :)

**Comment by chri5tia** [comment]
Dave's spreadsheet. https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12423
