### ISSUE TITLE
Create recurrent editorial survey for measuring trust with the CMS

### ISSUE THREAD

**Issue by EWashb** [department-of-veterans-affairs/va.gov-cms#12410]
## Background

As we explore feedback loops and baseline health metrics for the CMS, we must define and evaluate what trust looks like for editors. Trust as a metric is crucial to understanding the overall health of the CMS. We want to understand the editor's trust level so we might understand tasks/experiences they are having problems with and determine ways the CMS Team can help them through various improvements within product initiatives. 

This survey should go out at least once per quarter but more often if deemed necessary. It should also go out to all editors of the CMS. We will want to create a frequency with similar questions. The midpoint of the quarter might be next, possibly every 5th sprint. 

 **How can we measure editor understanding of the separation of content from display?**

Questions we might want to ask and explore include:
- How confident are you creating content (plain language/ for va.gov? 
- How confident are you when you reach out to the help desk, that I'll get help promptly?
- What problems are editors trying to solve, and what is the confidence level in those actions?
-  Are you confident creating alt text for images?

This is not an exhaustive list of questions; it is a jumping-off point and example of the types of things we would like to learn about as a CMS Team. However, the questions may change each time depending on specific topics we would like to aggregate data on.

## Hypothesis

- Baseline trust metrics for the CMS will allow product teams to build solutions that advance the mission of providing quality content to Veterans. 
- Editors' trust levels vary by product. 
- Editors are accustomed to surveys and will participate in a quarterly survey via email. 

## Acceptance Criteria

- [ ] A draft survey is created in Survey Monkey that measures trust in the CMS
- [ ] Survey is shared with PM

**Comment by joagnitti** [comment]
Doing some discovery work now!

**Comment by EWashb** [comment]
[EditorTrustSurvey_1.docx](https://github.com/department-of-veterans-affairs/va.gov-cms/files/10855517/EditorTrustSurvey_1.docx)

The survey will be emailed to Dave C for feedback and then distributed to editors.
