### ISSUE TITLE
Content design: Document BCM design spec for engineering

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#12423]
## Description

AS A Drupal engineer, 
I WANT a technical design document of the Benefit content model (BCM) 
SO THAT there is nothing ambiguous about the implementation requirements.

**AS A** PO or SWContent Editor
**I WANT** to see a detailed BCM MVP spec
**SO THAT** I can review the design before implementation

The MVP definition has been largely determined in a meeting on Feb 13, 2023.

## Acceptance Criteria
- [x] Draft document of content design suitable for sign-off and engineering (collab with @chri5tia ; consult Swirt and/or Daniel about format)
~~Document how design connects to schema.org markup in presentation layer (see #10240)~~ Not a content requirement, more an engineering issue. This should be a requirement for an eng ticket.
~~- [ ] Scheduled (Wes help) meeting to go over with Dave C and Danielle T~~ #12731 is now a blocker for the Dave / Danielle meeting, as schema.org outcomes may affect the set of suggested fields, so we want that data included before CMS collab cycle review & D/D meeting.

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [x] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`

**Comment by wesrowe** [comment]
@davidmpickett, I'm assigning this ticket to us for refining

**Comment by davidmpickett** [comment]
I'm still writing this comment - just saving since I already lost it once

# VA Benefit content type

## Benefit Name

- Official benefit name
- Plain language name
- Acronym (may not be MVP)

## Benefit relationships

- Benefit category (does this reuse the Related to / Benefits hub from VA Form?)

## About this benefit

## Eligibility

## How to Apply

## After you apply

# VA Form content type

## Existing fields to use

- FORM NUMBER
- FORM TITLE
- LINK TO FORM (pdf)
- Link to online tool (How to apply online)
- Benefits hub

## New fields
- How to apply by mail
- How to apply in person
- How to apply by phone
- How to apply by fax

**Comment by davidmpickett** [comment]
@wesrowe I need to put my head down on Facilities stuff for the next couple days, but here's a first stab at identifying the matrix of fields and field properties that would likely be needed for a full spec. Feel free to workshop it with techier minds

**Comment by davidmpickett** [comment]
I started working on the spec in Google docs for internal review: https://docs.google.com/spreadsheets/d/1gP6x-QLFRrJlLWdCEE1COAZXU-kRRmFKSc0sIlc_tyM/edit?usp=sharing

**Comment by davidmpickett** [comment]
Had some great coworking sessions today with @chri5tia and we fleshed out the columns for the spec. Should be pretty comprehensive of all the things we want to know about a field.

**Comment by jilladams** [comment]
@davidmpickett do you have a sense of where that puts this ticket? Are we ready for @wesrowe to schedule the meeting Dave & Danielle?

**Comment by davidmpickett** [comment]
@jilladams @wesrowe So the specification ended up have twice as many columns as I originally guesstimated. So we should probably chat about how much of this needs to be fully fleshed out, vs having some best guess and some clear conversation points. 16th minute in scrum tomorrow?

**Comment by davidmpickett** [comment]
PS - I also took this to Sitewide CMS Office Hours today and got some helpful feedback from @timcosgrove and others

**Comment by davidmpickett** [comment]
**My priorities**
- Only working on "VA Benefit Content type" tab for now, because we want to get some parts locked down that be copied to the "VA form content type" 
- Column B - makes sure that all the fields that this model needs are added
- Column D - "What is this field for?"
- Row 2 & Row 3

**Comment by davidmpickett** [comment]
Follow up work: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12736

**Comment by davidmpickett** [comment]
I have brain dumped my lingering thoughts into comments on the spreadsheet so I can pick them up again next sprint
