### ISSUE TITLE
Require revision logs for all content types

### ISSUE THREAD

**Issue by EWashb** [department-of-veterans-affairs/va.gov-cms#12449]
## Description

Similar to work completed in #4628, we need to require revision logs for all products. ~~VAMC editors. As a note, VAMC editors had required revision logs as part of their teamsite, but these requirements were not carried over to Drupal.~~

## User Story

As a CMS user ~~of VAMC products~~, I want meaningful revision histories that tell me what changed with each edit. 

As a CMS stakeholder, I would like to use the revision log to track compliance with VA Directive 6102.

## Acceptance Criteria
- [x] Artifact/document about content type audit. [Listed here](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12449#issuecomment-1432186892)
- [x] All node content types have a required Revision log field.
- [x] Hide the active disabled checkbox for "Create new revision" for VAMC and Vet Center editors
- [x] code auto publishes the latest draft of the KB

### Team
Please check the team(s) that will do this work.

- [x] `CMS Team`
- [ ] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`

**Comment by EWashb** [comment]
@swirtSJW looking forward to Sprint 78

**Comment by BlakeOrgan** [comment]
I added an AC to hide the active disabled checkbox for "Create new revision" for VAMC and Vet Center editors. It's unnecessary to have it there if there's no way for editors to change it and revision logs are required.

<img width="1470" alt="Screen Shot 2023-02-08 at 10 24 58 AM" src="https://user-images.githubusercontent.com/113871419/217597159-53d4d61f-c0a8-4acd-8103-8c512f94d22f.png">

**Comment by EWashb** [comment]
There may be some overlap between other content types used by VAMC (events, etc.) Would we want to look at requiring these for all users instead of just VAMC? We will want to hold this going live until CM is completed.

**Comment by swirtSJW** [comment]
@EWashb Here is the list of content types that currently have code requiring revision logs.

va_gov_vet_center/src/EventSubscriber/EntityEventSubscriber.php:

- Vet Center:   'node_vet_center_edit_form',
- Vet Center - Community Access Point:  'node_vet_center_cap_edit_form',
- Vet Center - Facility Service: 'node_vet_center_facility_health_servi_edit_form',
- Vet Center - Locations List: 'node_vet_center_locations_list_edit_form',
- Vet Center- Mobile Vet Center: 'node_vet_center_mobile_vet_center_edit_form',
- Vet Center - Outstation: 'node_vet_center_outstation_edit_form',

va_gov_banner/src/EventSubscriber/EntityEventSubscriber.php:
- Full Width Alert: node_banner_edit_form

**Comment by swirtSJW** [comment]
Ran into this little snag.  https://github.com/department-of-veterans-affairs/va.gov-cms/issues/5390
There is code That fixes this but only for vet centers.  I need to make it generic enough to work for all others that are using inline entity forms.

**Comment by swirtSJW** [comment]
@EWashb The PR for this is passing all tests
![image](https://user-images.githubusercontent.com/5752113/220400590-61676d58-7294-4f97-8e70-9965e271199e.png)

and has been approved by reviewers 
![image](https://user-images.githubusercontent.com/5752113/220400750-697a4a5e-dada-439c-8be5-3f258de74899.png)


I'll let you decide how you want to handle this issue as far as calling it done before the PR is merged since merging is contingent on comms.

**Comment by swirtSJW** [comment]
Closed since the work is done and we are waiting on external team, VHA Digital Media to role out.
