### ISSUE TITLE
Create KB article for Emergency Situations

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#12451]
## Description
It was noted by Dave C that there is no one-stop-shop KB article for editors regarding what to do in emergency situations (i.e. How do they alert Veterans if their location is closed for a hurricane?). We should create this missing article.

### Additional notes

- What is considered an "emergency situation"? In what cases would an editor use or be directed to this article?
- Other related GitHub KB tickets:
  - #7978
  - #8555
  - #9291
  - #10346
  - #10433
  - #10496
- [Relevant JIRA ticket](https://va-gov.atlassian.net/browse/VAHELP-4878)

## Acceptance Criteria
- [x] Draft article is written
- [x] Article is reviewed by CMS team
- [ ] New article is published

**Comment by stefaniefgray** [comment]
Draft https://docs.google.com/document/d/1F2ZEpE_omdyJSKUYYsQGtDSmt9pDLtJ9vcRU3SpfKSM/edit?usp=sharing

Ready for review @laflannery @TroyA6

**Comment by stefaniefgray** [comment]
https://prod.cms.va.gov/help/cms-basics/resources-for-emergency-situations

Need to plug Google Docs content into draft node once approved

**Comment by stefaniefgray** [comment]
Added to Sprint 78 demo for 2/28/2023 in Confluence since it can probably be marked as Done for this sprint (once I've stuffed all of the bullet points into Drupal and gotten them to cooperate, lol)

**Comment by stefaniefgray** [comment]
<img width="1279" alt="Screen Shot 2023-02-17 at 6 59 02 PM" src="https://user-images.githubusercontent.com/9059428/219826262-a909686b-92e3-4192-a446-8d9f4227e6b1.png">

Also, this is what it looks like when you use the "Link Teasers" feature, and I wasn't a fan so I switched to rich text

**Comment by laflannery** [comment]
@TroyA6 do you want to review this before I publish? https://prod.cms.va.gov/help/cms-basics/resources-for-emergency-situations

**Comment by TroyA6** [comment]
@laflannery  - This looks good to me - Please publish when ready!

**Comment by laflannery** [comment]
Published!
