### ISSUE TITLE
URL change for fredericksburg

### ISSUE THREAD

**Issue by stefaniefgray** [department-of-veterans-affairs/va.gov-cms#12509]
Closed by https://github.com/department-of-veterans-affairs/lighthouse-facilities/pull/430

### Instructions
- This issue will be used from initial request through implementation to ensure all individuals working on this are notified of status updates.  Please do not create multiple issues to track different steps.
- It is your responsibility to notify VA stakeholders as appropriate.
- Be sure to link the related facility closure / rename issue.
- Front end redirects are tracked in the [devops](https://github.com/department-of-veterans-affairs/devops) repo in `ansible/deployment/config/revproxy-vagov/vars/redirects.yml`

### Acceptance Criteria 
- [x] I expect the canonical URL is updated and put on a PR 
- [x] I expect lighthouse is notified of this PR to ultimately push the changes 

### Implementation date
When does this request need to be live: When clinic homepage is re-published (see https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12508 for details)

### Redirects 
| Current URL  |  Redirect Destination or New URL |
| ---  |  --- |
| https://www.va.gov/find-locations/facility/vha_652GA | https://www.va.gov/richmond-health-care/locations/fredericksburg-va-clinic |

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [ ] `Public Websites`
- [x] `Facilities`
- [x] `User support`

**Comment by omahane** [comment]
This PR has been created: https://github.com/department-of-veterans-affairs/lighthouse-facilities/pull/430

**Comment by omahane** [comment]
@TroyA6 This center is now available in the Facility Locator:
<img width="1840" alt="Screen Shot 2023-03-24 at 9 22 49 AM" src="https://user-images.githubusercontent.com/766573/227554224-a56d7666-89a2-4a7f-ad3f-50e12320a510.png">

**Comment by omahane** [comment]
@TroyA6 @stefaniefgray Can you sign off on this today if you see that it's complete?

**Comment by stefaniefgray** [comment]
@omahane @jilladams Looks good! Thanks for your help, Christian -- closing
