### ISSUE TITLE
Discovery: strategize how to identify and prioritize user research projects

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#12503]
## Description

As a user researcher, I want to be organized about how we find and prioritize user research projects so that I can maximize the value I deliver for Veterans.

As a PO, I want to have a flowing pipeline of user research projects so that I can prioritize new projects for implementation based on validated Veteran pain points.

## Notes area

List of baseball card fields that the PW team brainstormed at the on-site: 
- Analytics - how many unique Veterans use this product per week?
  - Does it have a dashboard in Domo?
  - How well are key interactions covered in GA? (e.g., does each "Apply now" button in wizard have a unique tracking capability? or is there another proxy for paths through each branch of UI?)
- Definition of success (when first launched)
- Dependencies (systems, eg CMS)
- Stack / codebase / Drupal
- User characteristics (Veterans, caregivers, etc)
- Editors (if CMS product) 
  - who has permission, when last edited
- Last maintained / Maintenance mode
  - When was code last changed?
- Prerequisites [???]

## Acceptance Criteria
- [x] Drafted document outlining where could projects come from and how they can be prioritized
- [x] Discuss with some Ad Hoc researchers and a PM, Dave Pickett, and Wes
- [x] Discuss with Jill
- [x] Brainstorm what could glean from research repo about the Public Websites product portfolio for the "baseball cards" we discussed at the Onsite --> Excel spreadsheet
- [x] Make a list of potential research projects from the research insights that I've collected over the past 2 years
- [x] Compile list of potential research projects from [PS portfolio excel](https://dvagov-my.sharepoint.com/:x:/r/personal/wesley_rowe_va_gov/Documents/PW%20portfolio.xlsx?d=w2c8c26b2b1f0446ca786971396f14eb8&csf=1&web=1&e=782NQ6), research insights, and anywhere else
- [x] Begin populating columns in portfolio excel
- [x] Discuss WIP potential project prioritization with Wes and Jill

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [x] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`

**Comment by wesrowe** [comment]
@jilladams – FYI, an injection since Cindy has bandwidth

**Comment by wesrowe** [comment]
@cindymerrill, I had an idea for where to look for research ideas – would it be practical to search for what research was done for older products in our portfolio? Its outcomes (or non-existence) could provide ideas for research projects.

**Comment by cindymerrill** [comment]
Adding research findings to this spreadsheet of products in our portfolio: https://dvagov-my.sharepoint.com/:x:/r/personal/wesley_rowe_va_gov/Documents/PW%20portfolio.xlsx?d=w2c8c26b2b1f0446ca786971396f14eb8&csf=1&web=1&e=oD4VlO

**Comment by cindymerrill** [comment]
Finished filling in all the research columns in this [spreadsheet](https://dvagov-my.sharepoint.com/:x:/g/personal/wesley_rowe_va_gov/EbImjCzwsWxEp4aXE5bxTrgBduUNALgWIbD1RsoqraOtgA?e=thu8WE) about products in PW’s portfolio, plus some product outlines and one launch date.

**Comment by cindymerrill** [comment]
Drafted a list of potential research projects in a new “Research Pipeline” tab in this [spreadsheet](https://dvagov-my.sharepoint.com/:x:/g/personal/wesley_rowe_va_gov/EbImjCzwsWxEp4aXE5bxTrgBduUNALgWIbD1RsoqraOtgA?e=thu8WE), along with some columns that we could use to start to prioritize. Scheduled a meeting with Wes and Jill to discuss.

**Comment by jilladams** [comment]
@cindymerrill @wesrowe given that we want to hold off bringing this to Dave just yet, do we need to revise ACs / cut a separate ticket for remaining steps?

**Comment by cindymerrill** [comment]
Sure! And it could also involve training on Google Analytics for me so I can fill out more of the Portfolio worksheet, which will give us more data with which to prioritize.

**Comment by wesrowe** [comment]
I'm updating ACs and will cut a new/follow-up ticket

**Comment by wesrowe** [comment]
also removed the "high priority" tagging, no doubt it was added on accident by column change (@cindymerrill everyone makes this mistake at least twice, easier to demonstrate what happened than explain it here).

**Comment by wesrowe** [comment]
follow-up ticket written and added to Stretch: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12601. This can close
