### ISSUE TITLE
Facility Re-Opening: Fredericksburg VA Clinic (Previously archived)

### ISSUE THREAD

**Issue by stefaniefgray** [department-of-veterans-affairs/va.gov-cms#12508]
## Background
The Fredericksburg VA Clinic (VA Richmond) was archived in September 2021.

Per Jira tickets VAHELP-4906 and VAHELP-5452, the clinic is open once more, and the clinic homepage and linked health services must be published to the live site.

*What triggered this runbook?*
https://va-gov.atlassian.net/browse/VAHELP-4906
https://va-gov.atlassian.net/browse/VAHELP-5452

*1. Please attach Facility Locator link to this ticket*
https://www.va.gov/find-locations/facility/vha_652GA

**Facility Locator re-direct request link:** https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12509

*2. Please attach prod link to this ticket*
https://prod.cms.va.gov/richmond-health-care/locations/fredericksburg-va-clinic

*3. Please also include link to Jira help desk ticket, if applicable*
See above

## Acceptance criteria
- [ ] https://prod.cms.va.gov/richmond-health-care/locations/fredericksburg-va-clinic is published to the live site and is listed in the correct alphabetical order on the left-nav Locations menu
- [ ] The following 3 health services are re-published:
  - [ ] “[Mental Health Care](https://prod.cms.va.gov/richmond-health-care/locations/fredericksburg-va-clinic/mental-health-care)” 
  - [ ] “[Physical Therapy](https://prod.cms.va.gov/richmond-health-care/locations/fredericksburg-va-clinic/physical-therapy-occupational-therapy-and-kinesiotherapy)” 
  - [ ] “[Chiropractic](https://prod.cms.va.gov/richmond-health-care/locations/fredericksburg-va-clinic/chiropractic)” 
- [ ] notify lighthouse of the URL for the specific re-direct to clinic homepage
(Notes to let them know Facility Locator entry linked above re-directs to clinic homepage (may not be facilities AC, manual process into csv, lighthouse takes care of this)

### VAMC
Please refer to the Knowledge Base article titled "How do I add a facility to my health care system?" for more information: https://prod.cms.va.gov/help/vamc/about-locations-content-for-vamcs/how-do-i-add-a-facility-to-my-health-care-system

#### CMS help desk steps
- [x] 1. Become aware that the new facility is now on the Facility API (typically, via a Flag, but this may come in as a helpdesk ticket).
- [x] 2. If the editor has followed the steps from the above Knowledge Base article and included which section and VAMC the facility belongs to (i.e. VA Pittsburgh), great! **Proceed to step 3.** If not, please check with the editor or VHA digital media regarding what section and VAMC it belongs to.
- [x] 3. Updates the Section (default is "VAMC facilities", but it should be a VAMC system in a VISN) and VAMC system field accordingly.
- [x] 4. Communicate with editor (cc VHA Digital Media) to give them go-ahead to complete the content, with this [KB article](https://prod.cms.va.gov/help/vamc/about-locations-content-for-vamcs/how-do-i-add-a-facility-to-my-health-care-system).
- [x] 5. When editor has prepared content and let help desk know, reassign this issue to appropriate CMS engineer on Product Support team, for bulk publishing.

#### CMS engineer
- [x] 6. CMS engineer bulk publishes nodes and facility.
- [x] 7. CMS engineer edit facility node and remove `New facility` flag and save node.
- [ ] 8. Let help desk know this has been done.

#### CMS Help desk
- [ ] 9. HD notifies editor and any other stakeholders.

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [ ] `Public Websites`
- [x] `Facilities`
- [x] `User support`

**Comment by stefaniefgray** [comment]
@Dottisea @kmariepat-cityfriends This clinic is ready to go! 🚀 

Can we please push this forward? Thank you!

**Context:** Clinic was previously closed, is now open once more

**Comment by stefaniefgray** [comment]
@kmariepat-cityfriends @Dottisea Editor just wrote the following:

"Good morning, 

I am following up on this as I have not heard back from anyone and it has been 5 weeks and it appears the page has still not been published. Can I get an update and a potential timeline so our Veterans can know what care they can access at this CBOC?  

Thank you."

**Comment by kmariepat-cityfriends** [comment]
@stefaniefgray this is in our current sprint, I just marked it high priority to push it along, but with confidence it will be complete by end of sprint pending no unknowns or blockers surfacing

**Comment by kmariepat-cityfriends** [comment]
@stefaniefgray this is in our current sprint, I just marked it high priority to push it along, but with confidence it will be complete by end of sprint pending no unknowns or blockers surfacing

**Comment by omahane** [comment]
@stefaniefgray @TroyA6 This clinic and its services have been published.

**Comment by omahane** [comment]
Here's the link: https://www.va.gov/richmond-health-care/locations/fredericksburg-va-clinic/

**Comment by stefaniefgray** [comment]
Editor is notified in https://va-gov.atlassian.net/browse/VAHELP-5452

Closing! Thanks for all your help @omahane
