### ISSUE TITLE
Align content model with design system to make it easier for product teams to build products

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#1250]
## Problem statements

1. Product designers don't know what the CMS offers in terms of components and "building blocks" of content. 
1. Product designers come up with new variations on existing components, and we don't have the tools or documentation to steer product teams towards standardization. 
1. The existing design system and content style guide each document patterns supported by the content model, but the content model often goes "further" in depth by setting rules and guidelinesa bout where certain components and design patterns can be used in CMS manged products. 

### User Story

As a product designer, i can learn how components in the design system map to the content model and CMS. 

### Affected users and stakeholders

Mainly product designers, but also some content designers and editors who push at the "edges" of the CMS and content model. 

### Hypothesis

We believe that aligning content model documentation with content style guide and design system will 

1) help product teams build products faster by knowing what's already available to them in CMS
2) assist with the governance of the content model by facilitating conversations about when new variants are possible, and the tradeoff with technical debt. 

## Ideas for implementation

* Add content model documentation to various components and/or content style guide pages
* [more ideation needed, possibly with a design studio held in conjunction with the Design System Council]

**Comment by sandyisland1** [comment]
@kevwalsh : can we resolve this ticket?

**Comment by EWashb** [comment]
We've created our own CMS design system that is now available to all CMS product teams.
