### ISSUE TITLE
Update the default sort order of content in the outdated content report to be chronological or reverse chronological based on the filter chosen for Last Saved by an Editor 

### ISSUE THREAD

**Issue by BlakeOrgan** [department-of-veterans-affairs/va.gov-cms#12514]
## User Story or Problem Statement

As an editor, I need to view outdated content in the outdated content report in chronological or reverse chronological order based on my current filter, so that I can know which content is most/least outdated.

## Acceptance Criteria
- [ ] The default sort order of content listed in "All outdated content" is listed in order of content that is the most outdated to least outdated. 
- [ ] The default sort order of content listed in the Over 30/60/90 days overdue filters are also listed in order of content that is the most outdated to least outdated. 
- [ ] The default sort order of content listed in the Over 30/60/90 days until due filters are listed in order of content that will become outdated first.
- [ ] Users can change the default sort order between ascending/descending in the header row by clicking "Last Saved by an Editor" like how they can change the sort order of other columns in the outdated content report
- [ ] Requires design review
- [ ] Requires KB article update

## Design principles

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [x] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [x] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [x] `Empowering`: Provide clear information to help editors make decisions about their work.

### Team
Please check the team(s) that will do this work.

- [x] `CMS Team`
- [ ] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`

**Comment by BlakeOrgan** [comment]
Below is an example of how content in the outdated content report is not listed in order and an example of how users are able to currently sort other columns of the outdated content report and not the "Last Saved by an Editor" column.

<img width="1470" alt="Screen Shot 2023-02-07 at 10 42 16 AM" src="https://user-images.githubusercontent.com/113871419/217587714-93418ea0-92db-4a2d-82be-391a424eca70.png">

**Comment by EWashb** [comment]
@edmund-dunn @BlakeOrgan this was added to another PR, yes? Please confirm, and if so, have that PR linked to this ticket to close

**Comment by BlakeOrgan** [comment]
I believe it's this PR: https://github.com/department-of-veterans-affairs/va.gov-cms/pull/12547

**Comment by EWashb** [comment]
PR #12547 closes this ticket.
