### ISSUE TITLE
Get familiar with PW product portfolio

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#12527]
## Description

Top level docs: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/public-websites

## Acceptance Criteria
- [x] Review PW product docs to get familiar with product suite.
- [x] Update doc with any new notes / to fix broken links, or share feedback with Jill for necessary changes

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [X] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`

**Comment by thejordanwood** [comment]
Didn't have any updates to make for this. It was great to see our full product portfolio!
