### ISSUE TITLE
Redirect Request for closed Jacksonville Navy facility back to main VA North Florida / South Georgia system page

### ISSUE THREAD

**Issue by stefaniefgray** [department-of-veterans-affairs/va.gov-cms#12539]
### Instructions
- This issue will be used from initial request through implementation to ensure all individuals working on this are notified of status updates.  Please do not create multiple issues to track different steps.
- It is your responsibility to notify VA stakeholders as appropriate.
- Be sure to link the related facility closure / rename issue.
- Front end redirects are tracked in the [devops](https://github.com/department-of-veterans-affairs/devops) repo in `ansible/deployment/config/revproxy-vagov/vars/redirects.yml`

### Implementation date
When does this request need to be live:

### Acceptance Criteria 
- [x] I expect this has been removed from VAST (the current URL)
- [x] I expect va.gov executes a redirect as an outcome of this card 
- [x] I expect this is put in the devops repo

### Redirects 
| Current URL  |  Redirect Destination or New URL |
| ---  |  --- |
| https://www.va.gov/north-florida-health-care/locations/jacksonville-navy-va-medical-center | https://www.va.gov/north-florida-health-care/ |

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [ ] `Public Websites`
- [x] `Facilities`
- [x] `User support`

**Comment by kmariepat-cityfriends** [comment]
These are deployed once a week on Wednesdays, can request an out of band deploy (by the Platform group??)

**Comment by kmariepat-cityfriends** [comment]
@kmariepat-cityfriends to talk with @davidconlon about the approach for handling redirects

**Comment by kmariepat-cityfriends** [comment]
additional context on the server side vs client side debate on this card:

If server-side redirect: Revproxy build job must deploy the code: http://jenkins.vfs.va.gov/job/deploys/job/revproxy-vagov-prod/ -- this job only runs automatically on Wed at ~10am ET. (Job is owned by the Platform team. )
If you need offcycle deployment prior to Wed deploy: open a #vfs-platform-support request, Release Tools > Off-Cycle deployment. Example: https://dsva.slack.com/archives/CBU0KDSB1/p1664314493443639
If client-side redirect: vets-website deploys the code.

**Comment by JayDarnell** [comment]
The facility is marked as removed from source and a search in VAST shows that the facility no longer exists.

**Comment by JayDarnell** [comment]
A redirect request PR has been submitted and I have requested an off-cycle deployment here: https://dsva.slack.com/archives/CBU0KDSB1/p1677787195822869
