### ISSUE TITLE
Error when saving node with an error in the WYSIWYG

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#12556]
## Description
I was testing a specific error scenario (because I think it might be fixed in Drupal 10) but I ended up getting a scary error

These were my steps I used for what I was testing:

1. Edit a node, e.g. [VAMC System Health Service Whole health at VA Cincinnati health care](https://cms-pxuj8mm5h1fhqfidhiax67zm0v28bxf4.ci.cms.va.gov/node/24426/edit)
2. Insert a relative link containing a URL into a rich text field. For instance: <a href="/https://www.example.org/">Example Link!</a>.
3. Attempt to save the document.
4. I expected to see an error message at the top of the screen:
![Screen Shot 2023-02-01 at 11 00 38 AM](https://user-images.githubusercontent.com/1318579/216095983-f1e5553f-d72d-42b6-b588-2921a00b159d.png)
5. But instead I got this:
![image](https://user-images.githubusercontent.com/106678594/218125549-af85b036-b491-4304-a41a-7acc0364bb63.png)
(pasted below as plain text in case that's more helpful)

> The website encountered an unexpected error. Please try again later.
> 
> Drupal\Core\Entity\Query\QueryException: Entity queries must explicitly set whether the query should be access checked or not. See Drupal\Core\Entity\Query\QueryInterface::accessCheck(). in Drupal\Core\Entity\Query\Sql\Query->prepare() (line 141 of core/lib/Drupal/Core/Entity/Query/Sql/Query.php).

**Comment by ndouglas** [comment]
I've seen this before -- this is a quick fix.  I feel like this should actually be fixed already 🤔  Feel like it showed up at some point as a deprecation warning in Drupal 9.

**Comment by laflannery** [comment]
This same error is occurring when trying to edit a Vet center node: https://vacms-12252-drupal-10-cne7edu0najqzzmwjbq3awbbjcxb40w3.ci.cms.va.gov/node/3780/edit.  Not when I trying to save it after making a change like I did above, but trying to edit it originally.

**Comment by ndouglas** [comment]
Same!

**Comment by ndouglas** [comment]
I think these might all have the same underlying issue, @laflannery 

![Screen Shot 2023-02-10 at 1 22 19 PM](https://user-images.githubusercontent.com/1318579/218167866-e2b519ce-aeb4-4fd0-a1ae-a5c10e6c3267.png)

**Comment by laflannery** [comment]
No longer an issue, closing
