### ISSUE TITLE
Incorrect column widths on View nodes for content

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#12555]
## Description
When viewing nodes within the CMS, the columns widths are not the same size that they currently are in prod, see screenshots below

**Prod screenshot - 3 columns:**
![image](https://user-images.githubusercontent.com/106678594/218122923-f9f588bf-25c4-4575-ad42-04d66b867cbf.png)

**Drupal 10 screenshot - 3 columns:**
![image](https://user-images.githubusercontent.com/106678594/218122987-955a5fa2-cce2-4602-9bac-4480ea37bead.png)

**Prod screenshot - 2 columns:**
![image](https://user-images.githubusercontent.com/106678594/218123439-042307ff-877a-4efe-81f4-daa9e76c800c.png)

**Drupal 10 Screenshot - 3 columns:**
![image](https://user-images.githubusercontent.com/106678594/218123553-b7a6f18d-c902-43d5-8a73-9f117669c567.png)

**Comment by laflannery** [comment]
Update 2/15: This is now resolved. I feel like I shouldn't close it though because I don't know why it's resolved?

**Comment by laflannery** [comment]
Update 7/28 - this is unresolved, it's back to being different column widths than what is on prod

**Comment by edmund-dunn** [comment]
Reviewed with @laflannery and this has already been fixed.
