### ISSUE TITLE
Tooltips not working

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#12560]
## Description
**Updated 7/27**

One type of tool tip is only sort of working, this tool tip can be found on VAMC Facility pages, example: https://vacms-12252-drupal-10-cne7edu0najqzzmwjbq3awbbjcxb40w3.ci.cms.va.gov/north-texas-health-care/locations/polk-street-va-clinic
- These tooltips work if I hover and wait a second, but the display of the tip is much different than it currently is on prod.
- Prod screenshot:
![image](https://user-images.githubusercontent.com/106678594/218137236-e655e8ab-f83a-48e6-ae40-ceac50ba01c3.png)
- Drupal 10 screenshot: I can't do this apparently, whenever I try to screenshot the tip goes away
  - The tip doesn't work at all when I focus.
  - I see no console errors appearing when I try to activate this type of tool tip either

### Original Description (no longer applicable)

~~The tooltips are not working, when I hover over them or focus on them, the info does not appear and show me what the tip actually is. There are 2 types of tooltips:~~

- ~~The first type can be found on Benefits Details pages.~~ 
  - ~~It should look like this:~~
![image](https://user-images.githubusercontent.com/106678594/218135971-e39812fa-95a3-4ab4-8695-137b8c94bdcb.png)
  - ~~But instead a JS error is appearing in the console each time I try to activate this:
![image](https://user-images.githubusercontent.com/106678594/218136147-8e79f3bf-28de-4a80-89f3-ca03d96e2c34.png)~~

**Comment by laflannery** [comment]
I think this is related - If I hover over the Content release icon in the top right corner of the main admin toolbar I see the title of the element, not the tooltip I'm supposed to (I can't screenshot what I see, the screenshot won't capture it)

**What I should see:**
![image](https://user-images.githubusercontent.com/106678594/218204559-a649acb1-c84c-4dc9-9c43-ec73baf467f1.png)

**Comment by laflannery** [comment]
From a11y testing - I confirmed that this issue only partly still exists - I updated the description and the comment to accurately reflect what I am seeing now

**Comment by productmike** [comment]
Closing

**Comment by edmund-dunn** [comment]
Duplicates #14538. Issue fixed and merged.
