### ISSUE TITLE
Link widget in CKEditor does not make node suggestions

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#12564]
## Description
When I try to create a link in a Rich text field to an existing node, I usually start typing in the title of the page I want to link to and then I will get a bunch of suggested existing nodes.  However, this is not currently happening in Drupal 10.

**Prod:**
![image](https://user-images.githubusercontent.com/106678594/218159143-2383289d-bec1-47a1-9901-17e1c0ea5cf7.png)

**Drupal 10:**
![image](https://user-images.githubusercontent.com/106678594/218159051-a9981096-75b3-49aa-9102-373cd27fe315.png)

**Comment by EWashb** [comment]
Should we double check this before #8308 ?

**Comment by EWashb** [comment]
@laflannery if you feel strongly about it, let's make sure to get this in the requirements gathering pipeline!

**Comment by laflannery** [comment]
@EWashb I think this goes to what was talked about at the big D10 meeting the other day with the "neutral or better" standard. To me this is a worse experience because editors now need to know the exact node URL of the page they want to link to, however I am not the decider of things lol

I also don't know how I would get this into that pipeline you speak of - does @productmike know?

**Comment by EWashb** [comment]
I'll move it to the right pipeline! And I agree with you about further discussion needed with @productmike

**Comment by EWashb** [comment]
I actually went ahead and put it into pre-finement because this is a higher priority for the D10 release. I hope that was the correct spot.

**Comment by productmike** [comment]
@laflannery Is your request basically to keep Linkit enabled as current? And if not possible, how might we find ways to shoehorn the functionality into D10?

**Comment by laflannery** [comment]
@productmike yes, I believe Linkit can be enabled, you just need to go flip it on (not sure why it went off?)

**Comment by productmike** [comment]
10-4 and good news. Thanks

**Comment by edmund-dunn** [comment]
This has already been fixed.
