### ISSUE TITLE
Placement of sticky CKEditor header

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#12561]
## Description
When the CKEditor header goes sticky, it's placed oddly:
![image](https://user-images.githubusercontent.com/106678594/218150752-666e766f-5c99-4431-8e78-dc954073939f.png)

The main nav is now in between the CKEditor toolbar and the editor itself which could cause some confusion

**Comment by laflannery** [comment]
I just ran into this again and it's not happening everywhere - it seems this might only be an issue when the rich texter editor is inside a main content panel, where you add content blocks, like this: https://vacms-12252-drupal-10-cne7edu0najqzzmwjbq3awbbjcxb40w3.ci.cms.va.gov/node/3014/edit (the accordions are sticking and being weird). But doesn't happen in a regular old place like an event: https://vacms-12252-drupal-10-cne7edu0najqzzmwjbq3awbbjcxb40w3.ci.cms.va.gov/node/53375/edit

**Comment by laflannery** [comment]
This is still happening but only when I am clicked into the particular editor does the toolbar attempt to go sticky and then this weird display happen

**Comment by edmund-dunn** [comment]
This has been fixed.
