### ISSUE TITLE
CKEditor Style dropdown has incorrect options

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#12562]
## Description
In the Full Rich text editor, there is a Styles dropdown.  Current in Prod there is only 1 option for an Address block.  In Drupal 10, the addres block style is display but there are also multiple text styles showing as well (I was on the Create Story node fyi)

**Prod:**
![image](https://user-images.githubusercontent.com/106678594/218157915-d591e773-f9ff-452d-b1e9-0580ee516cc0.png)

**Drupal 10:**
![image](https://user-images.githubusercontent.com/106678594/218157980-5805f19f-1eab-4ce6-80b5-705293b96be4.png)

**Comment by laflannery** [comment]
I've also noticed that on existing content, it doesn't seem like I can add styles, the option is disabled:
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/106678594/c43c5e1d-d005-4da6-82c1-72b6fd071486)

**Comment by EWashb** [comment]
I suggest not allowing editors additional style options they are unfamiliar with. The current mental model for editors does not include additional styles and I'm concerned we will do a disservice without proper change management and training updates with these additional options.

**Comment by laflannery** [comment]
### Address Block:
- Present in both prod and D10
- Displays on the view screen in D10 correctly
- **Does NOT display at all on the edit screen in D10.** This is a problem because the editor is not going to be able to tell if they actually applied the style or not.
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/106678594/1f3fb511-fdf1-4a63-87d3-1842045fa9b5)

### Link styles
- These styles are all present in Prod, it's the fact that they do not show up until they can be used that was throwing us all off.
   - Link styles are only allowed to be used on links, not plain text. Therefore, unless the editor has a link highlighted, we couldn't see these particular styles:
   - Typical PROD style dropdown: 
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/106678594/6fd0b2f6-e23f-4c26-a497-294c4537ab1c)
   - PROD Style dropdown when I highlight a link (notice the link I have highlighted to the left): 
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/106678594/5c5880b3-5b66-460d-97ca-20eddf5df796)
   - In D10 the same thing happens it's just that the styles are disabled until a link is highlighted rather then completely gone.
- All styles display on the view screen in D10. The styles are not exactly matching the DS however:
  - The CMS Styles have a Default (Blue) and Primary (Green) button however the [DS components](https://design.va.gov/components/button/) don't have this so I think we should investigate if this should be here (there is a chance the CAIA team have these for reasons?)
  - The Secondary button in the DS components has a hover style of a slight blue hue, but the secondary button in the CMS Styles does not have this and instead turns black. This should ideally be adjusted.
- **Does NOT display at all on the edit screen in D10.** This is a problem because the editor is not going to be able to tell if they actually applied the style or not.
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/106678594/d9bbe8b3-139c-49a0-b4d9-24404849804e)


### Next steps
After realizing that this is not actually introducing new functionality to the CKEditor, I think next steps should be:
- Edmund: Fix the issue with the styles not showing on the edit screen, this does not meet the "neutral or better" bar we are trying to hit.
- Laura: Investigate with CAIA/DST if the green button should be available in the styles and remove if not
- Laura: Update this [KB article](https://prod.cms.va.gov/help/cms-basics/how-to-use-the-rich-text-editor) and replace the "Address Block" section with a more robust "Styles" section to explain what these are, why/when they should be used and why they are sometimes disabled.

@EWashb Let me know if this all makes sense to you or if you have any changes/additions to how we want to handle these styles.

**Comment by EWashb** [comment]
Thank you @laflannery for investigating this. I agree with you about the interim fix to make sure the styles are showing on the edit screen. 

I also agree with you that it is work a chat with CAIA/DST regarding those styles since this is one of the areas that does affect the FE presentation. We can even chunk out that work to another ticket.

**Comment by laflannery** [comment]
Thanks @EWashb!

@edmund-dunn We need to resolve the issue with styles not displaying properly on the edit screen. Please let me know if you would like to close this ticket and have me open a new one for that task (for the sake of organization)

I will also be opening new tickets for my pieces of this. I will link them here when they have been created

**Comment by laflannery** [comment]
Closing this issue in favor of the 2 above
