### ISSUE TITLE
Covid Merge and Deploy

### ISSUE THREAD

**Issue by Dottisea** [department-of-veterans-affairs/va.gov-cms#12572]
Once the change mgt plan for the covid status is ready we will know when to deploy code changes created in tickets #12217, #10708, #12570 so the feature is live for Veterans and editors to use.

AC: 
[x ] New covid capabilities related to this work are working in production
[ x] KB Article has been update before or in sync with this action (dependency)

Note - Run bulk update so WYSIWYG changes are captured

**Comment by Dottisea** [comment]
Verbiahe is here:https://prod.cms.va.gov/lovell-federal-health-care-va/vamc-banner-alert/2023-01-30/website-coming-soon-not-the-official-lovell-federal-health-care-website

**Comment by omahane** [comment]
@Dottisea 
You can see the new, customized status information here:
https://www.va.gov/long-beach-health-care/locations/tibor-rubin-va-medical-center/
And the KB article describing how to edit it here:
https://prod.cms.va.gov/help/vamc/about-locations-content-for-vamcs/about-alerts-and-operating-statuses/how-to-edit-covid-19-status-for-a-vamc-facility

I think we are good to close this issue.
