### ISSUE TITLE
Mismatched Facility Locator ID: San Antonio-Pecan Valley VA Clinic

### ISSUE THREAD

**Issue by stefaniefgray** [department-of-veterans-affairs/va.gov-cms#12576]
## Description
The San Antonio-Pecan Valley VA Clinic is being [flagged](https://prod.cms.va.gov/admin/content/flagged) as “Removed from source." However, the clinic is still open and operational.

The problem is that the address for this facility changed, and in turn, there are mismatched Facility Locator ID entries between the clinic homepage within the CMS, and on the Facility Locator lookup tool.

**Summary:** The former Facility Locator ID for this clinic `vha_671GK03` needs to be swapped out for the current ID `vha_671GU`

------

**Prod link:** https://prod.cms.va.gov/south-texas-health-care/locations/san-antonio-pecan-valley-va-clinic

**Old street address:** 
4243 East Southcross Boulevard, Suite 204, San Antonio, TX 78222-3750 (Currently listed on clinic homepage

**New street address:** 
3418 East Southcross Boulevard, San Antonio, TX 78223-1633? 
^^ This is the address currently listed on the Facility Locator: https://www.va.gov/find-locations/facility/vha_671GU 

**Current Facility Locator entry:** `vha_671GU` (See direct link above)

**Non-existent Facility Locator entry listed on clinic homepage:** `vha_671GK03`
^^ If you try to go to the following URL, it does not work: https://www.va.gov/find-locations/facility/vha_671GK03 

## Acceptance Criteria
- [ ] Old Facility Locator ID for this clinic `vha_671GK03` is swapped out for current Facility Locator ID `vha_671GU`
- [ ] Clinic homepage updates as intended, with current street address listed
- [ ] "Removed from source" flag is removed for this location on Flagged Content view

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [ ] `Public Websites`
- [x] `Facilities`
- [x] `User support`

**Comment by omahane** [comment]
@swirtSJW This makes me think we should have a runbook for facility address change. What do you think?

**Comment by stefaniefgray** [comment]
Node 1 (Original): https://prod.cms.va.gov/south-texas-health-care/locations/san-antonio-pecan-valley-va-clinic
Facility Locator ID: vha_671GK03

Node 2 (New): 
https://prod.cms.va.gov/locations/san-antonio-pecan-valley-va-clinic
Facility Locator ID: vha_671GU

**Comment by JayDarnell** [comment]
@omahane I'm of the opinion we don't need a complete runbook for address changes. I say this mostly because the root issue isn't the address change, but any change of facility information were the editors go to VAST and the change results in the "same facility" but with a new facility api id.

To fix this item we need to do the facility API ID swap like we did here: https://dsva.slack.com/archives/C02HX4AQZ33/p1671640128574559

**Comment by stefaniefgray** [comment]
Editor wrote in on Feb 27th asking for updates -- https://va-gov.atlassian.net/browse/VAHELP-5506

**Comment by stefaniefgray** [comment]
The editor has written us once again asking for updates -- tagging @kmariepat-cityfriends for visibility 

This is sort of a rare case/complicated situation outside of the norm, so I think as long as we continue to assure the editor that we're aware of the issue, they'll be pleased 👍

**Comment by JayDarnell** [comment]
This issue is duplicated by #12972 - I am closing this issue in favor of that one because it contains the complete runbook.

**Comment by TroyA6** [comment]
@stefaniefgray @JayDarnell @omahane @kmariepat-cityfriends - I have reviewed the requested changes in production; everything seems to be correct - The displayed address is correct, the Facility ID is correct within CMS, the production site and links TO the site all appear to be working correctly.
