### ISSUE TITLE
Round of UX review on CM Document

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#12574]
A lot of fields were added to the Content Model Document entity to cover what we need to bring in from airtable, but also new fields.  
Now that they are in, as a result of #12309, would be good to have a UX review to refine labels and help text so that this user interface is all good.

## ACs
- [ ] UX review of CM Document field form https://prod.cms.va.gov/admin/structure/cm_document/add (editorial interface)
- [ ] UX review of CM Document view (will have a link for it after saving a new one)
- [ ] Design recommendations for improvements (field order,  labels, helptext)

**Comment by maortiz-27-80** [comment]
Currently not in scope.  Reviewed with PO and team.  Closing 01/08/24  - Marcia
