### ISSUE TITLE
FE: TRICARE System and Facility health services should be displayed using the TRICARE name if supplied

### ISSUE THREAD

**Issue by JayDarnell** [department-of-veterans-affairs/va.gov-cms#12588]
This work has been abandoned for a different approch to the rpoblem outlined herein. See https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12716

Closing this ticket 2/23/2023

## User Story or Problem Statement

See #12356 

Once work in the issues above has been completed, we need to see what front end work is needed to utilize the new TRICARE service names. It is possible the front end will pick up the new names automatically but graphQL queries may need to be adjusted to pull these new values if the names are being built on the front end on the fly.

1. TRICARE Health Services List page (https://www.va.gov/lovell-federal-health-care-tricare/health-services) - if the names of the individual VAMC System health services are changed on the backend is that enough for the front end to reflect the changes or are these names derived by means of a graphQL query and that query needs the new field?

![Screenshot 2023-02-03 at 1 41 12 PM](https://user-images.githubusercontent.com/21045418/216682048-3fcd28af-a389-4a6d-b8b8-e3b74d75ac92.png)

2. TRICARE VAMC Facility pages (Example: https://www.va.gov/lovell-federal-health-care-tricare/locations/uss-osborne-dental-clinic) - if the names of the individual VAMC Facility health services are changed on the backend is that enough for the front end to reflect the changes or are these names derived by means of a graphQL query and that query needs the new field?

![Screenshot 2023-02-03 at 1 44 39 PM](https://user-images.githubusercontent.com/21045418/216682513-2c66b7e9-89df-46fc-abf4-44fe2ffd1ec8.png)

## Acceptance Criteria
- [ ] TRICARE service names used on the backend (CMS) for VAMC System Health Services and VAMC Facility Health Services within the TRICARE system are reflected on the front end as well

## Design principles

Veteran-centered
- [x] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [x] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [x] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [ ] `Public Websites`
- [x] `Facilities`
- [ ] `User support`

**Comment by omahane** [comment]
I updated the Cypress tests so they should fail until the winnower works in the following way:
- when selecting a TRICARE section, "Women Veteran Care" will not show in the Services dropdown, nor will a "|"
- when selecting a non-TRICARE section, either Lovell VA or any other, "Women Veteran Care" will show, but a "|" will not
https://github.com/department-of-veterans-affairs/va.gov-cms/pull/12675

I spent some time trying to get the winnower to choose one over the other. I got it working, but only on load. Basically, I got stuck when I winnowed by removing some of the text from the <option> and was unsure how to recover the removed text should the editor choose a different section. 

Perhaps you have a plan for this.
