### ISSUE TITLE
Request for update to existing KB article : How to add, edit or remove a Vet Center service

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#12599]
## Background context
**What is the request for?**

An update was made to the functionality of Vet Center facility services so editors are no longer able to edit the Service name.  The [existing KB article](https://prod.cms.va.gov/help/vet-centers/how-to-edit-a-vet-center-service) is now out of date as this has screenshots showing the old functionality and info regarding the Service name field.
see https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11367

Can this please be updated to reflect the new functionality?

**Person and team of requester:** 
- Laura Flannery, Accessibility Lead, CMS Team

**Priority or deadline for request**

  Choose either Deadline or a priority:
  
- [ ] Deadline: [name the deadline here]
- [ ] Priority:
  - [ ] Critical - Without this, there is a large negative impact on the majority of editors causing negative consequences within the CMS; Should be completed as soon as possible
  - [ ] High - Without this, there is negative impact on some editors causing negative consequences within the CMS; should be completed within the current sprint
  - [x] Medium - Without this, there is confusion for editors but not causing negative consequences within the CMS; Should be completed within the next 1-2 sprints
  - [ ] Low - This is not currently causing confusion for many editors but would be a nice to have or is something that may be more impactful in the future; Should be completed within the next 3-4 sprints
  

**Is the article associated with an ongoing product or feature update?**
- [ ] Yes [Add the link to the relevant issue](URL)
- [x] No

  
## If requesting a new article:

**Audience:**
Who is this intended for? Who would need this information? (i.e. All editors, only editors for a particular product, Internal use only, etc.)
- [name of product or type of editor]

**Related KB articles, if applicable:** 
- [If you know that related KB articles already exist, link them here]

  
**Any other relevant documentation, if applicable:** 
- [for example, could be the VA content style guide]

## Process
1. Sitewide CMS and Helpdesk teams will review request and confirm no current, applicable KB article/content exists.
2. Refine request and prioritize
3. Update KB article tracker to indicate that the article has been requested and is in progress
4. Assign to appropriate product team
5. Draft article content 
6. Sitewide CMS team will review for formatting and writing style guidelines
7. Helpdesk team will review for functionality and editorial tone
8. Publish
9. Update KB article tracker to indicate that the article has been published

## Acceptance Criteria
- [x] Article is updated using [KB content style guidelines](https://va-gov.atlassian.net/wiki/spaces/VAGOV/pages/1771831299/Knowledge+Base+content+style) 
- [x] Article is reviewed by Sitewide CMS
- [x] Article is reviewed by Helpdesk
- [x] Article posted to KB 
- [x] Impacts on other KB articles have been considered and any necessary changes have been made
- [x] Once published, let Jay (because he made the updates) and Laura (because she requested the changes) both know

**Comment by laflannery** [comment]
@laflannery tagging myself because @JayDarnell said this was ready for review https://dsva.slack.com/archives/C0FQSS30V/p1677773200596829

**Comment by laflannery** [comment]
@TroyA6 Can you please review and publish this? https://prod.cms.va.gov/node/23222/latest

**Comment by TroyA6** [comment]
Apologies @JayDarnell  and @laflannery    -- Letting you know that the KBA has passed HD review, and has been published -
