### ISSUE TITLE
Clean up stale content-build on-demand runners

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#12603]
## Description
content-build has several workflows that use on-demand runners. These generally tear their runners down afterwards, but sometimes they get left behind. There are currently many EC2 instances for content-build runners, most of which are very stale and are unregistered. https://console.amazonaws-us-gov.com/ec2/home?region=us-gov-west-1#Instances:search=:content-build;v=3;$case=tags:true%5C,client:false;$regex=tags:false%5C,client:false

The devops repo has a workflow which is responsible for cleaning up similar vets-website runners: https://github.com/department-of-veterans-affairs/devops/actions/workflows/stale-gha-odrunners-packer-builders-cleanup.yml

This workflow could either be copied or else adapted to also remove stale content-build runners.

## Acceptance Criteria
- [ ] Stale content-build runners are checked for and removed once daily.

### Team
Please check the team(s) that will do this work.

- [x] `CMS Team`
- [ ] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`

**Comment by laflannery** [comment]
@olivereri, @timcosgrove mentioned today in refinement that he believed this was completed.  I just wanted to confirm before we closed this out.

**Comment by olivereri** [comment]
Yes, this can can be closed. I'll close with this comment. #11405 Makes this ticket obsolete.
