### ISSUE TITLE
CMS: Adjust field validation/reset on VAMC Facility health service

### ISSUE THREAD

**Issue by ryguyk** [department-of-veterans-affairs/va.gov-cms#12619]
## Description
See [this comment](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12232#issuecomment-1431464681).

Field selections do not get reset when changing the Section field, so it's possible to end up with weird field combinations:
![image](https://user-images.githubusercontent.com/6863534/219084777-1af2425d-41bf-4691-9db2-7249e4e11f1b.png)

Further, these inconsistent field values are not validated on save.

So, fields should be reset and/or validated on save.

## Acceptance Criteria
Field Reset 
- [ ] (If applicable) Node create: Two dependent fields are reset when Section field is changed. (This already happens; ensure no regression).
- [ ] (If applicable) Node edit: Two dependent fields are reset when Section field is changed. ([There's an issue with this.](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12619#issuecomment-1440062908))

Field Validation
- [ ] When the Facility and VAMC system health service match the chosen Section, the node is saved. 
- [ ] When the Facility does not match the section:
  - [ ] The node does not save.
  - [ ] A message is shown to the editor: "The Facility does not match the Section. Please select a matching option."
- [ ] When the VAMC system health service does not match the Section:
  - [ ] The node does not save.
  - [ ] A message is shown to the editor: "The VAMC system health service does not match the Section. Please select a matching option."
- [ ] When both the Facility and the VAMC system health service do not match the Section:
  - [ ] The node does not save.
  - [ ] A message is shown to the editor: "The Facility and VAMC system health service do not match the section. Please select matching options."

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [ ] `Public Websites`
- [x] `Facilities`
- [ ] `User support`

**Comment by omahane** [comment]
The JavaScript approach for pages with content already in the "Facility" and "VAMC system health service" is undercut by the lack of the "_none" option in the select list, which is available when creating a new node. 

In addition, the PHP validation is more bulletproof as a validation, preventing the node from saving when the "Facility" and "VAMC system health service" do not match each other or the section.

**Comment by omahane** [comment]
@thejordanwood I am not sure exactly how we want to handle the field validation messaging to editors. I took a crack at it in [this Google Sheet](https://docs.google.com/spreadsheets/d/111SNnSgbB6zpOpF8R3m-RqEp5v3AVnMYpmnwTe0V6mM/edit#gid=0).

**Comment by thejordanwood** [comment]
@omahane I made one edit to your copy, but I'm going to loop @EWashb and @laflannery in on this because they'll probably have some good suggestions for the messaging too.

**Comment by EWashb** [comment]
@omahane and @thejordanwood that copy looks good to me.

**Comment by omahane** [comment]
@laflannery @BlakeOrgan @thejordanwood I found that we did a *very* similar thing for [Lovell in this ticket](https://github.com/department-of-veterans-affairs/va.gov-cms/pull/11356), which means that I had a very reliable, already-established pattern to follow:
![Screen Shot 2023-03-06 at 4 16 18 PM](https://user-images.githubusercontent.com/766573/223253497-283024ee-a915-4cf8-bdca-0bfe62ed2e84.png)
![Screen Shot 2023-03-06 at 4 17 53 PM](https://user-images.githubusercontent.com/766573/223253629-7f5ce735-68cc-427d-9b1b-2cf623cded87.png)
![Screen Shot 2023-03-06 at 4 16 59 PM](https://user-images.githubusercontent.com/766573/223253749-fb4a0fc8-ec2f-4f5e-98ec-b4a72c22c0d7.png)
