### ISSUE TITLE
Investigate impacts of retry-fetch bug on Search, Jan 25 - Feb 2

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#12625]
### User story
> _Describe the audience/user, enhancement or fix, and value / outcome desired._

**AS A** Veteran
**I WANT** the team that owns site search on VAgov to ensure issues are noticed
**SO THAT** I don't experience failures for significant periods of time.

### Engineering notes / background

We heard from Steve Albers in a [slack thread](https://dsva.slack.com/archives/C52CL1PKQ/p1676477178721839) that a post-mortem on an issue impacting "letter downloads" also appears to have impacted va.gov/search. The problematic `fetch-retry` library was present in production from Jan 25 to Feb 2, 2023.

Details are in their post-mortem. Specifically, the [screenshot from Sentry monitoring](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/va-albers-file-download-postmortem/Postmortems/2023/2023-02-03-letter-downloads.md#impact) shows significant impact to Search – see rows 1, 3, 4, and 8.

### Analytics considerations
na

### Quality / testing notes
na

## Acceptance criteria

- [x] Understand how the errors seen in Sentry could have impacted search
  - [x] Document whether/how we think Veterans were impacted
  - [ ] Document what evidence we should see in analytic platforms: Sentry, GA
- [x] Investigate why we didn't see issues 
  - [ ] What tests are present to protect Veterans from failures in Search
~~Document recommendations for better instrumenting Search~~ - because this bug / fix don't sit with the FE implementation, this AC is not relevant
- [x] Write ticket(s) for implementing tests or analytics to prevent these issues with Search
- [x] Update onsite-search product brief with notes about the API token / management

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [X] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`

**Comment by jilladams** [comment]
Note: analytics may be useful, connect with Wes as needed.

**Comment by wesrowe** [comment]
I took a first look at analytics and didn't see any changes in trend for the period of these Sentry errors. My method was to study in Domo the Search KPIs dashboard. The time-series chart for successful search count did not appear unusual.

**Comment by jilladams** [comment]
Note from FE refinement: Josh found that main user impact here is that type-ahead doesn't work during these error times. Has a Platform support ticket open about API token getting refreshed, which he thinks may be an underlying cause. He'll add more notes later in sprint.

**Comment by jilladams** [comment]
Sprint planning S79: 
* 95% confidence that this issue does not sit with FE
* 80% confidence that data.gov API key is the root cause, which we can verify when Plat updates the token

**Comment by jtmst** [comment]
Verified that the API key swap has fixed the issue:
@jilladams @wesrowe 

<img width="1182" alt="image" src="https://user-images.githubusercontent.com/61624970/222499429-3cd6774a-d07b-4cd0-92b6-fd2ec7c5a60d.png">

**Comment by jtmst** [comment]
API documentation added here, and Wes created the testing ticket.  There are no front end tests at this time that test a proper api response for the search type ahead vets-api endpoint, which a ticket has been cut for and is the next recommended action.

For vets-api, there does appear to be a test for this endpoint at spec/requests/search_typeahead_request_spec.rb.  It is unclear at this time why this failure wasnt detected, but adding testing to the front end should protect us from this happening undetected again.
