### ISSUE TITLE
Order column on Service locations table no longer hidden

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#12631]
## Description
On VAMC Facility service content types, there is a Service locations table. In prod currently, there is a column on this table for the Order that is hidden with `display: none` however in Drupal 10 now this column is visible.

**Prod:** 
![image](https://user-images.githubusercontent.com/106678594/219129689-16463d15-4d6a-4b0e-8684-58fd039b8f6d.png)

**Drupal 10:**
![image](https://user-images.githubusercontent.com/106678594/219129764-41270713-e851-4b6a-9e2f-dfff1835c9f6.png)

## Additional context
This is also happening on the events date and Time table

**Comment by laflannery** [comment]
I feel like this Hide/Show row weights column is showing everywhere now when before it was either defaulted to hidden or hidden entirely.  I have no screenshots from Friday but I just don't remember seeing this:
![image](https://user-images.githubusercontent.com/106678594/219157064-e503cb13-3a9d-432c-8970-68d7d3a7bf3a.png)

I know for a fact we have it hidden in Prod by default - and therefore we should fix this - but I feel like it was correct on Friday too and now it is not

**Comment by laflannery** [comment]
This is still an issue

**Comment by edmund-dunn** [comment]
This has already been fixed.

**Comment by ndouglas** [comment]
Is this fixed on `main`?

**Comment by laflannery** [comment]
So this is happening on stage now, but not on prod and not on D10 so I'm going to reopen because I don't want to retype the issue

**Comment by laflannery** [comment]
@xiongjaneg This was an issue that I had previously seen in D10 but it was closed. Now I see the issue on staging (where I'm testing VBA) and it's ONLY on staging, not Prod or D10 and just on Facilities products. My question is - should I now assign this to Facilities?

**Comment by xiongjaneg** [comment]
@laflannery Yes, thanks for noting. I'll change the label to Facilities and Backlog.

**Comment by laflannery** [comment]
I discovered something - 

Below the service locations situation, there is another block that has an option for Hide/show row weights. It was saying "hide row weights" instead of Show which is what I'm used to. If I switched this, it fixed everything - the Service locations section above on VBA Service region AND the Service location table on VAMC Facility Health Services. 

It's almost like my row weights preference was being saved and used across the CMS - is that expected?

**Comment by xiongjaneg** [comment]
@swirtSJW ^^ Thoughts about Laura's question about row weight preferences?

**Comment by xiongjaneg** [comment]
In some cases, there doesn't need to be an order so that could be removed. But the kebab menu is also for dragging and dropping, so that is not accessible. Hiding weights also hides dropping and dragging. 

Some cases do need sorting and arranging.

Would it be helpful to differentiate between content types (or fields, e.g., multiple phone numbers) that need sorting and arranging and those that don't? There's a defect that Edmund found last refinement around the kebab menu is related. 

Show row weights is a universal setting. Once selecting, it persists throughout the system. Is expected.

Action
- Jane to find related issue.
- Is this a blocker to D10 implementation from the Facilities perspective? Potentially yes from engineering, but needs UX (Blake and Jordan) and accessibility perspectives. Could be confusing for editors if they suddenly see a row weight where they didn't before.

**Comment by xiongjaneg** [comment]
@laflannery RE your question on row weights preference, per Steve: Show row weights is a universal setting. Once selected, it persists throughout the system for accessibility. This is expected behavior.

**Comment by xiongjaneg** [comment]
Related to #14797

**Comment by xiongjaneg** [comment]
@thejordanwood @laflannery Question for you on this ticket: Is D10 not showing the order column on Service locations table a blocker to D10 implementation?

**Comment by laflannery** [comment]
The behavior I was seeing and reported above with the order column Is exactly the same as it currently behaves on Prod. I was not aware that the Show row weights was a persistent feature (meaning once I select it in one content type it will remain as my default throughout the CMS). This is especially confusing because in this instance the order column/row weights displayed but I had no way to hide them here.

However, as mentioned, this is exactly the same behavior as Prod and we are using the "neutral or better" scale to determine issues for the D10 upgrade. This is neutral and therefore not an issue for D10.

There are 2 issues that we should have in the backlog though for future discovery/resolution:
- The existing issue you linked above regarding the Drag & Drop behavior
- The issue mentioned in [the comment above](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12631#issuecomment-1708515433) regarding the fact that this doesn't need to be sorted and the order column should probably be removed. I would recommend that perhaps gets ticketed for the backlog so it does not get lost.

That all being said, I think this issue should be closed.

**Comment by xiongjaneg** [comment]
Created #15197 to capture removal from content types that don't need sorting
