### ISSUE TITLE
Date and time table is showing additional sections

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#12634]
## Description
On events, there is a Date/time table and in Drupal 10 it is showing an extra section at the bottom that shouldn't be visible.

Example event: https://vacms-12252-drupal-10-cne7edu0najqzzmwjbq3awbbjcxb40w3.ci.cms.va.gov/node/53154/edit

**Prod:**
![image](https://user-images.githubusercontent.com/106678594/219146767-dc0815ae-9236-4bcf-a20a-42f6fa013616.png)

**Drupal 10 (the same event):**

![image](https://user-images.githubusercontent.com/106678594/219146623-cf378cd2-07bc-481e-818d-73caa8fafd33.png)

**Comment by laflannery** [comment]
This is still an issue

**Comment by EWashb** [comment]
This is a terrible user experience and I agree that we should consider fixing this before launch if we are able. 

If we are measuring acceptable impact to editors and neutral or better experience, this definitely falls below neutral and into worse experience.

**Comment by edmund-dunn** [comment]
This has been fixed for D10.
