### ISSUE TITLE
Kebab menu toggle on Service locations table not working

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#12636]
## Description
On VAMC Facility service content types, there is a Service locations table. On this table there is a kebab menu toggle for the drag & drop functionality. This is not working. When I try to use this, console errors are appearing instead of the proper functionality:

![image](https://user-images.githubusercontent.com/106678594/219167862-ffec4005-5293-474b-8285-104a7e7238f3.png)

## Acceptance Criteria

- [ ] Root cause has been identified and documented in this thread.
- [ ] Followup issue(s) opened to address as needed, including:
  - [ ] Creation of behavioral test to assure proper function of this widget in the future.

**Comment by laflannery** [comment]
Still an issue

**Comment by edmund-dunn** [comment]
@productmike this is fixed. It was related to an underlying javascript library update that was part of the D10 upgrade. We had to update some syntax to get the JS to load correctly.
