### ISSUE TITLE
Review and Publish KB article : COVID status feature updates

### ISSUE THREAD

**Issue by EWashb** [department-of-veterans-affairs/va.gov-cms#12639]
## Background context
The Facilities team will be updating a KB article on COVID status feature updates. The CMS Team will be responsible for reviewing and publishing this KB article once the changes are live via #12111. 

**Priority or deadline for request**

  Choose either Deadline or a priority:
  
- Deadline: Concurrently with #12572 
- Priority:
  - [ ] Critical - Without this, there is a large negative impact on the majority of editors causing negative consequences within the CMS; Should be completed as soon as possible
  - [X] High - Without this, there is negative impact on some editors causing negative consequences within the CMS; should be completed within the current sprint
  - [ ] Medium - Without this, there is confusion for editors but not causing negative consequences within the CMS; Should be completed within the next 1-2 sprints
  - [ ] Low - This is not currently causing confusion for many editors but would be a nice to have or is something that may be more impactful in the future; Should be completed within the next 3-4 sprints
  

**Is the article associated with an ongoing product or feature update?**
- [X] Yes [How to edit COVID-19 status for a VAMC facility
Search](https://prod.cms.va.gov/help/vamc/about-locations-content-for-vamcs/about-alerts-and-operating-statuses/how-to-edit-covid-19-status-for-a-vamc-facility)
- [ ] No

## Process
1. Sitewide CMS and Helpdesk teams will review request and confirm no current, applicable KB article/content exists.
2. Refine request and prioritize
3. Update KB article tracker to indicate that the article has been requested and is in progress
4. Assign to appropriate product team
5. Draft article content 
6. Sitewide CMS team will review for formatting and writing style guidelines
7. Helpdesk team will review for functionality and editorial tone
8. Publish
9. Update KB article tracker to indicate that the article has been published

## Acceptance Criteria
- [x] Article is reviewed by CMS Team
- [x] Article is reviewed by Helpdesk
- [x] Article posted to KB 
- [x] Once published, notify Facilities PM and DM

**Comment by TroyA6** [comment]
@EWashb @laflannery @dawnpruitt This KBA passes HD review.

**Comment by laflannery** [comment]
@TroyA6 and @EWashb I just redid the whole format of this is you wanted to give it another once over: https://prod.cms.va.gov/node/46088/latest
