### ISSUE TITLE
URL change for Phoenix 32nd Street VA Clinic

### ISSUE THREAD

**Issue by stefaniefgray** [department-of-veterans-affairs/va.gov-cms#12645]
### Instructions
- This issue will be used from initial request through implementation to ensure all individuals working on this are notified of status updates.  Please do not create multiple issues to track different steps.
- It is your responsibility to notify VA stakeholders as appropriate.
- Be sure to link the related facility closure / rename issue.
- Front end redirects are tracked in the [devops](https://github.com/department-of-veterans-affairs/devops) repo in `ansible/deployment/config/revproxy-vagov/vars/redirects.yml`

### Implementation date
When does this request need to be live: As soon as possible

### Acceptance Criteria 
- [ ] I expect the canonical URL is updated and put on a PR 
- [ ] I expect lighthouse is notified of this PR to ultimately push the changes 

### Redirects 
| Current URL  |  Redirect Destination or New URL |
| ---  |  --- |
| https://www.va.gov/find-locations/facility/vha_644GI | https://www.va.gov/phoenix-health-care/locations/phoenix-32nd-street-va-clinic |

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [ ] `Public Websites`
- [x] `Facilities`
- [x] `User support`

**Comment by JayDarnell** [comment]
Redirect change for this has been bundled with the changes for #12644. See the PR in the devops repo above: #12615)
