### ISSUE TITLE
URL change for Mesa VA Clinic

### ISSUE THREAD

**Issue by stefaniefgray** [department-of-veterans-affairs/va.gov-cms#12644]
### Instructions
- This issue will be used from initial request through implementation to ensure all individuals working on this are notified of status updates.  Please do not create multiple issues to track different steps.
- It is your responsibility to notify VA stakeholders as appropriate.
- Be sure to link the related facility closure / rename issue.
- Front end redirects are tracked in the [devops](https://github.com/department-of-veterans-affairs/devops) repo in `ansible/deployment/config/revproxy-vagov/vars/redirects.yml`

### Acceptance Criteria 
- [ ] I expect yaml file changes occur before the lighthouse csv changes 
- [ ] I expect the canonical URL is updated and put on a PR 
- [ ] I expect lighthouse is notified of this PR to ultimately push the changes 

### Implementation date
When does this request need to be live: As soon as possible

### Redirects 
| Current URL  |  Redirect Destination or New URL |
| ---  |  --- |
| https://www.va.gov/find-locations/facility/vha_644GJ | https://www.va.gov/phoenix-health-care/locations/mesa-va-clinic |

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [ ] `Public Websites`
- [x] `Facilities`
- [x] `User support`

**Comment by JayDarnell** [comment]
A pull request for this redirect has been created.
