### ISSUE TITLE
va.gov-cms workflows need GHA syntax updated and actions updated for node16

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#12641]
```[tasklist]
## Acceptance Criteria
- [ ] We have identified every dependency action that needs updating, with estimated level of effort to update
- [ ] Tickets are created for each update
```

## Description
**Actions and required resolutions: https://docs.google.com/spreadsheets/d/1cIEuX36NgsmPLeqeCnjLNCKRRAX4x3UFD2OmgYqOLlk/edit#gid=0**

Github has deprecated some syntax and usage of node12 in actions, as described in these posts:

https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/

**The save state/set output syntax deprecation will begin to cause workflows to completely fail June 1, 2023**. The node12 -> 16 move does not have a defined deadline, but the work is similar and connected to the syntax change, and so should be done together.

All workflows will need following updates made:
* convert to newer set output/env syntax
* convert any scripts making that set output/env to use @actions/core at least at 1.10.0
* any actions currently in use that are throwing warnings about node12 need to be updated or replaced with equivalent functionality.
 
Our preferred approach for each action update are, in order:
* The action has been updated by its maintainer and we point to the new version
* We find an acceptable replacement that is compliant with the changes
* We make the changes ourselves.

**Implications for VA Platform:** We cannot be responsible for updating every use of these outdated packages throughout the VA ecosystem, but we can alert Platform Devops CoP that these packages are outdated and they should communicate with the respective owners to update it.

Warnings thrown for the above problems are in the form:
```
Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: aws-actions/configure-aws-credentials@v1, marvinpinto/action-inject-ssm-secrets@v1.2.1. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.

The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```

### Team
Please check the team(s) that will do this work.

- [x] `CMS Team`
- [ ] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`

**Comment by timcosgrove** [comment]
Pull request is opened: https://github.com/department-of-veterans-affairs/va.gov-cms/pull/13471

This is blocked pending this repo becoming public: https://github.com/department-of-veterans-affairs/action-inject-ssm-secrets

**Comment by productmike** [comment]
@timcosgrove same comment as #12640 -- timeline?

**Comment by productmike** [comment]
closing in lieu of #13521 placeholder to track repo readiness.
