### ISSUE TITLE
Edit existing KB article: CLCs and Domiciliary Locations [Facilities]

### ISSUE THREAD

**Issue by stefaniefgray** [department-of-veterans-affairs/va.gov-cms#12659]
## Background context
**What is the request for?**

**Existing article:** https://prod.cms.va.gov/help/vamc/about-locations-content-for-vamcs/how-to-add-a-community-living-center-or-domiciliary-page

**Backstory:** See https://va-gov.atlassian.net/browse/VAHELP-5468

Current KB article unclear as to how CLCs and Domiciliary locations are not official "VAMC Facility" locations in Drupal and do not show up under the "Locations" left-nav menu or on the "Locations" page.

Low impact because tickets pertaining to CLCs are very rare and there are only a small handful listed in Drupal -- see https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10080 for info

**Person and team of requester:** 
- Stefanie Gray, VA Drupal CMS Help Desk

**Priority or deadline for request**

  Choose either Deadline or a priority:
  
- [ ] Deadline: [name the deadline here]
- [ ] Priority:
  - [ ] Critical - Without this, there is a large negative impact on the majority of editors causing negative consequences within the CMS; Should be completed as soon as possible
  - [ ] High - Without this, there is negative impact on some editors causing negative consequences within the CMS; should be completed within the current sprint
  - [ ] Medium - Without this, there is confusion for editors but not causing negative consequences within the CMS; Should be completed within the next 1-2 sprints
  - [x] Low - This is not currently causing confusion for many editors but would be a nice to have or is something that may be more impactful in the future; Should be completed within the next 3-4 sprints
  
**Is the article associated with an ongoing product or feature update?**
- [ ] Yes [Add the link to the relevant issue](URL)
- [x] No
  
**Any other relevant documentation, if applicable:** 
- [for example, could be the VA content style guide]

## Acceptance Criteria
- [x] Specified that CLCs and Domiciliary locations are not official "VAMC Facility" locations in Drupal and do not show up under the "Locations" left-nav menu or on the "Locations" page.

**Comment by xiongjaneg** [comment]
made updates and closing
