### ISSUE TITLE
Redirect Request for New Facility: Walzem VA Clinic [Waiting for Facility Publication]

### ISSUE THREAD

**Issue by stefaniefgray** [department-of-veterans-affairs/va.gov-cms#12651]
See: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10835
Must be completed first

### Instructions
- This issue will be used from initial request through implementation to ensure all individuals working on this are notified of status updates.  Please do not create multiple issues to track different steps.
- It is your responsibility to notify VA stakeholders as appropriate.
- Be sure to link the related facility closure / rename issue.
- Front end redirects are tracked in the [devops](https://github.com/department-of-veterans-affairs/devops) repo in `ansible/deployment/config/revproxy-vagov/vars/redirects.yml`

### Implementation date
When does this request need to be live:

### Redirects 
| Current URL  |  Redirect Destination or New URL |
| ---  |  --- |
| https://www.va.gov/find-locations/facility/vha_671GT | va.gov/south-texas-health-care/locations/walzem-va-clinic |

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [ ] `Public Websites`
- [x] `Facilities`
- [x] `User support`

**Comment by stefaniefgray** [comment]
Prior Walzem new facility ticket did not have re-direct request created since new facilities runbook did not have redirects mentioned

See https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10835

**Comment by stefaniefgray** [comment]
Hey, I learned how to link blocked tickets in Github!

**Comment by JayDarnell** [comment]
I'm closing this issue as the redirects for new facilities was a workaround I proposed with Lighthouse being under a code freeze. Now that LH is no longer under a code freeze we should be submitting URL updates to lighthouse for new facilities.
