### ISSUE TITLE
CMS Audit: Locate Incorrectly Archived VAMC Facilities

### ISSUE THREAD

**Issue by stefaniefgray** [department-of-veterans-affairs/va.gov-cms#12662]
## Background
When a VAMC facility closes, the associated section editor(s) must follow the steps listed within the "How to Archive a Closed Facility" Knowledge Base article: https://prod.cms.va.gov/help/vamc/about-locations-content-for-vamcs/how-to-archive-a-closed-facility

However, if they don't know that this article exists, and don't reach out to the VA Drupal CMS Help Desk about the closure, then they may not follow all of the steps involved.

As a result, there may be one or more permanently closed facility homepages published within the CMS where section editors never reached out to our team about the closure.

If this is the case, then it is also highly likely that no one has requested that the facility be removed from the Facilities API -- which would keep them from coming up on the [Flagged Facilities](https://prod.cms.va.gov/admin/content/facilities/flagged) page as "Removed From Source." 

**Real life example:** The Goshen VA Clinic in VA Indiana is a recent example of a clinic that was permanently closed but never came up as "Removed From Source.": https://prod.cms.va.gov/northern-indiana-health-care/locations/goshen-va-clinic

The editor was not aware of the steps listed within the Knowledge Base article linked above. Fortunately, once the steps were sent, the editor was able to help complete the facility archival process from their end.

See spreadsheet: https://docs.google.com/spreadsheets/d/19LqpUBZRppJTRHczJeUgzTItC3idWQBSgKkd_o0cqQo/edit?usp=sharing

Slack thread: https://dsva.slack.com/archives/C0FQSS30V/p1676587026652919?thread_ts=1676579342.485879&cid=C0FQSS30V

See related ticket: #11028 

------
The best way to track these facilities is by checking over all VAMC locations where Operating Status = "Closed" 

Editors who have not read the Knowledge Base article steps for archiving a closed facility are likely to think that this is the only action that must be taken, so it's worth examining the listing of facilities with this operating status that are still published to the live site.

**Facilities filtered for Operating Status = "Closed":**
https://prod.cms.va.gov/admin/content/facilities/facility-status?Title=&field_facility_locator_api_id_value=&field_operating_status_facility_value=closed&field_operating_status_more_info_value=&field_supplemental_status_target_id_op=or&field_supplemental_status_target_id=All&type=All&moderation_state=editorial-published&workbench_access_section__section=All

-------

## Acceptance Criteria
- [x] VAMC Facilities that are published with an Operating Status of "Closed" for reasons other than temporary closures (i.e. federal holiday, snowstorm) are filtered
- [x] If editor needs to complete Knowledge Base article steps for archiving a closed facility, editor is provided link and instructions
- [x] Open Github tickets linked to known partially-archived facilities are resolved:
     - [x] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/7925
- [ ] VAMC Facility closure Github tickets and re-direct requests are created for each of the facilities that do not currently have tickets so that the archiving process can be completed.
     - [x] [Denver VA Clinic](https://prod.cms.va.gov/eastern-colorado-health-care/locations/denver-va-clinic)
          - [x] Main closure ticket: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13653
          - [x] URL redirect ticket: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13827
     - [x] [Frank M. Tejeda Department of Veterans Affairs Outpatient Clinic](https://prod.cms.va.gov/south-texas-health-care/locations/frank-m-tejeda-department-of-veterans-affairs-outpatient-clinic)
          - [x] As of 5/25/23 - Emailed editors in https://va-gov.atlassian.net/browse/VAHELP-5871
     - [x] [Goshen VA Clinic](https://prod.cms.va.gov/northern-indiana-health-care/locations/goshen-va-clinic)
          - [x] As of 5/25/23 - Still hasn't been removed from VAST, but getting taken care of in https://va-gov.atlassian.net/browse/VAHELP-5869
     - [ ] [Jacksonville 2 VA Clinic](https://prod.cms.va.gov/fayetteville-coastal-health-care/locations/jacksonville-2-va-clinic)
     - [ ] [Market Commons VA Clinic](https://prod.cms.va.gov/charleston-health-care/locations/market-commons-va-clinic)
     - [x] [Orlando 1 VA Mobile Clinic](https://prod.cms.va.gov/orlando-health-care/locations/orlando-1-va-mobile-clinic)
          - No tickets needed -- operating status says "Facility closed, does not exist."

**For facilities where we are unsure of current status:** 
- [ ] Facilities / Help Desk team follows up with editors by asking about real-life status of facility -- information provided is tracked and cross-referenced

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [ ] `Public Websites`
- [x] `Facilities`
- [x] `User support`

**Comment by stefaniefgray** [comment]
Note that the Denver VA Clinic is very much closed and it's just a big old empty building that's up for sale

Safe to proceed once ticket is created

**Comment by stefaniefgray** [comment]
I might have to tackle this one when I'm back in office since it'll take Jira legwork to reach out to the editors, and to create associated Facility Closure and re-direct tickets

**Comment by kmariepat-cityfriends** [comment]
@stefaniefgray to confirm AC are complete on this card and make new cards for facility closure runbooks

**Comment by stefaniefgray** [comment]
@kmariepat-cityfriends I'm gonna need to work on this next week when I'm back

**Comment by stefaniefgray** [comment]
Check up on:
- https://prod.cms.va.gov/orlando-health-care/locations/orlando-1-va-mobile-clinic
- https://prod.cms.va.gov/wilmington-health-care/locations/wilmington-va-mobile-clinic

**Comment by xiongjaneg** [comment]
@stefaniefgray @omahane The last action on this was in July. Is this still in progress? Can this closed?

**Comment by stefaniefgray** [comment]
@xiongjaneg We can close this out, but would it be possible to make this a quarterly task so that we can catch other improperly closed Facilities? cc: @jilladams @mmiddaugh

**Comment by xiongjaneg** [comment]
@stefaniefgray Thanks, I'll stub out a follow-up ticket for ongoing.

**Comment by stefaniefgray** [comment]
@xiongjaneg Thanks for closing! 

Note: It's tough to suss out which ones are "partially closed" when a bunch of locations are closed for an impending hurricane, federal holidays, etc., so if this is a recurring task, the person performing it should be aware of how those things affect the "Operating Status = Closed" list
