### ISSUE TITLE
Invalid HTML for <ul> when adding Benefits Hub contacts

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#12664]
## Description
On some content types, there is an option to add Benefits Hub contacts. When these are added it pulls in content from the particular Benefit hub in a list format, however the underlying HTML is invalid because it has tags as direct children of the `<ul>` that are tags other than `<li>`.

Example pages:
- https://prod.cms.va.gov/resources/test-registry-exam-checklist (Checklist content type)
- https://prod.cms.va.gov/resources/getting-a-gi-bill-extension (Resources and Support Detail page)

**_Update 12/14/2023 from Laura: Yes this is still an issue and No it does not happen when Default contacts is selected, here's an example of a [default contacts page](https://prod.cms.va.gov/resources/getting-care-through-the-foreign-medical-program)_**

### Screenshots
**Adding Benefits Hub contacts on edit node:**
![image](https://user-images.githubusercontent.com/106678594/219671808-1cced7e7-3924-43be-91f3-7f47db90ea9f.png)
**Display of View node:**
![image](https://user-images.githubusercontent.com/106678594/219672159-e4d801cd-4120-4762-a226-9ef344c5ded1.png)
**Invalid HTML:**
- Heading is `<ul>` with `<span>` inside
![image](https://user-images.githubusercontent.com/106678594/219672635-a5acf85e-afd1-40ba-b75e-f151081b596a.png)
- List is `<ul>` with many other tags inside
![image](https://user-images.githubusercontent.com/106678594/219673124-99eecbcb-f3a5-4895-9dff-646c54b89749.png)

## Acceptance Criteria
- [x] Update HTML for Contact information headers to be valid
- [x] Update HTML for Contact information lists to be valid
- [x] Accessibility lead review

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [x] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`

**Comment by laflannery** [comment]
This is happening because of all the entity references, it can be fixed with Twig.  When we fix it we want to start at the very top and very clearly and deliberately place everything we need and remove what we don't need.

I should find out what is the case for Default contacts and if that's impacted. And we want to make sure that we don't unintentionally break anything else (i.e. the main benefits hub view node)

**Comment by FranECross** [comment]
> This is happening because of all the entity references, it can be fixed with Twig. When we fix it we want to start at the very top and very clearly and deliberately place everything we need and remove what we don't need.
> 
> I should find out what is the case for Default contacts and if that's impacted. And we want to make sure that we don't unintentionally break anything else (i.e. the main benefits hub view node)

@laflannery Wondering if you have an update on whether Default contacts is impacted? This ticket is fairly old and I also want to check to see if it's still an issue. Thank so much!

**Comment by laflannery** [comment]
@FranECross Yes this is still an issue and No it does not happen when Default contacts is selected, here's an example of a [default contacts page](https://prod.cms.va.gov/resources/getting-care-through-the-foreign-medical-program)

**Comment by dsasser** [comment]
Verified in prod:

![Screenshot 2024-02-08 at 8 20 15 AM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/221539/eeca3eae-d498-4bf1-bf1c-a9d66f05142b)
![Screenshot 2024-02-08 at 8 19 59 AM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/221539/52dceb8e-c35e-4a9e-9c82-e8445bec656e)
