### ISSUE TITLE
New Facility: Gainesville VA Clinic

### ISSUE THREAD

**Issue by stefaniefgray** [department-of-veterans-affairs/va.gov-cms#12660]
## Background

*What triggered this runbook?*
Help Desk ticket: https://va-gov.atlassian.net/browse/VAHELP-5454

**Redirect request:** https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12661

*1. Please attach Facility Locator link to this ticket*
https://www.va.gov/find-locations/facility/vha_573QL

*2. Please attach prod link to this ticket*
https://prod.cms.va.gov/north-florida-health-care/locations/gainesville-va-clinic

*3. Please also include link to Jira help desk ticket, if applicable*
https://va-gov.atlassian.net/browse/VAHELP-5454

### VAMC
Please refer to the Knowledge Base article titled "How do I add a facility to my health care system?" for more information: https://prod.cms.va.gov/help/vamc/about-locations-content-for-vamcs/how-do-i-add-a-facility-to-my-health-care-system

#### CMS help desk steps
- [x] 1. Become aware that the new facility is now on the Facility API (typically, via a Flag, but this may come in as a helpdesk ticket).
- [ x 2. If the editor has followed the steps from the above Knowledge Base article and included which section and VAMC the facility belongs to (i.e. VA Pittsburgh), great! **Proceed to step 3.** If not, please check with the editor or VHA digital media regarding what section and VAMC it belongs to.
- [x] 3. Updates the Section (default is "VAMC facilities", but it should be a VAMC system in a VISN) and VAMC system field accordingly.
- [x] 4. Communicate with editor (cc VHA Digital Media) to give them go-ahead to complete the content, with this [KB article](https://prod.cms.va.gov/help/vamc/about-locations-content-for-vamcs/how-do-i-add-a-facility-to-my-health-care-system). (See sample notification email below)
- [ ] 5. When editor has prepared content and let help desk know, reassign this issue to appropriate CMS engineer on Product Support team, for bulk publishing.

    #### Sample notification email for Step 4:
    Hello! You should now be able to edit the draft page for this facility, located at [LINK TO NEW FACILITY DRAFT PAGE ON PROD]

    Important: Please make sure that all relevant steps listed within the “How do I add a facility to my health care system?” Knowledge Base article have been completed: https://prod.cms.va.gov/help/vamc/about-locations-content-for-vamcs/how-do-i-add-a-facility-to-my-health-care-system
    
    Once finished, please save this page (and all related VAMC Facility Health Service pages) in the moderation state “Draft." Please do not save them as “Published.”

    Please let us know when your draft content is complete, so that we can wrap up the technical process from our end before publishing the new facility to VA.gov. Thanks!

#### CMS engineer
- [x] 6. CMS engineer bulk publishes nodes and facility.
- [x] 7. CMS engineer edit facility node and remove `New facility` flag and save node.
- [x] 8. Let help desk know this has been done.

#### CMS Help desk
- [ ] 9. HD notifies editor and any other stakeholders.

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [ ] `Public Websites`
- [x] `Facilities`
- [x] `User support`

**Comment by stefaniefgray** [comment]
Blocked until facility is published

Redirect request: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12661

**Comment by stefaniefgray** [comment]
@kmariepat-cityfriends @omahane Facility is unblocked and ready to go 🚀 

Draft homepage: https://prod.cms.va.gov/north-florida-health-care/locations/gainesville-va-clinic

**Comment by omahane** [comment]
@stefaniefgray @TroyA6 This has been published. I noticed here, though, some discrepancies between the phone number and hours in the page introduction and those from Lighthouse:
https://prod.cms.va.gov/north-florida-health-care/locations/gainesville-va-clinic
- 352-548-1900 (page intro) vs 352-548-6000 (lighthouse)
- 7:00 - 4:30 (page intro) vs 8:00 - 4:30 (lighthouse)
Can you reach out to the editor to make sure they align those?

**Comment by TroyA6** [comment]
@stefaniefgray @omahane - Here is the response from the editor -- (please let me know best course of action / next steps after reading the response):

The correct phone number and operating hours are as listed on the web page in the “page introduction” (352-548-1900, Monday-Friday 7:00 a.m. - 4:30 p.m.). 

The new facility’s administration asked our VAST Administrator to submit a requested update to the database, but those changes are processed nationally and in our experience can take a long time to show in the database. So until the changes are processed nationally, the API is pulling in the VAST info which is incorrect. While we are waiting on the database update, I at least put the correct info in the “page intro” so it would be in a large font at the top of the new page…

**Comment by omahane** [comment]
@swirtSJW That seems like a reasonable workaround, but I'm interested your take.

**Comment by kmariepat-cityfriends** [comment]
Closing because this is now appearing in facility locator
