### ISSUE TITLE
Lovell: Main System pages do not have unique page titles

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#12685]
## Description
While I was doing the final staging review for the Collab cycle - and with direction from Max - I focused on the page titles of the pages. The main system pages for both VA and TRICARE do not pull in unique page titles.

[Lovell TRICARE](https://web-liqqgmzl7tsyfbwyulbkuborufuuttav.demo.cms.va.gov/lovell-federal-health-care-tricare/) - has a page title of Lovell Federal Health Care | Veterans Affairs
[Lovell VA](https://web-liqqgmzl7tsyfbwyulbkuborufuuttav.demo.cms.va.gov/lovell-federal-health-care-va/) - has a page title of Lovell Federal Health Care | Veterans Affairs

However, The interior pages do have proper titles:
[TRICARE Health Services](https://web-liqqgmzl7tsyfbwyulbkuborufuuttav.demo.cms.va.gov/lovell-federal-health-care-tricare/health-services/) says Health services | Lovell Federal Health Care - TRICARE| Veterans Affairs
[VA Health Services](https://web-liqqgmzl7tsyfbwyulbkuborufuuttav.demo.cms.va.gov/lovell-federal-health-care-va/health-services/) says Health services | Lovell Federal Health Care - VA | Veterans Affairs

## Acceptance Criteria
- [ ] Update page title for Lovell TRICARE main page to be Lovell Federal Health Care - TRICARE| Veterans Affairs
- [ ] Update page title for Lovell VA main page to be Lovell Federal Health Care - VA| Veterans Affairs

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [ ] `Public Websites`
- [x] `Facilities`
- [ ] `User support`

**Comment by laflannery** [comment]
@Dottisea Tagging you for visibility

**Comment by Dottisea** [comment]
Pulling into sprint 78 as potentially linked with #12686

**Comment by ryguyk** [comment]
Closing in favor of https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12776
