### ISSUE TITLE
Adding Spanish toggle to 3 disability pages

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-cms#12694]
**SHOULD NOT MERGE until Sitewide Content gives greenlight**

### Describe your request

Sitewide Content published to prod 3 core disability pages in Spanish. They are currently in QA with the State Department, but once that's complete, we need to add the toggle to the top of the English/Spanish pages like we have on our COVID and PACT Act pages. 

These are the pages that will need the toggle:

#### Spanish
- https://www.va.gov/disability/eligibility-esp/
- https://www.va.gov/disability/how-to-file-claim-esp/
- https://www.va.gov/disability/after-you-file-claim-esp/

#### English
- https://www.va.gov/disability/eligibility/
- https://www.va.gov/disability/how-to-file-claim/
- https://www.va.gov/disability/after-you-file-claim/

### Time constraints / launch deadlines

Pages are currently with State Department for QA. Looking like this may be ready to implement the week of 3/6/23.

### Point of contact

@Rlhecht, Randi Hecht

## Acceptance criteria

- [ ] **SHOULD NOT MERGE until Sitewide Content gives greenlight**
- [ ] English & Spanish toggles appear on all 3 pages
- [ ] Tagalog toggle does not appear
- [ ] Clicking Spanish loads Spanish page
- [ ] Clicking English loads the English page
- [ ] Verify existing toggles on https://www.va.gov/coronavirus-veteran-frequently-asked-questions/ are not affected by these changes. (Spanish, English, Taglog all work as expected)
- [ ] Design review to verify mobile & desktop

**Comment by jilladams** [comment]
Ticket updated and moved to our repo. Assigning to @jtmst for pre-refinement -- this is 3 language React widgets added to SPanish / English pages. (No Tagalog.)

**Comment by wesrowe** [comment]
@RLHecht, can you please clarify why there is a single page under "Spanish" above? That url seems to be the Spanish version of the eligibility page under "English."

**Comment by RLHecht** [comment]
These are the 3 that need the toggle (I think Jill reworked this ticket and it probably got rearranged). Each of these have a Spanish page connected that ends in -esp

https://www.va.gov/disability/eligibility/
https://www.va.gov/disability/how-to-file-claim/
https://www.va.gov/disability/after-you-file-claim/

**Comment by jtmst** [comment]
Am i correct in assuming that we want the placement and behavior to be identical to the corona FAQ page, just without Tagalog?

https://www.va.gov/coronavirus-veteran-frequently-asked-questions/

**Comment by jilladams** [comment]
FE refinement: 
* Toggles incl Sp and Tagalog by default, so we'll need to update the widget to remove Taglog
* No designs available, so if @RLHecht can confirm that it should looks like https://www.va.gov/coronavirus-veteran-frequently-asked-questions/, sans Tagalog, we can move forward.
* Design: we don't have comps, and don't really need them if ^ is correct, but do want to loop @thejordanwood for review as an AC. (Added.)

**Comment by RLHecht** [comment]
@jilladams Yes, we would want the toggles to look the same as on our COVID and PACT content but just with the Spanish one like you said.

**Comment by RLHecht** [comment]
@jilladams We are getting back the Spanish disability pages from QA tomorrow, so we were aiming to have them corrected and live by the end of next week. Do you think the toggle would be able to be in place at that point?

**Comment by jilladams** [comment]
In sprint planning we had talked about prepping this PR and merging it when you all give us the greenlight. Our sprint ends next Tues, so at minimum, we'd have these ready to merge by then, and then can hit the button when you're ready. (@jtmst let me know if that causes any concern.)

**Comment by jilladams** [comment]
Merge ok'ed, https://dsva.slack.com/archives/C01K37HRUAH/p1678750158858839?thread_ts=1678747326.719939&cid=C01K37HRUAH.

**Comment by jilladams** [comment]
Verified on Staging. Will deploy to prod tomorrow.

**Comment by jilladams** [comment]
Same - Changes are live and verified on Production, @RLHecht . Closing.
