### ISSUE TITLE
Improve unauthenticated homepage 

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#1269]
We held a December 10th design workshop and [the outcome of that is in this mural](https://app.mural.co/t/vagov6717/m/vagov6717/1639116803499/4d8afbb1f64096998231a5021ad60f0b58ccf0ba?sender=kevinwalsh8610)

**Comment by tjheffner** [comment]
newest mockup: https://www.figma.com/file/w0z1NIdY7nent0Q6r7hjTD/Login-page?node-id=304%3A3

- add a toggle that lets us switch between PIV login & user/pw without changing URL
- update header logo + title

**Comment by tjheffner** [comment]
All sub issues have been completed here :tada:
