### ISSUE TITLE
[CMS-CI] cannot choose master branch when rebuilding environment

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#1270]
**Expected behavior**
Should be able to select master branch when rebuilding environment.

**Screenshots**

master branch missing
<img width="1194" alt="Screen Shot 2020-03-18 at 11 49 11 AM" src="https://user-images.githubusercontent.com/16477724/76991089-a7915680-690e-11ea-9856-2289ae64ff73.png">

## Labels
- [/] Issue type (red) (defaults to "Defect")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [/] CMS objective (orange) (not needed for bug tickets)
- [ ] CMS-supported product (black)

**Comment by ElijahLynn** [comment]
Closing for now as we are likely moving off of DevShop and this functionality will be moved to the CMS.
