### ISSUE TITLE
UX: comparative study of search and filter UI across PW products

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#12719]
### User story

**AS A(N)** Veteran
**I WANT** to have a consistent experience across search products on VA.gov
**SO THAT** my cognitive load is minimized.

### Engineering notes / background
Search is built using Search.gov.

## Acceptance criteria
- [ ] Compare UIs across search & filter products
  - [ ] R&S, 
  - [ ] Find a Form, 
  - [ ] Outreach Events, 
  - [ ] Find a Yellow Ribbon school, 
  - [ ] Site search
- [ ] Consult design system for latest thinking on patterns for search and filters

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [X] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`

**Comment by jilladams** [comment]
Sprint planning Note: 
* Search/filter will also appear on Facility Locator
* Consistency is good, but bespoke experiences may be necessary in some cases for satisfying some user flows. "Design debt" = our team should be mindful of whether updates / alignment are value add for Veterans. 
  * Ideally data driven to prove whether Veterans are having trouble with the different experience.

**Comment by wesrowe** [comment]
Per Dave, this is low priority until we hear that Veterans are having issues that consistency would help solve.

**Comment by jilladams** [comment]
From today: this may have a little crossover with Facility Locator design project to add search to existing filters. Re: whether or not Veterans have this issue / have reported it, we wonder: is there a way to help answer that with data, and maybe (tbd load), is this a thing Jordan could help answer? Cindy may have related notes from her recent work reviewing Medallia data.

**Comment by FranECross** [comment]
Closing; a new ticket will be created if/when we revisit this and it becomes a quarterly goal.
