### ISSUE TITLE
Review Medallia/CSAT survey results for 3 or 4 products in PW portfolio

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#12718]
### User story
> _Describe the audience/user, enhancement or fix, and value / outcome desired._

**AS A(N)** 
**I WANT** 
**SO THAT** 

## Acceptance criteria

>Consider 
> - Design / Accessibility reviews
> - Collab cycle requirements
> - Device sizes (mobile first)
> - Documentation updates / Change management
> - Testing notes

- [ ] Review Medallia user feedback and document big issues/insights in [PW portfolio excel](https://dvagov-my.sharepoint.com/:x:/r/personal/wesley_rowe_va_gov/Documents/PW%20portfolio.xlsx?d=w2c8c26b2b1f0446ca786971396f14eb8&csf=1&web=1&e=782NQ6) – column "Pain points from Medallia feedback" – for 3 or 4 products, including Discharge Upgrade Wizard
  - [x] Discharge upgrade wizard
  - [x] header/footer
  - [ ] outreach events
  - [x] Find a yellow ribbon school
- [x] Also collect findings in a working doc if appropriate (edit out PII)
- [ ] Schedule meeting with Wes, Jill, Jordan to discuss findings

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [X] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`

**Comment by cindymerrill** [comment]
Went through all Medallia feedback from Discharge Update Wizard, and documented one thing in the [PW portfolio spreadsheet](https://dvagov-my.sharepoint.com/:x:/r/personal/wesley_rowe_va_gov/Documents/PW%20portfolio.xlsx?d=w2c8c26b2b1f0446ca786971396f14eb8&csf=1&web=1&e=d5Ztc3) and one quote in a [new google doc](**url**)

**Comment by wesrowe** [comment]
@cindymerrill, I've recently mastered using pivot tables to count respondents' numerical responses (eg, 1-5 on satisfaction). Lmk if you'd like me to show you or just do that for your data at some point, once it's available on the cloud.

**Comment by cindymerrill** [comment]
Cool, @wesrowe ! It would be great if you could show me at some point, but for now I was only looking at the qualitative responses.

**Comment by cindymerrill** [comment]
Went through all Medallia feedback from Global header/footer and part of Outreach Events. Documenting a summary of my findings in the [PW portfolio spreadsheet](https://dvagov-my.sharepoint.com/:x:/r/personal/wesley_rowe_va_gov/Documents/PW%20portfolio.xlsx?d=w2c8c26b2b1f0446ca786971396f14eb8&csf=1&web=1&e=d5Ztc3) and all the verbatims in a [new spreadsheet](https://dvagov-my.sharepoint.com/:x:/r/personal/cynthia_merrill_va_gov/Documents/Public%20Websites/Medallia%20survey%20data%2011-01-22%20to%2002-12-23/Medallia%20Verbatims%20re%20PW%20Products%2011-01-22--02-12-23.xlsx?d=wcfd4b2a16db745ceba69f2acbf6126a5&csf=1&web=1&e=UC8LWh).

**Comment by cindymerrill** [comment]
Analyzed more Medallia feedback on Outreach Events but didn't finish. Found not much data on Yellow Ribbon so analyzed that.

**Comment by cindymerrill** [comment]
Reviewed the rest of the feedback on Outreach Events and analyzing it. Plan to summarize it into portfolio spreadsheet tomorrow and schedule a review meeting before end of sprint.

**Comment by cindymerrill** [comment]
Talked with Wes today about how to use Excel pivot tables to quickly tally my Outreach Events data by tag counts. 

Also discussed how writing up a short summary of the findings would be helpful because it's too much for the single cell in the Portfolio spreadsheet, and I plan to do a short writeup for any product with a lot of user feedback. Wes created a [new ticket for this work] (https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12793#event-8631020729).

I'll also move my discussion of user survey findings with Wes, Jill, and Jordan to the Outreach and Events ticket.
