### ISSUE TITLE
"Where should this be listed?" select lists on listing item content types are not filtered by section

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#12737]
## Describe the defect
Within the CMS, on listing content types (i.e. Event, Story, News Release) there is a dropdown to choose where the story should be listing, which section.  However, this dropdown is not filtered according to the section the user has permissions for.

## To Reproduce
1. In staging, login as the test user "QA Content Publisher". This user is a Content Publisher and only has access to VA Boston
2. Create a new node for a story: https://staging.cms.va.gov/node/add/news_story
3. Click on the "Where should the story be listed?" dropdown.
4. Note that all VAMCs are displaying, instead of just the one I have access to.

## AC / Expected behavior
[ ] Determine if this is intentional behavior or if this should be filtered to only display sections the user has permissions for

## Screenshots
![image](https://user-images.githubusercontent.com/106678594/221022932-68115024-7c05-41f5-802e-bddc41d8c2d8.png)

 ## Additional context
I found this when I was on a meeting with Swirt, he was trying to think of or remember why this may have been architected in this way.  He couldn't remember anything off the top of his head but it's definitely something that we maybe want to investigate more and see if there was a reason before changing it.

### Team
Please check the team(s) that will do this work.

- [x] `CMS Team`
- [ ] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`

**Comment by davidmpickett** [comment]
This definitely seems like a regression.
The [knowledge base article for stories](https://prod.cms.va.gov/help/va-medical-centers-vamcs/about-stories-content-for-vamcs/how-to-add-a-story) states:

> Using the Where should the story be listed? dropdown, select which site the story should appear on.
> For example, selecting VA Pittsburgh health care means your story will appear on the VA Pittsburgh’s Stories page.
> **If you only have permission to edit one section, you will only have one option in this dropdown menu.**

The [training video for adding an event](https://www.youtube.com/watch?v=PYU7eSmlZTc) shows this select list being winnowed:

![Screenshot 2023-08-21 170300](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/5a10ff24-f11c-4a4c-87c8-c9cce02ba6a2)

**Comment by chri5tia** [comment]
Entity reference (`admin/structure/types/manage/news_story/fields/node.news_story.field_listing`) to a view content_entity_reference_source (`admin/structure/views/view/content_entity_reference_source`). May be addressed by changing the view's permissions, which is currently set to published content. I am not sure how/where "the winnower" comes into affect with this, however.

**Comment by davidmpickett** [comment]
This might be resolved by @omahane's work on #15901

**Comment by swirtSJW** [comment]
This is closed by https://github.com/department-of-veterans-affairs/va.gov-cms/pull/16663

**Comment by jilladams** [comment]
![Screenshot 2024-01-09 at 4 02 26 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/85581471/d1b14e9e-3e87-4593-a9e5-08bd28bd1195)

Verified.
