### ISSUE TITLE
Better content proofing for embedded alerts on benefits detail pages

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#1273]
## User Story or Problem Statement

As an editor of benefits detail page, i want a better way to browse and place existing alert blocks on my page, and to review them on the content proofing page.

## Acceptance Criteria
* From /node/3014/edit, i open an alert block browser and filter and choose any alert, in the Alert field above Featured content 
* Also on /node/3014/edit, i can place an "Alert" content block and use the same widget to find and place an existing alert (or add a non-reusable alert)
* On /node/3014, i can see the content of an alert block, instead of just a link to edit it.

**Comment by kevwalsh** [comment]
@rachel-kauff  Short notice, but let's get a release note for this today if possible. There are gifs and screenshots on https://github.com/department-of-veterans-affairs/va.gov-cms/pull/1274

**Comment by rachel-kauff** [comment]
@kevwalsh  Got it. I assume today= after 3:30 deploy, yes?
