### ISSUE TITLE
Finish drafting BCM spec

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#12736]
### User story
> _Describe the audience/user, enhancement or fix, and value / outcome desired._

**AS A** content designer
**I WANT** to get the BCM spec to an internally consistent state
**SO THAT** it will drive an efficient review from colleagues

### Engineering notes / background
(Work carried over from s78)
- [In-progress spec](https://docs.google.com/spreadsheets/d/1gP6x-QLFRrJlLWdCEE1COAZXU-kRRmFKSc0sIlc_tyM/edit?usp=sharing) (Google Sheet)
- [Airtable](https://airtable.com/appjh4Bp3A7CCUNkm/tblh1P8UIHY4QunLK/viw0edc5JNKbTNBJq?blocks=hide)

## Acceptance criteria

Dave P will focus on the following in this ticket:
- [x] Only working on "VA Benefit Content type" tab for now, because we want to get some parts locked down that will be copied to the "VA form content type" 
- [x] Column B populated - makes sure that all the fields that this model needs are added
- [x] Column D populated - "What is this field for?"
- [x] Row 2 populated
- [x] Row 3 populated
- [x] Review with @chri5tia for feedback before closing the ticket

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [X] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`

**Comment by davidmpickett** [comment]
Will be in tandem with https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12736

**Comment by davidmpickett** [comment]
From Facilities Sprint planning today, my capacity this sprint is entirely over there, so I won't be able to move this forward. Might be worth chatting about whether others can move it forward

**Comment by jilladams** [comment]
@wesrowe If this should be reported on in Sprint 79, will you add the Sprint to it, and a status note?

**Comment by wesrowe** [comment]
Scheduling of internal spec review is in progress, but now I see it's not even an AC. Closing.

**Comment by wesrowe** [comment]
@jilladams, I just added the sprint value (late) – sorry!

**Comment by jilladams** [comment]
No points, so no impact to reporting, but thanks for flagging!
