### ISSUE TITLE
[cms-ci] CI DB is 4 days old

### ISSUE THREAD

**Issue by ElijahLynn** [department-of-veterans-affairs/va.gov-cms#1275]
Problem: The DB for CI environments is 4 days old. 

Solution: I had run the `cms-db-download` script manually as my `elijahlynn` user while working on the files sync story and it saved it to /tmp with those permissions. Then the 10 minute cron that ran as `aegir` didn't have perms to overwrite it. 

I deleted the file and all is well now.

**Comment by kevwalsh** [comment]
nice find!
