### ISSUE TITLE
Draft Content Model for VBA Regional Office MVP

### ISSUE THREAD

**Issue by davidmpickett** [department-of-veterans-affairs/va.gov-cms#12769]
## Description

As a Facilities Team member, I need to understand the possible ways that VBA Facility content can be structured so that I can chose the one that aligns best with our goals for the Regional Office MVP.

As a CMS Platform team member, I need a document of the proposed content model to review as part of the CMS collaboration cycle for the Regional Office MVP. 

As a Regional Office MVP stakeholder, I need a high level summary of the plan so I can connect it to internal VBA resources.

**Main question - how are we modeling relationship between VBA Facility types?**
- VBA Regional Office
- VBA Satellite Office
- VBA Facility 
   - How does this relate to Regional Office and Satellite Office? 
   - Are they subtypes? split off? 
   - Is this just a husk that contains the other VBA facility types not being hardened at this time?

**Other MVP / Fast Follow items to address**
- Top Tasks
   - Make an appointment
- VBA Operating Status (see also #10808)
- VBA Facility Service (previously addressed in #11250)
- Events?
- Leadership?
- Banners?
- Connections to benefit hubs?

**Lenses to consider**
- External data sources - is any of this in VAST / lighthouse? / what are we pushing /pulling?
- What is local / national?
- Is connecting to VERA for appointments hardened or blobby?
- Which existing content types / reusable fields may need updates?

## Acceptance Criteria
- [x] Draft content model for workshop
- [x] Hold first workshop with Dave C
- [x] Revise content model based on workshop feedback
- [x] Second workshop is scheduled

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [ ] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`

**Comment by davidmpickett** [comment]
@kmariepat-cityfriends FYI, just cleaned this up in advance of refinement tomorrow. Mostly just following the pattern of #11250

**Comment by jilladams** [comment]
Looks like this got marked as High Priority / sprint goal mid-sprint during a lane change in the board, so removed the High Prio flag.

**Comment by davidmpickett** [comment]
VBA area of the main Content Model updated:
https://app.mural.co/t/vagov6717/m/vagov6717/1658937741729/88cc653ce1bed251e60940c147867eb061496070?wid=1-1663969676087

**Comment by davidmpickett** [comment]
mural with iterations and notes: https://app.mural.co/invitation/mural/vagov6717/1677277602711?sender=u9c899abc4fe36c9a698b1647&key=6da67540-4d0d-4aa4-826b-db416b0fec7b

Detailed specifications will be created in https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13096 or resulting tickets
