### ISSUE TITLE
VA Lovell: Pharmacy page is incorretly found under "Programs" - see #54300

### ISSUE THREAD

**Issue by Dottisea** [department-of-veterans-affairs/va.gov-cms#12789]
see Components and pattern standards] The components of the navigation system (i.e. URL, breadcrumb, left nav) within your content or feature don't accurately and/or consistently represent the location of the page within the IA. (04.01.1) #54300

https://github.com/department-of-veterans-affairs/va.gov-team/issues/54300#:~:text=The%20components%20of%20the%20navigation%20system%20(i.e.%20URL%2C%20breadcrumb%2C%20left%20nav)%20within%20your%20content%20or%20feature%20don%27t%20accurately%20and/or%20consistently%20represent%20the%20location%20of%20the%20page%20within%20the%20IA.%20(04.01.1)%20%2354300

**Comment by davidmpickett** [comment]
FYI - I updated the parent link for the VA version of the Pharmacy page on production, but didn't touch the TRICARE one yet. @TroyA6

**Comment by TroyA6** [comment]
@davidmpickett @Dottisea I have been in meetings, and have two more coming up -- I will look ASAP after the remaining meetings.

**Comment by TroyA6** [comment]
@Dottisea @davidmpickett - I believe that should do it. Pharmacy link under TRICARE / Programs has been disabled.
