### ISSUE TITLE
Add to tasks.yml to ensure monthly delivery of CMS 6102 Notification Email to VAMC editors

### ISSUE THREAD

**Issue by EWashb** [department-of-veterans-affairs/va.gov-cms#12783]
## Background
We are currently only setting up the automated task to send emails out to VAMCs editors to start with. 

To ensure that the 6102 notification emails are sent monthly to these VAMC editors within the appropriate cron queue, tasks.yml must be enabled for proper delivery aka sending emails without elevated risk. 

## User Story

As a CMS developer, I need tasks.yml appropriately configured so that I can ensure 6102 notification emails are sent on the proper cadence for VAMC editors only. 

## Acceptance Criteria

- [ ] wait to do until May 1st at least
- [ ] Monthly `task` job is created starting at 3am ET on the last day of the month
- [ ] Email queue is populated once per month and not more than once per month

**Comment by laflannery** [comment]
Edmund and Elijah/Eric to pair

**Comment by laflannery** [comment]
Removed from s81 due to [this comment](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12870#issuecomment-1479693454)
