### ISSUE TITLE
New KB Article: Outdated Content Editorial Workflow

### ISSUE THREAD

**Issue by EWashb** [department-of-veterans-affairs/va.gov-cms#12784]
## Background context
**What is the request for?**
This article should detail the editorial workflow process for when editors receive a CMS notification regarding outdated content. We do have [an article](https://prod.cms.va.gov/help/cms-basics/outdated-content-audit-tool) already on the outdated content audit tool that we could link to this one, or updated and just use instead of creating a new one. 

**Person and team of requester:** 
- Erika Washburn/Dawn Pruitt- CMS Team

**Priority or deadline for request**

  Choose either Deadline or a priority: 
  
- [ ] Deadline: End of Q1 2023/March 2023- linked to code merging with #12703 
- [ ] Priority: 
  - [X] Critical - Without this, there is a large negative impact on the majority of editors causing negative consequences within the CMS; Should be completed as soon as possible
  - [ ] High - Without this, there is negative impact on some editors causing negative consequences within the CMS; should be completed within the current sprint
  - [ ] Medium - Without this, there is confusion for editors but not causing negative consequences within the CMS; Should be completed within the next 1-2 sprints
  - [ ] Low - This is not currently causing confusion for many editors but would be a nice to have or is something that may be more impactful in the future; Should be completed within the next 3-4 sprints
  

**Is the article associated with an ongoing product or feature update?**
- [X] Yes #10477 
- [ ] No

  
## If requesting a new article:

**Audience:**
Who is this intended for? Who would need this information? All editors will receive an outdated content email notification 
- All products/all editors

**Related KB articles, if applicable:** 
- https://prod.cms.va.gov/help/cms-basics/outdated-content-audit-tool

  
**Any other relevant documentation, if applicable:** 
- We will need to send a draft of this information to stakeholders such as VHA Digital Media and Vet Centers

## Process
1. Sitewide CMS and Helpdesk teams will review request and confirm no current, applicable KB article/content exists.
2. Refine request and prioritize
3. Update KB article tracker to indicate that the article has been requested and is in progress
4. Assign to appropriate product team
5. Draft article content 
6. Sitewide CMS team will review for formatting and writing style guidelines
7. Helpdesk team will review for functionality and editorial tone
8. Publish
9. Update KB article tracker to indicate that the article has been published

## Acceptance Criteria
- [x] Article is created using [KB content style guidelines](https://va-gov.atlassian.net/wiki/spaces/VAGOV/pages/1771831299/Knowledge+Base+content+style) 
- [x] Article is reviewed by CMS Team
- [ ] Article published to KB 
- [ ] Impacts on other KB articles have been considered and any necessary changes have been made
- [ ] Once published, the person requesting the article has been notified

**Comment by laflannery** [comment]
@EWashb Yes, I think we are going to want something different - or this is going to need an entire overhaul. I can definitely work on this this sprint

**Comment by EWashb** [comment]
I just realized we may need another regarding "what it takes to be complaint with VA Directive 6102" but we could tie it all into one I think

**Comment by laflannery** [comment]
- [Outdated content article](https://prod.cms.va.gov/node/51112/latest) is revised and updated
- [New VA Directive 6102 article](https://prod.cms.va.gov/help/va-directive-6102) created and set as draft 
Both currently in draft and waiting will publish with launch of notifications

**Comment by laflannery** [comment]
Articles were approved to publish, they are ready to go for launch of notifications at the end of the month
