### ISSUE TITLE
Move facility logic for VAMC system health service descriptions into va_gov_facilities

### ISSUE THREAD

**Issue by JayDarnell** [department-of-veterans-affairs/va.gov-cms#12787]
## User Story or Problem Statement

This issue relates to work completed in the following PR: https://github.com/department-of-veterans-affairs/va.gov-cms/pull/12720

More specifically, this has to do with some of the code that currently resides in the `modules/custom/va_gov_backend/js/displayServiceDescriptions.es6.js` file. Most, if not all, of this code - and the code found in `modules/custom/va_gov_backend/src/EventSubscriber/EntityEventSubscriber.php` to add this javascript library using a form alter - should be moved to the more appropriate va_gov_facilities custom module. 

Functionally this work shouldn't result in any changes. This is simply a matter of cleaning up our code so individual functions reside in their most logical code buckets (modules).

### Acceptance Criteria
- [x] I expect JS libraries and the appropriate hooks responsible for calling those libraries, are moved from one custom module to the most appropriate va_gov_facilities custom module
- [x] Specifically this file:`modules/custom/va_gov_backend/js/displayServiceDescriptions.es6.js` file. AND this file `modules/custom/va_gov_backend/src/EventSubscriber/EntityEventSubscriber.php`

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [ ] `Public Websites`
- [x] `Facilities`
- [ ] `User support`

**Comment by maxx1128** [comment]
My estimate: **1-2**

This is just moving code around, although the placement looks a little more complicated given the file locations. I'm not as familiar with these modules, so I'm between a 1 and 2.

**Comment by JayDarnell** [comment]
Nothing to add. This is merely a matter of moving some JS libraries and the appropriate hooks responsible for calling those libraries from one custom module to another.

**Comment by swirtSJW** [comment]
There are a bunch of event subscribers that need to be moved.  This is more than a two just for coming up with QA steps to validate nothing broke.
