### ISSUE TITLE
[cms-ci] Rebuild Environment not pulling new commits from upstream va-gov/web

### ISSUE THREAD

**Issue by ElijahLynn** [department-of-veterans-affairs/va.gov-cms#1278]
Rebuild Environment not pulling new commits from upstream va-gov/web and in addition, it is resetting the previous composer require composer.json/lock changes as well. 

Here is what it looks like triggering a rebuild on a previously triggered upstream of va-gov/web. You can see it resets the code and does not do another require to get the upstream commits. 

![image](https://user-images.githubusercontent.com/1504756/77119486-cb7a9800-69f3-11ea-8dd1-811bec566f6e.png)

**Comment by indytechcook** [comment]
This occurs because the composer.lock file has the commit in it.  The solution is to have dependabot updates the composer.lock file on every release which is covered in #910

**Comment by indytechcook** [comment]
Closing since #910 is in.
