### ISSUE TITLE
Redirect Request: Vet Centers/outstations still needing redirects

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-cms#12794]
### Instructions
- Requests must be submitted **AT LEAST** 2 weeks in advance.  Some requests take a significant amount of time and coordination to implement, so start the process as soon as you know you will need one. 
- This issue will be used from initial request through implementation to ensure all individuals working on this are notified of status updates.  Please do not create multiple issues to track differnt steps.
- It is your responsibility to notify VA stakeholders as appropriate.  

### Type of request
- [x] We are retiring or taking down a page and need to redirect the URL (complete redirect section)
- [ ] We are changing the URL of an existing page (complete redirect section)
- [ ] We need a custom vanity URL (complete vanity URL section)

### Implementation date
When does this request need to be live?
Choose one:
- [ ] On a specific date, connected to a program or publishing requirement. **DATE:**
- [ ] Any day prior to a deadline/latest possible date. **DEADLINE:** 
- [ ] Any day after an earliest possible date. **EARLIEST DATE:**
- [ ] During a specific date range: ***EARLIEST DATE TO LATEST DATE:***
- [x] No hard timing requirements, publish when possible.

### Redirects 
Current URL  |  Redirect Destination or New URL
---  |  ---
www.va.gov/find-locations/facility/vc_4061OS | https://www.va.gov/fargo-vet-center/
https://www.va.gov/directory/guide/facility.asp?ID=6443&dnum=All | https://www.va.gov/fargo-vet-center/
https://www.va.gov/directory/guide/keystaff.cfm?id=6443 | https://www.va.gov/fargo-vet-center/
www.va.gov/find-locations/facility/vc_0844MVC | https://www.va.gov/knoxville-vet-center/
www.va.gov/find-locations/facility/vc_0720V | https://www.va.gov/knoxville-vet-center/
https://www.va.gov/directory/guide/facility.asp?ID=6187&dnum=All | https://www.va.gov/knoxville-vet-center/
https://www.va.gov/directory/guide/keystaff.cfm?id=6187 | https://www.va.gov/knoxville-vet-center/
www.va.gov/find-locations/facility/vc_0806MVC | https://www.va.gov/lexington-vet-center/
https://www.va.gov/directory/guide/facility.asp?ID=652&dnum=All | https://www.va.gov/savannah-vet-center/
www.va.gov/find-locations/facility/vc_4421OS | https://www.va.gov/la-crosse-vet-center/
https://www.va.gov/directory/guide/facility.asp?ID=6177&dnum=All | https://www.va.gov/la-crosse-vet-center/
https://www.va.gov/directory/guide/keystaff.cfm?id=6177 | https://www.va.gov/la-crosse-vet-center/
www.va.gov/find-locations/facility/vc_3121OS | https://www.va.gov/san-juan-vet-center/
https://www.va.gov/directory/guide/facility.asp?ID=685&dnum=All | https://www.va.gov/san-juan-vet-center/
https://www.va.gov/directory/guide/keystaff.cfm?id=685 | https://www.va.gov/san-juan-vet-center/
www.va.gov/find-locations/facility/vc_3122OS | https://www.va.gov/san-juan-vet-center/
https://www.va.gov/directory/guide/facility.asp?ID=686&dnum=All | https://www.va.gov/san-juan-vet-center/
https://www.va.gov/directory/guide/keystaff.cfm?id=686 | https://www.va.gov/san-juan-vet-center/

### Vanity URLs 
Vanity URL  |  Landing page
---  |  ---
requested URL | landing page URL

**Link to campaign landing page request issue:**

### Process, Roles and Responsibilities
- [ ] Requesting team: Above information is provided
- [ ] Requesting team: All appropriate VA stakeholders are notified as appropriate
- [ ] IA: Request is vetted and documented and implementation plan is clear 
- [ ] IA: Request is assigned to appropriate team for implementation 
- [ ] Implementation team: Work is complete
- [ ] Implementation team: Validated in production
- [ ] Requesting team: Validates everything is correct in production and closes ticket

**Comment by jilladams** [comment]
Thanks! Moved to our repo and queued for Sprint planning. Should get done in Sprint 79, starting tomorrow.

**Comment by chri5tia** [comment]
- [x] www.va.gov/find-locations/facility/vc_4061OS | https://www.va.gov/fargo-vet-center/
- [x] https://www.va.gov/directory/guide/facility.asp?ID=6443&dnum=All | https://www.va.gov/fargo-vet-center/
- [x] https://www.va.gov/directory/guide/keystaff.cfm?id=6443 | https://www.va.gov/fargo-vet-center/
- [x] www.va.gov/find-locations/facility/vc_0844MVC | https://www.va.gov/knoxville-vet-center/
- [x] www.va.gov/find-locations/facility/vc_0720V | https://www.va.gov/knoxville-vet-center/
- [x] https://www.va.gov/directory/guide/facility.asp?ID=6187&dnum=All | https://www.va.gov/knoxville-vet-center/
- [x] https://www.va.gov/directory/guide/keystaff.cfm?id=6187 | https://www.va.gov/knoxville-vet-center/
- [x] www.va.gov/find-locations/facility/vc_0806MVC | https://www.va.gov/lexington-vet-center/
- [x] https://www.va.gov/directory/guide/facility.asp?ID=652&dnum=All | https://www.va.gov/savannah-vet-center/
- [x] www.va.gov/find-locations/facility/vc_4421OS | https://www.va.gov/la-crosse-vet-center/
- [x] https://www.va.gov/directory/guide/facility.asp?ID=6177&dnum=All | https://www.va.gov/la-crosse-vet-center/
- [x] https://www.va.gov/directory/guide/keystaff.cfm?id=6177 | https://www.va.gov/la-crosse-vet-center/
- [x] www.va.gov/find-locations/facility/vc_3121OS | https://www.va.gov/san-juan-vet-center/
- [x] https://www.va.gov/directory/guide/facility.asp?ID=685&dnum=All | https://www.va.gov/san-juan-vet-center/
- [x] https://www.va.gov/directory/guide/keystaff.cfm?id=685 | https://www.va.gov/san-juan-vet-center/
- [x] www.va.gov/find-locations/facility/vc_3122OS | https://www.va.gov/san-juan-vet-center/
- [x] https://www.va.gov/directory/guide/facility.asp?ID=686&dnum=All | https://www.va.gov/san-juan-vet-center/
- [x] https://www.va.gov/directory/guide/keystaff.cfm?id=686 | https://www.va.gov/san-juan-vet-center/

**Comment by jilladams** [comment]
Verified in Prod today, cuz I was looking at the PR for catch up purposes. Thanks for knocking these out!

**Comment by chri5tia** [comment]
Didn't see that you checked these. Guess I double-checked them. :)
