### ISSUE TITLE
Analyze Medallia survey data for New Homepage for first 2 weeks in prod

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#12790]
### User story

**AS A** Product Owner
**I WANT** to understand the feedback Veterans are providing about the new homepage
**SO THAT** I can decide what action to take to improve it and whether to increase rollout.

## Acceptance criteria
- [x] Gave Ian McCullough a heads up via Slack DM about quick pull of data
- [x] Planned request ticket, and submitted at EOD Mar 7
- [x] Obtained first 2 weeks of prod Medallia data, both intercept modal and feedback button
- [x] **For feedback button data**, created spreadsheet analysis of that data that includes:
  - [x] Verbatims collected in a separate sheet
  - [x] Verbatims tagged to categorize (as appropriate)
  - [x] Tallied satisfaction scores btw 1-5 (optional)
- [x] **For Intercept modal analysis**, review/analyze qualitative feedback only (rationale: intercept is only 20 seconds into session, not enough time to assess quantitative ratings)
- [x] High-level summary of findings is saved as markdown file in homepage product folder on github
  - [x] added folder in github [metrics-and-analytics-2023](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/public-websites/home-page/home-page-redesign-initiative/metrics-and-analytics-2023)
- [x] Assets like excel file with verbatims are saved alongside markdown report

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [X] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`

**Comment by cindymerrill** [comment]
@wesrowe I gave Ian McCullough a heads up about our data request. I'll plan to submit it on Tuesday, and he plans to pull the data on Wednesday.

**Comment by cindymerrill** [comment]
Submitted request for 2 weeks of data. Ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/54761

**Comment by cindymerrill** [comment]
Got data. I summarized qualitative verbatims, and @wesrowe  generated pivot tables for the quantitative ratings. All summarized in this spreadsheet: https://dvagov-my.sharepoint.com/:x:/r/personal/cynthia_merrill_va_gov/Documents/Public%20Websites/Home%20page%20baseline%20and%20redesign/[medallia_newHomePage-first2weeks.xlsx](https://dvagov-my.sharepoint.com/:x:/r/personal/cynthia_merrill_va_gov/Documents/Public%20Websites/Home%20page%20baseline%20and%20redesign/medallia_newHomePage-first2weeks.xlsx?d=w0730df42875049e8b264c9ca2a540358&csf=1&web=1&e=My7V9j)?d=w0730df42875049e8b264c9ca2a540358&csf=1&web=1&e=My7V9j

Need to talk about how to share these findings.

**Comment by cindymerrill** [comment]
Here's my summary of the qualitative data:

![image (28)](https://user-images.githubusercontent.com/69914583/224106274-0ac5b16b-265d-4565-ba5c-24e89b7c6ac0.png)

Per conversation with @wesrowe , that's all I'm going to do on this ticket for now (so that I can focus on Income Limits research and analyzing 2022 data from the current home page).

**Comment by jilladams** [comment]
@cindymerrill is this spreadsheet (https://dvagov-my.sharepoint.com/:x:/g/personal/cynthia_merrill_va_gov/EULfMAdQh-hJsmTJyipUA1gBKBYmB553lw66jZkyMrmKaw?e=KcrUB0) the one I need to push to Github?

**Comment by cindymerrill** [comment]
No, that's for the home page. The one you're supposed to push is for Outreach Events, but I need to make a change to it first, which is why I haven't shared it yet. @jilladams

**Comment by cindymerrill** [comment]
@wesrowe @jilladams Should the data in the comments of this ticket be saved somewhere on github, or should I just close the ticket?

**Comment by wesrowe** [comment]
@cindymerrill, I referenced it in #12160 and that's enough for now. I anticipate returning to it for a longer timeframe when we approach the decision to make the New HP the Actual HP.

**Comment by jilladams** [comment]
@wesrowe ok to close?

**Comment by wesrowe** [comment]
Created folder, uploaded assets. See AC above for link
