### ISSUE TITLE
Write quick summary of Outreach & Events qualitative feedback from Medallia

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#12793]
### User story
> _Describe the audience/user, enhancement or fix, and value / outcome desired._

**AS A(N)** member of the Public Websites team
**I WANT** to understand current user feedback on the Outreach and Events product
**SO THAT** we can consider whether we should try to work on it

## Acceptance criteria

- [x] Documented quick summary of findings (pivot tables in a new worksheet in verbatims spreadsheet)
- [x] Decided how to shared findings with others in slack/github (i.e., PDF of pivot tables + attached verbatims spreadsheet with PII removed?)
- [x] Scheduled meeting with Wes, Jill, Jordan to discuss findings

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [X] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`

**Comment by cindymerrill** [comment]
Scheduled review meeting with Wes, Jill, and Jordan, which is now happening tomorrow (Mar 2)

**Comment by cindymerrill** [comment]
Discussed on Mar 2. Next steps:

- [ ] fix feedback summary of event issues vs. finding event issues
- [ ] check proportion of feedback from which survey
- [ ] look at Florence's design in figma for event editing

**Comment by cindymerrill** [comment]
Per @wesrowe 's request, here are links to my [spreadsheet with verbatims and analysis](https://dvagov-my.sharepoint.com/:x:/r/personal/cynthia_merrill_va_gov/Documents/Public%20Websites/Medallia%20survey%20data%2011-01-22%20to%2002-12-23/Medallia%20Verbatims%20re%20O%26E,%20DischargeUpgrade,%20YellowRibbon%2011-01-22--02-12-23.xlsx?d=wcfd4b2a16db745ceba69f2acbf6126a5&csf=1&web=1&e=183iBR) and the [file containing all Medallia feedback](https://dvagov-my.sharepoint.com/:x:/r/personal/cynthia_merrill_va_gov/Documents/Public%20Websites/Medallia%20survey%20data%2011-01-22%20to%2002-12-23/[publicWebsites--11-01-22--02-12-23.xlsx](https://dvagov-my.sharepoint.com/:x:/r/personal/cynthia_merrill_va_gov/Documents/Public%20Websites/Medallia%20survey%20data%2011-01-22%20to%2002-12-23/publicWebsites--11-01-22--02-12-23.xlsx?d=w72951a174ed34db38aaf480596c8a5a6&csf=1&web=1&e=8Zs0Lu)?d=w72951a174ed34db38aaf480596c8a5a6&csf=1&web=1&e=8Zs0Lu)

**Comment by jilladams** [comment]
1:1 with Cindy: 
- Income limits is unstuck, so that's priority now.
- Cindy will add a screenshot of her summary here, but will not complete the final AC here, and we'll move this ticket out of sprint for future follow up as stretch.

**Comment by cindymerrill** [comment]
@jilladams  Here's the recommended path from Wes: 

A new "research" folder within this existing [outreach folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/outreach-events)

**Comment by cindymerrill** [comment]
Updated the Outreach & Events summary to include the count of issues/questions about specific events (103) vs. feedback on the interface to find events (19)

**Comment by cindymerrill** [comment]
Screenshots of Outreach & Events verbatim summary:
![image](https://user-images.githubusercontent.com/69914583/224456520-19e4fc57-fadb-456b-be64-10932c49066a.png)
![image](https://user-images.githubusercontent.com/69914583/224456911-b71a8ffd-bbff-4b05-aff8-b7c86e37661e.png)

These screenshots came from the **Outreach & Events SUMMARY** tab in [this spreadsheet](https://dvagov-my.sharepoint.com/:x:/g/personal/cynthia_merrill_va_gov/EaGy1M-3bc5FumnyrL9hJqUBKp32GvfLE4xwL2Pci9aJRg?e=BwtpGT) on SharePoint.

@jilladams Now this these screenshots and spreadsheet are ready for you to post on github.

**Comment by cindymerrill** [comment]
@jilladams I've done all that I have time to do on this for this sprint, so we can either close this ticket or put it into the backlog for additional analysis later.

**Comment by cindymerrill** [comment]
If we want to see which events generated the most feedback, we can look in the above spreadsheet in the **Verbatim** column in the **Vertabims** tab.

**Comment by jilladams** [comment]
Files added: https://github.com/jilladams/va.gov-team/tree/18121e76508e3ab7260105cb153afcf2da290424/products/outreach-events

**Comment by cindymerrill** [comment]
Thank you, @jilladams !
