### ISSUE TITLE
Analyze Medallia qualitative survey data for remaining PW portfolio products

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#12791]
Status:
[2024-04-04]  Carving off Resources & Support, and Search into their own tickets.

NOTE: should pull more recent data when we pick this up

### User story
**AS A(N)** member of the Public Websites team
**I WANT** to understand current user feedback on the products in the Public Websites portfolio
**SO THAT** we can consider if there are any that we should try to work

When writing ACs and estimating, check how many rows are present in remaining data.

### Notes / Background

Qualitative Medallia export was already requested in [this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/53598), which was closed (executed) on 3/1/23. Cindy may have access to that export.

## Acceptance criteria

- [ ] Data from the following products reviewed, analyzed, summarized into Portfolio spreadsheet and (if need more than a spreadsheet cell to summarize) in a quick summary doc...
  - [x] Find a form (long)
  - [x] Disability rating calculator
  - [x] Benefit hub landing pages (11 sets of data; only 1 of which is long)
- [ ] Discuss findings with Fran, Jill, and Dave C.

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [X] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`

**Comment by cindymerrill** [comment]
@wesrowe Wondering if this should be split into 2 tickets because it's so much data analysis. If so, maybe  Resources and Support and Search could together become a different ticket?

**Comment by cindymerrill** [comment]
@wesrowe I'm leaving the "Needs Refining" label on this until I hear from you about whether you want this to be 2 tickets or only 1.

**Comment by cindymerrill** [comment]
Just received more Medallia data on Search from Ian McCullough, which he had to request from another team. So when I'm ready to analyze the Search data, I have more of it.

**Comment by wesrowe** [comment]
refinement: @thejordanwood will find out from @cindymerrill what the state of this ticket is when they're both back in the office around 7/13.

**Comment by cindymerrill** [comment]
I haven't worked on this ticket for a while because I've been assigned other research projects that have taken all of my time. The products listed above are the ones that I haven't done any data analysis on. Is this the status that @thejordanwood is looking for?

**Comment by thejordanwood** [comment]
@cindymerrill Thanks Cindy! Yes, that's what I was looking for. I'm going to start working on this again and wanted to make sure I wasn't going to duplicate efforts.

**Comment by cindymerrill** [comment]
What will you be doing, @thejordanwood ? Analyzing survey data, or something more design related?

**Comment by jilladams** [comment]
From S89 planning: If @thejordanwood and/or @cindymerrill have capacity, both should connect re: what happens next here before work picks up.

**Comment by cindymerrill** [comment]
Started working on this ticket. 

Looked at [feedback on Disability Rating Calculator](https://dvagov-my.sharepoint.com/:x:/r/personal/cynthia_merrill_va_gov/Documents/Public%20Websites/Medallia%20survey%20data%2011-01-22%20to%2002-12-23/[publicWebsites--11-01-22--02-12-23.xlsx](https://dvagov-my.sharepoint.com/:x:/r/personal/cynthia_merrill_va_gov/Documents/Public%20Websites/Medallia%20survey%20data%2011-01-22%20to%2002-12-23/publicWebsites--11-01-22--02-12-23.xlsx?d=w72951a174ed34db38aaf480596c8a5a6&csf=1&web=1&e=JyOoHp&nav=MTVfezAwMDAwMDAwLTAwMDEtMDAwMC0wMjAwLTAwMDAwMDAwMDAwMH0)?d=w72951a174ed34db38aaf480596c8a5a6&csf=1&web=1&e=JyOoHp&nav=MTVfezAwMDAwMDAwLTAwMDEtMDAwMC0wMjAwLTAwMDAwMDAwMDAwMH0), summarized the little qualitative data that was there in my [Verbatims spreadsheet](https://dvagov-my.sharepoint.com/:x:/r/personal/cynthia_merrill_va_gov/Documents/Public%20Websites/Medallia%20survey%20data%2011-01-22%20to%2002-12-23/Medallia%20Verbatims%20re%20O%26E,%20DischargeUpgrade,%20YellowRibbon%2011-01-22--02-12-23.xlsx?d=wcfd4b2a16db745ceba69f2acbf6126a5&csf=1&web=1&e=X43VnB&nav=MTVfezAwMDAwMDAwLTAwMDEtMDAwMC0wMDAwLTAwMDAwMDAwMDAwMH0), and added it to the [PW Portfolio spreadsheet](https://dvagov-my.sharepoint.com/:x:/r/personal/wesley_rowe_va_gov/Documents/PW%20portfolio.xlsx?d=w2c8c26b2b1f0446ca786971396f14eb8&csf=1&web=1&e=iPa84P).

**Comment by cindymerrill** [comment]
Looked at [feedback on Find a Form](https://dvagov-my.sharepoint.com/:x:/r/personal/cynthia_merrill_va_gov/Documents/Public%20Websites/Medallia%20survey%20data%2011-01-22%20to%2002-12-23/[publicWebsites--11-01-22--02-12-23.xlsx](https://dvagov-my.sharepoint.com/:x:/r/personal/cynthia_merrill_va_gov/Documents/Public%20Websites/Medallia%20survey%20data%2011-01-22%20to%2002-12-23/publicWebsites--11-01-22--02-12-23.xlsx?d=w72951a174ed34db38aaf480596c8a5a6&csf=1&web=1&e=vLg6WH&nav=MTVfezAwMDAwMDAwLTAwMDEtMDAwMC0wNTAwLTAwMDAwMDAwMDAwMH0)?d=w72951a174ed34db38aaf480596c8a5a6&csf=1&web=1&e=vLg6WH&nav=MTVfezAwMDAwMDAwLTAwMDEtMDAwMC0wNTAwLTAwMDAwMDAwMDAwMH0), tagged the qualitative feedback, and then summarized in a pivot table.  and added it to the [PW Portfolio spreadsheet](https://dvagov-my.sharepoint.com/:x:/r/personal/wesley_rowe_va_gov/Documents/PW%20portfolio.xlsx?d=w2c8c26b2b1f0446ca786971396f14eb8&csf=1&web=1&e=iPa84P).

In the original data are my tags as well as YELLOW highlighting for specific form issues that could be shared with VBA/VHA form owners, which are also listed below:



Issue | Form number/description
-- | --
can't download form | 21-526
can't find form | 861
can't find form | 2237
can't find form | 3075
can't find form | 7468
can't find form | 0969 [can't replicate]
can't find form | 10-1281
can't find form | 1099R for my VA payments
can't find form | 20-0344
can't find form | 21-0960L-2
can't find form | 21-0960P-3
can't find form | 26-1880
can't find form | DD149 filled out online
can't find form | form to request a flag holder at cemetery
can't find form | search didn't find Form 21-4142 [can't replicate]
can't find form | travel pay
can't print form | 13055
can't print form | 21 p-4703
can't print form | only 3/4 of it prints
can't tab through fields on form [tab order wrong] | 526EZ [tab order IS wrong]
form outdated | 10-5345 and 10-5345a are both dated July 2021
form outdated | 21-22 says Feb 2019 and has expiration date of 2/28/2022
form outdated | most recent version of 26-6393 [can't replicate]
leading zeroes not allowed, so can't enter SSN that starts with a zero | 966 [couldn't replicate but maybe investigate more]
link not working | apply for Veteran ID card
link not working | disability compensation

</body></html></div>

**Comment by cindymerrill** [comment]
Started working on analyzing Benefit hub data.

**Comment by cindymerrill** [comment]
Have pulled out all relevant verbatims from ALL of the Benefit Hubs data into a new spreadsheet tab. Still need to review tags and summarize.

**Comment by cindymerrill** [comment]
Summary of Find a Form data that I put into the PW Portfolio spreadsheet:

- can't find a specific form (18, of which 3 for travel pay)
- can't print form (4)
- can't download form (4)
- form outdated, per old date on form (4)
- link not working (3)
- can't find document showing 100% disabled (2)
- leading zeroes not allowed, so can't enter SSN that starts with a zero	(1)
- can't tab through fields on form [tab order wrong]	(1)

**Comment by cindymerrill** [comment]
High-level summary of Benefit hubs verbatims, which I put into the PW Portfolio spreadsheet:

- couldn't do task (86)
- couldn't find info (38)
- confusing (7)
- couldn't follow links in email (4)

Could do additional analysis (if desired) on the specific tasks that people were trying to do but couldn't, and also of the information they were unable to find.

**Comment by cindymerrill** [comment]
@FranECross Perhaps this ticket should be moved back into Refined because I won't have time to get back to it for a while

**Comment by FranECross** [comment]
@cindymerrill Excellent idea. I'll scoot it back there. Thanks!

**Comment by aklausmeier** [comment]
@FranECross - @cindymerrill and I discussed this work as a potential next up, we may need to adjust and refine AC's but we can refine when this is ready to pull in

**Comment by FranECross** [comment]
Thank you, @aklausmeier !

**Comment by FranECross** [comment]
@aklausmeier I carved off the remaining features, Resources & Support, and Search, into their own tickets and am going to close this one. cc @thejordanwood @jilladams 

The new tickets are:
- #17731 
- #17730

**Comment by FranECross** [comment]
Closing per comment above.
