### ISSUE TITLE
[BLOCKED] [Discharge Upgrade Wizard] Implementation of Phase 2 content and flow changes.

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#12803]
### Status
[2024-05-07] Still blocked awaiting stakeholder feedback/changes for Phase 2. Phase 1 (subtask pattern; some text changes to questions) is being implemented now.

### Description
Phase 2 will have updates from stakeholders and any possible legal review updates as well.

### Acceptance Criteria
- [ ] The user flow is one question per page as shown in sketch
- [ ] Content changes for Phase 2 are made (TBD 2024)
- [ ] a11y review
- [ ] PM review

### Design
https://www.sketch.com/s/20ea8818-8846-4f47-b341-7dc0ee6fc57e

**Comment by jilladams** [comment]
@FranECross should this ticket be moved out of Blocked?

**Comment by FranECross** [comment]
@jilladams I realize I hadn't saved edits to this one, which is actually supposed to be Phase 2 (sometime in 2024). I edited and fiddled with what blocks what and I think the tickets are okay now. This one will remain blocked, and  #12801 is in Next Refinement, and is for the Phase 1 edits to be implemented. Thanks for catching this faux pas!
