### ISSUE TITLE
[Discharge Wizard] Phase 1 content changes from CAIA

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#12801]
## Status
**[2024-07-15] [Fran]** All Phase 1 content changes have been added to the individual DUW tickets for implementation. Closing this ticket, and a Phase 2 [Epic ticket ](https://app.zenhub.com/workspaces/vagov-sitewide-product-team-6645154188a81a1f7a0a9464/issues/gh/department-of-veterans-affairs/va.gov-cms/18517)is being created today.

## Description
CAIA reviewed the text for the Discharge Upgrade Wizard and provided updates where Stakeholder review/feedback is not needed. After the flow is changed to the substack pattern, these content changes should be implemented before we release the MVP of the wizard.

## Status

- 2023-01-04: Content changes provided by CAIA to be implemented after the substack pattern changes have been made. Then we'll release an MVP of the wizard. Phase 2 will entail text changes from Stakeholders, once they've been identified.

## Design
[Sketch mockups](https://www.sketch.com/s/20ea8818-8846-4f47-b341-7dc0ee6fc57e)

## Artifacts
- [Discharge Upgrade Wizard Flow](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1696352911500/80253b1c7200212cbcbcfb940d2cf4a29fed8417?sender=u71e5a9ded413bfa79dd23932)
- [CAIA intake ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/63977)
- [CAIA text changes simplified](https://dvagov-my.sharepoint.com/:w:/r/personal/frances_cross_va_gov/Documents/Phase%201%20(MVP)%20Discharge%20Wizard%20Content%20Changes.docx?d=w12be8687d871488ea2a6e9881066c6d1&csf=1&web=1&e=lRzh8s)
- [Original CAIA text changes document for reference](https://dvagov.sharepoint.com/:w:/r/sites/SitewidePublicWebsites/_layouts/15/Doc.aspx?sourcedoc=%7BE399B79E-68AE-41E2-82AE-042F5A7DA6F4%7D&file=DischargeUpgradeWizardContent.docx&action=default&mobileredirect=true) 

## ACs

- [ ] Updated with Phase 1 content edits in the document linked above "CAIA text changes simplified - Phase 1 (MVP) Discharge Wizard Content Changes"
- [ ] a11y review
- [ ] PM review

**Comment by jilladams** [comment]
Opportunistic work for PW, and other projects (Income limits) are higher priority. So: we can file the intake ticket, but this is likely very far down SWC objectives list.

**Comment by wesrowe** [comment]
Determined in sync 3/6 not to prioritize this until the broader portfolio analysis is complete.

**Comment by jilladams** [comment]
Blocked on CAIA content review: https://github.com/department-of-veterans-affairs/va.gov-team/issues/63977

**Comment by FranECross** [comment]
Katherine Fung has stated that the changes will be done in two Phases. She's provided content changes, and CAIA feedback has also been received and will be reviewed, which will unblock this ticket.

**Comment by FranECross** [comment]
Ticket is unblocked to make (Phase 1) design changes.

**Comment by jilladams** [comment]
@FranECross from UX refinement: 
* Design won't need a prototype here. Comps are meant to display the design system subtask pattern update, but we won't need to mock up every question / screen.
* Engineers _could_ start the build update with the Phase 1 content. But we wouldn't ship it as partial, so there may or may not be an advantage to having Eng 
* May be ready to revise this ticket to become an engineering implementation ticket (or close this and instead create a FE ticket), for when we get all content back.

**Comment by FranECross** [comment]
Closing this ticket and will create a new FE engineering ticket

**Comment by jilladams** [comment]
@FranECross we may still need to do this work, but later whenever CAIA comes back with feedback on final content / logic flow changes that may be required. It may be nice to reopen / rephrase that this won't block Phase 1?

**Comment by FranECross** [comment]
@jilladams Sure! I can reopen this, and alter it so it's not updating the prototype and is for the actual work, along with a note as you suggest that it doesn't block phase 1. I was told a few weeks ago that a prototype isn't going to be built for the wizard, and that the mockups in Sketch and flow detailed in Mural are what we'll work from. Thank you!

**Comment by FranECross** [comment]
Info from original ticket, which is being repurposed for a Phase 2 ticket. 

Design office hours requested that we review this design with the content team. 
* Start page may need updated from a button to a link
* Copy may need to be adjusted
* Breadcrumbs: currently point to Home rather than the Start screen, which is not preferred by the Design team, so need insight to decide where Breadcrumb should go
* CAIA feedback in ([ticket](https://app.zenhub.com/workspaces/collaboration-cycle-reviews-61d89e9e5f4c120011a0ad37/issues/gh/department-of-veterans-affairs/va.gov-team/71494)): My only feedback is that the white part of the banner with the seal seems to take up a lot of vertical space on desktop,
* Sketch design: https://www.sketch.com/s/20ea8818-8846-4f47-b341-7dc0ee6fc57e
