### ISSUE TITLE
Review previous Editor Research (VAMC, Vet Center) to offer guidance on CMS editor usability research efforts

### ISSUE THREAD

**Issue by davidmpickett** [department-of-veterans-affairs/va.gov-cms#12813]
**Potential Research to Review**
Ultimately Jo can decide which studies and resources are reviewed as a work output of this card 
- [ ] [Vet Centers MVP - usability study](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/cms/research/vet-center) - Oct 2021 
- [ ] [VAMC listening sessions](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/research/VAMC%20listening%20sessions%20Jan%202022/VAMC%20upgrade%20listening%20sessions.pdf) - Jan 2022
- [ ] [VAMC COVID status editor feedback](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/cms/research/2022-5-COVID-status-editor-feedback) - May 2022
- [ ] [VAMC top tasks](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/cms/research/VAMC-top-tasks-spring-2022) - April 2022

### Original Synthesis Questions
Question form Dave C - how do we define a successful editorial experience for each of these products? How do measure editor sentiment at key points in the change management process. Aka before they onboard to Drupal once they are ramped up. How does this connect to Jo's work about editor surveys?

Question from Steve W - can we get links to relevant research (or connect to Platform Research Library )added to Content Model docs in Drupal. How is that made a standard AC for all editor researach in future?

### Acceptance Criteria
- [x] I expect that the output of this card will include a selection of representative studies (and other resources) from the past that will serve as a good baseline reference for creating the VBA editor research plan
- [x] I expect that useful questions, pain points or other items are pulled out from the above studies and resources to highlight as potentially useful for a researcher conducting studies on editor facing features

**Comment by davidmpickett** [comment]
Chatted with @EWashb, @dawnpruitt, and @joagnitti and they agreed that this ticket could be handled by the CMS team as it's foundational to our understanding of editor roles. 

The follow up work of creating a research plan and implementing it would need to be handled by a UXer on the Sitewide contract though.

**Comment by EWashb** [comment]
Thank you for all of this @davidmpickett. We think this is a good first step for our CMS ResearchOps initiative. This directly ties into the need for broad synthesis.

**Comment by EWashb** [comment]
As part of #12833 we will be doing a deeper dive into personas, so we might not have totally updated personas for this ticket. Persona work could be a higher lift than just this ticket. I recommend "persona insights documented" instead as a good compromise. However, we will be able to make suggestions for updating them and also identify the gaps that we have. @joagnitti can give a better idea on the lift of this ask.

**Comment by joagnitti** [comment]
Here is a link to the research review! For now it's a google doc, but I can move this to wherever is most easy to access for everyone: https://docs.google.com/document/d/1Y_K1GSYDm1I97Qe7NYuWz5jghJBkJ6TnnwSXAsGKnyo/edit?usp=sharing
