### ISSUE TITLE
Search type-ahead: Implement Datadog monitor that will detect failures of site search and type-ahead in the future

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#12817]
### User story
> _Describe the audience/user, enhancement or fix, and value / outcome desired._

**AS A** Veteran
**I WANT** site search type-ahead to work
**SO THAT** I'm more likely to find what I'm looking for

### Engineering notes / background

In #12625 we found that unnoticed Sentry errors left type-ahead broken for >6 months. We have not been able to get better Sentry support to make alerts work (which would notify the team of Sentry errors). So we propose adding a test that will be more visible within our testing frameworks.

**Precedent:**
Facilities did this once before. Facility Locator – Datadog runs e2e "synthetic" test against Prod periodically (~4 hrs), records success/fail, and DD post a slack alert to the/a platform support channel. 

Questions for discussion in refinement:
- Could we use Cypress as a CRON on Prod? would have the benefit of re-use of cypress tests
  - possible tradeoff: would we lose some benefits of DD, e.g. searchable log history, connection between errors in different parts of the stack, etc?

## Acceptance criteria

**Estimated at 5pts, assume timebox (~2 days) and come back to team if scope blows up**

- [ ] Search working: Datadog synthetic test monitors searches
- [ ] Type-ahead monitoring: Datadog synthetic test monitors that type-ahead is working
- [ ] Failure notifies PW team in Slack support channel, something like `public-websites-monitoring`

**Comment by jilladams** [comment]
Q out to Platform re: whether / how we could notify a Slack channel or something as part of the failure case: https://dsva.slack.com/archives/CBU0KDSB1/p1678303576907459?thread_ts=1676649281.271409&cid=CBU0KDSB1

**Comment by jilladams** [comment]
From ^ slack thread: 
* Cypress failures will block PR merge for all contributors to vets-website. That's not ideal, since we won't be able to always actively mitigate a search.gov endpoint being down.
* Instead, Platform suggested adding a "synthetic monitor" to Datadog, which Josh is familiar with from similar thing for Facility locator.

To be done: 

- [ ] Identify how a datadog monitor gets actually monitored. Does a human need to see it for it to matter? Can it notify us? 
- [ ] Update ticket body with that new direction / ACs

**Comment by jilladams** [comment]
Related to https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12978, maybe

**Comment by wesrowe** [comment]
from FE refinement 9/20: we will revisit refining this after Chris has gotten more familiar with Datadog.

**Comment by FranECross** [comment]
@chriskim2311 to check if this is redundant.

**Comment by chriskim2311** [comment]
This has been completed. I had the test off but I just restarted it again to run once a day and alert the PW slack if it fails.
https://vagov.ddog-gov.com/synthetics/details/qba-bdz-t78?from_ts=1699560181882&to_ts=1700164981882
