### ISSUE TITLE
Homepage baseline: Summarize Medallia qualitative feedback for 2022

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#12814]
### User story
> _Describe the audience/user, enhancement or fix, and value / outcome desired._

**AS A** PO
**I WANT** to understand the qualitative data Veterans provided about the VAgov homepage during 2022
**SO THAT** I have a baseline for comparison of qualitative feedback about the new homepage.

### Engineering notes / background

[Feedback Excel](https://dvagov-my.sharepoint.com/:x:/r/personal/wesley_rowe_va_gov/Documents/feedback%20data%20with%20possible%20PII/2022%20homepage%20medallia%20analysis.xlsx?d=w706b6f5221e6436690f3c7d0995066c6&csf=1&web=1&e=rrXQsN) is in Wes's sharepoint folder; request access if you don't have it already.

## Acceptance criteria

- [ ] Gather relevant verbatims in a new tab/sheet (omit f/b that is not about the homepage itself)--DECIDED TO NOT DO THIS B/C TOO TIME-CONSUMING TO COPY/PASTE SO MANY VERBATIMS. DID ALL ANALYSIS IN THE DATA SHEET ITSELF
  - [x] Remove PII
- [x] Analyze / tabulate in some structured way, e.g., tag
- [ ] Add excel to [research folder in github product area](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/public-websites/home-page)--DECIDED TO NOT DO B/C OF RISK OF PII
- [x] Add pdf or markdown version of high-level summary to research folder

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [X] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`

**Comment by cindymerrill** [comment]
Got access to the qualitative data from @wesrowe . Sorted it and found that it's 3203 rows of verbatims, which is a LOT. 

When I start going through the verbatims, it’s important that the rows NOT get resorted so I don’t lose track of where I am. Are you going to be working with the data and resorting it, @wesrowe ? If so, then maybe I should be working with a copy of the data, which I know is not your preference.

**Comment by cindymerrill** [comment]
Started looking through the verbatims, but have a lot more to go.

**Comment by cindymerrill** [comment]
Looked at more verbatims today

**Comment by jilladams** [comment]
Because Income Limits is unstuck, this is no longer top priority in the current sprint. Demoting this from sprint goal in Sprint 79, and will goalify an alternate research ticket instead. FYI @wesrowe @davidconlon

**Comment by cindymerrill** [comment]
Read through a LOT of verbatims today and tagged them.

**Comment by cindymerrill** [comment]
Here's my high-level qualitative summary: 
![image](https://user-images.githubusercontent.com/69914583/227646070-60dd2487-0fb3-46c5-b525-7ea9aa850402.png)

Perhaps @jilladams could post it on github in this folder: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/public-websites/home-page

**Comment by cindymerrill** [comment]
We could post the whole data spreadsheet on github, too, but it’s huge and might have some PII (though I aimed to remove it all), so I’d recommend not posting it. Here's a link to it: https://dvagov-my.sharepoint.com/:x:/g/personal/wesley_rowe_va_gov/EVJva3DmIWZDkPPH0JlQZsYBFe-lTET-C2WUfa22b69A2w?email=JILL.ADAMS1%40VA.GOV&e=ZYdjQ3

**Comment by cindymerrill** [comment]
As soon as my screenshot summary is posted on github, I think this ticket can be closed @jilladams @wesrowe

**Comment by cindymerrill** [comment]
Closing ticket because this is all the work I'm going to do on it for now. Happy to discuss it with @wesrowe or anyone else when I get back from PTO on April 3.
