### ISSUE TITLE
Prototype for image upload editorial interface workflow in the CMS

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#12825]
## Description
We would like to create a design prototype for a new image upload workflow that includes the proposed updates to the alt text field using existing design patterns:

- Form validation when a filename is detected within the alt text field
  - This would be blocking - we would not let the form be saved if a file name was found.
  - One error at the top of the screen that summarizes the fields where errors are found.
    - Number of errors noted
    - Links to the field level errors found are noted.
  - Each individual error is clearly indicated by a red outline around the input field along with a description of the error found and what needs to be resolved is explained in red text.

![](https://user-images.githubusercontent.com/113871419/230220171-39aac237-d737-48ef-ba84-2c4a469112e2.png)

- Warning patten for Redundant phrases (i.e. "image of", "photo of", etc.)
  - This is not blocking. The editor can still save the image upload form but we do want to provide them with a message/warning to discourage them from using this type of language
  - Use Existing Warning Pattern
    - Use the following pattern (see screenshot) that appears at the top of edit forms and the top of node view.

![](https://user-images.githubusercontent.com/113871419/230217741-38d2d401-9614-4b30-b2ac-26a43724ab24.png)

- Addition of character count
  - Yellow/red pattern based on character limit of 150 characters
  - The current implementation of this pattern in the CMS can be seen in the “Description” text input on the [“Add Image” page](https://prod.cms.va.gov/media/add/image). We can use this same exact pattern on the alt text input field for images.
    - Yellow text box outline  = Warning. You are 5 characters or less away from the character limit.
    - Red text box outline = You are over the character limit. You can continue to type (aka, there is a “soft limit”), but you will get an error if you try to save and you won't be able to save unless you fix the error.

## Acceptance Criteria
- [x] Design/Prototype is created
- [x] Meeting scheduled to review with Engineering and accessibility

### Team
Please check the team(s) that will do this work.

- [x] `CMS Team`
- [ ] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`

**Comment by laflannery** [comment]
For any character limits we need to be aware of any strict limits because of translations

**Comment by laflannery** [comment]
Clean this up, make epic, add ticket for tech discovery to determine feasibility

Possibly investigate: There is a Soft Limit Length module I believe. I worked on it many years ago. (Elijah)

**Comment by BlakeOrgan** [comment]
The version 1 designs for the additions mentioned in this ticket can be found at this Figma link: https://www.figma.com/file/OXueAhBrPif6wh8vynPxGs/Alt-Text-Errors-and-Warnings?node-id=15%3A1894&t=CQlx6iaHpOXrYyAV-1

**Comment by BlakeOrgan** [comment]
Meeting to review designs with @laflannery, @edmund-dunn, and @joagnitti is scheduled for April 2. AC's only list engineering and accessibility reviews, but I wanted to start to loop Jo in as she will be running research based on these designs.
