### ISSUE TITLE
Discovery: document how many Facility Services do not have Service Locations

### ISSUE THREAD

**Issue by JayDarnell** [department-of-veterans-affairs/va.gov-cms#12830]
Slack thread: https://dsva.slack.com/archives/C02BTJTDFTN/p1677768032765469

It has come to our attention that there are some VAMC Facility Health Service nodes out in the wild that do not contain any Service Location information. One example would be Cardiology at Hunter Holmes McGuire Hospital in Richmond: https://prod.cms.va.gov/node/14778/edit

## Acceptance Criteria

- [ ] Identify every VAMC Facility Health Service node where the Service Location field has no entries
- [ ] Should likely be accomplished via a script that could be later extended to actually fix the identified items

**Comment by kmariepat-cityfriends** [comment]
this work is being completed on 12831
