### ISSUE TITLE
Bug: Events can be created with invalid start/end dates.

### ISSUE THREAD

**Issue by dsasser** [department-of-veterans-affairs/va.gov-cms#12832]
## Description
It is possible to create an Event with an end date earlier than the start date. This should not be possible.

### User story
**AS A(N)** Content Admin
**I WANT** Ensure Event dates are validated correctly in respect to start and end dates
**SO THAT** I am unable to create an Event with a date that doesn't make sense

### Engineering notes / background
It is possible, in our VA.gov configuration, to create an event which has an _end_ date which is _earlier_ than the _start_ date. I confirmed that by disabling our custom `va_gov_events` module, this behavior is rectified--pointing to some of our custom code which is interfering with the form validation. In our EntityEventSubscriber we are doing the following:

```
    // Set defaults to prevent validation errors.
    $form['field_datetime_range_timezone']['widget'][0]['value']['#value']['object'] = '';
    $form['field_datetime_range_timezone']['widget'][0]['end_value']['#value']['object'] = '';
```

This may be a red herring, but at first glance it appears to be intentional for some reason yet unknown.
It's weird that validation suppression is in there. Removing it is probably risky for reasons we don't know. So: we'll need to be mindful of that in testing.

Origin of those lines of code, as far as we can tell, are: 
* commit [#774728a](https://github.com/department-of-veterans-affairs/va.gov-cms/pull/7981/commits/774728a30299f710ffc767972d20d62ea00dc4a6#diff-e3ce07474d1419339788d36cafcf913d4327eee7e4ebd86e1e07554e1f47ce33R105) 
* PR [#7713](https://github.com/department-of-veterans-affairs/va.gov-cms/pull/7713) 
* Issue #6057
* Issue #7803 

## Acceptance criteria

- [ ] Determined reason for custom code that prevents validation
- [ ] User cannot set an end date that comes before the selected start date
- [ ] User can create and successfully save all flavors of events
  - [ ] Recurring
  - [ ] Single

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [X] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`

**Comment by wesrowe** [comment]
Iceboxing since we don't have evidence that Editors encounter this defect in the wild.

**Comment by FranECross** [comment]
Closing previously iceboxed issue. No evidence this is causing issues with editors.
