### ISSUE TITLE
Optimize accordion header-level plugin for content-build time

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#12863]
### User story

**AS A** PO or Editor
**I WANT** the plugin to have less impact on build time
**SO THAT** Editors are less impacted by slow builds

### Engineering notes / background

@ryguyk proposed optimization(s) to the plugin in a [slack thread](https://dsva.slack.com/archives/C52CL1PKQ/p1678121450511429). We determined that the decision to pursue optimization should be driven in part by how much time it adds to content-build in production.

** Proposed optimizations **
from: https://github.com/department-of-veterans-affairs/content-build/pull/1487
1. 
<img width="800" alt="image" src="https://user-images.githubusercontent.com/61624970/224070516-432c6b7e-f829-41cc-95a8-1818db38abe1.png">
2. 
<img width="800" alt="image" src="https://user-images.githubusercontent.com/61624970/224070602-1d1cb798-9f43-4595-9580-6796b01829ee.png">
3. 
<img width="802" alt="image" src="https://user-images.githubusercontent.com/61624970/224070699-60c80726-a0c1-4501-90fe-46ce10f0946d.png">

### Analytics considerations

Use DataDog from Prod as reference - ***Josh to add Prod data of plugin's impact to content build timing***
DataDog dashboard referenced: 
https://app.ddog-gov.com/sb/f327ad72-c02a-11ec-a50a-da7ad0900007-b0be82e93e3a72857990965ab100570b

Josh's analysis:
`we were somewhere around 22.3 minutes before, jumped up to around 28 minutes for a few days around release, and now we’re seeing an average around 24`
That's a 7-8% increase, in line with our expectations from testing in a local environment.

<img width="618" alt="image" src="https://user-images.githubusercontent.com/4054752/225081120-5ef7da80-e549-48ed-b60e-aa4ee2a06cc4.png">

## Acceptance criteria

- [ ] Determined optimization(s) to attempt
- [ ] Implemented optimization(s)
- [ ] Benchmarked new build time locally to gauge impact
- [ ] Ensured that the plugin's functionality is not impacted adversely
- [ ] Monitored performance in prod to ensure performance is improved and not slowed

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [X] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`

**Comment by wesrowe** [comment]
@jilladams, we overlooked this one in FE refinement because I forgot to put the label on it. 

@jtmst, can you check Datadog for build-time impact before refinement tomorrow? And please add to ticket details above so we'll see it for refinement.

**Comment by wesrowe** [comment]
Or actually, to clarify, DaveC asked that inputs like that be clear in the ticket rather than spread across slack threads, etc. Also, it may be best to summarize the proposed optimization above also, for the sake of pulling things together in one place.

**Comment by wesrowe** [comment]
If it negatively impacts prod, we can wait till next day's deploy to roll back (if necessary).

**Comment by jilladams** [comment]
Launched the header plugin. 
Prod data = Tim Cosgrove noted that other work in Content Build may be muddying the data, so we don't have a clear read yet on the actual impact of our work vs. other devops work. 

We plan to punt til the end of Sprint 80 to get better data to confirm whether this is worth pursuing in the near-term.

**Comment by jilladams** [comment]
Based on newest data, the plugin had a more minor impact that we originally thought, ~2 mins on build time. Iceboxing.

**Comment by FranECross** [comment]
Closing as a no op.
