### ISSUE TITLE
Create Knowledge Base article for admins to edit COVID status term descriptions

### ISSUE THREAD

**Issue by omahane** [department-of-veterans-affairs/va.gov-cms#12875]
## Description
As an admin, I may need to change the default language associated with the various COVID statuses so that we can provide the most relevant, useful guidance for editors to have as default language when setting or changing a COVID status for a VAMC facility.

## Process
1. Review request and confirm no current, applicable KB article/content exists.
2. Assign to appropriate product team (if the request did not already come from the product team)
3. Draft article content
4. CMS team will review for formatting and writing style guidelines
5. Helpdesk team will review for functionality and editorial tone
6. Publish
7. If the KB is for a specific content type, go to the [Content model document](https://prod.cms.va.gov/admin/structure/cm_document) for that content type and add link to the new KB article

## Acceptance Criteria
- [x] Article is created using [KB content style guidelines](https://va-gov.atlassian.net/wiki/spaces/VAGOV/pages/1771831299/Knowledge+Base+content+style)
- [x] An article has been created for admin users in the Sitewide Content team
- [x] The article describes the steps necessary to update the COVID status term descriptions
- [x] The article has been reviewed and approved by the Sitewide CMS team
- [x] The article has been reviewed ad approved by the Help Desk
- [x] Article published to KB
- [x] Impacts on other KB articles have been considered and any necessary changes have been made
- [x] If necessary, add link to the new KB article in the [Content model document](https://prod.cms.va.gov/admin/structure/cm_document) for that content type 
- [x] Once published, the person requesting the article has been notified

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [ ] `Public Websites`
- [x] `Facilities`
- [ ] `User support`

**Comment by omahane** [comment]
I created this article here:
https://prod.cms.va.gov/help/vamc/editing-facility-supplemental-status-covid-19-term-descriptions

**Comment by laflannery** [comment]
@omahane reviewed and updated! The only thing I added that I'm not 100% sure about (so if it's incorrect you can just deleted before publishing) is this generic line I put into the "Before you start" heading:

> Taxonomy terms are only manageable by editors with the Content Editor role.

I wasn't sure if all taxonomies were for the content editor role so if this general statement was ok to make or not?

![image](https://user-images.githubusercontent.com/106678594/229219754-a8e40fb6-4995-408a-980e-f4edd06ba1ed.png)

**Comment by omahane** [comment]
I just tested this on staging, and found that it is "Content admin," not "Content editor" that has access to edit taxonomy terms.
![Screen Shot 2023-04-03 at 2 19 00 PM](https://user-images.githubusercontent.com/766573/229606550-75008e99-9b16-49b3-ac6f-86f1d820c191.png)
![Screen Shot 2023-04-03 at 2 19 55 PM](https://user-images.githubusercontent.com/766573/229606567-dbbb32f3-4a24-4cdf-8bfe-bea17cdf0c6f.png)

**Comment by omahane** [comment]
@stefaniefgray @TroyA6 Could you look at this? https://prod.cms.va.gov/help/vamc/editing-facility-supplemental-status-covid-19-term-descriptions

**Comment by laflannery** [comment]
@omahane Yes this makes much more sense and it's very possible I accidently just wrote the wrong thing.

My recommendation would be to change what I wrote to say:
"Taxonomy terms are only manageable by editors with the Content Admin role."

And then we just circle back to this when the updates @davidmpickett mentioned come up.

**Comment by TroyA6** [comment]
@omahane @stefaniefgray @laflannery - FWIW: I found that the role 'Administrator' does not allow editing - it is specifically tied to Content Admin role - The steps seem to be accurate and functional - so it looks good to me!

**Comment by stefaniefgray** [comment]
Looks good on my end -- only thing I'd like to note is that editors sometimes get confused when finding articles intended for Content Admins, and end up writing to us anyhow about "Why can't I do this thing from the article?"

The Content Admin role is extremely limited, and only belongs to a handful of users. Perhaps this could be an internal article that isn't published live?

**Comment by omahane** [comment]
@kmariepat-cityfriends I'm not sure what to do with Stefanie's question. Do you have any advice?

**Comment by jilladams** [comment]
From Fac scrum: 
* KBs should be Published. Shouldn't use Publishing to manage visibility per role.
* Open ticket has been made for Taxonomy updates
  * When that's done, could move this KB into a product guide. 
* KB already includes language: "Before you start. Taxonomy terms are only manageable by editors with the Content Admin role. If you are not assigned to that role, you will not have access to edit these Facility Supplemental Status descriptions." Kamari will provide an edit we can update here to solve for this.

**Comment by jilladams** [comment]
Noting: this ticket isn't following the new 2 ticket approach, so won't result in a follow up review ticket.

**Comment by omahane** [comment]
@kmariepat-cityfriends I slightly edited your language and added a screenshot to show the toolbar for Content Admins, as there's no other indication of which roles have been assigned to you.
https://prod.cms.va.gov/help/vamc/editing-facility-supplemental-status-covid-19-term-descriptions

**Comment by TroyA6** [comment]
@omahane @kmariepat-cityfriends @stefaniefgray - explaining Content Admin is a great addition -- Passes my review!
