### ISSUE TITLE
Name that CMS! (part 1)

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#1287]
## Description

Is it Drupal? Is it VA.gov CMS? Is it VACMS?  All of the above? What are the rules by which we use these names/brands in different places? 

## Artifacts
* [MURAL](https://app.mural.co/t/vagov6717/m/vagov6717/1589235929175/97ed9978b0165a98942150bf667b133e4faad3f1) 

# Sprint 6 Summary
- [x] Held 2 "word huddles" to get oriented in the problem space
- [x] Async brainstorming with the CMS team with a list of possibilities
- [x] Sorted and ranked possibilities based on current assumptions
- [x] Identified areas of alignment/misalignment on direction

## Next Sprint steps
- [ ] Identify stakeholders for a smaller working group
- [ ] Orient to mission statement direction
- [ ] Revisit product name problems with mission statement context in mind

## Later on 
- [ ] Figure out the stakeholders for final signoff (Chris Johnson? etc)
- [ ] Complete audit of all the places where the product's name is used.

**Comment by kevwalsh** [comment]
![VA_gov_Design_System](https://user-images.githubusercontent.com/643678/77233842-a9fae700-6b80-11ea-89a8-3f34410224f4.jpg)

Here's what VACMS might look like on a CMS homepage, with a design stolen shamelessly from design.va.gov 😆

**Comment by ElijahLynn** [comment]
> VA.gov CMS

I have always thought this makes the most sense. But that is such engineer-brain thinking I am afraid.
