### ISSUE TITLE
Winnower does not work in Safari

### ISSUE THREAD

**Issue by omahane** [department-of-veterans-affairs/va.gov-cms#12884]
## Describe the defect
When editing in the CMS on Safari, the winnower applies the appropriate classes (per the JavaScript), but Safari does not respect class-driven CSS in `<select>` elements, resulting in nothing being winnowed.

## To Reproduce

1. Using Safari on a Mac, [create a VAMC facility health service](https://prod.cms.va.gov/node/add/health_care_local_health_service)
2. Choose "---VA Bedford health care" in the Section dropdown
3. Click the "Health service and facility basic info" to expand the field group
4. Click the "Facility" dropdown
5. Notice that the first option is "A.K. Baker VA Clinic | VA North Florida/South Georgia health care" and the last is "Zephyrhills VA Clinic | VA Tampa health care", meaning that nothing was winnowed.
6. Right-click on the dropdown and choose "Inspect Element"
7. Expand the `<select>` element.
8. Notice that `<option value="6792" class="hidden-option">A.K. Baker VA Clinic | VA North Florida/South Georgia health care</option>` contains the correct class (`hidden-option`)
9. Repeat (for confirmation) with the "VAMC system health service" to confirm that despite having the right class to hide the options, all the options are showing

## AC / Expected behavior
All facilities and VAMC health services not in the Section should be hidden (as they are in Chrome and Firefox)

## Screenshots
<img width="1574" alt="Screen Shot 2023-03-08 at 11 22 36 AM" src="https://user-images.githubusercontent.com/766573/223785320-718c2585-4a64-4039-b2b1-0272bb3c9555.png">

 ## Additional context
https://www.sitepoint.com/community/t/css-select-class-doesnt-work-in-safari/2908/12

### Implementation suggestion
We would need a persistent source for all the options in any winnowed field from which we could draw and to create a subset of the options to populate the "Facility" and "VAMC system health services fields" whenever the "Section" is selected (whether once or more than one times).

## Desktop (please complete the following information if relevant, or delete)
 - OS: MacOS
 - Browser: Safari
 - Version: All

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Defect")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS workstream (orange) (not needed for bug tickets)
- [ ] CMS-supported product (black)

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [ ] `Public Websites`
- [x] `Facilities`
- [ ] `User support`

**Comment by ryguyk** [comment]
[Related issue](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12879) that might be solved by same solution.

**Comment by jilladams** [comment]
From refinement: 
* Data: confirm the scope of Safari CMS users

**Comment by omahane** [comment]
Someone found a solution to this: https://codepen.io/martinkrulltott/pen/zrKvRj

@mmiddaugh Is there a way to find out how many editors are using Safari? That will help determine the priority of this issue.

**Comment by jilladams** [comment]
From sprint planning discussion: We believe the CMS does collect analytics we could review, but Michelle isn't familiar with them. Erika / Marcia may know. Next step is a product convo. cc @xiongjaneg

**Comment by jilladams** [comment]
FYI @xiongjaneg . Seems reasonable to me, and closing, but feel free to reopen if we need to discuss further.
