### ISSUE TITLE
Homepage: Confirm that full-width and promo banners are available on new homepage

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#12889]
### User story

**AS A** Veteran
**I WANT** to see the promo and full-width banners in the new homepage
**SO THAT** VA can communicate to me when necessary

### Engineering notes / background

We think these banners come with the header in `header.html`.

## Acceptance criteria

- [ ] Confirmed in a local build of CMS and FE that adding the path `/new-home-page` to both banner types works:
  - [ ] full-width banner for general facility updates (on regular homepage) – [node](https://prod.cms.va.gov/banner/va-facility-and-status-updates)
  - [ ] promo banner for PACT Act (on regular homepage) – [node](https://prod.cms.va.gov/node/48052/edit)

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [X] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`

**Comment by dsasser** [comment]
I confirmed, via local and Tugboat environments, that by modifying the paths of CMS banners, they will appear on the new home page:

![Screenshot 2023-03-13 at 3 10 19 PM](https://user-images.githubusercontent.com/221539/224843534-a10a6f05-5938-4da6-bea4-ed2c648e68e2.png)

**Comment by ElijahLynn** [comment]
I'm deleting this Tugboat environment: 
![image](https://user-images.githubusercontent.com/1504756/228417827-070ff4f3-4f53-4ab6-9272-009e50bc0e53.png)
