### ISSUE TITLE
Need SSM access to prod

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#12888]
## Description
In order to complete #12870, we must have SSM access to prod, which must be requested from and granted by Platform.

### Resources

- [Platform page on AWS developer access](https://depo-platform-documentation.scrollhelp.site/getting-started/request-access-to-tools#Requestaccesstotools-AWSconsoleaccess)
- [GitHub template for AWS request ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=external-request%2Coperations%2Cops-access-request&template=aws-access-request.yml&title=AWS+access+for+%5Bindividual%5D)

## Acceptance Criteria
- [x] SSM access has been requested
- [ ] SSM access has been granted

### Team
Please check the team(s) that will do this work.

- [x] `CMS Team`
- [ ] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`

**Comment by laflannery** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/issues/54856

**Comment by laflannery** [comment]
@edmund-dunn I saw the related request ticket (above) was closed - should we close this one now too?

**Comment by productmike** [comment]
closing as dependent ticket has been closed
