### ISSUE TITLE
RUNBOOK: VAMC facility renaming 

### ISSUE THREAD

**Issue by kmariepat-cityfriends** [department-of-veterans-affairs/va.gov-cms#12899]
## Description
As apart of our committed Q1 Priorities, we will be updating or creating runbooks
For this runbook, we need to include all of the things we need to do when a VAMC facility is renamed

One thing to note is that this is NOT of a health care system, the VAMC facility referenced here is distinct from that 

## Acceptance Criteria
- [ ] I expect an initial draft of runbook steps is created  to perform the process in the description is created 
- [ ] I expect this initial draft is reviewed with helpdesk to refine the steps to ensure they sense to all parties involved and take into account steps needed to clearly communicate these things with editors
- [ ] I expect a finalized and approved runbook is created and housed where runbooks are housed 

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by JayDarnell** [comment]
This runbook was updated last sprint. I added some text to specify that the newly saved node should be published. @stefaniefgray @TroyA6 please review the runbook and let me know if there are any edits needed to make things clearer.

**Comment by kmariepat-cityfriends** [comment]
@stefaniefgray @TroyA6 pinging you on here to let you know this card is ready for review. Review should be complete by COB tuesday ideally, let me know if you need anything to support your review.

**Comment by stefaniefgray** [comment]
@jilladams Looks good, can be closed
