### ISSUE TITLE
RUNBOOK: Community access point BECOMES an outstation 

### ISSUE THREAD

**Issue by kmariepat-cityfriends** [department-of-veterans-affairs/va.gov-cms#12897]
## Description
As apart of our committed Q1 Priorities, we will be updating or creating runbooks that 
For this runbook, we do know that when a community access point becomes an outstation, it gets an entry into VAST

Life of a Vet Center: 
~Mobile →~ Community access point → outstation (gets an entry into VAST) → becomes a VET Center (gets a new ID from VAST)

## Acceptance Criteria
- [x] I expect an initial draft of runbook steps is created  to perform the process in the title/description  
- [x] I expect this initial draft is reviewed with helpdesk to refine the steps to ensure they make sense to all parties involved and take into account steps needed to clearly communicate these things with editors
- [x] I expect a finalized and approved runbook is created as a github issue template 

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by swirtSJW** [comment]
@kmariepat-cityfriends This has been merged and the runbook now exists in our repo.  Passing it on for your review.
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/new?assignees=&labels=Change+request%2C+Vet+Center&template=runbook-vet-center-cap-to-outstation.md&title=Vet+Center+CAP+becomes+an+Outstation%3A+%3Cinsert_name_of_facility%3E
