### ISSUE TITLE
RUNBOOK: outstation BECOMES a VET Center 

### ISSUE THREAD

**Issue by kmariepat-cityfriends** [department-of-veterans-affairs/va.gov-cms#12898]
## Description
This is sized as a 3, assuming this card has been completed first: https://app.zenhub.com/workspaces/sitewide-facilities-639f5253e4b702a32376339e/issues/gh/department-of-veterans-affairs/va.gov-cms/12897
As apart of our committed Q1 Priorities, we will be updating or creating runbooks that 
For this runbook, we do know that when an outstation point becomes a VET CENTER, it gets a new ID in VAST

Life of a Vet Center: 
Mobile → Community access point → outstation (gets an entry into VAST) → becomes a VET Center (gets a new ID in VAST)

## Acceptance Criteria
- [ ] I expect an initial draft of runbook steps is created  to perform the process in the description is created 
- [ ] I expect this initial draft is reviewed with helpdesk to refine the steps to ensure they sense to all parties involved and take into account steps needed to clearly communicate these things with editors
- [ ] I expect a finalized and approved runbook is created and housed where runbooks are housed 

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by stefaniefgray** [comment]
**List of existing runbooks:** https://github.com/department-of-veterans-affairs/va.gov-cms/tree/main/.github/ISSUE_TEMPLATE
