### ISSUE TITLE
Facility Locator uses Lighthouse API v1 with existing functionality (Phase 2)

### ISSUE THREAD

**Issue by kmariepat-cityfriends** [department-of-veterans-affairs/va.gov-cms#12907]
## Description
Lighthouse Facilities V1 shipped August 24, 2023. This long-awaited update made CMS the source of truth for nearly all VA health services throughout the ecosystem. This is Phase 2 of 3 parts to implement V1. The work covered by this epic will convert the Facility Locator to use Facility API v1 with existing functionality. ([#12907](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12907))

- In Phase 1, we updated Vets-API to point to Lighthouse v1 (Phase 1) [#15344](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15344). This unblocks teams dependent on this functionality. 
- Phase 3 will implement Lighthouse v1 to power the Facility Locator, making it possible to search using the full list of (VA health) services available in CMS [#14993](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14993)

Currently, Veterans can search for 19 VA health services in the Facility Locator. Today, those searches are powered by a legacy data source which affiliates services and facilities. This data source has not been entirely accurate for some time and is no longer maintained given the launch of Lighthouse Facilities V1 in August 2023.  

Lighthouse V1 (c/o CMS) contains data for over 90 service types. We are not able to make searching for all of these possible given the current UX which presents a dropdown list of services. However, we can point to CMS as the source of truth for the service selected from the existing service dropdown. This will reduce the discrepancies between the facility/service data we return in search results and the data which is available in CMS (and displayed on VAMC pages). 

There is relevant history and bigger picture context in #11542. 

## Tasks
- Need to determine the source of the dropdown Service type list for VA health Facility type searches and if anything needs to change during this phase
- TBD

## Expected behavior
- [ ] The existing UX does not change. The data sourced for the existing search functionality is provided by CMS via Lighthouse V1 (`facilities-api` V2)
- [ ] Tests are passing

**Comment by xiongjaneg** [comment]
closing, no tickets associated and plenty of epics to use

**Comment by jilladams** [comment]
@jilladams review epic to confirm if the FE work is scoped to adopt

**Comment by jilladams** [comment]
In theory: when the Facilities API in vets-api has been updated from V1 to V2, theoretically we should be able to update the endpoints that the Facility Locator is calling to point from V1 to V2 endpoints, and everything still works. 

In vets-api: `facilities-api` has 2 endpoints: 
1. `va` - sends calls to Lighthouse. This one will be changed by the LH V1 work.
2. `ccp` - sends calls to PPMS. won't be affected, as we use different PPMS endpoints that aren't modified by LH.

The number of available services won't change until Phase 3, when we adopt the expanded functionality available in LH V1.

**Comment by mmiddaugh** [comment]
@oddballpete @jilladams you'll want to check on the source of the service list dropdown when Facility type = VA health or VA benefits (example in screenshot below). I think both are hardcoded - I don't think we get either from Lighthouse. 

If hiding them becomes necessary, here's data to support that as a interim solution. Year to date, 
- 85% of the nearly 1 million unique searches for VA health did not specify a Service type
- 87% of the nearly 216K unique searches for VA benefits did not specify a Service type

After the change, Lighthouse v2 should be the source for the following searches
- Facility type = VA health
- Facility type = VA benefits
- Facility type = VA cemeteries
- Facility type = Vet Centers
- Facility type = Urgent care + Service type = VA urgent care (and the VA results included in the All in-network urgent care mashup)
- Facility type = Emergency care + Service type = VA emergency care (and the VA results included in the All in-network emergency care mashup)

Search functionality for community care providers should be maintained 


<details>
<summary> Facility Locator screenshots </summary>

![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/55411834/20ddefc2-c05b-45d5-b8b8-303b81d0b1c4)
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/55411834/105df600-562c-4f07-adbd-6bcb6331f1a9)
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/55411834/f3820106-bc7c-4cc9-82c8-951c23e094ce)
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/55411834/3cac19de-7126-49ce-86fb-d15dfdf66c8c)
</details>

**Comment by khenson-oddball** [comment]
@mmiddaugh Thanks for this info! Could I ask a clarifying question about the "Search functionality for community care providers should be maintained" portion? I'm wondering what specifically is meant by the that portion of the comment since it is separated out from the "Lighthouse v2" portion?

I'm thinking this is speaking specifically to searches that have Facility type = "Community providers (in VA’s network)" OR "Community pharmacies (in VA’s network)". Is that correct?

Also, does the comment mean that community care providers search should continue to use Lighthouse v1 (vets-api) and therefore Lighthouse API [v0](https://developer.va.gov/explore/api/va-facilities/docs?version=v0) (instead of v1)?

Cc: @oddballpete

**Comment by jilladams** [comment]
Great questions. You're right re: Community Care providers & pharmacies -- there's a diagram here that explains data origins / Lighthouse vs. PPMS community care data: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/facilities/facility-locator/engineering#technical-diagrams

@eselkin & @maxx1128 tagging you in for technical expertise re: Kyle's question in the comment above re: PPMS data in the facilities-api V2 version, once we have LH V1 integrated. When we scoped out V1 Lighthouse updates, we didn't really talk about the fact that the PPMS data sits on facilities-api V1 in vets-api and whether or not that will need to increment in some way.  I'm curious if either of you or Kyle see any issues around keeping that data / endpoint at V1?

**Comment by khenson-oddball** [comment]
@mmiddaugh @eselkin Thank you for this extra info! After discussing with @oddballpete, we believe that we can get the ccp/ppms functionality moved over from v1 facilities_api (vets-api) to v2. We are planning on working on this after completing the facilities_api (vets-api) Lighthouse v1 to v2 backend change and before starting Phase 2 (frontend change to integrate with v2 of facilities_api). Please let us know if you have any concerns or see any potential issues with this plan.

Also, there's a `mobile_covid` service I have noticed in facilities_api (vets-api). Is that something we need to consider? The only place I find it being used is in the va_controller (`/facilities_api/v1/va` endpoint) and it is behind a feature toggle named "facilities_locator_mobile_covid_online_scheduling" and also requires specific "mobile" params be passed from the frontend.

**Comment by eselkin** [comment]
I've never touched the mobile COVID stuff. I'll look.

**Comment by jilladams** [comment]
@khenson-oddball In general your plan makes great sense - thank you!

For the mobile covid bit, are you all able to trace git blame and see who added that? Could be that it was the facilities team who held the contract before us in 2021, but I'm not finding related tickets. If there's still code in the wild that calls the endpoint, we'll need to preserve it OR remove the code that calls it (worst case: someone turns that flipper on and we have problems, if not?). Also: ^ Eli added some notes after posting his original comment that may not have come through in email.

**Comment by khenson-oddball** [comment]
@eselkin I didn't find that flipper toggle listed either. I believe you are right about the prod endpoint. I don't believe that is Lighthouse, but I can't be certain about that.

@jilladams thanks for the heads up on Eli's comment! It looks like the Lance Sanchez added the mobile covid change back in May of 2021 with these two [PRs](https://github.com/department-of-veterans-affairs/vets-api/pulls?q=is%3Apr+is%3Aclosed+21734). 

Happy to preserve the mobile covid code if needed, but was hoping to remove it if it is not being used. I'm guessing with it being behind a flipper toggle since 2021 and no mention of the toggle in flipper, it's not being used. 😆

**Comment by jilladams** [comment]
Closing this. IIR team is handling this migration: 
https://github.com/department-of-veterans-affairs/va-iir/issues/618

As part of epic: https://github.com/department-of-veterans-affairs/va-iir/issues/617

 #18014 will track our QA
