### ISSUE TITLE
Add heading for Facility map on Facility Locator

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#12905]
## Description
Screen readers users have the ability to navigate a page by headings - they can hear a list of all headings on a page and choose to jump to any of these headings. By adding a heading for the map specifically users would be able to navigate directly and easily to this section of the page. This heading need not have to be a visual addition to the page - the class `sr-only` can be used to hide this visually but still have it accessible to screen readers

Happens with "Find a VA location"

Since this is not used by visual users, there is no need for the visual addition for ease of use for visual users.

## Acceptance Criteria

- [ ] Add visually hidden H2 heading ("Map of Results") for the map section of the page
- [ ] The class `sr-only` is used to hide the heading
- [ ] Accessibility lead review

**Comment by laflannery** [comment]
@thejordanwood

**Comment by eselkin** [comment]
I guess the question didn't get answered:
The map on https://va.gov/find-locations
or the FacilityMap on an individual facility page?

The map on find-locations has a p-tag with an sr-only that says 
`<p className="sr-only" id="map-instructions" aria-live="assertive" />`

Should we change this tag to a <h2> and the contents to `Map Results`?

**Comment by laflannery** [comment]
@eselkin Apologies, we changed the title of the ticket to say "Facility Locator" thinking that would clarify but not when teams change! I'll make sure to be more clear in future! 

Regarding where to put the heading, I would like it right here:
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/106678594/b2f8df98-d1c7-479d-ad5c-1094534a214b)

Right above the screen reader map info that's already there. This will introduce the Map section to screen reader users so we want to make sure that it's before everything that's there already.

**Comment by mmiddaugh** [comment]
@laflannery can you give this a defect level to assist with prioritization, please?

**Comment by laflannery** [comment]
Verified on prod!
![image](https://github.com/user-attachments/assets/539a1c83-5367-4ff4-af1f-4ccda17c9366)
