### ISSUE TITLE
Increase Test Coverage for Lovell 

### ISSUE THREAD

**Issue by kmariepat-cityfriends** [department-of-veterans-affairs/va.gov-cms#12904]
#### Background 
The functions in update-page.js are written to take in an object generated from that file's getLovellPageVariables function. That function can be imported into the test file and used with some fake page variable test data. That same page test data should be used for testing the functions in helpers.js without the getLovellPageVariables function.

#### Acceptance Criteria 

- [ ] I expect unit tests are added for the functions in src/site/stages/build/drupal/lovell/helpers.js and src/site/stages/build/drupal/lovell/update-page.js
- [ ] I expect the unit tests confirm these two criteria
- [ ] When the right arguments are passed in, it confirms the correct output is given (2 + 2 === 4)
- [ ] When the right arguments are passed in, it confirms the incorrect output is not given (2 + 2 !== 5)

**Comment by maxx1128** [comment]
This increased test coverage should include adding unit tests for the functions in `src/site/stages/build/drupal/lovell/helpers.js` and `src/site/stages/build/drupal/lovell/update-page.js`. These are pure functions so they should be relatively easy to write unit tests for.

The functions in `update-page.js` are written to take in an object generated from that file's `getLovellPageVariables` function. That function can be imported into the test file and used with some fake `page` variable test data. That same `page` test data should be used for testing the functions in `helpers.js` without the `getLovellPageVariables` function.

The unit tests should confirm these two criteria:
1. When the right arguments are passed in, it confirms the correct output is given (2 + 2 === 4)
2. When the right arguments are passed in, it confirms the incorrect output is not given (2 + 2 !== 5)
