### ISSUE TITLE
Initiative - VAMC Hardening 

### ISSUE THREAD

**Issue by kmariepat-cityfriends** [department-of-veterans-affairs/va.gov-cms#12920]
#### Background 
This is an ongoing activity that facilities will iterate on 

#### Goal 
How can we level up the VAMC product to be more effective through an improved editorial interface, new content types, structured content... in order to provide deliver consistent, accessible, quality information to Veterans across the digital ecosystem

**Comment by kmariepat-cityfriends** [comment]
Initial list to explore:
Make an appointment
Pharmacy
DAV Vans
VAMC Facility Map
Contact us
Required health services

**Comment by kmariepat-cityfriends** [comment]
Have a conversation with VHA digital media to determine which order of priorities, true up with that team

**Comment by jilladams** [comment]
@kmariepat-cityfriends Consolidating content from this epic into https://github.com/department-of-veterans-affairs/va.gov-cms/issues/2721. That epic contains subepics already for: 

Make an appointment - #3048 
Pharmacy - #3051 
VAMC Facility Map - #3049 
Contact us - #3045 
Required health services - #9773  (Note: this epic is framed up as a Vet Center specific epic, but the content may apply to VAMCs as well.



The only epic I found re: DAV Vans was narrative written up by @mmiddaugh , no issues written up for it, but closed as done - https://github.com/department-of-veterans-affairs/va.gov-team/issues/7797. Might be worth looking at / reopening / moving over, if the content still pertains to what we wanna do here.

**Comment by jilladams** [comment]
Tickets and notes moved. Closing.
