### ISSUE TITLE
Use `memcached` PHP client library on BRD, not `memcache`.

### ISSUE THREAD

**Issue by ElijahLynn** [department-of-veterans-affairs/va.gov-cms#12935]
Our Elasticache Memcached config doesn't match Tugboat and DDEV. It should be as close as possible. Related https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12934.

**Comment by ElijahLynn** [comment]
We may want to tackle this to our "one container" approach when moving to Lagoon.

**Comment by ndouglas** [comment]
Closed in department-of-veterans-affairs/devops#12903.
