### ISSUE TITLE
Write script for creating event data and implement unit tests

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#12932]
## User story
As an engineer (or PO)
I want unit tests focused on event timing and filtering to run against a source of event data on CI build
so that I can work more quickly in the event product and be confident I didn't create a regression.

## Problems / cases to consider
* It's hard (time consuming, finicky) to generate mock data for events in test environments in order to do functional testing. Maybe: we could cook up a script that can generate events in an env.
* Events have many flavors:
  * Recurring - all future
  * Recurring - some past, some future
  * Single events
  * Events happening now
  * Various locations: 
    * At a facility
    * Online
    * At a not-facility location
* Filters 
  * Past
  * Upcoming
  * Specific dates
  * Date range
* Unit tests - we don't have unit tests for all the helper functions in vets-website. You have to be able to specify your expected outcome, so need to dynamically handle dates. (e.g. don't always expect Nov 7, 2022, but expect tomorrow, etc) 

## Implementation notes

Create a script that generates a data structure with all the test cases we select.

### Risks:
- Code may need refactoring to make testing possible

## Test cases

_Picked from among the events above_
- Recurring - some past, some future
- Happening right now
- Single event - some past, some future
- Filters and associated helper functions:
  * Past
  * Upcoming
  * Specific dates
  * Date range

## Acceptance criteria

- [ ] Script generates a data structure for unit tests
- [ ] Delivered a reasonable amount of coverage as possible without significant refactor

**Comment by dsasser** [comment]
# Status Update 6/16/2023

Event generation script has been created and is up for PR review [here](https://github.com/department-of-veterans-affairs/vets-website/pull/24590).
