### ISSUE TITLE
Injected header: mobile view: Search icon displays half width

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#12948]
## description
https://dsva.slack.com/archives/C52CL1PKQ/p1678737935535419

On mobile breakpoint, injected header search form > search button displays half width, e.g. https://www.va.gov/health/

### Chrome on Android and Mac
<img width="469" alt="image (1)" src="https://user-images.githubusercontent.com/85581471/224850327-a0252ebc-1a11-4eec-b906-d64a3d5144ce.png">

### Mac desktop mobile break
![Screenshot 2023-03-13 at 3 51 38 PM](https://user-images.githubusercontent.com/85581471/224850518-1a41dadf-4b67-4244-8e40-11e1c38f0038.png)

## Acceptance criteria

- [ ] Search form in mobile header on injected header sites appears similar to non-injected header sites

**Comment by wesrowe** [comment]
I just realized this is probably a design system issue. I'll let the DST know and see if they agree.

**Comment by jilladams** [comment]
We should ask Conlon if this is a priority, if our team needs to own it. 

When we onboard new sites to the injected header, we hand them the JS and say: test to make sure your site CSS is not making anything look wild, and if so, it's yours to fix. So in that spirit: it seems this may sit with the downstream injected header site teams to fix?

**Comment by wesrowe** [comment]
I agree that if it's just one injection site that's broken then it's their problem to fix. Is that the case?

**Comment by wesrowe** [comment]
Confirmed that this is the problem of the owner(s) of specific Teamsites site(s) that use the injected header.
