### ISSUE TITLE
Lovell TRICARE Leadership page is empty

### ISSUE THREAD

**Issue by ryguyk** [department-of-veterans-affairs/va.gov-cms#12946]
## Describe the defect
The Lovell TRICARE Leadership list is not being populated. There are [no staff members added to the list](https://prod.cms.va.gov/lovell-federal-health-care-tricare/about-us/leadership).

## To Reproduce
1. Go to the Lovell - TRICARE Leadership list: https://www.va.gov/lovell-federal-health-care-tricare/about-us/leadership
2. Confirm that the page exists but is empty.

## AC / Expected behavior
- [ ] The [TRICARE Leadership page](https://www.va.gov/lovell-federal-health-care-tricare/about-us/leadership) should be populated

## Screenshots
<img width="2168" alt="leadership-list-tricare-empty" src="https://user-images.githubusercontent.com/766573/224757031-956f42d6-7f47-4047-ba04-d6a31f6f92be.png">

![image](https://user-images.githubusercontent.com/6863534/224828924-76e19856-7607-4f37-983f-f3f3b1eb8148.png)

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [ ] `Public Websites`
- [x] `Facilities`
- [ ] `User support`

**Comment by omahane** [comment]
Note: this is a content issue. The Facilities team can do it, but we'd need to know who is supposed to be listed. @stefaniefgray or @TroyA6 may be able to help with this.

**Comment by davidmpickett** [comment]
Seems like the leadership list has been populated: https://www.va.gov/lovell-federal-health-care-tricare/about-us/leadership-0/

However, something about the URL is messing up. It has a -0 appended which means the switch link to the VA version of the page is absent

**Comment by davidconlon** [comment]
@ryguyk @davidmpickett  I just looked and this may be fixed. 
If not fixed this could block full-launch which I think we're close to.
Can y'all confirm that this is all set and I'm not crazy? (Or at the very least maybe this is not supporting evidence of me being crazy?)

**Comment by omahane** [comment]
Leadership is now populated.
https://www.va.gov/lovell-federal-health-care-tricare/about-us/leadership/

But our menu is missing.
![Screen Shot 2023-04-12 at 9 59 51 AM](https://user-images.githubusercontent.com/766573/231515857-2068684d-9a21-4c94-a9e9-c2204f98c68e.png)

**Comment by swirtSJW** [comment]
This was a content issue.   We had the VA leadership assigned to the umbrella, so it was clobbering the tricare.

We now have both pages showing humans now
![image](https://user-images.githubusercontent.com/5752113/231532348-015b170b-5920-44dd-876b-26c83b6f66ad.png)

**Comment by swirtSJW** [comment]
This issue is resolved by the content change and unrelated to the menu missing.  (separate issue)

**Comment by swirtSJW** [comment]
As a side note.  They are maintaining two leadership pages that are identical for VA and Tricare.  Perhaps they are creating space for them to differ somewhere in the future.

**Comment by davidmpickett** [comment]
> As a side note. They are maintaining two leadership pages that are identical for VA and Tricare. Perhaps they are creating space for them to differ somewhere in the future.

I believe we intentionally had them duplicated the leadership list pages because of https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12943

Having a leadership list in the umbrella system was creating problems for links and so the solution was have two separate leadership list pages

**Comment by ryguyk** [comment]
I'm not sure this needs to be the case. I don't love the idea of creating two copies of identical content _only_ so we can accommodate menus. It might be worth considering whether there are other ways to handle this need.
