### ISSUE TITLE
Redirect Request: How to get a DS Logon account

### ISSUE THREAD

**Issue by laurwill** [department-of-veterans-affairs/va.gov-cms#12944]
### Instructions
- Requests must be submitted **AT LEAST** 2 weeks in advance.  Some requests take a significant amount of time and coordination to implement, so start the process as soon as you know you will need one. 
- This issue will be used from initial request through implementation to ensure all individuals working on this are notified of status updates.  Please do not create multiple issues to track different steps.
- It is your responsibility to notify VA stakeholders as appropriate.  

### Type of request
- [X] We are retiring or taking down a page and need to redirect the URL (complete redirect section)
- [ ] We are changing the URL of an existing page (complete redirect section)
- [ ] We need a custom vanity URL (complete vanity URL section)

### Implementation date
When does this request need to be live?
Choose one:
- [ ] On a specific date, connected to a program or publishing requirement. **DATE:**
- [ ] Any day prior to a deadline/latest possible date. **DEADLINE:** 
- [ ] Any day after an earliest possible date. **EARLIEST DATE:**
- [ ] During a specific date range: ***EARLIEST DATE TO LATEST DATE:***
- [x] No hard timing requirements, publish when possible.

### Redirects 
Current URL  |  Redirect Destination or New URL
---  |  ---
current URL: https://www.va.gov/resources/how-to-get-a-premium-ds-logon-account-online/ | new URL: https://www.va.gov/resources/ds-logon-faqs/

### Vanity URLs 
Vanity URL  |  Landing page
---  |  ---
requested URL | landing page URL

**Link to campaign landing page request issue:**

### Process, Roles and Responsibilities
- [X] Requesting team: Above information is provided
- [x] Requesting team: All appropriate VA stakeholders are notified as appropriate
- [x] IA: Request is vetted and documented and implementation plan is clear 
- [x] IA: Request is assigned to appropriate team for implementation 
- [ ] Implementation team: Work is complete
- [ ] Implementation team: Validated in production
- [ ] Requesting team: Validates everything is correct in production and closes ticket

**Comment by chri5tia** [comment]
Done and waiting to check on prod before closing.

**Comment by laurwill** [comment]
Hi @jilladams @chri5tia , just confirming, is this redirect supposed to be in prod now? It's not redirecting for me. Thank you!

**Comment by jilladams** [comment]
The code has been merged but won't deploy until tomorrow morning on the weekly Revproxy deploy, ~10a ET. So: should be live within an hour or two of that tomorrow.

**Comment by laurwill** [comment]
Oh right! I forgot these were on the weekly deploy. Thank you!
