### ISSUE TITLE
Update colors in the design system.

### ISSUE THREAD

**Issue by BlakeOrgan** [department-of-veterans-affairs/va.gov-cms#12949]
## Description

- As a designer, I want to solidify the colors we are using in the design system, so that we can minimize 508 compliance issues, create a unified language for how designers discuss colors with developers, and create a solid foundation for color usage for component, pattern, and template level items that will be created in the future.
- As a developer, I want to have agreed upon rules with the designer on how colors are used, so that I can update Storybook to make reusable components that are in the CMS.
- As a CMS Editor, I want to use the CMS without running into 508 color errors and rely on established color patterns, so that I can easily complete the task that I am trying to do.

## Atomic Level

These levels match the levels in [VA.gov Design System Documentation](https://design.va.gov/)

- [x] **Foundation** - The Foundation section provides information about the visual language and styles used in the CMS.
- [ ] **Component** - Components are interactive and non-interactive UI elements that can be grouped together or presented individually. They are independent, reusable chunks of a user interface.
- [ ] **Pattern** - Patterns are solutions and researched best practices for solving user-focused tasks and recurring user interface design problems.
- [ ] **Template** - Templates, or page layouts, compose components within a single page. A layout can contain multiple variations of a component depending on the context.

## Acceptance Criteria
**Update Figma**
- [x] Simplify the number of colors in the design system.
- [x] Lightest colors should always be ADA-compliant against black and link text
- [x] Darkest colors should always be a ADA-compliant against either black or white text.
- [x] Figure out if we are depreciating any colors that are currently used and identify alternates that we will be using moving forward.
- [x] Ensure that the [CMS Design System in Figma](https://www.figma.com/file/LAlrfgqFJgCV9EIq7eyDcw/Simplified-Design-System?node-id=210%3A123&t=HGcnMLHgk9fV2TxN-1) is updated to reflect the changes listed above.

**Collab with Dev**
- [x] Set up a meeting to collaborate with the developer who will be implementing the design.
- [x] Figure out what colors that are being depreciated and change them to ones that we are using instead.
- [x] Agree on a naming convention to use in Figma and in Storybook.

**Create Follow Up Tickets**
- [ ] Create a github ticket using (this template) to update the [CMS Design System Documentation in Confluence](https://va-gov.atlassian.net/wiki/spaces/VAGOV/pages/1712324609/CMS+Design+System) and link to it as a comment in this ticket.
- [ ] Create a github ticket using (this template) for a developer to update the [CMS Storybook](https://storybook-stdirdt4jxl4xlaze1syc4vdz1pb9gvr.ci.cms.va.gov/?path=/story/introduction--page) and link to it as a comment in this ticket.

## Team
Please check the team(s) that will do this work.

- [x] `CMS Team`
- [ ] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`

**Comment by productmike** [comment]
@BlakeOrgan From the s85 and quarterly goals perspective, you have a lighter load this sprint (other than consolidating past work to develop/find playbook of how we'd like to engage NCA to further develop the permissions schema investigation). In lieu of that work, is this ticket above something that makes sense to re-enagage on your side? I think it'll dovetail nicely with potential 3Q goals as well if so. Let me know if any hesitations to pulling this in for s85.

**Comment by BlakeOrgan** [comment]
I audited colors in the Figma design system color library and compared that to what currently exists in Storybook. Storybook is currently the source of truth for all colors that are used in the CMS, so ideally Figma and Storybook should be aligned with one another to ensure that color names and HEX codes are the same in both pieces of documentation. This ensures that design and dev are on the same page when sharing artifacts between one another.

The following is some data that I found when comparing existing colors across Figma and Storybook:

- **23/60 (38%)** of colors in the Figma Design system had an exact match in Storybook
- **22/60  (37%)** of colors in the Figma Design system had a partial match in Storybook. Either a different name or a different HEX code was being used.
- **15/60 (25%)** of colors in the Figma Design system had no equivalent match in Storybook

To solve this problem, I created a new color library in Figma that matches the current state of Storybook. All Hex codes and the colors of names are now aligned across Storybook and the Figma color library. 🎉

Now that Figma is aligned with Storybook, I have also made a list of suggestions for how we can reduce the number of colors used in Storybook to further reduce any confusion and help our Figma design system be more in line with the colors used in the VA Platform design system in preparation for our eventual transition to the platform team. I have a meeting set with @edmund-dunn next week on June 8 to discuss how we might implement any planned changes to the colors used in Storybook. We will also discuss 

All color work that is part of this ticket can be viewed in [this Figma file](https://www.figma.com/file/LAlrfgqFJgCV9EIq7eyDcw/Simplified-Design-System?type=design&node-id=0%3A1&t=KQRHUTV3bHlbG5ie-1).

**Next steps:**

Two Github ticket templates need to be created in order to improve our Design system governance and create a repeatable process for all future design system updates.

- Ticket #13349
- Ticket #13350

**Comment by BlakeOrgan** [comment]
Ticket templates have been created as mentioned above and the following two tickets have been created and need to be completed before all color updates can be considered fully complete.

- Implement colors from the design system. #14268
- Update/add colors in the design system documentation. #14267
