### ISSUE TITLE
Vet Center Facility closed: Newington Vet Center Outstation

### ISSUE THREAD

**Issue by JayDarnell** [department-of-veterans-affairs/va.gov-cms#12969]
Relates to #12647 

Related slack conversation: https://dsva.slack.com/archives/C02BTJTDFTN/p1675892430252639

Redirect request: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13330

## Intake
- [x] What triggered this runbook? (Flag in CMS, Help desk ticket, Product team, VHA Digital Media)
Trigger: Helpdesk ticket

- [x] Link to associated help desk ticket (if applicable)
Jira ticket: https://va-gov.atlassian.net/browse/VAHELP-5571

- [x] Name of submitter (if applicable)
Submitter: Selena.Herbert@va.gov

- [x] If the submitter is an editor, send them a link to the operating status KB article and have them change the status to Facility notice and provide a description of the facility closure so that Veterans are aware of the future closure.
https://va-gov.atlassian.net/browse/VAHELP-5571?focusedCommentId=38566
KB articles: https://prod.cms.va.gov/help/vet-centers/how-do-i-update-my-vet-center-facilitys-basic-location-data?check_logged_in=1

- [x] Link to facility in production:
Facility link: https://prod.cms.va.gov/manchester-vet-center/newington-outstation, archived

#### CMS help desk steps
- [x] 1. CMS team becomes aware that the facility is no longer on the Facility API.
- [x] 2. CMS team submits [Redirect request](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/new?assignees=&labels=Redirect+request&template=redirect-request-facility-url.md&title=Redirect+Request+for%3A+%3Cinsert+facility+name%3E), cc'ing Facilities team, and referencing this issue.

https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13330

- [x] 3. Once timing of Redirect going live is known, alert CMS engineers to carry out the other steps

#### CMS engineer steps
- [x] 4. CMS engineer bulk unpublishes the nodes.
- [x] 5. ~~CMS engineer removes the Section.~~ Not necessary or desired in this case
- [x] 6. CMS engineer edits facility node by removing the flag `Removed from source`, sets moderation state to archived, and saves the node.

#### CMS Help desk (wrap up)
- [x] 7. Help desk notifies editor and any other stakeholders.

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [ ] `Public Websites`
- [x] `Facilities`
- [x] `User support`

**Comment by omahane** [comment]
@JayDarnell This was already archived on Feb 8, 2023. I also don't see any menu item.

**Comment by JayDarnell** [comment]
I just realized I created this using the wrong runbook so updating the steps now.

**Comment by omahane** [comment]
It seems like we still have some confusion about whether this closure is permanent or not. @stefaniefgray @TroyA6 Can you help me with getting this information?

**Comment by stefaniefgray** [comment]
Asked in https://va-gov.atlassian.net/browse/VAHELP-5571 -- @TroyA6 please update this ticket if the editor writes back, thank you!

**Comment by kmariepat-cityfriends** [comment]
@stefaniefgray @TroyA6 bump on the inquiry to the editor, can we ask the editor again

**Comment by stefaniefgray** [comment]
@kmariepat-cityfriends @omahane 

**Editor replied:**

"Stephanie,  

The Newington location was closed during COVID initially. We have been awaiting a lease contract for a permanent location for now we are located in an armory with locked doors. The clinician that is there is there three days a week by appointment only. It is in Portsmouth New Hampshire. The outstation will remain active since it is in use but there are changes in location, accessibility and contact information. All outstation traffic for scheduling, new clients and appointments come through the Manchester Vet Center since there is no admin staff at that location. I hope that helps.   

Selena"

**Comment by omahane** [comment]
@stefaniefgray @TroyA6  This message helps to clarify the information in this thread:
https://dsva.slack.com/archives/C02BTJTDFTN/p1675892430252639

# Remaining points of confusion
## Status in CMS
What's not clear to me is why the facility went from Draft to Archived on 2/8/2023 if the hope was to publish it with the hours and name change.

## Name change
The request was to change the name from "Newington Vet Center Outstation" to  "Newington Outstation," but I don't see another such example among [published outstations](https://prod.cms.va.gov/admin/content?title=&type=vet_center_outstation&moderation_state=editorial-published&owner=All). It would appear that the naming convention for outstations is "[locality name] Vet Center Outstation".

## Hours change
The request mentioned in the Slack thread is for an hours change, but aren't the hours picked up from the CMS? Shouldn't Selena be able to edit the hours? 

## Location
The latest revision message in the CMS, wherein the status was changed to Archived, mentioned an issue with the location. Can't the editor change the location in the CMS?

# Next steps
After the editor changes the location, hours, and picture, can we publish the facility?

**Comment by TroyA6** [comment]
@omahane @stefaniefgray @kmariepat-cityfriends - I have posed the naming convention question to Randi Hecht (she is no longer an 'approver' now that the VCs have been published). Her suggestion is to follow the naming convention of the other published facilities.

Here is what I have found regarding other requested changes that Christian questioned earlier: 

Address	change requests:  	Editor should Email the Vet Center RCS Help desk     VHAECHRCSNET_Helpdesk@va.gov

Phone number change requests: 	Editor should Email the Vet Center RCS Help desk     VHAECHRCSNET_Helpdesk@va.gov

Hours of operation change requests: Editor should Email the Vet Center RCS Help desk     VHAECHRCSNET_Helpdesk@va.gov

So, it looks like the processes for these requests should be shared with the requesting editor.

Thoughts? Comments? Suggestions? Feedback?

**Comment by omahane** [comment]
Based on Randi's comments, I would say not to change the name, pointing to the naming convention. I'm interested in @davidconlon's thoughts? 

I would say that after we tell the editor about the procedure for the address, phone and hours changes, the process is out of our hands.

Lastly, this is a facility closed ticket, which is actually not the case any longer. We should change the ticket name to reflect that this actually a re-opening.

**Comment by TroyA6** [comment]
@omahane @stefaniefgray - I would classify this as BLOCKED, as we are awaiting Editor response.

**Comment by stefaniefgray** [comment]
Redirect ticket not needed!

**Comment by stefaniefgray** [comment]
Checked back in with editor to see if this ticket can be closed

**Comment by stefaniefgray** [comment]
Redirect request: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13330

**Comment by omahane** [comment]
PR is made: https://github.com/department-of-veterans-affairs/devops/pull/12882

**Comment by omahane** [comment]
@stefaniefgray The redirect has been deployed: 
https://www.va.gov/manchester-vet-center/newington-outstation/
takes you to 
https://www.va.gov/manchester-vet-center/

**Comment by omahane** [comment]
@stefaniefgray This is done. Please let the stakeholders know.

**Comment by stefaniefgray** [comment]
@omahane Just notified 'em! Thanks for all your help

**Comment by jilladams** [comment]
That's all the ACs - close-able? @stefaniefgray @omahane

**Comment by stefaniefgray** [comment]
Closing
