### ISSUE TITLE
Help Desk Sprint 80 Epic

### ISSUE THREAD

**Issue by kmariepat-cityfriends** [department-of-veterans-affairs/va.gov-cms#12974]

**Comment by omahane** [comment]
@kmariepat-cityfriends We had the issue of the content-release breaking last Thursday. I worked on fixing this but never made a ticket for it. Should I do so to make sure it gets added here?

**Comment by kmariepat-cityfriends** [comment]
@omahane good call, for the purposes of tracking work capacity in the sprints I think making a ticket is a good idea. I added a card to this epic, you can add the points estimate now. Feel free to add more details as well but not fully required on my end, or maybe just the PR at a minimum.
