### ISSUE TITLE
Populate help text, Char limit, and Field/Form Widgets in spec sheet

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#12975]
## Description

Spec sheet: https://docs.google.com/spreadsheets/d/1gP6x-QLFRrJlLWdCEE1COAZXU-kRRmFKSc0sIlc_tyM/edit#gid=0

Character limits will be a draft for review, not final.

## Acceptance Criteria

- [ ] Spec sheet contains Help text, Char limit, and Field/Form Widget based on "widget" type per field, to inform CMS design

**Comment by davidmpickett** [comment]
Can of worms for what I thought would be a simple field: **Benefit Category**

I found three existing patterns for how other parts of Drupal map this:

![Screenshot 2023-03-28 223434](https://user-images.githubusercontent.com/51967950/228421888-b4a8306b-6a93-4354-abea-1ac374dc34e6.png)
![Screenshot 2023-03-28 223533](https://user-images.githubusercontent.com/51967950/228421895-9cf6a4dd-987e-4f17-9d16-ea71eed24776.png)
![Screenshot 2023-03-28 223819](https://user-images.githubusercontent.com/51967950/228421904-22103426-2895-4f97-af5c-b0ca820ddc75.png)

**Comment by davidmpickett** [comment]
[Spreadsheet](https://docs.google.com/spreadsheets/d/1gP6x-QLFRrJlLWdCEE1COAZXU-kRRmFKSc0sIlc_tyM/edit?usp=sharing) is updated with my best guess for all the fields. Points for discussion are in the far-right columns

Excel snapshot of the current state of the spreadsheet:
[VA Benefit content spec.xlsx](https://github.com/department-of-veterans-affairs/va.gov-cms/files/11097273/VA.Benefit.content.spec.xlsx)
