### ISSUE TITLE
Hide "Create account" block by default, and load only for unauthed users

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#12980]
## Description

New homepage includes a block prompting to create an account. Once a user has logged in, that block still appears, which doesn't make much sense. 

### User story
**AS A** Veteran who has logged in
**I WANT** the homepage NOT to include prominent calls to create an account
**SO THAT** I'm not confused by doubts about whether I'm logged in or not.

<img width="1153" alt="Screenshot 2023-03-15 at 2 17 15 PM" src="https://user-images.githubusercontent.com/85581471/225446091-d09607a5-737e-40f0-9ecd-104960e9d6e4.png">

### Engineering notes / background

For now we're hiding this component. In the future we will replace it with something meaningful for logged-in Veterans.

## Acceptance criteria

- [ ] Logged in user does not see new homepage Create account block
  - [ ] Test user: any account from the test user dashboard
  - [ ] Block hidden on desktop
  - [ ] Block hidden on mobile
  - [ ] Other blocks stay where they were and don't shift
- [ ] Unauthenticated user continues to see Create account block
- [ ] Design review required for both mobile and desktop

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [X] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`

**Comment by jilladams** [comment]
If we show by default and remove using JS, for authed users, the page loads with the block and then it disappears.
If we reverse the logic and hide by default, authed users never see it, and it loads after page load for unauthed users. 
Decision here in scrum: hide by default.

**Comment by jilladams** [comment]
Unassigning bc Josh ran out of time before PTO, in favor of BTSSS. We will reassign to either Daniel or Bryan to pick up. 

Josh noted: even if we hide by default and show only for unauthed users: when the page loads, it believes you are unauthed before it gets the signal that you are authed, so the block still shows momentarily then hides for unauthed. Josh will push his branch to date for someone to pick up.

**Comment by jilladams** [comment]
Show by default, hide for unauthed: 
* page loads, block appears for both authed / unauthed
* When site recognizes authed, use CSS to hide, block disappears
So: momentary visibility for authed users.

Hide by default, show only to unauthed: 
* page loads without the block for both authed /unauthed, using a "hidden" class
* class gets removed early if React thinks the user isn't authed yet, so block appears
* Once React knows you're authed, the block stays visible bc React doens't reapply the class without re-rendering the page

**Comment by jtmst** [comment]
double checked injected header on local and verified login functionality on staging
