### ISSUE TITLE
I expect vets-api endpoints are updated 

### ISSUE THREAD

**Issue by kmariepat-cityfriends** [department-of-veterans-affairs/va.gov-cms#12991]
The following AC are dependent on the technical architecture of the existing vets-api AND the product decision on keeping/maintaining the existing v0 calls (should we keep the same end points that points at v1
- [ ] I expect it has been determined whether we'll need to add new vets-api endpoint(s) or utilize existing endpoints with updated functionality
- [ ] I expect new issue(s) will be created for adding or editing a vets-api endpoint

**Comment by mmiddaugh** [comment]
Closing in favor of Update Vets-API to Lighthouse v1#15000
