### ISSUE TITLE
Get rid of the mouf node-installer thing.

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-cms#12994]
## Description
We should be managing this at the environment level rather than installing it via Composer, etc.  NVM yes.

This ticket does need to be refined to make sure that we're covering the ins-and-outs across all environments.  I should be able to do that, but if I don't get to it, eh.

## Acceptance Criteria
- [ ] NVM is installed and used by DDEV
- [ ] NVM is installed and used by Tugboat
- [ ] ~NVM is installed and used by BRD~ See #13212.

**Comment by FHiatt** [comment]
Please ignore - keeping my account active
