### ISSUE TITLE
VBA Regional Offices modernization

### ISSUE THREAD

**Issue by kmariepat-cityfriends** [department-of-veterans-affairs/va.gov-cms#13029]
## Background

This ticket is the highest level roll-up of the VBA Regional Office modernization effort. It should be used to nest initiatives/phases of the project

Edit: 10/30/23 - Phase 2 Pilot MVP sub-epic tickets moved to a single epic to reflect current state and simplify tracking

[Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/facilities/regional-offices)

### Phase 1 - Discovery & MVP Definition
- #9659
- July 2022 - February 2023
- Selected [7 MVP sites](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9961#issuecomment-1242802953)
- Conducted generative [research with Veterans](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/regional-offices/research/2022-8-veteran-facing/research-readout.pdf)
- Conducted generative [research with Public Contact Staff](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/regional-offices/research/2022-9-public-contact/vba_public_contact_research.pdf)
- MVP scope established and [shared with VBA stakeholders](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12047#issuecomment-1451850564)

### Phase 2 - MVP Design & Development
- #10514
- March 2023 - ongoing as of July 2023
- VA.gov front end design & development governed by Platform Collab Cycle
- Drupal CMS content model & editorial interface governed by CMS Collab Cycle
- VA Service Taxonomy additions governed by CAIA and Taxonomy council

### Phase 3 - Fast Follow & National Roll-out
- #14477
- Will begin after phase 2

**Comment by Agile6MSkinner** [comment]
All epics and tickets have been either completed or moved to the ongoing enhancements epic. VBA Regional Offices are officially modernized!
