### ISSUE TITLE
{P2} Plan Outreach Hub KB discovery session

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#13037]
## Description
Brief background of the problem we are trying to solve - what specifically are editors having difficulty with in the outreach hub and how might the KB assist

**Purpose**
We want to approach this as a discovery session for documentation. We want to use this as a learning opportunity on how we write knowledge base articles, training materials we provide, etc.

**Goal**
We want to encourage self-service and use of self support mechanisms.

## Acceptance Criteria
- [x] Create research plan
- [x] Draft a rough conversation guide
- [x] Async review with PO, DM, PM and Design prior to meet on 8/3

### Team
Please check the team(s) that will do this work.

- [x] `CMS Team`
- [ ] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`

**Comment by laflannery** [comment]
Set up 1:1 with Jo and Help desk for background info

**Comment by dawnpruitt** [comment]
Emailed Outreach hub editor to advise of usability study. 

From: Pruitt, Dawn M. (liberty It Solutions, Llc)
Sent: Thursday, March 23, 2023 3:37 PM

My name is Dawn Pruitt and this email is a follow up to your conversation with Dave in reference to the Outreach Materials Page help desk ticket submitted on 3/22. I am the Delivery Manager for the CMS team and have included our Senior User Experience Researcher, Jo Agnitti.

We would love to find time with you next week to conduct a usability study on the Knowledge Base (KB) article for Outreach Hub. We would like to ensure the KB content meets your needs, identify any information gaps in the KB, and capture your feedback on the helpfulness of the KB.

The usability study plan is for you to share your screen while walking through the steps of the KB. Jo will help guide the conversation while capturing usability feedback. I will also take notes to ensure nothing is missed.

We are targeting either 3/30 or 3/31 for the meeting and anticipate that it will take an hour or less. I wanted to provide this context before sending the meeting and provide the opportunity for you to ask any questions you may have. I am happy to work from your calendar availability to schedule.

We are looking forward to working with you!

**Comment by stefaniefgray** [comment]
This user has not logged into https://prod.cms.va.gov/ in 1 year and 9 months as of March 23rd, 2023.

There is **absolutely no way** that they could have attempted any of the steps listed within the Knowledge Base article in question (linked below) if they haven't even logged into the CMS.

https://prod.cms.va.gov/help/outreach-hub/how-to-create-outreach-materials-publications

**Comment by stefaniefgray** [comment]
**User wrote:**

"Good morning, The outreach materials page ( https://www.va.gov/outreach-and-events/outreach-materials ) has out of date materials on it. I have attempted to update it over and over and, while the updates seem to take, the next day they are gone. I’ve not gotten a firm answer about what is wrong other than I’m doing the updates correctly. Can someone please assist?"

**VA Drupal CMS Help Desk Support response**

"Hi Bronwyn,

I’m sorry you’ve had this experience! 

Have you attempted to edit the Outreach Hub materials recently? 

From what I can see, you have not logged into https://prod.cms.va.gov/ under your account ([Bronwyn.Emmet@va.gov](mailto:Bronwyn.Emmet@va.gov)) in 1 year and 9 months.

Please double-check the URL that you are logging into.

https://prod.cms.va.gov/ is the production environment, where changes to the live site are made. 

The production environment is where you should be logging in to add, edit, and modify Outreach Hub materials.

If you are logging into https://staging.cms.va.gov/, this is the staging environment where our developers test code changes before they go live. This staging is refreshed from the production site every 24 hours, and any changes made on staging are automatically wiped each night.

Please make sure that you are attempting to make your edits to Outreach Hub content on https://prod.cms.va.gov/. Thank you!

Once you’re logged into the production environment, you will also be able to find helpful training materials within the Knowledge Base, such as the following useful article: https://prod.cms.va.gov/help/outreach-hub/how-to-create-outreach-materials-publications

This article contains step-by-step instructions on how to add and edit Outreach Hub publications content.

If you are still having trouble updating Outreach Hub publications after logging into https://prod.cms.va.gov/ and reviewing the Knowledge Base article linked above, please let us know, and we will be happy to help.

We hope you have a great rest of your week, and we'll be here if there’s anything else you need.

Sincerely,
Stefanie Gray
VA Drupal CMS Help Desk Support"

See: https://va-gov.atlassian.net/browse/VAHELP-5592

**Comment by stefaniefgray** [comment]
**Editor:** "I’ve not tried in a long time. I think the process of updating the page has changed since I last did so. Could we archive the page, make it not visible to an external audience?"

**Our response:**

"Hi [NAME],

We cannot help you with this process if you do not log into https://prod.cms.va.gov/. 

These pages cannot be updated or revised if you are not logged into the CMS.

Please log into https://prod.cms.va.gov/, and let us know if you are able to follow the steps listed in the following Knowledge Base article: https://prod.cms.va.gov/help/outreach-hub/how-to-create-outreach-materials-publications

Sincerely,
VA Drupal CMS Help Desk Support"

**Comment by joagnitti** [comment]
After learning more and reading through the conversation Stefanie has led with this user, I realize that it doesn't make sense to call this a "usability study" (and toes the line of ethics, even); I'm not convinced UX research is the best solution for this problem. It seems like Support is handling this very well! Should we keep it in their hands?

**Comment by dawnpruitt** [comment]
PO has reached out to customer to offer assistance. No action for our team at this time.

**Comment by EWashb** [comment]
Reopening this task. We have confirmed with OPIA leadership that this would be the best path forward.

**Comment by EWashb** [comment]
Rather than testing the user's ability, we should find a way to test/confirm the usefulness of our training materials. How might we do that? We need to confirm the direction we have for editors is helpful and useful/what they need to complete the task. We would like to determine areas in our materials that need to be updated for ease of use.

**Comment by EWashb** [comment]
@productmike @BerniXiongA6 this is the work that Dave has asked about. I did speak with @joagnitti while you were out, Mike. She is aware that this is the next task after current synthesis of alt text research.

**Comment by productmike** [comment]
@EWashb @joagnitti @BerniXiongA6 
Perfecto, thanks. I'll go ahead and put 15 mins on our calendars for the 4 of us to walk through what's needed to support and start to back into timing based on that. Sound good?

**Comment by productmike** [comment]
Refinement 7/26: 
Split the ACs into three tickets: (1) workshopping; (2) research plan; (3) conversation guide. @joagnitti to schedule time with Erika, Berni, Mike, Blake

Potential outcomes: outreach hub personas?

**Comment by EWashb** [comment]
Brain dump below on other outcomes we could get from the research study:

1. feedback on KB articles in general: are they clear, concise, and helpful to the task? 
2. Feedback on Knowledge base: can you navigate to what you need/expect to find?  How would you navigate the knowledge base to find your product-specific items? Did that path align with your expectations/mental model?
3. Confidence level in your Drupal ability?
4. Confidence level in completing tasks once you've read the articles?
5. Hardships you've faced with completing your tasks in the outreach hub?


cc: @productmike @joagnitti

**Comment by productmike** [comment]
@joagnitti Same thing here as the ticket to conduct the session -- I included another AC for async review between the 3-4 of us prior to the meet on 8/3. Effectively just a sharing of your thoughts for quick feedback, but again given the timeframe here no expectation of super fine detail as more time would empower :). LMK if that AC is agreeable and if the story points need updated accordingly. Thank you!

**Comment by joagnitti** [comment]
@productmike Good call, Mike! This looks great to me. I think this might end up feeling more like an 8, but I'm good with keeping it a 5 so it doesn't seem so overwhelming 😅
