### ISSUE TITLE
EPIC: VBA Pilot MVP - CMS Editor Permissions

### ISSUE THREAD

**Issue by kmariepat-cityfriends** [department-of-veterans-affairs/va.gov-cms#13035]

**Comment by xiongjaneg** [comment]
@xiongjaneg After secondary workflow is decided/completed, scrub the issues in this epic

**Comment by davidmpickett** [comment]
@xiongjaneg All tickets in this epic have been completed, or moved to a different epic in accordance with [new organization direction](https://dsva.slack.com/archives/C0FQSS30V/p1698262564019539). Closing it as it was already pretty small
