### ISSUE TITLE
[Events] Outreach video help reflect actual (workaround) steps up upload video

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#13033]
### User story

**AS AN** Editor
**I WANT** help text in the [outreach asset UI](https://prod.cms.va.gov/node/add/outreach_asset) to correctly reflect the process for uploading a video
**SO THAT** I can figure it out.

### Engineering notes / background

- Goal is to add a video to the [Outreach materials page](https://www.va.gov/outreach-and-events/outreach-materials/).
- Ryan's workaround for adding videos includes actually uploading the video via [Add video](https://prod.cms.va.gov/media/add/video).

# Acceptance criteria

- [ ] Help text matches the process/steps

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [X] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`

**Comment by FranECross** [comment]
Closing per per Michelle M., - the IIR team is helping us with an initiative to rethink the media uploading process, and the outreach materials hub "may" move out of PW's domain. Closing (we can always recreate/revisit in the future if needed).
