### ISSUE TITLE
Use yaml-tasks instead of yaml-tests for deploys

### ISSUE THREAD

**Issue by jonpugh** [department-of-veterans-affairs/va.gov-cms#1303]
Use `devshop/yaml-tasks` package instead of the deprecated `provision-ops/yaml-tests`.

We must make sure all deploy code will still work. I think our "Deploy" playbook uses just "drush" and "drush config-import", etc, not "yaml-tests" command.

This would be a good time to change all deploy scripts to use `composer yaml-tasks $FILTER` instead of managing the list of commands in Jenkins or ansible code.

For example: `composer yaml-tasks va/deploy` 

More triage is needed.

- [x] Find replace in devops repo https://github.com/department-of-veterans-affairs/devops/pull/6636
- [ ] Deploy to DEV before merge for testing BRD
- [ ] Coincide merge of https://github.com/department-of-veterans-affairs/devops/pull/6636 with https://github.com/department-of-veterans-affairs/va.gov-cms/pull/1304. 
- [ ]  Users / Customer facing communication planned
- [x] Create follow up story to remove redundant deploy steps (cache:rebuild, updatedb, config:import) from ansible/deployment/config/cms/tasks/post-init-tasks.yml and ansible/deployment/config/cms/tasks/post-init-tasks-prod.yml because it is being run twice now, the second time being in the deploy/* section of tests.yaml. 
#1377

**Comment by ElijahLynn** [comment]
We should be getting this done in next Sprint, going to remove the HTTPS for devshop as a blocker. It isn't ideal but it will only affect engineers.

**Comment by ElijahLynn** [comment]
Kinda dependent on what we do in #2679.
