### ISSUE TITLE
Add Vet Centers editor emails to existing tasks.yml

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#13044]
## Background
We had previously enabled tasks.yml to send automated notification emails for VAMC editors (#12783). We need to add Vet Centers to this same tasks.yml so that these editors are now also receiving monthly notifications.

## User Story

As a CMS developer, I need tasks.yml appropriately configured so that I can ensure 6102 notification emails are sent on the proper cadence to Vet Center editors. 

## Acceptance Criteria
These will need to be determined/refined once we are unblocked as we cannot set the timeline until then

- [ ] wait to do until 30 days after the first manual email
- [ ] Monthly `task` job is created starting at 3am ET on the last day of the month
- [ ] Email queue is populated once per month and not more than once per month

**Comment by xiongjaneg** [comment]
per Mike and Jane discussion, Facilities to take first pass due to existing experience with this and then connect with CMS team engineer for knowledge transfer

**Comment by xiongjaneg** [comment]
question for CMS team: if there's a bouceback from an editor who's gone, do we get bouncebacks and if we do, what do we do with them?

**Comment by xiongjaneg** [comment]
Erica confirmed the sent email does get bouncebacks for editors who have left. Not certain about the automation of this. That would be desirable.

**Comment by xiongjaneg** [comment]
@swirtSJW If we don't need the first manual email ticket, do we still need this one?

**Comment by swirtSJW** [comment]
This is also completed as the work done in #14816
