### ISSUE TITLE
State of published content in CMS on VA.gov

### ISSUE THREAD

**Issue by indytechcook** [department-of-veterans-affairs/va.gov-cms#1306]
As a content editor, I want to know if the content I have published in the CMS is currently live on the public website.  I should be able to see this information from within the CMS.

Possible implementations
* Drupal check which revision id is live on va.gov, like in this screenshot
![VA_Education_Benefits___Veterans_Affairs](https://user-images.githubusercontent.com/643678/82075600-7a60ea80-96aa-11ea-9253-583e67fca79e.jpg)

**Comment by acrollet** [comment]
Related completed work: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/2861

**Comment by jefflbrauer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VAgov-CMS-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/1306?planning-poker) with ZenHub @ElijahLynn @indytechcook @ndouglas @olivereri @timcosgrove

**Comment by jefflbrauer** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VAgov-CMS-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/1306?planning-poker) with ZenHub @cweagans

**Comment by kevwalsh** [comment]
Closing this in favor of #8229
