### ISSUE TITLE
Identify tool to store and iterated on canned responses. 

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#1307]
Splitting out from #1224 

## Description

AC
* We have identified a tool to store and iterate on our canned responses for help desk

To do
* Research eligible tools
* Take each for a spin to see how our content would work there

Can be Internal for now. Airtable / Google Doc / va.gov-team github repo.

**Comment by howardbrande** [comment]
WIP on Github https://github.com/department-of-veterans-affairs/va.gov-cms/edit/master/helpdesk-responses/README.md

**Comment by howardbrande** [comment]
Google Doc: not usable since it cannot be accessed on the VA network

**Comment by howardbrande** [comment]
AirTable WIP 
https://airtable.com/tblQDX8dwkhmUExm0/viw7oDaHVRETiUYAk?blocks=hide
