### ISSUE TITLE
VA Benefits Taxonomy Build Ph4: Complete and merge

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#13075]
### User story

**AS AN** Editor
**I WANT** benefit data to be structured in the CMS
**SO THAT** I can create content once and have it published everywhere with consistent messaging. (COPE – create once publish everywhere)

**AS AN**  Veteran 
**I WANT** VA benefits to be discussed in any product using the same consistent language 
**SO THAT** I feel reassured that the information is accurate and trustworthy.

### Engineering notes / background
Phase 4 build for the benefits taxonomy includes finishing up any tickets for technical pieces extracted through phase 1-3 that needed a closer look, writing automated tests, fine code review and pushing to production.

### Quality / testing notes
This ticket should include automated tests.
* No circular dependencies on taxonomy entity references
* Title can't be edited by anyone but an Admin
* API field lock behavior

## Acceptance criteria
Phase 4:
- [ ] Final CMS config
- [ ] Automated tests cover listed test cases and are passing
- [ ] PR review and functional testing
- [ ] PR concerns addressed
- [ ] Final PR signed off by Code Reviewers (Daniel, Tim, Steve) and merged
- [ ] Product sign off from: Wes, Dave P., Jordan, before merge
- [ ] PR merged
- [ ] Verified in production: Christia demo to Wes

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [X] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`

**Comment by chri5tia** [comment]
Note from phase 1: 

- [ ] Decide strategy for taxonomy name property label change: weight doing a hook form alter for this vs. base field overrides in config (phase 1 closed using hook form alter)

**Comment by chri5tia** [comment]
- [ ] fix unrelated cypress test failure

**Comment by wesrowe** [comment]
@chri5tia, noting here Steve's suggestion in another ticket for regarding moving uniqueness error messages to the fields they're addressing.

**Comment by wesrowe** [comment]
@jilladams, Notes from sync Fri 4/28:
- The oustanding requirement that we need to resolve is the immutability of Official Name and API ID. @chri5tia and I have the impression that the workflow module would enable Content Editors to create new terms, including those 2 required fields. But our model, VA Services, doesn't seem to have resolved this piece of the term creation experience either.

I'm going to slack Steve W about it now.

**Comment by jilladams** [comment]
From discussion with Wes this morning: 
* Taxonomy workflow will fix: Draft vs. Published states, ability to add a Revision log. Will _not_ affect roles/permissions for creating terms.
* VA Services taxonomy paradigm is / has been that a Drupal Admin must create the term, and after that: Editors can create revisions.

If we follow suit: Drupal Admins must always create VA Benefit terms. Then Editors can modify them.

**Comment by jilladams** [comment]
Live on prod!
