### ISSUE TITLE
VA Benefits Taxonomy Build Ph3: CMS Collab cycle

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#13074]
### User story

**AS A** PO
**I WANT** the VA Benefits Taxonomy implementation to go through CMS Collab Flow/Cycle
**SO THAT** we make sure it aligns with platform goals before merging

### Engineering notes / background

Source of truth for what should be implemented is the [BCM spec](https://docs.google.com/spreadsheets/d/1gP6x-QLFRrJlLWdCEE1COAZXU-kRRmFKSc0sIlc_tyM/edit?usp=share_link) (Google sheet; please request an Excel copy if you need one.)

### Quality / testing notes

QA still light until Phase 4

## Acceptance criteria

Phase 3
- [x] CMS Flow / Collab cycle review meeting
- [x] 508 concerns raised and addressed
  - [x] Bring LauraF in to mini-sprints if not during her PTO
- [x] Changes are made based on Collab Cycle feedback, including changes to fields and configs, UI, 508
- [x] Final round of thorough Interface testing after CMS collab cycle changes not local (Tugboat)
  - [x] Test as Content Admin
  - [x] Test as Drupal Admin
- [x] Architecture polishing based on collab review
- [x] Updated PR for team review (in phase 4)
- [x] Any Collab Cycle feedback that won't be addressed in MVP filed as separate tickets
- [x] Collab signed off on any issues fixed via in collab cycle review (Ph 3)
   - [x] Includes: Laura, & CMS eng(Tony?Nate?)
- [x] Design team review (Dave P., Blake)
- [x] PR NOT merged yet

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [X] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`

**Comment by jilladams** [comment]
5 estimate is a guess until we get the full scope of collab cycle feedback.

**Comment by laflannery** [comment]
Changes to help text suggested in the [Figma mockup](https://www.figma.com/file/1xUGIKRiuVmYMUoXYTr0BI/Benefit-Content-Model?node-id=6-4792&t=3OC1WXfb5UVF11nk-0)

**Comment by chri5tia** [comment]
Thanks @wesrowe. Here is the ticket for uniqueness if you want to update it to include other logic: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13231

**Comment by chri5tia** [comment]
4/12 Checkpoint notes:

- Default fields to not required and iterate later, check spec, notes and action items added to #13206 
- API Design? API design vs API ID field #13142 

A11y header stuff: collab cycle chat, post-MVP, it's own epic:
- https://www.drupal.org/project/drupal/issues/3303777
- https://www.w3.org/WAI/GL/wiki/Using_Standard_Text_Formatting_For_Headings#Example_2

**Comment by chri5tia** [comment]
4/13 benefit eligibility headers meeting notes:
@laflannery @davidmpickett and I grouped on the header conversation and how it relates to Benefits Taxonomy project

Eligibility summary will end up with “blobby chunks” of information that need to be structured either by the system or by the editor, such as: age, length of service, dates of service, etc. but without the use of the problematic Header tags in a WYSIWYG editor.

Rich text limited has removed the headers but leaves no option for information structure.

There is a predictable pattern here in the way information will need to be structured, within the eligibility summary, that warrants exploration. We have ideas.

Due to the size of the project of content modeling so far, we put a pin in it, but will need to discuss when to pull the pin.

This will likely come up in the collab cycle, and now I see why it doesn’t necessarily need it’s own.

**Comment by davidmpickett** [comment]
> Eligibility summary will end up with “blobby chunks” of information that need to be structured either by the system or by the editor, such as: age, length of service, dates of service, etc. but without the use of the problematic Header tags in a WYSIWYG editor.

For more details on the blobby chunk problem, see this ticket: #13143

> There is a predictable pattern here in the way information will need to be structured, within the eligibility summary, that warrants exploration. We have ideas.

Very rough sketch of a possible solution https://app.mural.co/t/departmentofveteransaffairs9999/m/vagov6717/1660845137501/6eadf59a3f4d8dcd29da572a68115a22d6114fe4?wid=0-1681487526574

**Comment by laflannery** [comment]
@chri5tia for the checkboxes for the audience:
- everything should be wrapped in a `<fieldset>`
- the "Choose the beneficiaries..." text should be the `<legend>` element

If that is not happening, and you are using what Drupal is just giving you, you do not need to change/fix this because it is most likely happening elsewhere in the CMS and the CMS team will need to make a global fix. Just let me know so that I can investigate and make a ticket for CMS.

**Comment by jilladams** [comment]
Collab cycle feedback notes: 
* Make sure @BlakeOrgan gets eyes on it. Have invited him to the Wed 4/19 team project sync.
* Implement Laura's notes above.
* Make sure Tim Cosgrove is added as code reviewer on the PR.
* Triple check Tugboat state vs. spreadsheet to confirm that any dark grey fields in the spec are actually removed from the code / not committed, vs. hidden. (Swirt thought he saw `Benefit application type` in the Tugboat env, which should not be included in MVP.)

@chri5tia @wesrowe did I miss anything?

**Comment by wesrowe** [comment]
I think this might be an issue with the URL/Link field that we reused here... the error message is confusing as it doesn't agree with the help text or actual validation. `Https://` is an acceptable/recommended way to start an external link, but the error message doesn't acknowledge it:
<img width="755" alt="image" src="https://user-images.githubusercontent.com/4054752/232166627-c37f950b-d0bd-4f5d-9f7e-07d0f2794ebf.png">

**Comment by wesrowe** [comment]
Reminder to hide/disable the Relations block.
<img width="467" alt="image" src="https://user-images.githubusercontent.com/4054752/232167349-7f37c8cb-5186-415b-8c15-39db0a42f79b.png">

Also, wondering if there should be "unlock" and/or "cancel" buttons present?

**Comment by chri5tia** [comment]
Unlock will be implemented during workflow, and will show up if it is locked (if locking is part of workflow). As to cancel, not sure what that would be used for if we use it elsewhere on the site. Do you see any examples of it being used?

**Comment by chri5tia** [comment]
4/19 Checkpoint notes:

There are some CMS design system considerations that come into play here. We strategized whether or not they should be addressed separately as global CMS concerns or what things can be changes for this feature.

- [ ] See if help text and error message can be changed for Benefits Taxonomy for Link widget

- Timebox Laura's suggestion or decide to use an existing pattern from design system for the multi-select list (such as multi-select list until such a time that multi-select functionality is addressed globally). 
- [ ] Provide update on the above by tomorrow (can I implement the requirements into checkboxes as part of this work or if it should be separate based on time, complexity)

- Link widget error text and help text; help text should be contextual for the feature the widget is used in; Daniel recommended that I used the Linkit field widget for this product instead, which addresses some of this
- Soft character limit design

Post check point meeting items:
- [ ] Replace link fields with linkit field widget

**Comment by chri5tia** [comment]
Linkit module isn't going to work here from what I can tell, as it's for wysiwyg editors. 

Code that defines the LINK help text and error text is part of the core Link Widget module:

/Users/christiahall/Sites/dorquenet/docroot/core/modules/link/src/Plugin/Field/FieldWidget/LinkWidget.php, line 146

```
    // If getUserEnteredStringAsUri() mapped the entered value to an 'internal:'
    // URI , ensure the raw value begins with '/', '?' or '#'.
    // @todo '<front>' is valid input for BC reasons, may be removed by
    //   https://www.drupal.org/node/2421941
    if (parse_url($uri, PHP_URL_SCHEME) === 'internal' && !in_array($element['#value'][0], ['/', '?', '#'], TRUE) && substr($element['#value'], 0, 7) !== '<front>') {
      $form_state->setError($element, new TranslatableMarkup('Manually entered paths should start with one of the following characters: / ? #'));
      return;
    }
  }
```

and line 222:

```
    // If the field is configured to allow both internal and external links,
    // show a useful description.
    elseif ($this->supportsExternalLinks() && $this->supportsInternalLinks()) {
      $element['uri']['#description'] = $this->t('Start typing the title of a piece of content to select it. You can also enter an internal path such as %add-node or an external URL such as %url. Enter %front to link to the front page. Enter %nolink to display link text only. Enter %button to display keyboard-accessible link text only.', ['%front' => '<front>', '%add-node' => '/node/add', '%url' => 'http://example.com', '%nolink' => '<nolink>', '%button' => '<button>']);
    }
```

**Comment by chri5tia** [comment]
Laura's suggestion should be handled by the CMS team for themeing. Need to decide where we go from here. (Multi-select list for now, etc.)
