### ISSUE TITLE
VA Benefits Taxonomy Build Ph 2: Add design elements and prettify per design

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#13071]
### User story

**AS A** Content Admin
**I WANT** the VA Benefits Taxonomy UI to follow the design
**SO THAT** it is clear and easy for me to enter benefit content.

**AS A** PW developer
**I WANT** to iterate the UI to its designed state
**SO THAT** I and team members can review and identify any iterations that are needed to the product.

### Engineering notes / background

Source of truth for what should be implemented is the [BCM spec](https://docs.google.com/spreadsheets/d/1gP6x-QLFRrJlLWdCEE1COAZXU-kRRmFKSc0sIlc_tyM/edit?usp=share_link) (Google sheet; please request an Excel copy if you need one.)

Follow design created in #12383. 
**MOCKUP:** https://www.figma.com/file/1xUGIKRiuVmYMUoXYTr0BI/Benefit-Content-Model?node-id=6%3A4791&t=eniBhcrYY9Zy61ot-1

### Analytics considerations
n/a

### Quality / testing notes
- Basic QA on this pass
- Detailed code review

## Acceptance criteria

- [ ] UI now follows CMS designs from #12383 
  - [ ] help text added for all fields (per spec)
  - [ ] field/form widget added for all fields (per spec)
  - [ ] text input appropriate per text format field in spec (ie formatter)
  - [ ] inputs laid out per design, e.g. by fieldset
  - [ ] followed considerations in the BCM spec column R, "Notes for Drupal Engineers"
- [ ] CMS and Design roadblocks, changes, or questions uncovered during stage 1 are considered:
  - [ ] discussed in mini-sprints and documented in the ticket
  - [ ] new tickets cut per item discovered if they warrant more than a 30 minute conversation or need to involve more parties (e.g. we can’t make Drupal to do the thing we want)
- [ ] Field config and UI is ready for collab cycle review
- [ ] revision log messaging matches what editors experience on editing nodes (note: workflow moved to [new ticket](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13141))
- [ ] reviewed, preferably in a group demo meeting, by:
  - [ ] LauraF (508) (Final sign off will be later)
  - [ ] Wes
  - [ ] Jordan (design)
  - [ ] Dave Pickett (content strategy)
- [ ] light code review by one or more of: Daniel, Tony, Swirt (to avoid late surprises with CMS Collab Flow)

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [X] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`

**Comment by wesrowe** [comment]
Note that I focused the ACs on the fields that we reviewed in yesterday's meeting.

**Comment by wesrowe** [comment]
Per discussion with Christia, ticket now applies to all fields/rows in the spec, not just thru 17.

**Comment by chri5tia** [comment]
4/10 checkpoint items:
- [ ] Official benefit name help text
- [ ] "Add another item" > "Add another link" (Related legislation, pre-requisite benefit, co-considered benefits)
- [ ] Related VA forms add button > "Add another form"
- [ ] Remove "TODO" things from help texts (preparing to apply, getting help)

**Comment by chri5tia** [comment]
Demo environment: https://cms-i7n92wfzswpe358hivrspihf2ntzshzp.ci.cms.va.gov/taxonomy/term/1141/edit

**Comment by wesrowe** [comment]
Meets ACs, a few requirements being finalized and will be implemented in Ph 3 ticket.
