### ISSUE TITLE
Update Yellow Ribbon UI for current school year

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#13083]
~~**BLOCKED: on 3/28 Wes emailed Janice Fisher to confirm that this change is appropriate.** Janice seems to be OOO, but Jill was CC'd on the email so she can update the ticket.~~

### User story

**AS A** Veteran or Beneficiary
**I WANT** to see the current school year in the search tool UI
**SO THAT** I feel confident the other info provided is accurate.

On the main [Yellow Ribbon search page](https://www.va.gov/education/yellow-ribbon-participating-schools/):
![image.png](https://images.zenhubusercontent.com/61a671f5fc46c2a311655f75/6e93d09f-a802-4e21-a679-f50a27819af3)
- Note that it says "You may search for schools participating in the current academic year, August 2021 through July 2022."

On the subsequent [Yellow Ribbon Search Results page](https://www.va.gov/education/yellow-ribbon-participating-schools/?state=CA):
![image.png](https://images.zenhubusercontent.com/61a671f5fc46c2a311655f75/44a55cf3-2d50-4ef4-babf-4dbe76a22154)
- Note similar (incorrect) language about school year, "Information for participating schools is for the current academic year, August 2021 through July 2022."

### Engineering notes / background

Make change to content manually/hard-coded:
https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/yellow-ribbon/constants/index.js#L9

## Acceptance criteria

- [x] Confirmed with stakeholder (Stakeholder from 2021: Janice Fisher at VBAVACO ([janice.fisher1@va.gov](mailto:janice.fisher1@va.gov)) that the current school year is in fact "August 2022 through July 2023."
- [x] When dates are confirmed...
  - [x] Main Yellow Ribbon page refers to current school year as "You may search for schools participating in the current academic year, August 2022 through July 2023."
  - [x] Yellow Ribbon Search results page refers to current school year as follows: "Information for participating schools is for the current academic year, August 2022 through July 2023."
  - [x] Searched codebase for any other references to "current school year", e.g. in an alert or something
    - [ ] If found, notified Wes
    - [ ] Fixed or ticketed those instances

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [X] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`

**Comment by wesrowe** [comment]
@rlhecht, can you confirm that the ACs above are accurate? 

Also, since we're learning for the first time that this app needs annual maintenance - do you have any idea whether the underlying data is being updated annually? Or how we would find out?

cc @jilladams

**Comment by jilladams** [comment]
Verified! 
![Screenshot 2023-04-04 at 4 07 06 PM](https://user-images.githubusercontent.com/85581471/229941788-a42ce0f6-f13f-4635-90e8-d0bb6f668bd6.png)
