### ISSUE TITLE
Discovery: Yellow Ribbon search tool implementation and health monitoring

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#13084]
### User story

**AS A** PW team member
**I WANT** to understand how the Yellow Ribbon tool works and how its health is monitored
**SO THAT** I can be sure that it is serving Veterans as intended.

Dave C found this [old ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/16500) that's related to updating text:
- It implies the data is updated annually without VAgov involvement
- Stakeholder from 2021 is identified: Janice Fisher at VBAVACO ([janice.fisher1@va.gov](mailto:janice.fisher1@va.gov))
- Confirms that text about the "current school year" needs to be verified and hard-coded every year by the VAgov team 

### Engineering notes / background

Wes reached out to Janice Fisher to verify she's still the right stakeholder. Notes in #13083.

## Acceptance criteria

**Product ACs:**
- [x] Searched for a Domo dashboard (link) – The "VAgov Search KPIs" dashboard in Domo has a YR option in the `search_scope` filter ([this link](https://va-gov.domo.com/page/1964748112) may work, but Domo doesn't seem to support link-sharing) 
- [x] Find documentation of product intention/goals
- [x] Have read/ grokked [existing Yellow Ribbon docs we have](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/public-websites#yellow-ribbon-tool)

**Eng ACs**
Discovery of implementation:
- [x] Have read/ grokked [existing Yellow Ribbon docs we have](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/public-websites#yellow-ribbon-tool)
- [x] Find docs / document how data is pulled from APIs, what is BE, etc.
  * **NOTE**: these findings will be particularly relevant for Income LImits, which could maybe work exactly the same way. Detailed notes appreciated.
- [x] Find any technical documentation of how data/DB behind search is governed, refreshed

Health monitoring:
- [x] Looked for custom GA tracking – at code level and AdSwerve console messages (Josh or Wes have AdSwerve)
- [x] Is there any protection of the Veteran experience from BE failures – Sentry logging, error states that lead to emails (like on find-a-form), etc.
- [x] Findings are documented in this ticket and Github documentation 

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [X] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`

**Comment by jilladams** [comment]
From planning: Pulling into sprint bc we expect to have some capacity to start, but likely not finish, in Sprint 84.

**Comment by wesrowe** [comment]
Product ACs completed, and I added how to find the Domo dashboard within the ACs.

Original product docs list some KPIs/OKRs to track, but they are not baselined and that may be because they are difficult to measure or not directly attributable to the app. E.g., "Track how many users did [outcome like account creation] in the same session they looked at the YR tool page" is not causality, only association.

**Comment by jilladams** [comment]
@wesrowe if the Domo dashboard isn't linked anywhere int he product docs you read in Teams repo, could you add it?

**Comment by wesrowe** [comment]
I already added to ticket body a description of where to find the Domo dash. (Not directly linkable due to Domo shortcomings)

**Comment by jilladams** [comment]
I meant the product docs, not the ticket.
