### ISSUE TITLE
Document translation management current state

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#13097]
## Description
There are several steps needed to collect content for translation, export it, import it, review it, and save it as a translation. We need to documentation the current state of translations including the previously mentioned steps. This documentation might also include a possible suggested process for a translations manager, how they might work within the existing architecture.

```[tasklist]
## Acceptance Criteria
- [x] Documents on the translation management process are created in Github
  - <https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/READMES/translation.md>
```

### Team
Please check the team(s) that will do this work.

- [x] `CMS Team`
- [ ] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`

**Comment by laflannery** [comment]
Is there current documentation on the implementation and what has been done to date anywhere?

**Comment by timcosgrove** [comment]
This was documented here: https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/READMES/translation.md
