### ISSUE TITLE
Spec Drupal work for VBA Regional Office MVP

### ISSUE THREAD

**Issue by davidmpickett** [department-of-veterans-affairs/va.gov-cms#13096]
How do we go from a high level diagram to actionable Drupal tickets?

-  [VBA Content Model in Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/vagov6717/1677277602711/74cecb64b6eeb9558aa868240cd726b54fcb93a7?wid=0-1680038357024)

![Screen Shot 2023-03-28 at 3 53 55 PM](https://user-images.githubusercontent.com/51967950/228364372-8b1d9758-9951-42c8-b573-8e26b2c60ee0.png)

![Screen Shot 2023-03-28 at 6 42 23 PM](https://user-images.githubusercontent.com/51967950/228390793-2e1fe5dc-5605-461f-adb3-22bfa9c4e42e.png)

**Existing entities that will need updates**
- VA Services taxonomy (VBA fieldset)
- VBA Facility Service
- VBA Facility 
- Service location

**New entity**
- VBA Service Region
- VBA menu

Each of these will might need a detailed spec ala [VA Benefit content spec](https://docs.google.com/spreadsheets/d/1gP6x-QLFRrJlLWdCEE1COAZXU-kRRmFKSc0sIlc_tyM/edit?usp=sharing)

**Comment by swirtSJW** [comment]
@davidmpickett  typically we spec it out like you have done (or less than you have done ;) ), then identify what parts can be built separately, and what parts must go together.   Then we spin up the tickets from there.

**Comment by omahane** [comment]
I'd also suggest having some design work done for the CMS editorial experience so that we know what the expectations are. For instance, with a lot of other content, we are doing some custom wizardry:
- Bringing in content from related entities, based on a selection, either for a Tooltip or added to the WYSIWYG
- We have fields that are disabled but visible
- We have fields are are completely hidden to editors

**Comment by swirtSJW** [comment]
Off the cuff I think the tickets would look like this

- Design for VBA fieldset on VA Service Taxonomy
- Design for Service Location paragraph
- Design for Service Region
- Design for VBA Facility
- Design for VBA Facility Service
- Add VBA fieldset to VA Service Taxonomy
- Refactor Service location paragraph
- Create VBA Service Region
- Add fields to VBA Facility
- Add fields to VBA Facility Service

**Comment by kmariepat-cityfriends** [comment]
@davidmpickett AC wise, I would be interested is seeing:

- I expect a detailed content model spec is created for all of the following content types?
- `VBA Service Region` 
- `VBA menu`
- `VA Services taxonomy (VBA fieldset)`
- `VBA Facility Service`
- `VBA Facility`
- `Service location`

What are the drupal terms for the above, they are referred to as entities in the description of this card, is that a highest level grouping term. I know some of these are what is known as a content type in drupal, what are the others known as?

**Comment by davidmpickett** [comment]
**Entity > Content > Node > Content Type**
VBA Service Region
VBA Facility Service
VBA Facility

**Entity > Content >  Node > Paragraph Type**
Service location

**Entity > Content > Taxonomy Term >  Vocabulary**
VA Services taxonomy 

**Entity > Configuration > Menu**
VBA menu

**Comment by kmariepat-cityfriends** [comment]
Next Steps: chat with CMS collab cycle to determine which is most important to work on first, our proposed 


- Service Location paragraph
- Service Region
- VBA fieldset on VA Service Taxonomy

**Comment by jilladams** [comment]
@kmariepat-cityfriends added to Sprint 81 (based on [Slack](https://dsva.slack.com/archives/C0FQSS30V/p1680108728309759) that this is a sprint goal)

**Comment by xiongjaneg** [comment]
@davidmpickett I stubbed out some UX review tickets to follow implementation tickets.

**Comment by davidmpickett** [comment]
@xiongjaneg This VBA epic is nearly closable, just need decision on whether 15757 is Pilot MVP or National MVP

**Comment by xiongjaneg** [comment]
@davidmpickett Michelle and I did discuss moving supplemental status to National MVP given the tight timeline, so closing sounds right. I'll move the last ticket and close the epic.
