### ISSUE TITLE
Can no longer get ids for vet center on facility locator -- How do we now surface this info

### ISSUE THREAD

**Issue by kmariepat-cityfriends** [department-of-veterans-affairs/va.gov-cms#13108]
Make a separate issue for this because the, need to make a new pattern because you can no longer get ids for vet center on facility locator

For Step 10, there is no mention of how to find the facility ID in order to add it into one of these fields. In case this is not be obvious for all editors, it should perhaps be added here

**Comment by mmiddaugh** [comment]
A change must have recently resolved this issue as an editor can see  the ID within the Locations and contact information block.  Closing as resolved
<img width="499" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdytUQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--48c2d22635ccc108553e282edfaa15c28dd9c4f3/image.png" alt="image.png" />
