### ISSUE TITLE
Remove btsss_login_widget feature flag after launch

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#13117]
## Description

#12591 created a flipper, `btsss_login_widget` for the purposes of testing / launch. 

When BTSSS widget is launched, this flipper can be deprecated. 

### User story
> _Describe the audience/user, enhancement or fix, and value / outcome desired._

**AS A(N)** engineer
**I WANT** to reduce technical debt and the number of feature flags in play
**SO THAT** the build system stays optimized.

(This story is speaking for Plat where they care about the fact of Flippers, but I can't speak technically to why.)

### Order of operations
* Remove from vets-website first (to show widget regardless of flipper, and remove flipper references)
* Remove from vets-api after

## Acceptance criteria

- [x] I expect that the `btsss_login_widget` is no longer present in vets-api code or flipper UI
- [ ] I expect that the BTSSS login widget still appears correctly in prod

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [X] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`

**Comment by jilladams** [comment]
3 assumes this could be a good ramp up task for Randi.

**Comment by randimays** [comment]
Validation complete for staging and production for vets-website and vets-api changes. Waiting on the flipper dashboard to catch up (and remove the flag) as final validation.

**Comment by randimays** [comment]
Still waiting on flipper dashboard to catch up and remove the flag here: https://api.va.gov/flipper/features Not sure what the standard waiting period is, but it looks like this ticket won't close in time for the new sprint.

**Comment by jilladams** [comment]
Totally fine. If we don't see this ship in a day or two, may be worth a #vfs-platform-support ask to understand timing and if we hit all the necessary boxes for it to wrap.

**Comment by randimays** [comment]
I made a [Platform Support ticket](https://dsva.slack.com/archives/CBU0KDSB1/p1682527701785429) to see what's happening with the flipper dashboard. Waiting for a response.

**Comment by randimays** [comment]
Screenshots for prod validation

Logged In
<img width="1263" alt="Screenshot 2023-04-27 at 4 25 10 PM" src="https://user-images.githubusercontent.com/19175324/234994851-a8e7a278-bd3d-4448-85bf-b802fae95231.png">

Not Logged In
<img width="1437" alt="Screenshot 2023-04-27 at 4 25 26 PM" src="https://user-images.githubusercontent.com/19175324/234994848-60facfc8-f12c-43f4-a6bf-844cd7a23d5a.png">

**Comment by randimays** [comment]
Support ticket and Slack thread for reference:
https://github.com/department-of-veterans-affairs/va.gov-team/issues/57465
https://dsva.slack.com/archives/CBU0KDSB1/p1682527701785429

**Comment by wesrowe** [comment]
Since this is Platform's problem and they have a process around it, I think we can close.

**Comment by jilladams** [comment]
INTERESTING. I did _not_ know that the pruning job was doing this exact work. @randimays did Platform indicate they would run the pruning job? Or now is it expected behavior that removed flags will appear in the UI? Do we know what happens if we try to modify the flag, now that it doesn't exist?

**Comment by randimays** [comment]
@jilladams Platform said in [the support ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/57465) that they would try to get it manually removed, but not that they would run the job. I think it's disabled until they can dig deeper. For now the expected behavior is that removed flags will still appear in the UI until that job is fixed. Since there is no `vets-api` mapping for the flag anymore, and no code in the UI to respond to it, changing it in Flipper Admin shouldn't do anything.
