### ISSUE TITLE
The revision log message displays html  <em>Wed, 07/17/2019</em>

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#1311]
**Describe the defect**
The revision log message appears with html code in the right sidebar. 

**To Reproduce**
1. Revert any node to an earlier version
2. See that the revision log message contains HTML

**Expected behavior**
1. No html code should show on FE.

**Possible fix**
* Could be a views formatting problem?
* Could be a drupal core issue with revisions
* stripping HTML would be acceptable

**Screenshots**
![About_VA_Health_Benefits___Veterans_Affairs.jpg](https://images.zenhubusercontent.com/5d6e57ad330f64311395f08b/ef06e61c-9a12-4a8f-be44-3633e529cc92)

![Revisions_for_VA_education_and_training_benefits___VA_gov_CMS](https://user-images.githubusercontent.com/643678/82075002-957f2a80-96a9-11ea-9f1e-f35df620f948.jpg)

**Comment by oksana-c** [comment]
closing in favor of #1884
