### ISSUE TITLE
Drupal 10 upgrade testing - Facilities Team

### ISSUE THREAD

**Issue by kmariepat-cityfriends** [department-of-veterans-affairs/va.gov-cms#13112]
This epic is to track the work for the Facilities team testing the Drupal 10 upgrade. Any tickets created that pertain to the Facilities Team aspects of Drupal 10 should be tracked here, even if they are being worked on by the CMS team.

Slack threads about process: 
- https://dsva.slack.com/archives/C03LFSPGV16/p1688749304944389
- https://dsva.slack.com/archives/C03LFSPGV16/p1689011453969499

Spreadsheets
- Jill's spreadsheet https://docs.google.com/spreadsheets/d/136FP-HtxRWJuPYYV4D95ngby96Wqy4Ul_HOgOqEk1K0/edit#gid=1052173265
- CMS spreadsheet https://docs.google.com/spreadsheets/d/1R4g9jSZJvGRCAWWoslnxlC2hv5A2kHKMMxabbct3bI4/edit#gid=0

[Drupal 10 Tugboat home page](https://tugboat.vfs.va.gov/64c11c302d3036648d7f600e)
[Drupal 10 environment](https://vacms-12252-drupal-10-esdtuqzba9g5gopezqazojjvehr8jy4i.ci.cms.va.gov/)

Slack channel for upgrade chatter
- https://dsva.slack.com/archives/C05EJD52H1R

CMS Team Epic
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13475

**Comment by kmariepat-cityfriends** [comment]
ask @EWashb and @productmike about priority of this

**Comment by jilladams** [comment]
Note: we don't know trigger timing for when CMS team will be ready for us to begin. 

Another concern I have: @BerniXiongA6 / @productmike / @edmund-dunn  :  we'll need to work out when / how changes are deployed to the test environment, once testing gets rolling. I'd like to make sure we avoid churn during testing that may come out of frequent changes to the test environment. An ideal way to handle would be create an automated test for any fixes required as a result of tests, so the automated test can "rerun" the test case and verify the fix.
