### ISSUE TITLE
Audit Facility API NCA data to determine what fields need to be added and migrated accordingly

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#13123]
## Description
As a NCA stakeholder I would like the relevant data that lives in the Facility API related to NCA facilities to also be present in the CMS so there is parity with the other facility types that are in the CMS.

## Note
- there may be existing documentation, can ask Adam 

## Acceptance Criteria
- [x] I expect fields to be added to the nca facility content type are specified 
- [x] I expect a card is made to add the identified fields to the content type 
- [x] I expect a card is made to implement the field mapping in the NCA migration  
- [x] Any custom processing needed for NCA migration is specified.

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [ ] `Public Websites`
- [x] `Facilities`
- [ ] `User support`

**Comment by kmariepat-cityfriends** [comment]
https://www.cem.va.gov/cems/cems.xml
https://www.cem.va.gov/cems/national.xml

**Comment by kmariepat-cityfriends** [comment]
NCA table in CDW:
SQL40.BISL_GIS_SpatialData.[DOEx].[v_FacilityLocator_NCA]

**Comment by omahane** [comment]
> https://www.cem.va.gov/cems/cems.xml 
> https://www.cem.va.gov/cems/national.xml

## The structures are nearly the same:
### State
```
<cem 
fac_id="1001" 
state="ALABAMA" 
statecode="AL" 
cem_name="Alabama State Veterans Memorial Cemetery at Spanish Fort" 
cem_url="https://va.alabama.gov/veterans-memorial-cemetery/" 
funded="Yes" 
address_line1="34904 State Highway 225" 
address_line2="Spanish Fort, AL 36527" 
address_line3="" 
mailing_line1="" 
mailing_line2="" 
mailing_line3="" 
contact1="Tony Ross, Cemetery Director" 
contact2="Joseph S. Buschell, Assistant Cemetery Director" 
phone="251-625-1338" 
fax="251-626-9204" 
email="" 
lat="30.7346233" 
long="-87.8985442" 
stationid="400"/>
```
### National
```
<cem 
station="910" 
cem_name="Fort Richardson National Cemetery" 
state="ALASKA" 
statecode="AK" 
cem_url="https://www.cem.va.gov/cems/nchp/FtRichardson.asp" 
fac_id="265" 
status="Open" 
address_line1="Bldg 58-512 Davis Hwy" 
address_line2="Fort Richardson, AK 99505" 
address_line3="" 
mailing_line1="" 
mailing_line2="" 
mailing_line3="" 
contact1="" 
contact2="" 
phone="907-384-7075" 
fax="907-384-7111" 
email="" 
lat="61.272429100000068" 
long="-149.65825009999998"/>
```

### Comparison of XML (after sorting the elements)
The difference is 
- State has `Funded`
- National has `Open`

<img width="1165" alt="state-national-cemeteries" src="https://user-images.githubusercontent.com/766573/232621818-635d56a8-df6b-46cb-a3b6-ab2973b0e8c4.png">

**Comment by omahane** [comment]
## Facilities API
https://sandbox-api.va.gov/services/va_facilities/v0/facilities/

```
{
	"type": "Feature",
	"geometry": {
		"type": "Point",
		"coordinates": [
			-87.8985442,
			30.7346233
		]
	},
	"properties": {
		"id": "nca_s1001",
		"name": "Alabama State Veterans Memorial Cemetery at Spanish Fort",
		"facility_type": "va_cemetery",
		"classification": "State Cemetery",
		"website": "https://va.alabama.gov/veterans-memorial-cemetery/",
		"time_zone": "America/Chicago",
		"address": {
			"mailing": {},
			"physical": {
				"zip": "36527",
				"city": "Spanish Fort",
				"state": "AL",
				"address_1": "34904 State Highway 225"
			}
		},
		"phone": {
			"fax": "251-626-9204",
			"main": "251-625-1338"
		},
		"hours": {
			"Friday": "Sunrise - Sunset",
			"Monday": "Sunrise - Sunset",
			"Sunday": "Sunrise - Sunset",
			"Tuesday": "Sunrise - Sunset",
			"Saturday": "Sunrise - Sunset",
			"Thursday": "Sunrise - Sunset",
			"Wednesday": "Sunrise - Sunset"
		},
		"operational_hours_special_instructions": null,
		"services": {},
		"satisfaction": {},
		"wait_times": {},
		"mobile": null,
		"active_status": null,
		"operating_status": {
			"code": "NORMAL"
		},
		"detailed_services": null,
		"visn": null
	}
},
```
<img width="646" alt="Screen Shot 2023-04-18 at 8 01 37 AM" src="https://user-images.githubusercontent.com/766573/232786843-8f8bb0e0-bcc2-4a90-815c-fea0678836c1.png">

**Comment by omahane** [comment]
From Adam in Lighthouse:
These are the fields that will have data:
```
  String siteId;
  String fullName;
  String siteType;
  String siteAddress1;
  String siteAddress2;
  String siteCity;
  String siteState;
  String siteZip;
  String mailAddress1;
  String mailAddress2;
  String mailCity;
  String mailState;
  String mailZip;
  String phone;
  String fax;
  String visitationHoursWeekday;
  String visitationHoursWeekend;
  String websiteUrl;
  BigDecimal longitude;
  BigDecimal latitude;
```

**Comment by omahane** [comment]
@davidconlon  
Regarding migrating more of the API data:
### State Cemeteries
We are currently deliberately skipping the state cemeteries in the Facilities API? Should we continue to do so or should they also be migrated? For the record, there are 147 state cemeteries out of the 338 total available in the API.

### Fax numbers
When looking at the NCA data, it appears that fax numbers nearly always have data in them. I don’t see that we bring in fax numbers in any of our other migrations, though. Should we plan to do so for NCA?

**Comment by davidconlon** [comment]
@omahane 
Re: State Cemeteries: Yes. For now we should deliberately skip state cemeteries. This may change in the future but I seriously doubt it will. 

Re: Fax Numbers on VA Cemeteries: Yes. We should migrate the fax numbers. I _think_ that we have deprecated fax numbers from the other facilities (VBA/VHA) as a thing to be used (for the most part) but NCA still uses faxes to my knowledge.

**Comment by omahane** [comment]
@swirtSJW I would like to get your feedback on the tickets I created here:
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13340
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13362

**Comment by omahane** [comment]
I have addressed questions by @swirtSJW .  Moving to PO review.
