### ISSUE TITLE
Design: Provide address in "Where" field for all Events at VA facilities instead of linking to facility's web page

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#13124]
### User story

**AS A** Veteran
**I WANT** all events to have a consistent presentation on the event page of where they are located, including the address
**SO THAT** my cognitive load and number of interactions is reduced.

### Design
Mockups are in [this Sketch file](https://www.sketch.com/s/8ec18b80-a905-47fb-a217-5720450befa1). 

#### Non-VA location

Notice that the "Where" contains a place name (building/floor/room field) stacked on top of a street address, and that this place name has no hyperlink.
- Is this stacked design the design we want in general?
- Is it accessible?
- Is the street address easy to map if opened on a smartphone (i.e., one-tap or require creative copy/paste)?
- How does it look if the Editor left the building/floor/room field empty? 

Non-va Facility event:
Event listing: https://www.va.gov/outreach-and-events/events/
Event detail page: https://www.va.gov/outreach-and-events/events/54775/
CMS: https://prod.cms.va.gov/node/54775/edit

<details>
<summary>(shots)</summary>
 
**Event listing**

<img width="369" alt="image" src="https://user-images.githubusercontent.com/4054752/233749902-c5c30cf9-2639-4e18-94b1-323711adc027.png">

**Event Detail page**
<img width="366" alt="image" src="https://user-images.githubusercontent.com/4054752/233749919-b406a0ed-affc-4617-b1bf-8b37fa836002.png">

**CMS view of Event**
<img width="333" alt="image" src="https://user-images.githubusercontent.com/4054752/233749946-fa191e60-b111-4298-aac1-654c6d77357f.png">

</details>

#### VA location (current state)

Notice that the "Where" contains a VA facility name (building/floor/room field) which is hyperlinked to its webpage stacked on top of the building/floor/room field (no hyperlink).

VA Facility event:
Event listing: https://www.va.gov/loma-linda-health-care/events/
Event detail page: https://www.va.gov/loma-linda-health-care/events/54700/
CMS: https://prod.cms.va.gov/node/54700/edit

<details>
<summary>(shots)</summary>

**Event listing**
<img width="356" alt="image" src="https://user-images.githubusercontent.com/4054752/233750004-b05ba9a7-65c7-4d38-b02d-046844df4445.png">

**Event Detail page**
<img width="363" alt="image" src="https://user-images.githubusercontent.com/4054752/233750030-9243d22c-9621-4044-87f7-b4c9989ae273.png">

**CMS view of Event**
<img width="362" alt="image" src="https://user-images.githubusercontent.com/4054752/233750051-ed8e75fe-919d-4f68-b363-8fa6ff7da196.png">

</details>

### Engineering notes / background

Motivation for this move:
- Defect #11937, in which the FE template built broken links when the VA facility hosting an event doesn't have its own web page – e.g. Vet Center CAPs and Outstations
- Cemeteries is in a related situation

**Cemeteries:**
- Do Cemeteries have address data available in Drupal? No. They have lat/long. 
- Related Facilities tickets: 
  - https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10536
  - https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10535

## Acceptance criteria

- [ ] Delivered a UI design that can be implemented for events at both VA and non-VA locations which addresses the following details:
  - [ ] Is the current design with a place name (building/floor/room field) stacked on top of a street address what we want, or should there be separate fields?
  - [ ] What is best for accessibility?
  - [ ] How should the street address behave if tapped on a smartphone?
  - [ ] How should it look if the Editor left the building/floor/room field empty? 
  - [ ] How should the appearance change (if at all) between VA and non-VA locations?
  - [ ] Should VA locations still hyperlink to the facility's dedicated page, if it exists? (If so, provide both versions)
- [ ] Scheduled meeting to review with PM, PO, Accessibility (and others as needed)

**Comment by wesrowe** [comment]
Wes to add:
- screen shot of existing FE (Jill sent)
- Drupal side
- check whether Cemeteries are available as entity references in the VA facility chooser

Design questions:
- Does every event have a "building name" type field? besides just address
- If not, would you just stack all the building name and address together? or would you split them into two fields? how does a11y answer that question?

User story: I want a consistent address presentation for all events
Future story: I want all VA facilities to have a link to a detail page
Show street address for all events, including VA Facilities
Include links?

**Comment by wesrowe** [comment]
@thejordanwood, this is revised and ready for your pre-refinement and estimation.

**Comment by jilladams** [comment]
Note from planning: may be helpful to annotate tap behavior in the design.

**Comment by thejordanwood** [comment]
Mockups are in [this Sketch file](https://www.sketch.com/s/6d5ce084-763e-4720-80aa-fc5ee671f0ee). Going to set up a meeting to ask accessibility questions.

**Comment by thejordanwood** [comment]
Cleaned up [the Sketch file](https://www.sketch.com/s/8ec18b80-a905-47fb-a217-5720450befa1). This is now ready to pass on to development.

**Comment by wesrowe** [comment]
Thanks Jordan! I used it to update the implementation ticket.
