### ISSUE TITLE
Migrate "phase 2" react components targed for deprecation: es-lint & other

### ISSUE THREAD

**Issue by jtmst** [department-of-veterans-affairs/va.gov-cms#13135]
### User story
AS A PO for PW
I WANT my products to move from "phase 2" deprecated react components to design system web components
SO THAT VA can stay on the path to upgrade the DS to USWDS 3.0

### Engineering notes / background
- Original Audit Conducted here: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13098
- Original slack convo here: https://dsva.slack.com/archives/C03R5SBELQM/p1680033521847529
- Migration docs here:  https://design.va.gov/about/developers/using-web-components#how-to-migrate-to-web-components

#### ES-lint

breadcrumbs:
under “es-lint-rule” category,  low complexity
- src/applications/search/components/SearchBreadcrumbs.jsx:
- src/applications/yellow-ribbon/containers/YellowRibbonApp/index.jsx:

dropdown-panel:
(This is in the slack post list but not included in the migration documentation, complexity unknown)
- src/platform/site-wide/user-nav/components/SearchMenu.jsx:
- src/platform/site-wide/user-nav/tests/components/PersonalizationDropDownPanel.unit.spec.jsx

Modal:
under “es-lint-rule” category,  low complexity
- src/applications/find-forms/containers/SearchResults.jsx:
- src/applications/find-forms/widgets/createFindVaFormsPDFDownloadHelper/DownloadPDFModal.jsx:
- src/applications/static-pages/dependency-verification/components/dependencyVerificationModal.jsx:

Pagination:
under “es-lint-rule” category,  low complexity

- src/applications/find-forms/containers/SearchResults.jsx:
- src/applications/resources-and-support/components/ResourcesAndSupportSearchApp.jsx:
- src/applications/search/containers/SearchApp.jsx:
- src/applications/yellow-ribbon/containers/SearchResults/index.jsx:

Telephone: 
under “es-lint-rule” category,  medium complexity

- src/applications/static-pages/cta-widget/components/messages/DeactivatedMHVIds.jsx:
- src/applications/static-pages/cta-widget/components/messages/MultipleIds.jsx:
- src/applications/static-pages/cta-widget/components/messages/NeedsSSNResolution.jsx:
- src/applications/static-pages/cta-widget/components/messages/NeedsVAPatient.jsx:
- src/applications/static-pages/cta-widget/components/messages/RegisterFailed.jsx:
- src/applications/static-pages/cta-widget/components/messages/UpgradeFailed.jsx:
- src/applications/static-pages/cta-widget/components/messages/mvi/NotFound.jsx:
- src/applications/static-pages/health-care-manage-benefits/refill-track-prescriptions-page/components/AuthContent/index.js:
- src/applications/static-pages/health-care-manage-benefits/refill-track-prescriptions-page/components/UnauthContent/index.js:
- src/platform/site-wide/va-footer/components/CrisisPanel.jsx:
- src/applications/static-pages/health-care-manage-benefits/view-test-and-lab-results-page/components/AuthContent/index.js:

### Quality / testing notes
These changes will affect over 60 individual components. Care should be taken to spot check component functionality especially where unit test coverage is not sufficient 

## Acceptance criteria
- [ ] All listed components are cut over to new web components
- [ ] There are no regressions for any component functionality
- [ ] Unit tests are updated where necessary and all tests pass

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [X] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`

**Comment by jilladams** [comment]
5 assumes the es-lint style update works as advertised. If that doesn't prove to be true, need to wave a flag and effort will certainly increase.

**Comment by jtmst** [comment]
Adjustment needs to be made for failing cypress test.  Likely to merge tomorrow

**Comment by jtmst** [comment]
In prod, awaiting PO review

**Comment by jilladams** [comment]
Discussed with Wes, closing.
