### ISSUE TITLE
Draft content spec for VBA Facility content type

### ISSUE THREAD

**Issue by davidmpickett** [department-of-veterans-affairs/va.gov-cms#13130]
## Description

**AS A** Drupal engineer, 
**I WANT** a technical design document
**SO THAT** there is nothing ambiguous about the implementation requirements.

**AS A** PO, CMS team member or stakeholder
**I WANT** to see a detailed content spec
**SO THAT** I can review the design before implementation

**Example artifact**
- [Drupal Content Spec Template](https://docs.google.com/spreadsheets/d/1oD8GMll7k-9E2AYCjUIl_Eu48wKfXyurfnW63b2G0_k/edit?usp=sharing)
- [Drupal Content Spec TEMPLATE.xlsx](https://github.com/department-of-veterans-affairs/va.gov-cms/files/11113423/Drupal.Content.Spec.TEMPLATE.xlsx)

## Supporting documents
- [VBA Design](https://www.sketch.com/s/891d33ae-152d-471c-ab5d-9aedf89cf6ff)

## Artifact
[Drupal Content Spec VBA Facility content type](https://docs.google.com/spreadsheets/d/135zZdRAdUMgnidB2HMHuJE85upDucejilmTTOyQpPVQ/edit#gid=0)

## Acceptance Criteria
- [x] Draft document of content design
- [x] Review document with Product and Drupal engineering
- [x] Send to CMS team for review (or wait until all related specs are ready and then schedule a review meeting)

**Comment by swirtSJW** [comment]
@kmariepat-cityfriends With the exception of the parent office, it seems like we should be definitely surfacing the others  ^^   Parent office I am not sure if that means anything to Veterans.  We'd have to consult with RO personell to see if they think it is important.

**Comment by kmariepat-cityfriends** [comment]
@swirtSJW @omahane thank you for the guidance and info. I have a meeting with RO managers next week so I will ask there, after confirming with Dave C. that I can, FWIW I think this makes sense too. Also I will let @thejordanwood know to add representation of those fields in her design

**Comment by davidmpickett** [comment]
> @kmariepat-cityfriends With the exception of the parent office, it seems like we should be definitely surfacing the others ^^ Parent office I am not sure if that means anything to Veterans. We'd have to consult with RO personell to see if they think it is important.

This already came up in both rounds of research. The Parent Office field is relevant for Satellite Offices because [Veterans have an understanding that the Regional Offices tend to be one stop shops](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/regional-offices/research/2022-8-veteran-facing/research-findings.md#details-of-findings). In speaking to [Public Contact Staff](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/regional-offices/research/2022-9-public-contact/research-findings.md#6---public-contact-staff-provide-a-consistent-set-of-services-at-multiple-vba-facility-types), we also learned that having that relationship is important for issue escalation. 

> I work closely with the public contact step in Honolulu and we're on email daily. We meet weekly, sometimes multiple times weekly. So, no, there's there's not a disconnect between this satellite office and the regional office... I would make sure that they understand that I represent the Honolulu Regional Office, and that, any issues that require any type of escalation they know contact the Honolulu Regional Office Public Contact. - Saipan

In https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13510 there is conversation around exactly where we would show the Parent Regional Office on Satellite Office pages. Possibly at top of "Other nearby VA locations" or might need a separate header but still be in that vicinity

**Comment by omahane** [comment]
@davidmpickett @swirtSJW "Other nearby VA Locations" is one section of the VBA Facility design.
I am unsure how the other facilities will be determined, though. In particular, I'm trying to figure out whether there's some data on the facility itself that will determine this list.

A relevant example is here
https://www.va.gov/charlotte-vet-center/locations/

I know the locations_listing and vet_center_locations_listing have field_office that relates the listing to the facility. What's not clear to me is how the "Other nearby Vet Centers" works. Given that this is similar to the VBA design, I am unclear by what means these will be connected.

**Comment by omahane** [comment]
@davidmpickett The artifact has been updated to the extent I can do so.

**Comment by omahane** [comment]
@swirtSJW Could you take a look at this? I'd like your feedback/input.

**Comment by swirtSJW** [comment]
I put this in [Slack](https://civicactions.slack.com/archives/C04FTR5J9E0/p1683740266859919?thread_ts=1683675315.365499&cid=C04FTR5J9E0) but adding here for better tracking:

The only issue I am seeing so far and clarifying are the Required: yes?
Whenever something is coming from a migration/external source we NEVER want to make it required.  Let's say a field from the source was required but data was empty in the external source, the migration would create a node, but an editor would never be able to save it because of a required field they can not control.

Now when we flip it so that CMS is the source of truth for VBA, then we would have unlock those fields AND make them required

**Comment by swirtSJW** [comment]
The only other thing that caught my eye this one, but the field already exists so not a big issue and too late-ish.  
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5752113/344ec166-19e7-45c4-9c36-70bffccdd949)

I don't think there was a reason to make a VBA specific field.  This could have been the more generic field.

**Comment by omahane** [comment]
@davidmpickett This is ready for your review/sign-off.

**Comment by swirtSJW** [comment]
One note on the doc still has a question about facility status.   I created this issue to help refine that particular piece https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14546
