### ISSUE TITLE
The wrong alert is showing in the entity browser widget for benefits detail pages. 

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#1313]
**Describe the defect**
In some cases (for some users?) the wrong alert shows in the Entity browser widget (and possibly in the node view?)

[Here's a slack thread with some examples and timestamps, if that's relevant.](https://app.slack.com/client/T03FECE8V/CDHBKAL9W/thread/CT4GZBM8F-1585062972.359000)

**To Reproduce**
We need to figure out how to reproduce

**Expected behavior**

**Screenshots**

![Slack___cms-support___Digital_Service___VA](https://user-images.githubusercontent.com/643678/77454817-6ea22780-6dcf-11ea-8357-54eb3fa0a647.jpg)

**Comment by ElijahLynn** [comment]
Some notes discussed from planning now:
* Not reproducible yet
* Happened to 2 users, find out what times they happened and see if they correlate to code deployment - see slack thread
* Using core entity browser, are we using any patches?

**Comment by oksana-c** [comment]
Troubleshooting tips discussed:

* check entity_browser contrib for related bugs in issue queue
* review for applied patches
* potential for Drupal cache issue

**Comment by oksana-c** [comment]
good news: I'm able to reproduce this locally!

Steps to reproduce:
- login as user w/ roles: Content publisher; Content admin)
- visit /node/912 , note current alert title
- edit node
- remove currently selected alert reference
- add new alert reference
- save
- note correct alert title on node view page
- click on edit again - note the old alert reference is displayed
