### ISSUE TITLE
Draft content spec for updated VBA fieldset of VA Service taxonomy

### ISSUE THREAD

**Issue by davidmpickett** [department-of-veterans-affairs/va.gov-cms#13131]
## Description

**AS A** Drupal engineer, 
**I WANT** a technical design document
**SO THAT** there is nothing ambiguous about the implementation requirements.

**AS A** PO, CMS team member or stakeholder
**I WANT** to see a detailed content spec
**SO THAT** I can review the design before implementation

**Example artifact**
- [Drupal Content Spec Template](https://docs.google.com/spreadsheets/d/1oD8GMll7k-9E2AYCjUIl_Eu48wKfXyurfnW63b2G0_k/edit?usp=sharing)
- [Drupal Content Spec TEMPLATE.xlsx](https://github.com/department-of-veterans-affairs/va.gov-cms/files/11113423/Drupal.Content.Spec.TEMPLATE.xlsx)

## Artifact
[Drupal Content Spec VBA - VA Services Taxonomy](https://docs.google.com/spreadsheets/d/168DaIdA7fIJsknMbYGIsipYYYl5Ht_864o8O89npE8U/edit#gid=1094978439)

## Acceptance Criteria
- [x] Draft document of content design
- [x] Review document with Product and Drupal engineering
- [ ] Send to CMS team for review (or wait until all related specs are ready and then schedule a review meeting)

**Comment by davidmpickett** [comment]
**How to Prepare (blobby)** 

- This is essentially the "What to bring to your appointment" field from Jordan's design. (That's probably a better name for the field too!)
- Should be Limited Rich Text format to prevent headers, but allow bullet points

![Screen Shot 2023-05-01 at 3 32 36 PM](https://user-images.githubusercontent.com/51967950/235526053-fb4bc97e-3e21-48b2-a16b-b04a5796d2d2.png)

**Online self-service**

- I think this could just be a link field
- Would just be referencing relevant online tool(s) e.g. https://www.va.gov/pension/application/527EZ/introduction
- Not sure if we can assume this will always be referencing a Drupal entity

**Comment by omahane** [comment]
@davidmpickett I've been working on this, but I'm unsure if I'm supposed to be creating this spec as though we don't have any of these fields in our current VA Services taxonomy or whether I should describe those fields that already exist and add new ones. For now, I'm doing the latter: describing first and prescribing new.

**Comment by omahane** [comment]
@davidmpickett The other part that's a little unclear is whether I should be suggesting changes to fields that already exist or not (such as help or whether they are required) and how to note these if I do. 

I also have some cells with questions or just question marks because I'm not sure what should be in them.

**Comment by omahane** [comment]
@davidmpickett @swirtSJW @kmariepat-cityfriends The artifact for this is ready for your review. 
https://docs.google.com/spreadsheets/d/168DaIdA7fIJsknMbYGIsipYYYl5Ht_864o8O89npE8U/edit#gid=1094978439

**Comment by jilladams** [comment]
Moved to PO Review for @kmariepat-cityfriends workflow visibility.

**Comment by kmariepat-cityfriends** [comment]
@swirtSJW @davidmpickett  let me know when you've reviewed this work and if you have any proposed changes

**Comment by swirtSJW** [comment]
I looked over https://docs.google.com/spreadsheets/d/168DaIdA7fIJsknMbYGIsipYYYl5Ht_864o8O89npE8U/edit#gid=1094978439 and I see no issues.

**Comment by kmariepat-cityfriends** [comment]
Closing this, will go to review with CMS in Take VBA Content specs to CMS collab cycle #13178
