### ISSUE TITLE
508-defect-4 [COGNITION]: Breadcrumbs should match `h1`

### ISSUE THREAD

**Issue by joshkimux** [department-of-veterans-affairs/va.gov-cms#13147]
## Details

We recently updated a couple of the search page's `h1`s from "Search results" to "Search" in order to communicate to screen reader users that they can both search and browse search results. However, we did not update the breadcrumbs to match those changes which may be confusing or inconsistent to users.

## Acceptance Criteria

- [x] department-of-veterans-affairs/va.gov-team#29733 is closed 
- [x] Breadcrumbs for VA.gov Search matches respective `h1`
- [ ] Breadcrumbs for Resources and support matches respective `h1`

### Before
<img width="784" alt="Screen Shot 2021-09-08 at 2 28 44 PM" src="https://user-images.githubusercontent.com/14154792/132566179-1024cb97-0f83-4140-af98-8da7338ab976.png">

<img width="800" alt="Screen Shot 2021-09-08 at 2 38 23 PM" src="https://user-images.githubusercontent.com/14154792/132566229-88452e9e-1de2-430a-8116-ccee3a3d1799.png">

### After
<img width="787" alt="Screen Shot 2021-09-08 at 2 28 37 PM" src="https://user-images.githubusercontent.com/14154792/132566193-a383e7f3-818d-4707-95f6-b1bbc5e136f0.png">

<img width="791" alt="Screen Shot 2021-09-08 at 2 30 42 PM" src="https://user-images.githubusercontent.com/14154792/132566157-9e5635b4-864e-4898-b043-b0b3bd3c08e0.png">

**Comment by randimays** [comment]
End-of-sprint update: this will deploy to production this afternoon and we can validate and close.

**Comment by jilladams** [comment]
Prod deploy delayed - verified in Staging, though!

![Screenshot 2023-08-15 at 5 59 35 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/85581471/b2ffb16f-4c0a-4ef8-aa86-2e8d91c4542a)

**Comment by randimays** [comment]
Successfully validated in production. Closing!

<img width="1128" alt="Screenshot 2023-08-16 at 3 51 54 PM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/19175324/115ec980-272b-44a4-bdbf-c57b2630cdc7">
