### ISSUE TITLE
Add workflow functionality to VA Benefit Taxonomy

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#13141]
### User story

**AS AN** Editor
**I WANT** VA Benefit taxonomy terms to have workflow rules in place
**SO THAT** content life cycle is easier to manage.

### Engineering notes / background

**Not launch blocking for merging the Taxonomy to CMS.**

Facilities is working on adding workflows to taxonomies in [this ticket](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13079). ~~Our work will likely precede theirs.~~ _Update: Facilities went first_

Can't leverage the existing node workflow, but can create a new workflow that mimics it, for this type of entity (taxonomy terms).

## Acceptance criteria

- [x] As a Content Editor 
  - [x] Benefit taxonomy terms follow existing MVP node workflow (draft, needs review, published, archived)
  - [x] Benefit terms require me to enter a revision log message with each save
- [x] I expect as a Content Admin or Drupal Admin to be able to use these workflow steps (Draft, Published, etc) and see Revisions.
- [x] [Any changes required to permissions for Official Name and API Name fields]

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [X] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`

**Comment by davidmpickett** [comment]
Retitling this to kill the BCM acronym. The benefit content model includes multiple Drupal entities. The specific entity this ticket will be addressing in the VA Benefit Taxonomy

**Comment by wesrowe** [comment]
Per refinement today, PW will most likely be the first to implement workflow on a taxonomy. 

We also confirmed that this is _**not**_ launch blocking for the MVP. Rationale: the MVP won't lead to content being actually published until there is a FE actually presenting content to Veterans. So this workflow issue is a "launch-blocker" for release of a FE product built upon the content model.

**Comment by wesrowe** [comment]
Note that it sounds like Facilities may beat PW to this after all: [Swirt's comment](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13079#issuecomment-1509145580).

**Comment by chri5tia** [comment]
Workflow functionality is available now and since revision logs are now _required_, I went ahead and added this. It should be tested as part of the PR review.

**Comment by chri5tia** [comment]
@swirtSJW I've added editorial workflow to VA Benefits Taxonomy but cannot figure out how to put the revision log message _inside_  an editorial workflow fieldset like it is on VA Services and other places:

![Screenshot 2023-04-21 at 1 23 18 PM](https://user-images.githubusercontent.com/22764938/233728198-6463d5bf-229d-494f-a2fc-ce856e06f3db.png)

![Screenshot 2023-04-21 at 1 23 29 PM](https://user-images.githubusercontent.com/22764938/233728222-2c69cdbf-91e1-4e6c-a2e7-0b5a4472a213.png)

Can you take a look and see if there is something I missed?

**Comment by wesrowe** [comment]
I don't think this is really a sprint goal. Removing pin.

**Comment by jilladams** [comment]
Just realized this wasn't assigned or in sprint, but updating that since this got demoed and will merge with Phase 4. Closing, and the code will ship along with #13075. @chri5tia feel free to reopen if this doesn't smell right.
