### ISSUE TITLE
Resolve lovell tricare detail page url issues

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#13156]
## Description
Making certain changes early in the lovell lifecyle has resulted in some aliases being created incorrectly.  Moreover resaving or event editing the alias does not stay.  A re-save brings the bad alias back.
It happens because there are pairs of nodes that block each other from having the alias they are supposed to have.

The solution is to delete they aliases from the [alias UI](https://prod.cms.va.gov/admin/config/search/path) for the one that appears broken AND the one that is blocking it.  Then re-save both nodes.  Then the alias gets built correctly.

- [x] https://prod.cms.va.gov/lovell-federal-health-care-tricare/about-us/leadership-0
    - [x] https://prod.cms.va.gov/lovell-federal-health-care-va/about-us/leadership
- [x] https://prod.cms.va.gov/lovell-federal-health-care-tricare/programs/gynecology-clinic-0
     - [x] https://prod.cms.va.gov/lovell-federal-health-care-va/programs/gynecology-clinic
- [x] https://prod.cms.va.gov/lovell-federal-health-care-tricare/programs/internal-medicine-0
    - [x] https://prod.cms.va.gov/lovell-federal-health-care-va/programs/internal-medicine
- [x] /lovell-federal-health-care-tricare/programs/ophthalmology-0
    - [x] /lovell-federal-health-care-va/programs/ophthalmology
- [x] https://prod.cms.va.gov/lovell-federal-health-care-tricare/programs/physical-medicine-and-rehabilitation-0
    - [x] https://prod.cms.va.gov/lovell-federal-health-care-va/programs/physical-medicine-and-rehabilitation
- [x] https://prod.cms.va.gov/lovell-federal-health-care-tricare/programs/veterans-justice-outreach-0
    - [x] https://prod.cms.va.gov/lovell-federal-health-care-va/programs/veterans-justice-outreach
- [x] /lovell-federal-health-care-tricare/health-services/returning-service-member-care-0
   - [x] /lovell-federal-health-care-va/health-services/returning-service-member-care
- [x] /lovell-federal-health-care-tricare/programs/intimate-partner-violence-support-0
   - [x] /lovell-federal-health-care-va/programs/intimate-partner-violence-support
- [x] /lovell-federal-health-care-tricare/programs/chaplain-services-0
   - [x] /lovell-federal-health-care-va/programs/chaplain-services

## Steps to reproduce
1. Create a Lovell tricare detail page.  It will have the proper url on save
2. Create a Lovell VA version of the previous detail page, it will have the proper url on save.
3. Edit and save the Lovell Tricare page, its old url is gone and the new one now has a -0 at the end.
4. Fixing the alias by hand in the alias interface will only temporarily fix the alias, then next time someone saves the tricare node, it will re-appear.

## Acceptance Criteria
- [ ] Saving any of the nodes identified above, does not cause a -0 to return.
- [x] There are no -0 aliases in the lovell systems.
   - [x] I went through all 6 pages of lovell VA aliases ![image.png](https://images.zenhubusercontent.com/5dcda45425f6cc0001763cb5/288d7688-b44e-423f-bcaa-4ccd47361f39)
  - [x] I went through all 5 pages of tricare aliases.

**Comment by swirtSJW** [comment]
@kmariepat-cityfriends I reccomend adding this one to the spint if we have capacity.  It solves a lovell problem that would be good to get right.

**Comment by kmariepat-cityfriends** [comment]
@swirtSJW I see this is a 1 pointer but from a burndown perspective there is still a lot yet to be picked up from the sprint backlog. I don't want to bring this in at this time. I'll check in on things thursday

**Comment by swirtSJW** [comment]
The problem is on retrieving what the url ought to be.  For detail pages, it uses the menu for the first slug, and the menu is Federal VA.... so it thinks this page already exists due to the VA version of the page so it increments the -0   but then we alter the first slug.  So really it is really a case of mistaken identity.
Image for the predicted url for  a tricare page.
![image](https://user-images.githubusercontent.com/5752113/231026967-01eea724-f560-4873-8729-70b6bb906d8e.png)

**Comment by swirtSJW** [comment]
This PR fixes the issue.   After it is merged, we may have to re-save any of the TRICARE detail pages that have had their -0 re-emerge.

**Comment by jilladams** [comment]
@kmariepat-cityfriends closing for sprint reporting / boundary purposes. Please feel free to reopen if you find any issues with sign off.
