### ISSUE TITLE
Hide health services on FE with no "Type of care" selected 

### ISSUE THREAD

**Issue by ryguyk** [department-of-veterans-affairs/va.gov-cms#13164]
## Description
See [this Slack thread](https://dsva.slack.com/archives/C0FQSS30V/p1680634927292839).

The template `src/site/includes/health_services_listing_services.liquid` filters services by "Type of care". Currently, it seems, if a service does not have this field populated, the service will show under all sections:

![image](https://user-images.githubusercontent.com/6863534/229914992-b05fb9b1-3513-4726-a31a-4717aa52e76e.png)

We should explore whether there might be a better approach. Some possibilities:
- Show it under none.
- Show it under a default.
- Make the field required (Drupal).

## Acceptance Criteria
- [ ] I expect that the service does not appear under any section on the front end when no `type of care` is selected 

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [ ] `Public Websites`
- [x] `Facilities`
- [ ] `User support`

**Comment by davidmpickett** [comment]
@ryguyk Do you know if this is true just for VAMCs, or is it also happening on Vet Centers?

**Comment by kmariepat-cityfriends** [comment]
Notes from refinement:
- this may be a problem with Vet Centers, need to be explored 
- validation on CMS side, to check on the service taxonomy it has to have a type of care IF its slated for VAMCs (maybe 3 pt)
