### ISSUE TITLE
Take VBA Content specs to CMS collab cycle

### ISSUE THREAD

**Issue by davidmpickett** [department-of-veterans-affairs/va.gov-cms#13178]
Once all 5 specs have been drafted, reviewed internally and updated with any feedback, then we should schedule another meeting with the CMS collab cycle
Collab cycle ticket https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10241

- [x] I expect all 5 content specs are "trued up"
- [x] I expect all content spec are put into a single spreadsheet with multiple tabs
- [x] I expect that this is exported from Google Docs to excel format for those on VA network
[VBA Drupal Content Spec (ALL) (1).xlsx](https://github.com/department-of-veterans-affairs/va.gov-cms/files/11544361/VBA.Drupal.Content.Spec.ALL.1.xlsx)

- [x] I expect questions that need CMS input are identified and documented to be presented in the collab cycle meeting 
- [x] I expect a CMS Collab Cycle sync is scheduled or request sent

**Comment by davidmpickett** [comment]
- [VBA Service Region](https://docs.google.com/spreadsheets/d/1Q60iXh_fclHuiaSG5XW1I9b42nTKQ1VHG21jDmm7lnw/edit#gid=1459034511)
- [VBA Facility Service](https://docs.google.com/spreadsheets/d/1X4lhbJilVJf8sCScyKUvKohEl2SZJtt2ERXRhkPWfNI/edit#gid=0)
- [Service Location](https://docs.google.com/spreadsheets/d/1yk3LQQCLspztbXN0E3Jtj2cUcp0LAwJpeYIuysvIPeQ/edit#gid=1459034511)
- [Drupal Content Spec](https://docs.google.com/spreadsheets/d/168DaIdA7fIJsknMbYGIsipYYYl5Ht_864o8O89npE8U/edit#gid=0)

**Comment by omahane** [comment]
@davidmpickett I'm not sure what "trued up" means in the ACs. Right now, I'm trying get the look of the same so that the ones I worked on, for instance, look more like yours in terms of mirroring the form display. Otherwise...🤷‍♂️

**Comment by omahane** [comment]
# Question for CMS Collab Cycle

## VBA Service Region
- Primary VBA Facility
  - Should the Field/Form Widget be an Autocomplete?
- VBA Facilities in this region
  - Should the Field/Form Widget be an Autocomplete?
  - Does the Primary VBA Facility also need to be on this list?
  
## VBA Facility Service
- Title
  - Is it translatable?
- Facility
  - Should we allow editors to change this field after save/publish?
- Service name
  - Should we allow editors to change this field after save/publish?
- VBA service description
  - Should this field have a character limit of 200?
  - Do we actually want this field?

## VBA Facility
- GovDelivery
  - Does VBA use GovDelivery?
- Local social media
  - Do facilities (or regions) have their own social media accounts?
- Top Tasks
  - Can VERA or Ask VA accept query parameters, allowing us to send the type of facility with the link?
- Other Nearby VA Locations
  - Should this be a field on the facility or by using a locations list? Or should it be handled as a radius-based programatic query? If so, should editors be able to add a desired radius setting?
- Operating status
  - Is this translatable?
  - Will this include supplemental status or will we be making supplemental status the actual operational status?
- Operating status - more info
  - Is this translatable?
  - What will go here?  (See question above)
- Page introduction
  - Is this translatable?
- Facility photo
  - Is this translatable?
- Classification
  - Is this translatable?
- Hours
  - The design shows multiple time ranges per day for lunch break, sleep study clinic. And timezone. Should it?
- Location services
  - Is this translatable?
- Services
  - Is this translatable?

## Service Location
- Service locations help text
  - Should the field type be "HTML element + Markup"?
- Service Delivery Method(s)
  - Should the field type be "List (text)"?
  - Should the cardinality be 1 or unlimited?
  - Is this the right place to gather this information? What's the change management plan for all the existing Service Locations on VAMCs?
- Address
  - Is this translatable?
- Appointments
  - What is this field for: New paragraph type to capture all scheduling information?
  - How much do we want this to solve for all products?
- Other phone numbers
  - Is this translatable?
- Email contacts
  - Is this translatable?

# VA Services taxonomy
- Type of care
  - What are some examples of this?
- What to bring to your appointment
  - Should this be Rich Text Limited, or is there a more limited we would want to create and use (ask Laura)?

**Comment by omahane** [comment]
@davidmpickett I'm done with this except for the scheduled/requested meeting. Could you handle that? Or should that be @kmariepat-cityfriends ?

**Comment by kmariepat-cityfriends** [comment]
@omahane I will reach out on the CMS collab cycle ticket to say we are ready for this meeting, i'll suggest the list of people you included above and ultimately the CMS collab cycle team may suggest others. From there, i'll own scheduling the meeting.

**Comment by davidmpickett** [comment]
@omahane Do you have a Google Doc version of the Excel doc attached to this ticket?
