### ISSUE TITLE
Audit Facilities codebase for "phase 2" react components targeted for deprecation

### ISSUE THREAD

**Issue by kmariepat-cityfriends** [department-of-veterans-affairs/va.gov-cms#13179]
### User story

**AS A** PO for Facilities 
**I WANT** my products to move from "phase 2" deprecated react components to design system web components
**SO THAT** VA can stay on the path to upgrade the DS to USWDS 3.0

### Engineering notes / background

1. [Deprecation Slack announcement](https://dsva.slack.com/archives/C03R5SBELQM/p1680033521847529).
    - At this stage, eslint _errors_ will be thrown.
    - Documentation listed in that slack thread: https://design.va.gov/about/developers/using-web-components#how-to-migrate-to-web-components
2. The DST has created a [google sheet](https://docs.google.com/spreadsheets/d/1IKi_kNSQtasTb3hHbcKbhHLv7BCYCmRqsUtaRPcrtG8/edit#gid=933859360) with React component usage broken out by owner, app and component total, created this to provide teams with information on the React components which we have been in the process of deprecating. This list should be verified for Facilities.
3. The Public Websites team has performed the same audit and is working on migrations during Sprint 82. Steps we could mimic: 
    - Audit ticket broke findings into 2 implementation tickets: 1 for es-lint related changes  and 1 for migration script related changes
      - #13135 
      - #13175
    - PW noted that the migration script provided is not a guarantee for easy migration -- sometimes fails, sometimes makes incorrect changes, sometimes succeeds.

**Scope**: React components from the list below that appear within files owned by Facilities: https://github.com/department-of-veterans-affairs/vets-website/blob/b14a0aa539875a7cf23621874db16678379a1595/.github/CODEOWNERS#L79

List of react components being deprecated in Phase 2:

1. System down view
2. Text input
4. Alert Box
5. Checkbox group
6. Expanding group
7. Additional Info
8. Breadcrumbs
9. Dropdown panel
10. Loading indicator
11. Modal
12. OMB Info
13. Pagination
14. Progress button
15. ProgressButton / button pair React component
16. Table
17. Telephone
18. Select
19. Fileinput 

## Acceptance criteria

- [x] Documented in this ticket which react components in the above list exist in Facilities-owned products/files and where they are located (see PW example: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13098#issuecomment-1490830222)
- [x] Assessed complexity/effort for each instance
- [x] Ticket(s) created to replace with web component for logical groupings
- [ ] ~Create Content Team intake ticket to review the findings for any necessary content changes~ (this should be N/A)

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [ ] `Public Websites`
- [X] `Facilities`
- [ ] `User support`

**Comment by ryguyk** [comment]
(This comment is a WIP)
Components in use by Facilities that need to be replaced:
1. `AlertBox`
2. `LoadingIndicator`
3. `Pagination`
