### ISSUE TITLE
Migrate "phase 2" react components targed for deprecation: migration script set

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#13175]
### User story
AS A PO for PW
I WANT my products to move from "phase 2" deprecated react components to design system web components
SO THAT VA can stay on the path to upgrade the DS to USWDS 3.0

### Engineering notes / background
- Original Audit Conducted here: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13098
- Original slack convo here: https://dsva.slack.com/archives/C03R5SBELQM/p1680033521847529
- Migration docs here:  https://design.va.gov/about/developers/using-web-components#how-to-migrate-to-web-components

### Audit results: 
alertBox:
 These should be covered by migration script and will just need to be run against the script and confirmed confirmed (check corresponding test files as well) (low complexity)

- src/applications/resources-and-support/components/ResourcesAndSupportSearchApp.jsx:
- src/applications/static-pages/covid-vaccine-updates-cta/Off.jsx:
- src/applications/static-pages/covid-vaccine-updates-cta/On.jsx:
- src/applications/static-pages/cta-widget/components/CallToActionAlert.jsx:
- src/applications/static-pages/health-care-manage-benefits/components/CernerCallToAction/index.js:

additional-info:
These should be covered by migration script and will just need to be run against the script and confirmed confirmed (check corresponding test files as well) (low complexity)
- src/applications/static-pages/cta-widget/components/messages/DeactivatedMHVIds.jsx:
- src/applications/static-pages/cta-widget/components/messages/MultipleIds.jsx:
- src/applications/static-pages/cta-widget/components/messages/NeedsSSNResolution.jsx:
- src/applications/static-pages/cta-widget/components/messages/RegisterFailed.jsx:
- src/applications/static-pages/cta-widget/components/messages/UpgradeFailed.jsx:
- src/applications/yellow-ribbon/containers/SearchForm/index.jsx:

loading-indicator: 

These should be covered by migration script and will just need to be run against the script and confirmed confirmed (check corresponding test files as well) (low complexity)
- src/applications/resources-and-support/components/ResourcesAndSupportSearchApp.jsx:
- src/applications/search/containers/SearchApp.jsx:
- src/applications/static-pages/covid-vaccine-updates-cta/widget.jsx:
- src/applications/static-pages/cta-widget/index.js:
- src/applications/static-pages/health-care-manage-benefits/components/CernerCallToAction/index.js:
- src/applications/static-pages/health-care-manage-benefits/components/CernerCallToAction/index.unit.spec.js:
- src/applications/static-pages/view-modify-dependent/686-cta/containers/Form686CTA.jsx:
- src/applications/static-pages/view-modify-dependents/view-dependents-cta/containers/ViewDependentsCTA.jsx:
- src/applications/yellow-ribbon/containers/SearchResults/index.jsx:

Select:
These are listed as N/A on the migrate list.  May be a manual process (medium complexity)
- src/applications/discharge-wizard/components/questions/DischargeMonth.jsx:
- src/applications/discharge-wizard/components/questions/DischargeYear.jsx:
- src/applications/find-forms/containers/SearchResults.jsx:

### Quality / testing notes
These changes will affect over 60 individual components. Care should be taken to spot check component functionality especially where unit test coverage is not sufficient 

## Acceptance criteria
- [ ] All listed components are cut over to new web components
- [ ] There are no regressions for any component functionality
- [ ] Unit tests are updated where necessary and all tests pass

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [X] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`

**Comment by jilladams** [comment]
5 assumes the migration script works as advertised. If that doesn't prove to be true, need to wave a flag and effort will certainly increase.

**Comment by jtmst** [comment]
Undergoing QA in review instance and code review.  Potential for this to take a couple days to close

**Comment by jtmst** [comment]
merged, will hit prod tomorrow
