### ISSUE TITLE
Train VBA National Editors on updating Facility Operating Status

### ISSUE THREAD

**Issue by kmariepat-cityfriends** [department-of-veterans-affairs/va.gov-cms#13182]
#### Background 
As a Facilities Product Owner (Dave C), I want to no longer be a single point of failure for updating the operating status for 400+ VBA Facilities.

As a VBA National Editor, I want to be connected to the appropriate resources for completing this task in Drupal.

As a Help Desk team member....

As a VBA facility staff member, I want to know who to contact about updating my Facility's operating status in Facility Locator.

https://prod.cms.va.gov/va-benefit-facilities-vba/how-do-i-update-my-vba-facility-operating-status

work with help desk to create + deliver this training 

#### Acceptance Criteria 
- [x] I expect that Tanekwa.Bournes@va.gov and Kenyonna.Power@va.gov are assigned to the VBA section 
- [x] I expect Kenyonna.Power@va.gov is given access to drupal and publishing rights
- [x] I expect a meeting is set to live walk through the existing [KB article](https://prod.cms.va.gov/va-benefit-facilities-vba/how-do-i-update-my-vba-facility-operating-status) and ask for questions and overall present the article as training

**Comment by davidmpickett** [comment]
I think we will need to address this ticket first -> https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11334

**Comment by davidmpickett** [comment]
Current status of relevant druapl users

- [Tanekwa.Bournes@va.gov](https://prod.cms.va.gov/user/1797)
  - Roles
     - Content creator - Outreach Hub
     - Content publisher
  - Sections
     - VBA 
     - Outreach Hub
- [Kenyonna.Power@va.gov](https://prod.cms.va.gov/user/2967)
   - No roles
   - No sections

**Comment by jilladams** [comment]
@stefaniefgray @TroyA6 FYI that this card is in our sprint, and changing some process re: creating new users, to have Facilities handle onboarding our VBA stakeholders as CMS users. Connect with me / @kmariepat-cityfriends with any concerns / notes, or we can also invite you to the kickoff / training with them.

**Comment by swirtSJW** [comment]
I granted Kenyonna the role of "content publisher" as pert he AC but did want to call out that "content editor" would cover the needs of updating status without the risk of accidentally publishing.   None of the VBA facilities should be published yet.

**Comment by stefaniefgray** [comment]
@jilladams Yes, please invite us to the kickoff training! Thank you

cc: @TroyA6

**Comment by jilladams** [comment]
Ok great - @kmariepat-cityfriends took the scheduling action item, so she'll send that invite to you / Troy. (Or: @swirtSJW if you took that over, FYI.)

**Comment by swirtSJW** [comment]
This communication and onboarding should likely go through this page   https://prod.cms.va.gov/help/va-benefit-facilities-vba  However we have no articles in there about basic editing.   The current KB on VBA status is only about example statuses, it does not address the actual facilities, how to get to them or event how to edit them.  I am searching to see if there are some other generic KBs we can reference.

**Comment by swirtSJW** [comment]
@kmariepat-cityfriends Passing the torch to you for scheduling the training call.   I can either attend and do the call, or CMS Support can (either if fine).

**Comment by kmariepat-cityfriends** [comment]
@swirtSJW I scheduled the call for Tuesday 5/16 11:30 am to 12:30 pm EST

I currently invited you, @stefaniefgray and @TroyA6 will confirm in stand who will deliver the training. From there those not delivering the training will not be required to attend.
