### ISSUE TITLE
Support and monitor EKS rollout

### ISSUE THREAD

**Issue by kmariepat-cityfriends** [department-of-veterans-affairs/va.gov-cms#13180]
This card is to represent the capacity given to supporting the eks-migration

- April 10/11 - /facilities_api/* 
- April 10/11 - /v1/facilities/va 

From @laineymajor:
@Ryan Koch should follow this channel. https://dsva.slack.com/archives/C04M7T1CZAS
I will ping him the morning of migration!

- We keep a zoom room opened all day for the migration. I'll tag him the morning of with the zoom room link.
Any questions, comments, concerns, issues should be communicated with us though the above linked slack channel.
If you scroll up in this channel, you'll see a few examples of how we've been operating.
https://dsva.slack.com/archives/C04M7T1CZAS/p1680786000219139
https://dsva.slack.com/archives/C04M7T1CZAS/p1680789931833519

**Comment by kmariepat-cityfriends** [comment]
@ryguyk I added some details to the card of how they are running things. Let me know if you have any questions or concerns and ill support however I can

**Comment by ryguyk** [comment]
Status: everything appears normal up to this point in time.
