### ISSUE TITLE
Remove va_home_preview_modal feature flag after launch

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#13184]
## Description

When homepage is hard launched, this flipper can be deprecated. 

### User story
> _Describe the audience/user, enhancement or fix, and value / outcome desired._

**AS A(N)** engineer
**I WANT** to reduce technical debt and the number of feature flags in play
**SO THAT** the build system stays optimized.

(This story is speaking for Plat where they care about the fact of Flippers, but I can't speak technically to why.)

### Order of operations
* Remove from vets-website first (to NOT show widget regardless of flipper, and remove flipper references) - via #13955 
* Remove from vets-api after

## Acceptance criteria

- [x] I expect that the `va_home_preview_modal` is no longer present in vets-api code ~~or flipper UI~~ [edit: the flipper will remain in the flipper UI since those no longer get purged automatically. This is a Platform thing that they decided to do to avoid the bug where some flippers were being accidentally deleted.]
- [x] I expect that the homepage modal still does not appear in prod

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [X] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`

**Comment by jilladams** [comment]
2, unless we change scope unless we change scope to handle more tech debt.

**Comment by randimays** [comment]
Marking as complete; changes have been deployed to production and modal does not show up at `/` or `/new-home-page`. As stated above, flipper still appears in the Flipper Admin because the job to clean up unused flippers is temporarily turned off due to bugs.
