### ISSUE TITLE
SPIKE: Explore shifting some Facilities Runbook tasks to Help Desk

### ISSUE THREAD

**Issue by ryguyk** [department-of-veterans-affairs/va.gov-cms#13195]
## Description
As a Facilities Team member, I want the routine processes related to facility changes (opening, closures, name changes, etc.) to be as efficient as possible so that Veterans and beneficiaries receive accurate information as quickly as possible.

As a Help Desk team member, I want to be empowered to complete "support engineering" tasks (e.g. Drupal configuration changes) without always waiting for a Facilities Engineer.

## Acceptance Criteria
- [x] I expect tasks that are listed for an engineer to complete are reviewed to determine which can be moved to the responsibility of another facilities team member or help desk team member with the goal of improving speed to DONE state for these facilities runbooks 
- [x] I expect the proposed approach is signed off by Facilities team members and help desk 
- [x] Runbooks PRs are approved by Facilities engineers and help desk 

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [ ] `Public Websites`
- [x] `Facilities`
- [x] `User support`

**Comment by jilladams** [comment]
The PR here ^^ will satisfy _some_ of this work but not all. That PR makes the requested change for any "CMS Engineer" tasks that _follow_ a URL change request. I didn't adjust any prior to that step. 

I think I can still help review / own the changes and knock this out, but will take a little more team discussion.
