### ISSUE TITLE
Plan to remove italics from rich text editor

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#13201]
## Description
Italics should not be allowed as an option for editors in any rich text editor when we upgrade to Drupal 10 and CKeditor 5. Using italics goes against the the [VA content guidelines](https://design.va.gov/content-style-guide/bold-text):

> Note: Don’t use italics. It doesn’t show up well on a screen, and sometimes it can be harder to read than normal text." It doesn’t show up well on a screen, and sometimes it can be harder to read than normal text.

Because this is currently an option, we can probably assume there is some italics being used within the content already.  What will happen when this is no longer an option?

## Acceptance Criteria
- [x] Determine what will happen to existing italic text when this particular style is removed as an option
- [x] Confirm with PO if the scenario above is acceptable for all users (editors and site visitors) or if an alternate solution needs to be found
- [x] Determine if change management is needed for this update and if so create a separate ticket

**Comment by laflannery** [comment]
Looking at a basic install on simply test me:
- CKEditor 5 italics > CKeditor 5 no italics: strips the tag so all italic text would change to standard text
- CKeditor italics > CKeditor no italics: does not strip the tag. However, I have no removed the button from the toolbar so editors have no UI friendly way to remove italics. They would have to remove this by editing the source code.
- Ckeditor italics > Ckeditor 5 no italics: strips the tag so all italic text would change to standard text

**Comment by laflannery** [comment]
Erika will ask Danielle if this (italics going away without warning) is ok or if there is anything we aren't thinking of

**Comment by EWashb** [comment]
There are no additional concerns. Let's move forward with implementation in the new CKeditor @laflannery @productmike

**Comment by laflannery** [comment]
New ticket created for change management #13959
