### ISSUE TITLE
Adding YouTube Video to News Release Creates Broken Link Alerts

### ISSUE THREAD

**Issue by stefaniefgray** [department-of-veterans-affairs/va.gov-cms#13205]
## Describe the defect
The VA Drupal CMS Help Desk team is tasked with responding to broken link alerts ASAP. 

When broken links are reported, we receive notifications in the #content-broken-links channel _every 30-60 minutes_ until they are resolved. This can be very annoying and distracting from our other work.

It seems that adding a YouTube video to a News Release currently creates a broken link under the "Download Media Asset" section of the News Release content type. 

I do not know how to resolve this or find a workaround that can stop the broken link alerts.

## To Reproduce

1. Go to `/admin/content/media` and use the "Add Media" button to add a YouTube video. 
( **Note:** This is the only way that a YouTube video can be added as a Media Asset for use with News Releases.)
**Sample link:** https://youtu.be/N9XvzKACbfM

2. Be sure to assign the video to the same VAMC section that your News Release is intended for. Click "Save."

3. Confirm that the video you've added is listed on `/admin/content/media`

4. Create a new News Release node ( `/node/add/press_release` )

5. Under the "Media Assets" section, click "Add Media" to add the video to your new News Release. Select the video from the grid of available videos, and click "Save."

6. Save and publish the page. It should look something like: https://www.va.gov/northern-california-health-care/news-releases/va-northern-california-provides-free-support-to-survivors-of-military-sexual-trauma/

7. Find the "Download media assets" section of this page, and click the link listed below. Your computer will download a "Download.html" version of the News Release.

8. However, this is being reported as a broken link by our broken link checker tool. See screenshot below:

## AC / Expected behavior
- [ ] Adding a YouTube video to a News Release should not produce broken link reports.
- [ ] I expect that the YouTube video shows 

## Screenshots
![Screen Shot 2023-04-07 at 5 37 07 PM](https://user-images.githubusercontent.com/9059428/230692378-d9cca56b-8441-41b6-91c2-ae6c2a9f8b0a.png)

 ## Additional context
Here is where broken links are reported after each content release: https://s3-us-gov-west-1.amazonaws.com/vetsgov-website-builds-s3-upload/broken-link-reports/vagovprod-broken-links.json

Original node where this issue was discovered: https://prod.cms.va.gov/northern-california-health-care/news-releases/va-northern-california-provides-free-support-to-survivors-of-military-sexual-trauma/

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Defect")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS workstream (orange) (not needed for bug tickets)
- [ ] CMS-supported product (black)

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [ ] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`

**Comment by stefaniefgray** [comment]
@jilladams Hello! Is this a Sitewide CMS team thing or a Public Websites thing? Thank you!

**Comment by stefaniefgray** [comment]
Testing whether changing "You've" to "You Have" fixes the broken link alert based on how it is being reported as `<a href download>If You&apos;ve Experienced MST, VA Can Help</a>`

Probably won't do much of anything but we'll see after the next content release goes out 🤷‍♀️

**Comment by swirtSJW** [comment]
At first glance, this seems to be a FE issue, though I think we need to consider how "download media asset" should work in the case of a youtube video.  I don't think we can legally or technically provide a youtube download link. We can embed the video or offer a way to click through the video but not a link to download.

It seems really odd to me that this has not come up before, so I am hunting for another example.  I can not believe this is the first time someone tried to put a video on a press release.

**Comment by swirtSJW** [comment]
Randomly poking around I have not been able to find another press release that uses a video.

**Comment by jilladams** [comment]
@kmariepat-cityfriends Confirmed with DaveC via PW sync: News Releases sit with Facilities since they are used by VAMCs almost entirely, FYI

**Comment by stefaniefgray** [comment]
@jilladams @kmariepat-cityfriends Thank you! Is there any way we can find a quick fix in order to stop the broken link alerts every 30 minutes in #content-broken-links? It's very distracting whenever we're trying to stay focused 😭 

@TroyA6  and I have to respond to broken link alerts ASAP (per Dave C) as part of the many notifications we receive daily from various platforms and it can easily add up to 15-20 extra notifications per day every time a content release is completed

It's 10:30 AM here and we already got them at 8:18 AM, 9:02 AM, 9:40 AM, and 10:17 AM

**Comment by jilladams** [comment]
Noting that Kamari has tagged it for consideration in S82.

**Comment by kmariepat-cityfriends** [comment]
Refinement Notes:
- Find in the code base where video is rendered in other places; follow these patterns 
- minor design input required to confirm the FE implementation

**Comment by jilladams** [comment]
Auto closed via PR. Moving back to PO Review, so @stefaniefgray can close the loop / verify.

**Comment by stefaniefgray** [comment]
Issue is resolved -- closing

This team rules 🚀  Thank you for resolving this, @timcosgrove !
