### ISSUE TITLE
Support/monitor Cerner data addition by a Health team

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#13200]
### User story
> _Describe the audience/user, enhancement or fix, and value / outcome desired._

**AS A** PO
**I WANT** PW to monitor the rollout of a data addition to the header in VAgov and injected sites
**SO THAT** we catch any breakage quickly.

### Engineering notes / background
[slack thread](https://dsva.slack.com/archives/C52CL1PKQ/p1680793891321189).

Pull request: https://github.com/department-of-veterans-affairs/vets-website/pull/23881

### Quality / testing notes
Injected header scenarios need to be verified. 

## Acceptance criteria

>Consider
> - Design / Accessibility reviews
> - Collab cycle requirements
> - Device sizes (mobile first)
> - Documentation updates / Change management
< - [Content model documentation](https://prod.cms.va.gov/admin/structure/cm_document)
> - Testing notes

- [ ] Stayed in touch with deploying team, PO Patrick Bateman, eng Mark Dewey
- [ ] Monitored injected sites and VAgov during deployment

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [X] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`

**Comment by jilladams** [comment]
Noting: Josh verified injected header: https://dsva.slack.com/archives/C52CL1PKQ/p1681223328841569?thread_ts=1681167359.649159&cid=C52CL1PKQ

**Comment by jilladams** [comment]
Merged on 4/13/2023, 06:17 AM , deployed today. No drama today that I've heard of on injected sites. 🎉

**Comment by jilladams** [comment]
No issues so far. Closing.
