### ISSUE TITLE
New VAMC Facility: Sterling VA Clinic [Ready to go]

### ISSUE THREAD

**Issue by stefaniefgray** [department-of-veterans-affairs/va.gov-cms#13203]
## Intake
- [x] What triggered this runbook? (Flag in CMS, Help desk ticket, Product team, VHA Digital Media)
Trigger: Jira correspondence with editor

- [x] Link to associated help desk ticket (if applicable)
Help desk ticket: See https://va-gov.atlassian.net/browse/VAHELP-5639 and linked tickets

- [x] Name of submitter (if applicable)
Submitter: Tyler Moore @ VISN 19

- [x] If the submitter is an editor, send them links to any relevant KB articles for the VAMC Facility product.

- [x] Link to facility in production:
Facility link: https://prod.cms.va.gov/cheyenne-health-care/locations/sterling-va-clinic

### New VAMC Facility
Please refer to the Knowledge Base article titled "How do I add a facility to my health care system?" for more information: https://prod.cms.va.gov/help/vamc/about-locations-content-for-vamcs/how-do-i-add-a-facility-to-my-health-care-system

#### CMS help desk steps
- [x] 1. Become aware that the new facility is now on the Facility API (typically, via a Flag, but this may come in as a helpdesk ticket).
- [x] 2. If the editor has followed the steps from the above Knowledge Base article and included which section and VAMC the facility belongs to (i.e. VA Pittsburgh), great! **Proceed to step 3.** If not, please check with the editor or VHA digital media regarding what section and VAMC it belongs to.
- [x] 3. Updates the Section (default is "VAMC facilities", but it should be a VAMC system in a VISN) and VAMC system field accordingly.
- [x] 4. Communicate with editor (cc VHA Digital Media) to give them go-ahead to complete the content, with this [KB article](https://prod.cms.va.gov/help/vamc/about-locations-content-for-vamcs/how-do-i-add-a-facility-to-my-health-care-system). (See sample notification email below)

[@TODO: Update email template]

<details><summary>Email template </summary>

```
Hello! You should now be able to edit the draft page for this facility, located at [LINK TO NEW FACILITY DRAFT PAGE ON PROD]

Important: Please make sure that all relevant steps listed within the “How do I add a facility to my health care system?” Knowledge Base article have been completed: https://prod.cms.va.gov/help/vamc/about-locations-content-for-vamcs/how-do-i-add-a-facility-to-my-health-care-system

Once finished, please save this page (and all related VAMC Facility Health Service pages) in the moderation state “Draft." Please do not save them as “Published.”

Please let us know when your draft content is complete, so that we can wrap up the technical process from our end before publishing the new facility to VA.gov. Thanks!
```
</details>

- [x] 5. Create a [URL change request](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/new?assignees=&template=runbook-facility-url-change.md&title=URL+Change+for%3A+%3Cinsert+facility+name%3E), changing the entry from the old facility URL to the new facility URL. (**Note: The URL change request ticket blocks the completion of this ticket.**)

https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13345

(Redirects are released Wednesday afternoons, so coordinate the following items below and canonical URL change around that timeframe.)

- [ ] 6. When editor has prepared content and let help desk know, reassign this issue to appropriate CMS engineer on Product Support team, for bulk publishing.

#### CMS engineer steps
- [ ] 7. CMS engineer executes the steps of the URL change request ticket from step 5.
- [ ] 8. CMS engineer bulk publishes nodes and facility.
- [ ] 9. CMS engineer edit facility node and remove `New facility` flag and save node.
- [ ] 10. Let help desk know this has been done.

#### CMS engineer steps (the new facility)
- [x] 1. Change the Facility Locator API ID on the new facility to the Facility Locator API ID for the old one.
- [x] 2. Change the section on the new facility to the old one
- [x] 3. Change the VAMC system on the new facility to the old one
- [x] 4. Update the Menu link (Parent link) on the new facility to the old system (unable to delete it)
- [x] 5. Check the box under URL alias to **Generate automatic URL alias**
- [x] 6. Archive the facility with a good log message
- [x] 7. Manually disable the menu link for this item directly in the system menu

#### CMS engineer steps (the original facility)
- [x] 8. Change the Facility Locator API ID on the old facility to the Facility Locator API ID for new one
- [x] 9. Change the section on the old facility to the new one
- [x] 10. Change the VAMC system on the old facility to the new one
- [x] 11. Update the Menu link (Parent link) on the old facility to the new system
- [x] 12. Check the box under URL alias to **Generate automatic URL alias**
- [x] 13. Publish changes with good log message
- [x] 14. Manually move the menu link for this item into alphabetical order in locations section of the menu for its new system

#### CMS engineer steps (bulk edit)
Update related content (VAMC Facility Health Services, VAMC Non-clinical Services, Events, Stories, etc)
- [x] 15. Bulk edit the VAMC Facility Health Services for the original Facility (update the section to the new section)
- [x] 16. Manually edit each VAMC Facility Health Service (updating the VAMC system health service to use the new system)
- [x] 17. Bulk edit the VAMC Facility Health Services to **Update URL alias**
- [x] 18. Bulk edit the VAMC Facility Health services to **Resave content** (now the urls will be correct)

#### CMS engineer (create script to be run against the production DB)

- [x] 19. Update this script to be tested on stage and then run against the production database by a member of the platform team to accomplish the following goals:

- [x] Remove the migrate_map entry for the old facility
- [x] Update the migrate_map entry for the new facility, updating the destid1 from the new nid to the old nid (sql command in drush)

```
// remove old facility migration map
drush sql:query "DELETE FROM migrate_map_va_node_health_care_local_facility WHERE destid1 = '1122"

// update new facility migration map so that it updates the original node
drush sql:query "UPDATE migrate_map_va_node_health_care_local_facility SET destid1 = '1122' WHERE destid1 = '55337'"
```

#### CMS Help desk (wrap up)
- [ ] Notify editor and any other stakeholders.

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [ ] `Public Websites`
- [x] `Facilities`
- [x] `User support`

**Comment by stefaniefgray** [comment]
Waiting on editor to also confirm whether facility homepage + health services are good to go

**Comment by stefaniefgray** [comment]
Checked back in with editor to see if homepage and health services are ready to go

**Comment by stefaniefgray** [comment]
@jilladams @kmariepat-cityfriends @omahane Facility is ready for re-publishing to the live site! 🚀 

All VAMC Facility Health Services should stay archived _**except for**_ Primary Care. **The only health service at this clinic is Primary Care.**

Thanks, team!

**Comment by stefaniefgray** [comment]
@jilladams A redirect _is_ needed and you were right to ask!!

https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13203

**Comment by omahane** [comment]
Turns out that this is more of a duplicate now:
![Screen Shot 2023-04-26 at 8 37 25 AM](https://user-images.githubusercontent.com/766573/234593509-5b9e088a-4967-4673-b3e8-a3256f9ef49f.png)

I'm going to add the steps from the duplicate runbook in case they are relevant.

**Comment by stefaniefgray** [comment]
Waiting for editor to add photo and intro -- asked in https://va-gov.atlassian.net/browse/VAHELP-5639

**Comment by stefaniefgray** [comment]
Redirect confirmed, yay! Page is also published live.

Will follow up with editor via Jira re: photo and homepage intro; otherwise, closing this ticket and keeping Jira ticket open

Thanks, @omahane ! 🚀
