### ISSUE TITLE
VA Benefits Taxonomy: enforce no self references for taxonomy references and final field requirements

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#13206]
### User story
> _Describe the audience/user, enhancement or fix, and value / outcome desired._

**AS A** Content Editor
**I WANT** Drupal to enforce special properties on a few key fields
**SO THAT** I can't accidentally break the model or API.

## Acceptance criteria

- [x] @chri5tia - Enforced that terms can’t be linked to themselves in any taxonomy reference field (Co-considered, Pre-requisite)
- [x] @wesrowe - Confirmed that `required` fields are correct on the three bottom rows of spec (currently set as Yes, [slacked](https://agilesix.slack.com/archives/C03EUQRCHGS/p1681160510146299) for confirmation) -- Answer = No. Not right yet.
- [x] @chri5tia - for any field marked "No --> Yes?" in Column H: make sure they are set to be NOT required

**Comment by chri5tia** [comment]
Link to demo for preview and sign off: https://cms-i7n92wfzswpe358hivrspihf2ntzshzp.ci.cms.va.gov/admin/structure/taxonomy/manage/va_benefits_taxonomy/add

**Comment by wesrowe** [comment]
The no self-reference works as designed. I find the error message a bit vague/confusing and wonder if it would be possible to customize it? Along the lines of, "An entity cannot reference itself."
<img width="439" alt="image" src="https://user-images.githubusercontent.com/4054752/232167035-8bc2ce09-5026-474b-aae1-519ee1d3f7cb.png">


Also, I was able to enter the same co-considered benefit twice. Is that something we can prevent? One idea but maybe not good practice: don't include one that has already been selected. (?)
<img width="735" alt="image" src="https://user-images.githubusercontent.com/4054752/232166991-a8196558-b033-4f08-978e-7f6f517e999a.png">

**Comment by jilladams** [comment]
@chri5tia @wesrowe let's touch on this in the sync tomorrow afternoon to see if we can close it or if it needs work still to close in sprint.

**Comment by jilladams** [comment]
@wesrowe can you help clarify expectations for this sprint based on yesterday's convo with Blake?

**Comment by wesrowe** [comment]
Error messaging is fine for now, ticket can close when ready
