### ISSUE TITLE
CMS Design/strategy/governance: should we allow editing Q&A within parent node context (eg R&S, FAQ)?

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#13202]
### User story
> _Describe the audience/user, enhancement or fix, and value / outcome desired._

**AS A** PO
**I WANT** editing of Q&A nodes to be rational, not have weirdness (as discovered in #12800)
**SO THAT** COPE for Q&As can proceed with minimal governance and change management challenges.

Team recommendation: don't allow in-line editing of Q&As in other contexts.

## Acceptance criteria

- [x] Confirmed intention to remove in-line editing with relevant internal and adjacent stakeholders
  - [x] Steve Wirt
  - [x] Erika W
- [x] Communicated intention to SWContent team – Danielle T and Randi H
- [x] Implementation is ticketed in this epic

**Comment by jilladams** [comment]
Confirmed with DaveC in sync with @wesrowe today:  If inline editing is not working, let's verify with CMS team (Erika), but plan to disable inline editing and always point editors back to the primary content. This is a safer strategy in the world of COPE, making sure that any editor modifying content used in multiple places is aware of all the places it's used and that changes don't get too contextual.

Next steps:
- [ ] Confirm with @EWashb re: high level decision, to disable inline editing for nested nodes.
  - [ ] Remodel this ticket to be scoped to disabling inline editing
  - [ ] Inform content team that we are disabling inline editing and why

FYI @swirtSJW for context.

**Comment by jilladams** [comment]
Closing as no-op. We should _not_ allow inline editing, already disabled to Wes's point, and Erika / other teams are in the loop.
