### ISSUE TITLE
Update text of translation links in footer

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#13217]
## Description
At a recent Design System Council meeting, it was brought to their attention that on a [page like this](https://www.va.gov/health-care/covid-19-vaccine/), there is an on-page language switcher near the top. Also, at the bottom in the footer, there are similar links with the same label text that go to a different place, to pages about resources in different languages. They suggested that we should try to make those links more unique.

## Screenshot
![image](https://user-images.githubusercontent.com/106678594/230961641-5fde40a7-436c-4b80-861b-29cf5e900d0f.png)

## Acceptance Criteria

- [ ] Create unique link text for Español footer link (different from language switcher at the top of the page)
- [ ] Create unique link text for Tagalog footer link (different from language switcher at the top of the page)

**Comment by FranECross** [comment]
@FranECross Check with Randi Hecht in CAIA on whether or not we should pursue this.

**Comment by FranECross** [comment]
@RLHecht Is the work in this ticket something our team should pursue? Thanks in advance for your review and determination!

**Comment by jilladams** [comment]
Controversially, I am going to close this. It's an agine ticket, PW no longer owns the footer, and I do not expect the DST to prioritize this. We can always reopen later.
