### ISSUE TITLE
Archived services should not result in node link report notices on system pages

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#13214]
## Describe the defect
When a system health service is archived, the result is a notification from the node_link_report that there is a broken link
![image](https://user-images.githubusercontent.com/5752113/230949884-5e21ee59-5431-4b18-8bf2-e659d12727f7.png)

The system services list is currently not filtering based on state

It should only: 

- show published and draft (not archived)
- draft ideally should be pink background to show it is in draft
- this list should be alphasorted.
- 
![image](https://user-images.githubusercontent.com/5752113/230950651-09245f4b-564b-461c-94aa-86656cd3f231.png)

## To Reproduce
1. Go to https://prod.cms.va.gov/lovell-federal-health-care-tricare
2. See alert at the top about links to unpublished content found. 
3. Scroll down and see links to unpublished system services.

## AC / Expected behavior
- [ ] ~I expect to only see links to draft and published system health services and NOT archived services~
- [x] I expect draft pages to reveal by color(pink) and text that they are in draft
- [x] I expect the list of health services to be alpha sorted for ease of reading.

## changes
This field_clinical_health_services field is using Corresponding Entity Reference, the use and effect of which are not clear. Removing it may be key to changing which services are a part of the content of the node (or not). I can't seem to effect the output at present. In any case, it's not entirely clear what will happen on the front end if we do that, so it needs a little discovery.

Instead, this ticket will cover the editor-facing output. I have alphabetized and modified the output slightly, showing both Archived and Draft content in the meantime with clear indications of its moderation state.

**Comment by jilladams** [comment]
Just to ask: this is CMS-wide, so could also get the CMS Team label? Or this is happening specific to Facilities?

**Comment by swirtSJW** [comment]
Details:  This is coming from the field 'field_clinical_health_services'

which is linked not in the edit form but by corresponding entity reference /admin/config/content/cer/local_health_service_to_regions_health_service

We will need to alter the display of the field.

**Comment by swirtSJW** [comment]
Either of these are options 
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5752113/64f8565f-8a93-4e48-86dc-19b3aeffc296)

If we want  unpublished but non-archived system services to show, so that editors are aware if they have something unpublished, we should go with the View filters.

If we want all unpublished system services to not show, then we could go with the "Default"  but that may not remove things that were published and are now archived (it may only affect creation, not removal)

**Comment by omahane** [comment]
@xiongjaneg @mmiddaugh 
I went in a slightly different direction. This `field_clinical_health_services` field is using Corresponding Entity Reference, the use and effect of which are not clear. Removing it may be key to changing which services are a part of the content of the node (or not). I can't seem to effect the output at present. In any case, it's not entirely clear what will happen on the front end if we do that, so it needs a little discovery.

Instead, this ticket will cover the editor-facing output. I have alphabetized and modified the output slightly. After discussing this with @Becapa, it made sense to show both Archived and Draft content in the meantime with clear indications of its moderation state.

# Archived VAMC system services (among the others)
<img width="817" alt="Screenshot 2024-03-05 at 12 55 58 PM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/766573/8aae9ddd-9690-4807-97f1-7deccd6dd07a">

# A Draft VAMC system service (among the others)
<img width="744" alt="Screenshot 2024-03-05 at 12 57 43 PM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/766573/2b8b3dd9-3823-460a-8c19-8fb715cca26e">

**Comment by omahane** [comment]
After some more investigation, @Becapa and I figured out what CER does, which is actually very useful. When you create a VAMC System Health Service, CER updates the VACM System so that this service is now related to the system. That's how the service shows up there at all on the System node:view. Otherwise, it wouldn't. It also means that the field setting has nothing at all to do with what shows on the system node:view, which we suspected.

**Comment by omahane** [comment]
Documentation added here: https://prod.cms.va.gov/admin/structure/types/manage/health_care_region_page/fields/node.health_care_region_page.field_clinical_health_services/document

**Comment by jilladams** [comment]
Verified:
https://prod.cms.va.gov/washington-dc-health-care - contains Draft services associated
https://prod.cms.va.gov/lovell-federal-health-care-tricare - has archived services associated
Now alpha sorted.

![Screenshot 2024-03-08 at 7 01 20 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/85581471/12134c21-d5f5-4e5a-b47a-8d51fffba365)

![Screenshot 2024-03-08 at 7 01 24 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/85581471/be2c8443-aa70-4efb-8935-4e380358e13e)
