### ISSUE TITLE
SPIKE: VAMC Events Calendar Single Source of Truth 

### ISSUE THREAD

**Issue by kmariepat-cityfriends** [department-of-veterans-affairs/va.gov-cms#13213]
#### Business case
Some events that happen at a local location are required or suggested to also publish to the Outreach Events calendar for national visibility. Right now VEO has to manually copy/paste nationally relevant events that happen in a regional/local location. e.g.: PACT Act related events.

Primary goal: Provide the ability to make local level events visible at the national level
Secondary goal: As an editor, I want to publish this event to every calendar I have access to. (Regional visibility)

On Lovell you can publish a page to Lovell VA - Lovell Tricare OR both...the question is, is there a way to do that with events and what is the lift. 

#### User stories

- As a VEO Outreach Events editor, I want to elevate visiblity of a regional / local event to the national level so that Veterans are aware of it.
- As a VEO Outreach Events or local editor, I want a single source of truth for local events that should be visible at the national level. 
 
- As an events publisher, I can specify whether an event publishes to my events calendar OR my events calendar(s) AND the national calendar 

- As an editor of Lovell, how might I say an event is happening at Lovell and I want that event published to Lovell VA AND Lovell TRICARE 

- As an editor of Lovell, how might I say an event is happening at Lovell and I want that event published that only applies to Lovell VA

- As a Veteran who visits the outreach events calendar, when I click an event I will be led to the outreach events calendar 
- As a Veteran, I want to see regional/locally relevant events in the Outreach Events national calendar

This may be a permissions thing...
How might I publish to one or more of the events I have access to
editors should be able to select where they want the events to appear 
Not dealing with workflows, it would be ok to say all VAMC editors will be given access to the outreach events section (using the Lovell model of publish it 1 publish it 2)

looking for a LOE to make these COPE (create once publish everywhere)

#### Acceptance Criteria 
- [x] I expect solutions are explored to implement the ability to publish events to one or more of the events VAMC systems, editors should be able to select where they want the events to appear AND Outreach and events 
 - [x] I do not expect implementation occurs on this card
 - [x] I expect the proposed solutions are as low LOE as possible
 - [x] I expect the proposed solutions are documented on this card 
- [x]  I expect the proposed solutions are reviewed with @kmariepat-cityfriends
- [x] I expect a solution is selected with @davidconlon's input and an epic of cards needed to complete an implementation of this selected solution are is created

**Comment by jilladams** [comment]
@kmariepat-cityfriends Confirmed in PW sync with Wes and DaveC that this should stay with Facilities. The true ask: Make it possible for VAMC editors to publish Events to the main [Outreach Events calendar ](https://www.va.gov/outreach-and-events/events/). (This may be something that the Outreach Events folks later need to moderate, but for now, that's not a problem to solve.)

Re: How it works today, did some poking -- notes for helping with scope, and for whoever picks this up to pre-refine: 

* Right now, Editors can publish an event to a single location, e.g. https://staging.cms.va.gov/node/55143/edit.  "Where should event appear" is currently a select list / single option field. We likely will need to update this field to allow editors to publish to both their own VAMC as well as "Outreach and Events: Outreach Events". so it becomes a multi-select. 
* VAMC editors with just one section permission for their VAMC can see all "where" options. I was able to create a test event on Staging, as Lauren.Bolanos@va.gov (LA VAMC editor / content publisher, https://staging.cms.va.gov/user/3421/edit), and publish it to "Outreach & Events":  https://staging.cms.va.gov/node/55258/edit. (This event will get wiped with the next Prod > Staging mirror.) I don't know if Editors _should_ be able to do this today? If so, then we really just need to deal with multi-select, I think. 
![Screenshot 2023-04-10 at 1 18 11 PM](https://user-images.githubusercontent.com/85581471/230991099-58a192cd-ebef-4d7c-a5a9-b08d371578bb.png)
* Tim Hudak is a good example user who can successfully post events to the [Outreach Events calendar](https://www.va.gov/outreach-and-events/events/). He has the role `Content creator - Outreach Hub.` I believe that role can also post materials to the Outreach Hub, which VAMC editors should _not_ be able to do.

**Comment by kmariepat-cityfriends** [comment]
Next Steps: @swirtSJW to complete writing AC

**Comment by davidconlon** [comment]
Note: I am aware may roll into sprint 83 and reviewed as part of mid-sprint check-in on 82.

**Comment by davidmpickett** [comment]
> * VAMC editors with just one section permission for their VAMC can see all "where" options. I was able to create a test event on Staging, as [Lauren.Bolanos@va.gov](mailto:Lauren.Bolanos@va.gov) (LA VAMC editor / content publisher, https://staging.cms.va.gov/user/3421/edit), and publish it to "Outreach & Events":  https://staging.cms.va.gov/node/55258/edit. (This event will get wiped with the next Prod > Staging mirror.) I don't know if Editors _should_ be able to do this today? If so, then we really just need to deal with multi-select, I think.

Contrasting what @jilladams experienced. I logged into Staging as Katie.Yearley@va.gov and was unable to save an event using a "Where should the event be listed?" list that didn't match the Section I selected. Quite possible that Jill found an instance of an validation criteria step not firing correctly.

![Screenshot 2023-04-24 170324](https://user-images.githubusercontent.com/51967950/234127210-6eb62dfd-4925-44e4-9c97-58438778fec6.png)

**Comment by davidmpickett** [comment]
## Option A - Change "Where should the event be listed?" field
- Increase "Allowed number of values" from 1 to unlimited
- Change interface/widget from single select list to something with multiselect. Could pattern off the autocomplete widget for leadership list? ![Screenshot 2023-04-24 172329](https://user-images.githubusercontent.com/51967950/234129497-57e96d0e-7518-4a85-bb5b-652d02c1582b.png)
- Create workaround for the Outreach Events events list to let all VAMC editors add events to it, even though it's not in their section

## Option B - Add a separate field specifically for submitting events to the Outreach Event calendar
- Could be a simple boolean after the "Where should the event be listed?" field
- Not sure if this is feasible, or a desirable approach

**Comment by swirtSJW** [comment]
Option B while being the smallest lift on being able to select the logic, would yield no existing way to connect events on the FE,   A checkbox would not be an entity reference which would allow the listing pages to find what references them.

Sections should be unaffected as that is about ownership and we do not want outreach to be editing facility level events. 

This is really about changing two things.

1. Make the selector field (field_listing) for which listing page an event is connected to be multi-select.
2. Exempt the existing winnower from removing the Outreach and Events from the select list.

We definitely should not be tying our examples to Lovell.  Lovell is a completely different animal that does not need its logic changed.

**Comment by swirtSJW** [comment]
## Option C All events go to Outreach Events by default.
The other option is to alter how the Outreach Events list page works and have it grab all events, not just the ones that reference it.  (that would be forcing all events onto that page, without the option of ever not having an event show.  I am not sure event search can handle this.

RISK:   There is a risk with any of these approaches that the number of events may swamp Events V2 front end which puts them all into JS.

**Comment by swirtSJW** [comment]
## RISK:   Overloading event search
There is a risk with any of these approaches that the number of events may swamp Events V2 front end which puts them all into JS. Currently Outreach Events (events search) has 187 Upcoming results.   The current total of upcoming evetns across all event lists is 3,700  I am not certain the current event search (events V2) was built to support that level of growth and be performant.

**Comment by swirtSJW** [comment]
## Summary

### Option A  - Change "Where should the event be listed?" field
1. Make the selector field (field_listing) for which listing page an event is connected to be multi-select (cardinality of 2 or more).
![image](https://user-images.githubusercontent.com/5752113/234139311-64c40afe-af91-4cf5-a7e5-b604cb39d3d3.png)

2. Exempt the existing winnower from removing the Outreach and Events from the select list. (8)

- Pro: Least change to our existing patterns.
- Pro: Little to no FE changes needed,
- Con: moderate risk of overwhelming Outreach and Events since each event would be opting into displaying there. (would not be an immediate jump.)

### Option B - Add a separate field specifically for submitting events to the Outreach Event calendar
1. Add a checkbox field to opt-in to "Also show on Outreach Events"
2.  Would need to not show the new checkbox field when Outreach Events is actually selected if we want to keep that pattern.
- Pro:. Lightest lift on CMS
- Con: Would require a complete rebuild of Outreach Events FE page to use the unique logic.

### Option C - All events go to Outreach Events by default.
1. Would require a complete rebuild of Outreach Events FE page to use the logic to get ALL events.
- Pro: a more robust national calendar for Veterans
- Con: Heavy risk that Events V2 would not support the current volume of events.

**Comment by swirtSJW** [comment]
@kmariepat-cityfriends Let me know if you want to discuss ^^

**Comment by kmariepat-cityfriends** [comment]
@davidconlon this card is complete sans 1 AC regarding your selection of one of the proposed implementation options above. 

After my review I support Option A, in that it is the lightest development lift requiring little to no front end changes and is the least change to existing patterns. Additionally it caries a moderate risk to overwhelming the events cal with content, option B and C have a moderate to heavy risk of overwhelming the events cal.

With that said, please review the options above and identify your ideal choice. If you don't comment on this card before sprint planning, I will do my best to give a 10 min timebox to selecting an implementation option. From there @swirtSJW can complete the AC on the card by making the implementation epic for the selected approach.

**Comment by omahane** [comment]
@swirtSJW @davidmpickett A couple questions.

Why would the select list have to be 2 or more? Wouldn't unlimited work? The event could still be for only 1 section, I'd think.

Also, we should have some UX review on this, as the solution Dave Pickett recommended, to mirror the way Leadership List works, seems a better user experience than the "CTRL+Click" or "CMD+Click" for multi-select lists.

**Comment by jilladams** [comment]
The "multi-select as checkboxes" paradigm is "experimental" in the CMS Design System and spawned a ticket for the CMS team. So: we may be able to use it, but would need CMS collab cycle review to confirm. I'll find the open ticket.

**Comment by jilladams** [comment]
(Realizing I read "Leadership list" as "Benefit" bc braIns, so you are talking about something else entirely. Ignore.)

**Comment by jilladams** [comment]
From sprint planning: 

Business case: Right now VEO has to manually copy/paste nationally relevant events that happen in a regional/local location. e.g.: PACT Act related events must be published nationally. 

Goal: 
   * Primary: Make local level events visible at the national level
   * Secondary: As an editor, I want to publish this event to every calendar I have access to. (Regional visibility)
* A - covers both scenarios and is lightest lift. This could affect page performance on the Outreach Events cal page.
* B - covers the Primary goal, but doesn't really address Secondary goal
* C - DaveC: definitely no.

**Comment by jilladams** [comment]
@swirtSJW @kmariepat-cityfriends Is this ticket ok to close? Comment above from sprint planning noted Option A is preferred. I think the outstanding item here is tickets for implementing that option?

**Comment by kmariepat-cityfriends** [comment]
An epic to track implementation has been created: Events Calendar Single Source of Truth #13527
