### ISSUE TITLE
VA Benefits Taxonomy: Explore Chosen to implement better a multi-select interface

### ISSUE THREAD

**Issue by chri5tia** [department-of-veterans-affairs/va.gov-cms#13232]
### User story
> _Describe the audience/user, enhancement or fix, and value / outcome desired._

**AS A(N)**
editor or content creator on va.org
**I WANT**
I want to be able to choose multiple options from a list without the items taking up a lot of space on the screen (checkbox) or having to scroll and use keyboard commands in order to select more than one
**SO THAT**
I don't miss something and so that I have accessibility options

### Engineering notes / background
Explore https://harvesthq.github.io/chosen/ 

## Acceptance criteria

>Consider
> - Design / Accessibility reviews
> - Collab cycle requirements
> - Device sizes (mobile first)
> - Documentation updates / Change management
< - [Content model documentation](https://prod.cms.va.gov/admin/structure/cm_document)
> - Testing notes

- [ ] Explore https://harvesthq.github.io/chosen/ and decide whether or not to implement it.

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [X] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`

**Comment by jilladams** [comment]
closing as no op. If CMS team wants to go this route instead, they may reopen and take it over.
