### ISSUE TITLE
Add Github Workflow for Injected Header Changes

### ISSUE THREAD

**Issue by dsasser** [department-of-veterans-affairs/va.gov-cms#13230]
## Status
[2024-03-21] This may become a moot point after the flattened HTML of the injected header/footer is released. Will be revisited after that happens.

## Description
Write a github workflow that comments or reviews a PR with header changes, such that developers are reminded to test the injected header.

## Background 
Teams that make changes to the header aren't always considering how those changes will affect the injected header context.

## Engineering Notes
Vets-website does something similar in the [icon-check workflow](https://github.com/department-of-veterans-affairs/vets-website/blob/main/.github/workflows/pull-request.yml#:~:text=a%20VSP%20review.-,icon%2Dcheck%3A,-name%3A%20Icon). 

## Acceptance Criteria
- [ ] PRs that touch the header will go through automated reviews created by a new Github workflow to ensure the injected header works as designed with the new cope.

### Team
Please check the team(s) that will do this work.
- [x] `Public Websites`

**Comment by FranECross** [comment]
Closing as as a no op; the DST will be modifying PRs ticket templates for the header/footer.
