### ISSUE TITLE
VA Benefits Taxonomy Build: Prevent duplicate taxonomy terms

### ISSUE THREAD

**Issue by chri5tia** [department-of-veterans-affairs/va.gov-cms#13231]
### User story
> _Describe the audience/user, enhancement or fix, and value / outcome desired._

**AS A(N)** editor or content creator for va.gov
**I WANT** to ensure that I don't accidentally create multiple instances of the same VA Benefit
**SO THAT** there is only once source of truth for each benefit

### Engineering notes / background
We are already using "allow only one" module. Explore this. VA Services doesn't prevent duplicate taxonomy terms either.

Duplicates are considered dupes regardless of Case, but not managing spaces, e.g. 1s and 2s are dupes of each other but As and Bs are not: 
A1. healthcare
A2. Healthcare
B1. Health Care
B2. health care

### Quality / testing notes
May need tests written. 

## Acceptance criteria

>Consider
> - Design / Accessibility reviews
> - Collab cycle requirements
> - Device sizes (mobile first)
> - Documentation updates / Change management
< - [Content model documentation](https://prod.cms.va.gov/admin/structure/cm_document)
> - Testing notes

- [x] Met with Swirt / Daniel to understand existing patterns
- [x] If existing patterns don't satisfy requirements, determined a technical plan for doing that based on LOE for MVP. in other words: what's the easiest way for now. 
- [x] Taxonomy doesn't allow duplicate terms based on Official Benefit Name field, regardless of case.
- [ ] Automated testing verifies no duplicates behavior

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [X] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`

**Comment by chri5tia** [comment]
Using existing patterns, it was straight forward to prevent duplicate Benefit names and API IDs. We may want to talk about the error message
![Screenshot 2023-04-13 at 9 12 40 PM](https://user-images.githubusercontent.com/22764938/231939884-d6e334fb-3fe5-4a4d-9958-74c329a20212.png)
.

See in demo: admin/structure/taxonomy/manage/va_benefits_taxonomy/overview

**Comment by wesrowe** [comment]
I found that the error checking for both Name and API ID works as expected – i.e., the check is not case-sensitive. However, I think we should try to polish the error messaging if it's not a heavy lift. 

Here are the two error message areas when I broke uniqueness for both fields at once:
<img width="701" alt="image" src="https://user-images.githubusercontent.com/4054752/232163753-5ee8c574-d5c2-447a-bca2-b2ec309186e8.png">
<img width="623" alt="image" src="https://user-images.githubusercontent.com/4054752/232163766-4ef64aff-ceb0-40ae-9639-61f8b5857b93.png">

Note that the references use different words to refer to the same fields, and none is exactly what the field is called in the UI.

**Comment by jilladams** [comment]
Same here - should close loop on error messaging here in the sync tomorrow to make sure these are closeable in sprint.

**Comment by jilladams** [comment]
@wesrowe can you help clarify expectations for this sprint based on yesterday's convo with Blake?

**Comment by wesrowe** [comment]
We will not hold this ticket back due to error messaging

**Comment by swirtSJW** [comment]
The error messaging can't be nicely polished because it comes from contrib and has to fit a lot of use cases.  However the allow only one fields should be moved up to in front of the field they control.

**Comment by wesrowe** [comment]
@chri5tia, can you please note Steve's suggestion for revision next sprint? (Placement of uniqueness error messages.)

**Comment by wesrowe** [comment]
@chri5tia, I'll note Steve's suggestion for a ticket next sprint? (Placement of uniqueness error messages.)
