### ISSUE TITLE
Implement Flipper Removal 

### ISSUE THREAD

**Issue by kmariepat-cityfriends** [department-of-veterans-affairs/va.gov-cms#13239]
#### Background 

#11592 and #11593 are discovery cards looking into criteria to remove the flippers they reference

##### Acceptance Criteria 
- [x] I expect PRs are created for the following branches to reviewed and follow existing team QA process: 

- [x] vets-api - va-11593-remove-ppms-forced-unique-id-feature

**Comment by kmariepat-cityfriends** [comment]
Next Steps: @kmariepat-cityfriends to confirm the above flippers are approved to be removed

**Comment by kmariepat-cityfriends** [comment]
these 2 ACs were removed to be put on another backlog card for later removal

- [ ] vets-website - va-11592-remove-covid-vaccine-query-flipper
- [ ] vets-api - va-11592-remove-covid-vaccine-query-feature

**Comment by kmariepat-cityfriends** [comment]
Backlog card referenced above is here: #13331

**Comment by maxx1128** [comment]
@kmariepat-cityfriends That's right, I apologize for forgetting to assign myself. I'll do so now.
