### ISSUE TITLE
Lovell Menu Missing (ALL Lovell)

### ISSUE THREAD

**Issue by kmariepat-cityfriends** [department-of-veterans-affairs/va.gov-cms#13244]
# Screenshots
https://www.va.gov/lovell-federal-health-care-va/about-us/leadership/
![Screen Shot 2023-04-12 at 9 59 51 AM](https://user-images.githubusercontent.com/766573/231517818-09614f8c-e8d5-4430-9e28-bffcd6ffc7ae.png)

https://www.va.gov/lovell-federal-health-care-tricare/
![image (11)](https://user-images.githubusercontent.com/766573/231518112-cde8baeb-78ac-4cfb-ac93-81fd741f5ecf.png)

**Comment by swirtSJW** [comment]
This has been resolved on the FE.  Menus are showing now.

(details to follow but wanted to get this timestamped)

**Comment by swirtSJW** [comment]
Assigning to @ryguyk  so that he is credited with the fix as he had the most time on it.
