### ISSUE TITLE
Figure out how to solve Yellow Ribbon issues in email

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#13257]
### User story

**AS A** PO
**I WANT** to help stakeholders figure out why a school is missing from the Yellow Ribbon Tool
**SO THAT** Veterans can find all the schools that participate in the program.

Michael Napper forwarded emails suggesting that several schools were missing from the YR Tool. 

## Acceptance criteria

- [x] Reproduced the error – i.e., the schools really are missing from the YR tool
- [x] Studied documentation of how the tool connects to the database (which is maintained by others, including Kristina Howard)
- [x] Contacted relevant people for resolution
- [x] Provided any additional support

**Comment by wesrowe** [comment]
I forwarded the emails to @jtmst.

I attempted to reproduce the error but the two "missing" schools I could identify from the emails were present in the tool. I replied to Michael Napper asking for clarification.

Is it possible that the YR Tool fails in silent or unclear ways when `vets-api` has latency or other issues, similar to Find-a-form?

**Comment by jtmst** [comment]
Per Noah: "Brian Grubb needs to hit up the dpet of ed to get them added to a spreadsheet. There are 2 yellow ribbon spreadsheets used to build out these tables. The one that your api references doesn't have the instititutions. The ones the comparison tool uses does. So when your api goes to look them up, they're not there. It's not a coding thing, it's a data thing."


At this point we've done all we can do with this,  the data needs to be updated and then the tool will be accurate.

**Comment by jilladams** [comment]
@wesrowe did the notes above make it back to the Yellow Ribbon folks? Not totally clear what we need to do next as far as ownership.

**Comment by wesrowe** [comment]
I'm pretty sure @jtmst said that the YR folks are who he was communicating with. "Call from inside the house" situation.

**Comment by jtmst** [comment]
Yep, the engineer on their team told me it was a data issue that they would address with the dept of edu.  Nothing else for us to do here

**Comment by jilladams** [comment]
Sent a close loop to the requesters, just in case that info didn't make its way back around already. Thanks!
