### ISSUE TITLE
Understand how to map needs of VBA users to CMS: Create VBA Editor role(s)

### ISSUE THREAD

**Issue by kmariepat-cityfriends** [department-of-veterans-affairs/va.gov-cms#13272]
# Stories by user type

These stories are all formatted the same way:
- I want to _DRUPAL ACTION_ a **DRUPAL ENTITY** in a `DRUPAL SECTION`

I tried to write these stories in a way that is agnostic about Drupal Roles & Workflows, since those should be configured to support these stories (rather than the reverse). To do so, I created this list of Drupal actions that is slightly different than the one we use in our existing workflow.

**Drupal Actions Glossary**
- _Create_ - Create a new instance of a Drupal entity
- _Edit_ - Draft a revision of an existing Drupal entity (regardless of publishing status)
- _Change Node Status_ - Publish or Archive a Drupal entity (change node_status between 0 & 1)
- _Publish Revision_* - Publish a new revision of a published Drupal entity (node_status = 1)
- _Submit for Approval_ & _Approve_ - Only used in situations with official sign-off steps

*The ability to perform this action cannot currently be granted without also granting the ability to _Change Node Status_

## VBA Local Facility Editors
e.g. Honolulu Regional Office employee

**MVP**
- I want to _Edit, Publish Revision_ a **VBA Facility**, in `a regional VBA section`
- I want to _Create, Edit, Change Node Status, Publish Revision_ a **VBA Facility Service**, in a `regional VBA section`
- I want to _Create, Edit, Change Node Status, Publish Revision_  a **Banner**, in `a regional VBA section`

**Post-MVP**
- I want to _Create, Edit, Change Node Status, Publish Revision_ **Events**, in `a regional VBA section`
- I want to _Edit, Publish Revision_ a **Event List Page**, in `a regional VBA section`
- I want to _Create, Edit, Change Node Status, Publish Revision_ a **Staff Profile**, in `a regional VBA section`
- I want to _Edit, Publish Revision_ a **Leadership List Page**, in `a regional VBA section`

## VBA National Editors
e.g. Office of Strategic Engagement employees

- I want to do everything **VBA Local Editors** can & also...
- I want to _Edit, Approve, Publish Revision_ a **VBA Service Region**, in `all VBA sections`
- I want to _Edit, Submit for Approval, Publish Revision_ a **VA Service Taxonomy Term**, in `all VBA sections`
- I want to _Edit, Publish Revision_ a **Centralized Content**, in `all VBA sections`

## Facilities Admins
e.g. CMS Help Desk, Facilities Team Engineers

**MVP**
- I want to do everything **VBA Local Editors** & **VBA National Editors** can & also...
- I want to _Create, Change Node Status,_ a **VBA Facility**, in `all VBA sections`
- I want to _Create, Change Node Status_ a **VBA Service Region**, in `all VBA sections`
- I want to _Create, Change Node Status_ a **Centralized Content**, `in all VBA sections` 
- I want to _Create, Edit, Change Node Status, Publish Revision_ a **VBA Menu**, in `all VBA sections` 

**Post MVP**
- I want to _Create, Change Node Status_ a **Event List Page**, in `all VBA sections`
- I want to _Create, Change Node Status_ a **Leadership List Page**, in `all VBA sections`

## VA Service Taxonomy Admin
e.g. OCTO-DE employee

**Post MVP?**
- I want to _Create, Approve, Change Node Status_ a **VA Service Taxonomy Term**, in `all VBA sections`

## VBA Business Line Editors
e.g. Pension Benefits employee

**Post MVP?**
- I want to _Edit, Submit for Approval_ a **VBA Service Region**, in a `business-line VBA section`

# Stories by Drupal Entity

Here I am listing the user with the least permissions that can perform each action. Any action that VBA Local Facility Editors can perform can also be performed VBA National Editors & Facilities Admins, but I won't list all three every time.

## Low-risk, high-volume entities 

- VBA Facility Service
- Banner
- Event
- Staff Profile

**Permissions**
- _Create_ =  VBA Local Facility Editors
- _Change Node Status_ =  VBA Local Facility Editors
- _Edit_ = VBA Local Facility Editors
- _Publish Revision_ = VBA Local Facility Editors
- _Submit for Approval_ & _Approve_ = Not used

**Suggested Approach**
- Roles: Content Creator - VBA & Content Publisher 
- Workflow: Existing Editorial Workflow

## Moderate-risk, moderate-volume entities

- VBA Facility
- Event List Page
- Leadership List Page

**Permissions**
- _Create_ =  Facilities Admins
- _Change Node Status_ =  Facilities Admins
- _Edit_ = VBA Local Facility Editors 
- _Publish Revision_ = VBA Local Facility Editors
- _Submit for Approval_ & _Approve_ = Not used

**Suggested Approach**
- Roles: Content Publisher 
- Workflow: Add a new, more restrictive Editorial Workflow that distinguishes _Change Node Status_ & _Publish Revision_ so we can limit _Change Node Status_ to Facilities Admins

## High-risk, low-volume entities 

- VBA Service Region
- Centralized Content
- VA Service Taxonomy Term
- VBA Menu

**Permissions**
- _Create_ =  Facilities / Taxonomy Admins
- _Change Node Status_ =  Facilities / Taxonomy Admins
- _Edit_ = VBA Business Line Editors / VBA National Editors 
- _Publish Revision_ = VBA National Editors
- _Submit for Approval_  = VBA Business Line Editors / VBA National Editors 
- _Approve_ = VBA National Editors / Taxonomy Admins

**Suggested Approach**
- This group isn't as easy to lump together, but you get the gist
- Would also require a Restrictive Editorial Workflow to limit powers of VBA National Editors for different entities

## Acceptance Criteria 
- [x] I expect that VBA national editor  needs in the form of their content type access is mapped in order to inform new `VBA editor role creation`, `permissions` `workflow`(draft, published, archived, and `sections` 
- [x] I expect that VBA local editor needs in the form of their content type access is mapped in order to inform new `VBA editor role creation`, `permissions`  `workflow` (draft, published, archived), and `sections` 
- [x] I expect that based on the finding in this cards, acceptance criteria are updated on #11334
- [x] I expect that if something is observed that is an exception to existing patterns it is documented on this card
- [x] I expect that the output and work on this card is reviewed with at least another facilities team member 
- [x] I expect that the CMS team is asked if they want to contribute to this work now or wait until midpoint CMS collab cycle review (@Jo + another CMS team member should be consulted with this ask)

**Comment by davidmpickett** [comment]
The initial mapping of Drupal entities to VBA user types from the [VBA Content model](https://app.mural.co/t/departmentofveteransaffairs9999/m/vagov6717/1677277602711/74cecb64b6eeb9558aa868240cd726b54fcb93a7?wid=0-1680038357024)

![VBA Content model_2023-04-26_20-37-37](https://user-images.githubusercontent.com/51967950/234696632-e0747fdb-750e-44d5-99a7-0407b7633439.png)

**VBA National Editors**
- VA Service Taxonomy (all? can we narrow to VBA-relevant?)
- VBA Service Region (all)
- Centralized Content
+ everything a local editor can do?

**VBA Local Editors**
- VBA Facility (in their section)
- VBA Facility Service (in their section)
- Banners (in their section)

**Comment by davidmpickett** [comment]
Mural where I'm diagramming my understanding as i learn about this space: https://app.mural.co/t/departmentofveteransaffairs9999/m/vagov6717/1677277602711/74cecb64b6eeb9558aa868240cd726b54fcb93a7?wid=0-1682544407635

**Comment by davidmpickett** [comment]
Thinking through some things
## Distinguishing Pre-Published Drafts from Published Drafts

### Workflow with Approval Steps

``` mermaid
flowchart LR

    A -->|Edit| A
    A(Draft) -->|Review| B(In review)
    B -->|Approve| C(Approved)
    C -->|Publish| D(Published)
    D -->|Archive| E(Archived)
    E -->|Restore from Archive|D
    D -->|Edit| F(Proposed Revision)
    F -->|Review|B
    F -->|Edit| F
```

**Comment by davidmpickett** [comment]
Updated the VBA Content Model airtable to start generating User Permission stories: https://airtable.com/shrbC1tO24AZavkEU

**Comment by davidmpickett** [comment]
Made significant updates to the Content Moderation Roles documentation
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/content-governance/content-moderation-roles/README.md

[Building a presentation](https://docs.google.com/presentation/d/1Kkjmx7rBprudAHXN8uFuxNp7D0nPD2oSj9-9-Jirxr8/edit?usp=sharing) to explain the basic concepts of out User Permission Model:
[CMS User Permission Model.pptx](https://github.com/department-of-veterans-affairs/va.gov-cms/files/11402281/CMS.User.Permission.Model.pptx)

**Comment by swirtSJW** [comment]
The diagrams you have done on this are amazing @davidmpickett Is there anything more you and I need to discuss or collaborate on to be able to call this ticket done?

**Comment by davidmpickett** [comment]
@swirtSJW I updated the main comment on this card with all the user permission stories I think we need for VBA. Tried to explain them in plain language while also being sensitive to important Drupal terminology. Please take a look and let me know if anything is unclear or seems dubious

And here they are in csv format from AirTable if that's easier to review:
[User Permission Stories-Grid view.csv](https://github.com/department-of-veterans-affairs/va.gov-cms/files/11427085/User.Permission.Stories-Grid.view.csv)

**Comment by swirtSJW** [comment]
@davidmpickett 
>> I want to Create, Edit, Change Node Status, Publish Revision a Banner, in 

What kind of Banner are e talking about here?  None of the three we have go by that name. 

1.  [VAMC System Banner Alert with Situation Updates](https://prod.cms.va.gov/node/add/full_width_banner_alert)
2. [Promo Banner](https://prod.cms.va.gov/node/add/promo_banner)
3. [Full Width Alert](https://prod.cms.va.gov/node/add/banner)
4.  Some other new banner.  

The decision is not germane to the issue, but it did make me aware that I wasn't sure.

**Comment by swirtSJW** [comment]
Very thorough review of all of this.  Well done.  It is good to know that most of our current setup supports this without any alteration.   The alterations that are needed are both minor and expected to so that is great.

**Comment by jilladams** [comment]
Dave also completed 
> I expect that based on the finding in this cards, acceptance criteria are updated on https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11334
earlier this afternoon. That was the last AC. 

I'm moving this to PO Review.

**Comment by davidmpickett** [comment]
> @davidmpickett
> 
> > > I want to Create, Edit, Change Node Status, Publish Revision a Banner, in
> 
> What kind of Banner are e talking about here? None of the three we have go by that name.
> 
> 1. [VAMC System Banner Alert with Situation Updates](https://prod.cms.va.gov/node/add/full_width_banner_alert)
> 2. [Promo Banner](https://prod.cms.va.gov/node/add/promo_banner)
> 3. [Full Width Alert](https://prod.cms.va.gov/node/add/banner)
> 4. Some other new banner.
> 
> The decision is not germane to the issue, but it did make me aware that I wasn't sure.

@swirtSJW See [Jordan's design](https://www.sketch.com/s/891d33ae-152d-471c-ab5d-9aedf89cf6ff) for the front-end implementation of banners. We haven't discussed anything about the Drupal side and whether this can use an existing content type of if it needs it's own. But yes that's definitely a conversation we need to have.

**Comment by davidmpickett** [comment]
> @davidmpickett
> 
> > > I want to Create, Edit, Change Node Status, Publish Revision a Banner, in
> 
> What kind of Banner are e talking about here? None of the three we have go by that name.
> 
> 1. [VAMC System Banner Alert with Situation Updates](https://prod.cms.va.gov/node/add/full_width_banner_alert)
> 2. [Promo Banner](https://prod.cms.va.gov/node/add/promo_banner)
> 3. [Full Width Alert](https://prod.cms.va.gov/node/add/banner)
> 4. Some other new banner.
> 
> The decision is not germane to the issue, but it did make me aware that I wasn't sure.

@swirtSJW I just created a stub ticket for working out VBA banners https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13811
