### ISSUE TITLE
Add preview support for Lovell in content-build

### ISSUE THREAD

**Issue by ryguyk** [department-of-veterans-affairs/va.gov-cms#13289]
## Description
Preview is a useful tool for both editors and developers. It's available in most places, but it is currently unavailable for most or all Lovell pages because the preview process does not include the special Lovell processing. This ticket is to add that processing to the preview mechanism.

### Implementation notes
This is a starting point, if not the entire implementation:
`script/preview.js`
```
app.get('/preview', async (req, res, next) => {
    .
    .
    .
    Object.assign(drupalData.data, nonNodeContent.content.data);

    /* ADD THESE THREE LINES */
    drupalData.data.nodeQuery = drupalData.data.nodes;
    processLovellPages(drupalData);
    const pageIndex = req.query?.lovellVariant === 'va' ? 1 : 0;

    const drupalPage = drupalData.data.nodes.entities[pageIndex];
    const drupalPath = `${req.path.substring(1)}/index.html`;

    .
    .
    .
}
```
The three lines:
1. `drupalData.data.nodeQuery = drupalData.data.nodes;`
    - The preview steps use `nodes` but `processLovellPages` uses `nodeQuery`. This line just creates an alias.
2. `processLovellPages(drupalData);`
    - This is what actually does the Lovell-specific work.
3. `const pageIndex = req.query?.lovellVariant === 'va' ? 1 : 0;`
    - If we want to be able to preview cloned pages in both VA and TRICARE contexts, this line accommodates the addition of a query parameter that would allow preview to be done as in this example: `/preview?nodeId=2431&lovellVariant=va`

## Acceptance Criteria
- [ ] I expect that Lovell nodes are viewable in Preview mode
- [ ] I expect that pages that are duplicated and available at both VA and TRICARE paths can be previewed in both contexts 

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [ ] `Public Websites`
- [x] `Facilities`
- [ ] `User support`

**Comment by kmariepat-cityfriends** [comment]
- CMS backlog item: supporting both preview experiences a separate issue (do we allow COPE content to be previewed)

**Comment by ryguyk** [comment]
[The PR that closes this issue](https://github.com/department-of-veterans-affairs/content-build/pull/1575) adds support for Lovell preview in _almost_ all cases. Some Lovell processing requires the existence of multiple nodes that are then merged/injected/etc. This cannot be done with the current preview solution.

I've created a [draft PR for a more robust solution](https://github.com/department-of-veterans-affairs/content-build/pull/1576). It feels like scope creep, and the solution requires more testing and organization. But it's largely done and feels viable. If there is a strong need in the future for preview support for the Lovell pages that are not supported with the smaller solution, this draft PR can be considered for more development and merging.

**Comment by kmariepat-cityfriends** [comment]
@ryguyk thank you for the update, I've added your draft PR to a card for the backlog: Additional support for Lovell preview #13803
