### ISSUE TITLE
Dirscovery: GraphQL v3 update for Drupal 10

### ISSUE THREAD

**Issue by edmund-dunn** [department-of-veterans-affairs/va.gov-cms#13296]
## Description
Update GraphQLv3 for Drupal 10.

## Acceptance Criteria
- [ ] Testable_Outcome_X
- [ ] Testable_Outcome_Y
- [ ] Testable_Outcome_Z
- [ ] Requires design review

### Team
Please check the team(s) that will do this work.

- [x] `CMS Team`
- [ ] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`

**Comment by dawnpruitt** [comment]
Duplicate ticket, please see https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13456
