### ISSUE TITLE
URL Change for: Bonner County VA Clinic (formerly Sandpoint VA Clinic) [Ready to go]

### ISSUE THREAD

**Issue by stefaniefgray** [department-of-veterans-affairs/va.gov-cms#13309]
### Implementation date
When does this request need to be live:
As soon as possible

### Instructions for URL redirect
(Note: This issue will be used from initial request through implementation to ensure all individuals working on this are notified of status updates.  Please do not create multiple issues to track different steps.)
- [x] Notify VA stakeholders as appropriate.
- [x] Link the related facility closure / rename issue.
- [x] Create a URL redirect in the [devops](https://github.com/department-of-veterans-affairs/devops) repo in `ansible/deployment/config/revproxy-vagov/vars/redirects.yml`
- [x]  Redirects deploy weekly on Wed. at 10am ET, or by requesting OOB deploy (of the revproxy job to prod) in #vfs-platform-support. After deploy, validate that the URL redirect is deployed. (Note: In the event of a facility closure or a name change,  validate that this occurs before making the Lighthouse csv changes.)
- [x]  Notify helpdesk via comment on ticket or Slack message in #cms-support that changes are ready for review.  

#### URL Redirect
| Current URL  |  Redirect Destination or New URL |
| ---  |  --- |
| /spokane-health-care/locations/sandpoint-va-clinic | /spokane-health-care/locations/bonner-county-va-clinic |

### Instructions for canonical URL change
- [x] Verify that the new URL for the facility is published and accessible on VA.gov.
- [x] Update the [CSV in Lighthouse](https://github.com/department-of-veterans-affairs/lighthouse-facilities/blob/master/facilities/src/main/resources/websites.csv) with the changed URL, maintaining the sorted order of the Facility API IDs.
- [x] Create a PR in the [lighthouse-facilities repo](https://github.com/department-of-veterans-affairs/lighthouse-facilities), tagging the Lighthouse team.
- [x] Post a message in the #api-facilities channel in Slack, with an @mention to a Lighthouse team member.
- [x] Validate that the change has deployed by checking that the Facility Locator has been updated with the new url.
- [ ] Edit facility node and remove the `Changed name` and `Awaiting CSV` flags. Then, save node (with moderation state = published)

#### URL change example (update with actual ID and URL)
| Facility API ID  |  Full VA.gov URL |
| ---  |  --- |
| vha_668QD | https://www.va.gov/spokane-health-care/locations/bonner-county-va-clinic |

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [ ] `Public Websites`
- [x] `Facilities`
- [x] `User support`

**Comment by omahane** [comment]
@kmariepat-cityfriends CSV has been deployed and confirmed in Facility Locator. This can be closed.
