### ISSUE TITLE
Create Database Migrations for Income Limits Datasets

### ISSUE THREAD

**Issue by dsasser** [department-of-veterans-affairs/va.gov-cms#13319]
## Description
The Income Limits application will utilize the vets-api postgresql database for backend data storage. In order to support this, the table schemas will need to be created in the Income Limits vets-api Ruby application.

## Engineering notes

- Schemas below are taken from VES tables, unaltered
- Consider limiting how many years back the app should allow searching
- Use ID as primary key for all tables

### std_county
| FIELD | TYPE | ALLOW NULL | EXAMPLE VALUE |
|--------|--------|--------|--------|
|ID		|integer	|NO		|1010890|
|NAME		|string		|NO		|Lafayette|
|COUNTYNUMBER	|integer	|NO		|071|
|DESCRIPTION	|string		|NO		|The county of Lafayette|		
|STATE_ID	|integer	|NO		|1009328|
|VERSION	|integer	|NO		|0|
|CREATED	|datetime	|NO		|6/23/2004 9:43:48.000000 AM|
|UPDATED	|datetime	|YES		|2/19/2010 8:35:36.400104 AM|
|CREATEDBY	|string		|YES		|Initial Load|
|UPDATEDBY	|string		|YES		|HEC Review|

### gmt_thresholds
| FIELD | TYPE | ALLOW NULL | EXAMPLE VALUE |
|--------|--------|--------|--------|
|ID		|integer		|NO		|1477926|
|EFFECTIVEYEAR	|integer		|NO		|2001|
|STATENAME	|string		|NO		|INDIANA|
|COUNTYNAME	|string		|NO		|HENDRICKS COUNTY|
|FIPS		|integer		|NO	|	18063|
|TRHD1		|integer		|NO	|	34000|
|TRHD2		|integer	|	NO	|	34000|
|TRHD3		|integer	|	NO	|	34000|
|TRHD4		|integer	|	NO	|	34000|
|TRHD5		|integer	|	NO	|	34000|
|TRHD6		|integer	|	NO	|	34000|
|TRHD7		|integer	|	NO	|	34000|
|TRHD8		|integer	|	NO	|	34000|
|MSA		|integer	|	NO	|	3480|
|MSANAME	|	string	|	YES	|	test|
|VERSION	|	integer	|	NO	|	0|
|CREATED	|	datetime|	NO	|	7/21/2005 12:13:36.000000 PM|
|UPDATED	|	datetime|	YES	|	7/21/2005 12:13:36.000000 PM|
|CREATEDBY	|string		|YES		|Initial Load|
|UPDATEDBY	|string		|YES		|HEC Review|

### std_incomethreshold

| FIELD | TYPE | ALLOW NULL | EXAMPLE VALUE |
|--------|--------|--------|--------|
|ID				|integer	|	NO		|1617161|
|INCOME_THRESHOLD_YEAR		|integer	|	NO		|1993|
|EXEMPT_AMOUNT			|integer	|	NO		|19912|
|MEDICAL_EXPENSE_DEDUCTIBLE	|integer	|	NO		|5|
|CHILD_INCOME_EXCLUSION		|integer	|	NO		|6207|
|DEPENDENT			|integer	|	NO		|23896|
|ADD_DEPENDENT_THRESHOLD|		integer	|	NO		|1330|
|PROPERTY_THRESHOLD		|integer	|	NO		|50000|
|PENSION_THRESHOLD		|integer	|	YES		|8037|
|PENSION_1_DEPENDENT		|integer	|	YES		|10527|
|ADD_DEPENDENT_PENSION		|integer	|	YES		|1368|
|NINETY_DAY_HOSPITAL_COPAY	|integer	|	YES		|716|
|ADD_90_DAY_HOSPITAL_COPAY	|integer	|	YES		|358|
|OUTPATIENT_BASIC_CARE_COPAY	|integer	|	YES		|39|
|OUTPATIENT_SPECIALTY_COPAY	|integer	|	YES		|50|
|THRESHOLD_EFFECTIVE_DATE	|datetime	|YES		|12/01/1994 00:00:00|
|AID_AND_ATTENDANCE_THRESHOLD	|integer	|	YES	|	12856|
|OUTPATIENT_PREVENTIVE_COPAY	|integer	|	YES	|	0|
|MEDICATION_COPAY		|integer	|	YES	|	7|
|MEDICATION_COPAY_ANNUAL_CAP	|integer	|	YES	|	840|
|LTC_INPATIENT_COPAY		|integer	|	YES	|	97|
|LTC_OUTPATIENT_COPAY		|integer	|	YES	|	15|
|LTC_DOMICILIARY_COPAY		|integer	|	YES	|	5|
|INPATIENT_PER_DIEM		|integer	|	YES	|	10|
|DESCRIPTION			|string		|YES		||
|VERSION			|	integer	|	NO	|	0|
|CREATED			|	datetime|	NO	|	7/21/2005 12:13:36.000000 PM|
|UPDATED			|	datetime|	YES	|	7/21/2005 12:13:36.000000 PM|
|CREATEDBY			|string		|YES		|Initial Load|
|UPDATEDBY			|string		|YES		|HEC Review|

### std_state
| FIELD | TYPE | ALLOW NULL | EXAMPLE VALUE |
|--------|--------|--------|--------|
|ID		|integer	|	NO	|	1009301|
|NAME		|string		|NO		|Alabama|
|POSTALNAME	|string		|NO		|AL|
|FIPSCODE	|integer	|NO		|01|
|COUNTRY_ID	|integer	|	NO	|	1006840|
|VERSION	|	integer	|	NO	|	0|
|CREATED	|	datetime|	NO	|	7/21/2005 12:13:36.000000 PM|
|UPDATED	|	datetime|	YES	|	2/19/2010 8:36:52.786825 AM|
|CREATEDBY	|string		|YES		|Initial Load|
|UPDATEDBY	|string		|YES		|HEC Review|

### std_zipcode
| FIELD | TYPE | ALLOW NULL | EXAMPLE VALUE |
|--------|--------|--------|--------|
|ID			|integer		|NO		|1111258|
|ZIPCODE		|integer		|NO		|03869|
|ZIPCLASSIFICATION_ID	|integer		|YES		|1100002|
|PREFERREDZIPPLACE_ID	|integer		|YES		|1163648|
|STATE_ID		|integer		|NO		|1009333|
|COUNTYNUMBER		|integer		|NO		|017|
|VERSION	|	integer	|	NO	|	0|
|CREATED	|	datetime|	NO	|	7/21/2005 12:13:36.000000 PM|
|UPDATED	|	datetime|	YES	|	2/19/2010 8:36:52.786825 AM|
|CREATEDBY	|string		|YES		|Initial Load|
|UPDATEDBY	|string		|YES		|HEC Review|

## Acceptance Criteria
- [ ] Database table migrations created
- [ ] Database tables std_county, gmt_thresholds, std_incomethreshold, std_state, and std_zipcode exist with the above schema definitions
- [ ] Confirmed locally that the migrations work as expected
- [x] Self-documented in code

**Comment by jtmst** [comment]
PR issues fixed and awaiting platform code review
