### ISSUE TITLE
Link format validation failure on Section Terms preventing save

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#13317]
## Describe the defect
When I try to edit a term in the sections taxonomy, I am unable to submit it and get a white screen error  that eventually traces back to a php error in PreventAbsoluteCmsLinksValidator  

I have verified that this is ONLY happening on Sections taxonomy.   All other taxonomies are working correctly.
I have verified that I can create new sections without seeing this error,  The error only comes on saving an existing term.

## To Reproduce
1. Go to https://staging.cms.va.gov/taxonomy/term/2/edit
2. Save the term
3. See whitescreen error of "The website encountered an unexpected error. Please try again later."
4.Go to watchdog and see the php error
`
TypeError: Drupal\va_gov_backend\Plugin\Validation\Constraint\PreventAbsoluteCmsLinksValidator::validateHtml(): Argument #1 ($html) must be of type string, null given, called in /var/www/cms/docroot/modules/custom/va_gov_backend/src/Plugin/Validation/Constraint/PreventAbsoluteCmsLinksValidator.php on line 43 in Drupal\va_gov_backend\Plugin\Validation\Constraint\PreventAbsoluteCmsLinksValidator->validateHtml() (line 83 of /var/www/cms/docroot/modules/custom/va_gov_backend/src/Plugin/Validation/Constraint/PreventAbsoluteCmsLinksValidator.php) 
#0 /var/www/cms/docroot/modules/custom/va_gov_backend/src/Plugin/Validation/Constraint/PreventAbsoluteCmsLinksValidator.php(43): Drupal\va_gov_backend\Plugin\Validation\Constraint\PreventAbsoluteCmsLinksValidator->validateHtml(NULL, Object(Drupal\va_gov_backend\Plugin\Validation\Constraint\PreventAbsoluteCmsLinks), 0) 
#1 /var/www/cms/docroot/core/lib/Drupal/Core/TypedData/Validation/RecursiveContextualValidator.php(201): Drupal\va_gov_backend\Plugin\Validation\Constraint\PreventAbsoluteCmsLinksValidator->validate(Object(Drupal\Core\Field\FieldItemList), Object(Drupal\va_gov_backend\Plugin\Validation\Constraint\PreventAbsoluteCmsLinks)) 
#2 /var/www/cms/docroot/core/lib/Drupal/Core/TypedData/Validation/RecursiveContextualValidator.php(153): Drupal\Core\TypedData\Validation\RecursiveContextualValidator->validateConstraints(Object(Drupal\Core\Field\FieldItemList), '000000000000134...', Array) 
#3 /var/www/cms/docroot/core/lib/Drupal/Core/TypedData/Validation/RecursiveContextualValidator.php(163): Drupal\Core\TypedData\Validation\RecursiveContextualValidator->validateNode(Object(Drupal\Core\Field\FieldItemList)) 
#4 /var/www/cms/docroot/core/lib/Drupal/Core/TypedData/Validation/RecursiveContextualValidator.php(105): Drupal\Core\TypedData\Validation\RecursiveContextualValidator->validateNode(Object(Drupal\Core\Entity\Plugin\DataType\EntityAdapter), Array, true) 
#5 /var/www/cms/docroot/core/lib/Drupal/Core/TypedData/Validation/RecursiveValidator.php(93): Drupal\Core\TypedData\Validation\RecursiveContextualValidator->validate(Object(Drupal\Core\Entity\Plugin\DataType\EntityAdapter), NULL, NULL) 
#6 /var/www/cms/docroot/core/lib/Drupal/Core/TypedData/TypedData.php(132): Drupal\Core\TypedData\Validation\RecursiveValidator->validate(Object(Drupal\Core\Entity\Plugin\DataType\EntityAdapter)) 
#7 /var/www/cms/docroot/core/lib/Drupal/Core/Entity/ContentEntityBase.php(489): Drupal\Core\TypedData\TypedData->validate() 
#8 /var/www/cms/docroot/core/lib/Drupal/Core/Entity/ContentEntityForm.php(188): Drupal\Core\Entity\ContentEntityBase->validate() 
#9 /var/www/cms/docroot/core/modules/taxonomy/src/TermForm.php(141): Drupal\Core\Entity\ContentEntityForm->validateForm(Array, Object(Drupal\Core\Form\FormState)) 
#10 [internal function]: Drupal\taxonomy\TermForm->validateForm(Array, Object(Drupal\Core\Form\FormState)) 
#11 /var/www/cms/docroot/core/lib/Drupal/Core/Form/FormValidator.php(82): call_user_func_array(Array, Array) 
#12 /var/www/cms/docroot/core/lib/Drupal/Core/Form/FormValidator.php(275): Drupal\Core\Form\FormValidator->executeValidateHandlers(Array, Object(Drupal\Core\Form\FormState)) 
#13 /var/www/cms/docroot/core/lib/Drupal/Core/Form/FormValidator.php(118): Drupal\Core\Form\FormValidator->doValidateForm(Array, Object(Drupal\Core\Form\FormState), 'taxonomy_term_a...') 
#14 /var/www/cms/docroot/core/lib/Drupal/Core/Form/FormBuilder.php(591): Drupal\Core\Form\FormValidator->validateForm('taxonomy_term_a...', Array, Object(Drupal\Core\Form\FormState)) 
#15 /var/www/cms/docroot/core/lib/Drupal/Core/Form/FormBuilder.php(323): Drupal\Core\Form\FormBuilder->processForm('taxonomy_term_a...', Array, Object(Drupal\Core\Form\FormState)) 
#16 /var/www/cms/docroot/core/lib/Drupal/Core/Controller/FormController.php(73): Drupal\Core\Form\FormBuilder->buildForm(Object(Drupal\taxonomy\TermForm), Object(Drupal\Core\Form\FormState)) 
#17 /var/www/cms/docroot/core/modules/layout_builder/src/Controller/LayoutBuilderHtmlEntityFormController.php(39): Drupal\Core\Controller\FormController->getContentResult(Object(Symfony\Component\HttpFoundation\Request), Object(Drupal\Core\Routing\RouteMatch)) 
#18 [internal function]: Drupal\layout_builder\Controller\LayoutBuilderHtmlEntityFormController->getContentResult(Object(Symfony\Component\HttpFoundation\Request), Object(Drupal\Core\Routing\RouteMatch)) 
#19 /var/www/cms/docroot/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(123): call_user_func_array(Array, Array) 
#20 /var/www/cms/docroot/core/lib/Drupal/Core/Render/Renderer.php(580): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\@closure() 
#21 /var/www/cms/docroot/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(124): Drupal\Core\Render\Renderer->executeInRenderContext(Object(Drupal\Core\Render\RenderContext), Object(Closure)) 
#22 /var/www/cms/docroot/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(97): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext(Array, Array) 
#23 /var/www/cms/docroot/vendor/symfony/http-kernel/HttpKernel.php(169): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\@closure() 
#24 /var/www/cms/docroot/vendor/symfony/http-kernel/HttpKernel.php(81): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) 
#25 /var/www/cms/docroot/modules/contrib/simple_oauth/src/HttpMiddleware/BasicAuthSwap.php(68): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) 
#26 /var/www/cms/docroot/core/lib/Drupal/Core/StackMiddleware/Session.php(58): Drupal\simple_oauth\HttpMiddleware\BasicAuthSwap->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) 
#27 /var/www/cms/docroot/core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php(48): Drupal\Core\StackMiddleware\Session->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) 
#28 /var/www/cms/docroot/core/modules/page_cache/src/StackMiddleware/PageCache.php(106): Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) 
#29 /var/www/cms/docroot/core/modules/page_cache/src/StackMiddleware/PageCache.php(85): Drupal\page_cache\StackMiddleware\PageCache->pass(Object(Symfony\Component\HttpFoundation\Request), 1, true) 
#30 /var/www/cms/docroot/vendor/asm89/stack-cors/src/Asm89/Stack/Cors.php(49): Drupal\page_cache\StackMiddleware\PageCache->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) 
#31 /var/www/cms/docroot/core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php(48): Asm89\Stack\Cors->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) 
#32 /var/www/cms/docroot/core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php(51): Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) 
#33 /var/www/cms/docroot/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) 
#34 /var/www/cms/docroot/core/lib/Drupal/Core/DrupalKernel.php(718): Stack\StackedHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) 
#35 /var/www/cms/docroot/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request)) #36 @main. [dd.trace_id=9223372036854775807 dd.span_id=9223372036854775807]
`

## AC / Expected behavior
- [ ] As an admin  I expect to be able to save changes to a section taxonomy term.

## Screenshots
![image](https://user-images.githubusercontent.com/5752113/232178789-18e291de-9b6a-4ae7-92ee-da79d303f55a.png)

![image](https://user-images.githubusercontent.com/5752113/232179087-f896afdb-7f09-490c-bf72-f29db5914c48.png)

 ## Additional context
This is only affecting Admins right now and the sections taxonomy is not updated often, but still is critical because it is blocking a save and losing data in the process.

**Comment by ndouglas** [comment]
I believe [this commit](https://github.com/department-of-veterans-affairs/va.gov-cms/commit/eb5870ad194cf36d53d60309b329e63c0851fbfe) is where this issue started occurring.

I bisected and the issue does not appear prior to this commit, and appears consistently after it. I also reverted the commit in a test branch and saving the term subsequently works as expected. 

If I log the field item that causes the issue:

```php
\Drupal::logger('nate')->notice(json_encode((array) $item->getFieldDefinition()));
```

I see:

```
@"*entityTypeId":"base_field_override",
"*enforceIsNew":null,
"*typedData":null,
"*cacheContexts":["languages:language_interface"],
"*cacheTags":[],
"*cacheMaxAge":-1,
"*_serviceIds":[],
"*_entityStorages":[],
"*originalId":"taxonomy_term.administration.description",
"*status":true,
"*uuid":"7dec1ce4-e222-4e44-bb8d-0474612eae49",
"Drupal\\Core\\Config\\Entity\\ConfigEntityBaseisUninstalling":false,
"*langcode":"en",
"*third_party_settings":[],
"*_core":[],
"*trustedData":false,
"*dependencies":@
"config":["taxonomy.vocabulary.administration"],
"module":["text"],
"*isSyncing":false,
"*id":"taxonomy_term.administration.description",
"*field_name":"description",
"*field_type":"text_long",
"*entity_type":"taxonomy_term",
"*bundle":"administration",
"*label":"Description",
"*description":"",
"*settings":[],
"*required":false,
"*translatable":false,
"*default_value": [], "*default_value_callback":"",
"*fieldStorage":null,
"*itemDefinition":@,
"*constraints":@
"PreventAbsoluteCmsLinks":null,
"PreventLocalFileLinks":null,
"PreventProtocolRelativeLinks":null,
"PreventMediaViewLinks":null,
"PreventAbsoluteUrlsAsPathsInLinks":null,
"PreventVaGovDomainsAsPathsInLinks":null,
"PreventDomainsAsPathsInLinks":null,
"*propertyConstraints":[],
"*baseFieldDefinition":@
```

**Comment by ndouglas** [comment]
Looking at `config/sync/core.base_field_override.taxonomy_term.administration.description.yml`, we see:

```yaml
uuid: 7dec1ce4-e222-4e44-bb8d-0474612eae49
langcode: en
status: true
dependencies:
  config:
    - taxonomy.vocabulary.administration
  module:
    - text
id: taxonomy_term.administration.description
field_name: description
entity_type: taxonomy_term
bundle: administration
label: Description
description: ''
required: false
translatable: false
default_value: {  }
default_value_callback: ''
settings: {  }
field_type: text_long
```

For the `validate()` function, we have:

```php
  /**
   * {@inheritdoc}
   */
  public function validate($items, Constraint $constraint) {
    foreach ($items as $delta => $item) {
      $type = $item->getFieldDefinition()->getType();
      $fieldValue = $item->getValue();
      /** @var \Drupal\va_gov_backend\Plugin\Validation\Constraint\PreventAbsoluteCmsLinks $constraint */
      if ($type === 'text_long' && $fieldValue['format'] !== 'plain_text') {
        $this->validateHtml($fieldValue['value'], $constraint, $delta);
      }
      else {
        $this->validateText($fieldValue['value'], $constraint, $delta);
      }
    }
  }
```

So the `type` is indeed `text_long`, but there doesn't appear to be a `format` value set.

The ultimate issue is that `$fieldValue['value']` is `null`, not an empty string, so I think I can just put a ternary conditional with an empty string in there and make this a little safer.
