### ISSUE TITLE
PACT Wiz: Draft research plan

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#13324]
### User story
> _Describe the audience/user, enhancement or fix, and value / outcome desired._

**AS A** PO/PM
**I WANT** a solid research plan for the PACT Wizard
**SO THAT** we can engage research when ready.

### Notes / background

Danielle Thierry is a good resource for guidance on trauma-informed questions and approach

## Acceptance criteria

NOTE: Possible dependency on determining what tool will be used to prototype for testing 

- [x] Drafted user research plan

### Sprint 90 ACs - 5
- [x] Recruitment strategy and screening questions finalized and added to research plan
- [x] Wes reviewed research plan and feedback incorporated
- [x] Research plan shared with Danielle for feedback

### Sprint 91 
NONE - blocked by prototype

### Sprint 92 ACs - 3pts
- [ ] ~~Timeline section completed~~ - moved to Prototype
- [x] Shared research plan with Dave C, Amanda, and Danielle for feedback by Sept 8
- [x] Feedback from Dave C, Amanda, and Danielle incorporated 
- [ ] Received official approval from DaveC (on plan + conversation guide) for research ops

**Comment by jilladams** [comment]
Need @cindymerrill to help break down: what's practically possible before the prototyping tool selection, vs. after, for this ticket.

**Comment by cindymerrill** [comment]
@jilladams Before selecting a prototype tool, I can draft the research goals, questions and hypotheses. Methods, recruitment, and timeline probably need to wait.

**Comment by cindymerrill** [comment]
I completed a first draft of the research plan here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/pact-act-wizard/research/research-plan.md

Could I get your feedback on this, @wesrowe ?

**Comment by jilladams** [comment]
@cindymerrill just confirming that my last comment here is true, that prototyping is next before any other action on the research plan, and that's blocked bythe new news re: content needs / potential need for a different tool?

**Comment by cindymerrill** [comment]
Yes. I worked today to understand the new version of Danielle's content flow and now I finally understand it. Tomorrow I'll try to document what's needed to prototype it.

**Comment by wesrowe** [comment]
@cindymerrill, are you actively working on this this sprint? So many PAW balls in the air I can't keep track.

**Comment by cindymerrill** [comment]
I am not working on this because building the prototype is blocking it. And getting a Survey Monkey license is blocking the prototype. Did you see my [thread in slack](https://adhoc.slack.com/archives/C03EUQRCHGS/p1690826531380549) this morning? A6 IT scheduled a call with Survey Monkey for tomorrow (Tuesday 11:30-11:45 am PT), and it doesn't look good. @jilladams @wesrowe

**Comment by cindymerrill** [comment]
Scheduled a meeting with Danielle and @wesrowe on Aug 8 to discuss the following:
- Which versions of the results screens we should prototype
- Recruitment strategy to get research participants for whom the above results would be relevant
- Status of content in the results screens (in the Word doc on Sharepoint)--any more changes coming?

**Comment by cindymerrill** [comment]
@wesrowe and I had a super helpful meeting with Danielle; notes have been added in italics to my [logic flow/prototype doc on Sharepoint](https://dvagov-my.sharepoint.com/:w:/r/personal/cynthia_merrill_va_gov/Documents/PACT%20Act%20Wizard/PACT%20Act%20Wizard%20user%20flow%20%26%20prototyping.docx?d=w633a53c5387e4238a7701eab9f29c6aa&csf=1&web=1&e=he0M3f), in response to the thoughts and questions I came up with this morning before the meeting. Unfortunately we didn’t have much time in the meeting to discuss recruitment criteria, but we talked in detail about the results screens. 

Wes and I met afterwards to debrief and talk about recruitment, and we came up with more questions for Danielle, which I posed to her in slack and via comments in her content doc so she could respond async. She's already answered most of the questions in slack but not yet in the content doc. 

Next steps:

- [ ] I will work on updating the recruitment criteria in my research plan, per our meeting and input from Danielle. I'll also make updates to the research questions in the research plan, plus the question --> result flow spreadsheet I made.
- [ ] Wes/I need to explore prototyping one or two of the results screens, which we'll show to all research participants--even if their responses to the questions don't match. If we do this in CodePen or another code solution, we can hopefully make it accessible for screen reader users (like the question flow in the survey tool will be). The need for accordions and multiple levels of headers make it impossible to build the most complicated results screens in a survey tool.

FYI @jilladams

**Comment by wesrowe** [comment]
@cindymerrill, FYSA an update from FE refinement today – we cut a [FE implementation ticket](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14729) for the results screens. Recommendation is to build it on Staging like we did for New Homepage, but will try to confirm that path asap. (2nd choice: CodePen.) Further discussion of the eng approach belongs in that ticket.

**Comment by cindymerrill** [comment]
Still waiting for response from Danielle on recruitment questions. I plan to write up what I know early next week before the sprint ends. @jilladams @wesrowe

**Comment by jilladams** [comment]
Danielle is now on PTO through 8/21, returning 8/22.

**Comment by cindymerrill** [comment]
Revised Recruitment section per meetings and slack exchanges with Danielle. Also revised Research questions and Hypotheses.

Shared in slack for review-- @wesrowe now and Danielle when she's back from PTO. FYI @jilladams

**Comment by wesrowe** [comment]
@cindymerrill, I don't see a question about rural location – is that something Perigean already knows?

**Comment by wesrowe** [comment]
otherwise looks good to me!

**Comment by cindymerrill** [comment]
@wesrowe Yes, there's no need for a screening question for rural location because that info is already in Perigean's recruitment database

**Comment by jilladams** [comment]
@cindymerrill @wesrowe I counted 5 pts for Sprint 90, and removed estimate. Need to re-estimate for post-90 ACs.

**Comment by jilladams** [comment]
https://dsva.slack.com/archives/C52CL1PKQ/p1692636616972079?thread_ts=1692631800.339859&cid=C52CL1PKQ 

Current draft timing for research:

![image (29)](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/85581471/b9e5fbf3-f233-4f94-90ba-c1587ce0243b)

**Comment by cindymerrill** [comment]
@jilladams @wesrowe @aklausmeier Slight update to account for my PTO on the Jewish holiday of Yom Kippur: 
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/69914583/1f14f5ab-ebef-4b2b-96da-ce0eb1118127)

**Comment by jilladams** [comment]
From S92 planning: 
* Timeline is the only outstanding content, hinged on completion of the prototype
* Dave, Danielle, Amanda can / should go ahead and review the current state of the Research plan

@cindymerrill will send out the plan for reviews, with request to deliver feedback by Fri 9/8 COB if possible or request a date by which feedback will be sent.

**Comment by cindymerrill** [comment]
Shared the research plan for feedback from Dave, Danielle, and Amanda by 9/8 COB if possible via slack with a Word doc on SharePoint for feedback: https://dvagov-my.sharepoint.com/:w:/g/personal/cynthia_merrill_va_gov/ESDyN7hanmBGkAwgNjfKG3ABF4qG80mghJpVAGSca2ZySQ?e=fhArIy

**Comment by cindymerrill** [comment]
Received feedback in the doc from Dave Conlon, replied, and incorporated all of his suggestions except for one, which I left him a question about.

**Comment by aklausmeier** [comment]
Reviewed and added comments in research plan draft Word doc.

**Comment by cindymerrill** [comment]
Reviewed feedback from @aklausmeier , replied, and incorporated her suggestions.

**Comment by cindymerrill** [comment]
Reviewed feedback from Danielle, replied, and incorporated her suggestions.

**Comment by cindymerrill** [comment]
PACT Act Wizard research plan [on github](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/pact-act-wizard/research/research-plan.md) updated per feedback received on SharePoint and timeline revisited. 

Assumption for the above timeline: I will get feedback and approval for the [conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/pact-act-wizard/research/research-plan.md) and the [prototype](https://www.surveymonkey.com/r/KKVHSFV), incorporate feedback on both, and _launch recruiting this Friday_. This depends on timely reviews from @wesrowe , @DanielleThierryUSDSVA , @davidconlon , and an accessibility decision from @laflannery . FYI @jilladams

**Comment by laflannery** [comment]
From an accessibility standpoint - if we are looking at strictly screen readers users - SurveyMonkey is not a viable tool and I do not believe that SurveyMonkey support is going to have anything remediated in a short amount of time in order to make this usable. However, if it is decided that research will go forward without screen reader users, I do not have any objection to the current prototype.

**Comment by cindymerrill** [comment]
Moved the review and approval AC's into https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15244, so this ticket can be closed.
