### ISSUE TITLE
Redirect Request for Newington Vet Center Outstation -> Manchester Vet Center

### ISSUE THREAD

**Issue by stefaniefgray** [department-of-veterans-affairs/va.gov-cms#13330]
### Instructions
(Note: This issue will be used from initial request through implementation to ensure all individuals working on this are notified of status updates.  Please do not create multiple issues to track different steps.)
- [x] Notify VA stakeholders as appropriate.
- [x] Link the related facility closure / rename issue.
- [x] Create a URL redirect in the [devops](https://github.com/department-of-veterans-affairs/devops) repo in `ansible/deployment/config/revproxy-vagov/vars/redirects.yml`
- [x] Validate that the URL redirect is deployed.

### Implementation date
When does this request need to be live:

### Redirects
| Current URL  |  Redirect Destination or New URL |
| ---  |  --- |
| https://www.va.gov/manchester-vet-center/newington-outstation | https://www.va.gov/manchester-vet-center |

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [ ] `Public Websites`
- [x] `Facilities`
- [x] `User support`

**Comment by omahane** [comment]
The redirect has been deployed.

**Comment by stefaniefgray** [comment]
@omahane You rock! 🎸
