### ISSUE TITLE
COVID-19 Clean Up: Implement Flipper Removal 

### ISSUE THREAD

**Issue by kmariepat-cityfriends** [department-of-veterans-affairs/va.gov-cms#13331]
#### Background 

#11592 and #11593 are discovery cards looking into criteria to remove the flippers they reference

##### Acceptance Criteria 
- [ ] I expect the following PR are created for the following branches to reviewed and follow existing team QA process: 

- [ ] vets-website - va-11592-remove-covid-vaccine-query-flipper
- [ ] vets-api - va-11592-remove-covid-vaccine-query-feature

**Comment by eselkin** [comment]
There seem to be branches connected with these two desired actions. 

`vets-website` has a `va-11592-remove-covid-vaccine-query-flipper` branch which was mergeable with a resolution.

and 

`vets-api` has a branch `va-11592-remove-covid-vaccine-query-feature`
but that branch says it can't be merged. I created a new branch (`vamc-11592-remove-covid-vaccine-query-feature-mergeable`) with the same section of `features.yml` removed. Not sure how to test when the feature is removed.

**Comment by jilladams** [comment]
@eselkin couple things here: 
1. Reminder to update ticket status when you're done done. 
2. Flippers are weird. You may have heard this already elsewhere but: there is a process on the Platform side that automagically _can_ clean up the Flipper UI. It serves dual purpose, as far as I understand it, and will both remove references to removed Flippers from the Flipper UI, as well as update the status of any given flipper as needed based on config. (Layman's terms, Platform would probably not agree with my description of that.) When it runs, it has been known to problematically flip some flippers Off or On, in ways that are not desired. So: that job is disabled. But this means that while the job is disabled, any flippers removed from code will _not_ be removed from the flipper UI. They will still show up as an option that can be selected on https://api.va.gov/flipper/features. 

So, re: #1, how to validate done-ness is weird in light of #2. If you have questions or want to discuss, holler.
