### ISSUE TITLE
Research: Create VBA Veteran Facing Usability Research Plan

### ISSUE THREAD

**Issue by kmariepat-cityfriends** [department-of-veterans-affairs/va.gov-cms#13338]
#### Background

- Jordan's VBA design - https://sketch.com/s/891d33ae-152d-471c-ab5d-9aedf89cf6ff
- VBA Veteran Research Findings (generative) - https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/regional-offices/research/2022-8-veteran-facing/research-findings.md
- VBA Public Contact Staff Research Findings - https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/regional-offices/research/2022-9-public-contact/research-findings.md#details-of-findings---veteran-preparation
- High level overview of VBA MVP scope meeting recording 

#### Possible recruitment considerations
- Disability compensation is the [primary benefit](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/regional-offices/research/2022-9-public-contact/research-findings.md#2---public-contact-staff-are-primarily-equipped-to-assist-with-the-benefit-of-disability-compensation) handled at these offices - do we want to get users who do/do not have that (vs all/any benefits) 

#### Goals (what are we trying to learn at a high level)
- "We need to get feedback on this because"

#### Things to understand 
- What phone numbers do veterans want and what do they expect to do with that phone number?
- How often are people calling the main number for a given regional office and what are they calling about?
- Why are Veterans generally calling the main phone number? 
- Do users understand the [distinction between virtual and in-person appointments](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/regional-offices/research/2022-9-public-contact/research-findings.md#5---there-are-few-if-any-tasks-that-require-a-veteran-to-be-physically-present-at-a-public-contact-office)?
- When prompted with specific tasks (e.g. find out your Education benefit balance), can Veterans navigate to the correct service accordion and find the [correct next steps](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/regional-offices/research/2022-9-public-contact/research-findings.md#3---public-contact-staff-primarily-assist-with-the-task-of-applying-for-benefits)? (e.g. calling Muskogee Education center as opposed to visiting local Regional Office) 

#### Design Note
- The research questions here will determine what areas of Jordan's design need to be made clickable for prototype
- what tasks do we want to make available in prototype 

### Acceptance Criteria

- [x] Research plan drafted
- [ ] Research plan shared with team and PO(s) for feedback, and feedback incorporated
- [x] Recruiting criteria discussed with @davidmpickett (who's providing content for prototype), team, and PO(s)
- [ ] Research timeline discussed with PM, DM, Design, POs

**Comment by kmariepat-cityfriends** [comment]
Link recording from most recent design review meeting here:

**Comment by cindymerrill** [comment]
@kmariepat-cityfriends As promised, here's a link to the last research plan I wrote so you can see the types of information I'll be including for the VBA research: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/income-limits-app/research/2023-01-income-limits-usability/research-plan.md

**Comment by kmariepat-cityfriends** [comment]
@cindymerrill I populated a new section in the card, titled things to understand. Not quite hypotheses but questions we want to know the answer to coming out of this research effort. The first 3 were mentioned by Dave C. in the design review meeting we had yesterday (the recording to that meeting is in an above comment)

I will continue refining this card to include an overarching goal statement. This will be in place and ready to pick up by 11 am CT Monday, ill tag you on the card. Ultimately I want to run some language by Michelle in a touchbase we have Monday.

**Comment by cindymerrill** [comment]
Today I watched the high level overview of VBA MVP scope meeting recording that Dave Pickett shared with me.

**Comment by cindymerrill** [comment]
Today I watched the recording of last week's design review meeting

**Comment by cindymerrill** [comment]
@kmariepat-cityfriends The **Things to understand** section in this card's description is helpful, though I think (per last week's design review meeting) that two of the questions are for the pilot with content editors, not for Veterans in my research:

- How often are people calling the main number for a given regional office and what are they calling about?
- Why are Veterans generally calling the main phone number?

**Comment by kmariepat-cityfriends** [comment]
Notes from design review meeting:

For Usability:
- what phone numbers are Veterans calling and why
- get a sense of if Veteran's know what a regional office is and what they might do there 
- get a sense if Veterans feel the in page navigation experience is sufficient; impression of the page in general 
- include screening question: Are Veterans aware of what a regional office is? Can use more generic language: benefits facility... @davidmpickett to send screening questions from initial research
- qualifying candidates: must include both populations of people that have visited a regional office and those that haven't 
- need to test mobile first 
- How would Veteran's expect to interact with top task action links, are these the correct top tasks

For Design:
- https://ask.va.gov/ top task change to "get more benefit information"
- make `on this page links` functional in the prototype 
- make operating status clickable in prototype, show a description referencing that the main door is closed 
- show actual phone number and not x's
- verify the accuracy of information presented; the existing benefits websites should be the source of truth
- make prototype clickable action links

**Comment by cindymerrill** [comment]
@kmariepat-cityfriends @davidmpickett What github folder should I put my research plan into?

**Comment by davidmpickett** [comment]
Create a new subfolder here: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/facilities/regional-offices/research

**Comment by davidmpickett** [comment]
Screening questions and other recruitment criteria for participants in the generative research with Veterans: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/regional-offices/research/2022-8-veteran-facing/research-plan.md#recruitment

**Comment by davidmpickett** [comment]
> For Usability:
> 
> * what phone numbers are Veterans calling and why
> * get a sense of if Veteran's know what a regional office is and what they might do there
> * include screening question: Are Veterans aware of what a regional office is? Can use more generic language: benefits facility... @davidmpickett to send screening questions from initial research

**Comment by davidmpickett** [comment]
Related slack thread: https://dsva.slack.com/archives/C0FQSS30V/p1683129628076269

**Comment by cindymerrill** [comment]
Is there a Product Brief for this work? If so, I'd like to add a link to it from my research plan. @kmariepat-cityfriends @davidmpickett

**Comment by cindymerrill** [comment]
I started drafting my research plan here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/regional-offices/research/2023-06-veteran-facing/research-plan.md

I'm hoping to fill in some gaps from tomorrow's meeting (May 5).

**Comment by davidmpickett** [comment]
Product brief: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/facilities/regional-offices

**Comment by kmariepat-cityfriends** [comment]
Notes from 5/5 Usability review meeting"
- Make sure Veterans understand what the hours represent 
- Any confusion or comments on two sets of hours 
- Do people understand what their options are for getting service

**Comment by cindymerrill** [comment]
Updated research plan per VBA design/research meeting this morning. Met with Jordan and Dave P, documented VBA design work needed before usability testing [in slack](https://dsva.slack.com/archives/C0FQSS30V/p1683328127965399).

**Comment by jilladams** [comment]
@kmariepat-cityfriends @cindymerrill this ticket doesn't have ACs so am not sure how to determine if it's ready to close or not. 
@cindymerrill can you make checkboxes for any last steps you need in order for this to close?

**Comment by cindymerrill** [comment]
I will add some tomorrow...

**Comment by cindymerrill** [comment]
Shared my draft research plan for feedback in the Facilities channel [in slack](https://dsva.slack.com/archives/C0FQSS30V/p1684272129555449). The _Timeline_ section is blank because I don’t know when the design/content will be filled in enough about services that I can draft user tasks and discuss prototyping. I'll look for feedback in the slack thread and/or a meeting on or after I return from PTO on Wed May 24.

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/regional-offices/research/2023-06-veteran-facing/research-plan.md

**Comment by kmariepat-cityfriends** [comment]
Note: 
- Get reaction from Veterans on service taxonomy terms determined in this card: Propose VBA terms for Service Taxonomy (new and existing) #11266

**Comment by cindymerrill** [comment]
@kmariepat-cityfriends @davidmpickett What would you like to learn from Veterans about VBA terms in the service taxonomy?

**Comment by cindymerrill** [comment]
Updated recruitment section in the [research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/regional-offices/research/2023-06-veteran-facing/research-plan.md). Now only thing missing is the timeline, which depends on the completion/approval of the design and coordination with the tasks in the conversation guide. @kmariepat-cityfriends @ALogsdon3

**Comment by cindymerrill** [comment]
Haven't gotten any recent feedback on recruiting from @davidmpickett as specified in the Acceptance Criteria, and now he's on PTO so I recommend dropping this criterion. Michelle Middaugh was fine with the recruiting criteria. @kmariepat-cityfriends

**Comment by cindymerrill** [comment]
CANCEL the above request because @davidmpickett just provided feedback on the recruitment criteria. Thank you!

**Comment by jilladams** [comment]
Lane was affected by workflow integration. Moving back to In Progress.

**Comment by cindymerrill** [comment]
Discussed VBA research tasks with Michelle and Alexis today. Then updated the [research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/regional-offices/research/2023-06-veteran-facing/research-plan.md) and [conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/regional-offices/research/2023-06-veteran-facing/conversation-guide.md) accordingly.

**Comment by cindymerrill** [comment]
Just updated the [VBA conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/regional-offices/research/2023-06-veteran-facing/conversation-guide.md) with updated user tasks, a trauma-informed protocol, and new video permission. @ALogsdon3 @davidmpickett @Dottisea

**Comment by jilladams** [comment]
@cindymerrill after more thinking I agree with you: I dont' know why we are carrying this sprint to sprint when it's blocked. I'm going to move out of S89, we can pin down the hard blockers in UX Refinement on Thurs, and pull it back in when it's unblocked.

**Comment by cindymerrill** [comment]
The research plan is done and has been shared with the team and PO for feedback and approval.
