### ISSUE TITLE
UXR: Identify potential participants for alt text usability study

### ISSUE THREAD

**Issue by joagnitti** [department-of-veterans-affairs/va.gov-cms#13352]
## Description
Related to ticket [#13107](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13107). We need to identify who we would like to reach out to to participate in this study. 

## Acceptance Criteria
- [x] Add eligible participants to Airtable research database from editorial research survey (and crosscheck for previous participation)
- [x] Cross check names to make sure they still work for the VA
- [x] Create a list of potential participants 

### Team
Please check the team(s) that will do this work.

- [x] `CMS Team`
- [ ] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`

**Comment by productmike** [comment]
@joagnitti adding in another AC to account for VHA DM review as would think it'll have to go through similar cycle as the editor trust survey

**Comment by joagnitti** [comment]
@productmike it might actually be a lot simpler for this round! we have a list of about 39 editors who have opted in to participate in research studies, so i'd be selecting from that panel. so i'm not sure if we'd have to go through vha dm, but maybe we could run a review with erika once we have identified candidates for this study?

**Comment by joagnitti** [comment]
@productmike just verified with Erika... we do _not_ need to consult with VHA DM in order to contact anyone who has already opted in to the research panel 🙌 🎉
