### ISSUE TITLE
Alert language audit 

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#1335]
## Description
Work with @rtwell on the alert audit, including figuring out things are currently named. 

## Acceptance Criteria
- [x] Initial background mtg w/ Ryan
- [ ] Scope of audit is identified (from where will we draw examples? How do we know we are done)
- [ ] Attributes for auditing identified
- [ ] Attributes audited for each kind of alert
- [ ] Validated with stakeholders (FE folk, content folk, CMS team)
- [ ] Next steps identified

# Artifacts
* [Ryan's Alerts Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1584997699567/7efd2f32ea136fea3d6f9d3e7b035ecacbe8ec72)
* [Working doc](https://docs.google.com/document/d/11onnJ1NzFIBlzDyzQqzTB9PQ4pqwbZP9M4Hd6WBEIPQ/edit)
* [AT inventory](https://airtable.com/invite/l?inviteId=inv35LUyaArFmi481&inviteToken=655dd3df41e7f6f941d0f76041b348dc00efe42385b54e45b4e598311e77e03d)

**Comment by EWashb** [comment]
no longer within scope
