### ISSUE TITLE
Create a reusable Github ticket template for designers to update design system documentation.

### ISSUE THREAD

**Issue by BlakeOrgan** [department-of-veterans-affairs/va.gov-cms#13350]
## Description
One of the steps in the [ticket template for updates to the the design system](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/new?assignees=BlakeOrgan&labels=Needs+refining%2C+CMS+Team%2C+CMS+design+system&template=cms-design-system-update-or-addition.md&title=Update%2Fadd+%3Cinsert+topic+here%3E+in+the+design+system) includes a step for creating a ticket for designers to create or update documentation about the approved design. A reusable ticket template needs to be created so that we can link the ticket template to update documentation to the design system update ticket because right now there is just a placeholder for where the documentation ticket should be created.

We will also need to define where the documentation should be housed. Right now it is in Confluence, but concerns have been brought up about that not being open to the entire VA, so it might not be scalable as we grow.

## Acceptance Criteria
- [x] Write the template
- [x] Define where the documentation should be housed.
- [x] Add the template to the template repo
- [x] Link the ticket template in the design system update template

### Team
Please check the team(s) that will do this work.

- [x] `CMS Team`
- [ ] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`

**Comment by productmike** [comment]
Shifting out of this sprint due to capacity and confluence changes. Aiming to address by next sprint.

**Comment by BlakeOrgan** [comment]
Ticket template has been created and can be viewed here:

https://github.com/department-of-veterans-affairs/va.gov-cms/issues/new?assignees=BlakeOrgan&labels=CMS+design+system%2C+CMS+design%2C+CMS+Team%2C+Needs+refining&projects=&template=cms-design-system-documentation.md&title=Update%2Fadd+%3Cinsert+topic+here%3E+in+the+design+system+documentation.
