### ISSUE TITLE
VAMC Facility name change: Gainesville Sixty-Fourth Street 1 VA Clinic [Ready to go]

### ISSUE THREAD

**Issue by stefaniefgray** [department-of-veterans-affairs/va.gov-cms#13369]
## Intake
- [x] What triggered this runbook? (Flag in CMS, Help desk ticket, Product team, VHA Digital Media)
Trigger: Flagged facilities review - https://docs.google.com/spreadsheets/d/1TR-5sEWaEj8GsyHYCPYbaylIRQDnXDVsGp80O8YLESw/edit?usp=sharing

- [x] Link to associated help desk ticket (if applicable)
Help desk ticket: https://va-gov.atlassian.net/browse/VAHELP-5712

- [x] Name of submitter (if applicable)
Submitter: @stefaniefgray 

- [x] If the submitter is an editor, send them links to any relevant KB articles for the VAMC product. Let them know that facility changes can take between 75 days and 4 months after submitting a request, according to VAST administrators.
KB articles: Not needed

- [x] Link to facility in production:
Facility link: https://prod.cms.va.gov/north-florida-health-care/locations/gainesville-sixty-fourth-street-1-va-clinic

Live URL: https://www.va.gov/north-florida-health-care/locations/gainesville-sixty-fourth-street-1-va-clinic/
Facility Locator ID: vha_573QC

Backstory: https://dsva.slack.com/archives/C0FQSS30V/p1682004462645399

Facility Locator re-direct is not needed -- Facility Locator goes to proper URL. 

The only difference within this URL is that it previously did not have a hyphen; now it does. See revision history for details.

## Acceptance criteria
No remaining issues hanging from space turning to hyphen within numerical title.

#### CMS help desk steps
What happens: The name change is made in VAST, that syncs to Lighthouse which syncs to Drupal.
- [x] 1. Check that the title change in name field on the VACM node has shown up in Drupal.
- [x] 2. Create a [URL change request](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/new?assignees=&template=runbook-facility-url-change.md&title=URL+Change+for%3A+%3Cinsert+facility+name%3E), changing the entry from the old facility URL to the new facility URL. (**Note: The URL change request ticket blocks the completion of this ticket.**)

Facility Locator re-direct not needed. Facility Locator goes to proper URL as of 4/20/2023.

#### CMS engineer steps
- [x] 3. Execute the steps of the URL change request ticket from step 2.
- [x] 4. Locate the newly renamed VAMC Facility (https://prod.cms.va.gov/admin/content/bulk) Search by new name
- [x] 5. Updates URL alias for this facility
- [x] 6. Resave this facility
- [x] 7. Make bulk alias changes to facility service nodes. (https://prod.cms.va.gov/admin/content/bulk?type=health_care_local_health_service)
- [x] 8. Bulk save fixed titles to facility service nodes. (https://prod.cms.va.gov/admin/content/bulk?type=health_care_local_health_service)
- [x] 9. Update menu title for facility
- [x] 10. May also need to directly edit the VAMC System menu to alpha sort the menu item after the title changes
- [x] 11. Update Alt text for facility image, if relevant
- [x] 12. Update Meta description (TBD: some backwards compatibility for SEM, by including something like ", formerly known as [previous name]".
- [x] 13. Edit facility node and remove flag `Changed name` then save node (with moderation state = published)

#### CMS Help desk (wrap up)
- [ ] 14. Notify editor and any other stakeholders

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [ ] `Public Websites`
- [x] `Facilities`
- [x] `User support`

**Comment by stefaniefgray** [comment]
Followed up with VA North Florida / South Georgia editor and teammates in https://va-gov.atlassian.net/browse/VAHELP-5712

**Comment by stefaniefgray** [comment]
Confirmed name change in https://va-gov.atlassian.net/browse/VAHELP-5712

**Comment by kmariepat-cityfriends** [comment]
@stefaniefgray I see the step is checked off, but I can't find the URL change request card, can you confirm if you made one, before I make a dupe

**Comment by stefaniefgray** [comment]
@kmariepat-cityfriends I don't think one is needed since the URL linked within the Facility Locator goes to the correct location within the CMS already, but I'll check with @omahane to verify

**Comment by stefaniefgray** [comment]
Informed editor that facility lacks health services, they should be added ASAP: https://va-gov.atlassian.net/browse/VAHELP-5712

**Comment by stefaniefgray** [comment]
Reminded editor about missing health services -- can continue to follow-up via Jira

Closing
