### ISSUE TITLE
URL Change for: Howell VA Clinic [Ready to go]

### ISSUE THREAD

**Issue by stefaniefgray** [department-of-veterans-affairs/va.gov-cms#13377]
Original ticket: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10825 

### Implementation date
When does this request need to be live:
ASAP

### Instructions for URL redirect
**No redirect required**

#### URL Redirect
| Current URL  |  Redirect Destination or New URL |
| ---  |  --- |
| https://www.va.gov/find-locations/facility/vha_506GE | https://www.va.gov/ann-arbor-health-care/locations/howell-va-clinic/ |

### Instructions for canonical URL change
- [x] Verify that the new URL for the facility is published and accessible on VA.gov.
- [x] Update the [CSV in Lighthouse](https://github.com/department-of-veterans-affairs/lighthouse-facilities/blob/master/facilities/src/main/resources/websites.csv) with the changed URL, maintaining the sorted order of the Facility API IDs.
- [x] Create a PR in the [lighthouse-facilities repo](https://github.com/department-of-veterans-affairs/lighthouse-facilities), tagging the Lighthouse team.
- [x] Post a message in the #api-facilities channel in Slack, with an @mention to a Lighthouse team member.
- [x] Validate that the change has deployed by checking that the Facility Locator has been updated with the new url.

#### URL change example (update with actual ID and URL)
| Facility API ID  |  Full VA.gov URL |
| ---  |  --- |
| vha_506GE | https://www.va.gov/ann-arbor-health-care/locations/howell-va-clinic// |

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [ ] `Public Websites`
- [x] `Facilities`
- [x] `User support`

**Comment by omahane** [comment]
CSV has been deployed and Facility Locator is updated.
