### ISSUE TITLE
URL Change for: Knox West VA Clinic [Awaiting CSV]

### ISSUE THREAD

**Issue by stefaniefgray** [department-of-veterans-affairs/va.gov-cms#13378]
### Instructions for URL redirect

**TEMPORARY: Until the CSV can be deployed by Lighthouse. Will [revert](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14400) after that.**
(Note: This issue will be used from initial request through implementation to ensure all individuals working on this are notified of status updates.  Please do not create multiple issues to track different steps.)
UPDATE (2023-07-31): This redirect strategy did not work. Lighthouse merged this change in.
- [x] Notify VA stakeholders as appropriate.
- [x] Link the related facility closure / rename issue.
- [x] Create a URL redirect in the [devops](https://github.com/department-of-veterans-affairs/devops) repo in `ansible/deployment/config/revproxy-vagov/vars/redirects.yml`
- [x] Add the "Awaiting redirect" flag to the facility node with a revision log message that includes a link to this ticket, preserving the node's current moderation state.
- [ ] Redirects deploy weekly on Wed. at 10am ET, or by requesting OOB deploy (of the revproxy job to prod) in #vfs-platform-support. After deploy, validate that the URL redirect is deployed. (Note: In the event of a facility closure or a name change,  validate that this occurs before making the Lighthouse csv changes.)
- [ ] Update this ticket with a comment that the redirect has been deployed.
- [ ] Remove the "Awaiting redirect" flag on the facility node with a revision log message that includes a link to this ticket, preserving the node's current moderation state.
- [ ]  Notify helpdesk via comment on ticket or Slack message in #cms-support that changes are ready for review.

-----

### Implementation date
When does this request need to be live:
Whenever clinic is published -- see original ticket https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10826

#### URL Redirect
| Current URL  |  Redirect Destination or New URL |
| ---  |  --- |
| https://www.va.gov/find-locations/facility/vha_621QG | https://www.va.gov/mountain-home-health-care/locations/knox-west-va-clinic/ |
-----

### Instructions for canonical URL change
- [x] Verify that the new URL for the facility is published and accessible on VA.gov.
- [x] Update the [CSV in Lighthouse](https://github.com/department-of-veterans-affairs/lighthouse-facilities/blob/master/facilities/src/main/resources/websites.csv) with the changed URL, maintaining the sorted order of the Facility API IDs.
- [x] Create a PR in the [lighthouse-facilities repo](https://github.com/department-of-veterans-affairs/lighthouse-facilities), tagging the Lighthouse team.
- [x] Post a message in the #api-facilities channel in Slack, with an @mention to a Lighthouse team member.
- [x] Validate that the change has deployed by checking that the Facility Locator has been updated with the new url.

#### URL change example (update with actual ID and URL)
| Facility API ID  |  Full VA.gov URL |
| ---  |  --- |
| vha_621QG | https://www.va.gov/mountain-home-health-care/locations/knox-west-va-clinic/ |

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [ ] `Public Websites`
- [x] `Facilities`
- [x] `User support`

**Comment by TroyA6** [comment]
@omahane @stefaniefgray As of 5/24/23, appears to still be waiting for editor

**Comment by stefaniefgray** [comment]
@jilladams @kmariepat-cityfriends Here's a basic CSV update ready for this sprint -- linked new facility ticket can be closed once completed: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10826

**Comment by omahane** [comment]
This change has now been deployed. (cc: @stefaniefgray @jilladams )

**Comment by stefaniefgray** [comment]
@omahane Looks good! Closing
