### ISSUE TITLE
URL Change for: Corpus Christi West Point VA Clinic

### ISSUE THREAD

**Issue by stefaniefgray** [department-of-veterans-affairs/va.gov-cms#13379]
⚠️  NO URL RE-DIRECT NEEDED ⚠️ 

Simply needs to be updated within Lighthouse CSV / canonical URL change

-----

### Implementation date
When does this request need to be live:
Whenever clinic is published -- see original ticket https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12000

### Instructions for canonical URL change
- [x] Verify that the new URL for the facility is published and accessible on VA.gov.
- [x] Update the [CSV in Lighthouse](https://github.com/department-of-veterans-affairs/lighthouse-facilities/blob/master/facilities/src/main/resources/websites.csv) with the changed URL, maintaining the sorted order of the Facility API IDs.
- [x] Create a PR in the [lighthouse-facilities repo](https://github.com/department-of-veterans-affairs/lighthouse-facilities), tagging the Lighthouse team.
- [x] Post a message in the #cms-lighthouse channel in Slack, with an @mention to a Lighthouse team member.
- [x] Add the "Awaiting CSV" flag to the facility node with a revision log message that includes a link to this ticket.
- [x] Validate that the change has deployed by checking that the Facility Locator has been updated with the new url.
- [x] Update this ticket with a comment that the CSV change has been deployed.
- [x] Remove the "Awaiting CSV" flag to the facility node with a revision log message that includes a link to this ticket.

#### URL change example (update with actual ID and URL)
| Facility API ID  |  Full VA.gov URL |
| ---  |  --- |
| vha_740QB | https://www.va.gov/texas-valley-health-care/locations/corpus-christi-west-point-va-clinic |

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [ ] `Public Websites`
- [x] `Facilities`
- [x] `User support`

**Comment by stefaniefgray** [comment]
Per https://va-gov.atlassian.net/browse/VAHELP-5227, editor published homepage instead of saving as "Draft" as requested

Editor also published homepage without any VAMC Facility Health Services added, which impacts patient safety

**Comment by TroyA6** [comment]
@omahane @stefaniefgray Jira Ticket [VAHELP-5227](https://va-gov.atlassian.net/browse/VAHELP-5227) is flagged as Waiting for Editor - No Health Services have been added

**Comment by stefaniefgray** [comment]
Editor added health services

Can be closed once CSV is updated: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13379

cc: @omahane

**Comment by omahane** [comment]
The CSV has been deployed.

**Comment by stefaniefgray** [comment]
Confirmed complete -- closing!

**Comment by jilladams** [comment]
Was reported incomplete in S86, added to S87 to close out reporting.
