### ISSUE TITLE
URL Change for: Garden of the Gods VA Clinic

### ISSUE THREAD

**Issue by stefaniefgray** [department-of-veterans-affairs/va.gov-cms#13376]
⚠️  NO URL RE-DIRECT NEEDED ⚠️ 

Simply needs to be updated within Lighthouse CSV / canonical URL change

-----

### Implementation date
When does this request need to be live: As soon as possible
See original new facility ticket: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10818

### Instructions for canonical URL change
- [x] Verify that the new URL for the facility is published and accessible on VA.gov.
- [x] Update the [CSV in Lighthouse](https://github.com/department-of-veterans-affairs/lighthouse-facilities/blob/master/facilities/src/main/resources/websites.csv) with the changed URL, maintaining the sorted order of the Facility API IDs.
- [x] Create a PR in the [lighthouse-facilities repo](https://github.com/department-of-veterans-affairs/lighthouse-facilities), tagging the Lighthouse team.
- [x] Post a message in the #cms-lighthouse channel in Slack, with an @mention to a Lighthouse team member.
- [x] Add the "Awaiting CSV" flag to the facility node with a revision log message that includes a link to this ticket.
- [x] Validate that the change has deployed by checking that the Facility Locator has been updated with the new url.
- [x] Update this ticket with a comment that the CSV change has been deployed.
- [x] Remove the "Awaiting CSV" flag to the facility node with a revision log message that includes a link to this ticket.

#### URL change example (update with actual ID and URL)
| Facility API ID  |  Full VA.gov URL |
| ---  |  --- |
| vha_554QF | https://www.va.gov/eastern-colorado-health-care/locations/garden-of-the-gods-va-clinic |

**Comment by stefaniefgray** [comment]
See most recent notes in https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10818

**Comment by omahane** [comment]
The CSV has been deployed.

**Comment by stefaniefgray** [comment]
Confirmed complete! Closing

**Comment by jilladams** [comment]
Was reported incomplete in S86, added to S87 to close out reporting.
