### ISSUE TITLE
VAMC Facility name change: Gainesville Twenty Third Avenue VA Clinic -> Gainesville 1 VA Clinic [Ready to go]

### ISSUE THREAD

**Issue by stefaniefgray** [department-of-veterans-affairs/va.gov-cms#13373]
## Intake
- [x] What triggered this runbook? (Flag in CMS, Help desk ticket, Product team, VHA Digital Media)
Trigger: Flagged facilities review - https://docs.google.com/spreadsheets/d/1TR-5sEWaEj8GsyHYCPYbaylIRQDnXDVsGp80O8YLESw/edit?usp=sharing

- [x] Link to associated help desk ticket (if applicable)
Help desk ticket: https://va-gov.atlassian.net/browse/VAHELP-5712

- [x] Name of submitter (if applicable)
Submitter: @stefaniefgray 

- [x] If the submitter is an editor, send them links to any relevant KB articles for the VAMC product. Let them know that facility changes can take between 75 days and 4 months after submitting a request, according to VAST administrators.
KB articles: Not needed

- [x] Link to facility in production:
Facility link: https://prod.cms.va.gov/north-florida-health-care/locations/gainesville-twenty-third-avenue-va-clinic

Facility Locator ID: vha_573QF

#### CMS help desk steps
What happens: The name change is made in VAST, that syncs to Lighthouse which syncs to Drupal.
- [x] 1. Check that the title change in name field on the VACM node has shown up in Drupal.
- [x] 2. Create a [URL change request](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/new?assignees=&template=runbook-facility-url-change.md&title=URL+Change+for%3A+%3Cinsert+facility+name%3E), changing the entry from the old facility URL to the new facility URL. (**Note: The URL change request ticket blocks the completion of this ticket.**)

https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13372

(Redirects deploy weekly on Wed. at 10am ET, or by requesting OOB deploy (of the revproxy job to prod) in #vfs-platform-support. Coordinate the following items below and canonical URL change after URL change ticket is merged, deployed, and verified in prod.)

#### CMS engineer steps
- [x] 3. Execute the steps of the URL change request ticket from step 2.
- [x] 4. Locate the newly renamed VAMC Facility (https://prod.cms.va.gov/admin/content/bulk) Search by new name
- [x] 5. Updates URL alias for this facility
- [x] 6. Resave this facility
- [x] 7. Make bulk alias changes to facility service nodes. (https://prod.cms.va.gov/admin/content/bulk?type=health_care_local_health_service)
- [x] 8. Bulk save fixed titles to facility service nodes. (https://prod.cms.va.gov/admin/content/bulk?type=health_care_local_health_service)
- [x] 9. Update menu title for facility
- [x] 10. May also need to directly edit the VAMC System menu to alpha sort the menu item after the title changes
- [x] 11. Update Alt text for facility image, if relevant
- [x] 12. Update Meta description (TBD: some backwards compatibility for SEM, by including something like ", formerly known as [previous name]".

#### CMS Help desk (wrap up)
- [ ] 14. Notify editor and any other stakeholders

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [ ] `Public Websites`
- [x] `Facilities`
- [x] `User support`

**Comment by stefaniefgray** [comment]
Hold until editor confirms that name is correct in https://va-gov.atlassian.net/browse/VAHELP-5712

**Comment by stefaniefgray** [comment]
Followed up with VA North Florida / South Georgia editor and teammates in https://va-gov.atlassian.net/browse/VAHELP-5712

**Comment by stefaniefgray** [comment]
Confirmed name change in https://va-gov.atlassian.net/browse/VAHELP-5712

**Comment by omahane** [comment]
@stefaniefgray @TroyA6 Redirect has been deployed. Confirm with stakeholders. This can be closed. Let's remove the "Changed Name" flag after the CSV has been deployed.
