### ISSUE TITLE
URL Change for: Oxnard VA Clinic [Ready to go]

### ISSUE THREAD

**Issue by stefaniefgray** [department-of-veterans-affairs/va.gov-cms#13381]
### Implementation date
When does this request need to be live:
Whenever clinic closure steps are complete -- see https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11225

### Instructions for URL redirect
(Note: This issue will be used from initial request through implementation to ensure all individuals working on this are notified of status updates.  Please do not create multiple issues to track different steps.)
- [x] Notify VA stakeholders as appropriate.
- [x] Link the related facility closure / rename issue.
- [x] Create a URL redirect in the [devops](https://github.com/department-of-veterans-affairs/devops) repo in `ansible/deployment/config/revproxy-vagov/vars/redirects.yml`
- [x]  Redirects deploy weekly on Wed. at 10am ET, or by requesting OOB deploy (of the revproxy job to prod) in #vfs-platform-support. After deploy, validate that the URL redirect is deployed. (Note: In the event of a facility closure or a name change,  validate that this occurs before making the Lighthouse csv changes.)
- [x]  Notify helpdesk via comment on ticket or Slack message in #cms-support that changes are ready for review.  

#### URL Redirect
| Current URL  |  Redirect Destination or New URL |
| ---  |  --- |
| https://www.va.gov/greater-los-angeles-health-care/locations/oxnard-va-clinic | https://www.va.gov/greater-los-angeles-health-care/locations/ |

### Instructions for removing a canonical URL
- [x] Try to find the facility via the Facility Locator. If it is not available, proceed.
- [x] Verify that the Facility API ID is no longer available by reaching out to Lighthouse via Slack #api-facilities.
- [x] Update the [CSV in Lighthouse](https://github.com/department-of-veterans-affairs/lighthouse-facilities/blob/master/facilities/src/main/resources/websites.csv) removing the row with the Facility API ID.
- [x] Create a PR in the [lighthouse-facilities repo](https://github.com/department-of-veterans-affairs/lighthouse-facilities), tagging the Lighthouse team.
- [x] Post a message in the #api-facilities channel in Slack, with an @mention to a Lighthouse team member.
**Note: there's no check for to see if it's not returning anything, as it should already be not showing anything in the Facility Locator.**

#### URL removal example (update with actual ID and URL to remove)
| Facility API ID  |  Full VA.gov URL |
| ---  |  --- |
| vha_691GM | https://www.va.gov/greater-los-angeles-health-care/locations/oxnard-va-clinic |

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [ ] `Public Websites`
- [x] `Facilities`
- [x] `User support`

**Comment by kmariepat-cityfriends** [comment]
@stefaniefgray I see on card: Facility closed: Oxnard VA Clinic [Ready for next steps] #11225 that this is ready to go, although there is a waiting for editor this card, are we waiting on the editor for anything?

**Comment by stefaniefgray** [comment]
Waiting on redirect

**Comment by omahane** [comment]
@stefaniefgray The redirect is now live. Keep this ticket open until the CSV is deployed.

**Comment by stefaniefgray** [comment]
Editor is notified in https://va-gov.atlassian.net/browse/VAHELP-5432

**Comment by omahane** [comment]
@stefaniefgray This one should be closed, actually. It's been removed from VAST. The CSV change is just hygiene for the file. No change in behavior at all.
