### ISSUE TITLE
UXR: Synthesize Usability Feedback

### ISSUE THREAD

**Issue by productmike** [department-of-veterans-affairs/va.gov-cms#13387]
## Description
The VFS-CMS team completed research usability sessions to find out how we might support editors in creating better quality alt-text. Research will synthesize user feedback we received so that the team can identify recommendations for improvement.

## What You Need to Know
- We've also completed an audit of the alt-text to identify deficiencies (let's add a link to any of that prev. work for historical info)
- We've already added Best Practice bullets that editors can follow before they add/write their content

## Acceptance Criteria
- [x] Usability sessions are wrapped up
- [x] Research sessions have been reviewed
- [ ] Emerging trends and patterns have been identified
- [x] Data that will be used for Topline Summary has been identified

**Comment by BerniXiongA6** [comment]
Making a note here that @joagnitti 's topline summary can be found here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/research/alt%20text/topline.md

**Comment by productmike** [comment]
Also cross-posted here for consistency sake: https://vfs.atlassian.net/wiki/spaces/PCMS/pages/2716205060/Alt+Text+Prototype+placeholder
