### ISSUE TITLE
IL: Research readout report prep and finalize written report

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#13380]
## Description

Follow on to https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11101. 

Note: DaveC will be OOO 4/28-5/9. This readout should be scheduled for a time when DaveC in office, with understanding that this ticket will/can close before the presentation takes place. (FYI @cindymerrill )

## Acceptance criteria

- [x] Research report gets reviewed
- [x] Report feedback is incorporated
- [x] Draft a readout presentation
- [x] Get presentation reviewed and incorporate feedback
- [x] Schedule readout presentation to interested parties (PW, DaveC, Danielle, invite any research observer invites that went out)

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [X] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`

**Comment by cindymerrill** [comment]
Incorporated feedback from Jordan. Waiting for feedback from @wesrowe  before sharing report with Dave C and Danielle.

**Comment by cindymerrill** [comment]
Drafted a very brief read out presentation for Sprint Demo today. Will expand on it for presentation to more people.

**Comment by cindymerrill** [comment]
Link to slack convo yesterday about who to invite to readout: https://adhoc.slack.com/archives/C03EUQRCHGS/p1682378009159089

**Comment by cindymerrill** [comment]
Discussing findings and recommendations with Wes and Jordan, and then updating report and readout slides accordingly.

**Comment by cindymerrill** [comment]
Finished discussing findings and recommendations with Wes and Jordan, and then updated report and readout slides accordingly. Slides are awaiting feedback from @wesrowe  and @thejordanwood, and potential design screenshots from Jordan.

Posted link to report in Content/IA ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/51132

**Comment by cindymerrill** [comment]
I incorporated feedback from Wes into the readout presentation, and I plan to share it with another researcher for feedback. The readout won't be presented until after the current sprint has ended; not sure if that's been scheduled yet (@wesrowe ?). 

Should I close this ticket or leave it open, @jilladams ?

**Comment by jilladams** [comment]
Once readout is scheduled, can be closed!

**Comment by cindymerrill** [comment]
Discussions with Dave C and Danielle have been scheduled, but so far not the readout. (Correct, @wesrowe ?)

**Comment by cindymerrill** [comment]
@wesrowe scheduled the readout for May 31, so I'm now closing this ticket. @jilladams 

Leading up to May 31, I may make some revisions to the readout presentation based on feedback from another researcher, Dave Conlon, and Danielle Thierry.
