### ISSUE TITLE
URL Change for: Bartlesville VA Clinic

### ISSUE THREAD

**Issue by stefaniefgray** [department-of-veterans-affairs/va.gov-cms#13399]
### Instructions for URL redirect
**TEMPORARY: Until the CSV can be deployed by Lighthouse. Will [revert](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14400) after that.**
(Note: This issue will be used from initial request through implementation to ensure all individuals working on this are notified of status updates.  Please do not create multiple issues to track different steps.)
UPDATE (2023-07-31): This redirect strategy did not work. Lighthouse merged this change in.

- [x] Notify VA stakeholders as appropriate.
- [x] Link the related facility closure / rename issue.
- [x] Create a URL redirect in the [devops](https://github.com/department-of-veterans-affairs/devops) repo in `ansible/deployment/config/revproxy-vagov/vars/redirects.yml`
- [x] Add the "Awaiting redirect" flag to the facility node with a revision log message that includes a link to this ticket, preserving the node's current moderation state.
- [ ] Redirects deploy weekly on Wed. at 10am ET, or by requesting OOB deploy (of the revproxy job to prod) in #vfs-platform-support. After deploy, validate that the URL redirect is deployed. (Note: In the event of a facility closure or a name change,  validate that this occurs before making the Lighthouse csv changes.)
- [x] Update this ticket with a comment that the redirect has been deployed.
- [x] Remove the "Awaiting redirect" flag on the facility node with a revision log message that includes a link to this ticket, preserving the node's current moderation state.
- [x]  Notify helpdesk via comment on ticket or Slack message in #cms-support that changes are ready for review.

#### URL Redirect
| Current URL  |  Redirect Destination or New URL |
| ---  |  --- |
| https://www.va.gov/find-locations/facility/vha_623QD | https://www.va.gov/eastern-oklahoma-health-care/locations/bartlesville-va-clinic/ |
-----

-----

### Implementation date
When does this request need to be live:
Whenever clinic ticket is complete: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13400

### Instructions for canonical URL change
- [x] Verify that the new URL for the facility is published and accessible on VA.gov.
- [x] Update the [CSV in Lighthouse](https://github.com/department-of-veterans-affairs/lighthouse-facilities/blob/master/facilities/src/main/resources/websites.csv) with the changed URL, maintaining the sorted order of the Facility API IDs.
- [x] Create a PR in the [lighthouse-facilities repo](https://github.com/department-of-veterans-affairs/lighthouse-facilities), tagging the Lighthouse team.
- [x] Post a message in the #cms-lighthouse channel in Slack, with an @mention to a Lighthouse team member.
- [x] Add the "Awaiting CSV" flag to the facility node with a revision log message that includes a link to this ticket.
- [x] Validate that the change has deployed by checking that the Facility Locator has been updated with the new url.
- [x] Update this ticket with a comment that the CSV change has been deployed.
- [x] Remove the "Awaiting CSV" flag to the facility node with a revision log message that includes a link to this ticket.

#### URL change example (update with actual ID and URL)
| Facility API ID  |  Full VA.gov URL |
| ---  |  --- |
| vha_623QD | https://www.va.gov/eastern-oklahoma-health-care/locations/bartlesville-va-clinic |

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [ ] `Public Websites`
- [x] `Facilities`
- [x] `User support`

**Comment by TroyA6** [comment]
@omahane @stefaniefgray - Jira Ticket [VAHELP-5703](https://va-gov.atlassian.net/browse/VAHELP-5703) is flagged as Waiting on Editor -- the facility's scheduled opening was May 22, but the page is still in Draft mode, with no Health Services added

**Comment by stefaniefgray** [comment]
Escalated to VHA DM

**Comment by stefaniefgray** [comment]
Completed. Closing!

**Comment by omahane** [comment]
This csv has not been deployed and we now also need a redirect.

**Comment by jilladams** [comment]
Went through and repeated the checklist steps and everything here seems done, including verification from within Facility Locator. CLosing.
