### ISSUE TITLE
PM: Implement Medallia on Vet Center pages 

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-cms#13390]
## Issue Description
We'd like to track Veteran satisfaction on Vet Center pages
Jessica/RCS may have access to VHA Medallia/CSAT implementation 

---
## Tasks
- [x] does the existing survey for va.gov fire for vet centers; IF yes share with Jessica Schiefer (Primary Vet Center Stakeholder) IF no, determine next steps to get this going 
- [x] Work with Jessica Schiefer (Primary Vet Center Stakeholder) to determine which version/questions

**Comment by kmariepat-cityfriends** [comment]
There may be a default survey already implemented

**Comment by davidconlon** [comment]
@jilladams @kmariepat-cityfriends why did we ask Jessica this? She wouldn't know. 

I stated in the meeting that you need to check with Platform Analytics to see if there is data being returned from any of the Vet Center URLs.
If yes THEN talk to Jessica.
I'm not sure how we ended up with the task of "what version/questions"

**Comment by kmariepat-cityfriends** [comment]
@davidconlon a missed note on my part. With your clarifying note above, I've now asked platform analytics, see slack message here: https://dsva.slack.com/archives/CKCRMLGAC/p1683814288861429

**Comment by kmariepat-cityfriends** [comment]
I made a qualitative data request for the survey data: https://github.com/department-of-veterans-affairs/va.gov-team/issues/58929
