### ISSUE TITLE
URL Change for: Fort Yates VA Clinic

### ISSUE THREAD

**Issue by stefaniefgray** [department-of-veterans-affairs/va.gov-cms#13403]
### Instructions for URL redirect
**TEMPORARY: Until the CSV can be deployed by Lighthouse. Will [revert](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14400) after that.**
(Note: This issue will be used from initial request through implementation to ensure all individuals working on this are notified of status updates.  Please do not create multiple issues to track different steps.)
UPDATE (2023-07-31): This redirect strategy did not work. Lighthouse merged this change in.

- [x] Notify VA stakeholders as appropriate.
- [x] Link the related facility closure / rename issue.
- [x] Create a URL redirect in the [devops](https://github.com/department-of-veterans-affairs/devops) repo in `ansible/deployment/config/revproxy-vagov/vars/redirects.yml`
- [ ] Add the "Awaiting redirect" flag to the facility node with a revision log message that includes a link to this ticket, preserving the node's current moderation state.
- [ ] Redirects deploy weekly on Wed. at 10am ET, or by requesting OOB deploy (of the revproxy job to prod) in #vfs-platform-support. After deploy, validate that the URL redirect is deployed. (Note: In the event of a facility closure or a name change,  validate that this occurs before making the Lighthouse csv changes.)
- [ ] Update this ticket with a comment that the redirect has been deployed.
- [ ] Remove the "Awaiting redirect" flag on the facility node with a revision log message that includes a link to this ticket, preserving the node's current moderation state.
- [ ]  Notify helpdesk via comment on ticket or Slack message in #cms-support that changes are ready for review.

-----

### Implementation date
When does this request need to be live:
Whenever clinic homepage is published - https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13404

#### URL Redirect
| Current URL  |  Redirect Destination or New URL |
| ---  |  --- |
| https://www.va.gov/find-locations/facility/vha_568QA | https://www.va.gov/black-hills-health-care/locations/fort-yates-va-clinic |

### Instructions for canonical URL change
- [ ] Verify that the new URL for the facility is published and accessible on VA.gov.
- [x] Update the [CSV in Lighthouse](https://github.com/department-of-veterans-affairs/lighthouse-facilities/blob/master/facilities/src/main/resources/websites.csv) with the changed URL, maintaining the sorted order of the Facility API IDs.
- [x] Create a PR in the [lighthouse-facilities repo](https://github.com/department-of-veterans-affairs/lighthouse-facilities), tagging the Lighthouse team.
- [x] Post a message in the #api-facilities channel in Slack, with an @mention to a Lighthouse team member.
- [ ] Validate that the change has deployed by checking that the Facility Locator has been updated with the new url.

#### URL change example (update with actual ID and URL)
| Facility API ID  |  Full VA.gov URL |
| ---  |  --- |
| vha_568QA | https://www.va.gov/black-hills-health-care/locations/fort-yates-va-clinic |

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [ ] `Public Websites`
- [x] `Facilities`
- [x] `User support`

**Comment by stefaniefgray** [comment]
@omahane Ready! 🚀

**Comment by stefaniefgray** [comment]
@omahane Facility Locator is still directing to placeholder page instead of CMS URL -- is this a CSV hold-up?

Thx for any info you can provide!

**Comment by omahane** [comment]
The CSV has been deployed (CC: @stefaniefgray @jilladams )

**Comment by stefaniefgray** [comment]
@omahane Looks good! Marked as complete on Flagged Facilities spreadsheet, editor notified -- gonna go ahead and close, please let me know if I should re-open it
