### ISSUE TITLE
New VAMC Facility: Johnson Air Force Base VA Clinic

### ISSUE THREAD

**Issue by stefaniefgray** [department-of-veterans-affairs/va.gov-cms#13406]
## Intake
- [x] What triggered this runbook? (Flag in CMS, Help desk ticket, Product team, VHA Digital Media)
Trigger: Flagged Facilities view -- see updated spreadsheet https://docs.google.com/spreadsheets/d/1TR-5sEWaEj8GsyHYCPYbaylIRQDnXDVsGp80O8YLESw/edit#gid=0

- [x] Link to associated help desk ticket (if applicable)
Help desk ticket: https://va-gov.atlassian.net/browse/VAHELP-5706

- [x] Name of submitter (if applicable)
Submitter: Stefanie Gray

- [ ] If the submitter is an editor, send them links to any relevant KB articles for the VAMC Facility product.
KB articles: <insert_kb_article_links>

- [x] Link to facility in production:
Facility link: https://prod.cms.va.gov/locations/johnson-air-force-base-va-clinic
Facility Locator link: https://www.va.gov/find-locations/facility/vha_565GO

### New VAMC Facility
Please refer to the Knowledge Base article titled "How do I add a facility to my health care system?" for more information: https://prod.cms.va.gov/help/vamc/about-locations-content-for-vamcs/how-do-i-add-a-facility-to-my-health-care-system

#### CMS help desk steps
- [x] 1. Become aware that the new facility is now on the Facility API (typically, via a Flag, but this may come in as a helpdesk ticket).
- [x] 2. If the editor has followed the steps from the above Knowledge Base article and included which section and VAMC the facility belongs to (i.e. VA Pittsburgh), great! **Proceed to step 3.** If not, please check with the editor or VHA digital media regarding what section and VAMC it belongs to.
- [x] 3. Updates the Section (default is "VAMC facilities", but it should be a VAMC system in a VISN) and VAMC system field accordingly.
- [x] 4. Communicate with editor (cc VHA Digital Media) to give them go-ahead to complete the content, with this [KB article](https://prod.cms.va.gov/help/vamc/about-locations-content-for-vamcs/how-do-i-add-a-facility-to-my-health-care-system). (See sample notification email below)

[@TODO: Update email template]

<details><summary>Email template </summary>

```
Hello! You should now be able to edit the draft page for this facility, located at [LINK TO NEW FACILITY DRAFT PAGE ON PROD]

Important: Please make sure that all relevant steps listed within the “How do I add a facility to my health care system?” Knowledge Base article have been completed: https://prod.cms.va.gov/help/vamc/about-locations-content-for-vamcs/how-do-i-add-a-facility-to-my-health-care-system

Once finished, please save this page (and all related VAMC Facility Health Service pages) in the moderation state “Draft." Please do not save them as “Published.”

Please let us know when your draft content is complete, so that we can wrap up the technical process from our end before publishing the new facility to VA.gov. Thanks!
```

</details>
- [ ] 5. Create a [URL change request](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/new?assignees=&template=runbook-facility-url-change.md&title=URL+Change+for%3A+%3Cinsert+facility+name%3E), changing the entry from the old facility URL to the new facility URL. (**Note: The URL change request ticket blocks the completion of this ticket.**)

https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13405

(Redirects are released Wednesday afternoons, so coordinate the following items below and canonical URL change around that timeframe.)

- [x] 6. When editor has prepared content and let help desk know, reassign this issue to appropriate CMS engineer on Product Support team, for bulk publishing.
#### CMS engineer steps
- [x] 7. CMS engineer executes the steps of the URL change request ticket from step 5 above.

(Redirects deploy weekly on Wed. at 10am ET, or by requesting OOB deploy (of the revproxy job to prod) in #vfs-platform-support. Coordinate the items below and canonical URL change after URL change ticket is merged, deployed, and verified in prod.)

#### Drupal Admin steps (CMS Engineer or Help desk)
_Help desk will complete these steps or escalate to request help from CMS engineering._
- [x] 8. Drupal Admin bulk publishes nodes and facility.
- [x] 9. Drupal Admin edit facility node and remove `New facility` flag and save node.
- [x] 10. Let Help desk know this has been done, if not done by Help desk.

#### CMS Help desk (wrap up)
- [ ] 11. Notify editor and any other stakeholders.

**Comment by stefaniefgray** [comment]
Escalated to VHA DM after 3 attempts to contact editor - https://va-gov.atlassian.net/browse/VAHELP-5706

Can't add "Waiting for Editor" flag because editor has not confirmed section; can't edit and re-save facility node without it having an assigned section

**Comment by stefaniefgray** [comment]
Waiting for editor to finish draft homepage

**Comment by stefaniefgray** [comment]
Editor prematurely published homepage without health services

Escalating to VHA DM

**Comment by stefaniefgray** [comment]
@omahane Editor prematurely published location, so I fixed the menu link alphabetical order issue

Only health service associated with this facility is also now published

Can I go ahead and close this? Running it by you just to double-check -- thanks!

**Comment by stefaniefgray** [comment]
Facility Locator hasn't updated yet

**Comment by davidconlon** [comment]
@jilladams @stefaniefgray This runbook was incorrect/out-of-date because there shouldn't have been a dependency on Facility Locator to close this issue.
An unnecessary redirect has been deployed (because it now works)

**Comment by jilladams** [comment]
Thanks for flagging, Dave. Will follow up.

**Comment by jilladams** [comment]
1. Double checked recent PRs for runbook updates, no changes to New VAMC facility yet. ([List of PRs created by DaveC](https://github.com/department-of-veterans-affairs/va.gov-cms/pulls?q=is%3Apr+author%3Adavidconlon+is%3Aclosed).)
2. Updated body of this ticket to align with [runbook-vamc-facility-new.md](https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/.github/ISSUE_TEMPLATE/runbook-vamc-facility-new.md). (Main changes were re: Drupal admin for steps 8-10.)
3. From Facility Locator, found this Clinic ([here](https://www.va.gov/find-locations/?page=1&address=Goldsboro%2C%20NC&facilityType=health&serviceType&latitude=35.384884&longitude=-77.992765&radius=27&bounds%5B%5D=-78.742765&bounds%5B%5D=34.634884&bounds%5B%5D=-77.242765&bounds%5B%5D=36.134884&context=Goldsboro%2C%20North%20Carolina%2C%20United%20States)), clicked through, and land on https://www.va.gov/find-locations/facility/vha_565GO rather than https://www.va.gov/fayetteville-coastal-health-care/locations/johnson-air-force-base-va-clinic/. @omahane can you confirm: this is because of the LH hold up on CSV merges right now, right? 
4. Ping for follow up in Slack:

**Comment by stefaniefgray** [comment]
Spoke to @davidconlon directly about this; clarified that an older runbook was used, all is well

@jilladams Thank you so much for updating! Looks like we're all in alignment, but please let me know if there's anything else that needs updates or clarification

**Comment by omahane** [comment]
> * Double checked recent PRs for runbook updates, no changes to New VAMC facility yet. ([List of PRs created by DaveC](https://github.com/department-of-veterans-affairs/va.gov-cms/pulls?q=is%3Apr+author%3Adavidconlon+is%3Aclosed).)
> * Updated body of this ticket to align with [runbook-vamc-facility-new.md](https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/.github/ISSUE_TEMPLATE/runbook-vamc-facility-new.md). (Main changes were re: Drupal admin for steps 8-10.)
> * From Facility Locator, found this Clinic ([here](https://www.va.gov/find-locations/?page=1&address=Goldsboro%2C%20NC&facilityType=health&serviceType&latitude=35.384884&longitude=-77.992765&radius=27&bounds%5B%5D=-78.742765&bounds%5B%5D=34.634884&bounds%5B%5D=-77.242765&bounds%5B%5D=36.134884&context=Goldsboro%2C%20North%20Carolina%2C%20United%20States)), clicked through, and land on https://www.va.gov/find-locations/facility/vha_565GO rather than https://www.va.gov/fayetteville-coastal-health-care/locations/johnson-air-force-base-va-clinic/. @omahane can you confirm: this is because of the LH hold up on CSV merges right now, right?
> * Ping for follow up in Slack: https://dsva.slack.com/archives/C02730UEZPS/p1691013117440469

Yes, the reason for the redirect is mentioned on the [URL change ticket](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13405): we mistakenly thought this would allow Facility Locator to send a user to the full facility URL rather than to the placeholder FL page. 

The explanation in that other ticket also points to the ticket to revert the redirect: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14400, which further elaborates which CSV changes have been made of those facilities we redirected. 

This facility and Cedar Crest have yet to have the CSV updated, but that has been requested of Lighthouse here: https://dsva.slack.com/archives/C02BTJTDFTN/p1690826180027919

**Comment by omahane** [comment]
@stefaniefgray @TroyA6 The CSV has been deployed. This facility page now is returned in the Facility locator. Please confirm with editors and close this ticket at your convenience.

**Comment by stefaniefgray** [comment]
Editor notified -- closing! Thanks @omahane 🚀
