### ISSUE TITLE
Configure view modes for all content types to support content proofing needs

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#1344]

**Comment by oksana-c** [comment]
Scope is too broad as applied to all content types. We also may rethink how we approach content proofing in the near future as we enter ideation phase for [full site preview](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/product-outlines/full-site-preview.md). Closing this issue.
