### ISSUE TITLE
Flagged Facilities Audit Follow-Up: Flags to Remove

### ISSUE THREAD

**Issue by stefaniefgray** [department-of-veterans-affairs/va.gov-cms#13441]
## Description
Here are the different types of flags that can be removed according to my audit of flagged VAMC facilities ( https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13440 )

Master tracking spreadsheet, which also has links to Jira Service Desk correspondence: https://docs.google.com/spreadsheets/d/1TR-5sEWaEj8GsyHYCPYbaylIRQDnXDVsGp80O8YLESw/edit?usp=sharing

If a Facility Locator link is included for the following facilities, it means it is still listed as of 4/20/2023:

### Location is already published, flag removal step was skipped in runbook: 
Facility Locator links are accurate
- [x] [Mesa VA Clinic](https://prod.cms.va.gov/phoenix-health-care/locations/mesa-va-clinic)
- [x] [Phoenix 32nd Street VA Clinic](https://prod.cms.va.gov/phoenix-health-care/locations/phoenix-32nd-street-va-clinic)

### Editor said "Don't publish this to our site."
- [x] [Academy VA Clinic](https://prod.cms.va.gov/eastern-colorado-health-care/locations/academy-va-clinic)
Facility Locator: https://www.va.gov/find-locations/facility/vha_554QE
- [x] [Evans VA Clinic](https://prod.cms.va.gov/eastern-colorado-health-care/locations/evans-va-clinic)
Facility Locator: https://www.va.gov/find-locations/facility/vha_554QD
- [x] [Gulf Coast West VA Mobile Medical Unit-Clinic](https://prod.cms.va.gov/locations/gulf-coast-west-va-mobile-medical-unit-clinic)
Facility Locator: https://www.va.gov/find-locations/facility/vha_520QB
- [x] [Jackson 2 VA Mobile Clinic](https://prod.cms.va.gov/locations/jackson-2-va-mobile-clinic)
Facility Locator:  https://www.va.gov/find-locations/facility/vha_586QD
- [x] [Papillion VA Community Living Center](https://prod.cms.va.gov/locations/papillion-va-community-living-center)
Facility Locator: https://www.va.gov/find-locations/facility/vha_6369BA

### Editors haven't heard of location or claim it does not exist within their system:
- [x] [Maple Street VA Domiciliary](https://prod.cms.va.gov/locations/maple-street-va-domiciliary)
Facility Locator: https://www.va.gov/find-locations/facility/vha_689BW
- [x] [Norton Street VA Domiciliary](https://prod.cms.va.gov/locations/norton-street-va-domiciliary)
Facility Locator: https://www.va.gov/find-locations/facility/vha_689BX
- [x] [Orlando 2 VA Mobile Clinic](https://prod.cms.va.gov/locations/orlando-2-va-mobile-clinic)
Facility Locator: https://www.va.gov/find-locations/facility/vha_675QH

## Acceptance Criteria
- [x] The above list is reviewed by @omahane and @swirtSJW for accuracy
- [x] Flags are removed for each facility where they can be removed, list is checked-off one-by-one
   - [x] For any that should not be published there should be a revision log that explains why and links to any relevant jira or github tickets. 
- [x] Facility Locator issues are tracked and handled by our team

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [ ] `Public Websites`
- [x] `Facilities`
- [x] `User support`

**Comment by swirtSJW** [comment]
I took care of the first two in the list and added one AC.  This is good to go.

**Comment by swirtSJW** [comment]
Added the two missing facility locator links for mobiles

**Comment by omahane** [comment]
I finished the rest today.

**Comment by stefaniefgray** [comment]
@omahane You rock!!! Confirmed completed
