### ISSUE TITLE
Spike: Check patched GraphQL 3/Drupal 10 data integrity

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#13456]
## Description
We have determined that we will most likely be able to patch GraphQL 3 to work with Drupal 10 with minimal effort. However, we need to verify this is actually true.

Steps would be:
1. Set up an environment with a current DB, current content build, and current Drupal install.
2. Run a content-build; save the front-end output & the pages.json file that is generated somewhere where it can be referenced later.
3. Run the Drupal 10 w/ GraphQL 3 branch updates on this same environment; perform no other updates.
4. Run a content-build with a content-build branch containing necessary changes (should be minor) to work with the updated GraphQL libraries. Save the front-end output & the pages.json file to the same location as in 2.
5. Run a comparison. This could be a diff of the json files; diffs of the front-end output files; visual regression diff of the two directories.

## Acceptance Criteria
- [x] Identify the differences between before & after GraphQL 3 patch (if patched GraphQL 3 & Drupal 10 will produce identical front-end output or not). 
- [x] For any differences found that an editor would experience in production (e.g. timestamp diffs would be a side effect of the testing method but NOT what an editor would normally experience), provide an impact estimate (1-5 scoring is fine). 
- [x] Document findings in this ticket or existing dev repo. Indicate in this ticket where they are stored.

### Team
Please check the team(s) that will do this work.

- [x] `CMS Team`
- [ ] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`

**Comment by productmike** [comment]
@timcosgrove @edmund-dunn @tonytaylor 
I lied -- I did expand the ACs slightly. Still within frame of what we discussed earlier, other than give a VERY basic impact score to/if any differences found.

Can y'all take a look, let me know if any Qs? When y'all are comfortable with the expectations of the ticket, could you story point it as well prior to Wednesday?

Much appreciate on your time this morning!!

**Comment by timcosgrove** [comment]
Preview: https://tugboat.vfs.va.gov/645019679a752fdd1688835c

**Comment by timcosgrove** [comment]
2 PRs out of this:
https://github.com/department-of-veterans-affairs/va.gov-cms/pull/13568
https://github.com/department-of-veterans-affairs/content-build/pull/1549

They need a bit more touch up and discussion before review.

**Comment by timcosgrove** [comment]
The testing process revealed a few things that needed modification in the Drupal 10 branch. These are captured in https://github.com/department-of-veterans-affairs/va.gov-cms/pull/13568.

The testing process also revealed that changes in the way Drupal handles Office Hours fields are causing problems on the content-build side. These are handled in https://github.com/department-of-veterans-affairs/content-build/pull/1549.

**Comment by timcosgrove** [comment]
Other differences were only due to timing differences due to when the builds happened and/or what database is available to the Tugboat instance - i.e. different events being available on events pages - or additions due to changes in the Linkit module that will not impact the user-facing experience.

None of the remaining changes will impact the user experience.
