### ISSUE TITLE
VAMC: Design Update Implementation

### ISSUE THREAD

**Issue by productmike** [department-of-veterans-affairs/va.gov-cms#13468]
##Description
As an editor for the VA VAMC properties, I want CMS notifications to be tightly integrated into my existing workstream, so that it's an amplification of my work, not another a separate set of criteria/Work instructions I need to monitor.

## Acceptance Criteria
- [ ] The updates have been communicated to and prepared with dev and Helpdesk.
- [ ] The notification changes (updating language only) have been made, tested and queued in production.

**Comment by productmike** [comment]
@edmund-dunn @BlakeOrgan -- this is in response to refinement last week. If my memory and notes serve, we were looking at both a separate Vet Center design AND VAMC design update since they've now been forked for implementation. Let me know if that isn't accurate :)

**Comment by productmike** [comment]
@productmike to update to include the determination from design ticket

**Comment by BlakeOrgan** [comment]
The updated designs for the VAMC 6102 Notification email can be found in the Figma file linked below. The updates match the Vet Center updates exactly where the only thing we updated is the body copy of the email. The only difference between the two is that we state in the body copy that VAMCs will update 25 pieces of content.  
  
https://www.figma.com/file/fQl2Y2k9MDA2dc0xViC645/6102-Notification-Email?node-id=519%3A7745&t=mYOS6tLP0dHg6ODz-1
