### ISSUE TITLE
SPIKE: Review Criteria for Flagged Facilities 

### ISSUE THREAD

**Issue by kmariepat-cityfriends** [department-of-veterans-affairs/va.gov-cms#13469]
### Background 

VAST updates generate changes to Facilities nodes in the CMS. 
The CMS adds flags: 
- Changed name
- New facility
- Removed from source

Some flagged facilities have follow up steps required to address / mitigate the change in the front end for Veterans. But: not all. 

We _think_ there are flags being applied to Facility types that do not require follow up steps. In those cases, the Flag clog up the [Flagged Facilities dashboard](https://prod.cms.va.gov/admin/content/facilities/flagged) and require manual steps to remove the flag. Also makes it hard to assess the scale of follow up changes that actually _are_ required. 

Related existing card: #13441

### Goal
1. Assess the flags we apply, and if there are cases where a certain Facility type does _not_ need a flag for a specific type of change, note that for future logic change to stop applying the flag. (Reduce manual toil.)
2. Assess the flags we _do_ apply and make sure we have runbooks for follow up steps.
3. Document the criteria used for Flagging. 

## Acceptance criteria

- [x] Document criteria for flags that are applied
- [x] Document recommendation for any flags we can stop applying to any facility types

**Comment by jilladams** [comment]
Existing flags: 

**Substantive flags from VAST changes**
- Changed name
- New facility
- Removed from source

**Workflow flags** added to manage updates based on VAST updates
- Awaiting CSV
- Awaiting editor
- Awaiting redirect

Flags are applied to all Facility types with any matching change? To be verified.  
YES:
* VAMC System 
* VAMC Facility 
* Vet center
* Vet center outstation

Not sure: 
* VBA Facilities
* NCA facilities (Cemeteries)
* Vet Center mobile

Matrix: https://docs.google.com/spreadsheets/d/1fkGH1PGXXPHObsDc_kVnea-JQVnS0HGVKP16aBTjdpw/edit#gid=0

Meeting scheduled 5/4 to review with Stef & verify my assumptions & get to recommendation.

**Comment by jilladams** [comment]
## Analysis
[Facilities Flags & Runbooks - Sheet1.pdf](https://github.com/department-of-veterans-affairs/va.gov-cms/files/11408082/Facilities.Flags.Runbooks.-.Sheet1.pdf)
* Also as Google sheet for edits: https://docs.google.com/spreadsheets/d/1fkGH1PGXXPHObsDc_kVnea-JQVnS0HGVKP16aBTjdpw/edit#gid=0

### Flags to remove (optional)
There are 4 flags we could stop flagging: 
1. Changed Name - NCA
2. Changed Name - VBA
3. Removed from source - NCA
4. Removed from source - VBA

These don't currently require any follow up steps, though they will in the future.  Otherwise, the spreadsheet calls out which runbooks apply to which flags.


### Other changes / recommendations
1. **Add bulk actions to the [Flagged Content view](https://prod.cms.va.gov/admin/content/facilities/flagged).** Currently you have to edit each node to change the flag. This is ok, as it prompts for a Revision Log. But in the case of removing unnecessary flags, that's a lot of manual work for ultimately a no-op. Bulk actions are available on other content moderation views (e.g. [New/Deleted Forms view](https://prod.cms.va.gov/admin/content/va-forms/new-deleted) ), and this seems like a light lift to add to Flagged Content view. The one consideration is: that would remove the Revision Log requirement (I think).
2. **Vet center changed name / removed from source runbooks** Need an update to make it clear they apply to Outstation and Mobile Vet Center name changes / removals as well. I'll just do that here shortly under this ticket. 
3. **Mobile Vet Centers moving to different Vet Center:** Sometimes a MVC may change hands and be sold from one Vet Center to another. Those have previously shown up as a duplicate new Facility, and need a runbook, similar to [runbook-vamc-facility-duplicate-or-section-change.md](https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/.github/ISSUE_TEMPLATE/runbook-vamc-facility-duplicate-or-section-change.md). Will cut a ticket for this.


FYI @swirtSJW  @omahane @stefaniefgray @TroyA6 @kmariepat-cityfriends

**Comment by swirtSJW** [comment]
I don't think we should get rid of the Flags for 
Removed from source - NCA
Removed from source - VBA
We still need to know to archive them so they do not create confusion later on when we launch these products.
The only way we could remove them is if we alter the migration to autoarchive them when they disappear.... but we would have to remove the autoarchive when the product lauches.

**Comment by swirtSJW** [comment]
Changed Name - NCA
Changed Name - VBA
Actually there is a followup step to update the drupal alias.... unless we automate that.  (aliases get locked down intentionally so they do not float on their own.)

**Comment by swirtSJW** [comment]
```
Not sure:
VBA Facilities
NCA facilities (Cemeteries)
Vet Center mobile
``` 
Yes these all get flagged too.

**Comment by swirtSJW** [comment]
> Add bulk actions to the [Flagged Content view](https://prod.cms.va.gov/admin/content/facilities/flagged). Currently you have to edit each node to change the flag. This is ok, as it prompts for a Revision Log. But in the case of removing unnecessary flags, that's a lot of manual work for ultimately a no-op. Bulk actions are available on other content moderation views (e.g. [New/Deleted Forms view](https://prod.cms.va.gov/admin/content/va-forms/new-deleted) ), and this seems like a light lift to add to Flagged Content view. The one consideration is: that would remove the Revision Log requirement (I think).

Bulk operations bypasses a lot of things, and may prevent both adding a revision log, and the automated part of the revision log that happens (not sure on this one without trying it)

**Comment by swirtSJW** [comment]
> Mobile Vet Centers moving to different Vet Center:

Why wouldn't the facility moved runbook apply to this.  I can't think of anything about this one that would be different except you would change parent vet center instead of System.   (different field name but same idea)

**Comment by jilladams** [comment]
Ok. The spreadsheet (also as PDF) answers all the questions posed in my first comment here, in more detail. 

I went ahead and cut a ticket for bulk actions, which we can opt to refine at some point and maybe Icebox or close. If we aren't going to remove the flags that don't have follow up actions, I'd advocate for bulk actions to help make it easy to keep the Flagged Content board clean. 

@swirtSJW it might be fastest for you and I to connect for 5 mins to clear up the open questions Christian / Stef and I discussed live, vs. comments traffic here.

**Comment by jilladams** [comment]
Also: one thing I forgot to mention / propose is a Workflow flag for "Github tickets created". That would help when looking at the Flagged Content view and seeing items that are flagged New / Removed / Changed, but not yet also flagged as "awaiting CSV / editor / redirect" so we know the state of the workflow and if they're actually new flags that need to be addressed, or things are already underway.

**Comment by jilladams** [comment]
Talked to Steve, got some additional details / stepped through the spreadsheet with him. Updated final outcome here: 

## Analysis
New PDF: [Facilities Flags & Runbooks.pdf](https://github.com/department-of-veterans-affairs/va.gov-cms/files/11424331/Facilities.Flags.Runbooks.pdf)
* Also as Google sheet for edits: https://docs.google.com/spreadsheets/d/1fkGH1PGXXPHObsDc_kVnea-JQVnS0HGVKP16aBTjdpw/edit#gid=0

### Flags to remove
Each flag coming in does have follow up steps currently, so there are none we can immediately stop flagging. However, there are opportunities to automate a few steps that we could then stop generating some NCA/VBA flags until those workflows launch and runbooks get more detailed.

### **Opportunities to automate:**
In each of these cases, the listed step is the only runbook step. If automated, these runbooks could be temporarily retired. @swirtSJW suspects tickets exist for these changes, but I did not find any tickets this specific. TODO: decide if we need to cut those tickets, or find them and link them here.
* **VBA Facilities**
    * Name change = automate updating the Section term name to match the Facility's new name. 
    * Closed = delete the related section term.
* **NCA facilities**
    * Name change = update URL alias to match Facility's new name.
    * Closed = move node status to Archived

### Other changes / recommendations 
1. **Add bulk actions to the [Flagged Content view](https://prod.cms.va.gov/admin/content/facilities/flagged).** Ticket = #13624. Currently you have to edit each node to change the flag. This is ok, as it prompts for a Revision Log. But in the case of removing unnecessary flags, that's a lot of manual work for ultimately a no-op. Bulk actions are available on other content moderation views (e.g. [New/Deleted Forms view](https://prod.cms.va.gov/admin/content/va-forms/new-deleted) ), and this seems like a light lift to add to Flagged Content view. The one consideration is: that would remove the Revision Log requirement (I think). 
2. **Mobile Vet Centers moving to different Vet Center:** Sometimes a MVC may change hands and be sold from one Vet Center to another. Those have previously shown up as a duplicate new Facility, and need a runbook, similar to [runbook-vamc-facility-duplicate-or-section-change.md](https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/.github/ISSUE_TEMPLATE/runbook-vamc-facility-duplicate-or-section-change.md). Ticket = #13623. The criteria may be satisfied already, tbd from help desk, notes on ticket.

I've made all the other edits we noted were needed within runbooks. Moving to PO review.

FYI @swirtSJW  @omahane @stefaniefgray @TroyA6 @kmariepat-cityfriends

**Comment by jilladams** [comment]
I also migrated the Google Sheet info and some top level information about how / why we flag, into Github: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/flagged-facilities.md

That can move to wherever it makes sense. I did not find any of this info in the Team repo (no references to `facilities/flagged` or "flagged facility").

**Comment by kmariepat-cityfriends** [comment]
I made a follow up card to this to discuss in a future refinement: #13644
