### ISSUE TITLE
D10: Impacts to Full Stack

### ISSUE THREAD

**Issue by productmike** [department-of-veterans-affairs/va.gov-cms#13475]

**Comment by EWashb** [comment]
@productmike do you have a description of this work? I'm not sure of the context of this one.

**Comment by productmike** [comment]
@jilladams @EWashb This epic was a placeholder as I got more acquainted with the upgrade activities. Then intent was to capture the work needed from the technical side in prep for testing. I shift the PW epic into our new testing epic and will close this one. Thanks!

**Comment by omahane** [comment]
Sure would be nice to have something here to go on for the Drupal 11 testing.
