### ISSUE TITLE
Task: Discovery for all contrib modules

### ISSUE THREAD

**Issue by productmike** [department-of-veterans-affairs/va.gov-cms#13478]
## Description
The end goal of this task is to identify the content modules that are going to be supported in Drupal 10. 

## Acceptance Criteria
- [x] Identify any contrib modules that may be abandoned by Drupal.
- [ ] Identify any contrib modules that are going to be supported by D10, but require updates that could cause production impacts without further planning. 
- [ ] Identify any contrib module that can be updated immediately with causing production impacts (e.g. no breaking changes). 
- [ ] Begin to update contrib modules that can be updated immediately with causing production impacts (e.g. no breaking changes).

**Comment by productmike** [comment]
@tonytaylor @timcosgrove @edmund-dunn Here's the contib code ticket mentioned earlier. Let me know what updates/questions answered needed to be considered refined/ready for sprint. Thanks!!

**Comment by edmund-dunn** [comment]
https://www.drupal.org/project/entity_route_context is D10 only.

**Comment by edmund-dunn** [comment]
@productmike adding tickets generated form this discovery.
