### ISSUE TITLE
Dependabot ID'd Risks for 2Q 2023

### ISSUE THREAD

**Issue by productmike** [department-of-veterans-affairs/va.gov-cms#13497]
## Description
This epic houses the spikes and tasks needed to support security risks identified by Dependabot within 2Q 2023. 

## Acceptance Criteria
- [ ] All security updates identified have been documented within this epic. 
- [ ] All security updates have a documented decision point (defer, perform spike, fix) - and any associated tickets to support.

**Comment by productmike** [comment]
@ndouglas I'm not sure if this is the 'best' way to address the security issues ID'd by dependabot. If this requires to much overhead to support, let's rethink -- essentially looking for a way to loosely connect that work with github to accurately illustrate the work we're performing.

**Comment by ndouglas** [comment]
This looks fine to me. 

I opened an issue (#13489) for the Rust vulnerabilities. Personally, I don't think it's worth estimating but I'm happy to talk about it at the next refinement (or just do it, but its related vulnerabilities are a purely cosmetic issue on the repository).

@edmund-dunn has a strong interest in security things and he has addressed some of these issues in the past (and his work is responsible for making addressing these vulnerabilities less painful moving forward), so he might have feelings about managing the Node vulnerabilities 🙂
