### ISSUE TITLE
Solidify details for editor survey rollout

### ISSUE THREAD

**Issue by joagnitti** [department-of-veterans-affairs/va.gov-cms#13501]
## Description
After a review from VHA DM of the survey and plans for rollout, a number of concerns arose that need to be addressed before we distribute the survey. From Blake S.:

> Per VHA's Office of Workforce Management and Consulting, it is not permissible to send a survey to VHA employees until it has first been sent/shared with the national labor partners for review and approval. This would need to be assigned formerly through VIEWS to VACO LMR to start that process. 
> 
> Additionally, have you all checked to see if OIT has a survey platform to use that's NOT Survey Monkey? Survey Monkey is not on https://www.oit.va.gov/marketplace/ nor on FEDRAMP list so not an approved SaaS product. If OIT does not have an approved survey platform to use, it may be possible to tap into VHA's Qualtrics instance, but I have been informed there would be costs associated with the size and volume of the survey.

## Acceptance Criteria
- [ ] Confirm what survey platform we will be using (i.e., Survey Monkey, Qualtrics, other)
- [ ] Share survey with appropriate partners for review and approval 

### Team
Please check the team(s) that will do this work.

- [x] `CMS Team`
- [ ] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`

**Comment by productmike** [comment]
Re: platform -- Erika having similar discussions like this: https://dsva.slack.com/archives/C052A7RJFPS/p1683299048617819

**Comment by EWashb** [comment]
@joagnitti @productmike I feel like this was completed. We have the details nailed down. The only feedback was to go through VIEWS. I also confirmed the use of Survey Monkey. What say ye?

**Comment by joagnitti** [comment]
Ohh we can keep Survey Monkey? That would save me time, for sure. It sounds like this can be closed, then!
