### ISSUE TITLE
Add multiselect checkboxes to the design system.

### ISSUE THREAD

**Issue by BlakeOrgan** [department-of-veterans-affairs/va.gov-cms#13500]
## Description

- As a designer, I want to have a component in the design system that allows for a good UX when selecting multiple options from a large list, so that I can use this component in places where it would solve a UX problem for my product.
- As a CMS Editor, I want to be able to easily select multiple options from a large list so that I can do what I need to do and move on to the next task.

## Atomic Level

These levels match the levels in [VA.gov Design System Documentation](https://design.va.gov/)

- [ ] **Foundation** - The Foundation section provides information about the visual language and styles used in the CMS.
- [x] **Component** - Components are interactive and non-interactive UI elements that can be grouped together or presented individually. They are independent, reusable chunks of a user interface.
- [ ] **Pattern** - Patterns are solutions and researched best practices for solving user-focused tasks and recurring user interface design problems.
- [ ] **Template** - Templates, or page layouts, compose components within a single page. A layout can contain multiple variations of a component depending on the context.

## Acceptance Criteria
**Update Figma**
- [x] Create multiselect dropdown component.
- [x] Create multiselect dropdown component that is searchable for lists that are REALLY long.
- [ ] Make sure that the design aligns with any existing components in the USWDS or the VA Design System
- [ ] Ensure that the [CMS Design System in Figma](https://www.figma.com/file/LAlrfgqFJgCV9EIq7eyDcw/Simplified-Design-System?node-id=210%3A123&t=HGcnMLHgk9fV2TxN-1) is updated to reflect the changes listed above.

**Collab with Dev**
- [x] Set up a meeting to collaborate with the developer who will be implementing the design.
- [ ] See if there's an existing Drupal module that can be used to achieve the intended design.

**Create Follow Up Tickets**
- [x] Create a github ticket using [this template](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/new?assignees=BlakeOrgan&labels=CMS+design+system%2C+CMS+design%2C+CMS+Team%2C+Needs+refining&projects=&template=cms-design-system-documentation.md&title=Update%2Fadd+%3Cinsert+topic+here%3E+in+the+design+system+documentation.) to update the CMS Design System Documentation in Figma and link to it as a comment in this ticket.
- [x] Create a github ticket using [this template](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/new?assignees=edmund-dunn%2C+tonytaylor&labels=CMS+design+system%2C+CMS+Team%2C+Needs+refining&projects=&template=cms-design-system-dev-implementation.md&title=Implement+%3Cinsert+topic+here%3E+from+the+design+system.) for a developer to update the [CMS Storybook](https://storybook-stdirdt4jxl4xlaze1syc4vdz1pb9gvr.ci.cms.va.gov/?path=/story/introduction--page) and link to it as a comment in this ticket.

**Comment by BlakeOrgan** [comment]
There are currently multiple ways to do a multiselct in the CMS. [Ticket #11490](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11490) discusses one way that is not widely used because it is not intuitive and did not go through a design review before being implemented. We should change anywhere that uses the multiselct pattern in [ticket #11490](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11490) to whatever pattern is decided on as part of this design ticket.

**Comment by jilladams** [comment]
Note: PW also has an exploratory ticket open that could slot in here and either PW could run with or CMS Team could take it: #13232 .

**Comment by BlakeOrgan** [comment]
Update on this. The designs for how a multiselect dropdown component could look can be found in [this Figma link](https://www.figma.com/file/dLiV79QpWrpdwsTDC2veJW/Design-System-Playground?type=design&node-id=741%3A3114&mode=design&t=ZfPcu1ay6ynbgXjJ-1) inside the Design System Playground.

Neither the USWDS or the VA Design System had a solution that we could use to achieve our goal of a multiselect dropdown.

We explored several potential Drupal modules to achieve this functionality, but none met accessibility standards from @laflannery 

A couple of the modules that we explored are listed below:

- [Virtual Select](https://www.drupal.org/project/virtual_select) 
- [Select2 Multicheck](https://www.drupal.org/project/select2_multicheck)
- [Bootstrap Multiselect](https://www.drupal.org/project/bootstrap_multiselect)


It was determined that in order to achieve this functionality in an accessible manner, the team would need to build a solution from scratch and contribute it back to the Drupal community.

I have created an [implementation ticket](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15214) for when the team figures out how we want to implement this design. Since there might be some additional design changes based on how it's decided that we implement this component, I am going to hold off on making this into an official component in the Design System for other teams to start using until that process has been finalized and we're confident that the component is ready for other teams to start using.

Once the design and implementation of this component has been done and is ready for other teams to start using, I've created a [design system documentation ticket](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15215) so that other teams can start to use the component when it's ready.
