### ISSUE TITLE
Replace React component with Web Component: AlertBox

### ISSUE THREAD

**Issue by ryguyk** [department-of-veterans-affairs/va.gov-cms#13502]
## Description
See [audit of Facilities' React components that need to be replaced with Web Components](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13179#issuecomment-1520648960).

One of the components that was identified is `AlertBox`. This ticket is to implement the replacement with the appropriate Web Component.

## Acceptance Criteria
- [ ] All instances of `<AlertBox>` are replaced with `<va-alert>`
- [ ] For each replacement, it's confirmed that the replacement results in no UI/UX changes, or, if they do result in changes, those changes are documented.

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [ ] `Public Websites`
- [x] `Facilities`
- [ ] `User support`

**Comment by kmariepat-cityfriends** [comment]
@maxx1128 is this card in the correct status lane

**Comment by kmariepat-cityfriends** [comment]
@maxx1128 is this card in the correct status lane

**Comment by maxx1128** [comment]
> @maxx1128 is this card in the correct status lane 

Yes, the pull requests got merged earlier today so it's closed.
