### ISSUE TITLE
Facility Locator Design Iteration #2 

### ISSUE THREAD

**Issue by kmariepat-cityfriends** [department-of-veterans-affairs/va.gov-cms#13511]
##### Acceptance Criteria 

I expect the following updates are explored per the feedback given in 4/26 meeting:

- [x] Accessibility review (with @laflannery post-PTO) is performed on these cards 
- [x] update filter to say `postal code or city, state` make sure this language is updated everywhere this verbiage appears 
- [x] explore putting 'for better results' into additional info component; get accessibility review on this 
- [x] get accessibility feedback on `view all filters` should say something like `filter these results` `additional filters`
- [x] what happens when there's only one filter, explore potentially not using a modal, overall think about progressive filter reveal in another way 
- [x] use sentence case for provider core training 
- [x] show what the experience will be if more than one filter available

**Comment by mmiddaugh** [comment]
@kmariepat-cityfriends @thejordanwood - adding some of my notes from Design review discussion
- OK to remove Coronavirus update at the top of page when the design update is implemented
- Re: geographic filter requirements (postal code or city, state)  
  - May want to get content input on the best way to clarify search parameter expectations 
  - May want to confirm with data from GA or DOMO for how Veterans most commonly search now, if available
- Evaluate options in Design system for selecting from a drop down vs dynamic search 
   - [Select component usage](https://design.va.gov/components/form/select#usage)
   - [Search input with type-ahead](https://design.va.gov/components/search-input#usage)
- View within state may be a subsequent iteration
- Get content input on wording for Provider training flag 
   - I'm curious about what, if anything, we know about Veteran familiarity with the concept of the provider training - will they understand what this flag means?
- Service type for Vet Center to be implemented

**Comment by mmiddaugh** [comment]
To document for my background, these filters are for future use and may be implemented at separate times
