### ISSUE TITLE
Update Events CMS feature toggle to expose Events checkbox to a specific set of usernames

### ISSUE THREAD

**Issue by kmariepat-cityfriends** [department-of-veterans-affairs/va.gov-cms#13529]
## User story
As a product owner, I want to ship an update to a small group of editors to verify it is easy to use, before rolling out change management to all Events editors.

## Description
Expand the CMS Feature Toggle binary on/off for National Events calendar checkbox to allow the feature to be visible to a subset of users.

List of emails is available in DSVA slack: https://dsva.slack.com/archives/C52CL1PKQ/p1697148973755669?thread_ts=1697148950.813469&cid=C52CL1PKQ

##### Acceptance Criteria 
- [x] Events CMS feature toggle, when enabled, will only expose the feature to specific Editors listed, and Drupal Admins

**Comment by jilladams** [comment]
@dsasser @chri5tia this ticket is regarding this earlier [thread in Slack](https://dsva.slack.com/archives/C52CL1PKQ/p1696610411984349?thread_ts=1696434452.043579&cid=C52CL1PKQ) , around the idea that the Events-related feature toggle could be expanded to enable display to a subset of users. 

Dave will be having some conversations in the next couple of days that will help us know if this is required. If so, it's likely to be that we expand to show to a set of explicit users by username/email. If that's required, we will need to inject into sprint, and it will slot in after the Events related sprint goal. (It will deprioritize the Notifications framework discovery). 

Please let me know if you have questions / concerns. A stab at points would also be much appreciated, based on the assumption we'll be enabling for a list of ~3-10 usernames.

**Comment by dsasser** [comment]
> @dsasser @chri5tia this ticket is regarding this earlier [thread in Slack](https://dsva.slack.com/archives/C52CL1PKQ/p1696610411984349?thread_ts=1696434452.043579&cid=C52CL1PKQ) , around the idea that the Events-related feature toggle could be expanded to enable display to a subset of users.
> 
> Dave will be having some conversations in the next couple of days that will help us know if this is required. If so, it's likely to be that we expand to show to a set of explicit users by username/email. If that's required, we will need to inject into sprint, and it will slot in after the Events related sprint goal. (It will deprioritize the Notifications framework discovery).
> 
> Please let me know if you have questions / concerns. A stab at points would also be much appreciated, based on the assumption we'll be enabling for a list of ~3-10 usernames.

This is rather trivial to implement. Currently we have an `isCheckboxEnabled` property that is used throughout the code to control display and processing. We would expand on the logic that sets this property to include a username condition. This would be a '1' in terms of points.

**Comment by jilladams** [comment]
"2"ing for safety / testing / verification, but noted! Thank you.

**Comment by jilladams** [comment]
Michelle provided me a list of 12 users today who will be enabled here. Pulling this ticket into sprint. It's blocked by resolving #15641 and re-shipping the checkbox feature, so we _could_ use an integration branch to test both at the same time, and merge as one shebang. @dsasser I'll let you opine about that next week. 

This injection officially pushes #15533 down in priority and will move it across the sprint line to an unknown extent. (Will note on that ticket as well.

**Comment by dsasser** [comment]
> Michelle provided me a list of 12 users today who will be enabled here. Pulling this ticket into sprint. It's blocked by resolving #15641 and re-shipping the checkbox feature, so we _could_ use an integration branch to test both at the same time, and merge as one shebang. @dsasser I'll let you opine about that next week.
> 
> This injection officially pushes #15533 down in priority and will move it across the sprint line to an unknown extent. (Will note on that ticket as well.

The code changes for this ticket were bundled with the work for #15641, so no integration branch is necessary at this time.
