### ISSUE TITLE
Design Selection UX

### ISSUE THREAD

**Issue by kmariepat-cityfriends** [department-of-veterans-affairs/va.gov-cms#13528]
##### Background 
Editorial design for publishing one event to multiple lists 

##### Acceptance Criteria 
- [ ] provide a means to determine which calendars the event will be posted on (not multiselect) 
- [ ] create a wireframe for the above proposed solution 
- [ ] review wireframe with @BlakeOrgan 
- [ ] NOTE: this wireframe will be reviewed with editors by UX Research resources as next steps

**Comment by mmiddaugh** [comment]
@jilladams is this still valid? If so, should it belong to Facilities or Public Websites?
