### ISSUE TITLE
URL Change for: Huntington VA Clinic  [Waiting on Facility Locator to redirect]

### ISSUE THREAD

**Issue by stefaniefgray** [department-of-veterans-affairs/va.gov-cms#13545]
### Implementation date
When does this request need to be live:
7/19/2023

See linked ticket: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13546

⚠️ NO REDIRECT NEEDED ⚠️ 
(as this is a new facility)

### Instructions for canonical URL change
- [x] Verify that the new URL for the facility is published and accessible on VA.gov.
- [x] Update the [CSV in Lighthouse](https://github.com/department-of-veterans-affairs/lighthouse-facilities/blob/master/facilities/src/main/resources/websites.csv) with the changed URL, maintaining the sorted order of the Facility API IDs.
- [x] Create a PR in the [lighthouse-facilities repo](https://github.com/department-of-veterans-affairs/lighthouse-facilities), tagging the Lighthouse team.
- [x] Post a message in the #api-facilities channel in Slack, with an @mention to a Lighthouse team member.
- [x] Validate that the change has deployed by checking that the Facility Locator has been updated with the new url.

#### URL change example (update with actual ID and URL)
| Facility API ID  |  Full VA.gov URL |
| ---  |  --- |
| vha_610GF | https://www.va.gov/northern-indiana-health-care/locations/huntington-va-clinic |

**Comment by omahane** [comment]
The https://github.com/department-of-veterans-affairs/lighthouse-facilities is currently locked down in a way that I can't make a PR against it. For now, I'm sending my changes directly to Adam Stilton:
https://dsva.slack.com/archives/C02BTJTDFTN/p1690826180027919

**Comment by stefaniefgray** [comment]
@omahane Thanks for the update! Have updated https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13546

**Comment by omahane** [comment]
The CSV has been deployed, and the facility is in the Facility locator.
