### ISSUE TITLE
IncLim BE: Implement business rules to return limits to FE per API design

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#13558]
### User story

**AS A** PM/PO
**I WANT** the Income limits API to reliably return limits to the front-end based on the API design
**SO THAT** Veteran-facing products can present the results.

### Engineering notes / background

- API design documented in #12584 
- Business logic documented in #13582
- Provide all limits, even in cases where the geographic means test limit (GMT) is below the national means test limit (NMT). (The product can make the determination not to show the GMT.)

Error cases in [comment below](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13558#issuecomment-1565028467).

### Analytics considerations
n/a

### Quality / testing notes

- What pattern are we following for testing, documentation, etc?
- QA for income limits themselves is defined as "return the same numbers as VES" Joshua Faulkner told us we can get test-case data for comparison directly from [VES](https://dev.ves.va.gov/esr/) (must be on VA network).

## Acceptance criteria

- [ ] API returns necessary limits pre API design
- [ ] API returns specific error messages for specific error cases
- [ ] There is no aid-and-attendance, housebound, or relaxation threshold in API response
- [ ] Add to engineering documentation the link to swagger self-documentation on vets-api and to the README

Testing ACs:
- [ ] For the following tests, grab 4 test cases from VES covering various cases
  - [ ] Kansas City with 2 dependents
  - [ ] Past year with 8 or more dependents
  - [ ] Past year with zero dependents
- [ ] Unit tests on all mathematical methods, using mock data
- [ ] Integration testing with live database: 
  - [ ] test against the database that Rails spins up for testing (vets-api practice)
  - [ ] ~~ticket creation of synthetic tests in Datadog (follow best practice for vets-api)~~
  - [ ] Confirmed that Sentry logging is working correctly

**Comment by wesrowe** [comment]
Estimated as an 8 due to uncertainty around the specifics of business rules (not yet documented) and lack of familiarity with testing patterns expected.

**Comment by jilladams** [comment]
This is blocked by #13582 , WIP. By Friday 5/12, we think that blocker will be done.

**Comment by wesrowe** [comment]
Error messaging from a slack message from @jtmst: 

>There will be a couple extra responses available that were not included in the design, both status 422.  One will be return a 422: Invalid Zipcode response, and the other will return an “Invalid Parameters” response.     The latter would return if a param was missing or outside the range of expected inputs (ie if the year was 1854).   I’ll be sure to add these to the documentation

**Comment by jtmst** [comment]
Some changes in the spec and feedback from early reviews will result in this rolling over.  Work around how error handling/validation/tests is still being done.  The core business logic is complete but this is not yet ready to merge
