### ISSUE TITLE
Extra line break being added in Limited Rich text editors in CMS

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#13550]
## Describe the defect
In Limited rich text editors, when a line break is added `<br>`, an additional break is injected once the content is saved.

When testing I found that this is not happening with Full rich text editors, only limited.

## To Reproduce
1. Go to https://staging.cms.va.gov/resources/how-do-i-notify-va-of-my-intent-to-file
2. Click on Edit and view the source of the Answer field.
3. Notice that there is only one line break at the end of each line of the address
4. Also notice that in the standard view, there is the proper amount of space between each line of the address.
5. Save the content so you will be taken to the View screen
6. Notice that there is now an extra space between each line of the address and upon inspecting there are 2 line breaks in the code

## Screenshots
![image](https://user-images.githubusercontent.com/106678594/235471750-40702284-cfad-460d-add7-6460ba4b9fc7.png)

![image](https://user-images.githubusercontent.com/106678594/235472119-e6ab58bf-4481-4075-b224-897e19f661de.png)

![image](https://user-images.githubusercontent.com/106678594/235472219-33dd3efe-2d6b-4ded-bd6c-3f258d7f9248.png)

## AC / Expected behavior

- [ ] The HTML in the View should match the HTML in the source code, no additional HTML should be added.

 ## Additional context
I tested this on another content type with a limited rich test editor and the same behavior happened. I also tested this using a Full rich text editor and this did not happen, only 1 `<br>` showed in the View screen.

### Team
Please check the team(s) that will do this work.

- [x] `CMS Team`
- [ ] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`

**Comment by productmike** [comment]
@edmund-dunn @tonytaylor  I promised Laura I'd mention this to you for refinement today, but totes forgot. What LOE would you give on this defect?

**Comment by productmike** [comment]
Refinement 7/26: 
- hold for validation after D10 and CKEditor5 push per @edmund-dunn @tonytaylor

**Comment by EWashb** [comment]
@BerniXiongA6 can we get this one refined soon?

**Comment by BerniXiongA6** [comment]
Hey @edmund-dunn @tonytaylor -- I'll reach out when I'm back tomorrow to help us get this ticket async refined. In the meantime, could you both have a peek and comment with any questions you might have ahead of refining? Thanks!

**Comment by BerniXiongA6** [comment]
Hey @tonytaylor we'll be pulling this into S97 -- we can refine today at Planning. thanks! cc: @EWashb

**Comment by EWashb** [comment]
@BerniXiongA6 remind me. Did this officially get pulled in? I would like to update CAIA and align expectations.

**Comment by BerniXiongA6** [comment]
@EWashb sorry for the delay, we pulled this into Sprint 97. @tonytaylor will be working on it.

**Comment by BerniXiongA6** [comment]
Hey @tonytaylor can I ask you to size this ticket? Sorry I forgot to ask this at Sprint Planning, thanks!

**Comment by tonytaylor** [comment]
## Core Issue

This issue boils down to two filters: `Limit allowed HTML tags and correct faulty HTML` and `Correct faulty and chopped off HTML`.

They have filtering/normalization operations that inadvertently turn `<br />` into `<br>` -- this clashes with a rule that will prevent adding extra tags if an explicit `<br />` is found at the end of a line.  For testing purposes: you can turn off both of these filter rules (turning off both are required -- configuration page is @ /admin/config/content/formats/manage/rich_text_limited) and voila, no more double spacing issue. 

![20231121--1454](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/607178/489ad2da-32c4-4d47-964a-39e9ae31820e)


Below is the captured before/after output of the filters:

`Limit allowed HTML tags and and correct faulty HTML`
![20231120--0939](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/607178/37bf6c1d-1691-44fb-b263-45e7ba114941)

`Correct faulty and chopped off HTML`
![20231121--1402](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/607178/cd0a069b-d5de-476a-946a-b54563fe43d0)

## Next Steps

- Create d.o issues detailing what we found in these funky filters (by EOD 11/22)
- If this is a high-priority need, provide a temporary patch that changes the EOL regex target from `<br />` to `<br>`

**Comment by EWashb** [comment]
@tonytaylor just so I follow, this issue is bigger and requires more work?

**Comment by tonytaylor** [comment]
Afraid so.  The tag appears to get stripped within an object that handles
data sanitization.  My thinking is this will get more eyes on the issue.

**Comment by EWashb** [comment]
@maortiz-27-80 @BerniXiongA6 @tonytaylor Do we have additional tickets created for this?

**Comment by tonytaylor** [comment]
@EWashb Just got started drafting a follow-up.  Perhaps we can review at refinement tomorrow?

**Comment by maortiz-27-80** [comment]
@tonytaylor - That would be great if you could create the follow up ticket.  Let us know once complete and we can add it to https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16229 to refine and prioritize tomorrow. cc: @BerniXiongA6 @EWashb

**Comment by BerniXiongA6** [comment]
Hey @tonytaylor what's that follow-up ticket number so I can add to refinement? cc: @EWashb @maortiz-27-80 @ndouglas

**Comment by tonytaylor** [comment]
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16232
