### ISSUE TITLE
URL Change for: Seguin VA Clinic (Closed)

### ISSUE THREAD

**Issue by stefaniefgray** [department-of-veterans-affairs/va.gov-cms#13553]
### Implementation date
When does this request need to be live:
As soon as possible

Original ticket: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13552

### Instructions for URL redirect
(Note: This issue will be used from initial request through implementation to ensure all individuals working on this are notified of status updates.  Please do not create multiple issues to track different steps.)
- [x] Notify VA stakeholders as appropriate.
- [x] Link the related facility closure / rename issue.
- [x] Create a URL redirect in the [devops](https://github.com/department-of-veterans-affairs/devops) repo in `ansible/deployment/config/revproxy-vagov/vars/redirects.yml`
- [x]  Redirects deploy weekly on Wed. at 10am ET, or by requesting OOB deploy (of the revproxy job to prod) in #vfs-platform-support. After deploy, validate that the URL redirect is deployed. (Note: In the event of a facility closure or a name change,  validate that this occurs before making the Lighthouse csv changes.)
- [x]  Notify helpdesk via comment on ticket or Slack message in #cms-support that changes are ready for review.  

#### URL Redirect
| Current URL  |  Redirect Destination or New URL |
| ---  |  --- |
| https://www.va.gov/south-texas-health-care/locations/seguin-va-clinic/ | https://www.va.gov/south-texas-health-care/locations/ |

### Instructions for canonical URL removal
- [x] Try to find the facility via the Facility Locator, using the Facility API ID (e.g. https://va.gov/find-locations/facility/"facility_api_id"). If it is not available, proceed.
- [x] Update the [CSV in Lighthouse](https://github.com/department-of-veterans-affairs/lighthouse-facilities/blob/master/facilities/src/main/resources/websites.csv) removing the row with the Facility API ID.
- [ ] Create a PR in the [lighthouse-facilities repo](https://github.com/department-of-veterans-affairs/lighthouse-facilities), tagging the Lighthouse team.
- [ ] Post a message in the #cms-lighthouse channel in Slack, with an @mention to a Lighthouse team member.
**Note: there's no check to see if it's not returning anything, as it should already be not showing anything in the Facility Locator.**

#### URL change example (update with actual ID and URL)
| Facility API ID  |  Full VA.gov URL |
| ---  |  --- |
| vha_671GN | https://www.va.gov/south-texas-health-care/locations/ |

**Comment by omahane** [comment]
@stefaniefgray @TroyA6 The redirect has been deployed. The parent ticket can now be worked.

**Comment by stefaniefgray** [comment]
#13552 complete -- closing!

Thanks @omahane 🚀
