### ISSUE TITLE
March and April log analysis

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#1355]
Acceptance Criteria
- [x] Content is extracted from channels
- [ ] Content is anonymized (in progress)
- [ ] Coding is complete in Reframer (in progress)
- [ ] Analysis is done
- [ ] Slide deck is done
- [ ] Readout happened
- [ ] Readout slide deck is in GitHub

**Comment by cmaeng** [comment]
March/April and future log analysis will be put on hold until further research into how they will fit into the overall design strategy is complete. Looking to get a better understanding of the why, whom it'll serve, and what sensors will be used.

**Comment by oksana-c** [comment]
this will be replaced w/ helpdesk triage processes in Q1 2021. Closing.
