### ISSUE TITLE
Explore ways to reduce risk space around "Sandy's database"

### ISSUE THREAD

**Issue by davidmpickett** [department-of-veterans-affairs/va.gov-cms#13570]
## Description
"Sandy's Database" is currently the source of truth for all VBA facility information in Facility Locator & Facilities API. @davidconlon is currently the only person who can update that database. If a request to update that database comes in when he is on PTO, that is blocked until he returns.

This issue will eventually be resolved by the VBA modernization making Drupal the source of truth for VBA facility information. In the interim, do we need to have a backup method of updating the database to reduce the reliance on Dave C's availability?

Do we have a clear roadmap for when in the VBA modernization we could retire Sandy's DB? Pre-MVP? With MVP? Fast follow?

## Acceptance Criteria
- [ ] Testable_Outcome_X
- [ ] Testable_Outcome_Y
- [ ] Testable_Outcome_Z
- [ ] Requires design review

**Comment by davidmpickett** [comment]
per @davidconlon in refinement "This will be solved by me giving @mmiddaugh access once she has a working computer. Vendors can not be given access."

**Comment by davidmpickett** [comment]
Slack thread where this came up for context: https://dsva.slack.com/archives/C0FQSS30V/p1683048506799779

**Comment by mmiddaugh** [comment]
I am gaining access to this data - we can close this issue.
