### ISSUE TITLE
VA Maryland Contact Us page: Public Affairs number shown in Google search result teaser

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#13574]
## Describe the defect

VA Maryland Contact Us page includes many phone numbers, managed in paragraphs (unstructured content). None are listed as primary / main.  The Public Affairs phone number (**410-605-7464**) is pretty far down page, but is shown in Google search results teaser. The editor who reported said the Public Affairs office is receiving increased call volume. 

* Helpdesk ticket: https://va-gov.atlassian.net/browse/VAHELP-5693
* **CMS Node**: https://prod.cms.va.gov/maryland-health-care/contact-us
* **FE page**: https://www.va.gov/maryland-health-care/contact-us/
* Slack thread: https://dsva.slack.com/archives/C0FQSS30V/p1682983945584309

## Screenshots / repro
[Google search: VA Maryland contact us](https://www.google.com/search?q=va+maryland+contact+us&ei=1kxQZP77O72E0PEPsryZiAo&ved=0ahUKEwj-vu3DpNX-AhU9AjQIHTJeBqEQ4dUDCBA&uact=5&oq=va+maryland+contact+us&gs_lcp=Cgxnd3Mtd2l6LXNlcnAQAzIFCCEQoAEyBQghEKsCOgoIABBHENYEELADOggIABCKBRCRAjoFCAAQgAQ6BwgAEIoFEEM6BwguEIoFEEM6CAgAEIoFEIYDOgYIABAWEB5KBAhBGABQlwJYogxgrQ1oAXABeACAAWCIAZgHkgECMTGYAQCgAQHIAQjAAQE&sclient=gws-wiz-serp)

![Screenshot 2023-05-01 at 4.36.41 PM.png](https://images.zenhubusercontent.com/624dd6bb7d958ceb206d043b/45ecca3b-b5cb-44df-b089-a867fc7f9474)

This phone number doesn't appear in results for just [Google search: VA Maryland](https://www.google.com/search?q=va+maryland&oq=va+mary&aqs=chrome.0.69i59j69i57j69i64j69i60l3.1696j0j1&sourceid=chrome&ie=UTF-8). 
<details>
![Screenshot 2023-05-01 at 4.36.29 PM (1).png](https://images.zenhubusercontent.com/624dd6bb7d958ceb206d043b/0198edb8-c17e-4c1f-b925-c517dbdb4fc1)
</details>

## Acceptance criteria

- [ ] One or many primary phone numbers are listed for VA Maryland
- [ ] Google search results no longer tease the Public Affairs phone number (is this a reasonable AC?)

**Comment by jilladams** [comment]
Other random notes: 
* Not sure how we know what the primary / main phone number _should_ be
* Unclear if / how we can get Google to re-crawl the website. Figuring that out should maybe be an AC?
* Swirt noted: The FE variants of the page should be using [schema.org](http://schema.org/) and that should help guide what number is surfaced to search engines as the main number. This is editor generated content in a paragraph, though, so unclear how to go about that without adding more CMS content structure. 
* Per Michelle, there are backlog tickets for wrangling the Contact Us page to be more structured. Didn't dig for them today.

**Comment by jilladams** [comment]
https://dsva.slack.com/archives/C52CL1PKQ/p1683642409071949?thread_ts=1682025826.324029&cid=C52CL1PKQ
 
Per DaveC: 
>  this is a content thing. The first place on the page where there is a phone: label is for media and press, which is why that is showing up. It's missing from other places.
They should add Phone: before each of the labels and it should resolve.

Request to @stefaniefgray in Slack to send this info back to the Editor to confirm if that resolves the issue, at which point we can close.

**Comment by stefaniefgray** [comment]
Editor is notified of how to resolve, waiting on response

**Comment by stefaniefgray** [comment]
Instructed editor in https://va-gov.atlassian.net/browse/VAHELP-5693 on how to resolve

"That is amazing! Good job figuring it out! Thank you for all the help!!" :) 

All is well, can close
