### ISSUE TITLE
I.L. FE: Build core application screens for current year with placeholder text

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#13585]
### User story

**AS A** Veteran
**I WANT** to see the income limits for a single (mocked) combination of zip, dependents, and year
**SO THAT** I'm sure the app can deliver values as expected.

***The goal of this ticket is bare bones necessary to connect to API, nothing more***

**Not in scope:**
- no intro screen (this may be in Drupal instead of app; will add later if needed)
- no logic for case where GMT < NMT (aka the "Jonesboro case")
- no "real" text (invent placeholder text that is obviously not real)
- no yes/no questions in flow – i.e., even if PO/PM determine that we'll ask a yes/no question like "do you receive a VA Pension?" in the MVP, it will not yet be built. (Our goal is to get data functionality working asap.)
- no alternate UX flows within app (i.e., no edit functionality for data entered, no "shortcut/knockout" questions)
- no previous year flow
- no breadcrumbs

### Engineering notes / background

Comps are in [Sketch](https://www.sketch.com/s/a8506c94-a5bd-4a69-91ff-fe06545f3126) – make sure "current" tab is selected. Detailed UX designs will come later and include a11y markup, heading specifications where ambiguous, etc.
#13596 will complete some additional UX flow documentation.

Data mapping to database values is in this [area of Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1683232214853/cfc6da5007d8f99ee0bc83e261e118e7074ffa85?wid=0-1683306939130).

IA is in [this github comment](https://github.com/department-of-veterans-affairs/va.gov-team/issues/51132#issuecomment-1405806542). 

### Quality / testing notes

- Unit tests?

## Acceptance criteria

- [x] All of the below responds to both mobile and desktop layouts using default design system behavior
- [x] Flipper is created
- [ ] Experience is hidden by a flipper
- [x] Results screen is data-driven based on a mock API response (i.e., inputs don't affect results screen yet) - 
  - [x] mock data has shape of future API response, documented in [this comment](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12584#issuecomment-1446629888) (but definitely cross-check with the mock response built into the initial version of the income limits API)
  - [x] mock data should be of "typical" shape, where GMT > NMT
- [x] Screens exist _with placeholder/junk content_ for the "core" app screens, which _do not include any yes/no questions_:
  - [x] Zip code input
  - [x] Dependents input 
  - [x] Review Info screen (read-only, no edit links)
  - [x] Results screen
- [x] URLs for each screen are as follows:
  - [x] Base url of app is `/health-care/income-limits-temp' ("temp" path will be updated by Content team later)
  - [x] Screens have unique URLs – _discuss with Wes, may need a little research into how other form flows do urls – temps would be okay, e.g. "/zip"_
- [x] Continue and Back buttons function navigate between screens when present
  - [x] On results screen, only the browser Back button can take me to the previous screen (Results)
- [x] All income ranges are displayed correctly in accordion header text _for the typical GMT > NMT case_ – refer to this [annotated screenshot in Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1683232214853/cfc6da5007d8f99ee0bc83e261e118e7074ffa85?wid=0-1683306939130)
  - [x] accordions themselves have placeholder content
  - [x] accordions default to closed
- [x] Placeholder content _which is obviously fake_ is in place on each screen

**Comment by jilladams** [comment]
From planning: Would be helpful to provide an example API response. 

This is current shape of the data response: https://api.va.gov/income_limits/v1/limitsByZipCode/97000/2022/2, just using mock data / values.

**Comment by randimays** [comment]
This is the app configuration for the Income Limits application in `content-build`:

<img width="433" alt="Screenshot 2023-05-12 at 3 32 04 PM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/19175324/2d1bd1b5-f2d9-436e-9792-be039c6bb359">

According to [this documentation](https://depo-platform-documentation.scrollhelp.site/developer-docs/creating-a-new-application#Creatinganewapplication-Goingtoproduction), changing the `vagovprod` flag to `true` enables this application to be published in production. Until that point, `/health-care/income-limits-temp` is a 404 in production.

I did create a feature flipper right off the bat when starting this story, thinking I'd need one. So we have one in case we decide to use it later, but for now it doesn't seem to be necessary.

**Comment by randimays** [comment]
Adding some learnings from this ticket so far:
- The `content-build` changes required to register a new application are in the above screenshot
- `content-build` changes cannot be merged first. You will see a CI error that the build is looking for a corresponding CSS file from `vets-website` that does not exist yet. You have to merge your application code in `vets-website` first, then merge the corresponding registry code in `content-build`.
- If you are adding Cypress tests to the initial `vets-website` application code, they will not work in the CI. You will see a 404 for the new URL of the application because the `content-build` registry changes are not there yet. They need to be added in a future PR _after_ the initial `content-build` and `vets-website` changes have been merged.
- Make sure to follow the convention of using `import 'platform/polyfills'` in your app's entry file, and ignore the lint warning to change this import to `@department-of-veterans-affairs/platform-polyfills`. If you use the wrong import, you won't be able to load the application at `localhost:3001` locally and won't be able to get Cypress tests to work in the CI.

**Comment by randimays** [comment]
@wesrowe Moving to PO Review. This can be validated at https://staging.va.gov/health-care/income-limits-temp/

**Comment by wesrowe** [comment]
It's very exciting to review the real thing. Things I noticed:

- The url for the first screen (Zip) should include `/zip` at the end, it doesn't have a sub-path currently.
- The 3 yes/no responses on the Review screen can be eliminated. There won't be any yes/no questions in the launch version of the product.
<img width="435" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/4054752/ec71135e-a790-447e-a36b-39e0d23251c0">

**Comment by randimays** [comment]
@wesrowe The feedback from above has been addressed. Please review at https://staging.va.gov/health-care/income-limits-temp/. Thank you!

**Comment by wesrowe** [comment]
Thanks for the changes! closing

**Comment by wesrowe** [comment]
by the way, I triggered the field validation and was pleasantly surprised to see it working

**Comment by randimays** [comment]
The API response was out of date in previous comments and should be updated to:
```
"message": {
  "countyName": "Some County, XX",
  "incomeYear": 2023,
  "limits": {
    "pension_threshold": 99999,
    "gmt_threshold": 99999,
    "national_threshold": 99999
  }
}
```
