### ISSUE TITLE
I.L. UX: Document finalized UX flows for implementation

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#13596]
### User story

**AS A** PO/PM/Developer
**I WANT** a UX flow artifact that captures all the nuances of the UX design that Veterans will need
**SO THAT** we are assured to have one source of truth for implementation and testing.

[Income Limits Sketch design file ](https://sketch.com/s/a8506c94-a5bd-4a69-91ff-fe06545f3126)

### Engineering notes / background

Ben Brasso from the Check-in team provided some good examples and tools:
- Check in team's [design and user flow sketch file](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/v/yx40RA)
- Example mural of [low fi user flow w/ backend interactions](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1677530927937/7a113f5244fcac48d05c34b0cfb9c7759f92f85a?sender=u37bb983bd3fc3cc00c7d3286)
- [Annotations library in DS](https://www.sketch.com/s/aaa5c25f-6991-4aac-a6ed-d378bdff7727/p/2B20BA69-5D4D-4006-A902-6C66AFD7AAE3/canvas)
- [VAOS/Appointments design and user flow in figma](https://www.figma.com/file/xRs9s6QWoBPRhpdYCGc3cV/User-Flow?type=whiteboard&node-id=160-34302&t=scMg6sVejIy75y4T-0) (Peter and Ciera)

## Acceptance criteria

- [x] Sketch file includes key nuances of design beyond simply the layout:
  - [x] Main flow between screens
  - [x] Alternate ways to flow between screens (e.g. Edit flows)
  - [x] A11y markup, e.g., aria labels
  - [x] Error states (results screen)
  - [x] Heading levels (both semantic and styling, if different)
  - [x] Alternate versions of screens (e.g. 3-range results screen)

**Comment by thejordanwood** [comment]
**End of sprint updates:**

- Added main flow between screens 
- Added alternate ways to flow between screens (e.g. Edit flows)
- Added Heading levels (both semantic and styling, if different)
- Added mockup for GMT<NMT special case
- Added error state on the special case results screen

**Updates that still need to be made:**

- Need Danielle's updated copy for bullet points on results screen
- Need accessibility review on this. (I'm hoping to do this on Wednesday 5/24).

**Comment by thejordanwood** [comment]
All ACs on this ticket are finished, so I'm going to close this. Making a note here that we're waiting on copy for a couple of spots: 

- copy for bullet points on results screen
- copy for year selection page in the past income limits flow
