### ISSUE TITLE
I.L. FE: Add logic for case where GMT < NMT (the "Jonesboro AR case")

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#13590]
### User story

**AS A** Veteran living in a location where the zip-based Geographic Means Test threshold doesn't apply to me
**I WANT** not to see the GMT threshold at all, and have the top range based on NMT
**SO THAT** I don't see a very confusing set of numbers

See [Mural area](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1683232214853/cfc6da5007d8f99ee0bc83e261e118e7074ffa85?wid=0-1683331066052) for details.

### Engineering notes / background

GMT stands for Geographic Means Test threshold, a cost of living number set by HUD and looked up in our API by zip code. This is meant to account for how the cost of living affects a Veteran's ability to pay for health care. 

NMT is National Means Test, a single number across the country. 

In most of the country, the GMT is higher than the NMT. In these cases, there is a separate income range with different VA copay expectations in the range between the two numbers. However, in a few rural locations like Jonesboro, AR, where Jordan lives, the numbers are flipped, and GMT < NMT. In those cases GMT isn't relevant to the Veteran, so we are going to leave GMT out of the Results screen completely. Also, we will use NMT+10% for calculating the top threshold.

This UI design is documented in the [Sketch file](https://www.sketch.com/s/a8506c94-a5bd-4a69-91ff-fe06545f3126) a little to the right of the others, as a "special case."

We discussed whether this logic should live in the API vs. the front-end app. The lines are drawn as: 
* FE job is to handle cases where geographic is less than the national. 
* API will contain all information, and other API consumers can determine how to display in their apps.

### Quality / testing notes
Unit testable

## Acceptance criteria

Per [Mural area](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1683232214853/cfc6da5007d8f99ee0bc83e261e118e7074ffa85?wid=0-1683331066052):
- [x] The accordion that would typically use GMT only is hidden – i.e., the 4th one, 80%-reduced copays) – i.e., this case's benefits go straight from "free health care" to "health care with full copay"
- [x] The threshold that sets the boundary between the bottom two ranges ("full copays" and "may not be eligible) is calculated based on NMT+10% instead of GMT+10%
- [x] Unit tests implemented and Cypress functionality is added if needed

**Comment by wesrowe** [comment]
@randimays, fyi I assigned this to you for pre-refinement. When you have downtime, review the ticket for ACs, clarity, etc. You can put points on it if you know. The goal of pre-refining is for a team member to be familiar with it in the next refinement meeting.

**Comment by randimays** [comment]
This is waiting in line for code review behind #13587.

**Comment by wesrowe** [comment]
I can't test with real data – I'm not sure what to do about that. Hard to say it's done at this point. But we could close and then treat an issue (if arises) as a defect.

**Comment by randimays** [comment]
Right; we are limited with testing until the API is ready. When the back end is hooked up, this'll be part of the testing for that ticket. Closing this as complete.
