### ISSUE TITLE
GovDelivery Bulletin integration docs

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#1361]
## Description

Collect and add accurate documentation about GovDelivery Bulletin integration to GH docs. 

## Acceptance Criteria
* GovDelivery Bulletin integration is reviewed and documentation is added to GH.

**Comment by swirtSJW** [comment]
We had created some diagrams for this.  I think Elijah had access to them.   We should find those.

**Comment by swirtSJW** [comment]
I found one of the artifacts https://dsva.slack.com/archives/CDJQ0JCE4/p1576083453230200?thread_ts=1576083453.230200

**Comment by oksana-c** [comment]
closing in favor of https://github.com/department-of-veterans-affairs/va.gov-cms/issues/4595
