### ISSUE TITLE
Draft User Permission stories for VA Benefit Taxonomy

### ISSUE THREAD

**Issue by davidmpickett** [department-of-veterans-affairs/va.gov-cms#13628]
## Description
How does CAIA manage taxonomy now? What can we reuse that currently exists.

As a member of the Public Websites team, I need clearly defined user stories about the permissions different users will need throughout the lifecycle of the product. These should be written in terms that stakeholders / product owners can understand and be specific enough that Drupal engineers can implement them.

**Users to consider**
- Benefits Taxonomy Editors (Sitewide CAIA)
- Drupal Admins

**Drupal aspects to consider**
- Workflows
- Roles
- Sections
- Permissions

**Use cases to consider**
- "Immutable" fields like Official name, API ID

## Acceptance Criteria
- [ ] Create current user flows (ask CAIA)
- [ ] Revisit what is needed for MVP future user flows
- [ ] What permission.

**Comment by davidmpickett** [comment]
@wesrowe @jilladams - rough draft

**Comment by FranECross** [comment]
Closing; will add info to the Product Brief on existing permissions/user flows and new ticket(s) will be created as needed.
