### ISSUE TITLE
Q&A content type - Unlock button is disappearing on some nodes

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#13639]
## Describe the defect
On the Q&A content type in the CMS, on some nodes, the Unlock button and the warnings/notifications at the top of the node are disappearing from the screen. This doesn't seem to happen on all Q&A but on some:

- [Node 15637](https://prod.cms.va.gov/node/15637/edit)
  - unlock button is removed from the DOM completely, warning disappears from the top of the page
- [Node 47213](https://prod.cms.va.gov/node/47213/edit)
  - unlock button appears, with warning at the top of the page

I was not able to discover a pattern as to when these elements would disappear or not, the things I thought of and ruled out:
- Section:
  - Q&A's can be in different sections but I found instances in various sections where this worked and didn't work so this didn't seem to be the reason for the issue
- Standalone page:
  - The above examples both do not have a standalone page yet one works and one doesn't, so that also doesn't seem to be the reason for the issue.

### Additional Info
This might also be happening on the Step-by-Step content type but I'm not positive. It is happening on the D10 environment on [this example](https://vacms-12252-drupal-10-opslrfeufzwsvhxx2uuv1wmvjbiq7wuq.ci.cms.va.gov/node/57111/edit) But I wasn't seeing it in Prod in that same example. However, since I can't figure out exactly what makes the Unlock disappear or not I can't say for sure if it is happening on Prod or not since I didn't look at every node on prod.

## To Reproduce
1. Go to [Node 47213](https://prod.cms.va.gov/node/47213/edit)
2. Notice that there is a green warning at the top of the page
3. Scroll down to the bottom of the page and notice that there is an unlock button
4. Now go to [Node 15637](https://prod.cms.va.gov/node/15637/edit)
5. Confirm that the page has fully loaded
6. Confirm that the green warning at the top of the page as disappeared
7. Scroll down to the bottom of the page and notice that there is not an unlock button

## AC / Expected behavior

- [ ] Unlock button is persistent on Edit screens for all Q&A nodes
- [ ] CMS warnings/notifications remain persistent on Edit screens for all Q&A nodes

## Screenshots
![image](https://user-images.githubusercontent.com/106678594/236936998-cfe538d7-9142-42a2-a142-8f6f9c786a07.png)

![image](https://user-images.githubusercontent.com/106678594/236937076-bda312b1-a7df-4992-a206-d7d3271ca4f7.png)

### Team
Please check the team(s) that will do this work.

- [x] `CMS Team`
- [ ] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`

**Comment by BerniXiongA6** [comment]
Hi @tonytaylor -- I know you've started working on this ticket, so I'll move it over to In Progress for you. In the future, if you could move your tickets on the board as you make progress on them, that would be very helpful for Product and Delivery. Thanks Tony!

**Comment by chri5tia** [comment]
The unlock button is not going to show up unless the content is locked for editing, e.g. if more than one user session is opened to edit that specific content. I am not sure if this is related, will read the ticket closer soon.
