### ISSUE TITLE
content-build: Prototype pollution in webpack loader-utils

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#13635]
## Description
See https://github.com/department-of-veterans-affairs/content-build/security/dependabot/53

* The affected package is loader-utils, which should be patched to 1.4.1.
* loader-utils is added by cache-loader 4.1.0, which is deprecated
* recommendation is to update webpack to at least version 5 and use its built-in caching setup as a replacement for cacheloader: https://github.com/webpack-contrib/cache-loader
* We are already on webpack 5, so it may be possible to set up caching as directed by cache-loader and remove cache-loader entirely.

## Acceptance Criteria
- [ ] loader-utils is either updated to at least 1.4.1 or removed from content-build entirely if no longer needed

### Team
Please check the team(s) that will do this work.

- [x] `CMS Team`
- [ ] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`

**Comment by timcosgrove** [comment]
loader-utils is a dependency of cache-loader, which is specified in our own dependencies:
```
❯ yarn why loader-utils
yarn why v1.22.19
[1/4] 🤔  Why do we have the module "loader-utils"...?
[2/4] 🚚  Initialising dependency graph...
warning Resolution field "lodash@4.17.21" is incompatible with requested version "lodash@^2.4.1"
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "loader-utils@1.4.0"
info Reasons this module exists
   - "cache-loader" depends on it
   - Hoisted from "cache-loader#loader-utils"
info Disk size without dependencies: "84KB"
info Disk size with unique dependencies: "348KB"
info Disk size with transitive dependencies: "452KB"
info Number of shared dependencies: 4
✨  Done in 0.31s.
❯ yarn why cache-loader
yarn why v1.22.19
[1/4] 🤔  Why do we have the module "cache-loader"...?
[2/4] 🚚  Initialising dependency graph...
warning Resolution field "lodash@4.17.21" is incompatible with requested version "lodash@^2.4.1"
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "cache-loader@4.1.0"
info Has been hoisted to "cache-loader"
info This module exists because it's specified in "devDependencies".
info Disk size without dependencies: "196KB"
info Disk size with unique dependencies: "1.19MB"
info Disk size with transitive dependencies: "4.34MB"
info Number of shared dependencies: 27
✨  Done in 0.33s.
```

**Comment by timcosgrove** [comment]
cache-loader is deprecated and its last version is 4.1.0. The repo page recommends updating webpack to at least version 5 and using its built-in caching setup.

https://github.com/webpack-contrib/cache-loader

**Comment by timcosgrove** [comment]
This was originally introduced in this PR: https://github.com/department-of-veterans-affairs/content-build/pull/574/files#diff-c49a22733230fd83e34ff3bc78014ee352ad46ce10c7c502dd2a7c3982adb0a5

I don't see evidence in this PR that cache-loader was actually made use of. See configuration instructions at https://github.com/webpack-contrib/cache-loader.

**Comment by ndouglas** [comment]
The Dependabot alert appears to be closed per https://github.com/department-of-veterans-affairs/content-build/security/dependabot/53 after [Tim's PR](https://github.com/department-of-veterans-affairs/content-build/pull/1561). Pls reopen if I've misread.
