### ISSUE TITLE
Spike: SimpleSAML Tugboat testing (PIV auth, etc.)

### ISSUE THREAD

**Issue by productmike** [department-of-veterans-affairs/va.gov-cms#13637]
## User Story/Description
As a devops representative, I want to be sure that we are following best SDLC practices when it comes to promoting code to production and unit testing/integration into main line, so that risk is mitigated as much as possible.

Continuation linking of #12453

## Acceptance Criteria
- [x] Investigate if testing SimpleSAML updates through tugboat is possible. 
- [x] If so, document in this ticket and/or indicate location where it can be found.
- [x] Document alternatives to test CMS PIV Logon

**Comment by olivereri** [comment]
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/31904439/296285bc-44c9-4523-81f9-6358e0236f0e)

Just what I thought, finally confirmed :(

**Comment by olivereri** [comment]
Single Sign-on External (SSOe) is an available service from the Identity and Access Management team but likely won't be an appropriate test as the path and underlying technology is different. Also the configuration would be different taking us farther away from a simple, valid test. An additional wrinkle is that even if we could configure PIV login from Tugboat, we would have to do it from Citrix or GFE.  That or we add a forwarding rule in SOCKs for this domain: ssologon.iam.va.gov.  We are more constrained than I had thought while using Single Sign-On Internal (SSOi) than I had thought.

What I suppose we can do is take this ticket in a different direction and validate PIV login on CMS-Test Staging.

**Comment by olivereri** [comment]
# Testing Alternatives to Tugboat
Listed from lowest to highest effort: How can we more efficiently test changes to PIV login infrastructure without negatively effecting BRD Testing environments.
## Configure CMS-Test Staging for PIV Login

## Configure Single Sign-on External
## Move Tugboat to VA IP Space
# SAML Testing Improvements
## Add Single Sign-on Internal Domain to Socks
