### ISSUE TITLE
Facility Locator: Design Iteration #3

### ISSUE THREAD

**Issue by kmariepat-cityfriends** [department-of-veterans-affairs/va.gov-cms#13643]
- [x] I expect the designs up to this point are reviewed with Dave Conlon
- [x] incorporate accessibility feedback

**Comment by kmariepat-cityfriends** [comment]
Open Questions from @thejordanwood 

- [ ] Covid messaging is being removed
- [ ] Accessibility gave the okay on the filter modal
- [ ] Accessibility said the alphabet page was their preferred choice (talked through modal and drawer options with them too). They just want to make sure that the copy is clear that users need to select something here on that page.
- [ ] Vet Center and VA benefits flows are added. These are similar to the VA health services flow and was mainly added for developers. Design system says dropdowns are for about 7-15 items, so anything above that needs to be a search.
- [ ] “For better results…” functionality is wrong. This should only appear if no search results are found and should NOT appear before a user selects the search button.
- [ ] Questions about the state only option:
- [ ] Are the filters correct?
- [ ] Is starter page correct?
- [ ] Note: I believe this is being modeled after this search on the old site, so have made state selection required.
- [ ] I created some options if we only have one filter.
- [ ] There is a section where I commented out every accessibility improvement that Laura suggested.

**Comment by kmariepat-cityfriends** [comment]
Goals for 5/19 touchbase:

1. Accessibility has flagged several things, and we need to decide where we are drawing the line with what we are going to fix
2. Addressing the list above

**Comment by kmariepat-cityfriends** [comment]
**Notes from 5/19 Touchbase:**
- "Select a health service" confirm language with the content team 
- scrapping the browse all health services page in favor of a solution using expanded plain term health services taxonomy (keep design somewhere in case we revist)
- Look at 536 form typeahead for another example for browse all health services page 

**Design Notes that are no longer relevant:** 
- get rid of the state filer on the browse all health services page 
- Add a back to search for the browse all health services page 


**UX Research Notes:** 
- Intuitively Veterans will know that's a type ahead and it will work so they don't feel obligated to Browse all health service 
- Research if the list of services will be useful

**Comment by mmiddaugh** [comment]
[VA services](https://app.zenhub.com/files/154174777/d4cf1f94-fcc3-4ed7-b761-3a29630e7280/download)
@thejordanwood - I've attached an export of the VA service taxonomy so you can see what words/common terms are currently available for use in your Facility Locator search design. Please let me know if you have any questions

**Comment by mmiddaugh** [comment]
@thejordanwood I'd love to hear your thoughts about maintaining the "all VA health services" functionality when searching for VA health. It might also be good to see what analytics are available related to how Veterans tend to search. 

![image.png](https://images.zenhubusercontent.com/5d8a47393ac3440001d1a2ed/bcabed49-5ea0-40fa-8175-a9c796faa5c5)

**Comment by mmiddaugh** [comment]
Regarding Veteran searches for VA health facilities:
YTD through May 18, 2023

- 1,241,637 unique searches on the Facility Locator
- 1,063,254 (85.63%) did not select a service type and used the default "All health services"
- The most common VA health service type selected was Primary Care with 62,490 unique searches (5% of the searches)
-

**Comment by thejordanwood** [comment]
@mmiddaugh Thanks for digging up these statistics! Looks like we need to keep the default "All health services" on this. I don't have access to the GA view, but I just tried requesting access to it.

**Comment by thejordanwood** [comment]
@kmariepat-cityfriends @mmiddaugh Closing this and starting the [next design iteration ticket](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13792) for this.
