### ISSUE TITLE
Dev Review of Options

### ISSUE THREAD

**Issue by productmike** [department-of-veterans-affairs/va.gov-cms#13647]
## User Story
As a developer, I want to confer with other developers to ensure the option selected to handle the soft text limits is thoroughly vetted and impacts accounted for, so that consensus is built.

## Description
We need to transition any text fields that have character limits on them to text fields that allow unlimited amounts of text; the field widget for that will become 'Text with Counter'.

Existing fields need to be updated in-place. We cannot do a migration to a new field - there are too many places where errors could happen.

Continuation of: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13248#issuecomment-1522828596

## Acceptance Criteria
- [x] Approaches are discussed as a group (CMS Team, possibly folks from other teams).
  - https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13647#issuecomment-1560222166 
- [x] Course of action is decided upon and tickets written for its implementation.
  - https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13512

**Comment by timcosgrove** [comment]
Steps:
1. Identify the entity type and field you need to update (in other words, field storage).
2. Retrieve the field storage config.
3. Fetch all data from the associated table and store it for later.
4. Fetch the field config for all field instances of the field storage.
5. Fetch the form widget settings for each of those field instances, so we can restore necessary pieces.
6. Copy and update the field storage config from step 2, modifying the field type etc. Keep the previous config; it may have settings we need later.
7. Delete field storage and purge field data. This also deletes the field instances.
8. Create the field with the modified field storage config from step 2.
9. Create new field instances with the data from step 4.
10. Restore or modify the form widget settings from 5, making any necessary changes (i.e. taking character limits from former field storage and applying them to the form widget).
11. Ensure that any field config in `config/sync` is updated to match the updated config from the above steps.

We may also need to address template references to data in the event those change; investigate.
