### ISSUE TITLE
I.L. Research: Finalize findings and recommendations

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#13650]
### User story

**AS A** UX Researcher
**I WANT** to attend meetings with Dave and Danielle and get their input
**SO THAT** I can finalize the report and readout.

## Acceptance criteria

- [x] Met with Dave and Danielle to discuss findings and recommendations
- [ ] Tweaked report and deck as needed (assuming relatively minor)

**Comment by cindymerrill** [comment]
Met with Dave C yesterday, and revised recommendations in readout presentation with decisions discussed.

**Comment by cindymerrill** [comment]
Met with Danielle today, and then discussed design revisions with Wes and wrote them up for Jordan.

**Comment by cindymerrill** [comment]
Met with Dave Conlon and Danielle to show design revisions based on the research recommendations, we discussed some of them, and they were happy.

When I get back from PTO, I'll add the decisions made to each recommendation in the report and the readout. And during the readouts on May 31 (to stakeholders) and June 5 (to the VA Design/Research/Content sync), I'll ask @thejordanwood to walk through the revised design (in Sketch) at the end of my slides.

**Comment by cindymerrill** [comment]
Will close this ticket and move to https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13703 to update the readout slides and report when I return from PTO.
