### ISSUE TITLE
VIEWS Process

### ISSUE THREAD

**Issue by productmike** [department-of-veterans-affairs/va.gov-cms#13662]
## User Story/Description
As a PO, I need to internally coordinate across my organization to get approval on the delivery tool for the survey, so that I'm in compliance with existing SOPs. 

## Acceptance Criteria
- [x] Gather necessary artifacts, documentation determined by the VIEWS approval process. (word doc of survey attached)

**Comment by EWashb** [comment]
I have now provided everything needed to start the VIEWS process. It is out of our hands now, so there's no further task for this team to do right now. We just have to wait.

@productmike I am ok with closing this issue since we have that in progress. I'll update the team as I hear about progress.
