### ISSUE TITLE
Test & Merge all D10-ready Custom Modules

### ISSUE THREAD

**Issue by productmike** [department-of-veterans-affairs/va.gov-cms#13664]
## User Story/Description

Continues #13479

## Acceptance Criteria
- [ ] Merged into main branch.
- [ ] Start testing. 
- [ ] Logging and prioritizing bugs for fix or defer.

**Comment by productmike** [comment]
@laflannery  do you have bandwidth in s85 to help test here?

**Comment by laflannery** [comment]
@productmike Yes I should be able to help out here

**Comment by productmike** [comment]
@tonytaylor thanks for the update. Based on our last refinement and current state of the ACs, this ticket will need to continue into the next sprint for testing, etc. Confirming that is accurate?

**Comment by tonytaylor** [comment]
@productmike This is true.

**Comment by jilladams** [comment]
@tonytaylor for Sprint 86 reporting, could you post an update here on status of this ticket?

**Comment by tonytaylor** [comment]
@jilladams Currently awaiting clearance to merge; Beginning prep for testing.

**Comment by EWashb** [comment]
@productmike @BerniXiongA6  what are we waiting for on this?
