### ISSUE TITLE
Sunset COVID Health Status: VAMC Drupal BE (editorial interface)

### ISSUE THREAD

**Issue by kmariepat-cityfriends** [department-of-veterans-affairs/va.gov-cms#13679]
##### Acceptance Criteria 
- [x] I expect that the COVID Health status supplemental status is hidden
- [x] I expect that the supplemental status mode info is hidden 
- [x] I expect these fields are set to not required 
- [x] I expect editor facing KB articles are reviewed to note which should be modified to remove references 
- [x] I expect editor facing KB articles are reviewed to note which should be archived 
- [x]  I expect that the COVID data is pushed as NULL to Lighthouse Facilities API

#### KB articles to modify
- https://prod.cms.va.gov/help/vamc/about-locations-content-for-vamcs/about-alerts-and-operating-statuses/how-to-edit-a-vamc-facility-operating-status

#### KB Articles to archive
-  https://prod.cms.va.gov/help/vamc/editing-facility-supplemental-status-covid-19-term-descriptions
- https://prod.cms.va.gov/help/vamc/about-locations-content-for-vamcs/about-alerts-and-operating-statuses/how-to-edit-covid-19-status-for-a-vamc-facility

##### Does not relate to the **Supplemental status** field but describes in detail COVID-related operating status messaging.
- https://prod.cms.va.gov/help/va-benefit-facilities-vba/how-do-i-update-my-vba-facility-operating-status
- https://prod.cms.va.gov/help/vet-centers/how-do-i-update-my-vet-center-facility-operating-status

**Comment by mmiddaugh** [comment]
The [How do I update my VAMC Facility's Basic Location Data? KB article](https://prod.cms.va.gov/help/vamc/how-do-i-update-my-vamc-facilitys-basic-location-data) may also include reference to the COVID health status

**Comment by swirtSJW** [comment]
I think we missed an AC on this https://github.com/department-of-veterans-affairs/va.gov-cms/pull/14592#issuecomment-1662679130

**Comment by omahane** [comment]
@jilladams @xiongjaneg While all the ACs that we identified in refinement or in the beginning of the sprint were completed in [the PR](https://github.com/department-of-veterans-affairs/va.gov-cms/pull/14592), I didn't realize that we'd be sending the supplemental status information to lighthouse whenever an operating status changes until we clear out the supplemental status fields.

I started working on a script that will need to be run on production to do the cleaning up of those fields, but then Drupal 10 testing took priority over this work. The facility status push work also crowded it out. 

What's remaining to be done is the script, though I have started it. I just haven't completed it yet.

**Comment by jilladams** [comment]
Perfect thanks - and per Planning discussion, we'd originally mapped #13680 to cover that status change, so since it's happening here: we've added the AC from that ticket, and I upped the points to cover that work from 3 to 5.

**Comment by omahane** [comment]
Conversation about the data deleting implementation: https://dsva.slack.com/archives/C0FQSS30V/p1690911285219159

**Comment by jilladams** [comment]
@omahane end of sprint update?

**Comment by omahane** [comment]
@jilladams The script has been run on production. This can be closed.
