### ISSUE TITLE
COVID health status will be sunset from VA.gov

### ISSUE THREAD

**Issue by kmariepat-cityfriends** [department-of-veterans-affairs/va.gov-cms#13676]
##### Background
The health emergency end on 5/11, following the lead of the joint task force regarding implementation timeline (waiting for thumbs up from Danielle T.) On a VA health facility we currently display the COVID health protection levels on the cards, these will become meaningless

Lots of CM here, that editors will be responsible for 

##### Scope of Work
- Facility Locator FE 
- VAMC FE
- VAMC Drupal BE (editorial interface)
- Lighthouse Migration push 
- Sunset COVID 19 as a service

**Comment by davidmpickett** [comment]
Closing as All issues are complete
