### ISSUE TITLE
Remove COVID health status from VAMC product FE 

### ISSUE THREAD

**Issue by kmariepat-cityfriends** [department-of-veterans-affairs/va.gov-cms#13673]
#### Acceptance Criteria 
- [x]  I expect the COVID health status is removed from the VAMC facility page FE 
- [x] I expect the COVID health status is removed from the VAMC system operating status page FE
- [x] I expect the COVID health status is removed from the VAMC locations page FE
- [x] I expect the COVID health status is removed from the VAMC system page FE
- [x] I expect that any tests associated with the above pages are updated to account for the removal of COVID health status
- [ ] I expect the that after the removal of the COVID health status the page still looks aesthetically "good" and NOT broken; ping @thejordanwood and @kmariepat-cityfriends for design review and look at @swirtSJW original commit 
- [x] I expect it is left in the query and graphQL fields 
- [x] I expect the PR(s) are created as draft
- [ ] I expect a separate merge the PR(s) ticket is created that includes the appropriate PR(s)

**Comment by maxx1128** [comment]
I have two draft PRs with screenshots of the affected pages up, pinging @thejordanwood and @kmariepat-cityfriends for design review

**Comment by kmariepat-cityfriends** [comment]
@maxx1128 where can I find the screenshots?

**Comment by maxx1128** [comment]
@kmariepat-cityfriends 

> @maxx1128 where can I find the screenshots?

They're in the two pull requests referenced here.

**Comment by thejordanwood** [comment]
@maxx1128 This looks good to me!

**Comment by mmiddaugh** [comment]
VHA DM sent an email to VHA VAMC web editors this morning, June 1, to advise them of the plan to remove COVID-19 health protection levels from the front end of VAMC and Facility Locator. FYI, @kmariepat-cityfriends
