### ISSUE TITLE
Create Documentation for COVID Status/Supplemental Status 

### ISSUE THREAD

**Issue by kmariepat-cityfriends** [department-of-veterans-affairs/va.gov-cms#13683]
- [x] I expect product documentation is updated to note the steps of re-implementation in CMS and on the FE for this health status - limited as so far we have only removed this from the FE.  It has not been shutdown in the CMS yet.
- [x] I expect the facility status path is created and the documentation referenced above should live there: veterans-affairs/va.gov-team/tree/master/products/facilities   https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/status/supplemental_status.md
- [x] I expect backstory and business context is added to the documentation

**Comment by kmariepat-cityfriends** [comment]
Pre-assigning to @swirtSJW because he carries the most context

**Comment by kmariepat-cityfriends** [comment]
@swirtSJW also making note that maybe the pre-assignment of cards can be confusing, because this is pre-assigned to you, but in the refined product backlog and not in a sprint

**Comment by swirtSJW** [comment]
Document in progress https://prod.cms.va.gov/admin/structure/cm_document/note/118/Supplemental-Status

**Comment by swirtSJW** [comment]
Page in the team repo https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/status/supplemental_status.md

**Comment by swirtSJW** [comment]
@kmariepat-cityfriends the documentation is created and is read for you review https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/status/supplemental_status.md
