### ISSUE TITLE
Remove COVID-19 from Lighthouse Migration push

### ISSUE THREAD

**Issue by kmariepat-cityfriends** [department-of-veterans-affairs/va.gov-cms#13680]
##### Background 
the fields are in the CMS with data that has previously been pushed to lighthouse, we need to blank these out with lighthouse, by doing a push that sends NULL (or empty string) for COVID status

##### Acceptance Criteria 
- [ ] I expect that the COVID data no longer appears on Lighthouse Facilities API
- [ ] Lighthouse dependency for verification

**Comment by davidmpickett** [comment]
@omahane to review
