### ISSUE TITLE
FE: Update Facility Locator display of hours 

### ISSUE THREAD

**Issue by kmariepat-cityfriends** [department-of-veterans-affairs/va.gov-cms#13689]
## Description

Facility Locator is pulling hours directly from the Facilities API. However: in some cases, the hours allow for lunch hours. We are not parsing that correctly on the front-end to display those hours. 

### Engineering notes
[Here is the commit](https://github.com/department-of-veterans-affairs/vets-website/pull/10838/commits/d1f518b64e712c55cdd7d696f0507026cbffe923) where the code was introduced. Specifically, it's this code:
```
  // Derive the opening and closing hours.
  const hours = split(sanitizedOperatingHours, '-');
  const openingHour = first(hours);
  const closingHour = last(hours);
```

This code has the effect of breaking up the string into pieces, where those pieces are the bits between the "-" characters.
Ex:
`"8:30 a.m. - 4:00 p.m." => ["8:30 a.m.", "4:00 p.m."]`
`"8:30 a.m. - 12:00 a.m., 1:00 p.m - 4:00 p.m."  => ["8:30 a.m.", "12:00 a.m., 1:00 p.m", "4:00 p.m."]`

In all cases, the displayed opening hour is the first item in the list, and the displayed closing hour is the last item in the list. In the two examples above, the exact same result is displayed: `8:30 a.m. - 4:00 p.m.`

It's not evident that this code intentionally modifies the longer format. Rather, it's very possible that this method of grabbing the `first()` and `last()` items overlooks the possibility that the data might come over with the longer format that includes multiple open/closed slots. Notably, I cannot find any commentary around these lines of code at all. I certainly cannot find anything that speaks to intentionally changing this longer format to condense the hours. Additionally, it does not look like any unit tests are written for the longer version of the hours either. It seems quite possible that this code just doesn't consider this possible format.

Said another way, there is an intentional modification going on, but it seems like the modification might not properly accommodate all possible data formats.

**Comments:**  The additional string of hours is stored in the "Comments". FE is already displaying this.

### VBA Facilities with these weird hours
vba_339
vba_339b
vba_339c

### Context
Context: https://dsva.slack.com/archives/C0FQSS30V/p1685996475828239
FE Discovery: https://dsva.slack.com/archives/C0FQSS30V/p1683648039657469?thread_ts=1683637773.471849&cid=C0FQSS30V

There are 3 points of failure here: 
* Facility Locator = Currently pulling directly from the Facilities API -- this issue.
* VAMC pages = CMS is the source of truth -- #13649
* Facility page FE not displaying hours -- #14031

## Acceptance criteria

- [x] I expect that if a multiple time span pattern is detected bypass the special processing and the string is displyed on the front end as is
- [x] I expect that `operational_hours_special_instructions` is validated to not be mixed up with the `hours` field
- [x] I expect validating for several different benefit and cemetery locations in order to ensure handling of a cross-section of all possible data samples
- [x] I expect this documentation is updated to reflect 2 separate spans: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/facility-locator/data/hours-of-operation.md

**Comment by jilladams** [comment]
From planning, note: there a different field, Operating Hours special instructions. That field can include weird data / pipes, etc. We don't _think_ that field will come into play here. If it does: we may need to revisit ACs / estimate.

**Comment by jilladams** [comment]
Auto-closed by merging the PR. Reopening in order to make sure we verify in Prod after deploy, @maxx1128 . To prevent auto-closing in future, can use "relates to" in PR body, instead of "Closes."

**Comment by jilladams** [comment]
Noting: of the 3 locations listed, all are VBA. VBAs are not published to prod, so not clear how to verify in prod. 

Also need to verify that the AC around documentation is complete.

**Comment by jilladams** [comment]
Was reported incomplete in Sprint 86. Added to S87 to make sure it gets reflected in reporting, that documentation was done.
