### ISSUE TITLE
Research: Update recommendations in presentation and report 

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#13703]
## Description

**AS A** UX Researcher
**I WANT** to update my artifacts with final decisions on recommendations
**SO THAT** the story I present to stakeholders and others is complete.

## Acceptance criteria

- [x] Updated slide deck in preparation for stakeholder readout scheduled for May 31 and Weekly VA Design Sync June 5. (This includes having removed the extra content recommendation slides at the end, and introducing @thejordanwood to walk through the revised design in Sketch.)
- [x] Updated report in github

**Comment by cindymerrill** [comment]
Done adding decisions for each recommendation to the report and to the presentation
