### ISSUE TITLE
Inconsistent displays for phone numbers within VAMC health service accordions

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-cms#13705]
## Describe the defect
The VAMC front end service location details do not consistently respect CMS editorial input. 

## To Reproduce
1. Go to https://prod.cms.va.gov/node/10160
2. Scroll down to the Facility descriptions for Mental health care - Richmond VA Medical Center and view the Appointments content
3. Observe the specified "Appointment phone number" label
4. Go to [Richmond VA Medical Center](https://www.va.gov/richmond-health-care/locations/richmond-va-medical-center/)
5. Scroll down to Mental health care under Health services and open the accordion. 
6. Observe the Appointment phone number is not labeled
7. Return to the node: https://prod.cms.va.gov/node/10160
8. Scroll to the first service location (Mental Health Service in Building 500). Note the option to display the general facility number is selected. 
9. Return to the rendered page to observe it is not displayed for the first service location (the one open 7:30 to 4:30).
10. In CMS, scroll to the second service location, using the facility's street address, open 24/7. Note the same option to display the general facility number is selected for the second service location (open 24/7) but a second phone number is also added, specifying the label "Administrative Office" is rendered
11. Return to the rendered page to observe the "Administrative Office" label following the Hours listing

## AC / Expected behavior

- [x] The facility phone number should be rendered within the front end's service accordion for that location if the option to display the general facility phone number has been selected for a service location's contact information. 
- [x] I expect that Phone number labels should be displayed when they have been specified
- [x] I expect that any phone number is using the phone number component 
- [ ] I expect that if necessary @thejordanwood is consulted for a design review 

## Screenshots
<details>
<summary> CMS editorial input </summary>

 ![image.png](https://images.zenhubusercontent.com/5d8a47393ac3440001d1a2ed/a2f3e8ae-6910-4bc6-904e-ca858ca39de2)

![image.png](https://images.zenhubusercontent.com/5d8a47393ac3440001d1a2ed/c0aeb025-88d4-4a66-8ffd-5eb7de46c56e)

![image.png](https://images.zenhubusercontent.com/5d8a47393ac3440001d1a2ed/bb805717-e963-4c85-99c8-5f83b76c670b)

</details>

<details>
<summary>FE display </summary>

![image.png](https://images.zenhubusercontent.com/5d8a47393ac3440001d1a2ed/823666ef-e744-4819-b14a-fc1a2915332c)

![image.png](https://images.zenhubusercontent.com/5d8a47393ac3440001d1a2ed/3a509025-17f8-4ab7-a0e2-21014524cc5e)
</details>

 ## Additional context
Add any other context about the problem here. Reach out to the Product Managers to determine if it should be escalated as critical (prevents users from accomplishing their work with no known workaround and needs to be addressed within 2 business days).

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Defect")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS workstream (orange) (not needed for bug tickets)
- [ ] CMS-supported product (black)

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [ ] `Public Websites`
- [x] `Facilities`
- [ ] `User support`

**Comment by kmariepat-cityfriends** [comment]
Next steps: size with FE dev present

**Comment by jilladams** [comment]
From scrum: 
* Listings right now show: 
    * Mental Health Service 
    * Hours
    * Phone
    * Hours
    * Phone
* We want to figure out a subhead to appear over the 2nd chunk of hours / phone, to distinguish them, when mental health info appears
* Refinement tomorrow will discuss, probably a separate ticket, given that these ACs are fulfilled, adn current state is a net improvement.

**Comment by ryguyk** [comment]
> * **Refinement tomorrow will discuss, probably a separate ticket**, given that these ACs are fulfilled, adn current state is a net improvement.

Per @thejordanwood, this should likely wait until VBA because this problem is being worked on in that context and can likely be matched on VAMCs after it's ironed out with VBA.
