### ISSUE TITLE
Create new KB article or update  existing article : Updating Vet Center data in VAST

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-cms#13701]
## Background context
**What is the request for?**
- [ ] Create new article
  - [ ] I have reviewed the Knowledge Base to confirm that an article for this topic does not already exist
- [x] Update existing article: [How do I update my Vet Center Facility's Basic Location Data?](https://prod.cms.va.gov/help/vet-centers/how-do-i-update-my-vet-center-facilitys-basic-location-data)

---

Within "How to update Basic Location Data for Vet Centers, Outstations, and Mobile Vet Centers" there is a table for editors with appropriate actions to take to request updates to Facility data, depending on the type of change which is needed. 

**Current info:** For changes to Facility Address, Phone Number of Hours of Operation, the editor is instructed to Email the Vet Center RCS Help Desk. 

**New process:** For changes to facility address, phone number, or hours of operation, editors should complete a Request to Change Vet Center Information form which is linked from the [VAST Updates – Readjustment Counseling Service (RCS) page](https://vaww.vetcenter.va.gov/vast-updates/).

---

## If requesting a new article:
**Topic Description**
Details about the topic. If possible, include an example of a use case or situation that illustrates the topic well.
- [topic description]

**Audience**
Who is this intended for? Who would need this information? (i.e. All editors, only editors for a particular product, Internal use only, etc.)
- Vet Center editors

**Other related KB articles, if applicable:**
- [If you know that related KB articles already exist, link them here]

## Is the article associated with an ongoing product or feature update?
- [ ] Yes [Link to relevant Github ticket](URL)
- [x] No - _business process change_

  
## Priority or deadline for request
Choose either Deadline or a priority:

- [ ] Deadline: [name the deadline here]
- [ ] Priority:
  - [ ] Critical - Without this, there is a large negative impact on the majority of editors causing negative consequences within the CMS; Should be completed as soon as possible
  - [ ] High - Without this, there is negative impact on some editors causing negative consequences within the CMS; should be completed within the current sprint
  - [x] Medium - Without this, there is confusion for editors but not causing negative consequences within the CMS; Should be completed within the next 1-2 sprints
  - [ ] Low - This is not currently causing confusion for many editors but would be a nice to have or is something that may be more impactful in the future; Should be completed within the next 3-4 sprints

## Acceptance Criteria
- [ ] Article is created/updated using [KB content style guidelines](https://va-gov.atlassian.net/wiki/spaces/VAGOV/pages/1771831299/Knowledge+Base+content+style) and saved as a draft
- [ ] Impacts on other KB articles have been considered and any necessary changes have been made and saved as draft
- [ ] If necessary, add link to the new KB article in the [Content model document](https://prod.cms.va.gov/admin/structure/cm_document) for that content type 
- [ ] [Ticket for article review](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/new?assignees=&labels=Knowledge+Base%2C+Needs+refining&template=knowledge-base-article-review.md&title=Review+of+new+or+updated+KB+article+%3A+%3Cinsert+topic+here%3E) has been created

**Comment by mmiddaugh** [comment]
Re: priority - Editors need to know how to update the facility location or hours in VAST so that the correct information is displayed on Vet Center pages and in Facility Locator search results for Veterans seeking services. Because this process requires some handling by more than one team, updating this KB guidance will hopefully prevent additional delays.

**Comment by stefaniefgray** [comment]
@mmiddaugh How does this draft revision look? Please let me know if you would like me to change the wording or the way that the RCS request page is linked -- thank you! https://prod.cms.va.gov/node/23533/latest

Currently:
`Please complete a <b>Request to Change Vet Center Information</b> form, linked from the <a href="https://vaww.vetcenter.va.gov/vast-updates/">VAST Updates – Readjustment Counseling Service (RCS) page.</a>`

**Comment by stefaniefgray** [comment]
@mmiddaugh said the changes look good -- https://dsva.slack.com/archives/C02730UEZPS/p1683927135959039?thread_ts=1683900820.989689&cid=C02730UEZPS

Just published approved revision

Closing as complete! cc: @jilladams

**Comment by stefaniefgray** [comment]
(Also, a new ticket for the article review wasn't created per the guidelines, but it was a super small change that we were able to turn around quickly)
