### ISSUE TITLE
URL Change for: Cedar Crest Boulevard VA Clinic [Ready to go]

### ISSUE THREAD

**Issue by stefaniefgray** [department-of-veterans-affairs/va.gov-cms#13711]
### Instructions for URL redirect
**TEMPORARY: Until the CSV can be deployed by Lighthouse. Will [revert](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14400) after that.**
(Note: This issue will be used from initial request through implementation to ensure all individuals working on this are notified of status updates.  Please do not create multiple issues to track different steps.)
- [x] Notify VA stakeholders as appropriate.
- [x] Link the related facility closure / rename issue.
- [x] Create a URL redirect in the [devops](https://github.com/department-of-veterans-affairs/devops) repo in `ansible/deployment/config/revproxy-vagov/vars/redirects.yml`
- [x] Add the "Awaiting redirect" flag to the facility node with a revision log message that includes a link to this ticket, preserving the node's current moderation state.
- [x] Redirects deploy weekly on Wed. at 10am ET, or by requesting OOB deploy (of the revproxy job to prod) in #vfs-platform-support. After deploy, validate that the URL redirect is deployed. (Note: In the event of a facility closure or a name change,  validate that this occurs before making the Lighthouse csv changes.)
- [x] Update this ticket with a comment that the redirect has been deployed.
- [x] Remove the "Awaiting redirect" flag on the facility node with a revision log message that includes a link to this ticket, preserving the node's current moderation state.
- [x]  Notify helpdesk via comment on ticket or Slack message in #cms-support that changes are ready for review.

-----
#### URL Redirect
| Current URL  |  Redirect Destination or New URL |
| ---  |  --- |
| https://www.va.gov/find-locations/facility/vha_693QB | https://www.va.gov/wilkes-barre-health-care/locations/cedar-crest-boulevard-va-clinic/ |
-----

### Implementation date
When does this request need to be live:
Once main new facility ticket is completed: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13710

### Instructions for canonical URL change
- [x] Verify that the new URL for the facility is published and accessible on VA.gov.
- [x] Update the [CSV in Lighthouse](https://github.com/department-of-veterans-affairs/lighthouse-facilities/blob/master/facilities/src/main/resources/websites.csv) with the changed URL, maintaining the sorted order of the Facility API IDs.
- [x] Create a PR in the [lighthouse-facilities repo](https://github.com/department-of-veterans-affairs/lighthouse-facilities), tagging the Lighthouse team.
- [x] Post a message in the #cms-lighthouse channel in Slack, with an @mention to a Lighthouse team member.
- [x] Add the "Awaiting CSV" flag to the facility node with a revision log message that includes a link to this ticket.
- [x] Validate that the change has deployed by checking that the Facility Locator has been updated with the new url.
- [x] Update this ticket with a comment that the CSV change has been deployed.
- [x] Remove the "Awaiting CSV" flag to the facility node with a revision log message that includes a link to this ticket.

#### URL change example (update with actual ID and URL)
| Facility API ID  |  Full VA.gov URL |
| ---  |  --- |
| vha_691GM | https://www.va.gov/wilkes-barre-health-care/locations/cedar-crest-boulevard-va-clinic/ |

**Comment by omahane** [comment]
Redirect made.

**Comment by stefaniefgray** [comment]
Awaiting URL change as of 7/25/23

**Comment by stefaniefgray** [comment]
Everything looks good but facility still can't be found on Facility Locator

**Comment by davidconlon** [comment]
It is on Facility Locator.
We don't need a redirect, we need the website field to be populated in Lighthouse.

<img width="752" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/56046371/6ebf1d92-6eee-4a29-8d0a-4b0b90195ae1">

**Comment by omahane** [comment]
The CSV has been deployed and the Drupal-sourced facility page is linked from the Facility Locator.
