### ISSUE TITLE
New VAMC Facility: Houston Webster VA Clinic

### ISSUE THREAD

**Issue by stefaniefgray** [department-of-veterans-affairs/va.gov-cms#13712]
Re-direct ticket: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13713

## Intake
- [x] What triggered this runbook? (Flag in CMS, Help desk ticket, Product team, VHA Digital Media)
Trigger: Flagged facilities view

- [x] Link to associated help desk ticket (if applicable)
Help desk ticket: https://va-gov.atlassian.net/browse/VAHELP-5848

- [x] Name of submitter (if applicable)
Submitter: <insert_name>

- [x] If the submitter is an editor, send them links to any relevant KB articles for the VAMC Facility product.
KB articles: <insert_kb_article_links>

- [x] Link to facility in production:
Facility CMS link: https://prod.cms.va.gov/houston-health-care/locations/houston-webster-va-clinic/
Facility API ID: vha_580QE

### New VAMC Facility
Please refer to the Knowledge Base article titled "How do I add a facility to my health care system?" for more information: https://prod.cms.va.gov/help/vamc/about-locations-content-for-vamcs/how-do-i-add-a-facility-to-my-health-care-system

#### CMS help desk steps
**Note: If the help desk is waiting on information from the facility staff or editor, add the "Awaiting editor" flag to the facility with a log message that includes a link to this ticket. Remove the flag when the ticket is ready to be worked by the Facilities team. Be sure to preserve the current moderation state of the node when adding or removing the flag.**
- [x] 1. Become aware that the new facility is now on the Facility API (typically, via a Flag, but this may come in as a helpdesk ticket).
- [x] 2. If the editor has followed the steps from the above Knowledge Base article and included which section and VAMC the facility belongs to (i.e. VA Pittsburgh), great! **Proceed to step 3.** If not, please check with the editor or VHA digital media regarding what section and VAMC it belongs to.
- [x] 3. Updates the Section (default is "VAMC facilities", but it should be a VAMC system in a VISN) and VAMC system field accordingly.
- [x] 4. Communicate with editor (cc VHA Digital Media) to give them go-ahead to complete the content, with this [KB article](https://prod.cms.va.gov/help/vamc/about-locations-content-for-vamcs/how-do-i-add-a-facility-to-my-health-care-system). (See sample notification email below)

<details><summary>Email template </summary>

```

Hello! You should now be able to edit the draft page for this facility, located at [LINK TO NEW FACILITY DRAFT PAGE ON PROD]

Important: Please make sure that all relevant steps listed within the “How do I add a facility to my health care system?” Knowledge Base article have been completed: https://prod.cms.va.gov/help/vamc/about-locations-content-for-vamcs/how-do-i-add-a-facility-to-my-health-care-system

Once finished, please save this page (and all related VAMC Facility Health Service pages) in the moderation state “Draft." Please do not save them as “Published.”

Please let us know when your draft content is complete, so that we can wrap up the technical process from our end before publishing the new facility to VA.gov. Thanks!

```

</details>

- [x] 5. Create a [URL change request](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/new?assignees=&template=runbook-facility-url-change.md&title=URL+Change+for%3A+%3Cinsert+facility+name%3E), changing the entry from the old facility URL to the new facility URL. (**Note: The URL change request ticket blocks the completion of this ticket.**)
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13713

- [x] 6. When editor has prepared content and let help desk know, reassign this issue to appropriate CMS engineer on Product Support team, for bulk publishing.

#### CMS engineer steps
- [x] 7. CMS engineer executes the steps of the URL change request ticket from step 5 above.

(Redirects deploy weekly on Wed. at 10am ET, or by requesting OOB deploy (of the revproxy job to prod) in #vfs-platform-support. Coordinate the items below and canonical URL change after URL change ticket is merged, deployed, and verified in prod.)

#### Drupal Admin steps (CMS Engineer or Help desk)
_Help desk will complete these steps or escalate to request help from CMS engineering._
- [x] 8. Drupal Admin bulk publishes nodes and facility.
- [x] 9. Drupal Admin edit facility node and remove `New facility` flag and save node.
- [x] 10. Let Help desk know this has been done, if not done by Help desk.

#### CMS Help desk (wrap up)
- [x] 11. Notify editor and any other stakeholders.

**Comment by stefaniefgray** [comment]
Current Jira thread: https://va-gov.atlassian.net/browse/VAHELP-5930

**Comment by stefaniefgray** [comment]
Jira thread linked above has turned into debate re: whether or not location should be published

**Comment by stefaniefgray** [comment]
Closing for now, can re-open if future if needed

Per editor in https://va-gov.atlassian.net/browse/VAHELP-5848 -- facility is not open, they do not know when it will be open, and the homepage should not be published

**Comment by stefaniefgray** [comment]
Re-opening per https://va-gov.atlassian.net/browse/VAHELP-7040 -- editor says this facility is now open and needs a homepage. Waiting for editor to edit homepage draft and add health services.

cc: @jilladams @xiongjaneg

**Comment by TroyCMSSupport** [comment]
@ian-sears @omahane @jilladams - I have updated the [URL Change ticket ](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13713)  and have updated this ticket as well. 

Key points: The facility is open, the page is published, I have contacted the editor to add Health services, and it appears in VA Locator tool, but that tool still points to the Facility ID rather than the URL.

**Comment by jilladams** [comment]
Moved both this and the URL change into Ready in the Facilities board, removed the URL Change from Blocked status. We should be able to work on this in next sprint.

**Comment by omahane** [comment]
@ian-sears @TroyCMSSupport This facility needs services.

**Comment by omahane** [comment]
@ian-sears @TroyCMSSupport While this facility still needs services, the canonical URL has been deployed, [per Adam](https://dsva.slack.com/archives/C02BTJTDFTN/p1720015713762209?thread_ts=1719340047.322509&cid=C02BTJTDFTN), and verified by me on VA.gov.

Please follow up with the editor about services and close this ticket when you are done. For now, though, I'm unassigning myself from it.

**Comment by TroyCMSSupport** [comment]
@ian-sears @omahane @jilladams - I have followed up with the editor to emphasize the importance of adding health services via the Jira ticket - https://va-gov.atlassian.net/browse/VAHELP-7040 -- I will keep that ticket open until services have been added but will close this ticket.

**Comment by TroyCMSSupport** [comment]
@jilladams @omahane @ian-sears - Editor notified, VA Locator points to the correct page, Parent site contains proper link.
