### ISSUE TITLE
URL Change for: Houston Webster VA Clinic

### ISSUE THREAD

**Issue by stefaniefgray** [department-of-veterans-affairs/va.gov-cms#13713]
⚠️  NO URL RE-DIRECT NEEDED ⚠️ 

Simply needs to be updated within Lighthouse CSV / canonical URL change

-----

### Implementation date
When does this request need to be live:
Once main new facility ticket is completed: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13712

### Instructions for canonical URL change
- [x] Verify that the new URL for the facility is published and accessible on VA.gov.
- [x] Update the [CSV in Lighthouse](https://github.com/department-of-veterans-affairs/lighthouse-facilities/blob/master/facilities/src/main/resources/websites.csv) with the changed URL, maintaining the sorted order of the Facility API IDs.
- [x] Create a PR in the [lighthouse-facilities repo](https://github.com/department-of-veterans-affairs/lighthouse-facilities), tagging the Lighthouse team.
- [x] Post a message in the #cms-lighthouse channel in Slack, with an @mention to a Lighthouse team member.
- [x] Add the "Awaiting CSV" flag to the facility node with a revision log message that includes a link to this ticket.
- [x] Validate that the change has deployed by checking that the Facility Locator has been updated with the new url.
- [x] Update this ticket with a comment that the CSV change has been deployed.
- [x] Remove the "Awaiting CSV" flag to the facility node with a revision log message that includes a link to this ticket.

#### URL change example (update with actual ID and URL)
| Facility API ID  |  Full VA.gov URL |
| ---  |  --- |
| vha_580QE | https://www.va.gov/houston-health-care/locations/houston-webster-va-clinic/ |

**Comment by stefaniefgray** [comment]
Closing for now, can re-open if future if needed

Per editor in https://va-gov.atlassian.net/browse/VAHELP-5848 -- facility is not open, they do not know when it will be open, and the homepage should not be published

**Comment by stefaniefgray** [comment]
Can re-open Jira ticket if needed -- https://va-gov.atlassian.net/browse/VAHELP-5848

**Comment by stefaniefgray** [comment]
Re-opening per https://va-gov.atlassian.net/browse/VAHELP-7040 -- editor says this facility is now open and needs a homepage. Waiting for editor to edit homepage draft and add health services.

cc: @jilladams @xiongjaneg

**Comment by TroyCMSSupport** [comment]
@ian-sears @omahane @jilladams - I made an attempt to add facility ID vha_580QE and URL https://www.va.gov/houston-health-care/locations/houston-webster-va-clinic/ to the CSV but was unable to do so -- 

The current situation on this issue is that the Facility is open, the page is published (have contacted the Editor to update Health services), and it appears in VA Locator tool, but that tool still points to the Facility ID rather than the URL.

For reference, the Parent issue is https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13712

**Comment by omahane** [comment]
@TroyCMSSupport Adding to the [websites.csv](https://github.com/department-of-veterans-affairs/lighthouse-facilities/blob/master/facilities/src/main/resources/websites.csv) can only be done by Lighthouse. I have made a request to add this, [via Slack](https://dsva.slack.com/archives/C02BTJTDFTN/p1719594660449489?thread_ts=1719340047.322509&cid=C02BTJTDFTN), as this page is already published, anyway.

**Comment by omahane** [comment]
The canonical URL has been deployed, [per Adam](https://dsva.slack.com/archives/C02BTJTDFTN/p1720015713762209?thread_ts=1719340047.322509&cid=C02BTJTDFTN), and verified by me on VA.gov.
