### ISSUE TITLE
URL Change for: Monroeville VA Clinic [Ready to go] - Clinic opens 7/31

### ISSUE THREAD

**Issue by stefaniefgray** [department-of-veterans-affairs/va.gov-cms#13715]
⚠️  NO URL RE-DIRECT NEEDED ⚠️ 

Simply needs to be updated within Lighthouse CSV / canonical URL change

-----

### Implementation date
When does this request need to be live:
Once main new facility ticket is completed: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13714

### Instructions for canonical URL change
- [x] Verify that the new URL for the facility is published and accessible on VA.gov.
- [x] Update the [CSV in Lighthouse](https://github.com/department-of-veterans-affairs/lighthouse-facilities/blob/master/facilities/src/main/resources/websites.csv) with the changed URL, maintaining the sorted order of the Facility API IDs.
- [x] Create a PR in the [lighthouse-facilities repo](https://github.com/department-of-veterans-affairs/lighthouse-facilities), tagging the Lighthouse team.
- [x] Post a message in the #cms-lighthouse channel in Slack, with an @mention to a Lighthouse team member.
- [x] Add the "Awaiting CSV" flag to the facility node with a revision log message that includes a link to this ticket.
- [x] Validate that the change has deployed by checking that the Facility Locator has been updated with the new url.
- [x] Update this ticket with a comment that the CSV change has been deployed.
- [x] Remove the "Awaiting CSV" flag to the facility node with a revision log message that includes a link to this ticket.

#### URL change example (update with actual ID and URL)
| Facility API ID  |  Full VA.gov URL |
| ---  |  --- |
| vha_646GF | https://www.va.gov/pittsburgh-health-care/locations/monroeville-va-clinic |

**Comment by stefaniefgray** [comment]
Clinic opens 7/31, can hold until then

**Comment by omahane** [comment]
I've put in the request for the canonical URL to be added on the Lighthouse side. https://dsva.slack.com/archives/C02BTJTDFTN/p1692120123517529?thread_ts=1690826180.027919&cid=C02BTJTDFTN

**Comment by omahane** [comment]
I removed the "Awaiting Editor" flag, as this seemed to be ready, according to the information in this ticket. I added the "Awaiting CSV" flag.

**Comment by omahane** [comment]
The CSV has been deployed. The facility is in Facility Locator.
