### ISSUE TITLE
I.L. UX: Update UX flow documentation as implementation raises questions

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#13723]
### User story

**AS A** PO/PM/Engineer
**I WANT** the UX flows documentation to be updated quickly when decisions are made or new use cases uncovered
**SO THAT** I always have a single source of truth for desired functionality.

## Acceptance criteria

- [x] Provided input on implementation questions
- [ ] Updated UX flows with decisions and use case adjustments for the following (items to be added as they arise):
  - [x] invalid zip code – The Zip screen can perform front-end validation to ensure the user enters a 5-digit number. However, if the 5-digit zip code submitted is not a real zip, the app won't know that until info is submitted on the Review Info screen. How should the app behave in that case? What screen land on, how indicate error? (if the answer is "as soon as they try to continue from zip screen," then we need to do a little engineering.)

**Comment by wesrowe** [comment]
Added invalid-zip error handling as an AC.

**Comment by thejordanwood** [comment]
My recommendation is that the error message should appear once the user tries to navigate away from the zip code screen. This way we can use the form field error state. 

![zip code error](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/104526584/d54af8c6-bd71-4510-9af2-186236f23236)

**Comment by jilladams** [comment]
Talked to Wes, we know this is in Sketch. Is captured in a FE ticket for zip implementation. Closing.
