### ISSUE TITLE
VBA: draft Conversation Guide

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#13724]
## Acceptance Criteria
- [x] Draft discussion guide based on design
- [x] Iterate at least once in collaboration with Jordan to better match discussion guide to design
- [ ]  Share research plan with someone on UX team for feedback, and incorporate their feedback
- [ ]  (optional) Internal review of first draft of conversation guide with Jordan/Michelle/DaveC/Kamari 
- [ ] Ready for PO review

**Comment by kmariepat-cityfriends** [comment]
Current state draft: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/regional-offices/research/2023-06-veteran-facing/conversation-guide.md

**Comment by cindymerrill** [comment]
Shared my draft conversation guide along with my research plan for feedback in the Facilities channel [in slack](https://dsva.slack.com/archives/C0FQSS30V/p1684272129555449). The _User Tasks_ section needs detailing once I know what services will be on the page. I'll look for feedback in the slack thread and/or a meeting on or after I return from PTO on Wed May 24.

**Comment by davidmpickett** [comment]
From [Logged-in Wayfinding Study Research Findings
](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/information-architecture/research-and-analytics/2023-generative-logged-in-research/2023-logged-in-user-interviews/findings-summary.md#navigating-to-tasks-was-challenging-for-participants-who-werent-sure-how-their-task-was-categorized-within-va)

> **Navigating to tasks was challenging for participants who weren’t sure how their task was categorized within VA.**
> Participants had a harder time finding what they needed via the navigation menu when: - there could be multiple related categories (e.g. downloading benefit letters), or - they didn't have enough context around the task (e.g. viewing dependents)

Wondering if the fact that previous research shows that there is confusion for tasks that are not specific to benefits means we should specifically have a task that deals one of those items (e.g. add a dependent)?

**Comment by kmariepat-cityfriends** [comment]
@cindymerrill closing this card in favor of VBA: Refine Conversation Guide#14008; the conversation guide has been sufficiently drafted to this point, Dave C. wanted us to denote completion of iterating to this point, thus I will be closing this card
