### ISSUE TITLE
Fix "dependabot cannot update to the required version"

### ISSUE THREAD

**Issue by cmaeng** [department-of-veterans-affairs/va.gov-cms#1372]
Implementation
- [ ] Submit upstream PR with fix to dependabot to work with PHP Git packages.

Useful links:
* Guidance from Dependabot maintainer on how to test > https://github.com/dependabot/feedback/issues/803#issuecomment-581960516
* View logs by clicking "last updated" link here https://app.dependabot.com/accounts/department-of-veterans-affairs
* View settings here https://app.dependabot.com/accounts/department-of-veterans-affairs/projects/107296
* Packagist https://packagist.org/packages/va-gov/web
* https://github.com/department-of-veterans-affairs/va.gov-cms/blob/master/.dependabot/config.yml

We currently have a .dependabot.yml file setup to automerge daily security and WEB updates if they pass tests. This isn't working however, due to an upstream bug I filed here https://github.com/dependabot/feedback/issues/803 (Dependabot can't deal with PHP git updates (Requirements to unlock update_not_possible)). The code is open source and there are testing instructions if we want to fix it ourselves. 

**Background**

Megan Kelley, of the VSP Content and IA team reported in the CMS Support channel seeing the attached notifications around a vulnerability found in the json package.

Looking to research:
- What is causing this alert?
- Is this a vulnerability that we need to worry about?
- Is there any action needed on our part?

Reply back to this thread with conclusions:
https://dsva.slack.com/archives/CDHBKAL9W/p1585752963051300

![Screen Shot 2020-04-01 at 10.51.40 AM.png](https://images.zenhubusercontent.com/5e3ad9b2c4b3070f908bf89c/18b7899b-ba6d-4f86-8f76-c6b289c867e7)

![Screen Shot 2020-04-01 at 10.51.44 AM.png](https://images.zenhubusercontent.com/5e3ad9b2c4b3070f908bf89c/56b08303-6704-43cc-9591-db24e49bc827)

**Comment by ElijahLynn** [comment]
Link to all Security Alerts > https://github.com/department-of-veterans-affairs/va.gov-cms/network/alerts

**Comment by ElijahLynn** [comment]
We don't have dependabot setup to manage NPM dependencies so that is interesting. We just have it setup for php:composer. 

https://github.com/department-of-veterans-affairs/va.gov-cms/blob/master/.dependabot/config.yml

We can view logs here https://app.dependabot.com/accounts/department-of-veterans-affairs by clicking "last checked <N> hours ago" link.

**Comment by ElijahLynn** [comment]
> We don't have dependabot setup to manage NPM dependencies so that is interesting. We just have it setup for php:composer.
> 
> https://github.com/department-of-veterans-affairs/va.gov-cms/blob/master/.dependabot/config.yml
> 
> We can view logs here https://app.dependabot.com/accounts/department-of-veterans-affairs by clicking "last checked hours ago" link.

Hrm, even though our config.yml is set to php:composer only, it must be inheriting some defaults. https://github.com/department-of-veterans-affairs/va.gov-cms/pull/1259

If I click "details about this error" it says:
> Dependabot cannot create a pull request as one or more other dependencies require a version that is incompatible with this update.

Next step is to see if we can update locally.

**Comment by indytechcook** [comment]
While working on #1771, I found that the vets-website and corresponding va-gov/web are not sending tags to packagist.  If they were sending tags then dependabot would be able to auto-create PRs and merge them.  

I did work with Rian to add sending tags and releases to packagist via the webhook but it did not send the tag for yesterday's release as I expected.
