### ISSUE TITLE
Q&As Design: Document placement of reusable Q&As within Benefit Detail FE template

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#13725]
### User story

**AS A** PW Engineer
**I WANT** to see where to place reusable Q&As in 1) the Benefit Detail front-end template and 2) the Drupal UI
**SO THAT** the solution is sustainable and delivers a good Veteran experience.

### Design notes / background

Example benefit page:
* https://www.va.gov/health-care/about-va-health-benefits/
* https://prod.cms.va.gov/node/29/edit

Right now, Benefit Detail Pages can use Q&A, but the old way, as Q&A paragraph types. Those can be interleaved into Featured Content or Main Content areas.
After we restructure the content, they'll use reusable Q&A type that can appear at a specific point in the CMS content type. This means we need stakeholder input (Content team) to understand: where should reusable Q&As really sit, in the CMS structure, and in the Front-end.

### Questions:
- Many BD pages have Q&As on them already – would the expectation be that the Q&As on a given page be migrated to a Reusable Q&A section wholesale? Or would the Reusable section have to be able to co-exist with the existing Q&As?

## Acceptance criteria

- [ ] Reviewed Benefit Detail page layout with Sitewide Content team (CAIA)
    - [ ] Ask CAIA if they need an intake ticket 
- [ ] Validate the approach with engineering (both CMS and FE) 
- [ ] Documented/mocked where to add reusable Q&As
- [ ] Linked design documentation in FE implementation ticket #10944

**Comment by jilladams** [comment]
Example FAQ where Q&A groups already live, for reference: https://prod.cms.va.gov/node/47278/edit

**Comment by wesrowe** [comment]
@thejordanwood, FYSA I pinged Danielle & RandiH [in slack](https://dsva.slack.com/archives/C52CL1PKQ/p1686784348471769) to ask if we can proceed async or need meeting.

**Comment by jilladams** [comment]
Danielle confirmed a meeting is needed. Wes to schedule with Danielle & Randi.

**Comment by wesrowe** [comment]
I haven't scheduled the Danielle meeting yet, will carry over.

**Comment by wesrowe** [comment]
meeting scheduled next Wed, 7/28

**Comment by wesrowe** [comment]
Meeting 6/28 with Danielle:
- Example BD pages that will need migration?
- How intend to migrate content?

Notes:

Danielle's plan – eg on the About page for health care, she intends to migrate all but 3-4 Q&As from the About page to Resources & Support. The best way to do that is to copy-paste each Q&A into a Reusable Q&A, then (re)use it on the new R&S page.

Discovery: Reusable Q&A content blocks will be created amongst the existing list of content blocks under Main Content in Drupal. So the FE should just display those content blocks the same order from Drupal.

Next step: Randi Mays will verify that the FE template can pick up Reusable Q&A content blocks in the same order they were added in Drupal amongst other content block types.

**Comment by wesrowe** [comment]
@thejordanwood, this seems like a no-op for you after all. I think we can close...

**Comment by thejordanwood** [comment]
@wesrowe Sounds good to me! I'll close this ticket, but let me know if anything changes. I'm always happy to help out.
