### ISSUE TITLE
Resolve data discrepancies around Mental Health phone number change

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#13720]
### User story
> _Describe the audience/user, enhancement or fix, and value / outcome desired._

**AS A**
**I WANT**
**SO THAT**

### Engineering notes / background
#11338 CMS: Compare Mental Health phone number reports
Jay identified facilities with discrepancies between the Appointment Phone or Service Location Phone fields that differ from the number we get from lighthouse. He also marked a few instances with a difference between lighthouse and the CMS but attributed those differences to out of date lighthouse data. He was able to spot checked match those.

## Acceptance criteria

>Consider
> - Design / Accessibility reviews
> - Collab cycle requirements
> - Device sizes (mobile first)
> - Documentation updates / Change management
< - [Content model documentation](https://prod.cms.va.gov/admin/structure/cm_document)
> - Testing notes

- [ ]

**Comment by mmiddaugh** [comment]
Examples
[Atlantic County VA Clinic](https://www.va.gov/wilmington-health-care/locations/atlantic-county-va-clinic/)
| Jay's data | UI on facility page |
|---|---|
| Lighthouse phone = 302-994-2511 x4805 | Main phone = 800-461-8262 x2800| 
| Mental health phone = 302-994-2511 x4805 | Mental health care = 302-994-2511 x4805 | 
| Appointment phone = 800-461-8262 x2730 | MH service accordion Appointments 800-461-8262 x2730 | 
| Service Location phone = 800-461-8262 x4805 | MH service accordion 800-461-8262 x4805

[Wilmington VA Medical Center](https://www.va.gov/wilmington-health-care/locations/wilmington-va-medical-center/)
| Jay's data | UI on facility page |
|---|---|
| Lighthouse phone = 302-994-2511 x4805 | Main phone = 302-994-2511 x4805 | 
| Mental health phone = 302-994-2511 x4805 | Mental health care = 302-994-2511 x4805 | 
| Appointment phone = 800-461-8262 x4350 | MH service accordion Appointments 800-461-8262 x4350 | 
| Service Location phone 1 = 800-461-8262 x4805 | MH service accordion 302-994-2511 | 
| Service Location phone 2 = 302-994-2511 | MH service accordion 800-461-8262 x4805

VAMC and 5 associated clinics have the same

- Lighthouse phone 
- Mental health number
- Service location number
- 3 different extensions for appointment phone numbers

**Comment by mmiddaugh** [comment]
This will be addressed in coordination with VHA DM - no development work here at this point.
