### ISSUE TITLE
Discovery: How did vets-website end-to-end tests pass but React widgets site-wide were affected by footer outage

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#13730]
### User story

**AS A** FE engineer
**I WANT**  confidence that my changes are tested enough to confirm they will not break prod
**SO THAT** I don't break prod.

### Engineering notes / background
Post-mortem action item from: https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/pull/975

In short: content-build changes failed to deploy before vets-website changes. The vets-website changes that deployed were isolated to the footer but somehow broke many, if not all, React widgets. CI tests passed for the push to prod. Why?

This will likely require coordination with the Platform team. 
- NOTE: on 6/29, Matt Dingee of the Design system team said in [a comment](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11313#issuecomment-1613814206) that their former engineer Brooks had a way of using Cypress tests on headers. Following up with him is recommended for this ticket.

## Acceptance criteria

Timebox: up to 1 day
- [x] Studied test coverage of vets-website build processes
- [x] Identified gaps in tests where a javascript issue (such as data missing from footer) could slip through
- [ ] Recommend and ticket (if possible) next steps based on findings

**Comment by randimays** [comment]
[Discovery document](https://docs.google.com/document/d/1wK2HT8eja7MfupZjZNRGL6EA4GL4bJ6XdulDOMlJhXo/edit?usp=sharing) and [Slack thread](https://dsva.slack.com/archives/C52CL1PKQ/p1690811457990409) where I posted it.

Questions and recommendations in the document. I suggest a conversation with the team to determine next steps / ticketing.

**Comment by jilladams** [comment]
Good work, Randi. Glad you got closure on this, honestly. 

* As far as where to document: it does seem useful to have this searchable in Github, but I don't expect us to revisit it as a document ongoing, so imo a comment on this ticket would be fine. (I know that's a lot of formatting and images to manage, so feel free to timebox that to a topline summary and attach a document maybe?) 
* Re: next steps: I think it will be hard to make progress against the open items async just bc everyone is pretty busy. A dedicated time seems mostly useful to knock out any required ticketing / open items. 

We can verify both of those with Wes in scrum tomorrow, I've added to the board. 

Also: Reminder to move this doc to [PW team folder](https://drive.google.com/drive/u/1/folders/1Yyf0FqQvvyPFfX4KBmA0tgtXL4J6q5iz) until we get it into Github somewhere.

**Comment by randimays** [comment]
@jilladams Thank you. Gaurav asked me to send it over to him once it was documented in the team repo, so I thought I'd check what the final destination of this would be. Makes sense to just keep it here.

**Comment by jilladams** [comment]
Thanks Randi! In today's product sync, DaveC confirmed he'd like to be present to listen in on the discussion, so next step is @wesrowe will help schedule that chat.

**Comment by wesrowe** [comment]
@jilladams, can we close this ticket prior to the meeting, or is it carrying over? I can go either way.

**Comment by jilladams** [comment]
Next steps are recommended, I feel ok closing this. I own scheduling the review, which I'll work on by tomorrow EOD.
