### ISSUE TITLE
I.L. FE: Add FE form validation and API error handling/messaging

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#13737]
## Description

**AS A** Veteran
**I WANT** the to give me clear messaging when there is an issue with my input
**SO THAT** I can address issues with as little difficulty and cognitive load as possible.

**AS A** Veteran
**I WANT** the app to let me know if the API fails to respond in a reasonable time
**SO THAT** the app builds my trust and doesn't leave me waiting for something to happen.

### Engineering notes / background

API error codes were implemented in #13558.

## Acceptance criteria

**Form validation:**
- [x] The Zip input requires a 5-digit number before I can continue to the next screen
- [x] The dependents input requires a number between 0 and 100 (inclusive) before I can continue to the next screen
- [x] The year input requires a year to be selected before I can continue to the next screen 

**API responses and messaging**
The following error messages appear in a gray banner at the top of the Review Info screen, similar to this: 
<img width="236" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/4054752/ec716690-19e4-48a7-ae50-5de81f3bbc82">

- [x] If the API fails to return a response within 5 seconds, trigger general alert (in screen shot above) "We've run into a problem..."
- [x] If the API returns a 422 Invalid Zipcode response, display error to User "The zip code you entered doesn't exist in our database."
- [x] If the API returns a 422 Invalid Year response, display error to user "The year you entered doesn't exist in our database."
- [x] If the API returns a 422 Invalid number of dependents response, display error to user "The number of dependents you entered is not between 0 and 100."

**Comment by wesrowe** [comment]
Jordan will comp error message per [slack](https://dsva.slack.com/archives/C52CL1PKQ/p1687362986683999) on 6/21.

**Comment by wesrowe** [comment]
FYI @thejordanwood, see the ACs, we need several different error messages for this one.

**Comment by thejordanwood** [comment]
@wesrowe @randimays  Here are mockups showing the error states described in the ACs. I found the language for the general API error in [the content style guide](https://design.va.gov/content-style-guide/error-messages/access). 

<img width="320" alt="api_error" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/104526584/ac0675fe-fd5e-4afb-a0fe-6d904e8cb701">

![dependents_error](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/104526584/b6c87527-7440-49d8-8f33-4c215202edb2)

![zip code_error](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/104526584/ef4c0a75-9d0d-4f18-ad7e-df2d9023a8c9)

![year_error](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/104526584/7af5dd05-06a2-417e-86fd-352f011adfdd)

**Comment by thejordanwood** [comment]
@wesrowe @randimays Another mockup. This attempts to direct the user to the beginning of the app if they hit the API without properly going through the form. 

<img width="320" alt="form_error" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/104526584/fb0cf447-3703-47da-b67e-20efc64c08b4">

**Comment by randimays** [comment]
Screenshots of the final product and notes here (this ticket was combined with 14200): https://docs.google.com/document/d/1ubN8B0mWys5cnHome0FU7d85Xmg1NXOE1toAPtMDa3A/edit?usp=sharing

**Comment by randimays** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/24771/

Loom walkthrough of code only: https://www.loom.com/share/d41d14149abf4f189c9d6f40d22573d7?sid=c2b474e6-7f88-492b-bcfb-6f713a803b8c

**Comment by randimays** [comment]
This has accessibility, design and engineering approval. PR is ready to merge after @wesrowe gives us the green light. Slack thread for all the details: https://dsva.slack.com/archives/C52CL1PKQ/p1688676450644809

**Comment by wesrowe** [comment]
The google doc was really really helpful. Approved!

**Comment by randimays** [comment]
Verified in staging. Closing!
