### ISSUE TITLE
Form Flags: Remove "Changed title" flag and view

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#13732]
***5/18: Hold up, SteveW identified the reason for this flag. See comments for subsequent inputs.***

### User story

**AS A** PM/PO
**I WANT** the CMS to no longer create flags for a changed title nor display these flags in a view
**SO THAT** we don't collect data that isn't actionable for the PW team.

### Engineering notes / background

The Changed title flag works correctly, but it is noting a change that doesn't have any potential to break PW products or require us to notify another team for downstream checks/changes. So it's cluttering Drupal.

View/tab to remove: https://prod.cms.va.gov/admin/content/va-forms/changed-title.

screenshot: 
<img width="404" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/4054752/73b8945f-a6ff-4812-8469-ce6449722687">

Background: see [Mural](https://app.mural.co/invitation/mural/vagov6717/1666820558104?sender=uebde62ceb342c6477fb09406&key=355c3fde-b4b2-417e-85cb-8a7bc49ebe47) for how we will use other flags going forward.

## Acceptance criteria

- [ ] Removed Drupal logic to create Changed title flag
- [ ] Removed corresponding tab/view in Forms area of Drupal, so [Changed title URL](https://prod.cms.va.gov/admin/content/va-forms/changed-title) should 404
- [ ] Ensured that title-change metadata is still logged in the revision log

**Comment by wesrowe** [comment]
pointing as 5 due to potential complexity around tests, migrations, hooks, etc.

**Comment by swirtSJW** [comment]
Sorry, this might be outdated, but the intention of the TItle change flag was so that editors could identify places in the CMS where the name of the form is useed in text and fix those to use the new name.  That flag should be actionable.   Otherwise we have  have references to the form that no longer use its current name, creating veteran confusion.

**Comment by wesrowe** [comment]
Thanks @swirtSJW, that is timely info.

@rlhecht, @DanielleThierryUSDSVA, please see Steve's comment above. Does the CAIA team have any process in place to update form names in content? Or has it ever had such a process? Please offer any thoughts you have about the flag and whether you would want it monitored.

**Comment by RLHecht** [comment]
@wesrowe I'm not sure we've updated any form names in the past and we don't have a process for it. I didn't know this flag was here actually. But if a form name changes and this is a way to alert us or allows us to see where the old form name is being used on our pages so we can make updates, this would be a helpful tool.

**Comment by wesrowe** [comment]
@jilladams, any concerns with moving this to icebox? since we know that it's a useful flag after all...

**Comment by jilladams** [comment]
🤷‍♀️ I don't feel like that's my call, so I'm happy to defer to you / DaveC.
