### ISSUE TITLE
I.L. FE: Add final URLs for app steps/screens

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#13751]
### User story

**AS A** Veteran
**I WANT** each step in the I.L. app to have a URL in keeping with the IA scheme for VAgov
**SO THAT** I can stay oriented.

### Engineering notes / background

**DESIGN NEEDED:** The actual URLs per-page build off of the root `/income-limits` url, but the IA team [didn't specify them](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/information-architecture/ia-design-docs/income-limits.md). Instead, they said we should just follow the design system guidance.

From Kristin O.M.:
> Notes: Also, all consecutive pages in the flow (like the steps in the flow) will build from this root URL. For those additional URL slugs, you can follow our URL standards in word selection and formatting (you don't need to ask us for those -- they're in design system > content style guide). Let us know if you need help with that!

Deep link to [URL guidance](https://design.va.gov/content-style-guide/url-standards#urls-must-be-readable-utilize-plain-language-and-include-appropriate-and-consistent-keywords):
> URL keywords should be selected from the primary keywords used in the H1 of the page and accurately represent the content of the page.
> - If the content does not include information on eligibility, do not use the word “eligibility” in the URL. This can be misleading to users and search engines.
> - Primary keywords representing the content should be consistently used across headings, links, URLs and navigation components.

Kristin O.M. (CAIA) updated the [IA design doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/information-architecture/ia-design-docs/income-limits.md) with final URLs:
- Base/root url: /health-care/income-limits
  - Start screen - /introduction
  - Year screen - [www.va.gov/health-care/income-limits/year](http://www.va.gov/health-care/income-limits/year)
  - Zip code screen - [www.va.gov/health-care/income-limits/zip](http://www.va.gov/health-care/income-limits/zip)
  - Number of dependents screen - [www.va.gov/health-care/income-limits/dependents](http://www.va.gov/health-care/income-limits/dependents)
  - Review Info screen - [www.va.gov/health-care/income-limits/review](http://www.va.gov/health-care/income-limits/review)
  - Results screen - [www.va.gov/health-care/income-limits/results](http://www.va.gov/health-care/income-limits/results)

## Acceptance criteria

- [x] Each step in the IL app flow displays the correct URL, as documented above and in the IA design doc linked above.

**Comment by wesrowe** [comment]
@thejordanwood, note the "Design needed" in ticket details. Probably it's something I can solve without any particular design expertise. But you might get to it first so I wanted to put it on your radar.

**Comment by wesrowe** [comment]
I proposed to the IA team (CAIA) that we use the same URLs Randi used in the app. See this [comment in the intake ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/51132#issuecomment-1590242128).

**Comment by wesrowe** [comment]
Update: URLs are finalized as of 6/14 in the [IA design doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/information-architecture/ia-design-docs/income-limits.md#urls-and-breadcrumbs).

**Comment by wesrowe** [comment]
And we're putting the start screen at `/introduction`.

**Comment by wesrowe** [comment]
Danielle confirmed (slack DM) the decision to have the /introduction screen within the react app (and not drupalize).

**Comment by randimays** [comment]
Verified in staging. Closing!
