### ISSUE TITLE
Create scheduled Sidekiq job to automate VES export to S3

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#13761]
**Note: the below needs to be updated to reflect the fact that we are targeting Github Workflows for automation, rather than Sidekiq.

### User story

AS A PW Engineer
I WANT to write a sidekiq job that exports ONE of the Income Limits tables from VES to a CSV stored in AWS S3
SO THAT I feel confident we can manage and automate our own exports.

### Engineering notes / background

Automates work from 2 previous spikes.

This work is not a "spike" because we've done it before and should be able to write prod-worthy code.

## Acceptance criteria

- [ ] Sidekiq job ran at scheduled time
- [ ] Job migrated a VES table to a CSV stored in the product S3 bucket for Income Limits tables
- [ ] CSV has a temporary name so that it does not overwrite the actual prod CSV
- [ ] Diff between new and existing CSVs shows that the new one is the same

**Comment by dsasser** [comment]
Closing as a dupe with https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15203. We moved to Github Actions en lieu of Sidekiq, so this task is no longer necessary.
