### ISSUE TITLE
Vet Center Outstations and Mobile should be pushing urls for the parent/locations page

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#13769]
## Describe the defect
On our url facility push, Vet Center Outstations and Mobile Vet centers are pushing their own perceived address in drupal.   Drupal does not know that their FE page is on the parent vet center's locations page. ie: https://www.va.gov/la-crosse-vet-center/locations/

## To Reproduce
1. Go to '/la-crosse-vet-center/wausau-vet-center-outstation` and edit the node with a status change
2. Go to the queue and see that the url that is being pushed is `https://va.gov/la-crosse-vet-center/wausau-vet-center-outstation` which is a non-existent url because it really lives at `https://www.va.gov/la-crosse-vet-center/locations/`

## AC / Expected behavior
- [x] When a Vet Center Outstation, Mobile or ~CAP~ status is pushed to Lighthouse, they should be pushing the URL for the parent vet center's locations page 
- [x] The link to the locations page has the fragment that matches the id of the  heading on the locations page like this https://www.va.gov/abilene-vet-center/locations/#abilene-vet-center---ranger

**Comment by swirtSJW** [comment]
Discussion about the fragment [here in slack](https://dsva.slack.com/archives/C0FQSS30V/p1684503298334299)

**Comment by jilladams** [comment]
From scrum: Lighthouse not blocking.

**Comment by swirtSJW** [comment]
Here is the FE code that we have to mimic to generate the right fragment  that matches the ID
https://github.com/department-of-veterans-affairs/content-build/blob/6fcfe5ad8815610a70733cbc8c015386a8021a7a/src/site/stages/build/plugins/modify-dom/add-id-to-subheadings.js#L9C1-L16

**Comment by swirtSJW** [comment]
This one had some unanticipated complexity because I had forgotten that Mobile vet centers do not have a status so we were not pushing them as part of our status pushes.

**Comment by swirtSJW** [comment]
Caps we are not pushing yet and the cap code accounts for this already do I removed CAPs from the AC.

**Comment by swirtSJW** [comment]
Here is the push of a mobile which happens, when

-  newly published, 
- name change 
- parent change.
- archived
```
{
  "core": {
    "facility_url": "https://www.va.gov/fargo-vet-center/locations/#fargo-mobile-vet-center"
  },
  "operating_status": {
    "code": "NORMAL",
    "additional_info": null
  }
}
```

Notice the url includes the proper location page and fragment.

**Comment by swirtSJW** [comment]
Here is the push for an outstation
Pushed for:

- draft if never published
- archived,
- published
- status change
- status description change
- change of name
- change of parent vet center

```
{
  "core": {
    "facility_url": "https://www.va.gov/elkton-vet-center/locations/#salisbury-vet-center-outstatio"
  },
  "operating_status": {
    "code": "LIMITED",
    "additional_info": "Bearffff"
  }
}
```
Provides correct link to [locations page](https://www.va.gov/elkton-vet-center/locations/#salisbury-vet-center-outstatio)

**Comment by swirtSJW** [comment]
Double checked behavior with Vet Centers to rule out breakage  (also added trailing slash to avoid 302 redirect.)
```
{
  "core": {
    "facility_url": "https://www.va.gov/tulsa-vet-center/"
  },
  "operating_status": {
    "code": "NORMAL",
    "additional_info": null
  }
}
```

**Comment by swirtSJW** [comment]
Confirmed still working for VAMC facility
```
{
  "core": {
    "facility_url": "https://www.va.gov/north-florida-health-care/locations/gainesville-va-clinic/"
  },
  "operating_status": {
    "code": "NOTICE",
    "additional_info": "Sunny so we are staying home",
    "supplemental_status": [
      {
        "id": "COVID_MEDIUM",
        "label": "COVID-19 health protection: Levels medium"
      }
    ]
  },
  "system": {
    "name": "VA North Florida/South Georgia health care",
    "url": "https://www.va.gov/north-florida-health-care",
    "covid_url": "https://www.va.gov/north-florida-health-care/programs/covid-19-vaccines",
    "va_health_connect_phone": "877-741-3400"
  }
}
```

**Comment by swirtSJW** [comment]
Test of VBA facility  Notice there is no url because they are not known to us.
```
{
  "core": {
    "facility_url": null
  },
  "operating_status": {
    "code": "NOTICE",
    "additional_info": "We're open for visitors. Be prepared to wear a mask and complete COVID-19 symptom screening if needed, based on current "
  }
}
```

**Comment by swirtSJW** [comment]
Here is an example of NCA  Since they have not launched, they have no url.

```
{
  "core": {
    "facility_url": null
  },
  "operating_status": {
    "code": "NORMAL",
    "additional_info": null
  }
}
```

**Comment by swirtSJW** [comment]
PR is going to have some angry tests because the tests need to be altered to account for more push reasons and code to mock.

**Comment by swirtSJW** [comment]
Yikes.  Adding the push of a facility without status (mobile VC) has doubled our testing permutations from 500 to 1000    I am looking for another way.
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5752113/c2202e5b-d42a-4ce8-9fcb-68f63d73d81b)

**Comment by swirtSJW** [comment]
I raised the possibility of a less complex approach that would be more reliable and not need so many permutations of data and moderation states.  https://dsva.slack.com/archives/C02BTJTDFTN/p1684977926175719

**Comment by swirtSJW** [comment]
After this code went out today, I attempted to do a force push of facility datat just to get lighthouse in sync and discovered a deffect in our force push functionality. I ticketted it for followup work. https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13916
