### ISSUE TITLE
Move exported CSV to S3

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#13760]
### User story

AS A PW Engineer
I WANT to figure out how to move an exported CSV to S3 in a way that can be automated (in Github Workflow)
SO THAT I feel confident we can manage and automate our own uploads to S3.

### Engineering notes / background

This is a follow-on to #13759.

## Acceptance criteria

- [ ] Automate-able script uploads the exported-from-VES CSV to S3

**Comment by wesrowe** [comment]
waiting to finish refining until outcome of previous spike

**Comment by FranECross** [comment]
@jilladams @dsasser I think this ticket is obsolete given the other tickets we've created for automating import of income limits data to S3. Any objections to me closing? Thanks!

**Comment by jilladams** [comment]
Agree, but @dsasser can you confirm that this ticket is no longer necessary?

**Comment by dsasser** [comment]
> Agree, but @dsasser can you confirm that this ticket is no longer necessary?

Yes we can close this. We ended up combining a few of these smaller issues into #16217.
