### ISSUE TITLE
Remove redundant deploy steps 

### ISSUE THREAD

**Issue by ElijahLynn** [department-of-veterans-affairs/va.gov-cms#1377]
Follow up of #1303

Remove redundant deploy steps (cache:rebuild, updatedb, config:import) from ansible/deployment/config/cms/tasks/post-init-tasks.yml and ansible/deployment/config/cms/tasks/post-init-tasks-prod.yml because it is being run twice now, the second time being in the deploy/* section of tests.yaml.

**Comment by indytechcook** [comment]
@ElijahLynn @olivereri is this still an issue with the #2494

**Comment by ElijahLynn** [comment]
I think it is still run twice, and we need to update the BRD test run now to pass a filter to not run those for the yaml-tests.

**Comment by ElijahLynn** [comment]
Now that we are half moved off of DevShop I think this should be updated to run `drush deploy` once we upgrade to Drush 10, #1230.

**Comment by ElijahLynn** [comment]
We should do https://github.com/department-of-veterans-affairs/va.gov-cms/issues/3904 first and see if this is still needed.

**Comment by oksana-c** [comment]
@ElijahLynn what was the conclusion after completing #3904 ^^? Do we still need to keep this story open?

**Comment by ElijahLynn** [comment]
Yeah, this is done now, in #3904.
