### ISSUE TITLE
Homepage: new KB articles for Promo/Benefit spotlight editing / publishing

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#13789]
## Description
[Managing homepage content blocks](https://prod.cms.va.gov/help/managing-homepage-content-blocks) KB article is too technical for the OPIA audience. We will keep this around for team reference, but DaveC is drafting new KB articles that are more drilled in for the OPIA audience. 

This ticket is to track reviews

## Acceptance Criteria
- [x] DaveC provides drafts
- [ ] Helpdesk review
- [ ] Publish

**Comment by davidconlon** [comment]
@stefaniefgray @TroyA6 so that I'm setting these things up in the right way Here's what I'd like to do and hopefully you can help me.:

Can you create these shell pages as draft for me (I can add content, I just know I've placed them wrong in the past)
- Add a "Product guide" page for VA.gov Homepage (shell in draft, I can fill out)
- Create a new page "How to edit the homepage beneficiary-facing spotlight"
- Create a new page "How to edit the homepage news spotlight"

What I'm going to do is add content in draft for those three pages and send them to you for review, but it's probably easier for you to put the draft pages in the right place first rather than have me mess that up too.

**Comment by TroyA6** [comment]
I have not - I must have missed this...

**Comment by davidconlon** [comment]
Cool. I'll go in and add my draft content in there a little later and follow up here with when they're ready for review.
@jilladams do you want eyes-on first before sending them to Service Desk?

**Comment by jilladams** [comment]
Happy to do a once-over when they're ready.

**Comment by TroyA6** [comment]
@jilladams @davidconlon - Happy to review as well!

**Comment by jilladams** [comment]
@davidconlon  I added a draft [revision](https://prod.cms.va.gov/node/57045/revisions/view/784781/786080/visual_inline) with some changes: 
* updating "teaser" / "spotlight" language to "promo" to align with naming in the CMS block types, to reduce editor confusion
* fixed one missing letter / one typo
* Suggested language change re: character limits

**Action items:**
KB copy includes suggestions for 2 (now 3) new KBs, for now I've left that copy in the KB. I need to make 3 KB [intake](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/new?assignees=&labels=Knowledge+Base%2C+Needs+refining&projects=&template=knowledge-base-article.md&title=Create+new+KB+article+or+update++existing+article+%3A+%3Cinsert+topic+here%3E) tickets for new suggested KBs and add to existing epic of KB requests
* Have been assigned the "Homepage manager" role in Drupal. (Note: Create "How to see your role in Drupal" even if, for now, the content of that article is 'contact the help desk'
* Create: How to know what section you're assigned to. What's a section?
* KB article on how to request a KB article 

@TroyA6 ready for your review. When those intake tickets are done, we'll need to decide whether
A) we remove references to the requested KBs and publish
B) We hold publish til the 3 new KBs exist.

**Comment by davidconlon** [comment]
Option A.

**Comment by jilladams** [comment]
1. #14201 
2. #14202 
3. #14203 

@davidconlon I listed those all as Low priority ("This is not currently causing confusion for many editors but would be a nice to have or is something that may be more impactful in the future; Should be completed within the next 3-4 sprints.") but feel free to update if you disagree.
5. https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14202
6. https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14203

**Comment by davidconlon** [comment]
@jilladams those 3 articles should be for Help Desk/CMS prioritization. So that's more of an @EWashb prioritization decision. I'm only allowed to have opinions :-)

I'm still working on the other article now.

**Comment by davidconlon** [comment]
@jilladams I've created https://prod.cms.va.gov/help/vagov-homepage-product-guide/how-to-edit-the-homepage-news-spotlight for review. Would appreciate the same review and send along to Service Desk for final review/publishing (I don't need to see it again)

I've also edited https://prod.cms.va.gov/help/vagov-homepage-product-guide for links. 
We should review promo banner and may need to consider a specific homepage emergency banner article.

We also need to put in a guide for the "turn on/off the beneficiary-facing spotlight that, for now, is contact the help desk, but later will hopefully be "here's how you self-service"

**Comment by jilladams** [comment]
@TroyA6 @stefaniefgray (cc @BerniXiongA6 @productmike ) 4 KBs ready for Helpdesk review. I'm gonna reassign this ticket -- happy to help in any way you need, just lemme know.


1. Homepage product guide: modified to add links to related KBs -- https://prod.cms.va.gov/help/vagov-homepage-product-guide
2. How to edit the homepage beneficiary promo: https://prod.cms.va.gov/help/vagov-homepage-product-guide/how-to-edit-the-vagov-homepage-beneficiary-facing-promo
3. How to turn off / on the homepage beneficiary promo: https://prod.cms.va.gov/help/vagov-homepage-product-guide/how-to-edit-the-vagov-homepage-beneficiary-facing-promo/how-to-turn-off-and-on-the-beneficiary-facing-homepage
4. How to edit the homepage news spotlight: https://prod.cms.va.gov/help/vagov-homepage-product-guide/how-to-edit-the-homepage-news-spotlight

**Comment by TroyA6** [comment]
@jilladams @BerniXiongA6 @stefaniefgray @productmike - 

1. Homepage product guide: modified to add links to related KBs -- [https://prod.cms.va.gov/help/vagov-homepage-product-guide](https://prod.cms.va.gov/help/vagov-homepage-product-guide)  Reviewed by @TroyA6 - [x]

2. How to edit the homepage beneficiary promo: [https://prod.cms.va.gov/help/vagov-homepage-product-guide/how-to-edit-the-vagov-homepage-beneficiary-facing-promo](https://prod.cms.va.gov/help/vagov-homepage-product-guide/how-to-edit-the-vagov-homepage-beneficiary-facing-promo) Reviewed by @TroyA6  - [x] 

3. How to turn off / on the homepage beneficiary promo: [https://prod.cms.va.gov/help/vagov-homepage-product-guide/how-to-edit-the-vagov-homepage-beneficiary-facing-promo/how-to-turn-off-and-on-the-beneficiary-facing-homepage](https://prod.cms.va.gov/help/vagov-homepage-product-guide/how-to-edit-the-vagov-homepage-beneficiary-facing-promo/how-to-turn-off-and-on-the-beneficiary-facing-homepage) Reviewed by @TroyA6 - [x] 

4. How to edit the homepage news spotlight: [https://prod.cms.va.gov/help/vagov-homepage-product-guide/how-to-edit-the-homepage-news-spotlight](https://prod.cms.va.gov/help/vagov-homepage-product-guide/how-to-edit-the-homepage-news-spotlight) Reviewed by @TroyA6 - [x]

**Comment by jilladams** [comment]
@stefaniefgray I'd like to go ahead and publish these, and do edits as next revisions that you can go ahead and publish when you have the time to get to them. If any concerns, holler, and if not: I'll publish tomorrow.

**Comment by stefaniefgray** [comment]
@jilladams No concerns! All 4 look good to go  🚀 

Can come back and revise in the future based off of editor feedback, but otherwise, these look ready to ship. Thank you for putting these together!

- **Homepage Product Guide** - https://prod.cms.va.gov/help/vagov-homepage-product-guide - Reviewed ✅ 

- **How to edit the VA.gov homepage beneficiary-facing promo** - https://prod.cms.va.gov/help/vagov-homepage-product-guide/how-to-edit-the-vagov-homepage-beneficiary-facing-promo - Reviewed ✅ 

- **How to edit the homepage news spotlight** - https://prod.cms.va.gov/help/vagov-homepage-product-guide/how-to-edit-the-homepage-news-spotlight - Reviewed ✅ 

- **Managing homepage content blocks** - https://prod.cms.va.gov/help/managing-homepage-content-blocks - Reviewed ✅

**Comment by jilladams** [comment]
Woo! Published! Closing.
