### ISSUE TITLE
Demo Feedback: Conflicting item on job check out page

### ISSUE THREAD

**Issue by productmike** [department-of-veterans-affairs/va.gov-cms#13780]
## User story / Problem Statement
When creating translation jobs, if the user adds a piece of content for translation that has already been added to another translation job, they will see a message like the following:

> 16 items conflict with pending items and will be dropped on submission. Conflicting items: [[Test Data] Tenetur doloribus adipisci doloremque commodi nihil.](https://pr9985-md2mcx3l0miycwmefh5lz1vszw4pshdg.ci.cms.va.gov/admin/tmgmt/items/270), [[Test Data] Architecto officia et eum eos similique.](https://pr9985-md2mcx3l0miycwmefh5lz1vszw4pshdg.ci.cms.va.gov/admin/tmgmt/items/271), [[Test Data] Blanditiis molestiae dolore exercitationem odio.](https://pr9985-md2mcx3l0miycwmefh5lz1vszw4pshdg.ci.cms.va.gov/admin/tmgmt/items/272), [[Test Data] Voluptas exercitationem modi.](https://pr9985-md2mcx3l0miycwmefh5lz1vszw4pshdg.ci.cms.va.gov/admin/tmgmt/items/273), [VA decision reviews and appeals](https://pr9985-md2mcx3l0miycwmefh5lz1vszw4pshdg.ci.cms.va.gov/admin/tmgmt/items/274), [VA benefits for spouses, dependents, survivors, and family caregivers](https://pr9985-md2mcx3l0miycwmefh5lz1vszw4pshdg.ci.cms.va.gov/admin/tmgmt/items/275), [VA benefits for service members](https://pr9985-md2mcx3l0miycwmefh5lz1vszw4pshdg.ci.cms.va.gov/admin/tmgmt/items/276), [VA records](https://pr9985-md2mcx3l0miycwmefh5lz1vszw4pshdg.ci.cms.va.gov/admin/tmgmt/items/277), [VA burial benefits and memorial items](https://pr9985-md2mcx3l0miycwmefh5lz1vszw4pshdg.ci.cms.va.gov/admin/tmgmt/items/278), [VA life insurance](https://pr9985-md2mcx3l0miycwmefh5lz1vszw4pshdg.ci.cms.va.gov/admin/tmgmt/items/279), [VA housing assistance](https://pr9985-md2mcx3l0miycwmefh5lz1vszw4pshdg.ci.cms.va.gov/admin/tmgmt/items/280), [VA pension benefits](https://pr9985-md2mcx3l0miycwmefh5lz1vszw4pshdg.ci.cms.va.gov/admin/tmgmt/items/281), [Careers and employment](https://pr9985-md2mcx3l0miycwmefh5lz1vszw4pshdg.ci.cms.va.gov/admin/tmgmt/items/282), [VA education and training benefits](https://pr9985-md2mcx3l0miycwmefh5lz1vszw4pshdg.ci.cms.va.gov/admin/tmgmt/items/283), [VA disability compensation](https://pr9985-md2mcx3l0miycwmefh5lz1vszw4pshdg.ci.cms.va.gov/admin/tmgmt/items/284), [VA health care](https://pr9985-md2mcx3l0miycwmefh5lz1vszw4pshdg.ci.cms.va.gov/admin/tmgmt/items/285).

<img width="1622" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/203623/ebb2e2e0-8753-4bb0-9402-2901ab392119">

This notification is a good one, but the language is unclear and alarming. We should implement better language, and also use the CMS style for an info notification here.

After discussion with UX team members, the following language is suggested: 
> The translation for the following items is already in progress, so they will not be added to this job:

If the custom module `va_gov_multilingual` does not exist, please create it and a sub-module `va_gov_multilingual_tmgmt` within it, and house the alteration code there. 

## Acceptance Criteria
- [ ] UX provides updated language (spin off separate UX ticket if needed)
- [ ] Alter the language of the conflicting items warning to be what is provided by the UX team
- [ ] Alter the display of the conflicting items warning to be a standard CMS info warning.

**Comment by timcosgrove** [comment]
This is complete. It took far longer than I anticipated. The language provided by the module that underlies the translation management system was not positioned in ways that made substitution easy. There is a small defect that I spent nearly a day trying to fix before giving up, as it does not prevent the system from being used nor is it particularly disruptive. 

My other ticket work suffered as a result of my underestimation, and I should have deprioritized the ticket entirely or done only what was necessary and written follow-up tickets for the remainder. Lesson learned.
