### ISSUE TITLE
Facility Locator: Design Iteration #4

### ISSUE THREAD

**Issue by thejordanwood** [department-of-veterans-affairs/va.gov-cms#13792]
## Description
We had an internal review on 5/18 and discussed what updates are still needed for this.

[Link to Sketch design](https://sketch.com/s/d5e5c924-e8c0-47af-b3e4-994c335d6f31)

## Design Changes

- [x] Scrap the "Browse all health services" page in favor of a solution using expanded plain term health services taxonomy (keep design somewhere in case we revisit). Look at [536 form](https://www.va.gov/disability/file-disability-claim-form-21-526ez/introduction) typeahead for another example for "Browse all health services" page
- [x] Show the facility type on the "Search by state" if a facility type isn't selected.  Add in another line to name the facility type and alphabetize list
- [x] Put "Browse VA facilities in each state" in the link at the bottom of the map (keep use other search tools language as an OR)
- [x] Change postal code to zip code (review with content team once designs are finalized)
- [x] The mobile version should match desktop

## UX Research Notes:

- Intuitively Veterans will know that's a type ahead and it will work so they don't feel obligated to Browse all health service
- Research if the list of services will be useful
- Test comfortability with the names that are they; what are they coming to search for

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [ ] `Public Websites`
- [x] `Facilities`
- [ ] `User support`

**Comment by thejordanwood** [comment]
@ryguyk We're now trying to model the Service Type search in Facility Locator after the disability compensation 526EZ form. The 526 form has a plain term search that allows users to search for simple terms instead of looking up specific medical terminology. 

 It looks like VA health has a plain term health services taxonomy that we can use. I was wondering if other facility types have plain terms we could use for their service type searches too (vet centers, vet benefits, community providers, etc.)?

**Comment by ryguyk** [comment]
@thejordanwood I'm actually not certain. @maxx1128 might be able to offer some insight here. Can you point us to how you determined that VA health has a plain-term health-services taxonomy?

**Comment by thejordanwood** [comment]
@ryguyk After the last design review meeting, @mmiddaugh exported the VA services taxonomy for this to show the plain language terms. There may be more information you'll find useful in the last iteration ticket for this as well. 

- [VA service taxonomy](https://app.zenhub.com/files/154174777/d4cf1f94-fcc3-4ed7-b761-3a29630e7280/download)
- [Facility Locator: Design Iteration #3 ticket](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13643)

**Comment by ryguyk** [comment]
[Slack thread](https://dsva.slack.com/archives/C0FQSS30V/p1685555188190509) from sitewide-facilities.

Recap:
- Drupal data model accommodates patient-friendly names for VAMCs, Vet Centers and VBA facilities, but community providers are not managed in Drupal.
- These fields are not populated in all cases (more common on VAMCs than the others, it seems).
- This data is not currently pushed to Lighthouse.
- We can likely get this data to the browser via static JSON files (i.e. KISS) rather than via Lighthouse.
