### ISSUE TITLE
Spec Centralized Content content type for VBA

### ISSUE THREAD

**Issue by kmariepat-cityfriends** [department-of-veterans-affairs/va.gov-cms#13799]
## Description

**AS A** VBA national editor
**I WANT** to see modify content that applies to all ROs nationwide
**SO THAT** I have a streamlined editing experience, and that national content is standardized (COPE)

**AS A** Drupal engineer, 
**I WANT** a technical design document
**SO THAT** there is nothing ambiguous about the implementation requirements.

**AS A** PO, CMS team member or stakeholder
**I WANT** to see a detailed content spec
**SO THAT** I can review the design before implementation

**Example artifact**
- [Drupal Content Spec Template](https://docs.google.com/spreadsheets/d/1oD8GMll7k-9E2AYCjUIl_Eu48wKfXyurfnW63b2G0_k/edit?usp=sharing)
- [Drupal Content Spec TEMPLATE.xlsx](https://github.com/department-of-veterans-affairs/va.gov-cms/files/11113423/Drupal.Content.Spec.TEMPLATE.xlsx)

![Screenshot 2023-05-23 150922](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/2af06634-7920-4356-a5a8-c8a99133aebd)

## Supporting documents
- [VBA RO designs, Sketch](https://www.sketch.com/s/891d33ae-152d-471c-ab5d-9aedf89cf6ff) Centralized Content = annotated in Sketch comments.
- [VBA Content Model diagram](https://app.mural.co/t/departmentofveteransaffairs9999/m/vagov6717/1677277602711/74cecb64b6eeb9558aa868240cd726b54fcb93a7?wid=0-1680038357024) (Mural)
- [Five previous specs combined into one](https://github.com/department-of-veterans-affairs/va.gov-cms/files/11544361/VBA.Drupal.Content.Spec.ALL.1.xlsx) 
- [Centralized Content intro video](https://www.youtube.com/watch?v=uLUXpbc1DhM)

### Sprint 92 ACs - 5 points
- [x] [Dave] Elements in the VBA FE design that will be determined at a national level for all Regional Office pages (e.g. spotlights, national hotline CTA) are documented.

### Sprint 93 AC - 5points
- [x] ~Draft document of content design~ - do not need spreadsheet, bc these fields are all using existing paragraph types. Dev is unblocked.
- [x] Review implementation of Centralized Content content type for Vet Centers
    * We will adapt the existing Centralized Content node type to accommodate our data needs. Existing Centralized Content form: https://prod.cms.va.gov/node/add/centralized_content
    * We will create a single VBA RO Centralized Content node. Vet Centers is already set up this way. Their CC node: https://staging.cms.va.gov/node/16142/edit. (Staging CMS uses a standardized password.)
- [x] Review backlog for Vet Center centralized content tickets to see where effort overlaps / dupes / opportunities to satisfy multiple tickets with this work
- [x] Implementation ticket is updated with takeaways from the review - #14699 
- [ ] Review document with Product and Drupal engineering
- [ ] Share Centralized Content topic dive with CMS team for review / awareness

**Comment by laflannery** [comment]
After looking at other existing Spotlight CMS patterns and discussing with Michelle, we talked through what the standard spotlight pattern should look like going forward and would ideally like VBA to use this if possible:

- It is based on what Vet Center is currently using but with some labeling changes
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/106678594/2555becf-bf3b-4d6a-84dd-2c9d193881b7)
- Featured content:
  - Change label to Spotlight content - this will help with consistency and lessen confusion by aligning CMS and FE naming conventions
- Section Header
  - Change label to Title - section is a term used very specifically for something else within the CMS so should be avoided whenever possible to refer to other things.
  - Keep field as required
  - Keep field as a text input
  - Keep character limit at 80
- All other fields (Description and Call to Action fields) can remain the same including all existing character limits and labeling.

**Comment by davidmpickett** [comment]
Given that this content type is very heavily tied to the FE design, I would suggest that we do not spec this out until after usability research is complete and any updates to the design are implemented.

**Comment by mmiddaugh** [comment]
Summary of business feedback/decisions from Office of Strategic engagement:

Design should include 
- Gov Delivery
- national social media only (no local)
- 1 centralized/national spotlight with 2 local/editor level spotlights
- AVA and VERA

Pending questions 
- programmatic vs radius based nearest locations

**Comment by mmiddaugh** [comment]
We'll need to consider events sooner than later as it is a significant method of delivering services at some locations. Spotlights will not offer the flexibility needed for the number of events or variety of locations. 

Use case: [Honolulu Regional Office](https://www.benefits.va.gov/honolulu/) lists 9+ events occurring this week. 
<details>
<summary> Snapshot from July 19 </summary>

![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/55411834/0f23fd23-98ce-4331-b70f-5028a2743289)

</details>

**Comment by mmiddaugh** [comment]
"Other nearby locations" should be programmatically addressed - let's not leave this to editors.

**Comment by jilladams** [comment]
From team refinement: this _could_ go into FE hard coded for MVP launch. 
Or, we can Drupalize now. 
Next step: FE architecture conversation to understand difference in the lift if the data is hard coded. And: effort from CMS team, including CMS Collab Cycle.

**Comment by davidmpickett** [comment]
> Summary of business feedback/decisions from Office of Strategic engagement:
> 
> Design should include
> 
> * Gov Delivery

@mmiddaugh Double-checking an assumption here. Is Gov Delivery per facility? Or is it just national.

**Comment by xiongjaneg** [comment]
drupalize or hardcode or mvp

**Comment by davidmpickett** [comment]
[New page in sketch file ](https://www.sketch.com/s/891d33ae-152d-471c-ab5d-9aedf89cf6ff/p/23336061-721C-400F-BEAD-0DED48F3A8EF/canvas)with annotations about Drupal vs Hardcoded

**Comment by davidmpickett** [comment]
## All annotations

![VBA-all-annotations](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/92b64b14-9cbd-4780-8983-b4fa4bd25132)

## Drupal annotations

![VBA-drupal-annotations](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/b3263a43-127e-4608-8632-d7818d33d431)
0/4d3efdfd-0983-4fc2-a715-1565523e43ee)

## Hardcoded annotations

![VBA-hardcoded-annotations](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5196795

**Comment by jilladams** [comment]
Tracked 5 points from Sprint 92. We'll need new estimate for ACs in Sprint 93.

**Comment by jilladams** [comment]
From scrum: 
* We don't need a spreadsheet version of this spec, bc it uses existing fields & screenshots suffice.
* CMS folk can run with this.

**Comment by davidmpickett** [comment]
>  Review backlog for Vet Center centralized content tickets to see where effort overlaps / dupes / opportunities to satisfy multiple tickets with this work

Step 0 for this AC - I just went and tagged a whole bunch of issues with the [Centralized Content label](https://github.com/department-of-veterans-affairs/va.gov-cms/labels/Centralized%20Content) so there is a clear way to see the product/feature history

**Comment by davidmpickett** [comment]
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/4195 - tagged @swirtSJW for review on relevance/value
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/4055 - fleshed out the ticket with examples and recommendations

**Comment by jilladams** [comment]
from Scrum: 
* Jane / Jill to discuss Centralized Content ownership with Michelle.
* ANy updates made on behalf of VBA should be documented by the Facilities in existing docs.

**Comment by davidmpickett** [comment]
From refinement last week: the [follow up ticket](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14699) is ready to go.  I think this is safe to close
