### ISSUE TITLE
Update KB: how-do-i-feature-a-story-on-my-sites-homepage

### ISSUE THREAD

**Issue by kmariepat-cityfriends** [department-of-veterans-affairs/va.gov-cms#13795]
update old content in the following KB:
-  https://prod.cms.va.gov/help/vamc/how-do-i-feature-a-story-on-my-sites-homepage

- Need to remove 1st and 2nd
-

**Comment by EWashb** [comment]
@xiongjaneg @BerniXiongA6 @mmiddaugh @jilladams 

Here is the article about the KB updates that need to be completed for the stories being 1 and not 2.

**Comment by jilladams** [comment]
Related slack thread: https://dsva.slack.com/archives/C02730UEZPS/p1698082410704429
Assigning to @xiongjaneg based on notes in that thread.
 
Context from the "rethink how to feature stories" #11401 epic body re: what was defined vs. how things work in prod today: 
> Background from @swirtSJW and @JayDarnell
> * The original design included 2 featured stories (and 2 events) and there is indication in the UI that this is still the case though it isn't.
> * When a story is created, there is an option to make it featured
> * Currently, creating a 2nd featured story, removes the feature attribute from all other stories
> * If we're going to support 2 featured stories
>   * When you create a 2nd featured story, what should happen to first featured story?
>   * If we do intend to support 2 features. then if you already have two featured stories, and create a new featured story, how do we decide which of the first two to eliminate? How to expose to editor and have them decide?
> * This is similar to events, but events expire and if there's no featured event, we display the next chronological event

**Comment by xiongjaneg** [comment]
saved draft of language removing references to two featured stories, however, this doesn't match the current UI, which still mentions two stories in the UI and allows the editor to pick the order of 1 or 2

**Comment by EWashb** [comment]
Reviewed @xiongjaneg's updates and all looked well. The biggest question is the above ^ which is being chatted through on the thread mentioned.
