### ISSUE TITLE
Update php-github-api

### ISSUE THREAD

**Issue by edmund-dunn** [department-of-veterans-affairs/va.gov-cms#13794]
## Description
We use the KnpLabs/php-github-api in the `va_gov_consumers` custom module. To line it up with D10 dependencies, we need to submit a PR for KnpLabs/php-github-api with updates to the following dependencies. We will also need to fork it with those updates so we can use the forked version until our PR is merged.

```
    - drupal/core-recommended 10.1.0-beta1 requires psr/http-message ~2.0 -> satisfiable by psr/http-message[2.0, 2.0.x-dev].
    - drupal/core-recommended 10.1.0-beta1 requires symfony/deprecation-contracts ~v3.2.1 -> satisfiable by symfony/deprecation-contracts[v3.2.1, 3.2.x-dev].
    - drupal/core-recommended 10.1.0-beta1 requires symfony/error-handler ~v6.3.0-BETA3 -> satisfiable by symfony/error-handler[v6.3.0-BETA3, v6.3.0-RC1, 6.3.x-dev].
    
```

## Acceptance Criteria
- [ ] Submit PR for KnpLabs/php-github-api 
- [ ] Fork with updates in place for us to use until he pr is merged

### Team
Please check the team(s) that will do this work.

- [x] `CMS Team`
- [ ] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`

**Comment by ndouglas** [comment]
My changes are not backward-compatible with the existing state of the upstream package, so far as I can tell. This would be a major version difference for them and it wasn't terribly complicated, so this leads me to think that there is a reason they haven't done this yet. I'm looking into that but I'm not seeing much information.

My opinion is that we should consider either forking the package and using our fork or replacing the package and just using the Guzzle tools to make the requests. We don't have that many discrete methods that we call, so it shouldn't be that effort-intensive of a task.

**Comment by ndouglas** [comment]
guess this is not needed now.
