### ISSUE TITLE
Onboarding: ALogsdon3, Alexis Logsdon

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#13807]
# Welcome to the VA.gov Modernization Team! 👋
We're thrilled to have you join us on this journey! 🎆🎉🙌

Our [vision](https://docs.google.com/presentation/d/14mK-4OMeEnR_-fgj62U4lUHBHg6htj4i4ucTA5DJFzg/edit#slide=id.g11ae1dc437e_0_1) is to craft a seamless editorial experience that empowers editors to create Veteran-centered content. In April of 2022, we also assumed responsibility for a portfolio of front-end products and sites.

The onboarding materials below are organized by chronological time to complete (day one, week one, week two, month one); and main category (why, how, who, what). There's a lot to digest but don't worry, your Delivery Manager will guide you, you'll have an onboarding buddy to provide support, and we'll also introduce you to your workstream's lead to help with specific things related to your discipline (UX, DevOps, Drupal Engineering, etc). In addition, you'll have the support of the entire team, who have all gone through this process before and are eager to answer any questions that arise. Come back to this ticket any time to refresh your knowledge on a specific topic covered below.

Have fun and we look forward to getting to know you! 😊

Projected start date: 5/24/23

**Team info**
- Onboarding buddy (short check-in meetings the first week): @cindymerrill 
- Team name: Sitewide Facilities
- Delivery Manager name: @jilladams 
- Product Manager name:  @kmariepat-cityfriends 
- Discipline lead name: @cindymerrill 

[Day One](#day-one)
[Week One](#week-one)
[Week Two](#week-two)
[Month One](#month-one)
[Onboarding for UX members](#onboarding-for-UX-members)

## Day one
Your top priority is any onboarding paperwork provided by Contract Onboarding folks. Start tasks below after that.

### Process & Principles
- [x] Read through our [team norms](https://docs.google.com/document/d/1cs5FePhtR0LIJi63b9ZtqT7T6dphgB584UpfEbejSOc/edit#), which will also give an overview of how we apply the [USDS playbook](https://playbook.cio.gov/) and VA.gov platform [code of conduct](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/policies-work-norms/code-of-conduct.md).
- [x] Read the [VA.gov platform mission and goals](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/onboarding/library/VA.gov%20Platform%20Overview%202021.pdf).
- [x] Read the [VA's Office of the CTO (OCTO) engineering excellence guiding principles](https://dsva.slack.com/archives/C04KXPXL4/p1674065912579799) [post in DSVA slack]

### People
- [x] Meet with A6 Contract Onboarding Specialists (COS) to get an introduction to the paperwork process. They'll schedule.
- [x] Who is our team? [View & bookmark this Mural org chart](https://app.mural.co/t/departmentofveteransaffairs9999/m/vagov6717/1653588059793/7a260edabca9535d25d71fac1035c979261c223c?sender=u0b235d03cbd64f7f93673243)
- [x] Complete your personal information & bookmark the [official team roster](https://docs.google.com/spreadsheets/d/1S31-cj0TPczh4K9r2G--kERqZStOOECX_W2VrQy3kRA/edit#gid=0). Note: this is separate from the Platform roster mentioned in Day 1 section.
    * Your DM will ask you to update your paperwork status until you receive official clearance.
    - [x] Make your Google calendar publicly accessible, showing free/busy time. This will allow team members in other organizations to easily schedule with you. See [Mark your calendar as public](https://support.google.com/calendar/answer/37083?hl=en#zippy=%2Cmark-your-calendar-as-public).
- [x] Who is on the team? Read your [team members' user manuals](https://drive.google.com/drive/u/0/folders/195otsT1IUxi_k8oEU21TUkvEG-6p5YQj?ths)
- [x] Create your own User Manual: duplicate [the template](https://docs.google.com/document/d/1Rvtoo8CQvE7dptcqmMVqmJ_hbKSNWJ983NXkDj_gVg0/edit?usp=share_link), fill it out, and save your manual in your team's folder.
   - [x] Share your user manual with your team in Slack, once you've created it!

### Access & Delivery
- [x] Open a VA.gov [Platform orientation ticket](https://depo-platform-documentation.scrollhelp.site/getting-started/guidance-for-new-teams-and-team-members#Guidancefornewteamsandteammembers-NewVFSteammembers). Orientations may only be available several weeks out, so sign up as soon as you're able.
    * The VA.gov Platform team manages VA.gov tooling and network access. In order to receive access to many tools you'll need day to day, you must access the SOCKS network proxy (described later). For SOCKS access, you must 
        1. complete the steps described in the link above 
        2. complete your eQip paperwork and receive/provide a screenshot of the email with your E-QIP transmittal date,
        3. attend a Platform orientation. If a Platform orientation isn't available for several weeks, sign up for the next available slot, then mention your Delivery Manager and/or Program Manager on your Platform ticket to expedite SOCKS access.
    * When those steps are complete, the VA Platform team will add you to the [VFS Platform roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665). This will allow you to get SOCKS access.
- [x] Contract - Ask your Delivery Manager anything you would like to know about your contract.

## Week one
The goals of this week are: 
1) get background paperwork completed as quickly as possible 
2) start gaining context for what we're doing and why

### Access & Delivery
**Paperwork**
You'll receive an email from A6 COS directing you to the paperwork you should fill out for secure access to relevant VA systems. Federal contractors are required to complete many of the same forms as federal employees.
- [x] Complete & submit your initial paperwork according to instructions, including setting up your fingerprinting appointment. 
- [x] When you are notified to complete your e-QIP (the online version of the federal standard investigation form, SF 86), it will require a lot of background & family information. [Review page 7 of the SF 86 guide](https://www.dcsa.mil/Portals/91/Documents/pv/mbi/standard-form-sf-86-guide-for-applicants.pdf) in advance for the list of information you'll need to collect to complete e-QIP.

#### Github / Zenhub configuration
Github + Zenhub are the tools required for sprint boards, epics, estimates, and issue tracking for our team, as well as code version control. To work successfully: 
- [x] New Hire: Create a Github user account
- [x] New Hire: Add your agency email address to your Github account at https://github.com/settings/emails
- [x] Delivery Manager: Creates a [Github request](https://github.com/department-of-veterans-affairs/github-user-requests/issues/new?labels=add-user-to-org%2C+new-user%2C+user-created&template=add-user-to-the-va-organization.md&title=ADD+USER+TO+ORG+-+%5BUSERNAME%5D) to add your Github user to the Dept of VA Github organization. This will provide you with access to view VA repositories. 
- [x] New Hire: Accept the Github org invitation. It will appear as a yellow banner at the top of https://github.com/department-of-veterans-affairs
- [x] Delivery Manager: After invite is accepted, add user to the [VFS-CMS team](https://github.com/orgs/department-of-veterans-affairs/teams/vfs-cms-team/members). You must be added to this team to contribute to [va.gov-cms repository](https://github.com/department-of-veterans-affairs/va.gov-cms/) code and issues in Github.
- [x] New Hire: Install the [Zenhub browser extension](https://www.zenhub.com/extension) in your browser of choice
- [x] Delivery Manager: Log into app.zenhub.com, click "Invite your team" button in lower left sidebar, invite new hire via their agency email address. This will generate a license request that must be approved by Zenhub admins within the VA. In the meantime, new hires may see a "You do not have a license" message when they log in to app.zenhub.com.
- [x] VA Zenhub Admins: Must approve the license request. If they're slow about it, in DSVA slack, use @zenhub-admins to mention and request help. Licenses might not be approved until after the new hire has been fingerprinted. 
- [x] New Hire: Verify Zenhub access by logging into app.zenhub.com, using Google auth with your agency email address. **Do not use Github oauth**. It's no longer supported by the VA.

**Sprint boards:**
You can view team sprint boards using either the Github view with Zenhub browser extension enabled, or the Zenhub webapp view.
* CMS team: [Github view](https://github.com/department-of-veterans-affairs/va.gov-cms/#workspaces/vagov-cms-team-5c0e7b864b5806bc2bfc2087/board), [Zenhub webapp view](https://app.zenhub.com/workspaces/vagov-cms-team-5c0e7b864b5806bc2bfc2087/board)
* Facilities: [Github view](https://github.com/department-of-veterans-affairs/va.gov-cms/#workspaces/sitewide-facilities-639f5253e4b702a32376339e/board), [Zenhub webapp view](https://app.zenhub.com/workspaces/sitewide-facilities-639f5253e4b702a32376339e/board
)
* Public Websites: [Github view](https://github.com/department-of-veterans-affairs/va.gov-cms/#workspaces/public-websites-6171bf4bf43742001af18cc5/board), [Zenhub webapp view](https://app.zenhub.com/workspaces/public-websites-6171bf4bf43742001af18cc5/board)

### Process & Principles
- [x] Read about our teams' [Agile / sprint best practices](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/onboarding/library/sprint-best-practices.md)
- [x] How do Agile 6 and our partners work together on this project? Discuss with your Delivery Manager.
- [x] Read your team's Charter:
    * [CMS]()
    * [Facilities](https://docs.google.com/document/u/1/d/1eI1w9Bcj2rlmFtxkM6Dkn_c-Srszd88UxAQimSZkVqo/edit)
    * [Public Websites](https://docs.google.com/document/d/1jiq90ffon5UxAqybiEncl8feqmXhEOChlijiDBOWUtc/edit)
- [x] Check your calendar for invitations to team ceremonies.
  - [x] Scrums
  - [x] Planning session
  - [x] Refinement session(s)
  - [x] Demo
  - [x] Retro

### People
- [x] Familiarize yourself with our team's [shared calendar](https://va-gov.atlassian.net/wiki/spaces/VAGOV/calendars) and add in any known upcoming out of office (OOO). Choose "Calendar" = OOO and "Event type" = whatever is relevant.
- [x] Let's start introducing you to the team and key stakeholders. If you're on a meeting where you don't know someone, feel free to kickstart an introduction. Everyone in the ecosystem is friendly and interested in connecting.

### Context & History
- [x] How does the team fit into the larger OCTO ecosystem? [View this Mural diagram](https://app.mural.co/t/vagov6717/m/vagov6717/1643724063628/1654203c1a0d6c763bbd5c969febf94ec476df79?sender=u0b235d03cbd64f7f93673243)
- [ ] Why is VA.gov using a Drupal CMS and how is our success measured? Read the [objectives and key results](https://va-gov.atlassian.net/wiki/spaces/VAGOV/pages/96698383/Product+CMS).
- [x] [Watch the Drupal GovCon presentation about the project](https://www.youtube.com/watch?v=WN4bGjEuQdM).
- [x] Why are VA Medical Centers changing their websites? Watch the [2-minute YouTube video](https://youtu.be/Xrv5wCv6cKY).
- [x] Why are Vet Centers important to Veterans? Watch the [2-minute YouTube video](https://www.youtube.com/watch?v=VMzkZNbKk1I).

## Week two
The goal for this week is to get you set up with the tools you need to be successful. We will pair you up with a buddy on the project that is in your same discipline to help inform which ones are relevant and which aren't. **The most important thing is to get set up is SOCKS** as it will give you access to our systems so try to prioritize that.

### Process & Principles
- [x] Check your calendar for invitations to team ceremonies.
  - [x] Scrums
  - [x] Planning session
  - [x] Refinement session(s)
  - [x] Demo
  - [x] Retro

### Context & History: What products do we support?
- [x] Review [History of sitewide product portfolio & teams mural](https://app.mural.co/t/vagov6717/m/vagov6717/1646745279937/9a5570c420939d84e875e8334fd73073e3a3971b?fromVisitorModal=true&sender=u0b235d03cbd64f7f93673243).
    - [x] Discuss with your Delivery Manager and Product Manager for more context on your team's products. 
- [x] [Review the editor onboarding slides](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/onboarding/library/https___prod.cms.va.gov_sites_default_files_2021-07_Welcome%2520to%2520the%2520new%2520VA.gov%2520CMS.pdf).
- [x] Read the [product sheets](https://github.com/department-of-veterans-affairs/va.gov-team/raw/master/platform/cms/VA-CMS-Product-Sheets.pdf) (PDF download).

### Access & Delivery
- [x] [Opt out](https://www.va.gov/analytics-opt-out.html) of Google Analytics collection on VA.gov.
- [ ] [Opt out](https://depo-platform-documentation.scrollhelp.site/?internal-user-opt-out=true) of analytics for Platform's website. You will not get a confirmation message and will have to do this for every browser and every time you clear cookies.

#### Github for issue tracking and document sharing
- [x] [Intro to CMS Team Github](https://github.com/department-of-veterans-affairs/va.gov-cms#readme) - describes an overview of our project in terms of repositories and architecture
    - [x] New to Github and markdown? [Learn about writing on Github](https://docs.github.com/en/github/writing-on-github/getting-started-with-writing-and-formatting-on-github) or [watch a tutorial video](https://youtu.be/TBbtbKplUoc)

#### Slack for instant messaging
- [x] [Review Slack etiquette](https://slack.com/blog/collaboration/etiquette-tips-in-slack).
- [x] Update your profiles in Slack (in DSVA and your agency workspace): add a calendar link, profile picture, your role and team.
    - [x] Your Delivery Manager should add you to appropriate Slack user groups for the DSVA workspace (e.g. `@cms-team`, `@cms-helpdesk`, `@public-websites-team`, `@facilities-team`. Also `@cms-engineers-group` for eng.)

**Channels** 
- [x] A6/agency workspace = `#proj-sitewide-vfs-cms-team`
 - [x] DSVA workspace = `#sitewide-program`, and your team channel e.g. `#cms-team`, `#cms-platform`, `#sitewide-public-websites`, `#sitewide-facilities`
 - [x] [VA Slack Channel Overview](https://docs.google.com/spreadsheets/d/1_lZzectbSzs8zt4dvTFJTiPURxa0Kfp3xinYEuZdqq4/edit#gid=0) describes useful channels to be aware of / join. Note that many are going to be dependent on which workstream you're in (DevOps, Helpdesk, UX, etc.). Feel free to join whichever you think will aid you and your work. 

#### SOCKS - VA network proxy (after your Platform Orientation)
The VA network is required in order to access Drupal CMS and other VA tools. Network access usually requires a VA ID card (also called a "PIV" or Smartcard). Until your paperwork is approved and you receive a PIV card, using the SOCKS proxy can provide earlier acces to some of these tools. **You cannot be approved for SOCKS access until your eQip is sent and you receive a "transmittal notice" confirming receipt.** If you have received an eQip transmittal notice, but not a PIV, please complete the steps for SOCKS access. This is the first priority for week two, especially for engineers. (If your role doesn't demand immediate access to the CMS, you may be able to wait until you receive a PIV.) 

This can be a complex process. Post in #sitewide-program Slack channel if you need help from a current member - we're happy to help.
  - [ ] Take a screenshot of your eQip transmittal notice.
  - [ ] [Request a Github personal access token](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token). You only need to do the "repo" panel in that form and leave the other panels as is. You'll need the output of this for your SOCKS request.
  - [ ] File a [SOCKS proxy request](https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html) and select the label for your team.  It may take a day or two for the SOCKS proxy request to be fulfilled before you can complete the rest of the SOCKS process. 
    - [ ] Attach your eQip transmittal notice screenshot. This is an acknowledgement that your paperwork is being processed from a security standpoint. You cannot receive SOCKS access prior to this point in your onboarding.
    - [ ] Add a comment to note the scheduled date of your [Platform orientation](https://depo-platform-documentation.scrollhelp.site/getting-started/Calendly-Orientation-Sessions.2133393543.html#CalendlyOrientationSessions-GeneralOrientation), if you haven't yet completed it. (This should have been requested on day one but is here as a reminder that this is a blocker for SOCKS access.)
- [ ] Optional [Core Tunnel set up for SOCKS proxy on all browsers on Mac](https://www.youtube.com/watch?v=fSuN9LhkB5o)

You can file the SOCKS request before completing your Platform Orientation, but it may not be approved/fulfilled until after.

#### Drupal 
Drupal is the VA's content management system of choice. For anyone on our team, it's beneficial to have a CMS user account so you can login, look at settings, and understand how the CMS works at a high level. If you need help completing the technical steps here, schedule 30 mins with your Delivery Manager.
  - [x] **Drupal production access**: (SOCKS or VA network required) - in DSVA #cms-support channel, use the Slack workflow to file a helpdesk support request. Ask the helpdesk to create a Drupal user for you in [prod.cms.va.gov](prod.cms.va.gov). 
     * DevOps team members require an administrator account. (SOCKS or VA access with PIV card required)
     * Standard practice for other roles is to have minimal access in prod (content editor or even a blocked account) and full admin access in lower environments.
  - [ ] [View short presentations on specific topics](https://va-gov.atlassian.net/wiki/spaces/VAGOV/pages/1714094110/CMS+Topic+Dives). Topics include site alerts, release and deploy, Facility API, etc.
  - [ ] [Browse the VA Drupal CMS Knowledge Base articles](https://prod.cms.va.gov/help/).
  - [ ] What is Drupal? [Link list for Drupal context and community](https://docs.google.com/spreadsheets/d/11ppWiIggKJh-YAWia28utZXW48tJZGCEg-sFJ6eIl9c)

##### Tugboat demo environments (Drupal)
Tugboat is a development server platform where you can preview CMS code changes pre-production. 
  - [ ] [Tugboat for engineers](https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/READMES/tugboat.md)
  - [ ] [Tugboat for non-engineers](https://prod.cms.va.gov/help/demo-environments-tugboat-guides) SOCKS required

#### Other tools / access
- [x] [Confluence](https://va-gov.atlassian.net/wiki/spaces/VAGOV/pages/179765342/2020-2021?NO_SSR=1) for team calendar, demo run of show, and reporting.
- [x] [Google Drive](https://drive.google.com/drive/u/0/folders/0ADx85_gnl3Y4Uk9PVA?ths=true) for team documents. VA doesn't have access to view Google products while on the VA network. Use Github or downloadable files when sharing with VA.
- [x] [Trello](https://trello.com/vacmsteam) for retro boards

## Month one
By this point you should have enough context and access to be able to start contributing. Work with your team to identify specific issues to focus on.

### People
- [x] Who are our VA points of contact? Discuss with your Delivery Manager or Product Manager.
- [x] Who should we know on the platform teams? Discuss with your Delivery Manager or Product Manager.

### Access & Delivery
**Paperwork**
- [x] Complete any VA-assigned trainings in the TMS system. If the TMS learning modules malfunction, assign yourself the print version of the module. (Ask in #proj-sitewide-vfs-cms-team if you need help.)
- [x] You'll receive an email confirming that you have been approved for remote access, using Citrix Access Gateway (CAG). You can contact Enterprise Service desk via provided instructions to set up your CAG access manually, if you need access prior to receiving your PIV card.
- [x] After your background check is complete, you will get an email to get your Personal Identify Verification (PIV) card. Contact your local VA office (where you got your fingerprints taken) for information about getting your [PIV card](https://www.oit.va.gov/programs/piv/how-to.cfm?). 
  - [x] Review a [video about the benefits of the PIV card and VA network access](https://youtu.be/6rI-i8zmOzE).
  - [x] PIV card will help you get remote VA network access. See [VA network remote access options](https://www.oit.va.gov/resources/remote-access/index.cfm?) 
    - [x] [Azure virtual desktop is recommended for Windows](https://www.oit.va.gov/resources/remote-access/azure-virtual-desktop/)
    - [x] Mac users should [follow these CAG download instructions](https://docs.google.com/document/d/1_3HKMk4AXyqAoQcfF4CthEQ7uU_d1h9Tt7CPHGJ-FaM)
    - [x] Purchase a card reader, if you don't have one. A6 IT recommends these options: [USB](https://www.amazon.com/gp/product/B002N3MM6W/ref=ppx_yo_dt_b_asin_title_o01_s00?ie=UTF8&th=1) or [USB-C](https://www.amazon.com/gp/product/B002N3MM6W/ref=ppx_yo_dt_b_asin_title_o01_s00?ie=UTF8&th=1)
    - [x] Use your PIV card to access CAG. You must access CAG every 60 days or your access will be expired.

### Discipline specific onboarding (UX, developers, helpdesk, etc.)
Remove the sections that don't apply

- [x] What do I need to know about my discipline on this team (DevOps, Engineering, Helpdesk, ID, UX)? Discuss with your discipline lead.
- [x] What applications or discipline-specific tools are needed? Discuss with your discipline lead.

## Onboarding for UX members
Your discipline lead will assist with onboarding tasks / calls.

- [x] Attend design onboarding call 1: [You are here](https://docs.google.com/presentation/d/1zrHekhA56JhtobKv8JtEUyM_d9sMWYTh1CWIjVcYTzI/edit)
   - You'll get an invite during Week 3-ish.
- [x] Attend design onboarding call 2: [Partners](https://docs.google.com/presentation/d/1__iyFNPB03u850nXDjG4uRgK0jmCL16e5PradD29jmk/edit)
   - You'll get an invite during Week 3-ish.
- [ ] Reading (this is more for Public Websites and Facilities teams, but helpful context for everyone)
   - [Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/collaboration-cycle-kickoff)
   - [Research Overview](https://depo-platform-documentation.scrollhelp.site/research-design/research-overview)
   - [VA Design System](https://design.va.gov/)
- [x] Install tools and request access if not already provided
   - [x] Sketch (for designers on Public Websites or Facilities)
   - [x] [Mural](https://app.mural.co/t/departmentofveteransaffairs9999) - when you have been assigned your VA email address, ask your DM to add you to Team folders in Mural. Without a VA email, other users can share the Visitor link to Murals so you can view them meantime.
   - [x] Figma (for designers on Sitewide CMS)
   - [x] Airtable (for Research / Content strategists)
   - [x] Review and start getting acquainted with existing design systems.
- [x] Helpful Slack channels to join
   - #accessibility-ops
   - #design
   - #cms-design
   - #inclusive-design
   - #research-ops
   - #accessibility-help
- [ ] Fonts to download
   - Lucida Grande [download from fontsgeek.com](https://fontsgeek.com/fonts/Lucida-Grande-Regular)
   - Source Sans Pro [download from Google Fonts](https://fonts.google.com/specimen/Source+Sans+Pro)
   - Bitter [download from Google Fonts](https://fonts.google.com/specimen/Bitter)
- [ ] Request an "Ask-Me-Anything" call [optional]
   - It's an opportunity to ask any lingering questions and clarify any information we've covered.
- [x] Download a [markdown cheat sheet](https://cheatography.com/lucbpz/cheat-sheets/the-ultimate-markdown/pdf/) [optional]
- [ ] Request a Github Cliff's Notes call [optional]
  - Aren't comfortable with Github? It's cool. We have people who can help.
  - [ ] Watch the "Github / pull request basics for non-engineers" [Topic Dive](https://va-gov.atlassian.net/wiki/spaces/VAGOV/pages/1714094110/CMS+Topic+Dives)

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [ ] `Public Websites`
- [x] `Facilities`
- [ ] `User support`

**Comment by jilladams** [comment]
@ALogsdon3 I did some work on our onboarding template today, so I updated your ticket to have those changes. Which is to say: yes, it looks different, you're not crazy. :D

**Comment by cindymerrill** [comment]
@jilladams Has @ALogsdon3 been invited to a Platform onboarding session? That's essential before doing UX work for/with Veterans. Here's Platform's website: https://depo-platform-documentation.scrollhelp.site/. There's a _Getting started_ link that may be helpful. Plus, I'd definitely recommend perusing the _Research and design_ pages.

**Comment by ALogsdon3** [comment]
> @jilladams Has @ALogsdon3 been invited to a Platform orientation session? That's essential before doing UX work for/with Veterans. Here's Platform's website: https://depo-platform-documentation.scrollhelp.site/. There's a _Getting started_ link that may be helpful. Plus, I'd definitely recommend reading the _Research and design_ pages.

@cindymerrill I'm signed up for one next week on Tuesday. :) I have those pages bookmarked to read through.

**Comment by jilladams** [comment]
After these comments and talking to Cindy today, I've added this section to our [onboarding ticket template](https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/.github/ISSUE_TEMPLATE/cms-team-and-sitewide-crew-member-onboarding.md): 

Onboarding for Researchers:
- [ ] Review https://depo-platform-documentation.scrollhelp.site/research-design/
   - [ ] [Sign up for the next research and design orientation session](https://calendly.com/collaboration-cycle/design-orientation-for-va-gov-platform)
- [ ] Ask for invitation to Monday Research meeting
- [ ] Ask (who?) to be invited to the [va.gov-research-repository](https://github.com/department-of-veterans-affairs/va.gov-research-repository)
- [ ] Join #research-ops channel in DSVA slack

If you come up with more things that Researchers need up front, just @ me in comments here and I'll them!

**Comment by cindymerrill** [comment]
I'll post here with UX research/design onboarding tasks, including the following:

- Join DSVA #design slack channel and request that your agency and VA email addresses be added to the invite for the weekly Monday VA Design/UX Sync meeting (@mention Cailin O'Connor)
- Join DSVA #research-ops slack channel and request that you be added to the research repo (@mention Shane Strassberg)

**Comment by cindymerrill** [comment]
@jilladams My previous comment has some answers for you, which I posted before I saw your questions :)

**Comment by ALogsdon3** [comment]
@cindymerrill @jilladams just an update for future onboarding tickets: Shane Strassberg says that if you do the Platform orientation you get added to the research repo automatically

**Comment by cindymerrill** [comment]
Here's something else that @ALogsdon3 should do if she hasn't yet: 

[Opt Out of Google Analytics](https://www.va.gov/analytics-opt-out.html) for VA, so that your activity on VA.gov as a contractor doesn’t inflate user metrics.
FYI @jilladams

**Comment by jilladams** [comment]
Yes - that's an action included in the template body of this ticket, during Week 2

**Comment by ALogsdon3** [comment]
@jilladams @cindymerrill  I opted out of Google Analytics, but it's less clear how to opt out of Platform analytics. The link in the task is just the Platform landing page and I didn't find the opt-out info through searching the site or browsing pages.

**Comment by ALogsdon3** [comment]
In Helpful Slack channels to join: I didn't find a #/inclusive-design channel. Should this say #/inclusive-research?

**Comment by cindymerrill** [comment]
I think so. #inclusive-research is a great channel to join.
