### ISSUE TITLE
Form widgets that enforce character limits should not enforce those limits on translations

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#13806]
## Story
As a CMS editor, I want character limits on source text to not be enforced in translations, so that those translations can be accurate to the source text while rendered correctly in the translation language.

## Description
When text is translated from English into other languages, it often becomes longer than the English. We need to allow text to get longer for other languages.

We also need to sometimes enforce character limits on text, for a variety of reasons. In general, character limits can be enforced at the form level and/or at the database level. However, the CMS stores translated versions of text in the same location as its English. 

Therefore, we cannot enforce the limits at the database/field structure level. We need to allow for arbitrary text length (`text_long`), and to enforce character limits at the form. Additionally, these form widgets should not enforce length limits on translations. 

We will be shifting all character limitations to use the widgets provided by the textfield_counter module. We will need to alter these widgets so that the character count is not displayed and not enforced on translations. 

This should be done from the perspective of 'source' vs 'translations' of entities and their forms, rather than English vs non-English. In our case it is unlikely that we would translate content that was initially created in a languages besides English, but we should account for that  possibility and provide text limits there.

## Notes
This issue may be helpful, though I don't think it completes our use-case: https://www.drupal.org/project/textfield_counter/issues/3004457

Handling any change of underlying field type from e.g. `text` (with a database-enforced limit) to `text_long` (no database limit) is outside the scope of this ticket. #13512 is handling that.

## Acceptance Criteria
- [x] Any text limit widgets provided by textfield_counter do not enforce text limits on entity translations
- [x] These widgets do not show the counter on translations

### Team
Please check the team(s) that will do this work.

- [x] `CMS Team`
- [ ] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`

**Comment by productmike** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VAgov-CMS-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/13806?planning-poker) with Zenhub @timcosgrove @edmund-dunn @tonytaylor @teeshe

**Comment by productmike** [comment]
@timcosgrove I know we said two things in refinement: (1) that this work didn't have to be completed by you and (2) we are going to do live planning session for s86. Due to how capacities are playing out, I'd love it if you'd be willing to head this up as a final bow on the translations present :)

Re: #2, my body is forcing me to take a wellness today so live planning will have to wait unfortunately -- which is the force mechanism for this comment now instead of during planning.
