### ISSUE TITLE
Have facility runbooks reviewed by Dave C. 

### ISSUE THREAD

**Issue by kmariepat-cityfriends** [department-of-veterans-affairs/va.gov-cms#13816]
- [ ] Dave and Michelle will go in and adjust facility runbooks after a review and highlight changes to the team

**Comment by jilladams** [comment]
@mmiddaugh @davidconlon there's still one left to do here, right, re: VAMCs? Or this is ready to close?

**Comment by mmiddaugh** [comment]
Remaining runbook is for a new VAMC - which is rare. Dave C suggested we close this and create a placeholder issue to create this runbook when the situation occurs. 

@jilladams @xiongjaneg should we remove the [existing runbook-vamc-facility-new](https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/.github/ISSUE_TEMPLATE/runbook-vamc-facility-new.md) or remove the details with a note that we will return when the situation occurs?

**Comment by mmiddaugh** [comment]
Create new runbook for New VAMC facility #15264
Create a new runbook for New Vet Center #15265

**Comment by jilladams** [comment]
Sounds like this can close, @mmiddaugh ? Closing, but feel free to reopen, if needed.
