### ISSUE TITLE
Cerner / KISS knowledge transfer

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#13823]
## Description
In light of Ryan's upcoming transition to AP, we need to knowledge transfer Cerner info to Randi / Max / Daniel. 
Can work with Jill & @wesrowe  to cover business logic side.

Topics to cover: 
* How Cerner data works today
* Turning off old Cerner data
* KISS
* Next steps for KISS in an ideal world

## Acceptance Criteria
- [x] Documentation is created somewhere
- [x] Topic Dive or similar is scheduled

**Comment by ryguyk** [comment]
WIP

**Comment by ryguyk** [comment]
Topic Dive scheduled for 6/12/2023.
