### ISSUE TITLE
Deprecate `injected_header_web_components` after web components in injected headers launch

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#13825]
## Description
re: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11313
`injected_header_web_components`

Note: flippers will still appear in the Flipper UI bc the pruning job doesn't run. 

## Acceptance Criteria
- [ ] injected_header_web_components is removed from use and from vets-api

**Comment by FranECross** [comment]
@randimays @jilladams would it make sense to close this ticket as obsolete, in light of all the changes being made to header/footer, and the possibility of the injected header/footer being turned into a flat HTML? Thanks!

**Comment by randimays** [comment]
@FranECross I think so. As far as I know, it is impossible to use web components in the injected header. Many teams have tried.

**Comment by FranECross** [comment]
Closing as will not do.
