### ISSUE TITLE
URL Change for: Wenatchee VA Clinic -> Elwood “Bud” Link Department of Veterans Affairs Outpatient Clinic

### ISSUE THREAD

**Issue by stefaniefgray** [department-of-veterans-affairs/va.gov-cms#13829]
### Implementation date
When does this request need to be live:
Once original name change ticket is handled: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13821

^^ See notes at top of this ticket for why this one was re-opened 6/1/23

### Instructions for URL redirect
(Note: This issue will be used from initial request through implementation to ensure all individuals working on this are notified of status updates.  Please do not create multiple issues to track different steps.)
- [x] Notify VA stakeholders as appropriate.
- [x] Link the related facility closure / rename issue.
- [x] Create a URL redirect in the [devops](https://github.com/department-of-veterans-affairs/devops) repo in `ansible/deployment/config/revproxy-vagov/vars/redirects.yml`
- [x] Add the "Awaiting redirect" flag to the facility node with a revision log message that includes a link to this ticket, preserving the node's current moderation state.
- [x] Redirects deploy weekly on Wed. at 10am ET, or by requesting OOB deploy (of the revproxy job to prod) in #vfs-platform-support. After deploy, validate that the URL redirect is deployed. (Note: In the event of a facility closure or a name change,  validate that this occurs before making the Lighthouse csv changes.)
- [x] Update this ticket with a comment that the redirect has been deployed.
- [x] Remove the "Awaiting redirect" flag on the facility node with a revision log message that includes a link to this ticket, preserving the node's current moderation state.
- [x]  Notify helpdesk via comment on ticket or Slack message in #cms-support that changes are ready for review.

#### URL Redirect
| Current URL  |  Redirect Destination or New URL |
| ---  |  --- |
| https://www.va.gov/spokane-health-care/locations/wenatchee-va-clinic | https://www.va.gov/spokane-health-care/locations/elwood-bud-link-department-of-veterans-affairs-outpatient-clinic |

### 1. Canonical URL change 
**Note: Canonical URL changes do not block the completion of the parent ticket. Once the URL redirect above has been deployed, the value to the Veteran is delivered. This ticket should be kept open until the URL change is verified, except in the case of a removal (as described below).**

### Instructions for canonical URL change
- [x] Verify that the new URL for the facility is published and accessible on VA.gov.
- [x] Update the [CSV in Lighthouse](https://github.com/department-of-veterans-affairs/lighthouse-facilities/blob/master/facilities/src/main/resources/websites.csv) with the changed URL, maintaining the sorted order of the Facility API IDs.
- [x] Create a PR in the [lighthouse-facilities repo](https://github.com/department-of-veterans-affairs/lighthouse-facilities), tagging the Lighthouse team.
- [x] Post a message in the #cms-lighthouse channel in Slack, with an @mention to a Lighthouse team member.
- [x] Add the "Awaiting CSV" flag to the facility node with a revision log message that includes a link to this ticket.
- [x] Validate that the change has deployed by checking that the Facility Locator has been updated with the new url.
- [x] Update this ticket with a comment that the CSV change has been deployed.
- [x] Remove the "Awaiting CSV" flag to the facility node with a revision log message that includes a link to this ticket.

#### URL change example (update with actual ID and URL)
| Facility API ID  |  Full VA.gov URL |
| ---  |  --- |
| vha_668GA | https://www.va.gov/spokane-health-care/locations/elwood-bud-link-department-of-veterans-affairs-outpatient-clinic/ |

**Comment by stefaniefgray** [comment]
CLOSING

Clinic should actually remain Fort Belvoir per https://va-gov.atlassian.net/browse/VAHELP-5856

**Comment by stefaniefgray** [comment]
Re-opening!

See notes at top of https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13821 for why

**Comment by omahane** [comment]
The redirect has been deployed. I'm now going to update the CMS.

**Comment by stefaniefgray** [comment]
Not working yet

**Comment by jilladams** [comment]
Sorry if I'm flapping at standard procedure - just working on sprint report and came across this: This redirect is working, but https://www.va.gov/spokane-health-care/locations/elwood-bud-link-department-of-veterans-affairs-outpatient-clinic is 404ing. Are we sure that's the right destination? Or: we already knew that and that's what "not working yet" means, bc they haven't published a thing that will eventually publish?

Is it ok we're redirected to a 404 link meantime?

**Comment by omahane** [comment]
@jilladams The problem is that the name in the act of Congress and the name in the Facilities API are different (by one character):
Elwood "Bud" Link Department of Veterans Affairs Outpatient Clinic (actual name)
vs
Elwood "Bud" Link Department of Veteran Affairs Outpatient Clinic (name in API)

"Veterans" accidentally became "Veteran" in the translation.

The URL in the redirect is right, but the name as it's come into the CMS is wrong because the API is wrong.

I have reached out to Lighthouse about getting this corrected: https://dsva.slack.com/archives/C02BTJTDFTN/p1688133080517459

**Comment by stefaniefgray** [comment]
From Slack thread earlier today, 7/3/23: "The VAST team got back with us on this and confirmed the facility name was misspelled. They've processed a correction, we should get the update from them overnight, and it should persist in our API tomorrow."

**Comment by omahane** [comment]
The name has changed. I have resaved it with a new menu name and path alias. It should propagate to the front-end in the next hour (or less). When it has, I'll confirm that our redirect is working correctly.

**Comment by stefaniefgray** [comment]
Facility Locator still directs to Wenatchee CMS link as of 7/25/23

**Comment by omahane** [comment]
The CSV has been deployed. (CC: @stefaniefgray @jilladams )

**Comment by stefaniefgray** [comment]
Looks good, notified editor in https://va-gov.atlassian.net/browse/VAHELP-6189

Closing!
