### ISSUE TITLE
Discovery: Need to audit for published VAMC facilities that lack any published Facility Health Services

### ISSUE THREAD

**Issue by stefaniefgray** [department-of-veterans-affairs/va.gov-cms#13832]
## Description
If a facility homepage doesn't have any VAMC Facility Health Services added, this presents a patient safety issue. 

Without any linked published health service nodes, Veterans will not be able to find out what sort of care they can access at the location.

How can we audit for this? @swirtSJW may have ideas for how to create a View for this

## Acceptance Criteria
- [ ] Can pull ongoing list of published VAMC facilities that lack any associated and published VAMC Facility Health Service nodes

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [ ] `Public Websites`
- [x] `Facilities`
- [ ] `User support`

**Comment by stefaniefgray** [comment]
@jilladams For visibility -- this would be good info to have

**Comment by stefaniefgray** [comment]
Two examples of published facilities currently lacking linked health services:
- **Gainesville Sixty-Fourth Street 1 VA Clinic:** https://prod.cms.va.gov/north-florida-health-care/locations/gainesville-sixty-fourth-street-1-va-clinic
- **Gainesville Sixty-Fourth Street 3 VA Clinic:** https://prod.cms.va.gov/north-florida-health-care/locations/gainesville-sixty-fourth-street-3-va-clinic

Scroll to "Health Services" at bottom of each page -- empty (as of 5/24/23)

**Comment by jilladams** [comment]
Noted - it's sitting in the right place to get Kamari's attention for upcoming refinements.

**Comment by mmiddaugh** [comment]
There may be valid reasons for a facility to be published without health services. An audit may help to identify these use cases.

**Comment by davidmpickett** [comment]
Resolved via https://github.com/department-of-veterans-affairs/va.gov-cms/issues/7325
