### ISSUE TITLE
Minimize PR overhead for non-code changes.

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-cms#13834]
## Description

As someone who hates that we don't have all of the branch protection rules enabled on `main`,
I should prevent Tugboat deploys and GHA workflow runs on documentation-only PRs
So that people don't look like Walter Donovan in _Indiana Jones and the Last Crusade_ when he drank from the fake Grail while waiting for completely unnecessary test runs to complete.

## Acceptance Criteria
- [ ] Tugboat deploy doesn't happen on documentation-only changes
- [ ] GHA workflows don't happen on documentation-only changes.

**Comment by ndouglas** [comment]
This could turn out to be a major PITA/time sink.

**Comment by JunTaoLuo** [comment]
FYI, `paths-ignore` should be very helpful here: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-excluding-paths.

**Comment by BerniXiongA6** [comment]
@JunTaoLuo how many points of this ticket would you say were completed so far? We can carry over ticket if needed (I can calculate the points manually on my planning calculator). cc: @maortiz-27-80

**Comment by JunTaoLuo** [comment]
I think there's still 5 points left here since I've done about half of the work but the half remaining seems to be trickier.

**Comment by BerniXiongA6** [comment]
Thanks @JunTaoLuo ! cc: @maortiz-27-80
