### ISSUE TITLE
Homepage: News promo not using Drupal's 1:1 image crop

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#13843]
## Description
https://dsva.slack.com/archives/C52CL1PKQ/p1685037593850369

In the Homepage News Promo block, the FE aspect ratio for image is locked to 1:1. In Drupal, users can set the focus area for the crop, and Dave has done that. But the FE isn't showing the specified crop area:

<details><summary>CMS screenshot</summary>

![CMS crop](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/85581471/ed9f92b2-63ee-459d-9282-342530e3665e)

</details>

<details><summary>FE screenshot</summary>

<img width="424" alt="FE crop displayed" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/85581471/f64ed62d-e9c1-49b8-9387-e9f864ad403f">
</details>

## Acceptance Criteria
- [ ] News promo image delivered by graphql uses a 1:1 aspect ratio

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [x] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`

**Comment by dsasser** [comment]
Verified in Prod:

![Screenshot 2023-05-30 at 8 40 34 AM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/221539/6aadf1ae-a642-4dc6-a256-5f47adf08b29)
