### ISSUE TITLE
Composer yaml-tasks command does not have environment set by EnvironmentHandler.php any longer.

### ISSUE THREAD

**Issue by jonpugh** [department-of-veterans-affairs/va.gov-cms#1385]
We setup EnvironmentHandler.php to load the environment variables stored at `.env` automatically.

It used to work for anything that used the autoloader, including composer plugins, etc.

The `composer yaml-tasks` command no longer appears to load the `.env` file. We mitigated this by adding `--github-token` 

I think this is YamlTasks fault. It gets tricky when creating plugins and commands because ConsoleCommand and ComposerCommand are not the same thing.

**Comment by jonpugh** [comment]
Ahh, it seems that bin/yaml tests DOES load the autoloader? the tests use `bin/yaml-tasks` now and that is picking up the github token: http://devshop.cms.va.gov/node/17957

**Comment by ElijahLynn** [comment]
This all seems to work currently, closing.
