### ISSUE TITLE
Add Drush commands for interactively performing GitHub-related tasks.

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-cms#13857]
## Description

We currently have a `GitHubClient` class, but we can't easily use it without engaging the full machinery of Drupal. This is a shame, since the functionality itself is fairly innocuous and otherwise very difficult to test.

We should add some Drush commands so that we can test this adapter interactively, e.g. create repository_dispatch events, list workflow runs, etc.

## Acceptance Criteria

- [ ] Rudimentary Drush commands for the GitHub client exist so that we can introspect and perform operations on GitHub from the command line.

**Comment by ndouglas** [comment]
Closed in favor of #14460.

**Comment by productmike** [comment]
Removing this from s89 due to capacity concerns. @ndouglas has also suggested to replace this ticket with #14460 which I'm good with doing. We can close this ticket if DevSecOps team agrees.
