### ISSUE TITLE
URL Change for: Frank M. Tejeda Department of Veterans Affairs Outpatient Clinic

### ISSUE THREAD

**Issue by stefaniefgray** [department-of-veterans-affairs/va.gov-cms#13864]
### Implementation date
When does this request need to be live:
As soon as possible

### Instructions for URL redirect
(Note: This issue will be used from initial request through implementation to ensure all individuals working on this are notified of status updates.  Please do not create multiple issues to track different steps.)
- [x] Notify VA stakeholders as appropriate.
- [x] Link the related facility closure / rename issue.
- [x] Create a URL redirect in the [devops](https://github.com/department-of-veterans-affairs/devops) repo in `ansible/deployment/config/revproxy-vagov/vars/redirects.yml`
- [x] Add the "Awaiting redirect" flag to the facility node with a revision log message that includes a link to this ticket, preserving the node's current moderation state.
- [x] Redirects deploy weekly on Wed. at 10am ET, or by requesting OOB deploy (of the revproxy job to prod) in #vfs-platform-support. After deploy, validate that the URL redirect is deployed. (Note: In the event of a facility closure or a name change,  validate that this occurs before making the Lighthouse csv changes.)
- [x] Update this ticket with a comment that the redirect has been deployed.
- [x] Remove the "Awaiting redirect" flag on the facility node with a revision log message that includes a link to this ticket, preserving the node's current moderation state.
- [x]  Notify helpdesk via comment on ticket or Slack message in #cms-support that changes are ready for review.

#### URL Redirect
| Current URL  |  Redirect Destination or New URL |
| ---  |  --- |
| https://www.va.gov/south-texas-health-care/locations/frank-m-tejeda-department-of-veterans-affairs-outpatient-clinic/ | https://www.va.gov/south-texas-health-care/locations/ |

#### URL change example (update with actual ID and URL)
| Facility API ID  |  Full VA.gov URL |
| ---  |  --- |
| vha_671BY | https://www.va.gov/south-texas-health-care/locations/ |

### Instructions for canonical URL removal
- [x] Try to find the facility via the Facility Locator, using the Facility API ID (e.g. https://va.gov/find-locations/facility/"facility_api_id"). If it is not available, proceed.
- [x] Update the [CSV in Lighthouse](https://github.com/department-of-veterans-affairs/lighthouse-facilities/blob/master/facilities/src/main/resources/websites.csv) removing the row with the Facility API ID.
- [x] Create a PR in the [lighthouse-facilities repo](https://github.com/department-of-veterans-affairs/lighthouse-facilities), tagging the Lighthouse team.
- [x] Post a message in the #cms-lighthouse channel in Slack, with an @mention to a Lighthouse team member.
**Note: there's no check to see if it's not returning anything, as it should already be not showing anything in the Facility Locator.**

#### URL removal example (update with actual ID and URL to remove)
| Facility API ID  |  Full VA.gov URL |
| ---  |  --- |
| vha_671BY | https://www.va.gov/south-texas-health-care/locations/frank-m-tejeda-department-of-veterans-affairs-outpatient-clinic/ |

**Comment by stefaniefgray** [comment]
Editor in VAHELP-5871: "I hope y’all had a wonderful weekend! This location is already fully archived on our end. Please move forward with fully archiving this location from VA.gov."

**Comment by stefaniefgray** [comment]
@jilladams @kmariepat-cityfriends Quick win for next sprint?

**Comment by omahane** [comment]
The redirect has been deployed.

**Comment by omahane** [comment]
@TroyA6 @stefaniefgray The CSV change has been added to PR. There's no more work to be done except stakeholder confirmation.

**Comment by omahane** [comment]
@kmariepat-cityfriends This ticket can be closed.

**Comment by stefaniefgray** [comment]
Confirmed complete! Closing
