### ISSUE TITLE
Review of new or updated KB article : How to update Basic Location Data for VA Medical Centers and Clinics

### ISSUE THREAD

**Issue by TroyA6** [department-of-veterans-affairs/va.gov-cms#13875]
## Which article(s) need review?
Provide the link to latest revision of each article that requires review.
- [Article](https://prod.cms.va.gov/node/35570/latest)

  
## Priority or deadline for request
Choose either Deadline or a priority:

- [ ] Deadline: [name the deadline here]
- [ ] Priority:
  - [ ] Critical
  - [ ] High
  - [x] Medium
  - [ ] Low

## Associated KB article ticket
Provide the original ticket where the article was originally created/updated so we can refer back there for any additional context if necessary.
- [Github ticket](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13874)
  
## Can article(s) be published?
Once the article has been fully reviewed, can the article(s) be published? For example, is anything tied directly to an upcoming feature and this information should not be published until the feature is on production?
- [x] Yes, all article(s)s within this ticket can be published once reviewed
- [ ] No, the article(s) within this ticket should not be published and should only be reviewed
  
## Notify the CMS team of this ticket in the cms-support Slack channel.
- [x] I acknowledge that I must notify #cms-support after submitting this issue.

## Acceptance Criteria
- [ ] Article reviewed by CMS Team
- [ ] Article reviewed by Help desk
- [ ] If approved above, article is published
- [ ] Requesting person/team has been notified that article was reviewed/published

**Comment by laflannery** [comment]
I have reviewed - my only comment is this line under the "How to update Basic Location Data for VA Medical Centers and Clinics" heading:

> If the table below shows that your request should be addressed to VAST

and if it should this be:

- "... addressed by VAST"
- "...addressed in VAST"
- “...addressed by the VAST team”

Or some other option we didn't think of

**Comment by xiongjaneg** [comment]
closing, this has been updated with specific updates as they've occured
