### ISSUE TITLE
Omit unpublished authors from news release pages

### ISSUE THREAD

**Issue by mpelzsherman** [department-of-veterans-affairs/va.gov-cms#13885]
Some news release pages have unpublished authors. e.g. https://www.va.gov/pittsburgh-health-care/stories/new-program-empowers-community-providers/

We should omit the author when this is the case.

![__New_Program_Empowers_Community_Providers___Veterans_Affairs.png](https://images.zenhubusercontent.com/5ee91ea93ee2bbe222cd827f/4f529333-18ce-4972-b273-e24a691ece09)

**Comment by mmiddaugh** [comment]
This [New Jersey health care news release](https://www.va.gov/new-jersey-health-care/news-releases/va-launches-national-pact-act-summer-vetfest-to-encourage-veterans-and-survivors-to-apply-for-new-health-care/) does not feature the author - closing this as resolved.
