### ISSUE TITLE
VAMC System health service accordions should link directly to corresponding VAMC Facility health service accordions

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-cms#13910]
## Issue Description
Navigation for VAMC health services at the facility level is different than at the system level and may prove confusing for Veterans. 

## Current behavior
[Health services](https://www.va.gov/pittsburgh-health-care/health-services/) system-level page has "On this page" jump links.  
When a Veteran selects "Mental health care", s(he) is taken to that section on the page and can explore the accordions. Once a facility where a particular service is offered has been clicked, the experience changes. This can increase cognitive load for the Veteran in several ways:
- The Veteran is dropped on the facility home page, rather than into/at the specific accordion from which s(he) navigated from the system page so Veteran needs to remember which accordion (s)he had previously been viewing.
- The system page organized health services by category (ie: Primary care, Mental health care, etc.) while they are all listed under **Health services offered here**  at the facility level
- Some services are both a category and a service in themselves (ie: Mental health). 
- The list of health services can be quite lengthy and may benefit from an A-Z navigation, particularly on the mobile experience, 

https://www.loom.com/share/1d3509c90cc3440bb4cc62b239ef141b

How might we reduce cognitive load and make it easier for Veterans to connect with care more quickly? 
(Can we leverage deep links from system accordions to the matching facility accordion?)

Also reported by PAO: [VAHELP-7007](https://va-gov.atlassian.net/jira/servicedesk/projects/VAHELP/queues/issue/VAHELP-7007)

[VAHELP-7007]: https://va-gov.atlassian.net/browse/VAHELP-7007?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

## Expected behavior
It is expected that Veterans will prefer to be taken to
- the relevant service area of the main page for the chosen facility.

## ACs
- [x] Within a VAMC System Health Service accordion on the [Health Services page](https://www.va.gov/pittsburgh-health-care/health-services/), the links to Facilities under **Available at these locations** should use anchor links to the corresponding service accordion at that Facility, e.g. https://www.va.gov/pittsburgh-health-care/locations/beaver-county-va-clinic/#mental-health-care
- [x] Only Facilities that have a published local version of that service should appear on the System Health service accordion. (Currently true in Prod, don't regress it.)
- [ ] ~If no Facilities offer that service... (should the System service even show?)~ - covered in https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17165. It would be smart to schedule that at the same time as this ticket.
- [x] Update VHA DM sync card to make VHA DM aware of the change: 
  - [ ] https://trello.com/c/ve9QID5M/154-sioux-falls-feedback-on-services-phone-numbers-deep-links-from-system-service-to-facility-service-13910
  - [ ] https://trello.com/c/rXhzTuVM/172-blinded-and-low-vision-rehab-health-service-accordion-links-deep-links-13910

**Comment by mmiddaugh** [comment]
@xiongjaneg this relates to a recent VHA DM topic: https://trello.com/c/ve9QID5M
time permitting, it might be a good one to discuss at refinement

**Comment by xiongjaneg** [comment]
@mmiddaugh We already discussed Front end prerefinement focusing on Design System upcoming changes. Where does this rank in priority?

**Comment by davidmpickett** [comment]
> It is expected that Veterans will prefer to be taken to
> 
> - the specialty page for the chosen facility (where available) or

Do we have specialty pages per **facility**? I know we have specialty pages per **system** (e.g. [Mental health care at Pittsburgh](https://www.va.gov/pittsburgh-health-care/health-services/mental-health-care/))


> - the relevant service area of the main page for the chosen facility.

This should be doable via anchor links:

https://www.va.gov/pittsburgh-health-care/locations/h-john-heinz-iii-department-of-veterans-affairs-medical-center/#mental-health-care

**Comment by davidmpickett** [comment]
@mmiddaugh In order to clean up the ticket body for implementation, I am moving your original expeceted behavior bullet and explanation of why we're not pursuing it to a comment

> It is expected that Veterans will prefer to be taken to
> - the specialty page for the chosen facility (where available) **_or_** 
> 
> **As specialty pages are not universally available for all services and as anchor links should allow us to easily improve usability, let's focus on navigation from the system health service accordion to the facility health service accordion.** 
> (Noting that any specialty page or related required health service detail page can be accessed via the link within the accordion)

**Comment by jilladams** [comment]
From refinement: 
* Example link for where we want Veterans to land: https://www.va.gov/pittsburgh-health-care/locations/beaver-county-va-clinic/#mental-health-care
* Building this URL from the system page: the name of the service derives from the Taxonomy. The System template will need to access that via GraphQL query to build the URL with ID for the service. This might add some complexity.

Max says: 2.

**Comment by jilladams** [comment]
@Agile6MSkinner @eselkin I feel like we pulled this in as stretch based on a live discussion, but it's not correlated to VBA, and is tech debt, so I just wanna make sure this is the right next thing to be doing if it was grabbed before the Ready column was prioritized. Can either of you confirm that?

**Comment by Agile6MSkinner** [comment]
I'm not familiar with this ticket, and I agree. It doesn't seem like the highest priority to me. If it was at the top of the "ready" column, that's on me. It should be prioritized by EOD today.

**Comment by eselkin** [comment]
I think I accidentally pulled it in

**Comment by jilladams** [comment]
Verified accordion system link points to vamc accordion on 
https://www.va.gov/minneapolis-health-care/health-services/
and https://www.va.gov/pittsburgh-health-care/health-services/

Spot checked and validated that these links only occur on those 2 systems and on https://www.va.gov/sioux-falls-health-care/health-services/ that links only appear if VAMCs offer those services.

Closing!
