### ISSUE TITLE
Some functions got de-namespaced related to va_gov_post_api

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#13916]
## Describe the defect
When trying to do a force push of faciity data the function ir calls is to the old namespacing of the module.  It generates the error 

```
Error: Call to undefined function Drupal\va_gov_post_api\Form\_post_api_add_facility_status_to_queue() in Drupal\va_gov_post_api\Form\VaGovFacilityForceQueueForm->submitForm() (line 149 of /var/www/cms/docroot/modules/custom/va_gov_post_api/src/Form/VaGovFacilityForceQueueForm.php) #0 [internal function]:
```

We nee d to make sure the call to that function is using the correctly namespaced version of that function.

This is currently blocking us from doing andy force push of facilities.
## Additional context
Add any other context about the problem here. Reach out to the Product Managers to determine if it should be escalated as critical (prevents users from accomplishing their work with no known workaround and needs to be addressed within 2 business days).

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Defect")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS workstream (orange) (not needed for bug tickets)
- [ ] CMS-supported product (black)

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [ ] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`

**Comment by kmariepat-cityfriends** [comment]
Closing, no longer needed due to work on: Force queue of VetCenter Facilities does not include all Outstations, mobiles or CAPS #13768
