### ISSUE TITLE
[CONSIDER] Pass params for home health and telehealth as "false" 

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-cms#13921]
## Issue Description
PPMS telehealth and home health parameters default to "on".  Since we are not sure how to display them in a meaningful way to Veterans, we decided to hard code them as "off" (#31520) 
If we want to use them, we'll need to pass the params as false. 

## Tasks
- [ ] TBD 

## Acceptance Criteria

**Comment by jilladams** [comment]
This is light on details, not an active effort, and lingering in an old epic that doesn't need to migrate to Github projects. Closing and we can recreate as needed later on when we properly wrangle telehealth related things.
