### ISSUE TITLE
508-defect-4: Avoid mouse-centric instructions

### ISSUE THREAD

**Issue by joshkimux** [department-of-veterans-affairs/va.gov-cms#13937]
## Description

On VAMC Facility pages ([example](https://www.va.gov/boston-health-care/locations/framingham-va-clinic/)) and Vet center pages ([example](https://www.va.gov/boston-vet-center/)) We currently have text before each accordion group that uses the word "Click". Not all users will be able to "click" on accordions to open them. To be more inclusive, we should update this language for all accordion sections to align with the approved language we are using on VBA "Select a topic to learn more."

## Acceptance Criteria

- [x] Language in Prepare for your visit accordion section on VAMC Facility pages has been updated to "Select a topic to learn more."
- [x] Language in Health services accordion section on VAMC Facility pages has been updated to "Select a topic to learn more."
- [x] Language in Prepare for your visit accordion section on Vet Center pages has been updated to "Select a topic to learn more."
- [x] Language in all services accordion sections on Vet Center pages has been updated to "Select a topic to learn more."

## Screenshots

![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/167716994/ea5e7256-fed4-43ff-87e8-ef581c73e69e)

**Comment by jilladams** [comment]
This is in the wrong Facilities accessibility epic, and I need to find the right one to move it to.

**Comment by laflannery** [comment]
@jilladams This is related to content on the "Prepare for your visit" section on VAMC locations pages. Do you have an epic related to that?

**Comment by laflannery** [comment]
Also, I'm going to propose we change this text to align with the new VBA designs and use "Select a topic to learn more."
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/106678594/e8a9efa1-d622-42fc-8c56-447c927dedcf)

**Comment by jilladams** [comment]
@laflannery we've got an epic for everrryyythingnggg -> https://github.com/department-of-veterans-affairs/va.gov-cms/issues/8325. Adding.

**Comment by eselkin** [comment]
Not one of the ACs but in the `src/site/includes/health_services_listing_services.liquid` we don't have anything below the h2.
like: 
<img width="1472" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN3ZsQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6ec21d9e4f8e87d425650b42c2b393c087927eee/Screenshot%202024-07-16%20at%202.54.33%E2%80%AFPM.png" alt="Screenshot 2024-07-16 at 2.54.33 PM.png" />

Should we add the text to this one too? @laflannery

**Comment by eselkin** [comment]
Discovery: The "How we’re different than a clinic" section text "Click on a topic for more details." is defined in drupal.

**Comment by Agile6MSkinner** [comment]
@eselkin Does that mean a drupal engineer needs to be tagged in?

**Comment by eselkin** [comment]
@Agile6MSkinner Nope, just a content change

**Comment by Agile6MSkinner** [comment]
@davidmpickett regarding @eselkin's discovery note, who would make those content changes?

**Comment by davidmpickett** [comment]
@Agile6MSkinner This is controlled for the [Vet Center centralized content](https://prod.cms.va.gov/centralized-content/national-vet-center-content) node. I went ahead and made this change since it is straightforward and well-documented.

Typically edited by @mmiddaugh or Vet Center national stakeholders

**Comment by laflannery** [comment]
@eselkin The one you asked me about that currently has no text is for VBA and is covered in [this other ticket](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17601) I believe?

**Comment by davidmpickett** [comment]
Vet Center FAQ change live on Prod ![Screenshot 2024-07-17 at 11 14 54 AM](https://github.com/user-attachments/assets/d472ea3b-44b0-4554-96a5-b14ce8a88c68)

**Comment by eselkin** [comment]
@laflannery Sorry, I missed your response. No, the one that has no text is on health services pages for VAMC systems (not the facility)
e.g. https://www.va.gov/northeast-ohio-health-care/health-services/

**Comment by laflannery** [comment]
O! I see, I don't think we new about this, yes if it's not going to increase the scope of this too much, could you also include the same text here on the VAMCs that you found as well, that would be great @eselkin Thanks!

**Comment by eselkin** [comment]
It doesn't increase the scope much.

**Comment by jilladams** [comment]
@Agile6MSkinner to help verify / close

**Comment by jilladams** [comment]
@Agile6MSkinner were you able to verify this one? If not, now that @laflannery is back, maybe you could help do that?

**Comment by eselkin** [comment]
Both example links from description show with the "Select a topic to learn more" beneath the title of the accordion in all accordion sections.
