### ISSUE TITLE
Redirect: PACT Act vanity url variations

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#13947]
## Description
https://dsva.slack.com/archives/C52CL1PKQ/p1685556037263849

We need to have redirects for
/PACTACT
/PACTAct
/PACTact
/pactact
All redirecting to
https://www.va.gov/resources/the-pact-act-and-your-va-benefits/
Note: this could/should be grouped with the existing Vanity redirect for /PACT
### User story

**AS A** Veteran
**I WANT** variations of the pact-act vanity URL to redirect to the PACT page
**SO THAT** marketing materials don't 404.

## Acceptance criteria

>Consider
> - Design / Accessibility reviews
> - Collab cycle requirements
> - Device sizes (mobile first)
> - Documentation updates / Change management
< - [Content model documentation](https://prod.cms.va.gov/admin/structure/cm_document)
> - Testing notes

- [ ]

**Comment by jilladams** [comment]
Deployed: https://dsva.slack.com/archives/CBU0KDSB1/p1685558140475059

Verified in prod, closing.
