### ISSUE TITLE
Change management for removing italics in CKEditor 5

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#13959]
## Description
When we update to D10 and CKEditor 5, italics will no longer be available in the CKEditor. Also, all text that has currently been styled using italics will automatically be reverted to standard text. Erika has said that we might want to have a small amount of change management around this update when it happens.

### Notes
- Use [Change management template](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/new?assignees=&labels=Needs+refining&projects=&template=change-management-epic.md&title=Change+management+for+%3Cinsert+issue+name%3E) to create plan but scaled back
- Need to determine where would this will live forever. Perhaps there will be an interim place until Platform Confluence is finalized
- Should we discuss with Content team about improving/changing content style guidance for how to create emphasis in content without italics going forward?
  - Since the guidelines currently say that italics should not be used but don't indicate an alternative for providing emphasis, this wouldn't necessarily be a launch-blocker but more an enhancement.

## Acceptance Criteria
- [x] Create change management plan for editors
- [x] PO/PM feedback and/or approval
- [x] Provide notification and awareness to Helpdesk

### Team
Please check the team(s) that will do this work.

- [x] `CMS Team`
- [ ] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`

**Comment by laflannery** [comment]
## Proposed change management plan

1. Editors will no longer be able to style their text using italics.
2. Any text in a rich text editor that had previously been italicized will be reverted back to the standard text format.

Italics should not be used for text styling as this is not in accordance with the VA Design guidelines. Italics text also often creates a more inaccessible experience for users and should be avoided whenever possible.

This will impact all CMS Editors.

This change adheres to VA policies and standards because, as mentioned previously, it is assisting editors in making sure the content they create is more inline with the VA Design guidelines. No Helpdesk support or updates to training materials is needed for this change, only awareness that this change as taken place and way so that if questions do come up, the Helpdesk team is able to respond.

This change will not be tested with users prior to launch.

This change will occur at the same time that the update to D10 and CKEditor 5 occurs.

**Comment by EWashb** [comment]
Thanks for this one too, @laflannery. I know we mentioned no changes to KB articles needed, but are we sure that there are no KB images of the editor that we need to update?

It may be helpful as we plan the actual launch of Drupal10 that we give some update during regular syncs with stakeholders that "D10 is coming. Please be aware of any visual changes (?). You will also notice that there are changes to with our text editor."

Tbh I am still unsure if there are obvious visual changes to D10, but it may be worth at least bringing up this one (and others if so) to our stakeholders like Blake & Justin at VHA DM, Jessica at VC, etc.

**Comment by EWashb** [comment]
@laflannery let's let @mmiddaugh know FYSA (which I just did by tagging) in case she'd like to bring it to Jessica at Vet Centers.

**Comment by laflannery** [comment]
Note: After meeting with Erika, we decided that we will update any screenshots in KBs after launch

**Comment by laflannery** [comment]
We documented the change in [Github here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/product-outlines/ckeditor/README.md)
