### ISSUE TITLE
Improve Editorial Experience for VAMCs 

### ISSUE THREAD

**Issue by kmariepat-cityfriends** [department-of-veterans-affairs/va.gov-cms#13962]
- More action based rather than trying to navigate different content types 
- More specific titles for content types 
- How do we leverage the editorial interface to encourage good habits 
- Should we be considering a button `View your site's performance" / "View your analytics"
- How do you measure the outcomes you are trying to achieve and what are those outcomes

**Comment by jilladams** [comment]
Closing as dupe of #5413
