### ISSUE TITLE
I.L. BE: Add Zip validation endpoint

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#13968]
### User story

**AS A** Veteran
**I WANT** to get instant feedback on the Zip screen in the case where I entered a zip that doesn't exist in our database
**SO THAT** I can fix it with minimal cognitive load.

## Acceptance criteria

- [ ] Endpoint requires only a zip code in the request
- [ ] Endpoint returns a success or failure response indicating whether the requested zip code is present in the IL database – both cases are 200, set `valid` to true or false
- [ ] Has sufficient test coverage
  - [ ] controller test
  - [ ] request test (integration)
- [ ] Updated documentation
- [ ] Added Swagger docs to repo (but blocked from being published to vets-api consumers; dev's choice on method) and updated with this new endpoint

**Comment by jilladams** [comment]
@jtmst here as well, much obliged for any status update for progress so far in sprint (since fixing #14059 )
