### ISSUE TITLE
VBA Product Brief Review + VBA Editor Role Research Review 

### ISSUE THREAD

**Issue by kmariepat-cityfriends** [department-of-veterans-affairs/va.gov-cms#13966]
https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/facilities/regional-offices

- Review defined business outcomes
- Create associated KPIs
- Write Problem statements
- Looking at the product outline what other high level information buckets would you like us to have? Messaging is we are starting from first principles 

---
- Answer "where are we limited by using on one workflow for VBA editor roles and permission..."
- Kamari to review existing use cases 

- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12911#issuecomment-1541267890
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13783
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11334
- [ ] slack thread 

- address content types vs. permissions vs. workflows 

## Acceptance criteria

- [ ] Review proposal with @mmiddaugh prior to scheduling CMS Collab Cycle touchpoint
- [ ] Schedule CMS Collab cycle touchpoint

**Comment by kmariepat-cityfriends** [comment]
synthesis to be reviewed with @mmiddaugh in product sync

**Comment by jilladams** [comment]
Distilled Kamari doc: https://docs.google.com/document/d/19mZHD2VqIaytmDzgx-2Wgz3_8lonPIbZN5ncXRD2mig/edit
