### ISSUE TITLE
I.L. FE: Leverage API for zip code validation on Zip screen

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#13969]
### User story

**AS A** Veteran
**I WANT** to get instant feedback on the Zip screen in the case where I entered a zip that doesn't exist in our database
**SO THAT** I can fix it with minimal cognitive load.

## Acceptance criteria

- [x] When the user clicks Continue on the Zip screen, the front-end app confirms the zip code's existence in the BE before advancing the use to the next screen
- [x] If the zip doesn't exist, the user is kept on the Zip screen and notified with a message "Please enter a valid 5 digit zip code." 
- [x] Test cases added
- [x] Requires design review

**Comment by thejordanwood** [comment]
Zip code error message should read, "Please enter a valid 5 digit zip code." This is similar to the error message for the SSN field when [applying for VA health care](https://www.va.gov/health-care/apply/application/id-form). 

![zip code error](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/104526584/17e9de13-a0ef-4885-8530-d361d60a0bb2)

**Comment by wesrowe** [comment]
I responded to @randimays's [Slack post seeking review](https://dsva.slack.com/archives/C52CL1PKQ/p1688062467215189) with a question, I'll repeat it here: when the API recovers, will the app be ready to Continue?

Otherwise looks good and can close.

**Comment by randimays** [comment]
Follow up on the Slack post seeking review above, here was my reply:
> It's hard to simulate that in a local build. Making code changes requires a rebuild and you have to reload the page for them to reflect. Out in the wild (in prod), it would behave differently. As soon as the API is up again, you could simply click again on the CTA and it would hit the working endpoint.

Also asked Jordan and Laura to have a look. Jordan approved, and Laura asked if all the components we used for errors are DST components (they are). She said she would get back to me if she found any accessibility issues, but they'd likely be on the Platform side to fix, so nothing we could really do at this point.

**Comment by wesrowe** [comment]
Thanks! Close when ready.

**Comment by randimays** [comment]
Loom walkthrough: https://www.loom.com/share/7f41009cd1ee4256afe2143910a007d7?sid=0e9bba16-9159-45a2-bf11-0d95c2a03828
