### ISSUE TITLE
URL Change for: Corpus Christi VA Mobile Clinic [Ready to go]

### ISSUE THREAD

**Issue by stefaniefgray** [department-of-veterans-affairs/va.gov-cms#13979]
⚠️  NO URL RE-DIRECT NEEDED ⚠️ 

Simply needs to be updated within Lighthouse CSV / canonical URL change

-----

### Implementation date
When does this request need to be live:
Once the original new facility ticket is completed: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13978

### Instructions for canonical URL change
- [x] Verify that the new URL for the facility is published and accessible on VA.gov.
- [x] Update the [CSV in Lighthouse](https://github.com/department-of-veterans-affairs/lighthouse-facilities/blob/master/facilities/src/main/resources/websites.csv) with the changed URL, maintaining the sorted order of the Facility API IDs.
- [x] Create a PR in the [lighthouse-facilities repo](https://github.com/department-of-veterans-affairs/lighthouse-facilities), tagging the Lighthouse team.
- [x] Post a message in the #cms-lighthouse channel in Slack, with an @mention to a Lighthouse team member.
- [x] Add the "Awaiting CSV" flag to the facility node with a revision log message that includes a link to this ticket.
- [x] Validate that the change has deployed by checking that the Facility Locator has been updated with the new url.
- [x] Update this ticket with a comment that the CSV change has been deployed.
- [x] Remove the "Awaiting CSV" flag to the facility node with a revision log message that includes a link to this ticket.

#### URL change example (update with actual ID and URL)
| Facility API ID  |  Full VA.gov URL |
| ---  |  --- |
| vha_740QC | https://www.va.gov/texas-valley-health-care/locations/corpus-christi-va-mobile-clinic |

**Comment by stefaniefgray** [comment]
@omahane Is this how URL change tickets ought to look?

**Comment by stefaniefgray** [comment]
@jilladams @xiongjaneg @omahane Also ready for the upcoming sprint

**Comment by omahane** [comment]
The CSV redirect has been requested. https://dsva.slack.com/archives/C02BTJTDFTN/p1692382064254419

**Comment by stefaniefgray** [comment]
Still awaiting CSV update

**Comment by omahane** [comment]
The CSV has been deployed.
