### ISSUE TITLE
Send broken link numbers data to Datadog

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#13975]
## Description
As a CMS user support team member, I would like to be able to see the number of broken links per content release over time, so that I can identify trends in broken links and my team's impact on them.

Slack discussion: https://dsva.slack.com/archives/C03LFSPGV16/p1685650253253909

## Acceptance Criteria
- [x] Number of broken links detected in a content release is sent to Datadog with other content release information.
- [ ] A simple dashboard is set up visualizing the data.

### Team
Please check the team(s) that will do this work.

- [x] `CMS Team`
- [ ] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`

**Comment by teeshe** [comment]
I have updated [script/github-actions/check-broken-links.js](https://github.com/department-of-veterans-affairs/content-build/blob/VACMS-13975/script/github-actions/check-broken-links.js) in content-build repository to send the number of broken-links-count to content-release workflow, also added a step that sets this output as an environment variable "[.github/workflows/content-release.yml](https://github.com/department-of-veterans-affairs/content-build/blob/VACMS-13975/.github/workflows/content-release.yml)",  I update the Build JSON object that creates content-build metrics for Datadog to include Broken links count.

**Comment by BerniXiongA6** [comment]
@ariperez If you could work this in S100 -- this might be the Sprint goal for S100.

**Comment by BerniXiongA6** [comment]
Hey @ndouglas @maortiz-27-80 -- what do you want to do with this ticket? It seems to be mostly done and just needs finishing touches I believe.

**Comment by ndouglas** [comment]
@BerniXiongA6 @maortiz-27-80 I opened a PR with Tolase's changes. I don't think it needs anything but a review and merge. All looks great to me 🙂

**Comment by ndouglas** [comment]
Tanner approved and I merged the PR in question.  We should see fairly soon if it works.  If so, I can add a widget to our dashboard and close this ticket.

**Comment by ndouglas** [comment]
I added the widget, but our numbers have been consistently zero for the past few days. I'd like to close this ticket but due to the nature of the scripts and system in question, this is difficult to verify. It's possible this will need to be tweaked a bit this coming sprint.
