### ISSUE TITLE
Sterling VA Clinic is duplicated on VA Cheyenne VAMC Facility Health Service dropdown menu

### ISSUE THREAD

**Issue by stefaniefgray** [department-of-veterans-affairs/va.gov-cms#13980]
## Describe the defect
As an editor updating a VA Cheyenne VAMC Facility Health Service node, I should not see the Sterling VA Clinic listed twice.

## To Reproduce
1. Go to a VAMC Facility Health Service node such as Social Work ( https://prod.cms.va.gov/cheyenne-health-care/locations/sterling-va-clinic-0/social-work ) 
2. Go to the "Health service and facility basic info" section and click the "Facility" dropdown menu
3. You will see two Sterling VA Clinics listed, as shown in the screenshot.

## AC / Expected behavior

- [x] Only the published Sterling VA Clinic facility should be an option when creating VAMC Facility Health Services, with the URL `/sterling-va-clinic`: https://prod.cms.va.gov/cheyenne-health-care/locations/sterling-va-clinic
- [x] The archived Sterling VA Clinic with the URL` /sterling-va-clinic-0` should not appear within this menu: https://prod.cms.va.gov/cheyenne-health-care/locations/sterling-va-clinic-0
- [x] validate there is no migration cause

## Screenshots
<img width="768" alt="Screen Shot 2023-06-01 at 10 32 00 PM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/9059428/064a9864-4fdd-46e4-8efc-492a6a0a2a6a">

 ## Additional context
The Sterling VA Clinic facility node was duplicated within the CMS due to a new Facility Locator ID and had to be swapped out -- see https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13203

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Defect")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS workstream (orange) (not needed for bug tickets)
- [ ] CMS-supported product (black)

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [ ] `Public Websites`
- [x] `Facilities`
- [ ] `User support`

**Comment by stefaniefgray** [comment]
cc: @omahane -- We might need to add this to the Facility Locator swap-out runbook

**Comment by stefaniefgray** [comment]
cc: @davidmpickett ^^

**Comment by stefaniefgray** [comment]
Original Jira ticket -- can follow up once complete: https://va-gov.atlassian.net/browse/VAHELP-5798

**Comment by stefaniefgray** [comment]
cc: @davidmpickett, discussed during today's Helpdesk/UX check-in and I learned the definition of "winnowing"

**Comment by jilladams** [comment]
From scrum: we think this list is built from a view that includes archived facilities. It shouldn't include archived. Is this view used in other places and do those places care about displaying archived facilities? Christian to double check.

**Comment by stefaniefgray** [comment]
Confirmed fixed on prod!
