### ISSUE TITLE
Custom urls for media (especially PDFs and documents)

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#1398]
## User Story or Problem Statement

As a document editor, i want to specify the alias. 

As an information architect, i want some governance over the way URL aliases for media files are managed, so that people have guardrails and guidelines for how to create them. 

## Background

* The public websites team manages pdfs with custom URLs in [vagov-content](https://github.com/department-of-veterans-affairs/vagov-content). but they would like to retire that repo.
* [Slack thread from April 3 2020 looking for this feature](https://dsva.slack.com/archives/C52CL1PKQ/p1585938477468100)
* [Old jira ticket](https://va-gov.atlassian.net/browse/VAGOV-6196) 

## Acceptance Criteria
* A content_admin can create a custom URL alias for a pdf without any restrictions

Possibly
* VAMC content editor can create a custom URL alias with X restrictions (eg must start with /pittsburgh-health-care, or something). 

## Implementation steps
* Possibly https://www.drupal.org/project/url_alias_permissions module, but that may be node-specific

**Comment by FranECross** [comment]
Ancient ticket; closing as a no op.
