### ISSUE TITLE
BE: Support Drupal 10 testing/bug bash

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#13990]
### Engineering notes / background
Tugboat: https://vacms-12252-drupal-10-kaaijt1fsqp1qasl6a8metonglihfa26.ci.cms.va.gov/ 

### Quality / testing notes

Test env: Tugboat

Risk factors for D10:
- Dependence on a module with deprecated php syntax - e.g., contrib or custom modules
- D9-deprecated code

Products to manually test:
- Drupal-driven products
- Areas without Cypress test coverage

Functionality to test:
- Events - Cypress test coverage is good, could do some manual testing as well
- Forms migration
- Reusable Q&As - Entity Browser functionality

Possible next steps:
- Assess which products Cypress tests exist for (start with Cypress files, see what they test)
- Audit a few products at a time for test coverage, make clear recommendations for tests to add
- Test types to consider: Cypress (slow), kernel (fast), unit (fastest)

**Testing spreadsheet**: https://docs.google.com/spreadsheets/d/136FP-HtxRWJuPYYV4D95ngby96Wqy4Ul_HOgOqEk1K0/edit#gid=0**

## Acceptance criteria

- [ ] 1st pass - Tests in https://docs.google.com/spreadsheets/d/136FP-HtxRWJuPYYV4D95ngby96Wqy4Ul_HOgOqEk1K0/edit#gid=0 are run, bugs are filed and/or reported to CMS team in #d10-upgrade-testing DSVA slack
- [ ] 2nd pass - re-run tests when D10 fixes are largely complete and we are approaching go/no-go

**Comment by wesrowe** [comment]
@jilladams created a [Google spreadsheet](https://docs.google.com/spreadsheets/d/136FP-HtxRWJuPYYV4D95ngby96Wqy4Ul_HOgOqEk1K0/edit?usp=sharing) as a temporary working doc for testing/bug bashing across PW products.

**Comment by jilladams** [comment]
Facilities sister ticket: 
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13990

**Comment by dsasser** [comment]
# Mid-sprint status update

This ticket is not likely to close in sprint 88 due to: it was not started until mid sprint, and it is a 13 point ticket. This is no surprise as we planned for this potentiality during sprint planning.

**Comment by jilladams** [comment]
@dsasser proposed an AC here, since there wasn't one. If unreasonable, holler.

**Comment by jilladams** [comment]
Also noting: Facilities team opted for an epic and tickets to track each logical chunk of testing work. If that seems nice / more reasonable as a way to break this up, let's discuss. I'll seed in scrum tomorrow.

**Comment by jilladams** [comment]
went ahead and made an epic: #14414 , so we can keep track of the bugs that pop up.

**Comment by jilladams** [comment]
Per scrum convo today, closing.
