### ISSUE TITLE
Remove `urgent care` reference....

### ISSUE THREAD

**Issue by kmariepat-cityfriends** [department-of-veterans-affairs/va.gov-cms#14006]
Can we please have "Urgent care" removed or changed? It has a particular meaning, particularly to health care professionals, so is misleading. It is on the Gillette VA Clinic page and the Riverton VA Clinic page, but none of the others in our system. We do not provide "urgent care" though do provide "Walk-in care" ... which would be accurate terminology.
Riverton VA Clinic | VA Sheridan Health Care | Veterans Affairs<https://www.va.gov/sheridan-health-care/locations/riverton-va-clinic/>
[cid:image001.png@01D8D262.217B8240]
I'll bring it to facilities team refinement on Thursday and will update this thread after

https://dsva.slack.com/archives/CJ162GDDJ/p1685540911406779?thread_ts=1664211493.324099&cid=CJ162GDDJ

**Comment by kmariepat-cityfriends** [comment]
The text comes from Access to Care, may need to check in with this team

related card: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11709

**Comment by kmariepat-cityfriends** [comment]
@mmiddaugh will do, 

- #11709 remains because it contains the most content 
- #14006 is closed as a dupe
- #55227 produces a 404 when I try to view 

I made a new issue with the sitewide content team to review the proposal from @laflannery presented on #11709
https://app.zenhub.com/workspaces/sitewide-content-accessibility-and-ia-63a1d63232beba0011a7833f/issues/gh/department-of-veterans-affairs/va.gov-team/60112

**Comment by mmiddaugh** [comment]
I suspect the link to #55227 has been problematic because the auto-generated link points to the wrong repo. [This link](https://github.com/department-of-veterans-affairs/va.gov-team/issues/55227) should work.
