### ISSUE TITLE
Add SEO configuration for VBA Regional Office

### ISSUE THREAD

**Issue by omahane** [department-of-veterans-affairs/va.gov-cms#14000]
## User Story or Problem Statement

As an editor, I want to be able to add meta tag information to the VA Regional Office to maximize the ability for search engines to find the content and for social media to display links to the content.

## Acceptance Criteria
- [x] Implement meta tag field (hidden) on the VBA Facility content type.
- [ ] Populate meta tag with entity fetch field for the description.

## Implementation steps
Update the appropriate fields 
https://prod.cms.va.gov/admin/config/search/metatag

**Comment by xiongjaneg** [comment]
@mmiddaugh Do we want the metatag information for VBA Regional Offices? It currently is on VAMCs and Vet Centers. It is using custom content that puts the name into the content and is under full editor control but could be wrong. A better option would be to use a token that isn't editable but will always be right.

**Comment by xiongjaneg** [comment]
Per PO sync, is it possible for MVP to follow the Vet Center model but make the field uneditable (add to centralized content)?

**Comment by xiongjaneg** [comment]
@mmiddaugh Will we ever want the editors to be able to customize the page introduction text?

**Comment by xiongjaneg** [comment]
Per Michelle 11/29, follow the Vet Center model and leave it editable by local editors. We'll start by providing standard text for these fields.

**Comment by xiongjaneg** [comment]
Tokens are an option when using meta tags. They could be slightly customized (editable, visible) later. We are not currently using tokens.

With meta description, when a facility name changes, the meta description has to be updated and still refer to the former name. This doesn't affect how high you show up in a search. This is the default if a search engine can't find a smart snippet.

**Comment by xiongjaneg** [comment]
Decision:
MVP: Use meta tag for VBA MVP so it can be tokenized.
Future: Collab with CAIA on guidance for optimizing meta description fields.

**Comment by xiongjaneg** [comment]
@xiongjaneg follow up ticket

**Comment by omahane** [comment]
This will need to be done in production once the code is deployed: 
`drush scr ./scripts/content/VACMS-14000-vba-facility-meta-tags.php`

**Comment by jilladams** [comment]
Script ran on prod: https://dsva.slack.com/archives/CT4GZBM8F/p1703019100211129

Checked QA steps from PR in prod, and verified, e.g., https://prod.cms.va.gov/wilmington-va-regional-benefit-office/locations/wilmington-va-regional-benefit-office includes meta name in the inspector but not on screen. 

Closing!
