### ISSUE TITLE
VBA: Refine Conversation Guide

### ISSUE THREAD

**Issue by kmariepat-cityfriends** [department-of-veterans-affairs/va.gov-cms#14008]
- [x] Refine in collaboration with @thejordanwood based on VBA prototype
- [x] Review conversation guide with @mmiddaugh + @kmariepat-cityfriends + UX team

**Comment by cindymerrill** [comment]
Yesterday we met with Michelle to talk about tasks for usability testing, and also talked a lot about the design with Jordan and @kmariepat-cityfriends . After the meeting, I made a quick list of the tasks we talked about in my [brainstorming document](https://dvagov-my.sharepoint.com/:w:/g/personal/cynthia_merrill_va_gov/EX34G0luidZNkCSxwLwujMIBlt-165ZbOoYqLjHVjYj0Yg?e=FYleMn) on SharePoint in the new **Task list (draft)** section.

Today I met with @ALogsdon3 to discuss the tasks needed, and she's going to try drafting some and share them with me at end-of-day Monday. I am available to help and will collaborate with her on them.

**Comment by cindymerrill** [comment]
Reviewed the user tasks that @ALogsdon3 drafted and left comments. Next steps: Discuss tomorrow with Alexis, and then get them into the conversation guide with appropriate followup questions based on research questions.

**Comment by cindymerrill** [comment]
Worked with @ALogsdon3 on user tasks. Revised them some more and then [shared them in slack](https://dsva.slack.com/archives/C0FQSS30V/p1686788023989539) for feedback. 

Next step is to add questions/probes based on the research questions, which I plan to work on next.

**Comment by cindymerrill** [comment]
Incorporated tasks from shared document into [conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/regional-offices/research/2023-06-veteran-facing/conversation-guide.md)
