### ISSUE TITLE
Design: Improve Editorial UI for News promo block

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#14002]
### User story

**AS A** Homepage Manager role
**I WANT** the UX of altering the News promo block to be clearer and have revision logs
**SO THAT** I am more likely to successfully keep that area of the homepage fresh.

### Design

[News promo Figma file](https://www.figma.com/file/sOMpovTM82TgC08ugF0FxF/News-Promo-Block?type=design&node-id=0%3A1&mode=design&t=fqOkdRBl50BIRhv6-1)

### Engineering notes / background

Dave C edited the News promo block just before hard launch of the new homepage and made the following observations:

- We need to do some QA on the help text associated with any of these fields.
- There's no way to "cancel" my edits when I've started editing.
- Revision logs are not required
- It's not clear why the Link Text CTA is a dropdown if the only option is "Read the full article". (Reason: #11172 will add further options.)

**Where to find in CMS:**
Filter block type on [Staging blocks list](https://staging.cms.va.gov/admin/structure/block/block-content)

[Overview of Homepage Editor UX](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11802) of steps and UI (possibly slightly outdated)

## Acceptance criteria
- [x] Documented the following updates in a Figma design
  - [x] Help text is accurate and complete
       - [x] Link Text help text ONLY on News Promo
       - [x] Block Description help text on both Benefit and News promos
       - [x] Promo Headline help text on both Benefit and News promos
  - [x] Added a way to "cancel" my edits when I've started editing.
  - [x] Revision logs are required
  - [x] Decided whether we can should leave the Link Text CTA as a dropdown if the only option is "Read the full article". (Reason: #11172 will add further options.) - We're keeping this a dropdown
- [x] Added Figma link to implementation ticket #13863.
- [ ] Design reviewed by @wesrowe and @davidconlon

**Comment by wesrowe** [comment]
Assigning to @thejordanwood for pre-refinement.

**Comment by jilladams** [comment]
@thejordanwood I don't think we'll add new CTA options anytime soon, AND I am not certain we want to spend the effort to change the dropdown to something else meantime. Where does that leave you on this? If that sucks, we can confirm with DaveC that I'm right in my hunches.

**Comment by thejordanwood** [comment]
@jilladams I should've wrote a follow up comment here. I discussed this with Wes and we're going to leave it as a dropdown for now.

**Comment by thejordanwood** [comment]
@jilladams My end of sprint update on this: Wes has approved the design, but I don't believe this has been approved by Dave C. yet.

**Comment by wesrowe** [comment]
I can't recall why we said Dave C needed to review the design. The ticket did start with his feedback. But I don't think the problem or solution warrants his review, unless someone recalls a specific reason he needed to review. (Vacation brain at my end here.)

**Comment by jilladams** [comment]
@thejordanwood is this file set to "Anyone can view"? It asks me to auth to view it, and I'm wary of their Dark Pattern 🧙

**Comment by jilladams** [comment]
https://dsva.slack.com/archives/C52CL1PKQ/p1689718592173949

**Comment by wesrowe** [comment]
Noting here Dave's [response](https://dsva.slack.com/archives/C52CL1PKQ/p1689780497481509?thread_ts=1689718592.173949&cid=C52CL1PKQ): 
>the "delete" is throwing me because this is the first time I've seen "delete" in the CMS
