### ISSUE TITLE
User Flow Diagram for Facility Locator 

### ISSUE THREAD

**Issue by kmariepat-cityfriends** [department-of-veterans-affairs/va.gov-cms#14005]
The Collaboration Cycle has introduced a new requirement for Design Intent. :change-announcement:
Attention: VFS teams
As of 06/06/2023, the Governance team has a new requirement for the Collaboration Cycle.
Impact: VFS teams must now provide a user flow diagram as a required artifact for Design Intent meetings.
Documentation: see the Design Intent requirements on Platform Website
Support: Reach out to the Governance team by filing a support request on #vfs-platform-support

**Comment by thejordanwood** [comment]
Mockups that show each screen of the flows for VA health, VA benefits, Vet Centers, and Community Providers are in [the Sketch file](https://sketch.com/s/d5e5c924-e8c0-47af-b3e4-994c335d6f31).
