### ISSUE TITLE
KB Articles related to VAMC System Banner alerts:  Review for publish

### ISSUE THREAD

**Issue by kmariepat-cityfriends** [department-of-veterans-affairs/va.gov-cms#14009]
## Context
For limiting VAMC banners published to one, we need to review KB articles. 

We need to break apart homepage Full-width (& Promo) banners from VAMC banners, and make the distinctions clear. 

## ACs

- [x] FOR ALL OF THEM
  - [x] ensure we use full name of Content type for clarity "VAMC System Banner Alert with Situation Updates"
  - [x] Double check link, because they break
  - [x] Double check that any screenshots are showing new truth
  - [x] Follow style guide https://va-gov.atlassian.net/wiki/spaces/VAGOV/pages/1771831299/Knowledge+Base+content+style
  - [x] Remove any covid-19 references
  - [x] Consolidate content release info by linking to article
- [x] [About VAMC alerts and operating statuses KB Article Updates](https://docs.google.com/document/d/1wfzt3f6e9hEU8gxaTuxyLAI4OvWCtSoUkKptegnXnhs/edit)
  - https://prod.cms.va.gov/help/vamc/about-locations-content-for-vamcs/about-alerts-and-operating-statuses
  - [x] Update screenshot of banner alert so it's compliant with new rules
  - [x] Remove COVID-19 language? 
  - [x] Add section about what to use instead for marketing type stuff @mmiddaugh 
  - [x]  Review content, draft changes in the CMS node
  - [x] Get technical review
  - [x]  VHA DM signoff
- [x] https://prod.cms.va.gov/help/vamc/about-locations-content-for-vamcs/about-alerts-and-operating-statuses/how-to-add-a-system-banner-alert
    - [x] Add a section about Allow Only One between Add a banner alert and Add a situation update
    - [x] update "Unpublish a banner alert" to reflect new truth - link to view for copy and paste of unpublished?
    - [x] Review content, draft changes in the CMS node
    - [x] Get technical review
    - [x] VHA DM signoff
- [x] https://prod.cms.va.gov/help/vamc/about-locations-content-for-vamcs/about-alerts-and-operating-statuses/best-practices-for-vamc-system-banner-alerts
    - [x] Review content, draft changes in the CMS node
    - [x] Get technical review
    - [x] VHA DM signoff
- [x] https://prod.cms.va.gov/help/cms-basics/resources-for-emergency-situations
    - [x] Review content, draft changes in the CMS node (I saw nothing that needed to be changed --Christian)
    - [x] Get technical review
    - [x] VHA DM signoff
- [x] https://prod.cms.va.gov/help/vamc/how-to-create-a-situation-update
    - [x] Review content, draft changes in the CMS node
    - [x] Get technical review
    - [x] VHA DM signoff

### Other things that may need updates, but are not critical for this sprint
- [ ] https://prod.cms.va.gov/help/get-training/session-4-facilities
   - [ ] talk to help desk about the video here and a path forward 
- [ ] [Full Width Alerts KB Article Updates](https://docs.google.com/document/d/1PaqjVYG37kVxp_fT3T87okM0Qki814Py4O2v6QWskt4/edit)
    - [x] Add changes to node as draft revision https://prod.cms.va.gov/help/homepage-alerts-and-promo-banners/full-width-alerts
    - [ ] Need to verify if character count language here applies, and whether this update should be published 
- [ ] https://prod.cms.va.gov/help/vamc/about-locations-content-for-vamcs/about-alerts-and-operating-statuses/govdelivery-and-vamc-system-banner-alerts
    - [ ] Review content, draft changes in the CMS node
    - [ ] Get technical review
    - [ ] get Helpdesk signoff
    - [ ] get VHA DM signoff
- [ ] (Need access) [Promo Banners KB Article Updates](https://docs.google.com/document/d/1IT6YPVOYH9-6V0YYBdab7DKsb3zTZjjpx4RgDKIbuLE/edit#heading=h.2tiout23hfzj)
        - https://prod.cms.va.gov/help/homepage-alerts-and-promo-banners/promo-banners

**Comment by TroyA6** [comment]
@kmariepat-cityfriends @stefaniefgray  - The Article looks good, but I do have a couple of thoughts (I was unable to edit)

**Comment by kmariepat-cityfriends** [comment]
@TroyA6 have your comments been added? is this ready to go for another edit round incorporating your comments. Ideally I'd like to send a final version to review to VHA DM tomorrow

**Comment by jilladams** [comment]
Pinged helpdesk internally for update ([here](https://agilesix.slack.com/archives/C01DTUNHFE2/p1687298100703609))

**Comment by kmariepat-cityfriends** [comment]
rolling into Sprint 88, awaiting help desk approval and publish of article

**Comment by TroyA6** [comment]
@kmariepat-cityfriends @jilladams @stefaniefgray  - These changes look good to me - especially the example scenarios, the explanation of the functionality, and the instruction to create new rather than re-use alerts. Nice job! 
I approve -- Please let me know if I need to act further.

**Comment by kmariepat-cityfriends** [comment]
@TroyA6 thank you for your review, i've sent final help desk approved language to VHA DM for final review, after their approval we will publish changes

**Comment by swirtSJW** [comment]
Thanks @davidmpickett .  I feel like this is incomplete.   That article is not addressing the VACMS System banner alerts, only the global ones.

**Comment by swirtSJW** [comment]
Yah the KBs that actually relate to VAMCs have not been touched.  
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5752113/9f989ed8-8ed6-406f-a7ff-2cd799ba97cc)

**Comment by jilladams** [comment]
DaveP has migrated changes from https://docs.google.com/document/d/1PaqjVYG37kVxp_fT3T87okM0Qki814Py4O2v6QWskt4/edit?usp=sharing to the CMS node as a draft revision.

Next steps from planning: 

- [ ] @swirtSJW provide links to the articles in the screenshot above
- [ ] Google docs access we need from Friends in re: KB nodes: 
    - [ ] [About VAMC alerts and operating statuses KB Article Updates](https://docs.google.com/document/d/1TzmP9ULIIU7u-mFgrJwuE4jVPduCpALFF2H4Zkth620/edit#heading=h.lg64atfhmewa)
        - https://prod.cms.va.gov/help/vamc/about-locations-content-for-vamcs/about-alerts-and-operating-statuses
    - [ ] [Promo Banners KB Article Updates](https://docs.google.com/document/d/1IT6YPVOYH9-6V0YYBdab7DKsb3zTZjjpx4RgDKIbuLE/edit#heading=h.2tiout23hfzj)
        - https://prod.cms.va.gov/help/homepage-alerts-and-promo-banners/promo-banners

**Comment by davidconlon** [comment]
@davidmpickett @jilladams Something I noticed that we need to be careful on conflating in terms of support/help docs and discussions that will likely need collaboration between Facilities and PW so we don't conflate/lose anything:
- Full Width Alert - this term is used for a CMS content type and is also used for a front end design element. These are connected at this time, but not sure if that's the right thing? The Doc that @davidmpickett edited (node 34828), as I read it, is for the Full Width Alert content type, not facilities (this is an idiot check. For consideration; rename?)
- VAMC System Banner Alerts with Situation Updates this is a Facilities-owned content type that uses Design System elements (one of which is the Full Width Alert FE Design Pattern). 

@EWashb - I'm also noting that we have "Banners and Alerts" as a product in the CMS, but I don't think this is inherently a product but is a feature of products.  For instance:
- "Full Width Alert" is a feature of Benefits Hubs, Outreach Hub, Resources and Support, and Homepage (currently, I think)
- VAMC System Banner Alerts with Situation Updates is a feature of VAMCs

**Comment by omahane** [comment]
@mmiddaugh We have multiple references to the content release time in the articles I'm editing (I've already noticed these 3):

https://prod.cms.va.gov/help/vamc/about-locations-content-for-vamcs/about-alerts-and-operating-statuses/how-to-add-a-system-banner-alert
>  It may take about 30 to 45 minutes after saving the alert for the banner to appear, depending on how long the content release takes. 
> Check "Published" to add the banner alert to the top of your system pages after the content release finishes (usually 15 to 30 minutes after publishing).

https://prod.cms.va.gov/help/vamc/about-locations-content-for-vamcs/about-alerts-and-operating-statuses
> The alert will appear at the top of every page on your site, after the content release finishes, which can take about 30 to 45 minutes. 

---

After looking more, there's the following:
[How to release content](https://prod.cms.va.gov/node/23361/)
> Click the Release content button. The process may take about 10 minutes to be successfully completed.

[Full Width Alerts](https://prod.cms.va.gov/help/homepage-alerts-and-promo-banners/full-width-alerts)
> Content releases may take 15 to 30 minutes to finish.

[Content release to VA.gov](https://prod.cms.va.gov/help/cms-basics/content-release-to-vagov)
> In general, the content release process will take about 30 to 45 minutes to complete if there are no technical or content issues. 

[How to release content in the demo environment
](https://prod.cms.va.gov/help/how-to-release-content-in-the-demo-environment)
> Click Release content. The process may take about 10 minutes to be successfully completed.

My recommendation is that we only mention the time it takes on the [Content release to VA.gov](https://prod.cms.va.gov/help/cms-basics/content-release-to-vagov) and change any other reference to "content release," "[r]elease content," or "content releases" to include a link to that page. Especially with accelerated publishing, we intend to reduce that time, and I don't think we want to update multiple pages every time we do so.

**Comment by mmiddaugh** [comment]
Previously provided feedback and questions from VHA DM: 

- Add Screenshots of improper banner use and proper banner use
- Add Screenshots of what it looks like to use a story or event with a spotlight 
- Add more language on how multiple banners and/or long banners are terrible for mobile use

Questions from VHA DM which we can _consider_ proactively answering in the KB article as appropriate 

- Is there a difference between Full Width Banners and Full Width Alerts? Or are these terms interchangeable? 
- Is the “VAMC System Banner Alert” option going away 
- Is the 1 banner limit per facility or health care system? 
- If we put up a system wide banner does that affect a VAMC's ability to put up a banner?
- If we (VHA DM/OCTO) put up a national banner on all VAMC websites, will an individual facility still be able to put up their own banner? 
   - Answer previously provided to VHA DM by Dave C: "As it stands right now, no. Only one banner is allowed per the VA.gov design system. Don’t stack banners. Only one Banner may appear on any page at one time. If multiple emergency issues occur at once, combine the message and link out to a landing page or to individual affected medical centers, for example."

**Comment by omahane** [comment]
@mmiddaugh I am not sure about the alternative as described in this AC:
- [ ] Add section about what to use instead for marketing type stuff @mmiddaugh
related to https://prod.cms.va.gov/help/vamc/about-locations-content-for-vamcs/about-alerts-and-operating-statuses

For instance, I logged in as an editor, and they don't have access to the Promo Banner or Full-width alert.

**Comment by omahane** [comment]
@davidmpickett @mmiddaugh I didn't make any changes to https://prod.cms.va.gov/help/cms-basics/resources-for-emergency-situations, as I didn't see any to make. Let me know if you see otherwise.

**Comment by omahane** [comment]
@davidmpickett @mmiddaugh Do you want to look at these before I send them to Help Desk?

**Comment by mmiddaugh** [comment]
What to use instead of a VAMC System Banner Alert with Situation Update

For non-emergency information such as marketing and national content, you can use a story or event with a spotlight. See some examples below. 
Note: Do not duplicate national content. 

- For promotional messages about the Call center or secure messaging: Use a story with a spotlight.
- For information about the availability of a flu shot or promotion of a flu clinic: Use a story with spotlight, event for flu clinics, or a program page with a link from the spotlight area.
- To guide Veterans to information about vaccinations: Use a program page with a link from the spotlight area or a story with a spotlight. 
- To announce new phone numbers: Use a news release or story. 
- For Town Hall event announcements: Use an event with spotlight.

We are continually listening to feedback and looking at the analytics on the performance of the VAMC product, including the effectiveness of these methods for promoting content. This data will inform future iterations or the creation of additional methods to share information with your audience.

**Comment by omahane** [comment]
@stefaniefgray I have updated the KB articles here (except for https://prod.cms.va.gov/help/cms-basics/resources-for-emergency-situations, which didn't appear to require a change). Could you do the Help desk review of the latest revisions?

**Comment by davidmpickett** [comment]
For ease of review, here are links to the latest draft revision compared to the currently published revision for each of the articles
- [ ] [About VAMC alerts and operating statuses](https://prod.cms.va.gov/node/6868/revisions/view/721350/788219/visual_inline)
- [ ] [How to add a system banner alert](https://prod.cms.va.gov/node/6871/revisions/view/721349/788012/visual_inline)
- [ ] [Best practices for VAMC system banner alerts](https://prod.cms.va.gov/node/43819/revisions/view/656780/788039/visual_inline)
- [ ] [How to create a situation update](https://prod.cms.va.gov/node/23520/revisions/view/527774/788071/visual_inline)

**Comment by davidmpickett** [comment]
@omahane - some feedback in Must/should/consider format

**About VAMC alerts and operating statuses**
- MUST - The new screenshot under System banner alerts labels the FE banner alert as a "VAMC System Banner Alert with Situation Updates" but technically it's only a "VAMC System Banner Alert." The Drupal content type powers two separate front end elements.
- SHOULD - To be consistent with other screenshots, this should also have the box around it with a label of the page represented
- CONSIDER - Should there be a link to the "How to create a situation update" article somewhere on this page? Given that they are discussed here alongside banners and operating statuses, it seems like a logical addition
- CONSIDER - Now that we link to the Content release article, do we need the sentence "Each content release processes all published content on Drupal." ?

**Comment by davidmpickett** [comment]
Do we need both a [Add a situation update](https://prod.cms.va.gov/node/6871/revisions/788012/view#situation-update) section in "How to add a system banner alert" article and a separate [How to create a situation update](https://prod.cms.va.gov/node/23520/revisions/788071/view) article?

These  seem to serve the exact same purpose - a step-by-step guide on adding a situation update. I think we SHOULD remove the "Add a situation update" section from the "How to add a system banner alert" article and link to the "How to create a situation update" article where relevant instead.

That being said, I think the steps listed in the section text are better than the steps listed in the full article. The full article instructs editors to use the in-line editor on the VAMC System Operating Status, which we know has issues and want to move away from.

**Comment by davidmpickett** [comment]
@omahane Reading through these, I feel like we need to have more specific guidance on how to distinguish banner alerts, situation updates, and the content type that controls both. Here's what I'm thinking:

- **VAMC System Banner Alert** 
  - Describes the front end banner that displays on a VAMC system site
  - On first reference use full title
    - e.g. _The intent of a Situation Update is to provide a site visitor long-form, detailed information about a situation described in a VAMC System Banner Alert._
  - Subsequent references in same article can shorten to "system banner alert" or "banner alert" 
    - e.g. _Follow the steps to unpublish the banner alert._
  - "Alert" and "banner" on their own should only be used when absolutely necessary
    - e.g. _Click the Alert type menu. Select Information if it's not an immediate emergency alert._
- **VAMC System Banner Alert with Situation Updates**
  - Describes the Drupal Content type editors interact with
  - Use full name whenever specifically referencing the content type as a whole
  - e.g. _Click the "Content type" dropdown menu and select "VAMC System Banner Alert with Situation Updates."_
- **Situation Updates**
  - Describes the optional extended message that displays on the VAMC System Operating Status page
  - Situation Update on first reference, can be shortened to "update" on subsequent use

**Comment by davidmpickett** [comment]
**Best practices for VAMC system banner alerts**
- SHOULD - Mention and link to Situation Updates in the 2nd bullet under **Use links** section. Maybe "Consider putting extended information in a Situation Update on the Operating Status page..."

**Comment by davidmpickett** [comment]
Official request https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14317

**Comment by mmiddaugh** [comment]
@omahane I'm hoping you still have the screenshot and it's easy for you to make updates. If so, would it be possible to make the changes suggested by [DaveP](https://app.zenhub.com/workspaces/sitewide-facilities-639f5253e4b702a32376339e/issues/gh/department-of-veterans-affairs/va.gov-cms/14009#issuecomment-1629804240) 

- [ ] update the label on the screenshot under System banner alerts on "About VAMC alerts and operating statuses" from "VAMC System Banner Alert with Situation Updates" to "VAMC System Banner Alert"
- [ ] add the box around it for consistency

**Comment by omahane** [comment]
@davidmpickett Do you know if there's some template around for screenshots to make them inline with others?

**Comment by omahane** [comment]
> @davidmpickett Do you know if there's some template around for screenshots to make them inline with others?

I made one in Acorn.

**Comment by omahane** [comment]
@davidmpickett @mmiddaugh Am I the only one that has a hard time reading the text on the screenshots? I don't know why the images themselves are so small, but it makes the text barely readable and even some of the elements in the screenshot hard to distinguish.

**Comment by omahane** [comment]
> @omahane Reading through these, I feel like we need to have more specific guidance on how to distinguish banner alerts, situation updates, and the content type that controls both. Here's what I'm thinking:
> 
> * **VAMC System Banner Alert**
>   
>   * Describes the front end banner that displays on a VAMC system site
>   * On first reference use full title
>     
>     * e.g. _The intent of a Situation Update is to provide a site visitor long-form, detailed information about a situation described in a VAMC System Banner Alert._
>   * Subsequent references in same article can shorten to "system banner alert" or "banner alert"
>     
>     * e.g. _Follow the steps to unpublish the banner alert._
>   * "Alert" and "banner" on their own should only be used when absolutely necessary
>     
>     * e.g. _Click the Alert type menu. Select Information if it's not an immediate emergency alert._
> * **VAMC System Banner Alert with Situation Updates**
>   
>   * Describes the Drupal Content type editors interact with
>   * Use full name whenever specifically referencing the content type as a whole
>   * e.g. _Click the "Content type" dropdown menu and select "VAMC System Banner Alert with Situation Updates."_
> * **Situation Updates**
>   
>   * Describes the optional extended message that displays on the VAMC System Operating Status page
>   * Situation Update on first reference, can be shortened to "update" on subsequent use

Where are you thinking we should make this distinction? I am assuming that you're referring to [About VAMC alerts and operating statuses](https://prod.cms.va.gov/node/6868/revisions/view/721350/788219/visual_inline)

**Comment by omahane** [comment]
Further questions, concerns about this: https://dsva.slack.com/archives/C0FQSS30V/p1689284007309889

**Comment by omahane** [comment]
@davidconlon @jilladams I have made all my edits. These are ready for further review now.

**Comment by jilladams** [comment]
Based on this: https://dsva.slack.com/archives/C0FQSS30V/p1689273357069219
> - only feedback from VHA DM on VAMC  Banner Alert KBs is the desire to emphasize the character limitation (Blake suggested bolding item 12 under the “Add a banner alert” heading)
> I don't object to that suggestion if it works within the style guide and just note that there may be other places where adding that emphasis makes sense

I'm checking off the AC re: VHA DM signoff ACs.
