### ISSUE TITLE
Figure out initial steps with eMASS/Code Scanning/etc

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-cms#14055]
## Description
Recently the following PRs were opened for This Very Repo:
- https://github.com/department-of-veterans-affairs/va.gov-cms/pull/13993
and `content-build`:
- https://github.com/department-of-veterans-affairs/content-build/pull/1591

Related are the following issues:
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14054
- https://github.com/department-of-veterans-affairs/content-build/issues/1601

To my knowledge, and according to other people in Slack, we haven't received any prior communications about this:
- https://dsva.slack.com/archives/C04CYC4LMU6/p1686059193842309
- https://dsva.slack.com/archives/C02RLAUM2LV/p1686094794161249

This is not something I can currently deal with easily and unilaterally, since updating and merging the PR [requires information that I don't have](https://department-of-veterans-affairs.github.io/ois-swa-wiki/docs/ghas/codeql-usage/update-emass-json/). 

Of course, we already have CodeQL configured, so the only real urgency is incurred by whatever will be done to us if we don't remedy this situation in compliance with the requirements and timeline they haven't bothered to relay to us.

## Acceptance Criteria
- [ ] Find someone who knows what they're talking about.
- [ ] Discover requirements and action items from whatever they tell us to do.
- [ ] Followup issue(s) opened to address specific action items identified during the above process.

**Comment by ndouglas** [comment]
Note that they closed #14054 and opened a new, apparently identical issue. Warning to not consider this completed.

**Comment by timcosgrove** [comment]
@ndouglas I just spoke to some OIT support folks about this. The short answer is, here is an example of the correct values to configure here:

https://github.com/department-of-veterans-affairs/next-build/pull/116/files#diff-97a207d4a10a411faf194af2121f302eb1e7b3b091385932ef5da1706628f5f5R2

1027 and the System Name are shared. Owner name should reflect the team or person responsible for the repo, and the email should reflect that. The email is allowed to be external to VA.

That said, I have not yet seen it successfully run: https://github.com/department-of-veterans-affairs/next-build/actions/runs/5624972334/job/15242935908

I have a ticket open on the VA codeql-tools repo asking about this: https://github.com/department-of-veterans-affairs/codeql-tools/issues/45

 I'll update this ticket when I learn anything.

**Comment by timcosgrove** [comment]
In case it's useful, this is the spreadsheet I pulled the ID and System Name values from, which was linked to by OIT Support and is public information. 
[emass.xls](https://github.com/department-of-veterans-affairs/va.gov-cms/files/12131334/emass.xls)

**Comment by ndouglas** [comment]
Thank you, @timcosgrove . Think this is closed now in #14490.
