### ISSUE TITLE
Relative links not working in injected footer

### ISSUE THREAD

**Issue by jtmst** [department-of-veterans-affairs/va.gov-cms#14064]
## Description
It was observed on the benefits.va.gov site that relative links are not working in the injected footer.  It is suspected that the drupalizing of the footer has left some relevant links not working. It may be possible to just add protocol/domain to menu links so that it works on both va.gov and injected header sites.

per this slack convo:
https://dsva.slack.com/archives/C52CL1PKQ/p1686663115353049

**Broken links:** 
* VA Outreach Events -- https://prod.cms.va.gov/admin/structure/menu/item/11570/edit?destination=/admin/structure/menu/manage/va-gov-footer
* VA forms -- https://prod.cms.va.gov/admin/structure/menu/item/11573/edit?destination=/admin/structure/menu/manage/va-gov-footer
* VA Outreach Materials -- https://prod.cms.va.gov/admin/structure/menu/item/11580/edit?destination=/admin/structure/menu/manage/va-gov-footer
* Your VA Welcome kit -- https://prod.cms.va.gov/admin/structure/menu/item/11581/edit?destination=/admin/structure/menu/manage/va-gov-footer

## repro steps
* Go to https://benefits.va.gov
* Click on the 4 listed footer links
* Observe that you land on `https://department.va.gov/path` rather than `https://va.gov/path`

### User story
As a veteran, I want all links in the injected header nav to lead to the correct page

**AS A** veteran
**I WANT** links from the footer to work from any site where the footer appears
**SO THAT** I get the info I need

### Engineering notes / background
#11482 was the most recent change, likely implicated here

### Analytics considerations
@wesrowe I think we should try and see if we can work out whether we can see how many 404s people got as a result of this breakage? Not sure if that's possible, since it was pointers to department.va.gov paths.

## Acceptance criteria
- [ ] When clicking from injected site e.g. https://benefits.va.gov, All links in injected footer work as intended, and user lands on va.gov paths.
  - [ ] Find forms
  - [ ] VA outreach events
  - [ ] VA outreach materials
  - [ ] VA welcome kit

**Comment by jilladams** [comment]
@wesrowe we likely also need a backlog ticket to modify the Drupal footer menu https://prod.cms.va.gov/admin/structure/menu/manage/va-gov-footer to make form instructions clear that absolute links must be used, for the injected header/ footer to work, if that's where this solution lands.
