### ISSUE TITLE
I.L. Design/Content: How could the app handle Veterans without a zip code?

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#14073]
### User story

**AS A** Veteran without a zip code
**I WANT** my situation to be acknowledged and some help offered
**SO THAT** I trust the VA has my interests in mind.

### Background

Some Veterans will not have a zip code to enter but might still want to know income limits. Examples include (per stakeholder Lindsey Peace):
- Homeless in the year in question (e.g., last year for the current-year flow)
- Living outside the U.S.

The current experience fails these Veterans because:
- It requires a zip code to proceed to the results screen
- The results screen doesn't offer any way to figure out which thresholds relate to zip code and which don't require a zip code (actual: only the GMT is zip-related; the non-zip results are basically the same as the GMT<NMT case, ie with one fewer accordion)

## Acceptance criteria

- [ ] Researched use cases
- [ ] Documented how app could handle it
- [ ] Ticketed next steps (e.g. Content intake ticket, UX design, etc)

**Comment by wesrowe** [comment]
Lindsey Peace emailed:

>The national and pension thresholds are set regardless of where the Veteran lives. Also note that if the correspondence address is local to US, the GMT will apply for that address. For example, a Veteran living overseas temporarily will have an overseas address as well as a US address.  

Lindsey forwarded a SME analysis of this question:

>Here [below] are the links I found regarding medical services for veterans in foreign.   Based on these sites, only veterans with a service connection are authorized care outside the US after they have registered for the Foreign Medical Program (FMP).  Any nonservice-connected veteran would not be eligible for this program and would need to return to the US for VA care or have personal insurance that covers foreign medical care.  Therefore, nonservice-connected veterans living outside the US would be subject to income verification based on the National and the pension thresholds.  The GMT would be based on their address stateside.
>Thanks,
>Stanford W. Harrell
>Management and Program Analyst

Links:
[1601F_05(1)_D_2021-10-19.pdf](file:///C:/Users/VHAHEC~1/AppData/Local/Temp/1/MicrosoftEdgeDownloads/352db4c0-32a1-4e64-9936-6bc35ff078fd/1601F_05(1)_D_2021-10-19.pdf)               VHA Directive 1601F.05               Hospital Care & Medical Services in Foreign Countries
[Foreign Medical Program (FMP) - Community Care (va.gov)](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.va.gov%2FCOMMUNITYCARE%2Fprograms%2Fveterans%2Ffmp%2Findex.asp&data=05%7C01%7C%7C207f943ec26147cf1d4b08db6e5cf116%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C638225117681016044%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=WdOMFyBmVl40escbqwvQEh5ct3pVAzFMb1RShlxflbw%3D&reserved=0)                       Foreign Medical Program
[eCFR :: 38 CFR 17.35 -- Hospital care and outpatient services in foreign countries.](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.ecfr.gov%2Fcurrent%2Ftitle-38%2Fchapter-I%2Fpart-17%2Fsubject-group-ECFR9f304a469572619%2Fsection-17.35&data=05%7C01%7C%7C207f943ec26147cf1d4b08db6e5cf116%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C638225117681016044%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=vsCBVu9Ft2stbpRT%2BHg26Qkkxr2gBGs0UAA0nSukouA%3D&reserved=0)           Hospital care and outpatient services in foreign countries

**Comment by wesrowe** [comment]
this is likely a no-op – per stakeholders, offshore Veterans are required to have a US mailing address, and that zip code is used for income limits. Before closing, you can confirm with stakeholders (Lindsey Peace).

**Comment by FranECross** [comment]
Email sent today to Lindsey Peace

Hello, Lindsey,

I’m looking at an older Github ticket for a proposed update to the Income Limits app, and you’re mentioned as a Stakeholder. If you’re still the stakeholder, will you please review my question below? If not, will you please respond letting me know?

The ticket is to design a way for Veterans without US addresses to still retrieve information from the app, however I see notes in the ticket that indicate “this is likely a no-op – per stakeholders, offshore Veterans are required to have a US mailing address, and that zip code is used for income limits. Before closing, you can confirm with stakeholders (Lindsey Peace).”

My question is whether or not we can close the ticket as ‘will not be done’ based on the info in italics above.

Thanks in advance!

**Comment by FranECross** [comment]
Closing per stakeholder as not needed. 
[IncomeLimitsApp - Question regarding an old ticket we have in the Public Website Team re #14073.pdf](https://github.com/department-of-veterans-affairs/va.gov-cms/files/14484038/IncomeLimitsApp.-.Question.regarding.an.old.ticket.we.have.in.the.Public.Website.Team.re.14073.pdf)
