### ISSUE TITLE
Footer F.E.: Ensure that any relative links (node references) in Drupal footer menu are rendered as absolute in injected footer

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#14071]
### User story

**AS A** PO/PM
**I WANT** the front-end template that builds the injected footer to protect against building relative URLs onto the wrong domain/subdomain, as they did in defect #14064
**SO THAT** this type of defect doesn't happen again.

### Engineering notes / background

See [bug ticket](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14064) for scenario and discussion.
- In that ticket, four links in the injected footer should have had `va.gov` as the root domain, but instead took the root domain of the site where the footer was injected
- To fix it, we changed the Drupal menu driving the footer to have those links be absolute instead of relative
- Per [Jill's comment](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14064#issuecomment-1589852466), we suspect that the problem was that these menu links used node references – a scenario which could happen again in the future, and we want to protect against

**Header code** that may be what we need: https://github.com/department-of-veterans-affairs/content-build/blob/524837be536013fc83717950408e1776d91ab713/src/site/stages/build/drupal/menus.js#LL12C1-L12C1

The "four links" from that defect on 6/13:
**Broken links:** 
* VA Outreach Events -- https://prod.cms.va.gov/admin/structure/menu/item/11570/edit?destination=/admin/structure/menu/manage/va-gov-footer
* VA forms -- https://prod.cms.va.gov/admin/structure/menu/item/11573/edit?destination=/admin/structure/menu/manage/va-gov-footer
* VA Outreach Materials -- https://prod.cms.va.gov/admin/structure/menu/item/11580/edit?destination=/admin/structure/menu/manage/va-gov-footer
* Your VA Welcome kit -- https://prod.cms.va.gov/admin/structure/menu/item/11581/edit?destination=/admin/structure/menu/manage/va-gov-footer

## Acceptance criteria

- [ ] Injected footer template
  - [ ] processes entity-reference (ie relative?) links like the header does, so that `va.gov/` links are rendered on the correct base url in injected sites
- [ ] On Drupal side, reverted the 4 links (see above) from the defect on 6/13 to be entity references again
- [ ] Confirmed in Prod that the 4 links render correctly in injected footer on benefits.va.gov

**Comment by randimays** [comment]
@dsasser helped me validate in Tugboat that the way the relative links (i.e. `/find-form`) were rendered in the DOM is like this:

<img width="400" alt="Screenshot 2023-07-14 at 3 20 44 PM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/19175324/f2329df4-dec8-4850-841d-d3459f419b5a">
<img width="350" alt="Screenshot 2023-07-14 at 3 20 36 PM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/19175324/408ddc9d-79a9-459e-bf87-f930185c6c84">


We added these links in different ways in Drupal:
1. Selecting a node for the URL input (`Find a VA form`)
2. Manually inputting a relative link (`/accessibility-at-va`)

The code I wrote was locally tested by cobbling together the Drupal data + a dummy link with a relative URL, and feeding that through the `convertLinkToAbsolute` utility that the header uses to properly format all the links. I tested this scenario locally in the injected footer, but there is no way to test it again as it moves through environments until it reaches prod. _So_ we will get it merged in Monday after the deploy, validate the regular scenario in staging (not injected), and cross our fingers as it goes to prod on Tuesday afternoon.

**Comment by randimays** [comment]
Slack thread for real-time updates for this ticket: https://dsva.slack.com/archives/C52CL1PKQ/p1689696116231259

We are prepared for a rollback after the prod deploy today if need be.

All links have been verified in staging (**not** the injected footer scenario, only regular staging.va.gov). Moving to Prod verification

**Comment by jilladams** [comment]
Verified in Prod! https://dsva.slack.com/archives/C52CL1PKQ/p1689721359615359?thread_ts=1689696116.231259&cid=C52CL1PKQ
