### ISSUE TITLE
Tim Knowledge Transfer

### ISSUE THREAD

**Issue by productmike** [department-of-veterans-affairs/va.gov-cms#14081]
## Description
Before Tim fully transitions from CMS Team to Accelerated Publishing team, would like to ensure we collectively can pickup the things he's been leading, so that we have a starting point in future work while being respectful of his bandwidth on his new team. 

## Acceptance Criteria
- [ ] Translations documentation has been stored and location identified in this ticket.
- [ ] Any content-build documentation, future ideas, etc. have been discussed (stored when appropriate) with Nate, Edmund, Tony.
- [ ] Any DevSecOps documentation, future ideas, etc. have been discussed (stored when appropriate) with Eric, Nate and Tolashe.
- [ ] Anything else that has been a labor of love during his CMS team reign has been discussed (stored when appropriate) with appropriate members of the team.
- [ ] Tim realizes how much we'll miss him, his witty, sometimes curmudgeon-like words yet always authentic self :)

**Comment by productmike** [comment]
@timcosgrove I think you've already been working on this, so likely duplicative in some regards. But as discussed last time, I'm not planning to assign you anything else during your remaining time on the CMS Team. Pretty much down to knowledge transfer and then fill in the gaps with CMS-urgent items/AP prep.

Any concerns, feedback with that approach?

**Comment by timcosgrove** [comment]
This sounds good. I'll start working on this.

Last AC might be kind of difficult, we'll see how it pans out.

**Comment by productmike** [comment]
@timcosgrove we can always push it to the AP board as well :)
