### ISSUE TITLE
Review release notes and upgrade Upgrade Address module in an integration branch

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#14083]
## Description
Upgrade Address module to version 2

This ticket is for part 1 of a three part series:
This ticket is to review the release notes and upgrade the module in an integration branch while determining exactly what additional changes need to happen (i.e. the facility migrations, graphql queries, front end templates, and any additional changes found after performing the upgrade).

## Subsequent work
Part 2. The back end changes along with any associated tests should be added to the integration branch (separate ticket that is populated with the findings of this ticket).
Part 3. The front end changes along with any associated tests should be added to the integration branch (another separate ticket that is populated with the findings of this ticket).

## Background
The [Address](https://www.drupal.org/project/address) module is inline to release a 2.0 version of the module.
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5752113/610d19d3-1ed7-41f6-8935-72067f924ec9)

Possible issues (just for advanced planning)

1. One of the updates to 2.0 is the addition of the address line 3.   (current version only has two)  In our facility migrations, lighthouse provides three lines of data and we concatenate the  lines 2 &3 to get them to fit into CMS line 2.    We would need to remove that concatenation from our facility migrations.
   - Changes would need to be made to the GraphQL queries and  FE templates
   - This change would need to be accounted for in our push to LH of Vet Center CAPs and VBA(? if we are source of truth by then)

## Acceptance Criteria
- [x] [Address module V2 release notes](https://www.drupal.org/project/address/releases/2.0.0) are reviewed.
- [x] Address module has been upgraded in an integration branch.
- [x] Additional back end ticket #17191 has been populated with the changes that need to be made.
- [x] Additional front end ticket #17193 has been populated with the changes that need to be made.

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [ ] `Public Websites`
- [x] `Facilities`
- [ ] `User support`

**Comment by swirtSJW** [comment]
This does not have to happen right away, and it should not happen until 2.0 becomes a stable and the maintainer recommended release.

**Comment by swirtSJW** [comment]
@xiongjaneg 2.0 has been released.  This is no longer blocked.

**Comment by xiongjaneg** [comment]
This could be timed along with the dependabot issue

**Comment by xiongjaneg** [comment]
pending discussion between Erika and Michelle on which team should own

**Comment by xiongjaneg** [comment]
Erika and Michelle agreed Facilities could take this on

**Comment by xiongjaneg** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Sitewide-Facilities-639f5253e4b702a32376339e/issues/department-of-veterans-affairs/va.gov-cms/14083?planning-poker) with Zenhub @omahane @Becapa

**Comment by xiongjaneg** [comment]
From Michelle: What is the impact to other teams (events?)? 
From Steve: For events, the front end needs to pick up address line 3. Will need some coordination with Public Websites.

@xiongjaneg Create a ticket and coordinate with Public Websites.

**Comment by xiongjaneg** [comment]
From Eli: VA.gov front end will need address line 3 updates all over. There may be a possibility to use a broader template.

**Comment by xiongjaneg** [comment]
See subsequent ticket #17191 affected teams reviewed and signed off
