### ISSUE TITLE
Published VBA facilities should be moved back to Draft

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-cms#14088]
## Issue description
New VBA editors inadvertently saved VBA facilities as "published", rather than "draft" when updated the operating status. (This can be seen by viewing the revision logs.) When the FE template is built in preparation for the MVP roll-out, these published status will create pages. 

Separately, we may want to update VBA editor permissions level to prevent them from accidentally publishing again but will want to confirm that they don't need publishing rights in other areas. 

[Link to CMS report](https://prod.cms.va.gov/admin/content/facilities?title=&type_op=in&type%5B%5D=vba_facility&moderation_state=editorial-published&workbench_access_section__section=All)

### Driving factor
We need to have these facilities back in Draft before re-training VBA Editors. Not yet scheduled.

## Tasks
- Use bulk edit to manually fix: https://prod.cms.va.gov/admin/content/bulk?title=&type=vba_facility&moderation_state=editorial-published&taxonomy_entity_index_tid_depth=All

## Acceptance criteria
- [x] VBA facility status is set to "Draft" for all facilities in advance of the FE template becoming available. 
- [x] Verify that VBA Facilities are still pushing status to Lighthouse

**Comment by mmiddaugh** [comment]
Per conversation with Swirt in Slack today
My question:  If we roll these back to "Draft", will they still push to Lighthouse?
Answer: They have to be archived, saved, then saved again as draft, and the draft change will send to lighthouse

If they get accidentally published, they should:
- Set the moderation state to "archived" and save the facility.
- Set the moderation state to "draft" and save the facility.
- All future saves should be as "draft".

**Comment by jilladams** [comment]
From refinement: 
* DaveP: This is a prime example of why workflow per content type would be helpful. 
    * Currently: The workflow applies to EVERY content type handling, and how they're allowed to be moved through the publishing flow. If we say: VBA editor role cannot publish, that would be applied to every content type, not just Operating Status. 
    * Roles / permissions cannot effectively manage this, in the context of the single workflow.
    * In the current implementation / single workflow: we think we could write custom code to manage display / hide of certain workflow options. 
    * A content publisher role: _could_ be used, but would need to be applied [...we would need to think more and it balloons roles, probably]
* To reiterate: CMS team does not prefer Workflow modifications. Previously when tried, it broke the main content view, because filtering by Draft / Published, etc. relies on Workflows. 
    * We would like to dive into what broke before

**Comment by jilladams** [comment]
@omahane I think you were around for the discussion of this in refinement -- I took a stab at testing my ability to knock it out on Staging and have a question. 

IIRC correctly, to move a Published VBA node back to Draft, we have to: 
* Unpublish (archive)
* Then Editors can draft a revision that can be later published.

Is that accurate? If so, when I tried using the bulk edit tool on staging to do it to a test node, I get a 200 error: 
![Screenshot 2023-07-25 at 4 14 12 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/85581471/78944d64-5ed0-4d82-a2d9-99826ff0d565)

**Comment by jilladams** [comment]
Dave to clarify for Jill with the question above.

**Comment by davidmpickett** [comment]
@omahane @swirtSJW I moved the VBA facilities that were published to archived and then to draft - can one of you confirm after the next content release?

**Comment by davidmpickett** [comment]
> Dave to clarify for Jill with the question above.

I have been unable to reproduce the error you saw @jilladams. Happy to watch over your shoulder / vice versa

**Comment by jilladams** [comment]
We have had several content releases since that comment, and facilities are showing as draft. https://prod.cms.va.gov/admin/content?title=&type=vba_facility&moderation_state=All&owner=All

I think my error was probably user error. Content to close.

**Comment by swirtSJW** [comment]
We should double check that these are still pushing to Lighthouse, because one of the checks for pushing is if it has been published in the past, it should not push for a draft change.
- never published -> draft  : should push
- published - > published : should push
- previously published -> draft : should not push (this is the risk in where we are right now) ... in this particular case, we want it to push.

**Comment by swirtSJW** [comment]
I validated that a facility moved to Published, then archived then back to draft will post status changes to the Post API queue
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5752113/3ecd347e-1a66-4728-9ff5-195b2a3fbb1f)
