### ISSUE TITLE
CMS user research: Conduct "low-key" usability sessions of para-w/-header ("magic header")

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#14095]
### User story

**AS A** PO/PM
**I WANT** a few editors of varying familiarity with Drupal to try using the "magic header" UI
**SO THAT** I can determine if any further work is required.

### notes / background

Suggested usability testing Editors:
- SW CAIA - Danielle T, other editor
- Michelle Middaugh
- Justin Warren (Justin.Warren@va.gov) from VA Digital Media (via Michelle M)

**Note:** Informal sessions don't preclude further usability testing with a larger group of editors if/when magic headers are rolled out in additional CMS locations, to a larger editor audience.

## Acceptance criteria

- [ ] Scheduled 3-4 sessions with VA editors of varying skill levels
- [ ] Conducted sessions per plan
- [ ] Documented high-level findings and recommendation on whether to launch or iterate

**Comment by jilladams** [comment]
@wesrowe to reach out to @cindymerrill for some informal ramp up before Cindy's PTO.

**Comment by wesrowe** [comment]
**Notes based on Cindy input:**

Provide background:
- What's this session about?
  - AR: look at CM convo guide for some language; not testing you, I won’t be offended, don’t - 
  - What’s the problem we’re trying to solve - context, not “all the beans”
- Be clear about process: (we’re not inviting you into the design process) We would like to get your feedback on something we’re working on. We have something to show you, we’d like to see if our concept works for you.
worry about doing it right.

Goal setting:
- For editors of different levels of familiarity with Drupal:
  - Determine whether the UI is usable (communicates depth/nesting), in both drag/drop and accessible modes
  - Does the help text provide enough context

Tasks - Give them something to do at a high level, see what they do – encourage them to think out loud
- First try from scratch
- Save - validate
- Try accessible/weights way to do it (accessible)

Ask follow-up questions, e.g.:
- What was easy
- What was challenging
- What would you change
- Which method would you choose, given the choice?

**Comment by cindymerrill** [comment]
@wesrowe Here are the standard questions I ask at the end of a research session:

- What worked well for you?
- What was unclear or didn’t work well for you?
- What would you like to change or add?

You can see them at the end of this [conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/regional-offices/research/2023-06-veteran-facing/conversation-guide.md) I wrote for the VBA usability testing. You can also use my wording from the Intro section about how we're not testing you, etc.

**Comment by wesrowe** [comment]
I had to punt hallway testing to after my PTO, now scheduled (due to others' calendars) for week of July 24.

**Comment by wesrowe** [comment]
Did last one today with Justin. Realizing now that synthesis needs to be its own ticket, per research practice. Will create.
