### ISSUE TITLE
Incorrect location guidance on system pages

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#14100]
## Describe the defect
When editing a system page, I see incorrect guidance about adding locations
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5752113/471249d2-704f-4fe4-876e-8d3f09379870)

## AC / Expected behavior
- [ ] I expect that guidance on the Locations list field set matches what is actually possible (does not direct editors to create a facility)
## Additional context
Add any other context about the problem here. Reach out to the Product Managers to determine if it should be escalated as critical (prevents users from accomplishing their work with no known workaround and needs to be addressed within 2 business days).

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Defect")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS workstream (orange) (not needed for bug tickets)
- [ ] CMS-supported product (black)

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [ ] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`

**Comment by mmiddaugh** [comment]
Closing in lieu of [#13896 [CONSIDER] Revisit logic governing "Other nearby VA locations" on VAMC pages](https://app.zenhub.com/workspaces/sitewide-facilities-639f5253e4b702a32376339e/issues/gh/department-of-veterans-affairs/va.gov-cms/13896)
