### ISSUE TITLE
Redirect Request: COVID boosters page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-cms#14104]
### Instructions
- Requests must be submitted **AT LEAST** 2 weeks in advance.  Some requests take a significant amount of time and coordination to implement, so start the process as soon as you know you will need one. 
- This issue will be used from initial request through implementation to ensure all individuals working on this are notified of status updates.  Please do not create multiple issues to track differnt steps.
- It is your responsibility to notify VA stakeholders as appropriate.  

### Type of request
- [x] We are retiring or taking down a page and need to redirect the URL (complete redirect section)
- [ ] We are changing the URL of an existing page (complete redirect section)
- [ ] We need a custom vanity URL (complete vanity URL section)

We are archiving the boosters page and redirecting it to our main covid vaccines page.

### Implementation date
When does this request need to be live?
Choose one:
- [ ] On a specific date, connected to a program or publishing requirement. **DATE:**
- [ ] Any day prior to a deadline/latest possible date. **DEADLINE:** 
- [ ] Any day after an earliest possible date. **EARLIEST DATE:**
- [ ] During a specific date range: ***EARLIEST DATE TO LATEST DATE:***
- [x] No hard timing requirements, publish when possible. We'd like this to get done as soon as possible but no hard deadline

### Redirects 
Current URL  |  Redirect Destination or New URL
---  |  ---
https://www.va.gov/health-care/covid-19-vaccine/booster-shots-and-additional-doses/ | https://www.va.gov/health-care/covid-19-vaccine/

### Vanity URLs 
Vanity URL  |  Landing page
---  |  ---
requested URL | landing page URL

**Link to campaign landing page request issue:**

### Process, Roles and Responsibilities
- [ ] Requesting team: Above information is provided
- [ ] Requesting team: All appropriate VA stakeholders are notified as appropriate
- [x] IA: Request is vetted and documented and implementation plan is clear 
- [x] IA: Request is assigned to appropriate team for implementation 
- [ ] Implementation team: Work is complete
- [ ] Implementation team: Validated in production
- [ ] Requesting team: Validates everything is correct in production and closes ticket

**Comment by chri5tia** [comment]
Fixed with https://github.com/department-of-veterans-affairs/devops/pull/13223

**Comment by randimays** [comment]
Tested this one in prod. It's good to close 👍

**Comment by RLHecht** [comment]
@jennymayoco We also needed to redirect the Spanish and Tagalog pages, which I never listed here.

Spanish page: https://www.va.gov/health-care/covid-19-vaccine-esp/booster-shots-and-additional-doses-esp/
Tagalog page: https://www.va.gov/health-care/covid-19-vaccine-tag/booster-shots-and-additional-doses-tag/

They need to redirect to the following:
Spanish: https://www.va.gov/health-care/covid-19-vaccine-esp/
Tagalog: https://www.va.gov/health-care/covid-19-vaccine-tag/

Would you be able to review these and let Jill know when they can be worked on? Thank you!

Would you be able to review these

**Comment by jilladams** [comment]
I think we should open a new ticket for those, since this is closed -- will help make sure we get everything through the workflow correctly.

**Comment by RLHecht** [comment]
No problem. I'll do that now.
