### ISSUE TITLE
Redirect Request: legacy compare education rates page to new R&S page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-cms#14119]
### Instructions
- Requests must be submitted **AT LEAST** 2 weeks in advance.  Some requests take a significant amount of time and coordination to implement, so start the process as soon as you know you will need one. 
- This issue will be used from initial request through implementation to ensure all individuals working on this are notified of status updates.  Please do not create multiple issues to track differnt steps.
- It is your responsibility to notify VA stakeholders as appropriate.  

### Type of request
- [x] We are retiring or taking down a page and need to redirect the URL (complete redirect section)
- [ ] We are changing the URL of an existing page (complete redirect section)
- [ ] We need a custom vanity URL (complete vanity URL section)

### Implementation date
When does this request need to be live?
Choose one:
- [ ] On a specific date, connected to a program or publishing requirement. **DATE:**
- [ ] Any day prior to a deadline/latest possible date. **DEADLINE:** 
- [ ] Any day after an earliest possible date. **EARLIEST DATE:**
- [ ] During a specific date range: ***EARLIEST DATE TO LATEST DATE:***
- [x] No hard timing requirements, publish when possible.

### Redirects 
Current URL  |  Redirect Destination or New URL
---  |  ---
https://www.benefits.va.gov/GIBILL/comparison_chart.asp | https://www.va.gov/resources/compare-va-education-benefits/ (edited by JM 6/20)

### Vanity URLs 
Vanity URL  |  Landing page
---  |  ---
requested URL | landing page URL

**Link to campaign landing page request issue:**

### Process, Roles and Responsibilities
- [ ] Requesting team: Above information is provided
- [ ] Requesting team: All appropriate VA stakeholders are notified as appropriate
- [x] IA: Request is vetted and documented and implementation plan is clear 
- [x] IA: Request is assigned to appropriate team for implementation 
- [ ] Implementation team: Work is complete
- [ ] Implementation team: Validated in production
- [ ] Requesting team: Validates everything is correct in production and closes ticket

**Comment by randimays** [comment]
@chri5tia I tested this one this morning and realized it should've gone in [vets-website](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/proxy-rewrite/redirects/crossDomainRedirects.json). Sorry for this oversight! I didn't realize it last week when I reviewed. We should remove it from `devops` and put it in `vets-website` instead. Good news though is that this should work after the prod deploy today.
CC @wesrowe @jilladams

**Comment by chri5tia** [comment]
This PR reverts the [previous work](https://github.com/department-of-veterans-affairs/devops/pull/13225) that should have gone in vets-website: https://github.com/department-of-veterans-affairs/devops/pull/13251

**Comment by chri5tia** [comment]
Does this need to be changed here?

**Comment by chri5tia** [comment]
Completed with https://github.com/department-of-veterans-affairs/vets-website/pull/24982
