### ISSUE TITLE
Change management for adding Abbreviation module in CKEditor 5

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#14114]
## Description
When we update to D10 and CKEditor 5, we will be adding a module to allow accessible abbreviations. We need to support our editors by making them aware of this new functionality and create new training materials to explain how to use this new module. 

### Notes
- Use [Change management template](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/new?assignees=&labels=Needs+refining&projects=&template=change-management-epic.md&title=Change+management+for+%3Cinsert+issue+name%3E) to create plan but scaled back
- Need to determine where would this will live forever. Perhaps there will be an interim place until Platform Confluence is finalized

## Acceptance Criteria
- [x] Create change management plan for editors
- [x] Create any training materials needed
- [x] PO/PM feedback and/or approval
- [x] Provide notification and awareness to Helpdesk

### Team
Please check the team(s) that will do this work.

- [x] `CMS Team`
- [ ] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`

**Comment by laflannery** [comment]
## Proposed change management plan

On the toolbar on the rich text editors in the CMS, we are adding an abbreviation function. When used, this will allow editors to add abbreviations to their content with proper semantic HTML markup.

This change is being done ...

This will impact all CMS Editors.

**Success metrics?**

**Knowledge base articles?**

This change will not be tested with users prior to launch.

This change will occur at the same time that the update to D10 and CKEditor 5 occurs.

**Comment by laflannery** [comment]
@EWashb Can you review the write up above as well as the updated KB and let me know your thoughts or anything I missed? Once this looks good I will add this to the GitHub documentation

**Comment by EWashb** [comment]
@laflannery I have this on the top of my to-do list for tomorrow!
