### ISSUE TITLE
Streamline editorial workflow roles so that they cascade 

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#1411]
## Background

![Add_user_-_WIP_–_Figma.png](https://images.zenhubusercontent.com/5d6e57ad330f64311395f08b/ec8dcd89-ead8-42ca-a69d-58f97217c3bf)

Most CMS users have one of three editorial workflow roles
1. Editor
2. Reviewer
3. Publisher

*Reviewer* role should be inclusive of *Editor* role, but should also be able to use the Approve transition (Draft to Approved). 

*Publisher* role should be inclusive of *Reviewer* role, but should also be able to Publish and Archive. 

## ACs 
- [ ] Permissions from Editor are also held by Reviewer
- [ ] Permissions from Reviewer are also head by Publisher
- [ ] Automated tests should exist to ensure that no user 
  - [ ] All permission held by Editor are also held by Reviewer and Publisher
  - [ ] All permissions held by Reviewer are also held by Publisher 
- [ ] ~Form validation to ensure that no user is given more than one of the three editorial workflow roles~ Removed for now
- [ ] ~Post release: existing CMS users are edited to ensure no user has more than one of the three editorial workflow roles~
- [ ] [Documentation](https://prod.cms.va.gov/help/cms-basics/roles-and-permissions) is updated 

## Implementation
- [ ] Permissions config 
- [ ] Automated tests.

**Comment by davidmpickett** [comment]
Our current [Content Moderation Roles](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/cms/content-governance/content-moderation-roles) reflect the desired permissions model
