### ISSUE TITLE
Review and publish updates to KB article: VBA facility operating status

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-cms#14134]
## Background context
**What is the request for?**
- [ ] Create new article
  - [ ] I have reviewed the Knowledge Base to confirm that an article for this topic does not already exist
- [x] Update existing article: [How do I update my VBA facility operating status?](https://prod.cms.va.gov/help/va-benefit-facilities-vba) 
**_Dave has already edited this article to remove the "Operating statuses during COVID" content. The article is ready to be reviewed and published._**

## If requesting a new article:
**Topic Description**
Details about the topic. If possible, include an example of a use case or situation that illustrates the topic well.
- [topic description]

**Audience**
Who is this intended for? Who would need this information? (i.e. All editors, only editors for a particular product, Internal use only, etc.)
- VBA editor

**Other related KB articles, if applicable:**
- [If you know that related KB articles already exist, link them here]

## Is the article associated with an ongoing product or feature update?
- [x] _Yes - associated with upcoming training_ 
- [ ] No

  
## Priority or deadline for request
Choose either Deadline or a priority:

- [x] Deadline: _before training_ 
- [ ] Priority:
  - [ ] Critical - Without this, there is a large negative impact on the majority of editors causing negative consequences within the CMS; Should be completed as soon as possible
  - [ ] High - Without this, there is negative impact on some editors causing negative consequences within the CMS; should be completed within the current sprint
  - [x] Medium - Without this, there is confusion for editors but not causing negative consequences within the CMS; Should be completed within the next 1-2 sprints
  - [ ] Low - This is not currently causing confusion for many editors but would be a nice to have or is something that may be more impactful in the future; Should be completed within the next 3-4 sprints

## Acceptance Criteria
- [ ] Article is created/updated using [KB content style guidelines](https://va-gov.atlassian.net/wiki/spaces/VAGOV/pages/1771831299/Knowledge+Base+content+style) and saved as a draft
- [ ] Impacts on other KB articles have been considered and any necessary changes have been made and saved as draft
- [ ] If necessary, add link to the new KB article in the [Content model document](https://prod.cms.va.gov/admin/structure/cm_document) for that content type 
- [ ] [Ticket for article review](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/new?assignees=&labels=Knowledge+Base%2C+Needs+refining&template=knowledge-base-article-review.md&title=Review+of+new+or+updated+KB+article+%3A+%3Cinsert+topic+here%3E) has been created

**Comment by mmiddaugh** [comment]
This article is ready for Help desk support and publication @kmariepat-cityfriends

**Comment by davidmpickett** [comment]
@mmiddaugh @jilladams Is the next step here review by CMS team/ help desk? Have they been flagged?

**Comment by jilladams** [comment]
^ Review ticket created (#14685). Closing.
