### ISSUE TITLE
CMS Out-of-Band Code Deployment for break fix

### ISSUE THREAD

**Issue by olivereri** [department-of-veterans-affairs/va.gov-cms#14146]
## Description
CMS has suffered a PIV logon outage. This issue tracks an out-of-band deployment to remediate the issue discussed [here](https://dsva.slack.com/archives/CT4GZBM8F/p1687527640024979).

## Acceptance Criteria
- [x] OOB Deployment Completes successfully.
- [x] Breaking issue resolved, PIV login restored.
- [ ] Postmortem written and reviewed.

## Implementation Details
[OOB Deploy Documentation](https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/READMES/devops/deploy-oob.md)

## Related issues
https://github.com/department-of-veterans-affairs/va.gov-cms/pull/14145

### Team
Please check the team(s) that will do this work.

- [x] `CMS Team`
- [ ] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`

**Comment by productmike** [comment]
@olivereri @ndouglas 
Can we update this ticket to include the post-mortem (https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Postmortems/2023/2023-6-23-CMS-PIV-Login-Failure.md) review as well?

**Comment by ndouglas** [comment]
Assigned Eric so he gets credit for his work here as well 🙂

**Comment by ndouglas** [comment]
[PR for OOB docs](https://github.com/department-of-veterans-affairs/va.gov-cms/pull/14151)
