### ISSUE TITLE
Add service push for Vet Centers

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#14149]
## User Story or Problem Statement

As a veteran I would like to see services offered through my local Vet Centers in the Facility locator so that I can best choose where I need to go.

## Acceptance Criteria
- [x] I expect that when Vet Center service updates are published, they will be sent to the Facility API, using the Post API method.
- [x] I expect that I can force push Vet Center Services through the UI as a separate option that pushing VAMC  services.
- [x] I expect updates are made to Content Model Documents  for the fields that we push to indicate that facility api is a consumer.

## Implementation notes

- Vet Center services are of slightly different structure than VAMCs because they do not have a System service that has to be collected.  So we should use a different method call to get the payload.

## Design principles

Veteran-centered
- [x] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [x] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

**Comment by jilladams** [comment]
Added to sprint 92, with understanding that this might not complete fully by end of sprint.

**Comment by omahane** [comment]
@mmiddaugh Our Vet Center service data will have a national description of the service that comes from the term in the VA Services taxonomy. The Vet Center section of the taxonomy has a description field that is currently filled in for all Vet Center services. This field will be the source for the `description_national` in the data we send. 

I want to know if we should expect that field to always be filled in for all Vet Center services. If so, we will have no need for a fallback data option for that field. Otherwise, we may need to consider using the VAMC description as a fallback. 

Personally, I would lean on Vet Center description and avoid using the VAMC description, as it sometimes differs a great deal, but that will only work if the Vet Center description is filled in. Do you expect that to always be the case?

![Screenshot 2023-09-01 at 7 30 19 AM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/766573/1bc8f563-c185-4690-a498-518ff891a564)

**Comment by swirtSJW** [comment]
I think description_facility  should actually just be description_system, but we should confer with lighthouse whether they want to add another property.  

I also wonder if we should be sending the facility info as the service location, contact info etc so that we round out the data the same way.  I think we have to bend the shape of this data to look like what we send for facilities.

**Comment by omahane** [comment]
After our discussion, here's the new structure:
```
{
  "nid": "3481",
  "uid": "facility_service_3738_3481",
  "endpoint_path": "/services/va_facilities/v0/facilities/vc_0512V/cms-overlay",
  "payload": {
    "detailed_services": [{
      "name": "Women Veteran care",
      "active": true,
      "description_national": "If you’re a woman Veteran transitioning to civilian life, we can help you find counseling, support, and referral services to meet your specific needs.",
      "description_facility": "\n <p>The Wasilla Vet Center proudly welcomes eligible female active duty service members and Veterans.&nbsp; We offer services in a sensitive and safe environment for counseling, therapy, support, and referral services to meet unique needs.</p> \n <p><strong>Calling all Women Veterans! We want to tailor services to your needs. Let us know if you'd be interested in joining a female Veteran support group, activity, social group, or fitness activity. We will be kicking off new programs and activities in the Fall!</strong></p> \n <p>We also work closely with the Women Veterans Health Program Manager and service providers at the Alaska VA Healthcare System and can make a direct referrals. For more information -&nbsp;<a href=\"/admin/content/linky/5274\">VA Alaska Health Care | Veterans Affairs</a></p> \n",
      "service_api_id": "womensHealth",
      "service_locations": [{
        "service_address": {
          "address_line1": "1751 E Gardner Way",
          "address_line2": null,
          "city": "Wasilla",
          "state": "AK",
          "zip_code": "99654",
          "country_code": "US"
        },
        "service_hours": {
          "monday": "08:00 a.m. to 04:30 p.m.",
          "tuesday": "08:00 a.m. to 04:30 p.m.",
          "wednesday": "08:00 a.m. to 04:30 p.m.",
          "thursday": "08:00 a.m. to 04:30 p.m.",
          "friday": "08:00 a.m. to 04:30 p.m.",
          "saturday": "",
          "sunday": ""
        },
        "phones": [{
          "type": "tel",
          "label": "Direct line",
          "number": "907-376-4318",
          "extension": null
        }]
      }]
    }]
  }
}
```

**Comment by swirtSJW** [comment]
Don't we want to keep it as description_system ?

**Comment by omahane** [comment]
> Don't we want to keep it as description_system ?

OK, now it's fixed.

**Comment by omahane** [comment]
I have updated the Content Model Documentation, but also found a bug that is preventing some additions: https://www.drupal.org/project/content_model_documentation/issues/3386794#comment-15227230

**Comment by omahane** [comment]
I am sending the Vet Center Facility Services to Lighthouse today, now that the code has been deployed.
