### ISSUE TITLE
Facility migrations failing

### ISSUE THREAD

**Issue by edmund-dunn** [department-of-veterans-affairs/va.gov-cms#14148]
## Description
This is the continuing saga of the strReplace migrate process. Caught it int he Jenkins logs. 
![CleanShot2023-06-23at10.41.53.jpg](https://images.zenhubusercontent.com/62e017d215adbc33b1310f7b/7406a459-2b97-4f61-b7ce-1e35f5ba9043)

## Acceptance Criteria
- [ ] All facilities migrations work correctly. 
- [ ] Submit patch to migrate_plus module

### Team
Please check the team(s) that will do this work.

- [x] `CMS Team`
- [ ] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`

**Comment by swirtSJW** [comment]
Connecting these two tickets for tracking https://www.drupal.org/project/migrate_plus/issues/3368310
