### ISSUE TITLE
Discharge Wizard: Navigating to /guidance or other deep form pages results in invalid form state

### ISSUE THREAD

**Issue by randimays** [department-of-veterans-affairs/va.gov-cms#14150]
### User story

**AS A** Veteran
**I WANT** to be prevented from deep-linking into the discharge wizard
**SO THAT** I do not get an invalid form state

### Engineering notes / background
![Screenshot 2023-06-23 at 11.49.52 AM.png](https://images.zenhubusercontent.com/642c5916aade1f575a2a6def/69474ea8-cf97-4f58-81cc-a0ba1ab5b7a0)

The main root of the application is `/discharge-upgrade-instructions`. If you try to navigate to `/discharge-upgrade-instructions/guidance`, the page loads, but with some bad data. 

From the screenshot above:
> ...send it to the Board for Correction of Naval Records (BCNR) for the **undefined**

It also seems strange that you can get to the guidance page without actually having filled out your information. We should guard against this.

## Acceptance criteria

- [ ] My attempt to deep-link into the `/guidance` route is re-routed to the start screen

**Comment by wesrowe** [comment]
@randimays, since you just did this deeplink protection for Income Limits, can you pre-refine this one too?

**Comment by chriskim2311** [comment]
Code is complete need verification on prod

**Comment by chriskim2311** [comment]
This has been verified on prod and redirecting as expected

**Comment by chriskim2311** [comment]
@wesrowe Good catch, For IL we don't render any info to the DOM unless we have the necessary data. There was no check for valid data for this wizard. I will add that logic in and merge this week.

**Comment by randimays** [comment]
@chriskim2311 I wondered about this when you put up your PR but wasn't sure. Typically the way we handle redirects is to use the `router.push` functionality (which requires an entry in `devops` to allow client-side routing). This may be a cleaner way to do the redirect that won't do the "flashing."

**Comment by wesrowe** [comment]
I validated that the flash has been fixed in the review instance
