### ISSUE TITLE
Spike: Determine sensible measurements for main platform components

### ISSUE THREAD

**Issue by productmike** [department-of-veterans-affairs/va.gov-cms#14165]
## User Story
As a PO, I want to know what the measurements of a healthy, optimized platform are, so that I can consistently determine the level of investment (if any) that is needed to maintain, improve those standards. 

## Acceptance Criteria
- [ ] Identify the primary components of the CMS platform incl. content build.
- [ ] Assess the current level of monitoring and measurements for each component. (A)
- [ ] Work with PM to determine the measurements needed for each. (B) 
- [ ] Develop iterative plan to go from A --> B.

**Comment by EWashb** [comment]
This seems very vague, and I'm unsure what the intention was here. Closing
