### ISSUE TITLE
[SPIKE] Communicate Drupal Governance

### ISSUE THREAD

**Issue by productmike** [department-of-veterans-affairs/va.gov-cms#14161]
## User Story
As a sitewide team member (Facilities or Public Websites), I want to have the expectations and ~~consequences~~ of interactions with the CMS scrum team to be articulated clearly (and documented accordingly), so that I can predictably complete any associated user stories.

As a platform, I want to be able to develop a set of standards, best practices around other teams building on the CMS, so that I can ensure there are appropriate controls around change management to maintain/improve:
- **Platform usability**: Reducing tedious tasks/toil, lowering wait times (merge to fail/success times), and reduce release related failures. Ease of CI use.

- **Platform reliability, availability and stability**: Protect Production uptime, reduce deployment failures, and fault tolerance

- **Platform observability**: Better ability to actively debug errors/failures. Awareness of user issues before it is raised. Ability to "observe" and react to novel issues or failures.

- **Security and vulnerabilities reduction**

## Acceptance Criteria
- [ ] Documentation created and logged in this ticket of CMS team interaction points within the SDLC (defined by component) -- including what those milestones are, why they are important/implications of not following and how folks are expected to interact with us to get our eyes on it. E.G. rules of engagement for anything pertaining to CMS platform.
- [ ] Define what types of PRs should be reviewed (e.g. all?; certain ones?)
- [ ] Articulate accepted exceptions (if any) to the criteria above.
- [ ] ~~Define actions taken by CMS team if criteria not followed and how folks will be notified.~~ define escalation points and process for remediation for our partner teams
- [ ] Review draft governance policy with PM and PO.

**Comment by EWashb** [comment]
"Consequences"?

I want to word that better. Let's avoid getting into a mindset of handing out consequences and repercussions to our trusted and valued partners. Yes, let's determine our governance policies and how we can communicate those to our partners in a clear and collaborative way. We won't always have it right and we want to encourage our teams to feel like they can provide us feedback

**Comment by EWashb** [comment]
I'm going to close this, but we can reopen if need be. I would like to rethink our approach to this work.
