### ISSUE TITLE
Staging Review for iOS App Promo Banner

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#14179]
## Description

- [x] Scheduled Staging Review 8/31
- [ ] Conducted Staging Review

**Comment by wesrowe** [comment]
Not likely to close this sprint – lower priority than Income Limits staging review (also in sprint).

**Comment by wesrowe** [comment]
meeting time wasn't available until 8/31. This will close next sprint.

**Comment by jilladams** [comment]
https://dsva.slack.com/archives/C52CL1PKQ/p1693498877101349
>  Staging Review collab cycle for the mobile app promo banner closed without findings. :tada:
