### ISSUE TITLE
Validate changes to str_replace in migration resulted in no data change

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#14189]
## Description
[This PR](https://github.com/department-of-veterans-affairs/va.gov-cms/pull/14159) went out to prod on 6/27/23 without validating that the data migrated in using the str_replace process plugin were resulting in the same values as they were before this change.
This affects the following migrations that are still being used (some other migrations are affected but we no longer use them):
- va_node_facility_nca
   -  field_link/uri
   - field_link/title
   - field_fax_number
   - field_phone_number
- va_node_facility_vba_db_extract
   - field_non_va_official_name
   -  field_non_va_location_url/uri
   - field_non_va_location_url/title
- va_node_facility_vba
   - field_phone_number*
- va_node_facility_vet_centers_mvc
   - non_field3_vet_center_parent
   - field_phone_number*
- va_node_facility_vet_centers_os
   - field_phone_number*
- va_node_facility_vet_centers
   - field_phone_number
- va_node_health_care_local_facility
   - field_phone_number*
   - field_mental_health_phone* (similar to field_phone_number)

* repeated field with same process pipeline, so testing the first instance should be enough.

## Acceptance Criteria
- [x] Migrations are run as update migration in tugboat with with an old database and code that predates the D10 breaking fix
- [x] Migrations are run as update migration in tugboat with current code
- [x] nodes from each type of migration are compared between the two tugboat instances to validate the data is the same.
- [x] Nodes containing NULL in the affected fields are checked between the two instances to validate data is the same.

**Comment by jilladams** [comment]
Talked about this with Steve. Notes:

- D10 contrib module update (which broke PIV auth) also broke VBA migrations
- Because of a PHP bump, changes the way str_replace function works
    - That str_replace function is used heavily in the str_replace plugin, which is used heavily in our migrations
    - Tests to verify if the migration runs without errors. BUT: that doesn’t confirm that, without errors, the data is actually correct.
    - The patch changes the behavior of a plugin that we use 16 times across 9 migrations. (8 Facilities, and 1 Public Websites)
    - This ticket spells out the migrations and fields that are affected by str_replace change.

**Comment by omahane** [comment]
@swirtSJW Comparing 
the month-old environment
https://main-1ouqufuiwhqohaqnvgjjoaidpjpensj4.demo.cms.va.gov/admin/structure/migrate/manage/facility/migrations/va_node_facility_nca/execute
to 
the day-old environment
https://vacms-13768-force-queue-vet-ce-4joeu71a92bqu3efkvsviral9glkk6xm.demo.cms.va.gov/admin/structure/migrate/manage/facility/migrations/va_node_facility_nca/execute

I notice immediately that we have something different happening during migration:
"The facility status info for {facility name} is being sent to the Facility Locator."

![Screenshot 2023-06-30 at 11 12 29 AM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/766573/1c3b2af2-718c-4217-928d-d8392332de0a)

**Comment by jilladams** [comment]
@omahane @swirtSJW what are the implications of sending that info to FL? Do we know?

**Comment by swirtSJW** [comment]
@omahane That is unrelated.   That was a shift I made a few weeks back just before I went on vacation.  We don't do all the checking to see if anything changed.  If it is a facility publish, we push.

**Comment by swirtSJW** [comment]
> @omahane @swirtSJW what are the implications of sending that info to FL? Do we know?

No worries.  That is no problem.

**Comment by swirtSJW** [comment]
@omahane  also the push of all changes from the migration is also a desired thing.
WHen we get a new facility from them, we immediately push it back to them so they will have an url for us being the source of truth.    If it is not published, we push the facility locator url,  if it is published we push a cms url.

**Comment by omahane** [comment]
# NCA
## Old (https://main-spvbjheoe12isfu1maky120fjrnm7ivg.demo.cms.va.gov/)
- Processed 2518 items (0 created, 192 updated, 0 failed, 2326 ignored) - done with 'va_node_facility_nca'
## New (https://vacms-13768-force-queue-vet-ce-4joeu71a92bqu3efkvsviral9glkk6xm.demo.cms.va.gov/)
- Processed 2518 items (0 created, 185 updated, 7 failed, 2326 ignored) - done with 'va_node_facility_nca'

## Failed
All the failed ones have null phone numbers

# VBA DB Extract
## Old (https://main-spvbjheoe12isfu1maky120fjrnm7ivg.demo.cms.va.gov/)
- Processed 450 items (0 created, 450 updated, 0 failed, 0 ignored) - done with 'va_node_facility_vba_db_extract'
## New (https://vacms-13768-force-queue-vet-ce-4joeu71a92bqu3efkvsviral9glkk6xm.demo.cms.va.gov/)
- Processed 450 items (0 created, 450 updated, 0 failed, 0 ignored) - done with 'va_node_facility_vba_db_extract'

# VBA 
## Old (https://main-spvbjheoe12isfu1maky120fjrnm7ivg.demo.cms.va.gov/)
- Processed 2518 items (0 created, 452 updated, 0 failed, 2066 ignored) - done with 'va_node_facility_vba'
## New (https://vacms-13768-force-queue-vet-ce-4joeu71a92bqu3efkvsviral9glkk6xm.demo.cms.va.gov/)
- Processed 2518 items (0 created, 450 updated, 2 failed, 2066 ignored) - done with 'va_node_facility_vba'

## Failed
- Veteran Readiness and Employment Office at Oceanside VA Clinic
- Veteran Readiness and Employment Office at San Marcos Vet Center
- Both have null phone numbers

_Note: 
The numbers with extensions are a problem, but not a new one:
https://vacms-13768-force-queue-vet-ce-4joeu71a92bqu3efkvsviral9glkk6xm.demo.cms.va.gov/node/3954/edit
https://main-spvbjheoe12isfu1maky120fjrnm7ivg.demo.cms.va.gov/node/3954/edit
phone number is the same:_ 
`631-261-4400, e xt. 7192`
vs
`631-261-4400, ext. 7192`
in API

# VAMC
## Old (https://main-spvbjheoe12isfu1maky120fjrnm7ivg.demo.cms.va.gov/)
- Processed 2518 items (1 created, 1324 updated, 0 failed, 1193 ignored) - done with 'va_node_health_care_local_facility'
## New (https://vacms-13768-force-queue-vet-ce-4joeu71a92bqu3efkvsviral9glkk6xm.demo.cms.va.gov/)
- Processed 2518 items (0 created, 1324 updated, 1 failed, 1193 ignored) - done with 'va_node_health_care_local_facility'

## Failed
- Tyler Broadway VA Clinic
- Has a null phone number in the Facilities API

**Comment by swirtSJW** [comment]
This part is curious.  In testing done on #14159 it shows no fails on VBA
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5752113/b5fe371d-43ec-4043-a75d-ec9e21c5b940)


Anyway I updated the upstream issue to clarify the situation
https://www.drupal.org/project/migrate_plus/issues/3368310

**Comment by swirtSJW** [comment]
I believe this ticket is complete.  Nice  work @omahane you surfaced the defect.  We will have to spin the solution into another ticket

@jilladams  and @kmariepat-cityfriends  To summarize,  This is not a data corruption issue, think of it more like a data blockage.  There are a handful of facilities that have no phone number and when there is an upstream change to one of those, those particular facilities will not be updated in the CMS because their particular migration fails.     This is roughly 10 out of 2500 facilities (0.4%).  It is a small number but I think we should still prioritize it for next sprint. 

When we fix this, the blockages will be cleared and we will be in sync with the data in the Facility API.

**Comment by swirtSJW** [comment]
Based on @omahane's finding with the ext. become e xt.  I created https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14238

**Comment by omahane** [comment]
> This part is curious. In testing done on #14159 it shows no fails on VBA ![image](https://user-images.githubusercontent.com/5752113/250205526-b5fe371d-43ec-4043-a75d-ec9e21c5b940.png)
> 
> Anyway I updated the upstream issue to clarify the situation https://www.drupal.org/project/migrate_plus/issues/3368310#comment-15132328

That is odd. I did check my branch from which I built the preview, and it definitely has [the commit](https://github.com/department-of-veterans-affairs/va.gov-cms/commit/2d64b1115b217c6d90aacdb773f9b93d82531bc2) of the merge that was made to fix the migration a few days ago.

**Comment by jilladams** [comment]
Confirming: this was a discovery-ish/ fact finding ticket, closing.
