### ISSUE TITLE
Gather data | Develop hypothesis to improve the KB product

### ISSUE THREAD

**Issue by productmike** [department-of-veterans-affairs/va.gov-cms#14195]
## User Story
As an editor, I want the knowledge-base self-serve to be contextual to my needs, so that I can DIY the top 80% of my issues with a positive experience. 

## ACs
- [ ] Review persona(s) of the primary KB user. 
- [ ] Review helpdesk input on user actions -- specifically heat map; traffic in/traffic out pages (anecdotally)

**Comment by BerniXiongA6** [comment]
Hey @joagnitti can we close / delete this since we've replaced it?

**Comment by joagnitti** [comment]
@BerniXiongA6 Works for me!

**Comment by BerniXiongA6** [comment]
Closing since this work is being captured on new tickets, particularly [#15246](https://app.zenhub.com/workspaces/vagov-cms-team-5c0e7b864b5806bc2bfc2087/issues/gh/department-of-veterans-affairs/va.gov-cms/15246)
