### ISSUE TITLE
I.L. FE: Add spinner to Submit and Zip validation actions while awaiting API response

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#14200]
### User story

**AS A** Veteran
**I WANT** to see a loading indicator while I'm waiting on an API response after clicking "Continue"
**SO THAT** I know the app is working on my request.

This needs to be implemented for BOTH steps where the app hits the API:
- Zip code screen
- Review info screen

### Engineering notes / background

The VADS provides a [loading indicator component](https://design.va.gov/components/loading-indicator). 

The component is configurable, see [Storybook](https://design.va.gov/storybook/?path=/docs/components-va-loading-indicator--default).

### Design

We will implement the same pattern as the health care application:
<img width="547" alt="loading indicator example" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/104526584/ae1fd393-61a5-402d-a807-bb2ec7325deb">

Text displayed beneath the spinner is the same as above, "Reviewing your information..." 

Also copy their pattern how other component parameters should be set: aria-label, set-focus.

## Acceptance criteria

- [x] Loading indicator replaces the buttons (continue and back) on the Review Info page after Continue is clicked, until the API response returns, per design
- [x] Loading indicator replaces the buttons (continue and back) on the Zip code page after Continue is clicked, until the API response returns, per design
- [x] Text under spinner is "Reviewing your information..." on both pages
- [x] Aria-label and focus parameters set per a11y recommendation on both pages
- [ ] Design and Product reviewed
- [x] A11y reviewed

**Comment by thejordanwood** [comment]
- The loading indicator should display inbetween pages. For example, if the Continue button is selected on the Zip Code screen, then a white screen with the  indicator should appear while loading the dependent page. This video shows what I mean (Sorry the loading indicator screen is a bit fast. I can't figure out how to adjust the play speed.). 
- The copy on this should be "Please wait while we load the application for you."


https://github.com/department-of-veterans-affairs/va.gov-cms/assets/104526584/e119babd-e7ba-421b-b076-85869ffe6513

**Comment by wesrowe** [comment]
@thejordanwood, I worry that calling it an "application" could be confusing in the I.L. scenario for a couple reasons: 
- The Veteran is filling out a form, not requesting an application. (And probably wouldn't use the word "application" to describe what they're doing anyway...?)
- If the API sends an error back they'll be returned to the previous screen. I think that would be less confusing if it were visible the whole time.

**Comment by thejordanwood** [comment]
@wesrowe Okay, then maybe we can do something like the health care application does. Once the continue button is selected, there is a loading indicator that takes the place of the button. Our copy can also say "Reviewing your information..." 

<img width="547" alt="loading indicator example" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/104526584/ae1fd393-61a5-402d-a807-bb2ec7325deb">

**Comment by wesrowe** [comment]
Thank you for finding this - that seems like a good pattern

**Comment by thejordanwood** [comment]
I like it much better than the first example I found!

**Comment by randimays** [comment]
Screenshots of the final product and notes here: https://docs.google.com/document/d/1ubN8B0mWys5cnHome0FU7d85Xmg1NXOE1toAPtMDa3A/edit?usp=sharing

**Comment by randimays** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/24771/

Loom walkthrough of code only: https://www.loom.com/share/d41d14149abf4f189c9d6f40d22573d7?sid=c2b474e6-7f88-492b-bcfb-6f713a803b8c

**Comment by randimays** [comment]
This has accessibility, design and engineering approval. PR is ready to merge after @wesrowe gives us the green light. Slack thread for all the details: https://dsva.slack.com/archives/C52CL1PKQ/p1688676450644809

**Comment by wesrowe** [comment]
The google doc was really really helpful. Approved!

**Comment by randimays** [comment]
Verified in staging. Closing!
