### ISSUE TITLE
Push mental health phone number field to lighthouse with the status push.

### ISSUE THREAD

**Issue by kmariepat-cityfriends** [department-of-veterans-affairs/va.gov-cms#14215]
Note that we cannot merge and perform the push outlined in the below AC until Lighthouse is ready to accept.  PRs for this should be against the integration-mental-health-phone branch.

- [x] I expect that the mental health phone number field is pushed to lighthouse with the status push
   - [x] If the mental_health_contact_phone is populated, send that.
   - [x] If it is not populated send  field_mental_health_phone  (this field will be slated for removal after full compliance with populating mental_health_contact_phone has been achieved.
- [ ] ~I expect the content model documentation is updated to show that it's a push and not a pull~ Moved to https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15576 because it can't be documented until it lands on prod.

**Comment by jilladams** [comment]
VHA DM needs to buy into options outlined in #. Then we will work with Lighthouse to define the shape of the data push.

**Comment by mmiddaugh** [comment]
This is blocked pending Changes to existing field field_mental_health_phone on VAMC facilities, change management and final signoff by OMHSP
