### ISSUE TITLE
Update KB article to reflect mental health phone number changes

### ISSUE THREAD

**Issue by kmariepat-cityfriends** [department-of-veterans-affairs/va.gov-cms#14217]
- [ ] KB articles are updated with draft revision
    - [ ] https://prod.cms.va.gov/help/vamc/how-do-i-update-my-vamc-facilitys-basic-location-data
    - [ ] https://prod.cms.va.gov/help/vet-centers/how-do-i-update-my-vet-center-facilitys-basic-location-data - TBD scope around Vet Center mental health numbers
- [ ] Helpdesk intake request has been filed for KB article review: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/new?assignees=&labels=Knowledge+Base%2C+Needs+refining&projects=&template=knowledge-base-article-review.md&title=Review+of+new+or+updated+KB+article+%3A+%3Cinsert+topic+here%3E
    - [ ] If revision must be published by a specific date, indicate in the ticket

**Comment by mmiddaugh** [comment]
closing this in favor of the templated request #15683
