### ISSUE TITLE
Changes to existing field field_mental_health_phone on VAMC facilities 

### ISSUE THREAD

**Issue by kmariepat-cityfriends** [department-of-veterans-affairs/va.gov-cms#14213]
**Acceptance Criteria based on option 1** 
- [x] Make the existing field field_mental_health_phone on VAMC facilities editable by moving it out of the existing field set 
- [x] I expect on node view to move the field to a matching grouping 
- [x] I expect this field has help text (work with @thejordanwood and @mmiddaugh to determine copy)
- [x] Remove it from the migration (either keep the existing values)
- [x] I expect the [content model documentation is updated](https://prod.cms.va.gov/admin/structure/types/manage/health_care_local_facility/fields/node.health_care_local_facility.field_mental_health_phone/document) 

---

### Solution
 - Make the existing field `field_mental_health_phone` on VAMC facilities editable.
 - Remove it from the migration _(and either keep the existing values or blank them out)_
 - Push that field to lighthouse with the status push.
 - Does this field need to be required?

### Pros 
* Lowest lift
* No FE change needed
* No CMS content model change needed
* Single point of failure, editor not entering a value.

### Cons
* No comprehensive fallback if there is no number specified at the facility level.
* Data is not riding where it makes the most sense.  Mental Health number is a number for a **service**, so making it a property of a **facility** seems misplaced.

### Possible enhancements

- Add a Clinical contact center field to each VAMC System that could be used as a fallback.
- Make Mental Health facility service pull from this field on the facility rather than the main phone number.

### Solution

- Leverage "VA Health Connect phone" field to VAMC System content type since this number is a VISN level thing and that is as high up the existing chain as we can get it (or maybe this gets added to System Service?) .
- Add "primary phone" field to VAMC Facility Service content type
- When sending to lighthouse we send the Mental Health phone number based on this priority order
   - Primary phone from from Facility Mental Health Service.
   - Mental health number from the Facility
   - Clinical number from System (or system service)
-  This would definitely need changes to GraphQL queries and FE templates

### Pros
   - Flexible for all variations of system and local overrides
   - Connects the number with the related service rather than off on its own at the Facility or System node.
   - Immediately extensible for any existing services (ie. Oncology hotline, Patient Advocates hotline ...) It would be there in case we needed it.
   - Redundant fall backs

### Cons
   - Largest level of effort
   - Fallbacks are not transparent to editors (it resembles magic)
   - More points of failure due to complexity.
   - More difficult set of steps for editors to carry out this change.

**Comment by davidmpickett** [comment]
I updated the body of the card to include the full text of both options @swirtSJW wrote up in #13785. Based on conversations with VHA DM today, probably good to have both on the table

**Comment by mmiddaugh** [comment]
Can we simplify even more to this?
-> If mental health service exists, prepopulate the field with the phone number from the first service location in Mental health and make it editable.
-> If mental health service does not exist, prepopulate the field with the system mental health number and make it editable. (In the event there are two medical centers, choose one and make it editable).

We will want to consider what label to use when the system number appears so that Veterans understand they are calling a different medical center

**Comment by swirtSJW** [comment]
@xiongjaneg  I think this needs some post-finement because the AC's have not been updated since Kamari put them in on June 29 and I think are plans were not finalized at the time.

**Comment by xiongjaneg** [comment]
@swirtSJW Do you have enough info to make those updates or do we need a product meeting?

**Comment by xiongjaneg** [comment]
From 16th minutes:
- Could put in integration branch until change management and Lighthouse are ready
- Field where the number is automatically displayed is editable by editors
- There is a field that is editable for editors to indicate where the custom phone number goes to (may be blank so that it doesn't display if an editor hasn't added text here)
- What's the fallback number? The Main system phone number?
- How to handle it in the service is outside the scope of this ticket.
- Changing the label on the front end is out of scope of this ticket.

Michelle and Jane will talk to VHA DM about a default system number in addition to the editable field.

**Comment by swirtSJW** [comment]
@thejordanwood and @mmiddaugh I need you guidance on what the text guidance for editors should see for this field.

It probably needs to be more than "Enter the phone number for mental health that gets answered by a human."  but I imagine the language needs to be more official.

**Comment by mmiddaugh** [comment]
I'd suggest something like this (assuming character limitation is not an issue)

> Please enter the number which Veterans should call to access mental health at your facility. If your facility does not offer mental health services, please enter the most appropriate system number.

I don't think it needs to reference federal law.

**Comment by davidmpickett** [comment]
- Enter the direct phone number for the mental health department at your facility
- Do not repeat the main phone number for your facility
- Leave this blank if your facility does not have mental health services
- This number will be displayed everywhere your facility appears across VA.gov ([read more](https://prod.cms.va.gov/help/va-medical-centers-vamcs/about-locations-content-for-vamcs/how-to-edit-a-vamc-facility))

**Comment by swirtSJW** [comment]
@davidmpickett    @mmiddaugh Can we say "Leave this blank if your facility does not have mental health services"   When this should be required and we are just not making it required to prevent them having to put in jibberish if they don't know?

I also have some concerns about saying don't repeat your main number.   If the main number is the right place and they don't put it  then the output on the FE will have no mental health number displayed and we fail the mandate.

**Comment by mmiddaugh** [comment]
If the editor knows a number they'd like to direct Veterans to use, they should be able to enter it - I don't want to discourage that.
I like Dave's suggestion about source of truth and linking to more information.

> Please enter the number which Veterans should call to access mental health at your facility. If your facility does not offer mental health services, please enter the most appropriate system number. This number will be displayed everywhere your facility appears across VA.gov ([read more](https://prod.cms.va.gov/help/va-medical-centers-vamcs/about-locations-content-for-vamcs/how-to-edit-a-vamc-facility))

@xiongjaneg and I will get signoff from VHA DM early next week

**Comment by thejordanwood** [comment]
@mmiddaugh My suggestion would be to remove the word "please." Help text in the CMS is usually a bit more direct so removing that would make it more consistent. For accessibility purposes, the link should also say where this is linking off to.

> Enter the number Veterans should call to access mental health services at your facility. If your facility doesn't offer these services, enter the most appropriate system number. This number will be displayed everywhere your facility appears across VA.gov. ([View guidelines for editing VAMC facilities](https://prod.cms.va.gov/help/va-medical-centers-vamcs/about-locations-content-for-vamcs/how-to-edit-a-vamc-facility))

**Comment by mmiddaugh** [comment]
awesome improvements, @thejordanwood - thank you!!

**Comment by swirtSJW** [comment]
Here it is in place.  
VACMS-14213-make-mental-health-source-of-truth
It links to the article and opens in a new tab following the example from other places in our system where help text links out.  

@laflannery I looked in our codebase and we only have two indications when something opens in a new tab  but I wasn't sure what we want as a standard.

Vet center: text in parentheses in the link
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5752113/baa307fa-02dc-47e2-994f-4358869e6d06)
Covid Supplemental status (which is hidden right now)  uses the text "opens in a new window"  which I think is misleading anyway.
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5752113/139ca5e4-d29f-43a7-b680-9fb3ce712d49)

@BlakeOrgan @thejordanwood @laflannery 
Given that Jordan's example is already in parentheses I am wondering if we need to do something different, or remove the parentheses around the link.  I looked for quidance from existing patterns and out of 41 links in help text, we have 20 that are in parentheses and 21 that are not.

**Comment by laflannery** [comment]
I'm assuming this is a KB article link? In that case, my vote is for B, I don't like double parentheses. If for some reason this is not linking to a KB article let me know

**Comment by thejordanwood** [comment]
My vote is also B. We can use this as an opportunity to start aligning with the [VA content style guide](https://design.va.gov/content-style-guide/links), which doesn't put parentheses around links. I'll write them without parenthesis going forward!

**Comment by BlakeOrgan** [comment]
Agreed, I also think we should use B.

**Comment by swirtSJW** [comment]
All of the of the other work on this will be PRs against the integration branch "integration-mental-health-phone" since it can not go directly to main.

**Comment by swirtSJW** [comment]
I created [this ticket to update the KB to address mental health numbers](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15574) since we are linking to it in the help text.

**Comment by jilladams** [comment]
@swirtSJW @xiongjaneg integration branches are easy to lose track of, so made a ticket to track the branch merging to main: #15576

**Comment by swirtSJW** [comment]
Updated the [Integration branch pr](https://github.com/department-of-veterans-affairs/va.gov-cms/pull/15585) to reference the tracking ticket Jill created ^^

**Comment by swirtSJW** [comment]
The work for this ticket is complete and can be closed.
