### ISSUE TITLE
Update phone numbers report under content audit tools 

### ISSUE THREAD

**Issue by kmariepat-cityfriends** [department-of-veterans-affairs/va.gov-cms#14214]
## Description
As a maintainer of  the content shift to VAMC editors being the source of truth for VACM mental health phones, I need a way to compare how that shift is progressing.   

## Acceptance Criteria 
On this View https://prod.cms.va.gov/admin/content/audit/phone-numbers   **Note:** This is on an integration branch and can not go to prod but it can be seen here https://pr15585-t4rxipfvixmstnbanwuh6xefo7lygqaj.ci.cms.va.gov/admin/content/audit/phone-numbers 
- [x]  Adjacent to the VAMC mental health phone number, add field mental-health-contact-phon
- [x] Columns  should be sortable

**Comment by swirtSJW** [comment]
Similiar but related to https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14721

**Comment by jilladams** [comment]
Merged to integration branch. 
Integration branch merge to main will be tracked in https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15576. 
Closing. FYI @xiongjaneg
