### ISSUE TITLE
I.L. FE: "+10%" calculation always rounds up to next dollar

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#14221]
### User story

**AS A** Veteran
**I WANT** the +10% calculation to always round up to the next dollar
**SO THAT** it's consistent with VES calculations and gives me the most generous limit.

### Quality / testing notes

**Test cases**

GMT always seem to end in zero, so no rounding needed. But NMT can end in any digit, so test this case using the Jonesboro case (NMT > GMT; zip 72401). 

E.g., for 2019 limits (2018 income year) and zero dependents, NMT was $33,632.
- 110% of that using conventional rounding would yield $36,995 as the top of the third accordion.
- the actual correct, rounded-up figure is $36,996.

## Acceptance criteria

- [x] "+10%" calculation for top income limit (aka relaxation threshold) always rounds up to next dollar

**Comment by wesrowe** [comment]
I was happy with the loom and Jonesboro tests that Randi tried locally. Can close when it's validated post-merge in Staging.

**Comment by randimays** [comment]
Loom walkthrough: https://www.loom.com/share/416b12210939416986d2a45c65df00c2?sid=54e495b5-c268-48d6-b4a9-1b813c0155b5

Slack context: https://dsva.slack.com/archives/C52CL1PKQ/p1688419343891789

**Comment by randimays** [comment]
@wesrowe Do you want to validate again in staging? I checked the values there and it's looking good.

**Comment by wesrowe** [comment]
got the value expected in staging for test case in ticket body! closing
