### ISSUE TITLE
VA Asheville Displays Duplicate Locations, pointing to different pages

### ISSUE THREAD

**Issue by TroyA6** [department-of-veterans-affairs/va.gov-cms#14224]
## Describe the defect
The VA Asheville health care site Locations page displays VA locations - each location is displayed twice. - once at the top of the page in the 'Main locations' and 'Health clinic locations' sections, and again in the 'Other nearby VA locations' section.

There are two items of concern: 
1. The locations should not be displayed twice
2. The second set of locations point to the 'placeholder' page for each of the locations

It is worth noting that the locations listed in the 'Main locations' and 'Health clinic locations' sections point to current, updated, modern pages.

## To Reproduce
1. Go to '[https://www.va.gov/asheville-health-care/locations/](https://www.va.gov/asheville-health-care/locations/)'
4. Scroll down the page to see that all five locations are duplicated toward the bottom of the page in the 'Other nearby VA locations' section.
5. Click on ANY of the five listed under 'Other nearby VA locations'
6. See error - the 'placeholder' page

## AC / Expected behavior
1. The locations should not be displayed twice
2. The second set of locations point to the 'placeholder' page for each of the locations

### Other VA Locations links - which point to 'placeholder' pages...
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/108767736/69b1fddf-98d7-45ce-b4a5-3a3b0dca5f88)

### Example of a 'placeholder' page
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/108767736/a3e49ed6-fe9c-48cb-9995-c91631146ba4)

 ## Additional context
Editing the 'locations' page does not allow the removal of the 'Other VA locations' section - it is not accessible to edit or remove.
Associated JIRA ticket [VAHELP-5986](https://va-gov.atlassian.net/jira/servicedesk/projects/VAHELP/queues/custom/12/VAHELP-5986)

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Defect")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS workstream (orange) (not needed for bug tickets)
- [ ] CMS-supported product (black)

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [ ] `Public Websites`
- [x] `Facilities`
- [ ] `User support`

[VAHELP-5986]: https://va-gov.atlassian.net/browse/VAHELP-5986?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by TroyA6** [comment]
Please let me know if I need to redirect, or classify as something other than Defect.

**Comment by stefaniefgray** [comment]
Removed duplicate locations -- https://www.va.gov/asheville-health-care/locations/

Need to re-check in the morning to see if workaround (deleting VHA_### codes) worked

**Comment by xiongjaneg** [comment]
Verified "Other nearby VA locations" is no longer displayed and locations are only displayed once 
<img width="847" alt="Screenshot 2023-08-18 at 3 01 41 PM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/73648238/122751f0-1bc2-403b-836c-f32fdda202e7">
