### ISSUE TITLE
Fix str_replace process plugin patch

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#14237]
## Describe the defect
A patch was created as part of https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14148
that changed a noisy Migration stopping failure into a rather silent data blockage for ~10 facilities.
The failure and the scope of it were determined here https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14189

The patch in the upstream issue needs to be reworked as described in this comment upstream
https://www.drupal.org/project/migrate_plus/issues/3368310#comment-15132328

## AC / Expected behavior
- [ ] I expect that when each of our facility migrations are run as update migrations, there are no failures identified.
- [ ] I expect that the data the we save in the CMS from the migration matches the data we stored before 14148 and before the php upgrade that broke the migration in a noisy way.

**Comment by omahane** [comment]
@edmund-dunn From [this comment](https://www.drupal.org/project/migrate_plus/issues/3368310#comment-15137635), it sounds like you plan to work on this. I spent a bit of time, but you may have a better solution than this.
```
 /**
   * Makes a string of a value (if possible)
   *
   * @param string $possible_string
   *   A value to be converted to a string if possible.
   *
   */
  public function makeStringIfPossible($possible_string) {
    if (is_null($possible_string)) {
      return '';
    }
    elseif ($possible_string === FALSE) {
      return '';
    }
    elseif ($possible_string === TRUE) {
      return '1';
    }
    elseif (is_numeric($possible_string)) {
      return strval($possible_string);
    }
    else {
      return $possible_string;
    }
  }
```

I was calling it on line 126ff:
```
 public function transform($value, MigrateExecutableInterface $migrate_executable, Row $row, $destination_property) {
    $this->multiple = is_array($value);
    // Need to replicate the old functionality
    // per https://www.drupal.org/project/migrate_plus/issues/3368310#comment-15132328
    $value = $this->makeStringIfPossible($value);
    if (!$this->multiple && !is_string($value)) {
      return $value;
    }
```

and around 164ff:
```
  if($this->multiple) {
      foreach($value as $key => $item) {
        $item = $this->makeStringIfPossible($item);
        if (is_string($item)) {
          $value[$key] = $function($config['search'], $config['replace'], $item);
        } else {
          $value[$key] = $item;
        }
      }
      return $value;
    }
```

**Comment by omahane** [comment]
@edmund-dunn is going to be working this, as discussed here: https://dsva.slack.com/archives/CT4GZBM8F/p1688582578256239

**Comment by omahane** [comment]
I'm testing the patch now.

**Comment by omahane** [comment]
I have tested the patch @edmund-dunn made and commented on the upstream here: [Comment#14](https://www.drupal.org/project/migrate_plus/issues/3368310#comment-15141784)
