### ISSUE TITLE
Troubleshoot Site Alert Dismissable Banner Defect

### ISSUE THREAD

**Issue by EWashb** [department-of-veterans-affairs/va.gov-cms#14243]
## Describe the defect
Sitewide Alerts were configured to be dismissible (in #9723) but they are no longer able to be dismissed as intended. The alerts are stacking and we should be providing the "X" to remove from view. 

## To Reproduce
1. Go to any CMS page. 
2. See error below. 

## AC / Expected behavior
There should be an "X" on the right side of the alert that allows it to be dismissed. 

## Screenshots
![image.png](https://images.zenhubusercontent.com/614b6cbe05afafb268be4c0b/850698a1-1e07-4410-9b24-3210a93371b0)If applicable, add screenshots to help explain your problem.

 ## Additional context
Alerts stacked are against our UX design principles and VA Style Guide. 

## Desktop (please complete the following information if relevant, or delete)
 - Browser: Chrome

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Defect")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS workstream (orange) (not needed for bug tickets)
- [ ] CMS-supported product (black)

### Team
Please check the team(s) that will do this work.

- [X] `CMS Team`
- [ ] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`

**Comment by productmike** [comment]
@edmund-dunn Let's earmark this for S88 planning. We'll have to story point on the fly, but this is a key UX thing I don't want to let hang. Even if we have to distill down to just discovery for now. Let's chat on this Wednesday morning!

**Comment by ndouglas** [comment]
![Screenshot 2023-07-05 at 11 23 10 AM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/1318579/670ec16c-0176-40a2-ae69-68d1ccde6b98)

Looks like the checkbox to make the alert dismissable isn't checked. I assume (though I haven't checked) that if that were checked, the alert would be dismissable.

Do we want to enforce that all alerts are dismissable? Make them dismissable by default?

**Comment by ndouglas** [comment]
Closed in favor of #14266.
