### ISSUE TITLE
Create VAMC Banner Audit View

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#14247]
## Description
As a mainainer of the VAMC product, I need to be able to see what VAMC banners are published or unpublished.

They appear in other Views, but those rely on filtering by moderation state and VAMC banners do not have a moderation state.

## Acceptance Criteria
- [ ] View restricted to just VAMC banners
- [ ] Present in the Facility collection of Views
- [x] Can filter and sort by published, unpublished
- [ ] show last updated date

**Comment by swirtSJW** [comment]
It turns out [we have a View that gets us 98% there](https://prod.cms.va.gov/admin/content/vamc-alerts-and-statuses).  It is hiding possibly in the wrong spot.  
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5752113/659bd3aa-9e8e-479a-b7ea-59971214dd8c)



The missing 2% is that you could not filter by the published status of the items.  So I added a filter so you could.

**Comment by jilladams** [comment]
@swirtSJW based on your comment, is this ticket actually close-able?

**Comment by swirtSJW** [comment]
@jilladams  I think we could either close it, or keep it open to address its possible misplacement in the menu. 
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5752113/cc0865bf-0e97-4cb1-87a1-e11e198ccaf1)

It is in a weird spot, but it is entirely possible that was intentional.

**Comment by davidmpickett** [comment]
In VHA DM sync today, Blake & Justin expressed interest in having access to this view. In its current placement they do. Were we to move this under the Admin/Content/Facilities they would lose access. Not saying that it isn't confusing to have some views only findable from the Content drop-down menu vs the Content tab menu, but I think that's a much larger thornier IA problem that should be it's own ticket

![Screenshot 2023-07-31 184941](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/0929800a-c9f0-44d2-b586-b204e93a9cad)

![Screenshot 2023-07-31 184709](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/6583484c-b16c-4738-9de8-627820cf22c2)

**Comment by swirtSJW** [comment]
Honestly, I think Justin and Blake should have access to https://prod.cms.va.gov/admin/content/facilities and all the Views in that location.   (meaning we should make that possible if they can not accesss them.)   It should be a different ticket though.

**Comment by swirtSJW** [comment]
@jilladams  I think we should close this as done, and create a new ticket if we want to move this view of expand access.
