### ISSUE TITLE
First transformer (out of 6) for new content listing pages

### ISSUE THREAD

**Issue by cmaeng** [department-of-veterans-affairs/va.gov-cms#1424]
The plan as discussed with the VSA-Facilities team is for @indytechcook to pick up and complete the transformer work started by @ethanteague for the first of 6 new content listing pages. Once that is done we will reach out to their team to walk through how they are created and hand-off for completion of the remaining 5.

AC:
- [ ] Transformer for the first of 6 content listing pages is done
- [ ] Documentation describing how this was done is upload to GitHub
- [ ] The Facilities team is notified that this has been completed

**Comment by indytechcook** [comment]
Cross-posting: https://github.com/department-of-veterans-affairs/vets-website/pull/11810

**Comment by indytechcook** [comment]
Also: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/1034

**Comment by oksana-c** [comment]
Outdated. Closing.
