### ISSUE TITLE
Update existing spec document with feedback from CMS Collab Cycle

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#14265]
We used a hard copy doc for Collab Cycle review that contained all existing VBA specs. Find it, share it, update it.

Epic that contains all existing VBA-related Collab Cycle tickets: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10205

- [x] Spec that was sent to Collab Cycle: [VBA.Drupal.Content.Spec.ALL.1.xlsx](https://github.com/department-of-veterans-affairs/va.gov-cms/files/12135234/VBA.Drupal.Content.Spec.ALL.1.xlsx)
- [x] Laura's feedback: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10241#issuecomment-1581312505
- [x] Kamari's meeting notes: [VBA Content Specs - CMS Collab Cycle Touchpoint.docx](https://github.com/department-of-veterans-affairs/va.gov-cms/files/12135251/VBA.Content.Specs.-.CMS.Collab.Cycle.Touchpoint.docx)

## ACs

- [x] I expect that the existing spec doc used for Collab Cycle review has been located, and moved to SharePoint for collaboration
- [x] I expect that Collab Cycle feedback has been incorporated
- [ ] Update or replace CMS build tickets in #12595 for modern times

**Comment by jilladams** [comment]
@davidmpickett @omahane fair to say this work was not prioritized in favor of PM activities for Dave and VAMC Banner KB activity / data migration fixes & Swirt coverage for Christian, in this sprint?

**Comment by davidmpickett** [comment]
Spreadsheet has been moved to [Sharepoint](https://dvagov.sharepoint.com/:x:/s/SitewideFacilitiesTeam/EVVWpQp091ZEvI2n-9iyvTQBGYFZjxlVPN3Zfyz-Eh6Oyg?e=NVvsCc)

**Comment by davidmpickett** [comment]
Lingering action items from the [feedback document](https://dvagov.sharepoint.com/:w:/s/SitewideFacilitiesTeam/EYim1KcqUh5OpDGMaT05YEIBQaEjuFjaCKiFtw1vuWJnbQ?e=aKWOhC) that fall outside the scope of just updating the existing specs:
- Can VERA or Ask VA accept query parameters, allowing us to send the type of facility with the link? (Product to connect with tech teams)
- GovDelivery - is this per facility or national? @mmiddaugh (I also commented on Centralized Content spec)
- Service Location - Appointment info - might be a nested paragraph type? - needs speccing but also needs strategy convo 
- Service Location – Delivery method - lots of question marks and no feedback in document

**Comment by davidmpickett** [comment]
@mmiddaugh @jilladams I just took a look at those old dev cards and there was nothing worth preserving. I closed them all as not planned. 

However, I'm not sure if this ticket is the right place to do the work of creating replacement cards. Might be more a productive exercise if done with CMS engineers in the room (and maybe our new PM, even just in sponge mode?)

That last AC was added to this card last week, so not technically part of original sprint commitment

**Comment by mmiddaugh** [comment]
@davidmpickett I support reviewing/replacing CMS build cards with engineers and Jane.

**Comment by jilladams** [comment]
My 2 cents: finding the time for that meeting is the challenge. @davidmpickett are you willing to help Make It So? If not, I might vote for async, just to keep plates spinning and not block on calendars.

cc @Dottisea

**Comment by jilladams** [comment]
Thinking further: 
* Added this outstanding overall VBA flow step to the body of the VBA epic, in #10514, to review the sharepoint doc and make CMS tickets. We could also ask @swirtSJW and @omahane in planning tomorrow if that's something they could consider async, if async is best, and have a review together from the draft. 
* Closing. 
Go team.

**Comment by jilladams** [comment]
Next step: @Dottisea @xiongjaneg @davidmpickett to work on stubbing out tickets in prep for next refinement, where CMS folks will help refine
