### ISSUE TITLE
UX Writing for 939/ intro text WYSIWYG field

### ISSUE THREAD

**Issue by rachel-kauff** [department-of-veterans-affairs/va.gov-cms#1427]
## User story
As a content editor of a benefits detail page, I need help text for the intro text field that helps me use (or decide not to use) the new WYSIWYG functionality.

## Context

**1. Provide a link to the original issue**
#939

**2. When/where users will see the changes?**
Help text for intro text fields on benefit detail pages

## Artifacts

- [MURAL: On help text](https://app.mural.co/t/vagov6717/m/vagov6717/1586882180337/415aa0adba23f935239d291d83fda234b16f1957)

**Intro field help text for benefits detail pages w/ WYSIWYG**
`Appears directly under the title, and helps users understand if the information on the page is relevant to them. Use the second person ("you"). Don't style intro text except in special cases that may require bold, italics, links, paragraph breaks, and line breaks. `

**Intro field help text for all other content types**
`Appears directly under the title, and helps users understand if the information on the page is relevant to them. Use the second person ("you"). `

## AC

- [x] Draft text in a format that is ready for usability testing or implementation, such as [this MURAL template](https://app.mural.co/t/vagov6717/m/vagov6717/1585780955246/6b5e798420e2992bbd56d825de8c42fbf343dfa0)
- [x] Validate draft with those responsible for the work
- [x] Peer review by a member of the design pod 
- [ ] Finalize edits to text, and mark as ready to implement in the original issue
- [x] Document strategy behind language choices that are relevant to [the back end style guide](https://docs.google.com/document/d/1o3euR0eMoXRyp8G6sx1OCpmRtBShYGAm-Rb8MSXXir0/edit#)

## Next steps

- Add spike ticket for help text design
- Add dev implementation ticket for intro text

**Comment by msbtterswrth** [comment]
Ticket is outdated. Closed per @rachel-kauff.
