### ISSUE TITLE
BE: I.L. Investigate cause of empty gmt_threshold response

### ISSUE THREAD

**Issue by randimays** [department-of-veterans-affairs/va.gov-cms#14273]
### User story
**AS A** Veteran
**I WANT** all income thresholds to be returned as expected
**SO THAT** I can be sure I am viewing correct and up-to-date income limits information

### Engineering notes / background
For at least one specific zip code, the `gmt_threshold` is coming back from the API as `{}`. In this case, the VES database is returning a GMT value for this zip code.

[See Slack thread for context](https://dsva.slack.com/archives/C52CL1PKQ/p1688416952172499)

Example zip code: 99548

Data on the front end:
```
{
    "data": {
        "pension_threshold": 16037,
        "national_threshold": 39849,
        "gmt_threshold": {}
    }
}
```

Data in VES:
![Screenshot 2023-07-03 at 4.01.45 PM.png](https://images.zenhubusercontent.com/642c5916aade1f575a2a6def/865dd1f6-2bcf-4615-8106-ec036adde60d)

## Acceptance criteria
- [ ] To do

**Comment by jtmst** [comment]
Fix is live in prod: 
<img width="498" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/61624970/f1ff5a0e-7066-4732-a1cf-8df43fdd00f1">
