### ISSUE TITLE
VAMC: Defect in the display of appointment wait times 

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-cms#14277]
## Background
The average number of days to get an appointment appears within the relevant service accordion, based on data which comes from Access to Care. This data is available by location, specialty, and for new and established patients. 

### Eng background
Access to care has to do with the data. 
@swirtSJW likely knows the data situation best.
This _could_ be a conditional error.

## What happened?

The Primary care accordion for [Cranberry Township VA Clinic](https://www.va.gov/butler-health-care/locations/cranberry-township-va-clinic/) does not include an appointment wait time for Established patients., although the data is available. through Access to care.

<details>
<summary> Cranberry Township screenshots </summary>

**Broken front-end not correctly displaying Access to Care data**

![image.png](https://images.zenhubusercontent.com/5d8a47393ac3440001d1a2ed/a8f7212e-fc82-4ef5-a17b-8b281475b48f)

**Access to care data that _should_ show**
Front-end https://www.accesstocare.va.gov/FindProviders
https://www.accesstocare.va.gov/FacilityPerformanceData/FacilityData?stationNumber=529GF

![image.png](https://images.zenhubusercontent.com/5d8a47393ac3440001d1a2ed/e46f07ba-8435-4033-8c22-27a434813354)
</details>

## Expected behavior 
[Abie Abraham VA Clinic](https://www.va.gov/butler-health-care/locations/abie-abraham-va-clinic/) also has a 1 day primary care wait time for established patients and displays it correctly on the front end. 
<details>
<summary> Abbie Abraham screenshot </summary>

![image.png](https://images.zenhubusercontent.com/5d8a47393ac3440001d1a2ed/f165a2e5-e9a6-4a2e-b350-442c4fb28acb)

</details>

## Acceptance criteria
- [x] The front end should display the data available. 
   - [ ] If the breakage includes a dependency, I expect that a ticket is filed with the appropriate team, or escalated to DM if we don't know where to ticket, and linked to this issue.
- [x] Verify if this data is being delivered via Facilities API / Lighthouse and note that in ticket comments for the record 
- [x] When data is not available, the front end should not display the currently displayed small "0"

**Comment by jilladams** [comment]
Verified in prod: 
https://www.accesstocare.va.gov/FacilityPerformanceData/FacilityData?stationNumber=529GF - 0 days at Cranberry Township clinic for Primary care
https://www.va.gov/butler-health-care/locations/cranberry-township-va-clinic/


![Screenshot 2023-08-29 at 4 47 14 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/85581471/547bf1dd-1ae2-4c02-8b0c-ac587dfcc9d2)


Re: how we arrived at showing "No Wait":
Thread: https://dsva.slack.com/archives/C0FQSS30V/p1692708483067829
Decision: https://dsva.slack.com/archives/C0FQSS30V/p1692731129424819?thread_ts=1692708483.067829&cid=C0FQSS30V

Closing.
