### ISSUE TITLE
CMS Help Text: Discovery and Planning

### ISSUE THREAD

**Issue by thejordanwood** [department-of-veterans-affairs/va.gov-cms#14278]
## Description
The UX team would like to define the style of CMS help text and write documentation in order for teams to create a consistent, helpful experience for CMS editors. The current plan is for the UX team to have a half day workshop, where we can focus on this issue and work together to start defining the CMS content style guide. 

This ticket will focus on what is needed before the workshop takes place and help the team gain a shared understanding of what we want to accomplish during the workshop. 

**Questions to answer**
1. Where does it eventually live? VA Design system or CMS Design System?
2. What is the CMS help text process? Who writes it? Who approves?
3. Who is the audience for this workshop? 
4. When is something a help text issue v. a design issue?

## Acceptance Criteria
- [x] Determine current state of the CMS help text world
   - Are there any backlog issues addressing this?
   - Is there any past documentation we can use?
   - Does the Content Team have help text documentation?
- [x] Draft goals + activities for brainstorming session ([Mural board](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1689026404901/4e2618d2840924740edbfc49a78648072da35e99?sender=u01810f3edbfc878c08be5925))
- [x] Schedule brainstorming session with the UX team to determine the workshop goals (July 28th)

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [x] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`

**Comment by laflannery** [comment]
CMS Team backlog help text issues:

- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/3782
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/1788
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/1848
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/2774
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12375
- We should also look at [this closed ticket ](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/1594)I think (and possibly the tickets related to it)

**Comment by thejordanwood** [comment]
An existing version of the [CMS style guide](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/cms/ux-writing) is here on Github. It looks like this was a good start, but wasn't completed.
