### ISSUE TITLE
VBA roles/permissions: next steps

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#14285]
We know a roles/perms doc exists where Kamari was synthesizing the updated Roles & Permissions for VBA. 

We need to: 
* Surface the last state of the discussion
* Review docs we have available from Kamari
* Finalize the decision around Workflow vs. Roles/Perms
* For Roles/Perms: document in a table fashion that makes it easy to see the distinctions between each role / permissions given

Some docs (list is incomplete, there are more):
https://docs.google.com/document/d/1l068EJbeJmwguMS6rxspy95VTmpqGDpAikdz9gQso64/edit

Proposal for CMS should address the following
- Value for Veterans (beyond "patient safety")
- Problem to be solved, including how the current functionality doesn't fit this need
- How success will be measured
- What is needed for MVP
- Risks to doing this work now vs the implications of doing it later 
- How this can be a small experiment
- What options were considered and eliminated (and why)

**Comment by jilladams** [comment]
re: workflows: "there is also a (secondary) workflow blocker which dates back to Kev which duplicates workflows with 2 different filters"

**Comment by davidmpickett** [comment]
This ticket may be a no-op is https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14529 determines the problem is TOO BIG TO NOT FAIL

**Comment by jilladams** [comment]
Closing this. We separately have #13800 where we can follow up as needed if Workflow doesn't move along.
