### ISSUE TITLE
iOS App: Add baseline stats to the Mobile App Promo Banner initiative brief

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#14288]
### User story

**AS A** PO/PM
**I WANT** baseline values to be documented for all outcomes we hope to improve
**SO THAT** we have a clear criteria for success and demonstrate it's being measured.

### Notes / background

[Initiative brief](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/public-websites/Benefit%20Hub/mobile-promotion/README.md)

### Analytics 

Excel version of Google sheets: 
[Mobile App Promo Banner _ Pilot KPIs Analysis - Start Sept 2023.xlsx](https://github.com/department-of-veterans-affairs/va.gov-cms/files/13245513/Mobile.App.Promo.Banner._.Pilot.KPIs.Analysis.-.Start.Sept.2023.xlsx)

PDF copies below:

[Week-over-Week Jun - Sept  Mobile App Promo Banner _ Pilot KPIs Analysis.pdf](https://github.com/department-of-veterans-affairs/va.gov-cms/files/13245505/Week-over-Week.Jun.-.Sept.Mobile.App.Promo.Banner._.Pilot.KPIs.Analysis.pdf)

[Jul_Aug Baselines - Mobile App Promo Banner _ Pilot KPIs Analysis - Start Sept 2023.pdf](https://github.com/department-of-veterans-affairs/va.gov-cms/files/13245506/Jul_Aug.Baselines.-.Mobile.App.Promo.Banner._.Pilot.KPIs.Analysis.-.Start.Sept.2023.pdf)

[Monthly Engagement Jun - Sep - Mobile App Promo Banner _ Pilot KPIs Analysis.pdf](https://github.com/department-of-veterans-affairs/va.gov-cms/files/13245507/Monthly.Engagement.Jun.-.Sep.-.Mobile.App.Promo.Banner._.Pilot.KPIs.Analysis.pdf)

## Acceptance criteria

- [ ] Baseline column in [initiative brief](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/public-websites/Benefit%20Hub/mobile-promotion/README.md) is populated

**Comment by jilladams** [comment]
Mobile team has provided @davidconlon with steps to make it self-service for ourselves. He also hopes/plans to clean up cruft in the product brief.

**Comment by wesrowe** [comment]
I did the first month-over-baseline analysis and posted [the excel](https://dvagov.sharepoint.com/:x:/r/sites/SitewidePublicWebsites/Shared%20Documents/Mobile%20promo%20banners/Pilot%20KPIs%20analysis%20-%20start%20Sept%202023.xlsx?d=wce7adfb4ff21429babe5e2f3b4e37f01&csf=1&web=1&e=qmpNHE) to the PW space on Sharepoint. It showed a positive trend for the features we promoted for iOS. DaveC requested via Slack that I use raw numbers instead of Daily Average Users. By that point the [Looker Studio dashboard](https://lookerstudio.google.com/u/0/reporting/e28cd59a-b2e5-4f29-8ae4-a4eea6d23f9c/page/p_7hxeqg1k9c) was broken, and per a [Slack thread](https://dsva.slack.com/archives/C018V2JCWRJ/p1696621679309219?thread_ts=1696620807.918189&cid=C018V2JCWRJ) there is a problem with the BigQuery functions that drive the dashboard; fix timing TBD (but still down as of 10/11).

**Comment by jilladams** [comment]
Marking blocked until we get confirmation that Looker Studio is back up, and @FranECross gets analytics / Looker Studio access. (Is Looker Studio access going to come along for the ride via the standard analytics access request? or does Fran need to do something special for that, @wesrowe ?)

**Comment by FranECross** [comment]
@jilladams I actually have access to Looker Studio - Wes shared a link on Friday and it comes up for me. I don't have access to the excel spreadsheet. I don't see the error that is mentioned in the Slack channel, so am assuming it's been fixed...

**Comment by wesrowe** [comment]
I didn't need to request access to Looker studio – maybe publicly accessible.

**Comment by jilladams** [comment]
Hey @FranECross looking at this, the AC here is to populate the Baseline column in the [Initiative brief](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/public-websites/Benefit%20Hub/mobile-promotion/README.md) which is still outstanding as far as I can tell, so I'm not gonna close this ticket yet. Not sure what your day looks like -- if that's possible to do today, yay. If not, no worries and I'll report this'll roll over.

**Comment by FranECross** [comment]
@jilladams Just saw your note! I'll add info to the Initiative brief today. :) Thanks!

**Comment by jilladams** [comment]
@FranECross would you go ahead and close once this is done? I'll catch it in sprint reporting.
