### ISSUE TITLE
BE: Implement max-depth and error messaging for Magic-head

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#14290]
DESIGN NEEDED: error message and placement
Max-depth needed: see Notes

### User story

**AS A** Content Admin
**I WANT** the Depth field on Overview Sections to be limited to [2?], counting from zero
**SO THAT** product teams consuming the Benefit Taxonomy know how many heading levels they'll need to account for in their front-end designs.

**Max-depth value**
Wes started a [slack thread](https://dsva.slack.com/archives/C52CL1PKQ/p1688745602512119) to get a max-depth value for the Benefits Taxonomy MVP. 

### Engineering notes / background

From BE refinement:
- we have to create "max-depth" configurable field option ("field setting") - note, it's customizable per-instance of magichead, so some other product could choose a max of 1 while Benefit Taxonomy uses 3.
- Tabledrag provides API we could leverage for messaging to user
- Error could be placed in the UI near where the user is dragging

## Acceptance criteria

- [ ] In drag-and-drop mode:
  - [ ] Eligibility Overview Sections can only be moved into positions corresponding to a depth of [limit] (easy, using Tabledrag API)
  - [ ] ~~If the Editor tries to drag a Section into a position of excessive depth (even if other rules are followed), an error message displays: "Section depth is limited to 3" (3 total, heading / sub-heading / sub-sub-heading)~~
  - [ ] ~~Error message is over/near the Section being dragged~~
- [ ] Magichead field allows a max depth to be set at the field instance level (field settings).

NOTE: 2 struckthrough ACs for client-side errors are nulled by being able to prevent dragging into positions we don't want. Any additional issues created by modifying row weights will be addressed via server side error messages in #14289.

**Comment by wesrowe** [comment]
@thejordanwood, I assigned this ticket for you to confirm/improve the error message in the AC.

**Comment by dsasser** [comment]
@wesrowe 
My initial thoughts:

In general, doing something based on if the "show row weights" option is selected/not is going to be a challenge. The showing/hiding of the weight/depth columns happens as a result of a localStorage varaible, which is a browser-only scope--the backend is never aware of this selection state. 

> validation prevents save if depth value entered is less than 0 or greater than [limit]

Setting the limit should become part of the field instance config, which involves adding that capability to the new MagicHead field type's widget display. The idea here is that anywhere the new field is setup, that instance is allowed to have a unique limit. The validation is achieved using a new custom validator to check that the field's depth has not been exceeded. 
Lift: Medium

> In accessible mode (show row weights):
> 
> problematic Depth field(s) (only) are highlighted red
> error message appears under red Depth field(s) indicating "Depth must be between 0 and [limit]" [JORDAN to provide]


This would be rather difficult given that the state of the accessible mode is client-side only. I would recommend we use the current behavior which is to highlight all the fields.
Lift: High

> In drag-and-drop mode:
> Sections can only be moved into positions corresponding to a depth of [limit]

The table dragging behavior is a core implementation, so this would be challenging to achieve as a client-side override to that implementation. Further complicating this is that the depth limit isn't known to the client-side, so we would need to do work to expose it there.
Lift: High

**Comment by thejordanwood** [comment]
I'm thinking the error message could be as simple as: "Please enter a number between 0 and [limit]."

**Comment by wesrowe** [comment]
UPdate from BE refinement:

For drag-and-drop:
- we have to create "max-depth" configurable field option ("field setting") - note, customizable per-instance of magichead
- Tabledrag provides API we could leverage for messaging to user
- next step: design
- possibly carve d&d off to its own ticket (vs a11y mode)

Accessible ACs:
- may not need to do anything, as core will cover it and Editor already "showed row weights"

**Comment by dsasser** [comment]
Moved estimate to an 8 to account for both client-side (custom javascript) and backend work.

**Comment by jilladams** [comment]
From planning: 
* Danielle has not yet confirmed max depth
* Easy to raise from 3 to 4 after ship
* To lower back to 2 would require either programmatic or manual edits to fix any leveling problems.
