### ISSUE TITLE
System warning related to field_alert being triggered on many pages

### ISSUE THREAD

**Issue by omahane** [department-of-veterans-affairs/va.gov-cms#14291]
## Describe the defect
A system warning is showing in the logs (as of July 6, 2023, 1:28 CDT) related to `field_alert`.
- https://prod.cms.va.gov/admin/reports/dblog/event/8732851
  - Entity form display 'paragraph.alert_single.default': Component 'field_alert_block_reference' was disabled because its settings depend on removed dependencies. [dd.trace_id=8981163560933668062 dd.span_id=5635090193601783288]
- https://prod.cms.va.gov/admin/reports/dblog/event/8733761
  - Entity form display 'node.landing_page.default': Component 'field_alert' was disabled because its settings depend on removed dependencies. [dd.trace_id=710611085698072179 dd.span_id=2495183657076857498]

## To Reproduce
Steps to reproduce the behavior (anytime "Enforce uniquie combo" shows for an editor)
1. Log into stage as an editor in the "VA Central Arkansas health care" section
2. Go to https://staging.cms.va.gov/node/11841/edit
3. Change VAMC system health service to "Pharmacy at VA Central Arkansas health care"
4. Add a revision log message
5. Save
6. As an admin, check the Recent Logs. Near or at the top should be the system warnings (approx. 10)

## AC / Expected behavior
No such error is triggered.

### Staging
![Screenshot 2023-07-07 at 7.07.17 AM-staging-system-warning-field_alert.png](https://images.zenhubusercontent.com/62aa0d60f60c1181e8837c67/7ced039b-84a4-4c00-9285-811e9ee1057b)

### Not isolated to a specific page or content type
![Screenshot 2023-07-07 at 7 20 47 AM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/766573/583a196e-f822-49db-9cba-a8e69652426a)

 ## Additional context
I suspect it has to do https://github.com/department-of-veterans-affairs/va.gov-cms/pull/13999, given the timing.

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Defect")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS workstream (orange) (not needed for bug tickets)
- [ ] CMS-supported product (black)

### Team
Please check the team(s) that will do this work.

- [x] `CMS Team`
- [ ] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`

**Comment by swirtSJW** [comment]
The earliest occurrence lookup will have to be done in datadog or something.  Our "recent log messages" get pruned to a limited number so they only go back a day or two.

I think this issue is a duplicate of https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14209

**Comment by omahane** [comment]
Yep. Closing after adding steps to reproduce to the first ticket.
