### ISSUE TITLE
Add CMS_FACILITY_WRITE* environment variables to servers.

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#1431]
In order to have CI,and BRD environments be able to write facility statuses to the lighthouse api, we need to be able to access them though settings.php the way we currently do with other secret items.

### Acceptance criteria

- [x] Get key from keybase  add to all environments as `CMS_FACILITY_WRITE_API_KEY`
- [x] CI, dev and staging should all point to `https://sandbox-api.va.gov,` stored as `CMS_FACILITY_WRITE_API_URL`
- [x] prod should all point to `https://api.va.gov/` also stored as `CMS_FACILITY_WRITE_API_URL`
- [ ] Verify PROD key has new write permissions

**Comment by ElijahLynn** [comment]
K, based on [latest discussion from Ryan T. ](https://dsva.slack.com/archives/CT4GZBM8F/p1586388548282600?thread_ts=1585940806.035500&cid=CT4GZBM8F), the lower ENVs should use `sandbox-api.va.gov` correct?

**Comment by swirtSJW** [comment]
I just got word that the api key originally send was not for all environments.    I just keybased @oksana-c and @ElijahLynn  The new key that should be used for all the environments using `https://sandbox-api.va.gov`    That is local, dev and staging.

I will update here when I get the prod api key keybased.

**Comment by ElijahLynn** [comment]
PR for BRD is here https://github.com/department-of-veterans-affairs/devops/pull/6693. Sandbox added to credstash, still waiting on PROD key.

**Comment by ElijahLynn** [comment]
Added to CMS-CI manually and in https://github.com/department-of-veterans-affairs/devops/commit/f721e4f9e.

**Comment by ElijahLynn** [comment]
New CMS-CI commit in https://github.com/department-of-veterans-affairs/devops/commit/116b396f4.

**Comment by ElijahLynn** [comment]
Next steps in specific order:
- [ ] Test https://github.com/department-of-veterans-affairs/va.gov-cms/pull/1435 migration to make sure working against sandbox API
- [ ] Merge https://github.com/department-of-veterans-affairs/devops/pull/6693
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/pull/1435
