### ISSUE TITLE
Review of new or updated KB article : VAMC System Banner alerts

### ISSUE THREAD

**Issue by davidmpickett** [department-of-veterans-affairs/va.gov-cms#14317]
## Which article(s) need review?
We're requesting your review of 4 KB articles which are related to VAMC System Banner Alerts with Situation Updates and the pending new functionality that will go live when a bunch of related changes are merged and which were demoed in Facilities Refinement on 7/6 ([recording](https://drive.google.com/file/d/1jBzy0FacH7A3cVjYckvp_tjUQUEgLHhE/view?usp=drive_link))
@TroyA6 previously reviewed an article Kamari drafted on this topic, but that article was about the wrong type of banner.

@omahane has drafted revisions of 4 articles to reflect the new functionality. These links will show a comparison of Christian’s latest revision to the currently published version of each article for ease of review
- [ ] [About VAMC alerts and operating statuses](https://prod.cms.va.gov/node/6868/revisions/view/721350/792314/visual_inline)
- [ ] [How to add a system banner alert](https://prod.cms.va.gov/node/6871/revisions/view/721349/792330/visual_inline)
- [ ] [Best practices for VAMC system banner alerts](https://prod.cms.va.gov/node/43819/revisions/view/656780/792554/visual_inline)
- [ ]  [How to create a situation update](https://prod.cms.va.gov/node/23520/revisions/view/527774/791621/visual_inline)

## Priority or deadline for request
Choose either Deadline or a priority:

- [x] Deadline: These articles block VHA DM's communication plan for editors which blocks our ability to merge these changes and move forward with these important changes. Given the hurricane season, we need to move forward with this implementation. 
- [ ] Priority:
  - [ ] Critical
  - [x] High
  - [ ] Medium
  - [ ] Low

## Associated KB article ticket
[#14009 KB Articles related to VAMC System Banner alerts: Review for publish](https://app.zenhub.com/workspaces/sitewide-facilities-639f5253e4b702a32376339e/issues/gh/department-of-veterans-affairs/va.gov-cms/14009)
  
## Can article(s) be published?
Once the article has been fully reviewed, can the article(s) be published? For example, is anything tied directly to an upcoming feature and this information should not be published until the feature is on production?
- [ ] Yes, all article(s)s within this ticket can be published once reviewed
- [x] No, the article(s) within this ticket should not be published and should only be reviewed - _we are coordinating simultaneous review by VHA DM_
  
## Notify the CMS team of this ticket in the cms-support Slack channel.
- [x] I acknowledge that I must notify #cms-support after submitting this issue.

## Acceptance Criteria
- [ ] Article reviewed by CMS Team
- [ ] Article reviewed by Help desk
- [ ] If approved above, article is published
- [ ] Requesting person/team has been notified that article was reviewed/published - _please tag @omahane,  @davidmpickett,  and @mmiddaugh in #sitewide-facilities_

**Comment by davidmpickett** [comment]
Has been sent to CMS Team for prioritization

**Comment by omahane** [comment]
@davidmpickett I updated the links to the the revision comparisons after making my most recent edits.

**Comment by davidmpickett** [comment]
@stefaniefgray @TroyA6 @productmike 
While reviewing KB articles, we also found this training node that will likely need updates: https://prod.cms.va.gov/help/get-training/session-4-facilities
- Are product teams responsible for updating training materials, or just KB articles?
- Is anyone equipped to update our training videos?

**Comment by jilladams** [comment]
@stefaniefgray @TroyA6 @BerniXiongA6 just a reminder: these edits will merge and ship on Wednesday 7/26 this week, in service of launch. If you'd like to provide feedback prior, please prioritize today / tomorrow. Thanks!

**Comment by jilladams** [comment]
https://prod.cms.va.gov/help/vamc/how-to-create-a-situation-update
https://prod.cms.va.gov/help/cms-basics/resources-for-emergency-situations
https://prod.cms.va.gov/help/vamc/about-locations-content-for-vamcs/about-alerts-and-operating-statuses/best-practices-for-vamc-system-banner-alerts
https://prod.cms.va.gov/help/vamc/about-locations-content-for-vamcs/about-alerts-and-operating-statuses/how-to-add-a-system-banner-alert
https://prod.cms.va.gov/help/vamc/about-locations-content-for-vamcs/about-alerts-and-operating-statuses

These were published with revisions on 7/26. Remaining HD feedback / updates are optional. If you don't think you'll get to it, feel free to close this ticket.
