### ISSUE TITLE
Remove header image from CMS Help Desk Jira website

### ISSUE THREAD

**Issue by EWashb** [department-of-veterans-affairs/va.gov-cms#14311]
## Description

The following image should be removed from our [Jira help desk instance](https://va-gov.atlassian.net/servicedesk/customer/portals). OCTO-DE only has permission to use this image on the homepage. The header image below should be removed from Jira and any other places it might appear:

![image.png](https://images.zenhubusercontent.com/614b6cbe05afafb268be4c0b/87a53be6-feb5-4b15-99c6-6c3f47bc7318)

## Acceptance Criteria
- [ ] the specific header in the screenshot is removed from our Jira/Help Desk intake site

### Team
Please check the team(s) that will do this work.

- [X] `CMS Team`
- [ ] `Public Websites`
- [ ] `Facilities`
- [X] `User support`

**Comment by EWashb** [comment]
@BerniXiongA6 @productmike tagging you in this new issue. We need to remove this image from Jira. I am not sure what the lift of this is. I don't suppose and engineer will need to do it, but please check with user support. This should be taken care of as soon as we have capacity since we are not authorized by our stakeholders to use this image in this way.

**Comment by EWashb** [comment]
Any chance we can pull this into sprint 90 or 91 @productmike?

**Comment by productmike** [comment]
@EWashb thanks for the reminder -- should be a quick thing so I'll flag it for planning today.

**Comment by BerniXiongA6** [comment]
Hi @stefaniefgray -- how close are we to completing this ticket?

**Comment by productmike** [comment]
@TroyA6 If you have a chance today, please take a look and see if you might be able to remove this image. Even if a temporary background in place, that's fine. Biggest thing is to get this particular image down. Thank you!

cc: @BerniXiongA6 @stefaniefgray

**Comment by TroyA6** [comment]
@productmike @BerniXiongA6 @EWashb @stefaniefgray - I have found that I do not have access to the necessary settings to remove the image. My 'Settings' access only applies to my account. I will get with Stefanie upon her return to remove the image.

**Comment by BerniXiongA6** [comment]
Thanks @TroyA6 -- I'll reach out to Tony A. for IT support on this permissions issue. Thank you!

**Comment by TroyA6** [comment]
I was granted sufficient permissions to remove the image -- task complete.
