### ISSUE TITLE
Sanitized logins not working on d10 tugboat

### ISSUE THREAD

**Issue by edmund-dunn** [department-of-veterans-affairs/va.gov-cms#14322]
## Description
The default login password is not working on the D10 tugboat. I am unable to replicate this locally. I pulled a fresh database one the same code nd login works as expected. 

## Acceptance Criteria
- [ ] Default login password works.

### Team
Please check the team(s) that will do this work.

- [x] `CMS Team`
- [ ] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`

**Comment by ndouglas** [comment]
I traced this to the password checker failing to confirm that the submitted password matches the stored password. This sounded to me like a hash or crypto method had changed. So I Googled and found this:

https://www.drupal.org/project/drupal/issues/3358524

Indeed, we do not have Password Compatibility enabled:

![Screenshot 2023-07-12 at 10 51 57 AM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/1318579/acaa01ee-eeb1-4d8e-9029-a55d7e7a0f07)

I think this is likely the issue.

**Comment by ndouglas** [comment]
Confirmed with my personal account, checking for confirmation from @edmund-dunn

**Comment by edmund-dunn** [comment]
This fixed my login as well.
