### ISSUE TITLE
Update cypress test for D10

### ISSUE THREAD

**Issue by edmund-dunn** [department-of-veterans-affairs/va.gov-cms#14329]
## Description
We need to fix cypress testing for D10. This revolves mostly around the move to CKeditor5. There might be other changes needed after this fix is in place for Ckeditor.

## Acceptance Criteria
- [x] Fix tests for new CKeditro5 structure.
- [ ] Check all cypress tests for errors and fix as needed.
- [ ] All cypress tests must pass.

### Team
Please check the team(s) that will do this work.

- [x] `CMS Team`
- [ ] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`

**Comment by ndouglas** [comment]
Is this resolved? I checked out the D10 branch, ran some tests, and they passed. Do we have a comprehensive list anywhere of tests that are still failing?

**Comment by edmund-dunn** [comment]
This has been fixed.
