### ISSUE TITLE
Remove all Behat tests

### ISSUE THREAD

**Issue by edmund-dunn** [department-of-veterans-affairs/va.gov-cms#14331]
## Description
All Behat tests will be removed. This is largely driven by the fact that the `goutte` driver has been abandoned. All functional testing needs to be moved to Cypress. 

## Acceptance Criteria
- [ ] Behat tests removed. 

### Team
Please check the team(s) that will do this work.

- [x] `CMS Team`
- [ ] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`

**Comment by ndouglas** [comment]
Duplicate of #12445.
