### ISSUE TITLE
Prep for D10 testing

### ISSUE THREAD

**Issue by davidmpickett** [department-of-veterans-affairs/va.gov-cms#14344]
- Get access to spreadsheet
- Review spreadsheet
- Chunk testing work into tickets and add to EPIC
  - [Product - VAMC-related (don't forget Lovell!)](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14385)
  - [Product - Vet Center](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14387)
  - [Features - Stories / News Release / Staff Profiles / Leadership List / Service Taxonomy](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14388)
  - [Product - VBA & NCA](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14389)
  - [Front end verification](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14390)

AC
- [x] I expect that tickets (stubs) have been created and added to the D10 epic

**Comment by omahane** [comment]
@davidmpickett @jilladams These tickets are made and linked in the description. They've been added to the epic, too.

**Comment by davidmpickett** [comment]
These tickets look great. Thanks for taking this on @omahane!
