### ISSUE TITLE
Change repo so that all developers do not use forks, but work out of branches in the main repo

### ISSUE THREAD

**Issue by edmund-dunn** [department-of-veterans-affairs/va.gov-cms#14341]
## Description
In order to fix permissions issues with github and testing we need to stop using forks and work out of the main repo using branches. 

## Acceptance Criteria
- [ ] Update documentation for new workflow. Developers will use branches in main repo to work from. CMS Team will need to ensure that the repo is cleaned up at the end of every sprint. 
- [ ] this change has been socialized to other CMS and CMS-adjacent teams (e.g. AP), including:
- [ ] TL;DR reasoning
- [ ] brief summary of how to most expediently update our local workflows to be in compliance

### Team
Please check the team(s) that will do this work.

- [x] `CMS Team`
- [ ] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`

**Comment by edmund-dunn** [comment]
@EWashb already approved this in a zoom call.

**Comment by EWashb** [comment]
I agree with @ndouglas on the new ACs. Before we do this work to change it, we want to do our due diligence with the change management portion of this. Let's communicate with the other teams this affects early and often. 

I would like to prewarn people this change is coming, then update them when the work is starting. May even be worth a topic dive presentation at some point. As we make changes to our workflows, we need to be prepared to be a resource for questions and feedback from the product teams.

**Comment by edmund-dunn** [comment]
This has already been done. Closing.
