### ISSUE TITLE
DevOps Engineers Require SSH Access to CMS Servers 

### ISSUE THREAD

**Issue by olivereri** [department-of-veterans-affairs/va.gov-cms#14357]
## Description
Sometimes it is necessary for DevOps engineers to directly access the CMS servers to make changes in Staging, Trouble Shoot issues, or rarely, run ad-hoc scripts on Production.  DSVA GovCloud IAM enforces Multi-factor Authentication for the Web Console and Programmatic access via the API. A tool called [AWS-MFA ](https://github.com/broamski/aws-mfa)automates the task of obtaining MFA access keys and updating AWS CLI credentials.  Additionally, a Go-lang application has been developed that interacts with AWS Systems Manager to facilitate SSH access to servers within the DSVA GovCloud account.

## Acceptance Criteria
- [x] [AWS-MFA](https://github.com/broamski/aws-mfa) is installed and configured.
- [x] SSM-Session is installed per installation instructions
- [x] CMS server login is tested successfully

## Implementation Details
- [SSM-Session prerequisites, usage and install instructions](https://github.com/department-of-veterans-affairs/devops/tree/master/utilities/ssm-session)

### Team
Please check the team(s) that will do this work.

- [x] `CMS Team`
- [ ] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`

**Comment by ndouglas** [comment]
Slightly more detail on AWS-MFA configuration.

Install `AWS-MFA`.

Your AWS config should look like this:

```
$ cat ~/.aws/config 
[default]
region = us-gov-west-1
output = json
```

And your credentials should look like this:

```
$ cat ~/.aws/credentials 
[default-long-term]
aws_access_key_id = your-access-key-id
aws_secret_access_key = your-secret-access-key
aws_mfa_device = ARN for your MFA device
```

Your MFA device should be listed on your [Security Credentials page](https://console.amazonaws-us-gov.com/iamv2/home#/security_credentials?section=IAM_credentials) in the AWS console. I assume that y'all have Authy or Google Authenticator or 1Password or something.

Then run `aws-mfa`, and it should prompt you for a TOTP. Enter it, and it should write temporary credentials to your `~/.aws/credentials` file under `[default]`. Then you should be able to execute any normal AWS command.

```
$ aws iam get-user
{
    "User": {
        "Path": "/",
        "UserName": "Nathan.Douglas",
        "UserId": "...",
        "Arn": "...",
        "CreateDate": "...",
        "PasswordLastUsed": "...",
        "Tags": [
          ...
        ]
    }
}
```
