### ISSUE TITLE
D10: Error while saving Campaign Landing Page

### ISSUE THREAD

**Issue by dsasser** [department-of-veterans-affairs/va.gov-cms#14359]
## Description
![Save error](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/221539/5588bf7b-62f2-43c3-a780-9508b11c8743)

### User story
> _Describe the audience/user, enhancement or fix, and value / outcome desired._

**AS A** CMS user
**I WANT** to be able to save campaign landing pages that are filled correctly
**SO THAT** I can create campaign landing pages for Veterans

### Engineering notes / background
I receive the above error when saving a Campaign Landing Page that had filled nearly every field. This error is not thrown in all cases, and I have not identified the particular fields which trigger the error. However, I did find the culprit code, which is calling a method that was removed in D10 (deprecated in D9): MimeTypeGuesser::guess()

Deprecated method in docroot/core/lib/Drupal/Core/File/MimeType/MimeTypeGuesser.php:
```php
  public function guess($path) {
    @trigger_error(__METHOD__ . '() is deprecated in drupal:9.1.0 and is removed from drupal:10.0.0. Use ::guessMimeType() instead. See https://www.drupal.org/node/3133341', E_USER_DEPRECATED);
    return $this->guessMimeType($path);
  }

```

Use in va_gov_backend:
```php
class PdfCheckValidator extends ConstraintValidator {

  /**
   * {@inheritdoc}
   */
  public function validate($item, Constraint $constraint) {
    /** @var \Drupal\va_gov_backend\Plugin\Validation\Constraint\PdfCheck $constraint */
    // Per internal dev meeting, dependency injection doesn't
    // work well with constraints.
    // Drupal contrib constraint modules call services directly.
    // Okay to follow this pattern.
    if (\Drupal::service('file.mime_type.guesser')->guess($item->uri) !== 'application/pdf') {
      $this->context->addViolation($constraint->notPdfFile, [':file' => $item->uri]);
    }

  }

}
```

## Acceptance criteria
- [ ] PHP error no longer fires when saving a Campaign Landing Page

**Comment by dsasser** [comment]
This was resolved in the d10 branch [VACMS-12252-drupal-10](https://github.com/department-of-veterans-affairs/va.gov-cms/compare/VACMS-12252-drupal-10) in commit 4662d86145d82de162afb12cc3af26ea08f9fca0

**Comment by jilladams** [comment]
@dsasser can't decide if we should close this. On the one hand: yes, the commit is in queue toward prod and that commit resolves the issue. On the other hand: it's not shipped til it's shipped. I err toward closing. Does that raise a hackle?
