### ISSUE TITLE
VBA Facility name change: 9 facilities (due to fort name changes)

### ISSUE THREAD

**Issue by omahane** [department-of-veterans-affairs/va.gov-cms#14377]
## Intake
- [x] What triggered this runbook? (Flag in CMS via Lighthouse migration)
Trigger: Fort name changes

- [x] Link to facility in production:

| **[Title](https://prod.cms.va.gov/admin/content/facilities/flagged?type=vba_facility&workbench_access_section__section=All&order=title&sort=asc)** | **Edit** | **[Section](https://prod.cms.va.gov/admin/content/facilities/flagged?type=vba_facility&workbench_access_section__section=All&order=field_administration&sort=asc)** |
|---|---|---|
| [VA Regional Benefit Satellite Office at Fort Cavazos](https://prod.cms.va.gov/vba-facilities/locations/fort-hood-vocational-rehabilitation-and-employment-office) | **[Edit](https://prod.cms.va.gov/node/4272/edit)** | Waco VA Regional Benefit Office |
| [Pre-Discharge Site at Fort Cavazos](https://prod.cms.va.gov/waco-va-regional-benefit-office/locations/pre-discharge-site-at-fort-cavazos) | **[Edit](https://prod.cms.va.gov/node/42651/edit)** | Waco VA Regional Benefit Office |
| [Integrated Disability Evaluation System \(IDES\) and Pre-Discharge Claims Intake Site at Fort Novosel](https://prod.cms.va.gov/montgomery-va-regional-benefit-office/locations/integrated-disability-evaluation-system-ides-and-pre-discharge-claims-intake-site-at-fort-novosel) | **[Edit](https://prod.cms.va.gov/node/42604/edit)** | Montgomery VA Regional Benefit Office |
| [Pre-Discharge Site at Fort Liberty](https://prod.cms.va.gov/winston-salem-va-regional-benefit-office/locations/pre-discharge-site-at-fort-liberty) | **[Edit](https://prod.cms.va.gov/node/42596/edit)** | Winston-Salem VA Regional Benefit Office |
| [Veteran Readiness and Employment Office at Fort Liberty](https://prod.cms.va.gov/winston-salem-va-regional-benefit-office/locations/veteran-readiness-and-employment-office-at-fort-liberty) | **[Edit](https://prod.cms.va.gov/node/4056/edit)** | Winston-Salem VA Regional Benefit Office |
| [Pre-Discharge Site at Fort Moore](https://prod.cms.va.gov/atlanta-va-regional-benefit-office/locations/pre-discharge-site-at-fort-moore) | **[Edit](https://prod.cms.va.gov/node/4023/edit)** | Atlanta VA Regional Benefit Office |
| [Integrated Disability Evaluation System \(IDES\) Site at Fort Moore](https://prod.cms.va.gov/atlanta-va-regional-benefit-office/locations/integrated-disability-evaluation-system-ides-site-at-fort-moore) | **[Edit](https://prod.cms.va.gov/node/4019/edit)** | Atlanta VA Regional Benefit Office |
| [Veteran Readiness and Employment Office at Fort Moore](https://prod.cms.va.gov/atlanta-va-regional-benefit-office/locations/veteran-readiness-and-employment-office-at-fort-moore) | **[Edit](https://prod.cms.va.gov/node/4018/edit)** | Atlanta VA Regional Benefit Office |
| [Integrated Disability Evaluation System \(IDES\) Site at Fort Gregg-Adams](https://prod.cms.va.gov/roanoke-va-regional-benefit-office/locations/integrated-disability-evaluation-system-ides-site-at-fort-gregg-adams) | **[Edit](https://prod.cms.va.gov/node/4000/edit)** | Roanoke VA Regional Benefit Office |

### Drupal Admin steps
- [x] Edit the node and update the alias to match the new facility name, lowercase with dashes.
- [x] Edit the facility node, remove the `Changed name` flag, save the node with revision log

**Comment by omahane** [comment]
This have been completed, leaving only 18 flagged facilities.

**Comment by jilladams** [comment]
@omahane can you update ticket here with reminder of what happened that did /d idn't work and pointer to the ticket for whatever needs to happen on Facility Locator to get it working correctly for these 9 Facilities?

**Comment by omahane** [comment]
These worked fine. This is not the issue related to CSV changes not being made. That is this one: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14400
