### ISSUE TITLE
Facilities Team Sprint 89 plan

### ISSUE THREAD

**Issue by davidmpickett** [department-of-veterans-affairs/va.gov-cms#14376]
### VAMC Banners with Situation Updates 🎯
State of the union 
- Tech = ready to ship
- KB articles = waiting for CMS review #14317
- Editor comms = VHA DM
    - Email send scheduled for Wed 7/19
    - Launch = Wed 7/26

**This sprint**
- 🎯 #14117

**Stretch**
- #13543 - not launch blocking, but would be good if possible to include

---

### VBA Regional Office Modernization
State of the union: 
- Prepping for Midpoint Review
- Midpoint blocks prototype
- Prototype blocks usability testing

**This sprint**
- 🎯 #10473 - Dave P to create more artifacts to frame discussion
- Then Midpoint (https://github.com/department-of-veterans-affairs/va.gov-team/issues/46029)
- #14351 - not a blocker for midpoint, but maybe a good fit for Alexis this sprint

**Stretch / next sprint**
- #13960
- #14265

---

### Facility Locator 
State of the union: Design Intent follow up

**This sprint**
- Collab cycle epic: https://github.com/department-of-veterans-affairs/va.gov-team/issues/61610
    - Feedback tickets will be added by Thursday 7/20
    - Refine those tickets 
- Incorporate feedback from platform - depends on Jordan's capacity and amount of feedback
- Tech: Think about order of ops / whether we can start any architectural process now
- Think about implementing LH V1 in FL: what's there / close the gap / how do we handle launching V1 with the old designs

---

### Mental Health Numbers
State of the union:  Largely blocked on things from VHA DM
- Coverage: @mmiddaugh to follow up on open questions

---

### Drupal 10 upgrade Testing ([Epic](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13112))
- #14385
- #14387
- #14388
- #14390
- #14389

### Other
- #13359 - Ruby
- #13980 - Drupal
- #14277 - FE
- #13651 - FE
- #13331 - FE

### Accessibility Initiated
- #12085
- #13837

### Flagged Facilities ([board](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13546#workspaces/flagged-facilities-64b47ffcd5bea6bc6ba82ddc/board))
- #13546 
- #13545 
- #14377

**Comment by jilladams** [comment]
I could cry, this is is useful. Thanks Dave. 🥲

**Comment by jilladams** [comment]
For discussion in planning: 
* https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14134

**Comment by jilladams** [comment]
* Initiative by initiative - pull in the right things
    * VAMC banners date
* Review what's pointed and refine anything that's not yet
* Assignments for obvious stuff
* Flagged Facilities review
* At the end: UX assignment review / Alexis etc

**Comment by jilladams** [comment]
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13543
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14351



https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14430

**Product things to figure out:**
Tech: Think about order of ops / whether we can start any architectural process now
Think about implementing LH V1 in FL: what's there / close the gap / how do we handle launching V1 with the old designs
Review: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13709
