### ISSUE TITLE
Drupal 10 Testing: Product - VBA & NCA

### ISSUE THREAD

**Issue by omahane** [department-of-veterans-affairs/va.gov-cms#14389]
## Description
Testing the VBA and NCA product-related items to determine whether there are any regressions of current functionality or behavior due to upgrading to Drupal 10.

[Drupal 10 Tugboat home page](https://tugboat.vfs.va.gov/64c11c302d3036648d7f600e)
[Drupal 10 environment](https://vacms-12252-drupal-10-esdtuqzba9g5gopezqazojjvehr8jy4i.ci.cms.va.gov/)

### I expect that we have tested the following items:
- [x] NCA Facility
   - [ ] ~Change of published status results in content release.~  Not done because these have no FE so they do not atttempt to trigger.
- [x] NCA Facility Migration
- [x] VBA Facility
   - [ ] ~Change of published status results in content release.~  Not done because these have no FE so they do not atttempt to trigger.
- [x] VBA Facility Migration
- [x] VBA Facility Service - the node exists.  Not much to test as we have no vba services yet.

### Additional AC
- [ ] I expect that any defects are added to the [D10 Sitewide sanity tests Google sheet](https://docs.google.com/spreadsheets/d/136FP-HtxRWJuPYYV4D95ngby96Wqy4Ul_HOgOqEk1K0/edit#gid=1052173265)
- [ ] I expect that any defects are added to the [Drupal10_Defects-MobTest Google sheet](https://docs.google.com/spreadsheets/d/1R4g9jSZJvGRCAWWoslnxlC2hv5A2kHKMMxabbct3bI4/edit#gid=0)
- [ ] I expect that any necessary tickets are made to capture the defects identified.

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [ ] `Public Websites`
- [x] `Facilities`
- [ ] `User support`

**Comment by swirtSJW** [comment]
NCA migration run
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5752113/509df241-488f-431d-a4e3-06b385bd62de)

No blatant failures.
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5752113/94fabed4-07cb-4693-bc08-def0172a7f28)

Data comparison is good
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5752113/212ed4d4-3265-4229-a3f3-b0b901c0b2e8)

**Comment by swirtSJW** [comment]
Can't detect if VBA status change triggers a content release because the new code has not landed yet.

**Comment by swirtSJW** [comment]
NCA Migration
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5752113/abb4618d-f175-421c-91d5-bed5d65d502a)

![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5752113/25e47914-5b89-4cab-b94d-65cd5baede13)

Only data changes showing were changes to time formatting, which is expected.
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5752113/d7fc9063-30de-4a9c-8fa4-f6548983917d)

**Comment by swirtSJW** [comment]
These all check out and are considered done.
