### ISSUE TITLE
Drupal 10 Testing: Product - Vet Center

### ISSUE THREAD

**Issue by omahane** [department-of-veterans-affairs/va.gov-cms#14387]
## Description
Testing the Vet Center product-related items to determine whether there are any regressions of current functionality or behavior due to upgrading to Drupal 10.

~[Drupal 10 Tugboat home page](https://tugboat.vfs.va.gov/64c11c302d3036648d7f600e)~   [New Tugboat](https://tugboat.vfs.va.gov/64c7db7a2d3036648df70ed9)
~[Drupal 10 environment](https://vacms-12252-drupal-10-esdtuqzba9g5gopezqazojjvehr8jy4i.ci.cms.va.gov/)~  [new D10](https://vacms-12252-drupal-10-opslrfeufzwsvhxx2uuv1wmvjbiq7wuq.ci.cms.va.gov/)

### I expect that we have tested the following items:
- [x] Vet Center
- [x] Vet Center Migration
- [x] Vet Center - Outstation
- [x] Vet Center Outstation Migration
- [x] Vet Center - Mobile Vet Center
- [x] Vet Center Mobile Migration
- [x] Vet Center - Community Access Point
- [ ] ~Vet Center CAP push - if it has been merged by then~ Not merged at time of testing.
- [x] Vet Center - Facility Service
- [x] Vet Center - Locations List
- [ ] Vet Center editor editing published facility (what moderation state is selected/available)

### Additional AC
- [ ] I expect that any defects are added to the [D10 Sitewide sanity tests Google sheet](https://docs.google.com/spreadsheets/d/136FP-HtxRWJuPYYV4D95ngby96Wqy4Ul_HOgOqEk1K0/edit#gid=1052173265)
- [ ] I expect that any defects are added to the [Drupal10_Defects-MobTest Google sheet](https://docs.google.com/spreadsheets/d/1R4g9jSZJvGRCAWWoslnxlC2hv5A2kHKMMxabbct3bI4/edit#gid=0)
- [ ] I expect that any necessary tickets are made to capture the defects identified.

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [ ] `Public Websites`
- [x] `Facilities`
- [ ] `User support`

**Comment by swirtSJW** [comment]
Deleting Vet Center failed 
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5752113/f88824fa-ffa6-463a-a115-a87daacf100c)

**Comment by swirtSJW** [comment]
Our D10 demo has gone away.   :(  https://dsva.slack.com/archives/C05EJD52H1R/p1690819251332939

**Comment by swirtSJW** [comment]
Vet Center no change save resulted in only expected changes.
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5752113/46bb4883-a80f-406b-a7ff-476502475e89)

**Comment by swirtSJW** [comment]
Tested deletion.  Failed
Demo environment does not have new code yet
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5752113/eba90520-e6b2-4b03-905f-62abb0ff7eec)

**Comment by swirtSJW** [comment]
Vet center migration 
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5752113/86662572-211b-4bc0-b5dc-680649791b9d)

**Comment by swirtSJW** [comment]
Outstations test out
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5752113/5ce9dc8e-5d7b-4c99-89e3-ad4a2cbf4945)

**Comment by swirtSJW** [comment]
API sourced content lockdown works

**Comment by swirtSJW** [comment]
Mobile data changes makes sense 
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5752113/a2fc0d32-7ae6-4935-917f-b3c05aac3c13)

**Comment by swirtSJW** [comment]
Mobile deletion works.
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5752113/baaa64fa-243b-4c3f-94fe-4a228ebbff86)

**Comment by swirtSJW** [comment]
Mobile migration 
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5752113/3c05c528-cb46-4bb9-8280-695c9c93205d)

**Comment by swirtSJW** [comment]
Services (wysiwyg) content is missing any and all whitespace in content 
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5752113/343137f9-15c3-4ae9-8f8b-df070bad3220)

It has no apparent impact on any display, but is interesting.

**Comment by swirtSJW** [comment]
Too weird.  The Mobile Vet center migration worked this time (and the counts are right too.
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5752113/9627d766-d3aa-4223-aa60-1300c82dbe64)

**Comment by swirtSJW** [comment]
CAP save is good.  
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5752113/a611c4e0-67cf-41f4-b416-f78812ff3b28)

**Comment by swirtSJW** [comment]
Service selector lockdown functions
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5752113/e6b6ae4d-1653-41a3-b485-cb6dc7a42d0d)

**Comment by swirtSJW** [comment]
Service duplicate prevention works
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5752113/8eaa9315-4011-431d-8ff0-9ccb2c9128dd)

**Comment by swirtSJW** [comment]
Locations.   Added and removed mobile.

**Comment by swirtSJW** [comment]
Vet Center editor checks out as being unable to archive a vet center.
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5752113/b64dd15a-02ba-4211-bdcf-12d67fa7841a)

**Comment by swirtSJW** [comment]
This concludes the testing related to the Vet center product.
