### ISSUE TITLE
Onboard Tolase to DSVA PagerDuty

### ISSUE THREAD

**Issue by olivereri** [department-of-veterans-affairs/va.gov-cms#14393]
## Description
A support request has been created to request access to PagerDuty for Tolase:
https://dsva.slack.com/archives/CBU0KDSB1/p1689619852468919

## Acceptance Criteria
- [x] Support ticket open to request access.
- [x] Tolase can successfully login to PagerDoty.

### Team
Please check the team(s) that will do this work.

- [x] `CMS Team`
- [ ] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`

**Comment by teeshe** [comment]
Pager Duty invite received and accepted [#62544](https://github.com/department-of-veterans-affairs/va.gov-team/issues/62544)
