### ISSUE TITLE
Use Credstash in Devshop

### ISSUE THREAD

**Issue by indytechcook** [department-of-veterans-affairs/va.gov-cms#1439]
Currently Devshop hardcodes some credential files within configurations.  These should pull from credstash directly.

- [ ] Evaluate credstash libraries: https://packagist.org/packages/stonewaves/credstash and https://packagist.org/packages/gmo/credstash
- [ ] Update `va.drush.inc.j2` devshp file to use credstash library

**Comment by ElijahLynn** [comment]
Closing for now as we are likely moving off of DevShop.
