### ISSUE TITLE
Drupal 10 Testing: Front end verification

### ISSUE THREAD

**Issue by omahane** [department-of-veterans-affairs/va.gov-cms#14390]
## Description
Testing the front-end items to determine whether there are any regressions of current functionality or behavior due to upgrading to Drupal 10.

[Drupal 10 Tugboat home page](https://tugboat.vfs.va.gov/64c11c302d3036648d7f600e)
[Drupal 10 environment](https://vacms-12252-drupal-10-esdtuqzba9g5gopezqazojjvehr8jy4i.ci.cms.va.gov/)

### Front-end build
Currently we don't know how to access a VA.gov FE of the D10 Tugboat. Open Q to CMS Team here: https://dsva.slack.com/archives/C05EJD52H1R/p1689782093039219

### I expect that we have tested the following items:
- [x] Lovell FE check
- [x] Facility Locator - operating status (CMS-driven data) - e.g. [Benefit office](https://www.va.gov/find-locations/?address=97206&bounds%5B%5D%5B%5D=-123.361406&bounds%5B%5D%5B%5D=44.746629&bounds%5B%5D%5B%5D=-121.861406&bounds%5B%5D%5B%5D=46.246629&context=Portland%2C%20Oregon%2097206%2C%20United%20States&facilityType=benefits&latitude=45.496629&longitude=-122.611406&page=1&radius=10&serviceType&bounds%5B%5D=-124.01140600000001&bounds%5B%5D=44.096629&bounds%5B%5D=-121.211406&bounds%5B%5D=46.896629)
- [x] Gov delivery build response received

### I expect that we have sanity checked the following items:
- [x] VAMC System - https://www.va.gov/portland-health-care/
- [x] VAMC Facility - https://www.va.gov/portland-health-care/locations/portland-va-medical-center/
- [x] Blue buttons
    - [x] https://www.va.gov/portland-health-care/make-an-appointment/
    - [x] https://www.va.gov/portland-health-care/register-for-care/
    - [x] https://www.va.gov/portland-health-care/pharmacy/
- [x] Spotlight links
    - [x] [Get help from a patient advocate](https://www.va.gov/portland-health-care/health-services/patient-advocates)
    - [x] [Access your health records](https://www.va.gov/portland-health-care/medical-records-office)
    - [x] [Find a phone number](https://www.va.gov/portland-health-care/contact-us)
    - [x] [Check your billing, insurance, and payment options](https://www.va.gov/portland-health-care/billing-and-insurance)
    - [x] [Volunteer or donate](https://www.va.gov/portland-health-care/work-with-us/volunteer-or-donate)
    - [x] [VA Portland Operational Status](https://www.va.gov/portland-health-care/operating-status/)
    - [x] [Compare our performance with non-VA facilities](https://www.va.gov/portland-health-care/about-us/performance)
- [x] Open health services accordions to confirm no weirdness - https://www.va.gov/portland-health-care/locations/portland-va-medical-center/#health-care-offered-here
- [x] SERVICES AND LOCATIONS
    - [x] [Health services](https://www.va.gov/portland-health-care/health-services)
    - [x] [Locations](https://www.va.gov/portland-health-care/locations)
    - [x] [Events](https://www.va.gov/portland-health-care/events)
    - [x] [News Releases](https://www.va.gov/portland-health-care/news-releases)
    - [x] [Stories](https://www.va.gov/portland-health-care/stories)
    - [x] [About us](https://www.va.gov/portland-health-care/about-us)
    - [x] [Work with us](https://www.va.gov/portland-health-care/work-with-us)
    - [x] [Contact us](https://www.va.gov/portland-health-care/contact-us)
    - [x] [Policies](https://www.va.gov/portland-health-care/policies)
    - [x] [Programs](https://www.va.gov/portland-health-care/programs)
- [x] Vet Center facility page
    - [x] https://www.va.gov/portland-or-vet-center/
    - [x] https://www.va.gov/portland-or-vet-center/locations/
- [x] Benefit Office pages - location / status: https://www.va.gov/find-locations/facility/vba_348a
- [x] NCA office pages - status (need to check Drupal for an example)

### Additional AC
- [x] I expect that any defects are added to the Facilities Team [D10 Sitewide sanity tests Google sheet](https://docs.google.com/spreadsheets/d/136FP-HtxRWJuPYYV4D95ngby96Wqy4Ul_HOgOqEk1K0/edit#gid=1052173265)
- [x] I expect that any defects are added to the Authoritative CMS Team sheet: [Drupal10_Defects-MobTest Google sheet](https://docs.google.com/spreadsheets/d/1R4g9jSZJvGRCAWWoslnxlC2hv5A2kHKMMxabbct3bI4/edit#gid=0)
- [x] I expect that any necessary tickets are made to capture the defects identified.

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [ ] `Public Websites`
- [x] `Facilities`
- [ ] `User support`

**Comment by jilladams** [comment]
@eselkin to shadow

**Comment by jilladams** [comment]
We found: Eli doesn't have his eQip received or submitted, so is not able to access CAG by any means, or SOCKS, therefore no Tugboat access: Therefore cannot help with this testing on his own. If pairing via screenshare works, Max will pull Eli in.

**Comment by maxx1128** [comment]
I have finished my D10 testing and any potential bugs or issues are below:

1. VAMC Facility Page - the static map of the facility location is not rendering, but the UI directional component still is.
![D10 - VAMC Facility static map](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/10790736/b4820eb5-ef36-40f8-9297-70efcdf105b4)

2. "Check your billing, insurance, and payment options" page -  Pay Options link goes to a URL with the DEV subdomain, which is different than the main site.
![D10 - Pay Options Link](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/10790736/978e35a5-66d3-4895-80aa-717ead9d529b)

3. "Benefit Office pages - location / status" page - returning a "not found on server" error.

I also found a few small bugs that were **consistent between the D10 environment and the current environment,** so they may be worth looking into later.

4. The Lovell VA - Policies breadcrumb is not formatted correctly. Other Lovell VA pages do not have this issue.
<img width="1325" alt="D10 - Lovell VA Breadcrumb" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/10790736/3edd6117-e88d-4c69-99ac-93e401fbe87d">

5. VAMC System page link for downloading medical records has (Blue Button) in the link text
<img width="1260" alt="D10 - VAMC System Link Text" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/10790736/ab42eabf-9999-46d2-9cee-6b9e94b6211d">

**Comment by jilladams** [comment]
@maxx1128 please verify the ACs here before you close.

**Comment by maxx1128** [comment]
Opened the below two tickets from what was found at the testing:

1. https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14596
2. https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14597

**Comment by jilladams** [comment]
Max tied it up, closing!
