### ISSUE TITLE
D10: Uncaught TypeError: $(...).once is not a function

### ISSUE THREAD

**Issue by dsasser** [department-of-veterans-affairs/va.gov-cms#14391]
## Description
jQuery error in console on many (all?) D10 pages:

![Screenshot 2023-07-17 at 10 33 10 AM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/221539/1a8539e9-6e5d-441b-b1d4-5af2e0575396)

## Acceptance criteria
- [ ] Error is resolved

**Comment by omahane** [comment]
The effects of this error are manifold, as suggested by the console error.

One such effect is the text counters are not available to editors:
![Screenshot 2023-07-19 at 9 04 30 AM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/766573/cf52c982-bb60-4cdb-a13f-691143aab305)
![Screenshot 2023-07-19 at 9 07 32 AM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/766573/9cbcfe9b-c29d-484a-bee6-cfd7f9093e86)
![Screenshot 2023-07-19 at 9 11 44 AM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/766573/525e5119-c511-4a9e-afdb-37b397b37144)

**Comment by dsasser** [comment]
@omahane @edmund-dunn just FYI I'm actively working on the solution here which involves combining two d.o patches:

https://www.drupal.org/files/issues/2022-08-04/textfield-counter-incompatible-with-claro-3182675-10.patch
https://www.drupal.org/files/issues/2023-05-15/textfield_counter-d10once-3358129-4.patch

As I type this, I see @edmund-dunn you have effectively done this, but I'll add that the reason textfield_counter-d10once-3358129-4.patch would not apply for you is because the existing patch textfield-counter-incompatible-with-claro-3182675-10.patch is conflicting. So the #5 patch is not going to apply unless others also have first applied textfield-counter-incompatible-with-claro-3182675-10.patch.

```
▶ git apply textfield_counter-d10once-3358129-5.patch
error: patch failed: js/textfield_counter.js:37
error: js/textfield_counter.js: patch does not apply
```

**Comment by omahane** [comment]
Text counters are now showing in the Tugboat environment.
<img width="1796" alt="Screenshot 2023-07-21 at 8 48 25 AM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/766573/62662d4f-3037-48d0-be88-a4cc89afc918">
