### ISSUE TITLE
DevOps Engineers Require OKTA Membership to Access Datadog

### ISSUE THREAD

**Issue by olivereri** [department-of-veterans-affairs/va.gov-cms#14396]
## Description
The CMS DevOps team manages application and infrastructure monitoring, alerting, and metrics in a FedRAMP, VA DevOps Transformation Services (DOTS) managed instance of Datadog. To effectively manage metrics, monitors, and alerts regarding the availability, reliability and other aspects of the CMS, DevOps Engineers need to be enrolled with OKTA. OKTA is an identity provided managed by DOTS that allows federated access to other VA managed applications, more importantly Datadog.

## Acceptance Criteria
- [x] CMS Team members requiring access to Datadog are identified.
- [x] CMS Engineers are registered with MAX.gov
- [x] CMS Engineers follow documentation to open a Support Request to access Datadog.
- [x] CMS Engineers successfully access Datadog

## Implementation Details
https://vfs.atlassian.net/wiki/spaces/OT/pages/2233598117/Get+Access+to+Datadog

### Team
Please check the team(s) that will do this work.

- [x] `CMS Team`
- [ ] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`

**Comment by teeshe** [comment]
Attempted to request access to [dots-va.okta.com](http://dots-va.okta.com/), so I can have access to the Datadog platform. I am unable to logon to Dots-va-okta using my PIV card, I get the error below. I have tried using a different browser and tried from the Citrix environment, but I encountered the same error.

_"Certificate validation failed. Try again by quitting the browser then selecting another certificate"_
![unnamed](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/39352093/31d9b315-38f1-4bb9-8281-ef9c8a2b912d)

**Comment by ndouglas** [comment]
@teeshe You might try rebooting or disconnecting and reconnecting the PIV reader. I've seen some misleading error messages.

**Comment by ndouglas** [comment]
Or it might be this: https://dsva.slack.com/archives/C01U8EYHSEM/p1690479479842099

**Comment by ndouglas** [comment]
I'm going to go ahead and close this since Tolase, Edmund, and I all have access now. I added an entry to Ari's onboarding ticket (see #14651) that can use this for reference.
