### ISSUE TITLE
Spike: header & footer investigation

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#14416]
## Description
The header and footer for VA.gov are React components that currently get dropped into Liquid templates to be rendered in content-build. Additionally, there is a so-called 'injectable' header which gets used in some scenarios (i.e. Teamsite sites). 

We need to determine how to proceed for Accelerated Publishing. Potential options include but may not be limited to:

* Setting up a template for the header and footer which contains a location for the React component to render into at viewing time (similar to current content-build)
* Using the injectable header/footer
* Including the component directly at build time (i.e. including the header/footer as a package to be utilized during build) i.e. using npm/yarn to include the header/footer components into our own build

Some options may be able to be quickly dismissed (for example, there is already agreement that the injectable header/footer is not a good solution for Next Build). For other solutions, we should evaluate:

* difficulty/LOE for executing the solution
* stability and functionality for the Veteran
* whether the solution would introduce any stability or functionality issues elsewhere in the ecosystem
* How the data could be sourced (written in-page like current content-build, written to a static file like 'KISS', retrieved from a live API endpoint), with pros, cons, and anticipated LOE for each; note that we're not asking for detailed implementation investigation for any of these options, only what pros and cons each would present for rendering the header/footer

## Acceptance Criteria
- [ ] Solutions for inserting & rendering the header & footer are identified and documented in this ticket
- [ ] Each solution is evaluated for LOE, stability, etc

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [ ] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`
- [x] `Accelerated Publishing`

**Comment by ryguyk** [comment]
WIP

# Header/Footer Spike Findings
## Possible approaches to rendering the header and footer on pages generated by next-build

### 1. Create templates that match those in content-build (recommended approach)
#### How it works
This approach would effectively copy the way content-build handles this. Notably, the header and footer are currently React components managed in vets-website. In content-build, there are templates that amount to wrapper/skeleton templates that provide `<div>` elements into which the header and footer can mount. We likely can and should copy this approach.
#### Benefits
- Would require no change to the header/footer components in vets-website.
- Of the possible models to follow for next-build, content-build seems the most natural, as that is the functionality we are mostly going to be replacing/augmenting.
#### Drawbacks/Risks
- The header template is a bit more than just a "simple" wrapper. There's a little more going on, and we'd have to copy that markup into next-build, which feels not very DRY.
- In this approach, the vets-website code expects the header/footer data to be on the `window` object at page load. This is done in content-build by including a `<script>` tag directly in the HTML `<head>` that, once loaded in the browser, parses the JSON data into a JS object and drops it on the `window` object. This brings up the question of how we're going to get the data into the template:
   - Option 1: Write new queries (JSON:API) to generate the header/footer data, along with new normalization code to structure the data as is expected by the existing vets-website components.
   - Option 2: This data is also made publicly available at `/generated/headerFooterData.json`. That's done via content-build, so we'd eventually need to do option 1 if content-build goes away, but, until then, we could make use of this file to kick that can down the road. **Importantly, this would preclude header/footer changes from "accelerated publishing".**

### 2. Use "injected header"

### 3. Import existing components directly into next-build

**Comment by tjheffner** [comment]
Out of everything written here, I lean towards option 1 with a path towards option 4. 

We should be able to either re-use the generated data file, or output the headerfooter data to an equivalent json file in next-build using an /api/ route. that api route can be hit & revalidated and components should be able to fetch data from that file on the client side.

I hesitate to subscribe us to any rewriting of vets-api components with the timeline on this contract. Feels like a future state to me.
