### ISSUE TITLE
Support Cross-Product D10 Testing

### ISSUE THREAD

**Issue by productmike** [department-of-veterans-affairs/va.gov-cms#14413]
## User Story / Task
Coming out of the cross-team sync on D10 test planning on 7/18, we need to ensure we provide space to support testing.

## Acceptance Criteria
- [x] Drupal team, PM, DM review CMS components ([mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/vagov6717/1646745279937/9a5570c420939d84e875e8334fd73073e3a3971b?fromVisitorModal=true&sender=ub3a2c2a4de441f561d452324)) to determine our expectations on which are core vs. product.
- [x] Manual vs. automated testing indicated for future test case building.
- [x] Component diagram shows cascading impacts product should test but is completed by core CMS team.
- [x] Component diagram shows functions that are governed by core CMS but can be customizable by products (e.g. login, permissions, menus, etc.)
- [x] Establishing the feedback loop with the downstream products. 
- [x] Review component diagram with downstream products and POs.

**Comment by productmike** [comment]
@tonytaylor @edmund-dunn @ndouglas Could one of y'all either update the mural by indicating which have automated testing vs manual? It's a hurdle to completing a sprint goal, so need to get it wrapped up sooner than later. I can do it as well if you could provide me a list of those that have cypress tests. Thank you!

**Comment by ndouglas** [comment]
@productmike to be honest I can't keep my Mural seat open.

There are dedicated, content-type-specific tests for creating the following content types:

- banner
- basic_landing_page
- campaign_landing_page
- checklist
- documentation_page
- event
- health_care_region_detail_page
- landing_page
- office
- person_profile
- step_by_step

These tests are generally fragmentary, just filling out the minimum required fields.

Some others have tests of specific functionality, but I don't believe they're comprehensive.

See also these issues:
- #12611
- #12499
- #12498
- #12497
- #12496
- #12495
- #12494
- #12493
- #12492
- #12491 
- #12490 
- #12489 
- #12488 
- #12487 
- #12486 
- #12485 
- #12484 
- #12483 
- #12482 
- #12481 
- #12480 
- #12479 
- #12478 
- #12477 
- #12476
- #12475 
- #12474 
- #12473 
- #12472 
- #12471 
- #12470 
- #12469 
- #12468 
- #12467 
- #12466
- #12465 
- #12464 
- #12463 
- #12462 
- #12461 
- #12460 
- #12459 

These are tickets that would be necessary to establish minimal _required_ functionality for all of our content types. That doesn't include weird custom behaviors like fields appearing and disappearing when we click one widget or another, or de-duping some things, custom form validation, etc. A lot (many? most?) of those special cases are already covered, but they aren't collected by content type or product.

**Comment by productmike** [comment]
Dang. I'm somewhere in between 'thanks @ndouglas' and 'thanks @ndouglas' (with a sarcastic tone), lol. In any event it's a start and I'll do my best to close this out today.

**Comment by ndouglas** [comment]
![460](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/1318579/d1989a1f-fd45-4550-8cb1-d33041639c4f)

**Comment by productmike** [comment]
Updated the ACs to more accurately reflect the essence of the ticket -- which was to assess automated vs. manual testing -- which Nate's comment above outlines. I'm still going to incorporate this into documentation, but for purposes of this ticket, we can consider closed.
