### ISSUE TITLE
PW: Drupal 10 upgrade testing

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#14414]
CMS Team has Drupal 10 ready to test. Tracking our work.

## CMS comms: 

Rules of Engagement as of 2023-11-08
https://dsva.slack.com/archives/C03LFSPGV16/p1699463805306319

*Rules of Engagement for Testing:*
- Product teams (Facilities and Public Websites) should test modules and functionalities specific to your respective products to identify any defects
- CMS team will be using [this master spreadsheet](https://docs.google.com/spreadsheets/d/1R4g9jSZJvGRCAWWoslnxlC2hv5A2kHKMMxabbct3bI4/edit?usp=sharing) to house all the tracked defects
- Your respective team can use your own D10 testing tracking spreadsheet to conduct the testing, but please also populate the [CMS master spreadsheet](https://docs.google.com/spreadsheets/d/1R4g9jSZJvGRCAWWoslnxlC2hv5A2kHKMMxabbct3bI4/edit?usp=sharing) so that CMS Team can triage and address issues as they come in
- All defects and/or associated information need to be provided to CMS team by the testing close date in order to be reviewed and prioritized accordingly
- Entered information should be answered as fully as possible
- If a screenshot is useful, please send it to your DM or PM for sending along. Rename the image to match the corresponding line # in the xls (e.g. if my issue is line #5 on the xls, then any associated materials should be saved and sent as Line5-[artifact].
- Issues will be triaged as they come in by the CMS team and work will be coordinated with product teams to address any potential blockers.
- Use [#d10-upgrade-testing](https://dsva.slack.com/archives/C05EJD52H1R) slack channel to communicate and collaborate on D10 testing
- Once testing is complete, any remaining issues will be reviewed with PM/PO/DMs to determine go/no-go for deployment.

*Questions?*

- Reach out to CMS team on [#d10-upgrade-testing](https://dsva.slack.com/archives/C05EJD52H1R) slack channel. Thanks all!

https://dsva.slack.com/archives/C03LFSPGV16/p1688749304944389

Rules of engagement for D10 testing as of 7/7 (post may be updated live, please refer to it):

- CMS team will not be responsible for testing modules and functionalities specific to PW and/or Facilities. That is up to those specific products to own.
    - Ownership is loosely based on [History of sitewide product portfolio, teams](https://app.mural.co/t/vagov6717/m/vagov6717/1646745279937/9a5570c420939d84e875e8334fd73073e3a3971b?fromVisitorModal=true&sender=clarencemaeng1702) Mural. 
    - CMS team to conduct additional audit (as of 7/18) to verify any additional shared functionality that either they will test, or they will request teams test.
- Each of the columns/criteria in the [CMS master spreadsheet](https://docs.google.com/spreadsheets/d/1R4g9jSZJvGRCAWWoslnxlC2hv5A2kHKMMxabbct3bI4/edit#gid=0) should be answered as fully as possible. A decision on the priority will be made based on the information entered. (CMS team will do our best to track and nudge you).
- Once a decision is made on if a defect is blocking (or not) to D10 release, the CMS team will not re-evaluate without the associated VA PO written justification.
- The testing open date is ~Monday 7/10~. The link and master spreadsheet will be posted in the [#sitewide-program](https://dsva.slack.com/archives/C03LFSPGV16) slack channel.
- If a screenshot is useful, please send along to your DM or PM for sending along. Or request access to [#d10-upgrade-testing](https://dsva.slack.com/archives/C05EJD52H1R) slack channel. Rename the image to match the corresponding ID # for the line in the xls (e.g. if my issue is ID #5 on the xls, then any associated materials should be saved and sent as ID5-[artifact].
- Test closing date is COB Friday 7/28. ALL defects and/or associated information need to be entered by then. No exceptions as the CMS team needs time to review and plan accordingly for the subsequent sprint.
    - 7/18 meeting with POs/ CMS leadership: testing will begin in Sprint 89, and we will complete as much as possible. CMS Team will hold a go/no-go to verify when we've satisfied enough fixes to ship.
    - P1 blockers are Veteran-facing
    - Editor-facing issues will be a judgment call re: whether they do / don't block launch.

## PW Testing sheet
[Sitewide testing sheet](https://docs.google.com/spreadsheets/d/136FP-HtxRWJuPYYV4D95ngby96Wqy4Ul_HOgOqEk1K0/edit#gid=1646781269)

**Comment by FranECross** [comment]
@jilladams @dsasser I updated the Description with the most recent 'Rules of Engagement' in Slack and referenced the Slack message link too. Thanks!

**Comment by FranECross** [comment]
Closing; all work has been completed.
