### ISSUE TITLE
Drupal 10 Testing: KISS data verification (supplemental status)

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#14430]
- [x] Facility locator  - confirm [supplemental status KISS endpoint](https://www.va.gov/data/cms/vamc-facility-supplemental-status.json) equivalent exists in D10 demo here https://web-kaaijt1fsqp1qasl6a8metonglihfa26.ci.cms.va.gov/data/cms/vamc-facility-supplemental-status.json

**Comment by jilladams** [comment]
@swirtSJW from planning, we need help understanding the distinctions in how we can / should test this KISS data. Assigned to you to help refine.

**Comment by swirtSJW** [comment]
This is the endpoint for supplemental status on prod https://www.va.gov/data/cms/vamc-facility-supplemental-status.json

so will need to validate that it exists on the D10 version of the build.

**Comment by swirtSJW** [comment]
Data is present in D10 
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5752113/31979b0a-72ed-400e-abfc-1fb9f42d9715)

**Comment by swirtSJW** [comment]
Data is confirmed to be identical.
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5752113/d04a7e1a-6c08-404b-9a1c-77b27cfd7e07)
