### ISSUE TITLE
Redirect Request: VA Form 28-8832 find forms landing page to VA Form 25-8832

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-cms#14436]
### Instructions
- Requests must be submitted **AT LEAST** 2 weeks in advance.  Some requests take a significant amount of time and coordination to implement, so start the process as soon as you know you will need one. 
- This issue will be used from initial request through implementation to ensure all individuals working on this are notified of status updates.  Please do not create multiple issues to track differnt steps.
- It is your responsibility to notify VA stakeholders as appropriate.  

### Type of request
- [x] We are retiring or taking down a page and need to redirect the URL (complete redirect section)
- [ ] We are changing the URL of an existing page (complete redirect section)
- [ ] We need a custom vanity URL (complete vanity URL section)

### Implementation date
When does this request need to be live?
Choose one:
- [ ] On a specific date, connected to a program or publishing requirement. **DATE:**
- [ ] Any day prior to a deadline/latest possible date. **DEADLINE:** 
- [ ] Any day after an earliest possible date. **EARLIEST DATE:**
- [ ] During a specific date range: ***EARLIEST DATE TO LATEST DATE:***
- [x] No hard timing requirements, publish when possible.

### Redirects 
Current URL  |  Redirect Destination or New URL
---  |  ---
https://www.va.gov/find-forms/about-form-28-8832/ | https://www.va.gov/find-forms/about-form-25-8832/

### Process, Roles and Responsibilities
- [x] Requesting team: Above information is provided
- [x] Requesting team: All appropriate VA stakeholders are notified as appropriate
- [x] IA: Request is vetted and documented and implementation plan is clear 
- [x] IA: Request is assigned to appropriate team for implementation 
- [x] Implementation team: Work is complete
  - [ ] [FE documentation](https://github.com/department-of-veterans-affairs/devops/tree/master/ansible/deployment/config/revproxy-vagov/vars)
  - [ ] [strategy doc for context](https://github.com/department-of-veterans-affairs/devops/tree/master/ansible/deployment/config/revproxy-vagov/vars)
- [x] Implementation team: Validated in production
- [ ] Requesting team: Validates everything is correct in production and closes ticket

**Comment by jilladams** [comment]
Sorry y'all - I hopped on this too early based on emails, and missed that it still needs IA review. @jennymayoco shall I move to back to your repo? Or you can review it from here? Fine by me either way.

**Comment by jennymayoco** [comment]
Hi @jilladams no worries, I can review from here!

@RLHecht I noticed that you mentioned form 28-8832 has been archived so it's no longer available. I searched 28-8832 and came across this [online application titled 28-8832](https://www.va.gov/careers-employment/education-and-career-counseling/apply-career-guidance-form-28-8832/introduction). In the [previous breadcrumb](https://www.va.gov/careers-employment/education-and-career-counseling/), the form name has been updated to 25-8832, but when you hover the online application, the URL refers to form 28-8832. Does the [online application 28-8832](https://www.va.gov/careers-employment/education-and-career-counseling/apply-career-guidance-form-28-8832/introduction) need to be redirected as well at this moment?

<kbd>![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/122128479/955f55ab-b905-41b4-b644-dd446aa3d7e0)</kbd>

**Comment by RLHecht** [comment]
@jennymayoco there's a product team working on making the changes to the online form. They are updating the numbers and other info in those pages. That work can be tracked in ticket #61721

**Comment by jennymayoco** [comment]
@RLHecht gotcha, thank you for the background!

@jilladams @wesrowe I'm not able to edit the original ticket, but wanted to update the current URL to `https://www.va.gov/find-forms/about-form-28-8832/` with a forward slash.

Other than that, we are good to go with this redirect.

**Comment by jilladams** [comment]
Per slack, ready for PW to work: https://dsva.slack.com/archives/C01K37HRUAH/p1689948878582749?thread_ts=1689898775.862399&cid=C01K37HRUAH

**Comment by chriskim2311** [comment]
Validated in production, closing ticket
