### ISSUE TITLE
Change management for v1 health service data

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-cms#14449]
## Context

VAMC editors understand that they maintain their websites but likely do not think of it as maintaining the source of truth for services available at their facilities. This has been a separate workstream with different parties responsible.

Currently, PAOs/editors are instructed to contact Lighthouse to update their service information.

With v1, we’ll need to help editors understand that
- the information they enter into Drupal will be the source of truth and
- it is important to keep service information up to date and accurate for Veterans viewing their website
- it is important to keep service information up to date and accurate because the information can be used across the entire ecosystem 

## Problems to solve

- How do we ensure that health service data is maintained and accurate?
- How can we move this to a proactive culture?
- What is the escalation path for resolving errors in health service data?

## Considerations

- Revised/Refresher training?
- Conversations with VHA leadership (i.e. Medical Center directors
- KB articles : new and updated
- Other….

**Comment by jilladams** [comment]
Verified today in VHA DM sync that: https://trello.com/c/eXE2eIHY/7-change-management-health-services-in-lighthouse-v1

- Tasker is running
- Expectations have been set with Editors and the message re; services has been delivered.
- Whenever V1 is ready, VHA DM feels ready.
- % of VAMC editors that have validated services: ~75%

@mmiddaugh going to close this, as we didn't identify any additional work to do here re: Change Management today, but feel free to reopen if you disagree.
