### ISSUE TITLE
PACT Wiz: Design/build start screen for survey-tool prototype

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#14446]
**Suggested by Cindy in sprint planning on 7/17, need clarification in UX refinement**
What Wes came away with from planning: 
`screen with links to start various pieces of prototype`

### User story

**AS A**
**I WANT**
**SO THAT**

## Acceptance criteria

>Consider
> - Design / Accessibility reviews
> - Collab cycle requirements
> - Device sizes (mobile first)
> - Documentation updates / Change management
< - [Content model documentation](https://prod.cms.va.gov/admin/structure/cm_document)
> - Testing notes

- [ ]

**Comment by jilladams** [comment]
Per Cindy, Optimal Workshop may be good enough to just enter this in there as a start screen vs. designing.

**Comment by wesrowe** [comment]
closing as a no-op – Survey Monkey had capability to build intro screen.
