### ISSUE TITLE
Design: Mock PACT Act Wizard results screens to support FE development

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#14444]
### User story

**AS A** Front end developer
**I WANT** to see the "R1" results screens mocked up
**SO THAT** I can more easily understand what I'm trying to prototype in code for research.

### Design

[Sketch file](https://sketch.com/s/2bf4405b-5cc4-4672-88fb-d215abdf3b0d)

## Acceptance criteria

- [x] Danielle and Cindy agreed on which results screens/versions will be shown to research participants
- [x] One pair of R1 results screens mocked up
  - [ ] [optional] If in Figma, the accordions expand/collapse
  - [x] NOTE: Copy can use the draft language provided, does NOT need to be kept current as things evolve
- [ ] Reviewed with Cindy and Danielle to ensure the design is as intended

**Comment by cindymerrill** [comment]
FYI @wesrowe If the screens will be prototyped outside of the survey tool, we'll need a design resource to do it, not me.

**Comment by wesrowe** [comment]
@jilladams @thejordanwood – I repurposed this ticket to support FE dev of the results screens instead of building them. hence I removed the 8-point estimate.

**Comment by cindymerrill** [comment]
@wesrowe @thejordanwood Here's a doc on Sharepoint that shows **one of the two-screen sequences of results screens** that we'd like to mock up for usability testing: 
https://dvagov-my.sharepoint.com/:w:/g/personal/cynthia_merrill_va_gov/EXcXBeLPnthDhzKkq0tHOgkB1hz4H5z-TpljngwAkGniFw?e=WJhfZI
The content isn't final and may change. I can talk you through it when you're ready to look at it.

**Comment by thejordanwood** [comment]
@wesrowe I've created [a Sketch file](https://sketch.com/s/2bf4405b-5cc4-4672-88fb-d215abdf3b0d) with the results screen mockups for this. Do we need to wait until Cindy is back next week to review?

**Comment by wesrowe** [comment]
Yes, @cindymerrill is on top of the content. Also Danielle.

**Comment by thejordanwood** [comment]
**End of sprint update:**

Cindy has reviewed [the Sketch file](https://sketch.com/s/2bf4405b-5cc4-4672-88fb-d215abdf3b0d) and Randi has already set up the design in staging. Danielle is reviewing all of this, but I believe is mainly going to be looking at staging from here instead of the Sketch file (no need to change the content in 2 places). 

@jilladams Given that update, is it okay to close this?

**Comment by jilladams** [comment]
Yes! FYI @wesrowe . Any future changes should route through FE folks with Design review as an AC. Closing.
