### ISSUE TITLE
Add a temporary redirect check to Facility Locator

### ISSUE THREAD

**Issue by omahane** [department-of-veterans-affairs/va.gov-cms#14472]
## User Story or Problem Statement
We want visitors to va.gov to be able to get to the full sites of new facilities even though the CSV that determines the canonical URL is not able to be updated while other work is being finalized by Lighthouse.

## Background
https://dsva.slack.com/archives/C52CL1PKQ/p1689793932442169

## Implementation steps
Either make the check in VaFacilityResult.jsx --> use an `<a>` instead of a `<Link>`

Or create a data object of redirects that we can add to the check. If the ID is among the redirects, the appropriate URL is returned

## Acceptance Criteria
- [ ] I expect that when I find a facility in the Facility Locator that has been redirected, I can click on the facility title and go to the full facility page, rather than the placeholder page

**Comment by maxx1128** [comment]
My opinion is the best approach is the one Ryan described in the Slack thread. Basically, the link needs to use mapping to see what the new URL would be, and if this unique URL uses client-side or server-side navigation. Server-side would need a <a> tag, otherwise, it’s a <Link> component.

**Comment by xiongjaneg** [comment]
Per Christian: CSVs are being updated and the requests are made directly with Lighthouse.
Per Steve: CMS is providing the source of truth until cutover
Marking closed
