### ISSUE TITLE
Analyze footer analytics in advance of research

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#14476]
## Description
In order to create prototyping, as well as a research questionnaire, analytics needs to be analyzed for the existing Header.

### User story

**AS A** PO/PM for the global Footer
**I WANT** to understand how site visitors use the footer links 
**SO THAT** we can see how different content guidance rules might impact current usage..

### Engineering notes / background

From DaveC: 
>As we approach the new header/footer, I'd like to understand the current use of the links in the footer so that we can see how different content guidance rules might impact current usage. (This is a bit of due-diligence here as we look to possibly remove some unnecessary links in the footer)
>In order to do that, I think we should look at analytics on the footer and essentially track the volume of click-thrus we have on each footer link (with the exception of the phone numbers and the Languages).
>So the ac's would be 1/ an artifact that provides the click-thru rate on each link in the footer. 2/ stack rank that click thru rate by-column 3/ attach findings to the usa-header-footer initiative work. We'll also want to have a column to denote whether or not the link is required, and another for stakeholder mapping, but that would be filled out later.
>I'd be interested in your thoughts as to how much data would be useful for this data capture/analysis:  Do you think 1 month's worth of data would be good? 1 quarter? Maybe 1 quarter broken down by month?

## Acceptance criteria

- [x] Picked a timeframe for analysis by looking for overall trends first
- [x] Artifact (table in GH) shows:
  - [x] click-thru rate on each link in the footer
  - [x] links are stack-ranked within their footer sections/columns
  - [x] do bottom two sections (Language, random stuff) in addition to main area with columns
  - [x] describes how best to use GA to get these numbers again
- [ ] Artifact is stored in the usa-header-footer initiative folder in the products repo

**Comment by aklausmeier** [comment]
@jilladams @FranECross would like to surface this ticket and understand if we have analytics for current footer as this could help inform research usability tasks for new Fed Footer, top footer tasks for example. Also, serve as baseline metrics. 

cc @davidconlon

**Comment by FranECross** [comment]
@aklausmeier I'll explore today to determine if there are analytics available, and then can compile and provide. I'll keep you all updated on findings. 

cc @jilladams @davidconlon

**Comment by aklausmeier** [comment]
@FranECross @jilladams flagging as a possibility of needing prioritization and would we also want analytics on header? 

CC @davidconlon

**Comment by FranECross** [comment]
Thanks, @aklausmeier ! I'll put this on my to do for this week and will reach out with any questions, and/or with updates. I agree analytics on the header is needed as well. I'll create another ticket for that.

cc @jilladams @davidconlon

**Comment by FranECross** [comment]
@aklausmeier Closing the loop here (I also posted in Slack)... I've gathered and organized the footer analytics and provided to Cindy for her use. Attaching here and will also add to the Product Initiative. Please let me know if you have any questions. Thanks! cc @jilladams @davidconlon 

[Google Sheets link](https://docs.google.com/spreadsheets/d/1sYWZMuSq6Qv8zEouYS77U-pen3z6CYU9t55Vu1nA1a0/edit#gid=1353535298
[VA.gov Footer Analytics Baseline & Other Info.xlsx](https://github.com/department-of-veterans-affairs/va.gov-cms/files/13379897/VA.gov.Footer.Analytics.Baseline.Other.Info.xlsx)
) here, and excel document also attached.
