### ISSUE TITLE
Spike: Investigate app router functionality

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#14474]
## Description
https://nextjs.org/docs/app

> The App Router is a new paradigm for building applications using React's latest features. If you're already familiar with Next.js, you'll find that the App Router is a natural evolution of the existing file-system based router in the [Pages Router](https://nextjs.org/docs/pages).

> For new applications, we recommend using the App Router. For existing applications, you can [incrementally migrate to the App Router](https://nextjs.org/docs/app/building-your-application/upgrading/app-router-migration).

## Acceptance criteria
- [x] Identify pros/cons of moving to App Router (App Router vs. Pages Router)
- [x] Determine if App Router use is compatible with next-drupal
- [x] Document what steps are necessary to migrate next-build from Page router to App router

**Comment by ryguyk** [comment]
WIP

## Overview
According to Next.js documentation, [App Router is the suggested path](https://nextjs.org/docs/app) for building new applications. The documentation also provides a [guide for incremental adoption](https://nextjs.org/docs/app/building-your-application/upgrading/app-router-migration) for applications that were initially built using the Pages Router.

Our application is not "new", per se, but it is relatively green and probably a really good time to consider migrating. This spike is aimed at determining the pros and cons of that move, as well as the lift.

## Pros/Cons
### Pros
- It seems like App Router is the paradigm that will be supported going forward. This is not to say that Pages Router is deprecated. It is not. But it feels very noteworthy that the Next.js team suggests using the App Router.
- App Router allows for server components, which could eventually have a significant positive impact on the javascript bundle size we send to the browser. Currently, with vets-website handling almost all of the browser javascript, it seems like this might not matter. However, components are client components by default, and even 
### Cons
- Revalidation is handled differently in App Router and it [might be a regression](https://agilesix.slack.com/archives/C05ECJY87NG/p1690575655277529).

## Steps to migrate to App Router
