### ISSUE TITLE
VBA Regional Offices: MVP National Rollout

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#14477]
## Background

Following the VBA RO MVP Pilot rollout #10514, we will iterate with VBA through onboarding more editors across the country. It is likely that Editors will be onboarded in waves, though the waves are not yet defined (04/2024). 

As of 4/8/24, National rollout will include: 
* Editor trainings, in conjunction with CMS
* Editor research sessions
* Bug fixes for issues identified during editor onboarding.

## Decision log
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/regional-offices/initiatives/2024-national-mvp/decision-log.md

## Definition of Done
- ~Selected features are updated / added~
- Rollout runbook is updated for National roll out

**Comment by jilladams** [comment]
@mmiddaugh @davidpickett 
From product sync: 
* Will be a next set of VBA editors, not the full set of National editors. We don't know how many. 
* Will _not_ include feature updates as "post-MVP." Will only be editor onboarding, content entry, and bug fixes for any issues identified during the process.

TO DO: @jilladams split out enhancements into a VBA enhancements epic (a la #15712 for Vet Centers)

**Comment by jilladams** [comment]
* Post-MVP epic created to track enhancements list to consider for future iterations: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17782
* National rollout decision log created: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/regional-offices/initiatives/2024-national-mvp/decision-log.md
* Ticket body updated with notes from today's discussion with Michelle, both in epic body here and in decision log
* Moved many tickets over into the post-MVP enhancements epic. 

Things I left in this epic are UX items or bugs we likely do need to address in this timeframe, or things I'm not sure about their criticality. (cc @davidmpickett )

**Comment by Agile6MSkinner** [comment]
An analytics request is in progress on the collab cycle epic, so that epic will remain open until it runs its course. But all VBA Regional Office Modernization development is done. Closing this epic and the super epic to which is belongs.
