### ISSUE TITLE
Create new KB articles to support VBA editors and Regional office roll-out

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-cms#14482]
## Description
New KB articles need to be created to support VBA editors as they create and maintain the content for their Regional offices.
These articles should include the purpose of the content, instructions for creating it, requirements, examples and best practices. 

They can be modeled after Vet Center KB articles but tailored to the specific content and data for VBA regional offices. 

## Landing page
To include
- Product purpose 
- Links to How to guides
- Links to Training videos
- Information about the publishing process

## "How to" guide topics

- [X] [overview](https://prod.cms.va.gov/help/veterans-benefits-administration-vba/benefit-office-overview)
- [X] [location and contact info](https://prod.cms.va.gov/help/veterans-benefits-administration-vba/location-and-contact-information)
- [X] [facility photos](https://prod.cms.va.gov/help/veterans-benefits-administration-vba/vba-facility-photos)
- [X] [spotlight](https://prod.cms.va.gov/help/veterans-benefits-administration-vba/vba-spotlight-content)
- [X] [Prepare for your Visit](https://prod.cms.va.gov/help/veterans-benefits-administration-vba/prepare-for-your-visit)
- [X] [banner alerts](https://prod.cms.va.gov/help/veterans-benefits-administration-vba/banner-alerts)
- [ ] services

**Comment by mmiddaugh** [comment]
articles are complete and available in prod 
@xiongjaneg does this need to be sent for review to the CMS team?

**Comment by xiongjaneg** [comment]
@mmiddaugh I cleared with Berni and Marcia so that they are aware but they will not be formally reviewing due to competing priorities on their plates in the next sprint.

You may need to discuss future state KB review process with Erika once the new team has access to VA technologies.

**Comment by jilladams** [comment]
Closing since the articles are live in prod. If we want a separate ticket for CMS team review, we should cut that separately.
