### ISSUE TITLE
SAML Module Upgrade Failure Investigation and Path Forward

### ISSUE THREAD

**Issue by olivereri** [department-of-veterans-affairs/va.gov-cms#14494]
## Description
July 20th's SAML module upgrade ended in failure. This issue will investigate the failure and develop a path forward to an eventual successful deployment. The previous issue is referenced in "Related issues". 

## Acceptance Criteria
- [x] Technical path forward determined 
- [ ] Technical solution is implemented and D10 upgrade unblocked by phpSimpleSAML

## Related Issues
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14246

## Implementation Details
The PIV logon failures for prod.cms.va.gov are captured in the below error log:
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/31904439/c9dd8f86-e384-4bb1-9534-fbd27a3deaa4)

This error indicates that the public certificate installed to validate signed responses from the Identity Provider are invalid. On the night of the upgrade, in coordination with the Identity and Access Management (IAM) team, the public certificate was confirmed as correct.  The suspicion now is that the response was being signed by a different key that doesn't match the public certificate installed.

On July 24th a test on CMS-Test Staging was conducted by installing a valid but incorrect public certificate for signature validation:
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/31904439/43ed45d1-5ea2-46a7-b22b-b8ba779d9a36)

The error response, while having a different severity, is the same as observed on July 20th.

### Team
Please check the team(s) that will do this work.

- [x] `CMS Team`
- [ ] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`
- [ ] `Accelerated Publishing`

**Comment by olivereri** [comment]
I've reached out to the IAM team. They understandably have reservations about integrating test.staging.cms.va.gov. They had suggested creating a new integration and we can create a new server/environment. I mentioned that we have test.prod.cms.va.gov so we may go that way.

I did ask whether or not the response was signed by a different private key and they said now. Stating that: `There are a total of 103 federation partners in Partnership model (which we are using for CMS) that are currently active in PROD (including current CMS integration) without any issues.`  I get the sense they think this problem sits chiefly on our side.

**Comment by edmund-dunn** [comment]
Talked to the maintainers. They concur it was most likely the cert. ![CleanShot2023-07-26at07.46.14.jpg](https://images.zenhubusercontent.com/62e017d215adbc33b1310f7b/bfdc6a27-d3de-4ef2-a0c5-17347282423d)

**Comment by mchelen-gov** [comment]
To clarify, the upgrade here refers to moving from https://www.drupal.org/project/simplesamlphp_auth to https://www.drupal.org/project/samlauth right?

**Comment by olivereri** [comment]
> To clarify, the upgrade here refers to moving from https://www.drupal.org/project/simplesamlphp_auth to https://www.drupal.org/project/samlauth right?

@mchelen-gov That is correct.

**Comment by olivereri** [comment]
@olivereri @mchelen-gov @EWashb @teeshe @edmund-dunn @BerniXiongA6 met to discuss SAML troubleshooting efforts and possible paths forward.  We came to the conclusion that SAMLAuth testing should be done to reproduce the issue or be used to learn from a working standard. This is instead of progressing with miniorange's module using SimpleSAMLphp because there are blockers due to funding lead times and a trail period shorter than we need.

**Comment by productmike** [comment]
Shifting back to READY FOR SPRINT since this is not committed work for S91. Can be pulled in if timelines are shorter than expected.

**Comment by EWashb** [comment]
Can we get an update on these tasks? I know we went with one SAML module over another so I'm unsure if all of these tasks are still appropriate for our path forward @teeshe @edmund-dunn
