### ISSUE TITLE
URL Change: Fort Polk VA Clinic -> Fort Johnson VA Clinic [Ready to go]

### ISSUE THREAD

**Issue by TroyA6** [department-of-veterans-affairs/va.gov-cms#14508]
### Instructions
(Note: This issue will be used from initial request through implementation to ensure all individuals working on this are notified of status updates.  Please do not create multiple issues to track different steps.)
- [x] Notify VA stakeholders as appropriate.
- [x] Link the related facility closure / rename issue - https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14509
- [ ] Create a URL redirect in the [devops](https://github.com/department-of-veterans-affairs/devops) repo in `ansible/deployment/config/revproxy-vagov/vars/redirects.yml`
- [x] Add the "Awaiting redirect" flag to the facility node with a revision log message that includes a link to this ticket, preserving the node's current moderation state.
- [ ] Redirects deploy weekly on Wed. at 10am ET, or by requesting OOB deploy (of the revproxy job to prod) in #vfs-platform-support. After deploy, validate that the URL redirect is deployed. (Note: In the event of a facility closure or a name change,  validate that this occurs before making the Lighthouse csv changes.)
- [ ] Update this ticket with a comment that the redirect has been deployed.
- [ ] Remove the "Awaiting redirect" flag on the facility node with a revision log message that includes a link to this ticket, preserving the node's current moderation state.

### Implementation date
When does this request need to be live:

### Redirects
| Current URL  |  Redirect Destination or New URL |
| ---  |  --- |
| [https://va.gov/alexandria-health-care/locations/fort-polk-va-clinic](https://va.gov/alexandria-health-care/locations/fort-polk-va-clinic) | [https://va.gov/alexandria-health-care/locations/fort-johnson-va-clinic](https://va.gov/alexandria-health-care/locations/fort-johnson-va-clinic) |

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [ ] `Public Websites`
- [x] `Facilities`
- [x] `User support`

**Comment by stefaniefgray** [comment]
@jilladams @Dottisea Ready for this sprint 🚀

**Comment by stefaniefgray** [comment]
See linked ticket: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14509

**Comment by omahane** [comment]
@TroyA6 @stefaniefgray We also need the CSV change portion of this ticket created.

**Comment by omahane** [comment]
Also these redirects should be from va.gov, not prod.cms.va.gov.

**Comment by TroyA6** [comment]
@omahane @stefaniefgray - Thank you for the feedback Christian - URLs have been changed from 'prod.cms.va.gov' to 'va.gov'
Closing this request in favor of [14614 ](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14614)
