### ISSUE TITLE
Facility Locator research: draft a strategy

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#14516]
# Description
Based on the review and subsequent FE tickets from #14798 and on a scheduled research discussion meeting (9/27), determine which areas will need research and draft a plan.

## Typeahead search functionality
- **Purpose:**  initially to support expanded VA health, plus Vet Center services and new benefit taxonomy in the future (because the current dropdown list cannot support ~100 services)
- **Strategy:** Examine feasibility of testing with live prototype. Has this interaction been tested by other teams? What's the lift? Initial spike to explore complexity / options before committing to developing prototype or research plan
- Questions
  - Are Vet Center service searches in or out of scope?
  - Will this use a prototype, and if so, how will the prototype work? Will we ask them to search for particular type(s) of care?
- Hypotheses to consider
  - Veterans are not confused by the use of typeahead search for some facility types but not all. 
    - between VA health and Community care
    - between VA facility types with plain language service search and those with dropdown service selection 
  - Veterans understand how to select a suggested term
  - By presenting "popular suggestions", we can help Veterans understand what sort of entry is expected. 
  - Veterans can find another way to successfully search for a facility when their search terms do not match the words from the taxonomy
- FE issues
  - [#14993 Update Facility Locator search by service to allow plain language search](https://app.zenhub.com/workspaces/sitewide-facilities-639f5253e4b702a32376339e/issues/gh/department-of-veterans-affairs/va.gov-cms/14993)

## Improved mobile map experience
- **Purpose:** to make the relationship between search results and indicators on the map more implicit
- **Strategy:** Testable with static prototype, feature has clear Veteran value and is a unique interaction. Develop tickets for building prototype and developing research plan.
- Hypotheses to consider
  - Veterans will understand how to get information about a particular location from the map. 
- FE issues
  - [Update Facility Locator results to show location number, name, distance, and TTY #14912](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14912)
  - [Update Facility Locator results mobile map for location number, name, distance, and TTY #15304](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15304)

## State level search
- **Purpose:** to fulfill NCA request
- **Strategy**: Not high priority feature for testing, could be built and shipped with a staging review.  Could be incorporated as an optional task in a research plan if timing is right.
- Hypotheses to consider
  - Veterans want to search for different types of VA locations using something larger than the current radius limitation
  - Veterans will understand how to filter the list of search results to be more meaningful for them 
- FE issues:
   - [Update Facility Locator API to search by state #14915](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14915)
   - [Build new Facility Locator search by state page #14916](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14916)
   - [UI for new Facility Locator search by state results #15300](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15300)
  
## Search result filter
- **Purpose:** initially to support Community care provider training, home health and telehealth designations, but designed for expansion in the future
- **Strategy:** Community care provider training filter alone is not a high priority. Wait until more filters options are ready and then test filters
- Question: What information do you need about the Provider training to provide context for research or in the UX?
- Hypotheses to consider
  - Veterans will understand how to apply the filter to search results.
  - Veterans will understand how to remove the filter to see more results.
  - Veterans find value in using this type of filter to narrow search results. 
  - Veterans find the filter category labels meaningful.
- FE issues
  - [Update Facility Locator search with filters for training and types of care #14913](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14913)

# Acceptance Criteria
- [x] Research strategy is discussed
- [x] Tickets are created for research plan steps

**Comment by davidmpickett** [comment]
Meeting has been rescheduled to 9/27

**Comment by xiongjaneg** [comment]
Michelle on research priorities:
High priority but higher effort: typeahead search
Mobile map: no brainer
Low priority: provider search

**Comment by xiongjaneg** [comment]
Amanda: technical feasibility of how to research typeahead is an unknown

**Comment by xiongjaneg** [comment]
Michelle and Alexis: At what point is something needed to be built before you can research.

**Comment by xiongjaneg** [comment]
Dave on next steps:
Typeahead search: ask other teams about past/existing typeahead functions
Mobile map: research valuable and worth putting in the time in Q4
State-level search: could be built and shipped with a staging review
Provider filter: not at place where research would be helpful

**Comment by aklausmeier** [comment]
@davidmpickett @thejordanwood @ALogsdon3 

Typeahead search functionality is part of the [Search Input component](https://design.va.gov/components/search-input) in the VA Design System.

>The Search input component lives in the global header of VA.gov and on search results pages, and can be paired with type-ahead functionality. Type-ahead displays up to five suggested search terms in a dropdown below the Search input field while the user is typing a query. The goal of type-ahead is to help Veterans navigate to relevant content more quickly by providing them with suggestions that match the characters they type.

There was a [previous effort (link)](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/637) done for adding as an experimental design component process which included research and it was approved.

**Comment by davidmpickett** [comment]
Re type-ahead

- This [research study](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/on-site-search/research/user-research/research-study-jan-2021/research-findings.md) that included typeahead was conducting on Staging as opposed to a prototype.

**Comment by davidmpickett** [comment]
Output update:
- Created spike ticket for exploring type ahead search research: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15543
- Created a new epic for consolidating FL tickets related to the Search Type field: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15541

**Comment by davidmpickett** [comment]
Created new epic for mobile map usability testing: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14518

**Comment by davidmpickett** [comment]
@xiongjaneg @mmiddaugh This ticket is complete from my perspective. We'll take a look at the follow up tickets I created during UX refinement right noooow

**Comment by xiongjaneg** [comment]
Tickets stubbed and discussed in UX refinement. Questions documented. Closing.
