### ISSUE TITLE
UX: synthesize previous editorial research / make recommendations

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#14528]
## Description
Collaborate with CMS UX to review previous editorial research and make recommendations.

@EWashb worked on early VBA RO development and has offered to share her insights.

@joagnitti did this to some extent as her first project, re: editors of CMS products broadly (meaning: Facilities, as Fac products are the only ones to have had Editor research conducted. e.g. COVID facility status, Blake has done some).

* Jo's meta-analysis https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13019
* Dig deeper into Vet Center Dashboard Usability Study
  * [Research Plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/research/vet-center/vet-center-dashboard-research-plan-Oct-2021.md)
  * [README](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/research/vet-center/README.md)
  * [Readout](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/research/vet-center/Vet.Center.Dashboard.Usability.Study.Read.Out.pdf)

Check out [Michelle's comment below](https://app.zenhub.com/workspaces/sitewide-facilities-639f5253e4b702a32376339e/issues/gh/department-of-veterans-affairs/va.gov-cms/14528#issuecomment-1760018496) for  input/observations from the last 4-6 weeks of Vet Center editor contact.

Also, CMS Team has a [ticket to collect data on editor experience](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15246) that might be helpful to share info on.

## Goals
* Learn from the Editor UX research that has come before
* Review Vet Center Dashboard (springboard) approach vs. VAMC approach, and distill good ideas from bad ideas for VBA
* Understand what we already know isn't working well, and how we could optimize it for VBA
* Understand existing patterns / good things, and use them
* Determine how we can get through Editor UX with minimal time investment
  * Call out blind spots
  * We can identify things that we could work with our VBA RO pilot folks to hallway test / get feedback

## ACs
- [x] Existing editor research is reviewed ~~with Jo on CMS Team~~
- [x] Insights and gaps are identified and documented
- [ ] ~~Recommendations are provided for the VBA editorial interface, based on Vet Center Dashboard (springboard) approach vs. VAMC approach~~
   - [ ] ~~Recommendations are documented on the next step dashboard design ticket~~
- [ ] ~~Usability research findings are reviewed to make a recommendation re: how we should proceed with CMS editor research based on findings~~
- [x] Meeting to review findings is scheduled 
- [ ] Follow on tickets are created as needed

**Comment by davidmpickett** [comment]
In scrum today, we discussed this a possible for me to pick up later this sprint depending on capacity and other UX priorities

**Comment by davidmpickett** [comment]
Discussed as possibility for Sprint 94 in [Facilities Refinement](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14087) today

**Comment by mmiddaugh** [comment]
The following needs are based on repeated questions from Vet Center editors (both new and experienced) during Vet Center office hours or submitted directly to me over the last 4-6 weeks.  These may be areas where we can improve the editorial experience as we think about supporting VBA editors
- How do I change my Vet Center's address/phone/hours of operation? 
  - We link to the KB article from the data but the question still comes up _weekly_ during office hours and/or by DM
- How do I update the photo of my Vet Center? 
  - We have a KB article on how to add one for the first time but don't link to it in the editorial experience 
  - We do not have guidance of any kind for removing/replacing in the editorial experience or KB
- When will my changes be visible on the site? How do I know if I saved them correctly?
- How do I add a Community Access Point?
  - The affiliated locations appear below the dashboard but aren't immediately visible on the screen without scrolling so they get missed. 
     - somewhat related:  during the initial roll-out, editors frequently added their Mobile Vet Center separately because they didn't realize it was already affiliated - we ended up with lots of duplicates 
- How do I remove a Community Access Point which recently closed? 
  - "Edit" is the only option available in the Satellite location list. To archive a location, editors must choose "edit", scroll to the bottom of the page which opens, and select "Archived" from the dropdown list in the editorial workflow. 
  - Also, the "edit" option was not available to content editors until they were promoted to content publishers. This made it hard for new editors to correct their own errors during the initial roll-out. 

Other observations 
- We should refer to something using the same name/term consistently. (i.e., we say "Spotlights" but the editorial experience labels them "Featured content")
- We should make it easy for editors to access self-help when and where they need it.

**Comment by davidmpickett** [comment]
Spoke with @ALogsdon3 this morning and discussed action items:

- @ALogsdon3's first focus is shifting context from VA.gov users to Drupal CMS users. She has not had much exposure to the Drupal side of our products yet and will need time to build context and understand existing state of affairs
- First action item for @ALogsdon3 is to read Jo's meta analysis and see if any of the recommendations from that might apply to VBA
- next step for me is to clean up ACs and make sure we have clear goals/checkpoints for this sprint and make recommendations for what aspects might need to be broken out
-

**Comment by ALogsdon3** [comment]
@davidmpickett This is unlikely to be something we can do anything about, but the link to the readout for the Dashboard Usability Study has an error code: "Unable to render code block"
platform/cms/research/vet-center/Vet.Center.Dashboard.Usability.Study.Read.Out.pdf

**Comment by ALogsdon3** [comment]
Created a Mural for identifying themes in past research: https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1697569400651/92298ea4aa3b0e64d71b6305a7d95e56261f4cf1?sender=u3f35bedf61955cb051f44770

**Comment by ALogsdon3** [comment]
I've identified the insights most likely to be relevant to VBA Editor design. [This link](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1697569400651/92298ea4aa3b0e64d71b6305a7d95e56261f4cf1?wid=0-1698078597376) should take you directly to the relevant section, but feel free to look through the other sections to see how I distilled and grouped things. 
You'll also notice that the Gaps section is empty. That's where I could use some help! I'm not sure who exactly to tag here, but to start I'll ask @thejordanwood @davidmpickett @mmiddaugh and @aklausmeier to have a look and tell me what you think.

**Comment by ALogsdon3** [comment]
Re: the "Follow on tickets are created as needed" AC: @xiongjaneg I think a ticket to look through the help desk tickets relevant to Editor experience would be appropriate. 
Re: "Meeting to review findings is scheduled AC": I think we talked about potentially using time in UX refinement to discuss this but I'm going to be out for a conference and won't be there. If I were to schedule a meeting to review findings, who should be invited?

**Comment by xiongjaneg** [comment]
@ALogsdon3 Let's "schedule" it for next week's UX Refinement and call that AC done. How does that sound?

**Comment by jilladams** [comment]
Per plannin gconvo, UX refin ement will cover follow on tickets.

**Comment by davidmpickett** [comment]
I think some of these insights will very naturally be able to be pulled into this future ticket: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14888

For example "Aim to give Editor- and Veteran-facing labels the same name whenever possible." has implications for **Prepare for your visit** / **Location services**

![Screenshot 2023-10-25 153329](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/e88cb968-9e6b-464d-a66c-d7ebbae002db)

These should probably mirror the way Vet Centers present them as Prepare for your visit accordions

![Screenshot 2023-10-25 153758](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/98e5bc6b-5c62-46e3-b2e3-a1e69de29bd5)
