### ISSUE TITLE
Research: Conduct research: VBA

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#14525]
## Description
Research plan: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/regional-offices/research/2023-06-veteran-facing/research-plan.md

## Ongoing tasks during days with sessions
- [x]  Post to #feedback-backchannel right before session starts with observer instructions and participant description
- [x]  Conduct scheduled research sessions
- [x]  Debrief research sessions w/team
- [x]  Post debrief/updates on slack
- [x]  Debrief research sessions into note-taking spreadsheet
- [x]  Check off completed sessions and record no-shows in [Recruitment Intake Ticket](https://github.com/department-of-veterans-affairs/va.gov-research-repository/issues/362)
- [x] Ongoing observer communications - @davidmpickett 

## Clean-up tasks after all sessions complete
- [x]  Download recordings
- [x]  Download notes from Perigean
- [x]  Download final participant list from Perigean
- [x]  Change display name of Perigean Zoom account back to what it was
- [x]  Close out ticket once all research sessions have been completed (Move to research synthesis ticket)

## Sprint 91 - 3pts
- [x] Conduct 2 sessions scheduled for 8/28

## Sprint 92 - 13pts
- [x] Conduct remainder of sessions scheduled from 8/30 - 9/5
- [x] Complete clean-up tasks

**Comment by mmiddaugh** [comment]
@cindymerrill @ALogsdon3 it looks like the link to the research plan in the description above points to a research plan for income limits - can we update that for future convenience, please?

**Comment by cindymerrill** [comment]
Done, @mmiddaugh ! That was an artifact of Jill having copied the Income Limits research tickets for VBA. Sorry that didn't get updated.

**Comment by davidmpickett** [comment]
Sessions will span Sprint 91 & 92

**Comment by xiongjaneg** [comment]
Once the schedule is finalized, we'll have a better sense of how many sessions will be completed in Sprint 91 and how many in Sprint 92. Once known, this will be added to the description above.

**Comment by davidmpickett** [comment]
@xiongjaneg @jilladams - I updated this with ACs for S91 and S92

**Comment by cindymerrill** [comment]
Added one task to days with research sessions:

- Check off completed sessions and record no-shows in [Recruitment Intake Ticket](https://github.com/department-of-veterans-affairs/va.gov-research-repository/issues/362)

FYI @davidmpickett

**Comment by jilladams** [comment]
Research sessions will continue into S92.
