### ISSUE TITLE
Research: Schedule and prep for readout

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#14527]
## Suggested tasks per Dave's template
**Crafting Recommendations**

Recommendations are key outputs of the research process. They connect your findings back to the product roadmap(s) and shape the experience of future users. Depending on the type of research conducted, recommendations might be narrowly focused on improving a specific interface component of your team's product, or they might have broad implications for multiple parts of the VA.gov ecosystem. Work with your Design team, Product Manager, & Product Owner to generate, refine, and categorize recommendations. PMs and POs also play a key role in socializing recommendations to other teams.

**Research Readout(s) suggestions**
- Work with PM & PO to determine audience(s) and meeting length(s)
- Default to a 30-min meeting with 20 min for presenting and 10 min for discussion
- [Research Presentation Template](https://docs.google.com/presentation/d/13G80avWGdY7tHU40PbP_l05W1yRpDr-opOk0u_AAhzQ/edit#slide=id.g892adcb623_0_141)
  - Consider slimming down this template based on your audience

## Acceptance Criteria
- [x] Findings and analysis are prepped for readout/next UX steps, regardless of presentation format
- [x] Readout scheduled (Assume the readout audience is Amanda, Michelle, Jordan, Dave, and typically Jane, for decision making purposes; and other folks on the team for awareness)

**Comment by xiongjaneg** [comment]
Oct. 4 is the next VBA stakeholder meeting. Report readout is the planned agenda topic.

**Comment by davidmpickett** [comment]
Points, tasks and ACs can be updated at Sprint 94 Planning

**Comment by davidmpickett** [comment]
Updates from chat with @ALogsdon3 and @aklausmeier today:
- We reviewed Alexis's [synthesis in Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1692999071676/faf135ff7c2bb24825ac0529ed16fd4643f59408?wid=0-1695831911893&sender=u9c899abc4fe36c9a698b1647)
- Dave is going to help start [putting slides together](https://docs.google.com/presentation/d/1ayrzpi3RE05WfVEJ43JiqtHmKtLRbl0pKQkqDTH7t0M/edit?usp=sharing) while Alexis focuses on pulling quotes to support findings / additional synthesis (slides in google for now, will migrate to sharepoint later)
- We will discuss areas of opportunity with Product tomorrow in UX Refinement
- Planned scope for RO meeting on Oct 2 is high level findings, not recommendations
- Goal is to have deck for RO meeting ready for review by EOD Monday so feedback/tweaks can happen Tuesday

**Comment by jilladams** [comment]
Readout to happen at Thurs UX refinement; Amanda K working on feedback for EOD Wed in prep for that readout. I _believe_ this can be closed, so am closing, but Alexis: if that's incorrect for some reason, flag for me on Wed morning por favor!
