### ISSUE TITLE
Research: Synthesis & reporting: VBA

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#14526]
### Synthesis
- Organize research notes in an [Affinity Diagram](https://miro.com/blog/create-affinity-diagrams/) to identify themes
- Rewatch session recordings to make additional notes & pull exact quotes
- Illustrate different paths participants took in prototypes (usability testing)
- Conduct statistical analysis
- Revisit the hypotheses from the Research Plan to see which can be confirmed

### Topline Summary
- Use the [Topline Summary Template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/sharing-research/topline-summary-template.md) to summarize major findings
- Consult your Product Manager and Product Owner to see if a meeting should be scheduled to discuss the Topline Summary
- Your PM and PO may have additional questions based on Topline Report that require additional synthesis
- This is just a summary of findings, no recommendations

### Sample research reports from Income Limits
- [topline summary](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/income-limits-app/research/2023-01-income-limits-usability/topline.md)
- [full findings report](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/income-limits-app/research/2023-01-income-limits-usability/research-findings.md)
- [readout presentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/income-limits-app/research/2023-01-income-limits-usability/NEWER%20Research%20Readout%20for%20IncLim%20usability%20testing.pdf)

### Next Steps
- The Research Lead should work with the Design Team & PM to create recommendations 
- The PM & PO should decide if a full research readout is required and who needs to be invited

## Sprint 92 ACs - 5 points
- [x] Start drafting Topline Summary
- [x] Clean up notes spreadsheet
- [x] For no-show participants, enter their data into [MVS checker](https://docs.google.com/spreadsheets/d/1pq7TSHZonfpzAQBJj6B2geGHlNUwZEs4DzEvxcRgu0o/edit?usp=sharing) with "N"'s
- [x] Start data analysis/synthesis of data collected from research

## Sprint 93 ACs - 13 points
- [x] Create Topline Summary, share with PO, and update if needed 
- [x] Continue data analysis/synthesis of data collected from research
- [x] Schedule a full research readout (if PM & PO request)

**Comment by davidmpickett** [comment]
@cindymerrill @ALogsdon3 I updated this card with links to Cindy's example documents from Income Limits since they will be more germane to this part of the process

**Comment by xiongjaneg** [comment]
topline summary meeting scheduled for Sept. 21

**Comment by ALogsdon3** [comment]
@mmiddaugh: [Topline summary](https://github.com/department-of-veterans-affairs/va.gov-team/blob/5b22660b5771a58d574dfef8f0d7681179281419/products/facilities/regional-offices/research/2023-06-veteran-facing/topline.md) has been added to the VBA research folder. 
cc: @jilladams @xiongjaneg @davidmpickett @thejordanwood

**Comment by mmiddaugh** [comment]
@ALogsdon3 - I think you are headed in the right direction and that you have initial observations to support each of the hypotheses. 

I'm looking forward to learning more about each of your preliminary observations, especially 
- the use of action links for tasks compared to the other options on the page
- usability related to the granular information within a service accordion
- whether these usability issues were observed generally/across benefit types or most obvious for specific benefit areas or a specific population

**Comment by jilladams** [comment]
@ALogsdon3 @xiongjaneg for reporting, if we break ACs up across sprints, just need to indicate the points value for each sprint, so I can count them. THis was pointed at 13, so I assumed 5pts in Sprint 92, and 8 remaining in Sprint 93. If that's wrong, please let me know. (Going to track the 5 for 92, but we can update the 8 for 93 if that's wrong.)

**Comment by xiongjaneg** [comment]
Marking ACs for 93 done. Alexis shared topline summary with Michelle async. Alexis continued synthesis. Internal and VBA report outs are scheduled.
