### ISSUE TITLE
Supplemental status more info does not update when supplemental status is selected

### ISSUE THREAD

**Issue by omahane** [department-of-veterans-affairs/va.gov-cms#14536]
## Describe the defect
The COVID-19 status Details WYSIWYG does not change when a COVID-19 status is selected or changed.

## To Reproduce
1. Go to "Houston Webster VA Clinic" (/node/56198/edit)
2. Scroll to **COVID-19 health protection guidelines** and select a different **COVID-19 status** than what is currently selected
3. Validate that the **Details** WYSIWYG does not change.

## AC / Expected behavior
The **Details** WYSIWYG should update with content from the respective term's description when choosing a **COVID-19 Status**.

### Working in Drupal 9
![drupal-9-supplemental-status-updating](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/766573/c99e71fc-2513-49a0-89eb-a3cc792924a3)
### Not working in Drupal 10
![drupal-10-supplemental-status-not-updating](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/766573/3495ee24-09b4-444e-be65-54e836aa0686)

 ## Additional context
The COVID-19 Status is will be be removed on the Drupal backend
#13679 
So it may not be necessary to do anything.

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Defect")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS workstream (orange) (not needed for bug tickets)
- [ ] CMS-supported product (black)

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [x] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`
- [ ] `Accelerated Publishing`

**Comment by jilladams** [comment]
@omahane COVID 19 status has been removed. (Don't see it in prod anymore.) Can this ticket be closed as no-op?

**Comment by jilladams** [comment]
Closing as no op bc supplemental status was changed.
