### ISSUE TITLE
Adapt log analysis coding methods (eg to target Key Results or other needs)

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#1453]
## Acceptance Criteria
- [ ] Codes and sensors defined for [as many KRs as appropriate](https://docs.google.com/spreadsheets/d/1XRQYWCacMIpf14sZr6kVQ7uq0iF-RfoDzdfv_EwsDVc/edit#gid=1547304655) 
- [ ] Add codes to Reframer

Optional:
- [ ] Consider recoding some existing data

**Comment by jefflbrauer** [comment]
@nickbloom please update this epic and sprint value
