### ISSUE TITLE
Some bulk edit operations never complete

### ISSUE THREAD

**Issue by omahane** [department-of-veterans-affairs/va.gov-cms#14549]
## Describe the defect
The "Archive selected content (Unpublish)" and "Publish latest revision" actions in bulk edit never complete, due to an error thrown in views_bulk_operations

## To Reproduce

1. Steps to reproduce the behavior:
2. Go to /admin/content/bulk
3. Select one or more items
4. Select "Archive selected content (Unpublish)" or "Publish latest revision" in the Action dropdown
5. Click "Apply to selected items"
6. Validate that the progress bar never advances
7. Go to the /admin/reports/dblog/
8. Validate that an error has been thrown

## AC / Expected behavior
I expect that the request action executes completely and without error.

## Screenshots
![Screenshot 2023-07-27 at 10 48 12 AM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/766573/7ced2e56-3c5c-4399-bc38-e2300787e728)

 ## Additional context
The error is
```
Error: Call to a member function isAllowed() on bool in Drupal\views_bulk_operations\Service\ViewsBulkOperationsActionProcessor->process() (line 446 of /var/lib/tugboat/docroot/modules/contrib/views_bulk_operations/src/Service/ViewsBulkOperationsActionProcessor.php).
```

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Defect")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS workstream (orange) (not needed for bug tickets)
- [ ] CMS-supported product (black)

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [x] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`
- [ ] `Accelerated Publishing`

**Comment by ndouglas** [comment]
Closing in favor of #14851.
