### ISSUE TITLE
D10: Refused to execute script gtm_tag_trackers.js

### ISSUE THREAD

**Issue by dsasser** [department-of-veterans-affairs/va.gov-cms#14548]
## Description
The gtm_tag_trackers.js javascript file does not exist, and the following error is thrown repeatedly for any page in the CMS (ostensibly)

```
Refused to execute script from 'https://vacms-12252-drupal-10-kaaijt1fsqp1qasl6a8metonglihfa26.ci.cms.va.gov/modules/custom/va_gov_backend/js/gtm_tag_trackers.js?v=1.x' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
```

![Screenshot 2023-07-27 at 10.51.57 AM.png](https://images.zenhubusercontent.com/628fa5e0de11802be559ed62/eedb2379-0ebb-48b7-b3c9-3f9a9897a718)

## Acceptance criteria
- [ ] gtm_tag_trackers.js javascript is accessible at /modules/custom/va_gov_backend/js/gtm_tag_trackers.js
- [ ] related javascript console errors are no longer present

**Comment by jilladams** [comment]
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14480 removed the GTM module. 
> Removing the current custom GTM implementation because it does not work under Drupal 10 JS library changes.

> Per PO Erika Washburn, we are ok to remove and eventually replace if needed. There is an initiative with Platform Analytics to migrate to Google Analytics 4.

Closing.
