### ISSUE TITLE
FE: Update R&S Detail template to place Reusable Q&As in the appropriate order among content blocks

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#14541]
### User story

**AS A** Content Editor
**I WANT** Reusable Q&As to appear in the same order among other content blocks that I entered them in Drupal (and not at the end)
**SO THAT** Veterans see content as intended.

### Engineering notes / background

In the current implementation of R&S Detail pages, the FE is adding Reusable Q&As to the end of the content blocks.

Runbook for adding Q&As to FE is available in #10937.

The goal for this ticket is to create a reusable solution for all pages that will eventually need their Q&As updated. Suggestion is to create a liquid template that can be included into each of the respective pages. If this is not possible, we will have to fix the implementation on R&S and apply this same pattern manually to each of the pages in the future.

### Quality / testing notes

Add unit/e2e tests as appropriate.

Testing steps:
- In an R&S Detail content node in Drupal, add Q&A Groups to a couple positions among Rich Text or other block types
- Check that they are rendered in the correct order on the FE

## Acceptance criteria

- [x] Reusable Q&As (within "Q&A Groups" in Drupal) appear in the same order among other content blocks as they were entered in Drupal
- [x] Updated FE runbook to incorporate reusable Q&As in the order that they are entered in drupal (among content blocks)

**Comment by wesrowe** [comment]
@randimays, I assigned this to you for pre-refinement – check ticket and estimate.

**Comment by wesrowe** [comment]
Wes to confirm with Danielle prior to sprint planning.

**Comment by wesrowe** [comment]
[Slacked Danielle](https://dsva.slack.com/archives/C52CL1PKQ/p1690491385682799?thread_ts=1690487036.035889&cid=C52CL1PKQ) in DSVA. She agreed Drupal should match FE, but is only leaning (not 100%) toward allowing Q&As anywhere, vs at the bottom of main content.

**Comment by wesrowe** [comment]
UPDATE: we're confirmed to implement ticket as written (same slack thread as previous comment).

**Comment by randimays** [comment]
Final runbook home: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/content/tier-2-content-IA-and-design/cope-cms-faq-library/engineering

**Comment by chriskim2311** [comment]
@jilladams @wesrowe Upon looking into this ticket. The Q&A group is being placed in the correct location based on its ordering in the main content block. Here is an example of where it is being used. Let me know if there's something else I may be missing here. staging.cms.va.gov/resources/choosing-a-decision-review-option

**Comment by jilladams** [comment]
From scrum: 
* 1 R&S node in the CMS with Q&A groups attached
* Thusly, for testing: proposed constructing some lorem content with Q&A groups in various places in the Main Content blocks, in order to verify presentation
