### ISSUE TITLE
Bulk edit action form elements moved and changed style

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#14556]
## Describe the defect
The bulk edit action elements have moved from the top of the view to the bottom, directly above the pagination. The style of these elements has also changed as well. These changes have taken place anywhere these elements appear (Bulk edit, People view, etc.)

These elements on the people view and the VA Forms view are also auto appearing as soon as I select items from the list. When you first go to the page, you will not see these actions, then if you start checking items the actions slide in from the bottom of the screen. This is new, unexpected behavior.

## To Reproduce
1. Go to [Bulk edit](https://vacms-12252-drupal-10-esdtuqzba9g5gopezqazojjvehr8jy4i.ci.cms.va.gov/admin/content/bulk)
2. Scroll down to the very bottom
3. Notice that directly before the pagination, there is a black bar with a dropdown of available actions.

## AC / Expected behavior

- [ ] The Action form elements are unchanged on /admin/people
- [ ] The Action form elements are unchanged on /admin/content/bulk
- [ ] The Action form elements are unchanged on other pages with these form elements.

## Screenshots
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/106678594/4c3d01da-2cf8-47b2-a150-684b763c8c05)

**Comment by edmund-dunn** [comment]
@laflannery @BlakeOrgan This cannot be changed to the old functionality and placement. We need to fix this form styling with custom CSS. The grayed-out text means the button is disabled. 

Laura will review for other a11y issues in views bulk edit/views bulk operations.

**Comment by BlakeOrgan** [comment]
@edmund-dunn Is there a reason that this can't be changed to the old functionality and placement?

**Comment by edmund-dunn** [comment]
@BlakeOrgan @laflannery the button was fixed in a core issue https://www.drupal.org/project/drupal/issues/3378091. Screen shots of fix below. 
Disabled:
![CleanShot2023-08-02at09.47.57.jpg](https://images.zenhubusercontent.com/62e017d215adbc33b1310f7b/ed6ebf10-510f-45d1-ac85-18deeac7fc7f)
Enabled:
![CleanShot2023-08-02at09.48.12.jpg](https://images.zenhubusercontent.com/62e017d215adbc33b1310f7b/205bd687-5b02-4e15-92bc-3de45af2625a)

**Comment by BlakeOrgan** [comment]
@edmund-dunn Here's a [Figma link](https://www.figma.com/file/juQb3n69LAT6UDasm0ZnBP/Bulk-Edit?type=design&node-id=12%3A2141&mode=dev) for how I think that the updated styling should look for bulk updates. Let me know if there might be any problems!

**Comment by edmund-dunn** [comment]
This is done and inthe D10 branch.

**Comment by laflannery** [comment]
@edmund-dunn and @BlakeOrgan I just tested this Design in D10 and this changes the visual display of the interactive elements so the tab order is not accurate - Focus order is **Action dropdown > Selected Dropdown > Select/Deselect checkbox** when it should be **Action dropdown > Select/Deselect checkbox > Selected Dropdown **.

Can we change the display to make the visual display match what's in the DOM so that tab order is accurate? It could perhaps look like this:
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/106678594/d13be4cc-b1f2-4718-8ba9-507d3d0951fc)

**Comment by edmund-dunn** [comment]
@BlakeOrgan Everything has been addressed.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbjR2IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--6f1cfa3df51032f4191ea8f6edf6b12ff63e8d30/CleanShot2023-08-23at10.19.59.jpg)
