### ISSUE TITLE
Finalize VBA fields for VA Services taxonomy with stakeholders

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#14551]
## Descriptions
#11267 will provide a draft of all VBA fields for VA Services taxonomy 

This ticket has external dependencies and we can expect it to span sprints until all approvals are complete.

## ACs

VBA review / CAIA (External dependency):
- [ ] All term fields are reviewed and signed off by VBA (which are required, rules for application, etc.)
- [ ] Provide post-VBA review term fields to CAIA for review and approval

Taxonomy council reviews (external dependency):
- [ ] Changes to existing terms are vetted with affected council members (VAMC or Vet Center)
- [ ] New terms that might have cross-utility are also brought to full council

Team:
- [ ] Implement changes in content, add final content reference doc to #11268

**Comment by jilladams** [comment]
@davidmpickett the review ticket, also for pointing at your leisure

**Comment by davidmpickett** [comment]
Closing in favor of the new approach which covers adding to Drupal and getting sign off: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15748
