### ISSUE TITLE
Deleting content leads to modal

### ISSUE THREAD

**Issue by omahane** [department-of-veterans-affairs/va.gov-cms#14568]
## Describe the defect
A modal overlay comes up when deleting content, as opposed to going to a page

## To Reproduce
1. As an admin user, go to a [listing of Events](https://vacms-12252-drupal-10-kaaijt1fsqp1qasl6a8metonglihfa26.ci.cms.va.gov/admin/content?title=&type=event&moderation_state=All&owner=All)
2. Click "Edit" on the first result
3. Scroll down to the bottom
4. Click "Delete"
5. Validate that a modal with 2 buttons comes up

## AC / Expected behavior
Unsure.
Is a modal the preferred user experience? 
Do we need an "Unlock" button?

## Screenshots
![Screenshot-deleting-content-modal](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/766573/f770782b-7a30-4ad3-ad9f-2f924ec84716)

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Defect")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS workstream (orange) (not needed for bug tickets)
- [ ] CMS-supported product (black)

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [ ] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`
- [ ] `Accelerated Publishing`

**Comment by xiongjaneg** [comment]
@BerniXiongA6 submitted for CMS Team intake, thanks for your consideration

**Comment by BerniXiongA6** [comment]
Hey @ndouglas -- could I have you peek at this to help triage for Drupal eng? I appreciate the assist, thanks!

**Comment by ndouglas** [comment]
This is a change in D10 (see https://www.drupal.org/project/drupal/issues/2253257). Not a bug. Might be worth informing @stefaniefgray @TroyA6 @BlakeOrgan @laflannery @joagnitti about though just for general awareness.

**Comment by laflannery** [comment]
@ndouglas I want to confirm who sees this - is it just super admins?

**Comment by ndouglas** [comment]
I think only super admins can delete things, but I might be wrong.

**Comment by BlakeOrgan** [comment]
From a UX perspective, typically a modal is the preferred experience when attempting a destructive action such as permanently deleting something. This is a welcomed change in my eyes.
