### ISSUE TITLE
Redirect Request: benefits.va.gov education rates page to modernized site

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-cms#14571]
**ALERT Beth Potts when this is scheduled to go live so she can warn stakeholders**

### Instructions
- Requests must be submitted **AT LEAST** 2 weeks in advance.  Some requests take a significant amount of time and coordination to implement, so start the process as soon as you know you will need one. 
- This issue will be used from initial request through implementation to ensure all individuals working on this are notified of status updates.  Please do not create multiple issues to track differnt steps.
- It is your responsibility to notify VA stakeholders as appropriate.  

### Type of request
- [x] We are retiring or taking down a page and need to redirect the URL (complete redirect section)
- [ ] We are changing the URL of an existing page (complete redirect section)
- [ ] We need a custom vanity URL (complete vanity URL section)

### Implementation date
When does this request need to be live?
Choose one:
- [ ] On a specific date, connected to a program or publishing requirement. 
- [ ] Any day prior to a deadline/latest possible date.
- [x] Any day after an earliest possible date. 6/29/23  **WES EDIT: Alert Beth so she can warn stakeholders**
- [ ] During a specific date range: 
- [ ] No hard timing requirements, publish when possible.

### Redirects 
Current URL  |  Redirect Destination or New URL
---  |  ---
https://www.benefits.va.gov/gibill/resources/benefits_resources/rate_tables.asp | https://www.va.gov/education/benefit-rates/

### Vanity URLs 
Vanity URL  |  Landing page
---  |  ---
requested URL | landing page URL

**Link to campaign landing page request issue:**

### Process, Roles and Responsibilities
- [ ] Requesting team: Above information is provided
- [ ] Requesting team: All appropriate VA stakeholders are notified as appropriate
- [x] IA: Request is vetted and documented and implementation plan is clear 
- [x] IA: Request is assigned to appropriate team for implementation 
- [x] Implementation team: Work is complete
- [x] Implementation team: Validated in production
- [ ] Requesting team: Validates everything is correct in production and closes ticket

**Comment by wesrowe** [comment]
Chris verified and notified Beth. Closing.
