### ISSUE TITLE
VBA Information Architecture: discovery / next steps

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#14572]
https://dsva.slack.com/archives/C0FQSS30V/p1690563738092019

**Blocks Collab Cycle Analytics request ticket.** Correlated suggestion: use the Analytics New KPI dashboard request for [Team] template to request a "Content" dashboard. We can talk more about it when we are ready

## Description
We need to pin down the IA for VBA Regional Offices. 

Right now in the CMS VBA ROs are "VBA Facility." VBA Facilities is a superset of Regional Offices, and right now this Facilities type includes: 
- ROs
- Pre-discharge sites
- Benefit Satellite offices
- Disability evaluation system sites
- Vet success campus sites
- Veteran Readiness & Employment Offices

**Open questions:**
* Content type structure
    * Will these become "Regional Office" in the great CMS Config of things? 
    * Will they remain VBA Facility?
    * OR: Is VBA Facility like the overarching VAMC System concept, and ROs will be sort of like VAMC Facility and be a child?
* Proposed IA path:  the path we have was our initial stab at it:  /<RO name>/locations/<satellite office name>
ex: /winston-salem-va-regional-benefit-office/locations/pre-discharge-site-at-fort-liberty
    * it would not be a bad idea to recommend name spacing them rather than have them all sit at the root level.
    * The artifact that those decisions should be documented in is probably https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/facilities/naming-schema
        * Not sure if that needs a new CAIA intake request, or if it can just be part of our open ticket that was used for reviewing design

### VBA facility types
What will the others become?  That has not been decided yet because we don't know enough about the needs of the other types.   If they don't have radically different data needs, then it would be good to keep them in the same content type as ROs.   We can link others under an RO without needing to move them to a different content type.  Again it is more a question of the what the data model needs.

This was one of the big questions we had going into the Discovery Phase of VBA. Are there meaningful connections between these facility types, or do Veterans expect there to be?
The only place this seems to be true is that for Satellite Offices and Regional Offices, there is a connection on a staff level and on a Veteran perception level. However, this connection did not seem to warrant nesting the Satellite Offices under Regional Offices for the front end website. Instead, we decided to give them the same front end treatment, except that Satellite Offices might have one additional element that links to the Regional Office.
But from a data model perspective, there didn't seem to be anything different enough to warrant splitting them into different content types.

old thread for when we discussed SOs listing ROs: https://dsva.slack.com/archives/C0FQSS30V/p1683122402176529?thread_ts=1683122402.176529&cid=C0FQSS30V

## ACs

- [ ] Determine Facilities proposal for IA for Regional Offices, within context of VBA Facilities. Already drafted? Or not? 
- [x] Determine the current state of IA ask to CAIA - have we proposed anything already? What state is the request in? 
   -  found (and updated) the original request which was in the SCAIA icebox: VBA Facility site modernization from Sitewide Facilities [#45672](https://app.zenhub.com/workspaces/sitewide-content-accessibility-and-ia-63a1d63232beba0011a7833f/issues/gh/department-of-veterans-affairs/va.gov-team/45672) 
- [x] Determine the process for IA requests with CAIA in light of staffing - _Michelle will take next steps_

**Comment by jilladams** [comment]
Michelle found https://github.com/department-of-veterans-affairs/va.gov-team/issues/45672, and is looking for info on an IA shepherd.

**Comment by mmiddaugh** [comment]
@jilladams Danielle will help me find a path for the IA request.

**Comment by jilladams** [comment]
Noting: we heard from CAIA this morning on Public Websites side that they expect Mikki to return next week ([slack](https://dsva.slack.com/archives/C01K37HRUAH/p1691685950135109?thread_ts=1691672402.210429&cid=C01K37HRUAH)), re: discussion around an IA shepherd.

**Comment by mmiddaugh** [comment]
Bumped this one up on the radar again...fyi @jilladams

**Comment by jilladams** [comment]
Bumped the IA ticket, with the note about namespacing.

**Comment by jilladams** [comment]
@mmiddaugh @xiongjaneg @davidmpickett the questions around actual path IA for regional offices is now on course and CAIA is engaged. The piece of this ticket that isn't done yet in this context is figuring out our Facilities proposal for whether we want Regional Offices to be different than "VBA Facility". That may have come up / been decided during the Drupal scoping conversations that I missed -- could you document here if so? And if not, and this is still an outstanding question, i think we shoudl assign Jane / Dave and try to pick up / work out that piece in our next sprint, if we have bandwidth.

**Comment by davidmpickett** [comment]
> figuring out our Facilities proposal for whether we want Regional Offices to be different than "VBA Facility"

[Our content model](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13096) does not include a separate content type for Regional Offices. The plan is to use the VBA Facility content type. [Our research](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/regional-offices/research/2022-9-public-contact/research-findings.md#6---public-contact-staff-provide-a-consistent-set-of-services-at-multiple-vba-facility-types) indicated that there do not appear to be significant differences between Regional Offices and Satellite Offices from a service delivery perspective. 

Adding an additional content type adds complexity to Content-Build and for editors. We should avoid it unless absolutely necessary.

**Comment by davidmpickett** [comment]
> Proposed IA path: the path we have was our initial stab at it:
> /winston-salem-va-regional-benefit-office/locations/pre-discharge-site-at-fort-liberty

I don't know where this came from, but it's the first I'm seeing it. I don't know if this is the best approach. This is reflecting the org chart, but that might not be the most logical mental model for Veterans. Many VBA locations are housed inside other VA Facilities and from a Veteran perspective, they might expect to have that reflected in the URL. Example, the Houston Regional Office is located on the campus for the the Houston VAMC and the Anchorage Regional office is located inside the Anchorage VAMC building.

This is also counter to the decision to treat ROs and SOs sites the same rather than nesting SOs under ROs in a side menu.

Copy and pasting some related comments I made back on #13645

> - Non-VA location official name
> - Non-VA location URL
> - Shared VHA location
> 
> These three fields are far more likely to be populated for Satellite Offices than Regional Offices:
> - Regional Office = 21/58 = 36%
> - Satellite Office = 75/84 = 89%
> 
> Based on the [VBA Facility Naming Schema](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/facilities/naming-schema#vba-benefits-facilities-naming-schema) some of this information would be embedded in the H1 of VBA pages (e.g. [Alaska RO](https://www.va.gov/find-locations/facility/vba_463) and [Satellite office at Fort Campbell](https://www.va.gov/find-locations/facility/vba_320g)). It might also show up in the address block (ala JFK Federal Building in Jordan's design). 
> 
> What other ways are you thinking this information would need to be surfaced to Veterans? Is this really a FE design problem, or a Drupal data flow issue? (e.g. Facility Operating Status of Alaska VAMC could cascade down to the Alaska RO since they share the same physical location?)
> 
> Here's an export of data (that is a bit outdated) that shows a range of values for these fields on the VBA facilities that are in scope for MVP (Regional Offices & Satellite Offices)
> [VBA Facilities-Grid view (1).csv](https://github.com/department-of-veterans-affairs/va.gov-cms/files/11456586/VBA.Facilities-Grid.view.1.csv)

**Comment by xiongjaneg** [comment]
Questions in the body of the ticket about types of VBA facilities, what will we do with the potential other types of facilities?

**Comment by jilladams** [comment]
Post-meeting last week: next steps are for Facilities to make a recommendation that IA can either accept/decline. @mmiddaugh owns that step.

**Comment by mmiddaugh** [comment]
CAIA request in [#64934 VBA IA Request from Sitewide-Facilities](https://app.zenhub.com/workspaces/sitewide-content-accessibility-and-ia-63a1d63232beba0011a7833f/issues/gh/department-of-veterans-affairs/va.gov-team/64934)
Closing this issue

**Comment by davidmpickett** [comment]
@jilladams @xiongjaneg @mmiddaugh 
The body of this ticket indicates this work as a blocker for submitting a Collab Cycle Analytics request ticket. Now that the active work has moved into a [ticket on the va.gov-team side](https://github.com/department-of-veterans-affairs/va.gov-team/issues/64934), I don't want use to lose track of that as a follow up action item. Might be worth a stub

**Comment by xiongjaneg** [comment]
@davidmpickett @mmiddaugh Is the Analytics request described in the ticket different from the Analytics request in the Collab Cycle ticket #46029? The instructions are different and I'm trying to figure out which (or both) are ready to request. The collab cycle instructions do ask for a URL, which we don't know yet.

**Comment by davidmpickett** [comment]
> @davidmpickett @mmiddaugh Is the Analytics request described in the ticket different from the Analytics request in the Collab Cycle ticket #46029? The instructions are different and I'm trying to figure out which (or both) are ready to request. The collab cycle instructions do ask for a URL, which we don't know yet.

Nope, they should be one and the same. I forgot that the Collab Cycle ticket gave explicit instructions on the Analytics request.

I just updated the ticket where I am tracking my work with an AC to do that request after other steps are complete: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15490

No further action required :)
