### ISSUE TITLE
Facility deletion does not trigger a content release.

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#14580]
## Describe the defect
Deleting a facility does not trigger a release.
![image](https://user-images.githubusercontent.com/5752113/257321335-cf4f66c6-10c3-4da3-bdb6-76b60d0be7fb.png)

It is not a critical problem, it is barely a minor problem: 

- 99% of the time we are not deleting facilities.
-  admins are the only one who can delete a facility so it would go out with normally scheduled content releases. 
- On the rare occasion where we do delete a facility, the facility was unpublished beforehand, which would trigger a content release.

This issue was surfaced in [this comment](https://github.com/department-of-veterans-affairs/va.gov-cms/pull/14569#pullrequestreview-1555567174) 

## To Reproduce
1. Go to and facility
2. Delete it
3. Check recent log messages to see that no content release was triggered.

## AC / Expected behavior
Ideally, deleting a facility should trigger a content release, just to reduce the risk of data on the FE not matching the state of the CMS.  However, the risk is a smalll... very small edge case that almost never happens, and even if it did the risk of Veteran impact is minimal.

Mainly just documenting this here so we know it is an small risk.

**Comment by Agile6MSkinner** [comment]
The issue description itself is screaming to be closed.
