### ISSUE TITLE
D10 Testing: VAMC Facility Page not rendering location on Map

### ISSUE THREAD

**Issue by maxx1128** [department-of-veterans-affairs/va.gov-cms#14596]
## Describe the defect

The VAMC Facility page normally shows a map of the facility location that can be panned and zoomed. But the Drupal 10 testing revealed that the map is no longer rendering.

## To Reproduce
1. Go to https://web-kaaijt1fsqp1qasl6a8metonglihfa26.ci.cms.va.gov/portland-health-care/locations/portland-va-medical-center/
2. Scroll down to 'Location and Contact Information'
4. See error below the static image of the facility

## AC / Expected behavior

The map interface that shows a Google map that can be panned and zoomed by the user.

## Screenshots

![](https://user-images.githubusercontent.com/10790736/257261532-b4820eb5-ef36-40f8-9297-70efcdf105b4.png)

 ## Additional context

This is not currently in production. It was found as part of [the Drupal 10 front-end testing by the facilities team.](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14390)

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Defect")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [ ] CMS workstream (orange) (not needed for bug tickets)
- [ ] CMS-supported product (black)

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [ ] `Public Websites`
- [x] `Facilities`
- [ ] `User support`
- [ ] `Accelerated Publishing`

**Comment by edmund-dunn** [comment]
@maxx1128 This appears to be common to tugboat, not specific to Drupal 10. I did notice a 403 for mapbox, which shows up in Drupal 9 tugboats as well. 
![CleanShot2023-08-03at12 53 50](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/109987005/a1edf4be-afec-4ca7-9286-0c1764e1dfd1)

**Comment by mmiddaugh** [comment]
@xiongjaneg @jilladams this is behaving as expected in CMS prod and Staging and on the Veteran-facing front end as well. Do we need to address this if it only exists in Tugboat?
