### ISSUE TITLE
Cypress testing setup for Next Build

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#14598]
## Description
In addition to unit tests with Jest, Next Build should have the ability to run integration tests with Cypress. Tests should be able to be run locally as well as on CI. There should be documentation for how to create a Cypress test within our setup.

## Acceptance Criteria
- [ ] Cypress tests can be run locally
- [ ] Cypress tests run on CI
- [ ] Cypress tests run locally and on CI produce the same results
- [ ] Documentation is written for how to create Cypress tests in our setup.
- [ ] Example test is added to example tests

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [ ] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`
- [x] `Accelerated Publishing`

**Comment by timcosgrove** [comment]
@ndouglas may be an advising resource here; Nate you are not to do much beyond providing links and guidance. :)

**Comment by timcosgrove** [comment]
Tanner

**Comment by tjheffner** [comment]
Finished with this PR: https://github.com/department-of-veterans-affairs/next-build/pull/135
