### ISSUE TITLE
No VA logo in main tool bar

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#14591]
## Describe the defect
The VA logo should be in the far left of the main toolbar, instead it's the Drupal logo

## To Reproduce
1. Log into D10: https://vacms-12252-drupal-10-opslrfeufzwsvhxx2uuv1wmvjbiq7wuq.ci.cms.va.gov/user/4174?check_logged_in=1
2. Look at the main toolbar
3. See the Drupal logo where the VA logo should be

## AC / Expected behavior

- [ ] The VA logo should be in the far left of the main toolbar

## Screenshots
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/106678594/d08ed45d-f2db-4e92-9fe7-aebf61125ed7)

### Team
Please check the team(s) that will do this work.

- [x] `CMS Team`
- [ ] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`
- [ ] `Accelerated Publishing`

**Comment by edmund-dunn** [comment]
This is fixed on the d10 branch
