### ISSUE TITLE
Lighthouse CSV / Canonical URL Change for: Croasdaile VA Clinic

### ISSUE THREAD

**Issue by stefaniefgray** [department-of-veterans-affairs/va.gov-cms#14607]
⚠️  NO URL RE-DIRECT NEEDED ⚠️ 

Simply needs to be updated within Lighthouse CSV / canonical URL change

-----

### Implementation date
When does this request need to be live:
Once main new facility ticket is completed: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14506

### Instructions for canonical URL change
- [x] Verify that the new URL for the facility is published and accessible on VA.gov.
- [x] Update the [CSV in Lighthouse](https://github.com/department-of-veterans-affairs/lighthouse-facilities/blob/master/facilities/src/main/resources/websites.csv) with the changed URL, maintaining the sorted order of the Facility API IDs.
- [x] Create a PR in the [lighthouse-facilities repo](https://github.com/department-of-veterans-affairs/lighthouse-facilities), tagging the Lighthouse team.
- [x] Post a message in the #cms-lighthouse channel in Slack, with an @mention to a Lighthouse team member.
- [x] Add the "Awaiting CSV" flag to the facility node with a revision log message that includes a link to this ticket.
- [x] Validate that the change has deployed by checking that the Facility Locator has been updated with the new url.
- [x] Update this ticket with a comment that the CSV change has been deployed.
- [ ] Remove the "Awaiting CSV" flag to the facility node with a revision log message that includes a link to this ticket.

#### URL change example (update with actual ID and URL)
| Facility API ID  |  Full VA.gov URL |
| ---  |  --- |
| vha_558GI | https://www.va.gov/durham-health-care/locations/croasdaile-va-clinic |

**Comment by stefaniefgray** [comment]
@omahane Does this look good for a just-canonical URL change for a brand-new facility, and if so, could this become the new URL-change-for-new-facility runbook template?

**Comment by omahane** [comment]
The CSV has been deployed

**Comment by stefaniefgray** [comment]
Notified in https://va-gov.atlassian.net/browse/VAHELP-6167 -- closing! Thanks for all your help @omahane
