### ISSUE TITLE
Image style information provided by JSON:API is not allowing for correct image formatting

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#14602]
## Description
The module we were previously using to provide image style information ([consumer_image_styles](https://www.drupal.org/project/consumer_image_styles)) no longer provides height and width information as part of the response.

Our current set up falls back to the uploaded images original height / width, but with the derived image URL.

We should be able to use fill or content-fit: object or some other approach to use the derived image from the desired image style at the correct size (edited).

Another module that provides similar functionality to consumer_image_styles is https://www.drupal.org/project/jsonapi_image_styles; only provided here as a reference.

## Acceptance Criteria
- [ ] Images using image styles that are built by Next Build render correctly
- [ ] Images look correct on both Story Listing pages and News Story pages

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [ ] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`
- [x] `Accelerated Publishing`

**Comment by tjheffner** [comment]
This may have been "handled" OOTB by upgrading next to 13. I am seeing images no longer stretched as I was:

before:
![Screenshot 2023-08-01 at 12 16 28 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/11279744/3da524d1-368a-4402-ac7f-98517d9d49b9)

after:
![Screenshot 2023-08-04 at 2 40 57 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/11279744/352befaa-5973-4a98-a556-4046dd28cf08)

**Comment by jtmst** [comment]
I didnt have images available on my local until after the 13 migration, so I never saw the old state.  They all look fine to me.
