### ISSUE TITLE
Content design for improved CMS unauth homepage

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#1461]
## User stories

* As an editor, I need to be able to tell the difference between the training and prod environments.
* As a new editor, I need to know how to get an account.
* As an editor logging in, I need to know what to do if I get a login error message.
* As an editor logging in, I need to know whether login is with username and password or PIV.
   - Login with PIV now the primary action
   - Copy added to username login screen explaining that it is a secondary/backup method.
* As a platform or product team member, I need to login to Drupal CMS.
   - Login with password option in upper right
* As an editor, I need to know when major changes affect my editing experience.
   - Announcement alert appears above login button
* As an editor needing help, I want to get help without logging in first.

ACs (need refinnig)
- [x] Content design that meets the above user stories
- [x] Determine footer links
- [x] UX writing
- [x] Placeholder for announcements?

**Comment by kevwalsh** [comment]
@rachel-kauff I feel like this is mostly done but i'm putting the footer links design as an AC.

**Comment by rachel-kauff** [comment]
After much back and forth thought, I am coming around to keeping the footer links as the legalistic/required/stuff in the context of the larger VA policies. That seems right for the login page, and the fact that they will soon be configurable means we don't have to put a lot of effort into fully validating all of this right now. 😅

**Comment by rachel-kauff** [comment]
Kauff to add design specs for
- [ ] the user story: contact help desk without logging in
- [ ] Add design system link to footer
- [ ] Design adjustments to footer height
