### ISSUE TITLE
I.L. FE: App should not auto-scroll

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#14613]
## Description
The Income Limit app is automatically scrolling between pages/screens when I click the back or continue button or when I am on the Review screen and click an Edit link. This automatic scrolling can cause issues for users with motion sensitivity or cognitive considerations.

### User story

**AS A** Veteran 
**I DO NOT WANT** the transitions within the app to auto-scroll
**SO THAT** I can manage my own expectations about when and where scrolling will occur

### Engineering notes / background
This scrolling is most evident going from the Intro screen to the first screen. If you are on the intro screen, scroll all the way down to the Past income limits flow link. Click this link and the page will scroll all the way to the top automagically.

Can the load be more like this form: https://staging.va.gov/supporting-forms-for-claims/alternate-signer-form-21-0972/introduction?

## Acceptance criteria

- [x] The auto-scroll of the app has been removed and replaced with loading to top
- [x] Accessibility lead review

**Comment by wesrowe** [comment]
@laflannery, this is a surprising one! I was quite pleased with this when Randi added it, so it's a learning moment for both of us.

**Comment by wesrowe** [comment]
I verified also.

**Comment by wesrowe** [comment]
And will link this ticket on the [collab cycle issue](https://github.com/department-of-veterans-affairs/va.gov-team/issues/63470).
