### ISSUE TITLE
Staff Profile does not get an alias when "Published" is its first moderation state

### ISSUE THREAD

**Issue by omahane** [department-of-veterans-affairs/va.gov-cms#14623]
## Describe the defect
A Staff Profile that is created and published in the same step, rather than going through any of the other moderation states, does not get assigned an URL alias.

## To Reproduce
1. Log in as an editor 
2. Create a Staff profile
3. Save it as "Published"
4. [ ] Validate that the URL is `/node/#####`, rather than an alias

## AC / Expected behavior
- [ ] A newly created Staff Profile saved to "Published" has an alias
- [ ] Current Staff Profiles are updated to be given an alias.
- [ ] The scope of the defect is identified as either only related to Staff Profile or other content types, too. 
- [ ] New tickets are created to cover this work if necessary

## Screenshots
![Screenshot 2023-08-01 at 3 59 35 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/766573/2665fbb6-2e32-44ac-9fed-e16cc09fbffd)

## Contextual information
An export of all nodes reveals five (5) content types with nodes that have node paths instead of aliases:
- Staff Profile (418)
- VAMC Facility Health Service (147)
- VAMC Facility Non-clinical Service (21)
- VAMC System Health Service (290)
- Vet Center - Community Access Point (14)

The total number of nodes without aliases is 891 nodes out of 62786

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Defect")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS workstream (orange) (not needed for bug tickets)
- [ ] CMS-supported product (black)

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [ ] `Public Websites`
- [x] `Facilities`
- [ ] `User support`
- [ ] `Accelerated Publishing`

**Comment by stefaniefgray** [comment]
<img width="382" alt="Screen Shot 2023-08-14 at 6 40 36 PM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/9059428/4e3a063a-c10c-49ac-872b-4a8e579bdeba">

<img width="668" alt="Screen Shot 2023-08-14 at 6 41 59 PM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/9059428/22c5502a-0c69-49d3-8fe5-2f66bb1b48e6">

Still an issue

**Comment by stefaniefgray** [comment]
@jilladams @xiongjaneg @BerniXiongA6 Howdy -- @TroyA6 and I are currently discussing this ticket and how it keeps creating broken links for our team to fix. Is it possible to get this ticket prioritized in an upcoming sprint? Thank you!

**Comment by jilladams** [comment]
@xiongjaneg this may be a nice tech debt / defect to pick up if / when we have Drupal capacity. This issue has been causing some broken link checker noise in the last week.

**Comment by xiongjaneg** [comment]
@jilladams @omahane @swirtSJW Yes, it's in ready so could be picked up as stretch this sprint or considered for next sprint pending other priorities

**Comment by jilladams** [comment]
Recent discussion with Helpdesk around this: https://dsva.slack.com/archives/C030F5WV2TF/p1704731953550589

**Comment by BerniXiongA6** [comment]
Hi @jilladams -- Based on the Slack thread convo, I think you're asking if CMS team can prioritize this work soon? Is that correct? If so, I'll defer to @maortiz-27-80 on establishing priority. cc: @EWashb

**Comment by omahane** [comment]
While trying to test this, I'm seeing that when making a story for the first time, it saves twice:
- Tremeaker Gilbert:
  - 01/09/2024 1:12 pm
-  Paul Odie
  - 01/09/2024 9:01 am
- Brandon Lunday
  - 01/09/2024 9:01 am
-  Joshua Cox
  - 01/09/24 8:56 am
- Autumn Watson
  - 01/08/24 2:38 pm
- Michelle Hamm: https://prod.cms.va.gov/node/63576
  - 11/28/2023 8:48 am
  - _Note: this is the earliest example I've found, though probably not the earliest example_

**Comment by xiongjaneg** [comment]
It looks like Christian already on this, but let me know if I'm missing something.

**Comment by jilladams** [comment]
That's right - to @BerniXiongA6 's question: in the Slack thread with Helpdesk, they asked if Facilities could prioritize, and I had noted that to Jane, and it's now in sprint for us. CMS Team doesn't have any obligation here.

**Comment by jilladams** [comment]
Verified in staging. 
Created a new staff profile, didn't set alias, published as first workflow step, got an alias: 
![Screenshot 2024-01-26 at 12 49 32 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/85581471/594f49d1-97f4-415a-bc64-a5b6bb529ca3)


Closing
