### ISSUE TITLE
Review Dependabot Alerts for (Sprint 90)

### ISSUE THREAD

**Issue by productmike** [department-of-veterans-affairs/va.gov-cms#14628]
## User Story
As a DevSecOps engineer, I want to ensure that I'm consistently reviewing and evaluating production alerts so that existing vulnerabilities are assessed and associate risks mitigated.

# Acceptance Criteria
- [ ] Indicate the alerts reviewed in this ticket. 
- [ ] Track evaluations in this ticket.
- [ ] Review high impacting alerts with PO, PM for work to be prioritized and tickets opened.

**Comment by ndouglas** [comment]
Opened:
- #14615
- #14616
- #14617
- #14618 
- #14620 
- #14621 
- #14622 
- #14624

**Comment by productmike** [comment]
This is perfect, thanks @ndouglas !!

**Comment by ndouglas** [comment]
A new ticket has appeared, but since it happened after this issue was partially resolved, I'm going to push it to next sprint. This issue's concerns were all resolved.
