### ISSUE TITLE
Checklist: Benefits hub contacts section showing before it is selected

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#14635]
## Describe the defect
Within the checklist content type, there is a section for Contact information. Here you can select either "Default contact" or "Benefit Hub contacts", with Default being defaulted as the chosen option.

- When "Default contact" is selection, you will see this this section with the VA411 information displayed.
- If you choose "Benefit Hub contacts", the above mentioned default section will be replaced by a new section where you can choose various other contacts.

However, the issues is that in D10, both sections, Default AND Benefits Hub contacts are displaying regardless of which radio button is selected.

## To Reproduce
1. Create a new [Checklist](https://vacms-12252-drupal-10-opslrfeufzwsvhxx2uuv1wmvjbiq7wuq.ci.cms.va.gov/node/add/checklist)
2. Scroll down to the Contact information section
3. Note that "Default contact" is selected automatically
4. Also note that below the radio buttons, you are able to see expanded sections for both Default contacts and Benefit Hub sections.
5. Within the radio buttons, now select "Benefit Hub contacts"
6. Note that the visible expanded sections do not change at all.

## AC / Expected behavior

- [ ] When "Default contact" is selected, only the Default contact expanded section is visible
- [ ] When "Benefits Hub contact" is selected only the Benefits Hub contact expanded section is visible

## Screenshots

![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/106678594/cb70b957-6084-4bb7-a4d0-e2529812ee5e)

![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/106678594/ac839e10-4e37-4875-a506-7ed4e2233681)

### Team
Please check the team(s) that will do this work.

- [x] `CMS Team`
- [ ] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`
- [ ] `Accelerated Publishing`

**Comment by laflannery** [comment]
This same thing is happening on the FAQ page with the Alert section - both "Reusable Alert" and "Non-reusable Alert" sections are showing regardless which of the 3 radio buttons are selected

**Comment by edmund-dunn** [comment]
This has been fixed and commited to D10 branch.
