### ISSUE TITLE
FaF: Standardize how environments are handled for links in Find-a-form search results and detail pages

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#14636]
### User story

**AS A** PM/PO/Engineer
**I WANT** links in pre-prod environments to point to either prod or pre-prod environments consistently and appropriately for env purposes
**SO THAT** best practices for testing are enabled across teams who use pre-prod environments.

Two types of links across two different page types are implicated:
- 2 pages: 
  - Search results (FaF search page) and 
  - Form Detail pages
- 2 types of links: 
  - Link to download form, 
  - Link to online form

### Engineering notes / background

- [Slack thread](https://dsva.slack.com/archives/C52CL1PKQ/p1690909749010239?thread_ts=1690904179.357029&cid=C52CL1PKQ)

Example form prod node in CMS: https://prod.cms.va.gov/node/6072/revisions
VA.gov search results page: https://www.va.gov/find-forms/?q=10182
VA.gov form detail page: https://www.va.gov/find-forms/about-form-10182/

🟢 Prod search PDF dl link: https://www.va.gov/vaforms/va/pdf/VA10182.pdf
:green_circle: Staging search PDF dl link: https://www.va.gov/vaforms/va/pdf/VA10182.pdf?_ga=2.201873429.521633681.1690817303-2111483346.1688053830

:green_circle: Prod detail page PDF dl  link: https://www.va.gov/vaforms/va/pdf/VA10182.pdf
:red_circle: Staging detail page PDF dl link: https://staging.va.gov/vaforms/va/pdf/VA10182.pdf

## Acceptance criteria

- [ ] FaF Search page / search results:
  - [ ] Form download link uses prod link always
  - [ ] ~~Online form link uses current-environment subdomain (so, staging->staging)~~
- [ ] Form Detail page:
  - [ ] Form download link uses ______ (prod?) subdomain (always?)
  - [ ] ~~Online form link uses current-environment  subdomain~~

**Comment by wesrowe** [comment]
Is there an expectation at Platform level that there are Staging file servers that mirror prod? 

Rewriting the URLs to prod URLs may not be a problem that needs solving...

**Comment by FranECross** [comment]
Iceboxed ticket; closing. Can reopen at a later date if needed.
