### ISSUE TITLE
KB: KB article for Q&A Groups

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#14633]
### User story

**AS A** Content Editor
**I WANT** the knowledge base (KB) article on Benefit Detail Pages to be updated for reusable Q&As
**SO THAT** I have accurate documentation to follow.

### Engineering notes / background

- There does not appear to be a KB article for Ben Deets Pages

## Acceptance criteria

- [x] KB article is drafted for how to use Q&A groups
- [ ] ~KB article is drafted for how to create a Benefit Detail page & links to Q&A groups KB~ moved to #15248 
- [ ] Got KB article updates:
   - [x] Drafted a revision to change the content
   - [x] Request review from CAIA
   - [x] Requested review from @wesrowe / @jilladams
   - [x] Cut a KB article review request for Helpdesk: [link](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/new?assignees=&labels=Knowledge+Base%2C+Needs+refining&projects=&template=knowledge-base-article-review.md&title=Review+of+new+or+updated+KB+article+%3A+%3Cinsert+topic+here%3E) - https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15250

**Comment by wesrowe** [comment]
@jilladams, I don't see a KB article for Benefit Detail pages. How sure are we that it would be useful/appreciated by our currently very small pool of Editors? (And noting that it will change as we start hardening Ben Deets content over the next couple quarters.)

**Comment by jilladams** [comment]
^ @davidconlon I think this practice around KBs for Sitewide Content folks is a question for you.

**Comment by wesrowe** [comment]
We confirmed that there is no article about Benefit Detail pages. Also, we asked CMS and Erika said that there really should be one.

**Comment by chri5tia** [comment]
Question/Research needed:
What format should I put the first draft in and where? e.g. Are there any instructions for doing KB articles?

**Comment by jilladams** [comment]
Yes! KB articles are a content type that appear in https://prod.cms.va.gov/help. 
So you can start one as a draft node, and just make sure to not publish it til after reviews: https://prod.cms.va.gov/node/add/documentation_page

There's a big picture statement here that's sort of useful, https://prod.cms.va.gov/help/cms-knowledge-base-content-strategy-statement, but it's probably most useful to review an existing KB that describes something that already exists, like for example: CLPs!! https://prod.cms.va.gov/help/campaign-landing-pages

**Comment by chri5tia** [comment]
@jilladams Draft of Q&As
https://prod.cms.va.gov/help/cms-basics/how-to-use-reusable-qas

**Comment by jilladams** [comment]
Nice! Will take a look and save a revision with my changes.

**Comment by jilladams** [comment]
Added a draft, and I need to draft the Benefit Detail page one. 

Noting - this Help page exists: https://prod.cms.va.gov/help/resources-and-support/a-guide-to-resources-and-support-content-types and those links all point out to Github pages maintained by the Content team. Next week I wanna check with Content team to see if they already have a Benny draft we could start from.

**Comment by jilladams** [comment]
From BE refinement yesterday: the naming of Q&A stuff is changing and not reflected in the latest draft of the Q&A article, since i changed some of Christia's wording. We'll need to address that when the naming changes actually ship. 

Also: asked Content team to review the Q&A article, and provide background content for Ben Deets page: https://dsva.slack.com/archives/C01K37HRUAH/p1693929893131649?thread_ts=1693929600.105569&cid=C01K37HRUAH.  Danielle said she'll follow up this week.

**Comment by chri5tia** [comment]
I'm still planning to write the Benefit Detail Page KB if we get confirmation that it's needed.

**Comment by jilladams** [comment]
From planning: splitting out BD KB into a separate ticket: #15248

**Comment by jilladams** [comment]
Closing! 🎉
