### ISSUE TITLE
Minimum height on CKEditor is different on D10

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#14643]
## Describe the defect
In D10, the default minimum height for a standalone editor is smaller than in prod. This I think is minor however I wanted to write an issue because 1. it's a difference and 2. in the most recent editor research we got feedback that folks tended to like larger fields so even though this field expands as you type perhaps it might lead folks to think they shouldn't add as much?

## To Reproduce
1. Create a new [News Release List](https://vacms-12252-drupal-10-
opslrfeufzwsvhxx2uuv1wmvjbiq7wuq.ci.cms.va.gov/node/add/press_releases_listing)
2. Scroll down to Press release blurb
3. Click to expand this section
4. Notice that the editor is shorter than is currently is in prod

## AC / Expected behavior

- [ ] Default height of editor is unchanged from prod

## Screenshots
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/106678594/6d8ecebb-cbd2-4e68-95f9-bc1b1d5c56b8)

### Team
Please check the team(s) that will do this work.

- [x] `CMS Team`
- [ ] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`
- [ ] `Accelerated Publishing`

**Comment by EWashb** [comment]
@BerniXiongA6 do you know if this is something we need to address pre d10 launch? If not, we may want to consider a D10 cleanup task epic if we dont already have one

**Comment by edmund-dunn** [comment]
This seems to be an issue in core. https://www.drupal.org/project/drupal/issues/3241295 I posted a patch.

**Comment by edmund-dunn** [comment]
This has been fixed and merged into the D10 branch.
