### ISSUE TITLE
Develop and Implement Fix for SAMLauth failure

### ISSUE THREAD

**Issue by olivereri** [department-of-veterans-affairs/va.gov-cms#14641]
## Description
Based on the findings from #14640 and continued investigation thereafter, develop and implement a fix to be used on CMS Production 

## Acceptance Criteria
- [ ] Technical solution to fix or work around PIV Logon issue identified.

## Implementation Details

Please check the team(s) that will do this work.

- [x] `CMS Team`
- [ ] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`
- [ ] `Accelerated Publishing`

**Comment by EWashb** [comment]
Shall we close these and the associated tickets? We found a path forward for our SAML issues @BerniXiongA6 @ndouglas

**Comment by BerniXiongA6** [comment]
Will defer to @ndouglas on whether to close, thanks!

**Comment by ndouglas** [comment]
Yes, I believe this is no longer relevant.
