### ISSUE TITLE
Integrate test.prod.cms.va.gov with IAM Prod

### ISSUE THREAD

**Issue by olivereri** [department-of-veterans-affairs/va.gov-cms#14640]
## Description
To reproduce the error seen during July 20th's SAMLauth deployment the CMS be added to Identity and Access Management's (IAM) Prod IdP.  The CMS will be ready to integrate after generating and providing our Service Provider (SP) Metadata.

## Acceptance Criteria
- [x] Reply to IAM e-mail stating that we are ready to integrate test.prod.cms.va.gov
  - [x] Attach metadata from #14639
- [ ] Coordinate the integration with the Identity and Access Management team.
- [ ] Test Piv Logon and report findings in this issue

## Implementation Details

Please check the team(s) that will do this work.

- [x] `CMS Team`
- [ ] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`
- [ ] `Accelerated Publishing`

**Comment by productmike** [comment]
@olivereri @teeshe Included a few ticket peripherals (label, state, sprint, etc.) as well as assigning to Tolase for continuity sake once you're OOO Eric.

cc: @BerniXiongA6 @EWashb This ticket is a further breakdown of #14494 that is planned for sprint 90.

**Comment by teeshe** [comment]
Metadata shared with IAM team to setup test-prod cms with SAMLauth module and integrate with IAM prod IdP

**Comment by edmund-dunn** [comment]
Closing this ticket as unneeded.
