### ISSUE TITLE
Published Vet Center National Content does not appear on Front End

### ISSUE THREAD

**Issue by TroyA6** [department-of-veterans-affairs/va.gov-cms#14647]
## Describe the defect
Vet Center National Content changes are not appearing on the front end after being PUBLISHED - conversely, Vet Center national content changes saved as DRAFT do appear on the front end after being published

## To Reproduce Scenario 1 (Published content does not appear)
1. Go to 'National Vet Center content' `/centralized-content/national-vet-center-content`
2. Make a change
3. Publish
4. See error - change does not appear on FE

Prod CMS: https://prod.cms.va.gov/centralized-content/national-vet-center-content
FE example: https://www.va.gov/brooklyn-vet-center/

Possibly affected fields
- field_cc_vet_center_faqs (most definitely this one)
- field_cc_vet_center_call_center
- field_cc_non_traditional_hours
- field_cc_vet_center_featured_con

![Screenshot 2023-08-04 at 9 14 40 AM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/85581471/1f10496f-68e4-4611-974f-83de6db0b0eb)

## AC / Expected behavior
- [ ] Published content should appear on the front end after the next content release cycle.

 ## Additional context
- This may turn out not to be a FE issue, but initial investigation indicates it probably is.  [See comment](#issuecomment-1664826605)   
- If it is a FE issue, it might not be limited to Vet Centers as it may apply to anything using the FAQ collapsible 
- This appears to have been an issue for some time, but just discovered. No known workaround - 
Last verifiable successful publish date: 6//2023 -- 
(prevents users from accomplishing their work with no known workaround and needs to be addressed within 2 business days).

**Comment by TroyA6** [comment]
Currently investigating with @swirtSJW  @ndouglas  and @stefaniefgray - It seems that the Draft content that should not have displayed is no longer appearing on the site.

However, content that was published last Friday has not yet appeared on the site

**Comment by TroyA6** [comment]
Confirmed bug regarding DRAFT CONTENT appearing on FE after Content Release, AND Some published content does not appear on FE - Per  @swirtSJW  
There may be an issue with accordions -- content in accordion shows multiple times in the code, but in this case, this specific content appears only once -- Public Websites may have insight into this as they have recently worked with accordions. 
Possibly a Front End issue rather than CMS issue.

**Comment by TroyA6** [comment]
Assigning to @swirtSJW

**Comment by swirtSJW** [comment]
Content from this Centralized content node (/node/16142/) has some content showing and other content not showing.
The history looked normal with the exception of a revision being reverted on 7/14  (should not cause a problem, just noting it here 
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5752113/8a5ae570-95c3-4c1a-8352-5437d848877e)


The part that leads me to suspect this is actually a FE issue is that there is some of the new content showing in schema.org output but NOT showing in the html.  (I would expect the content to appear twice.  (once in schema, once in html)

Example: This string  "Do I have to be enrolled in VA health care to access Vet Center services" is found in 3 places (schema. rendered html, and data-analytics-faq-text)

This string "You don’t need to be enrolled in VA health care to be eligible" is only found in the schema but not in the html .

This tells me the data is making it to the FE but something is  causing it not to be rendered in the hrml.

Here is the full html of the page just to preserve it
[vetcenter.txt](https://github.com/department-of-veterans-affairs/va.gov-cms/files/12256087/vetcenter.txt)

**Comment by swirtSJW** [comment]
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5752113/738ae87c-89bf-4dd9-8c40-755d54413213)

**Comment by swirtSJW** [comment]
It is possible this is due to the content being three paragraph levels deep.  Entity Field Fetch should be able to handle three levels, but in reality we have no other instance going that deep.
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5752113/a28a5453-b569-4d1b-bfb5-25f7f1382cc8)

**Comment by swirtSJW** [comment]
Link to [Slack discussion](https://dsva.slack.com/archives/C0FQSS30V/p1691172365591429) 

The missing data is definitely making it from Drupal, to the GraphQL results.   The data is visible in the contentData object on staging view-source:https://staging.va.gov/brooklyn-vet-center/   View the source and search for "(VET TEC)"
It is just not making it to rendering by the proper template.

**Comment by jilladams** [comment]
Root cause identified: https://dsva.slack.com/archives/C0FQSS30V/p1691184788169489?thread_ts=1691172365.591429&cid=C0FQSS30V

**Comment by jilladams** [comment]
From refinement:
* The issue here, we think, is this is a 1st instance of content nested 3 levels deep in paragraphs
    * Max is troubleshooting the flattening of data to work out making sure the 3rd level deep gets surfaced
* To workaround our issue, Editor could move the Alert content up to a 2nd level. e.g. make "What are the covered educational assistance benefits?" into a Question

**Comment by jilladams** [comment]
@maxx1128 please add an end of sprint comment re: where we are on this ticket.

**Comment by maxx1128** [comment]
Updates on this ticket before I go on PTO for the remainder of the week:

[This pull request](https://github.com/department-of-veterans-affairs/content-build/pull/1653) is open to fix the data flattening. I've confirmed that the other pages of centralized content do not break as a result ([see links in this comment](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14670#issuecomment-1679362098)), and also that the reusable alerts are still intact as well (see below screenshots).

![Screen Shot 2023-08-15 at 2 00 43 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/10790736/9d7a53a2-6b03-43df-8745-c949a1b4d79c)
![Screen Shot 2023-08-15 at 2 00 39 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/10790736/08af9fb3-d3ee-49d7-8f91-d07890aac0ca)

At this point, I believe the pull request should be ready to merge after some code review with additional/repeated troubleshooting to make sure there are no other errors. [There was some discussion](https://github.com/department-of-veterans-affairs/content-build/pull/1653#discussion_r1291664789) about refactors to improve the logic related to the data flattening and the `wysiwyg` templates, but my opinion is that is best saved for a follow-up so it doesn't block the ticket from merginf.

**Comment by jilladams** [comment]
Michelle saw that the Editor seems to have taken advantage of the workaround and the Nat'l content is present in the front-end today. So: urgency lowered a bit.

**Comment by mmiddaugh** [comment]
I confirmed with Katherine Fung that the content was published using the proposed workaround so eligibility information is now available to Veterans. 
[As seen on Brooklyn Vet Center](https://www.va.gov/brooklyn-vet-center/)
(https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBajROIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--4b6ab5db401d2e3f862fbb3cb995a239fed1924d/image.png)

**Comment by swirtSJW** [comment]
The originally intended alert content is now showing as of yesterday 8/23/23.  Due to the code landing on prod on 8/22 and then the content being correctly changed on 8/23
