### ISSUE TITLE
Top task sensors

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#1467]
## User story 

As a UX researcher, I need access to a data set around top tasks, so I can develop UX improvement strategy.

## Acceptance criteria

- [ ] sensors for measuring our impact for at least a portion of top tasks are identified
- [ ] stories for integrating sensors with Google Analytics or other tracking tools are created and groomed

**Comment by EWashb** [comment]
closing- top tasks were not implemented with this scope
