### ISSUE TITLE
Review of new or updated KB article : VAMC system health service KB articles in support of v1 

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-cms#14689]
## Background
VAMC editors understand that they maintain their websites but likely do not think of it as maintaining the source of truth for services available at their facilities. This has been a separate workstream with different parties responsible.
Currently, PAOs/editors are instructed to contact Lighthouse to update their service information.
With v1, we’ll need to help editors understand that

- the information they enter into Drupal will be the source of truth and
- it is important to keep service information up to date and accurate for Veterans viewing their website and 
- it is important to keep service information up to date and accurate because the information can be used across the entire ecosystem.

This issue is one of several tied to epic #14207 

## VAMC system health service KB articles
-  [How to add or edit a VAMC system health service](https://prod.cms.va.gov/help/vamc/how-to-add-or-edit-a-vamc-system-health-service) 
-  Possible duplicate/overlap: [How to edit a VAMC system health service](https://prod.cms.va.gov/help/va-medical-centers-vamcs/about-health-services/how-to-edit-a-vamc-system-health-service) **_- suggest we archive this_**
  
## Priority or deadline for request
Choose either Deadline or a priority:

- [x] Deadline: August 24, 2023 - in support of Lighthouse V1
- [ ] Priority:
  - [ ] Critical
  - [ ] High
  - [ ] Medium
  - [ ] Low

## Can article(s) be published?
Once the article has been fully reviewed, can the article(s) be published? For example, is anything tied directly to an upcoming feature and this information should not be published until the feature is on production?
- [ ] Yes, all article(s)s within this ticket can be published once reviewed
- [x] No, the article(s) within this ticket should not be published and should only be reviewed - please notify Michelle and Jane in #sitewide-facilities
  
## Notify the CMS team of this ticket in the cms-support Slack channel.
- [ ] I acknowledge that I must notify #cms-support after submitting this issue.

## Acceptance Criteria
- [ ] Both articles are reviewed by CMS Team
- [ ] Both articles are reviewed by Help desk
- [ ] If approved above, [How to add or edit a VAMC system health service](https://prod.cms.va.gov/help/vamc/how-to-add-or-edit-a-vamc-system-health-service) is published
- [ ] Duplicative KB article: [How to edit a VAMC system health service](https://prod.cms.va.gov/help/va-medical-centers-vamcs/about-health-services/how-to-edit-a-vamc-system-health-service) is archived
- [ ] Requesting person/team has been notified that article was reviewed/published

**Comment by mmiddaugh** [comment]
Draft ready for review in Sharepoint: [How to add or edit a VAMC system health service](https://dvagov-my.sharepoint.com/:w:/r/personal/suzanne_middaugh_va_gov/Documents/KB%20draft_system%20health%20service.docx?d=w5d91c33623ef49dca19e72ee29addb88&csf=1&web=1&e=R0B5Xz)
- Note: I do not have access to the KB article style guidance in Confluence
- The primary change in this article is to add context around the importance of keeping health service information accurate and up to date

**Comment by xiongjaneg** [comment]
Submitted to CMS Team on 8/17. Per Berni, OK to publish without CMS Team review if timing is an issue.

**Comment by productmike** [comment]
@xiongjaneg Accepted into sprint 92 on the CMS side for review.

**Comment by mmiddaugh** [comment]
VHA DM has reviewed and approved this article.

**Comment by xiongjaneg** [comment]
Changes approved by VHA DM have been published due to Lighthouse v1 launch timing

**Comment by productmike** [comment]
Reviewed and approved by CMS team. Removing CMS labels, etc..
