### ISSUE TITLE
Review of new or updated KB article : How do I update my VAMC Facility's Basic Location Data? in support of V1

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-cms#14691]
## Background
VAMC editors understand that they maintain their websites but likely do not think of it as maintaining the source of truth for services available at their facilities. This has been a separate workstream with different parties responsible.
Currently, PAOs/editors are instructed to contact Lighthouse to update their service information.
With v1, we’ll need to help editors understand that

- the information they enter into Drupal will be the source of truth and
- it is important to keep service information up to date and accurate for Veterans viewing their website and 
- it is important to keep service information up to date and accurate because the information can be used across the entire ecosystem.

This issue is one of several tied to epic #14207 
It also incorporates instructions requested in Edit existing KB article for updating VAMC facility data #13890

## Facility & locations list KB articles 
- [How do I update my VAMC Facility's Basic Location Data?](https://prod.cms.va.gov/help/vamc/how-do-i-update-my-vamc-facilitys-basic-location-data)

## Priority or deadline for request
Choose either Deadline or a priority:

- [x] Deadline: August 24, 2023 - in support of Lighthouse V1
- [ ] Priority:
  - [ ] Critical
  - [ ] High
  - [ ] Medium
  - [ ] Low

## Can article(s) be published?
Once the article has been fully reviewed, can the article(s) be published? For example, is anything tied directly to an upcoming feature and this information should not be published until the feature is on production?
- [ ] Yes, all article(s)s within this ticket can be published once reviewed
- [x] No, the article(s) within this ticket should not be published and should only be reviewed - please notify Michelle and Jane in #sitewide-facilities
  
## Notify the CMS team of this ticket in the cms-support Slack channel.
- [ ] I acknowledge that I must notify #cms-support after submitting this issue.

## Acceptance Criteria
- [ ] Article reviewed by CMS Team
- [ ] Article reviewed by Help desk
- [ ] If approved above, article is published
- [ ] Requesting person/team has been notified that article was reviewed/published

**Comment by mmiddaugh** [comment]
Draft is ready and available in [Sharepoint](https://dvagov-my.sharepoint.com/:w:/r/personal/suzanne_middaugh_va_gov/Documents/KB%20article%20draft_Basic%20data.docx?d=w8e9282b694a04804a5acee2094889084&csf=1&web=1&e=qAvg3n)

**Comment by mmiddaugh** [comment]
Note: I do not have access to the KB article style guidance in Confluence. Edits will be gratefully accepted!

**Comment by xiongjaneg** [comment]
Submitted to CMS Team on 8/17. Per Berni, OK to publish without CMS Team review if timing is an issue.

**Comment by xiongjaneg** [comment]
Reviewed, no comments

**Comment by productmike** [comment]
@xiongjaneg Accepted into sprint 92 on the CMS side for review.

**Comment by mmiddaugh** [comment]
VHA DM has reviewed and approved this article.

**Comment by xiongjaneg** [comment]
Changes approved by VHA DM have been published due to Lighthouse v1 launch timing

**Comment by productmike** [comment]
Reviewed and approved by CMS team. Removing CMS label.
