### ISSUE TITLE
Implement VBA roles and permissions in Drupal

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#14695]
Drupal implementation for roles and permissions is built to match the spec #13800 

Refer to [VBA Content Specs in Sharepoint](https://dvagov.sharepoint.com/:x:/s/SitewideFacilitiesTeam/EVVWpQp091ZEvI2n-9iyvTQBGYFZjxlVPN3Zfyz-Eh6Oyg?e=NVvsCc)

## Acceptance Criteria
- [ ] Fields, machine names, help text, required, cardinality, character limits and any other Drupal implementation specifics are implemented as specified in the spec
- [ ] Fields appear within fieldsets and in order as shown in the spec
- [ ] Follow up tickets are created to track any remaining work that arises during implementation

**Comment by xiongjaneg** [comment]
This is the Drupal stub. Front end stub will be separate and upcoming.

**Comment by davidmpickett** [comment]
@xiongjaneg this is a duplicate with #11334 - consider how you want to merge

**Comment by xiongjaneg** [comment]
closed in favor of #11334
