### ISSUE TITLE
Review of new or updated KB article : Health Services List KB articles  in support of v1

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-cms#14690]
## Background
VAMC editors understand that they maintain their websites but likely do not think of it as maintaining the source of truth for services available at their facilities. This has been a separate workstream with different parties responsible.
Currently, PAOs/editors are instructed to contact Lighthouse to update their service information.
With v1, we’ll need to help editors understand that

- the information they enter into Drupal will be the source of truth and
- it is important to keep service information up to date and accurate for Veterans viewing their website and 
- it is important to keep service information up to date and accurate because the information can be used across the entire ecosystem.

This issue is one of several tied to epic #14207 

## Health Services List KB articles  
- [How to edit a Health Services List](https://prod.cms.va.gov/help/va-medical-centers-vamcs/about-health-services/how-to-edit-a-health-services-list)
- [How do I change the name of a health service?](https://prod.cms.va.gov/help/vamc/how-do-i-change-the-name-of-a-health-service)
  
## Priority or deadline for request
Choose either Deadline or a priority:

- [x] Deadline: August 24, 2023 - in support of Lighthouse V1
- [ ] Priority:
  - [ ] Critical
  - [ ] High
  - [ ] Medium
  - [ ] Low

## Can article(s) be published?
Once the article has been fully reviewed, can the article(s) be published? For example, is anything tied directly to an upcoming feature and this information should not be published until the feature is on production?
- [ ] Yes, all article(s)s within this ticket can be published once reviewed
- [x] No, the article(s) within this ticket should not be published and should only be reviewed - please notify Michelle and Jane in #sitewide-facilities
  
## Notify the CMS team of this ticket in the cms-support Slack channel.
- [ ] I acknowledge that I must notify #cms-support after submitting this issue.

## Acceptance Criteria
- [ ] Article reviewed by CMS Team
- [ ] Article reviewed by Help desk
- [ ] If approved above, article is published
- [ ] Requesting person/team has been notified that article was reviewed/published

**Comment by mmiddaugh** [comment]
Drafts are ready and available in Sharepoint: 

- [How to edit a Health Services List](https://dvagov-my.sharepoint.com/:w:/r/personal/suzanne_middaugh_va_gov/Documents/KB%20draft_Health%20services%20list.docx?d=wf87b07dad49c4d8b9dd8b29cd886b3ca&csf=1&web=1&e=dbqhSI)

- [How do I change the name of a health service?](https://dvagov-my.sharepoint.com/:w:/r/personal/suzanne_middaugh_va_gov/Documents/How%20to%20change%20the%20name%20KB%20draft.docx?d=w8c0aa8eef1894e31b4b3a9d43d1d5b7e&csf=1&web=1&e=u5cMo1)

Note: I do not have access to the KB article style guidance in Confluence.

**Comment by jilladams** [comment]
@mmiddaugh since you did all the work here, I'm not certain if we should track this in the Facilities sprint reporting or not, but I'm inclined to say no -- lemme know if you agree.

**Comment by xiongjaneg** [comment]
New content looks fine. Capitalize start of second sentence under Content intent.

**Comment by xiongjaneg** [comment]
Submitted to CMS Team on 8/17. Per Berni, OK to publish without CMS Team review if timing is an issue.

**Comment by mmiddaugh** [comment]
VHA DM has reviewed and approved this article.

**Comment by xiongjaneg** [comment]
Changes approved by VHA DM have been published due to Lighthouse v1 launch timing

**Comment by productmike** [comment]
Reviewed and approved by CMS team. Removing CMS labels, etc..
