### ISSUE TITLE
Footer Defect: Footer template pulls "description" field instead of "title" to for link text

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#14697]
## To Reproduce
1. Create a new menu link for the Footer Rail menu (e.g. Harassment link)
2. Enter required Menu link title, and leave non-required Description field blank
3. Save and wait for content build
4. See that link text is an empty string (and not clickable) on prod footer because the template pulled the blank description field

## AC / Expected behavior
- [x] Footer displays _Menu link title_ field
- [x] Asked DST whether hover should show the `title` html attribute
  - [ ] ~If desired by DST, ensured that the _Description_ field is used in the FE as described in the CMS help text: 'Shown when hovering over the menu link.'~
  - [x] Otherwise, ticketed removing that message (and possibly field?) from CMS help text
- [x] Checked whether the other sections of the footer are using the correct fields to build links
  - [x] and fixed as needed
- [x] Checked header for gut check on correct fields being utilized

## Screenshots

CMS:
<img width="648" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/4054752/78805231-5bf9-4151-a85f-5c9e71a7ae5d">

Blank menu item:
<img width="474" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/4054752/7f9c221d-6881-4c0f-b56d-2269c8f8a7bb">

Code that pulls _description_ field:
```const formatLink = (link, linkIndex, columnId, hostUrl) => {
  return {
    column: columnId,
    href: convertLinkToAbsolute(hostUrl, link?.url?.path),
    order: linkIndex + 1,
    target: null,
    title: link?.description,
  };
}; 
```

**Comment by randimays** [comment]
@wesrowe re: tooltips / hover behavior

DST said we could ticket a request to add tooltips to the links, but [@laflannery recommends against](https://dsva.slack.com/archives/C01DBGX4P45/p1691609349807209?thread_ts=1691607021.411639&cid=C01DBGX4P45) adding them in most cases.

> Otherwise, ticketed removing that message (and possibly field?) from CMS help text
Can we confirm (@dsasser @chri5tia ?) that this `description` field is only used for tooltips? [Laura said](https://dsva.slack.com/archives/C01DBGX4P45/p1691609697144259?thread_ts=1691607021.411639&cid=C01DBGX4P45) it's possible these menus are in use for Benefit Hubs. If it's only for tooltips, we can remove the messaging & field entirely.

**Comment by randimays** [comment]
Update: PR approved by PW. Waiting for Platform to approve.

**Comment by randimays** [comment]
Update: PR approved. Waiting to merge until Monday.
