### ISSUE TITLE
Update Service Location paragraph type to account for VBA

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#14704]
## Description
Drupal implementation for VBA Service Location paragraph type is built to match the spec #13128. (Note from Dave - the spec has not been updated to reflect the FE design, so it is wildly out of date)

- VBA Content Specs XLS listed in #13096 

Collaborate with DaveP if questions arise based on the spec during implementation.

### Change management notes
We want to add new VBA fields to Service Location, but do not want those fields to be visible in Prod to VAMC editors yet. That requires Change Management. #14758 

## Acceptance Criteria
- [x] Most [recent design](https://www.sketch.com/s/891d33ae-152d-471c-ab5d-9aedf89cf6ff/p/578C3207-C5A3-4303-AB18-4AFC27AC54D2/canvas) is reviewed. [Edited to add updated link]
- [x] Spec is reviewed to accommodate most recent design.
- [x] Design is implemented.
- [x] I expect that these changes may be put in a PR branch pending change management.
- [ ] Link to view implementation is shared with Laura for accessibility audit in ticket #14893 
- [x] Note any comments in #14837

**Comment by jilladams** [comment]
@xiongjaneg we need to cut a follow up ticket to put in the backlog for exposing these fields and change management, when the time comes.

**Comment by xiongjaneg** [comment]
1. Does this include anything about restrictions? In the spec, there's a cardinality restriction on Facility.
2. Is 3 functional or does it need to be increased?
3. Is there work that needs to come before this? Yes.

**Comment by xiongjaneg** [comment]
@thejordanwood Can you confirm the Sketch link Christian is referring to is the most recent? Thank you!

**Comment by thejordanwood** [comment]
@xiongjaneg @omahane This is [the Figma file](https://www.figma.com/file/aKdT4weNNthDxb3r6MolEh/VBA-Content-Specs?type=design&node-id=100%3A481&mode=design&t=j3jWKWMmhqxHzgOG-1) that will have the Service location paragraph type. It's a bit confusing, but CMS designs are in Figma and front end designs are in Sketch. 

I just commented on [my Service locations ticket](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14890#issuecomment-1743817138) and pointed out that, while I've done some UX review of this, I haven't completed the work yet. I'm missing some of the suggestions [in Dave's spreadsheet](https://docs.google.com/spreadsheets/d/1kulQsfmJP_qVrb-MRkKsEVYkdwkNxNEa/edit?usp=sharing&ouid=109515556316253843471&rtpof=true&sd=true). Specifically the suggestion for better help text to describe what Service Locations are and the addition of the delivery method field.

I'm now realizing that perhaps I should have completed that ticket first, before completing work for Service Regions and other content types that contain the Service Location section.

**Comment by xiongjaneg** [comment]
@omahane Do you have what you need to continue work on this?

**Comment by omahane** [comment]
@xiongjaneg Can I get some clarity on the title? Is this something that an editor is going to manually create/edit?

Other facility service titles are generated:
<img width="1532" alt="Screenshot 2023-10-06 at 6 46 32 AM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/766573/ebc58193-7a9a-4149-b04d-0a00c0e5e0a7">

## Patterns for service titles
Vet Center Service title
- `[facility name] - [service name]`

VAMC System Health service title
- `[service name] at [system name]`

VAMC Facility Health service title
- `[service name] - [facility name]`

**Comment by omahane** [comment]
The other thing I want to confirm is that, aside from title (which I've asked about above), the only net new field is "Service description." Otherwise, it's mostly help text changes/additions. Is that right, @thejordanwood ?

**Comment by davidmpickett** [comment]
> @xiongjaneg I want to confirm that this is the design we're talking about reviewing in in the first AC: https://www.sketch.com/s/891d33ae-152d-471c-ab5d-9aedf89chttps://www.sketch.com/s/891d33ae-152d-471c-ab5d-9aedf89cf6ff/p/FC995695-308A-4493-8461-D9AFE6DC6B25/canvasf6ff/p/FC995695-308A-4493-8461-D9AFE6DC6B25/canvas

The most recent FE design to review is probably the annotated Service accordion:
https://www.sketch.com/s/891d33ae-152d-471c-ab5d-9aedf89cf6ff/p/578C3207-C5A3-4303-AB18-4AFC27AC54D2/canvas

**Comment by omahane** [comment]
You're so right, Dave. I was totally conflating the two, having looked at the Figma file from here: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14704#issuecomment-1743824509

**Comment by omahane** [comment]
Per [Slack conversation with Dave](https://dsva.slack.com/archives/C0FQSS30V/p1696862946597819?thread_ts=1696625019.046019&cid=C0FQSS30V), we'll be handing the Appointments structure in https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14837, rather than doing so here.

**Comment by jilladams** [comment]
@omahane can you confirm the state of this ticket? Not all ACs are checked, and not sure ifyou need an assist with anything since Jane is gone?
