### ISSUE TITLE
Implement updates to VBA Facility Service content type

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#14703]
## Description
Drupal implementation for VBA Facility Service content type is built to match the spec #13129 
Refer to [VBA Content Specs in Sharepoint](https://dvagov.sharepoint.com/:x:/s/SitewideFacilitiesTeam/EVVWpQp091ZEvI2n-9iyvTQBGYFZjxlVPN3Zfyz-Eh6Oyg?e=NVvsCc)

## Acceptance Criteria
- [ ] Fields, machine names, help text, required, cardinality, character limits and any other Drupal implementation specifics are implemented as specified in the spec
- [ ] field_service_name_and_descripti should show the VBA description from the service term in both edit view and node view.
- [ ] Fields appear within fieldsets and in order as shown in the spec
- [ ] Add comment in Accessibility Audit ticket #14897 with link for Laura on where to review implementation.
- [ ] Follow up tickets are created to track any remaining work that arises during implementation

**Comment by xiongjaneg** [comment]
UX Review ticket to be stubbed in UX Refinement

**Comment by omahane** [comment]
I have created a follow-up ticket for showing facility information: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15413
