### ISSUE TITLE
Implement updated VBA fieldset of VA Service taxonomy

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#14702]
## Description
Drupal implementation for the updated VBA fieldset of VA Service taxonomy is built to match the spec #13131 
Refer to [VBA Content Specs in Sharepoint](https://dvagov.sharepoint.com/:x:/s/SitewideFacilitiesTeam/EVVWpQp091ZEvI2n-9iyvTQBGYFZjxlVPN3Zfyz-Eh6Oyg?e=NVvsCc)

## Acceptance Criteria
- [ ] Fields, machine names, help text, required, cardinality, character limits and any other Drupal implementation specifics are implemented as specified in the spec
- [ ] Fields appear within fieldsets and in order as shown in the spec
- [ ] Follow up tickets are created to track any remaining work that arises during implementation

**Comment by xiongjaneg** [comment]
for Common Conditions, leave as string for now

**Comment by swirtSJW** [comment]
We might want common conditions to be a free tagging terms.  (pondering this)

**Comment by omahane** [comment]
@davidmpickett Do you have a list of the actual types of care for the VBA services in VA Services taxononomy?

**Comment by omahane** [comment]
Dave responded here: https://dsva.slack.com/archives/C0FQSS30V/p1693247101930659?thread_ts=1693244689.724179&cid=C0FQSS30V
