### ISSUE TITLE
Implement Service Region content type

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#14705]
# Description
Drupal implementation for VBA Service Region is built to match the spec #13127
- [VBA Content Specs XLS in Sharepoint](https://dvagov.sharepoint.com/:x:/s/SitewideFacilitiesTeam/EVVWpQp091ZEvI2n-9iyvTQBGYFZjxlVPN3Zfyz-Eh6Oyg?e=NVvsCc)  -- Legend tab explains color highlighting

Collaborate with DaveP if questions arise based on the spec during implementation.

May not be ready to implement, may need a follow up iteration ticket - discuss with DaveP & Jane.
- Regional Service Description - (may not be needed at this level, may move into Service Location)
- Service Location paragraph type - (reference existing one)

## Acceptance Criteria
- [x] A Service Region content type is created 
- [x] Fields, machine names, help text, required, cardinality, character limits and any other Drupal implementation specifics are implemented as specified in the XLS
- [x] Fields appear within fieldsets and in order as shown in the XLS
- [x] Only Drupal Admins are assigned permissions at this time
- [ ] ~Follow up tickets are created to track any remaining work that arises during implementation~

**Comment by swirtSJW** [comment]
Question:  Spec says the description should be plain text, but help text says use 6 bullets.  One of these is not telling the truth.

**Comment by swirtSJW** [comment]
@davidmpickett  A content type always needs an alias pattern.   What should the pattern be for Service regions?  Since these will have no FE page, we have to be careful that the pattern we choose will not block other actual pages with FE URLs.

**Comment by swirtSJW** [comment]
Notes to self on what I need to build to support this (scratchpad, updating as I go)

- [ ] entity reference view filtered to VBA facilities
- [ ] role for VBA national editor.

**Comment by davidmpickett** [comment]
> Question: Spec says the description should be plain text, but help text says use 6 bullets. One of these is not telling the truth.

Per the ticket body: Regional Service Description - (may not be needed at this level, may move into Service Location).

Spec is out of date with FE design. Relevant screen from [FE prototype](https://www.figma.com/file/8RYmYfVGS9CUfZbomH5lBe/VBA-Regional-Office-Prototype?type=design&node-id=0-1401&mode=design&t=OlUf02xNnn0bHhxP-0). The second card (Get help checking the status of your COE) is an example of service region information (all handled within service location). 

[Home loans Service accordion.pdf](https://github.com/department-of-veterans-affairs/va.gov-cms/files/12433912/Home.loans.Service.accordion.pdf)

Recommendation would be hide the body property and mark field as not needed in spec

**Comment by davidmpickett** [comment]
> Notes to self on what I need to build to support this (scratchpad, updating as I go)
> 
> * [ ]  role for VBA national editor.

note that creating a new role is outside the scope of this ticket and should be tracked via https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11334

**Comment by swirtSJW** [comment]
> Are there existing patterns we've adopted for other content types without FE pages that we could adapt?

@davidmpickett Most of our patterns are based on either a field_office they are are assigned to (in red) or they are a fixed base path.
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5752113/49c6c6fb-185c-4e8c-90d9-c0b44485f23c)

We have some examples of items (mostly taxonomies) that have no direct FE presence or facility affiliation.  But I also think we got some of them wrong (example service taxonomy terms live at /health-care/   which is no longer true.
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5752113/ff62d63a-9aad-4d03-812f-1b788daa20aa)


I am thinking we want something that is facility type agnostic right?  

I am tempted to say we should namespace all these to /cms-internal/  we would have things like
- /cms-internal/service/[term:name]
- **/cms-internal/service-region/[node:title]** 
- /cms-internal/resources/tag/[term:name]
- /cms-internal/resources/[term:name]

**Comment by swirtSJW** [comment]
Interesting error here trying to add `field_service_location`
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5752113/1b131107-cd0a-4437-9eda-6316dacee3cb)

After the error, the field goes missing completely
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5752113/272bf7f6-a1f6-4731-990a-76b3406879b0)


I am investigating further, but this might be related to translation work done by CMS team.

**Comment by swirtSJW** [comment]
WIP PR #14980   Still needs a little refining on layout and default timestamp.

**Comment by swirtSJW** [comment]
This is still throwing an error related to translation 
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5752113/e2d3a87f-a9eb-49e8-9c56-1901bbb45d8a)

![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5752113/56ec4d7b-6d6e-48e4-a1f0-e0ebc065e01d)

Still trying to get to the bottom of it.

**Comment by swirtSJW** [comment]
This PR is in QA now.  I encountered 2 unrelated bugs that are now also resolved because they were blockers to finishing this so I fixed them as part of the PR.

**Comment by swirtSJW** [comment]
PR is merged and complete.
