### ISSUE TITLE
Set up self-hosted runners for next-build GHA

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#14710]
## Description
We will need self-hosted runners for next-build GHA so that our CI can reach other servers behind the firewall. We want these runners to be managed by an ASG (autoscaling group) so that GHA always has enough resources to run all the build and CI processes it needs to.

We can set up runners and integrate them with next-build GHA as described here: https://vfs.atlassian.net/wiki/spaces/OT/pages/1474595213/Self-Hosted+Runners

## Acceptance Criteria
- [ ] ASG is set up to manage EC2 instances for next-build GHA
- [ ] Runners are automatically registered with GHA and used by next-build GHA

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [ ] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`
- [x] `Accelerated Publishing`

**Comment by timcosgrove** [comment]
This is stretch for sprint 91.

**Comment by timcosgrove** [comment]
Kit and Tanner will also work on this one.

**Comment by tjheffner** [comment]
PR merged, terraform applied to the devops repo:
https://github.com/department-of-veterans-affairs/devops/pull/13402

Runners have been assigned to the next-build repo:
https://github.com/department-of-veterans-affairs/next-build/settings/actions/runners


We also updated the AWS Console with the changes in the cleanup lambda, per the docs here (step 3 after terraform is applied): https://vfs.atlassian.net/wiki/spaces/OT/pages/1474595213/Self-Hosted+Runners

**Comment by tjheffner** [comment]
If we have long running jobs in the future (long a11y tests or what have you), Nate provided some helpful tips here: https://dsva.slack.com/archives/C01SR56755H/p1694116656786089
