### ISSUE TITLE
[RENAMED] "Addiction and substance abuse care" has become "Addiction and substance use care"

### ISSUE THREAD

**Issue by omahane** [department-of-veterans-affairs/va.gov-cms#14728]
## Describe the defect
While working with Lighthouse on the [services push](https://github.com/department-of-veterans-affairs/va.gov-cms/pull/13464), we noticed that we have two services with remarkably similar names:

- Addiction and substance abuse care
- Addiction and substance use care

The issue is that "Addiction and substance abuse care" no longer exists in the VA Services taxonomy.

This has been the case since at least May 31, per [this Slack thread](https://dsva.slack.com/archives/C0FQSS30V/p1685555188190509).

The revision history does not capture this change:
https://prod.cms.va.gov/taxonomy/term/47/revisions

Does someone know about this change?

## To Reproduce
1. Go to https://prod.cms.va.gov/coatesville-health-care/locations/coatesville-va-medical-center
2. Scroll down to the services listing
3. [ ] Confirm that "Addiction and substance abuse care at VA Coatesville health care" shows

1. Go to https://www.va.gov/coatesville-health-care/locations/coatesville-va-medical-center/
2. Scroll down to the "Health services offered here"
3. Confirm that the "Addiction and substance use care" shows

## AC / Expected behavior

- One name should be determined for this service.
- All services with the other name are updated and saved with the new name.

## Screenshots

![Screenshot 2023-08-09 at 1.18.42 PM.png](https://images.zenhubusercontent.com/62aa0d60f60c1181e8837c67/9eb38113-d021-4944-884d-13196f87c688)

## Additional context
Fixing this is important/essential to getting the services push work complete.

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Defect")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS workstream (orange) (not needed for bug tickets)
- [ ] CMS-supported product (black)

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [ ] `Public Websites`
- [x] `Facilities`
- [ ] `User support`
- [ ] `Accelerated Publishing`

**Comment by omahane** [comment]
Feb 3, 2023, it was 
Addiction and substance use care
per [Wayback machine](https://web.archive.org/web/20230203225035/https://www.va.gov/pittsburgh-health-care/locations/pittsburgh-va-medical-center-university-drive/)

Jan 4, 2023, it was
Addiction and substance abuse care
per [Editor training environment - please do not delete](https://main-qtpbfivdfzrlrlyiqwmanznaobpek1ca.demo.cms.va.gov/admin/structure/taxonomy/manage/health_care_service_taxonomy/overview)

**Comment by davidmpickett** [comment]
@omahane has all the work been done to resolve the downstream impacts of this change?

**Comment by mmiddaugh** [comment]
Where does this stand @davidmpickett @omahane

**Comment by davidmpickett** [comment]
All services in Drupal were renamed to match new term title. I assume this was done with a Bulk operation last August, but that was never documented on this ticket.

[Only instances of word abuse in the CMS](https://prod.cms.va.gov/admin/content?title=abuse&type=All&moderation_state=All&owner=All) are on other content types
