### ISSUE TITLE
Force push of services should not push draft services

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#14733]
## Description
In testing with Lighthouse, it was determined that when we force push services that we are force pushing services in draft, and we should not be.

## Acceptance Criteria
- [ ] VAMC services in draft should not be force pushed.
- [ ] published services should only force push their default revision, not necessarily the most recent revision.

**Comment by swirtSJW** [comment]
This is likely a blocker for FacilityAPI V1

**Comment by swirtSJW** [comment]
I think instead of moderation state, we just want published = 1 
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5752113/b9e74df4-e2e6-4e4c-b147-17a9dbe97f1c)

**Comment by omahane** [comment]
@swirtSJW  I notice that we are already checking for draft, but it's the opposite of what we are now thinking:
```
   case (!$defaultRevisionIsPublished && !$thisRevisionIsPublished):
        // Draft on node that has not been published, should be pushed.
        $push = TRUE;
        break;
```
in `docroot/modules/custom/va_gov_post_api/src/Service/PostFacilityService.php`

Is there any reason why we should keep this and add another condition? 
I only see this being called to push services, so I don't think the above is what we want anymore.
