### ISSUE TITLE
Investigate analytics tools beyond Google Analytics for tracking KPIs 

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#1473]
## Acceptance Criteria
- [ ] We have evaluated candidate tools that will help track the kinds of KPIs implicit in key results or metrics. 
- [ ] Can be leveraged for the #1351 and #1195 and other epics. 

## Background
- See what tools Platform team is using (Datadog?)

**Comment by jefflbrauer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VAgov-CMS-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/1473?planning-poker) with ZenHub @ElijahLynn @indytechcook @ndouglas @olivereri @timcosgrove

**Comment by jefflbrauer** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VAgov-CMS-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/1473?planning-poker) with ZenHub @cweagans
