### ISSUE TITLE
Spike: Lovell code & business logic documentation

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#14746]
## Description
There is much functionality in both CMS and Content Build that handles the Lovell case. This will need to be implemented for Next Build as all.

Please keep in mind the specific case of News Stories, as we need to support Lovell News Stories in the short term.

For Content Build:
* identify all places where Lovell-specific templates or business logic are implemented. Include code links and explanations where possible

For CMS:
* Identify all places where Lovell-specific fields, logic, or entities are implemented. Include code links and explanations where possible.
* Look at how that information is sent over GraphQL, and examine if a JSON:API equivalent is already available or if further work is needed to provide that information to JSON:API

## Acceptance Criteria
- [x] For Content Build, all Lovell-specific functionality is clearly identified and linked
- [x] For CMS, all Lovell-specific functionality is clearly identified and linked
- [ ] For CMS, identify how Lovell data is queried via GraphQL and see if that data is available to JSON:API or not

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [ ] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`
- [x] `Accelerated Publishing`

**Comment by timcosgrove** [comment]
In theory this may be documented; ask Facilities team and former team members after this.

**Comment by jtmst** [comment]
WIP
Lovell Spike Notes
Content-build:
- Overall: The code in content-build manages content and URLs related Lovell pages, with specific variations like "VA" and "TRICARE". The code provides functionalities for creating variations, manipulating URLs, determining types of pages, modifying breadcrumbs, and adding featured listing items to specific types of pages.
- src/site/stages/build/drupal/process-lovell-pages.js
    - Summary: This will customize the content, links, and structure of Lovell pages based on whether they are TRICARE or VA variants. 
        - getModifiedLovellPage: takes a page and page variant and modifies elements on the page (such as breadcrumbs, url, title, etc)
        - lovellMenusModifyLinks: modifies labels and paths of menu links recursively and filters out unnecessary links based on variant
        - processLovellPages: Categorizes the web pages into different sets (like Federal, TRICARE, VA, etc.) and processes them accordingly. The goal being  to modify the TRICARE and VA pages with content from the Federal pages.
- src/site/stages/build/drupal/lovell/update-page.js
    - Summary: Manipulates and retrieves data specific to the different Lovell page variants.  Alters URL paths, titles, and breadcrumbs according to whether the page is TRICARE or VA.
        - getLovellPageVariables:  For a given page and variant, will clone the page and return an object with details about the page, variant type, variant name, and specific links
- src/site/stages/build/drupal/lovell/featured-items.js
    - Adds, filters, and sorts featured listings and inserts them into the main page structure
- src/site/stages/build/drupal/lovell/helpers.js
    - Provides utility functions for categorizing, naming, and URL generation for different Lovell page types
- Switch Link
    - src/site/includes/lovell-switch-link.drupal.liquid
    - assigns VA or TRICARE distinction

CMS:
- Overall: Provided URL handling specific to Lovell entities and has logic to identify.lovell content within the CMS.
    - docroot/modules/custom/va_gov_lovell/va_gov_lovell.module
      -  The va_gov_lovell module provides specific modifications related to the "Lovell Federal" functionality in the CMS. This includes altering node edit forms to attach libraries, providing help information through a link to an external README, and adding a validation constraint to ensure proper relationship between sections and listings for certain content types.
  - docroot/modules/custom/va_gov_lovell/js/limit_lovell.js
      - Provides CMS frontend functionality to handle the visibility and select options in dropdown menus related to Lovell based on whether the selected type is VA or TRICARE
  - docroot/modules/custom/va_gov_lovell/js/winnowServiceNamesTricare.js
      - Shows or hides content in dropdown based on whether TRICARE or VA variants are selected
  - docroot/modules/custom/va_gov_lovell/src
      - docroot/modules/custom/va_gov_lovell/src/LovellOps.php
          - Provides various helper methods for managing URLS paths, prefixes, and validations for Lovell-related content
      - Additional files for managing breadcrumb functionality, and menu trees
  - docroot/modules/custom/va_gov_backend/src/Plugin/Block/SidebarMenusBlock.php
      - Determines the type of lovell menu to display, as well as fallback behavior
  - docroot/modules/custom/va_gov_menu_access/src/Service/MenuReductionService.php
      - Assigns menu type based on if Lovell subsystem is found
  - docroot/modules/custom/va_gov_post_api/src/Service/PostFacilityService.php
      - If the entity belongs to the lovell-tricare section, it is not pushed to the Post API queue
  - docroot/modules/custom/va_gov_post_api/src/Service/PostFacilityStatus.php
      - Does not push to lighthouse if entity belongs to lovell-tricare section
    - docroot/modules/custom/va_gov_workflow_assignments/src/Plugin/Block/EntityMetaDisplay.php
        - If the given node is of the ‘LovellOps’ type, it fetches the appropriate URLs, builds an array specific to Lovell.
