### ISSUE TITLE
Spike: Breadcrumb modules for Drupal JSON:API

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#14741]
## Description
Drupal does not provide Breadcrumb information to JSON:API natively. There are a couple modules identified that may fill that gap.

Evaluate these modules, and any others, to confirm
* Breadcrumb data is retrievable via JSON:API
* Whether breadcrumb data can be retrieved along with an existing request (i.e. attached to a single node, along with entity path info) or whether it needs to be retrieved separately
* Whether the module respects the manipulation of breadcrumb data that CMS does (see this ticket: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14742)

The data should be checked to be equivalent with what GraphQL currently provides for breadcrumb data (example queries?).

Potential modules (others may be available):
* https://www.drupal.org/project/computed_breadcrumbs
* https://www.drupal.org/project/jsonapi_hypermedia (this adds a lot of additional functionality)
* https://www.drupal.org/project/decoupled_kit (adds other additional functionality)

## Acceptance Criteria
- [x] Modules are evaluated based on whether they can correctly provide Breadcrumb data that matches what GraphQL currently provides
- [x] Other functionality provided by the modules if any is documented

## Supporting info
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14742#issuecomment-1693545973

**Comment by timcosgrove** [comment]
Stretch goal

**Comment by timcosgrove** [comment]
From https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14742#issuecomment-1693545973:

**CMS**
* menu_breadcrumb contrib
  * https://www.drupal.org/project/menu_breadcrumb
  * preprocess functions
* va_gov_help_center
  * hook_preprocess_breadcrumb()
  * removes 'home' for documentation pages
  * not relevant for current effort
* va_gov_lovell
  * BreadcrumbPreprocessEvent
  * BreadcrumbPreprocessEventFactory
  * LovellEventSubscriber
  * manipulates 'both'/'tricare'/'va' elements in lowell breadcrumb chains
* va_gov_workflow_assignments
  * EntityMetaDisplay
  * SectionHierarchyBreadcrumb
  * SectionHierarchyBreadcrumbInterface
  * This is CMS admin/internal; not necessary to engage with for AP needs.

Reading: vamc-facilities-lovell.md

**Comment by schiavo** [comment]
In progress

**Comment by schiavo** [comment]
computed_breadcrumbs seems to do the job out of the box

![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/7717261/a4887817-7651-4ec6-9913-c3c814c906c2)

**Comment by schiavo** [comment]
The [decoupled_kit](https://www.drupal.org/project/decoupled_kit) has a sub module for adding breadcrumbs to json api. When enabled a json path is added to access breadcrumbs. This path can be queried for breadcrumbs associated with a specific path. For example /decoupled_kit/breadcrumb?path=/article/interdico-ludus-saepius-suscipit

![Screenshot-20230905135420-1312x1036](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/7717261/be954540-0af8-4e04-9933-6ef9b0756a34)

**Comment by schiavo** [comment]
Decoupled kit query resulting in breadcrumb

![Screenshot-20230905135738-1028x518](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/7717261/23018e04-9d97-4a3b-a4bc-734ba30ddb9e)

**Comment by schiavo** [comment]
The breadcrumb provided by [decoupled_kit](https://www.drupal.org/project/decoupled_kit) is provided separately from content provided as a part of the json api feed. The resulting breadcrumb does not conform with existing breadcrumb configuration in the system and would have to be configured separately. 

computed_breadcrumb seems like the best solution for our purposed based on it's simplicity and ability to include breadcrumbs with each piece of content in the json feed.

**Comment by schiavo** [comment]
Comparing results in CMS. The feed for this node contains breadcrumbs four layers ddep

![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/7717261/1a0a48e4-0b09-4b9a-b26d-7065e0793256)

it corresponds with what the front end for the node shows.

![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/7717261/cf2a422f-8bf5-4537-ab20-ac836e61126f)

**Comment by schiavo** [comment]
Another comparison

![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/7717261/c97f4389-cc93-46b5-b539-a5f3b2da7a67)

![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/7717261/1c8df60f-a658-4d8f-9f37-1757310c3951)
