### ISSUE TITLE
PAW Research: Draft conversation guide for PAW research

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#14749]
### User story
**AS A** Researcher
**I WANT** to document the details for conducting PAW usability sessions
**SO THAT** the research will achieve the stated goals and answer the research questions

#### Sprint 9X ACs - 5 pt estimate
- [x] Rough-drafted conversation guide, prior to having the full prototypes all done

#### Future ACs
- [x] Conversation guide tested against finished prototypes
- [x] Shared conversation guide with Amanda, Wes (and Alexis) for feedback, and feedback incorporated 
- [x] Share conversation guide with Danielle in final form for review
- [ ] Danielle feedback incorporated for whole conversation guide
- [x] Offered to DaveC for feedback and discussion
- [ ] (Optional by Dave: meet about guide + plan)
- [ ] Received official approval from DaveC (on plan + conversation guide) for research ops

**Comment by cindymerrill** [comment]
@wesrowe I refined this ticket, as you requested

**Comment by cindymerrill** [comment]
Completed first draft of conversation guide: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/pact-act-wizard/research/conversation-guide.md

Next I plan to review it, potentially add more to it, and then share it for feedback.

**Comment by cindymerrill** [comment]
@jilladams Because we're trying to pull in the timeline, I finished the conversation guide and shared it with everyone to review at once. Comments can be left in this Word doc on Sharepoint: https://dvagov-my.sharepoint.com/:w:/r/personal/cynthia_merrill_va_gov/Documents/Public%20Websites/PACT%20Act%20Wizard/Conversation%20Guide%20for%20PACT%20Act%20Wizard%20(q%27s%20%26%20tasks%20only).docx?d=w41a8bd7202e24c39ab9021a5e5857d31&csf=1&web=1&e=y4tjiv

**Comment by wesrowe** [comment]
@cindymerrill, the guide looks good to me. Re the question in there about including the wayfinding task/question... I think we probably won't learn a ton there, but it seems like pretty good contet-setting for the prototype anyway.

**Comment by cindymerrill** [comment]
Moved the review and approval AC's into this [new Research Prep Tasks ticket](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15244), so this ticket can be closed.
