### ISSUE TITLE
Change management for updated Service Location impact on VAMC editors

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#14758]
## Description
VBA Service Location paragraph type will be built based off of existing type used for VAMCs. New VBA fields will be added to the existing Service Location paragraph type. Change management is required with existing VAMC editors when the fields are exposed.

[Figma file for VBA Service Location paragraph type](https://www.figma.com/file/aKdT4weNNthDxb3r6MolEh/VBA-Content-Specs?type=design&node-id=208-714&mode=design&t=LTvuLnielz6wFsoh-0)

[VBA Service Location spreadsheet link](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14890#issuecomment-1791554583)

## Changes
- Walk-ins accepted field going away and Service Delivery Options being added
- Telehealth service will be part of Service Options (currently still exists as a VAMC service that will be redundant)

## Acceptance Criteria
- [x] KB articles are updated
- [x] Change is previewed at December VAMC editor office hours
- [ ] On launch: publish drafts of the 2 KBs & share links with VHA DM 
- [ ] VHA Digital Media lets editors know when the day when the change will go live

**Comment by mmiddaugh** [comment]
Related to change management burden - some audit findings from common health services 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBamNiIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--c5b80a10f4e135f7befa92f49cb320f877721e8d/image.png)

**Comment by xiongjaneg** [comment]
@xiongjaneg 

Potentially
- new or updated KB article
- VHA Media coordination

Need to know if and how these will impact VAMC editors
- UI changes
- impact to existing data

**Comment by xiongjaneg** [comment]
@xiongjaneg walkins CM for VAMC

**Comment by xiongjaneg** [comment]
@xiongjaneg Question about telehealth being removed from service (will be a modality) for VHA DM

**Comment by jilladams** [comment]
Delayed from Sprint 105 to 106 due to Service Location bug bash findings / delayed launch. Staging review is now in Sprint 107 (or whatever the sprint-after-end-of-contract is going to be called), so: removing S106, tagging into that sprint, and I don't think we expect this to move before then. @xiongjaneg let me know if I'm wrong on that.

**Comment by xiongjaneg** [comment]
That's correct, thanks for updating

**Comment by jilladams** [comment]
@davidmpickett to dedupe if the remaining ACs are in the launch plan or recorded elsewhere, and close this if so.

**Comment by davidmpickett** [comment]
Dupe with https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16156
