### ISSUE TITLE
Set up Facilities team front end monitoring 

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#14756]
## Problem Statement
Facilities Team needs to be aware of front end performance issues and customer traffic data

## Acceptance Criteria
- [ ] FE engineers have Sentry accounts
- [ ] Reviewed resources documents for best practices
- [ ] Met with PM to discuss responsibilities

## Resources

[Sentry account instructions](https://depo-platform-documentation.scrollhelp.site/developer-docs/tracking-application-errors-with-sentry)

[Google Analytics/Domo account instructions](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/analytics-customer-support-guide#Analyticscustomersupportguide), particularly for Facility Locator data

[Vet Center Domo data example](https://github.com/department-of-veterans-affairs/va.gov-cms/files/12370505/How.to.view.and.understand.your.Vet.Center.data.docx)

## Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [ ] `Public Websites`
- [x] `Facilities`
- [ ] `User support`
- [ ] `Accelerated Publishing`

**Comment by jilladams** [comment]
This ticket might be closeable in the new world of Datadog.

**Comment by jilladams** [comment]
The only way we could do this in Datadog is re: successful calls to S3. But we don't aggregate data about those calls anywhere (Datadog, Sentry).

But actual monitors related to Google Analytics data probably aren't possible to integrate in Datadog. 
Does GA have its own monitoring available? 
Or would Datadog Realtime User Monitoring be of interest here?
