### ISSUE TITLE
FE: Remove unused content-build Drupal templates

### ISSUE THREAD

**Issue by randimays** [department-of-veterans-affairs/va.gov-cms#14767]
## Description

Slack thread for context: https://dsva.slack.com/archives/C52CL1PKQ/p1691776245384379

These 4 content-build templates:
```
press_releases_page.drupal.liquid
news_stories_page.drupal.liquid
events_page.drupal.liquid
bios_page.drupal.liquid
```

do not have a corresponding Content Type in Drupal. They are not used in the site anymore. We should remove them, and any vestigial utilities, etc. that are used only for these files.

### User story
> _Describe the audience/user, enhancement or fix, and value / outcome desired._

**AS A** VACMS engineer
**I WANT** to remove unused code from our repositories
**SO THAT** our codebase is more maintainable and easier for other engineers to understand

### Quality / testing notes

Testing is not possible.

## Acceptance criteria

- [ ] Performed due diligence to ensure these templates really are unused
  - [ ] Ran template findings and developers past Steve W for memory/insight (events and bios)
- [ ] Removed templates and any related code

**Comment by randimays** [comment]
`src/site/constants/content-modeling.js` Has the mapping between CMS node types and liquid templates.

**Comment by jilladams** [comment]
PR https://github.com/department-of-veterans-affairs/content-build/pull/1699
