### ISSUE TITLE
Identify options for adding Veterans Canteen Service link in Optometry service

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#14785]
## User Story or Problem Statement
As a Veteran needing optometry services, I need to be able to easily find optometry services offered by Veterans Canteen Service near me.

## Description or Additional Context 
Veterans Canteen Service has their own non-Drupal web page. They offer optometry services. It would be helpful to Veterans to be able to access the link to the canteen web page directly from the Optometry health service. This applies across all VAMCs.
- Can the Optometry taxonomy be a link?
- Can the canteen web page link be placed in the centralized service description in a way that would make it obvious to Veterans?

## Acceptance Criteria
- [ ] Testable_Outcome_X
- [ ] Testable_Outcome_Y
- [ ] Testable_Outcome_Z
- [ ] Requires design review
- [ ] Requires accessibility review

**Comment by xiongjaneg** [comment]
Michelle noted in VHA DM sync notes:
Although I’m not able to add the link to VCS RX Eyewear in the national description for Optometry, I’ve identified a few other options…

‌

Editors can add a link to [VCS RX Eyewear](https://vcsrxeyewear.com/) within the system health service description for optometry. This description is displayed in the health service accordion at the system level and for facilities within the system which offer the service. (115 systems have Optometry listed as a health service.)
Once editors have added the link, we can also consider mentioning the benefit in the Veteran-friendly terms displayed in the accordion heading.
I’ve mocked up these ideas in the screenshot below. We’d need to work with the VCS and content teams for the best link and language.
image.png

I also realized there is a [VA vision care page](https://www.va.gov/health-care/about-va-health-benefits/vision-care/). We may be able to advocate for inclusion of the link/mention of the benefit on that page as well.

**Comment by mmiddaugh** [comment]
We were asked to confirm that Veterans hear about VCS benefits at appointments, for consistency of message.  However, Justin learned that Veterans are directed to free vision benefits and services rather than to VCS. As a result, we will not pursue this option. 


‌
