### ISSUE TITLE
Unnest wysiwyg content when processing

### ISSUE THREAD

**Issue by eselkin** [department-of-veterans-affairs/va.gov-cms#14780]
An entity's fieldWysiwyg processed data field is not being unnested from an array leading to conditionals in liquid templates:

1. /src/site/paragraphs/wysiwyg.drupal.liquid
2. /src/site/paragraphs/expandable_text.drupal.liquid 

-- and references to the 0th element in the following templates
1. /src/site/components/informational_alert.drupal.liquid
2. /src/site/layouts/vamc_system_billing_insurance.drupal.liquid

Other templates expect the processed data to be unnested and do not refer to the array position. Not all fieldWysiwyg data is passed through processCentralizedContent as in the expandable_text file.

All utilities that process the entity field data should unnest the fields and all references to fieldWysiwyg in liquid should reference fieldWysiwyg.processed instead of the array element.

**Comment by EWashb** [comment]
@jilladams @xiongjaneg does this belong to facilities? Found this without labels

**Comment by xiongjaneg** [comment]
@EWashb Thanks, I'll tag it Facilities and follow up with Eli.

**Comment by eselkin** [comment]
I was looking for this I started another ticket for this. I'll delete this one after I pull out the content.

**Comment by xiongjaneg** [comment]
closing in favor or #15026
