### ISSUE TITLE
Confirm Medallia implementation on both Lovell - VA and Lovell - Tricare

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#14786]
## User Story or Problem Statement
As a Veteran, I want to be able to provide feedback about my customer experience at Lovell - VA and Lovell - Tricare.

## Description or Additional Context 
Currently, Medallia isn't showing survey data for one or both of Lovell sites. Both sites need to have Medallia snippet implemented and this needs to be confirmed.

## Acceptance Criteria
- [ ] Confirmed Medallia survey is implemented on Lovell - VA
- [ ] Confirmed Medallia survey is implemented on Lovell - Tricare

**Comment by mmiddaugh** [comment]
I see this snippet on [Lovell](https://www.va.gov/lovell-federal-health-care-va/health-services/)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaE1JIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--bc703cd5686bac1573eb6c7bd98f890fd182db8a/image.png)

**Comment by xiongjaneg** [comment]
What is the impact if, for example, a single event - does it get one ID or two? Would there be two separate trackings? This is a risk.

Desired outcome and the reason for the toggle was to compare and contrast the Veteran experience between VA and Tricare.

**Comment by xiongjaneg** [comment]
potential: open a qualitative data request with Analytics, do in parallel with this ticket.

**Comment by eselkin** [comment]
Did we ever get back if Analytics had two codes for VA and TriCare here?

**Comment by xiongjaneg** [comment]
@eselkin We didn't. Let me nudge them. Thank you.

**Comment by xiongjaneg** [comment]
Analytics directed us to Platform's Contact Center for the [qualitative data request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/65178), now submitted.

Analytics also provided a demo of recent stats, screenshot below.
![Lovell alert interaction data](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/73648238/2b528d5c-2a3c-4726-8267-f35dab6de630)

**Comment by eselkin** [comment]
In my investigation, the Feedback buttons do both produce the Medallia feedback box. So the script must be present on both. But whether they are leading to two different results, seems hard or impossible to tell from the code alone. The embedded js (KAMPYLE) shows medallia code in both pages, but trying to discern how it differentiates between pages seems difficult. The code does reference the page URL so it may be that all pages that have the feedback button and embedded js are independently monitored/stored.

**Comment by jilladams** [comment]
@eselkin @xiongjaneg  I'm not certain based on Eli's note how we decide if we're satisfied, or figure out next steps here. The Contact Center team, run by Chante  Lantos-Swett, runs the Feedback button and Medallia integration. Maybe we need to reach out to them for help understanding where the results are piping in? cc @mmiddaugh

**Comment by xiongjaneg** [comment]
@jilladams I'm awaiting Contact Center's response to my request for qualitative analysis. I'll prod them again.

**Comment by xiongjaneg** [comment]
Closing this ticket as Facilities has done our review.

**Comment by xiongjaneg** [comment]
Michelle shared the Tricare scores she found
![Lovell TRICARE experience ratings](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/73648238/489e2494-6c2e-4bec-bcbb-e0a3bfee161b)

**Comment by xiongjaneg** [comment]
Platform Contact Center shared the feedback survey qualitative review. The VA and Tricare pages are getting unique results.
