### ISSUE TITLE
FE: Refactor Discharge Upgrade Wizard accordions to use the web component

### ISSUE THREAD

**Issue by randimays** [department-of-veterans-affairs/va.gov-cms#14796]
## Description
The Discharge Upgrade Wizard application is using an older/custom implementation of accordions. We should be using the [web component](https://design.va.gov/storybook/?path=/docs/components-va-accordion--default) (`va-accordion`) instead.

### User story
**AS A** Veteran
**I WANT** accordion content to be implemented consistently across VA.gov
**SO THAT** all accordions are consistent, accessible and defects are minimized

### Engineering notes / background
We are using a custom implementation of accordions in [InstructionsPage.jsx](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/discharge-wizard/components/InstructionsPage.jsx) and [AdditionalInstructions.jsx](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/discharge-wizard/components/gpMinorComponents/AdditionalInstructions.jsx).

### Quality / testing notes
Relevant unit tests should be updated.

## Acceptance criteria
- [ ] Test `InstructionsPage.jsx` to ensure accordions are working as expected
- [ ] Test `AdditionalInstructions.jsx` to ensure accordions are working as expected
- [ ] Accessibility review

**Comment by chriskim2311** [comment]
Going to close this ticket and address it when we build in the subtask pattern.
