### ISSUE TITLE
FE: Replace custom pagination implementation with va-pagination in content-build

### ISSUE THREAD

**Issue by randimays** [department-of-veterans-affairs/va.gov-cms#14795]
## Description
There is a shared pagination template in `content-build` used by multiple templates. It is an older/custom implementation.

We should be using the `va-pagination` (web component) instead, if possible. [DST guidance](https://design.va.gov/storybook/?path=/docs/components-va-pagination--default)

### User story
**AS A** Veteran
**I WANT** all pagination functionality to be consistently implemented throughout VA.gov
**SO THAT** the functionality is accessible, consistent and defects are minimized

### Engineering notes / background

Several templates in `content-build` utilize [this pagination template](https://github.com/department-of-veterans-affairs/content-build/blob/4dc5b26b912c9c14d0eb43c37e87ca9d297263f3/src/site/includes/pagination.drupal.liquid#L24C48-L24C48):
- support_resources_article_listing

### Quality / testing notes
Need to explore whether we can add unit testing for this (is it possible in CB?)

## Acceptance criteria
- [ ] support_resources_article_listing pagination functionality thoroughly tested
- [ ] support_resources_article_listing pagination tested on mobile
- [ ] Accessibility review

**Comment by jilladams** [comment]
#14767 is complete, removed the lines below from ticket body:
~These templates also use the pagination component, but the templates should be removed by https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14767 as they appear to be unused~.

~If they are not removed by the time this ticket is picked up, we should omit making any fixes to these templates:~
~- bios_page~
~- events_page~
~- news_stories_page~
~- press_releases_page~

**Comment by FranECross** [comment]
@laflannery Please close this when you make the new ticket for V3 component updates. Thanks!

**Comment by laflannery** [comment]
Closing in favor of #16987
