### ISSUE TITLE
BE: Hide the Description field in VA footer menu UIs

### ISSUE THREAD

**Issue by randimays** [department-of-veterans-affairs/va.gov-cms#14793]
## Description
In the [CMS for the VA footer](https://staging.cms.va.gov/admin/structure/menu/item/11510/edit?destination=/admin/structure/menu/manage/footer-bottom-rail) (both columns and bottom rail), the `Description` field is used with help text above that reads `Shown when hovering over the menu link.` This is inaccurate; DSVA does not support using tooltips (link hover behavior) for accessibility reasons.

We should remove or update this text to more accurately reflect what this description field can be used for.

In the case of the VA footer, we will not be relying on this field at all (even though it is filled out for most, if not all of the current footer links). We are updating the footer code to pull the `Title` field instead, which is more accurate.

### User story

**AS A** CMS editor
**I WANT** the Description field to be hidden since it's not used
**SO THAT** I don't mistakenly use it.

### Engineering notes / background

Leverage scaffolding for this approach that we already used on menus driving homepage Hub list.: `docroot/modules/custom/va_gov_home/src/EventSubscriber/FormEventSubscriber.php`

## Acceptance criteria

- [x] Description field is hidden from Drupal footer links menus
  - [x] `VA.gov Footer bottom rail` menu
  - [x] `VA.gov Footer` menu

**Comment by wesrowe** [comment]
This needs "design" on new help text – @thejordanwood or I can probably come up with something once we understand what the Description field is really used for.

**Comment by thejordanwood** [comment]
Since the description field is currently not needed, the team has decided that it's best to hide the field to avoid any confusion. 

[Slack thread](https://dsva.slack.com/archives/C52CL1PKQ/p1692389335705089) where the decision was made.

**Comment by wesrowe** [comment]
Ticket body is updated consistent with decision above. @dsasser @chri5tia, assigned to you for async refinement.

**Comment by chri5tia** [comment]
## Strategy
I plan to create an array of menu link forms by ID and populate it with the footer and bottom rail form IDs. 
This array can be used in the future for other menu forms easily.
I will create a function called `removeMenuLinkDescription()`, not specific to footers so that it can be used by other menus.
The function will use `hook_form_alter()` to remove the Description field before rendering.

**Comment by dsasser** [comment]
> ## Strategy
> I plan to create an array of menu link forms by ID and populate it with the footer and bottom rail form IDs. This array can be used in the future for other menu forms easily. I will create a function called `removeMenuLinkDescription()`, not specific to footers so that it can be used by other menus. The function will use `hook_form_alter()` to remove the Description field before rendering.
> 
> It'll have to be added to the `formAlter()` function that already exists for the `va_gov_home` event subscriber.
> 
> I will leave the field exposed to admins because there is content in the field, in case it needs to be removed. I will change the help text of that field to reflect that it should not be used/that it is deprecated.

Overall this should work fine. I do have some thoughts:

- Create a new module, va_gov_menu (or something similar)
- In that module, create a trait (or service) that any module can use, and add thenew  removeMenuLinkDescription() method to it.
- Move the hubMenuHideAddtributes(), hubMenuHideExpanded(), hubMenuHideViewMode(), and hubMenuHideParentLink() methods from Drupal\va_gov_home\EventSubscriber into the new service/trait.
- In va_gov_menu, add an event subscriber that will respond to the menu IDs (using the array as you suggested)
- Leverage the trait to make the changes to the menus.

**Comment by chri5tia** [comment]
ACs are met. I decided to table the work to make this extendable to other menus for now until it's needed and focus on other work. 
https://github.com/department-of-veterans-affairs/va.gov-cms/compare/main...chri5tia:va.gov-cms:VACMS-14793-Hide-Footer-Description-Field-B-Service

**Comment by chri5tia** [comment]
Not sure what happened but the PR doesn't seem to be attached anymore. This still needs a review: https://github.com/department-of-veterans-affairs/va.gov-cms/pull/15069

**Comment by wesrowe** [comment]
just noticed this one might be languishing – thought I'd call it out so there's not a rush to close.
