### ISSUE TITLE
Homepage: make revision log required on promo blocks (News, Benefit)

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#14800]
### User story

**AS A** PO
**I WANT** promo blocks to require revision log
**SO THAT** we always have a record. 

### Implementation notes 
Adding the block_content base form to EntityEventSubscriber::getSubscribedEvents()

Adding a new method, alterBlockContentForm, that calls requireRevisionMessage()

## Acceptance criteria

- [ ] Revision log required to save News promo block
- [ ] Revision log required to save Benefit promo block

**Comment by jilladams** [comment]
Daniel and Christia to collab, Daniel to push his PR, Christia to own PR shepherding / testing.

**Comment by chri5tia** [comment]
Confirmed in staging.

**Comment by chri5tia** [comment]
Confirmed in prod.
![Screenshot 2023-08-24 at 12 17 11 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/22764938/d9f01c8a-1262-4079-ba49-d23cf4cb36ce)
