### ISSUE TITLE
VAMC "Get Updates..." links should indicate they open in a new tab

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#14809]
## User Story or Problem Statement
Because of the new, updated Design System [external link guidance](https://design.va.gov/content-style-guide/links#linking-to-external-sites), the "Get Updates..." links should be a bit clearer that they will be opening in a new tab, especially the first subscribe link.

## Description or Additional Context 
These links appear at the bottom of each VAMC main page.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdllMIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--4d2dcd61d43ddf1278f57d3d435242be9b334ca7/Screenshot%202023-08-16%20at%209.00.00%20AM.png)

## Acceptance Criteria
- [ ] Testable_Outcome_X
- [ ] Testable_Outcome_Y
- [ ] Testable_Outcome_Z
- [ ] Requires design review
- [ ] Requires accessibility review

**Comment by xiongjaneg** [comment]
There is an existing ticket for CAIA to provide input on VBA Get Updates ticket [ ]. Waiting on that to inform this ticket.

The text themselves are hardcoded but Veterans need to know explicitly these will go to a new tab.

**Comment by xiongjaneg** [comment]
Is there discussion about front end automation to search for these links. There is a subdomain list for considering certain links internal to VA, but it's a huge list.

**Comment by xiongjaneg** [comment]
We may need to do what's right on our end to set us up for success when design system or content (systemic) decisions are made.

**Comment by laflannery** [comment]
Closing because it is no longer applicable:
1. not only should these not open in a new tab anymore but
2. we have stopped them from opening in a new tab in the [Facility component ticket](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17654)
