### ISSUE TITLE
Implement Vet Center Notification email

### ISSUE THREAD

**Issue by davidmpickett** [department-of-veterans-affairs/va.gov-cms#14816]
## User Story or Problem Statement
Once the new content for the email is drafted and approved, it will need to be added to the email template.

## Description or Additional Context 
**Approved email content:**

> Subject line: [ACTION REQUIRED] Vet Center Website Content Review
> 
> VA Directive 6102 requires that VA content is reviewed yearly to ensure information is still relevant. RCS recommends a minimum quarterly review as a best practice. All content will need to be reviewed, and outdated content will need to be edited to remain compliant with VA Directive 6102. [Learn more about VA Directive 6102.](https://prod.cms.va.gov/help/va-directive-6102)
> 
> ---
> 
> To assist with getting your content compliant, we are sending you this monthly reminder to log into Drupal, review and update your website content, and attest that your content is up-to-date. 
> 
> Reviewing your website top to bottom at least quarterly will help you to maintain updated and accurate location and service information and keep the website compliant with VA Directive 6102. For more information, you can read this Knowledge Base article `<link pending>` for tips and best practices to manage compliance. 

> Need help?

> 
> · If you are a Vet Center Director or Outreach Specialist who needs assistance accessing Drupal CMS, please email the CMS Support Team at support@va.gov.atlassian.net.
> 
> · If you want to refresh your skills, need ideas, or have questions about creating content for your webpages, you can find How to Guides and Training videos in the [Drupal CMS Knowledge Base](https://prod.cms.va.gov/help/vet-centers) or drop in during office hours.
> 
> · If you received this email and no longer have a role at a Vet Center, please inform us by emailing the CMS Support Team at [support@va.gov.atlassian.net](support@va.gov.atlassian.net).
> 
> Please note that before the end of the calendar year a formal suspense will be sent to ensure 100 percent compliance. We encourage you to make use of the resources and tools available before then to ensure your success and the success of information delivery on your page!
> 

## Acceptance Criteria
- [x] Approved email content is added to the message stack template (not hardcoded)
- [x]  A Vet Center equivalent of VAMC drush php-eval "print_r(\Drupal::service('va_gov_notifications.outdated_content')->checkForOutdatedVamcContent());" is created

**Comment by xiongjaneg** [comment]
Complexity depends on content of email and whether there's placeholder content other than a name. The email uses the existing VAMC email.

**Comment by xiongjaneg** [comment]
Michelle in collaboration with Vet Center national office to develop content.

**Comment by xiongjaneg** [comment]
@xiongjaneg to discuss with Steve and Christian at pre-finement.

**Comment by xiongjaneg** [comment]
Get Steve's brain into this ticket in next Drupal pre-refinement

**Comment by xiongjaneg** [comment]
Steve created a ticket for CMS Team for documenting underlying code and use of outdated content. Facilities is not blocked by CMS Team work.

**Comment by mmiddaugh** [comment]
Approved email content added into description above.

**Comment by mmiddaugh** [comment]
I also have the KB article and will provide a link as soon as available

**Comment by xiongjaneg** [comment]
The template exists but doesn't have content yet.

**Comment by xiongjaneg** [comment]
The current VAMC model is that only editors who have outdated data get the notification. The Vet Center approach is that all Vet Center editors will get the monthly notification.

**Comment by jilladams** [comment]
From planning: 
* VAMC email uses a table, has a lot of inline styles. A11y may be a concern.
* Alternatives may be to remove formatting and make the email less beautiful, in order to be more accessible. However: the tradeoff is probably testing burden across email clients to ensure presentation makes sense. 
   * Except: all VA uses Outlook. (All on 365? GFE phones?)
* Deadline is the priority and needs to drive decisions.

**Comment by xiongjaneg** [comment]
GFE phone prevalence question to be asked at VHA DM sync

**Comment by xiongjaneg** [comment]
Some research is needed about the a11y review and concerns with the VAMC template and whether to update for Vet Centers. Limit this research if it goes too long.

**Comment by jilladams** [comment]
@xiongjaneg I missed VHA DM sync today - did the GFE use question come up?

**Comment by xiongjaneg** [comment]
@jilladams Yes, VHA DM says they're confident nearly all VAMC public affairs officers have a GFE phone in addition to GFE laptop.

**Comment by swirtSJW** [comment]
@mmiddaugh I am double checking the wording on this 

> Please note that before the end of the calendar year a formal **suspense** will be sent to ensure 100 percent compliance. We encourage you to make use of the resources and tools available before then to ensure your success and the success of information delivery on your page!

Is suspense the right word?

**Comment by swirtSJW** [comment]
I have the PR working for Vet Centers.  Documentation is updated.  Waiting on inter team discussion.

**Comment by swirtSJW** [comment]
List of unwritten ACs that I took care of including two existing bugs we didn't know about.
### Primary changes

1. Refactor Vet Center to use content templates
2. Refactor layout to make accessible at zoom other than 100%. Makes it mobile friendly.
3. Refactor to make it easier to add other products.
4. Refactor to allow different subjects by product.
5. Add the ability to test with a subset of editors.
6. Add extensive documentation for future products and other teams.
7. Bugfix: Digging for outdated content gave up if the first one it tried had none.  This made it possible that some editors are not receiving notifications if their first qualifying section was up-to-date or was a section that was outside the product. 
8. Bugfix: Banner image not pathed in all environments.  Not everyone could see it.

**Comment by swirtSJW** [comment]
Related discussions from Slack:
- [Pattern source](https://dsva.slack.com/archives/CT4GZBM8F/p1694633648502849)
- [scalable layout](https://dsva.slack.com/archives/C0FQSS30V/p1694703138745819)

**Comment by swirtSJW** [comment]
Helpful references:
https://www.goodemailcode.com/email-enhancements/mso-styles.html#mso-table-styles

**Comment by swirtSJW** [comment]
This has gone out and been tested on prod with the 12 users who agreed to test it.  So far reports are favorable.

@xiongjaneg  I did check and confirm that the email for VAMC and now Vet Centers do get queued up at ~3:30 AM on the 1st of the month
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5752113/4db8c3a6-4f7a-46fa-9dc9-d7a1d4bdd06d)

Cron then processes each email.  Due to rate limiting, that takes 10-30 minutes to send all the email in the queues.

**Comment by swirtSJW** [comment]
@mmiddaugh @EWashb @xiongjaneg  @BerniXiongA6  and @jilladams On previous runs of the VAMC outdated content blast it was only sending ~270 VAMC notifications to editors.  
Due to this bug that I found while I was working on this:

> Bugfix: Digging for outdated content gave up if the first one it tried had none. This made it possible that some editors are not receiving notifications if their first qualifying section was up-to-date or was a section that was outside the product.

Now that the bug is resolved it will send on the 1st of the month, ~550 VAMC notifications  So there are going to be a lot of editors who are receiving notifications that have never received them before.

**Comment by xiongjaneg** [comment]
@BerniXiongA6 Heads up for support staff. @mmiddaugh Adding to VHA DM sync agenda

**Comment by xiongjaneg** [comment]
@swirtSJW To verify, has the bug been present since VAMC notifications started? And looking forward, is there a way to detect this other than your stumbling on the bug?

**Comment by swirtSJW** [comment]
No I fixed the bug in my PR.  But in auditing the numbers just now, I found another existing bug
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15367

**Comment by swirtSJW** [comment]
Bahhh!  Disregard my ramblings about mailing blocked users.   It only happens on local because part of our database copy process enables ALL the users.  So the 550 count was coming from my local.  When run on prod it will be closer to the 370.
