### ISSUE TITLE
BE: Magichead: Keep dotted left borders consistent when toggling row weights on/off

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#14817]
**FE consult/pairing/exploration expected during development**

### User story

**AS A** Content Editor
**I WANT** the number of dotted borders at the left to correspond to the heading depth, even when toggling row weights on/off
**SO THAT** I can feel confident depths are what I think they are.

### Engineering notes / background

Jordan's [original Figma for this UI](https://www.figma.com/file/0gH9R0yAadciGcy73vpsgX/Magic-Headers-and-Paragraphs?type=design&node-id=0-1&mode=design&t=cDhSOeSazsU7xrQ9-0)

show-row-weights version: note that the top level (depth 0) sections don't have a dotted line:
<img width="599" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/4054752/487165ec-9b67-4c45-839e-73978b362ea7">

drag-and-drop version: note that an extra dotted line is there for all sections.
<img width="637" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/4054752/091e3dca-5560-495b-a2f7-06ecc2565efb">

## Acceptance criteria

- [ ] In show-row-weights mode, no dotted border is present for a Section with depth 0
  - (this is the current state before this ticket) 
- [ ] In drag-and-drop mode, a Section with depth 0 has no dotted border added at left
- [ ] Reviewed with Design, considered original Figma (linked above)
- [ ] Iterated on Design feedback
- [ ] PM review

**Comment by wesrowe** [comment]
This is ready for pre-refinement by @dsasser and @chri5tia

**Comment by wesrowe** [comment]
In Tugboat, I see you managed to make the number of dotted borders _consistent_ between the two modes (drag-drop and show-weights). I'm wondering if you can more precisely match the AC, which asks for the number of dotted lines to correspond to the depth? here's what I have for three depth-zero sections, note that they have single dotted lines to the left:

**drag-drop mode**
<img width="92" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/4054752/5ed5c61c-c437-4881-9f17-fbc56d15c2a8">

**show-row-weights mode**
<img width="87" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/4054752/576f2775-3024-4baa-9946-71245f0c46cc">

The other thing I want to note about the screen shots – the dotted borders around the asterisks are very confusing. Those appear after I have dragged a section. But they create so much distraction that the left borders, the ones that actually matter, are hard to notice or understand. Here's another example:
<img width="586" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/4054752/804a2409-7db5-4ee1-b0b5-bd30d4437973">
- Sections 1 and 2 (counting from top) are at the same depth; but the dotted line to the right of the asterisk really gives a visual impression that 2 is indented from 1.

Can we lose those dotted lines completely, so that dotted borders only mean depth?

cc @thejordanwood

**Comment by chri5tia** [comment]
Updated the draft PR to:
- remove accidental commits for a different project
- make the line darker according to design system, make it solid for kicks
- ensure that it's only applied to the magichead field widget and not all over where tabledrop is used

**Comment by chri5tia** [comment]
The PR is ready for review.

**Comment by wesrowe** [comment]
Nice work – it looks a lot better to me now. Can close from my perspective.

**Comment by jilladams** [comment]
PR still open - I added a couple reviewers.
