### ISSUE TITLE
Design: Magichead help text and labels in View and Edit modes

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#14815]
### User story

**AS A** Content Editor
**I WANT** magichead UI to be more intuitive and consistent to use
**SO THAT** I can create structured content with the least cognitive load possible.

### Design notes / background

[Figma design file](https://www.figma.com/file/0gH9R0yAadciGcy73vpsgX/Magic-Headers-and-Paragraphs?type=design&node-id=0%3A1&mode=design&t=FTx7ml9io6TJXtQq-1)

**Edit screen recommendations:**
- Improve help text for visibility, clarity, and readability
  - Break up the important points into separate bullets
  - Consider visual diagrams like the CLP UI
- Topics to explain in help text:
  - Left-right dragging and its quirks
    - Use of “show row weights” to reveal depth
    - Meaning of “depth” and fact that it starts at zero
    - Tell user what the max depth value is (this can be dynamically populated by the actual max-depth setting)
- Require Section heading 
- Rename “Section description” to something that sounds more like it is content, e.g. “Section content”

**View screen recommendations:**
- Change Drupal’s “outlining” numbers to bullets (unordered list)
-Clarify what is a Section heading and what is the Section description - currently, Heading is labeled but Description is not
  - Bold headings
  - It's possible that removing “section heading” label is clearer than adding a label to the Description content (?)
  - Needs a11y input to make sure that our chosen style/label approach has an adequate a semantic distinction btw heading and description for screen readers
  
## Acceptance criteria

- [x] Drafted design [in Figma file](https://www.figma.com/file/0gH9R0yAadciGcy73vpsgX/Magic-Headers-and-Paragraphs?type=design&node-id=0%3A1&mode=design&t=FTx7ml9io6TJXtQq-1)
- [x] Engineer review for feasibility
- [x] A11y reviewed
- [ ] PM reviewed
- [ ] Iterated design based on feedback
- [ ] Updated implementation ticket #14860 with design link and any relevant notes

**Comment by wesrowe** [comment]
@thejordanwood, as a next step from the magichead hallway test findings, I would like to assign this to you for pre-refinement. I copied in the findings from the [google doc](https://docs.google.com/document/d/1W3dB1vZnWzTmxInJ1be0S_94kAcv6yDBwTFREMhHDBM/edit?usp=sharing), which I should definitely get into github somehow.

Obvious ticket needs, but you might think of more:
- add context, links to existing designs you would be modifying, etc
- write ACs around the designs/artifacts you would expect to generate

Thanks in advance.

**Comment by wesrowe** [comment]
@thejordanwood, note that @dsasser studied some of the challenges editors faced in hallway tests and documented his findings in #14532 ([comment](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14532#issuecomment-1698041570)).

Here are his suggestions to Editors to get themselves unstuck, and could be included in help text: 

> Bail out Solutions
> - Ensure you can see the entire tree when dragging if possible: make window taller; zoom out on browser; save and revisit with collapsed view.
> - Move an item above, or below to "unstick" things.
> - Use accessibility mode (show row weights) to force depth/order.

Also note: we have a ticket for introducing a collapse button during Edit mode: #14534. If you want to add that functionality into your design I think that might be a good idea.

**Comment by thejordanwood** [comment]
@wesrowe Here's the copy I've created for the Eligibility overview sections. 

> Use headings and optional paragraph content to group the eligibility information into logical sections. Sections can be organized into a hierarchy that you can control using section depth. This is what to know about section depth:
> 
> - The drag and drop feature that moves each section to the left and right controls section depth.
> - Section depth starts at 0 and goes up to 2.
> - Show row weights can be used to reveal section depth.

A couple of notes and questions I have here:

1. Is the statement, "Section depth starts at 0 and goes up to 2" correct? I'm confused about the line "this can be dynamically populated by the actual max-depth setting" in the ticket body. 
2. I want to caution us from tying to explain quirks of the system in help text because this text is already very long . 
3. @chri5tia Since this help text is getting rather long, I'm wondering if there's a component in Drupal similar to the [additional info component ](https://design.va.gov/components/additional-info)the VA design system has where we'll be able to store some information.

**Comment by thejordanwood** [comment]
**Changes to view screen:**

- Changed Drupal’s “outlining” numbers to bullets (unordered list)
- Removed section heading label and bolded heading text to clear up confusion between the heading and description.

**Comment by wesrowe** [comment]
I love Jordan's question about an expandable help-text component!

>Is the statement, "Section depth starts at 0 and goes up to 2" correct? I'm confused about the line "this can be dynamically populated by the actual max-depth setting" in the ticket body.

@thejordanwood, that's an implementation question that should be raised later. I don't have a handle on whether help text will be reused across content types or not.

**Comment by thejordanwood** [comment]
**Changes to edit screen:**

- Revised help text
- Added additional info component that we use on the alternative text field
- Section heading is required
- “Section description” was renamed to “Section content”
- Added a collapse button in edit mode

All of these changes are shown in [the Figma file](https://www.figma.com/file/0gH9R0yAadciGcy73vpsgX/Magic-Headers-and-Paragraphs?type=design&node-id=0%3A1&mode=design&t=zVTh4MY0RiUm9gGW-1).

**Comment by dsasser** [comment]
Feedback from an engineering perspective:

✅  Revised help text

❓ Added additional info component that we use on the alternative text field
I'm not seeing this in Figma. Can you point me to where this change is?

✅  Section heading is required

✅  “Section description” was renamed to “Section content”

✅  Added a collapse button in edit mode
Doable, but difficult (5-8 points). We can leverage the existing paradigm where we see this on other fields, but we need to make modifications in order for it to work with magichead.

**Comment by laflannery** [comment]
Accessibility feedback:

The expanded help text could be more plain text. Would the below updates make sense?
- Make sure you can see all the sections when you use the drag and drop feature. 
- Use "Show row weights" to show the section depth values. (We should indicate that Show row weights in the name of an action in some way)

Everything else looks good to me

**Comment by thejordanwood** [comment]
Thanks @laflannery and @dsasser! 

@laflannery I've updated the help text with your suggestions.

**Comment by thejordanwood** [comment]
@dsasser has confirmed that the additional info component should be doable for this. ([Slack thread](https://dsva.slack.com/archives/C52CL1PKQ/p1694447645709499))

@wesrowe This is ready for your review.

**Comment by wesrowe** [comment]
Looks good to me, in that it achieves the requested input. It's a little out of sync from the MVP on the "tree lines", but that's not the topic of this issue.

Closing.
