### ISSUE TITLE
Spike: Vision formation and Workshopping

### ISSUE THREAD

**Issue by productmike** [department-of-veterans-affairs/va.gov-cms#14811]
## User Story or Problem Statement
As the CMS team, I need to (re)define the vision forward, so that I can identify all the things that worked for past team/vision iterations but are becoming hurdles to reaching success for the next iteration.

## Acceptance Criteria
- [x] Team drafts initial charter to be used to communicate our path forward to us, our clients and others.
- [x] Team produces a brainstorming artifact of things that are negatively or positively impacting the team, either team-wide and discipline-specific.
- [x] Team drafts initial hypothesis OR identifies hurdles to clear prior.

**Comment by BerniXiongA6** [comment]
Hey @productmike -- For my sprint planning calculator, I sized this spike ticket as 44 points: 9 team members at 4 pts each for participating, and 1 team member (Jo) at 8 pts for facilitating and planning.

**Comment by productmike** [comment]
Closing as completed
