### ISSUE TITLE
Pagination for Story Listing pages

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#14824]
## Requirements
As a reader of VA.gov, I want the list of News Stories on a Story Listing page to be manageable, so that I can more easily understand what stories are available. 

```[tasklist]
### Acceptance Criteria
- [ ] Story Listing pages uses the VA Design System pagination component
```

## Description or Additional Context 
Story Listing pages on va.gov list 10 stories per page, with a pagination component to navigate them:
> <img width="1053" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/203623/27e8a529-ee3d-4c11-8be4-2860ec55bbf8">

The component is a VA Design system component: https://design.va.gov/storybook/?path=/docs/components-va-pagination--default

Most of the work is figuring out how to build 'pages' here. Content Build generates a static listing page per 10 stories. It may make sense to include all data in-page and paginate 'live', rather than building multiple static pages for the listing. 

Whatever approach is taken, users should be able to navigate to a specific page. IOW, even if we do end up building a single page with all data and display it paginated, users should still be able to copy and paste a link to the 3rd page, say. 

JSON:API has mechanisms for making paginated queries; Next Build may also have some provisions for working with paginated queries or at least examples in the examples directory to look it.

Pagination documentation from Vercel: https://vercel.com/templates/next.js/pagination-with-ssg

#14829 almost certainly wants to be done together with this.

## Team
Please check the team(s) that will do this work.

- [ ] CMS Team
- [ ] Public Websites
- [ ] Facilities
- [ ] User support
- [x] Accelerated Publishing

**Comment by ryguyk** [comment]
I think we likely need to add some of the initial AC's back (e.g. deep links). We won't necessarily get deep linking just by using the design-system web component. We _can_ get it, but it's not automatic.

Let's consider some examples. First, let's lay out the two general paths forward for implementing paging (on listing pages).



In the first path,

**Comment by ryguyk** [comment]
I think we likely need to add some of the initial AC's back (e.g. deep links). We won't necessarily get deep linking just by using the design-system web component. We _can_ get it, but it's not automatic.

**Comment by tjheffner** [comment]
Thanks. I am heavily leaning towards path 1, investigating that currently. 

To split a single path into multiple paths is not a super hard problem for pagination. There are some straightforward examples from vercel & next-drupal, they may need a little bit of finesse/some updates to how we are using our magic `[[...slug]]` route.

https://pagination-with-ssg.vercel.app/
https://github.com/chapter-three/next-drupal/blob/main/examples/example-search-api/pages/api/search/paginated.ts

JSON:API will give us the paginated deeplinks as part of the response by default, if we pass `deserialize: false` . I'll try and have a PR up in the next day or two that maybe clears up what I mean / will confirm if path 1 is a viable option for us.

**Comment by tjheffner** [comment]
https://github.com/department-of-veterans-affairs/next-build/pull/155
