### ISSUE TITLE
Story listings should be sorted newest first

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#14829]
## Description or Additional Context 
Stories on listing pages are currently showing oldest first. This should be reversed. 

```[tasklist]
### Acceptance Criteria
- [ ] Stories on story listing pages are shown newest first.
```

**Comment by timcosgrove** [comment]
If it makes sense to do this with the pagination work, it can be combined.

**Comment by tjheffner** [comment]
https://github.com/department-of-veterans-affairs/next-build/pull/155
