### ISSUE TITLE
SPIKE: Proposed path for VAMC Facility Service appointment information migrating into updated Service Location

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#14837]
## Description or Additional Context 
Automatic migration that duplicates all information in a VAMC Facility Health Service into all of its service locations is technically possible but there would need to be some level of human validation after it is pushed.

Currently, these are single check boxes that aren't required and may not be used.

Considerations for the proposed path:

- What is the mapping of current fields to new fields (e.g., Walk-ins available field is currently boolean but might not be boolean in new modality)?
- What changes need to be considered before technical implementation and will need change management with editors to validate?
- Quantify the number of potential edge cases, such as how many services have multiple service locations.

[Figma file Service Location paragraph type](https://www.figma.com/file/aKdT4weNNthDxb3r6MolEh/VBA-Content-Specs?type=design&node-id=208-714&mode=design&t=LTvuLnielz6wFsoh-0)

## Working document
https://app.mural.co/t/departmentofveteransaffairs9999/m/vagov6717/1677277602711/74cecb64b6eeb9558aa868240cd726b54fcb93a7?sender=u9c899abc4fe36c9a698b1647

## Acceptance Criteria
- [x] There is a map of current fields to new fields.
- [x] Potential edge cases are identified and quantified.
- [x] Spec is generated, or ticketed to generate
- [x] Change management considerations are documented and subsequent tickets proposed.
- [x] Proposed path review is scheduled with PO/PM.

**Comment by xiongjaneg** [comment]
This ticket may be blocking the front end work for VBA RO MVP. It does not block VBA editor entry (may need to migrate at a later time).

**Comment by swirtSJW** [comment]
These are the effected instances
https://staging.cms.va.gov/admin/reports/content-model/fields?field_name=service_location&field_type=&entity_type=&bundle=&label=
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5752113/4611032b-cdb8-453e-9d11-70be0a8ec597)

**Comment by xiongjaneg** [comment]
For VBA could we merge our new service locations or will VAMCs see them? Yes, this would affect what VAMC editors see (they would see it in two places), so the migration has to be done with the fieldset.

**Comment by xiongjaneg** [comment]
3 pts

**Comment by omahane** [comment]
This ticket needs to account for the Appointments data structure, too, per https://dsva.slack.com/archives/C0FQSS30V/p1696862928259969?thread_ts=1696625019.046019&cid=C0FQSS30V

**Comment by jilladams** [comment]
Could be affected by #15649

**Comment by davidmpickett** [comment]
@jilladams @xiongjaneg Mid-sprint note that this is not likely to finish this sprint given work I have left on other tickets that are in-flight. We said this would be stretch during Sprint planning, but just confirming that it's definitely stretch

**Comment by davidmpickett** [comment]
New issue template for adding a term to taxonomy https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/.github/ISSUE_TEMPLATE/taxonomy-add-term.yml

**Comment by davidmpickett** [comment]
First pass https://app.mural.co/t/departmentofveteransaffairs9999/m/vagov6717/1677277602711/74cecb64b6eeb9558aa868240cd726b54fcb93a7?wid=0-1699298698525

**Comment by davidmpickett** [comment]
VAMC Facility Health Service Fields

Label | Machine Name | Field Type 
-- | -- | -- 
Appointment intro text | field_hservice_appt_intro_select | List (text) 
Appointment lead-in default | field_hservices_lead_in_default | Markup
Appointment lead-in text | field_hservice_appt_leadin | Text (plain, long)
Appointments help text | field_appointments_help_text | Markup
Are walkins accepted? | field_walk_ins_accepted | List (text)
Enforce unique combo | field_enforce_unique_combo | Allow Only One
Facility | field_facility_location | Entity reference 
Is a referral required? | field_referral_required | List (text)
Is online scheduling available for this service? | field_online_scheduling_availabl | List (text)
Last Saved by an Editor | field_last_saved_by_an_editor | Timestamp 
Phone number for appointments | field_phone_numbers_paragraph | Entity reference revisions 
Section | field_administration | Entity reference
Service locations | field_service_location | Entity reference revisions 
Service locations help text | field_facility_service_loc_help | Markup 
VAMC system health service | field_regional_health_service | Entity reference

**Comment by swirtSJW** [comment]
Great chart @davidmpickett   Very helpful.

On the fields to be migrated, we are likely going to have to make the assumption that whatever the value is on the node, it has to be repeated across all service locations on the node.

**Comment by omahane** [comment]
We have a couple fields:
- Are walk-ins accepted?
- Is a referral required?

That have an "unspecified" option. I don't know how many actually have that as the value, but if any do, how should we map that?

**Comment by davidmpickett** [comment]
I just mocked up a new Appointments section within @thejordanwood's existing [Service Location Paragraph Type Figma page](https://www.figma.com/file/aKdT4weNNthDxb3r6MolEh/VBA-Content-Specs?type=design&node-id=208-714&mode=design). In order to not mess up the positioning of all the existing feedback, I added this off to the side.

![Appointments proposal](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/6af240cb-a8e3-40d5-8338-961fb29553a7)

**Comment by davidmpickett** [comment]
Rough draft of new fields to add to Service Location paragraph type in the Appointment fieldset

Label | Machine Name | Field Type | Values
-- | -- | -- | --
Appointment intro text | field_service_apt_intro_select | List (text) | default_intro_text = Use default text custom_intro_text = Customize text no_intro_text = Remove text
Appointments help text | field_appointments_help_text | Markup | TBD by UX
Appointment intro text default | field_service_apt_intro_default | Markup | ❓Bifurcate? VBA vs VAMC? Or remove?
Appointment intro text field | field_hservice_appt_leadin | Text (plain, long) | 200 character limit
Is a medical referral required before making an appointment? | field_referral_required | List (text) | 1 = Yes / 0 = No / not_applicable = Unspecified
Is online scheduling available for this service? | field_online_scheduling_availabl | List (text) | 1 = Yes / 0 = No  / not_applicable = Unspecified
Phone number for appointments | field_phone_numbers_paragraph | Entity reference revisions | Phone number paragraph type


Question to @swirtSJW @omahane is there anyway to have an option in a select list be a valid option in the database, but prevent editors from selecting it? Trying to think through if there's anyway to migrate the list data for the referral and scheduling options, but also force editors to actually pick yes or no the next time they edit their facility service (which should happen at least once a year). That's probably outta scope for now, but would be good to have a stub to reflect that eventual goal/intention

**Comment by davidmpickett** [comment]
One of the trickier bits of the data migration is how we handle the "Are walkins accepted?" field. Unlike other fields, there's not a one-to-one correspondence here. I spun up a new piece of the mural to reflect that: https://app.mural.co/t/departmentofveteransaffairs9999/m/vagov6717/1677277602711/74cecb64b6eeb9558aa868240cd726b54fcb93a7?wid=0-1699331298373

**Comment by davidmpickett** [comment]
**Other tickets that may need to be created**
- How/when will VAMC FE queries be updated to use new fields? Does that need a separate ticket from #15559?
- How/when will VAMC FE templates be updated? Same as ticket above? Overlap with VBA templates
  - Minimum update needs to account for Walk-ins accepted going away and Service Delivery Options being added
  - Are we making other changes here to match the VBA design (i.e. order of fields, box around each service location, etc.)
- How and when are we deprecating the Telehealth service now that it will be part of Service Options

**Comment by xiongjaneg** [comment]
@davidmpickett Let's discuss these tickets at our 1:1

**Comment by swirtSJW** [comment]
> Question to @swirtSJW @omahane is there anyway to have an option in a select list be a valid option in the database, but prevent editors from selecting it? Trying to think through if there's anyway to migrate the list data for the referral and scheduling options, but also force editors to actually pick yes or no the next time they edit their facility service (which should happen at least once a year). That's probably outta scope for now, but would be good to have a stub to reflect that eventual goal/intention

@davidmpickett Yes we can do that.  It is essentially the same thing the "winnower"(s) does.   It creates tech debt, but if it must be done, we can do it.  It is all a javascript bit.

**Comment by davidmpickett** [comment]
> > Question to @swirtSJW @omahane is there anyway to have an option in a select list be a valid option in the database, but prevent editors from selecting it? Trying to think through if there's anyway to migrate the list data for the referral and scheduling options, but also force editors to actually pick yes or no the next time they edit their facility service (which should happen at least once a year). That's probably outta scope for now, but would be good to have a stub to reflect that eventual goal/intention
> 
> @davidmpickett Yes we can do that. It is essentially the same thing the "winnower"(s) does. It creates tech debt, but if it must be done, we can do it. It is all a javascript bit.

I'm not saying that's the best solution. But just trying to think of ways to we can start to reduce the data/content debt of having some key fields having a meaningless option that was meant as a stopgap.

**Comment by davidmpickett** [comment]
This will be reviewed with Product at UX sync on Thursday

**Comment by xiongjaneg** [comment]
closing as last AC is completed (scheduled for Nov. 9)

**Comment by xiongjaneg** [comment]
@xiongjaneg check for ticket for walkins CM for VAMC
