### ISSUE TITLE
"On this page" component no longer has links underneath it

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#14839]
## Describe the defect
Within Drupal, there are certain content types where the editor can choose to add a Table of Content to their page. This automatically adds the ["On this page" component](https://design.va.gov/components/on-this-page) generated by all the H2s on the page. Each link would be an anchor link down to the corresponding heading further down the page.

However, this component is not building properly on the front end and instead just has the "On the page" heading with no links underneath. We believe this is a result of a [previous update where IDs were removed from headings](https://github.com/department-of-veterans-affairs/content-build/pull/1660)

## To Reproduce
1. Go to a page using this component, for example [this one](https://www.va.gov/resources/the-pact-act-and-your-va-benefits/)
2. Scroll down to see the "On this page" header
3. Notice that there are no links under this header

## AC / Expected behavior

- [x] All H2s should automatically be included within the On this page component
- [x] Each link should correctly jump down to the appropriate heading further down the page when activated
- [x] testing is added to alert for this failure if it reappears.

## Screenshots
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/106678594/bfd05b68-bfdb-4863-97a9-e147133ef589)

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [x] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`
- [ ] `Accelerated Publishing`

**Comment by randimays** [comment]
Related Slack thread: https://dsva.slack.com/archives/CDHBKAL9W/p1692292106699339

Both issues are fixed as of the production deploy yesterday.
