### ISSUE TITLE
PDF Audit Not Working | Discovery and LOE?

### ISSUE THREAD

**Issue by productmike** [department-of-veterans-affairs/va.gov-cms#14836]
## Describe the defect
VHA DM is reporting that the PDF audit isn’t pulling up for them. They get a blank screen when they click into it on the CMS.

User: justin.warren@va.gov

## To Reproduce
1. Log into CMS
2. Go to 'Content' drop down
2. Click on 'Media'
3. Scroll down to 'PDFs'

## AC / Expected behavior
PDF audit should load. 

## Screenshots
![image.png](https://images.zenhubusercontent.com/64219c54ac9f88715a2c9e5a/b735de6e-8d82-4e33-a11a-acccb1d03c80)

 ## Additional context

1. Only asking for LOE to fix unless on the order of a few minutes.
2. Does this occur for others? (manually entered vs non)

## Desktop (please complete the following information if relevant, or delete)
**UNKNOWN**

**Comment by productmike** [comment]
@edmund-dunn Can you take a quick peek on what's going on here between D10 items? Not asking for a fix; just enough to determine what's happening unless it gets too convoluted and needs prioritization.

cc: @BerniXiongA6 @EWashb

**Comment by productmike** [comment]
@EWashb See the below from @edmund-dunn: "I checked if I can access it and I can, i logged into staging as him and can access it. Right now the only people over there that can access it are Jennifer.Heiland-luedtke@va.gov, Blake.Scates@va.gov and Justin.Warren@va.gov."

Any chance we can ask Justin if he's still having issues? Or I can tomorrow as well...


cc: @BerniXiongA6

**Comment by EWashb** [comment]
@productmike you can check with Justin. Chances are that you'll get to it before I am able.

**Comment by productmike** [comment]
@edmund-dunn Looks like Justin is still not able to view the PDF audit report. Here's the latest from him: 

> See below for screenshots of what I see when I access the audit reports. For some reason PDFs comes up blank for me (I just logged in 10 minutes ago and used both edge and chrome when logging in) but images and table does not.
> 
>  
> 
> The enhancements are not urgent requests but if there are any quick wins, it is greatly appreciated. Right now I just need to be able to see the PDF audit.
> 
>  
> 
> Screenshot of PDFs audit
> [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBakEyIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--d4cef77430210ff39cd18c0457126e8bfc4c4f8e/image001.png)
> 
> 
> 
>  
> 
>  
> 
> Screenshot of images audit
> [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaTgyIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--09152abe471a5e0652db9e4c8606576716268022/image002.png)
> 
>  
> 
> 
> 
>  
> 
>  
> 
> Screenshots of table audit
> [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaTAyIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--14c1aef7ca7fa08591cf339cecce3cbf666249ff/image003.png)
> 
>  
>

**Comment by productmike** [comment]
@edmund-dunn FYI, Justin confirmed that Blake cannot access either. Pulling in some times that might work for him to do a live zoom to do troubleshooting.

**Comment by productmike** [comment]
Re: meeting with Justin yesterday, we believe it was a caching issue as it began working for him just as we jumped on the call. He is confirming with Blake as well, so closing this ticket until/if the issue rises again.

**Comment by productmike** [comment]
@edmund-dunn Reopening based on feedback from Justin yesterday that the report was again not loading.Would like to have a session of troubleshooting with him before jumping into potential solutions.

**Comment by edmund-dunn** [comment]
Closing this, Work is being on in #15136.
