### ISSUE TITLE
TIC intercepts of api push should put item back in queue

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#14847]
## User Story or Problem Statement
With the code that is about to go out for service push, we are logging TIC intercepts, but the items intercepted are still getting removed from the queue.
In the event of a TIC intercept, the item should be put back in the queue. (because post_api module already removed it )

## Acceptance Criteria
- [x] When the TIC returns a misleading 200 response the item should be put back in the queue.
- [x] MD documentation is updated.

## Team
Please check the team(s) that will do this work.

- [ ] CMS Team
- [ ] Public Websites
- [x] Facilities
- [ ] User support
- [ ] Accelerated Publishing

**Comment by omahane** [comment]
@swirtSJW Do we want to keep the logging in, too, and add the item back to the queue or only add the item back to the queue?

**Comment by swirtSJW** [comment]
good question.  I think we want to keep the logging.   We want to know if it is happening.  Also I think this is not something that will resolve itself.  If the tic is accidentally intercepting it is going to keep doing it until we put in a request to fix it.  So the logging will keep us in formed.
