### ISSUE TITLE
I.L. FE: Links on Results screen open in new tab

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#14858]
### User story

**AS A** Veteran
**I WANT** links on the I.L. Results screen to open in a new browser tab
**SO THAT** I don't lose my progress and have to start over.

Addresses collab cycle staging review ticket [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/63469).

## Acceptance criteria

- For all links of the more-information variety on the Results screen 
  - "Learn more about income limits and deductions"
  - All 6 links under "More helpful information"
- [x] All open in a new tab
- [x] Text is added to each link: `(opens in a new tab)`
- [x] Apply now links still open _in the same tab_ - i.e., don't change them
- [ ] Closed [SR ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/63469) when this one closes

**Comment by wesrowe** [comment]
@randimays and @jilladams, here's the other ticket I mentioned, coming out of IL staging review. I missed it in planning. We probably want to inject.

**Comment by jilladams** [comment]
Ok, noted. Moved to stretch/next, top of the queue. 

@randimays / @chriskim2311 can you take a look and ask any questions re: ACs in comments or slack and @wesrowe for follow up or add a point estimate if no questions?  

Once we have points, we'll just need to work out if this requires tradeoffs for anything already pulled into sprint, and surface that with Dave for approval. (Flagging that in case it needs to happen once I'm traveling Tuesday.)

**Comment by laflannery** [comment]
@wesrowe I came across this ticket while looking for something else and there is an accessibility concern here:

These links are all on the same VA domain and opening them in a new tab is quite unexpected, the user needs to be told that this is happening, especially since this breaks the external links standards set by the DS. With this change in behavior, we should also be changing the link text, for example - "Eligibility for VA health care (opens in a new tab)"

**Comment by jilladams** [comment]
@laflannery @wesrowe @randimays did this become a no-op on Fri? 
> We landed on recommending that those links open in the same tab, since it's an action, a primary flow and the desired exit from the app. But/and we are going to keep surfacing this conversation, especially if it impacts the PACT Act wizard, which will likely have more steps than this one.

https://github.com/department-of-veterans-affairs/va.gov-team/issues/63469#issuecomment-1684447851

**Comment by randimays** [comment]
@jilladams I interpreted that to mean all of the links on the Results page are to remain as they are. Seems like a no-op to me.

**Comment by laflannery** [comment]
@jilladams and @randimays I thought this was in reference to the previous question asked by Wes in the [comment right before](https://github.com/department-of-veterans-affairs/va.gov-team/issues/63469#issuecomment-1684416743)

> I wanted to ask, though: I'm not sure about whether to open the "Apply for VA health care" action links in a new tab.

**Comment by randimays** [comment]
@laflannery I can see it interpreted either way. I think we need final clarification from Erin. I'll add a comment.

**Comment by randimays** [comment]
[Clarification here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/63469#issuecomment-1686996172); she was only referring to `Apply for VA health care` links, not the informational links on that page.

I do have to reiterate, though:

> Allowing the back button in this scenario would be very tricky if possible at all. Because the Veteran is lead to a new page not within the application, the local session for Income Limits is wiped out. When they try to navigate backward, there is no data in the store to check if they should be on the Results page, and the page is routed back to the introduction.

I really can't think of a way to make possible what they are asking.

**Comment by wesrowe** [comment]
@laflannery, thank you for catching this nuance about the text and clarifying the intent of Erin's original comments. 

@randimays, we are going to open the info links in new tabs, but not the Apply Now. I'll update the ACs. To Erin's point, Apply Now is the primary action and we don't expect people to go back from there.

**Comment by wesrowe** [comment]
Oh, and @randimays, please add points.

**Comment by randimays** [comment]
@wesrowe Got it. Points added!

**Comment by randimays** [comment]
Update for mid-sprint: Created [a PR](https://github.com/department-of-veterans-affairs/vets-website/pull/25344) for this. Waiting to review instance to finish so others can review. Not anticipating carryover here.

**Comment by randimays** [comment]
Successfully validated in Staging. Closing as complete

<img width="508" alt="Screenshot 2023-08-24 at 9 43 17 AM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/19175324/46cf408c-4ab3-4474-9df9-7c5b0d7f4654">
<br/>
<br/>
<img width="789" alt="Screenshot 2023-08-24 at 9 43 00 AM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/19175324/4273bf81-7b5e-4c35-b9aa-f7973b990039">
<br/>
<br/>
<img width="611" alt="Screenshot 2023-08-24 at 9 42 56 AM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/19175324/85a84836-8f9f-4fb7-8c5e-472bd22ab8b8">
