### ISSUE TITLE
Reduce logging of every queued service

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#14857]
## User Story or Problem Statement
With the code that went out 8/18/23 we are mistakenly file logging any queing of a service.  This is going to create a log file every time a facility service, system service, or service term gets saved.    
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5752113/4471e4d1-939f-4f3f-b406-1a352d21226e)

That is too many files.  The file directory will grow and futher slow down developers when they sync files to local.

We should be only logging in the when we do a force push.

We may also want to introduce a cleanup routine that deletes that directory every so often.  Maybe tying it to the bi-monthly email notification task.

## Acceptance Criteria
- [x] File logging for facility services should only be done for force pushes, not for day-to-day service saves.

## Team
Please check the team(s) that will do this work.

- [ ] CMS Team
- [ ] Public Websites
- [x] Facilities
- [ ] User support
- [ ] Accelerated Publishing

**Comment by omahane** [comment]
> We may also want to introduce a cleanup routine that deletes that directory every so often. Maybe tying it to the bi-monthly email notification task.

@swirtSJW Can this be added separately? I think it should be on some kind of scheduled activity, perhaps every month with an entry to clear up these log files here: 
`tasks-periodic.yml`

**Comment by omahane** [comment]
@xiongjaneg @jilladams The excess logging has been handled. I suggest a follow-up ticket to do this:
> We may also want to introduce a cleanup routine that deletes that directory every so often. Maybe tying it to the bi-monthly email notification task.
