### ISSUE TITLE
I.L. Update number input component to use message-aria-describedby

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#14854]
Note: Launch-blocking for IL.

## Description
The `<va-number-input>` was recently updated to allow for hint text that is available to screen readers using `message-aria-describedby`. This update did not automatically get updated on the Income Limits app and needs to be added manually. Without this addition, screen reader users will not have access to the hint text for the form fields.

## Acceptance Criteria
- [ ] SR only message is added for zip code field (both current and past flow) and programmatically associated to the input field
- [ ] SR only message is added for dependents field (both current and past flow) and programmatically associated to the input field
- [ ] Requires accessibility review

**Comment by wesrowe** [comment]
@randimays, assigning this to you for pre-refinement. We can pull it into sprint when ready.

cc @jilladams, this and the new-tab story I'm about to write will need to come into sprint to enable launching IL as soon as collab cycle is finished.

**Comment by jilladams** [comment]
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14858#issuecomment-1684478168 -- same principle applies: need points, need to understand what tradeoffs need to happen in sprint to get er done, need to surface with DaveC for signoff on the sprint scope change.

**Comment by randimays** [comment]
@wesrowe Added points.

**Comment by laflannery** [comment]
There was a miscommunication when I opened this issue with the DST - the original issue with the hint text not being read was resolved but not by this new prop. This prop was completely separate and we don't need it in our case.
