### ISSUE TITLE
Centralized Content dropdown menu for Product should only list products with CC

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#14859]
## User Story or Problem Statement
As an editor creating Centralized Content, I only want to see Product options that use the Centralized Content type.

## Description or Additional Context 
Currently the Product dropdown menu lists products that don't have centralized content, which can be misleading.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcnNiIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--143f6a16c19a989273fd7690c8921aac86b4c235/Screenshot%202023-08-18%20at%204.39.42%20PM.png)

## Acceptance Criteria
- [ ] Testable_Outcome_X
- [ ] Testable_Outcome_Y
- [ ] Testable_Outcome_Z
- [ ] Requires design review
- [ ] Requires accessibility review

## Team
Please check the team(s) that will do this work.

- [ ] CMS Team
- [ ] Public Websites
- [X] Facilities
- [ ] User support
- [ ] Accelerated Publishing

**Comment by swirtSJW** [comment]
It can't work this way or you would never be able to pick it.  Chicken and egg problem.

**Comment by xiongjaneg** [comment]
closing in consideration of previous comment
