### ISSUE TITLE
Accessibility Audit for VBA Service Region content type

### ISSUE THREAD

**Issue by davidmpickett** [department-of-veterans-affairs/va.gov-cms#14856]
**1. What is this request for?**

[Service Region](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14705) is a new content type being created for the VBA Regional Office MVP

Drupal implementation in #14705 

VBA Content Specs XLS linked in #13096

### Acceptance Criteria
- [x] Code recommendations documented as ticket(s)  
- [ ] UX recommendations documented in Figma created in #14845

**Comment by xiongjaneg** [comment]
@swirtSJW @omahane Where should Laura look to review?

**Comment by swirtSJW** [comment]
@laflannery This is node content can be explored here
Login as a true admin (they are the only user permed to edit this right now)
https://staging.cms.va.gov/node/add/service_region

\

**Comment by laflannery** [comment]
No new accessibility issues (just a few existing ones already documented and backlogged for CMS team).

**Documenting UX items here for now until Figma is ready for me to put them in:**
- I am not sure the "Add address" button and various other options is supposed to be at the bottom of the Service locations section. I compared this to the Service locations section on VAMC Facility Health Service content type and that is different. It seems odd that an editor could add all these various blocks at this point to the Service region:

![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/106678594/f53245a4-59d2-43c7-9ac6-c92fd8b2a33f)-

- Help text: Please update casing of field names within the help text (we want sentence case not Title case)

> Choose the VA service this Service region is related to.

> Add all VBA facilities that are within this Service region. 

This second one should also have a period - we want to make sure these all have consistent punctuation.

**Comment by laflannery** [comment]
Added my comments in Figma
