### ISSUE TITLE
Yellow Ribbon: Update school year text to 2023-24

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#14861]
**STATUS: waiting for Tammy Hurley to email back that data is updated (8/17)**

### User story

**AS A** Veteran
**I WANT** to see that my YR search results are for the current school year 
**SO THAT** I trust.

### Engineering notes / background

- URL for "Find a YR school" page: https://www.va.gov/education/yellow-ribbon-participating-schools/
- screen shot of current state (out of date as of 8/17/23):
- 
<img width="555" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/4054752/7a4b2c17-e3c5-40ce-85fb-ebc91f31d09a">

## Acceptance criteria

- [ ] When given the green light from Tammy Hurley:
  - [ ] Text is updated to read `You may search for schools participating in the current academic year, August 2023 through July 2024.`

**Comment by wesrowe** [comment]
@chriskim2311, little one to pick up when you're ready

**Comment by wesrowe** [comment]
The dynamic idea has appeal. I'll ticket and we can refine with Dave.

**Comment by chriskim2311** [comment]
Verified on prod
