### ISSUE TITLE
BE: Magichead: Update View mode to be more intuitive and accessible

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#14860]
### User story

**AS A** Content Editor
**I WANT** the View mode of a Taxonomy term's Benefit Overview Sections to be more intuitive to read
**SO THAT** I feel certain the content is structured as I intended.

Current state of View screen:
<img width="441" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/4054752/f5e19e9e-6a74-4e86-993e-c6eb4be12386">

### Engineering notes / background

[Figma designs](https://www.figma.com/file/0gH9R0yAadciGcy73vpsgX/Magic-Headers-and-Paragraphs?type=design&node-id=0-1&mode=design&t=zIhMFL21La5kD1Hy-0) updated in #14815.

## Acceptance criteria

- [x] Implemented design
  - [x] To aid review, full list of recommendations to be implemented were in the design ticket, #14815 
- [x] Design review
- [x] PM review
- [x] Requires a11y review

**Comment by dsasser** [comment]
✅ a11y approved by [Laura](https://github.com/department-of-veterans-affairs/va.gov-cms/pull/15292#issuecomment-1727854400).
✅ UX approved by [Jordan](https://dsva.slack.com/archives/C52CL1PKQ/p1695062958024969?thread_ts=1695053434.025369&cid=C52CL1PKQ).

**Comment by dsasser** [comment]
I attempted to prod verify today, but due to a [Platform problem](https://dsva.slack.com/archives/C03LFSPGV16/p1695308716779229), it has yet to go out. I will check again on Monday.

**Comment by dsasser** [comment]
Verified in prod:

![Screenshot 2023-09-22 at 1 41 19 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/221539/66cae12f-1c37-4fbf-b26a-28343318f966)
