### ISSUE TITLE
VBA Facility name change:Integrated Disability Evaluation System (IDES) and Pre-Discharge Claims Intake Site at Fort Polk changed to Integrated Disability Evaluation System (IDES) and Pre-Discharge Claims Intake Site at Fort Johnson

### ISSUE THREAD

**Issue by omahane** [department-of-veterans-affairs/va.gov-cms#14871]
## Intake
- [x] What triggered this runbook? (Flag in CMS via Lighthouse migration)
Trigger: Changed name

- [x] Link to facility in production:
Facility CMS link: https://prod.cms.va.gov/new-orleans-va-regional-benefit-office-at-new-orleans-va-medical-center/locations/integrated-disability-evaluation-system-ides-and-pre-discharge
Facility API ID: vba_321e

### Drupal Admin steps
- [x] Edit the node and update the alias to match the new facility name, lowercase with dashes.
- [x] Edit the facility node, remove the `Changed name` flag, save the node with revision log

If this facility is a Regional Office
- [x] Go to [Sections taxonomy]( https://prod.cms.va.gov/admin/structure/taxonomy/manage/administration/overview), VBA > Rename the term that matches the old Facility name to use the new Facility name
    * If this process gets automated, this runbook can be retired.

**Comment by omahane** [comment]
Removed flag and resaved node.

**Comment by jilladams** [comment]
@stefaniefgray noting the body of this node still has some data related to Polk: 
![Screenshot 2023-08-29 at 4 37 31 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/85581471/3ebcd6b9-c654-4a28-b4b6-fe68cbabf617)

https://prod.cms.va.gov/new-orleans-va-regional-benefit-office-at-new-orleans-va-medical-center/locations/integrated-disability-evaluation-system-ides-and-pre-discharge
 Not sure where that comes from or if we need to do anything about it before VBAs are live, but in case.

**Comment by mmiddaugh** [comment]
The name and city had already been changed but the Non_VA_Location_Official_Name and Non_VA_Location_URL still reflected "Polk". All now updated in Sandy's DB

**Comment by jilladams** [comment]
Thanks Michelle. I still see Polk in the CMS, so I'll keep this ticket open til we see that change reflected -- may need another day for the data sync to show up through Lighthouse?

**Comment by jilladams** [comment]
Noting: Non-VA location URL still says "Fort Polk." @mmiddaugh not sure if we need to do something to jiggle the handle here with Lighthouse or something? Do you know?

**Comment by jilladams** [comment]
@swirtSJW could you take a look here and see if you smell anything funny?

**Comment by swirtSJW** [comment]
The data from Sandys DB comes in two ways.

```mermaid
flowchart TD
    A["Sandy's DB"] -->|nightly| B(Facility API)
    A -->|manual export then import to cms| C(CMS)
    B -->|nightly| C
```
The parts that are not getting updated is because we have to do a manual export of the DB, move it to the CMS then re-run the migration.

**Comment by jilladams** [comment]
From planning, next step: Michelle to run the CSV export from Sandy's DB, share it, and Facilities will need to run the migration with the new CSV to fix this.

**Comment by jilladams** [comment]
@xiongjaneg for awareness

**Comment by mmiddaugh** [comment]
@omahane 
Which CMS fields do not get updated via Lighthouse? Anything beyond VBA DB fields (Shared VHA location, Non-VA location official name, and non-VA location URL)?
Assuming the VBA DB fields mentioned above are the only ones in this situation...

- Since CMS is not yet the source of truth for VBA (aside from operating status),  I think it's fine that these few fields are out of sync - for now. 
- these aren't required fields and are not usually populated so they could be updated by hand if absolutely necessary. 

We'll want to run a definitive load before cutting over as the source of truth. 

@jilladams @xiongjaneg

**Comment by omahane** [comment]
I honestly don't know what gets picked up by Lighthouse. But definitely not the VBA DB fields. @swirtSJW might know, or I can ask Adam to certainty. I'll also take a look and see if this is documented anywhere.

**Comment by mmiddaugh** [comment]
I changed these manually and this issue can now be closed.
