### ISSUE TITLE
Accessibility audit of VBA banner content type

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#14896]
**1. What is this request for?**

VBA banner is a new content type being created for the VBA Regional Office MVP
 https://pr16076-0znhspa1mtvem1whd635hc16to4gcyg0.ci.cms.va.gov/node/4338/edit
or 
https://prod.cms.va.gov/node/4338/edit (if the PR env has been removed)

### Acceptance Criteria
- [x] Code recommendations documented as ticket  
- [x] UX recommendations documented in [the Figma file](https://www.figma.com/file/aKdT4weNNthDxb3r6MolEh/VBA-Content-Specs?type=design&node-id=362%3A770&mode=design&t=xWfG0zwPvlFANqqu-1)

**Comment by omahane** [comment]
Note:
I still need to update the links in the help text, which needs to wait for a prod link to the KB article to be available.
![Screenshot 2023-11-17 at 12 46 04 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/766573/ca98a5f4-6886-49d3-a486-238a8c9e027f)

**Comment by laflannery** [comment]
No issues, Jordan's figma looks good to me. (I did have a weird issue where the Rich text editor wasn't accessible by keyboard but then I wasn't able to recreate it so I believe this was a fluke as I was doing quite a few things at once but I did want to note it just in case)
