### ISSUE TITLE
504 Time-out errors during services push

### ISSUE THREAD

**Issue by omahane** [department-of-veterans-affairs/va.gov-cms#14902]
## Describe the defect
While trying to save changes to a VA Services term to trigger a save to VAMC Facility Health Services to push those changes initially to Lighthouse, we kept running into 504 Time-out errors.

## To Reproduce
Steps to reproduce the behavior (**which we don't want to do now that we have done the initial push of all services**)
1. Edit the VA Services term "[Addiction and substance use care](https://prod.cms.va.gov/taxonomy/term/47/edit?destination=/admin/structure/taxonomy/manage/health_care_service_taxonomy/overview)"
2. Save the term
3. Note the 504 Gateway Time-out error
4. In the [Recent Logs](https://prod.cms.va.gov/admin/reports/dblog), you may also see an error that begins "Drupal\Core\Database\DatabaseExceptionWrapper: SQLSTATE[HY000]" 

## AC / Expected behavior
Updating a term should not result in an error.

## Screenshots
![Screenshot 2023-08-21 at 4 38 58 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/766573/e0f60d36-2338-4b8e-bfd6-61bead49f291)

 ## Additional context
Discussed here: https://dsva.slack.com/archives/CT4GZBM8F/p1692706455579669
https://dsva.slack.com/archives/C02BTJTDFTN/p1692208312102169
https://dsva.slack.com/archives/CT4GZBM8F/p1692741906567329

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Defect")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS workstream (orange) (not needed for bug tickets)
- [ ] CMS-supported product (black)

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [ ] `Public Websites`
- [x] `Facilities`
- [ ] `User support`
- [ ] `Accelerated Publishing`

**Comment by swirtSJW** [comment]
Closing this as we will not be testing this on the prod due to not force pushing anytime soon.
