### ISSUE TITLE
PROD Deploy Blocker: DEV/STAGING Deploy Tests Failing due to vets-website /graphql "TypeError: Cannot read property '0' of undefined"

### ISSUE THREAD

**Issue by ElijahLynn** [department-of-veterans-affairs/va.gov-cms#1490]
Getting:
> 11:37:49   " ┃ │ TypeError: Cannot read property '0' of undefined", 
http://jenkins.vfs.va.gov/job/deploys/job/cms-vagov-staging/251/console
http://jenkins.vfs.va.gov/job/deploys/job/cms-vagov-dev/353/console

Discussing here: https://dsva.slack.com/archives/CT4GZBM8F/p1586890042053400?thread_ts=1586889245.051800&cid=CT4GZBM8F

**Comment by ElijahLynn** [comment]
This also failed our latest content deploy here http://jenkins.vfs.va.gov/job/builds/job/vets-website-content-vagovprod/311/console
> TypeError: Cannot read property '0' of undefined

**Comment by ElijahLynn** [comment]
@cvalarida identified the root cause on a call with @swirtSJW, @Clark-W-Griswold and I. 

The cause was that an editor introduced an `https` files link that the build script attempts to replace with the right ELB links. e.g. https://prod.cms.va.gov/sites/default/files/2020-04/UD%20ROB1.pdf  

Previously we only had http links. 

https://github.com/department-of-veterans-affairs/vets-website/blob/e875cccfecdd21e0de413e87e1da975664b6ff61/src/site/stages/build/drupal/assets.js#L65

https://github.com/department-of-veterans-affairs/vets-website/blob/0f04910e219ab7bc8ebf3d55eea2c31638ff1d48/src/site/constants/drupals.js#L53-L54

**Comment by kevwalsh** [comment]
i've gone ahead and edited the offending content, which should unblock this, but it's clear to that it's a bandaid solution. 

1. Vets-website needs to be fixed to allow https links when it fetches files. 
2. CMS editorial experience probably needs some improvement to discourage the use of direct PDF links in WYSIWYG, because of the challenges that poses to single source of truth. We want editors to reference media entities, not absolute links to PDFs that can easily become outdated. But that's secondary to problem #1.

**Comment by ElijahLynn** [comment]
Also, fwiw. I have no idea how our auto-deploy job succeeded today, the commit it deployed never passed tests and GitHub reported it as "SUCCESS" 

![image](https://user-images.githubusercontent.com/1504756/79287830-e537bf80-7e79-11ea-9e83-152f231a6563.png)

http://jenkins.vfs.va.gov/job/deploys/job/cms-auto-deploy/162/console

**Comment by Clark-W-Griswold** [comment]
Code change has been merged to master with the following pull request:
https://github.com/department-of-veterans-affairs/vets-website/pull/12236

**Comment by ElijahLynn** [comment]
Thanks @Clark-W-Griswold, now we need to also update our vets-website dependency to include your change and then we can close this out.
