### ISSUE TITLE
Create new KB article or update  existing article : Linking to an accordion

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#14908]
## Background context
**What is the request for?**
- [X] Create new article
  - [x] I have reviewed the Knowledge Base to confirm that an article for this topic does not already exist
- [ ] Update existing article: [Link to existing article](URL)

## If requesting a new article:
**Topic Description**
Details about the topic. If possible, include an example of a use case or situation that illustrates the topic well.
#14206 now makes it possible to link to an accordion, which will take a user directly to an intended accordion which will be open to reveal the contents.

### Use cases
- A patient wants to know what hours our lab is open. Since I cannot link to the accordion, I have to link to this site and tell them to scroll down to "Laboratory" and expand it to see the hours.
[Mann-Grandstaff Department Of Veterans Affairs Medical Center | VA Spokane Health Care | Veterans Affairs](https://www.va.gov/spokane-health-care/locations/mann-grandstaff-department-of-veterans-affairs-medical-center/)
Reported 6/14/23 by Kristin A. Young from VA Spokane Health Care
- Working example: [Equine assisted psychotherapy](https://www.va.gov/salt-lake-city-health-care/programs/horses-helping-veterans/#equine-assisted-psychotherapy-101790)
- Vet Center FAQs

**Audience**
Who is this intended for? Who would need this information? (i.e. All editors, only editors for a particular product, Internal use only, etc.)
- All editors

**Other related KB articles, if applicable:**
- [If you know that related KB articles already exist, link them here]

## Is the article associated with an ongoing product or feature update?
- [X] Yes #14206 now closed
- [ ] No

  
## Priority or deadline for request
Choose either Deadline or a priority:

- [ ] Deadline: [name the deadline here]
- [ ] Priority:
  - [ ] Critical - Without this, there is a large negative impact on the majority of editors causing negative consequences within the CMS; Should be completed as soon as possible
  - [ ] High - Without this, there is negative impact on some editors causing negative consequences within the CMS; should be completed within the current sprint
  - [ ] Medium - Without this, there is confusion for editors but not causing negative consequences within the CMS; Should be completed within the next 1-2 sprints
  - [X] Low - This is not currently causing confusion for many editors but would be a nice to have or is something that may be more impactful in the future; Should be completed within the next 3-4 sprints

## Acceptance Criteria
- [x] Article is created/updated in Drupal, node ID 61442
- [ ] Impacts on other KB articles have been considered and any necessary changes have been made and saved as draft
- [ ] If necessary, add link to the new KB article in the [Content model document](https://prod.cms.va.gov/admin/structure/cm_document) for that content type 
- [x] [Ticket for article review](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/new?assignees=&labels=Knowledge+Base%2C+Needs+refining&template=knowledge-base-article-review.md&title=Review+of+new+or+updated+KB+article+%3A+%3Cinsert+topic+here%3E) has been created

**Comment by xiongjaneg** [comment]
submitted to CMS Team in Slack

**Comment by laflannery** [comment]
@xiongjaneg My draft is in [Google Docs](https://docs.google.com/document/d/19mYP5TV64DMFzNJa1nACjVH7-EifcFOSikvrzbVjjiA/edit?usp=sharing). I tend to keep things in here until they are at least somewhat finalized because it's a lot easier to edit and collaborate then it is in the KB. I have some comments in there as well about my thought process and section I think could use the most help.

**Comment by xiongjaneg** [comment]
in review by VHA Digital Media

**Comment by xiongjaneg** [comment]
From VHA DM
•	The article indicated there will be screen shots, which will definitely be needed, so I would like to review again with the screen shot(s) in the article.
•	Are the ID attributes standard for health services across all VAMCs? I ask just in case we could provide as an alternative to following the instructions in the KB article. 
•	Not sure if this will be addressed with screen shots in the KB article, but I found it easier to use the tag (circled in red in the screen shot below) on the left to find the ID attribute than searching through the code

**Comment by xiongjaneg** [comment]
From Michelle

- Suggest: By deep linking to an accordion, a Veteran can be sent directly to content within an accordion 
- This appears to be a general statement so we might want to make this more general - i.e., This link can now be sent directly in emails or used within other content and when activated, site visitors will be directed to the relevant accordion, which is automatically be open. In this case, the link will direct Veterans to the Boston VAMC Health services page with the COVID-19 accordion already open.

**Comment by laflannery** [comment]
@xiongjaneg Is this something that I should be updating based on feedback or is someone else going to be taking that on?

**Comment by xiongjaneg** [comment]
@laflannery This is me. VHA Digital Media just reviewed and I'll make updates. I'll copy you on revisions from their comments so you can provide feedback as well. Thanks for following up.

**Comment by xiongjaneg** [comment]
@laflannery 
For Justin's two questions, do you know the answers offhand? If not, I can do some checking.
• Are the ID attributes standard for health services across all VAMCs? I ask just in case we could provide as an alternative to following the instructions in the KB article.
• Not sure if this will be addressed with screen shots in the KB article, but I found it easier to use the tag (circled in red in the screen shot below) on the left to find the ID attribute than searching through the code
<img width="862" alt="Screenshot 2023-09-15 at 9 50 09 AM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/73648238/a641a451-23fc-497a-8351-b5c5b366763a">

**Comment by laflannery** [comment]
@xiongjaneg Answer below:
1. For the IDs, they typically use the accordion title, though I can't say this would be a guarantee. The ID also follows these rules:
   1. Spaces are replaced with dashes
   2. All letters are lowercased, and remembered that IDs are case sensitive 
   3. For example if the Accordion title is "Vaccine information for Veterans" the ID would be `vaccine-information-for-veterans`.
2. The screenshot was a bit cut off and fuzzy but I believe Justin is referring to the blue text in the pop up here:
   1. ![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/106678594/3c32e4d4-52f7-4fc1-8822-f3afdfb21333)
   2. The tricky thing about using this text is that this is including not only the ID but also all classes that are added to the element. In this case, someone might think the entire ID is `addiction-and-substance-use-ca.va-accordion-item.hydrated` when in actuality is is only `addiction-and-substance-use-ca`.
   3. If you do use this way to find the ID, the only part of the blue text that you should use is whatever is before the first period.
   4. Its also worth noting that different browsers display this popup differently and this tactic might actually be easier in these browsers. For example in FF, the ID is everything in green (much easier to explain!)
      1. ![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/106678594/740e5de1-53c1-462b-ad0a-a725ba93c1dc)

**Comment by xiongjaneg** [comment]
@BerniXiongA6 Submitted for CMS Team review.

**Comment by xiongjaneg** [comment]
@laflannery I'm working on the draft article in prod now and will add your comment. Thanks for the update.

**Comment by xiongjaneg** [comment]
Published for VHA DM final review

**Comment by BerniXiongA6** [comment]
Hi @xiongjaneg -- the article looks great. I have 2 suggested edits:

- Suggested Edit 1 -

Current: "Learn how to create a deep link to an accordion which can be used to direct site visitors directly to content contained within the accordion."

Suggested: "Learn how to create a deep link to an accordion which can be used to send site visitors directly to content contained within the accordion."

- Suggested Edit 2 -

Current: "7. Using the highlight functionality in the inspector, locate the that corresponds to the COVID-19 vaccine accordion."

Suggested: "7. Using the highlight functionality in the inspector, locate the [insert omitted word here] that corresponds to the COVID-19 vaccine accordion."

**Comment by xiongjaneg** [comment]
@BerniXiongA6 Both changes made. Closing this ticket. Thank you!
