### ISSUE TITLE
Parameter Store copy of CMS prod DB password may be incorrect.

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-cms#14922]
## Description

Last night (08/22), there was an issue with production that warranted direct access to the database. The engineers available did not know about the `cms` user (see #14921), and so attempted to connect to the DB using the credentials in Parameter Store. Unfortunately, they reported that the password credential was incorrect.

This should be investigated and remediated; going off memory, the environment variables for the credentials are set from Parameter Store, but I could be misremembering.

## Acceptance Criteria
- [x] The following DB password values stored in Parameter Store have been reviewed for accuracy and updated if necessary:
  - [x] Prod
  - [x] Staging

**Comment by ndouglas** [comment]
Both passwords were correct. Probable source of issue was using the value at `/cms/prod/mariadb/master_password` rather than `/cms/prod/mariadb/drupal_password`.

The broader issue is probably captured by #14921.

**Comment by swirtSJW** [comment]
> Both passwords were correct. Probable source of issue was using the value at `/cms/prod/mariadb/master_password` rather than `/cms/prod/mariadb/drupal_password`.

Interesting that they worked.  We tried both while acting as the cms user.   Both failed.  (maybe copy and pasting not working or throwing an extra character in that we could not detect??  (I saw that happen to Eljah a time or two)

**Comment by ndouglas** [comment]
Well, we're still setting these from Credstash, it looks like, so it's only a matter of time until they're completely incorrect 🙂  I'll open an issue for that.
