### ISSUE TITLE
Front end template for VBA Centralized Content type 

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#14933]
## Description or Additional Context 
Front end template for VBA Centralized Content type based on spec #13799.
Some centralized content is not appearing in preview, so needs verification that all parts are displayed.

### Resources
- Refer to VBA Content Specs XLS linked in #13096
- [Sketch file](https://www.sketch.com/s/891d33ae-152d-471c-ab5d-9aedf89cf6ff/p/FC995695-308A-4493-8461-D9AFE6DC6B25/canvas)
- [VBA centralized content in Drupal](https://prod.cms.va.gov/centralized-content/national-vba-facilities-content)

## Acceptance Criteria
- [x] Centralized content listed displays on a VBA regional office page
  - [x] Benefit office overview
  - [x] [Subscribe to our newsletter about VA benefits](https://public.govdelivery.com/accounts/USVAVBA/subscribers/new) in the social media area
- [x] Requires design review (added to PR)
- [x] Requires accessibility review (added to PR)

## Team
Please check the team(s) that will do this work.

- [ ] CMS Team
- [ ] Public Websites
- [X] Facilities
- [ ] User support
- [ ] Accelerated Publishing

**Comment by swirtSJW** [comment]
There is no FE tempate for Centralized content.  They just show up as fields on the facility nodes.   This ticket can likely be discarded.

**Comment by xiongjaneg** [comment]
@xiongjaneg split into two tickets like Facility type

**Comment by xiongjaneg** [comment]
closing per Steve's comment about this being a field on the facility node

**Comment by jilladams** [comment]
Merged pending deploy. Should go tomorrow.

**Comment by xiongjaneg** [comment]
Verfied on prod
<img width="983" alt="Screenshot 2024-03-06 at 9 55 50 AM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/73648238/98324883-0766-49ca-878b-0650d4078a6f">
<img width="960" alt="Screenshot 2024-03-06 at 9 56 04 AM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/73648238/f9317d9a-69f6-4090-abeb-6ae211f79198">
