### ISSUE TITLE
PAW: Agent Orange questions and display conditions

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#14939]
### User story

**AS A** Veteran whose service included 1989 or earlier
**I WANT** to be asked the first AO location question
**SO THAT** I can get started on the AO experience.

## Acceptance criteria

- [x] Added AO questions 2.2.A and 2.2.B - lorem follows established pattern 
  - [x] displays under correct conditions 
  - [x] url follows established pattern
- [x] Added AO question 2.2.1.A and 2.2.1.B - lorem follows established pattern
  - [x] displays under correct conditions 
  - [x] url follows established pattern
- [x] Added AO question 2.2.2 - lorem - lorem follows established patternno, not sure)
  - [x] displays under correct conditions 
  - [x] url follows established pattern
- [x] Added AO question 2.2.3 - lorem - lorem follows established pattern
  - [x] displays under correct conditions 
  - [x] url follows established pattern
- [x] Tests created per test plan and established pattern
- [ ] PM review
- [ ] Design review

**Comment by wesrowe** [comment]
@randimays @chriskim2311, I'm noticing that the agent orange checkbox questions have interesting logic – users need to be prevented from making contradictory selections, like choosing a location _and_ No or Not sure. Rather than making that part of this ticket, I wonder if it should be its own thing. (not sure if it should come before this ticket or after.) Thoughts?

**Comment by wesrowe** [comment]
update: @thejordanwood, I went ahead and created a design ticket for this validation experience, #14951.

**Comment by randimays** [comment]
@wesrowe We could add that as a separate ticket that comes after this one. It makes sense to me to add the question without that protection, then wire up the more complex validation afterward.

**Comment by randimays** [comment]
End-of-week update for this: most of this ticket is finished. All I have left is to ensure that answers that are no longer applicable for the flow are cleared. Example: if you answer all the questions, then change from `1990 or later` to `During both of these time periods`, the flows have no overlap in questions, and we need to clear out the Burn Pit answers so they are not used in determining the correct results page.

**Comment by wesrowe** [comment]
@randimays, I'm pretty sure you just typoed in your example – there **is** overlap between ≥1990 and both-time-periods, but (I think you probably meant) there isn't any overlap between ≤1989 and ≥1990.

**Comment by randimays** [comment]
@wesrowe Yes! That was indeed a typo. Thanks for calling that out.

**Comment by randimays** [comment]
Near end of sprint. I have some more unit tests to write today, then I need to make sure all the Cypress tests are covered, and prepare to share everything with Chris so he can review. This will likely carry over for reviews (@cindymerrill wants to go over for a demo before merging, too).

**Comment by cindymerrill** [comment]
@randimays I don't want to delay your merge, so if you want to merge and get my feedback later once it's up on Staging, that's OK with me.

**Comment by randimays** [comment]
👍  Thanks, Cindy! I think that would work better.

**Comment by wesrowe** [comment]
Logic is as expected. Merge away!

**Comment by randimays** [comment]
Validated in staging. Closing!
