### ISSUE TITLE
Front End testing for VBA Service Location paragraph type

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#14936]
## Description or Additional Context 
Test the updated Service Location paragraph type for VBA that Drupal engineers implemented in #14704 

To create a VBA Facility service in the [integration branch](https://pr15622-xptmfsnjoodldn85nzgkrgljqtfbz24b.ci.cms.va.gov/node/add/vba_facility_service)

This is used in the following VBA content types:
    - VBA service region
    - VBA facility service
- Use the content editor role

### Resources

[Design System link](https://www.figma.com/files/920496649063276587/project/53099542/CMS-Design-System-Library?fuid=1118989037713679864)

[Sketch file](https://www.sketch.com/s/891d33ae-152d-471c-ab5d-9aedf89cf6ff/p/DC11E46F-AF92-4DFD-AC0B-BEB9A9DD3C9A/canvas)

## Tasks
- [ ] Wrap the component in a purely semantic, unstyled div or span element and test that the wrapper is rendered to ensure that the component also renders.

## Acceptance criteria
- [ ] The wrapper is rendered.

**Comment by eselkin** [comment]
So the Service Location paragraph type refers to the `fieldServiceLocation` on the `reverseFieldOfficeNode` (This is the local facility service at a VBA) and the `fieldServiceLocation` on the `reverseFieldVbaRegionFacilityListNode`'s entity (NodeServiceRegion type) (for the regional service). 

We currently don't implement all of the Service Location paragraph values in the current development (Max is working on using more of the Regional Service one and will later work on the Facility Service one). So currently, all we can do is test that the pieces in the accordion are there that we currently implement. Therefore this testing will not test for completeness of those sections. Currently the entity of the `reverseFieldVbaRegionFacilityListNode` does not even get the `fieldServiceLocation` values.

**Comment by jilladams** [comment]
@eselkin should we cut separate tickets to make changes to this test, based on your notes, once the other pieces are in place from Max's side? Or should we just press pause here til we can do a more comprehensive job?  (cc @xiongjaneg )

**Comment by eselkin** [comment]
It's hard to say what's better. I have a fix for the component that is being tested and the test to test the full extent of the pieces of the accordions for the condition when a regional service and facility service exist for the same thing. However, it can't be built in the CI now because content-build is hitting a memory limit. I asked about it on CoP platform frontend but not sure if that's the right place.

**Comment by jilladams** [comment]
I think where we landed today is: 
* Max's changes on #14957 can merge as soon as Laura signs off on a11y grounds
* After that merge, Eli to pull those changes in and get his PR finalized, once code kinks are worked out. That will continue in S103.
* No additional tickets needed, but we noted in retro to make sure we're careful about sequencing build / test tickets in future sprints. 

@eselkin / @xiongjaneg let me know if that's incorrect or sounds right
