### ISSUE TITLE
PAW: Add Intro, first question and first Burn Pit question

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#14931]
### User story

**AS A** Veteran
**I WANT** to be asked the first few questions, including the first burn pit question (if appropriate to my service dates)
**SO THAT** I get started on the wizard experience.

**AS A** PM/PO/Eng
**I WANT** to add a conditional question
**SO THAT** we can try out the question display logic aspect of the architecture.

### Quality / testing notes
- Testing: Cypress tests
- Testing: Unit tests (for display conditions logic)

## Acceptance criteria

Note: required-question validation will be handled in a future ticket

- [x] Add introduction page with text simply “intro text here TBD” and a "Begin" CTA link (green-arrow variety)
  - [x] url: /test/pact-act/introduction
- [x] Add service period question - lorem = `service period S1`
  - [x] radio button choices: 1990 or later; 1989 or earlier; During both of these time periods
  - [x] logic: ask everyone
  - [x] url: /test/pact-act/service-period-temp
- [x] Added burn pit question 2.1.0 - lorem = `burn pit  S2.1.0, did you serve in any of these locations?`
  - [x] Logic: only displays if user selected ≥1990 or Both re svc period
  - [x] radio button choices: Yes, No, Not sure
  - [x] url: /test/pact-act/burn-pit-2-1-0
- [x] Implemented Cypress tests and unit tests (for display conditions logic)
- [x] A11y review
- [ ] Design review
- [x] PM review

**Comment by randimays** [comment]
[PR](https://github.com/department-of-veterans-affairs/vets-website/pull/25611) posted for review [here](https://dsva.slack.com/archives/C52CL1PKQ/p1694457145297999).

**Comment by wesrowe** [comment]
I verified that choosing "1989 or earlier" is a dead end, but both "1990 and later" and "both" lead to 2.1.0.

**Comment by randimays** [comment]
@laflannery had some feedback about the build re: `h1`s in the `label` instead of as a standalone element for the radio questions. Going to coordinate with her today to be sure focus management is correct before merging in the changes.

**Comment by jilladams** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/25611 merged. 

Laura signed off here: https://dsva.slack.com/archives/C52CL1PKQ/p1694532029201369?thread_ts=1694457145.297999&cid=C52CL1PKQ

Wes signed off here: https://dsva.slack.com/archives/C52CL1PKQ/p1694560749574919?thread_ts=1694552489.228249&cid=C52CL1PKQ

Closing.
