### ISSUE TITLE
PAW: Add remainder of Burn Pit questions

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#14932]
### User story

**AS A** Veteran whose service included 1990 or later
**I WANT** to be asked subsequent burn pit location questions if I didn't say yes to the first question
**SO THAT** I get all the burn pit location questions.

### Engineering notes / background
Engineering notes:

### Quality / testing notes
- Testing: Cypress tests
- Testing: Unit tests (for display conditions logic)

## Acceptance criteria

Note: “lorem ipsum” should be a little more descriptive, e.g. “intro text here TBD” or “[Burn pit question 2.1]”

- [x] Added burn pit question 2.1.1 - lorem = `burn pit  S2.1.1`
  - [x] displays under correct conditions
  - [x] url: /test/pact-act/burn-pit-2-1-1
- [x] Added burn pit question 2.1.2 - lorem = `burn pit  S2.1.2`
  - [x] displays under correct conditions
  - [x] url: /test/pact-act/burn-pit-2-1-2
- [x] Implemented Cypress tests and unit tests (for display conditions logic)
- [ ] ~~Client-side validation in case a response is not chosen: `[draft] please select a response`~~ _Moved this to a separate validation ticket_
- [ ] A11y review
- [ ] Design review
- [ ] PM review

**Comment by randimays** [comment]
Just picked this up yesterday from Stretch. It will carry over.

**Comment by randimays** [comment]
Verified in staging. Closing!
