### ISSUE TITLE
Determine why cms-auto-deploy job passed/deployed with failed commit status

### ISSUE THREAD

**Issue by ElijahLynn** [department-of-veterans-affairs/va.gov-cms#1493]
Also, fwiw. I have no idea how our auto-deploy job succeeded today, the commit it deployed never passed tests and ~GitHub~ Jenkins reported it as "SUCCESS" in the job but not in the GithUb UI.  

![image](https://user-images.githubusercontent.com/1504756/79287830-e537bf80-7e79-11ea-9e83-152f231a6563.png)

http://jenkins.vfs.va.gov/job/deploys/job/cms-auto-deploy/162/console

_Originally posted by @ElijahLynn in https://github.com/department-of-veterans-affairs/va.gov-cms/issues/1490#issuecomment-613756008_

**Comment by indytechcook** [comment]
I did some more testing on this PR on the cms-test and noticed it wasn't always working correctly.  I found that the commit status are being updated by the cron jobs.:  https://api.github.com/repos/department-of-veterans-affairs/va.gov-cms-test/statuses/216985b564fa4254c74ebf0672a75ddd965bf142 

```
{
"url": "https://api.github.com/repos/department-of-veterans-affairs/va.gov-cms-test/statuses/216985b564fa4254c74ebf0672a75ddd965bf142",
"avatar_url": "https://avatars2.githubusercontent.com/u/46540222?v=4",
"id": 9627976723,
"node_id": "MDEzOlN0YXR1c0NvbnRleHQ5NjI3OTc2NzIz",
"state": "success",
"description": "ip-10-247-32-64 — Run cron every 15 min as called by Jenkins....",
"target_url": "https:///",
"context": "va/background/periodic/cron",
"created_at": "2020-05-12T15:03:14Z",
"updated_at": "2020-05-12T15:03:14Z",
"creator": {
"login": "va-cms-bot",
"id": 46540222,
"node_id": "MDQ6VXNlcjQ2NTQwMjIy",
"avatar_url": "https://avatars2.githubusercontent.com/u/46540222?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/va-cms-bot",
"html_url": "https://github.com/va-cms-bot",
"followers_url": "https://api.github.com/users/va-cms-bot/followers",
"following_url": "https://api.github.com/users/va-cms-bot/following{/other_user}",
"gists_url": "https://api.github.com/users/va-cms-bot/gists{/gist_id}",
"starred_url": "https://api.github.com/users/va-cms-bot/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/va-cms-bot/subscriptions",
"organizations_url": "https://api.github.com/users/va-cms-bot/orgs",
"repos_url": "https://api.github.com/users/va-cms-bot/repos",
"events_url": "https://api.github.com/users/va-cms-bot/events{/privacy}",
"received_events_url": "https://api.github.com/users/va-cms-bot/received_events",
"type": "User",
"site_admin": false
}
},
```

**Comment by indytechcook** [comment]
Currently the github jenkins library does not have the ability to call the correct Github API method:  https://github.com/hub4j/github-api/issues/788

**Comment by indytechcook** [comment]
We are using
```
def build_status(ref, app) {
  def github = GitHub.connect()
  if (github.getRepository(GH_ORG + '/' + app).getLastCommitStatus(ref)) {
    def r = github.getRepository(GH_ORG + '/' + app).getLastCommitStatus(ref).getState()
    return r.toString()
  } else {
    return "NULL"
  }
}
```

But we need something like
```
def build_status(ref, app) {
  def status_url = "https://api.github.com/repos/department-of-veterans-affairs/${app}/commits/${ref}/status"
  def response = httpRequest status_url
  if (!response.getStatus().equals(200)) {
    return NULL;
  }
  def json = readJSON text: response.getContent()
  echo "${json}"
  return json.status
}
```

See the difference between the output of these two commands:
https://api.github.com/repos/department-of-veterans-affairs/va.gov-cms-test/commits/216985b564fa4254c74ebf0672a75ddd965bf142/status vs https://api.github.com/repos/department-of-veterans-affairs/va.gov-cms-test/statuses/216985b564fa4254c74ebf0672a75ddd965bf142

**Comment by ElijahLynn** [comment]
> I did some more testing on this PR on the cms-test and noticed it wasn't always working correctly. I found that the commit status are being updated by the cron jobs.: https://api.github.com/repos/department-of-veterans-affairs/va.gov-cms-test/statuses/216985b564fa4254c74ebf0672a75ddd965bf142
> 
> ```
> {
> "url": "https://api.github.com/repos/department-of-veterans-affairs/va.gov-cms-test/statuses/216985b564fa4254c74ebf0672a75ddd965bf142",
> "avatar_url": "https://avatars2.githubusercontent.com/u/46540222?v=4",
> "id": 9627976723,
> "node_id": "MDEzOlN0YXR1c0NvbnRleHQ5NjI3OTc2NzIz",
> "state": "success",
> "description": "ip-10-247-32-64 — Run cron every 15 min as called by Jenkins....",
> "target_url": "https:///",
> "context": "va/background/periodic/cron",
> "created_at": "2020-05-12T15:03:14Z",
> "updated_at": "2020-05-12T15:03:14Z",
> "creator": {
> "login": "va-cms-bot",
> "id": 46540222,
> "node_id": "MDQ6VXNlcjQ2NTQwMjIy",
> "avatar_url": "https://avatars2.githubusercontent.com/u/46540222?v=4",
> "gravatar_id": "",
> "url": "https://api.github.com/users/va-cms-bot",
> "html_url": "https://github.com/va-cms-bot",
> "followers_url": "https://api.github.com/users/va-cms-bot/followers",
> "following_url": "https://api.github.com/users/va-cms-bot/following{/other_user}",
> "gists_url": "https://api.github.com/users/va-cms-bot/gists{/gist_id}",
> "starred_url": "https://api.github.com/users/va-cms-bot/starred{/owner}{/repo}",
> "subscriptions_url": "https://api.github.com/users/va-cms-bot/subscriptions",
> "organizations_url": "https://api.github.com/users/va-cms-bot/orgs",
> "repos_url": "https://api.github.com/users/va-cms-bot/repos",
> "events_url": "https://api.github.com/users/va-cms-bot/events{/privacy}",
> "received_events_url": "https://api.github.com/users/va-cms-bot/received_events",
> "type": "User",
> "site_admin": false
> }
> },
> ```

We need to add `--dry-run` to all invocations of `yaml-tests` then so it doesn't contact the GitHub API at all.

**Comment by indytechcook** [comment]
We need it to connect the github API for the tests.  We are just using the Github API incorrectly.

**Comment by ElijahLynn** [comment]
> We need it to connect the github API for the tests. We are just using the Github API incorrectly.

Ah yes, I shouldn't have said "all invocations" just the non-test ones, you got it!
