### ISSUE TITLE
Front End testing for VBA banner

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#14938]
## Description or Additional Context 
Front End testing for VBA banner content type per spec #13811 
Refer to [VBA Content Specs in Sharepoint](https://dvagov.sharepoint.com/:x:/s/SitewideFacilitiesTeam/EVVWpQp091ZEvI2n-9iyvTQBGYFZjxlVPN3Zfyz-Eh6Oyg?e=NVvsCc)

## Acceptance Criteria
- [ ] Testable_Outcome_X
- [ ] Testable_Outcome_Y
- [ ] Testable_Outcome_Z
- [ ] Requires design review
- [ ] Requires accessibility review

## Team
Please check the team(s) that will do this work.

- [ ] CMS Team
- [ ] Public Websites
- [X] Facilities
- [ ] User support
- [ ] Accelerated Publishing

**Comment by eselkin** [comment]
@xiongjaneg this was covered as an AC on the VBA banner ticket, which kind of blended into the spike on testing for VBA. Both e2e and unit tests are done.

**Comment by xiongjaneg** [comment]
closing as completed in #16243
