### ISSUE TITLE
Front End template for VBA Facility Service content type

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#14942]
## Description or Additional Context 
Front End template for VBA Facility Service content type per spec #13129 

### Resources
- VBA Content Specs XLS linked in #13096
- [Sketch file](https://www.sketch.com/s/891d33ae-152d-471c-ab5d-9aedf89cf6ff)

## Acceptance Criteria
- [x] The front end shown matches the design file to a reasonably accurate extent.
- [x] If a USWDS V3 component is available, use the V3 component
- [ ] Any applicable unit or component testing is completed.
- [x] Any refinements to the front end have been stubbed out in tickets.
- [ ] Update the header for "Can't find the service you're looking for" to an H2
- [x] Requires design review
- [x] Requires accessibility review

## Team
Please check the team(s) that will do this work.

- [ ] CMS Team
- [ ] Public Websites
- [X] Facilities
- [ ] User support
- [ ] Accelerated Publishing

**Comment by xiongjaneg** [comment]
Facility Service includes service locations so that might be a blocker on this ticket. Also, Jordan will be updating design based on feedback.

**Comment by xiongjaneg** [comment]
@xiongjaneg check if V3 has been added

**Comment by jilladams** [comment]
@maxx1128 reminder; Please post end of sprint update

**Comment by maxx1128** [comment]
The bulk of the work for this ticket is currently done, the only blocker to review right now is getting the unit tests properly passing on the pull request.

**Comment by jilladams** [comment]
For end of sprint: Unit test troubleshooting is still the blocker here.

**Comment by jilladams** [comment]
@maxx1128 realizing this ticket had design / A11y review as ACs, but we didn't get that done before PR merged. That means: we'll need to stand this up with some data somewhere so @laflannery and @thejordanwood can review. @maxx1128 could you own that this week, and make sure to tag them in when you're ready for their review?

**Comment by maxx1128** [comment]
@jilladams Sure thing. I can get a tugboat instance up with this data this week.

**Comment by thejordanwood** [comment]
@maxx1128 This looks good to me!

**Comment by laflannery** [comment]
Can we please update the header for "Can't find the service you're looking for" to an H2? Otherwise, looks good!

**Comment by maxx1128** [comment]
This issue is just about ready to close. [The second pull request](https://github.com/department-of-veterans-affairs/content-build/pull/1867) wraps up the accessibility review and shows all the tests are passing. Once that merges, this should be ready to close.

**Comment by jilladams** [comment]
Merged the PR, should deploy tomorrow.
