### ISSUE TITLE
Front End query for VBA Centralized Content type

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#14945]
## Description or Additional Context 
Front End query for VBA Centralized Content type per spec #13799 
Refer to [VBA Content Specs in Sharepoint](https://dvagov.sharepoint.com/:x:/s/SitewideFacilitiesTeam/EVVWpQp091ZEvI2n-9iyvTQBGYFZjxlVPN3Zfyz-Eh6Oyg?e=NVvsCc)

## Acceptance Criteria
- [ ] Testable_Outcome_X
- [ ] Testable_Outcome_Y
- [ ] Testable_Outcome_Z
- [ ] Requires design review
- [ ] Requires accessibility review

## Team
Please check the team(s) that will do this work.

- [ ] CMS Team
- [ ] Public Websites
- [X] Facilities
- [ ] User support
- [ ] Accelerated Publishing

**Comment by swirtSJW** [comment]
There is no separate query for centralized content.  It is just a field on the content type that is using it (VBA Facility)

This can likely be discarded.

**Comment by xiongjaneg** [comment]
closing per Steve's comment
