### ISSUE TITLE
Build Front End query for VBA Facility

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#14948]
## Description or Additional Context 
In order to build the VBA Regional Office web page, we need a front end query for VBA Facility. We need to know what data is needed for this query, whether or not this builds on an existing query, is there any existing reference. This is a new page.

### Resources
- VBA Content Specs listed in #13096
- [Sketch file](https://www.sketch.com/s/891d33ae-152d-471c-ab5d-9aedf89cf6ff)

## Acceptance Criteria
- [ ] Query is aligned with all the sections in the VBA Facility Content Specs XLS in the Google Doc listed in #13096 
- [ ] Tests are identified for the page that is built around this query and added to the subsequent ticket #14941.

## Team
Please check the team(s) that will do this work.

- [ ] CMS Team
- [ ] Public Websites
- [X] Facilities
- [ ] User support
- [ ] Accelerated Publishing

**Comment by jilladams** [comment]
Could get unblocked mid sprint 92 by CMS work

**Comment by xiongjaneg** [comment]
GraphQL has a test on the CMS side to make sure that tests don't fail.

Do we want end to end testing or do we want testing for this content type? There may be existing tests that could be leveraged.

**Comment by xiongjaneg** [comment]
Is there a GraphQL playground? That could reduce some of the barriers and research on this.
It exists but it's not quite a 1 to 1 code. There is an explorer on staging and demo environments [link needed].

**Comment by jilladams** [comment]
From planning: 
* Intent here is to get FE query building moving without blocking the entire FE effort on completing all specs / Drupal skeleton builds. So: there will be components of the design that are _not_ yet built and available. That may add a little effort here, for finding data points that don't exist yet and realizing that after the search. That's ok. 
* This is a try approach, and if this is burdensome / it becomes obviously helpful to wait til more data is available, we can aggregate more tickets for next effort.

**Comment by maxx1128** [comment]
I'm saving some notes on getting a GraphQL query working in the explorer for myself and future developers.

1. Find the type of content you want to query on `https://staging.cms.va.gov/admin/content-models/content`. Click "manage fields" for it, and copy the second to last slug in the resulting page URL. In this case, the URL is `https://staging.cms.va.gov/admin/structure/types/manage/vba_facility/fields`, and the slug I'm copying is `vba_facility`. This is for the `type` field.
    * Keep this page open, as it lists available fields for the query.
3. Go to `https://staging.cms.va.gov/graphql/explorer` and use this starting query template in the explorer. Paste the slug from the last step in TYPE below.

```graphql
query RegionalVetCenterQuery($onlyPublishedContent: Boolean!) {
  nodeQuery(
    limit: 20
    offset: 0
    filter: {
      conditions: [
        {field: "status", value: ["1"], enabled: $onlyPublishedContent}, 
        {field: "type", value: [<TYPE>]}
      ]
    }
  ) {
    entities {
      # Query details go here
  }
}
```

4. In the `entities` part of the query, add any available fields. They can be found in the URL from step one that lists the fields and the "explorer" sidebar on the GraphQL Explorer page.
5. Add the below code snippet to "Query Variables." If this query is for new or developing content that has not yet been published, it may need to be set to `false`.

```json
{
  "onlyPublishedContent": true
}
```

6. Run the query!

Below is an example of the working query I developed for the VBA Regional Facilities.

```graphql
query RegionalVetCenterQuery($onlyPublishedContent: Boolean!) {
  nodeQuery(
    limit: 20
    offset: 0
    filter: {
      conditions: [
        {field: "status", value: ["1"], enabled: $onlyPublishedContent}, 
        {field: "type", value: ["vba_facility"]}
      ]
    }
  ) {
    entities {
      entityId
      entityUrl {
        path
        routed
      }
      entityMetatags {
        __typename
        key
        value
      }
      entityBundle
      entityLabel
      ... on NodeVbaFacility {
        title
        changed
        fieldIntroText
        fieldFacilityLocatorApiId
        fieldOperatingStatusFacility
        fieldOperatingStatusMoreInfo
        fieldPhoneNumber
        fieldAddress {
          addressLine1
          addressLine2
          countryCode
          locality
          postalCode
          administrativeArea
        }
        fieldGeolocation {
          lat
          lon
        }
        fieldMedia {
          entity {
            ... on MediaImage {
              image {
                alt
                title
                derivative(style: _32MEDIUMTHUMBNAIL) {
                  url
                  width
                  height
                }
              }
            }
          }
        }
        reverseFieldOfficeNode(
          limit: 500
          filter: {conditions: [{field: "type", value: ["vet_center_locations_list"]}]}
        ) {
          entities {
            ... on NodeVetCenterLocationsList {
              entityUrl {
                path
                routed
              }
            }
          }
        }
        fieldOfficeHours {
          day
          starthours
          endhours
          comment
        }
      }
    }
  }
}
```

**Comment by swirtSJW** [comment]
But not 'RegionalVetCenterQuery'   want something like 'RegionalVBAQuery'

**Comment by jilladams** [comment]
@maxx1128 anything left here to close this out for end of sprint?

**Comment by maxx1128** [comment]
> @maxx1128 anything left here to close this out for end of sprint? 

@jilladams this pull request only needs one more review from the cms infrastructure team. If that's not a blocker for merge, then it can be closed out.

**Comment by jilladams** [comment]
Ah! perfect, thx. Pinged them on PR, and maybe worth following up in Slack if no one responds tomorrow to indicate whether they plan to review.

**Comment by jilladams** [comment]
Merged, closeable?
