### ISSUE TITLE
Update the VBA Facility content type query to add banner fields

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#14947]
## Description or Additional Context 
Update the VBA Facility content type query to add banner fields #13811 

Drupal work in #14700 

[VBA banners in Figma](https://www.figma.com/file/aKdT4weNNthDxb3r6MolEh/VBA-Content-Specs?type=design&node-id=362-770&mode=design&t=nDtoUe3Zy6ab2Tar-0)

## Acceptance Criteria
- [x] banner related fields on VBA Facility content type are added to the existing VBA query.

## Team
Please check the team(s) that will do this work.

- [ ] CMS Team
- [ ] Public Websites
- [X] Facilities
- [ ] User support
- [ ] Accelerated Publishing

**Comment by swirtSJW** [comment]
This is not a separate query.  This is an addition to the existing VBA query.

**Comment by jilladams** [comment]
For end of sprint: In PR, changes requested in code review.

**Comment by eselkin** [comment]
I made the changes. I think I reapproved. If not, I will right now.

**Comment by xiongjaneg** [comment]
Waiting to see if the failed test passes.

**Comment by eselkin** [comment]
Tests passed, merged
