### ISSUE TITLE
PAW: Implement checkbox and radio button validation

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#14952]
### User story

**AS A** Veteran
**I WANT** to be alerted clearly when I have not provided a required response to a question
**SO THAT** I can continue with minimal cognitive difficulty.

### Engineering notes / background

- Note that checkbox validation was simplified to simply requiring a response
- Designs in [Figma](https://www.sketch.com/s/2bf4405b-5cc4-4672-88fb-d215abdf3b0d/p/92B8759D-A5CA-4C99-A939-0539F5241490/canvas) – see Form Validation tab 

## Acceptance criteria

>Consider
> - Design / Accessibility reviews
> - Collab cycle requirements
> - Device sizes (mobile first)
> - Documentation updates / Change management
< - [Content model documentation](https://prod.cms.va.gov/admin/structure/cm_document)
> - Testing notes

- [x] Validation occurs on all questions
- [x] Tests implemented per plan
- [x] Design review
- [ ] PM review

**Comment by thejordanwood** [comment]
@randimays This has design approval!

**Comment by randimays** [comment]
Holding the ticket until Agent Orange questions are ready so we can also validate the error messaging for checkboxes.

**Comment by randimays** [comment]
Jordan approved the validation for checkbox error messages. [Slack thread](https://dsva.slack.com/archives/C52CL1PKQ/p1695829810854549?thread_ts=1695821708.742609&cid=C52CL1PKQ). Closing!

**Comment by randimays** [comment]
Validated in staging. Closing!
