### ISSUE TITLE
I.L.: Redirect old Teamsites URL to new IL tool on VAgov

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#14964]
### User story

**AS A** Veteran
**I WANT** to be redirected to the new tool from the old URL
**SO THAT** I get the modernized VAgov experience.

### Engineering notes / background

IA team required this redirect post-launch in the [IA design doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/information-architecture/ia-design-docs/income-limits.md#redirects-). 

Timing does not need to be immediate, the next devops repo release post-launch is fine, per this discussion in the [IA intake ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/51132#issuecomment-1684283128).

## Acceptance criteria

- [x] Redirect in place:
  - Old url: `http://www.va.gov/healthbenefits/annual_income_limits_health_benefits.asp`
  - New url: `http://www.va.gov/health-care/income-limits`
- [x] Request OOB deploy in #vfs-platform-support
- [ ] Verify the redirect in prod

**Comment by randimays** [comment]
PR is up: https://github.com/department-of-veterans-affairs/devops/pull/13390

Holding for final go-ahead.

**Comment by randimays** [comment]
This has been merged, but not deployed to prod. Will require OOB, and waiting for the green light on that.

**Comment by jilladams** [comment]
http://www.va.gov/healthbenefits/annual_income_limits_health_benefits.asp is not redirecting to the new tool as of today's deploy. 

Originally I thought we might be in the weird hinterland of subdomain redirects (e.g. [Case 4- Page-level cross-domain redirects from subdomains to va.gov](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/redirect-implementation-strategy.md#4-page-level-cross-domain-redirects-from-subdomains-subdomainvagov-to-wwwvagov), where we are redirecting a TeamSite page.)

 BUT: no: there are plenty of examples in https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/revproxy-vagov/vars/redirects.yml#L3 of `va.gov/healthbenefits` asp paths being redirected this way. 

So: let's give it a day or two, and maybe the TeamSites / DNS servers will do their thing overnight. 🤷‍♀️

**Comment by chriskim2311** [comment]
@jilladams Just checked again and it is redirecting :+1:

**Comment by randimays** [comment]
Seems like this deploy took much longer to propagate than anticipated. Just verified - we're good to go! 🎉
