### ISSUE TITLE
Launch Mobile App Banner

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#14967]
### User story

**AS A** Veteran using iOS Safari
**I WANT** you to launch the mobile app promo banners
**SO THAT** I can be advised of functionality that would be better on the mobile app.

### Engineering notes / background
 Staging env check is a code change.

## Acceptance criteria

- [x] Ensured [Collab Cycle ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/60829) is closed
- [x] Enable the FEATURE_MOBILE_APP_PROMO CMS Feature flag in prod
- [x] Staging environment check is removed
- [ ] Verify in Prod

**Comment by wesrowe** [comment]
Staging Review collab cycle for the mobile app promo banner closed without findings!! We can launch today and get analytics for all of September!

**Comment by randimays** [comment]
We missed the prod deploy today due to a CI issue in content-build. Holding the merge/deploy for Tuesday, 9/5.

**Comment by jilladams** [comment]
https://dsva.slack.com/archives/C52CL1PKQ/p1693947954966689

Also verified: 
![IMG_3356](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/85581471/9a6656bc-92df-40e3-b7ab-8f0b7ed80dd3)
