### ISSUE TITLE
Homepage: Redirect /new-home-page to actual homepage

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#14960]
### User story

**AS A** Veteran
**I WANT** to be redirected from /new-home-page to /
**SO THAT** I don't continue to use a homepage that is not meant for continuing use.

### Engineering notes / background

Several months after the full launch of the new VA homepage, thousands of visitors every DAY are still visiting the version of the page at /new-home-page.

## Acceptance criteria

- [ ] When attempting to load the url `www.va.gov/new-home-page` I am automatically redirected to `www.va.gov/`
  - [x] This redirect is of a temporary nature, so that we could use /new-home-page for experiments in the future

**Comment by wesrowe** [comment]
Randi notes that there are slack threads on this topic, Facilities area.

**Comment by randimays** [comment]
This will deploy to production tomorrow morning.

**Comment by jilladams** [comment]
@randimays @wesrowe https://www.va.gov/new-home-page/ still loads - I know there was a double back at some point and I think the URL here was wrong in ticket to begin?

**Comment by jilladams** [comment]
(corrected the AC to use new-home-page)

**Comment by randimays** [comment]
@jilladams The AC was wrong in the ticket and I didn't catch the mistake when I added the code. [See here for Slack thread](https://dsva.slack.com/archives/C52CL1PKQ/p1693411012306049?thread_ts=1693410981.932809&cid=C52CL1PKQ). I have the correct code merged, but we were thinking that the Income Limits redirect was going to happen this week and take this to prod with it. At this rate it'll be going on Wednesday morning anyway.

Speaking of which - are we going to be ok to have the Income Limits redirect go to production on Wednesday?

**Comment by jilladams** [comment]
Yep!

**Comment by jilladams** [comment]
va.gov/new-home-page is now redirecting to https://www.va.gov/.
