### ISSUE TITLE
GitHub Repository Code Scanning Software Is Out Of Date

### ISSUE THREAD

**Issue by veterans-affairs-code-scanning** [department-of-veterans-affairs/va.gov-cms#14983]
<p>
The Department of Veterans Affairs (VA) Office of Information Security (OIS) has detected that the CodeQL code scanning software that is being used by the following repository is out of date:
</p>
<ul>
    <li>
        <a href="https://github.com/department-of-veterans-affairs/va.gov-cms" target="_blank">va.gov-cms</a>
    </li>
</ul>
<p>
Automation has analyzed your repository and identified your most recent CodeQL scans, for one or more of your supported languages, are using the following CodeQL version: 2.14.1
</p>
<p>
The most recent version of the CodeQL software, and the complete, most recent set of CodeQL language packs must be used when scanning code.
</p>
<p>
The steps that you will need to take to update the CodeQL code scanning software for the above repository to the latest release are provided here:
</p>
<ul>
    <li>
       <a href="https://department-of-veterans-affairs.github.io/ois-swa-wiki/docs/ghas/codeql-usage/update-jenkins-pipeline/#updating-codeql-cli-bundle" target="_blank">Updating CodeQL CLI Bundle</a>
    </li>
</ul>
<p>
To request technical support:
</p>
<ul>
    <li>
        <a href="https://outlook.office365.com/owa/calendar/OISSoftwareAssurance@DVAGOV.onmicrosoft.com/bookings/" target="_blank">Please book a meeting with OIS ISO SAVD Software Assurance</a>
    </li>
</ul>
<p>
    <img src="https://department-of-veterans-affairs.github.io/ois-swa-wiki/assets/images/OIT_logo.png" alt="VA OIT Logo">
</p>

**Comment by ndouglas** [comment]
See https://github.com/orgs/department-of-veterans-affairs/discussions/2
