### ISSUE TITLE
Change prod to use prod endpoint for govdelivery

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#1498]
Prod is still using govdelivery's staging endpoint.  This needs to be converted to use the prod endpoint.

- [x] Get prod account for govdelivery that is not based on Jeff Barnes account.
- [x] Verify with Jeff Barnes that this switch should be made.

Create an issue for devops / core team to 
- [ ] Validate that the endpoint and password work.
- [ ] Implement the change in credstash

**Comment by swirtSJW** [comment]
https://github.com/department-of-veterans-affairs/devops/pull/6737

**Comment by ElijahLynn** [comment]
I think we were also waiting on a service account email address we could use for password resets at GovDelivery, since our cms-admin@va.gov email is a distribution list that cannot accept external email and we need one that can accept external email (password resets).

**Comment by swirtSJW** [comment]
@jefflbrauer Any action on this?

**Comment by cmaeng** [comment]
Meeting scheduled with @JeffBarnesUSDS on 2/5/21 to see if we can tweak the GovDelivery account settings. We will also be chasing down trying to set up a generic service email to tie this to instead of using someone's personal account.

**Comment by ElijahLynn** [comment]
Also, the current integration with GovDelivery stage is not working anymore, which would normally send an email to <10 users like myself, which I did not get anything.

**Comment by cmaeng** [comment]
GovDelivery prod access achieved today for the CMS team. Based on today's conversation with Barnes, further work will be split out and tracked in an epic to:

- Document our current processes and configurations and how they might change
- Explore creation of a va.gov service account
- Complete technical tasks / configurations to ensure that GovDelivery is working correctly
