### ISSUE TITLE
All generated pages should have basic development information available in their head

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#14996]
## Requirements
All Next.js pages should have basic information about the content used to build them available, so that an engineer or other CMS worker can use that information to understand the content better and diagnose issues.

```[tasklist]
### Acceptance criteria
- [ ] The following information is available for any given page: CMS entity ID, if there is one; ResourceType, if there is one; intended url path of the page
```

## Background & implementation details
Content Build currently does this by putting this information in a comment in the `head`, for example:

```
<!--
--
  | layout: news_story.drupal.liquid
  | path: lovell-federal-health-care-tricare/stories/fleet-medicine-provides-comprehensive-care-to-navy-recruits
  | entityId: 56142
  | -->

```

```[tasklist]
### Implementation tasks
- [ ] Use this if it helps you or feel free to delete.
```

**Comment by tjheffner** [comment]
I would consider adding `uuid: ` as a piece of information here too. will be useful for checking the jsonapi of a given page (`/jsonapi/node/{resourceType}/{uuid}`
