### ISSUE TITLE
Redirect Request for Burial Form 530

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-cms#15002]
# Time sensitive: Blocked on approval from @steele-lm to implement the redirect. Once greenlit, OOB deploy may be required.
### Type of request
- [x] We are **temporarily** taking down the Application for Burial Benefits form (530) and need to redirect users who may access urls within the form flow to the "How to Apply" page (complete redirect section)
   - The digital burial form (530) is being temporarily deactivated until it can be updated to align with the paper form. These redirects will need to be removed once the new form is available.
   - The release of the redirects should be coordinated with the release of the new form summary pages we will be providing to users caught with in-progress claims.
- [ ] We are changing the URL of an existing page (complete redirect section)
- [ ] We need a custom vanity URL (complete vanity URL section)

### Implementation date
When does this request need to be live?
Choose one:
- [x] On a specific date, connected to the release of the updated form summary page. **1-2 weeks, coordinate release with @steele-lm**
- [ ] Any day prior to a deadline/latest possible date. **DEADLINE:** 
- [ ] Any day after an earliest possible date. **EARLIEST DATE:**
- [ ] During a specific date range: ***EARLIEST DATE TO LATEST DATE:***
- [ ] No hard timing requirements, publish when possible.

### Redirects
Current URL  |  Redirect Destination or New URL
---  |  ---
https://www.va.gov/burials-and-memorials/application/530/claimant-information | https://www.va.gov/burials-memorials/veterans-burial-allowance/
https://www.va.gov/burials-and-memorials/application/530/veteran-information | https://www.va.gov/burials-memorials/veterans-burial-allowance/
https://www.va.gov/burials-and-memorials/application/530/veteran-information/burial | https://www.va.gov/burials-memorials/veterans-burial-allowance/
https://www.va.gov/burials-and-memorials/application/530/military-history/service-periods | https://www.va.gov/burials-memorials/veterans-burial-allowance/
https://www.va.gov/burials-and-memorials/application/530/military-history/previous-names | https://www.va.gov/burials-memorials/veterans-burial-allowance/
https://www.va.gov/burials-and-memorials/application/530/benefits/selection | https://www.va.gov/burials-memorials/veterans-burial-allowance/
https://www.va.gov/burials-and-memorials/application/530/benefits/burial-allowance | https://www.va.gov/burials-memorials/veterans-burial-allowance/
https://www.va.gov/burials-and-memorials/application/530/benefits/plot-allowance | https://www.va.gov/burials-memorials/veterans-burial-allowance/
https://www.va.gov/burials-and-memorials/application/530/claimant-contact-information | https://www.va.gov/burials-memorials/veterans-burial-allowance/
https://www.va.gov/burials-and-memorials/application/530/documents | https://www.va.gov/burials-memorials/veterans-burial-allowance/
https://www.va.gov/burials-and-memorials/application/530/introduction (added a forward slash between 530 and intro (JM)) | https://www.va.gov/burials-memorials/veterans-burial-allowance/

Note: If user lands on review page, they should not be redirected.

[527 and 530 form links.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/12442739/527.and.530.form.links.xlsx), use 530 tab - moved the original spreadsheet here so this documentation remains in the original ticket. Pulled in URLs from spreadsheet (JM 8/28/23)

**Link to campaign landing page request issue:**

### Process, Roles and Responsibilities
- [x] Requesting team: Above information is provided
- [x] Requesting team: All appropriate VA stakeholders are notified as appropriate
- [x] IA: Request is vetted and documented and implementation plan is clear 
- [x] IA: Request is assigned to appropriate team for implementation 
- [ ] Implementation team: Work is complete
- [ ] Implementation team: Validated in production
- [ ] Requesting team: Validates everything is correct in production and closes ticket

**Comment by fred-khoury-oddball** [comment]
Hello all, I am working on the application where these redirects will be occurring. We plan on putting the current Burial Application behind a feature flag. This is so once we fix the form we can roll it back out incrementally. I this there could be some potential issues with this plan though. I was wondering if the redirects can be placed behind the feature flag as well. The potential issue im thinking about is:
- We have disabled the current form and the redirects are in place
- We make updates to the form and decide to roll it back out to 20% of Veterans
- They try and navigate to one of the urls that are on the redirect list
- They feature flag is set to allow them to view the old form
- They hit the url for the old form and are redirected back to the how to apply page

I am not sure of what the best solution for this scenario looks like and was wondering if you experience with something similar. This will also apply to the [request for the pension form](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15012) as well.

**Comment by jilladams** [comment]
Redirects can't be controlled by feature flags, as far as I'm aware. (They take place in a different codebase, at the server level, not within the front-end or vets-api code.)

They can be removed, if needed, in order to revert to the old behavior. The process, for awareness:

1. Once we implement a redirect, it will be added to https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/revproxy-vagov/vars/redirects.yml. 
2. If they need to be rolled back: 
  * We'll remove them from that file
  * We'll request a deployment of the change - that will take 1-3hrs, depending on the Platform support team's help to deploy / time of day, etc.
  * It can then take anywhere from an hour to several hours to propagate (typically it's pretty quick, but it's not something we can control if it happens slowly). 

The same will be true to roll it forward again. Worth keeping in mind as you plan. If we should hold off on implementing this redirect in light of that, just let us know. (We're already waiting for a greenlight.)

**Comment by fred-khoury-oddball** [comment]
Thank you so much this is great!
@jilladams

**Comment by steele-lm** [comment]
@chriskim2311 Rescinding this request for redirects. @fred-khoury-oddball is going to move them into a javascript solution, so we can toggle them on/off with the feature flag for the UI elements.

**Comment by chriskim2311** [comment]
@fred-khoury-oddball Can you tag me in the PR for this JS solution. Would like to learn your approach for potential future reference thanks!
