### ISSUE TITLE
PAW: draft test plan artifact

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#15001]
### User story

**AS A** PM/PO/Eng
**I WANT** to document our QA approach before we start implementing
**SO THAT** we have a clear hypothesis for a high-quality, repeatable approach and have a polished document ready for Collab Cycle when the time comes.

### Engineering notes / background

We can use the [Income Limits test plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/income-limits-app/engineering/testing-qa.md) as a jumping off point. (

## Acceptance criteria

>Consider
> - Design / Accessibility reviews
> - Collab cycle requirements
> - Device sizes (mobile first)
> - Documentation updates / Change management
< - [Content model documentation](https://prod.cms.va.gov/admin/structure/cm_document)
> - Testing notes

- [ ] Drafted test plan in the PAW product folder: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/pact-act-wizard/engineering/
- [ ] Got review from another Engineer, PM, DM

**Comment by wesrowe** [comment]
@chriskim2311 @randimays – have a look at this to pre-refine before sprint planning, if possible

**Comment by jilladams** [comment]
From planning: after development, we may need to revisit / revise the plan based on actuals.

**Comment by randimays** [comment]
Jill, Wes and Chris reviewed/approved. Merged, and closing!
