### ISSUE TITLE
Review Dependabot Alerts (Sprint 92)

### ISSUE THREAD

**Issue by productmike** [department-of-veterans-affairs/va.gov-cms#15031]
## User Story
As a DevSecOps engineer, I want to ensure that I'm consistently reviewing and evaluating production alerts so that existing vulnerabilities are assessed and associate risks mitigated.

# Acceptance Criteria
- [x] Indicate the alerts reviewed in this ticket. 
- [x] Track evaluations in this ticket.
- [x] Review high impacting alerts with PO, PM for work to be prioritized and tickets opened.

**Comment by ndouglas** [comment]
A single issue, which I've opened #15072 to address.
