### ISSUE TITLE
Link to Health chat from VAMC pages

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-cms#15037]
## Value to Veterans
Veterans will know and understand how to use VA health chat to contact their healthcare team in various situations and where to find the information on the health care system pages. 

## Headlines
**Business stakeholder** -**IVE, VHA, Health portfolio, stakeholders for each communication method***
**OCTO owner -** Michelle Middaugh
**Is request tracked to an event or Congressional deadline? -**  No

## Details
**Who is the primary user?**
- Veterans and beneficiaries 

**What are the user goals for the project/page/product?**
- Veterans have an intuitive way to access Health Chat from contextually relevant points in their digital health journey.

## Description
The Veterans Health Administration Office of Integrated Veteran Care (IVC) is invested in helping Veterans understand and have access to all the “ways to get care” especially same day care, access for  rural Veterans (i.e. virtual services), and communication methods which are faster than the long wait times associated with phone numbers (i.e. chat or secure messaging). 

We have been asked to support a pilot for Health chat by including it on VAMC pages for sites to be selected by the Office of Community care. 

> Sites will be selected by OCC to reflect sites that can definitely use Health Chat, so we do not further frustrate Veterans who cannot. Considerations include
> - Places where most of the HC functionality is rolled out
> - Places where some, but not all of the HC functionality is rolled out (demonstrate need)
> - Places where we are sure HC can handle the load
> - Places where we are NOT sure HC can handle the load

## Background
- The Facilities team did discovery into the multiple methods of contacting the VA to Veterans in the summer of 2021. At the time, the methods included the usual suspects (phone, mental health numbers and the VCL) plus VA health chat, Secure messaging, and VA health connect. We didn’t want to just randomly add them to the already crowded and confusing “Contact us” pages for VA health facilities or to the top-level facility contact information without some sort of context for which method to use in what scenario or understanding of how and where Veterans would expect to find the information. 
   - [Link to recommendations from health chat discovery ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/medical-centers/discovery/health-chat-discovery.md#recommendations)
   - A [research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/facility-locator/research/user-research/VAMC-communications-methods/Research-Plan.md) and [conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/facility-locator/research/user-research/VAMC-communications-methods/Conversation-Guide.md) were created before this effort was parked (for reasons which elude me now.)
   - VA Health Connect, also known as clinical contact centers, connects the Veteran to the VA by phone. The VA health connect number is already displayed on the relevant VAMC facility pages and in Facility Locator for the few VISNs which have rolled out (and notified us of their roll-out). The number is maintained in CMS. 
- This effort may be somewhat relevant to the work we're doing on how to present modalities in service accordions as part of our VBA work, expecting it to shape the approach for VAMCs in the future. It isn’t yet clear if one of more of these might fall into the “modality” category (other “modalities” in the mix are virtual/telehealth appointments, home-based care, phone appointments, etc.)

## Objectives and key results 
**Goal:** Give Veterans a way to access Health Chat from contextually relevant points in their digital health journey.
**Possible OKRS:** Traffic to HC over {insert appropriate time frame here}, feedback from Veterans, and/or feedback from staff supporting the app.

**Comment by jilladams** [comment]
VA Health connect already exists on a small set of VAMCs: https://www.va.gov/bay-pines-health-care/
![Screenshot 2023-10-17 at 12 17 18 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/85581471/9b905b71-2b81-4f03-9fe5-9a77e437dfd4)

**Comment by jilladams** [comment]
## Health Chat
Health Chat has 4 core functions that may or may not be rolled out at the same time: 
1. Rx
2. Appointments
3. Urgent Care
4. Nursing

May be used in separate locations for each functionality. Separate than Chatbot. 

Health Chat is being built, under Lauren Alexanderson's Healthcare teams, but we don't know if it's built in house or through a 3rd party vendor.

### Product teams / stakeholders
AskVA
Hotlines
Medical CTA widget owners (eventually MHVonVA)

### Flow / entry points
Michelle has a Mural started we can reference / expand on.

## Next steps for UX
* Create a UX discovery ticket -- Jordan and Amanda (design / research) will both need to wrap heads around what exists / what should be coming / how to think about it. They can cowork and present findings. - @xiongjaneg

**Comment by mmiddaugh** [comment]
Draft KB article is [here](https://prod.cms.va.gov/help/vamc/how-do-i-help-veterans-learn-about-va-health-chat)

**Comment by mmiddaugh** [comment]
**Update 12.11.2023**
- Coordinating with VHA DM
- Due to inconsistent national roll-out, we are unable to use centralized content so VAMC editors will be asked to add a detail page about how health chat can be used at their facility and links to the page from spotlights - _pending final input from CAIA_
- Editors will be given exact language and direction but  their time frame for implementing guidance may vary

**Comment by mmiddaugh** [comment]
Update 2.7.2024
Paused pending re-engagement with VA health connect team

**Comment by mmiddaugh** [comment]
**Update 3.9.2024**
- Preparing to implement links to combined campaign landing page from within Manage your healthcare online box on VAMC system pages (chosen as centralized content option which will not require editor effort)
- Will track analytics for clickthrough compared to locally created content
- Planning Veteran research in April 2024

Related: [Support for VA health connect on VAMC pages #897](https://github.com/department-of-veterans-affairs/digital-experience-products/issues/897)

**Comment by DanielleThierryUSDSVA** [comment]
@mmiddaugh I moved this date to April 30 for now. Feel free to shift further!

**Comment by jilladams** [comment]
This quarterly priority is temporarily on pause for program level communication alignment.

**Comment by mmiddaugh** [comment]
**Update 4.22.2024**
Blocked per Jenny HL's request for program team alignment and comms strategy

**Comment by mmiddaugh** [comment]
**Update 6.7.2024**
- Still blocked pending program team alignment and comms strategy

**Comment by mmiddaugh** [comment]
Update 7.10.2024

Links to download VA health chat and learn more about communication methods (including VA health connect) added to Manage your health online box for VA health systems
