### ISSUE TITLE
Internal discovery for VA Police Transparency (WIP)

### ISSUE THREAD

**Issue by davidmpickett** [department-of-veterans-affairs/va.gov-cms#15042]
## Discovery 

Start here --> [Initiative Brief: VA police transparency](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/medical-centers/police/readme.md#initiative-brief-va-police-transparency-wip)

**Additional suggested reading**
- [Story about the relationship between New Jersey law enforcement departments and the Wilmington VA Medical Center Police in a Veterans Response Team collaboration](https://www.va.gov/wilmington-health-care/stories/veteransresponseteam/)
- [Quick action by Wilmington VA Police saves Veteran](https://www.va.gov/wilmington-health-care/stories/quick-action-by-wilmington-va-police-saves-veteran)
- [K9 story]( https://www.va.gov/boston-health-care/stories/meet-belle)
- [Police officer recognized for assisting Veteran in crisis](https://www.va.gov/tennessee-valley-health-care/stories/police-officer-recognized-for-assisting-veteran-in-crisis/)
- [Veteran Mental Health Evaluation Team at VA Greater Los Angeles Healthcare System](https://www.va.gov/greater-los-angeles-health-care/stories/va-police-social-workers-team-up-to-prevent-veteran-suicide/) 
- [Press release about the impact on health care utilization](https://www.va.gov/wilmington-health-care/news-releases/va-and-law-enforcement-collaboration-leads-to-increase-in-health-care-utilization-study-finds) 
- Example VA Police detail pages
  - [VA Oklahoma City health care](https://www.va.gov/oklahoma-city-health-care/programs/va-police/)
  - [VA Northern California health care](https://www.va.gov/northern-california-health-care/programs/va-police/) (also linked from Sacramento VAMC's Prepare for your visit “Security” accordion)

**Comment by mmiddaugh** [comment]
@xiongjaneg I'm not sure this is still needed - should we close it?

**Comment by xiongjaneg** [comment]
@mmiddaugh Agreed, I think this was a placeholder until we got the other discovery tickets going. Closing.

**Comment by xiongjaneg** [comment]
replaced by #15041 and #15040
