### ISSUE TITLE
SPIKE: Drupal proposal for managing VAMC System Banner Alert inline editor on VAMC System Operating Status

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#15047]
## Description or Additional Context 

- [Reported defect](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13543): If an un-published VAMC System Banner Alert is still linked from the system VAMC System Operating Status, the node will not allow Content Publishers to save their changes.
- Public Websites [recently dealt with a similar issue](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13543#issuecomment-1654083902) around inline editors. Might be a useful reference.
- Previous engineering notes in #14820 comments

### To Reproduce

- Log in on Staging as a Content Publisher and go to your assigned system's VAMC System Operating Status node (i.e. /pittsburgh-health-care/operating-status )
- Create a new VAMC System Banner Alert or select the name of an existing VAMC System Banner Alert. Make sure the alert is published.
- Find the VAMC System Banner Alert via the Content page and un-publish it
- Go back to the VAMC System Operating Status node
- Make sure the un-published VAMC System Banner Alert is still listed within the "System-wide alerts" section of the page. 
- Attempt to make other changes to the page. 
- You will not be able to save and publish while the un-published Banner Alerts are still linked

## Acceptance Criteria
- [x] Recommendation is made about removing the entity reference field (and inline editor) in VAMC System Operating Status.
- [x] Roadmap is provided to the front end and shared in ticket #15057  [Done here](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15057#issuecomment-1736631747) 

## Team
Please check the team(s) that will do this work.

- [ ] CMS Team
- [ ] Public Websites
- [X] Facilities
- [ ] User support
- [ ] Accelerated Publishing

**Comment by xiongjaneg** [comment]
The intent of the Remove button in the inline editor was so that a local editor could remove their facility or system from a multi-system banner.

**Comment by jilladams** [comment]
From refinement: 
* Right now you can specify the entity relationship between VAMC System Banner Alert and VAMC System Operating status, going in 2 directions: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14820#issuecomment-1699919192
  * Specifying on the Banner Alert works. Unchecking works. However: unchecking on the Banner alert will _not_ remove from the VAMC System Operating status entity reference -- they will continue to rack up, and must be manually managed.
* Drupal proposals need to take this into account. Should also consider the GraphQL implications for how each proposal will be able to tell the FE which Banner Alert to show on which System operating status.
* @xiongjaneg to create a FE ticket blocked on this ticket, to follow it. The FE ticket should review the Drupal proposals and consider the impact / propose the best path in the FE. The main thing to consider will maybe be: depending on how entity references are managed in Drupal, and the proposed way to manage the queries. If the Drupal findings are clear and the GraphQL logic is easy, the FE ticket may be small, or no-op, tbd.

**Comment by swirtSJW** [comment]
## Technical solution
1. Remove corresponding entity reference `banner_alert_and_vamc_operating_status` (/admin/config/content/cer)
2. Search codebase and them to remove any reference to `field_banner_alert`.  Untangle as necessary.
3. Remove the field `field_banner_alert` from `vamc_operating_status_and_alerts` content type
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5752113/e90c5e43-f4a0-4498-8b1d-81f77cbc0be9)
4.  No existing KBs seem to reference the inline entity form so no changes to existing KB should be needed.
5. Add KB article about how to remove a banner from your system that was placed by someone at the multi-system level.
6. FE alter logic to not use direct entity reference `vamc_operating_status_and_alerts -> field_banner_alert` but instead alter query and template to use  reverse entity reference  `full_width_banner_alert -> field_banner_alert_vamcs`

**Comment by swirtSJW** [comment]
@xiongjaneg Calling this done.
