### ISSUE TITLE
CMS Breadcrumb data is available via JSON:API

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#15055]
## Requirements

Breadcrumb data that is owned by the CMS should be made available via JSON:API, so that it can be leveraged to build breadcrumbs on AP pages, which help Veterans to navigate VA.gov.

```[tasklist]
### Acceptance criteria
- [x] Breadcrumb data is available in the JSON:API response for a node
- [x] JSON:API breadcrumb data functionally matches GraphQL query data for equivalent queries/node types
- [x] Installation of the module does not alter the editor experience in any way
```

## Background & implementation details

Drupal does not do this natively; will need to be using a contrib module. Work done in https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14741 identified the [computed_breadcrumbs](https://www.drupal.org/project/computed_breadcrumbs) module as a likely candidate. 

```[tasklist]
### Implementation tasks
- [ ] Use this if it helps you or feel free to delete.
```

**Comment by schiavo** [comment]
computed_breadcrumbs provides breadcrumbs in response for a node
There is no change to the UI
Confirming that the data returned matches what is currently generated by GraphQL

**Comment by schiavo** [comment]
GraphQL Returns the same data for the previous example (nid = 761). It looks like processing during build removes the redundant breadcrumb before the title breadcrumb that does not have a url.  

![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/7717261/c4740a53-5d15-4511-b963-b412f5b5f37a)

**Comment by schiavo** [comment]
I've @swirtSJW that breadcrumbs go through processing on build. It looks like we're good with this setup. We will need to implement similar breadcrumb processing on build. It's also been suggested that we look into the possibility of sharing processing that happens on build so that legacy and next can use the same processing and there's only one set of processing code to maintain.

**Comment by schiavo** [comment]
From page.js
Breadcrumb generated based on path

`// Generate breadcrumbs from drupal page path
function generateBreadCrumbs(pathString) {
  const pathArray = pathString.split('/');
  const entityUrlObj = createEntityUrlObj(pathString);
  let previous = '';
  let trimmedValue;

  for (const value of pathArray) {
    trimmedValue = _.trim(value, '/');
    if (value) {
      const dehandlized =
        value === 'pittsburgh-health-care'
          ? 'VA Pittsburgh health care'
          : value.charAt(0).toUpperCase() + value.replace(/-/g, ' ').slice(1);
      entityUrlObj.breadcrumb.push({
        url: {
          path: `${previous}${value}`,
          routed: true,
        },
        text: dehandlized,
      });
    }
    previous += `${trimmedValue}/`;
  }
  return entityUrlObj;
}`

**Comment by schiavo** [comment]
computed_breadcrumbs shows a breadcrumb field in each content types manage display. But the manage display settings need to be saved before we get consistent results.

By doing this we no longer need easy_breadcrumbs which causes the va:test:content-build-gql to fail

**Comment by schiavo** [comment]
Going through each content type to make sure that graphql returns the same results before installing computed_breadcrumbs and testing content to make sure that breadcrumbs are being surfaced as expected.

For example for an event
![Screenshot-20230920131303-2186x1618](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/7717261/fd22082d-c88a-4a8f-abf4-630aeca116b8)

The same event in prod
![Screenshot-20230920131805-1986x702](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/7717261/389ce2a8-618e-4735-86c4-e5ed2a50bdff)

Event in CMS 
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/7717261/833a8e1a-6843-40ee-9aff-d954511e0ee1)

Need to confirm that the title is added in build

**Comment by schiavo** [comment]
Event listing in graphql with computed_breadcrumbs enabled
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/7717261/4df98937-bdc9-469b-95cb-f9396ce02f42)

Graphql returns the same breadcrumbs with computed_breadcrumbs disabled
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/7717261/baeda52b-78d1-4ecf-8d6e-19e5642304b0)

**Comment by schiavo** [comment]
Some content_types are not displayed on the front end as a node. In these cases breadcrumbs are not configured and breadcrumbs are not properly returned within CMS. 
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/7717261/53aea943-fafe-4b31-a05c-44fbba19d6e4)

**Comment by schiavo** [comment]
Testing again with computed_breadcrumbs without easy_breadcrumb. It looks like when a node is not included in a menu json api returns Home -> Node as breadcrumbs.

![Screenshot-20230921121939-1512x1642](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/7717261/b4957dff-785c-47bb-89ed-a68cab1861da)

For content that is associated with a menu correct breadcrumbs are returned
![Screenshot-20230921122146-1490x2032](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/7717261/bf7a8eb5-9b84-4858-ae48-b27fa57a717c)

**Comment by schiavo** [comment]
Another example

No menu selected

![Screenshot-20230921122728-2388x1410](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/7717261/e5db6d37-7c39-4ca0-9311-a937c378e3c2)

result in incomplete breadcrumbs returned in json api

![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/7717261/0fc02474-d6b0-47ec-8455-e12c05acbf7f)

**Comment by schiavo** [comment]
Once easy_breadcrumbs is enable correct breadcrumbs are returned
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/7717261/b104689e-5e50-4f65-b0d6-5224e11ffd52)

**Comment by schiavo** [comment]
Here's an example of front end build generating breadcrumbs for a content type (press_release) not included in the menu.

`const prPage = updateEntityUrlObj(prObj, drupalPagePath, 'News Releases');
  const prPath = prPage.entityUrl.path;
  prPage.regionOrOffice = page.title;
  prPage.entityUrl = generateBreadCrumbs(prPath);

  paginatePages(
    prPage,
    files,
    'allPressReleaseTeasers',
    'press_releases_page.drupal.liquid',
    'news releases',
  );`

**Comment by schiavo** [comment]
Comparison of build with PR and production. So far so good.
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/7717261/18043802-78d4-40b4-b445-bc39babe2b7f)

**Comment by schiavo** [comment]
Breadcrumbs on events listing line up
![Screenshot-20230921131448-3752x1448](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/7717261/5e33ba9d-b091-46f4-8328-3c02d2187478)

**Comment by schiavo** [comment]
Drilling into event. Breadcrumbs line up
![Screenshot-20230921131604-4648x1106](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/7717261/1b2ebeb7-5826-489e-b810-ce114a6781eb)

**Comment by schiavo** [comment]
Locations line up
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/7717261/4dcfb0d2-088b-4c34-94cb-bd0e2f0122f5)

**Comment by schiavo** [comment]
Stories line up
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/7717261/52edbec1-f8eb-4fa5-95dd-4e58fa568e89)

**Comment by schiavo** [comment]
Breadcrumbs in build pass all spot checks
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/7717261/f6b99f15-2433-4913-ab48-a09dc373597e)
