### ISSUE TITLE
Front End review: managing VAMC System Banner Alert inline editor on VAMC System Operating Status 

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#15057]
## Description or Additional Context 

- [Reported defect](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13543): If an un-published VAMC System Banner Alert is still linked from the system VAMC System Operating Status, the node will not allow Content Publishers to save their changes.
- Public Websites [recently dealt with a similar issue](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13543#issuecomment-1654083902) around inline editors. Might be a useful reference.

### To Reproduce

- Log in on Staging as a Content Publisher and go to your assigned system's VAMC System Operating Status node (i.e. /pittsburgh-health-care/operating-status )
- Create a new VAMC System Banner Alert or select the name of an existing VAMC System Banner Alert. Make sure the alert is published.
- Find the VAMC System Banner Alert via the Content page and un-publish it
- Go back to the VAMC System Operating Status node
- Make sure the un-published VAMC System Banner Alert is still listed within the "System-wide alerts" section of the page. 
- Attempt to make other changes to the page. 
- You will not be able to save and publish while the un-published Banner Alerts are still linked

## Acceptance Criteria
- [x] Drupal recommendation and roadmap is reviewed (see #15047)
- [x] Front end recommendation is shared with PO/PM

## Team
Please check the team(s) that will do this work.

- [ ] CMS Team
- [ ] Public Websites
- [X] Facilities
- [ ] User support
- [ ] Accelerated Publishing

**Comment by swirtSJW** [comment]
Here is the  the FE change that needs to be made to clear the way for the CMS changes

- FE alter logic to not use direct entity reference `vamc_operating_status_and_alerts -> field_banner_alert` but instead alter the query and templates to use reverse entity reference `full_width_banner_alert -> field_banner_alert_vamcs` on the vamc_operating_status_and_alerts pages.
- Keep in mind that banners can appear on the entire system or just the main and operating status pages.  This logic should be preserved.
- This change should not go out to prod before the field_banner_alert has been removed from the CMS.  This should be testable in a Tugboat environment pointing to the FE PR.

**Comment by jilladams** [comment]
Noting from chat with Max: if you end up with code changes that are relevant in order to prove out the concept, can put them in a Draft PR and link here, for use when we do the actual FE work post CMS changes.

**Comment by maxx1128** [comment]
I reproduced the bug on my tugboat environment and altered the query and templates as per @swirtSJW's above changes. I'll open a draft pull request for these changes and confirm that it can still be built correctly.

**Comment by maxx1128** [comment]
[I have a draft pull request open now](https://github.com/department-of-veterans-affairs/content-build/pull/1738), and it was a successful build.

**Comment by xiongjaneg** [comment]
@maxx1128 Let's review in pre-refinement so we can check off the last AC, thanks

**Comment by xiongjaneg** [comment]
Tabling inline editor issue for later due to other priorities, will stub tickets as needed
