### ISSUE TITLE
Naked link on Vet center pages

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#15067]
## Describe the defect
On the Vet center pages ([example](https://www.va.gov/reno-vet-center/locations/)), at the bottom, there is a section for "Vet Centers in other areas". Below this heading is the text "You can locate a Vet Center near you by visiting [http://www.va.gov/find-locations.](https://www.va.gov/find-locations)". This is a naked link - a link of just the URL, rather than plain text that is hyperlinked. This is bad for accessibility as assistive technology will announce the full URL making it difficult and frustrating for users to understand.

Can we please change this text to be similar to what was suggested by the CAIA team for VBA?

> Looking for a Vet Center in another area? [Find a Vet Center location](https://www.va.gov/find-locations)

## Screenshots
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/106678594/0813510e-bed7-425b-9d36-069860d89538)

## AC / Expected behavior

- [x] Update link text to Looking for a Vet Center in another area? [Find a Vet Center location](https://www.va.gov/find-locations)
- [x] Accessibility review

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [ ] `Public Websites`
- [x] `Facilities`
- [ ] `User support`
- [ ] `Accelerated Publishing`

**Comment by eselkin** [comment]
@laflannery I think this got accidentally merged despite not getting your review. I did look at it with VoiceOver, but I know that's different.

**Comment by laflannery** [comment]
@eselkin I just took a look, unfortunately there is an `aria-label` on the link that shouldn't be there - that will overwrite the actual link text for screen readers. Also  we should ideally be using the `<va-link>` [component](https://design.va.gov/components/link/#default)

Should this be reopened or should a new ticket be made?

**Comment by eselkin** [comment]
This ticket hasn't closed I'll open a new PR for it now.

**Comment by eselkin** [comment]
@laflannery when [this](https://github.com/department-of-veterans-affairs/content-build/pull/1782) builds on the review instance, it'll have the va-link component.

**Comment by laflannery** [comment]
The Review Instance is giving me a 502 error so I'm not able to retest this.

@jilladams and @xiongjaneg tagging you both for awareness since I know Eli is out today and the sprint is wrapping up

**Comment by eselkin** [comment]
I'm out but I see it. I'm trying to get it up on a tugboat. I guess the content-build builds aren't building.

**Comment by jilladams** [comment]
Also totally fine if this rolls to next sprint due to RI issues. @eselkin don't sweat it while you're out.

**Comment by laflannery** [comment]
Confirmed this is on Prod: [Example page](https://www.va.gov/reno-vet-center/locations/)

![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/106678594/dcfd9ec7-45d6-4109-bb2b-c370f77e6249)
