### ISSUE TITLE
Lovell Health Care pages should generate distinct URLs for Tricare and VA user if both are needed

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#15062]
## Requirements

When a page is part of Lovell Health Care, it should be available at paths specific to Tricare and VA patients, so that these patients are always able to see the version of the page appropriate to them.

```[tasklist]
### Acceptance criteria
- [ ] Lovell Health Care system pages are statically generated with paths for Tricare and for VA users when the page's section is Lovell Health Care (the parent)
- [ ] If the page is assigned to Lovell Tricare or Lovell VA, it should only build for a page for that system
```

## Background & implementation details

content-build or CMS repo has Lovell constants, with the specific nids/tids for the field_administration values.

```[tasklist]
### Implementation tasks
- [ ] Use this if it helps you or feel free to delete.
```

**Comment by timcosgrove** [comment]
content-build or CMS repo: Lovell constants, with the specific nids/tids for the field_administration values.

**Comment by tjheffner** [comment]
https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/docroot/modules/custom/va_gov_lovell/src/LovellOps.php
