### ISSUE TITLE
CORS configuration for Next Build

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#15064]
## Requirements

We should configure servers correctly such that CORS errors are not present in our requests, so that remote assets load correctly and Cypress tests can run.

```[tasklist]
### Acceptance criteria
- [ ] CORS errors are no longer present when viewing or using Next Build pages in Tugboat when requesting assets from S3
- [ ] Whatever configuration change solves the current problem for Tugboat is also made for other environments
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14977
```

By 'other environments', meaning: if we configure vets-websites' production s3 asset bucket's CORS setup, we also make same/equivalent changes to staging and dev buckets.

## Background & implementation details

The CORS errors when running `yarn dev` are mostly font related right now due to pulling in production stylesheets locally. This will likely be fixed by using local assets. CORS errors may still exist on other environments depending on how those environments pull in their assets.

![Screenshot 2023-08-31 at 6 21 57 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/11279744/4a1ea601-5398-454b-a2d9-73279d6f0620)

Sample response header:
```
HTTP/1.1 200 OK
x-amz-id-2: TVYgLoBWvlOrm1H0A1oRnTgL/u2c2lWTdcKDgA3V+7T5XBAESNEe6M6dfu7wZqRLMY9MPvp1y9E=
x-amz-request-id: MHGAHP1MH1FNX9EZ
Date: Fri, 01 Sep 2023 01:21:38 GMT
Last-Modified: Thu, 31 Aug 2023 20:07:12 GMT
ETag: "d824df7eb2e268626a2dd9a6a741ac4e"
x-amz-server-side-encryption: AES256
Cache-Control: public, no-cache
Accept-Ranges: bytes
Content-Type: font/woff2
Server: AmazonS3
Content-Length: 78268
```

Sample request header
```
GET /generated/fa-solid-900.woff2 HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
Cache-Control: no-cache
Connection: keep-alive
Host: prod-va-gov-assets.s3-us-gov-west-1.amazonaws.com
Origin: http://localhost:3000
Pragma: no-cache
Referer: https://prod-va-gov-assets.s3-us-gov-west-1.amazonaws.com/generated/style.css
Sec-Fetch-Dest: font
Sec-Fetch-Mode: cors
Sec-Fetch-Site: cross-site
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36
sec-ch-ua: "Chromium";v="116", "Not)A;Brand";v="24", "Google Chrome";v="116"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "macOS"
```

These cause problems for Cypress, which will exit automatically if an error is thrown in the browser console.
There is a segment in `cypress/support/e2e.ts` that should be removed after these errors are fixed:
```
// remove this once we have CORS and all that vets-website stuff figured out
Cypress.on('uncaught:exception', (err, runnable) => {
  // returning false here prevents Cypress from
  // failing the test
  return false
})
```

```[tasklist]
### Implementation tasks
- [ ] Use this if it helps you or feel free to delete.
```

**Comment by tjheffner** [comment]
We may not need this for the time being if vets-website assets are built as part of our process. See https://github.com/department-of-veterans-affairs/next-build/pull/184
