### ISSUE TITLE
Resources & Support link lists being floated left

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#15076]
## To Reproduce
1. Go to https://www.va.gov/resources/
3. Scroll to Browse by Topic
4. See that link lists are all floated left, rather than full width

Looking for an artifact that would 

## Screenshots
![Screenshot 2023-09-01 at 1 34 29 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/85581471/543212d9-d581-4f91-899a-ae3900384504)

## AC / Expected behavior

- [ ] Links lists should be full width
- [ ] Consider what other templates might have been affected by the change that caused this in R&S

**Comment by jilladams** [comment]
This issue was traced back to https://github.com/department-of-veterans-affairs/content-build/pull/1653, changes to content blocks in the basic_landing_page file, as part of #14670 . 

Has been this way in prod since that PR merged 2 weeks ago, thusly not making this a fire drill on a holiday weekend Friday. 

Have tagged with both Fac and PW for now, as the Fac change is affecting the PW product, and whoever can get it fixed first should.

**Comment by xiongjaneg** [comment]
More info in [Slack thread](https://dsva.slack.com/archives/C52CL1PKQ/p1693600095546259)

**Comment by wesrowe** [comment]
Note that I added an AC for pondering possible other templates that might have been affected but not noticed yet.

**Comment by xiongjaneg** [comment]
Changes made were already present elsewhere so this couldn't occur on other pages, reverted in
