### ISSUE TITLE
Incorrect Layout on Event Details page

### ISSUE THREAD

**Issue by TroyA6** [department-of-veterans-affairs/va.gov-cms#15071]
## Describe the defect
When creating an Event, if 'non-VA location' is selected as the location, the 'full description' of the event displays off to the right side of the event page - with or without an image in place.

## To Reproduce
1. Go to 'VAMC site'
2. Create an Event with 'Non-VA Location' as the Event location and publish / save as draft
3. Preview the Event
4. See error - Full description appears off to the right side of the page

## AC / Expected behavior
Event should display Full description the same as events with VA location

## Screenshots

![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/108767736/16ffb9b6-ff60-4762-af0a-0a597cfcd152)

 ## Additional context
Related to [Github 13222](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13222 )
Also related to [VAHELP-6312](https://va-gov.atlassian.net/jira/servicedesk/projects/VAHELP/queues/custom/12/VAHELP-6312)

Couple more examples:
[Correct](https://www.va.gov/boston-health-care/events/60513/)
[Incorrect](https://www.va.gov/boston-health-care/events/60684/)

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Defect")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS workstream (orange) (not needed for bug tickets)
- [ ] CMS-supported product (black)

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [x] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`
- [ ] `Accelerated Publishing`

[VAHELP-6312]: https://va-gov.atlassian.net/browse/VAHELP-6312?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by jilladams** [comment]
FYI @wesrowe @chriskim2311 - I think we need to pull this into S92. Doing that, @chriskim2311 let me know if you have concerns, and pls add points when you get a chance to take a look.
