### ISSUE TITLE
Events can be edited in such a way as to have no dates/times, breaking content release.

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-cms#15085]
## Description
Friday afternoon and evening, [content release](https://dsva.slack.com/archives/CT4GZBM8F/p1693607758415739) failed repeatedly for a period of a couple of hours. The issue was with [this node](https://prod.cms.va.gov/west-texas-health-care/events/60949), which had been edited in such a way that it didn't have any dates/times.

Log from Nate's debugging: https://dsva.slack.com/archives/CDHBKAL9W/p1693610767914389?thread_ts=1693608602.473489&cid=CDHBKAL9W

Affected node:

![Screenshot 2023-09-01 at 7 39 58 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/1318579/2d82f3f4-92da-472f-af1b-194227c825c6)

Compare:

![Screenshot 2023-09-01 at 7 40 38 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/1318579/71f9cd02-0571-4bfd-bd2a-d3e6e8e25af6)

It was not immediately apparent to me how this occurred. We may find hints by looking at the revision history of the node.

Needless to say, this should not be possible.

## Repro
* Create recurring event
* Remove all recurrences - that might repro

## Acceptance Criteria
- [ ] Events can't be saved in the CMS with no date/time

**Comment by jilladams** [comment]
From scrum: 
* Revision logs on this node may contain more info, somehow
* We think this was likely due to removing all event recurrences on a recurring event, and will need to see if that repros. 
* Pulling this into sprint, and Daniel will take a look in sideline while he waits for responses on #13759

**Comment by jilladams** [comment]
Tried this and was able to repro on staging. (https://staging.cms.va.gov/alaska-health-care/events/61050, it'll get wiped out tonight)

First: 
* Create an event: 10/1/2023, 8-9a
* Set recurring: recur every day for 7 days, until 10/7/2023
* Save draft
<details><summary> Screenshot </summary>

![recurring-alaska-event](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/85581471/c0badf36-aba3-43c9-9f50-1423eed31bc9)
</details>

Then: 
* Edit draft
* Open Edit recurrences window
* Dropdown arrow on each recurrence -> Remove recurrence
* The window shows all 7 occurrences as canceled. Date / time still show on the main Event form page. 
* Save draft
![Screenshot 2023-09-05 at 1 58 50 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/85581471/c8991574-2896-4302-949d-3d837bdc8038)
![Screenshot 2023-09-05 at 1 58 56 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/85581471/74d6a2a0-7f68-468a-9cbe-7557db918fee)

THEN: 
* Edit the node again -- no date / time information is present on the node
![Screenshot 2023-09-05 at 2 02 46 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/85581471/bce7766f-a6d2-45cc-aaa2-c028c7d8f8f5)


So if all recurrences are removed, we need to prevent save, with some kind of message that an event must have recurrences, or unmark it as a recurring event?

**Comment by dsasser** [comment]
@jilladams Thank you for providing the repo steps! That will save me some time.

**Comment by dsasser** [comment]
Verified on prod:
![Screenshot 2023-09-11 at 6 11 46 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/221539/e7a27288-8413-4bca-80d4-37b007fd9905)
