### ISSUE TITLE
Improve help text

### ISSUE THREAD

**Issue by rachel-kauff** [department-of-veterans-affairs/va.gov-cms#1508]
## Description
Let's improve help text.

Content editors need help text that contextualizes fields with only the information that they need, and where they need to see it. In other words, they don't want to have to entire paragraphs of help text above each field, which increases cognitive load and or contributes noise to the form.

Work on #1427, rewriting intro text field help text for benefits detail pages surfaced several opportunities to explore design improvements to how we present help text and other contextual help information to content editors.

For example:
* Optimal length and content of help text
* Placement of help text (should be above the field and below the field label)
* Opportunities to include screenshot examples
* How to present best practices (e.g. "Don't style intro text except in special cases that may require bold, italics, links, paragraph breaks, and line breaks. ")
* How to implement soft guidelines vs. hard requirements (e.g. hard requirement = "Use sentence case;" soft guideline = "Address the user in the second person.")
* Suggested and enforced character counts
* How should designs be applied across field types, field groups, and content types. In which cases should they be customized?

**Artifacts**
[MURAL: On help text](https://app.mural.co/t/vagov6717/m/vagov6717/1586882180337/415aa0adba23f935239d291d83fda234b16f1957)

**Comment by EWashb** [comment]
this is in a good spot so far.
