### ISSUE TITLE
Q&As: Update naming conventions in Drupal and runbooks

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#15098]
### User story

**AS A** Content Editor
**I WANT** Q&A naming conventions to make sense and be consistent across content types
**SO THAT** working on Q&As is less cognitively taxing.

### Engineering notes / background

Designs are in [Figma](https://www.figma.com/file/MTBtolRaZK4hUkCprXyIiD/Q%26As?type=design&node-id=4%3A2157&mode=design&t=J07jlBp0p9rkSrAl-1) – the CLP tab/workspace.

#### Key changes between old "Q&A Section" UI and new design:

Name changes:

- Q&A now called "Page-specific Q&A"
- Section now called "Page-specific Q&A Group"

Theme change:

- A page-specific Answer should NOT look draggable away from its own Question - i.e., it should not have a drag handle or be indented

There are also changes to help text.

<details><summary>Screenshot</summary>
<img width="397" alt="Q A screenshot" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/4054752/71fd5f6d-3a07-40c3-9036-6d04e60b96cc">

</details>

#### Key changes between old "Q&A Group" UI and new design:

Name changes:

- "Q&A - Single" now called "Reusable Q&A"
- "Q&A Group" now called "Reusable Q&A Section"

## Acceptance criteria

>Consider
> - Design / Accessibility reviews
> - Collab cycle requirements
> - Device sizes (mobile first)
> - Documentation updates / Change management
< - [Content model documentation](https://prod.cms.va.gov/admin/structure/cm_document)
> - Testing notes

**NOTE: Figma is the source of truth**

- [x] Made updates to "global" Q&A stuff
  - [x] Renamed Editor UI elements for Q&A Section -> Page-specific Q&A Group (e.g., the "add" button refers to the new language)
  - [ ] ~Made theme changes (e.g., a page-specific Answer shouldn't appear draggable away from its own Question)~ -- **We found 74 entities that have multiple answers. This needs to be addressed on the content side before we make this change.**
  - [x] Renamed Editor UI elements for Q&A Group -> Reusable Q&A Group (e.g., the "add button refers to the new language)
- [x] For each content type with Q&As: updated instance label for both reusable and page-specific Q&As to reflect designs
  - [x] FAQ
  - [x] Benefit Detail
  - [x] Resources & Support Detail
  - [x] Q&A - Single
- [x] Updated help text as directed by Figma
- [x] Discussed with Jordan and noted in comments any element of design that is either hard to implement or would require tech debt-y code
- [x] Updated [product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/product-outline.md) for reusable Q&As to let future team members know that the naming conventions changed
- [x] Updated naming used in KB articles for the impacted content types
- [ ] PM review
- [ ] Design review
- [ ] **Change management:** Notified key CAIA team members via slack about the change in naming conventions

**Comment by wesrowe** [comment]
I submitted a CMS Collab Cycle request, #15150. We are seeking feedback from them on whether they want a shot at reviewing this before implementation.

**Comment by wesrowe** [comment]
@thejordanwood, will the changes to help text be obvious in Figma? If not, a little callout or comment might be helpful.

**Comment by thejordanwood** [comment]
Good idea! I'll add comments in there to show what text is changing.

**Comment by thejordanwood** [comment]
@wesrowe I've added comments to help show what text is changing.

**Comment by chri5tia** [comment]
Page-specific Q&A has a superfluous drag and drop arrow for the answer because more than one answer is allowable. In order to change this, we need to analyze the pre-existing entities that have more than one answer.  

- [ ] Strategize a path forward for this:
![Screenshot 2023-09-18 at 10 15 31 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/22764938/a7797305-4332-4635-ab9f-6564b5586511)

**Comment by chri5tia** [comment]
Also merge this PR with the other one to update documentation: https://github.com/department-of-veterans-affairs/va.gov-team/pull/65930

**Comment by wesrowe** [comment]
@chri5tia - I'm good with keeping the 'superfluous' drag-handle in place, as it is not superfluous. we didn't encounter the complexity of this instance of page-specific Q&As in our process, so that's why we missed its functionality. (aaaaand CLP turns out to be a very complicated product!) so the fact that it is in fact draggable is good reason to leave it as-is.
