### ISSUE TITLE
Audit of eMIS potential use by Facilities

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#15093]
# Problem Statement
Platform is deprecating a service, eMIS, that integrates with vets-api to handle for pre-fills of veteran info. What is the impact on Facilities' customers, if any? In particular, does Facility Locator use eMIS?

# Background Information
Information in Slack threads
- https://dsva.slack.com/archives/CE4304QPK/p1693930211659039
- eMIS deprecation Slack channel #-emis-deprecation
- EMIS is an external service integrated into vets-api and appears to be engrained into the vets-api codebase.
A large part of eMIS, is the pre-fill service. The pre-fill service makes a simple API call to Vets API, allowing veterans to have their information prefilled within forms to reduce typing and ultimately the time it takes to fill out a form. EMIS is heavily used in the pre-fill service to fill in information related to veteran military information, status and payments.

# Acceptance Criteria
- [x] eMIS is verified as used or not used by Facilities
- [ ] If eMIS is verified as used by Facilities, front end engineers join Slack channel #-emis-deprecation for next steps.
- [ ] If eMIS is verified as used by Facilities, subsequent tickets are created for next steps.

**Comment by xiongjaneg** [comment]
checking would be involved in codebase, fairly straightforward

**Comment by maxx1128** [comment]
I did a look through `vets-website`, and it should be pretty easy to remove this dependency. It's only used as part of an array of dependencies for the `<DowntimeNotification>` component. Removing it from the array of dependencies passed into it, along with a few other small codebase tweaks, should be about a `2`.

**Comment by xiongjaneg** [comment]
@maxx1128 I'm going to mark this ticket done and stub a follow-up ticket for removal of the dependency. Thanks! cc @jilladams
