### ISSUE TITLE
HTML Markup displayed as plain text in pager

### ISSUE THREAD

**Issue by omahane** [department-of-veterans-affairs/va.gov-cms#15099]
## Describe the defect
The pager has HTML markup being displayed as plain text.

## To Reproduce
1. Log into https://prod.cms.va.gov as an admin
2. Go to https://prod.cms.va.gov/admin/structure/taxonomy/manage/health_care_service_taxonomy/overview
3. Scroll to the bottom
4. See "< id="pagination-heading" class="visually-hidden">Pagination" above the pager

## AC / Expected behavior
The pager should display without HTML being rendered as plain text.

## Screenshots
![Screenshot 2023-09-06 at 6 21 54 AM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/766573/7d143eb0-dd1e-422e-8893-d0f5c832101b)

 ## Additional context
A recent commit may be related:
https://github.com/department-of-veterans-affairs/va.gov-cms/commit/52d2635682c46326fe4cde7d48568acc241eaa72

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Defect")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS workstream (orange) (not needed for bug tickets)
- [ ] CMS-supported product (black)

### Team
Please check the team(s) that will do this work.

- [x] `CMS Team`
- [ ] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`
- [ ] `Accelerated Publishing`

**Comment by productmike** [comment]
@omahane Noted that we've seen this and are intaking into our backlog. Most likely will be part of sprint 93.

**Comment by BerniXiongA6** [comment]
Hey @tonytaylor @edmund-dunn cc: @ndouglas --- This ticket looks refined but I somehow missed bringing it into the Sprint. If you end up having bandwidth to take this on in Sprint 93, does this still seem ready to be worked on?

**Comment by ndouglas** [comment]
@BerniXiongA6 Yes, @tonytaylor has been working on this.

**Comment by BerniXiongA6** [comment]
@edmund-dunn if you could help out @tonytaylor on this that would be awesome thnks!!!

**Comment by tonytaylor** [comment]
Closed with https://github.com/department-of-veterans-affairs/va.gov-cms/pull/15948
