### ISSUE TITLE
DUW: Update designs to include field labels and other best practices

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#15090]
### User story

**AS A** PM/PO/Eng
**I WANT** Sketch file to have all the best practices we learned about the subtask pattern
**SO THAT** dev goes smoothly on the first try.

### Engineering notes / background

Jordan created a Sketch file for a single flow through the wizard.

See this [Mural area](https://app.mural.co/t/departmentofveteransaffairs9999/m/vagov6717/1670355600942/8ebd465060e3c6e404292ab065389458a27160f9?wid=0-1670355684531) for a flow chart of question display logic.

**Questions about process**
- How will we document the content (questions and answer choices) – spreadsheet, Word doc, etc?
- Would labels be written by CAIA, or would we write them and get CAIA review?

## Acceptance criteria

>Consider
> - Design / Accessibility reviews
> - Collab cycle requirements
> - Device sizes (mobile first)
> - Documentation updates / Change management
< - [Content model documentation](https://prod.cms.va.gov/admin/structure/cm_document)
> - Testing notes

- [ ] Field labels documented (either in Sketch or an agreed-upon content tool like spreadsheet

**Comment by wesrowe** [comment]
In UX refinement we discussed the artifacts we'll likely need for updating the DUW and discovered that there may more prep work here than we initially thought. Here is a quick breakdown of what that prep might entail:
- Documenting all the content in the existing wizard – spreadsheet or Word doc?
  - May be necessary to get stakeholder confirmation that the existing wizard content is accurate
  - It would be a source of truth for development and QA
  - Is probably PW responsibility – for PACT Wizard, CAIA took the lead on this documentation because it was new
  - Documentation could be augmented with notes about flow logic
  - New UX elements like field labels could be added
- Creating an updated flow chart
- One of these artifacts should very clearly capture the rules for displaying changing elements of the Results screen

We need to figure out what role CAIA would have in a partnership on this content and flow work. @aklausmeier, do you think that is the kind of question you could seek an answer to? From either Dave or Danielle? Or I can raise it independently with Dave. Lmk your preference.

Cc @thejordanwood

**Comment by aklausmeier** [comment]
@wesrowe My instinct is we document current as we know it, building off of existing Mural (with some clean up), prior to a CAIA ticket to help confirm all content is accurate and creation of any labels/hint text as needed. I will coordinate with Danielle to see if my instinct is the best path forward for CAIA collab on this.

**Comment by aklausmeier** [comment]
@wesrowe After discussion with Danielle, this needs to take a content-first approach and loop CAIA in from the start. We should confirm content with them before UX design so the guidance is begin with CAIA ticket.

**Comment by wesrowe** [comment]
@aklausmeier, thanks for pursuing this with Danielle. I chatted with Dave about it yesterday and we came to the same conclusion. I created a CAIA intake ticket for this project: https://github.com/department-of-veterans-affairs/va.gov-team/issues/63977. I'll cc you on a comment on that ticket.

**Comment by FranECross** [comment]
closing this ticket because CAIA is driving the content. When they provide updated content, we'll create appropriate tickets at that time.
