### ISSUE TITLE
SSO Login issues required an out-of-band deploy.

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-cms#15100]
## Description

On September 5th, a SimpleSAML package was downgraded unexpectedly, leading to an incompatibility with the Drupal SAML module that blocked new authentication requests for PIV login. Edmund merged a patch reverting the problematic portions of the changes, and the two of us performed the OOB deploy procedure.

[Slack Thread 1](https://dsva.slack.com/archives/CT4GZBM8F/p1693948291723129)
[Slack Thread 2](https://dsva.slack.com/archives/CT4GZBM8F/p1693951178033879)

## Tasks
- [Create postmortem document](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/tree/master/Postmortems)

## Acceptance Criteria

- [ ] Postmortem document has been created and is reviewed and accepted.
- [x] Followup issue(s) opened to address causes and findings.

**Comment by BerniXiongA6** [comment]
@ndouglas did we ever get the postmortem written up for this? cc: @EWashb

**Comment by ndouglas** [comment]
@BerniXiongA6 Yep, sorry -- thought I linked it here but apparently I did not. 

https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Postmortems/2023/2023-09-05%20-%20CMS%20PIV%20Login%20Outage.md
