### ISSUE TITLE
Sythesis | Developing the hypothesis for improved KB product

### ISSUE THREAD

**Issue by productmike** [department-of-veterans-affairs/va.gov-cms#15115]
## User Story / Task
As an editor, I want the knowledge-base self-serve to be contextual to my needs, so that I can DIY the top 80% of my issues with a positive experience. 

## Acceptance Criteria
- [ ] Develop hypothesis (epic), success measurements based on persona and helpdesk input with assistance from PM.
- [ ] Review/present findings with entire CMS team.

**Comment by BerniXiongA6** [comment]
Closing dupe!!
