### ISSUE TITLE
[SPIKE] Identify distinct concerns of the D10 update that can separated out into discrete PRs against `main`.

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-cms#15119]
## Description

I'd like to do another large round of splitting changes out of the D10 branch and making individual, smaller PRs against `main`.

## Acceptance Criteria
- [ ] A list of individual concerns that are backward compatible has been compiled.
- [ ] Followup issue(s) opened to address each of the changes.

**Comment by edmund-dunn** [comment]
@ndouglas I don't really see much more we can split out. What is left is mostly testing and config. We do have it down to 117 files.

**Comment by ndouglas** [comment]
I've kinda reached the same conclusion 🙂  Well, it was worth a try.
