### ISSUE TITLE
Styles are not showing on Edit screens in D10

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#15112]
## Description
In the Full Rich text editor, there is a Styles dropdown.  However, in D10 now, when I add a style to my content, it's not displaying on the Edit screen anymore as it does in Prod so as the editor, I can't tell if I've already applied the styles or if I've added the right style, etc.

![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/106678594/1f3fb511-fdf1-4a63-87d3-1842045fa9b5)

## Acceptance Criteria
- [ ] All available styles in the Styles dropdown should show on the Edit screen
- [ ] All available styles in the Styles dropdown should continue to show on the View screen

## Team
Please check the team(s) that will do this work.

- [x] CMS Team
- [ ] Public Websites
- [ ] Facilities
- [ ] User support
- [ ] Accelerated Publishing

**Comment by laflannery** [comment]
@edmund-dunn I'm not seeing this on the edit screens:
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/106678594/11b31dbb-f7d4-406f-9c78-908b708b3dca)

This is where I was testing: https://vacms-12252-drupal-10-opslrfeufzwsvhxx2uuv1wmvjbiq7wuq.ci.cms.va.gov/node/28368/edit

**Comment by edmund-dunn** [comment]
This has been merged into the D10 branch.
