### ISSUE TITLE
Support research into the KB | Trends, Jira Service Desk, etc.

### ISSUE THREAD

**Issue by productmike** [department-of-veterans-affairs/va.gov-cms#15117]
## User Story/ Task

As a CMS researcher, I would like to have a better understanding of KBs and user support requests. I would also like to know if there have been any requests received directly related to knowledge base resources.

## Acceptance Criteria
- [ ] Coordinate with user support to better understand the types of data and trends that we are tracking within the Jira Service Desk space. 
- [ ] If valuable or applicable, request downloads, screenshots or other sources of data from user support.
- [ ] Determine existing set of derived-data available through existing means.
- [ ] Review outcomes of those datasets with research.

**Comment by BerniXiongA6** [comment]
@joagnitti Is it OK to close this ticket, I think it's been replaced by #15246 that we wrote together, right??

**Comment by joagnitti** [comment]
@BerniXiongA6 Yeah, you can close this one; seems like a dupe now.
