### ISSUE TITLE
Revision log message on Vet Center Services are misleading

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#15125]
## Describe the defect
When an editor edits a Vet Center Service, they have to do so using the Inline Entity Form on the Vet Center node. This does not provide a revision log message field so no new revision log message is saved.  This makes it so that revision gets the same log message as the previous log message.
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5752113/7ee2a4ef-6a68-4a4a-855a-4434228e869c)

## To Reproduce
1. Go to a vet center'/node/3719/edit'
2. Scroll down to the services, then click the edit button on the service.
3. Make a change to the service. 
4. Save the Vet Center Facility node.
5. Find the service you just edited in /admin/content?title=&type=vet_center_facility_health_servi&moderation_state=All&owner=All
6. Click on the revisions tab 
7. Notice that the revision message for the change you just made is the same as the previous revision message.

## AC / Expected behavior
 - [ ] A revision log message field to the IEF form as hidden.
 - [ ] A revision message is required when a Vet Center Service is saved (just like on the node itself)

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Defect")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS workstream (orange) (not needed for bug tickets)
- [ ] CMS-supported product (black)

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [ ] `Public Websites`
- [x] `Facilities`
- [ ] `User support`
- [ ] `Accelerated Publishing`

**Comment by swirtSJW** [comment]
This is very similar to and has a similar solution set as #15124

IEF also causes bypass of "allow only one" validation"

**Comment by xiongjaneg** [comment]
ticket for larger IEF issue was created #17374

**Comment by xiongjaneg** [comment]
Moving out of sprint 105 due to Christian's [comment in #15124 ](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15124#issuecomment-1972132785)about needing custom code

**Comment by davidmpickett** [comment]
This defect will be resolved once the IEF changes are implemented. Leaving this defect in backlog to confirm and close after https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18003

**Comment by jilladams** [comment]
Can be validated / closed when #18003 ships

**Comment by davidmpickett** [comment]
Validated on Staging
![Screenshot 2024-08-19 at 2 01 36 PM](https://github.com/user-attachments/assets/671401cc-6270-4bd3-b342-98733d22bbf5)
