### ISSUE TITLE
Last updated by human not set when Vet Center Service is saved/updated.

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#15124]
## Describe the defect
When an editor edits a Vet Center Service, they have to do so using the Inline Entity Form on the Vet Center node.  This does not update the last saved by an editor field on the Vet Center Service node
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5752113/1672c74e-0a75-4abc-909f-427c06372b52)

## To Reproduce
1. Go to a vet center'/node/3719/edit'
2. Scroll down to the services, then click the edit button on the service.
3. Make a change to the service. 
4. Save the Vet Center Facility node.
5. Find the service you just edited in /admin/content?title=&type=vet_center_facility_health_servi&moderation_state=All&owner=All
6. Look at the date and time of your revision, notice it does not match the date of the Last saved by a human field.

## AC / Expected behavior
- [ ] The last updated field to the IEF form is hidden.
- [ ] When a Vet Center Service is saved by a human,  the last updated date is set accordingly.

**Comment by mmiddaugh** [comment]
Depending on changes, the new "Vet Center content review" KB article which was written to support Vet Center editors in reviewing/updating their content (currently in draft) may need to be updated.

**Comment by mmiddaugh** [comment]
Related: [Vet Center service editorial UX does not show national description #17177](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17177)

**Comment by xiongjaneg** [comment]
This could be resolved by removing inline editor.

**Comment by xiongjaneg** [comment]
moved larger IEF removal to #17374

**Comment by xiongjaneg** [comment]
@omahane Absolutely makes sense. I'll move both of those tickets back to backlog. I've moved #17191 address block work to high priority. cc @mmiddaugh @jilladams

**Comment by xiongjaneg** [comment]
IEF removal first ticket is #17374

**Comment by davidmpickett** [comment]
This defect will be resolved once the IEF changes are implemented. Leaving this defect in backlog to confirm and close after #18003

**Comment by jilladams** [comment]
Can be validated / closed when #18003 ships

**Comment by davidmpickett** [comment]
Verified on Staging

![Screenshot 2024-08-19 at 1 59 16 PM](https://github.com/user-attachments/assets/d4d7996e-8df2-4ef7-a623-bd771f1429f4)
