### ISSUE TITLE
Remove "Button" styles from D10 ckeditor

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#15135]
## Description
This is the first ticket in [this epic](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15068) (which is not actually an epic yet because my Zenhub is not working)

Editors should not be styling links to look like buttons. This breaks material honesty and is bad for accessibility. We want to remove the styles from the CKEditors that allow the editors to do this.

## Acceptance Criteria

- [x] The following styles have been removed from the Styles dropdown in the CKeditor in D10
  - [x] Default link button
  - [x] Primary link button
  - [x] Secondary link button
- [x] All style tags remain in the Allowed HTML Tag list
- [x] Requires accessibility review

## Team
Please check the team(s) that will do this work.

- [x] CMS Team
- [ ] Public Websites
- [ ] Facilities
- [ ] User support
- [ ] Accelerated Publishing

**Comment by edmund-dunn** [comment]
Button styles have been removed.[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbFdnIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--7b3e657074dba3d840b992ce07a8f5e9702bf342/CleanShot2023-09-14at11.15.36.jpg)

**Comment by edmund-dunn** [comment]
Button styles have been reomved. 
![CleanShot2023-09-14at11 16 58](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/109987005/1f20c35b-224b-4682-b9b3-4602cc4f532e)

**Comment by laflannery** [comment]
This is now approved!

**Comment by edmund-dunn** [comment]
Work has been merged into the D10 branch
