### ISSUE TITLE
Reconfigure permissions for PDF audit to use Role based permissions

### ISSUE THREAD

**Issue by edmund-dunn** [department-of-veterans-affairs/va.gov-cms#15136]
## User Story or Problem Statement
Selected individuals and super admins need to be able to access the PDF audit. 

"As a Drupal CMS Content publisher (maybe Content editor too) I would like to see a list of media, particularly PDFs) in my Section so I can more easily maintain my webpages and files."

For example, if a content publisher goes to https://prod.cms.va.gov/admin/content/media/pdfs, they get a blank page, which is unexpected. 

If an administrator goes there, they get the list of PDFs as expected.

## Use case
VHA Digital Media is training their editors to minimize use of PDFs. Many VAMCs have tens and potentially hundreds of PDFs in Drupal. They will be asked to reduce them. VHA DM would like an easy way for their editors to find their PDFs, published status, and which pages they are linked from. 

They would also like them to be able to archive them, if not delete them entirely (out of scope for this issue).

## Acceptance Criteria
- [ ] Refactor access check to use administrator, content_admin, content_editor, content_publisher and content_reviewer roles.

## Team
Please check the team(s) that will do this work.

- [x] CMS Team
- [ ] Public Websites
- [ ] Facilities
- [ ] User support
- [ ] Accelerated Publishing

**Comment by swirtSJW** [comment]
Is there a reason not to just open this up to authenticated users.  Seems really heavy to make an entire for access to one View.

**Comment by edmund-dunn** [comment]
@swirtSJW I got this. If I need help or advice, I will ask.

**Comment by edmund-dunn** [comment]
Moving to Icebox because it is not currently needed.

**Comment by EWashb** [comment]
Hi @BerniXiongA6 can we reopen this issue? VHA DM has made the business decision to open this up to their editor base after they've done the appropriate testing of the feature. They would like to confirm that our approach:

- only shows editors the sections they are assigned to
- will not allow them to reassign PDFs to other sections
- AKA This is just a view of them to see what PDFs are assigned to their own sections

**Comment by MDomngz** [comment]
Regression ticket for rollback around video media
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18244
