### ISSUE TITLE
CMS and/or web server errors when multiple sustained JSON:API requests are made

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#15138]
### What is the problem?

When we allow Next Build to make multiple requests to its CMS instance, there are often error responses, resulting in the build not being able to complete.

If we restrict Next Build to a single connection at a time, builds complete successfully, but this results in an unacceptably slow build time.

### Who is affected?
 
Engineers attempting to build Next Build; in the future, anyone dependent on Next Build.

### How urgent is the issue? 
Critical / **Major** / Minor

```[tasklist]
###
- [x] A solution is implemented such that Next Build can make multiple requests without triggering connection errors
- [x] Builds complete in a reasonable amount of time
```

'A reasonable amount of time' will be defined as 50% or less of the difference between single-thread and hypothetical no limits. In other words, if single thread takes 11m, and no limits takes 1m, then we're shooting for 6m or faster.

### How can we see the problem? (repro steps)

1. In next.config.js, remove/comment the section that sets workerthreads: false & cpu to 1, or else comment the entire experimental section.
2. Run build (happens from local, when targeting the content-build Tugboat CMS).

In order to see the incoming connections and errors in the web server logs:
1. AWS access, ssh into Tugboat (EC2 instance)
2. tail nginx logs
3. kick off build, watch incoming connections

**Expected result:** Next Build builds successfully.<br />
**Actual result:** Next Build fails with 502 'Bad Gateway' errors.

### Is there any additional information?
Screenshots:

Log messages (please specify from where or what commands(s))
```
Log messages here
```

**Comment by timcosgrove** [comment]
Possibly config change in nginx or php-fpm to fix; @tjheffner with more information.

**Comment by tjheffner** [comment]
Updates @ryguyk made to the fetcher on the next-build side now properly retry failed attempts, so a single 502 error no longer kills the build: https://github.com/department-of-veterans-affairs/next-build/pull/171/files#diff-5e12dbcc1bceedb735de6b63d5147d2f68647d2ec166b1216c4f64b2bc97e20e

```
- info Generating static pages (832/3331)
Failed request (Attempt 1 of 5): https://content-build-medc0xjkxm4jmpzxl3tfbcs7qcddsivh.ci.cms.va.gov/jsonapi/banner-alerts?item-path=/white-river-junction-health-care/stories/va-health-connect-launches-at-va-white-river-junction-get-immediate-help-by-calling-1-866-687-8387
Failed request (Attempt 1 of 5): https://content-build-medc0xjkxm4jmpzxl3tfbcs7qcddsivh.ci.cms.va.gov/jsonapi/node/news_story/993e86c8-5fec-4d25-bfd1-7a18b35603fa?include=field_media%2Cfield_media.image%2Cfield_author%2Cfield_listing
Failed request (Attempt 1 of 5): https://content-build-medc0xjkxm4jmpzxl3tfbcs7qcddsivh.ci.cms.va.gov/jsonapi/banner-alerts?item-path=/houston-health-care/stories/a-long-ride-in-support-of-veterans
Failed request (Attempt 1 of 5): https://content-build-medc0xjkxm4jmpzxl3tfbcs7qcddsivh.ci.cms.va.gov/jsonapi/banner-alerts?item-path=/louisville-health-care/stories/run-for-the-wall-makes-annual-stop-at-robley-rex-va-medical-center
Failed request (Attempt 1 of 5): https://content-build-medc0xjkxm4jmpzxl3tfbcs7qcddsivh.ci.cms.va.gov/router/translate-path?path=%2Fsaginaw-health-care%2Fstories%2Fjune-is-ptsd-awareness-month
- info Generating static pages (1665/3331)
- info Generating static pages (2498/3331)
- info Generating static pages (3256/3331)
- info Generating static pages (3331/3331)
- info Finalizing page optimization...
```

I think with the retry mechanism properly working, the 502s are no longer a blocking error for us. Additional retries receive the correct data and the build continues successfully.
