### ISSUE TITLE
Design+Eng: Spike: Find solution(s) to CLP image aspect ratio problem

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#15147]
### User story

**AS A** Designer
**I WANT** to work with an engineer to find solution(s) to the ultra-wide aspect ratio problem on CLP images
**SO THAT** we can eliminate bad layouts for Veterans.

### Engineering notes / background

Issue with layouts was reported in #10075. 

**Planning note:** intent is for Jordan to sit with an engineer to play around with CSS ideas. Probably should be assigned to the Engineer.

## Acceptance criteria

>Consider
> - Design / Accessibility reviews
> - Collab cycle requirements
> - Device sizes (mobile first)
> - Documentation updates / Change management
< - [Content model documentation](https://prod.cms.va.gov/admin/structure/cm_document)
> - Testing notes

- [ ] Designed a way to present CLP pages across all devices/breakpoints such that the FE layout respects the aspect ratio that the Editor was asked to follow (2:1) or a variant the Editor was asked to provide in Drupal
- [ ] Documented how to achieve the design from a CSS/markup coding perspective
- [x] Audited [published CLPs](https://prod.cms.va.gov/admin/content?title=&type=campaign_landing_page&moderation_state=editorial-published&owner=All) to make sure the change would not harm the UX of any published CLPs
- [ ] @wesrowe Reviewed analytics for device/resolution info on visitors to CLPs for any insights into Veteran devices

**Comment by jilladams** [comment]
From planning: 
* May require backend changes, if we confirm that Drupal is serving the full image rather than the 2:1 ratio image
* Timeboxed for estimate
* No expectation of working solution in this ticket, just path forward to a solution

**Comment by thejordanwood** [comment]
@wesrowe –  @randimays, @chriskim2311, @dsasser, and I met to discuss this on 9/18.. Our recommendations:

1. The hero image should have a max width. This will make it consistent with other pages on the site because other pages don't allow for elements to expand past a certain width. 
2. We should also update the help text to tell editors that this needs a new aspect ratio. Instead of a 2:1 ratio, it will be closer to a 1:1.

This is what we think the change could look like. 

![max width](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/104526584/bab46f82-abb0-49f9-b9d5-a822089e2f39)

**Comment by thejordanwood** [comment]
This is my audit of the current published CLPs. I think we could make the new image ratio work for all of them, although I may need to manually fix a couple of images. 

**Will not impact:**
1. https://www.va.gov/initiatives/veteran-trust-in-va/
2. https://www.va.gov/initiatives/veterans-experience-action-centers/
3. https://www.va.gov/initiatives/recognizing-lgbtq-veterans-during-pride-month/
4. https://www.va.gov/initiatives/vote/ (original image is a square)
5. https://www.va.gov/initiatives/end-of-life-benefits/ (I could manually crop if needed)
6. https://www.va.gov/initiatives/covid-flu/ (I could manually crop if needed)
7. https://www.va.gov/initiatives/sign-in-securely-with-logingov/ (I could manually crop if needed)

**May impact:**
1. https://www.va.gov/initiatives/emergency-room-911-or-urgent-care/ (original image is 2:3 ratio)
2. https://www.va.gov/initiatives/national-buddy-check-week-talk-to-10-veterans/ (original image is 2:3 ratio)

**Comment by wesrowe** [comment]
@thejordanwood, the next step is (I think) a single ticket that 
1. documents the new design
2. specifies the steps we would take to mitigate existing images per your audit above

Ticketed: #15351

**Comment by thejordanwood** [comment]
Closing because a new design ticket with next steps has been created for this.

**Comment by wesrowe** [comment]
FWIW I got the GA results on devices used for all the CLPs listed in Jordan's comment above:
<img width="200" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/4054752/14321741-79ed-4e6b-90ca-a17d22f5eb62">

Basically 50/50 split between mobile and desktop, with tablets 2.5%.

This is for nearly 2 months, from Aug 1 to Sept 25, 2023.
