### ISSUE TITLE
Establish and enact VBA facility alias pattern

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#15155]
@davidmpickett to refine this ticket based on outcomes of #15752

## User Story or Problem Statement
Currently VBAs have a pattern of 	[node:field_administration:entity:name]/locations/[node:title]

We need to update this schema to follow the recommendations out of #15752 that are documented here: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/facilities/naming-schema#vba-benefits-facilities-naming-schema

~~BLOCKER: Need to confirm that https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15752#issuecomment-1959742070 comment has been addressed in documentation before we start work.~~ Not a blocker for this ticket. This ticket will be scoped to just removing the Section/Location aspect of the URL so they are all [Node Title]. 

## Acceptance Criteria
- [ ] VBA facility path aliases match the [naming schema ](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/facilities/naming-schema#vba-benefits-facilities-naming-schema) 
- [ ] Validated in Tugboat

**Comment by swirtSJW** [comment]
Example of a really long path for a facility 
[/salt-lake-city-va-regional-benefit-office-at-george-e-wahlen-department-of-veterans-affairs-medical-center/locations/pre-discharge-site-at-fort](https://pr15143-x90pmpzpeuow6pi4uyluoagtj5rpzncy.ci.cms.va.gov/salt-lake-city-va-regional-benefit-office-at-george-e-wahlen-department-of-veterans-affairs-medical-center/locations/pre-discharge-site-at-fort)

**Comment by davidmpickett** [comment]
[Per CAIA](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/information-architecture/ia-design-docs/vba-benefit-offices-migration.md#url), namespacing request has been denied

**Comment by davidmpickett** [comment]
I think this ticket has been rendered moot by #15752. Or at least we know what the alias pattern will be from that ticket.

@omahane @Becapa is there anything specific we'd need to do in Drupal to "enact" the alias pattern?

**Comment by davidmpickett** [comment]
Closing as duplicate. #17351 will address the open question of how/where we cut the long names into condensed names. The condensed names will power H1/Breadcrumbs & URL

**Comment by davidmpickett** [comment]
Reopening this, because even without figuring out how we are snipping long names, the URL structure needs to be updated before staging review.

**Comment by jilladams** [comment]
Right now: NCA / VBA use the same pattern. Split them, please

**Comment by omahane** [comment]
@jilladams @davidmpickett I'm going to check prod. While we can't publish VBA or NCA for now, I can check the alias patterns and make sure they are as we expect.

**Comment by omahane** [comment]
VBA is now like Vet Center on [Prod](https://prod.cms.va.gov/admin/config/search/path/patterns). 
<img width="1352" alt="Screenshot 2024-04-30 at 07 27 40" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/766573/409deabe-2532-44f0-b7fe-21781bc2f54e">

And NCA is all by its lonesome.
