### ISSUE TITLE
CMS Collab Cycle intake request – PW: Event calendar with new multi-select component

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#15169]
### Description of the problem / issue / enhancement
PW wants to build a feature that enables Editors to create Events for display on multiple calendars – i.e., 1 or more Facilities plus optionally the Outreach/National calendar. This requires a multi-select drupal UI component, which Blake is already working on.

We are seeking how CMS C.C. wants to be involved with:
1. The design of the multi-calendar UI in general
2. The multi-select component in particular (which would be part of the CMS design system)

## Rough estimate of urgency and impact
As soon as possible – VEO has been requesting for a long time, we are building momentum.

## Acceptance Criteria
- [ ] The Product Manager for the recommended intake team is pinged through Slack about the issue
- [ ] The Product Manager has discussed with the respective Product Owner to determine prioritization
- [ ] Any decisions made on prioritization or implementation are communicated back to the originating team

### Team
Please check the team you project will do this work. If not sure, select "Program".

- [x] `CMS Team`
- [ ] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`
- [ ] `Accelerated Publishing`

**Comment by BerniXiongA6** [comment]
Hey @BlakeOrgan -- could we discuss this at one of the next pre-refinements? cc: @EWashb

**Comment by BlakeOrgan** [comment]
@wesrowe Based on the discussion in [this slack thread](https://dsva.slack.com/archives/C52CL1PKQ/p1694197792071149), we'll need to know what direction your team decides to go in regarding how you want to handle the MVP before deciding if a collab cycle would be necessary. We believe that a collab cycle will not be necessary as long as patterns already established in the CMS are used. Please let us know here once your team decides on which direction you would like to take.  
  
In the meantime, the CMS team will continue on with work adding a multi-select dropdown to the design system for teams to use in future use cases.

**Comment by jilladams** [comment]
Related ticket: #13500

**Comment by BerniXiongA6** [comment]
Just checking whether you feel good about the path forward that PW will take, @wesrowe -- I'll close this ticket on our end once I get your confirmation. Thanks! cc: @EWashb

**Comment by wesrowe** [comment]
I do feel good about it – we are going to use existing components (a checkbox), so no collab needed. We'll look forward to having a chance to use the multi-select dropdown when it's available.

**Comment by EWashb** [comment]
I'll go ahead and close per the comments above.
