### ISSUE TITLE
I.L.: Submit for 508 audit

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#15167]
### User story

**AS A** PO/PM
**I WANT** IL to be submitted to the 508 office for audit
**SO THAT** we keep things compliant.

### Engineering notes / background

- Docs on [how to do it](https://depo-platform-documentation.scrollhelp.site/developer-docs/request-support-from-the-va-508-office#audit-request)

## Acceptance criteria

- [x] Audit request [submitted](https://depo-platform-documentation.scrollhelp.site/developer-docs/request-support-from-the-va-508-office#audit-request)
  - ServiceNow (SNOW) request number REQ15696116

**Comment by wesrowe** [comment]
SNOW ticket created following instructions linked above. The portal says it could be a few weeks before we hear back. The ticket includes references to DaveC and Martha Wilkes.

**Comment by jilladams** [comment]
SNOW ticket: https://yourit.va.gov/va?sys_id=74c1f7bc1be13514018220a5624bcbda&id=ticket&view=sp&table=sc_req_item

**Comment by laflannery** [comment]
508 audit was returned on 2/5/24 with 0 defect
[40712 va.gov Income Limits Calculator Web Tool  1.0 - 508 Audit Report - 2_5_2024 9_30 AM.docx](https://github.com/department-of-veterans-affairs/va.gov-cms/files/14170606/40712.va.gov.Income.Limits.Calculator.Web.Tool.1.0.-.508.Audit.Report.-.2_5_2024.9_30.AM.docx)
