### ISSUE TITLE
Cleanup/delete old EFS volumes (post-mvp ship)

### ISSUE THREAD

**Issue by ElijahLynn** [department-of-veterans-affairs/va.gov-cms#1516]

**Comment by ElijahLynn** [comment]
Closing, either not needed anymore or moved to GitHub tasks in https://github.com/department-of-veterans-affairs/va.gov-cms/issues/1360#issue-589475211.

**Comment by ElijahLynn** [comment]
@cmaeng I don't think this should be in this epic right now if we want to close out the epic for MVP ship. Not sure how we are handling this, but this task is post-mvp, can you help organize that?

**Comment by cmaeng** [comment]
@ElijahLynn sounds good. let's keep tracking it but as long as it's not a dependency on something else that's fine. we'll prioritize during next sprint planning.

**Comment by ElijahLynn** [comment]
Adding to Sprint 10, just realized I forgot about this, it is costing money and isn't used anymore.

**Comment by ElijahLynn** [comment]
Going to assign this to @olivereri once he is onboarded and in the ORG.

**Comment by ElijahLynn** [comment]
@olivereri Give this a read first > https://github.com/department-of-veterans-affairs/devops/blob/master/docs/Terraform%20Knowledge%20Dump.md

**Comment by olivereri** [comment]
> @olivereri Give this a read first > https://github.com/department-of-veterans-affairs/devops/blob/master/docs/Terraform%20Knowledge%20Dump.md

That link gives me a 404. Are you able to pull it up? I'm also a member of the ORG now but can't see that doc.

**Comment by ElijahLynn** [comment]
> > @olivereri Give this a read first > https://github.com/department-of-veterans-affairs/devops/blob/master/docs/Terraform%20Knowledge%20Dump.md
> > @ElijahLynn
> > That link gives me a 404. Are you able to pull it up? I'm also a member of the ORG now but can't see that doc.

I just gave you access, so you should be good now!

**Comment by olivereri** [comment]
Waiting for VSP Operations review.

**Comment by olivereri** [comment]
EFS volumes, mount targets and SGs have been cleaned up after "terraform apply" on:
dsva-vagov-dev
dsva-vagov-staging
dsva-vagov-prod
dsva-vetsgov-utility
