### ISSUE TITLE
Composer should exit with error if any patch failed to apply

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#1519]
## Description

[Slack thread](https://dsva.slack.com/archives/CT4GZBM8F/p1587063847199200)

> **Composer Error handling**
> If a patch cannot be applied (hunk failed, different line endings, etc.) a message will be shown and the patch will be skipped.
> 
> To enforce throwing an error and stopping package installation/update immediately, you have two available options:
> 
> 1. Add "composer-exit-on-patch-failure": true option to the extra section of your composer.json file.
> 2. Export COMPOSER_EXIT_ON_PATCH_FAILURE=1

## Acceptance Criteria
* Composer includes `"composer-exit-on-patch-failure": true` option in the extra section of composer.json file
* Composer exits with error if any patch failed to apply

## Testing

All of these should cause fails on build:

- [ ] Update a current patch so it does apply
- [ ] Update the source code where a patch current applies

**Comment by ElijahLynn** [comment]
Note: We need to remove remove the logic we have in tests.yaml that does this now when we merge this.

**Comment by indytechcook** [comment]
Test with changes to `remove-paragraph-group-3116501-2.patch`

```
diff --git a/src/Plugin/Field/FieldWidget/InlineParagraphsBrowserWidgetTrait.php b/src/Plugin/Field/FieldWidget/InlineParagraphsBrowserWidgetTrait.php
index b01aebc3..3fcb6f70 100644
--- a/src/Plugin/Field/FieldWidget/InlineParagraphsBrowserWidgetTrait.php
+++ b/src/Plugin/Field/FieldWidget/InlineParagraphsBrowserWidgetTrait.php
@@ -94,7 +94,7 @@ public function formElement(FieldItemListInterface $items, $delta, array $elemen
       $group = $groups->getGroup($group_name);
       if ($group) {
         $element['top']['paragraph_type_title']['info'] = array(
-          '#markup' => '<span class="paragraph-group">' .  '</span> ' . $current_title,
+          '#markup' => $current_title,
         );
       }
     }
@@ -165,3 +165,4 @@ public function formMultipleElements(FieldItemListInterface $items, array &$form
   }

 }
+
```

This broke the application of the patch:
![~:code:va:va.gov-cms 2020-06-02 09-55-20.png](https://images.zenhubusercontent.com/543e76bb7c6ccc6277a54276/3c811f5a-deab-40ff-a0a6-7a7a837334f0)

**Comment by indytechcook** [comment]
Running with yam-tests produced a different output but it still failed.  This is with the composer command in `tests.yml` being `command: rm -rf ./docroot/vendor/va-gov/web && composer install --dev --no-interaction --no-progress --ansi`

![image.png](https://images.zenhubusercontent.com/543e76bb7c6ccc6277a54276/8d976563-841e-43de-a716-27a9dde4fb93)

![image.png](https://images.zenhubusercontent.com/543e76bb7c6ccc6277a54276/5817a589-b1c0-45cc-b22a-ebea2b2c3e79)

I did notice that all of the tests still ran even though patching failed.  I would expect if the `composer install` failed then the rest fo the tests do not need to run.

**Comment by indytechcook** [comment]
PR submitted: https://github.com/department-of-veterans-affairs/va.gov-cms/pull/1913

**Comment by ElijahLynn** [comment]
> I did notice that all of the tests still ran even though patching failed. I would expect if the `composer install` failed then the rest of the tests do not need to run.

I agree with this. 

We do have the option of "ignore-failures: true" which defaults to `false`, but that just marks the test as failed or passed but keeps on running everything.

**Comment by indytechcook** [comment]
I created #1979 as a follow up.
