### ISSUE TITLE
Redirect Request | Chapter 36 form url change

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-cms#15219]
# Specific timing for merge & Deploy required: check the comments

### Instructions
- Requests must be submitted **AT LEAST** 2 weeks in advance.  Some requests take a significant amount of time and coordination to implement, so start the process as soon as you know you will need one. 
- This issue will be used from initial request through implementation to ensure all individuals working on this are notified of status updates.  Please do not create multiple issues to track different steps.
- It is your responsibility to notify VA stakeholders as appropriate.  

### Type of request
- [ ] We are retiring or taking down a page and need to redirect the URL (complete redirect section)
- [x] We are changing the URL of an existing page (complete redirect section): The [Chapter 36 form number was recently changed](https://github.com/department-of-veterans-affairs/va.gov-team/issues/62663) from 28-8832 to 25-8832, so the url needs to be updated 
- [ ] We need a custom vanity URL (complete vanity URL section)

### Implementation date
When does this request need to be live?
Choose one:
- [ ] On a specific date, connected to a program or publishing requirement. **DATE:**
- [ ] Any day prior to a deadline/latest possible date. **DEADLINE:** 
- [x] Any day after an earliest possible date. **EARLIEST DATE: ASAP, the form number has already been updated on most VA.org pages**
- [ ] During a specific date range: ***EARLIEST DATE TO LATEST DATE:***
- [ ] No hard timing requirements, publish when possible.

### Redirects 
Current URL  |  Redirect Destination or New URL
---  |  ---
https://www.va.gov/careers-employment/education-and-career-counseling/apply-career-guidance-form-28-8832/ | https://www.va.gov/careers-employment/education-and-career-counseling/apply-career-guidance-form-25-8832

### Process, Roles and Responsibilities
- [x] Requesting team: Above information is provided
- [x] Requesting team: All appropriate VA stakeholders are notified as appropriate
- [ ] IA: Request is vetted and documented and implementation plan is clear 
- [ ] IA: Request is assigned to appropriate team for implementation 
- [ ] Implementation team: Work is complete
- [ ] Implementation team: Validated in production
- [ ] Requesting team: Validates everything is correct in production and closes ticket

**Comment by mnorthuis** [comment]
@jilladams  Please note that I updated the current URL above.  It is not just the /introduction page that needs redirecting, it is the main URL of the form and all child URLs that need to be redirected to the new form. 

This is vetted and ready to go from our end once the new URL is live.

FYI @jennymayoco I jumped in here since I've already been in convos on this one.

**Comment by jilladams** [comment]
Thanks, @mnorthuis . (In general I always update redirect tickets to show the actual URL instead of link text, for the sake of our engineers, so good catch seeing that the "current URL" was too limited.)

**Comment by DLarson-Oddball** [comment]
@jilladams Appreciate your detail and prompt responses. 

I am still trying to get statuses to pass on both open PRs. Despite being up to date with main & not having logic changes, the jobs are still failing. Therefore, I am tentative to schedule an OOB deployment until I know I can actually merge the PRs.

Can I provide an update once I have statuses passing? Thanks!

**Comment by jilladams** [comment]
@chriskim2311 FYI we skipped this in planning, but it's a pretty straightforward redirect. We shouldn't merge / deploy until we get the greenlight from @DLarson-Oddball . Merge timing may require an OOB deploy, TBD.

**Comment by DLarson-Oddball** [comment]
@jilladams PRs have been deployed since we last spoke. We are okay to proceed with this redirect implementation, and it can now be deployed as soon as possible without an OOB deployment. Let me know if any way I can assist. Thanks!

**Comment by jilladams** [comment]
@DLarson-Oddball thanks! We've merged this PR and the redirect will go live tomorrow morning on the standard devops deploy schedule.

**Comment by chriskim2311** [comment]
@DLarson-Oddball @jilladams This redirect is live on production. Closing!

**Comment by mnorthuis** [comment]
@chriskim2311 @jilladams The redirect is not catching the child pages of the old URL
this URL is redirected:
https://www.va.gov/careers-employment/education-and-career-counseling/apply-career-guidance-form-28-8832/

but this - as an example - is not
https://www.va.gov/careers-employment/education-and-career-counseling/apply-career-guidance-form-28-8832/introduction

Everything under the main URL needs to redirect.

**Comment by chriskim2311** [comment]
@steele-Im the online tool link will be fixed with the updated child URL change

**Comment by DLarson-Oddball** [comment]
Hi @chriskim2311 @jilladams @mnorthuis, After some additional testing, I am finding this URL: https://www.va.gov/careers-employment/education-and-career-counseling/apply-career-guidance-form-25-8832/introduction won't load the form as expected on production. If I omit /introduction, the form loads fine. 

After speaking with @Mottie, we determined [this file](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/revproxy-vagov/vars/react_routes.yml) doesn't include an entry with the new url. Is that something that can be addressed as part of this request?

**Comment by jilladams** [comment]
@DLarson-Oddball  that change will be addressed by Chris's fix to include all child pages of the apth that is currently working. @chriskim2311 , if you haven't already, we'll need to request an OOB deploy for your latest change, so it goes out before next Wed. Here's an example to follow: https://dsva.slack.com/archives/CBU0KDSB1/p1686865150058509

**Comment by chriskim2311** [comment]
@Dlarson-Oddball, @Mottie is correct, I have added this change in this PR. https://github.com/department-of-veterans-affairs/devops/pull/13464

@jilladams Once I get this approved I will ask for the OOB deploy.

**Comment by jilladams** [comment]
Platform did not get back to us on this PR today, so this update won't ship til Monday.

**Comment by chriskim2311** [comment]
@jilladams @DLarson-Oddball OOB request has been requested for today. Thank you https://dsva.slack.com/archives/CBU0KDSB1/p1695660555661709

**Comment by DLarson-Oddball** [comment]
Thanks for the quick turnaound @chriskim2311 @jilladams.

**Comment by jilladams** [comment]
Platform did not get that deploy out today. I've asked if it will go tomorrow, or if they won't deploy out of band, and we should expect it to go live on Wed with the auto deploy.

**Comment by DLarson-Oddball** [comment]
Thank you for getting this deployed OOB @chriskim2311! The redirects worked for me as well.

**Comment by jilladams** [comment]
@chriskim2311 one more dangler from this ticket identified here: https://dsva.slack.com/archives/CE4304QPK/p1697053016298709?thread_ts=1687293546.830659&cid=CE4304QPK

> URL should be redirecting and it's not. I'm not totally sure if it's an issue with the form itself or the redirect: https://www.va.gov/careers-employment/education-and-career-counseling/apply-career-guidance-form-28-8832

**Comment by chriskim2311** [comment]
@jilladams Platform ticket has been created for this. All child URL implementations across the site do not account for URL's without the forward slash.

https://dsva.slack.com/archives/CBU0KDSB1/p1697054897914219
