### ISSUE TITLE
FE: DUW: Validate content doc and flow diagram by examining wizard code

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#15216]
### User story

**AS A** PO/PM/Stakeholder
**I WANT** to be sure that the documentation that we have for the Discharge Upgrade Wizard accurately represents the product in production
**SO THAT** we base our review of the documentation on the current best understanding.

### Engineering notes / background

Docs to validate:
- [Mural of logic](https://app.mural.co/t/departmentofveteransaffairs9999/m/vagov6717/1670355600942/8ebd465060e3c6e404292ab065389458a27160f9?sender=uebde62ceb342c6477fb09406) – Note: for clarity's sake you might want to start a new Mural without some of the double screenshots (Wes create those whilst QAing radio component upgrade)
- [Content doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/veteran-military-records/discharge-update/dw-content.md#subway-map) in Github

## Acceptance criteria

>Consider
> - Design / Accessibility reviews
> - Collab cycle requirements
> - Device sizes (mobile first)
> - Documentation updates / Change management
< - [Content model documentation](https://prod.cms.va.gov/admin/structure/cm_document)
> - Testing notes

- [x] PM/DM have migrated Github content doc to a Sharepoint Word doc
- [x] Checked flow chart in Mural, updated as needed to represent all the possible branches of the wizard
- [x] Checked Word content doc, updated as needed to include all content that is presented on all logic branches
- [ ] Added any missing elements into both documents, with some indicator that they are new findings
- [ ] Ensured CAIA (content team) was notified in their [intake ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/63977) that this review has been completed

**Comment by wesrowe** [comment]
@chriskim2311, this is a first step toward rebuilding the DIscharge Upgrade Wizard. We may want to pull this into sprint, so take a look before planning if you can. Be ready with points, questions. Thanks!

**Comment by jilladams** [comment]
From planning: let's migrate the Github content doc to a Sharepoint Word doc, for ease of use. PM/DM will get that done before this ticket begins.

**Comment by chriskim2311** [comment]
@jilladams For this ticket, I have migrated the content doc from github to sharepoint and updated the flow to what we have currently.  

Sharepoint Word Doc: [Discharge Upgrade Wizard Content Doc](https://dvagov.sharepoint.com/:w:/r/sites/SitewidePublicWebsites/Shared%20Documents/Discharge%20Upgrade%20Wizard/DischargeUpgradeWizardContent.docx?d=we399b79e68ae41e282ae042f5a7da6f4&csf=1&web=1&e=ME9fUU)

I also validated the code/content with Jordan's mural flow and that looks good on my end no issues to note.

**Comment by jilladams** [comment]
@thejordanwood  - @chriskim2311  has a source of truth doc for DUW content in prod, and has cross-checked his SharePoint doc against your Mural. 

Sharepoint - https://dvagov.sharepoint.com/:w:/r/sites/SitewidePublicWebsites/_layouts/15/Doc.aspx?sourcedoc=%7BE399B79E-68AE-41E2-82AE-042F5A7DA6F4%7D&file=DischargeUpgradeWizardContent.docx&action=default&mobileredirect=true

I think we could close both this ticket and #15216 now, and share with CAIA, but if it seems wise to have Jordan put eyes on the content doc, or get me to step through it, etc: I'm happy to. Let me know your confidence levels.

**Comment by jilladams** [comment]
(I'm gonna go ahead and share with CAIA.)

**Comment by jilladams** [comment]
Closing, in that case!
