### ISSUE TITLE
Benefits Taxonomy: Enable Content Admins to create/edit Official Name and API ID

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#15222]
### User story

**AS A** Content Admin
**I WANT** to be able to edit Official Benefit Name and API ID fields
**SO THAT** I don't have to rely on a Drupal Admin to use the MVP.

### Engineering notes / background
Custom code has been written that limits those fields to be edited by specific roles. This code can be modified to be more permissive to additional roles.

There's a user permission service that does this, using `hasAdminRole()`. We should leverage this if we're not already.

## Acceptance criteria

- [ ] Content Admins can also create new Benefit Taxonomy terms (in addition to Drupal Admins)

**Comment by chri5tia** [comment]
## Engineering notes ##

Interesting. My former code already uses the isAdmin() service but I will analyze it further. Content admins can't even see the ID field and I think I hid that from all but admins. 
<img width="648" alt="Screenshot 2023-09-14 at 12 03 01 AM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/22764938/db6b56ab-af3e-42c6-9bfd-05048c73b1f6">

![Screenshot 2023-09-13 at 10 59 20 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/22764938/9b293b90-83c9-4d4b-a642-ee7d7403248c)

Ope, never mind, it uses hasAdminRole(). My bad. Note to self to remember.

**Comment by jilladams** [comment]
Verified as Danielle: 
![Screenshot 2023-09-20 at 4 17 00 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/85581471/742be5ea-8101-459a-9525-27f096db86fb)
