### ISSUE TITLE
SPIKE: Document the state of VBA Regional Office testing and prep for Staging Review

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#15223]
## Description or Additional Context 
 Front end testing of VBA Facility content type template from #14940
- Refer to VBA Content Specs XLS linked in #13096

## Where we're at
* This ticket is old. 
* We need to re-refine: we need to assess the current state of testing
* We should think about testing artifacts required for Staging Review: 
    * Regression test plan: https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-regression-test-planRegressionTestPlan
    * QA standards: https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-test-planTestPlan

## QA Test Artifact Required elements
An artifact that corresponds to each standard in the QA Standards.
- Regression test plan
- Test plan
- Coverage for References
- Summary(Defects) reports
- E2E tests (~~provide a link to the product’s code~~ provide a screenshot)
  - [Platform states](https://dsva.slack.com/archives/C0FQSS30V/p1708972084197619?thread_ts=1708969262.182049&cid=C0FQSS30V) Eli's plan is acceptable given our constraints:
 E2E testing really should be done on static data, not on dynamic editor-built data. We can build fake data in a mock and test it with the renderHTML feature of content-build which "renders" the page. This is not the same as rendering the page with cypress and therefore is not a complete E2E test but it is more than component testing and can test edge cases. However, the feature set of the rendered pages in terms of being able to access certain shadow-root components supplied by the DST is limited when testing this way.

  - The pages are not static. They are dynamic. But dynamic drupal content-build not dynamic vets-website. So E2E cypress is a challenge to test or nearly impossible if the drupal content changes which it may do very rapidly.

  - renderHTML doesn't produce any visual output so it doesn't generate artifacts. It's usually outputted just like the unit tests. We could screenshot and highlight the lines of the unit-test output that cover the rendered pages.
- Code coverage (provide a link to the product’s code)

### Example
[PACT Act example](https://github.com/department-of-veterans-affairs/va.gov-team/pull/72058/files#diff-0c7c3b4c1e1f4aeec0c4320ab4aab6636f950fd517cb5e6b2122031e576d8f43)

### QA test artifact specific steps
- [x] [Link to QA artifact](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/regional-offices/engineering/testing-qa.md) 
  - [x] Contains Regression test plan
  - [x] Contains Test plan
  - [x] Contains Coverage for References
  - [ ] Contains Summary(Defects) reports
  - [ ] Contains E2E tests (provide a screenshot and highlight the lines of the unit-test output that cover the rendered pages.)
      - [x]  e2e testing considerations are documented in ticket
      - [ ] Proposal for VBA Regional Offices path forward is documented
      - [ ] Proposal is reviewed with PM for consideration re: any changes we need to request from Collab Cycle or tickets that should be created for follow up work
  - [ ] Contains Code coverage (provide a link to the product’s code)

## Acceptance Criteria
- [x] Document the current state of VBA Regional Office testing (unit, e2e plan) in a QA test artifact
- [ ] Define the work required for VBA test coverage and Staging Review requirements in new tickets

**Comment by xiongjaneg** [comment]
won't be in 102, pausing until 104

**Comment by jilladams** [comment]
From sprint planning discussion: It's very hard to mock data for e2e tests on Drupal dynamic data in content-build. So: we won't ship with e2e tests, if we want to create them: we'll need to figure out what's viable.

**Comment by davidmpickett** [comment]
@eselkin @jilladams 
- I moved all the details about the QA artifact from #16540 into this ticket
- I created a [blank md file](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/regional-offices/engineering/testing-qa.md) in the appropriate file folder

**Comment by davidmpickett** [comment]
@eselkin can you provide an update on the status of this ticket?

**Comment by jilladams** [comment]
85% along

Missing: 
* Risk overview for where our test coverage gaps may pose issues for the product (or not)
* Overview / rationale for testing choices we made

**Comment by jilladams** [comment]
@eselkin fair to say this is in Review / QA? Or you're still working on the bullets above? (With the understanding that we pushed on PPMS a lot this sprint, which may have had an impact.)

**Comment by eselkin** [comment]
I added a section called Traceability which is kind of a combination of Coverage for references and Summary defects.

I did uncover that we could separate a few pieces out into partials and add a test for the partial if we really wanted to have non-manual testing

But now it's fair to say it's in QA or wherever you'd like to put it if your assessment was enough for it to pass QA.

**Comment by jilladams** [comment]
I'm content, merged the PR, and let's close. Based on feedback from staging review, we can sort out next steps.
