### ISSUE TITLE
BE: Ensure required revision log field is visible on promo block forms

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#15242]
### Engineering notes / background

In #15187 it was found that the promo block UI (used for publishing full-width banners?) requires a revision log, but the revision log field is hidden – thus preventing saving. [Example promo block in Prod](https://prod.cms.va.gov/block/6).

<details><summary>Screenshots</summary>

### Error Message:
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/108767736/12a08e94-52f3-4213-9871-1626df43c1e8)

### Editorial Workflow does not populate:
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/108767736/e2c5a8c8-73c4-467f-8d70-ec4aefc64dec)
</details>

## Acceptance criteria

>Consider
> - Design / Accessibility reviews
> - Collab cycle requirements
> - Device sizes (mobile first)
> - Documentation updates / Change management
< - [Content model documentation](https://prod.cms.va.gov/admin/structure/cm_document)
> - Testing notes

- [x] Revision log field shows and is required in Promo blocks, [example](https://prod.cms.va.gov/block/6)
- [ ] Checkbox to optionally include a Revision log should be hidden / removed
- [x] Spelunked codebase to look for any similar block types that might need to be fixed to have a required Revision log

**Comment by chri5tia** [comment]
https://github.com/department-of-veterans-affairs/va.gov-cms/pull/15243 addresses the first AC and is ready to merge. I need to put some more thought or planning into the other two ACs. We need to decide whether or not to hold on the PR or push it. It would be nice if this didn't have to wait a day while I look into the other ACs, which require enough testing to delay this.

**Comment by jilladams** [comment]
Push it!

**Comment by chri5tia** [comment]
Done. I suggest moving the last two ACs to a new ticket and assigning it to me. Call it a 5.

**Comment by jilladams** [comment]
@chri5tia counter-proposal: 
* Your current PR closes #15187 
* When merged, you check off the 1st AC here
* We keep this ticket for the remaining 2 ACs
Less ticketing busy work.

**Comment by chri5tia** [comment]
I am noticing that the CMS announcement block doesn't have a revision log message and seems broken, but shouldn't be affected by my change.
https://prod.cms.va.gov/block/add/cms_announcement

The third AC is done also.

**Comment by chri5tia** [comment]
@wesrowe I was about to post a summary in slack but we just need a ticket for the 2nd AC and I can clean it up.

**Comment by chri5tia** [comment]
@swirtSJW Wanted to get your opinion or validation on an approach. Since the form structure is different on promo blocks, I was going to re-code hiding the checkbox in a different way for promo blocks rather that adjust the form structure to match, which feels more disruptive. You can see that for the time being I had [created an exception for promo blocks](https://github.com/department-of-veterans-affairs/va.gov-cms/pull/15243/files#diff-3ac50fb449172bb531c74d4919048a7f1d9009cb47726ffa7836fbd34de8c4a7R268-R278) as a work around, to close [#15187](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15187). What's your take?

**Comment by chri5tia** [comment]
I found a defect in the PR so I am working to correct it.

**Comment by chri5tia** [comment]
This is ready for review.

**Comment by chri5tia** [comment]
Merged PR and waiting to verify on Prod before closing.

**Comment by chri5tia** [comment]
Verified on prod.
