### ISSUE TITLE
Discovery with internal CMS users and subject matter experts

### ISSUE THREAD

**Issue by BerniXiongA6** [department-of-veterans-affairs/va.gov-cms#15249]
## User Story or Problem Statement
Our goal is to collect insights from internal CMS users and subject matter experts that will inform the development of user stories and use cases for the self-service options available to Drupal CMS editors. 

## What You Need to Know / Additional Context 

- This work can be started after #15246 is completed.
- This work blocks #15247.

## Acceptance Criteria
- [x] Synched with Facilities product and/or delivery (subject matter experts) to gather info
- [x] Synched with CMS support (subject matter experts) to gather info
- [x] If additional folx are identified, synched with other Subject matter experts to gather info

----
For assignee:

**Comment by BerniXiongA6** [comment]
Add to Sprint 95 -- note to @BerniXiongA6 cc: @EWashb

**Comment by BerniXiongA6** [comment]
Hey @joagnitti - Erika mentioned adding CAIA (start with Randi Hecht) to the AC above under the bullet that says "additional folx" -- she will be a great Drupal SME for you! Thanks! cc: @EWashb

**Comment by joagnitti** [comment]
@BerniXiongA6 Sounds good! In that case, I'm going to bump this up to 5 points.

**Comment by BerniXiongA6** [comment]
hey @joagnitti could you update your ticket progress and pipeline since I know you've been working on this -- thanks so much!

**Comment by joagnitti** [comment]
@BerniXiongA6 To clarify, what are you looking for in terms of progress? For example, identify the people I've spoken to so far? Or do you mean something else?

**Comment by BerniXiongA6** [comment]
hi @joagnitti ! Any progress you've made can be left as comments or checked off in the Acceptance Criteria. It helps us to know how far along the work is and if we are blocked or making progress on our sprint goals. Hope that helps!

**Comment by joagnitti** [comment]
@BerniXiongA6 Ohhh 🤦🏻‍♀️ Gotcha loud and clear now. Thanks for being patient with me!

**Comment by BerniXiongA6** [comment]
Hi @joagnitti -- since I was planning to meet with you soon regarding upcoming sprint work, what do you think about usign some of that sync to chat briefly about KB experience too for this ticket? I forgot to mention that I have experience in helping to create a knowledge hub/resource center on a previous project that was very similar to our CMS support.

**Comment by joagnitti** [comment]
@BerniXiongA6 Sounds good to me!
