### ISSUE TITLE
PAW: Research prep tasks

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#15244]
### User story
**AS A** researcher
**I WANT** to prepare for user research sessions
**SO THAT** so they run smoothly and have observers scheduled

### Sprint 93 - 8 points
**Finalize research deliverables**
- [x] Update research plan and conversation guide with current timeline and protocol updates
- [x] Get feedback on conversation guide from Danielle
- [x] Get feedback and approval on conversation guide and research plan from Dave C
- [x] Get feedback on prototype from Danielle and/or Dave C
- [x] Get feedback on research deliverables from Platform at Midpoint Review
- [x] Incorporate all feedback 

**Coordinate with Research-Ops and Perigean**
- [x] Create card in research-repo and recruiting request and submit to VA Research-Ops
- [x] Make agenda for Kickoff meeting w/Perigean
- [x] Review Perigean's recruitment survey 
- [x] Attend Kickoff meeting w/Perigean and Amanda (and optionally Wes)
- [x] Test Zoom login from Perigean 
- [x] Change display name of Perigean Zoom account to "Cindy (Moderator)" 

**Notetaking prep**
- [x] Make note-taking spreadsheet 
- [x] Create a Mural board for research debrief sessions 

### Sprint 94 - 8 points

**Pilots** 
- [x] Recruit pilot participants from Ad Hoc  
- [x] Schedule pilots 
- [x] Schedule team debrief sessions after each pilot 
- [x] Schedule prep time before and debrief time after each pilot 
- [x] Confirm the day before with all pilot participants (and ask one to use smartphone)
- [x] Run pilots 
- [x] Debrief pilots with team
- [x] Make any revisions needed to conversation guide and prototype
- [x] Send thank you slack msg to pilot participants 

**Recruitment / scheduling sessions** 
- [x] Review recruited participant list for requirements met
- [x] Follow-up with Perigean re participant list, if needed
- [x] Make sure all research sessions are in calendar
- [x] Make signup sheet for observers, and share with team, stakeholders to sign up 
- [x] Invite signed up observers to each session and optional debrief session, per signup sheet
- [x] Add participant numbers, dates, and times into recruitment intake ticket Participant Tracker (to check off later after each session) 
- [x] Make notetaking doc in github for each session to share with Perigean right before each session starts (OK with Maria to share them all at once ahead of time)
- [x] Schedule team debrief sessions once a day
- [x] Schedule prep and debrief time for each session
- [x] Slack/email all observers with instructions

## Acceptance criteria

- [x] All preparation done before the first day of research sessions

**Comment by cindymerrill** [comment]
Will share with Dave C as requested:

- Invited Danielle to review the **prototype** in this [slack thread from Sept 7](https://dsva.slack.com/archives/C52CL1PKQ/p1694124510415769) and in the thread asked for feedback by COB Sept 11 if possible
- Pinged Danielle and Dave to provide feedback on the **prototype** in this [slack thread from Sept 11](https://dsva.slack.com/archives/C52CL1PKQ/p1694448689506229)
- Invited Danielle and Dave to provide feedback on **conversation guide** in this [slack thread from Sept 11](https://dsva.slack.com/archives/C52CL1PKQ/p1694458865387489)

- Invited Danielle and Dave to review the **prototype** before Sprint Demo in this [slack thread from Sept 12](https://dsva.slack.com/archives/C52CL1PKQ/p1694536552600009)

**Comment by cindymerrill** [comment]
Removed screen reader references from research plan and conversation guide, per decision made at Sprint Planning today.

**Comment by cindymerrill** [comment]
Reviewed Dave Conlon's feedback on conversation guide and made revisions.

**Comment by cindymerrill** [comment]
Reviewed Danielle's feedback on conversation guide and made revisions.

**Comment by cindymerrill** [comment]
Since Dave Conlon already gave me feedback on the research plan and conversation guide, and I've made all the changes he suggested, @aklausmeier  recommended that I moved forward with the assumption that both documents are "approved with changes". So I'll check that off in the task list at the top of the ticket.

**Comment by cindymerrill** [comment]
Had the Midpoint Review meeting today, and there were no changes that I was asked to make. Seems like the prototype wasn't reviewed all that closely, and neither were my research plan or conversation guide. I got approval to go ahead and launch recruiting with the VA Research Ops team, and Dave Conlon and Danielle Thierry were on board with this. So, now I'm unblocked and off to the races :)

**Comment by cindymerrill** [comment]
I just want to note that I never received any feedback on the prototype from Dave Conlon, and nothing detailed from Danielle. I'm assuming that everyone's all OK with it. Usually feedback is delivered on the content during a Midpoint Review, but since the content was provided by Danielle and not modified, it was all great as usual.

**Comment by cindymerrill** [comment]
Created and submitted [card in research repo](https://github.com/department-of-veterans-affairs/va.gov-research-repository/issues/385) and a participant [recruitment request](https://github.com/department-of-veterans-affairs/va.gov-research-repository/issues/387). Now I wait to hear back from VA Research Ops when they launch recruiting. FYI @jilladams @wesrowe .

**Comment by cindymerrill** [comment]
Shane Strassberg approved the research study and passed along my recruitment request to Perigean, who I heard back from. I tested the zoom login they provided.

**Comment by cindymerrill** [comment]
I made a notetaking spreadsheet.

**Comment by cindymerrill** [comment]
Maria from Perigean shared a recruitment survey with me, which I provided feedback on during the kickoff meeting this morning. Amanda and Wes also attended the meeting. Two issues came up, which I posted about [in slack here](https://dsva.slack.com/archives/C52CL1PKQ/p1695319252663039) for Danielle to weigh in on.

@jilladams @wesrowe Now I'm all done with all research prep tasks for this sprint. I might start recruiting a couple Veterans for pilot tests next week.

**Comment by cindymerrill** [comment]
Worked with Wes and Amanda to come up with 3 time slots for pilot testing next week (Tue-Thu), and posted a request to Veterans at Ad Hoc. Next week (after my PTO on Monday), I'll schedule whoever volunteers and let Perigean know.

**Comment by cindymerrill** [comment]
Scheduled 2 pilot participants for testing, and ran the first one today.

**Comment by cindymerrill** [comment]
Ran the second pilot test today. Reviewed recruited participant roster from Perigean, worked with Maria to swap out some participants and reschedule the session on Oct 9. Reviewed updated participant roster, updated observer signup sheet, and shared it with Dave and Danielle.

**Comment by cindymerrill** [comment]
Completed many more prep tasks. Will finish the last few tomorrow.

**Comment by cindymerrill** [comment]
Completed ALL tasks in preparation for research sessions, which start on Monday. @jilladams
