### ISSUE TITLE
Set up user and role for Next/Drupal CMS Preview

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#15245]
## Requirements

Next Drupal expects a user with certain permissions to be available to enable access to protected content (i.e. drafts & archives). We need this user set up and the required permissions assigned to a role and granted to that user.

```[tasklist]
### Acceptance criteria
- [x] A role is created that contains the necessary permissions for Next Drupal CMS Preview
- [x] A user is created per the CMS Team instructions to be the Next Drupal CMS Preview user, and is assigned the role with required permissions
```

## Background & implementation details

Next Drupal describes what needs doing for the User here: https://next-drupal.org/learn/preview-mode/create-oauth-client#1-create-role

Note that their instructions are oriented towards doing this in the Admin UI. We should follow our own procedures for managing config.

Re creating the user, see this document: https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/READMES/drupal_api_users.md
```[tasklist]
### Implementation tasks
- [ ] Use this if it helps you or feel free to delete.
```

**Comment by timcosgrove** [comment]
Slack discussion: https://dsva.slack.com/archives/CT4GZBM8F/p1694632191290119

Questions (and answers per @ndouglas ):

> The user needs the following permissions: Bypass content access control, Issue subrequests, View user information. I wanted to run that by the team, since Bypass content access control in particular has security implications.

I'm curious as to why Bypass content access control is needed, but not particularly opposed.

> Can/should we use content_build_api for this purpose? I have no plus/minus here. The things the user will be doing are different from what it currently does (JSON:API vs GraphQL) so if we needed to track down issues by user, it would be easy to do so. OTOH, it's trivial to create a distinct user/role.

No, let's create a new user.

> If we do want a separate user, what's the protocol for creating it? I see that content_build_api has no email address, which at a glance says to me that it was not set up in the interface. If there's a regular procedure for setting up a user like that, we should follow it, and/or decide what email should be on the user.

Let me get back to you on that. I don't think we have documentation for this area, and we should.

**Comment by schiavo** [comment]
Waiting for user to be created. [Ticket](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15362)

**Comment by schiavo** [comment]
User has been created
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/7717261/ab4c4c2e-12ee-4577-8d8a-161e13c61304)

and the role has been assigned
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/7717261/a28700d8-6c07-4a5b-b1db-386e6db7ac27)
