### ISSUE TITLE
Data collection and analysis for user needs

### ISSUE THREAD

**Issue by joagnitti** [department-of-veterans-affairs/va.gov-cms#15246]
## User Story or Problem Statement
Our goal is to identify user needs and gather insights that will inform the development of user stories and use cases for the self-service options available to Drupal CMS editors. 

## Acceptance Criteria
- [x] Insights about editor interactions (with self-service options) has been collected
- [x] That data above has been analyzed
- [x] Synched with Berni on Jira dashboard walkthrough
- [x] At least 3 user needs have been identified
- [x] At least 3 user challenges have been identified

----
For assignee:
## Steps for Implementation / To Do Tasks
- Collect insights about editor interactions with self-service options (e.g., their options, preferences, any pain points) via analytics, internal stakeholders, past surveys, and other past research.
- Analyze the data collected to identify common user needs and challenges in using self-service options.

**Comment by BerniXiongA6** [comment]
Hi @EWashb -- could we get your sign off to approve a seat on our Jira Service Desk license for @joagnitti so she can complete her discovery? You can reply here and I'll share this with my IT dept. Thanks!

**Comment by EWashb** [comment]
@BerniXiongA6 Approved!

**Comment by joagnitti** [comment]
@BerniXiongA6 @EWashb Thank you!! This is exciting.

**Comment by joagnitti** [comment]
Working doc: https://cityfriends-my.sharepoint.com/:w:/g/personal/joannagnitti_cityfriends_onmicrosoft_com/Ee4_S_MwVBtCiFR5Yz-CJuoBKFVUeQjA6hfjfVbVf95IVw?e=oCYMLm
