### ISSUE TITLE
Update KB sidebar link about Homepage

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#15258]
### User story

**AS AN** Editor
**I WANT** the sidebar alongside KB articles to link to the "VA.gov Homepage product guide" instead of "Homepage alerts and banners"
**SO THAT** the link is consistent with the content.

## Acceptance criteria

- [x] In KB sidebar, "Homepage alerts and banners" link is replaced with "VA.gov Homepage product guide"
- [x] It links to that article: `https://[ENV].cms.va.gov/help/vagov-homepage-product-guide`

**Comment by jilladams** [comment]
![Screenshot 2024-01-25 at 12 11 36 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/85581471/2fd533b4-9e15-4f45-a40f-39b999a52475)
