### ISSUE TITLE
Research Plan: Federal Header/Footer

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#15256]
### User story

**AS A** Researcher
**I WANT** to plan out the research
**SO THAT** we agree on research goals, methods, and recruiting criteria

## Acceptance criteria - S94
- [X] Cindy and Amanda to discuss research strategy and decide if this is a good candidate for EnjoyHQ pilot -- I believe we're going to do this because it was already decided

## Acceptance criteria - S96 5 points
- [x] Research plan drafted
- [x] Amanda revises draft 
- [x] Cindy reviews research plan w/updates
- [x] Cindy and Amanda discuss feedback on research plan 
- [x] Cindy revises research plan per discussions with Amanda in S96
- [x] Get lessons learned and best practices for assistive tech recruiting from [Forms team](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/tree/main/research/2023-09-form-header-usability-testing) and other studies
- [x] Copy research plan from Word to GitHub
- [x] Ready for Amanda to share research plan with stakeholders

## Acceptance criteria - S97 1 points
- [x] Move notes for conversation guide into a new document

## Acceptance criteria
- [x] Review secondary research insights #15278 to help inform potential research goals and strategy
~Need to plan for capturing a "before shot" of analytics (quant research): VCL, Sign In, Search, etc. (this is in a separate ticket)~
- [x] Research plan shared with PO for feedback (Amanda)
- [x] Feedback incorporated
- [x] Finalized Research Plan added to GitHub (Cindy)
- [x] Updated Research Plan in Enjoy HQ (Amanda)
- [x] Research Plan sent to stakeholders (Amanda)

## Acceptance criteria - S98 5 points
- [x] Research timeline discussed with team
- [x] Research timeline incorporated into Research Plan on github
- [x] Update Research Plan in Enjoy HQ under [Research Plan](https://app.enjoyhq.com/sh/pj/1d6fd889-5992-4819-b7da-3a11b52a7b86), on "plan tab" -- DEFERRED to prep tasks ticket so plan to do when launch recruiting (because there will be more small tweaks until then)

## Future sprints
- [ ] Make new version of research plan for Phase 2 (AT), and go through reviews again

**Comment by cindymerrill** [comment]
Reviewed my notes and added a few items to the [draft research plan doc](https://dvagov-my.sharepoint.com/:w:/r/personal/cynthia_merrill_va_gov/Documents/Header%20Footer/Research%20plan%20for%20Header%20Footer.docx?d=wdd224c755935414d9ceedb78d3f72074&csf=1&web=1&e=rLe90D).

**Comment by aklausmeier** [comment]
@cindymerrill moved this to in progress as it's one of my current priorities. I'm working on a research plan draft and will ping you when ready to review. 

cc: @jilladams

**Comment by aklausmeier** [comment]
@cindymerrill [research plan](https://dvagov-my.sharepoint.com/:w:/r/personal/cynthia_merrill_va_gov/Documents/Header%20Footer/Research%20plan%20for%20Header%20Footer.docx?d=wdd224c755935414d9ceedb78d3f72074&csf=1&web=1&e=rLe90D) draft is complete, please review and add any questions/concerns using the comments feature

**Comment by cindymerrill** [comment]
@aklausmeier I reviewed the research plan draft and left a LOT of comments in the doc--some typographical and others about the research. I'm happy to discuss any or all of them with you. Let me know if you want to talk.

**Comment by cindymerrill** [comment]
@aklausmeier FYI I've been making a lot of changes to my comments on the recruitment screener questions, based on slack conversations I've been having today with other Ad Hoc researchers.

**Comment by aklausmeier** [comment]
@cindymerrill Go ahead and make the grammatical corrections and delete those comments from Word. I'll review the research related comments in Word later this afternoon.

**Comment by cindymerrill** [comment]
OK, but I'm going to leave some wording ones that I want to talk with you about. I'll just fix the corrections where the fix is obvious.

**Comment by cindymerrill** [comment]
@amanda and I had a great collaborative meeting today where we discussed a lot of my feedback and revised the research plan. We have more to do about recruitment, especially of assistive tech users. 
Amanda asked me to work on revising the research plan more, but this work will likely wait until next week, which may or may not be included in this sprint. 
FYI @jilladams @FranECross. I revised the point estimate from 3 to 5, based on the amount of work that I did while reviewing and discussing the research plan.

**Comment by cindymerrill** [comment]
I made all the recruiting updates that I discussed with @aklausmeier , but I still have too many screening questions (I currently have 8, and I believe there’s a limit of 7). I posted in [#research-ops](https://dsva.slack.com/archives/C0216PL32HJ) for feedback: https://dsva.slack.com/archives/C0216PL32HJ/p1699316002093229

Tomorrow I'll check what responses I get, potentially revise what I have, and then let Amanda know when I'm done.

**Comment by cindymerrill** [comment]
@jilladams @FranECross FYI I just moved 2 of the S97 tasks into S96 because I finished them yesterday

**Comment by aklausmeier** [comment]
@cindymerrill Dave Conolon has reviewed and approved research plan. Next step is to for you to move it from Word to GitHub and I will then share with our stakeholders with the GitHub link.

**Comment by cindymerrill** [comment]
@aklausmeier I can do that now. Did Dave C have any feedback on the research plan? I see from a comment that he perhaps changed the order of the research goals. Did anything else change?

**Comment by aklausmeier** [comment]
> Did Dave C have any feedback on the research plan? I see from a comment that he perhaps changed the order of the research goals. Did anything else change?

@cindymerrill  Very minimal: Reordering of goals/hypothesis and some rewording of first paragraph in Background.

**Comment by cindymerrill** [comment]
@aklausmeier Should I document at the bottom that the research plan has been approved by Dave Conlon, or should I wait until later when we have the timeline specified?

**Comment by aklausmeier** [comment]
It's ok to say he approved it. Timing will be determined after Figma prototype is ready.

**Comment by aklausmeier** [comment]
@FranECross @jilladams do you think the following AC should be removed from this ticket. We have analytics #14476 ticket for footer and Fran and I discussed spinning up a ticket for the header in that ticket comments. 

> Need to plan for capturing a "before shot" of analytics (quant research): VCL, Sign In, Search, etc.

**Comment by cindymerrill** [comment]
@FranECross @jilladams I've added a few more tasks to the top of this ticket for S97, but some of them belong in a new conversation guide ticket. I just revised the conversation guide ticket template this afternoon, so as soon as I get feedback on it and it merges, we can use it to create the new ticket. If we need a ticket sooner than that happens, then I can simply copy the markdown from my ticket template into a new ticket.

**Comment by cindymerrill** [comment]
@aklausmeier Just finished copying the research plan from Word into github. You can find it here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/header-footer/federal-standardized-header-footer/research/phase1-no-AT/research-plan.md

Let me know if you see anything that needs revising.

**Comment by FranECross** [comment]
> @FranECross @jilladams do you think the following AC should be removed from this ticket. We have analytics #14476 ticket for footer and Fran and I discussed spinning up a ticket for the header in that ticket comments.
> 
> > Need to plan for capturing a "before shot" of analytics (quant research): VCL, Sign In, Search, etc.

@cindymerrill Yes, I agree and will remove that AC. Thanks for catching that! cc @jilladams

**Comment by cindymerrill** [comment]
@FranECross FYI It was @aklausmeier who commented about the analytics AC, not me.

**Comment by aklausmeier** [comment]
@cindymerrill plan in GitHub looks good, I'll send to stakeholders today and update in EnjoyHQ. 

We will want to pilot EnjoyHQ during this study and we can discuss what that means when we meet tomorrow.

**Comment by cindymerrill** [comment]
I won't bother deleting the convo guide ideas section from the Word document, but I've copied it into another working document to collaborate with Amanda on in preparation for writing the conversation guide.

**Comment by cindymerrill** [comment]
Created new conversation guide ticket (#16072) and moved the relevant AC's from this ticket over to there. Now done with my work on this ticket for this sprint. @FranECross @jilladams

**Comment by cindymerrill** [comment]
Added timeline, though waiting to hear from @aklausmeier on reducing the number of people recruited from 14 to 12, and also her availability for a kickoff meeting with Perigean.

Slack thread re recruiting: https://dsva.slack.com/archives/C52CL1PKQ/p1701736862870349

**Comment by cindymerrill** [comment]
Revised timeline section and split out Phase 2 info into a separate research plan [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/header-footer/federal-standardized-header-footer/research/phase2-AT/research-plan.md). Done with AC's for this sprint. Will need to come back when work on Phase 2 research in Jan/Feb 2024.

**Comment by cindymerrill** [comment]
On second thought, I'm closing this ticket and will plan to create a new one for the phase 2 research with assistive tech users in early 2024. FYI @jilladams @FranECross @aklausmeier
