### ISSUE TITLE
Review of new or updated KB article : How do I update my Vet Center Facility's Basic Location Data?

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#15257]
## Which article(s) need review?
Provide the link to latest revision of each article that requires review.
- https://prod.cms.va.gov/node/23533/latest

Added line to the table for a missing facility.  

## Priority or deadline for request
Choose either Deadline or a priority:

- [ ] Deadline: [name the deadline here]
- [ ] Priority:
  - [ ] Critical
  - [ ] High
  - [ ] Medium
  - [x] Low
  
## Can article(s) be published?
Once the article has been fully reviewed, can the article(s) be published? For example, is anything tied directly to an upcoming feature and this information should not be published until the feature is on production?
- [x] Yes, all article(s)s within this ticket can be published once reviewed
- [ ] No, the article(s) within this ticket should not be published and should only be reviewed

## Acceptance Criteria
- [x] Article reviewed by CMS Team
- [x] If approved above, article is published
- [x] Requesting person/team has been notified that article was reviewed/published

**Comment by BerniXiongA6** [comment]
Hi @xiongjaneg I'll add this to our Sprint 93 prerefinement and will follow up with you soon. Thanks!

**Comment by BerniXiongA6** [comment]
Changes are approved -- you may publish your draft @xiongjaneg !
