### ISSUE TITLE
Monitoring enhancements for API-driven Public Websites products

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#15262]
## Status
- **[2024-07-08] [Fran]** Moved to the Ready column and tagged with Sprint 10 for Chris K to pick up.

## Top-line Description / Goal(s)
How might we ensure a better site-user experience through proactive alerts and monitoring of the things PW owns or uses?

#### Monthly project updates:

---

## Headlines
**VA stakeholders** - 

**OCTO lead** - Dave Conlon

**Is this project tracked to an upcoming event or congressional deadline?** - No

## Details

**Which OCTO team should do this and what is currently on their roadmap?** - Sitewide (Public Websites)

**Which OCTO priority does this work support?** - 

**What is the user impact and scale of impact?** - 

**Who would manage this product long term?** - Public Websites

**How much leverage will this create to solve more problems in the future?** -  

**How great is the cost of inaction? (e.g., Can it wait? Must it be done by us?)** - 

---
An epic to capture monitoring for PR products like:
- Find-a-form
- Income Limits
- Site search

### User story

**AS A** Veteran
**I WANT** the Public Websites team to be automatically notified of major issues with the site
**SO THAT** I don't encounter them.

**AS A** VA stakeholder
**I WANT** the Public Websites team to be automatically notified of major issues with the site
**SO THAT** my users aren't affected.

## Acceptance criteria

>Consider
> - Design / Accessibility reviews
> - Collab cycle requirements
> - Device sizes (mobile first)
> - Documentation updates / Change management
< - [Content model documentation](https://prod.cms.va.gov/admin/structure/cm_document)
> - Testing notes

- [ ]

**Comment by davidconlon** [comment]
Adding additional monitoring for search

**Comment by mmiddaugh** [comment]
**Update 6.7.2024**
- Most of the planned monitoring has been implemented and recently adjusted
- Pending: Refine Datadog monitor for Forms GET alarms #17964

**Comment by mmiddaugh** [comment]
Recently adjusted monitors which were alarming to Service Now to ensure only the most relevant outages hit their radar with the appropriate thresholds 
Consider this work now complete
