### ISSUE TITLE
Create new runbook for New VAMC system 

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-cms#15264]
## Description
The best time to document the steps necessary for creating a new VAMC system in CMS may be when the situation actually occurs. 

```[tasklist]
### Items to address from #19271
- [x] Indicate which items need manual URL aliases and which can be auto
- [x] Consider Moving menu settings from VAMC sitemap in sharepointt into the runbook instead
- [x] move enable Menu Breadcrumbs module step up higher in runbook
- [x] Explain add menu to CONTENT BUILD FILE step better
- [x] "Create users if need / assign users to the appropriate section [link to KB article]" - need to find the KB if it exists, or write a ticket to make one if it doesn't
- [x] UPdate "Do all the things listed here" to "Do all the things listed in the VA Medical Centers (VAMCs) Knowledge base article
- [x] "Do we have an editor facing checklist for content entry / tasks that gate publishing like we do for VBA?" - answer this and update in the runbook
- [x] We need to figure out how to help Helpdesk or Editors know where to copy from to generate all the random un-hardened pages (e.g. Programs, etc.). There used to be template pages from 2021, we think, but they've aged and content isn't up to date. Can we say: copy from the most recently edited version from another VAMC / fix links? What's reasonable?
- [x] Sidenav: we say to use the Services/Locations and Events fake headers in the menu, BUT: a11y has said we want to move away from that paradigm. So: the runbook is advising an old pattern.
```

## Artifacts produced
- [Sitemap of a VAMC system in sharepoint](https://dvagov.sharepoint.com/:x:/s/SitewideContract/EblgAS21OUtHloKK3a8ZvNIBHzV1S6uO2l4hj4dqYG0avQ?e=J8UVZh).
- Static copy for convenience [VAMC Sitemap.xlsx](https://github.com/user-attachments/files/16787919/VAMC.Sitemap.xlsx)
- [Runbook template file](https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/.github/ISSUE_TEMPLATE/runbook-new-vamc-system.md)

## Acceptance Criteria
- [x] a new runbook has been created in the form of a github issue template
- [x] Distinguish between steps that need Drupal admin user vs engineering support vs editor tasks
- [ ] Review with help desk
- [x] supporting KB articles are created and/or updated https://prod.cms.va.gov/help/vamc/managing-vamc-sites-as-a-content-admin
- [x] Update [content model documentation](https://prod.cms.va.gov/admin/structure/types/manage/health_care_region_page/document)
- [x] https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/flagged-facilities.md is updated with runbook link / notes

**Comment by mmiddaugh** [comment]
This is blocked until the situation arises

**Comment by jilladams** [comment]
Noting that we've added this ticket to the VA Manila epic, since this will be technically a new facility that is a new system.

**Comment by davidmpickett** [comment]
As part of my work on Manila I created a excel sheet of the typical sitemap of a VAMC system. I've placed it in [sharepoint](https://dvagov.sharepoint.com/:x:/s/SitewideContract/EblgAS21OUtHloKK3a8ZvNIBHzV1S6uO2l4hj4dqYG0avQ?e=J8UVZh).

**Comment by davidmpickett** [comment]
[Shared status on slack](https://dsva.slack.com/archives/C0FQSS30V/p1724883189380759)

**Comment by jilladams** [comment]
Moving back to Ready, per https://dsva.slack.com/archives/C0FQSS30V/p1724886294559659?thread_ts=1724883189.380759&cid=C0FQSS30V

**Comment by jilladams** [comment]
Menu updates required, this will progress in Sprint 13 as we go through publishing Manila.

**Comment by jilladams** [comment]
I made https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19271 as a test drive of the stubbed runbook and am stepping through. Will flag questions there for Manila, and we can close loop on the runbook template itself when that's done.

**Comment by davidmpickett** [comment]
Note to self to update runbook for this https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19271#issuecomment-2362381368

**Comment by davidmpickett** [comment]
**Mid-sprint update:** Had a good conversation with @jilladams and @Agile6MSkinner today about Manila and which items we should update in the VAMC system runbook. Have added those as a task list to this ticket. Unsure if I will have time to get to them this sprint given CA retreat next week and other work in progress.

**Comment by davidmpickett** [comment]
**End of Sprint Update** 

@jilladams @Agile6MSkinner @mmiddaugh I updated the runbook to address the items that Jill found during this sprint. There are likely to be more discoveries as we continue with Manila, so I think we should probably keep the ticket open until Manila is launched, but I don't think there's anything else to do at this time

**Comment by davidmpickett** [comment]
Unassigning myself until this is actionable again

**Comment by davidmpickett** [comment]
@jilladams Does this belong in Progress? There's no current actionable work identified here. Suggest moving back to Admin/Workflow

**Comment by jilladams** [comment]
@davidmpickett thanks for flagging - I might propose we go over this runbook with Helpdesk at the next Flagged Facilities touchpoint (Thurs 11/7 11:35a CT, I'll invite you) and then call it closed, since Manila is all but shipped and we know now what we will know about the runbook. Thoughts?

**Comment by davidmpickett** [comment]
Works for me.

**Comment by jilladams** [comment]
Reviewed with Helpdesk today. Closing
