### ISSUE TITLE
Content release queue getting too big

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#15272]
## User Story or Problem Statement
We use advanced_queue to manage our content release queue.  Currently the content release queue has 21,000 items in it.
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5752113/78515c47-b919-42ea-9599-9b119e77997f)

This is because no cleanup was ever specified for it
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5752113/6f00a78b-8eae-49c9-bd2a-7a4005ecf88a)

This queue will continue to get larger and larger without any good reason for it to be.  ~Also since advanced queue does de-duping, this gets pretty intensive as the queue gets larger.~ Edit:  Advanced_Queue does not dedupe.

## Acceptance Criteria
- [ ] "Remove completed items" is set to 7 days.
- [ ] "Completed jobs state to remove" is set to "Both failed and success state"

## Team
Please check the team(s) that will do this work.

- [x] CMS Team
- [ ] Public Websites
- [ ] Facilities
- [ ] User support
- [ ] Accelerated Publishing

**Comment by BerniXiongA6** [comment]
Hi @ndouglas could we have you preview this to see if we have enough info to bring into pre-refinement discussion?

**Comment by ndouglas** [comment]
@BerniXiongA6 It's trivial. I opened a PR #15285 to close it.
