### ISSUE TITLE
Secondary Research: Federal Header/Footer

### ISSUE THREAD

**Issue by aklausmeier** [department-of-veterans-affairs/va.gov-cms#15278]
## Description

**Prior Related Research Studies**
•	[06-2023 Health Wayfinding](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/digital-health-modernization/mhv-to-va.gov/overall-content-IA/2023-06-health-wayfinding-study)
•	[04-2023 Landing Page User Research Study](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/digital-health-modernization/mhv-to-va.gov/landing-page/research/2023-03-Landing-Page-User-Research/2023-04-landing-page-readout.md)
•	[04-2021 Homepage Wayfinding](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/public-websites/research/202104-baseline-wayfinding)
•	[10-2022 VA.gov Home Page Redesign ROUND 2 Usability Testing](https://github.com/department-of-veterans-affairs/va.gov-research-repository/issues/184)

### User story
> _Describe the audience/user, enhancement or fix, and value / outcome desired._

**AS A designer and researcher**
**I WANT to know what related insights exist from prior research**
**SO THAT I can solve for issues in the design and better prepare research goals and strategy.**

## Acceptance criteria

- [x] Identify existing related research studies
- [x] Summarize [synthesis of insights in GitHub](https://dvagov-my.sharepoint.com/:w:/g/personal/amanda_klausmeier_va_gov/EXQL0olAz5lBrVbgEJKSjywBTnJqi7TDvlL3TKkcKj3i0A?e=KToIwX)

**Comment by cindymerrill** [comment]
@aklausmeier How does this ticket relate to the ticket that @wesrowe created yesterday (https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15256)?

**Comment by aklausmeier** [comment]
@cindymerrill  I was in the process of duplicating the ticket you referenced to create this ticket for the work I've done on Secondary Research synthesis. I think you just caught it before I updated the title and details.

**Comment by cindymerrill** [comment]
The duplication sent me an email notification, perhaps because I was assigned to the other ticket :)

**Comment by aklausmeier** [comment]
**Takeaways to consider for Primary Research Plan in #15256 :**
1)	Follow up for Insight 1 in [Research Synthesis](https://dvagov-my.sharepoint.com/:w:/g/personal/amanda_klausmeier_va_gov/EXQL0olAz5lBrVbgEJKSjywBTnJqi7TDvlL3TKkcKj3i0A?e=KToIwX), do users still struggle finding MHV and MyVA?
2)	Task Flow Analysis of Nav IA
3)	Mega Menu IA may not be impacted (out of scope)
4)	Capture current analytics as a baseline measurement for header and footer and especially include VCL as reduction in clicks may result in a stop failure, in design the VCL will be a lower tab order
5)	Must test with screen readers, assistive technology
a.	Can they locate VCL, MyVA, MHV, etc using assistive technology
6)	Recruiting for screen readers was difficult during [10-2022 VA.gov Home Page Redesign ROUND 2 Usability Testing](https://github.com/department-of-veterans-affairs/va.gov-research-repository/issues/184) because they were not able to use their assistive tech on the mobile prototype, participants stating they normally use desktops when they absolutely need to use a screen reader. 
a.	Possible solution: mobile and desktop prototypes for accessible accommodations as done in the [06-2023 Health Wayfinding](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/digital-health-modernization/mhv-to-va.gov/overall-content-IA/2023-06-health-wayfinding-study) study.
7)	How do we measure sentiment on USA logo, VA Seal (missing “VA” lockup), USA and VA Seal lockup in footer?

cc: @cindymerrill @davidconlon
