### ISSUE TITLE
[cms-ci] Site rebuild doesn't work when choosing a branch

### ISSUE THREAD

**Issue by howardbrande** [department-of-veterans-affairs/va.gov-cms#1527]
**Describe the defect**
When rebuilding an environment on DevShop, choosing 'Master branch' on CMS and WEB version dropdowns and choosing to destroy the current environment and rebuild with latest CMS prod content is causing builds to fail. However, not selecting 'Master branch' is not bringing in the most current content from CMS prod

**To Reproduce**
1. Go to http://devshop.cms.va.gov/hosting/c/howie.demo.ci.cms.va.gov
2. Click on 'rebuild environment' at the top of the list on the right
3. Scroll down and click on 'Change Code Versions'
4. Change CMS Version to 'Main branch (master) - Current revision
5. Change WEB version to 'Default branch (master) - Current revision
6. Scroll down and click on 'Advanced options'
7. Click on 'Destroy howie CMS site....'
8. Click on 'Rebuild environment'

**Expected behavior**
For the build to be successful and there be the most up to date content from PROD CMS

**Screenshots**
![Screen Shot 2020-04-20 at 10.02.51 AM.png](https://images.zenhubusercontent.com/5d2601b9de59d60b5978e81e/1bc2d0bf-00e9-43cb-925d-9772409b8048)

**Desktop (please complete the following information if relevant, or delete):**

**Additional context**

## Labels
- [/] Issue type (red) (defaults to "Defect")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [/] CMS objective (orange) (not needed for bug tickets)
- [ ] CMS-supported product (black)

**Comment by ElijahLynn** [comment]
Closing for now as we are likely moving off of DevShop.
