### ISSUE TITLE
Number of revisions not limited on all content types

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#1528]
**Describe the defect**
When visiting /admin/config/content/revisions-autoclean there are several content types that have a limit of 0 set which translated to unlimited revisions.  All should have some limit set.   

As a site admin I want to know that the number of tracked revisions does not get out of hand and create a burden for the site in terms of size of the revisions table.

Also need to disable the cron processing since none of ours are set to expire on age, only count.
![image](https://user-images.githubusercontent.com/5752113/79763634-564ffa80-82f2-11ea-8c35-a043742630fe.png)

Acceptance Criteria
- [ ] Determine what the limits should be for each content type that does not have a limit.
- [ ] Disable the cron method.
- [ ] Create a limit for each type and export the config.
 

## Labels
- [/] Issue type (red) (defaults to "Defect")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [/] CMS objective (orange) (not needed for bug tickets)
- [ ] CMS-supported product (black)

**Comment by kevwalsh** [comment]
@swirtSJW Please include me in the conversation about how many revisions to keep per content type.

**Comment by swirtSJW** [comment]
@kevwalsh We found an issue related to the cron side of this module.  The queue for removing revisions on cron run had bloated up the DB by 2.8G     If all entities are only being limited by number, and not by age, then the cron option can be disabled.   I set all the instances that were set to 0 (unlimited) I set to 50.   The ones that were already set to 200 I left as is.  Do you think there are some that should have different numbers?
