### ISSUE TITLE
CMS Styles not correct

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#15298]
## Describe the defect
The styles in the CMS are not correct. You can most clearly see this on the buttons on the edit nodes, they are not displaying properly:

![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/106678594/e3fce081-0641-4a8e-89ad-1ca6f644d341)

A couple other things I have noticed:
- The blue on the buttons is not quite right, it should be a va color variable but it's a Hex value:
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/106678594/e6835dc1-21a2-4bbc-bd44-dd2a95cafb1b)
- Breadcrumbs I'm pretty sure are bolder than they should be

## To Reproduce
1. Go to any edit node
2. Scroll down to the bottom to where the Save and Unlock buttons are
4. Notice the incorrect display/style

### Team
Please check the team(s) that will do this work.

- [x] `CMS Team`
- [ ] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`
- [ ] `Accelerated Publishing`

**Comment by ndouglas** [comment]
Yes, there's something weird going on. There's a discrepancy in styles between the Tugboat base preview and Staging, even though they're running the same commit:

Tugboat base preview:
![Screenshot 2023-09-19 at 8 34 00 AM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/1318579/090b961e-bf1a-4ab5-853a-947dc4b57a04)

Staging:
![Screenshot 2023-09-19 at 8 34 46 AM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/1318579/afc319c0-eb8f-4179-a1b6-96a9d012fe02)

(Note that prod behaves identically to staging here)

**Comment by ndouglas** [comment]
Tugboat:
![Screenshot 2023-09-19 at 8 36 56 AM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/1318579/0b01136f-cfb2-4cf1-aa10-2ad8b72e6c4b)

Staging:
![Screenshot 2023-09-19 at 8 37 03 AM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/1318579/96c784a0-a909-4e83-850e-fb7fee3bb4f3)

**Comment by ndouglas** [comment]
Is this affected by updating the Design System, @edmund-dunn?
