### ISSUE TITLE
Document the winnower

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#15291]
## User Story or Problem Statement
AS A Drupal engineer
I WANT TO understand the existing options / logic available to me for displaying only necessary sections to Editors in the Section selector
SO THAT I can provide the best CMS UX.

## Description or Additional Context 
Facilities uses the winnower to manage which sections appear in the Sections dropdown based on permissions. Other teams would benefit from this logic / option as the CMS expands, primarily Public Websites for starters on the Events national calendar project. 

Facilities built and uses the winnower.  We need to document it for the community.

## Acceptance Criteria
- [x] Documentation has been created in a logical place Drupal engineers might look for it, for how the winnower works

**Comment by jilladams** [comment]
ACs are deliberately agnostic about where the documentation should live. Drupal engineers should be able to find it when dealing with the Sections dropdown / roles and permissions. 

This is also probably worth a Topic Dive.

**Comment by davidmpickett** [comment]
Given that @omahane is deep in the winnower as part of #15901, this might be a good ticket to bring into next sprint to update documentation while it's fresh in his brain.

@xiongjaneg @jilladams consideration for pre-refinement

**Comment by jilladams** [comment]
I think this belongs in the CMS documentation somewhere. The winnower is ultimately a (function? feature?) that applies to the CMS UI/UX, and I think there's not a current logical spot where those things go. 

I could make a case for 2 options: 
1. Within https://github.com/department-of-veterans-affairs/va.gov-cms?tab=readme-ov-file#table-of-contents, add a section for: "Reusable UI functions" or somesuch more accurate technical label for what the Winnower really is. And add it there.
2. Add it to the Content Model documentation, https://prod.cms.va.gov/admin/structure/cm_document, like we've done with Breadcrumbs. We know this is a temporary location, and it'll likely move somewhere else in future. 

I don't think the CMS Team is in a position to spend much time considering the question at the moment, so I think I might put it back to @omahane (or maybe @dsasser as a Drupal brain also who may need the winnower one day? And who is OOO now til 1/16) as to where you all might look for this information? We can go ahead and put it where we think it makes sense for now, and consult with the new CMS Team once they're onboarded for more insight as to where this sort of info belongs in future. Thoughts?

**Comment by omahane** [comment]
This has been documented here: https://prod.cms.va.gov/admin/structure/cm_document/process/130/winnower

**Comment by xiongjaneg** [comment]
Verified documentation in prod
<img width="1511" alt="Screenshot 2024-03-18 at 4 24 48 PM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/73648238/002947d9-993a-4055-8889-affb9a7ea125">
