### ISSUE TITLE
Review the colors throughout the site.

### ISSUE THREAD

**Issue by edmund-dunn** [department-of-veterans-affairs/va.gov-cms#15309]
## User Story or Problem Statement
This follows #15308 

Review the colors throughout the site to ensure that the color variables have taken effect. Look for any colors that haven't been changed and document them. Changes can be reviewed in https://pr15560-ab9nzwp4bqjzcsp9aaggnxolxezeet0j.ci.cms.va.gov/

## Description or Additional Context 
This work will be done on a tugboat.

## Steps for Implementation
Document changes needed in ticket #15310

## Acceptance Criteria
- [x] All colors evaluated.
- [x] Colors that still need to be changed documented. 
- [x] Requires design review
- [x] Requires accessibility review

## Team
Please check the team(s) that will do this work.

- [x] CMS Team
- [ ] Public Websites
- [ ] Facilities
- [ ] User support
- [ ] Accelerated Publishing

**Comment by BerniXiongA6** [comment]
@BerniXiongA6 Note for self to add to Sprint 95 plan when the epic is created.

**Comment by BlakeOrgan** [comment]
Colors that changed were changed as expected, however colors that still need updated have been documented in [ticket #15310](https://app.zenhub.com/workspaces/vagov-cms-team-5c0e7b864b5806bc2bfc2087/issues/gh/department-of-veterans-affairs/va.gov-cms/15310).
