### ISSUE TITLE
Write a GHA workflow to continually check for and remove unhealthy `content-build` runners.

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-cms#15301]
## Description

An instance can be marked unhealthy by the ASG, but GHA will blithely continue to run jobs on it.

One way of working around this would be to run a script that checks the health of the host instance for every GHA runner on a regular basis (let's say 1-5 minutes) and deletes runners on unhealthy instances.

There might be other ways to approach the problem.

## Acceptance Criteria

- [ ] Runners are deleted when the host instance is marked unhealthy so that new jobs cannot be assigned to it.

**Comment by BerniXiongA6** [comment]
Hey @ariperez -- do we know how many points were completed in Sprint 96 and how many points are left to carry over to Sprint 97? Thanks! cc: @ndouglas

**Comment by BerniXiongA6** [comment]
Hey @ariperez -- do we know how many points were completed in Sprint 97 and how many points are left to carry over to Sprint 98? Thanks! cc: @ndouglas @maortiz-27-80
