### ISSUE TITLE
FE: Remove static-pages/shifted-vets-banner from vets-website if possible

### ISSUE THREAD

**Issue by randimays** [department-of-veterans-affairs/va.gov-cms#15312]
### User story
**AS AN** engineer
**I WANT** the vets-website repository to only contain code in use
**SO THAT** performance is optimum, and tech debt is eliminated

### Engineering notes / background
Per [this comment](https://github.com/department-of-veterans-affairs/vets-website/pull/25743#discussion_r1330534775) in the PR to update the CODEOWNERS file, Public Websites owns shifted-vets-banner. 

We believe this has been replaced by homepage-veteran-banner. We should confirm shifted-vets-banner is the same banner as homepage-veteran-banner, and remove shifted-vets-banner if so.

### Quality / testing notes
- Confirm that the randomized veteran banner (present on home page when there is no Benefit Promo selected in Drupal) is still present and working as expected when the shifted-vets-banner is removed
- Remove any references to this code across the repository

## Acceptance criteria
- [x] Confirm whether shifted-vets-banner is the same banner as the homepage-veteran banner
  ~- [ ] If it is, remove shifted-vets-banner and all code references to it in the repository~
~- [ ] Confirm the randomized veteran banner (homepage-veteran-banner) is working on the home page (when no Benefit Promo is selected in Drupal)~

Edited ACs above since the shifted-vets-banner and homepage-veteran-banner are not the same component ([see this comment](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15312#issuecomment-2073170199)).

**Comment by longmd** [comment]
For additional context, if needed, [here was the original issue for this build](https://github.com/department-of-veterans-affairs/va.gov-team/issues/37435).

**Comment by randimays** [comment]
Thanks @longmd for the assist! 🙌

**Comment by randimays** [comment]
Successfully validated in production (for VA.gov and injected H/F). Closing!
