### ISSUE TITLE
Change next-build default port

### ISSUE THREAD

**Issue by jtmst** [department-of-veterans-affairs/va.gov-cms#15314]
## Requirements
- Currently next-build's default port for localhost is 3000.  This is the same as vets-api and should be changed for the convenience of developers who are running vets-api locally

```[tasklist]
### Acceptance criteria
- [ ] next-build runs on a port unique to the rest of va.gov services (3003?)
```

## Background & implementation details

```[tasklist]
### Implementation tasks
- [ ] Use this if it helps you or feel free to delete.
```

**Comment by timcosgrove** [comment]
https://github.com/department-of-veterans-affairs/next-build/pull/358
