### ISSUE TITLE
Next Build options & settings handling

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#15322]
## Requirements

We want a way to manage options for the Next Build application, so that developers can use options in a consistent way without having to worry about how those options are set. 

We want a way to manage options for the Next Build application, so that developers can specify options in a variety of ways that suits their needs.

```[tasklist]
### Acceptance criteria
- [ ] Application options can be read from command-line flags, which will override environment variables
- [ ] Application options can have defaults set which can be overridden by command-line flags or environment variables
- [ ] There is a consistent interface for accessing options/settings regardless of whether they are passed to the application as flags, as environment variables, or they are set as application defaults
- [ ] Feature flag values can be incorporated into the shared 'options'/'settings'/etc
- [ ] Clearly differentiate different app env from current machine env & 'build type'
```

## Background & implementation details

The Content Build implementation of options functionality is here and can be used as an example of an implementation: https://github.com/department-of-veterans-affairs/content-build/blob/main/src/site/stages/build/options.js

We already have some environment variables that either Next.js or next-drupal look for. We also have some variables that we know we will care about, like 'build environment' i.e. vagovdev, vagovstaging, etc.

It will be helpful to have a consistent and centralized way to
* define options and defaults for those options
* define how those options map to environment variables (or, use environment variables as the options)
* specify application flags for when invoking the application from the command line, and intelligently collect those flags and consolidate them with options set in other ways
* provide those options to code without the code having to have any knowledge of where the option came from.

Pseudocoded:
```
// if options file will be called 'options'
const options;

options['cms-endpoint'] = someCLIParseLibrary('cms-endpoint') || process.env.CMS_ENDPOINT || 'https://some-sensible-default.com/v1/api';
// set other options

module.exports = options

// Then, elsewhere
import options from '@config/options'

const endpoint = options.cms-endpoint;

const results = fetch(endpoint);
```

```[tasklist]
### Implementation tasks
- [ ] Use this if it helps you or feel free to delete.
```

**Comment by timcosgrove** [comment]
Note: once decisions are made here and this work is completed, the repo should be scanned for places where these options are used. For example:

* https://github.com/department-of-veterans-affairs/next-build/pull/167/files#diff-0a6e6061c4cd09c4c1592fcbd3f5ca9047711609e4f1b19e5398aac4116ddb4fR42

**Comment by tjheffner** [comment]
Drupal feature flags can be reached at the endpoint `/flags_list` e.g. https://prod.cms.va.gov/flags_list
