### ISSUE TITLE
Front End template skeleton for VBA Service Region

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#15321]
## Description or Additional Context 
Front end template skeleton for VBA Service Region per spec #13127

### Resources
- VBA Content Specs listed in #13096 
- [Sketch file](https://www.sketch.com/s/891d33ae-152d-471c-ab5d-9aedf89cf6ff)

## Acceptance Criteria
- [ ] All needed data is pulling in from the query.
- [ ] The pages are rendering at the expected URL (not necessarily linked to other pages yet).
- [ ] Confirm that analytics are automatically enabled.
  - [ ] If not, enable analytics manually.
  
## Team
Please check the team(s) that will do this work.

- [ ] CMS Team
- [ ] Public Websites
- [X] Facilities
- [ ] User support
- [ ] Accelerated Publishing

**Comment by mmiddaugh** [comment]
@xiongjaneg we will want to ensure the new functionality is wired for analytics - is this covered by components or do we need to add relevant tasks/AC to this issue?

**Comment by xiongjaneg** [comment]
This is a blurb that shows up in the Facility page. It won't have its own URL because it's not a standalone page.
