### ISSUE TITLE
Update Limited Widgets For Unlimited Fields module to latest supported version

### ISSUE THREAD

**Issue by edmund-dunn** [department-of-veterans-affairs/va.gov-cms#15337]
## User Story or Problem Statement

AS A Content Editor
I WANT the Limited Widgets For Unlimited Fields module to be updated to the latest supported version
SO THAT Q&As continue to work properly as the site is updated to D10.

## Description or Additional Context 
The current version, 2.0.5, is unsupported. This will probably take some more extensive testing.
![CleanShot2023-09-20at12 19 58](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/109987005/74657c6c-422e-477f-82cb-15af291ddef4)

## Engineering Notes
The limited_field_widgets module adds third party settings to all unlimited fields, but only a subset of these are actually affected by the module:

| Node Type | Field Name | Limit |
|--------|--------|--------|
| Campaign Landing Page | field_benefit_categories | 2 |
| Campaign Landing Page | field_clp_faq_paragraphs | 10 |
| Campaign Landing Page | field_clp_spotlight_link_teasers | 3 |
| Event | field_datetime_range_timezone | 1 |
| VAMC Facility Health Service | field_service_location | 3 |

## Acceptance Criteria
- [ ] Updated the module to the latest supported version (currently 2.1.0-alpha1).
- [ ] Tested each field instance noted above for correct handling of item limit

**Comment by BerniXiongA6** [comment]
Hi @wesrowe -- Not sure if you knew that I'm filling in as interim Product Manager as of last Wednesday. Wanted to bring to your attention that our team has identified some potential Drupal work that looks like it might be for Public Websites team. Let us know if you have any questions as you're triaging this in consideration for your backlog. Thanks!

**Comment by swirtSJW** [comment]
Related discussion https://dsva.slack.com/archives/C03LFSPGV16/p1695237223708059

**Comment by wesrowe** [comment]
@dsasser, for your pre-refinement if you have time before actual refinement on Monday. The slack thread has good details.

**Comment by chri5tia** [comment]
QA
- [x] Checking status-report for anything pertinent.
- [ ] Check CLP form edit, create, fields (from chart above), node view
- [ ] Review issue queue for anything noteworthy
- [ ] Check event datetime_range_timezone and recent work for event recurrances
- [ ] Check VAMC service location field, form edit, create, node view
- [ ] Check GraphQL and FE templating for each of those 3 content types: CLP, VAMC, Event

**Comment by chri5tia** [comment]
Actual QA Steps
- [ ] Go to node/add/campaign_landing_page; page loads
- [ ]

**Comment by chri5tia** [comment]
## Actual Upgrade Steps
- composer require new latest version
- check for database updates
- clear cache
- QA CLP content type (see below)
- QA Events
- QA VAMC Facility Health Services


## Actual QA Steps

As administrator:
- Go to the CLP content type manage form display /admin/structure/types/manage/campaign_landing_page/form-display:
	- [x] Field `field_benefit_categories` has a limit of 2 ("Related benefits", in manage form display, field settings)
	- [x] Field `field_clp_faq_paragraphs` ("Add between 3 and 10 Q&As") has a limit of 10
	- [x] Field `field_clp_spotlight_link_teasers` ("Links with summaries") has a limit of 3

- Go to the Event content type manage form display: /admin/structure/types/manage/event/form-display
	- [x] Field `field_datetime_range_timezone` (Date and time) has a limit of 1

- Go to the VAMC Facility Health Service manage form display: /admin/structure/types/manage/health_care_local_health_service/form-display
	- [x] Field `field_service_location` ("Service locations") has a limit of 3

 As content_admin:
 - [ ] Go to node/add/campaign_landing_page:
 	- [ ] Form loads without errors
 	- [ ] Cannot bypass the limit of the 3 fields and their limits mentioned above
 - [x] Go to https://va-gov-cms.ddev.site/node/add/event
 	- [x] Form loads without errors
 	- [x] Cannot add more than one Date and Time

**Comment by chri5tia** [comment]
#Status Update 10/5/2023

PR is ready to review but I wouldn't mind going through the testing with someone else for double-eyes in case I missed some scenarios.

@edmund-dunn Since you created the ticket, seeing if you have anything you would want to see added to the QA steps here:
https://github.com/department-of-veterans-affairs/va.gov-cms/pull/15460#issue-1918281594

**Comment by chri5tia** [comment]
# Status update 10/6/23
PR merged

**Comment by jilladams** [comment]
This is live in Prod as of today's deploy. Closing.
