### ISSUE TITLE
Update Configuration Views module to supported version

### ISSUE THREAD

**Issue by edmund-dunn** [department-of-veterans-affairs/va.gov-cms#15336]
## User Story or Problem Statement
Update Configuration Views to latest supported version.

## Description or Additional Context 
Config_views is currently on 2.0.0 which is unsupported. 
![CleanShot2023-09-20at12 19 58](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/109987005/a6d63de0-8795-43cd-a301-04a2f66fdef1)

## Acceptance Criteria
- [ ] Config Views update to latest supported version.

## Team
Please check the team(s) that will do this work.

- [ ] CMS Team
- [ ] Public Websites
- [x] Facilities
- [ ] User support
- [ ] Accelerated Publishing

**Comment by BerniXiongA6** [comment]
Hi @xiongjaneg -- our team has identified some potential Drupal work that looks like it might be for Facilities team. Let us know if you have any questions as you're triaging this in consideration for your backlog. Thanks!

**Comment by xiongjaneg** [comment]
Content model documentation needs this module that Steve built when he was on CMS Team. It's for the whole site, not just Facilities.

**Comment by xiongjaneg** [comment]
Will resolve itself with Dependabot update, likely today.

**Comment by xiongjaneg** [comment]
@xiongjaneg To bring to future CMS Team discussion

**Comment by swirtSJW** [comment]
Dependabot did its thing https://github.com/department-of-veterans-affairs/va.gov-cms/pull/15342

**Comment by xiongjaneg** [comment]
@BerniXiongA6 This issues resolved itself in a Dependabot update today.
We'll table the discussion of CMS Team documentation and Facilities documentation to a later date. Thank you!
