### ISSUE TITLE
iOS App: Analyze September stats for the Mobile App Promo Banner

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#15348]
### User story

**AS A** PO/PM
**I WANT** to know whether Sept mobile app adoption data validates or disproves the hypothesis
**SO THAT** we can decide whether to implement banners for non-iOS-Safari mobile browsers.

### Analytics considerations

Baseline stats were added to the [initiative brief](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/public-websites/Benefit%20Hub/mobile-promotion/README.md) in #14288.

## Acceptance criteria

- [ ] Collected KPIs for September per initiative brief
- [ ] Shared findings with DaveC
- [ ] Ensured next step is ticketed (could be "analyze October KPIs")

**Comment by wesrowe** [comment]
I did the first month-over-baseline analysis and posted [the excel](https://dvagov.sharepoint.com/:x:/r/sites/SitewidePublicWebsites/Shared%20Documents/Mobile%20promo%20banners/Pilot%20KPIs%20analysis%20-%20start%20Sept%202023.xlsx?d=wce7adfb4ff21429babe5e2f3b4e37f01&csf=1&web=1&e=qmpNHE) to the PW space on Sharepoint. It showed a positive trend for the features we promoted for iOS. DaveC subsequently requested via Slack a week-over-week analysis. By that point the [Looker Studio dashboard](https://lookerstudio.google.com/u/0/reporting/e28cd59a-b2e5-4f29-8ae4-a4eea6d23f9c/page/p_7hxeqg1k9c) was broken, and per a [Slack thread](https://dsva.slack.com/archives/C018V2JCWRJ/p1696621679309219?thread_ts=1696620807.918189&cid=C018V2JCWRJ) there is a problem with the BigQuery functions that drive the dashboard; fix timing TBD (but still down as of 10/11).

The ticket can't close until the dashboard works again.

**Comment by FranECross** [comment]
Analytics documented, analysis done and shared with Dave C. Closing ticket and will open a new one if new analysis is needed.
