### ISSUE TITLE
When iOS/Android browser mobile banners are shipped, remove the letters-mobile-cta

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#15345]
## Description

The Letters mobile CTA points any visitor to the pages where it appears to the opportunity to use the mobile app. With mobile banners in place, this will no longer be necessary. 

Once remaining ioS / Android banners are shipped, we will deprecate the app

### Engineering notes / background
Existing app: https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/static-pages/letters-mobile-cta

Related thread where DaveC clarified that this CTA should be removed after banners are live: https://dsva.slack.com/archives/C52CL1PKQ/p1695156355685709

## Acceptance criteria

- [ ] Letters-mobile-cta app is deprecated including
    - [ ] vets-website code
    - [ ] vets-website codeowner rule https://github.com/department-of-veterans-affairs/vets-website/blob/main/.github/CODEOWNERS#L116
    - [ ] [Drupal content](https://staging.cms.va.gov/node/471/edit) for the "Get your VA letters online" section
 - [ ] CMS feature toggle FEATURE_MOBILE_APP_PROMO is also removed

**Comment by jilladams** [comment]
Updated banners shipped today. If we're stable by end of this week, we could remove this feature flag anytime. @FranECross moving to stretch.

**Comment by jilladams** [comment]
We also have a CMS feature toggle that can be removed on the same timing. FE folks don't typically do that, but in this case, Randi added that flag herself, so we _could_ opt to wrap that into these ACs as well.

**Comment by chriskim2311** [comment]
@jilladams @FranECross Before we merge these changes CAIA will need to remove this block in the CMS. 
<img width="1520" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeHZxQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--aa90737e3d45cf9d820c4c22fd76363eb6681394/Download_VA_Benefit_Letters___Veterans_Affairs.png" alt="Download_VA_Benefit_Letters___Veterans_Affairs.png" />

There will be changes in Content build, Vets-website, CMS repos in that order.

**Comment by jilladams** [comment]
Katherine Fung is the main editor of that page. Posed this question to her here: https://dsva.slack.com/archives/C01K37HRUAH/p1705966132181179

**Comment by jilladams** [comment]
Katherine affirmed that the React widget is ok to remove from the CMS node, however: there are several draft edits on the node and we'll need CAIA's help to sort out which of those draft updates should be published in order to publish a new revision. Katherine will need a ticket and time to prioritize that, so this ticket is blocked til that's done. Once they have a ticket up, I'll note it here so we can keep an eye. Pulling from sprint.

**Comment by jilladams** [comment]
Also: that said, there are 3 PRs in flight here: 
1. https://github.com/department-of-veterans-affairs/va.gov-cms/pull/16966 - can go ahead and merge
2. https://github.com/department-of-veterans-affairs/content-build/pull/1883 - can merge
3. https://github.com/department-of-veterans-affairs/vets-website/pull/27594 - is blocked on the CAIA updates

**Comment by jilladams** [comment]
Chris noted: It's likely smart to leave the CMS feature flag in place until we get #16969 sorted out, just in case.

**Comment by jilladams** [comment]
* Blocked by https://github.com/department-of-veterans-affairs/va.gov-team/issues/74561

**Comment by jilladams** [comment]
Was autoclosed by a PR. Reopening til all the related PRs get merged.

**Comment by randimays** [comment]
Reopening as this was auto-closed by a PR

**Comment by randimays** [comment]
`letters-mobile-cta` and mobile app promo banners validated in staging successfully 👍🏻 Will check again at prod deploy today.

**Comment by randimays** [comment]
Verified all mobile banners are still showing up as expected in production. Don't think I can test `letters-mobile-cta` in production since it requires a login, but all is good in staging!

**Comment by jilladams** [comment]
(Noting that for now FEATURE_MOBILE_APP_PROMO still showing up on https://prod.cms.va.gov/admin/config/system/feature_toggle bc we missed daily deploy cutoff by 1 min. But: no reason to believe this won't go live tomorrow, so reporting it done, and we can reopen / follow up if that doesn't prove out.)
