### ISSUE TITLE
Mobile banners: analyze use of mobile browsers in order to establish a cut line for iOS / Android banner browser support

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#15346]
### User story
> _Describe the audience/user, enhancement or fix, and value / outcome desired._

**AS AN** engineer and gov't product owner
**I WANT** teams to implement changes for the most-used set of browsers 
**SO THAT** we don't spend resources on long-tail browsers that are not widely in use.

### Analytics considerations
We want to see traffic for VA.gov (benefit pages specifically?) to understand the browser share of traffic. Goal is to establish a cut line for the remaining iOS and Android browser banners, to determine what we will / won't support.

## Acceptance criteria

- [ ] Breakdown of browser share is provided in ticket with proposal for a cut line for support
- [ ] DaveC review & Signoff

**Comment by wesrowe** [comment]
Dave Conlon stated in refinement on 9/21 that we should follow Platform support guidance. It is [here](https://depo-platform-documentation.scrollhelp.site/developer-docs/browser-support-policy).
Conclusion:
- Android browsers:
  - Chrome
  - Firefox
- iOS broswers
  - Safari
  - Chrome
  - Firefox
