### ISSUE TITLE
FE: make Event image aspect ratios consistent with help text

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#15350]
### User story

**AS An** Event Editor
**I WANT** help text about aspect ratios to accurately reflect the reality of how my image will be displayed across various browser/device widths
**SO THAT** I don't naively upload images at the requested ratio that will look bad at other ratios.

The solution may be to fix the Event layout.

### Engineering notes / background

This [slack thread](https://dsva.slack.com/archives/C03LFSPGV16/p1695329146436979) has a good discussion of the situation.
- CMS Help Desk has fielded Editor concerns around aspect ratios for Events
- Per an experiment Nathan did on Events, it looks like the event layout ([example](https://www.va.gov/wichita-health-care/events/61317/)) could probably be fixed to display the full image that the help text talks about.

The help text currently reads `The system will crop your image to the standard 7:2 aspect ratio if it isn't already.`

However, in the example, the 7:2 image is cropped to 5:1, thus cutting off top and bottom of the image:
<img width="332" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/4054752/8ab5d2c6-a502-4540-8fca-c1b0cb3b2bbd">

## Acceptance criteria

- [x] Event layout displays images in accordance with what the Event drupal UI tells Editors [ASSUMPTION: team agrees that changing the layout is the most straightforward way to resolve the discrepancy]
  - Note: a flexible approach may be okay – i.e., if the BE is providing guard rails around aspect ratio, the FE could just display the image provided by the BE without forcing it into a set-ratio box
- [ ] design review
- [ ] PM/DM review

**Comment by wesrowe** [comment]
@thejordanwood, fysa I tagged you for pre-refinement of this ticket.

**Comment by wesrowe** [comment]
@thejordanwood, sorry, after further discussion in that slack thread, it looks like the fix for Events is a straightforward layout/template change. I adjusted the ticket to be FE eng.

**Comment by randimays** [comment]
PR posted here: https://github.com/department-of-veterans-affairs/vets-website/pull/25971

**Comment by jilladams** [comment]
Verified: https://www.va.gov/wichita-health-care/events/61317/
