### ISSUE TITLE
PAW: Research synthesis and reporting

### ISSUE THREAD

**Issue by cindymerrill** [department-of-veterans-affairs/va.gov-cms#15369]
### User story

**AS A(N)** researcher
**I WANT** to synthesize data from research sessions
**SO THAT** I can summarize findings and draft recommendations

## Acceptance criteria

- [x] Clean up notes spreadsheet
- [x] Write topline summary and share out with team
- [x] Do data analysis/synthesis of data collected from research
- [x] Write research report
- [x] Share research report with Amanda for review prior to sharing with team
- [x] Update MVS checker with participant demographics, and for no-show participants, enter their data with "N"'s

**Comment by cindymerrill** [comment]
Yesterday I cleaned up my notes spreadsheet and wrote a brief topline summary, which I shared out with the team.

**Comment by aklausmeier** [comment]
@jilladams @FranECross added AC for: Share research report with Amanda for review prior to sharing with team. UX deliverables should be reviewed by me as a general rule. I think this has naturally been done but adding for Fran's awareness. 

cc: @cindymerrill

**Comment by FranECross** [comment]
Thank you, Amanda!

Fran

**Comment by cindymerrill** [comment]
Perhaps @aklausmeier 's AC belongs in my [next ticket ](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15370) instead of this one because that's where sharing/reviews are, but it's OK in either place.

**Comment by FranECross** [comment]
@cindymerrill Thanks for mentioning the next ticket! I've added it under the task list in the other ticket as well for visibility. cc @aklausmeier

**Comment by cindymerrill** [comment]
@FranECross I moved it up to the top of the task list in the other ticket so that I'll remember to do it before doing the next task, which is to share it with the team.

**Comment by cindymerrill** [comment]
Finished data synthesis! Now need to work on organizing and editing the report.

**Comment by cindymerrill** [comment]
Finished report writing! I just shared it with @aklausmeier for feedback before I share it any more widely: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/pact-act-wizard/research/research-findings.md @jilladams @FranECross
