### ISSUE TITLE
Design VAMC Police data page

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#15376]
## Description

- The current desired option is: Data is displayed on a page (stand-alone page)
- Jordan identified potential police data display options in #15041 
- The menu to get to this page is currently TBD and not in scope for this ticket.

## Design

[Sketch file with design](https://sketch.com/s/b48c905c-7c7f-46fb-9ae5-6020ff0e5174)

This task is to create the design for a new page for this. We could potentially reuse existing patterns to construct this page, but maybe not.

**Design should include:**

1. Make the sub-page link visible by:
     - Adding a VA Police link to the “In the Spotlight” section
     - Adding a link to the sidebar navigation. The current police page examples have this within the Program section, but I think we could move it out of there into the top About section. This would put it on the same level as the About us, Work with us, Contact us, etc. Moving it up would make it more visible.
     - Current examples: [VA Oklahoma City health care](https://www.va.gov/oklahoma-city-health-care/programs/va-police/) and [VA Northern California health care](https://www.va.gov/northern-california-health-care/programs/va-police/)
 
2. Leverage the appointment wait time percentage box design ([example](https://www.va.gov/eastern-colorado-health-care/locations/rocky-mountain-regional-va-medical-center/)).
3. Try to keep all explanations and additional information on one page, maybe by using reusable Q&As.

## Acceptance Criteria
- [x] Create a user flow
- [x] Create a lo-fi design
- [x] Review design with engineers
- [x] Review design with accessibility
- [x] Review design with Amanda
- [x] Review design with PM and PO
- [x] Schedule design intent meeting for Platform collab cycle

## Team
Please check the team(s) that will do this work.

- [ ] CMS Team
- [ ] Public Websites
- [x] Facilities
- [ ] User support
- [ ] Accelerated Publishing

**Comment by davidmpickett** [comment]
Would this include a user flow? Do we want to break this up into minimum viable pieces needed for Design Intent, vs full design?

**Comment by mmiddaugh** [comment]
I recently received information from the police data vendor, including software field mapping and a recommendation to reference the [Tucson Police data and Analysis](https://policeanalysis.tucsonaz.gov/) site. 

I'll add details here in the context of the legislative requirements:

---

The Secretary shall publish on the internet website of each facility of the Department the following information with respect to the `facility` 
- _we will have access to data at the system and facility level_

---

Summaries and statistics covering the previous five-year period regarding—
`arrests` made by and `tickets issued` by Department police officers;

_Types of enforcement actions_ 
 - _Written Warning_ 
 - _Civil Citation_ 
 - _Civil Traffic_
 - _Criminal Traffic_ 
 - _Misdemeanor_ 

_Arrest methods include_
- _taken into custody_
- _summoned/cited_
- _on-view arrest_
- _pretrial services release_
- _deflected_
- _plus: booked into jail_

_Arrest types include_
- _misdemeanors_
- _felony_
- _felony/misdemeanor_
- _status offense_
- _n/a_
- _unknown_

---

prosecutions, ticketing, and other actions relating to such arrests;
_- requesting more information_

---

the use of force and weapons discharge by Department police officers; 
_- requesting more information_

---

complaints, investigations, and disciplinary actions regarding Department police officers.
_- requesting more information_

---

Contact information for employees of the Department and the public to directly contact the police force of the facility, including for an individual (or the representative, attorney, or authorized agent of the individual) to request information regarding the arrest, ticketing, detainment, use of force, or other police matters pertaining to that individual.
_- requesting more information but we should be able to use existing patterns for this_

The Secretary shall ensure that each police force of a facility of the Department is able to provide to an individual who contacts the police force pursuant to paragraph (1)(B) the information described in such paragraph.

---

Other details
- the data uses codes from the standard National Incident-Based Reporting System (and we have access to data definitions)

Events are either
- calls for service or
- officer initiated 

Types of events are broadly organized into categories which include the following
- Family and juvenile matters
- Hate crimes
- Traffic Safety (such as Moving violations, Collisions)
- Mental health matters (such as Community assistance)
- Property Crime (such as Burglary, Property damage)
- General investigations (such as Suspicious Activity, Alarms, Missing persons, and Welfare checks)
- Quality of Life (such as Public order)
- Violent Crime (such Assault or Domestic violence)
- Department Operation (such as Public Assistance and Hazards)
- Sexually motivated offense

- This page might be a good reference for summaries about [Use of force](https://policeanalysis.tucsonaz.gov/pages/police-use-of-force)

**Comment by thejordanwood** [comment]
I've created [a Sketch file](https://sketch.com/s/b48c905c-7c7f-46fb-9ae5-6020ff0e5174) with the design and the user flow.

**Comment by mmiddaugh** [comment]
@thejordanwood - your design looks like a great place to start given what we know at the moment - thank you! A few thoughts:
- Consider adding "Current as of [date]" (we do this for Veteran satisfaction with appointment wait times data)
- Some health care systems have VA police or Security accordions in their Prepare for your visit sections, such as [Sacramento VA Medical Center](https://www.va.gov/northern-california-health-care/locations/sacramento-va-medical-center/#security) - you may want to include that possibility in the user flow
- I'm wondering if we need to add context to the "This is a summary of police activity" line above the data, such as adding "at this facility" -  just so it is clear that the data pertains to the facility, rather than the system or the local community. 
- My opinion is that having a total number of calls would give the data more context. 
  - For example, using your numbers in Sketch, there is a difference between these two scenarios
    - Police responded to 1,000 incidents. 600 people were arrested and 200 people received tickets. 
    - Police responded to 30,000 incidents. 600 people were arrested and 200 people received tickets. 
  - If we're able to get data about the source of the call, then we can further provide context for the total number of interactions, such as 
    - Police responded to 1,000 incidents: 800 calls for help and 200 officer initiated. 600 people were arrested and 200 people received tickets. 
- I like how you indicated how the contact information might be used (to request information regarding arrest, ticketing, detainment, etc.) 
  - Let's add a way to indicate how to reach the police in the event of an emergency - check out the contact information listed for [Oklahoma health care](https://www.va.gov/oklahoma-city-health-care/programs/va-police/) and the details in the Security accordion for [Edith Nourse Rogers Memorial Veterans' Hospital](https://www.va.gov/bedford-health-care/locations/edith-nourse-rogers-memorial-veterans-hospital/#security)
  - Let's consider adding a physical location (building/room #) for those who need to drop off a form or speak to someone in person

**Comment by thejordanwood** [comment]
@xiongjaneg I think we're ready to go to design intent with this. 

- I reviewed this with engineers and accessibility in [this Slack thread](https://dsva.slack.com/archives/C0FQSS30V/p1696453163592559). There are some comments we may need to pull out for future tickets, but nothing that should block us from going to design intent.
- I've added the user flow that Michelle suggested. We can move the other suggestions to a later ticket and tackle these after design intent. 
- I've added some comments in the Sketch file to better explain the design when the Platform team is reviewing this. I'd really like to stress to them that the content and data are placeholders for now, and that this iteration is to mainly review the structure of the page.

**Comment by xiongjaneg** [comment]
@thejordanwood Awesome! Do you need help scheduling the design intent meeting? Who else should attend? I'm out next week just in case I'm needed, but I don't want to delay the schedule.

**Comment by thejordanwood** [comment]
Design Intent is scheduled for October 24 at 3:30 ET. 

[Collab cycle ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/65082)

**Comment by mmiddaugh** [comment]
Additional input was recent received regarding contact information.

The following is suggested
- Physical Location
- Telephone Numbers (24 hour dispatch number, external)
- Chief of Police name and email

Open question: Should we expect police data and contact information for every facility or at the system level only?
