### ISSUE TITLE
Next-build Storybook is available via Tugboat

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#15382]
## Requirements

For each Next Build Tugboat instance, Storybook built from the code for that NB Tugboat's instance should be available, so that Storybook can be checked as part of the review process.

```[tasklist]
### Acceptance criteria
- [ ] Next Build's Storybook is available for a given Tugboat instance, and represents up-to-date changes.
```

## Background & implementation details

```[tasklist]
### Implementation tasks
- [ ] Use this if it helps you or feel free to delete.
```

**Comment by tjheffner** [comment]
This PR from the CMS repo is where tugboat support for storybook was added originally:
https://github.com/department-of-veterans-affairs/va.gov-cms/pull/8482/files#diff-fbd0812762ff8d2c67fa66a4956c3b55557ad0889505294f524192000b2ce50e

There's a lot in that PR, really only need the 3 files in the `.tugboat` directory.

**Comment by tjheffner** [comment]
Note: storybook should be built in the `online:` portion of tugboat config, so that it doesn't block the main build preview
