### ISSUE TITLE
[Consider] Assign non-MVP VBA facilities to different section

### ISSUE THREAD

**Issue by davidmpickett** [department-of-veterans-affairs/va.gov-cms#15381]
## User Story or Problem Statement

For the VBA regional office MVP, we will be creating modernized pages for 2 types of VBA facilities:
- Regional Offices
- Satellite Offices

However, there are 5 other types of VBA facilities that we also maintain data for:
- VR&E office
- Integrated Disability Evaluation System (IDES) Site
- Pre-Discharge Site
- Seamless Transition Integrated Care Clinic (STICC)
- VetSuccess on Campus

Right now the way the VBA facilities are grouped into the Section Taxonomy, all 7 types of facilities are grouped into sections based on the closest Regional Office. For example the [Honolulu section](https://prod.cms.va.gov/section/vba/vba-facilities/honolulu-va-regional-benefit-office-and-spark-m-matsunaga-department-of-veterans-affairs-medical-center) contains 10 facilities, only 5 of which are Regional Offices or satellite offices.

![screencapture-prod-cms-va-gov-section-vba-vba-facilities-honolulu-va-regional-benefit-office-and-spark-m-matsunaga-department-of-veterans-affairs-medical-center-2023-09-25-13_29_11](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/2217aa84-2f3c-41fd-9b47-0214ad6d642e)

## Option 1 - Do nothing
- Pro: No effort
- Con: MVP pilot VBA editors will have permission to edit types of VBA facilities that we didn't intend

## Option 2 - move them up to an existing section
- [VBA / VBA Facilities](https://prod.cms.va.gov/section/vba-facilities)
- or VBA / VBA Facilities / [region]
- Pro: This would get them out of the way of local editors, but not require making any further decision about long-term governance
- Con: Messy

## Option 3 - create new sections based on expected governance
- Talk to VBA stakeholders about long-term vision for managing other facility types - will it be managed regionally or by benefit type 
- e.g. VR&E becomes it's own Section under VBA Facilities and all VR&E facilities move over there
- Pro: Starts moving toward ideal state
- Con: scope creep ahoy!

## Sections to review
- [Albuquerque](https://prod.cms.va.gov/section/vba/vba-facilities/albuquerque-va-regional-benefit-office)
- [Anchorage](https://prod.cms.va.gov/section/vba/vba-facilities/anchorage-va-regional-benefit-office-at-anchorage-va-medical-center)
- [Boston](https://prod.cms.va.gov/section/vba/vba-facilities/boston-va-regional-benefit-office)
- [Honolulu](https://prod.cms.va.gov/section/vba/vba-facilities/honolulu-va-regional-benefit-office-and-spark-m-matsunaga-department-of-veterans-affairs-medical-center)
- [Houston](https://prod.cms.va.gov/section/vba/vba-facilities/houston-va-regional-benefit-office)
- [National Capital Region](https://prod.cms.va.gov/section/vba/vba-facilities/national-capital-region-va-regional-benefits-office)
- [San Juan](https://prod.cms.va.gov/section/vba/vba-facilities/san-juan-va-regional-benefit-office)

## Acceptance Criteria
- [ ] Decision on path forward is made by product (in conjunction with VBA stakeholders)
- [ ] Path forward is implemented (or implementation is moved to a new ticket)

**Comment by davidmpickett** [comment]
A possible next step on this is to dedicate some time in a future UX sync to discussing options 1, 2, 3 and having a decision on direction.

**Comment by mmiddaugh** [comment]
Given the number of competing priorities, I suggest we handle this through business process with an eye on how much trouble this presents to the initial editor group. If the MVP group or next round of editors have issues, we'll need to reconsider the approach. This also buys some time before decisions about governance or sections need to be made.

**Comment by davidmpickett** [comment]
@mmiddaugh That makes sense. I made a note on Alexis's corresponding research discovery ticket so it can get added to list of things we're hoping to learn about.

cc @aklausmeier

**Comment by davidmpickett** [comment]
Closing as not planned since we decided not to do this during the pilot
