### ISSUE TITLE
KB: CLP: Write article "How do I request a CLP?"

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#15384]
**FIRST of multiple tickets to migrate CLP Product Guide PDF into KB**

### User story
> _Describe the audience/user, enhancement or fix, and value / outcome desired._

**AS A** CLP Editor
**I WANT** a KB article on how to publish a CLP created to replace that portion of the product guide PDF
**SO THAT** the information is updated and more accessible.

### Engineering notes / background
* PW team runbook for how this process works today: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/campaign-landing-page#runbook-for-clp-creation
* what a "product guide" is : PDF in question: https://prod.cms.va.gov/sites/default/files/2021-12/VA.gov_.Campaign.Landing.Page_Governance_Product_Guide_11302021.pdf
  * Contains incorrect points of contact for the modern world

## Dave notes
* **Governance PDF**: Dave says no one else knows it exists but us. So we don't need to worry about redirects or getting it replaced / retired. 
* **Product brief:** Some of the content from the PDF should end up in our [CLP Product brief](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/campaign-landing-page#runbook-for-clp-creation). We are punting this for now, and will address it when we map out the next CLP iteration. 
* **KB:**
  * The Helpdesk steps should be removed, and moved to internal KB or other internal Helpdesk docs. 
  * Some of the PDF content about the governance model belongs in the KB. Editors are supposed to consult with their Administration leadership, etc.
    * Dave is going to take an edit pass to rough out this content, and Jill or Fran can clean up / submit to Helpdesk for review after. 

## Acceptance criteria
- [x] KB articles modified to provide direction on requesting new CLPs
  - [ ] https://prod.cms.va.gov/help/campaign-landing-pages/how-to-create-a-new-campaign-landing-page
    - [ ] Should be updated with necessary governance info around requesting a CLP
    - [ ] Helpdesk-facing content should be moved to another Helpdesk-facing location
  - [ ] https://prod.cms.va.gov/help/campaign-landing-pages - references a Youtube video that includes a walk through of the Governance PDF and should be removed
  - [ ] https://prod.cms.va.gov/help/campaign-landing-pages/how-to-manage-campaign-landing-pages - should add a reference to the new "how to request" KB
- [x] PM/DM review requested
- [x] Update https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15657 when new draft is ready for review

**Comment by chri5tia** [comment]
Status update:
Planning to deliver this before Monday's scrum udpate.

**Comment by chri5tia** [comment]
Noting similar KB Articles:
- https://prod.cms.va.gov/help/campaign-landing-pages/how-to-create-a-new-campaign-landing-page
- https://prod.cms.va.gov/help/campaign-landing-pages
- https://prod.cms.va.gov/help/campaign-landing-pages/how-to-manage-campaign-landing-pages

**Comment by chri5tia** [comment]
> how to publish a CLP created to replace that portion of the product guide PDF

Realizing that this KB is only for how to publish, I am not seeing this portion in the PDF or in our run book. There is a statement in [one of the other KBs](https://prod.cms.va.gov/help/campaign-landing-pages/how-to-manage-campaign-landing-pages) about using the editorial workflow and setting it to publish, like other nodes:
>Use "Published" when you are ready for the content to go live on VA.gov after the next top of the hour content release.

I am not finding anything regarding the step to create a help desk ticket. I think this is the portion the article is for, right?

Other portions of the KB have been created here:
https://prod.cms.va.gov/help/campaign-landing-pages/how-to-create-a-new-campaign-landing-page
https://prod.cms.va.gov/help/campaign-landing-pages
https://prod.cms.va.gov/help/campaign-landing-pages/how-to-manage-campaign-landing-pages

![Screenshot 2023-10-11 at 9 59 49 AM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/22764938/be9fe508-25a8-47fa-8f56-db2f3fd13cd0)
![Screenshot 2023-10-11 at 9 59 09 AM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/22764938/0bc4952d-2967-4926-b872-099916719b30)

**Comment by chri5tia** [comment]
# Notes 10/11/23
Sync with Jill

- How to request a new CLP

## Currently
Audiences:
- PW: github readme/[runbook](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/campaign-landing-page#runbook-for-clp-creation)
- Admin: "How to create a new Campaign Landing Page"

## Vision
- Expand "How to create a new Campaign Landing Page" to include Admin and Editor; create a section for the editor for how to request the CLP

### Editor Steps

1. Request a new Campaign Landing Page from the Helpdesk, either via emailing support@va-gov.atlassian.net or https://prod.cms.va.gov/help

**Comment by chri5tia** [comment]
Can we just edit the PDF ourselves to remove the names and keep them department named instead.

**Comment by jilladams** [comment]
Synced with Christia: 
* We have drafted an edit to the Create CLP to indicate to how to request a new CLP as an editor
* We have updated the Helpdesk steps in https://prod.cms.va.gov/help/campaign-landing-pages/how-to-create-a-new-campaign-landing-page to include a reference to filing the  Campaign Landing Page request ticket, which includes: PO signoff, Editor user setup, etc.
* We created #15657 for Helpdesk review
* We hackily modified the existing Governance PDF to update Brian Lloyd references to point to the Create KB, and to use Dave's name: [VA.gov_.Campaign.Landing.Page_Governance_Product_Guide_11302021.pdf](https://github.com/department-of-veterans-affairs/va.gov-cms/files/12874986/VA.gov_.Campaign.Landing.Page_Governance_Product_Guide_11302021.pdf)
  * The one quirk: PDF is managed in Drupal. So: if we upload a new version, it'll break the path and require a redirect. We can't find the node where this PDF was originally introduced/attached. Christia will follow up with @swirtSJW to see if we can figure out how to replace this on the server at existing path (prob not) or replace / redirect somehow.

**Comment by chri5tia** [comment]
## Status update 10/11/23
Worked with Jill to get this over the line; waiting on other stakeholders to approve and publish. Essentially, this is done.

**Comment by jilladams** [comment]
@chri5tia next step here was to investigate (with Steve?) whether / how we can update the PDF file on the server. Let me know what you find on that, and based on what we learn, we can decide if we can close this ticket.

**Comment by chri5tia** [comment]
https://civicactions.slack.com/archives/C0ASJ7C8P/p1697130024852709
Convo ongoing

**Comment by jilladams** [comment]
Talked to Dave today. Some updates / things I had misunderstood: 
1. PDF -- Dave says no one else knows it exists but us. So we don't need to worry about redirects or getting it replaced / retired. 
* **Product brief:** Some of the content from the PDF should end up in our [CLP Product brief](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/campaign-landing-page#runbook-for-clp-creation). We are punting this for now, and will address it when we map out the next CLP iteration. 
* **KB:**
  * The Helpdesk steps should be removed, and moved to internal KB or other internal Helpdesk docs. 
  * Some of the PDF content about the governance model belongs in the KB. Editors are supposed to consult with their Administration leadership, etc.
    * Dave is going to take an edit pass to rough out this content, and I'll clean up / submit to Helpdesk for review after. 

@chri5tia I'm going to take over this ticket, given those notes. Thank you for all your help to get this much clear / do the PDF research!
