### ISSUE TITLE
Restrict VBA RO editors from editing certain fields

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#15396]
## User Story or Problem Statement

- As a Veteran, I need timely and accurate information about VA benefits offices' services and locations.
- As a VBA editor, I want to see the data for my facility, even if I am unable to edit it in the CMS so that I can confirm it is correct.
- As a VBA editor, I want an easy way to know how to request changes or report inaccuracies for data which I am unable to edit in the CMS.

## Description or Additional Context 
We need to restrict VBA RO editors from editing certain fields (i.e. name, address, facility id). This data doesn't come from VAST which means we won't have a good way to know if changes have been made. 

## Acceptance Criteria
- [x] VBA facility names can't be edited by editors.
- [x] VBA facility addresses can't be edited by editors.
- [x] VBA facility IDs can't be edited by editors.

## Team
Please check the team(s) that will do this work.

- [ ] CMS Team
- [ ] Public Websites
- [x] Facilities
- [ ] User support
- [ ] Accelerated Publishing

**Comment by mmiddaugh** [comment]
**Additional user stories** 

- As a VBA editor, I want to see the data for my facility, even if I am unable to edit it in the CMS so that I can confirm it is correct. 
- As a VBA editor, I want an easy way to know how to request changes or report inaccuracies for data which I am unable to edit in the CMS.

**Comment by xiongjaneg** [comment]
@omahane Please review to see if this still applies

**Comment by xiongjaneg** [comment]
Does not currently apply as Sandy's DB is the source of VBA facility name, address, ID, but this will need to be put in place when Lighthouse is ready for cutover to Drupal as source of truth for VBA facility info

**Comment by swirtSJW** [comment]
@xiongjaneg This is already done, I think we can close it.  It is true for any migrated data across all facilities
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5752113/26cb1f76-88a3-4ab4-ae80-63cb9cc64ded)

**Comment by swirtSJW** [comment]
This is the comment in the question mark on node:  edit
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5752113/74013f19-758d-4be9-b3a5-2e755d414cdb)


And here it the full display on node: view
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5752113/50616ff4-37ff-4817-b011-bf38b0ab250b)

**Comment by swirtSJW** [comment]
@xiongjaneg the only part that is not covered is @mmiddaugh addition of 
> As a VBA editor, I want an easy way to know how to request changes or report inaccuracies for data which I am unable to edit in the CMS.

That could probably be put in its own ticket as it is specific to help text.

**Comment by xiongjaneg** [comment]
#16972 for the last user story
