### ISSUE TITLE
[SPIKE] Discovery on enhancements to existing monthly reporting CMS/Content-Build Datadog Dashboard

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-cms#15406]
## Description

Recently rapped with Berni about the existing monthly report dashboard. Bottom line is that it can be enhanced -- we should fit in 5XX issues, content-build reliability, product delivery metrics, and anything else that comes to mind.

The outcome of this ticket should be a ticket or collection of tickets with new items to add to the dashboard.

## Acceptance Criteria

- [x] Findings have been documented in this thread.
- [x] Followup issue(s) opened to address.

**Comment by BerniXiongA6** [comment]
How are we progressing on this @ndouglas ?

**Comment by ndouglas** [comment]
@BerniXiongA6 honestly lost sight of it, but I'll focus on it today and should be able to wrap it up.

**Comment by ndouglas** [comment]
- [ ] Product Delivery Metrics
  - [ ] Change Failure Rate (Daily)
    - how reliable is our Tugboat CI pipeline at preventing issues from reaching BRD?
    - how reliable is our Staging post-deploy tests system at preventing issues from reaching Prod?
  - [ ] Test Success Lead Time
    - how long before we have assurance that a change merged to `main` will deploy to Prod?
  - [ ] Test Failure Lead Time
    - how soon are we notified of failures in staging post-deploy tests?
- [ ] Content Build Metrics
  - [ ] Build Time by (Big) Steps
    - how long do the different steps of the content build process take?
  - [ ] Build Time by (Small) Steps
    - how long do the different steps of the content build process take?
  - [ ] Build Time per Node and Per Page, Historic
    - have we encountered any unexpected or undesired changes in performance?
    - is our process continuing to scale adequately for our content?
  - [ ] Build Time per Node and Per Page, Last Build
    - what are the raw numbers for build time per node?
    - how much does adding an additional node, or collection of nodes, impact our build time?
- [ ] Production SSO Login
  - [ ] SSO Login Errors, Historic
    - how reliable is the single-sign-on process?
  - [ ] SSO Login Errors, Cumulative
    - how many SSO login errors have been encountered, total, in this amount of time?
- [ ] Outdated and Overdue Content
  - [ ] All Overdue Content
    - how many nodes haven't been updated in a year?
  - [ ] All Outdated Content (>90 days overdue)
    - how many nodes have continued to not receive attention?
- [ ] Production 5XX Errors
  - [ ] General 5XX Errors, Historic
    - how commonly do our users encounter an issue caused by a programming error or system misconfiguration?
    - how reliable is our system, generally?
- [ ] GitHub Activity
  - [ ] New GitHub Tickets, by Week
    - how frequently do we identify opportunities for improvement? (note, these are not defects, but all opened tickets)
  - [ ] New GitHub Defect Tickets, by Week
    - how frequently do we identify issues in the CMS?
  - [ ] Closed GitHub Tickets, by Week
    - how does our work output compare to the ticket input?
  - [ ] Closed GitHub Defect Tickets, by Week
    - how quickly are we able to address identified issues in the CMS?
  - [ ] New Pull Requests, by Week
    - how many changes to the codebase do we initiate?
  - [ ] Merged Pull Requests, by Week
    - how many effective changes to the codebase do we actually complete?

**Comment by BerniXiongA6** [comment]
Looks good to go, thanks @ndouglas cc: @EWashb
