### ISSUE TITLE
FE: Remove eMIS dependency from vets-website

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#15408]
## Problem Statement
Platform is deprecating a service, eMIS, that integrates with vets-api to handle for pre-fills of veteran info. This work is to remove vets-website dependency on eMIS.

Background Information
Information in [Slack threads](https://dsva.slack.com/archives/CE4304QPK/p1693930211659039)

eMIS deprecation Slack channel #-emis-deprecation
EMIS is an external service integrated into vets-api and appears to be engrained into the vets-api codebase.
A large part of eMIS, is the pre-fill service. The pre-fill service makes a simple API call to Vets API, allowing veterans to have their information prefilled within forms to reduce typing and ultimately the time it takes to fill out a form. EMIS is heavily used in the pre-fill service to fill in information related to veteran military information, status and payments.

Noted in #15093: It's only used as part of an array of dependencies for the <DowntimeNotification> component. Removing it from the array of dependencies passed into it, along with a few other small codebase tweaks...

## Acceptance Criteria
- [ ] Test data is removed
- [ ] eMIS code data is removed

## Team
Please check the team(s) that will do this work.

- [ ] CMS Team
- [ ] Public Websites
- [x] Facilities
- [ ] User support
- [ ] Accelerated Publishing

**Comment by jilladams** [comment]
I just took a look at this PR and I think we got sideswiped here on accident. The intention was to audit Facilities owned products and remove _our team's_ dependencies on EMIS in vets-website. @maxx1128 , the scope of what you implemented is repo-wide, not Facilities-wide, right? That is very helpful in explaining why it was not, in fact, a 2 point ticket. 

In future: if you're having to touch code for products that don't belong to our team, wave a 🔴 flag, and let's discuss! This is a nicety for everyone else who referenced EMIS, but PR review is likely to be a little wild, I'm guessing, and we may need to discuss that if it absorbs a lot of your time / hand it back to the team managing EMIS deprecation.

**Comment by jilladams** [comment]
Have reached out to Lainey Trahan and Rebecca Tolmach for insights. I know other teams have reported they are working on migration off of EMIS, so straight removal is likely going to conflict with other work in progress from those teams. We should hear feedback on the PR as well, I'd imagine. 

@maxx1128 it may help to get a note from you here to clarify: were any of the changes made in that PR specific to Facilities? I don't see any, and want to confirm that, in order to understand how we should proceed with this PR.
