### ISSUE TITLE
PAW: FE: Add content (post-research from Danielle) content changes

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#15412]
## Description
These are the content changes needed for PACT Act, and then Danielle will circle around with Stakeholders

- [x] Need deletion of the sentence below, found under "What this means for you" at the URL shown below. (Question: Does this sentence display anywhere else in the Wizard?)
  - [x] Sentence to delete: We automatically assume (or “presume”) that these exposures cause certain health conditions. We call these “presumptive conditions.”
  - [x] URL: https://staging.va.gov/pact-act-eligibility/results-1-1
- [x] Need deletion of the sentence below, found under the list of conditions at the URL shown below:
  - [x] Sentence to delete: Note: If your condition isn’t listed here, you can learn more about other presumptive conditions and disability benefit eligibility. And if you have an illness that we don’t consider presumptive, you can still file a claim. But you’ll need to provide evidence that your service caused your condition.
  - [x] URL: https://staging.va.gov/pact-act-eligibility/results-1-2

## Status
- 2024-01-08 from Danielle T: I sent 2 updates just before the break. I think you all are working on those now. I don't have any further updates at this time. When those are complete, please let me know. I'm working with OPIA to brief VA leadership on this tool before launch. There is a possibility there will be content changes that come from that.

## Acceptance criteria
- [x] Content at URL: va.gov/pact-act-eligibility/results-1-1 is updated as per Description
- [x] Content at URL: va.gov/pact-act-eligibility/results-1-2 is updated as per Description
- [x] App behavior is unchanged
- [ ] Fran to notify Danielle that these have been implemented.

**Comment by jilladams** [comment]
Q to @thejordanwood & @FranECross : I don't think we have a corresponding ticket to update the PACT Act logic flow with any content changes -- when we get content feedback, we may want to either tack Jordan on here and add an AC for that, or make a new ticket for it.

**Comment by thejordanwood** [comment]
@FranECross Yes, I'd like a separate ticket for content please!

**Comment by FranECross** [comment]
@thejordanwood New ticket created. 😁 #16128  cc @jilladams

**Comment by FranECross** [comment]
[11/20] I touched base with Danielle today, and she plans to have all content revisions to us by Monday, 11/27.

**Comment by randimays** [comment]
@FranECross @cindymerrill Noting here - the results screens for Cindy's prototype do involve logic changes. The current flow does not have any dynamic content based on responses as indicated in Danielle's document. We need to implement those.

**Comment by FranECross** [comment]
> @FranECross @cindymerrill Noting here - the results screens for Cindy's prototype do involve logic changes. The current flow does not have any dynamic content based on responses as indicated in Danielle's document. We need to implement those.

@randimays Just to confirm that a ticket FE or BE or both?) needs to be created to adjust/ensure the logic flow is correct/updated/implemented? If so, then I'll create one. Thanks! cc @jilladams 

As an aside, I do have a ticket for Jordan already created to update the content for the logic flow.

**Comment by cindymerrill** [comment]
@FranECross 

> As an aside, I do have a ticket for Jordan already created to update the content for the logic flow.

Do you mean me and not Jordan? I'm updating the content in the Survey Monkey prototype.

**Comment by cindymerrill** [comment]
I believe that @randimays built the R1 prototype pages for usability testing using a design mockup that @thejordanwood built from a text mockup that I put together. So it's likely that Randi wasn't using Danielle's Word document of content and thus didn't see all the dynamic content specifications needed to populate the results pages. Would it help Randi if Jordan built a design mockup for this revised content, or is that not needed? FYI @FranECross @jilladams

**Comment by randimays** [comment]
@cindymerrill I did use Danielle's Word document for content; I don't think @thejordanwood built a comprehensive comp with all the text content (but I may have forgotten). All I need for updates is Danielle's updated Word document, and I have access to that already.

**Comment by FranECross** [comment]
@FranECross Confirm with Danielle on final (final) content.

**Comment by jilladams** [comment]
Most recent content changes to Staging are shipped, and this ticket will rack up any further edits toward launch. Danielle's most recent update on 12/22 includes 2 comments in this SharePoint doc that need to be addressed: https://dvagov-my.sharepoint.com/:w:/g/personal/danielle_thierry_va_gov/EUHemrVkxrVNnr6p_Al7evUBABvo3vtptiWyXA-L8uS7Fg?e=K6DsMs.

Related slack thread: https://dsva.slack.com/archives/C52CL1PKQ/p1703255576716919?thread_ts=1702404832.197869&cid=C52CL1PKQ

**Comment by DanielleThierryUSDSVA** [comment]
Hi, @jilladams! Could you let me know when the 2 comments in the doc above are addressed so I can share the final version of the results screen with OPIA? Thanks!

**Comment by FranECross** [comment]
@DanielleThierryUSDSVA I've reviewed the sharepoint document and compared it to the PACT Act on Staging, and then updated this ticket with the in changes you indicated in the document. I believe that the below items that were originally put on this ticket are no longer valid. Are you able to confirm? I'll have this ticket poised to be brought into the next sprint starting on 1/17. Thanks! cc @jilladams @chriskim2311 @randimays (BTW Jill and Randi are OOO today).

- [ ] Need final links:
  - [ ] introduction page: `Get PACT Act information for survivors`
  - [ ] results 1 page 1: `Review Agent Orange C-123 aircraft codes and service dates` (dynamic content: "Yes" for Orange 2.2.2)
  - [ ] results 2: `Learn about Camp Lejeune and VA benefits`
- [ ] Need final URLs for all questions & results pages

**Comment by FranECross** [comment]
@chriskim2311 Here's the ticket I mentioned in Standup that you can pull in if you need work. Let me know if there are any questions. Thanks! cc @jilladams

**Comment by chriskim2311** [comment]
@DanielleThierryUSDSVA @FranECross @jilladams @cindymerrill The revisions have made it to prod please verify when you get a chance thank you!

**Comment by FranECross** [comment]
@chriskim2311 Looks good, but I'll defer to @DanielleThierryUSDSVA for final approval. Thanks!

**Comment by randimays** [comment]
Pinged Danielle on an older Slack thread to ask her to review: https://dsva.slack.com/archives/C52CL1PKQ/p1706214406355629?thread_ts=1704742429.579119&cid=C52CL1PKQ

**Comment by jilladams** [comment]
Closing based on staging verification and we can cut new tickets for further changes as needed.
