### ISSUE TITLE
Vet Center Outstations should display common and official names in Drupal

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#15422]
## Background
VA facilities can renamed to honor a particular individual. Use of the legislated name is required but it is sometimes helpful to retain the geographic or community name for familiarity or discoverability reasons. 

The Vet Center approach has been to use the legislated/official name as the `Name of Vet Center` with the previous geographic name as the `Common name`. On the Veteran-facing front end, the official name is used for the H1 title for the page followed by the common name displayed as "also called". 

## Problem Statement

The Outstation associated with Salt Lake City Vet Center is displayed using only the Official name. The Common name concept needs to be available for Outstations as well. 

Example: Major Brent Taylor Vet Center Outstation (node/17527), associated with [Salt Lake City Vet Center](https://www.va.gov/salt-lake-city-vet-center/locations/)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZzNkIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--28c78c896ee1f339cda8dec32d062c36e2494f64/image.png)

## Acceptance Criteria

- [ ] Similar to a Vet Center, an Outstation can save both an official/legislated name and a common name.
- [ ] Similar to a Vet Center, when an Outstation is legislatively renamed, the official name becomes the Name of the facility and the previous geographic name becomes the common name.
- [ ] The migration of Vet Center - Outstation adds the facility name to the `field_official_name` and copies it over to the node title (if the node title is empty).

## Team
Please check the team(s) that will do this work.

- [ ] CMS Team
- [ ] Public Websites
- [x] Facilities
- [ ] User support
- [ ] Accelerated Publishing

**Comment by xiongjaneg** [comment]
This should not apply to CAPs, which have their own naming convention.

**Comment by xiongjaneg** [comment]
@xiongjaneg need to stub ticket for naming schema update to reflect current state of Vet Center naming schema

**Comment by omahane** [comment]
### Current data content models
Vet Center
- Common name (title [property])
- Name of Vet Center (field_official_name)

Vet Center Outstation
- Title (title [property])

### For Vet Center - Outstation
Do we want to reuse the `field_official_name` for Vet Center Outstation?
If so, do we want to change the Title to Common name?
If so, do we want to programmatically move all the data in Title to `field_official_name`?
If so, shouldn't we also have a front-end task (for va.gov) around changing this to match the way we show Vet Center names?

### Vet Center
Also, right now the Facility Locator doesn't show the common name for Vet Centers, only the official name. Should that change? It seems confusing, given the following

- The URL remains the common name.
- The common name is the prominent one on the facility page.

![Screenshot 2023-10-17 at 8 25 06 AM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/766573/a285f3d2-8cc5-4bb2-ac8e-add97f6215c4)

**Comment by omahane** [comment]
After conversation with @swirtSJW, @davidmpickett and @mmiddaugh, the conclusion is 
- Follow the Vet Center pattern
  - Use the `title` property for the common name
  - Use the `field_official_name` for the official name 
  - Write an hook_update_N to copy data from `title` to `field_official_name`
  - Update the migration put the name from the Facilities API into `field_official_name` 

There's a [front-end ticket](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15424) already.

We have approached Lighthouse about adding a field for common name so that consumers of the Facilities API would have both the official name from and the common name (from the CMS).

**Comment by swirtSJW** [comment]
@omahane This is done other than coordinating the run of the copy script by the devops team.   Can you coordinate that?

**Comment by omahane** [comment]
> @omahane This is done other than coordinating the run of the copy script by the devops team. Can you coordinate that?

Yes.

**Comment by omahane** [comment]
## The script run conversation:
https://dsva.slack.com/archives/CT4GZBM8F/p1698243756667109

## Log
![Screenshot 2023-10-25 at 9 31 07 AM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/766573/6c81f04a-2298-4ea2-b1ed-edc6c7364bca)

## Vet Center - Outstation example
![Screenshot 2023-10-25 at 9 32 10 AM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/766573/7209e3c7-109a-4a4e-a836-1009fab2a5bd)
