### ISSUE TITLE
site_alert: delete during deploy did not seem to run

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#1542]
When the deploy failed on 4/20   and I had to go remove the System update in progress message, I notice the the warning message was still present.   This leads me to believe that the Before any site alert is added, there should be a call to site_alert: delete to get rid os any existing alerts.

![image](https://user-images.githubusercontent.com/5752113/79795042-53203300-8321-11ea-88a8-d2491312e557.png)

Additional proof that they are not being deleted
![image](https://user-images.githubusercontent.com/5752113/80010566-994bd280-8498-11ea-92b4-0ae4b805fde5.png)

**Comment by indytechcook** [comment]
Also, All site alerts should be deleted before any new ones are added.

**Comment by indytechcook** [comment]
This is part of PR: https://github.com/department-of-veterans-affairs/devops/pull/6816.
