### ISSUE TITLE
Prepare Drupal 10 Updates Demo at VHA DM Office Hours on Oct. 11, 2023

### ISSUE THREAD

**Issue by BerniXiongA6** [department-of-veterans-affairs/va.gov-cms#15420]
## User Story or Problem Statement
As a CMS user, I need accurate information on how the CMS is changing with the Drupal 10 update so that I can understand how that affects my workflow or editorial experience.

## Affected users and stakeholders
- CMS content editors from VAMC

## What You Need to Know 
- Erika will inform Blake and Justin (VHA DM) that CMS will be providing a 5-minute demo at their VAMC Drupal CMS Office Hours on October 11, 2023
- The demo will be co-presented by Laura F. (who will cover accessibility) and Troy G. (who will provide a brief walkthrough of the notable changes)
- Resources from Laura that can be incorporated into the demo: ckeditor product outline ([link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/product-outlines/ckeditor/README.md))
- Laura's ticket already in progress for KB article #15154 

## Acceptance Criteria
- [x] a11y talking points have been finalized
- [x] training talking points have been finalized
- [x] visual being used for demo has been finalized (e.g. if it's a slide deck, then screenshots have been included on the slides; if it's a demo environment, then the environment has been created)
- [x] PM and PO have both reviewed and approved the demo before or by October 5th (Erika OOO on the 6th)

## To Do / Tasks (for the Assignee to complete)

**Comment by BerniXiongA6** [comment]
Notes for @BerniXiongA6 -- 4 points for Troy training development, 1 pt for Laura review -- for sprint 94

**Comment by TroyA6** [comment]
@BerniXiongA6 @EWashb @laflannery @stefaniefgray  - I have created an initial draft of the 'D10 Changes to CK Editor' document for a first review.... I welcome all feedback!

The thinking is that the document will summarize / visualize the changes. Those changes can be explained/described/demoed in the live session.

[D10 CKE Changes.pdf](https://github.com/department-of-veterans-affairs/va.gov-cms/files/12765887/D10.CKE.Changes.pdf)

**Comment by laflannery** [comment]
@TroyA6 I think this looks good! I have one suggestion:

> Functionality: ‘Styles’ options are context sensitive

'Styles' have always been context sensitive - meaning you always had to highlight linked text before the link styles (not just the address block style) would activate, I just didn't know this.

The change that is happening is:
- we are now limiting the styles by removing the 3 button styles that were available
- also the display is changing a bit because previously the styles weren't visible at all unless you highlighted a link but not they will be visible but disabled (see screenshots):
**Prod no link highlighted:**
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/106678594/ec4b2865-143f-4715-8648-3a21c1146543)
**Prod link highlighted:**
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/106678594/b6461d14-414c-4d9c-b27e-2db14791d304)
**D10 no link highlighted:**
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/106678594/d1e39180-263a-48c7-b73c-9a5ab8e219bd)
**D10 link highlighted:**
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/106678594/5a9572cb-6785-4e88-beab-dbd2ae9637cd)


So I think I might suggest changing this to something similar to:

> Functionality: ‘Styles’ options have been limited and will be disabled when unavailable

**Comment by BerniXiongA6** [comment]
@TroyA6 Thanks for getting on the initial draft so quickly. Could you clarify, is this initial draft your talking points or is this the intended doc/slide you'll plan on screensharing to demo the D10 changes to editors? If this is intended to be the visual you'll be screensharing, I would recommend more screenshots and less text (perhaps have the talking points and the screenshots on separate docs/slides). I'll defer to @laflannery for the specifics of changes to be discussed. cc: @EWashb

**Comment by TroyA6** [comment]
Thank you @BerniXiongA6  - this is the summary of changes/talking points.
The Screenshared Presentation will be a separate document - in progress now - with screenshots. Should have that available for review today.

**Comment by TroyA6** [comment]
@BerniXiongA6 @EWashb @laflannery @stefaniefgray  - I have created the initial **[Presentation](https://docs.google.com/presentation/d/1u9H0Pt8YB2uX67A6asY4hCJir0lashUm7-dhK094gdM/edit?usp=sharing)** for next week. Please provide any feedback for improvement!

**Comment by EWashb** [comment]
@TroyA6 unfortunately my GFE blocks me from Google Drive/Docs. I'll let @BerniXiongA6 and @laflannery give their feedback first and then feel free to export as a PDF or add to SharePoint for me to review

**Comment by laflannery** [comment]
This looks good @TroyA6! I have gone through and added some comments that might make things a bit more consistent. I also added one suggestion about showing the new link field that I know we hadn't discussed but I think it is probably good to show when discussing the new appearance.

**Comment by BerniXiongA6** [comment]
Hi @TroyA6 I've left comments in the slide deck and after those changes have been made, I'd look forward to getting a runthrough of the demo -- but only after you're able to share the updated slidedeck with @EWashb -- thanks !

**Comment by TroyA6** [comment]
Hi @BerniXiongA6 @EWashb @laflannery  - I have updated the show and have a pdf version for your review...
I tried to accommodate all suggestions, but please let me know if I've missed anything!
[Drupal 10 CMS – WHAT’S NEW.pdf](https://github.com/department-of-veterans-affairs/va.gov-cms/files/12808562/Drupal.10.CMS.WHAT.S.NEW.pdf)

**Comment by laflannery** [comment]
@TroyA6 Just a couple additional edits:
- Slide 13 (Abbreviation):
  - "Enhances screen reader use" is duplicated, this was already mentioned on the previous slide. We may not need to say it here again?
- Slide 15 (Links):
  - The directions you have are for adding external links only  - but the screenshot is an internal node.
  - When adding an link to an internal, you are still able to (and should) type in the name/title of your content to get a list of suggested internal nodes:
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/106678594/7b852852-9fc1-4d22-8abf-76e492acfa43)
  - Then you will select the correct node to create the internal link:
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/106678594/429e36e6-987a-4a73-bb91-4304173d2f4c)

These link directions are in [the current KB article here](https://prod.cms.va.gov/help/cms-basics/how-to-use-the-rich-text-editor#undefined). So it's not what the editors should do that has changed, just that the interface where they are doing it has changed a bit.

**Comment by BerniXiongA6** [comment]
@TroyA6 gave a walkthrough of the presentation w/ @EWashb and @BerniXiongA6 today -- all approved and good to go for 10//11! Berni will reach out to Blake S. (VHA DM) to confirm that the presentation can be recorded and video later shared with CMS team. Thanks all!

**Comment by TroyA6** [comment]
just adding the final presentation for documentation -- 
[Drupal 10 CMS – WHAT’S NEW.pdf](https://github.com/department-of-veterans-affairs/va.gov-cms/files/12833055/Drupal.10.CMS.WHAT.S.NEW.pdf)
