### ISSUE TITLE
Create client side validations for alt text input fields across the CMS.

### ISSUE THREAD

**Issue by BlakeOrgan** [department-of-veterans-affairs/va.gov-cms#15436]
## User Story or Problem Statement
Once [ticket 15435](https://app.zenhub.com/workspaces/vagov-cms-team-5c0e7b864b5806bc2bfc2087/issues/gh/department-of-veterans-affairs/va.gov-cms/15435) has been completed, we will need to implement client side validations using the [client side validation module](https://www.drupal.org/project/clientside_validation) for the same hard validations that were created as part of ticket 15435.

These clientside validations would be for all instances of the alt text input field across the CMS as decided on in [ticket #15241](https://app.zenhub.com/workspaces/vagov-cms-team-5c0e7b864b5806bc2bfc2087/issues/gh/department-of-veterans-affairs/va.gov-cms/15241)

As part of the alt text improvement initiative, we will need to throw an error using the error messages outlined in the design file to users immediately when...

- Alt text field is empty once focus is removed.
- Alt text reaches 151 characters or more.
- Alt text contains any of the following phrases “image of”, “photo of”, “graphic of”, or “picture of”.
- Alt text contains any of the following file extensions: .png .gif .jpg .jpeg

## Description or Additional Context 
Here is a link to the [Figma file](https://www.figma.com/file/OXueAhBrPif6wh8vynPxGs/Alt-Text-Errors?type=design&node-id=529%3A11615&mode=dev) WITH CLIENT SIDE VALIDATION for additional context.

## Acceptance Criteria
- [ ] Client side validations for all of the bullets above have been created.
- [ ] Users are given an error message as soon as any of these instances happen.
- [ ] Error messages do not go away until corrections are made. 
- [ ] Ensure errors are piped to datadog
- [ ] Designs match figma file
- [ ] Requires design review
- [ ] Requires accessibility review

## Team
Please check the team(s) that will do this work.

- [x] CMS Team
- [ ] Public Websites
- [ ] Facilities
- [ ] User support
- [ ] Accelerated Publishing

**Comment by mgifford** [comment]
Wanted to add that it would be useful to warn users when the alt text:

*   **Too Brief Check:** When the text is under 10 characters
*   **Redundancy Check**: When duplicate information is already present in the surrounding text

**Comment by mgifford** [comment]
https://yatil.net/blog/there-is-no-character-limit-for-alt-text

Language of the page matches language of the alt text

**Comment by edmund-dunn** [comment]
Closing this as complete.
