### ISSUE TITLE
Vet Center main page "For full guidance, see How to edit Vet Center pages" link is broken

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#15431]
## User Story or Problem Statement
As a Vet Center editor, when I'm editing my Main Vet Center page, I get a broken link when I click For full guidance, see How to edit Vet Center pages
<img width="1386" alt="Screenshot 2023-09-27 at 1 31 48 PM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/73648238/9fab5f08-fa91-4833-9efa-0f1234eeb15a">

Currently, this produces a page not found error
<img width="370" alt="Screenshot 2023-09-27 at 1 32 05 PM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/73648238/cd722946-71e4-4296-ad3c-c6c2162226ff">

This should link to /help/vet-centers

## Acceptance Criteria
- [ ] Clicking the link in the "For full guidance, see How to edit Vet Center pages" opens the Knowledge Base node /help/vet-centers

## Team
Please check the team(s) that will do this work.

- [ ] CMS Team
- [ ] Public Websites
- [x] Facilities
- [ ] User support
- [ ] Accelerated Publishing

**Comment by davidmpickett** [comment]
Closing in favor of https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16118 which has slightly more detail
