### ISSUE TITLE
FE: unit test coverage of new header

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#15449]
## Description
Platform team, as of 10/12/23 will enforce >=80% unit test coverage in order to approve any new launch. 

Federal header will need to comply with that mandate, and be able to demonstrate that 80% of our code is covered by code scanner, in order to pass Staging Review (QA Standards portion). 

## Background
https://dsva.slack.com/archives/C52CL1PKQ/p1695917981684259 

## Acceptance Criteria
- [ ] Code scanner demonstrates 80%+ code coverage via unit testing for new header code

**Comment by FranECross** [comment]
@randimays @jilladams I feel that this is going to be taken care of during coding of the new header/footer. Do you concur that I can just close this? Thanks!

**Comment by randimays** [comment]
@FranECross Yes indeed!

**Comment by FranECross** [comment]
Closing as obsolete - see comments just above.
