### ISSUE TITLE
Orphaned paragraph report white screening

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#15443]
## Describe the defect
When visiting the orphaned paragraph report (/admin/reports/orphaned-paragraphs) , there is an error

```
The website encountered an unexpected error. Please try again later.
ArgumentCountError: Too few arguments to function va_gov_backend_get_top_parent_entity(), 1 passed in /var/www/html/docroot/modules/custom/va_gov_backend/src/EventSubscriber/OrphansReportViewsEventSubscriber.php on line 155 and exactly 2 expected in va_gov_backend_get_top_parent_entity() (line 2066 of modules/custom/va_gov_backend/va_gov_backend.module).
```
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5752113/12576c3d-a6e8-4e6c-b0d4-287a585e897a)

When I don't get that error, I get a gateway timeout
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5752113/09184f02-1724-49dd-bc84-541c942aadb6)

## To Reproduce
1. Go to https://prod.cms.va.gov/admin/reports/orphaned-paragraphs
2. wait a long time
3. See error  or gateway timeout

## AC / Expected behavior
A report of any paragraph entities that have no parents.

 ## Additional context
This was built a while back by the CMS team.   It is a way to keep an eye on the health of the site.  This report should either be fixed, or removed.  This is NOT an urgent issue.

**Comment by ndouglas** [comment]
This and #15447 are dupes; this was closed in #15447.
