### ISSUE TITLE
UX questions to explore during VBA Regional Office pilot phase

### ISSUE THREAD

**Issue by davidmpickett** [department-of-veterans-affairs/va.gov-cms#15484]
A place to park things that would best be answered by observing users interacting with the system. Inquiry methods may include hallway usability testing, editor interviews, or surveys.

## General questions
- Do users understand the interface?
  - Are labels, help text, and other text in interface clear?
  - Are widget interactions intuitive (buttons, checkboxes, etc)?
- Are the fields and content types configured correctly to meet their needs?
  -  How easy is it to get to the content they need to edit?

## Specific questions
- What should the cardinality of the Service Locations on VBA Facility Service be?
  - Does Anchorage use multiple?
  - Is there a cap to impose?

**Comment by xiongjaneg** [comment]
moving content to #16295 and closing
