### ISSUE TITLE
Design: Full-width Banner Alerts Date limits and notifications

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#15495]
## Description

We need a CMS design for Editors being able to set an expiration date for Full-width banners. 
We need an email design for the notification(s) Editors will get when: 
* Expiration approaches
* Expiration is day of
* Content is archived

How might we ensure a better site-user experience by ensuring alignment to our VA.gov style guide. Encourage appropriate use of banners for time-sensitive items, in limited quantity. Any new Full-width banner content type would be published for an initial default timeframe (probably 7 days), that can then be extended.

### User story

**AS AN** Editor 
**I WANT** to select the initial period for display of my full-width banner, up to 7 days
**SO THAT**  site visitors always get a relevant experience.

**AS A** VA owner 
**I WANT** aging banners to expire
**SO THAT**  site visitors always get a relevant experience.

## Context
https://prod.cms.va.gov/node/add/banner -- this is the form where we'll be adding the date expiration stuff

## Design
[Figma file](https://www.figma.com/file/n2F9Y0QhjNoeNyQ4zv2VER/Full-Width-Banner-Alerts?type=design&node-id=0%3A1&mode=design&t=dWmDMYhlqBe68kUL-1) that shows content type updates and email template

## Acceptance criteria: Sprint 95

- [x] A UX is designed for Editors to manage setting an expiration date for full-width banners. Should include information about the default timeframe. 
- [x] Email structure from Vet Centers / VAMCs will be reused for this, Swirt has details, Blake may have the Figma template

## Acceptance criteria: Sprint 96
- [x] Review with engineers
- [x] Review with a11y
- [ ] ~Open CMS collab cycle ticket~ -- creating a separate ticket to track

**Comment by jilladams** [comment]
We discussed whether a CMS UX should display a warning that full-width alerts are about to expire. This would be a new paradigm so not included in scope for this effort.

**Comment by jilladams** [comment]
We think Blake developed the email template and it may already live in Figma.

**Comment by thejordanwood** [comment]
I created a [Figma file](https://www.figma.com/file/n2F9Y0QhjNoeNyQ4zv2VER/Full-Width-Banner-Alerts?type=design&node-id=0%3A1&mode=design&t=dWmDMYhlqBe68kUL-1) that shows content type updates and an email template. I'm going to work on getting feedback from the CMS team and PW engineers on this design.

**Comment by thejordanwood** [comment]
**End of sprint update:**

The engineering ticket for this work is going to roll over. I have a design for this ready in the Figma file, but will need to ask engineers for their feedback. Once I get feedback and confirm what's possible to implement for this, we can open a CMS collab cycle ticket. 

I'm updating my ACs on this ticket to reflect this.

**Comment by thejordanwood** [comment]
@jilladams @FranECross I reviewed this design with @dsasser yesterday and have made the changes that came out of this review. This is ready for a CMS collab cycle ticket.

**Comment by thejordanwood** [comment]
Accessibility feedback:

We need to look into validating against the start date field. If editors put an end date more than 7 days, we should show them an inline error message before they save.

**Comment by thejordanwood** [comment]
**Pre Out of Office Update:**

@jilladams @FranECross I asked these questions in a slack thread, but am adding them here too. 

1. Would it make sense to close this ticket, and create a follow up ticket to allow Daniel time to look into the accessibility feedback?
2. One of the ACs on this ticket is to open a CMS Collab Cycle ticket. I still think this is possible, because the accessibility note doesn't change the overall design. Is that reasonable?

If the CMS Collab cycle ticket gets opened, then this ticket can close.

**Comment by FranECross** [comment]
@thejordanwood Thank you for the follow up! I believe Yes to #1 (close this ticket/create follow up ticket), and #2 does sound reasonable. @jilladams I'm always happy to defer if we should do something different. 😁

**Comment by jilladams** [comment]
@FranECross makes sense to me, we just need to file the follow up ticket re a11y review, and the [CMS collab cycle ticket](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/new?assignees=BerniXiongA6&labels=CMS+Team%2C+Needs+Analysis%2C+CMS-Collab-Cycle%2C+Epic&projects=&template=cms-collaboration-cycle-request.yml&title=CMS+Collaboration+Cycle+for+%5BTeam+Name%2C+Product+Name%2C+Feature+Name%5D).  Wanna handle those, or would you rather I handle?

**Comment by FranECross** [comment]
A couple of questions having to do with the [A11y ticket](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16014)

@thejordanwood > Question number 4 in the the A11y ticket asks "4. Are there any specific testing requirements that should be noted?", but I'm not sure of the answer. 

@jilladams Question number 6 in the ticket asks "When does the product need to launch?" Is the target for this before the Winter Holiday code freeze? (before Dec 21?)

Thank you both in advance!

**Comment by jilladams** [comment]
From scrum: 
* We can clarify the a11y questions on that ticket. 
* We want to step one level up on this project and make an initiative brief, and do some high level product requirements gathering to make sure we're thinking through this correctly and have that in hand before we schedule CMS Collab Cycle Review. 
  * Breaking the AC for CMS Collab Cycle ticket out into its own ticket: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16033

FYI @thejordanwood and @FranECross
