### ISSUE TITLE
[Aging Content - Promo Blocks] Homepage news/benefit promo blocks: Design for aging content email and UI help text

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#15497]
## Description

We want Editors to frequently update the Homepage  news/benefit promo blocks, and to be notified when content is stale. 

https://prod.cms.va.gov/block/208
https://prod.cms.va.gov/block/209

### User story
> _Describe the audience/user, enhancement or fix, and value / outcome desired._

**AS A**
**I WANT**
**SO THAT**

## Questions
Right now the aging content notifications are sent out monthly on the 1st. We don't know where / how that timing is set. We would like to find out from Drupal folks if it's possible for the Block form help text to display the timeframe for notifications refresh based on the setting.

## Acceptance criteria
- [ ] Email template content and Block form helptext are designed for Homepage promo blocks

**Comment by FranECross** [comment]
Closing as duplicate/outdated ticket.
