### ISSUE TITLE
[Aging Content - Blocks] Drupal: Implement Ability to auto-archive any content type

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#15508]
## Elevator Statement
Create a way for any content type that's in a published state, and that has an expiration date, to be permanently auto-archived.

## Description

To provide timely information to Veterans and other users of VA.gov, and ensure stale content isn't displayed to Veterans, their caregivers, family or survivors, we want content in a 'published' state that has an expiration date assigned to be auto-archived EOD on the content's expiration date.

## User Story

**AS A** PO/PM, 
**I WANT** to know that content will be auto-archived on the last day of the timeframe assigned to it, 
**SO THAT** Veterans, their caregivers and other VA.gov users see only current, relevant information 

## Examples of Stale Content
**Stale Banners**
- How Veterans Can Register to Vote
- National Buddy Check Week (for one week in October; still up in late November)
- Recognizing LGBTQ+ Veterans During Pride Month (still up several months after Pride Month)
- It’s Time to “VAX to the MAX!” (outdated)

 **Stale Home Page News Spotlight Block**
 This news block navigates users to an article published in May 2023. An updated news article should have been published by now (Dec 2023).

 <img width="577" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/147188767/3b688d6c-7850-4c8f-9ab7-613239db6a9e">

## Acceptance Criteria

**GIVEN**: content is in a published state (e.g. Full width alert (aka full width banner), Home page news spotlight block, etc.) 
**WHEN**: content as been assigned an expiration date
**AND**: EOD (end of day) occurs on the expiration date
**THEN**: the content is permanently auto-archived

**Comment by FranECross** [comment]
@dsasser FYSA: I've created this epic to house the tickets that'll be created for the auto-archiving portion of Aging Content. I'll create another epic to house the tickets for actually then auto-archiving the different content types we're working with.

**Comment by FranECross** [comment]
Won't be done per Dave Conlon. We can always resurrect if we decide in the future to pursue.
