### ISSUE TITLE
Convert existing views to use the new filter for moderation state for additional workflow

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#15503]
## User Story or Problem Statement
An additional workflow will be used for the VBA RO Pilot MVP. Existing views will need to be updated to use the new filter for moderation state to account for the additional workflow.

Noting: without the 2nd workflow implemented, we will not be able to test the workflow but: we will be able to prove nothing breaks. 

## Acceptance Criteria
- [ ] After change, a list is provided of all views that will be affected, and added to #11334 as test criteria to verify the workflow change.
- [ ] All affected views function as expected
  - [ ] Moderation state 
- [ ] Requires accessibility review of the new filter

**Comment by jilladams** [comment]
Need to prefine, verify if this blocks #11334, or if that could move forward first.

**Comment by swirtSJW** [comment]
The PR for this is in code review.  Passed QA from facilities' team.  Just waiting for review from CMS team.

**Comment by swirtSJW** [comment]
This has been merged and should go out tomorrow.

**Comment by swirtSJW** [comment]
THis has made it to prod and should be closed.
