### ISSUE TITLE
Implement equivalent of content-build.css if necessary

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#15511]
## Requirements

We should determine if we need content-build.css, and implement an equivalent in Next Build, so that styles are consistent between both Content Build and Next Build.

```[tasklist]
### Acceptance criteria
- [ ] Discuss with Design Team whether to continue with one-off style for Medallia button and if so how that should be implemented
- [ ] Styles for the content footer are correct as per Design Team advice
```

## Background & implementation details

content-build.css is small and is built from a small Sass file: https://github.com/department-of-veterans-affairs/content-build/blob/main/src/site/assets/sass/style.scss

It is most likely that these styles should reflect the design system, rather than being stored here. We'll most likely have one of three options, in order of preference:

1. The Content Footer is already correct and we do not need to do anything.
2. These styles are derived from or integrated into the VA Design System (consult with the Design Team).
3. We implement a small Next Build style process that builds and provides these styles.

```[tasklist]
### Implementation tasks
- [ ] Use this if it helps you or feel free to delete.
```

**Comment by tjheffner** [comment]
I think we will need to add this stylesheet for the time being. It does make our feedback button slightly larger (which then matches va.gov). I didn't add the other styles, that would presumably fix the spacing issues here.

before:
![Screenshot 2023-10-03 at 8 05 43 AM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/11279744/57b5d28a-7983-4f64-8310-f26119a50c48)
after:
![Screenshot 2023-10-03 at 8 05 48 AM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/11279744/9cd1b726-627a-440d-886c-62695f558f5d)

va.gov:
![Screenshot 2023-10-03 at 8 06 17 AM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/11279744/6b5d3bf3-c696-4f93-ab23-1f6912967e42)

**Comment by tjheffner** [comment]
@timcosgrove probably. it doesn't appear to match any of the existing button styles in the system https://design.va.gov/components/button/

really feels like a one-off, and likely something that should be using one of those styles / not owned by us

**Comment by tjheffner** [comment]
Reached out to the design system team here: https://dsva.slack.com/archives/C01DBGX4P45/p1696973320406019

**Comment by tjheffner** [comment]
Per Design System Team, I do not think we should move this button style over. We may still need to include the other styles for content footer spacing.
