### ISSUE TITLE
Investigate viability of Metatag 2.0 Drupal module

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#15515]
## Requirements

We need metatag information to be included in JSON:API responses, so that we can construct metatags on the front end.

```[tasklist]
### Acceptance criteria
- [ ] Metatag v2 is confirmed to install without issue
- [ ] Metatag v2 produces the same output for GraphQL for content types that build front-end pages
- [ ] Metatag information is available in JSON:API and is equivalent to the GraphQL response for a given page
```

## Background & implementation details

[Drupal's Metatag module has a new 2.0 version](https://www.drupal.org/project/metatag), which among other things provides JSON:API support. This is important to the AP Team, as it is necessary to populate metatags for built static pages.

We should thoroughly explore Metatag 2.0 to see if it causes any disruption to current functioning of the CMS and Content Build, and also to see if it helps meet the needs of the AP project.

```[tasklist]
### Implementation tasks
- [ ] Use this if it helps you or feel free to delete.
```

**Comment by ryguyk** [comment]
(WIP)
## Findings

### Overview

### Methods
For each content type we need to examine, there are two steps:
#### Step 1
Ensure GraphQL query returns same data (ideally, same _exact_ data shape) using Metatag 2.0 compared to previous Metatag version. To determine this, we can use two different Drupal installs, one of which has the existing Metatag version and the other of which has Metatag 2.0.
   - Existing Metatag version: [this tugboat](https://main-xvxws7swcqwju7dzbhs2bwu0se0uwvpm.demo.cms.va.gov/graphql/explorer)
   - Metatag 2.0: local/PR tugboat

For each content type, this is the GraphQL query used to ensure compatibility:
```
query {
  nodeQuery(
    limit: 1
    offset: 0
    sort: { field: "nid", direction:  ASC }
    filter: {
      conditions: [
        { field: "status", value: ["1"] },
        { field: "type", value: [{NODE_TYPE}] }
      ]
  }) {
    entities {
      entityId
      entityLabel
      entityMetatags {
        __typename
        key
        value
      }
    }
  }
}
```


#### Step 2
On the environment with Metatag 2.0, ensure JSON:API request returns necessary metatag information, and note any differences in data shape.

For each content type, this is the JSON:API query used:
```
/jsonapi/node/{NODE_TYPE}?fields[node--{NODE_TYPE}]=title,metatag&filter[status][value]=1&page[limit]=1
```
E.g.
```
/jsonapi/node/news_story?fields[node--news_story]=title,metatag&filter[status][value]=1&page[limit]=1
```


### Content Types


```

```

#### News Story
```

```

**Comment by timcosgrove** [comment]
This was merged to the CMS and is operating without issue.
