### ISSUE TITLE
Focus Content and skip to content link

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#15512]
## Requirements

A standard accessibility feature is a 'Skip to content' link that allows a screen reader user to bypass navigation and other parts of the page that are prior to the main content of the page. We should implement this to support Veterans who make use of screen-readers to get information from VA.gov.

```[tasklist]
### Acceptance criteria
- [x] A skip to content link is available at the top of all pages
- [x] The skip to content link becomes visible when it has focus
- [x] The link takes the user to the main content area
```

## Background & implementation details

Note that the implementation does not need to match content-build; only the functionality needs to match. If this should be a web component, that is fine. If there is something off-the-shelf to do this in Next.js, that is fine.

Function implementation in content-build: https://github.com/department-of-veterans-affairs/content-build/blob/main/src/site/includes/header.html#L106

Actual link: https://github.com/department-of-veterans-affairs/content-build/blob/main/src/site/includes/header.html#L163

Note that the destination (`id="content"`) is part of individual page templates in content-build. 

```[tasklist]
### Implementation tasks
- [ ] Use this if it helps you or feel free to delete.
```

**Comment by tjheffner** [comment]
NextJS does not provide a skip-to-content link OOTB, that's fine. 

This link should be added to the wrapper component so it is above the navigation. the destination id should be added to the slug, imo
