### ISSUE TITLE
DUW: Logic flow

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#15532]
## User Story or Problem Statement
Create a logic flow (a la [Pact logic flow](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1692989444688/0044b9825c82d8d23920601f68c41a61d047d681?sender=u0b235d03cbd64f7f93673243)) of the DUW question flow

## Design

[Discharge Upgrade Wizard logic flow](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1696352911500/80253b1c7200212cbcbcfb940d2cf4a29fed8417?sender=u01810f3edbfc878c08be5925)

## Acceptance Criteria
- [x] A logic flow is created to map the question order and logic of the existing Discharge Upgrade Wizard
- [x] Flow is verified with outcomes from #15216 to make sure engineering is aligned

**Comment by thejordanwood** [comment]
End of sprint update:

I've created a Mural for the [Discharge Upgrade Wizard logic flow](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1696352911500/80253b1c7200212cbcbcfb940d2cf4a29fed8417?sender=u01810f3edbfc878c08be5925). This needs to be verified when the FE ticket is complete.
