### ISSUE TITLE
Report content release successes to Datadog.

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-cms#15539]
## Description

Followup from #13984 and #13985.

Content release successes do not appear to be reported to Datadog at this time.

This should be done in a separate task from the ones notifying CMS and Slack of success.

## Acceptance Criteria

- [ ] `content-build` content release workflow reports successes to Datadog
- [ ] Successes are reported in a separate task from other reportees

**Comment by teeshe** [comment]
I have added a task to content-release workflow so notification would be sent to Datadog every time there's a successful content-release. I would confirm on Datadog the notifications are coming in correctly.

**Comment by BerniXiongA6** [comment]
This is great to hear @teeshe -- with this ticket being one of our sprint goals, do you have any concerns about this work getting wrapped up soon?

**Comment by teeshe** [comment]
no concerns here @BerniXiongA6 this should be closed out soon.
The test passed [here](https://github.com/department-of-veterans-affairs/content-build/actions/runs/6566972118). also, notification was sent to Datadog.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN1pUQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--07be73595b88c2a1a9642a31cdd25bfe10c0df4c/image.png)
