### ISSUE TITLE
SPIKE: How to conduct research in a coded environment

### ISSUE THREAD

**Issue by davidmpickett** [department-of-veterans-affairs/va.gov-cms#15543]
Testing AutoSuggest field input is not feasible in a no-code prototype (Figma). What is the path forward for us to properly do usability testing on the Facility Locator `Search type` field?

VA Platform guidance on [Accessibility and Assistive Tech](https://depo-platform-documentation.scrollhelp.site/research-design/research-with-assistive-technology-users)

### Possibility 1 - Build something on staging.va.gov and test there
- **Pro:** No new tooling required
- **Con:** Feature flags / development time as blocker

Thread to follow:
- [Slack thread](https://dsva.slack.com/archives/C0216PL32HJ/p1696450953956489) 

While **type-ahead isn't the same as autosuggest**, they have similar needs from a usability research perspective, so some looking at type-ahead stuff may be helpful
-  This [research study](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/on-site-search/research/user-research/research-study-jan-2021/research-findings.md) that included type-ahead was conducted on Staging as opposed to a prototype. 
- The **Financial Status Report** is another product listed as using type-ahead search in the Experimental Design System Request. They also generally conduct [their research](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/combined_fsr/research/enhanced_fsr/research-findings.md) on staging
- **Charlotte Cesana** on Debt Resolution team is another Agile6 / Friends From the City contractor - could be a great person to chat with to learn more about how their team has set things up. @xiongjaneg connected @davidmpickett and @laflannery to her via DM and she said "Our target start date for the study is 10/18  We circulate an observer spreadsheet once sessions are scheduled. I'd be happy to share it with you when we're ready. "
 - [Type-ahead audit mural](https://app.mural.co/t/adhoccorporateworkspace2583/m/adhoccorporateworkspace2583/1643656901054/5ee29419d81a2191df3934d148d5e6804b92d1d3?sender=u9c899abc4fe36c9a698b1647)
- [Design system experimental design request](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/637) for type ahead search
- [Design system component](https://design.va.gov/components/search-input#with-type-ahead)
- [Slack thread](https://dsva.slack.com/archives/C8E985R32/p1602789990058600)

### Possibility 2 - Use a different tool like CodePen
- **Pro:** Would not have risk of seeping into va.gov before we're ready
- **Con:** Approval for research tooling can be blocker
- 526 team is spinning up a [new research study](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/research/CC-Team-Research/2023-10%20Conditions%20List/research-plan.md) in a few weeks for their version of the auto suggest component for "conditions list", prototype on CodePen, noting here as an example of prior research with taxonomy

## Acceptance Criteria
- [x] Accessibility and testing with Assistive Tech is explored and documented
- [x] Possibilities are explored and documented
- [x] Possibilities are discussed for technical feasibility with Engineering team members
- [x] Possibilities are discussed for timing and planning considerations with Product team members

**Comment by davidmpickett** [comment]
@aklausmeier and @laflannery to review async and consider points and timing

**Comment by aklausmeier** [comment]
@laflannery added accessibility/assistive tech considerations to ACs and link to Platform guidance for reference when we meet

**Comment by aklausmeier** [comment]
526 team is spinning up a [new research study](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/research/CC-Team-Research/2023-10%20Conditions%20List/research-plan.md) in a few weeks for their version of the auto suggest component for "conditions list", prototype on CodePen, noting here as an example of prior research with taxonomy

**Comment by laflannery** [comment]
Amanda and I started this and it is now pointed I want to make sure this gets into S95 - I will be in planning tomorrow so I can bring this up then as well

**Comment by jilladams** [comment]
Tagged accordingly - thanks for flagging!

**Comment by jilladams** [comment]
This could potentially also be relevant for Federal Header/Footer research, depending on where we land with research for screen reader users.

**Comment by laflannery** [comment]
[Mural for options](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1696863900971/fd3d8fa5eb58f2615d86c7a9a43d8676ef45736a?sender=u10a597890f85398daa3c4805)

**Comment by laflannery** [comment]
Next steps from Product meeting:
- Amanda and Laura to discuss with other teams how they decided on staging vs. Codepen prototyping
  - This is a more high level item and doesn't necessarily belong to a team but more an initiative, should we ticket this?
- Both Sitewide teams (PW & Facilities)
  - When planning research for future features/projects prototyping should be considered a bit differently:
    - Is accessibility testing what we are trying to achieve? If yes, we should be looking at an accessible prototype, either Staging or Codepen
    - From there, various considerations will need to be discussed to determine which would be better suited for a particular project
      - What is the deadline? Can i
      - Are we looking for low-fi or Hi-fi prototype? Codepen is probably going to be more lo-fi
      - What is the complexity of the project? Could it easily be created on Codepen?
      - What is it we are trying to get out of research? Is the VA.gov environment that staging provides going to be important?
- Codepen will require an account however Facilities most likely will not be going this route for their next project (Facility Locator). PW might need this for Header/Footer though. so it would be good to have the discussion sooner in case we need to get that set up first.
