### ISSUE TITLE
Content release failures should be reported to Datadog separately.

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-cms#15540]
## Description

These are currently reported in the same task as the CMS notification task. This means that this can be interrupted by a failure to successfully notify the CMS. These should be separated.

## Acceptance Criteria
- [x] Datadog is notified of content release failures separately from CMS and Slack.

**Comment by teeshe** [comment]
I have update the content-release workflow, isolated existing datadog failure notification to a setup of its own. 
Tested with breaking change to on branch to fail content-build and trigger failure notification
[https://github.com/department-of-veterans-affairs/content-build/actions/runs/6614918906/job/17967099012](https://github.com/department-of-veterans-affairs/content-build/actions/runs/6614918906/job/17967099012)
Notification was sent as expected on datdaog
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN1JoQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--228ebbc05d58c5bbdd1f8078390974acb89ee3f1/image.png)
