### ISSUE TITLE
UX Audit of CMS Datadog dashboard enhancements

### ISSUE THREAD

**Issue by BerniXiongA6** [department-of-veterans-affairs/va.gov-cms#15548]
## Problem Statement
CMS Team needs to have a UX audit of the current Datadog dashboard named "[CMS] Monthly Report" so that we can determine what improvements we can make to have the data tell a story for less technical audiences.

## What you need to know
- CMS Delivery Manager uses the CMS Monthly Report data from Datadog to share our monitoring tools and metrics with VA COR and account level individuals at Agile 6 and VA. 
- These dashboards are also used by CMS devs to monitor the performance metrics of the CMS.
- CMS Team would like to have more data and analytics to help inform our future work, which is helpful for Product, UX, and Engineering.
- The following screenshot is what the current state of our CMS Datadog "Monthly Report" dashboard looks like. 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeDBPQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2666b768b22b731431ee2c740d4ed1d24c9d9722/cms%20monthly%20report%20datadog%20screenshot%20for%20CMS%20UX%20research.png)

## Acceptance Criteria
- [x] Sync with Berni on monthly monitoring report has been completed 
- [x] Self-walkthrough of "CMS Monthly Report" Datadog dashboard has been completed
- [x] List of questions for Nate has been compiled
- [x] Audit finding have been compiled and linked up in this ticket

**Comment by BerniXiongA6** [comment]
@joagnitti -- tagging you to give a heads up that we can async pre-refine this until we have a chance to connect and chat about this. Would like to bring it in in Q4. Let us know if you have questions. Thanks!

**Comment by BerniXiongA6** [comment]
@EWashb @joagnitti why did I think we started on this work already but looks like we didn't? I think my brain is mush. Please advise?

**Comment by EWashb** [comment]
Nate has done a lot of work, I know, but I'll leave it up to the team to tell me. I don't know all the specifics but I know some work was done or is in process.

**Comment by BerniXiongA6** [comment]
I'll bring it back up in refinement this or next sprint to have @joagnitti and @ndouglas remind me where we're at on the UX audit side of things. Thanks @EWashb

**Comment by joagnitti** [comment]
@EWashb @BerniXiongA6 Here's my initial draft of a dream product/UX dashboard: https://docs.google.com/document/d/1kYtDUAPzZJEPhcOuu95ucVPARv--la09SX_IFMZPZ_M/edit
