### ISSUE TITLE
Migrate VAMC Facility Service appointment information into updated Service Location

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#15559]
## Description or Additional Context 
Implement the proposed path for migrating VAMC Facility Service appointment information into updated Service Location in #14837. This will align with appointment information location in VBA RO MVP.

[Figma file Service Location paragraph type](https://www.figma.com/file/aKdT4weNNthDxb3r6MolEh/VBA-Content-Specs?type=design&node-id=208-714&mode=design&t=LTvuLnielz6wFsoh-0)

## Acceptance Criteria
- [x] ~Post deploy hook~ Script run by drush moves current appointment information into the new appointment information on the Service Location paragraph
- [ ] ~Ticket(s) for future phone number label default are stubbed~ covered elsewhere
- [x] Ticket is stubbed for removing the old fields that contain the information currently https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17137
  - Fields that have the current data are cleared (e.g., Walkins accepted field for VAMC health service would likely need to move to Service Location)
  - Paragraphs that have the current data are removed

**Comment by xiongjaneg** [comment]
@xiongjaneg Consider plan B, a different service location paragraph type for VBA - more betterer, would require separate front end work for VBA (different) vs VAMC (existing), needs content modeling mapping

**Comment by xiongjaneg** [comment]
@xiongjaneg prioritize for next sprint

**Comment by xiongjaneg** [comment]
@xiongjaneg Will updating the front end query be part of this ticket or separate? Ask at pre-refinement.

**Comment by xiongjaneg** [comment]
@xiongjaneg stub out front end ticket, specifically the icons that need to be added

**Comment by xiongjaneg** [comment]
Helpful numbers for ballpark number of VAMC services that have more than 1 service location
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14758#issuecomment-1684321145

**Comment by swirtSJW** [comment]
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5752113/95e85a0d-3b51-4f36-9185-6b2b84b706f6)

**Comment by swirtSJW** [comment]
@jilladams  and @xiongjaneg I am making progress on this, but there is no way it is going to cross the finish line today (end of sprint).   I hope to have the migration working by the end of the day, but it needs more time for QA and verification before we can call it done.

**Comment by swirtSJW** [comment]
This is working 
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5752113/789e0540-358c-47c8-ba23-33d13c3e3b48)

but I need more time spot checking the audit

**Comment by swirtSJW** [comment]
The problem of extreme slowness (~ 6hrs to run) has been resolved by  https://www.drupal.org/project/post_api/issues/3418235
https://www.drupal.org/project/post_api/releases/2.0.5

However, the migration still takes over an hour to run on local.   Will have to monitor how fast it runs on tugboat.

My fear is that we will need to make this a human runnable script because the site is in deploy "shields up mode" during the running of this as a deploy hook.

My concern is that it needs to run as soon after deploy completes as humanly possible.  Will need to discuss.

**Comment by xiongjaneg** [comment]
This is a one time migration.

There is concern about editors seeing the fields and editing them before the migration runs.

This may require a feature flag.

**Comment by swirtSJW** [comment]
I converted this  from a deploy hook to a script so it can run by hand.
I also added the "Last edited by a human" field to the audit so that we can see which nodes were edited during the migration window.  ([related slack discussion](https://dsva.slack.com/archives/C0FQSS30V/p1706740645691209))

**Comment by omahane** [comment]
@davidmpickett Not a part of this ticket necessarily, but do editors know what the expectation is for Virtual Support? Any time they edit a VAMC Facility Health Service or Non-clinical Service, they will be required to choose some option.

**Comment by davidmpickett** [comment]
> @davidmpickett Not a part of this ticket necessarily, but do editors know what the expectation is for Virtual Support? Any time they edit a VAMC Facility Health Service or Non-clinical Service, they will be required to choose some option.

Definitely a topic that for #14758. Not sure what @xiongjaneg & @mmiddaugh have been cooking up with VHADM in regards to communicating this

**Comment by xiongjaneg** [comment]
Will add to next VHA DM sync

**Comment by swirtSJW** [comment]
This has been merged to integration so can be considered done.

**Comment by swirtSJW** [comment]
I am not really sure what "Ticket(s) for future phone number label default are stubbed"  maybe @omahane or @davidmpickett remembers what this refers to?

**Comment by davidmpickett** [comment]
> I am not really sure what "Ticket(s) for future phone number label default are stubbed" maybe @omahane or @davidmpickett remembers what this refers to?

That sounds like the work @omahane has done in #16348 to split the the default description for Appointment Phone numbers into multiple parts. This ticket was created a couple months before that one existed, so that AC was likely just never removed.

**Comment by jilladams** [comment]
Integration branch: https://github.com/department-of-veterans-affairs/va.gov-cms/tree/integration-service-location
