### ISSUE TITLE
Content Build updated to support changed Breadcrumb data

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#15565]
## Requirements

```[tasklist]
### Acceptance criteria
- [ ] Any content build template that makes use of breadcrumb data is verified to output unchanged
```

## Background & implementation details

```[tasklist]
### Implementation tasks
- [ ] Use this if it helps you or feel free to delete.
```

**Comment by schiavo** [comment]
**Broken pages**

On event the see more event link towards the bottom of the page is broken
image

**Comment by schiavo** [comment]
Testing against latest PR

Templates for the following were updated

faq_multiple_q_a
(breadcrumbs match)

![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/7717261/ec8084fb-9db0-4c19-9e7b-a31dedd39820)

q_a
(breadcrumbs match)

![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/7717261/ccd41469-88fa-44fe-a23b-02ed8df05a19)

**Comment by schiavo** [comment]
Testing the rest of the content types

Running comparison of current production breadcrumbs against [Content Build PR ](https://github.com/department-of-veterans-affairs/content-build/pull/1744)and [CMS PR](https://github.com/department-of-veterans-affairs/va.gov-cms/pull/15572) 

**First check by content type**
basic_landing_page

event

event_listing

faq_multiple_q_a
(tested above - breadcrumbs match)

health_care_local_facility (VAMC Facility)

health_care_region_detail_page (VAMC Detail Page)

health_care_region_page (VAMC System)
(breadcrumbs match)

health_services_listing

landing_page (Benefits Hub Landing Page)

leadership_listing (VAMC System Locations List )

locations_listing

news_story (Story)

page (Benefits Landing Page)

person_profile (Staff Profile)

press_release

press_releases_listing

promo_banner

publication_listing
(breadcrumbs match)

q_a (Reusable Q&A )
(tested above - breadcrumbs match)

service_region
(not in use - 1 draft node)

step_by_step
(tested above - breadcrumbs match)

story_listing (Stories List)
(breadcrumbs match)

support_resources_detail_page (Resources and Support Detail Page )
(tested above - breadcrumbs match)

support_service
(not rendered as page)

vamc_operating_status_and_alerts (VAMC System Operating Status)
(breadcrumbs match)

vamc_system_billing_insurance

vamc_system_medical_records_offi (VAMC System Medical Records Office )\
(breadcrumbs match)

vamc_system_policies_page
(breadcrumbs match)

vamc_system_register_for_care
(breadcrumbs match)

va_form 

vamc_facility (VAMC Facility)

vba_facility
(not in use - all set to draft)

vba_facility_service
(not in use - no nodes)

vet_center

vet_center_locations_list (Vet Center - Locations List )

video_list
(not in use - 2 nodes as draft)
