### ISSUE TITLE
Top task links on About [VAMC System] pages are removed from Programs pages

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#15567]
## User Story or Problem Statement
There seems to be some inconsistent logic in which VAMC pages display Top task links. Following the sub nav:

SERVICES AND LOCATIONS
System page :white_check_mark:
Health services :white_check_mark:
Locations :white_check_mark:
Individual facility pages :white_check_mark:
It makes sense that all these pages show the top task links

NEWS AND EVENTS
Events :x:
News releases :x:
Stories :x:
It makes sense that all these pages don't show the top task links

ABOUT [VAMC SYSTEM]
About us :x:
Work with us :x:
Contact us :white_check_mark: (this makes sense as an exception)
Programs :white_check_mark: (not sure that this always makes sense)
Research :x:
Policies :x:

Examples of Program pages (VAMC Detail pages) that might be misleading because they show top task links
https://www.va.gov/pittsburgh-health-care/programs/vsovba-representatives/
https://www.va.gov/chicago-health-care/programs/intimate-partner-violence-assistance-program/intimate-partner-violence-assistance-program/
https://www.va.gov/oklahoma-city-health-care/programs/
https://www.va.gov/northern-california-health-care/programs/stockton-sonora-and-modesto-shuttle/

These links have always been on the Program pages, but the change to action links has made them much more prominent and potentially confusing.

Refer to [Slack thread](https://dsva.slack.com/archives/C0FQSS30V/p1696463498455599) for comments

## Acceptance Criteria
- [x] Top task links are removed from Programs pages on all VAMC Systems, including Lovell VA and Lovell Tricare.
- [x] Regression test is done.
- [x] Design review (tag Jordan for PR review)

**Comment by mmiddaugh** [comment]
Support removing the top task links from Programs pages but retaining them for Contact us page

**Comment by jilladams** [comment]
From mid-sprint: since we removed all links below News and Events header, we are also removing that header.

**Comment by maxx1128** [comment]
End of Spring 106 update: the pull request for this ticket has been merged and is just waiting on production review/confirmation.

**Comment by jilladams** [comment]
Verified in prod, closing.
