### ISSUE TITLE
Merge Mental Health phone number integration branch to main

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#15576]
## description
All of the of the Mental health phone number CMS work in this epic will be PRs against the integration branch `integration-mental-health-phone` since it can not go directly to main.

## Notes
We don't currently have a Lighthouse data push-specific ticket, so that work should be included in the estimate here. 
([LH trello card](https://trello.com/c/x8YdixQ6/6-mental-health-phone-numbers)

## Acceptance criteria
- [x] Lighthouse / Drupal eng have verified that Mental health numbers are pushed / received correctly 
- [x] [Integration branch PR](https://github.com/department-of-veterans-affairs/va.gov-cms/pull/15585)  is merged to main
- [ ] Features are verified live in production
- [ ] I expect the content model documentation is updated to show that the `field_mental_health_phone` is both a push and a pull 
- [ ] I expect the content model documentation is updated to show that the `field_mental_health_contact_phon` is a push, and is short lived and expected to be removed in the final phase of this.

**Comment by xiongjaneg** [comment]
per 10/23 meeting, potentially early December for LH timeline

**Comment by mmiddaugh** [comment]
Per email from VHA DM, we will wait to merge until LH is ready

**Comment by jilladams** [comment]
Per Lighthouse, they'll be shipping their change to be ready for this today, Tues Jan 16, 2024.

**Comment by swirtSJW** [comment]
This has been merged.  I am blocked from completing the last three AC's. 
1. the code has not made it to prod yet
2. I can not update the content model documentation because those are currently [un-editable due to a alt text validation bug](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16827).

**Comment by jilladams** [comment]
https://dsva.slack.com/archives/C0FQSS30V/p1705525403105529

https://dsva.slack.com/archives/C02BTJTDFTN/p1705527249944789?thread_ts=1705525913.774379&cid=C02BTJTDFTN

Closing!
