### ISSUE TITLE
EPIC: VBA Regional Offices Pilot MVP - User Training / Onboarding

### ISSUE THREAD

**Issue by davidmpickett** [department-of-veterans-affairs/va.gov-cms#15573]
### User Story or Problem Statement

As a VBA editor participating in the regional office MVP, I need self-service materials to help me learn how to Drupal, so I can update information about my office(s) and related services.

**Comment by xiongjaneg** [comment]
closing epic, moving tickets to Pilot MVP initiative for better tracking
