### ISSUE TITLE
Update CMS Announcements page to include Drupal 10 updates

### ISSUE THREAD

**Issue by BerniXiongA6** [department-of-veterans-affairs/va.gov-cms#15579]
## Problem Statement
The CMS Team needs to have a method for communicating CMS updates and announcements to content editors so that they can be aware of changes to the editorial experience.

## What you need to know
- CMS Team will repurpose this page to announce D10 updates: https://prod.cms.va.gov/help/cms-announcements
- Background info on what prompted this work can be found on ticket #15154
- This was previously an actively updated product in the CMS for updates, outages, and things editors need to know

## Acceptance Criteria
- [x] sync with Product and UX has been completed to kickoff this ticket
- [x] page has been edited to include updates from D9 to D10 
- [x] content has been written for the editor audience
- [x] content adheres to VA content style guidelines
- [x] page is publish-ready before Drupal 10 launch
- [x] page updates have been reviewed and approved by PO

**Comment by EWashb** [comment]
After page is publish-ready, we should inform our stakeholders and partner teams.

In the future, we should include updating this page in our change management activities. Also, we might want to consider having "update announcements page" as a part of our regular QA process and create guidance around when teams should use it. I don't want the page to go stale like it did before, and I'm very excited we have this back in our rollout plans!

**Comment by BerniXiongA6** [comment]
Love the ideas @EWashb -- will make sure to create a new "update announcements page" every sprint or two. Thanks!

**Comment by EWashb** [comment]
@BlakeOrgan I was just looking at the announcements page, and I was curious if you plan on keeping that same emoji image situation in your design plan for announcements

**Comment by BlakeOrgan** [comment]
@EWashb I'm open to keeping it or getting rid of it. If we kept it, I think there needs to be some kind of key/structure for what the different emojis indicate.

**Comment by EWashb** [comment]
I agree @BlakeOrgan I'm ok with either, honestly. What would be the more appropriate solution for accessibility compliance, though?

**Comment by laflannery** [comment]
I have 2 requests for edits:
1. `Changes to the "Styles" dropdown to include primary and secondary action text styles.`
   - Can we change this to 
   
> Limited options in the "Styles" dropdown to align with content guidelines 

2. Can we remove everything below "Have questions?..." I feel like all of this is quite old and not super relevant to editors anymore?

**Comment by BerniXiongA6** [comment]
@BlakeOrgan I was thinking the same thing as @laflannery too about bullet 2, but then I also thought about where/how/when we archive old announcements? What's a good process for this (archiving old info) since we're using a KB article as opposed to a web page to make our CMS announcements? cc: @EWashb

**Comment by BlakeOrgan** [comment]
@laflannery @BerniXiongA6 
I made that update the the Styles bullet and I totally agree. Maybe we can section out the announcements by year using the the collapsable accordion group component. That way we can retain previous announcements, but only the most recent are displayed and all others must be expanded.

**Comment by BerniXiongA6** [comment]
I like that idea @BlakeOrgan -- hope it's not too complicated to add that to the scope of this ticket? cc: @EWashb

**Comment by BlakeOrgan** [comment]
@laflannery @BerniXiongA6 

Okay, I copied all of the previous announcements and pasted them into an accordion group for the year that they were posted if y'all want to take a look at the [updated draft state](https://prod.cms.va.gov/node/6900/latest). You'll still see the long list of announcements below the accordion groups right now because I wanted to keep them there in case the accordion group isn't the direction we want to go. The only downside to using accordion groups is that they don't allow for images (unless I'm missing something).

While I think the accordion group is a good way to solve for hiding the outdated content in the short term, I think there are better ways that we can handle this announcements page that we can iterate on in future sprints.

Let me know if y'all think the accordions work and I can get rid of the long list below the accordions.

**Comment by laflannery** [comment]
I think this works for what we are looking to do in the short term. I did go in and fix the heading structure so it worked when inside the accordions.

In the long term, I still do question if we even need to keep some of this content at all. For example, Planned CMS downtime from a Tuesday in 2020 - that doesn't seem like it would make sense on a page like this in general - it's information editors need at the time it's happening but once it's over, it's over (if that makes sense?).

I also have some engineering updates I need make to the accordions to make these more accessible, and in doing that we could evaluate what you brought up Blake that the image field isn't allowed here, so we could make some overall improvements like that to make these a bit better for various use cases longer term.

**Comment by BlakeOrgan** [comment]
Sounds good! I removed all the old announcements that are now housed in the accordion dropdown, so I'm gonna call this ticket complete.
