### ISSUE TITLE
[Events] Breadcrumbs vary between Event Listing and Event pages

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#15584]
## Status
**[2024-04-25]** Will be addressed in an overall breadcrumb effort, or in the imposter component work.

## Description 

Breadcrumbs vary between Event Listing and Event pages. Breadcrumbs should be consistent, at least at the healthcare center level, between these pages: 

https://www.va.gov/eastern-colorado-health-care/events/
Listing breadcrumb: [VA Eastern Colorado health care](https://www.va.gov/eastern-colorado-health-care)
Event breadcrumb: [Eastern colorado health care](https://www.va.gov/eastern-colorado-health-care)
<details>

![Screenshot 2023-10-06 at 12 54 01 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/85581471/652dfecf-4c4f-42e9-b4ad-2779c4deec55)

</details>

https://www.va.gov/minneapolis-health-care/events/?selectedOption=past
Listing breadcrumb: [VA Minneapolis health care](https://www.va.gov/minneapolis-health-care)
Event breadcrumb: [Minneapolis health care](https://www.va.gov/minneapolis-health-care)
<details>

![Screenshot 2023-10-06 at 12 53 12 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/85581471/e983193d-925a-4d2f-a797-c9bad58c90ed)

</details>

## Acceptance Criteria
- [ ] The breadcrumb for an Event page matches the Event detail page up to Event title

**Comment by FranECross** [comment]
Will be addressed in an overall breadcrumb effort, or in the imposter component work. Closing as a no-op

**Comment by jilladams** [comment]
( @FranECross we'll need to verify this after the DS breadcrumb work. )
