### ISSUE TITLE
VA Design System & vets-website components should be visible in Storybook

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#15625]
## Requirements

Next Build components that incorporate either vets-website components or VA Design System components should function and display correctly in Storybook, so that developers and others can readily see these components and how they function.

```[tasklist]
### Acceptance criteria
- [ ] Next Build components that incorporate VADS or vets-website components should display and function correctly in Storybook
- [ ] Web component scripts are loaded in Storybook preview.js
```

## Background & implementation details

```[tasklist]
### Implementation tasks
- [ ] Use this if it helps you or feel free to delete.
```

**Comment by tjheffner** [comment]
Web components from the design system work properly in storybook. The widgets from vets-website that depend on data being attached to the window object don't play as nicely with the order that storybook loads scripts. I have opened a bug ticket in the Storybook repo and will update in a later PR.
