### ISSUE TITLE
Finalize a plan (& implement?) it re: free text fields in Service Location paragraph type for VBA

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#15649]
## User Story or Problem Statement
2 free text fields spec'ed for Service Location. 
Is this the right approach, given the possibility for inconsistency in the way Service Locations are described by a single or multiple editors? 

Concerns around adding / maintaining those: 
* Service Locations writ large - VAMC implicated

## Description or Additional Context 
Follow on to #14704 .

- VBA Content Specs XLS listed in https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13096
- [recent design](https://www.sketch.com/s/891d33ae-152d-471c-ab5d-9aedf89cf6ff/p/578C3207-C5A3-4303-AB18-4AFC27AC54D2/canvas)

## Acceptance Criteria
- [x] Coordinate with PO and PM & Content strategy to finalize a plan
  - [x] If plan is reasonably sized, implement
    - [x] Link to view implementation is shared with Laura for accessibility audit in ticket https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14893
  - [ ] If not, cut a new ticket

**Comment by jilladams** [comment]
Dave / Christian to help schedule.

**Comment by davidmpickett** [comment]
Meeting to discuss scheduled for 10/13 by @omahane

**Comment by jilladams** [comment]
Meeting with Christian, Dave, Michelle, Swirt & me: 
* Tugboat: https://pr15622-xptmfsnjoodldn85nzgkrgljqtfbz24b.ci.cms.va.gov/node/add/vba_facility_service
* Sketch: https://www.sketch.com/s/891d33ae-152d-471c-ab5d-9aedf89cf6ff/p/578C3207-C5A3-4303-AB18-4AFC27AC54D2/canvas#About

### **Challenge:** 
* Each new service location will become available to VAMCs as well
  * If we add Task-oriented descriptive header & Service Location Description to Service Locations, that data will be required to be entered for _each_ Service Location (across facillity types)
  * Those fields are scoped as Text input fields without much validation. The opportunity to write weird stuff that is inconsistent across Service Locations is high. 
* We agree this is probably a bad idea

![Screenshot 2023-10-13 at 8 12 23 AM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/85581471/a2205a60-8466-404c-b622-6125fdaa66b9)

### **To solve?** 
* Description headers need to be programmatically generated for consistency, specific to the Service. (e.g. "Get help applying for or managing [Service name]. " And maybe the Service location description is standardized
  * QUESTIONS: 
    * "Service Location Description" will not be one-size fits all Service types / service locations. Who owns that content (Sitewide Content? VBA National?) and where / how can it be managed to make sure the right task descriptions line up with the Service / Service location?
      * Could encode that at the Service Region level.
      * Needs to line up with the service modality as well (call, walk in, appointment, etc)
    * VAMC System Health Service includes a Service Description field that sort of acts this way and we could follow the model, maybe
      * We believe the task description will be the same across services, regardless of Service Region.
      * So: Could put it on the VA Services taxonomy term as a VBA field. 
        * If we do this, we need to break the Location off the end of the Description into a "Public Contact Office"-like treatment 

e.g. go from this: 
![Screenshot 2023-10-13 at 8 41 48 AM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/85581471/e80f981f-6b50-443b-b898-a23e60ad2f38)

to more like this:
![Screenshot 2023-10-13 at 8 45 20 AM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/85581471/2ba2799e-e476-46da-96d4-75c347c0cf8c)


TO DO: 
* Drupalize "Task-oriented descriptive heade" & "Service Location Description" to VA Services taxonomy, as VBA specific fields. 
  * Remove from Service Location
  * Need these new fields: 
    * Regional Service header
    * Regional Service description
    * Facility Service header
    * Facility Service description
* Update design?

**Comment by swirtSJW** [comment]
This has been merged.

**Comment by omahane** [comment]
This has been completed with a link added in the accessibility review ticket.

**Comment by jilladams** [comment]
Closing based on notes and sprint planning convo.
