### ISSUE TITLE
Nat'l Cal CM: Revise training materials for Events

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#15652]
### User story

**AS AN** Editor
**I WANT** Event training materials to be updated for the new functionality (e.g. checkbox for Outreach Events event list)
**SO THAT** I can follow them.

### Engineering notes / background

(This ticket spun off from #13533.)

## Acceptance criteria

>Consider
> - Design / Accessibility reviews
> - Collab cycle requirements
> - Device sizes (mobile first)
> - Documentation updates / Change management
< - [Content model documentation](https://prod.cms.va.gov/admin/structure/cm_document)
> - Testing notes

- [ ] Updated materials and video

**Comment by jilladams** [comment]
duped by #13533
