### ISSUE TITLE
Update designs for facilities with complex names

### ISSUE THREAD

**Issue by davidmpickett** [department-of-veterans-affairs/va.gov-cms#15660]
## User Story or Problem Statement
Facilities sometimes have multiple name or multi-part names. Right now, this complexity is only displayed on the facilities' main page, and not in the other places it is listed across VA.gov.

We need to ensure that facility names are consistently displayed across VA.gov

### Design
[Vet Center Sketch file](https://www.sketch.com/s/83e13c18-5a9f-40ed-860f-61b9ead58bd6)

### Vet Center example
**Official name:** Dr. Cameron McKinley Department of Veterans Affairs Veterans Center
**Short name**: [Prescott Vet Center](https://www.va.gov/prescott-vet-center/)
**H1-associated text:** Also called the Dr. Cameron McKinley Department of Veterans Affairs Veterans Center

### VBA examples
See [VBA IA ticket for more context](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15490)
**Official name:** Salt Lake City VA Regional Benefit Office at George E. Wahlen Department of Veterans Affairs Medical Center
**Short name (h1):** - Salt Lake City Regional Office
**Shared location (h1-associated text)** - at George E. Wahlen Department of Veterans Affairs Medical Center

### Vet Center main page
![Screenshot 2023-10-12 093823](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/476acefb-550e-43f3-9c6e-dfe25fce65be)

### Vet Center Locations Page
![Screenshot 2023-10-12 093841](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/92837ccb-2084-4dbc-b112-bbaee0a063bd)

### Other nearby facilities lists
![Screenshot 2023-10-12 095741](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/49675a06-930b-4320-83a7-5aa7e8fc6be0)

### Facility locator results page
![Screenshot 2023-10-12 093807](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/aedd929f-7cad-40b8-8d3a-0fec30b37206)

### VA.gov Search results
![Screenshot 2023-10-12 094511](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/99f1c6cf-ae07-4add-9ef2-5a9c31bb140f)

### Google search results 
![Screenshot 2023-10-12 100741](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/24ef6154-e6a0-4ab8-9f95-ed6a9f56ad33)

## Acceptance Criteria
- [x] Facilities designs in Sketch are updated to show expected behavior for facilities
- [x] Review with Amanda K. 
- [x] Review with a11y
- [x] Review scheduled for next UX sync

## Team
Please check the team(s) that will do this work.

- [ ] CMS Team
- [ ] Public Websites
- [x] Facilities
- [ ] Accelerated Publishing

**Comment by davidmpickett** [comment]
@jilladams @xiongjaneg Candidate for sprint 96 based on UX refinement

**Comment by xiongjaneg** [comment]
@thejordanwood Would you please review and update the description and ACs as needed? If you have enough info, would you also please estimate points (in case this is ready for next sprint)? If you want to meet to discuss this, please let me know. Thank you!

**Comment by thejordanwood** [comment]
@davidmpickett To double check that I'm clear on this: 

1. We want to primarily display the short names on main facility pages, locations pages, Other nearby facilities lists, the Facility locator results page, and search results. 
2. We want to show the official names as h1-associated text on main facility pages, like in the Prescott Vet Center example. Is that the only place we need to show the official name?

**Comment by davidmpickett** [comment]
@thejordanwood The expected behaviors for Vet Centers are spelled out fully in the [parent epic](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15415) but essentially, all instances should show both names. 

> When a Vet Center with both an official and common name is included as a nearby location for another Vet Center, or in Facility Locator search results, both the official and common name are displayed.

**Comment by davidmpickett** [comment]
@thejordanwood @xiongjaneg This seems pretty refined now, thoughts about moving to Ready? Or do we want to review in UX Sync tomorrow?

**Comment by xiongjaneg** [comment]
@davidmpickett I'm OK to move to Ready if @thejordanwood is.

**Comment by thejordanwood** [comment]
@davidmpickett @xiongjaneg This has been moved to Ready!

**Comment by aklausmeier** [comment]
@thejordanwood reviewed, looks good, checked off AC for my review

**Comment by thejordanwood** [comment]
Last week, I created mockups [in this Sketch file](https://sketch.com/s/83e13c18-5a9f-40ed-860f-61b9ead58bd6) to show how facilities can display complex names consistently across the site.

I started [a slack thread](https://dsva.slack.com/archives/C0FQSS30V/p1700173013147379) to get feedback.

**Comment by xiongjaneg** [comment]
review schedule for 11/30 UX sync
