### ISSUE TITLE
Swap mental health phone fields when editorial cut-over is complete

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#15686]
## User Story or Problem Statement
At whatever point we decide that the editor cutover is complete (100% population of field_mental_health_contact_phon ?) we will need to swap out the temporary storage editor field with the API populated field_mental_health_phone.

This swap will result in there being only one source of truth for mental health phone numbers AND no FE changes required.

## ACs
- [x] Remove field `field_mental_health_contact_phon` from the VAMC Facility content type.
- [x] Move field  `field_mental_health_phone` from the api locked section to the editable region where `field_mental_health_contact_phon` used to live.  
- [x] Add the help text from the former field to `field_mental_health_phone`
- [x] Remove the check for `field_mental_health_contact_phon` from PostFacilityStatus->getFacilityMentalHealthPhone().   (The code will function fine with just the removal of the field from the node, but should be removed from getFacilityMentalHealthPhone() to avoid leaving mysteries behind.
- [x] Remove field_mental_health_phone from the VAMC Facility migtation.
- [x] Updated Content Model Documentation for these fields.

## Team
Please check the team(s) that will do this work.

- [ ] CMS Team
- [ ] Public Websites
- [x] Facilities
- [ ] Accelerated Publishing

**Comment by mmiddaugh** [comment]
@swirtSJW does it make sense to make the field required during this swap or should that be a separate effort?

**Comment by mmiddaugh** [comment]
Mental health cutover will be defined by PAO editor deadline, rather than by a % of populated fields, FYI

**Comment by mmiddaugh** [comment]
@xiongjaneg @jilladams VHA DM indicated editors will have two weeks once the tasker is sent out - this issue may need to be in Sprint 103

**Comment by xiongjaneg** [comment]
Justin sent the tasker to editors Jan. 29 with a deadline of Feb. 8, potential postponement to Feb. 15 if needed

**Comment by xiongjaneg** [comment]
If we do this right away, we won't be able to audit subsequent changes made by editors.

The VHA DM tasker says that no action is needed if the number is correct, so that may affect the audit.

Don't roll out on Friday because of bigger window of wonkiness.

**Comment by jilladams** [comment]
Should wait til late in Sprint 103 to do this (til after the VHA DM target 2/8 date for Editors to complete work, which may get extended to 2/15).  Safe to roll over sprint boundary if it doesn't fit into 103.

**Comment by jilladams** [comment]
https://trello.com/c/lvqPRuCI/33-mental-health-phone-numbers-1-6
2/13 update: 
> Four VISNs have confirmed their number. Extension is Thurs Feb. 15.

This will wait to merge / close til VHA DM provides sign off.

**Comment by xiongjaneg** [comment]
@omahane VHA DM has heard back from all VISNs and is considering editorial cut-over complete.

**Comment by omahane** [comment]
Documentation has been updated here: https://prod.cms.va.gov/admin/structure/types/manage/health_care_local_facility/fields/node.health_care_local_facility.field_mental_health_phone/document

This can now be closed.

**Comment by xiongjaneg** [comment]
Reviewed documentation. Closing as completed.
