### ISSUE TITLE
Review of new or updated KB article: How to add or edit a VAMC facility mental health phone number

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-cms#15683]
## Which article(s) need review?
Provide the link to latest revision of each article that requires review.
- New article [How to add or edit a VAMC facility mental health phone number](https://prod.cms.va.gov/help/vamc/how-to-add-or-edit-a-vamc-facility-mental-health-phone-number)
- **When the new article is published**, the existing ["Updating basic facility data"](https://prod.cms.va.gov/help/vamc/how-do-i-update-my-vamc-facilitys-basic-location-data) article needs to be updated by removing the Mental Health Phone Number row from the table. 

  
  
## Priority or deadline for request
Choose either Deadline or a priority:

- [ ] Deadline: [name the deadline here]
- [ ] Priority:
  - [ ] Critical
  - [x] High - this request to support forthcoming high priority changes
  - [ ] Medium
  - [ ] Low

## Can article(s) be published?
Once the article has been fully reviewed, can the article(s) be published? For example, is anything tied directly to an upcoming feature and this information should not be published until the feature is on production?
- [ ] Yes, all article(s)s within this ticket can be published once reviewed
- [x] No, the article(s) within this ticket should not be published and should only be reviewed - we need to coordinate timing with VHA communications and code changes
  
## Notify the CMS team of this ticket in the cms-support Slack channel.
- [x] I acknowledge that I must notify #cms-support after submitting this issue.

## Acceptance Criteria
- [x] Article reviewed by CMS Team
- [ ] Requesting person/team has been notified that article was reviewed

**Comment by mmiddaugh** [comment]
Blocked by 

- Changes to existing field field_mental_health_phone on VAMC facilities #14213
- Push mental health phone number field to lighthouse with the status push #14215

**Comment by mmiddaugh** [comment]
@xiongjaneg this is ready for your review and then we can send the text to VHA DM for their review and approval

**Comment by xiongjaneg** [comment]
@mmiddaugh Reviewed and fixed anchor links. One question on whether both numbered lists at the bottom are needed. Thanks!

**Comment by xiongjaneg** [comment]
emailed to VHA Digital Media for review and comment

**Comment by xiongjaneg** [comment]
@BerniXiongA6 This KB article is submitted for CMS review intake. Thank you.

**Comment by BerniXiongA6** [comment]
Thanks @xiongjaneg -- will bring into Sprint 96 next week.

**Comment by BerniXiongA6** [comment]
Hey @xiongjaneg -- the content that was last updated on Oct. 19th, 2023 has been reviewed and looks good. Please proceed with your coordination of publishing timing with VHA communications and code changes. I'm closing this ticket to indicate that CMS has reviewed the article.
