### ISSUE TITLE
FE: Remove references to FEATURE_MOBILE_APP_PROMO

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#15694]
## Description 
In #15079 we want to deprecate the FEATURE_MOBILE_APP_PROMO feature toggle from CMS, but first need to remove FE references in  [liquid.js](https://github.com/department-of-veterans-affairs/content-build/blob/3f693d41da6310ae64e1234b6e712e41829e6829/src/site/filters/liquid.js) (in content-build):

```js
  liquid.filters.shouldShowiOSBanner = currentPath => {
    const urlsForBanner = [
      '/health-care/refill-track-prescriptions',
      '/health-care/secure-messaging',
      '/health-care/get-medical-records',
      '/disability/view-disability-rating',
      '/claim-or-appeal-status',
      '/disability/upload-supporting-evidence',
      '/records/download-va-letters',
      '/va-payment-history',
      '/change-direct-deposit',
    ];

    return (
      cmsFeatureFlags.FEATURE_MOBILE_APP_PROMO &&
      urlsForBanner.includes(currentPath)
    );
  };
```

## Acceptance Criteria
- [x] FEATURE_MOBILE_APP_PROMO references are removed from FE code
- [x] After merge, a comment is added to #15079 to let CMS eng know that ticket is unblocked

**Comment by chriskim2311** [comment]
PR for FE removal has been merged. Comment has been made in the CMS ticket to alert Christia.
