### ISSUE TITLE
Update existing KB article : VA Health Connect phone number change requests 

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-cms#15692]
## Background context
**What is the request for?**
- [ ] Create new article
  - [ ] I have reviewed the Knowledge Base to confirm that an article for this topic does not already exist
- [x] Update existing article: [VA Health Connect phone number change requests](https://prod.cms.va.gov/va-health-connect-phone-number-change-requests)
- [x] Update existing article: [How do I update my VAMC Facility's Basic Location Data?](https://prod.cms.va.gov/help/vamc/how-do-i-update-my-vamc-facilitys-basic-location-data)
      - [(see comment below)](https://app.zenhub.com/workspaces/sitewide-facilities-639f5253e4b702a32376339e/issues/gh/department-of-veterans-affairs/va.gov-cms/15692#issuecomment-1764982768)

**Audience**
Who is this intended for? Who would need this information? (i.e. All editors, only editors for a particular product, Internal use only, etc.)
- VAMC editors and CMS support
**Other related KB articles, if applicable:**
- [If you know that related KB articles already exist, link them here]

## Is the article associated with an ongoing product or feature update?
- [ ] Yes [Link to relevant Github ticket](URL)
- [x] No - related to a change in process

  
## Priority or deadline for request
Choose either Deadline or a priority:

- [ ] Deadline: [name the deadline here]
- [ ] Priority:
  - [ ] Critical - Without this, there is a large negative impact on the majority of editors causing negative consequences within the CMS; Should be completed as soon as possible
  - [ ] High - Without this, there is negative impact on some editors causing negative consequences within the CMS; should be completed within the current sprint
  - [ ] Medium - Without this, there is confusion for editors but not causing negative consequences within the CMS; Should be completed within the next 1-2 sprints
  - [x] Low - This is not currently causing confusion for many editors but would be a nice to have or is something that may be more impactful in the future; Should be completed within the next 3-4 sprints

## Acceptance Criteria
- [x] Article is created/updated using [KB content style guidelines](https://va-gov.atlassian.net/wiki/spaces/VAGOV/pages/1771831299/Knowledge+Base+content+style) and saved as ~~a draft~~ Published per stakeholder approval
- [ ] Impacts on other KB articles have been considered and any necessary changes have been made and saved as draft
- [ ] If necessary, add link to the new KB article in the [Content model document](https://prod.cms.va.gov/admin/structure/cm_document) for that content type 
- [x] [Ticket for article review](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/new?assignees=&labels=Knowledge+Base%2C+Needs+refining&template=knowledge-base-article-review.md&title=Review+of+new+or+updated+KB+article+%3A+%3Cinsert+topic+here%3E) has been created

**Comment by mmiddaugh** [comment]
When VHA DM has approved the changes to the `VA Health Connect phone number change requests` article and other reviews are complete, we should add the following row (or similar) to the `How do I update my VAMC Facility's Basic Location Data? `article. 

| Facility Information | How to update|
|---|---|
| VA Health Connect phone number | VISN PAO should contact VHA DM. See [VA health connect article](https://prod.cms.va.gov/va-health-connect-phone-number-change-requests) for details. |

**Comment by xiongjaneg** [comment]
@BerniXiongA6 submitting to CMS Team for KB article review intake

**Comment by BerniXiongA6** [comment]
Thanks @xiongjaneg -- brining this into Sprint 96 next week.

**Comment by xiongjaneg** [comment]
Published per stakeholder approval, CMS Team may edit and publish as needed after review

**Comment by BerniXiongA6** [comment]
@xiongjaneg Sounds good, thanks for helping us move this one along!

**Comment by BerniXiongA6** [comment]
Reviewed updated article that was published on 11/29/2023 for VA Health Connect Phone Numbers change request -- that one is approved and no further action is required.

Reviewed updated article that was published on 11/29/2023 for [updating VAMC Facility's basic location data](https://prod.cms.va.gov/help/vamc/how-do-i-update-my-vamc-facilitys-basic-location-data) -- I found a couple of errors if you could resolve them when you have a chance:

1. There's a quotation mark missing at the start of the first sentence underneath the Veteran-centered purpose section.
2. There are a couple of broken links (see screenshot)
<img width="1792" alt="Screenshot 2023-12-08 at 3 32 27 PM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/85254824/c37d4f65-1f82-4b5f-a369-83568c71ec28">


 cc: @maortiz-27-80

**Comment by jilladams** [comment]
* Fixed the quotation marks
* The [Submit Request through VAST portal](https://dvagov.sharepoint.com/sites/VHAPlanning/VAST/Pages/default.aspx) link works if you're on VA network. Account access may be why the link checker is calling it broken?
* Assigned Roles within the VAST Validation Report - https://reports.vssc.med.va.gov/ReportServer/Pages/ReportViewer.aspx?%2FApps%2FVAST%2FPROD%2FAssigned_Roles_within_the_VAST_Validation_Report=&rs%3ACommand=Render -- this URL throws a DNS error, we'll need to figure out what that URL is supposed to be.

**Comment by jilladams** [comment]
Could folks assigned here let me know if there are any additional things we need to do to close this one out?

**Comment by BerniXiongA6** [comment]
@jilladams -- I can review your updated edits, and then I'll close out with my comments this sprint, thanks -- cc: @maortiz-27-80 @xiongjaneg

**Comment by xiongjaneg** [comment]
ok to close per Berni
