### ISSUE TITLE
UX Discovery: Health chat link on VAMC pages

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#15704]
## User Story or Problem Statement
As a Veteran, I want to get access to same day care through timely communication methods.

## Background
The Facilities team did discovery into the multiple methods of contacting the VA to Veterans in the summer of 2021. At the time, the methods included the usual suspects (phone, mental health numbers and the VCL) plus VA health chat, Secure messaging, and VA health connect. We didn’t want to just randomly add them to the already crowded and confusing “Contact us” pages for VA health facilities or to the top-level facility contact information without some sort of context for which method to use in what scenario or understanding of how and where Veterans would expect to find the information.
- [Link to recommendations from health chat discovery](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/medical-centers/discovery/health-chat-discovery.md#recommendations)
- A [research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/facility-locator/research/user-research/VAMC-communications-methods/Research-Plan.md) and [conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/facility-locator/research/user-research/VAMC-communications-methods/Conversation-Guide.md) were created before this effort was parked

## Where we are now
There is a push to make VA health chat available on VAMC pages but the roll-out does not look the same at every VISN. 
As of mid-October, 
- 3 (of 18) VISNs have not implemented VA health chat at all but are expected to begin doing so this calendar year
- 9 (of 18) VISNs have implemented all 4 core services for all Veterans
- The remaining VISNs have partial implementations of 2-3 services (not necessarily the same 3) which may or may not be available at all facilities within the VISN. 

Michelle created [this mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1695664515308/a963ef125f7542f67e962ca83a8f25b368180618?sender=u3fcece2648da0fcf15d81890) to understand the communication options which are available to Veterans for completing a particular task and to arrive at a set of recommendations to propose in the short term. 
- Based on inconsistent national implementation, we cannot leverage centralized content or one-size fits all recommendations. 

---

<details> 
<summary> VA health chat SMEs provided the following information about the Veteran experience </summary>

> 
> Health Chat is administered at the VISN level (with the exception of VISN 16).  A Veteran residing in the VISN where Health Chat is available would have the ability to securely log in through the VAMC webpage and choose from a ‘menu’ of services that could include Nursing, Urgent Care, Pharmacy and Scheduling depending on what is available in their area (services vary across VISNs).  We also have a few additional services that are offered at specific VAMC sites.  In our basic marketing efforts to Veterans we state that Health Chat is available to Veterans who have:
> - Non-life-threatening health issues
> - Pharmacy Needs
> - Scheduling Needs
> 
> When the Veteran logs in to the app, they then choose the the service area where they have a need and click on the ‘channel’.  
> 
> Here are the service  ‘channels’ Veterans sees when they log in to Health Chat in VISN 8, for example 

![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/55411834/a3cd41cc-10c5-4e34-9585-f080e5975169)

</details>

---

<details>
<summary> Lauren accepted the following recommendations and content input has been requested </summary> 

> - The following are created at the system level and appear in very visible locations.
>    - In the Spotlight on the system home page (below the Manage your health online box) -> [i.e., Wilmington health care](https://www.va.gov/wilmington-health-care/)
>    - In the spotlight on the health service page at the system level -> [i.e., Wilmington health care health services page](https://www.va.gov/wilmington-health-care/health-services/)
>    - The Facilities team needs to resolve the "Read more" link defect in this one
> - if only one type of service is available, the link label could be specific to that task, such as "Use VA health chat to make an appointment"
>   - in this case, it might be appropriate to point straight to health chat
> - if more than one type of service is available (or if availability depends on the facility, the link label could be more general, like "Learn more about VA health chat"
>   - in this case, it might be appropriate to point to a Programs page where more context/details can be provided - and then link to the VA health chat from there (although this requires an extra click) -> [i.e. Wilmington health care VA health chat program page](https://www.va.gov/wilmington-health-care/programs/va-health-chat/)

</details>

---

Reference: [(Content request to support VA health chat on VAMC pages from Sitewide-Facilities #68030)](https://app.zenhub.com/workspaces/sitewide-content-accessibility-and-ia-63a1d63232beba0011a7833f/issues/gh/department-of-veterans-affairs/va.gov-team/68030)

---

When this discovery and/or research effort gets prioritized, VA health chat may be present on some pages as an initial test and to satisfy stakeholder requests. 
- If so, we will need to confirm the placement has been successful by
  - conducting Veteran research to validate the placement supports Veteran discovery and understanding of the VA health chat option
  - reviewing analytics and click through rate to determine if placement on VAMC pages has increased the use of VA health chat

- If not, this discovery can better inform the recommendations for placement

Related: we may be able to fold some VA health connect discovery into this work but we can discuss that when appropriate

## Acceptance Criteria
- [x] Reviewed [Recommendations from health chat discovery](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/medical-centers/discovery/health-chat-discovery.md#recommendations)
- [x] Reviewed [past research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/facility-locator/research/user-research/VAMC-communications-methods/Research-Plan.md) and [conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/facility-locator/research/user-research/VAMC-communications-methods/Conversation-Guide.md)
- [x] If any other resources were found/reviewed, link to resource was added to the Background section above
- [x] Noted in ticket comments what questions might be answered by data (so subsequent work could provide access to the data or the data itself)
- [x] If there are common service modalities (how services are provided) between Health Chat and VBA, these are noted in ticket comments (Dave P. may have context on this)
- [x] Options are identified to meet the goal: Give Veterans a way to access Health Chat from contextually relevant points in their digital health journey.
- [x] Follow up tickets are stubbed or PM is tagged to stub follow up tickets

**Comment by aklausmeier** [comment]
@xiongjaneg this should be assigned to Jordan and Alexis, not me... I'll see if I can update

**Comment by xiongjaneg** [comment]
Jordan estimates a 5 in Slack

**Comment by xiongjaneg** [comment]
Meeting set with Michelle Oct. 31 for more context

**Comment by xiongjaneg** [comment]
Notes from Health Chat discussion 10/31/23 with Jordan, Alexis, and Michelle

9 out of 18 VISNs implemented all four core services
Core services:
-Appointments
-Pharmacy
-Urgent care
-Nursing

Lauren Alexanderson is the Health crew leader on VA Platform and is driving this request to Facilities.

Acceptance Criteria on VBA service modalities and how do they relate to Health Chat: what’s the relationship?

E.g., Telehealth is a service modality for VAMC. Health Chat is a chat modality. Will there be equivalents for VBA (e.g., virtual appointments)

How do we represent the way services are provided and is there consistency across products?

None of the current options on the table are Health Chat, and there’s an additional unlisted Chat that Michelle just learned about. These are all siloed and not coordinated, which can create confusion for Veterans.

Editors may have added chat links, Advice Nurse is a service, Health Connect is added by API

What data would be helpful for Jordan and Alexis to know? AC will be changed to identify questions that might be answered by data access or data itself.

**Comment by thejordanwood** [comment]
**Questions that might be answered with GA/Domo:**

1. Which top task links get the most interaction?
2. Which spotlight links get the most interaction?
3. How much interaction are the Health Chat links currently getting (if present on the page)?
4. How much interaction does the telehealth accordion get on [health services pages](https://www.va.gov/wilmington-health-care/health-services/)?

**Questions that might be answered when reviewing past or future research:**

1. Do Veterans understand what VISNs are?
2. Where do they expect services like Health Chat to appear?


**Initial design thoughts:**

1. Use the [featured content component](https://design.va.gov/components/featured-content) across pages to create consistency. 
    - [System level health services pages](https://www.va.gov/wilmington-health-care/health-services/): Move Health Chat from spotlight to a featured content component, where it’s easier to explain the services offered at a VISN level.
    - [System level pages](https://www.va.gov/wilmington-health-care/): Convert spotlight section to featured content component. 
    - Top level health pages ([Pharmacy](https://www.va.gov/wilmington-health-care/pharmacy/) and [Appointments](https://www.va.gov/wilmington-health-care/make-an-appointment/)): Add Health Chat to featured content at bottom of health page and link where relevant on other sections of the page.
5. I'm not very fond of these one-off [health chat pages](https://www.va.gov/wilmington-health-care/programs/va-health-chat/) some facilities have. I'm not sure if these are needed, because the [health chat homepage](https://mobile.va.gov/app/va-health-chat) does a pretty good job explaining what it is. If we keep these, I'd like to find a way to make these pages consistent.

**Comment by ALogsdon3** [comment]
### Reviewed [Recommendations from health chat discovery](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/medical-centers/discovery/health-chat-discovery.md#recommendations)

#### Further research recommendations 
Previous Health chat discovery research (conducted in 2021) recommended further research using tree testing* to determine where in the experience Veterans expect to see and access Health Chat. 

The central research questions proposed by this research for the tree test (I've rephrased these questions to be Veteran-centered):
Where do Vets expect to see Health Chat--on specific VAMC pages, or on the top level VAMC page?
- Where do Veterans expect to see Health Chat on a top level VA.gov page? 
- Where do Veterans expect to see Health Chat on system level or specific VAMC pages?

### Reviewed [past research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/facility-locator/research/user-research/VAMC-communications-methods/Research-Plan.md) and [conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/facility-locator/research/user-research/VAMC-communications-methods/Conversation-Guide.md)

Existing research plan and conversation guide are pretty bare bones, but can be used for creating a more up-to-date version. 

### Next research steps that need tickets
- Explore [the VA's licensed tool for tree testing](https://depo-platform-documentation.scrollhelp.site/getting-started/request-access-to-tools#Requestaccesstotools-OptimalWorkshop) 
- Update the research plan and conversation guide 
- Build the tree structure. For this type of testing, we _don't need a working prototype_. We _do_ need a list of all the categories and subcategories in our global nav. I could work on building this with @davidmpickett's help. This last piece of information is a new insight that I haven't talked through with @thejordanwood (or anyone else) yet. Should discuss at a future UX sync.

*"A tree test evaluates a hierarchical category structure, or tree, by having users find the locations in the tree where specific resources or features can be found" (Definition from the [Nielsen Norman Group](https://www.nngroup.com/articles/tree-testing/#What%20is%20Tree%20Testing))

Tagging for visibility on these updates: @mmiddaugh @aklausmeier @xiongjaneg @jilladams

**Comment by thejordanwood** [comment]
@xiongjaneg 

**Next design step that needs a ticket**

-  I'll need a ticket to start on the initial designs for this. In this ticket, I'll think through how to show Health Chat at all relevant touch points. 
- There will need to be another ticket to update the design after research.

**Comment by thejordanwood** [comment]
@ALogsdon3 My questions are merely suggestions/brainstorming, please feel free to do whatever you think is best! 

I have a feeling I know that the answer to "Do Veterans understand VISNs?" is a no, but wanted to call it out because there's currently a link on the [Wilmington health care](https://www.va.gov/wilmington-health-care/) page that references them.

**Comment by xiongjaneg** [comment]
@ALogsdon3 Ticket stubs for you to edit at a later point:
- exploring tree testing #16010
- research plan and conversation guide #16011 
- build tree structure #16012

**Comment by ALogsdon3** [comment]
Other research that was reviewed:
[Vaccination Services Taxonomy](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/vaccination-taxonomy/conversation-guide.md#conversation-guide-vaccination-services-taxonomy): an example of past unmoderated study on the Facilities contract. This one is a card sort, but the order of tasks and basic structure of the study is similar.
[Facility Locator Filter Card Sorting](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/facility-locator/research/user-research/redesign/filter-categorization/research-findings.md#facility-locator-filter-card-sorting): Another card sorting activity. Similar usefulness to the Vaccination Services Taxonomy.
