### ISSUE TITLE
Message about field office hours display settings unexpectedly shown to editor on vet centers

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-cms#15702]
## Description 
The following message was unexpectedly displayed to a Vet Center editor when she logged into to review her content

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGxGQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--eebba17f209b28b9dab48d7752be5fb7fad15507/image.png)

The Drupal project office_hours was updated on Oct 7 and the release notes indicate it has some additional field settings that need to be updated
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNU5GQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5ee335d93b0aa3029b8adffaeed51ef8ff462e5f/image.png)

Dependabot brought this update in and https://github.com/department-of-veterans-affairs/va.gov-cms/pull/15610.   As a result of what the module thinks is incomplete configuration, it displays this message on Vet Centers and Vet Center Outstations.   FOr some reason https://prod.cms.va.gov/admin/reports/content-model/fields?field_name=&field_type=office_hours&entity_type=&bundle=&label= are not showing the messages.

## ACs
- [ ] Visiting a Vet Center  page as an editor does not show this message
- [ ] Visiting a Vet Center Outstation page as an editor does not show this message.
- [ ] To be on the safe side all the view mode displays that have the field_office_hours on all content types should be saved and exported, just the config changes happen across the board.

**Comment by swirtSJW** [comment]
The notification comes from this check in the office_hours module
office_hours/office_hours.theme.exceptions.inc
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOTlGQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0a060cfca23a747a435e64a3d0d73cdfb91c0d2e/image.png)

**Comment by swirtSJW** [comment]
This is resolved by this PR https://github.com/department-of-veterans-affairs/va.gov-cms/pull/15841

**Comment by swirtSJW** [comment]
It was not resolved by #15841   it is resolved by https://github.com/department-of-veterans-affairs/va.gov-cms/pull/15863

**Comment by jilladams** [comment]
https://prod.cms.va.gov/scranton-vet-center - no messages visible
https://prod.cms.va.gov/great-falls-vet-center/helena-outstation - no messages visible.

Closing.
