### ISSUE TITLE
FE: Unit and Cypress test coverage: Find Forms

### ISSUE THREAD

**Issue by randimays** [department-of-veterans-affairs/va.gov-cms#15703]
## Description
In [this ticket](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15401), we evaluated the health of the unit and Cypress tests in the Find Forms application in vets-website. Overall, coverage and efficacy are high. There are some opportunities for improvement; they are detailed in the below doc.

[Test coverage in vets-website (GDrive)](https://docs.google.com/document/d/1xzZ52UB3H54HkScLLS8EC8K1kA9kqNhkhJp5Fr3gNTI)

### User story

**AS A** Veteran
**I WANT** a functioning and error-free Find Forms application
**SO THAT** I can conduct my business successfully on VA.gov

AS AN Engineer
I WANT comprehensive end-to-end and unit tests for the Find Forms product
SO THAT I can have high confidence that this app provides value to Veterans, and not merge in code that doesn't

### Engineering notes / background
The `Test comments` section of the Google doc above aligns with the `Test coverage` section. Where there is a gap in line coverage, there are also gaps in functionality coverage. Not every file needs to be 100% tested, so some spots are skipped where testing doesn't add value or otherwise isn't needed.

## Acceptance criteria
- [ ] Unit test coverage: Product must have 80% or higher unit test coverage in each category: Lines, Functions, Statements, and Branches.
- [x] E2E / Cypress test coverage: Product must have 1 or more E2E tests

**Comment by jilladams** [comment]
@FranECross ! This is an engineering ticket Randi created based on a SPIKE in #15401 . This is an opportunity to take a look at definition / ACs, and do product magic. 🧙‍♀️  This would be a candidate for upcoming sprints. 

Adding to the relevant epics (Forms maintenance; Testing & monitoring initiative).

**Comment by jilladams** [comment]
PDF of the Google doc in ticket body, for non-Googlers: 
[#15401 Discovery_ test coverage in vets-website.pdf](https://github.com/department-of-veterans-affairs/va.gov-cms/files/12972816/15401.Discovery_.test.coverage.in.vets-website.pdf).

**Comment by FranECross** [comment]
> @FranECross ! This is an engineering ticket Randi created based on a SPIKE in #15401 . This is an opportunity to take a look at definition / ACs, and do product magic. 🧙‍♀️ This would be a candidate for upcoming sprints.
> 
> Adding to the relevant epics (Forms maintenance; Testing & monitoring initiative).

@jilladams Thank you! I'll take a look at this today and ask questions as needed. 🪄

**Comment by FranECross** [comment]
Dashboard for unit test coverage: https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/frontend-support-dashboard/unit-test-coverage-report

**Comment by randimays** [comment]
End-of-sprint update: This ticket is maybe 25% likely to carry over. I have made good progress but do have some meetings today that might prevent me from finishing.

**Comment by randimays** [comment]
## Update
PR is posted [here](https://github.com/department-of-veterans-affairs/vets-website/pull/26846) for review.

### Unit Tests
Since much of the interaction in the Find Forms application is via the shadow DOM, we are limited in how much unit test coverage we can add. There are also a few calls to `recordEvent`, our Platform implementation of Google Analytics tracking. Since they're calling Platform code directly, it's not that valuable to try to test that those were called. Both of these combined makes it tough to achieve the 80%+ across the board that we'd like, but we have made some gains:

#### Before 
<img width="1143" alt="Screenshot 2023-11-22 at 2 06 07 PM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/19175324/ff7aa09b-e222-4754-89b1-de1d84d48d35">

#### After 
<img width="1147" alt="Screenshot 2023-11-22 at 2 05 37 PM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/19175324/7c1f67f1-b7f2-4c0a-bdea-97d70ec1e0de">

### Cypress
Our existing Cypress test suites for this application are quite thorough, and test all of the functionality that the unit tests cannot (for lack of access to the shadow DOM). I did not need to add anything here.

**Comment by randimays** [comment]
I ran into a snag getting the CI for the PR to pass. The `SearchForm` Cypress test hit the flaky E2E report last week, and even though it was passing on my branch as well as locally and in staging, the report was still blocking it. Platform re-ran the report step today and it finally passed. Going to merge this one in and complete today.

**Comment by randimays** [comment]
Merged the PR just now. Closing!
