### ISSUE TITLE
If Pre deploy tasks fail then the entire job fails

### ISSUE THREAD

**Issue by indytechcook** [department-of-veterans-affairs/va.gov-cms#1570]
If Pre deploy tasks fail then the entire job fails.  This can cause the site to not deploy without changing the deploy Jenkins job to a custom branch.

**Comment by indytechcook** [comment]
I'm putting this back into the backlog until #1713 is done since it's going to refactor parts of the build process.

**Comment by ElijahLynn** [comment]
We don't think this is an issue anymore, closing for now.
