### ISSUE TITLE
Drupal: Police page centralized content

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#15710]
## User Story or Problem Statement
Police page centralized content will include:
- brief intro content
- brief context for contact info (i.e., what are the ways these named people can help and which to use for what purpose, if multiple)
- validation of police forms box and/or other relevant appropriate resources
- a paragraph for the Summary of Police Activity
- definitions for terms
- FAQ Q&As paragraph (from existing model) - includes its own heading and description

**Needs scope of content for text fields** Michelle and Dave to provide here
- plain text / limited rich text / rich text
- recommendations for suggested length/maximum for each?

## Resources

- [Current Sketch file](https://www.sketch.com/s/b48c905c-7c7f-46fb-9ae5-6020ff0e5174)
- [Current content model](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1698092447003/c969debf289d4e43e3cdd293d90053c2c137c338?wid=0-1698094046232)
- [Data elements](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/medical-centers/police/readme.md#data-elements)

## Acceptance Criteria
- [x] @davidmpickett drafts a clear spec for fields that need to change and reviews with engineers before implementation
- [ ] Contains
   - [x]  a paragraph for the header description
   - [x] VA Police forms blocks
   - [x] a paragraph for the Summary of Police Activity
   - [x] Q&As paragraph (from existing model) - includes its own heading and description
- [ ] Requires design review
- [ ] Requires accessibility review

## Team
Facilities

**Comment by davidmpickett** [comment]
Per Jordan's updated design - definitions of terms
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/4d3a646f-ad2a-4405-b47d-c6ae3212aa0b)

**Comment by davidmpickett** [comment]
I was not able to do detailed spec for this as part of #15756. Would recommend adding my time doing that to the front end of this ticket and make this a 5. (Similar to what we did for #15911)

**Comment by davidmpickett** [comment]
## Content spec (in work in progress)

- **Node title:** VAMC System - "VA Police" page content
- **Product:** VAMC System
- **Applied to:** VAMC System VA Police pages
- **Purpose:** This content appears on VA Police pages in the **About [system name]** section of VAMC system websites.

### Content 1
- **Title:** VA Police overview
- **Description:** This appears below the page heading
- **Paragraph type:** 
- **Draft content** VA police officers ensure that VA Medical Centers and other VA health facilities are safe environments where Veterans and family members can receive care.

**Comment by davidmpickett** [comment]
Adding this marked up image from Michelle as is has some content feedback not reflected in the sketch file.
![VA Police with content input markup](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/dca2e5f1-c2c9-41c9-a4e3-90021e941f14)

**Comment by swirtSJW** [comment]
This page has been created as described.  https://prod.cms.va.gov/centralized-content/vamc-system-va-police-page-content

**Comment by swirtSJW** [comment]
There is no PR associated with this since the Centralized Content is just content.  @thejordanwood , @laflannery  and @davidmpickett  this page https://prod.cms.va.gov/centralized-content/vamc-system-va-police-page-content is ready for the three of you to look over.

**Comment by laflannery** [comment]
No comments from me since as you pointed out this is just content and the content type was already reviewed

**Comment by davidmpickett** [comment]
This matches the spec. No changes needed to the Drupal configuration unless there is a significant unforeseen design shift.

Next steps for content updates:
I suggest treating this node as the source of truth for this content for purposes of CAIA review. 

The "what do these terms mean" section is already out of date. Will need to match the words actually used in the stat boxes, which shifted in the last design.

![Screenshot 2023-11-13 162212](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/2de615da-80d2-4e29-b7e1-41c39ac7337f)

@mmiddaugh @xiongjaneg Do you feel like the labels of those boxes are stable now? Any new insights / curveballs out of the data meeting last week?

**Comment by xiongjaneg** [comment]
@davidmpickett [This Slack thread](https://dsva.slack.com/archives/C0FQSS30V/p1699568903256619?thread_ts=1699567119.574309&cid=C0FQSS30V) that you were in lists the ideal fields we wanted from the vendor

**Comment by thejordanwood** [comment]
@swirtSJW The content type looks good to me! As Dave pointed out, the actual content on the FE page may change but the Drupal configuration for this matches the spec.

**Comment by swirtSJW** [comment]
Thanks all.  Sounds like we can call this ticket done.

**Comment by xiongjaneg** [comment]
Submitted in [Platform collab cycle ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/68949)

**Comment by jilladams** [comment]
Closed based on comment thread while prepping sprint report. If this needs reopened for some reason, please tag me for awareness.
