### ISSUE TITLE
Auto generate police pages for VAMC systems

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#15715]
## User Story or Problem Statement
Police transparency pages need to be created for each system.

## Acceptance Criteria
- [x] A hook_update_N exists that automatically creates a page for each system
- [x] A menu item is generated for the proper location (child of ABOUT [SYSTEM NAME], above _____, below ____)
  - [ ] [CAIA location recommendation](https://github.com/department-of-veterans-affairs/va.gov-team/issues/67055#issuecomment-1819824600)
  - Note that CAIA recommendation involves [imposing a standard order](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16233) on the "ABOUT [SYSTEM NAME]" menu subsection. In lieu of imposing that order on all VAMC menus (which I assume is out of scope), we would need to choose a fallback placement rule (e.g. above "Work with us")
- [x] ~Account for Lovell exceptionalities (awaiting Tricare feedback)~ Too big a lift to account for automated creation of Lovell Tricare.  It is easy enough to build a tricare version or convert to Federal if they need one in both.  For now this only builds a page for Lovell VA.
- [x] Page is automatically published (shouldn't have any front end user facing affect) Edit - Since we have menues, the menu item would be visible on FE if the page was published.  So had to make them draft.

## Team
- Facilities

**Comment by xiongjaneg** [comment]
@swirtSJW Michelle and I are inclined not to have any editorial intervention on this page for MVP. We'd like it to be autopublished.

One question:
Jordan's [Sketch file ](https://www.sketch.com/s/b48c905c-7c7f-46fb-9ae5-6020ff0e5174) includes a Security accordion on the facility page under Prepare for Your Visit that would link to the Police page. Could this accordion be standardize to all facilities? Could this be auto-populated under Prepare for Your Visit?

**Comment by mmiddaugh** [comment]
Will we be able to auto-generate these based on the availability of data for a given facility? In other words, a VA health location shouldn't automatically get a VA police page unless there is data to display. For example, a VA Domiciliary may not have police presence or activity to report.

**Comment by davidmpickett** [comment]
Menu position will be determined by CAIA in https://github.com/department-of-veterans-affairs/va.gov-team/issues/67055
Proposals are currently being workshopped in Mural: https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1695321619292/8c3bdcb8a5e55c95c74f42d9a722d34d2b4f4c14?wid=0-1699288646782

**Comment by xiongjaneg** [comment]
@xiongjaneg Consider a Lovell exception for Tricare as Tricare facilities will likely not have VA Police data or will this be like any facility that doesn't have data

**Comment by xiongjaneg** [comment]
Capturing these questions for the record:

Questions for refinement

- Does the page need editorial intervention before publishing (or can we auto publish)? Likely no as the CSV could be a starting point that editors could correct later, if needed.
  - There will be a CSV of phone numbers but local editors should be able to edit the numbers because they may be the most accurate source of the phone number.
    -  Is this a starting CSV? What's the change management around the editor intervention?
- What about Lovell? The VA side will likely operate similarly to other VA facilities but Tricare facilities won't be included as Drupal is the source of those facilities.
  - Will Tricare duplicate what's on the VA page?
  - Should Tricare page be unpublished?

**Comment by davidmpickett** [comment]
> There will be a CSV of phone numbers but local editors should be able to edit the numbers because they may be the most accurate source of the phone number.
> Is this a starting CSV? What's the change management around the editor intervention?

No local editor intervention or even putting the phone number fields in Drupal for MVP. [Per the content model](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1698092447003/c969debf289d4e43e3cdd293d90053c2c137c338?wid=8-1698094046232), the non-emergency phone number csv will be converted to a JSON object and displayed dynamically per facility.

Editor intervention is a post-MVP consideration once the API is available and the content model will be updated then to reflect which data should be controlled via Drupal

**Comment by davidmpickett** [comment]
@jilladams @xiongjaneg @swirtSJW @omahane - I was following up on the CAIA IA recommendations and realized their guidance may not not be sufficient to answer AC #2. I added this note to the main ticket body.
 
Not a huge deal, but may require a small bit of conversation when ticket is picked up

**Comment by swirtSJW** [comment]
@davidmpickett I see your reference to a fallback of just above "Work with us" which puts it pretty high on the existing menu structure (which does not match the structure you showed in the description)
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5752113/c4f3e603-1ce5-452d-b98a-a43bcd5d858a)

**Comment by swirtSJW** [comment]
hook update built, and working 
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5752113/0bb64b54-2b73-426f-91fa-ebec2c3cdeb0)

With the exception of menu placement  :(
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5752113/a3fc77ba-dd38-49fd-a93f-56ea6e3849fb)

![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5752113/67339911-e88a-46a3-9cae-7824ceb41d46)

**Comment by davidmpickett** [comment]
> @davidmpickett I see your reference to a fallback of just above "Work with us" which puts it pretty high on the existing menu structure (which does not match the structure you showed in the description)

This was not an actual recommendation. It was just an example of what a fallback recommendation might look like.

> If the menu is ordered in terms of importance, this placement would indicate this page is pretty important. Is it the second most important of this group?

Per CAIA, the first and last menu positions are the most important, so we want this somewhere in the middle.

**Comment by swirtSJW** [comment]
Placement for the menu was placed just above Policies.   That was chosen because it has a weight that is significantly different from its siblings so I could reliably place things above it (rather than work with us)
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5752113/0d81efc4-393b-4058-a5bb-ee291585c156)

This was the most reliable way to pull this off.


The only possible solution to avoid this in the future is to actively separate all items in a menu by at least a value of two.
https://www.drupal.org/project/codit_menu_tools/issues/3406863

**Comment by xiongjaneg** [comment]
@swirtSJW If you want to stub a ticket for that potential solution, please do. Which you may have already :)...
