### ISSUE TITLE
Health Checks fail due to sync_db taking to long on dev/stage

### ISSUE THREAD

**Issue by indytechcook** [department-of-veterans-affairs/va.gov-cms#1571]
Health Checks fail due to sync_db taking to long on dev/stage.

The issue caused due to the health checks to `/heath` are being redirected to `install.php` on drupal after the database is empty.  Thes status of `302` was causing the health check to fail.

Tasks:
- [ ] Turn Drupal Maintenance mode back on
- [ ] Update terraform to add `302` to valid status.

**Comment by ElijahLynn** [comment]
Do we know why they fail yet?

**Comment by indytechcook** [comment]
The current working theory is the 503 response that drupal does during maintenance mode but my testing of `/health` returns a 200.

**Comment by ElijahLynn** [comment]
> The current working theory is the 503 response that drupal does during maintenance mode but my testing of `/health` returns a 200.

Thanks, I think there is a way to see the healthcheck responses, don't remember off hand.

**Comment by indytechcook** [comment]
We actually found that the issue is not related to the maintenance mode but related to failing health checks fail due to the the `sync_db` taking to long. 

I'm updating the description with the next steps.
