### ISSUE TITLE
VAMC System VA Police content type in the CMS

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#15714]
## User Story or Problem Statement

As a VAMC editor, I want to add custom information for my system to the police transparency page so that I can surface things for Veterans in my system.

## Questions for refinement
- What fields do editors need (might not use any for MVP??)? Answer: None, especially for MVP.
- If we are expecting editors to interact with this content type, then should it have design review now? Answer: Not needed for MVP.

## Resources
- [Current content model](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1698092447003/c969debf289d4e43e3cdd293d90053c2c137c338?wid=0-1698094046232)
- [Collab cycle IA design](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/information-architecture/ia-design-docs/va-police-facilities-page.md)

## Acceptance Criteria
- [x]  @davidmpickett drafts a spec for fields and reviews with engineers before implementation
  - [x] Content type name _____?
  - [x] machine name: vamc_system_police
  - [x] field_administration
  - [x] field_office (to connect to system)
  - [x] field fetch fields for centralized content
  - [x] perms match vamc_system_billing_insurance 
- [x] appropriate alias pattern
- [x] Requires Content Model Documentation
- [ ] Requires design review
- [ ] Requires @laflannery a11y review
- [ ] Ticket is stubbed for KB article update

## Design principles

Veteran-centered
- [x] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [x] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### Team
- Facilities

**Comment by xiongjaneg** [comment]
@swirtSJW Michelle and I are inclined not to have editors edit any part this page for MVP. Would iceboxing this ticket for now be a concern for you?

**Comment by xiongjaneg** [comment]
@xiongjaneg Needs content model ticket link here

**Comment by davidmpickett** [comment]
@xiongjaneg  This one might also need a point or two for me to help with spec

**Comment by xiongjaneg** [comment]
@davidmpickett added to AC

**Comment by xiongjaneg** [comment]
@xiongjaneg need update hook or script to run to generate 140 pages and put them in the right spots in the menu, etc.

**Comment by davidmpickett** [comment]
There won't be any fields they can do anything with for MVP. But I think we should still give the roles the standard permissions. The plan is to add additional fields that editors could control post-MVP. 

Even with no interactive content fields, they would still need to go in and save it once a year to keep it off the Outdated Content report.

**Comment by jilladams** [comment]
From scrum: 
* We can exclude Police pages from the aging content view, so they don't get pings. 
* For MVP, we could exclude these Police pages from the VAMC admin content view as well. If we don't exclude, Editors would be able to see and edit, but save nothing. 

Saving this for Steve to address in a future comment with more detail.

**Comment by xiongjaneg** [comment]
Stubbed #16120 for the outdated content report ticket

**Comment by mmiddaugh** [comment]
Agree: this page ought to be exempted from the outdated content report and trigger.

Understanding about local editor input/access changed during a conversation with Police Services leadership in which we learned a single 24/7 non-emergency phone number will be made available via csv and any additional phone numbers and/or physical address will be best known/owned by local staff. 

Access by local editors is post-MVP. 

Questions:
- Is there any risk in adding permissions now? 
- Is the proposal to add the fields for possible future local editor use now? If so, does it make sense to add those permissions at that time?

**Comment by swirtSJW** [comment]
> Is there any risk in adding permissions now?
@mmiddaugh the only risk is in creating editor confusion.  

I phone numbers will be maintained by local staff, then it makes sense to add them to the content type.  (and maybe even migrate them in from the CSV??)  The number of sources of truth on this is starting to get a bit concerning.

**Comment by swirtSJW** [comment]
Also if we are planning to add editorially controlled fields in the next 12 months, then there is no reason to intentionally remove this content type from the outdated content notifications because they will never get surfaced there in the first year anyway.

**Comment by davidmpickett** [comment]
BLUF - I don't think there's a huge risk either way. And 95% of the work for this ticket can be completed without a decision on this point, so this shouldn't be a blocker to Drupal devs starting the ticket.

> * Is there any risk in adding permissions now?

It is not non-zero, but it very low in my opinion. All the fields on the Content Type will locked down in various ways, so local editors wouldn't be able to break anything. 

The risk of **not** setting the permissions now is that future Facilities team members may spend unnecessary cycles trying to understand why something isn't working as expected. I'm thinking specifically here of the Sitewide Contract being up for recompete in April 2024.

Permissions are generally a "set it and forget it" part of Drupal that you put in place when you create something new. **Not** giving editing permissions to these 3 roles breaks the standard Permissions pattern for most content types. This would be an exception and therefore would require clear documentation so that future team members understand the intention.

> * Is the proposal to add the fields for possible future local editor use now? 

No. That would introduce risk and complexity we don't need for MVP

**Comment by mmiddaugh** [comment]
> The number of sources of truth on this is starting to get a bit concerning.

Although we have several sources of truth for the data on the page, there is a single source of truth for a given data point (i.e., number of arrests comes from a single source, even if it is supplied by a different source than the data for incidents with weapon discharge). 

Any contact information contributed by editors in the future will supplement the 24/7 non-emergency number we expect to receive from Police Services (such as the local emergency number or the physical campus location).

**Comment by swirtSJW** [comment]
Fields are created and that's about it.

**Comment by swirtSJW** [comment]
This content type is complete in this PR and is ready for design review, Accessibility review, and code review.  https://github.com/department-of-veterans-affairs/va.gov-cms/pull/16169
Will add QA steps for each in the morning.

**Comment by xiongjaneg** [comment]
@jilladams This is still pending PR review

**Comment by davidmpickett** [comment]
Just noting that I spent a chunk of time today reviewing the PR and responding to comments. Two [minor suggestions](https://github.com/department-of-veterans-affairs/va.gov-cms/pull/16169#discussion_r1406623517) (SHOULD) and then one [eyebrow raising thing](https://github.com/department-of-veterans-affairs/va.gov-cms/pull/16169#issuecomment-1828720168) that might be some known Tugboat quirk, but on it's surface feels approval-blocking to me (MUST).

**Comment by jilladams** [comment]
@xiongjaneg here too: From scrum notes and convo with Steve today, this one taking longer than expected to root cause the Sections issue that Dave flagged above, re: capacity for the remaining Drupal work in Sprint 98.

**Comment by swirtSJW** [comment]
All the issues were resolved and this has been merged.  Should land on prod on monday.
