### ISSUE TITLE
Add the block description field to alert list

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-cms#15721]
## User Story or Problem Statement
As someone who needs to add previously created alerts to Drupal pages, I have a hard time knowing which alert is the right one to choose based on what's showing on the list of alerts. 

## Description or Additional Context 
This is especially an issue for the Spanish and Tagalog alerts we have set up. We use the same content with a different link within the alert so it's impossible to know which alert we want just by look at the info that's currently listed.

A possible solution would be to add an additional column that adds the description block in the view for quick reference. 

Description field is displayed in the first column. 

Ensure this also displays in Benefits Details Pages.

## Acceptance Criteria
- [ ] Determine LOE needed to implement an additional column in the view for the alert list.
- [ ] Depending on LOE, create a new ticket or implement fix
- [ ] UX review
- [ ] Requires accessibility review of 

## Team
Please check the team(s) that will do this work.

- [x] CMS Team
- [ ] Public Websites
- [ ] Facilities
- [ ] Accelerated Publishing

**Comment by edmund-dunn** [comment]
@BerniXiongA6 Good candidate for next sprint.
