### ISSUE TITLE
Rework description on VAMC facility operating status to remove COVID

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#15737]
## User Story or Problem Statement
On VAMC facility nodes, the Operating status field give Covid related guidance.
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5752113/68861521-ab7d-44e4-b17f-49adb66127e5)

## Description or Additional Context 
This covid context was added to account for handling of Supplemental Status related to Covid which is no longer present.

## Acceptance Criteria
- [ ] Fieldset description is updated to: Use this status for weather or other events that impact your facility's operations. This status will display on the facility's location page, operating status page, and the VA's facility locator tool. For more guidance, refer to [the Knowledge Base article about operating status (opens in a new window)](/help/vamc/about-locations-content-for-vamcs/about-alerts-and-operating-statuses/how-to-edit-a-vamc-facility-operating-status).
- [ ] Remove the last sentence in the field description that references COVID.

**Comment by jilladams** [comment]
@xiongjaneg @mmiddaugh came across this ticket in the course of another random voyage through the backlog. The rest of the COVID facility status work was done right before Jane joined, and this was the last item in that epic that's not yet done. This help text still appears in production at https://prod.cms.va.gov/node/add/health_care_local_facility. 

Flagging as something we could pull into stretch sometime there's room.

**Comment by swirtSJW** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Sitewide-Facilities-639f5253e4b702a32376339e/issues/department-of-veterans-affairs/va.gov-cms/15737?planning-poker) with Zenhub @omahane

**Comment by xiongjaneg** [comment]
@davidmpickett Other than removing the last sentence, are there any other text changes needed for this field?

**Comment by davidmpickett** [comment]
Revised help text for the details field looks good. While we're looking at Operating Status we could rework the fieldset description to match the new pattern we've establish on VBA:

Use this status for weather or other events that impact your facility's operations. This status will display on the facility's location page, operating status page, and the VA's facility locator tool. For more guidance, refer to [the Knowledge Base article about operating status (opens in a new window)](https://prod.cms.va.gov/help/vamc/about-locations-content-for-vamcs/about-alerts-and-operating-statuses/how-to-edit-a-vamc-facility-operating-status).

**Comment by Agile6MSkinner** [comment]
This is the last remaining story in #13681, so I'd like to get it prioritized for sprint 9 and close out that epic.

**Comment by davidmpickett** [comment]
This is a 1-line configuration change that is within my skillset. Barely even qualifies as a code change.

**Comment by Agile6MSkinner** [comment]
@davidmpickett Want to just pull it in and do it now? Saves some time in planning...

**Comment by davidmpickett** [comment]
PR is up and ready for review. Tagged @jv-agile6 on in to see if we could get this done before @omahane even comes back from vacation ;)

**Comment by jilladams** [comment]
Prod verified, closing:
![Screenshot 2024-07-19 at 12 27 00 PM](https://github.com/user-attachments/assets/ecc21758-0104-44af-ac7b-86475ebb7eb1)
