### ISSUE TITLE
Align VC, VBA, NCA operating status with VAMC

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#15738]
## User Story or Problem Statement
The VAMC operating status field group
- uses radio buttons
- hides Description if "Normal" is selected
- When Description is visible it is required
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5752113/46987f48-dc02-4d33-a83d-598faadbe490)

Vet Centers, outstations, mobiles & CAPS, as well as VBA and NCA use a lesser version that does none of those things.
 
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5752113/0b0d18e3-d609-48b9-94aa-9de3a8603f7d)

For consistency and less editorial confusion, they should all used the improved version from VAMC.
## Problems created by the current situation
1. Editors are not entering descriptions under "facility notice" "Limited service" or "Closed" so it leaves Veterans hanging.
2. Editors are entering descriptions for "Normal services and hours" which are never getting rendered on the VA.gov because they are not supposed to be.  Creating editor confusion and extra effort.

## Acceptance Criteria
- Apply VAMC functionality to 
  - [ ] VBA facility
  - [ ] NCA facility
  - [ ] Vet Center
  - [ ] Vet Center Mobile
  - [ ] Vet Center Outstation
  - [ ] Vet Center Cap

## Team
Please check the team(s) that will do this work.

- [ ] CMS Team
- [ ] Public Websites
- [x] Facilities
- [ ] Accelerated Publishing

**Comment by davidmpickett** [comment]
Was resolved in #16469
