### ISSUE TITLE
 Vet Center change management for operating status alignment with VAMC model

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#15740]
## User Story or Problem Statement
The VAMC operating status field group
- uses radio buttons
- hides Description if "Normal" is selected
- When Description is visible it is required

Vet Centers currently doesn't.

#15738 aligns Vet Center operating status field group with the VAMC model. This ticket is to consider and address change management for that update.

## Acceptance Criteria
- [ ] Impact upon Vet Center editors is considered.
- [ ] Recommendations are made for change management, including KB articles or office hours.
- [ ] Subsequent tickets are stubbed as needed.

**Comment by davidmpickett** [comment]
Was resolved in #16469
