### ISSUE TITLE
Mechanism to hard launch Nat'l Cal events checkbox to all editors

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#15747]
## User stories

As the Events product owner, I want an easy means to roll back the new National outreach checkbox without code deploy, for quick mitigation.

## Description
We will soft launch the Nat'l events calendar checkbox to a short list of editors, using a feature flag configured to only show the box to that list of folks. 

FEATURE_EVENT_OUTREACH_CHECKBOX = the soft launch toggle
* Enabled = feature is visible to the shortlist of soft launch editors & Drupal Admins
* Disabled = feature is not visible to any Drupal user

When we hard launch, we want to launch to everyone and have an easy means of rolling back. 

### **Add a 2nd feature toggle:** 
  * Enabled = feature is visible to all editors
  * Disabled = feature is only visible to Drupal Admins & Editors controlled by the soft launch feature toggle, unless FEATURE_EVENT_OUTREACH_CHECKBOX is also disabled

Pros: no risk to soft launch editor experience. 
Pros: Can build this and ship it now, and just turn it on when we're ready
Cons: 2 checkboxes to manage in a rollback scenario.

**PLAN**
**1. FEATURE_EVENT_OUTREACH_CHECKBOX** 
  * Enabled:
    * CMS: Enables seeing the "Publish to National Calendar" checkbox on Events forms for 12 specified users.
    * FE: Publishes any Events with "Publish to nat'l cal" checked to the Natl Calendar, after the next content release.
  * Disabled:
    * CMS: 12 editors can't see the Publish checkbox on Events forms
    * FE: Any VAMC Events with "Publish to nat'l cal" checked will _not_ appear on the Natl Calendar, after the next content release.

**2. FEATURE_EVENT_OUTREACH_CHECKBOX_ALL**
  * Enabled:
    * CMS: Enables seeing the Publish checkbox for Everyone
    * FE: No changes.  
  * Disabled:
    * CMS: No editors can see the checkbox (_unless_ FEATURE_EVENT_OUTREACH_CHECKBOX is enabled) 
    * FE: No changes. 

## ACs

- [ ] Feature flags exist to allow easily enabling/ disabling the Nat'l calendar checkbox, after launch, to all CMS editors

**Comment by jilladams** [comment]
@dsasser please update in ticket if I misstated anything here. 

@FranECross here's the notes from talking to Daniel. Holler with your thoughts, and we should definitely get Dave's buy-in on whatever we propose, so he knows what to expect during launch / if we need to roll back for some reason.

**Comment by jilladams** [comment]
@FranECross I just realized we're going to have to pull this into current sprint to get it done next week. We'll need to prioritize refining it.

**Comment by FranECross** [comment]
@jilladams Thanks for the ping! Is it available so that Blake can send his email to the short list of editors? I'll review/groom and check with you on questions.

**Comment by jilladams** [comment]
Latest: https://dsva.slack.com/archives/C52CL1PKQ/p1698357908815749?thread_ts=1698191391.351039&cid=C52CL1PKQ

**Comment by jilladams** [comment]
**1. FEATURE_EVENT_OUTREACH_CHECKBOX** 
  * Enabled:
    * CMS: Enables seeing the "Publish to National Calendar" checkbox on Events forms for 12 specified users.
    * FE: Publishes any Events with "Publish to nat'l cal" checked to the Natl Calendar, after the next content release.
  * Disabled:
    * CMS: 12 editors can't see the Publish checkbox on Events forms
    * FE: Any VAMC Events with "Publish to nat'l cal" checked will _not_ appear on the Natl Calendar, after the next content release.

**2. FEATURE_EVENT_OUTREACH_CHECKBOX_ALL**
  * Enabled:
    * CMS: Enables seeing the Publish checkbox for Everyone
    * FE: No changes.  
  * Disabled:
    * CMS: No editors can see the checkbox (_unless_ FEATURE_EVENT_OUTREACH_CHECKBOX is enabled) 
    * FE: No changes. 

AND: we need 2 tech debt tickets for when launch is done and we know the feature will stay alive: 
1. Remove FE logic that references FEATURE_EVENT_OUTREACH_CHECKBOX 
2. Remove both CMS Feature toggles (FEATURE_EVENT_OUTREACH_CHECKBOX, FEATURE_EVENT_OUTREACH_CHECKBOX_ALL)

**Comment by jilladams** [comment]
Confirmed: the list of editors for beta launch are all VAMC editors.

**Comment by FranECross** [comment]
Email sent to Blake Scates with email template for editors

[2023-10-27_Email to Blake Scates with email template to send to editors.pdf](https://github.com/department-of-veterans-affairs/va.gov-cms/files/13191025/2023-10-27_Email.to.Blake.Scates.with.email.template.to.send.to.editors.pdf)

**Comment by jilladams** [comment]
New toggle appears in prod. Closing.
