### ISSUE TITLE
Figure out what is going on with our slow periodic tasks

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#1574]
The times on both our daily and periodic tasks have bloated up incredible for no change in related code.
Periodic (originally taking less the 20 min)
![image](https://user-images.githubusercontent.com/5752113/79997579-c04dd880-8487-11ea-81aa-5b3cf88f41d7.png)

Daily
![image](https://user-images.githubusercontent.com/5752113/79997614-c5ab2300-8487-11ea-9b52-ecdbdffc60db.png)

**Comment by indytechcook** [comment]
@swirtSJW found a resolution to this issue.

**Comment by indytechcook** [comment]
Related PRs:
* https://github.com/department-of-veterans-affairs/va.gov-cms/pull/1626
* https://github.com/department-of-veterans-affairs/va.gov-cms/pull/1603
