### ISSUE TITLE
Remove CMS feature flag FEATURE_SINGLE_VALUE_FIELD_LINK

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#15758]
## User Story or Problem Statement
The feature flag FEATURE_SINGLE_VALUE_FIELD_LINK was added to content-build in July 2019 [by this PR](https://github.com/department-of-veterans-affairs/vets-website/pull/10387)   It is currently disabled and seems to be in need of removal.

IN content build it is used by [the featureSingleValueFieldLink filter ](https://github.com/department-of-veterans-affairs/content-build/blob/249c6e57df98911b8d2a9f47df0fede6be4f539c/src/site/filters/liquid.js#L590)
which is used in the following templates
- [promo block](https://github.com/department-of-veterans-affairs/content-build/blob/249c6e57df98911b8d2a9f47df0fede6be4f539c/src/site/blocks/promo.drupal.liquid#L37)
- [Link teaser](https://github.com/department-of-veterans-affairs/content-build/blob/249c6e57df98911b8d2a9f47df0fede6be4f539c/src/site/paragraphs/linkTeaser.drupal.liquid#L28)
- link [teaser featured content](https://github.com/department-of-veterans-affairs/content-build/blob/249c6e57df98911b8d2a9f47df0fede6be4f539c/src/site/paragraphs/link_teaser_featured_content.drupal.liquid#L3)

## Acceptance Criteria
- [ ] Remove use of flag FEATURE_SINGLE_VALUE_FIELD_LINK from content-build
- [ ] Remove use of flag FEATURE_SINGLE_VALUE_FIELD_LINK from CMS
- [ ] Consider removing the filter featureSingleValueFieldLink which may no longer be needed.

## Team
Please check the team(s) that will do this work.

- [ ] CMS Team
- [x] Public Websites
- [ ] Facilities
- [ ] Accelerated Publishing

**Comment by randimays** [comment]
Both the content-build code and CMS feature flag code have been removed/merged. Waiting for things to get to staging to validate

**Comment by randimays** [comment]
Validated the below URLs in prod:

`promos.drupal.liquid`
https://va.gov/life-insurance: "Apply for Veterans Affairs Life Insurance (VALife)"

`linkTeasers.drupal.liquid`
https://va.gov/life-insurance: under "Get VA life insurance"

`link_teaser_featured_content.drupal.liquid`
https://va.gov/south-texas-health-care/health-services: "In the spotlight at VA South Texas health care"

All are good! Closing.
