### ISSUE TITLE
The all FE content View is outdated / no longer accurate

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#15768]
## Describe the defect
The all FE content View and its export file is outdated and no longer includes all the FE pages on the site.
https://prod.cms.va.gov/cms-content

### Should include 
- [x] Benefits Detail Page
- [x] Benefits Hub Landing Page
 ~CMS Knowledge Base Article~
- [ ] Campaign Landing Page
 ~Centralized Content~
- [ ] Checklist
- [ ] Event
- [x] Events List
- [ ] FAQ page
 ~Full Width Alert~
- [ ] Health Services List
- [ ] Image list
- [ ] Landing Page
- [ ] Leadership List
- [ ] NCA Facility
- [ ] News Release
- [ ] News Releases List
- [x] Office
 ~Promo Banner~
 ~Publication~
- [x] Publication Listing Page
- [ ] Resources and Support Detail Page
~Reusable Q&A~
 ~Service Region~
?? Staff Profile  - THis one is a hard one because only profiles of leadership get their own page.
- [ ] Step-by-Step
- [ ] Stories List
- [ ] Story
~Support Service~
- [ ] VA Form
- [x] VAMC Detail Page
- [x] VAMC Facility
 ~VAMC Facility Health Service~
 ~VAMC Facility Non-clinical Service~
 - [x] VAMC System
 ~VAMC System Banner Alert with Situation Updates~
- [ ] VAMC System Billing and Insurance
 ~VAMC System Health Service~
- [ ] VAMC System Locations List
- [ ] VAMC System Medical Records Office
- [ ] VAMC System Operating Status
- [ ] VAMC System Policies Page
- [ ] VAMC System Register for Care
- [ ] VBA Facility
 ~VBA Facility Service~
- [ ] Vet Center
 ~Vet Center - Community Access Point~
 ~Vet Center - Facility Service~
- [ ]  Vet Center - Locations List
~Vet Center - Mobile Vet Center~
~Vet Center - Outstation~
- [ ] Video list

## To Reproduce
1. Go to ['the View'](https://prod.cms.va.gov/cms-content)
2. Click on the content type filter.  
3. Notice not all the content types that have standalone pages are present.
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5752113/855a8216-0ce0-49ba-ad38-39de8b2013e3)

## AC / Expected behavior
For the View and displays  /admin/structure/views/view/content_served_from_drupal
- [ ] All content that has standalone pages on the va.gov is included in the View display
- [ ] All content that has standalone pages on the va.gov is included in the CSV download
- [ ] The filter on both View displays contains all the content types that have FE pages.
- [ ] Why are there two content type filters on the Views?   There should only be the exposed one.  The unexposed seems odd.
- [ ] text in the header seems incorrect
- [ ] accessibility review

## Additional context
In the past, CAIA has used this View to audit the site in a variety of ways (url structure, page presence...)

**Comment by BerniXiongA6** [comment]
Hi @ndouglas -- when you're able, could you help me triage this ticket to see if/when it can make it into prerefinement activities? Thank you sir!

**Comment by ndouglas** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VAgov-CMS-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/15768?planning-poker) with Zenhub @edmund-dunn @JunTaoLuo @tonytaylor

**Comment by edmund-dunn** [comment]
@ndouglas we need a comprehensive list of what needs to be included and what the header text should be. I am unable to estimate as it stands.

**Comment by EWashb** [comment]
Hey @ndouglas and @edmund-dunn, let me talk to CAIA first to see if they are still using this view. Also, do we know when this was last updated? I'll be honest that I didn't even know this existed.

I don't want to spend too much time updating something that folks aren't actively using. cc: @BerniXiongA6

**Comment by BerniXiongA6** [comment]
Per @EWashb -- CAIA does not use this, we'll close this ticket.
