### ISSUE TITLE
Update Events "See more events" link to use more descriptive links

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#15766]
## Status

**[2024-06-03]** Ticket no longer blocked.
**[2024-04-24]** This ticket blocked by a BE ticket that's Ready to be worked on.

## Description
IA feedback: https://github.com/department-of-veterans-affairs/va.gov-team/issues/67025
[IA mural treatment](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1695321619292/8c3bdcb8a5e55c95c74f42d9a722d34d2b4f4c14?wid=0-1697842616395)

Update See more events at the foot of main content on events. 

Want to see more events offered at Example VAMC?
[Go to VAMC events calendar]

Want to see more events offered by the VA across the country?  (for Outreach events or VAMC+Outreach events only)
[Go to outreach events calendar]

## ACs

**AC1: When Veteran or other user is viewing an event at a particular VAMC, they see two links in order to view other events that are VAMC specific or Outreach** 

**GIVEN:** a Veteran or other user is viewing an Event at a specific VAMC on VA.gov 
**WHEN:** the Veteran or other user looks toward the bottom of the event information on the screen
**THEN:** the Veteran or other user will see two links they can follow to other events:
  * Want to see more events offered at Example VAMC?  [Go to VAMC events calendar] 
  * Want to see more events offered by the VA across the country? [Go to outreach events calendar]

**AC2: When Veteran or other user is viewing an event on the Outreach calendar, they see only a link to view other Outreach events** 

**GIVEN:** a Veteran or other user is viewing an Outreach/National Event on VA.gov
**WHEN:** the Veteran or other user looks toward the bottom of the event information on the screen
**THEN:** the Veteran or other user will see a link they can follow to see the outreach/national calendar.
  * Want to see more events offered by the VA across the country? [Go to outreach events calendar]

ACs added 2024-06-11:
- [ ] a11y review
- [ ] Design review

Mural screens:

* [User is viewing an event for a specific VAMC, and in this case, there are two links at the bottom to view more events](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1695321619292/8c3bdcb8a5e55c95c74f42d9a722d34d2b4f4c14?wid=19-1697143649799)
* [User is viewing an event on the outreach and events calendar, and in this case there is just one link to view more events across the country](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1695321619292/8c3bdcb8a5e55c95c74f42d9a722d34d2b4f4c14?wid=6-1697143649799)

**Comment by jilladams** [comment]
@laflannery FYI, ticketed.
@thejordanwood I'm realizing this link treatment is maybe news to you, I've lost track this week.  We'll prob review in sprint planning if you don't get time to look-see before.

**Comment by FranECross** [comment]
@thejordanwood @jilladams Will you please review the AC I added and let me know if I captured what the original ticket was asking for? Also, one of the associated tickets indicates they want this by Veterans Day. Is that possible considering we just started a new sprint last week, and Veteran's Day is next Friday? Thanks a bunch!

**Comment by jilladams** [comment]
1. Re: Veterans Day ask: this was an IA ask related to our National Events calendar checkbox launch. We won't get this work done by veterans day but we did agree to get it done as soon as we're able, relative to the launch. So: as soon as we can get it refined / prioritized is good. 

2. re: ACs: great work, and they helped me realize a problem in the CAIA mural. I updated the AC text to fix it, and flagged it in a [comment](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1695321619292/8c3bdcb8a5e55c95c74f42d9a722d34d2b4f4c14?wid=0-1698709389172) in the mural for IA folks to be aware of:  If you are looking at an Outreach Calendar _only_ event, there should only be 1 "see more" link, pointing to the Outreach natl calendar.  (There shouldn't also be a "see more at a VAMC" link, bc there's no obvious VAMC calendar to point to.). I've asked the Mural owner to update that in the mural as well.

**Comment by thejordanwood** [comment]
@jilladams @FranECross Do we need anything from me for this ticket? I'm fine with the Mural board treatment for this, but can add the design into [this Sketch file](https://www.sketch.com/s/8ec18b80-a905-47fb-a217-5720450befa1) if needed.

**Comment by FranECross** [comment]
@thejordanwood I don't think anything is needed. Unless @jilladams thinks otherwise <grin> I don't think you need to get this into Sketch, since we'll be soon moving things to Figma. What do you think of me adding a small story to the backlog to have the design put in Figma for historical purposes after we actually move over there?

**Comment by jilladams** [comment]
Good by. me!

**Comment by FranECross** [comment]
Thanks, @jilladams and @thejordanwood ! I'll link the Figma story to this ticket after I get it created.

**Comment by thejordanwood** [comment]
@FranECross Works for me. Thank you!

**Comment by FranECross** [comment]
Fran to collaborate with Jordan regarding verbiage and links.

**Comment by FranECross** [comment]
@thejordanwood I think that you altered the mural board after we all chatted about making the wording/links shorter and more generic, and having them display depending on what event they are looking at. Will you please look at the two scenarios below and let me know if they are the current designs to use for the ticket? Thanks!

- [User is viewing an event for a specific VAMC, and in this case, there are two links at the bottom to view more events] (https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1695321619292/8c3bdcb8a5e55c95c74f42d9a722d34d2b4f4c14?wid=19-1697143649799)
- [User is viewing an event on the outreach and events calendar, and in this case there is just one link to view more events across the country](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1695321619292/8c3bdcb8a5e55c95c74f42d9a722d34d2b4f4c14?wid=6-1697143649799)

cc @randimays @chriskim2311

**Comment by FranECross** [comment]
@FranECross check with Jordan and did I make the ticket?

**Comment by jilladams** [comment]
@FranECross you did! https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15946

**Comment by thejordanwood** [comment]
@FranECross I haven't had a chance to work on this ticket and haven't updated the Mural board. I'm not sure if someone else has updated the Mural since it was decided that the wording/links should be shorter and more generic.

The designs themselves look fine to me, but I'm not sure who should approve the final wording for this. Any thoughts @jilladams?

**Comment by FranECross** [comment]
Dave responded that we don't need to reach out to CAIA, and that Jordan and Dave Pickett can come up with the wording. 

Slack message sent today https://dsva.slack.com/archives/C52CL1PKQ/p1701382788170309

**Comment by FranECross** [comment]
@FranECross The copy ticket is slotted for Sprint 100. This one follows and is blocked by.

**Comment by randimays** [comment]
This was pulled in as Stretch on 4/9

**Comment by randimays** [comment]
@FranECross Do we have analytics requirements for the two links that will be used? Right now, the existing "See more events" link just logs a "nav-secondary-button-click."

**Comment by FranECross** [comment]
@randimays Are the two links components that have the baked in analytic va-link? If so, I think we can get away with using that, since the destination will either be an event at a VAMC or on the outreach calendar. If not, then I can come up with custom events to capture. TIA!

**Comment by randimays** [comment]
@FranECross They are both using va-link (which has the baked-in analytics), but we're still lacking the destination URL. It seems like you are ok without it for now?

**Comment by randimays** [comment]
Update: This has been taking longer than anticipated for a few reasons:

1. content-build running locally has been bogging down (even with a slimmed-down data pull) and running into memory issues. This has made iteration / trial & error move slowly
2. I needed to determine how to distinguish different types of events (VAMC only vs. VAMC/Outreach and Outreach only) and update the GraphQL and this took a while (see number 1)
3. I need the "pretty" version of the VAMC name (i.e. "Portland health care") and the only place we currently have that is in the page breadcrumbs. Pulling it from there seems like a brittle approach (and has proven technically challenging, again see number 1); I have a question in Slack ([here](https://dsva.slack.com/archives/C52CL1PKQ/p1713285657832429)) to Christian and Daniel about whether we can cleanly add that data on the Drupal side for the FE to display.

**Comment by FranECross** [comment]
> @FranECross They are both using va-link (which has the baked-in analytics), but we're still lacking the destination URL in that baked-in data. It seems like you are ok without it for now?

Thanks, @randimays ! I am okay with it for now, since they are (I believe) working on adding destination in their current or next sprint.

**Comment by randimays** [comment]
Putting this into Blocked. We need a bit of Drupal work to send back the VAMC facility name (i.e. "Portland health care") so we can display it for this link:
> Want to see more events offered at Example VAMC? [Go to VAMC events calendar]

Brief Slack discussion: https://dsva.slack.com/archives/C52CL1PKQ/p1713285657832429

@FranECross to create the Drupal ticket for this work

**Comment by dsasser** [comment]
@FranECross @randimays it looks like we might be able to get to the facility name by adding it to the graphql (it took me taking a much closer look at this to see that this was possible). Randi I pushed a commit to your branch that should bring it in. If you have questions or problems using it let me know, but we should be able to close #17888 as a no-op if the graphql change ends up being what we need.

**Comment by FranECross** [comment]
Removed Blocked label per Daniel completing/releasing the work needed for this ticket.

**Comment by randimays** [comment]
Putting into Blocked temporarily as we're still not getting the correct data from Drupal with the added GraphQL. Daniel is helping to troubleshoot but content-build performance issues are slowing us down tremendously. This is at risk of not closing before end of sprint.

Slack thread for troubleshooting: https://dsva.slack.com/archives/C52CL1PKQ/p1717618099488709

**Comment by randimays** [comment]
Pulled out of blocked. Daniel helped pull more GraphQL data to get the right VAMC name. Thanks @dsasser!

**Comment by randimays** [comment]
This ticket is awaiting a11y and design review. Those are not marked as ACs on this ticket but since we had some design contributed for this ticket, I thought it'd be good to run it by Jordan and Laura. This will carry over to the next sprint since we won't make the prod deploy for today.

**Comment by thejordanwood** [comment]
@FranECross @randimays [I commented this](https://github.com/department-of-veterans-affairs/content-build/pull/2015#issuecomment-2161459621) on the PR, but am going to add this here for visibility. I think there may be some confusion on what needs to be implemented here.

> I had to look into this to refresh my memory. I think we landed on a different treatment than https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15766 suggests. The [Outreach and Events Figma file](https://www.figma.com/design/SbGKt6EhjlHAvJOc9ENXow/Outreach-and-Events?node-id=40-1584&t=vfRPow5cEONXgU5k-1) shows that we should add a header and the links should be the default styling.
> 
> Timeline of how this evolved:
> 
> - https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15766 had a Mural board with IA suggestions. https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15766#issuecomment-1834652552 on the ticket shows that new copy was going to be suggested.
> - https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16323 is the ticket where new copy was suggested
> - https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15946 is the ticket where I did the design work and edited the copy a bit more. The Figma file is linked in that ticket as well. Amanda approved this, so it's probably the one we should go with.

**Comment by randimays** [comment]
@thejordanwood Gotcha; I'll make the updates! Thank you.

**Comment by FranECross** [comment]
Thank you, @thejordanwood and @randimays ! BTW I added a11y and design review items to the AC.

**Comment by randimays** [comment]
This was delayed by the code freeze for the Juneteenth holiday and some content-build production deploy issues. But now these changes are in production and they have been successfully verified! Closing as complete.
