### ISSUE TITLE
[CONSIDER] Editors can easily share link to info from service accordion

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#15760]
## Description or Additional Context 
VBA Regional Office usability findings included a recommendation to consider linking to content in accordions that didn't require editors to understand HTML.

In #14981, Jordan suggested "we would hyperlink similar to how it works on the VA design system pages. When you hover over a header, you see a hyperlink symbol next to it. We could use that behavior on accordions here too."

This work is to consider options for sharing information from accordions in a simpler way for editors.

## Acceptance Criteria
- [ ] Testable_Outcome_X
- [ ] Testable_Outcome_Y
- [ ] Testable_Outcome_Z
- [ ] Requires design review
- [ ] Requires accessibility review

**Comment by mmiddaugh** [comment]
Current process for sharing a deep link requires finding the ID of the accordion using the browser inspector. 
The steps are documented in the KB article, [How to create a deep link to accordion content](https://prod.cms.va.gov/help/how-to-create-a-deep-link-to-accordion-content) (requires network connection)
