### ISSUE TITLE
Create tests for alt text validation

### ISSUE THREAD

**Issue by edmund-dunn** [department-of-veterans-affairs/va.gov-cms#15783]
## User Story or Problem Statement
Create tests that test hard and client-side validations for the alt text field. Test should test the alt text functionality in the /media/add/image page and test all three new validations. 

- Alt text input field is over 150 characters.
- Alt text includes any of the following file extensions: .png .gif .jpg .jpeg
- Alt text contains any of the following phrases “image of”, “photo of”, “graphic of”, or “picture of”.

## Acceptance Criteria
- [ ] Test character limit, client-side, and hard validations.
- [ ] Test no file names, client-side, and hard validations.
- [ ] Test no redundant phrases, client-side, and hard validations.

## Team
Please check the team(s) that will do this work.

- [x] CMS Team
- [ ] Public Websites
- [ ] Facilities
- [ ] Accelerated Publishing

**Comment by BerniXiongA6** [comment]
Hey @edmund-dunn @tonytaylor -- will tee this one up for us to discuss at backlog refinement -- thanks! cc: @ndouglas @EWashb

**Comment by ndouglas** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VAgov-CMS-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/15783?planning-poker) with Zenhub @edmund-dunn @JunTaoLuo @tonytaylor

**Comment by tonytaylor** [comment]
We're in good shape with some lovely tests. Will be working with @JunTaoLuo tomorrow to clean up some commits.  Closed by EOD 11/22.

**Comment by BerniXiongA6** [comment]
Since we've reopened to only have the PR reviewed by UX and a11y, and merged when approved -- I'm going to consider this as 2 points for Sprint 98. cc: @maortiz-27-80

**Comment by BerniXiongA6** [comment]
Will this get reviewed adn closed soon? Please advise @tonytaylor @laflannery @BlakeOrgan -- cc: @maortiz-27-80

**Comment by laflannery** [comment]
@BerniXiongA6 Blake and I both already reviewed - our comments are on the PR:
- [My review](https://github.com/department-of-veterans-affairs/va.gov-cms/pull/15787#pullrequestreview-1760365618)
- [Blake's review](https://github.com/department-of-veterans-affairs/va.gov-cms/pull/15787#pullrequestreview-1762941186) (he had one minor edit)

So I think the only thing left to do would be to update the link Blake pointed out

**Comment by BerniXiongA6** [comment]
Thanks @laflannery @BlakeOrgan -- hey @tonytaylor would you know when you could get this final change completed ? cc: @maortiz-27-80

**Comment by tonytaylor** [comment]
@BerniXiongA6 this will be wrapped up a bit later this morning.

**Comment by BerniXiongA6** [comment]
@edmund-dunn do we know if this one got reviewed/QA'ed? Could you help @maortiz-27-80 and me to decipher whether we could close it?
