### ISSUE TITLE
Generate Next Build Preview consumer

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#15799]
## Requirements

We need a Drupal Consumer to use with Next Build Preview, so that Next Build can authenticate to the CMS to display draft content.

```[tasklist]
### Acceptance criteria
- [ ] A consumer is created in the CMS for use by Next Build Preview
- [ ] Relevant values in the consumer are also stored in AWS SSM.
```

## Background & implementation details

Consumers are managed in the CMS here: https://prod.cms.va.gov/admin/config/services/consumer

Consumers are content entities, and so are database-managed. This means that the Next Build Preview consumer should be generated on Production and allowed to filter down to other environments. 

* Label: 'Next Build Preview Consumer'
* Client ID: can be random, but should be noted for storage
* User: Assign to the Next.js user
* New Secret: can be random, but should be noted for storage
* Scopes: select 'Next.js'

Other values can be left empty. 

```[tasklist]
### Implementation tasks
- [ ] Use this if it helps you or feel free to delete.
```

**Comment by tjheffner** [comment]
The Consumer has been created here: https://prod.cms.va.gov/admin/config/services/consumer

the Client ID was generated randomly by Drupal, the secret was generated randomly with `openssl rand -hex 16`

these values are stored in AWS Parameter Store here: 
`/cms/consumers/next-build/client_id` & `/cms/consumers/next-build/client_secret`

next-build will use them as values for these environment variables:
```
DRUPAL_CLIENT_ID=
DRUPAL_CLIENT_SECRET=
```
