### ISSUE TITLE
Design: Update display of "characters remaining" on text fields

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#15797]
## User Story or Problem Statement
From #14889:
How we display characters remaining on text fields - For consistency, these should say "xx characters remaining." This is how it's displayed in the CMS design system. This can be seen [next to this comment](https://www.figma.com/file/aKdT4weNNthDxb3r6MolEh?node-id=167:819&mode=design#590435939) in the Figma file.

## Acceptance Criteria
- [ ] Testable_Outcome_X
- [ ] Testable_Outcome_Y
- [ ] Testable_Outcome_Z
- [ ] Requires content review
- [ ] Requires accessibility review

**Comment by jilladams** [comment]
@thejordanwood @omahane If we know how this characters remaining treatment works on other field types, is the work here just to catch up the VBA comps and make sure that's present everywhere it applies, and make sure Drupal is aligned? Wondering if this is actually a no-op at this point.

**Comment by davidmpickett** [comment]
All the known character character issues for VBA are ticketed indivudally and tracked in #16073
