### ISSUE TITLE
Update help text for phone number fields on Phone Number paragraph type

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#15803]
## User Story or Problem Statement
From #14889: Add help text: Choose a phone number type.

Phone number fields - Help text changes would impact multiple places. This applies to the Type, Phone number, Extension number, and Label fields. Suggested changes can be seen starting [with this comment.](https://www.figma.com/file/aKdT4weNNthDxb3r6MolEh?node-id=180:806&mode=design#590436716)

## Acceptance Criteria
- [x] Help text on the phone number fields has been updated to match design
- [ ] QA has been done on multiple instances of this field
- [ ] Requires design review
- [ ] Requires accessibility review

**Comment by davidmpickett** [comment]
This is a simple config change that is within my scope of practice as a Drupal Site builder

**Comment by davidmpickett** [comment]
Verified on prod
![Screenshot 2024-07-22 at 3 12 24 PM](https://github.com/user-attachments/assets/f57dc33f-1496-4f18-9571-93a11d5737bb)
