### ISSUE TITLE
Env variables for authentication to BRD CMS instances are available on EKS Next Servers

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#15801]
## Requirements

Ensure `DRUPAL_CLIENT_ID` and `DRUPAL_CLIENT_SECRET` values are available as environment variables to the EKS Next Build servers, so that those values can be used to authenticate to their associated CMS.

```[tasklist]
### Acceptance criteria
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16857
- [x] Each Next.js instance is able to display draft content from its associated CMS instance.
- [x] Env variables maintain their values through multiple container deploys
- [x] public.key and private.key must also be available for authentication to work.
```

## Background & implementation details

```[tasklist]
### Implementation tasks
- [ ] Use this if it helps you or feel free to delete.
```

**Comment by timcosgrove** [comment]
I am reasonably certain this is just setting environment variables for the EKS-based Next.js servers.

**Comment by tjheffner** [comment]
Confirmed that environment variables are present and that authentication works between BRD & EKS preview servers!

- logged into https://test.staging.cms.va.gov/
- enabled the next preview feature flag at https://test.staging.cms.va.gov/admin/config/system/feature_toggle
- edited a story node https://test.staging.cms.va.gov/node/66634/ & saved as `draft`
- visited preview from the latest revision tab, saw draft content successfully



![Image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/11279744/e2c021c0-a81a-4070-ab05-1df1a26bddf8)
![Image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/11279744/087bf77b-f47e-4866-8156-a71fb54fee2c)
