### ISSUE TITLE
Change Management: CLP image ratios

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#15806]
## User Story: 
As an Editor of a CLP, I have information to effectively/efficiently create a CLP. 

## Description
CLP hero image dimensions are changing to 1:1. 

* Need to figure out if editors need to review the image before we change it on their behalf  -- [Google spreadsheet](https://docs.google.com/spreadsheets/d/1Vw1Ken60Zjz-3BLexbHBITcHUh7dzbr5K10IwbTJicQ/edit#gid=0)  that documents Editors
  * Could send out a Tugboat environment to top editors (creator / latest editor
  * Contacts from each Administration (VBA, VHA, VEO, NCA) - in the Governance PDF - need to be broadcast to these leaders, as FYI of the dimension change. 

## KBs
CLPs have a few KB articles: 

1.  https://prod.cms.va.gov/help/campaign-landing-pages/how-to-create-a-new-campaign-landing-page -- no reference to images, and larger overhaul being addressed in #15384
4.  https://prod.cms.va.gov/help/campaign-landing-pages - no reference to the images
5.  https://prod.cms.va.gov/help/campaign-landing-pages/how-to-manage-campaign-landing-pages - 1 image reference. Added to ACs.

### Published CLPs reachouts
- [X] During FE work, preview the [existing published CLPs](https://prod.cms.va.gov/admin/content?title=&type=campaign_landing_page&moderation_state=editorial-published&owner=All)  in Tugboat to verify which have problems after the 1:1 change
  - [X] Jordan update images for those to use 1:1 ratio & provide screenshots (we can upload to Tugboat)
- [X] Fran / Jill reach out to Editors of those CLPs for sign off on the updated image and log approvals. (Migrate the Gdoc to Sharepoint for this?)

### Administration reach-out
- [x] Stakeholders who need to be notified from each administration
  - [x] Heather Santos 👉🏼**Approved**
    - [x] National Buddy Week >Recommended sunsetting
    - [x] Veterans Experience Action Center (VEAC) > Adjust image ratio
    - [x] Veteran Trust in VA > Adjust image ratio
- [x] John Santos 👉🏼**No response yet; Fran sent another email on 12/6 AM PT**
  - [x] How Veterans Can Register to Vote > >Recommended sunsetting or updating photo
  - [x] Recognizing LGBTQ+ Veterans During Pride Month > Adjust image ratio
- [x] Danielle Thierry 👉🏼**Approved**
  - [x] Network of Support > Adjust image ratio
  - [x] Protecting Veterans from fraud > Adjust image ratio
  - [x] End-of-Life Benefits > Adjust image ratio
- [x] Steve Tokar 👉🏼**Approved**
  - [x] Flu and COVID-19: one visit, two vaccines > Adjust image ratio
  - [x] Emergency room, 911, or urgent care? > Adjust image ratio
- [x] 👉🏼Verified this one no longer displays in PROD: [It’s Time to “VAX to the MAX!”](https://prod.cms.va.gov/initiatives/flu)
- [X] Administration stakeholder Email (have timebox in the email for them to respond): 
  - [X] Draft provided for DaveC review, to notify administration stakeholders of the upcoming change
    - We intend to execute on this change unless you have objections.
    - For VBA, VEO, VHA: Messaging is you either own or support others who own CLPs. 
    - For NCA is: NCA is able to make CLPs but don't have any currently published. If you do create CLPs in future, we've changed Hero image requirements.
    - For CAIA: Messaging is: are you able to approve this change or do you need to review with stakeholders? (If you have issues, who makes the call about what image to use instead at 1:1 ratio)
    - Timebox: ~ maybe 5 business days for their response to the recommendations - maybe Mon after Thanks?; monitor bouncbacks; other considerations from Dave
  - [x] After modified image sign off, email sent to stakeholders to advise of the upcoming change

### KBs
- [x] KB updates
  - [x] https://prod.cms.va.gov/help/campaign-landing-pages/how-to-manage-campaign-landing-pages - Update mention of "large full-width image" and save revision as Draft
- [x] Launch plan is drafted into Epic body (#15807 )
- [x] Launch plan reviewed / signed off with DaveC

**Comment by FranECross** [comment]
Note that this is on hold until sometime after Veteran's Day. @jilladams and @FranECross will collaborate/sync on the ticket, etc.

**Comment by jilladams** [comment]
Dave Conlon slack note: https://dsva.slack.com/archives/C52CL1PKQ/p1698756446562149?thread_ts=1697750518.017569&cid=C52CL1PKQ
Some notes here around change management:

- I got a little confused in the thread as to which pages had images at-risk. It looks like there may have been a shift?
- We don't "own" this content - it's managed by our stakeholders. So we need to be careful about making changes carte blanche. We need to audit the pages and determine the owners which may be different than the last person who touched the page in order to figure out who needs to be engaged.
- In some cases, CAIA has directed folks to create CLPs, so let's double-check this list with their stakeholders. One that comes to mind is the End of Life page, Flu and COVID, etc. So I think it would behoove us to check with CAIA so that we know what, if any, bears we may be poking.
- There may be an opportunity to ask folks if the page should be taken down. For instance: https://www.va.gov/initiatives/vote/. Campaigns should generally be time-bound and this page hasn't been updated for over a year (6102 Policy) and the image itself references 2021.
- There may be an opportunity for us to look at analytics, but more importantly for us to ask stakeholders how they have measured success in prep for CLP v2.
- We desperately need to revise https://prod.cms.va.gov/help/how-to-upload-images that explains aspect ratios to people and encourages them to set the aspect ratios when they upload.

**Comment by FranECross** [comment]
@thejordanwood Please make 1:1 square images based on the list on the attached google sheets list so we can approach the editors to get buy in.

**Comment by jilladams** [comment]
XLS version of the google doc mentioned in ticket body, for reference: [CLP Image aspect ratio Editors.xlsx](https://github.com/department-of-veterans-affairs/va.gov-cms/files/13245397/CLP.Image.aspect.ratio.Editors.xlsx)

**Comment by jilladams** [comment]
https://docs.google.com/spreadsheets/d/1Vw1Ken60Zjz-3BLexbHBITcHUh7dzbr5K10IwbTJicQ/edit#gid=0 - Updated with Dave's recommendations about which CLPs need to be sunset ideally, vs updated with new images.

**Comment by thejordanwood** [comment]
@jilladams @FranECross I added another column to the [google sheet](https://docs.google.com/spreadsheets/d/1Vw1Ken60Zjz-3BLexbHBITcHUh7dzbr5K10IwbTJicQ/edit#gid=0) that provides tugboat links from [the FE ticket](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15632) of the pages I believe are good as is. 

These are the 3 new images for the pages noted in the spreadsheet. 

1. Sign in securely with Login.gov ([current tugboat link](https://web-3n6ncfwdu1vtlq90kzrj36nofdlqim1e.demo.cms.va.gov/initiatives/sign-in-securely-with-logingov/))

![sign_in_securely](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/104526584/d6280c48-bac5-4204-b6b4-62c1f2ea3f54)


2. End of life benefits ([current tugboat link](https://web-3n6ncfwdu1vtlq90kzrj36nofdlqim1e.demo.cms.va.gov/initiatives/end-of-life-benefits/))

![end-of-life](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/104526584/4f15570c-2296-43f3-b02b-f5b505a3a27e)


3. Flu and COVID-19: one visit, two vaccine ([current tugboat link](https://web-3n6ncfwdu1vtlq90kzrj36nofdlqim1e.demo.cms.va.gov/initiatives/covid-flu/))

![Flu_and_covid](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/104526584/f393afb5-307c-465a-a9ac-fb30d2f68537)

**Comment by jilladams** [comment]
1. BE work is compelte and PR is approved but marked Do Not Merge
2. FE work is complete and PR is approved (but marked Do Not Merge). 
3. Jordan's changes are staged in Tugboat, we can preview the affected CLPs.  A link to each has been added to the [Google sheet](https://docs.google.com/spreadsheets/d/1Vw1Ken60Zjz-3BLexbHBITcHUh7dzbr5K10IwbTJicQ/edit#gid=0)

@FranECross this is ready for email drafts to the CLP editors. Holler if you want to discuss / collaborate.

**Comment by jilladams** [comment]
@FranECross I made some updates in the Google doc email drafts: https://docs.google.com/document/d/1tKLjmSXbu5sxv5eepubVOLeOrOe3SIEui8pKYUs8Ne8/edit. Looking through this also brought up a question for Randi re: how the image handling in working in her Tugboat currently, logged here: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15632#issuecomment-1815419474. Holler with any questions!

**Comment by FranECross** [comment]
@jilladams Great updates to the emails; thanks so much for the review and edits, as well as the questions/comments to Randi!

**Comment by jilladams** [comment]
Emails sent on 11/29

**Comment by FranECross** [comment]
Received feedback from all but John Santos. Fran to follow up week ending 12/8

**Comment by jilladams** [comment]
1:1 images staged for launch.

FE code will deploy on Fri 12/8. The following 4 CLPs will need to have draft revisions published after code ships (I'll do that): 
https://prod.cms.va.gov/node/56090/latest
https://prod.cms.va.gov/node/43991/latest
https://prod.cms.va.gov/node/55104/latest
https://prod.cms.va.gov/node/51214/latest

The remaining 4 are using images where we just updated the 1:1 image crop on the media item, so should Just Work (TM) when code goes live:
https://prod.cms.va.gov/initiatives/protecting-veterans-from-fraud
https://prod.cms.va.gov/initiatives/veterans-experience-action-centers
https://prod.cms.va.gov/initiatives/veteran-trust-in-va
https://prod.cms.va.gov/initiatives/emergency-room-911-or-urgent-care
