### ISSUE TITLE
Post_api needs to accept a 202 response.

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#1581]
The lighthouse team is adding a new response for if we try to send a facility that does not exist
They will return a 202 response when we send them a facility that does not exist in their system.

post_api should be able to handle a 201 or 202 as though it was a 200, but would be a good idea to log specifics about the request, but then remove the item from the queue.

**Comment by oksana-c** [comment]
"contributable" approach would be to dispatch an event with a response code being a property. Then, in custom event subscriber, produce the log specific to our use case.
