### ISSUE TITLE
Banners work correctly for Lovell pages

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#15826]
## Requirements

Banners need to display correctly on Lovell pages, so that editors of those sections can communicate with their users.

```[tasklist]
### Acceptance criteria
- [ ] CMS API Endpoint for banners is updated to handle Lovell correctly
- [x] All banner types can be assigned to Lovell pages and display correctly
- [x] Banners continue to display correctly on non-Lovell pages
```

## Background & implementation details

At a minimum this involves updates to the Banner custom API endpoint; it may also involve front-end updates. 

The set of banners that should be tested to work:
* Full Width Banner Alerts | banner
* Facilities Banners | full_width_banner_alert
* Promo banners | promo_banner

```[tasklist]
### Implementation tasks
- [ ] Use this if it helps you or feel free to delete.
```

**Comment by schiavo** [comment]
Tested Full Width Alert|banner which did not display but this is not on our list here

**Comment by schiavo** [comment]
Tested VAMC System Banner Alert with Situation Updates | full_width_banner_alert

Banner successfully displays

![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/7717261/0a309501-ddb9-4e07-94f3-6f243e22f007)

**Comment by schiavo** [comment]
@timcosgrove these three banners are working properly. Tested locally with latest next and cms.

**Comment by tjheffner** [comment]
Confirmed
