### ISSUE TITLE
Income Limits: 2022 data returning empty gmt threshold for some zip codes 

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#15835]
## User Story or Problem Statement
As an income limits API user, I expect to receive a gmt threshold when I provide zip/year/dependents data to the income limits API.

## Description or Additional Context 
https://dsva.slack.com/archives/C52CL1PKQ/p1698156487939009

Benefits team reported: 
> We're getting an empty object for the gmt threshold from the income limits response and we're trying to narrow down the issue. > We're hitting the endpoint with the following zipcode/year/dependents: 23663/2023/0 and getting the following response.
`{"data":{"pension_threshold":16037,"national_threshold":39849,"gmt_threshold":{}}}`

> We're getting mostly populated responses, but have a list of zip codes that seem to be having some trouble: 
```
["21216",
 "23664",
 "23452",
 "00662",
 "23322",
 "23605",
 "23223",
 "23454",
 "23666",
 "23325",
 "23220",
 "23860",
 "23504",
 "23505",
 "59602",
 "23320",
 "23462",
 "23704",
 "22314",
 "23321",
 "23703",
 "23453",
 "22304",
 "23451",
 "70807",
 "70814",
 "23509",
 "23456",
 "23701",
 "23834",
 "23851",
 "22401",
 "23502",
 "96799",
 "21239",
 "23323",
 "23434",
 "70817",
 "46360",
 "23455",
 "23510",
 "23435",
 "21217",
 "23608",
 "23517",
 "23464",
 "70820",
 "23503",
 "23707",
 "23222",
 "21218",
 "24153",
 "22902",
 "24333",
 "24112",
 "21230",
 "70815",
 "23663",
 "70818",
 "24501",
 "23513",
 "24013",
 "70810",
 "21229",
 "23606",
 "23224",
 "23437",
 "24502",
 "23508",
 "46350",
 "24017",
 "23602",
 "23607",
 "23523",
 "23803",
 "00957",
 "22903",
 "21224",
 "23324"]
```

## Engineering notes
The year passed in is meant to be calendar year and the BE handles the "year - 1"for the data: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/income-limits-app/engineering/technical-architecture.md#geographic-means-test-gmt-threshold
> EFFECTIVEYEAR = benefit year - 1

## Acceptance Criteria
- [ ] zip/year/dependents data input returns a valid gmt threshold
- [ ] Invalid inputs return an error message
- [ ] Any additional tickets required to handle specific zip codes are generated

**Comment by jilladams** [comment]
Daniel can help with local vets-api data setup as needed.

**Comment by jilladams** [comment]
@chriskim2311 I _think_ vets-api deploys daily based on https://depo-platform-documentation.scrollhelp.site/developer-docs/deployments and clicking through to the vets-api EKS stuff. I notified the bug reporter in Slack that this shipped: https://dsva.slack.com/archives/C52CL1PKQ/p1700261593641649?thread_ts=1698156487.939009&cid=C52CL1PKQ, so if this gets verified would you go ahead and close ticket next week? Thanks!

**Comment by chriskim2311** [comment]
@jilladams Thanks for that, I did not know that we had that for vets-api. I have tested this on prod and it looks good going to close!
