### ISSUE TITLE
Rework PagerDuty rotation

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-cms#15854]
## Description

Time to get Eric, Ari, and Tolase involved in this 😎 

## Acceptance Criteria

- [x] Ari, Tolase, and Eric have been added to the PagerDuty rotation.
- [ ] Preliminary schedule has been circulated and adjustments made as needed.

**Comment by EWashb** [comment]
I am working with Platform to confirm enough seats exist to add folks who aren't already in. If you don't hear from me about this in a couple of days, please remind me to check again!

**Comment by ndouglas** [comment]
@EWashb I still need a seat for Ari and a seat for John, I believe. Tolase and Eric are taken care of 🙂

**Comment by EWashb** [comment]
@ndouglas did you have an existing ticket or thread anywhere yet?

**Comment by ndouglas** [comment]
https://dsva.slack.com/archives/CBU0KDSB1/p1699283761735289 😎

**Comment by EWashb** [comment]
No problem. I don't think we have the PagerDuty access process documented anywhere so I wanted to see what you might have done so far and then I could pick it up from there.

**Comment by BerniXiongA6** [comment]
Done per @ndouglas
