### ISSUE TITLE
Preview Server requests unexpectedly and intermittently redirecting HTTP -> HTTPS, breaking preview experience for editors.

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-cms#15852]
## Description

See [here](https://dsva.slack.com/archives/CDHBKAL9W/p1697059698606299).

This is... thorny. It's intermittent. I think there's something caching HTTP responses and acting on them, but I don't know what that might be.

Briefly:
- Drupal formats and outputs a link to the preview server on certain nodes. This looks like (abbreviated): `<a href="http://preview-prod.vfs.va.gov/preview?nodeId=62271" ref=noopener" target="_blank">Preview</a>`. Note that this is an HTTP URL.
- Upon clicking the link, a new tab will open (expected), but it appears to request `https://preview-prod.vfs.va.gov/preview?nodeId=62271`. This request will fail, returning "404 not found" because the preview server isn't accessible via HTTPS (no listener in place on the ALB, not sure if because of security issues or what).
- If this is retried, the same behavior will recur, i.e. it does not appear random on a per-request basis.
- If it is not retried for some time (several minutes, e.g. ~20 or so), the behavior does not change.
- Directly requesting the `http` version of the page seems to "unstick" this in some way. It is not redirected to `https`. Subsequent clicks of the "Preview" link will find the HTTP version of the page successfully, and not result in an error.

## Acceptance Criteria

- [ ] This stops happening.

**Comment by BerniXiongA6** [comment]
Hi @ndouglas don't forget to point this! I'll change it to "To Do" pipeline but I'll leave the "needs refining" label on that you can remove when you've pointed. Thanks!

**Comment by ndouglas** [comment]
Appears to be a Chromium bug: https://bugs.chromium.org/p/chromium/issues/detail?id=1492782&q=component%3AInternals%3ENetwork%3ESSL%3EHttpsUpgrades&can=2

https://github.com/department-of-veterans-affairs/va.gov-cms/assets/1318579/8eabec26-917c-4484-b9c1-a1d88551e5b7

**Comment by ndouglas** [comment]
I figured this out, but I want to provide a better solution. I'll do that in a followup ticket.
