### ISSUE TITLE
Apply and test workflows for VBA Facility content type

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#15869]
## User Story or Problem Statement
VBA editor permissions and a second workflow were implemented in #11334. This is to test the implementation of the workflows for VBA editors.

## Acceptance Criteria
- [x] Restricted archive workflow is applied to VBA Facility
- [x] Cypress tests that the facility cannot be reanimated (replicate Vet Center tests)

## QA Steps (draft)
As a local facility editor and a national editor
- [ ] edit a Facility
  - [ ] save in edit
  - [ ] save in review
  - [ ] save in approve
  - [ ] save in publish
  - [ ] save in archive
  - [ ] restore from archive to published
  - [ ] save in archive
  - [ ] restore from archive to draft

**Comment by xiongjaneg** [comment]
Related comment on archived to published workflow:
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13800#issuecomment-1745907030

**Comment by jilladams** [comment]
@xiongjaneg flagging per convo with Christian today: this is turning out to be an 8 point ticket, so some lower level Drupal things in sprint might be at risk. Will spin up a mid-sprint SLack thread tomorrow to check in more deeply about where we're at.

**Comment by xiongjaneg** [comment]
As vba_publisher in staging, able to save as draft, in review, approved, and published. Don't have access to archive a facility, as expected.

**Comment by omahane** [comment]
# Advice for next time
When moving a content type to a different workflow, to be thorough, it's best to do the following:

1. Remove the content type from its current workflow
2. Add the content type to its new workflow
3. [Change the config dependencies](https://github.com/department-of-veterans-affairs/va.gov-cms/pull/16395#discussion_r1430165958) on the content types form display to the new workflow
4. Create a hook_update_N that uses the `_va_gov_workflow_change_content_type_workflow` in `va_gov_workflow/va_gov_workflow.install`

**Comment by jilladams** [comment]
Would love to get that documented somewhere logical for future. Ideas that come to mind about where: 
* In the Workflow form where we set the Workflow on a content type? Is that out of bounds? 
* If CMS has any documentation about workflows, add it there? (Don't know that they do. If they don't maybe we could add to CMS repo docs somewhere?) 

@omahane if you have other ideas, holler.
