### ISSUE TITLE
Create plan for D10 Announcement using Sitewide Alerts

### ISSUE THREAD

**Issue by BlakeOrgan** [department-of-veterans-affairs/va.gov-cms#15862]
## User Story or Problem Statement
We will need to create two different [Sitewide Alerts](https://prod.cms.va.gov/admin/content/sitewide_alert) to announce the Drupal 10 upgrade to all CMS editors. One to display a couple days before the upgrade happens to let people know that it's coming and another once the upgrade has happened.

## Description or Additional Context 
- Both alerts should be informational, not warnings.
- Both alerts should be dismissable.
- Determine the scheduling of both of the alerts. How long should they display before and after the launch?
- Do not limit visibility by page.
- Create the title for both alerts.
- Create the body of both alerts.
- Refer users to someone if they notice any weirdness after the D10 update. Determine who that should be and how users should get in contact with them.
- Determine what happens if there is another alert that shows while these alerts are showing and if any action is needed.

## Acceptance Criteria
- [x] A plan for a sitewide alert has been created that displays before the launch of D10
- [x] A plan for a sitewide alert has been created that displays after the launch of D10

## Team
Please check the team(s) that will do this work.

- [x] CMS Team
- [ ] Public Websites
- [ ] Facilities
- [ ] Accelerated Publishing

**Comment by EWashb** [comment]
I cannot remember if when an editor creates a help desk ticket if they can assign a label, but if they can we can add a label that aligned with reporting an issue from the upgrade.

**Comment by BlakeOrgan** [comment]
### Pre-launch Alert:
**Name:** Drupal 10 Pre-launch Announcement
**Alert Style:** Informational
**Alert Title:** Text editing improvements are coming soon!
**Alert Message:** Beginning on [launch date] you will see changes to rich text editors in the CMS that will include a better authoring experience as part of an upgrade to Drupal 10. Stay tuned for more information!
**Dismissible:** Yes
**Scheduling:** Once launch date is determined, this alert will need to go up seven days prior to the launch date. This alert should stay for the full seven days unless it is dismissed by the user.
**Page Visibility:** DO NOT limit page visibility. This alert should be viewable on all pages.
**Revision Information:** Upon creation of the alert, the revision information should read, “Creation of a sitewide alert to announce improvements to rich text editors that will be coming soon as part of the Drupal 10 upgrade.”
**Active:** Active for 7 days prior to D10 launch, unless dismissed by the user.
**Other notes:**

### Post-launch Alert:
**Name:** Drupal 10 Post-launch Announcement
**Alert Style:** Informational
**Alert Title:** Text editing improvements are here!
**Alert Message:** As of [launch date] we have made improvements to rich text editors across the CMS that include a better authoring experience as part of an upgrade to Drupal 10. [See what’s new!](https://prod.cms.va.gov/help/cms-announcements)
**Dismissible:** Yes
**Scheduling:** This alert should stay for a full seven days past the launch date unless it is dismissed by the user.
**Page Visibility:** DO NOT limit page visibility. This alert should be viewable on all pages.
**Revision Information:** Upon creation of the alert, the revision information should read, “Creation of a sitewide alert to announce improvements to rich text editors that have happened as part of the Drupal 10 upgrade.”
**Active:** Active for 7 days past the D10 launch, unless dismissed by the user.


### Other notes:
Note that the "See what's new!" link in the post-launch alert should direct to the [CMS Announcements](https://prod.cms.va.gov/help/cms-announcements) page. [The latest version of the CMS Announcements page](https://prod.cms.va.gov/node/6900/latest) will need to be published before activating the post launch alert so that the link directs to the relevant information. The CMS Announcements page gives more information about what is changing, who to contact if there are issues and how to contact them, as well as a link to read more about the updated rich text editors in depth.

**Comment by BlakeOrgan** [comment]
If multiple alerts are active at the same time, the alerts will stack. Since the deploy-alert is temporary and is only up for a short period of time daily, there will only be two alerts in times where the deploy alert is active and the D10 announcement has not been dismissed. Since the deploy alert is something that we should keep, there is no action needed.

**Comment by EWashb** [comment]
[Slack thread](https://dsva.slack.com/archives/CT4GZBM8F/p1700239129433249) about CMS announcement changes, etc. cc: @BlakeOrgan @laflannery @BerniXiongA6
