### ISSUE TITLE
Redirect Request for: Coudersport VA Clinic (Facility closed)

### ISSUE THREAD

**Issue by stefaniefgray** [department-of-veterans-affairs/va.gov-cms#15865]
### Instructions
(Note: This issue will be used from initial request through implementation to ensure all individuals working on this are notified of status updates.  Please do not create multiple issues to track different steps.)

See main ticket: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15816

- [x] Notify VA stakeholders as appropriate.
- [x] Link the related facility closure / rename issue.
- [x] Create a URL redirect in the [devops](https://github.com/department-of-veterans-affairs/devops) repo in `ansible/deployment/config/revproxy-vagov/vars/redirects.yml`
- [x] Add the "Awaiting redirect" flag to the facility node with a revision log message that includes a link to this ticket, preserving the node's current moderation state.
- [x] Redirects deploy weekly on Wed. at 10am ET, or by requesting OOB deploy (of the revproxy job to prod) in #vfs-platform-support. After deploy, validate that the URL redirect is deployed. (Note: In the event of a facility closure or a name change,  validate that this occurs before making the Lighthouse csv changes.)
- [x] Update this ticket with a comment that the redirect has been deployed.
- [x] Remove the "Awaiting redirect" flag on the facility node with a revision log message that includes a link to this ticket, preserving the node's current moderation state.

### Implementation date
When does this request need to be live: Whenever possible

### Redirects
| Current URL  |  Redirect Destination or New URL |
| ---  |  --- |
| https://www.va.gov/finger-lakes-health-care/locations/coudersport-va-clinic/ | https://www.va.gov/finger-lakes-health-care/locations/ |

## Use one of the following:
**Note: Canonical URL changes do not block the completion of the parent ticket. Once the URL redirect above has been deployed, the value to the Veteran is delivered. This ticket should be kept open until the URL change is verified, except in the case of a removal (as described below).**

#### URL removal example (update with actual ID and URL to remove)
| Facility API ID  |  Full VA.gov URL |
| ---  |  --- |
| vha_528QE | https://www.va.gov/finger-lakes-health-care/locations/coudersport-va-clinic/ |

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [ ] `Public Websites`
- [x] `Facilities`
- [x] `User support`

**Comment by jilladams** [comment]
Will deploy after sprint boundary.

**Comment by omahane** [comment]
Confirmed that the redirect has been deployed.
