### ISSUE TITLE
Respond to Lighthouse plans for Facility data in lower environments

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#15860]
## User Story or Problem Statement
Joseph Justice put forth some possible plans for lower environments and asked for feedback: [Slack thread](https://dsva.slack.com/archives/C02BTJTDFTN/p1697818036178129)

"From a high level, there are only a few possible directions we truly could go. The two options listed below we felt most suitable to dive deeper into.

FAPI implements synthetic data in Sandbox - CMS has their Sandbox environment connect to our Production environment so they can see Production data.
- Meets both sides needs in terms of Sandbox data.
- Your team still could get a full Production data record out of the API.
- The drawback would be that it only works for data reads. CMS would not be able to push any data if they needed to test something in the publication part of the system or they would be making changes to the real Production environment’s data.
-If the CMS test environment is allowed to write data, we could run into to contention or data errors.
- CMS would then require a different API key for their production and test environments that we would allocate different permissions.

Maintain Production data in Sandbox – Although the Lighthouse program has echoed moving production data out of Sandbox environments and making Sandbox strictly pertain with synthetic data.
- Have CMS update their queue so every message they publish to Production they also send a duplicate message to Sandbox.
- CMS already has a Sandbox key, which already has the publish functionality.
- CMS would need to add a second API call to each push.
- A possible pitfall is the reliance on one another to help maintain our test data.

We are still trying to determine the best path forward and looking for additional input from your team to help shape our recommendations. Ultimately, the final decision will be determined by the Stakeholders on how we proceed forward."

## Acceptance Criteria
- [x] Respond to the plans (shared at Nov. 7 sync with Lighthouse)

**Comment by jilladams** [comment]
@swirtSJW if you do intend to get to this before sprint end, could you pull into sprint officially in the Sprint field here?

**Comment by swirtSJW** [comment]
Still editing
> FAPI implements synthetic data in Sandbox - CMS has their Sandbox environment connect to our Production environment so they can see Production data.
> Meets both sides needs in terms of Sandbox data.
> Your team still could get a full Production data record out of the API.
> The drawback would be that it only works for data reads. CMS would not be able to push any data if they needed to test something in the publication part of the system or they would be making changes to the real Production environment’s data.
>-If the CMS test environment is allowed to write data, we could run into to contention or data errors.
CMS would then require a different API key for their production and test environments that we would allocate different permissions.


This one is problematic because it makes it impossible for our lower environments to push new data into the facility API and then have the front end (public facing website) read and build from that data.
If this model were in place previously, we would not have been able to roll out :
- facility operating statuses (when covid first landed)
- facility supplemental status (when covid specific statuses were required)
- new facility mental health numbers being pushed into Facility API.

**Comment by swirtSJW** [comment]
still editing

> Maintain Production data in Sandbox – Although the Lighthouse program has echoed moving production data out of Sandbox environments and making Sandbox strictly pertain with synthetic data.

> * Have CMS update their queue so every message they publish to Production they also send a duplicate message to Sandbox.
* CMS already has a Sandbox key, which already has the publish functionality.
* CMS would need to add a second API call to each push.
* A possible pitfall is the reliance on one another to help maintain our test data.

We could do this, on the CMS, but it seems fairly risky. 
- It doubles the number of pushes from CMS-prod.  
- It also creates an odd state where a production machine has to reach out to both LH-prod and LH-sandbox.  
- There could be a situation where LH-sandbox is running code that is newer than LH-prod, yet the CMS-prod would have to be capable of successfully to pushing to both.   If there were ever a data structure change, our CMS-prod would have to track both structures, which is not ideal and a bit nearly impossible for us to roll out (neither chicken nor egg would work).  
- It also creates a situation where we are trying to add new data from a CMS lower environment to test out both a push from CMS and a pull from content-build, but we can't guarantee it is there because someone making a change on CMS-prod just overwrote it.  This would create a lot of confusion and a decreased level of certainty on all lower environment consumers.

**Comment by swirtSJW** [comment]
MVP for CMS needs

## Prod
```mermaid
flowchart LR
    cms-prod[CMS Prod] --> lh-prod
    lh-prod((LH Prod)) -->|FAPI| content-build[VA.gov]
```

**Comment by swirtSJW** [comment]
The feedback was delivered to Lighthouse team at the 11/6/23 call.  Calling this done.

**Comment by xiongjaneg** [comment]
@xiongjaneg will share update with Michelle at Nov. 7 1:1 meeting
