### ISSUE TITLE
Provide fallback for pagers w/configurable heading

### ISSUE THREAD

**Issue by tonytaylor** [department-of-veterans-affairs/va.gov-cms#15882]
## Description

A few sprints ago, we introduced a feature that adds configurable headings to pagers. This feature attempted to address concerns detailed in #10111.  We've since found the implementation doesn't cover some non-trivial cases--pagers that manage taxonomy terms (#15099), and pagers that have no view component (#15201).

Provide a default heading in template in the event a view or a configurable view is not available.

## Acceptance Criteria
- [ ] Assert proper pager render on a page using a pager that has no associated view (A populated queue on /admin/config/post-api/queue will be provided)
- [ ] Assert proper pager render on the Health Care Service Taxonomy Overview Page

## Team
Please check the team(s) that will do this work.

- [x] CMS Team
- [ ] Public Websites
- [ ] Facilities
- [ ] Accelerated Publishing

**Comment by BerniXiongA6** [comment]
Hey @tonytaylor -- I see that you did end up creating this ticket as we discussed. I'll add it to Sprint 96, thanks!
