### ISSUE TITLE
Prevent Vet Center editors from creating Services for Facilities outside of their section

### ISSUE THREAD

**Issue by davidmpickett** [department-of-veterans-affairs/va.gov-cms#15906]
- As [Heather.Freegard@va.gov](mailto:Heather.Freegard@va.gov) of Augusta Vet Center, I was able to create and publish Albuquerque Vet Center - Workshops and classes
- It showed up on the node view of Albuquerque vet Center (was only on staging, so couldn't test preview)
- As [Joseph.Madrid@va.gov](mailto:Joseph.Madrid@va.gov) of Albuquerque, I was not able to edit this service (because it was in the Augusta section), but I was able to Remove with inline entity form which leads to a strange vestigial Service without a Vet Center in the name

![Screenshot 2023-10-30 090327](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/0d3e8f9b-b34e-49ec-9385-8290f037fd41)

![Screenshot 2023-10-30 091900](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/fdb39dbd-5f78-49e5-aa04-3025cb2eaac8)

[Slack context](https://dsva.slack.com/archives/C0FQSS30V/p1698675697238659?thread_ts=1698673764.071269&cid=C0FQSS30V)

Winnower should be javascripting, but could also add form validation on save to ensure that no mismatch between Section and Facility

**Comment by mmiddaugh** [comment]
[Link to related Slack thread](https://dsva.slack.com/archives/CDHBKAL9W/p1666893981346209)

More context - editors shouldn't be able to remove a required service. In this example, "Workshops and classes" is an optional service so an editor should be able to be remove it from their own Vet Center - but not from another editor's Vet Center. 

Related: 

- CMS Editors Should Not Be Able to Rename/Re-URL-alias VAMCs Facility Services #14136 (which extends the work done for Vet Centers in #11367 to VAMCs)
- Services should not be moved from one facility to another #4924

**Comment by davidmpickett** [comment]
Might be partially resolved by @omahane's work on #15901

**Comment by swirtSJW** [comment]
This is closed by https://github.com/department-of-veterans-affairs/va.gov-cms/pull/16663
