### ISSUE TITLE
PAW: Implement custom HTML for checkbox questions

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#15902]
## Description
As a follow up to #15268, we need to use the same custom HTML approach to update the checkbox questions. The markup should look like this (NOTE: I made an educated guess on the attributes and values on the checkbox markup based on the radio buttons):

```
<h1 class="form-question-header" id="form-question">Agent orange S2.2B, which locations did you serve in?</h1>
<fieldset aria-labelledby="form-question">
   <span class="usa-error-message" role="alert">
      <div class="form-text-error">
         <span class="usa-sr-only">Error</span>
         Select a response.
      </div>
   </span>
   <input type="checkbox" id="the_republic_of_vietnam_input" name="ORANGE_2_2_B" value="The Republic of Vietnam">
   <label class="form-label" for="the_republic_of_vietnam_input">
      <span>The Republic of Vietnam</span>
   </label>
   <input type="checkbox" id="the_waters_in_or_around_vietnam_input" name="ORANGE_2_2_B" value="The waters in or around Vietnam">
   <label class="form-label" for="the_waters_in_or_around_vietnam_input">
      <span>The waters in or around Vietnam</span>
   </label>
   <input type="checkbox" id="at_or_near_the_korean demilitarized_zone_(DMZ)_input" name="ORANGE_2_2_B" value="At or near the Korean Demilitarized Zone (DMZ)">
   <label class="form-label" for="at_or_near_the_korean demilitarized_zone_(DMZ)_input">
      <span>At or near the Korean Demilitarized Zone (DMZ)</span>
   </label>
</fieldset>    
```

## Acceptance Criteria
- [ ] H1 heading is outside the fieldset
- [ ] H1 receives focus when navigating between screens/questions
- [ ] The H1 is read out by screen readers as the label of the fieldset
- [ ] Error is announced when user tries to submit without selecting an answer
- [ ] User can use tab to navigate through the checkbox options
- [ ] User can use the space bar to check or uncheck each option
- [ ] Requires design review
- [ ] Requires accessibility review
- [ ] Re-activate cypress test for form validation

## Team
Please check the team(s) that will do this work.

- [ ] CMS Team
- [x] Public Websites
- [ ] Facilities
- [ ] Accelerated Publishing

**Comment by chriskim2311** [comment]
Verified in staging that that this is working as expected and has new markup
