### ISSUE TITLE
SPIKE: Verify that Benefit Hub and Benefit Detail Page left navs only show published content

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#15907]
## User story
AS A content editor
I WANT only published content to appear in the left nav of Benefit pages
SO THAT users are not exposed to broken links to draft content

## Description
There is a known issue in the FE where sometimes Draft content appears in the Left Nav, if parent menu settings are configured on Draft content. This is done in Menu settings on the node. 
 
The front-end should only show menu items for published nodes. 

According to Swirt, this was fixed for all Facility pages back when AdHoc held the Facilities FE contract (by Michael Bell Sherman? Check the name with Swirt.) We need to make sure the same fix is applied on Benefit pages. It may be, or it may not be. 

### Example
Any draft Benefit Detail page: https://prod.cms.va.gov/admin/content?title=&type=page&moderation_state=draft&owner=All

Where: 
* Menu settings: Provide a menu link = enabled
* Parent link is set to a Benefit hub 

Even with parent menu link set, Draft nodes should not appear in prod left nav.

## Additional notes
This issue came up originally with respect to Dark launches. 
* Thread: https://dsva.slack.com/archives/C52CL1PKQ/p1698685492633159?thread_ts=1698088955.272569&cid=C52CL1PKQ
* Dark launch docs: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/public-websites#shadow--dark-launches-of-content

We would ideally like to know also whether dark launched nodes that aren't built to production will / won't appear in production menus. Need to refine and figure out if that's reasonable to include in ACs or not.

## ACs

- [ ] Findings are documented in ticket re: whether Draft Benefit Detail pages will / won't appear in the left nav on those pages 
- [ ] Tickets are created for any work that can't be completed within the bounds of this spike

**Comment by FranECross** [comment]
@FranECross Check with CAIA to see if they have a checklist to ensure this is covered. Then close this.

**Comment by mmiddaugh** [comment]
@FranECross can this be closed?

**Comment by FranECross** [comment]
Good reminder, @mmiddaugh ! Closing.

**Comment by jilladams** [comment]
@FranECross do you know if the behavior was verified? (I don't)

**Comment by FranECross** [comment]
I do remember it was verified, but can't find the note/message confirming. Not sure why I didn't close the ticket back then.
