### ISSUE TITLE
Add Featured Content ("in the spotlight") to VBA Facility Content Type

### ISSUE THREAD

**Issue by davidmpickett** [department-of-veterans-affairs/va.gov-cms#15911]
## User story
As a VBA editor, I want to be able to feature a timely event or other information to get Veterans' attention.

## Background
Summary of business feedback/decisions from Office of Strategic engagement:
Design should include:
- 1 centralized/national spotlight with 2 local/editor level spotlights

Use the Featured Content paragraph from Vet Center

Also see [Laura's comment in 13799](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13799#issuecomment-1561057420)
- Featured content:
   -Change label to Spotlight content - this will help with consistency and lessen confusion by aligning CMS and FE naming conventions
- Section Header
  -Change label to Title - section is a term used very specifically for something else within the CMS so should be avoided whenever possible to refer to other things.
   -Keep field as required
   -Keep field as a text input
   -Keep character limit at 80

## Acceptance criteria
- [x] @davidmpickett drafts a clear spec for fields that need to change and reviews with @omahane before @omahane starts implementation
- [x] @davidmpickett assesses impact of changes on Vet Centers, and brings that to Product for approval / change management. If Laura's requested updates to fields used on Vet Centers becomes a blocker, that work should split off from adding the fields AS IS to VBA
- [x] VBA Featured Content is implemented in the same way as Vet Center Featured Content (with the following changes)
  - [x] Featured content label is changed to Spotlight content
  - [x] Section Header label is changed to title
- [x] There is one centralized content field and one local content field with cardinality of two
- [x] @davidmpickett QAs @omahane's PR
- [x] @laflannery a11y review

**Comment by davidmpickett** [comment]
This was listed as a comment on [14699](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14699#issuecomment-1724630053), but doesn't look like that ever got addressed or turned into a ticket

**Comment by davidmpickett** [comment]
See also Laura's comments on implementation https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13799#issuecomment-1561057420

**Comment by xiongjaneg** [comment]
[Michelle's comment in Slack about making sure 3 spotlights show](https://dsva.slack.com/archives/C0FQSS30V/p1698791124025089?thread_ts=1698790049.426689&cid=C0FQSS30V)

**Comment by davidmpickett** [comment]
Re updated description. To avoid confusion, I would narrow this to only the spotlight piece

- ~~Gov Delivery~~
- ~~national social media only (no local)~~
- 1 centralized/national spotlight with 2 local/editor level spotlights
- ~~AVA and VERA~~

Those other three items are handled by entirely different parts of the system.

**Comment by davidmpickett** [comment]
## Content spec (WIP)

### VBA Facility Content Type

### Centralized Content -  VBA - benefit office

**Comment by davidmpickett** [comment]
@omahane let me know if this spec makes sense or if you need any clarifications

**Comment by mmiddaugh** [comment]
if we're moving to "Spotlight", the Vet Center dashboard will also need to be updated. 
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/55411834/9e33bd16-aff8-4311-817d-7dd05cdcdd99)

**Comment by omahane** [comment]
@swirtSJW  @davidmpickett  Do you have time to look at this, as I've already run into some unexpected trouble.

![Screenshot 2023-11-15 at 2 04 56 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/766573/53f7f3a5-636f-49cf-8093-32e3c17d75dc)

I'm thinking that this means that other content types that are using the paragraph already have more than the number I'm trying to limit it to, which means that the limit is not set per content type but on the paragraph itself, which, as a shared field means that we are trying to butt in on someone else's content.

So, @Dave Pickett I think we might be already running into a change management issue with #1. We could always keep it unlimited and say that only the first two will ever show, but that's clunky. Or we make a new Paragraph. I'll bring this discussion to the issue.

**Comment by omahane** [comment]
> @swirtSJW @davidmpickett Do you have time to look at this, as I've already run into some unexpected trouble.

After a quick Zoom, I realized I unintentionally reused the field_featured_content rather than made a new field_local_spotlight.

Solved.

**Comment by davidmpickett** [comment]
Fun and not-at-all-confusing fact:
The "Featured content" field on VAMC Detail Pages and Benefits Detail Page uses the Rich Text and Page-Specific Q&A paragraph types rather than the Featured Content (soon to be Spotlight Content) paragraph type.

![Screenshot 2023-11-15 143337](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/e4a16c6a-9c9f-44e3-8d93-7f18062a32a1)

**Comment by laflannery** [comment]
I want to note that the screenshot above is Featured Content, **not** Spotlight content for VAMCs. It is separate from what is being worked on in this ticket. The spotlight content is on the VAMC System page and is quite different from the pattern being worked on here and [is documented in this issue](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13801) to be handled at future time

**Comment by davidmpickett** [comment]
Responding to @omahane [comment on the PR](https://github.com/department-of-veterans-affairs/va.gov-cms/pull/16145#issuecomment-1813393893) back on the main ticket for visibility.

How about: 

- "Spotlight content" - for fieldset that groups everything (could also be "In the spotlight"
- "National spotlight" - for the cc fetch fields
- "Local spotlight(s)" - for the paragraph type heading
- "spotlight" - for the add another button
- Let's move the help text about "add up two office activities" down closer to where the user would actually perform that action

![spotlights](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/d42160e1-a1a1-48fd-b7c1-af12df873f34)

**Comment by davidmpickett** [comment]
> I want to note that the screenshot above is Featured Content, **not** Spotlight content for VAMCs. It is separate from what is being worked on in this ticket. The spotlight content is on the VAMC System page and is quite different from the pattern being worked on here and [is documented in this issue](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13801) to be handled at future time

@laflannery Sorry for any confusion. I was documenting it _because_ this is the very thing that tripped up @omahane earlier today. He was accidentally reusing the field_featured_content, despite Featured Content being a totally separate thing from Spotlight Content.

**Comment by davidmpickett** [comment]
Made these charts for my own sanity 

## Stuff that's actually part of this ticket

Thing | Current Label | New Label | Machine name
-- | -- | -- | --
**Paragraph type** that powers "In the spotlight" on VBA and Vet Center | Featured Content | Spotlight Content | featured_content
**Entity Reference Field** that powers the above paragraph type for Vet Centers | Featured content | Local spotlight(s) | field_vet_center_feature_content
**Entity Reference Field** that powers the above paragraph type for VBA | Spotlight content | Local spotlight(s) | field_local_spotlight
**Label on the button** for adding another instance of paragraph type | Add Spotlight content | Add spotlight | I am unclear on what actually determines this label

## Not part of this ticket, but has confusingly similar names

Thing | Label | Machine name
-- | -- | --
Paragraph type that powers "In the _spotlight_" on VAMC  | List of link teasers |  list_of_link_teasers 
Entity Reference Field that powers _Featured Content_ for VAMC and Benefit Detail Pages | Featured content | field_featured_content 
Paragraph types that power _Featured Content_ for VAMC and Benefit Detail Pages | Rich text & Page-Specific Q&A | wysiwyg & q_a

**Comment by swirtSJW** [comment]
Something might have broken in the conflict resolution 
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5752113/86184b96-e7f0-4726-9b9b-b23b58601279)

I am looking into it.

**Comment by swirtSJW** [comment]
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5752113/20e8f7c4-d045-4864-bd05-6f9b43e697a3)
This location seems misleading.

**Comment by swirtSJW** [comment]
This has been merged https://github.com/department-of-veterans-affairs/va.gov-cms/pull/16145
Nice work @omahane

**Comment by davidmpickett** [comment]
Uploading video clip for async demo:
https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/2d33c0e1-827c-47e0-adf0-4fe7ca3e76ed
