### ISSUE TITLE
PAW: Tracking ticket for custom HTML

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#15910]
## Status
**[2024-02-08 Fran]** This ticket and its AC will be revisited after we receive Stakeholder changes (probably some time in April).

## Description
Because the current DS components did not provide the flexibility or accessible markup needed at the time of implementation, we built this using custom HTML. However the downside to this is that any design updates now aren't going to get pushed into our implementation.

This ticket is to
- make sure we are aware of this tech debt and keep an eye on any DST updates that might impact this and therefore require us to make independent updates (i.e. font sizes, colors, etc.)
- make sure we clean this up to use components when they are available so we can clean up this tech debt

### Relevant DST tickets:
- [Original ticket](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2142), which the follow ups were created from
- [Radio group component ticket](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2269)
- [Checkbox component ticket](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2270)

## Acceptance Criteria
- [ ] Testable_Outcome_X
- [ ] Testable_Outcome_Y
- [ ] Testable_Outcome_Z
- [ ] Requires design review
- [ ] Requires accessibility review

## Team
Please check the team(s) that will do this work.

- [ ] CMS Team
- [x] Public Websites
- [ ] Facilities
- [ ] Accelerated Publishing

**Comment by laflannery** [comment]
@FranECross and @jilladams This is to get rid of the custom HTML/tech debt we are putting into place currently on PACT Act, I don't really know a better way to keep track of this but I figure we should at least have a ticket for it.

**Comment by jilladams** [comment]
Noted, added to PACT epic.

**Comment by laflannery** [comment]
I mentioned this the other day but noting here as well, this is unblocked, [radio buttons ](https://design.va.gov/storybook/?path=/docs/uswds-va-radio--forms-pattern-single#forms-pattern-single)and [checkbox groups](https://design.va.gov/storybook/?path=/docs/uswds-va-checkbox-group--forms-pattern-single) have been updated in the DS

**Comment by jilladams** [comment]
Removed Blocked label / queued for next refinement.

**Comment by FranECross** [comment]
Close this associated ticket when this one is completed/released. https://github.com/department-of-veterans-affairs/va.gov-team/issues/73576#issuecomment-1924248445

**Comment by FranECross** [comment]
Putting this back in New due to PAW being delayed until approx April 2024.

**Comment by FranECross** [comment]
Candidate for Design Team to handle this when they componentize?

**Comment by laflannery** [comment]
@FranECross This is a ticket for our team, it's our product and we have to add the v3 components to the PACT Act product.

**Comment by randimays** [comment]
Fair to say this can be closed since we have https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17200?

**Comment by laflannery** [comment]
Ya I think we can close this. The other ticket indicates these elements need to be updated and I don't think there's anything in here that needs to be moved into the other ticket
