### ISSUE TITLE
URL Change for: Hemet VA Clinic

### ISSUE THREAD

**Issue by omahane** [department-of-veterans-affairs/va.gov-cms#15920]
### Implementation date
When does this request need to be live:
[MM/DD/YYYY]

### 1. Canonical URL change 
**Note: Canonical URL changes do not block the completion of the parent ticket. Once the URL redirect above has been deployed, the value to the Veteran is delivered. This ticket should be kept open until the URL change is verified, except in the case of a removal (as described below).**

### Instructions for canonical URL change
- [x] Verify that the new URL for the facility is published and accessible on VA.gov.
- [x] Update the [CSV in Lighthouse](https://github.com/department-of-veterans-affairs/lighthouse-facilities/blob/master/facilities/src/main/resources/websites.csv) with the changed URL, maintaining the sorted order of the Facility API IDs.
- [x] Create a PR in the [lighthouse-facilities repo](https://github.com/department-of-veterans-affairs/lighthouse-facilities), tagging the Lighthouse team.
- [x] Post a message in the #cms-lighthouse channel in Slack, with an @mention to a Lighthouse team member.
- [x] Add the "Awaiting CSV" flag to the facility node with a revision log message that includes a link to this ticket.
- [x] Validate that the change has deployed by checking that the Facility Locator has been updated with the new url.
- [ ] Update this ticket with a comment that the CSV change has been deployed.
- [ ] Remove the "Awaiting CSV" flag to the facility node with a revision log message that includes a link to this ticket.

#### URL change example (update with actual ID and URL)
| Facility API ID  |  Full VA.gov URL |
| ---  |  --- |
| vha_605GG | https://www.va.gov/loma-linda-health-care/locations/hemet-va-clinic |

**Comment by stefaniefgray** [comment]
Jira ticket: https://va-gov.atlassian.net/browse/VAHELP-6651

**Comment by stefaniefgray** [comment]
Facility opens 1/22/2024 -- waiting for editors to finish draft homepage/health services

**Comment by stefaniefgray** [comment]
@omahane Ready to go

**Comment by ian-sears** [comment]
**Facility Locator API ID:** vha_605GG
**Published Facility Link**: https://www.va.gov/loma-linda-health-care/locations/hemet-va-clinic/
@omahane 
This Facility has been completed by the Editor, Brandon Murray, this afternoon, and is Published.
**Ref Jira Ticket:** https://va-gov.atlassian.net/browse/VAHELP-6970
**VISN:** 22

**Comment by omahane** [comment]
The CSV change has been requested: https://dsva.slack.com/archives/C02BTJTDFTN/p1711394944989009

**Comment by ian-sears** [comment]
Awaiting validation that the change has deployed by checking that the [Facility Locator has been updated](https://www.va.gov/find-locations/?page=1&address=loma%20linda%2C%20ca&facilityType=health&serviceType&latitude=34.053797&longitude=-117.261093&radius=10&bounds%5B%5D=-118.011093&bounds%5B%5D=33.303797&bounds%5B%5D=-116.511093&bounds%5B%5D=34.803797&context=Loma%20Linda%2C%20California%2C%20United%20States) with the new url.

**Comment by omahane** [comment]
End of sprint 106 report: still awaiting CSV change and deploy.

**Comment by omahane** [comment]
Confirmed that this is now live on va.gov.
