### ISSUE TITLE
FE: Fix va-breadcrumbs spacing across PW portfolio

### ISSUE THREAD

**Issue by randimays** [department-of-veterans-affairs/va.gov-cms#15924]
## Description

[Slack thread](https://dsva.slack.com/archives/C01DBGX4P45/p1698676437427859) for context.

We discovered that the DST [made a change](https://github.com/department-of-veterans-affairs/component-library/pull/861/files) to remove padding from the `<va-breadcrumbs>` component. This created an issue with the left-side spacing on the breadcrumbs across screen widths.

Example on Income Limits (in production)
<img width="322" alt="Screenshot 2023-10-31 at 10 58 07 AM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/19175324/c3ffd84f-a5d7-47ff-9137-c3dbe5b85c47">
<img width="1099" alt="Screenshot 2023-10-31 at 10 58 02 AM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/19175324/e64dbcc7-9726-49e7-ba23-153fbcacfb5a">

### User story

**AS A** Veteran or other user viewing a nested page in VA.gov
**I WANT** to see breadcrumbs in their entirety
**SO THAT** I may easily navigate to any page in the hierarchy, thus having a better user experience within VA.gov

### Engineering notes / background

Gather list of apps PW owns that use `<va-breadcrumbs>` (in vets-website). Adjust styling on the left side so the breadcrumbs are aligned with the left edge of the page content across screen widths.

## Acceptance criteria

**GIVEN** I'm a Veteran or other user navigating through pages in unauthenticated VA.gov pages (owned by PW)
**WHEN** I am on a mobile device (e.g. tablet, mobile phone, etc.) viewing a page nested 2, 3, 4 or more in the hierarchy of pages
**AND** I look at the breadcrumb
**THEN** I am able to see all of the breadcrumb links, including the beginning "home" page
**AND** I can click any breadcrumb link and have that page displayed

**Comment by FranECross** [comment]
@randimays @jilladams User Story and AC added. Please let me know if anything looks amiss. Thanks!

**Comment by randimays** [comment]
PR posted for review: https://github.com/department-of-veterans-affairs/vets-website/pull/27412

Also includes an upgrade to the USWDS v3 breadcrumbs (latest) for our other 3 products using breadcrumbs (PACT Act was already updated):
- Income Limits
- Search
- Yellow Ribbon

and a fix for the flaky Income Limits test (#16736).

**Comment by randimays** [comment]
Breadcrumbs spacing (and upgrades) are visible and successful in production. Closing!
