### ISSUE TITLE
Add annotations to VBA Regional Office design

### ISSUE THREAD

**Issue by thejordanwood** [department-of-veterans-affairs/va.gov-cms#15934]
## Description

Add accessibility and design annotations to the VBA Regional Office design. This will help engineers as they create the front end designs. Use the [Income Limits Sketch file](https://www.sketch.com/s/a8506c94-a5bd-4a69-91ff-fe06545f3126) as an example.

Note for all new designs: Use USWDS v3 components when available. Preference is not to mix v3 and v1 components. Consult Amanda.

### Design

[VBA Regional Office Sketch file](https://sketch.com/s/891d33ae-152d-471c-ab5d-9aedf89cf6ff)

## Acceptance criteria

- [x] Add annotations to VBA Sketch file
- [x] Review with accessibility
- [x] Review with engineers
- [x] @davidmpickett specifies annotations for open Service Accordion

**Comment by thejordanwood** [comment]
@xiongjaneg This is the ticket for adding accessibility and design annotations to VBA. I've refined this and think we should add it into next sprint if that works for you!

**Comment by laflannery** [comment]
I did most everything already (components, heading structure, etc.), just not the expanded accordions. I know a lot of that is editor managed text so it's not necessarily worth me going through that. If any of that can be determined by us though let me know and I can go through that as well

**Comment by xiongjaneg** [comment]
@laflannery Should I remove the a11y AC from this ticket?

**Comment by laflannery** [comment]
@xiongjaneg No, it can stay. There will probably be some review with Jordan, just to make sure there aren't questions in what I added or anything additional she adds

**Comment by xiongjaneg** [comment]
@davidmpickett Here's the ticket that Jordan has for annotations to the design if you want to sync up for additional context you want to provide

**Comment by davidmpickett** [comment]
Reopening per scrum discussion

**Comment by thejordanwood** [comment]
@davidmpickett I got ahead of myself! Please add any annotations you feel would be helpful.

**Comment by davidmpickett** [comment]
## Service Accordion annotations (WIP)

### High-level notes

- These accordions use the borderless variant. This is a change from VAMC & Vet Center Service accordions, which currently use the bordered variant. Pending outcome of #16154, VAMCs may also switch to borderless variant. Not sure how much the service accordion templates are currently shared across Vet Center & VAMCs

### Official taxonomy name (h3)

**Comment by davidmpickett** [comment]
Did a quick mock up in Mural to go along with the notes above https://app.mural.co/t/departmentofveteransaffairs9999/m/vagov6717/1677277602711/74cecb64b6eeb9558aa868240cd726b54fcb93a7?wid=0-1700494668694

**Comment by thejordanwood** [comment]
@davidmpickett I added your annotations to [the Sketch file](https://sketch.com/s/891d33ae-152d-471c-ab5d-9aedf89cf6ff).
