### ISSUE TITLE
Dark launch docs: Migrate from PW current source of truth into better location for CMS ongoing documentation

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#15932]
## User Story or Problem Statement
As a content editor, I need to understand the options for testing CMS content pre-production. 

## Description or Additional Context 
In 2022, Public Websites built a mechanism to allow "dark launching" CMS content, for usability testing. This "product" should now transition to CMS team for long-term enhancement & maintenance, or to EOL.

Background re: transitioning to CMS Team: 
https://dsva.slack.com/archives/CT4GZBM8F/p1698696734566799

Existing docs, in PW team products docs: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/public-websites#shadow--dark-launches-of-content
- The original use case here was for usability testing CMS content in Staging, since Tugboat is not publicly accessible.
- [Staged Content entity subqueue](https://prod.cms.va.gov/admin/structure/entityqueue/staged_content/staged_content?destination=/admin/structure/entityqueue) in the CMS. Adding nodes to this queue means they will only be built for Staging, not Production.
- [Dark launch request issuetemplate](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/new?assignees=jilladams%2C+wesrowe&labels=Drupal+engineering%2C+Needs+refining%2C+%E2%AD%90%EF%B8%8F+Public+Websites%2C+VA.gov+frontend&template=pw-dark-launch.md&title=CMS%2FReact+content+dark+launch+request%3A+%3Ccontent+info%3E): currently gets assigned to Public Websites -- includes a runbook for managing the steps to dark launch a new product
- Ryan Koch and Daniel Sasser helped build this. We've used it one time, for a new Form online tool that never did launch due to contract transition. It's really only fleshed out for new products / pages, and not really for handling iterative launches or existing CMS content.

## Acceptance Criteria
- [ ]

**Comment by jilladams** [comment]
Went ahead and updated assignment / team info in the issuetemplate for this: https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/.github/ISSUE_TEMPLATE/dark-launch.md

**Comment by BerniXiongA6** [comment]
@EWashb @ndouglas I'll add this to our sync this week

**Comment by jilladams** [comment]
Per Slack thread yesterday, decision was made to host these docs in the Platform content site: https://dsva.slack.com/archives/C03LFSPGV16/p1726518589434909

Closing, and the work will be tracked in https://github.com/department-of-veterans-affairs/va.gov-team/issues/93032
