### ISSUE TITLE
Improve and make consistent the help text for "top 4" text fields across content types. 

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#1594]
**AC**
- [x] Scope shortened to 9 content types and the following fields
  - [x] Title
  - [x] Intro text
  - [x] meta title
  - [x] meta description
  - [x] Title and introduction field group names 
- [x] Remaining 7 content types identified as better “deep dives,”  over cross-sectional approaches to fields
- [x] Help text content rewritten
  - Shortened to 150 characters or less
  - Content limited to action, purpose, and hard requirements
  - Rewritten to new structure/syntax developed in On help text work
  - Verb + field label + purpose + hard guidelines
Applies consistent content across similar fields
- [x] Some field labels rewritten for clarity and consistency
- [x] Listings content type names rewritten for clarity
- [x] Design opportunities or open questions identified and noted in AT content model documentation
- [x] Final proofread and merge

**Next steps**
- First pass on remaining content types
- Move help text up to display above the field
- Continue exploration of learn more pattern - get feedback from Jen Lee and potentially others

**9 First pass content types**
- Bene detail page
- Detail page
- Bene hub landing pages 
- Event
- Event listing
- Health services listing
- Leadership listing
- Locations listing 
- New releases listing 
- Office 

**Remaining content types for next sprint:**
- Press release
- Staff profile
- Story
- VAMC facility - name and API ID
- VAMC system
- Publications listing 
- Stories listing 
- Event

**Implementation**
 * Ask for a devshop demo environment right before you start working on this (assuming #1793 is already merged)
 * Rachel to implement help text on a cloud-based development (devshop demo)environment TBD
 * An engineer to export and commit those changes. 

 

Assumes that we don't have "Learn more", or two fields to structure help text, for now.

**Comment by kevwalsh** [comment]
i've created #1828 to export the help text to code, in Sprint 7, so i think we can mark this complete!

**Comment by rachel-kauff** [comment]
@kevwalsh I finished proofreading. This is ready to merge!
