### ISSUE TITLE
Update Front End query for VBA Service Location paragraph type

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#15959]
## Description
Create the query for the updated Service Location paragraph type for VBA that Drupal engineers implemented in https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14704

It is embedded in Facility accordions. Can be connected to Facility Service or Service Location.

This is used in the following content types:
VAMC non-clinical service
VAMC facility service
VBA service region
VBA facility service
Use the content editor role

## Resources
[Design System link](https://www.figma.com/files/920496649063276587/project/53099542/CMS-Design-System-Library?fuid=1118989037713679864)

[Figma file Service Location paragraph type](https://www.figma.com/file/aKdT4weNNthDxb3r6MolEh/VBA-Content-Specs?type=design&node-id=208-714&mode=design&t=LTvuLnielz6wFsoh-0)

[Service Location spreadsheet link](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14890#issuecomment-1791554583)

To create a VBA Facility service in the integration branch: https://pr15622-xptmfsnjoodldn85nzgkrgljqtfbz24b.ci.cms.va.gov/node/add/vba_facility_service

## Acceptance Criteria
- [x] VBA Service Location query is set up
- [x] VBA Service Location query is tested on the Tugboat branch.
- [x] This ticket need to go into their own integration branch.

**Comment by xiongjaneg** [comment]
@xiongjaneg find any depedency ticket

**Comment by xiongjaneg** [comment]
@maxx1128 Review and edit this ticket as this is an older ticket that may duplicate partially or entirely completed work.

**Comment by xiongjaneg** [comment]
Question from Max: Is this part of the taxonomy term Health care service?

**Comment by maxx1128** [comment]
This ticket is currently blocked due to waiting on final changes from the CMS side.

**Comment by xiongjaneg** [comment]
Pull request in review

**Comment by jilladams** [comment]
Merged and pending deploy. Should go tomorrow.

**Comment by xiongjaneg** [comment]
@maxx1128 Would you check off the ACs that you've completed? Thanks!

**Comment by jilladams** [comment]
@maxx1128 @xiongjaneg this is closeable, yes?

**Comment by jilladams** [comment]
🤦‍♀️ nevermind, it's complete pending integration already. Ignore me.
