### ISSUE TITLE
Update the UI and content of the "Add Image" flow.

### ISSUE THREAD

**Issue by BlakeOrgan** [department-of-veterans-affairs/va.gov-cms#15962]
## User Story or Problem Statement
As part of the alt text improvement work that we have been doing, there are UI and content updates that need to happen to the [Add image page of the CMS](https://prod.cms.va.gov/media/add/image) based on [the research findings](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/research/alt%20text/topline.md) from @joagnitti. These UI updates can be found in the [Figma file](https://www.figma.com/file/OXueAhBrPif6wh8vynPxGs/Alt-Text-Errors?type=design&node-id=529%3A11615&mode=dev) that @BlakeOrgan put together.

## Description or Additional Context 

The UI changes are listed below:

- [x] Changed "Provide a name that will help other users of the CMS find and reuse this image. The name is not visible to end users." to be help text that is attached to the Name input rather than separate and at the top.
- [x] Red colors updated to "--va-red-dark" HEX #CD2026 in order to increase visibility and to align with error messages on VA.gov
- [x] Switched position of alt text input field and image preview so that input field is now left aligned.
- [x] Image preview now shows the whole image and does not crop.
- [x] Increased the height of the input field so that 150 characters can show within the field without having to scroll left/right.
- [x] Updated the content of the "Best practices" bullet points based on editor feedback and educational opportunities.
- [x] Best practices bullet points should now default to closed to reduce cognitive load. We can rely on the error text to guide them in making corrections if they're made.
- [x] Learn more link should open in a new tab so that any work done on this page is not lost.
- [x] Removed the yellow "approaching character limit" indicator because it showed no effect on situational understanding and yellow is a difficult color to maintain AA contrast ratios on a white background.

## Acceptance Criteria
- [ ] UI and content was updated to match the Figma file
- [ ] Requires design review

## Team
Please check the team(s) that will do this work.

- [x] CMS Team
- [ ] Public Websites
- [ ] Facilities
- [ ] Accelerated Publishing

**Comment by edmund-dunn** [comment]
Closing this after reviewing with @BlakeOrgan via zoom. Final review work will take place after completion of testing ticket #15783.
