### ISSUE TITLE
Remove Events checkbox CMS feature toggles after full launch

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#15968]
After full launch of the Events national checkbox, we need to remove the feature toggles we created in the CMS: 

FEATURE_EVENT_OUTREACH_CHECKBOX
FEATURE_EVENT_OUTREACH_CHECKBOX_FULL

PRs where these were added: 
https://github.com/department-of-veterans-affairs/content-build/pull/1752/commits
https://github.com/department-of-veterans-affairs/va.gov-cms/pull/15930

## ACs

- [x] Both Events checkbox CMS feature toggles are removed and no longer present in Prod CMS
- [x] Events checkbox on Event node form is unaffected; all Editors with Event create / edit permissions can view and modify

**Comment by jilladams** [comment]
@FranECross @dsasser FYI, created this ticket for removing the Events checkbox feature toggles after full launch. I put it in Stretch / Next sprint, thinking we may get through full launch next week and could do this at the end of next sprint, tbd.

**Comment by dsasser** [comment]
This is probably a 2.

**Comment by dsasser** [comment]
## End of Sprint update for Sprint 97, 11/21/23

Did not get to this as planned, though we knew that it was a stretch putting it in the sprint.

**Comment by dsasser** [comment]
## Status Update 12/1/23

PR is ready and approved, but waiting to merge until we get the go-ahead from Blake/PO (see https://dsva.slack.com/archives/C52CL1PKQ/p1699997409870189)

**Comment by jilladams** [comment]
Full launch comms went out to all editors on 11/30. Will double check with Dave on Monday re: going ahead to merge here.

**Comment by dsasser** [comment]
Per [Slack notification](https://dsva.slack.com/archives/C52CL1PKQ/p1701722096417739), we are ok to merge.

**Comment by jilladams** [comment]
Content release timing data provided to Dave: https://dsva.slack.com/archives/C52CL1PKQ/p1701722096417739

This was his only question re: removing toggles, so we're moving ahead.

**Comment by jilladams** [comment]
Verified in Prod
