### ISSUE TITLE
FE: VA.gov homepage needs spacing adjustments in the Common Tasks (Search, Top Pages) section

### ISSUE THREAD

**Issue by randimays** [department-of-veterans-affairs/va.gov-cms#15967]
## Description
On the VA.gov homepage in the Common Tasks section (Search section, Top Pages link list), there are certain screen widths where the content touches the edge of the window.

Around 1010px wide on the Search side, the content touches the edge of the window.
<img width="1001" alt="Screenshot 2023-10-31 at 12 29 00 PM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/19175324/372ffc7a-5715-4030-8835-6663b17981c4">

Around 903px wide on the Top Pages side, the content touches the edge of the window.
<img width="874" alt="Screenshot 2023-10-31 at 12 26 19 PM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/19175324/58c8d3d2-759b-4aa2-8e4b-6e14b0104815">

### User story

**AS A** Veteran or user on VA.gov
**I WANT** to be able to use smaller tables/devices and view the common tasks fully on the page
**SO THAT** I don't inadvertently miss information or click the wrong thing

### Engineering notes / background
This is an issue with the padding/margins on the containers of the Search content and the Top Pages content. The background color containers are fine, but we need to make sure there is adequate space around the content itself across breakpoints.

### Quality / testing notes
- [ ] Test the full section at all breakpoints between mobile and wide desktop.

## Acceptance criteria
- [ ] Jordan creates mockup for tablet sizes
- [ ] FE work is done according to mockup

**Comment by FranECross** [comment]
Slack thread between Jordan and Randi: https://dsva.slack.com/archives/C52CL1PKQ/p1698773199888349

**Comment by jilladams** [comment]
Noting: Jordan's work is rolled into this ticket, but 2 points reflects engineering effort only. We'll want to double check that when we prioritize this into a sprint.

**Comment by chriskim2311** [comment]
Code is complete pending PR review
