### ISSUE TITLE
Update VBA Facility content type Prepare for your visit section

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#15977]
## Description or Additional Context
Per [Slack thread](https://dsva.slack.com/archives/C0FQSS30V/p1698332240617479?thread_ts=1698267723.358089&cid=C0FQSS30V) VBA Facility Content Type should be updated to switch health_care_local_facility_servi to basic_accordion in the Prepare for your visit section. The VAMC model uses full text while the Vet Center model uses limited text. We want to use the Vet Center model with limited text for VBA.

## Acceptance Criteria
- [x] health_care_local_facility_servi is changed to basic_accordion in the VBA Prepare for your visit section

**Comment by davidmpickett** [comment]
## Content Spec (WIP)

### vba_facility Content type
- Delete field_location_services
- Add existing field field_prepare_for_visit
  - Include paragraph type: Accordion
  - Users may translate this field: Uncheck
  - Cardinality: unlimited
- Manage Form Display
  - Nest field_prepare_for_visit within the Prepare for your visit Details 
  - Use Paragraphs (stable) widget
  - Match widget settings from Widget settings for vet_center, field_prepare_for_visit 


### basic_accordion paragraph type
- Consider changing label from 'Accordion' -> 'Prepare for your visit accordion'

**Comment by davidmpickett** [comment]
Pinged @omahane and @swirtSJW [in Slack](https://dsva.slack.com/archives/C0FQSS30V/p1700094525834369) for review of spec

**Comment by omahane** [comment]
>Users may translate this field: Uncheck

I can't uncheck this box, @davidmpickett

**Comment by omahane** [comment]
> Note that the VBA Facility type currently is using "Details" for this grouping and Vet Centers is using a "Fieldset." I don't know enough about Form Display to know what the distinction is. They seem very similar

I'll change VBA to match Vet Center

**Comment by davidmpickett** [comment]
Fix has merged to prod!
![Screenshot 2023-11-20 173237](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/a6fcabe4-9f74-43da-8279-837869061236)
