### ISSUE TITLE
Have Deploy Wait time calculated dynamically

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#1597]
## User Story or Problem Statement

As a editor, developer, I need the deployment window to be more timely and  less redundant delays so that I can get back to work in a more consistent fasion..

Currently there are two waits in the deployment to prod.
The first is waiting for a valid build status (wildly unpredictable)
The second is the defined wait time.  (very predictable)

The notification for doesn't go to slack that a deployment is starting until after we get a valid build status, and then we have the enforced wait.  So our deployment time is the sum of these two values.

It would be nice, if at all possible, to make the defined wait time be the "specified wait time, minus the time  time spent waiting for the valid build status.  Then the notiffication could be moved up in the chain and we don't have redundant waiting.
![image](https://user-images.githubusercontent.com/5752113/80137550-72ad9a80-8571-11ea-8fb5-c2b63047fc4d.png)

## Acceptance Criteria
* announcement  to slack is moved to in front of the build status wait.
* TIme spent waiting for the build status is subtracted from the requested delay.

## Implementation steps
<optional>

**Comment by olivereri** [comment]
I think this one can be closed, as this issue should satisfy AC #1.  AC #2 is superseded by always finding and deploying the last commit to pass Staging tests.

https://github.com/department-of-veterans-affairs/va.gov-cms/issues/2983

![image.png](https://images.zenhubusercontent.com/5f04cf8f49978b1615fee8c2/0ac5d386-8aac-402f-9e12-cd1e233e9c0a)

**Comment by ElijahLynn** [comment]
Agreed.
