### ISSUE TITLE
[Aging Content - Post MVP] Auto-archive the content hooked up to the notifications framework

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-cms#15973]
## Elevator Statement:
In order to ensure that only timely, relevant information is displayed to Veterans, their caregivers, family and survivors, we need the to have content auto-archived at 11:59:59 on the content's expiration date.

## Description 
Content in general, and for the purpose of this Initiative/epic content types of Full-width Banner/alert, the Home Page News Spotlight Block, and the Home Page Benefit Promo Block in VA.gov become stale and aren’t monitored or updated on a regular cadence, allowing many of them to still display after a campaign or event has passed.

A new notification [framework](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/governance/aging-content-notifications/initiatives/2024-specify-timeframes/Initiative-1-mvp-aging-content-new-framework.md) has been created for that is usable for any content type, wherein specific notification timeframes may be assigned to based on expiration dates, and the content should be auto-archived at 11:59:59 on the content's expiration date.

## Goal

Create a method/framework for auto-archiving content. It should be extendable to allow any content type to be auto-archived based on the content's expiration date, 
 
- As mentioned above, the framework should be easily extendable to handle other content types besides the examples listed below, which will be implemented after the framework is completed.
  - Full-width alert/banner: content type will be assigned a 7-day timeframe, and the content should be auto-archived at the end of the expiration day/date.
  - Home Page Promo Block:  content type will be assigned a 30-day timeframe, and the content should be auto-archived at the end of the expiration day/date.
  - Home Page News Block: content type is assigned a 30-day timeframe, and the content should be auto-archived at the end of the expiration day/date.

### User story

**AS A** PO/PM managing Full-width Banner, Home Page Benefit Promo Block, and the Home Page News Spotlight Block,
**I WANT** this content to be auto-archived at 11:59:59PM of the content's expiration date if the editor hasn't already archived it, or edited to 'reset' the timeline
**SO THAT** Veterans, their families, caregivers, and survivors only see current information on VA.gov and know that it's a reliable source of information for them.

### AC

**AC1: Full width alert/banner is auto archived at the end of its expiration dates**
**GIVEN** the content type of Full-width Banner has a timeframe assigned of 7 days
**WHEN** it is 11:59:59PM on the expiration dates (day 7)
**THEN** the content is permanently auto-archived

AC1: Home Page News Spotlight Block is auto archived at the end of its expiration dates
**GIVEN** the content type of Home Page News Spotlight Block has a timeframe assigned of 30 days
**WHEN** it is 11:59:59PM on the expiration dates (day 30)
**THEN** the content is permanently auto-archived

AC1: Home Page Benefit Promo Block is auto archived at the end of its expiration dates
**GIVEN** the content type of Home Page Benefit Promo Block has a timeframe assigned of 30 days
**WHEN** it is 11:59:59PM on the expiration dates (day 30)
**THEN** the content is permanently auto-archived

**Comment by FranECross** [comment]
@dsasser @jilladams Here's the story for carving off the work to auto-archive banners/blocks of content, as well as notify. I'll add the epic info as well as attach Daniel's document.

**Comment by dsasser** [comment]
Is this an epic? This is a large block of work for a single ticket, and could probably benefit from breaking it down into smaller tickets.

**Comment by FranECross** [comment]
Good call, @dsasser ! I'll turn it into an Epic.

**Comment by FranECross** [comment]
Per Dave C, auto-archiving is ice boxed until/if it's determined it provides value.
