### ISSUE TITLE
Remove 22 "old*" DB Tables

### ISSUE THREAD

**Issue by ElijahLynn** [department-of-veterans-affairs/va.gov-cms#1598]
## Description

Remove all these old tables, can we do this in an update hook?

> CREATE TABLE `old_2d0a86taxonomy_term__783aa8b8ea` (               
> CREATE TABLE `old_2d0a86taxonomy_term__88653be1a9` (    
> CREATE TABLE `old_2d0a86taxonomy_term__9782c9e15b` (               
> CREATE TABLE `old_2d0a86taxonomy_term__a4418df423` ( 
> CREATE TABLE `old_2d0a86taxonomy_term__d81762bde3` (
> CREATE TABLE `old_2d0a86taxonomy_term__field_acronym` (            
> CREATE TABLE `old_2d0a86taxonomy_term__field_also_known_as` (      
> CREATE TABLE `old_2d0a86taxonomy_term__field_description` (        
> CREATE TABLE `old_2d0a86taxonomy_term__field_email_updates_url` (  
> CREATE TABLE `old_2d0a86taxonomy_term__field_intro_text` (         
> CREATE TABLE `old_2d0a86taxonomy_term__field_link` (               
> CREATE TABLE `old_2d0a86taxonomy_term__field_metatags` (           
> CREATE TABLE `old_2d0a86taxonomy_term__field_owner` (    
> CREATE TABLE `old_2d0a86taxonomy_term__parent` (                   
> CREATE TABLE `old_2d0a86taxonomy_term_data` (                      
> CREATE TABLE `old_2d0a86taxonomy_term_field_data` (                
> CREATE TABLE `old_5e4efe_url_alias` (                              
> CREATE TABLE `old_cc8f4emenu_link_content` (                       
> CREATE TABLE `old_cc8f4emenu_link_content__74f36c1a32` (  
> CREATE TABLE `old_cc8f4emenu_link_content__8d207f0e04` (           
> CREATE TABLE `old_cc8f4emenu_link_content__field_label` (          
> CREATE TABLE `old_cc8f4emenu_link_content_data` (
> 

## Acceptance Criteria

- [ ] All tables with names starting with `old_{hash}` have been removed from the production database

**Comment by ndouglas** [comment]
Closed by #12299.
