### ISSUE TITLE
Duplicate users appearing in Drupal Admin "people" view

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#15984]
## Describe the defect
https://dsva.slack.com/archives/CT4GZBM8F/p1698964741773909

In the People page of Drupal Admin, I'm seeing dupe rows for several people, with identical user IDs: https://prod.cms.va.gov/admin/people?user=&status=1&role=content_publisher&workbench_access_section__section=194. 

I got here while looking for a Content Publisher test user with Sitewide Content section permissions. I didn't check other roles / sections to see if this happens other places. It might.

## To Reproduce
1. As Drupal admin, go to People
2. Filter by Content publisher role
3. Filter by Sitewide Content Team section
4. See multiple duplicate rows of users, with the same User ID

## AC / Expected behavior
Each user should appear one time in any list of users 

## Screenshots
![Screenshot 2023-11-02 at 3 37 07 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/85581471/988ec3aa-45b7-4022-ad0e-4c0757950dd1)

**Comment by TroyA6** [comment]
Possibly VIEW related. Searching all Active accounts, Carl Dickerson (for example) only appears once
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/108767736/c59de818-c320-477f-8832-b2c805b90edb)

**Comment by TroyA6** [comment]
Searching for an individual in the SITEWIDE CONTENT TEAM (such as Marci McGuire) results in duplicate results -
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/108767736/d2dbd416-4b2b-494d-8f9a-4964491afca0)

**Comment by ndouglas** [comment]
The view generates an SQL query with a LEFT JOIN on users against section associations, where there's an array of possibilities on the right. The number of rows for each user will correspond to the number of their section memberships within the array of possibilities. We just need to click the "DISTINCT" checkbox behind Query Settings, I believe.
