### ISSUE TITLE
Get Drupal View of System Ids and Connected Facility Ids into KISS format 

### ISSUE THREAD

**Issue by eselkin** [department-of-veterans-affairs/va.gov-cms#16019]
## User Story or Problem Statement

We need to get the facilities and system ids / system names / facility names from drupal view into content-build as a JSON file for KISS structure.

## Description or Additional Context 

This view's data will be used by VA Police and possibly other data.

Will require two PRs.

## Acceptance Criteria
- [x] CSV is pulled from prod CMS
- [x] vamc-system.json is created in cache static data files
- [x] e2e testing is added that vamc-system.json is created
- [x] Selector is created in vets-website
- [x] Connector is creates in vets-website
- [ ] Accelerated Publishing FE folks are added as code reviewers on the PR (Ryan Koch)

## Team
Please check the team(s) that will do this work.

- [ ] CMS Team
- [ ] Public Websites
- [x] Facilities
- [ ] Accelerated Publishing

**Comment by eselkin** [comment]
I think this needs to be blocked by a Drupal ticket of getting this view created.

**Comment by xiongjaneg** [comment]
@xiongjaneg find Drupal ticket that goes before this

**Comment by eselkin** [comment]
Created branch `VAMC-16019-KISS-VAMC-system-facilities-list`
Yes, It should have been VACMS-1... but I typoed and pushed
This branch pulls from staging.cms.va.gov for the CSV currently.
Need to wait for merging change to testing from the JSON testing branch for VA Police testing

**Comment by xiongjaneg** [comment]
@jilladams I'm not going to carry this over to 101 since we've decided to prioritize VBA and the FL spike for now. This one can park in Ready until the rest of police are ready to go once we get the police data the way we need it.

**Comment by jilladams** [comment]
@ryguyk @timcosgrove FYI that we are planning this KISS-related ticket to sprint starting today. Current thinking: we plan to implement in not-AP, as we will likely head to prod before AP's prod timing. We can track the migration to the AP version of KISS later, but will add Ryan as code reviewer for this work as FYI.  Let us know if that makes sense to y'all or not.

**Comment by jilladams** [comment]
The last AC here was to put Ryan Koch on PRs as reviewer, which we overlooked at PR time. Started a Slack thread here for his reference: https://dsva.slack.com/archives/C0FQSS30V/p1706301411453809

Closing.
