### ISSUE TITLE
Create View export to connect Systems to Facilities

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#16015]
## User Story or Problem Statement
We need a data source to be able to collect all facilities in a system.

System Name | Facility common name | Facility API ID

## Description or Additional Context 
We want the minimum data necessary to be able to keep the payload size down.

[Data elements](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/medical-centers/police/readme.md#data-elements)

## Acceptance Criteria
- [ ] A CSV that contains the following columns
   - [x] add an exports tab under the Content menu
   - [x] set a meaningful path to the export file (similar to supplemental status export)
   - [x] System Name
   - [x] Facility common name
   - [ ] Facility API ID. 
- [x] Visible to unauthed.

## Team
Please check the team(s) that will do this work.

- [ ] CMS Team
- [ ] Public Websites
- [x] Facilities
- [ ] Accelerated Publishing

**Comment by xiongjaneg** [comment]
@xiongjaneg hold for next sprint pending data mtg

**Comment by jilladams** [comment]
https://prod.cms.va.gov/admin/content/exports - verified, closing.
