### ISSUE TITLE
Draft VA health chat research plan and conversation guide

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#16012]
### User story
**AS A** Researcher
**I WANT** to document the details for planning  VA Health chat research
**SO THAT** the research will achieve its purpose

## Workflow/tasks:
- [ ] Create sitemap in Excel with potential placements for VA health chat  
- [ ] Update [research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/facility-locator/research/user-research/VAMC-communications-methods/Research-Plan.md)
- [ ] Update [conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/facility-locator/research/user-research/VAMC-communications-methods/Conversation-Guide.md)
- [ ] Solicit review/feedback from Sitewide UX Lead and other team members
- [ ] Become familiar with [Research Review cycle requirements](https://github.com/department-of-veterans-affairs/va.gov-research-repository/issues/70)

## Acceptance Criteria
- [ ] sitemap completed and shared as a spreadsheet in Sharepoint
- [ ] [Research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/medical-centers/research/VA-health-chat/research-plan) drafted
- [ ] [Conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/facility-locator/research/user-research/VAMC-communications-methods/Conversation-Guide.md)
- [ ] Feedback incorporated from Sitewide UX Lead and other team members
- [ ] Research plan posted on github in project research folder
- [ ] Final approval obtained from VA PO and UX lead and documented at the bottom of the file in preparation for Research Review cycle

**Comment by xiongjaneg** [comment]
@ALogsdon3 This was discussed by @aklausmeier  in sprint planning as potential work if you have capacity between research sessions.

**Comment by aklausmeier** [comment]
@xiongjaneg Do we need this ticket and #16011: [Update the research plan and conversation guide for VA Health Chat and VA Health Connect](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16011)

**Comment by xiongjaneg** [comment]
@aklausmeier There's probably nothing in it needed since we seem to be moving down the path of health chat research separate from health connect, so it could be closed. If needed in the future, we could reopen or repurpose. Thanks for checking!

**Comment by ALogsdon3** [comment]
@xiongjaneg I updated the tasks and ACs for this ticket and it's now ready for sprint 105.

**Comment by xiongjaneg** [comment]
closing as duplicate of #16011
