### ISSUE TITLE
D10 launch

### ISSUE THREAD

**Issue by edmund-dunn** [department-of-veterans-affairs/va.gov-cms#16018]
## User Story or Problem Statement
Deploy D10 to production.

## Description or Additional Context 
We're a Go to deploy on 11/29/2023. Per Edmund: the D10 branch will be merged into main on the morning of 29 Nov. so that D10 can be launched with the regular deployment.

## Acceptance Criteria
- [ ] Merge, test and deploy D10 to production.

**Comment by BerniXiongA6** [comment]
@edmund-dunn @ndouglas we can async refine this one, but I'm going to add it to the Sprint 98 epic -- lmk if you need anything to do so, but this one looks pretty straight forward. cc: @maortiz-27-80

**Comment by edmund-dunn** [comment]
Go/No Go meeting on 27 Nove 2023. We are a go for deployment on 29 Nove 2023. It will be part of the normal deployment. The D10 branch will be merged into main on the morning of 29 Nov.

**Comment by BerniXiongA6** [comment]
Closing this since it was completed last week cc: @maortiz-27-80
