### ISSUE TITLE
D10: Updated testing toward launch

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#16013]
## Description
As of 11/6, Drupal 10 is likely to launch during Q4, exact timing TBD.

Previous testing ticket: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13990

**Previous Testing spreadsheet**: https://docs.google.com/spreadsheets/d/136FP-HtxRWJuPYYV4D95ngby96Wqy4Ul_HOgOqEk1K0/edit#gid=0

**D10 channel:** #d10-upgrade-testing DSVA slack

**Reminders from that ticket:**
Risk factors for D10:
- Dependence on a module with deprecated php syntax - e.g., contrib or custom modules
- D9-deprecated code

Products to manually test:
- Drupal-driven products
- Areas without Cypress test coverage

Functionality to test:
- Events - Cypress test coverage is good, could do some manual testing as well
- Forms migration
- Reusable Q&As - Entity Browser functionality

Possible next steps:
- Assess which products Cypress tests exist for (start with Cypress files, see what they test)
- Audit a few products at a time for test coverage, make clear recommendations for tests to add
- Test types to consider: Cypress (slow), kernel (fast), unit (fastest)

## Acceptance criteria

- [ ] Verified no D10 impact to work since August testing
- [ ] Tickets filed for any new defects, and reported with severity (Blocking D10; Fast Follow; Low priority) in #d10-upgrade-testing channel

**Comment by jilladams** [comment]
environment details: https://dsva.slack.com/archives/C05EJD52H1R/p1699466480787859

**Comment by dsasser** [comment]
## Status update 11/13/23

As a means to gather work that has transpired since we last tested D10 in July, I queried git to find all commits that: occurred since July 1, 2023, and have an author as myself or Christia: `git log --since 2023-07-01 --author=christia.troyer@civicactions.com --author=daniel.sasser@gmail.com --oneline`

<details>
<summary>Results of git query:</summary>

```
1f5703735 VACMS-15891: Assign weights to content audit views menu local tasks to display alphabetically. (#16085)
79bc477de VACMS-15891: Fine tuning some things (#16003)
a4119bf0e VACMS-15747 Feature toggle to launch nat outreach checkbox for all (#15930)
936a97df8 VACMS-15891: Update Q&A Content Report View to use Multiple Workflow Filter (#15896)
b211d6c6e VACMS-15142: Page-specific Q&A Report (#15833)
c965bed59 (tag: cms/v0.0.865) VACMS-10579: Removed promo flag via config (#15675)
ae92483a3 VACMS-15641 national outreach checkbox (#15761)
1fc9aef81 VACMS-10938: Add reusable Q&A to CLP (#15577)
6aa0f534d (tag: cms/v0.0.860) Revert "VACMS-10089: Checkbox to add event to National Outreach Calen… (#15633)
4b4ff1241 VACMS-10089: Putting cypress event form conditional test back in (#15626)
a36ad8cc1 (tag: cms/v0.0.858) VACMS-10089: Checkbox to add event to National Outreach Calendar (#15552)
5bfe738cb VACMS-15337: Upgrade limited_field_widget module to 2.1 (#15460)
47a2093f2 VACMS-11230: Follow up to remove debugging code (#15421)
3619568a1 VACMS-15242: Adjust form structure of promo block to address revision log issues (#15355)
43d147e52 VACMS-15098: Language changes to Q&A Components (#15327)
e43fa914a VACMS-14793: Hide Link Description Field in Footers (#15069)
8b17cdee0 VACMS-14860: View mode changes for magichead/benefits taxonomy. (#15292)
09ce8af07 VAGOV-0000: Resync stray config changes to code (#15293)
788f54f06 VACMS-15222: Unlock benefit taxonomy fields to content admins (#15273)
7bd0c0308 VACMS-11230: Make Benefit Detail page unpublished alert blocks stand out (#15172)
8aa53bc87 (chri5tia/main) VACMS-14817: Improve Magichead Treelines (#15123)
97b97f02a VACMS-15187: Exposes revision log message on promo type blocks (#15243)
fd68b136a VACMS-15085: Eevents can break content build (#15126)
400e3e88b VACMS-14442: fix failing video test (#15028)
0100b134a VACMS-14442: Enable other CLP sections and test them (#14763)
4bb5f10ae VACMS-14289: Changes max depth to 2. (#15014)
cc6ffa62b VACMS-13863: Improve workflow for promo blocks (#14726)
872f226fd VACMS-14777: Entity Reference (with) Hierarchy D10 compatibility (#14976)
13f09e9e0 VACMS-14289: Enhance magichead error messaging (#14973)
42bf79194 VACMS-14778: Remove duplicate, preconfigured fields. (#14907)
2fa4ddd3c VACMS-14800: Makes revision log message required on block content forms. (#14842)
19624ecb9 VACMS-14604: Target blank on title link for entity browser view (#14723)
ae1f5a1a2 VACMS-14290 implement max depth magichead (#14709)
efd33b3ef VACMS-0000: Removes magichead update hook. (#14659)
54442e7e8 VACMS-13143: Magichead Model-3 (#14042)
72fb04d29 VACMS-10941: Add reusable Q&A to benefit detail pages (#14459)
bfbee8291 (tag: cms/v0.0.803) VACMS-12325: Replace placeholder with real help text (#14378)
2180e9396 VACMS-13481: Adds new feature toggle for mobile app promotion. (#14299)
4dc06a17f (tag: cms/v0.0.798) VACMS-14274: Removes entityqueue permission that is no longer valid. (#14295)
```

</details>

From this, I extraced the major changes:

- magichead (depth constraintts, max depth, tree lines)
- required revision log on block content forms
- removal of duplicate (pre-configured) fields (add new field)
- smart date error element validation targetting (see https://www.drupal.org/node/3385720)
- add revision log message to on promo block types
- improved workflow for promo block types
- Make Benefit Detail page unpublished alert blocks stand out (#15172)
- Unlock benefit taxonomy fields to content admins (#15273)
- Hide Link Description Field in Footers (#15069)
- Language changes to Q&A Components (#15327)
- Upgrade limited_field_widget module to 2.1 (#15460)
- Add reusable Q&A to CLP (#15577)
- Page-specific Q&A Report (#15833)
- national outreach checkbox (#15761)

**Comment by FranECross** [comment]
@dsasser @jilladams Will this ticket also be worked on in Sprint 98?  I think the answer is yes (that it was about 2 sprints worth of testing/work), but wanted to check so as to know whether to put on the Sprint 98 Plan or not. Thanks!

**Comment by dsasser** [comment]
> @dsasser @jilladams Will this ticket also be worked on in Sprint 98? I think the answer is yes (that it was about 2 sprints worth of testing/work), but wanted to check so as to know whether to put on the Sprint 98 Plan or not. Thanks!

Ideally this will not carry over to the next sprint (98), so for now I would say lets not plan any D10 work for 98, but if that changes, I'll definitely raise a flag.

**Comment by dsasser** [comment]
## Update 11/15/2023

All of the BE testing has been completed; will proceed with testing the few FE related bits once the tugboat comes online.

Testing spreadsheet export:
[D10 Sitewide sanity tests - Public Websites Round 3.pdf](https://github.com/department-of-veterans-affairs/va.gov-cms/files/13367747/D10.Sitewide.sanity.tests.-.Public.Websites.Round.3.pdf)

**Comment by dsasser** [comment]
D10 testing is complete for PW.

[D10 Sitewide sanity tests - Public Websites Round 3 (1).pdf](https://github.com/department-of-veterans-affairs/va.gov-cms/files/13382968/D10.Sitewide.sanity.tests.-.Public.Websites.Round.3.1.pdf)
