### ISSUE TITLE
Update the research plan and conversation guide for VA Health Chat and VA Health Connect

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#16011]
## Description 
The situation with VA health connect (phone) and VA health chat has continued to evolve with the nationwide implementation. Our intended approach for connecting Veterans with information about these communication options also evolved following recent conversations with the relevant teams. Veteran feedback on how and where they expect to find information about these options on VAMC pages will still be very valuable. 

Teams responsible for VA health connect and VA health chat will collaborate on a single Campaign Landing Page (CLP) promoting the availability of these communication options. The Facilities team will collaborate with VHA DM to guide PAOs in directing Veterans to the CLP from relevant points on VAMC pages.

[Related UX discovery issue](https://app.zenhub.com/workspaces/sitewide-facilities-639f5253e4b702a32376339e/issues/gh/department-of-veterans-affairs/va.gov-cms/15704)

[Related Mural - VA Health Communication Methods](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1695664515308/a963ef125f7542f67e962ca83a8f25b368180618?sender=u727a8f87b62662f75a603248)

Agreed upon [research scope](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17282#issuecomment-1955234184) from UX Discovery. 

## Goal(s)of the research
- To learn where on their VA health care system/facilities webpages Veterans expect to find information about methods for communicating with their healthcare team
- To understand how these expectations are affected by modality 
  - phoning the facility directly
  - speaking with a VA clinical professional by phone
  - chatting with a VA clinical professional online (browser) or via app
  - connecting with a provider via telehealth/virtual visit
- To understand how these expectations are affected by task, such as 
   - refilling or renewing prescriptions, asking medication-related questions, receiving medication education, or reviewing treatment plans
   - making, changing, or canceling appointments
   - sending messages to the Veterans care team
   - discussing new or worsening medical or mental health concerns 
   - visiting with a VA doctor by phone or video to discuss health care needs
   -
## Workflow/tasks:
- [x] Create sitemap in Excel with potential placements for VA health chat  
- [x] Update [research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/medical-centers/research/VA-health-chat/research-plan.md)
- [x] Solicit review/feedback from Sitewide UX Lead and other team members
- [x] Become familiar with [Research Review cycle requirements](https://github.com/department-of-veterans-affairs/va.gov-research-repository/issues/70)

## Acceptance Criteria
- [x] sitemap completed and shared as a [spreadsheet in Sharepoint](https://dvagov.sharepoint.com/:x:/r/sites/SitewideFacilitiesTeam/_layouts/15/Doc.aspx?sourcedoc=%7BB72AFA54-3520-46FB-ACC3-996BC8F7B6C7%7D&file=Health%20chat%20and%20health%20connect%20sitemap.xlsx&action=default&mobileredirect=true)
- [x] [Research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/medical-centers/research/VA-health-chat/research-plan.md) drafted
- [x] Feedback incorporated from Sitewide UX Lead and other team members
- [x] Research plan posted on github in project research folder
- [x] Final review requested from VA PO and UX lead and documented at the bottom of the file in preparation for Research Review cycle

**Comment by aklausmeier** [comment]
Adding link to @mmiddaugh's [Mural for VA Health communication methods](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1695664515308/a963ef125f7542f67e962ca83a8f25b368180618?sender=u727a8f87b62662f75a603248). I thought there was a link to this in the ticket. FYA @ALogsdon3

**Comment by aklausmeier** [comment]
added a few more helpful links to body of ticket for context

**Comment by aklausmeier** [comment]
@ALogsdon3 FYA and for easy reference back, this is my [initial recommendation](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17308#issuecomment-1977585337) of where links will be placed for the design related to VHA DM's campaign landing page that's already in the works

**Comment by ALogsdon3** [comment]
Midsprint update: the spreadsheet is nearly ready, and I will start updating the research plan and conversation guide today.
cc: @jilladams

**Comment by ALogsdon3** [comment]
Further updates: Completed a draft of the research plan and took a cue from another recent tree test that @aklausmeier alerted me to and decided to incorporate the conversation guide into the research plan. Still need to add tasks, but should get going on that tomorrow.
cc @jilladams @xiongjaneg

**Comment by ALogsdon3** [comment]
Current status: Made a ton of changes to the tree after testing it in Optimal Workshop; will need to update the spreadsheet tomorrow. Added all tasks to OW for further testing tomorrow.

**Comment by davidmpickett** [comment]
@xiongjaneg @aklausmeier @ALogsdon3 For end-of-sprint purposes should the last AC be updated to final review requested? The [follow up ticket](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17498) seems to include room for final tweaks before submitting to Research Ops.

**Comment by xiongjaneg** [comment]
That would be consistent with what we've been doing for other tickets, so I'd say yes.

**Comment by ALogsdon3** [comment]
@davidmpickett that works, I can update it

**Comment by ALogsdon3** [comment]
Updated!
