### ISSUE TITLE
Explore testing options for VA Health Chat research

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#16010]
## User Story or Problem Statement
As a user experience researcher, I need to explore the options for types of research to effectively answer research questions related to VA Health Chat in order to prepare a research plan. 
## Acceptance Criteria
- [x] Explore and report on options for research (ie, moderated vs unmoderated), including the benefits and limitations of each. 
- [x] Learn how to use [Treejack, the VA's licensed tool for tree testing](https://depo-platform-documentation.scrollhelp.site/getting-started/request-access-to-tools#Requestaccesstotools-OptimalWorkshop)
- [x] Document required information necessary to build a prototype in Treejack
- [x] Follow up tickets are created

**Comment by mmiddaugh** [comment]
@ALogsdon3 you may want to review this [Facility Locator Filter Card Sorting](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/facility-locator/research/user-research/redesign/filter-categorization/research-findings.md#facility-locator-filter-card-sorting) research for an example of previous unmoderated self-guided card sort exercise. It was conducted by the Facilities team in May 2020. FYI.

**Comment by ALogsdon3** [comment]
Spent some time today weighing options for testing. I started a [Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1699650112593/672d59e5ac915c73c1dfd8d6326fcff277bc28db?sender=u3f35bedf61955cb051f44770) record evolving thoughts.
