### ISSUE TITLE
Facilities: Drupal 10 pre-launch review

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#16016]
## Description
As of 11/6, Drupal 10 launch is planned for Nov. 29.

Any new implementations since last testing (Aug. 15) may need to be tested before launch.

## Spreadsheets

- Jill's spreadsheet https://docs.google.com/spreadsheets/d/136FP-HtxRWJuPYYV4D95ngby96Wqy4Ul_HOgOqEk1K0/edit#gid=1052173265
- CMS spreadsheet https://docs.google.com/spreadsheets/d/1R4g9jSZJvGRCAWWoslnxlC2hv5A2kHKMMxabbct3bI4/edit#gid=0

## Acceptance criteria
- [x] code reviewed changes
- [ ] Reviewed previous findings noted on spreadsheet(s) above
- [ ] Verified no D10 impact to work since August testing
- [ ] If any impacts are found, they are noted on the spreadsheet(s) or in tickets.

**Comment by xiongjaneg** [comment]
@xiongjaneg Find link to the spreadsheet and link to here

**Comment by jilladams** [comment]
environment details: https://dsva.slack.com/archives/C05EJD52H1R/p1699466480787859

**Comment by swirtSJW** [comment]
editing this as I go:

- [x] events

tickets created
1. https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16111
