### ISSUE TITLE
Change management for VAMC editors for Police pages

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#16023]
## User Story or Problem Statement
As a VAMC editor, I need to provide Veterans and other audiences with accurate information about police data that appears on my system and facility web pages.

As a CMS support team member, I need to be able to support VAMC editors with information about police data that appears on their system and facility web pages.

## Acceptance Criteria
- [x] Editors have advance notice of police data on their system and facility web pages. Shared at Dec. 13 office hours.
- [x] If any editor actions are needed to direct Veterans to police data, instructions are provided to them. Editors know where to find the police data on their system and facility web pages and what information they contain.
  - [x] KB article is drafted and submitted for CMS Team review #16372 
  - [x] KB article is published prior to launch.
  - [x] VHA DM is notified in advance of launch and gets a list of custom VA Police detail pages so they can notify those editors.
- [x] CMS Support has advance notice of police data on VAMC system and facility web pages.
  - [x] CMS Support knows where to direct VAMC editors for more information about police data on their web pages, via KB article.
- [x] Ticket(s) are stubbed for post-MMVP updates.

**Comment by xiongjaneg** [comment]
Dec. 13 VAMC office hours: Jane will provide introduction to Police MMVP and MVP

**Comment by jilladams** [comment]
Will roll over, for launch comms.

**Comment by xiongjaneg** [comment]
VHA DM and CMS Support pre-warned. Will follow up again after bulk publishing.

**Comment by xiongjaneg** [comment]
Notified VHA DM and CMS Support after successful content release
