### ISSUE TITLE
[Downtime Notification Needed] Upcoming VBA database Cost of Living Adjustment weekend of Saturday, November 18 – Sunday, November 19, 2023.

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-cms#16022]
## Description

There is an upcoming VBA database Cost of Living Adjustment that affects affects basically all the underlying VBA tech systems for 2 days weekend of Saturday, November 18 – Sunday, November 19, 2023. Benefits portfolio is likely to trigger manual maintenance windows for affected applications.

Planning is occurring:  in this [thread ](https://dsva.slack.com/archives/C055573C508/p1699021458069039
) and this [mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1699022689906/c254ed5503dedce1ff1c3240ada0cfa7cb91caf2?sender=u9189a8b68ad6598602620927) what to do per application/endpoint,

### User story

**AS A** Veteran, their caregiver, or other user of VA.gov
**I WANT** to see a notification alerting me of maintenance downtime when I visit VA.gov (or specifically the Income Limits feature?)
**SO THAT** I'm aware it's not available to me during this timeframe

### Engineering notes / background
The Income Limits application DOES use a live DB connection to Postgres. The CSVs are not utilized for day-to-day user activity. Each request to the API hits Postgres, so it would appear Income Limits will be affected by this. CSVs are queried monthly, I think, in order to populate Postgres, and there is no fallback to use CSVs for API requests. (from Daniel S)

## Acceptance criteria

Note: Need to determine which features and when/where the alert should display

AC1: Maintenance Window alert displays regarding Income Limits feature(s) not available
**GIVEN** I'm a Veteran, their caregiver or another user of the Income Limits feature
**WHEN** I log into VA.gov at 0000 on Saturday 18 November 2023 through 2359 Sunday 19 November
**THEN** I WILL see a Maintenance Window alert 

AC2: Maintenance Window alert no longer displays

**GIVEN** I'm a Veteran, their caregiver or another user of the Income Limits feature
**WHEN** I log into VA.gov at 000 on 0001 Monday 20 November
**THEN** I will NOT see a Maintenance Window alert 

>Consider
> - Design / Accessibility reviews
> - Collab cycle requirements
> - Device sizes (mobile first)
> - Documentation updates / Change management
< - [Content model documentation](https://prod.cms.va.gov/admin/structure/cm_document)
> - Testing notes

- [ ]

**Comment by jilladams** [comment]
We determined in Slack that we won't be affected by the VBA systems outage: https://dsva.slack.com/archives/C52CL1PKQ/p1699290324722839

Closing.
