### ISSUE TITLE
Create doc for SiteImprove editor feedback

### ISSUE THREAD

**Issue by joagnitti** [department-of-veterans-affairs/va.gov-cms#16021]
## User Story or Problem Statement
VHA DM would like to start a 30-day trial of Siteimprove, and is requesting for the CMS Team to potentially get this into a demo environment to allow some editors to do some research with this. They're proposing a testing start date of Monday, December 4, 2023.

We need to create a template that gives testers structure while also giving them a space to record their thoughts and questions. 

## Description or Additional Context 
_From Erika: if we are able to get a couple of editors on board to test in the environment, can we create some sort of doc or checklist where they can document their reactions/feedback in the system on an async basis? I foresee a log that allows them to track in a way but gives structure as well._

## Acceptance Criteria
- [ ] Template for logging feedback has been created
- [ ] Template has been shared with PO for review and edited, as necessary

## Team
Please check the team(s) that will do this work.

- [x] CMS Team
- [ ] Public Websites
- [ ] Facilities
- [ ] Accelerated Publishing

**Comment by BerniXiongA6** [comment]
@joagnitti -- quick update that @EWashb has been talking to Siteimprove customer service about the trial period/plan. We may be looking at a delay in our original pilot plan given the trial terms/unexpected constraints. This work is still needed, but the pilot date will be pushed out. More info to come from Erika. cc; @maortiz-27-80

**Comment by joagnitti** [comment]
@BerniXiongA6 Perfect, thanks for letting me know! I started a WIP doc so we have a head start in case things fall back on the original timeline.

**Comment by EWashb** [comment]
This looks great. I added one option for the email subject line @maortiz-27-80 @jo

**Comment by maortiz-27-80** [comment]
Notes per Erika 12/19:
- What can we do in test that really makes the most out of the free 30 day trial?
- **Tests should be things that only VAMC editors can do**
- How do we want them to test?
- What do we want them to test?
- Should we have examples of things we would like them to try?

**Comment by laflannery** [comment]
@maortiz-27-80 Because of the latest from Ari, and the fact that we can't have the prepublish check, I think we might not need this anymore. Can you let me know if there is still something that we would need the editors to test?

**Comment by maortiz-27-80** [comment]
Per discussion 12/21/23 - We will not be able to get prepublish checks (as part of the Siteimprove module) up and running as it is incompatible with our decoupled Drupal setup.  Closing the ticket as a "Won't Do" as we are unable to test.  A separate testing ticket will be opened for deep linking (if applicable.  the team will assess testing needs once deep linking in is working in #16521 ). cc: @laflannery @BerniXiongA6 @ndouglas @EWashb
