### ISSUE TITLE
Update VA IAM Prod SAML Public Certificate November 16 2023

### ISSUE THREAD

**Issue by olivereri** [department-of-veterans-affairs/va.gov-cms#16038]
## User Story or Problem Statement
As a DevOps engineer I need to update the Public Certificate stored on CMS Prod Servers that secures logon.iam.va.gov, because doing this will keep CMS Prod PIV logon working correctly.

## Description or Additional Context 
VA IAM Prod environment's certificate that protects logon.iam.va.gov is expiring soon. They are replacing their certificate with their newer one. This requires us to also put a copy of the public certificate on the CMS server as it is used to validate signatures from authentication responses.

## Steps for Implementation
- Find SSOi partner e-mail
- Download public certificate
- Join Nov 16th 6pm PT, call bridge with IAM team to trouble shoot any issues.
- Replace certificate on server and restart httpd
- Add new Base64 encoded certificate in configuration code to apply it during deployments.

## Technical References
[CMS SSO SAML IAM LOGIN HOW-TO](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/platform/cms/cms-sso-saml-iam-login-how-to.md#update-the-saml-certificate-provided-by-the-iamsso-team)

## Acceptance Criteria
- [ ] Eric / Edmund attended 11/16 6pm PT meeting with IAM team
- [ ] Running config server has been updated to validate PIV login is successful
- [ ] Received text version of certificate to enter into the infrastructure code

**Comment by olivereri** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VAgov-CMS-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/16038?planning-poker) with Zenhub @edmund-dunn @teeshe @ariperez @ndouglas

**Comment by BerniXiongA6** [comment]
Added to Sprint 97 draft plan. We can also use part of Sprint Planning if we need to finalize estimate for this ticket then. Thanks @olivereri cc: @ndouglas @EWashb

**Comment by olivereri** [comment]
Completed successfully, no issues.
