### ISSUE TITLE
Publish updated CKEditor KB article

### ISSUE THREAD

**Issue by BerniXiongA6** [department-of-veterans-affairs/va.gov-cms#16049]
## Description

There is a and existing [KB article about the Rich text editor](https://prod.cms.va.gov/help/cms-basics/how-to-use-the-rich-text-editor). When D10 officially launches, some of the functions of this editor are going to change and we want to make sure that this KB article accurately reflects the current state. This articles [has been updated and is in draft](https://prod.cms.va.gov/node/34036/latest), ready to be published upon launch of D10 - which is currently planned for this week.

## Acceptance Criteria

- [x] When D10 has been launched and is live to editors, the latest version of the Rich text editor is published.
- [x] Product and Helpdesk have been notified

**Comment by laflannery** [comment]
@BerniXiongA6 and @maortiz-27-80 Updated the description. Again, let me know if this should be assigned to me

**Comment by BerniXiongA6** [comment]
@laflannery thanks for doing these this sprint! I've added this to Sprint 98 epic, could you point this? cc: @maortiz-27-80

**Comment by maortiz-27-80** [comment]
@laflannery - I okay with keeping assigned to you as I do not have Drupal access yet.  Let us know if that's okay.  - Marcia cc: @BerniXiongA6
