### ISSUE TITLE
[UX] D10 Pre-Launch - create banner alert for Drupal 10 update (11/20/2023)

### ISSUE THREAD

**Issue by BerniXiongA6** [department-of-veterans-affairs/va.gov-cms#16051]
## What You Need to Know
- This is the ticket to create the pre-launch [sitewide alert](https://prod.cms.va.gov/admin/content/sitewide_alert) that will go up on the CMS before the Drupal 10 update. Use the plan created in ticket #15862 to schedule this sitewide alert.
- Drupal 10 launch date has been determined to be 11/29/2023

## Acceptance Criteria
- [x] Pre-launch banner alert has been created using the required criteria completed in #15862  
- [x] Pre-launch banner alert is deployed on 11/20/2023
- [x] Pre-launch banner alert has been QA/Reviewed by Product or Delivery before 11/20/2023 deploy date

**Comment by BerniXiongA6** [comment]
FYI @BlakeOrgan -- we can chat at Sprint Planning -- sorry for the short notice!

**Comment by BlakeOrgan** [comment]
@BerniXiongA6 Ticket has been refined and is ready for your review.

**Comment by BlakeOrgan** [comment]
@BerniXiongA6 @EWashb 
The sitewide alert for the [Drupal 10 Pre-launch Announcement](https://prod.cms.va.gov/admin/content/sitewide_alert/938) has been scheduled for release on Nov 20 and is ready for your review.

**Comment by BlakeOrgan** [comment]
As of this morning, the pre-launch sitewide alert was launched as expected.
