### ISSUE TITLE
Edit and publish CKEditor GitHub pages with relevant CKEditor info

### ISSUE THREAD

**Issue by BerniXiongA6** [department-of-veterans-affairs/va.gov-cms#16050]
## Description

There is a [Github page with documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/product-outlines/ckeditor/README.md) about current functionality of the CKEditor.  On that page is a [Change Management section](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/product-outlines/ckeditor/README.md#change-management) that discusses the upcoming D10 launch - that is happening this week - and what changes that will be bringing with in to the CKEditor.

When D10 does officially launch, we will want to edit/update this documentation to reflect the current state of affairs. Changes to make:
- Indicate editor is now CKEditor 5 (not 4)
- Update the main CKEditor section to accurately reflect functionality
  - Remove Italics from Limited and Full
  - Add Abbreviations to Limited and Full
  - Update Styles in Full to indicate Primary action links and Secondary actions links are available as well 
- Update the first line under Change Management header to indicate that the changes are not longer planned but they did take place and indicate when they took place (date of D10 launch)

## Acceptance Criteria

- [x] All updates indicated above are completed
- [x] Product has reviewed and signed off

**Comment by laflannery** [comment]
@BerniXiongA6 Ticket is updated. I also changed the ticket - this previously said "...relevant DRUPAL version" but the thing that I needed to update is the GitHub documentation for the CKEDITOR info.

Having documentation on Drupal in general, and what version we are on I think is a larger ticket we haven't necessarily started on yet.

**Comment by BerniXiongA6** [comment]
@laflannery thanks for doing these this sprint! I've added this to Springt 98 epic, could you point this? cc: @maortiz-27-80
