### ISSUE TITLE
New Lovell TRICARE facility: Naval Great Leakes Burkey Mall Pharmacy

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#16054]
## Description or Additional Context 

Lovell reported a new TRICARE facility. TRICARE facilities don't come through VAST and must be created in Drupal.
Facility Name: Naval Great Lakes Burkey Mall Pharmacy
Address: 2630 Green Bay Road, Bldg. 3452, Great Lakes, IL, 60088
Hours: Monday through Friday 9 am - 5:30 pm, closed from 2 - 2:30 pm
Phone: [847-688-2776](tel:8476882776)
Who needs access to edit the facility in Drupal: All editors for Lovell Federal Healthcare Center
Population served (Tricare or VA or both): TRICARE

## Acceptance Criteria
- [x] New Lovell Tricare facility displays with name, address, hours, and phone above
- [x] Facility is associated with Lovell TRICARE
- [x] Leave as draft and alert Michelle

**Comment by swirtSJW** [comment]
This has been completed https://prod.cms.va.gov/lovell-federal-health-care-tricare/locations/naval-great-lakes-burkey-mall-pharmacy

It needs a description, services and probably a better meta.

**Comment by xiongjaneg** [comment]
@swirtSJW Thanks for the quick turnaround.

@mmiddaugh I'll update the internal notes on the Jira ticket. Will you be following up with the contact in the Jira ticket?

**Comment by xiongjaneg** [comment]
Michelle replied to editor in Jira. Will wait for acknowledgement from editor in Jira thread before closing this ticket.

**Comment by xiongjaneg** [comment]
editor confirmed 11/9/2023
