### ISSUE TITLE
Design error states for VBA content types

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#16068]
## Description or Additional Context 
Feedback from CMS collab cycle states:

> Error messages MUST be determined for all input fields prior to product launch. Use clientside validation in as many places as it makes sense to display errors prior to form submit.

[UI/UX Feedback ticket from CMS collab cycle
](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16073)

Some error messages are predetermined in Drupal. We may only need to write error messages for specific fields, but additional information will be needed from the CMS team to determine this. 

From #16073 "Determine error messages prior to launch and ensure error handling has been internally reviewed by Facilities team."

## Design
[VBA Content Specs Figma file](https://www.figma.com/file/aKdT4weNNthDxb3r6MolEh/VBA-Content-Specs?type=design&node-id=208%3A714&mode=design&t=IePMjbSbOBYTX5xg-1)

## Acceptance Criteria
- [x] Review existing error messages
- [x] Write error messages where needed
- [x] Review with @ALogsdon3 
- [x] Review with Laura for a11y
- [x] Requested review with UX Lead (or PO)

## Team
Please check the team(s) that will do this work.

- [ ] CMS Team
- [ ] Public Websites
- [x] Facilities
- [ ] Accelerated Publishing

**Comment by davidmpickett** [comment]
Do we need to add review with @aklausmeier as final AC?

**Comment by xiongjaneg** [comment]
@jilladams @mmiddaugh Noting that in UX sync we identified this ticket as one to push back on CMS Team for a number of reasons. I'll pull this out of sprint 99 while I discuss with CMS Team this specific and overall CMS Team collab cycle. Thanks!

**Comment by thejordanwood** [comment]
I've added error message suggestions in [the Figma file](https://www.figma.com/file/aKdT4weNNthDxb3r6MolEh/VBA-Content-Specs?type=design&node-id=0%3A1&mode=design&t=aqdgsKkgbvvoitmu-1).

**Comment by thejordanwood** [comment]
@ALogsdon3 @laflannery Can you review the error message suggestions in the Figma file whenever you have time?

All of these fields have existing error messages in the CMS. I've suggested new messages in Figma that follow [VA content style guidance](https://design.va.gov/content-style-guide/error-messages/). The guidance says that messages should be clear, direct, and have an actionable call to action (CTA) for the user. 

We aren't sure which messages will be updated, but the suggestions are in Figma for whenever they can be.

**Comment by laflannery** [comment]
@thejordanwood Added some comments, let me know if anything isn't clear

**Comment by ALogsdon3** [comment]
@thejordanwood I added some comments, too. I hope they're helpful!

**Comment by thejordanwood** [comment]
@laflannery @ALogsdon3 Thanks for your reviews!

**Comment by thejordanwood** [comment]
@aklausmeier This is ready for your review.

**Comment by thejordanwood** [comment]
@jilladams For reporting purposes, this ticket can be considered closed. All ACs are complete, but I'd like to leave this ticket open to capture any feedback Amanda may have. 

cc: @xiongjaneg

**Comment by davidmpickett** [comment]
Interesting example of error message behavior here that might be worth raising to CMS Team. It's possible to get multiple error messages on a single field:

![Screenshot 2024-01-16 155531](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/63292993-9a20-41d8-9b1d-b15fb4573300)

Looking at the code there seem to be two different classes for error message styling used here:
form-item__error-message
form-item--error-message

Probably should be standardized so that these classes are the same.

**Comment by jilladams** [comment]
@thejordanwood makes sense to me, and we can add new ACs to implement any feedback you get, as needed.

**Comment by davidmpickett** [comment]
@aklausmeier @thejordanwood 
FYI - I just spun up a CMS Design System ticket to document the need for Error Messages to be added to Figma, etc - #16862

No need to prioritize this. I just wanted to document the fact that these are not currently baked into the components, so Jordan had to add all these manually and there's room to streamline and standardize. There was no outstanding issue

**Comment by jilladams** [comment]
Same here - have removed Sprint 102 from ticket since it's likely complete but we can add it back to sprint if feedback leads to new ACs.

**Comment by aklausmeier** [comment]
@jilladams @xiongjaneg I think this ticket can be closed as feedback is now in #16906
