### ISSUE TITLE
Fix empty <ul> element in VAMC Staff profile page side nav

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#16063]
## User Story or Problem Statement
On Staff profile pages, there is a side nav in the left column. There is an empty `<ul>` element within the nav. Empty semantic elements create confusion for assistive tech users. Ensure that there are no empty tags (i.e. if there is a `<ul>` there are list items in it but if not, the `<ul>` does not appear in the DOM).

Go to a Staff detail page, like [this one](https://www.va.gov/salem-health-care/staff-profiles/allen-r-moye/)
Inspect the sidenav
Note that there is an empty `<ul>`

## Acceptance Criteria
- [x] Add a conditional that removes the `<ul>` if it's empty.
- [x] @laflannery has reviewed

**Comment by randimays** [comment]
Validated successfully in production. Closing as complete.

**Comment by laflannery** [comment]
And also this :)
