### ISSUE TITLE
Draft Federal Header/Footer conversation guide

### ISSUE THREAD

**Issue by cindymerrill** [department-of-veterans-affairs/va.gov-cms#16072]
### User story
**AS A** Researcher
**I WANT** to document the details for conducting Header/Footer usability sessions
**SO THAT** the research will achieve the stated goals and answer the research questions

### Sprint 97 (8 pts):
- [x] Brainstorm potential tasks and discuss with Amanda
- [x] Create initial draft of conversation guide for Phase 1 (non-AT)
- [x] Solicit feedback from Sitewide UX Lead 
- [x] Solicit feedback from VA Product Owner (PO) async or in a meeting w/PM -- Amanda will talk w/Dave C on Nov 22

### Sprint 98 (5 pts):
- [x] Revise per feedback from VA PO
- [x] Post on github in project research folder for final approval before submitting to Research Review cycle
- [x] Test prototype(s) with conversation guide and align
- [x] Update in Enjoy HQ -- DEFERRED to prep tasks ticket so plan to do when launch recruiting (because there will be more small tweaks until then)

### Future sprints:
- [ ] Make new version of convo guide for Phase 2 (AT), and go through reviews again

## Acceptance Criteria
- [x] Conversation guide for Phase 1 drafted
- [x] Feedback incorporated from Sitewide UX Lead 
- [x] Feedback incorporated from VA PO and Sitewide UX Lead
- [x] Conversation guide posted on github in project research folder
- [x] Final approval obtained from Sitewide UX Lead and documented at the bottom of the file in preparation for Research Review cycle
- [x] Conversation guide aligns with prototype(s)

**Comment by cindymerrill** [comment]
Brainstormed ideas and considerations for user tasks to discuss with Amanda tomorrow. Doc in Sharepoint: https://dvagov.sharepoint.com/:w:/r/sites/SitewidePublicWebsites/Shared%20Documents/PW%20products/Federal%20Header%20Footer/Federal%20Header%20Footer%20Conversation%20Guide%20Ideas.docx?d=w6d2f43cdb5d9421c8a57bd9e819f3872&csf=1&web=1&e=c6wHkK

**Comment by aklausmeier** [comment]
@cindymerrill FYI: added a future sprint AC to add conversation guide to EnjoyHQ with link to project once it's been approved

**Comment by cindymerrill** [comment]
Here's my initial draft of the convo guide for Phase 1 (non-assistive tech users and Figma prototypes): https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/header-footer/federal-standardized-header-footer/research/phase1-no-AT/conversation-guide.md

Ideally (but not required) I'd take a look at any header analytics that @FranECross can dig up before I share this with Amanda for review, in case there are other high-usage header links that might suggest additional user tasks. I plan to share the convo guide with Amanda by end-of-day Thursday for her review.

**Comment by FranECross** [comment]
@cindymerrill Thank you! I hope to have Header analytics for you by EOD today (it's not as straightforward getting them as footer's were.).

**Comment by FranECross** [comment]
@cindymerrill Just closing the loop here (and I replied in Slack too 😁 ), I've gathered and organized Header [analytics ](https://docs.google.com/spreadsheets/d/1S28kXIkYqsETizQftn_ZpJ0tD-QSFrU9rwMxJBo8mkY/edit#gid=1258076082) for August 2023. Thanks! cc @jilladams

**Comment by cindymerrill** [comment]
@FranECross Looks to me like the greatest numbers of clicks by far are in the _VA Benefits and Health Care_ megamenu (as I'd expect) with next most clicks on _Contact Us_ and _About VA._ I'm surprised that there aren't more clicks on _Find a VA Location_. 

I'm trying to understand why the first _About VA_ row in your spreadsheet (line 32) has most of the clicks. Is that people clicking on the _About VA_ link but then nothing underneath it (so they probably didn't find what they were looking for)? The numbers on all links on that page are low.

Yesterday I added a user task about contacting the VA, and I think that's supported by the analytics. I already have another task that would drive participants to the megamenu.

Less relevant for my unauthenticated research, but...I don't understand why there are so many different URLs for the sign-in link, except if it's actually showing the analytics for anytime a user logged in--not only from the header. I'm wondering if these analytics include every time a sign-in button is clicked on a content page (i.e., because you're about to apply for something). Could you figure out if this is the case? If so, then this shouldn't be reported as header analytics.

**Comment by cindymerrill** [comment]
Hi @aklausmeier ! When you have time (Friday or next week), my draft [conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/header-footer/federal-standardized-header-footer/research/phase1-no-AT/conversation-guide.md) and [list of prototype screens needed](https://dvagov.sharepoint.com/:w:/r/sites/SitewidePublicWebsites/Shared%20Documents/PW%20products/Federal%20Header%20Footer/Federal%20Header%20Footer%20Conversation%20Guide%20Ideas.docx?d=w6d2f43cdb5d9421c8a57bd9e819f3872&csf=1&web=1&e=jJDuPJ) are ready for your review.

FYI I'm going to be out the day before and after Thanksgiving, so only working Mon-Tue next week.

**Comment by aklausmeier** [comment]
@cindymerrill and I will meet on Monday to finalize conversation guide

**Comment by cindymerrill** [comment]
Today Amanda provided feedback on the convo guide, and I made revisions. When we meet on Monday, we plan to discuss a few open items and also the screens needed for prototyping.

**Comment by cindymerrill** [comment]
Today discussed convo guide and list of prototype screens with @aklausmeier , and then made revisions to both and shared for feedback. Amanda plans to review both early tomorrow (Tuesday) and let me know if she has any feedback that requires revisions. I can make revisions on Tuesday by end-of-day. On Wednesday when I'm out, Amanda plans to share with Dave C and Mikki for review. When I return next Monday (Nov 27), I can make any revisions needed and answer any questions that Jordan may have about prototype needs.

**Comment by cindymerrill** [comment]
Made a few more changes based on slack conversations and one more revision from Amanda. Left some comments in the prototype screen doc that need resolving.

**Comment by aklausmeier** [comment]
@cindymerrill go ahead and share convo guide in Slack to share with Dave for his review as you normally would since it's ready

**Comment by cindymerrill** [comment]
Done! @aklausmeier 
Slack thread here: https://dsva.slack.com/archives/C52CL1PKQ/p1700588213467489

**Comment by cindymerrill** [comment]
Amanda shared feedback from Dave Conlon, I revised the convo guide and list of prototype screens, and I got Amanda's approval. Next is to align tasks and prompts with the prototypes that Jordan will be creating in Figma.

**Comment by cindymerrill** [comment]
Made revisions to align with new auth flow in prototypes, which Amanda requested.

Will wait to update in EnjoyHQ until recruiting is launched because there might be more small tweaks until then.

**Comment by cindymerrill** [comment]
Finished last revisions to convo guide, until final check with revised prototypes when they're ready (tomorrow?). Closing ticket with end of sprint because any additional tweaks will be covered by the AC in the research-prep tasks ticket. FYI @FranECross @jilladams

**Comment by cindymerrill** [comment]
On second thought, I'm closing this ticket and will plan to create a new one for the phase 2 research with assistive tech users in early 2024. FYI @jilladams @FranECross @aklausmeier
