### ISSUE TITLE
Add envs vars for next-build to all tugboat envs

### ISSUE THREAD

**Issue by tjheffner** [department-of-veterans-affairs/va.gov-cms#16078]
## User Story or Problem Statement
For CMS preview functionality with next-build on all tugboat environments, certain environment variables need to be present:
```
OAUTH_PUBLIC_KEY=
OAUTH_PRIVATE_KEY=
DRUPAL_CLIENT_ID=
DRUPAL_CLIENT_SECRET=
```
These have been added to the CMS PR environment settings here: https://tugboat.vfs.va.gov/5fd3b8ee7b4657022b5722d6/settings/

They are missing from other CMS tugboat environments, namely the CMS MIRROR project that the next-build repo points to.

AP isn't building next-build on BRD environments yet (though we will need to go to staging in a couple sprints for CMS preview), these same values will need to be added there too.

## Description or Additional Context 
`OAUTH_PUBLIC_KEY=` [https://us-gov-west-1.console.amazonaws-us-gov.com/systems-manager/parameters/cms/staging/drupal_a[…].key/description?region=us-gov-west-1&tab=Table](https://us-gov-west-1.console.amazonaws-us-gov.com/systems-manager/parameters/cms/staging/drupal_api_users/next_build_api/public.key/description?region=us-gov-west-1&tab=Table#list_parameter_filters=Name:Contains:next_build_api)

`OAUTH_PRIVATE_KEY=`[https://us-gov-west-1.console.amazonaws-us-gov.com/systems-manager/parameters/cms/staging/drupal_a[…].key/description?region=us-gov-west-1&tab=Table](https://us-gov-west-1.console.amazonaws-us-gov.com/systems-manager/parameters/cms/staging/drupal_api_users/next_build_api/private.key/description?region=us-gov-west-1&tab=Table#list_parameter_filters=Name:Contains:next_build_api)

`DRUPAL_CLIENT_ID=` https://us-gov-west-1.console.amazonaws-us-gov.com/systems-manager/parameters/cms/consumers/next-build/client_secret/description?region=us-gov-west-1&tab=Table#list_parameter_filters=Name:Contains:next-build

`DRUPAL_CLIENT_SECRET=` https://us-gov-west-1.console.amazonaws-us-gov.com/systems-manager/parameters/cms/consumers/next-build/client_id/description?region=us-gov-west-1&tab=Table#list_parameter_filters=Name:Contains:next-build

slack thread with convo: https://dsva.slack.com/archives/CT4GZBM8F/p1698773025811489
related ticket / PR:  #15795 #15936 

## Steps for Implementation
Add the above environment variables to these (I believe it is these) tugboat settings as well:
https://tugboat.vfs.va.gov/6042eeed6a89945a99399d3d/settings/ < CMS PROD MIRRORS [the environment where next-build repo points to by default is built in this project]
https://tugboat.vfs.va.gov/5ffe2f4dfa1ca136135134f6/settings/ < CMS DEMO ENV
https://tugboat.vfs.va.gov/5fd114f1c65644f68f6376ea/settings/ < CMS-TEST

If it is low-effort to add these variables to the appropriate non-production BRD environments as well, please do so. ❤️ 

## Acceptance Criteria
- [ ] Tugboat environments built under any of the cms projects contain the necessary environment variables

## Team
Please check the team(s) that will do this work.

- [x] CMS Team
- [ ] Public Websites
- [ ] Facilities
- [x] Accelerated Publishing

**Comment by olivereri** [comment]
- [x] CMS PR Envs
- [ ] CMS Demo Envs
- [ ] CMS-TEST Pull Request Envs
- [ ] CMS ProdMirrors
