### ISSUE TITLE
[CONSIDER] Make CMS the source of truth for VCL Suicide Prevention Coordinator contact information

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-cms#16087]
## Value to Veterans
Currently, there are at least three disparate sources for Suicide Prevention Coordinator contact information. This means the information displayed to Veterans (and those working on their behalf) depends on the resource or tool used. Information is different, at a minimum - if not entirely inaccurate.  -

## Headlines
**OCTO owner** - Michelle Middaugh
**Is request tracked to an event or Congressional deadline?** - No

## Details
**Who is the primary user?**
- Veterans and beneficiaries
- Suicide Prevention Coordinators acting on behalf of Veterans

**What are the user goals for the project/page/product?**
To improve data accuracy for Veterans seeking this important information while creating a more efficient process for maintaining the data 

## Background
- Kimberly Woehr maintains the contact information for Suicide Prevention Teams in 
  - VHA Sharepoint Power BI Dashboard (SPC Contact list)
  - Facilities and Leadership Directory, which powers the VCL Resource Locator via weekly uploads  
- This data is referenced by VCL Crisis Line Responders, by Suicide Prevention Coordinators searching for their colleagues, and in the VCL Resource Locator 
- During July 2023, a JSON error prevented recently updated Facility and Leadership Directory data from being available in the VCL Resource Locator, resulting in a xxx
- Contact information for Suicide Prevention Coordinators is required per Station ID (VA Medical Center)
- Suicide Prevention Teams are required to have voicemail and to respond within 24 hours. Teams are encouraged to establish a team phone number so that multiple coordinators might be available to respond. 
- Contact information for Suicide Prevention Coordinators is also entered into CMS by PAOs in the field. This data is frequently entered as a named individual with direct phone numbers (rather than using the Team number)

## Relevant Policy
As mandated by VHA Directive 1160.07, Suicide Prevention Program, 
- each VA medical center and community-based outpatient clinic (CBOC) large enough to serve more than 10,000 unique Veterans per year must appoint and maintain at least one clinically trained suicide prevention coordinator (SPC) with a full-time commitment to suicide prevention activities. 
- Facilities are required to enter all Suicide Prevention Program (SPP) staff and vacant positions into the VHA Support Service Center Patient Centered Management Module (PCMM)

**Comment by Agile6MSkinner** [comment]
Capturing this outside of GitHub and closing as not planned. We can re-open if we decide to work on it in the future.
