### ISSUE TITLE
FE: Update Beneficiary Tag logic to accommodate multi-select

### ISSUE THREAD

**Issue by randimays** [department-of-veterans-affairs/va.gov-cms#16099]
## Description

In support of #13188, update the FE templates and logic in content-build so Beneficiary Tags support a multi-select rather than a radio button.

Current implementation (radio button)
<img width="329" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/4054752/d90fc2e6-c30a-4454-a5dc-e82f0cf7a1be">

See https://www.va.gov/resources/will-i-have-to-pay-back-the-gi-bill-benefits-i-used-if-i-fail-a-class/ for example of Tag usage in production.

Refer to [this comment](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15743#issuecomment-1802223185) for an overview of what FE content-build files are affected / what changes need to be made. There are also instructions on how to validate everything in the Tugboat instance for these changes.

### Quality / testing notes

All of these CMS content types / nodes need to be validated for correct functionality. See [this comment](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15743#issuecomment-1802223185) for instructions on how to add each one to a Tugboat to test with your WIP branch.

- checklist
- media_list_images
- media_list_videos
- step_by_step
- faq_multiple_q_a
- q_a
- support_resources_detail_page 

We also need to update relevant unit test(s):
- `liquid.unit.spec.js` after changes to `getTagsList` utility
- If possible, add tests for `create-resources-and-support-section.js`'s `groupByTags` utility

## Acceptance criteria
- [ ] For all 6 affected content types: all Beneficiaries checked for a particular article appropriately display as tags on that article and link to tag pages
- [ ] Unit tests are updated
- [ ] README is updated

**Comment by FranECross** [comment]
@jilladams @chriskim2311 I added AC to this story (as discussed in refinement today). Please review when you can and let me know if anything seems amiss/is missing/needs to change. Thanks in advance!

**Comment by jilladams** [comment]
@FranECross made a couple edits: 
* Relocated the ACs re: the CMS UX (checkboxes vs. radio buttons) and the KB article into the backend ticket, #13188 
* Added a note to the "Beneficiaries checked for a particular article appropriately display" AC to indicate that Tags should link through to Tag pages. (That's true in Prod where they appear today, and we just don't wanna regress it / should do that for new tags appearing.)
* I didn't modify the README AC but  I'm not sure which README is in mind - possible to add a link to that, so Eng knows what needs the update?

**Comment by chriskim2311** [comment]
Just pulled this in on Monday. Will carry over into next sprint.

**Comment by jilladams** [comment]
Deployed. Closing. CAIA will need to verify in Prod.
