### ISSUE TITLE
Display issue with Rich text editor toolbars

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#16098]
## Describe the defect
The toolbar on the Rich Text editors is not displaying properly, it's too wide for the editor itself

![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/106678594/5994edd0-b399-4f4b-b1fe-6cd3997ebc23)

![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/106678594/85369ed9-0f0e-4f32-996e-af92efd38d02)

## To Reproduce
1. Go to a node, [example](https://vacms-12252-drupal-10-opslrfeufzwsvhxx2uuv1wmvjbiq7wuq.ci.cms.va.gov/node/63204/edit)
2. Scroll down.
3. Notice that the editors have a toolbar that is too wide

## AC / Expected behavior

- [ ] The toolbar width should match the width of the rich text editor

### Team
Please check the team(s) that will do this work.

- [x] `CMS Team`
- [ ] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`
- [ ] `Accelerated Publishing`

**Comment by edmund-dunn** [comment]
This has been fixed and merged into the D10 branch.
