### ISSUE TITLE
Data points for custom Facility Locator Domo Dashboard

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#16121]
## User Story or Problem Statement
As a Facilities team member, I want access to data about user experience with Facility Locator. Domo displays the results of customer satisfaction surveys on VA.gov.

[Read more about Domo](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/how-to-use-medallia-data-in-domo)

[Example Domo dashboard](https://va-gov.domo.com/page/1030131175) (requires Domo access)

Platform Analytics will be creating a custom Domo dashboard with Facility Locator data. What customer satisfaction data might be helpful to view on a dashboard in addition to those listed below?

- User data: New/returning, Mobile/desktop 
- Previous page visited (which page(s) directs the most Veterans to us?)  
- Clickthrough rate from search results to facility detail pages, such as https://www.va.gov/find-locations/facility/vba_346b or modernized VAMC/Vet Center pages (and by facility type...do more users clickthrough for VA health or VA benefits, for example) 
- number of users who visit the page and perform a search  
- use of "escape hatch" -> "Try using our other tools to search" link below the map (and other links such as the clickthrough to Emergency care info for community care) 
- Average position of search result for clickthrough and by facility type (do they usually clickthrough on one of the first 3 search results fo VA health but the first 10 for community care, for example) 
- Facility type search distribution – percent of VA health searches vs other facility types 
- Service type search distribution – how often is a service type specified for each (when relevant) and which are the most common 
- search refinements by facility type – how often do they change search parameters and fire a new search – via map interaction or with search box 
- Number/percent of searches which do not return search results 
- CSAT/Foresee aggregates and by facility type 

## Acceptance Criteria
- [ ] Additional data points are added in comments

**Comment by xiongjaneg** [comment]
- The amount of time between the initial search and clicking one of the results (how long did it take, not necessarily the click-through rate)

**Comment by jilladams** [comment]
@xiongjaneg could you add an end of sprint update for this one? (We don't typically need to report on PM work but it was listed in sprint. If this should be tracked outside sprint boundaries, feel free to just remove the Sprint value from it.)

**Comment by xiongjaneg** [comment]
@jilladams Apologies on the lack of update. This is done.
