### ISSUE TITLE
Incorrect alignment of new National Outreach Events checkbox

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#16126]
## Describe the defect
On the Events content type, there is a new checkbox to add the event to the National Outreach calendar. This checkbox is not left aligned properly, it's too far to the left:

**D10**
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/106678594/69d7c925-b248-4d90-a8e6-38b575986154)

**Prod**
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/106678594/57cf0568-15eb-486c-bf01-dd9a1a166220)

## To Reproduce
1. Go to an event, [example](https://vacms-12252-drupal-10-opslrfeufzwsvhxx2uuv1wmvjbiq7wuq.ci.cms.va.gov/node/63283/edit)
2. Scroll down to the National Outreach calendar checkbox
3. Notice that the checkbox is farther left than the rest of the fields

## AC / Expected behavior

- [ ] National outreach checkbox should be left aligned with with rest of the fields

 ## Additional context
This was added quite recently by Daniel Sasser on the Public Websites team

### Team
Please check the team(s) that will do this work.

- [x] `CMS Team`
- [ ] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`
- [ ] `Accelerated Publishing`

**Comment by laflannery** [comment]
Adding CMS team to review and triage, not positive if this will need to be resolved by the PW team ultimately though.

CC: @FranECross

**Comment by edmund-dunn** [comment]
This has been fixed. Verified it was fixed on the D10 tugboat. Closing.
