### ISSUE TITLE
D10: New Block Content Admin Page

### ISSUE THREAD

**Issue by dsasser** [department-of-veterans-affairs/va.gov-cms#16139]
## Description
In D10, there is a new block content administration page at /admin/content/block. The admin menu is taking users to this new page from Admin->Structure->Block Layout->Block content library.

![Screenshot 2023-11-15 at 9 26 27 AM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/221539/5dccfbb4-ea0c-41a6-824b-f8e3c2ac401a)

![Screenshot 2023-11-14 at 10 44 55 AM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/221539/df115df6-fd24-4a1a-9d4c-f29e62493779)

The new page lacks appropriate columns and filters found on the previous page (admin/structure/block/block-content).

![Screenshot 2023-11-14 at 10 45 01 AM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/221539/7ce1abee-5845-4a50-990f-1d80591df6d4)

The old page is still around and can be hit directly, but is no longer at the menu location expected.

### Engineering notes / background
Originally reported [here](https://dsva.slack.com/archives/C05EJD52H1R/p1699987372067699).

## Acceptance criteria
- [ ] Admin->Structure->Block Layout->Block content library takes the users to admin/structure/block/block-content, or the new page is otherwise improved to match the functionality and layout of the old page.

**Comment by edmund-dunn** [comment]
This changed in 10.1 per https://www.drupal.org/node/3320855

**Comment by edmund-dunn** [comment]
I was able to fix this by changing the URL for our view to the new content block URL `/admin/content/block` which fixed the issue.

**Comment by edmund-dunn** [comment]
Verified this was fixed on the D10 tugboat. Closing.
