### ISSUE TITLE
Add CMS test coverage for VBA banner.

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#16146]
## User Story or Problem Statement
VBA banners were added with https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14700

It would be good to have test coverage of that permutations that collection of fields.  (maybe use similar to person profile test)

## Acceptance Criteria
- [ ] Test coverage of permutations of VBA banners.

## Team
Please check the team(s) that will do this work.

- [ ] CMS Team
- [ ] Public Websites
- [x] Facilities
- [ ] Accelerated Publishing

**Comment by xiongjaneg** [comment]
@swirtSJW Is this for pilot MVP or later?

**Comment by xiongjaneg** [comment]
PW did similar tests for CLP widgets. This would be implementing a similar pattern (step functions) here.

**Comment by swirtSJW** [comment]
> @swirtSJW Is this for pilot MVP or later?

Sorry I missed this question.  It is for later.  We can do testing on banner fields in the CMS regardless of what the FE does with them.  So we do not have to wait for MVP.
