### ISSUE TITLE
Plan to Bifurcate the appointment description default based on whether it's in VBA or VAMC Service Location

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#16153]
## User Story or Problem Statement
Appointment description default text will be used in both VAMC and VBA products. Currently, the default text comes from VAMC facility health service and would be applied to both VAMC and VBA. However, the default text may not apply to VBA. The default has to be different based on whether it's in the VBA or VAMC product.

Implementing the plan would likely take place in 
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15559

## Acceptance Criteria
- [x] A documented plan to account for this default text for both VAMC and VBA and possibly others.

## Proposed plan
_Note: This plan assumes that we only need one default text for VAMC facility services and another for VBA facility services, as opposed to different default text for the type of service, too._
- Add appointment introduction text-related fields to Service Location paragraph
- Add a fieldset to the Service Location form for appointment introduction text-related fields ([mirroring the Figma design](https://www.figma.com/file/aKdT4weNNthDxb3r6MolEh/VBA-Content-Specs?type=design&node-id=218-715&mode=design&t=HgXBnMWY1AGHCHxx-0))
- Add a markup field for "Appointment lead-in default" to the VBA facility service content type to hold the default text (a fraternal twin to the same field on the VAMC facility health service content type)
- Add a markup field for "Appointment lead-in default" to the Service region content type to hold the default text
- Add a markup field for "Appointment lead-in default" to the VAMC facility non-clinical service content type to hold the default text
- Refactor code from va_gov_backend that handles the logic for the appointment introduction text for the new service location fields and accounts for the VAMC facility health service, VAMC facility non-clinical service , VBA facility service and Service region content types, putting the new code va_gov_facilities.
- Do all of the above in its own ticket, separate from migration but merging to an integration branch to support the migration effort.

## Ticket for proposed plan
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16348

**Comment by swirtSJW** [comment]
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15559

**Comment by omahane** [comment]
@xiongjaneg @jilladams I believe this is done.

**Comment by jilladams** [comment]
Closeable?
