### ISSUE TITLE
Update Breadcrumbs in Facilities products to use component

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#16157]
## Description
Facilities location templates do not currently use the `<va-breadcrumbs>` component. This is built in such a way that changing one template, changes multiple different sites (VAMC, Vet Centers, VBA Facilities, etc). This ticket is to determine they best way to update the breadcrumbs across products to use the component.

### Considerations
- We should get a full list of everywhere breadcrumbs are used and where they need to be updated
- We should determine whish of those instances would get changed all at once, and would therefore need to be tested and QA'ed at the same time
- v3 component is available so we will want to be sure that we use that when we get to this

## Acceptance Criteria
- [ ] Testable_Outcome_X
- [ ] Testable_Outcome_Y
- [ ] Testable_Outcome_Z
- [ ] Requires design review
- [ ] Requires accessibility review

**Comment by laflannery** [comment]
@jilladams I don't remember making this but I can close it now because it's covered by the other tickets the DST took over right?

**Comment by jilladams** [comment]
Yes. Laura today knew things Laura in Nov 2023 didn't know yet, and the breadcrumbs tickets in content-build that the DST owns will now cover this. Closing.
