### ISSUE TITLE
Design VAMC service accordion to align with VBA service accordion

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#16154]
## User Story or Problem Statement
VAMC Facility Service appointment information will be migrated into updated Service Location to align with appointment information location in VBA RO MVP. A design showing how VAMC service accordions will look after migration will help front end engineers understand changes, such as a box around content, order of content, etc.

[VBA service accordion example in Sketch](https://www.sketch.com/s/891d33ae-152d-471c-ab5d-9aedf89cf6ff/p/DC11E46F-AF92-4DFD-AC0B-BEB9A9DD3C9A/canvas)

[Mural of VAMC service accordion migration](https://app.mural.co/t/departmentofveteransaffairs9999/m/vagov6717/1677277602711/74cecb64b6eeb9558aa868240cd726b54fcb93a7?sender=u25440eff886a526ece257322)

## Design

- [VAMC Sketch file](https://sketch.com/s/8bda90fd-99e8-4761-9210-3a24282eb811) (FE design)
- [VAMC Figma file](https://www.figma.com/file/W4oO1UO0ilSgHu1kXf1Sj0/VAMC-facilities?type=design&node-id=709%3A18411&mode=design&t=ZdR0WAtcQExW2Mte-1) (Drupal design)

## Out of scope
Add more button label issue #16452 is out of scope as a CMS Team ticket and should not be considered as part of this ticket

## Acceptance Criteria - Sprint 99 (5 points)
- [x] Create design in Sketch for Front End
- [x] Create design in Figma for Drupal
- [x] Review with Content Designer (Dave)
- [x] Review with accessibility (Laura)
- [x] Review with UX Lead (Amanda)

## Acceptance Criteria - Sprint 100 (5 points)
- [x] Update mockup with feedback
- [x] Request UX lead review / signoff (Amanda) - 48h

**Comment by davidmpickett** [comment]
@davidmpickett to refine

**Comment by thejordanwood** [comment]
I've created the FE design for this and reviewed with @davidmpickett. It can be found on the Service accordion page in [this Sketch file](https://sketch.com/s/8bda90fd-99e8-4761-9210-3a24282eb811).

**Comment by thejordanwood** [comment]
I've created the Drupal design for this and reviewed with @davidmpickett. It can be found on the VAMC services page in [this Figma file](https://www.figma.com/file/W4oO1UO0ilSgHu1kXf1Sj0/VAMC-facilities?type=design&node-id=709%3A18411&mode=design&t=ZdR0WAtcQExW2Mte-1).

**Comment by davidmpickett** [comment]
[Slack thread for feedback](https://dsva.slack.com/archives/C0FQSS30V/p1702504668882679)

**Comment by xiongjaneg** [comment]
Noted in ticket description that Add more button label defect is out of scope for this ticket #16452

**Comment by jilladams** [comment]
@thejordanwood @xiongjaneg same here -- updated ACs with status as of today, given that Amanda gave first round feedback. Feel free to update as needed.

**Comment by thejordanwood** [comment]
@aklausmeier @davidmpickett I've updated the [VAMC Figma file](https://www.figma.com/file/W4oO1UO0ilSgHu1kXf1Sj0/VAMC-facilities?type=design&node-id=709%3A18411&mode=design&t=ZdR0WAtcQExW2Mte-1) and responded to the feedback you had. I think this is final, but let me know if there was anything that I missed. 

There was no feedback about the FE design in the [VAMC Sketch file](https://sketch.com/s/8bda90fd-99e8-4761-9210-3a24282eb811), so I'm assuming that's approved.

**Comment by aklausmeier** [comment]
@thejordanwood both files look good, checking off UX review AC which appears to be the last AC but I'll let you close ticket when you are ready
