### ISSUE TITLE
Review of new or updated KB article : VAMC and VBA Service Locations and appointment information

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#16156]
## Which article(s) need review?
Any article related to Service Locations and appointment information that will be affected by #14837
[Working document of appointment changes](https://app.mural.co/t/departmentofveteransaffairs9999/m/vagov6717/1677277602711/74cecb64b6eeb9558aa868240cd726b54fcb93a7?sender=u9c899abc4fe36c9a698b1647)

Provide the link to latest revision of each article that requires review.
- [x] [How to add or edit a VAMC facility health service](https://prod.cms.va.gov/help/vamc/how-to-add-or-edit-a-vamc-facility-health-service)
- [x] [How to create a VAMC System Medical Records Office page](https://prod.cms.va.gov/help/vamc/how-to-create-a-vamc-system-medical-records-office-page)
- [x] [How to create a VAMC System Register for Care Page](https://prod.cms.va.gov/help/vamc/how-to-create-a-vamc-system-register-for-care-page)
- [x] [How to edit a billing and insurance VAMC page](https://prod.cms.va.gov/help/vamc/how-to-edit-a-billing-and-insurance-vamc-page)
  
## Priority or deadline for request
Choose either Deadline or a priority:

- [ ] Deadline: [name the deadline here]
- [ ] Priority:
  - [ ] Critical
  - [ ] High
  - [ ] Medium
  - [x] Low
  
## Can article(s) be published?
Once the article has been fully reviewed, can the article(s) be published? For example, is anything tied directly to an upcoming feature and this information should not be published until the feature is on production?
- [ ] Yes, all article(s)s within this ticket can be published once reviewed
- [x] No, the article(s) within this ticket should not be published and should only be reviewed

## Acceptance Criteria - Sprint 98 (2 points) 
- [x] Affected articles are identified and listed above

## Product tasks
- [x] Article reviewed by CMS Team
- [ ] Updated articles are published (timed to coincide with Service Locations launch)
- [ ] CMS Support team is notified in Slack for awareness

**Comment by davidmpickett** [comment]
@xiongjaneg 

This is the main article that will need to be updated. This is where there will be the most obvious changes.
- [How to add or edit a VAMC facility health service](https://prod.cms.va.gov/help/vamc/how-to-add-or-edit-a-vamc-facility-health-service)

In addition, these three pages should be reviewed for edits. They all reference the process of creating a VAMC Facility **non-clinical** service. The non-clinical services will now have some new options that didn't exist previously. It also might be worth considering breaking off "how to add or edit a VAMC Facility non-clinical service" into a new article that all three of these article reference, rather than having all the steps related to non-clinical services repeated in three separate articles.
- [How to create a VAMC System Medical Records Office page](https://prod.cms.va.gov/help/vamc/how-to-create-a-vamc-system-medical-records-office-page)
- [How to create a VAMC System Register for Care Page](https://prod.cms.va.gov/help/vamc/how-to-create-a-vamc-system-register-for-care-page)
- [How to edit a billing and insurance VAMC page](https://prod.cms.va.gov/help/vamc/how-to-edit-a-billing-and-insurance-vamc-page)

**Comment by xiongjaneg** [comment]
@jilladams For your reporting, Dave's 2 points on this ticket can be considered done. The rest is my work and then sending it to CMS Team for review.

**Comment by jilladams** [comment]
@xiongjaneg  Perfect, thx - I revised the ACs area in such a way that I'll remember this in reporting, but feel free to modify that if you have any concerns about how that's now framed.

**Comment by xiongjaneg** [comment]
edits made to health service and submitted to VHA DM for review, once approved will copy to other articles

**Comment by xiongjaneg** [comment]
approved by VHA DM with addition of images

**Comment by jilladams** [comment]
@xiongjaneg can this one be closed out? Or the copying to other articles is still outstanding?

**Comment by xiongjaneg** [comment]
@jilladams Yes, I added an AC, they need copying and publishing timed along with launch.

**Comment by jilladams** [comment]
@xiongjaneg sorry to be obtuse, just making sure I know which launch -- is that with Service Location launch, yes?

**Comment by xiongjaneg** [comment]
Not obtuse at all, I updated the title and description to be more clear that this is related to Service Locations

**Comment by davidmpickett** [comment]
Moving this to Complete Pending Integration to reflect that there will be steps for this during the VAMC/VBA service location launch but otherwise is done

**Comment by davidmpickett** [comment]
Hey @xiongjaneg I was able to pretty easily find the draft revisions that will need to be published for three of the four articles
- https://prod.cms.va.gov/node/44552/revisions/view/845709/846918/visual_inline
- https://prod.cms.va.gov/node/44536/revisions/view/845721/846921/visual_inline
- https://prod.cms.va.gov/node/44150/revisions/view/845716/846919/visual_inline

But I'm having trouble finding a straightforward draft revision for _How to add or edit a VAMC facility health service_ that's ready to publish. Looks like you had one ready to go, but then the Mental Health phone number changes came in and knocked it out. Can you identify/create a draft revision that's ready to launch?
- https://prod.cms.va.gov/node/23473/revisions

**Comment by xiongjaneg** [comment]
@davidmpickett Yeah, the timing was tough on that one. The last draft before mental health number updates is this one: https://prod.cms.va.gov/node/23473/revisions/846911/view

**Comment by davidmpickett** [comment]
Okay I think I got it :) There was one other minor change in an early paragraph I needed to add as well to get a new draft revision lined up with the current state + your earlier draft. Now is ready for launch again
https://prod.cms.va.gov/node/23473/revisions/851618/view

**Comment by davidmpickett** [comment]
Revisions are published:

- https://prod.cms.va.gov/help/vamc/how-to-add-or-edit-a-vamc-facility-health-service
- https://prod.cms.va.gov/help/vamc/how-to-create-or-edit-a-vamc-system-register-for-care-page
- https://prod.cms.va.gov/help/vamc/how-to-create-or-edit-a-vamc-billing-and-insurance-page
- https://prod.cms.va.gov/help/vamc/how-to-create-or-edit-a-vamc-system-medical-records-office-page
