### ISSUE TITLE
Review of new or updated KB article : Vet Center Featured Content becomes Spotlight

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#16170]
## Which article(s) need review?
Provide the link to latest revision of each article that requires review.
- https://prod.cms.va.gov/node/19161
- https://prod.cms.va.gov/help/vet-centers/vet-center-content-review

For a consistent editor experience, we are changing "Featured Content" to "Spotlight" in the Vet Center editorial interface.

Vet Centers product page also had updated link text from the [Vet Centers KB page](https://prod.cms.va.gov/help/vet-centers).
  
## Priority or deadline for request
Choose either Deadline or a priority:

- [ ] Deadline: [name the deadline here]
- [ ] Priority:
  - [ ] Critical
  - [ ] High
  - [ ] Medium
  - [x] Low
  
## Can article(s) be published?
Once the article has been fully reviewed, can the article(s) be published? For example, is anything tied directly to an upcoming feature and this information should not be published until the feature is on production?
- [x] ~~Yes, all article(s)s within this ticket can be published once reviewed~~ Article is already published to coincide with merging PR. Post publishing edits can be published as needed.
- [ ] No, the article(s) within this ticket should not be published and should only be reviewed
  
## Notify the CMS team of this ticket in the cms-support Slack channel.
- [x] I acknowledge that I must notify #cms-support after submitting this issue.

## Acceptance Criteria
- [x] Article reviewed by CMS Team
- [ ] Requesting person/team has been notified that article was reviewed

**Comment by BerniXiongA6** [comment]
I can take this in the current sprint. Will circle back with any feedback @xiongjaneg cc: @maortiz-27-80

**Comment by xiongjaneg** [comment]
ok to close per Berni
