### ISSUE TITLE
Facility Locator search result directs user to legacy detail page

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-cms#16177]
## Describe the defect
Facility Locator search result directs user to legacy detail page rather than to the modernized page

## To Reproduce
1. Go to Facility Locator, enter Cheyenne, Wyoming for the geographic parameter and VA health as Facility type -> [Link to search](https://www.va.gov/find-locations/?address=cheyenne&bounds%5B%5D%5B%5D=-105.570246&bounds%5B%5D%5B%5D=40.389981&bounds%5B%5D%5B%5D=-104.070246&bounds%5B%5D%5B%5D=41.889981&bounds%5B%5D%5B%5D%5B%5D=-105.570246&bounds%5B%5D%5B%5D%5B%5D=40.389981&bounds%5B%5D%5B%5D%5B%5D=-104.070246&bounds%5B%5D%5B%5D%5B%5D=41.889981&context=Cheyenne%2C%20Wyoming%2C%20United%20States&facilityType=health&latitude=41.139981&longitude=-104.820246&page=1&radius=64&serviceType&bounds%5B%5D=-105.570246&bounds%5B%5D=40.389981&bounds%5B%5D=-104.070246&bounds%5B%5D=41.889981)
2. Click Enter
3. Scroll down to search result "C": Northern Colorado VA Clinic
4. Click on the facility name
5. Observe that the link directs to the legacy detail page -> https://www.va.gov/find-locations/facility/vha_442GE
6. In a new tab, visit [Northern Colorado VA Clinic's modernized page](https://www.va.gov/cheyenne-health-care/locations/northern-colorado-va-clinic/)

## AC / Expected behavior
Search results should direct to the modernized page, when available

## Screenshots
<details> 
<summary> Facility Locator screenshot </summary> 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN1R4QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2f68c566f9c6b88cee0f1909d754b73fdfc92138/image.png)
</details> 

<details> 
<summary> Legacy page screenshot </summary>
 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN1h4QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0ad9696253612268dde46ec790902b7eb9855a3f/image.png)

</details> 

<details> 
<summary>Modernized page screenshot </summary>

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN1B4QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--39048ed9b21b72709c40cd5ae74b3a60db1a793d/image.png)
</details>

**Comment by xiongjaneg** [comment]
Closing. Lighthouse has to make this change as Facilities no longer has access to this and until Lighthouse uses Drupal as the source for these urls. Steve will address with Adam.

**Comment by swirtSJW** [comment]
Addressed [here in slack](https://dsva.slack.com/archives/C02BTJTDFTN/p1700664393977769)
