### ISSUE TITLE
Update CMS team "how we work" documentation

### ISSUE THREAD

**Issue by cmaeng** [department-of-veterans-affairs/va.gov-cms#1617]
## Description
Update GitHub documentation with latest team member info and more details on how we work.

## Acceptance Criteria
- [ ] Everyone on the team has filled out the Team Member User Manual specific to them
- [ ] This information is availalble in our repo

## Labels
- [/] Issue type (red) (defaults to task)
- [/] CMS practice area (blue)

**Comment by oksana-c** [comment]
@cmaeng is this issue still relevant?
