### ISSUE TITLE
Migrate e2e tests to Playwright from Cypress

### ISSUE THREAD

**Issue by jtmst** [department-of-veterans-affairs/va.gov-cms#16172]
## Requirements

We want to migrate our tests from cypress to Playwright based on the prototype here: https://github.com/department-of-veterans-affairs/next-build/tree/15925-playwright-tests, based on the findings from this spike: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15925

We are doing this because we expect Playwright to be more reliable and better-supported than Cypress.

```[tasklist]
### Acceptance criteria
- [x] e2e test coverage suite is migrated to playwright
- [x] Command to run tests is added to package.json
- [x] Full site a11y test is split into its own command
- [x] Cypress tests are removed
- [x] Playwright config is optimized for our enviroments
- [ ] Local test runs work and are clearly documented
```

## Background & implementation details

```[tasklist]
### Implementation tasks
- [ ] Use this if it helps you or feel free to delete.
```

**Comment by tjheffner** [comment]
GHA-related work split out into #16240
