### ISSUE TITLE
[Find Forms] Replace MomentJS with date-fns

### ISSUE THREAD

**Issue by randimays** [department-of-veterans-affairs/va.gov-cms#16185]
## Description
**Application: Find Forms**

According to the [MomentJS Docs](https://momentjs.com/docs/#/-project-status/), MomentJS is a legacy project in maintenance mode. This means no new features or capabilities, no major changes, possibly no bug/quirk fixes, and no bundle size fixes.

MomentJS is a significantly larger JS library than alternatives like `date-fns`. We should migrate to `date-fns` to improve package size for our application. We may see tiny improvements in performance, but the biggest gain here is moving to a package that is actively supported/improved and more likely to have support for new browsers going forward.

### User story

**AS A** PO/PM for Find Forms
**I WANT** a JS library that is not obsolete/in maintenance mode
**SO THAT** the code is in a package that is active supported/improved, will be maintained and fixed if issues arise, and more likely to have support for new browsers going forward.

## Acceptance criteria
- [ ] Move Find Forms from the MomentJS library to `date-fns`
- [ ] Ensure Find Forms functionality/look and feel is not changed

**Comment by FranECross** [comment]
Identified as a possible 'code freeze' time candidate.

**Comment by chriskim2311** [comment]
End of Sprint update: PR has been opened and will close early next sprint

**Comment by chriskim2311** [comment]
Verified on Prod no regression from new functions.
