### ISSUE TITLE
Plan and deliver public websites training for May 5

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#1619]
## Acceptance Criteria
* Testable_Outcome_X
* Testable_Outcome_Y
* Testable_Outcome_Z

## Labels
- [/] Issue type (red) (defaults to task)
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [ ] CMS objective (orange)
- [ ] CMS-supported product (black)

**Comment by howardbrande** [comment]
Recording/artifactof the training https://zoom.us/rec/play/v8cuce_8qm43GNeT5QSDVPZ8W9W1eKmsgChMr6AMnh7kVHcGZFGjZrRDNOW9KQyMMZ4NGu5c5akigKiq?continueMode=true
