### ISSUE TITLE
URL Change for: Dothan 1 VA Clinic

### ISSUE THREAD

**Issue by omahane** [department-of-veterans-affairs/va.gov-cms#16203]
### Implementation date
When does this request need to be live:
ASAP

### Instructions for URL redirect
(Note: This issue will be used from initial request through implementation to ensure all individuals working on this are notified of status updates.  Please do not create multiple issues to track different steps.)
- [x] Notify VA stakeholders as appropriate.
- [x] Link the related facility closure / rename issue.
- [x] Create a URL redirect in the [devops](https://github.com/department-of-veterans-affairs/devops) repo in `ansible/deployment/config/revproxy-vagov/vars/redirects.yml`
- [x] Add the "Awaiting redirect" flag to the facility node with a revision log message that includes a link to this ticket, preserving the node's current moderation state.
- [x] Redirects deploy weekly on Wed. at 10am ET, or by requesting OOB deploy (of the revproxy job to prod) in #vfs-platform-support. After deploy, validate that the URL redirect is deployed. (Note: In the event of a facility closure or a name change,  validate that this occurs before making the Lighthouse csv changes.)
- [x] Update this ticket with a comment that the redirect has been deployed.
- [x] Remove the "Awaiting redirect" flag on the facility node with a revision log message that includes a link to this ticket, preserving the node's current moderation state.
- [x]  Notify helpdesk via comment on ticket or Slack message in #cms-support that changes are ready for review.

#### URL Redirect
| Current URL  |  Redirect Destination or New URL |
| --- | --- |
| https://www.va.gov/central-alabama-health-care/locations/dothan-1-va-clinic  |  https://www.va.gov/central-alabama-health-care/locations/ |

### 2. Canonical URL removal
⚠️ Not necessary. It is not in the CSV ⚠️

**Comment by jilladams** [comment]
@omahane This redirect is now live in prod thanks to an OOB deploy on Devops for PW today. :D
