### ISSUE TITLE
Add another field to Centralized Content for VA Police

### ISSUE THREAD

**Issue by davidmpickett** [department-of-veterans-affairs/va.gov-cms#16219]
## User Story or Problem Statement

[Changes to the VA police page design](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15631) have resulted in new needs for the [VA police Centralized Content](https://prod.cms.va.gov/centralized-content/vamc-system-va-police-page-content)

### Small change to content block 3
- **Title:** What do these terms mean? **(prosecutions & professional standards)**

### New content block to insert between content blocks 3 and 4
- **Title:** What do these terms mean? (use of force)
- **Description:**
- **Paragraph type:** Additional Information (spanish_translation_summary)
- **Draft content** 
  - **Trigger text:**  What do these terms mean?
  - **Text (Rich Text Limited)** 
    - **Use of force** is when a VA police officer uses physical force to get someone to follow their orders.
    - **Weapons discharge** is when someone fires a gun. 

### Also
Add a corresponding entity fetch field to [the content type](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15631)

## Acceptance Criteria
- [x] Content added to centralized content
- [x] field fetch field added to police content type.

**Comment by swirtSJW** [comment]
I added this to the content type.  It has already been merged and should land on prod with Monday's CMS deploy.

**Comment by jilladams** [comment]
https://prod.cms.va.gov/node/63204/edit -- The copy in ticket body _does_ appear after the CC descriptor "What do these terms mean? (use of force)" content block. @davidmpickett I'm closing, but if this is not acting as expected, please reopen.
