### ISSUE TITLE
Redirect Request: Community care Veterans programs

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-cms#16211]
### Instructions
- Requests must be submitted **AT LEAST** 2 weeks in advance.  Some requests take a significant amount of time and coordination to implement, so start the process as soon as you know you will need one. 
- This issue will be used from initial request through implementation to ensure all individuals working on this are notified of status updates.  Please do not create multiple issues to track differnt steps.
- It is your responsibility to notify VA stakeholders as appropriate.  

### Type of request
- [X] We are retiring or taking down a page and need to redirect the URL (complete redirect section)
- [ ] We are changing the URL of an existing page (complete redirect section)
- [ ] We need a custom vanity URL (complete vanity URL section)

### Implementation date
When does this request need to be live?
Choose one:
- [ ] On a specific date, connected to a program or publishing requirement. **DATE:**
- [ ] Any day prior to a deadline/latest possible date. **DEADLINE:** 
- [X] Any day after an earliest possible date. **11.21.23**
- [ ] During a specific date range: ***EARLIEST DATE TO LATEST DATE:***
- [ ] No hard timing requirements, publish when possible.

### Redirects 
Current URL  |  Redirect Destination or New URL
---  |  ---
https://www.va.gov/COMMUNITYCARE/programs/veterans/General_Care.asp, https://www.va.gov/COMMUNITYCARE/programs/veterans/General-Care.asp, and all variations of capping of each segment of URL **AND** any child pages  | https://www.va.gov/resources/eligibility-for-community-care-outside-va/  
https://www.va.gov/COMMUNITYCARE/programs/veterans/CCN-Veterans.asp and all variations of capping of each segment of URL**AND** any child pages  | https://www.va.gov/resources/about-our-va-community-care-network-and-covered-services/
https://www.va.gov/COMMUNITYCARE/programs/veterans/COVID-19_Vaccinations.asp and all variations of capping of each segment of URL  |  https://www.va.gov/health-care/covid-19-vaccine/ 
https://www.va.gov/COMMUNITYCARE/programs/veterans/Urgent_Care.asp, https://www.va.gov/COMMUNITYCARE/programs/veterans/Urgent-Care.asp, and all variations of capping of each segment of URL for both versions  |  https://www.va.gov/resources/getting-urgent-care-at-va-or-in-network-community-providers/
https://www.va.gov/COMMUNITYCARE/programs/veterans/Emergency_Care.asp, https://www.va.gov/COMMUNITYCARE/programs/veterans/Emergency-Care.asp, and all variations of capping of each segment of URL for both versions  |  https://www.va.gov/resources/getting-emergency-care-at-non-va-facilities/
https://www.va.gov/COMMUNITYCARE/programs/veterans/Home-Hospice-care.asp and all variations of capping of each segment of URL |  https://www.va.gov/health-care/about-va-health-benefits/long-term-care/ 
https://www.va.gov/COMMUNITYCARE/programs/veterans/ihs/index.asp and all variations of capping of each segment of URL |  https://www.va.gov/resources/does-va-cover-indian-health-service-or-tribal-health-programs-care/
https://www.va.gov/COMMUNITYCARE/programs/veterans/IVF.asp and all variations of capping of each segment of URL  |  https://www.womenshealth.va.gov/WOMENSHEALTH/topics/infertility-and-ivf.asp

### Vanity URLs 
Vanity URL  |  Landing page
---  |  ---
requested URL | landing page URL

**Link to campaign landing page request issue:**

### Process, Roles and Responsibilities
- [X] Requesting team: Above information is provided
- [X] Requesting team: All appropriate VA stakeholders are notified as appropriate
- [x] IA: Request is vetted and documented and implementation plan is clear 
- [ ] IA: Request is assigned to appropriate team for implementation 
- [ ] Implementation team: Work is complete
- [ ] Implementation team: Validated in production
- [ ] Requesting team: Validates everything is correct in production and closes ticket

**Comment by kristinoletmuskat** [comment]
Ooo yes thanks for asking @jilladams . Because the ticket isn't in our repo anymore I can't update the table, but the following seem to have child pages (unless anchor links in URLs aren't child pages? I'm not sure).

1. https://www.va.gov/COMMUNITYCARE/programs/veterans/CCN-Veterans.asp
2. https://www.va.gov/COMMUNITYCARE/programs/veterans/General-Care.asp

**Comment by DanielleThierryUSDSVA** [comment]
Ugh, thanks, @kristinoletmuskat! This is what I get for trying to put this table together so quickly...definitely shows why the validation step is needed :)

The first row in the table is correct. Mikki and I had discussed other options, but landed on that one. I updated in the table. Thanks!

**Comment by jilladams** [comment]
Thanks! This is in our current sprint, so we'll update you when it's queued to deploy.

**Comment by jilladams** [comment]
@DanielleThierryUSDSVA are these redirects no longer needed? (We have this ticket in sprint, it's not complete, and you closed it today, but not sure if that was intentional.)

**Comment by DanielleThierryUSDSVA** [comment]
Hey, @jilladams! Thanks for checking. The CAIA team had asked me to close this during our planning call today so I'm going to throw the question over to them: @strelichl @TerryNichols2vagov @kristinoletmuskat thanks!

**Comment by kristinoletmuskat** [comment]
@jilladams please implement these! That was our mistake.

**Comment by jilladams** [comment]
Ok thanks! Reopening.
