### ISSUE TITLE
[PAW] Implement all new content according to Danielle's latest updates (11/27/23)

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-cms#16218]
## Description

Update Cindy's SM results screens

### User story

**AS AN** OCTO crew lead
**I WANT** to be able to provide the PAW survey monkey to stakeholders 
**SO THAT** I can get buy-off on content and provide an example of the PACT Act Wizard

## Acceptance criteria
- [ ] The SM results screens are updated with Danielle's latest content

  * Danielle's document [sharepoint ](https://dvagov-my.sharepoint.com/:w:/g/personal/danielle_thierry_va_gov/EexjTD76bnVOl8snKt6nK5gBzGoQbo5zugMpjwOBDw7Tjg?e=9NV82P)document

**Comment by jilladams** [comment]
Talked to @cindymerrill today in 1:1 and I think these notes clarify what we need from @randimays . FYI @FranECross in case I missed anything, also.

**Needs that are driving these changes:** 
1. We need to provide a preview of the wizard to Danielle, to share with stakeholders, until Staging acts like the real thing.
2. We want Staging to act like the real thing, both for Demo video recording, maybe for Stakeholder preview (up to Danielle), and to get ready for launch.

**Changes that need to be made:**
1. Fix content changes in the 2 existing Results pages, that are linked to from Survey Monkey. This serves purpose # 1 above.
2. Update the content for all the other pages. 
   * After this, we could record the demo. (The demo doesn't require dynamic results screens.) 
4. Update Results screens to make them dynamic based on the question responses.
   * **Note**: when we do this to the existing results screens, this will mean Survey Monkey will point to a results screen that no longer has pre-populated static content, so will be blank / won't have survey data input to generate results. This will allow us, though, to walk away from Survey Monkey.

**Comment by jilladams** [comment]
Also: @FranECross and @randimays FYI: I went ahead and pulled this into sprint. It's the next logical priority, and trumps most everything else FE in the sprint IMO, but Fran lemme know if that's stomping on anything.

**Comment by jilladams** [comment]
Related slack convo: https://dsva.slack.com/archives/C52CL1PKQ/p1701191725741529

**Comment by FranECross** [comment]
@jilladams Totally agree with pulling it into the sprint. I just asked a question in Slack but will here, too... Does it make sense for me to split into three tickets to match what you outlined in 1, 2, 3 in your comment above?

**Comment by randimays** [comment]
Cindy and I validated the SurveyMonkey results screens in staging. Slack thread: https://dsva.slack.com/archives/C52CL1PKQ/p1701362178027049

This is good to close!
