### ISSUE TITLE
[PACT Act] Update the PACT Act Wizard prototype with Danielle's content revisions

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-cms#16216]
### User story
> _Describe the audience/user, enhancement or fix, and value / outcome desired._

**AS A** Stakeholder
**I WANT** to go through the survey monkey prototype and see updated content
**SO THAT** I understand what will be implemented

## Acceptance criteria
- [x] Content changes have been made to Survey Monkey
- [x] Review the changes that Randi makes to the two R1 results pages to ensure they are correct/updated

**Comment by cindymerrill** [comment]
I created a new copy of the PAW prototype from usability testing and made Danielle's revisions in it. The new survey URL is **https://www.surveymonkey.com/r/G7QBTQ2** . Now I'm waiting for @randimays 's revisions to the two R1 results screens on Staging, which don't appear to be working right now, assuming that https://staging.va.gov/pact-act-wizard-test/results-1-1 is the correct URL.

**Comment by randimays** [comment]
@cindymerrill We updated the URL for PAW before your readout. The results screens are at https://staging.va.gov/pact-act-eligibility/results-1-1.

**Comment by cindymerrill** [comment]
Thank you, @randimays ! I had updated it in my PAW prototype, but when I made a new copy of that survey yesterday for revisions, that URL wasn't copied over. When I added it yesterday, I apparently added the old URL, which I found in my browser bookmarks and apparently forgot to update.

**Comment by cindymerrill** [comment]
Reviewed @randimays 's revisions to the R1 results pages and tested on Staging from Survey Monkey. Everything checked out, so I'm closing this ticket.
