### ISSUE TITLE
Update top level Readme and linked documentation

### ISSUE THREAD

**Issue by JunTaoLuo** [department-of-veterans-affairs/va.gov-cms#16228]
## User Story or Problem Statement

As a collaborator on the CMS team, I would like the Readme's and related documentation to be up to date so I can efficiently learn how to work on the repository.

## Description or Additional Context 

As part of my onboarding I noticed a few broken/missing links and some documentation that need updates.

## Steps for Implementation

There are three main types of content updates I've identified: broken/missing links, unlinked/orphaned content and documentation that should be added or updated. See ACs for details.

### Broken or missing links
These are links in our documentation that are missing documentation or pointing to outdated links. The action items here are to create new documentation, link to updated content or remove the original link.

Top level [Readme](https://github.com/department-of-veterans-affairs/va.gov-cms/blob/efc87a8b61a98e5e5b9824a8da0c4743ef795a3d/README.md)
- [ ] 3.vi - should this be pointing to comparing-graphql-output.md?
- [ ] 4.iii - new documentation need to be added
- [ ] 5.i - missing architecture overview
- [ ] 5.ii - missing drupal overview, otherwise we should consolidate it and its subsection to Drupal - Memcache
- [ ] 5.iv - missing MetalSmith documentation
- [ ] 5.ix - broken link to downstream dependencies

QA [Readme](https://github.com/department-of-veterans-affairs/va.gov-cms/blob/1bcc9937a697280a9669ee1ff84a41ede0abde80/READMES/qa.md)
- [ ] Broken Conflence from outdated va-gov domain

Security [Readme](https://github.com/department-of-veterans-affairs/va.gov-cms/blob/efc87a8b61a98e5e5b9824a8da0c4743ef795a3d/READMES/security.md) 
- [ ] Fortify Security Scans was removed in https://github.com/department-of-veterans-affairs/va.gov-cms/commit/e9aca3cfa3824481311f7bcd3dc64abca04b590f
- [ ] Security policy has been moved to https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/SECURITY.md

### Unlinked or orphaned content
The action items are to decide if these content should be linked in the top level Readme's TOC. Some content may be outdated and should be moved to READMES/historical.

- [ ] analytics.md - move to historical
- [ ] blackfire.md
- [ ] codeowners.md
- [ ] comparing-graphql-output.md
- [ ] dependabot-alerts.md
- [ ] distribution-group-mgmt.md
- [ ] jsonapi.md
- [ ] multilingual.md - move to teams/platform/cms (https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/cms/product-outlines)
- [ ] remove-deprecated-fields.md
- [ ] scalability-testing.md
- [ ] sentry.md
- [ ] translation.md - move teams/platform/cms (https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/cms/product-outlines)
- [ ] user_management.md

### Documentation update
The action items here are to update our documentation to reflect our current workflow and recommendations.

- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/READMES/https.md Update OSX instructions for new macOS UI
- [ ] Use branches instead of forks in our getting started recommendations
- [ ] Update getting started steps to include:
  - create .env from .env.example
  - ddev pull va --skip-files requirement for running locally
- [ ] How to find link to cypress logs from CI Tugboat images
- [ ] Insert link to the docs at https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/cms

## Team
Please check the team(s) that will do this work.

- [x] CMS Team
- [ ] Public Websites
- [ ] Facilities
- [ ] Accelerated Publishing

**Comment by EWashb** [comment]
@JunTaoLuo here is the other space I was referring to: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/cms

Did you know about it?

**Comment by JunTaoLuo** [comment]
Ah I recall seeing a few of the documents in that repo that were linked in the onboarding issue but I haven't systematically gone through each like I've done for the documents in this repo. From a quick scan, it seems like most of the content is distinct from those in this repo (e.g. UX, product, etc) so simply migrating the docs should be easy. I'm sure once we dig a little deeper, there will be duplicate documentation that needs to be consolidated (e.g. github practices).

**Comment by EWashb** [comment]
@JunTaoLuo thats a fair solution. At the very least migrating one to the other can help streamline! Thanks for looking into this.

**Comment by JunTaoLuo** [comment]
Took another look and it seems the content at va.gov-team looks like it's more focused on product, design and research whereas the documentation in va.gov-cms is more engineering focused. I think we can actually move all the documents wholesale into this repo and we only need to consolidate the top level Readme.

**Comment by JunTaoLuo** [comment]
Hey @EWashb I took a closer look at the set of documentation in this repo vs at [va.gov-team](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/cms) and it does appear most of the docs in this repo are dev/devops/qa oriented whereas the ones in va.gov-team are more product/design/support/research/cross-team. I think this division makes sense so we shouldn't consolidate the docs to one repo and move the cheese for a lot of people. 

That being said, I feel there are two documents that feel out of place in this repo: https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/READMES/multilingual.md and https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/READMES/translation.md. Can you help me figure out where these should go (va.gov-team, KB, somewhere else)?

Also, from our previous meeting, we decided to make sure we link between the two sets of documentation in the top level readmes. Luckily the top level readme at va.gov-team already links to this repo and I've added an AC to this issue to ensure we link to the docs at va.gov-team.

Finally, let me know if there is anything else you'd like to reorganize in terms of documentation.

**Comment by EWashb** [comment]
This is amazing work, @JunTaoLuo! Thank you for doing this. 

For the translation and multilingual, I think the best place for now might just be a space in the [Product Outlines](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/cms/product-outlines). That work is basically in beta right now with an internal partner- CAIA. There is still a lot of work to do there, but eventually we should definitely look at having some of this live in KB. For now, moving to product outline would be a smart choice. 

Additionally, I agree with you- as long as we are cross linking and updating the readmes/descriptions of our spaces I think that is appropriate to keep the devs docs and other work separated. 

I have no other questions or comments. I'm excited to see this happen!
