### ISSUE TITLE
Missing password reset on prod

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#1623]
**Describe the defect**
When logging in on prod I should have the option to reset my password.
it is present on dev and staging but not prod.
![image](https://user-images.githubusercontent.com/5752113/80248633-575c9100-863e-11ea-8f70-dc36160c6365.png)

**To Reproduce**
1. Go to https://prod.cms.va.gov/
2. See that "reset your password" is not there.

**Expected behavior**
I should be able to reset my password on prod.

**Screenshots**

**Desktop (please complete the following information if relevant, or delete):**

**Additional context**

## Labels
- [/] Issue type (red) (defaults to "Defect")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [/] CMS objective (orange) (not needed for bug tickets)
- [ ] CMS-supported product (black)

**Comment by swirtSJW** [comment]
@howardbrande Just tagging you on this for your visibility.

**Comment by oksana-c** [comment]
this appears to be fixed.
<img width="786" alt="Screen Shot 2020-12-14 at 4 58 19 PM" src="https://user-images.githubusercontent.com/16477724/102150348-98075580-3e2d-11eb-88d8-0ac85dce2468.png">
