### ISSUE TITLE
Section taxonomy does not have the multi-workflow filter

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#16231]
## User Story or Problem Statement
When visiting a section "dashboard" that View has the single workflow filter instead of the multiworkflow filter.
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5752113/e1b6169d-fc4e-4686-9f52-f4f684adbe70)

Example: https://prod.cms.va.gov/section/nca

## Acceptance Criteria
- [ ] The section dashboard view should have the multiworkflow filter on it.

## Team
Please check the team(s) that will do this work.

- [ ] CMS Team
- [ ] Public Websites
- [x] Facilities
- [ ] Accelerated Publishing

**Comment by omahane** [comment]
This can be closed.

**Comment by xiongjaneg** [comment]
@omahane I'm not seeing this in prod. Am I looking in the wrong place?
<img width="1053" alt="Screenshot 2023-12-14 at 1 45 40 PM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/73648238/fe69a1d0-27da-4187-a36c-baadd4e51775">

**Comment by omahane** [comment]
@xiongjaneg This has been fixed in the PR above  (https://github.com/department-of-veterans-affairs/va.gov-cms/pull/16352), which is why I said it can be closed. Let me know if I can clarify this further.
