### ISSUE TITLE
BE: Create new Drupal image derivative for 500x500 images for CLPs

### ISSUE THREAD

**Issue by randimays** [department-of-veterans-affairs/va.gov-cms#16242]
### Engineering notes / background
Create a new Drupal image derivative that generates a square derivative at a particular size: 500 x 500.

Naming can be generic, but will be first used on Campaign landing pages.

Slack convo: https://dsva.slack.com/archives/C52CL1PKQ/p1701277638108409?thread_ts=1701273420.734929&cid=C52CL1PKQ
* Using `crop_square`, we don't get an enforced minimum size and have to upscale the image in order to make it larger than text
* Modifying `crop_square` will affect other usage in places like the homepage News promo
* We're proposing Drupal do the image scaling, to prevent delivering giant images to the FE that are scaled byt he browser, as a bandwidth concern.

## Acceptance criteria

- [ ] New image derivative provides 500x500 pixel images

**Comment by jilladams** [comment]
From discussion in FE refinement: 
* Drupal will upscale images that are smaller than min height, by default.
* We _think_ Drupal could enforce a min size, but need to research / confirm.
* We don't have to add Editorial constraint now.

**Comment by FranECross** [comment]
Check with CMS Team; probably doesn't need an actual collab cycle. @FranECross

**Comment by jilladams** [comment]
Went ahead and ticketed the FE ticket: #16361

**Comment by dsasser** [comment]
@randimays @jilladams the new derivative has a machine name of: `1_1_square_large`

**Comment by jilladams** [comment]
This should be live in Prod, but not sure how to verify it which brought to mind 1 question:  will this show as an optional crop, e.g. here? 
![Screenshot 2023-12-18 at 3 55 52 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/85581471/b39c804c-0722-44ec-88dc-4d6abbf978d7)

Or: it will just generate a 500x500 crop? I realized I'm unclear on how this will work from an Editor perspective. @dsasser this may be easiest to resolve via discussion. Adding to scrum agenda for tomorrow.

**Comment by dsasser** [comment]
> This should be live in Prod, but not sure how to verify it which brought to mind 1 question: will this show as an optional crop [...]
> 
> Or: it will just generate a 500x500 crop? I realized I'm unclear on how this will work from an Editor perspective. @dsasser this may be easiest to resolve via discussion. Adding to scrum agenda for tomorrow.

As discussed in scrum: doesn’t show up as a new crop option, but is based on Square / 1:1. So: an editor can set the 1:1 crop, and then image derivative will scale it down to 500x500. Won’t upscale.

1_1_square_large = new replacement for crop_square
