### ISSUE TITLE
Users should not get logged out while in maintenance mode.

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#1625]
**Describe the defect**
A user is logged in during deploy,  When the site goes in to maintenance mode, any requests for drupal makes them get logged out... unless they are allowed to be logged in during maintenance mode.

https://www.drupal.org/project/drupal/issues/3057267

## AC
1. Evaluate the security risk  (discuss with team)
2.  Apply patch.

## Labels
- [/] Issue type (red) (defaults to "Defect")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [/] CMS objective (orange) (not needed for bug tickets)
- [ ] CMS-supported product (black)

**Comment by indytechcook** [comment]
If we did not want to apply the patch, we could decorate the service instead.
