### ISSUE TITLE
Front End: Implement VBA Regional Office meta tag (SEO)

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#16254]
## Description or Additional Context 
In #14000, a meta tag was implemented for SEO for VBA Regional Office pages. This is a placeholder the subsequent front end work.

## Acceptance Criteria
- [x] `<meta name="description">` shows on the front-end of a VBA facility
- [x] `<meta name="og:description">` shows on the front-end of a VBA facility

**Comment by xiongjaneg** [comment]
This could be automatically done with the liquid template. The question is, are these coming through in the same tag that we're expecting from other pages. If yes, it should be automatic. If not, some modification may be needed to the template.

**Comment by eselkin** [comment]
Seems like it's coming through on here:
https://web-ihqrv6rby5lxlkn8zqdxf9u7lk1aplcp.demo.cms.va.gov/cleveland-va-regional-benefit-office/locations/cleveland-va-regional-benefit-office/
![Screenshot 2024-01-09 at 1 43 49 PM-01](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5606931/44f7b777-18aa-4887-b88d-fa5e569f4618)
