### ISSUE TITLE
D10 config needs export to cleanup stray changes

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#16265]
## Describe the defect
Following the D10 deploy there are a bunch of config files that all get updated that should be updated separate from actual product work.  These are slowing product work down a bit because it creates a fair amount of file changes that are unexpected and takes a while to find the files that are expected to change.

modified:   config/sync/core.entity_form_display.node.campaign_landing_page.default.yml
        modified:   config/sync/core.entity_form_display.node.health_care_local_facility.default.yml
        modified:   config/sync/core.entity_form_display.node.health_care_region_page.default.yml
        modified:   config/sync/core.entity_form_display.node.landing_page.default.yml
        modified:   config/sync/core.entity_form_display.node.office.default.yml
        modified:   config/sync/core.entity_form_display.node.vamc_system_billing_insurance.default.yml
        modified:   config/sync/core.entity_form_display.node.vba_facility.default.yml
        modified:   config/sync/core.entity_form_display.node.vet_center.default.yml
        modified:   config/sync/core.entity_form_display.node.vet_center_cap.default.yml
        modified:   config/sync/core.entity_view_display.media.document.default.yml
        modified:   config/sync/core.entity_view_display.node.checklist.default.yml
        modified:   config/sync/core.entity_view_display.node.documentation_page.default.yml
        modified:   config/sync/core.entity_view_display.node.health_care_region_page.default.yml
        modified:   config/sync/core.entity_view_display.node.health_care_region_page.external_content.yml
        modified:   config/sync/core.entity_view_display.node.service_region.full.yml
        modified:   config/sync/core.entity_view_display.node.vba_facility.default.yml
        modified:   config/sync/core.entity_view_display.node.vet_center.default.yml
        modified:   config/sync/core.entity_view_display.paragraph.q_a_group.default.yml
        modified:   config/sync/core.entity_view_display.paragraph.q_a_group.user_guides.yml
        modified:   config/sync/core.entity_view_display.user_history.user_history.default.yml
        modified:   config/sync/core.entity_view_display.user_history.user_history.tab.yml
        modified:   config/sync/field.field.block_content.benefit_promo.field_promo_headline.yml
        modified:   config/sync/field.field.block_content.news_promo.field_promo_headline.yml
        modified:   config/sync/field.field.menu_link_content.home-page-hub-list.field_icon.yml
        modified:   config/sync/field.field.node.basic_landing_page.field_intro_text_limited_html.yml
        modified:   config/sync/field.field.node.basic_landing_page.field_table_of_contents_boolean.yml
        modified:   config/sync/field.field.node.campaign_landing_page.field_clp_stories_header.yml
        modified:   config/sync/field.field.node.campaign_landing_page.field_clp_stories_teasers.yml
        modified:   config/sync/field.field.node.campaign_landing_page.field_clp_what_you_can_do_header.yml
        modified:   config/sync/field.field.node.checklist.field_table_of_contents_boolean.yml
        modified:   config/sync/field.field.node.event.field_media.yml
        modified:   config/sync/field.field.node.faq_multiple_q_a.field_intro_text_limited_html.yml
        modified:   config/sync/field.field.node.faq_multiple_q_a.field_table_of_contents_boolean.yml
        modified:   config/sync/field.field.node.full_width_banner_alert.field_situation_updates.yml
        modified:   config/sync/field.field.node.health_care_local_health_service.field_phone_numbers_paragraph.yml
        modified:   config/sync/field.field.node.health_care_region_detail_page.field_table_of_contents_boolean.yml
        modified:   config/sync/field.field.node.landing_page.field_title_icon.yml
        modified:   config/sync/field.field.node.media_list_images.field_table_of_contents_boolean.yml
        modified:   config/sync/field.field.node.media_list_videos.field_table_of_contents_boolean.yml
        modified:   config/sync/field.field.node.nca_facility.field_operating_status_more_info.yml
        modified:   config/sync/field.field.node.news_story.field_full_story.yml
        modified:   config/sync/field.field.node.page.field_plainlanguage_date.yml
        modified:   config/sync/field.field.node.page.field_table_of_contents_boolean.yml
        modified:   config/sync/field.field.node.person_profile.field_body.yml
        modified:   config/sync/field.field.node.press_release.field_release_date.yml
        modified:   config/sync/field.field.node.step_by_step.field_intro_text_limited_html.yml
        modified:   config/sync/field.field.node.step_by_step.field_table_of_contents_boolean.yml
        modified:   config/sync/field.field.node.support_resources_detail_page.field_intro_text_limited_html.yml
        modified:   config/sync/field.field.node.va_form.field_va_form_type.yml
        modified:   config/sync/field.field.node.vba_facility.field_cc_cant_find_benefits.yml
        modified:   config/sync/field.field.node.vba_facility.field_operating_status_more_info.yml
        modified:   config/sync/field.field.node.vet_center.field_operating_status_more_info.yml
        modified:   config/sync/field.field.node.vet_center_cap.field_operating_status_more_info.yml
        modified:   config/sync/field.field.paragraph.react_widget.field_default_link.yml
        modified:   config/sync/field.field.paragraph.service_location.field_hours.yml
        modified:   config/sync/field.field.paragraph.service_location_address.field_use_facility_address.yml
        modified:   config/sync/field.field.user.user.message_subscribe_email.yml
        modified:   config/sync/field.storage.node.field_dismissible_option.yml
        modified:   config/sync/field.storage.paragraph.field_hours.yml
        modified:   config/sync/flag.flag.email_node.yml
        modified:   config/sync/flag.flag.email_term.yml
        modified:   config/sync/flag.flag.email_user.yml
        modified:   config/sync/language/es/views.view.content_model_documents.yml
        modified:   config/sync/migrate_plus.migration.facility_health_care_service.yml
        modified:   config/sync/migrate_plus.migration.facility_health_care_service_2.yml
        modified:   config/sync/migrate_plus.migration.facility_health_care_service_covid.yml
        modified:   config/sync/migrate_plus.migration.facility_health_care_service_final_6visns.yml
        modified:   config/sync/migrate_plus.migration.facility_health_care_service_visn_10_17_20.yml
        modified:   config/sync/migrate_plus.migration.facility_health_care_service_visn_7_8.yml
        modified:   config/sync/migrate_plus.migration.health_care_region_page.yml
        modified:   config/sync/migrate_plus.migration.regional_health_care_service.yml
        modified:   config/sync/migrate_plus.migration.regional_health_care_service_covid.yml
        modified:   config/sync/migrate_plus.migration.regional_health_care_service_region_keyed.yml
        modified:   config/sync/migrate_plus.migration.regional_health_care_service_region_keyed_2.yml
        modified:   config/sync/migrate_plus.migration.regional_health_care_service_region_keyed_3.yml
        modified:   config/sync/migrate_plus.migration_group.va_gov.yml
        modified:   config/sync/node.type.campaign_landing_page.yml
        modified:   config/sync/node.type.health_care_region_detail_page.yml
        modified:   config/sync/node.type.news_story.yml
        modified:   config/sync/node.type.regional_health_care_service_des.yml
        modified:   config/sync/node.type.vamc_operating_status_and_alerts.yml
        modified:   config/sync/node_link_report.settings.yml
        modified:   config/sync/system.action.flag_action.email_node_unflag.yml
        modified:   config/sync/system.action.flag_action.email_term_unflag.yml
        modified:   config/sync/system.action.flag_action.email_user_unflag.yml
        modified:   config/sync/system.menu.documentation.yml
        modified:   config/sync/system.menu.header-megamenu.yml
        modified:   config/sync/system.site.yml
        modified:   config/sync/user.role.content_editor.yml
        modified:   config/sync/user.role.content_reviewer.yml
        modified:   config/sync/views.view.centralized_content_paragraphs.yml
        modified:   config/sync/views.view.content.yml
        modified:   config/sync/views.view.content_model_documents.yml
        modified:   config/sync/views.view.facility_services.yml
        modified:   config/sync/views.view.feedback.yml
        modified:   config/sync/views.view.files.yml
        modified:   config/sync/views.view.flagged_content.yml
        modified:   config/sync/views.view.flagged_content_va_forms.yml
        modified:   config/sync/views.view.glossary.yml
        modified:   config/sync/views.view.image_style_warmer_warmup_files.yml
        modified:   config/sync/views.view.media.yml
        modified:   config/sync/views.view.media_library.yml
        modified:   config/sync/views.view.metatag_audit.yml
        modified:   config/sync/views.view.moderated_content.yml
        modified:   config/sync/views.view.moderation_history.yml
        modified:   config/sync/views.view.non_clinical_services.yml
        modified:   config/sync/views.view.orphaned_paragraphs.yml
        modified:   config/sync/views.view.pdf_audit.yml
        modified:   config/sync/views.view.rich_text_field_audit.yml
        modified:   config/sync/views.view.right_sidebar_latest_revision.yml
        modified:   config/sync/views.view.section_export.yml
        modified:   config/sync/views.view.taxonomy_entity_browsers.yml
        modified:   config/sync/views.view.taxonomy_term.yml
        modified:   config/sync/views.view.tmgmt_job_items.yml
        modified:   config/sync/views.view.tmgmt_translation_all_job_items.yml
        modified:   config/sync/views.view.user_admin_people.yml
        modified:   config/sync/views.view.user_history.yml
        modified:   config/sync/views.view.user_history_list.yml
        modified:   config/sync/views.view.users_in_section.yml
        modified:   config/sync/views.view.va_forms.yml
        modified:   config/sync/views.view.vamc_alerts_and_operating_statuses.yml
        modified:   config/sync/views.view.vamc_top_task_page_revisions.yml
        modified:   config/sync/views.view.who_s_new.yml
        modified:   config/sync/views.view.who_s_online.yml
        modified:   config/sync/workbench_access.access_scheme.section.yml

## To Reproduce
1. ddev drush cex
2. see all the ~125 files that get modified

## AC / Expected behavior
- [ ] ddev drush cex cause no files to be altered.
- [ ] checks are made to make sure there are no changes to functionality as a result of the updates if they are not trivial changes like quotes, commas and sorting.
- [ ] Drupal update documentation is added to ensure the final step before launch is to do a config export.

## Additional context
Add any other context about the problem here. Reach out to the Product Managers to determine if it should be escalated as critical (prevents users from accomplishing their work with no known workaround and needs to be addressed within 2 business days).

### Team
Please check the team(s) that will do this work.

- [x] `CMS Team`
- [ ] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`
- [ ] `Accelerated Publishing`

**Comment by maortiz-27-80** [comment]
thanks, @ndouglas !  i've added "Post D10 Upgrade" label and have added this to the Sprint 99 Epic 15480. cc: @BerniXiongA6

**Comment by swirtSJW** [comment]
Sorry, I added an _suggested_ AC of adding a step to our upgrade documentation to remind our future selves that config export should be run as the last step before releasing the upgrade.

**Comment by swirtSJW** [comment]
[Related slack thread](https://dsva.slack.com/archives/CT4GZBM8F/p1701897652143529).

**Comment by ndouglas** [comment]
That's a good suggestion, @swirtSJW. We should add that to our upgrade playbook. I'll add a note to the relevant ticket for that.
