### ISSUE TITLE
[ADD] VBA services (batch 2) to Service Taxonomy

### ISSUE THREAD

**Issue by davidmpickett** [department-of-veterans-affairs/va.gov-cms#16269]
### Which Taxonomy is this term for?

VA services taxonomy

### Proposed terms

Label | Machine Name | Health Service API ID 
-- | -- | -- 
[Careers and employment](https://prod.cms.va.gov/health-care/careers-and-employment) | careers-and-employment | EducationAndCareerCounseling
Compensation benefits for survivors | compensation-benefits-for-survivors | FamilyMemberClaimAssistance*
Creating an account for VA.gov </br> ~~Veteran profile information~~  | creating-account-for-vagov | eBenefitsRegistrationAssistance  
[Direct deposit information](https://prod.cms.va.gov/health-care/direct-deposit-information) | direct-deposit-information | UpdatingDirectDepositInformation 
Fiduciary services </br> ~~Financial services~~ | fiduciary-services | FiduciaryServices 
[Military sexual trauma-related claims](https://prod.cms.va.gov/health-care/military-sexual-trauma-claims) | military-sexual-trauma-claims | MilitarySexualTraumaClaims
[Pre-discharge claims](https://prod.cms.va.gov/health-care/pre-discharge-claims)  | pre-discharge-claims | PreDischargeClaimAssistance 
Pre-need burial planning </br> ~~Burial in a VA cemetery~~ | pre-need-burial-planning | PreNeedBurialPlanning 
Transition assistance  | transition-assistance | TransitionAssistance 
[VetSuccess on Campus](https://prod.cms.va.gov/health-care/vetsuccess-on-campus)  | vet-success-on-campus | VetSuccessOnCampus

*Suggesting this as best fit for mapping the legacy Facilities API ID, even though it isn't perfect

### Rejected terms
| Proposed name | Decision | Comments | 
| --- | --- | ---|
| Caregiver support |  Do not add  | This is not a service which should be advertised as a VBA service.  If necessary, ROs refer to the VHA Caregivers program 
| Integrated Disability Evaluation System | Do not add | Feedback indicates that this is a DOD program supported by the VA, not a VA program. The military initiates the IDES process, not the service member. VBA role in this will be represented by the Pre-discharge claim service term 

### Does this overlap with any existing term in the taxonomy?

No

### Rationale for adding this term

Follow up from batch 1

### Which products will this term impact?

VBA Regional Office

### Have stakeholders from impacted products been consulted?

Yes

### Have you drafted content for all the relevant subfields?

- Original source of truth for all VBA services content [VBA Services](https://dvagov.sharepoint.com/:x:/s/VBAVA.govmodernization/ET964xEqUFREirhtu34HQVIBbsNOu12QIUc-EVNF_aW98g)
- Will need to draft subfields for Direct deposit information

### End of sprint 101 update - 2 points
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16269#issuecomment-1894898969 proposed labels, machine names, and API IDs for 10 terms
- Updated source of truth spreadsheet

### Sprint 102 - 3 points
- [x] Terms labels that need additional review and approval are sent to relevant taxonomy governance body
   - [Message to CAIA is drafted](https://github.com/department-of-veterans-affairs/va.gov-team/issues/74390).
- [x] If approved, a Drupal admin from Product team may add the term to the taxonomy
- [x] Content for subfields is drafted in Drupal by Product team
  - [x] [Careers and employment](https://prod.cms.va.gov/health-care/careers-and-employment)
  - [x] [Direct deposit information](https://prod.cms.va.gov/health-care/direct-deposit-information) 
  - [x] [Military sexual trauma-related claims](https://prod.cms.va.gov/health-care/military-sexual-trauma-claims)
  - [x] [Pre-discharge claims](https://prod.cms.va.gov/health-care/pre-discharge-claims)  
  - [x] [VetSuccess on Campus](https://prod.cms.va.gov/health-care/vetsuccess-on-campus) 
- [x] Links to Drupal Terms with drafted subfields is shared for further feedback/approvals
  - **For VBA review**
  - [Careers and employment](https://prod.cms.va.gov/health-care/careers-and-employment)
  - [Direct deposit information](https://prod.cms.va.gov/health-care/direct-deposit-information) 
  - [Military sexual trauma-related claims](https://prod.cms.va.gov/health-care/military-sexual-trauma-claims)
  - [Pre-discharge claims](https://prod.cms.va.gov/health-care/pre-discharge-claims)  
  - [VetSuccess on Campus](https://prod.cms.va.gov/health-care/vetsuccess-on-campus)

**Comment by mmiddaugh** [comment]
**Capturing VBA and Taxonomy Council input to date** 

| Proposed name | Decision | Comments | 
| --- | --- | ---|
| Burial in a VA cemetery	| See comment | Flagged as core VBA service but name may need wordsmithing or emphasis on "planning" to distinguish from Burials and Memorials | 
| Compensation benefits for survivors | Add | Thank you for incorporating the proposed name change | 
| Careers and employment | Add | Flagged as core VBA service | 
| Caregiver support |  Do not add  | This is not a service which should be advertised as a VBA service.  If necessary, ROs refer to the VHA Caregivers program 
| Direct deposit information | Add - see comment | Should this be named "Direct deposit assistance"? Flagged as a core VBA service | 
| Financial services | Add - see comment | Proposed name change to "Fiduciary services" | 
| Grief and bereavement counseling | Do not add - see comment |  This does not need to be added. It is already a listed service
| Integrated Disability Evaluation System | Do not add | Feedback indicates that this is a DOD program supported by the VA, not a VA program. The military initiates the IDES process, not the service member. VBA role in this will be represented by the Pre-discharge claim service term 
| Medical records | pending additional discussion | |
| Pre-discharge claims | pending additional discussion | |
| Returning service member care | pending additional discussion | |
| Transition help | pending additional discussion | |
| Veteran profile information | Add - see comment | This was flagged as a core VBA service but the name needs wordsmithing. Suggested: "Online account registration" or incorporation of "VA.gov" "VA.gov account assistance"?  |
| VetSuccess on Campus | Add | Flagged as a core service |

**Comment by davidmpickett** [comment]
Moved Medical records to https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16463 because it is an update of existing term not an addition

**Comment by davidmpickett** [comment]
@mmiddaugh @aklausmeier @xiongjaneg Potential ticket for me to take on in sprint 100 /101 depending on priority. I separated out the list in the main description to focus on the 8 terms that seem to have consensus (though I will need to wordsmith some of them.) 

Shifted a couple terms to other tickets based on feedback here and in Sharepoint doc.

**Comment by davidmpickett** [comment]
> Name | Decision | Comments
> -- | -- | --
> Grief and bereavement counseling | Do not add - see comment |  This does not need to be added. It is already a listed service

@mmiddaugh Want to clarify this comment. Is this saying that Grief and bereavement should not be listed as a VBA service, or simply pointing out that it would be an UPDATE to an existing term rather than a net addition?

**Comment by mmiddaugh** [comment]
@davidmpickett [good question about Grief and bereavement](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16269#issuecomment-1858606079) - apologies for not being more clear. 

- Grief and bereavement counseling was identified as a core service by some Regional offices.  
- This issue adds Label, Machine Name, and Health Service API ID for VBA services. 
- Since Grief and bereavement counseling is already present in the VA service taxonomy, I don't think anything is needed in this round.

**Comment by davidmpickett** [comment]
@mmiddaugh Awesome, thanks for clarification. I'm splitting that off into a separate issue: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16503

I also just created a new issue template to GitHub to handle this type of Taxonomy work. Also covers [Medical Records](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16463)

**Comment by davidmpickett** [comment]
**Health Service API ID list**

- ApplyingForBenefits
- BurialClaimAssistance = Burials and memorials
- DisabilityClaimAssistance = Disability compensation
- eBenefitsRegistrationAssistance
- EducationAndCareerCounseling
- EducationClaimAssistance = Education benefits for Veterans
- FamilyMemberClaimAssistance
- HomelessAssistance
- InsuranceClaimAssistanceAndFinancialCounseling = Life Insurance
- IntegratedDisabilityEvaluationSystemAssistance
- Pensions = Veterans Pension
- PreDiscargeClaimAssistance
- TransitionAssistance
- UpdatingDirectDepositInformation
- VAHomeLoanAssistance = Home loans
- VocationalRehabilitationAndEmploymentAssistance

**Comment by mmiddaugh** [comment]
@davidmpickett based on most recent RO conversations, here's the revised descriptions for the pending service taxons. I think they're ready to be added and reviewed by CAIA.

## Disability Compensation, Pre-discharge claims, and Appeals
>- The Regional office cannot help with filing pre-discharge claims (they are initiated before separation) or certain tasks for pre-discharge claims (IDES and BDD need to handled by a MSC or PEBLO)
>  - Although Regional offices can help check claim and higher level review status, they cannot assist once it is with the Board of Veteran Appeals. 

### Pre-discharge claims
- VBA Type of care: Service member benefits
- (Proposed) VBA National description: We can guide you through the disability compensation process. If you've already initiated a claim or higher-level review, we can help you check the status. If you already receive disability benefits, we can help address any payment issues. If you need help with the IDES process, we may refer you to your PEBLO or MSC. 

### Disability compensation
- VBA Type of care: Veteran benefits
- (Revised) proposed VBA National description: We can guide you through the disability compensation process. We can help you understand your eligibility, start a claim, or complete your paperwork. If you've already initiated a claim or higher-level review, we can help you check the status. If you already receive disability benefits, we can help address any payment issues.

---
## Returning service member care and Transition assistance
> Returning service member care was determined to be separate from Transition assistance because 
> - different audiences:  Service member vs Veteran 
> - restarting health care after returning from service is particular to Reservists and Guard members who were receiving disability before deployment 

### Returning service member care
- Already available: Health Service API ID `transitionCounseling`, Add VBA Type of care: Service member benefits
- (Revised) proposed VBA National description: If you’re in the Reserves or National Guard and returning from military service, we can help you readjust to civilian life. We can help you apply for or restart VA health care and understand other benefits that you may be eligible for. We can help you file claims or connect you with programs that offer mental health services and education and career counseling. 

### Transition assistance 
- suggest using `assistance` or `information` rather than `help` which can be perceived as insulting
- Add to VA service taxonomy, VBA Type of care: Veteran benefits
- (Revised) proposed VBA National description: We can help you prepare for the move from military to civilian life by learning about VA benefits that you may be eligible for. We can also help you find out which time-sensitive benefits to consider when separating or retiring.

**Comment by davidmpickett** [comment]
> Name | Action | Comment
> -- | -- | --
> Integrated Disability Evaluation System | Do not add | Feedback indicates that this is a DOD program supported by the VA, not a VA program. The military initiates the IDES process, not the service member. VBA role in this will be represented by the Pre-discharge claim service term 

@mmiddaugh Just making some additional notes on this now for sake of thoroughness.

- Our decision not to add IDES to the VA Service Taxonomy for the Regional Office Pilot MVP doesn't mean that it won't ever be added. 
- During Public Contact research, I did hear about some IDES employees working out of Regional Offices
- IDES facilities are also part of the [overall VBA product](https://github.com/department-of-veterans-affairs/va.gov-cms/labels/VBA), even if they are out of scope for the RO modernization effort.

**P12** - "There is only one person in our office that does that.... [The only reason Service Members would visit RO is] if they wanted to meet with that person."

**P9** - "I supervise the Military Specialist Coordinators that do the IDES but that is separate from Public Contact... IDES is completely different, and not something that I, personally, think should be on the website."

**Comment by davidmpickett** [comment]
@xiongjaneg @jilladams - This ticket will likely roll over the sprint boundary but should be closed next week. I just remembered that Monday is a holiday. That plus my sick days and other tickets taking priority means it won't quite hit the sprint report.

**Comment by davidmpickett** [comment]
## EASY PEASY

Label | Machine Name | Health Service API ID | Notes
-- | -- | -- | --
Careers and employment | careers-and-employment | EducationAndCareerCounseling
Direct deposit information | direct-deposit-information | UpdatingDirectDepositInformation 
Military sexual trauma-related claims | military-sexual-trauma-claims | MilitarySexualTraumaClaims
Pre-discharge claims  | pre-discharge-claims | PreDiscargeClaimAssistance 
Transition assistance  | transition-assistance | TransitionAssistance 
VetSuccess on Campus  | vet-success-on-campus | VetSuccessOnCampus

## THINKY SLINKY

Label | Machine Name | Health Service API ID | Notes
-- | -- | -- | --
Compensation benefits for survivors | compensation-benefits-for-survivors | FamilyMemberClaimAssistance | Suggesting this as best fit for mapping the legacy Facilities API ID, even though it isn't perfect
Creating an account for VA.gov </br> ~~Veteran profile information~~  | creating-account-for-vagov | eBenefitsRegistrationAssistance  
Fiduciary services </br> ~~Financial services~~ | fiduciary-services | FiduciaryServices 
Pre-need burial planning </br> ~~Burial in a VA cemetery~~ | pre-need-burial-planning | PreNeedBurialPlanning

**Comment by davidmpickett** [comment]
@jilladams @xiongjaneg 
### End of sprint 101 update
- [Drafted](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16269#issuecomment-1894898969) proposed labels, machine names, and API IDs for 10 terms
- Updated source of truth spreadsheet
- Various other housekeeping updates on this and related tickets

### For sprint 102
- Discussion and approvals (UX sync)
- Adding approved terms to Drupal
- Adding subfields in Drupal
- Sharing for further feedback/approvals

**Comment by davidmpickett** [comment]
Label | URL Alias | Health Service API ID 
-- | -- | -- 
Careers and employment | careers-and-employment | EducationAndCareerCounseling
Direct deposit information | direct-deposit-information | UpdatingDirectDepositInformation 
Military sexual trauma-related claims | military-sexual-trauma-claims | MilitarySexualTraumaClaims
Pre-discharge claims | pre-discharge-claims | PreDiscargeClaimAssistance 
VetSuccess on Campus  | vet-success-on-campus | VetSuccessOnCampus

**Comment by davidmpickett** [comment]
Made good progress on sub fields today. Also messaged CAIA [on slack](https://dsva.slack.com/archives/C01K37HRUAH/p1705969155084889) to ask how they want to get notified when stuff is ready for more input.

**Comment by davidmpickett** [comment]
DRAFT request to CAIA https://github.com/department-of-veterans-affairs/va.gov-team/issues/74390

**Comment by davidmpickett** [comment]
My work on this is complete, pending final feedback and direction on what to send to CAIA from @mmiddaugh. This is on the agenda for UX sync tomorrow.

FYI @jilladams @xiongjaneg  I made the ACs more specific

**Comment by jilladams** [comment]
Follow on ticket: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17046

Slack thread: https://dsva.slack.com/archives/C0FQSS30V/p1706220664151049?thread_ts=1706219966.668729&cid=C0FQSS30V
From Michelle: 
> All 14 services in [your comment](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17046#issue-2101249060) are now available for VBA review and approval (behind the scenes FYI: I'm using a Sharepoint doc where they can comment - this will make adding to it easier, I hope)
> The only thing missing is the the online self-service description for the latest group (because I pulled them straight from the taxonomy) but I don't think that is critical.


@xiongjaneg @mmiddaugh we ok to close this, knowing the follow up on approvals will happen in the other ticket?

**Comment by davidmpickett** [comment]
There was one batch of terms that were partially drafted in this ticket (I gave them new labels), but aren't quite ready to send to VBA (they haven't been added to Drupal and had additional fields drafted). 

During this week's UX Sync, we clarified that these "Thinky Slinky" terms did not need sign off from CAIA on the updated labels before being adding to Drupal. I cut a new ticket to do the follow up work that would get them to VBA readiness:

https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17060

**Comment by davidmpickett** [comment]
Now we should be good to close this ticket with follow up work & approvals both tracked
