### ISSUE TITLE
Unexpected Value in CSV Export

### ISSUE THREAD

**Issue by maortiz-27-80** [department-of-veterans-affairs/va.gov-cms#16262]
**Actual behavior:** 
Reported by Michelle Middaugh from Facilities - Users who have never used the system now have 1970-01-01 00:00 am as the value in the Last access column on the exported csv

**Expected behavior:**

**Possible cause:**
Drupal is trying to render a date of 0 

**Possible solution:**
Edit the View to rewrite "0" as "never"

More details can be found in [the following Slack thread](https://dsva.slack.com/archives/CDHBKAL9W/p1701378544976389)

cc: @BerniXiongA6 

## Acceptance Criteria

- [ ] Invalid dates are rendered as some value, e.g. "never".

**Comment by maortiz-27-80** [comment]
Note 12/05 - Tentatively schedule for Sprint 99. cc: @BerniXiongA6

**Comment by BerniXiongA6** [comment]
@ndouglas Please async refine, thank you!! cc: @maortiz-27-80

**Comment by edmund-dunn** [comment]
This issue was the result of changes in tokens used for the rewrite. I had to change it from {{ access }} to {{ access_1__value }}
