### ISSUE TITLE
FE add  query and template for VA Police

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#16278]
## Description or Additional Context 
The page data from Drupal is ready to be used to build the FE page that will house the police react ap.

It was decided in sprint planning 12/6, that the template for MVP will contain only FAQs and contact information (listed on the system page).

## Acceptance Criteria
- [x] Add graphQL query for vamc_system_va_police content type.
- [x] Add page build step to content-build.
- [x] Add page level template (not including the React Ap)
- [x] Requires design review
- [x] Requires accessibility review

## Team
Please check the team(s) that will do this work.

- [ ] CMS Team
- [ ] Public Websites
- [x] Facilities
- [ ] Accelerated Publishing

**Comment by maxx1128** [comment]
I would give this ticket **13** points. It's adding an entirely new page query and template that matches designs and requires additional review, which is quite the lift.

**Comment by eselkin** [comment]
This should create an integration branch similar to VBA.

**Comment by xiongjaneg** [comment]
@maxx1128 @eselkin Example of contact info from Police
[VAP Chief - Facility Contact List (12-5-2023).csv](https://github.com/department-of-veterans-affairs/va.gov-cms/files/13590596/VAP.Chief.-.Facility.Contact.List.12-5-2023.csv)

**Comment by xiongjaneg** [comment]
Tagging in @ryguyk, related to [Slack thread on breadcrumbs and Lovell](https://dsva.slack.com/archives/C0FQSS30V/p1702417283756189)

**Comment by jilladams** [comment]
Almost done with the contact information pushed yesterday.
Almost ready for real final review.
Last step: writing automated tests.

**Comment by xiongjaneg** [comment]
Noting decision from 12/14 UX sync: RE Last Updated date at the bottom of the page, please do not show this. We don't want confusion later on when activity dates become available.

**Comment by mmiddaugh** [comment]
[Link to video](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Faaxn.sharepoint.com%2F%3Av%3A%2Fr%2Fsites%2FVeteransAffairsPD%2FShared%2520Documents%2FDemonstration%2520videos%2FCDA%2520walkthrough.mp4%3Fcsf%3D1%26web%3D1%26e%3DHCkX75&data=05%7C02%7C%7Cce5697f97106469f826f08dbfda3b909%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C638382651853206955%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=tA0mA6GaX5lmL971sjQryyjl7FKPsQMnDKxB0nIaVCg%3D&reserved=0) of the draft spreadsheet Axon is working on - sent in advance of our meeting on 12/19

**Comment by jilladams** [comment]
@mmiddaugh neither link is working for me (on CAG). Both return: "We're sorry but <email> can't be found in the aaxn.sharepoint.com directory. I suspect Axon would need to add us all to their directory by email, or make their link sharing "anyone with the link" etc. A hack we could try: if you played the vid on a screenshare and recorded the screenshare? Not sure whether Teams or Zoom would be easier for that, but I'm happy to work with you on it to try and figure it out. Or: maybe just a screenshot of the relevant CSV set up so far?

**Comment by jilladams** [comment]
But before we do all that: @xiongjaneg @eselkin could you all verify whether you're able to view the links Michelle shared? Might just be a me problem.

**Comment by xiongjaneg** [comment]
Same error message for me for both links

**Comment by jilladams** [comment]
Will deploy today!

**Comment by jilladams** [comment]
This merged but content-build failed today: https://github.com/department-of-veterans-affairs/content-build/actions/runs/7266975547

Follow up with CMS team: https://dsva.slack.com/archives/C02VD909V08/p1703029646084569?thread_ts=1703012486.553909&cid=C02VD909V08
