### ISSUE TITLE
Draft Facility locator mobile map conversation guide

### ISSUE THREAD

**Issue by ALogsdon3** [department-of-veterans-affairs/va.gov-cms#16293]
### User story
**AS A** Researcher
**I WANT** to document the details for conducting Facility locator mobile map research
**SO THAT** the research will achieve the stated goals and answer the research questions

### Templates

Use the appropriate template for the group you're conducting research with:
~~- [Editor-facing Conversation Guide Template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/research/editor-moderation-guide.md)~~
- [Veteran-facing Conversation Guide Template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/conversation-guide-template.md)

### Suggested workflow/tasks (Sprint 101) 
- [x] Draft conversation guide
- [x] Solicit review/feedback from UX Lead/PM and other team members
- [x] Revise draft

### Suggested workflow/tasks (Sprint TBD)
- [ ] Test prototype(s) with conversation guide and align
- [ ] Post on github in project research folder for final approval before submitting to Research Review cycle

---

## Acceptance Criteria  (Sprint 101) - 13 points
- [x] Conversation guide drafted
- [x] Follow-up with feedback providers if there are questions
- [x] Document insights relevant to future phases of the project

## Acceptance Criteria  (Sprint 102) - 3 points
- [x] Port Mural to Github in Draft state with clear tasks that should be functional in the coded prototype

## Acceptance Criteria  (Sprint 103) - 3 points
- [x] Draft revised based on UX Lead and other feedback
- [x] Conversation guide posted on github in project research folder
- [ ] Final approval obtained from Sitewide UX Lead

**Comment by ALogsdon3** [comment]
@xiongjaneg working ahead a bit since I won't be here to refine this next week. Tried to break the ACs down by sprint realistically. Please let me know if you have suggestions/updates. :)

**Comment by xiongjaneg** [comment]
@jilladams I set the estimate at 5 points for now for sprint 100.

**Comment by jilladams** [comment]
@ALogsdon3 @xiongjaneg I am just noticing: we pulled this into Sprint 100 for 5 points, but the ACs are all tagged for Sprint 101.  Does that just reflect that we were optimistic for Sprint 100, but now this will actually move in Sprint 101?

**Comment by jilladams** [comment]
Talked to Alexis in 1:1 and was reminded of this thread from Jane: https://dsva.slack.com/archives/C0FQSS30V/p1703795685125399, so confirming: Plan stays in 100, Convo guide has only 101 actions. Reflecting that in the sprints listed on ticket.

**Comment by ALogsdon3** [comment]
These comments on the research plan ticket are relevant to the conversation guide:
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14515#issuecomment-1872369981
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14515#issuecomment-1872371914
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14515#issuecomment-1874343562
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14515#issuecomment-1874357255

**Comment by ALogsdon3** [comment]
### Updates on the status of this ticket
After digging through Amanda's feedback and then discussing Michelle's feedback earlier in the week, I made extensive revisions to the conversation guide draft and documentation of all the complex considerations we'll need to be aware of when moving to the next phase of the research. 
Here's where we're at: 
- @mmiddaugh brought up a question this week about the prototype being specifically for _mobile_ map, but the recruiting criteria we reference in the research plan have a broader scope. @aklausmeier and I discussed recruitment last sprint, and my understanding from that convo and my own discovery work that recruiting screen reader users using mobile devices is very challenging. But one major concern with testing on desktop is that the functions we're interested in testing won't really be present in the desktop view. So, this is an area where more clarity (and therefore more work) is needed.
- Some of the research goals and hypotheses we'd previously agreed were paramount for this study are potentially at odds with how a screenreader will present the information, namely "Veterans will understand the difference between map view and list view, and how to move from one to the other" and "Veterans will understand how to interact with the map and how their interactions change the search results." I will need to examine this more closely after Amanda and Cindy's Header/Footer research is concluded to refine how we frame using the map with AT users. @laflannery's input will be very necessary, too!
- Due to the large number of unknowns (not having a prototype, waiting to glean the wisdom of Cindy and Amanda's study), I'm keeping the conversation guide draft very very drafty. There will be content to review at the end of the sprint, but we should expect this document to go through major edits and updates when we revisit this study later in Q1. 
cc: @xiongjaneg @jilladams

**Comment by jilladams** [comment]
@aklausmeier @ALogsdon3 @xiongjaneg FYI: relocated the AC "Draft revised based on UX Lead and other feedback" from current sprint to next sprint, just based on timing to allow Amanda to provide feedback. Holler if any concerns.

**Comment by ALogsdon3** [comment]
[Link to conversation guide in github](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/facility-locator/research/user-research/2024-01-mobile-map/conversation-guide.md)

**Comment by ALogsdon3** [comment]
ACs complete

**Comment by aklausmeier** [comment]
@xiongjaneg since this is being left in a "draft" mode, should we spin up a ticket in the backlog to "finalize"

**Comment by ALogsdon3** [comment]
Made extensive updates to the [conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/facility-locator/research/user-research/2024-01-mobile-map/conversation-guide.md), ready for @aklausmeier's review.

**Comment by aklausmeier** [comment]
@xiongjaneg @ALogsdon3 I've reviewed the draft conversation guide and I think we are at a good point to close this ticket and track future work in a new ticket since this will be set aside until staging prototype is ready for Midpoint review.

**New ticket(s) to "finalize convo guide" might include:**
_(Sprint TBD)_
-  Test prototype(s) with conversation guide and align
-  Obtain UX / PO final approval
-  Submit research convo guide with plan and prototype to collab cycle
-  Revise based on Collab Cycle feedback if needed
-  Submit to ResearchOps Review / Kickoff

**Comment by xiongjaneg** [comment]
ACs added to stubbed ticket #17214

**Comment by biannuz** [comment]
I've drafted an updated conversation guide for the team to review [in DSVA Slack](https://dsva.slack.com/canvas/C06S9DADEUB).

Once initial feedback is collected, I will post the conversation guide to GitHub.
