### ISSUE TITLE
Editor facing research for VBA Regional Offices Pilot

### ISSUE THREAD

**Issue by ALogsdon3** [department-of-veterans-affairs/va.gov-cms#16294]
Epic for research with VBA editors during the rollout of VBA RO pilot MVP

The purpose of this epic is to gather, analyze, and make improvements to VBA Regional Offices pages based on editor research during the rollout of the pilot MVP.

During the pilot MVP, 7 Regional Offices will be moving content from Teamsite CMS (AKA legacy web page) to Drupal CMS (AKA modernized web page). A legacy example is [Anchorage Regional Office's site](https://www.benefits.va.gov/anchorage/)

**Comment by davidmpickett** [comment]
Noting that this research is not launch blocking for Staging Review, so it can comfortably continue in the National Rollout epic, even though it started in the Pilot epic
