### ISSUE TITLE
Devshop environments can't access Facility API

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#1630]
## Defect 
The Make an appointment online widget at  http://vamcupgrade.web.demo.ci.cms.va.gov/pittsburgh-health-care/make-an-appointment/ doesn't load.

## Expected behavior

It should load.

**Comment by indytechcook** [comment]
There are some errors in the browser console:

![VA Pittsburgh Health Care | Make An Appointment | Veterans Affairs 2020-04-28 10-25-45](https://user-images.githubusercontent.com/121603/80499215-afdfa700-893a-11ea-9b51-ecb5ae4721e7.png)

**Comment by kevwalsh** [comment]
@indytechcook  I'm assuming it's a network issue, devshop can't hit the Facility API? This is not a critical defect yet, but will be when stakeholders at various VAMCs across VISN 4 start reviewing the content. 

@davidconlon What's the timeline on that? Mid-May?

**Comment by davidconlon** [comment]
@kevwalsh Likely pushed out to late May due to QA cleanup and learning curve.

**Comment by indytechcook** [comment]
@kevwalsh I'm not sure yet.  I just did a quick test and put in some info so I can remember to follow up later.

**Comment by ElijahLynn** [comment]
These URLs are not correct and are pointing at themselves. 

e.g. This is suppose to be the URL of the API, but somehow it is the hostname of the demo environment. If they are correct the browser can probably access them. 
http://vamcupgrade.web.demo.ci.cms.va.gov/js-report/api/0/store/?sentry_key=faker&sentry_version=7

**Comment by indytechcook** [comment]
I was able to update the URL of the API based upon the `buildtype` which has the options of `vagovdev`, `vagovstaging` and `vagovprod`.  

When I tested this locally I then got a CORS error:

![VA Pittsburgh Health Care | Make An Appointment | Veterans Affairs 2020-05-05 10-32-31](https://user-images.githubusercontent.com/121603/81079104-1aee2800-8ebd-11ea-847e-733cb6e63de0.png)

I'll spin this up on devshop to see if the CORS errors go away.

**Comment by indytechcook** [comment]
I logged https://github.com/department-of-veterans-affairs/vets-website/pull/12579 to change the `dev-api` to `sandbox-api` so we don't to replace it in our build.

**Comment by indytechcook** [comment]
The PR to fix our build has been merged but the CORS issue still remains.  The main solution is to have the vets-api accept wildcards in the domain but this is a pretty heavy lift.  The workaround is to set a list of domains to allow and maintain this list manually.

Information from slack conversation: 

* Location within the vets-api where CORS is setup: https://github.com/department-of-veterans-affairs/vets-api/blob/6833e2fe1aaccb790c726d7172efc71586a5fbd1/config/application.rb#L52
* `web_origin` settings are configured in the `devops` repo in the `<env>-settings.local.yml.j2` files (e.g. `prod-settings.local.yml.j2`)
* As far as CORS goes, no, CORS spec only allows *, nullor the full domain in the Access-Control-Allow-Origin header.
Our backend uses the rack-cors gem for this configuration.  Here’s a link to the docs on origin.
It says we can use a regex, which would do it…EXCEPT that we store these values as a string in the devops repo.  I can’t think of a way we could store a regex as a string along with other literal strings and parse all of that properly.

**Comment by indytechcook** [comment]
Domains to whitelist:

http://altoonahealthcare.demo.ci.cms.va.gov
http://altoonahealthcare.web.demo.ci.cms.va.gov
http://butlerhealthcare.demo.ci.cms.va.gov
http://butlerhealthcare.web.demo.ci.cms.va.gov
http://coatesvillehealthcare.demo.ci.cms.va.gov
http://coatesvillehealthcare.web.demo.ci.cms.va.gov
http://erie.demo.ci.cms.va.gov
http://erie.web.demo.ci.cms.va.gov
http://lebanonhealthcare.demo.ci.cms.va.gov
http://lebanonhealthcare.web.demo.ci.cms.va.gov
http://philadelphiahealthcare.demo.ci.cms.va.gov
http://philadelphiahealthcare.web.demo.ci.cms.va.gov
http://wilkesbarrehealthcare.demo.ci.cms.va.gov
http://wilkesbarrehealthcare.web.demo.ci.cms.va.gov
http://wilmingtonhealthcare.demo.ci.cms.va.gov
http://wilmingtonhealthcare.web.demo.ci.cms.va.gov

**Comment by ElijahLynn** [comment]
Hrm, so I was thinking that the initial pre-flight request should check if it coming from an internal source and then set it to `no-cors` and then the CORS headers won't matter.

**Comment by indytechcook** [comment]
> Hrm, so I was thinking that the initial pre-flight request should check if it coming from an internal source and then set it to no-cors and then the CORS headers won't matter

[Preflight Requests](https://developer.mozilla.org/en-US/docs/Glossary/Preflight_request) come from the browser and not javascript.  The point of the CORS is to allow the server to say which requests can make Ajax requests and which can't.

**Comment by ElijahLynn** [comment]
> > Hrm, so I was thinking that the initial pre-flight request should check if it coming from an internal source and then set it to no-cors and then the CORS headers won't matter
> 
> [Preflight Requests](https://developer.mozilla.org/en-US/docs/Glossary/Preflight_request) come from the browser and not javascript. The point of the CORS is to allow the server to say which requests can make Ajax requests and which can't.

To clarify, I mean modifying the preflight response from our server. Can we serve a different preflight response for internal URLs/IPs?

**Comment by indytechcook** [comment]
This isn't our server, it's the VETS API: https://github.com/department-of-veterans-affairs/vets-api/blob/6833e2fe1aaccb790c726d7172efc71586a5fbd1/config/application.rb#L52

**Comment by indytechcook** [comment]
Fixed on VMAC upgrade pr environment:  http://vamcupgrade.demo.ci.cms.va.gov/pittsburgh-health-care/make-an-appointment?_format=static_html

The other PR environments will need to be rebuild from the prod code base in order to work.
