### ISSUE TITLE
Content Release Failures on December 4, 2023

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-cms#16302]
## Description

This is a retroactive ticket written to cover work performed on December 4, 2023 to get content releases working.

**SNOW Ticket**: INC30118349

## Timeline

- `2023-12-04@08:02 AM`: First content release failed.
- `2023-12-04@08:08 AM`: Nate noticed that three content release attempts had failed, each within a couple of minutes of beginning.
- `2023-12-04@08:09 AM`: Noticed that the failures stemmed from failed Cypress downloads.
- `2023-12-04@08:11 AM`: Download could be completed outside the TIC; something was interrupting the download.
- `2023-12-04@08:34 AM`: Observation that Tugboat builds (in our network, but outgoing requests do not transit the TIC) completed successfully.
- `2023-12-04@08:39 AM`: Observation that manual downloads via `curl` from self-hosted runners would fail as well; presumably something in the network is to blame.
- `2023-12-04@08:42 AM`: Observation that manual downloads via `curl` from CMS staging would fail as well; issue is not confined to a specific VPC but spans multiple VPCs and environments.
- `2023-12-04@08:48 AM`: Observation that manual downloads of very large files (e.g. Debian ISOs) from these same environments succeed; there's something problematic in the remote server, the route, the TIC, or the data.
- `2023-12-04@08:53 AM`: Observation that manual downloads of different versions of Cypress succeed.
- `2023-12-04@08:59 AM`: Idea that we might be able to upgrade or downgrade slightly to avoid this issue.
- `2023-12-04@09:06 AM`: Observation that Linux amd64 build downloads seem to be broken for several versions, while Linux arm64 and macOS amd64 and arm64 downloads are functional.
- `2023-12-04@09:20 AM`: Tests to all three IP addresses to which `cdn.cypress.io` resolves failed; this combined with the version success/failure would seem to make it far less likely that the issue is in Cypress' infrastructure.
- `2023-12-04@09:54 AM`: Notified PM, DM, PO that we were approaching two hours without a content release and explained the situation.
- `2023-12-04@10:23 AM`: Opened platform support ticket.
- `2023-12-04@11:06 AM`: Peter Hill suggests TIC issues.
- `2023-12-04@11:11 AM`: Adrian Rollett suggests TIC issues.
- `2023-12-04@11:33 AM`: Mike Chelen suggests opening a SNOW ticket.
- `2023-12-04@12:06 PM`: Opened `content-build` PR to downgrade Cypress to 13.3.0, the last version that can be successfully installed.
- `2023-12-04@12:16 PM`: Peter approves above PR.
- `2023-12-04@01:14 PM`: Tests complete on PR and it is merged into `main`.
- `2023-12-04@01:23 PM`: A new content release starts and passes initial steps.
- `2023-12-04@02:00 PM`: Above content release fails for unrelated reasons, largely bad luck.
- `2023-12-04@02:12 PM`: New content release starts.
- `2023-12-04@02:56 PM`: First successful content release completes.

## Thoughts

I should've opened the Cypress downgrade PR a lot sooner. That would've cut a couple hours from the outage. I had a strong suspicion that the TIC was to blame, and I should've acted on that and then worked separately to find the underlying cause and address it with NOC.

**Comment by ndouglas** [comment]
@BerniXiongA6 @maortiz-27-80 @EWashb I opened this to track yesterday's nightmare. IDK if I should open a postmortem for that or not -- if I should, then I at least have the timeline done 🙂

**Comment by EWashb** [comment]
@ndouglas @maortiz-27-80 @BerniXiongA6 we don't need to open a post mortem. The failure was not caused by anything within our control. We were just part of a larger ecosystem of downstream issues it sounds like. If there is a post mortem from the TIC our issues should just be accounted for there.
