### ISSUE TITLE
Write postmortem for smartbanner.js rollback

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#16319]
## User Story or Problem Statement

Postmortem is a written blameless retro, intended to articulate what went wrong so that we as a VA ecosystem can learn from it, and put supports in place to prevent similar issues from happening in the future. Historically, Jill has written the PW postmortems, but it's time to share the love. 

## incident
We rolled back Mobile promo banners: https://github.com/department-of-veterans-affairs/content-build/pull/1824
This required an OOB deploy, which requires a postmortem be written.

Platform support thread: https://dsva.slack.com/archives/CBU0KDSB1/p1701801851929449

## Postmortem resources
* Postmortem template: https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Postmortems/_template.md
* Previous Public Websites postmortems as examples: https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/pulls/jilladams

## Acceptance Criteria
- [x] Postmortem is created and reviewed by DM before the other reviews are triggered
- [x] Postmortem is created as a PR and PO, and Joe Niquette are tagged as reviewers

**Comment by FranECross** [comment]
Evidence is gathered via slack threads, etc. Most links are in ticket body. FE folks on PW will write the PM this time. Randy & Chris will collab.

**Comment by jilladams** [comment]
Postmortem PR is up, https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/pull/1361, reviewers have been added, and Dave is aware that he owns next steps for follow up. Closing.
