### ISSUE TITLE
Update VBA Facility post-review and collab cycle feedback

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#16327]
## Description or Additional Context 
VBA Facility content type was reviewed by UX in #14888. 
Collab cycle feedback was reveiwed by UX in [15989](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15989#issuecomment-1889969077)

Recommendations are documented [in Figma](https://www.figma.com/file/aKdT4weNNthDxb3r6MolEh/VBA-Content-Specs?type=design&node-id=500-154&mode=design&t=EjEy51rex5oUY9jV-0). 

Character counter and error states updates are covered under separate tickets.

## Acceptance Criteria
- [ ] Review [Figma](https://www.figma.com/file/aKdT4weNNthDxb3r6MolEh/VBA-Content-Specs?type=design&node-id=500-154&mode=design&t=EjEy51rex5oUY9jV-0) for updates and annotations. Consult Jordan as needed.
- [ ] VBA Facility updates are made according to [Figma](https://www.figma.com/file/aKdT4weNNthDxb3r6MolEh/VBA-Content-Specs?type=design&node-id=500-154&mode=design&t=EjEy51rex5oUY9jV-0).
   - [ ] The order of many fields has shifted from current design to new design
   - [x] Text under **Editing this Content** has changed
   - [x] **Jump to edit** renamed to **On this page**
   - [x] **Operating status** fieldset 
     - [x] Is now part of **Location and contact information** fieldset
     - [x] Text under operating status section says "This status will display on the facility's page and in VA's facility locator tool." 
     - [x] Help text under Operating status Details says "Add relevant details about how this status will impact Veterans and visitors."
   - [x] **Banner alert**
       - [x] Links in help text have been linked properly (See comment below for screenshot/details) 
         - [x] [VA Design System (opens in a new window)] links to https://design.va.gov/components/banner/
         - [x] [Knowledge Base (opens in a new window)]links to https://prod.cms.va.gov/help/veterans-benefits-administration-vba/banner-alerts
   - [x] **Top of page information** fieldset
      - [x] Page introduction field is removed from content type
      - [x] This fieldset is removed
   - [ ] **Facility Image** fieldset
      - [x] Renamed from **Facility photo**
      - [x] Is now part of **Location and contact information** fieldset 
      - [x] New text guidance added
   - [ ] **Location and contact information** fieldset
      - [x] This fieldset now includes both editable (Operating Status & Facility photo) and non-editable fieldsets
      - [x] This fieldset should now be a collapsable accordion
      - [ ] The order of fields in the non-editable fieldset has shifted
        - [x] **Benefit office hours may vary** fetch field is now included here
        - [x] **Benefits hotline** fetch field is now included here
        - [x] **Db data** has been renamed **Facility CMS data** and has explanatory text
   - [ ] **Prepare for your visit** fieldset
     - [x] This fieldset should now be a collapsable accordion
     - [x] Initial text has changed
     - [ ] Accordion / Header  help text has changed
   - [ ] **Spotlight content** fieldset
     - [x] This fieldset should now be a collapsable accordion
     - [ ] Spotlight call to action link text help text should go to https://design.va.gov/content-style-guide/links#link-text
     - [x] Why can't I edit this bubble on National spotlight should say "This content is standardized to provide consistent messaging for facilities nationwide."
   - [x] **Facility services** = brand new tooltip
   - [x] **Other VA locations** = brand new tooltip
- [ ] Requires design review
- [ ] Requires accessibility review

## Team
Please check the team(s) that will do this work.

- [ ] CMS Team
- [ ] Public Websites
- [x] Facilities
- [ ] Accelerated Publishing

**Comment by davidmpickett** [comment]
Current design [VBA_Facility_Current.pdf](https://github.com/department-of-veterans-affairs/va.gov-cms/files/14115370/VBA_Facility_Current.pdf)

**Comment by davidmpickett** [comment]
New design [Uploading VBA_Facility_new.pdf.zip…]()

**Comment by davidmpickett** [comment]
@omahane @swirtSJW @thejordanwood 
I updated the ticket with a lot more details of the updates between the current and new design. I did not spell out every single detail, but this should be a pretty good guide

**Comment by laflannery** [comment]
In the banner alert section there are 2 links in the help text that do not currently work, they are just refreshing the current page. Can these be updated?
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/106678594/4c64d833-e7a6-4c4e-9279-64abef75ce61)

**Comment by omahane** [comment]
@davidmpickett The changes to the design would change the header and content help text for all Accordions. I want to confirm that this is expected.

**Comment by omahane** [comment]
> @davidmpickett The changes to the design would change the header and content help text for all Accordions. I want to confirm that this is expected.

In fact, there are a number of changes in the design that would affect the paragraphs wherever they appear. Is that desired?

**Comment by omahane** [comment]
# Spotlight call to action link help text
@davidmpickett 
![Screenshot 2024-02-06 at 2 03 47 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/766573/380f7679-bfec-47c4-bdc5-25dba8d038c0)

`docroot/modules/contrib/linkit/src/Plugin/Field/FieldWidget/LinkitWidget.php`
needs to change to allow for the use of field help text, which would be the ideal solution, but an [issue needs to be made on the module](https://www.drupal.org/node/add/project-issue/linkit) to allow that.

**Comment by davidmpickett** [comment]
@xiongjaneg @aklausmeier Here's a small spinoff ticket that would likely need to go to the CMS Platform team for resolution. Not likely a high-priority item, but wanted to make sure it was documented https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17170

**Comment by laflannery** [comment]
Noting that I changed the above ticket completely. It is a request to add a CSS property to the CMS design system as this should be a global change

**Comment by davidmpickett** [comment]
> # Spotlight call to action link help text
> @davidmpickett ![Screenshot 2024-02-06 at 2 03 47 PM](https://private-user-images.githubusercontent.com/766573/302762548-380f7679-bfec-47c4-bdc5-25dba8d038c0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc1MTcyOTgsIm5iZiI6MTcwNzUxNjk5OCwicGF0aCI6Ii83NjY1NzMvMzAyNzYyNTQ4LTM4MGY3Njc5LWJmZWMtNDdjNC1iZGM1LTI1ZGJhOGQwMzhjMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwOVQyMjE2MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xOWY0MGIyNDBmY2ZmZTljNWVjZDMwZmZiOGRlNjRhNzE5ZGQxNzBkY2IxNzFkYTExYjJkMjdhNDg5NmE4YzRjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.H9u406TUaJIlcF2J4xpj8sCekZP_I8M98D4V6Z2KcoI)
> 
> `docroot/modules/contrib/linkit/src/Plugin/Field/FieldWidget/LinkitWidget.php` needs to change to allow for the use of field help text, which would be the ideal solution, but an [issue needs to be made on the module](https://www.drupal.org/node/add/project-issue/linkit) to allow that.

@omahane here's a stub of an issue for bringing this to CMS Platform team https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17201

@xiongjaneg Again, not likely a high priority, but just documenting for consideration
