### ISSUE TITLE
Create documentation in Confluence for CMS Collaboration Cycle Design Intent Touchpoint

### ISSUE THREAD

**Issue by BlakeOrgan** [department-of-veterans-affairs/va.gov-cms#16321]
## User Story or Problem Statement
Now that we have a solid starting point for the CMS Collab Cycle Kickoff Request as a part of [ticket 15438](https://app.zenhub.com/workspaces/vagov-cms-team-5c0e7b864b5806bc2bfc2087/issues/gh/department-of-veterans-affairs/va.gov-cms/15438), we need documentation that goes further into detail around the Design Intent Touchpoint of the CMS Collab Cycle that is only accessible for the CMS team and explains what our responsibilities are in this step of the process.

## Description or Additional Context.

- Here is a link to [Collaboration Cycle Design Intent Touchpoint documentation from Platform](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1979252752/Design+Intent) that we can use for guidance.
- Here is a link to [a mural](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1872822276/Custom+Tracks+Flow) that Platform uses to determine which touchpoints to recommend that we can use as guidance.
- Here is a link to the [CMS Team's documentation repo in Confluence](https://vfs.atlassian.net/wiki/spaces/PCMS/pages/2689761454/CMS+Collaboration+Cycle). This is where we will need to house documentation relating to the CMS Collab Cycle that is only accessible by the CMS team.

## Acceptance Criteria
- [x] Confluence is updated with documentation for the Design Intent Touchpoint

## Team
Please check the team(s) that will do this work.

- [x] CMS Team
- [ ] Public Websites
- [ ] Facilities
- [ ] Accelerated Publishing

**Comment by BerniXiongA6** [comment]
@BlakeOrgan is waiting to hear back from @EWashb on her meeting with Shira before taking on this ticket. cc: @maortiz-27-80 @BerniXiongA6

**Comment by BerniXiongA6** [comment]
Great, thanks @BlakeOrgan -- thanks for udpating the pipeline for the tickets! cc: @maortiz-27-80

**Comment by BlakeOrgan** [comment]
@EWashb @maortiz-27-80 @BerniXiongA6 

Documentation in Confluence has been updated you can use the following links to view the documentation. Please note that anything that had outstanding questions or things that would require action items are outlined directly in the documentation using the yellow warning panels.

- [Design Intent - Scheduling](https://vfs.atlassian.net/wiki/spaces/PCMS/pages/2877227060)
- [Design Intent - During the Meeting](https://vfs.atlassian.net/wiki/spaces/PCMS/pages/2877030487)
- [Design Intent - After the Meeting](https://vfs.atlassian.net/wiki/spaces/PCMS/pages/2876801405)
- [Design Intent - How to document feedback](https://vfs.atlassian.net/wiki/spaces/PCMS/pages/2876540167)
