### ISSUE TITLE
Typo in field config

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#16322]
## Describe the defect
Should say outstation not oustation.

![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5752113/921ea5aa-8d44-4b20-a5ac-9f8ad9209688)

## To Reproduce
1. Go to a vet center outstation
3. see the type on the common name field

## AC / Expected behavior
- [ ] outstation is spelled correctly.

## Additional context
Add any other context about the problem here. Reach out to the Product Managers to determine if it should be escalated as critical (prevents users from accomplishing their work with no known workaround and needs to be addressed within 2 business days).

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Defect")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS workstream (orange) (not needed for bug tickets)
- [ ] CMS-supported product (black)

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [ ] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`
- [ ] `Accelerated Publishing`

**Comment by swirtSJW** [comment]
Been merged, should land on prod tomorrow.  Consider this done.

**Comment by jilladams** [comment]
https://prod.cms.va.gov/san-juan-vet-center/st-thomas-vet-center-outstation
![Screenshot 2023-12-19 at 3 51 53 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/85581471/12ce5f94-5ee9-43eb-b5d6-be60fc5b7bb3)

Closing
