### ISSUE TITLE
Copy for Events see all link(s)

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#16323]
## Description
#15766 - we need to update the See all links. 

IA feedback: https://github.com/department-of-veterans-affairs/va.gov-team/issues/67025
[IA mural treatment](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1695321619292/8c3bdcb8a5e55c95c74f42d9a722d34d2b4f4c14?wid=0-1697842616395)

### Proposed language 
3 cases
* VAMC events
* VAMC events also on the Natl Outreach Events calendar
* Outreach Events cal events

[Proposal in comments](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16323#issuecomment-1894038228)

**Comment by FranECross** [comment]
Need to queue up for Jordan (or Dave) in Sprint 100 @FranECross

**Comment by davidmpickett** [comment]
**Notes**
- I'm using "VA Eastern Oklahoma health care" as an example VAMC System name to slot in to these examples for readability. You can see all 140 possibilities for VAMC System name in [prod](https://prod.cms.va.gov/admin/content?title=&type=health_care_region_page&moderation_state=All&owner=All&order=title&sort=asc&page=0). 
- Are these going to be using an [active link](https://design.va.gov/components/link/#active) or a default link? Current event pages are using active link, but mural mock up shows default links.
- Product question: are VA outreach events all within the USA? Is "across the country" an accurate summary?

| Case | Proposed language  | 
| --- | --- |
| VAMC event | Learn about other events offered at VA Eastern Oklahoma health care. <br/> [Browse the VA Eastern Oklahoma health care events calendar >]() <br/> <br/>Learn about other VA events offered across the country. <br/> [Browse the VA outreach events calendar >](https://www.va.gov/outreach-and-events/events/)  |
| VAMC events that are also featured on National Outreach calendar | Learn about other events offered at VA Eastern Oklahoma health care. <br/> [Browse the VA Eastern Oklahoma health care events calendar]() <br/> <br/>Learn about other VA events offered across the country. <br/> [Browse the VA outreach events calendar](https://www.va.gov/outreach-and-events/events/) |
| Outreach calendar events | Learn about other VA events offered across the country. <br/> [Browse the VA outreach events calendar](https://www.va.gov/outreach-and-events/events/) |

**Comment by jilladams** [comment]
@davidmpickett 
Re: [active link](https://design.va.gov/components/link/#active) or a default link:  not decided yet, but we do have a follow up design ticket to give it a treatment once the copy is agreed upon: #15946 

Product question: good call out, there are events in Guam at minimum, so "Across the country" is probably not correct to use. Sorry about that!

**Comment by davidmpickett** [comment]
@jilladams 

Updated [my comment](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16323#issuecomment-1894038228) to remove references to country and added variations that could be considered during design phase

**Comment by jilladams** [comment]
Woo! Closing.
