### ISSUE TITLE
Create documentation in Github for CMS Collaboration Cycle Design Intent Touchpoint 

### ISSUE THREAD

**Issue by BlakeOrgan** [department-of-veterans-affairs/va.gov-cms#16320]
## User Story or Problem Statement
Now that we have a solid starting point for the CMS Collab Cycle Kickoff Request as a part of [ticket 15438](https://app.zenhub.com/workspaces/vagov-cms-team-5c0e7b864b5806bc2bfc2087/issues/gh/department-of-veterans-affairs/va.gov-cms/15438), we need documentation that goes further into detail around what is typically the first touchpoint in the process that our team would recommend to other teams - the Design Intent Touchpoint.

## Description or Additional Context.

- Here is a link to [Platform's documentation for the Design Intent Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/design-intent) that we can use as a guide for creating our documentation that is specific to the CMS.
- Here is a link to the [CMS Team's Collab Cycle documentation repo in Github](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/cms/collaboration-cycle). This is where we will need to house documentation relating to the CMS Collab Cycle and the Design Intent touchpoint.

## Acceptance Criteria
- [x] Github is updated with documentation for the Design Intent touchpoint.

## Team
Please check the team(s) that will do this work.

- [x] CMS Team
- [ ] Public Websites
- [ ] Facilities
- [ ] Accelerated Publishing

**Comment by BerniXiongA6** [comment]
Thanks @BlakeOrgan -- and I appreciate the pipelines updates too! you rock!! cc: @maortiz-27-80

**Comment by BlakeOrgan** [comment]
Documentation for the [Design Intent Touchpoint](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/collaboration-cycle/design-intent.md) has been written and can be viewed in Github.
