### ISSUE TITLE
Conduct Federal header/footer research sessions

### ISSUE THREAD

**Issue by cindymerrill** [department-of-veterans-affairs/va.gov-cms#16336]
### User story
**AS A** researcher
**I WANT** to conduct research sessions with participants
**SO THAT** we can get feedback on Federal header/footer

**Guidelines**
- [Moderator guidelines](https://depo-platform-documentation.scrollhelp.site/research-design/conducting-research-sessions)
  - [Research Safety guidelines](https://depo-platform-documentation.scrollhelp.site/research-design/research-safety-and-emergency-exit-strategies) 
- [Notetaker guidelines](https://depo-platform-documentation.scrollhelp.site/research-design/notetaker-guidelines)
  - For Veteran-facing research, Perigean can provide a notetaker
  - For Editor-facing research, recruit a member of the product team to take notes
- [Observer guidelines](https://depo-platform-documentation.scrollhelp.site/research-design/observer-guidelines)

**Recruitment Trackers**
- Veteran-Facing research should follow [Platform guidance](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/accessibility/research/recruitment.md) on recruitment tracking
  - [VA recruitment checker spreadsheet in Google Sheets](https://docs.google.com/spreadsheets/d/1pq7TSHZonfpzAQBJj6B2geGHlNUwZEs4DzEvxcRgu0o/edit?usp=sharing)

**No-shows and rescheduling**
- If a participant doesn't show up at the scheduled start time, they should be contacted
  - In Veteran-facing research, the Perigean will contact the participant by phone and email
  - In Editor-facing research, the Moderator should contact the participant through email or Microsoft Teams
- If the participant hasn't shown up within 15 minutes of the start, consider it a no-show
  - See if the participant can reschedule for a different available slot 
  - If unable to reschedule, mark them officially as a no-show in the recruitment tracker 
- Keep the PM and Sitewide UX Lead in the loop about no-shows in case additional sessions need to be scheduled

### For Sprint 99: About half of the research sessions will be conducted (5 pts)

**Before first session** 
- [x] Pilot session(s) conducted and any relevant edits made to conversation guide
- [x] Moderator(s), Notetaker(s), & Observer(s) reviewed guidelines for their role(s)

**After every session**
- [x] Observers and Notetakers shared their notes with Research Lead
- [x] Researcher debriefed (i.e., into note-taking spreadsheet/Mural)
- [x] Session recording and transcript downloaded from Zoom
- [x] Remove any PII then upload transcript to EnjoyHQ so can highlight quotes
- [x] Notes taken by observers have been reviewed by Research Lead
- [x] *(for Veteran-facing research)* Session is checked off as completed or no-show in Recruitment Request ticket 

**After ALL sessions**
- [x] Have enough research sessions to satisfy recruitment criteria or Sitewide UX Lead/PO
- [ ] All notes stored in the research folder on github
  - [x] Notes documents for cancelled/no-show sessions have been deleted

*For Veteran-facing research ONLY:*
- [x]  Final participant list downloaded from Perigean 
- [x]  Display name of Perigean Zoom account changed back to what it was 
- [x] Recruitment tracker updated with participant demographics  
- [x] For no-show participants, data entered as "N"'s

**Comment by cindymerrill** [comment]
P1 was a no-show, but P2 was great!

**Comment by cindymerrill** [comment]
Completed the study with 10 participants and 2 no-shows (including the last scheduled session today).

**Comment by cindymerrill** [comment]
Only tasks left: 

1. Get notes from Chris Kim, who watched a session via recording
2. Upload all session notes into Enjoy HQ
3. Updated conversation guide in Enjoy HQ

**Comment by cindymerrill** [comment]
I completed tasks 1 and 3 above, and 2 is not straightforward (because I just discovered that you can't upload markdown files to EnjoyHQ), so I'm going to add this task into the post-research task ticket and close this ticket as is. FYI @aklausmeier @jilladams @FranECross .

**Comment by aklausmeier** [comment]
@cindymerrill You can not directly upload markdown files. The solution is to highlight text in Github, copy, and paste into a new note under data tab in EnjoyHQ project. This should carry over the formatting.
