### ISSUE TITLE
[Spike] UX Discovery of Datadog

### ISSUE THREAD

**Issue by BlakeOrgan** [department-of-veterans-affairs/va.gov-cms#16334]
## User Story or Problem Statement
Now that @BlakeOrgan has access to Datadog, discovery is needed to plan out potential new ways to track UX related info in Datadog.

## Description or Additional Context 
@joagnitti did her own Datadog audit and has created her own Datadog wishlist in ticket [#15548](https://app.zenhub.com/workspaces/vagov-cms-team-5c0e7b864b5806bc2bfc2087/issues/gh/department-of-veterans-affairs/va.gov-cms/15548), however Product Design and Research might have slightly different things they would like to track.

## Acceptance Criteria
- [x] Datadog has been explored
- [x] Potential ways to track UX data has been documented in this ticket

## Team
Please check the team(s) that will do this work.

- [x] CMS Team
- [ ] Public Websites
- [ ] Facilities
- [ ] Accelerated Publishing

**Comment by BerniXiongA6** [comment]
Hi @BlakeOrgan Note from sprint planning, @EWashb mentioned taking a look at #11928 when doing this ticket -- thanks! cc: @maortiz-27-80

**Comment by BlakeOrgan** [comment]
@EWashb @maortiz-27-80 @BerniXiongA6 @joagnitti 

After reviewing what features are available on Datadog, I've identified the following features as good opportunities to explore as we expand our UX monitoring. Reading the documentation leads me to believe that these features will need to be set up by a developer, but once they're set up we can use them to better inform Product and UX decisions.

# Real User Monitoring (Also known as RUM)
All of the monitoring features in Datadog that are most relevant to UX are under the Real User Monitoring section.

## Session Replay

With Datadog RUM’s Session Replay feature, you can watch individual user sessions using a video-like interface. This allows you to view exactly how your users interact with your website, saving you time and guesswork recreating bugs and helping you understand patterns in your users’ behavior.

Datadog Links:



* [Documentation](https://docs.datadoghq.com/real_user_monitoring/session_replay/)
* [Blog](https://www.datadoghq.com/blog/session-replay-datadog/?_gl=1*jotg6s*_gcl_aw*R0NMLjE3MDI0MDkxODIuQ2p3S0NBaUFwdUNyQmhBdUVpd0E4Vko2SnR4b2Z5THBDOXpYX2xjeDNPSW5DbVBhMmUteVJoYzZxOEtmcjZWSk5ia0tNeDdUM1hwRlNCb0NpbjRRQXZEX0J3RQ..*_gcl_au*NTMzNTM5Mjc2LjE3MDI0MDkxNDU.*_ga*MzQ4MDg2MDA1LjE3MDI0MDkxNDY.*_ga_KN80RDFSQK*MTcwMjQwOTE0Ni4xLjEuMTcwMjQxMjU4My4wLjAuMA..*_fplc*VnI0YVZVNEpwVk1NZUxpVWNIOFpxY2xmdnNKT2FnRzNpdDBxZTJGVzZHVElaNXNSY3BMTGdWeEdDdzFaJTJGSXZCNGlkeXZwNTFDbXZ2b0JCbU80dUJDTWtPQndBMFdEUmVtN1NTR0I2R0NHRHdUVURHem5GVU5jbnZhSXV0dkElM0QlM0Q.)


## Heat Maps

A heat map is a visualization of your user’s interactions overlaid on Session Replay data. Real User Monitoring has three different types of heatmaps:



* **Click maps:** View user interactions (clicks) to understand how users engage with your page
* **Top Elements:** View a ranking of up to the top 10 most interacted-with elements on a given page.
* **Scroll maps:** View how far users scroll down a page, including where the average fold of a page falls. The average fold is the lowest point on a page that a user can see on their device without scrolling.

Datadog Links:



* [Documentation](https://docs.datadoghq.com/real_user_monitoring/heatmaps)
* [Blog on Click Maps](https://www.datadoghq.com/blog/visualize-behavior-datadog-heatmaps/)
* [Blog on Scroll Maps](https://www.datadoghq.com/blog/visualize-behavior-datadog-scrollmaps/?_gl=1*1ebti82*_gcl_aw*R0NMLjE3MDI0MDkxODIuQ2p3S0NBaUFwdUNyQmhBdUVpd0E4Vko2SnR4b2Z5THBDOXpYX2xjeDNPSW5DbVBhMmUteVJoYzZxOEtmcjZWSk5ia0tNeDdUM1hwRlNCb0NpbjRRQXZEX0J3RQ..*_gcl_au*NTMzNTM5Mjc2LjE3MDI0MDkxNDU.*_ga*MzQ4MDg2MDA1LjE3MDI0MDkxNDY.*_ga_KN80RDFSQK*MTcwMjQwOTE0Ni4xLjEuMTcwMjQxNTYwOS4wLjAuMA..*_fplc*bndXa2xFRUdSRmdiT2hEUmFLT0dBNW9IVkZya0VBcGpaWkIlMkJCME1NNUxkJTJCcTMlMkJLb2w1Q2JJZjUxZUZYVGolMkZPZlV4SnU5ZkRzQzUxb2I5SzBmVjhOYiUyRkNBWmlIZkRpYVN0TmdHUXRaZVlBWjF5TjB6VHJMaWlMMWlibks3ZyUzRCUzRA..)


## Frustration Signals

Frustration signals help you identify your application’s highest points of user friction by surfacing moments when users exhibit frustration.

Real User Monitoring collects three types of frustration signals:



* **Rage Clicks:** A user clicks on an element more than three times in a one-second sliding window.
* **Dead Clicks:** A user clicks on a static element that produces no action on the page.
* **Error Clicks:** A user clicks on an element right before a JavaScript error occurs.

Datadog Links:



* [Documentation](https://docs.datadoghq.com/real_user_monitoring/frustration_signals/)
* [Blog](https://www.datadoghq.com/blog/analyze-user-experience-frustration-signals-with-rum/?_gl=1*88bc6k*_gcl_aw*R0NMLjE3MDI0MDkxODIuQ2p3S0NBaUFwdUNyQmhBdUVpd0E4Vko2SnR4b2Z5THBDOXpYX2xjeDNPSW5DbVBhMmUteVJoYzZxOEtmcjZWSk5ia0tNeDdUM1hwRlNCb0NpbjRRQXZEX0J3RQ..*_gcl_au*NTMzNTM5Mjc2LjE3MDI0MDkxNDU.*_ga*MzQ4MDg2MDA1LjE3MDI0MDkxNDY.*_ga_KN80RDFSQK*MTcwMjQwOTE0Ni4xLjEuMTcwMjQxNTc3Ny4wLjAuMA..*_fplc*YTZqQnhCWm5VQlJJOElCdldhUTlndHJVVUZtRkZWaUY4emlQcEtTQTcyVEJrZlowdE1xYWNaOEd3c3NkOHRSWVg2b0tVdUlaWiUyRktkazdpSjRzNmJGJTJGVUlrQVEwV3pjaFNuZWVrMFdFMnhRSHI0JTJGdGolMkZCQ0JudHU5WnVaSmclM0QlM0Q.)


##  Funnel Analysis

Funnel analysis helps you track conversion rates across key workflows to identify and address any bottlenecks in end-to-end user journeys. Specifically, you can:



* See if customers drop off at a certain point due to poor website performance
* Track how the conversion rate changes over time as new features are built
* Measure how adding new steps to a workflow impacts drop off rate

Datadog Links:



* [Documentation](https://docs.datadoghq.com/real_user_monitoring/funnel_analysis)
* [Blog](https://www.datadoghq.com/blog/reduce-customer-friction-funnel-analysis/?_gl=1*fpcm97*_gcl_aw*R0NMLjE3MDI0MDkxODIuQ2p3S0NBaUFwdUNyQmhBdUVpd0E4Vko2SnR4b2Z5THBDOXpYX2xjeDNPSW5DbVBhMmUteVJoYzZxOEtmcjZWSk5ia0tNeDdUM1hwRlNCb0NpbjRRQXZEX0J3RQ..*_gcl_au*NTMzNTM5Mjc2LjE3MDI0MDkxNDU.*_ga*MzQ4MDg2MDA1LjE3MDI0MDkxNDY.*_ga_KN80RDFSQK*MTcwMjQwOTE0Ni4xLjEuMTcwMjQxNTcyNy4wLjAuMA..*_fplc*Z1BsbkZPMSUyRlpmRSUyQmNDcFFqSU43OFRsVnF1QVlVOU0wbzVFRHFyRWc4MXg5UjlqZzhwdHVnZHlLYUZ3MFIwcSUyQjRpZDF2WnVNajZaVlVHemhydkt4ejl1Y1Z5RUdRRUxXd1FscXhrVENSJTJGTW5CT01YeWhJbU91cFA3U0RRdnclM0QlM0Q.)


## Feature Flag Tracking (In Beta)

Feature flag data gives you greater visibility into your user experience and performance monitoring by allowing you to determine which users are being shown a specific feature and if any change you introduce is impacting your user experience or negatively affecting performance.

By enriching your Real User Monitoring data with feature flag data, you can:



* Be confident that your feature will successfully launch without unintentionally causing a bug or performance regression
* Correlate feature releases with performance, pinpoint issues to specific releases, and troubleshoot faster
* Streamline data collection and analysis and focus on troubleshooting

Datadog Links:



* [Documentation](https://docs.datadoghq.com/real_user_monitoring/feature_flag_tracking)
* [Blog](https://www.datadoghq.com/blog/feature-flag-tracking/?_gl=1*vsm091*_gcl_aw*R0NMLjE3MDI0MDkxODIuQ2p3S0NBaUFwdUNyQmhBdUVpd0E4Vko2SnR4b2Z5THBDOXpYX2xjeDNPSW5DbVBhMmUteVJoYzZxOEtmcjZWSk5ia0tNeDdUM1hwRlNCb0NpbjRRQXZEX0J3RQ..*_gcl_au*NTMzNTM5Mjc2LjE3MDI0MDkxNDU.*_ga*MzQ4MDg2MDA1LjE3MDI0MDkxNDY.*_ga_KN80RDFSQK*MTcwMjQwOTE0Ni4xLjEuMTcwMjQxNTgxNy4wLjAuMA..*_fplc*UzRGSnlHUEhvektyJTJCZGg0OVBrWlklMkJ2M0EwWiUyRk55S1FNJTJGTFdMWmR2cU4lMkZWY2dFNFFKWkpQSFVqSTdvTElZcFNpUjNwemIlMkJNRGprNW80eCUyRnRSdDNLY0dabk9XanlsNnBGVEtLMEVCVWFnSkRmQVZERDRvYjhUV1JRa3JzbmclM0QlM0Q.)
