### ISSUE TITLE
Standardize character counter in text boxes

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#16345]
## User Story or Problem Statement
Character counts are currently handled in a couple different ways. This ticket is to work on which should be the standard approach.

VAMC spotlight
<img width="814" alt="Screenshot 2023-12-07 at 3 02 59 PM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/73648238/33f9e818-487c-4e9a-a494-3c0d7646645f">

VAMC operating status
<img width="801" alt="Screenshot 2023-12-07 at 3 01 47 PM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/73648238/e24247e2-26f4-4456-bfb1-4a1c17a3dee8">

From CMS Team collab cycle for VBA in #15989 
For all CMS interfaces:
All character counters MUST behave the same across all screens of this product and MUST align with other character counters in the CMS. Collaboration between a designer on this team and the CMS team may be necessary to determine the best path forward on how character counters are handled in this product.

## Acceptance Criteria
- [ ] Testable_Outcome_X
- [ ] Testable_Outcome_Y
- [ ] Testable_Outcome_Z
- [ ] Requires design review
- [ ] Requires accessibility review

**Comment by davidmpickett** [comment]
Closing as duplicate. These issues have all been individually ticketed and are tracked in [this epic](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10241)
