### ISSUE TITLE
Install GH CLI on self-hosted GHA runners

### ISSUE THREAD

**Issue by JunTaoLuo** [department-of-veterans-affairs/va.gov-cms#16358]
### Tasks:

The default GHA runners have the [GH CLI](https://cli.github.com/) installed which is helpful for writing GHA workflows. To avoid manually installing this CLI as a separate step in GHA workflows, it's best to install it on the self hosted runners so there is parity between self-hosted runners and GHA runners

### Team
Please check the team(s) that will do this work.

- [x] `CMS Team`
- [ ] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`

**Comment by JunTaoLuo** [comment]
@BerniXiongA6 @ndouglas @maortiz-27-80 Would like to get this issue prioritized for next sprint since it blocks part of https://github.com/department-of-veterans-affairs/va.gov-cms/pull/16279

**Comment by BerniXiongA6** [comment]
Hi @JunTaoLuo could we have you size the ticket? Sorry we didn't get a chance to do so in the planning meeting. Thank you sir! cc: @maortiz-27-80

**Comment by JunTaoLuo** [comment]
I've currently estimated this as a 1 since all it took for me was `brew install gh` and logging in but I'm not sure if there's anything extra we have to do on the self hosted runners. Feel free to bump it up if it turns out to be more complicated.

**Comment by JunTaoLuo** [comment]
I was able to find a workaround so this work is no longer needed.
