### ISSUE TITLE
New VAMC Facility: Naval Hospital Pensacola VA Clinic [Ready for redirect]

### ISSUE THREAD

**Issue by stefaniefgray** [department-of-veterans-affairs/va.gov-cms#16355]
## Intake
- [x] What triggered this runbook? (Flag in CMS, Help desk ticket, Product team, VHA Digital Media)
Trigger: Flagged Facilities view

- [x] Link to associated help desk ticket (if applicable)
Help desk ticket: https://va-gov.atlassian.net/browse/VAHELP-6710

- [x] Name of submitter (if applicable)
Submitter: @stefaniefgray 

- [x] If the submitter is an editor, send them links to any relevant KB articles for the VAMC Facility product.
KB articles: <insert_kb_article_links>

- [x] Link to facility in production:
Facility CMS link: https://prod.cms.va.gov/gulf-coast-health-care/locations/naval-hospital-pensacola-va-clinic
Facility API ID: vha_520QC

### New VAMC Facility
Please refer to the Knowledge Base article titled "How do I add a facility to my health care system?" for more information: https://prod.cms.va.gov/help/vamc/about-locations-content-for-vamcs/how-do-i-add-a-facility-to-my-health-care-system

#### CMS help desk steps
**Note: If the help desk is waiting on information from the facility staff or editor, add the "Awaiting editor" flag to the facility with a log message that includes a link to this ticket. Remove the flag when the ticket is ready to be worked by the Facilities team. Be sure to preserve the current moderation state of the node when adding or removing the flag.**
- [x] 1. Become aware that the new facility is now on the Facility API (typically, via a Flag, but this may come in as a helpdesk ticket).
- [x] 2. If the editor has followed the steps from the above Knowledge Base article and included which section and VAMC the facility belongs to (i.e. VA Pittsburgh), great! **Proceed to step 3.** If not, please check with the editor or VHA digital media regarding what section and VAMC it belongs to.
- [x] 3. Updates the Section (default is "VAMC facilities", but it should be a VAMC system in a VISN) and VAMC system field accordingly.
- [x] 4. Communicate with editor (cc VHA Digital Media) to give them go-ahead to complete the content, with this [KB article](https://prod.cms.va.gov/help/vamc/about-locations-content-for-vamcs/how-do-i-add-a-facility-to-my-health-care-system). (See sample notification email below)

<details><summary>Email template </summary>

```

Hello! You should now be able to edit the draft page for this facility, located at [LINK TO NEW FACILITY DRAFT PAGE ON PROD]

Important: Please make sure that all relevant steps listed within the “How do I add a facility to my health care system?” Knowledge Base article have been completed: https://prod.cms.va.gov/help/vamc/about-locations-content-for-vamcs/how-do-i-add-a-facility-to-my-health-care-system

Once finished, please save this page (and all related VAMC Facility Health Service pages) in the moderation state “Draft." Please do not save them as “Published.”

Please let us know when your draft content is complete, so that we can wrap up the technical process from our end before publishing the new facility to VA.gov. Thanks!

```

</details>

- [x] 5. Create a [URL change request](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/new?assignees=&template=runbook-facility-url-change.md&title=URL+Change+for%3A+%3Cinsert+facility+name%3E), changing the entry from the old facility URL to the new facility URL. (**Note: The URL change request ticket blocks the completion of this ticket.**)

https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16356

- [x] 6. When editor has prepared content and let help desk know, reassign this issue to appropriate CMS engineer on Product Support team, for bulk publishing.

#### CMS engineer steps
- [x] 7. CMS engineer executes the steps of the URL change request ticket from step 5 above.

(Redirects deploy weekly on Wed. at 10am ET, or by requesting OOB deploy (of the revproxy job to prod) in #vfs-platform-support. Coordinate the items below and canonical URL change after URL change ticket is merged, deployed, and verified in prod.)

#### Drupal Admin steps (CMS Engineer or Help desk)
_Help desk will complete these steps or escalate to request help from CMS engineering._
- [x] 8. Drupal Admin bulk publishes nodes and facility.
- [x] 9. Drupal Admin edit facility node and remove `New facility` flag and save node.
- [x] 10. Let Help desk know this has been done, if not done by Help desk.

#### CMS Help desk (wrap up)
- [x] 11. Notify editor and any other stakeholders.

**Comment by stefaniefgray** [comment]
URL change ticket: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16356

**Comment by TroyCMSSupport** [comment]
@omahane @ian-sears  -- FYI the editor for this facility has manually published this page -- should it be set back to Draft?
I have reviewed the content -appears to be updated appropriately.

**Comment by TroyCMSSupport** [comment]
@omahane ready for redirect I believe --

**Comment by TroyCMSSupport** [comment]
@omahane @ian-sears - Page has been updated by editor to include Hours and Health services.

**Comment by ian-sears** [comment]
@omahane @TroyCMSSupport @jilladams Yes. The Awaiting Editor tasks (reason for the Flag) were completed by the Editor. This facility is now prepared for the Canonical redirect to take place in #16356

**Comment by omahane** [comment]
@jilladams @Agile6MSkinner Based on our Flagged Facilities touchpoint meeting, I'd this this blocked. We don't don't know how to proceed given that this not a clinic of its own but more like services in a Naval hospital.

@ian-sears @TroyCMSSupport Could you update this ticket with your complete knowledge?

**Comment by ian-sears** [comment]
Yes. I cannot locate the comment (or was it verbal in a meeting?) that I think Michelle Middaugh was going to ask in an upcoming RCS meeting about this facility.
So far as we (CMS Help Desk) understand it, this is not really a facility, per se, so much as a location for Scheduled Surgeries Only. When this was brought up it is myu recollection that Michelle reacted with the above.
I've reached out to Michelle to ask if I have overlooked any resultant comment from that so we could get this moved forward.

**Comment by jilladams** [comment]
Slack with Michelle: https://dsva.slack.com/archives/C02730UEZPS/p1721165967429809 She said:
> I  just emailed Justin to see if he has had an opportunity to follow up. Please stand by

**Comment by ian-sears** [comment]
UPDATE: 8/16/2024 @7:30pm
CMS HD reached out again to VHADigitalMedia for result of their conversation wihth the Editor. (in [VAHELP-6710](https://va-gov.atlassian.net/browse/VAHELP-6710))
We conversed with @mmiddaugh and confirmed that the ball is in the court of VHADigitalMedia.
Reminder that the issue with this facility, is that it turns out to be designed for scheduled surguries only and it is on a Naval Base, so special circumstances apply when it comes to the public-facing info and availability.
Awaiting reply from VHADigitalMedia.

**Comment by ian-sears** [comment]
#16356 is moving forward with a Cononical URL request to activate this facility.

**Comment by ian-sears** [comment]
UPDATE: 8/19 Monday @omahane
And for CLARITY: this is NOT "[Pensacola VA Clinic](https://www.va.gov/gulf-coast-health-care/locations/pensacola-va-clinic/)" vha_520BZ.
This is "[Naval Hospital Pensacola VA Clinic](https://prod.cms.va.gov/gulf-coast-health-care/locations/naval-hospital-pensacola-va-clinic)" vha_520QC.
"Naval Hospital Pensacola VA Clinic" is a facility that only does scheduled surguries, and is on the Navy base itself.
https://www.va.gov/find-locations/facility/vha_520QC is now in the system. However nothing in in the CSV (yet).
Published the node, set it to Awaiting CSV. So, need the Canonical:

**Comment by jilladams** [comment]
VHA DM had an update yesterday on this facility. It can / should add an operating status like Helpdesk added here: https://www.va.gov/find-locations/facility/vha_671QC to reflect the accurate status in the Facility Locator, even if the facility gets archived (if not removed from VAST). Editor can decide whether to Publish or Archive the page itself.

Either way: Should use “limited service and hours” Operating status: https://prod.cms.va.gov/node/63424/edit

**Comment by ian-sears** [comment]
@jilladams Understood, and agree. CMS Help Desk will reach out to the Editor that expressed hesitation to make this facility "live" and discoverable by the public. Simply, we will show the example of Christus and ask them to craft and supply the language for their node's Operating Status.
Thank you for illuminating that.
@TroyCMSSupport fysa

**Comment by ian-sears** [comment]
Editor has been notified and the site is live.
