### ISSUE TITLE
URL Change for: Naval Hospital Pensacola VA Clinic

### ISSUE THREAD

**Issue by stefaniefgray** [department-of-veterans-affairs/va.gov-cms#16356]
⚠️  NO URL RE-DIRECT NEEDED ⚠️ 

Simply needs to be updated within Lighthouse CSV / canonical URL change

-----

### Implementation date
When does this request need to be live:
Once main new facility ticket is completed: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16355

### Instructions for canonical URL change
- [x] Verify that the new URL for the facility is published and accessible on VA.gov.
- [x] Update the [CSV in Lighthouse](https://github.com/department-of-veterans-affairs/lighthouse-facilities/blob/master/facilities/src/main/resources/websites.csv) with the changed URL, maintaining the sorted order of the Facility API IDs.
- [x] Create a PR in the [lighthouse-facilities repo](https://github.com/department-of-veterans-affairs/lighthouse-facilities), tagging the Lighthouse team.
- [x] Post a message in the #cms-lighthouse channel in Slack, with an @mention to a Lighthouse team member.
- [x] Add the "Awaiting CSV" flag to the facility node with a revision log message that includes a link to this ticket.
- [x] Validate that the change has deployed by checking that the Facility Locator has been updated with the new url.
- [x] Update this ticket with a comment that the CSV change has been deployed.
- [x] Remove the "Awaiting CSV" flag to the facility node with a revision log message that includes a link to this ticket.

#### URL change example (update with actual ID and URL)
| Facility API ID  |  Full VA.gov URL |
| ---  |  --- |
| vha_520QC | https://www.va.gov/gulf-coast-health-care/locations/naval-hospital-pensacola-va-clinic |

**Comment by TroyCMSSupport** [comment]
@omahane @ian-sears - awaiting feedback on #16355  before proceeding here.

**Comment by jilladams** [comment]
@TroyCMSSupport can you clarify re: the feed back we are waiting for? Not sure if the editor update on #16355 was it, or if we're waiting on anything else.

**Comment by ian-sears** [comment]
@jilladams @TroyCMSSupport @omahane Yes. The feedback we were waiting for (from the Editor) is now complete and this Canonical URL change can now continue and be completed. THe page is still in DRAFT mode.

**Comment by jilladams** [comment]
Blocked by newer notes in https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16355, that we need complete info from Helpdesk for this one. Moving to Github lane for "needs helpdesk input"

**Comment by ian-sears** [comment]
I updated #16355 with our most recent information from the CMS Help Desk.

**Comment by ian-sears** [comment]
UPDATE: 8/19 Monday @omahane 
And for CLARITY: this is **_NOT_** "[Pensacola VA Clinic](https://www.va.gov/gulf-coast-health-care/locations/pensacola-va-clinic/)" vha_520BZ. 
This is "[Naval Hospital Pensacola VA Clinic](https://prod.cms.va.gov/gulf-coast-health-care/locations/naval-hospital-pensacola-va-clinic)" vha_520QC.
"Naval Hospital Pensacola VA Clinic" is a facility that only does scheduled surguries, and is on the Navy base itself.
https://www.va.gov/find-locations/facility/vha_520QC is now in the system. However nothing in in the CSV (yet).
Published the node, set it to Awaiting CSV. So, need the Canonical:
#### Canonical needed
| Facility API ID  |  Full VA.gov URL |
| ---  |  --- |
| vha_520QC | https://www.va.gov/gulf-coast-health-care/locations/naval-hospital-pensacola-va-clinic |

@TroyCMSSupport fysa

**Comment by ian-sears** [comment]
The URL addition request has been made:
https://dsva.slack.com/archives/C02BTJTDFTN/p1724078308240949

**Comment by ian-sears** [comment]
CSV has been deployed
