### ISSUE TITLE
FE: Update CLP hero image to use new image derivative

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#16361]
#16242 will create a new image derivative that enforces a 500x500 min. 

Once it's created, FE CLP content-build template should be updated to use that derivative instead of `crop_square`. 

## Acceptance criteria

- [x] Review existing CLPs ([sheet](https://docs.google.com/spreadsheets/d/1Vw1Ken60Zjz-3BLexbHBITcHUh7dzbr5K10IwbTJicQ/edit#gid=0)) in a Tugboat to verify how FE image treatments look pre-merge
  - [ ] If manual updates will need to be made, flag for DM / PM
- [x] CLP hero images use new Drupal image derivative, machine name: `1_1_square_large`

**Comment by randimays** [comment]
All CLPs have been validated successfully in prod. Closing!
