### ISSUE TITLE
"Enable in menu" option is always checked after node save

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#1636]
## Description

<img width="568" alt="Screen Shot 2020-04-28 at 1 37 11 PM" src="https://user-images.githubusercontent.com/16477724/80530352-1d4d0100-8956-11ea-9ec0-c88ba76caaf0.png">

### To reproduce

- edit any node that allows customization of menu link. E.g. Story, VAMC facility, Office, etc
- check the checkbox "Provide a menu link" in "Menu settings"; uncheck "Enable in menu"; Save the node
- once node is saved, "Enable in menu" checkbox should be unchecked, but appears check within the form

NOTE: there may be other issues w/ disable_node_link_menu config - functionality needs review.

## Acceptance Criteria
* "Menu Settings > Enable in menu" checkbox behaves as expected

**Comment by cmaeng** [comment]
Just noticing this as done. Will include in sprint 19 for reporting purposes.
