### ISSUE TITLE
FL is missing Community care substance abuse rehab facility 

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-cms#16368]
## Describe the defect
A report of a missing Community care substance abuse rehab facility came through SNOW on 12/7/2023. 

## To Reproduce
1. Go to [Facility Locator](https://www.va.gov/find-locations/?page=1&address=costa%20mesa&facilityType=provider&serviceType=324500000X&latitude=33.663339&longitude=-117.903317&radius=10&bounds%5B%5D=-118.653317&bounds%5B%5D=32.913339&bounds%5B%5D=-117.153317&bounds%5B%5D=34.413339&context=Costa%20Mesa%2C%20California%2C%20United%20States)
2. Enter "Costa Mesa",  select "Community providers" and "Substance Abuse Rehabilitation Facility" as search parameters
3. View search results
4. See error - South Coast Counseling does not appear in the list of search results

## AC / Expected behavior
- [ ] South Coast Counseling, 693 Plumer St, Costa Mesa, CA is active within PPMS and is expected to be returned as a search result for Substance Abuse Rehabilitation Facility searches. 

- [ ] Please inform Michelle when this has been resolved so that I can follow up with the PPMS Project team and the individual who reported the issue. 

## Additional context
I varied my search in a number of ways but none South Coast Counseling 
- zoomed the map out to use a wider search result radius
- entered other substance abuse related specialties (and in combination with a wider search result)
- looked for individual providers with the same address 

<details>
<summary> the following information was provided by the PPMS Project team to support troubleshooting </summary>

<img width="1722" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeXhOQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--dc159af9e3086ecd1ada9a704c8cdd6cdb6548aa/image.png" alt="image.png" />

</details>

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Defect")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS workstream (orange) (not needed for bug tickets)
- [ ] CMS-supported product (black)

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [ ] `Public Websites`
- [x] `Facilities`
- [ ] `User support`
- [ ] `Accelerated Publishing`

**Comment by xiongjaneg** [comment]
Michelle confirmed they are active and they provide the listed service.

**Comment by mmiddaugh** [comment]
Closing this as the provider is available in Facility Locator but may not be immediately returned in list due to separate defect which will be addressed by fix identified in Spike: Facility Locator search results for PPMS don't update when search area is zoomed out [#17418](https://app.zenhub.com/workspaces/sitewide-facilities-639f5253e4b702a32376339e/issues/gh/department-of-veterans-affairs/va.gov-cms/17418)
<img width="828" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM2I5QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--57919b2c03c7331b936c1cd18f18449694a3b020/image.png" alt="image.png" />
