### ISSUE TITLE
Police: MMVP Launch Plan

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#16370]
Launch plan for our Dec 2023 rollout of the VAMC Police transparency MMMVP. 

## Questions
* Drupal: any integration branches / PRs to be refreshed & merged? Or everything is merged already?
  * Will already be in prod, no launch activity required.
* FE: Any tricky things to manage when merging? Nodes are in draft: do we need to be concerned about what will show on the FE? 
  * Merging in when no content is published will not show the menu or the pages. If a page is published, then on the daily content-build release the page and side nav will be pulled in and generated. Bottom line: FE can merge, with no impact until content is published.
* Drupal: WIll publishing the nodes resolve the missing menu item, or do we need an explicit launch step for that?  
  * When node is published,  content-release must run to build pages that have been published.
* Change management: #16023

## Prerequisites / blockers
- [x] Drupal changes merge to main / deploy
  - [x] Including #16411 for Title metatag fix
- [x] FE code is merge to main / deploy
   - [x] including GraphQL queries and FE template
- [x] Drupal content entry is complete in Centralized Content. (Content has already been CAIA provided and reviewed.)

## Launch Order of operations
(Assumes that code reviews, design reviews, a11y reviews were completed on separate engineering tickets, and that code is prod-ready.)
- [x] [All VAMC System VA Police page nodes](https://prod.cms.va.gov/admin/content?title=&type=vamc_system_va_police&moderation_state=All&owner=All) are bulk updated from Draft to 
   - [x] Confirm content-release is successful (ETA from 5mins-1.5hrs depending on where content-release cycle is at the point we publish)
- [x] Complete open Change Management items from #16023 

## Follow up tasks

- [x] @jilladams Use final state of this ticket when ready to generate launch plan tickets for VBA and Police reg MVP

**Comment by eselkin** [comment]
For FE: content-build only builds pages when the pages are published. Even if the Centralized Content is published it doesn't pull any of that in. The only way it can generate a page is if the VA Police page is published. It also won't create empty sidenav menu items.

This is the frontend with the ability to show police pages and 1 page published (e.g. accidental publishing of Tampa health care), but showing another health care page
https://web-w1a5evfuonymjntciz3pduj1ofhepwky.demo.cms.va.gov/palo-alto-health-care/
There is no VA Police page or side nav.

This is the frontend when pages are published and you are on a system page, the VA Police menu is there. https://web-cacdjnoiw2wnudzzof7nprvbfwb2tyde.demo.cms.va.gov/palo-alto-health-care/

So, merging in when no content is published will not show the menu or the pages. If a page is published, then on the daily content-build release the page will be pulled in and generated.

**Comment by mmiddaugh** [comment]
Additional launch tasks (if not for MMVP, then for MVP)
- KB article published and link sent to VHA DM
- Test coverage meets expected levels
- Foundational A11y testing complete and documented

**Comment by jilladams** [comment]
@mmiddaugh 2/3 of those will be required for Staging review - I think we should be tracking them for MVP not MMVP, but @xiongjaneg lemme know if I'm wrong.

**Comment by xiongjaneg** [comment]
1. is for both MMVP and MVP (same link but will be updated for MVP to reflect that facility level data is available) and tracked in change management ticket
2 and 3 are for MVP

**Comment by jilladams** [comment]
From scrum: Green light to merge FE code.

**Comment by jilladams** [comment]
Eli to rebuild Tugboat, share FE link to channel for preview before we merge.

**Comment by jilladams** [comment]
- After content-build is successful, we're ready to publish: likely today.
- Editors have been notified this is coming, per Jane.
- Helpdesk: will be notified when VHA DM is as a heads up before publish.
- For bulk publish: [VA Police pages](https://prod.cms.va.gov/admin/content/bulk?title=&type=vamc_system_va_police&moderation_state=All&taxonomy_entity_index_tid_depth=All)  - @swirtSJW to own publish after content-build success.
- Backup plan for rollback: unpublish the content to Draft to revert. 

These pages are not on Restricted Archive workflow, and likely should be: this will prevent Editors from archiving or unarchiving these pages. 
* Risk is: in the time between publish and move to Restricted Archive workflow, Editors could archive. That's known / accepted risk that is already prevalent in the system.
* @xiongjaneg we need a ticket for this change.

Note: There are a handful of systems that built their own VA Police pages, and they will be asked to archive those. That's expected.

**Comment by jilladams** [comment]
Launch thread: https://dsva.slack.com/archives/C0FQSS30V/p1703105241836059
