### ISSUE TITLE
Drupal users with View access should not be able to Edit the moderation state of a Taxonomy term 

### ISSUE THREAD

**Issue by davidmpickett** [department-of-veterans-affairs/va.gov-cms#16378]
## Describe the defect
When a Taxonomy term is in any state other than Published, a Moderation State widget shows up on Node View, allowing them to change the moderation state, even though they don't have normally have access to Node Edit. 

It is unlikely that most users would stumble upon this, but as follow up to #15748 we will be sending direct links to unpublished Taxonomy terms to VBA stakeholders, so it would be good to resolve this.

This can be resolved by an admin dragging Moderation Control down to Disabled on [Display config](https://prod.cms.va.gov/admin/structure/taxonomy/manage/health_care_service_taxonomy/overview/display).

![Screenshot 2023-12-11 183531](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/60eb018f-92ff-415c-a869-b6db500e828d)

See #15695 for a more holistic approach to governance of Taxonomy Terms.

## To Reproduce
1. Go to https://staging.cms.va.gov/
2. Log in as tanekwa.bournes@va.gov
3. Go to https://staging.cms.va.gov/health-care/life-insurance

## AC / Expected behavior
- [x] The Moderation Control widget does not show up on Node View for VA Service Taxonomy terms

## Screenshots

![Screenshot 2023-12-11 182349](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/3c733451-f10c-48c1-8fc1-264bdcc8f22b)

![Screenshot 2023-12-11 182336](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/8f3420a2-c1f4-4be1-ba1d-f3c4ebe63836)

**Comment by davidmpickett** [comment]
Merged, pending prod verification

**Comment by xiongjaneg** [comment]
Confirmed in staging the Moderation Control widget does not show up for this user
<img width="531" alt="Screenshot 2023-12-14 at 3 00 34 PM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/73648238/0a773885-52e2-47a0-aa4a-848336b7b577">
 on Node View for VA Service Taxonomy terms
