### ISSUE TITLE
[Search] Sitemap should correctly indicate the last modified date of content

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#16380]
## Status
[2024-04-23] Dave Conlon and Erika Washburn have asked that the PW team prioritize this item.

## Requirements

A page's entry in the sitemap should indicate its last-modified date, so that crawlers can identify updated content and index it.

- [ ] Timebox the discovery effort
- [ ] Create additional tickets as needed

- The AC may below may need to move to additional tickets:
- 
```
[tasklist]
### Acceptance criteria

- [ ] Sitemap draws the `lastmod` value from `field_last_saved_by_an_editor` if it is available on the content
- [ ] Sitemap draws the `lastmod` value from the `changed` property if `field_last_saved_by_an_editor` is not available
- [ ] `lastmod` is formatted in a W3C-compliant datetime format
- [ ] `changefreq` and `priority` are removed
```

## Background & implementation details

W3C compliant datetime formats: https://www.w3.org/TR/NOTE-datetime

General information about Sitemap structure: https://www.sitemaps.org/protocol.html

Search.gov sitemap.xml expectations: https://search.gov/indexing/sitemaps.html

```[tasklist]
### Implementation tasks
- [ ] Use this if it helps you or feel free to delete.
```

**Comment by tjheffner** [comment]
https://www.npmjs.com/package/next-sitemap#server-side-index-sitemaps-getserversidesitemapindex may be what we need to do for dynamic lastmod

**Comment by timcosgrove** [comment]
This is not a requirement for AP go-to-production launch.
