### ISSUE TITLE
Event pages follow-up tasks

### ISSUE THREAD

**Issue by tjheffner** [department-of-veterans-affairs/va.gov-cms#16399]
## Requirements
Events are now rendered by next-build! 🎉 

Some minor follow-up tasks to ensure functional parity to va.gov

```[tasklist]
### Acceptance criteria
- [ ] Event breadcrumbs match va.gov's (Home breadcrumb should be visible on event)
- [ ] Field types for Events are reviewed, made DRY if possible. Check `drupal/paragraph.ts` and `drupal/field_type.ts`
- [ ] Incorporate recent changes to the Event type to better handle mailto: links
- [ ] Recurring: "show all times" functionality limits to 5 initially, shows all if expanded
- [ ] Recurring: "When" should always show the next recurring date relative to the user's machine, regardless of when the page was built
- [ ] Recurring: If all dates are in the past, show the last event in the series
```

## Background & implementation details
Please see this PR for the changes for mailto: links: https://github.com/department-of-veterans-affairs/content-build/pull/1831/files

Event example: https://www.va.gov/loma-linda-health-care/events/63502/
Recurring event example: https://www.va.gov/central-iowa-health-care/events/52265/

![Screenshot 2023-12-12 at 2 23 22 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/11279744/2cec57c6-3cdd-4ed9-8552-e2fe0c6f4d0f)

There appears to be some spacing differences at the bottom of events compared to va.gov, but I think next-build's breathes better. Don't need to update that.

Re: recurring events:
When we move to Next and ISR in particular, it will not be guaranteed that an event page is published when an upcoming occurrence of the event moves into the past. We will need to write all dates to page as JSON data and then render the next date - 'When' - from JSON, taking the user's local time into account.

'View all dates' will also need to use this data. For the time being, do not make any changes to the ordering.

**Comment by timcosgrove** [comment]
Closing https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16473 in favor of this.

**Comment by tjheffner** [comment]
Completed here: https://github.com/department-of-veterans-affairs/next-build/pull/307
