### ISSUE TITLE
Header VCL Button Analytics

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#16397]
## Status
**[03-11-2024]** The refresh of the Federal Header/Footer is blocked by OFCIO's decision to expand research to platforms other than VA.gov. We'll resurrect this after implementation and release of the refreshed header/footer (TBD timing).

## Description
We want to track analytics for the VCL button in the header to help us determine if moving this down in the tab order has poorly impacted user experience and their ability to find and access the Veterans Crisis line.

We will want to establish baseline stats that can be compared to post-launch stats to help track this.

### Additional Context
This has been discussed during the development phase and also came up as both accessibility and IA feedback during [Midpoint review for Header/Footer](https://github.com/department-of-veterans-affairs/va.gov-team/issues/69826)

### Analytics
- [x] August 2023 Baseline
  - Total Events: 36,335 
  - Unique Events: 32,995

## Acceptance Criteria
- [ ] Testable_Outcome_X
- [ ] Testable_Outcome_Y
- [ ] Testable_Outcome_Z
- [ ] Requires design review
- [ ] Requires accessibility review

## Team
Please check the team(s) that will do this work.

- [ ] CMS Team
- [ ] Public Websites
- [ ] Facilities
- [ ] Accelerated Publishing

**Comment by laflannery** [comment]
@FranECross I spoke with @aklausmeier and we wanted to make sure that we had a tracking ticket for the VCL button analytics. She also thought you might already have the baseline stats so we might be done with that portion?

**Comment by FranECross** [comment]
@laflannery @aklausmeier thanks for creating the ticket! I do have baseline stats and added an Analytics section with the info to the body of this ticket. Thank you!

**Comment by FranECross** [comment]
Compare year over year.  @FranECross ensure stats are entered into brief.
@FranECross Add to prod sync to read over header/footer initiative/brief to review KPI section to fill it out and audit the product page.

**Comment by FranECross** [comment]
Per Dave Conlon, the Federal Header/Footer improvement effort has been closed by the Whitehouse / 18f. All related tickets may be closed.
