### ISSUE TITLE
PW intake: <Adding Spanish toggle to community care page> from <Sitewide Content, Accessibility, and IA>

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-cms#16392]
### Describe your request

We need to add the Spanish toggle to the top of this page: https://www.va.gov/family-member-benefits/comprehensive-assistance-for-family-caregivers-esp/
Note that there's no left nav info on the English page, so none is needed on the Spanish page.

### Time constraints / launch deadlines

This page has been live for a while but we were waiting on QA. We'd love to get this toggle added quickly so that we can let our Community Care partners know it's live, as it's been a priority for a while. I know you are working on toggles for other pages of ours. If need be, you can move this one ahead of those.

### Your product/team Slack channel

Sitewide CAIA

### Your OCTODE product owner

Randi Hecht

## ACs

- [x] Translation toggles appear on https://www.va.gov/family-member-benefits/comprehensive-assistance-for-family-caregivers-esp/ with Spanish highlighted
- [x] Translation toggles appear on https://www.va.gov/family-member-benefits/comprehensive-assistance-for-family-caregivers/ with English highlighted
- [x] The breadcrumb current page segment is translated
- [x] The title tags are translated
- [ ] Pages are linked to/referenced in the language resource page (spanish)
- [ ] Requires CAIA review in a Preview Instance before merge

**Comment by jilladams** [comment]
@RLHecht toggles now appear on these 2 pages in production: 
https://www.va.gov/family-member-benefits/comprehensive-assistance-for-family-caregivers/
https://www.va.gov/family-member-benefits/comprehensive-assistance-for-family-caregivers-esp/

Closing, but please reopen if you find anything remaining that needs updated.

**Comment by RLHecht** [comment]
Amazing, thank you @jilladams !
