### ISSUE TITLE
Non-admin editors are seeing breadcrumbs where the do not belong on VAMC system

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#16396]
## Describe the defect
Login as a non-admin editor for a VAMC system and try to edit the system page

You will see breadcrumbs where there should not be breadcrumbs.
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5752113/244b29e0-62a9-41cc-8ec1-d5bc9f2075f1)

This is likely related to changes made to default breadcrumbs and applying them to an external content view mode.

## To Reproduce
1. Login as a VAMC editor (Kaila.Bird)
2. Edit your system /node/14989/edit
3. Scroll down to 'VA Health Connect and Health Records System'
4. See the breadcrumbs where there should be none.

## AC / Expected behavior
- [x] External content view for systems does not show breadcrumbs.

## Additional context
Add any other context about the problem here. Reach out to the Product Managers to determine if it should be escalated as critical (prevents users from accomplishing their work with no known workaround and needs to be addressed within 2 business days).

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Defect")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS workstream (orange) (not needed for bug tickets)
- [ ] CMS-supported product (black)

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [ ] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`
- [ ] `Accelerated Publishing`

**Comment by swirtSJW** [comment]
This needs a config export of external_content view mode on VAMC system pages.   It is a remnant from AP team adding Default breadcrumbs.   It should not have been applied to this view mode.

**Comment by swirtSJW** [comment]
This was injected because it was impeding QA of #16360 but I wanted a separate ticket to track it rather than lumping it in with 16360

**Comment by xiongjaneg** [comment]
Confirmed breadcrumbs are not showing
<img width="489" alt="Screenshot 2023-12-14 at 3 03 22 PM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/73648238/82768762-c196-42ff-945d-beba62746e71">
