### ISSUE TITLE
PW intake: <Add Spanish toggle and set up left nav> from <Sitewide CAIA>

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-cms#16393]
### Indicate if you need front-end engineering support for

- [ ] Content audit
- [ ] Implementation of REACT sign-in widgets
- [ ] Support for UAT testing or phased roll out of app/tool landing page
- [ ] Implementation of Translation widgets
- [X] Something else

### Describe your request

We've published 2 pages in Spanish that we need to set up the left nav for and add the Spanish toggle at the top of the page. 

These pages are:

- Needs left nav and toggles: https://www.va.gov/decision-reviews/supplemental-claim-esp/
- Needs toggles only: https://www.va.gov/report-harassment-esp/

### Time constraints / launch deadlines

- no hard timing

### Your product/team Slack channel

- Sitewide CAIA

### Your OCTODE product owner

- Randi Hecht

### Notify Sitewide Public Websites of this issue, and tag @Fran Cross & @jilladams.

- [X] I acknowledge that I must notify `#sitewide-public-websites` in Slack after submitting this issue.

### Acceptance Criteria
- [ ] Add menu links to drupal (doesn't need engineer to do this; @FranECross check with Jill)
@FranECross turn this into an FE ticket
- [ ] Left nav displays in Spanish for the -esp pages noted above
- [ ] Front end ticket is created for:
  - [ ] Breadcrumb for the particular pages displays in Spanish
  - [ ] Toggles for English | Español display toward the top of the pages

**Comment by FranECross** [comment]
@FranECross Ensure there is a corresponding Drupal ticket.

**Comment by jilladams** [comment]
For end of sprint, noting: pulled in as stretch, a couple tests failing in the PR. I've updated branch to see if that/new run shake it loose. Moved to Review/QA pre-merge.

**Comment by randimays** [comment]
Update: PR for the English/Spanish toggles has been merged and will deploy to prod today. The missing left nav items are in progress on a Tugboat. Hoping those will finish today as well.

**Comment by randimays** [comment]
@FranECross @jilladams The menu data has been added into a Tugboat. Could you please sanity check these for me, then I can add the menu data into production?

[`/decision-reviews/supplemental-claim/`](https://web-kfm1m8xswxqqahdjzyhrrdblbwlsju40.demo.cms.va.gov/decision-reviews/supplemental-claim/)
[`/decision-reviews/supplemental-claim-esp/`](https://web-kfm1m8xswxqqahdjzyhrrdblbwlsju40.demo.cms.va.gov/decision-reviews/supplemental-claim-esp/)

**Comment by FranECross** [comment]
@randimays I'll be happy to! I'll take a look at it after sprint planning. Thanks!

**Comment by jilladams** [comment]
(took a quick look while working on sprint report, ✅ , and new toggles / no sidebar page looks good too)
![Screenshot 2024-01-03 at 12 57 57 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/85581471/b1564f0d-2387-46cf-afb1-082ce26aa2b8)
![Screenshot 2024-01-03 at 12 57 48 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/85581471/638e7781-7737-450d-8330-0c0c3d21bea9)

**Comment by randimays** [comment]
Thanks @jilladams, I'll get the menu data added to prod!

**Comment by FranECross** [comment]
Looks great, @randimays !! 🎉

**Comment by randimays** [comment]
Everything is confirmed in production. Closing!

## /report-harassment (toggles only)
<img width="1431" alt="Screenshot 2024-01-03 at 5 07 12 PM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/19175324/664011de-dfe3-4989-b6e8-d0f3116556d1">
<img width="1433" alt="Screenshot 2024-01-03 at 5 07 01 PM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/19175324/b40614d4-537a-4700-89b8-d40a493f23ae">
<br/>
<br/>
<br/>
<br/>

## /decision-reviews/supplemental-claim (toggles & sidebar)
<img width="1430" alt="Screenshot 2024-01-03 at 5 06 50 PM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/19175324/268294a0-0a64-4ddb-806f-e0c0038fbe91">
<img width="1432" alt="Screenshot 2024-01-03 at 5 06 40 PM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/19175324/bae61cda-8799-41f4-a4f6-00314a5a1607">
