### ISSUE TITLE
Set up VA Police metatags

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#16411]
## User Story or Problem Statement
As part of node setup, we need to setup patterns for the VA Police content type.

## Acceptance Criteria
- [x] Add default metatag for VA police content type (/admin/config/search/metatag)
   - [x] Meta title of "{Node title} | {VAMC System Name} | Veterans Affairs" is set up for VA police page
   - [x] Meta description of "field-cc?" is set up for VA police page

## Team
Please check the team(s) that will do this work.

- [ ] CMS Team
- [ ] Public Websites
- [x] Facilities
- [ ] Accelerated Publishing

**Comment by swirtSJW** [comment]
This is a 1 to set up once the pattern is determined for the description.

**Comment by xiongjaneg** [comment]
Need text for the description. Need title and existing description model for MMVP.

From Dave: "Meta descriptions are weird." CAIA provided some text for this. There is a ticket for wider CAIA input on meta tags and descriptions.

**Comment by swirtSJW** [comment]
This should be all set.  It should land on prod today.

**Comment by jilladams** [comment]
Validated in prod, closing: view-source:https://prod.cms.va.gov/tampa-health-care/va-police
![Screenshot 2023-12-20 at 9 37 27 AM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/85581471/9a78e417-2b9e-4f2e-9bf3-141f70cf0e07)
