### ISSUE TITLE
Back to top component for Police MVP

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#16414]
## Description or Additional Context 
Back to top component guidance according to the Usage:
In pages with static content that is more than two screens in length on large and medium screens, or more than four screens in length on small screens.

For the MMVP, the police page is two screens and doesn't fall under this guidance, so the component wasn't added.

For MVP, after police activity is added, the page length and applicability of this guidance will need to be reviewed and updated, if needed.

## Acceptance Criteria
- [x] MVP has back to top component.
- [x] Requires design review
- [x] Requires accessibility review

**Comment by mmiddaugh** [comment]
Related: #13879 Evaluate "Back to top" component for VAMC pages

**Comment by mmiddaugh** [comment]
Note: [this component](https://design.va.gov/components/back-to-top)is not yet flagged as USWDS V3 ready

**Comment by jilladams** [comment]
design / a11y signed off in PR  just needs prod deploy and verification Monday.

**Comment by jilladams** [comment]
Deployed to prod, but no prod content available to verify. Closing.
