### ISSUE TITLE
Homepage blocks: Homepage manager user cannot access blocks menu

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#16418]
## Description 
In https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11160, we created a Homepage Manager user role with permissions to modify the Homepage news spotlight and Homepage benefits block types. 

Today, logged in as Dave Conlon (a homepage manager), I do not have access to the custom block library or to edit blocks. 

KB articles provide instructions for how this functionality previously worked / should work: 
- [How to update the News Spotlight on the VA.gov homepage](https://prod.cms.va.gov/help/vagov-homepage-product-guide/how-to-edit-the-homepage-news-spotlight)
- [How to edit the Beneficiary-facing homepage promo](https://prod.cms.va.gov/help/vagov-homepage-product-guide/how-to-edit-the-vagov-homepage-beneficiary-facing-promo)
- [How to turn on or off the Beneficiary-facing homepage promo](https://prod.cms.va.gov/help/vagov-homepage-product-guide/how-to-edit-the-vagov-homepage-beneficiary-facing-promo/how-to-turn-off-and-on-the-beneficiary-facing-homepage)

## Additional context
With the D10 upgrade, the custom blocks library moved from /admin/structure/block to /admin/content/block (though menu items are still under Structure). Not sure what other Block related things may have changed.

## To repro
* Visit staging or a recently-built Tugboat
* Login as any [Homepage Manager](https://prod.cms.va.gov/admin/people?user=&status=1&role=homepage_manager&workbench_access_section__section=All)
* Per instructions on https://prod.cms.va.gov/help/vagov-homepage-product-guide/how-to-edit-the-vagov-homepage-beneficiary-facing-promo, How to Edit, Step 1: click https://prod.cms.va.gov/admin/content/block?info=&type=benefit_promo
* Get access denied

## Acceptance Criteria
- [ ] Homepage Manager users are able to follow KB instructions to modify Homepage News Spotlight and homepage Benefit Promo custom blocks
- [ ] Determine and share: How did regression happen?

**Comment by FranECross** [comment]
Okay to wait until Sprint 100; acknowledging that this may not ship until after the code freeze.

**Comment by jilladams** [comment]
Verified: Logged into staging as Josh Tuscher (Homepage manager), I can now access / modify Homepage promo blocks for news & benefits. FYI @davidconlon : you're clear for OPIA homepage next steps.
