### ISSUE TITLE
Determine content model for displaying VA Police contact information per facility when there are multiple numbers per system

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#16415]
## User Story or Problem Statement
In #16335 for VA Police MMVP, only one number will be displayed on the VAMC system VA Police page. This will be the number of the first facility listed on each system's web page.

Ten systems were identified that had more than one contact number per system, usually varying across two or three facilities. For MVP, when a VAMC system has more than one contact number (because of different numbers for different facilities), we want to display those multiple contact numbers.

## Acceptance Criteria
- [x] Options for content model are documented
- [x] Options are reviewed with engineering (may be included in UX Sync)
- [x] Options are reviewed with product (may be included in UX Sync)
- [x] Subsequent ticket is stubbed or PM is tagged to stub ticket

**Comment by mmiddaugh** [comment]
@davidmpickett VHA Law Enforcement Services are interested in moving toward CMS as source of truth for contact information if it makes sense to make these fields editable sooner than later

**Comment by davidmpickett** [comment]
This will carry into Sprint 101, but I did start work on this in Mural: https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1698092447003/c969debf289d4e43e3cdd293d90053c2c137c338?wid=0-1704220930063

**Comment by davidmpickett** [comment]
@mmiddaugh @xiongjaneg 
For scoping my work on this, do you want me to just look at moving from 1 phone number per system -> 1 phone number per facility? Or should I also account for the future state of having potentially multiple types of phone numbers at each level? 

For instance, [the CSV we received](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16335#issuecomment-1843532867) had a whole column for phone numbers for Police Chiefs in addition to the Ops Phone Number column we migrated into Drupal (there was also a column for Fax numbers)

**Comment by davidmpickett** [comment]
Will need to kick the tires on this a bit with @swirtSJW and @aklausmeier before doing a full write-up of pros and cons, but here's a first draft:

- [Current state](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1698092447003/c969debf289d4e43e3cdd293d90053c2c137c338?wid=0-1704231099551&outline=open)
- [Option 1 - VAMC Facility](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1698092447003/c969debf289d4e43e3cdd293d90053c2c137c338?wid=0-1704231159721&outline=open)
- [Option 2 - Non-clinical facility service](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1698092447003/c969debf289d4e43e3cdd293d90053c2c137c338?wid=0-1704231195878&outline=open)
- [Option 3 - Increase cardinality](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1698092447003/c969debf289d4e43e3cdd293d90053c2c137c338?wid=0-1704231245692&outline=open)

**Comment by mmiddaugh** [comment]
> For scoping my work on this, do you want me to just look at moving from 1 phone number per system -> 1 phone number per facility? Or should I also account for the future state of having potentially multiple types of phone numbers at each level?

I'd suggest accounting for the future state - even if we break it into now and later pieces.  This might include
- more than one phone number at a system/facility level (I'm not sure about including Police Chief numbers but I recall the VA Police stakeholders mentioning there might be local/facility level emergency contact numbers and can foresee the option of displaying both a system level number and a facility level number.)
- option for PAOs to add/edit existing

**Comment by swirtSJW** [comment]
The lift of option 1 and option 2 are nearly the same, so for the same lift I like the power / benefit / existing pattern of option 2.

Option 3 is an easy lift but flawed by the likely potential of disconnected data.  (not being able to associate the number with a facility)

**Comment by xiongjaneg** [comment]
@davidmpickett Got a use case for option 2 that come in through help desk: VA Greater Los Angeles has extra contact info in their [old police detail page](https://www.va.gov/greater-los-angeles-health-care/programs/va-police/) that they were concerned about not being able to put in the standard police page

**Comment by davidmpickett** [comment]
[Discussed in UX sync on 1/4/2024](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16586#issuecomment-1873487039)

- **Decided**: Needs to be at the facility level, we already anticipated editor involvement, so this points to Option 2, using the VAMC Facility Non-Clinical Service.
- Contact csv: we don't know if there are other consumers of that. Michelle to work on confirming.

I will work on stubbing out the subsequent tickets

**Comment by davidmpickett** [comment]
Subsequent ticket stubs: 
- #16810
- #16811
- #16812
- #16813
- #16814

This list may not be comprehensive, but it gives us a starting place
