### ISSUE TITLE
[Aging Content] Build Dependent Components for Expired FWB MVP

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-cms#16417]
## Background
Full-width banners in VA.gov become stale and aren’t monitored or updated on a regular cadence, allowing many of them to still display after a campaign or event has passed. In some cases, they are being used for month-long campaigns instead of their original intention - for informational alerts or warning alerts.

In order to provide timely information to Veterans and other users of VA.gov, and ensure banners are replaced and/or monitored, editors need to be notified via email of these stale banners.

## Description
Build the components (on top of the notification framework that was recently added leveraging the ECA and Message stacks) necessary to send expired FWB emails. These components include:

- View
- Queue (Advanced Queue)
- Job Type (Advanced Queue)
- Message Template
- Mail Handler
- Email template/theme hook
- Job Queue Action (ECA)
- ECA Model

### View
This is a View of expired FWB content. It should return only the expired FWBs which:

- are published
- have a _last saved by an editor_ field that is 7 days old.

This View will be used in an _Execute Views Query_ plugin implementation inside our ECA model.

### Queue (Advanced Queue)
This is an Advanced Queue for all aging content notification purposes. It should match the setup of the existing 6102 configuration [link]

### Job Type (Advanced Queue)
This Advanced Queue Job Type is responsible for sending email notifications for all aging content for VA.gov leveraging the Message stack. This queue will:

- Create and populate a new Message
- Expects Message values to exist in the Job payload
- Allows for optional arbitrary data from Job payload to be added to the Message (eg: populating Message fields)
- Allows for optional 'allowed recipients' in the payload which will prevent sending to anyone other than provided users.

### Message Template
A Message type specifically for expired FWB.

<details>
<summary>Message Subject:</summary>
Your Full-width banner has displayed for seven (7) days

</details>
<details>
<summary>Message Body:</summary>

Your Full-width banner has displayed for seven days. In order to meet the purpose of this type of content, please plan to archive, or edit to extend display of, your published Full-width banner titled [content title / link] by [date]. 

As a reminder, Full-width banners are to be used for emergencies or actions a veteran needs to take and should display for 7-days, unless there’s a compelling reason to extend display of the content.

If you do need to extend the display of the banner, simply edit with a comment to that effect, and the 7-day countdown window will reset.

________________________________________________________________________________________________________________________________

For more information, you can read this [Knowledge Base article](https://prod.cms.va.gov/help/vet-centers/vet-center-content-review) for tips and best practices to manage compliance.

Need help?
- If you are a Vet Center Director or Outreach Specialist who needs assistance accessing Drupal CMS, please email the CMS Support Team at support@va-gov.atlassian.net.
- If you want to refresh your skills, need ideas, or have questions about creating content for your webpages, you can find How to Guides and Training videos in the [Drupal CMS Knowledge Base](https://prod.cms.va.gov/help/vet-centers) or drop in during office hours.
- If you received this email and no longer have a role at a Vet Center, please inform us by emailing the CMS Support Team at support@va-gov.atlassian.net.

________________________________________________________________________________________________________________________________

**Coming Soon:**
- Banners will be permanently auto-archived at the end of Day 7, unless edited to reset the 7-day timeframe. We will give ample notice before this functionality is implemented.
- Notifications and auto-archiving of Home Page Benefit Promo Blocks
- Notifications and auto-archiving of Home Page News Spotlight Blocks

</details>

### Mail Handler
A mail handler for the Message is needed which is configured to send using the Mime Mail mail handler for the Message  Template.

### Email Template and Theming
To render emails as HTML and preserve the VA.gov style, a Twig template is needed. Additionally, and in order to hook the rendered Message content into the template, the Message Template needs a hook_theme override.

This was also done during the 6102 content notifications work, so that work can be extended to include the Message Template for FWB as well.

### Job Queue Action (ECA)
A generic "Create Job (Advanced Queue)" Action plugin. This plugin will allow creation any type of Advance Queue Job Type. It will optionally allow for queuing the Job to a specified AdvancedQueue queue, and allow for arbitrary payload data.

### ECA Model
This is the ECA (Event, Condition, Action) model that combines these components to orchestrate queuing and delivery of email. The model should not be enabled (equivalent of a disabled feature toggle) by default to avoid sending mail before testing can ensue.

## Acceptance Criteria
- [x] View
    - [x] Expired Results View exists and returns only published + expired FWB nodes 
- [x] Queue (Advanced Queue)
    - [x] Lease time: 10 minutes
    - [x] Process via: cron
    - [x] Processing time: 10 seconds
    - [x] Remove completed items: after 30 days for both failed and success job statuses
- [x] Job Type (Advanced Queue)
    - [x] Sends email message using Message Notify
    - [x] Receives Message values from the job payload
    - [x] Receives Message field values from job payload
    - [x] Allows for optional allowed recipients to restrict mail delivery
- [x] Message Template configured as defined above.
- [x] Mail Handler exists and configured for the correct Message Template
- [x] ECA Model
    - [x] Is disabled
    - [x] Has "cron" event configured to always fire (* * * * *)
    - [x] Includes Views query action
    - [x] Includes Create Job action

**Comment by dsasser** [comment]
@FranECross 

Some questions:

1. We never talked about how we are going to calculate if a banner is "expired". As it stands, there are at least 4 ways to track that a banner was edited/modified: the 'updated' date on the node, the 'last modified by an editor' field on the node, and creating start + end dates on the banner content type (Jordan did a design on this), or some other field/data source not yet identified. This probably warrants it's own discussion/call.
2. Who are the recipients of the notifications? The last modified editor?

**Comment by FranECross** [comment]
@dsasser I updated the story for accuracy. We've chatted in the past about having an initial email go to editors 4 days prior to 'expiration', then upon 'expiration'. Can this story contain both triggered emails? I'm happy to create one or more other stories to chunk things up if that's better, or if one ticket will work, I can update the AC and description. TIA!

**Comment by aklausmeier** [comment]
For my reference: email notification will pull from [Vet Centers verbiage](https://prod.cms.va.gov/admin/structure/message/manage/vet_center_outdated_content?destination=/admin/structure/message) with revisions as needed

**Comment by FranECross** [comment]
@aklausmeier @davidconlon Here's proposed email content for the Full-width banner cc @dsasser @thejordanwood 

Subject: Please update or archive your Full-width banner by [date]

Please plan to archive, or edit to extend display of, your published Full-width banner by [date]. 

As a reminder, Full-width banners are to be used for emergencies or actions a veteran needs to take and should display for 7-days, unless there’s a compelling reason to extend display of the content.

If you do need to extend the display of the banner, simply edit with a comment to that effect, and the 7-day countdown window will reset.

________________________________________________________________________________________________________


For more information, you can read this [Knowledge Base article](https://prod.cms.va.gov/help/vet-centers/vet-center-content-review) for tips and best practices to manage compliance.

Need help?
- If you are a Vet Center Director or Outreach Specialist who needs assistance accessing Drupal CMS, please email the CMS Support Team at support@va-gov.atlassian.net.

- If you want to refresh your skills, need ideas, or have questions about creating content for your webpages, you can find How to Guides and Training videos in the [Drupal CMS Knowledge Base](https://prod.cms.va.gov/help/vet-centers) or drop in during office hours.
- If you received this email and no longer have a role at a Vet Center, please inform us by emailing the CMS Support Team at support@va-gov.atlassian.net.


________________________________________________________________________________________________________

**Coming Soon:**
- Banners will be permanently auto-archived at the end of Day 7, unless edited to reset the 7-day timeframe. We will give ample notice before this functionality is implemented.
- Notifications and auto-archiving of Home Page Benefit Promo Blocks
- Notifications and auto-archiving of Home Page News Spotlight Blocks

**Comment by aklausmeier** [comment]
@FranECross This looks good to me. Are we planning to use this same email verbiage for the email that is sent on day 5 and day 7? 

Also, ticket mentions verbiage for instructional text on creation screen. Does that exist already? 

> content editors see instructional text on the Full-width banner creation screen explaining the intent of banners and that they should only display for up to 7 days

**Comment by dsasser** [comment]
@FranECross The verbiage looks great I just have a suggestion. The message copy lacks any data that ties the message back to the expiring content: title, link, etc. This means that if an editor receives this email, they won't know which node/block is expiring, and will have to go hunt it down on their own. I suggest we add a link to the affected content somewhere in the body of the message.

**Comment by FranECross** [comment]
> @FranECross The verbiage looks great I just have a suggestion. The message copy lacks any data that ties the message back to the expiring content: title, link, etc. This means that if an editor receives this email, they won't know which node/block is expiring, and will have to go hunt it down on their own. I suggest we add a link to the affected content somewhere in the body of the message.

@dsasser Excellent catch, thanks! I'll edit as suggested today, as well as incorporate suggestions from @aklausmeier and then will ping both of you again.

**Comment by FranECross** [comment]
> @FranECross This looks good to me. Are we planning to use this same email verbiage for the email that is sent on day 5 and day 7?
> 
> Also, ticket mentions verbiage for instructional text on creation screen. Does that exist already?
> 
> > content editors see instructional text on the Full-width banner creation screen explaining the intent of banners and that they should only display for up to 7 days

@aklausmeier Thanks for catching the need for instructional text. I had that on my radar at one time but then it slipped into the dreaded cracks.

 @dsasser So as not to make this ticket bigger, shall I create a new ticket to have instructional text added to the banner screen?

**Comment by FranECross** [comment]
@dsasser @aklausmeier I've edited the Day 4 email, and have also created a slightly different Day 7 email. Please see below, and as always, suggestions are welcome!

### Day Four Email


**Subject**: Please update or archive your Full-width banner by [Day 7 Date]

Please plan to archive, or edit to extend display of, your published Full-width banner entitled [content title / link] by [Day 7 Date]. 

As a reminder, Full-width banners are to be used for emergencies or actions a veteran needs to take and should display for 7-days, unless there’s a compelling reason to extend display of the content.

If you do need to extend the display of the banner, simply edit with a comment to that effect, and the 7-day countdown window will reset.


_______________________________________________________________________________________________________________________________

For more information, you can read this [Knowledge Base article](https://prod.cms.va.gov/help/vet-centers/vet-center-content-review) for tips and best practices to manage compliance.

Need help?
- If you are a Vet Center Director or Outreach Specialist who needs assistance accessing Drupal CMS, please email the CMS Support Team at support@va-gov.atlassian.net.
- If you want to refresh your skills, need ideas, or have questions about creating content for your webpages, you can find How to Guides and Training videos in the [Drupal CMS Knowledge Base](https://prod.cms.va.gov/help/vet-centers) or drop in during office hours.
- If you received this email and no longer have a role at a Vet Center, please inform us by emailing the CMS Support Team at support@va-gov.atlassian.net.

________________________________________________________________________________________________________________________________

**Coming Soon:**
- Banners will be permanently auto-archived at the end of Day 7, unless edited to reset the 7-day timeframe. We will give ample notice before this functionality is implemented.
- Notifications and auto-archiving of Home Page Benefit Promo Blocks
- Notifications and auto-archiving of Home Page News Spotlight Blocks


### Day 7 Email


**Subject:** Action Needed: Your Full-width banner has displayed for seven (7) days

Your Full-width banner has displayed for seven days. In order to meet the purpose of this type of content, please plan to archive, or edit to extend display of, your published Full-width banner entitled [content title / link] by [date]. 

As a reminder, Full-width banners are to be used for emergencies or actions a veteran needs to take and should display for 7-days, unless there’s a compelling reason to extend display of the content.

If you do need to extend the display of the banner, simply edit with a comment to that effect, and the 7-day countdown window will reset.

________________________________________________________________________________________________________________________________

For more information, you can read this [Knowledge Base article](https://prod.cms.va.gov/help/vet-centers/vet-center-content-review) for tips and best practices to manage compliance.

Need help?
- If you are a Vet Center Director or Outreach Specialist who needs assistance accessing Drupal CMS, please email the CMS Support Team at support@va-gov.atlassian.net.
- If you want to refresh your skills, need ideas, or have questions about creating content for your webpages, you can find How to Guides and Training videos in the [Drupal CMS Knowledge Base](https://prod.cms.va.gov/help/vet-centers) or drop in during office hours.
- If you received this email and no longer have a role at a Vet Center, please inform us by emailing the CMS Support Team at support@va-gov.atlassian.net.


________________________________________________________________________________________________________________________________

**Coming Soon:**
- Banners will be permanently auto-archived at the end of Day 7, unless edited to reset the 7-day timeframe. We will give ample notice before this functionality is implemented.
- Notifications and auto-archiving of Home Page Benefit Promo Blocks
- Notifications and auto-archiving of Home Page News Spotlight Blocks

**Comment by aklausmeier** [comment]
@FranECross do you mind if we use "titled" instead of "entitled" to line up verbiage with the title field

**Comment by FranECross** [comment]
@aklausmeier Not at all! I'll edit it directly in my comment above.

**Comment by dsasser** [comment]
Moving former ticket description here for posterity:

<details>
<summary>Original description</summary>

**The below represents the original state of this ticket, which has changed since written. The scope of the work ended up being too big for a single ticket, and as engineering details emerged during iterative work, we decided to rewrite this issue to reflect work that is now expected and deliverable.**

## Dependencies
- @FranECross to come up with text and coordinate with for Jordan to provide verbiage for the 7 day.
- 

## Description
Full-width banners in VA.gov become stale and aren’t monitored or updated on a regular cadence, allowing many of them to still display after a campaign or event has passed. In some cases, they are being used for month-long campaigns instead of their original intention - for informational alerts or warning alerts.

In order to provide timely information to Veterans and other users of VA.gov, and ensure banners are replaced and/or monitored, this MVP will change the timeframe for Full-width banners to seven (7) days.

Answers to questions per Dave:
- Calculation of if the banner is 'expired' should use the existing: "Save as published + 7"
- Recipients = The last modified editor.

## Questions (Answered)
@FranECross to discuss with Dave
- How we are going to calculate if a banner is "expired". As it stands, there are at least 4 ways to track that a banner was edited/modified: **_Per Dave, use "Save as published + 7"_**
  - the 'updated' date on the node, 
  - the 'last modified by an editor' field on the node
  - creating start + end dates on the banner content type (Jordan did a design on this), or
  - some other field/data source not yet identified. 
- Who are the recipients of the notifications? **_Per Dave: The last modified editor._**

### User Stories

#### **Veteran's Perspective:**
**AS A** Veteran, their Caregiver, or other users of VA.gov viewing Full-width banners
**I EXPECT** Full-width banners to contain time-boxed informational alerts or warning alerts that only display for 7 days, unless purposely extended by VA.gov editors
**SO THAT** important alerts garner my attention and are only displayed for a short period of time so that I don't start ignoring them.

#### **PO/PM's Perspective:**

**AS A** PO/PM for Full-width banner content types
**I WANT** the display 'window' for Full-width banners to change from 365 days to 7 days
**AND** have content editors see instructional text on the Full-width banner creation screen explaining the intent of banners and that they should only display for up to 7 days
**SO THAT** the banners are presented to Veterans, their caregivers, and other VA.gov users as intended for a short period of time
**AND** so that editors will know to expect email notifications (in future stories) three days before Day 7, then on Day 7 telling them to edit and extend the life of the banner, or archive it. (and in the future, when auto-archiving is implemented, they will receive an email notification upon archival of the content)

#### **Content Editor's Perspective:**
**AS A** Content Editor creating a new Full-width banner
**I WANT** to see instructional text on a Full-width banner creation screen so that I understand expectations for display of Full-width banners has changed and is now 7 days
**SO THAT** I can plan accordingly in managing my content and not be surprised by receiving notifications at 3 days prior to the 7th day, and on 7th day, instead of the current 365 days.
**AND** so that I understand I should edit & comment to extend display of the content or archive the content


### Additional Information

### Engineering notes / background

### Analytics considerations

### Quality / testing notes

## Acceptance criteria

</details>

**Comment by dsasser** [comment]
Verified in prod:

![Screenshot 2024-03-20 at 11 10 33 AM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/221539/c8918fe5-0f95-4f85-b8d9-85c0fad0b8af)

![Screenshot 2024-03-20 at 11 08 05 AM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/221539/9890fb75-7280-4de4-8f7a-fe1614787baa)

![Screenshot 2024-03-20 at 11 09 59 AM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/221539/e77d2506-d973-498c-b4bf-0d83f549247a)
