### ISSUE TITLE
Coordinate further triage meeting with the Platform team

### ISSUE THREAD

**Issue by cmaeng** [department-of-veterans-affairs/va.gov-cms#1642]
## Description
An initial meeting was held in February with the Platform team on potentially building out a triage team and process. One of the action items was to circle back after the CMS team had thought through its own triage/support processes.

This action item was brought up in the Sprint 4 retro on 4/24/20.

## AC
- [ ] We have a good understanding of where we want to take our support/help desk processes
- [ ] We are able to communicate to the Platform team where we are and where we want to be with our processes
- [ ] Meeting held with Platform folks to further discuss cross team triage

**Comment by erogray** [comment]
No longer directly relevant since processes have changed since this ticket was created.
