### ISSUE TITLE
Update Drupal Core to 10.1.7

### ISSUE THREAD

**Issue by edmund-dunn** [department-of-veterans-affairs/va.gov-cms#16429]
## User Story or Problem Statement
Update Drupal Core to 10.1.7

## Acceptance Criteria
- [ ] Automated tests pass

## Team
Please check the team(s) that will do this work.

- [x] CMS Team
- [ ] Public Websites
- [ ] Facilities
- [ ] Accelerated Publishing

**Comment by maortiz-27-80** [comment]
Note: added to Sprint 99.  cc: @BerniXiongA6
