### ISSUE TITLE
Missing required path property in va_gov_preview & va_gov_build_trigger

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#1644]
## Description

Notice: Undefined index: path in Drupal\Core\Routing\RouteBuilder->rebuild()

Another notice is observed locally when clearing cache via drush

<img width="1583" alt="Screen Shot 2020-04-28 at 11 02 49 AM" src="https://user-images.githubusercontent.com/16477724/80515942-f8e62a00-893f-11ea-8596-7905685e2fed.png">

**Conclusion:**
`Notice: Undefined index: path in Drupal\Core\Routing\RouteBuilder->rebuild() (line 177 of /app/docroot/core/lib/Drupal/Core/Routing/RouteBuilder.php)` is caused by missing `path` property which is _required_ for route definition. Path property is missing in routes defines in the following two files:
- `docroot/modules/custom/va_gov_preview/va_gov_preview.routing.yml`
- `docroot/modules/custom/va_gov_build_trigger/va_gov_build_trigger.routing.yml`

## Acceptance Criteria
* Notice is not logged when clearing cache w/ drush

**Comment by cmaeng** [comment]
This issue was completed in a previous sprint but just catching it now. Including in sprint 19 for reporting purposes.
