### ISSUE TITLE
VBA RO: national rollout launch plan

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#16446]
Launch plan for VBA Regional Office national rollout (to follow Pilot MVP rollout, research, and iteration).
#16445 tracks the Pilot rollout.

## Questions
* Drupal: any integration branches / PRs to be refreshed & merged? Or everything is merged already?
  * 
* FE: What are we launching beyond what shipped for the Pilot rollout? 
  * 
* Drupal: publishing requirements
* Change management: 

## Prerequisites / blockers
- [ ] Drupal changes merge to main / deploy
- [ ] FE changes, if any, merge to main / deploy
- [ ] Drupal content entry is complete in Centralized Content

## Launch Order of operations
(Assumes that code reviews, design reviews, a11y reviews were completed on separate engineering tickets, and that code is prod-ready.)
- [ ] Change management rollout
- [ ] Drupal editor access is provided to new editors (should be a prereq/blocker?)

## Follow up tasks
TBD

**Comment by xiongjaneg** [comment]
@jilladams The two issues you created were very similar. There's only one launch for pilot MVP in January. I'm repurposing this one for the later national rollout, which likely won't be until spring or summer.

**Comment by jilladams** [comment]
Thanks! I have been a little muddy about what the FE expectations are for launching to Editors to create content vs. content showing up in the FE, vs. rolling out to all editors which is later later as you noted, hence my ticket weirdness. So: that's a helpful distinction. We can clarify the FE expectations on the Pilot launch plan ticket when we discuss.

**Comment by jilladams** [comment]
Closing as a dupe of VA.gov rollout, #16445. We can create new launch plans for later iterations once we know what we're launching.
