### ISSUE TITLE
Facility Locator search does not respect state 

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-cms#16455]
## Describe the defect
Several instances of random and unexpected behavior have been reported during Facility Locator searches.  During these scenarios, a search for locations in one place have results from an entirely different, non-neighboring state. 

## To Reproduce
Scenario 1: Searches in Montana return results in New Jersey
1. Go to [Facility Locator](https://www.va.gov/find-locations/?page=1&address=scobie%2C%20mt&facilityType=benefits&serviceType&latitude=39.685396&longitude=-74.605711&radius=10&bounds%5B%5D=-76.005711&bounds%5B%5D=38.285396&bounds%5B%5D=-73.205711&bounds%5B%5D=41.085395999999996&context=Mount%2C%20New%20Jersey%2C%20United%20States)
2. Enter "`Scobie`, MT",  select "VA benefits" and "All VA benefits" as search parameters
3. View search results
4. Observe results are retuned for locations in New Jersey, not Montana - the map appears to center on "Mount". 
5. Update the geographic parameter with a different spelling: `Scobey` and resubmit
6. Observe the map is correctly centered in Montana and appropriate no results message is displayed 
7. Update the geographic parameters with "Paulsen, MT" and resubmit
8. Observe results are retuned for locations in New Jersey, not Montana
9. Update the geographic parameters with "Polson, MT" and resubmit
10. Observe locations are returned as expected

<details>
<summary> Montana - New Jersey examples </summary>

<img width="774" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM1h0QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6a1b91e233150190800113117fe8ddcf684997bb/image.png" alt="image.png" />

<img width="857" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM250QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f2d6850814fa77a70f046aad0019ed38b458e131/image.png" alt="image.png" />

<img width="811" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM2Z0QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--92bf151d4e905f2c4f5c0921a7934e413ab36e72/image.png" alt="image.png" />

<img width="923" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM2p0QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3d78ceb33e60b8fecf97a676c3eef9e0da83fc57/image.png" alt="image.png" />

</details>

---

**Scenario 2**
1. Search parameters: Pine Ridge, VA + Community providers + Technician - Personal care attendant = search results near Naples, FL
2. Remove VA and just search with "Pine Ridge" = search results in South Dakota

<details>
<summary> Pine Ridge examples </summary>

<img width="606" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNlcxQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--974cb3461352ff6a12a0053cb42c04072b4e808d/image.png" alt="image.png" />

<img width="613" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNnkxQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--170c99404d551f3552c6c239765e1c65a03ffda8/image.png" alt="image.png" />
</details>

---

**Scenario 3**
1. Go to Facility Locator
2. Enter 123 Barnes Rd, Monticello, Florida as geographic parameter, Urgent care as Facility type and All urgent in-network care for Service type
2. Click search
3. Observe search result in Virginia is returned
4. Change geographic parameter to 789 Barnes Rd, Monticello, Florida and resubmit search
5.  Observe search result in Virginia is returned
6.  Change geographic parameter to 12345 Barnes Rd, Monticello, Florida and resubmit search
7.  Observe search results include locations ~21 miles away near Tallahassee, FL and Thomasville, GA
8.  Change geographic parameter to Monticello, Florida and resubmit search
9.  Observe search results include locations ~21 miles away near Tallahassee, FL and Thomasville, GA
10.  Change geographic parameter to Barnes Road, Iowa and resubmit search
11. Observe search results include locations in Wisconsin

<Details>
</summary> Florida - Virginia screenshots </summary>

<img width="876" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMER0QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--39111aa00614dfc6d1ee433bd6176e90e62158d7/image.png" alt="image.png" />

<img width="887" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMG50QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9aa9876d18c2868a2144452fce3d78112c1ffa0a/image.png" alt="image.png" />

<img width="609" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMHZ0QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ea5b19e57dc26ec4fb583eeff732624578e9ccd4/image.png" alt="image.png" />

<img width="680" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMDd0QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e4bd75e51053f80c0a78fe6f81ff6ba6dbf961c2/image.png" alt="image.png" />

</details>
 
---

**Scenario 4**

1. Go to [Facility Locator](https://www.va.gov/find-locations/?address=East%20Olympic%20Place%2C%20Shelton%2C%20Washington%2098584%2C%20United%20States&bounds%5B%5D%5B%5D=-73.843164&bounds%5B%5D%5B%5D=40.566486&bounds%5B%5D%5B%5D=-72.343164&bounds%5B%5D%5B%5D=42.066486&context=Shelton%2C%20Connecticut%2C%20United%20States&facilityType=pharmacy&latitude=41.316486&longitude=-73.093164&page=1&radius=11&serviceType&bounds%5B%5D=-73.843164&bounds%5B%5D=40.566486&bounds%5B%5D=-72.343164&bounds%5B%5D=42.066486)
2. Enter "East Olympic Place, Shelton, Washington 98584, United States and "Community pharmacies" as search parameters
3. View search results
4. Observe results are retuned for locations in Connecticut
5. Update the geographic parameter by removing the street address and entering only Shelton, Washington 
6. Observe locations are returned as expected

<Details>
</summary> Washington - Connecticut screenshots </summary>

<img width="886" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNER0QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fec4140fbf5c37535c1d4a883badf0dcb1490a38/image.png" alt="image.png" />

<img width="902" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNEx0QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d3a29ffa7db4edf380af6b4bc731c037a7772d4a/image.png" alt="image.png" />

</details>

## AC / Expected behavior
- [ ] The Facility Locator would attempt a search honoring the user parameters and either return valid results or tell me no results were available and how to revise my search. 
- [ ] If the issue is larger, stub subsequent ticket(s).

**Comment by Agile6MSkinner** [comment]
3 and 4 no longer exhibit the noted behavior, mostly likely because these appear to be MapBox issues  that they have fixed on their end. #s 1&2 would also likely need to be fixed on their end, although they are results from searches with misspelling or not enough information, so that's unlikely to happen. Closing as not planned.
