### ISSUE TITLE
Review of new or updated KB article : VA Police

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#16453]
## Which article(s) need review?
Provide the link to latest revision of each article that requires review.
- [Article](https://prod.cms.va.gov/help/vamc/about-va-police)
  
## Priority or deadline for request
Choose either Deadline or a priority:

- [ ] Deadline: [name the deadline here]
- [ ] Priority:
  - [ ] Critical
  - [x] High
  - [ ] Medium
  - [ ] Low

## Associated KB article ticket
Provide the original ticket where the article was originally created/updated so we can refer back there for any additional context if necessary.
- #16372 
  
## Can article(s) be published?
Once the article has been fully reviewed, can the article(s) be published? For example, is anything tied directly to an upcoming feature and this information should not be published until the feature is on production?
- [x] Yes, all article(s)s within this ticket can be published once reviewed *Already published due to legislative timeline
- [ ] No, the article(s) within this ticket should not be published and should only be reviewed

## Acceptance Criteria
- [ ] Article reviewed by CMS Team
- [ ] Requesting person/team has been notified that article was reviewed/published

**Comment by xiongjaneg** [comment]
Noting that Facilities Team is still waiting for the point of contact if the editor thinks the contact information is wrong.

**Comment by xiongjaneg** [comment]
MMVP version published, will be updated for MVP in January

**Comment by BerniXiongA6** [comment]
@xiongjaneg I'm happy to review this and will let you know if I have any suggested edits after the fact. Thank you! cc: @maortiz-27-80

**Comment by xiongjaneg** [comment]
ok to closer per Berni
