### ISSUE TITLE
[Income Limits] Update the React app with info so Veterans know Income Limits data is for 2024 income limits

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-cms#16458]
## Description

We will be uploading the income limits data for the 2023 income year, and Dave C would like the Veterans to see more than the typically updated text when new data is uploaded.

CAIA doesn't believe this needs a full-width banner, so we will be updating the react app to display an in-page info alert after the intro paragraph on the first page of the tool. 

**We've updated this tool to check 2024 income limits**
You can check your income limits for 2024 now.

### User story

**AS A** Veteran using the Income Limits application
**I WANT** to be aware that the data has been refreshed for 2024
**SO THAT** I know I'm seeing the most up-to-date information

## Acceptance criteria

- [ ] AC1: React-app [informational alert](https://design.va.gov/components/alert), displays to Veterans/other users in lock-step with the upload of new Income Limits data in ticket [#16371 ](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16371)

GIVEN I'm a Veteran viewing the first page of the Income Limits tool
WHEN I look under the intro paragraph on the page, 
THEN I'll see an in-page react-app info alert, AND the text will be:

**We've updated this tool to check 2024 income limits**
You can check your income limits for 2024 now.

- [ ] AC2: Ticket is created to no longer display the info-alert after January 31

**Comment by FranECross** [comment]
@jilladams @chriskim2311 @dsasser I've created the ticket for the Income Limits info alert and have added AC to both tickets indicating they should be released together (or as close to together as they can be).

**Comment by jilladams** [comment]
Noted here in ACs that this should use [informational alert](https://design.va.gov/components/alert).

**Comment by jilladams** [comment]
Also noting: this ticket is properly blocked by #16371 , as we won't want the alert to tell Veterans we're using updated data until we actually are.

**Comment by randimays** [comment]
[PR is in draft](https://github.com/department-of-veterans-affairs/vets-website/pull/27232) but we are properly blocked by the Income Limits data refresh on Jan 1 at midnight.

**Comment by randimays** [comment]
@FranECross @jilladams CC @dsasser @Becapa 

The Income Limits 2024 data is available; I just validated in `dev.ves.va.gov/esr` (on a VA browser):
<img width="1445" alt="Screenshot 2024-01-02 at 11 15 28 AM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/19175324/4edb4f7f-796a-470a-a330-e6db22484f36">
<img width="1428" alt="Screenshot 2024-01-02 at 11 15 50 AM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/19175324/2d6c199d-0be8-42f6-ba59-780629ff5581">

**Comment by FranECross** [comment]
Excellent! Thank you, @randimays !! And also thanks for taking care of the banner ticket.

**Comment by randimays** [comment]
Banner added and verified in prod on desktop and mobile. Closing!

<img width="938" alt="Screenshot 2024-01-02 at 3 48 03 PM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/19175324/184c7707-84ad-4e02-8a8c-56cd112fc25a">
<img width="475" alt="Screenshot 2024-01-02 at 3 47 55 PM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/19175324/9f68da8b-258d-427f-bad7-08a8229e470c">

**Comment by FranECross** [comment]
@jilladams Can this be added to next week's ToT? Also I'll send an email to Joshua Faulkner letting him know the data has been uploaded and the banner is displaying. Great work everyone! cc @randimays @dsasser

**Comment by laflannery** [comment]
I would like to make a note for next year in case we use this ticket for a reference on how to do this:

This alert should have gone below the H1 in order to retain the proper heading structure for accessibility so when we add this again I would recommend adjusting the placement

**Comment by FranECross** [comment]
Thanks, Laura! I'll add a note in the Income Limits documentation ticket so that this info is added to it.
