### ISSUE TITLE
Hide "Operating status - more information" when "Normal services and hours" is selected

### ISSUE THREAD

**Issue by omahane** [department-of-veterans-affairs/va.gov-cms#16469]
## User Story or Problem Statement
The following content types should have "Operating status - more information" hidden when **Operating status** is "Normal services and hours."
- NCA
- VBA Facility
- Vet Center
- Vet Center CAP
- Vet Center Outstation

Per Blake in [Slack](https://dsva.slack.com/archives/C0FQSS30V/p1706211451730729?thread_ts=1706207441.523539&cid=C0FQSS30V): USWDS and VA Design System suggest the use of radio buttons when the number of options to choose from is less than 7. I would say that mimicking how the VAMC section works would be my guidance

## Acceptance Criteria
- [x] The widget for "Operating status" is changed from a dropdown to a set of radio buttons for the following:
  - [x] NCA
  - [x] VBA Facility
  - [x] Vet Center
  - [x] Vet Center CAP
  - [x] Vet Center Outstation 
- [x] The "Operating status - more information" is hidden (using the VAMC radio button model) when normal hours are set for the following:
  - [x] NCA
  - [x] VBA Facility
  - [x] Vet Center
  - [x] Vet Center CAP
  - [x] Vet Center Outstation
- [x] "Operating status" is required for Vet Center Outstation.

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [x] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [ ] `Public Websites`
- [x] `Facilities`
- [ ] `User support`

**Comment by swirtSJW** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Sitewide-Facilities-639f5253e4b702a32376339e/issues/department-of-veterans-affairs/va.gov-cms/16469?planning-poker) with Zenhub @omahane

**Comment by xiongjaneg** [comment]
This doesn't apply to VAMC because VAMC already hides it.

**Comment by xiongjaneg** [comment]
@thejordanwood @BlakeOrgan Is there a general preference for dropdown vs radio button for selecting operating status if we make this consistent across product?
