### ISSUE TITLE
[UPDATE] "Medical records" to include VBA fields

### ISSUE THREAD

**Issue by davidmpickett** [department-of-veterans-affairs/va.gov-cms#16463]
### Which Taxonomy is this term for?

VA services taxonomy

### Link to existing term

https://prod.cms.va.gov/health-care/medical-records

### Rationale for updating this term

Add VBA fields to existing term

### Which products will this term impact?

VBA Regional Office

### Have stakeholders from impacted products been consulted?

Yes - pending further discussion with council

### Have you drafted content for all the relevant subfields?

No - this one was not part of the previous round of description drafting and copy editing

### Acceptance Criteria

- [ ] Content for subfields is drafted in Drupal by Product team
- [ ] Content is reviewed by relevant taxonomy governance body 
- [ ] Content is reviewed by relevant stakeholders
- [ ] (List any necessary review and approval steps here)
- [ ] Term is published

**Comment by davidmpickett** [comment]
@xiongjaneg @mmiddaugh @aklausmeier - Just drafted and refined this Taxonomy ticket. This one is small and self-contained. One of the few terms for VBA that reuses an existing term. Only reason it's a 2 is because it doesn't already have a description drafted and copy-edited.

According to @mmiddaugh's [note on Batch 2 ](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16269#issuecomment-1850871779) this term is still pending feedback from Taxonomy Council, so might not be ready to pull in.

**Comment by mmiddaugh** [comment]
Based on recent conversation with the RO SMEs, the following description is ready to be added and reviewed by CAIA.

### Medical records
VBA Type of care: Other services
(Proposed) VBA National description: We can help you request military service treatment and private medical records to support your claim.

**Comment by mmiddaugh** [comment]
Update: this has been combined with Military records for now. We can reassess as the roll-out continues
