### ISSUE TITLE
Content Audit - Phone Numbers will not export data when filtered by Content type

### ISSUE THREAD

**Issue by omahane** [department-of-veterans-affairs/va.gov-cms#16461]
## Problem statement
The view cannot be exported by content type, which is likely to be one of the most common ways to filter this information.
As it is, the view can be filtered by content type, but the filtered data will not export.

## Describe the defect
The Content Audit - Phone Numbers does not successfully download when it has been filtered by Content Type.

## To Reproduce
1. Go to https://prod.cms.va.gov/admin/content/audit/phone-numbers
2. Click on **Content type**
3. Choose "NCA"
4. Click **Filter**
5. Verify that it filters the view to only show NCA facilities
6. Click **Download CSV**
7. Verify that you are redirected to your user page `/user/####` and presented with the following error: "The submitted value nca_facility in the type element is not allowed."
8. Click on the "here" of "Download the file here"
9. Open the downloaded file
10. Confirm that it's empty

## AC / Expected behavior
- [ ] The data export can successfully generate a CSV of items filtered by Content type
- [ ] The user is redirected back to the Content Audit - Phone Numbers view with the parameters set, meaning that the filtered list is as it was before clicking **Download CSV**

## Screenshots
![Screenshot 2023-12-15 at 4 20 41 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/766573/2209b734-ccb2-469d-98e0-0dd141bc93ea)

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Defect")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS workstream (orange) (not needed for bug tickets)
- [ ] CMS-supported product (black)

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [ ] `Public Websites`
- [x] `Facilities`
- [ ] `User support`
- [ ] `Accelerated Publishing`

**Comment by jilladams** [comment]
From planning: noting, let's timebox this to the 3 points, and if it's not solvable in that time, we'll likely icebox it.

**Comment by jilladams** [comment]
Verified in prod.
