### ISSUE TITLE
Many VAMC facility services have numerical aliases 

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#16465]
## Problem statement
It was discovered that many services ended up with aliases that do not reflect their service, only a number.  This has no impact on the FE but does create some confusion when you look at the url for a node in the CMS.  It would be nice to know the cause, but aliases are not revisioned, so it is hard to know when this occurred or why.

## Describe the defect
[Slack thread](https://dsva.slack.com/archives/C02730UEZPS/p1702679169410039?thread_ts=1702678164.231229&cid=C02730UEZPS) 

example : /eastern-oklahoma-health-care/locations/jack-c-montgomery-department-of-veterans-affairs-medical-37
shouldbe: /eastern-oklahoma-health-care/locations/jack-c-montgomery-department-of-veterans-affairs-medical-center/urology

## To Reproduce
1. These are detectable by spot checking the alias table for things like `-11` or `-5`

Unfortunately aliases are not tracked as part of revisions so it is not easy to determine when or why this happened.
Possibilities:
1. these picked up a bad alias when migrated in originally
2. some bulk operation damaged them.
3. Created via some inline entity form that creates nodes not fully formed? 
4. ???

The good news is a bulk operation of updating the alias does solve the problem.  The bad news is that bulk operation might be too intensive to run on ALL services since we have so many.   We would want to try that in a lower environment to make sure it works
The other good news is that this has NO FE implications as these nodes do not have pages of their own on the FE.  THis is mainly a cosmetic niceity on the CMS UX.

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Defect")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [ ] CMS workstream (orange) (not needed for bug tickets)
- [ ] CMS-supported product (black)

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [ ] `Public Websites`
- [x] `Facilities`
- [ ] `User support`
- [ ] `Accelerated Publishing`

**Comment by swirtSJW** [comment]
Upstream issue that points out the defect that aliases are revisionable, but do not create revisions https://www.drupal.org/project/drupal/issues/3321805

**Comment by omahane** [comment]
Updating the URL aliases took 5:21 seconds on staging.

**Comment by swirtSJW** [comment]
That sounds super quick and not a concern at all.

**Comment by omahane** [comment]
I ran this on production at 8:00 am CDT and checked the aliases. They appear to be gone.

**Comment by omahane** [comment]
This can now be closed.
