### ISSUE TITLE
UX: Standardize Operating status - more info across Facilities products

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#16470]
## Description
UX review across products to establish a pattern / figure out if we want to rework any products that don’t align with Hiding "Operating status - more info" for "Normal services and hours"

<img width="876" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeGx0QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2586790fd5132d61f19a680acd5efbeb966338f2/Screenshot_2023-12-15_at_10.03.47_AM.png" alt="Screenshot_2023-12-15_at_10.03.47_AM.png" />

Christian noted on 12/18/23:
NCA: Dropdown, no hiding
VAMC Facility: Radio button, hiding
VBA Facility: Dropdown, no hiding
Vet Center: Dropdown, no hiding
Vet Center CAP: Dropdown, no hiding
Vet Center Outstation: Dropdown (not required), no hiding

Also note transition to radio buttons post-VAMC launch discussed in [Slack thread](https://dsva.slack.com/archives/C0FQSS30V/p1652109866314259?thread_ts=1652109756.462559&cid=C0FQSS30V)

## Acceptance Criteria
- [ ] Testable_Outcome_X
- [ ] Testable_Outcome_Y
- [ ] Testable_Outcome_Z
- Required reviews are done (could be at UX sync)
  - [ ] Requires accessibility review
  - [ ] Requires UX Lead review
- [ ] Stub subsequent tickets or tag PM to stub

**Comment by davidmpickett** [comment]
Was resolved in #16469
