### ISSUE TITLE
Next Build Prod CMS preview server logging

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#16474]
## Requirements

We should instrument Next Build Preview servers for monitoring alerting and logging, so that we know if there are any issues with them and can diagnose problems.

```[tasklist]
### Acceptance criteria
- [ ] Next Build CMS Preview servers are monitored for uptime
- [ ] If the Preview server is down, an alert is triggered
- [ ] The running log output of the Preview Server is captured and forwarded to log management systems
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16857
```

## Background & implementation details

This ticket only applies to the 'BRD-adjacent' Prod preview servers, not Tugboat.

Work could be done against a lower environment and the specifics changed later.

Presumably monitors and alerts would be handled in Datadog.

Preview server output should be captured and sent to log management so that it can be examined for issues that arise.

```[tasklist]
### Implementation tasks
- [ ] Use this if it helps you or feel free to delete.
```

**Comment by timcosgrove** [comment]
Unsure if we can capture and forward STDOUT 'logs' or if we need to instrument proper logging for the Next.js server.

**Comment by jschmidt-civicactions** [comment]
Looks like I have access to vagov-va-datadog now.

**Comment by timcosgrove** [comment]
Dupe of #16954

**Comment by timcosgrove** [comment]
Also a dupe of https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16956 . Closing.
