### ISSUE TITLE
S3 buckets exist for hosting Next Build output

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#16475]
## Requirements

We need S3 buckets for Next Build output, so that we have a place to deploy static content to.

```[tasklist]
### Acceptance criteria
- [x] S3 buckets are available for production, staging, and dev Next Build output
- [x] These buckets are configured similarly to their Content Build counterparts with respect to permissions, access, behavior
- [x] The bucket can be reached at an S3-provided domain.
- [x] If the existing Content Build S3 buckets are code-managed, set these buckets up identically
```

## Background & implementation details

Bucket names:
* next-content.www.va.gov
* next-content.staging.va.gov
* next-content.dev.va.gov

These should be set up with web servers and similar object access permissions to what exists in content.www.va.gov etc.

These do not need to be connected to a domain other than what S3 provides.

```[tasklist]
### Implementation tasks
- [ ] Use this if it helps you or feel free to delete.
```

**Comment by jschmidt-civicactions** [comment]
It actually looks like there *are* Terraform configs for content-build S3 buckets in the devops repo, eg.

- https://github.com/department-of-veterans-affairs/devops/blob/master/terraform/environments/global/iam_gha_resources.tf#L336
- https://github.com/department-of-veterans-affairs/devops/blob/master/terraform/environments/global/iam_policies.tf#L2453

The content-build buckets that will be cloned for next-build are all tagged like one would expect a Terraform-managed resource to be tagged. So I'll need to check on how to add what we need for this ticket there.

**Comment by jschmidt-civicactions** [comment]
@timcosgrove I see there is also a `content.sandbox.va.gov` bucket, will you need this replicated to `next-content.sandbox.va.gov` as well?

**Comment by jschmidt-civicactions** [comment]
PR submitted:
https://github.com/department-of-veterans-affairs/devops/pull/13894

**Comment by olivereri** [comment]
IaC location:
https://github.com/department-of-veterans-affairs/terraform-aws-vsp-vets-api/blob/ebe79cec389e4a937e79a9094efdb66db54dcd5a/s3.tf#L497
