### ISSUE TITLE
[Events] [UX] Recurring events "View other times for this event" shows past recurrences

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#16472]
## Status
[2024-07-03] [Fran] Engineering [ticket ](https://app.zenhub.com/workspaces/vagov-sitewide-product-team-6645154188a81a1f7a0a9464/issues/gh/department-of-veterans-affairs/va.gov-cms/18440)created
[2024-05-09] Good for Carissa to take on.

## Description 

On a recurring event in the FE, a panel exists to "View other times for this event". 
That panel currently shows allllll recurrences of the event, in chrono order. So: you can expand the panel and get a list of all event times in the past. This doesn't seem terribly useful to Veterans.

## User Story
AS A Veteran, their family member, caregiver and/or survivor
I WANT to see only current or future events when I'm looking for events to attend
SO THAT I don't have to page through past events or be confused that an event is in the past and can readily find events of interest to me.

e.g. https://www.va.gov/minneapolis-health-care/events/48206/

![Screenshot 2023-12-18 at 10 59 12 AM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/85581471/bc4458a2-0638-442c-9de1-0eeccebb26d0)

## UX considerations
Governance-wise, there is some sort of congressional requirement to retain data in VA.gov for a set amount of time. We do not know the specifics of the requirement. This may need to be taken into consideration when developing a plan for how to modify this panel. Confer with @davidconlon re: what the governance rule is, specifically.

## Acceptance Criteria

- [x] Provide an alternate FE treatment for what should appear in "View other times for this event" [Figma treatment](https://www.figma.com/design/59V8ijSemGWGZCxWTHwplm/Events-Past-Events-Filtering?node-id=2040-8969)
- [x] UX review by Amanda K
- [ ] Engineering ticket is created to implement the UX update

**Comment by jilladams** [comment]
@timcosgrove ticket for the phenomena here. I know you noted that AP will need to rebuild this template, and that with some guidance, your team could address this in the Next rebuild. Feel free to spell out your proposed changes here, and I think the right next order of ops would be to get @thejordanwood to review and vet the ideas with Amanda K.

**Comment by jilladams** [comment]
@timcosgrove for this particular issue, talked to @davidconlon about it briefly. Some notes: 
1. No known timeline for moving Events off of Public Websites.  
2. In Dave's opinion, this is under the hood a question for Erika re: investing AP time in improving templates, vs. lift/shifting them.

He suggested he & Erika should co-own making a govvie call, so if you wanna chat with Erika about it and she can pull Dave in as needed?

**Comment by cmmerrill** [comment]
@FranECross @jilladams I don't believe this is still an issue? The current experience I have displays all future events under the accordion 'View other times for this event' (images attached); is there a specific use case the past events are still happening? And if so, is it more of a logic to display only future events? 
![Screenshot 2024-06-13 at 9 44 01 AM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/168835398/616241b8-370e-4d3f-a6ae-67e1220a2d28)
![Screenshot 2024-06-13 at 9 44 13 AM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/168835398/4584cb59-8fff-4f86-a1d5-f913887bd414)

**Comment by cmmerrill** [comment]
I reviewed this with UX @davidmpickett @thejordanwood @laflannery , made some updates to the accordion pattern with past/future events, as well as updated the links to other times of recurring events to solve some breaks/accessibility issues. Reviewed with @aklausmeier today and approved. Will update final designs and annotate for handoff and close once posted.

**Comment by jilladams** [comment]
@FranECross FYI I think we repurosed this ticket for UX, and will need an eng ticket to do the work that comes out of this, added to ACs.

**Comment by cmmerrill** [comment]
@FranECross link to FE annotations added. UX is complete, unless mods are needed. Thank you!

**Comment by FranECross** [comment]
Engineering [ticket](https://app.zenhub.com/workspaces/vagov-sitewide-product-team-6645154188a81a1f7a0a9464/issues/gh/department-of-veterans-affairs/va.gov-cms/18440) created
