### ISSUE TITLE
Content Deploy Builds Broken 

### ISSUE THREAD

**Issue by ElijahLynn** [department-of-veterans-affairs/va.gov-cms#1647]
The content build trigger to Jenkins is broken and appears to be due to a Jenkins upgrade and the way CSRF is enabled. We are getting error 403 in logs:

> No valid crumb was included in request for /job/deploys/job/vets-gov-autodeploy-vets-website/buildWithParameters by va-cms-bot. Returning 403.

Discussing here > https://dsva.slack.com/archives/CBU0KDSB1/p1588196351228700

**Comment by ElijahLynn** [comment]
@tskinn Resolved it by following the upgrade changelog notes:

> Responses to POST requests that do not set a CSRF crumb/token may in very rare cases change in unexpected ways due to the fix for SECURITY-1774. In case of problems with such requests, administrators can disable this security fix by setting the system property hudson.security.csrf.CrumbFilter.UNPROCESSED_PATHINFO to true.
> source: https://www.jenkins.io/doc/upgrade-guide/2.204/#upgrading-to-jenkins-lts-2-204-6

**Comment by indytechcook** [comment]
I'm closing this issue for https://github.com/department-of-veterans-affairs/va.gov-cms/issues/1647 since it's already fixed :)
