### ISSUE TITLE
Write KB-related messaging for study candidates and participants (8/?)

### ISSUE THREAD

**Issue by joagnitti** [department-of-veterans-affairs/va.gov-cms#16489]
## User Story or Problem Statement
In addition to the initial recruitment email, we need to also craft a followup (nudge) email, thank you email, and blurb for the calendly event description.

## Acceptance Criteria
- [x] Nudge email has been written
- [x] Thank you email has been written
- [x] Calendly blurb has been written
- [x] All 3 messages have been sent to PO and PM to review

## Team
Please check the team(s) that will do this work.

- [x] CMS Team
- [ ] Public Websites
- [ ] Facilities
- [ ] Accelerated Publishing

**Comment by joagnitti** [comment]
@EWashb and @maortiz-27-80 Hey Erika and Marcia! Here are the remaining messages (from "Thank you" on, in the doc) I wanted to get your eyes on. I used the same template as for the alt text study, so if the messaging looks slightly familiar, that's why. If you have any feedback, you can leave them as comments in the doc. Thank you! https://cityfriends-my.sharepoint.com/:w:/g/personal/joannagnitti_cityfriends_onmicrosoft_com/Edeq3VhXVfZOtZALCrul84wBo2PlpFobMXtStd4NXGzM0g?e=oXHuiy

**Comment by EWashb** [comment]
These all look great! One thing to keep in mind is that you might want to include your VA email. It is often viewed favorably by outside teams when we have our VA email as a contact method. It also legitimizes our touchpoint.
