### ISSUE TITLE
Add audit views to the audit menu

### ISSUE THREAD

**Issue by omahane** [department-of-veterans-affairs/va.gov-cms#16481]
## Problem Statement
We have several content audit Views that do not have any links to them in a menu, so nobody knows they are there. They only exist for people who know the url directly (likely no one)

## User Story
Audit views should be accessible through the [content audit menu](https://prod.cms.va.gov/admin/content/audit)

## Problem statement
As these are currently, you have to **know** the URL, as users don't have any way to arrive at them via the UI. 

## Acceptance Criteria
- [x] The following views are linked from the [content audit menu](https://prod.cms.va.gov/admin/content/audit):
  - [x] centralized_content_paragraphs ([edit](http://va-gov-cms.ddev.site/admin/structure/views/view/centralized_content_paragraphs))
  - [x] vamc_top_task_page_revisions ([edit](http://va-gov-cms.ddev.site/admin/content/audit/vamc-top-task-page-revision-histories))
  - [x] section_export ([edit](http://va-gov-cms.ddev.site/admin/content/audit/sections-hierarchy))
  - [x] detail_page_url_audit_and_bulk_udpate ([edit](http://va-gov-cms.ddev.site/admin/content/audit/vamc-detail-pages))

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [ ] `Public Websites`
- [x] `Facilities`
- [ ] `User support`

**Comment by swirtSJW** [comment]
This has been merged and should go to prod tomorrow (last deploy of the year) .  It is ultra low risk so no concerns.

**Comment by xiongjaneg** [comment]
Verified in prod
<img width="1473" alt="Screenshot 2023-12-27 at 10 48 24 AM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/73648238/d095bfea-ed35-42ef-9f67-dd183d1c05ba">
