### ISSUE TITLE
Spike: Support Lovell Cerner (Oracle health) implementation

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-cms#16485]
## Description
The Facilities team has been informed that Lovell plans to implement Cerner(Oracle Health) in early March 2024. They will be the last of the DoD facilities to implement.

We need to 
- understand the standard tasks for this implementation as roll-out for VA facilities is expected to resume in the future 
- understand the implications to Lovell specifically

## Background
Lovell is publicizing March 9, 2024 as the date for transition. 

### Tricare locations

- MHS GENESIS and the MHS GENESIS Patient Portal are replacing TRICARE Online, including the patient portal and secure messaging. 
- This will impact the following top tasks
   - View health information, including laboratory and radiology results
   - Schedule appointments
   - Communicate securely with your care team
   - Request prescription renewals
   - Complete intake and screening forms in advance of appointments
   - Access a health library

**Additional info**
- [Lovell Tricare info page](https://www.va.gov/lovell-federal-health-care-tricare/programs/electronic-health-record-modernization-ehrm/) 
- [MHS Genesis info page](https://www.health.mil/Military-Health-Topics/Technology/MHS-GENESIS)
- [MHS Genesis patient portal](https://my.mhsgenesis.health.mil/)

---

### VA locations

Once the Lovell FHCC site goes “live” with the federal EHR system, Veterans will manage their healthcare online via My VA Health
This will impact the following top tasks
- View health information, including laboratory and radiology results
- Schedule appointments
- Communicate securely with your care team
- Request prescription renewals

**Additional info**
- [Lovell VA info page](https://www.va.gov/lovell-federal-health-care-tricare/programs/electronic-health-record-modernization-ehrm/) 
- [My VA Health](https://patientportal.myhealth.va.gov/)
- This discovery should also be used to inform #12942. Top task links will be updated as functionality moves from MHV into VA.gov so that Veterans will have a seamless experience from their VA Medical center pages to managing their healthcare online. 

## Engineering resources
- [Electronic health records (EHR) system changes](https://prod.cms.va.gov/electronic-health-records-ehr-system-changes)
- [How to set up a VAMC's Oracle Health (formerly Cerner) integration within the VA.gov health care portals: hard coded data and CMS data](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/public-websites/healthcare-widget-support/how_to_set_up_vamc_cerner_within_va_health_care_portals.md)

## Acceptance criteria
- [x] Resources are reviewed.
- [x] Engineers with previous Cerner experience are consulted.
- [x] Follow-up tickets are stubbed or PM is tagged to stub them.

**Comment by maxx1128** [comment]
@mmiddaugh @ryguyk and I had a good discussion about the needed changes and any remaining questions about this ticket. The executive summary is:

* The "Manage Your Health Online" section (below) is currently hidden for Lovell TRICARE pages (src/site/layouts/health_care_region_page.drupal.liquid#55). It will need to be made visible for them

<img width="773" alt="Screen Shot 2024-01-12 at 1 00 22 PM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/10790736/d45adbd0-f101-43a0-b5c0-aa670c7cc9ea">

* The links in this section will need to check if a page is a Lovell TRICARE page and if Cerner is on. If they both are, the `topTaskUrl` filter will need to add additional logic that changes these links to the MHS Genesis links. It will just need to build on the existing conditional logic.
* The links on the template should make any needed TRICARE-specific changes, like changing visible instances of "VA" to "TRICARE" as needed.

### Questions that need Answering

1. What are the specific MHS Links that need to be used for each link label?
2. What was the specific reason that these links were hidden on TRICARE pages? Will they still need to be hidden from TRICARE pages under some circumstances, or will this change mean they can always be visible?
3. Do some of the six links in question need to be hidden under specific conditions, or can all six always remain visible together like they do now?
4. How much will me need to coordinate with public websites and similar Cerner changes they've made on their widget?

Michelle is waiting to hear back from a Lovell contact that she can run these questions by. Once they're answered, then there should be enough information to write out a ticket.

**Comment by maxx1128** [comment]
This ticket is currently blocked by waiting for answers to Michelle's questions for her Lovell contact. Once those are answered, this should be either ready or nearly ready to close and stub out 1-2 tickets for the front-end.

**Comment by maxx1128** [comment]
[A concern was raised in this Slack thread](https://dsva.slack.com/archives/C0190MTGNUE/p1706583840319089?thread_ts=1706556021.923479&cid=C0190MTGNUE) about a concern about the links for contacting doctors/refilling prescriptions being updated in advance of facilities being marked as "Cerner" in production; any time gap between a facility being marked as “cerner” in production and having their feature links updated is unacceptable. But we currently have no built-in functionality to avoid this. Wes recommends we check out cerner_staged as a way to tell if a facility will be Cerner in the near future, and use that as a check for adding the updated feature links in production ahead of the cutover.

I’m looking at where we use cerner_staged, and the code does this check: “if a facility is published as Cerner, or its cerner_staged in a non-prod environment, then it will use the new Patient Portal feature links ([src/site/filters/liquid.js:1646-1674](https://github.com/department-of-veterans-affairs/content-build/blob/main/src/site/filters/liquid.js#L1646-L1674)). If we removed that check for a non-production environment, then all the staged cerner facilities would get the updated feature links in production before the cutoff. So it looks like that could solve the problem.

```javascript
if (flag === 'cerner' || (flag === 'cerner_staged' && isNotProd))     // Remove isNotProd
```

**Comment by xiongjaneg** [comment]
From 16th minute:

From Max: Manage your experience box: hidden, hard codedly, on Tricare. Could it be restored on Tricare? Yes, with a code change.

Re: whether it could be restored on a subset of Facilities: should be possible, but could hard code the visiblity by Facility ID. (Possible but brittle)

From Steve: For cerner value: could add a 4th value to the CMS to do wat we actually need without corrupting meaning of cerner_staged.

**Comment by jilladams** [comment]
Re: usage of `cerner_staged`: https://dsva.slack.com/archives/C0190MTGNUE/p1706633034776289?thread_ts=1706556021.923479&cid=C0190MTGNUE
> The  cerner_staged flag is still used. It makes the Cerner behavior evident in non-production environments intentionally for the specific purpose of testing by teams and stakeholders in staging. Changing the way this setting works could impact functionality with wide implications.
> We propose another option. An additional state can be added to the toggle and designed to fit your need, keeping the existing settings clean for their intended use.

**Comment by xiongjaneg** [comment]
@jilladams Let's close this. I'll create a ticket stub to talk through findings and subsequent work.

**Comment by xiongjaneg** [comment]
@xiongjaneg to check on the thread about staging and if it's still needed

**Comment by xiongjaneg** [comment]
According to the [thread on mobile app transition for Lovell Cerner](https://dsva.slack.com/archives/C0190MTGNUE/p1706639475979239?thread_ts=1706556021.923479&cid=C0190MTGNUE), the solution is being pursued in the EHR, so our staging option doesn't appear needed at this time.
