### ISSUE TITLE
Redirect Request: Form 26-4555 SAH

### ISSUE THREAD

**Issue by jennymayoco** [department-of-veterans-affairs/va.gov-cms#16493]
### Instructions
- Requests must be submitted **AT LEAST** 2 weeks in advance.  Some requests take a significant amount of time and coordination to implement, so start the process as soon as you know you will need one. 
- This issue will be used from initial request through implementation to ensure all individuals working on this are notified of status updates.  Please do not create multiple issues to track differnt steps.
- It is your responsibility to notify VA stakeholders as appropriate.  

### Type of request
- [x] We are retiring or taking down a page and need to redirect the URL (complete redirect section). **This is temporary 302 redirect request.**
- [ ] We are changing the URL of an existing page (complete redirect section)
- [ ] We need a custom vanity URL (complete vanity URL section)

### Implementation date
When does this request need to be live?
Choose one:
- [ ] On a specific date, connected to a program or publishing requirement. **DATE:**
- [ ] Any day prior to a deadline/latest possible date. **DEADLINE:** 
- [ ] Any day after an earliest possible date. **EARLIEST DATE:**
- [ ] During a specific date range: ***EARLIEST DATE TO LATEST DATE:***
- [x] No hard timing requirements, publish when possible.

### Redirects 
Current URL  |  Redirect Destination or New URL
---  |  ---
https://www.va.gov/housing-assistance/disability-housing-grants/apply-for-grant-form-26-4555/introduction **and all child pages (temp 302 redirect)** | https://www.va.gov/housing-assistance/disability-housing-grants/how-to-apply/

### Vanity URLs 
Vanity URL  |  Landing page
---  |  ---
requested URL | landing page URL

**Link to campaign landing page request issue:**

### Process, Roles and Responsibilities
- [ ] Requesting team: Above information is provided
- [ ] Requesting team: All appropriate VA stakeholders are notified as appropriate
- [x] IA: Request is vetted and documented and implementation plan is clear 
- [x] IA: Request is assigned to appropriate team for implementation 
- [ ] Implementation team: Work is complete
- [ ] Implementation team: Validated in production
- [ ] Requesting team: Validates everything is correct in production and closes ticket

**Comment by chriskim2311** [comment]
Code complete pending merge

**Comment by randimays** [comment]
Merged; will deploy next Weds morning (Jan 10) unless we request an OOB deploy.

**Comment by chriskim2311** [comment]
@jennymayoco This has made it to production as of yesterday. Let me know if you see any issues thanks!

**Comment by jilladams** [comment]
@chriskim2311 when I try to ping https://www.va.gov/housing-assistance/disability-housing-grants/apply-for-grant-form-26-4555/introduction, I get a 404 with some busted css -- 
![Screenshot 2024-01-11 at 9 22 27 AM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/85581471/8abc6057-7e4d-45b7-a38e-a872a741c551)

Could you or @randimays take a look today?

**Comment by jilladams** [comment]
@jennymayoco @tbaker1026 the temporary redirect is now live and verified in prod. CLosing, but please reopen if you have any issues. When you're ready for us to update and remove this temp redirect, please just cut a new ticket for Public Websites.

**Comment by jennymayoco** [comment]
thank you @jilladams!

**Comment by tbaker1026** [comment]
@jilladams at the latest we will go live with this form on 4/30 as long as testing will go well.  I will update this ticket to confirm the date.

**Comment by tbaker1026** [comment]
@jilladams How long of a notice do you need to implement the redirect.  If we go live on 4/30 (tentative), what day do you need to know prior to that to implement the redirect?  Thank you

**Comment by tbaker1026** [comment]
@jilladams The launch date for this form got pushed out - I don't have an exact date but it won't be 4/30 - l will let you know as I know more about the date.

**Comment by FranECross** [comment]
Thanks for the update, @tbaker1026 !
