### ISSUE TITLE
URL Change for: Southwest VA Clinic

### ISSUE THREAD

**Issue by stefaniefgray** [department-of-veterans-affairs/va.gov-cms#16506]
⚠️  NO URL RE-DIRECT NEEDED ⚠️ 

Simply needs to be updated within Lighthouse CSV / canonical URL change

-----
### Implementation date
When does this request need to be live:
Once new clinic ticket is completed: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16505

### Instructions for canonical URL change
- [x] Verify that the new URL for the facility is published and accessible on VA.gov.
- [x] Update the [CSV in Lighthouse](https://github.com/department-of-veterans-affairs/lighthouse-facilities/blob/master/facilities/src/main/resources/websites.csv) with the changed URL, maintaining the sorted order of the Facility API IDs.
- [x] Create a PR in the [lighthouse-facilities repo](https://github.com/department-of-veterans-affairs/lighthouse-facilities), tagging the Lighthouse team.
- [x] Post a message in the #cms-lighthouse channel in Slack, with an @mention to a Lighthouse team member.
- [x] Add the "Awaiting CSV" flag to the facility node with a revision log message that includes a link to this ticket.
- [x] Validate that the change has deployed by checking that the Facility Locator has been updated with the new url.
- [x] Update this ticket with a comment that the CSV change has been deployed.
- [x] Remove the "Awaiting CSV" flag to the facility node with a revision log message that includes a link to this ticket.

#### URL change example (update with actual ID and URL)
| Facility API ID  |  Full VA.gov URL |
| ---  |  --- |
| vha_671GW | https://www.va.gov/south-texas-health-care/locations/southwest-va-clinic |

**Comment by omahane** [comment]
The request for a URL addition is here: https://dsva.slack.com/archives/C02BTJTDFTN/p1703792170821799?thread_ts=1703179501.227829&cid=C02BTJTDFTN

**Comment by omahane** [comment]
The CSV has been deployed and the change is now reflected in production.

**Comment by omahane** [comment]
This can be closed.
