### ISSUE TITLE
Accessibility review of new Facility Services view

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#16509]
## Description
Facilities created a new view for Facility Services in https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16152 . We missed the A11y review AC in that ticket, so have ticketed this separately for A11y follow up. 

View: https://prod.cms.va.gov/admin/content/audit/facility-services

## ACs

- [x] a11y review is provided
- [x] Any necessary follow up is created as a Drupal ticket

**Comment by laflannery** [comment]
No new issues, only existing ones that are already ticketed
