### ISSUE TITLE
[UPDATE] "Grief and bereavement counseling" to include VBA fields

### ISSUE THREAD

**Issue by davidmpickett** [department-of-veterans-affairs/va.gov-cms#16503]
### Which Taxonomy is this term for?

VA Service taxonomy

### Link to existing term

https://prod.cms.va.gov/health-care/grief-and-bereavement-counseling

### Rationale for adding this term

Grief and bereavement counseling was identified as a core service by some Regional offices.

### Which products will this term impact?

VBA Regional Office

### Have stakeholders from impacted products been consulted?

Yes

### Have you drafted content for all the relevant subfields?

No

### Acceptance Criteria

- [ ] Content for subfields is drafted in Drupal by Product team
- [ ] Content is reviewed by relevant taxonomy governance body
- [ ] Content is reviewed by relevant stakeholders
- [ ] (List any necessary review and approval steps here)
- [ ] Term is published

**Comment by mmiddaugh** [comment]
@davidmpickett , based on most recent RO conversations, this is ready to be added and reviewed by CAIA.

## Grief and bereavement counseling
- VBA Type of care: Other services (suggested as this service is applicable to all audiences) 
- (Revised) proposed VBA National description: We’re here to support you if someone close to you has died or you’re adjusting to a difficult life change. We can help you understand the benefits you may be eligible for and connect you to counseling or other support, such as outreach and referral services.

**Comment by mmiddaugh** [comment]
done
