### ISSUE TITLE
Redirect Request: Foreign Medical Program pages

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-cms#16507]
### Instructions
- Requests must be submitted **AT LEAST** 2 weeks in advance.  Some requests take a significant amount of time and coordination to implement, so start the process as soon as you know you will need one. 
- This issue will be used from initial request through implementation to ensure all individuals working on this are notified of status updates.  Please do not create multiple issues to track differnt steps.
- It is your responsibility to notify VA stakeholders as appropriate.  

### Type of request
- [x] We are retiring or taking down a page and need to redirect the URL (complete redirect section)
- [ ] We are changing the URL of an existing page (complete redirect section)
- [ ] We need a custom vanity URL (complete vanity URL section)

### Implementation date
When does this request need to be live?
Choose one:
- [ ] On a specific date, connected to a program or publishing requirement. **DATE:**
- [ ] Any day prior to a deadline/latest possible date. **DEADLINE:** 
- [x] Any day after an earliest possible date. **EARLIEST DATE:** Once these pages are live. This should be in the coming days but I don't have a set date yet. Will comment in the ticket when they're live.
- [ ] During a specific date range: ***EARLIEST DATE TO LATEST DATE:***
- [ ] No hard timing requirements, publish when possible.

### Redirects 
Current URL  |  Redirect Destination or New URL
---  |  ---
https://www.va.gov/COMMUNITYCARE/programs/veterans/fmp/index.asp | https://www.va.gov/health-care/foreign-medical-program/ (Updated 12/4 - JM)
https://www.va.gov/COMMUNITYCARE/programs/veterans/fmp/fmp_benefits_claims.asp / https://www.va.gov/COMMUNITYCARE/programs/veterans/fmp/fmp-benefits-claims.asp (Updated 12/4 - JM) | https://www.va.gov/resources/getting-care-through-the-foreign-medical-program/ (Updated 12/19 - JM)

**NOTE:** /communitycare is a teamsite using the injected header, so this will be a [client-side redirect](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/redirect-implementation-strategy.md#4-page-level-cross-domain-redirects-from-subdomains-subdomainvagov-to-wwwvagov)

**Link to campaign landing page request issue:**

### Process, Roles and Responsibilities
- [ ] Requesting team: Above information is provided
- [ ] Requesting team: All appropriate VA stakeholders are notified as appropriate
- [ ] IA: Request is vetted and documented and implementation plan is clear 
- [ ] IA: Request is assigned to appropriate team for implementation 
- [ ] Implementation team: Work is complete
- [ ] Implementation team: Validated in production
- [ ] Requesting team: Validates everything is correct in production and closes ticket

**Comment by jilladams** [comment]
NOTE: /communitycare is a teamsite using the injected header, so this will be a [client-side redirect](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/redirect-implementation-strategy.md#4-page-level-cross-domain-redirects-from-subdomains-subdomainvagov-to-wwwvagov)

**Comment by jilladams** [comment]
Moved this ticket to our repo, set it up for next refinement. We have a sprint starting 1/3, so can prioritize it into that sprint, just let us know when you know more about launch dates.

**Comment by jennymayoco** [comment]
@jilladams pages are live! apologies for the confusion. when the ticket was first opened, the pages weren't live yet and I had totally missed the original note under implementation date section when updating this.

**Comment by jilladams** [comment]
@jennymayoco is it still ok if redirects go in the new year? Or we should try to get it out before code freeze this week? cc @FranECross

**Comment by jennymayoco** [comment]
@jilladams - looping in @DanielleThierryUSDSVA to get insight from her on this timeline!

**Comment by jilladams** [comment]
Danielle confirmed this can ship after the break: https://dsva.slack.com/archives/C01K37HRUAH/p1703187901788289

**Comment by chriskim2311** [comment]
Confirmed all 3 redirects are working as expected on prod. Please reach out if you see any issues

**Comment by FranECross** [comment]
Closed the loop with stakeholders in the slack channel https://dsva.slack.com/archives/C01K37HRUAH/p1703187901788289

**Comment by jilladams** [comment]
Verified in prod, closing! Feel free to reopen if y'all find any issues.
