### ISSUE TITLE
Remove usage of FEATURE_EVENT_OUTREACH_CHECKBOX from content-build

### ISSUE THREAD

**Issue by dsasser** [department-of-veterans-affairs/va.gov-cms#16517]
## Description

This feature toggle `FEATURE_EVENT_OUTREACH_CHECKBOX` was removed from the CMS in #16215, yet content-build is still referencing this feature toggle. This is causing content-builds to faile, so we need to remove it from logic relying on it on the FE. 

## Acceptance criteria
- [ ] Content-build builds succeed

**Comment by randimays** [comment]
@dsasser should this be in Review? [PR](https://github.com/department-of-veterans-affairs/content-build/pull/1836)
