### ISSUE TITLE
Enable SiteImprove deep linking feature

### ISSUE THREAD

**Issue by ariperez** [department-of-veterans-affairs/va.gov-cms#16521]
## Background

Enable [CMS Deeplinking](https://help.siteimprove.com/support/solutions/articles/80000448272-what-is-cms-deeplinking-). This process involves submitting a few urls to the SiteImprove customer support team who will enable it on their backend. 

Note: that it appears this goes live only on production, therefore it may not be testable until after approving using of SiteImprove and deploying to prod which will occur after completing #15432

https://help.siteimprove.com/support/solutions/articles/80000448431-how-do-i-enable-cms-deeplinking-

## Acceptance Criteria

- [ ] [Enable deep linking through Siteimprove Customer Support ](https://help.siteimprove.com/support/solutions/articles/80000448431).  Request with two (2) examples, each example with: (1) Live URL and (2) CMS URL.
- [ ] Validate deep linking works on the production website.

**Comment by ariperez** [comment]
@maortiz-27-80 Here is the info we need to request for DeepLinking...

```
Drupal Version 10 

Edit - https://prod.cms.va.gov/atlanta-health-care/locations/trinka-davis-veterans-village
Live - https://va.gov/atlanta-health-care/locations/trinka-davis-veterans-village

Edit - https://prod.cms.va.gov/atlanta-health-care/locations/fort-mcpherson-va-clinic
Live - https://va.gov/atlanta-health-care/locations/fort-mcpherson-va-clinic
```

Note: After discussing with @laflannery and engineering, we are submitting urls that don't take the user directly to the edit page, but instead to the view page, where the editor can then click edit.  

<img width="1711" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/2553469/11e5dd5a-8a27-4c13-9ec9-834ed2d6a0b4">

**Comment by BerniXiongA6** [comment]
Hey @ariperez could you size the ticket? Thanks for writing this up! cc: @maortiz-27-80

**Comment by maortiz-27-80** [comment]
Note: URLs submitted to Siteimprove 12/22.  cc @BerniXiongA6 @EWashb

**Comment by maortiz-27-80** [comment]
Per Siteimprove 12/22:

> Deeplinking has now been set up for your site. It should be visible to you in the platform within the hour.
> 
> You can verify this by clicking the CMS button next to the page name/URL in the platform. If you see any problems, please reply to this email to reopen the ticket.

@laflannery - Let's circle back early next week to discuss next steps.  cc: @ariperez @BerniXiongA6  @EWashb

**Comment by maortiz-27-80** [comment]
- What is the new feature (deep linking)?
- How/why is this an upgrade from the previous experience?
- How can editors access this new feature?

**Comment by maortiz-27-80** [comment]
Sent to Siteimprove via email 12/27:

Our accessibility lead, Laura Flannery has logged in as Laura.flannery@va.gov and has read-only access (role).  Based on the [Siteimprove link](https://help.siteimprove.com/support/solutions/articles/80000448431-how-do-i-enable-cms-deeplinking-) provided, we tried to validate the setup of deep linking on our site.  

When navigating to accessibility issues via the Siteimprove dashboard, we do not see any option to click through a “CMS” Deeplinking button that we expect to see next to the icon for the outbound link that displays in the URL row.  See filename: accessibility_issue_01

Secondly, when clicking through the URL link, there is a “Set up a direct link to your CMS” tab that displays at the top of the detail page.  We expect to see a tab that says, “Edit in CMS”.  See filename: accessibility_issue_detail_page_02.

Please advise. 

<img width="1721" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMldJQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--146f6ca06faefd1a0cac1f8aa772beb1a7cd916a/accessibility_issue_01.png" alt="accessibility_issue_01.png" />
<img width="1776" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMmFJQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ef48b6dbcbe23db87e3078b35e660a627df27776/accessibility_issue_detail_page_02.png" alt="accessibility_issue_detail_page_02.png" />

cc: @ariperez @laflannery @BerniXiongA6 @EWashb

**Comment by maortiz-27-80** [comment]
Siteimprove enabled deep linking for https://www.va.gov/atlanta-health-care/.  I can confirm this is working when logging in to the Siteimprove dashboard.  See attached. 

<img width="1573" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNlNMQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--865fa45503bd5d9fd3cf7ad19a3d0c16cdda32cc/atlanta_deeplink_01.png" alt="atlanta_deeplink_01.png" />
<img width="1648" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNldMQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--06211f1598436d63c70361813d9abe499095f754/atlanta_deeplink_02.png" alt="atlanta_deeplink_02.png" />

cc: @BerniXiongA6 @ariperez @laflannery @EWashb

**Comment by laflannery** [comment]
@maortiz-27-80 is there anything you need me to do now that we have confirmed we have this working? Should we go back to [the questions you posed previously](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16521#issuecomment-1870350102)?

**Comment by maortiz-27-80** [comment]
hi, @laflannery .  hold for now.  i'd like to confirm that we have fulfilled our commitment and that vha-dm should be testing this functionality.  cc: @BerniXiongA6 @EWashb

**Comment by EWashb** [comment]
I have spoken with Justin and asked him to test out the deeplinking functionality. Also, I told him to check with Siteimprove to see if there is some associated cost with deeplinking every facility. I would like for him to check that before we look into any additional links to other facilities.

**Comment by maortiz-27-80** [comment]
This ticket is complete.  No further action required.  A new ticket, #16651 has been created if the CMS team needs to provide additional URLs for deep linking.  Closing this ticket.  Thanks! - Marcia cc: @BerniXiongA6  @ariperez @laflannery @EWashb @ndouglas
