### ISSUE TITLE
IL: Deprecate 2024 in-page data refresh alert

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#16528]
## Description

In https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16458, we created an in-page warning alert to notify Veterans that data has been refreshed in Income Limits for 2024.

We need to establish timeline to remove that alert, and then remove it when it's time.

PR That added the alert: https://github.com/department-of-veterans-affairs/vets-website/pull/27232
Commit = beac48d -- this could be as simple as git reverting that commit

## ACs
- [ ] Income limits warning alert re: 2024 data is no longer visible

**Comment by jilladams** [comment]
@FranECross FYI i made this ticket to remove the Income Limits alert, once it's published in Jan and we know timing for pulling it back down.

**Comment by jilladams** [comment]
@davidconlon Do you have a sense how long you'd like this alert re: the refreshed Income Limits data to stay up? If it ships on Jan 2 or 3, shall we plan to take it down again in the following sprint / mid-Jan, or later?

**Comment by FranECross** [comment]
Deprecate in Mid March 2024

**Comment by randimays** [comment]
Successfully validated in production. Closing!
