### ISSUE TITLE
VBA db phone cleanup needed

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#16530]
## User Story or Problem Statement
The following VBA facilities have odd phone data that needs a second look.  These surfaced during Steve's work to normalize our phone numbers.

### No phones
- [x] [Veteran Readiness and Employment Office at San Marcos Vet Center](https://prod.cms.va.gov/san-diego-va-regional-benefit-office/locations/veteran-readiness-and-employment-office-at-san-marcos-vet-center)
  -  This is an archived location and is not present in Sandy's DB.
- [ ] [VetSuccess on Campus at University of Cincinnati](https://prod.cms.va.gov/vba-facilities/locations/vetsuccess-on-campus-at-university-of-cincinnati)
   - There are two archived locations with this name in CMS 
      - vba_325e is archived and is not present in Sandy's DB. 
      - vba_325h is archived, is not present in Sandy's DB but does have a listed phone number in the Locations and contact information block in CMS. 
- [ ] [VA Regional Benefit Satellite Office at Sheridan VA Medical Center](https://prod.cms.va.gov/vba-facilities/locations/va-regional-benefit-satellite-office-at-sheridan-va-medical-center)
   - There are two locations with this name in CMS. 
      - vba_442a is in draft, has a phone number in the Locations and contact information block, and is present in Sandy's DB. 
      - vba_666 is archived in CMS and is not present in Sandy's DB. 
- [ ] [VA Regional Benefit Satellite Office at Fort Wayne VA Medical Center](https://prod.cms.va.gov/vba-facilities/locations/va-regional-benefit-satellite-office-at-fort-wayne-va-medical-center-0)
   - There are three locations with this name in CMS. 
      - vba_326h is in draft, has a phone number in the Locations and contact information block,  and is present in Sandy's DB. Will look at format of phone number in DB given the format in CMS ( `e xt. 71327`) 
      - vba_610A4a is archived in CMS and not present in Sandy's DB.
      - vba_326b is archived in CMS and not present in Sandy's DB.
- [ ] [Seamless Transition Integrated Care Clinic (STICC) at Richard L. Roudebush VA Medical Center](https://prod.cms.va.gov/vba-facilities/locations/seamless-transition-integrated-care-clinic-sticc-at-richard-l-roudebush-va-medical-center)
     - There are two locations with this name in CMS
        - vba_326g is in draft, has a phone number in the Locations and contact information block, and is present in Sandy's DB.
        - vba_583 is archived and is not present in Sandy's DB.
- [ ] [VA Regional Benefit Satellite Office at Dayton VA Medical Center](https://prod.cms.va.gov/vba-facilities/locations/va-regional-benefit-satellite-office-at-dayton-va-medical-center)
      - There are two locations with this name in CMS
        - vba_325g is in draft, has a phone number in the Locations and contact information block, and is present in Sandy's DB.
        - vba_552a is archived and is not present in Sandy's DB.
- [ ] [VA Regional Benefit Satellite Office at Athens VA Clinic](https://prod.cms.va.gov/vba-facilities/locations/va-regional-benefit-satellite-office-at-athens-va-clinic)
     - There are two locations with this name in CMS
        - vba_325f is in draft, has a phone number in the Locations and contact information block, and is present in Sandy's DB.
        - vba_538GA is archived and is not present in Sandy's DB.
- [x] [Veteran Readiness and Employment Office at Oceanside VA Clinic](https://prod.cms.va.gov/san-diego-va-regional-benefit-office/locations/veteran-readiness-and-employment-office-at-oceanside-va-clinic)
     - This is an archived location and is not present in Sandy's DB.
- [x] [VA Regional Benefit Satellite Office at Loma Linda](https://prod.cms.va.gov/vba-facilities/locations/va-regional-benefit-satellite-office-at-loma-linda)
     - This is an archived location and is not present in Sandy's DB.

## Typoed extension `e xt.`
- [x] [VA Regional Benefit Satellite Office at Northern Colorado Outpatient Clinic](https://prod.cms.va.gov/denver-va-regional-benefit-office/locations/va-regional-benefit-satellite-office-at-northern-colorado-outpatient-clinic) 
- [x] [Veteran Readiness and Employment Office at Beckley VA Vet Center](https://prod.cms.va.gov/huntington-va-regional-benefit-office/locations/veteran-readiness-and-employment-office-at-beckley-va-vet-center) 
- [x] [VA Regional Benefit Satellite Office at The Net Center](https://prod.cms.va.gov/vba-facilities/locations/roanoke-regional-satellite-office-at-hampton) 
- [x] [VA Regional Benefit Satellite Office at Omaha VA Medical Center](https://prod.cms.va.gov/lincoln-va-regional-benefit-office/locations/va-regional-benefit-satellite-office-at-omaha-va-medical-center) 
- [x] [VA Regional Benefit Satellite Office at Scott County VA Clinic](https://prod.cms.va.gov/indianapolis-va-regional-benefit-office/locations/va-regional-benefit-satellite-office-at-scott-county-va-clinic) 
- [x] [VA Regional Benefit Satellite Office at Wakeman VA Clinic](https://prod.cms.va.gov/indianapolis-va-regional-benefit-office/locations/va-regional-benefit-satellite-office-at-wakeman-va-clinic) 
- [x] [VA Regional Benefit Satellite Office at Northport VA Medical Center](https://prod.cms.va.gov/new-york-va-regional-benefit-office/locations/va-regional-benefit-satellite-office-at-northport-va-medical-center)
- [x] [VA Regional Benefit Satellite Office at Franklin Delano Roosevelt Hospital](https://prod.cms.va.gov/new-york-va-regional-benefit-office/locations/va-regional-benefit-satellite-office-at-franklin-delano-roosevelt-hospital-0) 
- [x] [VA Regional Benefit Satellite Office at Castle Point VA Medical Center](https://prod.cms.va.gov/new-york-va-regional-benefit-office/locations/va-regional-benefit-satellite-office-at-castle-point-va-medical-center) 
- [x] [VA Regional Benefit Satellite Office at Manhattan VA Medical Center](https://prod.cms.va.gov/new-york-va-regional-benefit-office/locations/va-regional-benefit-satellite-office-at-manhattan-va-medical-center) 
- [x] [VA Regional Benefit Satellite Office at Fort Wayne VA Medical Center](https://prod.cms.va.gov/indianapolis-va-regional-benefit-office/locations/va-regional-benefit-satellite-office-at-fort-wayne-va-medical-center)
- [x] [VetSuccess on Campus at Pasadena City College](https://prod.cms.va.gov/los-angeles-va-regional-benefit-office/locations/vetsuccess-on-campus-at-pasadena-city-college)
- [x] [Vetsuccess on Campus at MiraCosta College](https://prod.cms.va.gov/san-diego-va-regional-benefit-office/locations/vetsuccess-on-campus-at-miracosta-college)
- [x] [Integrated Disability Evaluation System (IDES) and Pre-Discharge Claims Intake Site at Fort Novosel](https://prod.cms.va.gov/montgomery-va-regional-benefit-office/locations/integrated-disability-evaluation-system-ides-and-pre-discharge-claims-intake-site-at-fort-novosel)
- [x] [Vetsuccess on Campus at MiraCosta College](https://prod.cms.va.gov/san-diego-va-regional-benefit-office/locations/vetsuccess-on-campus-at-miracosta-college)
- [x] [Integrated Disability Evaluation System (IDES) and Pre-Discharge Claims Intake Site at Fort Novosel](https://prod.cms.va.gov/montgomery-va-regional-benefit-office/locations/integrated-disability-evaluation-system-ides-and-pre-discharge-claims-intake-site-at-fort-novosel)
- [x] [VetSuccess on Campus at Johnson County Community College](https://prod.cms.va.gov/wichita-va-regional-benefit-office-at-robert-j-dole-va-medical-center/locations/vetsuccess-on-campus-at-johnson-county-community-college)
- [x] [Veteran Readiness and Employment Office at Clarksburg VA Medical Center](https://prod.cms.va.gov/huntington-va-regional-benefit-office/locations/veteran-readiness-and-employment-office-at-clarksburg-va-medical-center)
- [x] [VetSuccess on Campus at Northwest Florida State College](https://prod.cms.va.gov/montgomery-va-regional-benefit-office/locations/vetsuccess-on-campus-at-northwest-florida-state-college)
- [x] [VA Regional Benefit Satellite Office at Marion VA Medical Center](https://prod.cms.va.gov/indianapolis-va-regional-benefit-office/locations/va-regional-benefit-satellite-office-at-marion-va-medical-center)
- [x] [Veteran Readiness and Employment Office at Augusta VA Medical Center](https://prod.cms.va.gov/atlanta-va-regional-benefit-office/locations/veteran-readiness-and-employment-office-at-augusta-va-medical-center)
- [x] [Veteran Readiness and Employment Office at Charleston VA Clinic](https://prod.cms.va.gov/huntington-va-regional-benefit-office/locations/veteran-readiness-and-employment-office-at-charleston-va-clinic)
- [x] [Veteran Readiness and Employment Office at Martinsburg VA Medical Center](https://prod.cms.va.gov/huntington-va-regional-benefit-office/locations/veteran-readiness-and-employment-office-at-martinsburg-va-medical-center)
- [x] [VetSuccess on Campus at Tidewater Community College Chesapeake Campus](https://prod.cms.va.gov/roanoke-va-regional-benefit-office/locations/vetsuccess-on-campus-at-tidewater-community-college-chesapeake-campus)
- [x] [VetSuccess on Campus at Tidewater Community College Portsmouth Campus](https://prod.cms.va.gov/roanoke-va-regional-benefit-office/locations/vetsuccess-on-campus-at-tidewater-community-college-portsmouth-campus) 
- [x] [VetSuccess on Campus at Tidewater Community College Virginia Beach Campus](https://prod.cms.va.gov/roanoke-va-regional-benefit-office/locations/vetsuccess-on-campus-at-tidewater-community-college-virginia-beach-campus) 
- [x] [VetSuccess on Campus at Old Dominion University](https://prod.cms.va.gov/roanoke-va-regional-benefit-office/locations/vetsuccess-on-campus-at-old-dominion-university)
- [x] [VetSuccess on Campus at Norfolk State University](https://prod.cms.va.gov/roanoke-va-regional-benefit-office/locations/vetsuccess-on-campus-at-norfolk-state-university)
- [x] [VA Regional Benefit Satellite Office at Norfolk](https://prod.cms.va.gov/vba-facilities/locations/roanoke-regional-satellite-office-at-norfolk)
- [x] [VetSuccess on Campus at Tidewater Community College Norfolk Campus](https://prod.cms.va.gov/roanoke-va-regional-benefit-office/locations/vetsuccess-on-campus-at-tidewater-community-college-norfolk-campus)

## Acceptance Criteria
- [ ] Testable_Outcome_X
- [ ] Testable_Outcome_Y
- [ ] Testable_Outcome_Z
- [ ] Requires design review
- [ ] Requires accessibility review

## Team
Please check the team(s) that will do this work.

- [ ] CMS Team
- [ ] Public Websites
- [x] Facilities
- [ ] Accelerated Publishing

**Comment by mmiddaugh** [comment]
Noting that I discovered 4 sets of facilities where two locations with the same name but different  facility ids are in draft in CMS and present in Sandy's DB. Will contact VBA for decisions on which should remain

> Integrated   Disability Evaluation System (IDES) Site at Joint Base Langley-Eustis | 314aa
> Integrated Disability   Evaluation System (IDES) Site at Joint Base Langley-Eustis | 314n
> 
> VA Regional Benefit Satellite Office at Franklin Delano Roosevelt Hospital | 306a
> VA Regional Benefit Satellite Office at Franklin Delano Roosevelt Hospital | 306g
> 
> VA Regional Benefit Satellite Office at Manhattan VA Medical Center | 306h
> VA Regional Benefit Satellite Office at Manhattan VA Medical Center | 306i
> 
> VetSuccess on Campus at Florida State College at Jacksonville | 317aa
> VetSuccess on Campus at Florida State College at Jacksonville | 317p
>

**Comment by swirtSJW** [comment]
The typoed space in the extension turned out to be caused by the migration.  It has been resolved already in the CMS migration.

**Comment by mmiddaugh** [comment]
Duplicate locations resolved per Office of Field Operations - except the two Joint Base Langley-Eustis IDES Sites. Will work to differentiate naming. This issue can be closed
