### ISSUE TITLE
Bug: Possible to create an Event with an invalid date, fails content-build

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#16545]
## Description

1. Content-build daily deploy failed due to an Event being created with an Invalid date
2. The recurring Event had a revision https://prod.cms.va.gov/node/64229/revisions/828924/view where a date was added, implying that Event did not originally contain a date.

Event node that broke the build: https://prod.cms.va.gov/node/64229/revisions/view/828924/828940/visual_inline

Slack thread with Devops who found the issue: https://dsva.slack.com/archives/C02VD909V08/p1703184206929399?thread_ts=1703012486.553909&cid=C02VD909V08

## Context
This is a recurring event, and may have gotten into this state from removing recurrences somehow. Dunno.

We have previously thought we fixed a similar issue: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15085

## ACs
- [ ] Events cannot be created without a valid date / time

**Comment by Becapa** [comment]
I think I was able to reproduce this locally by:

1. Set the Start and End date/time.
2. Check the box to make it recurring.
3. Set an 'Until' Date that comes before the 'Start' Date

On submission this will clear out any dates that were in the 'Start' or 'End' date/time fields and save the Event with those fields empty.
