### ISSUE TITLE
Change content release trigger for facility edits to depend on operating status field changes

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#1654]
## User Story or Problem Statement

Currently, editing any VAMC facility node triggers a content release. 

## Acceptance Criteria
* We only want VAMC facility edits to trigger a content release if the operating status fields have changes and the node is published. 

## Implementation steps
 * Update the build trigger module.

**Comment by swirtSJW** [comment]
I removed this from the timely facility status updates epic as it is not related to that work other than by content type.
