### ISSUE TITLE
Turn Maintenance mode on during deployments

### ISSUE THREAD

**Issue by indytechcook** [department-of-veterans-affairs/va.gov-cms#1655]
We need to test and turn maintenance mode back on during deployments.

**Comment by indytechcook** [comment]
Let's hold off on this until we remove all deadlocks

**Comment by ElijahLynn** [comment]
Potentially blocked on some sort of combo of 403 and/or infinite redirect loop.

**Comment by ElijahLynn** [comment]
I think we don't need this anymore, please re-open if we do. @indytechcook created a "deploy mode" which takes care of this.
