### ISSUE TITLE
[Events - FE] Expose CMS "registration required" field information from events to the front-end

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-cms#16578]
## Status 2024-01-25

The backend story is no longer blocking this one.

### User story

**AS A** Veteran, their caregiver, or other VA.gov users viewing events
**I WANT** to easily and clearly understand if I need to RSVP, Apply, or Register for the event I'm viewing
**SO THAT** I get complete, easily understood, and accurate information about events and aren't frustrated by my experience.

### Design

[BE Design](https://www.figma.com/file/8ZT1nnu8r2twbOlEhysnNp/Events?type=design&node-id=58-672&mode=design&t=HmIGHRyNt4KylqUl-0)
[FE Design](https://www.sketch.com/s/8ec18b80-a905-47fb-a217-5720450befa1)

## Acceptance criteria

- [x] Fran to inform Tim Cosgrove this work is upcoming
- [x] Inform Tim just before this is released

**AC1: FE displays Editor's choice for Call to Action of 'Register'**

**GIVEN** Editor has created an event where Registration is required
**AND** they click the checkbox for "Include information on how to join this event"
**WHEN** they choose the Call to action 'Register'
**AND** they click the checkbox for Registration is required for this event
**AND** they enter/choose all other required fields/information and Save
**THEN** the FE for the event displays the text "**Registration:** Required
**AND** the FE for the event displays "Register" as a link next to the green arrow

**AC2: Editor chooses Call to Action 'Reserve your spot', and indicates RSVP is required**

**GIVEN** Editor has created an event where an RSVP is required
**AND** they click the checkbox for "Include information on how to join this event"
**WHEN** they choose the Call to action 'Reserve your spot'
**AND** they click the checkbox indicating RSVP is required for this event
**AND** they enter/choose all other required fields/information and Save
**THEN** the FE for the event displays the text "**RSVP:** Required
**AND** the FE for the event displays "RSVP" as a link next to the green arrow

**AC3: Editor chooses Call to Action 'Apply', and indicates this action is required**

**GIVEN** Editor has created an event where submitting an application is required
**AND** they click the checkbox for "Include information on how to join this event"
**WHEN** they choose the Call to action 'Apply'
**AND** they click the checkbox indicating applying is required for this event
**AND** they enter/choose all other required fields/information and Save
**THEN** the FE for the event displays the text "**Apply:** Required
**AND** the FE for the event displays "Apply" as a link next to the green arrow

**Comment by FranECross** [comment]
@timcosgrove Keeping you in the loop on this upcoming work. Please let us know if you have any questions. Thanks! cc @jilladams

**Comment by FranECross** [comment]
@randimays Does what Michael confirmed in the comment above unblock the frontend ticket? Thank you!

**Comment by randimays** [comment]
@FranECross Yes, I believe it does!

**Comment by jilladams** [comment]
Closing!

**Comment by jilladams** [comment]
(Doh, sorry - this is the FE ticket, thought it was the CMS ticket. Reopened.)

**Comment by randimays** [comment]
Validated successfully in prod! Refer to [this PR's description](https://github.com/department-of-veterans-affairs/content-build/pull/1997) for the URLs we tested for all scenarios. Closing!

**Comment by jilladams** [comment]
Noting: Events are in AP as well. AP were tagged on PR here. 
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17735 has been created and Tim has pulled that in on AP side to achieve parity.
