### ISSUE TITLE
Bug: CLP will not save with only Reusable Q&As associated

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#16575]
## Description
We added Reusable Q&A to CLPs in  #10938. However, currently you cannot successfully save a CLP with only Reusable Q&As associated. The CLP form throws an error related to Page-specific Q&As, and 3 of those must be added before the node form will save. 

### To reproduce: 
On Staging / local / Tugboat: 
* Visit /node/add/campaign_landing_page
* Populate required fields
  * Section
  * Page title
  * Primary CTA link / text
  * hero image
  * Why this matters
    * Introduction
    * Audiences > choose at least 1 
  * What you can do
    * Heading
    * Introduction
    * What you can do promo - choose at least 1
  * VA Benefits
    * Select Benefit Hub(s) and choose at least 1
* **Then:** FAQs > expand, select "Enable this page segment"
* Page-Specific Q&A:  leave empty
* Reusable Q&A > Add Reusable Q&As > in the modal that opens, select a RQA using the checkbox next to title, then click Select Q&As button to save & close the modal
* Enter revision log message
* Save

**Current behavior:** 
Screen shows an error at form top, "1 error has been found: [Page-Specific Q&A]". No error message is present in the FAQ > Page-Specific Q&A section of the page to indicate what the error is. Form does not save. 

**Expected behavior:** 
We need to define it, with input from Drupal engineering on what validations are possible / reasonable between Page-specific & Reusable Q&As.

## KB Article
https://prod.cms.va.gov/help/campaign-landing-pages/how-to-manage-campaign-landing-pages 
KB specifies: "FAQs: Add the FAQ segment when you have a minimum of three (max 10) frequently asked questions related to your campaign that will provide answers and additional context for your audience."

We need to update this language to reflect validation changes.

## ACs
- [ ] CLP form can be saved with any combination of 3 total page-specific _and/or_ Reusable Q&As associated
  - [x] AC has been technically vetted by Drupal engineering as feasible
- [x] KB article is updated to be specific about requirements for Q&As: https://prod.cms.va.gov/help/campaign-landing-pages/how-to-manage-campaign-landing-pages
- [ ] CAIA (Danielle) is updated when fix is shipped

**Comment by jilladams** [comment]
@DanielleThierryUSDSVA reported in Slack here: https://dsva.slack.com/archives/C52CL1PKQ/p1703712906383219

Noting: we need to keep her posted on timing for the fix, for a January CLP timeline that will either benefit from fix or need to work around the bug if we can't get it fixed in time.

**Comment by jilladams** [comment]
Re: these 2 ACs, remove them from ticket body: 
- [ ] If they aren't combined in the accordion group component, create an FE ticket
  - [ ] A11y review of the FE in a tugboat with a combination and ask the FE engineers/LauraF to look at it.

The FE creates 2 separate accordions for page-specific vs. reusable Q&As: https://github.com/department-of-veterans-affairs/content-build/blob/main/src/site/layouts/campaign_landing_page.drupal.liquid#L463.  So those ACs have been moved to #10940

**Comment by dsasser** [comment]
## Status Update 1/8/23

I discovered that the hidden error message is: "0 Q&A entries created. Minimum of 3 required.". This error exists anytime there are no Page-Specific Q&A's (field field_clp_faq_paragraphs) added to the CLP, and is being thrown by our custom constraint, `RequiredParagraph` in the va_gov_backend module.

in va_gov_backend_entity_bundle_field_info_alter():
```php
    // Add range check on faq panel.
    if (isset($fields['field_clp_faq_paragraphs'])) {
      $fields['field_clp_faq_paragraphs']->addConstraint('RequiredParagraph', [
        'toggle' => 'field_clp_faq_panel',
        'readable' => 'Q&A',
        'min' => 3,
        'max' => 10,
      ]);
    }
```

The validation code then requires a minimum of 3 and a max of 10 Page-Specific Q&A's on the CLP.

In order to solve for this, we'll need to replace the use of the RequiredParagraph constraint with a new one programmed to meet our needs. Fortunately Drupal doesn't have too many limitations on how we validate fields, even if they are being validated together.

**Comment by dsasser** [comment]
Per scrum 16th minute discussion on 1/9/24:

We decided that the verbiage for the error messages should be updated. @thejordanwood [provided](https://agilesix.slack.com/archives/C03EUQRCHGS/p1704824978070469?thread_ts=1704821398.267169&cid=C03EUQRCHGS) the following:

- The message that will be shown if there are fewer than than the minimum Q&As: Add page-specific or reusable Q&As. A minimum of 3 Q&As is required.
- The message that will be shown if there are more than the maximum Q&As: Remove page-specific or reusable Q&As. A maximum of 10 Q&As is allowed.
- The message that will be shown if there are no Q&As and the FAQs page segment is enabled: A minimum of 3 Q&As is required when the FAQs page segment is enabled. Disable the FAQs page segment if there are no Q&As to add.

**Comment by dsasser** [comment]
## Mid-Sprint Update 1/10/24

**This issue is at risk for closing this sprint, unless @Becapa can pick carry it over the line (I'm on PTO for most of the remainder of the sprint).**

Where we stand:
✅  The code to fix the problem has has been written.
❌ Tests have not been written
❌ KB Article has not been updated

Tests might be completed by COB today. If so, Michael or whomever can make KB article updates and ensure the PR is tested and merged.

**Comment by jilladams** [comment]
Reported the mid-sprint risk ([here](https://dsva.slack.com/archives/C52CL1PKQ/p1704917200151359)). The d10 patch upgrade takes priority, so this may roll, depending on how that goes.

**Comment by dsasser** [comment]
## Status Udate

I was not able to completely finish the cypress tests today. I've had to various unexpected challenges getting things previously untested to be testable, which has included adding additional cypress commands. I think I'm nearly there with the tests but just finishing up final bugs. All tests have been written, but a couple steps are failing still and I am in the middle of working those out. Here is a screenshot of the error I'm currently debugging:

![Screenshot 2024-01-10 at 4 21 21 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/221539/c945468c-b489-4f0f-bb4d-cce33a9a450c)

My current code, should Michael need to pick up where I left off, is in the branch `VACMS-16575-unable-to-save-clp-with-only-reusable-q`

As I said, I'm currently just debugging the last few (hopefully) cypress test bugs and this should be ready to go after those are resolved.

**Comment by jilladams** [comment]
From scrum this am: We've asked Michael to pick this up next and see if we can get it wrapped by sprint end, given that we got an extension on the Drupal 10.2 work.

**Comment by jilladams** [comment]
Noting: this PR merged 6 hours ago. CMS daily deploy theoretically ran after that, but today's daily deploy was aborted bc the git commit sha for main matched what's already in prod, so: maybe this merged after that check? Hard to tell. Should deploy tomorrow and be verifiable in prod.

**Comment by dsasser** [comment]
Verified in prod:

![Screenshot 2024-01-24 at 8 16 08 AM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/221539/edc8c80b-b6e0-48c9-8794-ba6dba8b7e97)

**Comment by jilladams** [comment]
Verified with Daniel that he did also confirm: any combo of page-specific / Reusable works as well.
