### ISSUE TITLE
Mobile View for header "My account" dropdown has truncated display issues

### ISSUE THREAD

**Issue by chriskim2311** [department-of-veterans-affairs/va.gov-cms#16580]
## Description
For LOA1 accounts they see a truncated **M... AND (Email)...** for their my account dropdown in mobile views. 

<img width="675" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOWFNQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--469bae40352b78d978917de235adffd64588b246/image%20%281%29.png" alt="image (1).png" />

## Acceptance criteria
- [ ] Fix CSS so that the My Account span shows properly in mobile view.
- [ ] Ensure that for all screen sizes that either Email or My Account is shown not both at the same time.

**Comment by andaleliz** [comment]
@chriskim2311 I think the span you're talking about is this one:

`<span class="small-screen:vads-u-visibility--visible medium-screen:vads-u-display--none">My Account</span>`

Just curious, what are the use cases in which it would show? I know for authenticated LOA3 users it shows their first name, and I can't think of a time when I've seen the words "My Account" displayed in the header.

**Comment by chriskim2311** [comment]
Having trouble testing this it will carry over to next sprint

**Comment by chriskim2311** [comment]
Verified in prod, closing!
<img width="363" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNVRpQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--11fb17977c29ace0cf7a6a337b57f3a5f08f2bb3/My_VA___Veterans_Affairs.png" alt="My_VA___Veterans_Affairs.png" />
