### ISSUE TITLE
Update Codepen prototype footer based on Phase 1 research

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#16592]
**_Note 01/02/2024: Will be placed in Sprint 101, but has the 'Blocked' tag because it's reliant on feedback from Amanda (to be provided this week I believe)._**

## Description or Additional Context 
@aklausmeier will be consulting with Mikki and Danielle on the new Federal Footer this week. After that meeting, she will provide updates that should be applied to the Codepen prototype. Also after that meeting, we should be able to update this ticket with the specific updates that need to be completed.

### Files
- [Footer file](https://codepen.io/Sitewide-Team/pen/XWOQQMO/d316dd3a4840dc04080af58a5339782a).
  - This is imported into the Contact page
  - If you want to change anything in the footer you would do it in this file.
  - Also I've noticed that when I change something in the Footer I then also have to re-save the Contact page to get the change to be reflected (probably cache)
- [Contact Page](https://codepen.io/Sitewide-Team/pen/eYxooWQ/0628a3dc13a4678d0a8249c64342f634):
  - This is an example screen that will probably be in the full prototype
  - This page will show the styled/functional footer (the footer file itself will not)

### Updates required

- [x] New USA logo file, footer uses white version, emailed files to Laura
- [x] Change Footer column heading from "Connect with us" to "News and media"
- [x] In VA footer section, move "Careers at VA" from the "Connect with us" column to the bottom of the "More resources" column
- [x] All fonts should be using Public Sans
- [x] Remove the following links from the Federal footer area:
  - [x] Civil Rights
  - [x] Harassment
  - [x] Office of Inspector General
  - [x] Plain language
  - [x] VA Performance dashboard
  - [x] Veterans Portrait Project

## Acceptance Criteria
- [x] All updates in this ticket description have been completed
- [x] UX Lead (Amanda) or PO review to confirm updates is requested 
- [x] Accessibility review to confirm updates did not create any barriers

## Team
Please check the team(s) that will do this work.

- [ ] CMS Team
- [x] Public Websites
- [ ] Facilities
- [ ] Accelerated Publishing

**Comment by laflannery** [comment]
@FranECross @jilladams This is the ticket for the next steps in the Footer Prototype. I know it can't start until we have the updates from Amanda but I think it should still be put in S101 because we need this done and finalized by the 17th as well.

**Comment by FranECross** [comment]
Thanks, @laflannery ! I added Sprint 101, put it in Stretch/Next Sprint, and also added a Blocked label to indicate we're awaiting feedback in order to work on this. cc @jilladams

**Comment by aklausmeier** [comment]
@laflannery Footer Revisions for CodePen:

1. New USA logo file, footer uses white version, emailed files to Laura
2. Change Footer column heading from "Connect with us" to "News and media"
3. In VA footer section, move "Careers at VA" from the "Connect with us" column to the bottom of the "More resources" column
4. All fonts should be using Public Sans


cc @cindymerrill some of these will impact expected/desired behavior of participant click paths with renaming and location changes

**Comment by aklausmeier** [comment]
@laflannery Remove the following links from the Federal footer area. These links will eventually move elsewhere but Danielle and Mikki are still making the decision as to where. I'll leave them in my Sketch design file until we have decisions but they can be removed from the CodePen prototype. 

Civil Rights
Harassment
Office of Inspector General
Plain language
VA Performance dashboard
Veterans Portrait Project

**Comment by cindymerrill** [comment]
@aklausmeier Will the new USA logo be black on a white background?

**Comment by cindymerrill** [comment]
@aklausmeier Looks like the only navigation path affected is the one to "Careers at VA", if I'm understanding the content changes correctly.

**Comment by laflannery** [comment]
@aklausmeier All updates have been completed from both your comments except:

> All fonts should be using Public Sans

I double checked everything in the footer and I think it does use the proper font. Was there something specific you saw that was incorrect?

**Comment by aklausmeier** [comment]
@laflannery Fonts was just a reminder to all of us including myself for when we do a final run through review.
