### ISSUE TITLE
Update Drupal Core to v10.2

### ISSUE THREAD

**Issue by edmund-dunn** [department-of-veterans-affairs/va.gov-cms#16591]
## User Story or Problem Statement
Update Drupal core to version 10.2

## Acceptance Criteria
- [ ] Core updated to 10.2
- [ ] remove aliasing if possible

## Team
Please check the team(s) that will do this work.

- [x] CMS Team
- [ ] Public Websites
- [ ] Facilities
- [ ] Accelerated Publishing

**Comment by BerniXiongA6** [comment]
@edmund-dunn let's have you size this if you could, thank you very much! cc: @maortiz-27-80

**Comment by edmund-dunn** [comment]
We were able to remove the aliasing for `drupal/core-recommended` and `drupal/core-composer-scaffold` because the final lingering dependencies that needed D9 were finally updated. We removed the direct requirement for `drupal/core` for the same reason.
