### ISSUE TITLE
Draft Federal Header Footer Phase 2 research plan

### ISSUE THREAD

**Issue by cindymerrill** [department-of-veterans-affairs/va.gov-cms#16611]
### User story
**AS A** Researcher
**I WANT** to document the details for planning Federal Header Footer Phase 2 research
**SO THAT** the research will achieve its purpose

## Suggested workflow/tasks:
- [x] Discuss participants with Amanda--screen reader users + low-vision screen magnifier users
- [x] Create initial draft of research plan--based on Phase 1 research plan
- [x] Solicit review/feedback from Sitewide UX Lead
~~- [ ] Solicit review/feedback from PO, PM, and/or other team members in a public slack post~~
- [x] Sitewide UX Lead provides consolidated feedback including from PO
- [x] Identify moderator(s), notetaker(s), and observer(s) if moderated research
- [x] Identify accessibility specialist to attend all sessions--Laura Flannery or someone from CAIA
- [x] Identify time slots for research sessions (twice as many slots as # of participants desired) if moderated research-_targeted to start Feb 1_
- [x] Post on github in project research folder for final approval before submitting to Research Review cycle

## Acceptance Criteria
- [x] Research plan drafted
- [x] Feedback incorporated from Sitewide UX Lead and PO
~~- [ ] Feedback incorporated from PM and/or other team members~~
- [x] Research plan posted on github in project research folder
- [x] Final approval obtained from Sitewide UX Lead and documented at the bottom of the file in preparation for Research Review cycle

**Comment by cindymerrill** [comment]
@aklausmeier For phase 1, we recruited 12 people in order to get 10 completed sessions (which we did). For phase 2, we initially said to recruit 14 people in order to get 8 completed sessions. I don't remember discussing why we needed to recruit more people to get fewer completes, so maybe you had this in your initial draft of the research plan. Do you remember why? Maybe AT users could be less reliable participants with their technology?

I'm fine with aiming for 8 completes, but then I think recruiting 10 people would be fine (since 10 is 25% over 8). If we're concerned about more no-shows with assistive-tech users, we could ask that 12 people be recruited instead. Since our sessions will be longer with AT (90 minutes instead of 60), setting aside twice as many time slots as people recruited will take up a LOT of days.

**Comment by cindymerrill** [comment]
If we want to recruit 10 people, we could ask for 5 who need to use screen readers and 5 who need to use screen magnifiers--unless you'd prefer a different proportion of assistive tech

**Comment by cindymerrill** [comment]
If we recruit 12 people, we'll need 24 time slots, which will take 8 days for research sessions. For 14 people, we'd need 28 time slots, which is 9.5 days. 10 people would need only 20 time slots, which can be done in 7 days--that's my recommendation.

**Comment by cindymerrill** [comment]
When do you think that the CodePen prototype will be ready to use? I'm wondering how soon I can schedule pilots and research sessions. After the prototype is all built, Amanda and I need time to review it, and Laura/Randi need time to make revisions. It would be nice if pilots could happen during the week of Jan 22, and research sessions the following week (starting Jan 29), but I don't know if this is unrealistic. Thoughts? @aklausmeier @FranECross @jilladams

**Comment by cindymerrill** [comment]
@aklausmeier Do we want a mix of Veterans and caregivers/family members of Veterans? Or do we not care? I would think we would still want a majority of Veterans, but not sure about others.

**Comment by FranECross** [comment]
@laflannery @randimays FYI Cindy's question two comments above this one ☝🏼 cc @chriskim2311

**Comment by cindymerrill** [comment]
@laflannery Are you willing to attend every research session to assist with AT issues that arise? (If so, we should talk about scheduling times that work for both of us across ET and PT.) In my previous AT studies, Angela Fowler did this for me, and that kept them running smoothly, but I doubt she can do that this time because she's on a different program. She previously told me that she's willing to train you in how to do this, if that would be helpful. She's also who I'd like to have as a pilot participant, preferably before she trains you so the prototype will be brand-new to her.

**Comment by cindymerrill** [comment]
Here's a [link to my draft research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/header-footer/federal-standardized-header-footer/research/phase2-AT/research-plan.md), which I'll update after I get replies to my questions above.

**Comment by aklausmeier** [comment]
@cindymerrill 

This solution works. 

> If we want to recruit 10 people, we could ask for 5 who need to use screen readers and 5 who need to use screen magnifiers--unless you'd prefer a different proportion of assistive tech


My concern was no-shows or participants showing up w/o the AT they said they used based on other teams' prior studies. We can always have Perigean recruit additional to meet the minimim if we need to.

**Comment by aklausmeier** [comment]
@cindymerrill Agree to have majority be Veterans. It will be more important to have the AT recruitment criteria met but the tasks are better suited to a Veteran.

> Do we want a mix of Veterans and caregivers/family members of Veterans? Or do we not care? I would think we would still want a majority of Veterans, but not sure about others.

**Comment by cindymerrill** [comment]
@aklausmeier Agreed. How about **at least 7** of the 10 recruited should be Veterans?

**Comment by aklausmeier** [comment]
> When do you think that the CodePen prototype will be ready to use? I'm wondering how soon I can schedule pilots and research sessions. After the prototype is all built (by Jan 16, is the target, I believe), Amanda and I need time to review it, and Laura/Randi need time to make revisions. It would be nice if pilots could happen during the week of Jan 22, and research sessions the following week (starting Jan 29), but I don't know if this is unrealistic. 

@laflannery and I have been pushing for a hard deadline of Jan 16 given the time you need and mentioned above. Laura is working hard to make this happen but there are areas she is needing assistance of engineers which I think we covered well in planning today. If we don't have CodePen ready by Jan 16, it will become a blocker to research due to required timing of research ops and recruitment.

cc @jilladams @FranECross

**Comment by cindymerrill** [comment]
@amanda [Research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/header-footer/federal-standardized-header-footer/research/phase2-AT/research-plan.md) has been updated per your responses above and so now ready for your review. Timeline is TBD because it depends on the prototype, but I've proposed some plausible dates that can be revised later.

**Comment by aklausmeier** [comment]
> @laflannery Are you willing to attend every research session to assist with AT issues that arise?

@cindymerrill My understanding is we have the ability to request a CAIA accessibility specialist to assist with these sessions. Is that no longer an option?

**Comment by cindymerrill** [comment]
@aklausmeier I've never done that before but could try. I saw that on the Platform documentation; I wonder if it's new. I talked with @laflannery about it a while ago, and she was interested in the time, but I don't know if she still is, and whether she could it for ALL sessions.

**Comment by cindymerrill** [comment]
@aklausmeier I just checked [where I read it](https://depo-platform-documentation.scrollhelp.site/research-design/research-with-assistive-technology-users#Researchwithassistivetechnologyusers-3.Participantrecruitment), and it doesn't sound like someone to attend sessions and provide AT tech support but instead a one-time review:

> You can request an Accessibility Specialist during the Collaboration Cycle Design Intent checkpoint. They can help you write and review your research plan and conversation guide before submitting your study for a formal research review.

**Comment by laflannery** [comment]
@cindymerrill and @aklausmeier I'm not sure depending on me for every research session is a viable option. I'm just not sure I have that time. [CAIA should be able to help us with this](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/CAIA/accessibility#research-support) and between them and myself we should be able to cover all the sessions

**Comment by cindymerrill** [comment]
@laflannery I didn't see the info you shared in the Platform research documentation so it must be new. I'll definitely reach out to CAIA to inquire...and then coordinate with you and them to cover all the sessions.

**Comment by aklausmeier** [comment]
@cindymerrill Research plan Phase 2 looks great, no changes!

**Comment by aklausmeier** [comment]
@cindymerrill Can you take a second pass on the conversation guide? I was noticing wording that references things like " you'll **see** a row of buttons at the bottom" since these are low vision participants we want to be sensitive to how we provide instructions.

**Comment by cindymerrill** [comment]
> @cindymerrill Research plan Phase 2 looks great, no changes!

So I should update the "approved" line at the bottom of the file with your name instead of Dave's from November? @aklausmeier

**Comment by cindymerrill** [comment]
> @cindymerrill Can you take a second pass on the conversation guide? I was noticing wording that references things like " you'll **see** a row of buttons at the bottom" since these are low vision participants we want to be sensitive to how we provide instructions.

I'll work on this later today...

**Comment by jilladams** [comment]
@cindymerrill for end of sprint 101 on Tuesday, could you update ACs to clarify which tasks we are expecting to close by end of sprint, vs. what may roll over? If everything is expected to complete in sprint, no changes necessary.

**Comment by cindymerrill** [comment]
All AC's done, except for PM review (which isn't happening).
