### ISSUE TITLE
Draft Federal Header Footer Phase 2 conversation guide

### ISSUE THREAD

**Issue by cindymerrill** [department-of-veterans-affairs/va.gov-cms#16613]
### User story
**AS A** Researcher
**I WANT** to document the details for conducting Federal Header Footer Phase 2 research
**SO THAT** the research will achieve the stated goals and answer the research questions

## Suggested workflow/tasks:
- [x] Discuss potential convo guide changes with Amanda
- [x] Create initial draft of conversation guide--based on Phase 1 convo guide, _targeted for Fri Jan 5_
  - [x] Track items mentioned in the initial topline draft, including any comments on the size/organization of the footer or false footer 
    > One study participant and one pilot participant said that the footer was too large. 
    > A different participant commented on the lack of organization or categories in the black section of footer links. 
    > Another participant didn't scroll all the way to the bottom of the page but only down to the USA logo, which looked like the bottom of the page to him. He said that he usually doesn't use footer links on web pages because it's just information about the company. 
- [x] Solicit review/feedback from Sitewide UX Lead
- [x] Solicit review/feedback from CAIA Accessibility Specialist 
~~- [ ] Solicit review/feedback from PO, PM, and/or other team members in a public slack post~~
- [x] Sitewide UX Lead provides consolidated feedback including from PO
- [x] Test prototype(s) with conversation guide and align
- [x] Post on github in project research folder for final approval before submitting to Research Review cycle

## Acceptance Criteria - Sprint 101
- [x] Conversation guide drafted
~~- [ ] Feedback incorporated from PM and/or other team members~~
- [x] Conversation guide posted on github in project research folder

## Acceptance Criteria - Sprint 102
- [x] Feedback incorporated from Sitewide UX Lead and PO
- [x] Conversation guide aligns with prototype(s)
- [x] Final approval obtained from Sitewide UX Lead and documented at the bottom of the file in preparation for Research Review cycle

**Comment by cindymerrill** [comment]
Drafted [phase 2 conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/header-footer/federal-standardized-header-footer/research/phase2-AT/conversation-guide.md) based on phase 1 version and added a few things specific to AT. Ready for @aklausmeier 's review and then testing with the CodePen prototype.

**Comment by cindymerrill** [comment]
@Jill Adams @Fran Cross @aklausmeier Just realized that I **won’t be able to close this ticket during this sprint** if the CodePen prototype finishes at the end of this sprint (as planned) because the AC's include aligning with the prototype, which will likely result in tweaks to both this convo guide and the prototype that will need time to make.

**Comment by cindymerrill** [comment]
@aklausmeier I removed the see/look language from the convo guide and updated one of the navigation paths per the footer content changes, so now it's ready for your review again.

**Comment by cindymerrill** [comment]
@aklausmeier plans to review the convo guide after

- A CAIA Accessibility Specialist has reviewed it AND
- The prototype is ready so we can go through it with the convo guide tasks

**Comment by cindymerrill** [comment]
Waiting to hear back from CAIA about an accessibility specialist to review the convo guide and research plan, service as a pilot participant, and serve as accessibility tech support during research sessions.

**Comment by cindymerrill** [comment]
I received feedback on my conversation guide from a CAIA accessibility specialist, and I've made the revisions. I also read Platform's [Screen Reader Checklist](screenhttps://depo-platform-documentation.scrollhelp.site/research-design/screen-reader-checklist) and think I'm all set.

**Comment by cindymerrill** [comment]
@aklausmeier I also tested my conversation guide with the CodePen prototype, which is done, and found a number of issues, which I documented [here](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16573#issuecomment-1888103977). I made a few tweaks to the convo guide, and I'll test the prototype again after the issues are resolved.

**Comment by jilladams** [comment]
Would be helpful to clarify here as well what we expect to close by end of sprint.  (Also: i am realizing we need to remember to revisit the phrasing of the ACs in all the research templates to be clear that we can request UX lead feedback but Amanda's asked for 48 hours to turn around feedback, in general.  That may sometimes cross sprint boundaries.)

**Comment by cindymerrill** [comment]
All the AC's are done except waiting for @aklausmeier 's review and feedback with the prototype, which still needs more tweaks. This will be carried over to the beginning of Sprint 102 and will likely be done by Friday Jan 19.

**Comment by jilladams** [comment]
@aklausmeier @cindymerrill I'm updating the ACs to make that clear. cc @FranECross

**Comment by aklausmeier** [comment]
@cindymerrill  Feedback post-CAIA a11y review. 

1. In Task 1, I noticed "Decide which prototype to show ..." It's only one prototype for this round of testing and it will automatically adjust to whatever device the participant is using. You could probably delete this sentence but up to you.
2. Intro needs an update to session length from "This session should take about an hour."  It doesn't need to take the allotted 90 minutes, so no need to stretch sessions to fill the adjusted length but want to set the right expectation that we have "an hour and a half" allotted.

**Comment by cindymerrill** [comment]
Thanks for your feedback, @aklausmeier ! Changes made, and this ticket is now complete (FYI @jilladams @FranECross).
