### ISSUE TITLE
Conduct KB research sessions (11/?)

### ISSUE THREAD

**Issue by joagnitti** [department-of-veterans-affairs/va.gov-cms#16612]
## User Story or Problem Statement
Now that we have scheduled KB research sessions, we can begin to conduct them. 

## Description or Additional Context 
[Research plan
](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/research/knowledge-base/research-plan.md)

[Conversation guide
](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/research/knowledge-base/kb-conversation-guide.md)
## Acceptance Criteria
- [x] Research sessions scheduled within the sprint have been conducted
- [x] Product Design take notes during sessions

## Team
Please check the team(s) that will do this work.

- [x] CMS Team
- [ ] Public Websites
- [ ] Facilities
- [ ] Accelerated Publishing

**Comment by BerniXiongA6** [comment]
@joagnitti completed 11pts in Sp 101, 8 left for Sp 102. cc: @maortiz-27-80

**Comment by maortiz-27-80** [comment]
Adding to A/C to capture some of Blake's capacity for note taking during sessions. - Marcia cc: @BerniXiongA6  @joagnitti @BlakeOrgan

**Comment by BlakeOrgan** [comment]
All research sessions have been held. 🎉
