### ISSUE TITLE
Create a notification (aging content) framework that's flexible and configurable by content type

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-cms#16623]
**Note: This story to be repurposed and rewritten after the Planned Architecture Ticket has been completed and reviewed with someone in CMS (either async or a formal CMS Collab Cycle Review)**

## Description
To provide timely information to Veterans and other users of VA.gov, and ensure banners are monitored and edited or archived, we need to implement the ability for a notification system to send notification emails for (the MVP) Full-Width banners on a seven (7) days timeframe.

Two different notifications will be sent:
 - the first email email will be sent three days before the 7th day will inform the editor that they need to edit and add a note that it is still needed or archive the banner
 - the second email will be sent the morning of the 7th day (12:01am) informing them they need to either edit to add a note that the banner is still needed, or archive. Note that after the future auto-archiving feature is implemented, this email will inform them that their content will be archived at midnight that night.

This framework will need to be extendable to accommodate other content types, such as other banners, Home Page Benefit Promo Blocks, and Home Page News Spotlight Blocks, which will be set at 30 day notification sequences. There are other initiatives for this work and we'll create subsequent stories as well. 

### User stories

TBD

### Engineering notes / background
- Refer to (recent) prior research/investigation

## Acceptance criteria
- [ ] TBD

**Comment by FranECross** [comment]
@jilladams I created this Aging Content Spike as a possible inclusion for Sprint 101, if the Drupal folks can accommodate it, and if nothing else urgent or higher in priority crops up before tomorrow.

**Comment by FranECross** [comment]
Need to have a design review meeting with the CMS team to come up with a plan forward.

**Comment by jilladams** [comment]
Noting: Michael helped create a Notifications module that may be useful for this case: https://www.drupal.org/project/content_reminders

**Comment by FranECross** [comment]
@dsasser @Becapa @jilladams @davidconlon Here's the edited Aging Content MVP story we can discuss during next refinement (and can be broken into multiple stories as needed). You'll see the link to Michael's notifications module in the comment above this one (thanks Jill!).

**Comment by dsasser** [comment]
@FranECross @jilladams 

Closing this as a dupe. We cut tickets that refine this into more discrete work, so this one is no longer needed.
