### ISSUE TITLE
Migrate from A6 Figma to Va.gov Figma

### ISSUE THREAD

**Issue by maortiz-27-80** [department-of-veterans-affairs/va.gov-cms#16637]
## User Story or Problem Statement
All of VA.gov designers will be moving from Sketch to Figma.  We already utilize A6 Figma and will need to migrate over to VA.gov Figma. 

## Acceptance Criteria
- [x] All A6 Figma files are migrated over to VA.gov Figma account
- [x] Notify Facilities UX who have A6 Figma seats the content of files transferred
- [x] Notify @BerniXiongA6 when complete so she can handle admin tasks related to this ticket

cc: @BerniXiongA6

**Comment by BerniXiongA6** [comment]
Hey @BlakeOrgan can we have you size this ticket for this sprint when you have a chance? Thanks! cc: @maortiz-27-80

**Comment by BlakeOrgan** [comment]
@BerniXiongA6 @maortiz-27-80 Pointed, but I think this should probably be part of next sprint, not this one.

**Comment by BerniXiongA6** [comment]
Making note here for me to add this ticket to Sprint 102 when that epic is ready. Thanks @BlakeOrgan cc: @maortiz-27-80

**Comment by BerniXiongA6** [comment]
@EWashb to discuss with Amanda K. to see how involved she'll be in the migration. Erika to reach out via Slack. cc: @BlakeOrgan

**Comment by BlakeOrgan** [comment]
@EWashb @maortiz-27-80 @BerniXiongA6 @michelle-dooley @gracekretschmer-metrostar @aklausmeier @thejordanwood 

All CMS files in the Agile 6 Figma organization now live in the [CMS Platform](https://www.figma.com/files/project/176533587) project of the VA Figma organization.

The only files that have yet to be migrated from the Agile 6 Figma organization into the VA Figma organization are the files in [Facilities Projects](https://www.figma.com/files/920496649063276587/project/85466124) and [Public Websites Projects](https://www.figma.com/files/920496649063276587/project/66401080) as these files are the responsibility of their respective teams.
