### ISSUE TITLE
Socialize deployment language with VSP and other teams

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#1664]
- [x] CMS support release note
- [x] Announce in vfs platform support
- [x] Add to documentation
- [x] Give to Howie for implementation in training materials
- [ ] Pin to CMS support

**Comment by rachel-kauff** [comment]
![Deployments ](https://user-images.githubusercontent.com/41017988/84707148-087ef980-af13-11ea-95ce-d216af37555a.png)

**Comment by rachel-kauff** [comment]
Announcement for VFS platform:

Standardized names for VA.gov deployments 
🤔 What the deploy? The CMS team has noticed that it can be really confusing to communicate about the different deployments that affect our work with content editors and other product teams, especially when everyone is speaking a slightly different language. We've come up with a set of standardized names we'll be using from now on, and a handy chart with all the details. Check it out: https://whimsical.com/14gDq8UJ61yYx4cD4kHFKQ
(or see the attached summary version).
