### ISSUE TITLE
Test restricted archive workflow

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#16641]
## Description
VA Police pages and other VAMC system level pages are not on Restricted Archive workflow. This means that there is a risk of a local editor archiving their page.

Risk is: in the time between publish and move to Restricted Archive workflow, Editors could archive. That's known / accepted risk that is already prevalent in the system with other content types.

#16522 put VA Police pages in the Restricted Archive workflow.

This ticket is to test Restricted Archive workflow implementation.

## Acceptance Criteria
- [x] cypress test that content_editor role can't archive pages (e.g., VA Police)
- [x] cypress test that content_admin role can archive pages in the restricted archive workflow.

**Comment by xiongjaneg** [comment]
From Christian: There is one test on VBA (currently as content_publisher, but most are content_editor)

From Dave: VAMCs are generally content_publisher. Testing for content_publisher generally covers content_editor, but not in restricted archive.

**Comment by swirtSJW** [comment]
There is nothing to review on prod.  Tests don't run there.  This can be considered done.

**Comment by xiongjaneg** [comment]
@Becapa On Facilities team, most folks mark their own ACs done. Once you mark them, I've noted Steve's comment above and will close this as done. Thanks for your great work!

**Comment by Becapa** [comment]
> @Becapa On Facilities team, most folks mark their own ACs done. Once you mark them, I've noted Steve's comment above and will close this as done. Thanks for your great work!

Sounds good! Should be good to go.
