### ISSUE TITLE
Transition Documentation: Help Desk

### ISSUE THREAD

**Issue by maortiz-27-80** [department-of-veterans-affairs/va.gov-cms#16648]
## User Story or Problem Statement
Our primary objective is to facilitate a smooth transition for the incoming CMS team. To achieve this, we need to document our processes comprehensively. This documentation will serve as a valuable resource for the new team members and contribute to the overall success of the handover.

## Overall Process Documentation
- [x] Identify and document end-to-end processes 
- [x] Include step-by-step procedures, key milestones, and dependencies
- [x] If applicable, identify and document dependencies on external systems, APIs, or third-party services
- [x] Document the location of critical knowledge repositories, wikis, or documentation sources
- [x] Include information about access permissions and guidelines for updating or maintaining these repositories
- [x] Include an updated list of key contacts within the organization, including team leads, support personnel, and any external contacts relevant to the CMS team's responsibilities
- [x] Document any historical data, insights, or lessons learned from past projects or incidents that may be valuable for the incoming team

## Repetitive Processes
- [x] Identify and document repetitive processes that are crucial for daily operations
- [x] Include detailed instructions, best practices, and any relevant tools or resources

## Acceptance Criteria
- [x] Document processes in Confluence.  Parent page for Help Desk [is here](https://vfs.atlassian.net/wiki/spaces/PCMS/pages/2891448757/Help+Desk). 
- [ ] Each documented process should be reviewed and approved by the PO, PM, and DM
- [ ] The documentation should be clear, concise, and easily understandable by individuals with varying levels of expertise
- [ ] Include visual aids, flowcharts, diagrams, and links (external and internal) where applicable to enhance clarity
- [ ] Confirm that ALL helpdesk documentation being housed in external spaces (like Notion or Google Drive/Sheets/Docs, etc.) have been moved to Confluence (or GitHub if appropriate).
- [ ] Confirm that any current processes being completed by the helpdesk are documented (even if they occur on an irregular basis)

## Team
Please check the team(s) that will do this work.

- [x] CMS Team
- [ ] Public Websites
- [ ] Facilities
- [ ] Accelerated Publishing

cc: @BerniXiongA6 @EWashb @ndouglas

**Comment by EWashb** [comment]
Additions: 
- confirm that ALL helpdesk documentation being housed in external spaces (like Notion or Google Drive/Sheets/Docs, etc.) have been moved to Confluence (or GitHub if appropriate). 
- confirm that any current processes being completed by the helpdesk are documented (even if they occur on an irregular basis)
@maortiz-27-80 @BerniXiongA6

**Comment by maortiz-27-80** [comment]
Thanks @EWashb !  A/C updated with your feedback. cc: @BerniXiongA6

**Comment by stefaniefgray** [comment]
**Progress so far:** 
- 43 Notion pages exported to .md (markdown) files
- Ran Python script to strip out Notion-specific formatting and convert all pages to HTML
- There is no bulk method for transferring either Markdown or HTML files to Confluence (HTML macro option must be installed by Confluence administrator) so after creating the new HTML files, they must be copied, pasted, and cleaned up manually. I am currently in the process of doing so.

**Comment by stefaniefgray** [comment]
All content has been migrated to Notion: https://vfs.atlassian.net/wiki/x/tQFYr

Facilities pages need work; would appreciate assistance from Facilities team regarding runbook protocols and procedures documentation as well as revised process for Flagged Facilities upon current team's departure

Passing to @BerniXiongA6 @EWashb @maortiz-27-80 and @TroyA6 for review

**Comment by maortiz-27-80** [comment]
Thanks, @stefaniefgray !  Reviewing now and can you or @TroyA6 confirm you meant Confluence rather than Notion?  Every link goes to Confluence, which is expected.  cc: @BerniXiongA6 @EWashb

**Comment by stefaniefgray** [comment]
@maortiz-27-80 Haha yes, definitely meant migrated to Confluence rather than Notion! Late-night editing marathon completed, was ready to 😴

**Comment by maortiz-27-80** [comment]
Thanks for confirming, @stefaniefgray !  I figured as much :)
