### ISSUE TITLE
Align Main mental health phone number with service contact info

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-cms#16652]
## Description
CMS became the source of truth for Mental health phone numbers in #9717.
Mental health numbers appear in a number of places throughout the VAMC sites and in the Facility Locator.
- The main number is displayed at the facility level in the Facility Locator search results and in the Locations and Contact information block on VAMC pages.
- One or more phone numbers can be added at the Mental health service level. These numbers might be labeled Main, Contact, Appointment, or other. 
- Contact information for Care Coordinators are displayed on required Mental health care pages (which are linked from within the service accordion)

## Problems to solve
- If a Veteran refers to the health service accordion to find a number, will the best number be listed? 
- And if it is listed, does it have a clear, identifiable label? 
- Do the two numbers labeled as "Main" agree? 
- How might we align this information to remove confusion for Veterans?

System level mental health numbers are scoped separately in #16655

## Current Examples to Avoid
[Hot Springs VA Medical Center](https://www.va.gov/black-hills-health-care/locations/hot-springs-va-medical-center/)

**Phone numbers displayed in Location and contact information area**
- Main phone: 605-745-2000
- Mental health care: 605-347-2511

**Within the [Mental health service accordion](https://www.va.gov/black-hills-health-care/locations/hot-springs-va-medical-center/#mental-health-care)** 
- Main Phone: 605-745-2000 (appears twice)
- Appointments: none listed

---

[Cheyenne VA Medical Center](https://www.va.gov/cheyenne-health-care/locations/cheyenne-va-medical-center/)

**Phone numbers displayed in Location and contact information area**

- Main phone: 307-778-7550
- Mental health care: 307-778-7349

**Within the [Mental health service accordion](https://www.va.gov/cheyenne-health-care/locations/cheyenne-va-medical-center/#mental-health-care)** 

- Main Phone: 307-778-7550
- Contact: 307-778-7550, ext. 7349
- Contact: 307-920-3536
- Appointments: 888-483-9127

## Engineering notes

- From discussion, logic is already in place. 
- FE change needed = look at service, if it's mental health, use the number specified by the facility
- Could also make an improvement in Drupal to align UX with front end experience to help editors avoid duplication. If we don't make these changes now, we'll need to make the existing behavior clear in KB article to support editors.

## Acceptance Criteria
- [x] The Mental health phone number listed under contact information should also appear as the Mental health phone number in the Mental health service accordion.
- [x] Use the telephone component with the aria described by label.

**Comment by xiongjaneg** [comment]
Questions to be asked:
- How do we prevent the editor from showing a number twice?

Front end:
- What if the editor didn't check the box for Use main facility number, should we grab the mental health number anyway?
- A separate ticket for Use main facility number, which is currently a front end function
- To prevent duplicating a number, front end may have to add some logic to compare and prevent duplication - current state

**Comment by xiongjaneg** [comment]
@xiongjaneg To align with the related content model ticket for Dave

**Comment by xiongjaneg** [comment]
@davidmpickett Please review for any related impact to/from #16655

**Comment by mmiddaugh** [comment]
FE change needed = look at service, if it's mental health, use the number specified by the facility
In addition to FE change, we could make an improvement in Drupal to align UX with front end experience to help editors avoid duplication. If we don't make these changes now, we'll need to make the existing behavior clear in KB article to support editors.

**Comment by xiongjaneg** [comment]
@xiongjaneg Note that there will be a KB article change when this is done. Stub a ticket for it.

**Comment by davidmpickett** [comment]
FYI - I updated the [Content model](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1690837066198/79f3d0e816f12daaf9a9ede96f4cf14ab6932cb7?wid=0-1706559598760) to reflect both the possibility of a Front End-only fix, and a more robust Drupal fix

**Comment by maxx1128** [comment]
End of Sprint 103 update: I started on this near of the end of the sprint and began [a Slack thread](https://dsva.slack.com/archives/C0FQSS30V/p1707762373114469) to get design/UX feedback on it. It's currently paused to focus on [#15959](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15959) and is scheduled to discuss at the next UX Sync.

**Comment by maxx1128** [comment]
As per the UX Discussion on 2/15, I've made the following updates to the pull request:

* The current pull request associated with this ticket will keep the original first two commits, which focus on showing the general mental health phone number instead of the general facility number when needed.
* The fixes in the last two commits (duplicate number and duplicate appointment headers) will be split off and saved into these respective pull requests. As of this writing, they are not associated with any tickets and can be renamed for future stubbed tickets, focusing on the issues they address.
    * `va-16652-SAVED-avoid-duplicate-health-service-phone-numbers`
    * `va-16652-SAVED-avoid-duplicate-appt-headers`
* The last AC in this ticket (using the aria described label) will be added to the original pull request since it's one of the original ACs and is a quick win.

**Comment by xiongjaneg** [comment]
#17251 stubbed for the duplicate phone number issue

**Comment by aklausmeier** [comment]
@thejordanwood FYA of Drupal feasibilities / quirks that you should be looped in on as the designer for FE and Drupal UI

**Comment by maxx1128** [comment]
The acceptance criteria for this ticket have been met, but [Eli noticed a bug with how the component rendered the phone number with an extension.](https://dsva.slack.com/archives/C0FQSS30V/p1708932472080379) This didn't appear before since the main facility number has never had an extension (as far as I'm aware). However, the main mental health numbers are sometimes the main facility number with an extension added. I have [a draft pull request open for it now.](https://github.com/department-of-veterans-affairs/content-build/pull/1931) Once it gets merged, this ticket should be good to close.

**Comment by xiongjaneg** [comment]
@maxx1128 Should this be in prod now? I'm not seeing it in the [Cheyenne page](https://www.va.gov/cheyenne-health-care/locations/cheyenne-va-medical-center/)
<img width="375" alt="Screenshot 2024-03-11 at 3 35 01 PM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/73648238/eed58644-08e7-45d0-bb73-5fc02a12abbc">

**Comment by maxx1128** [comment]
> @maxx1128 Should this be in prod now? I'm not seeing it in the [Cheyenne page](https://www.va.gov/cheyenne-health-care/locations/cheyenne-va-medical-center/) <img alt="Screenshot 2024-03-11 at 3 35 01 PM" width="375" src="https://private-user-images.githubusercontent.com/73648238/311859690-eed58644-08e7-45d0-bb73-5fc02a12abbc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAxOTQ5ODcsIm5iZiI6MTcxMDE5NDY4NywicGF0aCI6Ii83MzY0ODIzOC8zMTE4NTk2OTAtZWVkNTg2NDQtMDhlNy00NWQwLWJiNzMtNWZjMDJhMTJhYmJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzExVDIyMDQ0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRkZjU0NGZhMTBkMjhmNGMyYjA3ZTUwYTg4OTYxM2U2ZGIxOTU2ZjQ2YzRjOTgyYzk0NGI2OWRhZDAzMGVjZjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qdoOSMxwHY-Z2ctYdnR1g89JUuKEzUM3UFMoyMEdzs4">

@xiongjaneg It looks like it's working. The main phone in the "Mental Health" service accordion matches the mental health phone number at the top of the page. The two "contact" numbers below are other numbers added to the CMS, so those need to be edited on that side. Are you referring to something else on the page?

**Comment by xiongjaneg** [comment]
@maxx1128 For the first AC "The Mental health phone number listed under contact information should also appear as the Mental health phone number" I understood that to be the label in both places should be "Mental health care." That's the label in the facility contact information but not in the mental health accordion, though the numbers look correct.

@mmiddaugh Was that your intent?
<img width="751" alt="Screenshot 2024-03-12 at 9 14 06 AM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/73648238/137162d7-dbf8-4f48-8797-6d7abcb9e0e0">
<img width="718" alt="Screenshot 2024-03-12 at 9 14 35 AM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/73648238/fc997095-5b31-4422-ae43-48148ef4decd">
