### ISSUE TITLE
Content model for VAMC system level mental health number

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-cms#16655]
## Description
CMS became the source of truth for Mental health phone numbers in #9717. 
Mental health numbers appear in a number of places throughout the VAMC sites and in the Facility Locator. 
- The main number is displayed at the facility level in the Facility Locator search results and in the Locations and Contact information block on VAMC pages. 
- One or more phone numbers can be added at the Mental health service level. 
- Contact information for Care Coordinators are displayed on required Mental health care pages (which are linked from within the service accordion)

**Problems to solve**

- The contact information for mental health care should be present, accurate, and represent the best way for a Veteran to access mental health care for that facility/system. 
- The contact information displayed should be consistent, accurate, and clearly labeled.
- VHA Facilities are required to provide a phone number which Veterans can all to access mental health care, even if they do not offer mental health services. (They likely list the VA Medical Center for the system - although some systems have more than one.)  

Alignment of numbers with the health service details is scoped separately in #16652

## Example
[Cheyenne VA Medical Center](https://www.va.gov/cheyenne-health-care/locations/cheyenne-va-medical-center/)

**Phone numbers displayed in Location and contact information area**

- Main phone: 307-778-7550
- Mental health care: 307-778-7349

**Within the [Mental health service accordion](https://www.va.gov/cheyenne-health-care/locations/cheyenne-va-medical-center/#mental-health-care)** 

- Main Phone: 307-778-7550
- Contact: 307-778-7550, ext. 7349
- Contact: 307-920-3536
- Appointments: 888-483-9127

**Required health service page**
[Mental health care](https://www.va.gov/cheyenne-health-care/health-services/mental-health-care/)
- Phone: 970-593-3300, ext.2204 or ext. 2203

## Acceptance criteria
- [x] Content model is documented 
- [x] Content model is reviewed with engineering and Product
- [x] PM is tagged to stub subsequent tickets

**Comment by xiongjaneg** [comment]
@xiongjaneg Need to stub content model ticket for what we are going to do.

**Comment by xiongjaneg** [comment]
@davidmpickett If you think you'll get this into next sprint, would you refine and point by Tuesday? Thank you!

**Comment by davidmpickett** [comment]
Updated content model:
- [Previous state (late 2023)](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1690837066198/79f3d0e816f12daaf9a9ede96f4cf14ab6932cb7?wid=0-1693242058396)
- [Current state as of Jan 2024](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1690837066198/79f3d0e816f12daaf9a9ede96f4cf14ab6932cb7?wid=0-1693263650243)
- [Future state](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1690837066198/79f3d0e816f12daaf9a9ede96f4cf14ab6932cb7?wid=0-1706559598760)

**Comment by davidmpickett** [comment]
Shared on Slack for feedback: https://dsva.slack.com/archives/C0FQSS30V/p1706561994075419

@swirtSJW notes that Current State will be accurate after completing [#15686](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15686)
@mmiddaugh notes Future state looks good (with 1 comment which I addressed)

**Comment by davidmpickett** [comment]
Added to [agenda for Thursday's UX Sync](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16586#issuecomment-1915686366). I think the choice really comes down to Option 1 or 2, but I spelled out 3 & 4 for completeness.

@aklausmeier @xiongjaneg @Only remaining item on this is a decision and ticket stubbing, so I think we can close this, but defer to y'all

**Comment by xiongjaneg** [comment]
follow up ticket stubs for engineering #17085 and #17086

**Comment by davidmpickett** [comment]
From UX Sync today, it sounds like Option 1 is the clear next step, but the other options may be useful for other problems in the future

**Comment by mmiddaugh** [comment]
I think we'll need to allow the editor to enter a label for the system number so Veterans understand who/what they are calling (is it the hotline? the main medical center?). This raises a question though. If the system mental health number is used by the facility as a fallback, will the label go with it?

**Comment by mmiddaugh** [comment]
@davidmpickett thank you as always for concisely outlining all the options along with their pros/cons. 

@xiongjaneg and I support Option 1 because of the simple lift given engineering capacity and lower impact on editors, especially in light of all we have asked of them recently

---
To document why the other options were not selected: 
- **Option 2 - VAMC System Health Service** 
   - as you mentioned during UX Sync today, this is an interesting option but because it has implications across all services, it could cause editor confusion without good reason, since it isn't immediately applicable to most services
   - on my mind, even if not entirely related: there's a backlog issue to change the logic which cascades system health service descriptions down to facilities so that editors can create facility-specific descriptions when the local service differs from the system level description. This makes me think twice about adding another layer of data inheritance at the service-level, unless there is a compelling reason
- **Option 3 - (new) VAMC System Mental Health Care page**
   - this is a heavy lift for engineering _plus_ a big ask for editors, neither of which we planned for Q1-24
- **Option 4 - Service Region**
  - big lift, heavy impact on editors, _plus_ a hack of the intended use for this content type

**Comment by davidmpickett** [comment]
> I think we'll need to allow the editor to enter a label for the system number so Veterans understand who/what they are calling (is it the hotline? the main medical center?). This raises a question though. If the system mental health number is used by the facility as a fallback, will the label go with it?

@mmiddaugh In the content model, the VAMC System Mental Health Number isn't directly connected to any Front End page that Veterans would see. It's only purpose is as a fallback for VAMC Facility mental health phone numbers. 

![Screenshot 2024-02-02 at 2 35 13 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/0b48ad11-cc58-4480-84b6-825b35476a04)

My understanding is that the VAMC Facility mental health phone number would show up exactly the same way as is currently does in all the places it currently does. Just in some cases the original source of that data originates at the System level.

![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/366b8b82-286a-4aac-b5f8-cc975913ed68)
