### ISSUE TITLE
2023 Income year copay rates have 2 incorrect values re: 90 day hospital copays

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#16668]
## Description or Additional Context 
~The page https://www.va.gov/health-care/copay-rates/ includes 90-day hospital copay rates that are incorrect.~

~The 'First 90 days of care during a 365-day period' is listed as $1632 but should be $1652, and the 'Each additional 90 days of care during a 365-day period' value is listed as $816 but should be $826.~

### Update 1/24/24
The numbers above were verified via email chain with VES / CAIA, and the CAIA values stay. VES has updated their data upstream. Our copy of the VES data in S3, as of Jan 1 2024, is _incorrect_ and contains the old VES values that have been updated. 

We intend to automate the data import, so are opting not to update these values manually right now because these particular numbers are not used / presented in the app. Once data import automation is complete, these incorrect values will be automated-ly overwritten and this ticket can be closed. 

## Acceptance Criteria
~- [ ] 'First 90 days of care during a 365-day period' is listed as $1652~
~- [ ] 'Each additional 90 days of care during a 365-day period' is listed as $826~
- [ ] S3 copy of VES data contains the correct values for 90 day hospital care

**Comment by jilladams** [comment]
@dsasser this data correction was noted by Josh Tuscher today - seems like the CSV data updated on VA.gov is incorrect on this one value. I've pulled this into sprint - I'm hoping that pushing an updated CSV is lightweight, but I know we need a migration to run, so let's discuss if this affects other tickets in sprint.  FYI @FranECross

**Comment by dsasser** [comment]
@jilladams @FranECross Are we sure the data is incorrect in the CSV? I downloaded the latest income threshold CSV from S3 and I'm seeing the expected numbers:

![Screenshot 2024-01-05 at 8 57 19 AM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/221539/9c73c162-a5a2-4283-b7eb-17cebbd63185)

I reached out to Joshua for clarification as to where the bad data is being seen, and will update here when I get more info from him.

**Comment by dsasser** [comment]
## Update 1/5/24

This is not an application/CSV bug: Joshua was looking at https://www.va.gov/health-care/copay-rates/ which is CMS content. I have [reached out to CAIA](https://dsva.slack.com/archives/C01K37HRUAH/p1704477328599819) to address the discrepancy.

**Comment by FranECross** [comment]
Thanks for taking care of this, @dsasser !!

**Comment by jilladams** [comment]
Per slack thread, this is potentially an issue on the VES side. If CAIA determines that their copy / numbers are correct, I think we will have to update our CSV data source, so I'm readding Public Websites label til that's cleared up between CAIA / VES.

**Comment by jilladams** [comment]
Joshua Faulkner noted today re: whether VES updates are complete: 
> Not yet, its in progress and will be part of the Jan SDS standard data update which is in testing now.

**Comment by jilladams** [comment]
Josh Faulkner confirmed today that VES's data update is complete has been rolled out thru production. We can now update our copy of the data.

**Comment by dsasser** [comment]
@FranECross @jilladams 

A couple things:

1. The incorrect values in question are not used by any va.gov application including income limits. They are imported, but the data is never used. So changing the values in the Income Limits database will have no impact to va.gov or a Veteran.
2. We are 99% of the way toward full data import automation. Manually uploading data that isn't actively used may not be worth doing at all.

**Comment by FranECross** [comment]
@dsasser Thanks for this info, and I agree there's no reason to update.

**Comment by jilladams** [comment]
Concur. This reminded me that the original flag that came up here was in content that CAIA owns and hasn't changed as a result of vetting the diff with VES folks, who updated their side instead. I do worry a bit about having the wrong values stored  until it's a priority to complete automation, so I might vote to keep this in the icebox as an artifact until automation is done.

**Comment by jilladams** [comment]
(Updated ticket body to reflect that stance.)

**Comment by FranECross** [comment]
Closing; automation is almost complete, and we can always resurrect if needed.
