### ISSUE TITLE
[Figma Migration] Move Facility Locator Files to Figma

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-cms#16665]
## Description

The Facility Locator Sketch files need to be imported into VA Figma because the Sketch license ends on February 16th,  2024.
Public Websites and Facilities files that are in the CMS Figma account will need to be migrated to the VA Figma folder "CMS Editor Experiences" no later than March 29, 2024.

Note: Do not move until February 1, 2024 AND all comments are resolved

## Acceptance criteria

- [x] Sketch file imported to VA Figma (this is currently tracked as a check mark in this file)
- [x] File Cleanup: Design components and styles relinked to Figma VADS

**Comment by thejordanwood** [comment]
Link to new file: [Facility Locator](https://www.figma.com/file/GvNVeG9GAXZaBpny7vNxZP/Facility-Locator?type=design&t=JIzfDGE6y5dGhmmo-6)
