### ISSUE TITLE
[Figma Migration] Move Income limits Files to Figma

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-cms#16677]
**Status 2024-02-28:**

- All files have been moved from Agile Six Figma to VA Platform Figma ahead of the March 29, 2024 deadline
- Next step is to convert components in design files to Figma VA design system components. This will be done whenever time permits. 

## Description

The Income limits Sketch files need to be imported into VA Figma because the Sketch license ends on February 16th, 2024.

Public Websites and Facilities files that are in the CMS Figma account will need to be migrated to the VA Figma folder "CMS Editor Experiences" no later than March 29, 2024.

## Acceptance criteria

- [x] Sketch file imported to VA Figma (this is currently tracked as a check mark in this file)
- [x] File Cleanup: Design components and styles relinked to Figma VADS

**Comment by thejordanwood** [comment]
Link to new file: [Income limits](https://www.figma.com/file/BzNT78xb10l2P3fKtKirDI/Income-Limits?type=design&node-id=0%3A1&mode=design&t=0ZeIHF5WHMO1h3gb-1)
