### ISSUE TITLE
[Figma Migration] Move Yellow ribbon search results Files to Figma

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-cms#16688]
## Description

The Yellow ribbon search results Sketch files need to be imported into VA Figma because the Sketch license ends on February 16th,  2024.

Public Websites and Facilities files that are in the CMS Figma account will need to be migrated to the VA Figma folder "CMS Editor Experiences" no later than March 29, 2024.

## Acceptance criteria

- [x] Sketch file imported to VA Figma (this is currently tracked as a check mark in this file)
- [ ] ~~File Cleanup: Design components and styles relinked to Figma VADS~~ No cleanup needs to happen. This has been combined with the [Yellow Ribbon](https://www.figma.com/file/xJoDDBZtQfrHkZQZaWnkp6/Yellow-Ribbon?type=design&t=FDwcjWSz9mOOeI2y-6) file.

**Comment by thejordanwood** [comment]
Link to new file: [Yellow Ribbon](https://www.figma.com/file/xJoDDBZtQfrHkZQZaWnkp6/Yellow-Ribbon?type=design&t=FDwcjWSz9mOOeI2y-6)
