### ISSUE TITLE
[Figma Migration] Move Learning center mvp Files to Figma

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-cms#16690]
## Description

The Learning center map Sketch files need to be imported into VA Figma because the Sketch license ends on February 16th,  2024.
Public Websites and Facilities files that are in the CMS Figma account will need to be migrated to the VA Figma folder "CMS Editor Experiences" no later than March 29, 2024.

## Acceptance criteria

- [x] Sketch file imported to VA Figma (this is currently tracked as a check mark in this file)
- [ ] ~~File Cleanup: Design components and styles relinked to Figma VADS~~ No cleanup needs to happen. This has been combined with the [Learning Center](https://www.figma.com/file/xUNKcUayBrfft8jaoLCjRw/Learning-Center?type=design&node-id=1%3A4938&mode=design&t=oBC2BJtgY7PFipxy-1) file.

**Comment by thejordanwood** [comment]
This has been combined into the [Learning Center](https://www.figma.com/file/xUNKcUayBrfft8jaoLCjRw/Learning-Center?type=design&node-id=1%3A4938&mode=design&t=oBC2BJtgY7PFipxy-1) file.
