### ISSUE TITLE
[Figma Migration] Move the VBA Content Specs Files to Figma

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-cms#16716]
## Description

The VBA Content Specs files need to be imported into VA Figma because the Sketch license ends on February 16th,  2024.

Public Websites and Facilities files that are in the CMS Figma account will need to be migrated to the VA Figma folder "CMS Editor Experiences" no later than March 29, 2024.

## Acceptance criteria

- [x] Agile Six Figma file imported to VA Platform Figma 
- [x] File Cleanup: Convert the components in the file to Figma components.

**Comment by thejordanwood** [comment]
Link to new file: [VBA Content Specs](https://www.figma.com/file/eECF81nwktbnKX889HiKhl/VBA-Content-Specs?type=design&node-id=2%3A143&mode=design&t=aqhnuKEviepxIwly-1)
