### ISSUE TITLE
[Figma Migration] Move the VAMC facilities Files to Figma

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-cms#16715]
## Description

The VAMC facilities files need to be imported into VA Figma because the Sketch license ends on February 16th,  2024.

Public Websites and Facilities files that are in the CMS Figma account will need to be migrated to the VA Figma folder "CMS Editor Experiences" no later than March 29, 2024.

## Acceptance criteria

- [x] Agile Six Figma imported to VA Platform Figma 
- [x] File Cleanup: No components need to be relinked, but comments should be resolved or copied over.

**Comment by thejordanwood** [comment]
Link to new file: [VAMC facilities](https://www.figma.com/file/bwnxdqh3b7W7Xp6KuQ4Sab/VAMC-facilities?type=design&t=JIzfDGE6y5dGhmmo-6)
