### ISSUE TITLE
[Figma Migration] Move the VBA Regional Office Prototype Files to Figma

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-cms#16717]
## Description

The  files need to be imported into VA Figma because the Sketch license ends on February 16th,  2024.

Public Websites and Facilities files that are in the CMS Figma account will need to be migrated to the VA Figma folder "CMS Editor Experiences" no later than March 29, 2024.

## Acceptance criteria

- [x] Agile Six Figma file imported to VA Platform Figma 
- [x] File Cleanup: No components need to be relinked, but comments should be resolved or copied over.

**Comment by thejordanwood** [comment]
This file has been combined with the [VBA Regional Office](https://www.figma.com/file/88Gw7fmUkDbheSAHjIpHn7/VBA-Regional-Office?type=design&t=KA5lyLJT5bfSizMh-6) file in the Facilities folder in the VA Platform Figma.

cc: @aklausmeier
