### ISSUE TITLE
Remove block_content_permissions from composer

### ISSUE THREAD

**Issue by Becapa** [department-of-veterans-affairs/va.gov-cms#16726]
## Description
In #16553 block_content_permissions was disabled in the Drupal config since those permissions are now handled in Drupal core. This ticket is to complete the removal of the module by removing it from composer.

## Acceptance criteria
- [ ] block_content_permissions module is removed from composer

**Comment by FranECross** [comment]
@Becapa Would this be considered Tech Debt, to be done when we can fit it in a sprint, or something that should be done fairly soon? Thanks in advance! cc @jilladams

**Comment by Becapa** [comment]
@FranECross I _think_ it would probably be considered Tech Debt, but I also think it should be done sooner than later. I don't think that it'll end up being any more than 1 point worth of work, so should be able to fit into a sprint pretty easily.
