### ISSUE TITLE
[UPDATE] pension and & veterans-pension in Service Taxonomy

### ISSUE THREAD

**Issue by davidmpickett** [department-of-veterans-affairs/va.gov-cms#16727]
### Which Taxonomy is this term for?

VA services taxonomy

### Link to existing term

https://prod.cms.va.gov/health-care/pension
https://prod.cms.va.gov/health-care/veterans-pension

### Rationale for updating this term

In [15748](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15748#issuecomment-1836599998) I requested that `pension` be removed in favor of the newly added `veterans-pension`. This didn't happen. Since then, the deprecated term has been given the official Health Service API ID which should have been given to the new term.

Want to resolve this before any content gets added.

### Which products will this term impact?

VBA Regional Office

### Acceptance Criteria
- [x] pension is archived/deleted
- [x] veterans-pension is updated to have the Health Service ID `Pensions`

**Comment by omahane** [comment]
@davidmpickett I have made this change.
