### ISSUE TITLE
[Figma Migration] Move the VA medical Centers forms Files to Figma

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-cms#16720]
## Description

The VA medical Centers forms files need to be imported into VA Figma because the Sketch license ends on February 16th,  2024.

Public Websites and Facilities files that are in the CMS Figma account will need to be migrated to the VA Figma folder "CMS Editor Experiences" no later than March 29, 2024.

## Acceptance criteria

- [x] Agile Six Figma file imported to VA Platform Figma 
- [x] File Cleanup: No components need to be relinked, but comments should be resolved or copied over.

**Comment by thejordanwood** [comment]
Link to new file: [VAMC forms](https://www.figma.com/file/nHc1wFJjZ1WfDqdG04xo73/VAMC-forms?type=design&t=JIzfDGE6y5dGhmmo-6)
