### ISSUE TITLE
Update styling of Character Counters on Text Fields

### ISSUE THREAD

**Issue by davidmpickett** [department-of-veterans-affairs/va.gov-cms#16732]
## User Story or Problem Statement

**AS A** Drupal CMS editor 
**I NEED** real-time feedback while typing in a text field 
**SO THAT** I can stay within the character limits

### Current behavior

The character count updates to indicate how many characters are remaining. 

![character_count_zoom](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/0635ea41-cade-4131-8f98-e7918eecd0fb)

When the user is between 5 and 0 characters remaining, an orange warning border is applied to the text field.
 
![character_count_warning](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/4e9f171f-7288-4363-8a08-b27bb52259c3)

When the user goes over the character limit, a dark red border is applied to the text field. --va-red-dark #CD2026.

![character_count_over](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/e92542cd-4f57-4a3a-a01d-a862d15db3e4)

### Desired behavior

No border should be applied to the text field in any state (aside from existing focus border). These borders are not very noticable and not in line with the [USWDS character counter](https://designsystem.digital.gov/components/character-count/)

When User has entered more characters than the character limit, change the styling of the status message to bold and red.

## Description or Additional Context 
#16659

## Steps for Implementation

Most could likely be handled here:
https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/docroot/themes/custom/vagovclaro/assets/scss/components/_textfield_counter.scss

There's a bit of code here that may need to be tweaked too:
https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/docroot/themes/custom/vagovclaro/assets/scss/components/_elements.scss

## Acceptance Criteria
- [x] No border should be applied to the text field in any state (aside from existing focus border)
- [x] When the user has < 0 character remaining change the styling of the text to bold and red (--va-red-dark #CD2026)
- [ ] Nothing else breaks (translations has an exception to textfield counter that might be worth double checking)
- [ ] Requires design review
- [ ] Requires accessibility review
- [ ] Notified CMS Team via Slack that this has been updated per prior collab cycle feedback

**Comment by davidmpickett** [comment]
@thejordanwood can you specify the CMS Design System color token for red that should be used?

**Comment by thejordanwood** [comment]
The red that we should use is --va-red-dark #CD2026.

**Comment by davidmpickett** [comment]
From Drupal Pre-Refinement, the coding work is probably only a 2 or 3, but putting it at a 5 to account for testing the various places it shows up

**Comment by davidmpickett** [comment]
Note this PR comment and slack conversation where we discovered that `current_length` class already has the color changing behavior we want the `remaining_count` class to have:
https://github.com/department-of-veterans-affairs/va.gov-cms/pull/16807#pullrequestreview-1830400970
https://dsva.slack.com/archives/C0FQSS30V/p1705605619240659

**Comment by jilladams** [comment]
Noting from planning: we don't know current process for asking for CMS team review. We'll need to chat with @gracekretschmer-metrostar and @michelle-dooley re: how they'd prefer we pull in CMS Team UX for style changes like this. (cc @thejordanwood in case you have news on this front)

**Comment by gracekretschmer-metrostar** [comment]
cc:ing @MDomngz and @srancour for awareness. 

Thanks for your patience, @jilladams, we will work to get you an answer in the next few days.

**Comment by jilladams** [comment]
Verified in prod. @MDomngz @srancour FYI that I'm going to close this ticket as complete, but if y'all have any design feedback on what was implemented, we can always reopen. Thanks!
