### ISSUE TITLE
Refresh GHA Tugboat credentials

### ISSUE THREAD

**Issue by JunTaoLuo** [department-of-veterans-affairs/va.gov-cms#16734]
## User Story or Problem Statement

As a maintainer of the GHA infrastructure, the GHA credentials should not be owned by any one engineer but instead be managed centrally along with other secrets and credentials.

## Description or Additional Context 

This is a followup to the PRs https://github.com/department-of-veterans-affairs/va.gov-cms/pull/16562 and https://github.com/department-of-veterans-affairs/va.gov-cms/pull/16279. There are two credentials: `TUGBOAT_API_TOKEN` and `LABEL_API_TOKEN`. The current tokens are generated by me as a temporary measure but should be refreshed with a centrally managed account or DevOps like all other credentials.

## Steps for Implementation

- Refer to the Tugboat documentation for the required tokens and permissions required.
- The tokens should be generated from a centrally managed account and updated in the Actions/Dependabot secrets environments

## Acceptance Criteria

- [ ] Tokens are refreshed and GHA Tugboat automation confirmed to be working as expected in this repo.

## Team

- [x] CMS Team
- [ ] Public Websites
- [ ] Facilities
- [ ] Accelerated Publishing

**Comment by JunTaoLuo** [comment]
@maortiz-27-80 @BerniXiongA6 let's chat about this for the next refinement since one of the credentials has an expiry date. The task is simple but I'll need help from DevOps to figure out ownership.

**Comment by BerniXiongA6** [comment]
Hi @JunTaoLuo since we canceled backlog refinement, did you need to chat with @maortiz-27-80 and/me about this ticket? Let us know. Thanks!

**Comment by JunTaoLuo** [comment]
Yup we should chat about this! The actual actions needed here are very quick but I just need to figure out who should own these credentials, thanks!

**Comment by BerniXiongA6** [comment]
OK @JunTaoLuo will grab time for @maortiz-27-80 you and me next week -- thank you!

**Comment by ndouglas** [comment]
@JunTaoLuo you've onboarded with access for @va-cms-bot, right? It should own the credentials used here. If not, onboarding should be fairly painless. See here: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14345

**Comment by JunTaoLuo** [comment]
Ah I don't think I ever onboard with that account. Would it be better for me to onboard with it now or work with someone who already has access?

**Comment by ndouglas** [comment]
I can do it 🤷🏻  NBD

**Comment by ndouglas** [comment]
This should be done now.

**Comment by JunTaoLuo** [comment]
Thanks @ndouglas! I'll keep an eye out and see if everything works as expected when the workflows trigger.

**Comment by JunTaoLuo** [comment]
Looks like everything is working thanks!
