### ISSUE TITLE
Drush 10 causes 500 internal server error /admin/modules page 

### ISSUE THREAD

**Issue by ElijahLynn** [department-of-veterans-affairs/va.gov-cms#1676]
Steps to reproduce:
1. Upgrade to Drush 10 `composer require drush/drush`
1. Login as admin user
1. Visit https://prod.cms.va.gov/admin/modules (white screen)
1. See logs - https://prod.cms.va.gov/admin/reports/dblog

Notes: We just deployed CMS Export (tome_sync) and I noticed this while looking at logs. I don't know if this was the cause. 

> Warning: require(/var/www/cms/docroot/vendor/composer/../drush/drush/lib/Drush/Drush.php): failed to open stream: No such file or directory in require() (line 112 of /var/www/cms/docroot/vendor/symfony/class-loader/ApcClassLoader.php)
> #0 /var/www/cms/docroot/core/includes/bootstrap.inc(600): _drupal_error_handler_real(2, 'require(/var/ww...', '/var/www/cms/do...', 112, Array)
> #1 /var/www/cms/docroot/vendor/symfony/class-loader/ApcClassLoader.php(112): _drupal_error_handler(2, 'require(/var/ww...', '/var/www/cms/do...', 112, Array)
> #2 /var/www/cms/docroot/vendor/symfony/class-loader/ApcClassLoader.php(112): require()
> #3 [internal function]: Symfony\Component\ClassLoader\ApcClassLoader->loadClass('Drush\\Drush')
> #4 [internal function]: spl_autoload_call('Drush\\Drush')
> #5 /var/www/cms/docroot/modules/contrib/webform/src/WebformHelpManager.php(1729): class_exists('\\Drush\\Drush')
> #6 /var/www/cms/docroot/modules/contrib/webform/src/WebformHelpManager.php(143): Drupal\webform\WebformHelpManager->initHelp()
> #7 /var/www/cms/docroot/core/lib/Drupal/Component/DependencyInjection/Container.php(297): Drupal\webform\WebformHelpManager->__construct(Object(Drupal\Core\Session\AccountProxy), Object(Drupal\Core\Config\ConfigFactory), Object(Drupal\Core\Extension\ModuleHandler), Object(Drupal\Core\State\State), Object(Drupal\tome_static\ResettablePathMatcher), Object(Drupal\webform\WebformAddonsManager), Object(Drupal\webform\WebformLibrariesManager), Object(Drupal\webform\Plugin\WebformElementManager))
> #8 /var/www/cms/docroot/core/lib/Drupal/Component/DependencyInjection/Container.php(173): Drupal\Component\DependencyInjection\Container->createService(Array, 'webform.help_ma...')
> #9 /var/www/cms/docroot/core/lib/Drupal.php(158): Drupal\Component\DependencyInjection\Container->get('webform.help_ma...')
> #10 /var/www/cms/docroot/modules/contrib/webform/webform.module(50): Drupal::service('webform.help_ma...')
> #11 [internal function]: webform_help('system.modules_...', Object(Drupal\Core\Routing\CurrentRouteMatch))
> #12 /var/www/cms/docroot/core/lib/Drupal/Core/Extension/ModuleHandler.php(392): call_user_func_array('webform_help', Array)
> #13 /var/www/cms/docroot/core/modules/help/src/Plugin/Block/HelpBlock.php(102): Drupal\Core\Extension\ModuleHandler->invoke('webform', 'help', Array)
> #14 /var/www/cms/docroot/core/modules/block/src/BlockViewBuilder.php(171): Drupal\help\Plugin\Block\HelpBlock->build()
> #15 [internal function]: Drupal\block\BlockViewBuilder::preRender(Array)
> #16 /var/www/cms/docroot/core/lib/Drupal/Core/Security/DoTrustedCallbackTrait.php(100): call_user_func_array(Array, Array)
> #17 /var/www/cms/docroot/core/lib/Drupal/Core/Render/Renderer.php(781): Drupal\Core\Render\Renderer->doTrustedCallback(Array, Array, 'Render #pre_ren...', 'silenced_deprec...', 'Drupal\\Core\\Ren...')
> #18 /var/www/cms/docroot/core/lib/Drupal/Core/Render/Renderer.php(372): Drupal\Core\Render\Renderer->doCallback('#pre_render', Array, Array)
> #19 /var/www/cms/docroot/core/lib/Drupal/Core/Render/Renderer.php(444): Drupal\Core\Render\Renderer->doRender(Array)
> #20 /var/www/cms/docroot/core/lib/Drupal/Core/Render/Renderer.php(200): Drupal\Core\Render\Renderer->doRender(Array, false)
> #21 /var/www/cms/docroot/core/lib/Drupal/Core/Template/TwigExtension.php(501): Drupal\Core\Render\Renderer->render(Array)
> #22 /var/www/cms/docroot/sites/default/files/php/twig/5eae1add66715_page.html.twig_H0JnImIFNJpT-71D31S2D_Oqe/z_NIBZCJxf124Qlnp45M3M-iqrs3fzTmthOjS-viOS0.php(86): Drupal\Core\Template\TwigExtension->escapeFilter(Object(Drupal\Core\Template\TwigEnvironment), Array, 'html', NULL, true)
> #23 /var/www/cms/docroot/vendor/twig/twig/src/Template.php(455): __TwigTemplate_ae524c8d3791f238ac3d88d337d5bd42be8431ad5f6db44ff1953906db2260b6->doDisplay(Array, Array)
> #24 /var/www/cms/docroot/vendor/twig/twig/src/Template.php(422): Twig\Template->displayWithErrorHandling(Array, Array)
> #25 /var/www/cms/docroot/vendor/twig/twig/src/Template.php(434): Twig\Template->display(Array)
> #26 /var/www/cms/docroot/core/themes/engines/twig/twig.engine(64): Twig\Template->render(Array)
> #27 /var/www/cms/docroot/core/lib/Drupal/Core/Theme/ThemeManager.php(384): twig_render_template('core/themes/sev...', Array)
> #28 /var/www/cms/docroot/core/lib/Drupal/Core/Render/Renderer.php(431): Drupal\Core\Theme\ThemeManager->render('page', Array)
> #29 /var/www/cms/docroot/core/lib/Drupal/Core/Render/Renderer.php(200): Drupal\Core\Render\Renderer->doRender(Array, false)
> #30 /var/www/cms/docroot/core/lib/Drupal/Core/Template/TwigExtension.php(501): Drupal\Core\Render\Renderer->render(Array)
> #31 /var/www/cms/docroot/sites/default/files/php/twig/5eae1add66715_html.html.twig_wGUMjb2qZFyGY4FmLQkjMMbMb/rrvWaqCADowRmGy1z0VUYGcUri5i7sNnQ1ob9nTIR-w.php(96): Drupal\Core\Template\TwigExtension->escapeFilter(Object(Drupal\Core\Template\TwigEnvironment), Array, 'html', NULL, true)
> #32 /var/www/cms/docroot/vendor/twig/twig/src/Template.php(455): __TwigTemplate_04f2059601675f506419af2570b9a2ededf949d8b1ebc2d27bdf103e9690f609->doDisplay(Array, Array)
> #33 /var/www/cms/docroot/vendor/twig/twig/src/Template.php(422): Twig\Template->displayWithErrorHandling(Array, Array)
> #34 /var/www/cms/docroot/vendor/twig/twig/src/Template.php(434): Twig\Template->display(Array)
> #35 /var/www/cms/docroot/core/themes/engines/twig/twig.engine(64): Twig\Template->render(Array)
> #36 /var/www/cms/docroot/core/lib/Drupal/Core/Theme/ThemeManager.php(384): twig_render_template('themes/custom/v...', Array)
> #37 /var/www/cms/docroot/core/lib/Drupal/Core/Render/Renderer.php(431): Drupal\Core\Theme\ThemeManager->render('html', Array)
> #38 /var/www/cms/docroot/core/lib/Drupal/Core/Render/Renderer.php(200): Drupal\Core\Render\Renderer->doRender(Array, false)
> #39 /var/www/cms/docroot/core/lib/Drupal/Core/Render/MainContent/HtmlRenderer.php(147): Drupal\Core\Render\Renderer->render(Array)
> #40 /var/www/cms/docroot/core/lib/Drupal/Core/Render/Renderer.php(573): Drupal\Core\Render\MainContent\HtmlRenderer->Drupal\Core\Render\MainContent\{closure}()
> #41 /var/www/cms/docroot/core/lib/Drupal/Core/Render/MainContent/HtmlRenderer.php(148): Drupal\Core\Render\Renderer->executeInRenderContext(Object(Drupal\Core\Render\RenderContext), Object(Closure))
> #42 /var/www/cms/docroot/core/lib/Drupal/Core/EventSubscriber/MainContentViewSubscriber.php(90): Drupal\Core\Render\MainContent\HtmlRenderer->renderResponse(Array, Object(Symfony\Component\HttpFoundation\Request), Object(Drupal\Core\Routing\CurrentRouteMatch))
> #43 [internal function]: Drupal\Core\EventSubscriber\MainContentViewSubscriber->onViewRenderArray(Object(Symfony\Component\HttpKernel\Event\GetResponseForControllerResultEvent), 'kernel.view', Object(Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher))
> #44 /var/www/cms/docroot/core/lib/Drupal/Component/EventDispatcher/ContainerAwareEventDispatcher.php(111): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseForControllerResultEvent), 'kernel.view', Object(Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher))
> #45 /var/www/cms/docroot/vendor/symfony/http-kernel/HttpKernel.php(156): Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher->dispatch('kernel.view', Object(Symfony\Component\HttpKernel\Event\GetResponseForControllerResultEvent))
> #46 /var/www/cms/docroot/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
> #47 /var/www/cms/docroot/modules/contrib/simple_oauth/src/HttpMiddleware/BasicAuthSwap.php(67): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
> #48 /var/www/cms/docroot/core/lib/Drupal/Core/StackMiddleware/Session.php(57): Drupal\simple_oauth\HttpMiddleware\BasicAuthSwap->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
> #49 /var/www/cms/docroot/core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php(47): Drupal\Core\StackMiddleware\Session->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
> #50 /var/www/cms/docroot/core/modules/page_cache/src/StackMiddleware/PageCache.php(106): Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
> #51 /var/www/cms/docroot/core/modules/page_cache/src/StackMiddleware/PageCache.php(85): Drupal\page_cache\StackMiddleware\PageCache->pass(Object(Symfony\Component\HttpFoundation\Request), 1, true)
> #52 /var/www/cms/docroot/core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php(47): Drupal\page_cache\StackMiddleware\PageCache->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
> #53 /var/www/cms/docroot/core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php(52): Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
> #54 /var/www/cms/docroot/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
> #55 /var/www/cms/docroot/core/lib/Drupal/Core/DrupalKernel.php(694): Stack\StackedHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
> #56 /var/www/cms/docroot/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
> #57 {main}
> .

**Comment by indytechcook** [comment]
This is caused by Drush 10.  The follow up deploy will put the version back to 8.  Doing a in place downgrade is high risk.  If it's deemed necessary to downgrade before the next deploy, we can an off cycle deploy of the current code base to drush 8.

Drush 10 was upgrade to do the initial tome sync export.  It's not required for updates.

**Comment by indytechcook** [comment]
Linking to #1230

**Comment by ElijahLynn** [comment]
Thank you, good catch!
