### ISSUE TITLE
Change management for users of vets-api during Lighthouse v1 adoption before Lighthouse v0 deprecation

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#16778]
## User Story or Problem Statement
#15000 identified 1 potential consumer (1010 form) of vets-api who may want to use Lighthouse v1 adoption before Lighthouse v0 deprecation (Lighthouse estimates June 1, 2024).

## Acceptance Criteria
- [ ] @mmiddaugh: Find and update source of truth for teams who want to use vets-api to get more information about what's available v1 vs v0 and the timeline.

**Comment by xiongjaneg** [comment]
From Michelle: Is there a place for teams who want to use vets-api to get more information about what's available and the timeline?

From Eli: Yes, there is documentation.

**Comment by mmiddaugh** [comment]
[Request submitted to vfs-platform support ](https://dsva.slack.com/archives/CBU0KDSB1/p1706737811651779) requesting guidance for best place to document the endpoints

**Comment by mmiddaugh** [comment]
Per Platform: All endpoints exposed through Vets-API must be thoroughly documented with Swagger. 
No Swagger spec was found for facilities. 

- [Platform documentation] https://depo-platform-documentation.scrollhelp.site/developer-docs/documentation
- [Example API documentation](https://github.com/department-of-veterans-affairs/vets-api/blob/master/modules/appeals_api/app/swagger/decision_reviews/v2/api_description.md)
