### ISSUE TITLE
Document all CMS Slack Channels in Confluence

### ISSUE THREAD

**Issue by EWashb** [department-of-veterans-affairs/va.gov-cms#16783]
## User Story or Problem Statement

As the Product Owner for the Drupal CMS I need to know what all Slack channels exist for the CMS work and what they used for/how they fit into the CMS workflow.

As a new CMS team member, I need to understand what CMS slack channels exist and what they are used for so that I can ensure no monitors, requests, or work-related items go unnoticed. 

## Description or Additional Context 

there are many CMS-related channels such as:
#sitewide-cms-platform
#cms-support
#cms-notifications

...and more. 

## Steps for Implementation
All current CMS-related slack channels are documented in the CMS Transition space in Confluence. Each channel has a description of its use and importance to the scope of the CMS work. 

## Acceptance Criteria
- [ ] All CMS slack channels are documented in the Platform CMS confluence space: documentation includes the description and what they are used for within the scope of the CMS work

## Team
Please check the team(s) that will do this work.

- [X] CMS Team
- [ ] Public Websites
- [ ] Facilities
- [ ] Accelerated Publishing

**Comment by EWashb** [comment]
@maortiz-27-80 @BerniXiongA6 here's a first draft of the ticket regarding documenting slack channels. Not sure if there is an overall documentation epic to add it to

**Comment by EWashb** [comment]
It is probably important to have Nate or another dev help curate this list because there could be dev-specific channels that I'm not aware of

**Comment by maortiz-27-80** [comment]
Thanks, @EWashb !  I've created a "General Operations" page as of now: https://vfs.atlassian.net/wiki/spaces/PCMS/pages/2897707352/General+Operations.  We can noodle on renaming, but in addition to slack channels, I've added a section for email groups.  Maybe we can add in team meetings here too.  Berni and I will collab to see what makes sense.  cc: @BerniXiongA6

**Comment by EWashb** [comment]
Thank you at @maortiz-27-80! Thank you for the extra attention to additional comms channels that we have. I agree that our overall focus should be on determining and documenting our channels and additional operations

**Comment by maortiz-27-80** [comment]
@BerniXiongA6 - I added you as an assignee.  Can you review what i have so far on the [General Operations page](https://vfs.atlassian.net/wiki/spaces/PCMS/pages/2897707352/General+Operations) and help me fill out the, "Email Group" piece?  I'm open to feedback and let me know if there are other things I should consider adding.  Thanks! - M

**Comment by maortiz-27-80** [comment]
Closing and marking as complete.  cc: @BerniXiongA6 @EWashb @michelle-dooley @gracekretschmer-metrostar
