### ISSUE TITLE
Allow for different vets-website build targets in next-build

### ISSUE THREAD

**Issue by tjheffner** [department-of-veterans-affairs/va.gov-cms#16782]
## Requirements
In https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14974, we introduced vets-website assets to next-build. This uses the `localhost` build of vets-website. This is good, but we need to get different build types available for different environments, or testing locally. i.e [--buildtype=vagovprod](https://github.com/department-of-veterans-affairs/vets-website/blob/main/package.json#L11C22-L11C22) as seen in vets-website.

The available [buildtype options for vets-website ](https://github.com/department-of-veterans-affairs/vets-website/blob/0905225ab314b85ab9a14949d1614f30a18ef5b7/src/site/constants/environments.js)are:
`localhost`
`vagovdev`
`vagovstaging`
`vagovprod`

```[tasklist]
### Acceptance criteria
- [ ] Vets-website assets can be sourced from any vets-website build type, not only localhost.
- [x] Tugboat builds as expected without errors and all assets present using a non-localhost vets-website buildtype. (`vagovprod`? `vagovdev`?)
```

## Background & implementation details

The symlink setup will likely need to be adjusted, both locally and for different CI environments depending on the buildtype used. vets-website outputs to different directories based on the build type.

e.g. with `localhost` it outputs to `vets-website/build/localhost/generated`. With `vagovprod`, that directory updates to `vets-website/build/vagovprod/generated`.

next-build will need to source the assets from `next-build/public/generated` no matter the build type. We may need to re-build vets-website & move the assets vs symlinking directly to the generated output specific to localhost. This would have the side effect of adding vets-website build times to most of our local static builds. For my machine, that is 6 minutes of additional build time.
```
webpack 5.76.0 compiled with 2 warnings in 367955 ms
./script/../build/vagovprod/generated/vendor.entry.js -> ./script/../build/vagovprod/generated/shared-modules.entry.js
✨  Done in 372.31s.
```

**Comment by tjheffner** [comment]
content-build downloads assets each run in this way, this is probably faster than doing a full vets-website build
https://github.com/department-of-veterans-affairs/content-build/blob/main/src/site/stages/build/plugins/download-assets.js
https://github.com/department-of-veterans-affairs/content-build/blob/main/src/site/constants/buckets.js

locally we would still want to symlink to the adjacent directory so local changes could be tested easily

**Comment by timcosgrove** [comment]
I think this is covered by #16853 but putting into refinement.
