### ISSUE TITLE
Install task failing on SQL import

### ISSUE THREAD

**Issue by indytechcook** [department-of-veterans-affairs/va.gov-cms#1679]
We have several instances where the database install task is failing on dev shop

Examples:
* http://devshop.cms.va.gov/node/21188
* http://devshop.cms.va.gov/node/20489

I turned up logging on the devshop server by editing the following file:

`/var/aegir/devmaster-1.x/profiles/devmaster/modules/devshop/devshop_projects/drush/devshop_provision.drush.inc`

Line 553 add `-vvv` to `$command = "drush -vvv {$alias} sqlq 'SOURCE {$file_to_import}'";`

**Comment by ElijahLynn** [comment]
I changed the hosting queue task runner from 3 to 1. It was set to 3 before the 22nd I believe but the hostmaster verify task was run then to reimport the removal of system node, so I wonder if that setting actually started taking effect then. 

The last 4 PRs have passed since I made that change.

**Comment by ElijahLynn** [comment]
If this resolves it I'll write up a more formal hypothesis of what (I think) happened.

**Comment by ElijahLynn** [comment]
We removed system node because it wasn't supposed to be there to begin with and the refactoring to yaml-tasks to yaml-tests in https://github.com/department-of-veterans-affairs/va.gov-cms/pull/1304 was somehow picking it up in its PATH and failing egress HTTPS requests in the WEB build, which was configured with the right VA certs for Node 10.5 but the system node 13 wasn't picking them up.

**Comment by ElijahLynn** [comment]
I just triggered 4 installs and test runs for 4 failing PRs and we will see how they do: 
1. #1577 
1. #1672 
1. #1677 
1. #1639 

![image](https://user-images.githubusercontent.com/1504756/81026777-17f92600-8e30-11ea-97f6-9b4397da6257.png)

**Comment by ElijahLynn** [comment]
I have started linking other PRs to this Issue and think we may want to rename this issue to something around general CI failures and maybe make it an Epic.

**Comment by ElijahLynn** [comment]
> I just triggered 4 installs and test runs for 4 failing PRs and we will see how they do with task queue set to 1 now:
> 
> 1. #1577
> 2. #1672
> 3. #1677
> 4. #1639

1-3 failed and #1639 failed with this error > https://github.com/department-of-veterans-affairs/va.gov-cms/pull/1639#issuecomment-623848143

**Comment by ElijahLynn** [comment]
It appears that this worked and all failures today appeared to be legitimate failures.

**Comment by ElijahLynn** [comment]
Closing out, things appear stable right now and this isn't happening anymore.
