### ISSUE TITLE
Add script tag to header injection markup

### ISSUE THREAD

**Issue by it-harrison** [department-of-veterans-affairs/va.gov-cms#16799]
### User story
As a user of a Teamsite I want the injected header to render properly after `vets-website` and `content-build` have been updated to optimize bundle size.

### Engineering notes / background
There is an effort to tune the webpack config on `vets-website` to reduce bundle size, [PR here](https://github.com/department-of-veterans-affairs/vets-website/pull/27406). The effect of this optimization is to require a new file `runtime.entry.js` in the `head` of pages where javascript is run. This means that a script tag must be added to the header include in `content-build`, [PR here](https://github.com/department-of-veterans-affairs/content-build/pull/1841). It also means that `runtime.entry.js` must be added to the [Teamsite template](https://depo-platform-documentation.scrollhelp.site/developer-docs/teamsite-overview#TeamSiteoverview-ScriptsandTeamSiteAdministration). Specifcally: 

`<script type="text/javascript" src="https://prod-va-gov-assets.s3-us-gov-west-1.amazonaws.com/generated/runtime.entry.js"></script>`

needs to be added to the Teamsite template.

**Complication**: `runtime.entry.js` will not be in the prod S3 bucket until the `vets-website` PR is deployed to prod. As soon as this happens the injected headers on Teamsite pages in prod will break because they lack the runtime.entry.js file and the javascript will not run. So it will be important to coordinate deployments to minimize / eliminate down time of the injected header. 

**Question**: could the script tag be added to the header template and deployed slightly before the `vets-website`/`content-build` PRs are deployed to prod? This would result in a 404 on Teamsites but shouldn't break anything. I realize, however, that Teamsites CI might not allow this to happen. 

### Analytics considerations
none known

### Quality / testing notes
using the `proxy-rewrite-entry` 

without the runtime.entry.js file in the head tag:

<img width="1154" alt="Screenshot 2024-01-10 at 8 55 20 AM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/8867779/09103b86-5802-41d7-97b8-1815705bd772">

with the runtime.entry.js file in the head tag:

<img width="1113" alt="Screenshot 2024-01-10 at 9 08 34 AM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/8867779/cc161440-1624-4937-ab38-8fedda58bde6">

## Acceptance criteria

>Consider
> - Design / Accessibility reviews
> - Collab cycle requirements
> - Device sizes (mobile first)
> - Documentation updates / Change management
< - [Content model documentation](https://prod.cms.va.gov/admin/structure/cm_document)
> - Testing notes

- [ ]

**Comment by jilladams** [comment]
@it-harrison : Thanks for the ticket, and apologies, but I do think this is outside Public Websites team scope. We have no purview over TeamSite deployments or CI. We manage the proxy-rewrite application which is called by the TeamSite templates. 

I think you'll need to talk to TeamSite technical owners re: getting TeamSite templates modified.  Last I knew (early 2023), TeamSite technical ownership sits with OI&T. Our contacts there most recently were: 
* "Kotian, Sandeep (Veterans EZ Info, Inc.)" <Sandeep.Kumar@va.gov>,
* "Smelley, Bradley S." <Bradley.Smelley@va.gov>

I'm gonna go ahead and close this ticket with that in mind. If you'd like to cc me and Dave Conlon in your reachout to TeamSite owners, please feel free.
