### ISSUE TITLE
FE: Add/adjust messaging for Search to handle all success/failure scenarios

### ISSUE THREAD

**Issue by randimays** [department-of-veterans-affairs/va.gov-cms#16801]
## Description
On 1/9/24, we had an outage on the `v0/search` endpoint caused by [Search.gov's planned maintenance windows](https://dsva.slack.com/archives/C05THHJHH2R/p1700681474981739). We saw 500s during the ~5:00-5:30pm CST time period that triggered Datadog alerts in the #public-websites-monitoring Slack channel.. [An incident was kicked off](https://vagov.ddog-gov.com/incidents/117) to triage the issue.

We sent an email to the Search.gov support team to clarify "planned maintenance windows": Are deploys guaranteed during this time, or are these windows where deploys **may** take place? [This Slack message](https://dsva.slack.com/archives/C05THHJHH2R/p1704908199722959) outlines their reply (summary: they plan to deploy every Tues/Thurs during 3-6pm EST).

We are making vets-api adjustments in #16784 to better handle Search.gov maintenance windows. Our FE messaging needs to handle 5 distinct scenarios (some messaging already exists):

- Successful call with results returned from Search.gov
- Successful call with no results for search term from Search.gov
- Successful call with "no results" (maintenance window) from Search.gov**
- Failed call to Search.gov (successful vets-api response)
- Failed call to vets-api endpoint

****Need:** Design input for messaging on maintenance window scenarios.

### User story

**AS A** Veteran, their family member, caregiver, or survivor
**I WANT** to see meaningful, helpful messaging when VA.gov Search doesn't return results for a variety of reasons
**SO THAT** I'm not confused or annoyed during usage.

## Acceptance criteria

- [x] Successful call with results returned from Search.gov returns message TBD
- [x] Successful call with no results for search term from Search.gov returns message TBD
- [ ] Successful call with "no results" (maintenance window) from Search.gov returns message TBD
- [ ] Failed call to Search.gov (successful vets-api response) returns message TBD
- [ ] Failed call to vets-api endpoint returns message TBD

**Comment by FranECross** [comment]
@thejordanwood Randi has noted in the ticket that we'll need some Design input on the various messaging. Shall I create a ticket for you, or do you want to async on this ticket? I'm happy to do either. TIA!  cc @randimays @jilladams

**Comment by thejordanwood** [comment]
@FranECross We can async on this ticket! I can pick it up next sprint.

**Comment by thejordanwood** [comment]
@FranECross @jilladams @randimays Some of these already have messaging, but I'll put them here again for clarity. 

1. Successful call with results returned from Search.gov

We should continue to show the message "Showing 1-10 of X results for "[search term]" below the search input field. 

<img width="742" alt="Screenshot 2024-01-22 at 12 37 30 PM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/104526584/956a13e3-3e63-4e2e-8774-0f87ea958811">

2. Successful call with no results for search term from Search.gov

Continue to show the message "We didn't find any results for “[search term].” Try using different words or checking the spelling of the words you're using." below the search input field. 

<img width="755" alt="Screenshot 2024-01-22 at 12 29 51 PM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/104526584/9c9dffba-d643-4b04-a796-2cf92582689a">

3. Successful call with "no results" (maintenance window) from Search.gov**

We can use the [default maintenance banner](https://design.va.gov/components/banner/maintenance#examples) for this while the maintenance window is active . I don't think we need to use the Warning banner beforehand. I've altered the [suggested scheduled downtime notification](https://design.va.gov/components/banner/maintenance#examples) to fit this scenario. Let's say: 

**Search maintenance**
We’re working on Search [VA.gov](http://va.gov/) right now. If you have trouble using the search tool, check back after we’re finished. Thank you for your patience.
**Date:** Day, Date, Year
**Start/End time:** 0:00 a.m. to 00:00 a.m. ET

5. Failed call to Search.gov (successful vets-api response) AND Failed call to vets-api endpoint
We can keep using this error message in an [error alert](https://design.va.gov/components/alert#error-alert):

**Your search didn’t go through**
We’re sorry. Something went wrong on our end, and your search didn’t go through. Please try again.

**Comment by randimays** [comment]
@thejordanwood Does 3 include the messaging for 4 also?

**Comment by thejordanwood** [comment]
@randimays I updated the numbers in my post to make more sense. I lumped the 2 "Fail to call" into 4 &5. I think they should both get the generic "Your search didn't go through" messaging.

**Comment by thejordanwood** [comment]
@jilladams @FranECross I'm moving this back to Ready. I can make any updates to copy that are needed whenever FE starts to implement. 

I'll remove my points on this too. If you need that for reporting purposes, I had reported this ticket as a 2.

**Comment by jilladams** [comment]
PR where API error messaging / codes were updated: https://github.com/department-of-veterans-affairs/vets-api/pull/15337

**Comment by jilladams** [comment]
@FranECross FYI pulling this into sprint for Ari.

**Comment by jilladams** [comment]
Work is complete and deployed here. Closing, but @ariperez if I've misunderstood, please reopen and comment what I missed.

**Comment by ariperez** [comment]
Work is complete. Banner will show during maintenance hours is no search results are returned from search.gov

**Comment by FranECross** [comment]
@ariperez Will you please confirm that the error messages that will display during maintenance windows, and during API failed calls are as outlined by Jordan in her comment above (and I've pasted below). Apologies, but I'm not sure I'm interpreting your comment just above correctly. Thanks in advance! 

From Jordan: 
**Successful call with "no results" (maintenance window) from Search.gov**
We can use the [default maintenance banner](https://design.va.gov/components/banner/maintenance#examples) for this while the maintenance window is active . I don't think we need to use the Warning banner beforehand. I've altered the [suggested scheduled downtime notification](https://design.va.gov/components/banner/maintenance#examples) to fit this scenario. Let's say:

**Search maintenance message:**
We’re working on Search [VA.gov](http://va.gov/) right now. If you have trouble using the search tool, check back after we’re finished. Thank you for your patience.
Date: Day, Date, Year
Start/End time: 0:00 a.m. to 00:00 a.m. ET

**4 & 5. Failed call to Search.gov (successful vets-api response) AND Failed call to vets-api endpoint**
We can keep using this error message in an [error alert](https://design.va.gov/components/alert#error-alert):

Your search didn’t go through
We’re sorry. Something went wrong on our end, and your search didn’t go through. Please try again.

**Comment by ariperez** [comment]
@FranECross , correct.  The code currently matches the scenarios outlined by Jordan.
