### ISSUE TITLE
Test Drupal 10.2 version upgrade

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#16806]
# Description

CMS Team has a D10 patch upgrade to 10.2 in flight, and needs our teams' review to verify no regressions. 

PR: https://github.com/department-of-veterans-affairs/va.gov-cms/pull/16620

Edmund flagged it mostly needs smoke tests, nothing huge that needs specific looks. 

## Testing notes
Per Daniel, typical procedure: 

- Pick from the most heavily modified/used entities/nodes and go through CRUD operations as a non-admin.
- Poke around admin areas looking for any major changes to the UI/config forms
- Look at Drupal logs to see if there are any warnings/errors
- Sometimes also poke around product related Views (eg: VA Forms) and see if they are still working/filtering/etc.

## ACs

- [x] testing completed against the opened PR in CMS-provided Tugboat
- [x] Code review provided on PR 16620, by 1/16/24

**Comment by Becapa** [comment]
As a non-admin user I verified that I could create and edit Events, Benefits Detail Pages, Benefits Hub Landing Pages.
As an admin I verified that Create, Edit, and Delete worked fine on Campaign Landing Pages.
I clicked through several of the admin / config menus & pages and never came across any weirdness.
There was also nothing in the drupal logs to indicate anything out of the ordinary.
