### ISSUE TITLE
Draft detailed content spec for expanded police contact information

### ISSUE THREAD

**Issue by davidmpickett** [department-of-veterans-affairs/va.gov-cms#16812]
## User Story or Problem Statement
AS A Drupal Engineer
I NEED detailed guidance on how VA police contact information will work as a VAMC non-clinical service
SO THAT I can implement it in Drupal

## Description or Additional Context 

https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16415

## Acceptance Criteria
- [x] Fields and field properties and documented 
- [x] Reviewed with engineering & product
- [x] Subsequent tickets are updated
- ~~[ ] (Possibly) send to CMS Collab Cycle~~

## Team
Please check the team(s) that will do this work.

- [ ] CMS Team
- [ ] Public Websites
- [x] Facilities
- [ ] Accelerated Publishing

**Comment by davidmpickett** [comment]
Entities to spec:
- Term: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16811
- View: health_care_service_names_and_descriptions:entity_reference_non_clinical_services
   - This looks like it will automagically update the select list on VAMC Facility Non-clinical Service so long as the Type of Care for the term is set to "Non-clinical services"

**Comment by davidmpickett** [comment]
End of sprint 101 update - did some initial research and docmentation. Still have work to do, but have a good handle on the scope. 2 point done, 3 left for 102

@jilladams @xiongjaneg

**Comment by davidmpickett** [comment]
Shared on slack for review https://dsva.slack.com/archives/C0FQSS30V/p1707174166038499

**Comment by davidmpickett** [comment]
Updated content model: https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1698092447003/c969debf289d4e43e3cdd293d90053c2c137c338?wid=0-1698094046232

**Comment by davidmpickett** [comment]
Simplified content model: https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1698092447003/c969debf289d4e43e3cdd293d90053c2c137c338?wid=0-1707178993055

**Comment by swirtSJW** [comment]
I looked at the model and it makes sense to me, though it should really be @omahane who gives it a looky see.

**Comment by davidmpickett** [comment]
@mmiddaugh @aklausmeier 

Questions that I raised in UX Sync:

**1) Is Drupal now the source of truth for VA Police contact information?** 

- Will we ever again need to import data from the CSV maintained by Office of Security and Law Enforcement? 
- Do we need to provide an export of the data in Drupal to them for any reporting processes? 
- This isn't the most urgent question to answer, but it may impact some aspects of Drupal implementation 

<img width="600" alt="Screenshot 2024-02-09 at 12 39 31 PM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/8824bc76-3a31-48a2-a319-94de1de54de5">

2) **How will system-level and facility-level contact information play together?**

- As we move to a model where contact information can be facility specific (but doesn't have to be), are we keeping the requirement of one number per system? 
- For those systems that basically have two equally important numbers, should we allow them to leave the system phone number blank if they've provided facility-specific information via Non-clinical services? e.g. Some kind of required logic that makes system-level field OR a non-clinical service required? 
 - Relevant for #16813
- Do we want facility-specific information to be filtered dynamically by facility? Or are we keeping it all in the static portion of the page?
  - Relevant for #16810

<img width="689" alt="Screenshot 2024-02-09 at 12 41 45 PM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/d2f31940-da57-457c-a7be-691ca832b582">

**Comment by davidmpickett** [comment]
@xiongjaneg - I have shared this for review and updated following tickets:  
- #16813 
- #16814
- #16811

I assume we're not going take this to CMS collab cycle given everything going on right now, but it's one of the default ACs for any content model change, so want to make sure you make that call officially.

**Comment by xiongjaneg** [comment]
Yup, removing that AC for now. Just met with Grace the CMS Team PM and they're working on incorporating into the Platform collab cycle process, so lots tbd.
