### ISSUE TITLE
[Header] FE: Clean up mega menu styles and markup

### ISSUE THREAD

**Issue by randimays** [department-of-veterans-affairs/va.gov-cms#16816]
## Status
**[2024-07-02]** Transfer to the Design System Team for when they componentize the header/footer.

## Elevator Statement
This ticket is for the **Mega Menu** specifically. Given that our mega menu code is complex, while we're working on the Federal Header & Footer, we should do a quick audit of opportunities to simplify the markup and styles.

## Description
While working on the Federal Header / Footer project, Styles, the engineer has identified opportunities to clean-up the markup and styles. Feedback indicates that cleaning up both would make our lives easier, and quite possibly have a small positive impact on Veterans by maybe making load times better, as well as making the injected header easier to manage and maintain.

The engineer will estimate this ticket, and if the effort is negligible, this work will be done as a fast follow to the main 1st quarter project work.

The CodePen prototype was created by Laura Flannery to support the Federal Header/Footer research effort of the new header and footer, and this will be used as a guideline for changes to the Header/Footer. 

- [Codepen prototype](https://codepen.io/Sitewide-Team/pen/abModNV/ac9526217476cb0517cfdf3b2e8a1879) 
- [Codepen prototype](https://cdpn.io/pen/PoVggmp/cd965bc015c83de0302f0f72dbc960d0)

### User story

**AS A** AS A Veteran, their family member, caregiver, or survivor who uses  the Federal Header & Footer while in VA.gov
**I WANT** to easily navigate and understand the header Mega menu and experience faster load times
**SO THAT** I'm not frustrated and can quickly and easily complete my tasks

### Engineering notes / background
- Identify (and address, if time permits) any opportunities for simplifying markup
- Identify (and address, if time permits) any opportunities for simplifying styles
- Bonus points
  - address any lint issues
  - audit [README](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/platform/site-wide/mega-menu/README.md) to verify accuracy of existing documentation
 
### Quality / testing notes
- All existing end-to-end and unit tests should pass
- Validate unauthed and authed mega menu
- Validate correct functionality in injected header for unauthed and authed

## Acceptance criteria

- [ ] Markup identified has been simplified
- [ ] Styles identified has been simplified
- [ ] a11y review
- [ ] Injected header/footer is not regressed
- [ ] If possible, lint issues have been addressed (nice to have; not a blocker for releasing this and calling it done)
- [ ] If possible, audit README
  - [ ] if the two items above aren't possible in this ticket, new ticket created for that work to be performed as a follow-up to this ticket.

**Comment by FranECross** [comment]
Possibly an opportunity for the DST to pick this up when they componentize the header/footer.

**Comment by randimays** [comment]
@FranECross I think we can consider closing this ticket as a no-op for our team versus transferring this to DST. The ACs / requirements here are not clear and I think this refactor will come naturally as DST converts the existing header/footer to a web component (I don't think they'll need a ticket for it).

**Comment by FranECross** [comment]
@randimays Sounds good. Thanks. Closing per Randi's comment above.
