### ISSUE TITLE
Add language toggle to Accessibility at VA page from Sitewide CAIA

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-cms#16817]
## Description
CAIA has published a page in Spanish that we need to add the toggle to at the top of the page:

https://www.va.gov/accessibility-at-va-esp/

This is a root-level page so there shouldn't be any left nav work.

### Time constraints / launch deadlines

No hard timing

### Your product/team Slack channel

Sitewide CAIA

### Your OCTODE product owner

Randi Hecht

### Notify Sitewide Public Websites of this issue, and tag @Fran Cross & @jilladams.

- [X] I acknowledge that I must notify `#sitewide-public-websites` in Slack after submitting this issue.

**Comment by randimays** [comment]
Verified this is working as expected in production 👍 

<img width="1148" alt="Screenshot 2024-01-25 at 2 37 12 PM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/19175324/352ed062-6ee2-4602-b5df-a24c57a80ae0">
<img width="1173" alt="Screenshot 2024-01-25 at 2 37 06 PM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/19175324/9f046a41-9ec2-4d0e-b630-48dfdd4abb58">
