### ISSUE TITLE
Draft VBA RO pilot editor-facing research plan 

### ISSUE THREAD

**Issue by ALogsdon3** [department-of-veterans-affairs/va.gov-cms#16823]
### User story
**AS A** Researcher
**I WANT** to document the details for planning VBA RO pilot editor-facing research
**SO THAT** the research will achieve its purpose

### Templates
Use the appropriate template for the group you're conducting research with:
- [Editor-facing Research Plan Template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/research/sitewide-cms-editor-research-plan-template.md)
~- [Veteran-facing Research Plan Template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/research-plan-template.md)~

## Suggested workflow/tasks (Sprint 102)
- [x] Brainstorm ideas for research
- [x] Create initial draft of research plan
- [x] Solicit review/feedback from Sitewide UX Lead, PO, PM, et all
- [ ] Sitewide UX Lead provides consolidated feedback
~- [ ] Identify moderator(s), notetaker(s), and observer(s) if moderated research~

## Suggested workflow/tasks (Sprint 103)
- [x] Coordinate with PO to make a recruitment plan
- [x] Post on github in project research folder for final approval 

## Acceptance Criteria (Sprint 102)
- [x] [Research plan drafted](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/regional-offices/research/2024-01-editor-facing/research-plan.md)
- [x] Research plan posted on github in project research folder
- [x] Feedback requested from Sitewide UX Lead and PO
- [x] Feedback requested from PM and/or other team members
- [x] Verify with @mmiddaugh that VBA leaders are on board with research participation (move this AC to a follow-up ticket as needed)
~- [ ] Final approval obtained from Sitewide UX Lead and documented at the bottom of the file in preparation for Research Review cycle~ [not required for editor-facing research]

## Acceptance Criteria (Sprint 103 ~3 points)
- [x] Identify and document recruitment plan for editors

**Comment by jilladams** [comment]
@xiongjaneg @ALogsdon3 just noting this ticket still has Needs Refining label -- if we have a refined sense of what ACs are fitting into Sprint 102 vs. later sprints, could y'all update the ACs in ticket body?

**Comment by xiongjaneg** [comment]
@jilladams I just forgot to remove the label. Alexis and I talked yesterday and she does believe this will finish this sprint but if that changes, she will mend the ACs to include next sprint work.

**Comment by ALogsdon3** [comment]
@xiongjaneg @jilladams Updated this to reflect the one AC I think will carry over

> - [ ]  Identify and document recruitment plan for editors

**Comment by ALogsdon3** [comment]
All ACs for this sprint have been completed @xiongjaneg

**Comment by xiongjaneg** [comment]
3 points carrying over to next sprint

**Comment by ALogsdon3** [comment]
Coordinated with @xiongjaneg and @mmiddaugh on a recruitment plan. I will attend the training sessions and pitch the research sessions to editors before the end of the training sessions. We'll share a link to book a time using Bookings in Outlook. 
I've tested the Bookings featured with Michelle and @aklausmeier to make sure it works as expected on CAG. Sessions will be scheduled starting 2/14/2024 and go through 3/28/2024 (a week after the last training session. 
All ACs are complete, this ticket can now close.
