### ISSUE TITLE
10.2 testing for Facilities related issues.

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#16822]
CMS Team has a D10 patch upgrade to 10.2 in flight, and needs our teams' review to verify no regressions.

PR: https://github.com/department-of-veterans-affairs/va.gov-cms/pull/16620

Edmund flagged it mostly needs smoke tests, nothing huge that needs specific looks.

Testing notes
Per Daniel, typical procedure:

Pick from the most heavily modified/used entities/nodes and go through CRUD operations as a non-admin.
Poke around admin areas looking for any major changes to the UI/config forms
Look at Drupal logs to see if there are any warnings/errors
Poke around product related changes to 
- [x] geocoder
- [x] geofield
- [x] views_bulk_operations

## ACs
 - [ ] testing completed against the opened PR in CMS-provided Tugboat
 - [ ] Code review provided on PR 16620, by 1/16/24

**Comment by swirtSJW** [comment]
I left a list of non-core modules that were updated as part of this on the 10.2 PR

**Comment by swirtSJW** [comment]
Testing (will edit this as I go)

- [ ] animated_gif
- [ ] core_event_dispatcher (switched from stable to RC)
- [ ] field_event_dispatcher(switched from stable to RC)
- [ ] geocoder
- [ ] geofield
- [ ] danse
- [ ] graphql_core
- [ ] inline_entity_form
- [ ] simple_oauth
- [ ] subrequests
- [ ] views_bulk_operations

**Comment by swirtSJW** [comment]
I approved the PR and called out the two things I saw as risky / needing followup.
https://github.com/department-of-veterans-affairs/va.gov-cms/pull/16620#pullrequestreview-1828057054

**Comment by swirtSJW** [comment]
I'll leave this issue open for now in case there are questions or discussion about my feedback.

**Comment by swirtSJW** [comment]
The [PR was merged](https://github.com/department-of-veterans-affairs/va.gov-cms/pull/16620) without anyone addressing or acknowledging the concerns I noted.   I think we can call this ticket done.

**Comment by jilladams** [comment]
Posted a question to the PR to follow up with Edmund, Berni, Marcia on the noted concerns. Closing.
