### ISSUE TITLE
[PAW] Breadcrumbs to be adjusted according to Collab Staging Review

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-cms#16835]
## Description

The Collab Staging Review provided launch-blocking feedback regarding the breadcrumbs, and from info shown below, suggest we follow what is done with Income Limits e.g. 

## Platform Recommendation
Update the breadcrumbs to reflect the name of the tool/app as the "current" page, staying consistent across all pages in the flow: `Home > Learn how the PACT Act may affect you' This is similar to how we do breadcrumbs on other forms, and it is necessary for users to understand what tool they are using with this simplified one-thing-per-page model. This pattern is effective on the income limits wizard.

## Platform Issue
The components of the navigation system (i.e. URL, breadcrumb, left nav) within your content or feature don't accurately and/or consistently represent the location of the page within the IA.

## Issue Details
Once in the form flow, the breadcrumbs do not accurately convey where the user is within VA.gov. The breadcrumbs do not include a link back to the root of the app, resulting in a loss of wayfinding context.

### User story

**AS A** Veteran, 
**I WANT** to see reference to the PACT Act when go navigate through the pages
**SO THAT** I understand I'm still within the wizard as I answer questions

## Acceptance criteria

- [ ] All breadcrumbs are prepended with 'Home > Learn how the PACT Act may affect you'
  - example: after navigating to the second page, the breadcrumb is: Home > Learn how the PACT Act may affect you 
    - when the user navigates to any pages in the wizard, the breadcrumb above is what will display.
   - [ ] a11y review
   - [ ] Collab team re-review

**Comment by FranECross** [comment]
@laflannery @randimays Was there a decision on implementing the breadcrumb changes re: how long they will be? cc @jilladams

**Comment by laflannery** [comment]
@FranECross IA owns breadcrumbs and so I think we may need to consult CAIA to get guidance on length and if this change and the length that goes with it is frowned upon. That would be my opinion at least?

**Comment by jilladams** [comment]
Agree - @mnorthuis is our guiding light re: breadcrumbs. Mikki: I'm sure you're already familiar with the push to make breadcrumbs match H1. On this topic: 

In the new PACT Act wizard ([up on staging](https://staging.va.gov/pact-act-eligibility/service-period-1)), we got some collab cycle guidance, above, to change the breadcrumbs from: 
* Current: `Home > <H1>`
* To CC suggestion: `Home > Learn how the PACT Act may affect you > H1`
This makes for some long / unwieldy crumbs, e.g. `Home > Learn how the PACT Act may affect you > Did you serve in any of these locations for any amount of time?`

Meanwhile in the Income Limits wizard, we do _not_ match the last crumb to the H1 for each question, e.g. https://www.va.gov/health-care/income-limits, and the crumbs read `Home > Health Care > Check income limits` throughout the wizard. 

Collab Cycle is happy for us to defer to CAIA on this, but would love to confirm if you concur with Collab Cycle for PACT Act wizard crumbs. And if so: should we also be talking about updating the Income Limits crumbs to match?  And @randimays please correct anything I've gotten wrong technically here.

**Comment by mnorthuis** [comment]
Hi all,  breadcrumbs - currently - do not follow you through a form flow, so they stop at the initial page of the flow, and then hold steady through the rest of the flow, providing a way for visitors to get back to the initial page.  So the income limits tool is doing it correctly, although looks like the actual link for the current page is broken in that one.  You can also look at the [health care application](https://staging.va.gov/health-care/apply/application/introduction) as another example (although that one does not use the V3 breadcrumb).

**Comment by jilladams** [comment]
Thanks @mnorthuis 

So, @randimays it does look like we'll need to update current treatment to match IL, vs. what it's doing today. This could be one to prefine so it can get pulled in as stretch, with that in mind.

**Comment by FranECross** [comment]
@mnorthuis Here is the ticket from the collab team regarding the breadcrumbs: https://github.com/department-of-veterans-affairs/va.gov-team/issues/73577

"The suggestion above is not accurate for how the site works today. Can you point me at the CC ticket so I can help clarify that?"

**Comment by mnorthuis** [comment]
Thank you @FranECross!  In reading through that, I believe we are all aligned

> Update the breadcrumbs to reflect the name of the tool/app as the "current" page, staying consistent across all pages in the flow: `Home > Learn how the PACT Act may affect you' This is similar to how we do breadcrumbs on other forms, and it is necessary for users to understand what tool they are using with this simplified one-thing-per-page model. This pattern is effective on the [income limits wizard](https://www.va.gov/health-care/income-limits/).

Their feedback refers to keeping the H1 of the introduction page as the current page and staying set through the flow. So we would not add the H1 of each page to the breadcrumb.  This is how other form flows work, and how it's working on the income limits tool. 

Let me know if this doesn't make sense or you want to chat further.  Thank you!

**Comment by FranECross** [comment]
@mnorthuis Thanks or reviewing and confirming, Mikki! That's very helpful. 🎉

**Comment by FranECross** [comment]
@randimays @chriskim2311 Mikki has reviewed (see comment above), and I've updated the AC to reflect her guidance. In light of this, are you able to do an async refinement and provide an estimate? I'll scoot it over into Stretch/Next Sprint if so. Please let me know if you have any questions. Thanks! cc @laflannery @jilladams

**Comment by randimays** [comment]
Confirming: the PACT Act breadcrumbs should not be dynamic anymore; they should all say `Home > Learn how the PACT Act may affect you`. This is a 2-pointer; accounting for taking out the code that made these dynamic before.

**Comment by randimays** [comment]
@chriskim2311 Here's the PR where we implemented the dynamic breadcrumbs: https://github.com/department-of-veterans-affairs/vets-website/pull/27235/files There are a lot of other content adjustments in here, but note there is some Redux functionality to strip out.

**Comment by randimays** [comment]
@laflannery This is ready for accessibility review, please!

@jilladams @FranECross Should we pass to Collab Cycle folks to review as well?

Note to all: I believe someone in CC pointed out that breadcrumbs (v3) are not working as expected because the last "crumb" leaves you on the same page. I'm not sure what the DST desired behavior / expectations are for that crumb, so I asked a clarifying question in the DST channel here: https://dsva.slack.com/archives/C01DBGX4P45/p1706214933810129

**Comment by laflannery** [comment]
@randimays The last crumb has `aria-current="page", is this something you set manually or does this just automagically gets set on the last item? Technically it's not correct however, if your question in that slack message is that they are intentionally overwriting what we set and forcing folks to stay on the same page then it does make sense. So I am curious about the answer to your question and if we have the ability to control that attribute at all

**Comment by randimays** [comment]
@laflannery DST is setting the aria-current 👍

**Comment by laflannery** [comment]
Thanks @randimays Depending on their answer in that thread, I might have follow up questions and/or open a ticket for them to change that behavior. I don't want folks clicking the "Current" page and being taken somewhere else that seems not accurate lol

**Comment by FranECross** [comment]
@randimays I'll take a look at this today. Thanks!

**Comment by FranECross** [comment]
Reviewed and verified. Closing.
