### ISSUE TITLE
UX Writing for user sections block

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#1684]
## User story
 *As a user who has not been assigned to any VA section, I'd like to see a message on my profile that directs me to a contact who can assign me to a section.*

## Context

Link to original issue - #1243

Link to PR w/ relevant screenshots - #1683 

Placeholder text:
<img width="1040" alt="Screen Shot 2020-05-04 at 1 54 21 PM" src="https://user-images.githubusercontent.com/16477724/81014145-8d0d3100-8e19-11ea-8147-b6c521daf856.png">

## AC

- [x] Draft text in MURAL: https://app.mural.co/t/vagov6717/m/vagov6717/1588691272404/9034182995551a1d7ae0f67634f85afbfe77b4e0
- [x] Review email template with Howie
- [x] Document choices in word list

**Comment by kevwalsh** [comment]
I think the text should also mention the email address vacmssupport@va.gov, since not all VA employees are on Slack.
