### ISSUE TITLE
Create Next-Build Container Image Workflow

### ISSUE THREAD

**Issue by olivereri** [department-of-veterans-affairs/va.gov-cms#16857]
## Requirements
Accelerated Publishing needs a container image to host a Next-Build server on Platform's Elastic Kubernetes Service (EKS). This ticket will establish a Github Actions (GHA) workflow to create the image and register it with AWS Elastic Container Registry (ECR).  This will set the foundation for generating content using Next-Build.

```[tasklist]
### Acceptance criteria
- [x] Next-Build OS requirements has been determined. Likely just a Node v18 or above Image.
- [x] AWS ECR Repository created to store images.
- [x] Create GHA Workflow to build and register image.
- [x] Workflow uses OIDC for AWS Credentials, role-to-assume
- [x] AWS OIDC Role includes permissions to register images with AWS ECR
```

## Background & implementation details
An example of this being done in the now archived CMS infrastructure repo:
https://github.com/department-of-veterans-affairs/vsp-infra-cms/actions/runs/5861983381/workflow

**Comment by jschmidt-civicactions** [comment]
Working through all the dependencies to get a build set up in a docker container. Looks like nvm is not present by default in node:18-alpine, for instance.

**Comment by jschmidt-civicactions** [comment]
Note that I am not running this in the dockerfile: `nvm use 14.15.0 && yarn set version stable`. We should just make sure we are using the appropriate node docker image instead (currently `node:18-alpine`).

**Comment by jschmidt-civicactions** [comment]
Note that `008577686731.dkr.ecr.us-gov-west-1.amazonaws.com/dsva/next-build-node` was created to test staging promotion in a different ticket. I'll push to this repository when the workflow is in place with a working docker image.

**Comment by jschmidt-civicactions** [comment]
We'll have to take a closer look at what really needs to be copied from the app dir, the size seems excessive (but maybe not, if all of this is actually necessary for functioning):

```
❯ docker history next-build-node
IMAGE          CREATED        CREATED BY                                      SIZE      COMMENT
4d76fb4f884e   20 hours ago   /bin/sh -c #(nop)  CMD ["yarn" "dev"]           0B
aa56510fa1bc   20 hours ago   /bin/sh -c yarn install --frozen-lockfile       810MB
81484c9e6e8d   20 hours ago   /bin/sh -c #(nop) COPY dir:6adccc0e093c20da8…   3.78GB
e2572e53ff9d   6 days ago     /bin/sh -c #(nop) WORKDIR /app                  0B
8e2fedd9ed75   6 days ago     /bin/sh -c #(nop)  ENV HOME=/app                0B
```

**Comment by jschmidt-civicactions** [comment]
I've had to do a little thinking on how to actually invoke the app in the Dockerfile, so that we can have the same docker image for all envs and lean on Kubernetes to set all the env-specific bits.

Easiest way I can see is use a shell script that has all the non-secret parameters as env vars, populated by a k8s ConfigMap per environment. Secrets are also populated into the app config file per environment, read by the app as usual (and not overridden by the shell script).

The shell script is just something like:
```
APP_ENV=${ENV} yarn dev \
    --SITE_URL ${SITE_URL} \
    --NEXT_PUBLIC_DRUPAL_BASE_URL ${NEXT_PUBLIC_DRUPAL_BASE_URL} \
    --NEXT_IMAGE_DOMAIN ${NEXT_IMAGE_DOMAIN} \
    --REDIS_URL ${REDIS_URL} \
    --NEXT_PUBLIC_ASSETS_URL=/generated/
```

The secrets get populated by k8s to `./envs/.env.stage` or `./envs/.env.prod` like:
```
DRUPAL_PREVIEW_SECRET=preview-secret
DRUPAL_CLIENT_ID=client-id
DRUPAL_CLIENT_SECRET=client-secret
```

**Comment by jschmidt-civicactions** [comment]
Ok, now I'm stuck on running the assets script as part of the Dockerfile (`RUN BUILD_TYPE=vagovprod node ./scripts/yarn/vets-website-assets.mjs`). It seems to time out, although it doesn't have to do with connectivity to the S3 bucket, as it fetches file-manifest.json just fine (and testing fetches with wget from the Dockerfile also work). @tjheffner will that script try to spin off async downloads for *all* the files at once? On the suspicion that there was too much processing going on for docker to run that amount of parallelization, I truncated the keys array to just a few entries that that seemed to work.

However... `moveAssetsFromVetsWebsite()` is still assuming there is an adjacent checkout to copy fonts from.

**Comment by jschmidt-civicactions** [comment]
Update to the prior comment: the timeout seems to be entirely local to my machine, for some reason I can't discern. For local testing I've commented out that piece and we'll have to test as part of trying the GHA once merged.
