### ISSUE TITLE
VBA  banner tyPo

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#16858]
## Describe the defect
On editing a VBA facility in the banner section, a semicolon appears as a P.
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5752113/120dab18-b465-46dc-9820-57e01ff2b012)

## AC / Expected behavior
- [ ] Text says "Warning alerts:"

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Defect")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS workstream (orange) (not needed for bug tickets)
- [ ] CMS-supported product (black)

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [ ] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`
- [ ] `Accelerated Publishing`

**Comment by jilladams** [comment]
i see what you did here with the issue title, sir. 😂

**Comment by jilladams** [comment]
![Screenshot 2024-01-26 at 12 51 24 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/85581471/e3ec65e3-197a-4555-b8d9-70bced8d8882)
