### ISSUE TITLE
FE SPIKE: Learn how AP Next templates work

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#16865]
## Description
In prep for moving products to Accelerated Publishing, we need to learn how it works. 

AP team has prepared some docs here: https://github.com/department-of-veterans-affairs/next-build

## ACs
- [x] Review existing documentation / trainings
- [ ] Document learnings for future selves

**Comment by jilladams** [comment]
We'll need to figure out the criteria here to say we know enough to be ready to do more work. Context reminder: the candidates we're considering as a starter project are: 
*  Checklist
*  Step-by-step
*  Image list
*  Video list

**Comment by FranECross** [comment]
The AP contract ends on May 1st. We should try to get this done in early April.

**Comment by jilladams** [comment]
Demoted from Sprint 11 due to change in priorities / timing on the AP side. Not urgent. 

CMS team has a technical writer starting to help document some portions of the work.

**Comment by jilladams** [comment]
Michelle interested in some engineering input to help make decisions about our involvement. Pulling in for Daniel to get generally familiar.

**Comment by dsasser** [comment]
## End of Sprint Update 9/17/24

I will be attending both the AP knowledge transfer meetings (backend, frontend) which are scheduled for this week. This will suffice for initial understanding of how AP templates work, and should satisfy the ACs here.

**Comment by jilladams** [comment]
https://dsva.slack.com/archives/C03LFSPGV16/p1726778636068239
> after the AP FE training today, we regrouped with engineers re: what else we may want to learn / do while AP team is around (til Oct 9). The general sentiment was: trainings were helpful high level, but we'd love to try and get 1 small template implemented, just to make sure it really makes sense and while AP is here to ask questions.
That could be in Sprint 14, or we could opt to make sprint tradeoffs and try to start earlier. Easy candidates would be smaller resources and support content types, as previously discussed (Checklist has prod content, so may be a smart one, and hasn't already been started by AP per their[ template list](https://github.com/department-of-veterans-affairs/next-build/blob/main/READMEs/templates.md#template-list)). I'll queue this for Monday morning product sync, to close loop.

**Comment by dsasser** [comment]
@FranECross @jilladams considering I attended both the AP trainings, could we consider this closed? As Jill [noted](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16865#issuecomment-2362143045) we are planning on taking on an actual template for learning purposes where we will cover the original intent of this ticket.

**Comment by FranECross** [comment]
@dsasser Agree! Closing.
