### ISSUE TITLE
Create Next-Build Workflow to Update Helm Chart Container Image Version

### ISSUE THREAD

**Issue by olivereri** [department-of-veterans-affairs/va.gov-cms#16863]
## Requirements
When code updates are released and a new container image is built the helm chart in the application manifest repository needs to be made aware of the change. This ticket will establish a Github Actions (GHA) workflow to modify and commit a change to the Next-Build helm chart with the update image tag.

```[tasklist]
### Acceptance criteria
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16857
- [x] GHA Workflow is created to update Next-Build Helm charts with latest image release name.
- [x] Workflow runs automatically after a new release is created.
```

## Background & implementation details
Application Manifest Update:
https://github.com/department-of-veterans-affairs/vsp-infra-goldilocks/actions/runs/4266039617/workflow

This can be triggered by the successful completion of the Create Production Tag workflow: https://github.com/department-of-veterans-affairs/next-build/actions/workflows/production-tag.yml

See that workflow for an example of the Create Production Tag workflow being triggered by a successful run of Continuous Integration on the main branch.

This workflow will need to be able to identify the current leading tag. This could be exported from the Create Production Tag workflow, or it could be found by querying the repo.

**Comment by timcosgrove** [comment]
https://github.com/department-of-veterans-affairs/next-build/blob/main/.github/workflows/production-tag.yml#L5

**Comment by timcosgrove** [comment]
We need to grab the latest tag of the next-build repo and build using that.
