### ISSUE TITLE
[Aging Content] Create Architecture Plan for Aging Content Notification Framework 

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-cms#16885]
## Description

Draft Architecture Plan for Aging Content Notifications Configurable Framework and review with someone in CMS (either async or a formal CMS Collab Cycle Review).

### User story

**AS A** PO/PM
**I WANT** an architecture plan to be created and reviewed by the CMS team
**SO THAT** we can then decompose into actionable Aging Content tickets

## Acceptance criteria

- [x] Draft architecture plan
- [x] Request a review with the CMS team from Marcia, Erika and include Dave in the review
- [ ] ~Create tickets for the Notification framework based on the plan~ -- opting to hold on ticket creation until plan is agreed on with CMS team

**Comment by dsasser** [comment]
Here is the first draft of the architecture.

[VACMS-16885 Architecture - Scheduled (aging) Content Notifications Framework.pdf](https://github.com/department-of-veterans-affairs/va.gov-cms/files/14090309/VACMS-16885.Architecture.-.Scheduled.aging.Content.Notifications.Framework.pdf)

@FranECross @jilladams I sent an invite for discussing the architecture within PW. Once done, we can send over or schedule the architecture for CMS to review.

**Comment by dsasser** [comment]
We (myself, @FranECross, @Becapa, @jilladams) reviewed the architecture today and agreed to move forward with getting CMS approval.

**Comment by jilladams** [comment]
Highlights of today's conversation (FYI @davidconlon ): 
* The proposed approach uses Drupal's Views , which is flexible to handle nodes and blocks both
* Runs at cron time, and we don't expect it to take any additional heavy compute load beyond normal cron stuff
* Going this route involves less custom code, and if CMS team co-signs the approach, we think could be carried out in ~3 person-sprints, or potentially 2 calendar sprints if double staffed.
* Daniel has laid out ~6 execution tickets we'll cut once the plan is signed off with CMS team. Several of those can be parallelized, as they don't touch the same code.  (@dsasser would you go ahead and add those ticketing notes in comment on here?)
* This'll leave us with some Drupal bandwidth to play with later in the quarter, if things move as efficiently as we think they might.

cc @FranECross

**Comment by dsasser** [comment]
Breakdown of work/tickets expected if the framework is approved as designed:

Install ECA Drupal module

Create Views Result Condition Plugin for ECA
	Fields: View name, display, arguments (leverage the Views Action)
	Depends on: n/a
	Blocks:  Create new ECA Model

Create Queue Email Message from Views Result Action Plugin for ECA
	Fields: Message template, message template variables (mapping), View, View Display, Recipient, Subject
	Depends on: Custom Views Display Plugin
	Blocks:  Create new ECA Model

Create Custom Views Display Plugin
	Subclass of Entity Reference Selection display plugin, perhaps.
	Depends on: 
	Blocks:  Create new ECA Model

Create Message Template
	Design/verbiage TBD
	Depends on: Design
	Blocks:  Create new ECA Model

Create Advancedqueue and Mailer
	This is the "processor". It will run on cron. It needs to take each item, create a Message using provided template variables, and "Deliver" the email using the Message Notify module. Much like the 'va_gov_outdated_content_notification' queue.
	Name: TBD
	
Create a new View for "Aging FWB"
	Using the new Display type
	Depends on: Create Custom Views Display Plugin
	Blocks:

Create new ECA Model
	Event: Cron daily (time tbd)
	Action: Queue Email Message from Views Result Action Plugin for ECA
	Condition: Views Result Condition Plugin for ECA
	Depends on: ALL
	Blocks:

**Comment by jilladams** [comment]
CMS Collab cycle intake ticket: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17120

Closing. Next step will be whatever tickets come out of their review, whether to revise the plan or to cut our tickets to proceed with it.
