### ISSUE TITLE
Error: Call to a member function getValue() on null in Drupal\va_gov_content_types\Entity\Event->addToNationalOutreachCalendar()

### ISSUE THREAD

**Issue by dsasser** [department-of-veterans-affairs/va.gov-cms#16882]
## Description
When saving some nodes (eg: node/64741/edit), an error is thrown:

```
Error: Call to a member function getValue() on null in Drupal\va_gov_content_types\Entity\Event->addToNationalOutreachCalendar()
```

Originally reported via [Slack](https://dsva.slack.com/archives/CJT90C0UT/p1705501739844599).

### Engineering notes / background
It appears in some cases the field `field_publish_to_outreach_cal` has no value, and so calling first() on null is returning the error.

## Acceptance criteria
- [ ] Error is no longer thrown on node 64741 (or similar nodes without a field_publish_to_outreach_cal value).

**Comment by jilladams** [comment]
Slack thread with original report / risk assessment for why we should prioritize now: https://dsva.slack.com/archives/CJT90C0UT/p1705501739844599

**Comment by dsasser** [comment]
Verified on Prod:

![Screenshot 2024-01-24 at 8 06 18 AM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/221539/14487c62-449c-406e-8f1b-3bbae80d5395)
