### ISSUE TITLE
Preview server not working

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-cms#16891]
## User Story or Problem Statement
The preview server in Drupal doesn't seem to be working and an error message is shown saying "Please hold while the preview server is starting - 0.00%"

## Steps for Implementation

Click preview on any Drupal node.

## Acceptance Criteria
- [ ] Testable_Outcome_X
- [ ] Testable_Outcome_Y
- [ ] Testable_Outcome_Z
- [ ] Requires design review
- [ ] Requires accessibility review

## Team
Please check the team(s) that will do this work.

- [ ] CMS Team
- [ ] Public Websites
- [ ] Facilities
- [ ] Accelerated Publishing

**Comment by EWashb** [comment]
@BerniXiongA6 @maortiz-27-80 @michelle-dooley

**Comment by maortiz-27-80** [comment]
Working as expected and Randi confirmed morning of 01/18 that this is no longer an issue.  Closing.  cc: @BerniXiongA6 @michelle-dooley
