### ISSUE TITLE
[Discharge Upgrade Wizard]: (#1) Initial App Setup

### ISSUE THREAD

**Issue by chriskim2311** [department-of-veterans-affairs/va.gov-cms#16909]
## Description
Ticket 1

### User story

**AS A** Veteran
**I WANT** to be see the introduction page of the DUW
**SO THAT** I get start the wizard experience.

**AS A** PM/PO/Eng
**I WANT** to set up the routing, skeleton app and introduction page
**SO THAT** we can start building the new subtask pattern for DUW

## Engineering notes:

- Skeleton app with basic routing (VW - this must be merged first)
- Metadata information in content-build (CB - merged after above)
- devops client-side routing
- Breadcrumbs (Use income limits as a framework, make up something for the last string)
- set up introduction page/content
- use web components
- review the existing content for typos

## Acceptance criteria
- [ ] A11y review
- [ ] Design review
- [ ] PM review

Questions:
Should we check with CAIA to confirm that a new application is ok (and what route?)

**Comment by jilladams** [comment]
Chris verified routes are only present on Staging.
