### ISSUE TITLE
Audit breadcrumbs for V3 component update impact

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#16903]
# Description 
Design system components are being forced to V3 on Feb 16, 2024 ([announcement](https://dsva.slack.com/archives/C03R5SBELQM/p1705503589174489)), and we will need to request exceptions for cases where we cannot adopt V3 without negative impact on the DS timeline. This includes breadcrumbs.

Per notes in the parent epic of this ticket, #16902 , our team owns the FE implementation of breadcrumbs on our product pages, which can be implemented in a variety of ways. For templates that use the web component, we need to assess impact. 

## ACs

- [ ] Review FE templates for PW products, and assess breadcrumb implementation. Fill out  https://docs.google.com/spreadsheets/d/1A7mQMnL2d5JcDKHZ2daVYQVr85qOljrwM0aUk_inO88/edit with notes
- [ ] Tag PM / DM for review
- [ ] Tickets are cut to track updating any templates that do not use web components, to adopt V3 component. (Tickets should be per-template, rather than batching, unless Engineers say otherwise)

**Comment by jilladams** [comment]
DS Confirmed they will not be force-updating non-component implementations onto components: " - correct, if breadcrumbs exist that are not using the breadcrumbs web component, the design system team will not be converting them. VFS teams are responsible for ensuring their applications remain consistent with the VA design system and the style guide it sets forth."

cc @laflannery  @randimays

**Comment by jilladams** [comment]
We'll want eng to review & confirm, but from going through it today, only 3 of our templates with breadcrumbs are using DS component, and those are already using V3: 
* onsite search resultrs
* Income Limits
* PACT Act wizard

Everything else is _not_ using DS component, or doesn't have breadcrumbs at all: https://docs.google.com/spreadsheets/d/1A7mQMnL2d5JcDKHZ2daVYQVr85qOljrwM0aUk_inO88/edit#gid=0. So: the force upgrade from V1 > V3 seems like it won't have any impact on us, at first glance.

Also: Expanded that doc to cover additional V3 components as well. Based on 1 random page example for each template, logged what I saw -- for that as well, that won't be comprehensive, as some pages may have additional components that show when different variations of content are entered in the Drupal forms, so will need eng review. Will cross-post this to #16871

cc @laflannery @FranECross

**Comment by FranECross** [comment]
Can be done after Laura has done her work on the other V3 tickets.
