### ISSUE TITLE
[Discharge Upgrade Wizard] (#6) FE: Add Application Denial content: Failure to exhaust question

### ISSUE THREAD

**Issue by chriskim2311** [department-of-veterans-affairs/va.gov-cms#16915]
## Description
Ticket 6

### User story

**AS A** Veteran
**I WANT** to be see the Application Denial question of the DUW in a subtask pattern
**SO THAT** I get continue the wizard experience.

## Engineering notes:

- Add Application Denial question
- Create route for that
- Display conditions ("decision tree") for this question
- review the existing content for typos
- Redux store for answer storage
- Form error handling
- Testing: Cypress tests
- Testing: Unit tests (for display conditions logic)
- 

## Acceptance criteria
- [ ] Converted to subtask pattern (one question per page)
- [ ] Content changes made
- [ ] A11y review
- [ ] Design review

### Existing Text
**Q5c:** Was your application denied due to "failure to exhaust other remedies"?

**Note:** "Failure to exhaust other remedies" generally means you applied to the wrong board.
 
1. Yes, the [BCMR/BCNR] denied my application due to "failure to exhaust other remedies."
2. No, the [BCMR/BCNR] denied my application for other reasons, such as not agreeing with the evidence in my application.

### Updated Text (not all text is updated; but I included all text to reduce confusion):

**Q5c:** Did the board deny your application due to "failure to exhaust other remedies"?

**Note:** "Failure to exhaust other remedies" often means you applied to the wrong board.
 
1. Yes, the [BCMR/BCNR] denied my application due to "failure to exhaust other remedies."
2. No, the [BCMR/BCNR] denied my application for other reasons, such as not agreeing with the evidence in my application.

**Comment by randimays** [comment]
Verified successfully in staging. Closing!
