### ISSUE TITLE
[Discharge Upgrade Wizard] (#2) FE: Add Branch and Year/Month Questions

### ISSUE THREAD

**Issue by chriskim2311** [department-of-veterans-affairs/va.gov-cms#16910]
## Description
Ticket 2

### User story

**AS A** Veteran
**I WANT** to be see the Branch and Year and Month questions of the DUW in a subtask pattern
**SO THAT** I get continue the wizard experience.

## Engineering notes:

- Add Branch question
- Add Year of Discharge question
- Add Month of Discharge question
- Create routes for those
- Display conditions ("decision tree") for these 3 questions
- Redux store for answer storage
- review the existing content for typos
- Form error handling
- Testing: Cypress tests
- Testing: Unit tests (for display conditions logic)

## Acceptance criteria
- [x] Question is on a single screen (sub-task pattern)
- [x] Content changes per below
- [x] A11y review
- [x] Design review

### Existing Text:

**Q1:** In which branch of service did you serve?
1. Army
2. Navy
3. Air Force
4. Coast Guard
5. Marine Corps

**Q2:**  What year were you discharged from the military?
[ year selector ]

**Q2a:** What month were you discharged?
[ month selector ]

### Updated Text (not all text is updated; but I included all text to reduce confusion):

**Q1:** What was your branch of service?
1. Army
2. Navy
3. Air Force
4. Coast Guard
5. Marine Corps

**Q2:**  What year were you discharged from the military?
[ year selector ]
If Q2 == CURRENTYEAR - 15, show:
**Q2a:** What month were you discharged?
[ month selector ]

## Questions:
- What should the form error message say (if an answer is not selected when clicking Continue)?
     - Answer: These are the error messages that should appear on each field:
          - For Year of Discharge: Select a year
          - For Month of Discharge: Select a month

**Comment by thejordanwood** [comment]
If an answer is not selected, these are the error messages that should appear on each field:

- For Year of Discharge: Select a year
- For Month of Discharge: Select a month

cc: @FranECross @chriskim2311

**Comment by chriskim2311** [comment]
This will carry over to next sprint

**Comment by FranECross** [comment]
@chriskim2311 For when you're back, I added the content changes we chatted about (existing text/updated text), and will include in the other stories as well. Thanks!

**Comment by chriskim2311** [comment]
This is ready for review but will carry over, pending some unit tests fixes

**Comment by chriskim2311** [comment]
Verified changes are not live on prod but in staging. Closing!
