### ISSUE TITLE
VBA: Add local spotlights to query and template

### ISSUE THREAD

**Issue by eselkin** [department-of-veterans-affairs/va.gov-cms#16922]
## User Story or Problem Statement

As an editor or user I want to see the local spotlight fields in the VBA page

## Description or Additional Context 

Get featured content from local spotlights and merge them into list with single centralized content

## Steps for Implementation

- [x] Add fieldLocalSpotlight to VBA GQL query
- [x] Check if fieldLocalSpotlight has length (has items)
- [x] If fieldLocalSpotlight has items add featured content to array of items being processed for spotlights

## Acceptance Criteria
- [x] fieldLocalSpotlight is downloaded from drupal
- [x] local spotlights are visible on page
- [x] If no fieldLocalSpotlight items, no spotlight sections are added
- [ ] Requires design review
- [ ] Requires accessibility review

## Team
Please check the team(s) that will do this work.

- [ ] CMS Team
- [ ] Public Websites
- [x] Facilities
- [ ] Accelerated Publishing

**Comment by eselkin** [comment]
fieldLocalSpotlight is a ParagraphFeaturedContent and is accessed via its entity:
```
fieldLocalSpotlight {
      entity {
        entityRevisions { 
            entities {
          	... on ParagraphFeaturedContent {
            	id
            	fieldDescription {
              	value
            	}
              fieldCta{
                entity {
                  ... on ParagraphButton {
                    fieldButtonLink {
                      uri
                      title
                      options
                    }
                    fieldButtonLabel
                  }
                }
              }
            }
          }
        }
      }
    }
```

**Comment by jilladams** [comment]
@eselkin can you confirm that @thejordanwood and @laflannery were able to do the design / a11y review here? Those are the last ACs in order to close. If not, may need to re-standup a tugboat with content populated, so they can see it.

**Comment by eselkin** [comment]
I added those. But since they had viewed the original 3 elements with the non-local spotlights and they were using the same components just different data, I didn't think they needed to do a second check.

**Comment by jilladams** [comment]
Fair - if design / markup are the same, just content differences, makes sense to me. (FYI @laflannery / @thejordanwood in case you have any questions.)
