### ISSUE TITLE
Front end: Add Prepare for your visit to VBA Facility page

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#16921]
## User Story or Problem Statement

- As a Veteran, I need to know how to find and what to bring to a VBA Regional Office prior to my visit.
- As a VBA Regional Office editor, I need to help Veterans understand how to find my regional office and what to bring at their visit.

## Resources
- [VBA Facility content spec](https://www.figma.com/file/aKdT4weNNthDxb3r6MolEh/VBA-Content-Specs?type=design&node-id=500-154&mode=design&t=om6IU7Wo4w5ysWLT-0)
- [VBA Regional Office Sketch File](https://www.sketch.com/s/891d33ae-152d-471c-ab5d-9aedf89cf6ff/p/772C1EED-1ED9-4544-8DB1-FBB388534931/canvas?annotation=0e7f7e49-b0f4-435c-82a5-94b588b8b35a)
- Example added to [Anchorage in the VBA training environment](https://main-2pegzvqcy77ynmcultaityqtlrpfbfoo.demo.cms.va.gov/anchorage-va-regional-benefit-office-at-anchorage-va-medical-center/locations/anchorage-va-regional-benefit-office-at-anchorage-va-medical-center)
- Editor UI in Drupal staging
    <img width="741" alt="Screenshot 2024-01-30 at 4 18 24 PM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/73648238/0e471f90-4ba6-4d8c-abea-8442b0bb0b19">
- Staging preview not showing content
    <img width="741" alt="Screenshot 2024-01-30 at 4 27 23 PM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/73648238/dd0d0513-653c-4808-80fc-76c20489d47a">

## Acceptance Criteria
- [x] Content added by an editor to a Prepare for your visit accordion shows on the VA.gov page.
- [x] Accordion component uses USWDS V3 component.
- [x] Requires design review
- [x] Requires accessibility review

**Comment by laflannery** [comment]
@xiongjaneg I noticed that the prototype had no annotations (for headings and such) so I added some but was told by Jordan that the Figma linked above is an older file that only shows the prototype we used for testing. The most up to date VBA file is actually [the Sketch file](https://www.sketch.com/s/891d33ae-152d-471c-ab5d-9aedf89cf6ff/p/772C1EED-1ED9-4544-8DB1-FBB388534931/canvas?annotation=0e7f7e49-b0f4-435c-82a5-94b588b8b35a), and this actually has the annotations I remembered. Can we/should we have this as the source of truth in the ticket description?

**Comment by xiongjaneg** [comment]
@laflannery Yes please. That may have been my error (I get my Figmas and Sketches mixed up some times).

**Comment by mmiddaugh** [comment]
@maxx1128 @thejordanwood did these accordions get a design review after implementation?

**Comment by mmiddaugh** [comment]
@laflannery have you had a chance to review also?

**Comment by maxx1128** [comment]
@mmiddaugh Sorry, it's entirely my fault for skipping the design and accessibility review. I completely spaced on that. I'll get a tugboat instance of this setup.

**Comment by thejordanwood** [comment]
@maxx1128 I have a couple of notes:

- I'm unsure how heading levels are being controlled here. The headings in the Transportation for Veterans to their Appointments accordion should be H4. The heading levels look fine in the other accordions. 
- In the Chaplain services and chapels accordion, the button should be replaced with an [active link](https://design.va.gov/components/link/#active).

**Comment by mmiddaugh** [comment]
I added test content in staging 
[Try this preview page in staging](http://preview-staging.vfs.va.gov/preview?nodeId=4318)

**Comment by maxx1128** [comment]
@thejordanwood Both of these issues are on the CMS side of things. I checked [my local tugboat version of the CMS with the same data](https://cms-txcrk8bym4a0ivw3xfr8xvdhezmls36f.demo.cms.va.gov/node/1114/edit), and the Transportation headings are being set to H3s there and the Chaplain services accordion has a button set there too.

**Comment by laflannery** [comment]
@maxx1128 The page you had added in the original comment above  is a live VAMC page, see [Slack thread](https://dsva.slack.com/archives/C0FQSS30V/p1708118118401129) for question and discussion about this. So the issues mentioned do not apply to the VBA pages.

For the VBA pages and the scope of this ticket, @mmiddaugh added a test page she had been looking at in staging and I just reviewed - everything looks good!
<img width="752" alt="Screenshot 2024-02-19 at 8 40 37 AM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/106678594/18d35a7d-58bc-4e3b-8ed4-4f4de2768cee">

**Comment by thejordanwood** [comment]
@maxx1128 As Laura mentioned, please ignore my previous feedback for the VAMC page. The VBA page that @mmiddaugh added here looks good to me. This is approved on my end!

**Comment by jilladams** [comment]
Based on approvals in comments, closing.
