### ISSUE TITLE
Create Next-Build remaining EKS Environments

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#16949]
## Requirements
Accelerated Publishing needs a Helm Chart to host a Next-Build server on Platform's Elastic Kubernetes Service (EKS). Helm Charts are deployed to EKS by ArgoCD and exist in this repository: [Application Manifests](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests). 

Following on from work done for the Dev and Staging environments (#16861), this work should also be done for these environments:

- Staging
- Test Production
- Production 

```[tasklist]
### Acceptance criteria
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16857
- [x] Service requirements for Next-Build are determined. Likely a Heml files for: Service, Deployment, Configmap, DNS, and Ingress.
- [x] [Application Manifests](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests) PR Approved and merged for Next-Build in Dev.
- [x] At a minimum a Hello World container is reachable in Dev.
- [x] Copy work in Dev to EKS Staging environment. Or auto promotion.
- [x] AWS Route 53 DNS record is created.
```

## Background & implementation details
Environment Promotion may obviate the need to create Prod explicitly.

Simple CMS Dev Helm Chart:
https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/190/files#diff-2d13af2fe5c0c1cc02f200fd9c18281b92994e2f030ca5a6d1b3bbf11583bc1c

**Comment by timcosgrove** [comment]
This is mostly replication of the Staging Test with config copied and modified for the other environments.

**Comment by tjheffner** [comment]
The above PRs have been merged 🎉
