### ISSUE TITLE
Next Build success monitor and alerts

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#16955]
## Requirements

We want monitors on Next Build content release success and failure and alerts if Next Build is failing, so that we are made aware of the failures and can address them quickly.

```[tasklist]
### Acceptance criteria
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17022
- [x] Production Next Build reports an event into Datadog upon successful build
- [x] A monitor is created that watches the time between successive Next Builds
- [x] If there has not been a successful build in the past two hours, an alert is sent to a Slack channel to notify engineers of the issue
- [x] If there has not been a successful build in the past four hours, an alert is sent to CMS Support to notify CMS users about the situation
- [x] Count for every link that returns an error
- [x] Total built page count
```

## Background & implementation details

Equivalent monitors for Content Build can be viewed here:
* engineers: https://vagov.ddog-gov.com/monitors/104457?view=spans
* support: https://vagov.ddog-gov.com/monitors/157216?view=spans

Slack channel for notification: #status-next-build (id: `C06DSBT7CBW`)

Use @next-build-devops as the group to be alerted.

**Comment by mreed101** [comment]
This has been merged into main
