### ISSUE TITLE
CI site destroy failed on pr1626

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#1696]
The associated PR was merged, but for some reason the devshop destroy failed.
![image](https://user-images.githubusercontent.com/5752113/81112651-fd38b700-8eec-11ea-803c-396d65e3a793.png)

- [x] Investigate to see if there is an underlying issue to be fixed... or just goofy 1-off failure
- [x] remove it.
- [x] Document how to resolve in this ticket.

**Comment by ElijahLynn** [comment]
![image](https://user-images.githubusercontent.com/1504756/81115269-47fc0400-8ed8-11ea-87cc-ca9f326a143c.png)

Triggered a second destroy site and got:

![image](https://user-images.githubusercontent.com/1504756/81115375-7548b200-8ed8-11ea-89ff-a08d75b9c9e1.png)

But it did appear to work, site is gone now.
