### ISSUE TITLE
Mobile smart banners showing on PC touchscreen desktop browsers

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#16969]
## Describe the defect
The mobile smart banners are showing on PC touchscreen desktop browsers (Chrome, Edge and FF)

## To Reproduce
1. on a PC, go to a page that has the mobile smart banner set up, like [Download VA Letters](https://www.va.gov/records/download-va-letters/)
2. When the page loads, notice that the smart banner, which directs you to download the mobile app, is appearing at the top

## AC / Expected behavior

- [x] Mobile smart banners should only appear at mobile screen widths (or on mobile devices depending on technical feasibility)

## Screenshots
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/106678594/fd8646b9-4029-4062-93a1-4f0d41d84a06)

 ## Additional context
I checked my Mac and the banners are not showing on desktop there, so this just seems to be a PC issue.

**Comment by jilladams** [comment]
Related slack thread, https://dsva.slack.com/archives/C52CL1PKQ/p1706022428102699, where we identified this is limited to PC touchscreens. Issue updated to reflect that.

**Comment by randimays** [comment]
Successful validation in staging. Waiting for prod deploy today to check once more.

**Comment by randimays** [comment]
Verified iOS Chrome/Safari, Android Chrome/Firefox, and Laura validated all browsers on her Windows desktop (touchscreen). Good to go!
