### ISSUE TITLE
[EPIC - V3 Components] Implementation of V3 components for PW products currently using V1

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-cms#16977]
## Status
**[2024-02-29]** Out of 18 tickets:
- 15 Closed
- 2 will be closed this week
- 1 in To Do (current sprint)

## Description

The Design team will be migrating all V1 components to V3 components on ~February 16th~ March 4 ([slack](https://dsva.slack.com/archives/C03R5SBELQM/p1708543191236629)), which doesn't provide the Public Websites team adequate time to implement V3.

This Epic organizes the efforts to:
- validate the [spreadsheet ](https://docs.google.com/spreadsheets/d/1A7mQMnL2d5JcDKHZ2daVYQVr85qOljrwM0aUk_inO88/edit#gid=0)of PW products, whether they are using components, and if so, V1 or V3,
- assess the effort to change from V1 to V3,
- to implement opting out of V3 components so that we can prioritize the tickets implementing V3 for components currently using V1, and
- to implement V3 for those products currently using V1

For products not using any components, we'll prioritize those at a later date, or as those products are being enhanced/changed in the future.

### User story

**AS A** PO/PM for Public Websites products
**I WANT** to understand which PW products use components, and if so, are they using V1 or V3, as well as an assessment of the effort of changing from V1 to V3,
AND I WANT to then have all V1 components changed to V3
**SO THAT** all PW products are no longer using V1 and we are in alignment with the current component version.

## Acceptance criteria

- [ ] See the individual stories for AC

**Comment by FranECross** [comment]
@jilladams @randimays @chriskim2311 I've created stories for:

- reviewing the products against the spreadsheet (auditing the audit :) )
- opting out of the V3 upgrade
- updating our products listed in the spreadsheet with V1 components.

I'm happy to create more/edit as things shake out after the review of the spreadsheet.

**Comment by laflannery** [comment]
Adding important applicable deadlines:

- v1 deprecation is scheduled for 4/19

[Slack thread for reference](https://dsva.slack.com/archives/C03LFSPGV16/p1707759183364599)
