### ISSUE TITLE
[V3 Components Audit] Sitewide V3 DS component review of the audit

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-cms#16974]
## Description

The Design team will be switching all V1 components to V3 on February 16. Because of this announcement, Jill performed an audit of all PW products component usage, and we would like an engineer to review the spreadsheet for accuracy and edit if necessary, and check to determine if changing V1 to V3 will break anything.

Note that if no component is being used, this migration will not affect the product.

This ticket is to assess impact and verify the [spreadsheet](https://docs.google.com/spreadsheets/d/1A7mQMnL2d5JcDKHZ2daVYQVr85qOljrwM0aUk_inO88/edit#gid=0) 

### User story

**AS A** PO/PM on the Public Websites team
**I WANT** to verify that the Sitewide V3 DS component review spreadsheet accurately reflects current component usage for the PW products
**SO THAT** we can assess impact and effort to change all V1 components to V3

## Acceptance criteria

- [ ] Verify the spreadsheet reflects all PW products and their component usage (or lack thereof)
- [ ] Assess impact of changing V1 components to V3
- [ ] verify/review the E2E tests
- [ ] check desktop and mobile

**Comment by jilladams** [comment]
Done.
