### ISSUE TITLE
[CONSIDER] Child care as new service for VAMCs

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-cms#16979]
## Description 
Justin has requested draft language from the program office to get started with a description for a health care service in Drupal.

Danielle sent link to new unauthenticated VA.gov content intake form which Justin will use to initiate the health care hub content

Veterans Child Care Assistant Program - Program Office: VAMCs will offer drop in child care for Veterans with medical appointments. 

Central California VAMC will be launching a drop of site in January 2024. Could this be a page in the health care hub plus a facility health care service. That would put the services/locations into the API. Then someone could build a page with locations using the API.

**Comment by davidmpickett** [comment]
Dupe of https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16312?

**Comment by mmiddaugh** [comment]
Thank you! I'll close this one in favor of #16312
