### ISSUE TITLE
Consider: VBA editor reporting of data changes or inaccuracies

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#16972]
## User Story or Problem Statement
As a VBA editor, I want an easy way to know how to request changes or report inaccuracies for data which I am unable to edit in the CMS.

Examples:
 - Main phone for VBA facility - #17603

## Acceptance Criteria
- [ ] Testable_Outcome_X
- [ ] Testable_Outcome_Y
- [ ] Testable_Outcome_Z
- [ ] Requires design review
- [ ] Requires accessibility review

**Comment by davidmpickett** [comment]
@jilladams @mmiddaugh In light of conversation in scrum today. Do we still need this ticket? Or does the [existing KB article](https://prod.cms.va.gov/help/veterans-benefits-administration-vba/location-and-contact-information) cover this territory sufficiently from an editor perspective?

**Comment by mmiddaugh** [comment]
closing this as no longer needed - process in place
