### ISSUE TITLE
[V3 Components] Upgrade V1 components to V3 for Resources & Support detail page

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-cms#16985]
## Background
The Design team is migrating all V1 components to V3 on February 16, 2024, which means that the PW team needs to upgrade any of our products currently using V1 components to V3.

Resources and support results pages can be 1 of 4 types, Detail pages, FAQ pages, Q&A pages or Step-by-step. This is the ticket for the Detail pages.

**Example pages:**

- [How to use your Login.gov or ID.me account to access My HealtheVet](https://www.va.gov/resources/how-to-use-your-logingov-or-idme-account-to-access-my-healthevet/))
- [In-state tuition rates under the Veterans Choice Act](https://www.va.gov/resources/in-state-tuition-rates-under-the-veterans-choice-act/)
- [Example page with alert](https://www.va.gov/resources/choosing-between-urgent-and-emergency-care/)

### V1 components that need to be upgraded (Actionable)

1. Accordion
   - Accordion sections, in the right side bar, need to be updated [to v3](https://design.va.gov/components/accordion#examples---v3).
2. Alert
   - Component needs to be updated [to v3](https://design.va.gov/components/alert#examples---standard---v3).

## Documentation
[Sitewide V3 DS component review spreadsheet](https://docs.google.com/spreadsheets/d/1A7mQMnL2d5JcDKHZ2daVYQVr85qOljrwM0aUk_inO88/edit#gid=0)

### User story

**AS A** PO/PM for the PW team products, as well as for the Design team
**I WANT** all V1 components to be upgraded to V3 either before or soon after February 16, 2024
**SO THAT** all PW products are in alignment with the new components.

## Acceptance criteria

- [ ] the V3 component is now used for the features listed above, and display/function correctly
- [ ] other features display correctly
- [ ] verify/review the E2E tests
- [ ] check desktop and mobile
- [ ] a11y review

**Comment by chriskim2311** [comment]
This is a no-op the changes have been made in VACMS-16980 for Accordions and Alerts
