### ISSUE TITLE
[V1 & 3 Components] Implement available components for Resources & Support landing page

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-cms#16986]
## Background
The Design team is releasing a Typography update (sometime in March), which means that the PW team needs to upgrade any of our products where components aren't currently being using, but a V1 or V3 component is available.

If the updates aren't made prior to the Typography update, there's a chance that Veteran-facing issues may occur.

The following have been identified by Laura Flannery:

[Resources Landing Page](https://www.va.gov/resources/)

## Elements that are not using components that should be
1. ~Breadcrumbs~ Covered by #17162 
   ~- Not using any component but should be [using v3](https://design.va.gov/components/breadcrumbs#examples---v3)~
2. Link
   - We should be using [the V1 component](https://design.va.gov/components/link/) wherever we can
3. Search input
   - We should be using [the v3](https://design.va.gov/components/search-input#examples---v3)
4. Radio buttons
   - There might be some technical limitations here, I'm not sure but if possible we should be using [v3 components](https://design.va.gov/components/form/radio-button#examples---v3)
5. Button
   - Show all topics button should use [v3 component](https://design.va.gov/components/button/#examples---v3)

## Documentation
[Sitewide V3 DS component review spreadsheet](https://docs.google.com/spreadsheets/d/1A7mQMnL2d5JcDKHZ2daVYQVr85qOljrwM0aUk_inO88/edit#gid=0)

### User story

**AS A** PO/PM for Public Websites products
**I WANT** to implement available V1 or V3 components in features & products currently under Public Websites management where components aren't currently being used
**SO THAT** all PW products are in alignment with the current component version
**AND** Veterans and other users have a consistent experience throughout VA.gov tools and information

## Acceptance criteria

- [ ] Breadcrumbs are using V3
- [x] Link is using V1
- [x] Search is using V3
- [x] Radio button is using V3
- [ ] Buttons are using V3
- [x] other features display correctly
- [x] verify/review the E2E tests
- [x]  check desktop and mobile
- [x] a11y review

**Comment by randimays** [comment]
@FranECross @jilladams Can I remove breadcrumbs from the scope of this ticket, given that we have https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17162?

**Comment by jilladams** [comment]
Yep - we confirmed that yesterday live. Making the change here.

**Comment by randimays** [comment]
Update: The PR (https://github.com/department-of-veterans-affairs/vets-website/pull/28236) is ready for review. It excludes any web component updates for `<button>`. There is a single `<button>` used for the expand/collapse behavior on mobile:
<img width="398" alt="Screenshot 2024-03-01 at 10 24 56 AM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/19175324/201917f3-117b-4221-aa6b-2c62e7708f8c">

This does not need to be converted to a web component as it is stylistically very different from the web component. I have request an accessibility review that we can hopefully get on Monday when Laura returns from PTO.

**Comment by randimays** [comment]
Accessibility review is completed and the changes are verified in production. Closing!
