### ISSUE TITLE
[V3 Components] Upgrade V1 components to V3 for the Benefits Hub Landing Page

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-cms#16981]
## Background
The Design team is migrating all V1 components to V3 on February 16, 2024, which means that the PW team needs to upgrade any of our products using V1 to V3.

Example pages:

- [Health Care](https://www.va.gov/health-care/)
- [Disability](https://www.va.gov/disability/)

### V1 components that need to be upgraded (Actionable)

1. Accordion
   - Accordion sections, in the right side bar, need to be updated [to v3](https://design.va.gov/components/accordion#examples---v3).
2. Alert
   - In the main body content under "On the page", needs to be updated [to v3](https://design.va.gov/components/alert#examples---standard---v3).

## Documentation
[Sitewide V3 DS component review spreadsheet](https://docs.google.com/spreadsheets/d/1A7mQMnL2d5JcDKHZ2daVYQVr85qOljrwM0aUk_inO88/edit#gid=0)

### User story

**AS A** PO/PM for the PW team products, as well as for the Design team
**I WANT** all V1 components to be upgraded to V3 either before or soon after February 16, 2024
**SO THAT** all PW products are in alignment with the new components.

## Acceptance criteria

- [x] V3 components are now used for the accordion and Back to top
- [x] V3 component features display correctly
- [x] verify/review the E2E tests
- [x] check desktop and mobile
- [x] a11y review

**Comment by randimays** [comment]
Successfully validated in staging. Will check again in prod this afternoon.

**Comment by randimays** [comment]
Successfully validated in production. Closing!

Alert (Mobile)
<img width="401" alt="Screenshot 2024-02-21 at 5 04 42 PM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/19175324/c9ca9cf4-af5b-4b5b-8996-5e09da95b132">

Alert (Desktop)
<img width="675" alt="Screenshot 2024-02-21 at 5 04 52 PM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/19175324/05079072-2a40-494b-bb65-3fdc2704b9ea">

Accordion (Desktop - open)
<img width="342" alt="Screenshot 2024-02-21 at 5 04 56 PM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/19175324/9bee1b83-2a6d-4958-9613-c4ff749213f3">

Accordion (Desktop - closed)
<img width="311" alt="Screenshot 2024-02-21 at 5 05 04 PM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/19175324/75c60a4c-4a61-4c17-8bab-8484b4aa3355">
