### ISSUE TITLE
[V3 Components] Upgrade V1 components to V3 for Campaign Landing Pages

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-cms#16982]
## Background
The Design team is migrating all V1 components to V3 on February 16, 2024, which means that the PW team needs to upgrade any of our products currently using V1 components to V3.

Example pages:

- [Sign in securely with Login.gov](https://www.va.gov/initiatives/sign-in-securely-with-logingov/)
- [How Veterans can register to vote](https://www.va.gov/initiatives/vote/)

### V1 components that need to be upgraded (Actionable)

1. Accordion
   - Accordion sections under FAQs need to be updated [to v3](https://design.va.gov/components/accordion#examples---v3).

## Documentation
[Sitewide V3 DS component review spreadsheet](https://docs.google.com/spreadsheets/d/1A7mQMnL2d5JcDKHZ2daVYQVr85qOljrwM0aUk_inO88/edit#gid=0)

### User story

**AS A** PO/PM for the PW team products, as well as for the Design team
**I WANT** all V1 components to be upgraded to V3 either before or soon after February 16, 2024
**SO THAT** all PW products are in alignment with the new components.

## Acceptance criteria

- [ ] V3 components are now used for the accordion and Back to top, and display/function correctly
- [ ] other features display correctly
- [ ] verify/review the E2E tests
- [ ] check desktop and mobile
- [ ] a11y review

**Comment by chriskim2311** [comment]
Verified on Prod, Closing
