### ISSUE TITLE
[V3 Components] Upgrade V1 components to V3 for Find a Form

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-cms#16983]
## Background
The Design team is migrating all V1 components to V3 on February 16, 2024, which means that the PW team needs to upgrade any of our products currently using V1 components to V3.

Pages:

- [Find a Form](https://www.va.gov/find-forms/)
- [Forms results page](https://www.va.gov/find-forms/?q=veteran)
- Form Detail pages:
  - [Example page](https://www.va.gov/find-forms/about-form-0896a/)
  - [Another example](https://www.va.gov/find-forms/about-form-21-526ez/)

### V1 components that need to be upgraded

1. Alert
   - Results screen is currently using v1 and should be using [v3](https://design.va.gov/components/alert#examples---standard---v3)
2. Search input
   - Currently using v1 and should be using [v3](https://design.va.gov/components/search-input#examples---v3)
3. Select
   - Sort by is using v1 and should be using [v3](https://design.va.gov/components/form/select#examples---v3)
4. Modal
   - The modal that pops up to tell the user to download Adobe should use [the v3 component](https://design.va.gov/components/modal#examples---v3)

## Documentation
[Sitewide V3 DS component review spreadsheet](https://docs.google.com/spreadsheets/d/1A7mQMnL2d5JcDKHZ2daVYQVr85qOljrwM0aUk_inO88/edit#gid=0)

### User story

**AS A** PO/PM for the PW team products, as well as for the Design team
**I WANT** all V1 components to be upgraded to V3 either before or soon after February 16, 2024
**SO THAT** all PW products are in alignment with the new components.

## Acceptance criteria

- [ ] V3 components are now used for the features listed above, and display/function correctly
- [ ] other features display correctly
- [ ] verify/review the E2E tests
- [ ] check desktop and mobile
- [ ] a11y review

**Comment by chriskim2311** [comment]
PR ready but is pending review, had some issues with CI to allow for testing in review instance

**Comment by chriskim2311** [comment]
Components have been verified on prod closing!
