### ISSUE TITLE
New VAMC Facility: Temple Terrace VA Clinic

### ISSUE THREAD

**Issue by stefaniefgray** [department-of-veterans-affairs/va.gov-cms#16990]
## Intake
- [x] What triggered this runbook? (Flag in CMS, Help desk ticket, Product team, VHA Digital Media)
Trigger: Flagged Facilities view

- [x] Link to associated help desk ticket (if applicable)
Help desk ticket: https://va-gov.atlassian.net/browse/VAHELP-6890

- [x] Name of submitter (if applicable)
Submitter: @stefaniefgray 

- [x] If the submitter is an editor, send them links to any relevant KB articles for the VAMC Facility product.
KB articles: <insert_kb_article_links>

- [x] Link to facility in production:
Facility CMS link: https://prod.cms.va.gov/tampa-health-care/locations/temple-terrace-va-clinic
Facility API ID: vha_673QM

### New VAMC Facility
Please refer to the Knowledge Base article titled "How do I add a facility to my health care system?" for more information: https://prod.cms.va.gov/help/vamc/about-locations-content-for-vamcs/how-do-i-add-a-facility-to-my-health-care-system

#### CMS help desk steps
**Note: If the help desk is waiting on information from the facility staff or editor, add the "Awaiting editor" flag to the facility with a log message that includes a link to this ticket. Remove the flag when the ticket is ready to be worked by the Facilities team. Be sure to preserve the current moderation state of the node when adding or removing the flag.**
- [x] 1. Become aware that the new facility is now on the Facility API (typically, via a Flag, but this may come in as a helpdesk ticket).
- [x] 2. If the editor has followed the steps from the above Knowledge Base article and included which section and VAMC the facility belongs to (i.e. VA Pittsburgh), great! **Proceed to step 3.** If not, please check with the editor or VHA digital media regarding what section and VAMC it belongs to.
- [x] 3. Updates the Section (default is "VAMC facilities", but it should be a VAMC system in a VISN) and VAMC system field accordingly.
- [x] 4. Communicate with editor (cc VHA Digital Media) to give them go-ahead to complete the content, with this [KB article](https://prod.cms.va.gov/help/vamc/about-locations-content-for-vamcs/how-do-i-add-a-facility-to-my-health-care-system). (See sample notification email below)

<details><summary>Email template </summary>

```

Hello! You should now be able to edit the draft page for this facility, located at [LINK TO NEW FACILITY DRAFT PAGE ON PROD]

Important: Please make sure that all relevant steps listed within the “How do I add a facility to my health care system?” Knowledge Base article have been completed: https://prod.cms.va.gov/help/vamc/about-locations-content-for-vamcs/how-do-i-add-a-facility-to-my-health-care-system

Once finished, please save this page (and all related VAMC Facility Health Service pages) in the moderation state “Draft." Please do not save them as “Published.”

Please let us know when your draft content is complete, so that we can wrap up the technical process from our end before publishing the new facility to VA.gov. Thanks!

```

</details>

- [x] 5. Create a [URL change request](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/new?assignees=&template=runbook-facility-url-change.md&title=URL+Change+for%3A+%3Cinsert+facility+name%3E), changing the entry from the old facility URL to the new facility URL. (**Note: The URL change request ticket blocks the completion of this ticket.**)

https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16989

- [x] 6. When editor has prepared content and let help desk know, reassign this issue to appropriate CMS engineer on Product Support team, for bulk publishing.

#### CMS engineer steps
- [x] 7. CMS engineer executes the steps of the URL change request ticket from step 5 above.

(Redirects deploy weekly on Wed. at 10am ET, or by requesting OOB deploy (of the revproxy job to prod) in #vfs-platform-support. Coordinate the items below and canonical URL change after URL change ticket is merged, deployed, and verified in prod.)

#### Drupal Admin steps (CMS Engineer or Help desk)
_Help desk will complete these steps or escalate to request help from CMS engineering._
- [x] 8. Drupal Admin bulk publishes nodes and facility.
- [x] 9. Drupal Admin edit facility node and remove `New facility` flag and save node.
- [x] 10. Let Help desk know this has been done, if not done by Help desk.

#### CMS Help desk (wrap up)
- [x] 11. Notify editor and any other stakeholders.

**Comment by stefaniefgray** [comment]
Waiting on editor -- see https://va-gov.atlassian.net/browse/VAHELP-6890

**Comment by stefaniefgray** [comment]
Editor still needs to add health services, was reminded 2/8/2024

**Comment by stefaniefgray** [comment]
Issue may need to be escalated to VHA Digital Media -- have tagged @xiongjaneg and @mmiddaugh 

Editor received instructions on 1/18, 2/6 and 2/8 to add health services (which must be added before homepage can be published) and is now frustrated that homepage hasn't been added yet: https://va-gov.atlassian.net/browse/VAHELP-6890

**Comment by xiongjaneg** [comment]
@omahane This one's ready for step 7.

**Comment by omahane** [comment]
@xiongjaneg There seems to be some confusion about what should be put in the Meta description field. Typically, it's
> Get address and hours, parking and transportation information, and health services offered at [facility name]

In this case, it's 
> 8451 Temple Terrace Hwy; Hours of Operation 7 a.m. to 7 p.m.; (813) 631-7100; Onsite parking lot, shuttle available from Main Hospital campus; Mental Health Outpatient Services and Domiciliary

There's another point of confusion. The hours in the Meta description differ from the hours listed on the facility, which are M-F 8 - 4:30.

On a related note, it looks like we have a broken link here:
![Screenshot 2024-02-26 at 9 39 41 AM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/766573/3bc37e12-1e35-4ea4-ab0b-dc6f95042074)

We can make the Meta description more in line with other facilities and can still move forward with publishing this, but I think we need to reach out to the editor to make sure the hours on the facility are correct. (CC: @ian-sears ) If they are not correct, the VAST administrator will need to make a change.

**Comment by xiongjaneg** [comment]
Sounds good. I've been in touch with the editor so will let her know about the meta description being more in line with other facilities.

**Comment by xiongjaneg** [comment]
I'll stub a ticket for the See further guidelines broken link.

**Comment by xiongjaneg** [comment]
Request to change meta description submitted to editor

**Comment by xiongjaneg** [comment]
@omahane No response by editor on meta description, proceed as planned with standardizing meta description

**Comment by omahane** [comment]
@xiongjaneg I have published this, but it really needs a photo.

**Comment by xiongjaneg** [comment]
Will add to VHA DM sync

**Comment by omahane** [comment]
@ian-sears The CSV has been deployed and this now shows on Facility Locator.

**Comment by xiongjaneg** [comment]
Verified on VA.gov Facility Locator and link to facility page
![Uploading Screenshot 2024-03-22 at 3.25.52 PM.png…]()

**Comment by xiongjaneg** [comment]
<img width="1036" alt="Screenshot 2024-03-22 at 3 26 07 PM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/73648238/54f5fc9b-359a-4fe3-8a56-c1c3bd56d4c9">

**Comment by ian-sears** [comment]
All Stakeholders have been notified that the Temple Terrace VA Clinic page is now live.
**Reference:** [https://va-gov.atlassian.net/browse/VAHELP-7207](https://va-gov.atlassian.net/browse/VAHELP-7207)
