### ISSUE TITLE
[V3 Components] Upgrade V1 components to V3 for Income Limits

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-cms#17003]
## Background
The Design team is migrating all V1 components to V3 on February 16, 2024, which means that the PW team needs to upgrade any of our products currently using V1 components to V3.

[Income Limits App](https://www.va.gov/health-care/income-limits/introduction)

### V1 components that need to be upgraded

1. Accordion
   - Accordion section on results screen to be updated [to v3](https://design.va.gov/components/accordion#examples---v3).
2. Alert
   - Currently using v1 and should be using [v3](https://design.va.gov/components/alert#examples---standard---v3)
3. Button
   - Back button on results sreen should be using the [v3 component](https://design.va.gov/components/button/#examples---v3)
4. Button pair
   - Each screen should be using the [v3 component](https://design.va.gov/components/button/button-pair#examples---v3)
5. Number input
   - Each screen should be using the [v3 component](https://design.va.gov/components/form/number-input)
6. Additional Input
   - Dependent screen should have [v3 component](https://design.va.gov/components/additional-info)
7. Select
   - Previous years screen should have [v3 component](https://design.va.gov/components/form/select#examples---v3)

## Documentation
[Sitewide V3 DS component review spreadsheet](https://docs.google.com/spreadsheets/d/1A7mQMnL2d5JcDKHZ2daVYQVr85qOljrwM0aUk_inO88/edit#gid=0)

### User story

**AS A** PO/PM for the PW team products, as well as for the Design team
**I WANT** all V1 components to be upgraded to V3 either before or soon after February 16, 2024
**SO THAT** all PW products are in alignment with the new components.

## Acceptance criteria

- [ ] the V3 components are now used for the features listed above, and display/function correctly
- [ ] other features display correctly
- [ ] verify/review the E2E tests
- [ ] check desktop and mobile
- [ ] a11y review

**Comment by randimays** [comment]
Validated successfully in staging. Will verify in production tomorrow afternoon.

**Comment by randimays** [comment]
Successfully validated in production 👍🏻
