### ISSUE TITLE
Facilities Draft Sprint 103 Plan

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#17008]
## Schedule Notes
- Jane out 2/5
- Jill 1/2 day 2/13

## Sprint Priorities 🎯 
At the end of this sprint, what do we want to have accomplished/delivered?

Tickets for top priority:
- 🎯 UX Design: #16855 carrying over for feedback/updates
- 🎯 UX Research: #16823 carrying over for recruitment plan
- 🎯 Drupal: #16469 
- 🎯 FE: #16921 

### UX
- Police: #16812 carrying over
- VBA: #15752 
- VBA: #17096 
- Facility Locator: #17074 
- tickets in epic #16337 

### Drupal
- VBA/VAMC: #15559 carrying over
- VBA/VAMC: #16348 carrying over
- VBA: #16327 
- VAMC: #15686
- VAMC: #16233 
- Police: #16641 

### Front End
- VBA: #14957 carrying over due to block
- VBA: #16921 
- VAMC/VBA: #16144 
- VBA: #15959 
- USWDS: #17037 
- USWDS: #17038 
- USWDS: #17042 
- USWDS: #17043
- USWDS: #17045 
- USWDS: #17049 
- USWDS: #17058 
- USWDS: #17065

**Comment by jilladams** [comment]
@xiongjaneg FYI, duped the 102 plan. Only diff here so far is adding PTO, and adding #15686 to Drupal list based on Michelle's note re: PAO timing.

**Comment by mmiddaugh** [comment]
Noting timing for #15686 may need to be adjusted based on the deadline for editors (which is now 2/8 but could be extended to 2/15)

**Comment by mmiddaugh** [comment]
@xiongjaneg I thought we planned to pull [Vet Center unpublished services should not be showing on VA.gov #16362](https://app.zenhub.com/workspaces/sitewide-facilities-639f5253e4b702a32376339e/issues/gh/department-of-veterans-affairs/va.gov-cms/16362) into this sprint?

**Comment by xiongjaneg** [comment]
@mmiddaugh We had to bump a bunch of front end for USWDS V3
