### ISSUE TITLE
[V3 Components] Upgrade V1 components to V3 for the Home Page

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-cms#17002]
## Background
The Design team is migrating all V1 components to V3 on February 16, 2024, which means that the PW team needs to upgrade any of our products currently using V1 components to V3.

[Homepage](https://www.va.gov/)

### V1 components that need to be upgraded (Actionable)

1. Search input
   - In the main body section, the v1 component is used and should be updated [to v3](https://design.va.gov/components/search-input#examples---v3)
## Documentation
[Sitewide V3 DS component review spreadsheet](https://docs.google.com/spreadsheets/d/1A7mQMnL2d5JcDKHZ2daVYQVr85qOljrwM0aUk_inO88/edit#gid=0)

### User story

**AS A** PO/PM for the PW team products, as well as for the Design team
**I WANT** all V1 components to be upgraded to V3 either before or soon after February 16, 2024
**SO THAT** all PW products are in alignment with the new components.

## Acceptance criteria

- [x] the V3 component is now used for the features listed above, and display/function correctly
- [x] other features display correctly
- [x] verify/review the E2E tests
- [x] check desktop and mobile
- [x] a11y review

**Comment by randimays** [comment]
Successfully validated in production. Closing!

<img width="365" alt="Screenshot 2024-02-22 at 8 06 07 PM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/19175324/de83664e-a593-4892-91c6-5b82112384b4">
<img width="501" alt="Screenshot 2024-02-22 at 8 06 02 PM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/19175324/beff4108-02a6-4e45-b3f8-0164eedbea46">
<img width="400" alt="Screenshot 2024-02-22 at 8 05 57 PM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/19175324/163b103e-f9a3-4b6a-943c-b302b3090bdf">
