### ISSUE TITLE
[V3 Components] Upgrade V1 components to V3 for the the Discharge Upgrade Wizard

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-cms#17005]
## Background
The Design team is migrating all V1 components to V3 on February 16, 2024, which means that the PW team needs to upgrade any of our products currently using V1 components to V3.

Pages:

- [Discharge Upgrade instructions](https://www.va.gov/discharge-upgrade-instructions/)
- [Discharge upgrade Wizard](https://www.va.gov/discharge-upgrade-instructions/questions)
- [Discharge upgrade guidance (results)](https://www.va.gov/discharge-upgrade-instructions/guidance)

### V1 components that need to be upgraded to V3

**NOTE: Any links to v3 components are the generic V3 component since I know we are planning to redo this during Q1. Specific variants (ie. headers, hint text, etc.) will be reviewed during that work, not here.**

1. Radio
   - Each radio to be updated to be updated [to v3](https://design.va.gov/components/form/radio-button#examples---v3).
3. Select
   - Previous years screen should have [v3 component](https://design.va.gov/components/form/select#examples---v3)
4. Alert
   - Results screen is currently using v1 and should be using [v3](https://design.va.gov/components/alert#examples---standard---v3)

## Documentation
[Sitewide V3 DS component review spreadsheet](https://docs.google.com/spreadsheets/d/1A7mQMnL2d5JcDKHZ2daVYQVr85qOljrwM0aUk_inO88/edit#gid=0)

### User story

**AS A** PO/PM for the PW team products, as well as for the Design team
**I WANT** all V1 components to be upgraded to V3 either before or soon after February 16, 2024
**SO THAT** all PW products are in alignment with the new components.

## Acceptance criteria

- [ ] the V3 components are now used for the features listed above, and display/function correctly
- [ ] other features display correctly
- [ ] verify/review the E2E tests
- [ ] check desktop and mobile
- [ ] a11y review

**Comment by jilladams** [comment]
@laflannery FYI: verified in prod re: radio, select, alert on results screen. Closing.
