### ISSUE TITLE
Traffic routing mechanism implemented for VA dev and staging and verified there

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#17024]
## Requirements

We want to create the traffic routing setup for VA dev and staging environments, so that we can test the proposed setup against realistic infrastructure and find any issues that might arise. 

```[tasklist]
### Acceptance criteria
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16475
```

## Background & implementation details

The RFC for the traffic router is here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/accelerated_publishing/rfc/reverse-proxy-falback.md

This work may be as simple as merging the work from the Sandbox ticket.

**Comment by nfpappas-oddball** [comment]
Code for nextjs rev-proxy has been merged into the rev-proxy repo. Platform team is int he process of rolling out this update. Currently it is in dev and staging, prod is planned to be there by the end of the week
