### ISSUE TITLE
Front end: Modify VAMC Register for care template to opt out of USWDS V3 automatic upgrade 

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#17036]
## User Story or Problem Statement
On 2/16, USWDS V1 components will default to V3. V1 components that have V3 versions will be automatically upgraded unless we opt out proactively. Opting out means: modifying those existing V1 components to pass in the uswds={false}.

VAMC Register for care template needs to be modified to opt out of V1 to V3 automatic upgrade.

### List of v3 components
If the component is not on this list, do not add the `uswds` attribute:
- [Accordion](https://design.va.gov/components/accordion)
- [Additional Info](https://design.va.gov/components/additional-info)
- [Alert](https://design.va.gov/components/alert)
- [Button](https://design.va.gov/components/button/)
- [Button Pair](https://design.va.gov/components/button/button-pair)
- [Featured Content](https://design.va.gov/components/featured-content)
- [Pagination](https://design.va.gov/components/pagination)

## Findings
- Breadcrumbs
These are currently not using a component at all but they should be using [the v3 component](https://design.va.gov/components/breadcrumbs#examples---v3)
- Link
These are currently not using a component at all but all links should be using [the v1 component](https://design.va.gov/components/link/)

## Acceptance Criteria
 - [ ] Existing V1 components are modified to pass in the uswds={false}

**Comment by xiongjaneg** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Sitewide-Facilities-639f5253e4b702a32376339e/issues/department-of-veterans-affairs/va.gov-cms/17036?planning-poker) with Zenhub @eselkin

**Comment by xiongjaneg** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Sitewide-Facilities-639f5253e4b702a32376339e/issues/department-of-veterans-affairs/va.gov-cms/17036?planning-poker) with Zenhub @maxx1128

**Comment by eselkin** [comment]
We're assuming this is just for components, right @xiongjaneg not the classes that may come from design system.

**Comment by xiongjaneg** [comment]
@laflannery Do you have an answer for Eli's question? ^

**Comment by laflannery** [comment]
@eselkin Yes, just actual components

**Comment by xiongjaneg** [comment]
Closing, these are not currently using V1 components with V3 equivalents
