### ISSUE TITLE
Front end: Modify VAMC System template to opt out of USWDS V3 automatic upgrade

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#17034]
## User Story or Problem Statement
On 2/16, USWDS V1 components will default to V3. V1 components that have V3 versions will be automatically upgraded unless we opt out proactively. Opting out means: modifying those existing V1 components to pass in the uswds={false}.

VAMC System templates needs to be modified to opt out of V1 to V3 automatic upgrade.

### v3 components
- Breadcrumbs
These are currently not using a component at all but they should be using [the v3 component](https://design.va.gov/components/breadcrumbs#examples---v3)
- Link
These are currently not using a component at all but they should be using [the v1 component](https://design.va.gov/components/link/)
This would also apply anywhere a basic link is used - Get Directions, Spotlight
NOTE: Active links for CTA https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15598
- Telephone
These are currently not using a component at all but they should be using aria-describedby [v1 component](https://design.va.gov/components/telephone#aria-described-by)

## Acceptance Criteria
- [ ] Existing V1 components that have a v3 equivalent are modified to pass in the uswds={false}

**Comment by xiongjaneg** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Sitewide-Facilities-639f5253e4b702a32376339e/issues/department-of-veterans-affairs/va.gov-cms/17034?planning-poker) with Zenhub @eselkin @maxx1128

**Comment by eselkin** [comment]
I pointed as a 3. The reason so high is it's going to require building and rebuilding content-build many times.

**Comment by xiongjaneg** [comment]
Closing, not currently using V1 components with V3 equivalents
