### ISSUE TITLE
Front end: Modify VAMC Police template to opt out of USWDS V3 automatic upgrade 

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#17037]
## User Story or Problem Statement
On 2/16, USWDS V1 components will default to V3. V1 components that have V3 versions will be automatically upgraded unless we opt out proactively. Opting out means: modifying those existing V1 components to pass in the uswds={false}.

VAMC Police template needs to be modified to opt out of V1 to V3 automatic upgrade.

### List of applicable components
- Accordion

## Acceptance Criteria
- [x] All instances of the accordion component are modified to pass in the uswds={false}

**Comment by xiongjaneg** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Sitewide-Facilities-639f5253e4b702a32376339e/issues/department-of-veterans-affairs/va.gov-cms/17037?planning-poker) with Zenhub @maxx1128 @eselkin

**Comment by eselkin** [comment]
Check featured_content and contact_section and centralized_content and above-footer-elements

**Comment by xiongjaneg** [comment]
@maxx1128 @eselkin The ACs are updated to just the accordions. Please repoint as appropriate. Thank you!

**Comment by eselkin** [comment]
Checked, done
