### ISSUE TITLE
Front end: Modify VAMC Detail page template to opt out of USWDS V3 automatic upgrade

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#17043]
## User Story or Problem Statement
On 2/16, USWDS V1 components will default to V3. V1 components that have V3 versions will be automatically upgraded unless we opt out proactively. Opting out means: modifying those existing V1 components to pass in the uswds={false}.

VAMC Detail page template needs to be modified to opt out of V1 to V3 automatic upgrade.

### List of applicable components
- Accordion
- Alert
- Button
   - For reference, it was found inside the alert we want to make sure any instance of the button component is opted out of though

## Acceptance Criteria
- [ ] Existing V1 components are modified to pass in the uswds={false}
  - [ ] Accordions
  - [ ] Alert
  - [ ] Button

**Comment by xiongjaneg** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Sitewide-Facilities-639f5253e4b702a32376339e/issues/department-of-veterans-affairs/va.gov-cms/17043?planning-poker) with Zenhub @eselkin @maxx1128

**Comment by xiongjaneg** [comment]
@maxx1128 @eselkin The description and ACs have been updated. Please repoint. Thank you!

**Comment by eselkin** [comment]
Is it possible to give which pages had the button?

**Comment by xiongjaneg** [comment]
@laflannery Do you have more info on the button in reference?

**Comment by laflannery** [comment]
@xiongjaneg Eli and I figured this out and it was a button in a Sign in alert that was covered with the Medical Records update ticket so this should be all set here
