### ISSUE TITLE
Front end: Modify VAMC Health services template to opt out of USWDS V3 automatic upgrade

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#17042]
## User Story or Problem Statement
On 2/16, USWDS V1 components will default to V3. V1 components that have V3 versions will be automatically upgraded unless we opt out proactively. Opting out means: modifying those existing V1 components to pass in the uswds={false}.

VAMC Health service template needs to be modified to opt out of V1 to V3 automatic upgrade.

### List of applicable components
-  Accordion: Being used on Prepare for your visit and services sections

## Acceptance Criteria
- [x] All accordion components are modified to pass in the uswds={false}

**Comment by xiongjaneg** [comment]
@maxx1128 @eselkin The description and ACs have been updated. Please repoint. Thank you!

**Comment by maxx1128** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VAgov-CMS-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/17042?planning-poker) with Zenhub @eselkin

**Comment by eselkin** [comment]
Checked, done
