### ISSUE TITLE
Front end: Modify VAMC Facility template to opt out of USWDS V3 automatic upgrade

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#17040]
## User Story or Problem Statement
On 2/16, USWDS V1 components will default to V3. V1 components that have V3 versions will be automatically upgraded unless we opt out proactively. Opting out means: modifying those existing V1 components to pass in the uswds={false}.

VAMC Facility template needs to be modified to opt out of V1 to V3 automatic upgrade.

### List of v3 components

- Accordion

## Acceptance Criteria
- [ ] Accordion sections (Prepare for your visit and services) are modified to pass in the uswds={false}

**Comment by xiongjaneg** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Sitewide-Facilities-639f5253e4b702a32376339e/issues/department-of-veterans-affairs/va.gov-cms/17040?planning-poker) with Zenhub @eselkin @maxx1128

**Comment by xiongjaneg** [comment]
@maxx1128 @eselkin The description and ACs have been updated on this ticket. Please repoint. Thank you!

**Comment by laflannery** [comment]
Closing Confirmed on [Prod](https://www.va.gov/boston-health-care/locations/jamaica-plain-va-medical-center/)
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/106678594/95e7ecc3-7b0d-4b6c-aebc-4a025c338289)
