### ISSUE TITLE
Terms ready for VBA approval

### ISSUE THREAD

**Issue by davidmpickett** [department-of-veterans-affairs/va.gov-cms#17046]
Label and link to Drupal | Notes | Status | 
| -- | --  | -- |
[Benefit letters and decision letters](https://prod.cms.va.gov/health-care/benefit-letters-and-decision-letters) |  | Ready for CAIA review | 
[Burials and memorials](https://prod.cms.va.gov/health-care/burials-and-memorials) | | Ready for CAIA review | 
[Careers and employment](https://prod.cms.va.gov/health-care/careers-and-employment)| |Ready for CAIA review | 
[Compensation benefits for survivors](https://prod.cms.va.gov/health-care/compensation-benefits-for-survivors) | | Ready for CAIA review
[Direct deposit information](https://prod.cms.va.gov/health-care/direct-deposit-information) | | Ready for CAIA review | 
[Disability compensation](https://prod.cms.va.gov/health-care/disability-compensation) |  | Ready for CAIA review | 
[Education benefits for family members](https://prod.cms.va.gov/health-care/education-benefits-for-family-members) |   Regional | Ready for CAIA review | 
[Education benefits for Veterans](https://prod.cms.va.gov/health-care/education-benefits-for-veterans) | Regional  | Ready for CAIA review | 
[Grief and bereavement counseling](https://prod.cms.va.gov/health-care/grief-and-bereavement-counseling) | feedback incorporated | Ready for CAIA review | 
[Home loans](https://prod.cms.va.gov/health-care/home-loans) | Regional | Ready for CAIA review | 
[Homeless Veteran care](https://prod.cms.va.gov/health-care/homeless-veteran-care) | feedback incorporated | Ready for CAIA review | 
[Life Insurance](https://prod.cms.va.gov/health-care/life-insurance) |  | Ready for CAIA review | 
[Military records](https://prod.cms.va.gov/health-care/military-records) | feedback incorporated: medical records combined here rather than as a separate service | Ready for CAIA review | 
[Military sexual trauma-related claims](https://prod.cms.va.gov/health-care/military-sexual-trauma-claims) |  feedback incorporated | Ready for CAIA review | 
[Pre-discharge claims](https://prod.cms.va.gov/health-care/pre-discharge-claims) |  | Ready for CAIA review | 
[Pre-need burial planning](https://prod.cms.va.gov/health-care/pre-need-burial-planning) |  | Ready for CAIA review
[Returning service member care](https://prod.cms.va.gov/health-care/returning-service-member-care) | feedback incorporated| Ready for CAIA review | 
[Transition assistance](https://prod.cms.va.gov/health-care/transition-assistance)  |   | Ready for CAIA review
[Veterans Pension](https://prod.cms.va.gov/health-care/veterans-pension) | Regional | Ready for CAIA review | 
[VetSuccess on Campus](https://prod.cms.va.gov/health-care/vetsuccess-on-campus) |   | Ready for CAIA review | 

**Regional** = These are Services that I have drafted Regional service header & description fields for. My understanding is these are services that have regional centers that veterans can meaningfully interact with.

Field | Notes for content reviewers
-- | --
Show for VBA Facilities | This is where the VBA fields begin
Type of care | Previously reviewed. Looking for final approval on wording (CAIA) and categorization (VBA)
VBA description | Previously reviewed. These have all been copy-edited by CAIA & updated with feedback from VBA. Looking for final approval.
Regional service header | Needs review from CAIA (wording) & VBA (correct task for region?)
Regional service description | Needs review from CAIA (wording) & VBA (correct task for region?)
Facility service header | Needs review from CAIA (wording) & VBA (correct local task?)
Facility service description | Needs review from CAIA (wording) & VBA (correct local task?)
Online self-service |  Needs review from CAIA & VBA (wording & link)

![VBA Content model_2023-12-11_23-17-13](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/b33fbba7-0973-448d-9d18-b12f2ef4fdcb)

## Acceptance Criteria
- [ ] Terms are approved by VBA
- [ ] After VBA approval, update [the CAIA feedback ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/74390) for sending over

**Comment by davidmpickett** [comment]
Not blocking staging review, can comfortably roll into National Roll out epic

**Comment by davidmpickett** [comment]
@mmiddaugh FYI - I updated the table here to reflect work completed in #17060

**Comment by davidmpickett** [comment]
@mmiddaugh Did you ever get any feedback from VBA on the `Regional service header` and `Regional service descriptions` drafts on terms that have it? These fields were basically just educated guesses on my part and [CAIA](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17695) is asking (good) questions about them that I can't answer.

**Comment by davidmpickett** [comment]
Moving this to Admin/Workflow. @mmiddaugh considering we have published VBAs, I feel like VBA has implicitly approved all the basic of all service terms. Would you agree? If we want a way to track feedback about Service Region fields, we could cut a more specific ticket

**Comment by Agile6MSkinner** [comment]
Bumping this as I look to close out VBA ROs before the end of Q3 and this is basically the only ticket left. @mmiddaugh do you agree with @davidmpickett we can consider these approved?

**Comment by Agile6MSkinner** [comment]
Per comments in [this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/74390#issuecomment-2364587617), we can close this.
