### ISSUE TITLE
Front end: Modify Facility Locator template to opt out of USWDS V3 automatic upgrade 

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#17049]
## User Story or Problem Statement
On 2/16, USWDS V1 components will default to V3. V1 components that have V3 versions will be automatically upgraded unless we opt out proactively. Opting out means: modifying those existing V1 components to pass in the uswds={false}.

Facility Locator template needs to be modified to opt out of V1 to V3 automatic upgrade.

### List of applicable components
- Breadcrumbs
- Alert (slim)
- Modal
  - For reference this appears if you click "Use my location" but you are not sharing your location settings in your browser
- Pagination

## Acceptance Criteria
 - [x] Breadcrumb component is modified to pass in the uswds={false}
 - [x] All v1 slim alert components are modified to pass in the uswds={false}
 - [x] Modal component is modified to pass in the uswds={false}
 - [x] Pagination component is modified to pass in the uswds={false}

**Comment by xiongjaneg** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Sitewide-Facilities-639f5253e4b702a32376339e/issues/department-of-veterans-affairs/va.gov-cms/17049?planning-poker) with Zenhub @eselkin @maxx1128

**Comment by eselkin** [comment]
Checked
