### ISSUE TITLE
Front end: Modify Vet Center templates to opt out of USWDS V3 automatic upgrade

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#17045]
## User Story or Problem Statement
On 2/16, USWDS V1 components will default to V3. V1 components that have V3 versions will be automatically upgraded unless we opt out proactively. Opting out means: modifying those existing V1 components to pass in the uswds={false}.

Vet Center templates (Includes both main page and locations listing page) needs to be modified to opt out of V1 to V3 automatic upgrade.

### List of applicable components
- Accordion
- Alert

## Acceptance Criteria
- [x] All accordion components are modified to pass in the uswds={false}
- [x] All alert components are modified to pass in the uswds={false}

**Comment by xiongjaneg** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Sitewide-Facilities-639f5253e4b702a32376339e/issues/department-of-veterans-affairs/va.gov-cms/17045?planning-poker) with Zenhub @eselkin @maxx1128

**Comment by eselkin** [comment]
Simnilar to my other estimate requires a lot of rebuilding content-build and vets-website.

**Comment by xiongjaneg** [comment]
@eselkin @maxx1128 The description and ACs have been modified. Please repoint. Thank you!

**Comment by laflannery** [comment]
@eselkin and @maxx1128 I updated the description and ACs to indicate which components you should have to worry about, it should only be accordion and alert, if that changes your estimate at all CC: @xiongjaneg

**Comment by eselkin** [comment]
Checked, done
