### ISSUE TITLE
[V3 Components] Upgrade V1 components to V3 for Global Search results

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#17050]
## Background
The Design team is migrating all V1 components to V3 on February 16, 2024, which means that the PW team needs to upgrade any of our products currently using V1 components to V3.

[Search results](https://www.va.gov/search/)

### V1 components that need to be upgraded (Actionable)

1. Alert
   - Search error alert is using v1 and needs to be updated [to v3](https://design.va.gov/components/alert)

## Documentation
[Sitewide V3 DS component review spreadsheet](https://docs.google.com/spreadsheets/d/1A7mQMnL2d5JcDKHZ2daVYQVr85qOljrwM0aUk_inO88/edit#gid=0)

### User story

**AS A** PO/PM for the PW team products, as well as for the Design team
**I WANT** all V1 components to be upgraded to V3 either before or soon after February 16, 2024
**SO THAT** all PW products are in alignment with the new components.

## Acceptance criteria

- [x] the V3 component is now used for the features listed above, and display/function correctly
- [x] other features display correctly
- [x] verify/review the E2E tests
- [x] check desktop and mobile
- [ ] a11y review

**Comment by randimays** [comment]
Laura verified this in staging ([Slack thread here](https://dsva.slack.com/archives/C52CL1PKQ/p1708365549859879)). Just did a visual check in production; we're good to go!

<img width="1033" alt="Screenshot 2024-02-19 at 3 11 16 PM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/19175324/24499b85-df07-46c1-bd0a-47f43952e2e8">

<img width="426" alt="Screenshot 2024-02-19 at 3 11 28 PM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/19175324/3952f9e6-3de5-4190-b69d-8fd69039a931">
