### ISSUE TITLE
[V1 & 3 Components] Implement available components for Event Detail page

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#17057]
## Background
The Design team is releasing a Typography update (sometime in March), which means that the PW team needs to upgrade any of our products where components aren't currently being using, but a V1 or V3 component is available.

If the updates aren't made prior to the Typography update, there's a chance that Veteran-facing issues may occur.

The following have been identified by Laura Flannery:

Example Pages:
- [VAMC Events Page](https://www.va.gov/minneapolis-health-care/events/64415/)
- [National Event Page](https://www.va.gov/outreach-and-events/events/53182/)

### Elements that are not using components that should be (Backlog)
1. Link
   - We should be using this everywhere possible
2. Accordion
   - On recurring events, there is an accordion to show more times which should use [the v3 component](https://design.va.gov/components/accordion#examples---v3)

## Documentation
[Sitewide V3 DS component review spreadsheet](https://docs.google.com/spreadsheets/d/1A7mQMnL2d5JcDKHZ2daVYQVr85qOljrwM0aUk_inO88/edit#gid=0)

### User story

**AS A** PO/PM for Public Websites products
**I WANT** to implement available V1 or V3 components in features & products currently under Public Websites management where components aren't currently being used
**SO THAT** all PW products are in alignment with the current component version
**AND** Veterans and other users have a consistent experience throughout VA.gov tools and information
## Acceptance criteria

- [x] Links are using V1
- [x] Accordion is using V3
- [x] other features display correctly
- [x] verify/review the E2E tests
- [x] check desktop and mobile
- [x] a11y review

**Comment by randimays** [comment]
Verified successfully in prod. Closing!
