### ISSUE TITLE
[V3 Components] Upgrade V1 components to V3 for Step-by-Step page

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#17053]
## Background
The Design team is migrating all V1 components to V3 on February 16, 2024, which means that the PW team needs to upgrade any of our products currently using V1 components to V3.

Resources and support results pages can be 1 of 4 types, Detail pages, FAQ pages, Q&A pages or Step-by-step. This is the ticket for the Step-by-Step pages.

**Example pages:**

- [How to check in with your smartphone for some VA appointments](https://www.va.gov/resources/how-to-check-in-with-your-smartphone-for-some-va-appointments/)
- [How to set up direct deposit for VA travel pay reimbursement](https://www.va.gov/resources/how-to-set-up-direct-deposit-for-va-travel-pay-reimbursement/)

### V1 components that need to be upgraded (Actionable)

1. Alert
   - Component needs to be updated [to v3](https://design.va.gov/components/alert#examples---standard---v3).

## Documentation
[Sitewide V3 DS component review spreadsheet](https://docs.google.com/spreadsheets/d/1A7mQMnL2d5JcDKHZ2daVYQVr85qOljrwM0aUk_inO88/edit#gid=0)

### User story

**AS A** PO/PM for the PW team products, as well as for the Design team
**I WANT** all V1 components to be upgraded to V3 either before or soon after February 16, 2024
**SO THAT** all PW products are in alignment with the new components.

## Acceptance criteria

- [ ] the V3 component is now used for the features listed above, and display/function correctly
- [ ] other features display correctly
- [ ] verify/review the E2E tests
- [ ] check desktop and mobile
- [ ] a11y review

**Comment by laflannery** [comment]
@FranECross this got lost because when I made it I forgot to add it to the epic. I have now added it and edited it to match all the others

**Comment by randimays** [comment]
Noting here that the above PR ^ will take care of the changes necessary for this as well. I'll verify in staging/production as appropriate.

**Comment by randimays** [comment]
Confirming that this PR: https://github.com/department-of-veterans-affairs/content-build/pull/1918 took care of the changes needed for Step-by-Step pages. Just verified in production here: https://www.va.gov/resources/how-to-change-direct-deposit-information-for-va-benefits/ Closing!

## Desktop
<img width="989" alt="Screenshot 2024-02-22 at 8 24 04 PM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/19175324/edfe1b97-21d7-4711-84ce-cecf5b94f506">

## Mobile
<img width="402" alt="Screenshot 2024-02-22 at 8 24 15 PM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/19175324/95e962df-2688-47bc-9255-581c03b168f3">

**Comment by laflannery** [comment]
@randimays is the correct PR referenced in your comment? I was trying to look at some other stuff and then I realized that the PR is not yet on Prod but you are correct that the Step-by-Step updates are, so maybe this is in a different PR?
![image](https://github.com/department-of-veterans-affairs/content-build/assets/106678594/486e8867-3dbe-412b-8b74-bba200ae530f)

**Comment by randimays** [comment]
Correcting a previous mistake. This PR: https://github.com/department-of-veterans-affairs/content-build/pull/1917 (for Benefit Hub Landing pages) actually took care of the changes for the Step-by-Step page, not the one for Benefit Hub Detail Pages :)
