### ISSUE TITLE
Create Search.gov failures alert

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#17055]
## Background
Sometimes Search.gov goes down during maintenance windows and returns 503/504 errors. 

Slack thread: https://dsva.slack.com/archives/C05THHJHH2R/p1706291872067999?thread_ts=1706290263.066329&cid=C05THHJHH2R and distilled relevant notes: 
* We want to create an alert specifically on [search.gov](http://search.gov/) failures.
* We could set up a monitor on fwdproxy error responses and maybe do a [composite monitor](https://docs.datadoghq.com/monitors/types/composite/) of both that should show at a glance where the problem is occurring
*  https://docs.datadoghq.com/monitors/guide/create-monitor-dependencies/ is also useful to look at
* Search.gov's status page is not always accurate, and they do not have a healthcheck page we could query / report on
* the simplest approach is probably a dashboard widget or monitor using a [log query](https://vagov.ddog-gov.com/logs?query=%40message_content%3A%22undefined%20method%20%60dig%27%20for%20%5C%22%3Ch2%3EThis%20website%20is%20under%20heavy%20load%20%28queue%20full%29%3C%2Fh2%3E%3Cp%3EWe%27re%20sorry%2C%20too%20many%20people%20are%20accessing%20this%20website%20at%20the%20same%20time.%20We%27re%20working%20on%20this%20problem.%20Please%20try%20again%20later.%3C%2Fp%3E%5C%22%3AString.%22%20&agg_q=status%2Cservice&cols=host%2Cservice&index=&messageDisplay=inline&refresh_mode=sliding&sort_m=%2C&sort_t=%2C&stream_sort=desc&top_n=10%2C10&top_o=top%2Ctop&viz=pattern&x_missing=true%2Ctrue&from_ts=1705692296475&to_ts=1706297096475&live=true) for the heavy load error. 
  * Handling these errors in vets-api (in  #16784 ) is a good improvement, and composite monitors or monitor dependencies would prevent the alert from triggering when there are no actionable remediation steps.
* Can we see what the error rate is like? For example any time [search.gov](http://search.gov/) fails 50% of searches we probably want to escalate that, vs periodic transient errors.

## Acceptance criteria

- [ ] A monitor is added that: (logic for monitor? how frequently does it run, or does it aggregate logs? error/alarm conditions?)
  - [ ] Monitor is added to [Public Websites Datadog dashboard](https://vagov.ddog-gov.com/dashboard/szu-xny-9fu/public-websites-dashboard?refresh_mode=paused&from_ts=1696143600000&to_ts=1697236380000&live=false)
  - [ ] Monitor alarms to #public-websites-monitoring
  - [ ] Monitor is assigned within Datadog to the VFS Sitewide Public Websites team
  - [ ] Monitor includes `search` label
- [ ] [Search monitoring doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/on-site-search/engineering/monitoring.md) is updated with
  - [ ] Monitor link & description
  - [ ] Triage steps

**Comment by FranECross** [comment]
@jilladams I think Ari did the work for this ticket, but it's in the Refined column. Should it be closed, or do you know if there's still work to be done? Thanks!

**Comment by jilladams** [comment]
Good catch - moved to Reivew / QA. Notes with Ari re: next steps here: https://dsva.slack.com/archives/C06RWEW3S3W/p1712785143006479. He expects to have next steps sorted by end of week.
