### ISSUE TITLE
Front end: Modify Stories, News releases templates to opt out of USWDS V3 automatic upgrade 

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#17051]
## User Story or Problem Statement
On 2/16, USWDS V1 components will default to V3. V1 components that have V3 versions will be automatically upgraded unless we opt out proactively. Opting out means: modifying those existing V1 components to pass in the uswds={false}.

List content type templates need to be modified to opt out of V1 to V3 automatic upgrade. This includes:
- Stories
- News releases

### List of v3 components
Add the `uswds` attribute only to components on this list:
- [Accordion](https://design.va.gov/components/accordion)
- [Additional Info](https://design.va.gov/components/additional-info)
- [Alert](https://design.va.gov/components/alert)
- [Button](https://design.va.gov/components/button/)
- [Button Pair](https://design.va.gov/components/button/button-pair)
- [Featured Content](https://design.va.gov/components/featured-content)
- [Pagination](https://design.va.gov/components/pagination)

## Acceptance Criteria
 - [ ] Existing V1 components on the list above are modified to pass in the uswds={false}
   - [ ] Stories
   - [ ] News releases

**Comment by xiongjaneg** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Sitewide-Facilities-639f5253e4b702a32376339e/issues/department-of-veterans-affairs/va.gov-cms/17051?planning-poker) with Zenhub @maxx1128 @eselkin

**Comment by laflannery** [comment]
@xiongjaneg I'm closing this because I audited these and there are no components on these pages at all, so we don't need to opt out of anything
