### ISSUE TITLE
Replaced VAMC detail pages that are archived are accidentally updated and published by editors

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#17052]
## Problem statement

Some older VAMC detail pages were created before specific content types were created. These were archived in favor of new pages. The page names are the same except they have 'REPLACED' in the title and URL. Unfortunately, some editors keep edit these accidentally and publish them in confusion for the newer pages.  Here's the [filtered list](https://prod.cms.va.gov/admin/content?title=replaced&type=health_care_region_detail_page&moderation_state=archived&owner=All).

Consider
- deleting the old pages
- if unable to due to retention schedules, rename the old pages to make them less likely to be confused for the new pages
- move the old pages to a section that editors don't have access to republish them

Note: Michelle is reviewing the retention schedule for any impact on this. UPDATE: Since these are exact duplicates, these don't need to be retained and can be deleted.

[Slack thread
](https://dsva.slack.com/archives/C0FQSS30V/p1706304536978539)
[Example case ](https://dsva.slack.com/archives/C0FQSS30V/p1706304034596859)

## Acceptance criteria
- [ ] Archived VAMC detail pages with '- REPLACED' in the title are deleted.

**Comment by mmiddaugh** [comment]
@xiongjaneg I confirmed that since these pages are exact replacements, there is no need to retain them. They can be removed entirely.

**Comment by xiongjaneg** [comment]
@mmiddaugh That's awesome news. Thank you! I'll get that taken care of or spin up a ticket for Drupal engineers.

**Comment by jilladams** [comment]
From scrum: need to scrub the 5 nodes to make sure we're clear on state of what's published to these VAMCs before we handle these nodes. 

| Replaced page | Proper content type? | revisions on the replaced page? | Status / next step | 
| --- | --- | --- | --- |
|[Register for care - REPLACED](https://prod.cms.va.gov/portland-health-care/register-for-care-replaced) | [Register for care](https://prod.cms.va.gov/portland-health-care/register-for-care) | [655647](https://prod.cms.va.gov/node/27069/revisions/view/655647/818109/visual_inline) -- hours, some address changes <br/> [818109](https://prod.cms.va.gov/node/27069/revisions/view/818109/818275/visual_inline) -- hours | Portland has a published Registered for care page. Revisions need to be made to that page to ensure it's aligned (can't tell if it already is.) At that point, replaced page can be deleted. | 
|[Billing and insurance - REPLACED](https://prod.cms.va.gov/memphis-health-care/billing-and-insurance-replaced) | [Billing and insurance](https://prod.cms.va.gov/memphis-health-care/billing-and-insurance) | [723568](https://prod.cms.va.gov/node/27096/revisions/view/723564/723568/visual_inline) - phone ext, hours |  Memphis has a published Billing & Insurance page. Phone number is different between the replaced detail page and live B&I page. Need editor to confirm correct data in the live page. Then, replaced page can be deleted. | 
|[Billing and insurance - REPLACED](https://prod.cms.va.gov/wilmington-health-care/billing-and-insurance-replaced) | [Billing and insurance](https://prod.cms.va.gov/wilmington-health-care/billing-and-insurance) |  [646722](https://prod.cms.va.gov/node/2715/revisions/view/646722/646729/visual_inline) - hours, phone & ext  | Wilmington has a published Billing & Insurance page. Hours and phone number differ between the replaced detail page and the live B&I page. Need editor to confirm live B&I page info is correct, then replaced page can be deleted. | 
|[Medical records office - REPLACED](https://prod.cms.va.gov/connecticut-health-care/medical-records-office-replaced) | [Medical records office](https://prod.cms.va.gov/connecticut-health-care/medical-records-office) | [655226](https://prod.cms.va.gov/node/27940/revisions/view/655226/655296/visual_inline) - No changes. | CT has a published Medical Records page. Replaced page can be deleted, & has been. | 
|[Register for care - REPLACED](https://prod.cms.va.gov/connecticut-health-care/register-for-care-replaced) | [Register for care](https://prod.cms.va.gov/connecticut-health-care/register-for-care) | [655217](https://prod.cms.va.gov/node/27932/revisions/view/655217/700717/visual_inline)  | CT has a published Registered for care page. Replaced page can be deleted, & has been. |

**Comment by jilladams** [comment]
Thread for Helpdesk re: coordinating the edits to those last 3 pages: https://dsva.slack.com/archives/CDHBKAL9W/p1707169618819629

**Comment by stefaniefgray** [comment]
This KB article needs updates to guide editors away from updating the old/replaced Top Task Page Detail Pages: https://prod.cms.va.gov/help/vamc/how-to-edit-a-vamc-top-task-detail-page

**Comment by stefaniefgray** [comment]
1. VA Portland check-in ticket: https://va-gov.atlassian.net/browse/VAHELP-7041
2. VA Memphis check-in ticket: https://va-gov.atlassian.net/browse/VAHELP-7042
3. VA Wilmington check-in ticket: https://va-gov.atlassian.net/browse/VAHELP-7043

**Comment by stefaniefgray** [comment]
From VA Wilmington:

> "Hello, 
> 
> Yes the below link has the correct information. Thanks   
> 
> https://prod.cms.va.gov/wilmington-health-care/billing-and-insurance"

**Confirmed that new version of page has correct info and old one can be removed**

**Comment by jilladams** [comment]
Wilmington has been deleted. @ian-sears not urgent, but sometime could y'all take a look at these 2 JIRA tickets and let us know if any update from the editors? 

- VA Portland check-in ticket: https://va-gov.atlassian.net/browse/VAHELP-7041
- VA Memphis check-in ticket: https://va-gov.atlassian.net/browse/VAHELP-7042

**Comment by TroyCMSSupport** [comment]
@ian-sears @jilladams - I believe this issue can be closed - any objections?

**Comment by jilladams** [comment]
@TroyCMSSupport I'm not sure - are the 2 JIRAs in my comment above yours still open?
