### ISSUE TITLE
Front end: Modify VAMC Facility template to opt out of USWDS V3 automatic upgrade 

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#17058]
## User Story or Problem Statement
On 2/16, USWDS V1 components will default to V3. V1 components that have V3 versions will be automatically upgraded unless we opt out proactively. Opting out means: modifying those existing V1 components to pass in the uswds={false}.

VAMC Health service template needs to be modified to opt out of V1 to V3 automatic upgrade.

### List of applicable components
-  Accordion: Being used on Prepare for your visit and services sections

## Acceptance Criteria
- [ ] All accordion components are modified to pass in the uswds={false}

**Comment by laflannery** [comment]
@xiongjaneg When I was going through this got missed for the opt out, I assigned @maxx1128 and @eselkin so they would at least see it but I don't know how to do planning poker for them

**Comment by laflannery** [comment]
I also have a question - Does Lovell use the same template as the standard VAMC pages? Because the Tricare switcher is an alert that we need to opt out of, Should I be adding that to **every** VAMC ticket or is that different and I should make a separate ticket for Lovell?

**Comment by eselkin** [comment]
Probably make a separate Lovell ticket. Lovell has a whole set of different templates and scripts.

**Comment by xiongjaneg** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Sitewide-Facilities-639f5253e4b702a32376339e/issues/department-of-veterans-affairs/va.gov-cms/17058?planning-poker) with Zenhub @eselkin @maxx1128
