### ISSUE TITLE
[ADD] VBA terms (batch 3) to Service taxonomy name

### ISSUE THREAD

**Issue by davidmpickett** [department-of-veterans-affairs/va.gov-cms#17060]
### Which Taxonomy is this term for?

VA services taxonomy

### Proposed term name/label

Label  | Machine Name | Health Service API ID | Notes
-- | -- | -- | -- 
[Compensation benefits for survivors](https://prod.cms.va.gov/health-care/compensation-benefits-for-survivors) | compensation-benefits-for-survivors | FamilyMemberClaimAssistance | Suggesting this as best fit for mapping the legacy Facilities API ID
[Pre-need burial planning](https://prod.cms.va.gov/health-care/pre-need-burial-planning) |  pre-need-burial-planning | PreNeedBurialPlanning | Note that this mirrors the established pattern of "Couples and family counseling" and "Toxic exposure screening"
[Transition assistance](https://prod.cms.va.gov/health-care/transition-assistance) |  transition-assistance | TransitionAssistance  

### Does this overlap with any existing term in the taxonomy?

No

### Rationale for adding this term

Follow up from https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16269

### Which products will this term impact?

VBA Regional Office

### Have stakeholders from impacted products been consulted?

Yes

### Have you drafted content for all the relevant subfields?

Some, but not all

### Acceptance Criteria

- [x] A Drupal admin from the Product team may adds the term to the taxonomy
- [x] Content for subfields is drafted in Drupal by Product team
- [x] The sharepoint document is updated with links
- [x] Terms are [sent to VBA for final approval](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17046)
- [x] Terms are [sent to CAIA for final review](https://github.com/department-of-veterans-affairs/va.gov-team/issues/74390)

**Comment by mmiddaugh** [comment]
@davidmpickett, can we please move forward with the following benefit services 
- Compensation benefits for survivors
- Pre-need burial planning 
- Transition assistance 

and hold the following with a plan to reassess as the roll-out proceeds
- Creating an account for VA.gov/Veteran profile information 
- Fiduciary services

**Comment by davidmpickett** [comment]
@mmiddaugh Okay, I split off Creating an Account & Fiduciary into their own tickets.
- #17683
- #17684

I assume that this ticket would be a priority for Sprint 1 over #16906? This is a 2-pointer so I feel comfortable committing to it.

cc @jilladams

**Comment by davidmpickett** [comment]
Label  | Notes
-- | --  
[Compensation benefits for survivors](https://prod.cms.va.gov/health-care/compensation-benefits-for-survivors) | Note
[Pre-need burial planning](https://prod.cms.va.gov/health-care/pre-need-burial-planning) |  Note that this mirrors the established pattern of "Couples and family counseling" and "Toxic exposure screening"
[Transition assistance](https://prod.cms.va.gov/health-care/transition-assistance) |  Note that I am using the description that was copy edited by CAIA. There was a slightly different description suggested in the RO feedback tab, but all that really changed was the style of the sentence, not the content. Maintaining the CAIA version for consistency.

**Comment by mmiddaugh** [comment]
@davidmpickett 
- Compensation benefits for survivors: Linking to the root of the Family Member hub makes sense to me given more than one type of benefit might be applicable. 
- Pre-need burial planning
  - Current VBA description: "We can help you plan a burial in a VA national cemetery."
  - I found a copy-edited description in the VBA Service taxonomy sheet and suggest we use part of it to clarify that this service is for advance planning, rather time of need planning. Such as..."We can help you plan a burial in a VA national cemetery and make the burial planning process easier for your family members in their time of need." Thoughts?
- Transition assistance: I agree with using CAIA's version.

**Comment by davidmpickett** [comment]
> * Pre-need burial planning
>   
>   * Current VBA description: "We can help you plan a burial in a VA national cemetery."
>   * I found a copy-edited description in the VBA Service taxonomy sheet and suggest we use part of it to clarify that this service is for advance planning, rather time of need planning. Such as..."We can help you plan a burial in a VA national cemetery and make the burial planning process easier for your family members in their time of need." Thoughts?

Good catch. I was using a static copy of the spreadsheet and it didn't have that update. That was actually a change I suggested to expand on what was copy edited by CAIA. However, I have taken this language verbatim from the Pre-need page, so I think we can consider it copy edited enough for this pass (while still giving them the final review opportunity)

**Comment by davidmpickett** [comment]
@mmiddaugh FYI I tweaked the pre-need description a hair "We can help you apply in advance to be buried in a VA national cemetery. This can help make the burial planning process easier for your family members in their time of need."

**Comment by davidmpickett** [comment]
Related tickets updated
