### ISSUE TITLE
Front end: Modify VAMC Lovell templates to opt out of USWDS V3 automatic upgrade

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#17065]
## User Story or Problem Statement
On 2/16, USWDS V1 components will default to V3. V1 components that have V3 versions will be automatically upgraded unless we opt out proactively. Opting out means: modifying those existing V1 components to pass in the uswds={false}.

VAMC Lovell templates needs to be modified to opt out of V1 to V3 automatic upgrade.

### List of applicable components
- Accordion
- Alert
  - NOTE: This is used for the Tricare switcher so it is used on multiple pages/templates
- Button

## Acceptance Criteria
- [x] All Accordion components are modified to pass in the uswds={false}
- [x] All Alert components are modified to pass in the uswds={false}
- [x] All Button components are modified to pass in the uswds={false}

**Comment by laflannery** [comment]
@eselkin and @maxx1128 I created a new opt out ticket for Lovell per direction from Eli CC: @xiongjaneg

**Comment by xiongjaneg** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Sitewide-Facilities-639f5253e4b702a32376339e/issues/department-of-veterans-affairs/va.gov-cms/17065?planning-poker) with Zenhub @eselkin @maxx1128

**Comment by eselkin** [comment]
checked, done
