### ISSUE TITLE
PW: [EPIC] [V1 & 3 Components] Implement available components in PW products where components aren't currently used

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-cms#17078]
## Status

**[2024-03-013]** Good progress made; 7 completed out of 20

**[2024-02-29]** Out of 20 tickets:
- 3 Completed
- 1 Blocked
- 16 are in Refined and ready to be worked on

## Description

The Design team is releasing a Typography update in Mid-April, which means that the PW team needs to upgrade any of our products where components aren't currently being using, but a V1 or V3 component is available.

- Design Team's Typograph [epic](https://github.com/department-of-veterans-affairs/va.gov-team/issues/75641)
- Discovery work is on Confluence. I've asked (3/6/2024) if they can export to a PDF.

If the updates aren't made prior to the Typography update, there's a chance that Veteran-facing issues may occur.

### User story

**AS A** PO/PM for Public Websites products
**I WANT** to implement available V1 and V3 components in features & products currently under Public Websites management where components aren't currently being used
**SO THAT** all PW products are in alignment with the current component version.
**AND** Veterans and other users have a consistent experience within VA.gov

## Acceptance criteria

- [ ] See the individual stories for AC

**Comment by laflannery** [comment]
Adding important applicable deadlines:


- Typography update (which has the potential to possibly break elements that currently aren't using components) is happening most likely "next month". Matt Dingee has said there will be a more formal announcement when there is more info to share but this is currently what we know

[Slack thread for reference](https://dsva.slack.com/archives/C03LFSPGV16/p1707759183364599)

**Comment by FranECross** [comment]
@chriskim2311 @randimays I've added a link in the Description to the Design Team's epic (Thanks @jilladams ).

**Comment by jilladams** [comment]
Closing. The remaining work is in its own epic (#17557 )
