### ISSUE TITLE
Review Draft Vet Center runbook document

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-cms#17079]
## Description
We are expecting three new Vet Centers and six new Vet Center Outstations in the coming months. These new locations may require that our runbooks are updated to reflect the particular scenarios. 
- Only one of the new Vet Centers will be an entirely new location. The other two locations are currently Outstations which will be promoted to main Vet Centers.
- Most of the new Outstations are in locations currently served by CAPs - which may or may not continue to be listed as CAP locations. 

## Tasks
- Review and respond to this [runbook draft document in Sharepoint](https://dvagov-my.sharepoint.com/:w:/r/personal/suzanne_middaugh_va_gov/_layouts/15/Doc.aspx?sourcedoc=%7B673F552E-056C-48EF-BE72-5E4B6DF3DFBC%7D&file=Draft%20Vet%20Center%20runbook.docx&action=default&mobileredirect=true) which is a version of the existing runbook with suggested changes and questions in the comments

## Acceptance criteria
- [ ] Runbooks are updated as needed to support these forthcoming facility changes

**Comment by Becapa** [comment]
Looks like I don't have access to Sharepoint. I tried to access through CAG with my VA email.

**Comment by xiongjaneg** [comment]
@mmiddaugh Would you take a look at the Sharepoint doc permissions? Neither Michael nor I can access it, even on the VA network. It's not prompting for PIV login and email login doesn't seem to work. Thanks!

**Comment by mmiddaugh** [comment]
Sharepoint settings changed - apologies for the brick wall. Please let me know if you have any more trouble accessing the doc. 
(You'll need to use with your VA email)

**Comment by Becapa** [comment]
I added some comments to the doc and answered a couple of questions that I _think_ I knew the answers to.

**Comment by omahane** [comment]
I am a little confused by this ticket. We have runbooks for a couple of these scenarios:
- https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/.github/ISSUE_TEMPLATE/runbook-vet-center-outstation-to-vet-center.md
- https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/.github/ISSUE_TEMPLATE/runbook-vet-center-cap-to-outstation.md
Are we collapsing them all into the [new Vet Center runbook](https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/.github/ISSUE_TEMPLATE/runbook-vet-center-new.md)?

**Comment by jilladams** [comment]
@mmiddaugh flagging Christian's question above in case that's still an open issue
> We have runbooks for a couple of these scenarios: Are we collapsing them all into the [new Vet Center runbook](https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/.github/ISSUE_TEMPLATE/runbook-vet-center-new.md)?

**Comment by jilladams** [comment]
Chatted with Michelle, removed from Sprint 105 reporting as next steps sit with her.

**Comment by omahane** [comment]
Removing myself from it for now.

**Comment by mmiddaugh** [comment]
Closing with Update runbook-vet-center-new.md #17689
