### ISSUE TITLE
FE: Build Federal Header in vets-website

### ISSUE THREAD

**Issue by randimays** [department-of-veterans-affairs/va.gov-cms#17072]
## Description
Ahead of the final rounds of Federal Header/Footer research, we are beginning the build of the new designs in vets-website. This ticket is specifically for the **Header**, and also includes accessibility changes indicated in the CodePen prototype code.

[Header Codepen](https://cdpn.io/pen/PoVggmp/cd965bc015c83de0302f0f72dbc960d0)
[Full Codepen Prototype](https://codepen.io/Sitewide-Team/live/eYxooWQ/0628a3dc13a4678d0a8249c64342f634) for reference

Figma designs are below. **These mockups are the finalized designs** and may vary slightly from the CodePen prototype used in research.
- [Desktop header](https://www.figma.com/file/l35ykhDl0U885wSbmrc7Gc/USA-header-footer-VA?type=design&node-id=0%3A2&mode=design&t=e7tv1g0fDiXsCnFL-1)
- [Mobile header](https://www.figma.com/file/l35ykhDl0U885wSbmrc7Gc/USA-header-footer-VA?type=design&node-id=456%3A5970&mode=design&t=1weD9RILp4mAeAZx-1)

**USA banner Flipper:**
_hides USA logo as it may be necessary as we transition_

- [Header - Flipper](https://www.figma.com/file/l35ykhDl0U885wSbmrc7Gc/USA-header-footer-VA?type=design&node-id=11%3A4286&mode=design&t=e7tv1g0fDiXsCnFL-1) to include collapsed and expanded on desktop and mobile
- [Footer Flipper](https://www.figma.com/file/l35ykhDl0U885wSbmrc7Gc/USA-header-footer-VA?type=design&node-id=11%3A4404&mode=design&t=e7tv1g0fDiXsCnFL-1) to include desktop and mobile 

### User story

**AS A** Veteran, their family member, caregiver, or survivor
**I WANT** to be able to easily understand and navigate the VA.gov header with and without tools that aid accessibility
**SO THAT** I'm not frustrated, can find what I need in the least amount of time, and am able to understand that this is a government website

### Engineering notes / background
In order to keep any of this in-progress code from being accessible/visible in production, we can create a long-living Tugboat instance targeting the WIP vets-website branch.

### Quality / testing notes
- Unit and e2e tests must be adjusted to fit any new header HTML structure or dynamic data
- Testing the header on mobile with this WIP branch will require running vets-website locally, spinning up an ngrok server, and using the ngrok link to review. Tugboat does not work on mobile devices (for lack of SOCKS).

## Acceptance criteria
Definition of "done" for this ticket: a working Tugboat with the WIP header. **No deploys to staging or production**❗

- [ ] Confirm status of auth menu design with @aklausmeier before building

 - [ ] USA Logo should be behind a flipper, or some type of feature flag so we can do a content toggle between new USA branding and the existing official website of the US government text. The strip should be white in both cases. 
 - [ ] Injected Header is not updated with new designs
 - [ ] Injected Header is not regressed
 - [ ] [Injected Header documentation](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/proxy-rewrite) is updated to reflect how files work / state of code after the split
 - [ ] Desktop header created with all header data from Drupal
 - [ ] Mobile header created with all header data from Drupal
 - [ ] Accessibility review
 - [ ] Design review by Amanda K.
 - [ ] Design review by Dave C.

**Comment by jilladams** [comment]
Noting: per this thread, https://dsva.slack.com/archives/C52CL1PKQ/p1706630474348729, @aklausmeier may be making design changes to the auth menu. When we get rolling on this ticket, we should first confirm with Amanda where that's at, and likely leave the auth menu changes for last so they can settle before we build. Adding to ACs. (cc @FranECross )

**Comment by aklausmeier** [comment]
@randimays Ticket has been updated with revised Figma file links. This Figma file has updated auth menu design, different than CodePen prototype used in research.

**Comment by FranECross** [comment]
This project is placed on hold... the OFCIO wants to extend the research/usability study across a broader spectrum than only VA.gov. Undetermined at this time which team or who will do the actual work. Moving to Blocked.

**Comment by FranECross** [comment]
Per Dave Conlon, the Federal Header/Footer improvement effort has been closed by the Whitehouse / 18f. All related tickets may be closed.
