### ISSUE TITLE
Refactor deploy to deploy last commit that passed testing.

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#1707]
## Description
Our current deploy process requires the tip of master to pass tests before a deployment to production can proceed.   This creates a window that is rougly an hour where we can not merge anything or it will prevent the daily deploy.

It would be nice if the daily deployment could look to see what the last commit was to pass testing and deploy that (if it is beyond the last deployed tag) rather than requiring the last commit to master to pass.  This would allow us to keep merging code at any time and not cause the delay in our deploy while it waits up to 45 minutes for the tip to pass tests.

Benefits:
* merged could happen at any time without breaking deploy.
* code that has passed testing can go out and not be blocked by a last minute change to a markdown file.
* code goes out at a more consistent time (right now our deploys float by up top 45 minutes)

Drawbacks:
* the tip of master may not always get deployed.

## Acceptance Criteria
* Testable_Outcome_X
* Testable_Outcome_Y
* Testable_Outcome_Z

## Labels
- [/] Issue type (red) (defaults to task)
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [ ] CMS objective (orange)
- [ ] CMS-supported product (black)

**Comment by ElijahLynn** [comment]
This is done now. @olivereri can you cross link the issue you fixed this in?
