### ISSUE TITLE
Facilities Draft Sprint 104 Plan

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#17076]
## Schedule Notes
- Alexis out 2/14
- Jill out 2/12-2/16
- Jane out 2/16
- Christian out 2/16 to 2/21
- Washington's Birthday/Presidents Day
  -  Friends holiday
  - Not an A1M holiday
  - A6 holiday
  - Not a Civic Actions holiday
- Design system update by 4/19

## Sprint Priorities 🎯 
At the end of this sprint, what do we want to have accomplished/delivered?
- #16825 

Tickets for top priority:
- 🎯 UX Design: #17169 
- 🎯 UX Research: #17220
- 🎯 Drupal: #14083
- 🎯 FE: #14933 

### UX
- Research: #17155 in progress
- Research: #17282 
- Design: #16810 
- Design: #17169 
- Design: #15935 
- Content/Drupal/FE: #15752 carrying over and needs cross-discipline collaboration

### Drupal
- VBA/VAMC: #17114 in progress
- VAMC: #16233 in progress
- Vet Center: #17177 
- All products: #14083 
- Defect: #14667 
- Tech debt: #14136 

### Front end
- VBA: #16652 in progress
- VBA/VAMC: #15959 in progress
- USWDS V3: #17103 
- VBA: #14933 
- VBA: #14929 
- VBA: #16311

**Comment by mmiddaugh** [comment]
Front end: Vet Center unpublished services should not be showing on VA.gov #16362

**Comment by xiongjaneg** [comment]
For components using classes but not a link component (may not have a V3 component), how will these be affected?

Not all V1 components have a V3 equivalent. In that case, they may continue to be excluded from this update.

**Comment by swirtSJW** [comment]
@xiongjaneg I created this ticket https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17241 which is a blocker for service location launch.

**Comment by xiongjaneg** [comment]
@swirtSJW You're a mindreader. I was just looking for this info!
