### ISSUE TITLE
[UPDATE] VR&E in VA service taxonomy

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-cms#17080]
### Which Taxonomy is this term for?

VA services taxonomy

### Link to existing term

https://prod.cms.va.gov/health-care/vocational-rehabilitation-and-employment-programs

### Rationale for updating this term

The name for VA’s Vocational Rehabilitation and Employment (VR&E) service was changed in October 2020 to better reflect the needs of veterans. VR&E now stands for Veteran Readiness and Employment.

Note: this is a name change only. Content in the other fields related to this service have not changed. 
The related service type for VA benefit facility searches in Facility Locator has already been updated. 

### Which products will this term impact?

VAMCs, VBA Regional Office

### Have stakeholders from impacted products been consulted?

Yes

### Have you drafted content for all the relevant subfields?

Yes

### Acceptance Criteria
- [x] Change the service taxonomy name
- [x] Update the URL alias for the taxonomy to reflect the new name
- [x] Bulk resave system services to pick up name change (filtered for the old name)
- [x] Bulk Update alias for all system services (filtered for new name)
 - [x] Bulk update facility services (filtered for the old name)
- [x] Bulk update alias for all facility services (filtered for new name)

**Comment by xiongjaneg** [comment]
@davidmpickett This is newly created. We can discuss at our 1:1.

**Comment by davidmpickett** [comment]
If term is part of VA Service Taxonomy & the term name changes:
      - [ ] Bulk resave system services to pick up name change (filtered for the old name)
      - [ ] Bulk Update alias for all system services (filtered for new name)
      - [ ] Bulk update facility services (filtered for the old name)
      - [ ] Bulk update alias for all facility services (filtered for new name)

**Comment by xiongjaneg** [comment]
The service taxonomy term drives URL aliases, changes enact at service level, cascades down to facility level. We lock in aliases so they don't float willy nilly. After initial creation, the alias is locked in until and admin can change alias intentionally.

**Comment by xiongjaneg** [comment]
This is all in views and then verified.

**Comment by xiongjaneg** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Sitewide-Facilities-639f5253e4b702a32376339e/issues/department-of-veterans-affairs/va.gov-cms/17080?planning-poker) with Zenhub @omahane @Becapa

**Comment by xiongjaneg** [comment]
verified in Vet Center and VAMC Facility health service content types
