### ISSUE TITLE
Make periodic tasks to run every 15 minutes

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#1708]
Originally our periodic tasks triggered by Jenkins were supposed to run every 15 min, but we had to opt for them to run every hour because the jobs were taking so long.   Now that they run in only a few minutes, it would be nice to make them run every 15 minutes.

**Comment by olivereri** [comment]
To create a local Jenkins environment to test the seed job, I followed these steps with slight modifications and additions:

## Steps to follow:
https://github.com/department-of-veterans-affairs/devops/blob/996afdfeabf8eca4555590b1e57c95436872d5aa/docs/Testing%20Jenkins%20Seed%20Jobs.md

## Other plugins that must be installed:
https://plugins.jenkins.io/favorite 2.3.2
https://plugins.jenkins.io/throttle-concurrents 2.0.2

## Required Environment Variables
DSVA_JENKINS_ENV = prod
DSVA_SCHEDULE_ENABLED = true
REQUESTS_CA_BUNDLE = /etc/ssl/certs/ca-bundle.trust.crt
