### ISSUE TITLE
Draft VBA RO editor-facing research conversation guide

### ISSUE THREAD

**Issue by ALogsdon3** [department-of-veterans-affairs/va.gov-cms#17096]
### User story
**AS A** Researcher
**I WANT** to document the details for conducting VBA RO editor-facing research
**SO THAT** the research will achieve the stated goals and answer the research questions

## Suggested workflow/tasks:
- [x] Brainstorm potential questions
- [x] Create initial draft of conversation guide
- [x] Align conversation guide with CMS editor experience
- [x] [Align conversation guide with research questions and hypotheses](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1697569400651/92298ea4aa3b0e64d71b6305a7d95e56261f4cf1?wid=0-1706888652569) 
- [x] Solicit feedback from Sitewide UX Lead, PO, and team members
- [x] Post on github in project research folder for final approval 

## Acceptance Criteria
- [x] Guide drafted
- [x] Conversation guide posted on github in project research folder
- [x] Feedback solicited from Sitewide UX Lead, PO, and team members
- [x] Guide revised based on feedback
- [x] Final approval obtained from Sitewide UX Lead

**Comment by xiongjaneg** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Sitewide-Facilities-639f5253e4b702a32376339e/issues/department-of-veterans-affairs/va.gov-cms/17096?planning-poker) with Zenhub @ALogsdon3
