### ISSUE TITLE
Update VAMC Lovell with components (as needed) (v3)

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#17108]
**Be mindful of timing and 3/7 Cerner cutover for merging this change. Don't break Lovell.**

## Description
VAMC Lovell needs to be updated to have the most updated DS components. This should be updated with the other VAMC updates however we do want to make sure that nothing breaks and account for any separate templates/updates that may need be needed. This ticket can be reviewed after all other VAMC updates are completed and if it is determined if additional work is needed that can be outlined here.

### V1 components that need to be upgraded (Actionable)

1. Alert
   - The Tricare switcher is using the v1 alert component and will need to be upgraded to v3
   - _Consider related issue: Updated Lovell switch alert type should not appear on the page table of contents #15569_

## Acceptance Criteria
- [x] Alert component has been upgraded to v3
- [x] Update and run existing test(s).
- [x] If additional tests are needed, stub a ticket to note this for future work.
- [ ] Presentation is verified the same across all supported browsers on Mac & Win
    - [ ] Chrome 
    - [ ] Firefox
    - [ ] Safari
    - [ ] Edge
    - [ ] Android
    - [ ] iOS
- [ ] Requires accessibility review

**Comment by maxx1128** [comment]
This is just one component but also Lovell, so I estimate this to be a 2.

**Comment by mmiddaugh** [comment]
Related: Updated Lovell switch alert type should not appear on the page table of contents #15569

**Comment by aklausmeier** [comment]
@laflannery 

> Consider related issue: Updated Lovell switch alert type should not appear on the page table of contents [#15569](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15569)

Is this an accessibility bug we need to share with design system team or just a Lovell thing?

**Comment by laflannery** [comment]
@aklausmeier I wouldn't necessarily call this a bug and/or an accessibility issue. To be perfectly honestly I'm not thrilled with the choice of using this alert in this location, the H1 should really be the first heading on the page and because of the alert it's not any more. I had asked [to see if we can get some data](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15569#issuecomment-1932991484) to find out if this was actually solving the problem and go from there

**Comment by jilladams** [comment]
Due to #17807 popping up, where adoption of components ran into some browser-specific styling issues, I've added ACs here to cover cross-browser verification.

**Comment by laflannery** [comment]
Confirmed on prod:
![Screenshot 2024-04-16 at 5 26 25 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/106678594/06b20f9a-c997-4e4b-8191-0e2a7b87e589)

**Comment by jilladams** [comment]
WOO! DONE. CLosing this ticket, and closing epic!
