### ISSUE TITLE
Front end: Update VBA operating status to use component

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#17103]
## User Story or Problem Statement
We should use a component here. Follow the Vet Center pattern.

~~Breadcrumbs~~
~~These are currently using the v1 component but they should be using [the v3 component](https://design.va.gov/components/breadcrumbs#examples---v3)~~

- Alert - Expandable
   - Right now Operating status alert is using the VAMC pattern of linking to a 404 Operating Status page. It should be a [Alert-expandable component](https://design.va.gov/components/alert-expandable) and not link to a separate page.

## Acceptance criteria
- [x] Operating status alert uses alert-expandable-component
- [x] Accessibility is reviewed (tag Laura in PR)

**Comment by xiongjaneg** [comment]
From Laura: Are V3 breadcrumbs possible?
From Eli: All breadcrumbs use the liquid component. But if we change this in VBA, this should change in all products. In the V3 component now, they're switching to using the React router component changer so the click doesn't take you to the other page. It's a major upgrade to the V3 breadcrumb, so it may cause issues.

**Comment by xiongjaneg** [comment]
@xiongjaneg remove breadcrumbs from this issue and make it cross-platform. Tag also Public Websites in case it has impact on theirs. Tag Laura to add context to that ticket.

**Comment by xiongjaneg** [comment]
closed as completed, Laura verified on prod

**Comment by laflannery** [comment]
@xiongjaneg The comment above was referring to a different ticket. I looked in the current vet-website code and confirmed that updating the Operating display still need to occur

**Comment by xiongjaneg** [comment]
Oops, thanks, getting this in first thing next sprint

**Comment by xiongjaneg** [comment]
This may need a new component or can build off an existing one.

**Comment by jilladams** [comment]
a11y verified in PR, and deployed. Closing.
