### ISSUE TITLE
[Aging Content Notifications] Install ECA Drupal modules

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-cms#17115]
## Description

**This is the first step in creating the Aging Content Notification framework**

Install the latest stable versions of the following Drupal modules:
[ECA](https://www.drupal.org/project/eca)
ECA UI (submodule of ECA)
ECA Views (submodule of ECA)
[ECA Classic Modeller](https://www.drupal.org/project/eca_cm)

### Quality / testing notes
Visit the modules page (eg: https://staging.cms.va.gov/admin/modules) to verify modules are installed.

## Acceptance criteria
- [ ] ECA is installed
- [ ] ECA UI is installed
- [ ] ECA Views is installed
- [ ] ECA Classic is installed

**Comment by FranECross** [comment]
Per Daniel, this ticket just needs some wordsmithing, after we hear back from the review of the Architecture document.

**Comment by jilladams** [comment]
@dsasser tried to verify this in prod, may need your help.  https://prod.cms.va.gov/admin/config/workflow/eca doesn't load anything, and I don't see the ECA modules listed here: https://prod.cms.va.gov/admin/modules.  Maybe need to flush caches?

**Comment by dsasser** [comment]
@jilladams 
This is not yet on production.

Due to the [staging CMS deploy issues](https://dsva.slack.com/archives/CT4GZBM8F/p1708701168438119), no CMS code has gone out since v0.0.937 (February 21st).

**Comment by jilladams** [comment]
oofta. Thanks for clarifying that.

**Comment by dsasser** [comment]
Confirmed on prod:

![Screenshot 2024-03-04 at 8 39 46 AM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/221539/8d32a627-d204-4836-ba18-24995aed4d27)
