### ISSUE TITLE
[Aging Content Notifications] Create Views Result Condition Plugin for ECA

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-cms#17116]
## Description

*This story is the second step in creating the Aging Content Notifications framework.*

In order to use ECA for the Aging Content Notifications framework, we need a viable "condition" that ensures we are firing the appropriate action only when there is content to process.

Create an ECA Condition plugin that will return TRUE if a View has 1 or more results. The condition form should allow the admin to select from a list of Views which have ECA Displays (the Display type we are creating in this ticket as well)

Create a Views Display Plugin for ECA. The new Condition will allow the admin to select only Views with Displays of this type.

### User story

**AS THE** engineer working on Aging Content Notifications
**I WANT** to create the Views Result Condition Plugin for ECA
**SO THAT** I can build upon the framework for aging content notifications

#### Condition Plugin

Input of View + Display should be similar to 'View used to select the entities' field on entity reference field settings forms. It should allow Displays only of the type we are creating in this issue. eg:
![Screenshot 2024-02-14 at 9 51 11 AM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/221539/755efcc3-070e-47e5-b80d-d41f0243af69)

#### Views Display Plugin

- Subclass of DefaultDisplay.
- Set default row display to 'fields'

### Quality / testing notes
Testing the Condition will require setting up a View with a Display of type "ECA Result" (or whatever we end up calling it), creating a ECA Model with the new Condition that leverages the new View, And running the trigger (cron, probably) that fires the model->condition->action sequence, and verifying the result (a Drupal message, or Drupal log, is a likely candidate)

## Acceptance criteria

- [ ] ECA Condition exists
- [ ] Views Display Plugin exists
- [ ] An ECA Model exists which demonstrates the use of the Condition and Display plugins.
- [ ] Tests exist

**Comment by FranECross** [comment]
Per Daniel, this ticket just needs some wordsmithing, after we hear back from the review of the Architecture document.

**Comment by dsasser** [comment]
## Status Update 2/27/24

The plugin has been created. I am currently writing tests to verify the functionality, and I am hopeful to wrap that up before sprint close tomorrow.

**Comment by dsasser** [comment]
Confirmed on prod:

![Screenshot 2024-03-04 at 8 40 35 AM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/221539/54d4a207-9baf-4387-8185-424b8c2d9cf7)
