### ISSUE TITLE
Request to have CMS Team review an Architecture Plan for the Public Websites Team

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-cms#17120]
As a Sitewide Public Websites team member, I want to have an async review of the Aging Content Notifications Architecture Plan  with the intent to either have it approved as is, or approved with stated changes.

The requested deadline is for approval/feedback to be provided by February 12th, if possible

Please let us know if this is possible and an estimated date of completion.

Project: Aging Content Notification Framework
- [Architecture Plan for review](https://github.com/department-of-veterans-affairs/va.gov-cms/files/14090309/VACMS-16885.Architecture.-.Scheduled.aging.Content.Notifications.Framework.pdf)
- [Initiative](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/governance/aging-content-notifications/initiatives/2024-specify-timeframes/Initiative-1-mvp-aging-content-new-framework.md)
- [Epic](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15504)
- PW Engineer: Daniel Sasser
- PW Product Manager: Fran Cross
- PW Delivery Manager: Jill Adams
- PW PO: Dave Conlon

**Comment by FranECross** [comment]
FYSA 👉🏼 @maortiz-27-80 @EWashb @davidconlon @jilladams @dsasser

**Comment by maortiz-27-80** [comment]
FYSA @michelle-dooley and @gracekretschmer-metrostar .  @BerniXiongA6 will walk you through our ticket triaging process for CMS.  cc: @EWashb

**Comment by FranECross** [comment]
@EWashb Yes, thanks. Apologies for not specifying that. I'll update the description... Happy to also schedule a meeting as necessary if there are questions for @dsasser . cc @jilladams

**Comment by EWashb** [comment]
thanks. The current CMS Team is on their way out, but I will try to review this before the end of the week.

**Comment by EWashb** [comment]
Here are a couple of follow-up questions that weren't immediately clear to me when I read the plan:
1. Are you proposing building custom code on top of the ECA module, or is the Views query only customized after the ECA installation?
2. Emails will solely be isolated to the person who created the banner to begin with?
3. To confirm, does this implementation impact the current outdated content emails timed on the "last touched by an editor" field?
4. Do you have the content ready for the emails yet?

@FranECross @jilladams

**Comment by dsasser** [comment]
> Here are a couple of follow-up questions that weren't immediately clear to me when I read the plan:
> 
> 1. Are you proposing building custom code on top of the ECA module, or is the Views query only customized after the ECA installation?

Custom code will come in the form of two plugins: an ECA Condition plugin, and a core Action plugin. The Condition plugin will require the ECA module to be installed, but the Action plugin will not since ECA leverages core Actions.

> 2. Emails will solely be isolated to the person who created the banner to begin with?

When setting up the Action, email recipients will be set using a field which supports tokens (getting a value from any field on a node, for instance) or hard-coded (always using a set recipient) values.

> 3. To confirm, does this implementation impact the current outdated content emails timed on the "last touched by an editor" field?

No impact at all to the existing notification implementations or the last edited field--the current Outdated Content notifications can continue to operate untouched, or can be moved into the new framework if that becomes a priority.

> 4. Do you have the content ready for the emails yet?

We plan to use the same template as the Outdated Content notifications, but the body of the email content hasn't yet been flushed out.

**Comment by EWashb** [comment]
I see no issues from the CMS Team perspective. I look forward to hearing more about your insights and feedback as you implement.

**Comment by FranECross** [comment]
Thanks so much, @EWashb . FYI @dsasser ...
