### ISSUE TITLE
Document Vets API endpoints in Swagger

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-cms#17129]
## Description
Teams which rely on the current VetsAPI for facility names, location data, and/or service information and for those which hope to leverage the additional data available in Lighthouse v1 need to be aware that 
- an endpoint integrated with Lighthouse V1 (which shipped in August 2023) is now available
- V0 will remain available to maintain services while teams implement V1
- we intend to deprecate v0 in collaboration with Lighthouse's plan to sunset support on June 1, 2024

Per Platform, all endpoints exposed through Vets-API must be thoroughly documented with Swagger to provide information for engineers wishing to create an independent integration with our service. The documentation will also serve as the starting point for final review of the integration. 

This [Platform documentation](https://depo-platform-documentation.scrollhelp.site/developer-docs/documentation) provides detailed instructions and expectations. 
Example: [Decision Reviews API](https://github.com/department-of-veterans-affairs/vets-api/blob/master/modules/appeals_api/app/swagger/decision_reviews/v2/api_description.md)

## Tasks
- Consistent with the Platform documentation and example above, define the Swagger document(s) for the new Facilities endpoint and include the following details, at a minimum
   - A thorough and understandable summary of the endpoint
   - All input parameters
   - All possible success and error responses.
- Include the documented class in the SWAGGERED_DOCUMENTS list
- Update existing documentation to be complete and accurate, as needed

## Acceptance criteria
Swagger documentation consistent with Platform expectations exists for
- [ ] Existing v0 Facilities endpoint
- [ ] New Facilities v1 endpoint

**Comment by xiongjaneg** [comment]
Lighthouse may have the vast majority of this documentation in Swagger, so we might point to their documentation and supplement it with our specific documentation.

**Comment by xiongjaneg** [comment]
This is blocked until we do the new work because Swagger documentation needs to be created to tell them what the endpoint is.

**Comment by jilladams** [comment]
IIR completed this work under the following epic: https://github.com/department-of-veterans-affairs/va-iir/issues/540

Swagger ticket: https://github.com/department-of-veterans-affairs/va-iir/issues/601
