### ISSUE TITLE
Update service content types post-Service location migration

### ISSUE THREAD

**Issue by omahane** [department-of-veterans-affairs/va.gov-cms#17142]
## User Story or Problem Statement
As an editor, I want to have a clear interface for editing and reviewing services I create or edit.

## Acceptance Criteria
- [x] VAMC Facility Health Service fields no longer in use are hidden
  - [x] Appointment intro text
  - [x] Appointment lead-in text
  - [x] Are walkins accepted?
  - [x] Is online scheduling available for this service?
  - [x] Phone numbers for appointments
- [x] node:view displays for the following content types mirror the node:edit (Manage form) displays
  - [x] Service Region
  - [x] VAMC Facility Health Service
  - [x] VAMC Facility Non-clinical Service
  - [x] VBA Facility Health Service
- [x] Adjust any tests as needed

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [ ] `Public Websites`
- [x] `Facilities`
- [ ] `User support`

**Comment by xiongjaneg** [comment]
From Christian: Testing paragraphs is very hard. This ticket may not be the appropriate one for testing, but testing will need to be done in another ticket in this launch sequence. For example, where else is service location being tested and the paragraphs it relies on are being tested.

**Comment by xiongjaneg** [comment]
@xiongjaneg check for testing ticket

**Comment by swirtSJW** [comment]
PR should be made against the existing branch integration-service-location.
