### ISSUE TITLE
Prep for VBA RO editor research

### ISSUE THREAD

**Issue by ALogsdon3** [department-of-veterans-affairs/va.gov-cms#17155]
### User story
**AS A** Researcher
**I WANT** to complete all the details for setting up VBA RO editor research
**SO THAT** the research will happen successfully

### Finalize research deliverables
- [x] Update research plan and conversation guide with any timeline or protocol tweaks, including...
- [x] Consult with the CMS Platform Team on any requirements or limitations for participant recruiting (including PRA clarifications)

### Observer scheduling
- [x] Make [signup sheet for observers](https://dvagov-my.sharepoint.com/:x:/g/personal/alexis_logsdon_va_gov/ETFWAN6gCqVDo1v83ajjvd0Bu2uEHDYtdfF7Ts0CxTE3xQ?e=sBMta1), and share with team, stakeholders to sign up 
- [x] Create placeholder Google calendar events to block research session time slots  
- [x] Create research and debrief session events with Zoom links in Google calendar and invite observers

### Recruitment / scheduling sessions 
 - [x] Create Bookings time slots for participants to schedule sessions
 - [x] Recruit participants during Drupal editor training sessions (Sprint 103: 2/6/24)
 - [x] Update Outlook invites with Zoom link (see Observer scheduling above) and follow up with participants to make sure they attend sessions with work to complete

### Observer scheduling
- [x] Create research and debrief session events with Zoom links in Google calendar and invite observers

### Recruitment / scheduling sessions (Sprint 104)
 - [x] Update Outlook calendar with any additional unavailable times (block them on calendar so they don't show up on Bookings)
 - [x] Recruit participants during Drupal editor training sessions (Sprint 104: 2/20/24)
 - [x] Update Outlook invites with Zoom link (see Observer scheduling above) and follow up with participants to make sure they attend sessions with work to complete

### Notetaking prep
- [x] Identify a member of the Facilities team who will serve as official notetaker for each time slot. 
 
### Observer scheduling
- [ ] Create research and debrief session events with Zoom links in Google calendar and invite observers

### Recruitment / scheduling sessions (Sprint 104)
 - [ ] Update Outlook calendar with any additional unavailable times (block them on calendar so they don't show up on Bookings)
 - [ ] Recruit participants during Drupal editor training sessions (Sprint 105: 3/5/24)
 - [ ] Update Outlook invites with Zoom link (see Observer scheduling above) and follow up with participants to make sure they attend sessions with work to complete

### Notetaking prep
- [ ] Identify a member of the Facilities team who will serve as official notetaker for each time slot. 
 
## Acceptance Criteria -- Sprint 103
- [x] Research plan and conversation guide have final approvals
- [x] Participants for following sprint have been recruited and scheduled 

## Acceptance Criteria -- Sprint 104
- [x] The moderator(s), notetaker(s), and observer(s) have been invited to research sessions and daily debriefs
- [x] Participants for following sprint have been recruited and scheduled 
- [x] All preparation done before the first day of research sessions

**Comment by ALogsdon3** [comment]
@xiongjaneg I updated this ticket to reflect completed ACs for this sprint and to better capture what will need to be done next sprint (and all following sprints that we conduct research sessions.

**Comment by ALogsdon3** [comment]
@xiongjaneg I updated this ticket with tasks and ACs for next sprint. All ACs for sprint 104 have been completed.

**Comment by ALogsdon3** [comment]
@jilladams do you think we should give this ticket the same treatment as #17220? Aka, close it and spin up another if necessary?

**Comment by jilladams** [comment]
Per sprint planning discussion: we will spin up a small ticket per editor sign up to track both prep and conducting sessions. Closing this high level ticket.
