### ISSUE TITLE
Spike: Breadcrumbs for content-build and impact of USWDS V3 component

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#17162]
## User Story or Problem Statement
Breadcrumbs within content-build need to be updated to use the v3 component, they are currently using no component. The way the breadcrumbs are implemented, when they are updated it will impact all of content-build at once. That means both Facilities and Public Websites products will be impacted and we will want to make sure we plan for extensive QA.

### Timeline information
There is an automatic upgrade for all v1 to v3 component scheduled for 2/16 and a deprecation of all v1 components scheduled for 4/19. However, because content build is not using a component at all these two dates do not directly impact this.

However, there is another update coming regarding typography updates and because we are not using the components, there is potential for issues here. The only information we have on this typography change is "sometime next month".

### Additional context
Just for reference, so we know we have it documented, there are some instances of vets-website breadcrumbs that do use v1 or v3 breadcrumbs but those do not fall into the scope of this ticket:
- **Facilities:** Facility locator breadcrumbs have been opted out of the 2/16 auto-migration and will need to be manually updated to v3 by 4/19. Documented in [this ticket](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17071)
- **Public Websites:** PACT Act, Income Limits and Global Search Results are all already using the v3 component so no updates are necessary.
- All other templates are not using the component. We should check with FE Engineers if they would be wrapped up in this content-build update or if they need a separate update.

## Other notes
- "VA.gov home" has been determined to be the default for [V3 breadcrumbs](https://design.va.gov/components/breadcrumbs#examples---v3)

### Acceptance Criteria
- [x] The potential impact of V3 on breadcrumbs is reviewed and documented.
- [x] Subsequent tickets for upgrade or Design System feedback are stubbed.

## Team
Please check the team(s) that will do this work.

- [ ] CMS Team
- [x] Public Websites
- [x] Facilities
- [ ] Accelerated Publishing

**Comment by xiongjaneg** [comment]
Added Public Websites to determine if changes made in Facilities products impact PW products

**Comment by maxx1128** [comment]
Breadcrumbs are a relatively complicated component that affects a lot of pages, so moving them to a v3 component has a larger amount of risk for me. My opinion is this should be kept to a separate update, and I would rate it at either a **5** or an **8.**

**Comment by xiongjaneg** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Sitewide-Facilities-639f5253e4b702a32376339e/issues/department-of-veterans-affairs/va.gov-cms/17162?planning-poker) with Zenhub @eselkin @maxx1128

**Comment by laflannery** [comment]
@maxx1128 and @eselkin Adding [the note from DST](https://dsva.slack.com/archives/C03R5SBELQM/p1707158519701019) about updates to the Breadcrumb component:

> The V3 breadcrumbs component recently gained support for react-router link components. The above instances will need to follow [this documentation](https://design.va.gov/storybook/iframe.html?id=uswds-va-breadcrumbs--with-router-link-support&viewMode=docs&args=#with-router-link-support) for including react router link components when migrated to V3.

Eli noted a concern during FE pre-refinement meeting today that this update had not yet been documented for content-build and was not entirely sure it was possible with content-build. That will need to be investigated first to determine feasibility

CC: @xiongjaneg @mmiddaugh

**Comment by jilladams** [comment]
Discussed with Laura in PW FE prefinement, noting: 
* This affects 100% Facilities products and ~50% PW products, where we use the same Breadcrumb custom code/partial
* Facilities will handle this spike
* Public Websites should code review any PR that comes up from this ticket or a future implementation ticket, as an AC. 
* Public Websites will remove breadcrumbs from scope of our other no-component > V3 tickets.

cc. @chriskim2311 @FranECross

**Comment by FranECross** [comment]
Removed breadcrumbs from all V1/V3 stories (description & AC) not in progress. cc @jilladams @chriskim2311

**Comment by laflannery** [comment]
@FranECross To clarify this applies to content-build only which is only about half of PW templates. The breadcrumb item needs to be evaluated and only removed from the tickets that apply to content-build

**Comment by mmiddaugh** [comment]
"VA.gov home" has been determined to be the default for [V3 breadcrumbs](https://design.va.gov/components/breadcrumbs#examples---v3), FYI
@xiongjaneg

**Comment by maxx1128** [comment]
I've confirmed with Laura on Slack that the V3 breadcrumb component needs no current changes. The main change required is to take all the logic used to modify the breadcrumbs in `src/site/includes/breadcrumbs.drupal.liquid` and move it over to a (heavily tested) liquid filter. That array will then need to be passed into the breadcrumbs component.

I will stub out a ticket for making this filter and another for implementing the component.

**Comment by jilladams** [comment]
Work here is complete and those 2 tickets have already had PM eyes for queuing / prioritizing. Closing this ticket.
