### ISSUE TITLE
[V3 Components] Implement available components for Campaign Landing Pages

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-cms#17178]
## Description

To align with the Design Team's intent to have all available components implemented in VA.gov, implement V3 components for the following:

- Links: are not using a component but should be using the [component](https://design.va.gov/components/link/)
  - This should be used everywhere possible, including content inside accordions
  - We also want to make sure we are using the proper variant of the links (i.e [Active link](https://design.va.gov/components/link/#active), [Channel](https://design.va.gov/components/link/#channel), etc.) so the styles remain the same
- Telephone
  - The [component](https://design.va.gov/components/telephone) is not being used anywhere but should be

### User story

**AS A** PO/PM for Public Websites products
**I WANT** to implement available V3 components in features & products currently under Public Websites management where components aren't currently being used
**SO THAT** all PW products are in alignment with the current component version.
**AND** Veterans and other users have a consistent experience within VA.gov

## Acceptance criteria
- [x] Links are using DS component
- [x] Telephone is using DS component

**Comment by chriskim2311** [comment]
PR is in review, will merge early next sprint

**Comment by chriskim2311** [comment]
Verified on prod. Closing!
