### ISSUE TITLE
Vet Center service editorial UX does not show national description

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-cms#17177]
## Description
When a Vet Center editor navigates from the Springboard/Dashboard to edit a service, the inline editing view displays the national service description (`general service description`). This is their usual path based on training and KB article instructions. <details>

<summary> UX of service via inline editing form </summary>

<img width="837" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0pFQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--97ee44ba84605e4acb567bda0bb132f3b7fb3d47/image.png" alt="image.png" />

</details>

---

But when the editor edits a service via the content search, the editing UX does not display the national service description (`general service description`). 
<details>
<summary> UX of service via selection from content search </summary>

<img width="1164" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL2hEQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a4c3efbaf8c836fede3322aebfd72725acfe9ddf/image.png" alt="image.png" />
</details>

---

This is important because 
- we will soon direct editors to use the alternate flow so that edits are published correctly: [Front end: Vet Center unpublished services should not be showing on VA.gov #16362](https://app.zenhub.com/workspaces/sitewide-facilities-639f5253e4b702a32376339e/issues/gh/department-of-veterans-affairs/va.gov-cms/16362)
- we will d/c use of inline editor flow for Vet Centers and replace with the VAMC/VBA model: [Last updated by human not set when Vet Center Service is saved/updated. #15124](https://app.zenhub.com/workspaces/sitewide-facilities-639f5253e4b702a32376339e/issues/gh/department-of-veterans-affairs/va.gov-cms/15124)
- editors need to see the national description to confirm they've chosen the service they want to add and to avoid repeating the description when entering local details 

## Acceptance criteria
- [x] When adding/editing/removing a service, the Vet Center editor can see (but not edit) the associated national service description
- [x] This applies to node view as well as node edit.

**Comment by xiongjaneg** [comment]
suggest pairing with #16362

**Comment by jilladams** [comment]
Hi! @Becapa this PR merged to main, but the ticket is marked Complete pending integration. Is that just because of the CMS deployment issues blocking it in prod? Or is it actually blocked from shipping to prod for business reasons? (I'm going to assume the former, and move it to "Pending prod verification" until I hear otherwise.)

**Comment by jilladams** [comment]
I tried verifying this with a Vet Center user (This one https://staging.cms.va.gov/user/4683) who is Content creator - Vet Center, and Content Publisher. With those roles, that user doesn't have Edit permissions on Vet Center facility services. Does that permission require a specific role?

If folks want to cross check: as that user, 
* Service coming through content search: https://staging.cms.va.gov/alexandria-va-vet-center/service/alexandria-va-vet-center-mental-health-care
* Service coming through dashboard: https://staging.cms.va.gov/node/3887/edit?destination=/section/vha/vet-centers/alexandria-la-vet-center#edit-field-health-services

cc @xiongjaneg

**Comment by Becapa** [comment]
> I tried verifying this with a Vet Center user (This one https://staging.cms.va.gov/user/4683) who is Content creator - Vet Center, and Content Publisher. With those roles, that user doesn't have Edit permissions on Vet Center facility services. Does that permission require a specific role?
> 
> If folks want to cross check: as that user,
> 
>     * Service coming through content search: https://staging.cms.va.gov/alexandria-va-vet-center/service/alexandria-va-vet-center-mental-health-care
> 
>     * Service coming through dashboard: https://staging.cms.va.gov/node/3887/edit?destination=/section/vha/vet-centers/alexandria-la-vet-center#edit-field-health-services
> 
> 
> cc @xiongjaneg

I was able to edit the second item with that user, but not the first. I think this is because of the sections related to the content. The first is part of the `Alexandria, VA Vet Center` section which the user **is not** part of. The second is related to the `Alexandria, LA Vet Center` section which the user **is** a part of. For the first item I switched to a user with the same roles, but in the `Alexandria, VA Vet Center` section (https://staging.cms.va.gov/user/3186) and I was able to edit that Service.

**Comment by xiongjaneg** [comment]
Verified in prod with [Nassau Vet Center](https://prod.cms.va.gov/nassau-vet-center)'s editor.
- National content is viewable but not editable for a new service.
- National content is viewable but not editable for an existing service.
- National content is viewable on node view.
<img width="770" alt="Screenshot 2024-03-11 at 12 21 37 PM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/73648238/beb55105-ad4b-4a61-be4a-73133c9a9c33">
<img width="770" alt="Screenshot 2024-03-11 at 12 21 50 PM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/73648238/7f5fcafa-c0f9-430b-bdc0-79d52f9af826">
<img width="1093" alt="Screenshot 2024-03-11 at 12 22 52 PM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/73648238/ceeb5004-3501-4374-a65f-d80bc0407768">
