### ISSUE TITLE
[V1 & 3 Components] Implement available components for Events

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-cms#17175]
## Noting Comment Re; Ownership Below
- Although we're handing off Events, we'll go ahead and do this item, but let's have it be the last component story we do.

## Description

The Design team is releasing a Typography update (sometime in March), which means that the PW team needs to upgrade any of our products where components aren't currently being using, but a V1 or V3 component is available.

If the updates aren't made prior to the Typography update, there's a chance that Veteran-facing issues may occur.

Example Pages:
- [VAMC Minneapolis Events](https://www.va.gov/minneapolis-health-care/events/)
- [Outreach Events](https://www.va.gov/outreach-and-events/events/)

## Elements that are not using components that should be
1. Link: We should be using the component everywhere possible
2. Select: We should be using [the v3](https://design.va.gov/components/form/select#examples---v3)
3. Button: Apply filter button should use the [v3 component](https://design.va.gov/components/button/#examples---v3)

Info from #17056 

### User story

**AS A** PO/PM for Public Websites products
**I WANT** to implement available V1 or V3 components in features & products currently under Public Websites management where components aren't currently being used
**SO THAT** all PW products are in alignment with the current component version
**AND** Veterans and other users have a consistent experience throughout VA.gov tools and information

## Acceptance criteria

- [x] Links are using V1 component
- [x] Select is using V3 component
- [x] Buttons are using V3 component
- [x] other features display correctly
- [x] verify/review the E2E tests
- [x] check desktop and mobile
- [ ] a11y review

**Comment by randimays** [comment]
@FranECross @jilladams just double checking that we want to tackle this, given the IIR team is taking over Events?

**Comment by jilladams** [comment]
It would be nice of us to do for them, given the timing of transition won't really start til 2/29. I'd vote let's go ahead and just leave it to the bottom of our pile to do last.

**Comment by randimays** [comment]
The work for this is in PR reviews, but we are experiencing a lot of issues getting CI to pass / review instances to work. If they aren't working tomorrow, I'll spin up an ngrok to get reviews.

**Comment by randimays** [comment]
End-of-sprint update: This PR has been ready for a while, but I've been struggling getting the CI to pass. Platform has been troubleshooting a lot of CI issues; but hopefully this will get merged today!

**Comment by randimays** [comment]
Validated successfully in prod. Closing!
