### ISSUE TITLE
"The file public://cms-asset-export-latest.tar was not deleted because it does not exist." 

### ISSUE THREAD

**Issue by ElijahLynn** [department-of-veterans-affairs/va.gov-cms#1717]
Follow up from #1360.

**Problem** 
When `/cms-export/asset` is requested the error "The file public://cms-asset-export-latest.tar was not deleted because it does not exist."  is shown in the logs.

**Comment by indytechcook** [comment]
Do we actually need a change here?  Do we not want to log the error message?

**Comment by ElijahLynn** [comment]
I'm not sure, but seems like you might be right here.
