### ISSUE TITLE
PW intake: Add toggle to Spanish GI Bill eligibility page from CAIA

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-cms#17171]
### Indicate if you need front-end engineering support for

- [ ] Content audit
- [ ] Implementation of REACT sign-in widgets
- [ ] Support for UAT testing or phased roll out of app/tool landing page
- [ ] Implementation of Translation widgets
- [X] Something else

### Describe your request

We published a new Spanish page that we need to add the language toggle to: https://www.va.gov/education/eligibility-esp/

### Time constraints / launch deadlines

No hard timing

### Your product/team Slack channel

Sitewide CAIA

### Your OCTODE product owner

Randi Hecht

### Notify Sitewide Public Websites of this issue, and tag @Fran Cross & @jilladams.

- [X] I acknowledge that I must notify `#sitewide-public-websites` in Slack after submitting this issue.

**Comment by randimays** [comment]
Working on getting this merged and verified in production today.

**Comment by randimays** [comment]
Verified in production. Closing!

<img width="1579" alt="Screenshot 2024-02-14 at 3 35 06 PM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/19175324/57723af0-748d-4f55-83b6-0f6c661966b5">
<img width="1575" alt="Screenshot 2024-02-14 at 3 35 13 PM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/19175324/f822ca06-d4d9-4ad1-8564-738e1e5c4b03">

**Comment by RLHecht** [comment]
@randimays We need the left nav to show up on this page as well. Let me know if there's something we should do on our end first. Thanks!

**Comment by randimays** [comment]
@RLHecht I created a bare bones ticket for us to refine: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17347

CC @FranECross @jilladams
