### ISSUE TITLE
URL Change for: Oconomowoc VA Clinic

### ISSUE THREAD

**Issue by stefaniefgray** [department-of-veterans-affairs/va.gov-cms#17184]
⚠️  NO URL RE-DIRECT NEEDED ⚠️ 

Simply needs to be updated within Lighthouse CSV / canonical URL change

-----

### Implementation date
When does this request need to be live:
Once main new facility ticket is completed -- clinic opens March 8th: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17183

### Instructions for canonical URL change
- [x] Verify that the new URL for the facility is published and accessible on VA.gov.
- [x] Update the [CSV in Lighthouse](https://github.com/department-of-veterans-affairs/lighthouse-facilities/blob/master/facilities/src/main/resources/websites.csv) with the changed URL, maintaining the sorted order of the Facility API IDs.
- [x] Create a PR in the [lighthouse-facilities repo](https://github.com/department-of-veterans-affairs/lighthouse-facilities), tagging the Lighthouse team.
- [x] Post a message in the #cms-lighthouse channel in Slack, with an @mention to a Lighthouse team member.
- [x] Add the "Awaiting CSV" flag to the facility node with a revision log message that includes a link to this ticket.
- [x] Validate that the change has deployed by checking that the Facility Locator has been updated with the new url.
- [x] Update this ticket with a comment that the CSV change has been deployed.
- [x] Remove the "Awaiting CSV" flag to the facility node with a revision log message that includes a link to this ticket.

#### URL change example (update with actual ID and URL)
| Facility API ID  |  Full VA.gov URL |
| ---  |  --- |
| vha_695GE | https://www.va.gov/milwaukee-health-care/locations/oconomowoc-va-clinic |

**Comment by ian-sears** [comment]
Ok/Approved to procvess and Publish this.
@TroyCMSSupport FYSA

**Comment by omahane** [comment]
This has been published and is awaiting CSV: https://dsva.slack.com/archives/C02BTJTDFTN/p1719340047322509

**Comment by jilladams** [comment]
Moved to Complete Pending Integration.

**Comment by jilladams** [comment]
The CSV update has been requested, but Lighthouse informed us they won't be able to publish it earlier than next week due to an infrastructure migration they have in progress: https://dsva.slack.com/archives/C02BTJTDFTN/p1719344701087939?thread_ts=1719340047.322509&cid=C02BTJTDFTN

**Comment by ian-sears** [comment]
Thank you. Yes, we (CMS Help Desk) saw that (next week) also. Thank you for pushing this through for them and we will inform them.

**Comment by TroyCMSSupport** [comment]
@ian-sears @omahane @jilladams  -I have confirmed the site is live in production, links working properly, VA.gov locator points to the correct page.
Notified Editor via Jira ticket https://va-gov.atlassian.net/browse/VAHELP-6960
