### ISSUE TITLE
New VAMC Facility: Oconomowoc VA Clinic

### ISSUE THREAD

**Issue by stefaniefgray** [department-of-veterans-affairs/va.gov-cms#17183]
## Intake
- [x] What triggered this runbook? (Flag in CMS, Help desk ticket, Product team, VHA Digital Media)
Trigger: Flagged Facilities view

- [x] Link to associated help desk ticket (if applicable)
Help desk ticket: https://va-gov.atlassian.net/browse/VAHELP-6960

- [x] Name of submitter (if applicable)
Submitter: @stefaniefgray 

- [x] If the submitter is an editor, send them links to any relevant KB articles for the VAMC Facility product.
KB articles: <insert_kb_article_links>

- [x] Link to facility in production:
Facility CMS link: https://prod.cms.va.gov/milwaukee-health-care/locations/oconomowoc-va-clinic
Facility API ID: vha_695GE

### New VAMC Facility
Please refer to the Knowledge Base article titled "How do I add a facility to my health care system?" for more information: https://prod.cms.va.gov/help/vamc/about-locations-content-for-vamcs/how-do-i-add-a-facility-to-my-health-care-system

#### CMS help desk steps
**Note: If the help desk is waiting on information from the facility staff or editor, add the "Awaiting editor" flag to the facility with a log message that includes a link to this ticket. Remove the flag when the ticket is ready to be worked by the Facilities team. Be sure to preserve the current moderation state of the node when adding or removing the flag.**
- [x] 1. Become aware that the new facility is now on the Facility API (typically, via a Flag, but this may come in as a helpdesk ticket).
- [x] 2. If the editor has followed the steps from the above Knowledge Base article and included which section and VAMC the facility belongs to (i.e. VA Pittsburgh), great! **Proceed to step 3.** If not, please check with the editor or VHA digital media regarding what section and VAMC it belongs to.
- [x] 3. Updates the Section (default is "VAMC facilities", but it should be a VAMC system in a VISN) and VAMC system field accordingly.
- [x] 4. Communicate with editor (cc VHA Digital Media) to give them go-ahead to complete the content, with this [KB article](https://prod.cms.va.gov/help/vamc/about-locations-content-for-vamcs/how-do-i-add-a-facility-to-my-health-care-system). (See sample notification email below)

<details><summary>Email template </summary>

```

Hello! You should now be able to edit the draft page for this facility, located at [LINK TO NEW FACILITY DRAFT PAGE ON PROD]

Important: Please make sure that all relevant steps listed within the “How do I add a facility to my health care system?” Knowledge Base article have been completed: https://prod.cms.va.gov/help/vamc/about-locations-content-for-vamcs/how-do-i-add-a-facility-to-my-health-care-system

Once finished, please save this page (and all related VAMC Facility Health Service pages) in the moderation state “Draft." Please do not save them as “Published.”

Please let us know when your draft content is complete, so that we can wrap up the technical process from our end before publishing the new facility to VA.gov. Thanks!

```

</details>

- [x] 5. Create a [URL change request](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/new?assignees=&template=runbook-facility-url-change.md&title=URL+Change+for%3A+%3Cinsert+facility+name%3E), changing the entry from the old facility URL to the new facility URL. (**Note: The URL change request ticket blocks the completion of this ticket.**)

https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17184

- [x] 6. When editor has prepared content and let help desk know, reassign this issue to appropriate CMS engineer on Product Support team, for bulk publishing.

#### CMS engineer steps
- [x] 7. CMS engineer executes the steps of the URL change request ticket from step 5 above.

(Redirects deploy weekly on Wed. at 10am ET, or by requesting OOB deploy (of the revproxy job to prod) in #vfs-platform-support. Coordinate the items below and canonical URL change after URL change ticket is merged, deployed, and verified in prod.)

#### Drupal Admin steps (CMS Engineer or Help desk)
_Help desk will complete these steps or escalate to request help from CMS engineering._
- [x] 8. Drupal Admin bulk publishes nodes and facility.
- [x] 9. Drupal Admin edit facility node and remove `New facility` flag and save node.
- [x] 10. Let Help desk know this has been done, if not done by Help desk.

#### CMS Help desk (wrap up)
- [x] 11. Notify editor and any other stakeholders.

**Comment by stefaniefgray** [comment]
Flagging to @jilladams @xiongjaneg since clinic opens soon

Jira ticket: https://va-gov.atlassian.net/browse/VAHELP-6960

**Comment by xiongjaneg** [comment]
As of Feb. 9, still waiting on customer for content

**Comment by ian-sears** [comment]
Editor reached us today and states: "We are ready to go live with the  Oconomowoc VA Clinic webpage. "

@omahane Let us know if there is anything further for us at the CMS Help Desk to do for Flagged Facilities at this step.
Ok to Bulk Publish.

@TroyCMSSupport FYSA

**Comment by ian-sears** [comment]
@jilladams @Agile6MSkinner @mmiddaugh This facility is/was ready for Bulk Publish. Editor approved this all going LIVE for Oconomowoc VA Clinic.
@TroyCMSSupport FYSA

**Comment by jilladams** [comment]
Noting: URL change is in https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17184, needs to happen first. Not sure when we can get to that this week, and I believe it should block the bulk publish.

**Comment by ian-sears** [comment]
Thank you, @jilladams 
@TroyCMSSupport FYSA

**Comment by ian-sears** [comment]
@omahane Editor followed up this morning:
"The Oconomowoc VA Clinic in Wisconsin has opened, and the first Veteran is being seen today, Jun 24."
The Editor is hoping to have this web page activated, soonest possible.
I promised to look into the progress and follow up with them by the end of the day with what I can discern.

**Comment by jilladams** [comment]
The CSV update has been requested, but Lighthouse informed us they won't be able to publish it earlier than next week due to an infrastructure migration they have in progress: https://dsva.slack.com/archives/C02BTJTDFTN/p1719344701087939?thread_ts=1719340047.322509&cid=C02BTJTDFTN

**Comment by omahane** [comment]
@ian-sears @TroyCMSSupport The CSV with the link has been deployed and verified on VA.gov. There is no other work to be done, so this can closed after confirmation with the editor.

**Comment by omahane** [comment]
Unassigning myself from this as there's no more Facilities work to do here.

**Comment by TroyCMSSupport** [comment]
@ian-sears @omahane @jilladams  -I have confirmed the site is live in production, links working properly, VA.gov locator points to the correct page.
Notified Editor via Jira ticket https://va-gov.atlassian.net/browse/VAHELP-6960
