### ISSUE TITLE
Update VAMC service hours to display "The service hours are the same as our facility hours"

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#17186]
## Description
VBA design says "The service hours are the same as our facility hours." VAMC handles this condition (fieldHours == "0") now is to display the fieldOfficeHours. However in VBA we don't. But the facilities may be different than the page for the facility you're looking at.

This is a behavior that we changed when we did VBA. The goal was to reduce the overall accordion length. Service Locations that are generated from Service Regions should not have the same logic though. They should be showing the hours of their primary facility (which may be in another time zone).

So VAMCs should match the new VBA behavior of showing a message in this situation.

## Acceptance Criteria
- [ ] Testable_Outcome_X
- [ ] Testable_Outcome_Y
- [ ] Testable_Outcome_Z
- [ ] Requires design review
- [ ] Requires accessibility review

**Comment by davidmpickett** [comment]
I'm pretty sure this will be resolved by VBA/VAMC service location launch

**Comment by davidmpickett** [comment]
Verified in prod
![Screenshot 2024-05-15 at 1 12 43 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/a3e7710f-bd39-4d46-8e65-6f5655a835b8)
https://www.va.gov/battle-creek-health-care/locations/battle-creek-va-medical-center/#physical-therapy-occupational-therapy-and-kinesiotherapy
