### ISSUE TITLE
Draft IA for Vet Centers 2.0

### ISSUE THREAD

**Issue by davidmpickett** [department-of-veterans-affairs/va.gov-cms#17195]
## User Story or Problem Statement
When Vet Centers sites are expanded to have navigation, we will need to determine what should be in it.

This IA will need to be vetted with CAIA, but we can do a first draft based on existing structures

- Should Vet Center Outstations and CAPs get their own URLs?
- What else beyond Events might be needed?

## Proposal
- [Diagram](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17195#issuecomment-2125148772)
- [Details](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17195#issuecomment-2125371888)

## Acceptance Criteria
- [x] Draft IA is documented 
- [x] Draft IA is reviewed with team 
- [x] Draft IA is sent to CAIA for review [pending CAIA intake request]

**Comment by jilladams** [comment]
Amanda meeting with Mikki Thurs 3/28 to discuss left nav strategy, bigger picture.

**Comment by aklausmeier** [comment]
Meeting with Mikki recap: When ready this will follow standard CAIA intake process. Assume same design and structure as VAMC.

**Comment by jilladams** [comment]
@davidmpickett can you clarify the Blocked label on this one? It was blocked by a ticket that is now closed, and want to make sure we start refining if that's next step.

**Comment by davidmpickett** [comment]
@jilladams Yes, the blocked label was to indicate that there was a ticket in front of this. That ticket was closed as not planned and I hadn't updated this ticket.

**Comment by davidmpickett** [comment]
Started by documenting the existing IA of Vet Centers in an [Excel doc on sharepoint](https://dvagov.sharepoint.com/:x:/s/SitewideFacilitiesTeam/ET7MGDqOYNxIiTemA2Q6Qy0BLd883FQ4qwffFREUyih2-Q?e=cTfKIT).

Point in time copy for ease of not having to CAG into Sharepoint
[Vet Centers IA (May 17, 2024).xlsx](https://github.com/department-of-veterans-affairs/va.gov-cms/files/15355573/Vet.Centers.IA.May.17.2024.xlsx)

**Comment by davidmpickett** [comment]
Viewing the headings in a indented format makes the semantic issues that @laflannery previously flagged in her [Vet Center Audit](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17371) and in her feedback on @thejordanwood's [design](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17891) painfully apparent. Not new information but just a different representation of known issues.

![Screenshot 2024-05-17 at 1 26 05 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/27c3a8c0-58ec-4334-ac55-7e37658f1129)

**Comment by davidmpickett** [comment]
- Updated sharepoint doc with a second tab for new IA
- Focusing only on page-level IA for now, no headings
- Ugh, the naming schema for satellite locations is super hairy
- New point in time doc 
[Vet Centers IA (May 17b, 2024).xlsx](https://github.com/department-of-veterans-affairs/va.gov-cms/files/15358070/Vet.Centers.IA.May.17b.2024.xlsx)



[Vet Centers IA (May 17b, 2024).xlsx](https://github.com/department-of-veterans-affairs/va.gov-cms/files/15358064/Vet.Centers.IA.May.17b.2024.xlsx)

**Comment by davidmpickett** [comment]
Page nickname | H1 | Breadcrumb | Nav menu link | URL =
-- | -- | -- | -- | -- 
Vet Center - Main location |`VCRegion` Vet Center | VA.gov home  >  `VCRegion` vet center | ? | va.gov/`vcregion`-vet-center/ 
Vet Center - Locations list | Locations | VA.gov home  >  `VCRegion` vet center  >  Locations  | Locations	| va.gov/`vcregion`-vet-center/locations/ 
Vet Center - Satellite location [Outstation] |	`OSregion` Vet Center Outstation	| VA.gov home  > ` VCRegion` vet center  >  Locations  >  `OSregion` Outstation	| Locations / `OSregion` Outstation | va.gov/`vcregion`-vet-center/locations/`osregion`-outstation 

Vet Center - Satellite location [CAP]	VCRegion Vet Center - AccessPointName	VA.gov home  >  VCRegion vet center  >  Locations  >  AccessPointName CAP	Locations - AccessPointName CAP	va.gov/vcregion-vet-center/locations/accesspointname-cap	AccessPointName CAP | VCRegion Vet Center |Veterans Affairs
Vet Center - Satellite location [Mobile vet center]	VCRegion Mobile Vet Center	VA.gov home  >  VCRegion vet center  >  Locations  >  VCRegion Mobile Vet Center	Locations - VCRegion Mobile Vet Center	va.gov/vcregion-vet-center/locations/vcregion-mobile-vet-center	VCRegion Mobile Vet Center |VCRegion Vet Center |Veterans Affairs
Vet Center - Events list	Events	VA.gov home  >  VCRegion vet center  >  Events	Events	va.gov/vcregion-vet-center/events/	Events |VCRegion Vet Center |Veterans Affairs
Vet Center - Event page 1	[Event 1  title]	VA.gov home  >  VCRegion vet center  >  Events  >  [Event 1 title]	N/A	va.gov/vcregion-vet-center/events/123456	Event 1 Title |VCRegion Vet Center |Veterans Affairs
Vet Center - Event page 2	[Event 2  title]	VA.gov home  >  VCRegion vet center  >  Events  >  [Event 2 title]	N/A	va.gov/vcregion-vet-center/events/987654	Event 2 Title |VCRegion Vet Center |Veterans Affairs

**Comment by davidmpickett** [comment]
@thejordanwood for mock up purposes here's an example of what the contents of Vet Centers 2.0 nav menu could be:

- Locations
  - Lawton Vet Center
  - Clarksville Outstation
  - Duncan CAP
  - Lawton Mobile Vet Center
- Events

**Comment by davidmpickett** [comment]
Rough sitemap
![Screenshot 2024-05-17 at 3 41 10 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/a6688292-9fc7-4fc7-8cd4-92f2ad0dd9ba)

**Comment by davidmpickett** [comment]
**Problems**
- **Main vet center** is the root of the site, but then should it also be listed in the location nav menu? Dishonest navigation?
- Outstations seem fine. I'd like to ditch the "Vet Center" in the middle of their name for URL/breadcrumbs etc.
- CAPs have wildly different names. Might need to have some standardization / add "CAP" after some rather than just listing naked region slug
- Mobile vet centers are fine, until they are referenced by vet centers other than their home location. How will breadcrumb and navigation work? Ugh

**Comment by davidmpickett** [comment]
### Current IA
```mermaid
flowchart TD
X(Level 0) ~~~ Y(Level 1) ~~~ Z(Level 2)
A[VA.gov] -->B

    B[Main Vet Center] --> C
    C[Locations]
```

### New IA
```mermaid
flowchart TD
X(Level 0) ~~~ Y(Level 1) ~~~ Z(Level 2) ~~~ M(Level 3)
A[VA.gov] -->B
    B[Main Vet Center] --> C
    B --> D
    C[Locations]
    D[Events]
    C --> E
C --> F
C --> G
    E[Outstation]
    F[CAP]
    G[Mobile Vet Center]
```

**Comment by davidmpickett** [comment]
# WIP

## Level 1 and Level 2 Pages

IA element | Main Vet Center page | Locations list
-- | -- | --
H1 | `VCRegion` Vet Center </br> Also called the `VCOfficialName` | Locations
Breadcrumb | VA.gov home  >  `VCRegion` vet center | VA.gov home  >  `VCRegion` vet center  >  Locations
Navigation Menu Link | Locations - `VCRegion` vet center? | Locations
URL | va.gov/`vcregion`-vet-center/ | va.gov/`vcregion`-vet-center/locations/
Title Tag | `VCRegion` Vet Center / Veterans Affairs | Locations / `VCRegion` Vet Center  / Veterans Affairs

### Variables legend

- `VCRegion` = Geographic region of a Vet Center. e.g. **Nashville**
- `VCOfficialName` = Some Vet Center have congressionally mandated official names. e.g. **Dr. Cameron McKinley Department of Veterans Affairs Veterans Center**

**Comment by mmiddaugh** [comment]
@davidmpickett  one clarification to avoid additional twisty naming confusion:
In the image in [your comment from 5/17](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17195#issuecomment-2118361822), Clarksville Outstation is associated with Prescott Vet Center. It is actually associated with Nashville Vet Center.

**Comment by davidmpickett** [comment]
@mmiddaugh Yeah I was using a mishmash of examples. @thejordanwood chatted today and we’re going to move all examples to Nashville since it has at least one of each satellite location type.

**Comment by davidmpickett** [comment]
**IA proposals** are documented in comments:
- [Diagram](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17195#issuecomment-2125148772)
- [Details](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17195#issuecomment-2125371888)

**Other Notes:**
- Mobile Vet Centers will not be candidates for having their own pages, only Outstations or CAPs
- Unlike VAMC systems where all facilities have their own pages, we will not be instituting a broad rule that says all Outstations or CAPs have their own page. This will more likely be on a case-by-case basis.
- CAP names are messy, but since there will be a case-by-case evaluation, we can impose naming standards during that process

**Open questions:**
- How should Main Vet Center Location be listed in Navigation menu?
- Should we include links in Navigation menu to locations that don't have their own subpage? Could be anchor link that go to relevant section of Locations list page
- For Outstations that have their own pages, do we have to use the full name in URL, breadcrumbs etc?
- CAPs naming?

**Comment by jilladams** [comment]
End of sprint update: 
* Dave updated proposals based on today's feedback and left a summary above, and is pencils down on this for the rest of the sprint but leaving ticket open because:
  * Amanda Klausmeier needs a chance to review after PTO
  * Lingering item dependent on creating CAIA intake ticket

**Comment by aklausmeier** [comment]
@davidmpickett Are the open questions for CAIA or do you need feedback on these prior to submitting to CAIA?

Otherwise looks good to go.

**Comment by davidmpickett** [comment]
> @davidmpickett Are the open questions for CAIA or do you need feedback on these prior to submitting to CAIA?
> 
> Otherwise looks good to go.

Mostly for CAIA. The CAP naming is more of something for Michelle to talk about with RCS, but also not urgent or blocking CAIA review.

**Comment by jilladams** [comment]
CAIA intake exists, feel free to pile on: https://github.com/department-of-veterans-affairs/va.gov-team/issues/83961

**Comment by davidmpickett** [comment]
Added to CAIA intake
