### ISSUE TITLE
[V1 & 3 Components] Implement available components for Resources & Support taxonomy term page

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-cms#17199]
## Description
The Design team is releasing a Typography update (sometime in March), which means that the PW team needs to upgrade any of our products where components aren't currently being using, but a V1 or V3 component is available.

If the updates aren't made prior to the Typography update, there's a chance that Veteran-facing issues may occur.

Example pages:

- [VA account and profile](https://www.va.gov/resources/va-account-and-profile/)
- [Education and training](https://www.va.gov/resources/education-and-training/)

## Elements that are not using components that should be
1. Pagination
   - We are not using a component need to update to [v3 component](https://design.va.gov/components/pagination#examples---v3)

**Might be be resolved with the [Resources Landing page ticket](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16986) but if not:**

1. Search input
   - We should be using [the v3](https://design.va.gov/components/search-input#examples---v3)
2. Radio buttons
   - There might be some technical limitations here, I'm not sure but if possible we should be using [v3 components](https://design.va.gov/components/form/radio-button#examples---v3)

### User story

**AS A** PO/PM for Public Websites products
**I WANT** to implement available V1 or V3 components in features & products currently under Public Websites management where components aren't currently being used
**SO THAT** all PW products are in alignment with the current component version
**AND** Veterans and other users have a consistent experience throughout VA.gov tools and information

## Acceptance criteria

- [x] Pagination uses V3
- [x] Search input uses V3
- [x] Radio buttons use V3, if possible
- [x] other features display correctly
- [x] verify/review the E2E tests
- [x] check desktop and mobile
- [ ] a11y review

**Comment by randimays** [comment]
I am working on this one plus #16986. Struggling with pagination as the v3 component has elements in the shadow DOM, and we have to add a click handler to change the pages and can't access the shadow DOM elements. I have been communicating with Jami from the DST about it here: https://dsva.slack.com/archives/C01DBGX4P45/p1708967336736359 hopefully we can find a solution!

Search input and radio buttons are finished already, but we still need an accessibility review of everything once it's complete.

**Comment by randimays** [comment]
Continuing work on this as pagination has proven more tricky than anticipated. Max identified some issues with facility-side pagination and I am working on resolving those. I do expect this to close by end of sprint; it's just taking longer than we planned.

**Comment by randimays** [comment]
Just merged in the final changes for pagination. The code will deploy tomorrow afternoon and we can validate and close, hopefully!

**Comment by randimays** [comment]
Validated successfully in production. Closing!
