### ISSUE TITLE
[V1 & 3 Components] Implement available V1 or V3 components for the PACT Act Wizard

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-cms#17200]
## Description
The Design team is releasing a Typography update (sometime in March), which means that the PW team needs to upgrade any of our products where components aren't currently being using, but a V1 or V3 component is available.

If the updates aren't made prior to the Typography update, there's a chance that Veteran-facing issues may occur.

[PACT Act App](https://staging.va.gov/pact-act-eligibility/introduction)

## Elements that are not using components that should be

1. Link
   - We should be using the [V1 component ](https://design.va.gov/components/link/)everywhere we can, including content inside inside accordions

**We actually have a [separate tracking ticket ](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15910)for the next 2 because we knew we weren't using components in this case**

2. Radio buttons
   - With the recent update to the DS this can be updated to use the [v3 component](https://design.va.gov/storybook/?path=/docs/uswds-va-radio--forms-pattern-single#forms-pattern-single) now
3. Check box group
   - With the recent update to the DS this can be updated to use the [V3 component](https://design.va.gov/storybook/?path=/docs/uswds-va-checkbox-group--forms-pattern-single) now

### User story

**AS A** PO/PM for Public Websites products
**I WANT** to implement available V1 or V3 components in features & products currently under Public Websites management where components aren't currently being used
**SO THAT** all PW products are in alignment with the current component version
**AND** Veterans and other users have a consistent experience throughout VA.gov tools and information

## Acceptance criteria

- [x] Links use V1
- [x] Radio buttons use V3
- [x] Check box group uses V3
- [x] other features display correctly
- [x] verify/review the E2E tests
- [x] check desktop and mobile
- [ ] a11y review

**Comment by randimays** [comment]
## Converted components ([PR here](https://github.com/department-of-veterans-affairs/vets-website/pull/28227))
- Radio buttons
- Checkboxes
- Some links

## Can be converted but not yet

The green and blue action links are not yet converted into web components. Carol from the DST provided a ticket for their upcoming sprint that will add this: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2500

@FranECross @jilladams I propose we hold this ticket in Blocked after the PR for the rest of the work is merged, and we can complete once DST gets their work across the line?

Links that will need to be converted when this is available:

1. results 1 page 2<br/>
<img width="328" alt="Screenshot 2024-02-28 at 8 46 40 AM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/19175324/1742ae3a-567f-486c-a626-1cca21a47d6c">

2. results 1 page 2<br/>
<img width="251" alt="Screenshot 2024-02-28 at 8 46 45 AM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/19175324/a205f278-6c1e-40f8-b16a-b641317efdd0">

3. results 1 page 2<br/>
<img width="244" alt="Screenshot 2024-02-28 at 8 47 49 AM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/19175324/80ed8e4d-be07-4c42-b10b-b5d3c1be6058">

4. home screen<br/>
<img width="149" alt="Screenshot 2024-02-28 at 8 51 10 AM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/19175324/01165e35-952d-47e4-97f6-29499921211f">


## Cannot convert

Per this Slack thread: https://dsva.slack.com/archives/C01DBGX4P45/p1692802785182169 we cannot use `<va-link>` for links that open in a new tab.

1. results 1 page 1 <br/>
<img width="559" alt="Screenshot 2024-02-28 at 8 38 30 AM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/19175324/c57549a0-1613-43ce-9c78-f8519bbe37fd">

4. results 1 page 2<br/>
<img width="575" alt="Screenshot 2024-02-28 at 8 39 44 AM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/19175324/1dc8e549-746f-41f0-a82e-3c05cc7e3a57">

6. results 1 page 2<br/>
<img width="606" alt="Screenshot 2024-02-28 at 8 40 29 AM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/19175324/ab12db1c-ff33-4c43-b222-13930b999b27">

7. results 1 page 2 and results 2<br/>
<img width="465" alt="Screenshot 2024-02-28 at 8 41 08 AM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/19175324/536c19d9-5726-47d2-ad12-1e42d6abdf2e">

8. results 1 page 2<br/>
<img width="491" alt="Screenshot 2024-02-28 at 8 41 36 AM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/19175324/06e3c880-0c5b-4e5e-82f2-f8d8788dfeaf">

9. results 1 page 2<br/>
<img width="423" alt="Screenshot 2024-02-28 at 8 48 20 AM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/19175324/8e94ee30-306d-4213-8a57-aedfa8197fc7">

10. results 3<br/>
<img width="470" alt="Screenshot 2024-02-28 at 8 50 09 AM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/19175324/ff1f397b-6e26-4606-98bb-3780d02f1ff5">

11. results 3<br/>
<img width="405" alt="Screenshot 2024-02-28 at 8 50 15 AM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/19175324/04572bc1-1672-44f7-b584-ab185b3703c1">

**Comment by randimays** [comment]
Update: the new radio and checkbox components were added, but they required a bit more fine-tuning as we needed to implement h1 focus. The PR is ready for review and we should get accessibility signoff from Laura on Monday when she returns from PTO.

**Comment by FranECross** [comment]
> All of the PACT Act components that can be made into web components currently have been converted. @FranECross will split out the action link conversion (`Can be converted but not yet`) into a new ticket; Closing!

Ticket #17404 created! cc @randimays
