### ISSUE TITLE
Standardize spotlight patterns on FE facility pages

### ISSUE THREAD

**Issue by thejordanwood** [department-of-veterans-affairs/va.gov-cms#17208]
## Details
Spotlight content on VAMC and Vet Center pages are displayed differently. This content needs to be standardized across pages and aligned with design system components if possible. 

## Additional Context 

This was discussed in https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14981 with a decision to "leave the spotlight section as is (for VBA), with blue boxes and in the same location. We can review this along with it's placement on Vet Centers at a later date."

This is also discussed in #13804, where it was pointed out that the CMS fields also aren't consistent. This can be solved after the visual representation is aligned.

## Design

Spotlight content page in the [VAMC CMS Master Figma file](https://www.figma.com/file/ikCp2eOubIgbN1TwyEYIrN/VAMC-CMS-Master?type=design&node-id=108%3A1696&mode=design&t=bxSCcRyZGNjeIOfs-1). 

## Spotlight Content 

From [this comment](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13804#issuecomment-1783409012) on #13804:

The multiple blue boxes are currently used in two places (and soon to be a third with VBA regional offices).

[VAMC health services page](https://www.va.gov/chicago-health-care/health-services/)

![278739741-31d3d3bf-ac42-4fb0-8990-f8e9a271a2df](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/104526584/e343f45d-708f-4eb4-983e-d1e0b0d1b5c9)

[Vet center page](https://www.va.gov/evanston-vet-center/)

![278739756-a1f81ce1-0b5a-4e83-8d4c-7e274b3aee04](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/104526584/1842a68a-1919-4b0c-8602-c7465ab0bc46)

The single blue box approach is used on VAMCs. It is controlled at a System level, but shows up on multiple front end pages

https://www.va.gov/chicago-health-care/
https://www.va.gov/chicago-health-care/locations/jesse-brown-department-of-veterans-affairs-medical-center/

![278741172-a694bbba-8484-49db-af24-d564e29e7a03](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/104526584/2d478bb2-dd1b-4c86-bbb6-d57644431329)

## Acceptance Criteria
- [x]  Create single design for spotlight news boxes
- [x]  Convert the spotlight box with multiple links to align with [design system component](https://design.va.gov/components/link/collection)
- [x] Document use cases for the spotlight cards (multiple links, no links, bullets?) to prepare for Design Intent
- [x]  Review with accessibility (could use UX sync)
- [x]  Review with content design (could use UX sync)
- [x]  Review with engineers (could use UX sync)
- [x]  Schedule review with UX Lead
- [ ] Stub follow up tickets or tag PO to stub subsequent tickets.

**Comment by mmiddaugh** [comment]
@thejordanwood you may want to review [Standardize spotlight patterns in CMS facility content types #13804](https://app.zenhub.com/workspaces/sitewide-facilities-639f5253e4b702a32376339e/issues/gh/department-of-veterans-affairs/va.gov-cms/13804) as a possible duplicate for this issue. (If so, feel free to close on and keep your favorite) 

There are other issues on the board which might be relevant, including
- [Plain text links in Vet Center spotlights in CMS #10301](https://app.zenhub.com/workspaces/sitewide-facilities-639f5253e4b702a32376339e/issues/gh/department-of-veterans-affairs/va.gov-cms/10301)
- [Enable “Spotlight” component on VAMC detail pages (and possibly Benefits Hubs pages) as content blocks #5731](https://app.zenhub.com/workspaces/sitewide-facilities-639f5253e4b702a32376339e/issues/gh/department-of-veterans-affairs/va.gov-cms/5731)
- [VAMC System Spotlight content - Discrepancies between CMS and FE #13801](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13801)
- [Incorrect heading level for spotlight section on health services page #12080](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12080)

**Comment by xiongjaneg** [comment]
From Michelle: What will be the impact on existing implementation? Hopefully none.

**Comment by thejordanwood** [comment]
@mmiddaugh I relabeled this ticket for clarity. This is for the FE implementation, and once we've figured out how to standardize this we can move on to the [Standardize spotlight patterns in CMS facility content types #13804](https://app.zenhub.com/workspaces/sitewide-facilities-639f5253e4b702a32376339e/issues/gh/department-of-veterans-affairs/va.gov-cms/13804) ticket to create consistency in the CMS.

**Comment by thejordanwood** [comment]
This is ready for review from everyone. I've put some questions[ in the Figma file](https://www.figma.com/file/ikCp2eOubIgbN1TwyEYIrN/VAMC-CMS-Master?type=design&node-id=108%3A1696&mode=design&t=bxSCcRyZGNjeIOfs-1), which can be answered in UX sync if we'd like to talk about it there. 

- @aklausmeier @davidmpickett I have [a comment in Figma](https://www.figma.com/file/ikCp2eOubIgbN1TwyEYIrN?node-id=108:5635&mode=design#726347132) asking your thoughts on how we should handle spotlight content that has no link. 
- @maxx1128 @eselkin I have a couple of comments in Figma asking how the [major links](https://design.va.gov/components/link/collection#major-links) and [related links](https://design.va.gov/components/link/collection#related-links) components work. ([comment 1](https://www.figma.com/file/ikCp2eOubIgbN1TwyEYIrN?node-id=108:5635&mode=design#726339667), [comment 2](https://www.figma.com/file/ikCp2eOubIgbN1TwyEYIrN?node-id=108:5477&mode=design#726349457))
- @laflannery I don't have any specific question for you, but would love your accessibility eyes on this.

**Comment by laflannery** [comment]
A couple other use cases that we takled ot VBA about and we've seen in the past:
- Adding phone numbers (this happens A LOT)
- Register links for events
I will see if I can find some real life examples of these being used in the wild for you

**Comment by aklausmeier** [comment]
> I added some other use cases in the wild that might help you to mock up some examples to see how we might think about expanding the cards for editor needs:

and an opportunity to set up guardrails in Drupal and/or helps us create future product needs and ideas for Vet Center iteration (timing tbd, but still good to understand their needs)

**Comment by thejordanwood** [comment]
@aklausmeier I updated [the Figma file](https://www.figma.com/file/ikCp2eOubIgbN1TwyEYIrN/VAMC-CMS-Master?type=design&node-id=108%3A1696&mode=design&t=cVz51Gik6zrpoMUl-1) to show the use cases and how we could solve for them. I also included a couple of thoughts on some Drupal guardrails we could implement.

**Comment by aklausmeier** [comment]
@thejordanwood design review complete, looks good, I think you're ready for a design intent

**Comment by xiongjaneg** [comment]
Can be closed per [Amanda's comment in Slack](https://dsva.slack.com/archives/C0FQSS30V/p1710276047270189?thread_ts=1710271646.736379&cid=C0FQSS30V)
