### ISSUE TITLE
[cms-ci] Configure CI PR Review environments to receive the assets/files sync

### ISSUE THREAD

**Issue by ElijahLynn** [department-of-veterans-affairs/va.gov-cms#1721]
Follow up from #1360.

AC: 
- [ ] PR Review Environments all have the full files snapshot 
- [ ] Grafana chart to show diskspace of the CI server, with an alert to notify if reach 80% capacity

**Problem**
PR Review Environments do not get the `sites/pr123.ci.cms.va.gov/default` folder synced from upstream PROD. The "demo" environments do but not the PR ENVs. We must have this to test the new FE content build script coming, that depends on the files folder for the CMS Export folders to build content from. 

**Solution** 
Setup the site that they clone their settings from so that files are always cloned. 

**Notes**
Look at the devel tab for info on the site they clone from, I believe it is incorrect. And there was work and commits on getting this working for DEMO that we can sleuth for info on how to do this. 

Each site will end up using 1GB of files if we just straight copy the data, the current disk size is 250GB and should be fine as we shouldn't have more than 50 PR sites but if this grows we must take that into account. 

We discussed using Stage File Proxy, but that doesn't appear it will work because the WEB builds that consume CMS Export need _all_ the files present and SFP doesn't actually pull them all in (which is it's purpose, not to do that).

**Comment by ElijahLynn** [comment]
I did this for the DEMO environments but had an issue doing this for the PR environments because the source clone thing (foggy memory here) was bad. There is PHP code on the CI server to do this for DEMO.

**Comment by ElijahLynn** [comment]
Pausing on this until #2679 is decided.

**Comment by indytechcook** [comment]
This is not longer needed since we pull the files down with Tugboat
