### ISSUE TITLE
Update Drupal Address module to V2 for Events

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#17239]
## Description
Upgrade Drupal Address module to version 2 for Events.

## Background
The [Address](https://www.drupal.org/project/address) module is inline to release a 2.0 version of the module.
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5752113/610d19d3-1ed7-41f6-8935-72067f924ec9)

One of the updates to 2.0 is the addition of the address line 3.   (current version only has two) 
   - Changes would need to be made to the GraphQL queries and  FE templates

## Consideration
Facilities Team will be updating this module for facilities and could potentially incorporate Events into their work as well.

**Comment by FranECross** [comment]
@dsasser Did the recent Drupal updates take care of this request, or do we still need to consider this? No rush in answering; just grooming the backlog. Thanks!

**Comment by dsasser** [comment]
> @dsasser Did the recent Drupal updates take care of this request, or do we still need to consider this? No rush in answering; just grooming the backlog. Thanks!

Yes the address module has already been upgraded to version 2.0.2. Closing.
