### ISSUE TITLE
Prescott Vet Center content and users need to move under Dr. Cameron McKinley Department of Veterans Affairs Veterans Center

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#17240]
## Problem statement
"As a Prescott Vet Center editor, I need to be able to edit content for my Vet Center, which was formerly named Prescott Vet Center but is now named Dr. Cameron McKinley Department of Veterans Affairs Veterans Center."

Prescott Vet Center content and users need to be moved over to Dr. Cameron McKinley Department of Veterans Affairs Veterans Center.

Vet Center sections are named after the Vet Center itself, rather than a system (like VAMC), so when they change, there's a cascade of effects.

## Acceptance Criteria
- [Prescott Vet Center content ](https://prod.cms.va.gov/section/vha/vet-centers/prescott-vet-center) is moved under [Dr. Cameron McKinley Department of Veterans Affairs Veterans Center](https://prod.cms.va.gov/section/vha/vet-centers/dr-cameron-mckinley-department-of-veterans-affairs-veterans-center)
- Prescott Vet Center users are moved under [Dr. Cameron McKinley Department of Veterans Affairs Veterans Center](https://prod.cms.va.gov/section/vha/vet-centers/dr-cameron-mckinley-department-of-veterans-affairs-veterans-center)

**Comment by jilladams** [comment]
@xiongjaneg @omahane I'm pretty sure Steve did this work in the linked PR above and it's complete pending integration. Wasn't marked that way, but I did mark it based on the PR. Lemme know if I'm wrong?

**Comment by omahane** [comment]
Steve accidentally mentioned this issue. It was not related to the script.

**Comment by jilladams** [comment]
Ok thanks - moved back to "to do" column, and we can update from there.
