### ISSUE TITLE
Match export endpoint, TAR and folder names

### ISSUE THREAD

**Issue by ElijahLynn** [department-of-veterans-affairs/va.gov-cms#1724]
Follow up from #1360.

**Problem**
Currently the endpoints, TAR files and folder names don't all match:
* /cms-export/content
* /cms-export/asset

The TAR files are:
* cms-content-export-latest.tar
* cms-asset-export-latest.tar

And the folders inside are named:
* cms-export-content
* . (doesn't have a folder name)

**Solution** 
Make them all match. Will need to communicate with FE team to change build script too, or just make a PR.

**Comment by oksana-c** [comment]
closing due to deprecation of cms-export
