### ISSUE TITLE
[V1 & 3 Components] Implement available V1 or V3 components for Discharge Upgrade Wizard

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-cms#17252]
## Background

The Design team is releasing a Typography update (sometime in March), which means that the PW team needs to upgrade any of our products where components aren't currently being using, but a V1 or V3 component is available.

If the updates aren't made prior to the Typography update, there's a chance that Veteran-facing issues may occur.

Pages:

- [Discharge Upgrade instructions](https://www.va.gov/discharge-upgrade-instructions/)
- [Discharge upgrade Wizard](https://www.va.gov/discharge-upgrade-instructions/questions)
- [Discharge upgrade guidance (results)](https://www.va.gov/discharge-upgrade-instructions/guidance)

## Elements that are not using components that should be
1. Link
   - We should be using [the v1 component](https://design.va.gov/components/link/) everywhere we can, including content inside inside accordions
2. Action Link
   - On the results screen, it looks like we are using the proper [Action link](https://design.va.gov/components/link/action) but it's not. We are using an icon instead of the proper VADS class
3. Accordion
   - On the instructions and results pages, the accordion sections should be using [the v3 component](https://design.va.gov/components/accordion#examples---v3).
4. Process list
   - No component is being used but [the v3 one](https://design.va.gov/components/process-list#examples---v3) should be
5. Button? Download Link?
   - We should confirm this with CAIA but on the results screen there is a button that is for the form download. I believe the guidance is now to use the[ download link component](https://design.va.gov/components/link/#download) vs a [button](https://design.va.gov/components/button/#examples---v3) but I'm not positive
6. Breadcrumbs
   - Not using any component but should be [using v3 (https://design.va.gov/components/breadcrumbs#examples---v3)

From #17005

### User story

**AS A** PO/PM for Public Websites products
**I WANT** to implement available V1 or V3 components in features & products currently under Public Websites management where components aren't currently being used
**SO THAT** all PW products are in alignment with the current component version
**AND** Veterans and other users have a consistent experience throughout VA.gov tools and information

## Acceptance criteria

- [x] Links use V1
- [x] Action link is using the proper VADS class
- [x] Accordion is using V3
- [x] Process list is using V3
- [x] Button /Download link is per guidance
- [x] Breadcrumbs use v3 component
- [x] other features display correctly
- [x] verify/review the E2E tests
- [x] check desktop and mobile
- [x] a11y review

**Comment by randimays** [comment]
Posted this for review today: https://github.com/department-of-veterans-affairs/vets-website/pull/28359. Companion content-build PR needed (https://github.com/department-of-veterans-affairs/content-build/pull/1944) because we are removing the breadcrumbs from the content-build side and putting them in vets-website so we can use the v3 component.

**Comment by randimays** [comment]
Validated successfully in production. Closing!
