### ISSUE TITLE
[Income Limits] Automated Income Limits Launch Plan

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-cms#17250]
## Status
[2024-08-12 Daniel] Updated ACs. Also [proposed](https://dsva.slack.com/archives/C03LFSPGV16/p1723484364580289) a new cadence for Sidekiq scripts to allow for monthly automated data imports vs quarterly.
[2024-02-22 Fran] This was reviewed with Jill/Fran today; Daniel to update the A/C based on the convo.

## Description

Develop Income Limits automation Launch Plan.

### User story

**AS A** PO/PM for the Income Limits app
**I WANT** the uploading of new income limits information to be automated
**SO THAT** Veterans have the most up to date information readily available
**AND SO THAT** development work isn't needed to upload new information when it's available.

### Quality / testing notes
Confirmation of the end-to-end automation is made by running the Sidekiq import scripts.

## Acceptance criteria

- [ ] Run the GHA to export fresh CSVs to S3
- [ ] Run the Sidekiq import scripts (Ask Platform to run them)
- [ ] Confirm there are no errors when running the scripts

**Comment by FranECross** [comment]
@dsasser Here's the launch plan for Income Limits Automation. I've also created a card in Trello for 16th minute for next week. Thanks for all your hard work on this!

**Comment by jilladams** [comment]
If auto run is March 1, IMO we can wait for it. But if it's April 1, I'd vote to ask Plat to run the script just to reduce lag time / contract transition risk, etc.

**Comment by dsasser** [comment]
## Mid-sprint update 4/24/24

🟡 I haven't begun this work as I have been focused on the sprint goals. The plan is to begin this toward the end of the sprint.

**Comment by dsasser** [comment]
These original ACs ...

![Screenshot 2024-08-12 at 10 40 44 AM](https://github.com/user-attachments/assets/43585517-9a19-4328-bc2a-a289555ef5eb)

... were written before a full end-to-end automation was realized for Income Limits. Since then, the automated scripts have been running, and we have seen the 2023 year data auto-populate [as expected](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16458#issuecomment-1864938666), which confirms that the end-to-end automations are working.

**Comment by dsasser** [comment]
I executed the GHA for the first AC:

![Screenshot 2024-08-12 at 11 02 52 AM](https://github.com/user-attachments/assets/e99c0420-6461-40e6-9185-0db4926fd237)

**Comment by dsasser** [comment]
I [asked Platform](https://dsva.slack.com/archives/CBU0KDSB1/p1723486918368949) to run the Sidekiq scripts.
