### ISSUE TITLE
MVP for improved help text with "learn more" behavior.

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#1726]
## User Story or Problem Statement

We have a [hypothesis ](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/1628) for how to improve help text and a [Drupal Landscape analysis](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/1561). Now we need to find the best ways to implement the MVP to put ahead of users. 

## Acceptance Criteria
* We can test the hypothesis from #1628

## Implementation steps
* Implement the "learn more" design pattern for X fields on X content types, with js and theming in the vagovadmin theme 
* Get sample help content for those fields
* We have a demo environment in which we can test the hypothesis with users

https://app.mural.co/t/vagov6717/m/vagov6717/1586882180337/415aa0adba23f935239d291d83fda234b16f1957

![On_help_text_•_Agile_Six_Workspace](https://user-images.githubusercontent.com/643678/81361726-24d67d80-90ad-11ea-8abe-52599bb67446.jpg)

**Comment by oksana-c** [comment]
[Doc to collaborate on the MVP]( https://docs.google.com/document/d/1uWgNMI6-QuZ38y3Be6oxQb-QJbm5_XuxMZRsbBsEmFY/)
