### ISSUE TITLE
Income Limits: Documentation Update

### ISSUE THREAD

**Issue by dsasser** [department-of-veterans-affairs/va.gov-cms#17260]
## Description
After cutting over to the fully automated data import process using GHA, we need to update existing engineering documentation to reflect the changes.

Update the Income Limits engineering [documents](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/income-limits-app) to reflect the new automated import process.

## Acceptance criteria

- [x] Documentation has been updated and reflects the new automated processes
- [x] Documentation has been updated to reflect the steps to implement the banner visible to Veterans, and should note that the alert should go below the H1 in order to retain the proper heading structure for accessibility so when we add this again I would recommend adjusting the placement

**Comment by FranECross** [comment]
There is a ticket to cut over to automation that needs to happen before we transition.

**Comment by dsasser** [comment]
## Mid-sprint update 4/24/24

🟡 I haven't begun this work as I have been focused on the sprint goals. The plan is to begin this toward the end of the sprint.

**Comment by dsasser** [comment]
@FranECross I'm not sure what banner this AC is referring to:

> Documentation has been updated to reflect the steps to implement the banner visible to Veterans, and should note that the alert should go below the H1 in order to retain the proper heading structure for accessibility so when we add this again I would recommend adjusting the placement

**Comment by FranECross** [comment]
@dsasser It's the banner (react-app) that was put up to alert Veterans that new data was available (and there was a subsequent ticket to take it down). Here's the ticket to display the banner: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16458

**Comment by dsasser** [comment]
## Status Update 8/9/24

✅ Work completed.

All [engineering](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/income-limits-app/engineering) and [data](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/income-limits-app/data) related documentation has been updated (if needed).

I also added a new document for banner information and creation [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/income-limits-app/new-year-banner.md). It is linked from the main [engineering information page](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/income-limits-app/engineering) as well to make way finding easier.
