### ISSUE TITLE
[Drupal] Test the back end changes for the Address module upgrade to version 2 

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-cms#17268]
## Status
**[2024-02-22 Fran]** Their ticket will be worked on in Sprint 105 (2/28 to 3/12), so we should plan to pull this ticket into that sprint as well.

## Description

The CMS team is making back end changes for Address module upgrade to version 2 in ticket #[17191](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17191), and the PW team will need to test the changes when the tugboat is available.

### User story

**AS A** PO/PM/Engineer
**I WANT** to ensure that any Drupal changes are tested thoroughly
**SO THAT** there aren't any Veteran-facing issues in VA.gov

## Acceptance criteria

- [ ] Test to determine if there are any issues with the features affected by the Drupal backend changes
  - [ ] If there are issues, report to the executing team ASAP via Slack and as a comment in the ticket mentioned above
  - [ ] OR, if the issue(s) are on the PW side, communicate ASAP to the executing team, & create a ticket for the PW team
    - [ ] complete PW work; communicate to the executing team
  - [ ] If there are NO issues, report to the CMS team via Slack and comment on the associated ticket 
- [ ] Close this ticket after testing is successful with no issues.

**Comment by dsasser** [comment]
The changes all tested out fine in the related facilities [PR](https://github.com/department-of-veterans-affairs/va.gov-cms/pull/17392). This is good to ship.
