### ISSUE TITLE
[V1 & 3 Components] Implement available components for the homepage

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#17277]
## Background

The Design team is releasing a Typography update (sometime in March), which means that the PW team needs to upgrade any of our products where components aren't currently being using, but a V1 or V3 component is available.

If the updates aren't made prior to the Typography update, there's a chance that Veteran-facing issues may occur.

[Homepage](https://www.va.gov/)

## Elements that are not using components that should be

2. Button
   - Create account button, is not using a component and should be be using [the v3 component](https://design.va.gov/components/button/#examples---v3)
3. Link
   - We should be using the component everywhere possible (Create account block, Top pages, news, etc.)
4. Text input
   - The email signup should be using the [v3 text input field](https://design.va.gov/components/form/text-input#examples---v3). Type email is allowed so don't think there would be a technical issue implementing this

### Signin modal
Is owned by the Identity team. Identity is holding off on component updates, due to the limitation around web components in the header on injection. They are already in discussions with the DS team related to this and connected to injected header flattening: https://dsva.slack.com/archives/CSFV4QTKN/p1709239337204619

Thus: these 2 items won't be completed under this ticket: 

1. Modal
   - Sign in modal does not use a component but should use the [v3 modal](https://design.va.gov/components/modal#examples---v3)
2. Telephone
   - There are phone numbers inside the modal that should be using [the v1 component](https://design.va.gov/components/telephone)

### Search Input

Removed from this ticket and new [ticket](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17395) created
1. Search input
   - In the header, there is a second search input. Are we able to/should we embed the [v3 search input](https://design.va.gov/components/search-input#examples---v3) inside the header knowing that this will eventually be a component itself?
   - We are in discussions with DST about the best way to handle this relative to flattening the injected header and converting the header to become a web component: https://dsva.slack.com/archives/C01DBGX4P45/p1709240254379689

From #17002 

### User story

**AS A** PO/PM for Public Websites products
**I WANT** to implement available V1 or V3 components in features & products currently under Public Websites management where components aren't currently being used
**SO THAT** all PW products are in alignment with the current component version
**AND** Veterans and other users have a consistent experience throughout VA.gov tools and information

## Acceptance criteria

- [x] Buttons are using v3 component
- [x] Links are using v1 component
- [ ] Email signup is using v3 text input field component
- [x] other features display correctly
- [x] verify/review the E2E tests
- [x] check desktop and mobile
- [ ] a11y review

**Comment by randimays** [comment]
> 1. Search input
In the header, there is a second search input. Are we able to/should we embed the [v3 search input](https://design.va.gov/components/search-input#examples---v3) inside the header knowing that this will eventually be a component itself?

We cannot do this right now because the injected header still shares this code. Options:
- We can do this later when the injected header split merges in
- We can punt it to the design system team who will componentize the header

> Are we owners of the Sign in modal? If so:
>
>5. Modal
>Sign in modal does not use a component but should use the [v3 modal](https://design.va.gov/components/modal#examples---v3)
>6. Telephone
>There are phone numbers inside the modal that should be using [the v1 component](https://design.va.gov/components/telephone)

I don't actually know if we are the owners of the sign in modal. If we are: we cannot do this right now because this modal lives in the header, and thus the injected header still shares this code. Same options as above.

**Comment by FranECross** [comment]
Replying to comment above... @jilladams  and @laflannery, I would love if you'd vet my reply below for accuracy and to see if it makes sense. Thanks in advance!

**Search Input:** I think we should punt it to the design system team for when the componentize the header

**Sign in modal:** I don't believe we are owners - looking at this [README](https://github.com/department-of-veterans-affairs/va.gov-team/blob/9770d11e7c4922ed0b778a759b78f2c24d01535e/products/public-websites/README.md)

**Comment by jilladams** [comment]
Don't disagree, in theory --  Identity owns the sign-in modal, and we could ask DS for help on Search input. But: in practice, DS is driving deadlines, so my main concern would just be that we need confirmation from those teams that they can handle these pieces by the deadlines. If not, we may need to do the work. And the header componentization piece is almost certainly not gonna get done before the other component deadlines, I think? 

Happy to help reach out about that if you'd like. We know DS folks, and the modal people are in #vsp-identity. Joe Niquette is the person we talk to most from there.

**Comment by laflannery** [comment]
FWIW, my handoff notes to the DST included recommendations for the Search, and suggested they "align" with the component- whether then embed a component within their new componentized header that's up to them but it was mentioned. I did not mention the modal at all in those notes

**Comment by randimays** [comment]
@jilladams Would you mind reaching out to DST and Identity team about those two components, please? Worth mentioning: the search dropdown input doesn't currently use a design system component, so deprecation of v1 components will not affect it. I'm fine with picking up the sign in modal, provided the identity team can help support when it comes to testing.

**Comment by jilladams** [comment]
Asked Identity about modal: https://dsva.slack.com/archives/CSFV4QTKN/p1709239337204619

**Comment by jilladams** [comment]
Search Q to DST (and thanks Randi for chipping in there already): https://dsva.slack.com/archives/C01DBGX4P45/p1709240254379689

**Comment by jilladams** [comment]
Updated ticket body: 
1. Search - we still may end up needing to do this component piece, but I think we should break it out of this ticket into its own, since the timing of it is hinging on convos with DS team around componentizing the header, and it's not clear when we should do it still. 
2. Identity team owns the sign in modal, and they similarly are holding on the V3 stuff til the injected header destiny is handles, since they have the same problem re: web components in the header breaking on injection. That's fully out of scope for us, though, so noted that in ticket.

@laflannery @randimays lemme know if you have questions / concerns on any of that. @FranECross lemme know if you're ok to stub the search related ticket based on these notes and the slack thread, or if you'd like me to do that, fine either way.

**Comment by FranECross** [comment]
@jilladams No questions or concerns! I'm happy to stub out the ticket, and of course, ya'll feel free to edit it afterwards. Thanks for this info!

**Comment by FranECross** [comment]
Ticket created #17395

**Comment by randimays** [comment]
Update: we are splitting the email signup component upgrade to another ticket: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17568 it is not a straightforward conversion so it will require more focus.

**Comment by randimays** [comment]
The work for this is in PR reviews, but we are experiencing a lot of issues getting CI to pass / review instances to work. If they aren't working tomorrow, I'll spin up an ngrok to get reviews.

**Comment by randimays** [comment]
Validated successfully in production. Closing!
