### ISSUE TITLE
Post vets-website deploy warnings and failures to #cms-support

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#1727]
[See slack message here](https://dsva.slack.com/archives/CBU0KDSB1/p1588904843257800)

![Slack___vfs-engineers___Digital_Service___VA.jpg](https://images.zenhubusercontent.com/5d6e57ad330f64311395f08b/ee877055-8378-467e-bdc4-d29d79b87001)

The CMS team fields a lot of questions from editors wanting to see their content on va.gov. We’d love to see these messages from #vfs-engineers (both the “stand-by” 5 minute warning and the production deploy failures) over to #cms-support as well, since this has an impact on editors who are waiting for their content to go out. 

From Karl Brown: 
> I think this happens here: https://github.com/department-of-veterans-affairs/devops/blob/09d2feba4e236743e8e0ce28fd15fd01e87de770/ansible/Jenkinsfiles/deploys/warn-release-deploy
> as far as I can tell, this is a somewhat generic job that's used for a few apps, but it is configurable for one channel. If you want it sent to two channels you'd have to edit that Jenkinsfile and the seed jenkins file to add that feature (https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/jenkins-vetsgov/seed_job.groovy)

**Comment by kevwalsh** [comment]
If this is an 8, it's low priority.

**Comment by indytechcook** [comment]
I put an 8 mostly because posting to dual channels might cause a refactor.  It actually might be quicker but we have plenty to do :)

**Comment by jonpugh** [comment]
Creating github deployments is as easy as any other API call:

https://developer.github.com/v3/repos/deployments/#create-a-deployment

I have code to do that in the `devshop/github-api-cli` package, but it's hard coded into Commands class.

The functionality of "startDeployment" methods should be pulled into another class, then you could easily wire up the form submit to the GitHubApi::startDeployment() method...


@indytechcook , remember the GitHubAwareTrait?

**Comment by jonpugh** [comment]
From https://github.com/KnpLabs/php-github-api/blob/master/doc/repo/deployments.md#create-a-new-deployments

```
$data = $client->api('deployment')->create('KnpLabs', 'php-github-api', array('ref' => 'fd6a5f9e5a430dddae8d6a8ea378f913d3a766f9'));

```

**Comment by ElijahLynn** [comment]
@swirtSJW is suggesting that when this it would be more useful to also describe _why_ in the notification. e.g. broken links or another reason. So that if it is a broken link, maybe an action by the editor could be taken to resolve it.

**Comment by jonpugh** [comment]
FYI: https://github.com/opendevshop/devshop/blob/1.x/src/DevShop/Component/GitHubApiCli/README.md#github-deploymentstart

Once `deployment:start` command is run, the github "Deployment ID" is saved in git config.

So in theory, the Drupal site could access that Deployment ID and then post an update to it with the details of what went wrong (using the core GitHub API class or the DeploymentsCommands class.

See GIT_CONFIG_DEPLOYMENT_ID_NAME: https://github.com/opendevshop/devshop/blob/1.x/src/DevShop/Component/GitHubApiCli/Commands/DeploymentsCommands.php#L140

So in theory, when a thing fails, CMS code could shell exec `github deployment:update` (to automatically use the deployment ID) and then run a CURL or PHP command to ping slack. 

Or, code could extract the deployment ID from git config and do whatever it wants.

That way the deployments API would have the data about what went wrong, and you can have total control over what gets sent to slack.

**Comment by oksana-c** [comment]
related to #3124

**Comment by acrollet** [comment]
Obviated by newer issues.
