### ISSUE TITLE
[Search] [Design] Consider not allowing blank Global search submissions

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#17286]
## Description 
Currently the global search allows submission on a blank search, meaning I can just submit the form having not typed anything into the field. It brings me to the search results page with an error displayed:
<img width="829" alt="Screenshot 2024-02-19 at 1 17 46 PM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/106678594/937fe4f2-3534-4e74-a187-9fd363863fab">

I mentioned this to Randi and Jordan and they both agreed that allowing this was strange and the better UX would be to not allow this. It would be a good consideration for an improved Veteran experience to review this functionally and adjust accordingly.

When a user attempts a search without entering a search term from both homepage search fields, user is taken to global search page with this messaging. 

## NEW design and copy 
[Figma design](https://www.figma.com/design/d9CbnZ16tWcFgWmfMiuf9D/Search-UI?node-id=14-2610&t=4jbGPzAoeUetc0hj-1)

![Screenshot 2024-06-26 at 11 46 48 AM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/137226108/7bb19ca2-ff3c-49cf-89bb-26cdb9ba1da5)

## Acceptance Criteria
- [x] Design and text provided wherein a user isn't able to submit a blank search
- [ ] Tag @FranECross to create a front end ticket for the actual implementation

## Team
Please check the team(s) that will do this work.

- [ ] CMS Team
- [x] Public Websites
- [ ] Facilities
- [ ] Accelerated Publishing

**Comment by FranECross** [comment]
@thejordanwood I changed this to a Design ticket, and added AC to create the design/text, and then to tag me so I can create a front end ticket. Thanks!

**Comment by davidmpickett** [comment]
My estimate for this would be a 3. @thejordanwood might call it a 2 though

**Comment by FranECross** [comment]
@thejordanwood I'm setting at 3, but feel free to alter the estimate! Thanks @davidmpickett for the review and estimate.

**Comment by thejordanwood** [comment]
@FranECross A 3 is good for this!

**Comment by aklausmeier** [comment]
assigned to self, removed points

**Comment by aklausmeier** [comment]
@FranECross design is complete, ticket updated, tagging you to spin up FE ticket

**Comment by FranECross** [comment]
FE ticket created [[Search] [FE] Implement new text/design for blank search submissions#18496](https://app.zenhub.com/workspaces/vagov-sitewide-product-team-6645154188a81a1f7a0a9464/issues/gh/department-of-veterans-affairs/va.gov-cms/18496) and moved into Next refinement.
