### ISSUE TITLE
Unable to update operating status

### ISSUE THREAD

**Issue by ian-sears** [department-of-veterans-affairs/va.gov-cms#17289]
## User Story or Problem Statement
The Editor has tried multiple times from both Chrome and Edge to update the operating status of our Norman clinic and it gives an error saying the system is unavailable at this time and to try again later. 

## Description or Additional Context 
https://www.va.gov/oklahoma-city-health-care/locations/norman-va-clinic/
User/Editor: phillip.ybarra@va.gov
Jira TT#: https://va-gov.atlassian.net/browse/VAHELP-7061
prod.cms URL: https://prod.cms.va.gov/node/7236

-Ian Sears [ian-sears] in CMS VA VFS CMS Drupal Help Desk support

## Acceptance Criteria
- [ ] Editor/User [phillip.ybarra@va.gov] is able to alter the facility Operating Status from Closed to Open as needed.

## Team
Please check the team(s) that will do this work.

- [x] CMS Team
- [ ] Public Websites
- [x] Facilities
- [ ] Accelerated Publishing

**Comment by edmund-dunn** [comment]
Issue in core is here https://www.drupal.org/project/drupal/issues/3285657. Applied the patch. 

I would surmise that the revision created by the migration somehow conflicted with the revision created by the editor.
