### ISSUE TITLE
R&S search unit test reported flaky & disabled

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#17284]
## Description

- Test in question: `src/applications/resources-and-support/tests/components/ResourcesAndSupportSearchApp.unit.spec.jsx'
- unit test flaky disabled report: https://depo-platform-documentation.scrollhelp.site/developer-docs/currently-disallowed-unit-test-specs-on-va-gov

Timebox this as a discovery spike. 

## ACs
- [ ] Test passes consistently and/or thread with Platform support has been opened for Plat investigation into why we can't repro the errors and test is removed from flaky list
- [ ] If this needs fixed, create an issue and pull in to fixc.

**Comment by FranECross** [comment]
Jill noticed this on Monday 2/19; test disabled.

**Comment by jilladams** [comment]
No longer reported as flaky in the 2/27 listing of flaky tests. 🙃  Closing. (FYI @FranECross )
