### ISSUE TITLE
Discovery for VA Health Chat and VA Health Connect research

### ISSUE THREAD

**Issue by ALogsdon3** [department-of-veterans-affairs/va.gov-cms#17282]
### User story
**AS A** Researcher
**I WANT** to see what we know and could learn with VA Health Chat research
**SO THAT** we can provide value

Research Discovery is a time to establish the fundamental approach for a research initiative. Potential tasks may include the following:

**What do we want to know?**
- [x] Re-align with Sitewide UX Lead, Product Manager, and Product Owner on the high-level purpose and scope of the research
- [x] Review Product Outline and [Michelle's mural ](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1695664515308/a963ef125f7542f67e962ca83a8f25b368180618?sender=u3f35bedf61955cb051f44770)to re-acquaint self with background context
- [x] Draft big picture research questions

**Has anyone else researched this before?**
- [x] Review previous research on this product, including [previous discovery work ](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1699650112593/672d59e5ac915c73c1dfd8d6326fcff277bc28db?sender=u3f35bedf61955cb051f44770)
- [x] With UX Lead, connect with VAMC health chat team for product-specific research insights
- [x] Summarize findings from research review

**How might we learn more?**
- [x] Consider methodologies - do we have the right tools to build a useful prototype?
- [x] Consider participants - do we have access to the right users?
- [x] Consider timeline - how long will this take? how much time do we have?

## Possible Acceptance Criteria
- [x] High-level scope of research is drafted and agreed upon
- [x] Subsequent tickets are created

**Comment by ALogsdon3** [comment]
I think the very first thing I need to clarify before getting too far into this discovery is how things have changed since [this comment was made](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16008#issuecomment-1795812019) on #16008. That comment from @mmiddaugh refers to a comment on [thisCAIA Support Request ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/68030), but the link takes me to the top of the ticket, so I'm not sure which comment is being referred to. 
What I do recall at the time we tabled this work in the fall was that CAIA had determined a path for us to follow for where to include information about health chat options. I understand that the various chat services are becoming more integrated, but it's still unclear to me how that changes where we would put the link on the page. 
CC @aklausmeier because this might inform our conversation Tuesday morning.

**Comment by ALogsdon3** [comment]
I've spent  some time on this the past two days and had a 1:1 with @aklausmeier today to align our thinking. 

Based on current information, here's what I'm thinking in terms of scope for a research project:
### Research goal
Understand where Veterans expect contact methods for their healthcare team to be located on VAMC pages. 

### Methodology
A 2- (almost 3-) phase study...
- ...starting with an **unmoderated tree test** to determine where Veterans expect to find contact methods (VA health chat and VA health connect) within the IA of the VAMC pages. If we're satisfied with the data that comes out of this, we can add the link to VAMC pages. 
- After **analyzing GA and domo post-launch** (this is the "almost 3-" bit), we can decide whether we need more context for how it's performing. 
- If do determine we need more context (or if the health chat problem space evolves and surfaces new questions), we can launch a **usability study or user interviews**, depending on the research goals we identify. 

### Benefits of starting with unmoderated tree testing
- Can test **more than one path at a time**
- Will test a larger sampling of Veterans (at least 50 people)
- Can work on other research projects while test is running (2-week period)
- Post-study analysis is faster because output is mostly quantitative and provided by vendor

### Next steps 
If we agree this is the best path forward, the next steps include:
- deciding what link placements we want to test (possibly in concert with @thejordanwood and/or @davidmpickett?
- creating site tree for the test
- drafting research plan and conversation guide (the latter will consist of the tasks for the tree test)

@mmiddaugh @xiongjaneg @jilladams

**Comment by aklausmeier** [comment]
One additional consideration @ALogsdon3 and I discussed is a need to represent the accordion sections on a facility landing page into the tree test.

**Comment by aklausmeier** [comment]
Adding links to previous discovery and research work for quick reference:

- Alexis' previous [UX Discovery ticket for Health Chat](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15704) (has a lot of context)
- Existing [research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/facility-locator/research/user-research/VAMC-communications-methods/Research-Plan.md) and [conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/facility-locator/research/user-research/VAMC-communications-methods/Conversation-Guide.md created before this effort was parked and can be used as a starting point and revised so we are not starting from scratch
- [Link to recommendations from health chat discovery](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/medical-centers/discovery/health-chat-discovery.md#recommendations) (from 2021, at this time a tree test was recommended)

**Comment by aklausmeier** [comment]
**What we know:** 

- Some facilities and systems are already adding VA Health Chat app OR VA Health Connect (usually not both) to their pages, it's inconsistent across sites. This is driving the need for research
- Tree test will allow us to take a non-biased approach to where this should live and allow a broad scope for all modalities of communication preferences.

**Examples in the Wild** that @mmiddaugh has gathered to date

- Albany health care publicizes the health connect number on [their main system page](https://www.va.gov/albany-health-care/), on their individual facility pages, such as [Samuel S. Stratton Department of Veterans Affairs Medical Center](https://www.va.gov/albany-health-care/locations/samuel-s-stratton-department-of-veterans-affairs-medical-center/), and on their [Contact us page](https://www.va.gov/albany-health-care/contact-us/)
- Houston health care publicizes the number on their [Make an appointment page](https://www.va.gov/houston-health-care/make-an-appointment/) and [Pharmacy page](https://prod.cms.va.gov/houston-health-care/pharmacy) but not in Location and contact information for the system or individual facilities
- Finger Lakes health care includes the VA health connect number in Location and contact information blocks and in the [Advice nurse accordion](https://www.va.gov/finger-lakes-health-care/locations/bath-va-medical-center/#advice-nurse) for facilities, such as Bath VAMC
- South Texas includes the number in Location and contact information blocks and on a specific [Urgent care page](https://www.va.gov/south-texas-health-care/programs/urgent-care/)
- Cincinnati health care has a [Health chat page visible from within the Programs menu](https://www.va.gov/cincinnati-health-care/programs/va-health-chat/)
- VA Butler has a spotlight on the health service page at the system level
- [Northern California health care](https://www.va.gov/northern-california-health-care/) includes VA health chat in their system home page spotlight
- Miami health care has a featured story about VA health connect on [their home page](https://www.va.gov/miami-health-care/) right now and include the number in Location and contact information blocks at system and facility level, such as [Bruce W. Carter Department of Veterans Affairs Medical Center](https://www.va.gov/miami-health-care/locations/bruce-w-carter-department-of-veterans-affairs-medical-center). It is also listed on the [Contact us page](https://www.va.gov/miami-health-care/contact-us/)

**Comment by aklausmeier** [comment]
@ALogsdon3 

I fully support your research plan. After the tree test we can revise next steps if/as needed.

We can probably iterate on one of the "in the wild" examples above (copy and iterate in Staging) post tree test to help us expedite a usability test quicker.

**Comment by ALogsdon3** [comment]
@aklausmeier Thanks, Amanda! And thank you for adding all that background/context to the ticket. And great idea about the "in the wild" examples. :)

**Comment by aklausmeier** [comment]
@ALogsdon3 Chatted with our OCTO partners on the Health team. There is no prior research related to Health Chat app or Health Connect clinical center (phone) that was done by OCTO. Methods of communications are owned by various offices and none w/in OCTO so the what and who owns it is out of our control. How and where we communicate these various communication methods on the Facilities pages is somewhat w/in our control.

**Comment by jilladams** [comment]
@ALogsdon3 for end of sprint: could you update what's left here vs. rolling to new ticket? I see the draft research plan ticket, but not sure what remains here to be done, if anything. (cc  @xiongjaneg)
