### ISSUE TITLE
[Search.gov Monitor] Set up a new monitor on the fwdproxy health check for search.gov

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-cms#17298]
## Description

Set up a new monitor on the fwdproxy health check for search.gov (example metric) and then make the VA.gov search monitors dependent on it.

This request is based on this Slack Thread, and due to the number of outages we're experiencing from the Search.gov side, causing us to see a bunch of 503s indicating their service was down.

See Slack [thread](https://dsva.slack.com/archives/C05THHJHH2R/p1707836489611149?thread_ts=1707783323.864979&cid=C05THHJHH2R)

### User story

**AS AN** engineer responsible for troubleshooting errors for the VA.gov Search feature
**I WANT** a monitor specifically for a health check for search.gov
**SO THAT** we know whether it's the backend causing issues, or search.gov itself

## Acceptance criteria

- [ ] New datadog monitor is created 
    - [ ] tags should match existing PW monitors for Search
    - [ ]  monitor should be added to the Public Websites dashboard
- [ ] [Search monitoring doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/on-site-search/engineering/monitoring.md) is updated with details about the new monitor (link, how to triage, etc)

**Comment by jilladams** [comment]
If we aren't sure what it means here to monitor the fwdproxy, we can tap Adrian or the #public-datadog channel for help.

**Comment by jilladams** [comment]
@ariperez this is the main outstanding Datadog ticket where we could use your expertise if the search error msg ticket doesn't work out, or after that's done, either way.

**Comment by jilladams** [comment]
We didn't have ACs on here -- added a few. @ariperez holler if you have questions about them.

**Comment by ariperez** [comment]
https://vagov.ddog-gov.com/monitors/210576

Created monitor and refining notification criteria. Still establishing whether this monitor is providing useful notification of 503 errors.
