### ISSUE TITLE
Update links in Lovell Tricare experience

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-cms#17299]
## Description
The [MHS GENESIS Patient Portal](https://my.mhsgenesis.health.mil) will replace the TRICARE Online Secure Patient Portal as a result of the Cerner/Oracle health transition. The main portal link will redirect to a [log on](https://myaccess.dmdc.osd.mil/identitymanagement/app/login) page. Top task links in the Lovell Tricare experience should point to a relevant interstitial information page or to the new patient portal. 

`Timing is important: 
Changes occurring before the Cerner/Oracle transition should direct Tricare beneficiaries  to the TRICARE Online Secure Patient Portal. 
After the Cerner/Oracle cutover, links should direct to the MHS GENESIS Patient Portal.`

## Current behavior

| Tricare page | Top task link | Destination | Changes needed? 
| --- | --- |  --- | --- |
| <ul><li>[TRICARE Main system page](https://www.va.gov/lovell-federal-health-care-tricare/) </li><li>[Locations page](https://www.va.gov/lovell-federal-health-care-tricare/locations) </li><li>[Health services page](https://www.va.gov/lovell-federal-health-care-tricare/health-services/) </li><li>[Contact us page](https://www.va.gov/lovell-federal-health-care-tricare/contact-us/) </li><li>[Programs](https://www.va.gov/lovell-federal-health-care-tricare/programs/)</li></ul>| Make an appointment | [Make an appointment page](https://www.va.gov/lovell-federal-health-care-tricare/make-an-appointment) | will need changes
|<ul><li>[TRICARE Main system page](https://www.va.gov/lovell-federal-health-care-tricare/) </li><li>[Locations page](https://www.va.gov/lovell-federal-health-care-tricare/locations) </li><li>[Health services page](https://www.va.gov/lovell-federal-health-care-tricare/health-services/) </li><li>[Contact us page](https://www.va.gov/lovell-federal-health-care-tricare/contact-us/) </li><li>[Programs](https://www.va.gov/lovell-federal-health-care-tricare/programs/)</li></ul> | Register for care | [Register for care page](https://www.va.gov/lovell-federal-health-care-tricare/register-for-care) | Locally editable by Lovell
| <ul><li>[TRICARE Main system page](https://www.va.gov/lovell-federal-health-care-tricare/) </li><li>[Locations page](https://www.va.gov/lovell-federal-health-care-tricare/locations) </li><li>[Contact us page](https://www.va.gov/lovell-federal-health-care-tricare/contact-us/) </li><li>[Programs](https://www.va.gov/lovell-federal-health-care-tricare/programs/)</li></ul> | View all health services | [Health services page](https://www.va.gov/lovell-federal-health-care-tricare/health-services) | No changes needed
| [Health services page](https://www.va.gov/lovell-federal-health-care-tricare/health-services/)  and Individual facility pages, including <ul><li>[Captain James A. Lovell Federal health care](https://www.va.gov/lovell-federal-health-care-tricare/locations/captain-james-a-lovell-federal-health-care-center/) </li><li>[Naval Great Lakes Burkey Mall Pharmacy](https://www.va.gov/lovell-federal-health-care-tricare/locations/naval-great-lakes-burkey-mall-pharmacy)</li><li>[USS Osborne Dental Clinic](https://www.va.gov/lovell-federal-health-care-tricare/locations/uss-osborne-dental-clinic)</li><li>[USS Red Rover](https://www.va.gov/lovell-federal-health-care-tricare/locations/uss-red-rover)</li><li>[USS Tranquillity](https://www.va.gov/lovell-federal-health-care-tricare/locations/uss-tranquillity)</li><li>[Zachary and Elizabeth Fisher Medical and Dental Clinic](https://www.va.gov/lovell-federal-health-care-tricare/locations/zachary-and-elizabeth-fisher-medical-and-dental-clinic)</li></ul>| Pharmacy | [Pharmacy page](https://www.va.gov/lovell-federal-health-care-tricare/pharmacy/)| Locally editable by Lovell
## Problems to solve
The `Make an appointment` top task appears on both VA and Tricare pages and directs to an interstitial page which contains VA relevant details. In particular the "Before you make an appointment" box and the "Make an appointment online" widgets are VA-specific. 

**How might we direct Tricare beneficiaries to the MHS Genesis portal instead?** 

These top tasks also exist on the [Programs](https://www.va.gov/lovell-federal-health-care-tricare/programs/) and [Contact us](https://www.va.gov/lovell-federal-health-care-tricare/contact-us/) pages. This inconsistent logic is documented in a separate issue (Fix inconsistent logic in VAMC pages display of Top task links #15567). If we aren't able to address this logic simultaneously, we should ensure they direct correctly in the meanwhile. 

## Acceptance criteria
- [ ] On the Lovell Tricare page, the "Make an appointment" top task link on the following pages links to the [MHS GENESIS Patient Portal](https://my.mhsgenesis.health.mil).
  - [ ] [TRICARE Main system page](https://www.va.gov/lovell-federal-health-care-tricare/)
  - [ ] [Locations page](https://www.va.gov/lovell-federal-health-care-tricare/locations)
  - [ ] [Health services page](https://www.va.gov/lovell-federal-health-care-tricare/health-services/)
  - [ ] [Contact us page](https://www.va.gov/lovell-federal-health-care-tricare/contact-us/)
  - [ ] [Programs](https://www.va.gov/lovell-federal-health-care-tricare/programs/)
- [ ] For the Lovell Tricare page, the transitioning to Cerner EHR toggle being present in staging is confirmed.
 - [ ] If not, follow up tickets are stubbed.

**Comment by xiongjaneg** [comment]
Historical comments from related ticket #17107 

The "Manage Your Health Online" section (below) is currently hidden for Lovell TRICARE pages (src/site/layouts/health_care_region_page.drupal.liquid#55). It will need to be made visible for them
Screen Shot 2024-01-12 at 1 00 22 PM
The links in this section will need to check if a page is a Lovell TRICARE page and if Cerner is on. If they both are, the topTaskUrl filter will need to add additional logic that changes these links to the MHS Genesis links. It will just need to build on the existing conditional logic.

The links on the template should make any needed TRICARE-specific changes, like changing visible instances of "VA" to "TRICARE" as needed.

Questions that need Answering
- What are the specific MHS Links that need to be used for each link label?
- What was the specific reason that these links were hidden on TRICARE pages? Will they still need to be hidden from TRICARE pages under some circumstances, or will this change mean they can always be visible?
- Do some of the six links in question need to be hidden under specific conditions, or can all six always remain visible together like they do now?
- How much will we need to coordinate with public websites and similar Cerner changes they've made on their widget?

~~Michelle is waiting to hear back from a Lovell contact that she can run these questions by. Once they're answered, then there should be enough information to write out a ticket.~~ The answers to Michelle's questions are noted in the body of this ticket.

**Comment by mmiddaugh** [comment]
Following a conversation with Lovell, we need to 

- update the URL for the "Make an appointment" top task on Tricare pages (only) to the MHS general link
- update the label from "Make an appointment" to "MHS Genesis Patient Portal" 

changes should impact the Tricare experience only and on all pages where it currently appears

Lovell side

- Register for care top task link  should continue to point to interstitial page which Rowan at Lovell has been updating in cooperation with Humana rep
- Pharmacy top task link can also continue to point to the interstitial page which Rowan will revisit for content
- Rowan will also review Medical records and Billing and insurance pages and update content as needed.

**Comment by eselkin** [comment]
@xiongjaneg Programs as a submenu on Lovell is not TRICARE but Federal (both TRICARE and VA) so they cannot be changed. @mmiddaugh requested that we move the ticket into next sprint to hide top task menu/items on Program pages since they shouldn't be shown anyway similar to events pages, etc.

**Comment by eselkin** [comment]
I'm just verifying that the links to MHS Genesis don't display on prod builds currently.

**Comment by mmiddaugh** [comment]
Confirmed expected post-launch behavior, based on `converting-to-cerner` Drupal toggle
- Staging [TRICARE](https://www.va.gov/lovell-federal-health-care-va) experience confirmed on main system page, facility pages, locations page, and health services pages
   - the Make an appointment link is replaced by MHS Genesis Patient Portal and points to new .mil link 
   - new link gets keyboard focus
- Staging  [VA](https://staging.va.gov/lovell-federal-health-care-va) experience confirmed on main system page, facility pages, locations page, and health services pages
   - the Make an appointment link is present and points to interstitial [Make an appointment page](lovell-federal-health-care-va/make-an-appointment/) 
   - Medical records and Register for care pages will be locally updated
-Prod [TRICARE](https://www.va.gov/lovell-federal-health-care-tricare) and [VA](https://www.va.gov/lovell-federal-health-care-va) experiences confirmed on main system page, facility pages, locations page, and health services pages
  - Make an appointment links are present in both experiences and point to the appropriate interstitial Make an appointment pages


<details>
<summary> Staging screenshots </summary>

<img width="1629" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeUxIQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--815eec8698863b1e4e01ea74259be7a3e1278352/image.png" alt="image.png" />

<img width="1078" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeURIQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--974e1a356d2da3471740356a7b20cec44ffb4620/image.png" alt="image.png" />

<img width="821" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeUhIQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fbd058377246c12b9cc01281de9a5a31d4840788/image.png" alt="image.png" />


</details>

<details>
<summary> Prod screenshots </summary>

<img width="893" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeGpIQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--dbb851bea8568e6af392c22c9ab07d1f6dfa5c61/image.png" alt="image.png" />

<img width="867" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeG5IQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--447a106464835c26b467a90a9bd281f9f887220e/image.png" alt="image.png" />


</details>

---

Note: fast follow: **#15567 Top task links on About [VAMC System] pages are removed from Programs pages**

**Comment by xiongjaneg** [comment]
Confirmed in prod after Michelle flipped the switch todayu:

[VA TRICARE](https://www.va.gov/lovell-federal-health-care-tricare/) experience confirmed on main system page, facility pages, locations page, and health services pages
the Make an appointment link is replaced by MHS Genesis Patient Portal and points to new .mil link
new link gets keyboard focus

[Lovell VA](https://www.va.gov/lovell-federal-health-care-va/) experience confirmed on main system page, facility pages, locations page, and health services pages
the Make an appointment link is present and points to interstitial [Make an appointment page](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/lovell-federal-health-care-va/make-an-appointment/)
