### ISSUE TITLE
FAQs with Reusable Q&A group: Q&A group Introduction doesn't display in the FE

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#17319]
## Description or Additional Context 

Reported by CMS Helpdesk here: https://dsva.slack.com/archives/CDHBKAL9W/p1708638408484809

If a Reusable Q&A Group is added to an FAQ, with a Q&A Group Header and Introduction, the Header publishes to the FE, but the Introduction does not. Looks like this field is not handled in `content-build/src/site/layouts/faq_multiple_q_a.drupal.liquid`.

FAQ node: https://prod.cms.va.gov/node/63990/edit -- includes a Reusable Q&A group, with a Title and Introduction populated.
FE Page: http://preview-prod.vfs.va.gov/preview?nodeId=63990

![Screenshot 2024-02-22 at 2 40 08 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/85581471/9c0c4e39-2302-4442-a118-35cf2de610ee)

![Screenshot 2024-02-22 at 2 41 38 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/85581471/8924e366-bde8-46fb-87c9-6fca1c8e2746)

## Acceptance Criteria
- [ ] Anywhere Reusable Q&A groups appear, Q&A Group Header & Introduction should appear if they are populated, across content types. 
    - [ ] FAQ
    - [ ] Campaign Landing Pages
    - [ ] Benefit Detail Pages
    - [ ] Resources & Support
 - [ ] When verified on Prod, update https://dsva.slack.com/archives/CDHBKAL9W/p1708638408484809 and @ Ian Sears, so he can notify the editor this is resolved.

**Comment by FranECross** [comment]
@randimays @chriskim2311 @ariperez Are you able to async prefinement of this ticket so that we can consider it for next week's sprint? Thanks in advance! cc @jilladams

**Comment by chriskim2311** [comment]
For this ticket we would need to update the graphql query for `field_q_a_groups` inside `faqMultipleQa.graphql.js` with the following field
```
    fieldRichWysiwyg {
      value
      format
      processed
    }
```
Then update the `faq_multiple_q_a.drupal.liquid` file to render the introduction.

**Comment by FranECross** [comment]
Ticket has been refined and is at the top of Stretch/Next Sprint.

**Comment by chriskim2311** [comment]
@FranECross @jilladams FYI This PR is approved and tested. There's an issue blocking the merging of content build PRs in the CI pipeline due to a DST component issue with cypress tests. Plat ticket was opened today to try and get a fix out for tomorrow's release. https://dsva.slack.com/archives/CBU0KDSB1/p1709227437888479

**Comment by chriskim2311** [comment]
PR was able to get merged and will go out with today's deploy!

**Comment by jilladams** [comment]
Noting: content-build has had deploy issues. 
Support thread: https://dsva.slack.com/archives/CBU0KDSB1/p1709576168347899
And I let CAIA folks know about that / the delay on shipping, here: https://dsva.slack.com/archives/CDHBKAL9W/p1709585053570089?thread_ts=1708638408.484809&cid=CDHBKAL9W

**Comment by chriskim2311** [comment]
Notified slack thread and verified in prod, closing!
