### ISSUE TITLE
Show users with access on each section page

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#1731]
## User Story or Problem Statement

As an editor of a section, i want to know who has access to a section. 

## Acceptance Criteria
On /section/veterans-health-administration/vha-facilities/va-pittsburgh-health-care:
* a list of users assigned to that section is shown

**Comment by msbtterswrth** [comment]
Currently unable to show users assigned to parent sections (ex: VISN 5 user on Maryland page) but we may be able to use something like https://www.drupal.org/project/workbench_access/issues/1191484#comment-11319487 to add contextual filters for that!

**Comment by EWashb** [comment]
Not currently within scope
