### ISSUE TITLE
Show child sections on user profile page

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#1732]
## User Story or Problem Statement

As a member of a Section that has child sections, i want to see the child sections on my user profile, so i can access them with just one click. 

## Acceptance Criteria
* when [viewing Laura Walsh's profile](https://prod.cms.va.gov/user/1319), you see VBA Benefits hubs _and_ its six children

**Comment by oksana-c** [comment]
completed in a different ticket
