### ISSUE TITLE
Site_alert breaks dblog report screen

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#1733]
**Describe the defect**
https://www.drupal.org/project/site_alert/issues/3134602

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information if relevant, or delete):**

**Additional context**

**Comment by oksana-c** [comment]
@swirtSJW I can't reproduce this bug on staging and I see you commented 2 months ago that this issue is still unresolved here https://www.drupal.org/project/site_alert/issues/3134602#comment-13857239 .
Can you please post a screenshot if this is still happening? ty
