### ISSUE TITLE
Design updates for VAMC non-clinical contact information

### ISSUE THREAD

**Issue by thejordanwood** [department-of-veterans-affairs/va.gov-cms#17342]
## User Story or Problem Statement
In [#16810](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16810) it was decided that the front end and Drupal experience for VAMC non-clinical pages ([Billing and Insurance](https://www.va.gov/pittsburgh-health-care/billing-and-insurance/), Medical Records, and Register for Care pages) could be improved to create a better structure for contact information. 

When doing this work, think about short term and long term updates that could be made.

## Design
Front end: [VAMC CMS Master ](https://www.figma.com/file/ikCp2eOubIgbN1TwyEYIrN/VAMC-CMS-Master?type=design&node-id=0%3A1&mode=design&t=6SSho1Xd97CWrdR9-1)
Drupal: [VAMC Facilities](https://www.figma.com/file/bwnxdqh3b7W7Xp6KuQ4Sab/VAMC-facilities?type=design&node-id=6%3A2431&mode=design&t=4SRqbQ8MOx69DY8r-1)

## Situations to solve for

This is a preliminary list. More situations may be identified during discovery.

- 1 vs 2 service locations at one facility
- Multiple facilities listed on a page
- Drupal fields left blank (For example, the "Name of office or location" field in the address section) (Dave created [a ticket for this for Drupal engineering](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17380), will need a design review for possible changes on FE)
- Labels being duplicated (For example, the "Main phone" label being used multiple times and hours)
- Visual hierarchy within contact information, use of headers and paragraphs

## Acceptance Criteria

- [x]  Review current layout of contact info on VAMC non-clinical pages
- [x]  Document recommendation for Front End designs in Figma
- [x]  Document recommendation for Drupal designs in Figma
- [x]  Consult with engineering for feasibility and opportunities for conditional logic
- [x]  Identify and document Now, Next, Later
- [x]  Requires content design review
- [x]  Requires accessibility review
- [x]  Requested or scheduled UX Lead review, typically 48 hours turnaround (could be in UX Sync)

**Comment by aklausmeier** [comment]
Example 1: https://www.va.gov/butler-health-care/locations/abie-abraham-va-clinic/#pharmacy

Problems:

- Main phone and Hours repeated 3x in Pharmacy accordion
- No visual hierarchy in headings

**Comment by aklausmeier** [comment]
Example 2: https://www.va.gov/washington-dc-health-care/locations/washington-va-medical-center/#transplant-surgery

Problems:

- "Liver Transplant Coordinator" listed twice with different numbers, this may not be fixable but we could inspect help text here
- No visual hierarchy in headings (ex: Appointments and Appointment Line)
- Liver Transplant Coordinators contact information is duplicated in description, might not be a design problem but pointing this out

**Comment by aklausmeier** [comment]
Example 3: https://www.va.gov/washington-dc-health-care/locations/washington-va-medical-center/#mental-health-care

Problems:

- Main phone repeated 2x in Mental Health care accordion
- No visual hierarchy in headings
- 24/7 hours, could we explore some conditional logic where it's kept to one line in a 24/7 use case?

**Comment by aklausmeier** [comment]
Example 4: https://www.va.gov/gulf-coast-health-care/billing-and-insurance/

Problems:

- Main phone and hours repeated 2x w/no visual distinction
- 24/7 hours, could we explore some conditional logic?
- How can we support editors who list 2 sets of hours, there is no label shown on FE to explain the different set of hours

**Comment by mmiddaugh** [comment]
More examples available [in this mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1704815327585/d845c408f86efbd42e554d4854107f055e763ee8?wid=0-1709046831714)

**Comment by thejordanwood** [comment]
Some heading level considerations to keep in mind from [#16144](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16144). 

- [Service location address heading ](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16144#issuecomment-1967961247)
- [Heading level examples across VAMCs](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16144#issuecomment-1969053140)

**Comment by xiongjaneg** [comment]
From Michelle: What's the scope of this ticket?

From Amanda: Jordan and she are meeting to discuss further. The scope will include balancing what engineers can do and timeline.

**Comment by xiongjaneg** [comment]
Please note after further discussion what can be moved to later under later tickets.

**Comment by jilladams** [comment]
From #16144 : this issue also needs to be addressed under this ticket: 

Q: from Dave
> This isn't good, but I don't know how to fix it
> If an editor has entered building name/number or wing, floor or room number, but not Service location address this information now will be floating around without context. Vs on Prod, this information would default to falling under the generic Contact Info header


Proposed Answer: from Eli
> Right now if there's no clinic name but there is subsequent data, we could default to something like:
>     Location Info
> In the header space for that section.

**Comment by davidmpickett** [comment]
Update from meeting with @aklausmeier and @thejordanwood today:
- Jordan will focus on proposing ideal state for FE
- Dave will focus on reviewing specific issues identified in ticket and Mural and making sure they are ticketed

**Comment by davidmpickett** [comment]
@omahane @Becapa I'd like to get your thoughts on an issue Michelle documented about [Office Hours not showing up in Node View when all days are closed/not specified](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1704815327585/d845c408f86efbd42e554d4854107f055e763ee8?wid=0-1709047076643). 

I did a little digging and it looks like this might be the intended functionality of the Office Hours module. In fact this was behavior was introduced as a ["bug fix"](https://www.drupal.org/project/office_hours/issues/2907440). Can you confirm that the Office Hours disappearing from Node Edit in the scenario of no hours specified is part of the module and not something our Drupal implementation is doing intentionally?

I tend to agree with Michelle that having this information disappear in this case is more likely to lead to bad outcomes than the alternative, but before I make that argument upstream, want to make sure I've accurately assessed the situation.

**Comment by davidmpickett** [comment]
@thejordanwood From mural - here's another [specific example](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1704815327585/d845c408f86efbd42e554d4854107f055e763ee8?wid=0-1709056873703)for you to consider of something to defend against when Name of Office or Location is left blank

**Comment by Becapa** [comment]
> @omahane @Becapa I'd like to get your thoughts on an issue Michelle documented about [Office Hours not showing up in Node View when all days are closed/not specified](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1704815327585/d845c408f86efbd42e554d4854107f055e763ee8?wid=0-1709047076643).
> 
> I did a little digging and it looks like this might be the intended functionality of the Office Hours module. In fact this was behavior was introduced as a ["bug fix"](https://www.drupal.org/project/office_hours/issues/2907440). Can you confirm that the Office Hours disappearing from Node Edit in the scenario of no hours specified is part of the module and not something our Drupal implementation is doing intentionally?
> 
> I tend to agree with Michelle that having this information disappear in this case is more likely to lead to bad outcomes than the alternative, but before I make that argument upstream, want to make sure I've accurately assessed the situation.

It looks to me like you are correct. This is coming from the contrib module and not something that we are doing.

**Comment by davidmpickett** [comment]
> > @omahane @Becapa I'd like to get your thoughts on an issue Michelle documented about [Office Hours not showing up in Node View when all days are closed/not specified](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1704815327585/d845c408f86efbd42e554d4854107f055e763ee8?wid=0-1709047076643).
> > I did a little digging and it looks like this might be the intended functionality of the Office Hours module. In fact this was behavior was introduced as a ["bug fix"](https://www.drupal.org/project/office_hours/issues/2907440). Can you confirm that the Office Hours disappearing from Node Edit in the scenario of no hours specified is part of the module and not something our Drupal implementation is doing intentionally?
> > I tend to agree with Michelle that having this information disappear in this case is more likely to lead to bad outcomes than the alternative, but before I make that argument upstream, want to make sure I've accurately assessed the situation.
> 
> It looks to me like you are correct. This is coming from the contrib module and not something that we are doing.

Just discovered that someone else also just came to the same conclusion we did and has started an [upstream patch](https://www.drupal.org/project/office_hours/issues/3423233). Pinged engineers on [Slack](https://dsva.slack.com/archives/C0FQSS30V/p1709659655928739) about how to track that

**Comment by davidmpickett** [comment]
> Update from meeting with @aklausmeier and @thejordanwood today:
> 
> * Jordan will focus on proposing ideal state for FE
> * Dave will focus on reviewing specific issues identified in ticket and Mural and making sure they are ticketed

Progress update - so far I have gone through the **Billing and Insurance** and **Medical Records** examples in the Mural

**Comment by omahane** [comment]
@davidmpickett @mmiddaugh In following up on this behavior, I wanted to see how you wanted to handle the display of unfilled time slots. The default is that they read "Closed."

If I check the box that says, "Show the hours, even when fully empty", then it will say "Closed" on the node:view for each day. If we change the **Empty day notation** to "Hours not provided" or something like that, it will be easier for the editor to know that they need to be filled.

What do you think?

**Comment by aklausmeier** [comment]
@omahane - @thejordanwood has been working on design mockups to address these issues, looping her in in case she has thought through this specific scenario

> I wanted to see how you wanted to handle the display of unfilled time slots. The default is that they read "Closed."

> If I check the box that says, "Show the hours, even when fully empty", then it will say "Closed" on the node:view for each day. If we change the Empty day notation to "Hours not provided" or something like that, it will be easier for the editor to know that they need to be filled.

**Comment by davidmpickett** [comment]
> @davidmpickett @mmiddaugh The module has been updated, and I'm testing it out. In following up on this behavior, I wanted to see how you wanted to handle the display of unfilled time slots. The default is that they read "Closed."
> 
> <img alt="Screenshot 2024-03-07 at 9 01 11 AM" width="641" src="https://private-user-images.githubusercontent.com/766573/310927861-1012b51f-f6cc-4642-b77a-e8d042562ea3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4MzExNDIsIm5iZiI6MTcwOTgzMDg0MiwicGF0aCI6Ii83NjY1NzMvMzEwOTI3ODYxLTEwMTJiNTFmLWY2Y2MtNDY0Mi1iNzdhLWU4ZDA0MjU2MmVhMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwN1QxNzAwNDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04YzUwNzI1MDNmZDMxMzBmNTFkZDc4NzY4ZjZkM2QxNjFmNjIxYjNiNjE5NTZmYzFiZmY5MGRiZGJjOWZlM2Y4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.q2F4hBL8u7YbPCQfURcvmS6ZC1sgjEpI8IU8G1Bw-XE">
> If I check the box that says, "Show the hours, even when fully empty", then it will say "Closed" on the node:view for each day. If we change the **Empty day notation** to "Hours not provided" or something like that, it will be easier for the editor to know that they need to be filled.
> 
> What do you think?

To clarify: which situations does the **Empty day notation** apply to? Is it any instance of a day with no hours provided? or is only for the case of all days being empty? We have lots of instances where something is closed on Saturday and Sunday and leaving the hours blank is the correct way to indicate that.

![Screenshot 2024-03-07 at 11 04 33 AM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/5fd78ea1-a496-4477-b84e-0e4de454002c)

**Comment by davidmpickett** [comment]
@thejordanwood @aklausmeier FYI - As I have been scrubbing through related tickets, I found this [CMS Platform ticket](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14182). Wanted to get your thoughts on how the work Jordan is doing here or in [the larger epic](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17350) can be contributed back to the CMS Design system

**Comment by omahane** [comment]
> To clarify: which situations does the Empty day notation apply to? Is it any instance of a day with no hours provided? 
Yes, it is for each and every **day** that hasn't been filled in. It doesn't have to be more than one or a week. Each will get whatever "Empty day notation" has been set.

**Comment by aklausmeier** [comment]
@davidmpickett I'll reach out to CMS

> As I have been scrubbing through related tickets, I found this https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14182. Wanted to get your thoughts on how the work Jordan is doing here or in https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17350 can be contributed back to the CMS Design system

**Comment by davidmpickett** [comment]
## Work in progress - Roadmap

## Now 
- #17414

## Next
- #17380


## Later

**Comment by jilladams** [comment]
@davidmpickett @thejordanwood For end of sprint: Please update ACs with a new section & points estimate for anything that will over, thank you!

**Comment by davidmpickett** [comment]
Now /next /later Roadmap shared to slack for feedback: https://dsva.slack.com/archives/C0FQSS30V/p1710202980149649

**Comment by xiongjaneg** [comment]
@thejordanwood @davidmpickett I'd forgotten to update the last AC as we'd previously determined, so I've changed it to UX Lead review requested (not finished). If that's been requested, that last AC can be checked and this can be closed. Thank you both!

**Comment by davidmpickett** [comment]
Per [slack thread](https://dsva.slack.com/archives/C0FQSS30V/p1710202980149649), @aklausmeier is working on her final review of @thejordanwood's design work. She and I also have time scheduled tomorrow to talk through my work on the ticketing and Drupal side.

Closing
