### ISSUE TITLE
VAMC System banner alert w. situation updates: Add "select all" option, with overrides

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#17344]
## User story
As a VA owner of an update that should go to all VAMCs, 
I need a way to quickly select all, or almost all, VAMCs for a banner update.

## Description
When big things happen, sometimes we need to post a banner to all VAMC pages, for all VAMC Systems. This requires creating a [new VAMC System Banner Alert with Situation Updates](https://prod.cms.va.gov/node/add/full_width_banner_alert), and clicking 140 boxes to select each VAMC System. In the heat of an urgent update, it would be helpful to be able to click one box to select all VAMC Systems. 

We may also need to select all systems, except 1 or 2. The "select all" should allow then de-selecting one or more systems. (Vs. a radio button all/nothing solution.) For example: "publish to all VAMC Systems except Lovell Tricare" 

Example nodes that have been created for similar updates: 
https://prod.cms.va.gov/vamc-facilities/vamc-banner-alert/2024-02-23/non-va-pharmacy-prescription-issues
https://prod.cms.va.gov/vamc-facilities/vamc-banner-alert/2023-08-10/pact-act-backdated-benefits-deadline-extended

## Acceptance criteria - DRAFT

- [ ] Node add VAMC System Banner Alert with Situation Updates includes an option under "Where will this banner appear?" to allow selecting all systems
- [ ] When the select all option is chosen, all VAMC Systems are selected in the node form. 
  - [ ] On publish, the banner appears on all System pages, as specified (this is an FE AC, and if the GraphQL doesn't change, may not need its own ticket?)
- [ ] When "select all" is chosen, specific VAMC Systems may be de-selected

**Comment by davidmpickett** [comment]
Duplicate with https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14752?

**Comment by jilladams** [comment]
Yep, good catch. Will port my notes to that ticket.
