### ISSUE TITLE
Add left sidebar to Spanish GI Bill eligibility page

### ISSUE THREAD

**Issue by randimays** [department-of-veterans-affairs/va.gov-cms#17347]
## Description
A new Spanish page has been published that needs a left sidebar added for navigation.

Page: https://www.va.gov/education/eligibility-esp/

<img width="140" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/147188767/d8abbb98-2856-4ed9-b933-978186c3de56">

This is a Drupal admin task.

### User story

**AS A** Veteran, their family member, caregiver, or survivor who prefers website text be displayed in Spanich
**I WANT** to see the sidebar navigation in Spanish as well as the associated page I'm viewing
**SO THAT** I don't have trouble understanding what I'm reading or navigating to.

## Acceptance criteria

- [ ] The left navigation for this page is displayed in Spanish

**Comment by FranECross** [comment]
@RLHecht Will you please confirm if the left navigation specifically for this page should display as "Elegibilidad"? Thanks in advance!

**Comment by RLHecht** [comment]
@FranECross yes, that's correct. Thanks for checking!

**Comment by FranECross** [comment]
@RLHecht Just a quick head's up that a variety of work and defects have delayed our work on this. It's in Stretch / Next Sprint to be picked up when possible, but I don't have a good idea of which sprint yet that will be.

**Comment by dsasser** [comment]
@RLHecht 
I setup the sidebar in a Tugboat [here](https://web-jpda5wige5pwclzr1xemzvpiz3j9gnok.demo.cms.va.gov/education/eligibility-esp/). Could you confirm this meets your criteria (screenshot below for convenience)? Thanks!

![Screenshot 2024-04-17 at 2 17 49 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/221539/0b3187f6-540b-46f4-adea-cc865bb0f320)

cc @FranECross

**Comment by dsasser** [comment]
@RLHecht I have made the necessary change on prod so this should go out during the next content release. cc @FranECross

**Comment by dsasser** [comment]
Verified in production:
![Screenshot 2024-04-22 at 8 22 44 AM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/221539/9c155daf-6ba4-4836-9bfd-bb30a3261e0a)
