### ISSUE TITLE
Main phone number does not render correctly on Register for care page

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-cms#17359]
## Describe the defect
The main number for the Bruce B. Downs Boulevard VA Clinic displays as expected in Location and contact information block but not on the Register for care page

## To Reproduce
1. View Drupal node for [Tampa Register for care page](https://prod.cms.va.gov/tampa-health-care/register-for-care)
2. Observe that editor has added a phone number in the contact info block and has specified that the main number should be displayed
3. Go to [Tampa healthcare's Register for care page](https://www.va.gov/tampa-health-care/register-for-care/)
4. Observe that the Main phone number is displayed as 81397220005801
5. View the Location and contact information block for the Bruce B. Downs Boulevard VA Clinic on the [Tampa healthcare's Locations page](https://www.va.gov/tampa-health-care/locations)
6. Observe the Main phone number is displayed as 813-972-2000, ext. 5801, as expected
7. View the Location and contact information block for the Bruce B. Downs Boulevard VA Clinic on the [Tampa healthcare's facility page for Bruce B. Downs Boulevard VA Clinic](https://www.va.gov/tampa-health-care/locations/bruce-b-downs-boulevard-va-clinic/)
8. Observe the Main phone number is displayed as 813-972-2000, ext. 5801, as expected

## AC / Expected behavior
Main phone number should be displayed as 123-456-7890, ext. 1, consistent with the style guide 

## Screenshots

<details> 
<summary> As displayed in Locations and contact information block on Locations page </summary>

<img width="757" <img width="762" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd21WQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b44cefad784d8605a200e401896306f6cb55abf7/image.png" alt="image.png" />

</details>

<details> 
<summary> As displayed in Locations and contact information block on facility page </summary>

<img width="761" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd3FWQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e634a3e42465725085ff20bf6cc3171685b63706/image.png" alt="image.png" />

</details> 
<details> 
<summary> As displayed on Register for care page </summary>

<img width="757" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd2FWQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2cd7cee661b1fc25064be86cdbd2d111d002a26b/image.png" alt="image.png" />
</details>

<details> 
<summary> Drupal UX </summary>

<img width="830" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdzZWQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ba251990f093a84c5a1fd2cf45a17fbe16be472b/image.png" alt="image.png" />
</details>

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [ ] `Public Websites`
- [x] `Facilities`
- [ ] `User support`
- [ ] `Accelerated Publishing`

**Comment by xiongjaneg** [comment]
This is fixed now for VAMC, but uncertain for VBA.

From Laura: Could this be rolled into USWDS component updates?

From Eli: Eli has been using this as an edge case whenever telephone components are addressed.

**Comment by xiongjaneg** [comment]
From Laura: She will update component tickets with telephone reminders to parse extensions correctly.

**Comment by xiongjaneg** [comment]
@xiongjaneg close as resolved

**Comment by xiongjaneg** [comment]
Resolved as part of Max's front end work on Service Locations
