### ISSUE TITLE
SPIKE: Where do we cut VBA names? What can we do without lighthouse?

### ISSUE THREAD

**Issue by davidmpickett** [department-of-veterans-affairs/va.gov-cms#17351]
## User Story or Problem Statement

Follow up from #15752 (VBA IA)

## What can we do without lighthouse?

![VBA Naming Logic_2024-02-27_17-29-49](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/2033231e-5a3c-41cb-b6a6-87bacfbaee11)

![VBA Naming Logic_2024-02-27_17-30-01](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/82e973b6-9c41-4537-8236-0e8b2716d4c0)

![VBA Naming Logic_2024-02-27_17-29-56](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/ee6e2808-fcfa-4620-86d8-3815bacb4e9c)

- Confirm that option 1a is the desired path forward
- Front end exploration of querying Drupal directly for Facility Locator results?

## Once lighthouse is ready to accept new fields

![VBA Naming Logic_2024-02-27_17-32-39](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/2025871e-06f4-4926-a328-907d9bf26263)

- Do we initiate conversation with Lighthouse now?
- Do any of the paths above make this future state harder to reach

## Acceptance Criteria
- [x] Determination is made and findings are documented for: 
  - [x] Technical feasibility and decision for storing VBA condensed name
  - [x] Future-proofing concerns with eventual Lighthouse architecture / plan (consider long-term impact of any proposal given the eventual integration with LH)
  - [ ] Review with PM / PO / Content strategy
- [ ] Update these tickets with any relevant findings
  - [x] #17353 
  - [x] #17355
  - [x] #17356

**Comment by davidmpickett** [comment]
Copy and pasting this comment 
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15752#issuecomment-1959742070

For the engineering conversation, there are four locations which have shared vha locations which are not reflected in the name

Current name | vha shared location id | vha shared location name 
---| --- | --- | 
| White River Junction VA Regional Benefit Office | vha_405 | White River Junction VA Medical Center |
| Cheyenne VA Regional Benefit Office | vha_442 | Cheyenne VA Medical Center
| Muskogee VA Regional Benefit Office | vha_623 | Jack C. Montgomery Department of Veterans Affairs Medical Center
| San Diego VA Regional Benefit Office | vha_664BY | Kearny Mesa VA Clinic

and a few examples with non-VA shared locations which are not reflected in the name (one is an MVP location)
Current name  | non-VA shared location name 
---| --- | 
Cleveland VA Regional Benefit Office | Patrick V. McNamara Federal Building
Detroit VA Regional Benefit Office | Anthony J Celebrezze Federal Building
St Paul VA Regional Benefit Office | Henry Whipple Federal Building
Albuquerque VA Regional Benefit Office | Dennis Chavez Federal Building

The rule about having either a shared non-VA location or a shared VA location but not both is not accurate: 
Manila VA Regional Benefit Office at U.S. Embassy in Manila is associated with a non-VA building (U.S. Embassy in Manila) as well as a shared VHA location (VA Manila Outpatient Clinic). 
**Both are true: the Clinic is on the Embassy campus.** 

**Questions**

- How might we ensure the names of shared VA locations are accurate? 
  - Database currently has 10 locations with shared vha locations which have had name changes and the official name still uses previous name
   - One location has the shared location name for a completely different facility than the name affiliated with the shared vha ID

**Comment by jilladams** [comment]
I originally pulled this ticket into Next Refinement because it's a part of the VBA National epic and because we talked about #15583 in relation to it this week.

However: I'm not actually 100% certain on priority relative to other Q3 / VBA things. It might be best to let @Agile6MSkinner work through the VBA National epic priorities with Michelle before we try to dive in here, since that will be happening imminently.

Moving back to Backlog.

**Comment by jilladams** [comment]
This is a Drupal-first question, and then we can figure out how FE works.

**Comment by omahane** [comment]
Of the 489 VBA sites in prod, we have many that are only distinguishable by a combination of 
- [Type] at [Location]

These include the facilities that begin with the following:
- VA Regional Benefit Satellite Office
  - **Example**: VA Regional Benefit Satellite Office at American Samoa Vet Center
  - _Variation: VA Regional Benefit Office_ 
- Veteran Readiness and Employment Office
  - **Example**: Veteran Readiness and Employment Office at Augusta VA Medical Center - Uptown 
  - _Variation: Veteran Readiness and Employment_
  - _Variation: Veteran Readiness and Employment Office and Pre-Discharge Site_
- VetSuccess on Campus
  - **Example**: VetSuccess on Campus at American River College
- Integrated Disability Evaluation System (IDES) Site
  - **Example**: Integrated Disability Evaluation System (IDES) at Beaufort Naval Hospital 
  - _Variation: Integrated Disability Evaluation System (IDES)_
  - _Variation: Integrated Disability Evaluation System (IDES) and Pre-Discharge Claims Intake Site_
- Seamless Transition Integrated Care Clinic (STICC)
  - **Example**: Seamless Transition Integrated Care Clinic (STICC) at Richard L. Roudebush VA Medical Center 

@mmiddaugh (cc: @davidmpickett) Am I right in assuming that these are not up for the same kind of copy and bifurcation of the name that we are spiking in this ticket?

If that's the case, it's looks we are only looking to change the name of a dozen or so:
- Anchorage VA Regional Benefit Office at Colonel Mary Louise Rasmuson Campus of the Alaska VA Healthcare System
- Fargo VA Regional Benefit Office at North Fargo VA Clinic
- Fort Harrison VA Regional Benefit Office at Fort Harrison VA Medical Center
- Fort Harrison VA Regional Benefit Satellite Office at Benjamin Charles Steele VA Clinic
- Fort Harrison VA Regional Benefit Satellite Office at David J. Thatcher VA Clinic
- Hartford VA Regional Benefit Office at Newington VA Clinic
- Honolulu VA Regional Benefit Office at Spark M. Matsunaga Department of Veterans Affairs Medical Center
- Knoxville Veteran Readiness and Employment Office at J.D. Duncan Federal Building
- Little Rock VA Regional Benefit Office at Eugene J. Towbin Healthcare Center
- New Orleans VA Regional Benefit Office at New Orleans VA Medical Center
- Salt Lake City VA Regional Benefit Office at George E. Wahlen Department of Veterans Affairs Medical Center
- Salt Lake City Veteran Readiness and Employment Office at George E. Wahlen Department of Veterans Affairs Medical - Center
- Sioux Falls VA Regional Benefit Office at Royal C. Johnson Veterans' Memorial Hospital
- Togus VA Regional Benefit Office at Togus VA Medical Center

Am I reading this right? Please correct me of I'm mistaken.

**Comment by davidmpickett** [comment]
@omahane, because only Regional Offices and Satellite offices are in scope for MVP, my previous work focused only on those two types. We aren’t solving this for all VBA facility types. 

This spreadsheet was my working doc for tracking any facilities that might be edge cases
https://dvagov.sharepoint.com/:x:/s/SitewideFacilitiesTeam/ESGDTL0pkqdDiKT3oqcFoZEBuEtSx0NdGZIbvUwY7TwQ9w?e=9amPaQ

**Comment by davidmpickett** [comment]
Note also that for Satellite Offices that don’t currently have a geographical region prefixed before the office type, we have a ticket for @mmiddaugh to discuss those with stakeholders so that we then could cut off the shared location

https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17358

**Comment by omahane** [comment]
> @omahane, because only Regional Offices and Satellite offices are in scope for MVP, my previous work focused only on those two types. We aren’t solving this for all VBA facility types.

I was looking at all VBA facility names and found that this solution applies to dozens (among the hundreds). Can you confirm that we are only concerned right now with the list I posted above? I am trying to both get an understanding of the problem set and conceive of viable solutions for that set.

**Comment by omahane** [comment]
After talking looking at the naming conventions and talking to @davidmpickett, I have the following suggestions:
- Create an "official name" field in VBA
- Change the VBA migration to set the name from the API to populate the official name field
- Copy the official name field to the title (if the title is empty [as we do with Vet Center in the `va_gov_migrate.module`])
- Manually change the title for the Regional benefit offices that need to have a condensed name
  - The lack of a consistent naming convention for these makes is unlikely that a programmatic solution will be dependable
- `content-build` can use the **Shared VHA Location** field to create the "Located at ..." information under the name.
- Run another VBA DB extract migration

Other changes to the workflow could include:
- No longer updating Sandy's DB with information about 
  - District
  - Non-VA Location Name
  - Non-VA location URL
  - Shared VA Location
- Doing so would mean that we would no longer have to run a VBA DB extract migration

**Comment by omahane** [comment]
@davidmpickett Do you have any additional thoughts?

**Comment by davidmpickett** [comment]
Machine name | Nickname | Meaning | Notes
-- | -- | -- | --
`name` | API Name | What Lighthouse API lists as the name of a given facility | Source of truth is actually Sandy's DB
`title` (now )| Drupal name | The title of a node in Drupal drives URLs, breadcrumbs etcetera | Right now this is populated with API Name
`official name` | Official name in Drupal | This will be a new field that will match the API name | Won't actually do much, aside from hold the API name in case we need it for something
`title` (future) | Common name / Condensed name / Drupal name | After creating `official name`, we will make it so this Drupal property can be overridden to shorten names in Drupal only | Follow Vet Center pattern

**Comment by davidmpickett** [comment]
> @davidmpickett Do you have any additional thoughts?

I added a legend of the different terms you are referencing in your proposal to hopefully make it a little easier for others to understand. Otherwise my only thought is "good work" :)

**Comment by omahane** [comment]
Oh, I noticed that we don't have an alias pattern for VBA Facility Services, but I think we should also follow the Vet Center approach here, too.

**Comment by jilladams** [comment]
@mmiddaugh @Agile6MSkinner ready for final signoff from Product.

**Comment by omahane** [comment]
Product decided during the 12 Sept 2024 Sitewide UX sync to proceed with the recommendations I made in the [above comment](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17351#issuecomment-2327090762). I am writing up a ticket to capture the recommendation. This ticket is now closable.
