### ISSUE TITLE
[EPIC] [A11y] Public Website Products Accessibility Audits

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#17364]
## Description
Many of the Public Websites products were originally built a few years ago. While the majority of them are compliant with 508 standards and technically accessible, there have been updates in best practices since they have last been audited. There are most likely updates that can be done to improve the accessibility and general user experience of our products. It would be beneficial to do an accessibility audit of all products in the Public Websites portfolio and determine what accessibility updates could be made.

### Additional Info
Embedded inside other tickets:
- Translation toggle
- FAQ pages
- Step-by-Step
- Q&A pages

Not included in this epic:
- PACT Act: Redesigned Q4 2023/Q1 2024 however it was put on hold and will be looked at again later 2024
- Income Limits: Most recently updated 8/29/2023
- Homepage: Most recently updated 6/1/2023
- Discharge Upgrade: Planned Q2 2024
- Publications: Slated for deprecation
- Full width banner: Using DS component which I recently (1/23/24) worked with Facilities to update and contribute back to the DST
- Promo banner: Uses DS component that has a lot of complicated history behind it for why it is the way it is. Folks know changes are needed but a lot of work would need to be put into it and PW are not necessarily the only deciders of those decisions.

**Comment by laflannery** [comment]
@jilladams and/or @FranECross Can one of you confirm that every PW product has been accounted for in either one of the tickets in the epic or included in the Additional Info section above? I want to make sure nothing is missed, thanks!

**Comment by FranECross** [comment]
@laflannery In looking at our [Github products](https://github.com/department-of-veterans-affairs/va.gov-team/blob/9770d11e7c4922ed0b778a759b78f2c24d01535e/products/public-websites/README.md) page, I also see the following. Would love for @jilladams to vet the list below. Thanks!

- Benefits Hub Detail Page
- Discharge Upgrade Wizard
- FAQ page
- Full-width Alert (banner)
- General VA.gov unauth UI
- Global Header/Footer
- Header/Footer Injection
- Income Limits Web App
- Non-facility Redirects
- Outreach Materials Library (Publication listing & page)
- PACT Act Wizard
- Promo Banner
- Reusable Q&A
- Unauth React healthcare widgets
- VA.gov Homepage Translation React widgets
- Veterans Crisis Line Modal

**Comment by jilladams** [comment]
Took a look at the list Fran shared. 

**To add:** these 4 are valid and need tickets in this epic: 

1. Full-width Alert (banner)
2. Promo Banner
3. FAQ pages
4. Reusable Q&As that have standalone pages (any that don't will show up on R&S or FAQ pages

**Maybe?** These 2 are sort of weird conceptually and maybe we should talk about how we could make sure they're accessible? 
1. Unauth React CTA widget (used on Refill Rx, etc.).  I feel like this came up under another ticket recently, but I haven't gone to find it. Can do that next week.
2. Translation React widgets -- e.g. on https://www.va.gov/disability/eligibility/

**No tickets needed** For the rest:  
* 2 have tickets in epic already
  * Benefits Hub Detail Page - #17366
  * Veterans Crisis Line Modal - #15776
* These are excluded under Add'l Info in the ticket body:
  * PACT Act Wizard
  * Income Limits Web App
  * VA.gov Homepage 
  * Discharge Upgrade Wizard
  * Outreach Materials Library (Publication listing & page)
* These are excluded bc the header / footer rebuild: 
  * Global Header/Footer
  * Header/Footer Injection
* Non-facility Redirects -- not a product we can audit
* General VA.gov unauth UI is just sort of a CYA bucket we can ignore.

**Comment by laflannery** [comment]
Comments/questions:

- On the Full width Banner vs the Promo banner - what are these on the front end? For example what's currently on the homepage of [VA.gov](https://www.va.gov/)? Is this Full width or Promo?
  - This banner implemented is using the DS banner component which I very recently worked with Eli on to update and contribute back to the DST so I would put this in the ignore list for this ticket.

![Screenshot 2024-03-06 at 8 45 29 AM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/106678594/112149b3-6027-4014-85ec-183c6ac8852e)

   
- For the other 2 (FAQs and Q&A) I am including those in the Resources & Support ticket because that's where the pages go when these content types are created, the become Resources and Support Detail pages, same with Step-by-Step pages. We might need to split up tickets that come out of this but auditing is going to be much easier if I keep this entire section as one thing
- Translation react widget, this page is included in the Benefits Hub Ticket and so the translation toggle would be review on that page within the context of the content, which. is a bettter way to do it rather than in isolation. Similar to above, we may need to split up any ticket created but this ticket should handle the review of this toggle.
- CTA widgets - This is possibly [the ticket you were thinking of and my comment](https://github.com/department-of-veterans-affairs/va.gov-team/issues/50215#issuecomment-1966695750) where I did a brief review of heading levels. I will be doing another review soon because we need to upgrade these to the v3 component and at that point I can make sure there's nothing in the Un-auth experience besides these heading levels we need to worry about in which case we probably don't need to add an additional ticket here.

**Comment by jilladams** [comment]
Yes correct yay! As far as what full width banner and promo banner are in the FE:

- Full width banner = your screenshot, appears just below header.
- Promo banner = we don't have one live in the FE right now. Here's one in the CMS that we could unarchive in a Tugboat to see it -- https://prod.cms.va.gov/promo-banner/learn-what-the-pact-act-means-for-your-va-benefits.  It's the narrower 1 line stripe that appears pinned to the bottom of the viewport (pretty sure, vs. just scrolly above the footer), and was mostly used for PACT Act promotional purposes in recent history

**Comment by laflannery** [comment]
Thanks Jill - I know all about that Promo banner and there's some history there regarding the accessibility. It would not be easy to change. I'm not going to include it here for reasons but I've noted it in the description

**Comment by FranECross** [comment]
Added associated tickets as sub-issues so they'll display on the epic on the new board.

**Comment by laflannery** [comment]
All audits done, closing
