### ISSUE TITLE
VBA spotlights: national should stay on top when multiples exist

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#17382]
## Describe the defect
On VBA pages, if both a national and a local spotlight exist, the National spotlight should always appear first. 

## To Reproduce
1. Go to any VBA page or create one (node/add/vba_facility) on a Tugboat or locally
2. Scroll to spotlight content
3. Make sure a Natl spotlight exists
4. Create a local spotlight
5. Publish and see that on the FE, the newer local spotlight will appear above the National spotlight

## AC / Expected behavior

- [x] Nat'l spotlights should appear first, per designs
- [ ] ~~Design review of changes~~ Not needed as this is not a design change and can be verified by product

**Comment by xiongjaneg** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Sitewide-Facilities-639f5253e4b702a32376339e/issues/department-of-veterans-affairs/va.gov-cms/17382?planning-poker) with Zenhub @maxx1128 @eselkin

**Comment by xiongjaneg** [comment]
@maxx1128 @eselkin We'll want to prioritize this as next Tuesday's training with VBA editors is on Spotlight.

**Comment by jilladams** [comment]
https://prod.cms.va.gov/des-moines-va-regional-benefit-office/locations/des-moines-va-regional-benefit-office Can be used to verify this in prod (has both a national and local spotlight) but preview server is giving me a 504 right now.

**Comment by xiongjaneg** [comment]
Currently getting a 502 gateway error on preview of the above link.

**Comment by xiongjaneg** [comment]
@eselkin @omahane Since VBA's don't have URL redirects yet, can this be verified on prod preview?

**Comment by xiongjaneg** [comment]
@eselkin Would you please check off the ACs you've completed? Thanks! 
I'm currently verifying in Tugboat.

**Comment by xiongjaneg** [comment]
@thejordanwood This had an AC of a design review but I didn't see you as a PR reviewer. Did you get a chance to verify this?

**Comment by thejordanwood** [comment]
@xiongjaneg I don't believe I've verified this. I'm getting a 502 gateway error on the link that Jill posted, is there a way that I can see this?

**Comment by xiongjaneg** [comment]
@thejordanwood Since VBA isn't live yet, it can't be verified in prod. I'm going to add some sample spotlights in Eli's Tugboat environment and do a content release. It will take at least an hour (argh!) but I'll check back when it's ready. I'll be at this link: https://web-5zcelrjqvagaeosvzzyp1izj6ef2njrx.demo.cms.va.gov/cleveland-va-regional-benefit-office/locations/cleveland-va-regional-benefit-office/

**Comment by eselkin** [comment]
@xiongjaneg Use this link to check: https://web-ihqrv6rby5lxlkn8zqdxf9u7lk1aplcp.demo.cms.va.gov/cleveland-va-regional-benefit-office/locations/cleveland-va-regional-benefit-office/

**Comment by eselkin** [comment]
@xiongjaneg Since it was just putting back what had been there but in the right order, did it really need Jordan to re-review?

**Comment by xiongjaneg** [comment]
It was in the ACs and Jordan never reviewed, so just covering our bases.

**Comment by xiongjaneg** [comment]
@eselkin I think you're right on that last AC, prob don't need to waste @thejordanwood time on it, especially with Tugboat delays. I'll scratch that AC and I'll to the verification when the Tugboat is ready. Sorry for inconveniencing you both but thank you for your flexibility!

**Comment by xiongjaneg** [comment]
Verified in Tugboat
<img width="732" alt="Screenshot 2024-03-12 at 4 27 36 PM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/73648238/6a7e9e8c-16a5-45ae-926c-c52a52b1f12f">
