### ISSUE TITLE
CAIA review of design for Facility Locator error and empty states

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#17388]
## Description
In #15935, Jordan designed error states for the following Facility Locator situations. The scope of some changes mean that CAIA should review them. This ticket is to request CAIA review.

A note on the design: In an earlier iteration of this design, we wanted to rearrange the search fields by moving the Facility type field up beside the location field. This is why the current design in Figma is displayed this way. This review is for the error/empty state messages only–with the knowledge that a new design layout will be a future iteration. 

## New Copy:
- Browser isn't allowed to use location and the "Use my location" button is selected
     - Behavior: Warning Modal appears to ask user to change location settings. 
     - Message: Location sharing isn’t enabled. To use your location when searching for a VA facility, you need to enable location sharing. Go to the settings on your device and update sharing permissions. 
- No location is entered
     - Behavior: Error message displays on field.
     - Message: Enter zip code or city, state.
- Invalid location is entered OR no results are found
     - Behavior: A "no results" message is displayed below the search with suggestions on how to improve search results.
     - Open sections to view messages for desktop, mobile map view, and mobile list view.
     
     <details>
          <summary>No results: Desktop</summary>
          
             - Behavior: Message appears below the search fields.
             - Message for desktop: 

            No results  for "[Facility type]", "[Service type]" near "[Location]"
            
            Try searching for something else or in a different area.
            
            Suggestions:
            - Zoom out to view larger area of the map
            - Move the map to a different area
            - Enter a different location, facility type, or service type
     </details>
     <details>
          <summary>No results: Mobile map view</summary>
          
             - Behavior: Message appears below the search fields.
             - Message for mobile map view: 

            No results  for "[Facility type]", "[Service type]" near "[Location]"
            
            Try searching for something else or in a different area.
            
            Suggestions:
            - Zoom out to view larger area of the map
            - Move the map to a different area
           -  Enter a different location, facility type, or service type
     </details>
     <details>
          <summary>No results: Mobile list view</summary>
          
             - Behavior: Message appears below the search fields.
             - Message for mobile map view: 

            No results  for "[Facility type]", "[Service type]" near "[Location]"
            
            Try searching for something else or in a different area. Try entering a different location, facility type, or service type.
     </details>

- No facility type is selected from dropdown
     - Behavior: Error message displays on field.
     - Message: Select a facility type.
- No service type is entered (if required)
     - Behavior: This is a type ahead search, where matching results populate in a dropdown. Users need to select a result from the dropdown to initiate a valid search. The error message displays on field.
     - Message: Start typing and select a service type.
- Invalid service type is entered (if required)
     - Behavior: This is a type ahead search, where matching results populate in a dropdown. Users need to select a result from the dropdown to initiate a valid search. The error message displays on field and in a dropdown below the field.
     - Message on field: Select an available service type.
     - Message in dropdown: No results found. Search for a different service.
- Map or list doesn't display results (system error)
     - Behavior: Error alert appears below search.
     - Message: We’ve run into a problem. We’re sorry. Something went wrong on our end. Please try again.

Current error states are documented on the [Facility Locator error states page](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/facility-locator/engineering/error_states.md). 

## Design

Error/Empty states page in the [Facility Locator Figma file](https://www.figma.com/file/GvNVeG9GAXZaBpny7vNxZP/Facility-Locator?type=design&t=FDwcjWSz9mOOeI2y-6)

**Comment by aklausmeier** [comment]
Moved to Admin/Workflow column to get product input on priority and input on if we should proceed with CAIA review. While it's not a current quarterly priority, CAIA review could proceed so it's done when we are ready to pick it back up. @michael

**Comment by Agile6MSkinner** [comment]
This is in the epic for Service type autosuggest (typeahead), but it doesn't seem related to that. Are you able to comment @aklausmeier or @thejordanwood?

We're working on that functionality now.

**Comment by thejordanwood** [comment]
@Agile6MSkinner While working on autosuggest designs, we noticed that the current error/empty state messages don't meet content guidelines. We've already documented our suggestions in [the Figma file](https://www.figma.com/design/GvNVeG9GAXZaBpny7vNxZP/Facility-Locator?node-id=172-16230&t=21VNOakkxTkYSVzT-1), but need CAIA's approval.

There are new error message suggestions for the service type field in this.

**Comment by jilladams** [comment]
## Next steps
* @thejordanwood to confirm the error states in the Figma while working #18960. Handoff to Michael what will need to be sent to CAIA.
* @Agile6MSkinner then to create a CAIA intake ticket to review the text. 
  * CAIA has a contract transition at 12/19 and we don't know yet if existing team will stay or go. May take some time for a new team to handle, fysa.

**Comment by thejordanwood** [comment]
@Agile6MSkinner I took at look at this and am confirming that the error messages shown in this ticket are what we would like to update existing FL error messages to. 

There may be new error messages that need to be created for AutoSuggest and we can work on those when I get to this ticket https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18960.

**Comment by jilladams** [comment]
Moved the copy to a SharePoint doc: https://dvagov.sharepoint.com/:w:/r/sites/SitewideFacilitiesTeam/_layouts/15/Doc.aspx?sourcedoc=%7B16133e45-c971-4bb2-870e-4ff3ef968601%7D&action=editnew

Opened a CAIA intake ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/98598

Closing this.
