### ISSUE TITLE
Consider: Update Non-clinical services Views to match FE display

### ISSUE THREAD

**Issue by davidmpickett** [department-of-veterans-affairs/va.gov-cms#17381]
## User Story or Problem Statement
AS A VAMC editor adding Non-Clinical Services to a VAMC System Top Task page (Billing and Insurance, Medical Records, Register for Care)
I NEED to understand  how information will be displayed on the FE when I am editing Drupal
SO THAT, I can better understand the purpose of various fields

## For consideration (from Service Locations team testing)
If appointment information is entered, it should show on the front end. Currently, it isn't. Are appointment fields and service options needed for these VAMC non-clinical services? Are there use cases with more than one service location?

## Description or Additional Context 

**Current order**
field_clinic_name
field_building_name_number, field_wing_floor_or_room_number
field_address

**Order should be:**
field_address
field_clinic_name
field_building_name_number
field_wing_floor_or_room_number

![VAMC Service locations_2024-02-29_00-28-39](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/f4086131-e51a-439f-aa2d-608761d890ca)

![VAMC Service locations_2024-03-05_22-31-15](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/904a8ccf-4704-4105-a21a-dcc51e225ed1)

## Steps for Implementation

cms.va.gov/admin/structure/views/view/non_clinical_services

<img width="975" alt="Screenshot 2024-02-28 at 6 29 37 PM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/eec9ee7d-e412-45c4-9781-3cf0ecee9d3a">

## Acceptance Criteria
- [ ] View(s) are updated to match desired field order 
- [ ] Confirm that all three content types that use this view display fields in desired order
  - [ ] Billing and Insurance
  - [ ] Medical Records
  - [ ] Register for Care 
- [ ] Requires design review
- [ ] Requires accessibility review

## Team
Please check the team(s) that will do this work.

- [ ] CMS Team
- [ ] Public Websites
- [x] Facilities
- [ ] Accelerated Publishing

**Comment by omahane** [comment]
@davidmpickett I think clinic name needs to go first, based on the front end.

**Comment by omahane** [comment]
Confirmed on prod:
<img width="1948" alt="Screenshot 2024-04-10 at 08 18 50" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/766573/c8b5a8e6-8651-4859-bef3-2352ff79247a">

**Comment by omahane** [comment]
This can be closed.
