### ISSUE TITLE
[V1 & 3 Components] Implement the V3 Action Link component in the PACT Act Wizard

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-cms#17404]
## Status
**[2024-06-24]** This ticket is unblocked; DST released the action link component last Thursday: https://github.com/department-of-veterans-affairs/component-library/releases/tag/v42.2.0
**[2024-06-10]** _**Moved back to Blocked > Randi noted that DST has not yet released this component (though the work has been merged/closed). Once it is available (see releases here: https://github.com/department-of-veterans-affairs/component-library/releases) we can pull this ticket in.**_
**[2024-06-05]** Ticket 2500 has been completed and close. Unblocking this ticket and moving it to Stretch/Next Sprint.
**[2024-06-04]** This ticket is still blocked. The DST [ticket Link - Action Web Component - Development #2500 is in Review/QA](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2500)
**[2024-05-30]** This ticket is still blocked. The DST [ticket Link - Action Web Component - Development #2500 is in progress](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2500)
**[2024-05-21]** This ticket is still blocked. The DST ticket has not been completed yet: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2500
**[2024-05-07]** The ticket noted below has been completed. No longer blocked.

## Description

Convert the action link to a component (As Randi noted on 2024-03-04 in #[17200](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17200#top) the action link can be converted, but not yet)

### User story

**AS A** PO/PM for Public Websites products
**I WANT** to implement available V1 or V3 components in features & products currently under Public Websites management where components aren't currently being used
**SO THAT** all PW products are in alignment with the current component version
**AND** Veterans and other users have a consistent experience throughout VA.gov tools and information

## Acceptance criteria

- [ ] action link is componentized
- [ ] other features display correctly
- [ ] verify/review the E2E tests
- [ ] check desktop and mobile
- [ ] a11y review

**Comment by FranECross** [comment]
@randimays Here's the action link component (PAW) ticket mentioned in #17200 . Feel free to edit as needed. Thanks!

**Comment by randimays** [comment]
@FranECross This ticket is still blocked. The DST ticket has not been completed yet: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2500

**Comment by randimays** [comment]
Noting that DST has not yet released this component (though the work has been merged/closed). Once it is available (see releases here: https://github.com/department-of-veterans-affairs/component-library/releases) we can pull this ticket in.

**Comment by randimays** [comment]
@FranECross This ticket is unblocked; DST released the action link component last Thursday: https://github.com/department-of-veterans-affairs/component-library/releases/tag/v42.2.0

**Comment by chriskim2311** [comment]
Confirmed on staging PACT act wizard. Closing!
