### ISSUE TITLE
Document VA Benefits taxonomy in va.gov-team products repo

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#17401]
## 
We build the VA Benefits taxonomy, but it's not documented as a product. 

Docs should go in here: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products. We should maybe check with Dave & CAIA re: whether there's a nested place docs should live? (e.g. within https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/benefit-hubs? ) 

### artifacts brain dump: 
* epic re: content model: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9628
* epic re: the taxonomy / use in Benefit Detail pages: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13752
* The taxonomy itself: https://prod.cms.va.gov/admin/structure/taxonomy/manage/va_benefits_taxonomy/overview

## ACs

- [ ] Product docs area is created in va.gov-team/products for VA Benefit taxonomy (nested per CAIA feedback, if that applies)
- [ ] Documentation references existing artifacts and state of the build
- [x] Documentation includes a description / explainer about "magic header" (header + paragraphs, without header levels)

**Comment by FranECross** [comment]
Initial documentation; Jill will help with what type of artifact we can produce.  

Dave believes CAIA has documented some of this (Danielle). See if we can use that instead of duplicating work.

**Comment by jilladams** [comment]
PR is up that stubs out some high level notes, within CAIA's /products/content/structured-content area, alongside the benefits content model project docs: https://github.com/department-of-veterans-affairs/va.gov-team/pull/77922

**Comment by jilladams** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/content/structured-content/va-benefits-taxonomy
