### ISSUE TITLE
[Analytics] VFS Custom Event Audit Form for PW Products

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-cms#17412]
## Status
[2024-03-07] The components currently being implemented have baked in analytics, which render any custom analytics moot (and they'll be removed). Because of that, the audit needs to be conducted after all the component work has been finished. Targeting Sprint 107.

## Description
In preparation for the migration to GA4, the Analytics Insights team needs information on _all_ custom events used by the Public Websites products so they can continue to track them.

The request is to complete this form with [this spreadsheet](https://docs.google.com/spreadsheets/d/1t8FZbUk_B3SaqFcu-9PyR9AV62l7T9gIG1Qq0ms7gPA/edit#gid=0) as soon as possible, but no later than **Friday, April 5.** The **final deadline** where Universal Analytics will stop collecting data is **June 30, 2024**, so we are trying to ensure tracking coverage _well_ before that date.

### User story
**AS A** product manager/product owner
**I WANT** Public Websites products' custom analytics events to continue to be tracked after the migration to G4
**SO THAT** we can continue to obtain the analytics they provide in order to determine the future needs of our Veterans, their family members, and survivors

## Acceptance criteria
- [ ] Spreadsheet is completed detailing and GA custom events for the following products. Note that I've listed all products/features the PW team owns, but I'm not sure that they all have custom events. Feel free to cross out any that don't apply.
  - [ ] Benefits Hub Landing Page
  - [ ] Benefits Detail Page
  - [ ] Campaign Landing Pages
  - [ ] Discharge Upgrade Wizard
  - [ ] Events List
  - [ ] Event
  - [ ] FAQ Page
  - [ ] Find a Form / VA Forms
  - [ ] Full-width Alert/banner
  - [ ] Header/Footer
  - [ ] Homepage, VA.gov 
  - [ ] Income Limits Apps
  - [ ] Promo Banner
  - [ ] Outreach Materials Library
  - [ ] PACT Act Wizard
  - [ ] Resources & Support Detail Page
  - [ ] Reusable Q&A
  - [ ] Search, On-site
  - [ ] Translation React Widgets
  - [ ] Unathed React Healthcare Widgets
  - [ ] Veterans Crisis Line Modal

**Comment by FranECross** [comment]
@randimays @chriskim2311 @jilladams Just a heads up that the Analytics and Insights team is requesting all teams complete this form with [this spreadsheet](https://docs.google.com/spreadsheets/d/1t8FZbUk_B3SaqFcu-9PyR9AV62l7T9gIG1Qq0ms7gPA/edit#gid=0) as soon as possible, but no later than Friday, April 5. The final deadline where Universal Analytics will stop collecting data is June 30, 2024, so we are trying to ensure tracking coverage well before that date.

I have this ticket in Next Refinement to chat about tomorrow during prefinement. Thanks!

**Comment by randimays** [comment]
I had to put this down to move some other web component tickets across the line. This will carry over as I've just gotten started.

**Comment by randimays** [comment]
Public Websites' custom events spreadsheet: https://docs.google.com/spreadsheets/d/1fDsRQct_QMJ5nd3bTRDgwrfbFo_PqzdFQqYecJouic8/edit#gid=0

**Note**: this does not follow the format of the Platform Analytics spreadsheet. It is a comprehensive look at all the custom events we are using across PW products and where the DST web components do or do not meet our needs.

@FranECross to present this to Dave C next week to evaluate what events we want to **remove**, **adjust** or **add** before filling out the Platform Analytics spreadsheet.

@randimays to walk through this spreadsheet with @FranECross (and @jilladams @laflannery @chriskim2311 if yall are interested) on Monday 3/18.

**Comment by FranECross** [comment]
@randimays Thanks so much! I think it would be great to have a short walk-through. I think we'll introduce it to Dave, and then give him an opportunity to scrutinize it since there's so much good info in the spreadsheet. I can export to excel for him. cc @jilladams @laflannery @chriskim2311

**Comment by jilladams** [comment]
Fran to take a look at this spreadsheet, as first pass. She will submit the form to the Analytics team and escalate to Dave with any questions for clarification. Closing.
