### ISSUE TITLE
Office hours set to "All day open" in Drupal display as "Closed" on Front End

### ISSUE THREAD

**Issue by davidmpickett** [department-of-veterans-affairs/va.gov-cms#17415]
## Describe the defect

As seen on VA Oklahoma City health care -  Billing and insurance - Questions about copay balance
- Drupal says "All day open" https://prod.cms.va.gov/oklahoma-city-health-care/billing-and-insurance
- FE says "closed" https://www.va.gov/oklahoma-city-health-care/billing-and-insurance/ 

![Screenshot 2024-03-05 at 2 50 48 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/a93240a4-b60e-474e-a946-dfd2572b03a8)

 ## Additional context
Note that when we pull in data from Facilities API, we tend to format "open all day" hours as 24/7 in the comment field, rather than indicating start and end hours. 

![Screenshot 2024-03-05 at 2 58 57 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/d2fb6677-5df7-4a2f-9253-cab596d420d1)

Is this what we want editors to do? There's no clear guidance in the interface.

## AC / Expected behavior
- [ ] If editor has indicated midnight - midnight in Drupal. FE displays "Open 24 hours"
- [ ] Other office hours cases are not negatively affected
   - [ ] Any other time to midnight
   - [ ] Midnight to any other time
   - [ ] Any other time to any other time

**Comment by xiongjaneg** [comment]
From Christian: Drupal should throw a validation error when the start time and end time entered are the same.

**Comment by xiongjaneg** [comment]
From Dave: When open 24/7 comes in from the API, it is changed to a comment in Drupal (not hours) as "24/7." Could we guide editors to use this when a facility is open all the time?

**Comment by davidmpickett** [comment]
On further investigation, the editor has correctly entered the start and end hours per the logic of the Office hours module. 
> 'all_day' => ($starthours === '0000' && $endhours === '0000'),
There is no other way (currently) for an editor to input hours and get the result of "All day open" in the Drupal interface. We should have Front End logic to support this case

**Comment by aklausmeier** [comment]
@thejordanwood mocked up, where if a facility is open all day, should read "Open 24 hours" that is also shown in [#17455](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17455). Noting here so we can maintain consistency as needed. 


![Screenshot 2024-03-08 at 3 36 28 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/137226108/bf76a565-a229-4775-8ca8-b9cf3c73ffb0)

**Comment by davidmpickett** [comment]
Partially blocked by having a larger discussion about #17455

**Comment by davidmpickett** [comment]
@xiongjaneg @jilladams - FYI I discussed with @mmiddaugh today and I am suggesting that this not be launch blocking for VBA/VAMC service locations since it is a defect that predates this effort and was not introduced as a result of the new code. I have updated the launch plan to reflect this, but open to discussion at Refinement

**Comment by jilladams** [comment]
Editorial experience questions are captured here: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17455

**Comment by eselkin** [comment]
So midnight to some time doesn't currently work and some time to midnight doesn't seem to work either. Oddly.

**Comment by eselkin** [comment]
Added coverage of midnight and noon, re: https://design.va.gov/content-style-guide/dates-and-numbers#times-and-time-zones

**Comment by davidmpickett** [comment]
Confirmed on prod 
![Screenshot 2024-05-16 at 1 14 10 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/5d143069-017e-4b69-9154-2a8d4c7884c1)

**Comment by davidmpickett** [comment]
Also found an example of a service that uses noon
https://www.va.gov/shreveport-health-care/locations/overton-brooks-veterans-administration-medical-center/#covid-19-vaccines

![Screenshot 2024-05-16 at 1 21 31 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/47d5864f-b8ab-4916-a020-5499ac807672)
