### ISSUE TITLE
fieldVamcEhrSystem isn't currently available on all VAMC pages

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#17416]
## User Story or Problem Statement
The fieldVamcEhrSystem isn't currently available on all VAMC pages, so not all pages know they are in a cerner/vista system.

The fieldOffice and fieldRegionPage as opposed to fieldAdministration seems to be able to get me that information. Eli is modifying graphql pages get that data. For Lovell, Eli is working so EHR data will persist across some of the modifications we do to its data for the Cerner cutover scheduled March 9.

#Acceptance criteria
- [x] fieldVamcEhrSystem is on all VAMC pages

**Comment by eselkin** [comment]
Lots of page graphql pieces include fieldOffice or a reverse regional lookup but most most don't include the fieldVamcEhrSystem. Most fragments are not reused. So this required adding `fieldVamcEhrSystem` when a node of type NodeHealthCareRegionPage was discovered. This, however, does not catch all pages. Some, like the Locations Listing pages don't seem to be able to get the piece of information to the actual page.

**Comment by xiongjaneg** [comment]
@eselkin Would you please check the AC if done? How can this be verified? Is there a screenshot that would show this?

**Comment by eselkin** [comment]
The testing would be that MHS portal link is displayed on all TRICARE Lovell pages (not Federal pages). This will be reinforced in testing I'm creating for Lovell.

**Comment by xiongjaneg** [comment]
Verified in prod, the MHS portal link is displayed on Lovell TRICARE pages: system, every facility, health services, locations
![Uploading Screenshot 2024-03-12 at 2.55.14 PM.png…]()
