### ISSUE TITLE
[Table Margins] Audit all tables in products/features PW owns to ensure margins & captions are correct

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-cms#17419]
## Status
[2024-07-24] [Fran] Could this be a candidate for Sprint 9 for FE, or was this geared toward UX doing the audit? Or a PM? 

## Description

When the automated table migration was implemented by the Design team (tables that were previously not using the <va-table> now are), margins between tables disappeared and some tables have missing table captions

There is a [ticket](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16852)to fix table margin for the Benefits Detail pages, however we should audit PW team's other products to determine if the issue of decreased table margins and missing table captions is more widespread, and then a ticket or tickets should be created to address any issues.

This issue on the ticket mentioned above was (along with the along issues such as the missing table caption) was brought to our attention by Randi H: Slack thread. I did also ask in the DST slack channel if the fix to add margins would need to be done at the component level or at the template level and they said on the template, which would be something for our team to handle (assuming I'm understanding things correctly)

Note that the content build table has already been updated with the captions and margins. This audit should be for vets website.

### User story

**AS A** Veteran, their family member, caregiver or survivor
**I WANT** to view information presented in tables in VA.gov in a manner allowing me to clearly delineate separation of table information
**SO THAT** I'm not confused and my experience in VA.gov is optimal and helpful

## Acceptance criteria
- [ ] audit tables for decreased table margins and missing table captions in features/products owned by the PW team (list below)
- [ ] create a ticket or tickets for any tables that need their margins adjusted and/or captions displayed, OR create spreadsheet with information and alert @FranECross, who will then create tickets.

**Comment by FranECross** [comment]
@davidmpickett @aklausmeier Do you know or remember if this audit was meant to be done by the UX folks, or the FE folks? Thanks!

**Comment by aklausmeier** [comment]
@laflannery did some prelim work on this because the design system now has a v3 component #18843

I feel like we can close this ticket, wrap anything that is not covered in Laura's ticket above into hers. Should ensure we don't dupe efforts.

**Comment by FranECross** [comment]
@laflannery I'm not sure there is anything to take from this ticket and put into yours. When you have time, will you review and update your ticket if necessary? I'll close this one afterwards. Thanks.
