### ISSUE TITLE
Spike: Facility Locator search results for PPMS don't update when search area is zoomed out

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-cms#17418]
## Describe the defect
We've received a report from PPMS that an active in-network provider in Fairfax, Virginia is not returned in search results as expected. 

Expected provider:
RIGHT AT HOME OF NORTHERN VA
8280 WILLOW OAKS CORPORATE DR STE 520
FAIRFAX, VA 22031-4514

Michelle noted: "It's not that the provider is missing from the search results, it's that all of the results within the map's displayed area aren't returned - only the first 10."

This seems specific to PPMS results, not VA results. Eli saw on the network tab that the request doesn't happen a second time when you zoom out the map area and re-search for PPMS. It does for VA health services.

## To Reproduce
1. Go to [Facility Locator ](https://www.va.gov/find-locations/?page=1&address=Fairfax%2C%20va&facilityType=provider&serviceType=3747P1801X&latitude=38.846224&longitude=-77.306373&radius=13&bounds%5B%5D=-78.056373&bounds%5B%5D=38.096224&bounds%5B%5D=-76.556373&bounds%5B%5D=39.596224&context=Fairfax%2C%20Virginia%2C%20United%20States)
2. Enter Fairfax, VA as the geographic search parameter 
3. Select "Community providers (in VA's network) as the Facility type
4. Enter In-Home Supportive Care as service type
5. Click "Search"
6. Observe search results A - K are returned. 
<details> 
<summary> Screenshot 1 </summary>

<img width="680" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOGkxQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2833b6db91bc06216aa32b4bfd597ba6947e7317/image.png" alt="image.png" />

</details>

---

7. Zoom out twice and click "Search this area of the map"
8. Observe that although the map view shows a larger area, the same ten results around the new center of the map are displayed, and no additional pages of results are available 
<details> 
<summary> Screenshot 2 </summary>

<img width="644" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOVcxQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5aec84b0b43f793e93c9991644e0fb52bf9c384a/image.png" alt="image.png" />

</details>

---

9. Change search parameters to Annandale, Virginia and initiate search
10. Observe first search result is the expected provider 
<details> 
<summary> Screenshot 3 </summary>

<img width="664" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOEMxQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bb41c3b3918ba9c39b435c0652cee5bdfd23a060/image.png" alt="image.png" />

</details>

---

Notice in this side by side screenshot that the location of the expected provider is within the displayed map but is not included in search results. 

<details>
<summary> Side by side </summary>

<img width="1581" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOVMxQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1c1d7cd25f2593899bbe6fd36fb648c9126e5a95/image.png" alt="image.png" />

</details

## Acceptance criteria

- [x] Current functionality is reviewed for differences between PPMS and VA services
- [x] Recommendations are made for fixing the PPMS search results when zoomed out
- [x] If pagination of results pages are also affected, recommendations are made for pagination
- [ ] Results are shared at UX Sync or asynchronously with UX and product

**Comment by xiongjaneg** [comment]
From Eli: may be related to Facility API has limited results. If we want all results, we'd have to do multiple pages to show them all, which is many requests to the service, which would slow it down considerably.

From Michelle: could we request more?
From Eli: we can't request a certain number of pages, but we can request a certain number of results.

From Michelle: do we know how we can handle it or do we need a spike?
From Eli: Increasing the number of results is a small amount of work. Currently with letters for results, we are limited to 26 max.

From Michelle: Can we request 20, assuming 2 pages (10 per page)
From Eli: Likely possible, but the more requested, the greater the payload and the slower the download for people with slower internet.
From Max: Could we do the initial 10 and then async request the additional 10 in the background while the viewer is looking at the initial list.
From Eli: This is like but not as severe as building pagination.

From Michelle: Could we give viewers a "See more results" option and give them the choice to load more?
From Max: This could work but might be similar to clicking the second page.

From Max: Could we provide viewers an option to select how many results they want?

From Laura: What is happening in this situation that is not happening with other searches?
From Michelle: With VA locations, the results are inherently limited within a given radius, but providers would likely have many more results.

**Comment by xiongjaneg** [comment]
![Uploading Screenshot 2024-03-06 at 3.20.18 PM.png…]()

**Comment by xiongjaneg** [comment]
@maxx1128 @eselkin I turned this ticket into a spike. Would you please review, edit, and point? We can point by timeboxing how much time you want to spend on it. Thank you!

**Comment by xiongjaneg** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Sitewide-Facilities-639f5253e4b702a32376339e/issues/department-of-veterans-affairs/va.gov-cms/17418?planning-poker) with Zenhub @eselkin @maxx1128

**Comment by eselkin** [comment]
For this testing and exploration, I am using Urgent Care, because in dev/sandbox there are only like 3 community care providers for In Home Supportive Care.
There's several pieces to this puzzle I think.
1. Vets-api for queries to CCP/PPMS endpoints is not paginating
2. Vets-api returns incorrect values for the pages that is actually is returning
For Example: 
This request:
```
curl 'https://dev-api.va.gov/facilities_api/v1/ccp/urgent_care?page=1&per_page=10&radius=127&lat=37.143457238473474&long=-77.23129450000101' 
```
Returns 11 results, even though we request it to limit a page to 10 results. Not only that, it returns that there is no next page, which is odd and unlikely, especially if it's giving more than 10 results. If I change that limit to 5 and re-send with:
```
curl 'https://dev-api.va.gov/facilities_api/v1/ccp/urgent_care?page=1&per_page=5&radius=127&lat=37.143457238473474&long=-77.23129450000101'
```
We get 6 results (even though we specified 5) and no next page which definitely means pagination on vets-api is broken, this is not a component problem.

However, we may have said to turn off pagination in Vets-api because things like Urgent care take both `/ccp` data and `/va` data and join them together in one set of results which makes pagination from Vets-api odd/confusing.

Re-requests are made when zoom is changed. There is a significant delay before it can request results again. Not sure what this is, but the redraw/waiting of the map seems to play a part in this.

**Comment by eselkin** [comment]
in `modules/facilities_api/app/services/facilities_api/v1/ppms/client.rb`
The `base_location_params` do include pagination
The `base_params` do not include pagination
Question still stands whether the results are returned with pages or not. 
Can't get the details/logs because can't use vets-api locally to query PPMS/CCP. 
Will talk with @maxx1128 Monday to see how he was able to get prod data from PPMS. May need to go about getting similar credentials to evaluate.

**Comment by jilladams** [comment]
Sounds like we may also want to attend PPMS office hours to ask them about it?

**Comment by eselkin** [comment]
Checked on:
`https://dws-dev-ppms.devtest.vaec.va.gov/swagger/ui/index#!/ProviderLocator/ProviderLocatorControllerGetAsync`

Checked PL/POS/Facilities/etc all return no pagination

Example: ProviderLocator does not paginate
Results of:
```
https://dws-dev-ppms.devtest.vaec.va.gov/v1.0/ProviderLocator?address=800%20Vermont%20Ave%20NW%20Washington%20DC%2020005&radius=10&specialtycode1=207R00000X&maxResults=2
```
are:
```
{
  "@odata.context": "https://dws-dev-ppms.devtest.vaec.va.gov/v1.0/$metadata#Collection(PpmsDwsApis.NetFramework.Models.V10.CosmosProviderLocatorResult)",
  "value": [
    {
      "Miles": 1.0998,
      "Minutes": 7.5167,
      "ProviderName": "KANGO, GHAZAL",
      "ProviderSpecialty": "Internal Medicine",
      "SpecialtyCode": "207R00000X",
      "SpecialtyGroupName": "Primary Care Medicine",
      "PreferredMeansReceivingReferralHSRM": false,
      "PreferredMeansReceivingReferralSecuredEmail": false,
      "PreferredMeansReceivingReferralMail": false,
      "PreferredMeansReceivingReferralDirectMessaging": false,
      "PreferredMeansReceivingReferralFax": false,
      "ProviderType": "Individual",
      "HPP": "Unknown",
      "CareSite": "GEORGE WASHINGTON U HOSP",
      "CareSiteAddress": "900 23RD ST NW WASHINGTON, DC 20037-2342",
      "CareSiteAddressStreet": "900 23RD ST NW",
      "CareSiteAddressCity": "WASHINGTON",
      "CareSiteAddressState": "DC",
      "CareSiteAddressZipCode": "20037-2342",
      "CareSitePhoneNumber": "202-715-5109",
      "CareSiteFaxNumber": "(202) 715-4871",
      "CareSiteEmail": null,
      "WorkHours": null,
      "ProviderGender": "Female",
      "ProviderNetwork": "CCN Region 1",
      "NetworkId": 14,
      "ProviderAcceptingNewPatients": true,
      "ProviderPrimaryCare": false,
      "QualityRanking": null,
      "ProviderIdentifier": "1306370770",
      "Latitude": 38.901263,
      "Longitude": -77.050721,
      "GeoWarning": null,
      "Telehealth": false,
      "Homehealth": false,
      "TelehealthService": false,
      "SubServices": [],
      "Trainings": [],
      "VSS": null
    },
    {
      "Miles": 1.0998,
      "Minutes": 7.5167,
      "ProviderName": "DELIO, JOSEPH",
      "ProviderSpecialty": "Internal Medicine",
      "SpecialtyCode": "207R00000X",
      "SpecialtyGroupName": "Primary Care Medicine",
      "PreferredMeansReceivingReferralHSRM": false,
      "PreferredMeansReceivingReferralSecuredEmail": false,
      "PreferredMeansReceivingReferralMail": false,
      "PreferredMeansReceivingReferralDirectMessaging": false,
      "PreferredMeansReceivingReferralFax": false,
      "ProviderType": "Individual",
      "HPP": "Unknown",
      "CareSite": "GEORGE WASHINGTON U HOSP",
      "CareSiteAddress": "900 23RD ST NW WASHINGTON, DC 20037-2342",
      "CareSiteAddressStreet": "900 23RD ST NW",
      "CareSiteAddressCity": "WASHINGTON",
      "CareSiteAddressState": "DC",
      "CareSiteAddressZipCode": "20037-2342",
      "CareSitePhoneNumber": "(202) 715-5109",
      "CareSiteFaxNumber": "(202) 715-4871",
      "CareSiteEmail": null,
      "WorkHours": null,
      "ProviderGender": "Male",
      "ProviderNetwork": "CCN Region 1",
      "NetworkId": 14,
      "ProviderAcceptingNewPatients": true,
      "ProviderPrimaryCare": false,
      "QualityRanking": null,
      "ProviderIdentifier": "1114346939",
      "Latitude": 38.901263,
      "Longitude": -77.050721,
      "GeoWarning": null,
      "Telehealth": false,
      "Homehealth": false,
      "TelehealthService": false,
      "SubServices": [],
      "Trainings": [],
      "VSS": null
    }
  ]
}
```

**Comment by eselkin** [comment]
For the 2nd AC: _Recommendations are made for fixing the PPMS search results when zoomed out_
Solution is to fix pagination and query results for **FacilityServiceLocator** in vets-api, in `modules/facilities_api/app/services/facilities_api/v1/ppms/response.rb`

For the 3rd AC: _If pagination of results pages are also affected, recommendations are made for pagination_
Since it is pagination and results in vets-api that are not correct, the solution above of debugging and fixing results data processing in vets-api seems most correct.
It's hard to make recommendations about how pagination is affected since we can't see the debugging of vets-api until I get access. 

I have updated documentation of PPMS to include methods of using debugging from ArgoCD/vets-api rails terminal as well as the ticket used to request access.

**Comment by jilladams** [comment]
@eselkin are you willing to help cut the follow up tickets for that work / link them here? I can get them into epics etc. but getting your technical notes in the meat of the ticket would be very helpful.

**Comment by eselkin** [comment]
Yep. I'll make tickets
I'm brainstorming here:
1. Diagnose where pagination data is lost in vets-api with confirmatory debugging in ArgoCD
2. Diagnose whether query of paged data resolves to correct query of PPMS FacilityServiceLocator endpoint
3. Modify vets-api pagination to capture page (page, per_page, and total entries) information
4. Add tests to spec to guarantee pagination works for CCP vets-api endpoint
5. Verify that vets-website facility locator can page through results from CCP endpoint (it should use the same abstraction for pagination/wrapper as VA endpoints)
6. Add tests in vets-website to check that facility locator can page through CCP endpoint results.

**Comment by jilladams** [comment]
Also noting ArgoCD access got provided: https://github.com/department-of-veterans-affairs/va.gov-team/issues/79216#issuecomment-2022807922

**Comment by jilladams** [comment]
And I see some of the follow up tickets: 
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17646
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17649
