### ISSUE TITLE
Conditionally display "Location" header on Service Location templates

### ISSUE THREAD

**Issue by davidmpickett** [department-of-veterans-affairs/va.gov-cms#17414]
## User Story or Problem Statement

Currently it is possible for a CMS editor to populate the `field_building_name_number` or `field_wing_floor_or_room_number` fields of Service Location Address without populating the `field_clinic_name`. This can lead to situations where these fields don't have an appropriate header.

There is a [Drupal ticket](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17380) which would resolve this issue on the editor side by conditionally requiring this fields, however, having even once that is implemented, it won't immediately fix current instances of that field being missing.

In the [design ticket](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17342), Jordan has proposed adding the label “Location” when the Name field is left blank and moving it to the top of the Service Location section. 

### Mockup
A mockup can be seen here. This design can also be found on the Location headers page in the [VAMC Master Figma file](https://www.figma.com/file/ikCp2eOubIgbN1TwyEYIrN/VAMC-Master?type=design&node-id=550%3A10915&mode=design&t=lWfWJXeB1WLrnmSX-1)

<img width="381" alt="Screenshot 2024-03-11 at 10 03 31 AM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/104526584/dec7b2fe-181b-4980-8ba4-551043406c8b">

### VAMC Health Service

![Screenshot 2024-03-22 at 11 02 09 AM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/17670958-f849-4b78-a688-7b2593b2b495)

### VAMC Top Task Page
![Screenshot 2024-03-22 at 1 20 42 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/7bd04838-2451-4389-b12a-0d41112cd59d)

### VBA Facility Service

![Screenshot 2024-03-22 at 1 26 38 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/3be9b2d4-dedc-483d-a3f0-c24ff080bcb2)

## Acceptance Criteria
- [ ] If`field_building_name_number` or `field_wing_floor_or_room_number` are populated but `field_clinic_name` is not, display a header that says "Location" where `field_clinic_name` would normally be displayed
- [ ] I expect all Liquid Templates that have Service Location in them are updated with this logic
  - [ ] VAMC Facility (health services section)
  - [ ] VAMC Billing and Insurance, Medical records, register for care (Police if it has been updated to use non clinical services)
  - [ ] VBA facility (service accordions)
  - [ ] Confirm this works for cases where a service has either a single or multiple service locations
- [ ] Requires design review
- [ ] Requires accessibility review

**Comment by davidmpickett** [comment]
@xiongjaneg @mmiddaugh tagging you on this ticket as it is one that of the smaller actionable items to come out of Jordan's design work and might be a good candidate for prioritization

**Comment by aklausmeier** [comment]
@thejordanwood Please review and update ticket with finalized mockup, I believe you wanted to move "location" up above phone so it falls beneath facility address.

**Comment by thejordanwood** [comment]
@aklausmeier I've updated the ticket with that info and also included a screenshot.

**Comment by davidmpickett** [comment]
@mmiddaugh I think there's a good case for this being launch blocking for VBA/VAMC service location. Compare before and after:

![Screenshot 2024-03-22 at 1 31 52 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/cc607749-3bac-4db0-aa5f-ea74f07f9586)

![Screenshot 2024-03-22 at 1 32 03 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/4beb3128-c8ac-4e23-a804-6a96c863150e)

**Comment by jilladams** [comment]
Would help to provide an example service with multiple service locations for testing.

**Comment by davidmpickett** [comment]
https://www.va.gov/pittsburgh-health-care/locations/pittsburgh-va-medical-center-university-drive/#gastroenterology
is my go-to example of 2 service locations

**Comment by maxx1128** [comment]
@davidmpickett Are you able to give links to any other active page examples of this bug? I have a review instance up at http://9b38542627c29dcfdb00072ae2240fdc.review.vetsgov-internal/ and will be able to check the effectiveness of the fix quickly against that.

**Comment by davidmpickett** [comment]
- https://www.va.gov/greater-los-angeles-health-care/billing-and-insurance/
- https://www.va.gov/greater-los-angeles-health-care/locations/west-los-angeles-va-medical-center/#amputation-care
- For VBA you might need to create content that meets the criteria. All the examples I had previously created on the Tugboat were wiped

**Comment by maxx1128** [comment]
I was able to confirm the first two linked examples locally and updated the pull request. Once I can update my local environment to recreate multiple service locations, then this should be all set to review.

**Comment by davidmpickett** [comment]
Rerunning content release on Tugboat so this can be verified

**Comment by davidmpickett** [comment]
Verified on Prod, but still gonna verify on Tugboat that it plays well with VBA and Service Location enhancements

![Screenshot 2024-04-15 at 5 15 52 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/5fe4cf5d-0c71-4bde-b969-9ded9e268f5f)

![Screenshot 2024-04-15 at 5 16 01 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/c867feaa-680a-4267-ade2-d3a952608e9a)

**Comment by davidmpickett** [comment]
Hey @maxx1128 noticing some funky spacing on Tugboat when comparing the instances where the **Location** header is used compared to instances with **field_clinic_name**

### **Location**
![Screenshot 2024-04-15 at 11 49 46 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/0427357f-1e49-431a-96e9-e17824093c9f)

### **field_clinic_name**
![Screenshot 2024-04-15 at 11 49 54 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/3b38a3d3-3827-4493-a7e8-0d668b2420cf)

https://web-xptmfsnjoodldn85nzgkrgljqtfbz24b.ci.cms.va.gov/pittsburgh-health-care/locations/pittsburgh-va-medical-center-university-drive/#mental-health-care

https://web-xptmfsnjoodldn85nzgkrgljqtfbz24b.ci.cms.va.gov/pittsburgh-health-care/locations/pittsburgh-va-medical-center-university-drive/#hivhepatitis-care

Looks like the Location header is missing `class="vads-u-margin-top--0"`

**Comment by maxx1128** [comment]
@davidmpickett Those tugboat links aren't working, but I can still update those headers to add the class.

**Comment by maxx1128** [comment]
@davidmpickett I created a draft pull request with the class added, you can see it here: https://github.com/department-of-veterans-affairs/content-build/pull/2020

**Comment by jilladams** [comment]
#sitewide-ux thread with some concerns from Michelle / Amanda about changes here: https://dsva.slack.com/archives/C06S9DADEUB/p1713306503021989?thread_ts=1713306255.508589&cid=C06S9DADEUB.  

@maxx1128 please take a look at that thread for your reference, and Jordan / Dave are tagged there to take a UX-look as well.

**Comment by thejordanwood** [comment]
@maxx1128 Just for your awareness, I think this looks good except for the spacing issue that Dave pointed out. I'm waiting to approve until I can review the [draft pull request](https://github.com/department-of-veterans-affairs/content-build/pull/2020) you've created to fix this issue. cc: @davidmpickett

**Comment by davidmpickett** [comment]
@jilladams While I'm out. Steps to get this closed:
- Max's new PR (contentbuild-2020) needs to target the [content build integration branch](https://github.com/department-of-veterans-affairs/content-build/tree/VACMS-16144-VAMC-ServiceLocationParagraphs) rather than main so that it can be reviewed with all other changes in context
- Code review on Max's new PR @eselkin 
- [Optional] Do a [content release](https://cms-xptmfsnjoodldn85nzgkrgljqtfbz24b.ci.cms.va.gov/admin/content/deploy) on the Integration Branch Tugboat using contentbuild-2020 as the content build version so can verify the fix works as intended on Tugboat [QA step]
- Max's new PR merged into Integration Branch
- Do a [content release](https://cms-xptmfsnjoodldn85nzgkrgljqtfbz24b.ci.cms.va.gov/admin/content/deploy) on the Integration Branch Tugboat using Integration Branch PR (contentbuild-1912) as the content build version so can verify the fix works as intended on Tugboat [Verification on Prod]

The alternate path of merging contentbuild-2020 to Main 
- Precludes the step of QAing on Integration Branch Tugboat, might need ngrok into Max's local or something?
- would require rebasing contentbuild-1912 against Main before the final content release for "prod verification"

**Comment by maxx1128** [comment]
@thejordanwood The pull request with the change fixing the spacing issue has [a working test environment you can look at here.](http://02b47a2f4e7ea673d85842e0a69e5ef9.review.vetsgov-internal/)

**Comment by thejordanwood** [comment]
@maxx1128 The spacing is a bit too close together now. Is there any way that it can be the same as the spacing between the Contact information and Behavioral health services headers in this example?

This is what I'm seeing:
![Screenshot 2024-04-19 at 1 42 53 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/104526584/eb74a569-30a7-4797-8e18-654a0f9ea3ed)

ideally, the spacing should look like this:
![Screenshot 2024-04-19 at 1 42 34 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/104526584/d1b0b60b-c097-4b54-b084-a961b7b69c56)

**Comment by laflannery** [comment]
@maxx1128 I spoke to @aklausmeier and we want to make sure that there aren't custom margins being used - that we use the standard margins provided by the DS. That being said can you:
- Remove the 0 margin on the "Location" header Jordan noted above?

![Screenshot 2024-04-22 at 12 04 42 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/106678594/768f63fa-b627-4210-a9a2-f2edfdb291be)
- Remove the custom 1em margin that is on the "Contact information" header (which I know you didn't add if that could be removed anyway?)
![Screenshot 2024-04-22 at 12 04 13 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/106678594/11c8ded5-a4cb-492b-9b4a-aa9ab1c691de)

**Comment by maxx1128** [comment]
The custom 1em margin is actually being added in the vets-website repo, not content-build, which is a little odd, but makes these updates a bit simpler. I have closed the existing pull request, so the Location header stays as it is in production without the 0 margin helper. I've also opened [another pull request](https://github.com/department-of-veterans-affairs/vets-website/pull/29332) that removes the custom margin.

**Comment by laflannery** [comment]
Just want to close the loop on the spacing issues that [Jordan](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17414#issuecomment-2067110175) and [Dave](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17414#issuecomment-2058231029) had brought up in a few comments in this ticket. [This is a mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1713813993072/1bb7a26961235cc715442a5786bf9ddbf96f4f05?sender=u10a597890f85398daa3c4805) of everywhere this Location header work currently has an impact right now, it currently shows a few issues:
- The largest issue will be handled with a separate ticket (noted in a comment in the mural)
- The other 2 issues are what was pointed out originally by Dave but then after Max resolved that one instance a new issue was pointed out by Jordan, because now in another use case the headers were too close.

We ideally should always be using DS margins/spacing and not adding custom margins. In this case, we need to look at the margins being added to the wrapping `<div>`. But again, we need to look at this for every possible scenario because I already know that if I remove the margin in one case, I have created an issue in another case. The overall spacing here should be reviewed/cleaned up separately (perhaps as part of the typography review)

**Comment by aklausmeier** [comment]
Thank you @laflannery! Agree with reviewing spacing as part of the typography updates.

**Comment by davidmpickett** [comment]
@laflannery Thanks for that thorough audit! I made a note about reviewing spacing on the Typography Audit.

@maxx1128, seems like once you merge your new PR and this is verified on Prod, we'll be good to close this ticket

**Comment by davidmpickett** [comment]
Confirmed on Tugboat and Prod

![Screenshot 2024-04-25 at 11 07 25 AM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/e9e7f0ae-84e5-4838-a00f-dcd0329a2b10)

![Screenshot 2024-04-25 at 11 10 36 AM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/f3557416-85ec-4fcb-97d1-91461e26c179)
