### ISSUE TITLE
Facilities 106 sprint plan

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#17429]
## Schedule Notes
- Jill OOO 3/11-3/15
- Alexis OOO 3/18, and two half-days
- Christian OOO 3/19-3/21

## Sprint Priorities 🎯 
At the end of this sprint, what do we want to have accomplished/delivered?
- Service Locations team testing and subsequent issues #17453 

Tickets for top priority:
- 🎯 UX Design: #17505 
- 🎯 UX Research: #17499 
- 🎯 Drupal: #17501 
- 🎯 FE: #17453 related tickets

### UX
- Design: #17485 
- Design: #13804 
- Design: #16337 
- Research: #17498 
- Research: #17413 
- Content #16268 continuing
- Content supporting Front end with #16540

### Front End
- VBA: #16540 
- VAMC: #15567 
- Vet Centers: #17473
- Facility Locator: #17418
- Continuing V3 component tickets under epic #15887 (Amanda noted new target date May 3)

### Drupal
- VAMC/VBA: #17501
- Vet Centers: #17374 
- VAMC: #12666 
- #15291 
- Flagged facilities when ready

**Comment by aklausmeier** [comment]
What might be missing for UX is a Platform Design Intent for FE Spotlight pattern
