### ISSUE TITLE
Investigate Content Build Runners

### ISSUE THREAD

**Issue by gracekretschmer-metrostar** [department-of-veterans-affairs/va.gov-cms#17431]
## User Story or Problem Statement
Content build and release has experienced two failures and delays in publishing content. After troubleshooting the issues, CMS staff discovered irregularities. How can we better support the runners to ensure better stability with the content build process? 

## Acceptance Criteria
- [ ] Testable_Outcome_X
- [ ] Testable_Outcome_Y
- [ ] Testable_Outcome_Z
- [ ] Requires design review
- [ ] Requires accessibility review

## Team
Please check the team(s) that will do this work.

- [ ] CMS Team
- [ ] Public Websites
- [ ] Facilities
- [ ] Accelerated Publishing

**Comment by Hassantariq-MetroStar** [comment]
As per our investigation with @hgbarreto , we found that the issue with runners is disk space is not getting cleaned up after the completion of the job i.e, after uploading the .tar folder to s3 bucket and in that period of time, its reaching upto 78% of the disk space.
And we are not cleaning the .tar file after uploading to the S3 bucket in the pipeline. This is the reason that another runner dont have much space to run on the server and its getting stuck.
I'm assuming if we upload the .tar file to s3 bucket, so we already have a backup and we dont need that .tar to be on runner evertyime.
we will continue our investigation and update on this.
