### ISSUE TITLE
Facilities team testing for VAMC/VBA Service Locations changes

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#17453]
## Description
When dev is complete on the VAMC/VBA Service Locations changes, the team will synchronously test and capture any defects.

This ticket will track those issues in comments for review & triage, to determine priority.

- Tugboat links:
  - Tugboat env: https://tugboat.vfs.va.gov/65255ca9c573c9cdb2d06792
  - CMS: https://pr15622-xptmfsnjoodldn85nzgkrgljqtfbz24b.ci.cms.va.gov/
  - Web (front end): https://web-xptmfsnjoodldn85nzgkrgljqtfbz24b.ci.cms.va.gov/

- Once prioritized to be fixed, issues will get added to #17454 

## Issues
- #17513
- #17514
- #17516
- #17518
- #17515

**Comment by davidmpickett** [comment]
@xiongjaneg @mmiddaugh This ticket is not launch blocking or high priority since Service Regions will not be entered by local staff and the functionality works, it's just formatting https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17481

**Comment by davidmpickett** [comment]
@xiongjaneg @mmiddaugh Slightly higher priority, but still low because Service Regions will have limited users. Just wanted to make sure we had a placeholder in the backlog #17482

**Comment by davidmpickett** [comment]
@mmiddaugh @xiongjaneg Another low priority ticket about Service Region https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17512

**Comment by davidmpickett** [comment]
@xiongjaneg @mmiddaugh Here's my first find that might be worth considering prioritizing. Don't think it would be launch blocking, but could be something we want to run shortly after launch. https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17515

**Comment by davidmpickett** [comment]
@xiongjaneg @mmiddaugh And here's a basic stub for the thing I was talking about during the meeting today about having a way to reduce the number of "Unspecified" in the future. Definitely not an immediate action item, but pulled up some comments from a previous ticket

**Comment by jilladams** [comment]
@xiongjaneg @mmiddaugh for the purposes of Sprint 105 reporting: we've got an issue list, and I know y'all have collaborated on prioritization. Thoughts on whether or not this ticket can / should close?
