### ISSUE TITLE
"Save" + "Save and continue editing" UX

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#1745]
### User Story or Problem Statement

- As an editor, I want to clearly understand the purpose of "Save and continue editing" button. #1743
- As an editor, I want to be able to specify custom revision message and have it saved correctly while using "Save and continue editing" button. #1697 
- As an editor of Banner Alerts, I do not need to use "Save and continue editing" and I'd rather not see it at all. #1744 

**IMPORTANT**: "Save and continue editing button" is not saving new paragraphs on "VAMC facility health services" content type and potentially others. We may want to disable "Save and continue editing" on all content types until we stabilize the behavior across the CMS.

### Affected users and stakeholders

* CMS editors

### Hypothesis

_A hypothesis may depend on a spike ticket to be completed._

We believe that _this_solution_ will achieve _this_outcome_. We'll know that to be true when _this measurable outcome occurs._

### Assumptions
* Tk
* Tk

(How will these assumptions be validated?)

## Acceptance Criteria
* "Save" and "Save and continue editing" buttons have consistent UX and reliable behavior across all content types in the CMS

**Comment by kevwalsh** [comment]
Thanks for creating this epic @oksana-c !  Steve got me caught up on your conversation. 

We are likely moving away from allowing editors to set moderation to published within a content form, which may reduce the scope of this epic somewhat. I mocked up one version of what this might look like, including the exception for full_width_banner_alert or other content types that don't have editorial workflow applied to them. 

![save-as-draft](https://user-images.githubusercontent.com/643678/81764983-c0e2f900-94a0-11ea-9c98-dd2ab1ead422.png)

Of course, we'd be losing the ability to "save as draft and continue editing", which might be frustrating to users. So maybe we retain that as an option. [Original whimsical is here.](https://whimsical.com/W4Cm7i6T5P7srMrHbo5eUo)
