### ISSUE TITLE
SPIKE: Forms migration: nodes with changed Title should get the Changed Title flag

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#17450]
## Describe the defect
https://dsva.slack.com/archives/C52CL1PKQ/p1709821062708819

On 3/6/2024, VA Form 21-0307 was updated in the Forms DB with a new title. 
Drupal migration ran at midnight 3/7/2024, and data was successfully migrated to Drupal. 
After migration, the form node reflects the new `Form name` from Forms DB, but: https://prod.cms.va.gov/find-forms/about-form-21-0307 
* No revision on 3/7/2024 from CMS Migrator to reflect the changed title [defect]
* Change Title flag was not added to the node: https://prod.cms.va.gov/admin/content/va-forms/changed-title [defect]
* `Form title` (Drupal field) was not updated to match the `Form name`from the Forms DB. [not sure if this is a defect or intended behavior]

There are a couple of pieces to investigate here, to understand what happened vs. what should have happened. 

### Migration Context & docs
* Migration: https://prod.cms.va.gov/admin/structure/migrate/manage/forms/migrations
    * Nightly CSV artifact will appear here: https://prod.cms.va.gov/sites/default/files/migrate_source/va_forms_data.csv
* Forms Migration docs: https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/READMES/migrations-forms.md
* Product docs: Forms > engineering > data: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-a-va-form/engineering/data/data.md -- has some specific context around how we handle dates, for reference

## AC / Expected behavior
- [ ] After nightly forms migration, any form node with a changed title should get the Changed Title flag and appear in the Changed Title va-forms view
- [ ] Any node modified by the migration should get a revision log from the CMS Migrator
- [ ] ~Migration logic for how `Form name` is or isn't set up to modify the `Form title` Drupal field is documented in either [Forms Migration](https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/READMES/migrations-forms.md)  or [forms > engineering > data](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-a-va-form/engineering/data/data.md), to help determine if the existing logic should be modified~
- [ ] Summary notes are added to ticket comments, for PO / PM review re: whether follow up tickets are needed
- [x] New tickets are created to track any changes required

**Comment by jilladams** [comment]
In general, the CSV from the nightly migration can be found at https://prod.cms.va.gov/sites/default/files/migrate_source/va_forms_data.csv.  I got last night's download and edited it down to include only the row related to this form, here: [va_forms_data (2).csv](https://github.com/department-of-veterans-affairs/va.gov-cms/files/14527421/va_forms_data.2.csv)

**Comment by jilladams** [comment]
On this node, there is an old revision where title change shows up as metadata change in a revision (7/21/20): https://prod.cms.va.gov/node/5994/revisions/view/317886/318733/split_fields.  The metadata _does_ change after that, but without the revision log or flag.

**Comment by jilladams** [comment]
From scrum: 

### Truth in code
* Code should be creating a new revision from the CMS migrator every time a change is detected. We cannot reproduce a change arriving without the revision.
* The migrator creates a revision with a date/timestamp using the current time (meaning: the time when the migration is actually running.)
* Drupal form title will originally use the Forms DB form title value. 
  * The Drupal Form name field can then be modified by Editors. 
  * If the Forms DB form name changes in the future, the Drupal Forms DB field for Form title will update. The Drupal Form Name field won't. It will have to be manually updated to catch up. Daniel will verify this to make sure we can say this will full confidence.

### Revisions to this form
* **7/24/2020**: the title changed and got a revision log: https://prod.cms.va.gov/node/5994/revisions/view/317886/318733/split_fields. Manual revision by Randi Hecht.
    * From: Award Attachment for Qualifying Veteran's Child Born with Disabilities
    * To: Award Attachment for Certain Children with Disabilities Born of Vietnam and Certain Korea Service Veterans
* **3/7/2024**: Nancy Kessinger asked us to change the title to "Award Attachment for Qualifying Veteran's Child Born with Disabilities."  (This was a reversion to the 7/24/20 title change, but we didn't realize it at the time.) I edited the node, and notified Nancy it was live on VA.gov after a content release.
    * The email is proof, but this revision from me no longer appears in the Form node revision log. 😨 
* **3/16/2024**: (1 week after we created this ticket to figure out why the revision log didn't appear for the title change): The CMS migrator made a revision log with the title change: https://prod.cms.va.gov/node/5994/revisions/view/773763/848384/visual_inline 🤯 
    * From: Award Attachment for Certain Children with Disabilities Born of Vietnam and Certain Korea Service Veterans
    * To: Award Attachment for Qualifying Veteran's Child Born with Disabilities

So: the CMS Migrator now appears to be working correctly and doing what we expected originally. However: with a time delay? Or something? And my revision disappearing is wow not great. Daniel is not sure how we pursue figuring that out.

**Comment by jilladams** [comment]
@dsasser one other thing here I noticed after we hung up: that 3/16/2024 CMS migrator revision log changed the Form name field, but that change didn't get the flag and appear in https://prod.cms.va.gov/admin/content/va-forms/changed-title. So making sure the Changed Title flag is getting applied is one other place to verify if you're able. I'm wondering if the "Form name" field vs. "Title" is part of the issue there?

**Comment by dsasser** [comment]
> I'm wondering if the "Form name" field vs. "Title" is part of the issue there?

I know where the changed title flag is being set and how it works, but this is a good reminder that there are two fields involved, so I'll dig into that and surface what the code is doing with that in mind.

**Comment by dsasser** [comment]
We likely have 2 bugs here. I'm running through another round of testing to validate the results.

Bugs:

- Form Title changes do not always create a new revision.
- The Changed Title flag is not always getting set (I couldn't get it to flag any form)

The test:
I re-titled [an existing form](https://prod.cms.va.gov/find-forms/about-form-21-0307) and ran through a migration, which resulted in:

- A new revision was created with the message “Update of form metadata from Forms DB.”
- Drupal field “Form Title” (field_va_form_title) was updated with the new title.
- Drupal field “Form Name” (field_va_form_name) did not change
- The “changed title” flag did NOT get set.

Additionally, I tested back-to-back title changes, and each subsequent form title change _DOES NOT_ create a fresh revision, but instead replaces the previous revision:

![initial state](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/221539/46e8078f-ed01-485e-bf22-b3c513679157)
![v2 title change](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/221539/52092053-14a9-474d-9ff6-e051a2f0abce)
![v3 title change](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/221539/f06a48e3-7203-47f1-853b-4dd836cd0913)
![v4 title change](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/221539/3e2901fb-e01a-44c7-a83d-13f0d137d136)

**Comment by dsasser** [comment]
> I'm running through another round of testing to validate the results.

I have performed another round of tests and the results are the same.

## Issues Found

- New revisions are not always created during forms migrations.
- The 'Changed Title' flag is not being set during migration

### New revisions are not always created during forms migrations
In the forms migration, it is setup to create a new revision when any form node is updated

![Screenshot 2024-03-19 at 3 09 36 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/221539/37932634-7f05-489c-b120-60f435323089)

So the expectation is that we would end up with a fresh revision each time the migration needs to update the node. This is not happening; there is no new revision created (now new row is created in the revision tables).

For instance, I updated the a form's title in the UI and published it: 
![Screenshot 2024-03-19 at 3 20 14 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/221539/cf4f5087-bb63-4fdd-b431-9d759fa4d1a0)

This created a new node revision with the revision id (vid) of 850759 (not displayed in the screenshot). I then changed the same form's title in the CSV directly and ran the migration:

![Screenshot 2024-03-19 at 3 31 14 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/221539/ba8902b9-40d4-48ed-a6ab-5e8281227385)

This shows that the previous revision is being squashed by the new changes. There is no data integrity issue here, but this does represent a gap in revision retention.

### The Changed Title flag is not being set during migration
The Changed Title flag is not being set during the form migration, seemingly intentionally to avoid recursive node->save() loops. Below describes that the `isSyncing()` method is returning TRUE for every form during the migration.

![Screenshot 2024-03-19 at 3 57 45 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/221539/f69ec6e9-4d41-4074-8245-ab6c7447728f)

I was however able to trigger the flag by changing the form title in the UI:

![Screenshot 2024-03-19 at 3 20 14 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/221539/e2ecbf04-2826-4627-9e16-aa32dd4a63e7)

**Comment by dsasser** [comment]
> > I'm wondering if the "Form name" field vs. "Title" is part of the issue there?
> 
> I know where the changed title flag is being set and how it works, but this is a good reminder that there are two fields involved, so I'll dig into that and surface what the code is doing with that in mind.

The 'Changed Title' flag only operates on the Form Title (field_va_form_title). The Form Name (field_va_form_name) is only mentioned in code in one place, and that is just to move it to a fieldset when editing a Form node.

![Screenshot 2024-03-20 at 9 26 45 AM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/221539/4f287632-fb3f-4366-90d2-3966096f2506)



Also of note is that the flag should be sending Slack notifications, which are not working. I have not diagnosed this at all. I'll open a separate ticket for handling Forms flag notifications.

**Comment by jilladams** [comment]
@dsasser I don't think we ever pursued the world where flags send slack notifications. We'd thought a lot about it but never got that work prioritized. It's all detailed in this epic for a future time: [Form flag notifications #11456](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11456)

I'm gonna go ahead and close #17570 in light of that.

**Comment by jilladams** [comment]
Merr - wrong, Jill. 

I see the code pic now, #va-forms channel. Looking back through that channel, the last notification sent to slack was here: https://dsva.slack.com/archives/CUB5X5MGF/p1624256239383100, June 2021. Notifications haven't worked since that point. I'm gonna reopen the ticket I just closed, but I don't know that it's a modern priority, since it's been broken forever?

**Comment by jilladams** [comment]
This turned out to be a pure SPIKE and the ACs that weren't completed here are now ticketed for prioritizing.
