### ISSUE TITLE
VAMC/VBA Service Locations punch list for fixing issues

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#17454]
## Description
Tugboat links:
- Tugboat env: https://tugboat.vfs.va.gov/65255ca9c573c9cdb2d06792
 - CMS: https://pr15622-xptmfsnjoodldn85nzgkrgljqtfbz24b.ci.cms.va.gov/
 - Web (front end): https://web-xptmfsnjoodldn85nzgkrgljqtfbz24b.ci.cms.va.gov/
   
The following punchlist items have been identified as items to be fixed.

## Items to complete (launch blocking)
- Related to "Unspecified" and is there a holistic solution rather than individual solutions
  - #17513 
  - #17516 
  - #17518
  - #17415

## Items to complete with priority, not launch blocking
- #17514 
- #7416 
- #17511 
- #17381

**Comment by xiongjaneg** [comment]
Discussed in product sync and moved to refinement schedule

**Comment by davidmpickett** [comment]
FYI @xiongjaneg @mmiddaugh @jilladams I have migrated the information from this punchlist into the main launch ticket for ease of single reference https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16825
