### ISSUE TITLE
Switcher on Lovell VA experience's make-an-appointment allows changing to Lovell TRICARE experience

### ISSUE THREAD

**Issue by eselkin** [department-of-veterans-affairs/va.gov-cms#17469]
## User Story or Problem Statement

As a Lovell TRICARE user I might wind up on the make-an-appointment page for VA users and click the link to switch to the TRICARE experience with incorrect information. 

We want all links to that page to be removed in favor of pointing users to the MHS Genesis Patient Portal with the Top task links. So the switcher should be removed.

## Acceptance Criteria
- [x] Switcher is removed from `/lovell-federal-health-care-va/make-an-appointment/`

## Team
Please check the team(s) that will do this work.

- [ ] CMS Team
- [ ] Public Websites
- [x] Facilities
- [ ] Accelerated Publishing

**Comment by xiongjaneg** [comment]
PR merged, waiting for it to go live on prod

**Comment by xiongjaneg** [comment]
@eselkin Is this supposed to be live in prod now? I'm still seeing the change to TRICARE link at the top of the VA Make an appointment page.
<img width="1069" alt="Screenshot 2024-03-12 at 4 25 05 PM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/73648238/2d7450dd-2245-4793-ab8f-00283f477dc1">

**Comment by eselkin** [comment]
They were having trouble getting content-build released today. Not sure if they got it yet.

**Comment by eselkin** [comment]
Nope they haven't gotten it out yet

**Comment by xiongjaneg** [comment]
Verified now live on prod, closing
<img width="1224" alt="Screenshot 2024-03-14 at 9 36 00 AM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/73648238/1ec223fe-bd38-49f4-a5b1-6e89aaa94794">
