### ISSUE TITLE
[Aging Content MVP] Document implementation/behavior of the Full-width banner aging content MVP

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-cms#17468]
## Description

The Aging Content Full-width Banner MVP has been completed and needs documentation created.

### User story

**AS A** PO/PM/Engineer
**I WANT** to document the implementation & behavior of the Aging Content Full-width Banner MVP
**SO THAT** anyone who needs to use it/fix it/change it (present teams or future teams) may do so with minimum effort.

## Acceptance criteria
- [ ] Create typical documentation for this project

**Comment by dsasser** [comment]
After discussion it was decided to fold this work into the [FWB MVP ticket](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15506).
