### ISSUE TITLE
Onboarding Template - Therisa Tran

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-cms#17461]
# Welcome to the VA-CMS Team!

This ticket contains all of the onboarding activities for a new member joining the VA-CMS Team. 

**VFS-CMS Start Date:**  3/6/24

**Team info:**
- Product Owner: Erika Washburn
- Program Manager:  Michelle Dooley
- Product Manager: Grace Kretschmer

###
- [x] Meet with your Program Manager for a brief orientation to the CMS Team.
- [x] Read about the CMS Team and see full team roster ([link](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/cms ))
- [x] Read the [VA.gov platform crew principals](https://depo-platform-documentation.scrollhelp.site/getting-started/platform-crew-principles).
- [x] Review relevant [Platform orientation](https://depo-platform-documentation.scrollhelp.site/getting-started/Calendly-Orientation-Sessions.2133393543.html#CalendlyOrientationSessions-GeneralOrientation) recorded sessions.
- [x] Review [Platform website](https://depo-platform-documentation.scrollhelp.site/) to understand services and process.
- [x] Explore [VA.gov](https://www.va.gov/)

### VA security clearance / VA onboarding paperwork
Getting onboarded to the VA can take a few weeks to a few months. We encourage you to prioritize these tasks before any team tasks.
- [x] Wait to receive an email directing you to the paperwork you should fill out for secure access to relevant VA systems. Federal contractors are required to complete many of the same forms as federal employees. If you're not sure which you contract you are on, ask your Delivery Manager.  
- [x] Complete and submit your initial paperwork per contract instructions, including setting up your fingerprinting appointment. 
-  [x] When you are notified to complete your e-QIP (the online version of the federal standard investigation form, SF 86), it will require a lot of background information. [Review page 7 of the SF 86 guide](https://www.dcsa.mil/Portals/91/Documents/pv/mbi/standard-form-sf-86-guide-for-applicants.pdf) in advance for the list of information you'll need to collect to complete e-QIP

### Drupal Content Management System
Gaining product knowledge about the CMS can take some time. These activities can be completed in any order and are secondary to your VA security clearance onboarding tasks above.
- [x] [Watch the 2021 Drupal GovCon presentation about the project](https://www.youtube.com/watch?v=WN4bGjEuQdM).
- [x] Why are VA Medical Centers changing their websites? Watch the [2-minute YouTube video](https://youtu.be/Xrv5wCv6cKY).
- [x] Why are Vet Centers important to Veterans? Watch the [2-minute YouTube video](https://www.youtube.com/watch?v=VMzkZNbKk1I).

 
### What products do we support?
- [x] Read the [product outlines](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/cms/product-outlines) in the repository for a non-inclusive view of the platform. Be mindful of the dates, as some of these products have not been shipped but may still live in our backlog.

### Access 
Regardless of your role, please review these access notes. Your Program Manager will have set up most of the tools for you (with the exception of SOCKS). This list is for you to verify along the way:

#### SOCKS - VA network proxy
The VA network is required for Drupal CMS and other VA tools and usually requires a VA ID card (PIV or Smartcard). Until you get your paperwork approved and ID card, SOCKS proxy is a back door to some of these tools. This is the first priority for week two. 
   - [ ] File a [SOCKS proxy request](https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html) and select the label for your team. See https://github.com/department-of-veterans-affairs/va.gov-team/issues/68549
     
   - [x] Provide a screenshot of the email that confirms your eQip transmittal date. This is an acknowledgement that your paperwork is being processed from a security standpoint. You cannot receive SOCKS access prior to this point in your onboarding.
   - [ ] [Request a Github personal access token first](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token). You only need to do the "repo" panel in that form and leave the other panels as is. It may take a day or two for the SOCKS proxy request to be fulfilled before you can complete the rest of the SOCKS process. This can be a complex process. Post in #sitewide-program Slack channel if you need help from a current member - we're happy to help.

#### Github - for issue tracking and document sharing
  - [x] [VA.gov request instructions](https://github.com/department-of-veterans-affairs/github-user-requests/issues/new?labels=add-user-to-org%2C+new-user%2C+user-created&template=add-user-to-the-va-organization.md&title=ADD+USER+TO+ORG+-+%5BUSERNAME%5D) - Your Program Manager should have already requested this for you so double check with them before submitting a new request.   
  - [x] [Intro to CMS Team Github](https://github.com/department-of-veterans-affairs/va.gov-cms#readme)
  - [x] [CMS team list](https://github.com/orgs/department-of-veterans-affairs/teams/vfs-cms-team/members) - Same as above. You must be added to this team to contribute in Github.
    - [ ] Optional: New to Github and markdown? [Learn about writing on Github](https://docs.github.com/en/github/writing-on-github/getting-started-with-writing-and-formatting-on-github) or [watch a tutorial video](https://youtu.be/TBbtbKplUoc)

#### Slack - for instant messaging
Your Program Manager should have already requested this for you, but if not, view the [request instructions](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/orientation/slack-requests.md)
  - [x] [Review Slack etiquette](https://slack.com/blog/collaboration/etiquette-tips-in-slack).
  - [x] Update your profiles in Slack (in the Oddball and DSVA workspaces), add a calendar link
  - [ ] [This is a description of other channels](https://docs.google.com/spreadsheets/d/1_lZzectbSzs8zt4dvTFJTiPURxa0Kfp3xinYEuZdqq4/edit#gid=0) to put on your radar. Note that many are going to be dependent on which workstream you're in.

#### Drupal - for logging into the CMS (SOCKS or VA access with PIV card required)
Drupal is the VA's content management system of choice. For anyone on our team, it's beneficial to have a CMS user account so you can login, look at settings, and understand how the CMS works at a high level. If you need help completing the technical steps here, schedule 30 mins with your Delivery Manager.
  - [ ] [Learn about the different Drupal environments](https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/READMES/environments.md)
  - [ ] Drupal production environment access (SOCKS or VA network required) - in DSVA #cms-support channel, use the Slack workflow to file a helpdesk support request. Ask the helpdesk to create a Drupal user for you in [prod.cms.va.gov](prod.cms.va.gov). 
     * Product Managers should request an Administrator account. 
     *  DevOps team members require an administrator account. (SOCKS or VA access with PIV card required)
     * Standard practice for other roles is to have minimal access in prod (content editor or even a blocked account) and full admin access in lower environments.

##### Tugboat - for previewing in demo environments (SOCKS or VA access with PIV card required)
Tugboat is a development server platform where you can preview CMS code changes pre-production. 
  - [ ] [Tugboat for non-engineers](https://prod.cms.va.gov/help/demo-environments-tugboat-guides)
  - [ ] [Tugboat for engineers](https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/READMES/tugboat.md)

#### Other tools
- [x] Confluence (your Program Manager will get you added)
 - [ ] [Datadog](https://depo-platform-documentation.scrollhelp.site/getting-started/Request-access-to-tools.969605215.html#Requestaccesstotools-Requestaccess) to access monitoring metrics (your Delivery Manager will get you added)

## For Developers
 - [ ] [VA.gov tools overview](https://depo-platform-documentation.scrollhelp.site/getting-started/Request-access-to-tools.969605215.html)
 - [ ] [Access to dev & staging to be able to replicate the SSO piece of the login experience](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/5838) (SOCKS or VA access with PIV card required)
 - [ ] Review the [VA.gov Design System](https://design.va.gov/) which includes [how to provide feedback]([https://design.va.gov/about/feedback](https://design.va.gov/about/feedback))

 **VA Platform documentation**
 - [x] [VA Technical Architecture Overview](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/platform/engineering/TechnicalArchitectureOverview.md) - describes technical architecture of va.gov (+ api.va.gov)
 - [x] Deployments: https://depo-platform-documentation.scrollhelp.site/developer-docs/deployments
  - [x] [Deployment crib notes](https://docs.google.com/spreadsheets/d/164H07n4FChg-JxJZu964nfg2wAX0kPD0SjTfZMhzj_I/edit#gid=0) with detail re: various repos, timings, & support
 - [x] Front-end workflow: https://depo-platform-documentation.scrollhelp.site/developer-docs/frontend-workflow
 - [ ] [Front-end steps to run & build VA.gov locally](https://depo-platform-documentation.scrollhelp.site/developer-docs/run-and-build-va-gov-locally)

**Comment by gracekretschmer-metrostar** [comment]
Oddball is confirming if Therisa will need to submit e-qip because she has already submitted it.

**Comment by ttran-Therisa** [comment]
Does this acts as my screenshot that my eQip is finished since it was skipped?
<img width="1010" alt="Screenshot 2024-04-04 at 10 05 14 AM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/146353301/9c73ddea-d054-4ad1-8706-755deb98d74c">

**Comment by gracekretschmer-metrostar** [comment]
Therisa's PIV card is scheduled for 5/16.
