### ISSUE TITLE
[Aging Content MVP] QA / Testing of Full-width Banner MVP of Aging Content

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-cms#17467]
## Description

This ticket covers fully testing the new Aging Content Full-width banner notification MVP.

### User story

**AS A** PO/PM/Engineer
**I WANT** the Aging Content Full-width banner notification MVP fully tested
**SO THAT** the feature is usable and works as designed.

## Acceptance criteria

- [ ] TBD

**Comment by dsasser** [comment]
After discussion it was decided to fold this work into the [FWB MVP ticket](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15506).
