### ISSUE TITLE
Make devshop tasks smarter 

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#1746]
If a delete is triggered on a pr environment, because the PR has been merged, the environment should not keep running all the other tasks and run the delete last.    If delete/destory is called, all other tasks should be removed and or stopped.
![image](https://user-images.githubusercontent.com/5752113/81728841-11ceff00-9459-11ea-9e1f-4a42c07feaa5.png)

**Comment by swirtSJW** [comment]
Example of one stuck in destroy http://devshop.cms.va.gov/hosting/c/pr1740.ci.cms.va.gov

**Comment by ElijahLynn** [comment]
Closing for now as we are likely moving off of DevShop.
