### ISSUE TITLE
Internal links on Vet Center Spotlights do not link correctly on the FE

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#17473]
## Describe the defect
In the CTA field in Local Spotlights on the Vet Center content type, the Editor is able to add internal links to other VA.gov pages. When they do this however, the link on the front end is not generated properly, instead it is created as `entity:node/XXXX`

It is working on VBA, so follow the pattern being done on VBA.

## To Reproduce
1. Go to the [Hilo Vet Center page in the CMS](https://prod.cms.va.gov/hilo-vet-center)
2. Scroll down to the Local Spotlight section
3. Notice that the first local spotlight has a CTA with an internal link and link text as a phone number.
4. Then go to the [Hilo Vet Center page on the FE](https://www.va.gov/hilo-vet-center/)
5. Scroll down to the Spotlight section
6. Try to click on the phone number link and notice that it doesn't work
7. Also, notice that when you hover over it, you can see the improperly formatted link

## AC / Expected behavior

- [x] CTA links are properly formatted and are able to be followed on the FE
- [ ] Accessibility review (tag Laura for PR review)

## Screenshots
![Screenshot 2024-03-11 at 9 04 35 AM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/106678594/3fe5f78c-b553-494e-8003-6ce4b3c05741)

![Screenshot 2024-03-11 at 9 04 44 AM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/106678594/8eea439e-a1a1-44f7-90c4-a2463e0e5e92)

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [ ] `Public Websites`
- [x] `Facilities`
- [ ] `User support`
- [ ] `Accelerated Publishing`

**Comment by xiongjaneg** [comment]
@eselkin @maxx1128 Would you please review, refine, and point? Let's try to get in this upcoming sprint. Thank you!

**Comment by maxx1128** [comment]
I would point this to a **2.** There is likely an existing function for correctly formatting links passed through the CMS that we could use. If there isn't, the existing filters would be a helpful starting point for making one.

**Comment by eselkin** [comment]
This usually happens when the links should be written one way but the editor puts in something like the uri. In VBA we chose to present the URL instead of the URI of the link. I've seen other locations where the CTA is the phone number, but I can't find one now. I think the href of that link would be tel:<whatever> instead of /<xyz_vet_centernode>

**Comment by laflannery** [comment]
@eselkin I completely agree with you that this is not a good CTA in general, however putting that aside for the moment, this was the first example on Prod that I was able to find of an internal link.

You can see in the screen shot that the link in Prod is /hilo-vet-center so it should be rendering correctly regardless of what the link text is.

Also, I found this because I was testing something in Staging, created a link in the CTA spotlight - using the proper process by search for the title of the node, clicking it and saving the node - and when I previewed it the same thing happened so there is definitely something not right happening here with internal links.

**Comment by eselkin** [comment]
Yeah. I get it. I think switching to using the URL instead of the URI for the link coming from Drupal will probably fix the incorrect showing on the frontend. So I point at a 2.
