### ISSUE TITLE
Finalize design recommendations for Service Location Address paragraph type

### ISSUE THREAD

**Issue by davidmpickett** [department-of-veterans-affairs/va.gov-cms#17489]
## User Story or Problem Statement

The Address section of Service Locations has been reviewed in #14845 and #17342, but it still needs work before it's ready for engineers to implement.

[Latest design](https://www.figma.com/file/ikCp2eOubIgbN1TwyEYIrN/VAMC-Master?type=design&node-id=550%3A10915&mode=design&t=KsgmBDYaEZV2aLeu-1)

## Description or Additional Context 

**Latest iteration:**

![Section content](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/104526584/fdab33aa-8c0c-4801-9fde-e6967c4b0329)

## Acceptance Criteria
- [x] Improve help text
- [x] Consider possible combinations of required fields
- [x] Document recommendations in Figma
- [x] Update [implementation ticket](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17488) with specific updates

**Comment by thejordanwood** [comment]
I show this on the [Locations headers page](https://www.figma.com/file/ikCp2eOubIgbN1TwyEYIrN/VAMC-Master?type=design&node-id=550%3A10915&mode=design&t=jwFr5W082TDCSPP5-1) in the VAMC Master Figma file. 

Status update:

- It was decided in [UX sync](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17669#issuecomment-2035662432) that the Name field is required, but the Building name / room number fields will not be required. That's shown in the mockups. 
- I've suggested different help text for the Name field for @davidmpickett and @laflannery to review.  There is an [open comment thread in Figma](https://www.figma.com/file/ikCp2eOubIgbN1TwyEYIrN?type=design&node-id=590-1230&mode=design#767204027) discussing this.

**Comment by jilladams** [comment]
From discussion with Dave / Amanda: 
- We are proposing a pattern for CMS design system, to add input placeholder text
- Implementation ticket will wait til we have discussed that with Marisa for CMS Team reference.

We'll keep this ticket open to track those steps.

**Comment by davidmpickett** [comment]
> From discussion with Dave / Amanda:
> 
> * We are proposing a pattern for CMS design system, to add input placeholder text
> * Implementation ticket will wait til we have discussed that with Marisa for CMS Team reference.
> 
> We'll keep this ticket open to track those steps.

So turns out that placeholder text is an accessibility no-no. So we won't be pursuing that. But I think the new UX is a lot clearer than the current implementation

@aklausmeier this is ready for your approval. After you have signed off I will update the implementation ticket.

**Comment by thejordanwood** [comment]
@aklausmeier had [a small update](https://www.figma.com/file/ikCp2eOubIgbN1TwyEYIrN?type=design&node-id=619-3817&mode=design#773468999) to this that I've made on the mockups. 

@davidmpickett I've updated the implementation ticket to show specific changes, but please feel free to review.

**Comment by davidmpickett** [comment]
Thanks @thejordanwood! I just went through and updated the implementation ticket to be a little more Drupal developer friendly. I also took out the bullet point about making `field_clinic_name` required. That will have broader content model implications and should be a separate piece of work. All of the other changes are still improvements and can be implemented ASAP
