### ISSUE TITLE
Critical and High Vulnerabilities in va.gov-cms

### ISSUE THREAD

**Issue by JNHQ** [department-of-veterans-affairs/va.gov-cms#1748]
I'm writing from Ion Channel, a cybersecurity firm that monitors U.S. critical infrastructure.  In response to information on the escalating prevalence of software dependency attacks, and in an effort to preclude such an attack on a federal civilian agency infrastructure, we are reaching out to the developers of publicly released federal software projects that have critical and high severity vulnerabilities, to make them aware of these findings and to encourage immediate remediation.

Our analysis of va.gov-cms identifies a Critical and fifteen High vulnerabilities in the codebase, including lodash and other prototype pollution risks. Screenshot is attached. For detailed findings or to coordinate further, e-mail info@ionchannel.io . This is not a sales pitch - all findings will be delivered as open data. 

[va backend screenshot.pdf](https://github.com/department-of-veterans-affairs/va.gov-cms/files/4618095/--)

attached file removed by Swirt

**Comment by swirtSJW** [comment]
@JNHQ Sorry, this sounds a bit like spam at minimum, or worse a fishing attempt.  Today seems to be your first foray into assisting agencies by providing a vulnerability scan report. Please clarify under what office's direction you are undertaking this work?

**Comment by swirtSJW** [comment]
I just removed the attached file, in case it is not what it appears to be.

**Comment by JNHQ** [comment]
@swirtSJW I commend your vigilance on attachments, but this is neither a phishing attempt or spam. Ion Channel is a defense contractor and the findings are valid. We engage with federal agency development teams, but only use GitHub public issues as a last resort when contact information for security personnel is not posted (e.g. within a security.md or README), which is best practice. We have been sending the full JSON analysis to project owners privately, in an effort to be responsible. I can post them as plain text in this Issue, if you have no way of sanitizing attachments or accepting unsolicited private communications. You can also reach out to me privately on GitHub.

**Comment by swirtSJW** [comment]
Pardon my skepticism, you have been doing this for less than 24 hours but speak as though it is perfectly routine for you.  Ion Channel may be a defense contractor, but under what Government office are you undertaking this work?  Sorry, we need a better way to verify the truth of your claims.

**Comment by JNHQ** [comment]
@swirtSJW You will be receiving findings through another channel and can coordinate appropriately with project personnel.
