### ISSUE TITLE
Documentation: Review Figma files for design accuracy

### ISSUE THREAD

**Issue by thejordanwood** [department-of-veterans-affairs/va.gov-cms#17485]
## Details

Review Public Websites and Facilities Figma files for accuracy. Files should show the final design on FE or in Drupal so that engineers can check that their work is correct. 

**Folders to review:**

- [CMS - Facilities Editor Experiences](https://www.figma.com/files/project/199987654)
- [CMS - Public Websites Editor Experiences](https://www.figma.com/files/project/181240145)
- [Facilities](https://www.figma.com/files/project/175597252)
- [Public Websites](https://www.figma.com/files/project/175597240)

## Acceptance Criteria
- [x] All recent files in the CMS - Facilities Editor Experiences folder are reviewed
- [x] All recent files in the CMS - Public Websites Editor Experiences  folder are reviewed
- [x] All recent files in the Facilities folder are reviewed
- [x] All recent files in the Public Websites folder are reviewed

## Team
Please check the team(s) that will do this work.

- [ ] CMS Team
- [x] Public Websites
- [x] Facilities
- [ ] Accelerated Publishing

**Comment by aklausmeier** [comment]
Let's prioritize recent work first and if this becomes larger than a 5, let's re-sync to plan a path forward.

**Comment by aklausmeier** [comment]
@thejordanwood this is just clean up, no UX lead review needed on this one

**Comment by thejordanwood** [comment]
List of recent files I reviewed from the Facilities and Public Websites folders. These are folders that have the FE designs. 

**Facilities**
- Facility locator
- Police Transparency
- VBA regional office
- VAMC Master (This file is a work in progress for a current project. Changes are coming, but it’s as accurate as it can be for now. )

**Public Websites**
- Campaign landing pages
- DUW
- Outreach and events
- PACT Act (Changes are coming to the content. This file will be updated at a later date.)
- Income limits (Content is accurate, but styling didn’t carry over from Sketch to Figma. Styling should be fixed when [the migration ticket](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16677) is completed.)

**Comment by thejordanwood** [comment]
List of recent files I reviewed from the CMS - Facilities Editor Experiences and CMS - Public Websites Editor Experiences folders. These are folders that have the Drupal designs.

Some of these reflect the ideal state of what the design could be or the proposed design that hasn't been implemented yet. I've tried to leave notes or any indication in those files to better explain where the design is at. 

**CMS - Facilities Editor Experiences**
- VBA content specs (Reflects ideal state)
- VAMC facilities

**CMS - Public Websites Editor Experiences**
- Benefit content model (Reflects ideal state)
- Campaign landing pages
- CTA w/ links
- Events
- Full width banners
- HUB list menu
- Magic headers (I combined this file with the Benefit content model file.)
- News promo block
- Q&A - CLPs
