### ISSUE TITLE
URL Change for: Palo Alto 1 VA Mobile Clinic

### ISSUE THREAD

**Issue by omahane** [department-of-veterans-affairs/va.gov-cms#17495]
### Implementation date
When does this request need to be live:
ASAP

Parent ticket: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17494

### Instructions for URL redirect
(Note: This issue will be used from initial request through implementation to ensure all individuals working on this are notified of status updates.  Please do not create multiple issues to track different steps.)
- [x] Notify VA stakeholders as appropriate.
- [x] Link the related facility closure / rename issue. [Palo Alto 1 VA Mobile Clinic - #17494](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17494)
- [x] Create a URL redirect in the [devops](https://github.com/department-of-veterans-affairs/devops) repo in `ansible/deployment/config/revproxy-vagov/vars/redirects.yml`
- [x] Add the "Awaiting redirect" flag to the facility node with a revision log message that includes a link to this ticket, preserving the node's current moderation state.
- [x] Redirects deploy weekly on Wed. at 10am ET, or by requesting OOB deploy (of the revproxy job to prod) in #vfs-platform-support. After deploy, validate that the URL redirect is deployed. (Note: In the event of a facility closure or a name change,  validate that this occurs before making the Lighthouse csv changes.)
- [x] Update this ticket with a comment that the redirect has been deployed.
- [x] Remove the "Awaiting redirect" flag on the facility node with a revision log message that includes a link to this ticket, preserving the node's current moderation state.
- [ ]  Notify helpdesk via comment on ticket or Slack message in #cms-support that changes are ready for review.

#### URL Redirect
| Current URL  |  Redirect Destination or New URL |
| ---  |  --- |
| https://www.va.gov/palo-alto-health-care/locations/palo-alto-1-va-mobile-clinic/ | https://www.va.gov/palo-alto-health-care/locations/ |

#### URL removal example (update with actual ID and URL to remove)
| Facility API ID  |  Full VA.gov URL |
| ---  |  --- |
| vha_640QA | https://www.va.gov/palo-alto-health-care/locations/palo-alto-1-va-mobile-clinic/ |

### Instructions for canonical URL removal
- [x] Try to find the facility via the Facility Locator, using the Facility API ID (e.g. https://va.gov/find-locations/facility/"facility_api_id"). If it is not available, proceed.
- [x] Update the [CSV in Lighthouse](https://github.com/department-of-veterans-affairs/lighthouse-facilities/blob/master/facilities/src/main/resources/websites.csv) removing the row with the Facility API ID.
- [x] Create a PR in the [lighthouse-facilities repo](https://github.com/department-of-veterans-affairs/lighthouse-facilities), tagging the Lighthouse team.
- [x] Post a message in the #cms-lighthouse channel in Slack, with an @mention to a Lighthouse team member.
**Note: there's no check to see if it's not returning anything, as it should already be not showing anything in the Facility Locator.**

**Comment by ian-sears** [comment]
I want to address the above notice: "No canonical URL exists for this Mobile VA Clinic"
This System, **Palo Alto Health Care, had two (2) Mobile VA clinic (trucks)**. name Palo Alto 1 Mobile and Palo Alto 2 Mobile, respectively. One of them is going away (being moved to a new facility in a different state, for example).
**There will be only one (1) Palo Alto VA Mobile Clinic (truck)** and so I suspect a single, Canonical Link.

However, the web page title **Palo Alto 1 VA Mobile Clinic** is facility-tied to Facility Locator API ID **vha_640QA (now removed from VAST)**.

So, the remaining Palo Alto VA Mobile Clinic, currently named **Palo Alto 2 VA Mobile Clinic** (Facility Locator API ID **vha_640QB****) will remain, and be the only Mobile Clinic at the Palo Alto VA System. It then makes sense that eventually this "name" would change from "2" to simply "Palo Alto VA Mobile Clinic - and thus a Canonical URL.

However, to get this whole change moving and under way, I am delaying that request change until after the existing work here is completed. This naming convention caused unnecessary confusion and delayed out process.

**Comment by ian-sears** [comment]
If I am correctly picking up on this process, then this "Removed from Source" facility, "Palo Alto 1" [vha_640QA] **is awaiting a URL change** (redirect, actually) to the /locations/ of this VAMC System.
https://va-gov.atlassian.net/browse/VAHELP-7144 authorizes/confirms from the Editor that this is ready for that step.

I, on the other hand am awaiting for this step to complete/resolve, so that I can Archive the Facility page at: 
https://prod.cms.va.gov/node/1977/edit

**Comment by ian-sears** [comment]
**Reference discussion thread**: https://dsva.slack.com/archives/C02730UEZPS/p1712084530100769

**Comment by omahane** [comment]
This code has been merged. The deploy should happen on 4/10.

**Comment by omahane** [comment]
The code has been deployed. The CSV removal has been requested. I am closing this.
