### ISSUE TITLE
Conduct VA Regional Office editor-facing research sessions

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#17499]
### User story
**AS A** researcher
**I WANT** to conduct research sessions with participants
**SO THAT** we can get feedback on the VBA Regional Office editor experience

**Guidelines**
- [Moderator guidelines](https://depo-platform-documentation.scrollhelp.site/research-design/conducting-research-sessions)
  - [Research Safety guidelines](https://depo-platform-documentation.scrollhelp.site/research-design/research-safety-and-emergency-exit-strategies) 
- [Notetaker guidelines](https://depo-platform-documentation.scrollhelp.site/research-design/notetaker-guidelines)
    - For Editor-facing research, recruit a member of the product team to take notes
- [Observer guidelines](https://depo-platform-documentation.scrollhelp.site/research-design/observer-guidelines)

**Recruitment Trackers**
- Editor-Facing research should track participants in the [VA.gov CMS UX research base](link TBD from CMS Platform team)

**No-shows and rescheduling**
- If a participant doesn't show up at the scheduled start time, they should be contacted
   - In Editor-facing research, the Moderator should contact the participant through email or Microsoft Teams
- If the participant hasn't shown up within 15 minutes of the start, consider it a no-show
  - See if the participant can reschedule for a different available slot 
  
## Acceptance Criteria

**Before each session**
- [x] Moderator(s), Notetaker(s), & Observer(s) reviewed guidelines for their role(s)
- [x] Moderator completes session-specific [prep tasks](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17155)

**After every session**
- [x] Observers and Notetakers share their notes with Research Lead
- [x] Researcher debriefs (i.e., into note-taking spreadsheet/Mural)
- [x] Session recording and transcript downloaded from Zoom
- [x] Researcher reviews notes taken by observers 

**After ALL sessions have been completed**
- [x] All notes stored in the research folder on github
  - [x] Notes documents for cancelled/no-show sessions have been deleted
  - [x] Prep hand-off for subsequent researcher(s)

## Resources
[Research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/regional-offices/research/2024-01-editor-facing/research-plan.md) 
[Conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/regional-offices/research/2024-01-editor-facing/conversation-guide.md)
[Notetaking Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1707332466795/09bc172b8554e12831c422ca893d65a63745f05c?sender=u3f35bedf61955cb051f44770)

**Comment by aklausmeier** [comment]
@ALogsdon3 can you upload your recruitment tracker for this work to the Facilities team sharepoint > [UX Research folder](https://dvagov.sharepoint.com/:f:/s/SitewideFacilitiesTeam/Es-NKHca2vFNl28Vu6Kr-h4BEEWdgejYO3RmA1BBe7V9Jw)

**Comment by ALogsdon3** [comment]
I have finished all ACs on this ticket, so I'll close it now.
