### ISSUE TITLE
VBA Field featured content spotlight should allow no CTA

### ISSUE THREAD

**Issue by eselkin** [department-of-veterans-affairs/va.gov-cms#17500]
## User Story or Problem Statement
VBA local spotlights aren't downloaded from drupal with equivalent formatting to Centralized Content spotlights. Allow CTAs to be empty list.

## Description or Additional Context 
If statement for CTA presence needs to be added and only then add CTA.

## Steps for Implementation
Add if statement, move adding of CTA content into that if statement

## Acceptance Criteria
- [x] VBA facility local spotlight is added with no CTA and build finished
- [x] Spotlight is displayed without CTA

## Team
Please check the team(s) that will do this work.

- [ ] CMS Team
- [ ] Public Websites
- [x] Facilities
- [ ] Accelerated Publishing

**Comment by xiongjaneg** [comment]
Verified in Tugboat
<img width="732" alt="Screenshot 2024-03-12 at 4 27 36 PM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/73648238/6a278a5f-5ce0-42ab-9045-622c9e453dcf">
