### ISSUE TITLE
Hiding hours does not work with multiple Service locations

### ISSUE THREAD

**Issue by omahane** [department-of-veterans-affairs/va.gov-cms#17501]
## Describe the defect
When a service has only one service location, clicking "Use the facility's hours" shows the facility hours in the node:edit and clicking on "Provide specific hours for this service" shows the form elements. 

This showing and hiding does not work consistently when multiple service locations are added.

## To Reproduce
1. Edit a [service location](https://main-ewg1nnhm743rr5wsupwpmmslavlrdng1.demo.cms.va.gov/node/30379/edit)
2. Add 2 more service locations
3. Click the **Hours** accordion
4. Click "Use the facility's hours"
5. Click "Provide specific hours for this service"
6. Note that the form elements and/or facility hours are not showing or hiding appropriately

## AC / Expected behavior
The facility hours should show when "Use the facility's hours" is selected and the hours form elements show when "Use the facility's hours" is selected.

### A single service location
![single-service-location](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/766573/b8a7cac0-8b94-4fac-83c1-896f20a584a0)

### Multiple service location
![multiple-service-locations](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/766573/606eacba-e7a0-4ee4-b818-61066eab2b9c)

 ## Additional context
The error thrown in the console is
```
Uncaught TypeError: $(...).once is not a function
    at displayHours (service_location_hours.js?v=1.x:14:20)
    at service_location_hours.js?v=1.x:64:11
    at NodeList.forEach (<anonymous>)
    at HTMLDivElement.<anonymous> (service_location_hours.js?v=1.x:59:21)
```
Some examples of this fix:
https://github.com/department-of-veterans-affairs/va.gov-cms/pull/14852/files

Drupal guidance around the change from jQuery once() to Drupal once():
https://www.drupal.org/node/3158256

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [ ] `Public Websites`
- [x] `Facilities`
- [ ] `User support`
- [ ] `Accelerated Publishing`

**Comment by xiongjaneg** [comment]
@omahane @Becapa Would you review, refine and point? If possible, it would be good to get in the sprint starting tomorrow.

**Comment by omahane** [comment]
I believe that I have a fix for this:

https://github.com/department-of-veterans-affairs/va.gov-cms/assets/766573/15ffefca-c19a-4f99-b54f-23ab25dbfff6

**Comment by omahane** [comment]
@xiongjaneg @jilladams I just confirmed on [prod](https://prod.cms.va.gov/node/15466/edit) that the hours toggle is working correctly when there are multiple service locations. This can be closed.

**Comment by xiongjaneg** [comment]
@omahane I verified this worked in prod for existing multiple service locations for an existing service.
