### ISSUE TITLE
Add additional tugboat instance for content-build Continuous Integration

### ISSUE THREAD

**Issue by edmund-dunn** [department-of-veterans-affairs/va.gov-cms#17510]
## User Story or Problem Statement
content-build CI is failing on `vagovdev` and `vagovstaging`. All build jobs run concurrently, and both showed increased memory usage over time until they received a 504 error from the content build tugboat mirror. https://tugboat.vfs.va.gov/6042eeed6a89945a99399d3d 
It appears that both build jobs hitting the same tugboat instance with the same queries at the same time were causing it to fail. 

## Description or Additional Context 
We are adding a second prod mirror, so now we have:

- content-build-branch-builds-dev
- content-build-branch-builds-staging

## Steps for Implementation
![Screenshot 2024-03-13 at 13 06 48](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/109987005/5aea8155-3505-4e03-b156-0cb25dd2354e)

## Acceptance Criteria
- [ ] Add second mirror, `content-build-branch-builds-staging`
- [ ] rename mirror, `content-build-branch-builds` to `content-build-branch-builds-dev`

## Team
Please check the team(s) that will do this work.

- [x] CMS Team
- [ ] Public Websites
- [ ] Facilities
- [ ] Accelerated Publishing

**Comment by edmund-dunn** [comment]
@gracekretschmer-metrostar FYSA

**Comment by 7hunderbird** [comment]
:shipit:
