### ISSUE TITLE
Facility address should not be displayed on FE when editor selects "Use the facility's street address"

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-cms#17514]
## Description
In Tugboat, the VAMC Top Task pages and VBA Service accordions are displaying the Facility Address when "Use Facility Address" is checked in the Service Location. This is not the desired behavior. VAMC service accordions currently have the correct behavior.

### VAMC Top Task Page - [Los Angeles](https://web-xptmfsnjoodldn85nzgkrgljqtfbz24b.ci.cms.va.gov/greater-los-angeles-health-care/register-for-care/)

![Screenshot 2024-03-28 at 12 56 23 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/0e8dc2f8-85df-49d5-b26a-f77ca025d2a4)

### VBA Facility Service Accordion - [Cleveland](https://web-xptmfsnjoodldn85nzgkrgljqtfbz24b.ci.cms.va.gov/cleveland-va-regional-benefit-office/locations/cleveland-va-regional-benefit-office/#family-member-and-caregiver-be)

![Screenshot 2024-03-28 at 12 57 08 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/44fe66ff-37e8-4661-9fb2-69352dc77dd9)

### VAMC Facility Service Accordion - [Pittsburgh](https://web-xptmfsnjoodldn85nzgkrgljqtfbz24b.ci.cms.va.gov/pittsburgh-health-care/locations/pittsburgh-va-medical-center-university-drive/#addiction-and-substance-use-care)

![Screenshot 2024-03-28 at 1 17 29 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/5b9744c9-af8d-44e0-9bc7-cbd6eb054b9b)

## Eng notes
In the liquid template, for the address under the "name of clinic heading": a conditional is missing to check if the "use facility street address" checkbox is checked, before printing. 

## Acceptance Criteria
- [ ] If "use facility street address" box is checked, do not show the street address on the front end
- [ ] If "use facility street address" box is not checked, the user will be prompted to enter a street address, which should be displayed on the front end
- [ ] Applies to these templates
  - [ ] VAMC Top Task pages (Billing and Insurance, Register for Care, Medical Records)
  - [ ] VBA Facilities -> Service accordions
  - [ ] VAMC Facilities -> Service accordions [Currently working as intended, but including to check for regression]

**Comment by davidmpickett** [comment]
By contrast, the VBA facility services on Tugboat currently **are** showing the Facility Address when this box is checked. See [Cleveland VA Regional Benefit Office -home loans](https://web-xptmfsnjoodldn85nzgkrgljqtfbz24b.ci.cms.va.gov/cleveland-va-regional-benefit-office/locations/cleveland-va-regional-benefit-office/#veteran-benefits).

![Screenshot 2024-03-20 at 6 03 53 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/efe3a506-d312-4a6e-981f-8b12fe28e22c)

This is not what the [Figma design](https://www.figma.com/file/88Gw7fmUkDbheSAHjIpHn7/VBA-Regional-Office?type=design&node-id=0%3A1107&mode=design&t=QDFQsCzaM3U8aIs4-1) shows, so would want to make sure @thejordanwood signs off on the proposed direction for both these cases.

**Comment by xiongjaneg** [comment]
Take to UX sync to discuss current behavior in VAMC (not showing address), but VBA is different.

**Comment by davidmpickett** [comment]
For reference, here is a previous ticket where the current logic was implemented https://github.com/department-of-veterans-affairs/va.gov-cms/issues/7339

**Comment by thejordanwood** [comment]
@davidmpickett I agree with the logic on the ticket you linked. 

> Correct logic for the "use facility street address" checkbox according to the following:
> 
> if "use facility street address" box is checked, do not show the street address on the front end - show only wing/floor/room info
> if "use facility street address" box is not checked, the user will be prompted to enter a street address, which should be displayed on the front end

Additional logic would include:

If "use facility street address" box is checked and no wing/floor/room info is added, then nothing should show for this section.

**Comment by davidmpickett** [comment]
Thanks @thejordanwood! I am going to update this ticket to turn it in to a ticket to implement the desired behavior

**Comment by eselkin** [comment]
We have to modify the liquid template a bit. Not a big lift, but worthy of at least 2 points. The conditional needs a bit of restructuring and testing.

**Comment by mmiddaugh** [comment]
@jilladams @davidmpickett 
@aklausmeier and I discussed this work and agree that although it needs to be addressed, it is not a launch blocker.

**Comment by davidmpickett** [comment]
> @jilladams @davidmpickett @aklausmeier and I discussed this work and agree that although it needs to be addressed, it is not a launch blocker.

Thanks. I updated it's position in the [launch plan](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16825) and the [sprint 2 draft plan](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17687) to reflect this.

**Comment by eselkin** [comment]
Started to do this but then realized I can't test since data is not available from any mirror of prod yet and the SL tugboat ceased to exist after the merge.

**Comment by davidmpickett** [comment]
Confirmed on prod for VAMC top task pages
![Screenshot 2024-05-16 at 12 57 37 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/5e81fafd-8df7-44da-aba8-890924cff620)

Can't confirm VBA on Prod, but seems like this was done in a partial template and should fix all service locations
