### ISSUE TITLE
Hide Service Options and Appointments fieldsets on Non-Clinical Services

### ISSUE THREAD

**Issue by davidmpickett** [department-of-veterans-affairs/va.gov-cms#17515]
## Empty required fields creates bad editor UX
The [current migration](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15559) focuses on VAMC Facility Health Services. It did not do anything to VAMC Facility Non-Clinical Services. This makes sense, because there's no existing appointment data to migrate. However it also means that some key required fields are blank. 

**Service options**
- Office visits
- Virtual support

**Appointments**
- Appointment introduction text
- Is online scheduling available for this service?

By default, these required fields are hidden in accordions, so if an editor is coming in to make an edit to an unrelated area (like adding a phone number to Contact), they will be suddenly bombarded by error messages when they try to save. 

### Screenshots
<details><summary>Editor coming in to add a phone number, they have filled out all visible required fields</summary>

![screencapture-pr15622-xptmfsnjoodldn85nzgkrgljqtfbz24b-ci-cms-va-gov-node-50893-edit-2024-03-13-16_25_17](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/b97b6bbf-2713-4b0e-bea3-1e643d613fdb)

</details>

<details><summary>And then they click save and have Errors galore</summary>

![screencapture-pr15622-xptmfsnjoodldn85nzgkrgljqtfbz24b-ci-cms-va-gov-node-50893-edit-2024-03-13-16_25_42](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/0b1e3d7f-a91c-4e20-86e7-baa4762e81e3)

</details>

## Even if an editor populates these fields, nothing will display on FE, so why have them at all?

Current use of non-clinical services is confined to three top task pages where the nature of the service (e.g. Pay in Person) is contextualized for the user already. The Service Options information would be redundant, if not confusing. These tasks all also seem to be walk-in only vs. requiring an appointment, so the need to specify that within the service location is less clearl.

Because the Service Location paragraph type is the same across multiple types of Services, it's not easy to customize it for specific services. But it is possible.

## AC / Expected behavior
- [ ] The Service Options and Appointments fieldsets don't show up on Service Locations on VAMC non-clinical services
- [ ] There are no regressions for the UI on VAMC Facility health services
- [ ] There are no regressions on the UI on VBA Facility health services
- [ ] There are no regressions on the UI on Service Regions

**Comment by mmiddaugh** [comment]
@davidmpickett related to Virtual support, it occurs to me that the Billing and insurance (nonclinical service) pages already address the option for getting assistance by phone (i.e., from [Maine health care](https://www.va.gov/maine-health-care/billing-and-insurance/): For questions about the copay balance of your VA health care bill, call us toll free at the number below.)

![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/55411834/bbe6318d-9241-457e-a51a-aacbf15952eb)

**Comment by thejordanwood** [comment]
@davidmpickett Here's a possible design solution. Maybe we can show the red required asterisk on the accordion label.

<img width="565" alt="Screenshot 2024-03-22 at 3 41 22 PM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/104526584/3610de44-5237-4ed3-9648-f544eb425074">

**Comment by aklausmeier** [comment]
Is it possible to show any accordion with required fields expanded by default?

**Comment by davidmpickett** [comment]
> @davidmpickett Here's a possible design solution. Maybe we can show the red required asterisk on the accordion label.
> 
> <img alt="Screenshot 2024-03-22 at 3 41 22 PM" width="565" src="https://private-user-images.githubusercontent.com/104526584/316163109-3610de44-5237-4ed3-9648-f544eb425074.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1OTA2NjUsIm5iZiI6MTcxMTU5MDM2NSwicGF0aCI6Ii8xMDQ1MjY1ODQvMzE2MTYzMTA5LTM2MTBkZTQ0LTUyMzctNGVkMy05NjQ4LWY1NDRlYjQyNTA3NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyOFQwMTQ2MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMjJmZmYzOGQxM2JlMGQ0MGIzNTI1NTU2ZTMyNTNjMTQ3NzlmOWNjNmQxNTYxYTE3MjE0NWE1YWJkYzM5N2FiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.PsBbAu4OH-GXaII7mEXlz1I5iy6nEkxuvh5QUYaq_2o">

Turns out this is a [known upstream Drupal issue](https://www.drupal.org/project/drupal/issues/3171835) with the Claro admin theme. It should be doing exactly what Jordan is showing based on our Drupal settings.

**Comment by davidmpickett** [comment]
> Is it possible to show any accordion with required fields expanded by default?

We can choose per accordion whether to have it expanded by default or not. It's controlled by a checkbox in Site Building section of Drupal.

![Screenshot 2024-03-27 at 8 49 03 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/d61e8af0-380c-469c-8924-2388cfb18611)

[CMS told us](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16073) to CONSIDER if we should have these accordions expanded by default. We [chose](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15989#issuecomment-1889980440) to have them closed by default. Maybe with this new information we need to RECONSIDER?

**Comment by jilladams** [comment]
Ported from #17967: 

@omahane this ticket is the topic Laura brought up at the end of UX sync today. I would love to get your thoughts: 

1. She suggested data migration updates to set null values for the non-clinical services, to fix this UX. Does that seem light or heavy? 
2. We talked on the call about the fact that these fields from the Service Location paragraph will likely _never_ matter for non-clinical services. They'll be exposed in this location on Drupal, but won't map to anything in FE templates. Laura and I _think_ it's true that the paragraph type is one size fits all, and we can't hide these fields on non-clinical services. Could you confirm that, or correct us if that's wrong, if you know? 

cc @davidmpickett @aklausmeier

**Comment by davidmpickett** [comment]
Additional notes: I previously talked with @mmiddaugh  about this ticket (might have been in a 1on1) and she said that while it’s not great, it’s not launch blocking. Suggest pulling this up the Team Refinement list from priority 20 to priority 5 given the renewed discussion

**Comment by davidmpickett** [comment]
> Ported from #17967:
> 
> @omahane this ticket is the topic Laura brought up at the end of UX sync today. I would love to get your thoughts:
> 
> 1. She suggested data migration updates to set null values for the non-clinical services, to fix this UX. Does that seem light or heavy?

IMO We really should not be doing anything that will extend the time it takes to run the Migration. Adding 600 Non-Clinical services on top of the 16,000 VAMC Facility Health services may not seem like a lot (approximately 3% increase), but we also know that the migration runs slower the longer it runs. So this could easily end up adding 30 mins onto the ~4 hour process. 

Also increases the chance of something going wrong when we don't need to do anything here. There's no existing data to migrate, so can be handled post migration.

> 2. We talked on the call about the fact that these fields from the Service Location paragraph will likely _never_ matter for non-clinical services. They'll be exposed in this location on Drupal, but won't map to anything in FE templates

I would caution against saying these fields will _never_ matter for non-clinical services. The non-clinical service pattern is currently only used on those three top task pages, but we have an [open exploration around using it for VA Police pages](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17343) and also have a [ticket to consider migrating](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15897) "prepare for your visit" accordions into non-clinical services as a future content model hardening project.

That being said, I think one of the logical follow up iterations to consider for Service Locations is implementing conditional logic on the Drupal side to make certain sections of the form visible/hidden required/not required based on initial selections and other factors. 

> Laura and I _think_ it's true that the paragraph type is one size fits all, and we can't hide these fields on non-clinical services. Could you confirm that, or correct us if that's wrong, if you know?
> 
> cc @davidmpickett @aklausmeier

Paragraph Types are generally one size fits all by design, yes. But that's not necessarily the end of the story.

@omahane Could we use a Form Alter to hide the Service Options and Appointments sections of Service Locations when they are embedded in a VAMC Non Clinical Service? 

1. I think we have other instances where we hide required fields unless a certain value is set elsewhere in the form and editors are able to save those Content Types. Maybe this is Operating Status more info?
2. I think we're also conditionally passing a value (default appointment intro text) to Service Locations based on what Content Type it is.

If both those things are happening, logically i think that means we could do this, but want to validate with you

**Comment by aklausmeier** [comment]
Thank you @davidmpickett. I am very much interested in the possibility of `consider ... implementing conditional logic on the Drupal side to make certain sections of the form visible/hidden required/not required based on initial selections and other factors.`

**Comment by omahane** [comment]
> She suggested data migration updates to set null values for the non-clinical services, to fix this UX. Does that seem light or heavy?

I don't think that this would make any difference for editors. If someone opens a page with a field that has a null value that is also required, they will need to set the value before they can save the node.

**Comment by omahane** [comment]
Are there values we'd want to set for these fields?

**Comment by omahane** [comment]
Yes, we could alter the form with custom code to set required fields to not be required for non-clinical services. We could also hide them. It sounds like the preference is to hide them, as long as doing so would also mean they were not required.

**Comment by davidmpickett** [comment]
> > She suggested data migration updates to set null values for the non-clinical services, to fix this UX. Does that seem light or heavy?
> 
> I don't think that this would make any difference for editors. If someone opens a page with a field that has a null value that is also required, they will need to set the value before they can save the node.

I think this comment was supposed to say set _default_ values instead of null values. Null is the current state.

> Are there values we'd want to set for these fields?

We hadn't determined those yet because we hadn't fully refined this ticket. If we went in the direction of setting default values, I would specify those in the ticket body before it was started.

> Yes, we could alter the form with custom code to set required fields to not be required for non-clinical services. We could also hide them. It sounds like the preference is to hide them, as long as doing so would also mean they were not required.

Yes. If we could hide them (and thereby make them unrequired) that would be much preferable given that they currently have no FE impact. Do you have an estimate of what the level of effort would be for hiding them? I can update the ticket body to reflect that direction

**Comment by omahane** [comment]
Re: Setting values
"Set null values" as in `null` to `default`. Got it. Just misread that.

Re: setting them
We could do this by writing an additional script to run on deploy (well, post-deploy), technically. 

Re: hiding
We are doing something not unlike this already with Service locations in 
`va_gov_facilities/va_gov_facilities.module` with `function va_gov_facilities_field_widget_single_element_paragraphs_form_alter`. As a result, we'd need to do some amount of refactoring to create this new functionality without interfering with an alter of the same paragraph.

I'd give it a 5.

**Comment by davidmpickett** [comment]
> Thank you @davidmpickett. I am very much interested in the possibility of `consider ... implementing conditional logic on the Drupal side to make certain sections of the form visible/hidden required/not required based on initial selections and other factors.`

@aklausmeier FYI I just stubbed out a ticket as a holding spot for some of the use cases I've had in my mind: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18031

**Comment by davidmpickett** [comment]
@omahane I reframed the ticket to be about hiding the fieldsets and pointed it at a 5 per your comment. I'm moving it to Ready

**Comment by davidmpickett** [comment]
Confirmed on Prod ![screencapture-prod-cms-va-gov-node-51989-edit-2024-05-28-14_40_10](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/86d9a067-6864-4377-94cf-8eb1c89896e8)

**Comment by davidmpickett** [comment]
I also created a revision on a node to confirm I was able to save a node without filling in any of the hidden required fields. (I later deleted my revision).

Only thing that my revision did was set a value for a hidden boolean. Makes sense that this value has to be set in the background since booleans don't really have a NULL state. 

![screencapture-prod-cms-va-gov-node-50129-revisions-view-873442-893081-visual-inline-2024-05-28-14_45_14](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/93aa4438-f948-4d50-8e8f-a349f9886314)

**Comment by davidmpickett** [comment]
@omahane Should this be working on Node:Create as well as Node:Edit?

![screencapture-prod-cms-va-gov-node-add-vha-facility-nonclinical-service-2024-05-28-14_39_45](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/40233ce0-ae28-4776-ae38-41819da23b8e)

Your PR's QA steps indicate that this should cover Creating a new Service, but the conditional `$form_id === 'node_vha_facility_nonclinical_service_edit_form'` seems to only indicate Node:Edit

**Comment by omahane** [comment]
> Your PR's QA steps indicate that this should cover Creating a new Service, but the conditional `$form_id === 'node_vha_facility_nonclinical_service_edit_form'` seems to only indicate Node:Edit
@davidmpickett Yes, that's what it looks like, but I tested it. That being said, I apparently didn't correctly test it, though I'm unsure how I missed this.

**Comment by jilladams** [comment]
^ PR above addresses Dave's comment, seems like. I do want to make sure we verify the remaining ACs here before we call it good, since those aren't explicitly addressed during PR review: 

 There are no regressions for the UI on VAMC Facility health services
 There are no regressions on the UI on VBA Facility health services
 There are no regressions on the UI on Service Regions

Christian's busy with LH V0 deprecation work currently, afaik. We can discuss if you need help for that!

**Comment by davidmpickett** [comment]
@omahane I'm still seeing these fieldsets on prod https://prod.cms.va.gov/node/add/vha_facility_nonclinical_service

But your code has also merged into main https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/docroot/modules/custom/va_gov_vamc/va_gov_vamc.module#L54

???

**Comment by davidmpickett** [comment]
I spun up a fresh Tugboat and this is working as intended there

![screencapture-main-jdujzwgvp8kmj36hcfonqejlgtq5b6st-demo-cms-va-gov-node-add-vha-facility-nonclinical-service-2024-05-31-13_26_32](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/53ec84c7-dea2-4993-8117-c642e7bda3b3)

But Prod is still showing the fields
![screencapture-prod-cms-va-gov-node-add-vha-facility-nonclinical-service-2024-05-31-13_29_45](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/1ec1b3f3-b0f1-4037-9f41-bf5d24fab200)

**Comment by davidmpickett** [comment]
Verified on prod!
![screencapture-prod-cms-va-gov-node-add-vha-facility-nonclinical-service-2024-06-03-10_10_15](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/cbd8dc84-373a-4249-be38-ab046d83c68b)

Also verified

> There are no regressions for the UI on VAMC Facility health services
> There are no regressions on the UI on VBA Facility health services
> There are no regressions on the UI on Service Regions
