### ISSUE TITLE
Service location: "Unspecified" referral should not be included in front end display

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-cms#17513]
## Description
Calais VA Clinic, Laboratory and pathology services has the referral requirement set to "unspecified", which is correct based on migration. 

- [Prod node for Laboratory and pathology - Calais VA Clinic](https://prod.cms.va.gov/maine-health-care/locations/calais-va-clinic/laboratory-and-pathology)
- [Prod front end for Calais VA](https://www.va.gov/maine-health-care/locations/calais-va-clinic/)
- [Tugboat FE](https://web-xptmfsnjoodldn85nzgkrgljqtfbz24b.ci.cms.va.gov/maine-health-care/locations/calais-va-clinic/)
- [Tugboat service node](https://pr15622-xptmfsnjoodldn85nzgkrgljqtfbz24b.ci.cms.va.gov/maine-health-care/locations/calais-va-clinic/laboratory-and-pathology)

## Current behavior
Unspecified referral requirement maps to a FE display of "A referral is not required"
<details>
<summary> CMS referral option </summary>

<img width="1317" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGZiQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3679d3ef7c7c831f27d54fd2f765632d9ebcd69b/image.png" alt="image.png" />
</details>

---
<details>
<summary> FE display </summary>

<img width="669" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNHJiQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5a181920114c322eb8e3b43ab2eba29410eef66e/image.png" alt="image.png" />
</details> 

## Expected behavior
An Unspecified referral requirement should not be included in the front end display. 

## ACs
- [ ] When a service location's "Is a referral required" question is set to "Unspecified," nothing is shown on the front end.

**Comment by eselkin** [comment]
I still have a question about what "2" is. I think I asked before but was unsure. We see it in the data but I don't see it in the former content.
So "not_applicable","unknown" should be taken out and added as another when condition

**Comment by davidmpickett** [comment]
> I still have a question about what "2" is. I think I asked before but was unsure. We see it in the data but I don't see it in the former content. So "not_applicable","unknown" should be taken out and added as another when condition... Unless "2" is `Unspecified` now... perhaps.

[Way back in 2021](https://github.com/department-of-veterans-affairs/va.gov-cms/commit/a87c879b99d0405cff68aab786acbf109e70e46f) it seems that `2`(Unknown) became `not_applicable`(Unspecified)

**Comment by eselkin** [comment]
So, "2", "not_applicable" and unknown should be conditions where nothing is shown for that icon and statement about appointments.

**Comment by maxx1128** [comment]
**End of Spring 106 update:** the pull request for this ticket is completed and is waiting for review before being merged.

**Comment by davidmpickett** [comment]
[Confirmed on Tugboat!](https://web-xptmfsnjoodldn85nzgkrgljqtfbz24b.ci.cms.va.gov/maine-health-care/locations/calais-va-clinic/) 
![Screenshot 2024-03-27 at 8 05 44 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/8e840600-6d46-4757-a817-d54e044e87f3)
