### ISSUE TITLE
After pagination component update, only 3 pages of listing are showing

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#17526]
## Describe the defect
We recently [updated the pagination](https://github.com/department-of-veterans-affairs/content-build/pull/1941) on Resources & Support, News, and Stories to use the v3 component. We were notified that the pagination is only showing the first 3 pages in the pagination now. You can directly get to the other pages using the URL but if you do that the pagination at the bottom still only shows pages 1-3. 

You can see this on [Page 5 of Boston News](https://www.va.gov/boston-health-care/news-releases/page-5/) and [Page 4 of Greater Los Angeles Stories](https://www.va.gov/greater-los-angeles-health-care/stories/page-4/)

## AC / Expected behavior

- [ ] All available pages of listings should be available through the pagination component, the user should not need to access pages directly through the URL

## Screenshots
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/106678594/b4ab0794-c3dc-44a2-826b-0c792940799e)

 ## Additional context
Previously the pagination would show a max of 3 pages but as you paged through the numbers it showed would advanced. We got this from the way back machine:
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/106678594/ce177b85-44d4-462f-8fff-b706bfe3ea46)

Because we updated to the component I don't know if this would work exactly like what we had before but we do want to make sure users can access all the pages we have available somehow.

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [x] `Public Websites`
- [x] `Facilities`
- [ ] `User support`
- [ ] `Accelerated Publishing`

**Comment by laflannery** [comment]
@randimays I have a theory, and my theory is that the component does not work the way our custom implementation was working before (where it was only showing 3 pages - the current page and then the next 2).

So for what we have implemented currently - since we are saying there's a max page count of 7, I think we would want to use the [Seven or less variation of the component](https://design.va.gov/storybook/?path=/docs/uswds-va-pagination--default#with-seven-or-less) and then all 7 pages would show, however, and this is a big however, not all listings have the same number of page results (e.g. Boston New releases has 6 total, Greater Los Angeles Stories have 10)

Is there a way within the component to set it up so the `pages` prop is dynamic? Or do we actually have to set this at a set length and therefore only show say, 6 pages max for all listings that this pagination controls?

**Comment by randimays** [comment]
Update here: this was supposed to deploy to prod today but it appears there are some deploy issues. It'll likely get triaged and merged in tomorrow or Wednesday.

<img width="913" alt="Screenshot 2024-03-18 at 5 56 18 PM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/19175324/273235d5-9fc0-4528-9180-0d4c5469aaba">

**Comment by laflannery** [comment]
I just confirmed that this is on prod and showing the proper pagination - [Greater Los Angeles Stories](https://www.va.gov/greater-los-angeles-health-care/stories/page-3/):
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/106678594/186ad335-dbcf-40be-a123-7cbe4cba485c)

**Comment by randimays** [comment]
@laflannery Thank you for checking! I validated a few other pages in prod; we're good to go! Closing.
