### ISSUE TITLE
Analytics event inventory/audit in preparation for G4

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-cms#17532]
## Description
As announced 3/12 in VFS-All Teams, the Analytics team has asked that all VFS Teams create and share an inventory of any and all recordEvent actions currently living in their codebase -- also known as custom events so that we can ensure these events are transitioned properly for GA4 

**Inventories are due no later than Friday, April 5.** 
Forms submitted after this date will still be transitioned, but we risk gaps in metrics and reporting the closer we come to the 1 July 2024 UA cut-off date.

Questions should be posted to the #vfs-analytics Slack channel. A GA4 Migration FAQ document will be published on the Platform Website in the coming days. 

## Tasks
- Follow the instructions within [this Github Form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=johnny-jesensky-adhoc&labels=analytics-insights%2C+analytics-request%2C+ga4-migration%2C+analytics-insights-form&projects=&template=analytics-custom-event-request-%28WIP%29.md&title=VFS+Custom+Events+for+%5BTeam+Name%5D+%26+%5BProduct%28s%29%5D) to complete and submit the event inventory/audit template spreadsheet 

## Acceptance criteria
- [x] Complete event inventory/audit template spreadsheet has been submitted, including event names and any other included variables

**Comment by xiongjaneg** [comment]
Is record-event triggering something similar to regular events in GA? That and some other questions need to be explored.

**Comment by jilladams** [comment]
Public Websites references: 
* https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17412
* Public Websites' custom events spreadsheet: https://docs.google.com/spreadsheets/d/1fDsRQct_QMJ5nd3bTRDgwrfbFo_PqzdFQqYecJouic8/edit#gid=0
* Thread with Fran / Analytics: https://dsva.slack.com/archives/C1Q4294JJ/p1710345718294789
    * "we really need to know the event names and any other included variables in order to make sure everything is being captured."

**Comment by eselkin** [comment]
[Facility Locator Product Spreadsheet](https://docs.google.com/spreadsheets/d/1shb0jv1qALlxA_Z1qnn0WPA-YdKXvRENChD6AtPnmmg/edit?usp=sharing)

A little uncertain if they ONLY want custom events or if they also want events from DST components and things that generate random events like raw anchor tags (I see them in adswerve). I'm putting them in with tags like HTML element and they/we can hide/delete those rows if they are not worried about those.

**Comment by eselkin** [comment]
Tickets created for Analytics team here:
https://github.com/department-of-veterans-affairs/va.gov-team/issues/79968
https://github.com/department-of-veterans-affairs/va.gov-team/issues/79969
https://github.com/department-of-veterans-affairs/va.gov-team/issues/79970

**Comment by jilladams** [comment]
You're my hero. I think we can close this ticket, and track further asks on this topic in those tickets as needed. (Subscribing to them for updates.) THANK YOU! And way to hit a deadline, Eli. 🏆
