### ISSUE TITLE
Design: Vet Center link to intake form

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-cms#17541]
## Description
As a Veteran, service member, or family member, I want to be able to express my interest in Vet Center services from the webpage and request that someone will follow up with me. 

Vet Centers are implementing Salesforce as a platform for managing outreach activities. This implementation will include a digital intake form for the contact information of a prospective client which can be routed to the appropriate Vet Center for follow-up. The form will use the same URL, regardless of where it is initiated or routed so we should be able to easily point to it from the Vet Center pages.

Vet Centers do not yet have top task links - this may be an option. 
It may be desirable to make the link to the locations page more prominent during this work. The link to "View more [name] Vet Center locations" is currently below the Location and contact information and is displayed in normal text which may blend in with surrounding content. 

**Draft link text:**
"Begin intake process"

**This may be done along with a broader redesign for Vet Center pages**

<details>
<summary> Current link to locations </summary>

<img width="625" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeG5uQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5a5b5b2636c74329a2c44f40a85d99291a77faa0/image.png" alt="image.png" />
</details>

## Tasks
- First: UX design for appropriate location and link

**Comment by davidmpickett** [comment]
@mmiddaugh Do we have any details on what the Veteran value of this intake form will be? What task or purpose does it fill for them? Trying to think how'd we frame this in a Top Task sense. 
- "Request support"
- "Suggest activity"

**Comment by Agile6MSkinner** [comment]
Open Question:
Are all Vet centers ready to link?

Decided:
Satellite locations included

Jordan will create quick and simple design to link to ticket, then we will add engineering-ready ACs

**Comment by aklausmeier** [comment]
Vet Center stakeholders will get back with @mmiddaugh on a few possible actions Veterans will be able to act on with this intake form, hopefully in the next week.

**Comment by mmiddaugh** [comment]
@davidmpickett, Veterans and other prospective clients will use the linked form to express an interest in learning more about or initiating Vet Center services - link label guidance pending. 
@Agile6MSkinner, link can be added to all locations once made available

**Comment by jilladams** [comment]
@mmiddaugh to provide starter link text for design purposes, actual URL may come later for eng build.

**Comment by aklausmeier** [comment]
@thejordanwood This is draft link text. There is flexibility to revise if you think of better verbiage while in design. 

Draft link text: 
**Begin intake process**

**Comment by thejordanwood** [comment]
I created a mockup for this in the [Vet Center Figma file](https://www.figma.com/design/EVd3q06ukAbVS61Q8MwRAT/Vet-Centers?node-id=906-8577&t=ekm6i0y1NI1kktU4-1). It's being reviewed along with the work [in this ticket](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18389).

**Comment by davidmpickett** [comment]
Closing as complete. Link is in design as expected and no revisions were requested in initial feedback on #18389. Any additional revisions will be part of that process

**Comment by jilladams** [comment]
Ticket is closed, but: final copy for the link may be ~a month for the copy to be finalized. Form doesn't exist in Salesforce yet, will be created by ~Sept 10. At that point we will get the link, and we want CAIA's help to finalize copy in #18863
