### ISSUE TITLE
Update Twitter link in PW products which have this link to use new wording

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#17546]
## Description
Twitter's official name changed to X last year. We have a link in the footer that still currently only says "Twitter" however in order to accurately reflect this we should change this link to include the correct name of the service. Can this link be updated to say "X (formerly Twitter)" - this follows [the guidance received from CAIA](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15390#issuecomment-1994737759).

## Acceptance Criteria
- [ ] Footer link is updated to say "X (formerly Twitter)"
- [ ] Campaign Landing Pages
- [ ] Events
- [ ] Any other areas
- [ ] Requires design review

## Team
Please check the team(s) that will do this work.

- [ ] CMS Team
- [x] Public Websites
- [ ] Facilities
- [ ] Accelerated Publishing

Footer link screenshot:
![image](https://github.com/user-attachments/assets/0f875744-19a0-42cb-bd09-32ace7a59fed)

**Comment by laflannery** [comment]
@FranECross This is not a priority - it just came up at my Monday meeting and Dave said that we should at least have a ticket for it

**Comment by FranECross** [comment]
@FranECross Ask Carol W to transfer to their repository.

**Comment by laflannery** [comment]
This probably shouldn't be transferred as only the Footer link applies to the DST and all others have been completed

**Comment by FranECross** [comment]
Closing as a no op; all instances of PW products have the new verbiage. The footer link is in the DST wheelhouse now.
