### ISSUE TITLE
VBA Cypress test sometimes causes pipeline failures

### ISSUE THREAD

**Issue by Becapa** [department-of-veterans-affairs/va.gov-cms#17559]
## User Story or Problem Statement
The vba_facility.feature is failing periodically in the pipeline which causes a need for the staging build and deploy to be re-run.

## Description or Additional Context 
This appears to happen because there are Scenarios that are being run in parallel and one of the Scenarios opens the node edit form for a specific node but never saves it and never breaks the lock when it's done. Because of this, any other Scenario that runs afterwards which tries to edit the same node is not able to because it is locked.

We should add steps to the end of the test that break the lock on that specific node.

## Steps for Implementation
Add the following lines to the end of the last scenario (`Enable banner segment and ensure expected fields are present`) in the vba_facility.feature cypress test:
`And I scroll to position "bottom"`
`And I click the "Unlock" link`
`And I click the "Confirm break lock" button`

## Acceptance Criteria
- [x] Cypress test has been updated
- [x] Cypress test can be run more than once and still pass

**Comment by omahane** [comment]
This work has been completed and should be deployed tomorrow 4/2/2024.
