### ISSUE TITLE
Preview Button for VBA Facility results in 502 Bad Gateway error

### ISSUE THREAD

**Issue by helpdeskanalyst79** [department-of-veterans-affairs/va.gov-cms#17556]
I had a ticket that an editor stated, they are having issues with the VBA Facility Preview button not working , and it gives a 502 Bad Gateway error each time they press it for a preview.  It was brought to my attention, that this issue has been going on for a while, ~~and this function should be removed from the VBA~~. This ticket is for tracking purposes.

Preview on VBA Facility is a requirement for Facilities and VBA launching VBA Regional Office Pilot MVP. This is how editors review their edits and share their edits with stakeholders to review. This is a required process that has been a part of all Facilities launches. This did work previously but does not work now for VBA Facility. It works on other Facilities products.

## Acceptance Criteria
- [ ] When Preview is clicked for VBA Facility, the editor is able to view the single page preview.

**Comment by xiongjaneg** [comment]
@gracekretschmer-metrostar Submitting for your consideration ASAP. This is a launch blocker for VBA Facilities. Michelle will discuss priority with Erika.

**Comment by EWashb** [comment]
Is there a related slack thread that we can link to this ticket for context? @xiongjaneg @jilladams

**Comment by xiongjaneg** [comment]
@EWashb This is the[ first thread ](https://dsva.slack.com/archives/CDHBKAL9W/p1710868483591049)in a series of unthreaded Slack messages on this topic in the CMS Support channel. Thanks!

**Comment by gracekretschmer-metrostar** [comment]
Thanks y'all. I will sync with @EWashb tomorrow to refine and determine next steps.

**Comment by helpdeskanalyst79** [comment]
Sounds good.

**Comment by EWashb** [comment]
@edmund-dunn and @7hunderbird  found the issue.
https://prod.cms.va.gov/albuquerque-va-regional-benefit-office/locations/albuquerque-va-regional-benefit-office the preview generates this error: 
Node 4171: 1.496s
Pulling feature flags from Drupal...
(node:8) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated
(Use `node --trace-deprecation ...` to show where the warning was created)
TypeError: Cannot read property 'value' of undefined
    at liquid.filters.processCentralizedBenefitsHotline (/home/node/src/site/filters/liquid.js:1165:40)
    at exports.Context.callFilter (/home/node/node_modules/tinyliquid/lib/context.js:387:28)
    at /home/node/node_modules/tinyliquid/lib/vm.js:312:15
    at next (/home/node/node_modules/tinyliquid/lib/utils.js:492:9)

Scooting this back to our Facilities friends for the fix. If yall could let @helpdeskanalyst79 @ian-sears know a timeline on the fix when you know it, they can respond to the editor @jilladams

**Comment by EWashb** [comment]
Related[ slack thread](https://dsva.slack.com/archives/CT4GZBM8F/p1710958602902429) from CMS triage:
