### ISSUE TITLE
Sitewide V2: Facilities Sprint 1 Plan

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#17554]
## Schedule Notes
- Michael OOO 3/28-3/29
- Alexis OOO 3/29
- Dave OOO 4/5 & 4/8

## Sprint Priorities 🎯 
At the end of this sprint, what do we want to have accomplished/delivered?

Tickets for top priority:
- 🎯 UX: #17489
- 🎯 Drupal: #17516, #17518
- 🎯 FE: #17532

## UX
DISCUSS tracking ACs / use of epics / tasks.
- Service Location: #17489 needs refining
- VBA: #16906
- VBA/Vet Centers: #15349 needs refining -- is an epic. Are we saying work this whole epic now? 
    - VBA/Vet Centers: #17194 needs refining
        - blocked by #17195? 
- Police: #17343 needs refining

## Front End
DISCUSS: Analytics deadline April 5, Design system deadline for V1 deprecation where V3s exist = May 3. Progress to date indicates we need to focus on V3 adoption to hit date target. Or: push back on DS re: the deadline.

- Analytics: #17532 due Apr 5
- Facility Locator: #17409 -  a11y defect 2
- Service Locations: #17414 - launch blocking
- V1 deprecations: #16963 - May 3
- V1 deprecations: #16997 - May 3
- V1 deprecations: #17108 - May 3

### Other FE work
- Facility Locator: #16455 - actually 2 points? 
- Service Locations: #17415 - not launch blocking
- Adopt components: #17411 - 5pts
- Adopt components: #17410 - 5pts
- Adopt components: #16999 - May 3
- Adopt components: #16960 - May 3
- Adopt components: #16998 - May 3
- Adopt components: #17410
- Adopt components: #16952
- Adopt components: #16964
- Adopt components: #16957
- Adopt components: #16962
- Adopt components: #17066
- Adopt components: #17067
- Adopt components: #17068
- Adopt components: #16953
- Adopt components: #17095

## Drupal
DISCUSS: Christian working alone. Daniel or Edmund will need to be pulled in for code reviews. We will need to probably source QA on our team. We should expect a slow down as a result. 13 point suggested load may be high, even without text validation ticket.
- #17374 - discuss options for next step if needed
- Service Locations: #17516 - blocker
- Service Locations: #17518  - blocker
- Service Locations: #17381
- Service Locations: #17559

### Other Drupal work
- Service Locations: #17124  - 8 points
- Tickets that come out of #17374 
- Flagged facilities when ready

**Comment by mmiddaugh** [comment]
@xiongjaneg @jilladams 

[Consider: Update Non-clinical services Views to match FE display #17381](https://app.zenhub.com/workspaces/sitewide-facilities-639f5253e4b702a32376339e/issues/gh/department-of-veterans-affairs/va.gov-cms/17381) is listed twice under the Drupal heading, FYI
 -> one other related issue in Ready is [Add text validation to appointment custom text in Service Location #17124](https://app.zenhub.com/workspaces/sitewide-facilities-639f5253e4b702a32376339e/issues/gh/department-of-veterans-affairs/va.gov-cms/17124) -> might this one have been intended? 

Also - let's keep these two on the radar as we pushed them out of last sprint (each is 5 pts)
- [Replace content-build breadcrumb partial with V3 Component #17411](https://app.zenhub.com/workspaces/sitewide-facilities-639f5253e4b702a32376339e/issues/gh/department-of-veterans-affairs/va.gov-cms/17411)
- [Move content-build's breadcrumbs liquid logic to a liquid filter #17410](https://app.zenhub.com/workspaces/sitewide-facilities-639f5253e4b702a32376339e/issues/gh/department-of-veterans-affairs/va.gov-cms/17410)

**Comment by mmiddaugh** [comment]
UX candidate? [Review error states recommendations and feasibility for VBA content types #16906](https://app.zenhub.com/workspaces/sitewide-facilities-639f5253e4b702a32376339e/issues/gh/department-of-veterans-affairs/va.gov-cms/16906)

**Comment by xiongjaneg** [comment]
I put 17124 back on the list. My initial concern was that it's an 8 pointer, which is concerning given Drupal capacity. There will just need to be tradeoffs.

**Comment by jilladams** [comment]
Example for the UX / ACs discussion: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17643
