### ISSUE TITLE
VA Forms not creating new Revisions during migration

### ISSUE THREAD

**Issue by dsasser** [department-of-veterans-affairs/va.gov-cms#17567]
## Status
**[2024-04-05]** The CMS team took on this work. Putting this story into the Ice Box just in case we need to resurrect at any point.

## Description
The [Forms SPIKE](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17450) revealed that Forms migrations are [not creating revisions during updates](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17450#issuecomment-2008310102).

### User story

**AS A** Forms Editor
**I WANT** my edits to Forms to create revisions that don't get squashed
**SO THAT** I can see a valid and accurate revision history for all changes that occur

### Engineering notes / background

<details>
<summary>Running the migration in TB with a copy of the Prod CSV</summary>
Below demonstrates the problem. Here I simply spun up a fresh Tugboat, updated the migration config to use a copy of the Prod CSV that I control (I temporarily placed the CSV copy on S3 in a public location). I then ran the migration. It results in all Forms being updated (for what reason?) and two being created (why weren't these created in Prod?). Finally, the changes it does make do not create a revision, effectively hiding the previous revision metadata (no data loss occurs).

![Screenshot 2024-03-20 at 10 15 16 AM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/221539/b8934aea-10bf-4687-98d0-db057070fb11)

![Screenshot 2024-03-20 at 10 15 54 AM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/221539/6c141251-5dab-458c-9522-603c7efd9424)

![Screenshot 2024-03-20 at 10 18 39 AM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/221539/0d16576a-e2d8-4a49-9b72-0c4f9e57a2af)

![Screenshot 2024-03-20 at 10 20 53 AM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/221539/1c0e6afc-c0ca-406d-8f0c-60ae05939745)
</details>

<details>
<summary>Running the migration in TB with no CMS changes</summary>

![Screenshot 2024-03-20 at 10 36 22 AM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/221539/5b8c9cbe-6354-41d0-8e7f-aee18a9ed46e)

</details>

## Acceptance criteria
- [ ] Migration and manual revisions should create a fresh revision (don't overwrite prior revisions)
- [ ] Validate revisions are working function during node save in UI as well as when nodes are saved during migrations.

**Comment by jilladams** [comment]
Per Facilities research: 
> So I think this is something that happened in Drupal core. It looks like in 10.2 they made it so that when an entity is updating from a migrate there is an isSyncing flag that is being set. I guess this keeps the migrate from being able to set the update as a new Revision (see https://www.drupal.org/node/3052115). There is a workaround that's documented here: https://www.drupal.org/node/3426397

This is likely the same root cause for both revision logs, and for Title flags not getting correctly applied. Facilities has Drupal capacity to run this, so Michael is going to rally folks to discuss & make sure everyone's ok with the workaround.

**Comment by jilladams** [comment]
CMS resolved this issue. 
VA Forms now do get proper revision logs during migrations, e.g. https://prod.cms.va.gov/find-forms/about-form-21p-0519c-1-espanol

![Screenshot 2024-06-07 at 2 14 40 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/85581471/193598c9-7b80-410e-88ed-1858443e5e73)
