### ISSUE TITLE
Use web components for the homepage email signup form

### ISSUE THREAD

**Issue by randimays** [department-of-veterans-affairs/va.gov-cms#17568]
## Description

As part of this ticket: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17277 we attempted to convert the email signup form on the homepage to design system web components. Unfortunately, the simple implementation caused the form not to submit. We will need to explore further how to use the design system components to implement this form.

<img width="616" alt="Screenshot 2024-03-20 at 12 04 01 PM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/19175324/dcd8821b-df1d-4547-b992-6f50bd998305">

### User story

**End User's Point of View**
**AS A** Veteran, or their family member, caregiver or survivor
**I WANT** the email sign up form to submit correctly
**SO THAT** I can get the latest updates from the VA without errors

**PO/PM Point of View**
**AS A** PO/PM responsible for the sign up form on the VA.gov home page
**I WANT** the email sign up form to utilize web components
**AND** to submit correctly
**SO THAT** we are in alignment with the Design Team's current requests, as well as so that Veterans, their caregivers, family members and survivors can get the latest updates from the VA without errors

### Engineering notes / background
This email form is an integration of the [GovDelivery](https://granicus.com/solution/govdelivery/) platform. Submissions are sent to GovDelivery via the form action https://public.govdelivery.com/accounts/USVACHOOSE/subscribers/qualify and hidden input fields. 

Most recently modified here: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11389

## Acceptance criteria

**AC1: Veteran, their family member, caregiver or survivor successfully signs up for VA updates**
**GIVEN**: A Veteran, their family member, caregiver or survivor has entered their email address in the form in order to receive updates from the VA
**WHEN**: I click the 'Sign up' button
**THEN**: I want the form to submit my email address successfully so that I then receive updates accordingly

**AC2: Email sign up form on the VA.gov home page should use web components**
**GIVEN**: Web components are available for email fields
**WHEN**: the web components are implemented
**THEN**: the sign up form on the home page should function correctly by submitting the email address when "Sign up" up is clicked

**Comment by jilladams** [comment]
Added some notes to ticket body about the GovDelivery implementation on that form, for reference.

**Comment by randimays** [comment]
@FranECross @jilladams We can only complete part of this ticket right now. The input and the button on this form needed to be converted to web components. I have a PR open (#2008 above) to convert the input. But the `<va-button>` web component's `submit` property doesn't work yet, and it wasn't submitting the form data. @laflannery discovered an existing DST issue that describes this problem: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2379.

Should we keep this ticket open (in Blocked) until we can get the button converted? Meanwhile, I can merge the changes for the input. **Or** should we create a new ticket for the button specifically and close this one out for the input by itself?

**Comment by FranECross** [comment]
@randimays I like Option 2, so your code doesn't get old and you can release what you've done. (creating a new ticket for the button specifically). I'm happy to create another ticket if you'd like.

**Comment by randimays** [comment]
Thanks @FranECross! Do you mind adjusting the AC for this ticket and creating the new one please?

**Comment by FranECross** [comment]
Story created https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17790

@randimays Feel free to suggest edits or to edit as needed. Thanks!

**Comment by FranECross** [comment]
Confirmed input fields. Thanks!

**Comment by randimays** [comment]
Validated successfully in prod! Closing.
