### ISSUE TITLE
Create SECURITY.md

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#1756]
## Description
It would be prudent for our system to have a security file so that people can report security risks without making them public.  

It should reveal an email address that can be exposed.

Github proposes this as a template https://github.com/department-of-veterans-affairs/va.gov-cms/security/policy

# Security Policy

## Supported Versions

{Not necessary for our project, which is not consumed by other projects}

## Reporting a Vulnerability

Use this section to tell people how to report a vulnerability.

Tell them where to go, how often they can expect to get an update on a
reported vulnerability, what to expect if the vulnerability is accepted or
declined, etc.

## Acceptance Criteria 
- [ ] The designated contact method has been selected, is publicly available and is known to be monitored by multiple team members
- [ ] Policy doc includes a link to the [VA vulnerability disclosure policy](https://www.va.gov/vulnerability-disclosure-policy/)
- [ ] Policy doc created, reviewed and published

**Comment by swirtSJW** [comment]
Here is where vetswebsite is crafting one https://github.com/department-of-veterans-affairs/vets-website/pull/12660

**Comment by acrollet** [comment]
@joshworkscivicactions @jefflbrauer @cmaeng Do any of you see any issues with using the Help Desk form as a point of contact for this?
