### ISSUE TITLE
CTA Widget while authenticated: CTA appears as a plain link

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#17560]
## User Story or Problem Statement
On pages that use the CTA widget, while authenticated, the main CTAs do not appear as button or action link. 
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/85581471/36165367-7b7c-467b-9efc-9cbc0a63df17)

Previously, they looked like buttons. We think what happened was that back in January 2024 there was a [large PR](https://github.com/department-of-veterans-affairs/vets-website/pull/27307) merged with the intent on deprecating button classes in favor of va-button components. [This](https://github.com/department-of-veterans-affairs/vets-website/pull/27307/files#diff-064b584551b9f79877de15d42d64e617ebc3cfbd2e7414957768c9b04f2843ff) change in the cta-widget component removed all CTA link classes. (lines 507-515).

![Screenshot 2024-03-16 at 8 53 10 AM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/85581471/1837a91b-d6ed-442a-a885-b10e76ce6ac9)

## Expected behavior
Links should appear as Action Links, using the DS component.

The link is being rendered in [content-build](https://github.com/department-of-veterans-affairs/content-build/blob/main/src/site/paragraphs/react_widget.drupal.liquid#L33) and [vets-website](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/static-pages/cta-widget/index.js), so both locations need to be updated.

The CTA widget is invoked in a lot of places: https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/static-pages/cta-widget/ctaWidgets.js#L16

### To repro 
1. Go to https://www.va.gov/disability/view-disability-rating/
2. Login 
3. See that the action link / button looks like a plain link

## Acceptance Criteria
- [ ] CTA widgets while authenticated present the CTA as an Action link
- [ ] Spot check of several related pages is verified pre-merge and post-deploy

**Comment by randimays** [comment]
@jilladams @thejordanwood 

Based on the CSS classes that were removed from this link, it used to have a green background and white text. DST does not want us using this styling anymore. What **should** this link look like, now?

**Comment by thejordanwood** [comment]
@randimays I believe it should be a [primary action link](https://design.va.gov/components/link/action), like the one you have on the left. 

@laflannery Does that sound good to you?

**Comment by randimays** [comment]
Mikki verified this for us in production: https://dsva.slack.com/archives/C52CL1PKQ/p1712780025662939?thread_ts=1710856602.663289&cid=C52CL1PKQ. Closing as complete!
