### ISSUE TITLE
[Redirect] va.gov/remember needs to redirect to vlm.cem.va.gov

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-cms#17575]
### Status
**[2024-04-17]** Engineers will code the redirect, and then we'll get Joshua Tuscher on the phone, have him delete the folder, and test that it works
**[2024-04-16]** Dave C would like to chat about this during sprint planning this week.
**[2024-03-21]** This redirect was apparently already taken care of (by deleting a folder, it turns out). Keeping the ticket open per Dave C in case we need to take action in the future.

### Description
Redirect request from Dave Conlon via [Slack thread ](https://dsva.slack.com/archives/C52CL1PKQ/p1710958868700929)

This has already been discussed with CAIA (cc @mnorthuis @DanielleThierryUSDSVA 

### Type of request
- [ ] We are retiring or taking down a page and need to redirect the URL (complete redirect section)
- [X] We are changing the URL of an existing page (complete redirect section)
- [ ] We need a custom vanity URL (complete vanity URL section)

### Implementation date
When does this request need to be live?
Choose one:
- [ ] On a specific date, connected to a program or publishing requirement. **DATE:**
- [ ] Any day prior to a deadline/latest possible date. **DEADLINE:** 
- [ ] Any day after an earliest possible date. **EARLIEST DATE:**
- [X] During a specific date range: **_ASAP but not necessarily an OOB_**
- [ ] No hard timing requirements, publish when possible.

### Redirects 
Current URL  |  Redirect Destination or New URL
https://va.gov/remember AND www.va.gov/remember  |  www.vlm.cem.va.gov

### Process, Roles and Responsibilities
- [ ] Requesting team: Above information is provided
- [X] Requesting team: All appropriate VA stakeholders are notified as appropriate
- [x] IA: Request is vetted and documented and implementation plan is clear 
- [x] IA: Request is assigned to appropriate team for implementation 
- [ ] Implementation team: Work is complete
- [ ] Implementation team: Validated in production
- [ ] Requesting team: Validates everything is correct in production and closes ticket

### AC to validate the redirect is in place 
Note: Dave will introduce Josh T to Fran via email to get the ball rollling.
- [x] implement the revproxy process
- [ ] set up a meeting with Josh to have him delete the folder while on the call
- [ ] verify that the redirect works as expected

**Comment by jilladams** [comment]
@jennymayoco @mnorthuis can you confirm this is already signed off from IA? I know Dave said it, but having the record on ticket is better. :D

**Comment by jilladams** [comment]
And @kristinoletmuskat , sorry I forgot you

**Comment by jilladams** [comment]
Anndddd... nevermind? IN Slack, looks like this is working upstream now and ticket may be a no-op. Not closing just yet til that's final.

**Comment by FranECross** [comment]
Dave says a meeting has been scheduled to chat about this on Monday 4/8.

**Comment by randimays** [comment]
Just merged the redirect. It should go live Monday morning around 9am EST I believe. I'll circle back here to confirm.

**Comment by randimays** [comment]
@davidconlon @FranECross This redirect is in place in production 👍🏻

**Comment by FranECross** [comment]
@randimays Thank you! I'll email Joshua and schedule a short call this week with him/you/me so that he can delete the folder and we can confirm the redirect still works as expected. cc @davidconlon

**Comment by randimays** [comment]
The update to the redirect syntax was just merged in. Since we missed the deploy this morning, it'll deploy tomorrow at 10am ET.

**Comment by jilladams** [comment]
Stakeholders deleted the folder on their end today and redirect still verifies. Closing!
