### ISSUE TITLE
VA Forms Flags code to send flagged content to Slack #va-forms channel after nightly migration is not working

### ISSUE THREAD

**Issue by dsasser** [department-of-veterans-affairs/va.gov-cms#17570]
## Description
The [Forms SPIKE](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17450) revealed that [there are notifications that are not working](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17450#issuecomment-2009994071) for Forms changes such as a title change.

### User story

**AS A** Forms Administrator
**I WANT** to see Slack notifications for any Form flags
**SO THAT** I can respond to problems as they occur

### Engineering notes / background
Until June 2021, the nightly migration sent messages to slack about title changes. After https://dsva.slack.com/archives/CUB5X5MGF/p1624256239383100, this hasn't worked. 

## Acceptance criteria
- [ ]

**Comment by jilladams** [comment]
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11456 tracks the epic of work that would establish notifications for flags, but we never prioritized / implemented it. Closing as not planned. (if there's code that indicates to the contrary, holler? )

**Comment by jilladams** [comment]
Incorrect, Jill.
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17450#issuecomment-2010213612

![314583819-4f287632-fb3f-4366-90d2-3966096f2506](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/85581471/a8a01cd6-efb5-4d94-9aa1-123cbbd8c4c0)

> I see the code pic now, #va-forms channel. Looking back through that channel, the last notification sent to slack was here: https://dsva.slack.com/archives/CUB5X5MGF/p1624256239383100, June 2021. Notifications haven't worked since that point. I'm gonna reopen the ticket I just closed, but I don't know that it's a modern priority, since it's been broken forever?

**Comment by jilladams** [comment]
My personal opinion is: until we've thought harder about the ownership of who does what in light of a title change, these Slack notifications aren't helpful. Is our team going to scrub / mitigate them daily? Could we avoid the Slack noise and schedule a weekly review of the Flagged queue in Drupal instead? I think Dave's expectation is that our team owns these queues and keeps them clean, but how we go about that is up to us.

**Comment by FranECross** [comment]
@dsasser @jilladams I think we can close this ticket in favor of the audit view ticket, yes? https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17611
