### ISSUE TITLE
[EPIC] [Link Behavior]  VA.gov links with a non-VA.gov destination should open in the same screen/tab/window

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-cms#17594]
## Description
Update the FE template to VA.gov links that go to non-VA.gov pages should open in the same tab.

BTW Laura Flannery was told that this behavior is not being determined by Drupal, but is actually happening on the front end.

- Slack [conversation](https://dsva.slack.com/archives/CT4GZBM8F/p1710255666417699?thread_ts=1710246461.510779&cid=CT4GZBM8F)

- Here is a [conversation ](https://dsva.slack.com/archives/C0FQSS30V/p1710338168325059) Laura was having about VBA spotlights and I did confirm that what I was seeing here also happened in a WYSIWYG in a benefits detail page. 

### User story

**From a Veteran's perspective**
**AS A** Veteran, their caregiver, family member or survivor who clicks a link in VA.gov that opens a non-VA.gov page
**I WANT** the destination to open in my existing screen
**SO THAT** I'm not confused when I click the back button and nothing happens/I'm not taken back to VA.gov

**From the Design System Team's perspective**
**AS A** Design System Team decision-maker 
**I WANT** links in VA.gov that go from VA.gov to non-VA.gov destinations to open in the user's existing screen
**SO THAT** the user isn't confused when I click the back button and nothing happens/I'm not taken back to VA.gov

## Acceptance criteria

**AC1: User clicks a VA.gov link with a non-VA.gov destination (new behavior)**
**GIVEN**: A Veteran, their caregiver, family member or survivor is in VA.gov
**WHEN**: they click a VA.gov link with a non-VA.gov destination
**THEN**: the destination opens in the existing screen
**AND**: if the user clicks the browser back arrow
**THEN**: they are returned to the VA.gov screen they were viewing when they clicked the link

**AC2: User clicks a VA.gov link with a VA.gov destination**
**GIVEN**: A Veteran, their caregiver, family member or survivor is in VA.gov
**WHEN**: they click a VA.gov link with a VA.gov destination
**THEN**: the destination opens in the existing screen
**AND**: if the user clicks the browser back arrow
**THEN**: they are returned to the VA.gov screen they were viewing when they clicked the link

- [ ] Also: communicate to Jill whether Facilities will need to do the same things in their templates, or if this is a global fix.

**Comment by jilladams** [comment]
Couple things after talking to @laflannery on this in our 1:1 today: 

1. The old guidance changed about a year ago, and is now changing back. So if we complied with guidance from 2 versions ago and never updated to the newer version, this'll be a no-op in some places. 

2. I suspect this will end up as an epic -- external links could happen in a few places: 
* vets-website, hard coded in React apps/widgets
* content-build liquid templates, hard coded
* CMS editor input. (In this case: it might end up being that the related content-build template can specify how to handle external links, or maybe there's a single partial that handles all of them? guessing no, but eng can tell us.)

The other part of the matrix is: every product. 🙃  So this could end up looking a lot like the web components effort, that anywhere we've got an external happening in any product, we need to handle it. 

3. Prioritization! Per Laura, the Design System's official documentation hasn't caught up with new guidance yet, and there's no deadline. So we can work with Dave to figure out how much to care when.

**Comment by FranECross** [comment]
@jilladams Thanks so much for all the great info and background! I went ahead and converted this to an epic, and we can pay attention to it in the future when it comes up again. cc @laflannery

**Comment by jilladams** [comment]
I've been chasing my tail to remember what is going on here this week. For my own sake: 

## Old History: August 2023
PW flagged that guidance for links differed in 2 places: 
1. The Content style guide: https://design.va.gov/content-style-guide/links#linking-to-external-sites
2. DS Link behavior documentation: https://design.va.gov/components/link/#behavior

The language at the time didn't account for the fact in FE code, some subdomains are forced to open in a new tab. 

Slack thread from Aug 2023: https://dsva.slack.com/archives/C01DBGX4P45/p1692802785182169. This discussion led to an alignment: 
ticket: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2031
PR: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/pull/2102/files

## New history: April 2024
Guidance changed again: now we don't open in a new tab _unless_ user will lose a session / form progress.
https://github.com/department-of-veterans-affairs/vets-design-system-documentation/commit/8d53b17cd06432f1a6208c2d0ced34e7bddbb62a

## What we need to fix
There are 2 concerns here:

### 1. Subdomains that open in a new tab
There is code in content-build that says: for a specific set of subdomains, force any links to those subdomains to open in a new tab: https://github.com/department-of-veterans-affairs/content-build/blob/main/src/site/stages/build/plugins/modify-dom/update-external-links.js

CAIA wants us to stop doing that, as soon as we are able. That's captured in the ticket @mnorthuis created (https://github.com/department-of-veterans-affairs/va.gov-team/issues/81506), now added to this epic. 

### 2. Other links
Besides those forced subdomains, anywhere else we are opening links in new tabs _also_ need to stop doing that. This could be all over the place in our products, speaking to my earlier comment: 
> vets-website, hard coded in React apps/widgets
content-build liquid templates, hard coded
CMS editor input. (In this case: it might end up being that the related content-build template can specify how to handle external links, or maybe there's a single partial that handles all of them? guessing no, but eng can tell us.)


So I think we're officially in both-and territory and need to make the subdomain change (more urgently) AND assess where else links need to be updated (less urgently). 

@FranECross happy to discuss if I have further confused things!

**Comment by jilladams** [comment]
Also: the 2nd portion here, for any hard coded new tab links, will be true for Facilities as well. Adding that team label for now, as a reminder. If we decide to prioritize the audit work for other new tab links, we can break that up by team, etc down the road.

**Comment by FranECross** [comment]
@jilladams This info is super helpful. I'll get this ticket queued up for the next sprint, and will create (I think three?) other tickets to take care of the bullet items in your #2 above. Thanks so much for spelunking and coming up with crystals and gold. 🎉
