### ISSUE TITLE
Only published VBA services should display on front end

### ISSUE THREAD

**Issue by davidmpickett** [department-of-veterans-affairs/va.gov-cms#17599]
## User Story or Problem Statement

The VBA FE query/template should exclude any VBA facility services with Moderation State = `archived` or `draft`

VAMCs seem to be working correctly on the Tugboat.

<details><summary>Tugboat Drupal - VBA: archived services </summary>

![screencapture-cms-xptmfsnjoodldn85nzgkrgljqtfbz24b-ci-cms-va-gov-admin-content-2024-03-21-21_44_44](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/1188a719-af57-465a-bdf4-6b50f11277d9)

</details>

<details><summary>Tugboat Front End - VBA: archived services showing in the FE </summary>

![Screenshot 2024-03-21 at 9 44 14 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/831b9cfd-8e3a-47d6-9d11-4976e6f4bb90)

</details>

<details><summary>Tugboat Drupal - VAMC: archived services</summary>

![Screenshot 2024-03-21 at 9 40 46 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/cabe367d-e865-46ce-bb45-655b473006d3)

</details>

<details><summary>Tugboat Front End - VAMC: no archived showing</summary>

![Screenshot 2024-03-21 at 9 40 50 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/5af9beab-576f-4a98-9236-52c37b5e1460)

</details>

### Published state
There are 2 types of "Published": 
* Node status:  published, unpublished
* Workflow state: Published -- **this is the one we care about**. 

- [Cleveland Regional Benefit office on Tugboat](https://web-xptmfsnjoodldn85nzgkrgljqtfbz24b.ci.cms.va.gov/cleveland-va-regional-benefit-office/locations/cleveland-va-regional-benefit-office/#veteran-benefits)
- [Archived VBA facility services in tugboat](https://cms-xptmfsnjoodldn85nzgkrgljqtfbz24b.ci.cms.va.gov/admin/content?title=&type=vba_facility_service&moderation_state=archived&owner=All)

## Steps for reproduction (archived flow)
- Publish a VBA facility service on a published VBA facility
- Run content release
- See it show up on the front end of tugboat
- Archive VBA facility service
- Run content release
- See the facility service still showing

## Acceptance Criteria
- [ ] Only published VBA facility services and published VBA Service Region content show in the FE
- [ ] Other states should not show: 
    - [ ] Draft
    - [ ] Archived
    - [ ] Ready
    - [ ] Approved

**Comment by eselkin** [comment]
I think this is something we talked about once. Did we make a ticket for it in the past?

**Comment by davidmpickett** [comment]
> I think this is something we talked about once. Did we make a ticket for it in the past?

You might be thinking of a [similar situation with Vet Center services](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16362)?

**Comment by jilladams** [comment]
We need to confirm the GraphQL for workflow state = published

**Comment by laflannery** [comment]
Looking at the tugboat today I am seeing an issue where a non-existant service is showing - Home loans is on the FE but doesn't exist in Drupal. Is this a situation we need to cover within this ticket or a different ticket

![Screenshot 2024-04-29 at 9 38 30 AM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/106678594/fc6a19aa-e3dc-48dd-87fb-3f9cc1a627e6)

**Comment by davidmpickett** [comment]
@laflannery This is from the **Service Region** content type. You are correct that it shouldn't be showing because it is also in Draft and is called out in the ACs

![Screenshot 2024-04-29 at 10 01 06 AM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/20cc82ed-5635-4f7f-b7c9-c74ece4b6ba8)

**Comment by maxx1128** [comment]
@laflannery are you looking at the most recent test environment for this branch? I've already added a filter on the service region query that should take out all the unpublished ones.

```
          reverseFieldVbaRegionFacilityListNode (
            filter: {conditions: [
              {field: "status", value: ["1"]}
            ]}
          ){
            count
            entities {
              entityId
              entityLabel
              ... on NodeServiceRegion {
                // All the properties here
              }
```

I'm rebasing [the pull request to refresh the test environment](https://github.com/department-of-veterans-affairs/content-build/pull/2025), and then it should be good to check again.

**Comment by jilladams** [comment]
PR merged to main. @maxx1128 will you also be PRing to the SL integration branch?

**Comment by davidmpickett** [comment]
> PR merged to main. @maxx1128 will you also be PRing to the SL integration branch?

And/or rebasing the [Content Build integration branch](https://github.com/department-of-veterans-affairs/content-build/pull/1912) to pull in Main and then rerun Content Release on SL Tugboat

**Comment by jilladams** [comment]
From sprint planning; @maxx1128 to handle pulling changes into Service Locations integration branch, and tap Eli for support as needed.

**Comment by davidmpickett** [comment]
I have mostly verified this. Added a bunch of services in various workflow states and only published ones showed up on FE. However, I have one more thing to check and need to run content release again to do so

![Screenshot 2024-05-03 at 10 11 14 AM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/9c816f45-649f-4550-81ab-4a3ee844d0c1)

![Screenshot 2024-05-03 at 10 12 13 AM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/3d768b3e-4fab-4ee9-8d0f-757bd1c871f6)

**Comment by davidmpickett** [comment]
Additional conditions verified with second Content Release
- A service that was first Published and then Archived correctly disappeared from FE
- A Draft revision on a Published service correctly did not display on FE
