### ISSUE TITLE
component library update

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#17591]
## Requirements

The VA Design System needs updating, so that it is compatible with Next Build. 

```[tasklist]
### Acceptance criteria
- [ ] component-library is updated to the most recent version
- [ ] tests pass without issue
```

## Background & implementation details

Typescript issues that need to be updated upstream; see Slack thread from the DST channel: https://dsva.slack.com/archives/C01DBGX4P45/p1710888039224269

**Comment by tjheffner** [comment]
v38.0.3 fixes one of the errors. The second error related to the `Overlay` component will require an upgrade to the stencil package that the component-library repo is using. This may or may not be prioritized soon, based on comments here:

https://dsva.slack.com/archives/C01DBGX4P45/p1711732915383109?thread_ts=1710888039.224269&cid=C01DBGX4P45

**Comment by tjheffner** [comment]
Updating from our current version of `"@department-of-veterans-affairs/component-library": "^33.0.0",` is blocked pending the DST upgrading their stencil version that generates the react bindings. The file containing the error is gitignored and generated via stencil. 

See this slack thread for more details:
https://dsva.slack.com/archives/C01DBGX4P45/p1712177213757299?thread_ts=1710888039.224269&cid=C01DBGX4P45

**Comment by mreed101** [comment]
As of Mar 29th a ticket was created to do the stencil upgrade in the component library.

https://app.zenhub.com/workspaces/platform-design-system-5f8de67192551b0012ebb802/issues/gh/department-of-veterans-affairs/vets-design-system-documentation/2233

If the ticket has been completed, we will need to bump up our component-library package version to ^38.0.0, ideally 38.0.4

**Comment by ttran-Therisa** [comment]
The Stencil upgrade seems to get pushed frequently to later sprints. It has now moved to be a part of sprint Aug 1-14 and removed from the sprint of Jun 20th - Jul 3rd
> Updating from our current version of `"@department-of-veterans-affairs/component-library": "^33.0.0",` is blocked pending the DST upgrading their stencil version that generates the react bindings. The file containing the error is gitignored and generated via stencil.
> 
> See this slack thread for more details: https://dsva.slack.com/archives/C01DBGX4P45/p1712177213757299?thread_ts=1710888039.224269&cid=C01DBGX4P45

**Comment by timcosgrove** [comment]
v39 and onward solved this problem back in April 23. Any version from v39 does fine with the type checks.

The key change appears to be this: https://github.com/department-of-veterans-affairs/component-library/compare/v38.0.4...v39.0.1#diff-7298512f791c54d2827facfc8d26ae8a5db2ac960e464e30953ccaab05dd412eR44

They were able to update the stencil/react-output-target package without going to Stencil 2.

**Comment by mreed101** [comment]
Library has been updated
