### ISSUE TITLE
Update VBA template to display "Manage your benefits online"

### ISSUE THREAD

**Issue by davidmpickett** [department-of-veterans-affairs/va.gov-cms#17598]
## User Story or Problem Statement

- If a VBA facility service has been added and that service has `online self-service` set in the VA Services Taxonomy, then the Manage your Benefits header, paragraph, and link should show

<details><summary>Tugboat FE </summary>

![Screenshot 2024-03-20 at 5 44 37 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/e64b3df0-d159-4f6d-8084-2df94b51e009)

</details>

<details><summary>Tugboat Service Taxonomy </summary>

![Screenshot 2024-03-20 at 5 44 51 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/0df2cf6f-82be-4021-8dc0-6d5d5ead1be4)

</details>

<details><summary>Design in Figma</summary>

![Service accordions](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/de151d16-3d37-4598-ac54-478adb68e5a4)

</details>

## Data origin
This data comes from the VA Services taxonomy term, VBA section, Online-self-service:  URL / Link text fields, e.g. https://staging.cms.va.gov/taxonomy/term/1131/edit?destination=/admin/structure/taxonomy/manage/health_care_service_taxonomy/overview

## Description or Additional Context 
May require modifying GraphQL to get ahold of the VA Services taxonomy data. 

- [Cleveland Regional Benefit office on Tugboat](https://web-xptmfsnjoodldn85nzgkrgljqtfbz24b.ci.cms.va.gov/cleveland-va-regional-benefit-office/locations/cleveland-va-regional-benefit-office/#veteran-benefits)
- [VBA design in Figma](https://www.figma.com/file/88Gw7fmUkDbheSAHjIpHn7/VBA-Regional-Office?type=design&node-id=0-1107&mode=design)
- [Home loans taxon in Tugboat](https://cms-xptmfsnjoodldn85nzgkrgljqtfbz24b.ci.cms.va.gov/health-care/home-loans)

## Acceptance Criteria
- [ ] When a service has `online self-service` set in the VA Services Taxonomy - VBA section, show
  - [x] Manage your benefits online - H4
  - [x] You always have the option to apply for and manage your VA benefits online. - Paragraph
  - [ ] Link specified in Service taxonomy - VA link
- [ ] When a service does not have `online self-service` set in the VA Services Taxonomy, do not show this content
- [ ] Related tests are updated
- [ ] Requires design review
- [ ] Requires accessibility review

**Comment by mmiddaugh** [comment]
> You always have the option to apply for and manage your VA benefits online.

@davidmpickett has this wording been confirmed with CAIA? 
If we don't list an online option for all services, is it true that it's `always` available? 
Is the online option true for all Veterans and other beneficiaries?

**Comment by davidmpickett** [comment]
> > You always have the option to apply for and manage your VA benefits online.
> 
> @davidmpickett has this wording been confirmed with CAIA? If we don't list an online option for all services, is it true that it's `always` available? Is the online option true for `all` Veterans and other beneficiaries?

This is the wording provided by CAIA. I just tagged you in the spreadsheet comment where it was provided

**Comment by davidmpickett** [comment]
@maxx1128 can you provide an update on the status of this ticket?

**Comment by maxx1128** [comment]
@davidmpickett My local build instances, computer and tugboat, have been erroring out as I try to work on this, so it will need to be pushed into the next sprint 😕

**Comment by davidmpickett** [comment]
Rereleasing content on SL Tugboat to verify

**Comment by davidmpickett** [comment]
@maxx1128 I'm not seeing the "You always have the option to apply for and manage your VA benefits online." paragraph that's supposed to be between the H4 and VA link

![Screenshot 2024-05-10 at 11 43 32 AM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/adecfaca-fdff-4e45-85f6-3fcc9461b8f8)

https://web-xptmfsnjoodldn85nzgkrgljqtfbz24b.ci.cms.va.gov/cleveland-va-regional-benefit-office/#family-member-and-caregiver-be

**Comment by maxx1128** [comment]
@davidmpickett I apologize for missing that text, I got too distracted by the logic part of the template 😅 I created a small pull request to add it in: https://github.com/department-of-veterans-affairs/content-build/pull/2078

**Comment by davidmpickett** [comment]
New version is live on Tugboat. Has @laflannery or @thejordanwood reviewed this yet?

**Comment by davidmpickett** [comment]
Approved by Laura and Jordan in Slack https://dsva.slack.com/archives/C0FQSS30V/p1715365690242829

**Comment by davidmpickett** [comment]
Verification screenshot
![Screenshot 2024-05-10 at 3 49 22 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/3e61da0d-0d3c-4e10-9850-c521135d4430)
