### ISSUE TITLE
Initial look at possible solutions for File Storage on S3

### ISSUE THREAD

**Issue by indytechcook** [department-of-veterans-affairs/va.gov-cms#1759]
Look at the current landscape of Drupal module and implementations.  Also update the linked Epic with new issues to implement the new solution.

**Comment by indytechcook** [comment]
## [WIP] Possible approached to use s3fs 

### What to take into consideration
* CEX file
* Image Style generation occurs when the file is created instead of on demand.
* JS/CSS generate files
* should file links be `s3` url or cms URL? 

### Use a separate file schema for s3.
* Only certain files are served from s3.
* File schemas will need to be migrated from `public://` to `s3fs://`
* Configuration for all file uploads will need to be configured to use `s3fs://` instead of `public://` as the default
* Possibility of files not making it to s3 if someone uploads using `public` instead of `s3.
* JS/CSS optimized files are still served from the server
* Image Styles: When an image style is requested, the s3fs module takes over the route.  If the file is found then the URL is replaced with the S3 URL, otherwise, the file is generated and sent to s3 then served on the next request.
* CEX files?

### Set all files to be served by s3
* `public://` and `private://` schema files are served from s3
* Dynamically generation needs .htaccess config
* CEX files?
* Redirect image styles/dynamic files back to drupal for 404: https://stackoverflow.com/questions/28115048/amazon-s3-redirect-404-to-different-host

**Comment by indytechcook** [comment]
@ElijahLynn and I also considered other solutions besides s3fs:

* Having a master "file" server where all file request were redirected to
* Using https://www.gluster.org/ 
* Using EBS Multi-Attach

The main drawback on these was the performance of the CEX real time taring of files.  The solutions all were not performant enough.

The ideal solution would use some sort of 2 layer file system where the files were stored locally then synced up/down between the servers.

**Comment by ElijahLynn** [comment]
> The ideal solution would use some sort of 2 layer file system where the files were stored locally then synced up/down between the servers.

And I honestly think that FS-Cache should have been light years faster than it was. It might be worth revisiting that because that's exactly the 2 layer cache that is built for network filesystems. I can find a way to send the benchmarks to the maintainers and get some feedback on if that is normal.

**Comment by ElijahLynn** [comment]
I wonder if tar is "opening for direct IO" which I don't think would but we can strace to find out. Or maybe just use strace to find out why it's slower than expected. It seemed to be going over the network in my tests even though the cache was full of objects and large (GBs). We can also monitor network activity to see what happens during a tar on an FS-Cache system.

>  opening a file from a shared file system for either direct I/O or writing will flush the cached copy of the file. FS-Cache will not cache the file again until it is no longer opened for direct I/O or writing


https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/6/html/storage_administration_guide/fscachelimitnfs

**Comment by indytechcook** [comment]
I looked at GlusterFS and tar performance and found this https://www.mail-archive.com/gluster-users@gluster.org/msg08370.html.  It is from 2012.  I'm looking for more updated information.

FS-Cache would definitely be the ideal solution.

**Comment by indytechcook** [comment]
Reading https://www.mail-archive.com/gluster-users@gluster.org/msg08370.html it seems it's more the metadata calls that cause many of the performance issues.

**Comment by indytechcook** [comment]
Created #1761 as a follow up to use FS-Cache.  I'll move the notes over there.
