### ISSUE TITLE
storybook 8

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#17590]
## Requirements

Storybook should be updated to v8 so that it is up to date.

```[tasklist]
### Acceptance criteria
- [ ] How can we verify the requirements have been met factually/quantifiably?
```

## Background & implementation details

Breaking changes around some of the add-ons will require work on Next-Build's end. .mdx is no longer supported in particular.

**Comment by mreed101** [comment]
Completed
