### ISSUE TITLE
Add "Select a topic to learn more." to VBA service accordion groups

### ISSUE THREAD

**Issue by davidmpickett** [department-of-veterans-affairs/va.gov-cms#17601]
## User Story or Problem Statement
There are four headings for Service accordions on VBA facilities
- Veteran benefits
- Family member and caregiver benefits
- Service member benefits
- Other services

These headings only show up if there is a published VBA facility service that corresponds to that category. However, per the Figma Design, the headings should be followed by the paragraph "Select a topic to learn more."

<details><summary>Tugboat FE </summary>

![Screenshot 2024-03-21 at 11 05 57 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/1604b461-392e-4a56-a2ba-7496240e1ef8)

</details>

<details><summary>Design in Figma</summary>

![Screenshot 2024-03-21 at 11 05 52 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/17b4c554-5972-4f83-93fa-22090915c10f)

</details>

## Description or Additional Context 
- [Cleveland Regional Benefit office on Tugboat](https://web-xptmfsnjoodldn85nzgkrgljqtfbz24b.ci.cms.va.gov/cleveland-va-regional-benefit-office/locations/cleveland-va-regional-benefit-office/#veteran-benefits)
- [VBA design in Figma](https://www.figma.com/file/88Gw7fmUkDbheSAHjIpHn7/VBA-Regional-Office?type=design&node-id=0-1107&mode=design)

## Acceptance Criteria
- [x] Service accordion group headers & text match Figma design
- [x] Service accordion group headers do not show if there is no content (Conditionals are handled appropriately)
- [ ] Requires design review

**Comment by laflannery** [comment]
Verified on prod:
![image](https://github.com/user-attachments/assets/91509757-9922-4685-8c5a-3353b849f7de)
