### ISSUE TITLE
Make PDF Audit Available to Editors

### ISSUE THREAD

**Issue by gracekretschmer-metrostar** [department-of-veterans-affairs/va.gov-cms#17604]
## User Story or Problem Statement
As a VA editor, I want to see a list of PDFs relevant to my work and how those PDFs relate (e.g. where linked to VA.gov) to VA.gov. 

## Description or Additional Context 
In the first iteration of the VA CMS allowed for PDFs to be uploaded. Created lots of problems, including 

Right now, there is a bug in VA CMS where editors cannot delete PDFs and cannot see a list of the existing PDFs in Drupal and how they are linked in VA.gov. To help implement better PDFs habits, @edmund-dunn created a PDF audit feature, so that VA editors could get an overview of PDFs related to their work. 

The ultimate goal of this work is to implement a deletion feature within Drupal and have a process to move PDFs out of Drupal and into another records management system that is in alignment with 

## Steps for Implementation
- [x] UX review of the existing PDF audit feature to ensure that features will be both useful and understandable for VA editors. 
- [x] Accessibility review of the existing PDF audit feature to flag and categorize any accessibility issues with the feature. 
- [ ] Documentation and a change management process so that VA editors understand how to use the PDF audit feature. 
- [ ] Make the PDF audit available to VA editors. 

## Reference Materials
- https://github.com/department-of-veterans-affairs/va.gov-cms/pull/8013#pullrequestreview-882140044
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/6980
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13815

## Acceptance Criteria
- [ ] The PDF audit feature allows VA editors to understand the PDFs that could be a webpage instead of a PDF. 
- [ ] The PDF audit feature is available to VA editors. 
- [ ] VA editors understand how to use the PDF audit feature. 

## Team
Please check the team(s) that will do this work.
- [x] CMS Team
- [ ] Public Websites
- [ ] Facilities
- [ ] Accelerated Publishing

**Comment by gracekretschmer-metrostar** [comment]
Meeting recording for 3/22 Pre-Refinement Convo: Drupal + PDFs: https://drive.google.com/file/d/1jQuTKN4PYsfqpyMzZi6zR4n53a6t1Cxw/view?usp=sharing

**Comment by gracekretschmer-metrostar** [comment]
Idea: use this task to prototype an internal collab cycle.

**Comment by gracekretschmer-metrostar** [comment]
Need to do: make sure help desk team is included in the release of this feature.

**Comment by anantais** [comment]
I'm not sure if this will get completed this sprint. Marisa is out this week and Steve is out part of next week. 

So far I have tested out the pdf editor locally and I am looking into making it available to more editors (it is currently restricted to a few people).

**Comment by gracekretschmer-metrostar** [comment]
Thanks, @anantais, for that update and that is understandable that we can't complete this task this sprint. In the meantime, can you pivot your focus on completing this task? https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17648

**Comment by gracekretschmer-metrostar** [comment]
Change management plan will consist of a knowledge base article (created by @MDomngz, in collaboration with @edmund-dunn) and office hours will be led by @gracekretschmer-metrostar and @srancour.

**Comment by gracekretschmer-metrostar** [comment]
Erika will send drafts of roll out plans and runbooks that we can leverage.

**Comment by gracekretschmer-metrostar** [comment]
https://[prod.cms.va.gov](https://prod.cms.va.gov/admin/content/media/pdfs)/admin/content/media/pdfs
