### ISSUE TITLE
Update Spotlights on Vet Center main page to use Card component

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#17618]
## Description
To be in compliance with the Design System and to help make sure our products receive design and accessibility updates, the Vet Center product needs to be updated to use the most recent versions of all available components.

Example pages:

- [Boston Vet Center](https://www.va.gov/boston-vet-center/)
- [St. Paul Vet Center](https://www.va.gov/st-paul-vet-center/)

The Spotlight display has been standardized by Design and we are going to use [the card component](https://design.va.gov/components/card#default---white-with-border). The inside of this component is freeform so we have [an annotated Figma file](https://www.figma.com/file/ikCp2eOubIgbN1TwyEYIrN/VAMC-Master?type=design&node-id=108-1696&mode=design&t=A1cZUr56N0WILqUv-0) to help implement this change:
![Screenshot 2024-03-25 at 8 47 51 AM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/106678594/4d553cc5-1629-41bc-a866-bc3d638f3231)

## Acceptance Criteria
- [ ] Card component has been added
- [ ] Proper components and markup has been used inside the cards
- [ ] Update and run existing test(s)
- [ ] If additional tests are needed, stub a ticket to note this for future work
- [ ] Requires design review
- [ ] Requires accessibility review
- [x] Change management

**Comment by laflannery** [comment]
I added an AC for change management - I spoke to @mmiddaugh and since there is a large-ish display change she felt that giving folks a heads up that this was happening would be good.

**Comment by eselkin** [comment]
See logic on VAMC update. 
3 if just changing to card.
3 if just changing to card and all links are action links.
5 if changing to card, differentiating link types to use action and va-link with lead in type.

**Comment by jilladams** [comment]
Just the card for now. Other link changes will come when we standardize spotlights.

**Comment by jilladams** [comment]
For Change management AC: 
* Slack thread: https://dsva.slack.com/archives/C0FQSS30V/p1715023108494009


### Draft language for Vet Center editors
(This prob isn't how we talk to editors, but getting the bullets together)

Please be aware that the visual presentation of Vet Center spotlights will change this week. 
When: <merge day?>
What: The visual style of Spotlights will be updated to use the [VA Design System's "card" component](https://design.va.gov/components/card). Changes include: 
* Spotlight card blue background will become white background with an outline
* Spotlight titles will use a serif font and larger font size

### BEFORE
e.g. https://www.va.gov/boston-vet-center/
![Screenshot 2024-05-06 at 3 05 06 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/85581471/b961251c-7ba5-4145-8e1b-95766943c6ab)

### AFTER
![328290903-52bb1a5e-3729-4b5a-85e5-0a03444a542a](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/85581471/a0d7bf32-d569-4dd4-a594-709a4cf17525)

**Comment by jilladams** [comment]
@mmiddaugh plans to communicate to Barb / Jessica , and then drop this info in the Vet Center office hours Teams chat.

Jll to make helpdesk aware.

**Comment by jilladams** [comment]
CM: 
* Vet Centers: https://dsva.slack.com/archives/C0FQSS30V/p1715098254352709
* Helpdesk: https://dsva.slack.com/archives/C02730UEZPS/p1715097058627559

**Comment by davidmpickett** [comment]
Verified on Prod 
![Screenshot 2024-05-08 at 5 19 49 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/3418d4f8-9c28-462f-af6c-2afa6b3e4b98)
