### ISSUE TITLE
Investigate FS-Cache tar performance 

### ISSUE THREAD

**Issue by indytechcook** [department-of-veterans-affairs/va.gov-cms#1761]
[FS-Cache](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/6/html/storage_administration_guide/ch-fscache) was looked into as a possible solution for CEX.  We ran into issues with the performance of the tar action so the idea was scrapped.  We want to spend more time looking into tweaking FS-Cache and filesystem configuration to improve performance.

Previous Issues:
* https://github.com/department-of-veterans-affairs/va.gov-cms/issues/1360

External Articles to review:
* https://www.cyberciti.biz/faq/centos-redhat-install-configure-cachefilesd-for-nfs/
* https://www.admin-magazine.com/HPC/Articles/Useful-NFS-Options-for-Tuning-and-Management
* https://people.redhat.com/dhowells/fscache/FS-Cache.pdf
* https://blog.frehi.be/2019/01/03/fs-cache-for-nfs-clients/
* https://www.mail-archive.com/gluster-users@gluster.org/msg08351.html

## Acceptance criteria

- [ ] research into the subject
- [ ] action items identified

**Comment by ElijahLynn** [comment]
Crosslinking relevant tickets:
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/1716
Note to self - add link to devops benchmarking I did previously on fs-cache (not saying more should not be done)
