### ISSUE TITLE
VC: Not all published facilities have a canonical URL

### ISSUE THREAD

**Issue by omahane** [department-of-veterans-affairs/va.gov-cms#17621]
## Describe the defect
All published facilities should have a canonical URL so that visitors looking for a facility in the Facility Locator are provided a link the Drupal-sourced page, rather than the Facility Locator details page.

## To Reproduce
1. Go to the Facility locator, [looking for Vet Centers in Seattle](https://www.va.gov/find-locations/?address=Seattle%2C%20WA%20&bounds%5B%5D%5B%5D=-123.189875&bounds%5B%5D%5B%5D=46.49958&bounds%5B%5D%5B%5D=-121.689875&bounds%5B%5D%5B%5D=47.99958&context=Seattle%2C%20Washington%2C%20United%20States&facilityType=vet_center&latitude=47.603832&longitude=-122.330062&page=1&radius=21&serviceType&bounds%5B%5D=-123.080062&bounds%5B%5D=46.853832&bounds%5B%5D=-121.580062&bounds%5B%5D=48.353832).
2. Note that the link to the Seattle Vet Center is https://www.va.gov/find-locations/facility/vc_0507V
3. Go to https://prod.cms.va.gov/seattle-vet-center
4. Confirm that the page is published
5. Confirm that the link is https://www.va.gov/seattle-vet-center/

## AC / Expected behavior
A published facility page of the following content types should links to their Drupal-sourced pages on the VA.gov website:

- [x] VAMC facility
- [x] Vet Center
- [x] Vet Center - Outstation
- [x] Vet Center - Mobile Vet Center

## Screenshots
<img width="1440" alt="Screenshot 2024-03-25 at 12 31 30 PM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/766573/fc4fb3d0-9d7b-4865-b86b-6fd73cff39d7">

## Context
There are around 70 of these at present.

Here's a diff of the Published facilities vs Lighthouse Facilities API:
[published-lighthouse-diffs.patch](https://github.com/department-of-veterans-affairs/va.gov-cms/files/14747683/published-lighthouse-diffs.patch)

**Comment by jilladams** [comment]
Curious: do we think this was maybe a last step of Vet Center launches that never got done, or was working previously and is a regression? (Probably no way to know unless we deep dive, but @mmiddaugh maybe you recall from the Vet Center rollout? )

**Comment by jilladams** [comment]
From refinement: we need to follow up on this with Lighthouse.

**Comment by davidmpickett** [comment]
> From refinement: we need to follow up on this with Lighthouse.

Do we need information from them before this ticket can start? Or would that be part of the work here?

**Comment by jilladams** [comment]
Yes, bad note from me. 

Better note: we think this is only a Lighthouse problem. Lighthouse is responsible for the URLs being correct in the API, and sent to the Facility Locator. So likely: we just need to get in touch with them to correct the upstream data source to provide the right URL for these Vet Centers. The only work in this ticket is talking to Lighthouse & verifying the update once they make it.

**Comment by omahane** [comment]
So there's more than meets the eye in that diff I posted. Here's the first, most important batch, the facilities that need their URLs up in the websites.csv:
```
vc_0206V,https://www.va.gov/parma-vet-center/
vc_0234V,https://www.va.gov/toledo-vet-center/
vc_0402V,https://www.va.gov/detroit-vet-center/
vc_0414V,https://www.va.gov/st-louis-vet-center/
vc_0507V,https://www.va.gov/seattle-vet-center/
vc_0736V,https://www.va.gov/springfield-mo-vet-center/
vc_0807MVC,https://www.va.gov/huntington-vet-center/
vc_0863MVC,https://www.va.gov/jackson-vet-center/
vc_0865MVC,https://www.va.gov/lawton-vet-center/
vc_0868MVC,https://www.va.gov/saint-george-vet-center/
vc_0877MVC,https://www.va.gov/shreveport-vet-center/
vc_0880MVC,https://www.va.gov/sacramento-vet-center/
vc_3071OS,https://www.va.gov/san-juan-vet-center/ 	
vc_3072OS,https://www.va.gov/san-juan-vet-center/ 		
vha_436GO,https://www.va.gov/montana-health-care/locations/butte-va-clinic
vha_442GE,https://www.va.gov/cheyenne-health-care/locations/northern-colorado-va-clinic
vha_508GQ,https://www.va.gov/atlanta-health-care/locations/cobb-county-va-clinic
vha_508GS,https://www.va.gov/atlanta-health-care/locations/pike-county-va-clinic
vha_521QB,https://www.va.gov/birmingham-health-care/locations/birmingham-east-va-clinic
vha_605GF,https://www.va.gov/loma-linda-health-care/locations/north-loma-linda-va-clinic
vha_612QE,https://www.va.gov/northern-california-health-care/locations/stockton-va-clinic
vha_636GZ,https://www.va.gov/central-iowa-health-care/locations/south-des-moines-va-clinic
vha_663GK,https://www.va.gov/puget-sound-health-care/locations/everett-va-clinic
vha_674GG,https://www.va.gov/central-texas-health-care/locations/copperas-cove-va-clinic
vha_674GH,https://www.va.gov/central-texas-health-care/locations/killeen-va-clinic
```
I will ask LH to add these.

**Comment by omahane** [comment]
@mmiddaugh 
In the process of working this, I found this facility:
```
vc_0415V,
https://prod.cms.va.gov/milwaukee-vet-center
https://www.va.gov/milwaukee-vet-center/ 
```
- it's closed but has CAPs 
- should it stay Published?

**Comment by omahane** [comment]
I did some additional work but haven't finished it. I honestly don't think it's high value and does not directly relate the ACs on this ticket:
```
# toBeRemoved
## Unchecked
+vc_0538-1OS
+vc_0704MVC
+vc_0817MVC
+vc_0822MVC
+vc_0832MVC
+vc_0863MV
+vha_676QA  /// archived
+vha_740GJ
+vha_757QC

## Checked
vc_0875MVC,https://www.va.gov/columbia-mo-vet-center/, /// inAPI, draft, needsReview
vc_0882MVC,https://www.va.gov/farmington-vet-center/, /// inAPI, draft, needsReview
vc_0883MVC,https://www.va.gov/san-marcos-vet-center/, /// inAPI, archived, needsReview
vc_1081OS,https://www.va.gov/manchester-vet-center/, /// inAPI, needsReview
vc_3121OS,https://www.va.gov/san-juan-vet-center/, /// notInCMS, toBeRemoved
vc_3122OS,https://www.va.gov/san-juan-vet-center/, /// notInCMS, toBeRemoved
vc_6051OS,https://www.va.gov/chatsworth-vet-center/, /// archived, toBeRemoved
vha_402HL,https://www.maine.va.gov/locations/Mobile_Medical_Unit.asp redirects to https://www.va.gov/maine-health-care/, /// archived, toBeRemoved
vha_436GA,https://www.va.gov/montana-health-care/locations/anaconda-va-clinic/ redirects to https://www.va.gov/montana-health-care/, /// archived, toBeRemoved 
vha_442HK,https://www.cheyenne.va.gov/locations/Wheatland_VA_Mobile_Clinic.asp redirects to https://www.va.gov/cheyenne-health-care/, /// needsReview
vha_442QB,https://www.cheyenne.va.gov/locations/Torrington_VA_Mobile_Clinic.asp redirects to https://www.va.gov/cheyenne-health-care/, /// needsReview
vha_442QD,https://www.cheyenne.va.gov/locations/Laramie.asp, redirects to https://www.va.gov/cheyenne-health-care/, /// needsReview
vha_508QD,https://www.va.gov/atlanta-health-care/locations/fulton-county-va-clinic/ redirects to https://www.va.gov/atlanta-health-care/, /// archived, toBeRemoved 
vha_528GX,https://www.va.gov/albany-health-care/locations/troy-va-clinic/ redirects to https://www.va.gov/albany-health-care/, /// archived, toBeRemoved 
vha_540HK,https://www.clarksburg.va.gov/locations/Rural_Mobile_Clinic.asp, redirects to https://www.va.gov/clarksburg-health-care/, /// needsReview
vha_554A4,https://www.denver.va.gov/locations/Pueblo_VA_Community_Living_Center.asp, redirects to https://www.va.gov/eastern-colorado-health-care/, /// needsReview
vha_554BU,https://www.denver.va.gov/locations/Valor_Point_VA_Domiciliary.asp, redirects /// needsReview
vha_573A5,https://www.va.gov/north-florida-health-care/locations/jacksonville-navy-va-medical-center/, /// archived, toBeRemoved 
vha_573QA,https://www.va.gov/north-florida-health-care/locations/gainesville-sixteenth-street-va-clinic/, /// archived, toBeRemoved 
vha_573QH,https://www.va.gov/north-florida-health-care/locations/ocala-west-va-clinic/, /// needsRedirect
vha_575QC,https://www.grandjunction.va.gov/locations/Grand_Junction_VA_Mobile_Clinic.asp, /// needsReview
vha_583QC,https://www.va.gov/indiana-health-care/locations/vigo-county-va-clinic/, /// archived, toBeRemoved 
vha_583QF, https://www.va.gov/indiana-health-care/locations/crane-va-clinic/, /// archived, toBeRemoved  
vha_589G3,https://www.va.gov/wichita-health-care/locations/liberal-va-clinic/, /// archived, toBeRemoved  
vha_589HK,https://www.kansascity.va.gov/locations/MobileMedUnit.asp redirects to https://www.va.gov/kansas-city-health-care/, /// needsReview
vha_589QC,https://www.va.gov/wichita-health-care/locations/south-parklane-va-clinic/, /// archived, toBeRemoved  
vha_612QD,https://www.va.gov/northern-california-health-care/locations/howe-road-va-clinic/, /// archived, toBeRemoved 
vha_631QB,https://www.va.gov/central-western-massachusetts-health-care/locations/lake-avenue-va-clinic/, /// archived, toBeRemoved 
vha_636GX,https://www.va.gov/central-iowa-health-care/locations/fort-dodge-north-va-clinic/, /// archived, toBeRemoved
vha_636QD,https://www.va.gov/iowa-city-health-care/locations/macomb-va-clinic/, /// archived, toBeRemoved
vha_640HA,https://www.va.gov/palo-alto-health-care/locations/stockton-va-clinic/, /// archived, toBeRemoved
vha_642BU, Philadelphia VA Domiciliary, https://www.va.gov/philadelphia-health-care/locations/burlington-county-va-clinic/, /// same URL as vha_642GA, needsReview
vha_652GH,Richmond 2 VA Mobile Clinic, in Sandbox API, not in csv, /// archived, needsReview
vha_655QB,https://www.va.gov/saginaw-health-care/locations/grand-traverse-va-clinic/ /// archived,toBeRemoved
vha_671GK01,https://www.va.gov/south-texas-health-care/locations/san-antonio-northeast-410-va-clinic/ /// archived,toBeRemoved
vha_671GK02,https://www.va.gov/south-texas-health-care/locations/san-antonio-southwest-military-va-clinic/ /// archived,toBeRemoved
vha_673BV,https://www.tampa.va.gov/locations/Tampa_VA_Domiciliary.asp /// archived, toBeRemoved
```
Because these are not preventing Veterans from getting to necessary information, working these would be just data hygiene. If Drupal is to be the source of truth for URLs, any of this work would be wasted, anyway.

**Comment by jilladams** [comment]
@omahane for end of sprint, I know we asked Lighthouse to make CSV updates. Is there work left for you on this ticket? Or is your comment above asking whether we should do that work or not? Happy to agree with your assessment there, but curious if there are any risks we should record? Sounds like no?

**Comment by jilladams** [comment]
@omahane is there an associated PR here, or it's all just notes to LH for CSV update? I think we said in Planning that as long as we're aligned on punting the non-valuable cleanup work, we could call this Complete Pending Integration,b ut wasn't sure if there's a PR related or not.

I've noted the closed VC with CAPs question for next product sync with Michelle, so we don't lose it.

**Comment by mmiddaugh** [comment]
I emailed RCS to get confirmation that the operating status for Milwaukee Vet Center is accurate, FYI.

**Comment by omahane** [comment]
Confirming these changes are in production
✅ vc_0206V,https://www.va.gov/parma-vet-center/
✅ vc_0234V,https://www.va.gov/toledo-vet-center/
✅ vc_0402V,https://www.va.gov/detroit-vet-center/
✅ vc_0414V,https://www.va.gov/st-louis-vet-center/
✅ vc_0507V,https://www.va.gov/seattle-vet-center/
✅ vc_0736V,https://www.va.gov/springfield-mo-vet-center/
✅ vc_0807MVC,https://www.va.gov/huntington-vet-center/
✅ vc_0863MVC,https://www.va.gov/jackson-vet-center/
✅ vc_0865MVC,https://www.va.gov/lawton-vet-center/
✅ vc_0868MVC,https://www.va.gov/saint-george-vet-center/
✅ vc_0877MVC,https://www.va.gov/shreveport-vet-center/
✅ vc_0880MVC,https://www.va.gov/sacramento-vet-center/
✅ vc_3071OS,https://www.va.gov/san-juan-vet-center/ 	
✅ vc_3072OS,https://www.va.gov/san-juan-vet-center/ 		
✅ vha_436GO,https://www.va.gov/montana-health-care/locations/butte-va-clinic
✅ vha_442GE,https://www.va.gov/cheyenne-health-care/locations/northern-colorado-va-clinic
✅ vha_508GQ,https://www.va.gov/atlanta-health-care/locations/cobb-county-va-clinic
✅ vha_508GS,https://www.va.gov/atlanta-health-care/locations/pike-county-va-clinic
✅ vha_521QB,https://www.va.gov/birmingham-health-care/locations/birmingham-east-va-clinic
✅ vha_605GF,https://www.va.gov/loma-linda-health-care/locations/north-loma-linda-va-clinic
✅ vha_612QE,https://www.va.gov/northern-california-health-care/locations/stockton-va-clinic
✅ vha_636GZ,https://www.va.gov/central-iowa-health-care/locations/south-des-moines-va-clinic
✅ vha_663GK,https://www.va.gov/puget-sound-health-care/locations/everett-va-clinic
✅ vha_674GG,https://www.va.gov/central-texas-health-care/locations/copperas-cove-va-clinic
✅ vha_674GH,https://www.va.gov/central-texas-health-care/locations/killeen-va-clinic

This can be closed.
