### ISSUE TITLE
Discovery: Technical Options Related to Deletion and Retention PDFs in the CMS

### ISSUE THREAD

**Issue by gracekretschmer-metrostar** [department-of-veterans-affairs/va.gov-cms#17648]
## User Story or Problem Statement
Currently, there is not a way to delete PDFs from Drupal, which causes confusion for VA editors creating and managing content and vets consuming possibly inaccurate content. In addition, the VA requires that PDFs are retained for a set period of time, for FOIA request. Therefore, we need to evaluate our technical options to delete PDFs and then have the deleted PDFs moved into a separate environment to meet their rentention requirements.  

## Description or Additional Context 
Currently, the only way to remove an unwanted PDF is to remove the link to it in the content. This does not remove it from our system, it only removes it from being actively published. They can still be found in the CMS media library. Not only does this make it hard for editors to understand what is currently published, it burdens our system with a large amount of old and unused files. However, there may be record retention concerns with deleting these altogether, especially if they must be retained as public record and in the event of a FOIA request.

Could we explore moving PDFs upon "deletion" to an S3 bucket? That way we are retaining what we need and for how long we need to?

## Steps for Implementation
- Evaluate the options to meaningfully delete PDFs from Drupal and determine a path forward
- Evaluate the options to have deleted PDFs retained in a separate environment from Drupal and determine a path forward
- Create a plan of action (including estimates of effort) for how to move forward to implement a workflow to delete PDFs from Drupal and move the deleted PDFs into a separate environment to meet the VA's retention requirements.

## Acceptance Criteria
- [x] An evaluation of both available and best options to delete PDFs within Drupal
- [x] An evaluation of both available and best options to move deleted PDFs into a separate environment from Drupal to meet retention requirements

**Comment by anantais** [comment]
Edmund has started a confluence document for this. I met with him today and went over possible options. He also pointed me towards some modules to look into while he is on the retreat. Once we have finalized the confluence page I will post it here (probably after he gets back next week).

**Comment by anantais** [comment]
One of the modules I will be looking into is https://www.drupal.org/project/s3fs

Edmund has used it before and thought it might help us with creating the S3 bucket.

**Comment by gracekretschmer-metrostar** [comment]
Next steps: schedule a pre-refinement/regroup meeting Thursday or Friday next week.

**Comment by gracekretschmer-metrostar** [comment]
https://vfs.atlassian.net/wiki/spaces/PCMS/pages/3067150440/PDF+Retention+and+Deletion+Issue
