### ISSUE TITLE
2024 CMS Roadmap

### ISSUE THREAD

**Issue by gracekretschmer-metrostar** [department-of-veterans-affairs/va.gov-cms#17640]
## Background
The outgoing Agile 6 team created the first version of the roadmap for 2024, but paused finishing the roadmap when their CMS contract was not renewed. As the new Oddball CMS team came onboard, the CMS Product Manager and CMS Product Owner collaborated on a roadmap for Q1, but paused on creating a larger roadmap for the year until the new team had a first understanding of the system and where each team member wants to move forward within their discipline.

Now that the team is finishing the first quarter, the CMS leadership team needs to collaborate on setting the direction and priorities for CMS through a roadmap. 

### User Story or Problem Statement
As a member of the CMS team, I need to understand the vision, direction and priorities for CMS in 2024, so that I can understand how to shape my own work and priorities for each quarter this year. 

### Relevant Links
- https://vfs.atlassian.net/wiki/spaces/PCMS/pages/2948890632/2024+Roadmap

### Affected users and stakeholders
* CMS Team

## Acceptance Criteria
- [x] An artifact is created that shows the CMS roadmap (vision, direction, and priorities) for 2024. 
- [x] Objectives are determined and connected back to the roadmap, so that the team can understand the goal for each priority.

### Team
Please check the team(s) that will do this work.

- [x] `CMS Team`
- [ ] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`
- [ ] `Accelerated Publishing`

**Comment by michelle-dooley** [comment]
Link to [roadmap mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1710770110435/815417c164d347d6720309063a146709685712f5?sender=u8beee983051743368a5d0733)
