### ISSUE TITLE
[GA Custom Events - PW Team] Custom events for line items 26, 31, 47, 48, 49

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-cms#17652]
## Description

To ensure the custom event analytics still needed in Public Websites managed products is carried over when the Google Analytics upgrade to G4 is performed, 

The following have been identified as being needed, and at this time don't have component baked-in analytics.

Note that we will have several stories that will have five custom events where the code snippet and the file location/name are needed. 

This is the [spreadsheet](https://docs.google.com/spreadsheets/d/1t8FZbUk_B3SaqFcu-9PyR9AV62l7T9gIG1Qq0ms7gPA/edit#gid=2087351809) to log the information into for the Analytics team.

### User story

**AS A**
**I WANT**
**SO THAT**

## Acceptance criteria

- [ ] Line item 26 (File URL and code snippet logged in spreadsheet mentioned above
  - [ ] Find a Form, "Go to the online tool" link, Event Name = cta-primary-button-click
- [ ] Line item 31 File URL and code snippet logged in spreadsheet mentioned above
  - [ ] Home Page, (Hero CTA) "Learn what the PACT Act means for you" link, Event Name = homepage-benefit-link-click
- [ ] Line item 47 File URL and code snippet logged in spreadsheet mentioned above
  - [ ] On-site search results, (Search results) Search result click (example: "The PACT Act and your VA benefits"), Event Name = onsite-search-results-click
- [ ] Line item 48 File URL and code snippet logged in spreadsheet mentioned above
  - [ ] On-site search results, (Search results) If a best bet exists, this event is recorded (example: "VA/DoD eBenefits"), Event Name = nav-searchresults
- [ ] Line item 49 File URL and code snippet logged in spreadsheet mentioned above
  - [ ] On-site search results, (Searching) When a query is typed and the search button is clicked, Event Name = event is variable; it could be a search term or a typeahead selection

**Comment by FranECross** [comment]
Fran to check with Jamie on whether they need each snippet of variable code or if the 'generic' along with the file name/location will do.

**Comment by FranECross** [comment]
Per Randi's meeting with Jamie on the analytics team, this is no longer needed, and Randi's current spreadsheet will suffice. Closing.

**Comment by randimays** [comment]
Closing per Fran's comment above.
