### ISSUE TITLE
VACMS orientation for developers on product teams

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#1765]
### User Story or Problem Statement

As a developer on a va.gov VFS product team, i want to understand how to work with VACMS so that i can build products and features. 

### Affected users and stakeholders

* Developers on product teams.
* Particular need expressed from Public Websites team.

**Comment by sandyisland1** [comment]
@kevwalsh : Has this issue been resolved?
