### ISSUE TITLE
VAMC Facility closed: Elmendorf-Richardson VA Clinic

### ISSUE THREAD

**Issue by ian-sears** [department-of-veterans-affairs/va.gov-cms#17658]
## Intake
- [x] What triggered this runbook? (Flag in CMS, Help desk ticket, Product team, VHA Digital Media)
Trigger: Removed from source flag

- [x] Link to associated JIRA help desk ticket (if applicable)
Help desk ticket: [https://va-gov.atlassian.net/browse/VAHELP-7224](https://va-gov.atlassian.net/browse/VAHELP-7224)

- [x] Name of submitter (if applicable)
Submitter: Flagged Facilities

- [x] If the submitter is an editor, send them a link to the KB article: [How to archive a closed facility](https://prod.cms.va.gov/help/vamc/about-locations-content-for-vamcs/how-to-archive-a-closed-facility)

- [x] Link to facility in production:
Facility CMS link: [https://prod.cms.va.gov/alaska-health-care/locations/elmendorf-richardson-va-clinic)](https://prod.cms.va.gov/alaska-health-care/locations/elmendorf-richardson-va-clinic)
Facility API ID: vha_463QA

#### CMS Help desk steps
**Note: If the help desk is waiting on information from the facility staff or editor, add the "Awaiting editor" flag to the facility with a log message that includes a link to this ticket. Remove the flag when the ticket is ready to be worked by the Facilities team. Be sure to preserve the current moderation state of the node when adding or removing the flag.**
- [x] 1. CMS team becomes aware that the facility is no longer on the Facility API.
- [x] 2. If we don't already have context (say, via a HD ticket submitted by an editor), check with editor to find out more about the status of the facility
- [x] 3. Find out if there are any services or events tied to the facility to be archived that should be moved to a new facility or otherwise preserved and updated

[@TODO: Update email template]

<details><summary>Email template </summary>

```
SUBJECT: <facility name> removed from VAST

Hi [VAMC editor(s) who own the node in CMS]

We see that [name of facility] has been removed from VAST. If this facility has been permanently closed or moved, you can work with us to unpublish the facility from the CMS and remove it from VA.gov.

Because some Veterans may have bookmarked this facility, external sites may have linked to it, and because it can take a little time for search engines to catch up to web content, we want prevent errors and bad web experiences for our Veterans.

In order to do that we have some questions about the nature of this closure so that we can help redirect Veterans to the right place and understand this change.

1. Was this facility replaced with another facility?
   If yes, which one?
2. Is there a news release or story about this published on your VAMC website?
3. Anything else we should know about this facility closure?

If this facility has been removed from VAST in error, please notify the VA Drupal CMS Help Desk Support Team by writing to support@va-gov.atlassian.net, and please also notify your VAST coordinator.

[outro]

[CMS helpdesk signature]
   
Alternative, for "Removed From Source" flag follow-up:
-----------------------
During a site-wide review, our team found a location within the [INSERT SYSTEM NAME] health care system that is no longer listed within the Facilities API, but still exists within Drupal.

Can you please tell us more about the status of the [CLINIC NAME]?  Thanks!

Here is a link to the clinic homepage, which is still published on the live site: [INSERT CLINIC HOMEPAGE LINK FROM LIVE SITE]

Here is a link to this page on the production site:  [INSERT CLINIC HOMEPAGE LINK FROM PRODUCTION SITE]

IF THIS FACILITY IS CLOSED: 
Please follow the steps listed in the following Knowledge Base article in order to fully archive it from VA.gov: https://prod.cms.va.gov/help/vamc/about-locations-content-for-vamcs/how-to-archive-a-closed-facility

Important: Once these steps have been followed, please reach back out to the VA Drupal CMS Help Desk by replying to this email or by writing to support@va-gov.atlassian.net. 

From there, our engineering team will proceed with next steps for archiving this facility.

If the clinic has not been closed, please also let our team know as soon as possible.

Thank you for your help!
   
[Signature]
   
```
</details>

- [x] 4. Are any of the services or upcoming events for the facility to be closed moving to a different facility?
  - [x] 4a. If so, note the facility picking up the services and events here: [Joint Base Elemendorf-Richardson VA Medical Center](https://prod.cms.va.gov/alaska-health-care/locations/joint-base-elmendorf-richardson-va-medical-center)
  - [x] 4b. If so, note the services and events here: 
  [Mental health care at VA Alaska health care](https://prod.cms.va.gov/alaska-health-care/locations/elmendorf-richardson-va-clinic/mental-health-care)
  [Orthopedics at VA Alaska health care](https://prod.cms.va.gov/alaska-health-care/locations/elmendorf-richardson-va-clinic/orthopedics)
  [Primary care at VA Alaska health care](https://prod.cms.va.gov/alaska-health-care/locations/elmendorf-richardson-va-clinic/primary-care)
  [Radiology at VA Alaska health care](https://prod.cms.va.gov/alaska-health-care/locations/elmendorf-richardson-va-clinic/radiology)
- [x] 5. Create a [redirect request](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/new?assignees=&labels=Redirect+request&template=redirect-request-facility-url.md&title=Redirect+Request+for%3A+%3Cinsert+facility+name%3E) from the URL of the facility to be closed to the URL of its parent system.

[#17663](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17663)

#### CMS Engineer steps
- [x] 6. Execute the steps of the URL change request ticket from step 5 above.

(Redirects deploy weekly on Wed. at 10am ET, or by requesting OOB deploy (of the revproxy job to prod) in #vfs-platform-support. Coordinate the items below and canonical URL change after URL change ticket is merged, deployed, and verified in prod.)

#### Drupal Admin steps (CMS Engineer or Helpdesk)
_Help desk will complete these steps or escalate to request help from CMS engineering._
- [x] 7. When redirect has been deployed, make these changes. Practice first on staging or a demo environment.
  - [x] 7a. Drupal Admin bulk moves any content identified **4b** to new facility **4a**.
  - [x] 7b. Drupal Admin edits the facility node, removes flag `Removed from source`, add a revision log that explains the change, with a link to github issue, and change moderation state to archive. (Note: any remaining health services, non-clinical services and events for the given facility will be archived automatically when these changes are saved.)
  - [x] 7c. Drupal Admin finds the menu for the system https://prod.cms.va.gov/admin/structure/menu and deletes the menu item for the facility being closed.

#### CMS Help desk (wrap up)
- [x] 8. Help desk notifies editor and any other stakeholders.

**Comment by ian-sears** [comment]
I reached out to the Editor, which looks to be Timothy.Chavis@va.gov via Jira Ticket https://va-gov.atlassian.net/browse/VAHELP-7224 to ask if this facility is Closed. Awaiting Editor

**Comment by ian-sears** [comment]
We've escalated attempts to reach an Editor to VHADigitalMedia, asking for assistance in reaching their CBOC.
Awaiting Customer in [VAHELP-7224](https://va-gov.atlassian.net/browse/VAHELP-7224)
@TroyCMSSupport FYSA
Spreadsheet updated. Collapsed JIRA-6958 into the above parent JIRA ticket #7224.

**Comment by ian-sears** [comment]
Spoke in depth and at length with the Editor (via screenshare on Teams). Samuel Hudson is reaching out to his VAST coordinator to inquire why this was (VAST request??) requested to be closed. This facility page is correct, the Editor is going to go over it in detail just to be certain of that, and no change should be made.
This was possibly removed from source in error.

**Comment by jilladams** [comment]
I'm going to go ahead and close this  Github since we think there's no action for Sitewide, and the correction needs to come from VAST. If that turns out to be incorrect, this ticket can be reopened.

**Comment by ian-sears** [comment]
Clarity from the Editor.
The Joint Base Elmendorf facility (vha_463A4) #18489 is REPLACING the Elmendorf facility (vha_463QA).

**Comment by jilladams** [comment]
What does that mean about the work that needs to be done here?

**Comment by ian-sears** [comment]
Editor is completing the Joint Base Elmendorf node information in preparation to Publish. Once Published we can execute the Archival process of the currently Published, but Removed from Source Elemendorf page, moving the traffic, redirect, et to the new Joint Base Elmendorf facility page.

**Comment by ian-sears** [comment]
Still awaiting Editor to complet addition of facilityu Health Services to the Joint Base Elmendorf facility prior to the removal of this facility. Will update here once that has been completed.

**Comment by omahane** [comment]
@ian-sears @TroyCMSSupport I see that the editor added a page intro a week or so ago (July 23). Can you see if there's something holding up the creation of the services? They already services on the one that is closing: https://prod.cms.va.gov/alaska-health-care/locations/elmendorf-richardson-va-clinic. While we don't want them moved but recreated, it should be a relatively trivial matter, if the same services are being offered, that is.

**Comment by ian-sears** [comment]
I once again reached out to the Editor last night via the ongoing Jira tickets to get this done. The Editor expressed distress at understanding the process of "moving" Health Services from one facility to the other and described difficulty at their facility for him to get the subordinate tasked with doing this into a meeting (with him). That was a month ago.

Only two things I see holding this up is for the DRAFT Joint Base Elmendorf facility to have the remaining 4 of total of 5 Health Services moved over, and then the Joint Base Elmendorf Hours of Operation to be updated via VAST request from the Editor (currently just reads "24/7").

However the Editor has become unresponsive to requests for status or estimate of when this will be completed.

I'm about to escalate to VHADigitalMedia due to unresponsiveness.

Get the Joint Base Elmendorf stood up, and then migrate the Elmendorf traffic over to close it.

**Comment by omahane** [comment]
@ian-sears Has this been escalated? I'd like to move this closed facility through but closing it without publishing its replacement doesn't help Veterans that much.

**Comment by ian-sears** [comment]
Just awaiting the Redirect to take place prior to closing this facility. Ref #17663

**Comment by omahane** [comment]
@ian-sears The redirect has been deployed. This ticket can be closed after any editor confirmation.

**Comment by ian-sears** [comment]
Editor has been notified. [VAHELP-7224](https://va-gov.atlassian.net/browse/VAHELP-7224) CMS Help Desk ticket closed as complete. Closing this GH as complete as well.
