### ISSUE TITLE
Sitewide UX Sync (2024)

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#17669]
NEW: Expanding Facilities UX sync to incorporate Public Websites as Sitewide UX Sync

## Jump link to latest agenda
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17669#issuecomment-2181118389

## Meeting Purpose and Structure

This is a weekly meeting where we focus on the following actions:
- Presenting Sitewide UX work for feedback / signoff
- Roadmapping Sitewide UX work for prioritized initiatives
- Refining cards for upcoming UX work

## Meeting logistics
- Thursdays at 3:05 - 4:00 pm ET
- Zoom link: https://us06web.zoom.us/j/83523330154?pwd=6MBNJhHaoBibK2P7aDstaievaK4l2s.1
- Scheduled via Sitewide Team Google calendar
- The second Thursday of every month, @davidconlon, @mmiddaugh, and @aklausmeier have a conflict for the second half hour of the meeting so we need to be sure to prioritize those agendas accordingly

## Agenda

- The agenda is updated on a weekly basis by @davidmpickett 
- Draft agenda will be sent out ~24 hours in advance via Slack
- If you have an item you would like to add, you can always add a comment to the ticket async
- Agenda items should have clear action-oriented language. Why are we looking at this item? What is the desired feedback or next step?
- Agenda items should ordered from highest priority to lowest priority
- Agenda items should have a rough time box

## Attendees

- Core attendees 
  - Sitewide UX team members (@davidmpickett, @thejordanwood, @laflannery) 
  - Facilities PM /  PO (TBD, @mmiddaugh)    
  - Public Websites PM / PO (@FranECross, @davidconlon )
  - Sitewide UX Lead (@aklausmeier) 
  - Sitewide Delivery Manager (@jilladams )
- All other attendees are optional and may choose to join or skip based on agenda
  - Sitewide Devs ( @omahane, @eselkin, @maxx1128, @randimays, @chriskim2311 , @dsasser )

**Comment by jilladams** [comment]
Q from Amanda here: 
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16586#issuecomment-2024134170
> 
@jilladams @davidmpickett Does this thought process also include scrapping Public Websites UX refinement and rolling into the Sitewide UX sync?

@aklausmeier hadn't gotten that far - good Q. I did keep PW UX Prefinement on calendar, but we've been mostly canceling it lately. @FranECross let's discuss with Amanda, and see how everyone feels about collapsing the meetings. Main action out of that would just be to make sure that if we have design / research projects for Public Websites, that we give Dave advance notice enough to get them on the agenda to get them in the agenda to address in this context. Good topic for all the team forming stuff next week.

**Comment by davidmpickett** [comment]
## Agenda for 4/4/24

- Why does this meeting exist? Quick explanation for new attendees - @davidmpickett (5 min)
- Service Location designs - @thejordanwood (15 min)
- Prefining Service Location tickets - @davidmpickett (15 min)

## Why does this meeting exist?
- Read through the top of this ticket

## Service Location designs
- Ticket:
- Designs:
- Notes:

## Service Location tickets to pre-fine
- Ticket 1
- Ticket 2

**Comment by jilladams** [comment]
@jilladams to update #16686 with updated priority order of UX projects based on comment above

**Comment by FranECross** [comment]
@davidmpickett Here's an item from Public Websites for the 4/11 Sync meeting: [[UX - TESTING] Test PW managed apps/features/products against a 640px breakpoint #17762](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17762)  Thanks in advance!  cc @thejordanwood @jilladams

**Comment by davidmpickett** [comment]
## Agenda for 4/11/24

- (3 min) Review agenda and assign notetaker
- (10 min) Breakpoint testing `Sitewide`
- (10 min) VA Health Chat & Heath Connect research findings `Facilities`
- 



## Topic

**Comment by davidmpickett** [comment]
## Agenda for 4/18/24

- Vet Centers 2.0 discovery discussion (20 min)

**Comment by davidmpickett** [comment]
## Agenda for 4/25/24

- Let's all look at what Jordan mocked up for #17680
- Does @laflannery have to sneeze (aka remember the question she mentioned she might have)? We'll find out

**Comment by FranECross** [comment]
Notes for today on - Events v2: 
  - Events v2: 
  - Amanda: there is a current product for events. We didn't know if we were going to iterate or rebuild the whole thing. There's another team - IIR - they help from time to time on tickets. They did some research / discovery and identified a couple of areas we can improve upon. They have a mural of research discovery. They have early design iterations of potential solutions. IIR team will meet with product folks, Jill, Amanda to level set on their vision and hand-off. Then Fran/Dave C can realign on the scope. Amanda's idea for Carissa is that she can pick up where they left off. She can get to know the product.
  - Dave: That's basically it. We're waiting for things to come back to us and this is a great opp for Carissa to familarize herself with that. Jill has peppered links into convo earlier of examples of existing events. Here's an example from Dave: https://www.va.gov/chicago-health-care/events/. We'll get her other links to product overview. 
  - Jill: Change from Events v2 > in 2022 when Michelle was still the FE product lead at ad-hoc for facilities. There was a project to create filters, and for that effort they called that for Event's v2; this is used in code and documentation. We'll go with Events v3 (Amanda okayed for now as a placeholder). Fran/Jill to change all instances of Events v2 (for our new endeavor) to Events v3.

**Comment by davidmpickett** [comment]
# Agenda for 5/9

- #17966

**Comment by FranECross** [comment]
@Dave Pickett For consideration to add to the Sitewide UX Sync meeting agenda ☝🏼 UX stories in our backlog (I may have already shared one?) (I also posted in the DSVA Slack Sitewide UX channel for visibility). cc @jilladams @thejordanwood 

- [[Events] [UX] Recurring events "View other times for this event" shows past recurrences](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16472)
- [[Discharge Upgrade Wizard] [UX] Provide design/UX logic to display questions after Discharge Year "Before 1992"](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18025)
- [[PACT Act Wizard] [UX] Determine if PAW should have a review screen for Veterans et al to review answers before final Results screen](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18030)

**Comment by davidmpickett** [comment]
## Agenda for 5/19

- Review agenda, assign notetaker and timekeeper (5 min)
- Walk through of Vet Center differentiation design exploration - @thejordanwood (20 min)
- Vet Center 2.0 UX ticketing philosophy - @davidmpickett (10 min)

### Vet Centers are not medical centers, ya hear?
- #17891
- [Figma](https://www.figma.com/design/EVd3q06ukAbVS61Q8MwRAT/Vet-Centers?node-id=21-2&t=XKWVtxBUWmdkcE5c-0)


### Vet Center 2.0 UX ticketing philosophy
- #18098

**Comment by davidmpickett** [comment]
## Agenda for 5/23
- Vet Center 2.0 - Satellite locations - @thejordanwood (20 min)
- Vet Center 2.0 - IA - @davidmpickett (15 min)
- Spotlights on Vet Centers - color and grid (10 min)
  - https://dsva.slack.com/archives/C06S9DADEUB/p1716313396255239
  - https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18126
- Refine some tickets

## Vet Center 2.0 - Satellite locations
- #18121

## Vet Center 2.0 - IA
- #17195

## Spotlights on Vet Centers
- Color  https://dsva.slack.com/archives/C06S9DADEUB/p1716313396255239
- #18126

## Tickets to refine
- #15349
- #17695
- #17966
- #18197

**Comment by davidmpickett** [comment]
## Agenda for 5/30
- #17929

**Comment by FranECross** [comment]
## Agenda for 6/6

PW Team tickets for refinment:

- [[Discharge Upgrade Wizard] [UX] Identify content and placement of text telling Veterans they may apply online or download a form #18154](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18154)
- [ [Events] [UX] Provide error message text for Events filter #18197](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18197)

**Comment by davidmpickett** [comment]
## Agenda for 6/20

**Comment by davidmpickett** [comment]
Closing in favor of a Slack List going forward https://dsva.slack.com/lists/T03FECE8V/F079N7QEZ45
