### ISSUE TITLE
Facilities Sprint 2 plan

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#17687]
## Schedule Notes
- Max OOO: Wed 4/17
- Eli OOO: Wed 4/24
- DaveP OOO: Fri 4/19, Mon 4/22
- Jordan OOO: Mon 4/22-Fri 4/26
- Jill OOO: 1/2 day Mon 4/22; Wed 4/24; 1/2 day Fri 4/26
- Michelle OOO Wed 4/24-Fri 5/3

## Sprint Priorities 🎯 
At the end of this sprint, what do we want to have accomplished/delivered?
* UX: department-of-veterans-affairs/va.gov-cms#17806 -- May 8 DS proposed ship date so if environment becomes available this will move after PTO
* FE: department-of-veterans-affairs/va.gov-cms#17737
* Drupal: department-of-veterans-affairs/va.gov-cms#17843 - needs estimate 

#  CY Q2 Priorities

<details><summary>Numbered list </summary>

1. department-of-veterans-affairs/va.gov-cms#17653
2. department-of-veterans-affairs/va.gov-cms#17722
3. department-of-veterans-affairs/va-iir/issues/553
4. department-of-veterans-affairs/va.gov-cms#14507
   4a. department-of-veterans-affairs/va.gov-cms#15344
   4b. department-of-veterans-affairs/va.gov-cms#12907
5. department-of-veterans-affairs/va.gov-cms#16825
6. department-of-veterans-affairs/va.gov-cms#16268
7. department-of-veterans-affairs/va.gov-cms#15037
8. department-of-veterans-affairs/va.gov-cms#14225
9. department-of-veterans-affairs/va.gov-cms#17655
10. department-of-veterans-affairs/va.gov-cms#17708
    10b. department-of-veterans-affairs/va.gov-cms#7818
11. department-of-veterans-affairs/va.gov-cms#17661
13. department-of-veterans-affairs/va.gov-cms#12923
14. department-of-veterans-affairs/va.gov-cms#14477
16. department-of-veterans-affairs/va.gov-cms#12942
17. department-of-veterans-affairs/va.gov-cms#14327
18. department-of-veterans-affairs/va.gov-cms#15541
19. department-of-veterans-affairs/va.gov-cms#17748
20. department-of-veterans-affairs/va.gov-cms#17350 

</details>

## 2) va-icon adoption - end of May deadline - department-of-veterans-affairs/va.gov-cms#17722
- In sprint: will be talking to IIR / DS about whether we can get help. Not pulling any tickets into Sprint 2.

## 3) Security / PII issue - https://github.com/department-of-veterans-affairs/va-iir/issues/553
- FE - May need some capacity to review work done by IIR

## 5) VBA/VAMC Service Location enhancements - department-of-veterans-affairs/va.gov-cms#16825
- Drupal department-of-veterans-affairs/va.gov-cms#17605 -- rollover from Sprint 1
- Drupal department-of-veterans-affairs/va.gov-cms#17843 -- Need refined (sprint goal)
- FE department-of-veterans-affairs/va.gov-cms#17844 -- Needs refined
- FE/UX(Dave) department-of-veterans-affairs/va.gov-cms#17632 -- if it fits

## 6) VBA Staging review blockers - department-of-veterans-affairs/va.gov-cms#16268
- FE department-of-veterans-affairs/va.gov-cms#17599
- FE department-of-veterans-affairs/va.gov-cms#17710
- FE department-of-veterans-affairs/va.gov-cms#17598
- FE department-of-veterans-affairs/va.gov-cms#15223
- Drupal department-of-veterans-affairs/va.gov-cms#15155

## 9) Adopt V1 & V3 components to replace custom code implementations department-of-veterans-affairs/va.gov-cms#17655
- UX department-of-veterans-affairs/va.gov-cms#17806
- FE department-of-veterans-affairs/va.gov-cms#16148

## 10) Vet Centers remove IEF - department-of-veterans-affairs/va.gov-cms#17708
- UX & Drupal department-of-veterans-affairs/va.gov-cms#17680 -- Stretch, due to Jordan's PTO. Won't close in sprint.

## 20) Improve services accordions & locations across products - department-of-veterans-affairs/va.gov-cms#17350
- FE department-of-veterans-affairs/va.gov-cms#17514
- FE department-of-veterans-affairs/va.gov-cms#17415 

# Other Work (Not Q2 Prioritized)
- Drupal department-of-veterans-affairs/va.gov-cms#17621
- department-of-veterans-affairs/va.gov-cms#17848 -- 

# Sprint 3

Moved to #17895

**Comment by jilladams** [comment]
@davidmpickett FYI this exists, scratch pad for now. Feel free to scratch as well.

**Comment by davidmpickett** [comment]
@jilladams FYI - I have been scratching away. I think the Scrub section is handled, but leaving it here with notes for you to confirm

**Comment by davidmpickett** [comment]
@jilladams Converted this into an Epic and added all issues that are under consideration so we can get the [quick view](https://github.com/department-of-veterans-affairs/va.gov-cms#workspaces/sitewide-facilities-639f5253e4b702a32376339e/board?epics=Z2lkOi8vcmFwdG9yL0VwaWMvMTEzNTc0OA) of where they are in the pipeline. I also moved any ticket that is potential for Sprint 2 to the top of the Next Refinement column.

**Comment by davidmpickett** [comment]
@jilladams I updated this to have a numbered list of the 20 Q1 priorities and updated section headers to match

**Comment by jilladams** [comment]
- [Proposed FE load](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10514#workspaces/sitewide-facilities-639f5253e4b702a32376339e/board?epics=Z2lkOi8vcmFwdG9yL0VwaWMvMTEzNTc0OA&labels=va.gov%20frontend): 40 points. Need to get down to ~25
- [Proposed Drupal load](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10514#workspaces/sitewide-facilities-639f5253e4b702a32376339e/board?epics=Z2lkOi8vcmFwdG9yL0VwaWMvMTEzNTc0OA&labels=drupal%20engineering): 21 points. Need to get down to ~12-15
- [Proposed UX load](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10514#workspaces/sitewide-facilities-639f5253e4b702a32376339e/board?epics=Z2lkOi8vcmFwdG9yL0VwaWMvMTEzNTc0OA&labels=ux): 13 points, need to drop to ~8-9

My proposed cuts: 
* FE: 16pts
    * #17411 
    * #17410 
    * #17566 
    * #17601 
    * #17415 
* Drupal: 8pts
    * #17124 - can be top of stretch
    * #17674 (not refined)
* UX: #17680 -- moves to Sprint 3, or Jordan can start it post-PTO if she has time after typography audit

**Comment by jilladams** [comment]
@mmiddaugh I think this is ready for a look from you, with consideration for my note above.

**Comment by davidmpickett** [comment]
I agree with FE cuts. 

**Drupal**
Want to point out that 17680 is counting in Drupal and UX. So Drupal load might be a few points lower. 

I think 17674 is higher value than 17124 and if it can be refined async then it should be on the list for next week

**UX**
17632 is a FE ticket with design review so those 3 points aren't really UX points. This is one I will be reviewing/ QAing, so doesn't need to affect Jordan's capacity. 

I think it's good to leave in 17680 since it's a blocker for a Drupal priority. Make as much progress as possible.

**Comment by jilladams** [comment]
Also: 2 defects that are not in plan that will need tradeoffs if we add them: 
* #17547 
* #15664 -- still repros

Neither are refined yet

**Comment by jilladams** [comment]
@mmiddaugh @davidmpickett noting: Eli finished the va-icon audit, and we have a 5pt ticket (#17855) to do the updates once DS guidance is available (in the next week, per Carol Wong. this morning). I've swapped that into plan.

**Comment by jilladams** [comment]
Removing - now marked blocked on VHA DM comms strategy: 

## 7) Link to Health chat from VAMC pages - #15037
- FE #17436

**Comment by mmiddaugh** [comment]
Given availability of environment to audit typography impact, suggest 
- prioritize and 🎯 [Draft updated editorial flow for updated Vet Center services #17680](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17680) first 
- return to [Audit DS-staged typography update for product impact #17806](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17806) after Jordan returns 

Suggest pushing out to Sprint 3 (or giving back to the Design system)
- FE: #17411
- FE: #17410

Keep
- FE: #17415
- FE  #16148 
- Drupal: #17621

Push to Stretch or Sprint 3
- FE: #17632 (unless it is very quick)
- FE: #17566
- FE: #17601
- FE: #17547 (prioritize for next refinement) 
- FE: #15664 (prioritize for next refinement)
- Drupal:  #17124
- Drupal: #17674 (prioritize for next refinement) 
- Drupal: #14531

**Comment by jilladams** [comment]
* Updated sprint goals 
* Moved demoted tickets to the Sprint 3 draft plan epic: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17875


- [Proposed FE load](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10514#workspaces/sitewide-facilities-639f5253e4b702a32376339e/board?epics=Z2lkOi8vcmFwdG9yL0VwaWMvMTEzNTc0OA&labels=va.gov%20frontend): 22 points ready; 2 tickets need refined. Should be good.
- [Proposed Drupal load](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10514#workspaces/sitewide-facilities-639f5253e4b702a32376339e/board?epics=Z2lkOi8vcmFwdG9yL0VwaWMvMTEzNTc0OA&labels=drupal%20engineering): 9 points ready; 1 ticket to refine. Woo.
- [Proposed UX load](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10514#workspaces/sitewide-facilities-639f5253e4b702a32376339e/board?epics=Z2lkOi8vcmFwdG9yL0VwaWMvMTEzNTc0OA&labels=ux): still 13 points but acknowleding the typography work will come after the IEF flow stuff

Go team. Thanks for all your help, @mmiddaugh and @davidmpickett
