### ISSUE TITLE
"Additional Hours Options" content shows in Italics

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#17686]
## Description
I added test content for training into the "Additional Hours Options" field for VBA Services and it showed on the front end in italics:
<img width="802" alt="Screenshot 2024-03-29 at 4 23 14 PM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/106678594/284237ff-6864-45f1-891a-f132484b1688">

![Screenshot 2024-05-09 at 9 30 51 AM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/85581471/258b281a-b81d-45c7-ad4e-7ae2accba98e)

This is not part of the VA style guide, we don't use italics and we also try our best to avoid this for accessibility reasons. For these reasons we need to remove this styling.

### Additional Info
- I couldn't actually find this in the VBA comp at all so I'm not sure what the design intent was here. Jordan signed off on making this plain text.
- This also happens on Vet Centers ([Mental Health for Bath VA Medical Center](https://www.va.gov/finger-lakes-health-care/locations/bath-va-medical-center/#mental-health-care)) so this was probably copied directly from there and retained the same styles but it should be updated on Vet Centers as well.

## Acceptance Criteria
- [x] Content from the "Additional Hours Options" field is no longer displayed with italics on the FE on VBA
- [x] Content from the "Additional Hours Options" field is no longer displayed with italics on the FE of VAMCs
- [ ] Requires design review

**Comment by mmiddaugh** [comment]
@laflannery this occurs on VAMC pages also - check out [Mental Health for Bath VA Medical Center](https://www.va.gov/finger-lakes-health-care/locations/bath-va-medical-center/#mental-health-care)

**Comment by mmiddaugh** [comment]
As this exists today on Prod for VAMCs, I don't know that it should be considered a launch blocker - although it does need to be addressed @jilladams

**Comment by jilladams** [comment]
Moving to the National rollout epic to reflect that it won't block Staging Review / launch. (Unless Staging Review tells us otherwise)

**Comment by davidmpickett** [comment]
Confirmed on Prod for VAMCs
https://www.va.gov/lovell-federal-health-care-va/locations/captain-james-a-lovell-federal-health-care-center/#dermatology

![Screenshot 2024-07-05 at 1 56 32 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/1e95f5db-19aa-49bd-b4f1-994557e925c5)

Confirmed on Tugboat for VBA

![Screenshot 2024-07-05 at 1 49 07 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/2d7bc002-5ebf-454c-a918-34cd25056254)
