### ISSUE TITLE
Draft Content model for Vet Center Satellite Locations having services & their own pages

### ISSUE THREAD

**Issue by davidmpickett** [department-of-veterans-affairs/va.gov-cms#17695]
## User Story or Problem Statement

**Satellite locations should have an option to include services and be discoverable in their own right** 

- How might we support expansion of these pages (i.e. support for other location types)? Only Vet Centers have pages and associated services. Other locations where services are available are included on the Locations page for the parent Vet Center. Some satellite locations are very similar in maturity to a full Vet Center and may have dedicated staff, daily hours and a full suite of services. Without their own page, they can be difficult to discover because Veterans do not know to search for these locations in the context of a main Vet Center.
- Is the MVP approach to organization of services working?

## Description or Additional Context 
 - [x] not every satellite location might have the same needs
   - [x] have services or not
   - [x] i.e. distinguish within outstations , not just outstations vs CAPs 
- [x] MENUs ughhhh

## Acceptance Criteria
- [x] Proposed entities and relationships are documented 
- [ ] Reviewed with engineering & product
- [ ] Send to CMS Collab Cycle

**Comment by davidmpickett** [comment]
@davidmpickett to refine async

**Comment by davidmpickett** [comment]
https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1719513855223/66baec9950d315cd88ecde19264548fd8910c245?sender=u9c899abc4fe36c9a698b1647 has begun

**Comment by davidmpickett** [comment]
Now with a [Proposed Content Flow](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1719513855223/66baec9950d315cd88ecde19264548fd8910c245?wid=0-1719616348210) and a [Change Analysis](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1719513855223/66baec9950d315cd88ecde19264548fd8910c245?wid=0-1719616985082). I plan to discuss these with @mmiddaugh on Monday during our 1on1 for gut checking and then will loop others in for feedback.

**Comment by davidmpickett** [comment]
Drupal entity | Machine name | proposed change
-- | -- | --
-- | vet_center
Vet Center - Facility Service | vet_center_facility_health_servi | Update field_office entity reference to include Outsations and CAP+s
Vet Center - Locations List | vet_center_locations_list
Vet Center - Outstation | vet_center_outstation
-- | vet_center_cap
Vet Center - Mobile Vet Center  | vet_center_mobile_vet_center
-- | centralized-content/national-vet-center-content
VA Service taxonomy | health_care_service_taxonomy |

**Comment by davidmpickett** [comment]
**End of Sprint Update** 
- I did an initial gut-check review with Michelle on Monday Jul 1 in 1on1.
- [I shared drafts on Slack](https://dsva.slack.com/archives/C0FQSS30V/p1719954611225279) to allow async review.
- I proposed a sync meeting for content setting and discussion that's not likely to occur in sprint bounds.

**Comment by jilladams** [comment]
Per Michelle: let's try to time content strategy review alongside other Drupal work, to keep the loops tight. @Agile6MSkinner we should discuss what to do with this ticket for end of sprint that in mind.

**Comment by omahane** [comment]
I believe that I understand that only some CAPs will have their own pages, those are being called CAP+s. I'm trying to understand what will distinguish a CAP from a CAP+. Is it services?

**Comment by davidmpickett** [comment]
> I believe that I understand that only some CAPs will have their own pages, those are being called CAP+s. I'm trying to understand what will distinguish a CAP from a CAP+. Is it services?

- Definitely Services & Prepare for your Visit accordions
- Likely Spotlights
- Maybe events

**Comment by Agile6MSkinner** [comment]
If the content model is drafted then this ticket is done. Let's close it.

**Comment by jilladams** [comment]
Next steps probably story mapping.

**Comment by mmiddaugh** [comment]
@jilladams @Agile6MSkinner is this enough for a Drupal engineer to act on?

**Comment by jilladams** [comment]
I believe @FranECross has a story mapping scheduled for Vet Center satellite locations, if I'm not mistaken?

**Comment by FranECross** [comment]
I haven't scheduled anything yet because of R&S and shift in personnel. Didn't want to detract from that, but will look at the calendar and get something scheduled later this week/next week.
