### ISSUE TITLE
[UX] Provide verbiage for fields in Drupal Aging Content Developer Configuration UI

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-cms#17691]
## Description

As part of the Aging Content Notifications work, new Drupal UI fields have been created that will be developer-facing only (editors won't see or utilize these screens or features). Our ask in this UX ticket is that more user-friendly, descriptive language be used to help guide developers when they're configuring a content-type's expiration and notifications.

Please work with Daniel Sasser if you have any questions.

Glossary

- Entity = Content
- Bundle - Description

## Artifacts

1. Ticket for Drupal work: #15506 
 
2. Expirable Content types fields

![image-1](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/104526584/8f02f0a2-75d2-43cd-806c-2055e4bc8a5c)

3. Structure fields

![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/104526584/c41e3d2d-1b25-4e84-879a-a16dddd29379)

### User story

**AS A** Drupal developer who is configuring aging content expiration and notifications for one or more content types (banner, block, etc.)
**I WANT** descriptive labels on the various fields in the UI that I'll utilize
**SO THAT** I can easily and quickly configure the aging content expiration and notification emails

## Final help text

'Structure' screen: No changes

'Expirable Content types' screen: 

> **Entity type**
> Select the entity type to add content that can expire.
> 
> **Entity bundle**
> Select the bundle of the entity type.
> 
> **Last updated field**
> Select the name of the field that will calculate when the entity was last updated.
> 
> **Days before expiration**
> Enter the number of days before the entity will expire. This will be the number of days after the entity was created or last updated.
> 
> **Days to notify before expiration**
> Enter the number of days to notify an editor before an entity expires.

## Acceptance criteria

- [x] Fields on the 'Expirable Content types' screen are user-friendly
- [x] Fields on the 'Structure' screen are user-friendly (no changes)
- [x] Review with engineers
- [x] Review with accessibility 
- [x] Review with PM/DM

**Comment by FranECross** [comment]
@thejordanwood We have a (hopefully small) task for you to come up with verbiage other than machine names for developer-only facing UI. I've noted in the description the ticket Daniel is working on and he'll be a good resource for questions. I wonder if it's possible that you're able to async this in the sprint that just started? cc @jilladams @dsasser

**Comment by thejordanwood** [comment]
@FranECross I've refined this ticket and added it to this sprint. I'll async with @dsasser when I start this ticket later this week. 

I also want to note that I added an accessibility review for this ticket, but mainly because @laflannery is great to bounce content ideas off of.

**Comment by FranECross** [comment]
@thejordanwood Thanks so much! And also thanks for adding the a11y review. I totally forgot 😁

**Comment by thejordanwood** [comment]
@laflannery @dsasser Here's my first pass at updated help text for these fields. Since the audience will be developers only, I'm going to assume they know what an entity type and bundle is. I'm open to any suggestions that you have. 

**Entity type**
Select the entity type to add content that can expire. 

**Entity bundle**
Select the bundle of the entity type. 

**Last updated field**
Select the name of the field that will calculate when the entity was last updated. This must be a date field. 

**Days before expiration**
Enter the number of days before the entity will expire. This will be the number of days after the entity was created or last updated.

**Days to notify before expiration**
Enter the number of days to notify an editor before an entity expires.

**Comment by laflannery** [comment]
@thejordanwood and/or @dsasser  - Question on the Last Updated Field:
- This is a dropdown that I feel like is probably pulling fields from the entity. Is it pulling all fields and that's why we want to clarification in the help text for "It must be a date field"?

**Comment by dsasser** [comment]
> @thejordanwood and/or @dsasser - Question on the Last Updated Field:
> 
> * This is a dropdown that I feel like is probably pulling fields from the entity. Is it pulling all fields and that's why we want to clarification in the help text for "It must be a date field"?

Good point. That dropdown will only ever list "timestamp", "created" and "updated" fields. I wrote that help text really early on in development and didn't change it once the dropdown was limiting correctly the types of fields to allow. So in that case I would say "It must be a date field" is totally redundant and not helpful at all.

**Comment by dsasser** [comment]
@thejordanwood 

> Since the audience will be developers only, I'm going to assume they know what an entity type and bundle is. I'm open to any suggestions that you have.

Yes the configuration page is for developers so those terms would be familiar. It has made me think about what I would call/how I would describe an entity and entity bundle in a more non-technical way 🤔. I will let you know if I come up with anything.

**Comment by thejordanwood** [comment]
@dsasser @laflannery 

1. It sounds like the help text for the last updated field should be updated to:

     > **Last updated field**
     > Select the name of the field that will calculate when the entity was last updated. 

2. @dsasser I think it's okay to leave it as entity type and bundle for now. If we ever need to describe this to a non-technical audience, then we can update it at that time.

**Comment by thejordanwood** [comment]
@FranECross Putting final help text for the 'Expirable Content types' screen here for clarity. I had no changes to the 'Structure' screen.

@dsasser @laflannery I think we're good on this, but let me know if ya'll have any final thoughts. 

> **Entity type**
> Select the entity type to add content that can expire.
> 
> **Entity bundle**
> Select the bundle of the entity type.
> 
> **Last updated field**
> Select the name of the field that will calculate when the entity was last updated.
> 
> **Days before expiration**
> Enter the number of days before the entity will expire. This will be the number of days after the entity was created or last updated.
> 
> **Days to notify before expiration**
> Enter the number of days to notify an editor before an entity expires.

**Comment by laflannery** [comment]
This works for me!

**Comment by FranECross** [comment]
Thank you, @thejordanwood and @laflannery !!
