### ISSUE TITLE
Remove inline entity form (IEF) from Vet Center services

### ISSUE THREAD

**Issue by davidmpickett** [department-of-veterans-affairs/va.gov-cms#17708]
### User Story or Problem Statement

Currently Vet Center Facility Services are created and edited through an IEF interface on the Vet Center  content type. This means they circumvent some standard aspects of the VA.gov Drupal CMS like workflow and revision messages.  This can lead to incomplete content being accidentally published to Veterans.

### Affected users and stakeholders

* Veteran pain point: risk associated with seeing draft services
* Editor pain point: need for draft content to stay draft until published

<link to any existing research or data supporting this>

**Comment by davidmpickett** [comment]
@jilladams @Agile6MSkinner @mmiddaugh FYI that I just cleaned up the tickets in this epic. Closed some as not needed. Marked other that are defect reports that should be resolved by our planned work as Blocked.

**Comment by davidmpickett** [comment]
@Agile6MSkinner @dsasser 

My high-level notes on the tickets in this epic:

- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18003
  - The main chunk of engineering work remaining to resolve the defect
  - This is no longer blocked. The technical pre-requisites are complete and the Change Management work just blocks merging the PR, not starting the ticket.
  - I know Daniel had questions for Christian on the exact technical approach. Not sure how much of that needs to happen in refinement vs once it it in sprint.
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17840
  - Change Management tickets are a ongoing point of friction due to lack of dedicated resources for training and documentation. Technically up to Michael to consult with Jill and Michelle on, but I am willing to lend a hand with drafting/ revising content is needed.
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17674
  - Not technically required to fix defect, but would preserve some of the existing UX that will otherwise be lost and would set a model that we want to use on other products.
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18321
  - Tiny issue that has limited impact
- These three tickets are defect reports that initiated this work. They should all be resolved by 18003. I think you could safely close these all since the work to fix them is ticketed, but historically we would wait until after the fix merges and close all the defect reports after prod verification.
  - https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15125
  - https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15124
  - https://github.com/department-of-veterans-affairs/va.gov-cms/issues/5981
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/7818
  - This epic is only tangentially related to this work. Don't know that it needs to be listed under this epic any more. The only action item is after 17674 is resolved to revisit 7818. But that could be noted on 17674

**Comment by davidmpickett** [comment]
Just dug up one small ticket that should be a fast follow https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16362

This was another of the tickets that originally signaled the IEF problem to us. It's a FE ticket that is blocked by this Drupal work but will technically be a small) separate fix

**Comment by Agile6MSkinner** [comment]
That last straggler ticket is moved to the ongoing VetCenter epic and this Q3 work is done. Closing.
