### ISSUE TITLE
"Schedule an appointment online" line on VBA Facility Services should point to VERA

### ISSUE THREAD

**Issue by davidmpickett** [department-of-veterans-affairs/va.gov-cms#17710]
## User Story or Problem Statement
The "Schedule an appointment online" line on VBA Facility Services currently points to the VAMC scheduling page instead of VERA. (Top tasks are working correctly.)

## Description or Additional Context 
![Screenshot 2024-04-02 at 7 11 49 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/bbd83ed6-bbb1-48ab-8baa-f3eea627c9d9)

## Steps for repro

- Connect to SOCKS
- Go to [Cleveland RO](https://web-xptmfsnjoodldn85nzgkrgljqtfbz24b.ci.cms.va.gov/cleveland-va-regional-benefit-office/locations/cleveland-va-regional-benefit-office/#veteran-benefits) on Tugboat
- Scroll down to Veteran benefits
- Open the Home loans accordion
- Click the Schedule an appointment online link
- See that you go to VAMC scheduling page

## Steps for implementation
Add a conditional: if it's a VBA service point to VERA, if it's a VAMC service, point to VAMC scheduling page

## Acceptance Criteria
- [x] The "Schedule an appointment online" link on VBA facility services points to https://va.my.site.com/VAVERA/s/
- [x] VAMC appointment links are not negatively affected

**Comment by eselkin** [comment]
If you branch off `VACMS-17632-Non-Clinical-Services-No-Card` There's a typeOfService parameter now on service_location.drupal.liquid

**Comment by jilladams** [comment]
Updated to ready for review, since PR is merged.

**Comment by davidmpickett** [comment]
Doing a Content Release on SL Tugboat so this can be verified

**Comment by davidmpickett** [comment]
Confirmed on Tugboat that the link is correct. 

Want to note that the Design System Team changed the external link guidance since we first designed and built this. Right now both this link and the "make an appointment" link at the top of VBA open in a new tab, but we might need a new ticket to remove that behavior to match the new guidance. Thoughts? @thejordanwood @laflannery

**Comment by davidmpickett** [comment]
Thanks. I am closing this issue as complete since it met the criteria and have stubbed a follow up issue https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18004
