### ISSUE TITLE
Conduct VA Regional Office editor-facing research session

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#17713]
### User story
**AS A** researcher
**I WANT** to conduct research sessions with participants
**SO THAT** we can get feedback on the VBA Regional Office editor experience

**Guidelines**
- [Moderator guidelines](https://depo-platform-documentation.scrollhelp.site/research-design/conducting-research-sessions)
  - [Research Safety guidelines](https://depo-platform-documentation.scrollhelp.site/research-design/research-safety-and-emergency-exit-strategies) 
- [Notetaker guidelines](https://depo-platform-documentation.scrollhelp.site/research-design/notetaker-guidelines)
    - For Editor-facing research, recruit a member of the product team to take notes
- [Observer guidelines](https://depo-platform-documentation.scrollhelp.site/research-design/observer-guidelines)

**Recruitment Trackers**
- Editor-Facing research should track participants in the [VA.gov CMS UX research base](link TBD from CMS Platform team)

**No-shows and rescheduling**
- If a participant doesn't show up at the scheduled start time, they should be contacted
   - In Editor-facing research, the Moderator should contact the participant through email or Microsoft Teams
- If the participant hasn't shown up within 15 minutes of the start, consider it a no-show
  - See if the participant can reschedule for a different available slot 
  
## Acceptance Criteria

**Before each session**
- [ ] Moderator(s), Notetaker(s), & Observer(s) reviewed guidelines for their role(s)
- [ ] Moderator completes session-specific [prep tasks](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17155)

**After every session**
- [ ] Observers and Notetakers share their notes with Research Lead
- [ ] Researcher debriefs (i.e., into note-taking spreadsheet/Mural)
- [ ] Session recording and transcript downloaded from Zoom
- [ ] Researcher reviews notes taken by observers 

**After ALL sessions have been completed**
- [ ] All notes stored in the research folder on github
  - [ ] Notes documents for cancelled/no-show sessions have been deleted
  - [ ] Prep hand-off for subsequent researcher(s)

## Resources
[Research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/regional-offices/research/2024-01-editor-facing/research-plan.md) 
[Conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/regional-offices/research/2024-01-editor-facing/conversation-guide.md)
[Notetaking Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1707332466795/09bc172b8554e12831c422ca893d65a63745f05c?sender=u3f35bedf61955cb051f44770) 
[Sharepoint UX Folder](https://dvagov.sharepoint.com/:f:/s/SitewideFacilitiesTeam/ErvUu43stltFi3flMKfefQ8BS3oRgyfZ58R4yrto0gOaYw?email=Jordan.Wood1%40va.gov&e=ApJhKd), specific to this study

**Comment by thejordanwood** [comment]
@davidmpickett Sounds good!

**Comment by davidmpickett** [comment]
Update: @aklausmeier told us that the participant has had other priorities come up and may not be able to complete this session during this sprint

**Comment by davidmpickett** [comment]
@jilladams I am removing Sprint 1 from this ticket and moving it back into Ready. The participant was unable to schedule the session. This was an injection rather than part of the Sprint plan. We can keep this ticket in our pocket for any other opportunity that pops up.

**Comment by davidmpickett** [comment]
Moving to Blocked since we don't have any participants lined up

**Comment by aklausmeier** [comment]
closing, no longer a prioritized effort
