### ISSUE TITLE
Fix automated security update PRs 

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#1771]
**AC**

- [ ] Security updates create PRs automatically by dependabot

Implementation
- [ ] See if yaml config removal will fix this (bandaid)

Timebox to an hour to see if it helps, if not then proceed to #1372.

**Comment by indytechcook** [comment]
Deleting the config file and manually configuring in the UI fo dependable did create new PR's for cms-test.  These are more then just security updates though.

* https://github.com/department-of-veterans-affairs/va.gov-cms-test/pulls
* 
![Dependabot](https://user-images.githubusercontent.com/121603/82221885-91901a00-98ee-11ea-9c42-a2514517382d.png)

**Comment by indytechcook** [comment]
Dependabot breaks when "security" is check in the UI.

**Comment by indytechcook** [comment]
We have issues being created now so I'm closing this and pushing off on #1372 to fix the vets-website tags not being in packagist.
