### ISSUE TITLE
Fix PDF audit view to correctly show all PDF usage data

### ISSUE THREAD

**Issue by edmund-dunn** [department-of-veterans-affairs/va.gov-cms#17718]
## User Story or Problem Statement
The [PDF audit](https://prod.cms.va.gov/admin/content/media/pdfs) is not correctly showing PDFs that are in paragraphs. 

## User problems
There are two main user problems: 
1. The editor workflow for uploading a PDF is disjointed; they are two paths provided, one of which is not connected to their new-post workflow. 
2. The editor is unable to see which post the pdf is attached to and therefore is unable to determine if it is re-useable or ready to be archived.

## Assumptions
- the editor uploads a pdf and never comes back to archive
- pdfs uploaded are used for short-term event notifications and therefore should be archived accordingly
- global pdfs are being re-uploaded many times as the editor is unaware that it is available for use in the system
- the upload > pdf option outside of the new-post workflow is disconnected and could be creating unnecessary duplicates in the system

## Description or Additional Context 
Use the contrib module: https://www.drupal.org/project/entity_usage_addons

Patched: https://www.drupal.org/project/entity_usage_addons/issues/3000184#comment-15533449
## Acceptance Criteria
- [ ] Fix view to correctly show all usage of PDFs, including paragraphs. 
- [x] Requires design review
- [x] Requires accessibility review

**Comment by edmund-dunn** [comment]
@gracekretschmer-metrostar @MDomngz FYSA

**Comment by MDomngz** [comment]
## UX Artifacts
User journey - 
https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1712587869604/fead5bc2ac0915af1ada1f01053f68dfe403b90e?wid=0-1712590844554
![PDF Audit_17718_2024-04-08_15-42-12](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/156954219/0f7e39e4-5c9d-4627-a601-529137b7d3b3)

**Comment by gracekretschmer-metrostar** [comment]
@edmund-dunn has this been completed?
