### ISSUE TITLE
Content model?

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#17733]
Stub for the belief that we'll probably need content modeling to go along with IEF work.

**Comment by davidmpickett** [comment]
Closing as not needed. We're not fundamentally altering any content entities. The only new addition is [the View](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18003) and Jordan's design probably already gives Christian everything he needs for that. If needed, I might just add some points to that ticket for my support
