### ISSUE TITLE
[Resources & Support] [Analytics] Analyze Medallia qualitative survey data for Resources & Support

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-cms#17730]
Status:
**[2024-07-18] [Fran]** Messaged UX folks asking who will be taking on this ticket.
**[2024-04-04]**  Carved off Resources & Support into its own ticket

## Description
Pull current  Medalia data and analyze in order to understand user feedback, which will be used to determine future changes or enhancements to Resources & Support.

### User story
**AS A** PO/PM of the Public Websites team
**I WANT** to understand current user feedback on the products in the Public Websites portfolio
**SO THAT** we can consider if there are any that we should try to work

When writing ACs and estimating, check how many rows are present in remaining data.

### Notes / Background

Qualitative Medallia export was already requested in [this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/53598), which was closed (executed) on 3/1/23. 

## Acceptance criteria

- [ ] Pull more current data for the analysis
Data from Resources & Support is reviewed, analyzed, summarized into a Portfolio spreadsheet, and if more than a spreadsheet cell is needed to summarize, then also a quick summary doc.
- [ ] Discuss findings with Fran, Michelle M, Michael S, and Jill A.

**Comment by FranECross** [comment]
@aklausmeier @davidmpickett @thejordanwood Are the Medalia tickets such as this for UXers to analyze, or is it PO/PM/UX to analyze? Should they actually be in Next Refinement? Thanks!

**Comment by aklausmeier** [comment]
Medallia qualitative synthesis and reporting is a UX research activity. 

Medallia quant / CSAT can be either.

**Comment by aklausmeier** [comment]
Met with Randi Hecht. R&S's qualitative survey is continuously monitored by CAIA and summarized in their [content product folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsa/teams/sitewide-content/unauthenticated-content-outcomes-and-metrics/monthly-experience-ratings). Closing ticket to prevent duplicate work.
