### ISSUE TITLE
PW: [EPIC] Migrate off of font-awesome for iconography; deprecation of Font Awesome 

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-cms#17738]
## Description
Font Awesome will be deprecated. 
**Goal:** Stop using font awesome prior to June 19 deadline. 
Narrative: https://dsva.slack.com/archives/C06V7AAFVH7/p1715952465877389

va-icon adoption is optional. 

### User story

**AS A** PO/PM for products/features/applications managed by the Public Websites team
**I WANT** our features/products/applicates migrated off of Font Awesome (and onto va-icon where appropriate)
**SO THAT** when the deprecation of Font Awesome takes place, there won't be degraded Veteran-facing experiences in VA.gov.

## Acceptance criteria

- AC will be in individual tickets

**Comment by jilladams** [comment]
@FranECross I realized re: planning: 
* May 8 is current deadline for this icon cutover
* We have 19 points of work to do to hit that
* Sprint 2 ends on April 30. I think we're going to have to rethink priorities on FE for next sprint, to get that together.

**Comment by jilladams** [comment]
Renaming this epic, since the actual mandate is to stop using font-awesome, and from DST perspective, va-icon is just the easy path to do so but adoption is not required (https://dsva.slack.com/archives/C06V7AAFVH7/p1715952465877389)
