### ISSUE TITLE
[SPIKE] Discover where in Public Websites managed products/features/apps we need to accommodate migration onto va-icon

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-cms#17744]
## Description
This spike is to discover and list out which features/apps/products will be affected and need work done in order to accommodate the migration to va-icon, and deprecation of  Font  Awesome.

### User story

**AS A** PO/PM of Public Website managed apps/features/products
**I WANT** to understand the scope of work necessary to migrate to va-icon and accommodate the deprecation of Font Awesome
**SO THAT** I can prioritize the work and meet the (tentative) deadline of end of May 2024

### Artifacts
- [Mural ](https://app.mural.co/t/adhoccorporateworkspace2583/m/adhoccorporateworkspace2583/1678830068825/553b0ef0eb59ba6e26ad03692dc255f43c852737?invited=true&sender=u71e5a9ded413bfa79dd23932)with audit of Font Awesome icons - not sure if this is helpful?

## Acceptance criteria

- [x] List the  PW features/apps/products that will be affected by migration to va-icon and deprecation of Font Awesome
- [x] Create the ticket(s) necessary to do the work, or list the work needed and notify @FranECross to create the tickets.

**Comment by randimays** [comment]
Pulling in as Stretch on 4/11

**Comment by randimays** [comment]
Here's our list of places where we need to make some changes. I'll start creating tickets for these now.

# Applications Needing Updates

🟦 Currently using Font Awesome (needs conversion to va-icon by end of May)
🟧  Not using Font Awesome, but can be converted to va-icon
🟥  Not using Font Awesome, and not able to be converted to va-icon
🟫 Convert to plain SVG

## Find Forms
🟦  https://github.com/department-of-veterans-affairs/vets-website/blob/17621d7d0b4c4a3df774bd3a742aeda72cdae797/src/applications/find-forms/components/SearchResult.jsx#L241
🟦  https://github.com/department-of-veterans-affairs/vets-website/blob/17621d7d0b4c4a3df774bd3a742aeda72cdae797/src/applications/find-forms/containers/SearchResults.jsx#L282
🟦  https://github.com/department-of-veterans-affairs/content-build/blob/267e8c01b81d33570a2d97cf9f71e93b23f996fb/src/site/layouts/va_form.drupal.liquid#L94
🟦  https://github.com/department-of-veterans-affairs/content-build/blob/267e8c01b81d33570a2d97cf9f71e93b23f996fb/src/site/layouts/va_form.drupal.liquid#L155

## Landing Pages (e.g. /service-member-benefits)
🟧  https://github.com/department-of-veterans-affairs/content-build/blob/267e8c01b81d33570a2d97cf9f71e93b23f996fb/src/site/layouts/landing_page.drupal.liquid#L11
🟦  https://github.com/department-of-veterans-affairs/content-build/blob/267e8c01b81d33570a2d97cf9f71e93b23f996fb/src/site/layouts/landing_page.drupal.liquid#L178
🟦  https://github.com/department-of-veterans-affairs/content-build/blob/267e8c01b81d33570a2d97cf9f71e93b23f996fb/src/site/layouts/landing_page.drupal.liquid#L202
🟦  https://github.com/department-of-veterans-affairs/content-build/blob/267e8c01b81d33570a2d97cf9f71e93b23f996fb/src/site/layouts/landing_page.drupal.liquid#L214
🟦  https://github.com/department-of-veterans-affairs/content-build/blob/267e8c01b81d33570a2d97cf9f71e93b23f996fb/src/site/layouts/landing_page.drupal.liquid#L226

## Resources and Support
🟦  https://github.com/department-of-veterans-affairs/vets-website/blob/17621d7d0b4c4a3df774bd3a742aeda72cdae797/src/applications/resources-and-support/components/SearchBar.jsx#L128
🟦  https://github.com/department-of-veterans-affairs/vets-website/blob/17621d7d0b4c4a3df774bd3a742aeda72cdae797/src/applications/resources-and-support/components/SearchBar.jsx#L135
🟦  https://github.com/department-of-veterans-affairs/content-build/blob/267e8c01b81d33570a2d97cf9f71e93b23f996fb/src/site/components/browse-by-audience.drupal.liquid#L33
🟦  https://github.com/department-of-veterans-affairs/content-build/blob/267e8c01b81d33570a2d97cf9f71e93b23f996fb/src/site/paragraphs/lists_of_links.drupal.liquid#L26
🟦  https://github.com/department-of-veterans-affairs/content-build/blob/267e8c01b81d33570a2d97cf9f71e93b23f996fb/src/site/layouts/media_list_images.drupal.liquid#L82

## Search
🟦 https://github.com/department-of-veterans-affairs/vets-website/blob/17621d7d0b4c4a3df774bd3a742aeda72cdae797/src/applications/search/containers/SearchApp.jsx#L386

## Sitewide Alerts
🟦  https://github.com/department-of-veterans-affairs/vets-website/blob/17621d7d0b4c4a3df774bd3a742aeda72cdae797/src/platform/site-wide/alerts/MobileAppCallout.jsx#L39
🟦  https://github.com/department-of-veterans-affairs/vets-website/blob/17621d7d0b4c4a3df774bd3a742aeda72cdae797/src/platform/site-wide/alerts/MobileAppCallout.jsx#L54

## Sidebars (left and right)
🟦  https://github.com/department-of-veterans-affairs/content-build/blob/267e8c01b81d33570a2d97cf9f71e93b23f996fb/src/site/components/merger-social-sco.html#L52
🟦  https://github.com/department-of-veterans-affairs/content-build/blob/267e8c01b81d33570a2d97cf9f71e93b23f996fb/src/site/components/merger-social-sco.html#L54
🟧  https://github.com/department-of-veterans-affairs/content-build/blob/267e8c01b81d33570a2d97cf9f71e93b23f996fb/src/site/components/navigation-sidebar.html#L30
🟧  https://github.com/department-of-veterans-affairs/content-build/blob/267e8c01b81d33570a2d97cf9f71e93b23f996fb/src/site/navigation/sidebar_nav.drupal.liquid#L9
🟦  https://github.com/department-of-veterans-affairs/content-build/blob/267e8c01b81d33570a2d97cf9f71e93b23f996fb/src/site/includes/social-share.drupal.liquid#L21
🟦  https://github.com/department-of-veterans-affairs/content-build/blob/267e8c01b81d33570a2d97cf9f71e93b23f996fb/src/site/includes/social-share.drupal.liquid#L30

## Homepage
🟦  https://github.com/department-of-veterans-affairs/content-build/blob/267e8c01b81d33570a2d97cf9f71e93b23f996fb/src/site/includes/common-tasks.drupal.liquid#L26
🟧  https://github.com/department-of-veterans-affairs/content-build/blob/267e8c01b81d33570a2d97cf9f71e93b23f996fb/src/site/layouts/home.html#L15
🟧  https://github.com/department-of-veterans-affairs/content-build/blob/267e8c01b81d33570a2d97cf9f71e93b23f996fb/src/site/layouts/home.html#L42
🟦  https://github.com/department-of-veterans-affairs/content-build/blob/267e8c01b81d33570a2d97cf9f71e93b23f996fb/src/site/layouts/home.html#L58
🟦   https://github.com/department-of-veterans-affairs/content-build/blob/267e8c01b81d33570a2d97cf9f71e93b23f996fb/src/site/layouts/home.html#L79
🟧  https://github.com/department-of-veterans-affairs/content-build/blob/267e8c01b81d33570a2d97cf9f71e93b23f996fb/src/site/includes/homepage-benefits.drupal.liquid#L17

## Campaign Landing Pages
🟦  https://github.com/department-of-veterans-affairs/content-build/blob/267e8c01b81d33570a2d97cf9f71e93b23f996fb/src/site/layouts/campaign_landing_page.drupal.liquid#L76
🟦  https://github.com/department-of-veterans-affairs/content-build/blob/267e8c01b81d33570a2d97cf9f71e93b23f996fb/src/site/layouts/campaign_landing_page.drupal.liquid#L81
🟦  https://github.com/department-of-veterans-affairs/content-build/blob/267e8c01b81d33570a2d97cf9f71e93b23f996fb/src/site/layouts/campaign_landing_page.drupal.liquid#L539
🟦  https://github.com/department-of-veterans-affairs/content-build/blob/267e8c01b81d33570a2d97cf9f71e93b23f996fb/src/site/layouts/campaign_landing_page.drupal.liquid#L556
🟦  https://github.com/department-of-veterans-affairs/content-build/blob/267e8c01b81d33570a2d97cf9f71e93b23f996fb/src/site/layouts/campaign_landing_page.drupal.liquid#L573
🟦  https://github.com/department-of-veterans-affairs/content-build/blob/267e8c01b81d33570a2d97cf9f71e93b23f996fb/src/site/layouts/campaign_landing_page.drupal.liquid#L590
🟦  https://github.com/department-of-veterans-affairs/content-build/blob/267e8c01b81d33570a2d97cf9f71e93b23f996fb/src/site/layouts/campaign_landing_page.drupal.liquid#L607
🟦  https://github.com/department-of-veterans-affairs/content-build/blob/267e8c01b81d33570a2d97cf9f71e93b23f996fb/src/site/layouts/campaign_landing_page.drupal.liquid#L624
🟧  https://github.com/department-of-veterans-affairs/content-build/blob/267e8c01b81d33570a2d97cf9f71e93b23f996fb/src/site/layouts/campaign_landing_page.drupal.liquid#L651

## Events
🟦  https://github.com/department-of-veterans-affairs/content-build/blob/267e8c01b81d33570a2d97cf9f71e93b23f996fb/src/site/layouts/event.drupal.liquid#L58

## Education SCO (e.g. /school-administrators)
🟧 https://github.com/department-of-veterans-affairs/content-build/blob/267e8c01b81d33570a2d97cf9f71e93b23f996fb/src/site/includes/education-sco.html#L15

## Test file in content-build
🟦  https://github.com/department-of-veterans-affairs/content-build/blob/267e8c01b81d33570a2d97cf9f71e93b23f996fb/src/site/layouts/liquid_template_axe_check_smoke_test.drupal.liquid#L55
🟦  https://github.com/department-of-veterans-affairs/content-build/blob/267e8c01b81d33570a2d97cf9f71e93b23f996fb/src/site/layouts/liquid_template_axe_check_smoke_test.drupal.liquid#L78
🟦  https://github.com/department-of-veterans-affairs/content-build/blob/267e8c01b81d33570a2d97cf9f71e93b23f996fb/src/site/layouts/liquid_template_axe_check_smoke_test.drupal.liquid#L81
🟦  https://github.com/department-of-veterans-affairs/content-build/blob/267e8c01b81d33570a2d97cf9f71e93b23f996fb/src/site/layouts/liquid_template_axe_check_smoke_test.drupal.liquid#L91
🟦  https://github.com/department-of-veterans-affairs/content-build/blob/267e8c01b81d33570a2d97cf9f71e93b23f996fb/src/site/layouts/liquid_template_axe_check_smoke_test.drupal.liquid#L94
🟦  https://github.com/department-of-veterans-affairs/content-build/blob/267e8c01b81d33570a2d97cf9f71e93b23f996fb/src/site/layouts/liquid_template_axe_check_smoke_test.drupal.liquid#L104
🟦  https://github.com/department-of-veterans-affairs/content-build/blob/267e8c01b81d33570a2d97cf9f71e93b23f996fb/src/site/layouts/liquid_template_axe_check_smoke_test.drupal.liquid#L107
🟦  https://github.com/department-of-veterans-affairs/content-build/blob/267e8c01b81d33570a2d97cf9f71e93b23f996fb/src/site/layouts/liquid_template_axe_check_smoke_test.drupal.liquid#L115
🟦  https://github.com/department-of-veterans-affairs/content-build/blob/267e8c01b81d33570a2d97cf9f71e93b23f996fb/src/site/layouts/liquid_template_axe_check_smoke_test.drupal.liquid#L118
🟦  https://github.com/department-of-veterans-affairs/content-build/blob/267e8c01b81d33570a2d97cf9f71e93b23f996fb/src/site/layouts/liquid_template_axe_check_smoke_test.drupal.liquid#L127
🟦  https://github.com/department-of-veterans-affairs/content-build/blob/267e8c01b81d33570a2d97cf9f71e93b23f996fb/src/site/layouts/liquid_template_axe_check_smoke_test.drupal.liquid#L129
🟦  https://github.com/department-of-veterans-affairs/content-build/blob/267e8c01b81d33570a2d97cf9f71e93b23f996fb/src/site/layouts/liquid_template_axe_check_smoke_test.drupal.liquid#L156
🟦  https://github.com/department-of-veterans-affairs/content-build/blob/267e8c01b81d33570a2d97cf9f71e93b23f996fb/src/site/layouts/liquid_template_axe_check_smoke_test.drupal.liquid#L175
🟦  https://github.com/department-of-veterans-affairs/content-build/blob/267e8c01b81d33570a2d97cf9f71e93b23f996fb/src/site/layouts/liquid_template_axe_check_smoke_test.drupal.liquid#L191

## Outreach Materials
🟦  https://github.com/department-of-veterans-affairs/content-build/blob/267e8c01b81d33570a2d97cf9f71e93b23f996fb/src/site/layouts/publication_listing.drupal.liquid#L210
🟦  https://github.com/department-of-veterans-affairs/content-build/blob/267e8c01b81d33570a2d97cf9f71e93b23f996fb/src/site/layouts/publication_listing.drupal.liquid#L219
🟦  https://github.com/department-of-veterans-affairs/content-build/blob/267e8c01b81d33570a2d97cf9f71e93b23f996fb/src/site/layouts/publication_listing.drupal.liquid#L232
🟥  https://github.com/department-of-veterans-affairs/content-build/blob/267e8c01b81d33570a2d97cf9f71e93b23f996fb/src/site/layouts/publication_listing.drupal.liquid#L183

## Header/footer & injected header/footer
🟫  https://github.com/department-of-veterans-affairs/vets-website/blob/17621d7d0b4c4a3df774bd3a742aeda72cdae797/src/applications/search/components/SearchDropdown/SearchDropdownComponent.js#L793
🟫  https://github.com/department-of-veterans-affairs/vets-website/blob/17621d7d0b4c4a3df774bd3a742aeda72cdae797/src/platform/site-wide/header/components/LogoRow/index.js#L43
🟫  https://github.com/department-of-veterans-affairs/vets-website/blob/17621d7d0b4c4a3df774bd3a742aeda72cdae797/src/platform/site-wide/header/components/LogoRow/index.js#L48
🟫  https://github.com/department-of-veterans-affairs/vets-website/blob/830a706fb3d800db36156a1d54769dd41a9e57f8/src/platform/site-wide/header/components/MenuItemLevel1/index.js#L72
🟫  https://github.com/department-of-veterans-affairs/vets-website/blob/830a706fb3d800db36156a1d54769dd41a9e57f8/src/platform/site-wide/header/components/MenuItemLevel1/index.js#L77
🟫  https://github.com/department-of-veterans-affairs/vets-website/blob/830a706fb3d800db36156a1d54769dd41a9e57f8/src/platform/site-wide/header/components/MenuItemLevel2/index.js#L72
🟫  https://github.com/department-of-veterans-affairs/vets-website/blob/830a706fb3d800db36156a1d54769dd41a9e57f8/src/platform/site-wide/header/components/OfficialGovtWebsite/index.js#L34
🟫  https://github.com/department-of-veterans-affairs/vets-website/blob/830a706fb3d800db36156a1d54769dd41a9e57f8/src/platform/site-wide/header/components/Search/index.js#L199
🟫  https://github.com/department-of-veterans-affairs/vets-website/blob/830a706fb3d800db36156a1d54769dd41a9e57f8/src/platform/site-wide/header/components/SubMenu/index.js#L31
🟫  https://github.com/department-of-veterans-affairs/vets-website/blob/830a706fb3d800db36156a1d54769dd41a9e57f8/src/platform/site-wide/header/components/VeteranCrisisLine/index.js#L18
🟫  https://github.com/department-of-veterans-affairs/vets-website/blob/830a706fb3d800db36156a1d54769dd41a9e57f8/src/platform/site-wide/loading-button/LoadingButton.jsx#L13
🟫  https://github.com/department-of-veterans-affairs/vets-website/blob/830a706fb3d800db36156a1d54769dd41a9e57f8/src/platform/site-wide/user-nav/components/SearchMenu.jsx#L249
🟫  https://github.com/department-of-veterans-affairs/vets-website/blob/830a706fb3d800db36156a1d54769dd41a9e57f8/src/platform/site-wide/user-nav/components/SearchMenu.jsx#L294
🟫  https://github.com/department-of-veterans-affairs/vets-website/blob/830a706fb3d800db36156a1d54769dd41a9e57f8/src/platform/site-wide/user-nav/components/SignInProfileMenu.jsx#L9
🟫  https://github.com/department-of-veterans-affairs/vets-website/blob/830a706fb3d800db36156a1d54769dd41a9e57f8/src/platform/site-wide/va-footer/components/CrisisPanel.jsx#L17
🟫  https://github.com/department-of-veterans-affairs/vets-website/blob/830a706fb3d800db36156a1d54769dd41a9e57f8/src/platform/site-wide/va-footer/components/CrisisPanel.jsx#L33
🟫  https://github.com/department-of-veterans-affairs/vets-website/blob/830a706fb3d800db36156a1d54769dd41a9e57f8/src/platform/site-wide/va-footer/components/CrisisPanel.jsx#L45
🟫  https://github.com/department-of-veterans-affairs/vets-website/blob/830a706fb3d800db36156a1d54769dd41a9e57f8/src/platform/site-wide/va-footer/components/CrisisPanel.jsx#L54
🟫  https://github.com/department-of-veterans-affairs/vets-website/blob/830a706fb3d800db36156a1d54769dd41a9e57f8/src/platform/site-wide/va-footer/components/CrisisPanel.jsx#L66

**Comment by randimays** [comment]
Tickets created (@FranECross feel free to edit as needed!):

1. Find Forms: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17815
2. Landing Pages: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17816
3. Resources & Support: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17817
4. Sitewide Alerts: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17818
5. Sidebars: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17819
6. Homepage: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17820
7. Campaign Landing Pages: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17821
8. Events: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17822
9. Education SCO: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17823
10. Axe Check Smoke Test (Content-build): https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17824
11. Outreach Materials: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17825
12. Header/footer & injected header/footer: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17826

Epic: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17738

Closing this ticket as complete.

**Comment by FranECross** [comment]
Excellent, @randimays ! Thanks so much!
