### ISSUE TITLE
[Discharge Upgrade Wizard] Text, URL, and address corrections

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-cms#17765]
## Description

Several areas (incorrect mailing address and incorrect website URL) in the wizard have been identified as being incorrect (by Ashmore, Margarete P CIV OSD OUSD P-R (USA)).

Although we are currently updating the Discharge Upgrade Wizard to a subtask pattern, it's important to correct the items identified as being erroneous and get the changes released soon, so as to improve Veteran outcomes and experiences when they apply for a Discharge Upgrade.

### User story

**AS A** Veteran using the Discharge Upgrade Wizard VA.gov
**I WANT** information and websites to be correct so as to expedite by request for an upgrade
**SO THAT** my opinion of the Veteran's Administration, as well as VA.gov, are not eroded
**AND SO THAT** my discharge upgrade request can be processed expeditiously and routed to the correct departments/offices

## Acceptance criteria

**AC1: Text for Air Force Review Boards Agency Website and Portal is correct on the guidance screen**
**GIVEN**: I'm a Veteran using the Discharge Upgrade Wizard in VA.gov
**WHEN**: I land on the guidance screen, or encounter the name of this agency anywhere in the wizard
**THEN**: the name for the Air Force Review Boards Agency website is correctly displayed as "Air Force Review Boards Agency Website and Portal", and I'm not confused or misled by encountering an incorrect agency name of "Air Force Review Agency Portal"

**AC2:  The link to request their military personnel record is correct**
**GIVEN**: I'm a Veteran using the Discharge Upgrade Wizard in VA.gov
**WHEN**: I land on the guidance screen and see the information of where I can download the Application for Correction of Military Record
**THEN**: the information I see is:

Based on your answers, you need to complete an Application for Correction of Military Record (DD 149). You can download this form from the Air Force Review Boards Agency Website and Portal.

Get the form on the Air Force Review Boards Agency Website and Portal.

Note that the URL for link should be updated to: https://afrba-portal.cce.af.mil/

**AC3:  The address for the Air Force Review Boards Agency is correct**
**GIVEN**: I'm a Veteran using the Discharge Upgrade Wizard in VA.gov
**WHEN**: I land on the guidance screen, or need the physical address to the Air Force Discharge Review Board 
**THEN**: the address for the Air Force Review Board is correctly displayed as:

Air Force Discharge Review Board
3351 Celmers Lane
Joint Base Andrews, MD  20762-6435

_**Not**_ the current information of:
Air Force Review Boards Agency
SAF/MRBR
550-C Street West, Suite 40
Randolph AFB, TX 78150-4742

- [x] Code has been searched to ensure any other instances of the above corrections are also changed.
- [ ] Please notify the PW PM Fran Cross when released so she can notify stakeholders.

**Comment by chriskim2311** [comment]
@FranECross Can you have the stakeholder double check this page as well. https://www.va.gov/discharge-upgrade-instructions/request-dd214

Not sure if this page has correct information or not. This page is instructing to not send to the Discharge Board for the Air Force. Meaning that the current address listed here is the Review Boards address and the previous is the Discharge Review Address.

Essentially I am thinking the addresses are actually correct based on what we have here. But let me know if they indeed want them to change. 

Currently based on the code:

**Discharge Board Address:**
SAF/MRBR
550-C Street West, Suite 40
Randolph AFB, TX 78150-4742

**Review Board Address**
SAF/MRBR
3351 Celmers Lane
Joint Base Andrews NAF Washington 20762-6604

**Comment by chriskim2311** [comment]
@FranECross Thanks I will make the changes!

**Comment by chriskim2311** [comment]
@FranECross This is live on prod you can let the stakeholder know. Thanks!

**Comment by FranECross** [comment]
Thanks, @chriskim2311 ! I'll let them know today.

**Comment by gibbsjd** [comment]
> @FranECross Can you have the stakeholder double check this page as well. https://www.va.gov/discharge-upgrade-instructions/request-dd214.
> 
> * To get to this page you must select  **'I completed a prior period of service, but I did not receive discharge paperwork from that period.'** for the Prior Service question.
> 
> Not sure if this page has correct information or not. This page is instructing to not send to the Discharge Board for the Air Force. Meaning that the current address listed here is the Review Boards address and the previous is the Discharge Review Address.
> 
> Essentially I am thinking the addresses are actually correct based on what we have here. But let me know if they indeed want them to change.
> 
> Currently based on the code:
> 
> **Discharge Board Address:** SAF/MRBR 550-C Street West, Suite 40 Randolph AFB, TX 78150-4742
> 
> **Review Board Address** SAF/MRBR 3351 Celmers Lane Joint Base Andrews NAF Washington 20762-6604

Hello all, the City/State should be Joint Base Andrews, MD 20762-6435. As shown on the website: https://afrba-portal.cce.af.mil/#contact

**Comment by FranECross** [comment]
@gibbsjd I'm happy to have them check that page as well and will ask when I alert them of the other items going to prod. Thanks!

**Comment by FranECross** [comment]
@gibbsjd Thanks for the information! I'll create a new ticket to have the correction done.

**Comment by gibbsjd** [comment]
Is a new ticket required this was referencing the previous chain asking that the stakeholder double check this page as well. https://www.va.gov/discharge-upgrade-instructions/request-dd214.

**Comment by chriskim2311** [comment]
@gibbsjd @FranECross Thanks for the heads up. 

This was the initial ask for the Discharge Review Board: 
**Air Force Discharge Review Board
3351 Celmers Lane
Joint Base Andrews, MD 20762-6435**

This is what we will have after the change for Air Force Board for Correction of Military Records:
**Air Force Board for Correction of Military Records
SAF/MRBR
3351 Celmers Lane
Joint Base Andrews, MD 20762-6435**


I see in the contact page there is` SAF/MRBP (AFDRB)` for the Discharge Review Board should we add that as well?

And for the Air Force Board for Correction of Military Records should we change it to `SAF/MRBC (AFBCMR)`?

**Comment by gibbsjd** [comment]
@chriskim2311 yes we would like to mirror the actual website address label please.

**Comment by chriskim2311** [comment]
Thanks I'll work on it today

**Comment by chriskim2311** [comment]
@FranECross @gibbsjd The changes have been deployed to prod. Please let me know if you find any other discrepancies thanks!

**Comment by FranECross** [comment]
@chriskim2311 Thanks so much! 

@gibbsjd After you sign off, I'll send an email to the broader audience letting them know changes are in prod.

**Comment by gibbsjd** [comment]
@chriskim2311 The title for mailing address should read Air Force Review Boards Agency. Also, is there a way to add a link to their website: https://afrba-portal.cce.af.mil/#. Lastly, Get your military personnel record link is incorrect should be https://www.dpris.dod.mil/veteranaccess.html)](https://www.archives.gov/veterans/military-service-recor

**Comment by FranECross** [comment]
@gibbsjd Question... are you talking about the [/guidance page](https://www.va.gov/discharge-upgrade-instructions/guidance) when you reference the "Get your military record..." link being incorrect?

When I click the link you provided, it returns an error. Actually, when I click the link in the wizard, it also returns an error...

Both your link and the current link return this:

Error 404--Not Found
From RFC 2068 Hypertext Transfer Protocol -- HTTP/1.1:
10.4.5 404 Not Found
The server has not found anything matching the Request-URI. No indication is given of whether the condition is temporary or permanent.

If the server does not wish to make this information available to the client, the status code 403 (Forbidden) can be used instead. The 410 (Gone) status code SHOULD be used if the server knows, through some internally configurable mechanism, that an old resource is permanently unavailable and has no forwarding address.

**Comment by gibbsjd** [comment]
@FranECross I am unclear what you are asking my you call to make sure we are on the same page please  202-243-8437

**Comment by FranECross** [comment]
@gibbsjd Actually, you supplying the PDF is super helpful. We though you were requesting changes to the actual website wizard page, so were confused. We don't make the PDF alterations, though... only to the actual website wizard itself. I'll find out who to tag for the PDF updates and will keep you in the loop on that via email or Slack. I'll give you a ring with any other clarifications or questions!

**Comment by gibbsjd** [comment]
@FranECross I am new to this position I was under the impression wizard was the website. Am I mistaken?

**Comment by FranECross** [comment]
@gibbsjd You're correct, the wizard is the website, but the PDF is is a separate document accessed via a link in the wizard, and any PDFs/documents are provided by I believe the forms group and controlled/uploaded to a database by them. I'll need to find out who in that groups can make an update to the form and then ask them to do so.

**Comment by gibbsjd** [comment]
@FranECross the pdf document is really a screen shot of the website. As long as the website is reflecting correctly all will be corrected.

**Comment by FranECross** [comment]
@chriskim2311 Here are a couple of updates, and thanks in advance.

- Change Air Force Discharge Review Board to Air Force Review Boards Agency (on the guidance screen)
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/147188767/303374fa-005e-4e57-954c-38130aebc0c8)

- On any page in the wizard, change the "Get your military record..." link to: https://www.archives.gov/veterans/military-service-records.

- For this request:  is there a way to add a link to their website: https://afrba-portal.cce.af.mil/#. , I'll need to engage our UX person and possibility CAIA to provide placement and link text and will create another ticket for that.

- Regarding any PDFs that have the incorrect "Get your military records...' link that are linked from the wizard, I'll contact the forms folks and ask that they update it, and will cc you, Joshua @gibbsjd  (Also, thanks so much for reviewing and providing corrections!)

**Comment by gibbsjd** [comment]
@chriskim2311 may with website (https://www.va.gov/discharge-upgrade-instructions/guidance) for the Air Force also be updated to indicate the "DoD Form 293 may will filed online or may be downloaded"?
![Discharge](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/167910779/e125523f-ed6f-465d-a392-5c0e7b6a8b74)

**Comment by jilladams** [comment]
From planning: 
* Randi will help get this closed out
* Changes go into both live DUW and dev branch for DUW update
* @FranECross is coordinating re: stakeholder feedback, and any new changes will go into new tickets.

**Comment by randimays** [comment]
Successfully validated the text changes in prod. @FranECross we are good to notify stakeholders. 👍🏻  Closing!

**Comment by FranECross** [comment]
Thank you, @randimays !!

@gibbsjd A quick status for you. The original engineer working on this ticket is OOO the month of May, and in the interest of getting the existing alterations released and to keep the code from becoming stale, we've released what was altered so far. I'm going to review your notes and requests and will create a new ticket for anything not yet implemented to review with you, and then I can get it into our next sprint. Thanks in advance for your patience while we work through the updates! cc @randimays @jilladams

**Comment by gibbsjd** [comment]
Good morning,

Wanted to follow-up on the discussion on starting a new ticket to complete all requested adjustments. Any update is greatly appreciated.

Respectfully,
***@***.***
Joshua Gibbs
Benefits Executive Committee Coordinator
Office: 202-461-5988 Cell: 202-243-8437
Web https://www.va.gov/service-member-benefits/
Email ***@***.******@***.***>
[Title: LinkedIn - Description: image of LinkedIn icon]<http://linkedin.com/>


From: Fran Cross ***@***.***>
Sent: Thursday, May 2, 2024 5:55 PM
To: department-of-veterans-affairs/va.gov-cms ***@***.***>
Cc: GIBBS, JOSHUA ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [department-of-veterans-affairs/va.gov-cms] [Discharge Upgrade Wizard] Text, URL, and address corrections (Issue #17765)


Thank you, @randimays<https://github.com/randimays> !!

@gibbsjd<https://github.com/gibbsjd> A quick status for you. The original engineer working on this ticket is OOO the month of May, and in the interest of getting the existing alterations released and to keep the code from becoming stale, we've released what was altered so far. I'm going to review your notes and requests and will create a new ticket for anything not yet implemented to review with you, and then I can get it into our next sprint. Thanks in advance for your patience while we work through the updates! cc @randimays<https://github.com/randimays> @jilladams<https://github.com/jilladams>

-

**Comment by FranECross** [comment]
++ @Jill Adams ***@***.***>

Hello, Joshua,

Apologies for the delay. I've been sporadically out of the office ill and
dealing with a family emergency, and the team has been heads down on design
system implementations with hard deadlines (however I should have apprised
you of the delay). I'll create a ticket today for the requested changes,
have you review for accuracy, and will ensure it's in our next sprint
(which starts on 5/29). I'll ask that this be one of the first tickets
implemented and released.

Best,

Fran

**Comment by FranECross** [comment]
> may with website (https://www.va.gov/discharge-upgrade-instructions/guidance) for the Air Force also be updated to indicate the "DoD Form 293 may will filed online or may be downloaded"? !

@gibbsjd Do you have the link to where a Veteran can go to fill out this form online? I couldn't find it by searching in VA.gov. Thanks.

**Comment by gibbsjd** [comment]
@FranECross the online submission is https://afrba-portal.cce.af.mil/#portal

**Comment by FranECross** [comment]
@gibbsjd Hello Joshua, Please see tickets below I created today. I'll keep you apprised of status, and I've also added to the Acceptance Criteria "Stakeholder review by Joshua Gibbs" so that we'll ensure accuracy prior to release. Thanks again for your patience during my delay in getting this started.

- Design/UX ticket to provide content and design for the information on any guidance screen telling the Veteran they can complete and submit the (DoD) Form 293 online. Ticket [here](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18154).
  -  I'll create a subsequent implementation ticket after Jordan provides the info. 
- Update the review board name, address, and add the website link; update the URL for Get your military record. Ticket [here]([Discharge Upgrade Wizard] Change the acronym, review board name, and address for the the Air Force #18155).
