### ISSUE TITLE
Discovery: Determine the use of the Lighthouse v0 key "FacilitiesDrupalCMS"

### ISSUE THREAD

**Issue by omahane** [department-of-veterans-affairs/va.gov-cms#17788]
## User Story or Problem Statement

As a developer, I need to know what use of the Facilities API is being made by any process using the consumer key labeled `FacilitiesDrupalCMS`. 

v0 is set to sunset this summer. Before then, we need to know which consumers are still on it and who needs to be informed. The `FacilitiesDrupalCMS` point of contact was listed as Ethan Teague.

# Background
https://trello.com/c/sf70Untx

Problem description. How might we _____________ ?

## Acceptance Criteria
- [ ] Testable_Outcome_X
- [ ] Testable_Outcome_Y
- [ ] Testable_Outcome_Z
- [ ] Requires Content Model Documentation
- [ ] Requires design review
- [ ] Requires KB article update

## Implementation steps
<optional>

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

**Comment by jilladams** [comment]
We worked this out in Slack: https://dsva.slack.com/archives/C02BTJTDFTN/p1711646732752519. 

And then we documented it here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/facility-pages/technical-documentation.md#vets-api--lighthouse-key--rate-limits

Point of contact for this API consumer has been updated to be Michelle: https://dsva.slack.com/archives/C02BTJTDFTN/p1712705228261859.

Closing.
