### ISSUE TITLE
Update Facilities monitors to add a trace retention policy for 401

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#17791]
## Description or Additional Context 
The following monitor is not retaining traces: [Warn: 401 errors Facilities source app on Vets-API requests](https://vagov.ddog-gov.com/monitors/174791?from_ts=1712674031000&to_ts=1712675231000&event_id=7523107093525543878&source=monitor_notif)

So when it alarms, we don't have enough data retained to understand root cause or follow errors through to determine root cause.

We need to add a trace retention policy for 401 to see the traces of these errors.

## Acceptance Criteria
- [ ] 401 monitor retains logs for triage

**Comment by eselkin** [comment]
I'm thinking this [monitor](https://vagov.ddog-gov.com/monitors/174791) really isn't a good monitor and doesn't tell us something about our products exactly. 

It's a vets-api api_rack_request metric. Rack requests to vets-api are requests coming into vets-api from users. Therefore these 401s on rack_requests are only for users. And, the users having 401 errors are for authenticated routes. We don't have any authenticated routes. I'm not sure how `source_app:facilities` is even getting 401 errors unless they are errors that are bubbling up from other requests they are making to authenticated routes. 

The source_app on the metrics is `facilities` and may not actually be our facilities_api but referring to something else. The source_app names come from `lib/statsd_middleware.rb` in vets-api. And facilities may be referring to `lighthouse/facilities` and not our `facilities_api` which isn't even listed in `statsd_middleware.rb`

In looking at traces. 401s do exist in the traces but not on any route related to our `/facilities_api/va` or `facilities_api/ccp` so it's likely that the surfaced on `source_app:facilities` is not our app at all.

I propose to remove the monitor.

**Comment by eselkin** [comment]
Here are all 401s on vets-api in traces (they do get captured in traces)
<img width="1574" alt="Screenshot 2024-04-09 at 1 17 42 PM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5606931/62d9772e-a07c-46f7-9154-5b9e84f38306">

Here are NO 401s on vets-api in traces on our routes:
<img width="1563" alt="Screenshot 2024-04-09 at 1 18 42 PM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5606931/899f6019-a13d-4131-95f8-e1090ea25d4e">

**Comment by Agile6MSkinner** [comment]
This DataDog monitor has been removed. Replaces with another one which we need to look at.

**Comment by jilladams** [comment]
Per internets: The 401 error code, also known as the "Unauthorized" status code, means that the server has not been able to identify the user because they do not have the correct authentication credentials or have provided invalid ones. 

I think we can cover any fall out from this in https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18179, which is queued for refinement.
