### ISSUE TITLE
New Vet Center Facility: St. Cloud Vet Center Outstation

### ISSUE THREAD

**Issue by omahane** [department-of-veterans-affairs/va.gov-cms#17795]
## Description
Use this runbook if: a Vet Centers, Mobile Vet Centers, Vet Center Outstations is flagged as New, OR if an existing facility is flagged as New with a new Facility API ID. (This may happen  if a Vet Center moves districts, or a Mobile Vet Center is reallocated to a different Vet Center.)

## Intake
- [x] What triggered this runbook? (Flag in CMS, Help desk ticket, Product team, VHA Digital Media)
Trigger: @mmiddaugh provided a heads up on [Slack](https://dsva.slack.com/archives/C02730UEZPS/p1712672364039079)

- [x] Link to associated help desk ticket (if applicable)
Help desk ticket: [VAHELP-7324](https://va-gov.atlassian.net/browse/VAHELP-7324)

- [x] Name of submitter (if applicable)
Submitter: <insert_name>

- [x] If the submitter is an editor, send them links to any relevate KB articles for the Vet Center product.
KB articles: <insert_kb_article_links>

- [x] Link to facility in production:
Facility CMS link: [St. Cloud Vet Center Outstation](https://prod.cms.va.gov/anoka-vet-center/st-cloud-vet-center-outstation)
Facility API ID: vc_04391OS

## Link to URL ticket
#18013

### New Vet Center
[@TODO: KB ARTICLE FOR ADDING VET CENTERS - SEE runbook-vamc-facility-new]

#### CMS help desk steps
**Note: If the help desk is waiting on information from the facility staff or editor, add the `Awaiting editor` flag to the facility** with a log message that includes a link to this ticket. Remove the flag when the ticket is ready to be worked by the Facilities team. **Be sure to preserve the current moderation state of the node when adding or removing the flag.**

**If a Outstation:**
- [x] Confirm what Vet Center it belongs to, and set the "Main Vet Center location" field. The parent location may be derived by the Facility ID.
- [x] Contact the Vet Center editor to remind them to (1) add a photo of the Outstation and then they can publish when ready
- [ ] Consider: Following up with Barb/RCS Central office to be sure that she's aware that the Outstation is in-flight

**Drupal Admin steps**
- [x] 8. Bulk publish the nodes and facility.
- [x] 9. Edit the facility node: remove the `New facility` and `Awaiting editor` flags, save the node.
- [x] 10. Let Help desk know this has been done.

#### CMS Help desk (wrap up)
- [x] 11. Upgrade the Vet Center Director and Outreach Specialist accounts to the publisher role for that Vet Center.
- [x] 12. Notify editor and any other stakeholders.

[VAHELP-7324]: https://va-gov.atlassian.net/browse/VAHELP-7324?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by mmiddaugh** [comment]
<img width="1827" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOWRUQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9a3851aeca43661e15174024ea5c870142dadd87/image.png" alt="image.png" />

<img width="458" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOWhUQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b644078980a5dd049adbbb866e00714076af7db3/image.png" alt="image.png" />


@omahane the corrected version is now available - it's free range, currently. I assume that it will get wrangled into a District when the section is assigned?

**Comment by omahane** [comment]
I just moved it to the right section: https://prod.cms.va.gov/anoka-vet-center/st-cloud-vet-center-outstation

**Comment by omahane** [comment]
@ian-sears I have moved the facility to the correct section, could you follow up with an editor about having them add a photo?

**Comment by mmiddaugh** [comment]
@omahane the photo is added and the editors have been directed to publish. 
During Vet Center office hours this morning, we noticed that although the section has been assigned to the correct version of the facility, a few odd things are happening
- the archived (incorrect) St Cloud location is now free-range
- the valid Outstation is not included in the [content list for Anoka](https://prod.cms.va.gov/admin/content?title=anoka&type=All&moderation_state=All&owner=All) although the invalid/archived versions are

<img width="394" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeEtIQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8c02e49b8fd87a2d7b1022be6d55a60fc8895706/image.png" alt="image.png" />

<img width="598" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN2VIQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--be13006e23b49fb8ca29f01b06b92dc961f06f1a/image.png" alt="image.png" />

**Comment by mmiddaugh** [comment]
Also @omahane St Cloud Outstation (not clear to me yet which version - valid or invalid) is displayed as a Nearby Location on the [Anoka Vet Center Locations page](https://www.va.gov/anoka-vet-center/locations/)
I would expect the Outstation to be listed as a Satellite location once published, similar to [Clarksville Outstation, with Nashville Vet Center](https://www.va.gov/nashville-vet-center/locations/)

<img width="441" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMldJQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fca2def6bee10aa3d3b1eef282f401df66cc1342/image.png" alt="image.png" />

**Comment by omahane** [comment]
@mmiddaugh I just checked this today and see that St. Cloud Vet Center Outstation has been published. Going to the [Anoka Vet Center](https://www.va.gov/anoka-vet-center/locations/) on va.gov, shows that the outstation is now showing as a satellite location.

<img width="532" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMkNlQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4e4eb1e36b320fa43b2865558dc98aef9adec599/Screen%20Shot%202024-04-29%20at%2008.50.23.png" alt="Screen Shot 2024-04-29 at 08.50.23.png" />

I believe that this is now behaving as expected. Please let me know if you think otherwise.

**Comment by jilladams** [comment]
@omahane @ian-sears Can you clarify if the remaining Drupal Admin / Helpdesk steps in ticket are outstanding, not necessary, or have been done and not checked off? Thanks!

**Comment by omahane** [comment]
@jilladams We are only now awaiting the CVS change and deploy so that the outstation in the Facility Locator links to the main Vet Center: https://www.va.gov/anoka-vet-center/

When that is done, the Help Desk should communicate that all work on the outstation is complete.

**Comment by omahane** [comment]
@ian-sears @TroyCMSSupport The CSV has been deployed. After confirmation with editors, this issue can be closed.

**Comment by jilladams** [comment]
This one too -- @ian-sears / @TroyCMSSupport can you verify that the editor loop is closed? This ticket can be closed and tracked just in JIRA moving forward.

**Comment by ian-sears** [comment]
Closing. Editors permissions varified. Notified Editors of Facility status.
