### ISSUE TITLE
FL: Service Type label & selector are vertically misaligned in Facility Locator filters

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#17807]
## Description or Additional Context 
We shipped #17071 on Wed 4/10. After daily deploy, in Firefox and possibly other browsers, the Service type dropdown field and label are vertically misaligned. 

<details><summary>Screenshots of markup</summary>

### City state input markup: 
![Screenshot 2024-04-10 at 3 02 51 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/85581471/e3460614-d19a-427d-b345-3267fd47ced7)

### Facility type
Within `search-controls-bottom-row`, the Facility Type form allows some head room above the label. Not clear to me what CSS is allowing for that -- no padding / margin in use, etc. , that I can tell.
![Screenshot 2024-04-10 at 3 04 00 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/85581471/2fefc9a3-4cb4-492a-aa61-885b9293866f)

### Service type selector
Is top aligned to the parent row. (It's a span, but converted to a div in the inspector and it didn't change anything. )
![Screenshot 2024-04-10 at 3 04 27 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/85581471/ace14686-674c-41cf-a603-a581f693b538)

</details>

## To reproduce
* Load https://www.va.gov/find-locations/ in any non-Chrome browser, at width >768px
* See that the Service type selector sits higher than the other filter in the same row

## Acceptance Criteria
- [x] Facility locator search controls should be visually the same across all supported browsers on Mac & Win
    - [x] Chrome 
    - [x] Firefox
    - [x] Safari
    - [x] Edge
    - [ ] Android
    - [x] iOS
- [x] Confirm all 3 Service Type filter variants:
  - [x] Disabled (on load, Community Pharmacies, Cemeteries, Vet Centers)
  - [x] Community Providers
  - [x] Active (VA Health, Urgent Care, Emergency Care, VA Benefits)
- [ ] Requires design review
- [x] Requires accessibility review

**Comment by laflannery** [comment]
@maxx1128 I feel badly I missed this. FWIW, if you change the `align-content: end` to `align-self: end` the display was fixed for me locally:

![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/106678594/dc5125ad-d093-41af-a06a-2604ff1d8ed1)

**Comment by davidmpickett** [comment]
@jilladams Should this be a Sprint 1 injection?

**Comment by jilladams** [comment]
@maxx1128 got a PR up and merged for this, but @maxx1128 can you confirm the ACs here?

**Comment by jilladams** [comment]
Quick check on FF in prod and it's fixed, but wanna make sure we get testing across browsers. 

![Screenshot 2024-04-11 at 2 47 00 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/85581471/0b66ebc7-b50e-4e51-ba27-366b7d8ab5b7)

**Comment by laflannery** [comment]
- Tested all Supported Windows browsers (FF, Chrome, Edge) and all 3 variants of the Service Type field (active, disabled, typeahead). Each are properly lined up and look as the screen shot in the comment above does.
- All Mac supported browsers I can test in the morning
- iOS browsers (Safari, Chrome, FF) are also lined up and look like this:
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/106678594/bebd4ce5-2a56-437a-9e32-57c2a8790c8b)
- Android I don't have access to so someone else would need to take a look

**Comment by randimays** [comment]
Verified in Chrome and Firefox on Android; looks good!

### Chrome

<img width="300" alt="Screenshot_20240412_084451_Chrome" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/19175324/e0210b4c-c18a-4f92-807d-65aebdb99c41">

### Firefox

<img width="300" alt="Screenshot_20240412_084519_Firefox" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/19175324/4854f8c6-c6f3-4676-addb-0ad506c6a7dd">

**Comment by jilladams** [comment]
@thejordanwood took a look and found one weird thing re: the size of the services field being slightly larger. That's gonna get a separate ticket, since we suspect the typography update may affect it as well. Otherwise: @thejordanwood when you're back online next week, if you could not whether you found anything else from design review? That's the last AC left.

**Comment by thejordanwood** [comment]
@jilladams I created [a ticket](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17836) for the sizing issues. I suspect that the typography update will fix this. Currently, the Facility type label is a larger font than the other labels. 

I noted this in my follow up ticket, but the Facility type label should be sentence case and say "Facility type".

**Comment by jilladams** [comment]
Ok - since that's tracked separately, closing here.
