### ISSUE TITLE
[BE Re-usable Q&A] Change the cardinality in the config for re-usable Q&As for CLPs

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-cms#17805]
## Description
In support of this ticket > CLP: FE combine page-specific and reusable Q&As under the same header & accordion group #10940, the cardinality of the re-usable Q&A field on CLPs (only) needs to be changed to 1 via the config.

### User story

**AS THE** engineer working on the ticket referenced above
**I WANT** the changes described above and in the AC to be made in support of the ticket I'm working on
**SO THAT** I can successfully complete the work to limit re-usable Q&As to 2 on CLPs, which will provide a better experience for Veterans, their caregivers, family and survivors

## Acceptance criteria

- [x] the cardinality of the re-usable q&a field on CLPs has been changed to 1 via the config
- [x] Verified the shape of the GraphQL data didn't change (which would affect Randi's work). **the shape [DID](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17805#issuecomment-2080992129) change**

**Comment by FranECross** [comment]
@dsasser Here's the ticket in support of Randi's re-usable Q&A ticket. I put it in Ready for you to pull in, if you're able to (if it won't blow up the work you're currently trying to get done). Or, alternatively, it can be pulled in next week in the new sprint. cc @jilladams @randimays

**Comment by jilladams** [comment]
@FranECross Based on [mid-sprint checkin](https://trello.com/c/AkcTlJvb/328-mid-sprint-2-checkin), this won't naturally fit in sprint, but if there might be a product argument to make for prioritizing it above other things at risk in sprint after the notifications work. If you make a call on that, just surface for Dave and cc me.

**Comment by dsasser** [comment]
## Mid-sprint Update 4/24/24

I plan to get this done in the morning. It is a quick change requires context switching I haven't been ready to do until now.

**Comment by dsasser** [comment]
@FranECross @randimays @jilladams 
I verified that the graphql output does change the data type from an array of objects to a single object:

<img width="852" alt="Screenshot 2024-04-27 at 9 01 28 AM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/221539/59aabe76-f109-4d24-88b6-3711692d5b6d">
<img width="933" alt="Screenshot 2024-04-27 at 9 06 18 AM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/221539/5956cb97-a54a-4c99-9e9e-4e79cc31a99d">

**Comment by dsasser** [comment]
## End of Sprint Update 4/30/24

PR is in review. Prior to merge we'll need to verify if changes are needed first on the FE in order to accommodate the data [shape of the graphql](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17805#issuecomment-2080992129) changing.

**Comment by jilladams** [comment]
@dsasser When PR merges, will you move this ticket to "Complete Pending Integration"?

**Comment by dsasser** [comment]
> @dsasser When PR merges, will you move this ticket to "Complete Pending Integration"?

Done.

**Comment by dsasser** [comment]
Verified in prod:
![Screenshot 2024-05-02 at 7 49 42 AM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/221539/06ab22b5-5708-4760-b853-87be992a511a)
