### ISSUE TITLE
Benefit Hub Landing Pages: upgrade to va-icon

### ISSUE THREAD

**Issue by randimays** [department-of-veterans-affairs/va.gov-cms#17816]
## Description
The Design System team is deprecating Font Awesome and encouraging teams to use `<va-icon>` where possible by the end of May 2024. Slack post here: https://dsva.slack.com/archives/C03R5SBELQM/p1710776364414359

We need to convert all usage of `<i>` in this application to `<va-icon>` to align with the icons in DST's library here: https://design.va.gov/foundation/icons

`<va-icon>` guidance in Storybook: https://design.va.gov/storybook/?path=/docs/uswds-va-icon--default

### Engineering notes
Icons to be converted:

1. https://github.com/department-of-veterans-affairs/content-build/blob/267e8c01b81d33570a2d97cf9f71e93b23f996fb/src/site/layouts/landing_page.drupal.liquid#L11
2. https://github.com/department-of-veterans-affairs/content-build/blob/267e8c01b81d33570a2d97cf9f71e93b23f996fb/src/site/layouts/landing_page.drupal.liquid#L178
3. https://github.com/department-of-veterans-affairs/content-build/blob/267e8c01b81d33570a2d97cf9f71e93b23f996fb/src/site/layouts/landing_page.drupal.liquid#L178
4. https://github.com/department-of-veterans-affairs/content-build/blob/267e8c01b81d33570a2d97cf9f71e93b23f996fb/src/site/layouts/landing_page.drupal.liquid#L214
5. https://github.com/department-of-veterans-affairs/content-build/blob/267e8c01b81d33570a2d97cf9f71e93b23f996fb/src/site/layouts/landing_page.drupal.liquid#L226

### User story

**AS A** PO/PM for products/features/applications managed by the Public Websites team
**I WANT** our features/products/applicates migrated to va-icon where appropriate
**SO THAT** when the migration to va-icon and deprecation of Font Awesome takes place, there won't be degraded Veteran-facing experiences in VA.gov.

### Quality / testing notes
- [ ] Spot check of all converted icons on mobile and desktop
- [ ] Update any unit / e2e tests where applicable

## Acceptance criteria
- [ ] a11y review
- [ ] all instances of `<i>` that can be converted to `<va-icon>` are converted

**Comment by randimays** [comment]
Mid-sprint update: we have been blocked on using va-icon in content-build since 4/19. DST is still working on a fix; it's not clear whether it will be released before the end of our sprint, but flagging the risk here.

**Comment by randimays** [comment]
We added the <va-icon>s to Benefit Hub landing pages and we're finding that the "size 3" of the icons (the smallest size available) is still too large for the social icons on these pages.

Slack conversation with DST here: https://dsva.slack.com/archives/C01DBGX4P45/p1715116583772769

We are awaiting DST's responses to the questions at the bottom. For now putting this in Blocked.

**Comment by randimays** [comment]
Still iterating on design & accessibility feedback for these icons. This will carry over.

**Comment by laflannery** [comment]
Confirmed in prod:
![Screenshot 2024-05-20 at 1 44 16 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/106678594/c4a4d464-34d9-48b6-974a-7add5f0e3c9d)
![Screenshot 2024-05-20 at 1 44 33 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/106678594/57a6c183-fb99-4cb9-a4cf-838ed98e1747)
