### ISSUE TITLE
Sidebars: upgrade to va-icon

### ISSUE THREAD

**Issue by randimays** [department-of-veterans-affairs/va.gov-cms#17819]
## Description
The Design System team is deprecating Font Awesome and encouraging teams to use `<va-icon>` where possible by the end of May 2024. Slack post here: https://dsva.slack.com/archives/C03R5SBELQM/p1710776364414359

We need to convert all usage of `<i>` in this application to `<va-icon>` to align with the icons in DST's library here: https://design.va.gov/foundation/icons

`<va-icon>` guidance in Storybook: https://design.va.gov/storybook/?path=/docs/uswds-va-icon--default

### Engineering notes
Icons to be converted:

1. https://github.com/department-of-veterans-affairs/content-build/blob/267e8c01b81d33570a2d97cf9f71e93b23f996fb/src/site/components/merger-social-sco.html#L52
2. https://github.com/department-of-veterans-affairs/content-build/blob/267e8c01b81d33570a2d97cf9f71e93b23f996fb/src/site/components/merger-social-sco.html#L54
3. https://github.com/department-of-veterans-affairs/content-build/blob/267e8c01b81d33570a2d97cf9f71e93b23f996fb/src/site/components/navigation-sidebar.html#L30
4. https://github.com/department-of-veterans-affairs/content-build/blob/267e8c01b81d33570a2d97cf9f71e93b23f996fb/src/site/navigation/sidebar_nav.drupal.liquid#L9
5. ~https://github.com/department-of-veterans-affairs/content-build/blob/267e8c01b81d33570a2d97cf9f71e93b23f996fb/src/site/includes/social-share.drupal.liquid#L21~ Completed in [this PR](https://github.com/department-of-veterans-affairs/content-build/pull/2082)
6. ~https://github.com/department-of-veterans-affairs/content-build/blob/267e8c01b81d33570a2d97cf9f71e93b23f996fb/src/site/includes/social-share.drupal.liquid#L30~ Completed in [this PR](https://github.com/department-of-veterans-affairs/content-build/pull/2082)

### User story

**AS A** PO/PM for products/features/applications managed by the Public Websites team
**I WANT** our features/products/applicates migrated to va-icon where appropriate
**SO THAT** when the migration to va-icon and deprecation of Font Awesome takes place, there won't be degraded Veteran-facing experiences in VA.gov.

### Quality / testing notes
- [x] Spot check of all converted icons on mobile and desktop
- [x] Update any unit / e2e tests where applicable

## Acceptance criteria
- [x] a11y review
- [x] all instances of `<i>` that can be converted to `<va-icon>` are converted

**Comment by jilladams** [comment]
Adding the Facilities label/products as well, since this sidebar will affect VAMC pages, News releases, and Stories as well. (If I'm understanding the ticket correctly.)

**Comment by randimays** [comment]
@jilladams I could be wrong, but the Facilities pages use a different sidebar than others, so I don't think Facilities is impacted here.

Here are the sidebars created by the files in this ticket:

<img width="600" alt="Screenshot 2024-04-12 at 8 53 36 AM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/19175324/0e905dfe-a0d1-48e2-b153-2e4148eed84e">
<img width="418" alt="Screenshot 2024-04-12 at 8 56 06 AM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/19175324/dac37b11-0f57-4e81-b23a-1f8359589e3f">

<img width="600" alt="Screenshot 2024-04-12 at 8 53 44 AM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/19175324/7ce7b4fd-b298-4f12-9005-20b20bd11a8c">
<img width="366" alt="Screenshot 2024-04-12 at 8 55 39 AM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/19175324/2b49982a-5c60-4ebf-a3d4-3bc7c0cdd8b2">


<br/><br/><br/>
Here is the sidebar on the Facilities screens:
<br/>
<img width="600" alt="Screenshot 2024-04-12 at 8 52 40 AM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/19175324/f2cc93d0-e777-48fb-abbd-56ec11b9e453">
<img width="339" alt="Screenshot 2024-04-12 at 8 52 45 AM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/19175324/75c316a5-0707-4aa3-a61b-0b57fe40912e">

**Comment by randimays** [comment]
Mid-sprint update: we have been blocked on using va-icon in content-build since 4/19. DST is still working on a fix; it's not clear whether it will be released before the end of our sprint, but flagging the risk here.

- [Initial Slack thread to describe the content-build issue](https://dsva.slack.com/archives/C01DBGX4P45/p1713550017444309)
- [First content-build fix from DST](https://github.com/department-of-veterans-affairs/content-build/pull/2030)
- [Continuing content-build issues Slack thread](https://dsva.slack.com/archives/C01DBGX4P45/p1714061116324459)

**Comment by randimays** [comment]
Successfully validated in production. Closing!
