### ISSUE TITLE
Mobile Vet Centers with unassigned facility operating status do not render on FE correctly

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-cms#17829]
## Describe the defect

For Mobile Vet Centers, we assume that they will have an operating status. However, in production currently only 5 of 88 do. 

For Mobile Vet Centers with no operating status, the `alert-expandable warning` is not wrapped in a conditional, to protect against empty operating status. This leads to a a less than ideal front end experience of an odd expanded alert carat displayed above the phone number on the Locations page. 

Please see other related defects described under Additional Context

[empty_MVC_operating_status.xlsx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBekJWQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--dd083fece4b9e6b7c7437c74f70d16422d438917/empty_MVC_operating_status.xlsx)

## To Reproduce
1. Go to [Salt Lake City Vet Center Locations page](https://www.va.gov/salt-lake-city-vet-center/locations/)
2. Scroll down to Satellite Location list and view Mobile Vet Centers.
3. Observe empty carat displayed about Phone number 
4. Go to [Greensboro Vet Center Locations page](https://www.va.gov/greensboro-vet-center/locations/)
5. Scroll down to Satellite Location list and view Greensboro Vet Center - Kernersville VA Healthcare Center and Mobile Vet Centers.
6. Observe "Limited services and hours" expanded alert appears as expected
7. View [Facility operating status view in Drupal, filtered to District 5 Vet Centers, filtered with keyword "Mobile"](https://prod.cms.va.gov/admin/content/facilities/facility-status?Title=Mobile&field_facility_locator_api_id_value=&field_operating_status_facility_value=All&field_operating_status_more_info_value=&field_supplemental_status_target_id_op=or&field_supplemental_status_target_id=All&type=All&moderation_state=All&workbench_access_section__section=1017)
8. Observe affected Mobile Clinics have no associated facility operating status

## AC / Expected behavior
- [x] Expandable alerts only appear if they are populated with content
- [x] Expandable alerts that contain operating status still appear correctly, e.g. https://www.va.gov/cape-cod-vet-center/locations/
- [x] verification across browsers

## Screenshots
<details>
<summary> Salt Lake City Mobile Vet Center Operating status  </summary>

<img width="510" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeWRWQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3c091e032ad5d651b3665de1058775b395210e79/image.png" alt="image.png" />
</details>

<details>
<summary> Mobile Vet Center Operating status in Drupal  </summary>

<img width="583" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd1ZWQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4b72c71c8b3ad7d9707263b4f3287a68fec383d9/image.png" alt="image.png" />

</details>
<details>
<summary> Greensboro Vet Center </summary>

<img width="851" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL2hVQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b384177f18efe694fdc4cfccccfbd4d082ee2cf8/image.png" alt="image.png" />
</details>

 ## Additional context
I tripped up against 3 other defects while documenting this situation. They likely need separate tickets. 
1. #17830 - tracks the Drupal investigation fix for why 83 of 88 Mobile Vet Centers have no operating status assigned in Drupal. This is unexpected for existing, published locations.
2. I attempted to download the Facility status report twice. The view appeared to download, but when I opened the file, the first two times it was completely empty. The third time, it had 5 rows, rather than the expected 88.
3. I finally cut and pasted the rows into a spreadsheet and while sorting, I discovered 5 Mobile Vet Centers which are not assigned to an appropriate Section. All have "Vet Centers" listed as their Section. All also are draft, which seems suspicious. 
<img width="504" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeVJWQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--614fa947d1ffdd43a21e5e8052ba58af2147a262/image.png" alt="image.png" />

## Desktop (please complete the following information if relevant, or delete)
 - Browser: GFE Edge

**Comment by jilladams** [comment]
@mmiddaugh @omahane I agree we have 2 separate issues here, but let's keep this issue for FE. Will separately ticket Drupal.

**Comment by jilladams** [comment]
@mmiddaugh Drupal issue cut as https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17830. 

Some questions: 
1. I'm not familiar with the "Facility status report" - could you post a link to that?  Couldn't find it in content audit tools, not sure where to look.
2. Just confirming that from what we see so far, this only applies to Mobile Vet Centers, correct? (Can double check using the report )

**Comment by eselkin** [comment]
Mobile Vet Centers don't have 
`fieldOperatingStatusFacility` and `fieldOperatingStatusMoreInfo` to begin with, according to graphql

**Comment by jilladams** [comment]
Verified in production. Closing.
