### ISSUE TITLE
Education SCO: upgrade to va-icon

### ISSUE THREAD

**Issue by randimays** [department-of-veterans-affairs/va.gov-cms#17823]
## Description
The Design System team is deprecating Font Awesome and encouraging teams to use `<va-icon>` where possible by the end of May 2024. Slack post here: https://dsva.slack.com/archives/C03R5SBELQM/p1710776364414359

We need to convert all usage of `<i>` in this application to `<va-icon>` to align with the icons in DST's library here: https://design.va.gov/foundation/icons

`<va-icon>` guidance in Storybook: https://design.va.gov/storybook/?path=/docs/uswds-va-icon--default

### Engineering notes
Icons to be converted:

1. https://github.com/department-of-veterans-affairs/content-build/blob/267e8c01b81d33570a2d97cf9f71e93b23f996fb/src/site/layouts/event.drupal.liquid#L58

### User story

**AS A** PO/PM for products/features/applications managed by the Public Websites team
**I WANT** our features/products/applicates migrated to va-icon where appropriate
**SO THAT** when the migration to va-icon and deprecation of Font Awesome takes place, there won't be degraded Veteran-facing experiences in VA.gov.

### Quality / testing notes
- [ ] Spot check of all converted icons on mobile and desktop
- [ ] Update any unit / e2e tests where applicable

## Acceptance criteria
- [ ] a11y review
- [ ] all instances of `<i>` that can be converted to `<va-icon>` are converted

**Comment by jilladams** [comment]
@randimays the code link here references Events, but that's a dupe of what's in #17822 - we don't own Education anymore. Could this be closed?

**Comment by randimays** [comment]
@jilladams whoops! I copy/pasta'd the wrong link. Good to know we don't own Education anymore; so this can be closed!
