### ISSUE TITLE
Update Facility Locator fields to be the same height

### ISSUE THREAD

**Issue by thejordanwood** [department-of-veterans-affairs/va.gov-cms#17836]
## Description

When the Facility Locator template was update to v3 components in [#17071 ](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17071), the Facility type field became smaller than the Service type and location fields. 

The Facility type field is now 2 px shorter. Consider adjusting the height of the Service type field to be the same as the Facility type field. 

![Screenshot 2024-04-11 at 2 47 00 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/85581471/0b66ebc7-b50e-4e51-ba27-366b7d8ab5b7)

## Additional update

The label on the Facility type field should use sentence case and be "Facility type" instead of "Facility Type"

```[tasklist]
### Acceptance criteria
- [ ] Facility Locator search fields are the same size, across browsers
- [ ] Facility type field label uses sentence case: "Facility type"
```

```[tasklist]
### QA
- [ ] Design Review
```

**Comment by Agile6MSkinner** [comment]
@thejordanwood to check if it's still an issue. If it is, we can re-open it if we have the capacity and it becomes a priority.

**Comment by thejordanwood** [comment]
@Agile6MSkinner Yes, this should be resolved when these are turned into components. I'll close this ticket and add that note to the [facility locator design update ticket](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17835) that I have open.
