### ISSUE TITLE
New Vet Center Facility: Clarksville Vet Center (BOLO)

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-cms#17846]
> We expect to learn about a new Vet Center in Clarksville, TN. This location will replace the [Clarksville Vet Center Outstation](https://prod.cms.va.gov/nashville-vet-center/clarksville-outstation) (vc_7241OS) associated with Nashville Vet Center. 

## Description
Use this runbook if: a Vet Centers, Mobile Vet Centers, Vet Center Outstations is flagged as New, OR if an existing facility is flagged as New with a new Facility API ID. (This may happen if a Vet Center moves districts, or a Mobile Vet Center is reallocated to a different Vet Center.)

## Intake
What triggered this runbook? (Flag in CMS, Help desk ticket, Product team, VHA Digital Media)
Trigger: @mmiddaugh informed us to be on the lookout via Slack

Link to associated help desk ticket (if applicable)
Help desk ticket: <insert_help_desk_link>

Name of submitter (if applicable)
Submitter: <insert_name>

If the submitter is an editor, send them links to any relevant KB articles for the Vet Center product.
KB articles: <insert_kb_article_links>

Link to facility in production:
Facility CMS link: ???
Facility API ID: ???

## Acceptance criteria
- [ ] New Vet Center
[@TODO: KB ARTICLE FOR ADDING VET CENTERS - SEE runbook-vamc-facility-new]

CMS help desk steps
Note: If the help desk is waiting on information from the facility staff or editor, add the Awaiting editor flag to the facility with a log message that includes a link to this ticket. Remove the flag when the ticket is ready to be worked by the Facilities team. Be sure to preserve the current moderation state of the node when adding or removing the flag.

**If a Mobile Vet Center:**
1. Confirm what Vet Center it belongs to, and set the "Main Vet Center location" field. The parent location may be derived by the Facility ID.
2. Contact the Vet Center editor to remind them to (1) add a photo of the Mobile Vet Center and then they can publish when ready and (2) remind them that if this Mobile Vet Center is used by any other facilities to communicate with those Vet Center editors
3. Consider: Following up with Barb/RCS Central office to be sure that she's aware that the mobile Vet Center is in-flight

**If a Outstation:**
1. Confirm what Vet Center it belongs to, and set the "Main Vet Center location" field. The parent location may be derived by the Facility ID.
2. Contact the Vet Center editor to remind them to (1) add a photo of the Outstation and then they can publish when ready
3. Consider: Following up with Barb/RCS Central office to be sure that she's aware that the Outstation is in-flight

**If a Vet Center:**
1. Become aware that the new facility is now on the Facility API (typically, via a Flag).
2. Check with Readjustment Counseling Services to (1) confirm what district the Vet Center belongs and (2) Identify the Vet Center Director and Outreach Specialist (names/email addresses)
3. In Sections taxonomy, move the Vet Center Section to the appropriate district.
4. Create accounts (or restrict existing accounts) with editor rights only for Vet Center Director and Outreach Specialist so that they cannot publish on their own.
5. Contact Vet Center Director and Outreach specialist to onboard for training [@TODO write sample email - SEE runbook-vamc-facility-new] Note: this should include instructions for adding content and preparing for publishing and RCS Central Office should be included as CC
6. Add flag Awaiting editor to this facility. Note: This is now blocked until RCS Central office approves.
7. Once approved by RCS Central Office as complete, proceed to Drupal Admin publishing steps

**Drupal Admin steps**
8. Bulk publish the nodes and facility.
9. Edit the facility node: remove the New facility and Awaiting editor flags, save the node.
10. Let Help desk know this has been done.

**CMS Help desk (wrap up)**
11. Upgrade the Vet Center Director and Outreach Specialist accounts to the publisher role for that Vet Center.
12. Notify editor and any other stakeholders.

**Comment by ian-sears** [comment]
Monday, July 22, 2024 Jira ticket (to CMS HD) alerted us of this upcoming change: [VAHELP-7767](https://va-gov.atlassian.net/browse/VAHELP-7767) from Outstation to Vet Center. We advised the Editor to begine the process first of setting up the New Vet Center, migration to that would follow, then closing the Outstation in the process.

Today, CMS Migrator Archived the [Clarksville Vet Center Outstation](https://prod.cms.va.gov/nashville-vet-center/clarksville-outstation)

**Comment by ian-sears** [comment]
Closing this as it was resolved 8/21/2024.
This Outstation became a Vet Center, Redirect wwas deployed and CSV was updated.
https://www.va.gov/clarksville-vet-center/
vc_0350V
