### ISSUE TITLE
Update Drupal interface for Service Options to match new guidance

### ISSUE THREAD

**Issue by davidmpickett** [department-of-veterans-affairs/va.gov-cms#17843]
## User Story or Problem Statement

Follow up ticket based on #17600

###  Desired state for launch - Office Visits

**Drupal selection** | **Change explanation**
-- | -- 
Office visits - NULL | No change
Office visits - No | No change
Office visits - Yes, by appointment only | No change
Office visits - Yes, ~~on a first-come, first-served basis~~ **walk-in visits only** | Updated per comment thread
Office visits - Yes, with or without an appointment | No change

### Desired state for launch - Virtual Support

**Drupal selection** | **Change explanation**
-- | --
Virtual support - NULL | No change
Virtual support - No | No change
Virtual support - Yes, by appointment only |  No change in Drupal
Virtual support - Yes, ~~on a first-come, first-served basis~~ **Veterans can call at their convenience** | This wording is what we validated with users during testing. 
**Virtual support - Virtual visits may be available** | Add this option to allow for partial availability based on feedback from VAMC editors
~~Virtual support - Yes, with or without an appointment~~  | Remove this option - no use cases

## Description or Additional Context 

Coordinate with FE ([#17844](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17844)) around how the fourth Virtual Support option is changing. Might be okay to keep the same machine name and just change the label so the GraphQL query doesn't have to change. Rather than deleting a field and adding a new field.

## Acceptance Criteria
- [x] The editor-visible labels in Drupal match the wording above
- [ ] Machine name updates for code comprehension? Coordinate with FE.
- [x] The existing Service Location data migration is not negatively impacted
- [x] The existing LH push code is not negatively impacted
- [x] Requires design review
- [ ] Requires accessibility review

**Comment by omahane** [comment]
@davidmpickett @davidmpickett Confirming that this is what it should look like:
![Screenshot 2024-04-17 at 16 54 50](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/766573/a7ba7715-2072-4aaa-84b1-54a1156c9146)

I was thinking about this, and I can foresee these new options being confusing.

## Office visits
"Yes, no appointment necessary" might mean that you can make an appointment but you don't have to. In that case, why not choose "Yes, with or without an appointment"?  If "Yes, no appointment necessary" means that no appointments can be made, then it is distinct from "Yes, with or without an appointment". Does that make sense?

## Virtual support
I do not understand how "Virtual visits may be available" should be interpreted, but it sounds like a hedge against guaranteeing that virtual support is available while leaving the possibility open for virtual support. I am not sure exactly how helpful that is to a Veteran, though. It seems kind of like a roll of the dice whether you can actually get virtual support or not. Am I misinterpreting this?

**Comment by davidmpickett** [comment]
> I was thinking about this, and I can foresee these new options being confusing.
> 
> ## Office visits
> "Yes, no appointment necessary" might mean that you can make an appointment, but you don't have to. In that case, why not choose "Yes, with or without an appointment"? If "Yes, no appointment necessary" means that no appointments can be made, then it is distinct from "Yes, with or without an appointment". Does that make sense?
> 

"Yes, no appointment necessary" is supposed to represent cases where no appointments are possible. I think that "first come, first served" is a less ambiguous explanation of this scenario for editors, but I don't think it is the correct phrase to show to Veterans. Our principal here is deciding the desired FE language and then making Drupal options match that so editors have a clear sense of what will show up. 

> ## Virtual support
> I do not understand how "Virtual visits may be available" should be interpreted, but it sounds like a hedge against guaranteeing that virtual support is available while leaving the possibility open for virtual support. I am not sure exactly how helpful that is to a Veteran, though. It seems kind of like a roll of the dice whether you can actually get virtual support or not. Am I misinterpreting this?

This came out of feedback from VAMC editors that sometimes a given service or service location may have different types of visits/appointments, some of which can be virtual and other that have to be in-person. In conjunction with this option, editors can provide additional context in the Custom Appointment Intro Text that appears immediately below these icons and phrases

Slack thread from last sprint where @mmiddaugh talked about this: https://dsva.slack.com/archives/C0FQSS30V/p1712951198246389

**Comment by omahane** [comment]
> > I was thinking about this, and I can foresee these new options being confusing.
> > ## Office visits
> > "Yes, no appointment necessary" might mean that you can make an appointment, but you don't have to. In that case, why not choose "Yes, with or without an appointment"? If "Yes, no appointment necessary" means that no appointments can be made, then it is distinct from "Yes, with or without an appointment". Does that make sense?
> 
> "Yes, no appointment necessary" is supposed to represent cases where no appointments are possible. I think that "first come, first served" is a less ambiguous explanation of this scenario for editors, but I don't think it is the correct phrase to show to Veterans. Our principal here is deciding the desired FE language and then making Drupal options match that so editors have a clear sense of what will show up.
> 
Yes, walk-in visits only" would probably be clearer.

**Comment by davidmpickett** [comment]
One of CAIA's content principles is avoiding ability-focused language (view, walk, see, hear), so "walk-in" was deliberately excluded when drafting these phrases

**Comment by omahane** [comment]
That makes sense.  Here are some alternatives:
"Yes, drop-in visits only"
"Yes, impromptu visits only"
"Yes, unscheduled visits only"

**Comment by omahane** [comment]
Also, if you're committed to the suggested language change, I can implement that. My only goal was to avoid confusion before implementation and launch.

**Comment by mmiddaugh** [comment]
Per Danielle, the general alternative is "no appointment needed", although there is familiarity with the "walk-in clinic" phrase and some locations literally use that name and signage.

Since we're really trying to distinguish between these options, I think "Yes, walk-in visits only" will provide the clarity that is needed.

**Comment by davidmpickett** [comment]
> Per Danielle, the general alternative is "no appointment needed", although there is familiarity with the "walk-in clinic" phrase and some locations literally use that name and signage.
> 
> Since we're really trying to distinguish between these options, I think "Yes, walk-in visits only" will provide the clarity that is needed.

I updated the body of this ticket and the corresponding FE ticket to match

**Comment by davidmpickett** [comment]
QA complete. Suggest moving to complete pending integration and coordinating merge timing with @eselkin in #17844 17844

**Comment by omahane** [comment]
@davidmpickett Do we need design and @laflannery to look at this? (The ACs say so).

**Comment by davidmpickett** [comment]
It might make sense to wait until [Eli's related ticket](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17844) is also in PR and then ask Jordan and Laura to review the combined solution.

**Comment by davidmpickett** [comment]
Confirmed on Tugboat
![Screenshot 2024-04-26 at 1 20 02 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/03381d5a-7cd6-4c54-843f-fb7765f02d63)

**Comment by davidmpickett** [comment]
Design review complete. In this case, I actually updated [Figma](https://www.figma.com/file/eECF81nwktbnKX889HiKhl/VBA-Content-Specs?type=design&node-id=208-714&mode=design) to match the new wording here. Interface is otherwise up to spec

**Comment by davidmpickett** [comment]
Verified on Tugboat.
![Screenshot 2024-04-29 at 9 46 13 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/69ec55b4-5c3e-47b4-bb78-20baf7107f07)

@laflannery I know you were very thorough in checking these scenarios when you tested Eli's related PR, but just want to confirm you are good signing off on the Drupal side too.

**Comment by laflannery** [comment]
Yep, I also did Drupal at that point as well
