### ISSUE TITLE
Columbia Mobile Vet Center still in DRAFT

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-cms#17848]
## Description
The Facilities team noticed last week that some Mobile Vet Centers seem to have been created as CAPs. Once such example is [Columbia, SC Vet Center - Mobile Vet Center](https://prod.cms.va.gov/columbia-sc-vet-center/community-access-point/columbia-sc-vet-center-mobile-vet-center). 
> - According to VAST, Columbia, SC Vet Center has an associated MVC: [0817MVC](https://prod.cms.va.gov/columbia-mobile-vet-center), which appears to still be in Draft. 

### Steps for implementation
1. Need to get the MVC published 
2. Barb: Needs to work with the editor to associate the image with the actual MVC (assuming it is correct and up to date) -- if Michelle is OOO, Facilities to handle.
3. And then potentially archive the CAP. I suggest including Barb Kuhn in communications so that she can help the editor determine if the CAP should be archived or retained. 

# New Vet Center runbook steps
Use this runbook if: a Vet Centers, Mobile Vet Centers, Vet Center Outstations is flagged as New, OR if an existing facility is flagged as New with a new Facility API ID. (This may happen if a Vet Center moves districts, or a Mobile Vet Center is reallocated to a different Vet Center.)

## Intake
What triggered this runbook? (Flag in CMS, Help desk ticket, Product team, VHA Digital Media)
Trigger: @mmiddaugh informed us to be on the lookout via Slack

Link to associated help desk ticket (if applicable)
Help desk ticket: <insert_help_desk_link>

Name of submitter (if applicable)
Submitter: <insert_name>

If the submitter is an editor, send them links to any relevant KB articles for the Vet Center product.
KB articles: <insert_kb_article_links>

Link to facility in production:
Facility CMS link: ???
Facility API ID: ???

## Acceptance criteria
- [ ] New Vet Center
[@TODO: KB ARTICLE FOR ADDING VET CENTERS - SEE runbook-vamc-facility-new]

**CMS help desk steps**
Note: If the help desk is waiting on information from the facility staff or editor, add the Awaiting editor flag to the facility with a log message that includes a link to this ticket. Remove the flag when the ticket is ready to be worked by the Facilities team. Be sure to preserve the current moderation state of the node when adding or removing the flag.

**If a Mobile Vet Center:**
1. Confirm what Vet Center it belongs to, and set the "Main Vet Center location" field. The parent location may be derived by the Facility ID.
4. Contact the Vet Center editor to remind them to (1) add a photo of the Mobile Vet Center and then they can publish when ready and (2) remind them that if this Mobile Vet Center is used by any other facilities to communicate with those Vet Center editors
5. Consider: Following up with Barb/RCS Central office to be sure that she's aware that the mobile Vet Center is in-flight

**Drupal Admin steps**
10. Bulk publish the nodes and facility.
11. Edit the facility node: remove the New facility and Awaiting editor flags, save the node.
12. Let Help desk know this has been done.

**CMS Help desk (wrap up)**
13. Upgrade the Vet Center Director and Outreach Specialist accounts to the publisher role for that Vet Center.
14. Notify editor and any other stakeholders.

**Comment by mmiddaugh** [comment]
@jilladams @davidmpickett 
this one may have slipped through the Flagged Facility cracks - it isn't urgent but probably should get some eyes on it to confirm. Leaving it to you to prioritize.

**Comment by jilladams** [comment]
Noted in sprint plan

**Comment by jilladams** [comment]
@omahane to check and confirm we have an MVC right now / if anything needs to be archived
@mmiddaugh to check for comms from Barb on Columbia MVC

**Comment by omahane** [comment]
We have 2 Vet Center MVCs:
- vc_0817MVC: https://prod.cms.va.gov/node/17458/
- vc_0875MVC: https://prod.cms.va.gov/node/17482/
  - 2475 Broadway Bluffs DriveSuite 40
Columbia, MO 65201
United States

Both were created the same day on 3/26/2021. Neither have ever been published.

Meanwhile, we have this CAP

**Comment by mmiddaugh** [comment]
@omahane 
Barb confirmed that this editor has added the correct 817 MVC node to his site and will add an image before archiving the erroneous MVC CAP.

**Comment by omahane** [comment]
@ian-sears @TroyCMSSupport The editor has archived https://prod.cms.va.gov/columbia-sc-vet-center/community-access-point/columbia-sc-vet-center-mobile-vet-center, so they just need to update https://prod.cms.va.gov/columbia-sc-vet-center/columbia-mobile-vet-center and publish it.

**Comment by jilladams** [comment]
Reassigned to @TroyCMSSupport @ian-sears

**Comment by mmiddaugh** [comment]
The Mobile Vet Center is published with an image and available on [Prod](https://www.va.gov/columbia-sc-vet-center/locations/) 
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/55411834/5ffbea45-aabe-45a4-9f09-978efc749846)
Closing this issue
