### ISSUE TITLE
Update VAMC to use va-icon

### ISSUE THREAD

**Issue by eselkin** [department-of-veterans-affairs/va.gov-cms#17855]
## User Story or Problem Statement

`<va-icon>` is replacing `<i>` font awesome tags. VAMCs must replace font awesome with va-icon ASAP.

### VAMC system detail pages
UDPATE 5/29: Only the Media file still has FA icons

1. update all `src/site/paragraphs` includes since all may be dependent (service location later)
   1. ~`src/site/paragraphs/downloadable_file.drupal.liquid` (3 occurrences)~
       -  ~Decision was made to update these instances to use the proper component (link component with `download` prop) rather than only updating the icon (Original component update ticket #16999)~
   2. ~`src/site/paragraphs/link_teaser_featured_content.drupal.liquid` (1 occ)~
   3. ~`src/site/paragraphs/lists_of_links.drupal.liquid` (1 occ)~
   4. **`src/site/paragraphs/media.drupal.liquid` (1 occ)**

### Top Task pages
1. `src/site/layouts/vamc_system_billing_insurance.drupal.liquid` or `src/site/layouts/vamc_system_medical_records_offi.drupal.liquid` 
    1. **UPDATE 5/28: I can't find any FA icons in the above 2 files. I think they might be gone since SL was merged in and we no longer need to update anything here.**
    2. ~Update NEW (SL integration branch) `src/site/paragraphs/service_location.drupal.liquid` (5 occurrences - not on main)~

### Side Nav 
1. vets-website `src/platform/site-wide/side-nav/components/SideNav.js`
   - Bars icon in mobile display
   - `src/platform/site-wide/side-nav/components/ExpandCollapseIcon.js` 2 Chevrons

### Press Releases/News Releases
1. Listing page: No changes
2. Press Release page: `src/site/layouts/press_release.drupal.liquid` (2 occ)
   - ~download could probably be changed to the download va-link type~ 
   - However there is no link type for print, so that definitely has to update the icon. Additionally, that print link is actually a button and not a link with an onclick.
     - **UPDATE 5/29: The print button [should be a updated to secondary button](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17914) however there is a pending question about the display of this on the 320 breakpoint** 

## Already completed in other tickets

<details>
  <summary>VAMC system pages - COMPLETED</summary>

  ### Items
  1. update `src/site/layouts/health_care_region_page.drupal.liquid` (16 occurrences) (question, should we be changing the See all Locations faux-buttons to buttons or continue buttons or active links) [asked about font-size](https://dsva.slack.com/archives/C01DBGX4P45/p1713204226211629)... Update font-size classes have no effect. We should change this to a [secondary continue va-button](https://design.va.gov/storybook/?path=/docs/components-va-button--primary) or active link @thejordanwood @laflannery
     * Yes - we should be updating these "imposters" to use proper components. This work will close ticket #15598
  2. update `src/site/includes/operatingStatusFlagsLinks.drupal.liquid` (6 occurrences)
  3. update `src/site/facilities/facility_social_links.drupal.liquid` (8 occurrences) 
     * Note 1: We want to remember to change the icon to use the new X icon instead of the old Twitter
     * Note: This impacts VAMC Facility pages as well 
</details>

<details>
  <summary>VAMC Health Services - COMPLETED</summary>

  ### Items
  No Changes were needed
</details>

<details>
  <summary>VAMC Operating Status pages - COMPLETED</summary>

  ### Items
  1. `src/site/layouts/vamc_operating_status_and_alerts.drupal.liquid` 
     * Remove all faux va-on-this-page down-arrow links/icons (the real va-on-this-page elements capture the conditionally rendered h2 page elements)
     * Update fake alert icon/title spans (3 occ)
       * Decision was made to update these instances to use the proper component (alert component with `slim` prop) rather than only updating the icon (Original component update ticket #16998)

</details>

<details>
  <summary>Full width Banners - COMPLETED</summary>

  ### Items
  1. `src/site/components/fullwidth_banner_alerts.drupal.liquid` (1 occ) 
    
</details>

<details>
  <summary>Other banners - COMPLETED</summary>

  ### Items
  No Changes were needed as they were already va-banner or va-promo-banner
</details>

<details>
  <summary>Stories - COMPLETED</summary>

  ### Items
  1. Stories listing - No changes needed
  2. Story detail pages:
     *  Update `src/site/facilities/story_social_share.drupal.liquid` (2 occ) (Uses the old twitter Icon and text, should this be updated @thejordanwood @laflannery)
        * Answer: Yes please update to use the new X icon and the new text should be "Share on X (formerly Twitter)"

</details>

<details>
  <summary>Staff - COMPLETED</summary>

  ### Items
  1. Leadership listing - No changes needed
  2. Person profile pages:
     *  Update `src/site/layouts/person_profile.drupal.liquid` (2 occ) Can use the download va-link type.

</details>

 
## Acceptance Criteria
- [x] VAMC System page fontawesome icons have been replaced by va-icon
- [ ] VAMC Detail pages (programs, work for us, contact us) fontawesome icons have been replaced by va-icon
- [x] VAMC Operating Status page fontawesome icons have been replaced by va-icon
- [x] VAMC top-task pages (register for care, Billing and insurance, Medical records) fontawesome icons have been replaced by va-icons
- [ ] Side Nav contains no fontawesome icons in mobile or desktop views and have been replaced by va-icons
- [x] Full-width banner has no fontawesome icon and has been been replaced by va-icons
- [x] Stories have no fontawesome icons and have been been replaced by va-icons
- [ ] News releases have no fontawesome icons and have been been replaced by va-icons
- [x] Staff have no fontawesome icons and have been been replaced by va-icons
- [ ] Update and run existing test(s).
- [ ] If additional tests are needed, stub a ticket to note this for future work.
- [ ] Requires accessibility review
- [ ] Requires design review

**Comment by laflannery** [comment]
@eselkin Regarding your question:

> question, should we be changing the See all Locations faux-buttons to buttons or continue buttons or active links
This has been [ticketed separately here](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15598)

**Comment by jilladams** [comment]
Thanks @eselkin !  @maxx1128 could you gut check to confirm / deny the 5 point estimate here? 

Also acknowledging; we don't have guidance from DS on this update, so that guidance may affect estimate once it's available.

**Comment by maxx1128** [comment]
@jilladams confirming the 5 points 👍

**Comment by eselkin** [comment]
@jilladams I put the 5 because it should be easy changes but there may be unforeseen problems like alignment and size issues. 

@laflannery I'll double check on the banners. I know the alerts didn't have icon tags.

**Comment by eselkin** [comment]
When doing this ticket https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15598 should also be brought in simultaneously.

**Comment by eselkin** [comment]
Added Full Width banner, other banners don't use icons and are already components @laflannery

**Comment by jilladams** [comment]
Noted re: the suggested ticket that should go along with this one, for refinement next week. (Eli, if you already have an idea how large that one is, feel free to go ahead and estimate async.)

**Comment by laflannery** [comment]
Another point we may want to consider discussing in refinement (which was briefly discussed in slack) is the effort between doing the icon work for custom code where a DS component is available. I think this only applies to 2 items:
- Alert - slim on operating status pages
- VAMC Banners

**Comment by eselkin** [comment]
@eselkin make separate ticket for SL integration branch work

**Comment by jilladams** [comment]
VAMC System Banner Alert with Situation Updates (`full_width_banner_alert`) -- doesn't use a component, needs to, needs custom work. We will not update the icon on alerts in this ticket. That work is in #16952 currently, and we'll either do it there or break it out of that ticket into its own as needed.

**Comment by eselkin** [comment]
@laflannery add component stuff (for downloadable file and media etc)

**Comment by laflannery** [comment]
Updated description to include notes that the following "imposters" should be replaced:
- "See all" buttons should be replaced with <va-link> `active` prop
- Download links should be replaced with <va-link> with `download` prop
- Media links should be replaced with <va-link> with `channel` prop
- Operating status alerts should be replaced with <va-alert> with `slim` prop

**Comment by eselkin** [comment]
Updated to include Stories/Story Page, News Releases/News Release Page, Leadership/Person Profile

@mmiddaugh @jilladams @laflannery @thejordanwood See #10.ii above. Should we change the Twitter icon/text?
Also #9.ii there's two kinds of links on this page with icons (One is a print button that looks like a link and one is a download. If we change one to the download va-link it might look odd next to each other.

**Comment by laflannery** [comment]
@eselkin I struckout the download links on 9 because these were done when Randi just did the News release component ticket (#17068)

**Comment by laflannery** [comment]
Updating original description:

- `src/site/layouts/health_care_region_page.drupal.liquid` was completed in ticket #16952
- `src/site/includes/operatingStatusFlagsLinks.drupal.liquid` was completed in ticket #16964
- `src/site/facilities/facility_social_links.drupal.liquid` was completed in ticket #17654
- `src/site/layouts/vamc_operating_status_and_alerts.drupal.liquid` was completed in ticket #16998
- `src/site/components/fullwidth_banner_alerts.drupal.liquid` was completed in ticket #16952
- `src/site/paragraphs/service_location.drupal.liquid` was completed in ticket #17654
- `src/site/facilities/story_social_share.drupal.liquid` was completed in ticket #17067

**Comment by laflannery** [comment]
`src/site/paragraphs/downloadable_file.drupal.liquid` was updated in ticket #16999
`src/site/paragraphs/link_teaser_featured_content.drupal.liquid` was updated in ticket #17657
`src/site/paragraphs/lists_of_links.drupal.liquid` was updated in ticket #17817

**Comment by chriskim2311** [comment]
Verified changes are live on prod, closing!
