### ISSUE TITLE
FE: Update Staff Phone number to work with new fields

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#17865]
## Background
In #17860 the Phone number field was updated to use the Phone paragraph type field (instead of the Telephone number field that it previously was). This means the FE query needs to be updated to pull the data properly from these new fields and then display on the FE.

## Description
The Phone paragraph type has more fields than what we previously had so there are more conditions to account for:
- Type:
  - Phone: standard component, no additional props
  - Fax: the `not-clickable` prop in the component should be used
  - SMS: the `sms` prop in the component should be used 
  - TTY: the `tty` prop should in the component be used
- Phone number: This is the info that would go into the `contact` prop of the component
- Extension number: This is the info that would go into the `ext` prop of the component
- Label:
  - This is hidden from Drupal and we will not be changing the current label of "Phone" that is used on the FE

This update should be done on both Staff listing and Staff detail pages

## Acceptance Criteria
- [x] If type Fax is selected, number is not clickable
- [x] If type SMS is selected, number uses the `sms` prop
- [x] If type TTY is selected, number shows "TTY"
- [x] Exts are displayed and parsed correctly
- [x] The current label of "Phone" is not changed
- [x] The above work is done everywhere staff phone numbers are used:
   - [x] Leadership listing
   - [x] Staff detail pages
   - [x] VAMC detail pages when Staff is pulled in
- [x] Requires accessibility review

## QA
- [ ]  Need to test everything that uses the partial template for phone number paragraphs

**Comment by davidmpickett** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VAgov-Sitewide-Product-Team-6645154188a81a1f7a0a9464/issues/department-of-veterans-affairs/va.gov-cms/17865?planning-poker) with Zenhub @randimays @chriskim2311 @eselkin

**Comment by Agile6MSkinner** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VAgov-Sitewide-Product-Team-6645154188a81a1f7a0a9464/issues/department-of-veterans-affairs/va.gov-cms/17865?planning-poker) with Zenhub @jv-agile6

**Comment by Agile6MSkinner** [comment]
@laflannery This is refined other than the label stuff. Hoping to get into Sprint 14, so let's talk.

**Comment by laflannery** [comment]
@Agile6MSkinner I updated the Label information let me know if that makes sense

**Comment by SnowboardTechie** [comment]
After connecting with @eselkin and clearing up some of the confusing bits here we determined it would be smoothest and best for all if he ran with this and #17866 as it is familiar turf for him and leaves me room to tackle #19302

**Comment by jilladams** [comment]
Press Releases use the STaff profile content type to build contact information for the person responsible for the press release. Sometimes it includes only name and emial, but sometimes it includes a phone number. Right now that phone number isn't formatted / linked. Eli just needs to know the markup to use in order to handle that while handling this ticket. 

Example of the issue, where phone number appears: https://www.va.gov/augusta-health-care/news-releases/va-augusta-to-host-fall-claims-clinic-for-local-veterans/. 

In this instance: we want to standardize treatment to use:  `Phone:` and same treatment

**Comment by jilladams** [comment]
FYI @Agile6MSkinner the decision from team was to go ahead and handle that staff profile / press release treatment within this ticket.

**Comment by eselkin** [comment]
Also added Press releases because sometimes the same source of staff is used as a contact for a press release and it uses phone numbers as well. Introduced the phone number partial to the press release page with the phone number present.

**Comment by jilladams** [comment]
This has been deployed to prod behind a flipper. We've done everything we can to complete the work, so am closing ticket. Revealing it in production will happen via #19064 launch plan.
