### ISSUE TITLE
FE: Update VAMC Facility Mental health phone number to work with new fields

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#17867]
## Status 

1. Decide how to format / break down the work in #17861
2. Update the formatting of this ticket to mirror that

## Background
In #17862 the Mental health phone number field was updated to use the Phone paragraph type field (instead of the Telephone number field that it previously was). This means the FE query needs to be updated to pull the data properly from these new fields and then display on the FE.

## Description
The Phone paragraph type has more fields than what we previously had so there are more conditions to account for:
- Type:
  - Phone: standard component, no additional props
  - Fax: the `not-clickable` prop in the component should be used
  - SMS: the `sms` prop in the component should be used 
  - TTY: the `tty` prop should in the component be used
- Phone number: This is the info that would go into the `contact` prop of the component
- Extension number: This is the info that would go into the `ext` prop of the component
- Label:
  - The mental health phone number appearing in VAMC Mental health service accordions uses a label consistent with other displays of the number (if more context needed see #17373) 
  - Labels for other phone numbers (entered by local staff) appearing in the VAMC Mental health service accordion are not changed
  - Labels for phone numbers in other health services are not changed
  - Tests are updated or added as needed

## Acceptance Criteria
- [x] If type Fax is selected, number is not clickable
- [x] If type SMS is selected, number uses the `sms` prop
- [x] If type TTY is selected, number shows "TTY"
- [x] Exts are displayed and parsed correctly
- [x] The current label of "Mental health care" is not changed
- [x] The above work is done everywhere mental health phone numbers are used:
   - [x] VAMC System pages
   - [x] VAMC Locations List
   - [x] VAMC Facility Detail pages
   - [ ] Facility Locator
- [x] Requires accessibility review

**Comment by davidmpickett** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VAgov-Sitewide-Product-Team-6645154188a81a1f7a0a9464/issues/department-of-veterans-affairs/va.gov-cms/17867?planning-poker) with Zenhub @chriskim2311 @eselkin @randimays

**Comment by Agile6MSkinner** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VAgov-Sitewide-Product-Team-6645154188a81a1f7a0a9464/issues/department-of-veterans-affairs/va.gov-cms/17867?planning-poker) with Zenhub @jv-agile6

**Comment by Agile6MSkinner** [comment]
@laflannery ready other than labels ACs

**Comment by laflannery** [comment]
@Agile6MSkinner I also updated this ticket as well as added another AC to make sure that these numbers get updated everywhere. I'm not positive these are the only 3 places this number shows up though, someone should double check me

**Comment by davidmpickett** [comment]
@SnowboardTechie  For the new AC about the label that appears in some Mental Health service accordions here are a couple live examples of various cases:

Example | Appointment use main phone | Contact info use main phone | Labels to change
-- | -- | -- | --
[San Luis Obispo VA Clinic](https://www.va.gov/greater-los-angeles-health-care/locations/san-luis-obispo-va-clinic/#mental-health-care) | Off | No, do not display | 0
[Fort Meade VA Clinic](https://www.va.gov/maryland-health-care/locations/fort-meade-va-clinic/#mental-health-care) | Off | Yes, display  | 1
[Venango County VA Clinic](https://www.va.gov/erie-health-care/locations/venango-county-va-clinic/#mental-health-care) | On | No, do not display | 1
[Fredericksburg VA Clinic](https://www.va.gov/richmond-health-care/locations/fredericksburg-va-clinic/#mental-health-care) | On | Yes. display | 2

**Comment by davidmpickett** [comment]
@SnowboardTechie I realized there is another variation that might be helpful for you to be aware of. The chart above covers accordions that only contain 1 "service location." The chart is comprehensive for the possibilities for Main phone in a single service location, but it's possible to have up to 3 "service locations". Here are some live examples of accordions with 2 service locations:

- https://www.va.gov/shreveport-health-care/locations/overton-brooks-veterans-administration-medical-center/#mental-health-care
- https://www.va.gov/bedford-health-care/locations/edith-nourse-rogers-memorial-veterans-hospital/#mental-health-care
- https://www.va.gov/tampa-health-care/locations/temple-terrace-va-clinic/#mental-health-care

I'm pretty sure the Content Build partial templates are nested in a way that you'll only have to update one of two spots, but just wanted to give you a sense of the variety of possibilities.

**Comment by eselkin** [comment]
@laflannery and I discussed that Facility Locator MH phone numbers come from Lighthouse not CMS/Drupal and the data passed to LH has been transformed from the object we get in graphql to a string that LH can accept, so it only knows how to pass back a string.

**Comment by jilladams** [comment]
This has been deployed to prod behind a flipper. We've done everything we can to complete the work, so am closing ticket. Revealing it in production will happen via #19064 launch plan.
