### ISSUE TITLE
Fix the ability to link to unpublished Drupal pages with a node ID 

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-cms#17872]
## User Story or Problem Statement

As a content author building out new Drupal pages, I need to be able to link to these pages easily using node IDs from within Drupal.

Drupal no longer allows an editor to link with a node ID to an unpublished page by typing in the H1 of the page.  

## Description or Additional Context 
When creating a link within Drupal, the CMS used to allow you to type in the H1 of an unpublished page and it would pull up the node ID. Now if you start typing the H1 of an unpublished page, Drupal can't find it. In order to set up a link you need to manually add the node ID by typing **/node/[nodeID]** in the link field. Not sure why or when Drupal lost this functionality but it's much easier for an editor to find the node by typing the H1.
Note that the old way of adding a node ID still works with published pages.

## Acceptance Criteria
- [ ] Tech discovery on this regression is completed and issue is understood. 
- [ ] A path forward for a fix is identified

**Comment by EWashb** [comment]
@gracekretschmer-metrostar Randi H. found a regression in the CMS. This isn't on fire, but we should see about building in this tech debt to an upcoming sprint. This used to work so I'm assuming a regression happened at some point in the last month or so

**Comment by gracekretschmer-metrostar** [comment]
@keisterj-oddball to be added to do some discovery work to understand how this originally happened and how it was discovered.

**Comment by anantais** [comment]
@RLHecht - do you know when you first noticed this issue (approximately)? I have tried a lot of things to fix this with nothing working yet. Right now, I am trying to figure out if this was an issue before the Drupal 10 upgrade or after.

**Comment by anantais** [comment]
Update: 

The problem seems to be with Linkit  but so far I have not found anything obviously wrong. There is a checkbox in Linkit config for showing unpublished nodes (and that is checked).  I tried changing permissions, reverting to older modules and looking through recent updates. At this point I am wondering if another module is an issue so I will look a little further back in the history of our module updates.

**Comment by anantais** [comment]
This seems like it could be an issue related to the Drupal 10 upgrade. The patch I applied has been around for a while but was re-released for Drupal 10. It does not appear as though we were using a patch before then.

Here is the issue - https://www.drupal.org/project/linkit/issues/3049946

@keisterj-oddball

**Comment by gracekretschmer-metrostar** [comment]
@anantais this has been completed, correct? I wanted to confirm before I closed.
