### ISSUE TITLE
SPIKE: VBA: Consider e2e test plan and propose path forward

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#17882]
Collab Cycle has an e2e test requirement for Staging Review. We have previously made the case successfully that we won't have e2e tests available at Staging Review but will add them once products ship and content is entered in Drupal. 

Factors to consider as we figure out our plan: 
* For e2e tests, they require content to exists in order to validate that content. 
* For Drupal content types: Drupal content is unreliable for automated test purposes. Live content can be changed and break a test anytime. 
* Mocking data: From FE perspective, it's hard to mock representative data to come through content-build for e2e validation. 

We need to get ourselves aligned on our plan for VBA, OR, what we need to present to the Collab Cycle for consideration in their process when they're dealing with Drupal-driven products. This should include considering e2e test behavior, requirements, and value for Drupal-driven content types generally and VBA specifically. 

## ACs

- [ ] e2e testing considerations are documented in ticket
- [ ] Proposal for VBA Regional Offices path forward is documented
- [ ] Proposal is reviewed with PM for consideration re: any changes we need to request from Collab Cycle or tickets that should be created for follow up work

**Comment by davidmpickett** [comment]
@jilladams You called this a dupe, so I am closing
