### ISSUE TITLE
Update VBA Regional Office Pre-Prod Pages to use va-icon in place of fontawesome

### ISSUE THREAD

**Issue by eselkin** [department-of-veterans-affairs/va.gov-cms#17886]
## User Story or Problem Statement

`<va-icon>` is replacing `<i>` font awesome tags. Facility Locator and Detail Pages must replace font awesome with va-icon ASAP.

## Steps for Implementation

1. Change VBA Regional Office Page
    1. Update `src/site/facilities/vba_social_links.drupal.liquid` (7x)
       - Reminder to use the new X icon for this update ~and update the text of the link to say "X (formerly Twitter)"~
    2. Nearby VA Locations - will be updated in Nearby Vet Centers - because merged those sub-dependencies

## Acceptance Criteria
- [ ] VBA Regional Office Page has no Fontawesome icons
- [ ] Requires design review
- [ ] Requires accessibility review

**Comment by randimays** [comment]
Successfully validated on this page in pre-prod: http://preview-prod.vfs.va.gov/preview?nodeId=4171

<img width="604" alt="Screenshot 2024-06-06 at 12 03 14 PM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/19175324/24f202b6-6d7b-420b-8cd4-72a669166646">
<img width="502" alt="Screenshot 2024-06-06 at 12 03 28 PM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/19175324/86a5506d-20d2-44bc-9387-7e6a34e389af">

Note: there are still issues with the "X" icon but this is something DST is working on.

Closing!
