### ISSUE TITLE
[Outreach & Events] Send back the facility name so it can be displayed on the FE in a link

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-cms#17888]
## Description
In support of the FE ticket "Update Events "[See more events" link to use more descriptive links #15766](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15766#top)", Drupal needs to send back the facility name so it can be displayed in links. As an example, VAMC facility name (i.e. "Portland health care")

Want to see more events offered at Example VAMC? [Go to VAMC events calendar]

[Brief Slack discussion]( https://dsva.slack.com/archives/C52CL1PKQ/p1713285657832429)

_Note: We know that the facility names don't match what's in Drupal, however we aren't going to try to fix that at this time. Another ticket will be created later to address that._

### User story

**AS A** Veteran, their caregiver, family member or survivor
**I WANT** to see a user friendly (actual) facility name in the event link I click
**SO THAT** I'm not confused by a name different than what is noted in the event displaying in the link

## Acceptance criteria

- [ ] Include a graphQL snippet for the front-end 
- [ ] The front-end on VA.gov has access to the actual facility name

**Comment by FranECross** [comment]
@randimays Here is the ticket for the drupal work in support of your see more events link FE ticket. I realized I should have had it ready for Sprint planning this morning. 🫤 @dsasser Will you please async refine this when you have a moment, and then I'll put it at the top of the Ready column, just in case you have bandwidth in the new sprint to take care of it. Thanks!

**Comment by dsasser** [comment]
## Update 5/13/24

No code changes are necessary for this ticket. Instead, we can modify the existing Events queries to include the office title. Randi already has a branch with her pending FE changes, so I pushed the changes [there](https://github.com/department-of-veterans-affairs/content-build/compare/main...15766-see-more-events).


```diff
diff --git a/src/site/stages/build/drupal/graphql/nodeEvent.graphql.js b/src/site/stages/build/drupal/graphql/nodeEvent.graphql.js
index cbc4d630b..c894e8d7a 100644
--- a/src/site/stages/build/drupal/graphql/nodeEvent.graphql.js
+++ b/src/site/stages/build/drupal/graphql/nodeEvent.graphql.js
@@ -132,6 +132,7 @@ const nodeEvent = `
               entityBundle
               entityId
               ... on NodeOffice {
+                title
                 fieldBody {
                   value
                   format
@@ -158,6 +159,7 @@ const nodeEvent = `
               entityBundle
               entityId
               ... on NodeOffice {
+                title
                 fieldBody {
                   value
                   format
@@ -331,6 +333,7 @@ const nodeEventWithoutBreadcrumbs = `
               entityBundle
               entityId
               ... on NodeOffice {
+                title
                 fieldBody {
                   value
                   format
@@ -357,6 +360,7 @@ const nodeEventWithoutBreadcrumbs = `
               entityBundle
               entityId
               ... on NodeOffice {
+                title
                 fieldBody {
                   value
                   format
```
