### ISSUE TITLE
Update Facility Locator and Detail Pages to use va-icon in place of fontawesome

### ISSUE THREAD

**Issue by eselkin** [department-of-veterans-affairs/va.gov-cms#17884]
## User Story or Problem Statement

`<va-icon>` is replacing `<i>` font awesome tags. Facility Locator and Detail Pages must replace font awesome with va-icon ASAP.

## Steps for Implementation

1. Facility Locator widget changes
    1. Update `src/applications/facility-locator/components/SearchControls.jsx` (2x)
    2. ~Update `src/applications/facility-locator/components/search-results-items/EmergencyCareResult.jsx` (1x)~
       - ~Decision was made to update to use the proper component https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17887 rather than only updating the icon~
    3. ~Update `src/applications/facility-locator/components/search-results-items/UrgentCareResult.jsx` (1x)~
       - ~Decision was made to update to use the proper component https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17887 rather than only updating the icon~
    4. Update `src/applications/facility-locator/components/search-results-items/common/Covid19Alert.jsx` (1x)
    5. Update `src/applications/facility-locator/components/search-results-items/common/LocationDirectionsLink.jsx` (1x)
    6. Update `src/applications/facility-locator/components/search-results-items/common/LocationPhoneLink.jsx` (1x)
2. Facility Locator Detail Pages Changes
    1. Update `src/applications/facility-locator/containers/FacilityDetail.jsx` (1x)
    2. Update `src/applications/facility-locator/containers/ProviderDetail.jsx` (6x)

## Acceptance Criteria
- [ ] Fontawesome icons are removed from Facility Locator
- [ ] Fontawesome icons are removed from Detail Pages
- [ ] Update and run existing test(s).
- [ ] If additional tests are needed, stub a ticket to note this for future work.
- [ ] Requires accessibility review

**Comment by laflannery** [comment]
@eselkin [This is the ticket](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17887) that I have to update the alert component for the Emergency and Urgent Care results. I just want to confirm that this would be for these 2 files:
- src/applications/facility-locator/components/search-results-items/EmergencyCareResult.jsx 
- src/applications/facility-locator/components/search-results-items/UrgentCareResult.jsx

**Comment by eselkin** [comment]
Yes. Those two files.

**Comment by laflannery** [comment]
Verified on prod:
![Screenshot 2024-06-14 at 3 48 10 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/106678594/7a90c148-3d19-447c-ac14-729d96ae4fe6)
