### ISSUE TITLE
Improve the editor UX by adding link to VBA Facility Service workflow from the VBA facility node

### ISSUE THREAD

**Issue by davidmpickett** [department-of-veterans-affairs/va.gov-cms#17885]
If at all possible, we should improve the editor UX slightly by adding more support via navigation to the VBA Facility Service workflow from the VBA facility node before staging review
- i.e., Replace "Facility services are created on a different page." with "Add or edit Facility services [here](VBA service link)"

![68747470733a2f2f7a682d66696c652d70726f64756374696f6e2d707269766174652e73332e616d617a6f6e6177732e636f6d2f7675397370766f6a706962726f71386c78766f726f6c37757162666f3f726573706f6e73652d636f6e74656e742d646973706f736974696f6e3d696e6c696e6525334225](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/b4a3da4e-c204-4347-b65d-13489831723b)

_Originally posted by @mmiddaugh in https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16268#issuecomment-2057694364_

## Plan
This is an interim plan. Eventually we want to adopt the paradigm we will be using for Vet Center Facility Services out of #17708.

## ACs

- [x] UX provides final copy for 2 links
     * On VBA Facility node form: Facility Services section should link to node add form for VBA Facility Service, as a link with parameters that point to the correct Section  https://prod.cms.va.gov/node/add/vba_facility_service
    *  Also want to show a link for Services that exist for this facility: https://prod.cms.va.gov/admin/content?title=Portland+Veteran+Readiness+and+Employment+Office&type=vba_facility_service&moderation_state=All&owner=All
- [x] Editors are directed to the correct area to create VBA Facility Services, when editing a VBA Facility
- [x] Design review of build

**Comment by davidmpickett** [comment]
Once #18003 is complete, we might be able to port that interface to VBA

**Comment by jilladams** [comment]
Stopgap still has value to Editrors in the interim

**Comment by omahane** [comment]
The solution will be something like how it is for nonclinical:
- field.field.node.vha_facility_nonclinical_service.field_administration.yml
```
  epp:
    value: '[current-page:query:field_administration]'
```

**Comment by omahane** [comment]
@davidmpickett Is this language sufficient for these links:
> Facility services
> To create a facility service, visit the [add VBA facility service form](https://va-gov-cms.ddev.site/node/add/vba_facility_service?field_administration=1088&field_office=4237).

> To see all services for this facility, visit the [content search page](https://va-gov-cms.ddev.site/admin/content?title=Portland+VA+Regional+Benefit+Office&type=vba_facility_service&moderation_state=All&owner=All) (filtered for services of this facility).

![Screenshot 2024-07-02 at 1 04 07 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/766573/b4414b8f-0d07-4bb9-ad9e-b50106e5c763)

**Comment by davidmpickett** [comment]
[Create a new service for this facility (opens in new window)](url).

[Manage existing services for this facility (opens in new window)](url).

**Comment by omahane** [comment]
Got it.
![Screenshot 2024-07-02 at 2 56 56 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/766573/65949cd6-23e6-4964-967d-87d8d806920b)

**Comment by davidmpickett** [comment]
Verified on prod!

<img width="865" alt="Screenshot 2024-07-03 at 5 36 10 PM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/c2b0811b-e918-47fa-9cc9-fc745c699c5a">

**Comment by jilladams** [comment]
The new links are working, but there's a weird behavior happening related to this issue where the "cant' find what you're looking for" section is also strangely linking to the facility service area. Visible on Tugboat here: 
https://main-2pegzvqcy77ynmcultaityqtlrpfbfoo.demo.cms.va.gov/node/4105/edit#undefined

**Comment by omahane** [comment]
@jilladams @Agile6MSkinner I see what happened here. I've got a PR for this: https://github.com/department-of-veterans-affairs/va.gov-cms/pull/18509

**Comment by omahane** [comment]
![Screenshot 2024-07-18 at 8 46 39 AM](https://github.com/user-attachments/assets/b10d8ef5-3579-4e93-900a-23caabab001d)
Verified on prod.

@Agile6MSkinner @davidmpickett This can be closed.
