### ISSUE TITLE
[EPIC] Vet Center Differentiation

### ISSUE THREAD

**Issue by davidmpickett** [department-of-veterans-affairs/va.gov-cms#17893]
# Vet Center Differentiation on Facility Pages

## Objective
Clearly differentiate Vet Centers from VA Medical Centers on individual facility pages to reduce confusion among veterans, family members, and caregivers after they've used the facility locator.

## Background
Veterans often confuse Vet Centers with VA Medical Centers when viewing facility pages, leading to misunderstandings about available services and potentially missed opportunities for care. Although Vet Centers are under VHA, they have a distinct identity as a warm, welcoming, non-clinical front door to the VA where Veterans, service members, and their families can access mental health counseling and other services.

Stakeholder feedback has emphasized the need to overcome common misconceptions, including the frequently expressed thought that Vet Centers are VA medical centers or veterinary clinics. RCS has requested consideration of their brand colors and logo, based on their research and brand analysis process. This process focused on representing the services they offer, the clients they serve, and their staff, who are often Veterans themselves.

## User Stories
- As a veteran, I want to quickly understand the unique services offered by Vet Centers when I view a facility page so I can decide if it's the right resource for me.
- As a family member, I want to easily distinguish between Vet Centers and VA Medical Centers on facility pages so I can guide my veteran to the appropriate facility.

## Proposed Solution
1. Add a Vet Centers logo at the top of Vet Center facility pages
2. Add a concise explainer at the top of Vet Center facility pages
3. Add evocative graphic at the top of Vet Center facility pages
4. Change "Referral Services" to a less equivocal term.

## Constraints
- Must align with RCS brand colors and logo guidelines
- Should emphasize Vet Centers' non-clinical, welcoming nature
- Changes limited to facility pages, not the facility locator itself

## Out of Scope
- Changes to VA Medical Center facility pages
- Modifications to the facility locator search functionality
- Marketing campaigns outside the website

### Key Differentiators for Vet Centers
- Offer a warm, welcoming, non-clinical environment
- Provide mental health counseling and other specialized services
- Staffed often by Veterans, offering a Veteran-to-Veteran approach
- Separate from traditional VA medical facilities
- Offer individualized treatment plans
- Veterans can access services at Vet Centers without having VA Health Care Benefits
- They do not share any PII/PHI or other records with the VA at large

### Design Considerations
- Utilize RCS brand colors and logo to establish a distinct identity
- Incorporate photos to showcase the unique environment and services
- Clearly explain the types of services offered and not offered
- Highlight the non-clinical, Veteran-focused nature of Vet Centers

## Past research
<details>
<summary>1. When looking at Vet Center pages, most Veterans thought they were looking at a medical
facility’s website.</summary>

- Findings from [Vet Center Product Usability Study - V2](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/vet-centers/initiatives/2020-2021-modernization/discovery/client-usability-tests/Vet-Centers-Usability-V2-Research-Findings.pdf), Feb 2021
- Most Veterans thought they were looking at a medical facility’s website.
- Veterans continue to equate “Referral services” with “getting a doctor's
referral”. This may be perpetuating the notional that this is a medical facility.

</details>
<details>
<summary>2. Vet Centers aren’t well known among Veterans. Clients of Vet Centers expressed being
“separate from VA” as a key benefit of Vet Centers.</summary>

- Findings from [Vet Center - Client Interviews](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/vet-centers/initiatives/2020-2021-modernization/discovery/veteran-interviews/research-findings.md), October 2020
- Vet Centers are not well known among Veterans.
- Clients had a favorable view of Vet Centers.
- Clients expressed being “separate from VA” as a key benefit of Vet Centers
- Clients value the Veteran to Veteran approach to counseling, outreach and
staffing of Vet Centers
</details>

<details>
<summary>3. Vet Centers could increase efforts to promote its distinguishing qualities, such as having
individualized treatment plans.</summary>

- Findings from the [Vet Center Brand Analysis](https://github.com/department-of-veterans-affairs/va.gov-team/blob/801e368b7d65df9496b6381c6ad423e37a7d0a1c/products/facilities/vet-centers/initiatives/2020-2021-modernization/VetCenters_BrandAnalysisReport_03272020.pdf#L2), March 2020
- The variety of services and individualized treatment plans are largely recognized
for being unique and distinguishing qualities of Vet Centers.
- Often confused with VA medical centers and CBOCs, Vet Centers have not yet
established themselves as an entity distinct from VA.
- Vet Centers could increase efforts to promote its most distinguishing and highly
praised qualities, which are often unknown to different stakeholder groups.
</details>

**Comment by Agile6MSkinner** [comment]
All work planned for this Q3 iteration has been completed, so I am closing the ticket.
