### ISSUE TITLE
Design exploration: Distinguish Vet Center pages from medical facilities

### ISSUE THREAD

**Issue by thejordanwood** [department-of-veterans-affairs/va.gov-cms#17891]
## Description 

For [Vet Centers 2.0](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17661), explore how Vet Centers could be distinguished from medical facilities. In [the research synthesis](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/vet-centers/initiatives/2024-vet-center-2.0/seconday-research-synthesis/Vet%20Center%20branding.md), past research indicates that when looking at Vet Center pages, Veterans thought they were looking at a medical facility's site. 

Although Vet Centers are under VHA, they have a distinct identity as a warm, welcoming, nonclinical front door to the VA where Veterans, service members, and their families can access mental health counseling and other services.

## Design 
[Vet Center Figma file](https://www.figma.com/file/EVd3q06ukAbVS61Q8MwRAT/Vet-Centers?type=design&node-id=1%3A900&mode=design&t=Wqtm0fJVxdIkoObB-1)

## Design considerations

- Consider adding Vet Center branding (brand colors and logo) to pages to help differentiate them form VAMCs.
- Consider making content changes to Vet Center pages to better emphasize the difference between Vet Centers and VAMCs. For example, changing the “Referral services” header.
- Consider how to emphasize that Vet Centers are "separate from VA". Vet Centers provide confidential counseling, outreach and referral services. 
- Consider how to effectively communicate that Vet Centers don't prescribe medication. Related ticket #10398 

<details>
<summary> Vet Center Logo </summary>

![VC_slogan_color-1](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/104526584/b4763ff9-ad97-4e9c-b749-1b64e0c3293e)

</details>

## Acceptance criteria

- [x] Design mockups exploring different options are documented in Figma
- [x] Review with UX Lead, Product, Engineering, Content, and Accessibility
- [x] Design is reviewed with and sent to VA UX Lead for final sign off
- [x] Follow up tickets are created
   - [x] CAIA intake
   - [x] Drupal interface design ticket #18125

**Comment by jilladams** [comment]
@thejordanwood to refine and flesh out design considerations before Sprint 3 planning on 5/1.

**Comment by jilladams** [comment]
@thejordanwood Dave and I looked at this ticket today and I had forgotten, so pinging in case you have as well, that we're hoping for more notes here before sprint planning.

**Comment by jilladams** [comment]
From planning: 
* Amanda will be out next Tues - Fri
* Amanda would be prefer to be along for the thought process 
* Please include Michael as you move through.

**Comment by thejordanwood** [comment]
Suggested changes are in the [Vet Center Figma file](https://www.figma.com/design/EVd3q06ukAbVS61Q8MwRAT/Vet-Centers?node-id=21%3A2&t=Wza6Cmx5kM3sZmpF-1). Some notable changes are:

- Adding the Vet Centers logo to the top of the page
- Adding a summary box to the top of the page that describes what Vet Centers do
- Moving the "How we're different than a clinic" section below the contact info 
- Changing the "Referral services" to "Recommendation services" or something similar. A final decision can be made on this later.

**Comment by thejordanwood** [comment]
Next steps for this:

- Create an intake ticket for CAIA to review the content changes. 
- Create a Drupal ticket in the future. We can create Drupal designs at the end of the FE work, that way we can capture any changes at once. 

This could be task for Michael, to get him comfortable with the CAIA process. He could also create a Drupal design ticket stub if he has an idea of where to put that within our epics/however he wants to structure everything (or I'm perfectly willing to do this too). 

cc: @jilladams @davidmpickett (I can't find Michael in Github to tag him)

**Comment by davidmpickett** [comment]
@Agile6MSkinner ^^

**Comment by jilladams** [comment]
Discussed this status with @Agile6MSkinner . We talked through who CAIA is, their [intake template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=strelichl%2Ccoforma-terry&labels=sitewide+CAIA&projects=&template=sitewide-CAIA-intake-form.md&title=%5BCAIA+Intake%5D+%3CTeam+Name%3E%3A+%3CInitiative+Name%3E) is here. He has a sense of what the copy changes are, but Michael if you need clarity, reach out to Jordan for help to collate those.

Jordan, Michael is still working on Zenhub access (blocked by Platform currently) so could you make the Drupal design ticket and stick it in this epic? Discussed that with him live, and he'll hop into ticket making as soon as he has Zenhub.

**Comment by jilladams** [comment]
re: ACs, engineering review was requested here: https://dsva.slack.com/archives/C0FQSS30V/p1715704793111279

Will roll into Sprint 4, just given eng bandwidth relative to SL launch / end of sprint activities.

**Comment by thejordanwood** [comment]
Thanks @jilladams and @Agile6MSkinner! I've created that follow up Drupal ticket. 

@Agile6MSkinner I can call out the copy changes using Figma comments if that would be helpful.

**Comment by jilladams** [comment]
@eselkin @omahane This feels easy to lose the engineering review. Should we schedule time or assign you to ticket to reflect we need to get that done? I didn't see anything in UX sync today that went beyond rearranging existing data in the FE template, but lemme know if you disagree. (notes here: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17669#issuecomment-2115557382)

**Comment by eselkin** [comment]
It didn't appear in UX sync that there was new data (except for the combined accordions in Dave's stuff), only rearrangement.

**Comment by thejordanwood** [comment]
@eselkin @omahane As Eli pointed out, I think the summary box will have FE and Drupal implications. If that raises any red flags just let me know!

**Comment by jilladams** [comment]
Talked to Jordan today re: status here: 
1. She's closing loop with Christian about Drupal technical implementation
2. CAIA intake ticket is outstanding and is an AC. On this: 
  * The main change right now that we want them to review is the Summary box we are adding to the page. 
  * CAIA is backlogged on things so on the one hand it might make sense to make one bigger ticket for allt he things we will need reviewed, later (including IA?). On the other hand, it might be smart to get it filed and get on their radar now. 

I'm gonna ask CAIA.

**Comment by omahane** [comment]
> @eselkin @omahane As Eli pointed out, I think the summary box will have FE and Drupal implications. If that raises any red flags just let me know!

At first (and second) blush, I think this summary box could be Centralized Content.

**Comment by thejordanwood** [comment]
@mmiddaugh I think we'll stick with the horizontal logo without words for now, but it would be an easy change if we decide to switch it out later

**Comment by thejordanwood** [comment]
@jilladams @Agile6MSkinner From [this Slack thread](https://dsva.slack.com/archives/C01K37HRUAH/p1716326336725279), it looks like CAIA would prefer one, larger ticket that includes all of this work. How do we want to handle the CAIA intake ticket so that this ticket can be closed?

**Comment by jilladams** [comment]
From UX sync: @Agile6MSkinner to file the CAIA ticket and link it / close this when that's done. Related slack thread: https://dsva.slack.com/archives/C0FQSS30V/p1716497949983119?thread_ts=1716496708.964969&cid=C0FQSS30V
