### ISSUE TITLE
FL Alert in Emergency Care Filter is updated to component

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#17913]
## Description
An imposter alert was found in the Emergency Care filter:

![Screenshot 2024-04-22 at 1 23 36 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/106678594/aac8075f-6b99-4278-87e9-33786bb31a89)

This alert should be using the [Alert - slim v3 component](https://design.va.gov/components/alert#examples---slim-alert---v3)

## Acceptance Criteria
- [x] Alert in the Emergency Care filter is updated to use the slim v3 component
- [x] Update and run existing test(s).
- [x] If additional tests are needed, stub a ticket to note this for future work. (N/A)
- [x] QA is completed on all supported browsers
- [ ] Requires accessibility review

**Comment by eselkin** [comment]
What level of alert should we use? "info" "warning" "error"
I'm thinking warning, but info is the similar color.

**Comment by eselkin** [comment]
@laflannery @thejordanwood @jilladams any of your opinions are better than mine ^

**Comment by jilladams** [comment]
Agree: Info. We can always change this later as needed.

**Comment by jilladams** [comment]
Present in prod! Closing. 
![Screenshot 2024-06-04 at 2 06 15 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/85581471/7c420949-40fc-48a1-b08f-432b042a3db1)
