### ISSUE TITLE
Support Design System initiative to align with U.S. Web Design System v3

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-cms#17915]
## Value to Veterans
This initiative and timeline are largely driven by the Design System. 
The work with the most Veteran facing value is updating product components to the highest version available which will allow us to deliver a more accessible and consistent Veteran experience. 

## Headlines
**Business stakeholder:** Design System Team
**OCTO owner(s):** Matt Dingee, Dave Conlon, Michelle Middaugh
**Is request tracked to an event or Congressional deadline?** - No

## Scope
**Update existing V1 components to use Web Design System v3 [#17653](https://app.zenhub.com/workspaces/sitewide-facilities-639f5253e4b702a32376339e/issues/gh/department-of-veterans-affairs/va.gov-cms/17653)**
- v1 components on facility pages must be upgraded to their V3 counterparts before the Design system team deprecates v1 on May 3, 2024. 

**Audit products for product impact in preparation for updated typography changes [#17806](https://app.zenhub.com/workspaces/sitewide-facilities-639f5253e4b702a32376339e/issues/gh/department-of-veterans-affairs/va.gov-cms/17806)**
- The Design system team plans to ship updated typography on May 8. This may cause a visual impact to facility pages which will need to be mitigated before/when typography update ships.

**Adoption of va-icon due to deprecation of Font Awesome [#17722](https://app.zenhub.com/workspaces/sitewide-facilities-639f5253e4b702a32376339e/issues/gh/department-of-veterans-affairs/va.gov-cms/17722)**
- The Design System Team is deprecating Font Awesome by the end of May. Facility pages need to migrate to use va-icon. 

**Adopt V1 & V3 components to replace custom ("imposter") code implementations [#17655](https://app.zenhub.com/workspaces/sitewide-facilities-639f5253e4b702a32376339e/issues/gh/department-of-veterans-affairs/va.gov-cms/17655)**
- This work is largely tech debt based on the vintage of facility products and the components which were available for use at that time.

**Assess impact on facility products/pages and prepare for deprecation of 768px breakpoint and adoption of 640px breakpoint [#17762](https://app.zenhub.com/workspaces/sitewide-facilities-639f5253e4b702a32376339e/issues/gh/department-of-veterans-affairs/va.gov-cms/17762)**
- The Design System Team will be deprecating the 768px breakpoint and adding a 640px breakpoint (tentatively) in mid-August.

## Objectives and key results
Goal: Minimize product and page impact as result of Design System's alignment with WDS 3.0
Possible OKRS: # of sprint injections caused by foundational changes

**Comment by mmiddaugh** [comment]
**Update 5.24.2024**

Component upgrade V1 to v3, Deadline: May 8 
- Aside from breadcrumb changes, all known work to upgrade components from v1 to v3 is complete for Public Websites and Facilities products.
- All phone numbers that can use the component have been successfully updated

Audit products in staged Typography environment
- Phase 1: UX and engineering validation: complete.
- Phase 2: not yet started 

Update VA icons
- In progress

Replace custom code (imposters) with v1 or v3 components
- Public Websites products are fully v3 compliant where currently possible (some adoptions are not possible due to DS blockers)
- Facilities product updates are in progress

Prepare for 768 breakpoint replacement by 640 breakpoint 
- not started

**Comment by jilladams** [comment]
@mmiddaugh FYI That I added the Public Websites related epics into this higher level tracking epic today and added PW tag.  (As far as I'm aware, we didn't / don't have a parallel tracking epic on the PW side already.)

**Comment by jilladams** [comment]
(Sidebar: 223 points completed for this effort so far 🤯 )

**Comment by mmiddaugh** [comment]
**Update 6.7.2024**

- 95 of 112 Issues completed
- 181 of 228 Epic points completed

**Comment by mmiddaugh** [comment]
The bulk of this initiative is now complete
