### ISSUE TITLE
Appointments header is showing on VBA services without content

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#17925]
## Background
I added to test services to a VBA facility and in one instance the "Appointments" header showed when I'm not sure it should be because there was no content below it.

## Description
<details><summary>Happy path that works properly</summary> 
I added a VBA service with the following options:
- Service options:
  - Office visits: First-come, first-served
  - Virtual: First-come, first-served
- Appointments:
  - Remove text
  - Uncheck Facility phone number
  - No additional phone numbers
  - No online scheduling

On the FE, there was no appointments info at all, which was expected:
![Screenshot 2024-04-23 at 9 52 15 AM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/106678594/55f824a9-2b9a-41ce-aa60-e7a38c812968)

</details>

### Bug
However, in the second scenario I did see FE info and I feel like I shouldn't have:
- Service options:
  - Office visits: Yes, with or without and appointment
  - Virtual: First-come, first-served
- Appointments:
  - Remove text
  - Uncheck Facility phone number
  - No additional phone numbers
  - No online scheduling
On the FE, there was an **"Appointment" heading and then no content underneath it:**
![Screenshot 2024-04-23 at 9 54 12 AM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/106678594/290de0a2-d45d-4439-80bf-89f80b06243b)

Is this heading conditional based on the Service option choices? And if so, would we be able to but some conditionals into Drupal to validate against this FE scenario? or at the very least maybe update the helptext - For example "If you have indicate that appointments are available or necessary please make sure to do something"? Or is the better option to conditionalize the header against something else?

## Acceptance Criteria
- [x] If all the values below a header are empty, on either VAMC or VBA Regional Office, don't display the Appointments header
- [ ] Requires accessibility review

**Comment by jilladams** [comment]
From refinement: 
* Previously Dave tried to come up with a logic matrix for when to / not to display the Appointments header. This might be an exception. The task here is to revisit the matrix, figure out this case, and handle it.

**Comment by davidmpickett** [comment]
Logic matrix is maintained in Figma: https://www.figma.com/file/eECF81nwktbnKX889HiKhl/VBA-Content-Specs?type=design&node-id=208-714&mode=design

Static copy for ease of references

![Logic for displaying Appointment Info on Front End](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/77a5ec03-71cb-4d93-b4e4-2278e0664b04)

However, this matrix was really meant to show scenarios in which all the Appointment fields should definitely be Hidden (because editor has indicated that appointments are not possible). The Show scenarios still should account for the possibility of no appointment data being entered and therefore the Header shouldn't show.

Ideally, in the scenario Laura has described that what we should actually be doing is enforcing Drupal input. If the Editor has indicated that Appointments are possible, there should be SOMETHING in the appointment section (a phone number, online scheduling, or some text). I have a ticket where I have been gathering some of the possible conditional validation situations: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17425

I think this ticket can be refined as a FE ticket to be defensive against this scenario.

**Comment by jilladams** [comment]
(Just read this title as "Appointments header is showing on VBA services without con**s**ent" and had to double take for a sec.)

**Comment by laflannery** [comment]
The issue is actually simpler than this and the matrix really should have nothing to do with the display of this header.

- The "Appointments" header should only appear if content in the Drupal Appointments section has been entered because this is the relevant information that would apply to the Appointments section
- We also need to address the heading levels/display of this information. This was something we put off for MVP but it needs to be addressed
  - For example, when we have an H4 Appointments heading and then an H4 phone heading, it's not clear that this phone number is for making appointments

**Comment by mmiddaugh** [comment]
Example in Prod with scenario Laura describes above, from [Coatesville VA Medical Center urgent care](https://www.va.gov/coatesville-health-care/locations/coatesville-va-medical-center/#urgent-care) 

<details>
<summary> Screenshot </summary>

<img width="553" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGdCQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1d26025e480faca922c4d8b86f802e88a11ead62/image.png" alt="image.png" />
</details>

**Comment by eselkin** [comment]
I agree about the h4s all being the same level, because of the way that I constructed the new conditionals (variables that can be reused), we can conditionally push the appointments phone numbers down to h5 if we want. But I don't know what the view of using headers that high are.

**Comment by davidmpickett** [comment]
> I agree about the h4s all being the same level, because of the way that I constructed the new conditionals (variables that can be reused), we can conditionally push the appointments phone numbers down to h5 if we want. But I don't know what the view of using headers that high are.

The long-term vision is to move away from headers for most of the interior of Service Accordions, so I would say let's definitely not add an additional tier of headers.

**Comment by davidmpickett** [comment]
I didn't have published content that met the specific criteria needed to test this on my Tugboat, so I just added some and am doing content release again. Should be here when ready: https://web-jdujzwgvp8kmj36hcfonqejlgtq5b6st.demo.cms.va.gov/birmingham-veteran-readiness-and-employment-office

**Comment by davidmpickett** [comment]
Verified on Tugboat 
![Screenshot 2024-07-08 at 9 55 21 AM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/a7dfcdd7-1e08-46f1-a9d3-21d46becf4bd)
