### ISSUE TITLE
URL Change for: North East Bexar VA Clinic

### ISSUE THREAD

**Issue by ian-sears** [department-of-veterans-affairs/va.gov-cms#17946]
### Implementation date
When does this request need to be live:
[07/01/2024] Confirmed. Monday July 1, 2024

### 1. Canonical URL change or
**Note: Canonical URL changes do not block the completion of the parent ticket. Once the URL redirect above has been deployed, the value to the Veteran is delivered. This ticket should be kept open until the URL change is verified, except in the case of a removal (as described below).**

## Parent Ticket
#17945

### Instructions for canonical URL change
- [x] Verify that the new URL for the facility is published and accessible on VA.gov.
- [x] Update the [CSV in Lighthouse](https://github.com/department-of-veterans-affairs/lighthouse-facilities/blob/master/facilities/src/main/resources/websites.csv) with the changed URL, maintaining the sorted order of the Facility API IDs.
- [x] Create a PR in the [lighthouse-facilities repo](https://github.com/department-of-veterans-affairs/lighthouse-facilities), tagging the Lighthouse team.
- [x] Post a message in the #cms-lighthouse channel in Slack, with an @mention to a Lighthouse team member.
- [x] Add the "Awaiting CSV" flag to the facility node with a revision log message that includes a link to this ticket.
- [x] Validate that the change has deployed by checking that the Facility Locator has been updated with the new url.
- [x] Update this ticket with a comment that the CSV change has been deployed.
- [x] Remove the "Awaiting CSV" flag to the facility node with a revision log message that includes a link to this ticket.

#### URL change example (update with actual ID and URL)
| Facility API ID  |  Full VA.gov URL |
| ---  |  --- |
| vha_671GV | https://www.va.gov/south-texas-health-care/locations/north-east-bexar-va-clinic |

**Comment by ian-sears** [comment]
Editor contacted the CMS Help Desk. They want this to be made live Monday, July 1.
Is it possible to push this through to lighthouse csv update in time?

**Comment by omahane** [comment]
> @omahane Editor contacted the CMS Help Desk. They want this to be made live Monday, July 1. Is it possible to push this through to lighthouse csv update in time?

@ian-sears Based on this [thread in Slack](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17946#issuecomment-2195095264), I suspect the earliest would be around July 4, perhaps the 3rd or the 5th.

**Comment by omahane** [comment]
The canonical URL has been deployed, [per Adam](https://dsva.slack.com/archives/C02BTJTDFTN/p1720015713762209?thread_ts=1719340047.322509&cid=C02BTJTDFTN), and verified by me on VA.gov.
