### ISSUE TITLE
[FE] [Income Limits] Implement updated system error message per VA guidance

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-cms#17948]
## Status

**[2024-05-07]** Unblocked by the UX ticket in the current Sprint with Jordan.

## Description  

There was a previous [ticket ](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17851)updating some error message wording on Income limits. Randi pointed out we have a system error that also included "Please" that should probably get updated.

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOGlPQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b7c90962664408f34b2fb1eac3576fbcbb16620f/image.png" alt="image.png" />

### User story

**AS A** PO/PM/CAIA person
**I WANT** the error messages in the Income Limits app to follow VA guidance
**SO THAT** Veterans, their caregivers, family members and survivors aren't confused by ambiguous wording
**AND** have clear instructions as to next steps when they encounter system errors while using the app

**AS A** Veteran, their caregiver, family member and survivor
**I WANT** the error messages in the Income Limits app to follow to inform and instruct me
**SO THAT** I'm not confused by ambiguous wording
**AND** I have clear instructions as to next steps when they encounter system errors while using the app

**Error message for both scenarios above:**

Your answer didn’t go through.
We’re sorry. There’s a problem with our system. Refresh this page or try again later.

## Acceptance criteria

- [ ] New error text implemented (from this [ticket](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17944#top))
- [ ] a11y Review

**Comment by randimays** [comment]
It is not possible to test these changes (force error states) in any other environment than local. The changes successfully deployed to staging and production, so calling this complete.
