### ISSUE TITLE
CMS Intake Form for Platform Collab Cycle

### ISSUE THREAD

**Issue by gracekretschmer-metrostar** [department-of-veterans-affairs/va.gov-cms#17942]
## User Story or Problem Statement
The CMS team needs to receive additional information about new or changed features within Drupal CMS to provide effective guidance and feedback to the product team owning the feature. 

## Description or Additional Context 
For some teams (e.g. Platform Security, Analytics) integrated within the collab cycle, the Platform Governance team sends a follow up Github ticket for teams to fill out with additional questions after the team submits the collab cycle's intake form. The purpose of these questions is to provide better context about the feature for the team impacted and begin a conversation of collaboration between the two teams. 

## Steps for Implementation
- Review the intake forms for Veteran Support, Analytics, and Platform Security 
- Schedule time with Analytics Team's PM
- Fold in CMS PO's requirements into questions for the CMS intake form
- Create supporting materials to provide enough context for teams to effectively answer the CMS intake form questions

## Acceptance Criteria
- [x] A list of questions for the CMS intake form that use language that product teams without CMS context could understand
- [x] A list of questions for the CMS intake form that provide the CMS team with enough context for the new or changed feature, but is not a burden on product teams to fill out. 
- [x] CMS intake form is documented in [Confluence](https://vfs.atlassian.net/wiki/spaces/PCMS/pages/3092447277/CMS+Platform+Collab+Cycle)

**Comment by gracekretschmer-metrostar** [comment]
Next steps: get documentation into Github and meet with Erika ahead of onsite next week.

**Comment by MDomngz** [comment]
Current draft is being worked in Confluence - we will migrate over to GH once we have approved the ticket
https://vfs.atlassian.net/wiki/spaces/PCMS/pages/3200942220/DRAFT+-+GH+Intake+Form
