### ISSUE TITLE
[UX] [Income Limits] Update wording of Income Limits system error to fit guidelines

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#17944]
## Status
**[2024-04-24]** Moved to Next Refinement; created and linked an FE ticket to implement the new text.

## Description
There was [a previous ticket](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17851) updating some error message wording on Income limits. Randi pointed out we have a system error that also included "Please" that should probably get updated. 
<img width="1024" alt="Screenshot 2024-04-23 at 4 15 43 PM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/19175324/b50e52d1-48d4-4eb5-a07c-adddf2bb8bf6">

After asking CAIA to confirm, Laura Willwerth had additional feedback of how this particular message should be updated to fit VA guidance better:

> - We try to be more specific about the error when possible, so the header on a system error like this would usually say something like "We can't [xyz intended action, like 'access your records'] right now"
> - In new error messages we avoid subtle idioms like "run into a problem" and "on our end," so the body text might say something like "We're sorry. There's a problem with our system. Try again later."
> - We try to provide a recovery step beyond "try again" when possible—that's usually a phone contact number specific to the tool or form

We should update this message to be as specific and have clear actions, depending on the use cases of when it could appear. 

### Questions
**_Note: see answers to questions in the comment field below._**
In order to write better text, we will want to get a better idea of the following:

- Why does this message appear? 
  - A very specific reason?
  - Multiple very specific reasons?
  - Some reason that isn't super important to the user other than the fact that their information was not submitted?
- When does this error appear?
  - Could it be when the user submits any of the questions or would it be only specific use cases?
- What should the user do when they see it?
  - Should the immediately try the Continue button again?
  - Should they wait 30 seconds and try again?
  - Should they go back to the beginning of the form and start over?
  - Something else?

## Acceptance Criteria
- [x] New error message text provided in this ticket for use in the separate FE ticket

**Comment by laflannery** [comment]
@FranECross This ticket will need UX work to create some clearer text and then FE can implement

**Comment by FranECross** [comment]
@randimays When you have time, will you please answer the questions in the ticket so that Jordan can come up with new text? I'll create an additional FE ticket and show it blocked by this one. Thanks in advance! cc @laflannery

**Comment by randimays** [comment]
@FranECross sure!

**- Why/when does this message appear?**
1) if zip code validation fails on the zip code screen because of a service error (e.g. nothing wrong with user input)
2) if income limits retrieval fails on the review screen because of a service error (e.g. nothing wrong with user input)

** -What should the user do when they see it?**
Because this relies on the uptime of vets-api, any number of things could be wrong:
- TIC gateway latency
- Non-TIC latency (e.g. vets-api is lagging for some reason)
- vets-api outage / maintenance

My recommendation is to have the user try again right away. It's possible we could track the number of times the service has been tried in one session, and if it's continually failing, we can change the error message to say something like "This service is down right now, try again later."

**Comment by davidmpickett** [comment]
Given that the logic is clearly spelled out in the comment above, I'd point this at a 1

**Comment by thejordanwood** [comment]
My suggestion is to keep this general enough to cover both instances where this message would appear. I've tried to use the advice in the ticket and also the guidance for [feedback messages](https://design.va.gov/content-style-guide/error-messages/feedback) in the DS. 

@laflannery and @randimays What do you think of changing the error message to this?

> **Your answer didn’t go through.** 
> We’re sorry. There’s a problem with our system. Refresh this page or try again later.

**Comment by randimays** [comment]
@thejordanwood This works for me 👍🏻

**Comment by laflannery** [comment]
This also sounds lovely to me, thank you @thejordanwood!

**Comment by FranECross** [comment]
Thanks, @thejordanwood ! I've updated the FE ticket and unblocked.

**Comment by thejordanwood** [comment]
Thanks everyone!
