### ISSUE TITLE
Audit CMS Collab Cycle Documentation

### ISSUE THREAD

**Issue by gracekretschmer-metrostar** [department-of-veterans-affairs/va.gov-cms#17941]
## User Story or Problem Statement
As a product team who needs to engage with the platform collab cycle, I need to understand how and where the CMS team is engaged in the process. 

## Description or Additional Context 
Previous iterations of the CMS team had created a CMS-specific collab cycle and that process is still represented in documentation in both the Confluence and Github. When the CMS team integrates into the platform's collab cycle, that out-of-date documentation needs to be removed, to prevent confusion for teams engaging with the platform's collab cycle. 

## Steps for Implementation
- Determine process to remove out-of-date  
- Review the documentation in Github and remove documentation that is out-of-date 
- Review the documentation in Confluence and remove documentation that is out-of-date

## Acceptance Criteria
- [ ] Out-of-date documentation has been removed from Github and Confluence
- [ ] The removal process is in compliance with VA standards and requirements

**Comment by gracekretschmer-metrostar** [comment]
Blocked until we get guidance from Erika about VA requirements for deleting and/or removing documentation from Github and Confluence.

**Comment by gracekretschmer-metrostar** [comment]
Erika's feedback: not process that we need to follow to remove content from Github or Confluence. 

Erika's question: are we going to use the platform's website for CMS collab cycle documentation.

**Comment by MDomngz** [comment]
@EWashb I believe that we should use the platform for CMS Collab Cycle docs/guidance. One less place they need to bookmark - plus, keeping it together will allow them to familiarize themselves with our process. 

cc: @gracekretschmer-metrostar
