### ISSUE TITLE
New VAMC Facility: North East Bexar VA Clinic

### ISSUE THREAD

**Issue by ian-sears** [department-of-veterans-affairs/va.gov-cms#17945]
## Intake
- [x] What triggered this runbook? (Flag in CMS, Help desk ticket, Product team, VHA Digital Media)
Trigger: Flag in CMS

- [x] Link to associated help desk ticket (if applicable)
Help desk ticket: [VAHELP-6959](https://va-gov.atlassian.net/browse/VAHELP-6959)

- [x] Name of submitter (if applicable)
Submitter: Justin Saucier

- [x] If the submitter is an editor, send them links to any relevant KB articles for the VAMC Facility product.
KB articles: [How to edit a VAMC Facility](https://prod.cms.va.gov/help/va-medical-centers-vamcs/about-locations-content-for-vamcs/how-to-edit-a-vamc-facility)
[How do I add a facility to my health care system?](https://prod.cms.va.gov/help/vamc/about-locations-content-for-vamcs/how-do-i-add-a-facility-to-my-health-care-system)

- [x] Link to facility in production:
Facility CMS link: https://prod.cms.va.gov/south-texas-health-care/locations/north-east-bexar-va-clinic
Facility API ID: vha_671GV

### New VAMC Facility
Please refer to the Knowledge Base article titled "How do I add a facility to my health care system?" for more information: https://prod.cms.va.gov/help/vamc/about-locations-content-for-vamcs/how-do-i-add-a-facility-to-my-health-care-system

#### CMS help desk steps
**Note: If the help desk is waiting on information from the facility staff or editor, add the "Awaiting editor" flag to the facility with a log message that includes a link to this ticket. Remove the flag when the ticket is ready to be worked by the Facilities team. Be sure to preserve the current moderation state of the node when adding or removing the flag.**
- [x] 1. Become aware that the new facility is now on the Facility API (typically, via a Flag, but this may come in as a helpdesk ticket).
- [x] 2. If the editor has followed the steps from the above Knowledge Base article and included which section and VAMC the facility belongs to (i.e. VA Pittsburgh), great! **Proceed to step 3.** If not, please check with the editor or VHA digital media regarding what section and VAMC it belongs to.
- [x] 3. Updates the Section (default is "VAMC facilities", but it should be a VAMC system in a VISN) and VAMC system field accordingly.
- [x] 4. Communicate with editor (cc VHA Digital Media) to give them go-ahead to complete the content, with this [KB article](https://prod.cms.va.gov/help/vamc/about-locations-content-for-vamcs/how-do-i-add-a-facility-to-my-health-care-system). (See sample notification email below)

<details><summary>Email template </summary>

```

Hello! You should now be able to edit the draft page for this facility, located at [LINK TO NEW FACILITY DRAFT PAGE ON PROD]

Important: Please make sure that all relevant steps listed within the “How do I add a facility to my health care system?” Knowledge Base article have been completed: https://prod.cms.va.gov/help/vamc/about-locations-content-for-vamcs/how-do-i-add-a-facility-to-my-health-care-system

Once finished, please save this page (and all related VAMC Facility Health Service pages) in the moderation state “Draft." Please do not save them as “Published.”

Please let us know when your draft content is complete, so that we can wrap up the technical process from our end before publishing the new facility to VA.gov. Thanks!

```

</details>

- [x] 5. Create a [URL change request](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/new?assignees=&template=runbook-facility-url-change.md&title=URL+Change+for%3A+%3Cinsert+facility+name%3E), changing the entry from the old facility URL to the new facility URL. (**Note: The URL change request ticket blocks the completion of this ticket.**)

#17946

- [x] 6. When editor has prepared content and let help desk know, reassign this issue to appropriate CMS engineer on Product Support team, for bulk publishing.

#### CMS engineer steps
- [x] 7. CMS engineer executes the steps of the URL change request ticket from step 5 above.

(Redirects deploy daily except Friday at 10am ET, or by requesting OOB deploy (of the revproxy job to prod) in #vfs-platform-support. Coordinate the items below and canonical URL change after URL change ticket is merged, deployed, and verified in prod.)

#### Drupal Admin steps (CMS Engineer or Help desk)
_Help desk will complete these steps or escalate to request help from CMS engineering._
- [x] 8. Drupal Admin bulk publishes nodes and facility.
- [x] 9. Drupal Admin edit facility node and remove `New facility` flag and save node.
- [x] 10. Let Help desk know this has been done, if not done by Help desk.

#### CMS Help desk (wrap up)
- [x] 11. Notify editor and any other stakeholders.

[VAHELP-6959]: https://va-gov.atlassian.net/browse/VAHELP-6959?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by omahane** [comment]
# Outstanding Drupal admin tasks
## Publish service nodes
![Screenshot 2024-06-28 at 7 46 14 AM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/766573/6c3d4b3e-2406-411b-9afe-5af9d539181d)

The [bulk edit view](https://prod.cms.va.gov/admin/content/bulk?title=north+east+bexar&type=All&moderation_state=All&taxonomy_entity_index_tid_depth=All) is easiest to use for publishing multiple nodes.

## Alphabetize the locations menu
<img width="1792" alt="Screenshot 2024-06-28 at 7 40 37 AM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/766573/4cf376d7-bf97-4036-aa51-8b70c23d32d1">

The menu item should be placed for appropriate listing in the VA South Texas health care menu:
https://prod.cms.va.gov/admin/structure/menu/manage/va-south-texas-health-care

**Comment by ian-sears** [comment]
@omahane Thank you for the hand-holding. It was slowed last night as @TroyCMSSupport and I met to use this as an example from us back to you that we are understanding our steps of responsibility, et al. We'll walk through and complete the above so we improve our understanding. Teach a man ta fish. And thanks. 😉

**Comment by ian-sears** [comment]
@omahane  Above is all set. We conversed with the editor to let him know the Health Services Publishing and Menu alphabetizing can be expected to be seen on the live site after the next Content Release.
I was about to remove the final Flag on the facility node, but see you have it Locked for editing. Ok to remove it if you are in there.

**Comment by omahane** [comment]
The canonical URL has been deployed, [per Adam](https://dsva.slack.com/archives/C02BTJTDFTN/p1720015713762209?thread_ts=1719340047.322509&cid=C02BTJTDFTN), and verified by me on VA.gov. This ticket can be closed after confirmation with the editor.

**Comment by omahane** [comment]
Unassigning myself from this as there's no more Facilities work to do here.

**Comment by TroyCMSSupport** [comment]
@jilladams @ian-sears @omahane - I have notified the editor, and confirmed all links work as expected, and site appears in the VA.gov locator.
