### ISSUE TITLE
"Common conditions" text shows in Italics

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#17954]
## Description
When reviewing I noticed that the "Common conditions" text showed on the front end in italics on VAMC services ([Example](https://www.va.gov/boston-health-care/locations/brockton-va-medical-center/#dermotology)):
![Screenshot 2024-04-25 at 9 21 05 AM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/106678594/448a8c25-34f8-449b-b3fc-685d54672ddc)

This is not part of the VA style guide, we don't use italics and we also try our best to avoid this for accessibility reasons. We should remove this styling.

## Acceptance Criteria
- [ ] "Common conditions" text is no longer displayed with italics on the FE on VAMC Service accordions
- [ ] Requires design review
- [ ] Requires accessibility review

**Comment by davidmpickett** [comment]
Verified in prod
![Screenshot 2024-08-19 at 4 01 58 PM](https://github.com/user-attachments/assets/ea843f77-f154-404d-ab81-3c204d3784a6)
