### ISSUE TITLE
Refine Datadog monitor for Forms GET alarms

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#17964]
## Status
**[2024-07-08]** Moved to Ready for Chris K to work in in ~ Sprint 10
**[2024-04-25]** Asked via Slack if Chris K. can estimate async so that we can pull it into Sprint 3 for Josh to work on.

## User Story or Problem Statement
As a product team, I want to get Datadog alarms only if a problem is critical or ongoing, not for every blip. 

## Description or Additional Context 
We own a Datadog synthetic monitor that sends a GET request to the vets-api /v0/forms endpoint every minute, and expects a response within 1000ms: 
[[Synthetics] GET vets-api /v0/forms (prod)](https://vagov.ddog-gov.com/synthetics/details/vxk-9ki-9fa?resultId=8489920035257965261&source=monitor_notif)

Anytime a response is >1000ms, the monitor alarms. That's not useful. More notes here: https://dsva.slack.com/archives/C05THHJHH2R/p1714069662900159?thread_ts=1714068389.937709&cid=C05THHJHH2R

We want to update the monitor to only alarm if ... (figure out better criteria here, when we refine this ticket)

Notes from Chris K: 
- Latency for response range was: 2071 - 54273ms

- I would recommend either:
  - Increasing the response time from the 1000ms.
  - Increase the timeframe we evaluate the test in a failed state to alert. Right now this timeframe is at 5mins.

Either of these would be fairly easy to implement.

## Acceptance Criteria
- [ ] Forms GET monitor is configured to alarm when ...

**Comment by chriskim2311** [comment]
Some notes:
Latency for response range was: 2071 - 54273ms

I would recommend either:
Increasing the response time from the 1000ms.
Increase the timeframe we evaluate the test in a failed state to alert. Right now this timeframe is at 5mins.

Either of these would be fairly easy to implement.

**Comment by chriskim2311** [comment]
I have updated the monitor to fail after 10 seconds now instead of 1 second. Also have allowed for 3 retries if it has failed. Monitor will still alert if in a failed state after 5 mins.
![Image](https://github.com/user-attachments/assets/5ff00ed8-3108-4f12-8e2e-c5a9af930d80)

**Comment by chriskim2311** [comment]
@FranECross @jilladams You can review the changes I have made for this monitor. Let me know if I should make additional changes thanks!

**Comment by FranECross** [comment]
@chriskim2311 The changes look good; would like @jilladams to sign off as well since she's more familiar with monitoring. Thanks!

**Comment by jilladams** [comment]
That seems sensible, and we can always adjust if this still makes noise / doesn't make enough noise for real problems. Gonna go ahead and close. Thanks, @chriskim2311 !
