### ISSUE TITLE
VBA final design review

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#17966]
When component adoption is complete for VBA, we need to design review the template with pre-populated data for several cases. This should start as a FE exercise to ensure that we are: 

* Using DS components wherever possible
* Not using custom code and classes, unless absolutely necessary
* Build is as compliant with Figma designs as possible

When those thing are confirmed, FE should tag Design for further design review for any final changes.

## Setting up a Tugboat with content
* Go to Tugboat, you can use the VBA Staging review one if it hasn't been torn down / errored out: https://tugboat.vfs.va.gov/6658992b17e38363d35596a2
* If it needs rebuild, you can use the script to re-generate content: 
  * https://tugboat.vfs.va.gov/6658992b17e38363d35596a2 > Actions > Rebuild (takes ~5ish mins)
  * https://tugboat.vfs.va.gov/6658992b17e38363d35596a2 > Services section > php, far right column: Click Terminal link
  * paste in `drush scr scripts/content/vacms-17969/VACMS-17969-vba-test-data-processor.php` (This should take less than a minute.)
  * In the browser, go to https://cms-jdujzwgvp8kmj36hcfonqejlgtq5b6st.demo.cms.va.gov/admin/content/
     * Confirm that content has just been created or updated of the following types: 1) Service region, 2) VBA Facility, 3) VBA Facility Health Service
     * https://cms-jdujzwgvp8kmj36hcfonqejlgtq5b6st.demo.cms.va.gov/admin/content/deploy to Release content

## ACs
- [ ] FE engineering has reviewed the build to ensure: 
    - [ ] DS components are used wherever possible
    - [ ] No custom code and classes are in use, unless absolutely necessary. If they are, their use is flagged for design review
    - [ ] Build is as compliant with Figma designs as possible
- [ ] UX has reviewed the build from this point for: 
    - [ ] Design compliance
    - [ ] Case by case review of any spots where custom code / classes would be required to achieve the Figma designs, to determine if that's preferred or if designs should change to accommodate pure DS use
    - [ ] Tickets are filed for FE required updates

**Comment by jilladams** [comment]
FE points = 3
We need UX points

**Comment by davidmpickett** [comment]
Per UX Sync today. This is officially not blocking Staging Review and instead just blocking full MVP launch

**Comment by Agile6MSkinner** [comment]
Removed a couple of blockers that we have decided were not launch blocking.

**Comment by Agile6MSkinner** [comment]
Last blocker will be cleared at the end of this sprint. @dsasser @davidmpickett Does this look ready to pull in or does it need refinement?

**Comment by davidmpickett** [comment]
@Agile6MSkinner IMO this is blocked until all known launch blocking bugs are resolved. New bugs have cropped up that haven't been refined yet:

- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18393
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18383

**Comment by davidmpickett** [comment]
IMO Additional bugs that should be resolved before this @thejordanwood reviews
- #17601
- #18228
- #17852
- #18227
- #18540

**Comment by jilladams** [comment]
Revisiting this ticket:  VBAs are published in the wild, so it's starting to feel weird that this review is dangling. The 4 open tickets Dave noted 2 comments up are all in the National Rollout epic, 2 queued for refinement, 2 in the backlog. I'm not sure it makes sense to hold up a final double check of VBAs while we are allowing them to publish. 

Could we: do the design / FE review just to make sure we don't have issues actively making it to prod, and include design review on those 4 remaining bugs, as they get scheduled / close?

cc @Agile6MSkinner

**Comment by davidmpickett** [comment]
> Revisiting this ticket: VBAs are published in the wild, so it's starting to feel weird that this review is dangling. The 4 open tickets Dave noted 2 comments up are all in the National Rollout epic, 2 queued for refinement, 2 in the backlog. I'm not sure it makes sense to hold up a final double check of VBAs while we are allowing them to publish.
> 
> Could we: do the design / FE review just to make sure we don't have issues actively making it to prod, and include design review on those 4 remaining bugs, as they get scheduled / close?
> 
> cc @Agile6MSkinner

I would close this as a no-op rather than doing a review against current state. Can always open a new ticket for a holistic audit once outstanding issues are addressed.

Design review is a continuous process, so we'll be continuing to review as defect tickets get picked up. Also a reminder that in addition to those 4 bug tickets, there are issues from Staging Review epic have not been necessarily ticketed on our board.

We've already done several holistic reviews throughout. No point in doing another until we've resolved all the defects flagged from previous reviews. We would have caught anything major by now.
