### ISSUE TITLE
VBA: Create a method to generate test content to use for QA

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#17969]
## User Story or Problem Statement
As a product owner, I want confidence that our QA has reviewed an example Regional Office that represents all the available flavors of options with Drupal. 

## Description or Additional Context 

When using Tugboat, the database gets blown away everytime we rebuild the environment. Having a method to easily generate test content saves time with generating data examples after every rebuild, and can help guarantee we are remembering to review all data cases when we do things like design reviews (#17966 ).

The one tradeoff here might be effort. Not only initial effort, but if the Drupal data model continues to evolve, the script needs to stay in step. To discuss when refining.

## Eng notes
We can make [content generation scripts](https://github.com/department-of-veterans-affairs/va.gov-cms/tree/main/scripts/content) that can be run on the Tugboat terminal, to generate content. 

We could also do this via migration. Would need to build the migration (Drupal), and then create a CSV that can be migrated in when we need it (more notes in comments).

The script we end up with will need to be run on the server, but that can be done in Tugboat terminal by anyone on the team.

## Decisions
For now: write a content migration script. 
For later: think holistically about better path for migration-based content. 

## Scope
All of VBA types / fields: facility, services, related paragraphs. 
Engineering to complile the list of fields. 
@davidmpickett took a first pass [in a comment](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17969#issuecomment-2125507625)
Described in Google sheet [VACMS-17696-vba-test-data](https://docs.google.com/spreadsheets/d/1g-gXoo03vvQeTxEJ2Rr1X8avGhRtSCA7d2gD6c4zRdg/edit#gid=0)

## Acceptance Criteria
- [ ] Generate script for test data for all VBA fields from VBA Facilities, VBA Service Regions, VBA Facility Services
  - [ ] Does not need to include Centralized Content, bc it already exists in the database

**Comment by omahane** [comment]
I've been thinking about this and it **might** make more sense to create a migration for test data instead. If we were migrating a CSV, non-engineers could help develop/maintain the CSV. I'm not 100% sure if it's better. It might clearer/easier to see what we're creating.

**Comment by jilladams** [comment]
Could we make it possible to auto publish auto content in lower envs? If not: we have to run script and then content release on Tugboat to get the content live.

**Comment by jilladams** [comment]
If we go CSV route: 
* We can set content to published
* Exporting VBA might be fastest step to get a read on how Drupal expects the CSV to be structured
* Sitebuilder stuff: 
  * Creating CSV & test data
  * Importing for migration
* Drupal eng stuff: 
  * Write the actual migration code

**Comment by jilladams** [comment]
Guesstimate 5ish for now

**Comment by davidmpickett** [comment]
took a first pass at a list

## VBA Facility 1 (pick an existing Regional Office) = ALL the Services
- Add 1 of every VBA Facility Service to this facility (there are currently 18)
- Across those services account for all possible scenarios for:
    - Office Visits - 4 options + Null
    - Virtual support - 4 options + Null
    - Appointment intro text - 3 options + Null
      - Within the custom appointment text account for no characters entered & some characters entered 
    - Appt phone use facility phone - 2 boolean options (no Null?)
    - Appt phone additional phone #s - account for Phone/SMS/Fax
    - Address
    - Hours 
    - Contact info 
## VBA Facility 2 (pick an existing Satellite Benefit office) = NONE of the Services
- Add No VBA Facility Services to this facility (to confirm that accordion groups don't show when there's no content ) 

## VBA Facilities 3-7? = Make sure each of the possible variants for Facility fields is accounted for
- Operating Status - 4 + Null
- Facility image  - has and image / doesn't
- Prepare for your visit accordions- zero/ one / multiple
- Local spotlights - zero/one /two
  - Call to actions yes/no

**Comment by omahane** [comment]
@davidmpickett I'm going to start coding for services to the spreadsheet in earnest tomorrow. If you have any questions/concerns about the distribution of content or the content itself, could you let me know?

**Comment by davidmpickett** [comment]
> @davidmpickett With regard to [service regions](https://prod.cms.va.gov/node/add/service_region), do you have some sense of what we need?

Copying my response from slack here:

Given that the Service Region considerations have officially been punted from Pilot MVP to National roll out, I would say that it no longer makes sense to try and generate test content for them now.

In theory, they could have as many variations as a VBA Facility Service in terms of all the possible scenarios. However, in total there will probably only be a handful of these. Until we have national stakeholders actively engaged in creating these, I don't think that we need to be testing them.

But that's a product call so @mmiddaugh @Agile6MSkinner?

**Comment by jilladams** [comment]
Further copying from Slack: Michelle flagged it would be smart to ensure the service regions are present when expected - even if we acknowledge they aren't displayed as expected. 

Thus: Possible Service region test scenarios

- Service Region A
  - **Service** = home loans
  - field_vba_region_facility_list: includes Philadelphia RO
  - **Scenario to test**: does Service region A content show on Philadelphia - Home Loans?
- Service Region B
  - **Service** = Veterans pension
  - field_vba_region_facility_list does NOT include Philadelphia
  - **Scenario to test**: does Service region B content NOT show on Philadelphia Veterans Pension

**Comment by omahane** [comment]
@jilladams This is approved and ready to go. Any objections to having this merged? We can always make changes to the data files if we need to.

**Comment by jilladams** [comment]
Go for it!

**Comment by jilladams** [comment]
Oh - went for it already! Moved ot pending prod deploy

**Comment by omahane** [comment]
To run the script: `drush scr scripts/content/vacms-17969/VACMS-17969-vba-test-data-processor.php`

**Comment by laflannery** [comment]
@omahane I took a look at the spreadsheet and have some questions:
- Is there a reason we decided to use `null` on required fields? For example, on the service options, an editor cannot leave Office or Virtual visits blank so real data would not have a `null` value
- For the `field_office_hours (case statement)` field on Grief and bereavement counseling, only the start time was added in Drupal and the hours aren't being shown on the front end. Are you able to adjust this so that start and end time are added in Drupal?
- I'm confused about Services with multiple locations - is the data with services 2 and/or 3 in the spreadsheet and I'm just missing it?
- I believe Jordan may have already mentioned this in her comments but she wasn't seeing the Service regions on the FE. It is because the Service region is not attached to a Facility. In the spreadsheet, `(field_vba_region_facility_list)` has the proper facility in the cell but for some reason this is not coming over into Drupal

**Comment by davidmpickett** [comment]
> Is there a reason we decided to use null on required fields? For example, on the service options, an editor cannot leave Office or Virtual visits blank so real data would not have a null value

This was my suggestion. It is basically a way to ensure gracefully degradation in case something about the Drupal field requirements were to ever change, I want to make sure the FE is not gonna freakout because a field it expects to exist ever comes back Null. 

Also we know that VAMCs have a lot of Nulls because required fields were added after the services were initially required. Even though this test data is VBA, having nulls here is a sneaky way to confirm VAMC services aren't gonna break since they share the same partial template for Service Location.

**Comment by omahane** [comment]
> @omahane I took a look at the spreadsheet and have some questions:
> 

> * I'm confused about Services with multiple locations - is the data for service locations 2 and/or 3 in the spreadsheet and I'm just missing it?

No, to keep the spreadsheet from becoming insanely long, I have chosen to do the following:
- Follow the spreadsheet for the first service location
- For any subsequent service location, I create random numbers of appointment phones, contact phones and email, randomly determine whether they get extensions, whether to use facility hours, and whether to use facility phone

I hope that makes sense.

**Comment by jilladams** [comment]
This is done, merged, and has been used successfully on Tugboat (YAY, thankyou). This work did spawn a new ticket, #18393 , where hours are weirdly not consistent on the FE, and we think that's a FE bug. Doesn't block closing this ticket, so.
