### ISSUE TITLE
URL Change for: Leeward Oahu VA Clinic TO Daniel Kahikina Akaka VA Clinic

### ISSUE THREAD

**Issue by TroyCMSSupport** [department-of-veterans-affairs/va.gov-cms#17963]
### Implementation date
When does this request need to be live:
04/25/2024

### Instructions for URL redirect
(Note: This issue will be used from initial request through implementation to ensure all individuals working on this are notified of status updates.  Please do not create multiple issues to track different steps.)
- [x] Notify VA stakeholders as appropriate.
- [x] Link the related facility closure / rename issue.
- [x] Create a URL redirect in the [devops](https://github.com/department-of-veterans-affairs/devops) repo in `ansible/deployment/config/revproxy-vagov/vars/redirects.yml`
- [x] Add the "Awaiting redirect" flag to the facility node with a revision log message that includes a link to this ticket, preserving the node's current moderation state.
- [x] Redirects deploy daily except Friday at 10am ET, or by requesting OOB deploy (of the revproxy job to prod) in #vfs-platform-support. After deploy, validate that the URL redirect is deployed. (Note: In the event of a facility closure or a name change,  validate that this occurs before making the Lighthouse csv changes.)
- [x] Update this ticket with a comment that the redirect has been deployed.
- [ ] Remove the "Awaiting redirect" flag on the facility node with a revision log message that includes a link to this ticket, preserving the node's current moderation state.
- [ ]  Notify helpdesk via comment on ticket or Slack message in #cms-support that changes are ready for review.

#### URL Redirect
| Current URL  |  Redirect Destination or New URL |
| ---  |  --- |
|(https://www.va.gov/pacific-islands-health-care/locations/leeward-oahu-va-clinic/) | (https://www.va.gov/pacific-islands-health-care/locations/daniel-kahikina-akaka-va-clinic/) |

### 1. Canonical URL change or
**Note: Canonical URL changes do not block the completion of the parent ticket. Once the URL redirect above has been deployed, the value to the Veteran is delivered. This ticket should be kept open until the URL change is verified, except in the case of a removal (as described below).**

### Instructions for canonical URL change
- [ ] Verify that the new URL for the facility is published and accessible on VA.gov.
- [ ] Update the [CSV in Lighthouse](https://github.com/department-of-veterans-affairs/lighthouse-facilities/blob/master/facilities/src/main/resources/websites.csv) with the changed URL, maintaining the sorted order of the Facility API IDs.
- [ ] Create a PR in the [lighthouse-facilities repo](https://github.com/department-of-veterans-affairs/lighthouse-facilities), tagging the Lighthouse team.
- [ ] Post a message in the #cms-lighthouse channel in Slack, with an @mention to a Lighthouse team member.
- [ ] Add the "Awaiting CSV" flag to the facility node with a revision log message that includes a link to this ticket.
- [ ] Validate that the change has deployed by checking that the Facility Locator has been updated with the new url.
- [ ] Update this ticket with a comment that the CSV change has been deployed.
- [ ] Remove the "Awaiting CSV" flag to the facility node with a revision log message that includes a link to this ticket.

#### URL change example (update with actual ID and URL)
| Facility API ID  |  Full VA.gov URL |
| ---  |  --- |
| vha_459GG | https://www.va.gov/pacific-islands-health-care/locations/daniel-kahikina-akaka-va-clinic/ |

**Comment by TroyCMSSupport** [comment]
@omahane @ian-sears  - I am currently unable to revise Github tickets - but this is related to [17961 ](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17961)

**Comment by TroyCMSSupport** [comment]
@ian-sears @omahane - I am able now to revise / edit so have added details. Please let me know if I have missed anything.

**Comment by TroyCMSSupport** [comment]
@omahane - I think I've updated the URL information correctly - please let me know if you find otherwise!

**Comment by omahane** [comment]
PRs for redirects have been added:
https://github.com/department-of-veterans-affairs/devops/pull/14271
https://github.com/department-of-veterans-affairs/vsp-platform-revproxy/pull/304

**Comment by omahane** [comment]
The redirect has been deployed.

**Comment by omahane** [comment]
Because the CSV change would only be data hygiene (as the redirect is already in place), there's no Veteran facing value in asking for this change. Thus, this ticket is done.

**Comment by TroyCMSSupport** [comment]
Thank you @omahane
