### ISSUE TITLE
VBA: Custom street address does not display on FE

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#17973]
## Description

If an editor adds a custom street address (not the main facility address), I'm not seeing this, I'm not seeing anything. This is happening on VBA Facility services and Service regions.

[Regional Loan Center in Cleveland](https://main-shoowipgxumevd9gysmbhgkv2catpzm1.demo.cms.va.gov/node/61786/edit)
- "Use Facility address" has been unselected
- Information has been added into the various address fields
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/106678594/bbe72b43-e3ef-4246-9ea5-1c4bb96c1bdb)
**Front end**
On [the home loans accordion](https://web-shoowipgxumevd9gysmbhgkv2catpzm1.demo.cms.va.gov/cleveland-va-regional-benefit-office/#vba-service-item-1131-), within the Region content, I don't see any additional address info other than the "Name/Building/Floor" fields
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/106678594/896c7f29-b362-4cb4-8b4b-ca10196b4fdb)

## Acceptance Criteria
- [ ] Determine if the custom street address should be displaying and if so where
- [ ] Add the custom street address to the FE for services and service regions as indicated in the design file (link incoming)
- [ ] Requires design review

**Comment by jilladams** [comment]
@laflannery when Facility street address IS checked, does the full street address appear under the "Name of office" header shown in your screenshot? 

Figma for service accordions is here: https://www.figma.com/design/88Gw7fmUkDbheSAHjIpHn7/VBA-Regional-Office?node-id=0-1107&t=AZZS3r6WkPwG6sal-0 -- seems like the address should appear int he same place, whether it's the Facility or not-the-facility address, but I tagged @aklausmeier in Figma to help us confirm, since Jordan's out.

**Comment by jilladams** [comment]
(Looking at some example VBA facility services in Laura's tugboat, looks like when Facility Street address is used, no address header or data shows in the service accordion: 

https://cms-shoowipgxumevd9gysmbhgkv2catpzm1.demo.cms.va.gov/node/68722/edit
![Screenshot 2024-05-31 at 3 36 34 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/85581471/96277198-ca19-4326-b07a-091627a74d2e)

https://web-shoowipgxumevd9gysmbhgkv2catpzm1.demo.cms.va.gov/national-capital-region-va-regional-benefit-office/
![Screenshot 2024-05-31 at 3 36 41 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/85581471/90ee7016-0065-4cb6-919c-cf0e846e61ae)

**Comment by laflannery** [comment]
@jilladams The above scenario is purposeful, the facility address should not be showing - https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17514

**Comment by thejordanwood** [comment]
@davidmpickett I now show that scenario in [the Figma file](https://www.figma.com/design/88Gw7fmUkDbheSAHjIpHn7/VBA-Regional-Office?node-id=0-1742&t=UbYsq9MaodsMlrwq-1).
