### ISSUE TITLE
[Retire?] Telehealth in VA Services

### ISSUE THREAD

**Issue by davidmpickett** [department-of-veterans-affairs/va.gov-cms#17974]
### Which Taxonomy is this term for?

VA services taxonomy

### Link to existing term

https://prod.cms.va.gov/health-care/telehealth

### Rationale for updating this term

Telehealth is a modality by which services are delivered, not a services unto itself. Since we didn't previously have a way to indicate service delivery options, Telehealth was added as a workaround.

Once [Service Options have been launched](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16825), VAMC editors will be able to indicate virtual support/telehealth per service. What is the plan to retire Telehealth as a stand alone service? 

- Do we give VAMC editors a deadline to update all their services to use Virtual Support?
- We could turn off Telehealth "Show for VAMC". This would prevent new instances of Telehealth from being added, but not get rid of existing ones.
- What about Vet Centers?

### Which products will this term impact?

VAMCs
Vet Centers

### Have stakeholders from impacted products been consulted?

No

### Acceptance Criteria

- [ ] Plan is reviewed by relevant stakeholders
- [ ] (List any necessary review and approval steps here)

**Comment by mmiddaugh** [comment]
In consultation with editors, VHA DM wants to maintain this service for now because it improves findability for the information as Veterans may find and view that service. Will revisit over time. Closing this for now - we can reopen or recreate if needed in future.
