### ISSUE TITLE
Terraform monitor for Content Build lower environment Tugboat instance

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#17989]
## User Story or Problem Statement
We want the monitor watching the Tugboat instance that Content Build uses for lower environment builds to be managed in code so that it can be restored and changes to it are documented.

## Steps for Implementation
This is the monitor that was created: https://vagov.ddog-gov.com/monitors/237441?view=spans

We should move this into Terraform code in the Devops repo so that we are managing it properly. 

## Acceptance Criteria
- [ ] The existing monitor is moved into Terraform code in the Devops repo.

**Comment by jcbolling** [comment]
Terraform'd monitor now available at https://vagov.ddog-gov.com/synthetics/details/5gj-9f4-ntj?from_ts=1723046456359&to_ts=1723050056359&live=true
