### ISSUE TITLE
VBA not correctly referencing Drupal Appointment introduction text values on FE

### ISSUE THREAD

**Issue by davidmpickett** [department-of-veterans-affairs/va.gov-cms#17999]
# Description
In Drupal, editors can choose Default, Custom, or remove. 
FE should respect and display that value.

## Default text
Drupal is correct https://pr15622-xptmfsnjoodldn85nzgkrgljqtfbz24b.ci.cms.va.gov/node/68188/edit

![Screenshot 2024-04-29 at 11 01 23 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/3338126a-df95-4076-9087-90d5b7259e7b)

FE is wrong: https://web-xptmfsnjoodldn85nzgkrgljqtfbz24b.ci.cms.va.gov/cleveland-va-regional-benefit-office/locations/cleveland-va-regional-benefit-office/#veteran-benefits

![Screenshot 2024-04-29 at 11 01 12 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/672708c1-320d-400f-bc42-f85c01d81900)

## Appointments - Custom text

**Update 5/22 - I am no longer seeing this issue**
I have an instance where the editor added custom text and it does properly show on the front end:
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/106678594/505c54a6-e479-4879-9f29-bef4f1996721)

![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/106678594/5379f75d-f8fa-431c-b9d8-3175a420509e)

   - ~If an editor chooses to add custom appointments text, this text is not showing on within the service accordion info on the FE.~
   - ~Example: Cleveland VBA Home loans service~
     - ~[Drupal](https://pr-xptmfsnjoodldn85nzgkrgljqtfbz24b.ci.cms.va.gov/node/67934)~
~![Screenshot 2024-04-26 at 10 09 14 AM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/106678594/0df137a4-8b31-4109-a11a-b24fa32d6254)~

     - ~[FE](https://web-xptmfsnjoodldn85nzgkrgljqtfbz24b.ci.cms.va.gov/cleveland-va-regional-benefit-office/locations/cleveland-va-regional-benefit-office/#vba-service-item-1131-)~
~![Screenshot 2024-04-26 at 10 09 39 AM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/106678594/21ee097e-6958-4045-bb86-f67267e9bc11)~

## Acs

- [ ] FE should show the value stored in Drupal on the Regional Office for Appointments introduction text
- [ ] If GraphQL is not possible to get, flag for Drupal ticket

**Comment by jilladams** [comment]
From refinement: 
* Default text: the FE receives the string of the radio button value selected, e.g. "Use default text". The GraphQL does _not_ currently provide the actual default text. 
  * The mechanism that creates the Default text is a Drupal-side thing that now has 3 optional Defaults (based on what type of service: VAMC Health, VAMC non-clinical, or VBA.) We will find and link the ticket where that was done, in order to trace the GraphQL.
  * @dsasser can help figure out the GraphQL path to it.
* Custom text: the value of the actual text comes through GraphQL

**Comment by jilladams** [comment]
Estimate = 3, with assumption that we can provide the GraphQL, and that the work is to implement default graphQL, and troubleshoot why Custom isn't showing up.

**Comment by jilladams** [comment]
@davidmpickett noting: we found the missing Default field info on #16348. Eli flagged that in the new Service Location world: it would be best to handle all 4 of those default text options in one go in this ticket, rather than only handle VBA. (Since SL is now basically a component.)

With that in mind: there is _not_ a field specified on #16348 for VAMC health services Appointment default text. 
* If we need that: we need a Drupal ticket to create it? 
* If we don't need that: why? OR: we just need to tell Eli what to hard code for an `else` when it's a VAMC Health service.

**Comment by eselkin** [comment]
A little discovery:
fieldVbaFacServApptDefault
is in:
```
reverseFieldOfficeNode(
          filter: {conditions: [{field: "type", value: ["vba_facility_service"]}, {field: "status", value: ["1"]}]}
        ) {
          entities {
            ... on NodeVbaFacilityService {
              ...
              fieldVbaFacServApptDefault
```
and
fieldVbaServRegApptDefault
is in
```
reverseFieldVbaRegionFacilityListNode(
          filter: {conditions: [{field: "status", value: ["1"]}]}
        ) {
          count
          entities {
            entityId
            entityLabel
            ... on NodeServiceRegion {
              ...
              fieldVbaServRegApptDefault
            }
          }
        }
      }
```

fieldVamcNonclinApptDefault
is `null` in the data, is this expected?
at
```
reverseFieldFacilityLocationNode(
                    limit: 50
                    filter: {conditions: [{field: "type", value: ["vha_facility_nonclinical_service"]}, {field: "status", value: ["1"], enabled: true}]}
                  ) {
                    entities {
                      ... on NodeVhaFacilityNonclinicalService {
                        fieldVamcNonclinApptDefault
```

as for something in NodeHealthCareLocalHealthService, I don't see anything.

**Comment by jilladams** [comment]
(I don't think I understand the implications of the code enough to be able to say whether that's expected. Is that a Drupal data question? If so, Christian's not on this ticket anywhere. Until now: @omahane )

**Comment by davidmpickett** [comment]
> fieldVamcNonclinApptDefault
> is `null` in the data, is this expected?

That makes sense since we're not showing Appointment information on VAMC non-clinical services FE templates AND we've now [hidden the related Drupal fields](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17515) from users.

**Comment by davidmpickett** [comment]
> as for something in NodeHealthCareLocalHealthService, I don't see anything.

Poked around @omahane's code and I think this is the field you need @eselkin: 
health_care_local_health_service' => 'field_hservices_lead_in_default'

**Comment by eselkin** [comment]
I thought when I checked that field I got values like "1" which didn't make any sense. I'll double check.

**Comment by eselkin** [comment]
```
query f {
  nodeQuery(
    limit: 20
    offset: 0
    sort: {field: "nid", direction: ASC}
    filter: {conditions: [{field: "status", value: ["1"], enabled: true}, {field: "type", value: ["health_care_local_facility"]}]}
  ) {
    entities {
      ... on NodeHealthCareLocalFacility {
        fieldLocalHealthCareService {
          entity {
            ... on NodeHealthCareLocalHealthService {
              fieldHservicesLeadInDefault
              fieldHserviceApptLeadin
            }
          }
        }
      }
    }
  }
}
```
`fieldHservicesLeadInDefault` is always null

**Comment by omahane** [comment]
Markup fields don't show for users, only on the node:edit.

**Comment by jilladams** [comment]
That field in screenshot currently contains what was intended to be Veteran facing appointment related text, I think -- sounds like we may need to revisit that? Queuing for 16th min tomorrow.

**Comment by davidmpickett** [comment]
Seems like the [plan for multiple default appointment texts](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16153) did not account for being the default text being accessible to VA.gov FE, just the Drupal FE.

1) Default text is essentially centralized content. Should these be driven by relevant Centralized Content nodes for each product and the markup fields converted into EFFs?

2) Or is there a KISS route to take? Some other way to get those markup field contents into a place FE can reference.

**Comment by eselkin** [comment]
> 2. Or is there a KISS route to take? Some other way to get those markup field contents into a place FE can reference.

The data would need to be used in content-build and not vets-website. Only vets-website can make use of KISS data.

**Comment by jilladams** [comment]
This default text varies across Service Location types: 

### VAMC
![Screenshot 2024-06-05 at 8 59 22 AM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/85581471/b5a91896-ae81-41e4-ae86-870b34d79dc8)

### VBA
![Screenshot 2024-06-05 at 8 59 18 AM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/85581471/bdba0200-a762-4a7a-b22a-098d1d97cfeb)

**Comment by jilladams** [comment]
This ticket is blocked until Drupal updates to provide the data to the FE.

**Comment by jilladams** [comment]
Since we worked out root cause and defined a path to handle this default text via hard copy in #18273, we are closing this one as a Spike, and #18273 will track the hard coded change.
