### ISSUE TITLE
Perform a disk space cleanup before running builds in Continuous Integration workflow

### ISSUE THREAD

**Issue by 7hunderbird** [department-of-veterans-affairs/va.gov-cms#17990]
## Background
- [Slack Link](https://dsva.slack.com/archives/C02VD909V08/p1714417988154919)

Our builds for https://github.com/department-of-veterans-affairs/content-build/actions/workflows/continuous-integration.yml fail after an hour because there isn't enough space to complete all steps.

If we had it "fail fast" by checking disk space before it builds, that could help. 

But it may be better to figure out if we can clear the disk space in the /home/runner folders.

The main problem is that each Runner can run multiple workflows and we'd not want to clear the shared disk space of each of the runners if they are still performing work.

We'd need to assess the architectural options and trade-offs with either failing the build quicker or running a disk purge before the workflow.

## Steps to Implementation
- [ ] Discovery work to determine the best path forward to resolve the issue.
- [ ] Implementation plan. 

## Acceptance Criteria
- [ ]

**Comment by gracekretschmer-metrostar** [comment]
The value of this ticket will verify that there are no disk space problems and help prevent fires from happening.

**Comment by 7hunderbird** [comment]
We've not had disk space issues on the GitHub Action runners since this issue was brought up.  I think we can close it and create a new ticket later if needed.
