### ISSUE TITLE
Tests on Vet Centers Operating Status Crashes Sometimes

### ISSUE THREAD

**Issue by eselkin** [department-of-veterans-affairs/va.gov-cms#17994]
## User Story or Problem Statement

Tests should be robust against ordering issues. The Vet Center operating status test tests a deeply copied array before and after modification. 

## Steps for Implementation

Even though spread operator copy is used, beginning of test modifies object so the tests should all pass as expected.

## Acceptance Criteria
- [x] Tests pass no matter the order

**Comment by jilladams** [comment]
Merged for 2 days, no flags from CI. Closing and we can reopen as needed for follow up.
