### ISSUE TITLE
Update VBA VERA links to open in same tab

### ISSUE THREAD

**Issue by davidmpickett** [department-of-veterans-affairs/va.gov-cms#18004]
The Design System Team changed the external link guidance (on 4/22) since we first designed and built VBA. 

- VERA is not on a va.gov subdomain -> https://va.my.site.com/VAVERA/s/
- Previous guidance was all such external links should open in a new tab
- New guidance is that links should only open in new tab if they would interrupt a form flow

Two affected links on VBA Regional Office page
- The "Make an appointment" top task link
- The "Schedule an appointment online" link that conditionally shows up in service accordions 

https://web-xptmfsnjoodldn85nzgkrgljqtfbz24b.ci.cms.va.gov/cleveland-va-regional-benefit-office/

## Screenshots from SL Tugboat as of 5/8

![Screenshot 2024-05-08 at 3 41 42 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/23b4a8c9-701b-4669-bc21-a651b6a6721f)

![Screenshot 2024-05-08 at 3 42 25 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/acfab549-3d3a-440b-8caa-57fc5be29858)

**Comment by jilladams** [comment]
@davidmpickett when we updated these links to use VERA (here: https://github.com/department-of-veterans-affairs/content-build/pull/2026/files) the code doesn't say to open in a new tab. We might've assumed it would/did -- this may be a no-op, unless we have seen it new tabbing in the wild. Have you? If not, prob can close.

**Comment by davidmpickett** [comment]
Confirmed as a yes-op. Screenshots added to tickets

**Comment by jilladams** [comment]
FASCINATING, fyi @eselkin (and @laflannery ). 

Ok so: that's not the service_location template Eli and I were looking at today: https://github.com/department-of-veterans-affairs/content-build/blob/c657ad7727bbcd32d2ebb54b9b40a1a9ae62e5c9/src/site/includes/vba_facilities/service_location.liquid#L83

Instead, it's the main buttons: https://github.com/department-of-veterans-affairs/content-build/blob/VACMS-16144-VAMC-ServiceLocationParagraphs/src/site/facilities/main_buttons.drupal.liquid#L8

But still: target="_blank" isn't in the markup, which means it's getting injected. That might mean that this ticket is blocked by https://github.com/department-of-veterans-affairs/va.gov-team/issues/81506, where we'll be modifying https://github.com/department-of-veterans-affairs/content-build/blob/main/src/site/stages/build/plugins/modify-dom/update-external-links.js#L49 to stop the new tab business bigger picture, on PW side.

**Comment by jilladams** [comment]
Also: Public Websites is going to fix https://github.com/department-of-veterans-affairs/va.gov-team/issues/81506 in Sprint 4, so we'll know by end of Sprint 4 whether this gets fixed by it or not. 
Also: not a blocker for Staging Review.

**Comment by jilladams** [comment]
#81506 didn't make it into Sprint 4. I don't think we can / should block VBA launch on this.

**Comment by davidmpickett** [comment]
Confirmed on Tugboat that this is fixed: https://web-jdujzwgvp8kmj36hcfonqejlgtq5b6st.demo.cms.va.gov/philadelphia-va-regional-benefit-office/

![Screenshot 2024-06-18 at 11 56 50 AM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/38051e16-6785-44ba-a9e6-79438f566d50)


![Screenshot 2024-06-18 at 11 57 40 AM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/c767b788-8716-4e92-8db0-9376b52717e4)
