### ISSUE TITLE
[Aging Content] Edit the existing Full-width banner KB article with information regarding notification emails

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-cms#18006]
## Statuses
**[2024-09-23] [Fran]** Article updated and [saved as Draft](https://prod.cms.va.gov/node/34828/latest). [Message in Slack](https://dsva.slack.com/archives/C06EK4NLGDQ/p1727116105949039) to Jill/Michelle asking if they want to review.
**[2024-09-09] [Fran]** Message via Slack to Laura (and David P & Jill A) asking for a review of the verbiage.

## Description

As part of the Aging Content launch plan, we need to update the existing Full-width banner alert [editor-facing KB article](https://prod.cms.va.gov/help/homepage-alerts-and-promo-banners/how-to-do-i-create-a-full-width-alert-banner), expanding it with information regarding aging content notification emails.

### User story

**AS AN** editor who publishes content (e.g. full-width alerts/banners, blocks, etc.), 
**I WANT** to be able to reference a KB article to learn how aging content notifications work
**SO THAT** I'm not confused when I start receiving aging content notifications about my published content.

### Proposed KB Article Update:
_Proposed updates are in italics below._

https://prod.cms.va.gov/help/homepage-alerts-and-promo-banners/how-to-do-i-create-a-full-width-alert-banner

Best practices and content limitations
Learn more about best content practices in the VA.gov design system documentation.

- Only one full-width banner alert should be used on any given page.
- Always use a new alert! Re-using alerts may not refresh the experience for a Veteran or other site visitor who has previously dismissed that alert.
- Banners should be user-dismissible by default.
- Banners should be used for emergency or urgent communications that prompt a user to take action. They should be in-place for no more than 7-days _(including weekends)._
- _To ensure Veterans continue to rely on this content for current, relevant communication and don't visually dismiss stale content, the last published author of this content will receive emails reminding them to archive, or extend the display of the content by logging in to Drupal, editing the banner, and resaving it with a comment to that effect. The 7-day countdown window will then reset. At this time no action will be taken on expired content, but the emails will continue to be sent, and this will likely be enforced programmatically with auto-archiving in the near future._
- Heading field should be limited to 70 characters maximum, including spaces.
- Details field is limited to 300 characters maximum, including spaces.
- Heading and details should be targeted communications. Who needs to be aware of this alert and what action, if any, do they need to take. When more detail is needed, link to another page that has all of the details.

## Acceptance criteria

- [ ] KB article updates written
- [ ] Reviewed by Laura F.

_Noting here that Erika has approved the KB article being reviewed at the team level at this time.  She would like us to consult the [CMS Content Style Guide](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/cms/content-style-guide) and [VA Style Guide](https://design.va.gov/content-style-guide/) as references for how you choose to write and update. Although each of these resources are not specific to KB articles, the CMS team will be using them to create our KB template and guidance down the road. They are revamping KB article publication processes, and CMS review/approval is not needed in this particular instance._ Slack [thread ](https://dsva.slack.com/archives/CT4GZBM8F/p1715691916798699?thread_ts=1715628751.439249&cid=CT4GZBM8F)here. cc @jilladams @dsasser

**Comment by FranECross** [comment]
@FranECross Connect with Erika and ask that the support team reviews before we publish.

**Comment by dsasser** [comment]
## Update 5/24/24

Work has not yet begun due to sprint priority work taking priority. This may roll over as we have a holiday Monday, but not quite in the 🔴  status just yet.

**Comment by FranECross** [comment]
@dsasser If you don't object, I'm going to assign this to me, and will review the latest demo/video information so I can attempt to craft a KB article draft that you can then review/edit. That way you can concentrate on other stories.

**Comment by jilladams** [comment]
Hi! I have some random thoughts about this ticket: 

1. We need to get some sort of update on ticket since it's technically in sprint but: I think that update is: we actually aren't ready for this yet. I say that because: we know right now that Randi Hecht will be the only editor who receives these notifications initially, so the KB itself won't have much of an audience for awhile. Meantwhile: Fran, your time is probably better spent in the next sprint (or 2?) on Q3 strategic work to get priority initiatives understood / write briefs / do epic and ticket refining, etc etc.  SO: I'm going to remove from Sprint 7, and move back to Ready, and feel free to pull it back in when you have time to work on it. (Or: when you want to reassign it. )

2. When it _is_ time to do it:  I think this is Fran's first go-round with KB's. If you need tactical or moral support: I can help a little, @laflannery has a lot of history with the KB system, and the CMS team maintains a style guide that lives somewhere but I'm not sure where, so Grace / Michelle Dooley can probably help with that. I don't think there's any expectation you can figure it all out on your own.

**Comment by FranECross** [comment]
Closing this as a no op; decision was made that each content-type KB article will be edited to include information specific to that content type.

**Comment by FranECross** [comment]
@laflannery I answered in-line with your questions above (bold/italics with my name). Also, the KB article text has been updated in the ticket description. Thanks!

**Comment by FranECross** [comment]
Updated and published.
