### ISSUE TITLE
Add new Services View into Vet Centers node and remove IEF

### ISSUE THREAD

**Issue by davidmpickett** [department-of-veterans-affairs/va.gov-cms#18003]
## User Story or Problem Statement
Final Drupal implementation

## Description or Additional Context 
- Based on design in #17680: [Vet Center forms Figma](https://www.figma.com/file/qqQhab9SGhvDNZgRIdWS7g/Vet-Centers-forms?type=design&node-id=12%3A201&mode=design&t=ExecYwxiWZK4bTyS-1)

## Steps for Implementation
- Create the new view
- Follow design for "Add new service" button implementation, and to pass a token to Vet Center - Facility Service so the Facility is pre-populated
- Update Vet Center content type to embed this view
- Remove IEF from Vet Center
  - field_health_services should be Disabled rather than Removed, b/c [it powers FE query](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17681)

@davidmpickett says "Consider splitting creating the View into it's own ticket and letting this one serve as the step where you embed it in Vet Center content type and remove IEF" 

@omahane said "Nope, has to go together"

## Acceptance Criteria

- [x] Editors can see the existing Facility Services for their Vet Center while editing their Vet Center
- [x] Editors can see what services are required vs. not
- [x] Editors can see the moderation state of a listed Vet Center facility service
- [x] Editors can click out to a Vet Center facility service to edit
- [x] Editors can click the "Go to services" button in their dashboard and be taken directly to the relevant part of the Vet Center node edit
- [x] Appropriate services display on FE of Vet Center (no regression)
- [x] **SHOULD NOT MERGE until Change Management is coordinated** - #17840
- [ ] Requires design review
- [x] Requires accessibility review

```[tasklist]
### Close Child Tickets
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15125
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15124
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/5981
```

```[tasklist]
### Unblock follow up FE ticket
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16362
```

**Comment by jilladams** [comment]
8 point estimate for engineering; 5 points for standing up env / testing / support & verification

**Comment by Agile6MSkinner** [comment]
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15125
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15124
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/5981

Can be closed when this one is.

**Comment by jilladams** [comment]
Change management info is updated in https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17840 and target is 8/15, so this will roll into Sprint 10. @omahane best to plan some time around then for refreshing the PR to get updated to main / passing tests, etc.

**Comment by jilladams** [comment]
Updated branch on this PR and moved it to Ready to review.  We can merge tomorrow after daily deploy if CI passes.

**Comment by jilladams** [comment]
Comms went out to editors for CM last night. PR is now merged. Moving to prod verify.

**Comment by jilladams** [comment]
Changes have deployed and are live in prod: https://prod.cms.va.gov/node/3784/edit

I haven't gone through full verification, so we will need some help to do UAT for end of sprint just to verify that everything's correct live, and we can close this.

**Comment by davidmpickett** [comment]
Verified the following on [Clarksville Vet Center](https://prod.cms.va.gov/clarksville-vet-center)
- Services area shows up in appropriate spot on Node:Edit of Vet Center
- Service names are linked to Node:View of correct Services
- Edit buttons open Node:Edit of correct Service
- Add service button correctly pre-populates Vet Center and Section fields on Node:Create for Service
- All links open in new tab

**Comment by davidmpickett** [comment]
Verified on [Vet Center dashboard for Clarksville](https://prod.cms.va.gov/section/vha/vet-centers/clarksville-vet-center)

- Clicking the Go to Services button directly jumps the user top the Services part of the correct Vet Center

**Comment by davidmpickett** [comment]
Verified on [Staging for Clarksville Vet Center](https://prod.cms.va.gov/node/71230/edit?destination=/section/vha/vet-centers/clarksville-vet-center#edit-group-vet-center-services)
- Adding an Optional service shows up correctly as optional on Service list
- Required Services cannot be Archived
- Optional Services can be archived


![Screenshot 2024-08-19 at 1 48 12 PM](https://github.com/user-attachments/assets/e00d6e2a-3405-44bc-8b28-fc4f7658b56d)

![Screenshot 2024-08-19 at 1 50 03 PM](https://github.com/user-attachments/assets/d8d902cf-b05e-4a1a-8206-390464002024)

![Screenshot 2024-08-19 at 1 50 23 PM](https://github.com/user-attachments/assets/2af4cea4-299a-4da4-8a55-19742ef7222d)

**Comment by davidmpickett** [comment]
One small regression, the **Jump to edit** link at the top broke because the id for the Services area changes from
`#edit-field-health-services` to `#edit-group-vet-center-services`

I know that [we talked about spinning up a dedicated ticket](https://github.com/department-of-veterans-affairs/va.gov-cms/pull/18890#issuecomment-2287113351) for addressing all the Anchor Links on the Vet Center content types after @laflannery's feedback on the Mission explainer ticket. I am comfortable having that fix be part of that ticket.

**Comment by davidmpickett** [comment]
And here's that ticket: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18953

**Comment by davidmpickett** [comment]
Closing as complete and verified
