### ISSUE TITLE
[Aging Content] Write unit tests for the notifications framework (& full-width alert/banner if applicable)

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-cms#18005]
##  Status
**[2024-05-31]** This is currently blocked due to an error preventing Daniel from updating a composer package. He filed a ticket and reported to CMS.

## Description

Expand unit tests for the Aging Content 'framework', and if applicable, the full-width alert/banner code using the framework.

### User story

**AS A** PO/PM managing the new feature aging content notifications framework 
**I WANT** sufficient unit tests written
**SO THAT** if any failures occur in the notifications process, we are notified and corrections may be made.

### Engineering notes / background
Tests will need to be written for both custom code as well as the contributed Expirable Content module.

## Acceptance criteria
- [x] CreateAdvancedQueueJob ECA Action (Kernel/Unit tests)
- [ ] Expirable Content Views fields and filters (Kernel/Unit tests)
- [x] Expirable Content Computed field (Kernel  tests)
- [x] Expirable Content Calculation of expiration and warning dates (Unit tests)
- [ ] Test FWB end-to-end, save for mail receipt and delivery. Tests should assert that emails get queued correctly and with the expected content.

**Comment by FranECross** [comment]
@dsasser I'm good with postponing/striking the Views tests based on your info above. cc @jilladams

**Comment by dsasser** [comment]
@FranECross this issue is currently [blocked](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18257). I reported this to the Platform CMS team this morning via [Slack](https://dsva.slack.com/archives/CT4GZBM8F/p1717160406339979).

**Comment by dsasser** [comment]
## Status Update 5/6/24

This remains blocked while we wait for Platform CMS capacity to pick this up; they have been wrangling a lot of high priority issues and are working through their backlog as quickly as they can.

**Comment by dsasser** [comment]
These tests are now in prod.
