### ISSUE TITLE
QA / FE review of IIR contribs to LH V1 & FE code

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#18014]
## Description

IIR team updated vets-api Facilities API to use LIghthouse V1 endpoint. This created Facilities API V2 endpoint. 

They are now doing the FE work to integrate the Facility Locator to use the V2 endpoint. 

This may include: 
* vets-api PRs for update the API
* FE PRs in vets-website that update the Facility Locator

## AC
- [x] Review the code and make sure we can maintain it
- [x] Review the implementation in Facility Locator and make sure there's feature parity and no existing behavior breaks
  - [x] Run Facility Locator regression test suite: https://dsvavsp.testrail.io/index.php?/projects/overview/15

**Comment by eselkin** [comment]
I just keep reviewing the PRs as they come online. I don't think we can move this into in-progress until at least the last of their PRs is in review. Or maybe it is in-progress now since I've been reviewing their PRs.

**Comment by jilladams** [comment]
@eselkin can you confirm if you've been able to test in an environment, to see whether the changes affect anything in the Faciltiy Locator? Or will that only be possible once their FE changes are delivered for review?

**Comment by eselkin** [comment]
It'll only be possible once their changes are in vets-website. It requires too much for a quick check. But I did run a few tests in postman to see it worked and pagination on the va (LightHouse) endpoint worked.

**Comment by jilladams** [comment]
I did some random thinking about this testing for FE changes in [this slack thread](https://dsva.slack.com/archives/C0FQSS30V/p1715118168889079?thread_ts=1715117382.121629&cid=C0FQSS30V). I put my brain scrambles in a [trello card](https://trello.com/c/wypehHzq/468-facility-locator-fe-testing-regression-test-suite-in-testrail) for scrum tomorrow, to discuss. We can port relevant decisions back here and update ACs as needed.

**Comment by jilladams** [comment]
Discussed with Eli. Because the Frontend regression test is included in this ticket, we've increased estimate to 8. 

We need a document to guide regression testing. Jill to make a spreadsheet to spell out test cases. We can reference the 4yo Testrail cases for this, but investing in actually updating testrail is not necessarily the best use of time, esp since we're about to do a design iteration on the API / FE for mobile map, etc.

**Comment by jilladams** [comment]
Vets-api work from IIR is complete. They're now starting FE work to migrate the Facility Locator onto LH V1 / Facilities-api V2. This ticket will include the regression run to test that, so will continue into Sprint 4.

**Comment by jilladams** [comment]
Status on regression test plan: https://docs.google.com/spreadsheets/d/1wgIM4oIwAQk-E151z07P3hhZuQJ6mhepv7U5tZjdpEI/edit?usp=sharing

I've migrated the [Facility Locator Testrail cases](https://dsvavsp.testrail.io/index.php?/projects/overview/15)  out to a spreadsheet (they were a few years behind prod already), and have updated for state of truth in prod today. 

Spreadsheet includes general UI stuff (crumb, tab title, H1, form fields, default states), as well as expected results for:
* Each Facility type
* Re-searching using map zoom in/out, and click+drag
* Location-based behavior

@eselkin maybe we can chat in our 1:1 next week about what else we should be poking at in terms of API behavior, for verification. This testing regimen is very front-end UX heavy so far, and I don't think we expect _anything_ to change with the new API, but especially not UI behavior. If anything, the nature of the data returned will be the changeset and I don't think these old-now-refreshed test cases really get at that.

**Comment by jilladams** [comment]
V1 will use Drupal facility services as source of truth, where V0 didn't. Once V1 is integrated, we can identify cases where a Facility in Drupal offers a service, but that same Facility in the old LH CSV doesn't offer that service. Those are test cases to verify V1 implementation. We may need help to identify the right Facilities and services to use to test & verify.

**Comment by jilladams** [comment]
Q: In FL, in prod today: how is the Service type dropdown populated? Is it built from LH V0 API? Is it hard coded? 
Dave says: the existing list of 19 items (in very random sort order in prod) is from the legacy data source. (We don't know how it arrives into LH V0, and that's ok.)

We don't know (at product level) if this dropdown in the locator is hardcoded to map to the LH list, or if it's dynamically built from LH call or what. 

In the VA Services taxonomy, the camelCase (no spaces) Health Service API ID is the key being used between CMS and Lighthouse.

We need to also make sure this dropdown is correctly populated. (We need to define / document what "correctly" means?)

**Comment by mmiddaugh** [comment]
@jilladams @eselkin thanks for the opportunity to review the testing plan. I really appreciate the thorough and well-documented plan.  

A few additional thoughts:
- VA Health Facility Search
    - line 69: Service type input is active, and displays "All VA health services" -> suggest validation that the drop down list includes the expected list of options
- Urgent care
  -  Suggest validation of the alternate way to perform the same search -> searches for Facility type = VA health + Service type = Urgent care should present the same list of search results as searches for Facility type = Urgent care + Service type = VA urgent care
- Emergency care
  - Suggest validation of the alternate way to perform the same search -> searches for Facility type = VA health + Service type = Emergency care should present the same list of search results as searches for Facility type = Emergency care + Service type = VA emergency care
- Vet Center Facility Search
  - When clicking on the linked name of an Outstation from search results, the Locations page for the parent Vet Center loads
- Will validation be done in desktop? If so, do we need to account for any different behavior in the mobile experience?
- I assume there is no risk to the "escape hatch" link below the map (Can’t find what you’re looking for?   Try using our other tools to search.)
- Might there be any impact to the VAOS team which includes the Locator in their workflow for appointment scheduling?

**Comment by jilladams** [comment]
Made that a checklist and added the suggested cases. 

The changes being made here are all re: data connection and no actual changes to FE templates / UI, so we don't expect to see any behavior variance across desktop vs. mobile, but we can sanity check on mobile. 

re: escape hatch - presence of that markup is covered on line 25, but we don't expect that to be affected, no. 

VAOS: I don't know directly about that workflow. (This might be why we were using their API endpoints before?) They're sending people out to our locator? Maybe we should discuss this a bit to make sure we're on same page about it. Tagged for next scrum.

**Comment by jilladams** [comment]
We think: VAOS links out to the Facility Locator. Jeff Roof's team is on this, Lauren Ernst, Health Apps teams (can check ToT slides for that). @mmiddaugh  volunteered to work with @Agile6MSkinner to figure out workflow here, and we will flag in ToT.

**Comment by davidmpickett** [comment]
@eselkin @jilladams should this be considered In Progress due to y'alls work on the test plan?

Are we blocked from starting to test?

**Comment by jilladams** [comment]
Build delivered yesterday via PR, in testing now. Marking unblocked.

**Comment by eselkin** [comment]
All tests on the spreadsheet pass except for the Urgent Care tests we expected to change but those turned out to be dependent on ATC data rather than just CMS data.

**Comment by jilladams** [comment]
Noting for our mutual awareness: those Urgent care data cases were the only actual data test cases that we thought could help us verify V1 vs. V0, where the rest of the UI tests are safety but shouldn't have been affected by the API update. So: we don't have a great way to know with certainty that V1 is returning accurate data / same results as V0. @eselkin, it would probably be worth doing just a couple of side by side searches in prod vs. the RI to make sure we get same results, for a data sanity check.

**Comment by eselkin** [comment]
I ran the same steps I was doing in the local instance in staging (staging.va.gov) and got the same data. But I can run some side by side in prod as well.
