### ISSUE TITLE
[Metadata] Implement the Va.gov homepage metadata that is missing

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-cms#18020]
## Status
**[2024-09-30] [Fran]** Pull out all but the meta description and create another ticket for them. Fran to check our other products to determine if any metadata is missing; will create tickets as needed.
**[2024-07-29] [Fran]** Metadata provided by Danielle. Ticket moved to Next Refinement pipeline.
**[2024-07-26] [Fran]** Danielle responded and will provide the metadata.
**[2024-07-25] [Fran]** Message via [Slack](https://dsva.slack.com/archives/C01K37HRUAH/p1721944037232969) to CAIA asking for them to provide metadata, and how to go about formalizing the request.

## Description

Per Michelle, there is a new [Federal website standards](https://standards.digital.gov/) call for HTML page titles and meta descriptions for every page of your website

Standard for meta description = https://standards.digital.gov/standards/meta-page-description/

An independent audit of VA.gov as part of a school project has brought to our attention missing MetaData. All other checks garnered VA.gov an A (URL, Sitemap, and Robots).

Dave C. would like these to (eventually) be addressed, and considers this a low priority item.

### Steps to Reproduce
- Go to: https://scangov.org/
- With the Metadata radio button highlighted, enter VA.gov in the Search field
- Press Enter key

### User story

**AS A** PO/PM managing products in VA.gov
**I WANT** to ensure the metadata for the homepage in VA.gov is complete and accurate
**SO THAT** we don't lose the trust of Veterans, their family members, caregivers and survivors based on reports of our metadata, 

## Acceptance criteria

- [ ] Homepage (only) < meta name="description" > = Welcome to the official website of the U.S. Department of Veterans Affairs. Discover, apply for, and manage your VA benefits and care.

**Comment by DanielleThierryUSDSVA** [comment]
@FranECross Here's meta description text:

Welcome to the official website of the U.S. Department of Veterans Affairs. Discover, apply for, and manage your VA benefits and care.

Do you need the image alt text and other fields listed in the ticket or are you all set with those?

**Comment by FranECross** [comment]
@DanielleThierryUSDSVA If you're able to provide the other meta data, that would be amazing. It was mentioned a while ago it would be best coming from CAIA, if possible. 💖

**Comment by FranECross** [comment]
@FranECross Pull out the last three and have this description one refined and done.

Fran - check our other products to see if description is there. Create issues if not.

**Comment by randimays** [comment]
@FranECross We have some custom logic determining the meta description on certain pages. Here's where the code lives in content-build: https://github.com/department-of-veterans-affairs/content-build/blob/main/src/site/includes/metatags.drupal.liquid#L122-L138

Basically, if one of four fields (coming from Drupal) is set, it adds the meta description according to the given logic. There's no fallback for if the fields aren't set, which seems to be the case for most pages and we don't get that meta description.

For the purposes of this ticket, should we remove all custom meta description logic and implement one single meta description piece with the below content for every VA.gov page?

> Welcome to the official website of the U.S. Department of Veterans Affairs. Discover, apply for, and manage your VA benefits and care.

**Comment by FranECross** [comment]
@randimays I like your idea, but would like to get an opinion from @mmiddaugh , since we'll be removing custom descriptions on pages we don't own, and adding to all pages in VA.gov (which I think is an excellent idea). @mmiddaugh will you please review and let us know if you see any issues with us doing this? Thanks!

**Comment by FranECross** [comment]
Pinged Michelle in [Slack ](https://dsva.slack.com/archives/C52CL1PKQ/p1727883866717489)for visibility

**Comment by jilladams** [comment]
This needs a follow up to figure out: 
* Audit: What else is missing in metadata on other parts of PW / Facilities products, and tickets for those
* FE ticket: to create a backup when Drupal doesn't contain a metadata description
* Maybe: A "Drupalize" the homepage metadescription, so it's editable without a code change in the future

@FranECross will help make an audit for deeper inspection.

**Comment by mmiddaugh** [comment]
limiting this particular issue to the VA.gov homepage only but will get Mikki's insight for fallback descriptions for pages without fields populated to generate custom descriptions based on logic (as described by Randi above)

**Comment by FranECross** [comment]
> This needs a follow up to figure out:
> 
> * Audit: What else is missing in metadata on other parts of PW / Facilities products, and tickets for those
> * FE ticket: to create a backup when Drupal doesn't contain a metadata description
> * Maybe: A "Drupalize" the homepage metadescription, so it's editable without a code change in the future
> 
> [@FranECross](https://github.com/FranECross) will help make an audit for deeper inspection.

- [Epic created](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19390)
  - [Audit ticket created](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19391)

**Comment by chriskim2311** [comment]
Code complete and in PR. Having issues with testing will carry over.

**Comment by chriskim2311** [comment]
Update PR merged and will test tomorrow after deploy

**Comment by chriskim2311** [comment]
Verified on prod, closing!
