### ISSUE TITLE
[Discharge Upgrade Wizard] [UX] Provide design/UX logic to display questions after Discharge Year "Before 1992"

### ISSUE THREAD

**Issue by randimays** [department-of-veterans-affairs/va.gov-cms#18025]
## Status

[2024-05-10] Jordan reviewed this ticket. 
[2024-05-09] Jordan to review and estimate async.

## Description
If you select "Before 1992" as the Discharge Year in the flow, the Continue button does not show any more questions. We are likely missing display logic for this flow and it needs to be added.

### User story

**AS A** Veteran, their caregiver, family member or survivor
**I WANT** to be able to select  "Before 1992" as my Discharge Year, click Continue, and see additional questions to answer
**SO THAT** I can get accurate results at the end of the wizard for this particular flow

### Design

[DUW flow Mural board](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1696352911500/80253b1c7200212cbcbcfb940d2cf4a29fed8417?sender=u01810f3edbfc878c08be5925)

## Acceptance criteria
- [ ] Determine the logic flow if the user selects "Before 1992" as their Discharge Year
- [ ] Show the logic flow in Mural
- [ ] Notify Fran Cross so that can unblock the FE story

**Comment by FranECross** [comment]
@randimays Thanks for stubbing out the story! I turned this into a UX story, and will create a corresponding FE story after decisions are made and Mural updated. cc @thejordanwood

**Comment by thejordanwood** [comment]
@FranECross I explored this [on prod](https://www.va.gov/discharge-upgrade-instructions/questions) and reviewed the content doc linked in the Mural. 

- My understanding was an additional question was added only if the user selects the year that was 15 years ago (in this case 2009). 
- I wasn't able to determine on my own if there were additional questions added to the flow if a user selects "Before 1992". 
- I'll need to work with an engineer to figure out if questions are added and what that flow is.

**Comment by FranECross** [comment]
@thejordanwood I found the sharepoint document which shows logic around what should display according to what the user chooses. I wonder if this would be helpful? The info is on page 15... 
[DischargeUpgradeWizardContent - Copy for phase 1 text updates (1).docx](https://github.com/department-of-veterans-affairs/va.gov-cms/files/15338954/DischargeUpgradeWizardContent.-.Copy.for.phase.1.text.updates.1.docx)

**Comment by thejordanwood** [comment]
@FranECross I should have been clearer, this Sharepoint document is also linked in the Mural. I looked it over and didn't see anything that would impact the logic/question flow if a user selects "Before 1992". The content on page 15 is about the conditional content that appears on the results screen, which is already documented in the Mural. 

All of that being said, I do think having an engineer look at the code on prod would be beneficial. When I made the Mural, Chris found flows that weren't documented in the Sharepoint doc and they weren't obvious to me when trying to discover them on prod.

**Comment by FranECross** [comment]
@thejordanwood Thanks for clarifying! I'll have a Spike for an engineer to document the flow around that question..

**Comment by thejordanwood** [comment]
I asked about this [in a Slack](https://dsva.slack.com/archives/C52CL1PKQ/p1719859203878299) thread and confirmed that selecting "Before 1992" was just missing logic for that particular answer. Selecting "Before 1992" does not affect any logic flow and should follow the main flow documented in [the Mural board](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1696352911500/80253b1c7200212cbcbcfb940d2cf4a29fed8417?sender=u01810f3edbfc878c08be5925). 

@FranECross @chriskim2311 I'm going to close this ticket, but an engineering ticket will need to be created to add a logic flow to the "Before 1992" answer.

**Comment by FranECross** [comment]
@thejordanwood Thanks so much! I'll create the FE ticket today.
