### ISSUE TITLE
[V3 Components] Adopt component for white links on home page 

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-cms#18035]
## Description

In order to meet USDS Design Standards, we need to adopt the available white links component on the VA.gov home page.

### User story

**AS A** PO/PM for Public Websites products
**I WANT** to implement available V3 link component(s) on the VA.gov home page
**SO THAT** all PW products are in alignment with the current component version
**AND** Veterans and other users have a consistent experience throughout VA.gov tools and information

## Acceptance criteria

- [x] Home page links are using v3 component
- [ ] a11y review

**Comment by randimays** [comment]
This ticket pairs nicely with #17820. Pulling it in as Stretch

**Comment by randimays** [comment]
This is posted for review today. It most likely won't make the production deploy, so it will carry over to tomorrow.

**Comment by jilladams** [comment]
@FranECross @randimays This is rolling into the Facilities V3 epic, I think bc the PW epic is closed. Can this find a new epic home?

**Comment by FranECross** [comment]
@jilladams Just updated to one of our open V1/V3 epics. Thanks!

**Comment by randimays** [comment]
Successfully validated in production. Closing!
