### ISSUE TITLE
Restore Vet Center Outstation: Newington Vet Center Outstation

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-cms#18043]
## Description
> I am using this runbook although I'm not sure all the steps apply as this request is to restore an archived facility. 
> 
> @omahane , do we need a different runbook for this?

A request to restore the [Newington Vet Center Outstation](https://prod.cms.va.gov/manchester-vet-center/newington-outstation) (vc_1081OS) has been received from RCS. Per VAST, it is a valid location which should be associated with the [Manchester Vet Center](https://prod.cms.va.gov/section/vha/vet-centers/manchester-vet-center). 

There is a long history associated with this location. See also #12969

## Vet Center, Outstation, Mobile Vet Center facility name change - Description
Vet Centers, Mobile Vet Centers, and Vet Center Oustations may all be subject to name changes in VAST. Not all steps apply to each type of facility -- please pay attention and make sure you've done the relevant steps based on facility type.

## Intake
- [x] What triggered this runbook? (Flag in CMS, Help desk ticket, Product team, VHA Digital Media)
Trigger: Product team

- [ ] Link to associated help desk ticket (if applicable)
Help desk ticket: ???

- [x] Name of submitter (if applicable)
Submitter: Michelle Middaugh

- [x] If the submitter is an editor, send them links to any relevate KB articles for the Vet Center product. Let them know that facility changes can take between 75 days and 4 months after submitting a request, according to VAST administrators.
KB articles: N/A

- [x] Link to facility in production:
Facility CMS link: https://prod.cms.va.gov/manchester-vet-center/newington-outstation
Facility API ID: vc_1081OS

### CMS help desk steps
**Note: If the help desk is waiting on information from the facility staff or editor, add the "Awaiting editor" flag to the facility** with a log message that includes a link to this ticket. Remove the flag when the ticket is ready to be worked by the Facilities team. **Be sure to preserve the current moderation state of the node when adding or removing the flag.**
- [x] 1. The title (Name of Vet Center field) change comes from Lighthouse to Drupal & is flagged
- [x] 2. If the Vet Center published and is NOT an Outstation/MVC, create a [URL change request](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/new?assignees=&template=runbook-facility-url-change.md&title=URL+Change+for%3A+%3Cinsert+facility+name%3E), changing the entry from the old facility URL to the new facility URL. (**Note: The URL change request ticket blocks the completion of this ticket.**)

**No redirect or canonical URL change needed**

### CMS engineer steps - Vet Center only (not Outstation/MVC)
- [x] 3. Execute the steps of the URL change request ticket from step 2.: **N/A**

(Redirects deploy daily except Friday at 10am ET, or by requesting OOB deploy (of the revproxy job to prod) in #vfs-platform-support. Coordinate the items below and canonical URL change after URL change ticket is merged, deployed, and verified in prod.)

### Drupal Admin steps (CMS Engineer or Help desk)
_Help desk will complete these steps or escalate to request help from CMS engineering._

**If a Mobile Vet Center or Outstation**
- [x] 4. Verify which Vet Center it belongs to, and confirm that the "Main Vet Center Location" field is set correctly.

#### CMS Help desk (wrap up)
- [x] 11. Notify editor and any other stakeholders.

**Comment by mmiddaugh** [comment]
@Agile6MSkinner this needs to come into the next sprint as Flagged Facility work

**Comment by Agile6MSkinner** [comment]
Ok, done. I would like to start including buffer in our velocity for these tickets since they seem to come up frequently. If we don't get any, we can pull work in.

**Comment by omahane** [comment]
@jilladams @Agile6MSkinner @ian-sears The facility has been published. After content release, va.gov should reflect the facility's publication. It's associated with https://www.va.gov/manchester-vet-center/ and should be listed on that page, subsequently. No other work is required after informing the editor.

**Comment by jilladams** [comment]
Assigning @ian-sears @TroyCMSSupport for editor notification after we verify deploy.

**Comment by jilladams** [comment]
Ready for editor outreach! 
https://www.va.gov/manchester-vet-center/locations/
![Screenshot 2024-06-26 at 5 20 37 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/85581471/ba2a1451-eae2-43f3-9eb5-211d8b12f315)

**Comment by jilladams** [comment]
@TroyCMSSupport @ian-sears mind taking al ook here and verifying if the Editor outreach has been done? Thanks!

**Comment by ian-sears** [comment]
Can do.
