### ISSUE TITLE
Next Build content release workflow should be able to deploy to dev.va.gov and staging.va.gov

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#18046]
## Requirements

We want to be able to release content via Next Build to dev.va.gov and staging.va.gov, so that Next Build content is appropriately represented on those environments.

```[tasklist]
### Acceptance criteria
- [x] Next Build content release workflow is updated to be able to choose different build destinations from a manual dispatch
- [x] Workflow creates and publishes Next Build content to the appropriate S3 destination based on the build type
- [x] Workflow defaults to prod if no build destination input is present
- [x] Workflow concurrency is set up so that only one prod, staging, and dev workflow can be running at a given time
- [x] Success & Failure events reach Datadog with appropriate labeling
```

## Background & implementation details

Documentation for GHA:
- https://docs.github.com/en/actions
- https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions

Note that this work will be done in the [next-build repo](https://github.com/department-of-veterans-affairs/next-build/). 

The Next Build content release workflow is here: https://github.com/department-of-veterans-affairs/next-build/blob/main/.github/workflows/content-release.yml

Currently, the workflow triggers on the following events:
- `repository_dispatch`: this is a trigger due to an API call
- `workflow_run`: this is a trigger due to another workflow running, in this case the Continuous Integration workflow on the `main` branch.

The workflow should be updated to be triggerable with a `workflow_dispatch` event, which is a manual trigger event. See GHA documentation: https://docs.github.com/en/enterprise-cloud@latest/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch

`workflow_dispatch` events can include 'inputs' which can in turn be used to pass information to the worfklow. We will add a `build_type` input which can take one of these values: `prod`, `staging`, `dev`. `build_type` in turn will allow us to choose different values in the workflow so that we can build to specific destinations.

The following are values in the workflow that are specific to the production build:
- `APP_ENV`: what type of build we are outputting: currently [prod](https://github.com/department-of-veterans-affairs/next-build/blob/main/.github/workflows/content-release.yml#L106) 
- `DEST`: where the content should be published to; currently https://github.com/department-of-veterans-affairs/next-build/blob/main/.github/workflows/content-release.yml#L169

The values for all environments: 

| APP_ENV | DEST |
| --- | --- |
| prod | s3://next-content.www.va.gov |
| staging | s3://next-content.staging.va.gov |
| dev | s3://next-content.dev.va.gov |
 
We want to modify the workflow so that based on the input selection for build_type, `APP_ENV` and `DEST` are set appropriately. 

For Github Actions, there are a number of different strategies that can be used to conditionally set environment or output variables based on input or other varying values. This workflow shows one strategy - it runs a job at the beginning of the workflow which sets a number of values for use later by subsequent jobs. https://github.com/department-of-veterans-affairs/vets-website/blob/main/.github/workflows/manual-deploy-dev-staging.yml#L29-L51

Additionally, the `APP_ENV` should be used for sending information to Datadog: 
- https://github.com/department-of-veterans-affairs/next-build/blob/main/.github/workflows/content-release.yml#L213
- https://github.com/department-of-veterans-affairs/next-build/blob/main/.github/workflows/content-release.yml#L267

This value should match `APP_ENV`. Events reaching Datadog can be validated in the Datadog Event Explorer by searching for the text `next-build`, like this: https://vagov.ddog-gov.com/event/explorer?query=next-build%20&cols=&messageDisplay=expanded-lg&options=&refresh_mode=sliding&sort=DESC

Please be sure to modify the time being investigated by the explorer if necessary. It defaults to the previous 15 minutes.

The workflow should be set up with concurrency settings such that only one of each environment deploy can be running at a given time. In other words, a staging and a dev run of the workflow can be run at the same time, but it should not be possible to run two dev runs at the same time. See Github Actions documentation for more information on concurrency: https://docs.github.com/en/enterprise-cloud@latest/actions/using-jobs/using-concurrency

Finally, note that we will not be able to directly verify seeing Next Build output built to dev.va.gov / staging.va.gov directly until the reverse proxy changes have gone through. Therefore, validating the build at this stage should simply consist of confirming that the contents of the S3 buckets look appropriate, via AWS console. For example, this is the current contents for the prod bucket (s3://next-content.www.va.gov):

<img width="893" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/203623/0602d0ba-4b0e-44e2-819b-4fa3fd9360dd">

In order to confirm a build that you are observing or working on, you can drill into one of the directories until you find an output file, which will have time information on it:

<img width="879" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/203623/eee15a6e-5e54-4dd7-9188-0e5017309751">

**Comment by mreed101** [comment]
This has been merged to main
