### ISSUE TITLE
Regular expression denial of service in scss-tokenizer

### ISSUE THREAD

**Issue by edmund-dunn** [department-of-veterans-affairs/va.gov-cms#18055]
## Description
This is partly a discovery ticket. If you find this is blocked because of version issues, especially with node please annotate that in the [Confluence page ](https://vfs.atlassian.net/wiki/spaces/PRT/pages/2942369846/Code+Scanning+Fixes+Required+for+WASA+scan+in+support+of+Preview+Environments.) and here in the ticket. 

One other package sass-graph depends on an early version of this. Worst case is that two packages need to be upgraded, so this shouldn’t be too difficult.

## Acceptance Criteria

- [ ] Upgrade scss-tokenizer to >= 0.4.3

**Comment by JakeBapple** [comment]
Currently, I believe the node-sass package requires sass-graph, which requires scss-tokenizer. So I believe we need to update the dependency of the tokenizer and graph within node-sass.

**Comment by JakeBapple** [comment]
this PR was merged and the work here should be good to go @gracekretschmer-metrostar 

https://github.com/department-of-veterans-affairs/content-build/pull/2182
