### ISSUE TITLE
Add 'Last Saved by an Editor' field to FE graphql queries

### ISSUE THREAD

**Issue by dsasser** [department-of-veterans-affairs/va.gov-cms#18065]
## Description
Relates to: #16333 

CMS nodes have a `field_last_changed_by_an_editor` field that represent the date when an editor last changed the content in the UI. If the node has this value, it should used as the canonical "last changed" date in both the sitemap and the page templates.

In order to add the field_last_changed_by_an_editor field to the FE, we need to include it in all graphql queries for the following node types:

[VAMC Facility Non-clinical Service](https://staging.cms.va.gov/admin/structure/types/manage/vha_facility_nonclinical_service/fields), [Vet Center - Outstation](https://staging.cms.va.gov/admin/structure/types/manage/vet_center_outstation/fields), [Vet Center - Mobile Vet Center](https://staging.cms.va.gov/admin/structure/types/manage/vet_center_mobile_vet_center/fields), [Vet Center - Locations List](https://staging.cms.va.gov/admin/structure/types/manage/vet_center_locations_list/fields), [Vet Center - Facility Service](https://staging.cms.va.gov/admin/structure/types/manage/vet_center_facility_health_servi/fields), [Vet Center - Community Access Point](https://staging.cms.va.gov/admin/structure/types/manage/vet_center_cap/fields), [Vet Center](https://staging.cms.va.gov/admin/structure/types/manage/vet_center/fields), [VBA Facility Service](https://staging.cms.va.gov/admin/structure/types/manage/vba_facility_service/fields), [VBA Facility](https://staging.cms.va.gov/admin/structure/types/manage/vba_facility/fields), [VA Form](https://staging.cms.va.gov/admin/structure/types/manage/va_form/fields), [VAMC System Register for Care](https://staging.cms.va.gov/admin/structure/types/manage/vamc_system_register_for_care/fields), [VAMC System Policies Page](https://staging.cms.va.gov/admin/structure/types/manage/vamc_system_policies_page/fields), [VAMC System Medical Records Office](https://staging.cms.va.gov/admin/structure/types/manage/vamc_system_medical_records_offi/fields), [VAMC System Billing and Insurance](https://staging.cms.va.gov/admin/structure/types/manage/vamc_system_billing_insurance/fields), [VAMC System Operating Status](https://staging.cms.va.gov/admin/structure/types/manage/vamc_operating_status_and_alerts/fields), [Support Service](https://staging.cms.va.gov/admin/structure/types/manage/support_service/fields), [Resources and Support Detail Page](https://staging.cms.va.gov/admin/structure/types/manage/support_resources_detail_page/fields), [Stories List](https://staging.cms.va.gov/admin/structure/types/manage/story_listing/fields), [Step-by-Step](https://staging.cms.va.gov/admin/structure/types/manage/step_by_step/fields), [VAMC System Health Service](https://staging.cms.va.gov/admin/structure/types/manage/regional_health_care_service_des/fields), [Reusable Q&A](https://staging.cms.va.gov/admin/structure/types/manage/q_a/fields), [Publication Listing Page](https://staging.cms.va.gov/admin/structure/types/manage/publication_listing/fields), [Promo Banner](https://staging.cms.va.gov/admin/structure/types/manage/promo_banner/fields), [News Releases List](https://staging.cms.va.gov/admin/structure/types/manage/press_releases_listing/fields), [News Release](https://staging.cms.va.gov/admin/structure/types/manage/press_release/fields), [Staff Profile](https://staging.cms.va.gov/admin/structure/types/manage/person_profile/fields), [Benefits Detail Page](https://staging.cms.va.gov/admin/structure/types/manage/page/fields), [Publication](https://staging.cms.va.gov/admin/structure/types/manage/outreach_asset/fields), [Office](https://staging.cms.va.gov/admin/structure/types/manage/office/fields), [Story](https://staging.cms.va.gov/admin/structure/types/manage/news_story/fields), [NCA Facility](https://staging.cms.va.gov/admin/structure/types/manage/nca_facility/fields), [Video list](https://staging.cms.va.gov/admin/structure/types/manage/media_list_videos/fields), [Image list](https://staging.cms.va.gov/admin/structure/types/manage/media_list_images/fields), [VAMC System Locations List](https://staging.cms.va.gov/admin/structure/types/manage/locations_listing/fields), [Leadership List](https://staging.cms.va.gov/admin/structure/types/manage/leadership_listing/fields), [Benefits Hub Landing Page](https://staging.cms.va.gov/admin/structure/types/manage/landing_page/fields), [Health Services List](https://staging.cms.va.gov/admin/structure/types/manage/health_services_listing/fields), [VAMC System](https://staging.cms.va.gov/admin/structure/types/manage/health_care_region_page/fields), [VAMC Detail Page](https://staging.cms.va.gov/admin/structure/types/manage/health_care_region_detail_page/fields), [VAMC Facility Health Service](https://staging.cms.va.gov/admin/structure/types/manage/health_care_local_health_service/fields), [VAMC Facility](https://staging.cms.va.gov/admin/structure/types/manage/health_care_local_facility/fields), [VAMC System Banner Alert with Situation Updates](https://staging.cms.va.gov/admin/structure/types/manage/full_width_banner_alert/fields), [FAQ page](https://staging.cms.va.gov/admin/structure/types/manage/faq_multiple_q_a/fields), [Events List](https://staging.cms.va.gov/admin/structure/types/manage/event_listing/fields), [Event](https://staging.cms.va.gov/admin/structure/types/manage/event/fields), [CMS Knowledge Base Article](https://staging.cms.va.gov/admin/structure/types/manage/documentation_page/fields), [Checklist](https://staging.cms.va.gov/admin/structure/types/manage/checklist/fields), [Centralized Content](https://staging.cms.va.gov/admin/structure/types/manage/centralized_content/fields), [Campaign Landing Page](https://staging.cms.va.gov/admin/structure/types/manage/campaign_landing_page/fields), [Landing Page](https://staging.cms.va.gov/admin/structure/types/manage/basic_landing_page/fields), [Full Width Alert](https://staging.cms.va.gov/admin/structure/types/manage/banner/fields), [Service Region](https://staging.cms.va.gov/admin/structure/types/manage/service_region/fields), [VAMC System VA Police page](https://staging.cms.va.gov/admin/structure/types/manage/vamc_system_va_police/fields)

### Engineering notes / background

The compilePage() method already contains the changes necessary to realize the change we are making to add the last changed by editor field.

~In addition to adding the field to the graphql queries, the src/site/includes/last-updated.drupal.liquid template needs to be updated to use stats.mtime if it is available (stats.mtime is added to the page template in compilePage() and represents the value following this logic: use the value from field_last_saved_by_an_editor if it is available on the content
use the lastmod value from the changed property if field_last_saved_by_an_editor is not availableRather than reproducing that logic in the template, it may be better to use stats.mtime en lieu of the 'changed' conditional currently in place (or in addition to it, providing the above rules are followed).~

## Acceptance criteria

- [ ] include the field > field_last_changed_by_an_editor in all graphql queries for the node types noted above
- [ ] confirm that the last changed by an editor field is reflected in the sitemap.

**Comment by FranECross** [comment]
@dsasser I added AC to this story based on your description and engineering notes and moved the ticket to Next Refinement; as always, feel free to edit.

**Comment by dsasser** [comment]
@FranECross just thinking that we might want to engage with the AP team on our recent sitemap changes so that they can track replicating functionality in their repo.

**Comment by dsasser** [comment]
## Status update 6/11/24

This work is in PR https://github.com/department-of-veterans-affairs/content-build/pull/2126

The review instance didn't come up, however. Github is reporting: This branch has not been deployed

I'll need to spin up a tugboat and test there, but given the onsite at DC this week I will be delayed in doing so.

**Comment by dsasser** [comment]
## Implementation note

There were a couple places in GraphQL queries that needed to change in order to satisfy this issue.

1. A common fragment used by many content types
2. Some per-entity queries
3. Unchanged fragment queries (queries used by other queries, where the last updated date would have no meaning).

Here are my notes on changes made for each content type:

Change | Content Type
-- | --
No detail page | centralized_content
No detail page | documentation_page
No detail page | health_care_local_facility
No detail page | health_care_local_health_service
No detail page | nca_facility
No detail page | service_region
No detail page | support_service
No detail page | vet_center_facility_health_servi
No detail page | vha_facility_nonclinical_service
Updated GQL query | banner
Updated GQL query | campaign_landing_page
Updated GQL query | checklist
Updated GQL query | event
Updated GQL query | full_width_banner_alert
Updated GQL query | news_story
Updated GQL query | outreach_asset
Updated GQL query | promo_banner
Updated GQL query | vamc_system_policies_page
Updated GQL query | vet_center
Updated GQL query | vet_center_cap
Updated GQL query | vet_center_locations_list
Updated GQL query | vet_center_mobile_vet_center
Updated GQL query | vet_center_outstation
Uses common fragment | basic_landing_page
Uses common fragment | event_listing
Uses common fragment | faq_multiple_q_a
Uses common fragment | health_care_region_detail_page
Uses common fragment | health_care_region_page
Uses common fragment | health_services_listing
Uses common fragment | landing_page
Uses common fragment | leadership_listing
Uses common fragment | locations_listing
Uses common fragment | media_list_images
Uses common fragment | media_list_videos
Uses common fragment | office
Uses common fragment | page
Uses common fragment | person_profile
Uses common fragment | press_release
Uses common fragment | press_releases_listing
Uses common fragment | publication_listing
Uses common fragment | q_a
Uses common fragment | regional_health_care_service_des
Uses common fragment | step_by_step
Uses common fragment | story_listing
Uses common fragment | support_resources_detail_page
Uses common fragment | vamc_operating_status_and_alerts
Uses common fragment | vamc_system_billing_insurance
Uses common fragment | vamc_system_medical_records_offi
Uses common fragment | vamc_system_register_for_care
Uses common fragment | vamc_system_va_police
Uses common fragment | va_form
Uses common fragment | vba_facility
Uses common fragment | vba_facility_service

**Comment by jilladams** [comment]
@FranECross @dsasser I know y'all talked about this today. Could one of you update on ticket here to reflect where we landed with it?

**Comment by dsasser** [comment]
@jilladams this has been merged and will go out with the next release which should be tomorrow (as today is a holiday).

**Comment by dsasser** [comment]
Verified on prod:

![Screenshot 2024-06-24 at 12 45 16 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/221539/61aedd3c-7e93-417e-a5b3-269ddc40f96d)
![Screenshot 2024-06-24 at 12 42 41 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/221539/ac343207-8f45-4e4c-970e-241dde40421c)
