### ISSUE TITLE
Content-build build stage crashes due to EMFILE error

### ISSUE THREAD

**Issue by eselkin** [department-of-veterans-affairs/va.gov-cms#18069]
## User Story or Problem Statement

Content-build has EMFILE error of opening too many files. This should be caught gracefully by gracefulfs; but because it is being used by process.memoryUsage it seems to be outside the bounds of gracefulfs's handling.

## Description or Additional Context 

```
Error: EMFILE: too many open files, uv_resident_set_memory
    at process.memoryUsage (internal/process/per_thread.js:153:5)
    at Timeout._onTimeout (/var/lib/tugboat/docroot/vendor/va-gov/content-build/src/site/stages/build/silversmith.js:182:31)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7) {
  errno: -24,
  code: 'EMFILE',
  syscall: 'uv_resident_set_memory'
}
```

## Steps for Implementation

Wrap process execution of memoryUsage in try/catch blocks. Garbage collection still seems to occur correctly when memUsage calls result in errors.

## Acceptance Criteria
- [x] Build stages complete

**Comment by davidmpickett** [comment]
@eselkin Is this something we can verify positively on Prod? or is it more that we just don't see things crash?

**Comment by eselkin** [comment]
In the CI builds, I'm not seeing the error pop up so it seems it doesn't happen. I just wanted to place a guard on it in case it does happen. It does occur currently on tugboat builds, which is why we needed the fix for testing purposes. Likely it's a system configuration issue solely on the AWS instance that runs all the tugboats, but it's better to be safe than sorry.

**Comment by davidmpickett** [comment]
@eselkin So this ticket is closable, since there's nothing to verify on prod?
