### ISSUE TITLE
Prep CMS Audit from VA 508 Office 

### ISSUE THREAD

**Issue by gracekretschmer-metrostar** [department-of-veterans-affairs/va.gov-cms#18077]
## User Story or Problem Statement
The CMS team needs to understand what is needed to begin the audit process from the 508 office. 

## Description or Additional Context 
In the VA, there is a 508 Accessibility Office that will do audit of systems, to evaluate their technology using accessibility standards. The CMS has never undergone this audit, but will likely be required to be audited in the future. Therefore, the CMS team wants to proactively begin the audit process with the 508 office and, in turn, use the results to build out an accessibility backlog for CMS developers to work on. 

## Steps for Implementation
- Talk to Martha in the 508 Office
- Talk to Cerner/Serner Medical Apps, because they recent went through this audit
- Talk to PW and facilities team to understand the most common user flows and existing UXR for user personas and user flows.

## Acceptance Criteria
- [x] A plan of action to kick off the audit with the 508 Office.
- [x] 2-3 common user flows per user type.
- [x] Identify test user accounts for the 508 office that have the correct permissions
  - [x] Admin
  - [x] Editor
  - [x] Reviewer
- [x] Compile a list of known accessibility issues
- [x] Spin up demo site

**Comment by srancour** [comment]
@gracekretschmer-metrostar I think we should take off this task from the ticket:

> * Compile a list of known accessibility issues.

This is basically the same as the backlog work (#17936) I'm still working on and wouldn't be done at the end of the sprint that this is the goal of. Unless this can just be the existence of the [Accessibility board](https://github.com/orgs/department-of-veterans-affairs/projects/1246) that I'm still putting tickets into?

**Comment by gracekretschmer-metrostar** [comment]
@srancour I think it's find to point to the Accessibility board and communicate your current process of evaluating the backlog with the 508 office.

**Comment by srancour** [comment]
Questions to ask Chris on Tuesday: 

- Are there any deadlines to implement? 
  - I'm assuming no from memory of other team audits and because it is an internal facing tool.
- Will the 508 office come back with priority levels?
  - I'm assuming yes and that they will be following the [Accessibility defect severity rubric](https://depo-platform-documentation.scrollhelp.site/developer-docs/accessibility-defect-severity-rubric) that we already have labels for in Github: 
    - [a11y-defect-0](https://github.com/department-of-veterans-affairs/va.gov-cms/labels/a11y-defect-0)
    - [a11y-defect-1](https://github.com/department-of-veterans-affairs/va.gov-cms/labels/a11y-defect-1)
    - [a11y-defect-2](https://github.com/department-of-veterans-affairs/va.gov-cms/labels/a11y-defect-2)
    - [a11y-defect-3](https://github.com/department-of-veterans-affairs/va.gov-cms/labels/a11y-defect-3)
    - [a11y-defect-4](https://github.com/department-of-veterans-affairs/va.gov-cms/labels/a11y-defect-4)

**Comment by srancour** [comment]
They will provide us:

- Sampling audit readout with issues.
  - Critical, High, Medium, and Low. They also have an Accessibility defect label which doesn't affect score, but is a callout of what could be done better.
  - They have an Audit tracking tool
    - Just started using the tool in November
    - Martha and Erika will be the contacts for the tool and will be able to mark issues as done
    - Can request re-audit when things are fixed to be signed off
    - They will run audits to see what issues are sticking around for 6 months/1 year to make sure things are getting done

They should be able to get the audit back to us in a week or two after access is given if Chris does the audit himself, which he thinks he will, or 4-6 weeks if it goes off to the contractors.

Tasks for CMS Team:

- Create 3 test users
  - Admin
  - Editor
  - Reviewer
- Create 2-3 common user flows per user type.

They keep the audit request ticket open for 6 weeks and then will close and mark as "platform not ready" if we haven't gotten the flows/access to them by then.

**Comment by srancour** [comment]
@edmund-dunn suggested instead of using staging to use a demo site to make sure it doesn't go down for deployments randomly. He also said that we can just identify users with the permissions we need instead of creating test users.

**Comment by gracekretschmer-metrostar** [comment]
Thanks, @srancour for taking notes and updating the ticket. With the adjustments, do you still feel on track to complete this ticket by the end of this sprint (6/5)? If not, I am leaning towards refining the ticket to be achievable, since this is a sprint goal. My assumption is that the biggest lift will be identifying those most common user flows. 

cc: @michelle-dooley

**Comment by srancour** [comment]
@gracekretschmer-metrostar I agree that the biggest lift is now identifying those most common user flows and I do still feel on track and think this can still be completed in this sprint. I will add the caveat that with needing to reach out to the Facilities and Public Websites to help with identifying those user flows it could become larger than I'm currently thinking especially if they haven't captured this information in someway or could easily extrapolate it.

I did reach out to figure out who the current designers are now for both teams especially since the Facilities contract had recently rolled and some people changed. So things are already in motion and I still feel good about being able to complete this within the sprint even with the scope change.

**Comment by srancour** [comment]
[Tugboat demo site](https://main-q9xabvkysjsd684szf0orih2iznyznvg.demo.cms.va.gov/) and [Troubleshooting link](https://tugboat.vfs.va.gov/6660cd5917e38363d3c23807) provided by @timcosgrove

**Comment by srancour** [comment]
Data from the last year (June 3, 2023-June 3, 2024):

Total content changes: 74,693

- Added: 11,976
- Deleted: 60
- Reverted: 183
- Updated: 62,474

Unique UIDs: 729

Sections assigned to users:
Crossover entries in data below (users with multiple sections assigned): 18,885
- Benefits Hub
  - Total content changes: 520
    - Added: 15
    - Deleted: 0
    - Reverted: 0
    - Updated: 505
- Campaign Landing Pages
  - Total content changes: 497
    - Added: 110
    - Deleted: 0
    - Reverted: 1
    - Updated: 386
- VA.gov CMS Knowledge Base
  - Total content changes: 18
    - Added: 0
    - Deleted: 0
    - Reverted: 0
    - Updated: 18
- Not Assigned
  - Total content changes: 979
    - Added: 183
    - Deleted: 0
    - Reverted: 0
    - Updated: 796
- OPIA
  - Total content changes: 5
    - Added: 0
    - Deleted: 0
    - Reverted: 0
    - Updated: 5
- Outreach Hub
  - Total content changes: 16,994
    - Added: 3,849
    - Deleted: 0
    - Reverted: 15
    - Updated: 13,131
- Regional Benefit Office
  - Total content changes: 91
    - Added: 25
    - Deleted: 0
    - Reverted: 0
    - Updated: 66
- Resources and Support
  - Total content changes: 532
    - Added: 20
    - Deleted: 0
    - Reverted: 0
    - Updated: 512
- Sections
  - Total content changes: 8,348
    - Added: 358
    - Deleted: 60
    - Reverted: 127
    - Updated: 7,803
- Sitewide Content
  - Total content changes: 529
    - Added: 15
    - Deleted: 0
    - Reverted: 0
    - Updated: 514
- VACO
  - Total content changes: 5
    - Added: 0
    - Deleted: 0
    - Reverted: 0
    - Updated: 5
- VAMC/Medical Centers/health centers
  - Total content changes: 56,208
    - Added: 9,492
    - Deleted: 0
    - Reverted: 29
    - Updated: 46,693
- VBA
  - Total content changes: 629
    - Added: 35
    - Deleted: 0
    - Reverted: 0
    - Updated: 594
- VEO
  - Total content changes: 448
    - Added: 110
    - Deleted: 0
    - Reverted: 1
    - Updated: 337
- Vet Centers
  - Total content changes: 2,560
    - Added: 89
    - Deleted: 0
    - Reverted: 18
    - Updated: 2,453
- VHA
  - Total content changes: 128
    - Added: 9
    - Deleted: 0
    - Reverted: 0
    - Updated: 119
- VISN
  - Total content changes: 5,087
    - Added: 766
    - Deleted: 0
    - Reverted: 8
    - Updated: 4,313

**Comment by srancour** [comment]
Full data can be viewed currently in [Google Sheets](https://docs.google.com/spreadsheets/d/1Pgzm-Bqgy7UEOQ-gv4P9B1m64xXdSJ-lIRGtwfF7aj0/edit?usp=sharing)

**Comment by srancour** [comment]
> * VAMC/Medical Centers/health centers
>   
>   * Total content changes: 56,208
>     
>     * Added: 9,492
>     * Deleted: 0
>     * Reverted: 29
>     * Updated: 46,693

> * VISN
>   
>   * Total content changes: 5,087
>     
>     * Added: 766
>     * Deleted: 0
>     * Reverted: 8
>     * Updated: 4,313

Going through the flows I'm realizing I should mix these into one filter:

VAMC/VISN/Medical Centers/health centers
Total content changes: 61,080
Added: 10,234
Deleted: 0
Reverted: 37
Updated: 50,815

**Comment by srancour** [comment]
Vet Center:
- Users to use
  - 4730: jeffrey.deluca@va.gov

- Flows:
  - Review and edit Main Center page -
    - Knowledge base explanation flow: Knowledge Base - Vet Centers - Vet center content review
    - Edit flow: follow knowledge base explanation on Vet center content review and edit and add one item of each type available to add. Remove and add a photo as well.


VISN/VAMC/Medical Centers/health centers:
- User to use
  - 5014: Dennis.Ranch@va.gov

- Flows
  - Health care local health service -
    - Knowledge base explanation flow: Knowledge Base - VA Medical Centers (VAMCs) - How to add, edit, or remove a VAMC facility health service
    - Add flow: Manage in top menu - Content in sub menu - add content - VAMC Facility Health Service
    - Edit flow: select section (VISN 10) - VA Ann Arbor health care - Content type dropdown menu and select VAMC Facility Health Service - Filter - Edit

  - Health care region page - 13,960
    - Knowledge base explanation flow: Knowledge Base - VA Medical Centers (VAMCs) - How to edit a VAMC Healthcare System homepage
    - Edit flow: select section (VISN 10) - VA Ann Arbor health care - Content type dropdown menu and select VAMC System - Filter - Edit

  - Person profile - 7,087
    - Knowledge base explanation flow: Knowledge Base - VA Medical Centers (VAMCs) - How to edit or add a staff profile
    - Add flow:
      - Verify staff profile doesn't exist: Manage in top menu - Content in sub menu - Title field enter last name - select Staff Profile in content type dropdown - Filter - verify doesn't exist 
      - Add new: Manage in top menu - Content in sub menu - add content - staff profile

  - Event - 6,468
    - Knowledge base explanation flow: Knowledge Base - VA Medical Centers (VAMCs) - How to add a new event
    - Add flow: Manage in top menu - Content in sub menu - add content - event

  - News - 4,182
    - Knowledge base explanation flow: Knowledge Base - VA Medical Centers (VAMCs) - How to add a story
    - Add flow: Manage in top menu - Content in sub menu - add content - story


Outreach hub:
- User to use:
  - 4982: Michael.Billings@va.gov

- Flows
  - Outreach materials
    - Knowledge base explanation flow: Knowledge Base - Outreach Hub - How to add, edit, or remove outreach materials in the Outreach Library
    - Add flow: Manage in top menu - Content in sub menu - add content - Publication
    - Edit flow: Manage in top menu - Content in sub menu - Content type dropdown menu and select Publication - Filter - Edit
