### ISSUE TITLE
Update core to 10.2.5

### ISSUE THREAD

**Issue by gracekretschmer-metrostar** [department-of-veterans-affairs/va.gov-cms#18072]
## User Story or Problem Statement
Update core to 10.2.5

## Reference Tickets
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16898
- https://github.com/department-of-veterans-affairs/va.gov-cms/pull/16899
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15332

## Steps for Implementation
Make sure ddev is running locally
Run the following command: ddev composer update drupal/core-recommended drupal/core-composer-scaffold -W
See if any module has failed and needs to be updated/removed/flagged

### NOTES
The following error has been noted and will not be addressed in the near future so you can ignore:
 - Package webmozart/path-util is abandoned, you should avoid using it. Use symfony/filesystem instead.
Also, the composer.json file may not need to be changed as the ^ notation is there for both required packages at ^10.2.0 (which should cover all updates in the 10.2 era).

## Acceptance Criteria
- [ ]  Core update to 10.2.5 (updating to 10.2.6 instead)

**Comment by gracekretschmer-metrostar** [comment]
@edmund-dunn I reviewed a few of the past Drupal core upgrade tickets to structure this ticket and linked those tickets under the reference ticket section. Can you review and, if needed, edit?

**Comment by gracekretschmer-metrostar** [comment]
@JakeBapple what's the status of this work? Do you think you could have it completed by next sprint (6/5)?

**Comment by JakeBapple** [comment]
@gracekretschmer-metrostar I believe I can do this work by that timeline!  @edmund-dunn I see you recently updated core, I may tag you on any steps you took in terms of checking dependencies.

**Comment by gracekretschmer-metrostar** [comment]
@JakeBapple if you want Edmund's support, remember that he will be OOO after 5/31.

**Comment by JakeBapple** [comment]
Making a note that this update happened after drupal core moved to 10.2.6, so the change was made to update both to that number instead of 10.2.5.

**Comment by JakeBapple** [comment]
This work also included a cypress test update to remove a fail-test when a user doesn't click the agreement statement found here: va.gov-cms/tests/cypress/integration/features/platform/content_release.feature
The update to core looks like it disabled that button if the box to agree wasn't checked, so this test became irrelevant and blocking.
