### ISSUE TITLE
Allow CMS to use different public file base URL on request

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#18070]
## Requirements

We want to allow Drupal to switch its public file base URL on request, so that we can request the appropriate base URL for internal use or for external use.

```[tasklist]
### Acceptance criteria
- [ ] If a request to the CMS contains a custom header with a known value (chosen by the developer), the CMS will use a public-facing file base URL (S3 bucket)
- [ ] In all other circumstances, the file base URL will be the current default
- [ ] If the request contains the custom header, an API response with file URLs will contain URLs that point to the public-facing location
```

## Background & implementation details

[The setting `file_public_base_url` is handled in settings.php](https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/docroot/sites/default/settings.php#L256). Under normal circumstances, this base url is `{$webhost}/sites/default/files`; for example, for Prod CMS this is https://prod.cms.va.gov/sites/default/files. This is the appropriate base URL to use for CMS-internal use. However, it is behind the firewall with the rest of the CMS, which means file URLs are not accessible to the public. 

We have public-facing S3 buckets that are synced with the CMS filesystem. The base URLs for these are:
- https://dsva-vagov-prod-cms-files.s3.us-gov-west-1.amazonaws.com (Prod; used for production builds)
- https://dsva-vagov-staging-cms-files.s3.us-gov-west-1.amazonaws.com (Staging; use for all other environments)

**Please note that these public-facing URLs do not contain `/sites/default/files`. This is correct; the public facing locations do not use the `sites/default/files` directory. All files start at the root.**

We want to use these base URLs for static files that are built for public use. A good way to do this is to look for a custom request header in requests to Drupal, and switch to the public-facing base URL only if that custom request header is present. 

So, the modification to settings.php (and its environment-specific versions) would be:
- If a custom request header is present with a specific value, use the appropriate public-facing base URL for that environment
- Otherwise, fall back to the default `{$webhost}/sites/default/files`

The system should *not* under any circumstances change the public file base URL to an arbitrary URL specified in the custom header. The header should only be used to indicate that we want to switch - i.e. a value of `S3` - and then the public file base URL switched to a value that we control. 

The desired result is, if a CMS request is made with the custom header set to the correct value, links to files will change to use the public-facing base URLs. This can be verified by looking at any API request that returns file URLs, for example: https://prod.cms.va.gov/jsonapi/media/image/9def6f1e-b943-4d61-97c1-09e6d6feecbd/image?resourceVersion=id%3A34510

**Comment by JakeBapple** [comment]
This work was merged in and is ready for the next-build counterpart for real testing.
