### ISSUE TITLE
Next Build should use a custom request header when requesting API data

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#18071]
## Requirements

Next Build should use the custom header implemented for the CMS in https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18070, so that data that it receives from the CMS contains file URLs that are rewritten to point to publicly accessible versions of those files.

```[tasklist]
### Acceptance criteria
- [ ] The API request client is modified to use the correct request header
- [ ] Links to files in the data returned by the API contain public-facing URLs rather than CMS-internal URLs
- [ ] When Next Build generates a page, any CMS files (images, etc) have URLs that point to the public-facing S3 buckets, and they load correctly without being on the proxy.
```

## Background & implementation details

In https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18070, we implemented a switch in the CMS which changes what public file base URL is used for CMS-managed files. This switch is based on the CMS receiving a specific custom request header and value, which tells it to use a different base URL.

We should modify the `drupalClient` utility to make use of this header when making requests to the CMS. This modification should be fairly simple. The implementation of `drupalClient` at time of writing is here: https://github.com/department-of-veterans-affairs/next-build/blob/main/src/lib/drupal/drupalClient.ts

Adding headers to the client request can be as simple as adding a `headers` property to the options:
```
export const drupalClient = new DrupalClient(baseUrl, {
  fetcher: getFetcher(baseUrl, debug),
  useDefaultResourceTypeEntry: true,
  throwJsonApiErrors: false,
  auth: {
    clientId: process.env.DRUPAL_CLIENT_ID,
    clientSecret: process.env.DRUPAL_CLIENT_SECRET,
  },
  // Generally use cache for `yarn export` as it generates all pages
  cache:
    process.env.USE_REDIS === 'true'
      ? redisCache(createRedisClient(process.env.REDIS_URL))
      : null,
  previewSecret: process.env.DRUPAL_PREVIEW_SECRET,
  // Add request header to tell the CMS to return public-facing URLs for files.
  headers: {
    "SOME-HEADER-NAME": "SOME-HEADER-VALUE",
  },
})
```

We may later make the addition of this header conditional - for example, we may not want to use this header in a CMS Preview context, so that CMS Preview always has access to the internal CMS images - but that can be handled later.

**Comment by JakeBapple** [comment]
I have made the changes in this PR: https://github.com/department-of-veterans-affairs/next-build/pull/560 

but I am having trouble seeing any headers updated in next-build.

**Comment by timcosgrove** [comment]
This is complete.
