### ISSUE TITLE
Typography Audit Issue: PACT Act

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#18083]
## Description
From Phase 1 of the Typography audit, one issue was found that should be investigated to confirm if any action needs to be taken:

1. The width on the page in the PR is just a bit smaller in the PR, you can tell because the headings are wrapping whereas in Prod they aren't. However, looking at the markup, it doesn't look like we are doing anything custom here, it just seems like maybe this is just a change that is because of the global changes and this will be the new display. Can we confirm is that is correct or is there something that we should be doing here?
![image (10)](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/106678594/1393afe8-9916-41bc-a6d2-714aa50acd89)

## Acceptance Criteria
- [ ] The form screens all use the correct width
- [ ] Requires design review

**Comment by FranECross** [comment]
This has been corrected (we think) by a PR the DST released. Note that if this crops up again, our UX has said it's okay like this and not an issue. Closing.
