### ISSUE TITLE
Typography Audit Issue: Income Limits

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#18086]
## Description
From Phase 1 of the Typography audit, one issue was found that should be investigated to confirm if any action needs to be taken:

1. The horizontal line and the feedback button is missing from the bottom of the results screen. The markup for this is actually not present on the page and I'm not sure why typography changes would have anything to do with this. 
![image (11)](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/106678594/19acff1a-ea64-41ba-a56e-72ce73c825e2)

## Acceptance Criteria
- [ ] Issue as been investigated to confirm if we need to make any updates or inform the DST about an issue
- [ ] Requires design review

**Comment by randimays** [comment]
I can see the Feedback button on the results page of Income Limits when running the typography branch locally. Maybe this is one of the somehow-magically-fixed items as well?

<img width="1065" alt="Screenshot 2024-05-09 at 1 36 19 PM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/19175324/166b3009-380d-4de8-9763-dd3bbe605344">

**Comment by laflannery** [comment]
I still don't so I'm going to go with - I'm just doing something wrong somehow. @FranECross based on this - should we close?

**Comment by randimays** [comment]
@laflannery You're doing nothing wrong; it occurred to me that running vets-website in isolation won't show the Feedback button.

Income Limits is a React app, but it is rendered in a content-build template. The Feedback button is part of that CB template. If you aren't running CB locally, you aren't seeing anything that CB constructs. VW is equipped to fake things (e.g. header/footer data) when CB isn't running (see https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/platform/landing-pages/dev-template.ejs). Most teams don't use CB at all, so having those dev template elements available for them is helpful to fill in the page. The dev template doesn't include a Feedback button, though.

All this to say, @laflannery did you notice this issue when running locally? Or was this a problem in the review instance? I tried checking the RI again but it is down right now / rebuilding.

**Comment by laflannery** [comment]
@randimays this was locally since you can’t get past zip code in a RI. I know there must have been something I was missing, thanks for explaining!

With all this and you seeing no issues - I would say we could close this? @FranECross

**Comment by FranECross** [comment]
Closing as a no op per the note from Randi in this Slack [thread](https://agilesix.slack.com/archives/C05Q7J61NR5/p1715632447144389?thread_ts=1715625917.823179&cid=C05Q7J61NR5)and Laura's comment above.
