### ISSUE TITLE
Typography Audit Issue: Hours on Facility Locator Detail pages

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#18084]
## Description
From Phase 1 of the Typography audit, one issue with the Hours display on the Facility Locator detail pages:

1. The padding on the standard `columns` class has increased. This means that the Hours display doesn't have as much space anymore and is wrapping:
![Screenshot 2024-05-08 at 4 23 20 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/106678594/6eabce93-4415-4b71-8bc2-03cd8ca9674a)
   - Even though this isn't necessarily using anything custom should we consider possible updates that make this look a bit nicer, the way it was previously?
     - Are there other classes that we could/should use that would have small padding?
     - We could also consider changing the 50/50 split of the columns to allow for more space in the second - since the first doesn't need as much

## Acceptance Criteria
- [ ] Hours display does not wrap
- [ ] Requires design review

**Comment by jilladams** [comment]
This feels very deeply not urgent to me, given everything we have that _is_ urgent, and that it's the FL detail page. I would like to vote this can hang in the icebox for a bit, but will let @Agile6MSkinner and @mmiddaugh confirm.

**Comment by jilladams** [comment]
For Michael's context: modernized facilities like VAMCs and Vet Centers do not use this template. Only non-modernized facilities do. That includes Regional Benefit offices, until we get our modernized VBA work shipped (SOON, we are hoping), and cemeteries.

**Comment by jilladams** [comment]
Laura also noted that this weird line breaking is already happening in prod at smaller breakpoints.

**Comment by laflannery** [comment]
@thejordanwood On the RI for Typography phase 2 this is back to the before view:
![Screenshot 2024-06-18 at 2 02 16 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/106678594/5090ea4f-3602-4d3f-8315-43f039d372b8)

Because of that, I think we should close this but I will let you make this call since you had originally found the issue

**Comment by thejordanwood** [comment]
@laflannery I agree!
