### ISSUE TITLE
[SPIKE] [Community Care] Community Care search results list differently when search for by city vs zip code

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-cms#18090]
## Status
[2024-08-014] [Fran] Turned this into a Spike and added AC. Note that the actual engineering changes that shake out from the tickets created off this one may actually fix the pagination issues. That ticket will be tested to see if that's the case and will be closed if so.
**[2024-08-06] [Fran]** Note that the case of this issue may be the absence of bounding box parameters in the query but may also be related to pagination issues documented in #17646  and #17649 

## Description

Concerns about the discoverability for an in-network urgent care provider (Alaska Urgent Care in Anchorage) was reported by a Triage Nurse at the VISN 20 Clinical Contact Center. 

The Facility Locator does not return the same list of providers if searched using zip code compared to city - and has only one provider in common. 

<details>
<summary> Performing the search using the zip code 99515 yields 3 results, including the expected provider</summary>

<img width="597" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK1hHQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--097bacb2f90a7b5565983001cdc2e5aba07b15ca/image.png" alt="image.png" />

Search results list includes 3 results: 
A) 
Alaska Urgent Care LLC
300 E Dimond Blvd Ste 12
Anchorage, AK 99515

B and C) 
Primary Care Associates
12350 Industry Way Ste 160
Anchorage, AK 99515

</details>

<details>
<summary> Performing the search using Anchorage yields 5 results, but does not include the expected provider</summary>

A) 
ACN AK MIDTOWN URGENT CARE
1200 W Northern Lights Blvd
Anchorage, AK 99503

B) 
Mountain View Urgent Care
3521 Mountain View Dr
Anchorage, AK 99508

C, D, and E) 
Primary Care Associates
4100 Lake Otis Pkwy Ste 100
Anchorage, AK 99508

<img width="595" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK2JHQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0515f256ab53d1e8ab0f91d4a867feecf55ee624/image.png" alt="image.png" />

</details>
 
## Related

The case of this issue may be the absence of bounding box parameters in the query but may also be related to pagination issues documented in #17646 and #17649

## Acceptance Criteria
- [x] explore the possibility of adding 'within a certain distance query' to PPMS to get things outside the visible border. 
- [x] explore a way to have MapBox not to zoom in so far with we pass a zip or city.
- [x] Discuss with PM/PO; they will work with engineer to create tickets after this is closed.

**Comment by mmiddaugh** [comment]
Scenario reported this week (https://va-gov.atlassian.net/browse/VAHELP-7793):

- A search for Facility type = Urgent care + Service type = All in-network urgent care using the parameters of “Keene, NH” returned 1 result: Edward P. Boland Department of Veterans Affairs Medical Center. 
- The same search for Facility type = Urgent care + Service type = All in-network urgent care using the Keene zip code (03431) as the search parameter returns two results, a community provider, Clear Choice, followed by the VA Medical Center.  

I am able to reproduce this observation. 

<details>
<summary> Screenshots </summary>

<img width="622" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd29aQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7e301f5a3db67dd7792357e7014f9b1d6bdfdb18/image.png" alt="image.png" />

<img width="622" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd3NaQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1af162179106db75607fe4aa4fbf389371374e54/image.png" alt="image.png" />


</details>

**Comment by FranECross** [comment]
Things are passed through by a center's coordinate, rather than an address or zip code. Maybe these two things are centering around different points.  The address isn't actually passed to PPMS.

**Comment by eselkin** [comment]
Findings:

entered: 20001
vets-api
```
Rails -- API PARAMS PROVIDER LOCATOR XXX -- { :PARAMS => { :address => "38.899818,-77.019911", :radius => 10, :maxResults => 11, :pageNumber => 1, :pageSize => 10, :telehealthSearch => 0, :homeHealthSearch => 0, :specialtycode1 => "122300000X" } }
```

entered: Washington, DC
vets-api
```
Rails -- API PARAMS PROVIDER LOCATOR XXX -- { :PARAMS => { :address => "38.903797,-77.04013", :radius => 18, :maxResults => 11, :pageNumber => 1, :pageSize => 10, :telehealthSearch => 0, :homeHealthSearch => 0, :specialtycode1 => "122300000X" } }
```

RADIUS is set in radiusFromBoundingBox in src/applications/facility-locator/actions/mapbox/genBBoxFromAddress.js
this is the radius generated by mapbox from the bounding box

The issue is that mapbox knows whether you entered a postalcode or something else (address or city) when it generates a boundingbox (when it’s a postal code the generation of the bounding box gets types: [‘postcode’] added so it must zoom in closer

There’s a step that says is the radius generated smaller than the minimum radius, and sets the value to that if it’s too small. We could probably increase that if we enter a zipcode and the type if CCP to be equal to the entered city radius

Radius generated when a zip code is entered: 2.851955974147978, which is smaller than 10 (minimum) so it is set to 10 (which is smaller than the 18 given when a City is entered)

**Comment by eselkin** [comment]
We cannot control how far mapbox zooms in, but we can set the radius minimum to 18 to make it equivalent to the default city value

**Comment by FranECross** [comment]
@eselkin Can we also expand the radius for the city value, so that providers outside of the current radius, but within the city, are returned? Thanks so much for this great investigation!

**Comment by eselkin** [comment]
We don't know what the radii of cities are (and have no way to get them). Nor do we know what the radii of zip codes are either. We could make both of them 20 which is larger than the current 18 and might help. But there's no way to guarantee that the entire city or zip code is contained in the radius given back by mapbox.

**Comment by eselkin** [comment]
The search is also different between when you use the search button and when you zoom in on the map and use the search within this map window button that appears in the map. This is probably expected by the user. The search in this window uses the radius of the map window and the center point of the map window, which makes sense.

**Comment by FranECross** [comment]
Thank you for all this info!

**Comment by FranECross** [comment]
@eselkin I'm going to create a ticket based on your research to have radius for both zip and city changed to 20, so if and/or how much that helps the existing issues, and then we can go from there to triage and possibly work on the other existing tickets. Thanks again for your extensive research. If you don't mind, I'll ask you to review the ticket for accuracy after I've created it; I always welcome suggestions and corrections. 😉
