### ISSUE TITLE
Typography Audit Issue: Feedback button padding (all products)

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#18091]
## Description
From Phase 1 of the Typography audit, an issues was found on the global search results that should be reviewed:

1. The padding around the Feedback button on the global Search results is larger on the PR 
![Screenshot 2024-05-09 at 9 18 02 AM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/106678594/ce1fef8d-5c83-4ac2-b38a-45e5a3d6d33c)

## Acceptance Criteria
- [ ] The Feedback button has the correct padding
- [ ] Requires design review

**Comment by FranECross** [comment]
This is global and not owned by the PW team. See Slack [thread](https://dsva.slack.com/archives/C06V7AAFVH7/p1715102477904739?thread_ts=1715101093.103219&cid=C06V7AAFVH7).
