### ISSUE TITLE
Vet Centers 2.0 final design artifact

### ISSUE THREAD

**Issue by davidmpickett** [department-of-veterans-affairs/va.gov-cms#18098]
## User Story or Problem Statement
Some of the changes are happening in their own tickets but let's also have this one to represent everything being done.

- #17891
- #18121
- #15349
- #17541 
- #18389
- New 640 Breakpoint 

## Design

[Vet Centers Figma file](https://www.figma.com/design/EVd3q06ukAbVS61Q8MwRAT/Vet-Centers?node-id=906-8577&t=FwtZx3lYgR7Q4lIL-1)

## Acceptance Criteria
- [x] Revisit Satellite Office pages
- [ ] Annotate Satellite Office locations
- [x] Add 640 breakpoint for SO locations
- [x] Address issues noted in [accessibility audit](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17371#issuecomment-2043127994)
- [x] Show design changes from this ticket in mockups #18268 
- [ ] UX review from Dave, Laura, Amanda

**Comment by jilladams** [comment]
@thejordanwood @Agile6MSkinner @davidmpickett to work a separate ticket for breaking Figma up into phased implementation for the FE.

**Comment by thejordanwood** [comment]
Adding latest stakeholder feedback here:

https://dsva.slack.com/archives/C06S9DADEUB/p1723050880800519
Vet Center 2.0 - stakeholder feedback

- `Top image` - moving forward with recommendation of one image used across all Vet Centers
- add a top optional `banner alert`, new to Vet Centers (like VBA)
- `Satellite/Outstations` will have the same look/template as main Vet Center
     - they have limited needs but same required services
     - may not use Events or Spotlights but Spotlight can use the one National if that is all that is available
- `Summary box` currently with CAIA for revisions, Amanda will follow up
- `Top task link` draft link text will need review once we have link, ETA mid Sept
     - Stakeholder suggested revising to "Connect with
     - once we see what this link/form is we could recommend different wording

**Comment by aklausmeier** [comment]
added design revision ticket to list w/in ticket for reference

**Comment by laflannery** [comment]
@thejordanwood I am done with annotations, I reviewed the notes in my audit ticket and all the related items on the main page are covered.

**Comment by jilladams** [comment]
Noting this is awaiting final signoff from Amanda, which sparked a conversation about tracking CAIA approval on FAQ copy.

**Comment by jilladams** [comment]
We need to send the FAQ copy to both RCS and CAIA for approvals. If they contradict each other, Michelle will call the shots.

**Comment by thejordanwood** [comment]
Relevant Slack thread where the conversation about tracking CAIA approval on FAQ copy took place.

https://dsva.slack.com/archives/C03LFSPGV16/p1724170165786589?thread_ts=1724166554.980479&cid=C03LFSPGV16

**Comment by aklausmeier** [comment]
Vet center satellite location designs look good other than getting review on the new FAQ content (Michelle/RCS/CAIA).

**Comment by thejordanwood** [comment]
A ticket has been stubbed to add updated content in Drupal once new copy has been approved. New ticket has been assigned to @Agile6MSkinner. 

https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19017
