### ISSUE TITLE
Typography Audit Issue: Global search results left/right padding

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#18099]
## Description
From Phase 1 of the Typography audit, an issue was found with the padding on the Global search results that should be reviewed:

1. The left/right padding has slightly increased on the global search results. While this is on all breakpoints, the concern is on the 320 breakpoint where the H1 now goes to 2 lines. The concern from UX is that because it dropd to 2 lines, it's just adding to the scroll length before users can see search results.
![Screenshot 2024-05-10 at 10 12 49 AM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/106678594/49a17f15-ce6f-42c9-a3eb-0a91fc060591)
![Screenshot 2024-05-10 at 10 13 52 AM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/106678594/c5a0751e-eaac-4a18-a8b6-23102e11a1ff)

## Acceptance Criteria
- [ ] Heading for Search results does not drop to 2 lines on any breakpoint
- [ ] Requires design review

**Comment by jilladams** [comment]
@FranECross I've tagged this into Sprint 4, but please feel free to override if this doesn't feel like a priority for next sprint. @thejordanwood also happy to hear your opinion on priority here.

**Comment by randimays** [comment]
I tested this locally. Dropping my findings here. It feels to me like the typography scaling issues are something in DST's court but I could be wrong there.

### Header line width issue
This seems either fixed or just not-reproducible on my end.

<img width="324" alt="Screenshot 2024-05-13 at 2 33 54 PM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/19175324/9f9ffc80-379b-4f28-aaeb-286d86284ac9">

### Typography scaling issues
It seems as though the default font size is 10px 🤔  Looking specifically at misalignment in the header and the tiny description text under each search result.

<img width="1619" alt="Screenshot 2024-05-13 at 2 33 05 PM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/19175324/87dd090c-c80b-4895-8d97-8fb5bb1cc01a">
<img width="766" alt="Screenshot 2024-05-13 at 2 34 29 PM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/19175324/c7df6d8e-72df-4d6b-9c0e-869ff205e0ad">

**Comment by laflannery** [comment]
I think this might be another instance of Local and RI showing different things - which again is slightly concerning because we were told either way of testing would be fine

**Comment by FranECross** [comment]
@jilladams @laflannery Circling back around on this one... I completely forgot @jilladams you'd tagged for Sprint 4, but to Randi's point, I think this might be a no op, or something the DST will fix/has a fix for? Should we wait and retest? cc @randimays

**Comment by FranECross** [comment]
DST has merged their fixes; need to validate on Prod @FranECross . If it's still an issue, then the PW team will need to take action.

**Comment by randimays** [comment]
@FranECross I validated in production; everything looks fine to me (padding, text size, etc.). I'll lean on @laflannery to confirm.

**Comment by laflannery** [comment]
I'm also not seeing the issues in prod that we reported in the previous screenshots, we should be good to close this!
