### ISSUE TITLE
Appointment Phone Number - Increase Cardinality from 5?

### ISSUE THREAD

**Issue by davidmpickett** [department-of-veterans-affairs/va.gov-cms#18112]
## User Story or Problem Statement

After running the [Service Location migration](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16825), @omahane discovered that there were 4 facility health services that had more appointment phone numbers than is allowed in the new content model. 

When we drafted the content spec, we limited the number of appointment phone numbers to 5. This was in line with the existing limit of 5 contact phone #s per Service Location. However, we discovered that there had never been a limit set on Appointment Phone numbers previously (likely due to historical concerns about data migration). Out of 15,000 published VAMC facility health services, only 4 of them use more than 5 appointment phone numbers.

A cursory review of these four services does not seem to indicate that they are misusing the appointment phone # field type. They are simply services with a lot of different phone numbers.

## Description or Additional Context 

Appt phone #s | FE link | Drupal link
-- | -- | --
6 | [Women centered care - Captain James A. Lovell Federal Health Care Center](https://www.va.gov/lovell-federal-health-care-tricare/locations/captain-james-a-lovell-federal-health-care-center/#women-centered-care) | [Drupal](https://prod.cms.va.gov/lovell-federal-health-care-tricare/locations/captain-james-a-lovell-federal-health-care-center/women-centered-care)
6 | [Primary care - Richmond VA Medical Center](https://www.va.gov/richmond-health-care/locations/richmond-va-medical-center/#primary-care) | [Drupal](https://prod.cms.va.gov/richmond-health-care/locations/richmond-va-medical-center/primary-care)
7 | [Radiology - Syracuse VA Medical Center](https://www.va.gov/syracuse-health-care/locations/syracuse-va-medical-center/#radiology) | [Drupal ](https://prod.cms.va.gov/syracuse-health-care/locations/syracuse-va-medical-center/radiology)
9 | [Primary care - Wilmington VA Medical Center](https://www.va.gov/wilmington-health-care/locations/wilmington-va-medical-center/#primary-care) | [Drupal](https://prod.cms.va.gov/wilmington-health-care/locations/wilmington-va-medical-center/primary-care)

## What will happen if we do nothing
- No data has been lost, it is merely hidden in Drupal
- Data will be deleted once we complete #17137
- After the FE changes merge on Tuesday May 14, these 4 services will only show 5 appointment phone numbers to Veterans

## Proposed short term path
- Increase the cardinality of this field from 5 to 9, this accounts for the current largest instance of appointment phone numbers while still preventing truly excessive phone number entry
- Manually add the 8 phone numbers that were not migrated to the new appointment phone number field on the corresponding services

## Another option that's probably not a good idea
- Create a second service location on these services and move some phone numbers to that based on our interpretation of the content

## Possible longer term follow up
- Work with the editors of these services to understand if this information could/should be split into multiple service locations under the Service, rather than all under one service
- Revisit the cardinality of this field 

## Acceptance Criteria
- [x] Number of Service Location appointment phone numbers possible is 9 rather than 5
- [ ] Data that was not migrated (originally) is migrated (manually or auto) to Drupal

**Comment by omahane** [comment]
@davidmpickett @mmiddaugh 
[service-location-additional-numbers-after-cardinatlity-change.xlsx](https://github.com/department-of-veterans-affairs/va.gov-cms/files/15322304/service-location-additional-numbers-after-cardinatlity-change.xlsx)
I have the additional numbers here. I would gladly change them but then I also have to set a lot of data I'm not sure about, including office visits, virtual support, and online scheduling. I could do that, but I'd need to have the editor go in and verify. 

How would you like to proceed?

**Comment by jilladams** [comment]
@mmiddaugh @omahane @davidmpickett to discuss and modify last AC as needed if we opt for editor reachout instead.

**Comment by jilladams** [comment]
Confirmed with VHA DM in sync today: 
We will coordinate with Helpdesk to reach out to the editors regarding populating the new required information.  If we have any trouble VHA can help contact them.

**Comment by davidmpickett** [comment]
Cardinality charge verified on prod
![Screenshot 2024-05-15 at 4 15 49 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/9ff4fc02-c772-497b-adc7-70dd4a9964a0)

**Comment by omahane** [comment]
@jilladams We can close, as we've confirmed on prod and have editors making additional necessary additions to phone numbers.

**Comment by davidmpickett** [comment]
Moved editor comms to separate ticket so this can close https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18145
