### ISSUE TITLE
[SPIKE] CMS Collab Cycle - Discovery for QA

### ISSUE THREAD

**Issue by gracekretschmer-metrostar** [department-of-veterans-affairs/va.gov-cms#18110]
## User Story or Problem Statement
Determine if/how CMS can leverage the existing collab cycle for QA standards and where the CMS team wants to add their own QA standards into the process.

## Steps for Implementation
- Review current Platform Collab Cycle
- Review the Collab Cycle that was being used in the CMS team
- Meet with Platform QA lead and Sitewide/Facilities Accessibility team
- Produce report detailing findings, next steps, and recommendations

## Acceptance Criteria
- [x] We have a direction to move forward with integrating into the Platform Collab Cycle from the QA standpoint.
- [x] We have communicate changes to impacted teams (facilities and PW).

**Comment by gracekretschmer-metrostar** [comment]
Note to self: get this ticket refined and have it mirroring the collab cycle accessibility review: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17442

**Comment by gracekretschmer-metrostar** [comment]
Due date: have completed by DC offsite trip in June

**Comment by keisterj-oddball** [comment]
@gracekretschmer-metrostar Can you give [this page](https://vfs.atlassian.net/wiki/spaces/~712020eee99537517b4d9594003707b252e24b/pages/3201499156/CMS+Collaboration+Cycle+Discovery) a read when you have time?  These are my findings and suggestions for a first pass with CMS QA in the collab cycle.

**Comment by gracekretschmer-metrostar** [comment]
Next steps:
1. Refining the confluence page, based upon feedback from Erika and Grace.
2. Getting review from Shira/Governance team. 
3. Move content into Github (need to determine where). 
4. Present to work to sitewide teams.

**Comment by keisterj-oddball** [comment]
Next steps:

1. Refining the confluence page, based upon feedback from Erika and Grace. - ✅ 
2. Getting review from Shira/Governance team. - **Pending**
3. Move content into Github (need to determine where). - ✅ 
4. Present to work to sitewide teams. - ✅

**Comment by gracekretschmer-metrostar** [comment]
Thanks, Jon! I am going to get the Governance Team's review represented in a new ticket and I consider this closed. Great work!
