### ISSUE TITLE
Analyze HelpDesk Tickets for 2024

### ISSUE THREAD

**Issue by MDomngz** [department-of-veterans-affairs/va.gov-cms#18113]
### Problem Statement

As a UX designer, it's important for me to identify where the editor is experiencing the greatest knowledge gaps. This understanding will enable me to develop a solution that addresses their pain points using the Knowledge Base resource center.

### Description

By using the data available in Jira, I will analyze and synthesize the information by date, focusing on the year 2024.

**Additional tasks include -** 
- Exporting all DONE tickets into a CSV
- Created a Pivot Table looking at labels and their respective counts to look for correlations
- Creation of Jira Dashboards, centered around time to complete and label applied to ticket

### Acceptance Criteria

- [x] Jira data is cleaned and analyzed
- [x] Data is synthesized by larger group categories
- [x] Data is combed for any correlations
- [x] Data is used for design work

**Comment by MDomngz** [comment]
Findings from Jira Dashboard - 

**Top 20 Labels Utilized:** 
Labels | COUNTA of Issue key
-- | --
access-request | 252
account-deactivation | 26
account-update | 15
banner-alerts | 24
broken-link | 51
detail-page | 20
duplicate | 28
events | 13
facility-addition | 34
facility-closure | 10
health-services | 15
login-trouble | 16
menu | 34
newCMSaccount | 31
other | 22
phone-numbers | 14
question | 24
ready-for-review | 15
spam | 12
training | 18

**Comment by EWashb** [comment]
@MDomngz @gracekretschmer-metrostar, do you have the pivot table you created to share? Your work could help inform some other initiatives we have in flight on the product teams. I'm interesting in seeing your findings and possibly adding that to our research repo

**Comment by MDomngz** [comment]
@EWashb Excel sheet with pivot tables. I'm still figuring out how to store this in a place that's shareable. Until then...

[CMS HelpDesk_Labels.xlsx](https://github.com/department-of-veterans-affairs/va.gov-cms/files/15338238/CMS.HelpDesk_Labels.xlsx)
