### ISSUE TITLE
[SPIKE] Research issue with Injected header that needs to appear on http://cem.va.gov

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#18120]
## Status
**[2024-05-22]** Hold going forward with this until some time after Memorial Day (Per Dave C)... see comment from Jill.

## Description or Additional Context 

https://www.cem.va.gov/ -- injected header appears
https://cem.va.gov/ -- injected headers don't

_Might need to work with server/security folks... CORs issue._

We need to fix the 2nd case 

I tried: https://github.com/department-of-veterans-affairs/vets-website/pull/29782/files -- that fix resulted in neither the TeamSite header nor the Injected Headers appearing, so we rolled it back in that PR. Apparently was a CORS error. We need to fix it better and resolve the CORS issue to roll forward.

## Acceptance Criteria
- [ ] Update injected header documentation re: whitelist and domains with current understanding
- [ ] Injected header appears on https://cem.va.gov/

**Comment by jilladams** [comment]
CORS is a server-level issue. Injected header is working on a TeamSite subdomain (benefits) both with and without www, so we know this is possible. We need help from the CEM teamsite admin to check their CORS header settings to see if they match the Benefits subdomain settings. 

TeamSite big picture owners can help us find the specific subdomain TeamSite admin for cem.va.gov: 

"Kotian, Sandeep (Veterans EZ Info, Inc.)" <Sandeep.Kumar@va.gov>,"Smelley, Bradley S." <Bradley.Smelley@va.gov>

**Comment by jilladams** [comment]
Emailed Brad & Sandeep, with Fran, Daniel, Randi, and Dave C in cc.

**Comment by jilladams** [comment]
Sandeep confirmed content owner in TeamSite, but feels we'll need to file a WebOps ticket for the network piece here: [KBX: Open a Ticket with Web Operations (va.gov)](https://vaww.webops.va.gov/apps/kbx/kbarticle.cfm?get=2018-CST-0416041924). Assigning to myself.

**Comment by randimays** [comment]
## Some initial research / findings
CC @dsasser @jtmst 

I looked around at the [proxy-rewrite-whitelist.json](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/proxy-rewrite/proxy-rewrite-whitelist.json). I am not sure, but it seems like we have this `www` or `not www` issue in multiple places.

For example: https://github.com/department-of-veterans-affairs/vets-website/blob/49cde5c221fc6364c4a030b642fa9e267864da2a/src/applications/proxy-rewrite/proxy-rewrite-whitelist.json#L95. The `www.move.va.gov` entry should show the injected header/footer at https://www.move.va.gov, right? But it doesn't.

<img width="1434" alt="Screenshot 2024-05-15 at 4 49 45 PM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/19175324/b6958ce6-eeb3-4188-b3f8-31fd8500862f">

### Injected footer?
I checked `https://cem.va.gov` vs `https://www.cem.va.gov` to see if the conditions were met for the injected footer to show up. See [Gotchas, number 2](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/proxy-rewrite/README.md#gotchas); the Teamsites footer has to have 2 `div`s (`sub-footer` and `small-print`) in order for injection to take place. 

On both `https://cem.va.gov` and `https://www.cem.va.gov`, these `div`s are present, but the behavior is different.

<img width="1450" alt="Screenshot 2024-05-15 at 4 54 05 PM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/19175324/88c14f27-bd29-442c-b8a9-004239b8eda8">

<img width="1450" alt="Screenshot 2024-05-15 at 4 54 23 PM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/19175324/4843dbf6-643f-4cac-bb11-638cc6e034ce">

### Consolidated style sheet
I also noticed that on both `https://cem.va.gov` and `https://www.cem.va.gov`, the `styleConsolidated.css` file is being imported into the page. This are the styles specific to injected header/footer.

<img width="1122" alt="Screenshot 2024-05-15 at 4 59 21 PM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/19175324/bf065c5d-e790-46fc-951a-4ed9538e765a">

<img width="1122" alt="Screenshot 2024-05-15 at 4 59 30 PM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/19175324/eab4ecb3-da45-4ef3-b8c0-c0f977256a78">

### Injected header/footer locally
I checked both `https://cem.va.gov` and `https://www.cem.va.gov` locally to see if the proxy rewrite application puts the header/footer on both. It does:

<img width="1435" alt="Screenshot 2024-05-15 at 4 43 55 PM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/19175324/b59c063d-ef5f-4d20-bbb8-06024111cb66">
<img width="1438" alt="Screenshot 2024-05-15 at 4 43 43 PM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/19175324/ca55a9a1-d050-4534-af1c-44617ee526fd">

**Comment by jilladams** [comment]
Filed a WebOps ticket; https://yourit.va.gov/va?id=ticket&is_new_order=true&table=incident&sys_id=2d7a5bb31b0a4e5034050f6fe54bcb84

**Comment by randimays** [comment]
From scrum today: I did not have a complete understanding of the proxy whitelist file (https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/proxy-rewrite/proxy-rewrite-whitelist.json). The entries with a `"cookieOnly": true` value are not expected to inject the header by default as they require a cookie. Things are working as expected according to that whitelist.

**Comment by jilladams** [comment]
Context:
* Lisa Hollenback = Content owner of the CEM teamsite
* Sandeep Kotian / Brad Smelley = OIT owners of the TeamSite product

So far: 
* Lisa asked Dave for help
* We took that request to Brad / Sandeep for direction on fixing the CORS problem
* Sandeep (OIT for TeamSite) noted we shoudl file a WebOps ticket
* WebOp reached out to Lisa for help.
* Lisa reached out to Brad (also OIT for TeamSite) for help. 
* I closed loop via email that we have already talked to Sandeep (equivalent to Brad) who sent us to WebOps.

So we now wait to see who can help us get out of the hoopsnake. :D

**Comment by jilladams** [comment]
Daniel determined that we might be able to get this fixed by asking Platform to modify the S3 bucket policy for the file hitting the CORS error, to allow the cem non-www domain to call it. 

Plat support ticket opened: https://dsva.slack.com/archives/CBU0KDSB1/p1716398255107869

**Comment by jilladams** [comment]
**TIMING:** If plat can help us, FYI @randimays @dsasser @FranECross that Dave wants us to hold on trying to roll forward the update for cem.va.gov til after Memorial Day. I went ahead and prepped a roll forward PR: https://github.com/department-of-veterans-affairs/vets-website/pull/29945

Also: Lisa Hollenbeck at NCA noted today in an email chain that she has opened a YourIT ticket to request server level redirect of cem.va.gov to www.cem.va.gov.  If that goes through, we will need to verify expectations here. Let's continue as though it won't, just in case.

**Comment by jilladams** [comment]
S3 bucket policy has been updated: https://dsva.slack.com/archives/CBU0KDSB1/p1716398255107869

I'm clarifying if we can roll forward the injection: https://dsva.slack.com/archives/C52CL1PKQ/p1716942064919329

cem.va.gov still resolves. Can't currently get on CAG (gotta restart) to check the webops ticket. Will do that tonight/early tomorrow.

**Comment by jilladams** [comment]
Fix deployed and verified in prod yesterday. Closing!
