### ISSUE TITLE
Adopt spotlight-card class on spotlight cards on Vet Centers and VBA

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#18126]
## Description
An editor add a naked link into one of their spotlights. Because these do not wrap natively, the spotlights did not keep their equal widths and instead one became much larger than the others to accommodate the nakedness. This happened on [Greensboro Vet Center](https://www.va.gov/greensboro-vet-center/) and looked like:

![Screenshot 2024-05-15 at 11 39 47 AM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/106678594/eac8020d-c107-4f12-827b-d52ecdb77783)

Both Eli and Josh reviewed. We originally thought that we would want to update these to use a grid layout. However, Josh added a new class to handled this - [see original comment](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18126#issuecomment-2120503009). This has already been done to VAMCs on prod and [can be seen here](https://www.va.gov/boston-health-care/health-services/).

We would like to add the `spotlight-card` class to the card components on both Vet centers and VBA spotlights.

## Acceptance Criteria
- [ ] `spotlight-card` class has been added to Vet Center spotlights so that now they always display properly and have equal widths when there are 2 or 3 added
- [ ] `spotlight-card` class has been added to VBA spotlights always so that now they display properly and have equal widths when there are 2 or 3 added (here or separate ticket)
- [ ] Requires design review

**Comment by aklausmeier** [comment]
I have also inquired about naked link error validation in Drupal in [Slack](https://dsva.slack.com/archives/C0FQSS30V/p1715790519605809?thread_ts=1715729058.731029&cid=C0FQSS30V).

**Comment by eselkin** [comment]
This happens on non-naked-links too [here](https://www.va.gov/brockton-vet-center/), like email addresses (separated not with spaces but `&nbsp;` with that (preferred) 

![Screenshot 2024-05-15 at 6 18 46 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5606931/01b74136-3b9d-419c-97be-2bcbe302768a)

**Comment by eselkin** [comment]
Actually found the `style="word-break: break-word;"` does wrap the naked links. So we don't need to switch to the grid. We can keep the flex.

**Comment by aklausmeier** [comment]
@eselkin Does the wrap solution keep the 3 columns to equal widths?

**Comment by jtmst** [comment]
by adding the following class we will be able to maintain equal width and appropriately wrap long links: 

`.spotlight-card {
  min-width: 30%;
  word-wrap: break-word;
}`

I'll be adding this as part of the health-services PR component migration PR, we will just need to add the class to other instances of the cards if @eselkin agrees that this works

**Comment by davidmpickett** [comment]
Verified on Prod for Vet Center
![Screenshot 2024-05-28 at 6 03 33 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/2b82c924-0139-48b2-80a2-75dc72c087d6)

Verified on Preview for VBA
![Screenshot 2024-05-28 at 6 05 41 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/2735e6fd-42ed-4973-bc91-b07070351abf)
