### ISSUE TITLE
URL Change for: Deer Park VA Clinic (Awaiting Redirect)

### ISSUE THREAD

**Issue by omahane** [department-of-veterans-affairs/va.gov-cms#18133]
### Implementation date
When does this request need to be live:
ASAP

Parent ticket: #18132 

### Instructions for URL redirect
(Note: This issue will be used from initial request through implementation to ensure all individuals working on this are notified of status updates.  Please do not create multiple issues to track different steps.)
- [x] Notify VA stakeholders as appropriate.
- [x] Link the related facility closure / rename issue.
- [x] Create a URL redirect in the [devops](https://github.com/department-of-veterans-affairs/devops) repo in `ansible/deployment/config/revproxy-vagov/vars/redirects.yml`
- [x] Add the "Awaiting redirect" flag to the facility node with a revision log message that includes a link to this ticket, preserving the node's current moderation state.
- [x] Redirects deploy daily except Friday at 10am ET, or by requesting OOB deploy (of the revproxy job to prod) in #vfs-platform-support. After deploy, validate that the URL redirect is deployed. (Note: In the event of a facility closure or a name change,  validate that this occurs before making the Lighthouse csv changes.)
- [x] Update this ticket with a comment that the redirect has been deployed.
- [x] Remove the "Awaiting redirect" flag on the facility node with a revision log message that includes a link to this ticket, preserving the node's current moderation state.
- [x]  Notify helpdesk via comment on ticket or Slack message in #cms-support that changes are ready for review.

#### URL Redirect
| Current URL  |  Redirect Destination or New URL |
| ---  |  --- |
| https://www.va.gov/tampa-health-care/locations/deer-park-va-clinic | https://www.va.gov/tampa-health-care/locations/ |

### Instructions for canonical URL removal
- [ ] Try to find the facility via the Facility Locator, using the Facility API ID (e.g. https://va.gov/find-locations/facility/"facility_api_id"). If it is not available, proceed.
- [ ] Update the [CSV in Lighthouse](https://github.com/department-of-veterans-affairs/lighthouse-facilities/blob/master/facilities/src/main/resources/websites.csv) removing the row with the Facility API ID.
- [ ] Create a PR in the [lighthouse-facilities repo](https://github.com/department-of-veterans-affairs/lighthouse-facilities), tagging the Lighthouse team.
- [ ] Post a message in the #cms-lighthouse channel in Slack, with an @mention to a Lighthouse team member.
**Note: there's no check to see if it's not returning anything, as it should already be not showing anything in the Facility Locator.**

#### URL removal example (update with actual ID and URL to remove)
| Facility API ID  |  Full VA.gov URL |
| ---  |  --- |
| vha_673QD | https://www.va.gov/tampa-health-care/locations/deer-park-va-clinic |

**Comment by ian-sears** [comment]
I've [reached out](https://va-gov.atlassian.net/browse/VAHELP-7486) to the Editor, Stephen.Westerfield@va.gov, inquiring about the status of this **Deer Park VA Clinic**, provided him the KB article for Facility Closure, and am **Awaiting Editor to confirm Closure**. If it IS Closed, I will check off the 1st box top of this ticket and reach out here.

**Comment by ian-sears** [comment]
UPDATE: THis Facility is CLOSED. Editor confirmed in VAHELP-7486.
All Health Services have been removed, the Operating Status has been set to CLOSED. Node is prepared and ready for Canonical URL removal and redirect to Tampa locations.

**Comment by omahane** [comment]
This redirect has been deployed.

**Comment by jilladams** [comment]
Redirect verified in prod. Can this be closed?

**Comment by ian-sears** [comment]
Closing. Tested this curl and it correctly resolves to their Locations page for this now-closed facility.
@TroyCMSSupport FYSA
