### ISSUE TITLE
VAMC Facility name change: Bellevue VA Clinic to Sarpy County VA Clinic (Awaiting Redirect)

### ISSUE THREAD

**Issue by omahane** [department-of-veterans-affairs/va.gov-cms#18137]
## Intake
- [x] What triggered this runbook? (Flag in CMS, Help desk ticket, Product team, VHA Digital Media)
Trigger: Flag in CMS

- [x] Link to associated help desk ticket (if applicable)
Help desk ticket: https://va-gov.atlassian.net/browse/VAHELP-7563

- [x] Name of submitter (if applicable)
Submitter: [Jeffrey.Gates@va.gov](https://prod.cms.va.gov/user/2745)

- [x] If the submitter is an editor, send them link to KB article: ["How Do I Update My VAMC Facility's Basic Location Data?"](https://prod.cms.va.gov/help/vamc/how-do-i-update-my-vamc-facilitys-basic-location-data). Let them know that once VAST/Lighthouse has been updated 1/ the Facility Name will be automatically updated and 2/ we will use a Facility name change flag to update the facility's URL. We can notify them once we have been notified that VAST/Lighthouse has been updated.

- [x] Link to facility in production:
Facility CMS link: https://prod.cms.va.gov/nebraska-western-iowa-health-care/locations/bellevue-va-clinic
Facility API ID: vha_636GL

#### CMS help desk steps
**Note: If the help desk is waiting on information from the facility staff or editor, add the "Awaiting editor" flag to the facility with a log message that includes a link to this ticket. Remove the flag when the ticket is ready to be worked by the Facilities team. Be sure to preserve the current moderation state of the node when adding or removing the flag.**
What happens: The name change is made in VAST, that syncs to Lighthouse which syncs to Drupal.
- [x] 1. Check that the title change in name field on the VAMC node has shown up in Drupal.
- [x] 2. Create a [URL change request](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/new?assignees=&template=runbook-facility-url-change.md&title=URL+Change+for%3A+%3Cinsert+facility+name%3E), changing the entry from the old facility URL to the new facility URL. (**Note: The URL change request ticket blocks the completion of this ticket.**)

#18138 

#### CMS Engineer steps
- [x] 3. Execute the steps of the URL change request ticket from step 2 above.

(Redirects deploy daily except Friday at 10am ET, or by requesting OOB deploy (of the revproxy job to prod) in #vfs-platform-support. Coordinate the following items below and canonical URL change after URL change ticket is merged, deployed, and verified in prod.)

#### Drupal Admin steps (CMS Engineer or Help desk)
_Help desk will complete these steps or escalate to request help from CMS engineering._
- [x] 4. Locate the newly renamed VAMC Facility (https://prod.cms.va.gov/admin/content/bulk) Search by new name
- [x] 5. Updates URL alias for this facility
- [x] 6. Resave this facility
- [x] 7. Make bulk alias changes to facility service nodes. (https://prod.cms.va.gov/admin/content/bulk?type=health_care_local_health_service)
- [x] 8. Bulk save fixed titles to facility service nodes. (https://prod.cms.va.gov/admin/content/bulk?type=health_care_local_health_service)
- [x] 9. Update menu title for facility
- [x] 10. May also need to directly edit the VAMC System menu to alpha sort the menu item after the title changes
- [x] 11. Update Alt text for facility image, if relevant
- [x] 12. Update Meta description (TBD: some backwards compatibility for SEM, by including something like ", formerly known as [previous name]".
- [x] 13. Edit facility node and remove flag `Changed name` then save node (with moderation state = published)

#### CMS Help desk (wrap up)
- [x] 14. Notify editor and any other stakeholders. Ask editor to validate that the photo of the facility does not contain the old name in any signage, etc. and to replace if necessary.

**Comment by TroyCMSSupport** [comment]
@omahane - May I assist with this?

**Comment by TroyCMSSupport** [comment]
@omahane @ian-sears  - This just became a bit more complicated -- This is not a name change; it is closing a facility and opening a new facility in a different location, serving the same population...

**Comment by TroyCMSSupport** [comment]
Update 6/17/24 - I have reached out to VHA Digital Media for clarification as to whether this is a facility rename OR a total facility closure and opening of a new facility.  Related JIRA ticket [VAHELP-7563](https://va-gov.atlassian.net/browse/VAHELP-7563)

**Comment by TroyCMSSupport** [comment]
@omahane @jilladams @ian-sears 

Update 6/17/24 - I have reached out to VHA Digital Media for clarification as to whether this is a facility rename OR a total facility closure and opening of a new facility.  Related JIRA ticket [VAHELP-7563](https://va-gov.atlassian.net/browse/VAHELP-7563)

[VAHELP-7563]: https://va-gov.atlassian.net/browse/VAHELP-7563?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by ian-sears** [comment]
Editor replied with clarity today in Jira ticket.
This is indeed to be Sarpy County VA Clinic.

**Comment by omahane** [comment]
@ian-sears @TroyCMSSupport Can you confirm that they are going to change the name upstream in VAST?

**Comment by ian-sears** [comment]
Awaiting VAST update (request was made to VAST, (see attched) on Feb 27th.
The node still shows the old address and we've not yet seen an update from VAST in the CMS.

[Sarpy_County_VA_Clinic.pdf](https://github.com/user-attachments/files/16513271/Sarpy_County_VA_Clinic.pdf)

**Comment by jilladams** [comment]
CSV update is complete, and URL change request is closed. I updated the checklist with things I know are complete, but I think the remaining items still need to be done.

**Comment by TroyCMSSupport** [comment]
@jilladams @omahane @ian-sears  - I am contacting the Editor to have them revise (change references from Bellevue to Sarpy County).

**Comment by TroyCMSSupport** [comment]
@omahane @jilladams @ian-sears  -- It looks like the URL change still needs to be processed as well in https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18138 

VA Locator does take the user to the correct page, but the URL appears to be redirected to the proper page.

**Comment by jilladams** [comment]
@TroyCMSSupport can you provide more detail on the URL piece? When I tested yesterday, Ithought everything was working as it should be so I'm not totally clear on what else may need to be fixed. Could you share your testing process with the URLs you got vs. what you expected to get?  My notes are here, for comparison: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18138#issuecomment-2357039318

**Comment by TroyCMSSupport** [comment]
Hi @jilladams  Yes, in VA Locator, I search and find Sarpy County VA Clinic in the list of facilities.
When my mouse hovers over the name of the clinic, I see in the lower left corner that the URL is still referring to Bellevue rather than Sarpy County -- If that is OK, I'm good with it, but I just want to confirm whether that is acceptable or not.

![image](https://github.com/user-attachments/assets/ffd8fc15-6ee2-4158-95fe-291a589363a9)

**Comment by jilladams** [comment]
Right you are! I reopened the URL change ticket with a comment to explain.

**Comment by TroyCMSSupport** [comment]
I have followed up with the remaining checkboxes (11-14). Marking this as closed - @ian-sears @omahane @jilladams
