### ISSUE TITLE
[Analytics] [Find a Form] Remove redundant GA event per the Analytics Team

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-cms#18148]
## Description

While reviewing our spreadsheet showing VFS Custom Events for Public Websites Products in this [ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/79590), Jamie Stutts found that on the Find Forms screen, there are two (2) dataLayer push events firing when the link "Change your direct deposit information" is clicked, and only one should be firing. 

Per her suggestion, we need to remove the GA Event nav-link-click.

### User story

**AS A** PO/PM for the Find a Form app
**I WANT** only one GA event to fire when a link is clicked
**SO THAT** data isn't confusing, and also so that we aren't paying for an even that isn't needed.

#### Steps to Reproduce
- Open developer tools in Chrome
- Go to https://www.va.gov/find-forms/
- Scroll down and click the link: Change your direct deposit information

## Acceptance criteria

- [ ] The Google Analytics dataLayer push event nav-link-click no longer fires
- [ ] The Google Analytics dataLayer push event nav-linkslist DOES still fire.

**Comment by FranECross** [comment]
@FranECross check to see if this is one of the custom events we're removing; and if so does va-link actually suffice; would we remove both.

**Comment by randimays** [comment]
We converted this link to a `va-link` and removed the custom event ([PR here](https://github.com/department-of-veterans-affairs/content-build/pull/2131)). It has a `nav-link-click` event with the current URL, destination URL, and the link text ("Change your direct deposit information"). Closing as a no-op as no additional action is needed here.
