### ISSUE TITLE
VAMC editor communication follow-up to Service Location launch

### ISSUE THREAD

**Issue by davidmpickett** [department-of-veterans-affairs/va.gov-cms#18145]
## Communications to draft
- [x] Direct comms to 4 editors impacted by the phone number migration as detailed in #18112
- ~~[ ] General comms to all VAMC editors about checking & updating their health services~~
  - ~~a summary of what fields we want editors to check~~
- ~~VHA DM will ask Editors to review their data / verify no issues, we get confirmation, then we remove old fields.~~
- ~~Figure out reasonable timeframes?~~

## Acceptance Criteria
- [x] Communications drafts shared with PO & VHA DM

**Comment by jilladams** [comment]
Per discussion to refine this ticket: 
* @omahane downloaded the CSV export of the Service Location audit, and compared it before and after migration. That's where he found 4 phone numbers that didn't line up, but otherwise: data is good. 
    * Those 4 editors do need comms, in order to fix the issue. That's captured in this ticket.
* We may not need Editors to do anything here if we are high confidence on that audit, in order to decide to remove the old fields.

**Comment by davidmpickett** [comment]
@Agile6MSkinner, I have drafted this on Sharepoint:
https://dvagov.sharepoint.com/:w:/s/SitewideFacilitiesTeam/EZbLS4Z0_uhLuxYJqVLGWKQBPrOngBW0rXLWIXKAQ5HsqQ?e=oi7Si2

Every email is same base message, but with a few specifics altered:
- I added the email addresses of currently active editors who have permission to edit the impacted service
- I update the count of phone numbers in paragraph 1
- Service, url, and phone number information details

Let me know if you have any questions

**Comment by Agile6MSkinner** [comment]
@davidmpickett These look great!

One suggestion: I don't think we need to apologize. If we want to soften the experience, I'd recommend thanking them for their patience instead. Or we can just leave that sentence off and only tell them they can reach out.

**Comment by davidmpickett** [comment]
Sounds good, feel free to make that edit and pass to VHA DM today. Once it's in their hands we can close this ticket and unblock the follow ups

**Comment by davidmpickett** [comment]
@laflannery I saw [on Slack](https://dsva.slack.com/archives/CDHBKAL9W/p1717594604030409) that you sent these comms via JIRA. Good to close?
