### ISSUE TITLE
[Discharge Upgrade Wizard] Change the acronym, review board name, address for the Air Force, and 'Get your military record...' URL

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-cms#18155]
## Status
**[2024-05-21]** Targeting Sprint 5 starting on 5/29

## Description

Our stakeholder has identified that the address for  which the Air Force Veterans send their discharge review paperwork is incomplete/incorrect, as well as the 'Get your military record...' link. See information below:

### Address & Acronym Correction
Any instance in the Discharge Upgrade Wizard where this information and address displays should be updated. An example screenshot is below and the areas to be corrected highlighted, as well as identified in the AC below.

<img width="783" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNEx4QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--588fa3261b7e0c9f6b41dd605156a48ca60a73ce/image.png" alt="image.png" />

#### Get your military record... link correction

Any instance in DUW of the link for Veterans to get their military records should utilize this URL: https://www.archives.gov/veterans/military-service-records.

### User story

**AS A** Veteran using the Discharge Upgrade Wizard VA.gov
**I WANT** information and websites to be correct so as to expedite by request for an upgrade
**SO THAT** my opinion of the Veteran's Administration, as well as VA.gov, are not eroded
**AND SO THAT** my discharge upgrade request can be processed expeditiously and routed to the correct departments/offices

### Steps to Reproduce
_The following steps to reproduce is just one of the paths to that will take you to the guidance page showing Air Force veterans where to send their discharge papers. Please code search to ensure all instances of this Air Force address are updated, as well as all instances of 'Get your military record... URL. Thanks!_

Steps to Reproduce getting to the Guidance screen:

- **Question**: In which branch of service did you serve? 
  - **Answer**: Air Force
- **Question**: What year were you discharged? 
  - **Answer**: (I don't think it matters, but I used 2012)
- **Question**: Which of the following best describes why you want to change your discharge paperwork? Choose the one that's closest to your situation. 
  - **Answer**: I suffered from an undiagnosed, misdiagnosed, or untreated mental health condition, including posttraumatic stress disorder (PTSD), while in the service. I was discharged for reasons related to this condition.
- **Question**: Do you want to change your name, discharge date, or anything written in the "other remarks" section of your DD214? 
  - **Answer**: No, I want to change only my characterization of discharge, re-enlistment code, separation code, and/or narrative reason for discharge.
- **Question**: Was your discharge the outcome of a general court-martial? 
  - **Answer**: I'm not sure.
- **Question**: Have you previously applied for and been denied a discharge upgrade for this period of service? 
  - **Answer**: No.
- **Question**: Did you complete a period of Service in which your character of service was Honorable or General Under Honorable Conditions? 
  - **Answer**: No, I did not complete an earlier prior of service.

#### AC for updating the acronym and mailing address

- [x] The paragraph (for when the guidance indicates they should send their information to the Air Force; no other branch) "Mail your completed form and all supporting materials" should read:

There are a number of different boards that handle discharge upgrades and corrections. Based on your answers on the previous page, you need to apply to the Air Force Review Boards Agency (AFDRB) for the Air Force. The AFDRB is a panel of commissioned officers, or a combination of senior non-commissioned officers (NCOs) and officers. The deadline to apply to the AFDRB is 15 years after your date of discharge; after this time period, you must apply to a different board.

- [x] The address should be:
Air Force Review Boards Agency
SAF/MRBP (AFDRB)
3351 Celmers Lane
Joint Base Andrews, MD 20762-6435

#### AC for updating the 'Get your military record..." link:
- [x] URL for Get your military record link for all branches of the military is now https://www.archives.gov/veterans/military-service-records.
- [x] Stakeholder review and sign-off by Joshua Gibbs
- [x] Alert PM Fran Cross before closing ticket.

This will be a separate ticket. ~- [ ] Add the agency's website as a link (may need Jordan Wood to provide link content/placement)~

**Comment by randimays** [comment]
Adding some screenshots for clarity.

This was on a guidance page for the Army.
<img width="767" alt="Screenshot 2024-05-29 at 11 25 35 AM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/19175324/d2e17e4f-b05f-40f9-b1f4-cc7c5e233115">

Only the third response on this question is dynamic based on branch. If we want to target Air Force only, we need to make the other two dynamic.
<img width="470" alt="Screenshot 2024-05-29 at 11 26 08 AM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/19175324/bcbb2dfc-3275-4ddc-8846-fb10a34caead">

This was on the Navy guidance screen.
<img width="679" alt="Screenshot 2024-05-29 at 11 28 07 AM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/19175324/f7db1c53-015f-4af2-aed7-0e706d47542c">

**Comment by FranECross** [comment]
@randimays Thanks for confirming! 

- The address change for the discharge review board is only for the Air Force. 
- The military records link is for requesting records from any military branch, so all instances.

**Comment by randimays** [comment]
@FranECross I have a PR up here: https://github.com/department-of-veterans-affairs/vets-website/pull/30079 In the description it has screenshots of the changes I made for the Air Force flow specifically and the global URL change for the military records. Could you please confirm I understood the task correctly? For posterity, we also discussed confirming with the stakeholder that we understood his requests correctly.

**Comment by FranECross** [comment]
@randimays Thanks for sharing the PR. Yes, it looks correct. I was unable to log into Citrix yesterday afternoon to send an email to the stakeholder, but will attempt again now and will cc you.

**Comment by randimays** [comment]
@FranECross I have an AC to alert you before closing this ticket. I have successfully validated the content changes in production 👍🏻

**Comment by FranECross** [comment]
Thanks, @randimays ! I've marked off that AC and this is good to close. I'll alert the stakeholder that this has deployed!
