### ISSUE TITLE
[Discharge Upgrade Wizard] [UX] Identify content and placement of text telling Veterans they may apply online or download a form

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-cms#18154]
## Description

Our stakeholder, Joshua Gibbs, has alerted us that Veterans may not only download the form (DoD) Form 293, but they may also fill it out online and submit it.

To that end, in addition to the current download form information, we need text alerting Veterans of they can also complete the form online https://afrba-portal.cce.af.mil/#application-submission-drb.

The text in the screenshot below is no longer valid.

![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/147188767/6c033458-6256-4b4f-b8c9-87908826ac2b)

### User story

**AS A** Veteran looking at the Form 293 information on the guidance page in the Discharge Upgrade Wizard
**I WANT** to know that I can not only mail a completed form, but also submit the form online
**SO THAT** if I'm able to do this online to expedite the request, I may proceed to submit it online

### Steps to Reproduce

Steps to Reproduce getting to the Guidance screen:

Go to the Discharge Upgrade Wizard here: https://www.va.gov/discharge-upgrade-instructions/
- Click the Get started link
- **Question**: In which branch of service did you serve? 
  - **Answer**: Air Force
- **Question**: What year were you discharged? 
  - **Answer**: (I don't think it matters, but I used 2012)
- **Question**: Which of the following best describes why you want to change your discharge paperwork? Choose the one that's closest to your situation. 
  - **Answer**: I suffered from an undiagnosed, misdiagnosed, or untreated mental health condition, including posttraumatic stress disorder (PTSD), while in the service. I was discharged for reasons related to this condition.
- **Question**: Do you want to change your name, discharge date, or anything written in the "other remarks" section of your DD214? 
  - **Answer**: No, I want to change only my characterization of discharge, re-enlistment code, separation code, and/or narrative reason for discharge.
- **Question**: Was your discharge the outcome of a general court-martial? 
  - **Answer**: I'm not sure.
- **Question**: Have you previously applied for and been denied a discharge upgrade for this period of service? 
  - **Answer**: No.
- **Question**: Did you complete a period of Service in which your character of service was Honorable or General Under Honorable Conditions? 
  - **Answer**: No, I did not complete an earlier prior of service.
- Click Get my result link

### notes / background
Currently: you have to download / complete and mail the form.
This text will clarify: also you can upload a completed PDF form to submit.

## Acceptance criteria

- [x] Content is alerting the Veteran they can also submit (DoD) Form 293 online, and the link to the online form is part of this content. 
- [x] @davidmpickett content review
- [x] @FranECross to facilitate Stakeholder review by Joshua Gibbs 
- [x] Inform Fran Cross so she can unblock the engineering story

**Comment by cmmerrill** [comment]
@FranECross can you re-share the image of existing? The link is broken here. Thanks!

**Comment by FranECross** [comment]
@cmmerrill I'm not sure why the image isn't displaying for you, so I created a quick Google slide deck to put misc [Discharge Upgrade Wizard screenshots](https://docs.google.com/presentation/d/1mrdM7ZQELOG7KTah9XgrJ_CoQ3Obowz9ctv03viKx1Q/edit#slide=id.g2e355af6d64_0_0) for anyone who isn't able to view them in tickets, and am sharing to anyone with the link. I'll also update the ticket with the actual url to the online form (the stakeholder provided it recently). TIA!

**Comment by davidmpickett** [comment]
I found this, which seems to allow Submitting Online (vs Submitting by Mail), but you still have to download the PDf
https://afrba-portal.cce.af.mil/#application-submission-drb

**Comment by FranECross** [comment]
Thanks, @davidmpickett ! That's the one! I found the email from the Stakeholder just to confirm. I've updated the description. cc @cmmerrill

**Comment by davidmpickett** [comment]
@FranECross to get an example of the full results page(s) so we can evaluate how to update the content.

**Comment by FranECross** [comment]
@cmmerrill @davidmpickett I've updated the screenshot and added Steps to Reproduce. Please let me know if you have any questions. Thanks!

**Comment by davidmpickett** [comment]
@cmmerrill Thoughts on points for this one? Looks like it's on deck for next sprint

**Comment by davidmpickett** [comment]
@cmmerrill FYI - I just found an example in Figma that is relevant. https://www.figma.com/design/XHQAQ8ZDKKsDcXfBn5ulhh?node-id=0-110#855727120

**Comment by gibbsjd** [comment]
@FranECross hey hope all is going well. I noticed that the Form number and download changed from DD293 which was correct to DD149 which is incorrect. 
[Discharge Memo Style.docx](https://github.com/user-attachments/files/16033003/Discharge.Memo.Style.docx)

Also, will the link that allows Submitting Online (vs Submitting by Mail) be added that @davidmpickett mentioned?

**Comment by FranECross** [comment]
Hey, @gibbsjd! I've actually been out for a while with COVID and am back this week catching up. I'll review this afternoon and see what I can do about getting the form correction and the link into our next sprint (starting next Wednesday). Thanks for letting us know and the reminder about the link! (and hope all is going well with you too. 😁)

**Comment by thejordanwood** [comment]
@FranECross I made some updates to [the Figma file](https://www.figma.com/design/XHQAQ8ZDKKsDcXfBn5ulhh/Discharge-Upgrade-Wizard?node-id=147-5583&t=ERHikjmxIDS8cKEt-1). Could you review some of the comments that I left in there?

**Comment by gibbsjd** [comment]
@thejordanwood ; @FranECross Hello, hope day going well the Option 1 in the Figma file would be a great setup. Thank you! 
<img width="370" alt="Option 1" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/167910779/af226e30-0083-4ef4-acab-e18e83e19ebd">

**Comment by gibbsjd** [comment]
@thejordanwood; @FranECross Also, is there any update on changing the form back to DD293 as it was before? The Steps described in step one are incorrect for DD293 form. Any questions or concerns please reachout 202-243-8437.
<img width="759" alt="15 or more Years" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/167910779/107335d8-cb39-469d-b048-b75798fd1124">
<img width="759" alt="PTSD" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/167910779/a832d3d2-76ec-44d0-adf7-bc95cfb24517">

**Comment by FranECross** [comment]
@gibbsjd Thanks so much for the feedback! I'll be sure to have the form change as part of the engineering ticket to implement the change you noted above, and then will reach out to have you confirm when the engineer has it implemented on a lower environment. Thanks so much for your patience while we work through this! The team was tasked with scads of design updates that had hard deadlines and have been diligently working through those (while acknowledging that this is also very important). We really appreciate your collaborate and guidance!

**Comment by gibbsjd** [comment]
@FranECross thank you I appreciate everyone's hard work and helping in the concern.
