### ISSUE TITLE
[Events] [Analytics] Analyze Medallia qualitative survey data

### ISSUE THREAD

**Issue by aklausmeier** [department-of-veterans-affairs/va.gov-cms#18152]
## Description
Pull current Medalia data and analyze in order to understand user feedback, which will be used to determine future changes or enhancements to Outreach and Events.

### User story
**AS A** PO/PM of the Public Websites team
**I WANT** to understand current user feedback on the VA.gov Outreach and Events in the Public Websites portfolio
**SO THAT** we can make HCD decisions in the upcoming Events work

### Notes / Background

Qualitative Medallia export was requested in [this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/83397) 5/17/24 and has been scrubbed of PII and added to Sharepoint:  [Events Medallia data](https://dvagov.sharepoint.com/:x:/s/SitewidePublicWebsites/EeBJE9h5ybhGuDdNVH6LbSsBTydQIMSK-kV5Eh2FHGyDGg?e=fylHA0).

## Acceptance criteria

- [x] Pull more current data for the analysis
- [x] PII removed
- [x] Data is synthesized and summarized as high level themes
- [x] Share findings with Fran, Dave, and Amanda [Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1719869297920/91249490453460d0c938e96804ab880c634cc7db?sender=u727a8f87b62662f75a603248)

**Comment by aklausmeier** [comment]
@FranECross FYA added new ticket for updated Events data. I put in request for Medallia and linked in ticket.

**Comment by aklausmeier** [comment]
Data pull request complete, PII removed and uploaded to PW Teams site. [Events Medallia data](https://dvagov.sharepoint.com/:x:/s/SitewidePublicWebsites/EeBJE9h5ybhGuDdNVH6LbSsBTydQIMSK-kV5Eh2FHGyDGg?e=fylHA0) ready to be synthesized. Early review shows **events near me** is still the largest Veteran request like last year's pull. 

> Looking at upcoming events. It would be nice if we could filter on location rather than have to search through 200+ events.

**Comment by davidmpickett** [comment]
@cmmerrill This is the root level website
https://www.va.gov/outreach-and-events/events/

**Comment by cmmerrill** [comment]
Mural with findings breakdown [https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1719869297920/91249490453460d0c938e96804ab880c634cc7db?sender=u3257ec2a20c7146a0cea2135](url)

**Comment by cmmerrill** [comment]
Updated based on @aklausmeier 's inquiries, and linked in the original data set. I also uploaded the coded data sheet to the same folder. @FranECross @davidmpickett @aklausmeier ready for review.

**Comment by aklausmeier** [comment]
Reviewed Carissa's synthesis in Mural, posted as a [summary](https://github.com/department-of-veterans-affairs/va.gov-team/edit/master/products/outreach-events/research/2024-Medallia-feedback/findings-summary.md) in GitHub with minor revisions. Closing ticket. cc @jilladams 

@mmiddaugh @FranECross recommendations for product to review

1. filtering/findability continues to be a significant issue
2. registration issues are a significant finding but mostly appears on the registration site like Eventbrite, review of editor help text and Drupal CMS flows could be an area of opportunity
