### ISSUE TITLE
[VA Benefit Taxonomy] [Drupal] Editors creating or editing benefit details can indicate exclusionary or simultaneous benefits

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-cms#18167]
## Description
When an editor is adding or editing a benefit that has exclusionary benefits, or simultaneous benefits, they will be able to choose/check/indicate exclusionary or simultaneous.

### Additional Information
* _Exclusionary Benefits Definition:_ Meaning > If you have _this_ benefit, you can’t have _that_ benefit.
  * Example: Question is asked of the Veteran: "Add Exclusionary benefits?" Example of options "Housebound **or** Aid & Attendance", etc. The note to the Veteran will be something like: "You can have one of these or the other, but not both (if you choose this benefit, you can’t select this linked benefit)."
* _Simultaneous Benefits Definition:_ Meaning > if you have this benefit, you MUST have this other benefit at the same time, _or_ you’re automatically enrolled in this other benefit at the same time.
  * Example language: Add Simultaneous benefit? Note to Veteran: What we’re talking about here is a benefit that you should or must consider applying for or obtaining at the same time as this benefit.

### Questions
* Can a benefit have both exclusionary and simultaneous linked benefits?
* Can a benefit have more than one exclusionary benefit, or more than one simultaneous benefit?

### User story

**AS AN** editor creating or editing a benefit with exclusionary or simultaneous benefits
**I WANT** to be able to indicate exclusionary or simultaneous, as well as add additional information specific to this benefit and the exclusion or simultaneous benefit
**SO THAT** Veterans, their family members and/or caregivers may easily navigate how to apply for the benefit with little to no confusion or frustration.

[UX ticket](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18166) created for designs, field names and help text.

## Acceptance criteria
Note that AC many be adjusted based on the answers to the questions above.

- [ ] Editors see a field they can choose to indicate the benefit they are creating/editing has an exclusionary benefit/benefits (design from the UX story)
  - [ ] Editors see a field name (from the UX story)
  - [ ] Editors see help text for this field (from the UX story)
- [ ]  Editors see a field they can choose to indicate the benefit they are creating/editing has a simultaneous benefit/benefits (design from the UX story)
  - [ ] Editors see a field name (from the UX story)
  - [ ] Editors see help text for this field (from the UX story)

**Comment by davidmpickett** [comment]
Closing as not planned due to stakeholder feedback on #18165 

> The taxonomy is not expected to determine eligibility at this stage. Because of edge cases and the complexity of the relationships between benefits, we determined that simultaneous and exclusionary benefit relationship categories are not necessary for MVP. These scenarios can be covered by the "co-considered benefits" category for now. The content will be responsible for providing the details, rather than the content model.
