### ISSUE TITLE
[VA Benefit Taxonomy] [UX] Provide editors the ability to indicate/add exclusionary or simultaneous benefits

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-cms#18166]
## Description
When an editor is adding or editing a benefit, they need a way to add/check exclusionary benefits, or simultaneous benefits.

This ticket is to provide designs around how the editor will indicate if there are exclusionary benefits or simultaneous benefits, help text, and Dave Conlon will need to collaborate with UX/Daniel for field names.

### Additional Information
* _Exclusionary Benefits Definition:_ Meaning > If you have _this_ benefit, you can’t have _that_ benefit.
  * Example: Question is asked of the Veteran: "Add Exclusionary benefits?" Example of options "Housebound **or** Aid & Attendance", etc. The note to the Veteran will be something like: "You can have one of these or the other, but not both (if you choose this benefit, you can’t select this linked benefit)."
* _Simultaneous Benefits Definition:_ Meaning > if you have this benefit, you MUST have this other benefit at the same time, _or_ you’re automatically enrolled in this other benefit at the same time.
  * Example language: Add Simultaneous benefit? Note to Veteran: What we’re talking about here is a benefit that you should or must consider applying for or obtaining at the same time as this benefit.

### Questions
* Can a benefit have both exclusionary and simultaneous linked benefits?
* Can a benefit have more than one exclusionary benefit, or more than one simultaneous benefit?

### User story

**AS AN** editor creating or editing a benefit with exclusionary or simultaneous benefits
**I WANT** to be able to indicate exclusionary or simultaneous, as well as add additional information specific to this benefit and the exclusion or simultaneous benefit
**SO THAT** Veterans, their family members and/or caregivers may easily navigate how to apply for the benefit with little to no confusion or frustration.

## Acceptance criteria

- [ ] Editors are able to indicate if the benefit they are creating or editing has an exclusionary benefit
  - [ ] Field name is provided and easily understood
  - [ ] Help text is provided and easily understood
- [ ] Editors are able to indicate if the benefit they are creating or editing has a simultaneous benefit
  - [ ] Field name is provided and easily understood
  - [ ] Help text is provided and easily understood

**Comment by davidmpickett** [comment]
@FranECross FYI - I chatted with @mmiddaugh about this briefly in a 1on1 today. I called out that there is likely not going to be much discrete UX work here. I don't think will require it's own ticket.

I will be proposing field names and help text as part of #18165 and will make sure the relevant details are added to #18167. I will make sure Laura and Jordan review them before implementation. I'd say close this as duplicate
