### ISSUE TITLE
Understand LH push / receipt for Mental health care and Dental/oral surgery

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#18178]
## Description
We need to confirm some "source of truth" data questions with Lighthouse. 

### Mental health
We send Mental Health phone numbers to Lighthouse. 
We do _not_ send Mental Health facility service information to Lighthouse. 
We would like to. This applies to VAMCs and Vet Centers facility services. 
We have 1 known line of code stopping this push. We can change that, push, and verify with them if they can receive.
We need to check with LH: 
* Can they receive, if we send? 

VA Service taxon: 
* Mental health care
* https://prod.cms.va.gov/health-care/mental-health-care
* Drupal API ID = `mentalHealth`
* LH API ID = `MentalHealthCare`

### Dental
Dental health service has a name discrepancy between our API taxon ID, and LH's API taxon ID.

The only existing VA Service that references dentistry is: 
* Dental/oral surgery
* https://prod.cms.va.gov/health-care/dentaloral-surgery
* Drupal API ID = `dental`
* LH API ID = `DentalServices`

It's possibile that LH is receiving `dental` from us, and somehow converting that to `DentalServices`, or that their data is referencing some other source of truth.  When we move the Facility Locator onto V1 and start pulling service data, this will have a material difference in what information Veterans can access in the FL. Also: other LH Facilities API consumers will have that data disconnect.
We need to verify what Lighthouse is receiving / why the IDs are different.

## Acceptance criteria
- [x] Understand and document in ticket comments the state of truth for LH push / receipt of these 2 services
- [x] Understand what, if anything, blocks us from pushing both of these services
- [x] Update https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/READMES/migrations-facility.md accordingly 
- [x] Cut a ticket for that follow up work, if any

**Comment by davidmpickett** [comment]
We should also update this diagram that shows data sources for vets-API Facilities API v1 vs v2 https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/facilities-api/README.md

**Comment by omahane** [comment]
Dental services have been syncing to v1. The v0 compatibility required that Lighthouse check and convert the `MentalHealthCare` and `MentalHealthCare` ids to their v1 ids, which are the same as the services taxonomy. 

Adam and I tested sending Dental and Mental Health. There was no code work required for sending Dental. For mental, it was just the one line change, removing the mental health line from the following in `va_gov_post_api/src/Service/PostFacilityServiceBase.php`
```
/**
   * The services that should be withheld from Lighthouse.
   *
   * The key is for making sense of code, the TID is used for comparison.
   *
   * @var array
   */
  protected $servicesToWithhold = [
      // Key: service name (not used) => Value: TID.
    'Caregiver support' => 48,
    'Mental health care' => 43,
  ];
```

There appears to be no more change than this one line, per [my conversation with Adam](https://dsva.slack.com/archives/C02BTJTDFTN/p1718369366085299).

**Comment by jilladams** [comment]
@omahane is this now pending prod deploy?

**Comment by omahane** [comment]
@jilladams Yes, this can be closed after prod verification.

**Comment by jilladams** [comment]
I think this is different than @eselkin 's ticket for the Facility Locator erroring on MH / Dental, so I'm not sure how we know this is working other than verifying with lighthouse.  @omahane is that the best way?

**Comment by omahane** [comment]
Adam has confirmed via [Slack](https://dsva.slack.com/archives/C02BTJTDFTN/p1719581415813369) that they are receiving mental health services on production. This can be closed.
