### ISSUE TITLE
Tugboat failing to build due to EMFILE error too many open files

### ISSUE THREAD

**Issue by eselkin** [department-of-veterans-affairs/va.gov-cms#18173]
## User Story or Problem Statement

CMS web-build cannot build any content-build now. It fails with the EMFILE too many open files issue. This is an additional level of failure than the one that I caught in the garbage collection process of content-build/metalsmith.

```
Error getting memBefore memory usage: Error: EMFILE: too many open files, uv_resident_set_memory
    at process.memoryUsage (internal/process/per_thread.js:153:5)
    at Timeout._onTimeout (/var/lib/tugboat/docroot/vendor/va-gov/content-build/src/site/stages/build/silversmith.js:184:31)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7) {
  errno: -24,
  code: 'EMFILE',
  syscall: 'uv_resident_set_memory'
}
Error getting memAfter memory usage: Error: EMFILE: too many open files, uv_resident_set_memory
    at process.memoryUsage (internal/process/per_thread.js:153:5)
    at Timeout._onTimeout (/var/lib/tugboat/docroot/vendor/va-gov/content-build/src/site/stages/build/silversmith.js:191:30)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7) {
  errno: -24,
  code: 'EMFILE',
  syscall: 'uv_resident_set_memory'
}
/var/lib/tugboat/docroot/vendor/va-gov/content-build/src/site/stages/build/plugins/download-assets.js:11
  throw up;
  ^

[Error: EMFILE: too many open files, open '/var/lib/tugboat/docroot/vendor/va-gov/content-build/src/site/layouts/news_story.drupal.liquid'] {
  errno: -24,
  code: 'EMFILE',
  syscall: 'open',
  path: '/var/lib/tugboat/docroot/vendor/va-gov/content-build/src/site/layouts/news_story.drupal.liquid'
}
```

I think we need to try to increase the limit of open files on the tugboat server/system.

## Description or Additional Context 

Release content on any tugboat instance. When it gets to the 45/54th step, it fails with the above message. It appears on any tugboat instance building off main content-build main vets-website.

## Steps for Implementation

Uncertain, possibly editing `/etc/security/limits.conf` if there is a set limit. Remove calls or increase limits to `ulimit` if they are in a startup script.

## Acceptance Criteria
- [ ] content-build builds using web-build.sh

**Comment by edmund-dunn** [comment]
We need to increase the `ulimit` without the docker containers. See https://dsva.slack.com/archives/C01A35JDH88/p1716309740593269

**Comment by edmund-dunn** [comment]
We had to increase the `ulimit` in `/etc/sysconfig/docker` on the tugboat instance. We change the line too `OPTIONS=" — default-ulimit nofile=32768:32768"`.

We had to shut down tugboat using `tbctl stop`, then stop all of the docker containers, then restart docker using `service docker restart` then stat tugboat using `tbctl start`. Once this was down we had to rebuild all of the base previews and previews.

**Comment by edmund-dunn** [comment]
Change took effect.
![Screenshot 2024-05-21 at 14 23 58](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/109987005/0ea2f924-6b1b-4f02-b8d2-7eae2fe66406)

**Comment by edmund-dunn** [comment]
@eselkin was able to run a successful build!

**Comment by edmund-dunn** [comment]
@gracekretschmer-metrostar closing this as complete.
