### ISSUE TITLE
[VA Benefit Taxonomy] Add logic to determine if Benefit Description fields are required based on character count of previous field

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-cms#18172]
## Description

There are three (existing) fields for providing Benefit Descriptions to Veterans, their family members, and/or caregivers:

* Longer summary (500 characters)
* Brief summary (300 characters)
* Teaser summary (200 characters)

The Longer summary field is always required, however both fields will be optional UNLESS the following occurs:
*  the Longer summary exceeds the 300 character count of the Brief summary; in that case, the Brief summary becomes required.
*  the Brief summary exceeds the 200 character count of the Teaser summary; in that case, the Teaser summary becomes required.

Details outlines below.

Use the required character counts on the fields to drive logic to determine if the Brief summary and Teaser summary fields are required or optional. 
 * **Longer summary:**
   * Character count limit = 500
   * Always required.
 * **Brief summary:**
    * Character count limit = 300
    * Optional, UNLESS the Longer summary description character count is more than 300 characters. If so, then the Brief summary changes from optional to required.
* **Teaser summary:**
    * Character count limit = 200
    * Optional, UNLESS the Brief summary is greater than 200, then the teaser summary is required.
  
In the editorial interface, we want to include error message/warning feedback to the editors regarding the character counts, to include in the description what the character counts are, and to dynamically indicate if the Brief summary and/or Teaser summary become required based on the character count of the field just prior.

Fran to work with CAIA to provide content for the editorial interface for best practices:
  * Note that CAIA will provide editorial context e.g. word counts for the Longer, Brief, and Teaser summary descriptions and helper text.
  * Note from CAIA: We need to think about how much depth we want to go into for the “Longer summary.” For example, for health care benefit programs, would we include what’s covered and what’s not in the full (Longer summary) description? This is something for us (CAIA) to do. We’ll think through this more and document it, but we want to capture it here as part of our overall findings as we began to use this taxonomy.

### User story

**AS AN ** editor creating a benefit's description
**I WANT** 
**SO THAT**

## Acceptance criteria

>Consider
> - Design / Accessibility reviews
> - Collab cycle requirements
> - Device sizes (mobile first)
> - Documentation updates / Change management
< - [Content model documentation](https://prod.cms.va.gov/admin/structure/cm_document)
> - Testing notes

- [ ]

**Comment by davidmpickett** [comment]
Closing as not planned due to [change in direction](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18170#issuecomment-2248329497)
