### ISSUE TITLE
URL Change for: Sabal Park VA Clinic - waiting on CSV update

### ISSUE THREAD

**Issue by ian-sears** [department-of-veterans-affairs/va.gov-cms#18177]
⚠️  NO URL RE-DIRECT NEEDED ⚠️ 

Simply needs to be updated within Lighthouse CSV / canonical URL change

-----

### Implementation date
When does this request need to be live:
ASAP

Parent GH ticket: #18175 

### Instructions for canonical URL change
- [x] Verify that the new URL for the facility is published and accessible on VA.gov.
- [x] Update the [CSV in Lighthouse](https://github.com/department-of-veterans-affairs/lighthouse-facilities/blob/master/facilities/src/main/resources/websites.csv) with the changed URL, maintaining the sorted order of the Facility API IDs.
- [x] Create a PR in the [lighthouse-facilities repo](https://github.com/department-of-veterans-affairs/lighthouse-facilities), tagging the Lighthouse team.
- [x] Post a message in the #cms-lighthouse channel in Slack, with an @mention to a Lighthouse team member.
- [x] Add the "Awaiting CSV" flag to the facility node with a revision log message that includes a link to this ticket.
- [x] Validate that the change has deployed by checking that the Facility Locator has been updated with the new url.
- [x] Update this ticket with a comment that the CSV change has been deployed.
- [x] Remove the "Awaiting CSV" flag to the facility node with a revision log message that includes a link to this ticket.

#### URL change example (update with actual ID and URL)
| Facility API ID  |  Full VA.gov URL |
| --- | --- |
| vha_673QN  |  [https://www.va.gov/tampa-health-care/locations/sabal-park-va-clinic](https://www.va.gov/tampa-health-care/locations/sabal-park-va-clinic) |

**Comment by ian-sears** [comment]
NOTE: Editor (Stephen Westerfield) Published this node May 20, 2024 at 8:02 AM with a reply to the CMS Help Desk
"Yes, we just did the ribbon cutting last week. It is an official CBOK and it is up and running."

https://www.va.gov/tampa-health-care/locations/sabal-park-va-clinic/ resolves
but the link from the Facility Locator still goes to
https://www.va.gov/find-locations/facility/vha_673QN

Need the Canonical URL implemented in the CSV.

**Comment by ian-sears** [comment]
This Canonical seems to be resolving now from this page here: 
https://www.va.gov/tampa-health-care/locations/
Correctly linking to the Sabal Park Facility page now.

**Comment by omahane** [comment]
@ian-sears We really want to check that the correct link is coming from the results on the Facility Locator page. Given that the CSV update has been deployed, I have confirmed that the page is being linked from the facility locator search results for [Tampa, FL VA Clinics](https://www.va.gov/find-locations/?address=Tampa%2C%20FL&bounds%5B%5D%5B%5D=-83.20877&bounds%5B%5D%5B%5D=27.197401&bounds%5B%5D%5B%5D=-81.70877&bounds%5B%5D%5B%5D=28.697401&context=Tampa%2C%20Florida%2C%20United%20States&facilityType=health&latitude=27.947401&longitude=-82.45877&page=1&radius=34&serviceType&bounds%5B%5D=-83.20877&bounds%5B%5D=27.197401&bounds%5B%5D=-81.70877&bounds%5B%5D=28.697401).
