### ISSUE TITLE
[Analytics] [Campaign Landing Pages] Custom GA events removal & va-link component w/analytics adoption

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-cms#18186]
## Description

The va-link component has been enhanced to provide destination and can be used now for applicable Campaign Landing Page features, along with removal of the GA custom events.

Details are in the AC.

### User story

**AS A PO/PM** managing Campaign Landing Pages
**I WANT** to (where appropriate) adopt the va-link component, its baked-in analytics, and remove the custom GA events
**SO THAT** extraneous code is removed and only the events needed will be triggered.

## Acceptance criteria

- [ ] **Element with custom events:** (What you can do) "Learn how to get your flu shot" link
  - [ ] Example page: https://www.va.gov/initiatives/covid-flu
  - [ ] Event name: clp-link-click
    - [ ] convert to va-link? Yes
    - [ ] enable DST analytics? Yes
    - [ ] remove custom code? Yes
- [ ] **Element with custom events:** (Spotlight) "Why is VA helping Veterans to vote?" link
  - [ ] Example page: https://www.va.gov/initiatives/vote/
  - [ ] Event name: clp-link-click
    - [ ] convert to va-link? Yes
    - [ ] enable DST analytics? Yes
    - [ ] remove custom code? Yes
- [ ] **Element with custom events:** (Stories) "Staying safe when considering employment with a foreign organization" link
  - [ ] Example page: https://www.va.gov/initiatives/protecting-veterans-from-fraud/
  - [ ] Event name: clp-link-click
    - [ ] convert to va-link? Yes
    - [ ] enable DST analytics? Yes
    - [ ] remove custom code? Yes
- [ ] **Element with custom events:** (Events) Event title, facility link, online event link, event link
  - [ ] Example page: No examples in prod
  - [ ] Event name: clp-link-click
    - [ ] convert to va-link? Yes
    - [ ] enable DST analytics? Yes
    - [ ] remove custom code? Yes
- [ ] **Element with custom events:** (Connect with us) "Veterans benefits email updates" link
  - [ ] Example page: https://www.va.gov/initiatives/protecting-veterans-from-fraud/ (Someone removed this link by the time I finished this spreadsheet)
  - [ ] Event name: clp-link-click
    - [ ] convert to va-link? Yes
    - [ ] enable DST analytics? Yes
    - [ ] remove custom code? Yes
- [ ] **Element with custom events:** (Connect with us) Social media links (Twitter, Facebook, YouTube, LinkedIn, Instagram)
  - [ ] Example page: https://www.va.gov/initiatives/protecting-veterans-from-fraud/
  - [ ] Event name: clp-link-click
    - [ ] convert to va-link? Yes
    - [ ] enable DST analytics? Yes
    - [ ] remove custom code? Yes
- [ ] **Element with custom events:** (VA Benefits) "VA housing assistance" link
  - [ ] Example page: https://www.va.gov/initiatives/protecting-veterans-from-fraud/
  - [ ] Event name: clp-link-click
    - [ ] convert to va-link? Yes
    - [ ] enable DST analytics? Yes
    - [ ] remove custom code? Yes
- [ ] a11y Review

**Comment by chriskim2311** [comment]
@FranECross A few of these are not ready for migration yet as they are open in new tab links and not converted to va-link's. I saw the spreadsheet that Randi posted. I don't have permissions but can you update that so we keep track of these since they have not been converted yet. 

Element with custom events: (Connect with us) "Veterans benefits email updates" link
Element with custom events: (Connect with us) Social media links (Twitter, Facebook, YouTube, LinkedIn, Instagram)

**Comment by FranECross** [comment]
@chriskim2311 I've been working off a [copy of Randi's ticket](https://docs.google.com/spreadsheets/d/1iDtKAagOxMlkqoYHGWvrNsG9MtDZZxl39i_5BkP0hik/edit#gid=999920757), so as not to inadvertently make changes to her original. Here you go! I still have some tickets to create, which I'll be doing today (since I'm OOO the rest of the week).

**Comment by chriskim2311** [comment]
Verified links in prod are va-links with proper analytics, closing!
