### ISSUE TITLE
[CONSIDER] Navigation flow between FLocator and facility

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-cms#18189]
## Description
As a Veteran searching for a particular service on the Facility Locator, I would like to be connected to the information about that service when I click on a facility in the search results.

## Current experience
When someone searches on the Facility Locator and clicks the name of the search result, the link connects the user to the main page for the facility.

A Veteran searching on the Facility Locator can choose to search for all VA health services or specify a particular health service. 

85% of VA health searches use the default "All VA health services". This may change when the UX is updated to allow searching for all services in Drupal.

**Comment by Agile6MSkinner** [comment]
User experience most likely not worth the benefit. Potential cognitive load to clicking on a facility name and being sent to an accordion. Potential complex logic.
