### ISSUE TITLE
Feasibility prototype: USWDS admin theme based on Claro

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#1818]
##  AC

- [ ] define an MVP
- [ ] define theme architecture
   - [ ] use composer library for both?
   - [ ] etc

**Comment by jefflbrauer** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VAgov-CMS-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/1818?planning-poker) with ZenHub @cweagans
