### ISSUE TITLE
Gap analysis of USWDS/VADS and Drupal Design Systems

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#1819]
## Owner

Daniel Miller

## Description

- USWDS https://designsystem.digital.gov/
- VADS https://design.va.gov/
- Claro/Drupal Design system https://www.figma.com/file/OqWgzAluHtsOd5uwm1lubFeH/Drupal-Design-system

**Proposed guidelines for gap analysis:**
- core principles
- features of visual style: color; typography; spacing & rhythm; icons
- UI patterns and components: core set of common components
- 508 compliance
- outputs: code frameworks; templates; design software, etc
- features: what exists; how they are disseminated as code and design assets
- depth of documentation
- system practices: people dedicated to maintaining; community contribution process; regularity and proficiency of system maintenance; communication channels and barrier to entry

## Related 
- VA.gov CMS UX writing principles  https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/ux-writing/CMS-back-end-style-guide/principles.md

## Acceptance Criteria
- [x] The team has a shared understanding of how these design systems could align, with an artifact that captures this understanding.

**Comment by cmaeng** [comment]
Working through hand off of information and synthesizing for presentation.

**Comment by kevwalsh** [comment]
@oksana-c @cmaeng I've moved this back to "new issues"

**Comment by oksana-c** [comment]
Gap Analysis Documents - https://drive.google.com/drive/folders/1n6Ro-1a7E-AfvMPJSZ5fGfAAgy_V1Ekt?usp=sharing
