### ISSUE TITLE
[Analytics] [Find a Form] Custom GA events removal & va-link component w/analytics adoption

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-cms#18202]
## Description

The va-link component has been enhanced to provide destination and can be used now for applicable Find a Form features, along with removal of the GA custom events.

Details are in the AC, and the The [spreadsheet](https://docs.google.com/spreadsheets/d/1iDtKAagOxMlkqoYHGWvrNsG9MtDZZxl39i_5BkP0hik/edit#gid=999920757) used for this endeavor is a copy of the original that Randi Mays created, with the products on individual tabs.

### User story

**AS A PO/PM** managing Public Websites products & features
**I WANT** to (where appropriate) adopt the va-link component, its baked-in analytics, and remove the custom GA events
**SO THAT** extraneous code is removed and only the events needed will be triggered.

## Acceptance criteria

- [x] **Element with custom events:** (Manage your VA benefits and other information online) "Change your direct deposit information" link
  - [ ] Example page: https://www.va.gov/find-forms/?q=526ez
  - [ ] Event name: nav-linkslist
    - [ ] convert to va-link? Already converted
    - [ ] enable DST analytics? Yes
    - [ ] remove custom code? Yes

- [x] **Element with custom events:** (Manage your VA benefits and other information online) "Change your address in your VA.gov profile" link
  - [ ] Example page: https://www.va.gov/find-forms/?q=526ez
  - [ ] Event name: nav-linkslist
    - [ ] convert to va-link? Already converted
    - [ ] enable DST analytics? Yes
    - [ ] remove custom code? Yes

- [x] **Element with custom events:** (Manage your VA benefits and other information online) "Get your VA records and documents online" link
  - [ ] Example page: https://www.va.gov/find-forms/?q=526ez
  - [ ] Event name: nav-linkslist
    - [ ] convert to va-link? Already converted
    - [ ] enable DST analytics? Yes
    - [ ] remove custom code? Yes

- [x] **Element with custom events:** (Frequently used VA forms) Links on the blue sections at the bottom of the page ("File a VA disability claim," etc.)
  - [ ] Example page: https://www.va.gov/find-forms/?q=1010
  - [ ] Event name: nav-featured-content-link-click
    - [ ] convert to va-link? Already converted
    - [ ] enable DST analytics? Yes
    - [ ] remove custom code? Yes

- [ ] **Element with custom events:** (Search results) Form title / link (example: "Research Consent Form")
  - [ ] Example page: https://www.va.gov/find-forms/?q=1010
  - [ ] Event name: onsite-search-results-click
    - [ ] convert to va-link? Already converted
    - [ ] enable DST analytics? Yes
    - [ ] remove custom code? Yes

- [x] **Element with custom events:** (Manage your VA benefits and other information online) "Request your military records, including DD214" link
  - [ ] Example page: https://www.va.gov/find-forms/?q=526ez
  - [ ] Event name: nav-linkslist
    - [ ] convert to va-link? Already converted
    - [ ] enable DST analytics? Yes
    - [ ] remove custom code? Yes

**Comment by chriskim2311** [comment]
@FranECross Upon looking at this ticket, these 3 are not va-links I think we can remove them from the ACs of this ticket.

Button: (Search results) clicking "Download VA Form ##"
Button:  (Download modal) closing the modal
va-select: (Search results) sorting by a value

**Comment by FranECross** [comment]
@chriskim2311 In looking at the page example for (Search results) clicking "Download VA Form ##", they appear as links. Are they actually considered buttons? Thanks!

![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/147188767/5c712341-48a9-4719-84f0-e56723e3ac64)

**Comment by chriskim2311** [comment]
@FranECross Yup! They are buttons that open the pdf download modal specifically. Styled like a link however.

<img width="1525" alt="Find_A_VA_Form___Veterans_Affairs" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/42885441/718f9142-5397-4139-a735-1ae46272db50">

**Comment by FranECross** [comment]
Thanks, @chriskim2311 ! I've removed the three you noted. 😁

**Comment by chriskim2311** [comment]
@FranECross One more question about the VA-Form Link. This when converted to the va-link does lose some data that is being reported to GA. Do you know if this is sufficient or should we leave it as is?

**Current GA Data**
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNHhvQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--05bd36ac27b1b8d4cf48b7a5a31ddcf0a0c051c7/Find_A_VA_Form___Veterans_Affairs.png" alt="Find_A_VA_Form___Veterans_Affairs.png" />

**Converted VA-Link Data**
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNDFvQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--04b1397990a41cf1f6a625e9ac9555ff36126228/Find_A_VA_Form___Veterans_Affairs.png" alt="Find_A_VA_Form___Veterans_Affairs.png" />

**Comment by FranECross** [comment]
@mmiddaugh @davidconlon Context: (We are removing custom Google Analytics code where possible, and using the analytics we get when we adopt a/the component. Chris has informed us that if we remove the custom code in this case, we'll lose some data, however I'm not sure anyone uses/looks at this particular data. Please see the two screenshots he's provided and let us know if you'd like to retain the custom code? I've included Dave C in case there were historical reasons why we have this much detail in the analytics we get. cc @chriskim2311 

We would lose things like (etc.):
- search-results-pagination-current-page: 1,
- search-results-position: 3,

**Comment by chriskim2311** [comment]
Blocked currently waiting on question to be answered,  One PR closed already, one is still open.

**Comment by jilladams** [comment]
MIchelle is double checking with Mikki

**Comment by mmiddaugh** [comment]
- search-results-pagination-current-page: 1,
- search-results-position: 3,

^ these metrics could be useful but only if combined with the search keyword (so that we would understand which specific searches lead to someone going deeper into the search results) -> is this possible with the custom analytics?

apologies if the answer could be found in the images you added - I'm not able to see your images, for some reason

if this is possible, I might be interested in retaining the custom analytics but I want to understand the consequences of that decision. Is there a downside?

@chriskim2311 @FranECross

**Comment by chriskim2311** [comment]
Per this [slack thread](https://dsva.slack.com/archives/C52CL1PKQ/p1720550438988719) with Michelle. We are not going to  convert the form title over to va-link so we can keep the more detailed analytics flowing through GA. Other changes have been verified on prod, closing!
