### ISSUE TITLE
PPMS nprod API key update, June 4

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#18205]
## User Story or Problem Statement
https://dsva.slack.com/archives/C0FQSS30V/p1715982323485409

PPMS is updating API keys. 
Platform manages API keys for us in AWS param store.

Announcement: 
> BLUF: Provider Profile Management System (PPMS) will be migrating it's Azure Environments to a dedicated Azure Subscription. Included in the subscription migration, PPMS will also be upgrading to the Azure Services Environment (ASE) version 3. INT/PPD will begin Testing May 20, 2024 through May 24, 2024. A new URL and the API Subscription Key for your product will be sent this week before testing begins. Please update your new key on 05/20/2024.
> BACKGROUND: VAEC informed PPMS that Azure will be deprecating Azure Services Environment (ASE) version 1 & 2 on August 31, 2024. PPMS has taken advantage of this opportunity to upgrade the current ASE v.2, which requires a migration from our current Shared Subscription to a Dedicated Subscription. These improvements will enhance performance/ scalability, simplify management, and aide in futureproofing for ongoing improvements.
> Next Steps:

- [x] Obtain new subscription key from PPMS Team (between 5/15 – 5/17)
- [ ] Start using the new key in the API request (on 5/21)
- [ ] Send a request to Test

API Keys will be issued out by our team the week before our testing window. Currently the PPD/INT window will be from June 4th to June 7th. We should receive the key week of 5/28.

## Steps for Implementation
* Get the key from PPMS for nprod (lower envs) - they should email us to tell us where / how
* Open a Plat support request to ask them to update the key in the param store
* We can test on dev env using ArgoCD to make sure it works correctly

## Acceptance Criteria
- [x] New API key successfully can call data from PPMS nprod env

**Comment by eselkin** [comment]
In my last comment the forward proxy was pointing to brood and the new key that they emailed today should work with it.

**Comment by eselkin** [comment]
I brought up changing the token to Platform support in this [thread](https://dsva.slack.com/archives/CBU0KDSB1/p1717016026805679)

Joel Njanga identified that they would do it immediately after I sent it to them, so I decided to wait to re-request.

The location of the token value is under: `/dsva-vagov/vets-api/dev/facilities/ppms-apim` on AWS Parameter Store

**Comment by eselkin** [comment]
Added to my calendar to request at 12:30 PT on 6/3 after meeting with Michael Skinner

**Comment by eselkin** [comment]
Requested at 7:11am PT on 6/4
https://dsva.slack.com/archives/CBU0KDSB1/p1717510267665379?thread_ts=1717510264.313569&cid=CBU0KDSB1

**Comment by eselkin** [comment]
So, they had updated the key but then they needed to update the port/forward proxy where PPMS data goes through and the whole dev configuration for the forward proxy seems broken. Something about terraform (the system used for configuring the service). I couldn't really follow the error messages they were copying to me.

**Comment by eselkin** [comment]
Here's the error in daily deploy that's making it impossible for Platform to get the updates to the forward proxy running: https://github.com/department-of-veterans-affairs/vsp-platform-fwdproxy/actions/runs/9402293743/job/25896087298

**Comment by eselkin** [comment]
Forward proxy now sends data to new PPMS URL and with new key

**Comment by jilladams** [comment]
PPMS folks have been notified. Per Eli, ACs are met. Closing.
