### ISSUE TITLE
[Analytics] [Events] Custom GA events removal & va-link component w/analytics adoption

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-cms#18200]
The va-link component has been enhanced to provide destination and can be used now for applicable Outreach & Events features, along with removal of the GA custom events.

Details are in the AC.

### User story

**AS A PO/PM** managing Public Websites products & features
**I WANT** to (where appropriate) adopt the va-link component, its baked-in analytics, and remove the custom GA events
**SO THAT** extraneous code is removed and only the events needed will be triggered.

## Acceptance criteria

- [ ] **Element with custom events:** "See more events" link
  - [ ] Example page: https://www.va.gov/alaska-health-care/events/65945/
  - [ ] Event name: nav-secondary-button-click
    - [ ] convert to va-link? Yes
    - [ ] enable DST analytics? Yes
    - [ ] remove custom code? Yes

**Comment by FranECross** [comment]
@chriskim2311 Do you mind doing an async review of this ticket when you get a moment, and then I can slot it into Stretch/Next Sprint to be pulled in if possible.

**Comment by chriskim2311** [comment]
This has been verified on prod to be changed with the PR linked above, closing!
