### ISSUE TITLE
VBA QA: Grammar fix on Service options 

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#18215]
## Description
A comma should be added to one of the virtual service options for consistency. The current options for Office visits are:
- Visit our office, with or without an appointment
- Visit our office, walk-in visits only
- Visit our office, by appointment only

But then for Virtual support we have:
- Virtual visits by appointment only

This matches the pattern, sentence structure for office visits but is missing a comma. It should be updated to be consistent:
- Virtual visits, by appointment only

## Acceptance Criteria
- [ ] Update virtual visit option on the FE to "Virtual visits, by appointment only"
- [ ] Requires design review

**Comment by davidmpickett** [comment]
Unlike `Visit our office`, `Virtual visits` is not an independent clause. Placing a comma there would not be conventional or consistent with AP style.
