### ISSUE TITLE
Other VBA locations link should be a prefiltered link

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#18219]
## Description 
At the bottom of the VBA page, we have a section for other VA locations in the area with a link to "Find VA Benefits locations". However this links just goes to the Facility locator page. It would be a better user experience if this link was pre-filtered to VA benefits locations - as that is what the link is indicating. We should considering updating this link to: https://www.va.gov/find-locations/?facilityType=benefits

[Example Preview page](https://preview-prod.vfs.va.gov/preview?nodeId=4237):
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/106678594/eb143edd-cb41-4b2e-9d3d-e0e8f4803549)

## Acceptance Criteria
- [x] Determine if the VA Benefits link should be pre-filtered
- [x] Determine if URL parameters can still be used
- [x] Link results in pre-filtered view of facility locator
- [ ] Requires UX/A11y review

**Comment by davidmpickett** [comment]
Agreed. This was the intended behavior. It would match the other identical link in "Can't find the service you're looking for?"

**Comment by davidmpickett** [comment]
Priority suggestion. Launch blocking, but not staging review blocking.

**Comment by davidmpickett** [comment]
Look like the URL parameter was never added.
https://github.com/department-of-veterans-affairs/content-build/blob/main/src/site/layouts/vba_facility.drupal.liquid#L298

**Comment by Agile6MSkinner** [comment]
@eselkin Will verify that URL parameters will still work in the new FE build delivered by IIR.

**Comment by eselkin** [comment]
URL params still work on the new IIR branch

![Screenshot 2024-06-06 at 9 43 20 AM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5606931/9b42a58a-7122-4794-bda7-105a9723f582)

**Comment by davidmpickett** [comment]
Confirmed on Prod / Preview
![Screenshot 2024-06-24 at 12 47 41 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/7b9bb76f-5a36-436c-8d2f-46ee5689b7bd)

**Comment by davidmpickett** [comment]
Just realized I checked the wrong link. This is NOT working on Prod preview. The link is missing a slash before the question mark, so the link isn't properly filtering

https://preview-prod.vfs.va.gov/preview?nodeId=4237

![Screenshot 2024-06-24 at 12 50 40 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/1b7f696e-bf91-4adf-bcc8-c9f9e7096a44)

**Comment by davidmpickett** [comment]
Either link format works correctly on Prod, but lower environments seem finnicky

- https://www.va.gov/find-locations?facilityType=benefits
- https://www.va.gov/find-locations/?facilityType=benefits

- https://preview-prod.vfs.va.gov/find-locations/?facilityType=benefits
- https://preview-prod.vfs.va.gov/find-locations?facilityType=benefits

This ticket technically meets ACs for prod, but might be worth considering the lower environment situation

**Comment by Agile6MSkinner** [comment]
One caveat about the preview server, but that's just something we can keep an eye on.
