### ISSUE TITLE
VBA services should be sorted alphabetically within accordion groups

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#18213]
## Description
Services should be alphabetized within each section, as they are on VAMCs.

On  [National capital](https://web-shoowipgxumevd9gysmbhgkv2catpzm1.demo.cms.va.gov/national-capital-region-va-regional-benefit-office/), Veterans readiness is the last service in Veterans Benefits, but in [Honolulu](https://web-shoowipgxumevd9gysmbhgkv2catpzm1.demo.cms.va.gov/honolulu-va-regional-benefit-office-at-spark-m-matsunaga-department-of-veterans-affairs-medical-center/) it is first. This order should be consistent so folks have an idea of where to find services within the list.

**Honolulu**
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/106678594/25b8aeac-13a2-4db9-bb7a-14a093244e26)

**National Capital**
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/106678594/07acb380-e7c9-42d9-ab8e-0e50b58326fb)

Vs. example VAMC with alpha lists: https://www.va.gov/minneapolis-health-care/health-services/

## Acceptance Criteria
- [x] Determine the order services should be showing in
- [x] Determine if that order is being implemented properly on the FE
- [x] Services should be alphabetized within each section, as they are on VAMCs
- [ ] Requires design review

**Comment by davidmpickett** [comment]
Alphabetical is what is [in Figma](https://www.figma.com/design/88Gw7fmUkDbheSAHjIpHn7/VBA-Regional-Office?node-id=0-1107&t=Sf6fBu71tfOwW0dZ-0) and is consistent with VAMC and Vet center.

Likely that [includes/vba_facilities/services.liquid](https://github.com/department-of-veterans-affairs/content-build/blob/main/src/site/includes/vba_facilities/services.liquid) needs to implement an `SortObjectsBy` similar to [vet_centers/service.liquid](https://github.com/department-of-veterans-affairs/content-build/blob/main/src/site/includes/vet_centers/health_services.liquid)

**Comment by davidmpickett** [comment]
Priority suggestion, Launch blocking, not staging review blocking

**Comment by jilladams** [comment]
Alpha happens within the liquid filter that separates which section a service appears under.

**Comment by randimays** [comment]
This successfully deployed to upper environments, but we can't test in them. It was thoroughly tested in a Tugboat locally, so closing this as complete.
