### ISSUE TITLE
VBA QA: The CTA is not showing on the FE for VBA Spotlights

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#18235]
## Description
The editors have added spotlights with CTAs to local spotlights but they are not showing on the front end. Examples:
- Portland
  - [Preview](http://preview-prod.vfs.va.gov/preview?nodeId=4237)
![Screenshot 2024-05-28 at 4 05 00 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/106678594/8d6dad55-f3c2-4743-a900-7ca398fb1d62)
  - [Drupal](https://prod.cms.va.gov/portland-va-regional-benefit-office)
![Screenshot 2024-05-28 at 4 04 07 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/106678594/0e93287a-9b38-41b2-9030-270022945330)

- Albuquerque
  - [Preview](http://preview-prod.vfs.va.gov/preview?nodeId=4171)
![Screenshot 2024-05-28 at 4 05 00 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/106678594/8d6dad55-f3c2-4743-a900-7ca398fb1d62)
  - [Drupal](https://prod.cms.va.gov/albuquerque-va-regional-benefit-office)
![Screenshot 2024-05-28 at 4 06 53 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/106678594/e60f2a31-f261-4441-beda-60408876f52b)

## Acceptance Criteria
- [x] CTA in local spotlights should display on the FE
- [x] Confirm that CTA in national spotlight also shows
- [ ] Requires accessibility review

**Comment by davidmpickett** [comment]
Verified on Tugboat https://web-jdujzwgvp8kmj36hcfonqejlgtq5b6st.demo.cms.va.gov/philadelphia-va-regional-benefit-office/
![Screenshot 2024-06-26 at 1 55 22 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/ffabe052-6b85-406f-9c2f-e30766715327)
