### ISSUE TITLE
Triage Facility Locator 403 errors in prod, post-mortem, vets-website roll forward

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#18237]
https://dsva.slack.com/archives/C0FQSS30V/p1716925759167659

Facility locator service is showing a 70% error rate in Datadog: https://vagov.ddog-gov.com/apm/services/facility-locator/operations/rack.request?env=eks-prod&start=1716922492774&end=1716926092774&paused=false

## Related monitors
Monitors that report to #facilities-monitoring in DSVA slack did not go off. We may already know about work we need to do in monitors to surface something like this for ourselves, e.g.:
* #18179
* #9399

However: if this didn't push through for reasons that don't connect to those existing tickets (or others in the #15461 monitoring epic), we should account for the work we'll need to do to create monitoring around this.

## Postmortem
Follow postmortem instructions to create a new postmortem: https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/tree/master/Postmortems

Postmortem should also mention the monitoring notes from ACs, probably.

Create a PR for it, and add as reviewers:  Anyone involved in decision making around the incident from our team and from Platform team, including signoff on the OOB deploy.  Reviews often take awhile, so this ticket can be closed when PR is up, doesn't need to wait for merge.

## ACs
- [x] Identify root cause
- [x] Identify if other Datadog monitors should have shown this error or if work to update/create such a monitor is already ticketed
- [x] Cut follow up tickets for implementation work to fix, as needed 
- [x] Post-mortem PR is created for review / approval 
- [ ] vets-website fixes from the following tickets are rolled forward:
  - #12908 
  - #12909 
  - #18127

**Comment by jilladams** [comment]
I made this a giant slush pile of: get back to good here.

**Comment by eselkin** [comment]
Evidently a majority of the requests that turned vets-api red were from https://preview-prod.vfs.va.gov which is a next-build site?

**Comment by eselkin** [comment]
Ticket for adding monitoring that would have caught this is: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18179

**Comment by eselkin** [comment]
The root cause of the error from preview-prod.vfs.va.gov is still not completely understood. We could not find where in the next-build code the requests are coming from that are still sending 7k/15 minutes

**Comment by eselkin** [comment]
This is the postmortem location: https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/2024-05-28-PM-vets-api-403-on-POST-from-vets-website/Postmortems/2024/2024-05-28%20-%20Vets%20API%20403%20on%20POST%20from%20Vets%20Website.md

**Comment by eselkin** [comment]
@jilladams for the postmortem PR https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/pull/1697

It says in the steps to
```
Assign the pull request to the main stakeholder, which cannot be the same individual as the main author of the post mortem.
```
Should that be @EWashb ?

**Comment by jilladams** [comment]
I asked Michelle live today and she confirmed it should be both her and Erika -- I went ahead and made that change on the PR.

**Comment by jilladams** [comment]
Since the roll forward has its own ticket now (#18260 ) I think this can close. The postmortem is up and ready to be reviewed by POs and merging it shouldn't block closing this ticket.
