### ISSUE TITLE
Revert removal of media Video menu item

### ISSUE THREAD

**Issue by ian-sears** [department-of-veterans-affairs/va.gov-cms#18244]
## Describe the defect
As an Editor, when I have a video that was placed up on YouTube, I need to add that video using the Menu items available to me.

## To Reproduce
1. Go to https://prod.cms.va.gov
2. Click on Menu Content >> Media  >> Add media
3. Scroll down to Video to add the video uploaded to YouTube
4. This "Video" menu item needs to be restored or made available to us as Editors ...

## AC / Expected behavior
As an Editor, when I need to add a video I need to see and be able to use that menu item to add my video.

## Screenshots
![image001 (8ffac185-b490-45a3-9f29-d8cca5b4bc08)](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/156952195/3b7684ae-56d5-4a03-8eea-865d0223bb4e)

 ## Additional context
This functionality used to be the norm, however it was recently removed and needs to be restored for use by the Editors.

**Comment by ian-sears** [comment]
dsva discussion: https://dsva.slack.com/archives/CT4GZBM8F/p1716245194587609

**Comment by ian-sears** [comment]
Once the regression is completed, **please notify** @cms-helpdesk in Slack so we can place a notice of "Regressed" into the Editors' msTeams Channel.

**Comment by edmund-dunn** [comment]
The code for this resides in `docroot/modules/custom/va_gov_media/src/EventSubscriber/VaGovMediaAddRouteSubscriber.php`. I just commented out the relevant sections. Once this is ready o go live, those sections will just need to be uncommented and pushed.
