### ISSUE TITLE
URL Change for: New VAMC Facility - Hato Rey VA Clinic - Awaiting CSV

### ISSUE THREAD

**Issue by TroyCMSSupport** [department-of-veterans-affairs/va.gov-cms#18255]
### Implementation date
When does this request need to be live:
ASAP

### Instructions for URL redirect
(Note: This issue will be used from initial request through implementation to ensure all individuals working on this are notified of status updates.  Please do not create multiple issues to track different steps.)
- [x] Notify VA stakeholders as appropriate.
- [x] Link the related facility closure / rename issue.
- [x] Create a URL redirect in the [devops](https://github.com/department-of-veterans-affairs/devops) repo in `ansible/deployment/config/revproxy-vagov/vars/redirects.yml`
- [x] Add the "Awaiting redirect" flag to the facility node with a revision log message that includes a link to this ticket, preserving the node's current moderation state.
- [x] Redirects deploy daily except Friday at 10am ET, or by requesting OOB deploy (of the revproxy job to prod) in #vfs-platform-support. After deploy, validate that the URL redirect is deployed. (Note: In the event of a facility closure or a name change,  validate that this occurs before making the Lighthouse csv changes.)
- [x] Update this ticket with a comment that the redirect has been deployed.
- [x] Remove the "Awaiting redirect" flag on the facility node with a revision log message that includes a link to this ticket, preserving the node's current moderation state.
- [x]  Notify helpdesk via comment on ticket or Slack message in #cms-support that changes are ready for review.

#### URL Redirect
| Current URL  |  Redirect Destination or New URL |
| ---  |  --- |
| https://prod.cms.va.gov/caribbean-health-care/locations/hato-rey-va-clinic | https://www.va.gov/caribbean-health-care/locations/hato-rey-va-clinic |

### 2. Canonical URL removal (if removed from VAST)
**Note: Canonical URL changes do not block the completion of the parent ticket. Once the URL redirect above has been deployed, the value to the Veteran is delivered. This ticket should be kept open until the URL change is verified, except in the case of a removal (as described below).**

### Instructions for canonical URL change
- [x] Verify that the new URL for the facility is published and accessible on VA.gov.
- [x] Update the [CSV in Lighthouse](https://github.com/department-of-veterans-affairs/lighthouse-facilities/blob/master/facilities/src/main/resources/websites.csv) with the changed URL, maintaining the sorted order of the Facility API IDs.
- [x] Create a PR in the [lighthouse-facilities repo](https://github.com/department-of-veterans-affairs/lighthouse-facilities), tagging the Lighthouse team.
- [x] Post a message in the #cms-lighthouse channel in Slack, with an @mention to a Lighthouse team member.
- [x] Add the "Awaiting CSV" flag to the facility node with a revision log message that includes a link to this ticket.
- [x] Validate that the change has deployed by checking that the Facility Locator has been updated with the new url.
- [x] Update this ticket with a comment that the CSV change has been deployed.
- [x] Remove the "Awaiting CSV" flag to the facility node with a revision log message that includes a link to this ticket.

#### URL change example (update with actual ID and URL)
| Facility API ID  |  Full VA.gov URL |
| ---  |  --- |
| vha_672QH | https://www.va.gov/caribbean-health-care/locations/hato-rey-va-clinic |

### Instructions for canonical URL removal
- [x] Try to find the facility via the Facility Locator, using the Facility API ID (e.g. https://va.gov/find-locations/facility/"facility_api_id"). If it is not available, proceed.
- [x] Update the [CSV in Lighthouse](https://github.com/department-of-veterans-affairs/lighthouse-facilities/blob/master/facilities/src/main/resources/websites.csv) removing the row with the Facility API ID.
- [x] Create a PR in the [lighthouse-facilities repo](https://github.com/department-of-veterans-affairs/lighthouse-facilities), tagging the Lighthouse team.
- [x] Post a message in the #cms-lighthouse channel in Slack, with an @mention to a Lighthouse team member.
**Note: there's no check to see if it's not returning anything, as it should already be not showing anything in the Facility Locator.**

#### URL removal example (update with actual ID and URL to remove)
| Facility API ID  |  Full VA.gov URL |
| ---  |  --- |
| vha_672QH | https://www.va.gov/caribbean-health-care/locations/hato-rey-va-clinic |

**Comment by jilladams** [comment]
Facility still in draft: https://prod.cms.va.gov/caribbean-health-care/locations/hato-rey-va-clinic

**Comment by ian-sears** [comment]
Hurricane Beryl may be affecting timely response on progress of this facility in San Juan, PR.

**Comment by ian-sears** [comment]
Editor updated the CMS HD that "The Hato Rey Clinic is [actually] a:  Domiciliary Program and Psychosocial Rehabilitation and Recovery Outpatient Center."
@mmiddaugh **is looking into policy** on how to classify this facility prior to Publishing. We are paused as we wait on Michelle's findings and decision.

**Comment by ian-sears** [comment]
@omahane 
We Published the node for Hato Rey, and made the request in #cms-lighthouse here for the CSV to be updated
https://dsva.slack.com/archives/C02BTJTDFTN/p1725904693342479?thread_ts=1725490925.404569&cid=C02BTJTDFTN

Question for this Runbook to you; 
Have we overlooked a step that reads:
Create a PR in the [lighthouse-facilities repo](https://github.com/department-of-veterans-affairs/lighthouse-facilities), tagging the Lighthouse team.

Does this apply?/not  apply? to this runbook?

Can you advise us both at the @department-of-veterans-affairs/platform-cms-helpdesk how we caqn read and understand this step in the RunBooks, please?

**Comment by jilladams** [comment]
@ian-sears that's an old step that doesn't exist in the [Facility URL Change runbook](https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/.github/ISSUE_TEMPLATE/runbook-facility-url-change.md) anymore. It's in this ticket just bc the ticket was made awhile back from the old version of the runbook template, if that makes sense. You can ignore it -- we can't create pull requests for Lighthouse anymore.

**Comment by TroyCMSSupport** [comment]
@omahane @ian-sears @mmiddaugh @jilladams    CSV has been deployed

**Comment by TroyCMSSupport** [comment]
I've updated the checkboxes and ensured completion - I am closing as COMPLETE
