### ISSUE TITLE
New VAMC Facility: Hato Rey VA Clinic - Awaiting CSV

### ISSUE THREAD

**Issue by TroyCMSSupport** [department-of-veterans-affairs/va.gov-cms#18254]
## Intake
- [x] What triggered this runbook? (Flag in CMS, Help desk ticket, Product team, VHA Digital Media)
Trigger: Flag in CMS

- [x] Link to associated help desk ticket (if applicable)
Help desk ticket: [VAHELP-7543](https://va-gov.atlassian.net/browse/VAHELP-7543)
[VAHELP-7629](https://va-gov.atlassian.net/jira/servicedesk/projects/VAHELP/queues/custom/22/VAHELP-7629)

- [x] Name of submitter (if applicable)
Submitter:  Cynthia Snook

- [x] If the submitter is an editor, send them links to any relevant KB articles for the VAMC Facility product.
KB articles: [KB Article link](https://prod.cms.va.gov/help/vamc/about-locations-content-for-vamcs/how-do-i-add-a-facility-to-my-health-care-system)  **n/a**

- [x] Link to facility in production:
Facility CMS link: [Facility link](https://prod.cms.va.gov/locations/hato-rey-va-clinic)
Facility API ID: vha_672QH

### New VAMC Facility
Please refer to the Knowledge Base article titled "How do I add a facility to my health care system?" for more information: https://prod.cms.va.gov/help/vamc/about-locations-content-for-vamcs/how-do-i-add-a-facility-to-my-health-care-system

#### CMS help desk steps
**Note: If the help desk is waiting on information from the facility staff or editor, add the "Awaiting editor" flag to the facility with a log message that includes a link to this ticket. Remove the flag when the ticket is ready to be worked by the Facilities team. Be sure to preserve the current moderation state of the node when adding or removing the flag.**
- [x] 1. Become aware that the new facility is now on the Facility API (typically, via a Flag, but this may come in as a helpdesk ticket).
- [x] 2. If the editor has followed the steps from the above Knowledge Base article and included which section and VAMC the facility belongs to (i.e. VA Pittsburgh), great! **Proceed to step 3.** If not, please check with the editor or VHA digital media regarding what section and VAMC it belongs to.
- [x] 3. Updates the Section (default is "VAMC facilities", but it should be a VAMC system in a VISN) and VAMC system field accordingly.
- [x] 4. Communicate with editor (cc VHA Digital Media) to give them go-ahead to complete the content, with this [KB article](https://prod.cms.va.gov/help/vamc/about-locations-content-for-vamcs/how-do-i-add-a-facility-to-my-health-care-system). (See sample notification email below)

<details><summary>Email template </summary>

```

Hello! You should now be able to edit the draft page for this facility, located at [LINK TO NEW FACILITY DRAFT PAGE ON PROD]

Important: Please make sure that all relevant steps listed within the “How do I add a facility to my health care system?” Knowledge Base article have been completed: https://prod.cms.va.gov/help/vamc/about-locations-content-for-vamcs/how-do-i-add-a-facility-to-my-health-care-system

Once finished, please save this page (and all related VAMC Facility Health Service pages) in the moderation state “Draft." Please do not save them as “Published.”

Please let us know when your draft content is complete, so that we can wrap up the technical process from our end before publishing the new facility to VA.gov. Thanks!

```

</details>

- [x] 5. Create a [URL change request](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/new?assignees=&template=runbook-facility-url-change.md&title=URL+Change+for%3A+%3Cinsert+facility+name%3E), changing the entry from the old facility URL to the new facility URL. (**Note: The URL change request ticket blocks the completion of this ticket.**)

[URL Change Request Link 18255](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18255)

- [x] 6. When editor has prepared content and let help desk know, reassign this issue to appropriate CMS engineer on Product Support team, for bulk publishing.

#### CMS engineer steps
- [x] 7. CMS engineer executes the steps of the URL change request ticket from step 5 above.

(Redirects deploy daily except Friday at 10am ET, or by requesting OOB deploy (of the revproxy job to prod) in #vfs-platform-support. Coordinate the items below and canonical URL change after URL change ticket is merged, deployed, and verified in prod.)

#### Drupal Admin steps (CMS Engineer or Help desk)
_Help desk will complete these steps or escalate to request help from CMS engineering._
- [x] 8. Drupal Admin bulk publishes nodes and facility.
- [x] 9. Drupal Admin edit facility node and remove `New facility` flag and save node.
- [x] 10. Let Help desk know this has been done, if not done by Help desk.

#### CMS Help desk (wrap up)
- [x] 11. Notify editor and any other stakeholders.

[VAHELP-7543]: https://va-gov.atlassian.net/browse/VAHELP-7543?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[VAHELP-7629]: https://va-gov.atlassian.net/browse/VAHELP-7629?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by TroyCMSSupport** [comment]
@ian-sears @jilladams @omahane  -- Editor has confirmed an Opening Date of June 24, 2024. I have provided the KBA regarding adding new facilities and let them know that they site is ready for their updates.

**Comment by jilladams** [comment]
Facility is still in Draft: https://prod.cms.va.gov/caribbean-health-care/locations/hato-rey-va-clinic

**Comment by ian-sears** [comment]
New information from the Editor this morning.
The Hato Rey Clinic is a:  **Domiciliary Program** and Psychosocial Rehabilitation and Recovery Outpatient Center

This is the first time I will be handling a Domicilliary, so I will be looking up all references I've been provided to understand how, or differently these typse of Facilities are to be managed.

**Comment by TroyCMSSupport** [comment]
@ian-sears the followup comment from Hato Rey was to disregard the Domiciliary comment - Should be ready to Publish

**Comment by mmiddaugh** [comment]
@ian-sears We learned from VHA DM this week that this location is a facility which has a co-located domiliciary. Please help the editor create pages consistent with a new VA health facility and a domiliciary page, as outlined in the KB article, [How to add a Community Living Center or Domiciliary detail page](https://prod.cms.va.gov/help/vamc/about-locations-content-for-vamcs/how-to-add-a-community-living-center-or-domiciliary-detail-page)

**Comment by TroyCMSSupport** [comment]
@omahane Still awaiting CSV

**Comment by TroyCMSSupport** [comment]
Looks like all is well with Hato-Rey (except Health services, which are addressed in the Jira ticket); Closing this ticket as COMPLETE. 
Thank you all @jilladams @omahane @ian-sears @mmiddaugh for your help, guidance, and patience.
