### ISSUE TITLE
Roll forward changes from v0 to v1 lighthouse, using Facilities API v2

### ISSUE THREAD

**Issue by eselkin** [department-of-veterans-affairs/va.gov-cms#18260]
## User Story or Problem Statement

After difficulties bringing in the v0 -> v1 LH changes using Facilities Api V2 endpoints, we have resolved the CSRF issues on the backend (and added rack attack limits and monitoring). We are rolling forward the changes initially from #12908.

## Acceptance Criteria
- [x] VAMC Facility Pages use `/facilities_api/v2/va`
- [x] VAMC Locations Listing Page uses `/facilities_api/v2/va`
- [x] Vet Center Facility Pages use `/facilities_api/v2/va`
- [x] Vet Center Facility Locations Pages use `/facilities_api/v2/va`
- [x] VBA Facilities use `/facilities_api/v2/va` and not `/facilities_api/v2/va`
- [x] Testing is updated to cover use of new endpoints
- [x] Testing is completed that ensures no 403 errors

**Comment by jilladams** [comment]
This has been deployed, no issues so far in production. Closing.
