### ISSUE TITLE
Add default appt intro text for VBA & logic to conditionally display VBA/VAMC

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#18273]
## Description or Additional Context 
Blocks https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17999
See 17999 for visual details

Only one default text string for appointment introductions exists, which is currently written for VMACs. There needs to be a separate text string that will act as the default text displayed for VBA facilities.

## Copy
VBA Appt Info default text: "Contact us to schedule, reschedule, or cancel your appointment."

VAMC Appt Info default text: "Contact us to schedule, reschedule, or cancel your appointment. If a referral is required, you’ll need to contact your primary care provider first."

## Manual testing expectations
Use Tugboat to test
Verify that FE correctly presents with all data cases: 

| Data |  VAMC | VBA |  
| --- | --- | --- | 
| Default text |    |   | 
| Custom text |    |   | 
| Remove text |     |   | 

## Acceptance Criteria
- [ ] FE correctly handles all possible Drupal values for Appointment intro text, for both VBA and VAMC

**Comment by jilladams** [comment]
Marked as a Staging Review blocker, since the FE ticket also was. 

FYI @Agile6MSkinner this is the one for refinement

**Comment by Agile6MSkinner** [comment]
Going to repurpose this ticket to add VBA default text and add logic to conditionally display based on if it is VBA or VAMC

**Comment by davidmpickett** [comment]
Verified on Tugboat https://web-jdujzwgvp8kmj36hcfonqejlgtq5b6st.demo.cms.va.gov/philadelphia-va-regional-benefit-office/

![Screenshot 2024-06-26 at 1 56 24 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/633a06c8-5a2d-4489-a8ed-1ec9095e4acc)
