### ISSUE TITLE
Remove extra spacing on the va-on-this-page component

### ISSUE THREAD

**Issue by randimays** [department-of-veterans-affairs/va.gov-cms#18270]
## Description
The `va-on-this-page` component in some of our content-build templates has left margin that causes the component to not align with content on smaller screens.

Examples:
<img width="300" alt="Screenshot 2024-06-04 at 12 39 27 PM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/19175324/50472bae-6cac-4d17-9fb1-a928cf7341f2">
<img width="300" alt="Screenshot 2024-06-04 at 12 39 21 PM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/19175324/174b3e48-efdd-4b48-a7c1-d630358b4e6d">

We need to remove this margin so the content and the `va-on-this-page` component will left-align on smaller screens.

Templates where this spacing still exists:
- [basic_landing_page.drupal.liquid](https://github.com/department-of-veterans-affairs/content-build/blob/main/src/site/layouts/basic_landing_page.drupal.liquid) - Not sure there's a prod example for this as this template is only at `/resources` and doesn't have the `fieldTableOfContentsBoolean` marked true
- [faq_multiple_q_a.drupal.liquid](https://github.com/department-of-veterans-affairs/content-build/blob/main/src/site/layouts/faq_multiple_q_a.drupal.liquid) - `/resources/verifying-your-identity-on-vagov/`
- [landing_page.drupal.liquid](https://github.com/department-of-veterans-affairs/content-build/blob/main/src/site/layouts/landing_page.drupal.liquid) - `/service-member-benefits/`
- [page.drupal.liquid](https://github.com/department-of-veterans-affairs/content-build/blob/main/src/site/layouts/page.drupal.liquid) - `/records/get-military-service-records/`
- [support_resources_detail_page.drupal.liquid](https://github.com/department-of-veterans-affairs/content-build/blob/main/src/site/layouts/support_resources_detail_page.drupal.liquid) - `/resources/reimbursed-va-travel-expenses-and-mileage-rate/`
- [vamc_operating_status_and_alerts.drupal.liquid](https://github.com/department-of-veterans-affairs/content-build/blob/main/src/site/layouts/vamc_operating_status_and_alerts.drupal.liquid) - `/tuscaloosa-health-care/operating-status/`
- [vamc_system_policies_page.drupal.liquid](https://github.com/department-of-veterans-affairs/content-build/blob/main/src/site/layouts/vamc_system_policies_page.drupal.liquid) - `/puget-sound-health-care/policies/`
- [vamc_system_va_police.drupal.liquid](https://github.com/department-of-veterans-affairs/content-build/blob/main/src/site/layouts/vamc_system_va_police.drupal.liquid) - `/puget-sound-health-care/va-police/`
- [vba_facility.drupal.liquid](https://github.com/department-of-veterans-affairs/content-build/blob/main/src/site/layouts/vba_facility.drupal.liquid) - No prod examples yet as VBA facilities aren't launched. Locally: `yarn preview` and use http://localhost:3002/preview?nodeId=4171
- [vet_center.drupal.liquid](https://github.com/department-of-veterans-affairs/content-build/blob/main/src/site/layouts/vet_center.drupal.liquid) - `/bangor-vet-center`

### Engineering notes / background
This is the implementation of the component on templates that still have the spacing:
```<va-on-this-page class="vads-u-margin-left--1 vads-u-margin-bottom--0 vads-u-padding-bottom--0"></va-on-this-page>```

In many cases, no classes are needed on va-on-this-page at all. Ideally we can remove all of the spacing classes since va-on-this-page does not come with margin or padding on the bottom. 

## Acceptance criteria
- [ ] Remove all unneeded margins and padding from the above templates
- [ ] Test each template on desktop and mobile for spacing
- [ ] Design review

**Comment by chriskim2311** [comment]
Pulling this in to work on this sprint

**Comment by chriskim2311** [comment]
Verified on prod, closing!
