### ISSUE TITLE
Incorporate Most Common Workflows in Comprehensive Test Plan

### ISSUE THREAD

**Issue by gracekretschmer-metrostar** [department-of-veterans-affairs/va.gov-cms#18275]
## User Story or Problem Statement
As a QA engineer, I need to understand the critical user flows for the CMS to inform appropriate testing coverage for the platform. 

## Description or Additional Context 
@srancour determined the most common user flows to inform the focus of the 508 office's audit and this work can help inform the critical workflows for the CMS platform. There are gaps in the existing research on most common user flows, that should be taken in consideration and flagged for this work. 

## Relevant Links
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18272
- https://vfs.atlassian.net/wiki/spaces/~712020eee99537517b4d9594003707b252e24b/pages/3079766076/CMS+Test+Plan+Discovery

## Steps for Implementation
- @keisterj-oddball review's the research and findings for the most common user flows work done for the 508 office's audit
- @keisterj-oddball maps the most common user flows 

## Acceptance Criteria
- [ ] The most common user flows are used to scope the comprehensive test plan for QA CMS.
- [ ] Gaps in the most common user flows and identified to inform future research.

**Comment by keisterj-oddball** [comment]
I've incorporated the common workflow data that Steve had put together for the 508 office audit.  The workflows from that data are indicated in blue on the Critical Path Tests tab of the following google sheet: [CMS Test Plan](https://docs.google.com/spreadsheets/d/1SodVsDSzwaP5oMU8E0189d9dm2pAYAWiPbazseSRK-c/edit?gid=0#gid=0)

This will be transferred to a more accessible space once the comprehensive test plan is in a more mature state.
