### ISSUE TITLE
Kick off CMS Audit with 508 Office

### ISSUE THREAD

**Issue by gracekretschmer-metrostar** [department-of-veterans-affairs/va.gov-cms#18272]
## User Story or Problem Statement
The CMS team needs to hand over materials and information to the 508 office so that they can begin their audit of CMS. 

## Description or Additional Context 
The 508 office will be doing a spot audit of CMS and to begin that work the office needs the most common user flows, test accounts, and sandbox environment. 

## Steps for Implementation
- Synthesize the outcomes from https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18077 
- Create comms to contextualize the outcomes we are handing over
- Bundling information into an email to the 508 office. 

## Acceptance Criteria
- [x] The 508 office has the information that they need to begin their audit of CMS.

**Comment by srancour** [comment]
Vet Center:
- Users to use
  - 4730: jeffrey.deluca@va.gov

- Flows:
  - Review and edit Main Center page -
    - Knowledge base explanation flow: Knowledge Base - Vet Centers - Vet center content review
    - Edit flow: follow knowledge base explanation on Vet center content review and edit and add one item of each type available to add. Remove and add a photo as well.


VISN/VAMC/Medical Centers/health centers:
- User to use
  - 5014: Dennis.Ranch@va.gov

- Flows
  - Health care local health service -
    - Knowledge base explanation flow: Knowledge Base - VA Medical Centers (VAMCs) - How to add, edit, or remove a VAMC facility health service
    - Add flow: Manage in top menu - Content in sub menu - add content - VAMC Facility Health Service
    - Edit flow: select section (VISN 10) - VA Ann Arbor health care - Content type dropdown menu and select VAMC Facility Health Service - Filter - Edit

  - Health care region page - 13,960
    - Knowledge base explanation flow: Knowledge Base - VA Medical Centers (VAMCs) - How to edit a VAMC Healthcare System homepage
    - Edit flow: select section (VISN 10) - VA Ann Arbor health care - Content type dropdown menu and select VAMC System - Filter - Edit

  - Person profile - 7,087
    - Knowledge base explanation flow: Knowledge Base - VA Medical Centers (VAMCs) - How to edit or add a staff profile
    - Add flow:
      - Verify staff profile doesn't exist: Manage in top menu - Content in sub menu - Title field enter last name - select Staff Profile in content type dropdown - Filter - verify doesn't exist 
      - Add new: Manage in top menu - Content in sub menu - add content - staff profile

  - Event - 6,468
    - Knowledge base explanation flow: Knowledge Base - VA Medical Centers (VAMCs) - How to add a new event
    - Add flow: Manage in top menu - Content in sub menu - add content - event

  - News - 4,182
    - Knowledge base explanation flow: Knowledge Base - VA Medical Centers (VAMCs) - How to add a story
    - Add flow: Manage in top menu - Content in sub menu - add content - story


Outreach hub:
- User to use:
  - 4982: Michael.Billings@va.gov

- Flows
  - Outreach materials
    - Knowledge base explanation flow: Knowledge Base - Outreach Hub - How to add, edit, or remove outreach materials in the Outreach Library
    - Add flow: Manage in top menu - Content in sub menu - add content - Publication
    - Edit flow: Manage in top menu - Content in sub menu - Content type dropdown menu and select Publication - Filter - Edit
