### ISSUE TITLE
Next-Build local environment failures

### ISSUE THREAD

**Issue by JakeBapple** [department-of-veterans-affairs/va.gov-cms#18286]
## User Story or Problem Statement
As a user (developer specifically), I would like to be able to follow the instructions in the next-build repository ([next-build](https://github.com/department-of-veterans-affairs/next-build)).

## Description or Additional Context 
As developers, we need to be able to use both va.gov-cms and next-build repositories simultaneously. We should be able to tear down repos and rebuild that at any time with the README files provided. Right now, @JakeBapple is running into the following error when trying to build Next Build local environment: 

Right now, error that is stalling is on the "yarn setup" task when running the basic installation method:

`Removed existing vets-website assets. Preparing to gather fresh from https://prod-va-gov-assets.s3-us-gov-west-1.amazonaws.com

/xxxxxx/next-build/node_modules/node-fetch/lib/index.js:1501
                        reject(new FetchError(`request to ${request.url} failed, reason: ${err.message}`, 'system', err));
                               ^
FetchError: request to https://prod-va-gov-assets.s3-us-gov-west-1.amazonaws.com/generated/node_modules_department-of-veterans-affairs_web-components_dist_esm-es5_va-accordion-item_entry_js.entry.js failed, reason: read ECONNRESET
    at ClientRequest.<anonymous> (/Users/jbapple/Desktop/Workbench/NEXT_BUILD/next-build/node_modules/node-fetch/lib/index.js:1501:11)
    at ClientRequest.emit (node:events:517:28)
    at TLSSocket.socketErrorListener (node:_http_client:501:9)
    at TLSSocket.emit (node:events:517:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  type: 'system',
  errno: 'ECONNRESET',
  code: 'ECONNRESET'
}

Node.js v18.20.3`

This specific error (ECONNRESET) is consistent, but the file it fails on does fluctuate.

## Steps for Implementation
- Determine if @JakeBapple's error is specific to his machine or a global issue. 
- Go to the next-build repository here: [next-build](https://github.com/department-of-veterans-affairs/next-build)
- Spin up a local from nothing and be able to choose any of the available options as described from the repo

NOTE: this work will most likely include updating the next-build repository's README

## Acceptance Criteria
- [ ] Setup local with basic instructions from nothing
- [ ] Setup local with Local CMS option from nothing
- [ ] Setup local with Vets-Website option from nothing

**Comment by gracekretschmer-metrostar** [comment]
Possible next steps: have @anantais remove your local set up for Next Build and readd it, to determine if this is @JakeBapple specific or a more global issue.

**Comment by anantais** [comment]
I managed to break my own local install on the same yarn setup step but the error message is different. 

/Users/anantaisaustin/Sites/next-build/node_modules/node-fetch/lib/index.js:1501
			reject(new FetchError(`request to ${request.url} failed, reason: ${err.message}`, 'system', err));
			       ^
FetchError: request to https://prod-va-gov-assets.s3-us-gov-west-1.amazonaws.com/generated/0996-higher-level-review.entry.js failed, reason: connect ENOMEM 108.175.50.160:443 - Local (0.0.0.0:0)
    at ClientRequest.<anonymous> (/Users/anantaisaustin/Sites/next-build/node_modules/node-fetch/lib/index.js:1501:11)
    at ClientRequest.emit (node:events:517:28)
    at TLSSocket.socketErrorListener (node:_http_client:501:9)
    at TLSSocket.emit (node:events:517:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  type: 'system',
  errno: 'ENOMEM',
  code: 'ENOMEM'
}

Node.js v18.20.2

**Comment by anantais** [comment]
I managed to fix this issue by altering this file and then running yarn setup - .github/workflows/content-release.yml

This is what changed in the file. 

    - name: Setup Yarn
      run: |
        cd main
        corepack enable
        corepack install -g --cache-only .yarn/releases/corepack.tgz

    - name: Install dependencies
      run: cd main && yarn

    - name: Install awscli
      run: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip -o awscliv2.zip
        ./aws/install

    - uses: actions/setup-node@v4
      with:
        node-version: 18


At line 159 I put the Yarn Setup and install steps to run before awscli and setup-node. I found people with similar errors and in multiple online discussions it came up that running corepack enable before node was the best fix. Running it after node appears to cause some of these issues.

So, this solution worked for me and allowed me to run "yarn setup". I have reinstalled twice now and was able to use this same fix. The only caveat is that, after changing the file, I need to run "yarn setup" twice to get it to work. Not sure if it is caching the old file or there is something else I would need to add this to. Also not sure if this will fix Jake's issue.

**Comment by JakeBapple** [comment]
Even after a complete re-install and adjusting the onctent-release.yml file, i'm still running into the same issue unfortunately.

**Comment by JakeBapple** [comment]
Troubleshooting with Nick included:
- moving rootCA.pem file
- updating env.local file with key/value pairs
- tried to switch to different versions of node (18.20.1)
- generating site with redis (this "worked" in that the pages showed generation but no local was up)
- yarn build and yarn dev showing errors after changing line 111 to default to localhost
- possible short-term work-around being the above method combined with a zipped up package of working local files from Nick.

**Comment by gracekretschmer-metrostar** [comment]
Thanks, Jake. I am going to sync with @mreed101 and @timcosgrove later today to determine next steps.

**Comment by JakeBapple** [comment]
@nfpappas-oddball  solved the files issue! we need to update the urls being used in vets-website-assets.js from https to http.

**Comment by gracekretschmer-metrostar** [comment]
@JakeBapple can you confirm that this issue has been resolved? 

Thread with the current status: https://dsva.slack.com/archives/C01SR56755H/p1718657568274729

**Comment by JakeBapple** [comment]
Confirming, I can now see pages from next-build locally with that adjustment! Will work with Nick and Therisa to see if this change will mess their locals up before I push a commit.

**Comment by JakeBapple** [comment]
PR is up here: https://github.com/department-of-veterans-affairs/next-build/pull/561

This is a fix for local, but per @nfpappas-oddball suggestion, we should create a new ticket for investigating why we needed to change from https to http.
