### ISSUE TITLE
DUE: June 12 - Test injected header and Review Typography issues and pass off to DST 

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#18285]
## Status
**[2024-06-12]** Review completed; mural updated; changes posted to DST on their [PR](https://github.com/department-of-veterans-affairs/vets-website/pull/30089#pullrequestreview-2109678119)

## Background
Jordan and I are reviewing the DST PR for step 2 of their Typography update. Change announcement and details are in the [slack post here](https://dsva.slack.com/archives/C03R5SBELQM/p1717618603508049).

Their ask for feedback is:

> If something needs to be addressed, please leave a review comment on the [package.json file](https://github.com/department-of-veterans-affairs/vets-website/pull/30089/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R261), stating what team you are from, a screenshot of the content that needs to be addressed, and a link to the manifest.json file of your application in vets-website. Please thread any additional comments to your original top level comment on the package.json file.

## Description
There are 2 asks here:

1. The injected header/footer can only be reviewed locally, which Jordan and I are not great at doing. Can you please review/test the DST PR locally and see if there are any issues here? We would want to confirm that the follow all look good on Desktop, Tablet and Mobile:
   - Header
   - Footer
   - VCL modal

2. Jordan and I are reviewing everything visually and aren't able to provide feedback in the way DST is requesting. We need some assistance here.
   - Can you please review the issues documented in the mural below and provide feedback to the DST in the format they have requested based on what Jordan and I have found?

### Resources
- We are using [the DST review instance](http://c55ef0615acff58b32655196f7de6bed.review.vetsgov-internal/) provided
- We are tracking the progress on where we are with the audit in [this google sheet](https://docs.google.com/spreadsheets/d/1rEKHNoeC4x6jW4e8mgYZL991m781CgblGXNS7iJzgU8/edit#gid=2080021802).
- We are noting any issues we find in [this mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1715017468641/ffb7fbb561bbca436ad535ecbbf0b96815413c29?wid=0-1717621280278&sender=u10a597890f85398daa3c4805) under the Phase 2 heading

## Acceptance Criteria
- [x] Review the injected header/footer locally and report and issues to the DST
- [x] Review Income limits
- [x] Review all issues documented in the mural
- [x] Provide feedback to DST in their PR in the format request
- [x] All feedback is provided to DST by EOD June 12

**Comment by laflannery** [comment]
@thejordanwood for awareness

**Comment by FranECross** [comment]
@chriskim2311 I imagine this will be in Sprint 6, in support of Randi's injected header/footer work, yes? If so, I'll scoot it to Stretch/Next Sprint and tag it with Sprint 6. TIA!

**Comment by laflannery** [comment]
@FranECross this work is for the typography audit that is being done now and will need to be done before sprint 6 as there is a deadline of June 12

**Comment by FranECross** [comment]
Gotcha! @chriskim2311 Please estimate/move the ticket to where you need it, when you need it. Thanks for the clarification, @laflannery !!

**Comment by thejordanwood** [comment]
Update: Laura and I have finished our initial review and [the Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1715017468641/ffb7fbb561bbca436ad535ecbbf0b96815413c29?wid=0-1717621280278&sender=u10a597890f85398daa3c4805) is up to date.

**Comment by thejordanwood** [comment]
@chriskim2311 I have an additional request. Could you also test income limits? This needs to be tested locally because you can't get past the API/Zip code field in a Review instance. I'm still a rookie when it comes to testing locally and can't figure out how to do this.

**Comment by jilladams** [comment]
@chriskim2311 @FranECross note here - if we're not able to get through this by EOD tomorrow, could one of you ping Micah Chiang to let him know we'll need a little more time for Sitewide?

**Comment by FranECross** [comment]
@jilladams Will do!

**Comment by chriskim2311** [comment]
@thejordanwood Income limits looks good locally!

**Comment by chriskim2311** [comment]
@jilladams @FranECross @laflannery @thejordanwood Hi all! I have posted the requested changes to DST on their PR [here](https://github.com/department-of-veterans-affairs/vets-website/pull/30089#pullrequestreview-2109678119). I'll continue to monitor and if they need any changes or more info I can provide.

Question should I attach the mural to the PR comment?

**Comment by thejordanwood** [comment]
@chriskim2311 Thank you for doing that! I don't think it would hurt to attach the Mural to the comment, just in case it's helpful for them.

**Comment by jilladams** [comment]
(Closing this since we've shared feedback. )
