### ISSUE TITLE
[Link Behavior] Correct external link behavior based on updates to design standards

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-cms#18287]
## Description

Update link behavior per the link audit performed in ticket #[81506](https://github.com/department-of-veterans-affairs/va.gov-team/issues/81506). 

## Acceptance criteria

[Spreadsheet with details](https://docs.google.com/spreadsheets/d/1V8FVt8Kx2L0eNFIoiAqr1HWwH9DXqusVuskj9wEtyAU/edit#gid=1298545092)

- [x] Campaign Landing Page links noted in spreadsheet are NOT updated
- [x] Discharge Upgrade Wizard is updated with "open in new tab' behavior per the spreadsheet
- [x] Education SCO is updated to remove the new tab behavior per the spreadsheet
- [x] Events page links noted in the spreadsheet are updated to remove the new tab behavior.
- [x] Find Forms links are updated per the spreadsheet (combo of one removal and additions of new tab behavior)
- [x] Header Footer links are updated to remove new tab behavior per the spreadsheet

**Comment by randimays** [comment]
Pulling in to Sprint 6 as stretch.

**Comment by randimays** [comment]
Validated successfully in production. Closing!
