### ISSUE TITLE
Add Character counter on phone paragraph type field in Drupal

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#18281]
## Description
Currently the **Phone number** field and the **Extension number** field on the phone paragraph type in Drupal both have a character limit of 12 but no indication of this. We should add the character counter both of these fields. The character counters should function as display the same as they currently do on the VBA Facility content type:
- No border should be applied to the text field in any state (aside from existing focus border)
- When the user gone over the character limit, change the styling of the `X characters remaining` to bold and red (--va-red-dark #CD2026)

## Acceptance Criteria
- [x] Character counter following design guidelines has been added to Phone number field
- [x] Character counter following design guidelines has been added to Extension number field
- [x] QA has been done on multiple instances of this field
- [ ] Requires design review
- [ ] Requires accessibility review

**Comment by laflannery** [comment]
@Agile6MSkinner - Part of the broken up Phone validation ticket

**Comment by davidmpickett** [comment]
This is a pretty straight forward config change that is within my scope of practice as a Drupal Sitebuilder.

**Comment by davidmpickett** [comment]
Verified on prod
![Screenshot 2024-07-22 at 3 12 24 PM](https://github.com/user-attachments/assets/f57dc33f-1496-4f18-9571-93a11d5737bb)
