### ISSUE TITLE
URL change for: Langley VA Clinic - New Facility

### ISSUE THREAD

**Issue by TroyCMSSupport** [department-of-veterans-affairs/va.gov-cms#18297]
Parent ticket: #18296 

Implementation date
When does this request need to be live:
[MM/DD/YYYY]

### Instructions for canonical URL change
- [x] Verify that the new URL for the facility is published and accessible on VA.gov.
- [x] Update the [CSV in Lighthouse](https://github.com/department-of-veterans-affairs/lighthouse-facilities/blob/master/facilities/src/main/resources/websites.csv) with the changed URL, maintaining the sorted order of the Facility API IDs.
- [x] Create a PR in the [lighthouse-facilities repo](https://github.com/department-of-veterans-affairs/lighthouse-facilities), tagging the Lighthouse team.
- [x] Post a message in the #cms-lighthouse channel in Slack, with an @mention to a Lighthouse team member.
- [x] Add the "Awaiting CSV" flag to the facility node with a revision log message that includes a link to this ticket.
- [x] Validate that the change has deployed by checking that the Facility Locator has been updated with the new url.
- [x] Update this ticket with a comment that the CSV change has been deployed.
- [x] Remove the "Awaiting CSV" flag to the facility node with a revision log message that includes a link to this ticket.

#### URL change example (update with actual ID and URL)
| Facility API ID  |  Full VA.gov URL |
| ---  |  --- |
| vha_590QD | https://www.va.gov/hampton-health-care/locations/langley-va-clinic/ |

**Comment by omahane** [comment]
@TroyCMSSupport Thanks for making this ticket. New facilities don't get redirects. I'll reconfigure this for a canonical URL change.

**Comment by omahane** [comment]
@mmiddaugh I am waiting to put in the request for a canonical url until I better understand whether we want a published facility with no listed services to have a canonical link. The current page off of the Facility Locator at least has Primary Care listed:
https://www.va.gov/find-locations/facility/vha_590QD
![Screenshot 2024-06-26 at 9 34 04 AM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/766573/cb17adfe-e681-49b0-9f88-6984f4052271)

The Drupal sourced page describes having primary care and dental in the page introduction. If that is sufficient despite no facility services, I'll put in the request for the canonical link:
https://www.va.gov/hampton-health-care/locations/langley-va-clinic/
![Screenshot 2024-06-26 at 9 36 57 AM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/766573/64bba781-093b-4f9c-955a-3f924c401400)

**Comment by omahane** [comment]
I have put in a canonical link request [via Slack](https://dsva.slack.com/archives/C02BTJTDFTN/p1719594660449489?thread_ts=1719340047.322509&cid=C02BTJTDFTN).

**Comment by omahane** [comment]
The canonical URL has been deployed, [per Adam](https://dsva.slack.com/archives/C02BTJTDFTN/p1720015713762209?thread_ts=1719340047.322509&cid=C02BTJTDFTN), and verified by me on VA.gov.
