### ISSUE TITLE
URL Change for: VAMC Facility URL change:  from 'Jacksonville Southpoint VA Clinic' to 'Jacksonville North VA Clinic'

### ISSUE THREAD

**Issue by TroyCMSSupport** [department-of-veterans-affairs/va.gov-cms#18290]
### Implementation date
When does this request need to be live:
ASAP

### Instructions for URL redirect
(Note: This issue will be used from initial request through implementation to ensure all individuals working on this are notified of status updates.  Please do not create multiple issues to track different steps.)
- [x] Notify VA stakeholders as appropriate.
- [x] Link the related facility closure / rename issue. #18289 
- [x] Create a URL redirect in the [devops](https://github.com/department-of-veterans-affairs/devops) repo in `ansible/deployment/config/revproxy-vagov/vars/redirects.yml`
- [x] Add the "Awaiting redirect" flag to the facility node with a revision log message that includes a link to this ticket, preserving the node's current moderation state.
- [x] Redirects deploy daily except Friday at 10am ET, or by requesting OOB deploy (of the revproxy job to prod) in #vfs-platform-support. After deploy, validate that the URL redirect is deployed. (Note: In the event of a facility closure or a name change,  validate that this occurs before making the Lighthouse csv changes.)
- [x] Update this ticket with a comment that the redirect has been deployed.
- [x] Remove the "Awaiting redirect" flag on the facility node with a revision log message that includes a link to this ticket, preserving the node's current moderation state.
- [x]  Notify helpdesk via comment on ticket or Slack message in #cms-support that changes are ready for review.

#### URL Redirect
| Current URL  |  Redirect Destination or New URL |
| ---  |  --- |
| https://www.va.gov/north-florida-health-care/locations/jacksonville-southpoint-va-clinic/ | https://www.va.gov/north-florida-health-care/locations/jacksonville-north-va-clinic/ |

### 1. Canonical URL change or

**Note: Canonical URL changes do not block the completion of the parent ticket. Once the URL redirect above has been deployed, the value to the Veteran is delivered. This ticket should be kept open until the URL change is verified, except in the case of a removal (as described below).**

### Instructions for canonical URL change
- [x] Verify that the new URL for the facility is published and accessible on VA.gov.
- [x] Update the [CSV in Lighthouse](https://github.com/department-of-veterans-affairs/lighthouse-facilities/blob/master/facilities/src/main/resources/websites.csv) with the changed URL, maintaining the sorted order of the Facility API IDs.
- [x] Create a PR in the [lighthouse-facilities repo](https://github.com/department-of-veterans-affairs/lighthouse-facilities), tagging the Lighthouse team.
- [x] Post a message in the #cms-lighthouse channel in Slack, with an @mention to a Lighthouse team member.
- [x] Add the "Awaiting CSV" flag to the facility node with a revision log message that includes a link to this ticket.
- [x] Validate that the change has deployed by checking that the Facility Locator has been updated with the new url.
- [x] Update this ticket with a comment that the CSV change has been deployed.
- [x] Remove the "Awaiting CSV" flag to the facility node with a revision log message that includes a link to this ticket.

#### URL change example (update with actual ID and URL)
| Facility API ID  |  Full VA.gov URL |
| ---  |  --- |
| vha_573QG | https://www.va.gov/north-florida-health-care/locations/jacksonville-north-va-clinic/|

**Comment by TroyCMSSupport** [comment]
@omahane @ian-sears @jilladams  - This is ready for URL Redirect - Facility name has already changed

**Comment by jilladams** [comment]
The destination URL 404s: https://www.va.gov/north-florida-health-care/locations/jacksonville-north-va-clinic/

The Drupal node for that URL doesn't exist: https://prod.cms.va.gov/north-florida-health-care/locations/jacksonville-north-va-clinic/

The live page for Jacksonville North VA clinic is: https://www.va.gov/north-florida-health-care/locations/jacksonville-southpoint-va-clinic/ with North in the H1

The URL alias is set to /north-florida-health-care/locations/jacksonville-southpoint-va-clinic in the Drupal node: https://prod.cms.va.gov/node/1581/edit

Do we need to actually update the URL alias, before publishing a devops redirect?

**Comment by omahane** [comment]
The redirect has been deployed.

**Comment by jilladams** [comment]
@omahane noting, when I click the old URL https://www.va.gov/north-florida-health-care/locations/jacksonville-southpoint-va-clinic/, I get a 404 not a redirect. True on the Tulare one too. I do see the deploy today contained your commits, and went out 4 hours ago - should definitely be working by now.

**Comment by omahane** [comment]
It's working now. This is a timing issue one way or another. Either the redirect goes first and deploys a URL that doesn't exist or we save the content and the release goes out with a link that doesn't exist. We typically do the former.

**Comment by TroyCMSSupport** [comment]
Thank you @omahane @jilladams @ian-sears  - I have confirmed the redirect, VA.gov locator, and Locations section of the main facility - all point to the correct / published page.

**Comment by omahane** [comment]
I had to reopen this because we have a canonical URL request out there: https://dsva.slack.com/archives/C02BTJTDFTN/p1721669125978809?thread_ts=1721421342.650609&cid=C02BTJTDFTN

**Comment by omahane** [comment]
CSV has been deployed, per Slack:
https://dsva.slack.com/archives/C02BTJTDFTN/p1721421342650609

**Comment by TroyCMSSupport** [comment]
Confirmed rename is in place
