### ISSUE TITLE
[Search] Search in Find a Form and Global Search exhibiting odd behavior

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-cms#18295]
## Description
 Extract the code from [V1 & 3 Components] Implement available components for Global Search Results #17176 in order to fix the undesirable search behavior (details to be entered here by Fran). See Steps to Reproduce and screenshots below.

### Steps to Reproduce

1. I searched for 10-10, and result displayed.
2. I then clicked in the search field to search for something else, backspacing to delete the 10-10, and an error message displayed that my search didn't go through.
3. I put the cursor back in the search field and started typing request, but the after entering just the r, the error message disappeared, the search field jumped up, and the cursor was no longer in it. I had to place my cursor back int he field to then enter my next search term.

### Screenshots
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/147188767/7b468605-6a74-435c-aca3-72be91b4ca45)

![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/147188767/24a48083-1aa2-452a-8103-7f1943fbff27)

## Acceptance criteria

- [ ] User is able to delete a previous search term without encountering the error message that their search didn't go through
- [ ] When user starts entering a new search term after deleting the previous search term, they are able to enter the entire search string in one go.

**Comment by FranECross** [comment]
@randimays Here's the ticket we chatted about this morning.

**Comment by FranECross** [comment]
@randimays Is this ticket okay to pull into Sprint 6?

**Comment by chriskim2311** [comment]
Pulling this in to work on this sprint

**Comment by randimays** [comment]
@chriskim2311 Here's the PR for Global search web component stuff: https://github.com/department-of-veterans-affairs/vets-website/pull/28812 I believe the fix is in this branch. If you're able to pull in some of this code (selfishly to avoid big merge conflicts for me later) I'd appreciate it!

**Comment by chriskim2311** [comment]
@randimays Definitely! I did take a look and updated the util function and naming with your changes yesterday. But will move it to the new file like you have in your changes.

**Comment by chriskim2311** [comment]
Code changes are live on prod no longer encountering the search message error.
