### ISSUE TITLE
New VAMC Facility: Langley VA Clinic - Published

### ISSUE THREAD

**Issue by TroyCMSSupport** [department-of-veterans-affairs/va.gov-cms#18296]
## Intake
- [x] What triggered this runbook? (Flag in CMS, Help desk ticket, Product team, VHA Digital Media)
Trigger: **Flag in CMS**

- [x] Link to associated help desk ticket (if applicable)
Help desk ticket: [Helpdesk link](https://va-gov.atlassian.net/browse/VAHELP-7589)

- [x] Name of submitter (if applicable)
Submitter: @TroyCMSSupport 

- [x] If the submitter is an editor, send them links to any relevate KB articles for the VAMC Facility product.
KB articles: https://prod.cms.va.gov/help/vamc/about-locations-content-for-vamcs/how-do-i-add-a-facility-to-my-health-care-system 

- [x] Link to facility in production:
Facility CMS link: [CMS Link](https://prod.cms.va.gov/locations/langley-va-clinic)
Facility API ID:  vha_590QD

### New VAMC Facility
Please refer to the Knowledge Base article titled "How do I add a facility to my health care system?" for more information: https://prod.cms.va.gov/help/vamc/about-locations-content-for-vamcs/how-do-i-add-a-facility-to-my-health-care-system

#### CMS help desk steps
**Note: If the help desk is waiting on information from the facility staff or editor, add the "Awaiting editor" flag to the facility with a log message that includes a link to this ticket. Remove the flag when the ticket is ready to be worked by the Facilities team. Be sure to preserve the current moderation state of the node when adding or removing the flag.**
- [x] 1. Become aware that the new facility is now on the Facility API (typically, via a Flag, but this may come in as a helpdesk ticket).
- [x] 2. If the editor has followed the steps from the above Knowledge Base article and included which section and VAMC the facility belongs to (i.e. VA Pittsburgh), great! **Proceed to step 3.** If not, please check with the editor or VHA digital media regarding what section and VAMC it belongs to.
- [x] 3. Updates the Section (default is "VAMC facilities", but it should be a VAMC system in a VISN) and VAMC system field accordingly.
- [x] 4. Communicate with editor (cc VHA Digital Media) to give them go-ahead to complete the content, with this [KB article](https://prod.cms.va.gov/help/vamc/about-locations-content-for-vamcs/how-do-i-add-a-facility-to-my-health-care-system). (See sample notification email below)

<details><summary>Email template </summary>

```

Hello! You should now be able to edit the draft page for this facility, located at [LINK TO NEW FACILITY DRAFT PAGE ON PROD]

Important: Please make sure that all relevant steps listed within the “How do I add a facility to my health care system?” Knowledge Base article have been completed: https://prod.cms.va.gov/help/vamc/about-locations-content-for-vamcs/how-do-i-add-a-facility-to-my-health-care-system

Once finished, please save this page (and all related VAMC Facility Health Service pages) in the moderation state “Draft." Please do not save them as “Published.”

Please let us know when your draft content is complete, so that we can wrap up the technical process from our end before publishing the new facility to VA.gov. Thanks!

```

</details>

- [x] 5. Create a [URL change request](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/new?assignees=&template=runbook-facility-url-change.md&title=URL+Change+for%3A+%3Cinsert+facility+name%3E), changing the entry from the old facility URL to the new facility URL. (**Note: The URL change request ticket blocks the completion of this ticket.**)

[URL Change Request](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18297)

- [x] 6. When editor has prepared content and let help desk know, reassign this issue to appropriate CMS engineer on Product Support team, for bulk publishing.

#### CMS engineer steps
- [x] 7. CMS engineer executes the steps of the URL change request ticket from step 5 above.

(Redirects deploy daily except Friday at 10am ET, or by requesting OOB deploy (of the revproxy job to prod) in #vfs-platform-support. Coordinate the items below and canonical URL change after URL change ticket is merged, deployed, and verified in prod.)

#### Drupal Admin steps (CMS Engineer or Help desk)
_Help desk will complete these steps or escalate to request help from CMS engineering._
- [x] 8. Drupal Admin bulk publishes nodes and facility.
- [x] 9. Drupal Admin edit facility node and remove `New facility` flag and save node.
- [x] 10. Let Help desk know this has been done, if not done by Help desk.

#### CMS Help desk (wrap up)
- [x] 11. Notify editor and any other stakeholders.

**Comment by omahane** [comment]
@TroyCMSSupport Do we know what the timeline is for this? I see there's still work to be done on the [facility node](https://prod.cms.va.gov/hampton-health-care/locations/langley-va-clinic): 
![langley-va-clinic](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/766573/732cd49a-e49b-4a43-b336-3f51572c46b2)

**Comment by ian-sears** [comment]
Thank you, @omahane for this update. We've reached out to the editor this morning (providing him the examples of what needs to be done on their end for us to process on our end. We can update here once the Editor replies with a timeline (or) completes their end so we can progress.
@TroyCMSSupport FYSA [VAHELP-7589](https://va-gov.atlassian.net/browse/VAHELP-7589) Waiting for Customer

**Comment by omahane** [comment]
@ian-sears 
The editor published the facility, which is not ideal. There's no services, still, despite the helpful meta description, which the editor changed:

![Screenshot 2024-06-26 at 9 18 22 AM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/766573/63f334bd-2f2a-4a9e-9eba-0a4c76cf06ae)

The typical meta description reads as follows:
"Get address and hours, parking and transportation information, and health services offered at Hampton VA Medical Center", as it reads on a facility in the same system.

@mmiddaugh I don't know how you feel about a facility being published that doesn't have services for it, so we can keep this up and ask again for the editor to create the services or unpublish it until they are up. 

In the meantime, I will alphabetize the listing in the menu:
![Screenshot 2024-06-26 at 9 26 01 AM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/766573/86071fdd-9af4-4e66-a950-7a85587efffa)

**Comment by mmiddaugh** [comment]
@omahane @TroyCMSSupport @ian-sears
Since the page is already published and the clinic has been open for almost two months, let's keep it published so Veterans and others looking for services in their area can find it. Please add VHA DM to the JIRA issue to increase visibility and I'll add it to their list of editors who need support.

**Comment by TroyCMSSupport** [comment]
@mmiddaugh @omahane @jilladams @ian-sears 

I did reach out again to the Editor and cc: d VHA DM -- I requested the following: 
Thank you for removing the link in the Meta section of the page.

I would like to suggest two very important items needed to complete this page:

1 - Add to the Meta section something to the effect of “Get address and hours, parking and transportation information, and health services offered at Hampton VA Medical Center.”

2 - Please add Facility health services to this page so that Veterans and their caretakers will know which types of services are available at that specific facility. 

I also included links to the relevant KBAs.

**Comment by omahane** [comment]
@ian-sears @TroyCMSSupport The canonical URL has been deployed, [per Adam](https://dsva.slack.com/archives/C02BTJTDFTN/p1720015713762209?thread_ts=1719340047.322509&cid=C02BTJTDFTN), and verified by me on VA.gov. I have updated the Meta description.

The only outstanding issue is missing services. Given that there's no further Facilities team work, I am unassigning myself.

**Comment by TroyCMSSupport** [comment]
@jilladams @omahane @ian-sears  - Editor contacted, page is live in production, all links work as expected, including VA.gov Locator - I have requested that services be added/confirmed - will keep the Jira ticket open until complete.
