### ISSUE TITLE
Greensboro Mobile Vet Center Breadcrumb does not match Section

### ISSUE THREAD

**Issue by TroyCMSSupport** [department-of-veterans-affairs/va.gov-cms#18305]
### What is the problem?
The Greensboro MVC is assigned to the Greensboro Vet Center. However, the breadcrumbs at the top of the page and the URL both reflect Ponce Vet Center. 

### Who is affected?
Veterans or other users may be directed to the incorrect Vet Center if following the breadcrumbs

### How urgent is the issue?
Minor

```[tasklist]
###
- [ ] The problem as described is fixed
- [ ] The repro steps result in 'expected result'
- [ ] An automated test is written to catch the problem, if appropriate
```

### How can we see the problem? (repro steps)

1. Navigate to https://prod.cms.va.gov/ponce-vet-center/ponce-mobile-vet-center
2. Notice that the Greensboro MVC is assigned to Greensboro VC, but the breadcrumbs point to Ponce VC in Puerto Rico

**Expected result:** What should be the outcome?<br />
Breadcrumbs should point to Greensboro Vet Center

**Actual result:** What currently happens?
Breadcrumbs point to Ponce Vet Center

### Is there any additional information?
Screenshots:

![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/166865749/8df404e6-3e62-4d12-bd2b-64477bf96b49)

![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/166865749/eb21bfd5-52c5-45ce-96b2-d3e3950acb82)

Log messages (please specify from where or what commands(s))
```
Log messages here
```

### Why is the problem happening and how do we fix it?

There seems to be a history of this particular facility being linked to Ponce VC -
https://va-gov.atlassian.net/browse/VAHELP-6694

Good afternoon Support Team, 

During recent review of the Ponce Vet Center website, I observed there is an MVC from Greensboro, NC on our Locations Listing.  

I reached out to Barbara Kuhn to remove it. However, she was unable to do. As per Barbara: “I think this is a different system called Lighthouse that automatically feeds into Drupal and obviously this is an error. The best approach at this point is to contact the CMS team at [support@va-gov.atlassian.net](mailto:support@va-gov.atlassian.net) and explain the situation along with the screenshot and link to that page [Locations | Ponce Vet Center | Veterans Affairs (va.gov)|https://www.va.gov/ponce-vet-center/locations/].” 

As noted above the Greensboro, NC MVC should not be affiliated with the Ponce Vet Center.

https://va-gov.atlassian.net/browse/VAHELP-7501

Michelle and CMS Support team, 

Here are two more areas where the Section assignments are strange via the breadcrumbs (similar issue to that noted for the San Juan MVC). 

The respective Greensboro and Savannah MVCs are shown in their Section for each assigned Vet Center, except when you view each link, the breadcrumbs reflect a different Vet Center.

**Comment by mmiddaugh** [comment]
@Agile6MSkinner @jilladams we need to get this one refined, please
