### ISSUE TITLE
Redirect Request for: From William V Chappell Jr Veterans' Outpatient Clinic TO Daytona Beach VA Clinic

### ISSUE THREAD

**Issue by TroyCMSSupport** [department-of-veterans-affairs/va.gov-cms#18300]
### Instructions
(Note: This issue will be used from initial request through implementation to ensure all individuals working on this are notified of status updates.  Please do not create multiple issues to track different steps.)
- [x] Notify VA stakeholders as appropriate.
- [x] Link the related facility closure / rename issue. https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18299
- [x] Create a URL redirect in the [devops](https://github.com/department-of-veterans-affairs/devops) repo in `ansible/deployment/config/revproxy-vagov/vars/redirects.yml`
- [x] Add the "Awaiting redirect" flag to the facility node with a revision log message that includes a link to this ticket, preserving the node's current moderation state.
- [x] Redirects deploy daily except Friday at 10am ET, or by requesting OOB deploy (of the revproxy job to prod) in #vfs-platform-support. After deploy, validate that the URL redirect is deployed. (Note: In the event of a facility closure or a name change,  validate that this occurs before making the Lighthouse csv changes.)
- [x] Update this ticket with a comment that the redirect has been deployed.
- [x] Remove the "Awaiting redirect" flag on the facility node with a revision log message that includes a link to this ticket, preserving the node's current moderation state.

### Implementation date
When does this request need to be live:

### Redirects
| Current URL  |  Redirect Destination or New URL |
| ---  |  --- |
| https://www.va.gov/orlando-health-care/locations/william-v-chappell-jr-veterans-outpatient-clinic/  | [(https://www.va.gov/orlando-health-care/locations/daytona-beach-va-clinic/)](https://www.va.gov/orlando-health-care/locations/daytona-beach-va-clinic/) |

### 1. Canonical URL change

**Note: Canonical URL changes do not block the completion of the parent ticket. Once the URL redirect above has been deployed, the value to the Veteran is delivered. This ticket should be kept open until the URL change is verified, except in the case of a removal (as described below).**

### Instructions for canonical URL change
- [ ] Verify that the new URL for the facility is published and accessible on VA.gov.
- [ ] Contact Lighthouse via Slack at #cms-lighthouse channel that this facility requires a canonical link in the following format (replacing the placeholder data with the actual API Id and VA.gov URL):
  - `vha_675GB,https://www.va.gov/orlando-health-care/locations/daytona-beach-va-clinic/`
- [ ] Add the "Awaiting CSV" flag to the facility node with a revision log message that includes a link to this ticket.
- [ ] Let Help desk know this has been done, if not done by Help desk.

#### Wait (days or weeks, potentially)
- [x] After the canonical link has been added to the websites.csv and you have confirmation from Lighthouse that the CSV has been deployed, validate that the change has deployed by checking that the Facility Locator has been updated with the new url.
- [x] Update this ticket with a comment that the CSV change has been deployed.

#### URL change example (update with actual ID and URL)
| Facility API ID  |  Full VA.gov URL |
| ---  |  --- |
| vha_675GB  | https://www.va.gov/orlando-health-care/locations/daytona-beach-va-clinic/ |

**Comment by ian-sears** [comment]
The editor has updated/changed the title of the node, however this node is still only resolving at the "old" url/path.

**Comment by jilladams** [comment]
Redirect destination 404s: https://www.va.gov/orlando-health-care/locations/daytona-beach-va-clinic/
CMS node has new name in H1, but old URL: https://prod.cms.va.gov/orlando-health-care/locations/william-v-chappell-jr-veterans-outpatient-clinic/ -- needs URL alias update

**Comment by omahane** [comment]
The redirect has been deployed.

**Comment by ian-sears** [comment]
CSV shows the new url, Facility locator now pulls up the new url and correct anming. All cis complete.
Closing this as resolved.
