### ISSUE TITLE
Deprecate facilities-api V1, after LH V0 deprecation

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#18314]
From onsite: when LH V0 is deprecated, we need to also deprecate facilities-api V1. 

IIR may be able to help with this, need to check with them. 

Swagger docs need to be updated to indicate a sunset date.

**Comment by dsasser** [comment]
Discovery note:
The v0 Facilities API isn't showing up in Swagger UI, but the Facility heading is present there:
<img width="930" alt="Screenshot 2024-06-12 at 12 23 58 PM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/221539/d295bc85-2c82-4981-9705-c99587641e49">

The v1 Facilities API is showing in Swagger:
<img width="1123" alt="Screenshot 2024-06-12 at 12 24 35 PM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/221539/cc91454f-6a15-4163-9903-992a40a85c2e">

**Comment by eselkin** [comment]
@dsasser There is no v0 Facilities API endpoint (they didn't make one), they just made v1. Now we're on v2.

**Comment by jilladams** [comment]
Pinged Pete and cc'ed Michael to see if IIR may have capacity: https://dsva.slack.com/archives/C078VEZCMJS/p1718907592194749

**Comment by Agile6MSkinner** [comment]
@jilladams Any update on this RE: IIR capacity?

**Comment by eselkin** [comment]
They are currently removing the v1 Facilities_api endpoint. I've been reviewing their PRs.

**Comment by jilladams** [comment]
IIR declared victory on the deprecation in ToT this week.

Regarding Swagger docs: 
https://department-of-veterans-affairs.github.io/va-digital-services-platform-docs/api-reference/#/facilities 
* Search by https://dev-api.va.gov/v0/apidocs: Facilities shows an empty header now
* Search by https://dev-api.va.gov/v1/apidocs: Facilities shows v1 endpoints for the legacy API client. 
* Search by https://dev-api.va.gov/v2/apidocs: errors, not available

Which means our v2 endpoints for the facilities-api that we use aren't findable in swagger, right? I feel like we need to track that -- I'm gonna ticket separately. 

Closing this ticket.
