### ISSUE TITLE
[Aging Content MVP] Notification emails need to be able to limit sending to specific users/email addresses

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-cms#18311]
## Description

In order to ensure appropriate people other than the last published editor receive the aging content notification emails, we want the ability to limit sending the emails to specific users/email addresses. This will enable us to expand our use of aging content notifications to cover content not yet published that needs review, content that has been edited by someone without permissions to publish, and managers of editors who published content.

This is to ensure emails aren't sent to the 'bot' last editor, when the system makes a change.

### User story

**AS A** CAIA member, or a manager of editors
**I WANT** to receive emails alerting me that content needs to be archived, reviewed, published, or updated
**SO THAT** I can take appropriate actions.

## Acceptance criteria
- [x] Notification email will be sent only to the users/email addresses specified in the criteria for when setting up aging content notifications
- [x] Update unit tests if applicable
- [ ] Update KB article if applicable

**Comment by jilladams** [comment]
@dsasser @jv-agile6 could y'all add some detail about where we're at on this ticket for current sprint?

**Comment by dsasser** [comment]
> @dsasser @jv-agile6 could y'all add some detail about where we're at on this ticket for current sprint?

The work is [complete](https://github.com/department-of-veterans-affairs/va.gov-cms/tree/VACMS-18311-limit-aging-content-email-to-specific-users), and tests have been added and updated as necessary. I planned to go over the git commit->PR workflow with Jerry tomorrow in order to get some muscle memory going in that direction, but there aren't any flags or concerns with getting this over the line by sprint end.

**Comment by jilladams** [comment]
Deployed to prod. Poked at the config a bit https://prod.cms.va.gov/admin/config/workflow/eca/aging_content_warn_fwb/edit but I'm not certain how to verify. (We def need to get this sucker documented for future generations, somewhere. )

**Comment by FranECross** [comment]
I think that the remaining ticket "[send notifications at midnight](https://app.zenhub.com/workspaces/vagov-sitewide-product-team-6645154188a81a1f7a0a9464/issues/gh/department-of-veterans-affairs/va.gov-cms/18312)" needs to be released too before it can be tested? I have the [KB article ticket](https://app.zenhub.com/workspaces/vagov-sitewide-product-team-6645154188a81a1f7a0a9464/issues/gh/department-of-veterans-affairs/va.gov-cms/18006) assigned to me and will make a point to draft it next week and then will ask Daniel to PR review.

**Comment by dsasser** [comment]
> @jilladams I think that the remaining ticket "[send notifications at midnight](https://app.zenhub.com/workspaces/vagov-sitewide-product-team-6645154188a81a1f7a0a9464/issues/gh/department-of-veterans-affairs/va.gov-cms/18312)" needs to be released too before it can be tested? (@dsasser , is this true?I have the [KB article ticket](https://app.zenhub.com/workspaces/vagov-sitewide-product-team-6645154188a81a1f7a0a9464/issues/gh/department-of-veterans-affairs/va.gov-cms/18006) assigned to me and will make a point to draft it next week and then will ask Daniel to PR review.

@FranECross @jilladams At this time, Aging Content is deployed and enabled for FWB notifications. No other work needs to go out. Emails should start going out at midnight tonight. Apologies for the confusion, a couple tickets seem to have dropped off my board (a filtering issue on my end I'm sure), and that caused me to miss updating statuses.
