### ISSUE TITLE
[Find a Form] Amend the text in the blue info box at the top of Find a Form

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-cms#18317]
## Description
There are predatory websites/companies that are charging Veterans for software to auto-fill VA forms. 

Beth Potts and Randi Hecht are collaborating with VEO and an office within VBA that's responding to this situation, and they would like to have additional text added to the Adobe informational text in the blue info box at the top of Find a Form. 

Slack thread with request from Beth Potts [here](https://dsva.slack.com/archives/C52CL1PKQ/p1718226806133089).

The existing text is: 

**Title: Use the latest version of Acrobat Reader**
**Body**: Some VA forms may not work with older versions of Acrobat Reader. You may also need to download a new copy of the VA form. Get Acrobat Reader for free from Adobe. 

The proposed updated text is: 

**Title: Use the latest version of Acrobat Reader**
**Body**: Some VA forms may not work with older versions of Acrobat Reader. You may also need to download a new copy of the VA form. Get Acrobat Reader for free from Adobe. **Note:** You never need to pay for special software to fill out VA forms.

### User story

**AS A** Veteran, their family member, caregiver or survivor
**I WANT** to understand that I don't need special software to fill out VA forms
**SO THAT** I'm not paying money to predatory companies trying to sell me software or services.

## Acceptance criteria
- [ ] Text in the blue information box at the top of Find a Form now displays: 

**Title: Use the latest version of Acrobat Reader**
**Body**: Some VA forms may not work with older versions of Acrobat Reader. You may also need to download a new copy of the VA form. Get Acrobat Reader for free from Adobe. **Note:** You never need to pay for special software to fill out VA forms.

**Comment by FranECross** [comment]
@cmmerrill @thejordanwood Since this is such a simple review/request, I'd love if the UX review/approval of the suggested text can be done in this front-end implementation ticket instead of creating a UX only ticket. Please let me know if you'd prefer a separate one, though, and I'll spin one up! Targeting Sprint 7 06/26 to 07/09.

**Comment by thejordanwood** [comment]
@FranECross Did Beth Potts and Randi Hecht suggest this additional text? The added note sounds good to me.

**Comment by FranECross** [comment]
@thejordanwood They did. Apologies, I forgot to add the [Slack thread](https://dsva.slack.com/archives/C52CL1PKQ/p1718226806133089) in the description (I'll add it now). Thanks for the quick review!

**Comment by bethpottsVADEPO** [comment]
I took a screen shot of the alert and added the note as it should appear to save time/later clarification about the bolding of "note" and the colon! Hope that's helpful.
[image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/66026798/c515a78e-5f95-4aa9-b2fa-748ac2aab9ad)

**Comment by FranECross** [comment]
@bethpottsVADEPO Very helpful! Thanks so much for the info.

**Comment by chriskim2311** [comment]
Pulling this in to work on, Sprint 6

**Comment by chriskim2311** [comment]
@bethpottsVADEPO @FranECross This has been merged and is live on prod, closing!
<img width="774" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMzJVQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c709924588e316de826296bc2be521cb74dd8023/Find_A_VA_Form___Veterans_Affairs.png" alt="Find_A_VA_Form___Veterans_Affairs.png" />
