### ISSUE TITLE
[Aging Content MVP] Aging content email notifications should be sent at midnight

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-cms#18312]
## Description

The Aging Content emails should be sent at:

- midnight on the third day prior to expiration date
- midnight on the day of expiration

### User story

**AS A** PO/PM for Aging Content
**I WANT** emails to fire on midnight on the appropriate days noted above
**SO THAT** emails aren't sent until the end of the timeframe we are specifying for first and last notification.

## Acceptance criteria

- [ ] At midnight three days prior to expiration, the first Aging Content notification email will be sent
- [ ] At midnight on the expiration date, the first Aging Content notification email will be sent
- [ ] Update unit tests
- [ ] Update KB article

**Comment by dsasser** [comment]
@FranECross is it your understanding that, once this ticket lands, that the emails will start going out? Recall that we have intentionally turned off the workflows for now, with the original intent being that we would incrementally rollout the notifications to users--but we only have 1 or 2 published FWB for which to notify on, so perhaps that is alone its own incremental rollout?

**Comment by FranECross** [comment]
@dsasser That is my understanding (that the emails will go out, since there are only a couple of folks). I'll ping Michelle in Slack just to confirm/get final sign-off though, so there aren't any surprises. Thanks for all your hard work on this!

**Comment by dsasser** [comment]
This has been released and is enabled on prod:

<img width="1538" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGIyQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--46a221d19e6ea7bf70ff4e5370bcf18a22197ad8/Screenshot%202024-07-19%20at%201.54.48%20PM.png" alt="Screenshot 2024-07-19 at 1.54.48 PM.png" />
