### ISSUE TITLE
Repair Jenkins Disk Space Issues Caused by Ansible Archive Changes

### ISSUE THREAD

**Issue by 7hunderbird** [department-of-veterans-affairs/va.gov-cms#18316]
## User Story or Problem Statement

When we changed how we [Use Ansible's Archive Module](https://github.com/department-of-veterans-affairs/devops/pull/14429) to create an archive file it's been filling up the disk space on the jenkins servers.

As a result I've been coming in each day and killing the last server it filled up.

There are are a few things we can do to fix this, but in discovering what the root cause of the problem is we'll want to choose a solution that fits once we really unterstand 

## Acceptance Criteria
- [x] Understand which file system is running out of space
- [x] Determine options to fix
- [x] Choose an option to test
- [x] Test options to find
- [x] An automated option that changes configuration makes it so we don't have to do a morning fire-fight and delete a jenkins agent

**Comment by 7hunderbird** [comment]
Relates to https://github.com/department-of-veterans-affairs/devops/pull/14429

**Comment by 7hunderbird** [comment]
There was an error today that was odd.

- [Slack thread](https://dsva.slack.com/archives/CJT90C0UT/p1718898562804389)

```
09:49:22          ("No usable temporary directory found in %s" % dirlist))
```

I ended up replacing the Jenkins Agent (which is the same manual fix for "out of disk space").

**Comment by gracekretschmer-metrostar** [comment]
For Sprint 13: this is the highest priority for tech debt.

**Comment by 7hunderbird** [comment]
Getting a review in https://github.com/department-of-veterans-affairs/devops/pull/14486, upon review we can release to Jenkins by merging https://github.com/department-of-veterans-affairs/devops/pull/14486 and then this will be deployed.

**Comment by 7hunderbird** [comment]
Trying again with https://github.com/department-of-veterans-affairs/devops/pull/14490

**Comment by 7hunderbird** [comment]
![CleanShot 2024-06-28 at 08 09 44](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/3761/4f8be3fa-13d9-4ed4-9389-771f9c3cefcd)

This has been fixed by https://github.com/department-of-veterans-affairs/devops/pull/14490
