### ISSUE TITLE
Replace Font awesome with va-icon in remaining content-build files

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#18326]
## Background
Font Awesome is being deprecated on June 20th in favor on the new `va-icon` component. This was announced in [a slack post](https://dsva.slack.com/archives/C03R5SBELQM/p1718135591699409). There are 2 important points:
- On June 20th, eslint will error on instances where font awesome is being used, and teams will need to update to va-icon using the [provided guidance](https://design.va.gov/about/developers/using-web-components#how-to-migrate-from-font-awesome-to-va-icon).
- The eslint rule will provide a quickfix option to replace icon tags with va-icon. The icon prop will still need to be updated with the correct icon name. Use the [icon name map](https://design.va.gov/foundation/icons) to determine which v3 icon you need.

We had previously done an audit and created tickets to find where FA was currently used and would need to be replaced. However, Randi found a couple lingering files in `content-build` that were not accounted for in that original audit that will error starting June 20th.

## Description
We need to update the icons in 3 files in `content-build` to avoid eslint errors. Eli already took a very brief look at these files and commented:
- [operation_status_information.liquid](https://github.com/department-of-veterans-affairs/content-build/blob/main/src/site/includes/operation_status_information.liquid) (Fac)
  - Eli's comment: I don't think this gets used, but can update
[health_care_facility_status.drupal.liquid](https://github.com/department-of-veterans-affairs/content-build/blob/main/src/site/layouts/health_care_facility_status.drupal.liquid) (Fac)
  - Eli's comment: Needs work
[staff_profile.drupal.liquid](https://github.com/department-of-veterans-affairs/content-build/blob/2ed635080798c5ad069a2642717bf0af6b8abe51/src/site/paragraphs/staff_profile.drupal.liquid#L11) (Fac)
  - Eli's comment: not sure how to update this, does it even work, it's not an <i> tag

## Acceptance Criteria
- [x] Fontawesome icons are removed from `operation_status_information.liquid`
- [x] Fontawesome icons are removed from `health_care_facility_status.drupal.liquid`
- [x] Fontawesome class is removed from `staff_profile.drupal.liquid`
- [x] Update and run existing test(s).
- [ ] If additional tests are needed, stub a ticket to note this for future work.
- [ ] Requires review

**Comment by laflannery** [comment]
Eli found that `operation_status_information.liquid` is actually building a separate Operating status page that I don't believe we are using anymore, for example:
- Old page: https://www.va.gov/greater-los-angeles-health-care/status/
- Proper, current page: https://www.va.gov/greater-los-angeles-health-care/operating-status/
Should we put in a redirect for that older page?

**Comment by jilladams** [comment]
^ ticketed the weird old page removal

operating statuses: 
![Screenshot 2024-06-26 at 4 59 15 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/85581471/a7de2b44-acbd-4acd-8638-8fa87b154e29)

![Screenshot 2024-06-26 at 5 00 44 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/85581471/789dcbb9-9915-4d04-850c-bc94b037476d)

I can't find an example staff profile with a missing image that is published to have its own page. (Related/unrelated: why are there so many staff profiles created that don't show up anywhere in the FE afaict??) Anyways. I'm calling this good and I'll own the fire drill if staff profile icon turns out to not be working in prod.

**Comment by laflannery** [comment]
@jilladams You might be seeing the staff profiles that don't have bio pages and are only used to pull into on other pages, that would be my guess
