### ISSUE TITLE
Replace Font awesome with va-icon in remaining vets-website file

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#18327]
## Background
Font Awesome is being deprecated on June 20th in favor on the new `va-icon` component. This was announced in [a slack post](https://dsva.slack.com/archives/C03R5SBELQM/p1718135591699409). There are 2 important points:
- On June 20th, eslint will error on instances where font awesome is being used, and teams will need to update to va-icon using the [provided guidance](https://design.va.gov/about/developers/using-web-components#how-to-migrate-from-font-awesome-to-va-icon).
- The eslint rule will provide a quickfix option to replace icon tags with va-icon. The icon prop will still need to be updated with the correct icon name. Use the [icon name map](https://design.va.gov/foundation/icons) to determine which v3 icon you need.

We had previously done an audit and created tickets to find where FA was currently used and would need to be replaced. However, Randi found a lingering file in `vets-website` that was not accounted for in that original audit that will error starting June 20th.

## Description
We need to update the icons in 1 file in `vets-website` to avoid eslint errors. Eli already took a very brief look at this file and commented:
- [SearchControls.jsx](https://github.com/department-of-veterans-affairs/vets-website/blob/789ce15218ac6f54659413ef83e06e754360b006/src/applications/facility-locator/components/SearchControls.jsx#L201) (Fac) - will work on this
  - Eli's comment: will work on this, I think Max tried to update the vets-website one but there was a problem when he did

## Acceptance Criteria
- [x] Fontawesome icons are removed from `SearchControls.jsx`
- [x] Update and run existing test(s).
- [x] If additional tests are needed, stub a ticket to note this for future work.
- [x] Requires review

**Comment by jilladams** [comment]
@laflannery @eselkin I see the code change but I can't figure out how to verify in prod / what the actual icon is that should appear. Is it this x to close? 

![Screenshot 2024-06-26 at 4 34 29 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/85581471/8db7cebc-a5ac-469e-93bd-41dc9f80e5cf)

**Comment by eselkin** [comment]
Yep. It's a button but it's just the close icon in the input.

**Comment by eselkin** [comment]
The "use my location" button is an image not fontawesome by the way.

**Comment by jilladams** [comment]
CLosing!
