### ISSUE TITLE
Remove pw_ehr_cta_drupal_source_of_truth flipper

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#18335]
## Description 

The flipper `pw_ehr_cta_drupal_source_of_truth` was created during converting Cerner to use KISS data ( #8198 epic). 

When the work in that epic is complete, we need to set the FE logic to always-on regardless of this flipper, and remove the flipper itself. 

## Additional Information
This ticket is in an epic where we did work with KISS. There are remaining open tickets; can an FE person please look at the other open tickets to see if there are any repercussions to removing this.

## ACs

- [ ] ~In FE code (vets-website) update logic to always use the route that's used when flipper is on, regardless of flipper state~
- [x] In vets-api, deprecate the `pw_ehr_cta_drupal_source_of_truth` flipper
- [x] Open a Platform support request to manually update the Flipper dashboard to remove that flipper, e.g. https://dsva.slack.com/archives/CBU0KDSB1/p1706215548005939
- [x] Review https://depo-platform-documentation.scrollhelp.site/developer-docs/how-to-opt-in-to-drupal-as-the-source-of-truth-for#Howtoopt-intoDrupalasthesourceoftruthforOracleHealth-relatedappsandwidgets-HowthisdatapointismanagedbyDrupal and the references to Flipper. Use the Help and feedback link to "Suggest content changes to this page" and provide content updates that will ensure the document is accurate after this flipper removal.

**Comment by jilladams** [comment]
We need to understand before working this ticket whether removing the flipper will affect our ability to complete the remainder of the KISS-related tickets.

**Comment by FranECross** [comment]
Will refine and have in Stretch/Next Sprint if someone can get to it; not urgent at all.

**Comment by randimays** [comment]
Flipper is not used anywhere so I disabled it in both staging and prod:
- https://staging-api.va.gov/flipper/features/pw_ehr_cta_drupal_source_of_truth
- https://api.va.gov/flipper/features/pw_ehr_cta_drupal_source_of_truth

Also crossed out the vets-website AC since this won't apply.

**Comment by randimays** [comment]
This was pulled in as stretch for Sprint 10.

**Comment by randimays** [comment]
Created a ticket for Platform to update the "Drupal as source of truth" documentation: https://github.com/department-of-veterans-affairs/va.gov-team/issues/90948

**Comment by randimays** [comment]
Code has been removed from vets-api, did not exist in vets-website. [Platform request](https://dsva.slack.com/archives/CBU0KDSB1/p1724082592366179) to remove from flipper dashboards is complete.

Verified in [staging flipper admin](https://staging-api.va.gov/flipper/features) and [prod flipper admin](https://api.va.gov/flipper/features) that the flipper is removed.

Closing as complete!
