### ISSUE TITLE
Verify we can remove search_dropdown_component_enabled & remove if so

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#18336]
## Description
Old flipper, `search_dropdown_component_enabled`, "Enables typeahead 2.0 functionality". 

This can likely be removed. We need to double check usage in the code, and if it seems ok to do, update header logic to always use this code path, then remove the flipper itself. 

## ACs

- [x] In FE code (vets-website) update logic to always use the route that's used when flipper is on, regardless of flipper state
- [x] In vets-api, deprecate the `search_dropdown_component_enabled` flipper
- [ ] Open a Platform support request to manually update the Flipper dashboard to remove that flipper, e.g. https://dsva.slack.com/archives/CBU0KDSB1/p1706215548005939

**Comment by chriskim2311** [comment]
@jilladams This was a CMS feature toggle not a flipper so no platform request is needed. I think this is ready to close.

**Comment by jilladams** [comment]
@chriskim2311 ah, ok. I had assumed due to the vets-api PR rather than a va.gov-cms PR. But regardless I don't see this toggle name in flipper or CMS, so: closing!
