### ISSUE TITLE
CMS Daily Job Fails to Run

### ISSUE THREAD

**Issue by 7hunderbird** [department-of-veterans-affairs/va.gov-cms#18342]
## User Story or Problem Statement

- http://jenkins.vfs.va.gov/job/cms/job/cms-daily-0800/

The `ansible/Jenkinsfiles/cms/cms-daily-0800.groovy` in the [devops repo](https://github.com/department-of-veterans-affairs/devops) is running this command:

```
source /etc/sysconfig/httpd; PATH=$PATH:/usr/local/bin:/var/www/cms/bin task --color=false --taskfile=tasks-periodic.yml daily_0800
```

Which then calls the `docroot/modules/custom/va_gov_migrate/src/Commands/Commands.php` in the [va.gov-cms repo](https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/docroot/modules/custom/va_gov_migrate/src/Commands/Commands.php).

the error message is:

```
TypeError: array_map(): Argument #2 ($array) must be of type array, null given in array_map() (line 298 of /var/www/cms/docroot/modules/custom/va_gov_migrate/src/Commands/Commands.php).
```

I think it it has to do with the `va_gov_migrate:flag-missing-facilities` task.  Because I logged into the prod EC2 instance and tried running the `source /etc/sysconfig ...` command above. 

![CleanShot 2024-06-16 at 23 12 49@2x](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/3761/63b5f576-1698-4bdd-be2d-8b3487a2e74e)

## Steps for Implementation
- [ ] Communicate what the error is to CMS developers
- [ ] Determine what data is missing or wrong
- [ ] Fix the data
- [ ] Run the job manually on prod
- [ ] Review that the job runs automatically

## Acceptance Criteria
- [ ] The job can run again

**Comment by 7hunderbird** [comment]
This started Wednesday June 12th because we can see alerts in the `#cms-notifications` channel in DSVA slack these alerts:

![CleanShot 2024-06-18 at 10 45 25](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/3761/bbd36559-d46f-40ae-8143-d921a0f231e3)

> CMS daily task job failed. See http://jenkins.vfs.va.gov/job/cms/job/cms-daily-0800/649/ for more information on why it failed.

**Comment by 7hunderbird** [comment]
There may be some useful results in slack to check.

I used this search:

```
in:#cms-notifications "CMS daily task job failed"
```

![CleanShot 2024-06-18 at 12 28 22](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/3761/1ddfe62a-1c16-4d5e-9fb9-7c28c1e7a01a)

**Comment by gracekretschmer-metrostar** [comment]
Next step, @gracekretschmer-metrostar will reach out to sitewide teams to understand if any their changes impacted this daily job.

**Comment by gracekretschmer-metrostar** [comment]
I reached out to sitewide team and we will wait until next week, when Christian gets back to troubleshoot.

**Comment by omahane** [comment]
This should be addressed by this ticket, where the analysis of the problem was performed and with which a PR was made, approved and merged: #18380

**Comment by omahane** [comment]
The conversation about this work is in this [Slack thread](https://dsva.slack.com/archives/C0FQSS30V/p1718747644621959).

**Comment by 7hunderbird** [comment]
The daily job that runs at 8:00 AM ET ran successfully today.

Thanks @omahane for your work to resolve this.

![CleanShot 2024-06-28 at 08 01 24](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/3761/30409431-89b8-47df-827f-f2d0a360e5ab)
