### ISSUE TITLE
[Analytics] [Header] Custom GA events removal & adoption of va-link component w/analytics

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-cms#18347]
## Status
**[2024-07-15]** Closing this ticket. We won't lose any analytics by waiting for the DS team to componentize the header/footer; they will take this on when they work on the header/footer.
**[2024-07-02]** [Messaged in Slack](https://dsva.slack.com/archives/C01DBGX4P45/p1719951470104989) Micah and Carol about transferring this ticket (and one more) to them for when they work on components in the header. Added Transfer label.

## Description

The va-link component has been enhanced to provide the destination URL in its built-in analytics, and can now be used for the 'mainstream' header.

### User story

**AS A PO/PM** managing Public Websites products & features
**I WANT** to (where appropriate) adopt the 'action link' va-link component, its baked-in analytics, and remove the custom GA events
**SO THAT** extraneous code is removed and only the events needed will be triggered.

## Acceptance criteria

- [ ] **Element with custom events:*When the desktop header is loaded and a Benefits Hub Detail Page is clicked* 
  - [ ] Example page:https://www.va.gov/
  - [ ] Event name:nav-header-link
    - [ ] convert to va-link? Yes
    - [ ] enable DST analytics? Yes
    - [ ] remove custom code? Yes

- [ ] **Element with custom events:*When the desktop header is loaded and a column three link is clicked ("VA Benefits and Health Care" -> "Health Care" -> "Coronavirus FAQs")* 
  - [ ] Example page:https://www.va.gov/
  - [ ] Event name:nav-hub-containers
    - [ ] convert to va-link? Yes
    - [ ] enable DST analytics? Yes
    - [ ] remove custom code? Yes

- [ ] **Element with custom events:* Veterans Crisis Line modal button
  - [ ] Example page:https://www.va.gov/
  - [ ] Event name:nav-crisis-header
    - [ ] convert to va-button? Yes
    - [ ] enable DST analytics? Yes
    - [ ] remove custom code? Yes

**Comment by FranECross** [comment]
@laflannery @randimays to async to determine if the link will turn purple, which we don't want. We might no op this!

**Comment by randimays** [comment]
@FranECross @laflannery This ticket does not include white links. It's for links in the mega menu, so we shouldn't have any issues with purple links here (in fact all the mega menu links are hardcoded to be blue in any state). @FranECross Do we have a ticket for removing custom GA events on the homepage? That would be the work concerning white links (which I've started a thread with DST about here: https://dsva.slack.com/archives/C01DBGX4P45/p1718741463008769).

Also: we cannot convert these to va-links until after the injected header/footer code split is merged in (so we can time this ticket appropriately).

**Comment by jilladams** [comment]
@randimays @chriskim2311  FYI: per Michelle, moving this to top of Ready column: 
> Per Dave Conlon, the risk of not doing the Analytics issues discussed during planning this morning is the loss of data following the GA4 migration on 7/1. We deprioritized this work during planning due to the risk for double work but sounds we'll have to take that chance. 
> can we add these relatively small issues to the sprint and/or top of the Ready column to be picked up when sprint commitments are complete?

**Comment by randimays** [comment]
Adding a note here that we shouldn't pick this up until injected H/F code split has been merged. We won't be able to adopt the web components into the header until then.

**Comment by FranECross** [comment]
[Messaged in Slack](https://dsva.slack.com/archives/C01DBGX4P45/p1719951470104989) Micah and Carol about transferring this ticket (and one more) to them for when they work on components in the header.

**Comment by randimays** [comment]
@FranECross Should this ticket be in **Ready** or are we transferring this to DST?

**Comment by FranECross** [comment]
@randimays Good point. Since we won't lose any analytics data by waiting, I'll move it to Admin or  Backlog and mark blocked, and will update the status that it'll be transferred to DST. Thanks for the ping!
