### ISSUE TITLE
[Analytics] [Find a Form] Custom GA events removal & adoption of "action link" va-link component w/analytics

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-cms#18346]
## Description

The 'action link' va-link component is being enhanced (and will be available soon) to provide the destination URL in its built in analytics, and when released, can be used for Find a Form, allowing us to remove custom GA code.

### User story

**AS A PO/PM** managing Find a Form
**I WANT** to (where appropriate) adopt the 'action link' va-link component, its baked-in analytics, and remove the custom GA events
**SO THAT** extraneous code is removed and only the events needed will be triggered.

## Acceptance criteria

- [ ] **Element with custom events:*"Go to the online tool" link* 
  - [ ] Example page:https://www.va.gov/find-forms/about-form-21-526ez/
  - [ ] Event name: cta-primary-button-click
    - [ ] convert to va-link? Yes
    - [ ] enable DST analytics? Yes
    - [ ] remove custom code? Yes

**Comment by chriskim2311** [comment]
Pulling this ticket in to work on Sprint 6

**Comment by chriskim2311** [comment]
In PR and approved, blocked due to content-build PR blocking other PRs. Will merge tomorrow.

**Comment by jilladams** [comment]
Now merged and needs to be verified. Not sure how we're doing that, so gonna let Fran weigh in when she's back.

**Comment by chriskim2311** [comment]
Verified HTML markup of new component and verified analytics flowing

<img width="1845" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK0NiQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a0f99771e0bd4f2f6b63bb4204847083a01876cd/About_VA_Form_21-526EZ___Veterans_Affairs.png" alt="About_VA_Form_21-526EZ___Veterans_Affairs.png" />
