### ISSUE TITLE
New Vet Center Facility: Leesburg Outstation

### ISSUE THREAD

**Issue by TroyCMSSupport** [department-of-veterans-affairs/va.gov-cms#18355]
## Description
Use this runbook if: a Vet Centers, Mobile Vet Centers, Vet Center Outstations is flagged as New, OR if an existing facility is flagged as New with a new Facility API ID. (This may happen  if a Vet Center moves districts, or a Mobile Vet Center is reallocated to a different Vet Center.)

## Intake
- [x] What triggered this runbook? (Flag in CMS, Help desk ticket, Product team, VHA Digital Media)
Trigger: **Flag in CMS**

- [x] Link to associated help desk ticket (if applicable)
Help desk ticket: [Helpdesk Ticket 7720](https://va-gov.atlassian.net/jira/servicedesk/projects/VAHELP/queues/custom/12/VAHELP-7720)

- [x] Name of submitter (if applicable)
Submitter: @TroyCMSSupport 

- [x] If the submitter is an editor, send them links to any relevant KB articles for the Vet Center product.
KB articles: <insert_kb_article_links>

- [x] Link to facility in production:
Facility CMS link: [Facility link](https://prod.cms.va.gov/leesburg-outstation)
Facility API ID: **vc_2241** -- This ID was incorrect for outstations, needs to be an OS ID.

UPDATE 8/30/2024:
Facility CMS link: [Facility link](https://prod.cms.va.gov/martinsburg-vet-center/leesburg-vet-center-outstation)
Facility API ID: **vc_2241OS** -- We got this corrected with RCS. It is now a correct Facility ID for Outstations.

### New Vet Center
[@TODO: KB ARTICLE FOR ADDING VET CENTERS - SEE runbook-vamc-facility-new]

#### CMS help desk steps
**Note: If the help desk is waiting on information from the facility staff or editor, add the `Awaiting editor` flag to the facility** with a log message that includes a link to this ticket. Remove the flag when the ticket is ready to be worked by the Facilities team. **Be sure to preserve the current moderation state of the node when adding or removing the flag.**

**If a Outstation:**
- [x] Confirm what Vet Center it belongs to, and set the "Main Vet Center location" field. The parent location may be derived by the Facility ID.
- [x] Contact the Vet Center editor to remind them to (1) add a photo of the Outstation and then they can publish when ready
- [x] Consider: Following up with Barb/RCS Central office to be sure that she's aware that the Outstation is in-flight

**Drupal Admin steps**
- [x] 8. Bulk publish the nodes and facility.
- [x] 9. Edit the facility node: remove the `New facility` and `Awaiting editor` flags, save the node.
- [x] 10. Let Help desk know this has been done.

#### CMS Help desk (wrap up)
- [x] 11. Upgrade the Vet Center Director and Outreach Specialist accounts to the publisher role for that Vet Center.
- [x] 12. Notify editor and any other stakeholders.

**Comment by mmiddaugh** [comment]
@agile6MSkinner this one should be pulled into the next sprint if possible 
Expecting a new name to come through VAST (Leesburg Vet Center Outstation)
This location is currently free-range and needs to have a section assigned

**Comment by jilladams** [comment]
The CSV step to add the Facility url to the LH CSV is not represented in this runbook and needs to be added.

**Comment by jilladams** [comment]
The API ID is incorrect here. the `vc_` should be `os_`. @mmiddaugh to follow up with RCS.

**Comment by mmiddaugh** [comment]
RCS will follow up to ensure name and facility ID are updated. Until then, marking this as blocked.

**Comment by jilladams** [comment]
Same on this one, noting: all of the steps in this runbook can be carried out by Helpdesk who are also Drupal Admins. We shouldn't need Facilities team work here, but Helpdesk is welcome to ask for support from us as needed, @TroyCMSSupport @ian-sears , once Michelle has the updated API ID from RCS.

**Comment by ian-sears** [comment]
@mmiddaugh We at the CMS HD will carry this out once the updated API ID is resolved from RCS.
The CMS page, as it sits currently, has Alaska set as its "STATE". **This should be Virginia** (zip code 20175). Just highlighting this in case any API information can be corrected at the same time.

**Comment by ian-sears** [comment]
@mmiddaugh @Agile6MSkinner @jilladams CMS Help Desk following up here on this Blocked facility change.
The situation:
The existing, LIVE in the CMS, CAP
[Martinsburg Vet Center - Leesburg VA Community Access Point](https://prod.cms.va.gov/martinsburg-vet-center/community-access-point/martinsburg-vet-center-leesburg-va-community-access-point)
https://prod.cms.va.gov/martinsburg-vet-center/community-access-point/martinsburg-vet-center-leesburg-va-community-access-point

is becoming:
[Leesburg Outstation](https://prod.cms.va.gov/leesburg-outstation)
https://prod.cms.va.gov/leesburg-outstation
Still in Draft with the incorrect Facility API ID for an Outstation.

So this is why we received the Leesburg Outstation as a New Facility in Flagged Facilites.

However, the Facility API ID for this is currently (still) vc_2241
The API ID is incorrect here - we're expecting an ID which is something like vc_2241OS
@mmiddaugh was following up with RCS June 26.
[Leesburg Outstation](https://prod.cms.va.gov/leesburg-outstation)
https://prod.cms.va.gov/leesburg-outstation

Once the Facility API ID is updated for this node, we will be able to launch this "New" Facility and Close down the Martinsville CAP.

Can we have an update to this process for Martinsville CAP becoming Leesburg Outstation. Or are we at the CMS Help Desk misundurstanding action that we should be taking?
@TroyCMSSupport  fysa (spreadsheet has been updated)

**Comment by mmiddaugh** [comment]
Leesburg Vet Center Outstation has Facility ID= vc_2241OS. You can proceed.

**Comment by ian-sears** [comment]
Awaiting Editor.
[VAHELP-7720](https://va-gov.atlassian.net/browse/VAHELP-7720) - We invited the Editor Kimber.Mdidleton@va.gov to upload the facility photograph, review for accuracy and Publish when ready. cc'd Barbara Kuhn for situational awareness.

**Comment by ian-sears** [comment]
Barbara Kuhn Published. No photo yet.
Request to have this new Outstation Facility ID has been made to #cms-lighthouse.
I think we need to do a redirect for the CAP to this.

**Comment by ian-sears** [comment]
Complete. Editor has been notified. VHADigitalMedia has been alerted to this updated facility.
Node Flags removed.
Tagging CMS Help Desk fysa @department-of-veterans-affairs/platform-cms-helpdesk
