### ISSUE TITLE
Create Process for Managing 508 Audit Results

### ISSUE THREAD

**Issue by gracekretschmer-metrostar** [department-of-veterans-affairs/va.gov-cms#18369]
## User Story or Problem Statement
The CMS team needs to create a process to effectively receive, evaluate, and fix the issues found in the 508 Office's audit.

## Description or Additional Context 
The 508 Office is doing a spot audit of the most common user flows within CMS. The CMS team has an existing backlog of accessibility issues, so the CMS team needs to create a process to integrate the findings from the 508 Office into their existing accessibility backlog. In addition, the team needs to create a process to determine which team should own fixing the issue and how to hand off the issue to that team.

## Steps for Implementation
- Understand what and how results will be provided to the CMS team from the 508 Office.
- Create a process input the results into the CMS accessibility backlog.
- Create a process to hand off accessibility issues to the appropriate team.

## Acceptance Criteria
- [x] Create a process to integrate the 508 Office's audit results for CMS into the CMS' accessibility audit backlog.
- [x] Map accessibility issue to the appropriate team that will own fixing the issue. 
- [x] All documentation around how to manage backlog is in Github and ready for feedback from stakeholders.

**Comment by srancour** [comment]
[Shared audits from forms team](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/blob/main/Accessibility/508-audits.md).

**Comment by srancour** [comment]
Met with @timcosgrove to discuss possibility of automating ticket labeling to make flow easier on intake. Tim is going to look into the 3rd party [advanced issue labeler](https://github.com/redhat-plumbers-in-action/advanced-issue-labeler) workflow that uses the [github issue parser](https://github.com/stefanbuck/github-issue-parser) workflow that could better accomplish this better than the [auto labeling](https://github.com/timcosgrove/auto-labeling/) workflow we're currently using as part of the [pull request labels](https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/.github/workflows/pull-request-labels.yml) workflow.

This is a first iterative step towards my eventual hope for this of being able to automate the entire flow by being able to drop in the document that the 508 office provides and have tickets auto created, labeled, organized into epics, placed within the correct teams project, and linked to the 508 office's tickets for tracking.

**Comment by srancour** [comment]
[Completed flow](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1720471253526/cc9496d0c2db0fdb4a631d62be166e71a5ecb613?sender=u974c6e508bd6b6d3906a8513) to review with @gracekretschmer-metrostar and @EWashb

**Comment by srancour** [comment]
[Documented in github](https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/READMES/508-office-audit.md)
