### ISSUE TITLE
Implement text wrapping in Service Location partial template

### ISSUE THREAD

**Issue by davidmpickett** [department-of-veterans-affairs/va.gov-cms#18367]
## User Story or Problem Statement
When zoomed to 400%, email addresses in Service Locations don't line wrap. 

[Example](https://web-jdujzwgvp8kmj36hcfonqejlgtq5b6st.demo.cms.va.gov/philadelphia-va-regional-benefit-office/#vba-service-item-39-)

Solution might be similar to [spotlight fix](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18126)

## Description or Additional Context 
![Screenshot 2024-06-18 at 1 22 17 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/1832a52a-dca9-408b-b07a-c56c5488748d)

![Screenshot 2024-06-20 at 12 38 51 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/bac9d825-180d-4934-8d09-7f0159fb711c)

## Steps for Implementation
Zoom to 400% and look at an email address

## Acceptance Criteria
- [x] Text is wrapped at zoom levels up to 400%
- [ ] Requires design review
- [ ] Requires accessibility review

```[tasklist]
### QA
- [ ] Applies to both VBA and VAMC
```

**Comment by Agile6MSkinner** [comment]
Verified via creating of data in tugboat by @eselkin. Did not find data in prod to accomplish verification in the wild.
