### ISSUE TITLE
Content Release is timing out in the build step

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#18362]
## User Story or Problem Statement
The Content Release workflow build step is capped at 40 minutes:  https://github.com/department-of-veterans-affairs/content-build/blob/main/.github/workflows/content-release.yml#L209

Time for the build step is exceeding 40 minutes at times. We need to raise the ceiling as a short-term measure to allow Content Release to continue.

## Description or Additional Context 
https://dsva.slack.com/archives/C0FQSS30V/p1718901368011679

## Steps for Implementation
Raise the time to 50 minutes.

## Acceptance Criteria
- [x] Build time for the build step is 50 minutes.

**Comment by gracekretschmer-metrostar** [comment]
@timcosgrove I am confirming that this has been completed, correct?
