### ISSUE TITLE
VAMC Facility closed: Medical View Lane VA Clinic

### ISSUE THREAD

**Issue by ian-sears** [department-of-veterans-affairs/va.gov-cms#18387]
## Intake
- [x] What triggered this runbook? (Flag in CMS, Help desk ticket, Product team, VHA Digital Media)
Trigger: Help desk ticket 

- [x] Link to associated JIRA help desk ticket (if applicable)
Help desk ticket: [VAHELP-7599](https://va-gov.atlassian.net/browse/VAHELP-7599)

- [x] Name of submitter (if applicable)
Submitter: Stephen.Westerfield@va.gov

- [x] If the submitter is an editor, send them a link to the KB article: [How to archive a closed facility](https://prod.cms.va.gov/help/vamc/about-locations-content-for-vamcs/how-to-archive-a-closed-facility)

- [x] Link to facility in production:
Facility CMS link: [(https://prod.cms.va.gov/tampa-health-care/locations/medical-view-lane-va-clinic](https://prod.cms.va.gov/tampa-health-care/locations/medical-view-lane-va-clinic)
Facility API ID: vha_673QI

#### CMS Help desk steps
**Note: If the help desk is waiting on information from the facility staff or editor, add the "Awaiting editor" flag to the facility with a log message that includes a link to this ticket. Remove the flag when the ticket is ready to be worked by the Facilities team. Be sure to preserve the current moderation state of the node when adding or removing the flag.**
- [x] 1. CMS team becomes aware that the facility is no longer on the Facility API.
- [x] 2. If we don't already have context (say, via a HD ticket submitted by an editor), check with editor to find out more about the status of the facility
- [x] 3. Find out if there are any services or events tied to the facility to be archived that should be moved to a new facility or otherwise preserved and updated

- [x] 4. Are any of the services or upcoming events for the facility to be closed moving to a different facility?
Editor has removed all the Health Services and prepared the page for Archival.
  - [- ] 4a. If so, note the facility picking up the services and events here: None.
  - [- ] 4b. If so, note the services and events here: None.
- [x] 5. Create a [URL change](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/new?assignees=&template=runbook-facility-url-change.md&title=URL+Change+for%3A+%3Cinsert+facility+name%3E) to redirect the from the URL of the facility to be closed to the URL of its parent system and to remove the old canonical link.

#18390 18390

#### CMS Engineer steps
- [x] 6. Execute the steps of the URL change request ticket from step 5 above.

(Redirects deploy daily except Friday at 10am ET, or by requesting OOB deploy (of the revproxy job to prod) in #vfs-platform-support. Coordinate the items below and canonical URL change after URL change ticket is merged, deployed, and verified in prod.)

#### Drupal Admin steps (CMS Engineer or Helpdesk)
_Help desk will complete these steps or escalate to request help from CMS engineering._
- [x] 7. When redirect has been deployed, make these changes. Practice first on staging or a demo environment.
  - [x] 7a. Drupal Admin bulk moves any content identified **4b** to new facility **4a**.
  - [x] 7b. Drupal Admin edits the facility node, removes flag `Removed from source`, add a revision log that explains the change, with a link to github issue, and change moderation state to archive. (Note: any remaining health services, non-clinical services and events for the given facility will be archived automatically when these changes are saved.)
  - [x] 7c. Drupal Admin finds the menu for the system https://prod.cms.va.gov/admin/structure/menu and deletes the menu item for the facility being closed.

#### CMS Help desk (wrap up)
- [x] 8. Help desk notifies editor and any other stakeholders.

[VAHELP-7599]: https://va-gov.atlassian.net/browse/VAHELP-7599?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by jilladams** [comment]
> Editor asks for this to be Archived VAHELP-7599. Directed Editor to request via VAST. Awaiting Editor/VAST. This Facility is closed as per the Editor. CMS Help Desk

https://va-gov.atlassian.net/browse/VAHELP-7599
> According to VAHELP-7715: RE: [EXTERNAL] VAHELP-7599 Archive Facility_Medical View Lane_Tampa Health Services, VAST has been made aware of the facility closure (but not yet flagged as ‘closed’).

**Comment by ian-sears** [comment]
Redirect has been made. https://www.va.gov/find-locations/facility/vha_673QI is removed. Request to remove vha_673QI has been made in Slack. URL change GH ticket is closed. Page is archived and Editor has been notified.
Closing this as complete.
