### ISSUE TITLE
Facility Locator search for Dental and Mental Health services returns error

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#18382]
## User Story or Problem Statement
Reported by VHA DM: 
Facility Locator search for Dental and Mental Health services returns an error: 
![Screenshot 2024-06-24 at 9 06 44 AM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/85581471/b3a99bc7-4361-4278-9520-31aefe5087e2)

## Description or Additional Context 
We believe this is an artifact of the Lighthouse V0 > V1 migration where service IDs changed for these 2 services: 
* The /cms-overlay endpoint that pushes the services to us is "version agnostic" so we can accept payloads with either id format, but the front-door endpoints are version specific so the V1 request endpoints only accept V1 service ids.Based on those two being the only services that aren't working I would suspect the requests are using the old V0 id format.
* API request for dental (V1 id for "Dental" service) returns 247 results.API request for dentalServices (V0 id for "Dental" service) returns an error specifying the id is invalid.

## Acceptance Criteria
- [x] Mental health and dental services correctly return results in the Facility Locator in production

**Comment by jilladams** [comment]
This got injected today per scrum discussion with Michelle, Michael, Eli. This will affect any work remaining in sprint that wasn't started or was in progress, mostly affecting VBA Staging Review blockers, I believe.

Eli said they'll be following up to work out where in vets-api we may be handling Dental / MH services, and need to update the related serviceID.

**Comment by eselkin** [comment]
So I'm not sure that we use the piece that processed DentalServices in vets-api. It was under a batch job. Do we know anything about the batch jobs that load data into files there? Is there any documentation on how we were handling dental services?

**Comment by eselkin** [comment]
So the service we should now be processing is Dental not DentalServices? I'm trying to get this running locally but something changed in vets-api and I had to reinstall ruby and now it's not running.

**Comment by eselkin** [comment]
Ok, it's just vets-website that needs to change its request. Phew... I was a little panicked that the batch job had to change.

**Comment by eselkin** [comment]
It could be vets-api needs to change for caching reasons, but to get the results back all that is needed is to update vets-website

**Comment by jilladams** [comment]
Merged, but missed today's daily deploy. Asked Michelle and VHA DM about requesting an Out of Band deployment, and they opted **not** to request OOB since the usage of the Services dropdown is low (2% for MH, 3% for Dental) vs. most folks using the default All Services in dropdown (~85% of searches). 

This will roll out with tomorrow's vets-website deploy.

**Comment by Agile6MSkinner** [comment]
Verified in prod:
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/167716994/59164167-d7a8-4af8-a4a6-1ee71bdd312a)
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/167716994/fb62361f-26b4-4efa-a9cf-8a657508340c)
