### ISSUE TITLE
Design revisions: Vet Center 2.0 main page

### ISSUE THREAD

**Issue by aklausmeier** [department-of-veterans-affairs/va.gov-cms#18389]
## Description 

Design revisions based on Vet Center office hours stakeholder/SME feedback. 

## Design 
[Vet Center Figma file](https://www.figma.com/file/EVd3q06ukAbVS61Q8MwRAT/Vet-Centers?type=design&node-id=1%3A900&mode=design&t=Wqtm0fJVxdIkoObB-1)

## Design revisions

- [x] Revisit location of FAQs 
- [x] Consider full width image instead of logo to communicate a "warm, welcoming, nonclinical front door," stakeholder is not sure we should move forward with logo
- [x] 24/7 after hours phone label consider how to better set context and expectations for this phone number
- [x] Show what an operating status would look like in a design
- [x] Move back to "referrals" language over "recommendation" in heading

## Acceptance criteria

- [x] Design revisions in Figma
- [x] Review with UX Lead, Product, and Accessibility
- [x] Final design with annotations sent to VA UX Lead for final sign off

**Comment by davidmpickett** [comment]
Notes from call with @thejordanwood @aklausmeier 

**Header image**
- Warm welcoming image 
- Amanda has access to an image repository
- Will logo still be present if we have image?

**Blue Box**
- Remove "mental health", focus on counseling and social services
- Remove bullet points about referrals
- Jump link? Probably not
- Alternative therapies "equine" etc.

**After hours call center**
- Ask Michelle what happens when they call
- Stakeholders don't like "call center"
- Alert vs additional phone number

** Vet Centers different than medical clinic**
- Move it back down
- Domo analytics - people scroll down today
- 2nd most interacted component? So maybe the bottom isn't correct placement
- Between **prepare for your visit** and **in the spotlight**?

**Recommendation services**
- Stakeholders want the word referral

**Referral link**
- Multiple possible actions

**Outstations**
- Ideally all would have their own page

**Mobile vet centers**
- Don't want to list as Locations period

**Comment by jilladams** [comment]
@thejordanwood I went ahead and assigned this to you. Could you estimate points, if you feel it's at the point where it's ready for you to work?

**Comment by thejordanwood** [comment]
@jilladams We're still waiting on more stakeholder feedback. I can add points whenever that comes in!

**Comment by davidmpickett** [comment]
Moving this out of Current Sprint since it is blocked.

**Comment by thejordanwood** [comment]
We decided in UX sync on 7/18 that we're going to move forward with the feedback we received from stakeholders in the initial meeting on 6/24. This is ready to work on.

**Comment by jilladams** [comment]
Before Dave's PTO, an ask to help check in with CAIA about needed copy revisions in the blue box.

**Comment by aklausmeier** [comment]
Let's prioritize getting revision request for summary box to CAIA.

**Comment by Agile6MSkinner** [comment]
The "full length image" feature is something we've begun to talk about in prod/eng. Can we focus on that?

**Comment by aklausmeier** [comment]
@Agile6MSkinner a full width image would be very similar to VA health systems https://www.va.gov/eastern-colorado-health-care/

**Comment by aklausmeier** [comment]
@thejordanwood reminder from our past selves...

Image direction from previous [Slack conversation](https://dsva.slack.com/archives/C06S9DADEUB/p1719262954606519): 

> The decorative image at the top of the health system page is the area Jessica was referencing (i.e. Pittsburgh) - what if it wasn't a facility image? Could it be a Veteran image, something that that reflects counseling/community/services?

**Comment by jilladams** [comment]
From Michelle today [in Slack](https://dsva.slack.com/archives/C0FQSS30V/p1721853255169089?thread_ts=1721851644.633729&cid=C0FQSS30V): "I think it is unlikely that RCS will support regional/local images unless there is a defined library for them to pull from" 

I think we are getting a little bit of competing direction here -- adding to scrum agenda for tomorrow.

**Comment by jilladams** [comment]
Slack discussion from scrum: https://dsva.slack.com/archives/C079GFKN50D/p1721922823932459?thread_ts=1721857395.422269&cid=C079GFKN50D

- RCS does want a decorative image at the top of the page.
  - Intent is still national centralized content.
  - Not regional / local.
- So far: it has not been suggested to RCS that we could support more than one image.

**Comment by thejordanwood** [comment]
Updating here that Amanda has made revisions to the summary box content based on feedback from stakeholders and submitted that in the [CAIA intake ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/83961) for them to review.

**Comment by thejordanwood** [comment]
Updates:

- @aklausmeier has reviewed and I updated the design based on her feedback. 
- @laflannery I believe you're next in line to review. Changes are in [the Figma file](https://www.figma.com/design/EVd3q06ukAbVS61Q8MwRAT/Vet-Centers?node-id=21-2&t=2M86uZ9mLvMJqvFp-1) under the revisions section. The design also shows top task links to the intake form referenced in [this design ticket](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17541).

**Comment by aklausmeier** [comment]
First pass design review complete. 

After Laura's review, the Figma file will then need to be organized so final design is on one page with finalized desktop and mobile mockups and previous/discarded options moved out of the working file.

We will need FE annotations and an updated stakeholder presentation file for Michelle to share with RCS.

**Comment by aklausmeier** [comment]
Let's move forward with image "option 2"

**Comment by laflannery** [comment]
@thejordanwood I finished my review. No real issues, just comments to sort of align things with current state.

I do have many thing regarding implementation so as @aklausmeier mentioned, once this is organized and ready to be annotated, let me know and I can put my notes on the proper file

**Comment by aklausmeier** [comment]
I'd like a final design review once file is organized and annotated.

**Comment by thejordanwood** [comment]
Checking in:

- @davidmpickett Have you had a chance to review the final design?
- @laflannery Are we finished with annotations? If so, this is ready for Amanda's final review.

**Comment by laflannery** [comment]
Yes I'm done, no more for me!

**Comment by davidmpickett** [comment]
I have some updates/feedback about the navigation sidebar, but that wasn't a specific focus for this ticket, so that can probably wait until we are finalizing design for other pages.

**Comment by davidmpickett** [comment]
Clarifying question. The design includes a tablet width at the new 640 px breakpoint, but there are no annotations the tablet scale. I assume that it's because we still need to finalize additional pages at that breakpoint before getting engineers started on that work.

**Comment by davidmpickett** [comment]
My review is complete

**Comment by thejordanwood** [comment]
@davidmpickett Correct about the 640px mockup. I think we need to look at other pages before getting engineers started on this.

**Comment by jilladams** [comment]
https://dsva.slack.com/archives/C06S9DADEUB/p1723050880800519
 Vet Center 2.0 - stakeholder feedback

- `Top image` - moving forward with recommendation of one image used across all Vet Centers
- add a top optional `banner alert`, new to Vet Centers (like VBA)
- `Satellite/Outstations` will have the same look/template as main Vet Center
  - they have limited needs but same required services
  - may not use Events or Spotlights but Spotlight can use the one National if that is all that is available
- `Summary box` currently with CAIA for revisions, Amanda will follow up
- `Top task link` draft link text will need review once we have link, ETA mid Sept
  - Stakeholder suggested revising to "Connect with
  - once we see what this link/form is we could recommend different wording

**Comment by thejordanwood** [comment]
@aklausmeier I've added the banners to the final mockups in the [Vet Center Figma file](https://www.figma.com/design/EVd3q06ukAbVS61Q8MwRAT/Vet-Centers?node-id=906-8577&t=BNjMVqdvgDTwz5rO-1).

**Comment by aklausmeier** [comment]
I mentioned in a previous scrum but adding documentation here: 

The Summary box content ("mission explainer") is currently with CAIA for final revisions. I shared our copy revision request along with stakeholder feedback for CAIA to finalize in the [CAIA Slack](https://dsva.slack.com/archives/C01K37HRUAH/p1721919339210829) and in the [ticket comments](https://github.com/department-of-veterans-affairs/va.gov-team/issues/83961). 

cc @Agile6MSkinner @davidmpickett
