### ISSUE TITLE
Review CAIA Redirect Documentation and Answer Questions

### ISSUE THREAD

**Issue by gracekretschmer-metrostar** [department-of-veterans-affairs/va.gov-cms#18398]
## User Story or Problem Statement
As a member of the CAIA team, I need support from the CMS team to understand how their redirect process and guidance will impact the CMS platform. 

## Description or Additional Context 
The CAIA team is asking for collaboration from the CMS team as they are firming up their processes and guidance for redirect links.

## CAIA Questions
1. What are the best ways to avoid broken links? 
2. How can we find all links in Drupal? Content team currently does a content audit in Drupal but it can miss links
3. When searching for nodes, archived pages still show up as options. They may share an H1 with an Active page, so there’s a risk that a Drupal user chooses the wrong one and links to a 404 node. How do we check which ones are which? 
4. Is the CMS team able to hide archived pages in Drupal?
5. What is the risk with cloning pages for redirects and creating new nodes? What is the limit?
6. There’s a cap on published pages ([Slack thread for context](https://dsva.slack.com/archives/CDHBKAL9W/p1674162356497589))
7. Can content folks get access to the Node Usage feature? This may be a question for someone else as we know Randi Hecht has been in communication with Erica, I think

## CAIA docs
- https://docs.google.com/document/d/1oYbC_zl07cIyrTAo3rUbzaqBw2BMHKtnFovTqor2EUY/edit?usp=sharing
- https://docs.google.com/document/d/1wRcgJn7p4Cuz4cFr-WF3JlvttK5CAbenZkJM4EqBLIs/edit?usp=sharing

## Steps for Implementation
- Understand how redirects impact CMS. 
- Answer CAIA questions.
- Review the CAIA docs and provide feedback, when the documentation relates to the CMS. 

## Acceptance Criteria
- [ ] CAIA's questions are answered.
- [ ] The CMS team reviews the documentation and provides guidance when steps impact the CMS platform.

**Comment by gracekretschmer-metrostar** [comment]
Next steps with building a relationship with CAIA, have Grace and Erika meet Randi.

**Comment by gracekretschmer-metrostar** [comment]
Next steps: pull this work into the knowledge base redesign epic.

**Comment by gracekretschmer-metrostar** [comment]
Explore this task: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17714

**Comment by JakeBapple** [comment]
I have requested access to the docs (via my jbapple@metrostar.com email address). Will look into the questions and provide feedback in this ticket first, and then I will disseminate approved responses in documents where it makes sense.

**Comment by JakeBapple** [comment]
1. What are the best ways to avoid broken links?
    * USING CKEDITOR WYSIWYG
        * Highlight the text you want to link to and click the link icon
        * Find the node id of the page you want to link to You can find the node id by editing the node of the page you want to link to and look in your browser url bar for the id number. For example, if the url bar contains …/node/813/edit… the node id is 813.
        * Enter a relative url using the node id For example you would enter: /node/813.It is important that you use a relative url and not an absolute url. A relative url omits your domain address and starts with a forward slash. An absolute url contains the full page url, including https and your domain name. You should ONLY use absolute urls for external links. We suggest you configure external links to open in a new window by adding the “target=‘_blank’” attribute to your <a> elements.
    * In general, don’t use absolute pathing when you link content in the page. An example of an absolute path would be https://www.va.gov/health-care/ 
2. How can we find all links in Drupal? Content team currently does a content audit in Drupal but it can miss links
    1. Possible solution: use Xenu (with some settings found here: https://www.drupal.org/forum/support/post-installation/2012-12-17/any-way-to-have-a-listing-of-all-external-links-aka-not)
    2. Could they provide more context as to why they need to find all links and do they mean all links within content or just urls available on the site or both or neither?
3. When searching for nodes, archived pages still show up as options. They may share an H1 with an Active page, so there’s a risk that a Drupal user chooses the wrong one and links to a 404 node. How do we check which ones are which?
    1. Need clarification on where you are searching for nodes in order to determine if it’s possible to remove archived pages. Also, an example of an archived page would be helpful
4. Is the CMS team able to hide archived pages in Drupal?
    1. Need clarification on what they mean by “hide”. Is this only for search or for navigation? Are we blocking these pages? Who do they want to have access to these pages if anyone?
5. What is the risk with cloning pages for redirects and creating new nodes? What is the limit?
    1. Need clarification on what risk and limit are referring to. Cloning generates a new page with a new node id. Anything you wanted to clone from a previous page would be there. This new cloned page would not be a part of the redirect if the page it was coming from had any.
6. There’s a cap on published pages ([Slack thread for context](https://dsva.slack.com/archives/CDHBKAL9W/p1674162356497589))
    1. Cloning a page would be the same as publishing a new page.
7. Can content folks get access to the Node Usage feature? This may be a question for someone else as we know Randi Hecht has been in communication with Erica, I think
    1. Assuming you mean the Node Usage module, it may be useful to have context as to why you want access to this (it’s typically on the reports side of the admin menu).

**Comment by gracekretschmer-metrostar** [comment]
Close ticket at the end of this sprint.
