### ISSUE TITLE
URL Change for: Medical View Lane VA Clinic

### ISSUE THREAD

**Issue by ian-sears** [department-of-veterans-affairs/va.gov-cms#18390]
Parent ticket: #18387
Facility to be Archived, soonest possible. Redirect to the System's Locations page and remove Canonical URL.

### Implementation date
When does this request need to be live:
ASAP

### Instructions for URL redirect
(Note: This issue will be used from initial request through implementation to ensure all individuals working on this are notified of status updates.  Please do not create multiple issues to track different steps.)
- [x] Notify VA stakeholders as appropriate.
- [x] Link the related facility closure / rename issue.
- [x] Create a URL redirect in the [vsp-platform-revproxy](https://github.com/department-of-veterans-affairs/vsp-platform-revproxy) repo in `template-rendering/revproxy-vagov/vars/redirects.yml`
- [x] Add the "Awaiting redirect" flag to the facility node with a revision log message that includes a link to this ticket, preserving the node's current moderation state.
- [x] Redirects deploy daily except Friday at 10am ET, or by requesting OOB deploy (of the revproxy job to prod) in #vfs-platform-support. After deploy, validate that the URL redirect is deployed. (Note: In the event of a facility closure or a name change,  validate that this occurs before making the Lighthouse csv changes.)
- [x] Update this ticket with a comment that the redirect has been deployed.
- [x] Remove the "Awaiting redirect" flag on the facility node with a revision log message that includes a link to this ticket, preserving the node's current moderation state.
- [x] Notify helpdesk via comment on ticket or Slack message in #cms-support that changes are ready for review.

#### URL Redirect
| Current URL  |  Redirect Destination or New URL |
| ---  |  --- |
|  https://www.va.gov/tampa-health-care/locations/medical-view-lane-va-clinic/ | https://www.va.gov/tampa-health-care/locations/ |

### Instructions for canonical URL removal
- [x] Try to find the facility via the Facility Locator, using the Facility API ID (e.g. https://va.gov/find-locations/facility/"facility_api_id"). If it is not available, proceed.
- [ ] Update the [CSV in Lighthouse](https://github.com/department-of-veterans-affairs/lighthouse-facilities/blob/master/facilities/src/main/resources/websites.csv) removing the row with the Facility API ID.
- [ ] Create a PR in the [lighthouse-facilities repo](https://github.com/department-of-veterans-affairs/lighthouse-facilities), tagging the Lighthouse team.
- [ ] Post a message in the #cms-lighthouse channel in Slack, with an @mention to a Lighthouse team member.
**Note: there's no check to see if it's not returning anything, as it should already be not showing anything in the Facility Locator.**

#### URL removal
| Facility API ID  |  Full VA.gov URL |
| --- | --- |
| vha_673QI  |  [https://www.va.gov/tampa-health-care/locations/medical-view-lane-va-clinic/](https://www.va.gov/tampa-health-care/locations/medical-view-lane-va-clinic/)

**Comment by ian-sears** [comment]
UPDATE: Awaiting removal of Facility from VAST. Editor indicates this request was made.
Currently still listed: https://www.va.gov/find-locations/facility/vha_673QI

**Comment by ian-sears** [comment]
UPDATE: Awaiting removal of Facility from VAST. Editor indicates this request was made.
Currently still listed: https://www.va.gov/find-locations/facility/vha_673QI

**Comment by ian-sears** [comment]
Removed from Source just showed up (from VAST) in the CMS. 
Moving forward now with closure of this facility.
@TroyCMSSupport fysa VAHELP-7869

The facility ID no longere shows in the facility locator:
https://www.va.gov/find-locations/facility/vha_673QI

@omahane ok now to proceed with removal from CSV in LH and continue with this runbook.

**Comment by omahane** [comment]
The redirect has been merged: https://github.com/department-of-veterans-affairs/vsp-platform-revproxy/pull/561

**Comment by omahane** [comment]
The redirect has been deployed.

**Comment by ian-sears** [comment]
@omahane LH CSV request to remove from csv has been made
https://dsva.slack.com/archives/C02BTJTDFTN/p1724191208597359?thread_ts=1724077493.106109&cid=C02BTJTDFTN
Looking at the runbook, above, is there something we are missing prior to closing this? A Pull request?
We look forward to your advice.
