### ISSUE TITLE
PHPUnit testPostApiQueueProcessing failing after Lighthouse v0 cutoff

### ISSUE THREAD

**Issue by omahane** [department-of-veterans-affairs/va.gov-cms#18407]
## Describe the defect
testPostApiQueueProcessing is throwing an error during PHPUnit tests.

## To Reproduce
1. Locally run `ddev exec bin/phpunit --exclude-group disabled tests/phpunit/API --filter testPostApiQueueProcessing`
2. Confirm that this error is thrown:
```
1) tests\phpunit\API\PostApiQueueTest::testPostApiQueueProcessing
Error: Call to a member function getStatusCode() on int
```

## AC / Expected behavior
The PHPUnit test passes.

## Screenshots
N/A

 ## Additional context
Add any other context about the problem here. Reach out to the Product Managers to determine if it should be escalated as critical (prevents users from accomplishing their work with no known workaround and needs to be addressed within 2 business days).

**Comment by jilladams** [comment]
@mmiddaugh @Agile6MSkinner FYI, a new defect that popped up today after sprint planning, from LH V0 work. Added to sprint.

**Comment by jilladams** [comment]
Merged 2 hours ago - to verify, we just need nightly deploy, and need to know unit tests aren't failing in main tomorrow?

**Comment by omahane** [comment]
@jilladams No errors related to this issue have been reported this morning, whereas they had been the previous days. I'd say that's all the sign we're going to get at this point.
