### ISSUE TITLE
Review CMS for Usage of Font Awesome

### ISSUE THREAD

**Issue by gracekretschmer-metrostar** [department-of-veterans-affairs/va.gov-cms#18400]
## User Story or Problem Statement
The CMS team needs to understand if and where font awesome is being used within the va.gov-cms repo. 

## Description or Additional Context 
Font awesome is being deprecated, so we need to review the va.gov-cms repo to determine if font awesome is being actively used. Right now, it's been identified that there's instances where font awesome is being used, but it is unclear if font awesome is being actively used. 

## Reference Links
- https://dsva.slack.com/archives/C03R5SBELQM/p1718135591699409

## Acceptance Criteria
- [ ] An understanding if CMS is actively being using font awesome.

**Comment by gracekretschmer-metrostar** [comment]
Next steps: a list of identifying how, where, and why it is being used.

**Comment by anantais** [comment]
Good news, I think. So far it looks like everything is labeled and most of the items say "Font Awesome Free". The exceptions i have found are these three icons (which are all listed as "Font Awesome Pro").

va.gov-cms/docroot/themes/custom/vagovclaro/images/icons/000000/chevron-circle-right-solid.svg
va.gov-cms/docroot/themes/custom/vagovclaro/images/icons/004795/chevron-circle-right-solid.svg
va.gov-cms/docroot/themes/custom/vagovclaro/images/icons/2e8540/chevron-circle-right-solid.svg

I will look again in the morning with a fresh set of eyes just to make sure.

@MDomngz

**Comment by anantais** [comment]
The only other place I saw a possible issue was in components used for the social media links for offices. They maybe using icons that are not free. Pretty sure this is not our concern though.
