### ISSUE TITLE
[Discharge Upgrade Wizard] Revise review screen behavior in light of #18029

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#18405]
## notes

Update the Review screen build with changes from UX work in #18029 

[Figma design](https://www.figma.com/design/XHQAQ8ZDKKsDcXfBn5ulhh/Discharge-Upgrade-Wizard?node-id=150-5583&t=FqifRvjEldJkRBRS-0) 

```[tasklist]
### Implement conditional alert when editing a forking question
- [ ] Add expandable alert to forking question pages
- [ ] Add expandable alert to Review screen after user has completed the new question flow
- [ ] Wording and placement should match Figma file
```

```[tasklist]
### Content changes to review screen
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18697
- [ ] Add a bold summary of the question next to every answer
- [ ] Update wording of h1 per Figma
- [ ] Remove text below h1 per Figma
```

**Comment by jilladams** [comment]
@FranECross FYI that since Jordan is creating design changes in #16917, and the Review screen is already built, we created this ticket during plannign to track the fact that we need to revisit the Review screen changes.

**Comment by davidmpickett** [comment]
@FranECross FYI that we ended up talking about this a bit in UX Sync a little bit today. I updated the ticket body a little bit based on that conversation. I think you and @chriskim2311 should have everything you need to scope out the tasks around adding the conditional alert.

@thejordanwood @laflannery and I need to do a little work on finalizing the exact wording of some new content on the review screen. I put this as a separate task list.

**Comment by FranECross** [comment]
@chriskim2311 Let me know if you want to review/collaborate async, or if you prefer a meeting to review? I'm good either way.

(Thanks so much, @davidmpickett ! )

**Comment by chriskim2311** [comment]
@FranECross Thanks! Just reviewed and the tasks look good to me. Can you write up the ticket and I can point it.  Thanks!

**Comment by FranECross** [comment]
@chriskim2311 This is the engineering ticket to be pointed during refinement (unless I'm missing something). 😁

The UX ticket was 18029. Thanks!

**Comment by chriskim2311** [comment]
@FranECross Got it my mistake! Unfortunately I won't be able to make the refinement tomorrow. I added points and assigned myself to work on it

**Comment by chriskim2311** [comment]
@thejordanwood @davidmpickett Question regarding the help text on the review page. Previously we have this help text. <img width="1126" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeE5KQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--86a136db4f23c72f6ca8f6fcf4101498cec014df/How_To_Apply_For_A_Discharge_Upgrade___Veterans_Affairs.png" alt="How_To_Apply_For_A_Discharge_Upgrade___Veterans_Affairs.png" />

Should it be conditional and only show the alert when answers have changed or remove entirely?

**Comment by davidmpickett** [comment]
I'd say remove entirely. That's what Jordan's updated design shows. It doesn't appear on [first landing](https://www.figma.com/design/XHQAQ8ZDKKsDcXfBn5ulhh/Discharge-Upgrade-Wizard?node-id=379-5837&t=IEdgvtqBrtDJi86J-1) on the Review page

**Comment by thejordanwood** [comment]
@chriskim2311 I agree. You can go ahead and remove this!

**Comment by jilladams** [comment]
Capturing the logic Jordan described int his PR so that we can reference it / update it to final when we're done for product documentation purposes later: 

> We had [a Slack thread](https://dsva.slack.com/archives/C52CL1PKQ/p1721754164265219) discussing how the edit flow should operate and I'm noticing some discrepancies. The summary of this:

- IF the user arrives at a question by clicking an Edit link on the review page, both the continue and back buttons should bring the user back to the Review screen and preserve any edits the user made
- UNLESS they have changed their answer on a branching question. In that case the continue and back buttons should work as normal for the new questions.
     - EXCEPT Clicking continue on the last new question should jump the user to the review page. (Assuming there are situations where new questions are perfectly encapsulated in the middle of the flow)
     - AND Clicking back on the branching question _after changing the answer_ should take them back to the previous question in the normal flow. We don't want them going back to the review screen without answering the new questions in that case.
     - AND Clicking back on the first new question should go back to the previous question they originally chose to edit



There are active converstaions happening about how we might need to document the way this should work both in slack (https://dsva.slack.com/archives/C52CL1PKQ/p1723494965135929) and on the PR (https://github.com/department-of-veterans-affairs/vets-website/pull/31319). Once the dust settles, team can figure out if we need a separate ticket for a Mural to help with logic. 

FYSA @FranECross

**Comment by chriskim2311** [comment]
There were discussions to limit the scope of this ticket to just review screen functionality, matching figma designs and covering all accessibility requirements. 

During work on this ticket we discovered some flows missing from our mural and some complex functionality in regards to navigation from the edit page. A new ticket was created to test all flows and update navigation logic here: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18974.

**Comment by jilladams** [comment]
@chriskim2311 I saw that https://github.com/department-of-veterans-affairs/vets-website/pull/31319 merged -- is the last step for this ticket just to verify the deploy? (I moved it to Prod verification on that assumption, but correct it if that's wrong?)

**Comment by chriskim2311** [comment]
@jilladams Verified on staging. This is good to close!
