### ISSUE TITLE
Identify Font Awesome Usage in CMS

### ISSUE THREAD

**Issue by gracekretschmer-metrostar** [department-of-veterans-affairs/va.gov-cms#18401]
## Problem Statement
The platform design team is deprecating font awesome and the CMS team needs to understand, if: 
1. Font Awesome is used within Drupal-CMS, if so - where?
2. What are the consequences if Font Awesome is deactivated?

The platform team is migrating to the USWDS icon library.

## Steps for Audit
- Amanda (cms dev) to work on discovery for depth of impact within the code - need to understand where current FA is being used.
- Discuss changes with lead designer, Naomi, on the platform team - understand what prompted the change?
- Determine if CMS team is using the free version versus the paid version - can we migrate to "free" version while we update our Storybook/Media queries?

## Acceptance Criteria
- [ ] Understanding the consequences to the editor experience, so that the CMS PO and PM can understand how to prioritize solutions for future sprints. 
- [ ] Create a plan of action for implementing a font awesome solution.

**Comment by MDomngz** [comment]
Slack threads- 

- Recent change deprecating FA: https://dsva.slack.com/archives/CT4GZBM8F/p1719351290816269
- Archived thread discussing CMS usage for FA: https://dsva.slack.com/archives/CDKB88PS8/p1648047759506079
- Discussion with Laura F. and Grace K.T. - content build : https://dsva.slack.com/archives/C079SRXLG4V/p1719412897007049

**Comment by MDomngz** [comment]
A free version of Font Awesome will "always" be available for use: https://fontawesome.com/search?m=free&o=r
