### ISSUE TITLE
PR environment for PR-1558 Broken

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#1840]
I have been babysitting this enivronment for several days now and despite several rebuilds triggered in devshop, as well as a couple rounds of closing the PR and re-opening, it fails to build.    ANd somehow iits current status in github does not match its current state in devshop at all.
![image](https://user-images.githubusercontent.com/5752113/82895079-a3db0b00-9f21-11ea-8457-5e4db2a32fe7.png)

http://devshop.cms.va.gov/node/20216
https://github.com/department-of-veterans-affairs/va.gov-cms/pull/1558

**Comment by indytechcook** [comment]
@swirtSJW it looks like the PR has been merged now.  Did any follow ups come out of this?

**Comment by swirtSJW** [comment]
@indytechcook  I think Elijah resolved this.  It had something to do with not exisitng on the disk?
https://dsva.slack.com/archives/CT4GZBM8F/p1591200826211600?thread_ts=1591200719.210500&cid=CT4GZBM8F

**Comment by indytechcook** [comment]
Thanks, closing in reference to the slack thread you posted.
