### ISSUE TITLE
va.gov-cms should keep its content-build reference up-to-date

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#18402]
## User Story or Problem Statement
The CMS repo should always have the most recent version of content-build referenced, so that when content-build is used by CMS it is up-to-date and represents the current state of content-build.

## Description or Additional Context 
va.gov-cms references content-build in its dependencies: https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/composer.json#L228

This content-build version is not automatically kept up-to-date. It appears that it is sometimes requested to be updated by Dependabot, but it has not updated in the past 2 months. https://github.com/department-of-veterans-affairs/va.gov-cms/pulls?q=is%3Apr+is%3Aclosed+content-build

We should figure out how to keep this dependency up-to-date, whether in a completely automated way or at least a way that is checked up on on a regular basis. 

## Acceptance Criteria
- [ ] The CMS repo always has an up-to-date version of it's reference to content build.

**Comment by edmund-dunn** [comment]
Found that dependabot was way behind on updates and content-build was caught in the build up of updates. Increased pull request limit to 25 so that we will see more of the PRs of updates. Doing mass update to catch dependabot up #18701. Closing this ticket in favor of that one.
