### ISSUE TITLE
[Analytics] [Resources & Support Detail Page] Custom GA events removal

### ISSUE THREAD

**Issue by randimays** [department-of-veterans-affairs/va.gov-cms#18417]
## Description
The va-link web component's analytics now include link destination, and va-link-action has been released to the component library. We can now use baked-in analytics on the Resources & Support detail pages.

Example pages
- https://www.va.gov/resources/can-i-get-a-replacement-gi-bill-benefit-certificate-of-eligibility/
- https://www.va.gov/resources/can-i-plan-ahead-for-my-burial-in-a-va-national-cemetery/

### User story
**AS A PO/PM** managing Public Websites products & features
**I WANT** to (where appropriate) adopt the va-link or va-link-action component, its baked-in analytics, and remove the custom GA events
**SO THAT** extraneous code is removed and only the events needed will be triggered.

## Acceptance criteria
- [ ] Element: VA Benefits hub link ("Education and training")
  - [ ] enable web component analytics
  - [ ] remove custom events
- [ ] Element: Related information links
  - [ ] enable web component analytics
  - [ ] remove custom events
- [ ] a11y review

**Comment by chriskim2311** [comment]
Pulling this in for Sprint 7 work

**Comment by chriskim2311** [comment]
Verified on Prod, closing!
