### ISSUE TITLE
[Analytics] [BTSSS Widget] Custom GA events removal & web component upgrades

### ISSUE THREAD

**Issue by randimays** [department-of-veterans-affairs/va.gov-cms#18419]
## Description
The va-link web component's analytics now include link destination, and va-link-action has been released to the component library. We can now use baked-in analytics and convert to web components where possible on the home page.

### User story
**AS A PO/PM** managing Public Websites products & features
**I WANT** to (where appropriate) adopt the va-link or va-link-action component, its baked-in analytics, and remove the custom GA events
**SO THAT** extraneous code is removed and only the events needed will be triggered.

## Acceptance criteria
- [ ] Element: "Go to BTSSS to file a claim" link (requires logging in to see this link)
  - [ ] convert to web component
  - [ ] enable web component analytics
  - [ ] remove custom events
- [ ] a11y review

**Comment by chriskim2311** [comment]
Verified on prod using my va.gov user profile, closing!
