### ISSUE TITLE
Facility locator: Lighthouse websites CSV should be source of truth for VBA Facility link in search results

### ISSUE THREAD

**Issue by omahane** [department-of-veterans-affairs/va.gov-cms#18413]
## User Story or Problem Statement

The websites CSV should be the source of truth for the facility link in a Facility Locator search result, whereas currently the Facility Locator detail page is being returned as the facility link.

## Background
The current state has been described in #14531:
- Under "Context on VBA links"
- In this [comment](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14531#issuecomment-2194953596)

## Acceptance Criteria
- [ ] When we have a facility ready to be published and when that published facility's Drupal-sourced link is added to [websites](https://github.com/department-of-veterans-affairs/lighthouse-facilities/blob/master/facilities/src/main/resources/websites.csv) and it has been deployed by Lighthouse, the link should be returned in the Facility Locator search result.

**Comment by eselkin** [comment]
The data coming back from lighthouse for the VBA result has the property `website: "https://www.benefits.va.gov/albuquerque/"`
So we must be giving a special link for certain facilities
Actually, it processes the website for all result types (not just VBA) and if it determines that the website `isVADomain` then it uses the website, if not then it uses the id for an old detail page

```
{isVADomain(website) ? (
            <h3 className="vads-u-font-size--h5 no-marg-top">
              <a href={website}>{name}</a>
            </h3>
          ) : (
            <h3 className="vads-u-font-size--h5 no-marg-top">
              <Link to={`facility/${location.id}`}>{name}</Link>
            </h3>
          )}
```
isVADomain looks like this, it must be in the form of www/staging.va.gov only. Which is kind of odd. But it makes sense.
```
export const isVADomain = website => {
  const regExp1 = /https?:\/\/(?:www\.|staging\.)?va\.gov(\/*)/;
  return regExp1.test(website);
};
```

**Comment by omahane** [comment]
This is great. That means that we shouldn't have a problem when we put in any va.gov facility page (so long as it has no subdomain [other than staging]).

**Comment by jilladams** [comment]
@omahane @eselkin do the comments mean that we do not actually need to write any code in order to get our first VBA facility published and correctly served from the Facility Locator? 

If that's true: this ticket can close, and we can spin up new tickets for publishing a facility, when one is ready. 
If not: please @ Michael in your reply for his awareness so we can get this refined / scheduled.

**Comment by eselkin** [comment]
Right. It needs to be published (then it will be accessible) then CSV will push that URL to LH. Then in our query to LH we will get back that URL in facility locator. And, since it will be a www.va.gov URL no changes in code need to happen (it doesn't get funneled back into the details pages)
