### ISSUE TITLE
Diagram system architecture of Next-Build as a static deployment system (current state)

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#18423]
## Requirements

We should diagram out the system architecture of Next Build as a static deployment system, so we can confirm that the AP team has a shared understanding of what that architecture is, and so we can explain the architecture to other teams.

```[tasklist]
### Acceptance criteria
- [x] The team comes up with a set of questions that the diagram should answer
- [x] The architecture is diagramed in such a way that it can be easily understood
- [ ] The architecture is posted to an agreed-upon location so that it can easily be found and reviewed by other teams
```

## Background & implementation details

Potential questions we might look at:

- How are code changes to the system deployed?
- How and when is content built and deployed?
- How is traffic routed from the public to Next Build or Content Build content?
- How does the CMS interact with Next Build at build time?
- How does the CMS interact with Next Build persistent servers for preview?

**Comment by mreed101** [comment]
https://app.diagrams.net/#G1ILEsfUWbsHlNlRXNd5jB8tb9s6AiZlJ8#%7B%22pageId%22%3A%22X9690DfesRpe8IeQT4Ge%22%7D
