### ISSUE TITLE
Defect: BRD Staging environment does not contain files from Production

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#18437]
## User Story or Problem Statement
BRD Staging environment is meant to have all files from the BRD Prod Drupal environment, but the images are not being synced correctly. These are supposed to be synced nightly. The images missing means Staging does not properly represent Prod.

## Description or Additional Context 
On every Staging deploy, files are meant to be synced from Production. This process begins here: https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/cms/tasks/post-deploy-tasks.yml#L146

This process appears to be running as part of Staging deploys, for example from [this log](http://jenkins.vfs.va.gov/job/deploys/job/cms-vagov-staging/3571/console):
```
09:22:08  TASK [sites/default/files set owner to cms & group to apache] ******************
09:22:08  Monday 01 July 2024  16:22:08 +0000 (0:00:00.328)       0:03:10.211 *********** 
09:45:00  [0;33mchanged: [ip-10-247-35-84.us-gov-west-1.compute.internal][0m
09:45:00  
09:45:00  TASK [Copy file with owner and permissions] ************************************
09:45:00  Monday 01 July 2024  16:44:59 +0000 (0:22:51.213)       0:26:01.424 *********** 
09:45:01  [0;33mchanged: [ip-10-247-35-84.us-gov-west-1.compute.internal][0m
09:45:01  
09:45:01  TASK [Download Asset files from S3] ********************************************
09:45:01  Monday 01 July 2024  16:45:01 +0000 (0:00:01.733)       0:26:03.157 *********** 
09:49:53  [0;33mchanged: [ip-10-247-35-84.us-gov-west-1.compute.internal][0m
09:49:53  
09:49:53  TASK [Create a local temporary directory] **************************************
09:49:53  Monday 01 July 2024  16:49:39 +0000 (0:04:38.069)       0:30:41.227 *********** 
09:49:53  [0;33mchanged: [ip-10-247-35-84.us-gov-west-1.compute.internal][0m
09:49:53  
09:49:53  TASK [set_fact] ****************************************************************
09:49:53  Monday 01 July 2024  16:49:40 +0000 (0:00:01.428)       0:30:42.655 *********** 
09:49:53  [0;32mok: [ip-10-247-35-84.us-gov-west-1.compute.internal][0m
09:49:53  
09:49:53  TASK [Extract asset files to a temp dir] ***************************************
09:49:53  Monday 01 July 2024  16:49:40 +0000 (0:00:00.028)       0:30:42.684 *********** 
10:12:30  [0;33mchanged: [ip-10-247-35-84.us-gov-west-1.compute.internal][0m
10:12:30  
10:12:30  TASK [Parallel Rsync files to EFS] *********************************************
10:12:30  Monday 01 July 2024  17:12:27 +0000 (0:22:46.960)       0:53:29.644 *********** 
10:17:21  [1;30mFAILED - RETRYING: Parallel Rsync files to EFS (3 retries left).[0m
10:19:42  [0;33mchanged: [ip-10-247-35-84.us-gov-west-1.compute.internal][0m
10:19:42  
10:19:42  TASK [Delete temp dir] *********************************************************
10:19:42  Monday 01 July 2024  17:19:39 +0000 (0:07:11.705)       1:00:41.349 *********** 
10:19:49  [0;33mchanged: [ip-10-247-35-84.us-gov-west-1.compute.internal][0m
```

The best way to see if the images are in place on Staging is to get into the file system and look at it:
1.  `ssm-session vagov-staging cms auto` (must be already authenticated)
2. Become the cms user: `sudo su - cms`
3. Change to the files directory: `cd docroot/sites/default/files/`
4. Check the file/directory structure in that directory.

If you only see one dated folder, the images are not synced properly: 
<img width="488" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/203623/493fb389-55f1-49bf-88be-e5aa67f32479">

A properly synced files directory will have dated directories dating back to 2019:

<img width="497" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/203623/8dc42b4d-acef-4505-811c-955fb05bd2f0">

## Steps for Implementation
Definitely look at the recent changes to permissions for staging in the post-deploy-tasks.yml file: https://github.com/department-of-veterans-affairs/devops/commits/master/ansible/deployment/config/cms/tasks/post-deploy-tasks.yml

There was work in there recently that is probably the source of the problem. 

## Acceptance Criteria
- [ ] Images in prod match the images in staging.

**Comment by 7hunderbird** [comment]
I ssh'd into the latest staging instance and saw that the files are there now.

![CleanShot 2024-07-11 at 12 05 40](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/3761/21ee95f4-3c90-4f1b-b0ac-828442415baa)

If you concur @timcosgrove we can close this ticket.

**Comment by timcosgrove** [comment]
I concur; closing this.
