### ISSUE TITLE
[Discharge Upgrade Wizard] Add missing logic for Discharge Year answer "Before 1992'

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-cms#18438]
## Status
[2024-07-02] This ticket will close with this one https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18429

## Description
If you select "Before 1992" as the Discharge Year in the flow, the Continue button does not show any more questions. We are likely missing display logic for this flow and it needs to be added.

In ticket #18025, Jordan asked about this in a [Slack thread](https://dsva.slack.com/archives/C52CL1PKQ/p1719859203878299) and confirmed that selecting "Before 1992" was just missing logic for that particular answer. Selecting "Before 1992" does not affect any logic flow and should follow the main flow documented in the [Mural board.](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1696352911500/80253b1c7200212cbcbcfb940d2cf4a29fed8417?sender=u01810f3edbfc878c08be5925)

### User story

**AS A** Veteran, their caregiver, family member or survivor
**I WANT** to be able to select  "Before 1992" as my Discharge Year, click Continue, and see additional questions to answer
**SO THAT** I can get accurate results at the end of the wizard for this particular flow

## Acceptance criteria

- [ ] Logic for the answer "Before 1992' (to the Discharge Year question) follows the main logic flow found in the Mural board referenced in the Description
- [ ] a11y Review

**Comment by chriskim2311** [comment]
@FranECross Sorry just saw that this was created. This ticket will close with this one https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18429

**Comment by FranECross** [comment]
Closing as a dupe of https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18429
