### ISSUE TITLE
After FE launch & publish of first RO: Submit 508 office audit request

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#18433]
### User story

**AS A** PO/PM
**I WANT** VBA Regional Offices to be submitted to the 508 office for audit
**SO THAT** we keep things compliant.

## Acceptance criteria

- [x] File Audit request according to docs: https://depo-platform-documentation.scrollhelp.site/developer-docs/request-support-from-the-va-508-office#audit-request
  - ServiceNow (SNOW) request number: REQ29858122
- [ ] Update Collab Cycle ticket body to reflect ticket is created / share SNOW number: https://github.com/department-of-veterans-affairs/va.gov-team/issues/46029

**Comment by jilladams** [comment]
FYI @laflannery @Agile6MSkinner created so we remember to create the 508 office audit ticket after launch (easy to forget, and we have forgotten many times...)

Moved to Blocked, and added launch plan as a blocking dependency.

**Comment by jilladams** [comment]
This has been published:
https://www.va.gov/portland-va-regional-benefit-office

This ticket is unblocked.

**Comment by Agile6MSkinner** [comment]
Service Now ticket REQ29858122 created
