### ISSUE TITLE
Discovery: Platform Support

### ISSUE THREAD

**Issue by gracekretschmer-metrostar** [department-of-veterans-affairs/va.gov-cms#18448]
## User Story or Problem Statement
The CMS team needs to understand what is feasible and what is needed for CMS to be folded into Platform Support.

## Description or Additional Context 
Currently, the CMS team supports requests and handling of bugs for the CMS platform from outside teams through posts within the #sitewide-cms-platform channel in Slacks. These posts are unstructured, ad hoc, and typically, the same set of team members within CMS respond to support troubleshooting. As the demands on the CMS team grows, the team needs to come up with more sustainable and scalable options to respond to developer support requests. 

## Steps for Implementation
- Reach out to platform leadership to get their advice and understand what is needed from CMS to integrate with Platform Support
- Platform leadership and CMS leadership determine next steps of if/how CMS folds into platform support 
- Create a list of requirements for CMS to move into platform support 

## Acceptance Criteria
- [x] Platform leadership understands that CMS wants to move into platform support
- [x] Platform leadership and CMS leadership are on the same page about next steps for developer support and platform support
- [ ] A list of requirements is documented about what is needed from CMS and best practices for moving into platform support

**Comment by gracekretschmer-metrostar** [comment]
Erika's feedback: there's existing documentation about platform support within Confluence.

**Comment by michelle-dooley** [comment]
Michelle met with Andrea to discuss. Platform team is aware and will help guide us when we are ready. We will need to have very thorough documentation/artifacts before this shift can happen.

[Platform Support documentation](https://vfs.atlassian.net/wiki/spaces/PTST/overview)

[Support overview](https://depo-platform-documentation.scrollhelp.site/support/support-overview)
