### ISSUE TITLE
Discovery: Developer Support

### ISSUE THREAD

**Issue by gracekretschmer-metrostar** [department-of-veterans-affairs/va.gov-cms#18446]
## User Story or Problem Statement
To more sustainability scale, the CMS team needs create structures for managing support requests and reporting of bugs from teams building within the CMS platform. 

## Description or Additional Context 
Currently, the CMS team supports requests and handling of bugs for the CMS platform from outside teams through posts within the #sitewide-cms-platform channel in Slacks. These posts are unstructured and ad hoc and typically, the same set of team members within CMS respond to support troubleshooting. As the demands on the CMS team grows, the team needs to come up with more sustainable and scalable options to respond to developer support requests. 

## Steps for Implementation
- Identify themes (e.g. look at sitewide posts within the CMS channel) of where support is needed from developers and the skills needed to support those requests
- Create a proposed structure (e.g. tier 1, tier 2, tier 3) for responding to support requests 
- Identify knowledge and skill gaps within the current team that is needed to support the developer support structure

## Acceptance Criteria
- [x] A prototype of a developer support structure to respond to our most common requests from developers 
- [x] A framework on how to respond to testing failures. 
- [ ] A list of gaps in both knowledge and skills that are needed to support the developer support structure

**Comment by gracekretschmer-metrostar** [comment]
Depending on Jon's capacity, possibly pull him into this work.

**Comment by 7hunderbird** [comment]
There are three main areas for Developer Support I see so far.

- area 1: brd
  - what is the pipeline
  - what are the utility jobs
  - potentially how to refresh a Jenkins Agent when a disk space error happens
- area 2: content-build
  - places to check
    - place 1: continuous integration
      - when it's safe to rebuild CI 
      - what a clean build will depend on 
    - place 2: content-release
      - what the delivery schedule is 8am to 8pm
      - what the SLA limit is
    - place 3: daily production release
- area 3: tugboat
  - it's safe to rebuild base preview
    - what to do if it doesn't work (escalation)

Miscellaneous diagnostic resources
- aws console
- ssh connections
- datadog

**Comment by gracekretschmer-metrostar** [comment]
Jon: build out a framework for testing failures. And how to respond to alerts,

**Comment by gracekretschmer-metrostar** [comment]
Make a sprint goal for sprint 15.

**Comment by gracekretschmer-metrostar** [comment]
https://vfs.atlassian.net/wiki/spaces/~712020eee99537517b4d9594003707b252e24b/pages/3330768947/Developer+Support+Discovery
