### ISSUE TITLE
[Action Link Component] Update Home Page with the new action link component

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-cms#18458]
## Description
The Design System Team has build a component for the Action link, and the Home Page needs to be updated.

### User story

**AS A** PO/PM
**I WANT** the Action Links in the Home Page to use the new V3 component when it's available
**SO THAT** Veterans, their caregivers, family and survivors have a visually appealing experience in VA.gov, thus retaining their confidence in the site and the VA.

## Acceptance criteria

Note: some of the work below could be partly or completely covered by the analytics removal tickets.

- [ ] Hero CTA (white link) has been updated
- [ ] a11y review

**Comment by laflannery** [comment]
@FranECross  This is done. Is there another reason (e.g. analytics maybe?) why this would need another ticket?
![image](https://github.com/user-attachments/assets/081e3ff7-e005-4929-aae3-b92ffd6d4e2b)

**Comment by FranECross** [comment]
@laflannery This must just be a dupe ticket. If it's decided we need some other event(s), after I review PAW during my analytics request with them, then I'll create another ticket at that time. Closing this one as a no op. Thanks!
