### ISSUE TITLE
a11y tests do not complete successfully

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#18450]
## Requirements

a11y tests should complete successfully so that we can review the results of them and correct a11y problems with our site.

```[tasklist]
### Acceptance criteria
- [ ] a11y workflow in next-build consistently completes without error
```

## Background & implementation details

The workflow is here: https://github.com/department-of-veterans-affairs/next-build/actions/workflows/a11y.yml

The last successful run was on May 25: https://github.com/department-of-veterans-affairs/next-build/actions/runs/9263052640

At this point, it is unclear what has changed.

**Comment by mreed101** [comment]
@timcosgrove I believe this work is already done. AXE test will fail during CI
