### ISSUE TITLE
[Action Link Component] Update Events with the new action link component

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-cms#18457]
## Description
The Design System Team has build a component for the Action link, and Events needs to be updated.

### User story

**AS A** PO/PM
**I WANT** the Action Links in Events to use the new V3 component when it's available
**SO THAT** Veterans, their caregivers, family and survivors have a visually appealing experience in VA.gov, thus retaining their confidence in the site and the VA.

## Acceptance criteria

Note: some of the work below could be partly or completely covered by the analytics removal tickets.

- [ ] RSVP CTA (two links; one for regular RSVP and one for email) has been updated
- [ ] a11y review

**Comment by randimays** [comment]
Noting here that we are planning to ship AP events to prod after Veteran's Day. Depending on when this ticket is worked, it may make sense to make these changes in next-build specifically (and not content-build): https://github.com/department-of-veterans-affairs/next-build/blob/main/src/templates/layouts/event/index.tsx

**Comment by randimays** [comment]
Pulled in for Sprint 19.

**Comment by randimays** [comment]
Validated all production events just in case! Prod deploy for next-build went out successfully and everything looks good 👍🏻 Closing as complete.
