### ISSUE TITLE
[Action Link Component] Update Discharge Upgrade Wizard with the new action link component

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-cms#18453]
## Description

The Design System Team has built a component for the Action link, and Discharge Upgrade Wizard to be updated.

### User story

**AS A** PO/PM
**I WANT** the Action Links in Discharge Upgrade Wizard to use the new V3 component
**SO THAT** Veterans, their caregivers, family and survivors have a visually appealing experience in VA.gov, thus retaining their confidence in the site and the VA.

## Acceptance criteria

Note: some of the work below could be partly or completely covered by the analytics removal tickets.

- [ ] "Get started" link on the landing page for the current (production) DUW has been updated
- [ ] "Get started" link on the landing page for the new DUW has been updated
- [ ] "Get my results" link under the review answers table has been updated
- [ ] "Get the form on the Air Force Review Boards Agency Website and Portal" on the results page has been updated
- [ ] a11y review

**Comment by laflannery** [comment]
@FranECross Can we roll this in with the Discharge upgrade stuff being done now? I almost gave this as part of my feedback to Chris on a PR recently not realizing we had a separate ticket for it

**Comment by FranECross** [comment]
@laflannery @chriskim2311 Absolutely. It's in the ready column... Chris, feel free to grab it while you're working on DUW. I'll add it to the DUW epic, as well as leaving it in the component epic, just for visibility.

**Comment by chriskim2311** [comment]
This ticket will be completed with the work in this PR https://github.com/department-of-veterans-affairs/vets-website/pull/31865

**Comment by laflannery** [comment]
@chriskim2311 to clarify - are all of these ACs supposed to be updated within the Step 3 PR or just the Air force one that I pointed out? I am only seeing that one which is why I want to be sure

**Comment by FranECross** [comment]
@chriskim2311 I believe you've already taken care of these?

**Comment by chriskim2311** [comment]
@FranECross Thanks for checking in. This can be closed as completed.

**Comment by FranECross** [comment]
Closing as a no op; completed in a different ticket.
