### ISSUE TITLE
Create Rates Editor Role

### ISSUE THREAD

**Issue by EWashb** [department-of-veterans-affairs/va.gov-cms#18451]
## User Story or Problem Statement
Benefits rates within the [Education Benefit Hubs](https://prod.cms.va.gov/section/vba/education-benefits-hub) are required to be updated by an August 1 cutover. In order to support this effort, partners in the associated business lines will need access to Drupal to edit (NOT publish) the Benefits Detail Pages that have rates information. They should not be given access to edit all Benefit Hubs content, therefore, this granular access preferred. Only Benefits Detail Pages within the Education Benefits Hub is the scope of this new role. 

## Description or Additional Context 
- This is a new role that is limited to **editing** only Education Benefits Hub. Specifically, only edit Benefits Detail Page and assigned to education benefits hub section. 
- This role should NEVER be allowed to publish. 
- The rates editor will edit the content and CAIA will publish the content.
- There is one person needing access right now, but there will be potentially others coming in August.
- This new editor will need access by mid July to meet the August 1 deadline to update the content. 
- Our helpdesk should be informed of this new role and a runbook should be created.
- CAIA partners would like to work with someone on our team to get a knowledge base article added.

## Steps for Implementation
- [ ] CMS engineering determines how give the user appropriate permissions. 
- [ ] CMS engineering implements user account. 
- [ ] QA review to confirm that rates editor have the appropriate access to edit and cannot publish

## Anti Goals
- The rates editor role has access to more than Benefits Details Page. 
- The rates editor role can publish their content. 

## Acceptance Criteria
- [ ] A new role is created with edit access only to the [Education Benefits Hub Section](https://prod.cms.va.gov/section/vba/education-benefits-hub) 
- [ ] CMS helpdesk runbook is created with support of CAIA
- [ ] One new user is given access by mid-July

**Comment by gracekretschmer-metrostar** [comment]
Feedback from Erika: it would be ideal to create a review process and very important that the user's permissions are correctly mapped. Take care during the QA.

**Comment by gracekretschmer-metrostar** [comment]
7/10: Edmund will have a test account ready for tugboat today. Get help desk to create an account for Tammy today.

**Comment by gracekretschmer-metrostar** [comment]
Jon will be assigned the reviewer and will do the testing.

**Comment by gracekretschmer-metrostar** [comment]
@EWashb can you provide us with the name and email address for the first user we are using this new rate editor role for?

**Comment by EWashb** [comment]
Posted the email in the corresponding slack. 

Also, can we update the name to `business line editor`? After a discussion with CAIA, we hope that this will allow the role to scale beyond rates and will keep the CMS team from creating a ton of roles in the future. We may eventually have a business line editor for other types of benefits hubs
