### ISSUE TITLE
[Action Link Component] Update Health Care / CTA Widgets with the new action link component

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-cms#18455]
## Description

The Design System Team has build a component for the Action link, and Health Care / CTA Widgets needs to be updated.

### User story

**AS A** PO/PM
**I WANT** the Action Links on the Health Care / CTA Widgets to use the new V3 component 
**SO THAT** Veterans, their caregivers, family and survivors have a visually appealing experience in VA.gov, thus retaining their confidence in the site and the VA.

## Acceptance criteria

Note: some of the work below could be partly or completely covered by the analytics removal tickets.

- [ ] CTA text (it varies; this is in static-pages/cta-widget in VW) has been updated
- [ ] "Go to My VA Health" link has been updated
- [ ] "Go to ___ on VA.gov" link has been updated
- [ ] a11y review

**Comment by randimays** [comment]
@FranECross This work has been completed for all healthcare widgets as part of an analytics ticket (there's a note in the AC above to corroborate): [PR](https://github.com/department-of-veterans-affairs/vets-website/pull/30902) and [ticket](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18538) where this was done.

Closing as complete, but feel free to re-open if I've missed something.
