### ISSUE TITLE
URL Change for: West Lakeland VA Clinic 

### ISSUE THREAD

**Issue by TroyCMSSupport** [department-of-veterans-affairs/va.gov-cms#18463]
Parent ticket: [18462](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18462)
Editor notified the CMS Help Desk that this facility is now closed. No other indication as yet
### Implementation date
When does this request need to be live:
ASAP

### Instructions for URL redirect
(Note: This issue will be used from initial request through implementation to ensure all individuals working on this are notified of status updates.  Please do not create multiple issues to track different steps.)
- [x] Notify VA stakeholders as appropriate.
- [x] Link the related facility closure / rename issue.
- [x] Create a URL redirect in the [devops](https://github.com/department-of-veterans-affairs/devops) repo in `ansible/deployment/config/revproxy-vagov/vars/redirects.yml`
- [x] Add the "Awaiting redirect" flag to the facility node with a revision log message that includes a link to this ticket, preserving the node's current moderation state.
- [x] Redirects deploy daily except Friday at 10am ET, or by requesting OOB deploy (of the revproxy job to prod) in #vfs-platform-support. After deploy, validate that the URL redirect is deployed. (Note: In the event of a facility closure or a name change,  validate that this occurs before making the Lighthouse csv changes.)
- [x] Update this ticket with a comment that the redirect has been deployed.
- [x] Remove the "Awaiting redirect" flag on the facility node with a revision log message that includes a link to this ticket, preserving the node's current moderation state.
- [x]  Notify helpdesk via comment on ticket or Slack message in #cms-support that changes are ready for review.

#### URL Redirect: vha_673QC
| Current URL  |  Redirect Destination or New URL |
| ---  |  --- |
| [https://www.va.gov/tampa-health-care/locations/west-lakeland-va-clinic/](https://www.va.gov/tampa-health-care/locations/west-lakeland-va-clinic/) | [https://www.va.gov/tampa-health-care/locations/](https://www.va.gov/tampa-health-care/locations/) |

**Note: Canonical URL changes do not block the completion of the parent ticket. Once the URL redirect above has been deployed, the value to the Veteran is delivered. This ticket should be kept open until the URL change is verified, except in the case of a removal (as described below).**

### 2. Canonical URL removal (if removed from VAST)
- [x] Try to find the facility via the Facility Locator, using the Facility API ID ([https://va.gov/find-locations/facility/"facility_api_id"](https://www.va.gov/find-locations/facility/vha_673QC)). If it is not available, proceed.
- [x] Contact Lighthouse via Slack at #cms-lighthouse channel that this facility requires a canonical link to be removed in the following format (replacing the placeholder data with the actual API Id and VA.gov URL):
  - `vha_673QC,https://www.va.gov/tampa-health-care/locations/west-lakeland-va-clinic/`

**Note: there's no check to see if it's not returning anything, as it should already be not showing anything in the Facility Locator.**

**Comment by ian-sears** [comment]
@omahane
tagging @TroyCMSSupport and @jilladams fysa
Please initiate the URL redirect
[FROM] https://www.va.gov/tampa-health-care/locations/west-lakeland-va-clinic/
[TO] https://www.va.gov/tampa-health-care/locations/
to get the above moving forward.
If we understand correctly, once this complete and resolves, the CMS Help Desk can return to this ticket and request the CSV Lighthouse change to reflect the same.
This Facility API ID has already been removed from source.
https://www.va.gov/find-locations/facility/vha_673QC
The page is here: https://www.va.gov/tampa-health-care/locations/west-lakeland-va-clinic/

**Comment by omahane** [comment]
The redirect was deployed today.

**Comment by jilladams** [comment]
Ian requested CSV removal here: https://dsva.slack.com/archives/C02BTJTDFTN/p1729018244043589?thread_ts=1728689982.365729&cid=C02BTJTDFTN

**Comment by ian-sears** [comment]
Closing as resolved.
Redirect has been deployed (resolves to the Locations page.
VAST came through as Removed from Source.
vha_673QC has been removed from websites.csv
