### ISSUE TITLE
Name that CMS! (part 2)

### ISSUE THREAD

**Issue by rachel-kauff** [department-of-veterans-affairs/va.gov-cms#1847]
## Description

Is it Drupal? Is it VA.gov CMS? Is it VACMS?  All of the above? What are the rules by which we use these names/brands in different places? 

## Artifacts
* [MURAL](https://app.mural.co/t/vagov6717/m/vagov6717/1589235929175/97ed9978b0165a98942150bf667b133e4faad3f1) 

**AC**
- [ ] Identify stakeholders for a smaller working group

-----
**Sprint 6 Summary**
- [x] Held 2 "word huddles" to get oriented in the problem space
- [x] Async brainstorming with the CMS team with a list of possibilities
- [x] Sorted and ranked possibilities based on current assumptions
- [x] Identified areas of alignment/misalignment on direction

**Beyond Sprint 7**
- [ ] Mission statement
- [ ] Figure out the stakeholders for final signoff (Chris Johnson? etc)
- [ ] Complete audit of all the places where the product's name is used.

**Comment by kevwalsh** [comment]
Changing estimate from 8 to 3 to reflect work in Sprint 8.
