### ISSUE TITLE
[EPIC] [Q3 2024] Redirect requests] All redirect requests to be worked on in Q3 2024

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-cms#18478]
## Description

Q3 Epic to organize all redirect requests

## Acceptance criteria

- [ ] See individual tickets for AC

**Comment by jilladams** [comment]
@FranECross would you be ok if we renamed this to content support? Sometimes CAIA needs things other than redirects (translation toggles, menu work, etc.)

**Comment by FranECross** [comment]
Oh, I was going to close this one, and move the tickets into it over to the ticket you pinged me about yesterday. I edited the title of that one to indicate Q1 - Q3: [EPIC] Public Websites: Content support Q1 - Q3 2024#16394, and you have a good list (including redirects in it) that works great. I'll close 16394 after Q3 and create a dupe for Q4 and onwards. Thanks for reminding me of this one!

**Comment by FranECross** [comment]
Closing as a dupe of #16394
