### ISSUE TITLE
LH V0: Deprecate the  /v1/facilities/va endpoint in vets-api

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#18487]
**[2024-10-30]** We cannot deprecate the whole legacy API client til we hear from Don (McCaughey?) on the mobile team. BUT: we may be able to deprecate this endpoint.

## Description or Additional Context 
Context: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18351
> Should decommission and remove not the library but the endpoint for /v1/facilities/va

The legacy Facilities API client/library in vets-api has an active endpoint that references Lighthouse V0. We need to deprecate that, now that LH V0 has been deprecated

The legacy API client is very minimally documented here: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/facilities/facilities-api#legacy-facilities-api-client

The code lives here: https://github.com/department-of-veterans-affairs/vets-api/tree/master/lib/lighthouse/facilities

## Acceptance Criteria
- [x] /v1/facilities/va endpoint is no longer available in vets-api

**Comment by jilladams** [comment]
We may find ourselves blocked from removing htis endpoint, depending on how Mobile handled the legacy API client V1 upgrade. But Eli will check, and if it can be removed, we will.

**Comment by eselkin** [comment]
The endpoint could be removed without touching the library stuff that the Mobile team modified.

**Comment by jilladams** [comment]
@eselkin how can we verify this in order to close?

**Comment by eselkin** [comment]
If you go to https://api.va.gov/v1/facilities/va/vha_648 you should get a 404.
