### ISSUE TITLE
PACT Act: Update <title> to align with new guidance

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#18486]
## Status
**[2024-07-15] [Fran]** Moved to Next Refinement because we're picking up the PAW work again.

## Background
There is [finalized guidance](https://design.va.gov/content-style-guide/title-tags#exception-2--forms-and-subtasks) now on the Design System website around `<title>` tags and the subtask pattern. This was created jointly with accessibility folks (myself included), CAIA and folks on the forms team to make sure this guidance met accessibility and content standards and that it would work for all use cases.

## Description
We need to update the behavior on the PACT Act form to align with this new, finalized guidance. Currently, for each screen the `<title>` is `{H1} | PACT Act | Veterans Affairs` but we should drop the H1 and this should be updated to just use the form name `Learn how the PACT Act may effect you | Veterans Affairs` for each screen of the flow.

## Acceptance Criteria
- [ ] All `title` tags in the PAW flow say `Learn how the PACT Act may effect you | Veterans Affairs`
- [ ] Requires accessibility review

**Comment by jilladams** [comment]
Clicked through Staging, <title> remains consistent, and meets AC. Closing.
![Screenshot 2024-07-25 at 9 27 55 AM](https://github.com/user-attachments/assets/59b4e2e6-a0c6-450c-9d3f-a807ac869853)
