### ISSUE TITLE
Frontend QA Next Build's Events and Event Listings

### ISSUE THREAD

**Issue by gracekretschmer-metrostar** [department-of-veterans-affairs/va.gov-cms#18493]
## User Story or Problem Statement
The AP team needs support in reviewing the Next Build templates to determine if their output matches Content Build's template's output. 

## Description or Additional Context 
Before Next Build moves into production, there needs to be a frontend QA to confirm that the Next Build templates are producing the same front experience as the existing templates within Content Build. For the first round of QA, the CMS team will perform the QA and also provide feedback about the existing structure for QAing. 

An overview of the review process can be found [here](https://vfs.atlassian.net/wiki/spaces/AP1/pages/3294068753/AP+QA+testing+framework)

## Reference Documentation
- https://vfs.atlassian.net/wiki/spaces/AP1/pages/3294068753/AP+QA+testing+framework

## Steps for Implementation
- [ ] Each reviewer is given 25 URLs for Next Build's events and event listing and it's corresponding Content Build's events and event listing URLs. 
- [ ] For each URL, the reviewer has used the [Review Instructions + Checklist](https://vfs.atlassian.net/wiki/spaces/AP1/pages/3294068753/AP+QA+testing+framework#Review-Instructions-%2B-Checklist) to review the page.
- [ ] Any problems discovered for each review are reported in the #accelerated-publishing slack channel, using the [Reporting Problems in Templates](https://vfs.atlassian.net/wiki/spaces/AP1/pages/3294068753/AP+QA+testing+framework#Reporting-Problems-with-Templates) guidance.
- [ ] The reviewer has tracked their time to complete their review of events and event details and shared that information with the AP team. 
- [ ] The reviewer has provided feedback about the [Review Instructions + Checklist](https://vfs.atlassian.net/wiki/spaces/AP1/pages/3294068753/AP+QA+testing+framework#Review-Instructions-%2B-Checklist)  

## Event Links

Any current production link can be used to test an event page or event listing.
Simply find any event or listing and replace the beginning of the url with https://dev.va.gov.
Any event page viewed on dev.va.gov will be a next build page

**Event Listings**
https://www.va.gov/chillicothe-health-care/events/
https://dev.va.gov/chillicothe-health-care/events/

**Event**
https://www.va.gov/chillicothe-health-care/events/70789/
https://dev.va.gov/chillicothe-health-care/events/70789/

## Acceptance Criteria
- [ ] Events and events details pages are reviewed by CMS team, if any inconsistencies or problems are discovered, those problems are reported in the #accelerated publishing channel. 
- [ ] CMS reviewers are give the AP team feedback about the reviewing structure and  context about the level of effort to perform the reviews.

**Comment by michelle-dooley** [comment]
link to AP [QA template](https://github.com/department-of-veterans-affairs/next-build/issues/574)

link to [Confluence documentation](https://vfs.atlassian.net/wiki/spaces/AP1/pages/3294068753/AP+QA+testing+framework#Review-Instructions-%2B-Checklist)

**Comment by michelle-dooley** [comment]
Links to AP tickets for Events and Event Listing QA to follow as guide

https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18494

https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18498

**Comment by srancour** [comment]
[Tracking document](https://docs.google.com/spreadsheets/d/1laE23c9INxp5jM7fZ7ZOJy9hMYr4We1h_MD52c3XW4w/edit?usp=sharing) Jake and I are using
