### ISSUE TITLE
[Analytics] [Featured News Story] Custom GA events removal & web component upgrades

### ISSUE THREAD

**Issue by randimays** [department-of-veterans-affairs/va.gov-cms#18497]
## Status
**[2024-07-18] [Fran]** Reviewed today; implementing component, adopting baked in analytics, remove custom analytics. No duplicate events firing. Not urgent.

## Description
The va-link web component's analytics now include link destination, and va-link-action has been released to the component library. We can now use baked-in analytics for featured news stories.

### User story
**AS A PO/PM** managing Sitewide products & features
**I WANT** to (where appropriate) adopt the va-link or va-link-action component, its baked-in analytics, and remove the custom GA events
**SO THAT** extraneous code is removed and only the events needed will be triggered.

### Engineering notes / background
Slack thread: https://dsva.slack.com/archives/C03LFSPGV16/p1720801871640619

Content-build template: https://github.com/department-of-veterans-affairs/content-build/blob/main/src/site/teasers/news_story_page_feature.drupal.liquid

This featured news story functionality is not used (see Slack thread for context). We can still make adjustments to the analytics, but we will not have a place to test them (even in a Tugboat).

## Acceptance criteria
- [x] Element: news story title
  - [x] upgrade to web component
  - [x] enable web component analytics
- [ ] a11y review

**Comment by eselkin** [comment]
Impossible to verify (featured news story not used), but code is correct on prod
