### ISSUE TITLE
[Analytics] [Event Detail Page] Custom &  Dupe GA events removal and web component upgrades

### ISSUE THREAD

**Issue by randimays** [department-of-veterans-affairs/va.gov-cms#18512]
## Status
**[2024-07-22] [Fran]** Duplicative events need to be removed. This ticket should be prioritized.

## Description
The va-link web component's analytics now include link destination, and va-link-action has been released to the component library. We can now use baked-in analytics on the event detail pages.

Example pages
- https://www.va.gov/durham-health-care/events/69410/

### User story
**AS A PO/PM** managing Sitewide products & features
**I WANT** to (where appropriate) adopt the va-link or va-link-action component, its baked-in analytics, and remove the custom GA events
**SO THAT** extraneous code is removed and only the events needed will be triggered.

## Acceptance criteria
- [ ] Element: "Browse the {VAMC location} events calendar" link
  - [ ] remove custom events
  - [ ] enable component's baked-in analytics
- [ ] Element: "Get directions on Google Maps" link
  - [ ] remove custom events
  - [ ] enable component's baked-in analytics
  - [ ] convert to web component
- [ ] a11y review

**Comment by chriskim2311** [comment]
Pulling in to work will carry over to sprint 9

**Comment by chriskim2311** [comment]
@laflannery Can you take a quick review on prod? Thanks! It looks good on my end.
