### ISSUE TITLE
[Analytics] [VAMC Locations Pages] Custom & Duplicate GA events removal

### ISSUE THREAD

**Issue by randimays** [department-of-veterans-affairs/va.gov-cms#18518]
## Status
**[2024-07-22] [Fran]** Duplicative events need to be removed. This ticket should be prioritized.

## Description
The va-link web component's analytics now include link destination, and va-link-action has been released to the component library. We can now use baked-in analytics on the VAMC locations pages.

Example pages
- https://www.va.gov/charleston-health-care/locations/

### User story
**AS A PO/PM** managing Sitewide products & features
**I WANT** to (where appropriate) adopt the va-link or va-link-action component, its baked-in analytics, and remove the custom GA events
**SO THAT** extraneous code is removed and only the events needed will be triggered.

## Acceptance criteria
- [ ] Element: "Facility notice" link (within alert)
  - [ ] remove custom events
  - [ ] enable component baked-in analytics
- [ ] Element: "Limited services and hours" link (within alert)
  - [ ] remove custom events
  - [ ] enable component baked-in analytics
- [ ] Element: "Facility closed" link (within alert)
  - [ ] remove custom events
  - [ ] enable component baked-in analytics
- [ ] a11y review

**Comment by chriskim2311** [comment]
Verified on prod, closing!
