### ISSUE TITLE
Service Locations do not show online scheduling link

### ISSUE THREAD

**Issue by eselkin** [department-of-veterans-affairs/va.gov-cms#18519]
## User Story or Problem Statement

Attempts to reuse variables to determine whether to display the Appointments header made several conditionals into variables, but the conditional for the `fieldOnlineSchedulingAvail` left it as a conditional assigned to a variable, but this is not possible in liquid (only Javascript and Ruby). 

@laflannery identified the missing link in VBA, but also affects VAMC

## Examples for QA
- Jamaica Plain VAMC Mental Health Facility Service
  - [Drupal Link](https://prod.cms.va.gov/boston-health-care/locations/jamaica-plain-va-medical-center/mental-health-care)
  - [Front end](https://www.va.gov/boston-health-care/locations/jamaica-plain-va-medical-center/#mental-health-care)
- Honolulu VBA Pre-Discharge Claims Facility Service
  - [Drupal Link](https://prod.cms.va.gov/node/68768)
  - Front end Must be viewed on a tugboat

Change conditional to use liquid filter for operator

## Acceptance Criteria
- [x] Online scheduling link is visible for VBA when set to yes in drupal
- [x] Online scheduling link is visible for VAMC when set to yes in drupal

**Comment by jilladams** [comment]
Verified the VAMC case on prod: https://www.va.gov/boston-health-care/locations/jamaica-plain-va-medical-center/#mental-health-care

![Screenshot 2024-07-19 at 12 32 20 PM](https://github.com/user-attachments/assets/c83ed85e-7b11-4c19-b1ed-c8ac07b14c5d)

I'm closing on the assumption that the VBA item here is a match for the case as well: https://www.va.gov/portland-va-regional-benefit-office/#vba-service-item-1171-

![Screenshot 2024-07-19 at 12 34 34 PM](https://github.com/user-attachments/assets/8416d6c4-197d-4a4b-bc84-d47f2918363a)


Reopen if not. Starting a slack thread about the ID on that service accordion also, separate issue if it's an issue.

**Comment by laflannery** [comment]
@jilladams I believe you are referring to [this issue](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17986)
