### ISSUE TITLE
[Analytics] [VAMC Region Detail Pages] Custom GA events removal

### ISSUE THREAD

**Issue by randimays** [department-of-veterans-affairs/va.gov-cms#18510]
## Status
**[2024-07-18] [Fran]** Reviewed today; implementing component, adopting baked in analytics, remove custom analytics. No duplicate events firing. Not urgent.

## Description
The va-link web component's analytics now include link destination, and va-link-action has been released to the component library. We can now use baked-in analytics on the VAMC region detail pages.

Example pages
- https://www.va.gov/south-texas-health-care/

### User story
**AS A PO/PM** managing Sitewide products & features
**I WANT** to (where appropriate) adopt the va-link or va-link-action component, its baked-in analytics, and remove the custom GA events
**SO THAT** extraneous code is removed and only the events needed will be triggered.

## Acceptance criteria
- [x] Element: "See all locations" link
  - [x] remove custom events
  - [x] enable baked-in component analytics
- [x] Element: "Refill and track your prescriptions" link
  - [x] remove custom events
  - [x] enable baked-in component analytics
- [x] Element: "Download your VA medical records (Blue Button)" link
  - [x] remove custom events
  - [x] enable baked-in component analytics
- [x] Element: "Send a secure message to your health care team" link
  - [x] remove custom events
  - [x] enable baked-in component analytics
- [x] Element: "View your lab and test results" link
  - [x] remove custom events
  - [x] enable baked-in component analytics
- [x] Element: "Schedule and manage health appointments" link
  - [x] remove custom events
  - [x] enable baked-in component analytics
- [x] Element: "Order hearing aid batteries and accessories" link
  - [x] remove custom events
  - [x] enable baked-in component analytics
- [x] Element: "See all stories" link
  - [x] remove custom events
  - [x] enable baked-in component analytics
- [x] Element: "See all events" link for a featured event
  - [x] remove custom events
  - [x] enable baked-in component analytics
- [x] Element: "See all events" link for a featured event
  - [x] remove custom events
  - [x] enable baked-in component analytics
- [ ] a11y review

**Comment by eselkin** [comment]
See all locations (verified just nav-link-click)
<img width="880" alt="Screenshot 2024-08-21 at 4 39 13 PM" src="https://github.com/user-attachments/assets/3037cd30-daca-463d-9eb6-10a21545e42c">

Refill and track
verified
<img width="878" alt="Screenshot 2024-08-21 at 4 40 14 PM" src="https://github.com/user-attachments/assets/c2f87bd8-8af0-4d8d-8239-963db78f99dd">

Download your VA Medical Records
<img width="878" alt="Screenshot 2024-08-21 at 4 40 14 PM" src="https://github.com/user-attachments/assets/394c402e-746e-450c-81ee-e9a1ceee629a">

Send a secure message
![Screenshot 2024-08-21 at 4 41 21 PM](https://github.com/user-attachments/assets/827db922-c8ab-451f-b2f9-48582c88fe68)

View your lab and test results
<img width="876" alt="Screenshot 2024-08-21 at 4 42 25 PM" src="https://github.com/user-attachments/assets/5a58de35-17f3-4264-9a38-a52f0db7dc36">

Schedule and manage health appointments
<img width="877" alt="Screenshot 2024-08-21 at 4 43 21 PM" src="https://github.com/user-attachments/assets/d3b82989-f209-431a-8120-f6b187a06f3f">

Order hearing aid batteries and accessories
![Screenshot 2024-08-21 at 4 44 15 PM](https://github.com/user-attachments/assets/69a69b3d-8f17-4810-9c69-c319236e3a8a)

Download VA Health Chat
<img width="879" alt="Screenshot 2024-08-21 at 4 45 03 PM" src="https://github.com/user-attachments/assets/71ce57c7-20bc-4f31-a13a-24e19d23c17e">

Connect to VA care
<img width="879" alt="Screenshot 2024-08-21 at 4 45 03 PM" src="https://github.com/user-attachments/assets/10687703-b011-4c87-957b-35e40c2f4563">

See all stories
![Screenshot 2024-08-21 at 4 46 29 PM](https://github.com/user-attachments/assets/b17e20f2-2d3a-4c87-bdf9-0212cbab24cd)

See all events (2x on the list, but 1x in the page)
<img width="879" alt="Screenshot 2024-08-21 at 4 47 10 PM" src="https://github.com/user-attachments/assets/078672bf-56d4-4ac2-89ca-92c3a0f5d7a7">

All verified in prod
