### ISSUE TITLE
[Analytics] [Navigation Links List] Custom GA events removal & web component upgrades

### ISSUE THREAD

**Issue by randimays** [department-of-veterans-affairs/va.gov-cms#18521]
## Status
**[2024-07-18] [Fran]** Reviewed today; implementing component, adopting baked in analytics, remove custom analytics. No duplicate events firing. Not urgent.

## Description
The va-link web component's analytics now include link destination, and va-link-action has been released to the component library. We can now use baked-in analytics and convert to web components where possible in links list navigation.

### Engineering notes
Some exploration will need to be done to discover where this file / sidebar is used and how it differs from the sidebars present on benefit hub detail pages.

Code: https://github.com/department-of-veterans-affairs/content-build/blob/2cfe33c456bd3fb3dfcb961d0e975d74fcbb904f/src/site/components/navigation-links-list.html#L49

### User story
**AS A PO/PM** managing Sitewide products & features
**I WANT** to (where appropriate) adopt the va-link or va-link-action component, its baked-in analytics, and remove the custom GA events
**SO THAT** extraneous code is removed and only the events needed will be triggered.

## Acceptance criteria
- [ ] Element: Navigation links list links
  - [ ] convert to web component
  - [ ] enable web component analytics
  - [ ] remove custom events
- [ ] a11y review

**Comment by chriskim2311** [comment]
Still looking for answers to if this is being used. Slack thread for more info: https://dsva.slack.com/archives/C52CL1PKQ/p1729796306070129

**Comment by jilladams** [comment]
From Slack: `detail-page.html` was all vagov-content and it's not in use anymore.

**Comment by jilladams** [comment]
Same here -- @FranECross @chriskim2311 I think we resolved this by removing the pages where the analytics events appeared. Is there anything required to do to close this? Or now that the removal is deployed, it can close?

**Comment by chriskim2311** [comment]
Closing with the release of the details page deprecation
