### ISSUE TITLE
[Analytics] [Merger crosslinks] Custom GA events removal & web component upgrades

### ISSUE THREAD

**Issue by randimays** [department-of-veterans-affairs/va.gov-cms#18523]
## Description
The va-link web component's analytics now include link destination, and va-link-action has been released to the component library. We can now use baked-in analytics and convert to web components where possible in merger crosslinks.

### Engineering notes
Some exploration will need to be done to discover where this file is used.

Code: https://github.com/department-of-veterans-affairs/content-build/blob/2cfe33c456bd3fb3dfcb961d0e975d74fcbb904f/src/site/components/merger-crosslinks.html#L38

### User story
**AS A PO/PM** managing Sitewide products & features
**I WANT** to (where appropriate) adopt the va-link or va-link-action component, its baked-in analytics, and remove the custom GA events
**SO THAT** extraneous code is removed and only the events needed will be triggered.

## Acceptance criteria
- [ ] Element: Merger cross links
  - [ ] remove custom events
  - [ ] upgrade to web component
- [ ] a11y review

**Comment by chriskim2311** [comment]
Code removal merged, closing!
