### ISSUE TITLE
[Analytics] [Health care widgets (CTAs)] Custom GA events removal & web component upgrades

### ISSUE THREAD

**Issue by randimays** [department-of-veterans-affairs/va.gov-cms#18538]
## Description
The va-link web component's analytics now include link destination, and va-link-action has been released to the component library. We can now use baked-in analytics on the CTAs for health care widgets.

Example page: https://www.va.gov/health-care/schedule-view-va-appointments (must be logged in to see the health care widget link for this ticket)

### Engineering notes
Code:
- https://github.com/department-of-veterans-affairs/vets-website/blob/d1c5684083334b52b1eb21a0bbb222aa5d53707f/src/applications/static-pages/health-care-manage-benefits/components/CernerCallToAction/index.js#L93
- https://github.com/department-of-veterans-affairs/vets-website/blob/d1c5684083334b52b1eb21a0bbb222aa5d53707f/src/applications/static-pages/health-care-manage-benefits/components/CernerCallToAction/index.js#L230

### User story
**AS A PO/PM** managing Sitewide products & features
**I WANT** to (where appropriate) adopt the va-link or va-link-action component, its baked-in analytics, and remove the custom GA events
**SO THAT** extraneous code is removed and only the events needed will be triggered.

## Acceptance criteria
- [ ] Element: "Go to My VA Health" link (appears when logged in)
  - [ ] remove custom events
  - [ ] convert to web component
- [ ] a11y review

**Comment by chriskim2311** [comment]
@Agile6MSkinner Hey! Wanted to know if you could possibly test this on prod for me to close if you have access? 

 https://www.va.gov/health-care/schedule-view-va-appointments

Inspect the Go to My VA Health link and take a screenshot of the HTML in the console?

**Comment by chriskim2311** [comment]
Found cerner accounts for testing. Closing!

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeWNEQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--35db1e110191c9f5cd2312b5b80d8caebf423310/Schedule_And_View_VA_Appointments_Online___Veterans_Affairs.png" alt="Schedule_And_View_VA_Appointments_Online___Veterans_Affairs.png" />
