### ISSUE TITLE
[Analytics] [Facility locator] Custom GA events removal & web component upgrades

### ISSUE THREAD

**Issue by randimays** [department-of-veterans-affairs/va.gov-cms#18536]
## Status
**[2024-07-18] [Fran]** Reviewed today; implementing component, adopting baked in analytics, remove custom analytics. No duplicate events firing. Not urgent.

## Description
The va-link web component's analytics now include link destination, and va-link-action has been released to the component library. We can now use baked-in analytics on the Facility locator.

Example page: https://www.va.gov/find-locations

### Engineering notes
Code:
- ~https://github.com/department-of-veterans-affairs/vets-website/blob/96aebeea59e203d6594ef9a5c52b0fb51d53f5fe/src/applications/facility-locator/components/search-results-items/VaFacilityResult.jsx#L20~ - 8/8/24 Determined not to be duplicated and will not be removed
- https://github.com/department-of-veterans-affairs/vets-website/blob/96aebeea59e203d6594ef9a5c52b0fb51d53f5fe/src/applications/facility-locator/components/search-results-items/Covid19Result.jsx#L35
- https://github.com/department-of-veterans-affairs/vets-website/blob/96aebeea59e203d6594ef9a5c52b0fb51d53f5fe/src/applications/facility-locator/components/search-results-items/Covid19Result.jsx#L38

### User story
**AS A PO/PM** managing Sitewide products & features
**I WANT** to (where appropriate) adopt the va-link or va-link-action component, its baked-in analytics, and remove the custom GA events
**SO THAT** extraneous code is removed and only the events needed will be triggered.

## Acceptance criteria
- [ ] Element: Search results links (Facility names)
  - [ ] remove custom events
  - [ ] convert to web components
  - [ ] enable component's baked-in analytics
- [ ] a11y review

**Comment by randimays** [comment]
Update: Some of the duplicate GA events in Facility Locator were caused by non-GA-related code functioning incorrectly. This includes basic storage of the results from the search. I made some adjustments to the non-GA-related code and the PR was posted earlier this week. When it was posted, there were 3 search endpoints that were not working in review instances (presumably because of some PPMS issue? I do not have the context here).

16th min scrum item for the 3 endpoints that weren't working: https://dsva.slack.com/lists/T03FECE8V/F079GFKN50D?record_id=Rec07H05PEGHJ

While we were waiting for deploys to happen to (maybe) fix those endpoints, review instances broke completely and have now been down for a couple days. Chris and Eli were able to test the PR locally but I need Laura's eyes on it since some code was changed and we need to be sure no a11y functionality went awry. She has not been able to get the code working locally, and the RI is still down.

**Comment by randimays** [comment]
@Agile6MSkinner @jilladams
Update: we got the review instance working and Laura and Jordan have reviewed and provided their feedback. I have a couple of questions resulting from that feedback:

1. We have a Google Analytics event that fires when pins are clicked on the map. In production this GA event only fires for search results of these facility types:
- VA health
- VA benefits
- VA cemeteries

For everything else in the dropdown, the pin click event is not recorded. I suspect this is a Michelle decision as to whether we want the GA event fired for every type of pin click, but based on the code ([context in this comment, #1](https://github.com/department-of-veterans-affairs/vets-website/pull/31273#issuecomment-2297315883)) it seems like it could be intentional to only include those 3 facility types.

If we decide to add it, we should cut a new ticket as this ticket's scope is for removing duplicate GA events, and this behavior is in production currently.

2. Similarly, we have a GA event that fires when a result from a search is clicked. 
- VA health
- VA benefits
- VA cemeteries

Other than vet centers, the facility types do not lead to clickable search results (e.g. urgent care just has locations, but the locations don't have their own page). For vet centers, we aren't firing a search result click event. Should we be?

Again, if we need to add it, it should be in a new ticket as the behavior is in production currently.

CC @laflannery @thejordanwood

**Comment by randimays** [comment]
Laura also spotted a defect with dragging the map view that exists in production. I tried solving this as part of this PR but I am stumped; it seems to be native JS behavior that I'm not sure we can work around. I created a defect ticket for it here: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18985. It may be kind of spike-y. I've spent a few hours investigating and wasn't able to make any headway so I'm not sure on points; I think it'd be good to get in front of other engineers / fresh eyes.

**Comment by randimays** [comment]
Update: The code for this was merged; I'll validate it in staging today, but I'll need some help from the team to validate it in production tomorrow (in the VW deploy), please.

**Comment by laflannery** [comment]
@jilladams and @Agile6MSkinner I tested all the items listed in the PR on Prod and confirmed they are working and not duplicated.

I'm not sure if the question above got answered yet so I don't know if I should close this in case we lose the follow up.

**Comment by jilladams** [comment]
We discussed briefly in product sync yesterday - I don't think we need to block closing this issue on it. 

Sync discussion was: 
* Michelle asked: what is my click through from search result to learn more/to where they are headed. If that's happening, then she might not care if they're clicking from a pin (might be valuable knowing where they are clicking from?)
* If click through isn't firing that should be fixed right away (Michael).

Product sync card: https://dsva.slack.com/archives/C07BVDGCY8H/p1724187234464369?thread_ts=1724098593.313969&cid=C07BVDGCY8H)

@Agile6MSkinner has the action item to follow up on this and create a new ticket to track addl work if it's necessary.

**Comment by jilladams** [comment]
(Closing, that in mind.)
