### ISSUE TITLE
[Web components] [Facility locator] Convert links to va-link where possible or update link text

### ISSUE THREAD

**Issue by randimays** [department-of-veterans-affairs/va.gov-cms#18537]
## Description

The facility locator app (in vets-website) has many links that can be converted to web components (`va-link`). For those links that cannot be converted (due to requiring new tab behavior), "(opens in a new tab)" should be added to the link text.

## Acceptance Criteria:

Converted to `va-link`:
- [VABenefitsCall.jsx#L9](https://github.com/department-of-veterans-affairs/vets-website/blob/41d713cad9c044207c96399c8073047e2fe3a3cc/src/applications/facility-locator/components/VABenefitsCall.jsx#L9)
   - https://va.gov/find-locations/facility/vba_344p 
- [OperationStatus.jsx#L13](https://github.com/department-of-veterans-affairs/vets-website/blob/41d713cad9c044207c96399c8073047e2fe3a3cc/src/applications/facility-locator/components/facility-details/OperationStatus.jsx#L13)
    - Can't find an NCA page with a status not NORMAL
- [OperationStatus.jsx#L19](https://github.com/department-of-veterans-affairs/vets-website/blob/41d713cad9c044207c96399c8073047e2fe3a3cc/src/applications/facility-locator/components/facility-details/OperationStatus.jsx#L19)
    - https://www.va.gov/find-locations/facility/vba_306j
- [Covid19Result.jsx#L45](https://github.com/department-of-veterans-affairs/vets-website/blob/41d713cad9c044207c96399c8073047e2fe3a3cc/src/applications/facility-locator/components/search-results-items/Covid19Result.jsx#L45)
   - We don't return COVID-19 results right now because we aren't using the data from the KISS JSON
- [VaFacilityResult.jsx#L37](https://github.com/department-of-veterans-affairs/vets-website/blob/41d713cad9c044207c96399c8073047e2fe3a3cc/src/applications/facility-locator/components/search-results-items/VaFacilityResult.jsx#L37)
    - [Result list](https://va.gov/find-locations/?address=Portland%2C%20OR&bounds%5B%5D%5B%5D=-75.4059945&bounds%5B%5D%5B%5D=39.3127492&bounds%5B%5D%5B%5D=-72.6059945&bounds%5B%5D%5B%5D=42.112749199999996&context=Portland%2C%20Oregon%2C%20United%20States&facilityType=benefits&latitude=45.52068&longitude=-122.6789&page=1&radius=38&serviceType&bounds%5B%5D=-124.0789&bounds%5B%5D=44.12068&bounds%5B%5D=-121.2789&bounds%5B%5D=46.92068) 
- [LocationDirectionsLink.jsx#L18](https://github.com/department-of-veterans-affairs/vets-website/blob/41d713cad9c044207c96399c8073047e2fe3a3cc/src/applications/facility-locator/components/search-results-items/common/LocationDirectionsLink.jsx#L18)
    - See above result list (any directions link on the results)
- [LocationInfoBlock.jsx#L34](https://github.com/department-of-veterans-affairs/vets-website/blob/41d713cad9c044207c96399c8073047e2fe3a3cc/src/applications/facility-locator/components/search-results-items/common/LocationInfoBlock.jsx#L34)
    - This is the facility name link in a result list as above (sometimes it is a Link and sometimes an anchor tag). The reason it is a Link sometimes is because facility details pages use react-router to route to the pages.
- [FacilityDetail.jsx#L74](https://github.com/department-of-veterans-affairs/vets-website/blob/41d713cad9c044207c96399c8073047e2fe3a3cc/src/applications/facility-locator/containers/FacilityDetail.jsx#L74)
    - https://va.gov/find-locations/facility/vba_344
- [ProviderDetail.jsx#L83](https://github.com/department-of-veterans-affairs/vets-website/blob/41d713cad9c044207c96399c8073047e2fe3a3cc/src/applications/facility-locator/containers/ProviderDetail.jsx#L83)
    - not used

Added "(opens in a new tab)" to the link text, and keep the `<a>` tag:

- [ProviderDetail.jsx#L75](https://github.com/department-of-veterans-affairs/vets-website/blob/41d713cad9c044207c96399c8073047e2fe3a3cc/src/applications/facility-locator/containers/ProviderDetail.jsx#L75)
    - not used 
- [ProviderDetail.jsx#L132](https://github.com/department-of-veterans-affairs/vets-website/blob/41d713cad9c044207c96399c8073047e2fe3a3cc/src/applications/facility-locator/containers/ProviderDetail.jsx#L132)
    - not used
- [UrgentCareAlert.jsx#L19](https://github.com/department-of-veterans-affairs/vets-website/blob/41d713cad9c044207c96399c8073047e2fe3a3cc/src/applications/facility-locator/containers/UrgentCareAlert.jsx#L19)
   - removed
## Considerations:
- Links opening in a new tab 
  - `va-link` does not support opening links in a new tab
  - If the link should open in a new tab per DST guidance (will otherwise result in loss of user data / progress), "(opens in a new tab)" should be added to the link text
- `va-link` analytics send the current URL, destination URL and the link text. If converting the link to a `va-link` makes the custom GA event duplicative, remove the custom GA event

### Quality / testing notes
- [ ] Relevant unit/e2e tests have been updated

**Comment by randimays** [comment]
@FranECross @Agile6MSkinner I noticed we had a bunch of links in facility locator that could be converted to `va-link` (or otherwise need an update). I'm not super familiar with the facility locator yet, so I don't have example URLs / "how to get there" instructions, so this ticket will need some refinement (in addition to user story / ACs). I estimated it at a 2 though because the changes are simple.

**Comment by eselkin** [comment]
In this [result list](https://va.gov/find-locations/?address=Portland%2C%20OR&bounds%5B%5D%5B%5D=-75.4059945&bounds%5B%5D%5B%5D=39.3127492&bounds%5B%5D%5B%5D=-72.6059945&bounds%5B%5D%5B%5D=42.112749199999996&context=Portland%2C%20Oregon%2C%20United%20States&facilityType=benefits&latitude=45.52068&longitude=-122.6789&page=1&radius=38&serviceType&bounds%5B%5D=-124.0789&bounds%5B%5D=44.12068&bounds%5B%5D=-121.2789&bounds%5B%5D=46.92068)

The result list titles (titles of the facilities) appear as h3 even though these classes are added `vads-u-font-size--h5 no-marg-top`... Right now, if you take that class off, it doesn't do anything (maybe because of the importance of some other sizes somewhere)

If you change the anchor tag (`<a>`) to a `va-link`, the font does shrink to the h5 size. Should we be showing them as h5-sized linked h3s?

@laflannery @thejordanwood

**Comment by laflannery** [comment]
@thejordanwood As I'm sure you know, I would very much prefer not doing this - I would rather just have H3 tags with default styles, but let me know if you disagree

**Comment by thejordanwood** [comment]
@eselkin @laflannery I agree with Laura, let's use H3 tags with the default styles.

**Comment by eselkin** [comment]
Slightly related, and just visual @thejordanwood 
The line height of a wrapped `<h3><a>text</a></h3>` is 1.5 (keeps the `a` tag line height)
but the wrapped `<h3><va-link text="text"></va-link><h3>` is 1.3 (keeps the `h3` line height)

Should I make the lineheight `4` (1.5) in-line with the `a` tag (there's no 1.3 line height only 1.35)?

**Comment by laflannery** [comment]
@eselkin to clarify, you are asking if you should add a custom `line-height` declaration on the new `<va-link>` component to match the current line height being used on the Facility names in the search results?

If that is correct, we should not - we want to avoid overwriting the DS styles unless there are there are drastic differences or very clear reasons why we need different styles. In this case the difference in line-height (1.5 vs. 1.3) is very slight and we should keep the default DS style

**Comment by thejordanwood** [comment]
@eselkin @laflannery I agree, we should use the default DS style. Sounds like that's 1.5 in this case?

**Comment by eselkin** [comment]
@laflannery @thejordanwood thanks, that's what I expected

**Comment by jilladams** [comment]
Deployed and ready to verify.
