### ISSUE TITLE
Moving Coronavirus-Chatbot to CMS

### ISSUE THREAD

**Issue by rumyeahs** [department-of-veterans-affairs/va.gov-cms#1859]
## *About this form*

*If you don't have the answer yet to some of the questions, that's fine!*

*A CMS team member will be in touch to schedule a meeting to review, within a few days of receiving it.*

*Questions? Go to #cms-support in Slack.*

----

## Your product team

**Who’s who on your product team? Provide a link to your team’s page on the CMS, or a general sense of the product owner and those responsible for it.**
This is for the Coronavirus-Chatbot ([https://www.va.gov/coronavirus-chatbot/])
Product Owner: Kaeli Yuen/ Ramya Ramesh
Architect: Mike Chelen/ Karl Brown

**Who are the primary stakeholders for the product?**
Kathleen Frisbee
Denise Kitts
Trisha Dang

**Which Slack channel on DSVA slack do you use to coordinate?**
#covid-19-chatbots

## Content audit / inventory

**Describe the purpose of the content you want to manage from the CMS.**
This is a veteran facing website, providing an interactive experience to the veterans for their frequently asked questions related to coronavirus. 
Currently the web page for chatbot is hosted in vagov-content at https://raw.githubusercontent.com/department-of-veterans-affairs/vagov-content/master/pages/coronavirus-chatbot.md 
Eventually this should be moved to Drupal content management system, so that the content editors can manage the content surrounding the chatbot widget.

**Does it already exist on another platform? Provide some links, to the source platform (like a markdown file) and/or to the front end.**
Currently the web page for chatbot is hosted in vagov-content at https://raw.githubusercontent.com/department-of-veterans-affairs/vagov-content/master/pages/coronavirus-chatbot.md 

**How many pages do you expect to manage from the CMS for your product?**
1 page

## Migration

**Do you expect to see some automated migration of content as part of your adoption of the CMS?** 
No automated migration. It will require manual migration. 

**If yes, what content do you expect to migrate?**
N/A

## Content ops & governance

**Who is responsible for writing and reviewing the content now?**
@DanielleThierryUSDSVA Is the content owner presently

**Are there external reviewers of the content?**
Yes, Danielle works with JTF and other reviewers to get necessary approvals. 

**Who will own this content in the future?**
@DanielleThierryUSDSVA and Kaeli Yuen 

**What is your existing editorial workflow, if any?**
The last updated date is manually updated whenever the chatbot content changes. The other content will be updated manually on an as needed basis. There is no automated way to update the content presently. 

**Will some of the content continue to have a “source of truth” outside the CMS? If yes, what aspect of it (for example: a dataset living in another database)?**
N/A

## Training and access to CMS

**Who will need access to CMS to edit?** 
The developers on the team: Shefali Nayak and Katie Ho. 

**Will they need training?**
Would like to have an overview of the process

## Product roadmap

**What’s your timeline for giving live OR for releasing the next iteration?**
The chatbot is currently live. In terms of migrating to CMS, there are no pressing time needs, but we would like to have it done sooner than later in order to keep it consistent with other veteran facing pages. 

**How do you expect the product to evolve, if at all, in the next:** 

- **Weeks (you should know this)** 
Regular content updates usually happen once a week, hence need to update the Last Updated Date on the page accordingly.

- **Months (you may know this)**
- **Years (you probably don’t know this, but if you had to guess…)**

## Next steps

**Provide some general times for the initial CMS discovery meeting.**
Early next week (Week of June 1) will work for the team

**Comment by jilladams** [comment]
Coronavirus chatbot has been retired, closing: 
https://dsva.slack.com/archives/C04KXPXL4/p1652807170031429
