### ISSUE TITLE
Create github issue template for coronavirus team to fill out

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#1862]
AC
- [ ] we have MVP for CMS discovery request issue template.

Review process
- [ ] Go to https://github.com/department-of-veterans-affairs/va.gov-cms/issues/new/choose and click CMS discovery
- [ ] Review first #1859 as the first use of it (Coronavirus team)
- [ ] Ask for feedback from various team members (Oksana)
- [ ] Ask for feedback from Platform experience team (kevin has asked Andrea Hewitt and Megan Kelly) 

Iteration will be done  on #1863, then we will announce this on Team of Teams and to our existing product teams.

**Comment by kevwalsh** [comment]
I made one small iteration since #1859 was submitted, based on feedback from Brauer: removing the migration questions, which we can infer from other questions already. Their original intent was to determine if we need migration engineers as part of discovery, but the earlier questions should be enough to determine that already.

**Comment by oksana-c** [comment]
opened https://github.com/department-of-veterans-affairs/va.gov-cms/pull/1907 w/ minor additions
