### ISSUE TITLE
CMS for managing dynamic covid-19 screening tool content for different VA facilities

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-cms#1865]
## *About this form*

*If you don't have the answer yet to some of the questions, that's fine!*

*A CMS team member will be in touch to schedule a meeting to review, within a few days of receiving it.*

*Questions? Go to #cms-support in Slack.*

----

## Your product team

**Who’s who on your product team?**

Charles Worthington, Chief Technology Officer
Lauren Alexanderson, OCTO health portfolio lead
Patrick Bateman, OCTO product lead 
Mike Chelen, Michelle Steigerwalt, Stephen Barrs, engineering
Jeff Barnes, research
Martha Wilkes, design
Danielle Thierry, content

**Who are the primary stakeholders for the product?**

Leadership at individual VAMCs 

**Which Slack channel on DSVA slack do you use to coordinate?**

#va-cto-covid-screener

## Content audit / inventory

**Describe the purpose of the content you want to manage from the CMS.**

This is a COVID-19 screening tool that consists of:
1) A welcome text message with link to the tool. The user receives this text by texting a keyword to a 5-digit number.
2) Intro text
3) A flow of questions (currently 5, soon to be 6 total, with a dynamic 6th question based on whether user is an employee or patient/caregiver)
4) Results screen (2 possible versions based on user's answers to questions)

We want to make the questions (# 3 in list above) easily customizable at multiple levels (ie, VAMC, facility) and accessed by a user through a common entry point.

Different VISNs/systems/facilities will want different levels of control. For example, one VISN might want to standardize across all facilities in the VISN (and have the buy-in to do so), whereas another VISN might leave it up to individual facilities to customize their own questions based on a default set. There are default national questions that should be used if there are not more specific questions.

[More information here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/51b97a7566a4f23cc819631026411bde24ccb359/products/health-care/COVID-screener/RFCs/customization-rfc.md#coivd-19-screener-customization-rfc)

**Does it already exist on another platform? Provide some links, to the source platform (like a markdown file) and/or to the front end.**

https://www.va.gov/covid19screen/

https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/coronavirus-screener/config/questions.jsx

**How many pages or pieces of content do you expect to manage from the CMS for your product?**

One set of tool questions

## Content ops & governance

**Who is responsible for writing and reviewing the content now?**

Our team (Danielle Thierry, content)

**Are there external reviewers of the content?**

No

**Who will own this content in the future?**

Local VAMCs or VISN area managers (tbd exactly), with editorial checks by this team.

**What is your existing editorial workflow, if any?**

Content in JSON file or tickets. First phase was very quick so we haven't established a specific editorial workflow. We're in the process of working out an interim solution of GH folders/files organized by VISN/facility.

**Will some of the content continue to have a “source of truth” outside the CMS? If yes, what aspect of it (for example: a dataset living in another database)?**

## Training and access to CMS

**Who will need access to CMS to edit?** 

Our team and possibly VAMC/VISN area managers (tbd).

**Will they need training?**

Yes.

## Product roadmap

**What’s your timeline for going live OR for releasing the next iteration?**

Tool is live, with ongoing iterations.

**How do you expect the product to evolve, if at all, in the next:** 

- **Weeks (you should know this)** We'll be rolling this out to more locations, with customized questions as needed.
- **Months (you may know this)** We'll be looking at ways to build upon this tool's features and capabilities to further help improve the Veteran's experience at VA health facilities. 
- **Years (you probably don’t know this, but if you had to guess…)**

## Next steps

**Provide some general times for the initial CMS discovery meeting.**

Week of June 1 would be great.

**Comment by kevwalsh** [comment]
Initial meeting set up for Sprint 9, followup work would happen in Sprint 10.
