### ISSUE TITLE
Evaluate viability of search via alpha health service list 

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-cms#18656]
## Description 
As of #12907, searches for VA health specifying a service selected from the existing service dropdown (and those using the default "All health services") are powered by Lighthouse v1 using Drupal as the source of truth. 

However, Lighthouse V1 (c/o CMS) contains data for over 90 service types which are not available as service types in the Facility Locator. We are not able to make searching for all of these possible given the current UX which presents a dropdown list of services. We intend to implement a new search experience but moving to a typeahead search is a larger effort than we can undertake at this time. We may need to implement a interim step to move us toward the goal. 

Additional context: until we get services aligned with Vet Center Outstations and VBA locations, we will not be able to offer a typeahead search evenly across facility types. We also need to make the VA service taxonomy more robust by filling gaps in fields such as common conditions to ensure a solid typeahead search experience. 

Jordan has initiated designs for the new search experience which include a page which support Veterans in choosing a service type from an alpha list of health services (similar to a Medicare.gov experience). 

This issue is to evaluate the viability and lift for creating this page as an interim way to offer the full list of health services. 

## Implementation considerations

- Design: [Facility Locator Figma file](https://www.figma.com/design/GvNVeG9GAXZaBpny7vNxZP/Facility-Locator?node-id=509-30097&t=FdkmqXS0BvPbbs9P-1)
- Design includes a search box for geographic location
- The selected health service would be used as the parameter in the Lighthouse query  
- The alphabet is sticky during the scroll.

**Comment by thejordanwood** [comment]
I updated the Figma link in the ticket. I created a new page in the Figma file for this idea so that we don't have to wade through all of the mockups on the working page.

[New Figma link](https://www.figma.com/design/GvNVeG9GAXZaBpny7vNxZP/Facility-Locator?node-id=509-30097&t=FdkmqXS0BvPbbs9P-1)

**Comment by Agile6MSkinner** [comment]
Closing per comment from @davidmpickett comment in #14993
