### ISSUE TITLE
Node links not working in campaign landing page

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-cms#18659]
## Describe the defect
On July 17th CAIA published a campaign landing page using node IDs for Drupal pages in the "What you can do" section. When the page published, the links in that section did not work but also didn't 404. They didn't navigate anywhere at all, instead "entity:node/[nodeID]" appeared in lower left corner of browser window.
CAIA had checked the links in the View tab in Drupal before publishing and they worked fine.
The links were updated to full URLs and republished. 

- CMS URL: [Drupal side: Prepare for VA’s secure sign-in changes - CLP](https://prod.cms.va.gov/initiatives/prepare-for-vas-secure-sign-in-changes)
- VA.gov URL: [Production CLP](https://www.va.gov/initiatives/prepare-for-vas-secure-sign-in-changes/)

## To Reproduce
1. Link a node ID in this component on a campaign landing page and then preview in Drupal
2. Observe the same weird "entity;node/nodeID" 

## AC / Expected behavior
Linked node IDs direct to the correct live VA.gov page or trigger a 403

## Screenshots

<details>
<summary> Seen in lower left browser when the link was clicked on the live page </summary>

<img width="472" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM1R4QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--31331468f358d0402a05e9b6484c786b859730f2/image.png" alt="image.png" />

</details>
 
<details>
<summary> Area of page with affected links </summary>

<img width="1434" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM1B4QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d1495d89f02673f7dae6358fae04bfbd7cdf1db9/image.png" alt="image.png" />

</details>

 ## Additional context
A similar issue was discovered and resolved in the Vet Center template: [Internal links on Vet Center Spotlights do not link correctly on the FE #17473](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17473)

Because it is likely that this issue is lurking elsewhere, the CMS team will perform an audit to identify other affected templates: [Audit internal link references across the CMS #18657](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17473)

**Comment by chriskim2311** [comment]
Confirmed on prod that the CLPs are working as expected and the data is flowing through graphQL with the changes from the PR. Closing!
