### ISSUE TITLE
[Research prep] Changing an answer to a Branching Question during Review flow

### ISSUE THREAD

**Issue by davidmpickett** [department-of-veterans-affairs/va.gov-cms#18660]
## Background

While working on [converting the Discharge Upgrade Wizard](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12043) from a single page experience to a [one-thing-per-page subtask flow](https://design.va.gov/patterns/help-users-to/complete-a-sub-task), we encountered a particular use case that required special attention:
- A user gets to the Review screen 
- Decides to edit a previous answer
- Changing this answer means that they have to now answer additional questions that weren't part of their original flow

[The solution we have proposed](https://www.figma.com/design/XHQAQ8ZDKKsDcXfBn5ulhh/Discharge-Upgrade-Wizard?node-id=150-5583&t=2lMhPApbElWMrM9T-1) is a conditional expandable alert that would be displayed to users who have returned to a branching question during the Review flow. 

<details><summary>Screenshot of design</summary>

![Mobile - subtask](https://github.com/user-attachments/assets/12ec56bc-3845-4058-a99f-5921e95c2118)

</details>

We are planning to[ have our FE engineers go forward with this pattern](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18405) so that the modernized DUW can launch. But before we implement this pattern on PACT Act Wizard (which also has branching logic) we want to verify it with users via usability testing. 

## Resources

- [Design System Pattern: Check Answers](https://design.va.gov/patterns/help-users-to/check-answers)
- [DUW Initiative Brief](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/veteran-military-records/discharge-upgrade-wizard/initiatives/2024-discharge-upgrade-wizard-subtask/initiative-brief.md)
- [DUW Figma](https://www.figma.com/design/XHQAQ8ZDKKsDcXfBn5ulhh/Discharge-Upgrade-Wizard?node-id=150-5869&t=2lMhPApbElWMrM9T-0)
- [Research Repository](https://github.com/department-of-veterans-affairs/va.gov-research-repository)
- [Slack thread](https://dsva.slack.com/archives/C52CL1PKQ/p1714591633627719) where this pattern was originally brainstormed

## Description

```[tasklist]
### Previous Research Synthesis
- [x] Review Research Repo for previous relevant research from other teams
- [ ] https://github.com/department-of-veterans-affairs/va.gov-research-repository/issues/110
- [ ] https://github.com/department-of-veterans-affairs/va.gov-research-repository/issues/143
- [ ] https://github.com/department-of-veterans-affairs/va.gov-research-repository/issues/192
- [ ] https://github.com/department-of-veterans-affairs/va.gov-research-repository/issues/212
- [ ] https://github.com/department-of-veterans-affairs/va.gov-research-repository/issues/385
- [ ] https://github.com/department-of-veterans-affairs/va.gov-research-repository/issues/219
- [ ] https://github.com/department-of-veterans-affairs/va.gov-research-repository/issues/154
- [ ] https://github.com/department-of-veterans-affairs/va.gov-research-repository/issues/359
- [x] Summarize findings from research review
- [x] Extract relevant findings from above studies (no need to do a book report on them)
```

```[tasklist]
### Relation to Jeana's work
- [x] Jordan will touch base with Jeana Clark who has been reviewing this pattern in a larger context
- [x] Jordan to summarize previous conversations to note known pain points / possible future directions / and maybe link to mural
```

```[tasklist]
### Acceptance Criteria
- [x] Synthesis of previous research and relation to Jeana's work is documented in draft Research plan (background section)
- [x] Subsequent research tickets are created
```

**Comment by davidmpickett** [comment]
@jilladams  Noting for Sprint reporting purposes that this ticket was not included in the Sprint 9 plan.  It was at the top of Ready. Jordan moved it to In Progress indicating an early start, but the majority of this work will be Sprint 10.

**Comment by jilladams** [comment]
@thejordanwood to follow up to create next step tickets.

**Comment by thejordanwood** [comment]
Veteran Facing Forms team update:

- The forms teams has more use cases with more complexity than our wizards do but we do share conditional logic where when one question is edited it may prompt additional questions that need to be answered.
- [This Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1717682397715/9fa45c5ed6119646a8bd192cde055ffdfc246731?sender=u01810f3edbfc878c08be5925) explores potential user flows the team were considering. 
- The team has [went through design intent](https://github.com/department-of-veterans-affairs/va.gov-team/issues/85443) and is starting to prepare for midpoint review. 
- This is [the latest Figma file](https://www.figma.com/design/kBH2U6bfC6sA9Fim3gcnuc/WIP---Review-Page---Edit-by-section?node-id=1-19&t=oAuy72ENFLnOB42S-11) their team is working on, but it's pretty sparse at the moment. 

[This is the Slack thread](https://dsva.slack.com/archives/C044AGZFG2W/p1723150198326189) where I reached out to Jeana to ask about their progress.

**Comment by aklausmeier** [comment]
@thejordanwood Let's continue to keep them in the loop and open up observer slots the Forms team when the time comes. 

> we do share conditional logic where when one question is edited it may prompt additional questions that need to be answered

**Comment by thejordanwood** [comment]
@aklausmeier The research synthesis is ready for your review! I put it in Sharepoint for now because I thought that would make it easier for you to comment on. I can add this into a research folder once approved. 

[DUW Research Synthesis](https://dvagov.sharepoint.com/:w:/s/SitewidePublicWebsites/EQUpdcxrBnlInP4VbQG4rkgBbGYART3ZJHqaDtb5U8iNKA?e=ufp0RO)

@davidmpickett has provided an initial review, but tagging him here so he can follow along.

**Comment by aklausmeier** [comment]
This is great @thejordanwood. Next step in order to call this ticket complete is to post as a `Secondary research` summary in the DUW research folder on GH.

**Comment by thejordanwood** [comment]
@aklausmeier Thanks! I added this secondary research summary to the DUW research folder. 

[Link to secondary research](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/veteran-military-records/discharge-upgrade-wizard/research/secondary-research.md)
