### ISSUE TITLE
[Discharge Upgrade Wizard] Update content on review screen

### ISSUE THREAD

**Issue by thejordanwood** [department-of-veterans-affairs/va.gov-cms#18697]
## Description
The current Discharge Review Screen displays the answers only. To align with the [income limits design](https://www.figma.com/design/BzNT78xb10l2P3fKtKirDI/Income-Limits?node-id=0-1&t=LhhNwLxohpueds4w-1), the review screen should include labels above the answers. The labels should reflect which questions were asked to add more context to the answers. 

## Relevant links

- [Discharge Upgrade Wizard Figma](https://www.figma.com/design/XHQAQ8ZDKKsDcXfBn5ulhh/Discharge-Upgrade-Wizard?node-id=150-5583&t=a18aijjBBG2FVMu7-1)
- [DUW Sharepoint doc with question copy](https://dvagov.sharepoint.com/:w:/r/sites/SitewidePublicWebsites/Shared%20Documents/Discharge%20Upgrade%20Wizard/DischargeUpgradeWizardContent.docx?d=we399b79e68ae41e282ae042f5a7da6f4&csf=1&web=1&e=uptSkP)
- [DUW PDF with question copy](https://github.com/user-attachments/files/16431562/DischargeUpgradeWizardContent.pdf)
- [Mural with logic flow](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1696352911500/80253b1c7200212cbcbcfb940d2cf4a29fed8417?sender=u01810f3edbfc878c08be5925)

## Acceptance criteria

- [x] Update artifacts with new review screen flow
- [x] Updated artifacts are reviewed with product and accessibility
- [x] Reviewed by UX sitewide lead 
- [x] Sent to VA UX lead for sign off 
- [ ] Tag PM to create follow up tickets

## Artifacts updated
- [Sharepoint spreadsheet with content](https://dvagov-my.sharepoint.com/:x:/g/personal/jordan_wood1_va_gov/EceDLfGfZxBCr9Yxb4ECa3kBeUwB32rSH0JRI0nJcXqIeA?e=e6j1ZJ)
- [Discharge Upgrade Wizard Figma](https://www.figma.com/design/XHQAQ8ZDKKsDcXfBn5ulhh/Discharge-Upgrade-Wizard?node-id=150-5583&t=a18aijjBBG2FVMu7-1)

**Comment by laflannery** [comment]
Unassigning myself until this is ready to be looked at

**Comment by thejordanwood** [comment]
@laflannery @aklausmeier @davidmpickett The content is ready for review. I put this in a Sharepoint spreadsheet to (hopefully) make it easier than trying to review content in Figma. 

[Sharepoint spreadsheet with content](https://dvagov-my.sharepoint.com/:x:/g/personal/jordan_wood1_va_gov/EceDLfGfZxBCr9Yxb4ECa3kBeUwB32rSH0JRI0nJcXqIeA?e=e6j1ZJ)

If you have trouble accessing it just let me know!

**Comment by laflannery** [comment]
@thejordanwood Most of these make sense to me. I wish we could make them shorter but o well. I did propose 2 edits, you will see them in the doc. Let me know if those make more sense. One of them I do think it works (adding the word "the") but the other I'm wondering if swapping the words actually changes the meaning of it a bit?

**Comment by aklausmeier** [comment]
I'm afraid adding "the" does change the meaning. 

Let's rephrase to include "was the" and closer mirror the original flow question. (line 8 in Sharepoint spreadsheet)

> Discharge was the outcome of a general court martial

No other concerns.

**Comment by thejordanwood** [comment]
Thanks for reviewing @aklausmeier and @laflannery! 

I've cleaned up the spreadsheet to show those edits as the final copy. I also tidied up the review page in the [Discharge Upgrade Wizard Figma file](https://www.figma.com/design/XHQAQ8ZDKKsDcXfBn5ulhh/Discharge-Upgrade-Wizard?node-id=150-5583&t=RWpxR1tw7LgLJtL9-1) so that Chris has a better example to refer to. 

I'll leave this ticket open to give Dave a chance to review once he gets back.

**Comment by davidmpickett** [comment]
Hey I just did a pass on the spreadsheet:
- I updated the column titles for better explain the context of the texts
- I added a column for possible responses so it's easier to get a full understanding of what the shortened question text would be pared with
- Fixed court-martial to align with [Content style guide](https://design.va.gov/content-style-guide/word-list#c)
- Added some comments to consider ways to shortening the question labels on review screen.

**Comment by davidmpickett** [comment]
@FranECross @mmiddaugh @aklausmeier - Best practice here would be to request CAIA review on the abbreviated question copy we're proposing for the review screen. I see that there's an open [CAIA intake request for Phase 2](https://github.com/department-of-veterans-affairs/va.gov-team/issues/71562), but I think this content technically falls under the purview of Phase 1? Wanted to get your thoughts on whether you want to take that step or are comfortable shipping this without CAIA review and adjustments can be made during their Phase 2 review if necessary.

**Comment by davidmpickett** [comment]
@FranECross @jilladams One of the ACs here says review with engineering, but this is just copy, there's no layout or logic change. Do we want to block closing on that?

**Comment by FranECross** [comment]
@davidmpickett No need to block closing. I'll delete that AC and will replace with "notify PM for inclusion in future engineering stories", which you just did. :)

**Comment by davidmpickett** [comment]
After checking in with @thejordanwood and @laflannery, I took ownership of this ticket and made some additional edits to shorten the question labels. These are highlighted in yellow on the spreadsheet (with previous copy preserved in a comment) if they or @aklausmeier want to take another peek before passing on 

Static copy of SharePoint spreadsheet for ease of access: 
[DUW Review page content 20240805.xlsx](https://github.com/user-attachments/files/16503558/DUW.Review.page.content.20240805.xlsx)

**Comment by aklausmeier** [comment]
@davidmpickett With the additional question label revisions, are we getting too far away from [content guidance (VADS and USWDS)](https://designsystem.digital.gov/patterns/complete-a-complex-form/keep-a-record/#guidance) by not restating original question and repeating verbiage? I wouldn't be opposed to taking this updated version to research and test a hypothesis that this more concise labeling is in favor of better UX.  

`Include a complete recap of all questions and their submitted answers.`

**Comment by davidmpickett** [comment]
> @davidmpickett With the additional question label revisions, are we getting too far away from [content guidance (VADS and USWDS)](https://designsystem.digital.gov/patterns/complete-a-complex-form/keep-a-record/#guidance) by not restating original question and repeating verbiage? I wouldn't be opposed to taking this updated version to research and test a hypothesis that this more concise labeling is in favor of better UX.
> 
> `Include a complete recap of all questions and their submitted answers.`

I think there is a distinction between [helping users to check answers](https://design.va.gov/patterns/help-users-to/check-answers) and [keeping a record of submitted information](https://design.va.gov/patterns/help-users-to/keep-a-record-of-submitted-information). For submittable forms, both apply, but since this is a "wizard" that doesn't submit the information anywhere, we're really just "helping users to check answers" rather than "keeping a record".

That being said, I definitely think this is another great reason for us to do usability testing and key research question to look at.
