### ISSUE TITLE
Update drupal core to v10.3.1

### ISSUE THREAD

**Issue by edmund-dunn** [department-of-veterans-affairs/va.gov-cms#18703]
## User Story or Problem Statement
Drupal core is now on v10.3.1. We need to update it.

## Description or Additional Context 
Additional packages in AC are dependent on core v10.3

## Order of Operations 
- Sprint 16: Update Drupal core for sitewide teams to review. 
- Sprint 17: Have sitewide Drupal developers spot check their products. No major review is needed, just a spot check that should only take sitewide developers an hour. 
- End of Sprint 17: Push Drupal core upgrade into production.

## Reference Links
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18072
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16898
- https://github.com/department-of-veterans-affairs/va.gov-cms/pull/16899
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15332

## Acceptance Criteria
- [x] `drupal/core-recommended` package update to 10.3.1 with all dependencies
- [x] `drupal/core-composer-scaffold` package updated to 10.3.1 with all dependencies
- [x] `drupal/twig_tweak` package update to v3.4
- [x] `drupal/animated_gif`package updated to v2.1
- [x] Sitewide developers review their products impacted by Drupal core upgrade.

**Comment by edmund-dunn** [comment]
@gracekretschmer-metrostar this should be a higher priority

**Comment by gracekretschmer-metrostar** [comment]
Next steps: Grace will preview this to sitewide teams this week. In the past, we have owned the PR and the sitewide teams have been reviewers.

**Comment by JakeBapple** [comment]
Two files in the most recent patch (found [here](https://www.drupal.org/project/drupal/issues/2893933)) that are being rejected:
/core/modules/system/tests/modules/cron_queue_test/src/Plugin/QueueWorker/CronQueueTestDatabaseDelayException.php 
/core/modules/system/tests/modules/cron_queue_test/src/Plugin/QueueWorker/CronQueueTestLeaseTime.php 

Need to fix those files in the patch and re-submit the patch back to the issue with the 10.3.x fix.

**Comment by JakeBapple** [comment]
Patch rerolled for the first two files [here](https://www.drupal.org/project/drupal/issues/2893933#comment-15725478) and uploaded for drupal community support.

**Comment by JakeBapple** [comment]
Patch rerolled for TextAreaWidget uploaded [here](https://www.drupal.org/project/drupal/issues/3229493) for drupal community.

**Comment by JakeBapple** [comment]
Patch re-rolled for role status and uploaded for drupal community [here](https://www.drupal.org/project/drupal/issues/2942404).

**Comment by JakeBapple** [comment]
Removed this patch (referenced [here](https://www.drupal.org/project/drupal/issues/3047110#comment-15496662)) as it has been reported "fixed" in core: "3047110 - Add workflow to taxonomy": "https://www.drupal.org/files/issues/2023-04-14/3047110-45.patch"

**Comment by JakeBapple** [comment]
Local patch not applying correctly: 3333401 - Pager h4 cause accessibility flag on many pages (patches/3333401-configurable-pager-heading-default-h2.patch). Many issues, all fixed in PR.

**Comment by JakeBapple** [comment]
Had to update https://www.drupal.org/project/eca to ^2.0.

**Comment by JakeBapple** [comment]
The PR is clearing tests and is ready for confirmation from other product teams that it is working for their interests. Waiting to merge based on feedback.

**Comment by omahane** [comment]
We found a visual regression in the taxonomy form: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19020

**Comment by gracekretschmer-metrostar** [comment]
@JakeBapple ^^^

**Comment by gracekretschmer-metrostar** [comment]
@omahane Christian we determined that https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19020 is not a visual regression, but a new feature, so we are not going to pick it up. 

cc: @edmund-dunn @JakeBapple @jilladams

**Comment by omahane** [comment]
> @omahane Christian we determined that #19020 is not a visual regression, but a new feature, so we are not going to pick it up.
> 

OK, I don't really understand the feature, but it was not a show-stopper either way.
