### ISSUE TITLE
Update memcache modules and reroll patch

### ISSUE THREAD

**Issue by edmund-dunn** [department-of-veterans-affairs/va.gov-cms#18705]
## User Story or Problem Statement
The memcache modules need to be updated to c2.6.0. The patch associated with the memcache module will need to be re-rolled.

## Description or Additional Context 
@edmund-dunn will add the patch location here. 

## Steps for Implementation
- Update module to c2.6.0
- Reroll the patch for the new module 
- Confirm that it applies cleanly (without error) by QAing a content type that uses dates. 

## Reference Links
- Look at Git blame to find the ticket from when the original patch was applied 
- https://www.drupal.org/node/3260965

## Acceptance Criteria
- [ ] `drupal/memcache` module updated to v2.6.0
- [ ] Patch at https://www.drupal.org/project/memcache/issues/3058121 rerolled and installs cleanly (without error)
- [ ] `drupal/memcache_admin` module updated to v2.6.0

**Comment by gracekretschmer-metrostar** [comment]
This work can be done in conjunction with this ticket: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18706

**Comment by anantais** [comment]
Patch is now working. Posting to Drupal.org and finishing ticket.
