### ISSUE TITLE
Update smart_date module and reroll patch

### ISSUE THREAD

**Issue by edmund-dunn** [department-of-veterans-affairs/va.gov-cms#18706]
## User Story or Problem Statement
The smart date module needs to be updated to v4.1.3, and the patch needs to be rerolled.

## Description or Additional Context 
Patch is locate at https://www.drupal.org/project/smart_date/issues/3260965

## Steps for Implementation
- Update module to v4.1.3 and then v4.1.5 (see [this ticket](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18994) for verification)
- Reroll the patch for the new module 
- Confirm that it applies cleanly (without error) by QAing a content type that uses dates. 
- Confirm that the drupal upgrade (ticket) does not negatively impacted 

## Reference Links
- Look at Git blame to find the ticket from when the original patch was applied 
- https://www.drupal.org/node/3260965

## Acceptance Criteria
- [ ] `drupal/smart_date' update to v4.1.3
- [ ] Patch at https://www.drupal.org/project/smart_date/issues/3260965 rerolled and applies cleanly (without error)
- [ ] Drupal upgrade ([ticket](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18703)) does not negatively impacted the module upgrade

**Comment by gracekretschmer-metrostar** [comment]
This work should be done in conjunction with this ticket: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18705

**Comment by anantais** [comment]
Finished #18075 and now working on this one again.
