### ISSUE TITLE
FE: Display Vet Center Banner Image on Facility Pages

### ISSUE THREAD

**Issue by Agile6MSkinner** [department-of-veterans-affairs/va.gov-cms#18711]
## Description
As a veteran who lands on a Vet Center facility page, I would like a VetCenter-specific banner imageto be prominently displayed at the top of the page so that I recognize it as something distinct from other VAMC facilities.

[Figma Designs](https://www.figma.com/design/EVd3q06ukAbVS61Q8MwRAT/Vet-Centers?node-id=971-3127&t=GrGP93DgGW1ElAzS-4)

Image will be added to Drupal in #18709

## Implementation Details
The interface for fetching the Vet Center banner image

will utilize GraphQL. The query will be configured to retrieve the necessary fields for displaying the logo appropriately across various device breakpoints.

Example GraphQL query configuration (DO NOT use this verbatim, we do not know what the field is yet and it may come in a different format due to Centralized Content):

```graphql
fieldVetCenterCCGraphic {
   entity {
        ... on MediaImage {
          image {
            alt
            title
            derivative(style: _32MEDIUMTHUMBNAIL) {
                url
                width
                height
            }
          }
        }
    }
}
```

```[tasklist]
### QA
- [ ] Accessibility Review
- [ ] Design Review
- [ ] Verify that image displays
- [ ] View on Desktop/tabet/mobile to verify breakpoints and resizing
```
## Acceptance Criteria
- [x] Create a GraphQL query to fetch the Vet Center banner image from the centralized content in Drupal.
- [x] Banner image is presented on Vet Center pages
- [x] Implement responsive breakpoints for the banner image
- [x] Follow all annotations in linked Figma designs

**Comment by eselkin** [comment]
The interface is the GraphQL, it will just add something for the field they wire up to say like:
```
fieldVetCenterCCGraphic {
   entity {
        ... on MediaImage {
          image {
            alt
            title
            derivative(style: _32MEDIUMTHUMBNAIL) {
                url
                width
                height
            }
          }
        }
}
```
or something, depending on the sizes/configuration.

**Comment by Agile6MSkinner** [comment]
Interesting point, @dsasser. @aklausmeier any thoughts on that?

**Comment by eselkin** [comment]
I put a caveat on the example GQL query.

**Comment by aklausmeier** [comment]
@Agile6MSkinner We have an exception to use the Vet Center logo by someone on the web governance board IF it becomes the final design. The design is still in iterations and the logo has potential to be revised to an image. In my view this ticket is blocked by design.

**Comment by randimays** [comment]
@Agile6MSkinner Should this be in the Ready column? Looks like it is still blocked by [the Drupal ticket](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18709).

**Comment by Agile6MSkinner** [comment]
It has been refined, so the story is ready, but it has a dependency that's listed: 
![image](https://github.com/user-attachments/assets/cfecf61d-f9c9-48ae-86e6-b125802f3945)

**Comment by eselkin** [comment]
Will wait on determination of image status for Monday

**Comment by laflannery** [comment]
@eselkin the image annotations have been finalized. The image will be contextual and I have added the approved alt text into Drupal already

**Comment by jilladams** [comment]
From planning: 
* Image is still in Vet Center centralized Content
* FE will hard code, referencing that image
* Michelle isn't concerned about confusing Natl staff, as they are not likely to try and edit the image.
* We can leave it this way for now and iterate in future if needed.

**Comment by davidmpickett** [comment]
Verified on prod: https://www.va.gov/evanston-vet-center/
