### ISSUE TITLE
In the spotlight heading

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-cms#18729]
## Description
The heading for the "In the spotlight" section on facility pages includes the facility name, which can be quite unwieldy for long names, especially those which honor an individual or include the colocation. Because it is a heading, it is also used as a jumplink which becomes wrapped for several lines.

In the spotlight is present on 

- Vet Center main pages
- Regional office main page
- VAMC health services page
- ~VAMC system home page (not a header/no jumplink)~

Could the heading be simply "In the spotlight"? 

## Screenshot examples

<details>
<summary> In the spotlight section </summary>

<img width="818" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeGdHQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a0ae6f15a8f4562788f87b31efc6b07383657e73/image.png" alt="image.png" />

<img width="737" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeVFHQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a8200b5954f34134041b1e82bbc4be39bab5841a/image.png" alt="image.png" />

<img width="767" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeWdHQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--82b67e30c9cd8fadc1bee548baeb41fc33496971/image.png" alt="image.png" />

</details>

<details>
<summary> as a jumplink </summary>

<img width="429" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeG9HQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9e1a39929faad7b6ae8102910c49fa976a41c448/image.png" alt="image.png" />

</details>

## Acceptance criteria
- [ ]  All spotlight headings for Vet Center main pages have the text (only) "In the spotlight", and is still a jumplink
- [ ] All spotlight headings for Regional office main pages say "In the spotlight", and is still a jumplink
- [ ] All spotlight headings for VAMC health services page say "In the spotlight", and is still a jumplink
- [ ] ~All spotlight headings for VAMC system home pages say "In the spotlight" **_Question: should this be a jumplink? The note in the description indicates it's not a header or jumplink._**~ separate issue, discussion here: https://dsva.slack.com/archives/C06S9DADEUB/p1721831113922919

**Comment by eselkin** [comment]
Verified on
https://www.va.gov/boston-health-care/health-services/
https://www.va.gov/portland-va-regional-benefit-office/
and 
https://www.va.gov/boston-vet-center/
