### ISSUE TITLE
[Discharge Upgrade Wizard] [FE] Update content and placement of text telling Veterans they may apply online or download a form; update to DD Form 293

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-cms#18722]
## Description

Our stakeholder, Joshua Gibbs, has alerted us that Veterans may not only download the form (DoD) Form 293, but they may also fill it out online and submit it.

See the Acceptance Criteria below for the changes necessary.

### User story

**AS A** Veteran looking at their results screen, specifically guidance for submitting DD Form 293 (currently the page shows DD Form 149) information on the guidance page in the Discharge Upgrade Wizard
**I WANT** to know that I can not only mail a completed form, but also submit the form online
**SO THAT** if I'm able to do this online to expedite the request, I may proceed to submit it online

### Steps to Reproduce

Steps to Reproduce getting to the Guidance screen:

Go to the Discharge Upgrade Wizard here: https://www.va.gov/discharge-upgrade-instructions/
- Click the Get started link
- **Question**: In which branch of service did you serve? 
  - **Answer**: Air Force
- **Question**: What year were you discharged? 
  - **Answer**: (I don't think it matters, but I used 2012)
- **Question**: Which of the following best describes why you want to change your discharge paperwork? Choose the one that's closest to your situation. 
  - **Answer**: I suffered from an undiagnosed, misdiagnosed, or untreated mental health condition, including posttraumatic stress disorder (PTSD), while in the service. I was discharged for reasons related to this condition.
- **Question**: Do you want to change your name, discharge date, or anything written in the "other remarks" section of your DD214? 
  - **Answer**: No, I want to change only my characterization of discharge, re-enlistment code, separation code, and/or narrative reason for discharge.
- **Question**: Was your discharge the outcome of a general court-martial? 
  - **Answer**: I'm not sure.
- **Question**: Have you previously applied for and been denied a discharge upgrade for this period of service? 
  - **Answer**: No.
- **Question**: Did you complete a period of Service in which your character of service was Honorable or General Under Honorable Conditions? 
  - **Answer**: No, I did not complete an earlier prior of service.
- Click Get my result link

### Changing instances of Form 149 to Form 293 for Air Force results screens (Question: is there more than one results screen to implement this one?)
- [ ] The first paragraph form number is changed from DoD Form 149 to DD Form 293
  - [ ] Based on your answers, you need to complete Department of Defense DD Form 293 and send it to the Air Force Review Boards Agency (AFDRB) for the Air Force.
- [ ] Item #1 header/title. and sub-title is changed from DoD Form 149 to DD Form 293; and from Form 149 to Form 293 respectively
  - [ ] Main title: Download and fill out DD Form 293,
  - [ ] Sub-title: Important tips for completing Form 293
- [ ] The following text just under the title is deleted (it was specific to Form 149 and not applicable to Form 293)
  - [ ] Pay special attention to item 6, which asks for the reason for your change. Most Veterans attach additional pages to answer this question.
For discharges related to PTSD or other mental health conditions, be sure to answer these questions to make the strongest case:
Did you have a condition that may explain or contribute to the discharge?
Did that condition start or get worse during your military service?
Why does the condition directly explain or contribute to the discharge?
Why does the condition carry more weight than any other reasons you may have been discharged for?
Item 8 asks for the date when you discovered the error or injustice you’re asking the Board to address. If it’s been more than 3 years since you found this error or injustice, you’ll need to include a reason why the Board should consider your application. Examples of good reasons include new evidence you’ve found to support your claim, or recent changes in policy (like liberal consideration for PTSD, TBI, or military sexual assault or harassment). These kinds of reasons will make it more likely for the Board to decide in your favor. The 3-year time limit isn’t a strict rule, so don’t let it keep you from applying if you think you have a strong case.
- [ ] last bullet item under the text above that starts with "Item 10", should be changed to "Item 17"
- [ ] the link just under this bullet "Download Form 149 (opens in a new tab), should be changed to "Download Form 293 (opens in a new tab).
  - [ ] the underlying hyperlink should be for DDForm 293: https://www.esd.whs.mil/portals/54/documents/dd/forms/dd/dd0293.pdf
  - [ ] Joshua Gibbs @gibbsjd has performed UAT
  - [ ] a11y review
 
###  Implementing Option 1 as per the screenshot below (see the Figma design; link above) informing users they can submit the form online, as well as mail it in

- [ ] Updated per the Figma design
- [ ] Joshua Gibbs @gibbsjd has performed UAT
- [ ] a11y review

<img width="583" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM29DQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--11e1a84aa48330159f9808165deec7e02783d9bb/image.png" alt="image.png" />

**Comment by chriskim2311** [comment]
@gibbsjd @FranECross Question: Do you know if this is only for Air Force discharges or all branches of the military?

**Comment by gibbsjd** [comment]
@chriskim2311 as of now only the Air Force.  The other branches have not updated their websites yet.

**Comment by chriskim2311** [comment]
@gibbsjd Thank you. Also for the `Submit your application online(opens in a new tab)` link in step 3 is this the correct URL https://afrba-portal.cce.af.mil/#board-info/drb/navbar ?

**Comment by gibbsjd** [comment]
@chriskim2311 no this is the correct link https://afrba-portal.cce.af.mil/#application-submission-drb

**Comment by chriskim2311** [comment]
@gibbsjd Got it thanks!

Lastly, for the AC `The following text just under the title is deleted (it was specific to Form 149 and not applicable to Form 293)`. We want to remove the item 6 and 8 references. I see they actually don't apply to the correct item for the other Form 149 either. Should I remove or update the item numbers for them? Not sure if you had dates when these forms were changed but seems like this information is no longer correct.

**Comment by gibbsjd** [comment]
@chriskim2311 you are correct item 6 and 8 are no longer valid and may be removed. Item 10 had been moved to item 17 on the new form and statement is still valid.

**Comment by chriskim2311** [comment]
Thanks! @gibbsjd I have changes done locally that you can approve then I can get this code reviewed and merged. Let me know if you find any issues with the changes.

<img width="848" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeFVQQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4c5db6b971d6a297658fd3d4160f8ac41d1b3dc5/How_To_Apply_For_A_Discharge_Upgrade___Veterans_Affairs.png" alt="How_To_Apply_For_A_Discharge_Upgrade___Veterans_Affairs.png" />

<img width="845" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeFlQQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--944125bcd07c9a0e6a3aa93b3a65729664cff9e3/How_To_Apply_For_A_Discharge_Upgrade___Veterans_Affairs.png" alt="How_To_Apply_For_A_Discharge_Upgrade___Veterans_Affairs.png" />

**Comment by gibbsjd** [comment]
Hello, @chriskim2311 for some reason it is not allowing me to view pictures. Can you email them to joshua.gibbs@va.gov

**Comment by gibbsjd** [comment]
@chriskim2311 thanks for sending screen shots. They are good with one correction. (AFDRB) = stands for "Air Force Discharge Review Board" not Air Force Review Boards Agency. 

The mailing address is perfect in the screen shot please do not change.

**Comment by FranECross** [comment]
@gibbsjd Thanks so much for the quick reviews and turnaround! We appreciate your collaboration very much.

**Comment by gibbsjd** [comment]
@FranECross @chriskim2311 Thank you both for assisting so quickly. I appreciate your hard work.

**Comment by chriskim2311** [comment]
@gibbsjd The changes have been merged and deployed to prod. Can you verify the changes and we can close the ticket thanks!

**Comment by gibbsjd** [comment]
Thank you all for your hard work and requested updates are correct. You may close the ticket. @chriskim2311 @FranECross

**Comment by FranECross** [comment]
Wonderful, @gibbsjd . Thanks for the amazing collaboration and your patience while she scheduled the work. We appreciate you!
