### ISSUE TITLE
Drupal: Add "Mission Explainer" Content Block to VetCenter Centralized Content

### ISSUE THREAD

**Issue by Agile6MSkinner** [department-of-veterans-affairs/va.gov-cms#18723]
### User Story
As a content manager, I want to add a blue information box to Vet Center pages with editable content in Drupal so that I can provide consistent information across all Vet Centers.

### Description
Add content blocks to VetCenter centralized content. The copy for the box will be editable in Drupal, but it will be the same for all Vet Centers.

### Draft content for blue box
Content will be revised by CAIA, but first draft from https://github.com/department-of-veterans-affairs/va.gov-team/issues/83961#issuecomment-2250545705 is: 

Title: Our services
Body: 
We offer these confidential services at our Vet Centers:
* Mental health counseling and a range of other social and mental health services
* Referrals to a VA medical clinic or community provider for medication and other services
* Connections to more support in VA and your community

**Note:** You may be eligible for these services no matter your discharge status or eligibility for VA health care. And we won't share anything about you or the services you receive at a Vet Center without your permission.

```[tasklist]
### ACs:
- [ ] 1. Add centralized content descriptor content block to VetCenter Centralized Content
- [ ] 2. Add "Rich text - char limit 1000" content block to VetCenter Centralized Content
- [ ] 4. Content block is populated with the following copy: @aklausmeier  to provide the draft content
- [ ] 5. Content block shows on node:edit and node:view(if low LOE) on VetCenter Content Type
```

```[tasklist]
### QA
- [ ] Content block is editable by user with appropriate permissions on VetCenter centralized content.
- [ ] Content block is not editable on VetCenter content type
```

```[tasklist]
### Review
- [ ] Design review in PR environment for Helptext / field labels, etc., before merge
```

**Comment by Agile6MSkinner** [comment]
@omahane @dsasser mind taking a look at this and validating?

**Comment by Agile6MSkinner** [comment]
@aklausmeier @thejordanwood In order to get this across the line we need final copy for the blue summary box at the top of the VetCenter facility pages.

**Comment by aklausmeier** [comment]
@Agile6MSkinner This will be blocked until CAIA provides revised content for blue summary box in the related [CAIA ticket #83961](https://github.com/department-of-veterans-affairs/va.gov-team/issues/83961). 

@thejordanwood @davidmpickett We could go ahead and provide this request to CAIA. I wouldn't expect any additional stakeholder feedback on this area. If we do we can always make additional minor tweaks.

**Comment by davidmpickett** [comment]
Update from convo with @aklausmeier she is going to own making som revisions to the content and then providing copy to CAIA for their review.

**Comment by aklausmeier** [comment]
**Draft copy below sent to CAIA, revisions are expected.** For context, how this appears in [Figma design](https://www.figma.com/design/EVd3q06ukAbVS61Q8MwRAT/Vet-Centers?node-id=814-7288&t=NBWgKRSGj2LN5mAk-1). 

Our services 

We offer these confidential services at our Vet Centers: 

- Counseling and a range of other services for individuals, families, and group sessions 
- Alternative therapies and events may be offered such as art, equine, yoga, or fly fishing 
- Connections to more support in VA and your community 

Note: You may be eligible for these services no matter your discharge status or eligibility for VA health care. And we won’t share anything about you or the services you receive at a Vet Center without your permission. 


cc @Agile6MSkinner

**Comment by jilladams** [comment]
@jv-agile6 I added an AC to this ticket to have Jordan (or Dave) take a look at your implementation in Tugboat, once it's in PR / before you merge. Many times we would have a design for the UI. In this case we didn't go that route, so we want to make sure that UX has eyes on it before we merge, for any feedback / changes. 

cc @thejordanwood @Agile6MSkinner  (based on thread with Amanda in Slack [here](https://dsva.slack.com/archives/C0FQSS30V/p1722373776820719))

**Comment by jv-agile6** [comment]
After much discussion the AC ojn this ticket has changed. 

- "2. Add "Rich text - char limit 1000" content block to VetCenter Centralized Content" is no longer a requirement for acceptance.

- A title field is an added requirement in addition to the rich text field with no character limit.

Discussions flushed out previous paragraph type - magichead_group that meets these requirements. I have added this paragraph block to the Vet Content Center on production.
<img width="1014" alt="Screenshot 2024-08-07 at 9 14 15 AM" src="https://github.com/user-attachments/assets/21184520-9a27-4ab9-bfa7-e5564f779ad0">

**Comment by jv-agile6** [comment]
Error when running ddev pull va --skip-files
<img width="1361" alt="Screenshot 2024-08-08 at 9 37 57 AM" src="https://github.com/user
<img width="1361" alt="Screenshot 2024-08-08 at 9 59 21 AM" src="https://github.com/user-attachments/assets/5a20d211-841b-42e5-a190-7280eb966038">
-attachments/assets/3598726f-09c7-44d2-b89b-656d8a4eea0f">

**Comment by jilladams** [comment]
@jv-agile6 just noting that while Christian is out this week, @davidmpickett can help with any questions about the content / Drupal config side or clarify what you need to do with his feedback if you have questions, and @dsasser is your man for any Qs on the Pull request itself, CI test issues, etc.

**Comment by jilladams** [comment]
@jv-agile6 looks like this deployed today and is now live in prod.

**On Centralized Content: Vet Centers**
https://prod.cms.va.gov/node/16142/edit

![Screenshot 2024-08-16 at 2 44 38 PM](https://github.com/user-attachments/assets/1ccdf1e8-2883-45ef-915d-411d9fbb7524)

**On a Vet Center node:**
e.g. https://prod.cms.va.gov/node/3788/edit

![Screenshot 2024-08-16 at 2 40 26 PM](https://github.com/user-attachments/assets/3e10b8ae-994e-4361-af2f-f1c4e4755692)

Noting: Copy in these screenshots differs from ACs on the ticket, due to feedback from Dave in the PR review. I did verify that placements in prod and copy match the PR feedback. If anyone has concerns about that, they can now make changes directly in the Production Centralized Content node. Closing!
