### ISSUE TITLE
Aging Content Notifications are not being sent

### ISSUE THREAD

**Issue by dsasser** [department-of-veterans-affairs/va.gov-cms#18721]
## Description
Aging Content notifications are not being sent.

### User story
**AS A** content editor
**I WANT** to receive aging content notifications
**SO THAT** I can keep content updated on va.gov

### Engineering notes / background
Original https://dsva.slack.com/archives/C52CL1PKQ/p1721742731928869 conversation.

## Acceptance criteria
- [x] Emails are sent at midnight daily for expire and warn FWB notifications.

**Comment by dsasser** [comment]
## Status Update 7/31/24

I identified a bug in the ECA logic for calculating when a cron event should fire and [discussed](https://drupal.slack.com/archives/C0287U62CSG/p1722376083228729) this with the ECA slack community. The module maintainer has suggested they are going to start working on it and requested a formal Drupal issue, which I [created](https://www.drupal.org/project/eca/issues/3465031).

In the interim, I am working on workaround for the issue by merging the existing ECA models, which should buy us some time (until we need to trigger off of cron for some other ECA thing).

**Comment by dsasser** [comment]
## End of Sprint Update 8/6/24

Work is in PR pending review.

**Comment by jilladams** [comment]
@dsasser is there a way to verify this other than checking if Randi Hecht received mail?

**Comment by dsasser** [comment]
> @dsasser is there a way to verify this other than checking if Randi Hecht received mail?

Yes we can look at the Aging Content queue here: https://prod.cms.va.gov/admin/config/system/queues/jobs/aging_content

![Screenshot 2024-08-09 at 1 59 29 PM](https://github.com/user-attachments/assets/ab5143cf-1591-4683-8ce2-dae5f8221ec3)

At the moment the queue ^ is showing that one email has gone out.

**Comment by jilladams** [comment]
Nice! That sounds like we can close. Doing so, but feel free to reopen if I'm missing something.

**Comment by jilladams** [comment]
Did ping Randi to verify here: https://dsva.slack.com/archives/C01K37HRUAH/p1723240486010319
