### ISSUE TITLE
Add "recent content i've edited" listing to user profile page. 

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#1873]
## Problem

People want to find content they're actively working on quickly.  

## Hypothesis

By placing actively worked on content on a user profile page, users will be able to edit the content they need immediately after logging in, with just one click. 

## Long-term context

We'll be developing these user profiles page as dashboards.

## Ideas

* "Temporary dashboard"
  * Borrow the "Recent activities" pattern from the node view page, showing Title of node, latest editor (even if it wasn't user), last revision log message, moderation state, date. 
  
## Acceptance criteria

- [ ] the block with recent content is rendered in the user profile page based on the available prototype - https://xd.adobe.com/view/9f94e624-9803-44f7-b799-5059e55796d1-cac7/screen/6b41da4e-852b-415a-b54a-df23184d4ff2?fullscreen
- [ ] users always see the latest content they've edited
- [ ] the view does not slow down user profile page load - login performance test is passing
- [ ] Coordinate Announcement with @rachel-kauff https://github.com/department-of-veterans-affairs/va.gov-cms/issues/4176 
   - Slack thread w/ announcement https://dsva.slack.com/archives/CT4GZBM8F/p1613583575276600?thread_ts=1613583550.276500&cid=CT4GZBM8F 

## Implementation

* Create a view, place on page using method from the Section listings
* Writing labels
* Internal feedback 
* Any small iteration
* @jordana to provide svg file for the lock icon
* lock icon is just an icon, not linked to anything
* view block has a distinct name e.g. `block_user_recent_content`

## Prototype 

https://xd.adobe.com/view/9f94e624-9803-44f7-b799-5059e55796d1-cac7/?fullscreen

**Comment by ethanteague** [comment]
@swirtSJW and I were talking about this task, @oksana-c - caching isn't really feasible for this block in it's current format. We need to limit the amount of data that is being returned. At present, there is no time or content limit restriction on the table. So, if a user made a revision two years ago, and someone else made a new revision this am, that content would show up on the top of the user table. We should figure out some reasonable limits before working out caching.

**Comment by oksana-c** [comment]
the need for "recently edited content" view was resurfaced by @davidconlon

**Comment by msbtterswrth** [comment]
We could leverage the existing 'recent content' block from core and add it to the profile pages as seen below.  There are a few things we could do to improve usability, such as:

- adding a 'view more' button that links out to a paginated page
- adding another layer of filter for most recent revision only
- 'lazy loading' more items

![image](https://user-images.githubusercontent.com/8375335/153061502-a86397fc-ca29-4ff4-aa68-82c3163f0cfe.png)

**Comment by rachel-kauff** [comment]
I think this needs more consideration to make sure we're doing something that provides value to users. The recent content table in those old initial prototypes had more columns for a reason (such as state, owner, and who last edited it, timestamp). This is also part of a user profile/dashboard idea that should be considered holistically.

**Comment by EWashb** [comment]
This is not currently within scope. At some point we could consider a user profile/dashboard for users to understand their workflows, but not currently prioritized.
