### ISSUE TITLE
[VA Benefit Taxonomy] [Drupal] Prevent reciprocal Entity references for Pre-Requisite Benefits on VA Benefits Taxonomy terms

### ISSUE THREAD

**Issue by davidmpickett** [department-of-veterans-affairs/va.gov-cms#18731]
## Status
**[2024-07-31] [Fran]** Asked Daniel [via Slack](https://dsva.slack.com/archives/C03LFSPGV16/p1722461629618799) to async refine.

## User Story or Problem Statement

AS AN Editor of the VA Benefit Taxonomy
I NEED a safeguard to prevent the possibility of indicating a benefit relationship that is impossible in the real world

- It is currently possible to have two Benefit terms list each other as Pre-Requisites
- This does not make sense in a real-world  benefit context, so should be prevented in Drupal

```mermaid
flowchart TB 
    X[houseboundAllowance] -->|field_va_benefit_prerequisite| Y[veteransPension]
    Y -->|field_va_benefit_prerequisite| X
    style X fill:#f2938c
    style Y fill:#f2938c    
```

## Examples: Valid Pre-requisite relationships

These are from [18165](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18165#issuecomment-2214455744)

### Model: Pre-requisite benefits
```mermaid
flowchart TB
    subgraph AB [Actual benefits]
    direction LR
        A(Benefit 1) -->|is a pre-requisite for| B(Benefit 2)
    end
    subgraph DE [Drupal entities]
    direction RL
    C[Term2] -->|field_va_benefit_prerequisite| D[Term1]
    style A fill:#00bde3,color:#fff
    style B fill:#00bde3,color:#fff
    style C fill:#f2938c
    style D fill:#f2938c
    end
    AB ~~~ DE
```

### Example: VA health care
- A single benefit can be a prerequisite for multiple other benefits 
```mermaid
flowchart TB
    subgraph AB [Actual benefits]
    direction LR
        A(VA health care) -->|is a pre-requisite for| B(VA dental care)
        A -->|is a pre-requisite for| Z(VA vision care)
    end
    subgraph DE [Drupal entities]
    direction RL
    C[DentalCare] -->|field_va_benefit_prerequisite| D[healthcare]
    Y[VisionCare] -->|field_va_benefit_prerequisite| D
    style A fill:#00bde3,color:#fff
style B fill:#00bde3,color:#fff
style Z fill:#00bde3,color:#fff
style C fill:#f2938c
    style D fill:#f2938c
    style Y fill:#f2938c
    end
    AB ~~~ DE
```

### Counter Example: Housebound allowance
- A single benefit can have multiple (possible) prerequisites
- Current model does not specify when/how prerequisites apply
```mermaid
flowchart TB
    subgraph AB [Actual benefits]
    direction LR
        A(Veterans Pension) -->|is a pre-requisite for| B(Housebound allowance)
        C(VA Survivors Pension) -->|is a pre-requisite for| B
    end
    subgraph DE [Drupal entities]
    direction RL
    X[houseboundAllowance] -->|field_va_benefit_prerequisite| Y[veteransPension]
    X -->|field_va_benefit_prerequisite| Z[survivorsPension]
    style A fill:#00bde3,color:#fff
style B fill:#00bde3,color:#fff
style C fill:#00bde3,color:#fff
style X fill:#f2938c
    style Y fill:#f2938c
    style Z fill:#f2938c    
    end
    AB ~~~ DE
```

## Proposed steps for Implementation
- Probably need to add a way for a Term to have awareness of Terms that are referencing it as Pre-requisite as a first step.
- Add validation to prevent saving `Term1` if it lists as Pre-Requisite a `Term2` which already lists `Term1` as Pre-requisite
   - Needs error message review
   - Save validation is a stable and reliable
   - Not the best UX since an editor won't know they've done something wrong until they finish the rest of the form
- AND/OR Winnow options for field_va_benefit_prerequisite to remove Terms that list the current term as field_va_benefit_prerequisite
   - Way better UX (prevents error rather than helps user recover from error)
   - Winnowing uses javascript (i think) and can be flakier than save validation
   - Might need to still have save validation in addition

## Acceptance Criteria
- [ ] It is no longer possible to save a VA Benefit Taxonomy term with a reciprocal pre-requisite reference to another term 
- [ ] No regressions to current VA Benefit Taxonomy functionality
- [ ] Requires design review?
- [ ] Requires accessibility review?

**Comment by davidmpickett** [comment]
@dsasser @mmiddaugh @FranECross I took a first pass at drafting up this Drupal implementation ticket. Might need a little tweaking in the tasks and ACs, but pretty confident that the basic story is there.

**Comment by dsasser** [comment]
## Engineering Pre-Refinement

Point estimate: 1 (Using the below solution)

We can achieve this using existing contrib module (already in use in the site), Entity Reference Validators. Below shows the configuration options for the pre-requisite field that the module provides:

<img width="487" alt="Screenshot 2024-08-07 at 2 23 32 PM" src="https://github.com/user-attachments/assets/aeeb1058-83cf-4e6a-995d-4bd0149bad1e">

And this is the result when the constraint is triggered:

<img width="672" alt="Screenshot 2024-08-07 at 2 42 50 PM" src="https://github.com/user-attachments/assets/fc6616a4-d3e7-433d-9afa-fdc7bb76403d">

**Comment by jv-agile6** [comment]
Created branch VACMS-18731-PreventReciprocal-EntityReferences-PreRequisiteBenefits-VABenefitsTaxonomyTerms

**Comment by jv-agile6** [comment]
Reviewing Entity Reference Validators configuration for VA Benefit Taxonomy

**Comment by jilladams** [comment]
Not ready for PR, hoping to get it up today.

**Comment by jv-agile6** [comment]
reference validators set to prevent circular references at admin/structure/taxonomy/manage/va_benefits_taxonomy/overview/fields/taxonomy_term.va_benefits_taxonomy.field_va_benefit_prerequisite

**Comment by jv-agile6** [comment]
Reached out to @dsasser to confirm this meets the AC. Awaiting response.

**Comment by jv-agile6** [comment]
[PR](https://github.com/department-of-veterans-affairs/va.gov-cms/pull/19511) is in draft awaiting the uid with user_role for QA requirement. In theory this could be merged today.

**Comment by jilladams** [comment]
@jv-agile6 here's an example user you can use for testing in lower envs - https://prod.cms.va.gov/user/1341.  This person will be one of the main people modifying this taxonomy.

**Comment by jilladams** [comment]
This should have deployed awhile ago now, but I'm not certain how to validate in production without modifying prod data. Thus: I'm going to close with confidence that we got it right based on lower environment testing from engineering. I'll own any blowback if we find follow up required.
