### ISSUE TITLE
URL Change for: Hinesville VA Clinic -> John Gibson, Dan James, William Sapp, and Frankie Smiley VA Clinic

### ISSUE THREAD

**Issue by ian-sears** [department-of-veterans-affairs/va.gov-cms#18741]
Parent ticket: #18740

### Implementation date
When does this request need to be live:
ASAP

### Instructions for URL redirect
(Note: This issue will be used from initial request through implementation to ensure all individuals working on this are notified of status updates.  Please do not create multiple issues to track different steps.)
- [x] Notify VA stakeholders as appropriate.
- [x] Link the related facility closure / rename issue.
- [x] Create a URL redirect in the [vsp-platform-revproxy](https://github.com/department-of-veterans-affairs/vsp-platform-revproxy) repo in `template-rendering/revproxy-vagov/vars/redirects.yml`
- [x] Add the "Awaiting redirect" flag to the facility node with a revision log message that includes a link to this ticket, preserving the node's current moderation state.
- [x] Redirects deploy daily except Friday at 10am ET, or by requesting OOB deploy (of the revproxy job to prod) in #vfs-platform-support. After deploy, validate that the URL redirect is deployed. (Note: In the event of a facility closure or a name change,  validate that this occurs before making the Lighthouse csv changes.)
- [x] Update this ticket with a comment that the redirect has been deployed.
- [x] Remove the "Awaiting redirect" flag on the facility node with a revision log message that includes a link to this ticket, preserving the node's current moderation state.
- [x] Notify helpdesk via comment on ticket or Slack message in #cms-support that changes are ready for review.

#### URL Redirect
| Current URL  |  Redirect Destination or New URL |
| ---  |  --- |
| `https://www.va.gov/charleston-health-care/locations/hinesville-va-clinic` | `https://www.va.gov/charleston-health-care/locations/john-gibson-dan-james-william-sapp-and-frankie-smiley-va-clinic` |

### 1. Canonical URL change

**Note: Canonical URL changes do not block the completion of the parent ticket. Once the URL redirect above has been deployed, the value to the Veteran is delivered. This ticket should be kept open until the URL change is verified, except in the case of a removal (as described below).**

### Instructions for canonical URL change
- [x] Verify that the new URL for the facility is published and accessible on VA.gov.
- [x] Contact Lighthouse via Slack at #cms-lighthouse channel that this facility requires a canonical link in the following format (replacing the placeholder data with the actual API Id and VA.gov URL):
  - `vha_534GE,https://www.va.gov/charleston-health-care/locations/john-gibson-dan-james-william-sapp-and-frankie-smiley-va-clinic/`
- [x] Add the "Awaiting CSV" flag to the facility node with a revision log message that includes a link to this ticket.
- [x] Let Help desk know this has been done, if not done by Help desk.

#### Wait (days or weeks, potentially)
- [x] After the canonical link has been added to the websites.csv and you have confirmation from Lighthouse that the CSV has been deployed, validate that the change has deployed by checking that the Facility Locator has been updated with the new url.
- [x] Update this ticket with a comment that the CSV change has been deployed.

#### URL change example (update with actual ID and URL)
| Facility API ID  |  Full VA.gov URL |
| ---  |  --- |
| vha_534GE | `https://www.va.gov/charleston-health-care/locations/john-gibson-dan-james-william-sapp-and-frankie-smiley-va-clinic` |

**Comment by ian-sears** [comment]
@omahane @mmiddaugh Please consider that I (me) made up the new URL to be changed to (logical). Please alert us at the CMS Help Desk if the new url that I devised is incorrect or requires modification so we can update our tickets for consistencey. This is, to me, and unusual VA CLinic name (thus url). Respectfully -Ian
@TroyCMSSupport fysa

**Comment by ian-sears** [comment]
@omahane This might have become overlooked? 
I made up the hyphenated url above, so please look at that and consider if correct? 
If it is... I think a Redirect needs to be made soonest possible to get this caugfht up. Was this not a high-profile/priority to turn around?
@TroyCMSSupport fysa

**Comment by omahane** [comment]
Name changes are not as high as closures. The facility doesn't move. It can move this sprint as without any issue..

**Comment by ian-sears** [comment]
@omahane Thanks. 
1. Is the mad-up-hyphenated url above there, correct? I assume I guessed correctly and everyone is (will be) good with it.
2. Should we initiate work to do a Redirect from Hinesville to this new url

**Comment by omahane** [comment]
> Is the made-up-hyphenated url above there, correct? I assume I guessed correctly and everyone is (will be) good with it.
I am going to test by going to https://staging.cms.va.gov/node/1344/edit and saving it after checking "Generate automatic URL alias". 

After saving, it was 
`https://staging.cms.va.gov/charleston-health-care/locations/john-gibson-dan-james-william-sapp-and-frankie-smiley-va-clinic`
which means that the VA.gov link will follow that
`https://va.gov/charleston-health-care/locations/john-gibson-dan-james-william-sapp-and-frankie-smiley-va-clinic`

**Comment by ian-sears** [comment]
Understood. My question was, rather, is everyone ok with me having turned "names" into a long, hyphenated, string of words.
Disregard. I'm going to assume this is fine (the only way it would work, anyway. Thank you for your test, though.

Are you intiating a redirect from the hinesburg url to the new long hyphenated new url?

**Comment by omahane** [comment]
The redirect has been deployed.

**Comment by ian-sears** [comment]
Awaiting csv. https://dsva.slack.com/archives/C02BTJTDFTN/p1725022775557719?thread_ts=1724374109.823729&cid=C02BTJTDFTN
node flag is now set to Awaiting CSV.

**Comment by ian-sears** [comment]
CSV change has been deployed.
