### ISSUE TITLE
Non-www NCA teamsite (cem.va.gov) not correctly loading injected header fonts

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#18756]
https://dsva.slack.com/archives/C52CL1PKQ/p1721927778370739?thread_ts=1721927672.794809&amp;cid=C52CL1PKQ

cem.va.gov does not correctly load Header/ footer fonts after the injected header work in #17291 
www.cem.va.gov does

CORS issue: 
![National_Cemetery_Administration](https://github.com/user-attachments/assets/dcdc4903-cc43-4b10-af3f-c13ba5e913f8)

 filed an ask to platform here to help us get it fixed: https://dsva.slack.com/archives/CBU0KDSB1/p1721936700782519

## ACs

- [ ] cem.va.gov correctly loads header fonts

**Comment by jilladams** [comment]
There's no work we can actually do here in code -- it's all getting help from Platform on the CORS fix, verifying, and then making sure Danielle / Michelle know in order to do comms with NCA as needed. Assigned both me and Randi, for that reason.

**Comment by randimays** [comment]
Ben Allen on the Platform team did some background devops work to help resolve this:

> FYI, for future reference within devops/terraform/dsva-vagov-prod I had to do a terraform apply -target='module.vets-api.module.va-gov'

Slack thread for context: https://dsva.slack.com/archives/CBU0KDSB1/p1722273995260569?thread_ts=1721936700.782519&cid=CBU0KDSB1

I tested across regular and private browsers on desktop and mobile this morning and confirmed the fonts are loading properly. Whoo-hoo!
