### ISSUE TITLE
[Analytics] [Dupe GA Events] Remove duplicate cta-button-click when the login modal is opened through 'Create account'

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-cms#18767]
## Description

Duplicate event(s) on FE Home Page identified and listed in (Randi's) this [spreadsheet](https://docs.google.com/spreadsheets/d/1fDsRQct_QMJ5nd3bTRDgwrfbFo_PqzdFQqYecJouic8/edit?gid=0#gid=0) needs to be removed.

For this ticket, line item 33 identifies the following Element as having a duplicate event that should be removed.

#### Element: When login modal is opened through "Create account"
- **Event name:** cta-button-click
- **Other event data:** "button-type: primary button-click-label: ""Create account"""
- **Example URL:** https://www.va.gov/

#### Element with custom events: When login modal is opened through "Create account"
- **Event name:** homepage-create-account
- **Other event data:** action: "Create account"
- **Example URL**: "https://www.va.gov/

### User story

**AS A** PO/PM of sitewide products
**I WANT** all duplicate events removed from our product's code
**SO THAT** we aren't charged by Google Analytics twice for the 'same' event

## Acceptance criteria
- [ ] Duplicate event listed in description was removed

**Comment by randimays** [comment]
This was taken care of in https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18416, [PR here](https://github.com/department-of-veterans-affairs/content-build/pull/2202). Closing as a dupe
