### ISSUE TITLE
[Bug] Income Limits Automated Workflow is Failing

### ISSUE THREAD

**Issue by dsasser** [department-of-veterans-affairs/va.gov-cms#18775]
## Status
**[2024-07-30] [Fran]** Ticket moved to Next Refinement and tagged with Sprint 10.

## Description
The monthly income limits Github workflow failing:

```
/usr/local/bundle/gems/ruby-oci8-2.2.13/lib/oci8lib_330.so: [BUG] Segmentation fault at 0x000079683475d398
ruby 3.3.3 (2024-06-12 revision f1c7b6f435) [x86_64-linux]
```

https://github.com/department-of-veterans-affairs/vets-api/actions/runs/10127679953

### Engineering notes / background
Possible red herring, but I noted that the Oracle client libraries on previous successful runs was using version ruby-oci8-2.2.12, but this run is using ruby-oci8-2.2.13.

## Acceptance criteria
```[tasklist]
### ACs
- [ ] Income limits workflow runs successfully
```

**Comment by jilladams** [comment]
Defect as timebox investigation = 3.

**Comment by jilladams** [comment]
No op, it's working now. 🙃
