### ISSUE TITLE
[Analytics] [Dupe GA Events] Remove duplicate GA event 'vba-regional-facility-services-manage-benefits-online' from FE VBA Facility pages

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-cms#18786]
## Description

The duplicate event(s) on **FE VBA Facility** pages identified and listed on line 61 in Randi's [spreadsheet](https://docs.google.com/spreadsheets/d/1fDsRQct_QMJ5nd3bTRDgwrfbFo_PqzdFQqYecJouic8/edit?gid=0#gid=0) needs to be removed.

#### Element:  Disability compensation accordion; "Learn how to manage disability compensation benefits online" link
- **Event name:** vba-regional-facility-services-manage-benefits-online 
- **Other event data: "**vba-regional-facility-name: {facility name} 
link-label: Find a VA benefits location
accordion-parent-label: {accordion title}"
- **Example URL:** https://web-2pegzvqcy77ynmcultaityqtlrpfbfoo.demo.cms.va.gov/honolulu-va-regional-benefit-office-at-spark-m-matsunaga-department-of-veterans-affairs-medical-center/

#### Element: Email contacts link
- **Event name:** vba-regional-facility-service-location-email-address
- **Other event data:** "vba-regional-facility-name: {facility name} accordion-parent-label: {accordion label} link-label: {email address}"
- **Example URL:** Not sure of a Tugboat example for this

#### Element: "Schedule an appointment online" link
- **Event name:** vba-regional-facility-service-location-schedule-appointment
- **Other event data:** "vba-regional-facility-name: {facility name} accordion-parent-label: {accordion label} link-label: Schedule an appointment online"
- **Example URL:** Not sure of a Tugboat example for this

### User story

**AS A** PO/PM of sitewide products
**I WANT** all duplicate events removed from our product's code
**SO THAT** we aren't charged by Google Analytics twice for the 'same' event

## Acceptance criteria

- [ ] Duplicate event listed in description was removed

**Comment by randimays** [comment]
The custom events `vba-regional-facility-service-location-email-address` and `vba-regional-facility-service-location-schedule-appointment` no longer exist anywhere in the code and must have been removed at some point. The event called `vba-regional-facility-services-manage-benefits-online` still exists and will be removed as part of this ticket.

**Comment by randimays** [comment]
@FranECross Forgot to add here that this was pulled in as stretch for sprint 9.

**Comment by randimays** [comment]
Validated successfully in production. Closing as complete!
