### ISSUE TITLE
[Analytics] [Dupe GA Events] Remove duplicate GA event on element 'VA benefits hotline link' on the FE page VBA Facility pages

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-cms#18785]
## Description

The duplicate event(s) on FE page VBA Facility identified and listed on line 59 in Randi's [spreadsheet](https://docs.google.com/spreadsheets/d/1fDsRQct_QMJ5nd3bTRDgwrfbFo_PqzdFQqYecJouic8/edit?gid=0#gid=0) needs to be removed.

#### Element: VA benefits hotline link
- **Event name:** vba-regional-facility-vba-facility-va-benefits-online
- **Other event data:** "vba-regional-facility-name: {facility name} link-label: VA benefits hotline"
- **Example URL:** /philadelphia-va-regional-benefit-office/ (duplicate event on top of baked-in component analytics)

### User story

**AS A** PO/PM of sitewide products
**I WANT** all duplicate events removed from our product's code
**SO THAT** we aren't charged by Google Analytics twice for the 'same' event

## Acceptance criteria

- [x] Duplicate event listed in description was removed

**Comment by randimays** [comment]
@FranECross Forgot to add here that this was pulled in as stretch for sprint 9.

**Comment by randimays** [comment]
Validated successfully in production. Closing as complete!
