### ISSUE TITLE
[Events] Filters: Custom date range error validation cause layout display issue

### ISSUE THREAD

**Issue by aklausmeier** [department-of-veterans-affairs/va.gov-cms#18780]
## Status
**[2024-07-30] [Fran]** Moved to Next Refinement; added AC; tagged for Sprint 10.

## Describe the defect
When using the Custom date range filters, entering an incorrect year produces red error bars that overlap the day input field causing a layout issue that is unexpected behavior.

## To Reproduce
1. Go to https://www.va.gov/outreach-and-events/events/
2. Click on Filter by: Choose custom date
3. Submit filter with an incorrect year, I used "8"
9. Filter shows red error bar overlapping day input box, mismatch of design system date input component 

## Expected behavior
Any validation error bars match design system component behavior, currently the red bars overlap date input field. 

## Screenshots
![Screenshot 2024-07-30 at 12 54 23 PM](https://github.com/user-attachments/assets/0c074f12-2256-4ae5-addc-073da44e4ce4)

## Eng notes
* Filters are generated in vets-website, so we can fix this without needing to worry about AP templates, as far as we are aware. (Doesn't impact content build)
* The event listing _results_ of the filter are in content-build. So if fixing this does end up requiring content-build work, we need to make sure to update AP as well, to keep them in sync.

### Acceptance Criteria
- [ ] Red error bar no longer overlaps day input box

**Comment by aklausmeier** [comment]
@FranECross @Agile6MSkinner discovered this defect while reviewing prod vs. AP events templates, bug is now in both templates, once we determine fix we need to update AP team if they have not yet handed off Events template to ensure it's been corrected in current and AP template versions

**Comment by FranECross** [comment]
Thanks, @aklausmeier ! I moved to Next Refinement, added AC and tagged for Sprint 10.

**Comment by aklausmeier** [comment]
Thanks!

**Comment by jilladams** [comment]
From refinement: 
* Filters are generated in vets-website, so we can fix this without needing to worry about AP templates, as far as we are aware. (Doesn't impact content build)
* The event listing _results_ of the filter are in content-build. So if fixing this does end up requiring content-build work, we need to make sure to update AP as well, to keep them in sync.

**Comment by randimays** [comment]
I went to the design system component docs for this web component: https://design.va.gov/storybook/?path=/docs/components-va-date--docs and I was able to reproduce the style error there.

<img width="700" alt="Screenshot 2024-07-31 at 11 33 02 AM" src="https://github.com/user-attachments/assets/9d9fa3d2-00a8-4678-a14b-2ac885d13d78">

I think we're good to close this ticket as a no-op because we won't be making any changes in the FE to fix this.

**Comment by aklausmeier** [comment]
Thank you @randimays! Closing since the work in now in a DST bug ticket [#3113](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3113). 
cc @laflannery
