### ISSUE TITLE
[Analytics] [Dupe GA Events] Remove duplicate GA event 'covid-status' from FE COVID status alert

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-cms#18789]
## Description

The duplicate event(s) on FE **COVID status alert** identified and listed on line 85 in Randi's [spreadsheet](https://docs.google.com/spreadsheets/d/1fDsRQct_QMJ5nd3bTRDgwrfbFo_PqzdFQqYecJouic8/edit?gid=0#gid=0) needs to be removed.

#### Element: COVID alert (event fires when alert is expanded)
- **Event name:** covid-status
- **Other event data:** "covid-status-entity-id: {entity ID} and covid-status-heading: {field status ID}"
- **Example URL:** Not sure of a prod example for this, but it is a duplicate event on top of baked-in analytics

### User story

**AS A** PO/PM of sitewide products
**I WANT** all duplicate events removed from our product's code
**SO THAT** we aren't charged by Google Analytics twice for the 'same' event

## Acceptance criteria

- [ ] Duplicate event listed in description was removed

**Comment by randimays** [comment]
Pulling in as stretch

**Comment by randimays** [comment]
Per [this Slack conversation](https://dsva.slack.com/archives/C52CL1PKQ/p1721405539358189?thread_ts=1721339395.211529&cid=C52CL1PKQ), we aren't using the COVID status alert anymore. [Epic for complete removal](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13673). This Drupal template must've been some cruft we missed when removing the implementation elsewhere. Will be removing the template for this ticket.

**Comment by randimays** [comment]
The code changes have deployed to production successfully. Since we're deleting a template that wasn't used anywhere, passing CI is the most testing we can do. Closing as complete!
