### ISSUE TITLE
[Analytics] [Dupe GA Events] Remove duplicate GA event int-modal-click on FE Homepage redesign modal (inactive)

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-cms#18798]
## Description

The duplicate event(s) on the **Homepage redesign modal (inactive)** identified and listed on line 147 in Randi's [spreadsheet](https://docs.google.com/spreadsheets/d/1fDsRQct_QMJ5nd3bTRDgwrfbFo_PqzdFQqYecJouic8/edit?gid=0#gid=0) needs to be removed.

#### Element: (When modal is open) clicking the close button
- **Event name:** int-modal-click
- **Other event data:** 
  - "modal-status: ""closed""
  - modal-title: ""Try our new VA.gov homepage"""
- **Example URL:** No prod examples as this is not currently in use

#### Element: (When modal is open) clicking the secondary button ("Not today, go to the current homepage")
- **Event name:** cta-button-click
- **Other event data:** 
  - "button-type: ""secondary""
  - button-click-label: ""Not today, go to the current homepage"""
- **Example URL:** No prod examples as this is not currently in use

### User story

**AS A** PO/PM of sitewide products
**I WANT** all duplicate events removed from our product's code
**SO THAT** we aren't charged by Google Analytics twice for the 'same' event

## Acceptance criteria

- [ ] Duplicate event listed in description was removed

**Comment by randimays** [comment]
Pulling in as stretch for sprint 9

**Comment by randimays** [comment]
This has successfully deployed to production. Since this modal is not in use, there's nothing to test in the prod environment. Closing as complete!
