### ISSUE TITLE
[Analytics] [Dupe GA Events] Remove duplicate GA event 'view_search_results' on FE Resources & Support search

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-cms#18792]
## Status
**[2024-09-10] [Fran]** Ticket unblocked; moved to Ready.
**[2024-09-03] [Fran]** PW Ticket (in QA/Code Review) [here](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18846).
**[2024-08-07] [Fran]** This ticket is blocked because the va-search-input web component (that homepage search uses) does not make use of the disable-analytics prop that we'd want to use here (to lean on our custom event instead). The prop applies to the component, but the baked-in event still fires.

We have a DST issue open for this issue and agreed to contribute to their repo to fix it with https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18846, but it is moving slowly due to local dev issues and after it is merged will still require a release on DST's end to be available.

## Description

The duplicate event(s) for the FE **Resources & Support Search** identified and listed on line 139 in Randi's [spreadsheet](https://docs.google.com/spreadsheets/d/1fDsRQct_QMJ5nd3bTRDgwrfbFo_PqzdFQqYecJouic8/edit?gid=0#gid=0) needs to be removed.

#### Element: (Searching) when search button is clicked
- **Event name**: view_search_results
- **Other event data:** 
  - "search-page-path: {current URL}
  - search-query: {query}
  - search-results-total-count: undefined
  - search-results-total-pages: undefined
  - search-selection: ""All VA.gov""
  - search-typeahead-enabled: false
  - search-location: ""Resources and Support""
  - sitewide-search-app-used: false
  - type-ahead-option-keyword-selected: undefined
  - type-ahead-option-position: undefined
  - type-ahead-options-list: undefined
  - type-ahead-options-count: undefined "
- **Example URL**: https://www.va.gov/resources/

#### Element: (Search Results) When result title is clicked (example: "Compare VA education benefits")
- **Event name:** onsite-search-results-click
- **Other event data:** 
  - "search-page-path: {current URL}
  - search-query: {query}
  - search-result-chosen-page-url: {result's destination}
  - search-result-chosen-title: {title of result}
  - search-results-pagination-current-page: {page number}
  - search-results-position: {position in the results}
  - search-results-top-recommendation: undefined
  - search-results-total-count: {total # of results}
  - search-results-total-pages: {total pages}
  - search-result-type: ""title""
  - search-selection: ""Resources and support"""
- **Example URL:** https://www.va.gov/resources/search/?query=benefits

### User story

**AS A** PO/PM of sitewide products
**I WANT** all duplicate events removed from our product's code
**SO THAT** we aren't charged by Google Analytics twice for the 'same' event

## Acceptance criteria

- [ ] Duplicate event listed in description was removed

**Comment by randimays** [comment]
Didn't catch this in refinement. This ticket is blocked because the `va-search-input` web component (that Resources & Support search uses) does not make use of the `disable-analytics` prop that we'd want to use here (to lean on our custom event instead). The prop applies to the component, but the baked-in event still fires. 

We have a DST issue open for this issue and agreed to contribute to their repo to fix it with #18846, but it is moving slowly due to local dev issues and after it is merged will still require a release on DST's end to be available.

This ticket is unlikely to be unblocked this sprint.

**Comment by chriskim2311** [comment]
Verified on prod, closing!
