### ISSUE TITLE
[Analytics] [Dupe GA Events] Remove duplicate GA event events-impossible-date-range on FE Events search

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-cms#18796]
## Description

The duplicate event(s) on FE **Events search** identified and listed on line 144 in Randi's [spreadsheet](https://docs.google.com/spreadsheets/d/1fDsRQct_QMJ5nd3bTRDgwrfbFo_PqzdFQqYecJouic8/edit?gid=0#gid=0) needs to be removed.

#### Element: Filtering by Custom date range and clicking "Apply filter" (Impossible date range is entered)
- **Event name:** events-impossible-date-range
- **Other event data:** 
  - "filter-by: {filter}
  - filters-list: {list}"
- **Example URL:** https://www.va.gov/outreach-and-events/events/

~#### Element: Filtering by Custom date range and clicking "Apply filter" (Valid date entered)~
~- **Event name:** events-apply-filter-clicked~
~- **Other event data:** ~
  ~- "filter-by: {filter}~
  ~- filters-list: {list}"~
~- **Example URL:** https://www.va.gov/outreach-and-events/events/~

#### Element: Filtering by Custom date range and clicking "Apply filter" (Apply filter fails because some inputs are missing)
- **Event name:** events-apply-filter-failed
- **Other event data:** 
  - "filter-by: {filter}
  - filters-list: {list}"
- **Example URL:** https://www.va.gov/outreach-and-events/events/

### User story

**AS A** PO/PM of sitewide products
**I WANT** all duplicate events removed from our product's code
**SO THAT** we aren't charged by Google Analytics twice for the 'same' event

## Acceptance criteria

- [ ] Duplicate event listed in description was removed

**Comment by randimays** [comment]
Updated the description to strike out `events-apply-filter-clicked`; it was removed between the time the spreadsheet was created and me picking up this ticket.

@FranECross I learned yesterday that form components (e.g. dropdowns, text inputs, etc.) are opt in for analytics (to avoid PHI/PII being captured). Two questions in bold below:

When I...
- go to https://www.va.gov/outreach-and-events/events
- filter by `Custom date range`
- enter an invalid date range on events filtering
- click "Apply filter"
 
...I get two events: one is for clicking the "Apply filter" button and the other is for the invalid date range. **Should we keep both events?**

<details><summary>Screenshot of events</summary>
<img width="559" alt="Screenshot 2024-08-07 at 1 40 53 PM" src="https://github.com/user-attachments/assets/28969102-4da8-43bc-9020-e22130ab8e60">
</details>

Similar situation when you filter by custom date range and don't fill out the fields, then click "Apply filter." You get a click event for the "Apply filter" button and the event for an empty filter. **Should we keep both events?**

<details><summary>Screenshot of events</summary>
<img width="565" alt="Screenshot 2024-08-07 at 1 44 39 PM" src="https://github.com/user-attachments/assets/e0061296-96b1-4ef3-b267-3c47cd9c133e">
</details>

**Comment by FranECross** [comment]
@randimays Thanks for the research and info! I don't believe we need the event for the invalid date range.

**Comment by randimays** [comment]
Verified successfully in production. Closing as complete!
