### ISSUE TITLE
[Analytics] [Dupe GA Events] Remove duplicate GA event fl-search on FE Facility locator 

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-cms#18800]
## Description

The duplicate event(s) on FE **Facility Locator** identified and listed on line 157 in Randi's [spreadsheet](https://docs.google.com/spreadsheets/d/1fDsRQct_QMJ5nd3bTRDgwrfbFo_PqzdFQqYecJouic8/edit?gid=0#gid=0) needs to be removed.

#### Element: "Search this area of the map" button (appears when you zoom on the map)
- **Event name:** fl-search
- **Other event data:** 
  - "fl-search-fac-type: {facility type}
  - fl-search-svc-type: {service type}"
- **Example URL:** https://www.va.gov/find-locations/?page=1&address=19103%20Birdsong%20West%2C%20San%20Antonio%2C%20Texas%2078258%2C%20United%20States&facilityType=health&serviceType&latitude=29.6267&longitude=-98.495114&radius=10&bounds%5B%5D=-99.245114&bounds%5B%5D=28.8767&bounds%5B%5D=-97.745114&bounds%5B%5D=30.3767&context=San%20Antonio%2C%20Texas%2078258%2C%20United%20States

### User story

**AS A** PO/PM of sitewide products
**I WANT** all duplicate events removed from our product's code
**SO THAT** we aren't charged by Google Analytics twice for the 'same' event

## Acceptance criteria

- [x] Duplicate event listed in description was removed

**Comment by jilladams** [comment]
@FranECross I haven't been paying attention to how we get the Analytics related tickets verified and closed -- are you helping with that? Or are engineers mostly verifying their own, after deploy?

**Comment by FranECross** [comment]
@jilladams Engineers are verifying and then closing...

**Comment by eselkin** [comment]
fl-search is triggered with extra values only, no DST event.
Verified in prod
<img width="875" alt="Screenshot 2024-08-21 at 4 37 54 PM" src="https://github.com/user-attachments/assets/b2ac6146-ce0f-4e5c-b70c-e27bc88a7db1">
