### ISSUE TITLE
EWA: Actions widget / Recent activity feed [design | content]

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#1880]
Finalize "Actions" widget UI for the following scenarios:
 - user is viewing content that is locked
 - user selected in Assign form has permission to perform a limited set of actions

Finalize "Recent activity feed" UI for the following scenarios:
 - user is viewing one of the older revisions needs a quick way to navigate to the "latest revision" - location TBD
 - user is looking for a link to the live version (if exist) - location TBD
 - user is viewing a revision that is nested in Revisions Activity sidebar - think about navigation within the sidebar

# AC
- [x] locked content indicator is defined in the UI
- [x] "Assign" form UI for assignee with limited permissions is finalized
- [x] navigation within the Recent activity feed is finalized
- [x] UI elements for navigating to the latest revision and to the live version of content is defined
- [x] Expandable/collapsable mechanism is defined for the revision entry area
- [x] Prototype is updated

**Comment by jordanamello** [comment]
@oksana-c the AC "user selected in Assign form has permission to perform a limited set of actions" is no longer valid. All users are allowed to use all three types of assignments. Correct?

**Comment by oksana-c** [comment]
@jordanamello this AC still stands, but I don't believe that prototype will need to change for this AC.

Example scenarios: user X selects user Y in "Assign to" field.
User Y does not have permission to use "Publish" transition but does have permissions to use "Approve" or "Create a new draft" transitions.
So then "Choose assignment" field will only display "Work on content" and "Review content" options, but not the "Publish content" option.

We know that the "Choose assignment" field will need to be refreshed upon user selection and display only limited options, but as long as we are using "select" field, we don't need to illustrate this scenario in the UI. This AC was added to account for a scenario in which we'd use a different pattern for displaying assignment options, e.g. radio boxes / buttons.

Let's connect on this quickly on our scheduled call Jul16th 2pm ET.
