### ISSUE TITLE
Adjust misleading Featured stories help text & hide non-functional Order field

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-cms#18819]
## Description
The logic which governs the number and order of stories which are featured for a VAMC system is flawed and needs to be completely reworked. The difference in what appears to be possible in the UI and the resulting behavior in the FE is confusing and very frustrating for editors. However, rebooting this would not be an insignificant lift for minimal Veteran value so we haven't been able to prioritize the initiative. 

There may be small changes we can make in the UX to reduce editor confusion in the meantime. 

Removing the Featured field order from the UI is a separate task. [#13688 ](https://app.zenhub.com/workspaces/vagov-sitewide-product-team-6645154188a81a1f7a0a9464/issues/gh/department-of-veterans-affairs/va.gov-cms/13688) 

## UX changes for consideration

Currently, the UX includes this help text

> Featured stories appear in the "featured" section of a VA product page, such as an Office or VAMC home page. You can feature up to 2.

In reality, 
- editors should not be able to feature more than one story, so we should remove the help text that says otherwise. 
- more than one story can be selected to be featured but only the last to be selected will appear. We should find a clear way to advise the editor that choosing to mark the story featured will cause any previously featured story to become "unfeatured". 
- editors do not need to uncheck previously selected stories. There may be a reasonable way to also make that known.  

**Related issues**
- #13687
- [Feature function for Story content types only allows one Featured story #11221](https://app.zenhub.com/workspaces/deprecated---can-be-deleted-639f5253e4b702a32376339e/issues/gh/department-of-veterans-affairs/va.gov-cms/11221)
- [CONSIDER: New possibilities for Featured Stories #13695](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13695)

## Screenshots

<details>
<summary> Drupal interface for featuring </summary>

<img width="852" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBKzhtQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b975626eda58aceb55bb100ae2475816af0a9ec3/image.png" alt="image.png" />

</details>

## Acceptance Criteria
- [x] Help text matches the intended Featuring functionality 
   - Functionality will be fixed by #13687
- [x] Order field is hidden on Events and Stories 
   - This will be fully removed in #13688

**Comment by davidmpickett** [comment]
Notes to self:

- https://github.com/department-of-veterans-affairs/content-build/blob/main/src/site/layouts/health_care_region_page.drupal.liquid

**Comment by davidmpickett** [comment]
**Mid-sprint update:** I have a PR up that updates the Help text and hides the Order fields. Need to add QA steps and take it through the process

**Comment by davidmpickett** [comment]
Requested PR review: https://dsva.slack.com/archives/C0FQSS30V/p1727724280485269

**Comment by davidmpickett** [comment]
- Suggested KB revision https://prod.cms.va.gov/node/23532/revisions/view/905522/921534/visual_inline

**Comment by davidmpickett** [comment]
@mmiddaugh @Agile6MSkinner @jilladams Closing as complete, but some notes for y'all

Verified on Prod: 
- https://prod.cms.va.gov/node/add/news_story
- https://prod.cms.va.gov/node/add/event

Updates to KB articles have been published to remove references to Order field:
- https://prod.cms.va.gov/help/vamc/how-do-i-feature-a-story-on-my-sites-homepage
- https://prod.cms.va.gov/help/va-medical-centers-vamcs/about-stories-content-for-vamcs/how-to-add-a-story

Related tickets to consider prioritizing:
- #13687
- #13688
- Limit FE display to 1? No existing ticket, but could reduce confusion possibility space

Documentation about Stories?
- There's no dedicated document about the Story product in [our Github folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/facilities). 
- It gets a brief mention in the (hidden) **copypasteable list of products** in the readme. 
- Right now, they are part and parcel with VAMCs, so it could theoretically be nested under that, but not sure if there's any plan to add to Vet Centers/VBAs at any point.
- It does have a [label](https://github.com/department-of-veterans-affairs/va.gov-cms/issues?q=label%3AStory%20state%3Aopen%20sort%3Aupdated-desc) though

Old related tickets I closed as no-ops dupes:
- #13914 
- #1317 
- #11221
- #13795
