### ISSUE TITLE
New VAMC Facility: Tampa Forty-Second Street VA Clinic - AWAITING CSV

### ISSUE THREAD

**Issue by TroyCMSSupport** [department-of-veterans-affairs/va.gov-cms#18816]
## Intake
- [x] What triggered this runbook? (Flag in CMS, Help desk ticket, Product team, VHA Digital Media)
Trigger: Flagged in CMS

- [x] Link to associated help desk ticket (if applicable)
Help desk ticket: [Helpdesk Ticket](https://va-gov.atlassian.net/browse/VAHELP-7825)

- [x] Name of submitter (if applicable)
Submitter: Stephen Westerfield

- [x] If the submitter is an editor, send them links to any relevant KB articles for the VAMC Facility product.
KB articles: <[KBA link1](https://prod.cms.va.gov/help/vamc/about-locations-content-for-vamcs/how-do-i-add-a-facility-to-my-health-care-system)>

<[KBA link2](https://prod.cms.va.gov/help/va-medical-centers-vamcs/about-locations-content-for-vamcs/how-to-edit-a-vamc-facility)>

<[KBA link3](https://prod.cms.va.gov/help/vamc/how-to-add-edit-or-remove-a-vamc-facility-health-service)>

- [x] Link to facility in production:
Facility CMS link: <https://prod.cms.va.gov/locations/tampa-forty-second-street-va-clinic>
Facility API ID: vha_673QO

### New VAMC Facility
Please refer to the Knowledge Base article titled "How do I add a facility to my health care system?" for more information: https://prod.cms.va.gov/help/vamc/about-locations-content-for-vamcs/how-do-i-add-a-facility-to-my-health-care-system

#### CMS help desk steps
**Note: If the help desk is waiting on information from the facility staff or editor, add the "Awaiting editor" flag to the facility with a log message that includes a link to this ticket. Remove the flag when the ticket is ready to be worked by the Facilities team. Be sure to preserve the current moderation state of the node when adding or removing the flag.**
- [x] Become aware that the new facility is now on the Facility API (typically, via a Flag, but this may come in as a helpdesk ticket).
- [x] **If the facility is a VA Mobile clinic, the "New facility" flag can be removed and the page archived with no further work needed. (Note, there are required fields that will need to be filled in before doing so.)**
- [x] If the editor has followed the steps from the above Knowledge Base article and included which section and VAMC the facility belongs to (i.e. VA Pittsburgh), great!
  - If not, please check with the editor or VHA digital media regarding what section and VAMC it belongs to.
    - [x] Update the Section (default is "VAMC facilities", but it should be a VAMC system in a VISN) and VAMC system field accordingly.
- [x] Communicate with editor (cc VHA Digital Media) to give them go-ahead to complete the content, with this [KB article](https://prod.cms.va.gov/help/vamc/about-locations-content-for-vamcs/how-do-i-add-a-facility-to-my-health-care-system). (See sample notification email below)

<details><summary>Email template </summary>

```

Hello! You should now be able to edit the draft page for this facility, located at [LINK TO NEW FACILITY DRAFT PAGE ON PROD]

Important: Please make sure that all relevant steps listed within the “How do I add a facility to my health care system?” Knowledge Base article have been completed: https://prod.cms.va.gov/help/vamc/about-locations-content-for-vamcs/how-do-i-add-a-facility-to-my-health-care-system

Once finished, please save this page (and all related VAMC Facility Health Service pages) in the moderation state “Draft." Please do not save them as “Published.”

Please let us know when your draft content is complete, so that we can wrap up the technical process from our end before publishing the new facility to VA.gov. Thanks!

```

</details>

- [x] When editor has prepared content and let help desk know, proceed to the remaining steps.

#### Drupal Admin steps (CMS Engineer or Help desk) _Help desk will complete these steps or escalate to request help from CMS engineering._
- [x] Update the facility **Meta description** field, using the following format: "Get address and hours, parking and transportation information, and health services offered at [facility name]."
- [x] Move the facility link in the health care system menu to its place in the alphabetized list (medical centers first, then clinics).
- [x] Drupal Admin bulk publishes nodes and facility.
- [x] Contact Lighthouse via Slack at #cms-lighthouse channel that this facility requires a canonical link in the following format (replacing the placeholder data with the actual API Id and VA.gov URL):
  - `vha_691GM,https://www.va.gov/greater-los-angeles-health-care/locations/oxnard-va-clinic/`
- [x] Add the "Awaiting CSV" flag to the facility node with a revision log message that includes a link to this ticket.
- [x] Let Help desk know this has been done, if not done by Help desk.

#### Wait (days or weeks, potentially)
- [x] After the canonical link has been added to the websites.csv and you have confirmation from Lighthouse that the CSV has been deployed, validate that the change has deployed by checking that the Facility Locator has been updated with the new url.
- [x] Update this ticket with a comment that the CSV change has been deployed.
- [ ] Edit facility node and remove `New facility` and "Awaiting CSV" flags with a revision log message that includes a link to this ticket.

#### CMS Help desk (wrap up)
- [ ] Notify editor and any other stakeholders.

**Comment by TroyCMSSupport** [comment]
@omahane @jilladams @ian-sears - Awaiting Editor revisions in DRAFT MODE ([VAHELP-7825](https://va-gov.atlassian.net/browse/VAHELP-7825))

**Comment by TroyCMSSupport** [comment]
I reached out today (9/20/24) to the editor regarding the needed revisions. No revisions to date.

**Comment by TroyCMSSupport** [comment]
I reached out today (10/18/24) to the editor regarding the needed revisions. No revisions to date.
@ian-sears @jilladams @omahane

**Comment by TroyCMSSupport** [comment]
@jilladams @ian-sears @omahane  - Editor has added one health service, still in draft mode; Reaching out to editor to confirm readiness.

**Comment by ian-sears** [comment]
@omahane Please advise.
https://prod.cms.va.gov/tampa-health-care/locations/tampa-forty-second-street-va-clinic
The editor Stephen Westerfield has approved Publishing of Tampa Forty-Second Street VA Clinic, but will not be adding facility image and description text until later today (likely).

**Question:** In your preferred process flow, should the CMS HD **Publish this now, to begin the Lighthouse CSV request** (or) or wait until these details are first completed by the Editor?

In the interest of getting this moved along, as the facility **is seeing Veterans, currently**...

@department-of-veterans-affairs/platform-cms-helpdesk fysa

**Comment by ian-sears** [comment]
Disregard the above. 
Editor has completed the promised final updates. 
Facility has been Published. Locations Menu has been sorted and activated.
Request to add the canonical to websites.csv has been made:
https://dsva.slack.com/archives/C02BTJTDFTN/p1729868962345899?thread_ts=1729289019.897279&cid=C02BTJTDFTN

@department-of-veterans-affairs/platform-cms-helpdesk fysa

**Comment by ian-sears** [comment]
CSV change has been deployed

**Comment by ian-sears** [comment]
Editor has been notified.
Closing as resolved.

**Comment by TroyCMSSupport** [comment]
@ian-sears @jilladams @omahane - This issue - as orginally reported - is complete. 
However, the same facility now has a name change in VAST - I will submit appropriate GH tickets to process the name change (FROM 'Tampa Forty-Second Street VA Clinic' TO 'Forty-Second Street VA Clinic'
