### ISSUE TITLE
Suggested Changes to Medical Records Office Page

### ISSUE THREAD

**Issue by ian-sears** [department-of-veterans-affairs/va.gov-cms#18810]
## User Story or Problem Statement
As an Editor responsible for process requests submitted to the Medical Records Office, we need the text on the Medical Records Office page(s) updated to align with new language from the VHA HIM National Program Office.

## Description or Additional Context 
The Editor writes "It was brought to my attention that the following information on the Medical Records Office page is incorrect nation-wide. Can you please make the following adjustments to the template? Thank you!"

## CMS URLs: 
Centralized Content for Medical Records: 
https://prod.cms.va.gov/centralized-content/vamc-system-medical-records-page-content

Example Medical Records VAMC page where the CC appears: 
https://prod.cms.va.gov/palo-alto-health-care/medical-records-office#questions-about-medical-record

### Page-specific FAQ:  Questions about medical records > Can I get a proof of health insurance document?
        Please ask at the Register for care office, and they will provide you documentation of your VA coverage.

        How we share your records with providers outside VA
        [Change FROM] We process mailed or faxed requests within 10-14 days. Per VHA HIM National Program Office, 
        [Change TO] We have 20 business days to process all requests.
        For privacy reasons, we can’t accept requests for medical records by email.

## Related 

- [VAHELP-7821 Suggested Changes to Medical Records Office Page](https://va-gov.atlassian.net/browse/VAHELP-7821?atlOrigin=eyJpIjoiNTMzY2I4NTg5MWY3NDIxN2I5OWE2ZjM5ODE4NTIxMzciLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
- [Related Slack thread in #cms-support](https://dsva.slack.com/archives/CDHBKAL9W/p1722380640279739)
- Card in VHA DM agenda: https://trello.com/c/Qcfgyxqn/229-copy-changes-requested-to-centralized-content-for-vamc-medical-records

## Acceptance Criteria
- [ ]

**Comment by ian-sears** [comment]
Original Request came in via JIRA CMS Help Desk support request ticket: [VAHELP-7821](https://va-gov.atlassian.net/browse/VAHELP-7821)

dsva [Slack discussion here](https://dsva.slack.com/archives/CDHBKAL9W/p1722380640279739)

**Comment by ian-sears** [comment]
@jilladams Filed as per request. Please do let us know if we should have filed additional details for your team to see this.
@TroyCMSSupport fysa

**Comment by jilladams** [comment]
We will need to get VHA DM sign off on updating this Centralized Content. 

Card in VHA DM agenda: https://trello.com/c/Qcfgyxqn/229-copy-changes-requested-to-centralized-content-for-vamc-medical-records

**Comment by jilladams** [comment]
Noting: this editor (Andrea.Ritz@va.gov) had requested 2 changes to Centralized Content. She already made one of those changes on July 29: 

### GET YOUR RECORDS IN PERSON (section)  
Please add: 

> What to bring
A completed and signed “Individuals’ Request For a Copy of Their Own Health Information” (VA Form 10-5345a) for a copy of your records to be sent to you [Download VA Form 10-5345a](https://www.va.gov/vaforms/medical/pdf/VHA%20Form%2010-5345a%20Fill-revision.pdf) (PDF)  

If she was able to modify that and get approval, she may be able to modify the FAQ as well, but we can run it past VHA DM to be sure.

**Comment by jilladams** [comment]
A side question: should this user have been able to make this Centralized Content change, permissions wise? 
https://prod.cms.va.gov/admin/people?user=Andrea.Ritz%40va.gov&status=1&role=All&workbench_access_section__section=All - Content Creator VAMC, and Content Publisher.
