### ISSUE TITLE
URL Change for: Concord VA Clinic

### ISSUE THREAD

**Issue by TroyCMSSupport** [department-of-veterans-affairs/va.gov-cms#18813]
Parent ticket: #[18812](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18812)

### Implementation date
When does this request need to be live:
TBD

### Instructions for URL redirect
(Note: This issue will be used from initial request through implementation to ensure all individuals working on this are notified of status updates.  Please do not create multiple issues to track different steps.)
- [x] Notify VA stakeholders as appropriate.
- [x] Link the related facility [closure](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18812) / rename issue.
- [x] Create a URL redirect in the [vsp-platform-revproxy](https://github.com/department-of-veterans-affairs/vsp-platform-revproxy) repo in `template-rendering/revproxy-vagov/vars/redirects.yml`
- [x] Add the "Awaiting redirect" flag to the facility node with a revision log message that includes a link to this ticket, preserving the node's current moderation state.
- [x] Redirects deploy daily except Friday at 10am ET, or by requesting OOB deploy (of the revproxy job to prod) in #vfs-platform-support. After deploy, validate that the URL redirect is deployed. (Note: In the event of a facility closure or a name change,  validate that this occurs before making the Lighthouse csv changes.)
- [x] Update this ticket with a comment that the redirect has been deployed.
- [x] Remove the "Awaiting redirect" flag on the facility node with a revision log message that includes a link to this ticket, preserving the node's current moderation state.
- [x] Notify helpdesk via comment on ticket or Slack message in #cms-support that changes are ready for review.

#### URL Redirect
| Current URL  |  Redirect Destination or New URL |
| ---  |  --- |
| https://www.va.gov/manchester-health-care/locations/concord-va-clinic | https://www.va.gov/manchester-health-care/locations/ |

### 1. Canonical URL change

**Note: Canonical URL changes do not block the completion of the parent ticket. Once the URL redirect above has been deployed, the value to the Veteran is delivered. This ticket should be kept open until the URL change is verified, except in the case of a removal (as described below).**

### Instructions for canonical URL removal
- [x] Try to find the facility via the Facility Locator, using the Facility API ID (e.g. https://va.gov/find-locations/facility/"facility_api_id"). If it is not available, proceed.
- [x] Contact Lighthouse via Slack at #cms-lighthouse channel that this facility requires a canonical link to be removed in the following format:
  - `vha_608BY,https://www.va.gov/manchester-health-care/locations/concord-va-clinic`

**Note: there's no check to see if it's not returning anything, as it should already be not showing anything in the Facility Locator.**

#### URL removal example (update with actual ID and URL to remove)
| Facility API ID  |  Full VA.gov URL |
| ---  |  --- |
| vha_608BY | https://www.va.gov/manchester-health-care/locations/concord-va-clinic |

**Comment by omahane** [comment]
@TroyCMSSupport I updated this ticket with the correct links and removed the section about a canonical URL change (as that doesn't apply to a closed facility), leaving the section about the removal.

**Comment by omahane** [comment]
The redirect has been merged: https://github.com/department-of-veterans-affairs/vsp-platform-revproxy/pull/561

**Comment by omahane** [comment]
The redirect has been deployed.
