### ISSUE TITLE
New VAMC Facility: Junction City VA Clinic - Awaiting CSV

### ISSUE THREAD

**Issue by TroyCMSSupport** [department-of-veterans-affairs/va.gov-cms#18823]
## Intake
- [x] What triggered this runbook? (Flag in CMS, Help desk ticket, Product team, VHA Digital Media)
Trigger: **Flag in CMS**

- [x] Link to associated help desk ticket (if applicable)
Help desk ticket: [insert_help_desk_link](https://va-gov.atlassian.net/browse/VAHELP-7804)

- [x] Name of submitter (if applicable)
Submitter: **Dane O'Hara** (dane.ohara@va.gov) 

- [x] If the submitter is an editor, send them links to any relevate KB articles for the VAMC Facility product.
KB articles: [KBA Link](https://prod.cms.va.gov/help/vamc/about-locations-content-for-vamcs/how-do-i-add-a-facility-to-my-health-care-system)

- [x] Link to facility in production:
Facility CMS link: [Facility Link](https://prod.cms.va.gov/eastern-kansas-health-care/locations/junction-city-va-clinic)
Facility API ID: **vha_589JH**

### New VAMC Facility
Please refer to the Knowledge Base article titled "How do I add a facility to my health care system?" for more information: https://prod.cms.va.gov/help/vamc/about-locations-content-for-vamcs/how-do-i-add-a-facility-to-my-health-care-system

#### CMS help desk steps
**Note: If the help desk is waiting on information from the facility staff or editor, add the "Awaiting editor" flag to the facility with a log message that includes a link to this ticket. Remove the flag when the ticket is ready to be worked by the Facilities team. Be sure to preserve the current moderation state of the node when adding or removing the flag.**
- [x] Become aware that the new facility is now on the Facility API (typically, via a Flag, but this may come in as a helpdesk ticket).
- [x] If the editor has followed the steps from the above Knowledge Base article and included which section and VAMC the facility belongs to (i.e. VA Pittsburgh), great!
  - If not, please check with the editor or VHA digital media regarding what section and VAMC it belongs to.
    - [x] Update the Section (default is "VAMC facilities", but it should be a VAMC system in a VISN) and VAMC system field accordingly.
- [x] Communicate with editor (cc VHA Digital Media) to give them go-ahead to complete the content, with this [KB article](https://prod.cms.va.gov/help/vamc/about-locations-content-for-vamcs/how-do-i-add-a-facility-to-my-health-care-system). (See sample notification email below)

<details><summary>Email template </summary>

```

Hello! You should now be able to edit the draft page for this facility, located at [LINK TO NEW FACILITY DRAFT PAGE ON PROD]

Important: Please make sure that all relevant steps listed within the “How do I add a facility to my health care system?” Knowledge Base article have been completed: https://prod.cms.va.gov/help/vamc/about-locations-content-for-vamcs/how-do-i-add-a-facility-to-my-health-care-system

Once finished, please save this page (and all related VAMC Facility Health Service pages) in the moderation state “Draft." Please do not save them as “Published.”

Please let us know when your draft content is complete, so that we can wrap up the technical process from our end before publishing the new facility to VA.gov. Thanks!

```

</details>

- [x] When editor has prepared content and let help desk know, proceed to the remaining steps.

#### Drupal Admin steps (CMS Engineer or Help desk) _Help desk will complete these steps or escalate to request help from CMS engineering._
- [x] Update the facility **Meta description** field, using the following format: "Get address and hours, parking and transportation information, and health services offered at [facility name]."
- [x] Move the facility link in the health care system menu to its place in the alphabetized list (medical centers first, then clinics).
- [x] Drupal Admin bulk publishes nodes and facility.
- [x] Contact Lighthouse via Slack at #cms-lighthouse channel that this facility requires a canonical link in the following format (replacing the placeholder data with the actual API Id and VA.gov URL):
  - `vha_589JH,https://www.va.gov/eastern-kansas-health-care/locations/junction-city-va-clinic/`
- [x] Add the "Awaiting CSV" flag to the facility node with a revision log message that includes a link to this ticket.
- [x] Let Help desk know this has been done, if not done by Help desk.

#### Wait (days or weeks, potentially)
- [ ] After the canonical link has been added to the websites.csv and you have confirmation from Lighthouse that the CSV has been deployed, validate that the change has deployed by checking that the Facility Locator has been updated with the new url.
- [ ] Update this ticket with a comment that the CSV change has been deployed.
- [ ] Edit facility node and remove `New facility` and "Awaiting CSV" flags with a revision log message that includes a link to this ticket.

#### CMS Help desk (wrap up)
- [ ] Notify editor and any other stakeholders.

**Comment by jilladams** [comment]
Junction City has a hard date in November to publish the facility, and we are waiting for that date to make changes.

**Comment by TroyCMSSupport** [comment]
@jilladams @omahane @ian-sears - I have updated this ticket -- This site is to go live in November; Page has been revised and is ready, but is currently still in DRAFT Mode --

**Comment by TroyCMSSupport** [comment]
@ian-sears @omahane @jilladams - Editor has revised the site and subsequently published; 

Request has been submitted to Lighthouse in Slack https://dsva.slack.com/archives/C02BTJTDFTN/p1730493962698479

**Comment by TroyCMSSupport** [comment]
Resubmitted as the original request failed on 11/4/24 -- https://dsva.slack.com/archives/C02BTJTDFTN/p1730936296407329

@omahane @jilladams @ian-sears

**Comment by ian-sears** [comment]
Flag removed: Changed name
Flag removed: Awaiting CSV
CSV has been deployed. Redirect resolves.
GH Parent - https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18823
JIRA-7804 Editor has been notified, all is complete.
@department-of-veterans-affairs/platform-cms-helpdesk FYSA
