### ISSUE TITLE
Update Get Directions link aria-label on Event Detail pages to be conditional

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#18822]
## Description
We recently updated the Get Directions link on event detail pages to use the `va-link` component and it includes an `aria-label` to make the link more specific, "Get directions on Google maps to {the facility or location name}". However, where there isn't information in a Drupal field to pull this from, the `aria-label` is now a bit odd - "Get Directions on Google Maps to". See these examples:

- No location: https://www.va.gov/minneapolis-health-care/events/69858/
- Location available: https://www.va.gov/minneapolis-health-care/events/69316/

If we make the `aria-label` conditional, those that have the info available will get the specific labels but those that don't will simply have the same visual text as what's on the screen.

There should potentially be a Drupal update to require the location name (This is going to become more important on listing pages because of duplicative links) but that would be a separate discussion/ticket.

## Acceptance Criteria
- [ ] Events with available location information have an appropriate `aria-label`
- [ ] Events without location info have no`aria-label`
- [ ] Requires accessibility review
- [ ] Coordinate with AP team re: them making the same change in AP templates and link to that thread / ticket

**Comment by jilladams** [comment]
@chriskim2311 saw you have a PR up for this, so pulled it over and assigned to you. Feel free to update if that's incorrect.

**Comment by jilladams** [comment]
@chriskim2311 this will need to be updated in the Event detail page AP templates as well. Are you willing to look into making that change yourself? Or: can surface for the AP team in #sitewide-accelerated-publishing. (May need to coordinate with @ttran-Therisa to make the change directly.)

**Comment by laflannery** [comment]
@jilladams Just FYI that they haven't even done the first part of this in AP yet - it's in my QA spreadsheet - so this would go with that first update now that they are both done (or close to)

**Comment by chriskim2311** [comment]
@jilladams @laflannery  Verified the changes on prod, based on Laura's comment I think this is good to close and changes in AP will come after QA.
