### ISSUE TITLE
[Drupal Update] QA and PR review of Drupal Core update to  v10.3.2

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-cms#18844]
## Description
Grace K shared  that the CMS team is working on a Drupal Core upgrade to v10.3.1 ([ticket here](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18703)) and will need support from the sitewide developers to review their products impacted by the upgrade.  [Slack convo](https://dsva.slack.com/archives/C03LFSPGV16/p1722625548060499)

Targeted completion of update is 8/14/2024.

### Engineering notes / background
PR: https://github.com/department-of-veterans-affairs/va.gov-cms/pull/18956/files
Need to review module updates to understand risk and potential blast radius.

Using this spreadsheet for tracking the testing: https://docs.google.com/spreadsheets/d/1sdhc_7dDYnmgusHkjfuJKtQOmRX89owDbEUn-MXmOz8/edit?gid=1052173265#gid=1052173265

## Acceptance criteria
- [x] QA review of work performed in the Drupal Core update to v10.3.2
- [x] PR review completed
- [x] Share issues or Pass with Grace & Jake Bapple

**Comment by jilladams** [comment]
@dsasser FYI that in Sitewide cross-team sync today, @gracekretschmer-metrostar flagged that CMS Team would ideally like to get feedback from testing by 8/14 if possible. There is flexibility on that, so if we need more time, just need to flag it.

**Comment by jilladams** [comment]
@dsasser question:  this ticket is framed as Public Websites specific. @Agile6MSkinner also made a ticket for the Facilities side, #18891. We didn't get that one pulled into sprint. I'm wondering what you're thinking as far as testing for this, and if we might be able to combine these 2 tickets and cover the testing once on behalf of both sides. 

If that makes scope wacky/wild, feel free to say: bad idea, and we'll just need to get the Facilities side ticket pulled in, based on CMS timing for our feedback.

**Comment by jilladams** [comment]
Clarified with CMS team: PR should arrive on 8/14. When we can assess scope, Daniel will confirm whether it makes sense to do both PW / Fac at once.

**Comment by jilladams** [comment]
https://dsva.slack.com/archives/CT4GZBM8F/p1723662054509539
>  D10.3 update is running into some issues w/ ECA that I'm (Daniel) planning to look into unless there are objections. My best guess is under 2 hours to fix, but I'm not sure until I get in there. This will probably slightly delay the 10.3 testing we planned in this sprint.

D10.3.1 errors when ECA 1.1.8 (current prod) is in use. Upgrade 2.0 is required _unless_ we can update our custom `va_gov_eca` module so that it doesn't directly extend `ConfigurableActionBase` which is currently used in our module and apparently not compatible with D10.3.1. 

Logging that, bc I think the effort for Daniel to help figure out what's going on in order to unblock 10.3.1 PR logically sits in this ticket just fine, if we're aware of what's up.

**Comment by dsasser** [comment]
## Status Update 8/19/24

Platform CMS team are having some issues with the upgrade and aren't ready for us to do our reviews yet.

**Comment by dsasser** [comment]
> ## Status Update 8/19/24
> Platform CMS team are having some issues with the upgrade and aren't ready for us to do our reviews yet.

Not long after I posted this the [CMS team notified us](https://dsva.slack.com/archives/C03LFSPGV16/p1724081715697259?thread_ts=1722625548.060499&cid=C03LFSPGV16) that they are now ready for us to review the upgrade.

**Comment by jilladams** [comment]
PR ready: https://github.com/department-of-veterans-affairs/va.gov-cms/pull/18956

https://dsva.slack.com/archives/C03LFSPGV16/p1724081715697259?thread_ts=1722625548.060499&cid=C03LFSPGV16

**Comment by omahane** [comment]
@jilladams @Agile6MSkinner I'm done with the spot checking that I think is necessary to determine that I haven't seen any regressions. Based on a call I had with @jv-agile6 , I have him down for a couple items, but if it's better to get this passed, I can do them or I can do them with him pretty quickly (< 1 hr) and we will probably be able to sign off on it.

**Comment by omahane** [comment]
I picked up the items @jv-agile6 and I had discussed having him look at to expedite the PR merge. No regressions have been detected.
