### ISSUE TITLE
Update table on sitewide products to use v3 component

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#18843]
## Description
When we were doing the massive DS component upgrades earlier this year the table component did not have a v3 equivalent, [it does now](https://design.va.gov/storybook/?path=/docs/uswds-va-table--default). We need to update everywhere we are using the current table component.

## Where are we using table?
- Benefits detail pages - Examples:
  - https://www.va.gov/pension/survivors-pension-rates/past-rates-2020/
  - https://www.va.gov/disability/compensation-rates/special-monthly-compensation-rates/past-rates-2023/
- VAMC Detail pages - Examples:
  - https://www.va.gov/pittsburgh-health-care/shuttle-schedule/
  - https://www.va.gov/bedford-health-care/programs/va-new-england-shuttle-schedule/
- Landing page:
  - No examples but this does have the capability so we should be sure the template is updated
- Resources and Support Detail page - Examples:
  - https://www.va.gov/resources/approved-fields-of-study-for-the-stem-scholarship/

## Additional context
- Alignment:
  - It has also been noted that the alignment of the data in the existing tables is not consistent, some cells are right aligned, some are left, etc. All cells should be left aligned to follow the default alignment of the component.
  - No classes or custom alignment should be added to these `<span>` tags:
![image](https://github.com/user-attachments/assets/611ab65d-dbc0-40af-8aae-a08588dc533b)

- Role
  - The component should not have `role="table"`

 

## Acceptance Criteria
- [ ] All tables on all above templates should use v3 table component
- [ ] The tables should all use [the bordered table](https://design.va.gov/storybook/?path=/docs/uswds-va-table--docs#bordered)
- [ ] If available, the Table Caption should be passed to the `table-title` component prop
- [ ] No custom styles, attributes, props, or classes should be added to the table or the contents of the table
- [ ] Requires design review
- [ ] Requires accessibility review

**Comment by jilladams** [comment]
I have no horse in the race and defer to @FranECross and @thejordanwood on UX grounds

**Comment by thejordanwood** [comment]
@randimays Releasing to prod is also fine with me.
