### ISSUE TITLE
Editorial Workflow & Assignments usage data collection strategy

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#1886]
## Problem statement

In order to gauge the effectiveness of implemented EWA tools, we need to identify KPIs and collect baseline measurements, so that we can gauge and compare these KPIs before and after the release of EWA features.

see parent epic for additional context #2168 

## Acceptance criteria

- [ ] brainstorm and document KPIs and metrics that will allow us to gauge the effectiveness of EWA tools
- [ ] discuss w/ a focus group (@jordanamello @oksana-c @kevwalsh @rachel-kauff)
- [ ] finalize a list of short / long-term metrics to track. 
    * short-term metrics may include those that can help us get any baseline numbers before EWA is implemented. E.g. the number of times users review past revisions for nodes, etc.
    * long-term metrics focus but are not limited to any new features to be introduced by EWA

**Comment by TheBoatyMcBoatFace** [comment]
Closing. This issue is handled under 
- #11928
