### ISSUE TITLE
[Injected header/footer] Docs updates in support of product handoff

### ISSUE THREAD

**Issue by randimays** [department-of-veterans-affairs/va.gov-cms#18866]
## Status
**[2024-08-16]** Jill completed first pass. Needs eng eyes. From Michelle side: ok to push til after Randi's PTO since Matt Dingee / Micah have PTO lined up and won't review til after regardless. Won't complete in Sprint 10.
**[2024-08-07]** [Fran] Put this ticket on hold - Laura F suggests holding off on picking up that ticket until DST has time to review our existing documentation and ask any questions (that can be answered by docs).

## Description
Now that the code split between the TeamSites ("injected") header/footer is complete, the next step is to prepare this product for handoff to the Platform Design System team.

https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/proxy-rewrite/README.md
This README lives alongside the Teamsites header/footer code. Its purpose is to explain the technical approach to the proxy-rewrite injection and how to test the code.

https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/header-footer/injected-header
This README is the runbook for TeamSites injection and describes the business details for implementation. It should be reviewed for accuracy and updated if needed.

Slack thread for context: https://dsva.slack.com/archives/C06V7AAFVH7/p1722984224566839

### User story
**AS A** an engineer, PO, PM, or other consumer of our product READMEs
**I WANT** to ensure the documentation regarding the updates to the Injected Header/Footer are up to date
**SO THAT** everyone concerned is aware of current implementation, which will lessen questions to the PW team, as well as potentially lessen prod issues in future.

## Acceptance criteria
- [ ] [Code-adjacent docs](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/proxy-rewrite/README.md):
  - [x] Update team ownership here: https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/proxy-rewrite#business-case--ownership
  - [x] Update team ownership here: https://depo-platform-documentation.scrollhelp.site/getting-started/global-va-gov-header-footer-including-injected-hea
  - [x] Update ownership here: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/header-footer
  - [x] Update CODEOWNERS files in [content-build](https://github.com/department-of-veterans-affairs/content-build/blob/main/.github/CODEOWNERS) and [vets-website](https://github.com/department-of-veterans-affairs/vets-website/blob/main/.github/CODEOWNERS)
  - [x] Update or relocate info about Datadog monitor for Teamsites: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/header-footer/engineering/monitoring.md re: https://vagov.ddog-gov.com/monitors/161580?view=spans
  - [x] Add info about how the header/footer data is received from Drupal / content-build
  - [x] Add info about the hard-coded language toggles
  - [x] Add info about testing through environments (e.g. only local and prod)
  - [x] Add info about risks to the header/footer (both modernized and injected) now that the code is separated
    - [x] Code duplication and keeping design and hard-coded content up to date 
    - [x] Unintended consequences of the few connections proxy-rewrite has to the outside world (e.g. code outside its folder)
- [x] Add info about content changes for hard coded language toggles
- [x] Review [this README](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/header-footer/injected-header) for accuracy and completeness

**Comment by randimays** [comment]
@FranECross @jilladams Per [Michelle's Slack thread](https://dsva.slack.com/archives/C06V7AAFVH7/p1722984224566839) 🍌: could you speak to the ownership of content changes for the hard coded language toggles? I think DST would receive those requests by ticket from CAIA and update manually in vets-website, but if there's something else in the mix, we should document it as part of this ticket.

**Comment by FranECross** [comment]
> @FranECross @jilladams Per [Michelle's Slack thread](https://dsva.slack.com/archives/C06V7AAFVH7/p1722984224566839) 🍌: could you speak to the ownership of content changes for the hard coded language toggles? I think DST would receive those requests by ticket from CAIA and update manually in vets-website, but if there's something else in the mix, we should document it as part of this ticket.

@randimays I agree in the belief that DST will own those changes, and receive requests from CAIA (unless Jill has heard differently? 😁) cc @jilladams

**Comment by jilladams** [comment]
Updated the **monitoring AC** to note that the existing monitor is described here, so we should update or relocate that info a necessary: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/header-footer/engineering/monitoring.md


re: **translation toggles**: From https://dsva.slack.com/archives/C06V7AAFVH7/p1720203529734199: 
I asked: 
> Content changes - Typically, any content changes to the Header or Footer can be / are managed by CAIA in Drupal. The exceptions that require code changes are within the VCL modal, and the translation menu in the footer (hard coded). If there are content changes required, will DST own that, or will Sitewide?

Matt [responded](https://dsva.slack.com/archives/C06V7AAFVH7/p1721850350022329?thread_ts=1720203529.734199&cid=C06V7AAFVH7: 
> I'm agnostic here and open to discussion. Typically, the DST doesn't own the content inside our components. We do have some "content components" where CAIA has set the content in stone and we do update those (e.g. [autosave](https://design.va.gov/components/form/autosave), [form prefill](https://design.va.gov/components/form/prefill), etc.) We do own the [VCL modal](https://design.va.gov/components/modal/crisis-line-modal) and that is kinda another example of that (it's really just a Modal but the content is specified and managed by us).

Based on that, I think Randi's right that this would act just like VCL and/or content components where CAIA will request changes and DST makes them. (Can't think of any other way to manage it that makes any sense.) We should document it as such.

**Comment by jilladams** [comment]
I read these comments again a week later and realized there's room for confusion, so to be clear: when we mention translation toggles, I am talking about the links/widget in the footer here: 

![Screenshot 2024-08-15 at 12 17 51 PM](https://github.com/user-attachments/assets/d4ae8935-4e59-4320-a854-4c36a2a9938d)

We are not talking about transitioning ownership of the landing pages for those links, or the other kind of hard coded translation toggle that we use on pages, e.g. on pages like https://www.va.gov/family-and-caregiver-benefits/health-and-disability/comprehensive-assistance-for-family-caregivers-esp/. Sitewide'll still own those.

![Screenshot 2024-08-15 at 12 19 21 PM](https://github.com/user-attachments/assets/8f000a76-9140-4e36-89c2-2452b05fde59)

**Comment by jilladams** [comment]
@randimays if you end up looking for work in sprint, you may be able to help me here to verify whether this diagram of the injection process is still accurate? https://app.mural.co/t/departmentofveteransaffairs9999/m/vagov6717/1668126089949/23f43e394e95c8fbf39cd39549bb1f6d20ce289e?wid=0-1668534093353

**Comment by jilladams** [comment]
Given Michelle's note last week: "DST will own the injected header and footer components but not the process that injects it (proxy-rewrite)," I think there are chunks of this ticket that don't require much change now, but I've taken a pass at everything I understand without an engineer, and pinged Randi about discussing the things I'll need her help with. 

TASKS remaining: 

- [ ] Is the injection flow in https://app.mural.co/invitation/mural/vagov6717/1668126089949?sender=u907f83e01e35bb04de6f8139&key=dd1afd5d-3cd7-4d0c-9aff-26e3308b2ec3  useful? 
  - [ ] If so, make sure it's up to date
  - [ ] If not, delete it
- [ ] Assess how we document the lines for injection. PW owns proxy-rewrite; DST owns rendering on injected sites. If someone makes a change that breaks presentation, that's a DST problem. If someone needs injection anew, that's PW. But if injection isn't working bc of a style change: Is that a DST problem or PW problem?
- [ ] Review remaining ACs to figure out how to get them addressed

**Comment by FranECross** [comment]
> @randimays if you end up looking for work in sprint, you may be able to help me here to verify whether this diagram of the injection process is still accurate? https://app.mural.co/t/departmentofveteransaffairs9999/m/vagov6717/1668126089949/23f43e394e95c8fbf39cd39549bb1f6d20ce289e?wid=0-1668534093353

@jilladams We chatted in scrum today about allotting Randi a bigger chunk of time after she returns to review this diagram and other header/footer info so that she isn't context switching and can devote brain power fully to this subject. 😉 cc @randimays

**Comment by randimays** [comment]
@FranECross @jilladams I think I'm going to need some help figuring out how to update this page:

https://depo-platform-documentation.scrollhelp.site/getting-started/global-va-gov-header-footer-including-injected-hea

To request changes to this page, we have to fill out a form under `Restricted Fields` in the above link (Github won't let me copy/paste for some reason).

I think we need to edit a lot of this table. Some edits seem clear-ish to me, but I'm not sure about the items in the red rectangle below.
<img width="788" alt="Screenshot 2024-09-04 at 11 22 56 AM" src="https://github.com/user-attachments/assets/f27340fa-3747-4cf4-a0d5-ad23fd63a04a">

For documentation, I'm going to suggest we add this link: https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/proxy-rewrite/README.md.

Do these proposed changes seem correct?

**Comment by jilladams** [comment]
## NEXT STEPS: 
- [ ]  1. Randi to look at comment on https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13351#issuecomment-2332426644 to verify engineering docs. That ticket can close when that's complete.
- [ ] 2. Jill to review Randi's proxy-rewrite PR: https://github.com/department-of-veterans-affairs/vets-website/pull/31759/files
- [ ] 3. Randi to update CODEOWNERS to make a Header/Footer section, and merge PR
- [ ] 4. Jill to hand off docs overview to Micah for review, and flag the remaining questions we want to finalize, after he's had a chance to review, below:


## Questions for handoff: 

### 1. Ownership of proxy-rewrite / injection:
Michelle [said](https://dsva.slack.com/archives/C06V7AAFVH7/p1722984224566839): "DST will own the injected header and footer components but not the process that injects it (proxy-rewrite)." 

Proxy-rewrite is an app that contains: 
1. the JS that manages injection -- to be owned by Sitewide Product Team 
2. the now-forked markup of the header/footer that get built for injection -- to be owned by DST. TeamSites cannot support components, so keeping the markup / presentation of injected header in sync with VA.gov componentized header will need to happen in this code, if/as needed.

Randi noted: the injected header markup/ injection can break for a few reasons: 
1. Markup or style changes that prevent successful build / injection. DST would own resolving. 
2. Server-level issues such as CORS errors for cross-domain things. Sitewide would own resolving. 
3. The way the Drupal data is put together in content-build. Sitewide would own resolving.

That's spelled out in the [ownership table update](https://dsva.slack.com/archives/C06V7AAFVH7/p1721850116954109?thread_ts=1720203529.734199&cid=C06V7AAFVH7), but we want to make sure this makes sense to everyone.

**Comment by randimays** [comment]
@jilladams The injected header/footer docs & code ownership changes have been merged!

**Comment by jilladams** [comment]
## Questions for handoff: 

### 1. Ownership of proxy-rewrite / injection:
Michelle [said](https://dsva.slack.com/archives/C06V7AAFVH7/p1722984224566839): "DST will own the injected header and footer components but not the process that injects it (proxy-rewrite)." 

Proxy-rewrite is an app that contains: 
1. the JS that manages injection -- to be owned by Sitewide Product Team 
2. the now-forked markup of the header/footer that get built for injection -- to be owned by DST. TeamSites cannot support components, so keeping the markup / presentation of injected header in sync with VA.gov componentized header will need to happen in this code, if/as needed.

Randi noted: the injected header markup/ injection can break for a few reasons: 
1. Markup or style changes that prevent successful build / injection. DST would own resolving. 
2. Server-level issues such as CORS errors for cross-domain things. Sitewide would own resolving. 
3. The way the Drupal data is put together in content-build. Sitewide would own resolving.

That's spelled out in the [ownership table update](https://dsva.slack.com/archives/C06V7AAFVH7/p1721850116954109?thread_ts=1720203529.734199&cid=C06V7AAFVH7), but we want to make sure this makes sense to everyone.

**Comment by jilladams** [comment]
Docs handed off / question posed in the re: fruit salad thread: https://dsva.slack.com/archives/C06V7AAFVH7/p1725646452899189?thread_ts=1722984224.566839&cid=C06V7AAFVH7

**Comment by jilladams** [comment]
Depo site update requested: https://github.com/department-of-veterans-affairs/product-directory/issues/1035

We review docs next week with DST, and if edits come up / are required, we can address at that time.
