### ISSUE TITLE
[Injected header/footer] Remove experimental web components flipper

### ISSUE THREAD

**Issue by randimays** [department-of-veterans-affairs/va.gov-cms#18864]
## Description
As part of https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11313, we added a web component to the TeamSites header for some testing and toggled it with a vets-api flipper called `injected_header_web_components`. Ultimately the web component experiment did not work, so we rolled back the code that was implemented in vets-website. This ticket is to remove that flipper from vets-api.

PR for that flipper: https://github.com/department-of-veterans-affairs/vets-api/pull/12887

## Acceptance criteria
- [x] In vets-api, remove the `injected_header_web_components` flipper
- [x] Open a Platform support request to manually update the Flipper dashboard to remove that flipper in staging and production, e.g. https://dsva.slack.com/archives/CBU0KDSB1/p1706215548005939
  - [x] Validate that the flipper has been removed from the [prod flipper dashboard](https://api.va.gov/flipper/features) and [staging flipper dashboard](https://staging-api.va.gov/flipper/features)

**Comment by randimays** [comment]
@FranECross I found this flipper lying around when I was researching things for injected header/footer handoff. It's ready for your eyes please 👀

**Comment by FranECross** [comment]
@randimays Looks great! I removed the User Story portion since it's tech debt and not user-facing. Thanks for your continued attention to detail and spelunking!

**Comment by randimays** [comment]
This was pulled in as stretch for Sprint 10.

**Comment by randimays** [comment]
Code has been removed from vets-api, did not exist in vets-website. [Platform request](https://dsva.slack.com/archives/CBU0KDSB1/p1724082649936389) to remove from flipper dashboards is complete.

Verified in [staging flipper admin](https://staging-api.va.gov/flipper/features) and [prod flipper admin](https://api.va.gov/flipper/features) that the flipper is removed.

Closing as complete!
