### ISSUE TITLE
Spike: Workflow Transition Permissions Management UI

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#1887]
managing Workflow Transition Permissions in Permissions UI is difficult. Multitude of checkboxes for different roles and various other permissions increases the possibility for error. 
Having a dedicated UI for managing Workflow Transition Permissions will improve Admin experience and reduce errors in configurations.

Potentially a contributable module.

**Comment by swirtSJW** [comment]
Closing this as too spikey and not refined enough to fill the need.
