### ISSUE TITLE
Draft DUW usability research conversation guide

### ISSUE THREAD

**Issue by thejordanwood** [department-of-veterans-affairs/va.gov-cms#18879]
### User story
**AS A** Researcher
**I WANT** to document the details for conducting DUW review flow research
**SO THAT** the research will achieve the stated goals and answer the research questions

### Templates

Use the appropriate template for the group you're conducting research with:
- [Editor-facing Conversation Guide Template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/research/editor-moderation-guide.md)
- [Veteran-facing Conversation Guide Template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/conversation-guide-template.md)

## Suggested workflow/tasks:
- [x] Brainstorm potential tasks
- [x] Create initial draft of conversation guide
- [x] Solicit review/feedback from Sitewide UX Lead
- [ ] Solicit review/feedback from PO, PM, and/or other team members in a public slack post
- [x] Sitewide UX Lead provides consolidated feedback including from PO
- [x] Test prototype(s) with conversation guide and align
- [x] Post on github in project research folder for final approval before submitting to Research Review cycle

## Acceptance Criteria
- [x] Conversation guide drafted
- [x] Feedback incorporated from Sitewide UX Lead and PO
- [x] Feedback incorporated from PM and/or other team members
- [x] Conversation guide aligns with prototype(s)
- [x] Conversation guide posted on github in project research folder
- [ ] Final approval obtained from Sitewide UX Lead and documented at the bottom of the file in preparation for Research Review cycle

**Comment by davidmpickett** [comment]
I think we can just refer to the project as "DUW usability research" for ticket titles to avoid word salad

**Comment by thejordanwood** [comment]
End of sprint update: 

I started this toward the end of sprint and am brainstorming tasks/writing a draft. This should be ready for reviews next sprint.

**Comment by thejordanwood** [comment]
@aklausmeier I've added the [conversation guide to Sharepoint](https://dvagov.sharepoint.com/:w:/r/sites/SitewidePublicWebsites/Shared%20Documents/UX%20Research/Discharge%20Upgrade%20Wizard/DUW%20Conversation%20Guide.docx?d=w0c1bcb7beec746239a84d818a6078535&csf=1&web=1&e=Q1nKbN) and it's ready for review! 

(Noting here that Dave was able to review this before the CA offsite this week.)

cc: @jilladams  @FranECross @davidmpickett

**Comment by aklausmeier** [comment]
@thejordanwood 

- reviewed conversation with dry run of staging environment, prototype looks good and ready!
- left a few comments in Sharepoint convo guide doc
- will need to stub another ticket to finalize research plan and convo guide to include AT participant needs/goals, dates, and any other final details

**Comment by davidmpickett** [comment]
> will need to stub another ticket to finalize research plan and convo guide to include AT participant needs/goals, dates, and any other final details

- These details can be added to the first section of the prep ticket: #19003

**Comment by thejordanwood** [comment]
- I updated the guide with Amanda's suggestions and added it to the [Github research folder](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/veteran-military-records/discharge-upgrade-wizard/research/2024-Review-Flow/conversation-guide.md)
- I updated the prep ticket to include finalizing research deliverables with AT details, dates, and other info. 

I believe this ticket is good to close for now, and we can move on to the prep ticket where we will finalize everything!

cc: @aklausmeier @davidmpickett @jilladams @FranECross
