### ISSUE TITLE
Campaign Landing Page request: Resources for Suicide Loss Survivors

### ISSUE THREAD

**Issue by ian-sears** [department-of-veterans-affairs/va.gov-cms#18871]
## Status

- **[2024-08-08] [Fran]** Approved by Michelle M via [Slack here](https://dsva.slack.com/archives/C52CL1PKQ/p1723147080122989?thread_ts=1723053440.543089&cid=C52CL1PKQ)
- **[2024-08-07]** Blocked on VHA DM answers to campaign questions in JIRA + Sitewide PO approval 

## Description
Justin Warren requests a CLP. The name or focus of the campaign is Resources for Suicide Loss Survivors.  

Justin Warren 

## Intake
- [x] What triggered this runbook? (Help desk ticket, Product team, Slack thread, etc)
Trigger: CMS Help Desk Ticket [VAHELP-7849](https://va-gov.atlassian.net/browse/VAHELP-7849)

- [x] Link to associated JIRA help desk ticket (if applicable)
Help desk ticket: [VAHELP-7849](https://va-gov.atlassian.net/browse/VAHELP-7849)

- [x] Vanity URL requested:
[https://www.va.gov/suicidelosssurvivors](https://www.va.gov/suicidelosssurvivors)	

- [x] Name of submitter (if applicable)
Submitter: Justin.Warren@va.gov

- Campaign title: Resources for Suicide Loss Survivors
- Who the editor(s) will be for the Campaign Landing Page and any appropriate stakeholders for awareness: 

- **The goals/outcomes you are looking to achieve with the campaign:** -  VA Secretary has identified a need to coordinate and increase awareness of VA resources for survivors of Veterans  who died by suicide. This site touches VHA, VBA, and NCA. See attached memorandum.
-  **Outcome success measurement & how it will be measured (note:** "Page views" is not a generally accepted success measurement):  Providing educational talking points for VA staff and non-VA service providers who may interface with suicide loss survivors
-  **Target Audience(s):**  Survivors of Veterans who died by suicide
-  **Campaign start/end dates:**  Start 8/26/24 end - TBD
-  **Is this a seasonal campaign?**  No
-  **If not: when campaign ends, should campaign page be archived or redirected?**  If campaign were to end it would be redirected.
-  **If redirected, where should it redirect?**  The site that it would be redirected has not been developed.
-  **Is there a preferred “Vanity URL” from the root of the [va.gov](http://va.gov/)website?**  [Va.gov/suicidelosssurvivors](http://va.gov/suicidelosssurvivors)

## Acceptance criteria
  
- Request comes in, via helpdesk request or direct to PO, or potentially in a Github issue.
- [x] If not in a helpdesk request, redirect to Helpdesk or create a Helpdesk issue using email support@va-gov.atlassian.net or URL https://prod.cms.va.gov/help
Helpdesk will use #sitewide-public-websites channel to request approvals
- [x] In helpdesk ticket, @ mention Michelle Middaugh to review/approve the creation / existence / description of the CLP. Example text: 
> Hi Michelle, Helpdesk has received a request for a new Campaign Landing Page. Can you confirm that this CLP is approved?

#### Helpdesk steps
- [x] Helpdesk or any Drupal Admin can create the CLP node. Clone the [CLP template node](https://prod.cms.va.gov/node/16512) 
[<New CLP Node Link>](https://prod.cms.va.gov/node/71402/edit)
- [x] If a new CMS editor user is needed, Helpdesk or any Drupal admin can create them and assign proper permissions according to [CLP CMS account administration policy](https://prod.cms.va.gov/help/cms-account-admin-policies/clp-cms-account-administration-policy).
- [x] Send the editor a link to the KB article: [self-guided Campaign Landing Page training](https://prod.cms.va.gov/help/campaign-landing-pages/how-to-manage-campaign-landing-pages)
- [x] Create a post in DSVA slack channel #sitewide-public-websites, and @ mention Jill Adams and Fran Cross: "New CLP requested and approved, for your awareness:" with a link to this Github issue for next steps.

#### Public Websites steps
- [x] Create a [Vanity URL redirect issue](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=jennymayoco%2C+jilladams%2C+RLHecht&labels=sitewide+CAIA%2C+Sitewide+IA%2C+Public+Websites%2C+VA.gov+frontend%2C+Redirect+request&template=redirect-request.md&title=Redirect+Request), IA _must_ review & approve URL requests.

https://github.com/department-of-veterans-affairs/va.gov-team/issues/90405

- [x] @mention Mikki Northuis in IA (#sitewide-content-ia) with link to Github issue, to provide Vanity URL request feedback. IA _must_ review & approve URL requests.    
     
https://dsva.slack.com/archives/C01K37HRUAH/p1723228040086079

- [ ] When approved by IA, execute the steps of the URL change request ticket from step 2 above.

- [ ] When redirect is verified in Production, close Redirect ticket as well as this ticket.

[VAHELP-7849]: https://va-gov.atlassian.net/browse/VAHELP-7849?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[VAHELP-7849]: https://va-gov.atlassian.net/browse/VAHELP-7849?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by ian-sears** [comment]
Tagging @mmiddaugh and @TroyCMSSupport fysa

**Comment by TroyCMSSupport** [comment]
@ian-sears @jilladams @FranECross New Vanity Request has been created, Mikki has been notified in Slack, awaiting EDITOR information from VHA DM

**Comment by TroyCMSSupport** [comment]
Editors will be Justin Warren, Blake Scates, Steve Tokar - sent CLP training document per Runbook.

**Comment by jilladams** [comment]
Thanks Troy!

**Comment by TroyCMSSupport** [comment]
@ian-sears @jilladams @mmiddaugh  - Editors (Justin, Steve, Blake) now appear to be able to edit the CLP as expected.

**Comment by FranECross** [comment]
@TroyCMSSupport @mnorthuis I think this has been completed and can be closed? cc @jilladams

**Comment by TroyCMSSupport** [comment]
@FranECross @jilladams @mnorthuis - This page is due to be published on Monday, Sep 23 -- If OK, I'd like to wait until the page is live before closing.
