### ISSUE TITLE
URL Change for VBA: Roanoke, Togus, Portland

### ISSUE THREAD

**Issue by omahane** [department-of-veterans-affairs/va.gov-cms#18897]
### Implementation date
When does this request need to be live:
ASAP, as these facilities have already been published and are live.

Note: these pages are being treated like Vet Centers, which also pre-existed in the Facility Locator prior to having Drupal-sourced pages. Just as they have redirects for their Facility Locator pages, so, too, will these.

### Instructions for URL redirect
(Note: This issue will be used from initial request through implementation to ensure all individuals working on this are notified of status updates.  Please do not create multiple issues to track different steps.)
- [x] Notify VA stakeholders as appropriate. (Requested by @mmiddaugh )
- [x] Create a URL redirect in the [vsp-platform-revproxy](https://github.com/department-of-veterans-affairs/vsp-platform-revproxy) repo in `template-rendering/revproxy-vagov/vars/redirects.yml`
- [ ] Redirects deploy daily except Friday at 10am ET, or by requesting OOB deploy (of the revproxy job to prod) in #vfs-platform-support. After deploy, validate that the URL redirect is deployed. (Note: In the event of a facility closure or a name change,  validate that this occurs before making the Lighthouse csv changes.)
- [ ] Update this ticket with a comment that the redirect has been deployed.

#### URL Redirect
| Current URL  |  Redirect Destination or New URL |
| ---  |  --- |
| https://www.va.gov/find-locations/facility/vba_314 | https://www.va.gov/roanoke-va-regional-benefit-office/ |
| https://www.va.gov/find-locations/facility/vba_402 | https://www.va.gov/togus-va-regional-benefit-office-at-togus-va-medical-center/ |
| https://www.va.gov/find-locations/facility/vba_348 | https://www.va.gov/portland-va-regional-benefit-office/ |

### 1. Canonical URL change

**Note: Canonical URL changes do not block the completion of the parent ticket. Once the URL redirect above has been deployed, the value to the Veteran is delivered. This ticket should be kept open until the URL change is verified, except in the case of a removal (as described below).**

### Instructions for canonical URL change
- [ ] Verify that the new URL for the facility is published and accessible on VA.gov.
- [ ] Contact Lighthouse via Slack at #cms-lighthouse channel that this facility requires a canonical link in the following format (replacing the placeholder data with the actual API Id and VA.gov URL):
  - `vha_691GM,https://www.va.gov/greater-los-angeles-health-care/locations/oxnard-va-clinic/`
- [ ] Add the "Awaiting CSV" flag to the facility node with a revision log message that includes a link to this ticket.
- [ ] Let Help desk know this has been done, if not done by Help desk.

#### Wait (days or weeks, potentially)
- [ ] After the canonical link has been added to the websites.csv and you have confirmation from Lighthouse that the CSV has been deployed, validate that the change has deployed by checking that the Facility Locator has been updated with the new url.
- [ ] Update this ticket with a comment that the CSV change has been deployed.

#### URL change example (update with actual ID and URL)
| Facility API ID  |  Full VA.gov URL |
| ---  |  --- |
| vha_691GM | https://www.va.gov/greater-los-angeles-health-care/locations/oxnard-va-clinic/ |

### Instructions for canonical URL removal
- [ ] Try to find the facility via the Facility Locator, using the Facility API ID (e.g. https://va.gov/find-locations/facility/"facility_api_id"). If it is not available, proceed.
- [ ] Contact Lighthouse via Slack at #cms-lighthouse channel that this facility requires a canonical link to be removed in the following format (replacing the placeholder data with the actual API Id and VA.gov URL):
  - `vha_691GM,https://www.va.gov/greater-los-angeles-health-care/locations/oxnard-va-clinic/`

**Note: there's no check to see if it's not returning anything, as it should already be not showing anything in the Facility Locator.**

#### URL removal example (update with actual ID and URL to remove)
| Facility API ID  |  Full VA.gov URL |
| ---  |  --- |
| vha_691GM | https://www.va.gov/greater-los-angeles-health-care/locations/oxnard-va-clinic |

**Comment by omahane** [comment]
Slack conversation about making redirects and asking for canonical URL changes:
https://dsva.slack.com/archives/C02BTJTDFTN/p1723148457574839

**Comment by jilladams** [comment]
We need to remember if we have already asked LH to update these for canonical URL. @jilladams @omahane

**Comment by jilladams** [comment]
Christian says: Jill, I don't think we need to do anything else for Roanoke, Togus and Portland. They have the right URLS in the FAPI
