### ISSUE TITLE
After DUW launch: file 508 audit request

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#18896]
### User story

**AS A** PO/PM
**I WANT** DUW to be submitted to the 508 office for audit
**SO THAT** we keep things compliant.

### Engineering notes / background

- Docs on [how to do it](https://depo-platform-documentation.scrollhelp.site/developer-docs/request-support-from-the-va-508-office#audit-request)

## Acceptance criteria

- [x] Audit request [submitted](https://depo-platform-documentation.scrollhelp.site/developer-docs/request-support-from-the-va-508-office#audit-request)
  - ServiceNow (SNOW) request number: Confirmation REQ35686854

**Comment by jilladams** [comment]
FYI @FranECross that I added this ticket to the DUW epic. It's an easy thing to forget to do so starting with Income Limits we've made a ticket for it, so we remember to file before closing the epic when we launch. (cc @laflannery )

**Comment by FranECross** [comment]
Thanks! I'll add to the launch plan as a post launch activity, and will be sure it's on the PAW one too.

**Comment by jilladams** [comment]
@FranECross Mind adding the link to that request onto this ticket? Then it can be closed.

**Comment by FranECross** [comment]
Audit request submitted; confirmation number added to the ticket. Closing.
