### ISSUE TITLE
Establish the baseline of number of simultaneous saves of unique benefits detail pages that that can happen within 3 seconds

### ISSUE THREAD

**Issue by ElijahLynn** [department-of-veterans-affairs/va.gov-cms#1890]
This is for the 2020 Q2 KPI "Establish the baseline of number of simultaneous saves of unique benefits detail pages that that can happen within 3 seconds". 

Need to write a test that does this and add it to CI with the baseline metric as the pass threshold.

**Comment by indytechcook** [comment]
Ran the script on staging running 5 the test script in 5 processes:

15 nodes saved in <5.37 seconds
A single node save took 1.7 seconds

- Operation took 5.14 and completed 3 iterations.
- Operation took 5.21 and completed 3 iterations.
- Operation took 5.26 and completed 3 iterations.
- Operation took 5.31 and completed 3 iterations.
- Operation took 5.37 and completed 3 iterations.

Running in 3 processes:

12 nodes saved in <4.5 seconds
A single node save took ~1.1 seconds

- Operation took 4.28 and completed 4 iterations.
- Operation took 4.39 and completed 4 iterations.
- Operation took 4.50 and completed 4 iterations.

Running in 10 processes:

20 nodes saved in < 7.68 seconds
A single node save took ~ 2.5 seconds.

- Operation took 7.05 and completed 2 iterations.
- Operation took 7.07 and completed 2 iterations.
- Operation took 7.23 and completed 2 iterations.
- Operation took 7.34 and completed 2 iterations.
- Operation took 7.37 and completed 2 iterations.
- Operation took 7.40 and completed 2 iterations.
- Operation took 7.52 and completed 2 iterations.
- Operation took 7.59 and completed 2 iterations.
- Operation took 7.68 and completed 2 iterations.
- Operation took 7.84 and completed 2 iterations.

As we scale horizontally the time per node save goes down.
