### ISSUE TITLE
[AutoSuggest for "Service type"] Step 1 - JSONify the service taxonomy data

### ISSUE THREAD

**Issue by davidmpickett** [department-of-veterans-affairs/va.gov-cms#18909]
## User Story or Problem Statement

**AS A** FE developer on VA.gov, 
**I NEED** to have a JSON object I can query that contains data from Drupal
**BECAUSE** Querying Drupal directly from a public app is a no-no

### drupal download using GraphQL in metalsmith and how to use in `vets-website`
The `Cerner->VistA` method was instituted because lots of disparate parts were relying on flippers per-facility to determine if that facility needed a link to Cerner or VistA portal. Whether a facility was Cerner or VisA was placed behind a redux slice that got data from drupal _en masse_. It is a fairly reusable approach. We should use the action built for that process to load in our data-- method is reasonably understandable.

### Plan
1. We can use the existing methods for pulling data from drupal in content-build. Modeling on (`src/site/stages/build/drupal/static-data-files/vamcFacilitySupplementalStatus/index.js` in content-build)
2. We can use the existing methods for pulling data from drupal generated json into vets-website. Modeling on `src/platform/utilities/cerner/dsot.js` and `src/platform/site-wide/drupal-static-data/source-files/vamc-ehr/connect/index.js`
3. We can use selectors similar to vamc-ehr to use the drupal data. 
    1. Just one selector for all data needed for the autocomplete
    2. Data has 4 booleans that are probably of importance. Some terms only apply to certain facilities (VBA,Vet Center,VAMC,TRICARE). It is unknown if we should make one file for each of these conditions or do some processing in app/on device. There are only 125 taxonomy entries so on-device is not too cumbersome.
    3. Consider the Moderation State (Draft, Published, etc)?
    4. Do we want to exclude terms that have 0 [number of uses](https://prod.cms.va.gov/va-services?type=All&order=nid_1&sort=asc) to prevent giving users options we know will have no results?

### GraphQL
Rudimentary query -- needs additional details:
```graphql
{
  taxonomyTermQuery(
    offset: 0
    filter: {conditions: [{operator: EQUAL, field: "vid", value: ["health_care_service_taxonomy"]}]}
  ) {
    count
    entities {
      ... on TaxonomyTermHealthCareServiceTaxonomy {
        name
        fieldAlsoKnownAs
        fieldCommonlyTreatedCondition
        fieldHealthServiceApiId
        fieldServiceTypeOfCare
        fieldShowForVetCenters
        fieldShowForVbaFacilities
        fieldShowForVamcFacilities
        fieldTricareSpecificService
      }
    }
  }
}
```
[fields that can be used in snake_case (convert to camel)](https://prod.cms.va.gov/admin/reports/content-model/fields?field_name=&field_type=&entity_type=taxonomy_term&bundle=health_care_service_taxonomy&label=)

```[tasklist]
### Specific fields to include
- [x] Name
- [x] Health Service API ID
- [x] Show for VAMC Facilities
- [x] Patient friendly name (VAMC) - aka
- [x] Common conditions (VAMC)
- [x] Service description (VAMC)
- [x] TRICARE service description?
- [x] Show for TRICARE Facilities only?
- [x] Published / Unpublished?
- [x] Number of uses?
```

## QA
- [ ] Test editing relevant fields on an existing term in the Service Taxonomy 
- [ ] Test adding a new term to the Service Taxonomy 
- [ ] Test removing a term from the Service Taxonomy
- [ ] Test a Published vs Unpublished Term
- [ ] Tested for VAMC, Vet Centers, and VBA
- [ ] Add automated unit and/or Cypress tests to verify data coming in, stored in the correct format, using Mocha

## Acceptance Criteria
- [x] Scope includes all VA Services (for VAMC, Vet Centers, and VBA) 
- [x] The JSON object should update with any new details added to a relevant field on a relevant Service Taxonomy Term after a successful Content Release
- [x] Inform AP team about this for Next Build implications?
- [x] Selectors added to vets-website for array results of each type (VBA, Vet Cetners, VAMC, TRICARE)

**Comment by jilladams** [comment]
Including VBA and Vet Center services in the data pull isn't add'l complexity but does affect file size for the JSON file, which loads in page load. So that has performance impact for rural / low bandwidth site visitors. We can assess filesize implications as we go. Let's keep all of the terms in the data for future extensibility.

**Comment by jilladams** [comment]
Notes on probable shape of the object: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18910#issuecomment-2285067653

**Comment by eselkin** [comment]
1. Excluded 0 count uses in the data stored
2. Add data to KISS source
3. Added selectors in vets-website PR

**Comment by jilladams** [comment]
@eselkin (cc @Agile6MSkinner ) is there anything we can do to validate this in Prod yet? Or do we need Steps 2 & 3 present in order to do so?

**Comment by eselkin** [comment]
You can see it in action at 

https://www.va.gov/data/cms/va-healthcare-services.json

The vets-website selectors you can't really see until they get used.

**Comment by jilladams** [comment]
Nice! Closing.
