### ISSUE TITLE
[AutoSuggest for "Service type"] Step 2 - Ability to search within JSONified data

### ISSUE THREAD

**Issue by davidmpickett** [department-of-veterans-affairs/va.gov-cms#18910]
**[2024-08-16]** Need outputs from #18909 in order to finalize ACs

## User Story or Problem Statement

[18909](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18909) converted Drupal data from the Service Taxonomy into a JSON object. Now we need to create functions that search that JSON object based on given text input to find and rank possible matches.

## Notes from #15054 

> Search logic is based on 526ez Form https://www.va.gov/find-forms/about-form-21-526ez/. If login is needed to view the form, there's a Github login or Laura can help identify the right person to ask.

Here's the file with the autosuggest logic
`src/applications/disability-benefits/all-claims/pages/addDisabilities.js`
in `vets-website`

And here's their schema
`src/applications/disability-benefits/all-claims/content/disabilityLabels.js`

However, it does not suggest one thing if it's related to some other condition only if its typing is closely related. So a `nephro` prefix does not bring up renal or kidney anything or vice-versa

Also, as a side reference:
`src/platform/forms-system/src/js/fields/AutosuggestField.jsx`
This is the field React Component
Not a fuzzy match or special kind of search

The autocomplete field is somewhat complex, but does not do any fuzzy matching or nearest matching, just substring search.

Filters should apply relevancy first, then facility appropriateness (And make the latter optional/modular for future usage)

## Acceptance Criteria
- [x] Inputting a text string returns results that match any taxonomy field included in JSON object
- [x] Results begin to populate after three characters are entered.
- [x] Results are sorted by occurrence frequency of service name and patient-friendly name
- [x] Can be scoped to only include VA Services that are marked as `show for VAMC` if that's easier than pulling in Vet Center and VBA stuff too.
- [x] Ordering should be by.... (fill in blank)

**Comment by eselkin** [comment]
my theory is the object will be
```json
{
  fieldHealthServiceApiId1: {
    name: "xyz",
    aka: "abc",
    commonConditions: "long string with conditions",
    showVetCenters: false,
    showVBA: false,
    showVAMC: true,
    showTricareSpecific: false
  }
}     
```
since we won't do any fuzzy matching, 
1. filter on whether service should be searched through,
2. filter substr match on name || aka || commonConditions

**Comment by jilladams** [comment]
@Agile6MSkinner @mmiddaugh ordering of results will block closing this out. But we can start it.

**Comment by jilladams** [comment]
@eselkin could you add a comment for end of sprint status? I see 2 merged PRs but not sure if this is ready to verify in Prod, or how we go about that.

**Comment by jilladams** [comment]
Ok. It got deployed, so closing.
