### ISSUE TITLE
Establish baseline for Editorial tools satisfaction score 

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#1892]
![Zoom_Meeting.jpg](https://images.zenhubusercontent.com/5d6e57ad330f64311395f08b/bae5f4c5-2671-4289-9364-b6ef21914862)![Zoom_Meeting.jpg]

How do we measure 5% improvement in a scale that goes from 1 to 3

**Comment by jefflbrauer** [comment]
@kevwalsh can you connect with @nickbloom on this please? It was sitting in "new issues" pipeline but Nick was on PTO then.
