### ISSUE TITLE
Content Release Daily Process Fails when GitHub Runners are Unavailable

### ISSUE THREAD

**Issue by 7hunderbird** [department-of-veterans-affairs/va.gov-cms#18923]
## User Story or Problem Statement

- This morning CMS support noticed that Content Release did not start
- DevOps investigated and saw that there were no GitHub Runners available
- There were no GitHub Runners because the Auto Scaling Group had failed to refresh them
- It failed to refresh because an [AMI `ami-0cc4f1573df8d60ce` got pruned](https://us-gov-west-1.console.amazonaws-us-gov.com/cloudtrailv2/home?region=us-gov-west-1#/events?EventName=DeregisterImage)

![CleanShot 2024-08-13 at 10 27 16](https://github.com/user-attachments/assets/a0906861-e1a0-481f-9595-854ce8744a54)

## Description or Additional Context

- Run [Build Platform Base AMI (Manual)](https://github.com/department-of-veterans-affairs/devops/actions/workflows/packer-build-platform-base-manual.yml)
- Run [Build GHAR](https://github.com/department-of-veterans-affairs/devops/actions/workflows/packer-ghar.yml)
- Run an Instance Refresh on the [`dsva-vagov-content-build-gha-runners-asg`](https://us-gov-west-1.console.amazonaws-us-gov.com/ec2/home?region=us-gov-west-1#AutoScalingGroupDetails:id=dsva-vagov-content-build-gha-runners-asg;view=instanceRefresh)

![CleanShot 2024-08-13 at 10 28 33](https://github.com/user-attachments/assets/1b213691-fec0-4f1e-8208-cb5f6cf7ae19)

## Acceptance Criteria
- [X] Complete a [content-release](https://github.com/department-of-veterans-affairs/content-build/actions/runs/10371590383)
- [x] Add doc to confluence on steps

**Comment by 7hunderbird** [comment]
Created https://vfs.atlassian.net/wiki/spaces/PCMS/pages/3378380804/Refresh+GitHub+Runners+for+Content-Release

**Comment by edmund-dunn** [comment]
@7hunderbird You captured everything nicely! I can't see anything you missed!
