### ISSUE TITLE
Knowledge Base Updates for Unattached PDF Deletion Script 

### ISSUE THREAD

**Issue by gracekretschmer-metrostar** [department-of-veterans-affairs/va.gov-cms#18938]
## User Story or Problem Statement
Using the knowledge base, editors need to understand that unattached PDFs will be removed from Drupal CMS. 

## Description or Additional Context 
On either 8/28 or 9/11, CMS team will be implementing a script to delete unattached PDFs from Drupal CMS and then will be running the script on a monthly basis. There is some language within the knowledge base about managing PDFs, so we can likely leverage those existing article to add information about the deletion script. 

## Relevant Links
- [Implement Script to move unattached PDFs from Drupal into S3 Bucket](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18821)
- [Unattached PDF deletion conversation](https://dsva.slack.com/archives/CT4GZBM8F/p1723585357603019)
- [How to Audit the PDF Media Library](https://prod.cms.va.gov/help/how-to-audit-the-pdf-media-library)

## Steps for Implementation
- Write up language about the new deletion task
  - Cadence for cleanup
  - Terminology editors can understand
  - Procedure to restore
- Review knowledge base articles and determine where information about the new deletion task should be added.

## Acceptance Criteria
- [x] VHA Digital Media understands where they can point editors to information about the new PDF deletion script. 
- [x] Editors understand how the PDF deletion script impacts them in their day-to-day work.

**Comment by srancour** [comment]
Latest notes, conversations, and links can be found in the [Confluence page](https://vfs.atlassian.net/l/cp/Nn1mpmhC). Current draft is out for everyone to give feedback on.

**Comment by srancour** [comment]
Published the draft and URL has been sent to VHA Digital Media
