### ISSUE TITLE
Configure dsva-cms-prod-db and dsva-cms-test-prod-db for Database Scans 

### ISSUE THREAD

**Issue by gracekretschmer-metrostar** [department-of-veterans-affairs/va.gov-cms#18940]
## User Story or Problem Statement
We need to create a CMS database user for the VA to use for security scans, so that VA can verify the integrity of our databases, which is a requirement for ATO.

## Description or Additional Context 
Per Hector Barreto: 
> As part of our continued efforts to maintain Security Compliance, the following Production Databases need to be configured to allow DB Scans from the VA.
> dsva-cms-prod-db 
> dsva-cms-test-prod-db

## Relevant Links
- [Slack thread](https://dsva.slack.com/archives/CT4GZBM8F/p1721914741152319)
- [Example PR](https://github.com/department-of-veterans-affairs/devops/commit/5fc2a8e2a8523c9e22b2d222b892fcfef858053f)

## Implementation information
In order to create the user, connect as a DB admin:
- user: `master`, all envs
- password: can be retrieved from ParamStore: https://us-gov-west-1.console.amazonaws-us-gov.com/systems-manager/parameters/?region=us-gov-west-1&tab=Table#list_parameter_filters=Name:Contains:mariadb%2Fmaster_password
- hosts: can be retrieved from RDS Database listings: https://us-gov-west-1.console.amazonaws-us-gov.com/rds/home?region=us-gov-west-1#databases:
  - endpoint is retrievable from each instance: https://us-gov-west-1.console.amazonaws-us-gov.com/rds/home?region=us-gov-west-1#database:id=dsva-cms-prod-db;is-cluster=false
- connection: from e.g. ec2 instance, cms-staging: `mysql -u master -h <endpoint from above> -p` ; password from ParamStore

required username: to be created: `VANSOCSCAN@%`
password: should be created and placed in ParamStore per environment; see equivalents there i.e. `/dsva-vagov/gibct-data-service/prod/VANSOCSCAN`

access requirements: This should be discussed with Hector or with the folks doing the scan. In theory they should only need `SELECT ON *.*` i.e. read-only for all databases. 

Presumably there will also need to be security access groups assigned to the Database for this. We do not appear to manage this database in Terraform, so they may need to be applied manually.

Ingress:
- Per the attached PR, we will need to define an Ingress rule for this. The port that needs ingress is 3306, the standard mysql/mariadb port. Unclear what IP blocks need access. 

Hector will work w/ the teams running the scan once we have completed our work, to confirm that they have the access they need, or with more information on what needs to be modified. We (CMS) do not have to be in contact with the team running the scan.

## Acceptance Criteria
- [x] A user is created in the two dbs with appropriate access, as described above
- [x] An Ingress rule is set up to allow access to the databases from the necessary IP block that the scan will run from
- [ ] We confirm with the office that will run the scan that they have the access they need to conduct their scan

**Comment by 7hunderbird** [comment]
1. I have added credentials in the Parameters Store with the names:

  - `/dsva-vagov/cms-test/staging/VANSOCSCAN`
  - `/dsva-vagov/cms/staging/VANSOCSCAN`
  - `/dsva-vagov/cms-test/prod/VANSOCSCAN`
  - `/dsva-vagov/cms/prod/VANSOCSCAN`
  
2. The `VANSOCSCAN` user was granted select permissions with the command:

```
GRANT SELECT ON dsva_cms_prod.* TO 'VANSOCSCAN'@'%';
```

or in the case of staging it was 

```
GRANT SELECT ON dsva_cms_staging.* TO 'VANSOCSCAN'@'%';
```
  
2. I have created security groups that will open the port for MariaDB on the IP addresses specified in the example.  One for `cms` and `cms-test` in both `staging` and `prod` VPCs.

3. Everything was performed manually and is not in Terraform.

**Comment by 7hunderbird** [comment]
@hgbarreto Do you have an ETA on when they will test that the service account credentials work?

**Comment by 7hunderbird** [comment]
We've submitted to the security team and will close this ticket as complete in the meantime.

![CleanShot 2024-08-27 at 10 00 58](https://github.com/user-attachments/assets/2c52e9c9-cf73-4c2d-ab10-e2e80d29d666)

If for any reason the service account doesn't work we'll re-open this ticket.

**Comment by 7hunderbird** [comment]
These GRANTs have been performed on `cms` and `cms-test` prod RDS databases.
