### ISSUE TITLE
Remove CMS team members from Zenhub

### ISSUE THREAD

**Issue by gracekretschmer-metrostar** [department-of-veterans-affairs/va.gov-cms#18942]
## User Story or Problem Statement
VA OCTO has run out of Zenhub licenses, so we need to remove CMS members who have Zenhub licenses but are not using it. 

## Steps for Implementation
- Post in slack to see who from the CMS and AP team have a Zenhub license and, of those, who uses it.
- Per Alyssa Gallion: You can submit a ticket via /support in the [#vfs-platform-support](https://dsva.slack.com/archives/CBU0KDSB1) channel. Just list their email they use on the account, their full names and GitHub user names so we can easily remove them. 

## Acceptance Criteria
- [ ] Platform support understands which CMS members can be removed from Zenhub.

**Comment by michelle-dooley** [comment]
Request submitted to have the following ZH licenses removed:
@gracekretschmer-metrostar
@srancour 
@timcosgrove 
@edmund-dunn 
@anantais 
@MDomngz 
@keisterj-oddball 
@7hunderbird
