### ISSUE TITLE
CLP: View screen should match Edit screen in Drupal

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#18954]
## Status
**[2024-09-06] [Dave]** Pulled in to sprint as a Site Building ticket
**[2024-08-15] [Fran]** Prioritization not decided yet, but moving to Next Refinement so it will be ready in case this bubbles up.

## Background
In Drupal for the Campaign Landing page content type, the edit screen has multiple sections that can be enabled to build the page. However, very few of these sections actually show on the View screen in Drupal when they are enabled. There is no issue on the FE - everything is working as expected on the FE - this is just a Drupal View issue.

This did however recently lead to quite a bit of confusion when Justin from VHA was trying to add the Downloadable resources section to a page for SECVA. He, as well as the Helpdesk all thought this section was not working because they couldn't see it being added in Drupal. [Slack thread for reference](https://dsva.slack.com/archives/C02730UEZPS/p1723665560987739?thread_ts=1723471792.698979&cid=C02730UEZPS)

## Description
In order to avoid future confusion, we should ensure that all enabled sections on a CLP are also shown on the View screen in Drupal.

Example (This is a tugboat link so it may break but I also have screenshots)
- Drupal Edit screen, I have enabled ALL sections, so this is everything that should be showing on the View screen
  - https://main-2pegzvqcy77ynmcultaityqtlrpfbfoo.demo.cms.va.gov/node/51214/edit
![image](https://github.com/user-attachments/assets/a9422e57-73cf-4297-8189-7a39271a6194)

- Drupal Node view: Only Hero Banner, Why this matters, What can you do, and connect with us show in the accordion style. Then Reusable Q&A show below
  - https://main-2pegzvqcy77ynmcultaityqtlrpfbfoo.demo.cms.va.gov/initiatives/covid-flu
![image](https://github.com/user-attachments/assets/dad4a6f9-9815-4db0-aca0-04d5dc14828f)

## Acceptance Criteria
- [x] All enabled sections on a CLP display on the View screen in the same order as the edit screen
- [x] Optional sections that have never been enabled do not show on the View screen
   - [x] Optional sections that have been enabled and then disabled may still show up on the View screen
- [ ] Requires QA

## Issues out of scope
-  #19161
-  #19163
- #19165

**Comment by laflannery** [comment]
@mmiddaugh I wanted to just let you know I made a ticket for this but I'm not sure if it needs to be prioritized or not. But at least you know it exists now. 

CC: @FranECross

**Comment by FranECross** [comment]
@laflannery Thanks so much! I'll move it to Next Refinement so that it'll be ready in case we do decide to prioritize.

**Comment by davidmpickett** [comment]
Notes:
- Video = not showing
- Spotlight = not showing
- Stories = not showing
- Downloadable resources = not showing
- Events = not showing
- FAQs = showing up at very bottom
- VA benefits = showing up inside of Connect with us

![screencapture-main-sivbehcvqkui7ce9b67dwanfbohmenin-demo-cms-va-gov-initiatives-everything-enabled-2024-09-06-10_52_31](https://github.com/user-attachments/assets/ccbdd337-544b-441e-bab6-dbb084f79b80)

**Comment by davidmpickett** [comment]
Seems like the culprit here is a custom module that would hide unused widgets on View back before that was a core widget functionality (leave "Show if empty" unchecked)

**Comment by davidmpickett** [comment]
My work on the PR is basically done. Enabled and disabled sections are now functioning as expected. I have also rearranged/renamed/reformatted a few fields so the View and Edit screens match better.

Remaining work is writing up QA steps etc.

**Comment by davidmpickett** [comment]
Or maybe I bit off more than I can chew and I need to let someone with more experience tackle this

**Comment by davidmpickett** [comment]
Issues out of scope
- Disabling previously enabled Story -> image validation error
-  Link with summaries -> is required but no asterisk

**Comment by davidmpickett** [comment]
@FranECross @mmiddaugh @laflannery - I would like to request a modification to one of the ACs:
- [ ] Sections not enabled do not show on the View screen

I have a solution working that partially resolves this. It won't show sections of the page that have **never** been enabled.

However, if an editor enables a section and then later disables it without manually clearing out the content, that content will still show on Node View. This is not ideal state, but I'd argue it's still functional.

Resolving this would require a much larger effort and would balloon the size of this ticket. We'd need to tag in an engineer and discuss tradeoffs of various possible solutions. I suggest that we ship my solution which improves 80% of the scenarios.

Here's a comparison from my QA of the current state in Prod vs the state in my tugboat:

 ✅ = Ideal state
⚠️ = Functional but not ideal
⛔ = Not functional

Scenario | Current prod behavior | Tugboat behavior
-- | -- | --
Create a new CLP with no optional panels | Hero banner ✅ <br> Why this matters ✅ <br> What can you do ⚠️ <br>  VA Benefits ⚠️  | Hero banner ✅ <br> Why this matters to you ✅ <br> What you can do ✅ <br>  VA Benefits ✅ 
Create a new CLP with all optional panels |  Hero banner ✅ <br> Why this matters ✅ <br> What can you do ⚠️ <br>  Video ⛔ <br> Spotlight ⛔ <br> Stories ⛔ <br> Downloadable resources ⛔ <br> Events ⛔ <br> FAQs ⚠️  <br> Connect with us ⚠️ <br> VA Benefits ⚠️ | Hero banner ✅ <br> Why this matters ✅ <br> What you can do ✅  <br>  Video ✅  <br> Spotlight ✅  <br> Stories ✅  <br> Downloadable resources ✅  <br> Events ✅  <br> FAQs ✅   <br> Connect with us ✅ <br> VA Benefits ✅ 
Enable an optional panel on an existing CLP |  Video ⛔ <br> Spotlight ⛔ <br> Stories ⛔ <br> Downloadable resources ⛔ <br> Events ⛔ <br> FAQs ⚠️  <br> Connect with us ⚠️ | Video ✅ <br> Spotlight ✅ <br> Stories ✅<br> Downloadable resources ✅ <br> Events ✅ <br> FAQs ✅  <br> Connect with us ✅
Disable an optional panel on an existing CLP | Video ✅ <br> Spotlight ✅  <br> Stories ⛔ <br> Downloadable resources ✅ <br> Events ✅ <br> FAQs ⚠️ <br> Connect with us ⚠️ | Video ⚠️ <br> Spotlight ⚠️  <br> Stories ⛔  <br> Downloadable resources ⚠️ <br> Events ⚠️<br> FAQs ⚠️ <br> Connect with us ✅

**Comment by FranECross** [comment]
@davidmpickett Thanks for providing the amazing table showing prod/future prod. I'm in favor of shipping with the 80% improvement, but defer to Michelle and Laura for final call.

**Comment by mmiddaugh** [comment]
Agree! The table is amazing and shipping an 80% improvement is a great win. 
We may pursue an iteration to the CLP in CY4Q24 so heroic efforts otherwise can wait until then

**Comment by davidmpickett** [comment]
**Likely end of sprint update**
- This is waiting for Code Review, but is low on the priority list given the other Drupal PRs in flight this sprint
