### ISSUE TITLE
Update anchor links on Vet Center edit screen

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#18953]
## Description
The Vet Center content type has anchor links on the Edit screen to help editors easily access various sections of the form. However, some of these links don't actually work and there's aren't links for each section. We should update these to be link we did on VBA:
- Update the heading to be "On this page"
- Ensure that each section has a functional anchor link. That means there should be a link for:
  - Operating status
  - Top of page information
  - Vet Center banner image
  - Vet Center services overview
  - Locations and contact information
  - Prepare for your visit
  - Spotlight content
  - Services
  - How we're different than a clinic

## Acceptance Criteria
- [x] Heading for ToC says "On this page"
- [x] Anchor links match above order
- [x] Anchor links are all functional
- [x] Requires QA

**Comment by davidmpickett** [comment]
Verified on prod https://prod.cms.va.gov/node/add/vet_center
![Screenshot 2024-09-12 at 11 32 00 AM](https://github.com/user-attachments/assets/928f6b9e-79b6-4840-a191-637f4e9aca92)
