### ISSUE TITLE
[Monitoring] Convert the monitor "Facilities Notification of error on Vet Center pages" to [TBD] 

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-cms#18962]
## Status
**[2024-08-19] [Fran]** Blocked by the SPIKE referenced below. This ticket will be updated when the it's decided what mechanism will replace Sentry.

## Description

Sentry will be deprecated, and some monitors for Sitewide products in Datadog rely on Sentry to push up errors, that are then aggregated in Datadog.

We need to convert the following monitor "Facilities Notification of error on Vet Center pages" to mechanism [determined by this SPIKE](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18708)

- Facilities Notification of error on Vet Center pages: https://vagov.ddog-gov.com/monitors/168205/edit

## Acceptance criteria

- [ ] "Facilities Notification of error on Vet Center pages" monitor converted to [TBD]: https://vagov.ddog-gov.com/monitors/168205/edit
- [ ] Datadog monitoring functions as expected for this item

**Comment by FranECross** [comment]
@Agile6MSkinner Per Bryan's note in the Spike, shall I just close this ticket as a no op? (note pasted below)

Facilities Notification of error on Vet Center pages: This one has not occurred in the past 3 months and was implemented using very specific searches on the Sentry side. This being the case, I believe we should deprecate this monitor entirely as we will not have examples to point to if trying to implement this more unique one in Datadog.

**Comment by Agile6MSkinner** [comment]
@FranECross Yep, I think that's the right call

**Comment by FranECross** [comment]
Closing as a no op (see comments above).
