### ISSUE TITLE
Remove feature toggle for CTA Cerner to use v2 API

### ISSUE THREAD

**Issue by eselkin** [department-of-veterans-affairs/va.gov-cms#18982]
## User Story or Problem Statement

Toggle was added to use v2 faclities_api for cerner widget, but never worked and toggle was not removed.

## Acceptance Criteria
- [x] Feature toggle is removed

**Comment by jilladams** [comment]
Requested Platform help to get it out of Flipper UI: https://dsva.slack.com/archives/CBU0KDSB1/p1725555324327549
