### ISSUE TITLE
Header Contact Us link hard coded to point to prod; should be relative to env

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#18984]
## Description
The "Contact us" link in the header is an absolute URL that always points to prod. Clicking this in the staging environment will route user to the actual [va.gov/contact-us](http://va.gov/contact-us).

This is a problem for user research flows or testing that may be conducted in Staging, and redirect logged in users to the production environment, where they aren't.

### Engineering notes / background
Link is set here for modernized site / header: https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/platform/site-wide/user-nav/components/SearchHelpSignIn.jsx#L122
>   href="https://www.va.gov/contact-us/"

Per Randi: 
>  The modernized header can be changed in any way as though the Teamsites header does not exist (and we can make the URL relative). Teamsites should continue to point to prod.

### Quality / testing notes
Make sure we are only modifying the desktop header.

Mobile header and Injected header have separate markup, and shouldn't be modified. 

## Acceptance criteria
- [ ] On desktop, on VA.gov, Contact Us is a relative link that will direct users to the Contact Us page for their current environment (Prod > Prod; Staging > Staging; Tugboat > Tugboat, etc)
- [ ] Notify AP team of the change

**Comment by Agile6MSkinner** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VAgov-Sitewide-Product-Team-6645154188a81a1f7a0a9464/issues/department-of-veterans-affairs/va.gov-cms/18984?planning-poker) with Zenhub @mmiddaugh @FranECross

**Comment by Agile6MSkinner** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VAgov-Sitewide-Product-Team-6645154188a81a1f7a0a9464/issues/department-of-veterans-affairs/va.gov-cms/18984?planning-poker) with Zenhub @chriskim2311 @eselkin

**Comment by chriskim2311** [comment]
Verified on prod, closing!
