### ISSUE TITLE
Update the drupal/pathauto module

### ISSUE THREAD

**Issue by edmund-dunn** [department-of-veterans-affairs/va.gov-cms#18998]
## User Story or Problem Statement
Update the `drupal/pathauto` to v1.13.0 and reroll or remove the patch

## Steps for Implementation
- [ ] Update the `drupal/pathauto` to v1.13.0
- [ ] Reroll or remove the patch as necessary
- [ ] Confirm that it applies cleanly (without error) by QAing a content type that uses that module.

## Acceptance Criteria
- [ ] Drupal/pathauto module is upgraded to v1.13.0

**Comment by anantais** [comment]
This one has an unusual issue where it is failing due to the info.yml file. So far I have not had luck with online troubelshooting.
