### ISSUE TITLE
Update drupal/metatag module

### ISSUE THREAD

**Issue by edmund-dunn** [department-of-veterans-affairs/va.gov-cms#18995]
## User Story or Problem Statement
The drupal/metatag modules need to be updated to v2.0.2. The patch associated with the drupal/metatag module will need to be re-rolled.

## Steps for Implementation
- [ ] Update the `drupal/metatag` module to v2.0.2
- [ ] Remove or reroll patch as necessary
- [ ] Confirm that it applies cleanly (without error) by QAing a content type that uses that module.

## Acceptance Criteria
- [ ] drupal/metatag module is upgraded v2.0.2

**Comment by gracekretschmer-metrostar** [comment]
Idea more generally: start templating this work.

**Comment by gracekretschmer-metrostar** [comment]
Replicate [this ticket](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18705) format for this existing ticket.
