### ISSUE TITLE
Update the drupal/admin_toolbar module

### ISSUE THREAD

**Issue by edmund-dunn** [department-of-veterans-affairs/va.gov-cms#18996]
## User Story or Problem Statement
Update the `drupal/admin_toolbar` to v3.5.0 and reroll or remove the patch

## Acceptance Criteria
- [ ] Update the `drupal/admin_toolbar` to v3.5.0
- [ ] Remove or reroll the patch

**Comment by gracekretschmer-metrostar** [comment]
Replicate https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18705 format for this existing ticket.

**Comment by gracekretschmer-metrostar** [comment]
@anantais let's keep this open into the PR is fully pushed through.
