### ISSUE TITLE
Update the drupal/openapi_jsonapi module

### ISSUE THREAD

**Issue by edmund-dunn** [department-of-veterans-affairs/va.gov-cms#18997]
## User Story or Problem Statement
Update the `drupal/openapi_jsonapi` module to v3.0.5 and remove or reroll patch

## Acceptance Criteria
- [ ] Update the `drupal/openapi_jsonapi` module to v3.0.5
- [ ] remove or reroll patch as necessary

**Comment by gracekretschmer-metrostar** [comment]
Replicate https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18705 format for this existing ticket.
