### ISSUE TITLE
Update drupal/smart_date module

### ISSUE THREAD

**Issue by edmund-dunn** [department-of-veterans-affairs/va.gov-cms#18994]
## User Story or Problem Statement
Update `drupal/smart_date` to v4.1.5 and address the patch

## Acceptance Criteria
- [ ] Update `drupal/smart_date` to v4.1.5 
- [ ] remove or reroll patch as necessary

**Comment by gracekretschmer-metrostar** [comment]
Closing this ticket to fold in this work in this ticket: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18706
