### ISSUE TITLE
Prep for DUW usability research

### ISSUE THREAD

**Issue by davidmpickett** [department-of-veterans-affairs/va.gov-cms#19003]
### User story
**AS A** Researcher
**I WANT** to complete all the details for setting up DUW usability research
**SO THAT** the research will happen successfully

## For Veteran-facing research 
**Finalize research deliverables**

[Github research folder
](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/veteran-military-records/discharge-upgrade-wizard/research/2024-Review-Flow)

- [x] Update research plan and conversation guide with any timeline or protocol tweaks
- [x] Include AT session details in research plan
- [x] Create conversation guide for AT participants
- [x] Identify time slots for research sessions (twice as many slots as # of participants desired)
- [x] Final approval obtained and documented at the bottom of the files in preparation for Research Review cycle

**Coordinate with Research-Ops and Perigean**
- [x] Create recruiting request and submit to VA Research-Ops. Use *Easy Recruitment Request* (for moderated research) or *Easy Recruitment Request for Unmoderated Cohorts* (for unmoderated research) on [this page](https://github.com/department-of-veterans-affairs/va.gov-research-repository/issues/new/choose)
  - Schedule 20-25% more sessions than the desired # of participants to account for no-shows & cancellations 
  - [DUW research recruitment request](https://github.com/department-of-veterans-affairs/va.gov-research-repository/issues/703)
- [x] Create *New Research Intake* request from [this page](https://github.com/department-of-veterans-affairs/va.gov-research-repository/issues/new/choose)
  - [x] In description, add links to github research folder and (from previous step) recruiting request form
  - [x] Make yourself the assignee
  - [x] Add labels for the project's product, research methodology, audience, etc. from [this list](https://github.com/department-of-veterans-affairs/va.gov-research-repository/labels?page=1&sort=name-asc)
  - [DUW research intake request](https://github.com/department-of-veterans-affairs/va.gov-research-repository/issues/704)
- [x] Make agenda for kickoff meeting w/Perigean
- [x] Review Perigean's recruitment survey before kickoff meeting
- [x] Attend kickoff meeting with Perigean and Sitewide UX Lead and/or PM
- [x] Test Zoom login from Perigean 
- [x] Change display name of Perigean Zoom account to "*<Moderator's first name>* (Moderator)" 

**Notetaking prep**
- [x] Make note-taking spreadsheet/Mural
- [x] Create a Mural board for research debrief sessions and/or data synthesis ([Mural board link](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1726091853497/11d98e6ba53e1a738c258f67c2671a8e43d7908c?sender=u01810f3edbfc878c08be5925))

**Pilots** 
[Guidance here](https://depo-platform-documentation.scrollhelp.site/research-design/research-checklist#Researchchecklist-4-Run-a-pilot-session4.Runapilotsession)
- [x] Recruit pilot participant(s) from your company or another one
- [x] Schedule pilot(s) 
- [x] Slack your Perigean lead with the date, time, and participant for your pilot(s)
- [x] Schedule team debrief sessions after each pilot 
- [x] Schedule prep time before and debrief time after each pilot 
- [x] Confirm the day before with pilot participant(s) 
- [x] Run pilot(s) 
- [x] Debrief pilot(s) with team
- [x] Make any revisions needed to conversation guide and prototype
- [x] Send thank you slack message to pilot participant(s) 

**Recruitment / scheduling sessions** (for moderated research only)
- [x] Review recruited participant list from Perigean for requirements met
- [x] Follow-up with Perigean re participant list, if needed
- [x] Make sure all research sessions scheduled by Perigean are in your calendar
- [x] Make signup sheet for observers, and share with team, stakeholders to sign up ([template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/regional-offices/research/observer_schedule_template.xlsx))
- [x] Invite signed up observers to each session and optional debrief session, per signup sheet
- [x] Add participant numbers, dates, and times into recruitment intake ticket Participant Tracker (to check off later after each session) 
- [x] Make notetaking doc in github for each session to share with Perigean right before each session starts (or all at once ahead of time if Perigean contact is OK with this)
- [x] Schedule 30-minute team debrief sessions once a day, and invite all observers signed up to observe in the previous 24 hours
- [x] Schedule prep and debrief time for each session
- [x] Slack/email all observers with instructions

## Acceptance Criteria
- [x] The target number(s) of participants have been recruited and scheduled (for overall & primary criteria)
- [x] The moderator(s), notetaker(s), and observer(s) have been invited to research sessions and daily debriefs
- [x] Pilot session(s) have been conducted
- [x] All preparation done before the first day of research sessions

**Comment by davidmpickett** [comment]
@thejordanwood I found the place where the math exists for how many participants we recruit based on how many sessions we want to complete. This research prep ticket is also the place where we circle back and finalize the Research Plan and Conversation guide, so it's a good placeholder for any things you want to go back and address

**Comment by FranECross** [comment]
@thejordanwood Did you mention this morning that this might be a candidate for Sprint 14? I wanted to be sure I didn't tag it as such if I misremembered. Thanks!

**Comment by thejordanwood** [comment]
@FranECross Yes, this will be my priority for Sprint 14.

**Comment by thejordanwood** [comment]
Pilot sessions and recruitment are completed. We're moving to [this ticket](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19503) as our next step!
