### ISSUE TITLE
Comprehensive Test Plan: Identify and Script E2E Tests For Additional Content Types

### ISSUE THREAD

**Issue by keisterj-oddball** [department-of-veterans-affairs/va.gov-cms#19002]
## User Story or Problem Statement
As a member of the CMS Team, I want better automated test coverage for editor focused functionality within the CMS, so that I am more confident in the ability to make code changes without breaking existing functionality used by editors.

## Description or Additional Context 
In order to improve automated test coverage for editor focused functionality within the CMS, eligible content types must be identified as pilots, and cypress tests should be created for said content types.

## Steps for Implementation

1. Identify 2-3 content types that make sense for the CMS Team to independently script cypress tests for
2. Script cypress tests to create and mark instances of each identified content type as published
3. Identify a way to annotate existing test scripts as "Critical" or "Regression" for later prioritization

## Acceptance Criteria
- [ ] A cypress test should be scripted for each identified content type
- [ ] Each test should create a node of the respective content type and mark it as published
- [ ] The newly scripted tests should be annotated as "Critical" for later test run segmentation
- [ ] The tests should pass locally, in tugboat, and on staging
- [ ] The tests should be able to be run repeatedly without failure

**Comment by keisterj-oddball** [comment]
Candidate content types: News Release, Story, Benefits Detail Page

**Comment by gracekretschmer-metrostar** [comment]
@keisterj-oddball for sprint 17, I am going to pull in @JakeBapple to support in you implementing these test scripts.

**Comment by gracekretschmer-metrostar** [comment]
Feedback from Jon: there could be helpful to bring in sitewide team to help script these tests because there's complexity and interdependence of the content types.

**Comment by keisterj-oddball** [comment]
@gracekretschmer-metrostar The addition of these 3 test scripts brings our test coverage of content creation from 22% to 28% coverage.
