### ISSUE TITLE
Add script to start port-forwarding session to DevOps repo

### ISSUE THREAD

**Issue by eselkin** [department-of-veterans-affairs/va.gov-cms#19007]
## User Story or Problem Statement

Currently starting port-forwarding is a manual process with several scripts and aws CLI commands. We need a script that synthesizes acquiring an AWS instance of an application, and starting the port forwarding session (remembering this command is hard).

## Description or Additional Context 

Starting port-forwarding is a multi-step procedure. There is a script for sshing via ssm into an instance for an application (e.g. fwdproxy) but doesn't do port forwarding.

## Steps for Implementation

1. Write script
2. Test script

## Acceptance Criteria
- [ ] Script is written for port forwarding in devops repo

**Comment by jilladams** [comment]
This has been merged for a couple days and is developer facing, so I'm gonna assume it's working and close it, but if you need toreopen for follow ups, feel free.
