### ISSUE TITLE
Establish common vocabulary for Editorial Workflow

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#1900]
## Owner
@rachel-kauff 

## Background

Editorial Workflow is complex and terms used to describe it very often clash with other important elements of the CMS or are confusing due to ambiguity.

A common vocabulary around Editorial Workflow must be established to unify and provide clarity to the efforts of design, training and engineering teams.

## Artifacts
- [EWA Vocabulary (Mural)](https://app.mural.co/t/vagov6717/m/vagov6717/1591809342617/3e4e84aa3a1bf7e67e1651d699de781c8f94187f)

## AC

- common vocabulary is established for referencing components of the Editorial Workflow (assignments):
   - component naming (e.g. component, sub-component names / labels)
   - definition for commonly used Drupal terms (state, transition, etc.)

**Comment by jordanamello** [comment]
Link to the Mural where this work will be done: https://app.mural.co/t/vagov6717/m/vagov6717/1591028145892/1ef11c627afd3437fe97a46cc57640eb9603328c
cc @rachel-kauff

**Comment by oksana-c** [comment]
linking @rachel-kauff 's Airtable - [Editorial Workflow and Assignments codified language](https://airtable.com/tblBN7rDqhagQCAJR/viwojsfCvWPTKErTL?blocks=hide)
