### ISSUE TITLE
QA for Accelerated Publishing Events

### ISSUE THREAD

**Issue by Agile6MSkinner** [department-of-veterans-affairs/va.gov-cms#19015]
## Descriptions
AP team will have Events and Event listings builds ready for testing by August 28. 

## ACs

- [ ] Events build is verified for parity with production, including
  - [ ] Events filters: Past
  - [ ] Events filters: Upcoming
  - [ ] Events filters: Specific date
  - [ ] Events filters: Date range
  - [ ] Recurring events presentation
  - [ ] Events appearing on both Outreach Events calendar and VAMC calendar if checkbox is selected in Drupal
  - [ ] Basic events metadata all presents / is correct 
    - [ ] On Event listing page
    - [ ] On Event detail page
  - [ ] Conditionals are correct
  - [ ] Feedback is provided in pull request

**Comment by jilladams** [comment]
R ealized we have an olde rticket with some comments history, so collapsing this in to #16660
