### ISSUE TITLE
Visualization of the editorial workflow process

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#1901]
## Owner

@jordanamello 

## Description

Create a visualization of the editorial workflow process to:
  - Provide clarity on content moderation workflow in terms of state transitions and actions
  - Use in training/onboarding materials/user guide

## Acceptance Criteria

* artifact that describes editorial workflow in terms of actions and state transitions. Available states:
    * DRAFT
    * IN REVIEW
    * APPROVED
    * PUBLISHED
    * ARCHIVED

## Implementation

- [x] create an artifact
- [x] validate with team
- [x] revise an artifact as/if needed

## Labels
- [/] Issue type (red) (defaults to task)
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [ ] CMS objective (orange)
- [ ] CMS-supported product (black)

**Comment by kevwalsh** [comment]
@jordanamello @oksana-c I'm reviewing this with @rachel-kauff and we're wondering if we can keep this "low fidelity" for now, since we won't be training on it for some time. It's also somewhat interdependent on the #1900 (common vocabulary), owned by @rachel-kauff.
