### ISSUE TITLE
Include Vet Center - Facility Service in Facility Services content audit

### ISSUE THREAD

**Issue by omahane** [department-of-veterans-affairs/va.gov-cms#19013]
## User Story or Problem Statement
[Facility services content audit](https://prod.cms.va.gov/admin/content/audit/facility-services) should include Vet Center - Facility Services

## Screenshot
<img width="1280" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL2QyQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--311ffcca6a042308657ad463dd4dff1eae3f5627/Screenshot%202024-08-21%20at%2011.20.24%E2%80%AFAM.png" alt="Screenshot 2024-08-21 at 11.20.24 AM.png" />

## Steps for Implementation
- Update the view
  - Include Vet Center - Facility Service in the results
  - Include Vet Center - Facility Service in the exposed filter 

## Acceptance Criteria
- [ ] Vet Center - Facility Service shows in the results
- [ ] Vet Center - Facility Service shows in the exposed filter 
- [ ] Requires design review
- [ ] Requires accessibility review

**Comment by omahane** [comment]
@laflannery @thejordanwood I noticed that Facility and API ID do not show for VBA (pre-existing missing functionality). They don't show for Vet Center, either. I still think this addition is a benefit and makes things easier, especially now that it kind of matters that Vet Center services are draft and shouldn't be published. I can add another ticket to fix the facility and api id display for non-VAMC.

**Comment by jilladams** [comment]
Merged today, will deploy on Wed 9/18 and can be verified.

**Comment by jilladams** [comment]
![Screenshot 2024-09-19 at 2 02 44 PM](https://github.com/user-attachments/assets/18addbc5-b387-4a53-b7a3-4f5780e87756)

Closing!
