### ISSUE TITLE
URL Change for: Garnett VA Clinic - Awaiting Redirect

### ISSUE THREAD

**Issue by TroyCMSSupport** [department-of-veterans-affairs/va.gov-cms#19036]
Parent ticket: #19035 

### Implementation date
When does this request need to be live:
ASAP

### Instructions for URL redirect
(Note: This issue will be used from initial request through implementation to ensure all individuals working on this are notified of status updates.  Please do not create multiple issues to track different steps.)
- [x] Notify VA stakeholders as appropriate.
- [x] Link the related facility closure / rename issue. https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19035
- [x] Create a URL redirect in the [vsp-platform-revproxy](https://github.com/department-of-veterans-affairs/vsp-platform-revproxy) repo in `template-rendering/revproxy-vagov/vars/redirects.yml`
- [x] Add the "Awaiting redirect" flag to the facility node with a revision log message that includes a link to this ticket, preserving the node's current moderation state.
- [x] Redirects deploy daily except Friday at 10am ET, or by requesting OOB deploy (of the revproxy job to prod) in #vfs-platform-support. After deploy, validate that the URL redirect is deployed. (Note: In the event of a facility closure or a name change,  validate that this occurs before making the Lighthouse csv changes.)
- [x] Update this ticket with a comment that the redirect has been deployed.
- [x] Remove the "Awaiting redirect" flag on the facility node with a revision log message that includes a link to this ticket, preserving the node's current moderation state.
- [x] Notify helpdesk via comment on ticket or Slack message in #cms-support that changes are ready for review.

#### URL Redirect
| Current URL  |  Redirect Destination or New URL |
| ---  |  --- |
| [https://www.va.gov/eastern-kansas-health-care/locations/garnett-va-clinic](https://www.va.gov/eastern-kansas-health-care/locations/garnett-va-clinic) | [https://www.va.gov/eastern-kansas-health-care/locations/](https://www.va.gov/eastern-kansas-health-care/locations/) |

### Instructions for canonical URL removal
- [x] Try to find the facility via the Facility Locator, using the Facility API ID (e.g. https://va.gov/find-locations/facility/"facility_api_id"). If it is not available, proceed.
- [x] Contact Lighthouse via Slack at #cms-lighthouse channel that this facility requires a canonical link to be removed in the following format (replacing the placeholder data with the actual API Id and VA.gov URL):
  - `vha_691GM,https://www.va.gov/greater-los-angeles-health-care/locations/oxnard-va-clinic/`

**Note: there's no check to see if it's not returning anything, as it should already be not showing anything in the Facility Locator.**

#### URL removal example (update with actual ID and URL to remove)
| Facility API ID  |  Full VA.gov URL |
| ---  |  --- |
| vha_589GP | https://www.va.gov/eastern-kansas-health-care/locations/garnett-va-clinic |

**Comment by TroyCMSSupport** [comment]
@omahane @jilladams @ian-sears - [Facility Closure ticket for Garnett VA Clinic](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19035), as well as the URL Change for Garnett VA Clinic have been created

**Comment by omahane** [comment]
@TroyCMSSupport Thanks for making this. As a reminder, closed facilities redirect to the locations page on the system:
<img width="843" alt="Screenshot 2024-08-23 at 10 18 34 AM" src="https://github.com/user-attachments/assets/74363d71-7e32-4fe9-b543-115908a24775">

`https://www.va.gov/eastern-kansas-health-care/locations/` instead of 
`https://www.va.gov/eastern-kansas-health-care/`

**Comment by TroyCMSSupport** [comment]
@omahane - I've updated to include 'locations/'  -- Thank you!

**Comment by jilladams** [comment]
Blocked by https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19405

**Comment by ian-sears** [comment]
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19405 is now complete, ubnblocking this request for the URL redirect.

Please intiate a URL Redirect
[FROM]: https://www.va.gov/eastern-kansas-health-care/locations/garnett-va-clinic
[TO]: https://www.va.gov/eastern-kansas-health-care/locations/
as specified above.
Please alert @department-of-veterans-affairs/platform-cms-helpdesk once complete.

@omahane

**Comment by omahane** [comment]
Redirect has been made.

**Comment by omahane** [comment]
The redirect has been merged. It should deploy tomorrow.

**Comment by TroyCMSSupport** [comment]
@ian-sears @omahane @jilladams Issue complete -
URL now points to VAMC locations for the home facility.
Location no longer appears in VA.gov Locator
Site will now be archived 

https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19035
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19036
