### ISSUE TITLE
Explore options for reducing Tugboat disk space usage

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#19043]
## User Story or Problem Statement
Tugboat's disk usage frequently grows into 75% or more of total disk capacity, and it trends upwards. We should figure out how to automatically keep disk space managed so that the system is self-maintaining.

## Description or Additional Context 
Right now one of the main drivers of Tugboat disk space usage is previews which drift from their base preview. Currently the safest method to resolving the disk space issue is to rebuild previews. However, this is a manual process, and it only lasts a day, given that the base preview itself refreshes each night.

Preview drift may not be the only driver of Tugboat disk usage. It would be good to look at Tugboat disk usage in general to make sure that there are not other parts of the system that are growing.

## Some potential options to explore:
- Simply increase the available disk size
- Set up previews to auto refresh. Note that there are some previews that must not be refreshed, including but potentially not limited to
  - The editor training environment: https://tugboat.vfs.va.gov/625069040356a782461a4fd8
  - The sprint demo environment: https://tugboat.vfs.va.gov/6500a7642d3036648d189cc6

It would be good to discuss the general problem with #tugboat-support to figure out how other instances have dealt with this issue, if they have faced it.

## Acceptance Criteria
- [ ] Tugboat disc space usage is reduced through a process that is automated and sustainable.

**Comment by timcosgrove** [comment]
One of the options for doing this is simply to turn on 'Rebuild Stale Previews Automatically' for the CMS PR project. This would tell Tugboat to refresh all the previews in that project after the Main preview has been updated, which currently happens nightly at 2 or 3 am depending on DST. See https://tugboat.vfs.va.gov/5fd3b8ee7b4657022b5722d6/settings/ (repository admin required).

I tested this by checking that box, then running a manual mid-day rebuild on the Main preview. These were the results:
1. Main took approximately 90 minutes to rebuild, as normal.
2. Once it completed, all the previews in that project immediately started rebuilding. Tugboat became slow to respond, but it did not crash.
3. Approximately 10 of the preview rebuilds immediately failed with this message or equivalent: `2024-08-27T23:37:22.405Z - Rebuilding preview: 66cce9c2ad8c5b097ab7ba99 (pr19047) / 2024-08-27T23:40:54.177Z - Internal Error (Tugboat Error 2000): (HTTP code 500) server error - unrecognized image ID sha256:af0545d49c1f3defcd0e0b76868de1c6ec97b3d6e536f4f60f3e64538911f4d5`
4. Several of the previews failed about 5 minutes in with this message: `The .git directory is missing from /var/lib/tugboat/docroot/vendor/va-gov/content-build, see https://getcomposer.org/commit-deps for more information`
5. Additionally, a number of the previews failed with composer.lock conflicts. This makes sense; rebuilding essentially updates the code on the instance to match Main and then applies the PR code to it. However, this means that some instances can get into a failure state which is unexpected. 
6. Running manual rebuilds on the errors from 3 and 4 eventually allowed many of them to rebuild successfully. The ones that continued to fail failed because of composer.lock issues. 

This did have a very sizable positive impact on Tugboat disk space usage: 
<img width="1223" alt="image" src="https://github.com/user-attachments/assets/04b64f79-c0ed-4df7-a2e2-af6c0fccc83f">

However, I believe we cannot use this mechanism as-is without some troubleshooting. The problems in 3 & 4 would probably require some input from Tugboat Support, since they appear to be transient and solvable with a simple rebuild. Problem 5 is more difficult; we would need to know if the code in a given instance can safely be updated before updating it, and it is not clear that that is something Tugboat can currently do.

More research is needed. This may not be able to be the path we use for this.

**Comment by gracekretschmer-metrostar** [comment]
Per Edmund: next steps is to 4x the disc space so that we can have a quick fix and resolve the issue, knowing our capacity limitations.

**Comment by edmund-dunn** [comment]
We will also reduce concurrence to 8 and turn on nightly rebuilds for all PR environments.

**Comment by edmund-dunn** [comment]
Extended disk space out to 1tb for OS.
