### ISSUE TITLE
[Community Care] [QA] Test the changes made in #18986:  Increase the Mapbox radius for both zip code & city search results; increase results from 10 to 15

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-cms#19045]
## Description

In an attempt to return more Community Care Providers during city/state, and postal code searches, ticket #18986 will implement increasing the Mapbox boundary (for CCPs only) to 20, as well as increasing the number of search results returned from 10 to 15. 

To ensure there are no unintended consequences occurring with these changes, we'll be robustly testing all types of Facilities/Service providers against the AC below.

### User story

**AS A** Veteran, their caregiver or family member
**I WANT** to be able to view all providers withing a given zip code or city when I use that criteria in a Facility Locator search
**SO THAT** I'm aware of all choices near me or within the area I'm interested in.

### Search Results Testing

_Note that the tests were edited to take into account there isn't away to get a list of CC facilities in order to fully test. We can test to see if more than 10 are returned, and to validate existing behavior is correct._

**_Scenario 1_: Community Care Search by City, State**

**Tests to Perform**

- [x] **Facility Type:** Urgent care; **Service type:** In-network community urgent care 
  - [x] expected search results display more than the previous 10 (15 if there are that many) of this Facility Type/Service Type combo only (when 15 or more results are found)
  - [x] expected search results displays correctly when less than 15 results are returned
  - [x] expected message displays when there are no results
  - [x] expected details for this Facility/Service Type display in search results
- [x] **Facility Type:** Emergency care; **Service type:** In-network community emergency care 
  - [x] expected search results display more than the previous 10 (15 if there are that many) of this Facility Type/Service Type combo only (when 15 or more results are found)
  - [x] expected search results displays correctly when less than 15 results are returned
  - [x] expected details for this Facility/Service Type display in search results
  - [x] expected message displays when there are no results
- [x] **Facility Type:** Community providers (in VA's network) ; **Service type** Enter a service type (test several)
  - [x] expected search results display more than the previous 10 (15 if there are that many) of this Facility Type/Service Type combo only (when 15 or more results are found)
  - [x] expected search results displays correctly when less than 15 results are returned
  - [x] expected details for this Facility/Service Type display in search results
  - [x] expected message displays when there are no results
- [x]  **Facility Type:** Community pharmacies (in VA's network); _Service Type field disabled_
  - [x] expected search results display more than the previous 10 (15 if there are that many) of this Facility Type only (when 15 or more results are found)
  - [x] expected search results displays correctly when less than 15 results are returned
  - [x] expected details for this Facility/Service Type display in search results
  - [x] expected message displays when there are no results

**_Scenario 1.1_: Non-CCP Search by City, State**

- [x] **Facility Type:** VA Health; **Service Type**:  _test each service type_
    - [x] expected search results still display 10 of these Facility Type/Service Type combos only (when 10 or more are found)
    - [x] expected search results displays correctly when less than 10 results are returned
    - [x] expected details for this Facility/Service Type display in search results
    - [x] expected message displays when there are no results
- [x] **Facility Type:** Urgent Care
  - [x] **Service Type:** All In-network urgent care
    - [x] expected search results display still 10 of this Facility Type/Service Type combo only (when 10 or more are found)
    - [x] expected search results displays correctly when less than 10 results are returned
    - [x] expected details for this Facility/Service Type display in search results
    - [x] expected message displays when there are no results
  - [x] **Service Type:** VA urgent care
    - [x] expected search results display still 10 of this Facility Type/Service Type combo only (when 10 or more are found)
    - [x] expected search results displays correctly when less than 10 results are returned
    - [x] expected details for this Facility/Service Type display in search results
    - [x] expected message displays when there are no results
- [x] **Facility Type:** Emergency Care
  - [x] **Service Type:** All In-network emergency care
    - [x] expected search results display still 10 of this Facility Type/Service Type combo only (when 10 or more are found)
    - [x] expected search results displays correctly when less than 10 results are returned
    - [x] expected details for this Facility/Service Type display in search results
    - [x] expected message displays when there are no results
  - [x] **Service Type:** VA emergency care
    - [x] expected search results display still 10 of this Facility Type/Service Type combo only (when 10 or more are found)
    - [x] expected search results displays correctly when less than 10 results are returned
    - [x] expected details for this Facility/Service Type display in search results
    - [x] expected message displays when there are no results
- [x] **Facility Type:** VA benefits; **Service Type**:  _test each service type_
  - [x] expected search results display still 10 of these Facility Type/Service Type combos only (when 10 or more are found)
  - [x] expected search results displays correctly when less than 10 results are returned
  - [x] expected details for this Facility/Service Type display in search results
  - [x] expected message displays when there are no results
- [x] **Facility Type:** VA cemeteries; **Service Type:** _field disabled_
  - [x] expected search results display still 10 of this Facility Type only (when 10 or more are found)
  - [x] expected search results displays correctly when less than 10 results are returned
  - [x] expected details for this Facility/Service Type display in search results
  - [x] expected message displays when there are no results
- [x] **Facility Type:** Vet Centers; **Service Type:** field disabled_
  - [x] expected search results display still 10 of this Facility Type only (when 10 or more are found)
  - [x] expected search results displays correctly when less than 10 results are returned
  - [x] expected details for this Facility/Service Type display in search results
  - [x] expected message displays when there are no results

**_Scenario 2_: Community Care Search by postal code**

- [x] **Facility Type:** Urgent care; **Service type:** In-network community urgent care 
  - [x] expected search results display more than the previous 10 (15 if there are that many) of this Facility Type/Service Type combo only (when 15 or more results are found)
  - [x] expected search results displays the correct number when less than 15 results are returned
  - [x] expected details for this Facility/Service Type display in search results
  - [x] expected message displays when there are no results
- [x] **Facility Type:** Emergency care; **Service type:** In-network community emergency care 
  - [x] expected search results display more than the previous 10 (15 if there are that many) of this Facility Type/Service Type combo only (when 15 or more results are found)
  - [x] expected search results displays the correct number when less than 15 results are returned
  - [x] expected details for this Facility/Service Type display in search results
  - [x] expected message displays when there are no results
- [x] **Facility Type:** Community providers (in VA's network) ; **Service type:** Enter/choose several Service types
  - [x] expected search results display more than the previous 10 (15 if there are that many) of these Facility Type/Service Type combos only (when 15 or more results are found)
  - [x] expected search results displays the correct number when less than 15 results are returned
  - [x] expected details for this Facility/Service Type display in search results
  - [x] expected message displays when there are no results
- [x]  **Facility Type:** Community pharmacies (in VA's network); **Service type:** _Service Type field disabled_
  - [x] expected search results display more than the previous 10 (15 if there are that many) of this Facility Type only (when 15 or more results are found)
  - [x] expected search results displays the correct number when less than 15 results are returned
  - [x] expected details for this Facility/Service Type display in search results
  - [x] expected message displays when there are no results

**_Scenario 2.1_: Non-CCP Search by postal code**

- [x] **Facility Type:** VA Health; Service Type; **Service type:** test each service type
    - [x] expected search results display 10 of these Facility Type/Service Type combos only (when 10 or more are found)
    - [x] expected search results displays correct number when less than 10 results are returned
    - [x] expected details for this Facility/Service Type display in search results
    - [x] expected message displays when there are no results
- [x] **Facility Type:** Urgent Care
  - [x] **Service Type:** All In-network urgent care
    - [x] expected search results display 10 of this Facility Type/Service Type combo only (when 10 or more are found)
    - [x] expected search results displays correct number when less than 10 results are returned
    - [x] expected details for this Facility/Service Type display in search results
    - [x] expected message displays when there are no results
  - [x] **Service Type:** VA urgent care
    - [x] expected search results display 10 of this Facility Type/Service Type combo only (when 10 or more are found)
    - [x] expected search results displays correct number  when less than 10 results are returned
    - [x] expected details for this Facility/Service Type display in search results
    - [x] expected message displays when there are no results
- [x] **Facility Type:** Emergency Care
  - [x] **Service Type:** All In-network emergency care
    - [x] expected search results display 10 of this Facility Type/Service Type combo only (when 10 or more are found)
    - [x] expected search results displays correct number  when less than 10 results are returned
    - [x] expected details for this Facility/Service Type display in search results
    - [x] expected message displays when there are no results
  - [x] **Service Type:** VA emergency care
    - [x] expected search results display 10 of this Facility Type/Service Type combo only (when 10 or more are found)
    - [x] expected search results displays correct number when less than 10 results are returned
    - [x] expected details for this Facility/Service Type display in search results
    - [x] expected message displays when there are no results
- [x] **Facility Type:** VA benefits; **Service type:** service type disabled
    - [x] expected search results display 10 of these Facility Type/Service Type combos only (when 10 or more are found)
    - [x] expected search results displays correct number when less than 10 results are returned
    - [x] expected details for this Facility/Service Type display in search results
    - [x] expected message displays when there are no results
- [x] **Facility Type:** VA cemeteries; **Service Type** field disabled
  - [x] expected search results display 10 of this Facility Type only (when 10 or more are found)
  - [x] expected search results displays correct number when less than 10 results are returned
  - [x] expected details for this Facility/Service Type display in search results
  - [x] expected message displays when there are no results
- [x] **Facility Type:** Vet Centers; **Service type:** _Service Type field disabled_
  - [x] expected search results display 10 of this Facility Type only (when 10 or more are found)
  - [x] expected search results displays correct number when less than 10 results are returned
  - [x] expected details for this Facility/Service Type display in search results
  - [x] expected message displays when there are no results

**Comment by eselkin** [comment]
Scenario 1.1 all passed. The exceptions are not exceptions really, The Urgent Care and Emergency Care All in-network didn't ever just return 10 and no count was ever provided.

**Comment by eselkin** [comment]
Scenario 2.1 all passed

**Comment by FranECross** [comment]
All passed; closing
