### ISSUE TITLE
Notifications framework architecture

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#1905]
## Description

We have completed an inventory of the [CMS notifications](https://docs.google.com/spreadsheets/d/1M0a4VBcuNxpYuhDDpARQdlpRXaeXG_K9JyVCV9xCu6c) that are expected to be implemented in the short/long-term. It's time to select a framework that will support all required notification channels and is scalable to support future needs yet to be identified.

## Acceptance Criteria

- [x] analysis of notification frameworks that are available as contributed modules in Drupal is performed while taking into account the outcomes of the spike #3156. Contrib candidates [Courier](https://www.drupal.org/project/courier), [Message](https://www.drupal.org/project/message) etc. 
     * we need to cover various notifications channels: email, slack, notifications center 
     * notifications are sent out close to real-time
     * notifications need to fail safe. e.g. if a notification cannot be sent to an appropriate channel due to any failures, this notification is queued and resent as soon as the failure is addressed
- [x] we know whether we can use any contributed DO solution or build our own
- [x] we know what third-party services we need to integrate with if any (e.g. AWS)
    * notifications should be queued - we may need to build a queue runner due to the real-time nature of most notifications
- [ ] we've planned/architected a framework that allows us to build highly customized UIs and allow our user granular control over their notifications, can scale over multiple channels (email,Slack, etc) and consume various types of content (editorial workflow events, broken link events, cms announcements, other)
- [ ] notifications framework architecture diagram is developed and finalized w/ a focus group (@indytechcook @oksana-c )

**Comment by oksana-c** [comment]
The effort to map out notifications framework architecture is in progress. The deliverable will be finalized next week after the team had a chance to meet and iterate on the approach.

Removing `Planned work` label in Sprint 18 and will retag as Planned for Sprint 19.

**Comment by oksana-c** [comment]
we have paused the work on this Sprint Goal due to the critical unplanned work in #3450 that consumed significant amount of @indytechcook 's and @ndouglas 's time.

moving into Sprint 20

**Comment by indytechcook** [comment]
Architecture Document: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/content-ops/editorial-workflow/notifications/architecture.md
