### ISSUE TITLE
[Aging Content] Updates to the two notification emails for Full-width banner alerts

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-cms#19052]
## Status
**[2024-09-04] [Fran]** Email verbiage and AC updated. Ready for implementation.
[2024-08-29] Jill to review content. We need to add a Needs help? with help desk email address. Fran to then move to Ready and remove Needs refining.

## Description

The Aging Content notification email content needs to be updated. 

Also, feedback received from Randi H. indicates the email sent on the expiration date should be sent in the morning, not at the end of that day. To this end, we'll be adjusting so that it's sent at six (6) am EST on the expiration date.
gi**Note from Daniel on this: the emails are setup to be sent at midnight. Nothing should be coming in the evening.

See Artifacts below for the new text.

### User story

**AS A** publisher of Full-width banner alerts 
**I WANT** the notification emails I receive telling me to update or archive to be concise and easily understood
**SO THAT** I'm not confused as to when the banner expiration date is and what actions I should take.

### Quality / testing notes
Test email sent to Randi Hecht or Jill Adams is used to verify the change

### Additional Information
The KB article linked in both emails will be updated to contain information regarding the notification emails.

## Artifacts

<details>
<summary>Text for the email sent three (3) days before expiration date</summary>

**Subject:** 
Full-width Banner Alert content expiring soon

**Body:** 
As a reminder, Full-width Banners Alerts should be used for emergency or urgent communications that prompt a Veteran or other user to take action. Unless there is a compelling reason, Full-width Banner Alerts should not promote the same content for longer than seven (7) days. 

Your published Full-width Banner Alert titled '[Title of Full-width Banner Alert]' will soon expire. Please plan to refresh this content by [expiration date]. 

To extend the display of the content, log in to Drupal and edit the banner, resaving it with a comment to that effect. The 7-day countdown window will reset.

For more information, you can read this [Knowledge Base article](https://prod.cms.va.gov/help/homepage-alerts-and-promo-banners/how-to-do-i-create-a-full-width-alert-banner) for tips and best practices to manage compliance.

**Need help?**
Contact VA.gov Drupal CMS support at support@va-gov.atlassian.net
</details>

<details>
<summary>Expiration Email Text
</summary>

**Subject:**
Full-width Banner Alert content is now expired

**Body:** 
Your published Full-width Banner Alert titled '[Title of Full-width Banner Alerts]' has displayed for seven (7) days. Please plan to replace the content of this published Full-width Banner Alert by EOD today.

If there is a compelling reason to continue this particular display, you can reset the 7-day countdown window by logging into Drupal, editing the banner, and resaving it with a comment to that effect. 

For more information, you can read this [Knowledge Base article](https://prod.cms.va.gov/help/homepage-alerts-and-promo-banners/how-to-do-i-create-a-full-width-alert-banner) for tips and best practices to manage compliance.

**Need help?**
Contact VA.gov Drupal CMS support at support@va-gov.atlassian.net
</details>

## Acceptance criteria
- [ ] Text for the warning email (sent three days prior to expiration date) has been updated
- [ ] Text for the expiration email (sent the morning of the expiration date) has been updated
- [ ] Test email sent to Randi Hecht or Jill Adams is used to verify the change

**Comment by FranECross** [comment]
@jilladams to review content. Consider adding a Needs help? along with the help desk email address.

**Comment by jilladams** [comment]
Jill and RandiH are currently receiving the expiration day banner email versions for live banners. The warning email won't be possible to test until a new banner goes up OR until we create the test mechanism. 

OR: Jill can edit the live banner and save a revision log note in order to test, and the email will get sent 4 days after the edit.

**Comment by jilladams** [comment]
From Michelle, CMS team has also requested that we onboard Jake Bapple to learn how this framework works, so their team can also leverage.

**Comment by dsasser** [comment]
> From Michelle, CMS team has also requested that we onboard Jake Bapple to learn how this framework works, so their team can also leverage.

Great! @JakeBapple if you want you can start by looking at the technical architecture document, or we can sync up and go over it together. Either way let me know how you want to proceed.

**Comment by dsasser** [comment]
## End-of-Sprint Status Update 9/16/24

[Pull request](https://github.com/department-of-veterans-affairs/va.gov-cms/pull) is in, but lacks QA steps. I'll get to those today, and approval and merge by COB tomorrow is the plan.

**Comment by jilladams** [comment]
Requested Randi share a test email: https://dsva.slack.com/archives/C01K37HRUAH/p1726609520945439

We'd discussed above in comments that I could modify a published FWB to get the notifications BUT: the only other published FWB right now is one Josh Tuscher published and I'd like him to receive the encouragement to archive it timely, so am not going to modify that banner.  (published FWBs: https://prod.cms.va.gov/admin/content?title=&type=banner&moderation_state=published&owner=All)

**Comment by jilladams** [comment]
Since we haven't heard from either recipient in the timeframe, I'm going to close this, and we can reopen or cut a new ticket if we get any feedback for required changes.

**Comment by jilladams** [comment]
Verified text for the email sent three (3) days before expiration date, and the link points to https://prod.cms.va.gov/help/homepage-alerts-and-promo-banners/how-to-do-i-create-a-full-width-alert-banner.

![Image](https://github.com/user-attachments/assets/b426c9e3-e7db-4527-a706-a9922054d8f9)
