### ISSUE TITLE
Help Desk Process for Handling Archived Unattached PDFs

### ISSUE THREAD

**Issue by gracekretschmer-metrostar** [department-of-veterans-affairs/va.gov-cms#19074]
## User Story or Problem Statement
As a member of the CMS Help Desk team, I need to understand how to answer requests from editors who need to retrieve an unattached PDF from Drupal CMS. 

## Steps for Implementation
- Create a template response for Help Desk to use in Jira
- Coordinate with Help Desk so that they understand how to respond if they get a question about the unattached PDF process.

## Acceptance Criteria
- [x] Both editors and Help Desk understand how to handle situations where editors need to retrieve a unattached PDF that has been removed from Drupal CMS.

**Comment by gracekretschmer-metrostar** [comment]
https://dsva.slack.com/archives/CT4GZBM8F/p1725406732690199

**Comment by gracekretschmer-metrostar** [comment]
Help desk documentation: https://vfs.atlassian.net/wiki/spaces/PCMS/pages/2947449129/Media+Files+and+PDF+DOCX+Files#PDF-Media-Library

**Comment by srancour** [comment]
[KB article](https://prod.cms.va.gov/help/how-to-use-the-pdf-media-library).

@ian-sears had some ideas for future improvements to this work so will be adding a section in the [KB Confluence Feedback article](https://vfs.atlassian.net/wiki/spaces/PCMS/pages/3411378232/PDF+Audit+Tool+KB+Article+Changes+Feedback).

Had a meeting with @ian-sears and @TroyCMSSupport who both approved that this is done and can be closed.
