### ISSUE TITLE
Facility Locator: Update <div> to semantic tag for accessibility

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#19095]
## Description
For accessibility, all text must be properly marked up so that it can properly resize and scale according to the user's font settings. There are elements within the Facility Locator that are not currently correct and need to be updated:

- “Please enter a location…” text is wrapped in a `<div>` instead of a `<p>` tag
- “Can’t find what you’re looking for text” is wrapping in a `<div>` instead of a `<p>` tag

**Note:** There are other elements that are not covered here because they are included in other tickets

## Acceptance Criteria
- [x] Text identified above is all wrapped in semantic tags
- [x] All text resizes amd scales according to browser font settings
- [x] Requires accessibility review

## Accessibility review steps
**Confirm the text resizes appropriately with the browser font settings**
1. Go to the Facility Locator page `/find-locations`
2. Within your default browser, update your settings to the largest font size available (you do not need to test all of these):
      - Chrome: Settings > Appearance > Font size
      - Firefox: Settings > Language & Appearance > Fonts
      - Edge: Settings > Appearance > Fonts
4. Confirm that the text detailed above increases in size correctly

### Screen shots
The below screen shots help to show what you are looking for
 
**Incorrect**
![Screenshot 2024-09-16 at 10 28 33 AM](https://github.com/user-attachments/assets/517f10f5-93c2-474b-9b65-7c4a7bd3da38)

**Correct**
![Screenshot 2024-09-16 at 10 30 03 AM](https://github.com/user-attachments/assets/71f3428c-1fb8-4539-a9b2-a095402ce55c)

**Comment by randimays** [comment]
Validated successfully in production; closing as complete.
