### ISSUE TITLE
New Vet Center Facility: US Virgin Islands Vet Center - Awaiting CSV

### ISSUE THREAD

**Issue by TroyCMSSupport** [department-of-veterans-affairs/va.gov-cms#19102]
## Description
Use this runbook if: a Vet Center, Mobile Vet Center, or Vet Center Outstation is flagged as New, OR if an existing facility is flagged as New with a new Facility API ID.  
- This may also occur when an Outstation is promoted to main Vet Center or if an existing Mobile Vet Center is reallocated to a different Vet Center 

## Intake
- [x] What triggered this runbook? (Flag in CMS, Help desk ticket, Product team, VHA Digital Media)
Trigger: Flag in CMS

- [x] Link to associated help desk ticket (if applicable)
Help desk ticket: [VAHELP-7989](https://va-gov.atlassian.net/browse/VAHELP-7989)

- [x] Name of submitter (if applicable)
Submitter: Alerted to us by Michelle Middaugh as a BOLO

- [x] If the submitter is an editor, send them links to any relevant KB articles for the Vet Center product.
KB articles: Beginning with Barbara.Kuhn@va.gov to identify the correct Editor to work with

- [x] Link to facility in production:
Facility CMS link: [Facility Link](https://prod.cms.va.gov/us-virgin-island-vet-center)
Facility API ID: **vc_0308V**

### New Vet Center
[@TODO: KB ARTICLE FOR ADDING VET CENTERS - SEE runbook-vamc-facility-new]

#### CMS help desk steps
**Note: If the help desk is waiting on information from the facility staff or editor, add the `Awaiting editor` flag to the facility** with a log message that includes a link to this ticket. Remove the flag when the ticket is ready to be worked by the Facilities team. **Be sure to preserve the current moderation state of the node when adding or removing the flag.**

**If a Vet Center:**
- [x] Become aware that the new facility is now on the Facility API (typically, via a Flag).
- [x] Check with Readjustment Counseling Services to (1) confirm what district the Vet Center belongs, (2) identify the Vet Center Director and Outreach Specialist (names/email addresses), (3) confirm the new location isn't a replacement for an existing Outstation
- [x] In [Sections taxonomy](https://prod.cms.va.gov/admin/structure/taxonomy/manage/administration/overview), move the Vet Center Section to the appropriate district.
- [x] Create account access as directed by RCS. If editors are new to Drupal, create accounts with editor rights only for Vet Center Director and Outreach Specialist so that they cannot publish on their own.
- [x] Contact Vet Center Director and Outreach specialist to onboard for training [@TODO write sample email - SEE runbook-vamc-facility-new] **Note: this should include instructions for adding content and preparing for publishing and RCS Central Office should be included as CC**
- [x] Add flag `Awaiting editor` to this facility. Note: This is now blocked until RCS Central office approves.
- [x] **Once approved by RCS Central Office as complete, proceed to Drupal Admin publishing steps**

**Drupal Admin steps**
- [x] Bulk publish the nodes and facility.
- [x] Contact Lighthouse via Slack at #cms-lighthouse channel that this facility requires a canonical link in the following format (replacing the placeholder data with the actual API Id and VA.gov URL):
  - `vha_691GM,https://www.va.gov/greater-los-angeles-health-care/locations/oxnard-va-clinic/`
- [x] Add the "Awaiting CSV" flag to the facility node with a revision log message that includes a link to this ticket.
- [x] Let Help desk know this has been done, if not done by Help desk.

#### Wait (days or weeks, potentially)
- [x] After the canonical link has been added to the websites.csv and you have confirmation from Lighthouse that the CSV has been deployed, validate that the change has deployed by checking that the Facility Locator has been updated with the new url.
- [x] Update this ticket with a comment that the CSV change has been deployed.
- [x] Edit facility node and remove `New facility` and "Awaiting CSV" flags with a revision log message that includes a link to this ticket.
- [x] Let Help desk know this has been done, if not done by Help desk.

#### CMS Help desk (wrap up)
- [x] 11. Upgrade the Vet Center Director and Outreach Specialist accounts to the publisher role for that Vet Center.
- [x] 12. Notify editor and any other stakeholders.

[VAHELP-7989]: https://va-gov.atlassian.net/browse/VAHELP-7989?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by TroyCMSSupport** [comment]
Additional Vet Center information is forthcoming - Jira and GH tickets will be updated accordingly

**Comment by TroyCMSSupport** [comment]
@ian-sears @omahane @jilladams  - 

Barb Kuhn will work with the Editor (Muria ) to build the page after 9/23  per Jira https://va-gov.atlassian.net/jira/servicedesk/projects/VAHELP/queues/custom/12/VAHELP-8025 

which has been added to https://va-gov.atlassian.net/jira/servicedesk/projects/VAHELP/queues/custom/12/VAHELP-7994

**Comment by ian-sears** [comment]
Requested #cms-lighthouse to please add to the websites.csv:
`vc_0308V,https://www.va.gov/us-virgin-islands-vet-center/`
https://dsva.slack.com/archives/C02BTJTDFTN/p1728689982365729
Tagged Adam Stilton with this request.
The node has been published and resolves.
Flags have been updated to Awaiting CSV in the Node.
Editor has been notified.

**Comment by TroyCMSSupport** [comment]
@jilladams @omahane @ian-sears - U.S. Virgin Islands Vet Center site is now complete.
Closing this issue -
