### ISSUE TITLE
New VAMC Facility: Iola VA Clinic (BOLO)

### ISSUE THREAD

**Issue by ian-sears** [department-of-veterans-affairs/va.gov-cms#19100]
## Intake
- [x] What triggered this runbook? (Flag in CMS, Help desk ticket, Product team, VHA Digital Media)
Trigger: Help desk ticket

- [x] Link to associated help desk ticket (if applicable)
Help desk ticket: [VAHELP-7916](https://va-gov.atlassian.net/browse/VAHELP-7916)
- [x] Name of submitter (if applicable)
Submitter: dane.ohara@va.gov

- [x] If the submitter is an editor, send them links to any relevate KB articles for the VAMC Facility product.
KB articles: <insert_kb_article_links>

- [ ] Link to facility in production:
Facility CMS link: See below
Facility API ID: See below

### New VAMC Facility
Please refer to the Knowledge Base article titled "How do I add a facility to my health care system?" for more information: https://prod.cms.va.gov/help/vamc/about-locations-content-for-vamcs/how-do-i-add-a-facility-to-my-health-care-system

#### CMS help desk steps
**Note: If the help desk is waiting on information from the facility staff or editor, add the "Awaiting editor" flag to the facility with a log message that includes a link to this ticket. Remove the flag when the ticket is ready to be worked by the Facilities team. Be sure to preserve the current moderation state of the node when adding or removing the flag.**
- [x] Become aware that the new facility is now on the Facility API (typically, via a Flag, but this may come in as a helpdesk ticket).
- [ ] **If the facility is a VA Mobile clinic, the "New facility" flag can be removed and the page archived with no further work needed. (Note, there are required fields that will need to be filled in before doing so.)**
- [ ] If the editor has followed the steps from the above Knowledge Base article and included which section and VAMC the facility belongs to (i.e. VA Pittsburgh), great!
  - If not, please check with the editor or VHA digital media regarding what section and VAMC it belongs to.
    - [ ] Update the Section (default is "VAMC facilities", but it should be a VAMC system in a VISN) and VAMC system field accordingly.
- [ ] Communicate with editor (cc VHA Digital Media) to give them go-ahead to complete the content, with this [KB article](https://prod.cms.va.gov/help/vamc/about-locations-content-for-vamcs/how-do-i-add-a-facility-to-my-health-care-system). (See sample notification email below)

- [ ] When editor has prepared content and let help desk know, proceed to the remaining steps.

#### Drupal Admin steps (CMS Engineer or Help desk) _Help desk will complete these steps or escalate to request help from CMS engineering._
- [ ] Update the facility **Meta description** field, using the following format: "Get address and hours, parking and transportation information, and health services offered at [facility name]."
- [ ] Move the facility link in the health care system menu to its place in the alphabetized list (medical centers first, then clinics).
- [ ] Drupal Admin bulk publishes nodes and facility.
- [ ] Contact Lighthouse via Slack at #cms-lighthouse channel that this facility requires a canonical link in the following format (replacing the placeholder data with the actual API Id and VA.gov URL):
  - `vha_691GM,https://www.va.gov/greater-los-angeles-health-care/locations/oxnard-va-clinic/`
- [ ] Add the "Awaiting CSV" flag to the facility node with a revision log message that includes a link to this ticket.
- [ ] Let Help desk know this has been done, if not done by Help desk.

#### Wait (days or weeks, potentially)
- [ ] After the canonical link has been added to the websites.csv and you have confirmation from Lighthouse that the CSV has been deployed, validate that the change has deployed by checking that the Facility Locator has been updated with the new url.
- [ ] Update this ticket with a comment that the CSV change has been deployed.
- [ ] Edit facility node and remove `New facility` and "Awaiting CSV" flags with a revision log message that includes a link to this ticket.

#### CMS Help desk (wrap up)
- [ ] Notify editor and any other stakeholders.

[VAHELP-7916]: https://va-gov.atlassian.net/browse/VAHELP-7916?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by ian-sears** [comment]
@omahane @jilladams @mmiddaugh @department-of-veterans-affairs/platform-cms-helpdesk 


The VAST request to set up this new Iola VA Clinic facility was not made correctly, and not in time.

The VAST requests to CLOSE three facilities were made and these facilities are now CLOSED and two of them already removed from VAST (CMS Help Desk is keeping these nodes Published until the New Facility web page is set up so we can initiate redirects). In each case (each facility web page) Veterans have been told to seek information and health services at this new Iola VA Clinic facility - however no CMS Iola facility web page was ever made in VAST. No Iola VA Clinic CMS page exists (yet).

This Iola VA Clinic NEW facility request should be fast-tracked in VAST to get this whole process back on track.

The following three (3) Eastern Kansas VAMC Facilities have been closed and no longer see Veterans:
[Chanute VA Clinic](https://prod.cms.va.gov/eastern-kansas-health-care/locations/chanute-va-clinic) - [vha_589GM](https://www.va.gov/find-locations/facility/vha_589GM) - [GitHub Closure ticket #19096](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19096)
[Garnett VA Clinic](https://prod.cms.va.gov/eastern-kansas-health-care/locations/garnett-va-clinic) - [vha_589GP](https://www.va.gov/find-locations/facility/vha_589GP) -  [GitHub Closure ticket #19035](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19035)
[Fort Scott VA Clinic](https://prod.cms.va.gov/eastern-kansas-health-care/locations/fort-scott-va-clinic) - [vha_589GV](https://www.va.gov/find-locations/facility/vha_589GV) - No Github closure ticket was generated (yet)

At this point the issue is that a VAST request was erroneously made to alter vha_589GV to become a new facility in different town.
![VAST-vha_589GV](https://github.com/user-attachments/assets/a4a2e47b-c612-444c-8685-6a481cf4f838)

What should have happened is a NEW FACILITY request should have been made in (via) VAST so all of these could be redirected to it, and shut down.

The Editor (dane.ohare@va.gov) that inherited this mess, is unfamiliar (yet) with this VAST process and immediately reached out to the CMS Help Desk and our teams to assist. 

The CMS Help Desk is keeping the three existing Published facility pages LIVE (although they were removed from Source) until this new Iola VA Clinic facility page is up and running (for redirects).

Consistent text on each of these closed facility pages currently reads:
The [yourNameHere] Clinic has been permanently closed. All services have been moved to the new Iola Clinic at 1408 East St. Iola KS 66749 Phone: [(785) 350-3111](tel:7853503111) ext. 54751

We need VAST contacted to fast setup of this new Iola VA Clinic with its own Facility ID.

**Comment by TroyCMSSupport** [comment]
FYSA - @jilladams @omahane @ian-sears  -- Flagged Facilities Report update: 
FF Report shows Iola VA Clinic as a NAME CHANGE from Fort Scott to Iola -- 
![image](https://github.com/user-attachments/assets/a9190270-d215-4756-a979-5a3036e2183f)

**Comment by jilladams** [comment]
Ok - noting, we are in a New VAMC Facility runbook right now, rather than a Name Change runbook. it might be simpler to close this ticket and create a enw one for the name change, to complete the rest of the tasks, if they confirm that there won't be a separate new facility coming through.

**Comment by TroyCMSSupport** [comment]
Thank you @jilladams - I have just created a Name Change Runbook https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19404 so will close this issue -
