### ISSUE TITLE
Break up Search APM to focus on v0/search endpoint

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#19114]
## Context
We call 3 different endpoints for Search -- v0/search is for real search traffic. The other 2 are less relevant -- for typeahead, and for click tracking.
1. V0::SearchController#index -- The main actual search call that returns search results
2. V0::SearchTypeaheadController#index -- Typeahead call that returns suggested search terms. This fails a lot, but when it does, searches can still be submitted. Not a dealbreaker, as a UX.
3. V0::SearchClickTrackingController#create -- Purely a metrics call. If it fails, we don't care. Search.gov has instability on this endpoint. 

## The problem
[Search APM](https://vagov.ddog-gov.com/apm/services/search/operations/rack.request/resources?dependencyMap=qson%3A%28data%3A%28telemetrySelection%3Aall_sources%29%2Cversion%3A%210%29&deployments=qson%3A%28data%3A%28hits%3A%28selected%3Aversion_count%29%2Cerrors%3A%28selected%3Aversion_count%29%2Clatency%3A%2195%2CtopN%3A%215%29%2Cversion%3A%210%29&env=eks-prod&fromUser=false&groupMapByOperation=null&infrastructure=qson%3A%28data%3A%28viewType%3Apods%29%2Cversion%3A%210%29&panels=qson%3A%28data%3A%28%29%2Cversion%3A%210%29&resources=qson%3A%28data%3A%28visible%3A%21t%2Chits%3A%28selected%3Atotal%29%2Cerrors%3A%28selected%3Atotal%29%2Clatency%3A%28selected%3Ap95%29%2CtopN%3A%215%29%2Cversion%3A%211%29&summary=qson%3A%28data%3A%28visible%3A%21t%2Cerrors%3A%28selected%3Acount%29%2Chits%3A%28selected%3Acount%29%2Clatency%3A%28selected%3Alatency%2Cslot%3A%28agg%3A95%29%2Cdistribution%3A%28isLogScale%3A%21f%29%2CshowTraceOutliers%3A%21t%29%2Csublayer%3A%28slot%3A%28layers%3Aservice%29%2Cselected%3Apercentage%29%2ClagMetrics%3A%28selectedMetric%3A%21s%2CselectedGroupBy%3A%21s%29%29%2Cversion%3A%211%29&traces=qson%3A%28data%3A%28%29%2Cversion%3A%210%29&view=spans&start=1725472435708&end=1725476035708&paused=false) is where we look to understand whether Search is in good health or poor health. Right now, Click tracking and Typeahead create a lot of noise, and make it difficult to discern when **actual** search is in poor health, and Veteran experience is affected. 

## What we want to do
Break Search APM down to only display v0/Search metrics. 
Move Typeahead and Click tracking resource information to.... somewhere else. Figure out where the right place is. 

## ACs

- [ ] Search APM displays only information that informs the actual health of the Search service / veteran experience

**Comment by FranECross** [comment]
Closing as a no op.

**Comment by jilladams** [comment]
We decided not to pursue this because APM is "Application Performance Monitoring," and in this case: the Search application does properly include 3 endpoints / Resources. We can get to the [Resource page for `v0/search`](https://vagov.ddog-gov.com/apm/resource/search/rack.request/72b7d62abdbc2323?query=env%3Aeks-prod%20operation_name%3Arack.request%20service%3Asearch&env=eks-prod&fromUser=false&summary=qson%3A%28data%3A%28visible%3A%21t%2Cchanges%3A%28%29%2Cerrors%3A%28selected%3Acount%29%2Chits%3A%28selected%3Acount%29%2Clatency%3A%28selected%3Alatency%2Cslot%3A%28agg%3A95%29%2Cdistribution%3A%28isLogScale%3A%21f%29%2CshowTraceOutliers%3A%21t%29%2Csublayer%3A%28slot%3A%28layers%3Aservice%29%2Cselected%3Apercentage%29%2ClagMetrics%3A%28selectedMetric%3A%21s%2CselectedGroupBy%3A%21s%29%29%2Cversion%3A%211%29&traces=qson%3A%28data%3A%28%29%2Cversion%3A%210%29&start=1727725485353&end=1727729085353&paused=false) easily enough. 

On the flip side, if we tried to break up the current Search APM into different views, one for `v0/search` and one for Typeahead and Click tracking, we would also need to make coded changes. This is because APM is tied directly to Services / models that are declared in vets-api. We thought we could achieve this just through monitoring changes, but since we can't: it's not that important to do. Hence closing.
