### ISSUE TITLE
Prep Meeting for Survey Analysis Readout

### ISSUE THREAD

**Issue by gracekretschmer-metrostar** [department-of-veterans-affairs/va.gov-cms#19112]
## User Story or Problem Statement
As the product designer for CMS, I need to understand what is needed for a meeting read out and use those findings to prepare for a meeting read out of the Q3 survey results. 

## Description or Additional Context 
The editor survey data has been synthesized and now the findings need to be put into a report that will eventually be read out in a meeting to VA stakeholders of CMS. 

## Meeting Requirements
- CMS Demo: Marisa will create a slide deck and present at CMS demo the readout on the report on 10/23
- VHA DM/OCTO Sync: Marisa will present to VHA stakeholders using slide deck on 10/29 meeting. Plan to present for 15 minutes, with 5 minutes for questions and discussion.
- Digital Modernization Council: Amanda Klausmeier and Erika Washburn will present to the meeting in January and will use the slide deck created by Marisa. 

## Steps for Implementation
- Use framework that was created by the platform team for platform survey. 
- Compile a list of everyone that should be invited to the meeting. 
- Create a meeting invite that includes a link to the report.
- Create the slide deck needed to aid the meeting. 

## Acceptance Criteria
- [x] CMS team is prepared to give a read out of the survey results in meetings to VA stakeholders.

**Comment by gracekretschmer-metrostar** [comment]
slide deck template https://docs.google.com/presentation/d/19l8281cENnUmdz0qIsyPcVIeoyB8uw_kzoHYWbuYlwA/edit?usp=sharing

**Comment by gracekretschmer-metrostar** [comment]
Results from 10/3/2024 conversation:
- Use a VHA Digital Media sync to share results. Potentially at the end of October or early November. Then let Justin and Blake decide how they want to share that slide deck. 
- Amanda K and Erika Washburn give a presentation of a Digital Modernization Council. Maybe the one in January?  
- Then all other groups could get an emailed version of the slide deck. 
- Use CMS demo to do a read out to the CMS team.

**Comment by aklausmeier** [comment]
Erika, Michelle and I would like to review the draft of the Survey presentation prior to the stakeholder readout.

**Comment by MDomngz** [comment]
[Working draft](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/research/2024-3rd-Quarter-Editor-Survey-Analysis.md) - converting report into markdown for Github distribution
- need to convert all tables into GH markdown, insert, save, distribute

@gracekretschmer-metrostar, the conversion from Confluence was not as simple as it should have been. I am working to resolve the kinks - will have an update by Friday afternoon EST.

**Comment by gracekretschmer-metrostar** [comment]
Slide deck here: https://docs.google.com/presentation/d/1G5HGCjAV2nVmaOrHVFjIe9a2pO5EgWsZ9d74508DSbI/edit?usp=sharing
