### ISSUE TITLE
[VAMC Health Services] Accordion subtext should have the first letter capitalized

### ISSUE THREAD

**Issue by randimays** [department-of-veterans-affairs/va.gov-cms#19142]
## Description
On VAMC health services pages, the descriptive text under the bold accordion headers should have a capital letter to start with. Most on the example page already have this formatting but we need to enforce it so it will carry to all of them.

**Example**: https://www.va.gov/pittsburgh-health-care/health-services/ -> Social programs and services -> Intimate partner violence support

**Code**: https://github.com/department-of-veterans-affairs/content-build/blob/9abb220fe8ce592fbfb669e796c4a3f9fd504110/src/site/facilities/health_service.drupal.liquid#L4

<img width="500" alt="Screenshot 2024-09-06 at 3 43 19 PM" src="https://github.com/user-attachments/assets/96a8161a-7d69-46d1-982e-48fceccf499b">

### User story
> _Describe the audience/user, enhancement or fix, and value / outcome desired._

**AS A**
**I WANT**
**SO THAT**

## Acceptance criteria
- [ ] All accordion subtext on health services pages have a capital letter to start with
- [ ] No regressions introduced to text that already started with a capital letter

**Comment by davidmpickett** [comment]
Updated all instances of patient-friendly names beginning with lower-case letter
- https://prod.cms.va.gov/health-care/outpatient-surgery
- https://prod.cms.va.gov/health-care/intimate-partner-violence-support

**Comment by davidmpickett** [comment]
After next Content Build, here is where the fix can be verified in Prod
- https://www.va.gov/clarksville-vet-center/#counseling-item-intimate-partner-violence-support
- https://www.va.gov/montana-health-care/locations/benjamin-charles-steele-va-clinic/#outpatient-surgery
- https://www.va.gov/milwaukee-health-care/locations/clement-j-zablocki-veterans-administration-medical-center/#intimate-partner-violence-support
- 
-

**Comment by randimays** [comment]
Thanks Dave! This is a true KISS moment. 🎸

**Comment by davidmpickett** [comment]
Verified on prod
