### ISSUE TITLE
VA Debt Management CMS Page

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-cms#1916]
## *About this form*

*If you don't have the answer yet to some of the questions, that's fine!*

*A CMS team member will be in touch to schedule a meeting to review, within a few days of receiving it, although the timing of that depends on our sprint capacity in the current and upcoming sprints. We allocate a set number of story points to each sprint to support VFS product teams.*

*Questions? Go to #cms-support in Slack.*

----

## Your product team

**What's your product called?**
'Debt Letters MVP' 

**Provide a link to your [product outline](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/debt-letters-mvp)**

**Who’s who on your product team? Provide a link to your team’s page on the CMS, or a general sense of the product owner and those responsible for the product.**
Matt Self (DSVA Lead), Leah Keeler (Product Manager), Riley Orr (Designer), Rebecca Walsh (Designer)

**Who are the primary stakeholders for the product?**
Debt Management Center (DMC)

**Which Slack channel on DSVA slack do you use to coordinate?**
#vsa-bam-2

## Content audit / inventory

**Describe the purpose of the content you want to manage from the CMS.**
Our team is working on a tool that allows Veterans to view debts they owe the VA, find next steps for resolving those debts, and who to reach out to for assistance navigating their debts. As part of this work, we want to replace the existing [VA Debtman pages](https://www.va.gov/debtman/) with a content page that empathetically helps Veterans learn about their debts and next steps. It may be helpful to reference [our early-stage wireflows](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/debt-letters-mvp/design/wireframes.md) to understand how we'd like the CMS page to interact with the tool we're building. 

**Does it already exist on another platform? If yes, provide links to the source platform (e.g. markdown file) and/or to the front end.**
[VA Debtman pages](https://www.va.gov/debtman/)

**How many pages or pieces of content do you expect to manage from the CMS for your product?**
1

**Will any of the content need to be served as a part of authenticated experience?**
Yes

## Content ops & governance

**Who is responsible for writing and reviewing the content now?**
DMC

**Are there external reviewers of the content?**
TBD

**Who will own this content in the future?**
TBD

**What is your existing editorial workflow, if any?**

**Will some of the content continue to have a “source of truth” outside the CMS? If yes, what aspect of it (for example: a dataset living in another database)?**

## Training and access to CMS

**Who will need access to CMS to edit?** 

**Will they need training?**

## Product roadmap

**What’s your timeline for going live OR for releasing the next iteration?**

**How do you expect the product to evolve, if at all, in the next:** 

- **Weeks (you should know this)** 
- **Months (you may know this)**
- **Years (you probably don’t know this, but if you had to guess…)**

## Next steps

**Propose some general time windows for the initial CMS discovery meeting.**
June 4th: 3:00pm - 4:00pm EST
June 8th: 12:00pm - 1:00pm EST; 2:30pm - 4:00 pm EST
June 9th: 12:30pm - 2:30pm EST; 3:00pm - 4:00 pm EST

**Comment by kevwalsh** [comment]
Hi @rileyorr @rebeccawalsh @leahkeeler 

Thank you for your this! 

I've set up a meeting for 2:30pm ET Monday June 8. 

Just to clarify a couple things:
* is this _one_ page? 
* are there any existing designs for that page, or content, other than the legacy page? (No worries if not, but i didn't see it in your existing documentation)
* are you all aware of the [Public Websites Intake Form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=lunascoop&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+needs-grooming%2C+Epic&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E)? It's a new process to me, but it strikes me as relevant to this product. 

/cc @oksana-c @stephorkandatx

**Comment by rebeccawalsh** [comment]
@kevwalsh 

Sounds like we were looking for something like the Public Websites intake form. These request avenues can be a little hard to keep track of, with so many new processes popping up. 😅

Can you explain the difference between your team's work/intake form and Public Websites'? Just so we know when we should use this sort of request in the future. The value prop of your issue template seemed to apply to us!

Questions:
- Maybe, maybe not? (A lot of this content will be incorporated into the tool itself and it has a good deal of duplication and word-ly-ness.)
- We're at the beginning of the design process and are looking for expertise for porting over debtman, so we don't have anything more for designs, yet.
- I have submitted one once, but that knowledge was apparently lost to the nethers! I think this is what we were intending to do.
