### ISSUE TITLE
BUG: FL VA Health / All VA health services search for Custer causes JavaScript Crash

### ISSUE THREAD

**Issue by Agile6MSkinner** [department-of-veterans-affairs/va.gov-cms#19172]
### Description
When searching for VA services using the word "Custer" as the place name and not selecting a specific services type, the facility locator disapears on search.

* Editors have reported that this occurs for any city in South Dakota. 
* we are able to get results for Eagle Butte ([here](https://www.va.gov/find-locations/?page=1&address=Eagle%20Butte&facilityType=health&serviceType&latitude=44.99698&longitude=-101.23483&radius=70&bounds%5B%5D=-101.98483&bounds%5B%5D=44.24698&bounds%5B%5D=-100.48483&bounds%5B%5D=45.74698&context=Eagle%20Butte%2C%20South%20Dakota%2C%20United%20States))
* Happens most reliably if search for a city near Custer

#### Search:

<img width="1270" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK2kvQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--161934a23ac1fd8342212a7d3a23171128a0ba8a/image.png" alt="image.png" />

#### Result:

<img width="1293" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK20vQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1cab4f71a81aa484359cd3461d85ea61006f6d9b/image.png" alt="image.png" />

### To Reproduce
1) Navigate to Facility Locator
2) Under "Custer" in "City, State, or postal code" field
3) Select VA health from the "Facility Type" dropdown
4) Leave Service Type as "All VA Health Services"
5) Submit, land on https://www.va.gov/find-locations/?page=1&address=custer&facilityType=health&serviceType&latitude=43.766216&longitude=-103.600266&radius=48&bounds%5B%5D=-104.350266&bounds%5B%5D=43.016216&bounds%5B%5D=-102.850266&bounds%5B%5D=44.516216&context=Custer%2C%20South%20Dakota%2C%20United%20States, see no search results / no map

## Eng notes
Console shows JS errors: `Uncaught TypeError: Cannot read properties of undefined (reading 'address1')`
![Screenshot 2024-09-10 at 9 11 49 AM](https://github.com/user-attachments/assets/85b68052-1d91-4a75-97da-693f22363a80)
![Screenshot 2024-09-10 at 9 12 00 AM](https://github.com/user-attachments/assets/26517260-4368-4604-95f2-efaf7d6d8370)

## Maybe related, maybe not
Unrelated but maybe related: https://dsva.slack.com/archives/C02BTJTDFTN/p1726069219905689

Lighthouse doesn't require an address for facilities, only name, type, lat, long.
There's a class of facilities (Compensated Work Therapy/Transitional Residences) coming through with no addresses. Example IDs:

- vha_568PD
- vha_568PB
- vha_568PC
- vha_676PA

these make an error on the Facility Locator detail page: https://www.va.gov/find-locations/facility/vha_568PB. This looks like a similar error for what we're getting on the Custer location, but in the Custer case, the Facility Locator detail page still works. But the same line of JS (109) is referenced in the error re: address:

![Screenshot 2024-09-11 at 8 59 57 AM](https://github.com/user-attachments/assets/8d9d9a01-d13e-4e3d-8987-91463f2b1899)

```[tasklist]
### ACs
- [x] Root cause analysis
- [x] Determine what other entries besides "custer" would cause the bug
- [x] Determine if the FL locator detail page / missing address needs its own ticket to resolve
- [x] Propose solution
```

**Comment by jilladams** [comment]
Added FE / Ruby labels, til we know exactly where the issue is, and screenshots of the console errors. (Also moved this issue into va.gov-cms repo.)

**Comment by jilladams** [comment]
Unrelated but maybe related: https://dsva.slack.com/archives/C02BTJTDFTN/p1726069219905689
* Lighthouse doesn't require an address for facilities, only name, type, lat, long.
* There's a class of facilities (Compensated Work Therapy/Transitional Residences) coming through with no addresses. Example IDs: 
    * vha_568PD
    * vha_568PB
    * vha_568PC
* these make an error on the Facility Locator detail page: https://www.va.gov/find-locations/facility/vha_568PB.  This looks like a similar error for what we're getting on the Custer location, but in the Custer case, the Facility Locator detail page still works. But the same line of JS (109) is referenced in the error re: address: 

![Screenshot 2024-09-11 at 8 59 57 AM](https://github.com/user-attachments/assets/8d9d9a01-d13e-4e3d-8987-91463f2b1899)

We need to be resilient to missing address on the FL Detail Pages. When we refine this ticket, let's discuss whether it's reasonable to add that issue to scope here, or whether it should be separate.

**Comment by eselkin** [comment]
The problem is empty addresses would be fine, but we no longer return null address we return `[]` which is not seen as empty and attempts to destructure it to address components. Fix is checking for empty array for the address. Made fix and tested.

**Comment by jilladams** [comment]
Big thread about it: https://dsva.slack.com/archives/C0FQSS30V/p1726165257024989

Other notes from scrum: https://dsva.slack.com/archives/C079GFKN50D/p1726177598540579?thread_ts=1726177359.140949&cid=C079GFKN50D

Takeaways: 
> Proposed fix just checks: do we have the data we expect to have, in order to show address data?  Historically, we have never showed any facility without address data. The API would return those facilities, but the address field had NULL as a value, instead of an empty array. Then: we in the FE check against API results for facilities with no address.

> Lat/long is required, and we could maybe show them on the map, but: that's not helpful for veterans trying to find the facility.

> This showed up due to a vets-api change during Lighthouse V2 implementation via IIR, where the shape of data changed (from NULL to empty array). In response to a detail page error.

#19207 stubbed to address VAMC pages where this is happening.
API fyi sent to 1010 about the data shape: https://dsva.slack.com/archives/CMJ2V70UV/p1726247220313999

**Comment by eselkin** [comment]
Prod seems to work now with Custer, SD and VA Health, and all VA Health services.
