### ISSUE TITLE
Monolog processor to put UID in log messages

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#19175]
## User Story or Problem Statement
In #19156, we removed Monolog's `current_user` processor, which was writing both `uid` and `username` information to log messages. `username` is PII, but `uid` is not. It is useful to be able to tie a log message back to the user whose actions resulted in the log message, so we should re-enable `uid`.

## Description or Additional Context 
The 'current_user' processor Monolog provides is here: https://git.drupalcode.org/project/monolog/-/blob/3.0.x/src/Logger/Processor/CurrentUserProcessor.php?ref_type=heads

This can almost certainly be used as a starting part for what we want. We specifically do *not* want to write email, username, or any other personally identifying information to the log; only user ID should be written.

The processor can be activated by adding it to a custom module's services. Example here:
https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/docroot/modules/custom/va_gov_backend/va_gov_backend.services.yml#L47

## Acceptance Criteria
- [ ] UID is add to the log messages.

**Comment by gracekretschmer-metrostar** [comment]
Pull into sprint 20.

**Comment by edmund-dunn** [comment]
![Image](https://github.com/user-attachments/assets/e31a8742-54ff-4aea-be60-78495ccd9f9b)
This is what shows up for the drupal logs being passed to Datadog, no that it is only the uid NOT the username.
