### ISSUE TITLE
Update seckit to 2.0.3

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#19188]
## Description or Additional Context 
https://www.drupal.org/sa-contrib-2024-039

A security advisory indicates we should update to seckit 2.0.3. This is of relatively low risk but should be prioritized in a reasonable manner.

## Steps for Implementation
On a clean `main` checkout, run `ddev composer update drupal/seckit` and ensure it is updated. If this does not work, in composer.json, update the reference to `^2.0.3` and run the above command again.

## Acceptance Criteria
- [ ] seckit is updated to 2.0.3. This can be verified by finding the module in the update status report and verifying its version. https://prod.cms.va.gov/admin/reports/updates (or equivalent server).

**Comment by gracekretschmer-metrostar** [comment]
Feedback from Tim: I expect this as a standard module update.
