### ISSUE TITLE
New VAMC system website: Manila VA Clinic

### ISSUE THREAD

**Issue by davidmpickett** [department-of-veterans-affairs/va.gov-cms#19185]
### Information needed from Product / VHA DM
- [x] The **plain language name** for the VAMC system?
   - [x] Manila VA Clinic = name of facility
   - VA Manila health care = matches pattern of other VAMC systems
- [x] Which VISN is this system in? = 21

### Create initial VAMC System Drupal entities [Sitewide team]
- [x] Add a new Term in the [Sections taxonomy](https://prod.cms.va.gov/admin/structure/taxonomy/manage/administration/overview) 
   - [x] Nest the term under VHA > VAMC Facilities > VISN 21
   - [x] Name = **VAMC system plain language name**
   - [x] As you create all the subsequent Drupal entities, assign them to this Section
- [x] [Add a new Menu](https://prod.cms.va.gov/admin/structure/menu/add)
   - [x] Title = **VAMC system plain language name**
   - [x] Administrative summary = VISN 21 | va.gov/**plain-language-name**
- [x] [Add a VAMC System](https://prod.cms.va.gov/node/add/health_care_region_page)
   - [x] Fill out all required fields
      - [x] Meta description = placeholder?
      - [x] Banner image = placeholder?
      - [x] GovDelivery ID(s) = placeholder?
      - [x] Menu settings > Menu link title = **VAMC system plain language name**
      - [x] Menu settings > Parent link = `<VAMC system plain language name>`
      - [x] System menu = **VAMC system plain language name**

### Create one copy of each of these hardened VAMC content types [CMS helpdesk or Sitewide team]
 - [x] Parent link = `<VAMC system plain language name>`
    - [x] VAMC System Billing and Insurance
    - [x] VAMC System Medical Records Office
    - [x] VAMC System Operating Status
    - [x] VAMC System Register for Care
    - [x] Health Services List
    - [x] Events List
    - [x] News Releases List
    - [x] Stories List
    - [x] Leadership List
    - [x] VAMC System Policies Page
    - [x] VAMC System VA Police page

### Clone (from where?) these semi-hardened VAMC detail pages [CMS helpdesk or Sitewide team]
- [x] Parent link = `<VAMC system plain language name>`
  - [x] Make an appointment
  - [x] Pharmacy
  - [x] About us
  - [x] Programs
  - [x] Research
  - [x] Work with us
  - [x] Contact us
- [x] Parent link = Health Services List
  - [x] Homeless Veteran care
  - [x] LGBT Veteran care
  - [x] Mental health care
  - [x] Minority Veteran care
  - [x] Patient advocates
  - [x] Returning service members
  - [x] Suicide prevention
  - [x] Women Veteran care
- [x] Parent link = About us
  - [x] Mission and vision
  - [x] History
  - [x] Performance
- [x] Parent link = Work with us
  - [x] Jobs and careers
  - [x] Internships and fellowships
  - [x] Volunteer or donate
  - [x] Doing business with us

### Find any existing VAMC facilities that belong to this system [CMS helpdesk or Sitewide team]
- [x] Set them to the appropriate Section
- [x] Set their Parent link settings to ???

### Menu configuration and clean up [CMS helpdesk or Sitewide team]
- [x] Go to [Content / Menus](https://prod.cms.va.gov/admin/structure/menu)
- [x] Find the relevant menu and select edit menu
- [x] Ensure all menu links are nested in the proper place
- [x] Set some menu links to disabled 
- [x] Consult [Manila sitemap in sharepoint](https://dvagov.sharepoint.com/:x:/s/SitewideContract/EdEKl_6X5vRDs7uTjg5tMNUBfXEsWuK834vmp7Hs4FZXZQ?e=b7juyL) for menu settings 

**Suggested cut line for this ticket**
---
### User set up [CMS helpdesk / Drupal admin]
- [ ] Create users if needed / assign users to the appropriate section
- [ ] Communicate to user that they can start editing (and explain what they shouldn't do)

### VAMC editor tasks
- [ ] Complete training if they haven't already
- [ ] Do all the things listed [here](https://prod.cms.va.gov/help/vamc)
- [ ] Do we have a checklist like we do for VBA?
- [ ] Confirm when ready to publish

### Launch tasks
- [ ] DRUPAL Enable the menu in Menu Breadcrumbs module
- [ ] DRUPAL Ensure URL aliases are functioning properly
- [ ] FE Update CONTENT BUILD FILE with the menu
- [ ] Lighthouse coordination for service push?
- [ ] Redirects? 
- [ ] Comms, change management?

**Comment by davidmpickett** [comment]
@mmiddaugh @Agile6MSkinner to get started on building out Manila we need to decide what the plain language name of the system/site will be
- **Manila VA Clinic** = same as the name of the only facility, but adds an engineering ticket (my recommendation)
- **VA Manila health care** = matches pattern of other VAMC systems, but might create confusion for users

**Comment by mmiddaugh** [comment]
I support use of Manila VA Clinic to avoid creating an artificial hierarchy or the necessity of changes to the VAMC Menu Custom Access configuration.

**Comment by davidmpickett** [comment]
PR for adding menu ready for review by @omahane. [Pinged on slack too](https://dsva.slack.com/archives/C0FQSS30V/p1726177430434179)

**Comment by davidmpickett** [comment]
Menu PR is merged, should be available after CMS daily deploy

**Comment by davidmpickett** [comment]
**End of sprint update**
All initial content has been created in Prod: https://prod.cms.va.gov/section/vha/vamc-facilities/manila-va-clinic

URL aliases need some support

**Comment by davidmpickett** [comment]
@Agile6MSkinner @mmiddaugh @omahane I just added a **suggested cut line** to this ticket. All the initial content creation and menu configuration is complete. I think we're at a state where this could be passed off to an editor and they could start updating content. 

There are definitely still some technical pieces that will need to be completed before we're ready for publish / launch, but those would probably be best handled in separate tickets

**Comment by davidmpickett** [comment]
**End of sprint update**
- My site building work is complete
- Pending decision from Product on proposed Cut line

**Comment by jilladams** [comment]
@Agile6MSkinner I saw you 👍 Dave's proposed cut line. WHere do the items below that line go?

**Comment by jilladams** [comment]
I moved the remaining ACs to [STUB: Manila overflow #19270](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19270). Closing this.
