### ISSUE TITLE
VAMC Menu Custom Access Config Adjusted for a New Pattern (launch blocking)

### ISSUE THREAD

**Issue by Agile6MSkinner** [department-of-veterans-affairs/va.gov-cms#19199]
### User Story
As a Drupal Editor, I should only be able to set the parent link for Manila on certain specific detail pages.

### Description
[Here is the place where the logic exists and needs to be updated](https://prod.cms.va.gov/admin/config/content/va_gov_menu_access)

We also need to enable the Manila VA Clinic menu within [Menu Breadcrumbs](https://prod.cms.va.gov/admin/config/user-interface/menu-breadcrumb) module and ensure that gets to Prod correctly.

### ACs
- [x] Configuration is updated
- [ ] Manila parent link is only available to editors on intended VAMC Detail pages per other system custom menu access.
- [ ] Pages with a left sidenav correctly present breadcrumbs based on [Manila VA menu](https://prod.cms.va.gov/admin/structure/menu/manage/manila-va-clinic) structure (which is non-standard for a VAMC)

**Comment by omahane** [comment]
Running into a couple issues:
1. Users outside of the Manila VA Clinic section have access to the Manila VA Clinic menu when setting the parent link
2. The root of the menu when setting the parent link is not showing as the Manila VA Clinic

**Comment by omahane** [comment]
While the parent link is not as it is in the other systems, I don't see an issue with this menu rood for editors:
![Image](https://github.com/user-attachments/assets/cc1f91d3-19d4-48c9-b23f-0ae2e988e97e)

**Comment by jilladams** [comment]
Merged this morning, moving to Prod verification, because it should deploy on Wed 10/16.

**Comment by jilladams** [comment]
@davidmpickett I would love to get your help verifying this when you're back. This should be the last launch blocking issue for Manila, and I took a look but feel shaky in my understanding of the content modeling to prove that we're ready to go live.

**Comment by davidmpickett** [comment]
Verified on Staging via:

- Logging in as [Anthony.Rivera3@va.gov](https://staging.cms.va.gov/user/1530)
- Correctly CANNOT change menu parent link on VAMC Detail Pages like Returning service member care and Pharmacy
- ![Image](https://github.com/user-attachments/assets/116c0d9f-2df1-4db6-a3a0-a679604fb5d4)
- When creating new VAMC detail page, it correctlys allow placement under Programs, Research, and Work with us sub categories
- ![Image](https://github.com/user-attachments/assets/54c7a715-70b1-4f06-818c-22b7b51915f8)
