### ISSUE TITLE
Pages for published facilities with no address are displaying incorrect markup

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#19207]
## Description or Additional Context 
During Lighthouse V1 implementation in facilities-api V2 endpoint, the shape of data for a facility with no address changed from NULL to empty array. This caused the error reported & fixed in #19172. 

This is also causing an issue on published Facility pages with no address. To see the issue: 

https://www.va.gov/black-hills-health-care/locations/rapid-city-compensated-work-therapytransitional-residence/

![Screenshot 2024-09-13 at 10 10 11 AM](https://github.com/user-attachments/assets/4e6b337e-bbd5-4e3e-9925-85eb99bb0c7a)

CMS page for that node: https://prod.cms.va.gov/black-hills-health-care/locations/rapid-city-compensated-work-therapytransitional-residence/

## Engineering notes
We need to review the code and confirm if we were previously correctly handling locations with no address, and just need to update for the API data change. OR: flag if something else needs product determination here.

## Acceptance Criteria
- [ ] 
- [ ] Requires design review
- [ ] Requires accessibility review

**Comment by jilladams** [comment]
I've tagged this as VAMC (where we have a confirmed report), but have also tagged Vet Center and VBA, as I think we need to review those templates and just make sure that no address handling is correct in those cases as well. We may not have any facilities with no address in those categories to test with. (I am not sure, but I'm guessing you may not be able to generate an address-free facility in Tugboat via Drupal directly, so we may need to talk about how to verify those cases.)

**Comment by eselkin** [comment]
This is not the same error as the array from lighthouse because this is a drupal generated page from content-build. But it still is a similar issue because drupal must not have an address.

**Comment by jilladams** [comment]
Per @mmiddaugh , this is an editorial responsibility issue and the location should never be published with such minimal information: https://dsva.slack.com/archives/C0FQSS30V/p1726251906404129?thread_ts=1726247838.339929&cid=C0FQSS30V

We will follow up with VHA about it. Closing, since we don't expect to spend team effort on preventing this from happening again. We can always reopen if we change our minds.
