### ISSUE TITLE
[EPIC] Sitewide: Zero silent failures

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#19219]
## Project Tracking
https://dsva.slack.com/lists/T03FECE8V/F07PF7S4Y91?view_id=View07PF7S5ATD

## Background
https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/platform/practices/zero-silent-failures/how-to-discover-if-your-app-has-silent-failures.md

### What is a silent failure?
Silent failures are any errors that occur within your application on any public facing VA platform (VA.gov, mobile application, VA Notify, et. al.) whereby the user (Veteran, claimant, 3rd party, etc.) interacting with your application is NOT made aware that an error has occurred.

### What is NOT a silent failure?
If an application returns an error to the user immediately upon detection of the error, then the error is not silent.
If an application sends an email to the user notifying them that an error with their transaction has occurred, then the error is not silent (so long as sending the email is also monitored and confirmed to have been sent).

It is our collectively responsibility as stewards of the Veteran's data to track these problems down and fix them. We appreciate your support and dedication in helping us reach the goal of zero silent errors. This is a blameless process. We want to thoroughly investigate this problem so that we know the depth and breadth of the problem and can take the necessary steps to address it.

## Description or Additional Context 
In this epic, we will audit Sitewide portfolio to see which, if any, of our products meet the standards for the Zero silent failures initiative. 

**Guidance:** https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/platform/practices/zero-silent-failures/how-to-discover-if-your-app-has-silent-failures.md

**Comment by jilladams** [comment]
@FranECross @Agile6MSkinner FYI, this is framed up as a Sitewide epic to track all the Silent failures work across both PW / Facilities portfolios. If y'all wanna break it down further, feel free to make sub-epics but please set this epic as the parent for that child epic if you do.

**Comment by FranECross** [comment]
@jilladams I'm good with having a combined epic, but defer to @Agile6MSkinner if he wants them split and can create a PW one. Thanks!

**Comment by Agile6MSkinner** [comment]
Combined epic is good!

**Comment by FranECross** [comment]
Associated tickets added as sub-issues.

**Comment by FranECross** [comment]
Issues that are 'consider', or blocked by Lighthouse actions, have been moved to this [epic](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/20007).  When the remaining ticket (19369) is completed, we can close this epic. cc @jilladams @Agile6MSkinner

**Comment by FranECross** [comment]
Tickets in this epic completed. Tickets that may or may not be able to be implemented and need research have been moved to a new epic.
