### ISSUE TITLE
[Forms] Monitor updated forms in response to outcome of #18898

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-cms#19228]
## Description
Ticket #18898 explored why  Form 10-334 was displaying a future "Form updated" date on VA.gov: April 2028. 

A decision was made to explore option 1 of the two suggestions in that ticket, which is:

Ask the Forms Managers to let us know when they update forms for a period of time, to be able to monitor whether Drupal picks up changes we have been notified about. I could send that email, if we think this is an ok minimal approach. Looking at the [history of Form edits](https://prod.cms.va.gov/admin/content?title=&type=va_form&moderation_state=All&owner=All), it looks like we get updates from the migrator every couple days, so it might not take long to increase our confidence that we are getting most changes successfully in prod.

## BLUF of Findings of 18898

BLUF: We can't repro the bug, and should close this as can't repro. But: we can opt to add some logging or do some stakeholder outreach with Forms Managers to rule out a more system issue, short term. Notes below that need a product call. cc @FranECross @mmiddaugh for product input.

From 1:1 with @dsasser : 
* He was able to test on Tugboat: provide an alternate CSV, make a CSV change, run the migration, and see that change get picked up by Drupal CMS successfully. We officially cannot repro this issue.
* We've effectively ruled out everything from Forms, CSV, migration, caching (file system, Drupal).
* We believe that this may have been a one-time fluke potentially at the network layer. We can't prove that without a history of the migration CSV, to compare times / network logs, etc.
* One thing we will document: There is an override from the migration, in PHP settings files. That's not obvious up front, so Daniel will update https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/READMES/migrations-forms.md to note it for future.

**Some ideas about what to do next:** 
1. We could ask the Forms Managers to let us know when they update forms for a period of time, to be able to monitor whether Drupal picks up changes we have been notified about. I could send that email, if we think this is an ok minimal approach. Looking at the [history of Form edits](https://prod.cms.va.gov/admin/content?title=&type=va_form&moderation_state=All&owner=All), it looks like we get updates from the migrator every couple days, so it might not take long to increase our confidence that we are getting most changes successfully in prod.
2. We could store some history of CSVs (1 week / 1 month?) in S3, in a bucket where we are only charged for accessing data to minimize cost, in order to have a record of prior Forms DB changes. That would allow us to programmatically compare the contents of CSVs from different days, to know when a change was introduced and should have been made by the migration, and then inspect if any network logs / issues might be affecting the CSV migration. We would likely need some CMS permissions / buy in to go this route.

Either of those should likely be a new ticket, depending on how we want to approach it. Leaving this ticket open til we get a chance to discuss / decide if we'll follow up in a new ticket.

## Acceptance criteria
- [ ] Log the form update information received by Forms editors
- [ ] Review to determine if the issue still occurs

**Comment by jilladams** [comment]
Thank you @FranECross ! Would you like me to go ahead with outreach to Forms Managers?

**Comment by FranECross** [comment]
@jilladams That would be amazing, thank you!

**Comment by jilladams** [comment]
From planning: let's plan proactively to go ahead with Step 2 in a future sprint.
Jill will reach out to Forms managers.

**Comment by jilladams** [comment]
Let's also notify CAIA of the status / plan for their awareness.

**Comment by jilladams** [comment]
Notified CAIA: https://dsva.slack.com/archives/C52CL1PKQ/p1726695544948859?thread_ts=1721330369.209779&cid=C52CL1PKQ

**Comment by jilladams** [comment]
Email sent to Forms Managers, subject: "VA.gov request for Forms Manager assistance". 🤞

**Comment by jilladams** [comment]
VBA forms mgr sent us one, Should appear in Drupal morning of Fri 9/20 to verify. 

- VA Form 22-10282 was uploaded this morning (Thurs 9/19)
- Issue date – 9/19/24
- Rev. date – 9/2023 (am clarifying with the Mgr whether this should actually read 2024, since the current Revision date in Prod is 7/2024)
- No changes to the form name/title

Form node: https://prod.cms.va.gov/find-forms/about-form-22-10282. Updated details will appear in the "Forms DB data" accordion. Screenshot of what's in prod today, for comparison:

![Screenshot 2024-09-19 at 10 28 52 AM](https://github.com/user-attachments/assets/9d14c772-1627-47a0-8493-1ecfc815375b)

**Comment by jilladams** [comment]
Migration successfully caught the above changes: 
![Image](https://github.com/user-attachments/assets/2f3b0475-d78d-46e4-943d-ee4324186531)

**Comment by jilladams** [comment]
More VBA updates were submitted yesterday, below. I didn't get a chance to see what the data looked like prior to migration, but post-migration, all of these edits were made successfully in Drupal: 

VA Form 21-4142 - https://prod.cms.va.gov/find-forms/about-form-21-4142
Issue date – 9/19/24
Rev. date – 8/2024
No changes to the form name/title

VA Form 21-4142a - https://prod.cms.va.gov/find-forms/about-form-21-4142a
Issue date – 9/19/24
Rev. date – 8/2024
No changes to the form name/title

VA Form 21-4170 - https://prod.cms.va.gov/find-forms/about-form-21-4170
Issue date – 9/19/24
Rev. date – 8/2024
No changes to the form name/title


**One incorrect**
VA Form 21-4502 - https://prod.cms.va.gov/find-forms/about-form-21-4502
Issue date – 9/19/24
Rev. date – 8/2024

The Revision date here shows September 2024 instead in Drupal, and that was a part of the revision last night: https://prod.cms.va.gov/node/5969/revisions/view/906199/919385/unified_fields

Emailing the Forms mgr to clarify.

**Comment by jilladams** [comment]
So far, all the changes reported by Forms managers have successfully appeared in Drupal. @FranECross we will need to decide if that's sufficient. I might prefer that we go ahead and cut the ticket for the "save more days of logged CSVs" ticket as a failsafe that would be useful to have in place to help debug any future issues, and keep that in the backlog as an opportunistic thing we could do some time when we have time.

**Comment by FranECross** [comment]
@jilladams Thanks so much. I like the idea of the failsafe and will get a ticket cut for that this week. Putting a reminder in my task list. Closing this ticket.
