### ISSUE TITLE
Update Drupal Address Module to support Philippines addresses

### ISSUE THREAD

**Issue by davidmpickett** [department-of-veterans-affairs/va.gov-cms#19227]
## User Story or Problem Statement
Should an editor try to edit a [Manila facility](https://prod.cms.va.gov/manila-va-clinic), the Address widget [throws an error](https://dsva.slack.com/archives/C0FQSS30V/p1726526004557529).

Further analysis shows that this is related to the state, being "PH" (for Philippines, which is not a state). The address from the Lighthouse Facilities API is 
```
"address": {
                    "physical": {
                        "zip": "01302",
                        "city": "Pasay City",
                        "state": "PH",
                        "address1": "1501 Roxas Boulevard"
                    }
                },
```

Should an admin save the node, the facility will save with the **State** subfield as blank.

Subsequently, an editor can edit and save the facility, but this leaves the state blank.

## Steps for Implementation
The information about a given State (or "Administrative area," as they call it) in the [address module](https://www.drupal.org/project/address) comes from a dependency, the [addressing PHP library](https://github.com/commerceguys/addressing). We can subscribe to the AddressEvents::SUBDIVISIONS event described in the [module's documention](https://docs.drupalcommerce.org/v2/developer-guide/customers/addresses/#how-do-i-add-or-modify-subdivisions-for-a-country). With that, we can add whatever subdivisions we want (including "PH"). (edited)

Drupal.org
[Address](https://www.drupal.org/project/address)
Provides functionality for storing, validating and displaying international postal addresses.

## Acceptance Criteria
- [ ] An editor can edit a facility in Manila without error
- [ ] Ad admin user can edit a facility in Manila without the **State** saving as blank
- [ ] The Manila **State** can be saved as "PH|Philippines"
- [ ] On a News release, an editor may select ~~a non-US country, City, and State. If this isn't resolved in this ticket, flag for PM/DM to create a new ticket~~ "Philippines" as a US state.

**Comment by omahane** [comment]
After some more research, it looks like the information about a given State (or "Administrative area," as they call it) in the [address module](https://www.drupal.org/project/address) comes from a dependency, the [addressing PHP library](https://github.com/commerceguys/addressing). However, there's an event to which we can subscribe, the AddressEvents::SUBDIVISIONS event described in the [module's documention](https://docs.drupalcommerce.org/v2/developer-guide/customers/addresses/#how-do-i-add-or-modify-subdivisions-for-a-country). With that, we can add whatever subdivisions we want (including "PH"). (edited) 

Drupal.org
[Address](https://www.drupal.org/project/address)
Provides functionality for storing, validating and displaying international postal addresses.

**Comment by Agile6MSkinner** [comment]
@omahane to look at options and flesh out the ticket. Will also apply to the VBA facility in the Philippines.

**Comment by jilladams** [comment]
It won't block publishing Manila, but it will block future edits -- Did we decide to consider this launch blocking? Or just: asap when we understand / can get to it?

**Comment by jilladams** [comment]
5 points is assuming an old Drupal hand does the work. If this goes to someone newer, may look more like an 8.

**Comment by jilladams** [comment]
A new finding related; https://dsva.slack.com/archives/C0FQSS30V/p1732570413688519
> on Press Release node, there's also an Address field, and the Philippines is not an option.

**Comment by jilladams** [comment]
Verified in Prod.
