### ISSUE TITLE
Bug: Improper Wrapping of Service location hours

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#19239]
## Description
A FE defect was found today where the "Wed." service hours are not displaying properly:
![image](https://github.com/user-attachments/assets/7e87b43d-0327-4cda-9962-d1bfe023400b)

There's a chance the issue might have to do with the font size - if you change the font back to the smaller 16px font (rather than the newer 16.96px), this displays correctly. However, I can't figure out why this issue is showing up now and not months ago, when the typography update actually took place.

However, regardless of how it happened, The font size is correct for the new standard font across VA so we don't want to change it. We should make whatever updates are necessary to properly display these service hours at this font size. This is happening on [VAMC Service locations](https://www.va.gov/washington-dc-health-care/locations/washington-va-medical-center/#laboratory-and-pathology), [VBA Service locations](https://www.va.gov/togus-va-regional-benefit-office-at-togus-va-medical-center/#disability-compensation) and [VAMC Non-clinical services](https://www.va.gov/boston-health-care/register-for-care/)

## Acceptance Criteria
- [x] Update service location hours so all days display correctly
- [x] Ensure all 3 types (VAMC services, VAMC non-clinical, VBA services) are all updated
- [x] Requires QA

**Comment by jilladams** [comment]
@Agile6MSkinner flagging from sprint planning chat: Michelle would like us to look at this defect when we get a chance, so we should prob prioritize for refinement / ready, in case folks end up with capacity to pull something in.

**Comment by Agile6MSkinner** [comment]
I noted it as a bug and moved it to next refinement. Asked about priority in Slack. Likely candidate for brining into sprint 13 as stretch if not prioritizing.

**Comment by Agile6MSkinner** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VAgov-Sitewide-Product-Team-6645154188a81a1f7a0a9464/issues/department-of-veterans-affairs/va.gov-cms/19239?planning-poker) with Zenhub @randimays @eselkin @dsasser @chriskim2311 @SnowboardTechie @jv-agile6

**Comment by laflannery** [comment]
I was reviewing this and noticed that the times are no longer left aligned like they used to be, I discussed with @thejordanwood and from a design/UX perspective she agreed that the readability would be better to have these left aligned. For reference, the times used to look like this:

![Image](https://github.com/user-attachments/assets/0fa1b8f8-130e-4532-bd6c-a8966fe8a4b9)
 
But now there is not a straight left alignment for the hours: 

![Image](https://github.com/user-attachments/assets/8b92917c-ab47-4256-b547-df0fc9fdae3a)

@randimays and @Agile6MSkinner is this something this ticket can be reopened for or a new ticket should be created instead?

**Comment by randimays** [comment]
I think it's ok to re-open this ticket (to save us some admin time / effort). But I'm not sure I will get back to this, this sprint.

**Comment by davidmpickett** [comment]
Verified on prod
