### ISSUE TITLE
[Zero Silent Failures SPIKE] Find a VA Form (Lighthouse API connection / migration)

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-cms#19246]
## Description
The following feature needs to be evaluated to determine if it meets the standards for 'zero silent failures'. which is a user-facing transaction that is submitted to the back-end system.  If we identify any missing monitoring, etc. from evaluating the checklist, we will file tickets to update implementation.

- Find a VA Form:
  - Find a Form:
    - Form searches to LH Forms API
    - LH forms API pulls via sidekiq
  - Form Detail Page
    - LH forms API pulls via sidekiq
  - Forms migration
    - LH forms API pulls via sidekiq

OCTODE guidance states:
- Does your application have a user-facing transaction that is submitted to a back-end system?
  - NOTE: This is not limited to online forms! Other examples can include:
    - Uploads of documents and/or attachments
    - Performing an action (Such as refilling a prescription or ordering supplies)
- Are you using any of the listed APIs?
  - Lighthouse Appeals Status
  - Lighthouse Benefits Documents API
  - Lighthouse Benefits Intake API / Central Mail
  - Lighthouse Decision Reviews
  - EVSS Document Upload
- Does your application submit to an API that relies on Sidekiq (or another background job processor)?

Problem Statement:
- [See Canvas in Slack ](https://dsva.slack.com/canvas/C07KTTFP308)

### Artifacts
- [Audit ticket](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19220)
- [Guidance document](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/platform/practices/zero-silent-failures/how-to-discover-if-your-app-has-silent-failures.md)
- [Sitewide Silent failures assessment](https://docs.google.com/document/d/1pZePkdB-p298QF8RXfK2-KRfNNegLhpytia_aiai8jU/edit#heading=h.5tmqzsfjv2t7)
- [Sitewide Silent Failure Assessment pre-screen](https://docs.google.com/spreadsheets/d/1X_cen1USFXlvNxkgkSwMdDIjgmSvP06c1H9whg0wPAY/edit?gid=0#gid=0)

### User story

**AS A**
**I WANT**
**SO THAT**

### Engineering notes / background

If you need to set up monitoring in DataDog:
### Set up monitoring in Datadog

Follow this [guidance on endpoint monitoring](https://depo-platform-documentation.scrollhelp.site/developer-docs/endpoint-monitoring) to get going. Then following the guidance on [monitoring performance](https://depo-platform-documentation.scrollhelp.site/developer-docs/monitor-applications-and-infrastructure-with-datad) to get up to speed with Datadog.

#### Examples

* [Benefits Intake API Form Submission Tracking](https://vagov.ddog-gov.com/dashboard/4d8-3fn-dbp/benefits-intake-form-submission-tracking?fromUser=false&refresh_mode=sliding&from_ts=1725259648303&to_ts=1725864448303&live=true)
* [Banana Peels (Lighthouse Appeals/Forms/Benefits Intake APIs)](https://vagov.ddog-gov.com/dashboard/aea-kge-ekt/banana-peels-lighthouse-appealsformsbenefits-intake-apis?fromUser=true&refresh_mode=sliding&from_ts=1725259764640&to_ts=1725864564640&live=true)
* [Benefits Sidekiq Death Queue view](https://vagov.ddog-gov.com/dashboard/ftx-zzd-v9j/benefits-sidekiq-job-death-queue-view) - shows recently exhausted Sidekiq jobs.

[Additional examples](https://depo-platform-documentation.scrollhelp.site/developer-docs/platform-dashboards-in-datadog)

#### Start

* [x] Do you know when your application shipped to production?
  * Early 2020 from github docs
* [x] Did your application use the same APIs when it shipped as it does today?
  * Yes it does.

#### Monitoring

* [x] Do you monitor the API that you submit to via Datadog? 
  * LH monitors these endpoints in their own LH non-VSP Datadog instances. Slack thread: https://dsva.slack.com/archives/CUB5X5MGF/p1727281368978889
* [ ] Does your Datadog monitoring use the appropriate tagging?
  * Monitoring is not apart of VSP anymore. LH does have monitors in place with alerts.
* [x] Do errors detected by Datadog go into a Slack notifications channel?
  * Yes LH does get alerts for these API migrations.
* [x] Does more than one person look at the Slack notifications channel containing errors on a daily basis? 
  * Yes their team does have more than one person looking at Slack notifications.
* [ ] Do the team members monitoring the Slack channel have a system for acknowledging and responding to the errors that appear there? 
  * If not, create a ticket to then follow this [guide on managing errors](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/platform/practices/zero-silent-failures/managing-errors.md)

⚠️ **Failure to have endpoint monitoring in place is a blocking QA standard at Staging review as of 9/10/24.** If you answered no to any of the questions above, you will be blocked from shipping at the Staging review touchpoint in Collab Cycle.

#### Reporting errors

* [x] Have you filed issues for errors that are appearing in Datadog / Slack?
  * No issues will show in VSP datadog. LH will get alerted for errors and file issues for them.
* [x] Do all fatal errors thrown in your application end up visible to the end user either in the user interface or via email?
  * For Find Forms we show error messages for different errors in the find forms flow to the user. We show no results if a no results are returned from the LH API and we show Invalid PDF Link, Invalid PDF accessed, and onDownloadLinkClick specific errors when trying to click on the download pdf links.

#### Documentation

* [x] Do you have a diagram of the submission path that user data your application accepts takes to reach a system of record? 
  * A user will use the Find a VA form service then the data will be populated by using this flow from the CMS to the LH API. https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/READMES/migrations-forms.md#cms-forms-data-to-va-forms-api-lighthouse
* [x] Do you understand how the error is handled when each system in the submission path fails, is down for maintenance, or is completely down?
  * There are a few points of failure listed here: https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/READMES/migrations-forms.md#points-of-failure
* [ ] Has the owner of the system of record receiving the user's data indicated in writing that their system notifies or resolves 100% of fatal errors once in their custody?
* I don't know if LH resolves all of these potential errors.
  * If not, notify @jilladams , @FranECross , @mmiddaugh to work with OCTO to meet with the owner of the system and get their agreement in writing.
    * Please document the outcome of this conversation in your product's documentation in Github.

#### User experience

* [x] Do you capture all of the potential points of failure and make those errors known to the user via email notification and/or through the application on VA.gov or the mobile application?
  *  Errors are shown directly to the user in the interface depending on the caught error but not specific to API connections or migration failures. If there is a migration failure the user will still see results since there are safety measures in place to use previous migrated data.

- [x] Create a user data flow diagram 
  * Data flow to the user: https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/READMES/migrations-forms.md#data-flow

[Learn how to create a user data flow diagram](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/platform/practices/zero-silent-failures/how-to-create-a-user-data-flow-diagram.md)

#### File silent errors issues in Github
  - [ ] Create a ticket to file silent error issues in Github
We want to know about your silent errors so that we can help you to fix them. To do this, follow the process in the [Managing Errors](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/platform/practices/zero-silent-failures/managing-errors.md) document.

## We don't have any silent errors!

Great! Please let us know that you went through the checklist above as a team and did not find any silent failures in our Slack channel: [#zero-silent-failures](https://dsva.slack.com/archives/C07KTTFP308). You don't have to hang out in there once you have notified us. Just pop in, tell us who you are (which team and in which portfolio) and that no failures were found. Thanks!

**Comment by jilladams** [comment]
@humancompanion-usds question: Find Forms relies on the LH Forms API, and that API pulls from Drupal via sidekiq job. We are feeling muddy on whether / how that meets the criteria here. We do **rely** on an API that relies on Sidekiq (or another background job processor), but we do not **submit** to that API. They pull from us. Curious your thoughts on the ownership of the onus for silent failure, that in mind. Do you happen to know if LH has gotten the same mandate / if they'll be doing similar audits?

**Comment by humancompanion-usds** [comment]
The most common case of silent failure is when we take data from a user and submit it and that submission fails async. I'm not quite following you you rely on an API that pulls from find a form. If you wouldn't mind pointing me to a data flow diagram, if you have one, that might help me to catch up. There is a [template](https://app.mural.co/t/departmentofveteransaffairs9999/template/10528961-f660-4adc-8d25-88405cd7958c) in Mural if you want to create one to demonstrate the flow.

Lighthouse is, for the most part, middleware in that it takes a submission from us and passes it onto another back-end system. When there are failures in those back-end systems Lighthouse returns those to us to manage. To their knowledge they have no errors that they fail to notify us of.

**Comment by jilladams** [comment]
@humancompanion-usds Sure thing - this is the data flow: https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/READMES/migrations-forms.md

What happens: 
* Forms DB (owned by OIT) is the source of truth
* Nightly, Drupal pulls Forms DB data and stores it in the Drupal DB.  (We use that to create form detail pages for some forms)
* Nightly, Lighthouse Forms API then pull that forms data from Drupal, via sidekiq job.
* The find-a-form interface queries Lighthouse for Form data.

So the proper user-facing silent failure would be limited to search in Find-a-Form, e.g if a user submitted a search and got no results and no error, or got partial results maybe? We handle that and aren't concerned about that area having silent failures.  

But: Michelle is concerned about our data integrations, and making sure that data is making it to its end destinations. We are not really _sending_ data from Find a Form, and if Lighthouse is sure that they don't have errors where they fail to notify, then this ticket might be a no-op?

**Comment by humancompanion-usds** [comment]
I'd recommend ensuring that we have monitoring in place to ensure we know when the data does not make it to an end destination and that you all have a playbook for how to handle those errors when they pop up in monitoring. This aligns with the [endpoint monitoring QA standard](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-endpoint-monitoringEndpointMonitoring).

**Comment by jilladams** [comment]
If we end up needing to talk to Lighthouse about the state of their monitoring, you can find Kristen Brown and Matt Kelly in the #va-forms channel.

**Comment by chriskim2311** [comment]
Spoke to Lighthouse folks in va-forms slack: https://dsva.slack.com/archives/CUB5X5MGF/p1727281368978889.

Lighthouse is monitoring the sidekiq jobs and get alerts if the migration job fails. The job continuously tries to migrate for about an hour before being exhausted. The LH team does have monitors in place and gets alerts for failures of this job through their non-VSP LH Datadog monitors.

In terms of FE for users, failures are shown to the end user for various failures(Invalid PDF Link, Invalid PDF accessed, and onDownloadLinkClick error) and monitors will be moved to datadog with Sentry being deprecated as part of this epic: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18766.

@FranECross @jilladams I don't think there are any other steps needed for this ticket as monitoring is in place on the LH side of things. Let me know if there are any outstanding questions and I can look into them thanks!

**Comment by jilladams** [comment]
@chriskim2311 this is annoying, but do you mind in the ticket body just updating the checklist to reflect which you've verified / any notes for cases where the question didn't have an obvious answer / you had to go find it? This will act as a document moving forward to prove that we did our due diligence.

**Comment by chriskim2311** [comment]
@jilladams Not a problem I will update it today!

**Comment by chriskim2311** [comment]
@jilladams @FranECross Updated the checklist and should be ready for your review.

**Comment by chriskim2311** [comment]
Closing this from conversation in demo. No more tasks need to be completed.
