### ISSUE TITLE
[Zero Silent Failures Spike] Global search in header and results page

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-cms#19244]
## Description
The following features needs to be evaluated to determine if it meets the standards for 'zero silent failures', which is a user-facing transaction that is submitted to the back-end system. For the two below, search terms are sent to the Search.gov API. If we identify any missing monitoring, etc. from evaluating the checklist, we will file tickets to update implementation.

- Search / results form in header
- Search results page

OCTODE guidance states:
- Does your application have a user-facing transaction that is submitted to a back-end system?
  - NOTE: This is not limited to online forms! Other examples can include:
    - Uploads of documents and/or attachments
    - Performing an action (Such as refilling a prescription or ordering supplies)
- Are you using any of the listed APIs?
  - Lighthouse Appeals Status
  - Lighthouse Benefits Documents API
  - Lighthouse Benefits Intake API / Central Mail
  - Lighthouse Decision Reviews
  - EVSS Document Upload
- Does your application submit to an API that relies on Sidekiq (or another background job processor)?

Problem Statement:
- [See Canvas in Slack ](https://dsva.slack.com/canvas/C07KTTFP308)

### Artifacts
- [Audit ticket](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19220)
- [Guidance document](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/platform/practices/zero-silent-failures/how-to-discover-if-your-app-has-silent-failures.md)
- [Sitewide Silent failures assessment](https://docs.google.com/document/d/1pZePkdB-p298QF8RXfK2-KRfNNegLhpytia_aiai8jU/edit#heading=h.5tmqzsfjv2t7)
- [Sitewide Silent Failure Assessment pre-screen](https://docs.google.com/spreadsheets/d/1X_cen1USFXlvNxkgkSwMdDIjgmSvP06c1H9whg0wPAY/edit?gid=0#gid=0)

### User story

**AS A**
**I WANT**
**SO THAT**

### Engineering notes / background

If you need to set up monitoring in DataDog:
### Set up monitoring in Datadog

Follow this [guidance on endpoint monitoring](https://depo-platform-documentation.scrollhelp.site/developer-docs/endpoint-monitoring) to get going. Then following the guidance on [monitoring performance](https://depo-platform-documentation.scrollhelp.site/developer-docs/monitor-applications-and-infrastructure-with-datad) to get up to speed with Datadog.

#### Examples

* [Benefits Intake API Form Submission Tracking](https://vagov.ddog-gov.com/dashboard/4d8-3fn-dbp/benefits-intake-form-submission-tracking?fromUser=false&refresh_mode=sliding&from_ts=1725259648303&to_ts=1725864448303&live=true)
* [Banana Peels (Lighthouse Appeals/Forms/Benefits Intake APIs)](https://vagov.ddog-gov.com/dashboard/aea-kge-ekt/banana-peels-lighthouse-appealsformsbenefits-intake-apis?fromUser=true&refresh_mode=sliding&from_ts=1725259764640&to_ts=1725864564640&live=true)
* [Benefits Sidekiq Death Queue view](https://vagov.ddog-gov.com/dashboard/ftx-zzd-v9j/benefits-sidekiq-job-death-queue-view) - shows recently exhausted Sidekiq jobs.

[Additional examples](https://depo-platform-documentation.scrollhelp.site/developer-docs/platform-dashboards-in-datadog)

#### Start

* [x] Do you know when your application shipped to production? 
  * If not, use Github to determine, roughly, when your application shipped to users.

**[Around 6 years ago the original search was introduced](https://github.com/department-of-veterans-affairs/vets-website/commit/82069d5ebc467a9fae89df17f4704b560e022166) and has been built upon since**

* [x] Did your application use the same APIs when it shipped as it does today? 
  * If not, then you'll need to consider the path user data took through both the current architecture and the previous architecture. You will need to account for potential failures in all paths since your application shipped.

**No, it has been recently adjusted to move from an API directly on search.gov to an identical one provided at gsa.gov. This was done per the search providers recommendation and is an identical endpoint. User data is not being captured/lost with this change.**

#### Monitoring

* [x] Do you monitor the API that you submit to via Datadog? 
  * If not, create a ticket to [set up monitoring in Datadog](#set-up-monitoring-in-datadog).

**Yes, monitored in multiple ways [here](https://vagov.ddog-gov.com/monitors/manage?q=tag%3A%28service%3Asearch%29%20status%3Aok&order=asc&sort=status)**

* [x] Does your Datadog monitoring use the appropriate tagging?
  * If not, create a ticket to [implement tagging standards](https://depo-platform-documentation.scrollhelp.site/developer-docs/monitor-tagging-standards). Adding the [dependency tag](https://depo-platform-documentation.scrollhelp.site/developer-docs/monitor-tagging-standards#MonitorTaggingStandards-Recommended:dependency) is highly recommended!
 
**Yes all monitoring has the appropriate required tags at minimum**

* [x] Do errors detected by Datadog go into a Slack notifications channel?
  * If not, create a ticket to start directing errors in Datadog to a dedicated Slack channel. See [#veteran-facing-forms-notifications](https://dsva.slack.com/archives/C063SM22J3H) for an example.

**Yes, errors from monitors alert the #public-websites-dd-search channel in slack**

* [x] Does more than one person look at the Slack notifications channel containing errors on a daily basis? 
  * If not, create a ticket to then follow this [guide on managing errors](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/platform/practices/zero-silent-failures/managing-errors.md)

**Yes, the Sitewide team follows this channel which currently has 15 members**

* [x] Do the team members monitoring the Slack channel have a system for acknowledging and responding to the errors that appear there? 
  * If not, create a ticket to then follow this [guide on managing errors](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/platform/practices/zero-silent-failures/managing-errors.md)

**Yes, Sitewide has monitors assigned weekly who watch the channel more actively to investigate errors that occur and connect with the appropriate VFS teams to help resolve if a solution can't be introduced through git**

⚠️ **Failure to have endpoint monitoring in place is a blocking QA standard at Staging review as of 9/10/24.** If you answered no to any of the questions above, you will be blocked from shipping at the Staging review touchpoint in Collab Cycle.

#### Reporting errors

* [x] Have you filed issues for errors that are appearing in Datadog / Slack?
  * If not, create a ticket to then start filing Github issues for new categories of errors following [this guidance](#file-silent-errors-issues-in-github)
* [x] Do all fatal errors thrown in your application end up visible to the end user either in the user interface or via email?
  * If not, create a ticket to then file Github issues to capture error categories following [this guidance](#file-silent-errors-issues-in-github)

#### Documentation

* [x] Do you have a diagram of the submission path that user data your application accepts takes to reach a system of record? 
  * If not, then create a ticket to [create a user data flow diagram](#how-to-create-a-user-data-flow-diagram) that captures this information. https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19353
* [x] Do you understand how the error is handled when each system in the submission path fails, is down for maintenance, or is completely down?
  * If not, create a ticket to then create documentation that captures how errors in each system are handled. Detail which systems retry a submission and what happens when those retries exhaust. Show this in your diagram.
* [x] Has the owner of the system of record receiving the user's data indicated in writing that their system notifies or resolves 100% of fatal errors once in their custody?
  * If not, notify @jilladams , @FranECross , @mmiddaugh to work with OCTO to meet with the owner of the system and get their agreement in writing.
    * Please document the outcome of this conversation in your product's documentation in Github.
 
**The API interactions include a GET request to the vets-api that utilizes a search.gov API GET request to generate the results. The possible error will be returned as HTTP errors**

#### User experience

* [x] Do you capture all of the potential points of failure and make those errors known to the user via email notification and/or through the application on VA.gov or the mobile application?
  * If not, note here but don't worry. Few teams are doing this and we'll be providing resources to help you do this in your application. Proceed to [create a user data flow diagram](#how-to-create-a-user-data-flow-diagram). That diagram will help us to help you and your team to create this user experience.

- [x] Create a user data flow diagram 
  - [x] Create a ticket to create a user flow based on the requirement noted below: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19353
     - Creating a user data flow diagram is a requirement of the Zero silent errors initiative and will be a required asset at the Architecture Intent touchpoint of the Engineering and Security track of Collaboration Cycle.

[Learn how to create a user data flow diagram](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/platform/practices/zero-silent-failures/how-to-create-a-user-data-flow-diagram.md)

#### File silent errors issues in Github
  - [x] Create a ticket to file silent error issues in Github
We want to know about your silent errors so that we can help you to fix them. To do this, follow the process in the [Managing Errors](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/platform/practices/zero-silent-failures/managing-errors.md) document.

## We don't have any silent errors!

Great! Please let us know that you went through the checklist above as a team and did not find any silent failures in our Slack channel: [#zero-silent-failures](https://dsva.slack.com/archives/C07KTTFP308). You don't have to hang out in there once you have notified us. Just pop in, tell us who you are (which team and in which portfolio) and that no failures were found. Thanks!

**Comment by jilladams** [comment]
Because Github markup / styling has changed and it's harder to see now: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19353 was cut, as a follow up of this ticket.

**Comment by jilladams** [comment]
Reviewed Bryan's notes, and we have the follow up ticket in current sprint. Closing.
