### ISSUE TITLE
Add Manila Menu to Menu list in Content Build (launch blocking)

### ISSUE THREAD

**Issue by Agile6MSkinner** [department-of-veterans-affairs/va.gov-cms#19273]
As Manila, I would like a menu so that I can be like the other kids.

https://github.com/department-of-veterans-affairs/content-build/blob/main/src/site/stages/build/drupal/graphql/navigation-fragments/facilitySidebar.nav.graphql.js

Until this is complete, Manila pages cannot publish. THey are likely to error and break content-build.

## ACs

- [x] Manila menu appears on the left sidenav of Manila VA Clinic pages based on Section
- [x] Preview works on Manila pages
- [x] Manila pages build successfully

**Comment by Agile6MSkinner** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VAgov-Sitewide-Product-Team-6645154188a81a1f7a0a9464/issues/department-of-veterans-affairs/va.gov-cms/19273?planning-poker) with Zenhub @eselkin @SnowboardTechie @dsasser

**Comment by eselkin** [comment]
This is likely a 1 if it's just adding the Manilla facility/system but it is uncertain if that breaks anything due to the nature of the new thing. I think @davidmpickett had to comment something out to make it build in their tests.

**Comment by randimays** [comment]
Can we flesh out this ticket a bit more for folks who aren't as familiar with Facilities work?

I'm assuming we're adding a value to the `FACILITY_MENU_NAMES` const in this file: https://github.com/department-of-veterans-affairs/content-build/blob/main/src/site/stages/build/drupal/graphql/navigation-fragments/facilitySidebar.nav.graphql.js. What is the string value that needs to be added? Is this the only change that needs to be made for this ticket? How do we test that it's working / what is the applicable page?

**Comment by jilladams** [comment]
@Agile6MSkinner since this was added mid-sprint and isn't started yet, I'm moving back to ready, so we can discuss Randi's Qs in planning tomorrow.

**Comment by davidmpickett** [comment]
> Can we flesh out this ticket a bit more for folks who aren't as familiar with Facilities work?
> 
> I'm assuming we're adding a value to the `FACILITY_MENU_NAMES` const in this file: https://github.com/department-of-veterans-affairs/content-build/blob/main/src/site/stages/build/drupal/graphql/navigation-fragments/facilitySidebar.nav.graphql.js. What is the string value that needs to be added? 

`manila-va-clinic`

> Is this the only change that needs to be made for this ticket? How do we test that it's working / what is the applicable page?

This ticket is somewhat entwined with #19272. The overall goal is to have Manila VAMC pages build/preview correctly. This step is necessary, but likely not sufficient. Some example pages:

- https://prod.cms.va.gov/manila-va-clinic
- http://preview-prod.vfs.va.gov/preview?nodeId=1059
- https://prod.cms.va.gov/manila-va-clinic/work-with-us/doing-business-with-us
- http://preview-prod.vfs.va.gov/preview?nodeId=72719

**Comment by eselkin** [comment]
So, you can add pages to the clinic rather than the system node
https://main-89yl07a9qwbiyshiolbfh1ldfqvpv6zp.demo.cms.va.gov/admin/structure/menu/manage/manila-va-clinic

However, the v-w processing of these pages needs a header or something to put them under or an exception in the v-w code if the pages are from Manila

**Comment by davidmpickett** [comment]
Verified on prod: http://preview-prod.vfs.va.gov/preview?nodeId=1059
