### ISSUE TITLE
Establish metric tracker for measuring time to resolve critical defects

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#1928]
Tied to Q2O5KR2: Decrease time to resolve critical defects by 25%.

Steps:

1. Measure # of critical defects known per week/month/quarter
2. Measure # of days between issue creation and issue resolution (into done or closed pipeline)
3. Track difference in time over the entire quarter

**Comment by cmaeng** [comment]
There is no good way for GitHub/ZenHub to automate this. Their reports don't get to the level of detail that we would need. I have an outstanding email to their support to see if there is a way to export data and manage but in the mean time I will be using [this spreadsheet](https://docs.google.com/spreadsheets/d/1D7A4eUovwFHfESMUiGeYVFYTSZpUYjo9DvhrNUjVosw/edit#gid=0) to track manually.
