### ISSUE TITLE
Manila: path updates required due to snowflake setup

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#19280]
## Description 
There are some Manila pages using default paths that are incorrect due to the special nature of the Manila setup. 

### System path
Under normal circumstances, a VAMC System path would be:
System = /PLACE-health-care
Facility = /PLACE-health-care/FACILITY-NAME

Manila is weird because the Facility IS the root of the system. So:
System = will not publish, does not get a FE page. How? There's a FE ticket to figure this out. https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19272
Facility = /manila-va-clinic

### Affected node paths
These hardened pages are using the default system path, which is incorrect for Manila. Path cannot be overridden on these nodes (the Path options do not appear on the right sidebar of the node pages): 

**Needed:**
 VAMC System Billing and Insurance - https://prod.cms.va.gov/manila-va-clinic/billing-and-insurance
 VAMC System Medical Records Office - https://prod.cms.va.gov/manila-va-clinic-system-node/medical-records-office
 VAMC System Operating Status - https://prod.cms.va.gov/manila-va-clinic-system-node/operating-status
 VAMC System Register for Care - https://prod.cms.va.gov/manila-va-clinic-system-node/register-for-care

**Not needed:**
 VAMC System Policies Page - https://prod.cms.va.gov/manila-va-clinic-system-node/policies
 VAMC System VA Police page - https://prod.cms.va.gov/manila-va-clinic-system-node/va-police

### Editor info
Manila editor has verified that 4 of these pages will be required. This ticket is launch blocking.

## Prerequisites

- [x] Manila editor has confirmed that they need / intend to publish these pages

## ACs

- [x] Path for listed Manila pages is updated to use /manila-va-clinic/ as root

**Comment by davidmpickett** [comment]
Likely controlled by" https://prod.cms.va.gov/admin/config/search/path/patterns

For Lovell there is a bit of Code in the backend module that disables pathauto for Lovell pages. [https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/docroot/mod[…]tom/va_gov_lovell/src/EventSubscriber/LovellEventSubscriber.php](https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/docroot/modules/custom/va_gov_lovell/src/EventSubscriber/LovellEventSubscriber.php#L185)
Might make sense to have something similar for Manila if we are going to do them all manually

**Comment by Agile6MSkinner** [comment]
Need to reach out to the editor to determine if these are needed and thus launch blocking. Helpdesk to reach out.

**Comment by jilladams** [comment]
Asked Helpdesk for an assist here: https://dsva.slack.com/archives/C02730UEZPS/p1727729745619329

**Comment by jilladams** [comment]
Helpdesk outreach to the editor: https://va-gov.atlassian.net/jira/servicedesk/projects/VAHELP/queues/custom/11/VAHELP-8073

**Comment by jilladams** [comment]
Editor verified they do need 4 of the 6 pages. This ticket is launch blocking, I updated ticket body and launch plan in #19271  accordingly.

**Comment by jilladams** [comment]
@jilladams to clarify with the Editor re: whether the centralized content will / won't apply, and wehther a VAMC detail page may be a better fit for the "Need" content of these top task pages. 

Pulling into sprint, but: let's wait to start it til I have that info.

**Comment by omahane** [comment]
@davidmpickett 
If `manila-va-clinic` is the root path for all content, that means we will end up with a facility (Manila VA Clinic) that is at `https://prod.cms.va.gov/manila-va-clinic/manila-va-clinic` and thus is at `https://va.gov/manila-va-clinic/manila-va-clinic`.

That may be fine, but I wanted to let you know.

I also notice that none of the health services are of the health services content types but are instead Detail pages. Why is that?

**Comment by davidmpickett** [comment]
> [@davidmpickett](https://github.com/davidmpickett) If `manila-va-clinic` is the root path for all content, that means we will end up with a facility (Manila VA Clinic) that is at `https://prod.cms.va.gov/manila-va-clinic/manila-va-clinic` and thus is at `https://va.gov/manila-va-clinic/manila-va-clinic`.
> 
> That may be fine, but I wanted to let you know.

I set the URL alias of the clinic to be https://prod.cms.va.gov/manila-va-clinic Are you saying there's something that will override that?

> 
> I also notice that none of the health services are of the health services content types but are instead Detail pages. Why is that?

Those aren't health services, they are health service Care Coordinator pages. These are on all VAMCs but are not super obvious because they aren't in the side nav. Example: https://www.va.gov/chicago-health-care/health-services/mental-health-care/

They are typically linked to from the System health service in the last line of the description https://www.va.gov/chicago-health-care/health-services/#item-mental-health-care

**Comment by omahane** [comment]
@davidmpickett I have updated the paths (at the https://prod.cms.va.gov/admin/config/search/path) for the needed pages.

For the pages we don't need (Policies and Police), should we archive or delete?

**Comment by omahane** [comment]
I just tried to create a system health service (on Staging) and got this:
`https://staging.cms.va.gov/manila-va-system/health-services/addiction-and-substance-use-care-at-manila-va-clinic`

I think we want this to be 
`https://staging.cms.va.gov/manila-va-clinic/health-services/addiction-and-substance-use-care-at-manila-va-clinic`

**Comment by jilladams** [comment]
Dave's out til Tuesday next week: let's archive, as the System may find they need these nodes later.

You are correct that we want th health service path to use `manila-va-clinic` not `manila-va-system`. If we don't think it's impactful, yay. I'm not certain of the implications -- we're saying the System health service page won't be visible to anyone bc we don't have a standard system page? (We have to make those in order to enable making a Facility Health Service right?)

**Comment by omahane** [comment]
Right, the system health services are typically listed on the system page in Drupal, but they don't show on the front-end. So I don't think it really matters what their URL is. The facility health services have the correct path, which is more important.

**Comment by jilladams** [comment]
I archived the nodes we don't need. The work here is done. The open question around the System health services paths is worth getting product to acknowledge the situation / decide if we need to programmatically ward against it, which we could roll into #19406 if so. CLosing this, and flagging that convo for scrum next week.

**Comment by davidmpickett** [comment]
@omahane Am I correct in my understanding that

1.  You performed a manual update to the paths (admin/config/search/path), rather than changing the patterns (admin/config/search/path/patterns)
2. While patterns can be exported as config and added to CMS repo as a PR, individual URL aliases are actually stored with the node and therefore environment dependent?

**Comment by jilladams** [comment]
Reopening. These URLs are still not working correctly in Tugboat after a rebuild of the env, so we need to understand how we can verify them before publishing in prod and why they don't work in lower envs.

https://cms-xwykohumwbnvcp90arpvpzfkcilh2ngo.demo.cms.va.gov/manila-va-system/register-for-care
https://cms-xwykohumwbnvcp90arpvpzfkcilh2ngo.demo.cms.va.gov/manila-va-system/billing-and-insurance
https://cms-xwykohumwbnvcp90arpvpzfkcilh2ngo.demo.cms.va.gov/manila-va-system/operating-status
https://cms-xwykohumwbnvcp90arpvpzfkcilh2ngo.demo.cms.va.gov/manila-va-system/medical-records-office

**Comment by jilladams** [comment]
Oh -- the paths just aren't righ tin that config. Fixing.

https://prod.cms.va.gov/admin/config/search/path?search=manila

**Comment by jilladams** [comment]
Working now.
