### ISSUE TITLE
[Homepage email signup] Create monitoring in Datadog for the POST call to GovDelivery

### ISSUE THREAD

**Issue by randimays** [department-of-veterans-affairs/va.gov-cms#19312]
## Status
[2024-09-24] [Fran] Reviewed, added User story and moved to next refinement

## Description
On VA.gov at the bottom of the homepage, there is a section titled "Sign up to get the latest VA updates" with an input for an email address. 

The source code for the form lives in content-build: https://github.com/department-of-veterans-affairs/content-build/blob/main/src/site/includes/email-update-signup.drupal.liquid#L6-L38

As part of the Zero Silent Failures research into Sitewide products, we investigated how this signup form integrates with the downstream API (call to GovDelivery). **Full technical details** are in [this ticket](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19242).

The purpose of this ticket is to add:
1. A Datadog monitor to catch any error codes GovDelivery sends back from the [form action URL](https://github.com/department-of-veterans-affairs/content-build/blob/762c699d0eaba45e3a3c506bfea19bf97f35484a/src/site/includes/email-update-signup.drupal.liquid#L7)
2. A Datadog synthetic test (and accompanying monitor) to verify that the ~GovDelivery page is loaded successfully with the email address pre-populated~ email input exists on the page. We can add this as a step to the existing [VA.gov homepage functional browser test](https://vagov.ddog-gov.com/synthetics/details/gsg-zui-hg8?from_ts=1727198348004&to_ts=1727201948004&live=true), ~or create a separate Datadog synthetic test to capture this flow~.

### User story

**As a PO/PM**
**AS A** PO/PM managing the feature "Sign up to get the latest VA updates" with an input for an email address found in the footer wherein an email address is entered/submitted
**I WANT** DataDog monitoring the submission 
**SO THAT** if there is a failure submitting, we're alerted and can take action, mitigating poor Veteran outcomes

**As a Veteran**
**AS A** PO/PM using the feature "Sign up to get the latest VA updates", where I input my email address and expect to then receive updates
**I WANT** the folks at VA.gov to know if my email address doesn't reach the mail list for updates
**SO THAT** if there is a failure submitting my email address, they are alerted and can take action, thus ensuring good outcomes for me

## Acceptance criteria
- [x] Datadog monitor is set up to capture errors from the [GovDelivery URL](https://public.govdelivery.com/accounts/USVACHOOSE/subscribers/qualify) endpoint used by the email signup form
- [x] Datadog synthetic for the email address field is captured in the existing [homepage synthetic test](https://vagov.ddog-gov.com/synthetics/details/gsg-zui-hg8?from_ts=1727198348004&to_ts=1727201948004&live=true) or a new synthetic is added if necessary
- [ ] All new or updated monitors follow the [Platform tagging standards](https://depo-platform-documentation.scrollhelp.site/developer-docs/monitor-tagging-standards) and include the recommended [dependency tag](https://depo-platform-documentation.scrollhelp.site/developer-docs/monitor-tagging-standards#MonitorTaggingStandards-Recommended:dependency)
- [x] New monitors successfully post to #public-websites-monitoring
- [x] New monitors added to the [Public Websites Dashboard](https://vagov.ddog-gov.com/dashboard/szu-xny-9fu/public-websites-dashboard?fromUser=false&refresh_mode=sliding&view=spans&from_ts=1727197154927&to_ts=1727200754927&live=true) in Datadog
- [x] Homepage monitoring documentation is updated here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/fbad53104ec20ff36a5a353c4c5159e91b68f3ec/products/home-page/engineering/monitoring.md

**Comment by randimays** [comment]
End-of-sprint update: Just pulled this in right before the sprint ended; will carry over.

**Comment by jilladams** [comment]
I am voting to close this issue. It's running, live, and we have verified how it alarms. If watch officers come back with concerns, we can always follow up with additional changes. 

Randi, if you hate that, please feel free to reopen for tracking purposes on your side.
