### ISSUE TITLE
Document Current Process for Module Upgrades

### ISSUE THREAD

**Issue by gracekretschmer-metrostar** [department-of-veterans-affairs/va.gov-cms#19311]
## User Story or Problem Statement
As a member of the CMS team, I need to understand what is needed to maintain the module upgrades in CMS. 

## Description or Additional Context 
Right now, Edmund is monitoring dependabot and identifying which modules need a developer to upgrade, which is creating a bottleneck, so we want to be more transparent about that process, so that we can have more CMS members involved to help and support and understand where we can improve and automate the process. 

## Steps for Implementation
- Meet with Edmund to understand his process for identifying which modules need to be upgraded by a developer instead of a dependabot.
- Identify what information is needed in the tickets for module upgrades completed by developers.
- Document findings in a page in Confluence. 

## Acceptance Criteria
- [ ] A documented understanding of the current process for identifying where a module upgrade needs to be manually updated instead of using dependabot.

**Comment by anantais** [comment]
Added file to the readme files that represents a list of current drush commands, where they can be found in the VA code and how to use them. https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/READMES/custom-drush-commands.md

**Comment by anantais** [comment]
Adding page in Confluence for my findings on Module upgrades: https://vfs.atlassian.net/wiki/spaces/PCMS/pages/3516432407/Module+Upgrades+-+new+process+and+brainstorming
