### ISSUE TITLE
Move all patches from Drupal.org to local repo

### ISSUE THREAD

**Issue by edmund-dunn** [department-of-veterans-affairs/va.gov-cms#19317]
## User Story or Problem Statement
We need to communicate to all product teams the change in workflows so that they are aware of where patches are placed an how to work with drupal.org.

## Description or Additional Context 
There is potential risk to patches hosted on drupal.org. Drupal.org is moving from a system of patches hosted on the site to merge requests through Drupals gitlab. To ensure continued, reliable delivery of all of the patches we use we need to host our patches locally as well as using drupal.org's system of MRs to contribute to Drupal and contrib modules and themes. 

## Steps for Implementation
- Place copies of all patches in the `/patches` directory
- Document the process of how to patch contrib code including links to relevant documentation on d.o. Make sure to include the node ID. 

## Acceptance Criteria
- [ ] all patches in the patches section of the `composer.json` are no place in the `/patches` folder and the location is updated

**Comment by gracekretschmer-metrostar** [comment]
Jake: I will take to Tim and Edmund about organization of files.

**Comment by gracekretschmer-metrostar** [comment]
Possible follow up ticket: fine opportunities where we could find opportunities to better uses of existing patches.
