### ISSUE TITLE
[Homepage email signup] [UX] Design an error state for the email signup form

### ISSUE THREAD

**Issue by randimays** [department-of-veterans-affairs/va.gov-cms#19314]
## Description
On VA.gov at the bottom of the homepage, there is a section titled "Sign up to get the latest VA updates" with an input for an email address.

There is currently no error handling in place for this form. If the form fails to reach the GovDelivery service, the user will be directed to a browser error page (404). We need to determine how we want the user to be notified that their attempt to sign up for VA email updates failed, and give them steps on what action they can take, if any.

Secondly, we need to consider form validation for the email address input. Do we want to: 1) add messaging for invalid emails 2) validate email address length (min or max) 3) strip out invalid characters, etc.? What are the DST patterns for this that we may want to adopt?

The solutions should consider desktop and mobile views.

<img width="700" alt="Screenshot 2024-09-24 at 1 36 21 PM" src="https://github.com/user-attachments/assets/33eaf47f-7b22-4a74-8661-b37f799669d2">

<img width="400" alt="Screenshot 2024-09-24 at 1 36 21 PM" src="https://github.com/user-attachments/assets/204bd77f-2121-4579-944c-bf33bed8c3a6">

### User story

**AS A** Veteran who is entering my email address in the 'Sign up to get the latest VA updates' form
**I WANT** to be presented with validation errors/information if I don't enter a properly formed email address
**AND** I want to be informed, as well as given next steps (if possible) if there was a system or other error that prevented my accurate email address from sending correctly
**SO THAT** I have a good experience when signing up for updates and know what to do and if there are issues.

## Artifacts produced:
- [ ] [Figma design](https://www.figma.com/design/60PPoOSpKiXwmNHT01C09J/Home-Page-Updates?node-id=38-3849)

## Acceptance criteria

- [ ] System error handling provided
  - [ ] including next steps, if possible
- [ ] Incorrect email format input error handling provided

**Comment by FranECross** [comment]
@davidmpickett @thejordanwood UX ticket that shook out from one of the silent failure tickets. Edited and moving to Next Refinement. cc @jilladams

**Comment by jilladams** [comment]
@randimays this may be going unsaid, but: from what you see about how we implemented the code for this signup, we have flexibility in being able to display error messages / add validation, etc? Basically: we need to know the tech feasibility of the form, within which UX can work.

**Comment by randimays** [comment]
@jilladams The form is completely contained within content-build. It would make the most sense to me to create a React widget out of this form instead. It's not impossible for us to get more robust success/failure handling of that POST call and input validation in content-build. But I think if things become JS-heavy in content-build, we should move the code to vets-website as React widgets if possible to keep content-build **very simply** static. @dsasser thoughts?

I think we should lead with desired UX and follow with an engineering implementation either way, though.

**Comment by FranECross** [comment]
@davidmpickett Is it possible to get this estimated and slotted for Sprint 14? Apologies for not having you in the mini-refinement today.

**Comment by davidmpickett** [comment]
Seems like a 3 to me. @thejordanwood feel free to disagree

**Comment by davidmpickett** [comment]
@randimays While [poking around](https://design.va.gov/patterns/ask-users-for/email-address) the Design System, I found this [bit of code in Vets Website](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/platform/forms-system/src/js/web-component-patterns/emailPattern.jsx) that handles email validation.

I also found [this pattern](https://www.figma.com/design/4A3O3mVx4xDAKfHE7fPF1U/VADS-Templates%2C-Patterns%2C-and-Forms?node-id=2987-41777&node-type=frame&t=ioNPxXw0VyFzJ6DY-0) in the Figma template library.

Given that this design is just about addressing a single field on the homepage, I don't know that me copy and pasting this into a new Figma file would add much value. I reviewed the error messages in the code and I think those sufficiently cover the use cases. 

Can you take a look and see what you think?

cc @FranECross

**Comment by randimays** [comment]
@davidmpickett I agree that we should use the existing VADS patterns for input validation. Can you confirm that the error messages in that Figma are the desired messages?

The email form right now is only in content-build, so we don't have access to any of the vets-website utilities. This will help inform the eventual engineering implementation. Most likely we will end up making a React widget out of this form anyway since it will require significant JS to properly handle the system error scenarios.

**Comment by davidmpickett** [comment]
First pass at design shared with @randimays @FranECross @thejordanwood via Slack

- https://www.figma.com/design/60PPoOSpKiXwmNHT01C09J/Home-Page-Updates?node-id=38-3849
- https://dsva.slack.com/archives/C52CL1PKQ/p1728933252412899

**Comment by davidmpickett** [comment]
**End of sprint update**
Revised based on feedback from Randi and Jordan. Complete pending sign off from @FranECross

**Comment by FranECross** [comment]
@randimays @jilladams I don't believe we have an FE ticket created to implement the outcome of this UX ticket, is that true? I can get one created if not (I don't see one when scanning the Backlog). Thanks!

**Comment by jilladams** [comment]
@FranECross no, I don't see a FE implementation ticket in the epic.

**Comment by randimays** [comment]
@FranECross @jilladams I just created a ticket here: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19516

I think from a technical perspective it's pretty solid, but @FranECross it does need your input in the analytics section, and then we just need to iron out testing details.

**Comment by FranECross** [comment]
@randimays Thanks! I'll take a look at the analytics section and can also take a run at the testing details.

**Comment by FranECross** [comment]
Closing as done.
