### ISSUE TITLE
Process CMS satisfaction survey for Q3 2020

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#1932]
AC
Results of CMS survey 
- [x] have been presented to the team at sprint 18 demo on Nov 6
- [x] have been added to design artifacts index
- [ ] ~we have reviewed and defined Q4 O2 KR1~ - will be defined in #3386

**Comment by nickbloom** [comment]
(10/5) This has been set back because of low response rate -- have been tracking it since it was assigned, Clarence and/or Kev followed up at mid-sprint check-in

**Comment by oksana-c** [comment]
Q3 deck - https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/cms/research/user-survey-results
