### ISSUE TITLE
Notification to user that system is not working when CC Providers selected and services do not load

### ISSUE THREAD

**Issue by eselkin** [department-of-veterans-affairs/va.gov-cms#19332]
## User Story or Problem Statement
Currently, as a user, if I select "Community providers (in VA's network)" and the `/facilities_api/v2/ccp/services` request does not succeed, I am not notified but I cannot enter anything to proceed (because the combobox doesn't work).

## Description or Additional Context 
The combobox loads options to suggest options when you type something, but if the suggestions do not load (with the codes for use in the subsequent requests), then the system will not be able to search.

This will prevent service search, which prevents submitting search terms, and a red box appears around the Service field, stating you must select an option. Except you can't. Broken UX for end users.

We cannot fix the combobox. But we need to alert the user that the system won't work. 

This does not apply to Community Care Pharmacies, only Providers.

## Error messaging
Can be put below, could be a banner. We can display based on an API error response, in whatever fashion.

## Artifacts produced
- [ ] [Figma design](https://www.figma.com/design/GvNVeG9GAXZaBpny7vNxZP/Facility-Locator?node-id=872-20048&t=clExp1TOlcze2Utl-1)

## Acceptance Criteria
- [ ] A design is provided to address error messaging in a scenario where Services are not available for CC providers

**Comment by jilladams** [comment]
@Agile6MSkinner FYI one we'll need to look at pulling into SPrint 14.

**Comment by davidmpickett** [comment]
First attempt
https://www.figma.com/design/GvNVeG9GAXZaBpny7vNxZP/Facility-Locator?node-id=872-20048&t=clExp1TOlcze2Utl-1

**Comment by davidmpickett** [comment]
Pinged @thejordanwood @eselkin and @Agile6MSkinner in Slack for feedback: https://dsva.slack.com/archives/C0FQSS30V/p1727998539632139

**Comment by jilladams** [comment]
I created https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19427 as the follow on to this ticket. Please add designs there when this ticket closes.

**Comment by davidmpickett** [comment]
Version 2 shared on Slack

**Comment by davidmpickett** [comment]
@Agile6MSkinner @thejordanwood @eselkin [Version 3 design in figma](https://www.figma.com/design/GvNVeG9GAXZaBpny7vNxZP/Facility-Locator?node-id=872-22257&t=f0p5ul3r1wcCH1pY-1)

**Updates to design**
- Crossed out the non-progressive disclosure version to reflect conversation in UX sync today that it makes sense to implement this error message with/after progressive disclosure
- Revised the error messaging to be more specific
- Added a loading indicator

**Next steps**
- I updated the [follow up implementation ticket](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19427) to move out of ZSF and link to these designs (moved it into Facility Location tech debt epic)
- I also noted there that it will also be blocked by the work @thejordanwood has to finalize designs for layout & progressive disclosure in #19484
- Any progressive disclosure-specific design tweaks (including loading indicator) should likely happen in Jordan's follow up ticket
- @Agile6MSkinner if you are good with the revised wording and this path forward, this ticket can be closed

**Comment by Agile6MSkinner** [comment]
I am good with the revised wording and this path forward. Closing.
