### ISSUE TITLE
Screen-size breakpoint name changes for Facilities

### ISSUE THREAD

**Issue by eselkin** [department-of-veterans-affairs/va.gov-cms#19339]
## User Story or Problem Statement
After update of DST screen size breakpoint name changes, recently old names are no longer respected.

## Acceptance Criteria
- [x] Change all Facilities pages from `large-screen:` to `desktop-lg:` 
- [x] Change all Facilities pages from `small-desktop-screen:` to `desktop:` 
- [x] Change all Facilities pages from `small-screen:` to `mobile-lg:` 
- [x] Change all Facilities pages from `xsmall-screen:` to `mobile:` 
- [ ] Requires design review
- [ ] Requires accessibility review

**Comment by jilladams** [comment]
@eselkin thanks for making this ticket last week. I see 2 merged PRs - can you help note what got covered from the ACs here, vs. what might be left to do, if anything?  (And maybe @chriskim2311 too?)

I see the following checks on the Facilities PRs: 
*  Vet Center pages render as before the update (i.e. images on right side of address block)
* VAMC pages render as before the update (ditto)

And I know there was a PR for CLPs separately under #19348 

But not sure if we got through all our templates for things like VBA, Events, press Releases, etc etc etc where images might appear and be affected. 

cc @Agile6MSkinner  @FranECross

**Comment by eselkin** [comment]
All screen sizes other than medium where changed to the new USWDS names except with respect to the ones preceding a grid or col class name. Those were kept because they are not changed yet in the DST updates.

**Comment by eselkin** [comment]
That is. All inside any Facilities product and on the home page.

**Comment by eselkin** [comment]
There may be some in facility locator that need an update still. Just saw something and will check.

**Comment by jilladams** [comment]
Noting: we left this ticket open, in order to track follow up after the final DST change to breakpoints. 
I'm not sure if there was a specific change we were on the lookout for, so: 

DST merged PRs that mention breakpoints: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/pulls?q=is%3Apr+breakpoint+is%3Aclosed

DST issues that mention breakpoints (open & closed: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues?q=is%3Aissue%20breakpoints

**Comment by eselkin** [comment]
The DST PRs about breakpoints have been more often mentioning CSS swap or CSS naming something, rather than overtly saying breakpoints in the titles. There's one open for FL that I was waiting on the RI for.

**Comment by eselkin** [comment]
The changes they are making are not always DS changes but changes in vets-website or C-B

**Comment by jilladams** [comment]
Ah ok - so am gonna continue reporting htis as open to track changes. I'll ping DST to see where they are in terms of completion.
Thanks!
