### ISSUE TITLE
[Campaign Landing Pages] Images are missing from the CLPs

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-cms#19348]
## Description

Michelle / Ian Sears reported images missing from CLPs and banners. Jamie Gibbs indicates that 

The small-desktop-screen name which should be desktop
vads-u-display--none small-desktop-screen:vads-u-display--block

This ticket is only to do the above. I'll coordinate any other work needed to accommodate all breakpoint names needing to be migrated to USWDS names. DST has completed most of them at this point but it looks like we have missed some. Here is the name mapping table: https://design.va.gov/foundation/breakpoints#names-and-values

### User story

**AS A** Veteran et al
**I WANT** to see the appropriate images on CLPs and banners
**SO THAT** the full impact of the content is received.

## Acceptance criteria

- [ ] Images are displaying appropriately on CLPs
- [ ] Images are displaying appropriately on banners

**Comment by ian-sears** [comment]
Please alert the VA CMS help desk @department-of-veterans-affairs/platform-cms-helpdesk once this is resolved, to enable us to confirm with the reporting Editor that it is resolved for them. Editor is Justin Warren with VHA Digital Media.

**Comment by jilladams** [comment]
@ian-sears This fix went out on Friday, and images are back on CLPs.

**Comment by jilladams** [comment]
e.g. https://www.va.gov/initiatives/va-health-connect/

Closing.
