### ISSUE TITLE
[Discharge Upgrade Wizard] Add support/contact information to DUW beginning & results screens

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-cms#19347]
## Status
**[2024-10-10] [Fran]** This will remain blocked until after research has concluded so as not to disrupt the sessions.

## Description
In reviewing the Veteran Support/Contact Center guidance document to prep for launch, I discovered that all applications on the Veteran-facing Services Platform must include a phone number Veterans can call to ask questions about the application's functionality.

Laura F has shared that there is a component we can use for this. See [here](https://design.va.gov/storybook/?path=/docs/components-va-need-help--docs) in Storybook, and screenshot below.

![Image](https://github.com/user-attachments/assets/f5d4ec5d-e19c-4bc2-b8a4-47ae8c8ef09c)

- The first contact component will display on the first DUW (introduction) screen (URL /discharge-upgrade-instructions/introduction), above the gray line that is above the Feedback button.

![Image](https://github.com/user-attachments/assets/edb1a68c-b328-424d-9beb-a288ec0295e3)

The second contact component will display on the DUW results screen(s) (URL /discharge-upgrade-instructions/results), above the gray line that is above the Feedback button.

![Image](https://github.com/user-attachments/assets/9f3da422-02e3-4d34-8f19-368d172d61b7)

### User story

**AS A** Veteran or their designate using the Discharge Upgrade Wizard
**I WANT** a number I can call if I run into issues completing the wizard
**SO THAT** I'm not frustrated by my experience and can receive the support needed when needed.

## Acceptance criteria

- [ ] **BLOCKED UNTIL AFTER RESEARCH SESSIONS ARE CONCLUDED**
- [ ] The contact verbiage and number (utilizing the existing component) is on the DUW introduction screen: URL /discharge-upgrade-instructions/introduction
- [ ] The contact verbiage and number (utilizing the existing component) is on the DUW results screen, URL /discharge-upgrade-instructions/results
- [ ] Clicking the phone number or TTY: 711 open the expected modal/app, based on the component's design/instructions.
- [x] Accessibility review
- [x] Product Manager review and sign off

**Comment by chriskim2311** [comment]
@FranECross This has made it to staging and is ready for your review thanks!

**Comment by FranECross** [comment]
@chriskim2311 This looks great! Has Laura done her accessibility review? (the checkbox in the AC isn't checked). If so, this is okay to close.

**Comment by chriskim2311** [comment]
@FranECross Yes during the PR review she gave her approval. This should be good to close!

**Comment by FranECross** [comment]
Closing as completed. Thanks!
