### ISSUE TITLE
 [Zero Silent Failures - Search] Create a user data flow diagram for search

### ISSUE THREAD

**Issue by SnowboardTechie** [department-of-veterans-affairs/va.gov-cms#19353]
## User Story or Problem Statement
Golbal search does not have a user data flow diagram

## Description or Additional Context 
[Related ZFS ticket](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19244)

## Steps for Implementation
Folow instructions [here](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/platform/practices/zero-silent-failures/how-to-create-a-user-data-flow-diagram.md)

## Acceptance Criteria
- [x] User data flow diagram created and is added to Search product documentation

**Comment by SnowboardTechie** [comment]
User data flow diagram for search [here](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1728324454952/c3cbd6203c07712994f5c5e4f9d6e81bfc2432e4?sender=u7abe3a97ceb5740cb6cf6602). Please note, objects marked in the color orange are expected to be removed with the completion of #19278

**Comment by jilladams** [comment]
Linked to the flow in the Search readme and in the engineering readme: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/on-site-search/engineering/readme.md
