### ISSUE TITLE
Facility Locator tech debt removal: old api keys and related code

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#19367]
## Description or Additional Context
Platform identified vets-api keys without an expiration (TTL value) & requested explanation / mitigation: https://dsva.slack.com/archives/C0FQSS30V/p1727206911544229.  No timeline provided or requested.

3 if those keys belong to Facilities, from the olden days of the Facility Locator. 
Patrick Vinograd identified that they are no longer in use, and could be removed entirely, along with a giant portion of old code related to ArcGIS, etc. Patrick provided a PR for this removal: 
https://github.com/department-of-veterans-affairs/vets-api/pull/18610

However, vets-api wants PRs to be smaller than 500 lines of afffected code, and this PR has 124,900 lines, most of them removed. 
Patrick doesn't have time to deal with it, since he put up this PR as a nice guy move and this isn't his project anymore.
Platform has asked us to break the PR up into separate PRs for each directory and the correlating spec directory. 

To finish this out, we'll need to do that. 

## Acceptance Criteria
- [ ] https://github.com/department-of-veterans-affairs/vets-api/pull/18610 is replaced by multiple PRs broken up by directory and spec directory
- [ ] Rachal Cassity is tagged for PR review from platform team

**Comment by jilladams** [comment]
Notified Kshitiz here; https://dsva.slack.com/archives/CE4304QPK/p1727811047815139?thread_ts=1727205902.397569&cid=CE4304QPK

**Comment by eselkin** [comment]
I'm giving it a 2 because I know a lot less than Patrick. However, the spec probably has to be removed first so it doesn't go trying to test components that aren't there. So it may have to happen in stages of merging.

**Comment by jilladams** [comment]
Closing as a no op - Platform merged the giant PR: https://dsva.slack.com/archives/C0FQSS30V/p1727968024413659?thread_ts=1727206911.544229&cid=C0FQSS30V
