### ISSUE TITLE
Defect 1 - Medium - Programmatic focus not moving

### ISSUE THREAD

**Issue by srancour** [department-of-veterans-affairs/va.gov-cms#19368]
## Description or Additional Context
9/16/2024 The three same page links "Before you Start" "How to do it" and "Alternate method" move the view area to those sections but do not move the programmatic focus. A Screen reader user will select the link, but focus will remain on the link and not move to the content.

## Example
The navigation "On this page" links in the [How to find content to edit KB article](https://prod.cms.va.gov/help/cms-basics/how-to-find-content-to-edit) don't set focus on the area they link to. ![Screenshot of the title and the "On this page" section of the example page with the "Before you start" link selected](https://github.com/user-attachments/assets/4dfc60fc-4ed2-4853-ab78-322a2418d050)

### Code snippet
Skip link `<p><strong>↓&nbsp;</strong><a href="#before-you-start">Before you start</a></p>`
Linked Heading `<h2 id="before-you-start"><strong>Before you start</strong></h2>`

### Steps to reproduce
Navigate: Home-> Knowledge Base -> How to Find Content to Edit
Press on "Before you start" link and then tab to the next element. You will visually see the screen move to the correct heading, but the focus won't move and on tab it will tab to the next link in the list.

## Recommended resolution
When linking to none interactive elements on the page `tab-index= "-1"` needs to be added to the none interactive element, like a heading, for the focus to move properly. This needs to be checked across all KB articles. 

We also need to look at why, when pressing the link, it sets the url to `#undefined` no matter what the link is actually set as.

## Defect Criterion
[WCAG 5.2.4 - Only Accessibility-Supported Ways of Using Technologies](https://www.w3.org/TR/WCAG21/#cc4) - Only accessibility-supported ways of using technologies are relied upon to satisfy the success criteria. Any information or functionality that is provided in a way that is not accessibility supported is also available in a way that is accessibility supported.

### Users affected
- Keyboard only
- Screen reader

## Teams that this affects:
- [x] CMS Team
- [x] sitewide

**Comment by srancour** [comment]
This also seems to have to be related with work that the last team had been doing as well in #12145.

**Comment by anantais** [comment]
Confirmed with Steve that the fix for the ticket - https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19375 - also fixes this ticket. Closing.
