### ISSUE TITLE
Exempting facilities that are not in VAST from automated process.

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#1940]
Health care facilities that are not in the Facility API source (VAST) will need some special handling in our automated processes.
- Are these to be treated like VetCenter CAPS where we are pushing everything about them to Lighthouse FacAPI?
   - [ ] Yes:  Special push needs to be added on node publish. 
   - [x] No: 
     - [ ] Exempt them from status push and url/system push, since there is no facility in the FacAPI to push to. ([See this thread](https://dsva.slack.com/archives/C02BTJTDFTN/p1658169770215249?thread_ts=1658165120.862879&cid=C02BTJTDFTN))
     - [ ] Exempt facility health services from push
- [ ]  Exempt these nodes from the nightly facility flagging scan as any changes to them would not come from upstream. (possibly exempt them by tricare section if we use that method, or exempt them by the field_faclility_locator id prefix that should be unique)

**Comment by JayDarnell** [comment]
This work was handled in #9943
