### ISSUE TITLE
URL Change for: Fort Scott VA Clinic TO Iola VA Clinic - Awaiting CSV

### ISSUE THREAD

**Issue by TroyCMSSupport** [department-of-veterans-affairs/va.gov-cms#19405]
Parent ticket: #[GH ticket](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19404)

### Implementation date
When does this request need to be live:
ASAP 

### Instructions for URL redirect
(Note: This issue will be used from initial request through implementation to ensure all individuals working on this are notified of status updates.  Please do not create multiple issues to track different steps.)
- [x] Notify VA stakeholders as appropriate.
- [x] Link the related facility closure / rename issue.
- [x] Create a URL redirect in the [vsp-platform-revproxy](https://github.com/department-of-veterans-affairs/vsp-platform-revproxy) repo in `template-rendering/revproxy-vagov/vars/redirects.yml`
- [x] Add the "Awaiting redirect" flag to the facility node with a revision log message that includes a link to this ticket, preserving the node's current moderation state.
- [x] Redirects deploy daily except Friday at 10am ET, or by requesting OOB deploy (of the revproxy job to prod) in #vfs-platform-support. After deploy, validate that the URL redirect is deployed. (Note: In the event of a facility closure or a name change,  validate that this occurs before making the Lighthouse csv changes.)
- [x] Update this ticket with a comment that the redirect has been deployed.
- [x] Remove the "Awaiting redirect" flag on the facility node with a revision log message that includes a link to this ticket, preserving the node's current moderation state.
- [x] Notify helpdesk via comment on ticket or Slack message in #cms-support that changes are ready for review.

#### URL Redirect
| Current URL  |  Redirect Destination or New URL |
| ---  |  --- |
| https://www.va.gov/eastern-kansas-health-care/locations/fort-scott-va-clinic/ | https://www.va.gov/eastern-kansas-health-care/locations/iola-va-clinic/ |

### 1. Canonical URL change

**Note: Canonical URL changes do not block the completion of the parent ticket. Once the URL redirect above has been deployed, the value to the Veteran is delivered. This ticket should be kept open until the URL change is verified, except in the case of a removal (as described below).**

### Instructions for canonical URL change
- [x] Verify that the new URL for the facility is published and accessible on VA.gov.
- [x] Contact Lighthouse via Slack at #cms-lighthouse channel that this facility requires a canonical link in the following format (replacing the placeholder data with the actual API Id and VA.gov URL):
  - `vha_691GM,https://www.va.gov/greater-los-angeles-health-care/locations/oxnard-va-clinic/`
- [x] Add the "Awaiting CSV" flag to the facility node with a revision log message that includes a link to this ticket.
- [x] Let Help desk know this has been done, if not done by Help desk.

#### Wait (days or weeks, potentially)
- [x] After the canonical link has been added to the websites.csv and you have confirmation from Lighthouse that the CSV has been deployed, validate that the change has deployed by checking that the Facility Locator has been updated with the new url.
- [x] Update this ticket with a comment that the CSV change has been deployed.

#### URL change example (update with actual ID and URL)
| Facility API ID  |  Full VA.gov URL |
| ---  |  --- |
| vha_589GV | https://www.va.gov/eastern-kansas-health-care/locations/iola-va-clinic/ |

**Comment by ian-sears** [comment]
@omahane Reminder that this redirect for iola
[FROM] https://www.va.gov/eastern-kansas-health-care/locations/fort-scott-va-clinic/
[TO] https://www.va.gov/eastern-kansas-health-care/locations/iola-va-clinic/
would get quite a few of the Flagged Facilities resolved, if we could get this done soon.

**Comment by omahane** [comment]
The redirect has been merged and should be deployed Monday (uncertain as this is Indigenous People's Day) or Tuesday.

**Comment by TroyCMSSupport** [comment]
@omahane @ian-sears @jilladams  -- Redirect is successful -- Now awaiting CSV (already submitted in Slack -- https://dsva.slack.com/archives/C02BTJTDFTN/p1729031838187109)

**Comment by ian-sears** [comment]
CSV has been added and works. Deployed.
Facility Locator has been updated with this URL.
Closing this one aqs resolved/Done.
@department-of-veterans-affairs/platform-cms-helpdesk

**Comment by TroyCMSSupport** [comment]
@omahane @ian-sears @jilladams - CSV has been deployed and verified - Closing this issue
