### ISSUE TITLE
[AP] In progress event is not at the top on Event Detail pages

### ISSUE THREAD

**Issue by randimays** [department-of-veterans-affairs/va.gov-cms#19411]
## Description

Slack thread for context: https://dsva.slack.com/archives/C07B86KV4P4/p1727981916287789

Events in progress should appear at the top of Event Detail pages until the event time has passed. This should apply for both:
- Events with recurrences
- Events without recurrences

Example AP URL: https://dev.va.gov/detroit-health-care/events/68589/
Example Prod URL: https://va.gov/detroit-health-care/events/68589/

~Why this is happening: https://dsva.slack.com/archives/C52CL1PKQ/p1660681413087369?thread_ts=1660266788.151129&cid=C52CL1PKQ~
~So, the decision we made in Next Build was, pull all the events for an event listing page, past and future, and put them in the page as one bucket. However, and this is key, when the user views the page, it looks at the timing of the user's browser, and it does that division of future and past on the fly.~
~It is possible there is an issue with the logic there, definitely. But we were looking at a situation where, in a hypothetical future state, an event listing might not be published for several days, because there's no reason to do it. So what is past and what is future would change. We wanted that to be dynamic and tied to the user's action, not for that decision to be made at time of page creation.~

**Note**: Troubleshooting this ticket requires finding an event that is currently in progress. The event above may or may not be currently in progress when this ticket is worked.

## Testing & QA
- For an event that has recurrences, the event currently happening should be at the top of the event detail page until the event has ended for the day, and **also** in the "other times" accordion at the bottom of the page.
- For an event that does not have recurrences, the event currently happening should be at the top of the event detail page until the event has ended for the day.
- The testing is outlined on the PR: https://github.com/department-of-veterans-affairs/next-build/pull/795. Testing is all on Tugboat. (from Tim C in a comment below).

### Roles / assignments
_After functional testing, code review, accessibility review, and design review can happen in parallel._
* **Functional testing:** AP team **and** @randimays 
* **Code review:** AP team **or** @randimays 
* **Product acceptance:** @FranECross 

## Acceptance criteria
- [x] Events in progress appear at the top of the Event Detail page until event time is complete (either end of day or end of event time, pending technical lift)
- [x] Events with recurrences have **all** recurrences in the "other times" accordion at the bottom of the page
- [x] Events without recurrences still show the correct time as expected

**Comment by randimays** [comment]
Marked as Ready because this is likely a launch-blocking defect, but still has a `needs refining` label because I'm not sure how much of the issue template to fill out for the purposes of this ticket.

**Comment by jilladams** [comment]
Determined this is launch blocking for Event LIstings, but not for Event Detail Pages: 
https://dsva.slack.com/archives/C07B86KV4P4/p1728318556408759?thread_ts=1728062069.765979&cid=C07B86KV4P4
> * Once we confirm no other launch blocking issues: let's ship Event Detail Pages.
> * Let's hold Event Listings. Since AP won't be officially staffed by CMS team and Sitewide will own the events logic long term: Sitewide will file a bug, we can own working out the logic fix / work with Tim to understand what happened before / what should happen next.

So: Pulling this out of Sprint 14, so we can refine. This will require ramp up for someone to get familiar with the decisions in AP logic, in order to revise them, and that should factor into points.

**Comment by randimays** [comment]
@ttran-Therisa I updated the ticket body here to note that this ticket is specifically for event detail pages, not event listings (search results). For both events with and without recurrences, the **currently happening** event should be at the top of the page.

This defect has been discussed extensively in Slack:
- https://dsva.slack.com/archives/C07B86KV4P4/p1728062069765979
- https://dsva.slack.com/archives/C07B86KV4P4/p1727981916287789

but if there's any confusion about functionality / expectation please ping; happy to help.

**Comment by randimays** [comment]
@ttran-Therisa Also wanted to point out that I had reported in the QA spreadsheet that in the "other times" accordion at the bottom of the page in AP, there are only 5 events showing (before the Show all button is clicked) when in prod there are 6 events showing. I think this is simply a `<` versus `<=` in the logic, but I just wanted to flag there here in case it has deeper ramifications.

Line 46 -> https://docs.google.com/spreadsheets/d/1czCFV4d4rQXcxoxVYoWtVyfSNGTDChhYchLLsxmp3OY/edit?gid=675750633#gid=675750633

**Comment by FranECross** [comment]
@jilladams Should I remove the Public Websites tag since we won't be working on this ticket? Thanks.

**Comment by jilladams** [comment]
IMO: let's leave it on for a bit in case Tim gets slammed and needs to hand it back.

**Comment by jilladams** [comment]
Great - just let us know where the environment is for testing -- is it on dev.va.gov?

**Comment by gracekretschmer-metrostar** [comment]
As on 10/23 Randi, has done some testing, but Grace will confirm timelines during today's sitewide sync.

**Comment by timcosgrove** [comment]
> Great - just let us know where the environment is for testing -- is it on dev.va.gov?

Apologies for not responding sooner. The testing is outlined on the PR: https://github.com/department-of-veterans-affairs/next-build/pull/795

Testing is all on Tugboat.
