### ISSUE TITLE
Create rate limiting monitor for Search

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#19414]
**[2024-10-04]** Blocked on confirming our rate limit with Search.gov and completing cutover to the new API endpoint

## Description 
Today when we moved to the new search API endpoint (#18736) , we hit a rate limit, but we didn't get a forewarning. We learned it when the VA.gov - Search Browser Test alarmed, showing that Search calls in the browser were failing. 

We don't have an alarm that explicitly goes off related to Search rate limiting and we probably should. 

We do this for VA Forms: https://vagov.ddog-gov.com/monitors/160407, based on the rate limit for LH API user key. The monitor counts calls to the API every minute, warning at 400, alarming at 450. 

We already know we have weird rate limiting problems with the search_click_tracking endpoint (#14819), and that doesn't appear to affect traffic to the actual search endpoint / get it rate limited. Maybe our rate limits are per endpoint? Or if they're per API key, we are using different keys per endpoint? 

Either way, there's some kind of current firewall between v0/search and search_click_tracking already, so once Search.gov verifies our rate limits for v0/search to the new gsa endpoint, we could set up a monitor similar to the Forms one.

## ACs

- [ ] A Datadog alarm is configured to warn when traffic to v0/search approaches our Search.gov rate limit
- [ ] Monitor warns / alarms to #public-websites-dd-search
- [ ] Search monitoring docs are updated to describe the new alarm: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/on-site-search/engineering/monitoring.md

**Comment by jilladams** [comment]
Pulling this in, based on conversation in #18736 that we can create this monitor now for use as we roll out the new endpoint. We still don't know what our rate limits are -- if that's a hard blocker, holler.

**Comment by SnowboardTechie** [comment]
@jilladams I have gathered all the required info to put this monitor together but realized I do not currently have Datadog privileges for creating monitors and have submitted a yourit request (REQ32893024) per the [platform documentation](https://depo-platform-documentation.scrollhelp.site/developer-docs/get-access-to-datadog#GetAccesstoDatadog-Step2:GainAccesstoDatadog) to have my permissions elevated.

**Comment by jilladams** [comment]
Asked in #pubilc-datadog about access, since I can't create new anymore either: https://dsva.slack.com/archives/C01G6J7UGGH/p1728671007158129

Both STeve Albers and Adrian Rollett who would normally help with this are OOO currently, so might be a minute before we figure out who else can help.

**Comment by jilladams** [comment]
Went ahead and made a new Platform support ticket, too: https://dsva.slack.com/archives/CBU0KDSB1/p1729033614050009

**Comment by SnowboardTechie** [comment]
Monitor for 429s has been added [here](https://vagov.ddog-gov.com/monitors/287522), additionally I included to a composite error [here](https://vagov.ddog-gov.com/monitors/214590)

**Comment by jilladams** [comment]
Added to [Search monitoring docs](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/on-site-search/engineering/monitoring.md#searchgov---vets-api-error-due-to-429-code-returned-from-searchgov-rate-limiting), and added mitigation steps to the monitor alert message + docs: 

> Mitigation:
> * Enable the Search.gov maintenance Flipper, which will warn Veterans that search may fail: https://api.va.gov/flipper/features/search_gov_maintenance
> * Post a note to the #public-websites-dd-search channel so others know you're taking follow up steps
> * Email [search@gsa.gov](mailto:search@gsa.gov) immediately to request API rate limit increase, and cc PO / PM / DM

If Search.gov does tell us what our rate limit is, we should probably convert this from a log reading error (which we can only know about once we're over threshold) to a metrics monitor that tracks the # of our calls to Search.gov, so we can count & warn ourselves if we're approaching rate limit. 

But for now: closing!
