### ISSUE TITLE
Release the new EFS File Sync job to CMS

### ISSUE THREAD

**Issue by 7hunderbird** [department-of-veterans-affairs/va.gov-cms#19425]
## User Story or Problem Statement

In this ticket we released the new efs file sync job that runs at 2AM ET.

- It's been running on test.staging.cms.va.gov.
- It's not breaking permissions
- The files are up-to-date between EFS sources (test.prod.cms.va.gov and test.staging.cms.va.gov)

## Steps for Implementation

- Create a PR that updates cms app in the devops repo
- Change the vagov-staging deploy off the test branch of `disable-file-sync` it's been running on

## Acceptance Criteria

The order of the Acceptance Criteria is our release plan.

- [x] Get [PR](https://github.com/department-of-veterans-affairs/devops/pull/14741) reviewed and merged
- [x] Change the `vagov-staging` deploy to the `master` branch
- [x] Turn on the EFS job in the `cms` application
- [x] At the end of day releasing we'll run the EFS job
- [ ] Ensure the job ran on timer at 2AM ET

**Comment by gracekretschmer-metrostar** [comment]
For the roll out, @7hunderbird will run the script at the EOB, so that he can catch anything if there's any errors.

**Comment by 7hunderbird** [comment]
We are looking to release this next Wednesday 10/16.

**Comment by 7hunderbird** [comment]
This job failed on 10/16 http://jenkins.vfs.va.gov/job/cms/job/cms-daily-0200/23/ but I'm going to try again today after 5PM ET.

**Comment by 7hunderbird** [comment]
I ran this manually yesterday:

- http://jenkins.vfs.va.gov/job/cms/job/cms-daily-0200/24

And the automated run completed yesterday too:

- http://jenkins.vfs.va.gov/job/cms/job/cms-daily-0200/25

We are done!
