### ISSUE TITLE
Discovery and Governance: Facilities that don't have a facility ID because they are not in VAST

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#1942]
This issue should answer the questions:
- [x]  Is this bigger than just the 3-4 Lovell and Manilla facilities?  If no then just some specific overrides are needed.  If yes, then we might want to consider a separate content type to make it easier to separate out the governance and technical processes.
  -  **The answer is no**
- [x] Who needs to be able to change the data that is normally governed by VAST? (Should inform the ACs of #1943)
    - facility locator id:  **Same as current user roles for other VAMC facilities** This should be only editable by admin and once assigned, should not be edited.
    - facility address: **Same as current user roles for other VAMC facilities** 
    - facility hours: **Same as current user roles for other VAMC facilities** 
    - Title **Same as current user roles for other VAMC facilities** 
 - [x] Should this data and status info be pushed to Lighthouse?  Do they want it? 
   - On agenda for July 18th
 - [x] What should Facility ID be for these? 

## ACs
- [x] Related tickets are updated with the findings and decisions from this ticket.
   - [x] #1943 
   - [x] #1940
- [ ] Process governance decided upon here is documented in KB article(s).

**Comment by swirtSJW** [comment]
Moved AC " Process governance decided upon here is documented in KB article(s)." to here https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10027  so we can close this
