### ISSUE TITLE
Increase the Time and Volume to Retrieve IP Address

### ISSUE THREAD

**Issue by 7hunderbird** [department-of-veterans-affairs/va.gov-cms#19423]
## User Story or Problem Statement

There were to incidents in September where a failure to get an IP address from AWS broke the deploy for prod.cms.va.gov.

This required 

- [Sep 23, 2024](http://jenkins.vfs.va.gov/job/deploys/job/cms-vagov-prod/1127/)
- [Sep 27, 2024](http://jenkins.vfs.va.gov/job/deploys/job/cms-vagov-prod/1132/) 

## Description or Additional Context
Missing IP addresses have caused prod CMS to go offline during daily deploy and the platform team is constrained on how much they can increase the number of IP addresses for prod CMS. Therefore, we need to brainstorm ways we can better mitigate this situation in the future. We've communicated with the Platform team who have expressed that there are available IP addresses in the pool for our deploy to use.

## Steps for Implementation

Examine what the deploy process does when it doesn't get an IP address.  

- Perhaps we need to increase timeouts or retries. This would be the most straightforward change as a configuration change to give it more times to try and longer to wait
- Tim's recommendation: 10 minutes is 120 times at 5 seconds;
- Possibly it may require
  - Ansible upgrades
  - AWS SDK upgrades
- Add better error handling and perhaps a [manual rollback of the deploy process](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19424)

### Pull Request

- https://github.com/department-of-veterans-affairs/devops/pull/14759

## Acceptance Criteria
- [x] A change to the number of retries is merged

**Comment by gracekretschmer-metrostar** [comment]
Tim: Increase the amount of time for the IP address is requested and spread out the amount of times prod CMS tried to get the IP address.

**Comment by 7hunderbird** [comment]
We've merged https://github.com/department-of-veterans-affairs/devops/pull/14759 and that will give our IP address allocation step 10 minutes to find the IP.  🤞🏻
