### ISSUE TITLE
[SPIKE] Opportunities for Improving PDF Accessibility Training within CMS

### ISSUE THREAD

**Issue by gracekretschmer-metrostar** [department-of-veterans-affairs/va.gov-cms#19432]
## User Story or Problem Statement
As the accessibility lead, I need to gain a better understanding on what the current state of the PDF and accessibility in the CMS.

## Steps for Implementation
- Audit the state of PDFs within CMS to understand where there are accessibility problems.
- Audit the documentation around uploading PDFs within CMS to understand where there's gaps in accessibility guidance. 
- Provide recommendations on training improvements, based upon the findings. 

## Acceptance Criteria
- [x] We have a direction to update the PDF support content from the Accessibility standpoint.
- [x] All research and recommendations is documented in this ticket.

**Comment by srancour** [comment]
I need to touch base with Martha, Laura, and potentially the 508 office for where the work landed, but there was work happening around the Level Access (LA) scanning tool for pdfs to figure out what pdfs are compliant and how we could tie it back to the PDF Media tool in CMS in [#10117](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10117).

This work could help with pointing in the right direction for how the editors are currently doing for a baseline.

**Comment by gracekretschmer-metrostar** [comment]
Move forward into sprint 22.

**Comment by srancour** [comment]
Martha let me know that there are resources in the 508 office that we can add to the KB
"Remediation Support
The Section 508 office provides a one-on-one outreach opportunity called “Bring your own document ” where our document experts will show you how to remediate your document and let you try it. Use the following link to register: [Registration Link: Bring Your Own Document](https://va-hcm03.ns2cloud.com/learning/user/common/viewItemDetails.do?componentTypeID=VA&componentID=4479843&revisionDate=1536087300000#/BD9DCB5FC830EA25E10600000A083EEF)
Additionally, the Office of Operational Planning and Remediation Directorate (OPRD) can provide additional accessibility remediation guidance. You can access this information by requesting access to the OPRD SharePoint site at: https://dvagov.sharepoint.com/sites/oitoprd.
Please submit a request in Service Now (YOURIT) at [Ask the 508 Office - yourIT Service Portal (](https://yourit.va.gov/va?id=sc_cat_item&sys_id=1a408a7b1b501c50a25d0d08ec4bcbee)[va.gov](http://va.gov/)[)](https://gcc02.safelinks.protection.outlook.com/?url=https://yourit.va.gov/va?id%3Dsc_cat_item%26sys_id%3D1a408a7b1b501c50a25d0d08ec4bcbee%26cat_id%3Da7ff40ec1b352850a25d0d08ec4bcb6f%26catalog_id%3D1e105b9c1b062010a25d0d08ec4bcb03&data=05%7c01%7c%7c57adb888218c4eb7d47608db974c6cbb%7ce95f1b23abaf45ee821db7ab251ab3bf%7c0%7c0%7c638270126710234982%7cUnknown%7cTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7c3000%7c%7c%7c&sdata=Z5Q9Pixk9GaomlDxcgRx6cClm3giT0eaETHk44QvmlM%3D&reserved=0) with Remediation as the topic (currently the Ask 508 Office catalog form)."

**Comment by srancour** [comment]
The VA also has these two resources available for PDFs that came from the 508 office:
[Documentation and Support Services](https://digital.va.gov/section-508/checklists/documentation-and-support-services/)
[Section 508 ICT Testing Baseline Portfolio - ICT Testing Baseline for Electronic Documents](https://ictbaseline.access-board.gov/document-baselines/)
