### ISSUE TITLE
Update Drush Commands Documentation

### ISSUE THREAD

**Issue by gracekretschmer-metrostar** [department-of-veterans-affairs/va.gov-cms#19431]
## User Story or Problem Statement
As a developer on the CMS team, I need to understand how and where Drush commands are being used so that I can know the scope and lift when upgrading Drush. 

## Relevant Links
- https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/READMES/drush.md

## Steps for Implementation
- Include how the commands are being used
- If the drush command is not being used, flagged for opportunity to retire the command 

## Acceptance Criteria
- [ ] A documented understanding of all the drush commands, how they operate, and how critical the command is for CMS day-to-day operations.

**Comment by anantais** [comment]
Updated api commands. Closing.
