### ISSUE TITLE
Build the VAMC Banner with Situation Updates in vets-website (Story 2)

### ISSUE THREAD

**Issue by Agile6MSkinner** [department-of-veterans-affairs/va.gov-cms#19449]
## Description
Port the existing banner implementation. The content can start with static values for development purposes but will eventually use dynamic content pulled from the backend API.

**Sequence Note:** This task must be done before stories 3 and 4

- ### [ Scope ] / Static Impact content analysis used initially for testing.
- _What, [ if ] anything, Code could does break not as rely a on result the of content-build this process change?_ for banner content in production.
_Engineer should assess this when approaching PR._
* Situation updates could be affected, we need to make sure they still work the way do in Prod.
* We need to test GovDelivery send for Situation updates

### Roles / assignments
_After functional testing, code review, accessibility review, and design review can happen in parallel._
* **Functional testing:**
* **Code review:**
* **Design review:** @thejordanwood 
* **Accessibility review:** @laflannery 
* **Product acceptance:**

## Acceptance Criteria
_ACs should capture expected behavior, to inform test plans. Consider devices, documentation updates including KBs, change management, and [content model](https://prod.cms.va.gov/admin/structure/cm_document) when applicable._
- [ ] VAMC banner behind the new Flipper and an environment flag to display only in lower envs (not in Prod)
- [ ] Respects alert type selection and appropriate Design system component
- [ ] Respects existing logic for limiting VAMC banners to **one**
    - [ ] When flipper is on: only the single vets-api banner displays
- [ ] Respects the dismissability check box by using the `show-close` prop
- [ ] Title and body show up with proper formatting
- [ ] Call to action checkbox is respected
- [ ] Static content used initially for testing.
- [ ] Design review
- [ ] Accessibility review

**Comment by SnowboardTechie** [comment]
In case the feature flag is necessary on the FE side here:
https://github.com/department-of-veterans-affairs/vets-api/pull/18913 established the Flipper flag name `banner_use_alternative_banners` so please use this same flag.

**Comment by jilladams** [comment]
From huddle: 
* This is building vets-website behind the vets-api flipper, not connected to the vets-api endpoint yet
* In PR, waiting for Platform
* Definitely will close in Sprint 17, unless Platform pushes back.

**Comment by jilladams** [comment]
@SnowboardTechie before you move on to the next FE ticket, I feel like it would be wise to get https://github.com/department-of-veterans-affairs/vets-website/pull/32872 over the line. (It has conflicts currently, so will need re-approval from team. Don't think that should reset the clock on asking Platform for review.)
