### ISSUE TITLE
[CMS Support] - Drush Documentation Review/Update

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-cms#19442]
## Description
Per Grace KT in this [Slack convo](https://dsva.slack.com/archives/C03LFSPGV16/p1728330157055419), the CMS team is working on upgrading Drush (ticket [here](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18728)) and needs sitewide’s support. 

Specifically, we need support in understanding the expected outputs for the Drush commands listed [here](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18728#issuecomment-2377504843).

> These specific commands were the ones that I could not test:
> va_gov_migrate:flag-missing-facilities -- (alias va-gov-flag-missing-facilities) -- Flag any facilities that no longer exist in Facilty API.

This ticket is to account for and track the review they've requested of Daniel.

#### Expected behavior of the `va_gov_migrate:flag-missing-facilities`
For the following facility types, the facilities that have been removed from the Lighthouse Facilities API should be automatically archived:
  - nca_facility
  - vet_center_mobile_vet_center
  - vet_center_outstation

For other facility types, the node should have the "Removed from source" flag applied.

##### Facilities that get flagged
- Find a VAMC facility with a "Removed from source" flag
- Remove the flag
- In a terminal, run `drush va_gov_migrate:flag-missing-facilities`
- Check to see that the flag has been applied

##### Facilities that get flaggerd
- Find an NCA facility that has been archived
- Publish it
- In a terminal, run `drush va_gov_migrate:flag-missing-facilities`
- Check to see if the facility has been archived

### Scope / Impact analysis
_What, if anything, could break as a result of this change?_
_Engineer should assess this when approaching PR._

### Roles / assignments
_After functional testing, code review, accessibility review, and design review can happen in parallel._
* **Functional testing:** 
* **Code review:** 
* **Design review:** 
* **Document review:** Daniel Sasser
* **Accessibility review:** 
* **Product acceptance:** 

## Acceptance criteria
- [ ] Drush document is reviewed and updated as needed.
- [ ] Notify Grace KT when done
- [ ] Close ticket when finished.

**Comment by FranECross** [comment]
Find out where the list of commands are.

**Comment by omahane** [comment]
I have successfully tested the flagged facilities script in my local dev environment. I see no issue.
![Image](https://github.com/user-attachments/assets/3aa61f05-aa40-4ac4-8d47-e0f1b1e06bc4)

**Comment by jilladams** [comment]
The CMS PR was merged. Closing.
