### ISSUE TITLE
Create a Flipper for VAMC Banners (Story 1)

### ISSUE THREAD

**Issue by Agile6MSkinner** [department-of-veterans-affairs/va.gov-cms#19448]
## Description
Implement a Flipper to toggle the display of the VAMC banner with situation updates. This will allow controlled rollouts and enable testing in production environments before full deployment.

**Sequence Note:** This task must be completed first before any other tasks in this epic.

## Acceptance Criteria
- [ ] Implemented for `vets-api` and `vets-website` per https://depo-platform-documentation.scrollhelp.site/developer-docs/feature-toggles-guide
- [ ] Flipper created for the VAMC banners.

**Comment by dsasser** [comment]
Verified on prod:

![Image](https://github.com/user-attachments/assets/48589805-0b7b-436b-b5c2-70f88dab7e79)
