### ISSUE TITLE
Script to Fetch Banner Data and Update Database (Story 4)

### ISSUE THREAD

**Issue by Agile6MSkinner** [department-of-veterans-affairs/va.gov-cms#19451]
## Description
Create a production-ready script that communicates with GraphQL to fetch the alert banner data and update the pSQL database accordingly, ensuring real-time data retrieval for production use.

**Sequence Note:** This task must be done after story 2. Can be done in parallel with 3, but must be completed before Story 5.

## Testing & QA
- [x] Code Review
- [x] Automated testing

### Roles / assignments
* **Code review:** 

## Acceptance criteria
- [x] Script fetches VAMC banner alert data
- [x] Fetched data is updated in the database
- [x] Generates location path to be passed to vets-api. (Add path to #19453)

**Comment by SnowboardTechie** [comment]
https://github.com/department-of-veterans-affairs/content-build/blob/main/src/site/stages/build/drupal/graphql/bannerAlerts.graphql.js

**Comment by SnowboardTechie** [comment]
Was meant to be moved to ready 4 deploy but PR attachment auto-closed.

**Comment by SnowboardTechie** [comment]
This is all good to go https://api.va.gov/v0/banners?path=/boston-health-care
