### ISSUE TITLE
Create vets-api Endpoint and E2E connection for VAMC Banners (Story 6)

### ISSUE THREAD

**Issue by Agile6MSkinner** [department-of-veterans-affairs/va.gov-cms#19453]
## Description
Build a production vets-api endpoint that retrieves banner data from the database and serves it to the frontend banner component, ensuring that banner content is up-to-date and dynamically served in production environments on the specific location passed via path from #19451. 

**Sequence Note:** This task must be completed last before E2E testing in #19465 

## Testing & QA
- Automated Testing

### Roles / assignments
_After functional testing, code review, accessibility review, and design review can happen in parallel._
* **Functional testing:** 
* **Code review:** 
* **Design review:** 
* **Accessibility review:** 
* **Product acceptance:** 

## Acceptance criteria
_ACs should capture expected behavior, to inform test plans. Consider devices, documentation updates including KBs, change management, and [content model](https://prod.cms.va.gov/admin/structure/cm_document) when applicable._

- [ ] vets-api endpoint reads production data from the database.
- [ ] Data is correctly provided to the frontend banner.
- [ ] End-to-end test ensuring the banner displays correctly in production environments.
- [ ] Impact analysis is filled out and QA test plan is updated accordingly
- [ ] Does this product have an existing regression test plan?
	- [ ] Yes, link: 
	- [ ] No, regression test plan will be created as part of the work / points in this ticket

**Comment by Agile6MSkinner** [comment]
We ran out of brain. Will finish at next refinement.

**Comment by jilladams** [comment]
Stories 1-5 are in sprint 15. They might reveal things we need to keep in mind when we get to it.

**Comment by dsasser** [comment]
Removed these ACs since this is an API and there are no UX/Accessibility concerns to address:

- [ ] Design review? 
- [ ] Accessibility review?

**Comment by Agile6MSkinner** [comment]
@dsasser I would think no? There's no harm in an endpoint being out there if nothing's happening with it, right?

**Comment by dsasser** [comment]
> [@dsasser](https://github.com/dsasser) I would think no? There's no harm in an endpoint being out there if nothing's happening with it, right?

Agreed it is benign until we pull the launch trigger (flip the flippers).

**Comment by jilladams** [comment]
In PR, blocked on Platform review. (day 2 waiting of 3)

**Comment by SnowboardTechie** [comment]
@jilladams I was able to confirm [here](https://api.va.gov/v0/banners?path=/va-facility-health-care&cookie_id=x2c6r5qebsq4ufvsh5qfk) that the API is giving a successful banner response on production (no banners at this time as the DB table has yet to be seeded with https://github.com/department-of-veterans-affairs/vets-api/pull/19511)

![Image](https://github.com/user-attachments/assets/479691b5-8d8f-4063-84e9-04c7c36b8863)
