### ISSUE TITLE
Add a method to make an exception to exclude an ID on a subheader

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#19467]
## Description
The DS "On this page" component automatically pulls in H2s on the page under 2 conditions:

- They must be a descendant of an article element
- They must have an ID attribute

There are a couple instances in our products where we would like to exclude a particular H2 from this component. Based on the current logic in the component, a way to exclude a header would be to **not** add an ID to that header.

However, within `content-build` there is an automatic process that runs and adds IDs to all subheaders in the content. That process lives here: https://github.com/department-of-veterans-affairs/content-build/blob/main/src/site/stages/build/plugins/modify-dom/add-id-to-subheadings.js.

We want to add some sort of exception into this function/process that would stop an ID from being added to particular headers. 
(The purpose of this would be for the Mission Explainer work happening now)

## Engineering notes
DST has said: to get an element out of the On This Page element, don't assign it an ID.

I talked to Chris about this a bit and his comments:

> It can definitely be done. And that is one way by excluding by text or by className. But I would opt to use a data-testid and filter it out based on that. Its not actually a DST thing. We have this function running for all nodes in content build and adds ids to all h2 and h3s.

### Scope / Impact analysis
Any content that appears in On This page 

### Roles / assignments
_After functional testing, code review, accessibility review, and design review can happen in parallel._
* **Functional testing:** @laflannery 
* **Code review:** @eselkin 

## Acceptance criteria
_ACs should capture expected behavior, to inform test plans. Consider devices, documentation updates including KBs, change management, and [content model](https://prod.cms.va.gov/admin/structure/cm_document) when applicable._

- [ ] A method exists that can be used for any subheader to prevent an ID from being assigned to it
- [ ] The Vet Center mission explainer subheader is added to get this exception
- [ ] Any subhead with an ID, appears in On This Page, across all content affected by the function
- [ ] Does this product have an existing regression test plan?
	- [ ] Yes, link: 
	- [ ] No, regression test plan will be created as part of the work / points in this ticket
- [ ] Design review? 
- [ ] Accessibility review?

**Comment by aklausmeier** [comment]
We will need to close the loop with DST in this ticket. https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2956#issuecomment-2402737738

**Comment by laflannery** [comment]
@chriskim2311 and @eselkin I have put together a [draft test plan spreadsheet here](https://docs.google.com/spreadsheets/d/1PUgwtG8_NXnc54DzYw6bKCYG-Lfmq0rfNL1Va3URLZ4/edit?gid=0#gid=0). It would be great if you had time to review this and see if you can think of anything else I might be missing regarding test cases/criteria to make this as comprehensive as possible. Or let me know if you have any questions on anything I already added. Thanks!

CC: @Agile6MSkinner and @jilladams Feel free to take a look and add anything as well

**Comment by eselkin** [comment]
The spreadsheet looks comprehensive @laflannery

**Comment by chriskim2311** [comment]
@laflannery Thank you for putting that together. Looks good to me!

**Comment by jilladams** [comment]
Merged, should deploy tomorrow.

**Comment by chriskim2311** [comment]
Thanks @jilladams! I was baby sitting this, CI was giving me issues.

**Comment by jilladams** [comment]
Our Commitment no longer appears in the On This Page element! https://www.va.gov/portland-or-vet-center/
![Image](https://github.com/user-attachments/assets/11ef95e6-8619-497a-8890-1dba3f98e192)
