### ISSUE TITLE
[SPIKE] [Facility Locator] Increase MapBox radius for remaining facility types (other than CCP)

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-cms#19462]
## Description
In ticket #18986, in Facility Locator, we extended the MapBox radius for both zipcode and city searches for Community Care (only) to the allowed maximum of 20.

This ticket is to increase the MapBox radius for for both zipcode and city searches for all other types of facilities to 20.

As a reminder, this change is an attempt to increase discoverability of facility providers during Facility Locator searches.

## User Story

**AS A** Veteran, their caregiver or family member
**I WANT** to be able to view all providers withing a given zip code or city when I use that criteria in a Facility Locator search
**SO THAT** I'm aware of all choices near me or within the area I'm interested in.

## Acceptance Criteria

- [ ] Increase the minimum radius for Zip Code searches from 10 to 20 (see list below)
- [ ] Increase the minimum radius for City searches from 10 to 20 (see list below)
- [ ] Do not merge and notify PM (Fran Cross) so that she can perform QA
  - [ ] QA ticket TBD (similar to this one) [19045](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19045)
- [ ] QA passed

List of Facilities to apply the change to:
- VA Health (all services)
- Urgent Care
  - All in-network urgent care
  - VA urgent care
- Emergency care
  - All in-network emergency care
  - VA emergency care
- VA benefits
- VA cemeteries
- Vet Centers

_**Note that the list above is assuming the following have already been expanded to 20. If any of the below are not at 20, then add these to the list.**_
- Community providers (in VA's network)
- Community pharmacies (in VA's network)
- In-network CCP urgent care
- In-network CCP emergency care

**Comment by FranECross** [comment]
@Agile6MSkinner @eselkin This is a ticket adjacent to the community care provider work I'm handling, and in a convo with Michelle on Monday's product sync, she agreed that we should increase the radius of the other facility types to see if that solved the outstanding defect where a provider in Anchorage isn't displaying. I added to the CCP epic for tracking purposes.

**Comment by jilladams** [comment]
@eselkin I feel like there was a PR for this, but I'm not finding it now - mind linking it?

**Comment by eselkin** [comment]
There was no PR for this, since my attempts did not work at sizing up the region in the same way that CCP was able to size up the region. I still haven't tracked down the reason the bounding box shrinks on some queries.

**Comment by eselkin** [comment]
So, I think what's happening, no matter if we give a radius of 40 or 50 miles to PPMS for a point (postcode geocoded to center point) they only return the same values as they would for 5 mile radius. What really matters is the center point and there's no way to adapt that. But what's odd is if you increase the max results to like 500 and then increase the range then you do get more back...

So what must be happening is our limit of like 10 is bringing back all types of facilities (even not the ones we want to match). Then PPMS is filtering for matches of types for that 10. Then it's finding the ones in range. So naturally we can't match a wide range if it's finding all the non-matching ones that are close as well.

**Comment by jilladams** [comment]
Is the limit of 10 coming from us when we call the PPMS API? (Meaning: we could adjust how many we ask for in the response? ) Read: trying to read from your comment what the next steps for this ticket might be.

**Comment by eselkin** [comment]
Yes (we give them the number 11 - to get 10 back - not sure why), however, I haven't figured out what is a good number to use instead of 11. If we use 20 we sometimes get better results, but not always. If we use 100 we generally get better results. But 100 might lead to a lot of results if we aren't limiting responses to a certain type. I'm trying to see if there's a way to raise that limit only in certain scenarios and maybe to figure what those scenarios might lead to.

**Comment by eselkin** [comment]
We were always talking about increasing the result maximum size / number of results. So maybe we do it here to like 50 or 100 but only in PPMS requests?

**Comment by eselkin** [comment]
I forgot, the issue was pagination on results - and adding pagination on vets-website as opposed to vets-api.

**Comment by jilladams** [comment]
Ahhh right. Ugh. Not sure where that puts this, still. If a convo with Fran is warranted to bounce product ideas / options around, feel free.

**Comment by FranECross** [comment]
Adding Eli's summary from [Slack](https://dsva.slack.com/archives/C0FQSS30V/p1732641060263699) here:

Here's a summary of the changing the radius of search results for PPMS (and mixed PPMS/VA and others) and complications that have arisen:
- If you just increase the radius it doesn't increase the number of results returned for PPMS urgent care and provider
- If you increase the maximum number of results returned it does increase the results
- If you increase both the radius and the maximum results (to a fairly large number like 50-100 -- we currently use 10) you can get the data expected on searches such as urgent care in Anchorage, AK/99515 (this is because the way PPMS searches it first limits the number of results, then filters the results for type so it gets way fewer of the facility type than expected)
- The complication with increasing both is... if you are searching in an area that has a lot of results with a large maximum result list, you get a lot of results back. Too many results in fact. The little markers are numeric so we can show a lot now but it is still probably not a good idea to flood the user. At one point we talked about adding pagination to the frontend and increasing the maximum result size. This seems like we might have to do that in order to get the larger radius and maximum result size.

And my [response](https://dsva.slack.com/archives/C0FQSS30V/p1732642320366039?thread_ts=1732641060.263699&cid=C0FQSS30V):

Thanks so much for the great research and summary! I'll re-designate the ticket as a spike, and we can close it as done. I'll add the info from the spike to the new CCP epic I created yesterday and will review with Michelle in the near future to see if this can be an early 2025 initiative. You ROCK!

Closing ticket.
