### ISSUE TITLE
Quick Wins from Q3 Editor Survey Results

### ISSUE THREAD

**Issue by gracekretschmer-metrostar** [department-of-veterans-affairs/va.gov-cms#19461]
## User Story or Problem Statement
As an editor, I need to see how my feedback was used to inform future development of the CMS. 

## Description or Additional Context 
 In the responses to the editor survey, some editors expressed that they were skeptical that their responses would lead to any changes within Drupal CMS. To demonstrate that we value their feedback, we want to find opportunities for "quick wins" aka small changes we can make within Drupal CMS to demonstrate to editors that we are listening to their feedback. 

## Steps for Implementation
- Review Q3 editor survey results to find small opportunities for changes within Drupal CMS. 
- Partner with relevant CMS team members to validate how feasible the change is within Drupal CMS. 
- Synthesize recommendations within this ticket. 

## Acceptance Criteria
- [x] A list of 5 small tasks that CMS team could implement, based upon the feedback from Q3 editor survey.

**Comment by MDomngz** [comment]
1. move daily prod-deployment time to non-working hours, avoiding times when editors are online
2. modify in-line micro text within workflows to include KB links for applicable support articles
3. set up data tracking for each workflow to learn more about editor behavior
4. review kb articles for audience appropriateness, we want to ensure we are speaking to all levels of editors

@gracekretschmer-metrostar

**Comment by gracekretschmer-metrostar** [comment]
@MDomngz can you create tickets for each of the areas of work that you identified?

**Comment by MDomngz** [comment]
Hi @gracekretschmer-metrostar, I've created new tickets for the quick-wins. They are listed on this ticket as sub-tasks. 

I held off on #3 until we work through the items with Jake and CMS Analytics.
