### ISSUE TITLE
KB Analytics: Implement KB Analytics Dashboard

### ISSUE THREAD

**Issue by gracekretschmer-metrostar** [department-of-veterans-affairs/va.gov-cms#19463]
## User Story or Problem Statement
As a member of the CMS team, I need to be able to see the analytics in a dashboard. 

## Description or Additional Context 
 Before the KB analytics can be implemented, the CMS team needs to partner with the analytics team to create a CMS analytics dashboard  

## Steps for Implementation
- Create a list of who from CMS should have access to the CMS Analytics Dashboard (same list as datadog)
- @JakeBapple will be set up as owner for now, all others will be analysts
- Install and enable the ga4 drupal module (https://www.drupal.org/project/ga4_google_analytics)
- Get the measurement_id from internal analytics team and plug it in

## Acceptance Criteria
- [ ] An CMS KB analytics dashboard is created and the appropriate CMS members are given the appropriate access.
- [ ] All access decisions are documented within Github.

**Comment by JakeBapple** [comment]
List of people are: 
Grace
Marisa
Jake
Edmund 
Tim
