### ISSUE TITLE
VAMC Real-time banners launch plan

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#19466]
There will be a slight change to the way that editors see banners publish. Nothing will change in the Drupal form.

## Dev
- [x] Create a vets-api Flipper: [banner_use_alternative_banners](https://api.va.gov/flipper/features/banner_use_alternative_banners)
- [x] Create [CMS feature toggle](https://prod.cms.va.gov/admin/config/system/feature_toggle), `FEATURE_BANNER_USE_ALTERNATIVE_BANNERS`
- [x] Finish launch blocking tickets
- [x] REPOs / MERGES for functional banner work ( not flipper creation)
  - [x] vets-api endpoint / data work: can merge to prod
  - [x] vets-website: can merge to prod BEHIND vets-api flipper
  - [x] content-build: existing prod work must move behind CMS feature toggle (ticketed)
  - [x] Drupal: no changes

Launch day should not involve merges or deployments. Everything should be in main in all branches, and be launchable using flippers.

## QA
- [ ] In a Tugboat built from main across all branches: test, verify, and document the order of steps to launch based on testing: 
   - [x] Run [QA test plan](https://docs.google.com/spreadsheets/d/1PUgwtG8_NXnc54DzYw6bKCYG-Lfmq0rfNL1Va3URLZ4/edit?gid=0#gid=0) and verify - #19887 
   - [ ] Goal: no visible changes, and SPEED

## Collab cycle - @Agile6MSkinner 
- [x] File CC intake - https://github.com/department-of-veterans-affairs/va.gov-team/issues/96762
- [x] Produce Architecture intent artifact, being mindful that we want approval of the concept that may apply to more things than VAMC BwSU in the future (operating statuses, etc) - N/A - Arch intent was not suggested in CC collab cycle ticket
- [x] Schedule Architecture intent - N/A
- [x] see if we can skip other touchpoints, with Governance team approval - they suggested: Design Intent, CMS request, Staging Review
- [x] Product Staging Review artifacts
  - [x] Architecture intent
  - [x] QA artifact
  - [x] Foundational accessibility testing artifact
- [x] Schedule Staging Review with at least 4 business days from final artifacts being done, for Governance team to review
  - **Scheduled for Fri 12/13 11a**: Jill will be on PTO and is the main invitee to the calendar invite. If meeting changes, @Agile6MSkinner will need to coordinate direct with Governance team for updates / invitation. 

## Pre-deploy comms
- [x] DM: Notify Helpdesk - @jilladams https://dsva.slack.com/archives/CT4GZBM8F/p1734372067656079
- [x] PM / DM: Are there KBs to update? If so, edit and save Drafts. - @Agile6MSkinner / @jilladams - add updates t
   - [x] [About VAMC alerts and operating statuses](https://prod.cms.va.gov/help/vamc/about-locations-content-for-vamcs/about-alerts-and-operating-statuses)
   - [x] [How do I update my Vet Center facility operating status?](https://prod.cms.va.gov/help/vet-centers/how-do-i-update-my-vet-center-facility-operating-status)
   - [x] [How to edit a VAMC facility operating status](https://prod.cms.va.gov/help/vamc/about-locations-content-for-vamcs/about-alerts-and-operating-statuses/how-to-edit-a-vamc-facility-operating-status)
   - [x] [How to edit the operating status of an NCA facility](https://prod.cms.va.gov/help/va-cemetery-facilities-nca/how-to-edit-the-operating-status-of-an-nca-facility)
   - [x] [How do I update my VBA facility operating status?](https://prod.cms.va.gov/help/veterans-benefits-administration-vba/how-do-i-update-my-vba-facility-operating-status)
   - [ ] [How to edit a VAMC Facility](https://prod.cms.va.gov/help/va-medical-centers-vamcs/about-locations-content-for-vamcs/how-to-edit-a-vamc-facility)
   - [x] [How to create a situation update](https://prod.cms.va.gov/help/vamc/how-to-create-a-situation-update)
   - [x] [How to add a system banner alert](https://prod.cms.va.gov/help/vamc/about-locations-content-for-vamcs/about-alerts-and-operating-statuses/how-to-add-a-system-banner-alert)
- [x] Confirm the timing of when content pushes to GovDelivery under the new system (with Publish save, or with content release?). So far we know it gets added to a queue in Drupal on save, but we don't know when that queue goes out. - @omahane or @dsasser  -- **after content release**
- [ ] PM: Send content to Justin for a Teams message in VAMC Editor channel to warn that a change is coming, along with timing - @Agile6MSkinner 
  - Explain the change

## LAUNCH
- [x] If there are no [published VAMC BwSU](https://prod.cms.va.gov/admin/content/vamc-alerts-and-statuses?field_alert_type_value=All&type=full_width_banner_alert&moderation_state=All&status=1&field_administration_target_id=All) on day of deployment. Plenty of published banners.
- [x] Notify CMS team of launch and need for support around content release -- https://dsva.slack.com/archives/CT4GZBM8F/p1734372067656079
- [x] Configure flipper with user emails we need to test. Emails are in this [slack thread](https://dsva.slack.com/archives/C0FQSS30V/p1731700890819489)
- [x] Enable new alternative banners via vets-api Flipper
- [x] Confirm that we see 2 sets of banners (duplicate): both content-build and vets-website versions. Keep this step to less than 5 minutes
- [x] When we verify double banners, re-disable vets-api Flipper.
- [x] Update vets-api flipper to change it from user-driven flipper to global on/off.
- [x] **Afternoon PST:** Enable CMS feature toggle FEATURE_BANNER_USE_ALTERNATIVE_BANNERS
  - [x] After a successful content release, content-build banners will disappear.
- [x] **Toward the end of that content release:** Enable vets-webite flipper again. Alternative banners are now on.  (Michelle has accepted the risk of temporary double banners in prod.)
- [x] If that checks out: let Justin know we're live, for Editor comms
- [x] Publish KB draft revisions

## post-launch / tech debt
- [ ] Update https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/READMES/vamc-facilities.md#status-changes-to-lighthouse to be accurate for the new world
- [ ] #19468
- [ ] #20041 
- [ ] #19908 
- [ ] #20064

**Comment by jilladams** [comment]
We can reference #19064 for help fleshing this out, once we've figured out what repos / branches / feature toggles we are / aren't using, in order to spell out launch steps.

**Comment by jilladams** [comment]
@Agile6MSkinner @laflannery @dsasser @mmiddaugh @SnowboardTechie (and @eselkin @omahane for sanity checks) Notes from launch discussion are added to the launch plan. Please give it a read through and make sure it makes sense to everybody?

**Comment by jilladams** [comment]
From planning today, we realized that testing in lower environments is going to be next to impossible if not on local, same as re: some other tickets where we need both a CMS feature toggle to control content-build, and a flipper to control vets-website: 

Laura's summary: 
* Tugboat is not feasible because we can't preview CB and VW changes together
* There is no front end for staging CMS: if we turn a toggle on there, we won't be able to see it in staging FE
* Review instances can't preview CB and VW changes together

We can get confidence testing locally, but then anywhere in between will be a :woman-shrugging::skin-tone-2: until we get to production, which is also a juggling act getting a feature toggle flipped on via content-release and then feature flipper on via flipper admin. We will need to factor all this in for this project as well.

**Comment by jilladams** [comment]
INCORRECT! We _can_ test in Tugboat. 

* Merge everything to main in content-build and vets-website, behind flippers
* Build a Tugboat from main(s) across all branches
* Use https://dev-api.va.gov/flipper/features to control flippers for Tugboat

Added to ticket body

**Comment by jilladams** [comment]
@SnowboardTechie @dsasser @Agile6MSkinner @laflannery Closing loop on how to test / ship for lower envs testing and for prod: 

## For testing
We can use the vets-api flipper as-is: on, or off, for everyone. That will work in Tugboat. 

## For prod double-banners verification
We can use the vets-api flipper config to specify a set of users. We enter those users, turn it on, and only those users will see double banners. This is not EXACTLY a replica of lower env testing, but it's not a code change and is safe enough. Also: it will be a double banners test in prod, and that's the goal. We think it will be fine this way. 

To enable that: everybody cc'ed here: please: 
* Go to https://va.gov
* Login as yourself, however you do that. 
* Double check the email you used, and add add it to this slack thread, so we can track it for launch day:

**Comment by jilladams** [comment]
Also: I think the body of this ticket is now updated / accurate across the board. I'd love to make sure others agree.

**Comment by laflannery** [comment]
@jilladams everything looks good on the QA front. I have 1 question though - Will I be doing the foundational testing? If so, I would imagine I would do that in Tugboat at the same time as functional QA?

**Comment by jilladams** [comment]
Yeah, hadn't gotten that far yet, but that sounds right that whoever does Foundational testing (for the Collab Cycle artifact) would need to do it on Tugboat

**Comment by jilladams** [comment]
https://dsva.slack.com/archives/C0FQSS30V/p1734369322725169
> Re GovDelivery timing for Situation Updates email, I found documentation on the timing! It is after a successful Content Release

**Comment by jilladams** [comment]
Re: enabling flipper for certain emails, I am confused. Asked for help here: https://dsva.slack.com/archives/C0FQSS30V/p1734372421339439
