### ISSUE TITLE
Add CMS feature toggle to provide ability to toggle content-build OFF for banners (Story 7)

### ISSUE THREAD

**Issue by davidmpickett** [department-of-veterans-affairs/va.gov-cms#19471]
## Description

Create a CMS feature toggle to allow turning off banners going through content build so that there are not two banners.

## Acceptance criteria

- [ ] CMS feature toggle is created, called `feature_banner_use_alternative_banners` 
- [ ] Toggle is OFF by default

**Comment by dsasser** [comment]
Decision: we [decided](https://dsva.slack.com/archives/C52CL1PKQ/p1730747747918419) to make the CMS feature toggle act the same way as the related Flipper on vets-api where:
ON = use alternative banners from vets-website + vets-api
OFF = use current "legacy" banners from content-build

I'll update ACs to match this.

**Comment by jilladams** [comment]
![Image](https://github.com/user-attachments/assets/861ba5a9-21eb-4956-a3e2-389acad7eecd)
