### ISSUE TITLE
Increase the Time and Volume to Retrieve IP Address

### ISSUE THREAD

**Issue by gracekretschmer-metrostar** [department-of-veterans-affairs/va.gov-cms#19475]
## User Story or Problem Statement
As the CMS DevOps engineer, I need to understand the path forward to minimize the problem of missing IP addresses bringing down CMS Prod during daily deploy. 

As an editor in Drupal CMS, I need to have confidence that Prod CMS will not go down, so I know I can complete my work duties without access challenges. 

## Description or Additional Context 
 Missing IP addresses have caused prod CMS to go offline during daily deploy and the platform team is constrained on how much they can increase the number of IP addresses for prod CMS. Therefore, we need to brainstorm ways we can better mitigate this situation in the future. 

## Steps for Implementation
- Do some cost/benefit analysis of the solutions
- Meet with platform and CMS tech leads to confirm strategy for IP address issue
- Incorporate feedback and plan of action into Github (specifically, [this ticket](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19423)

## Acceptance Criteria
- [x] A plan of action is identified to approach the IP address issue. 
- [x] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19423 is refined and ready to be picked up for work

**Comment by timcosgrove** [comment]
We recommend 200 retries at 10 seconds intervals, or 400 at 5 seconds.

**Comment by gracekretschmer-metrostar** [comment]
Another possible opportunity: put in better error handling when IP addresses fails.
