### ISSUE TITLE
New "Family and caregiver hub" menu needs to be enabled in Content Type Menu settings config

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#19481]
## Status
**[2024-10-18] [Fran]** Prioritizing for Sprint 16; Jill shared that Randi H. has encountered this issue again, so it will be good to get this fixed.

## Description
We deprecated an old Benefit Hub and made a new one: 
* Old = Family health benefits 
* New = Family and caregiver benefits 

Each of these has a correlated menu. 
When CAIA makes sub-pages, they need to select the correct parent menu item. 
CAIA can see the old menu, but not the new menu. 
New menu = https://prod.cms.va.gov/admin/structure/menu/manage/family-and-caregiver-benefits

We need to fix that, so CAIA can select the new menu. The fix: The menu needs to be enabled in the Content Type Menu settings via a config PR by a Drupal engineer

https://dsva.slack.com/archives/CDHBKAL9W/p1728587946601949?thread_ts=1727463549.317269&cid=CDHBKAL9W
> It makes sense that if we check the ‘provide menu link’ box, we should be choosing the menu called ‘Family and caregiver benefits’ (the new one) rather than ‘Family health benefits’ (the old one). But the new one was not available in that menu — do we know who can resolve that?

![Image](https://github.com/user-attachments/assets/3cfad7d2-af43-4571-8f94-58bf28ea8315)

### Scope / Impact analysis
Shouldn't impact anything - just captures the new setting.

### Roles / assignments
_After functional testing, code review, accessibility review, and design review can happen in parallel._
- [x] **Functional testing:** 
- [ ] **Code review:** 
- [ ] **Product acceptance:** 

## Acceptance criteria
_ACs should capture expected behavior, to inform test plans. Consider devices, documentation updates including KBs, change management, and [content model](https://prod.cms.va.gov/admin/structure/cm_document) when applicable._

- [x] As the Kristin Ouellette Muskat user, I can select the [Family and Caregiver Hub menu](https://prod.cms.va.gov/admin/structure/menu/manage/family-and-caregiver-benefits) as the parent link for a Benefit Detail Page node
- [x] Impact analysis is filled out and QA test plan / ACs are updated accordingly

**Comment by jilladams** [comment]
@FranECross it would be nice if we can prioritize this into next sprint - RandiH ran into this issue again today: https://dsva.slack.com/archives/CDHBKAL9W/p1729169728620629

**Comment by davidmpickett** [comment]
**End of Sprint update**
- This wasn't planned for Sprint 15. I picked up from Ready
- PR passed functional testing and needs code review
- Tugboat reliability issues today prevent further work

**Comment by jilladams** [comment]
Verified in Staging (cloned from Prod) as CAIA test user. 
![Image](https://github.com/user-attachments/assets/7e16cee5-2f08-4596-b109-fd4a5c360d50)

**Comment by jilladams** [comment]
Updated CAIA: https://dsva.slack.com/archives/CDHBKAL9W/p1730411430250459?thread_ts=1727463549.317269&cid=CDHBKAL9W
