### ISSUE TITLE
Facility Locator: Finalize layout revision/progressive disclosure design and add annotations

### ISSUE THREAD

**Issue by thejordanwood** [department-of-veterans-affairs/va.gov-cms#19484]
## Description 

Make any updates to the new facility locator layout revision design if necessary. Add design and accessibility annotations to mockups. 

## Design 
[Layout Revisions page in Facility Locator Figma file](https://www.figma.com/design/GvNVeG9GAXZaBpny7vNxZP/Facility-Locator?node-id=806-27055&t=K0P7LqxOhp3qMpZR-1)

## Design revisions

Add any specific design finalization/revisions here. 
- [x] Maybe - incorporate loading indicator into Community provider progressive disclosure flow (@davidmpickett mocked in #19332)
- [x] Show current state of facility locator. Add "use my location" to designs

## Acceptance criteria

- [x] Final design is in Figma
- [x] Add design and accessibility annotations
- [x] Review with UX Lead, Product, Accessibility

**Comment by jilladams** [comment]
Thread here asking if #19484 and #18960 are dupes or not: https://dsva.slack.com/archives/C06S9DADEUB/p1730932102417359

**Comment by thejordanwood** [comment]
@laflannery I've added design annotations for this in [the Figma file](https://www.figma.com/design/GvNVeG9GAXZaBpny7vNxZP/Facility-Locator?node-id=1280-45468&t=6kicvbPXqEXn4Djn-1). This is ready for accessibility annotations. Let me know if there's any other mockups we need to annotate for this!

**Comment by jilladams** [comment]
@thejordanwood  I think you mentioned in scrum, but I've since forgotten what's outstanding here - mind adding an end of sprint note?

**Comment by thejordanwood** [comment]
Designs are updated and annotations have been added. UX has reviewed and I believe engineering has too. @eselkin If you have any questions now or in the future just let me know! 

I'm going to go ahead and close this ticket since the work has been done.
