### ISSUE TITLE
SA-CORE-2020-013   Update to Drupal 8.9

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#1949]
SA-CORE-2020-013

https://www.drupal.org/sa-core-2020-013

**Comment by acrollet** [comment]
This has become high priority as Drupal 8.8.x [loses security coverage on Dec 2](https://www.drupal.org/project/drupal/releases/8.8.11). (Happy Birthday to Kev!)

```Drupal 8.8.x will receive security coverage until December 2, 2020 when Drupal 9.1.0 is released. You should plan to update to 8.9.x or higher as soon as possible.```

cc @oksana-c @ElijahLynn
