### ISSUE TITLE
URL Change for: change FROM Kansas City Kansas VA Clinic TO Captain Elwin Shopteese VA Clinic (Awaiting CSV)

### ISSUE THREAD

**Issue by TroyCMSSupport** [department-of-veterans-affairs/va.gov-cms#19509]
Parent ticket: #number-of-GH-ticket https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19508

### Implementation date
When does this request need to be live:
[ASAP]

### Instructions for URL redirect
(Note: This issue will be used from initial request through implementation to ensure all individuals working on this are notified of status updates.  Please do not create multiple issues to track different steps.)
- [x] Notify VA stakeholders as appropriate.
- [x] Link the related facility rename issue. https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19508
- [ ] Create a URL redirect in the [vsp-platform-revproxy](https://github.com/department-of-veterans-affairs/vsp-platform-revproxy) repo in `template-rendering/revproxy-vagov/vars/redirects.yml`
- [x] Add the "Awaiting redirect" flag to the facility node with a revision log message that includes a link to this ticket, preserving the node's current moderation state.
- [x] Redirects deploy daily except Friday at 10am ET, or by requesting OOB deploy (of the revproxy job to prod) in #vfs-platform-support. After deploy, validate that the URL redirect is deployed. (Note: In the event of a facility closure or a name change,  validate that this occurs before making the Lighthouse csv changes.)
- [x] Update this ticket with a comment that the redirect has been deployed.
- [x] Remove the "Awaiting redirect" flag on the facility node with a revision log message that includes a link to this ticket, preserving the node's current moderation state.
- [x] Notify helpdesk via comment on ticket or Slack message in #cms-support that changes are ready for review.

#### URL Redirect
| Current URL  |  Redirect Destination or New URL |
| ---  |  --- |
| https://www.va.gov/eastern-kansas-health-care/locations/kansas-city-kansas-va-clinic | (https://www.va.gov/eastern-kansas-health-care/locations/captain-elwin-shopteese-va-clinic) |

### 1. Canonical URL change

**Note: Canonical URL changes do not block the completion of the parent ticket. Once the URL redirect above has been deployed, the value to the Veteran is delivered. This ticket should be kept open until the URL change is verified, except in the case of a removal (as described below).**

### Instructions for canonical URL change
- [x] Verify that the new URL for the facility is published and accessible on VA.gov.
- [x] Contact Lighthouse via Slack at #cms-lighthouse channel that this facility requires a canonical link in the following format (replacing the placeholder data with the actual API Id and VA.gov URL):
  - `vha_589GJ,https://www.va.gov/eastern-kansas-health-care/locations/captain-elwin-shopteese-va-clinic`
- [x] Add the "Awaiting CSV" flag to the facility node with a revision log message that includes a link to this ticket.
- [x] Let Help desk know this has been done, if not done by Help desk.

#### Wait (days or weeks, potentially)
- [x] After the canonical link has been added to the websites.csv and you have confirmation from Lighthouse that the CSV has been deployed, validate that the change has deployed by checking that the Facility Locator has been updated with the new url.
- [x] Update this ticket with a comment that the CSV change has been deployed.

#### URL change example (update with actual ID and URL)
| Facility API ID  |  Full VA.gov URL |
| ---  |  --- |
| vha_589GJ | https://www.va.gov/eastern-kansas-health-care/locations/captain-elwin-shopteese-va-clinic/ |

**Comment by TroyCMSSupport** [comment]
@omahane @jilladams  --

Please Create a URL redirect in the [vsp-platform-revproxy](https://github.com/department-of-veterans-affairs/vsp-platform-revproxy) repo in template-rendering/revproxy-vagov/vars/redirects.yml

Please alert Helpdesk when this step has been completed.

**Comment by jilladams** [comment]
Noted - we didn't pull this in during sprint planning this morning, @omahane . That's my bad. Do you think we could?

**Comment by jilladams** [comment]
Redirect here has been deployed.

**Comment by jilladams** [comment]
I updated the one checkbox but don't have time to chase the LH step right now. If Helpdesk does, yay. If not, @omahane or I will come back to it. I did move this ticket to Awaiting CSV in the Flagged Facilities project board.

**Comment by ian-sears** [comment]
I was going to add it to the lighthouse channel, however I don't see this resolving yet. @jilladams 
We will however keep an eye out for this and make the request for the CSV.

**Comment by TroyCMSSupport** [comment]
@ian-sears  - I updated the URLs to reflect the www path rather than the prod.cms path.
Thank you for pointing that out.

**Comment by omahane** [comment]
As of this morning, the redirect has been merged but not deployed.

**Comment by jilladams** [comment]
(My bad, sorry for churn here. I saw the page title, and didn't cross-check the actual URL resolving)

**Comment by jilladams** [comment]
Daily deploy failed today: https://github.com/department-of-veterans-affairs/vsp-platform-revproxy/actions/runs/11594848582

Should go tomorrow.

**Comment by jilladams** [comment]
The URL is redirecting but I'm getting a 404 on the landing page: 
https://www.va.gov/eastern-kansas-health-care/locations/captain-elwin-shopteese-va-clinic/

The URL alias for the node is still: `/eastern-kansas-health-care/locations/kansas-city-kansas-va-clinic`
Node: https://prod.cms.va.gov/eastern-kansas-health-care/locations/captain-elwin-shopteese-va-clinic
          
@TroyCMSSupport @ian-sears finishing up the Drupal Admin steps on https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19508 will finish this up. I'm not sure if the template got steps out of order? (It does show in that ticket that we should do the URL change ticket before updating the alias, but: that makes a 404.)

**Comment by omahane** [comment]
The issue with these name changes is that you either update the node before revproxy changes, which means that the URL changes to the new one before the redirect:
- Facility Locator will still return the old URL, so it will 404 from there, even though it will be right when clicking from prod (which is really only useful to editors)

Or you do it after the name change is deployed:
- Then you have to do the URL change in production after (or ideally, as) front-end deploys.

And yesterday it didn't deploy at all.

So . . . I should have put a reminder. I checked this morning, but it sill had 4 hours to go. And then got busy.

**Comment by TroyCMSSupport** [comment]
Awaiting CSV - https://dsva.slack.com/archives/C02BTJTDFTN/p1730471572873009

**Comment by ian-sears** [comment]
CSV request (above url is now redirecting ok) is here:
https://dsva.slack.com/archives/C02BTJTDFTN/p1730988261314589?thread_ts=1730765512.022909&cid=C02BTJTDFTN
I could not locate a #cms-lighthouse request, so made this one.
This request is being staged by the lighthouse team today for Deploy tomorrow.

**Comment by ian-sears** [comment]
CSV has been deployed.
Both the URL redirect and the facility locator now resolve correctly.
Closing as resolved.
@department-of-veterans-affairs/platform-cms-helpdesk fysa
