### ISSUE TITLE
Improve Drupal UX for Staff Profile, VAMC Billing & Insurance, VAMC Facility mental health phone number

### ISSUE THREAD

**Issue by davidmpickett** [department-of-veterans-affairs/va.gov-cms#19512]
**[2024-10-16]** Not blocking shipping CMS changes behind a toggle, but **IS** launch blocking for change management / editor comms.

## Description

These three content types are changing from a single non-required field to a paragraph type for phone number entry

- Staff Profile
- VAMC System Billing & Insurance
- VAMC Facility - (Mental Health Phone Number)

## Current UX quirks

When a phone number has been added, it's not immediately clear how to remove it. There's also a bunch of irrelevant options in the menus like Collapse and Drag & Drop. We also repeat the "phone number" title.

![Image](https://github.com/user-attachments/assets/c547c0c8-83ce-45d1-9404-02c0a32fd64f)

When no phone number has been added there's a weird gap with a bullet point in it. And there's the awkward phrase "add phone number to phone number"

![Image](https://github.com/user-attachments/assets/ef0f6600-6f6b-434d-a6e5-e08d75c6c5a5)

## Change log
- Staff Profile now defaults to no phone number (but can be manually added)
- The widget for all three content types has changed from Paragraphs Stable to Paragraphs Legacy 

State | Current UI | New UI
-- | -- | --
No phone number added |![Image](https://github.com/user-attachments/assets/235a3c68-515f-48c8-a6c4-5de3013c9959) |![Screenshot 2024-10-24 at 5 16 25 PM](https://github.com/user-attachments/assets/9f0a3e81-5f9c-41a2-aacc-f862991d50df)
With phone number added |![Screenshot 2024-10-24 at 5 19 03 PM](https://github.com/user-attachments/assets/935b7c6c-05f1-460f-82e4-ce0e95004235) |![Screenshot 2024-10-24 at 5 31 56 PM](https://github.com/user-attachments/assets/2f0c1fc7-039e-4821-ab76-6a4390c9c347)

## Acceptance criteria
_ACs should capture expected behavior, to inform test plans. Consider devices, documentation updates including KBs, change management, and [content model](https://prod.cms.va.gov/admin/structure/cm_document) when applicable._

- [x] Implement new interface for each Content Type

**Comment by jilladams** [comment]
In sprint 15: Jordan may not have time to address before Dave is back from PTO

The conversation from scrum: https://dsva.slack.com/archives/C079GFKN50D/p1729007496363379?thread_ts=1728955309.898119&cid=C079GFKN50D
> Staff Profile = guess: ~75% of those have #s
> Mental Health Phone = should feel required (or be required)
> Billing & Ins = need to audit to know which way to handle

> All 3 don't have to act the same.

This does not block merging existing phone # work to prod behind the feature toggle.

**Comment by jilladams** [comment]
Pointing as a 5 based on Jordan's level of familiarity. May be lower if Dave picks it up.

**Comment by davidmpickett** [comment]
@jilladams Is this in Sprint or Needs refinement?

**Comment by davidmpickett** [comment]
# WIP notes to self

## VAMC System Billing & Insurance
- Current total = 140
- # with phone number filled in

## VAMC Facility - (Mental Health Phone Number)


## Staff profile

**Comment by davidmpickett** [comment]
I think the solution is gonna be switching to Paragraphs Legacy widget

![Image](https://github.com/user-attachments/assets/ccb70e31-29ae-42ec-87e0-26d3a209cceb)
![Image](https://github.com/user-attachments/assets/820d2864-b0fb-437d-9c92-c0bc440cf399)

**Comment by davidmpickett** [comment]
**End of Sprint update**
- PR has ✅ code review and ✅ UX review ([slack thread](https://dsva.slack.com/archives/C0FQSS30V/p1729893364216969))
- Waiting to hear from @laflannery if a11y review is needed
- Other than that ready to merge & verify

**Comment by davidmpickett** [comment]
**Update**
- I have moved this back to In Progress to incorporate @laflannery's [notes](https://github.com/department-of-veterans-affairs/va.gov-cms/pull/19607#issuecomment-2447201955) in the PR
- Because the new scope of Laura's edits require modifying the SCSS, I am also gonna fix the [Truncated text](https://github.com/department-of-veterans-affairs/va.gov-cms/pull/19607#issuecomment-2441929337)issue @jilladams caught 
- Will need to go through testing and code review again & now need review by CMS platform team

**Comment by jilladams** [comment]
@Agile6MSkinner we noted in ticket at some point that this is blocking editor comms, except turns out we did not. 😬 Just flagging that for awareness, and that this is something we should try to ideally knock out before we close the epic

**Comment by omahane** [comment]
@jilladams The PR to address this has been merged: https://github.com/department-of-veterans-affairs/va.gov-cms/pull/19607

**Comment by jilladams** [comment]
Updated UI in prod: 

![Image](https://github.com/user-attachments/assets/347ef54a-ae56-41e0-a23d-1928a820267f)

![Image](https://github.com/user-attachments/assets/55f4ff33-88bb-4907-8754-f3001d55f279)
