### ISSUE TITLE
Add poster download field on Event content

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#1951]
## User story

As an event manager, i want to be able to add a poster download 

## Affected users

Eg a PAO in Pittsburgh who wants to add a PDF download, but could not, June 4 2020.

## Implementation scenarios

* Add a Download field that allows pdfs and jpgs, possibly a Media field.

**Comment by jilladams** [comment]
Per Dave Conlon: this seems like a marketing request, not a veteran concern, so iceboxed until we can prove veteran-facing value.

**Comment by FranECross** [comment]
Closing as a no op.
