### ISSUE TITLE
Access denied when setting user role

### ISSUE THREAD

**Issue by omahane** [department-of-veterans-affairs/va.gov-cms#19523]
## Describe the defect
Admin users are unable to set the roles of users.

## To Reproduce
1. Log in as an admin
2. Go to https://prod.cms.va.gov/admin/people
3. Choose any user
4. Click "Edit" under **Roles**
- [ ] Confirm that you receive an "Access denied"
5. Go to https://prod.cms.va.gov/admin/reports/dblog/
6. Click on the message of the related "access denied" log entry
- [ ] Confirm that the message is like "Path: /user/4017/roles. Drupal\Core\Http\Exception\CacheableAccessDeniedHttpException: in Drupal\Core\Routing\AccessAwareRouter->checkAccess() (line 115 of /var/www/cms/docroot/core/lib/Drupal/Core/Routing/AccessAwareRouter.php)."

## AC / Expected behavior
An admin user is able to edit user roles.

## Screenshots
![Image](https://github.com/user-attachments/assets/62f875e6-f29e-487c-91be-ff8a918217dd)

**Comment by timcosgrove** [comment]
The user link should be removed. This route is no longer provided by Drupal. Roles are edited on the main user edit form. Simply remove the last 'User: User ID' item in the field list of the view `/admin/structure/views/view/user_admin_people`: ![Image](https://github.com/user-attachments/assets/1ee09117-b6a2-4b5b-80f9-6459b4705be9)

**Comment by edmund-dunn** [comment]
Roles are now part of the main edit tab. We are removing the Edit link in the roles column in favor of the main edit link in the Edit column. 
![Image](https://github.com/user-attachments/assets/68f4f9f3-3999-4861-ad76-f077455d59c3)
