### ISSUE TITLE
Listening Session with Ryan

### ISSUE THREAD

**Issue by nickbloom** [department-of-veterans-affairs/va.gov-cms#1953]
**Owners** 
@nickbloom 
@jordanamello 

Complete listening session with Ryan Stubblebine for both CMS and Facilities to get a brain dump of his experience

**Comment by oksana-c** [comment]
@jordanamello ,do we still need to follow through w/ this issue? It seems to be outdated and we've had several communication threads w/ Ryan since. Please close if this is not relevant anymore. Ty

**Comment by jordanamello** [comment]
@oksana-c I'm closing this issue. It was related to a list of complaints/suggestions that Ryan put together long ago and that Nick and I were supposed to have a clarification convo with him. I believe this list was already addressed by Kev.
