### ISSUE TITLE
URL Change for: VBA National Capital, Houston ROs, Denver & Cheyenne

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#19543]
Parent ticket: #19542 

Noting: #95250 was created to redirect the VBA TeamSites to VA.gov.

### Implementation date
When does this request need to be live:
Whenever we can

### Instructions for URL redirect
(Note: This issue will be used from initial request through implementation to ensure all individuals working on this are notified of status updates.  Please do not create multiple issues to track different steps.)
- [x] Notify VA stakeholders as appropriate.
- [x] Link the related facility closure / rename issue.
- [x] Create a URL redirect in the [vsp-platform-revproxy](https://github.com/department-of-veterans-affairs/vsp-platform-revproxy) repo in `template-rendering/revproxy-vagov/vars/redirects.yml`
- [ ] Redirects deploy daily except Friday at 10am ET, or by requesting OOB deploy (of the revproxy job to prod) in #vfs-platform-support. After deploy, validate that the URL redirect is deployed. (Note: In the event of a facility closure or a name change,  validate that this occurs before making the Lighthouse csv changes.)
- [ ] Update this ticket with a comment that the redirect has been deployed.

#### URL Redirect
| Current URL  |  Redirect Destination or New URL |
| ---  |  --- |
| https://www.va.gov/find-locations/facility/vba_372 | https://www.va.gov/national-capital-region-va-regional-benefit-office |
| https://www.va.gov/find-locations/facility/vba_362 | https://www.va.gov/houston-va-regional-benefit-office |
| https://www.va.gov/find-locations/facility/vba_339 | https://www.va.gov/denver-va-regional-benefit-office |
| https://www.va.gov/find-locations/facility/vba_442 | https://www.va.gov/cheyenne-va-regional-benefit-office |

### 1. Canonical URL change

**Note: Canonical URL changes do not block the completion of the parent ticket. Once the URL redirect above has been deployed, the value to the Veteran is delivered. This ticket should be kept open until the URL change is verified, except in the case of a removal (as described below).**

### Instructions for canonical URL change
- [x] Verify that the new URL for the facility is published and accessible on VA.gov.
- [x] Contact Lighthouse via Slack at #cms-lighthouse channel that this facility requires a canonical link in the following format (replacing the placeholder data with the actual API Id and VA.gov URL):
| `vba_372` | https://www.va.gov/national-capital-region-va-regional-benefit-office |
| `vba_362` | https://www.va.gov/houston-va-regional-benefit-office |
- [ ] Add the "Awaiting CSV" flag to the facility node with a revision log message that includes a link to this ticket.
- [ ] Let Help desk know this has been done, if not done by Help desk.

#### Wait (days or weeks, potentially)
- [ ] After the canonical link has been added to the websites.csv and you have confirmation from Lighthouse that the CSV has been deployed, validate that the change has deployed by checking that the Facility Locator has been updated with the new url.
- [ ] Update this ticket with a comment that the CSV change has been deployed.

**Comment by eselkin** [comment]
All of these come back as the modernized website from LH in their respective "website" value already, so I'm not sure we need to ask for the change. @jilladams

**Comment by jilladams** [comment]
We learned yes, the Sandy's DB change will auto-fix the CSV, but we do still want to redirect these in case they've been bookmarked, etc.

**Comment by jilladams** [comment]
Verified the redirects.
