### ISSUE TITLE
[Discharge Upgrade Wizard] DUW Launch Step 1: Add Redirect for existing DUW v1 and allow routes on prod

### ISSUE THREAD

**Issue by chriskim2311** [department-of-veterans-affairs/va.gov-cms#19540]
## Description
We want to launch v2 of DUW and we will redirect v1 to v2. This ticket will also include allowing the routes to be on prod not just staging

### Scope / Impact analysis
_What, if anything, could break as a result of this change?_
_Engineer should assess this when approaching PR._

## Acceptance criteria
- [x] Add redirect to v2 at `/introduction`
- [x] Remove logic restricting routes to lower envs only, which will allow them on prod
- [x] Ensure DUW is findable via VA.gov global search
- [x] Ensure all screens are available as a user goes through the wizard.

**Comment by FranECross** [comment]
@chriskim2311 I added a couple of AC steps... in case you want to bump it up from a 1. Thanks.
