### ISSUE TITLE
Archived facilities appearing on an Operating Status page

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#19552]
## Description
VA Tampa health care has several closed facilities still appearing on [this page](https://www.va.gov/tampa-health-care/status/).

The Tampa VA clinics are good examples, but also https://www.va.gov/houston-health-care/status/
These are all archived, but still show
Houston 3 VA Mobile Clinic
Houston 2 VA Mobile Clinic
Houston VA Mobile Clinic
Houston VA Domiciliary

### User story
> _Describe the audience/user, enhancement or fix, and value / outcome desired._

**AS A**
**I WANT**
**SO THAT**

### Scope / Impact analysis
_What, if anything, could break as a result of this change?_
_Engineer should assess this when approaching PR._

### Roles / assignments
_After functional testing, code review, accessibility review, and design review can happen in parallel._
- [ ] **Functional testing:** 
- [ ] **Code review:** 
- [ ] **Design review:** 
- [ ] **Accessibility review:** 
- [ ] **Product acceptance:** 

## Acceptance criteria
_ACs should capture expected behavior, to inform test plans. Consider devices, documentation updates including KBs, change management, and [content model](https://prod.cms.va.gov/admin/structure/cm_document) when applicable._

- [ ] 
- [ ] Impact analysis is filled out and QA test plan is updated accordingly
- [ ] Does this product have an existing regression test plan?
	- [ ] Yes, link: 
	- [ ] No, regression test plan will be created as part of the work / points in this ticket

**Comment by jilladams** [comment]
Dupe of https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18410

**Comment by omahane** [comment]
Per @jilladams via [Slack](https://dsva.slack.com/archives/C0FQSS30V/p1731013387372109), I stand corrected. The page in question is an operating status page that shouldn't be showing in the first place.
