### ISSUE TITLE
Vet Center name change: FROM Western Oahu Vet Center TO West Oahu Vet Center - AWAITING CSV

### ISSUE THREAD

**Issue by TroyCMSSupport** [department-of-veterans-affairs/va.gov-cms#19558]
## Vet Center, Outstation, Mobile Vet Center facility name change - Description
Vet Centers, Mobile Vet Centers, and Vet Center Oustations may all be subject to name changes in VAST. Not all steps apply to each type of facility -- please pay attention and make sure you've done the relevant steps based on facility type.

## Intake
- [x] What triggered this runbook? (Flag in CMS, Help desk ticket, Product team, VHA Digital Media)
Trigger: **Flag in CMS**

- [x] Link to associated help desk ticket (if applicable)
Help desk ticket: https://va-gov.atlassian.net/browse/VAHELP-8115 

- [x] Name of submitter (if applicable)
Submitter: Edmond.DeGuzman@va.gov

- [x] If the submitter is an editor, send them links to any relevate KB articles for the Vet Center product. Let them know that facility changes can take between 75 days and 4 months after submitting a request, according to VAST administrators.
KB articles: <insert_kb_article_links>

- [x] Link to facility in production:
Facility CMS link: [Facility Link](https://prod.cms.va.gov/western-oahu-vet-center)
Facility API ID: **vc_0621V**

### CMS help desk steps
**Note: If the help desk is waiting on information from the facility staff or editor, add the "Awaiting editor" flag to the facility** with a log message that includes a link to this ticket. Remove the flag when the ticket is ready to be worked by the Facilities team. **Be sure to preserve the current moderation state of the node when adding or removing the flag.**
- [x] The title (Name of Vet Center field) change comes from Lighthouse to Drupal & is flagged
- [x] If the Vet Center published and is NOT an Outstation/MVC, create a [URL change request](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/new?assignees=&template=runbook-facility-url-change.md&title=URL+Change+for%3A+%3Cinsert+facility+name%3E), changing the entry from the old facility URL to the new facility URL. (**Note: The URL change request ticket blocks the completion of this ticket.**)

[Redirect Request link](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19559)

### CMS engineer steps - Vet Center only (not Outstation/MVC)
- [x] Execute the steps of the URL change request ticket from step 2.

(Redirects deploy daily except Friday at 10am ET, or by requesting OOB deploy (of the revproxy job to prod) in #vfs-platform-support. Coordinate the items below and canonical URL change after URL change ticket is merged, deployed, and verified in prod.)

### Drupal Admin steps (CMS Engineer or Help desk)
_Help desk will complete these steps or escalate to request help from CMS engineering._

**If a Vet Center**

***CASE: Renamed, but still location-based naming convention***

- [x] If the new official name matches the pattern "<city> Vet Center", update the common name to match.
- [x] Visit [bulk operations](https://prod.cms.va.gov/admin/content/bulk) page and filter by section = old vet center name
- [x] Update URLs for all content in that section by bulk operations
- [x] Resave all content in that section by bulk operations

***CASE: Renamed***
- [x] Visit [bulk operations](https://prod.cms.va.gov/admin/content/bulk) page and filter by section = old vet center name
- [x] Select all
- [x] Choose "Modify values"
- [x] Change Section to new Section name
- [x] Execute
- [x] Visit [Users](https://prod.cms.va.gov/admin/people)
- [x] Filter by Section = old vet center name
- [x] Update users to new Section
- [x] Go to [Section](https://prod.cms.va.gov/admin/structure/taxonomy/manage/administration/overview) taxonomy
- [x] Delete old vet center name term
 
**For all types**
- [x] Edit the Vet Center node by removing flag `Changed name`, and saves the node (with moderation state = published)

#### CMS Help desk (wrap up)
- [x] Notify editor and any other stakeholders.

**Comment by ian-sears** [comment]
CSV in the URL change request completed.
Redirect resolvs correctly.
All Bulk Edit conversions from Western to West have been completed without issue.

JIRA-8115 Editor has been notified, all is complete.
@department-of-veterans-affairs/platform-cms-helpdesk FYSA
VA CMS Help Desk
