### ISSUE TITLE
CLP: draft content going to prod

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#19551]
## Description
A campaign landing page has a draft change in the first promo block under "What you can do" did roll out to production last night despite being saved as draft:
https://www.va.gov/initiatives/prepare-for-vas-secure-sign-in-changes/ 

### Technical notes
CLP promos use the Custom block type: Promo. 
Blocks don't have an editorial workflow.

## Acceptance criteria

- [ ] CLPs in the front-end only display published content
- [ ] We understand the mechanism by which this occurred, and comment with an assessment of what else may need to be reviewed

**Comment by omahane** [comment]
@jilladams From what I understand of [this comment](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19535#issuecomment-2423412297), it was determined that we don't have a Drupal-sourced issue at play. I'm I reading this wrong?

**Comment by omahane** [comment]
I found this conversation and see the issue: https://dsva.slack.com/archives/C07SFHRM745/p1729352044450959

**Comment by omahane** [comment]
Based on conversation with @edmund-dunn and my own analysis, we've determined that the inconsistencies with publishing appear to be related to entity reference fields and the way they are referenced.

**Comment by jilladams** [comment]
Noting: these promos use Blocks, which do not have an Editorial workflow, and can't be saved independently as Draft.

https://dsva.slack.com/archives/C07SFHRM745/p1729550800092079?thread_ts=1729287978.261209&cid=C07SFHRM745

Campaign Landing Pages > What you can do section:  What you can do promos:  This section of the CLP form is using Blocks, which do not have an Editorial workflow.
So for example:
* https://prod.cms.va.gov/node/63686/edit - this contains 3 promos that were created from within the context of the CLP form
* You can also find those promos / prove they are blocks by looking at them here:
  * https://prod.cms.va.gov/admin/content/block/276
  * https://prod.cms.va.gov/admin/content/block/278
  * https://prod.cms.va.gov/admin/content/block/277

When you are creating a new CLP with new promos this probably doesn't matter, but once a CLP is live, blocks don't provide a way to do drafts. So even though you might edit a block-in-the-context-of-a-CLP, and save the CLP as a Draft: Blocks themselves don't have a draft state. I dunno how that works in terms of publishing (are blocks Published by default?)

**Comment by jilladams** [comment]
We may also need to update the CLP KB related to promos. 
* don't set promos as published until you're read for the changes to go to the front-end
* You will have to separately adjust the state of the Promo block (draft/published)

**Comment by omahane** [comment]
@edmund-dunn  I have tested the configuration changes you made and have captured the test results in this [spreadsheet](https://docs.google.com/spreadsheets/d/1SusGkPNpdVSrA8ki12Pttz4kOgax9dmReJJFiqazeHE/edit?gid=0#gid=0). I think you're on the right path. Blocks in draft don't show on the front end. The node:edit of the block is showing the default revision, which actually may be right. It's a toss up. I can see how as an editor, if I haven't saved the block as published then maybe I shouldn't see the changed on the node:edit of the CLP on the premise that what is displayed is the default revision and that to see the latest requires clicking "Edit". That would be a change to note and communicate to the editors, though. 

CLP node:edit
![Image](https://github.com/user-attachments/assets/9fa32450-5673-41a4-9706-e823074927eb)

**Comment by jilladams** [comment]
The folks who create CLPs are mostly digital comms folks from other VA bureaus, and sometimes CAIA, so they're not Drupal pro users. If we change the behavior for previewing / seeing Draft changes, we need to update the related CLPs (and probably need technical notes on what exactly changed). Imo it's not a dealbreaker if it solves this, but It's ultimately a product call for @FranECross  / @mmiddaugh . 

If we were to say that this Node View showing Latest Revision (instead of draft revisions) is ok: would Edmund's solution be ready to PR?

**Comment by jilladams** [comment]
@edmund-dunn Christian noted that you were checking on your change with CAIA and may have news. We are tracking this ticket in our sprint, and wondering if it should be reassigned to you / tracked in the CMS board, if you have a fix in the works? 

cc @gracekretschmer-metrostar

**Comment by edmund-dunn** [comment]
@jilladams I will be following up with them today.

**Comment by edmund-dunn** [comment]
@jilladams I spoke with Randi Hecht and showed her the changes. She thinks they are good to go. Also ran them past @MDomngz who approved of them from a UX perspective. 

@omahane the necessary patches and changes to `composer.json` are pushed in your working banch. 

@gracekretschmer-metrostar CC

**Comment by omahane** [comment]
I'm testing this locally. Should I not see any issues, I'll put up a PR.

**Comment by omahane** [comment]
@laflannery @davidmpickett @thejordanwood 
We are using a different widget to solve this problem, moving from Inline Entity Form to Entity Browser. @edmund-dunn has patched the module to allow us to show the latest revision in the form widget. He has reviewed the solution with UX from his team, but I wanted to run this by you to make sure you don't see any issue. I'm doing this now, as opposed to when the PR is ready to review because the UX changes are breaking Cypress. If I make those changes, but it turns out we wanted a different solution to this anyway, it's going to mean rewriting the Cypress tests again.

Here's a page to test:
https://pr19640-4ikhsvndhlpcaaab3uhii2cuoabehwrm.ci.cms.va.gov/node/39911/edit
1. Go to **What you can do**
2. Click to expand it
3. Note the differences from production
![Image](https://github.com/user-attachments/assets/bf2717e1-e799-408f-97ff-45e99e68cfec)
4. Click the **Place promo** button
5. Note the use of a tabbed interface to either add an existing or make a new promo
![Image](https://github.com/user-attachments/assets/de8fc6e0-af56-446b-b028-0b0ce2f6ef3c)


You can also create a new CLP, of course.

**Comment by laflannery** [comment]
I took a look and while there are definitely accessibility issues here, the majority are not new to Drupal, they are existing within the overall product already (e..g. focus management, missing table headers, etc.). There is only 1 that is specific to this situation that we should address here before shipping:

- The "show row weights" button is missing so the only way I have to reorder the promos is by dragging and dropping.

**Comment by omahane** [comment]
@edmund-dunn 
I am looking at this and have found the JS that is breaking the modal for non-admins, but I don't understand why/how. What's weird is that Entity Browser uses 2 custom AJAX callbacks. One is working but the other isn't. 
- `entity_browser/js/entity_browser.modal.js`: ✅ working
- `entity_browser/js/entity_browser.common.js`: ❌ not working

Because the `entity_browser.modal.js` is not working, it is causing the improperly sized modal and the inability to place an existing promo block:
![Image](https://github.com/user-attachments/assets/a4d11a38-72d8-44df-bdd5-b5fc862f894f)

They both appear to be called only when the page is loaded by a non-admin. But in the case of the broken one, the AjaxCommands object doesn't appear to exist:
![Image](https://github.com/user-attachments/assets/187e801f-7a9c-4999-86bf-c48b5c716295)

While I've found the offending JS, I don't know why it's offending.

**Comment by omahane** [comment]
The other remaining issue is the "Place Block" button, which does not show when the 3rd block has been removed. It only shows after the node has been saved and is reloaded.

**Comment by omahane** [comment]
# Proposed fix for the breaking AJAX
When I added to the contrib module the AJAX library in the dependencies, the issue no longer presented itself when editing as a non-admin (and didn't regress for admins either).

I changed this file:
- `/contrib/entity_browser/entity_browser.libraries.yml`
- Adding `    - core/drupal.ajax` on line 65
- Now, lines 58 - 69 are as follows:
```
modal:
  css:
    component:
      css/entity_browser.modal.css: {}
  js:
    js/entity_browser.modal.js: {}
  dependencies:
    - core/drupal.ajax
    - core/drupalSettings
    - core/drupal
    - core/once
    - core/jquery
 ```

@edmund-dunn This will need to be added to the patch. (But could you hold off until we have a solution to the following issue?)

# Place Promo button does not show after 3rd promo block is removed
- When loading a CLP with 3 promo blocks in What You Can Do, removing one does not show the **Place Promo** button.
- You have to save and reload the edit form to see the **Place Promo**
- This is a regression from the IEF

**Comment by omahane** [comment]
# Continuing saga of the remove button
## On prod
We have Events on Campaign landing pages using Entity Browser.
- Cardinality: 2
- After adding 2 events, the "Select Event" button goes away.
- When we remove an event, the button reappears.

## On PR env
We have Events on Campaign landing pages using Entity Browser.
- Cardinality: 2
- After adding 2 events, the "Select Event" button goes away.
- When we remove an event, the button is still absent.

I have a video that shows this:
https://www.loom.com/share/78d0572df9034d5293a0df5b47bf1bda?sid=b14b270f-5a25-47ce-bf1a-815976081618

## Conclusion
I believe that the code we incorporated from the patch on https://www.drupal.org/project/entity_browser/issues/2851580 is breaking the expected remove functionality.

**Comment by omahane** [comment]
# Row weight issue
From @laflannery via [Slack](https://dsva.slack.com/archives/C0FQSS30V/p1731001101126429?thread_ts=1730999946.987189&cid=C0FQSS30V)
> Everything worked fine for me, there are accessibility issues but only 1 that is not already existing within the greater Drupal situation that we should address here before shipping:
The "show row weights" button is missing so the only way I have to reorder the promos is by dragging and dropping.

**Comment by omahane** [comment]
## Remove block III: This time it's personal
I figured out the remove block failure on Promos.

`/va_gov_workflow/src/EventSubscriber/EntityEventSubscriber.php`
- `getIefTypeFields()`  has a call to `isNodeIef()`, which bypasses Revision log validation on IEFs that target nodes but not content blocks.
- So I'm making a very minor change to make it true for blocks, too. (May need some biggish testing, though).

### Following the data
In the Promos area, using Inline Entity Browser, when clicking the **Remove** button, this is the result in the browser's developer tools network tab.
[xhr-call-events-remove-edit.json](https://github.com/user-attachments/files/17815975/xhr-call-events-remove-edit.json)
 
That last bit gets parsed to:
```
<div class="item-list--comma-list item-list">
  <ul class="item-list__comma-list">
    <li>
      <a href="#edit-revision-log-0-value--_b5kQ3IIxkM">Revision log message</a>
    </li>
  </ul>
</div>
```

Meaning that it's requiring a Revision log message during the removal process, which is unnecessary. Plus, that message never shows on the front end.

**Comment by jilladams** [comment]
Nice progress! If biggish testing means you need help, holler in scrum and we can sort out help.

**Comment by jilladams** [comment]
@omahane @edmund-dunn possible to get a status added here for our end of sprint reporting purposes? I know the PR is still in flight, but not sure if the Cypress tests are still the issue or where we're at with it.

**Comment by jilladams** [comment]
@omahane @laflannery Testing done on FE, results are green: https://docs.google.com/spreadsheets/d/1Nc9knpZZAFsM_n0JexJEkO5nZvfGmlHrtTKnHpZYyMQ/edit?gid=0#gid=0

Let me know if you have other quesitons, otherwise: i think you're good to merge, if PR is in good shape

**Comment by jilladams** [comment]
This work is now deployed to production. I'm closing, and notified CAIA in the private #temp-drafts-publishing channel: https://dsva.slack.com/archives/C07SFHRM745/p1733785547495569
