### ISSUE TITLE
URL Change for: FROM Western Oahu Vet Center TO West Oahu Vet Center - AWAITING CSV

### ISSUE THREAD

**Issue by TroyCMSSupport** [department-of-veterans-affairs/va.gov-cms#19559]
Parent ticket: #number-of-GH-ticket
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19558

### Implementation date
When does this request need to be live:
ASAP

### Instructions for URL redirect
(Note: This issue will be used from initial request through implementation to ensure all individuals working on this are notified of status updates.  Please do not create multiple issues to track different steps.)
- [x] Notify VA stakeholders as appropriate.
- [x] Link the related facility closure / rename issue.
- [x] Create a URL redirect in the [vsp-platform-revproxy](https://github.com/department-of-veterans-affairs/vsp-platform-revproxy) repo in `template-rendering/revproxy-vagov/vars/redirects.yml`
- [x] Add the "Awaiting redirect" flag to the facility node with a revision log message that includes a link to this ticket, preserving the node's current moderation state.
- [x] Redirects deploy daily except Friday at 10am ET, or by requesting OOB deploy (of the revproxy job to prod) in #vfs-platform-support. After deploy, validate that the URL redirect is deployed. (Note: In the event of a facility closure or a name change,  validate that this occurs before making the Lighthouse csv changes.)
- [x] Update this ticket with a comment that the redirect has been deployed.
- [x] Remove the "Awaiting redirect" flag on the facility node with a revision log message that includes a link to this ticket, preserving the node's current moderation state.
- [x] Notify helpdesk via comment on ticket or Slack message in #cms-support that changes are ready for review.

#### URL Redirect
| Current URL  |  Redirect Destination or New URL |
| ---  |  --- |
| https://www.va.gov/western-oahu-vet-center | https://www.va.gov/west-oahu-vet-center |

### 1. Canonical URL change

**Note: Canonical URL changes do not block the completion of the parent ticket. Once the URL redirect above has been deployed, the value to the Veteran is delivered. This ticket should be kept open until the URL change is verified, except in the case of a removal (as described below).**

### Instructions for canonical URL change
- [x] Verify that the new URL for the facility is published and accessible on VA.gov.
- [x] Contact Lighthouse via Slack at #cms-lighthouse channel that this facility requires a canonical link in the following format (replacing the placeholder data with the actual API Id and VA.gov URL):
  - `vc_0621V,https://www.va.gov/west-oahu-vet-center/`
- [x] Add the "Awaiting CSV" flag to the facility node with a revision log message that includes a link to this ticket.
- [x] Let Help desk know this has been done, if not done by Help desk.

#### Wait (days or weeks, potentially)
- [x] After the canonical link has been added to the websites.csv and you have confirmation from Lighthouse that the CSV has been deployed, validate that the change has deployed by checking that the Facility Locator has been updated with the new url.
- [x] Update this ticket with a comment that the CSV change has been deployed.

#### URL change example (update with actual ID and URL)
| Facility API ID  |  Full VA.gov URL |
| ---  |  --- |
|vc_0621V | https://www.va.gov/west-oahu-vet-center |

**Comment by TroyCMSSupport** [comment]
@ian-sears @omahane @jilladams  - Updated this issue with final detail - Please let me know if I've overlooked anything.

**Comment by TroyCMSSupport** [comment]
Awaiting CSV per Slack https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19558

**Comment by jilladams** [comment]
Doh, sorry: workflow automation. Reopening.

**Comment by ian-sears** [comment]
Flag removed: Awaiting CSV
CSV has been deployed. Redirect resolves.
GH Parent - https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19558
JIRA-8115 Editor has been notified, all is complete.
@department-of-veterans-affairs/platform-cms-helpdesk FYSA
VA CMS Help Desk
