### ISSUE TITLE
SPIKE: VBA event creation for National Outreach calendar

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-cms#19563]
## Description
Event functionality has not yet been enabled for use by VBA/Regional office editors due to content build constraints. A national editor  needs to be able to add VR&E events (which are national or through a Regional Office) without selecting a VAMC as the listing page. 

Is there an interim way to enable this functionality without enabling the feature for the entire group of VBA editors?

### User story
> _Describe the audience/user, enhancement or fix, and value / outcome desired._

**AS A** Outreach editor with VBA
**I WANT** to create events in Drupal
**SO THAT** I can add them to the national calendar. 

### Engineering notes / background
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13527 - epic where we established the national outreach calendar checkbox on Events.

## Acceptance criteria
- [ ] Assess how to enable VBA to create Events on the Outreach Events (VEO) event listing, in a world where VBA editors cannot create an Event associated with a Regional Office / publish to a VBA page yet
- [ ] Document what permissions / roles may need to be added / adjusted to enable the VBA-as-Outreach-Editor flow
- [ ] Document recommended path forward

**Comment by jilladams** [comment]
A short run around getting Events set up for full VBA use might be: give VBA editors Outreach and Event section / Event create/edit permissions only. They could then create Events to put on the Outreach Events listing directly, and skip the entire question of making those events appear on VBA regional office pages, until we figure out the rest of it / can do it in AP. 

@davidmpickett this may be a thing we could ask for your help to think about? Does that seem totally wacky?

**Comment by jilladams** [comment]
While we're here and I mulled it, just writing down what I think I know about the bigger picture to more properly enable VBA events: 

**State of affairs in production:** 
* "Where should the event be listed?" on an event page will show the editor the Listings where they have permissions to post an Event: https://prod.cms.va.gov/node/add/event
* Event Listings must be associated a VAMC system or Office: https://prod.cms.va.gov/node/add/event_listing
* Any Event can be added to the National Outreach Calendar using the checkbox (Once VBA can make events properly, this piece should just come along for the ride.)

**Big picture: What would need to change to enable Events for VBA generally:** 
* Event Listings "where should the event be listed?" needs to be expanded to be associated with VBA Facilities (including ROs)
* IA work for event listings / events needs to get settled for VBA events
* VBA editors need Event create / publish/ etc etc permissions.
* There's sections work in there.

**Comment by davidmpickett** [comment]
> @davidmpickett this may be a thing we could ask for your help to think about? Does that seem totally wacky?

Working through permissions possibilities is totally up my alley as a Content Designer ;)

**Comment by jilladams** [comment]
Per Product Sync:
* Michelle is interested in the VBA-as-Outreach-Events role fix for this, short term/ til we can enable VBA events properly
* If this requires a bunch of weird / large / artisanal work: Michelle is also ok pushing back and saying: you're gonna have to wait for full Events implementation
* This ticket is now framed as a content modeling / permissions SPIKE to figure out: 
  * Is this end run a good idea? 
  * How could it / should it work, if so

@mmiddaugh will provide a link to the relevant Editor in the CMS who is the example for what existing permissions are for this person / to identify the gap / plan for how to enable Events creation on Outreach events. 

@davidmpickett we'll likely pull this into next sprint if you have capacity. Feel free to take a stab at points.

**Comment by davidmpickett** [comment]
Do we have a specific list of users who would need this functionality?

**Comment by davidmpickett** [comment]
These VBA national editors have been granted the role Content creator - Outreach Hub and added to the Outreach Hub section.
- [Tanekwa](https://staging.cms.va.gov/user/1797)
- [Kenyonna](https://staging.cms.va.gov/user/2967)

Why would this solution not work for these editors?

**Comment by FranECross** [comment]
Jill has asked Michelle for the CMS user so that we can see what their current permissions are, and perhaps is there a combo of permissions we can add to this person that won't affect other folks?

**Comment by jilladams** [comment]
Related thread: https://dsva.slack.com/archives/C52CL1PKQ/p1730147202190199 

Given that for the Editor Michelle mentioned, https://prod.cms.va.gov/user/4852, there are older Helpdesk tickets specifically requesting the Outreach Hub section access (([VAHELP-7385](https://va-gov.atlassian.net/browse/VAHELP-7385#icft=VAHELP-7385),  [VAHELP-7441](https://va-gov.atlassian.net/issues/VAHELP-7441?jql=summary%20~%20%22Peter.Granato%40va.gov%22%20OR%20description%20~%20%22Peter.Granato%40va.gov%22%20ORDER%20BY%20created%20DESC))), Helpdesk has added the Outreach Hub section that user. 

We are waiting to hear if that was the only Editor we needed to account for -- if so, this ticket can close. If not, we'll need to come back to it and assess the other editors / if they can just get that role, or there's more to this.

**Comment by jilladams** [comment]
Per Michelle, that's good enough for now. Closing.
