### ISSUE TITLE
Next Build Template: R&S Checklist

### ISSUE THREAD

**Issue by gracekretschmer-metrostar** [department-of-veterans-affairs/va.gov-cms#19579]
## Template or Content Type
R&S Checklist

## Example
_URL to show an example of the template or content type in both Drupal CMS and VA.gov_

## Description
_Overview of template or content type, including relevant details to the migration lift._

## Owning Team 
_The team that is owning either the review, fixes, or deployment of template or content type into production_

## Definition of Done
- [ ] _What must be true in order for you to consider this epic complete?_

**Comment by jilladams** [comment]
Randi is working this migration in https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19386, in progress now.

**Comment by jilladams** [comment]
Closing as a dupe.
