### ISSUE TITLE
[Discharge Upgrade Wizard] Results page is missing text on Step 3 for the Army logic flows for service '> 15 years' prior

### ISSUE THREAD

**Issue by davidmpickett** [department-of-veterans-affairs/va.gov-cms#19599]
## Status
**[2024-11-07] [Fran]** Research sessions have concluded; no longer blocked.

## Description
Step 3 of the subway map is not always filling in the area after "you must apply to" when the branch of the military is Army, and service is 15 years or more ago.

On Staging (noted in the scenario in Steps to Reproduce) there is missing text in the first paragraph, just after the Step 3 title: **Mail your completed form and all supporting materials**

- **Prod's paragraph shows:**  "There are a number of different boards that handle discharge upgrades and corrections. Based on your answers on the previous page, you need to apply to the BCMR for the Army. This is because the Board handles all cases from 15 or more years ago."

![Image](https://github.com/user-attachments/assets/ffa2604f-9ac6-4c2a-8962-0c67d52246e8)

- **Staging's paragraph shows:** "There are a number of different boards that handle discharge upgrades and corrections. Based on your answers on the previous page, you need to apply to"

![Image](https://github.com/user-attachments/assets/57976037-cd23-4e16-bdd5-7de934e6bcb5)

## Steps to recreate

**Version of DUW**
- https://staging.va.gov/discharge-upgrade-instructions
- https://www.va.gov/discharge-upgrade-instructions/

**Answers**
- Army
- 2009
- April
- Reasons for discharge (note that if reason wanting to change is transgender, the info isn't missing):
  - I suffered from an undiagnosed, misdiagnosed...PTSD... AND
  - I suffered from an undiagnosed, misdiagnosed...TBI... AND
  - I was discharged due to my sexual orientation, AND
  - I experienced sexual assault or harassment during my service, AND
  - No, I want to change only my characterization of discharge, re-enlistment code, separation code, or narrative reason for discharge, AND
  - No, I want to change only my characterization of discharge, re-enlistment code, separation code, or narrative reason for discharge.
- No, I want to change only my characterization...
- No, my discharge was administrative...
- I have not previously applied
- No, I didn't complete earlier period of service

### Scope / Impact analysis
_What, if anything, could break as a result of this change?_
_Engineer should assess this when approaching PR._

### Roles / assignments
_After functional testing, code review, accessibility review, and design review can happen in parallel._
- [ ] **Functional testing:** 
- [ ] **Code review:** 
- [ ] **Design review:** 
- [ ] **Accessibility review:** 
- [ ] **Product acceptance:** 

## Acceptance criteria
_ACs should capture expected behavior, to inform test plans. Consider devices, documentation updates including KBs, change management, and [content model](https://prod.cms.va.gov/admin/structure/cm_document) when applicable._

- [ ] for logic flow where the Veteran needs to submit to BCMR, AND military branch is Army, the first paragraph just after the Step 3 title: **Mail your completed form and all supporting materials** should be: "There are a number of different boards that handle discharge upgrades and corrections. Based on your answers on the previous page, you need to apply to the BCMR for the Army. This is because the board handles all cases from 15 or more years ago.." 
- [N/A] Does this product have an existing regression test plan? Not yet. A regression plan will NOT be created as part of this ticket.

**Comment by FranECross** [comment]
@chriskim2311 I see that there are other military branches (Navy, etc.) that are also missing text from the results page. Do you want one ticket for each branch of service that needs correction, or just this ticket with all the changes in it? Thanks.

**Comment by chriskim2311** [comment]
@FranECross Thanks for catching these. One ticket is fine just list all the changes needed and I'll address them.

**Comment by jilladams** [comment]
@FranECross this should land in Staging today for verification / closing

**Comment by FranECross** [comment]
Verified  using all answers for Question 3: Tell us why you want to change your discharge paperwork. and the happy path of more than 15 years ago, as well as outside the happy path of within 15 years. Closing
