### ISSUE TITLE
Move Accessibility Board into CMS Board

### ISSUE THREAD

**Issue by gracekretschmer-metrostar** [department-of-veterans-affairs/va.gov-cms#19590]
## User Story or Problem Statement
As the Accessibility Specialist on the CMS team, I want to get the accessibility backlog in better alignment with current CMS sprint ceremonies and tracking. 

## Description or Additional Context 
 The current CMS Accessibility backlog lives in it's own board, but we are engaging with it during our sprint ceremonies, so we are going to pull that board back into the CMS board, so that it can get more focus and attention from the CMS team. 

## Relevant Links
- [CMS board](https://github.com/orgs/department-of-veterans-affairs/projects/1194)
- [CMS Accessibility Board](https://github.com/orgs/department-of-veterans-affairs/projects/1246)

## Steps for Implementation
- Steve to partner with @LisaLindsey to understand how views work in Github Projects 

## Acceptance Criteria
- [ ] Tickets within the CMS Accessibility board has been folded back into the CMS board and an accessibility view has been created. 
- [ ] CMS Accessibility Board has been retired.

**Comment by srancour** [comment]
Created a [view in the CMS project](https://github.com/orgs/department-of-veterans-affairs/projects/1194/views/9) so the accessibility project can now be closed
