### ISSUE TITLE
Implement Drupal Community of Practice (CoP)

### ISSUE THREAD

**Issue by gracekretschmer-metrostar** [department-of-veterans-affairs/va.gov-cms#19605]
## User Story or Problem Statement
As a drupal engineer, I need support in Drupal best practices and approaches from the drupal engineers at OCTO. 

As a member of of the CMS team, I need to understand how CMS wants to approach leading a drupal community of practice for OCTO. 

## Description or Additional Context 
 @edmund-dunn Identified that there's a concentration of Drupal knowledge across CMS and Sitewide, between himself, Daniel, and Tim. Is there an opportunity to create a more formalized structure to provide Drupal guidance and support. 

Per Andrea:
> just chatted with Edmund about a Drupal COP
I know you talked about it already -- want to put in a ticket for the next sprint or two so we can carve out time to work on it?
I'm digging with other COP leads to figure out what all they do but I love the idea

Per Erika:
> Hey! I wanted to share this with you. Daniel from the sitewide team has finished his ECA framework and laid out estimates for using that framework for a variety of actions based on a list Michelle and I provided as important. There may be options here for our team to learn this framework and set up some ECAs on our own. This would be Drupal specific work. https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18737#issuecomment-2443062845
I also think this sort of thing would be a good candidate to share in the new Drupal CoP

## Steps for Implementation
- Create a slack channel
- Create a bi-weekly meeting 
- Create a structured understand of what a Drupal CoP

## Acceptance Criteria
- [x] A meeting and communication structure has been created for the Drupal Community of Practice.

**Comment by gracekretschmer-metrostar** [comment]
@edmund-dunn Can you fill out the Steps for Implementation section of this ticket?

**Comment by gracekretschmer-metrostar** [comment]
@LisaLindsey will help support building a ticketing workflow from tickets that come out of these meetings.

**Comment by edmund-dunn** [comment]
Slack channel: https://dsva.slack.com/archives/C081MPLQNHK

Meeting will be every other Thursday at 9:30am PT starting on 5 Dev 2024.
