### ISSUE TITLE
Spike: EWA treatment for entity "Edit" form

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#1960]
## User story

As a content editor, I want to see unified editorial experience when I switch from the content "view" to content "edit" page.

## Acceptance criteria

- [ ] discuss potential treatments for "edit" forms. e.g. Actions widget, other meta information, layout
- [ ] groom resulting tickets

**Comment by swirtSJW** [comment]
Closing this as a vapor idea that is no longer here.
