### ISSUE TITLE
URL Change for: Brunswick VA Clinic - DUBLIN - CLOSURE (Awaiting REDIRECT)

### ISSUE THREAD

**Issue by TroyCMSSupport** [department-of-veterans-affairs/va.gov-cms#19624]
Parent ticket: #[19269](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19269)

### Implementation date
When does this request need to be live:
ASAP

### Instructions for URL redirect
(Note: This issue will be used from initial request through implementation to ensure all individuals working on this are notified of status updates.  Please do not create multiple issues to track different steps.)
- [x] Notify VA stakeholders as appropriate.
- [x] Link the related facility closure / rename issue.
- [x] Create a URL redirect in the [vsp-platform-revproxy](https://github.com/department-of-veterans-affairs/vsp-platform-revproxy) repo in `template-rendering/revproxy-vagov/vars/redirects.yml`
- [x] Add the "Awaiting redirect" flag to the facility node with a revision log message that includes a link to this ticket, preserving the node's current moderation state.
- [x] Redirects deploy daily except Friday at 10am ET, or by requesting OOB deploy (of the revproxy job to prod) in #vfs-platform-support. After deploy, validate that the URL redirect is deployed. (Note: In the event of a facility closure or a name change,  validate that this occurs before making the Lighthouse csv changes.)
- [x] Update this ticket with a comment that the redirect has been deployed.
- [x] Remove the "Awaiting redirect" flag on the facility node with a revision log message that includes a link to this ticket, preserving the node's current moderation state.
- [x] Notify helpdesk via comment on ticket or Slack message in #cms-support that changes are ready for review.

#### URL Redirect
| Current URL  |  Redirect Destination or New URL |
| ---  |  --- |
| https://www.va.gov/dublin-health-care/locations/brunswick-va-clinic | https://www.va.gov/charleston-health-care/locations/brunswick-va-clinic |

### 1. Canonical URL change

**Note: Canonical URL changes do not block the completion of the parent ticket. Once the URL redirect above has been deployed, the value to the Veteran is delivered. This ticket should be kept open until the URL change is verified, except in the case of a removal (as described below).**

### Instructions for canonical URL change
- [x] Verify that the new URL for the facility is published and accessible on VA.gov.
- [x] Contact Lighthouse via Slack at #cms-lighthouse channel that this facility requires a canonical link in the following format (replacing the placeholder data with the actual API Id and VA.gov URL):
  - `vha_557GE,https://www.va.gov/charleston-health-care/locations/brunswick-va-clinic/`
- [x] Add the "Awaiting CSV" flag to the facility node with a revision log message that includes a link to this ticket.
- [x] Let Help desk know this has been done, if not done by Help desk.

#### Wait (days or weeks, potentially)
- [x] After the canonical link has been added to the websites.csv and you have confirmation from Lighthouse that the CSV has been deployed, validate that the change has deployed by checking that the Facility Locator has been updated with the new url.
- [x] Update this ticket with a comment that the CSV change has been deployed.

#### URL change example (update with actual ID and URL)
| Facility API ID  |  Full VA.gov URL |
| ---  |  --- |
| vha_557GE | https://www.va.gov/charleston-health-care/locations/brunswick-va-clinic/ |

### Instructions for canonical URL removal
- [x] Try to find the facility via the Facility Locator, using the Facility API ID (e.g. https://va.gov/find-locations/facility/"facility_api_id"). If it is not available, proceed.
- [x] Contact Lighthouse via Slack at #cms-lighthouse channel that this facility requires a canonical link to be removed in the following format (replacing the placeholder data with the actual API Id and VA.gov URL):
  - `vha_557GE,https://www.va.gov/charleston-health-care/locations/brunswick-va-clinic/`

**Note: there's no check to see if it's not returning anything, as it should already be not showing anything in the Facility Locator.**

**Comment by TroyCMSSupport** [comment]
@omahane @ian-sears -- 
Should this redirect move forward so that the Dublin / Brunswick site can be archived? 
The NEW Brunswick site (under Charleston) is already in place - 
Your thoughts? Suggestions?

**Comment by omahane** [comment]
@department-of-veterans-affairs/platform-cms-helpdesk The PR for this redirect is being reviewed.

**Comment by omahane** [comment]
@department-of-veterans-affairs/platform-cms-helpdesk The redirect has been merged and should deploy tomorrow.

**Comment by ian-sears** [comment]
Redirect resolves.
We @department-of-veterans-affairs/platform-cms-helpdesk reached out to the (new) editor in VA Charleston health care to add helath services to the new charleston Brunswick facility.
We had mistakenly been reaching out to the (old) dublin editor requesting this which dragged out timliness of getting that done.
**Awaiting Editor to add these health services.**

Requested websites.csv removal of the old vha_557GE https://www.va.gov/dublin-health-care/locations/brunswick-va-clinic/
 [here in #cms-lighthouse](https://dsva.slack.com/archives/C02BTJTDFTN/p1733441360717269?thread_ts=1733440827.767909&cid=C02BTJTDFTN)

The new vha_534GG https://www.va.gov/charleston-health-care/locations/brunswick-va-clinic/ has already been added to the websites.csv

**Comment by ian-sears** [comment]
UPDATE: I am deeply concerned, however, that the Basic Location data for this new Brunswick location may not be at all correct. CMS Help Desk is inquiring with the Editor to confirm accuracy.
If I understand correctly, Brunswick (Dublin) vha_557GE in VISN 07 Georgia
is the change TO this new Brunswick (Charleston) vha_534GG in the VISN 07 South Carolina

Currently the address is the same (Brunswick, GA) in both facility pages.
Inquiring with Editor to confirm intended correct information.

**Comment by ian-sears** [comment]
UPDATE from the Editor this morning on the possibly incorrect VAST Basic Location Data:
john.langevin@va.gov 
December 6, 2024 at 10:39 AM

Good morning,  

The address is correct but the phone number is not.  

I will put in the request for the update.  

John “Parker” Langevin  Digital Content Manager  
Ralph H. Johnson VA Health Care System 
109 Bee Street, Charleston, SC 29401

**Comment by ian-sears** [comment]
Status Update:
While this is basically "done", I am keeping this open because I do NOT (yet) see evidence of a VAST request to have the previous Brunswick site (vha_557GE) CLOSED. We've reached out to the editor john.langavin asking him to look into whetehr this request was ever made to VAST. Awaiting response from Editor in [JIRA VAHELP-7891](https://va-gov.atlassian.net/browse/VAHELP-7891)
tagging @department-of-veterans-affairs/platform-cms-helpdesk fysa

**Comment by TroyCMSSupport** [comment]
@ian-sears @jilladams @omahane  - Closing as complete.
