### ISSUE TITLE
Increased character limit on Alert body in VAMC Banner with Situation Update

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#19637]
## Description

In the world of Alternative Banners, links to pages may 404 until the related page makes its way through content-build. In light of that VHA DM may have need to create banners that publish the alternative route, the length of the Alert Body itself may need to be longer to support the content that would otherwise live in another link. 

Current character count: 300 characters

Increased character count: needs to be determined by product. 

### Considerations
* Once the rest of the banner / situation updates can be published via AP or otherwise faster than content-build: this character count should roll back to 300
* We need to be mindful of design / FE presentation for any increased length, especially in the case of non-dismissable banners

### Scope / Impact analysis
_What, if anything, could break as a result of this change?_
_Engineer should assess this when approaching PR._

### Roles / assignments
_After functional testing, code review, accessibility review, and design review can happen in parallel._
- [ ] **Functional testing:** 
- [ ] **Code review:** 
- [ ] **Design review:** 
- [ ] **Accessibility review:** 
- [ ] **Product acceptance:** 

## Acceptance criteria
_ACs should capture expected behavior, to inform test plans. Consider devices, documentation updates including KBs, change management, and [content model](https://prod.cms.va.gov/admin/structure/cm_document) when applicable._

- [ ] 
- [ ] Impact analysis is filled out and QA test plan is updated accordingly
- [ ] Does this product have an existing regression test plan?
	- [ ] Yes, link: 
	- [ ] No, regression test plan will be created as part of the work / points in this ticket

**Comment by jilladams** [comment]
Per Michelle, we want to do a content audit for the range of lengths being used right now.

**Comment by mmiddaugh** [comment]
attaching results of audit - not all were counted but of the 45 I checked, the average character is 213
only 4 banners added links 
[VAMC BWSO character count.xlsx](https://github.com/user-attachments/files/17579656/VAMC.BWSO.character.count.xlsx)

**Comment by jilladams** [comment]
Per refinement today: based on the current limits and basic usage to date, this is not a near-term priority. We didn't bother to refine it.

**Comment by Agile6MSkinner** [comment]
Closing for now because the data doesn't support a need. Can re-open if it becomes an issue.
