### ISSUE TITLE
[FE] Update template & query for Benefit hub & Campaign landing pages Connect With Us content

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-cms#19649]
**[2024-11-15]** The data relationship to use new Block type for Connect with Us content is saved on all production nodes, but for some Benefit Hub Landing Pages, that change is saved as Draft. It must be published before we can ship the FE change. Requires coordination with CAIA.

## Description

We want to get rid of the tech debt template for offices routes. This was something that was built long ago and that we don't need or want to ensure pages are published for this content type.

We need to also verify on the FE the changes in Ticket #19544 to ensure only published content displays on the FE.

### User story

**AS A** Veteran looking at Benefit Hubs in VA.gov
**I WANT** to only see published content
**SO THAT** I'm not confused by any unpublished content and so that I don't encounter any broken links.

1. Go to https://prod.cms.va.gov/burials-memorials, a Benefits Hub Landing Page.
2. Scroll down to the bottom of the page, and observe the 'Add a "Connect with us" block' content.
3. Visit the source for the 'Add a "Connect with us" block' , which is the NCA Office node: https://prod.cms.va.gov/nca.
4. Observe that there are no published revisions for the NCA Office node. The content should not be visible at all on Benefit Hub Landing Pages. 

## Testing & QA
* Make sure that Connect with Us content on Benefits Hubs in prod doesn't regress / is still visible after Office nodes are published
* Make sure that Outreach and Events office doesn't regress: 
  * https://www.va.gov/outreach-and-events/
  * https://prod.cms.va.gov/outreach-and-events

### Roles / assignments
_After functional testing, code review, accessibility review, and design review can happen in parallel._
- [x] **Functional testing:** @jilladams 
- [x] **Code review:** @chriskim2311 
- [ ] **Product acceptance:** 

## Warning
- Race condition exists when deploying to ensure prod isn't broken. 

## Acceptance criteria
_ACs should capture expected behavior, to inform test plans. Consider devices, documentation updates including KBs, change management, and [content model](https://prod.cms.va.gov/admin/structure/cm_document) when applicable._

- [x] Remove the templates / routes for offices-directory so that they don't build or publish to production
- [x] Verify that Draft changes to BHLPs are published prior to ship, to establish "Connect with us" block display
- [ ] Verify that Benefit Hub Landing Page "Connect with us" blocks display only the Latest Revision of Connect with Us block content after #19544

**Comment by jilladams** [comment]
Offices: 
* Outreach and Events is actually a published offfice live in the FE. That's news. 
* We need to revisit whether we can actually say: don't publish Offices to the FE.
* We cannot remove OFfices page routes, because of that.

So: now #19544 is a content model question of how to fix this.

**Comment by davidmpickett** [comment]
**End of sprint update**
- I have a [draft PR](https://github.com/department-of-veterans-affairs/content-build/pull/2351) to update Content Build queries and templates
- Currently attempting a Content Release on my personal [Demo tugboat](https://tugboat.vfs.va.gov/66a2b23f044834759e744124)(which has pulled in my Drupal changes even though Prod hasn't)
- Quite possible I have missed something and will definitely need some actual FE engineers to support me on

**Comment by davidmpickett** [comment]
I found an error in my GraphQL syntax and just pushed an update. Doing another Content Release on my Tugboat to verify.

**Comment by davidmpickett** [comment]
Success! https://web-sivbehcvqkui7ce9b67dwanfbohmenin.demo.cms.va.gov/burials-memorials/

Now I just need to write up all the stuff in the PR

![Image](https://github.com/user-attachments/assets/e16de7ae-9369-4e48-8be8-a0aeae8d914d)

**Comment by jilladams** [comment]
The data relationship to use new Block type for Connect with Us content is saved on all production nodes, but for some Benefit Hub Landing Pages, that change is saved as Draft. It must be published before we can ship the FE change. Requires coordination with CAIA.

BHLPs in this state include: 
https://prod.cms.va.gov/health-care - Danielle Thierry
https://prod.cms.va.gov/burials-memorials - Beth Potts
https://prod.cms.va.gov/decision-reviews - Danielle Thierry

**Comment by davidmpickett** [comment]
I just refreshed [my Tugboat](https://tugboat.vfs.va.gov/66a2b23f044834759e744124) to pull in all the content changes Jill made and am now running a Content Release using my CB PR.

**Comment by davidmpickett** [comment]
> The data relationship to use new Block type for Connect with Us content is saved on all production nodes, but for some Benefit Hub Landing Pages, that change is saved as Draft. It must be published before we can ship the FE change. Requires coordination with CAIA.
> 
> BHLPs in this state include: https://prod.cms.va.gov/health-care - Danielle Thierry https://prod.cms.va.gov/burials-memorials - Beth Potts https://prod.cms.va.gov/decision-reviews - Danielle Thierry

Resolved via revision manipulation

**Comment by davidmpickett** [comment]
**End of sprint update:**
- Finally passed CI on main, should deploy tomorrow AM

**Comment by jilladams** [comment]
This is now deployed to Prod. For verification, we can ask CAIA to make draft updates, but I think we can close / don't need to wait on that. So: closing.
