### ISSUE TITLE
Parent link on Manila VA Clinic pages changes on save

### ISSUE THREAD

**Issue by omahane** [department-of-veterans-affairs/va.gov-cms#19654]
## Describe the defect
When an editor saves a page (notably the VAMC Detail page) under the Manila VA Clinic menu, the page's "Parent link" changes to <Manila VA Clinic>. This results in the page not having a parent in the menu, which breaks the content-build process.

### Check the menu before saving
1. Log in as an admin
2. Go to `/admin/structure/menu/manage/manila-va-clinic`
- [ ] Confirm that "Make an appointment" has "Manila VA Clinic" (the facility node) as its menu parent

### Save the page as an editor
1. Log in as an editor with in the "Manila VA Clinic" section
2. Go to a page, such as "Make an appointment" (`node/72716/edit`)
- [ ] Confirm that you cannot change the **Menu parent** because the form element is disabled
- [ ] Confirm that the **Parent link** is "<Manila VA Clinic>"
3. Save the page

### Check the menu after saving
1. Log in as an admin
2. Go to `/admin/structure/menu/manage/manila-va-clinic`
- [ ] Confirm that "Make an appointment" is now at the menu root and has no parent

## AC / Expected behavior
When editing a page, the page should not change the parent link unless it has been explicitly changed.

## Screenshots
![Image](https://github.com/user-attachments/assets/f7a9adb1-4d41-42fa-affa-142cbf569236)

 ## Additional context
- This was first discovered when investigating the root cause of https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19652
- The original work done to control this menu parent and access is https://github.com/department-of-veterans-affairs/va.gov-cms/pull/5648

**Comment by davidmpickett** [comment]
For posterity sharing the link to the menu testing mural I made today https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1723593558224/a30b84ebae1d10930081e03f6bc8789ae00a0022?wid=0-1730405541128

**Comment by omahane** [comment]
Update on this: After time looking at this with our friend Steve Wirt, we found that the items which were changing to the menu root when being saved did not have a menu parent set in the database. This is despite the menu form showing otherwise.
![Image](https://github.com/user-attachments/assets/b4ea43a7-5558-43e0-a7be-061315f3d52d)

in production, I have saved all the items without parents that should have parents, using the place in the menu form as the guide.

**Comment by omahane** [comment]
After comparing Dave's testing of my PR and the items that had no parents in the database, I think we are at a 1:1 match. I would like to test the solution we have in the PR after the Tugboat db updates on Monday, Nov 4.

**Comment by omahane** [comment]
@jilladams @Agile6MSkinner 
The code has been merged and production changes have been made. The editor should be given the green light to update at their convenience. 🤞 that it doesn't go wonky again.

**Comment by jilladams** [comment]
Thank you!

**Comment by jilladams** [comment]
CLosing, and we can always reopen if we run into new trouble.
