### ISSUE TITLE
Addresses in rich text fields

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#1966]
As an editor, i want to add an address with structured content to my rich text field.

**Comment by swirtSJW** [comment]
I am not sure who is asking for this feature.   Would likely be a plugin for ckeditor.

**Comment by EWashb** [comment]
Agreed @swirtSJW. I'm going to add CKEditor 5 as a blocker to this. I don't know where this ask is coming from either, and I have not heard this myself.

**Comment by laflannery** [comment]
Closing as this looks like a duplicate of #3950
