### ISSUE TITLE
Run production migration script for Facilities phone number standardization project

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#19660]
Facilities is migrating some older phone number fields to a standardized phone paragraph type. 

We need CMS team help to run a migration script in production to launch. 

## Script details
Script should take ~40 minutes to run. 

Run the following commands:

```
drush codit-batch-operations:run MigratePhoneFieldToParagraph
drush codit-batch-operations:run MigrateVamcBillingInsurancePhoneFieldToParagraph
drush codit-batch-operations:run MigrateVamcFacilityMentalHealthPhoneFieldToParagraph 
```

After running, Codit Batch Operations logs (`/admin/config/development/batch_operations/log`) should show the completed runs and a log of the items migrated.

**Comment by gracekretschmer-metrostar** [comment]
@7hunderbird got word that Sitewide will likely need support to do this work next week.

**Comment by gracekretschmer-metrostar** [comment]
Edmund's feedback: Tim or myself can scrub in, if needed.

**Comment by jilladams** [comment]
Hiya - @gracekretschmer-metrostar just let @Agile6MSkinner know when y'all are able to run this script. We are timing some launch comms for VHA DM, and need to have that timing in hand in order to finalize.

**Comment by EWashb** [comment]
@mmiddaugh we have outlined this in our sprint to support.

**Comment by 7hunderbird** [comment]
@jilladams @gracekretschmer-metrostar This has been run on prod today.

- https://prod.cms.va.gov/admin/config/development/batch_operations/log

![Image](https://github.com/user-attachments/assets/ba9df178-279b-48f8-8549-5662944f27e8)

**Comment by jilladams** [comment]
Thank you! Safe to close from Sitewide POV, as far as I know.
