### ISSUE TITLE
Test AP story listings build and log blockers or approve for launch

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#19677]
## Description
Staged on AP Tugboat: 
https://main-kqjsor0i3mjdwsy9gojxhhyvdzh0wubb.tugboat.vfs.va.gov/pittsburgh-health-care/stories/

AP team built the template
IIR team reviewed it and compared to content-build / prod, and feels it's ready. 

We need to once-over it, and provide either greenlight or redlight, with notes about blockers. 

## Acceptance criteria
- [ ] Review stories next build
- [ ] Create a va.gov-cms ticket to track any findings. Include MUST, SHOULD, or CONSIDER in issue title, and set the parent issue to va.gov-cms #19575

**Comment by jilladams** [comment]
@laflannery we have achieved process for checking Stories and News releases. I'mma make another ticket like this for News. Feel free to take a look at this if you wanted to. So far this is ONLY for story listings -- not story nodes.

**Comment by laflannery** [comment]
@jilladams I can definitely get this in, I was working with Grace on a process for remaining Events items already so this works out nicely. Is there a timeframe we would ideally like to get this done in or just as we can?

**Comment by jilladams** [comment]
It won't launch until after Events do, which will at min be after Veterans Day, so no fire drill. Whenever you can get to it would be great. (Same for #19680 )

**Comment by laflannery** [comment]
Randi and I both reviewed, all issues are added as subtasks to the Next-build ticket
