### ISSUE TITLE
LAUNCH BLOCKER: i18next regression

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#19670]
## Description
There was [a previous ticket to resolve the loading of i18next](https://github.com/department-of-veterans-affairs/next-build/issues/629) however there is a chance this has regressed because of a few things that are being seen currently:
- The words "Previous" and "Next" are not displaying on the pagination component - this causes an accessibility issue
![Image](https://github.com/user-attachments/assets/12021ae9-8295-4622-b213-c0024a48454b)

- The word "Select" is not showing in the events filter
![Image](https://github.com/user-attachments/assets/59d97dce-79ff-418b-af38-0647e72f9b1c)

- The error messages on the date components are showing as "undefined"
![Image](https://github.com/user-attachments/assets/95960ee3-cb32-426f-b107-30d71fa92a01)

**Note:** This may be caused because the component-library is not up to date

```[tasklist]
###
- [x] The problem as described is fixed
- [x] The repro steps result in 'expected result'
- [x] An automated test is written to catch the problem, if appropriate
```

### How can we see the problem? (repro steps)

1. Please include a set of steps that allows an independent tester to see the problem.
2. Write them so that after the defect is fixed, the steps will result in the expected result.
3. It is helpful to write the steps methodically so they can be the foundation of an automated test.

**Expected result:** What should be the outcome?<br />
**Actual result:** What currently happens?

### Is there any additional information?
Screenshots:

Log messages (please specify from where or what commands(s))
```
Log messages here
```

**Comment by laflannery** [comment]
The fix has been merged and I am now seeing this resolved - I believe we can close this now?

**Comment by gracekretschmer-metrostar** [comment]
Yep! closing now.
