### ISSUE TITLE
Next-build Events: Style/Spacing difference on Last updated & Feedback button section

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#19691]
## Description

On the Next event detail pages, the section right above the footer that contains the "Last Updated" text and the feedback button is not the same as it is is on prod, it's much wider and taller (Next on the left, Prod on the right)
![Image](https://github.com/user-attachments/assets/626ddfda-0f27-4738-a2a1-2ecca2f5fe21)

After investigating, it looks like if [the breakpoint classes are updated from this issue](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19667), this should resolved the issue.

```[tasklist]
###
- [ ] The problem as described is fixed
- [ ] The repro steps result in 'expected result'
- [ ] An automated test is written to catch the problem, if appropriate
```

### How can we see the problem? (repro steps)

1. Please include a set of steps that allows an independent tester to see the problem.
2. Write them so that after the defect is fixed, the steps will result in the expected result.
3. It is helpful to write the steps methodically so they can be the foundation of an automated test.

**Expected result:** What should be the outcome?<br />
**Actual result:** What currently happens?

### Is there any additional information?
Screenshots:

Log messages (please specify from where or what commands(s))
```
Log messages here
```

**Comment by jilladams** [comment]
This appears to be fixed on Next events: 

Tugboat: 
![Image](https://github.com/user-attachments/assets/5f29cea0-1ef7-45cc-a34e-8fc18f79ca8e)

Prod: 
![Image](https://github.com/user-attachments/assets/706ee0ac-9cd2-4d1c-854f-d0a9197e5b5d)

Closing.

**Comment by laflannery** [comment]
Technically no? You are comparing Next-build to next-build in the screenshots above because events launched so we only have the old screen shots to compare to how it was. Basically the next feedback section goes much further left than it used to because the classes are incorrect

**Comment by jilladams** [comment]
Ah ok. I wasn't understanding the screenshots. I see what you were calling out, but what happens in prod today is that the Feedback button seems to float right and stay right-aligned with the width of the content. I understand that's different than it used to be, but do we know if it's a problem in design terms? (I'm reluctant to reopen.) 

![Image](https://github.com/user-attachments/assets/2b8e005e-ab70-4416-8c4b-6ca48db8faad)
