### ISSUE TITLE
Global: announcement-root div missing (Events)

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#19694]
## Description

In Prod, there is a div directly under the `<body>` tag with an ID of `announcement-root`:
![Image](https://github.com/user-attachments/assets/504e5b45-0483-445e-8a16-87af57c826df)

I had previously found this in the Next footer and called it out as being a difference from Prod. This is a previous screen shot of the Prod footer on the left and the next footer on the right - it shows that this announcement root used to be in the Next footer:
![Image](https://github.com/user-attachments/assets/95b4ef85-458e-44de-a403-596995101346)

However, this div was then removed from the next footer but not put back into the original position above the header.  The goal is to make Next as close to Prod as possible, I do not know the purpose of this announcement root div but I want to make sure we have confirmed we do not need this before we remove it entirely

```[tasklist]
###
- [ ] The problem as described is fixed
- [ ] The repro steps result in 'expected result'
- [ ] An automated test is written to catch the problem, if appropriate
```

### How can we see the problem? (repro steps)

1. Please include a set of steps that allows an independent tester to see the problem.
2. Write them so that after the defect is fixed, the steps will result in the expected result.
3. It is helpful to write the steps methodically so they can be the foundation of an automated test.

**Expected result:** What should be the outcome?<br />
**Actual result:** What currently happens?

### Is there any additional information?
Screenshots:

Log messages (please specify from where or what commands(s))
```
Log messages here
```

**Comment by mcommons10** [comment]
IIR is including this ticket in our upcoming planning; will ensure property placement / parity with out board

**Comment by mcommons10** [comment]
This work has been merged but is pending deployment.

**Comment by jilladams** [comment]
@mcommons10 can this ticket be closed now in the Next board?

**Comment by jilladams** [comment]
(#19695 is a sister ticket to this, but I'm unclear if a fix will be an actual Global fix, or will need to be addressed per-template / content type. If 19695 can also be confirmed for events listings with whatever IIR work did here, both should close.)

**Comment by mcommons10** [comment]
@jilladams - both tickets can be closed! confirmed with @AdamKing0126 this is a global fix.
