### ISSUE TITLE
Next-build events: Prod Other times for event only shows next 5 by default

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#19690]
## Description
On prod currently, the accordion that shows the other times for an event by default shows the next 6 events. However, on Next this accordion only shows the next 5 times. This is very minor however, I do not know why this was changed or if it was changed on purpose so I'm not sure if this is an indicator of other functionality issues which is why I want to make sure it was noted.

Example:
- [Prod event](https://www.va.gov/outreach-and-events/events/64661/) with 6 next times showing
![Image](https://github.com/user-attachments/assets/70fe45b9-acbe-4507-b6ec-7df42a0db714)
- [The same event in Next](https://dev.va.gov/outreach-and-events/events/64661/) but only shows 5 times by default
![Image](https://github.com/user-attachments/assets/eb4a5095-034f-415b-82ab-ad9956b76bbf)

```[tasklist]
###
- [ ] The problem as described is fixed
- [ ] The repro steps result in 'expected result'
- [ ] An automated test is written to catch the problem, if appropriate
```

### How can we see the problem? (repro steps)

1. Please include a set of steps that allows an independent tester to see the problem.
2. Write them so that after the defect is fixed, the steps will result in the expected result.
3. It is helpful to write the steps methodically so they can be the foundation of an automated test.

**Expected result:** What should be the outcome?<br />
**Actual result:** What currently happens?

### Is there any additional information?
Screenshots:

Log messages (please specify from where or what commands(s))
```
Log messages here
```

**Comment by jilladams** [comment]
I know this is a difference from Production, but I don't think 5 vs 6 is based on any kind of data, and I don't think we need to care about it. I'd like to advocate that we close as a no-op and focus energies on tickets with veteran-facing impact. cc @FranECross @mmiddaugh

**Comment by FranECross** [comment]
> I know this is a difference from Production, but I don't think 5 vs 6 is based on any kind of data, and I don't think we need to care about it. I'd like to advocate that we close as a no-op and focus energies on tickets with veteran-facing impact. cc [@FranECross](https://github.com/FranECross) [@mmiddaugh](https://github.com/mmiddaugh)

I'm on-board with closing as a no-op.
