### ISSUE TITLE
Global: Some mega nav Promos are not displaying

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#19692]
## Description
On any Next build template, some of the promos in the Mega nav are not displaying:

![Image](https://github.com/user-attachments/assets/653db874-2f32-41d4-9209-f4a376f91038)

[This was already ticketed an looked at ](https://github.com/department-of-veterans-affairs/next-build/issues/647)however we never saw these working and just weren't able to get a final confirmation/discussion around this to feel confident so I wanted to just make sure we new these would work once on Prod.

```[tasklist]
###
- [ ] The problem as described is fixed
- [ ] The repro steps result in 'expected result'
- [ ] An automated test is written to catch the problem, if appropriate
```

### How can we see the problem? (repro steps)

1. Please include a set of steps that allows an independent tester to see the problem.
2. Write them so that after the defect is fixed, the steps will result in the expected result.
3. It is helpful to write the steps methodically so they can be the foundation of an automated test.

**Expected result:** What should be the outcome?<br />
**Actual result:** What currently happens?

### Is there any additional information?
Screenshots:

Log messages (please specify from where or what commands(s))
```
Log messages here
```

**Comment by timcosgrove** [comment]
See more detail here:
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15491
https://dsva.slack.com/archives/CDHBKAL9W/p1696271256885979

**Comment by jilladams** [comment]
(I'm testing in a Tugboat: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15491#issuecomment-2489623257)

**Comment by jilladams** [comment]
In Tugboat, added the missing Promo blocks to the megamenu menu items, and there were no duplicate promo blocks or weird stuff after a FE content release. 

So: I've added the Promo blocks to Menu items in prod. They should go out in content-release 17102.

**Comment by laflannery** [comment]
Unfortunately this didn't seem to fix the next-build issue in prod:

- Current prod next-build events page: https://www.va.gov/mountain-home-health-care/events/62000/
- Health care promo is added in Drupal now: https://prod.cms.va.gov/admin/structure/menu/item/810/edit?destination=/admin/structure/menu/manage/header-megamenu
![Image](https://github.com/user-attachments/assets/d83fc170-1f7c-4b59-b34e-2168625f5329)

- Health care promo (among others) are still missing on the FE:
![Image](https://github.com/user-attachments/assets/cc90c180-c35e-4b9f-b848-3082f342418c)

**Comment by timcosgrove** [comment]
This one was fixed by @jilladams making data changes to the megamenu. Thanks Jill!

**Comment by jilladams** [comment]
RAD!!! Glad to hear that's all it took.
