### ISSUE TITLE
Resources and support MVP 1.0 [PW]

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#1975]
MVP 1.0 - October 2020
  * QA on Demo environment - Oct 29
  * Launch to prod - Nov 4

[MVP 1.1](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/2915) - December 2020
Content managed by PW team.

---

* [Notes](https://docs.google.com/document/d/1goAO4UWQLfEPFb5_J8Sft3CAJ9RMKelZe1B0_iQomSg/edit#)
* [Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1588167553516/2773c854e8ff3a725a5e3ee03272b78e8519f78b)
* [PW/CMS standing agenda with notes and action items](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/cms/readme.md)
* [Learning Center template requirements](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/template-requirements.md#about)

**Comment by oksana-c** [comment]
Resources and support MVP 1.0 is launched 🚀 
Closing this epic 🎉 
cc @jenniferlee-dsva @brianalloyd @swirtSJW @cmaeng @kevwalsh
