### ISSUE TITLE
[Drupal admin] Transfer "Connect with Us" content to blocks and associate with correct nodes

### ISSUE THREAD

**Issue by davidmpickett** [department-of-veterans-affairs/va.gov-cms#19764]
## Description
- [ ] Migrate the 4 offices with connect with us content into connect with us block
- [ ] Edit every CLP and BHLP and make the new Connect with Us field match the old field
- [ ] That's it

**Comment by jilladams** [comment]
Blocked on Drupal work merging to Prod.

**Comment by jilladams** [comment]
Connect with Us blocks have been created on Prod. https://prod.cms.va.gov/admin/content/block?info=&type=connect_with_us

![Image](https://github.com/user-attachments/assets/fc58b260-d227-4f87-836e-41962cd815f0)

All blocks have been set on published CLPs that had Connect With Us set, and on all BHLPs.

Notified CAIA here: https://dsva.slack.com/archives/C01K37HRUAH/p1731708377631319
