### ISSUE TITLE
Update composer dependencies

### ISSUE THREAD

**Issue by edmund-dunn** [department-of-veterans-affairs/va.gov-cms#19772]
## User Story or Problem Statement
All dependencies brought in using composer need to be updated. The only exceptions are `drupal/core-recommended` and `drupal/core-composer-scaffold`.

## Description or Additional Context 
For `views_bulk_operations` the following change will need tobe addressed:

> Actions Permissions
Deprecated: using actions permissions is deprecated and this module is removed from 4.3.x releases and higher. Please uninstall it before upgrading.
A module called actions_permissions is included in the package prior to 4.3.x. This module generates a permission for each action, and VBO honors those permissions before showing or executing the corresponding actions. This is useful if you want to provide your VBO to several groups of users with different privileges: the same view will accommodate those different groups, showing to each the actions that they are permitted to see.

To test VBO see https://dsva.slack.com/archives/CT4GZBM8F/p1730749024413859

## Steps for Implementation
Any patches that need to be rerolled or removed will need to be addressed.

## Acceptance Criteria
- [ ] Update all composer dependencies that have updates. 
- [ ] Requires design review
- [ ] Requires accessibility review

Using this sheet to keep track of updated/not updated modules as part of this ticket: https://docs.google.com/spreadsheets/d/1exMktEjiY9CaKtzvh0Qi-F8ffuDz-jJ5LXMuHVx4cu0/edit?usp=sharing

**Comment by JakeBapple** [comment]
for config_split update, we'll need a follow-up deployment to remove the config_filter module (https://www.drupal.org/project/config_split).
