### ISSUE TITLE
Update drupal core to v10.3.6

### ISSUE THREAD

**Issue by edmund-dunn** [department-of-veterans-affairs/va.gov-cms#19773]
## User Story or Problem Statement
Drupal core needs to updated to v10.3.6.

## Steps for Implementation
Update `drupal/core-recommended` and `drupal/core-composer-scaffold` to v10.3.6.

## Acceptance Criteria
- [ ] `drupal/core-recommended` package update to 10.3.1 with all dependencies
- [ ] `drupal/core-composer-scaffold` package updated to 10.3.1 with all dependencies

**Comment by JakeBapple** [comment]
Updated two patches for 10.3.8:
https://www.drupal.org/project/drupal/issues/3057267
and
https://www.drupal.org/project/drupal/issues/2942404
