### ISSUE TITLE
URL Change for: St. Croix Vet Center Outstation vc_3071OS - Awaiting Redirect

### ISSUE THREAD

**Issue by ian-sears** [department-of-veterans-affairs/va.gov-cms#19781]
Parent ticket: #17847 

## What had happened was
Three things: 
1. San Juan: St Thomas VC OS got removed from VAST (vc_3072OS) - no redirect needed. https://www.va.gov/san-juan-vet-center/locations/#st-thomas-vet-center-outstation and https://www.va.gov/san-juan-vet-center/#st-thomas-vet-center-outstation already just load the main VC page
2. San Juan: St Croix VC OS got removed from VAST (vc_3071OS) - needs a redirect
3. USVI > St Croix opened (vc_3081OS)

### Implementation date
When does this request need to be live:
ASAP

### Instructions for URL redirect: San Juan St Croix > USVI St Croix
(Note: This issue will be used from initial request through implementation to ensure all individuals working on this are notified of status updates.  Please do not create multiple issues to track different steps.)
- [x] Notify VA stakeholders as appropriate.
- [x] Link the related facility closure / rename issue. #17847 
Facility CMS link: https://prod.cms.va.gov/san-juan-vet-center/st-croix-vet-center-outstation
Facility API ID: vc_3071OS
- [x] Create a URL redirect in the [vsp-platform-revproxy](https://github.com/department-of-veterans-affairs/vsp-platform-revproxy) repo in `template-rendering/revproxy-vagov/vars/redirects.yml`
- [x] Add the "Awaiting redirect" flag to the facility node with a revision log message that includes a link to this ticket, preserving the node's current moderation state.
- [x] Redirects deploy daily except Friday at 10am ET, or by requesting OOB deploy (of the revproxy job to prod) in #vfs-platform-support. After deploy, validate that the URL redirect is deployed. (Note: In the event of a facility closure or a name change,  validate that this occurs before making the Lighthouse csv changes.)
- [x] Update this ticket with a comment that the redirect has been deployed.
- [x] Remove the "Awaiting redirect" flag on the facility node with a revision log message that includes a link to this ticket, preserving the node's current moderation state.
- [x] Notify helpdesk via comment on ticket or Slack message in #cms-support that changes are ready for review.

#### URL Redirects
| Current URL  |  Redirect Destination or New URL |
| -- | --|
| [https://www.va.gov/san-juan-vet-center/locations/#st-croix-vet-center-outstation](https://www.va.gov/san-juan-vet-center/locations/#st-croix-vet-center-outstation)  |  [https://www.va.gov/us-virgin-islands-vet-center/#st-croix-vet-center-outstation/](https://www.va.gov/us-virgin-islands-vet-center/#st-croix-vet-center-outstation/) |

### 1. Canonical URL change: San Juan St Croix > USVI St Croix

**Note: Canonical URL changes do not block the completion of the parent ticket. Once the URL redirect above has been deployed, the value to the Veteran is delivered. This ticket should be kept open until the URL change is verified, except in the case of a removal (as described below).**

### Instructions for canonical URL change
- [x] Verify that the new URL for the facility is published and accessible on VA.gov. - https://prod.cms.va.gov/us-virgin-islands-vet-center/st-croix-vet-center-outstation
- [x] Contact Lighthouse via Slack at #cms-lighthouse channel that this facility requires a canonical link in the following format (replacing the placeholder data with the actual API Id and VA.gov URL): https://dsva.slack.com/archives/C02BTJTDFTN/p1730765512022909
  - `vc_3081OS,https://www.va.gov/us-virgin-islands-vet-center/#st-croix-vet-center-outstation/`
- [x] Add the "Awaiting CSV" flag to the facility node with a revision log message that includes a link to this ticket.
- [x] Let Help desk know this has been done, if not done by Help desk.

#### Wait (days or weeks, potentially)
- [x] After the canonical link has been added to the websites.csv and you have confirmation from Lighthouse that the CSV has been deployed, validate that the change has deployed by checking that the Facility Locator has been updated with the new url.
- [x] Update this ticket with a comment that the CSV change has been deployed.

### Instructions for canonical URL removal
- [x] Try to find the facility via the Facility Locator, using the Facility API ID (e.g. https://va.gov/find-locations/facility/"facility_api_id"). If it is not available, proceed. - https://www.va.gov/find-locations/facility/vc_3071OS
- [x] Contact Lighthouse via Slack at #cms-lighthouse channel that this facility requires a canonical link to be removed in the following format (replacing the placeholder data with the actual API Id and VA.gov URL): https://dsva.slack.com/archives/C02BTJTDFTN/p1730765512022909
  - `vc_3071OS,https://www.va.gov/san-juan-vet-center/locations/#st-croix-vet-center-outstation`

**Comment by ian-sears** [comment]
@omahane @jilladams --

When you have some time, could you please Create a URL redirect in the [vsp-platform-revproxy](https://github.com/department-of-veterans-affairs/vsp-platform-revproxy) repo in template-rendering/revproxy-vagov/vars/redirects.yml

[FROM] https://www.va.gov/san-juan-vet-center/locations/#st-croix-vet-center-outstation/
[TO] https://www.va.gov/us-virgin-islands-vet-center/#st-croix-vet-center-outstation/

Please alert Helpdesk @department-of-veterans-affairs/platform-cms-helpdesk when this step has been completed.

**Comment by randimays** [comment]
The code for the redirect has been merged and will deploy Monday 11/25 around 9am CST.

**Comment by randimays** [comment]
The redirect is not working as expected. I believe I know what the issue is. Working on preparing the fix and hope to be able to deploy to production tomorrow instead.

**Comment by randimays** [comment]
After the new deploy this morning, the redirect is still not working as expected. I think there might be some trouble trying to redirect a URL with a `#` in it. @ian-sears I noticed that neither:

https://www.va.gov/san-juan-vet-center/locations/#st-croix-vet-center-outstation nor 
https://www.va.gov/us-virgin-islands-vet-center/#st-croix-vet-center-outstation

jumps to the St. Croix header because there is no ID on that header.

Do we actually want to redirect https://www.va.gov/san-juan-vet-center/locations to https://www.va.gov/us-virgin-islands-vet-center instead?

**Comment by ian-sears** [comment]
@randimays Thanks. (shrugs).
@jilladams Please advise on this case.

Is it appropriate for me to simply Archive this https://www.va.gov/san-juan-vet-center/locations/#st-croix-vet-center-outstation/ in this case?

Facts:
It is a closed facility. Its facility API ID was removed from VAST. The NEW facility is up and running, CSV is already resolving (for the new one); essentially all is well except for the consideration of reDirecting this (remember, this is an OUTstation, not a Vet Center or VAMC, or MVC, etc).

**Comment by randimays** [comment]
@ian-sears I verified in production this morning that https://www.va.gov/san-juan-vet-center/locations now redirects to https://www.va.gov/us-virgin-islands-vet-center. If everything is working as you intend, please close the ticket when ready.

**Comment by ian-sears** [comment]
This morning,
redirect has deployed.
https://www.va.gov/san-juan-vet-center/locations/#st-croix-vet-center-outstation
now has begun re-directing to 
https://www.va.gov/us-virgin-islands-vet-center/#st-croix-vet-center-outstation
Correct. The link on the page to "Other nearby.." is the convention and all is working as expected now.
CSV has deployed and is correct.
Closing this URL change as resolved.

Parent ticket: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17847
