### ISSUE TITLE
SPIKE: Audit Sitewide products' impact for upcoming vets-website deployment changes

### ISSUE THREAD

**Issue by randimays** [department-of-veterans-affairs/va.gov-cms#19780]
## Description

The Platform Reliability Team will be rolling out changes to the front end deployment pipeline for vets-website on 2/3/25. [Slack announcement](https://dsva.slack.com/archives/C03R5SBELQM/p1730830493762959)

If an application's code is not isolated, teams will not be able to deploy the application to production without Platform assistance.

We need to audit Sitewide products in vets-website and determine the impact of this change to each of our products.

Relatedly, we aren't sure how this change will impact Sitewide code that is not isolated to a `src/applications` folder (React widget or other componentized code). Jill requested some time to meet with the Reliability Team to understand how this would work. [Slack thread](https://dsva.slack.com/archives/C04B87D2QLS/p1730834080448269)

### User story

**AS A** PO/PM/Delivery Manager/PW Teammember
**I WANT** to understand how the PW team's applications will be affected by the above described change
**SO THAT** we can make changes so that we don't have to rely on Platform assistance, or if we're unable to do that, plan to accommodate and plan for delays due to Platform assistance being required

### Engineering notes / background

The below table can be used to assess code impact for Sitewide code in vets-website. Also, as part of the Frontend Support Dashboard, Platform has compiled a list of impacted applications that can be referenced: https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/frontend-support-dashboard/cross-app-import-report/

| Product Name | Code Path | Portfolio | Impact | 
| --- | --- | -- | -- |
| BTSSS Widget | src/applications/static-pages/BTSSS-login | PW |  ✅ **None**|
| CTA Widget | src/applications/static-pages/cta-widget  | PW |   ✅ **None**  |
| Discharge Upgrade Wizard | src/applications/discharge-wizard | PW |  ✅ **None**  |
| Drupal Static Data | src/platform/site-wide/drupal-static-data | PW |   ✅ **None**  |
| Find Forms | src/applications/find-forms | PW |   ✅ Imports are from platform folder, Platform utilities/helpers |
| Homepage Search | src/applications/static-pages/homepage | PW |   ✅ **None**  |
| Homepage Veteran Banner | src/applications/static-pages/homepage-veteran-banner | PW |   ✅ **None** |
| Income Limits | src/applications/income-limits | PW | ✅ **None** |
| Language Toggles (i18Select) | src/applications/static-pages/i18Select | PW |   ✅ **None**  |
| PACT Act Wizard | src/applications/pact-act | PW |  ✅ **None** |
| Public Outreach Materials | src/applications/public-outreach-materials | PW |  ✅ **None** |
| Resources & Support | src/applications/resources-and-support | PW | ✅ **None** |
| Search | src/applications/search | PW | ✅ **None** |
| Sitewide Announcements | src/platform/site-wide/announcements | PW |  ✅ **Widget type object might need to move to the platform folder** |
| Sitewide Banners | src/platform/site-wide/banners | PW |  ✅ **None** |
| TeamSites Helpers | src/platform/site-wide/helpers/team-sites |  PW | ✅ **Bucket object might need to move to the platform folder** |
| Side Nav | src/platform/site-wide/side-nav | CMS? PW? Fac? all 3? | ✅ **Widget type object might need to move to the platform folder** |
| Events (search) | src/applications/static-pages/events | Fac / PW |✅ **None** |
| Facility Locator | src/applications/facility-locator | Fac | ✅ Imports are from platform folder, Platform utilities/helpers |
| Facilities Widgets | src/applications/static-pages/facilities | Fac | ✅ Imports are from platform folder, Platform utilities/helpers. And multiple imports from facility locator folder |
| Cerner / Healthcare CTAs | src/applications/static-pages/health-care-manage-benefits | Fac but transitioning to Health Tools, no hard date | ✅ Imports are from platform folder, Platform utilities/helpers  |

### Scope / Impact analysis
_What, if anything, could break as a result of this change?_
_Engineer should assess this when approaching PR._

### Roles / assignments
_After functional testing, code review, accessibility review, and design review can happen in parallel._
- [ ] **Functional testing:** 
- [ ] **Code review:** 
- [ ] **Design review:** 
- [ ] **Accessibility review:** 
- [ ] **Product acceptance:** 

## Acceptance criteria
_ACs should capture expected behavior, to inform test plans. Consider devices, documentation updates including KBs, change management, and [content model](https://prod.cms.va.gov/admin/structure/cm_document) when applicable._

- [ ] For each line item above, note the impact of this change
- [ ] Notify @jilladams and @FranECross when completed so more tickets/other conversations may occur.

**Comment by randimays** [comment]
Platform added messaging on Github PRs to indicate issues with app isolation and it linked to this report: https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/frontend-support-dashboard/cross-app-import-report/ that appears to have done some of this investigation for us 🥳  I updated the description above with what's shown on this report.

**Comment by jilladams** [comment]
https://dsva.slack.com/archives/C04CYC4LMU6/p1732131652244929?thread_ts=1732129280.235259&cid=C04CYC4LMU6

**Comment by chriskim2311** [comment]
@jilladams Went through the table and determined which products have some cross imports. Question: Do we know if the entire platform folder will be allowed to have imports into other folders for helper functions? 

Only 2 products have cross imports

- Facility Locator
- Facilities Widgets

**Comment by jilladams** [comment]
From 12/6 meeting with Curt Bonade (Plat reliability); Tim & Grace (CMS / content-build), Michelle, and me/ Chris: 
* Our apps don't act differently with respect to CI/CD than any others
* vets-website deploys will be at our discretion, and we will need to manage the dependency on content-build deploy when there is one. 
* Platform is willing to work with us on cutting over our apps to the new CD system, testing with one app first before all of them move to independent deploy.

## Tickets to cut

### Ticket 1: Facility Locator / widgets - 3 (add QA) = 5
Facility Locator | src/applications/facility-locator | Fac | ✅ Imports are from platform folder, Platform utilities/helpers
Facilities Widgets | src/applications/static-pages/facilities | Fac | ✅ Imports are from platform folder, Platform utilities/helpers. And multiple imports from facility locator folder

### Ticket 2: Everything else - 2
Sitewide Announcements | src/platform/site-wide/announcements | PW | ✅ Widget type object might need to move to the platform folder
TeamSites Helpers | src/platform/site-wide/helpers/team-sites | PW | ✅ Bucket object might need to move to the platform folder
Side Nav | src/platform/site-wide/side-nav | CMS? PW? Fac? all 3? | ✅ Widget type object might need to move to the platform folder

**Comment by jilladams** [comment]
Follow up tix are created. Closing!
