### ISSUE TITLE
[Discharge Upgrade Wizard] Answer '1992' missing from dropdown for Question 2: "What year were you discharged from the military?

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-cms#19784]
## Description

For Question 2: What year were you discharged from the military?, their should be an answer of '1992' between the answers "Before 1992", and '1993'. 

Note that there is logic surrounding what text to display if a user chooses 1992, and the logic for displaying other questions should be the same as for 1993, along with whatever logic for other answers the Veteran provides.

### User story

**AS A** Veteran who was discharged in 1992
**I WANT** to see that option for the DUW question 2  What year were you discharged from the military?
**SO THAT** subsequent questions and the results screen are correct and I'm not frustrated by not having this answer available, and to also prevent me from choosing the 'next best answer', which might provide incorrect results.

### Scope / Impact analysis
_What, if anything, could break as a result of this change?_
_Engineer should assess this when approaching PR._

### Roles / assignments
_After functional testing, code review, accessibility review, and design review can happen in parallel._
- [x] **Functional testing:** @FranECross 
- [ ] **Code review:** 
- [ ] **Design review:** 
- [ ] **Accessibility review:** 
- [x] **Product acceptance:** @FranECross 

## AC / Expected behavior
- [ ] For  Question 2: What year were you discharged from the military?, the user can choose 1992
- [ ] The logic for the above answer mirrors logic for the answer 1993

**Comment by FranECross** [comment]
@chriskim2311 Will you please ping me when this is on staging and ready to test? Thank you!

**Comment by FranECross** [comment]
Functional testing and product acceptance complete/passed.

**Comment by chriskim2311** [comment]
Closing, verified in staging
