### ISSUE TITLE
[Discharge Upgrade Wizard] Update text in Medical Records subsection (in the Supporting Information section) based on various logic

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-cms#19786]
## Description

On the DUW Results screen, in the "Add supporting information" section, the sub-section "Medical Records" is missing the MS Word document updates based on various logic (described below).

### User story

**AS A** Veteran using the Discharge Upgrade Wizard
**I WANT** to know what type of Medical Records I need to submit with my request for an upgrade, based on my reason for requesting the upgrade
**SO THAT** my requested upgrade isn't delayed

### Medical Records Text Based on Logic

**LOGIC**: If Question 3 = _**1**_ AND If Question 2 = **_before 1992_**

 [H4] **Medical records:**
- You’ll need to submit copies of your medical records. 
- **If you need to request copies of your VA medical records**, fill out and submit a Request for and Authorization to Release Health Information (VA Form 10-5345) to your local VA medical center. 
- Your **military medical records** will be included with the VA medical records you request. [Get VA Form 10-5345 to download](https://www.va.gov/find-forms/about-form-10-5345/). 
- **If you've seen a non-VA health care provider for diagnosis or treatment of PTSD or another mental health condition**, you should also submit private medical treatment records that can provide information about your condition. You’ll need to contact your provider to request copies of your records.  

**LOGIC**: If Question 3 = **_1_** AND If Question 2 = **_1992 to present_**

[H4] **Medical records:**
- You’ll need to submit copies of your medical records.   
- **If you need to request copies of your VA medical records**, fill out and submit a Request for and Authorization to Release Health Information (VA Form 10-5345) to your local VA medical center. 
- [Find out how to request your **military medical records**](https://www.archives.gov/st-louis/military-personnel/ompf-background.html).
[Get VA Form 10-5345 to download](https://www.va.gov/find-forms/about-form-10-5345/). 
- **If you've seen a non-VA health care provider for diagnosis or treatment of PTSD or another mental health condition**, you should also submit private medical treatment records that can provide information about your condition. You’ll need to contact your provider to request copies of your records.

**LOGIC**: If Question 3 = **_2_** AND If Question 2 = **_before 1992_**

[H4] **Medical records:**
- You’ll need to submit copies of your medical records.   
- **If you need to request copies of your VA medical records**, fill out and submit a Request for and Authorization to Release Health Information (VA Form 10-5345) to your local VA medical center. 
- Your **military medical records** will be included with the VA medical records you request.
- [Get VA Form 10-5345 to download](https://www.va.gov/find-forms/about-form-10-5345/). 
- **If you've seen a non-VA health care provider for diagnosis or treatment of TBI**, you should also submit private medical treatment records that can provide information about your condition. You’ll need to contact your provider to request copies of your records.

**LOGIC**: If Question 3 = _**2**_ AND If Question 2 = _**1992 to present**_

[H4] **Medical records:**
- You’ll need to submit copies of your medical records.   
- **If you need to request copies of your VA medical records**, fill out and submit a Request for and Authorization to Release Health Information (VA Form 10-5345) to your local VA medical center. 
- [Find out how to request your **military medical records**](https://www.archives.gov/st-louis/military-personnel/ompf-background.html).
- [Get VA Form 10-5345 to download](https://www.va.gov/find-forms/about-form-10-5345/). 
- **If you've seen a non-VA health care provider for diagnosis or treatment of TBI**, you should also submit private medical treatment records that can provide information about your condition. You’ll need to contact your provider to request copies of your records.

**LOGIC**:  If Question 3 = **_4_** AND If Question 2 = **_before 1992_**

[H4] **Medical records:**
- You’ll need to submit copies of your medical records.   
- **If you need to request copies of your VA medical records**, fill out and submit a Request for and Authorization to Release Health Information (VA Form 10-5345) to your local VA medical center. 
- Your **military medical records** will be included with the VA medical records you request.
- [Get VA Form 10-5345 to download](https://www.va.gov/find-forms/about-form-10-5345/). 
- **If you've seen a non-VA health care provider for treatment after your assault or harassment**, you should also submit records from a non-VA health care provider. You’ll need to contact your provider to request copies of your records.

**LOGIC**: If Question 3 = **_4_** AND If Question 2 = **_1992 to present_**

[H4] **Medical records:**
- You’ll need to submit copies of your medical records.   
- **If you need to request copies of your VA medical records,** fill out and submit a Request for and Authorization to Release Health Information (VA Form 10-5345) to your local VA medical center. 
- [Find out how to request your **military medical records**](https://www.archives.gov/st-louis/military-personnel/ompf-background.html).
- [Get VA Form 10-5345 to download](https://www.va.gov/find-forms/about-form-10-5345/). 
- **If you've seen a non-VA health care provider for treatment after your assault or harassment**, you should also submit records from a non-VA health care provider. You’ll need to contact your provider to request copies of your records.

### Scope / Impact analysis
_What, if anything, could break as a result of this change?_
_Engineer should assess this when approaching PR._

### Roles / assignments
_After functional testing, code review, accessibility review, and design review can happen in parallel._
- [x] **Functional testing:** @FranECross 
- [ ] **Code review:** 
- [ ] **Design review:** N/A
- [x] **Accessibility review:** @laflannery 
- [x] **Product acceptance:** @FranECross 

## AC / Expected behavior
- [x] Medical Records text has been updated based on this logic **: If Question 3 = _**1**_ AND If Question 2 = **_before 1992_** using the text shown above
- [x]  Medical Records text has been updated based on this logic If Question 3 = **_1_** AND If Question 2 = **_1992 to present_** using the text shown above
- [x]  Medical Records text has been updated based on this logic If Question 3 = **_2_** AND If Question 2 = **_before 1992_** using the text shown above
- [x]  Medical Records text has been updated based on this logic If Question 3 = _**2**_ AND If Question 2 = _**1992 to present**_ using the text shown above
- [x]  Medical Records text has been updated based on this logic If Question 3 = **_4_** AND If Question 2 = **_before 1992_** using the text shown above
- [x]  Medical Records text has been updated based on this logic If Question 3 = **_4_** AND If Question 2 = **_1992 to present_** using the text shown above
- [x] Accessibility review
- [x] Product review/sign off

**Comment by jilladams** [comment]
@chriskim2311 @FranECross correct me if I'm wrong, but I think this one is in Staging and ready to verify as well?

**Comment by FranECross** [comment]
Reviewed and passed; closing. Thanks!
