### ISSUE TITLE
Design updated Operating Status presentation for FE

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#19806]
### Scope / Impact analysis
_What, if anything, could break as a result of this change?_
_Engineer should assess this when approaching PR._

## Acceptance criteria

- [ ] Design review
- [ ] A11y review

**Comment by davidmpickett** [comment]
Dupe of https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19804
