### ISSUE TITLE
FE: Handle new Operating Status options in Facility locator result list

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#19810]
## Description
New operating statuses need to be built and displayed correctly per final designs in Facility Locator search results, for all facility types / destinations: 
  - VAMC facilities
  - Vet Center facilities
  - Regional Office facilities with published modernized pages
  - Regional Office facilities without published modernized pages
  - NCA facilities without published modernized pages

| #   | Status                     | Color  | Comment                                 |
| --- | -------------------------- | ------ | --------------------------------------- |
| 1   | Normal services and hours  | N/A    | Default option, does not appear on FE   |
| 2   | Limited service and hours  | Blue   | Changes from yellow to blue             |
| 3   | Closed                     | Yellow | A legacy option that will be phased out |
| 4   | Temporary facility closure | Yellow | New option                              |
| 5   | Temporary location         | Yellow | New option                              |
| 6   | Virtual care only          | Yellow | New option                              |
| 7   | Coming soon                | Yellow | New option                              |
| 8   | Facility notice            | Blue   | Should be listed last in Drupal         |

## Testing & QA
QA test plan written in #19808 
QA test plan will be run against the aggregate changes in FE work in #19809 
QA test plan: [#13598 Facility Operating Status expansion test plan](https://docs.google.com/spreadsheets/d/1YUa8ujmnniU8E5VzqnSn8aG9iyOjypzrRazR0nKAVbE/edit?gid=0#gid=0)

## Acceptance criteria
- [ ] Normal operating status does not display in Facility Locator results
- [ ] Existing not-normal operating statuses display as they do in production today: 
  - [ ] Facility Operating status value appears without a link
  - [ ] Alert component style (Warning or Information) matches Figma design and design system supported options
- [ ] New not-normal operating statuses display per Figma designs
- [ ] Any behavior in final PR / build that differs from QA test plan expectations is identified, discussed with Product for signoff, and either QA test plan is updated or a ticket is created to modify that behavior to match the QA test plan

**Comment by Agile6MSkinner** [comment]
Added table of options for reference

**Comment by jilladams** [comment]
FE changes for this work have been merged and deployed. Color changes are visible in prod; status options won't appear until the Drupal work ships and additional statuses start flowing through. I'm closing this ticket.
