### ISSUE TITLE
Mental health numbers are showing in the Facility IEF on Operating Statuses

### ISSUE THREAD

**Issue by omahane** [department-of-veterans-affairs/va.gov-cms#19821]
## Describe the defect
When editing a Facility in an Inline Entity Form (IEF) on a given Operating Status, both the Mental Health field and Mental Health paragraph fields are showing.

## To Reproduce
1. Edit a VAMC System Operating Status Node (e.g. Boston)
2. Scroll ALLL the way down and open the Facility Operating Status accordion
3. Click edit button next to any facility
4. See both mental health numbers there even though neither should be

## AC / Expected behavior
Mental health phone numbers should not show on the Facility IEF display.

## Screenshots
![Image](https://github.com/user-attachments/assets/08571e84-8536-4aa8-9fe9-bfa0cd86f593)

 ## Additional context
This is related to work done to add the Mental health phone number paragraph: https://github.com/department-of-veterans-affairs/va.gov-cms/pull/19234

**Comment by jilladams** [comment]
This ticket shows a merged PR last week, but I still see both MH #s in this context. Not sure if that means the fix hasn't deployed, or the fix didn't work as expected: 
![Image](https://github.com/user-attachments/assets/dc005f0f-b93a-4fd7-8f96-bb485e20244f)

**Comment by jilladams** [comment]
Oh - just saw the PR actually just merged yesterday morning. Looks like yesterday the daily deploy may not have run? https://github.com/department-of-veterans-affairs/va.gov-cms/releases

Should likely go out with next deploy?

**Comment by jilladams** [comment]
Fixed in prod: 
![Image](https://github.com/user-attachments/assets/5935986c-e542-450f-89b5-5476f74929a6)
