### ISSUE TITLE
FE: Handle new Operating Status options on Modernized pages in vets-website

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#19826]
## Description
New operating statuses need to be built and displayed correctly per final designs on modernized pages for all facility types: 
  - VAMC System Locations page?
  - VAMC facility page?
  - VBA facility page
       - Nearby Locations
  - Vet Center facility page?
  - Vet Center locations Page

### Analytics considerations
Copy any existing analytics from current operating stati

## Testing & QA
QA test plan written in #19808 
QA test plan will be run against the aggregate changes in FE work in #19809 
QA test plan: [#13598 Facility Operating Status expansion test plan](https://docs.google.com/spreadsheets/d/1YUa8ujmnniU8E5VzqnSn8aG9iyOjypzrRazR0nKAVbE/edit?gid=0#gid=0)

## BLOCKER
Vets-website OS use the Lighthouse variant. So: we need to get our final list to LH, they need to provide info on what the API will return for these new statuses.

## Acceptance criteria
- [x] Normal operating status does not display
- [x] Existing not-normal operating statuses display More info using the same components that are used in prod today. (No changes to slim or expandable alert.)
  - [x] Facility notice - blue
  - [x] Limited services and hours - blue
  - [x] Facility closed - changes from red to yellow
- [x] New not-normal operating statuses display per Figma designs
- [x] Any behavior in final PR / build that differs from QA test plan expectations is identified, discussed with Product for signoff, and either QA test plan is updated or a ticket is created to modify that behavior to match the QA test plan

**Comment by jilladams** [comment]
Content-build version of this ticket is https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19825. We'll need help making sure this makes sense / is what was intended in story mapping.

**Comment by Agile6MSkinner** [comment]
Added table of options for reference

**Comment by laflannery** [comment]
@eselkin In doing the test plan I'm questioning if alerts show on Nearby locations on the VBA pages. I looked on every published VBA page and none of the locations pulling in happen to have a non-normal status so I can't confirm but I feel like they don't appear here currently. Are you able to confirm?

**Comment by eselkin** [comment]
Checking

**Comment by eselkin** [comment]
Part of the problem is on nearby the data comes from lighthouse.

**Comment by eselkin** [comment]
We can check if anything has a non-normal status by querying lighthouse for all VBAs in that system and checking status. I can try that for dev data.

**Comment by laflannery** [comment]
It's not VBAs, for Nearby locations you need to look at the other Facilities, I was using [the Drupal Facility status](https://prod.cms.va.gov/admin/content/facilities/facility-status) audit which is how I know that nothing currently pulling on Prod has a non-normal status. I just am not going to be able to test this in a tugboat because as you said, this comes form LH so I can't change it in Drupal and run c-r

**Comment by jilladams** [comment]
Removing from sprint, blocked on LH API for new OS.

**Comment by jilladams** [comment]
Eli clarified in 1:1 today: if we can get an API guarantee from LH on what the values will be for the new options, we could go ahead with this ticket. Asked for that here: https://dsva.slack.com/archives/C02BTJTDFTN/p1732128106743729?thread_ts=1731945395.067419&cid=C02BTJTDFTN

**Comment by jilladams** [comment]
FE changes for this work have been merged and deployed. Color changes are visible in prod; status options won't appear until the Drupal work ships and additional statuses start flowing through. I'm closing this ticket.
