### ISSUE TITLE
FE: Handle new Operating Status options on Modernized pages - content build

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#19825]
## Description
New operating statuses need to be built and displayed correctly per final designs on modernized pages for all facility types: 
  - VAMC System Locations page
  - VAMC System Operating Status page
  - VAMC System Page: [Example](https://www.va.gov/lovell-federal-health-care-tricare/)
  - VAMC facility page
  - VBA RO Modernized facility page
  - Vet Center facility page
  - Vet Center Location Page (Main & Satellite)

| #   | Status                     | Color  | Comment                                 |
| --- | -------------------------- | ------ | --------------------------------------- |
| 1   | Normal services and hours  | N/A    | Default option, does not appear on FE   |
| 2   | Limited service and hours  | Blue   | Changes from yellow to blue             |
| 3   | Closed                     | Yellow | A legacy option that will be phased out |
| 4   | Temporary facility closure | Yellow | New option                              |
| 5   | Temporary location         | Yellow | New option                              |
| 6   | Virtual care only          | Yellow | New option                              |
| 7   | Coming soon                | Yellow | New option                              |
| 8   | Facility notice            | Blue   | Should be listed last in Drupal         |

### Analytics considerations
Copy any existing analytics from current operating statuses

## Testing & QA
QA test plan written in #19808 
QA test plan will be run against the aggregate changes in FE work in #19809 
QA test plan: [#13598 Facility Operating Status expansion test plan](https://docs.google.com/spreadsheets/d/1YUa8ujmnniU8E5VzqnSn8aG9iyOjypzrRazR0nKAVbE/edit?gid=0#gid=0)

## Acceptance criteria
- [x] Normal operating status does not display except for VAMC operating status page
- [ ] Existing not-normal operating statuses display More info using the same components that are used in prod today. (No changes to slim or expandable alert.)
  - [ ] Facility notice - blue
  - [ ] Limited services and hours - blue
  - [ ] Facility closed - changes from red to yellow
- [ ] New not-normal operating statuses display per Figma designs
- [ ] Any behavior in final PR / build that differs from QA test plan expectations is identified, discussed with Product for signoff, and either QA test plan is updated or a ticket is created to modify that behavior to match the QA test plan

**Comment by jilladams** [comment]
Operating Status behavior varies across the page types listed in the ticket body. We need @eselkin 's help to clarify: from story mapping, the card was for "modernized pages - content build". The [test plan](https://docs.google.com/spreadsheets/d/1YUa8ujmnniU8E5VzqnSn8aG9iyOjypzrRazR0nKAVbE/edit?gid=0#gid=0) articulates how each Status behaves on each of these pages. Is this page sensible as written, or does it need revisions?

**Comment by jilladams** [comment]
Vets-website version of this ticket is https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19826

**Comment by Agile6MSkinner** [comment]
Added final list of statuses for reference

**Comment by omahane** [comment]
We tested the new statuses with Adam from Lighthouse (LH) in their Sandbox environment, and they passed. [Conversation in Slack](https://dsva.slack.com/archives/C02BTJTDFTN/p1731945395067419). LH plans to deploy the changes to production on Monday.

**Comment by jilladams** [comment]
The FE changes for this work have been merged and deployed. It's all moot until the Drupal work ships and additional statuses start flowing through. I'm closing this ticket.
