### ISSUE TITLE
[Discharge Upgrade Wizard] Broken link on results screen: "If you get a new DD214, request a copy"

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-cms#19844]
## Description

At the bottom of the Results screen, in the "What happens after I send in my application" accordion, there is a broken link:

- Clicking the following link results in a 404 error: "If you get a new DD214, request a copy (opens in a new tab)".results in an error 

The link should direct the user to https://www.archives.gov/veterans/military-service-records

Error 404--Not Found
From RFC 2068 Hypertext Transfer Protocol -- HTTP/1.1:
10.4.5 404 Not Found
The server has not found anything matching the Request-URI. No indication is given of whether the condition is temporary or permanent.

If the server does not wish to make this information available to the client, the status code 403 (Forbidden) can be used instead. The 410 (Gone) status code SHOULD be used if the server knows, through some internally configurable mechanism, that an old resource is permanently unavailable and has no forwarding address.

### User story

**AS A** Veteran who has completed the DUW wizard and is on the results screen, looking at the information in the accordion "What happens after I send in my application"
**I WANT** to click the link to obtain a new DD214 and have it take me to a site where I can submit my request
**SO THAT** I'm not frustrated by broken links or erroneous information.

### Scope / Impact analysis
_What, if anything, could break as a result of this change?_
_Engineer should assess this when approaching PR._

### Roles / assignments
_After functional testing, code review, accessibility review, and design review can happen in parallel._
- [ ] **Functional testing:** 
- [ ] **Code review:** 
- [ ] **Design review:** 
- [ ] **Accessibility review:** 
- [ ] **Product acceptance:** 

## AC / Expected behavior

**SCENARIO: Veteran clicks the link and a new tab opens to the correct site**
**GIVEN**: A veteran is on the results screen of Discharge Upgrade Wizard
**AND** they have expanded the accordion at the bottom of the screen: "What happens after I send in my application"
**WHEN**: they click the link in this sentence: If you get a new DD214, request a copy (opens in a new tab)
**THEN**: a new tab opens to this site:  https://www.archives.gov/veterans/military-service-records

- [ ] PM review/testing

**Comment by chriskim2311** [comment]
Verified on staging, closing!
