### ISSUE TITLE
Update the Manila url for operating status push

### ISSUE THREAD

**Issue by omahane** [department-of-veterans-affairs/va.gov-cms#19840]
## User Story or Problem Statement
The Manila VA Clinic needs to send the URLs of the system and facility when in the operating status information via the data push to lighthouse. Currently, the code has an exception for Manila that sends a TeamSite url.

## Implementation steps
Update the `getSystemOverrides()` in `va_gov_post_api/src/Service/PostFacilityStatus.php`.

## Acceptance Criteria
- [ ] When the operating status is updated, the POST API Queue item payload includes "https://va.gov/manila-va-clinic" as the facility URL 
- [ ] When the operating status is updated, the POST API Queue item payload includes "https://va.gov/manila-va-clinic" as the system URL

**Comment by jilladams** [comment]
@omahane since this merged Fri and will deploy today: any pro-tips on how we can verify for closing the ticket?

**Comment by omahane** [comment]
@jilladams This has been verified on prod.
![Image](https://github.com/user-attachments/assets/9925a959-d50d-4a00-815c-26b58fbc2fef)
