### ISSUE TITLE
VAMC real-time banners: cut over vets-website FE to using vets-api endpoint && make content-build use the new CMS feature toggle

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#19842]
### Vets-website / vets-api
Vets-website build will have built static version of the banner build. When the API is successfully returning data in Prod, we need to cut the vets-website FE build over to use the live vets-API. 

### content-build / CMS feature toggle
CMS feature toggle = `FEATURE_BANNER_USE_ALTERNATIVE_BANNERS`
When enabled, in content-build, the existing prod build of VAMC BwSU should *disappear*.

# ACs
- [x] FE vets-website VAMC BwSU uses vets-api endpoint (/banners)
  - [x] Still behind flipper
- [x] When CMS feature toggle FEATURE_BANNER_USE_ALTERNATIVE_BANNERS is enabled, in content-build, the existing prod build of VAMC BwSU should *disappear* across ALL templates

**Comment by jilladams** [comment]
@eselkin for VAMC banners with situation updates they can appear on any VAMC page. If we put the content-build code behind a CMS feature toggle, we need to do it everywhere they can appear. Could you sanity check a points estimate for that?

**Comment by randimays** [comment]
@eselkin @jilladams Yep, it's a 1. Feature toggles are small CMS repo changes. [Example here](https://github.com/department-of-veterans-affairs/va.gov-cms/pull/19653)

**Comment by jilladams** [comment]
Sorry misunderstanding. The CMS feature toggle already exists. This work is: 

In content-build, anywhere we display a VAMC Banner with Situation updates, we need to update the content-build markup to put it _behind_ that CMS feature toggle. When the feature toggle is on, the content-build markup is hidden. When it is off, the content-build markup displays.

The root of the question is: how many places are VAMC BwSU and how wild will that be, in points.

**Comment by eselkin** [comment]
Taking a look at where banners are. It's just VAMC system and facility banners right?

**Comment by jilladams** [comment]
Yes, exactly -- not full width alerts that sit in/ under the header yet

**Comment by eselkin** [comment]
Just checking which banners the BwSU are replacing... 
If the CMS feature toggle FEATURE_BANNER_USE_ALTERNATIVE_BANNERS is on
ONLY the 
`data-widget-type="situation-updates-banner"` should be used
otherwise
the visible banner(s) from `banners` that come from drupal should be shown
right?

**Comment by SnowboardTechie** [comment]
> Just checking which banners the BwSU are replacing... If the CMS feature toggle FEATURE_BANNER_USE_ALTERNATIVE_BANNERS is on ONLY the `data-widget-type="situation-updates-banner"` should be used otherwise the visible banner(s) from `banners` that come from drupal should be shown right?
> 
> Currently both are not showing because:
> 
> 1. A system or some other page may not have a banner
> 2. The current vets-api toggle is false so vets-website does not render it
>    `..."name": "bannerUseAlternativeBanners",  "value": false`

Spot on from my understanding as well. With that toggle enabled we will be both ENABLING the new banners (functionality set today with static banner) and after this work, DISABLING the old banners as well.

**Comment by jilladams** [comment]
We've seen this working in Tugboat as a result of PRs that have merged to main. I think we can close this ticket and open new ones to follow up on any bugs found during QA. (But if you find things that are easy to throw into PR, feel free to use this ticket as the reference.)
