### ISSUE TITLE
[Discharge Upgrade Wizard] Results page is missing text on Step 3 for the Navy logic flows for service '> 15 years' prior

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-cms#19841]
## Description

Step 3 of the subway map is not always filling in the area after "you must apply to" when the branch of the military is Army, and service is 15 years or more ago.

On Staging (noted in the scenario in Steps to Reproduce) there is missing text in the first paragraph, just after the Step 3 title: **Mail your completed form and all supporting materials**

- **Prod's paragraph shows:**  "There are a number of different boards that handle discharge upgrades and corrections. Based on your answers on the previous page, you need to apply to the BCNR for the Navy. This is because the Board handles all cases from 15 or more years ago."

![Image](https://github.com/user-attachments/assets/e381fa6b-1f3a-44a4-a654-68850b0761f1)

- **Staging's paragraph shows:** "There are a number of different boards that handle discharge upgrades and corrections. Based on your answers on the previous page, you need to apply to"
- 
![Image](https://github.com/user-attachments/assets/f8c097f0-ef4a-44f0-b450-5ad63bf3f3e9)

## Steps to recreate

**Version of DUW**
- https://staging.va.gov/discharge-upgrade-instructions
- https://www.va.gov/discharge-upgrade-instructions/

**Answers**
- Navy
- 2008
- Reasons for discharge (note that if reason wanting to change is transgender, the info isn't missing):
  - I suffered from an undiagnosed, misdiagnosed...PTSD... AND
  - I suffered from an undiagnosed, misdiagnosed...TBI... AND
  - I was discharged due to my sexual orientation, AND
  - I experienced sexual assault or harassment during my service, AND
  - No, I want to change only my characterization of discharge, re-enlistment code, separation code, or narrative reason for discharge, AND
  - No, I want to change only my characterization of discharge, re-enlistment code, separation code, or narrative reason for discharge.
- No, I want to change only my characterization...
- No, my discharge was administrative...
- I have not previously applied
- No, I didn't complete earlier period of service

### Scope / Impact analysis
_What, if anything, could break as a result of this change?_
_Engineer should assess this when approaching PR._

### Roles / assignments
_After functional testing, code review, accessibility review, and design review can happen in parallel._
- [ ] **Functional testing:** 
- [ ] **Code review:** 
- [ ] **Design review:** 
- [ ] **Accessibility review:** 
- [ ] **Product acceptance:** 

## AC / Expected behavior
- [ ] for logic flow where the Veteran needs to submit to BCNR, AND military branch is Navy, the first paragraph on the results page just after the Step 3 titled: **Mail your completed form and all supporting materials** should be: "There are a number of different boards that handle discharge upgrades and corrections. Based on your answers on the previous page, you need to apply to the BCNR for the Navy. This is because the board handles all cases from 15 or more years ago.." 
- [N/A] Does this product have an existing regression test plan? Not yet. A regression plan will NOT be created as part of this ticket.

**Comment by chriskim2311** [comment]
This ticket has been completed with [#19599](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19599).

Prod v2: 
![Image](https://github.com/user-attachments/assets/24435b18-3bba-4fa1-9aa3-0daef9254473)
