### ISSUE TITLE
Next-build Manila:  breadcrumbs are not working

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#19862]
## Descriptions
The breadcrumbs are not working for me. When I clicked the "Manila VA Clinic" crumb, I was taken to a 404 page. However there is a chance that this is a Tugboat issue, perhaps the facility is actually not published?

https://va.gov/manila-va-clinic

### Acceptance criteria
- [ ] Breadcrumbs on VA Manila clinic pages 
- [ ] The repro steps result in 'expected result'
- [ ] An automated test is written to catch the problem, if appropriate

**Comment by jilladams** [comment]
@laflannery to verify if the breadcrumb link is correct before clicking. Because now we know: the page probably 404s because that template isn't built in Next yet. If link is correct, this can close as no-op.

**Comment by laflannery** [comment]
I confirmed that the breadcrumb link is correct:

![Image](https://github.com/user-attachments/assets/b9513723-8dd6-492f-b7b5-a494f4f59320)
