### ISSUE TITLE
CMS Request: Sitewide VAMC Realtime Banners

### ISSUE THREAD

**Issue by gracekretschmer-metrostar** [department-of-veterans-affairs/va.gov-cms#19865]
## User Story or Problem Statement
As CMS team member, I need to review the Sitewide real-time banner solution to ensure it's in alignment with the CMS platform.

## Relevant Links
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/96762

## Description or Additional Context 
There needs to be an engineering review for this work. See if the CMS team member to be involved in the architecture intent meeting. Possibly pull in Tim, Edmund, and Tyler. 

## Acceptance Criteria
- [ ] CMS engineer, design, accessibility, and QA review of real-time banner solution. 
- [ ] CMS intake form is submitted by Sitewide and CMS team has reviewed and provided feedback.

**Comment by jilladams** [comment]
@gracekretschmer-metrostar FYI that the collab cycle didn't suggest Architecture Intent as a touchpoint for this one. We'll be figuring out with Michelle on Monday if we need Design Intent or not. If not, we'll go straight to Staging Review. Let @Agile6MSkinner if you want your folks to be pulled in anywhere specifically, in that case.

**Comment by Agile6MSkinner** [comment]
@gracekretschmer-metrostar We are not doing Design Intent. Staging review is scheduled for 20-Dec.

**Comment by jilladams** [comment]
Grace clarified that we can invite Grace & Tim to architecture intent, to satisfy the CMS portion of collab cycle for this feature.
