### ISSUE TITLE
VAMC real-time banners: run QA test plan and verify all feature work

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#19887]
## Description

[Link to Test plan](https://docs.google.com/spreadsheets/d/1PUgwtG8_NXnc54DzYw6bKCYG-Lfmq0rfNL1Va3URLZ4/edit?gid=0#gid=0)

**Audit of All Published banners:** /admin/content/vamc-alerts-and-statuses?field_alert_type_value=All&type=full_width_banner_alert&moderation_state=All&status=1&field_administration_target_id=All

## Test setup process:
**Run on a Tugboat environment**

**VAMC Real-Time banners Tugboat env: https://tugboat.vfs.va.gov/675235dfe2b213c93505aa4a**

1. Enable new alternative banners by enabling the vets-website flipper `banner_use_alternative_banners` in the dev flipper UI: https://dev-api.va.gov/flipper/features (this controls Tugboat)
2. Confirm that we see duplicate banners - the content-build banners and the new banners (this should be quick, under 5 mins)
3. Once we confirm, we disable the new banners by disabling the vets-website flipper
4. Before you start, confirm if these changes are in `main` or in another branch
5. We now turn off the content-build banners by enabling the CMS toggle `FEATURE_BANNER_USE_ALTERNATIVE_BANNERS` in the Tugboat CMS: /admin/config/system/feature_toggle
6. Run content-release (/admin/content/deploy) with vets-website branch `main` and the content-build branch from step 5
7. Wait about 1 hour and confirm on the Release content screen that build was successful
8. Confirm all banners are gone from the Front end
9. Then turn back on the new banners by re-enabling the vets-website flipper
10. Confirm that within 5 mins the banners are showing again.

Also: run the regression test cases, and all cases in the [spreadsheet](https://docs.google.com/spreadsheets/d/1PUgwtG8_NXnc54DzYw6bKCYG-Lfmq0rfNL1Va3URLZ4/edit?gid=0#gid=0)

## Acceptance criteria
- [ ] Test plan has been run 
- [ ] Failing tests are flagged for Product review re: whether they should block Staging Review or launch

**Comment by laflannery** [comment]
@jilladams and @Agile6MSkinner I assigned you so you can easily find this if needed on Friday but feel free to unassign if you want/don't end up doing this

**Comment by jilladams** [comment]
From slack today: 
* Laura has tested basic banner functionality
* Regression testing the remainder of operating status functionality / govdelivery stuff to ensure nothing has changed is still in progress. 

That'll wrap in the next few days.

**Comment by laflannery** [comment]
Passed done!! WOOOOOO!
