### ISSUE TITLE
Sort content types alphabetically

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#1989]
## User Story or Problem Statement

As an editor adding content, i want content types to be sorted alphabetically, so that i can find them more easily. 

## Acceptance Criteria
- [ ] Content types on /node/add are sorted as expected, alphabetically
- [x] Content types via the admin menu are sorted the same way (done in #1996)
 
## Implementation steps

- Consider this [drupal core patch](https://www.drupal.org/project/drupal/issues/2693485)

**Comment by acrollet** [comment]
The linked core issue is still in 'needs review' as of 9.2 - I propose that we instead override node/add with our own callback, and see the following benefits:

- avoid the overhead of keeping up with the core patch for the next 4+ revisions of drupal core
- allow for future VA-specific enhancements to the page (e.g. grouping by product)

@kevwalsh @oksana-c thoughts?

**Comment by oksana-c** [comment]
@acrollet , I agree w/ your recommendation of avoiding a patch. Let's go w/ a custom solution for sorting node/add entries.
