### ISSUE TITLE
Remove all composer dependencies from dependabot except content-build

### ISSUE THREAD

**Issue by edmund-dunn** [department-of-veterans-affairs/va.gov-cms#19894]
## User Story or Problem Statement
We need a better process for updating dependencies that gives us better control of the QA process. By removing all of the composer dependencies from dependabot and starting a process of updating them manually every other sprint, we will be able to manually QA all updates.

## Description or Additional Context 
Given the large number of patches we use, many of the updates end up requiring manual intervention anyway. We often have to remove, reroll or add patches. 

We will still use dependable to update the content-build dependency every night and to update the GitHub actions dependencies. 

## Steps for Implementation
- list all composer dependencies as `ignore:` in `.github/dependabot.yml`
- document new process, including the need to add new modules to `.github/dependabot.yml`
- communicate changes to drupal devs

## Acceptance Criteria
- [ ] `dependabot.yml` updated
- [ ] Documentation updates
- [ ] Communicated changes to devs

**Comment by gracekretschmer-metrostar** [comment]
Next steps with this ticket is to create a process to generate tickets to be added every other sprint to manage any dependabot tasks that need to be covered by the CMS team.
