### ISSUE TITLE
Operating status: KB article updates

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#19904]
## Description
All change management activity needed to roll out updated Operating Statuses. 

### KB Updates
* VBA - https://prod.cms.va.gov/help/veterans-benefits-administration-vba/how-do-i-update-my-vba-facility-operating-status
* Vet Center (includes CAPs/Outstations) - https://prod.cms.va.gov/help/vet-centers/how-do-i-update-my-vet-center-facility-operating-status
* VAMC overview of statuses - https://prod.cms.va.gov/help/vamc/about-locations-content-for-vamcs/about-alerts-and-operating-statuses 
* VAMC  specifics - https://prod.cms.va.gov/help/vamc/about-locations-content-for-vamcs/about-alerts-and-operating-statuses/how-to-edit-a-vamc-facility-operating-status
* NCA - https://prod.cms.va.gov/help/va-cemetery-facilities-nca/how-to-edit-the-operating-status-of-an-nca-facility

## Acceptance criteria
- [x] Save draft revisions on the KBs listed above:  
  - [x] to describe the additional statuses
  - [x] to update the alignment of the "Details"/"More info" fields across content types from #19805

**Comment by jilladams** [comment]
Assigning to @mmiddaugh per scrum convo today.

**Comment by mmiddaugh** [comment]
- VBA: [How do I update my VBA facility operating status?](https://prod.cms.va.gov/node/53697/latest) is in draft. Content is approved by VBA partners. 
- VAMC: [About VAMC alerts and operating statuses](https://prod.cms.va.gov/node/6868/latest) and [How to edit a VAMC facility operating status](https://prod.cms.va.gov/node/6869/latest) are in draft and pending approval from VHA partners
- Vet Center: [How do I update my Vet Center facility operating status?](https://prod.cms.va.gov/node/44122/latest) is in draft pending RCS approval.

All will need updated images when Drupal UI is exposed

**Comment by mmiddaugh** [comment]
An updated version of [How to edit the operating status of an NCA facility](https://prod.cms.va.gov/node/41809/latest) is also now in draft
