### ISSUE TITLE
[Facility Locator] [UX] Provide designs to display cemetery services on Facility Locator

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-cms#19916]
## Description
The Facility Locator allows Veterans to search for national and VA grant-funded cemeteries (State, Territory and Tribal Veterans Cemeteries) but does not include information about the funeral and burial services available. The need to include these details was emphasized during a Subcommittee on Disability Assistance & Memorial Affairs Oversight Hearing on 11/13/2024. ([1:20 mark](https://www.youtube.com/watch?v=hsouKUKgYkM))

The national cemetery data source includes a status field with possible values of "Open", "Closed", or "Cremation Only" representing whether or not the cemetery has space for new, subsequent, or cremation only interments. Equivalent data is not yet available in the data source for grant-funded cemeteries. 

Information about burial space is displayed on NCA's [Find a Cemetery page](https://www.cem.va.gov/find-cemetery/) and on cemetery detail pages. 

Once this data is available in the Lighthouse API, we should be able to make the information available in the Facility Locator. MVP may be brief description on Facility Locator search results card and inclusion on the detail page. 

We need designs to represent our needs. See very rough mockups below created just to illustrate what's needed and on what tile/pages.

**_Note: We may get updated wording from stakeholders._**

## High-level Requirements
- Cemetery Search results cards, instead of the actual status; instead display the following wording as a link to the cemetery detail page:  Find out about available burial space
- Cemetery Detail page: 
  - Display one of four statuses, along with the definition for each. Note that the statuses will not be custom for each cemetery; they will be one definition for each status.
    - Open 
    - Closed
    - Cremation Only
    - Under Construction

## Additional Information:
  - Lighthouse will provide the schema (they are trying to get it to us before Christmas).
  - LH will provide both the status and definitions in the LH API (this info is already in the data).
  - There are nationals and state. We are trying to harmonize everything regardless of type of cemetery.

## Questions
- Question: Will the status and definitions be in the main data? Or services addendum? Or some new endpoint? We will need to update Vets-api if not in the main data. 
  - Answer: Michelle believes it's in the main data but will confirm.
- Question: What if there is no status?
  - Assume everything will have a status.
- What about offices?
  - Offices may get pulled out of the data.

### Design

[Facility Locator Cemetery Services page](https://www.figma.com/design/GvNVeG9GAXZaBpny7vNxZP/Facility-Locator?node-id=1355-17020&t=AfVw5EicYQ9npcM7-1)

### Examples
Cemetery pages have a range of descriptions for open and closed, based on new vs subsequent for Veterans vs family members. Definitions will be confirmed with NCA. "Call for status" may be be needed. 

<details>
<summary> Examples </summary>

Fort Missoula Post Cemetery
- Data: status = Closed 
- On the [Find a cemetery page for Montana](https://www.cem.va.gov/find-cemetery/state.asp?STATE=MT) - Burial Space: Closed 
- On the [NCA Fort Missoula Post Cemetery page](https://www.cem.va.gov/cems/nchp/FtMissoula.asp) - [BURIAL SPACE] Fort Missoula Post Cemetery is currently closed to new interments. The only interments that are being performed are subsequent interments for Veterans or eligible family members in an existing gravesite.

Yellowstone National Cemetery
- Data: status = Open
- On the [Find a cemetery page for Montana](https://www.cem.va.gov/find-cemetery/state.asp?STATE=MT) - Burial Space: Open
- On the [NCA Yellowstone National Cemetery page](https://www.cem.va.gov/cems/nchp/Yellowstone.asp) - [BURIAL SPACE] This cemetery has space available to accommodate casketed and cremated remains.

Woodlawn National Cemetery
- Data: status = Cremation only
- On the [Find a cemetery page for New York](https://www.cem.va.gov/find-cemetery/state.asp?STATE=NY) - Burial Space: Open
- On the [NCA Woodlawn National Cemetery page](https://www.cem.va.gov/cems/nchp/Woodlawn.asp) - [BURIAL SPACE] This cemetery has space available for cremated remains in a columbarium only.

</details>

### Figma Designs

https://www.figma.com/design/GvNVeG9GAXZaBpny7vNxZP/Facility-Locator?node-id=1355-17020&t=AfVw5EicYQ9npcM7-1

### User story

**AS A** Veteran, family member, or other beneficiary searching for cemeteries on the Facility Locator
**I WANT** to know whether or not the cemeteries in my search results are open to new interments
**SO THAT** I can easily plan a burial. 

### Engineering notes / background
Similar pattern - Search result cards for community emergency and urgent care locations include "Call to confirm services and hours"

### Scope / Impact analysis
_What, if anything, could break as a result of this change?_
_Engineer should assess this when approaching PR._

### Roles / assignments
_After functional testing, code review, accessibility review, and design review can happen in parallel._
- [ ] **Functional testing:** 
- [ ] **Code review:** 
- [ ] **Design review:** 
- [ ] **Accessibility review:** 
- [ ] **Product acceptance:** Michelle Middaugh and Fran Cross

## Acceptance criteria
_ACs should capture expected behavior, to inform test plans. Consider devices, documentation updates including KBs, change management, and [content model](https://prod.cms.va.gov/admin/structure/cm_document) when applicable._

MVP AC

- [x] Design should show on the Facility Locator search results card the status received from Lighthouse e.g. 'Burial Space: Closed to new interments', 'Burial Space: Cremation Only', 'Burial Space: Open to new interments'
- [x] Design should show on the Facility detail page the more detailed info received from Lighthouse  e.g. 'Burial Space: Closed to new interments', 'Burial Space: Cremation Only', 'Burial Space: Open to new interments'
- [x] Consider whether we include full definition of each status on the FL Detail page, or redirect them to the Teamsite pages for that. **Update:** Decision was made to include full definition on detail page to reduce the amount of clicks for users. 
- [x] If there is no status from Lighthouse, display both on the search results tile and the FL results screen: 'Burial Space: Call for availability

**Comment by FranECross** [comment]
@thejordanwood to work on this on next sprint.

**Comment by jilladams** [comment]
@thejordanwood FYI that this one we are considering a sprint goal. Holler if you have concerns.

**Comment by mmiddaugh** [comment]
@thejordanwood @FranECross 
Two updates:
- It's been proposed that "Closed" should be displayed as "Call for status" because a given cemetery may accept subsequent burials (as in a burial in the same plot as a spouse or family member) or have updated availability 
- Veterans calling in these situations actually need to call the parent cemetery, rather than the phone number associated with the cemetery. The example given: if a Veteran wants details regarding the status for Philadelphia National Cemetery (nca_819), he or she would need to call Washington Crossing National Cemetery (nca_926), which administers Philadelphia National Cemetery. We're working with NCA and Lighthouse to understand how to get that data. From a UX perspective, we need to consider how to present this to Veterans, especially in the search result card. (I discovered the two phone numbers in this example are actually the same but I'm not sure that is true across all cemeteries)

**Comment by eselkin** [comment]
Just want to make sure we correct internments to interments if it's written that way elsewhere.

**Comment by jilladams** [comment]
What a very important piece of nuance I have never thought about ever in my life til just now.

**Comment by thejordanwood** [comment]
Thanks @eselkin! You saved a couple of my mockups and I corrected it in the ticket too.

**Comment by thejordanwood** [comment]
Designs are ready for review in [this Figma file](https://www.figma.com/design/GvNVeG9GAXZaBpny7vNxZP/Facility-Locator?node-id=1355-17020&t=AfVw5EicYQ9npcM7-1). I started [a thread in Slack](https://dsva.slack.com/archives/C06S9DADEUB/p1733265679646469) to get UX review on this.

**Comment by eselkin** [comment]
I mean you can be interned and interred at the same time, which would just be horrendous and I don't recommend.

**Comment by mmiddaugh** [comment]
@FranECross @thejordanwood in conversations with NCA today, we learned 

- we should not need to display more than one phone number for a given cemetery. The best number to call is already represented in the data (meaning, the data already has the "parent" number, if  needed for the location) and all questions can be directed to that number. Will confirm with NCA leadership but feels 90% settled. 
- burial status definitions will soon have an anchor tag, making it easier to link directly to them, if that is preferred over displaying them on the detail page itself.  (We may want to continue displaying the definition as a service to Veterans and efficiency)

**Comment by thejordanwood** [comment]
**End of sprint update:**

Latest designs are in [this Figma file](https://www.figma.com/design/GvNVeG9GAXZaBpny7vNxZP/Facility-Locator?node-id=1355-17020&t=4sXJzOZRPE6rOU7l-1) and have been reviewed. We have some open questions that need to be answered before the designs can be completed and this ticket can close:

1. What should we display when there's no status for cemeteries? What should we display when there's no status for offices that appear in the cemetery search?
3. What will the status definitions be for open, closed, and cremation only? This may determine wether we link to teamsites for more information from the detail pages. 
4. What's in scope for this work? I proposed alternative layout changes on the detail pages to help align with the content structure on VAMC location pages. We may need to have designs finalized before we're able to determine this. 

cc: @FranECross @mmiddaugh

**Comment by thejordanwood** [comment]
**End of sprint update:**

We discussed this in UX sync on 12/19 and the designs have been updated. Here are the answers to my questions I had last sprint:

> 1. What should we display when there's no status for cemeteries? What should we display when there's no status for offices that appear in the cemetery search?

- We need to remove specific statuses from the search results screen and add a generic link that says "Learn more about burial status"
- Offices may get pulled from the data so they don't show. We should also operate under the assumption that all cemeteries will have statuses. 

> 2. What will the status definitions be for open, closed, and cremation only?

- We need to add "Under construction" as a status 
- Details pages will have standard definitions for all 4 statuses. TBD on those. 

> What's in scope for this work?

- @FranECross It sounds like the alternate layout will be in scope for this work so that we can align with [VAMC location pages](https://www.va.gov/south-texas-health-care/locations/). Please correct me if I'm wrong.

@FranECross Given the new info and that the mockups are as updated as they can be for now, I think this is good to close. I can create a follow up ticket to update the mockups with the status definitions whenever we receive those. Let me know if that sounds good to you!

**Comment by thejordanwood** [comment]
I created a follow up ticket for this whenever we get status definitions. [#20164](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/20164)
