### ISSUE TITLE
Update document upload help text

### ISSUE THREAD

**Issue by srancour** [department-of-veterans-affairs/va.gov-cms#19912]
## User Story or Problem Statement
As an editor I need to know how to make my PDFs accessible while uploading my documents.

## Description or Additional Context 
The help text on the [Document settings for Document](https://prod.cms.va.gov/admin/structure/media/manage/document/fields/media.document.field_document) page needs to be changed from `For PDFs, please make sure the text can be cleanly copied out of the file – simple formatting is best.` to `For PDFs, please make sure that it has been made to be accessible. Accessibility standards for PDFs can be accessed in the <a href="/help/va-directive-6102#accessibility" target="_blank">VA Directive 6102 KB article's Accessibility section (opens in a new tab)</a>.`

## Acceptance Criteria
- [ ] Help text has been changed and the link to the KB article is included.

**Comment by gracekretschmer-metrostar** [comment]
Jake will pair with Steve when he does this work.

**Comment by JakeBapple** [comment]
For reference:
git pull main
git checkout new branch for work
ddev drush deploy (this will start your branch clean)
make changes in the UI or in files and save
ddev drush cex (this will show you the updated files you want to push)
commit those files
push upstream to make a PR
