### ISSUE TITLE
Rename pharmacy top task link on VAMC Facilities

### ISSUE THREAD

**Issue by Agile6MSkinner** [department-of-veterans-affairs/va.gov-cms#19913]
## Description
The current Top Task link for Pharmacy information on VAMC facilities is a bit misleading. We have been requested by VHA to rename it to "Learn about pharmacy services"

### User story
**AS A** Veteran or service member visiting a VAMC facilities page
**I WANT** the pharmacy information page link text to more accurately describe what I will see when I click
**SO THAT** I can make a more informed decision about clicking the link and/or be prepared for the information I am going to see on that page

![Image](https://github.com/user-attachments/assets/13653d00-7795-45da-be79-f29f2ff4b7a2)

## Acceptance criteria
- [ ] Link text reads as "Learn about pharmacy services"
- [ ] Change is reflected on health services pages and facilities pages
- [ ] Make sure that Lovell works like everything else.

**Comment by jilladams** [comment]
Related VHA DM trello card: https://trello.com/c/3m9M08qP/262-vamc-pharmacy-link-text-to-pharmacy-information

Related notes from Michelle in #sitewide-facilities: 
 https://dsva.slack.com/archives/C0FQSS30V/p1732048480279529

**Comment by randimays** [comment]
Pulling in as stretch for sprint 17.
