### ISSUE TITLE
Progressive disclosure: Write a QA test plan

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#19919]
## Description
#19489 is the epic for Facility Locator progressive disclosure. We need to write a test plan that: 

1. Harnesses the existing [Facility Locator regression test](https://docs.google.com/spreadsheets/d/1wgIM4oIwAQk-E151z07P3hhZuQJ6mhepv7U5tZjdpEI/edit?gid=0#gid=0) document, to articulate: which of these test cases need to be run, with respect to the Progressive Disclosure epic.
2. Specifies testing for the Progressive Disclosure testing, specifically

### Empty Sheet to populate 
[19489 FL Progressive disclosure test plan](https://docs.google.com/spreadsheets/d/1wgIM4oIwAQk-E151z07P3hhZuQJ6mhepv7U5tZjdpEI/edit?gid=1755592601#gid=1755592601)

### Functionality that will be added and needs to be accounted for
- New design of FL filter fields/area
  - All breakpoints
- Services Selector only displays when it should
- Loading Animation shows when waiting for display of Community care services field
  - If Community care field fails to load, error Message displays instead

## Acceptance criteria
- [x] Test plan is updated in [19489 FL Progressive disclosure test plan](https://docs.google.com/spreadsheets/d/1wgIM4oIwAQk-E151z07P3hhZuQJ6mhepv7U5tZjdpEI/edit?gid=1755592601#gid=1755592601) to capture
  - [x] Necessary regression test cases for FL that should be run
  - [x] New test cases for Progressive disclosure changes 
- [x] Does this product have an existing regression test plan?
	- [x] Yes: [Facility Locator regression test](https://docs.google.com/spreadsheets/d/1wgIM4oIwAQk-E151z07P3hhZuQJ6mhepv7U5tZjdpEI/edit?gid=0#gid=0)

**Comment by jilladams** [comment]
I've added an AC to the ticket for running the test plan, to make sure the regression test plan is updated with final changes to current prod behavior: #19920

**Comment by laflannery** [comment]
@jilladams and @Agile6MSkinner I believe I'm done with this but I also think there might be some unnecessary tests I left in/cleaned up and would like a sanity check on. For example I'm not sure we need to actually run searches, but I'm not positive?

We haven't really established a process for review or acceptance of QA test plans so I don't know what would be best here. Otherwise, the AC are complete and this is done
