### ISSUE TITLE
Remove PDFs and capture content into Knowledge Base

### ISSUE THREAD

**Issue by gracekretschmer-metrostar** [department-of-veterans-affairs/va.gov-cms#19917]
## User Story or Problem Statement
As an editor using screen reader, I want to be able to easily access content in the Knowledge Base and PDFs block that experience. 

As a member of the 508 office, I need to see progress in resolving the PDF issues I reported in the our audit of CMS. 

## Steps for Implementation
- Take the 3 PDFs in Knowledge Base and convert them into content in the HTML pages. 
- Remove the PDFs from the Knowledge Base. 

## Acceptance Criteria
- [ ] The 3 PDFs that have not been made accessible have been removed and the Knowledge Base and their contents are now in pages within the Knowledge Base.

**Comment by srancour** [comment]
[CMS KB content strategy statement article](https://prod.cms.va.gov/node/28394/latest) updated and ready for review

**Comment by srancour** [comment]
Created a new page for the [Orientation presentation](https://prod.cms.va.gov/help/get-training/drupal-cms-orientation) and created a draft of the [Get training article](https://prod.cms.va.gov/node/6884/latest) that changes the presentation download into a link to the Orientation page

**Comment by srancour** [comment]
[How to access and manage demo environments](https://prod.cms.va.gov/help/how-to-access-and-manage-demo-environments) page was updated and the PDF was removed from the active article. Also published all of the changes to the KB.
