### ISSUE TITLE
Gather Information about Users who have previous Experienced PIV Card Issues

### ISSUE THREAD

**Issue by gracekretschmer-metrostar** [department-of-veterans-affairs/va.gov-cms#19924]
## User Story or Problem Statement
As a CMS member, I am trying to get to the root cause of the PIV Card issue and need the most up-to-date information about these users experience with the defect. 

## Description or Additional Context 
There a re-emergence of reports from users that are experiencing the PIV card issue. 

## Known Users with this Issue
- Randi Hecht
- Sara Torres
- Beth Potts 
- Linda Wondra
- Megan Zehnder
- Clifford Coy

## Steps for Implementation
- Reach out to the known users with this issue to get an update if they are experiencing this issue.
- Re-enable the banner, notifying editors of this PIV card issue and if they are still experiencing the issue, reach out to the help desk.
- Document findings in this ticket. 

## Acceptance Criteria
- [ ] Documentation linked to this ticket for all users that still experiencing this issue.

**Comment by ian-sears** [comment]
Cross referencing ticket work began here: [#18859](18859)

And gathered Editor browser version numbers being used - [spreadsheet](https://hitssllc-my.sharepoint.com/:x:/p/troy_griffin/ERNitSMWjqZIslT786477m8BjYW1TvsG3JgvXisQ-ht3yA?rtime=QAF-gZcJ3Ug&nav=MTVfezI4Njc0QURDLUNENUUtNDhDNC1BRUYyLUI2MjRCNjdBRDQyOH0)
