### ISSUE TITLE
Zhuzh the Mobile Map Figma designs

### ISSUE THREAD

**Issue by Agile6MSkinner** [department-of-veterans-affairs/va.gov-cms#19928]
## Description

It's been a while since we looked at mobile map designs. Review designs, make any changes, and update annotations to the new style. 

## Design

[Mobile map designs](https://www.figma.com/design/GvNVeG9GAXZaBpny7vNxZP/Facility-Locator?node-id=0-4407&t=z5S83hjZcYQDCDz9-1)

## Design revisions

- [x] Remove filter functionality. This isn't being implemented at this time.

## New component

We're proposing that the [USWDS segmented button group](https://designsystem.digital.gov/button-group/button-group--segmented/) replace the current View List/View Map tabs. We need to determine how to get approval from the Design System team to use this (submit an experimental design request, have a design review collab, etc.). 

## Acceptance criteria

- [x] Update annotations to new style
- [x] Add any additional design and accessibility annotations
- [x] Determine next steps for segmented button group approval
- [x] Review with UX Lead, FE engineering, Product, Accessibility

**Comment by thejordanwood** [comment]
I've added the segmented button group design [in the comments on this previous experimental design ticket](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2346#issuecomment-2539696170) and submitted [a request](https://dsva.slack.com/archives/C01DBGX4P45/p1734027265035039?thread_ts=1733950506.796409&cid=C01DBGX4P45) to have the Design System Council review this at their next available opportunity on Jan 16.

**Comment by thejordanwood** [comment]
Annotations have been added and everyone has reviewed. Going to close this since the main work has been completed and will attend the DSC meeting on Jan 16.
