### ISSUE TITLE
Launching VBA Facility: Little Rock VA Regional Benefit Office at Eugene J. Towbin Healthcare Center

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-cms#19946]
## Intake
- [x] What triggered this runbook? (Slack notification, Helpdesk ticket, etc)
Trigger: Published approved Regional office page

- [x] Link to facility in production:
Facility CMS link: [Drupal node for Little Rock VA Regional Benefit Office at Eugene J. Towbin Healthcare Center](https://prod.cms.va.gov/little-rock-va-regional-benefit-office-at-eugene-j-towbin-healthcare-center)

### Prerequisites to publish
- [x] Verify with Michelle Middaugh that VBA leadership completed content review and approved publishing. When Michelle has acknowledged the request, JIRA may be closed. (_no JIRA issues was created- the editor contacted Michelle directly_)
- [x] Verify that all VBA Facility Services for this Facility have been set to Published. - https://prod.cms.va.gov/admin/content?title=&type=vba_facility_service&moderation_state=All&owner=1090
- [x] Verify that no major changes have been made directly in Drupal to data from migrations, such as Facility name, location, or contact information.
  - [ ] If any changes of that kind have been made in Drupal, provide the Editor with a link to [VBA location and contact information: How to Edit](https://prod.cms.va.gov/help/veterans-benefits-administration-vba/location-and-contact-information#how-to-edit) for instructions on how to properly make those changes.

### Publishing
- [x] Set the VBA Facility to Published, and note approvals in the revision log
- [x] Ask Michelle Middaugh to update the facility URL in Sandy's Database to the modernized URL. This eliminates the need for a URL change request ([LH confirmed](https://dsva.slack.com/archives/C02BTJTDFTN/p1730395863667449?thread_ts=1730395217.135779&cid=C02BTJTDFTN)).
- [x] Create a redirect request -> [#97721](https://github.com/department-of-veterans-affairs/va.gov-team/issues/97721)
  - [x] **Indicate in ticket** that this is a [page level redirect for a Teamsite using the injected header](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/redirect-implementation-strategy.md#3-subdomain--vagov-page-level-cross-domain-redirect-for-a-subdomain-that-loads-proxy-rewrite-js) -- it can be done within proxy rewrite as a client-side redirect

## Facilities PM / DM tasks
- [x] Verify that TeamSite redirect is complete
- [x] Verify that Facility Locator / LIghthouse redirect is complete
- [x] Notify Michelle when redirects are complete so she can notify the editors

**Comment by jilladams** [comment]
@mmiddaugh The Little Rock teamsite is now being redirected correctly to the modernized page, but the Facility Locator detail page doesn't redirect yet: https://www.va.gov/find-locations/facility/vba_350.  Pretty sure that's a change you need to make in Sandy's DB, but please let me know if that's incorrect.

**Comment by jilladams** [comment]
Michelle confirmed she updated Sandy's. Asking Adam to make sure there's not a LH issue, but might be that we do have to do redirects. https://dsva.slack.com/archives/C02BTJTDFTN/p1734566749186089

**Comment by jilladams** [comment]
Takeaway: the FL detail page will remain accessible. What we're checking for is that when you search the RO in the FL, the link you get to the search result points correctly to the modernized page and not the FL detail page. I'll update the template so I don't forget this again in future. CLosing!
