### ISSUE TITLE
VAMC real-time banners staging review: QA artifacts

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#19943]
## Description

The following QA artifact needs to be completed for the Staging review of Alternative Banners: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/medical-centers/initiatives/2024-real-time-banners/testing-qa.md

**Examples we can follow**
* React app: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/veteran-military-records/discharge-upgrade-wizard/initiatives/2024-discharge-upgrade-wizard-subtask/testing-qa.md
* React app: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/pact-act-wizard/initiatives/2023-2024-launch/testing-qa.md
* Drupal > content-build example: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/regional-offices/initiatives/2023-2024-pilot-mvp/testing-qa.md

## AC
- [ ] [QA artifact](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/medical-centers/initiatives/2024-real-time-banners/testing-qa.md) is updated, reviewed and ready for Staging Review and added to https://github.com/department-of-veterans-affairs/va.gov-team/issues/96762 (as noted in the Platform guidance: You are free to provide this information to Governance Team in whatever format is most convenient

**Comment by jilladams** [comment]
@SnowboardTechie @dsasser we assigned this for y'all in planning and you may be able to divide and conquer or just decide who will own making the artifact. @eselkin created the VBA regional office example and can provide insight if you need guidance.

**Comment by dsasser** [comment]
## Mid-sprint update 12-4-24

[Initial artifact](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/medical-centers/initiatives/2024-real-time-banners/testing-qa.md) has been created, but not yet reviewed by others.

We have a sub 80% code coverage in both FE and BE, which is subject to change as we continue to iterate (mostly on the FE now). We should continue to run coverage reports as we develop, and update this artifict once we are at or near completion.

**Comment by jilladams** [comment]
Thanks! Took a quick look and I think we're in pretty good shape for today. Governance did call 80% coverage a launch blocker for DUW this week, so that's something we can be aware of as we go into staging review for this. (I do think that's something we could work on beefing up in the background in the days between getting the app built / into testing, and Staging review itself, even if we aren't at 80% on the day we hand everything to Collab Cycle folx for review.)

cc @Agile6MSkinner for awareness

**Comment by dsasser** [comment]
> [department-of-veterans-affairs/vets-api#19742](https://github.com/department-of-veterans-affairs/vets-api/pull/19742) has been opened to help expand some test coverage on the BE, covering a simple job that was previously at 0%.

Once that gets in we will be at 89% code coverage for the BE!

**Comment by jilladams** [comment]
Daniel has kept the #s up to date for BE test coverage. 
We need to update the artifact for the new FE #s. Eli has screenshots in the big thread with %s.

**Comment by eselkin** [comment]
Updated numbers for FE unit tests

**Comment by jilladams** [comment]
Closing!
