### ISSUE TITLE
Update widget heading to H2 on Claim or Appeal Status

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#19956]
## Description
On the widget on the [Claim or Appeal Status page](https://www.va.gov/claim-or-appeal-status/), the H3 heading on the widget needs to be updated to be an H2
![Image](https://github.com/user-attachments/assets/7a11968d-8459-4d92-9f3e-48fc0a128c0c)

### Scope / Impact analysis
_What, if anything, could break as a result of this change?_
_Engineer should assess this when approaching PR._

### Roles / assignments
_After functional testing, code review, accessibility review, and design review can happen in parallel._
- [ ] **Functional testing:** 
- [ ] **Code review:** 
- [ ] **Design review:** 
- [ ] **Accessibility review:** Laura Flannery
- [ ] **Product acceptance:** 

## Acceptance criteria
_ACs should capture expected behavior, to inform test plans. Consider devices, documentation updates including KBs, change management, and [content model](https://prod.cms.va.gov/admin/structure/cm_document) when applicable._

- [x] The widget heading "Sign in to check your claim, decision review, or appeal status" has been updated to H2
- [x] Accessibility review

**Comment by randimays** [comment]
Pulled in for Sprint 19. Will be solved alongside [this ticket](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19960) in [this PR](https://github.com/department-of-veterans-affairs/vets-website/pull/33548).

**Comment by randimays** [comment]
Verified successfully in production; closing as complete.
