### ISSUE TITLE
Update widget heading to H2 on Disability Rating

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#19957]
## Description
On the widget on the [Disability Ratings page](https://www.va.gov/disability/view-disability-rating/), the H3 heading on the widget needs to be updated to be an H2
![Image](https://github.com/user-attachments/assets/c7e290ab-406e-421e-ae9f-08c672e46afe)

### Scope / Impact analysis
_What, if anything, could break as a result of this change?_
_Engineer should assess this when approaching PR._

### Roles / assignments
_After functional testing, code review, accessibility review, and design review can happen in parallel._
- [ ] **Functional testing:** 
- [ ] **Code review:** 
- [ ] **Design review:** 
- [ ] **Accessibility review:** Laura Flannery
- [ ] **Product acceptance:** 

## Acceptance criteria
_ACs should capture expected behavior, to inform test plans. Consider devices, documentation updates including KBs, change management, and [content model](https://prod.cms.va.gov/admin/structure/cm_document) when applicable._

- [x] The widget heading "Sign in to view your VA disability rating' is now an H2
- [x] Accessibility review

**Comment by randimays** [comment]
Pulled in for Sprint 19. Will be solved alongside [this similar ticket](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19960) in [this PR](https://github.com/department-of-veterans-affairs/vets-website/pull/33548).

**Comment by randimays** [comment]
Verified successfully in production; closing as complete.
