### ISSUE TITLE
Audit Drupal-powered pages to locate MHV links

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-cms#19952]
## Description
Early next year, MHV will move into VA.gov. To support this transition, we need to where the following links are present on Drupal controlled pages (including VAMC pages) so that we can work with the creators to update the links by March 15th. 

Task: Identify where the following links are present 
- https://va.gov/mhv-portal-web/home
- https://eauth.va.gov/mhv-portal-web/home

And these paths for each of those parent domains ([eauth.va.gov/mhv-portal-web/](http://eauth.va.gov/mhv-portal-web/) and [va.gov/mhv-portal-web/](http://va.gov/mhv-portal-web/))
- /refill-prescriptions
- /pharmacy
- /secure-messaging
- /mhv-portal-web/compose-message
- /download-my-data
- /appointments
- /mhv-portal-web/va-blue-button
- /labs-tests
- /prescription-tracking
- /my-complete-medications-list
- /mhv-portal-web/va-medical-images-and-reports
- /mhv-portal-web/va-health-summary

Kaitlin shared [this Sharepoint file](https://dvagov.sharepoint.com/:x:/r/sites/HealthApartment/_layouts/15/doc2.aspx?sourcedoc=%7Ba2129ee7-9bdc-4742-a63d-da66ddbb3ce1%7D&action=edit&clickparams=eyAiWC1BcHBOYW1lIiA6ICJNaWNyb3NvZnQgT3V0bG9vayIsICJYLUFwcFZlcnNpb24iIDogIjE2LjAuMTczMjguMjA2MTIiLCAiT1MiIDogIldpbmRvd3MiIH0%3D) where our findings can be documented

### User story
> _Describe the audience/user, enhancement or fix, and value / outcome desired._

**AS A** Veteran
**I WANT** a seamless connection to MHV
**SO THAT** I can manage my health online

### Scope / Impact analysis
_What, if anything, could break as a result of this change?_
_Engineer should assess this when approaching PR._

### Roles / assignments
_After functional testing, code review, accessibility review, and design review can happen in parallel._
- [ ] **Functional testing:** 
- [ ] **Code review:** 
- [ ] **Design review:** 
- [ ] **Accessibility review:** 
- [ ] **Product acceptance:** 

## Acceptance criteria
_ACs should capture expected behavior, to inform test plans. Consider devices, documentation updates including KBs, change management, and [content model](https://prod.cms.va.gov/admin/structure/cm_document) when applicable._

- [ ] 
- [ ] Impact analysis is filled out and QA test plan is updated accordingly
- [ ] Does this product have an existing regression test plan?
	- [ ] Yes, link: 
	- [ ] No, regression test plan will be created as part of the work / points in this ticket

**Comment by jilladams** [comment]
Asked Kaitlin for domain clarification here: https://dsva.slack.com/archives/C083K35V5A8/p1733248026455869

**Comment by jilladams** [comment]
[eauth.va.gov/mhv-portal-web/](http://eauth.va.gov/mhv-portal-web/) and [va.gov/mhv-portal-web/](http://va.gov/mhv-portal-web/) are the relevant domains. WIth that in mind: 

URL | Usage | Count
--- | --- | ---
va.gov/mhv-portal-web/home | https://prod.cms.va.gov/admin/content/linky?uri=va.gov%2Fmhv-portal-web%2Fhome&title= | 6 |
eauth.va.gov/mhv-portal-web/home | https://prod.cms.va.gov/admin/content/linky?uri=eauth.va.gov%2Fmhv-portal-web&title= | 2 |
va.gov/mhv-portal-web/refill-prescriptions | https://prod.cms.va.gov/admin/content/linky?uri=va.gov%2Fmhv-portal-web%2Frefill-prescriptions&title= | 1 | 
eauth.va.gov/mhv-portal-web//refill-prescriptions | https://prod.cms.va.gov/admin/content/linky?uri=eauth.va.gov%2Fmhv-portal-web%2F%2Frefill-prescriptions&title= | 0
va.gov/mhv-portal-web/pharmacy | https://prod.cms.va.gov/admin/content/linky?uri=va.gov%2Fmhv-portal-web%2Fpharmacy&title= | 0
eauth.va.gov/mhv-portal-web/pharmacy | https://prod.cms.va.gov/admin/content/linky?uri=eauth.va.gov%2Fmhv-portal-web%2Fpharmacy+&title= | 0
va.gov/mhv-portal-web/secure-messaging | https://prod.cms.va.gov/admin/content/linky?uri=va.gov%2Fmhv-portal-web%2Fsecure-messaging&title= | 1 
eauth.va.gov/mhv-portal-web/secure-messaging | https://prod.cms.va.gov/admin/content/linky?uri=eauth.va.gov%2Fmhv-portal-web%2Fsecure-messaging&title= | 0
va.gov/mhv-portal-web/mhv-portal-web/compose-message | https://prod.cms.va.gov/admin/content/linky?uri=va.gov%2Fmhv-portal-web%2Fmhv-portal-web%2Fcompose-message&title= | 0
eauth.va.gov/mhv-portal-web/mhv-portal-web/compose-message | https://prod.cms.va.gov/admin/content/linky?uri=eauth.va.gov%2Fmhv-portal-web%2Fmhv-portal-web%2Fcompose-message&title= | 0
va.gov/mhv-portal-web/download-my-data | https://prod.cms.va.gov/admin/content/linky?uri=va.gov%2Fmhv-portal-web%2Fdownload-my-data&title= | 0
eauth.va.gov/mhv-portal-web/download-my-data | https://prod.cms.va.gov/admin/content/linky?uri=eauth.va.gov%2Fmhv-portal-web%2Fdownload-my-data&title= | 0
va.gov/mhv-portal-web/appointments | https://prod.cms.va.gov/admin/content/linky?uri=va.gov%2Fmhv-portal-web%2Fappointments&title= | 0
eauth.va.gov/mhv-portal-web/appointments | https://prod.cms.va.gov/admin/content/linky?uri=eauth.va.gov%2Fmhv-portal-web%2Fappointments&title= | 0
va.gov/mhv-portal-web/mhv-portal-web/va-blue-button | https://prod.cms.va.gov/admin/content/linky?uri=va.gov%2Fmhv-portal-web%2Fmhv-portal-web%2Fva-blue-button&title= | 0
eauth.va.gov/mhv-portal-web/mhv-portal-web/va-blue-button | https://prod.cms.va.gov/admin/content/linky?uri=eauth.va.gov%2Fmhv-portal-web%2Fmhv-portal-web%2Fva-blue-button&title= | 0
va.gov/mhv-portal-web/labs-tests | https://prod.cms.va.gov/admin/content/linky?uri=va.gov%2Fmhv-portal-web%2Flabs-tests&title= | 0
eauth.va.gov/mhv-portal-web/labs-tests | https://prod.cms.va.gov/admin/content/linky?uri=eauth.va.gov%2Fmhv-portal-web%2Flabs-tests&title= | 0
va.gov/mhv-portal-web/prescription-tracking | https://prod.cms.va.gov/admin/content/linky?uri=va.gov%2Fmhv-portal-web%2Fprescription-tracking&title= | 0
eauth.va.gov/mhv-portal-web/prescription-tracking | https://prod.cms.va.gov/admin/content/linky?uri=eauth.va.gov%2Fmhv-portal-web%2Fprescription-tracking&title= | 0
va.gov/mhv-portal-web/my-complete-medications-list | https://prod.cms.va.gov/admin/content/linky?uri=va.gov%2Fmhv-portal-web%2Fmy-complete-medications-list&title= | 0
eauth.va.gov/mhv-portal-web/my-complete-medications-list | https://prod.cms.va.gov/admin/content/linky?uri=eauth.va.gov%2Fmhv-portal-web%2Fmy-complete-medications-list&title= | 0
va.gov/mhv-portal-web/mhv-portal-web/va-medical-images-and-reports | https://prod.cms.va.gov/admin/content/linky?uri=va.gov%2Fmhv-portal-web%2Fmhv-portal-web%2Fva-medical-images-and-reports&title= | 0
eauth.va.gov/mhv-portal-web/mhv-portal-web/va-medical-images-and-reports | https://prod.cms.va.gov/admin/content/linky?uri=eauth.va.gov%2Fmhv-portal-web%2Fmhv-portal-web%2Fva-medical-images-and-reports&title= | 0
va.gov/mhv-portal-web/mhv-portal-web/va-health-summary | https://prod.cms.va.gov/admin/content/linky?uri=va.gov%2Fmhv-portal-web%2Fmhv-portal-web%2Fva-health-summary&title= | 0
eauth.va.gov/mhv-portal-web/mhv-portal-web/va-health-summary | https://prod.cms.va.gov/admin/content/linky?uri=eauth.va.gov%2Fmhv-portal-web%2Fmhv-portal-web%2Fva-health-summary&title= | 0

**Comment by jilladams** [comment]
Added to Sharepoint.

**Comment by jilladams** [comment]
Kaitlin confirmed that bulk edits will be fine. The audit can be considered done, and I'm closing this. I cut https://github.com/department-of-veterans-affairs/va.gov-cms/issues/20012 to track actually making the content changes when the time comes (mid-March)
