### ISSUE TITLE
Update widget heading to H2 on View Payment History

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#19960]
## Description
On the widget on the [View Payment History](https://www.va.gov/va-payment-history/), the H3 heading on the widget needs to be updated to be an H2
![Image](https://github.com/user-attachments/assets/a205996a-b783-44dd-bb25-561effd967ba)

### Scope / Impact analysis
_What, if anything, could break as a result of this change?_
_Engineer should assess this when approaching PR._

### Roles / assignments
_After functional testing, code review, accessibility review, and design review can happen in parallel._
- [ ] **Functional testing:** 
- [ ] **Code review:** 
- [ ] **Design review:** 
- [ ] **Accessibility review:** 
- [ ] **Product acceptance:** 

## Acceptance criteria
_ACs should capture expected behavior, to inform test plans. Consider devices, documentation updates including KBs, change management, and [content model](https://prod.cms.va.gov/admin/structure/cm_document) when applicable._

- [ ] The widget heading "Sign in to view your VA payment history" is now an H2
- [ ] Accessibility review

**Comment by randimays** [comment]
Pulled in for Sprint 19.
