### ISSUE TITLE
Review and Synthesize: Platform CMS: Lagoon Project

### ISSUE THREAD

**Issue by gracekretschmer-metrostar** [department-of-veterans-affairs/va.gov-cms#19997]
## User Story or Problem Statement
Before closing the Github projects from the previous team, we want to review and synthesize any learnings from those projects. 

## Link to Github Project
https://github.com/orgs/department-of-veterans-affairs/projects/562

## Steps for Implementation
- Review project and tickets. 
- Summarize any findings in a comment of this ticket.
- Add any relevant tickets to the [Drupal CMS Product Team project](https://github.com/orgs/department-of-veterans-affairs/projects/1194). 
- Close project. 

## Acceptance Criteria
- [x] Lagoon project is closed (see instructions [here](https://docs.github.com/en/issues/planning-and-tracking-with-projects/managing-your-project/closing-and-deleting-your-projects)).
- [ ] A summary of any useful information found in the project is documented in a comment of this ticket.

**Comment by 7hunderbird** [comment]
1. Architecture diagram ticket

The first thing my eye was drawn to was this architecture document:
 
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13170#issuecomment-1507529357

Looks really well thought through and described.

They would leverage the fact that even though our Platform team is responsible for the Kubernetes runtime, part of what they are doing is leveraging the Elastic Kubernetes Service (EKS).

**Comment by 7hunderbird** [comment]
2. What is Amazee.io?

![Image](https://github.com/user-attachments/assets/b70ffc54-4e5e-4535-bb15-71fe88b901a9)

Interesting to see who they are and what they do.

I asked perplexity.ai:

> [What relationship does Amazee.io have with Lagoon.sh?](https://www.perplexity.ai/search/what-relationship-does-amazee-RMvvTh6BSH6GU..ekOprqA)

It looks like [amazee.io](https://www.amazee.io/) was a company that could run [lagoon.sh](https://lagoon.sh/) for you.

**Comment by 7hunderbird** [comment]
3. User experience can make or break a platform.

> Proper planning before Lagoon's rollout is critical to ensure long-term success. Foremost of these benefits is ensuring that Lagoon is introduced in such a way that maximizes its chances of success. It doesn't matter how great Lagoon is, [if users do not understand the system, the platform will be seen as a failure](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11837#issue-1480634954). 

I agree with this and that's part of the problem with delivering platforms at scale.  And platforms are specifically designed for scale.

**Comment by 7hunderbird** [comment]
There are too many things of value to extract in this project.  This value all depends on one thing, that the success of a platform comes from universal adoption.

Because there is a competing and dominant platform at the va, we need to focus on that platform's success.
