### ISSUE TITLE
[Discharge Upgrade Wizard] - v2 Unit test coverage

### ISSUE THREAD

**Issue by chriskim2311** [department-of-veterans-affairs/va.gov-cms#20015]
## Description

Based on feedback from Staging Review we need to get the test coverage of the DUW product folder to over 80%.

### User story
**AS A** Veteran
**I WANT** to be able to use the DUW at all times
**SO THAT** I can correctly find out if I am eligible for a discharge upgrade.

### Scope / Impact analysis
_What, if anything, could break as a result of this change?_
_Engineer should assess this when approaching PR._

### Roles / assignments
_After functional testing, code review, accessibility review, and design review can happen in parallel._
- [ ] **Functional testing:** 
- [ ] **Code review:** 
- [ ] **Design review:** 
- [ ] **Accessibility review:** 
- [ ] **Product acceptance:** 

## Acceptance criteria

- [ ] Review tests to determine if coverage can be bumped up
  - [ ] if not, check with Ian to determine if what we have is sufficient.

**Comment by jilladams** [comment]
PR merged, numbers got updated, Ian signed off. Closing. 

Chris, feel free to flag if I'm missing something here.
