### ISSUE TITLE
After DUW launch: Submit 508 office audit request

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#20011]
### User story

**AS A** PO/PM
**I WANT** DUW to be submitted to the 508 office for audit
**SO THAT** we keep things compliant.

## Acceptance criteria

- [ ] File Audit request according to docs: https://depo-platform-documentation.scrollhelp.site/developer-docs/request-support-from-the-va-508-office#audit-request
  - ServiceNow (SNOW) request number: REQ29858122
- [ ] Update Collab Cycle ticket body to reflect ticket is created / share SNOW number: https://github.com/department-of-veterans-affairs/va.gov-team/issues/80777

**Comment by jilladams** [comment]
@laflannery @FranECross FYI I made a ticket for this, since historically we've needed one so we don't forget. :D

**Comment by laflannery** [comment]
@jilladams you had [already done this](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18896) :) I'm going to close this as a dup

**Comment by jilladams** [comment]
Ahhhh, just didn't have the old one in the epic. Thank you! (Added now.)
