### ISSUE TITLE
tugboat.vfs.va.gov Certificate Expiring

### ISSUE THREAD

**Issue by gracekretschmer-metrostar** [department-of-veterans-affairs/va.gov-cms#20034]
## User Story or Problem Statement

The `tugboat.vfs.va.gov` certificate expires soon.  We will need to request a new one and deploy it.

## Description or Additional Context

Determined that the cert is stored and read in entirely in AWS and then traffic is forwarded along to the EC2 instance itself.

- [Confirmed with Lullabot Support](https://dsva.slack.com/archives/C01A35JDH88/p1733778167606699) that there is no additional place we need to deploy the cert because it's in our AWS load balancer.

## Steps for Implementation
- [ ] Put in a support request for a new certificate in slack's `#vfs-platform-support` channel.
- [ ] Recieve new certificate
- [ ] Deploy new certificate to AWS Certificate Manager

## Acceptance Criteria
- [ ] Once certificate is deployed, check in a browser that the expiration date is in Jan 2026

**Comment by 7hunderbird** [comment]
Support let me know we couldn't re-use the previous key.  So I generated a new one.

```
openssl genpkey -algorithm RSA -out tugboat.vfs.va.gov.key -pkeyopt rsa_keygen_bits:2048
```

Then I created a `tugboat.vfs.va.gov.cnf` "config" file with the alternate names we need:

```
[ req ]
default_bits       = 2048
prompt             = no
default_md         = sha256
distinguished_name = dn
req_extensions     = req_ext

[ dn ]
C  = US
ST = D.C.
L  = Washington
O  = U.S. Department of Veterans Affairs
CN = tugboat.vfs.va.gov

[ req_ext ]
subjectAltName = @alt_names

[ alt_names ]
DNS.1 = tugboat.vfs.va.gov
DNS.2 = *.tugboat.vfs.va.gov
DNS.3 = training.cms.va.gov
DNS.4 = *.ci.cms.va.gov
DNS.5 = *.demo.cms.va.gov
```

Saving that config to a file named `tugboat.vfs.va.gov.cnf` I then used that file and the key I generated to make a CSR file. (Certificate Signing Request)

## New CSR

```
-----BEGIN CERTIFICATE REQUEST-----
MIIDQDCCAigCAQAwfDELMAkGA1UEBhMCVVMxDTALBgNVBAgMBEQuQy4xEzARBgNV
BAcMCldhc2hpbmd0b24xLDAqBgNVBAoMI1UuUy4gRGVwYXJ0bWVudCBvZiBWZXRl
cmFucyBBZmZhaXJzMRswGQYDVQQDDBJ0dWdib2F0LnZmcy52YS5nb3YwggEiMA0G
CSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCSvs1Xj300wRKHcfqBPZyiF7SHO0yJ
4CN7PeN8xJFDMwEDaW00Js8JRUi324IWnTUp4uflOuugYo6Xdb2oUUvycUIvDzrD
esnrm1EIz2vYvog8vLzGpgsy6/r6RfaEEQrkmsjNqA3hTgRjdNmBVVwCpu9jk2KP
0N1LCAzblGtKS55RznVCvH/mvFbX9nWqgB3v7nhzdw4spdHfmsw7Xz10H6XoeELv
oQEu+YV/itDE1X65KsjbzrGfQln9oMaGc4ewWmeL5IdiGyhIIjcbGq0bFm1oj4ND
oTIfjhYluM8rYnGvMMEkVe3C4g6ajDt8dO4tiMRw5Tq7xzTdizQ7n7/TAgMBAAGg
fzB9BgkqhkiG9w0BCQ4xcDBuMGwGA1UdEQRlMGOCEnR1Z2JvYXQudmZzLnZhLmdv
doIUKi50dWdib2F0LnZmcy52YS5nb3aCE3RyYWluaW5nLmNtcy52YS5nb3aCDyou
Y2kuY21zLnZhLmdvdoIRKi5kZW1vLmNtcy52YS5nb3YwDQYJKoZIhvcNAQELBQAD
ggEBAGYqAV/62FCBsW9D2TUKVEQLriHzeW8RZ9RMRgxQjmR8sbLMEVtacy2CqAO1
2fMZLi1dUSfWQFh1NtDhzO1gr96FuUlKMLtd1W7/HRpfMhQojISlC8ovMKQPVPrR
5GK33knTbtbR4BRpXxYxYi94E8kjDcyl9WvWdTxfQeBjU20UUSzFyozOwvIwKr4P
Ph+bptec3uEfM5N00c9jqw5yOuszvsWjnBVRsKUwrHcTNG80hOyM1iOzF35Wr06Z
e2iLR47fo+hPb2mfdN+z1YCkNMuAU33SeCQZqhLMbxtcKe5w9oNo6kJ27/jp8Nup
X47ZwrVX4ictZwEsPXpCVehUbwk=
-----END CERTIFICATE REQUEST-----
```

We can then get the certificate back from support and I'll already have the key locally.  I will also publish the key to the Parameter Store.

**Comment by Efe-Oddball** [comment]
@7hunderbird Sent the new certificate to your VA email

**Comment by 7hunderbird** [comment]
Received certificate and deployed to AWS Certificate Manager.

![Image](https://github.com/user-attachments/assets/cc86ecf4-e942-4aeb-b823-ae509761a620)
