### ISSUE TITLE
Test AP stories build and log blockers or approve for launch

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#20059]
## Description
AP team built the template
IIR team reviewed it and compared to content-build / prod, and feels it's ready. 

We need to once-over it, and provide either greenlight or redlight, with notes about blockers. 

## Staging build
To make Story builds visible for testing, the CMS Feature Toggle must be set to True in https://github.com/department-of-veterans-affairs/next-build/blob/main/envs/.env.tugboat#L44, which will then allow the Next template to render in Tugboat. 

If the toggle is not yet set to TRUE, follow [Documentation in #accelerated-publishing Slack canvas](https://dsva.slack.com/docs/T03FECE8V/F07UG7EAWTE?focus_section_id=temp:C:CdV845e9862eaa04f0b8c8e6784b) for how to enable. 

If you have trouble or need to modify the process, please help everyone out and update the Slack canvas with accurate steps for future. 

## Areas to verify

**Data:**
* Conditional logic matches content-build / production 
* SEO Metadata matches production
* Analytics match production

**Interaction / Behavior:**
* Interactions / behavior match production (e.g. accordion expansion by default on page load if they do, data IDs on elements / their usage, link behavior, form / input field behaviors, etc) 
* Lovell Logic: Does each page have the proper System in the alert/URL/Breadcrumbs/Name/Left nav?
* VA Manila logic: Does each page have the proper URL/Breadcrumbs/Name/Left nav?

**Accessibility:**
* Accessibility experience matches production (voiceover/screen reader behavior, appearance at 400% zoom, params on elements, etc) 
* Run axe devTools - Confirm the results are the same as prod to make sure we are not introducing new issues
* Increase browser font size and verify that everything scales and displays appropriately

**Visual presentation:**
* https://github.com/department-of-veterans-affairs/va-iir/blob/main/Documents/design-qa-process-accelerated-publishing.md
* Design system components, prop usage and component versions match production
* Design (font size, spacing, Anything else?) matches production
* Review all breakpoints
* Ensure left/right padding on mobile breakpoints (481px and 320px) is 16px on each side

## Acceptance criteria
- [x] Make sure content type is enabled in Dev. (Requires an eng PR to next-build) -  https://github.com/department-of-veterans-affairs/next-build/blob/main/envs/.env.tugboat#L44
- [x] Review stories next build
- [x] Create a va.gov-cms ticket to track any findings. 
  - [x] Include MUST, SHOULD, or CONSIDER in issue title
  - [x] Include content type in issue title (e.g. MUST: Story: blah)
  - [x] set the parent issue to va.gov-cms #19574

**Comment by jilladams** [comment]
Noting: font-scaling is broken in DST, so QA on this will fail that until it's fixed.

**Comment by laflannery** [comment]
I forgot to mention that DST already put a PR up for the font-scaling and it will be in the next css-library release after code freeze is over. Not sure when that will be but it shouldn't be long!

**Comment by randimays** [comment]
Pulled into Sprint 20.

**Comment by randimays** [comment]
Testing is complete on my end. My findings are in this spreadsheet: https://docs.google.com/spreadsheets/d/12J9PlLr9TJKrPCDCmnarheB9LV2FLqb66zzf9T0J1UU/edit?gid=0#gid=0. 

All findings requiring a ticket have been ticketed and attached to this parent: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19574. We have several defects that must be addressed prior to launch.

### Summary
✅  Validated and meets requirements
❌  Defects found

**Data:**
❌  Conditional logic matches content-build / production
❌  SEO Metadata matches production
❌  Analytics match production

**Interaction / Behavior:**
❌  Interactions / behavior match production (e.g. accordion expansion by default on page load if they do, data IDs on elements / their usage, link behavior, form / input field behaviors, etc)
❌  Lovell Logic: Does each page have the proper System in the alert/URL/Breadcrumbs/Name/Left nav?
❌  VA Manila logic: Does each page have the proper URL/Breadcrumbs/Name/Left nav?

**Accessibility:**
✅  Accessibility experience matches production (voiceover/screen reader behavior, appearance at 400% zoom, params on elements, etc)
✅  Run axe devTools - Confirm the results are the same as prod to make sure we are not introducing new issues
✅  Increase browser font size and verify that everything scales and displays appropriately

**Visual presentation:**
❌  Design system components, prop usage and component versions match production
❌  Design (font size, spacing, Anything else?) matches production
✅  Review all breakpoints
✅  Ensure left/right padding on mobile breakpoints (481px and 320px) is 16px on each side (I think this should actually be 8px as it is in production)


Closing this QA ticket as complete.

**Comment by laflannery** [comment]
I had some notes regarding semantic tags/font sizing that I added into these tickets so know they are captured in one place
