### ISSUE TITLE
Test AP News release Listings build and log blockers or approve for launch

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#20061]
## Description
AP team built the template
IIR team reviewed it and compared to content-build / prod, and feels it's ready. 

We need to once-over it, and provide either greenlight or redlight, with notes about blockers. 

## Staging build
To make News release Listings visible for testing, the CMS Feature Toggle must be set to True in https://github.com/department-of-veterans-affairs/next-build/blob/main/envs/.env.tugboat#L47, which will then allow the Next template to render in Tugboat. 

If the toggle is not yet set to TRUE, follow [Documentation in #accelerated-publishing Slack canvas](https://dsva.slack.com/docs/T03FECE8V/F07UG7EAWTE?focus_section_id=temp:C:CdV845e9862eaa04f0b8c8e6784b) for how to enable. 

If you have trouble or need to modify the process, please help everyone out and update the Slack canvas with accurate steps for future. 

## Areas to verify

**Data:**
* Conditional logic matches content-build / production 
* SEO Metadata matches production
* Analytics match production

**Interaction / Behavior:**
* Interactions / behavior match production (e.g. accordion expansion by default on page load if they do, data IDs on elements / their usage, link behavior, form / input field behaviors, etc) 
* Lovell Logic: Does each page have the proper System in the alert/URL/Breadcrumbs/Name/Left nav?
* VA Manila logic: Does each page have the proper URL/Breadcrumbs/Name/Left nav?

**Accessibility:**
* Accessibility experience matches production (voiceover/screen reader behavior, appearance at 400% zoom, params on elements, etc) 
* Run axe devTools - Confirm the results are the same as prod to make sure we are not introducing new issues
* Increase browser font size and verify that everything scales and displays appropriately

**Visual presentation:**
* https://github.com/department-of-veterans-affairs/va-iir/blob/main/Documents/design-qa-process-accelerated-publishing.md
* Design system components, prop usage and component versions match production
* Design (font size, spacing, Anything else?) matches production
* Review all breakpoints
* Ensure left/right padding on mobile breakpoints (481px and 320px) is 16px on each side

## Acceptance criteria
- [x] Make sure content type is enabled in Dev. (Requires an eng PR to next-build) -  https://github.com/department-of-veterans-affairs/next-build/blob/main/envs/.env.tugboat#L47
- [x] Review stories next build
- [x] Create a va.gov-cms ticket to track any findings. 
  - [x] Include MUST, SHOULD, or CONSIDER in issue title
  - [x] Include content type in issue title (e.g. MUST: Content type: blah)
  - [x] set the parent issue to va.gov-cms #19577

**Comment by randimays** [comment]
Pulled into Sprint 19.

**Comment by randimays** [comment]
Testing is complete on my end. My findings are in this spreadsheet: https://docs.google.com/spreadsheets/d/1kq1PqTPhDWdJ7zuB_nkm5CVg3cc-S1WNHQNLXW_y0_Y/edit?usp=drive_link. 

All findings requiring a ticket have been ticketed and attached to this parent: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19577. We have several defects that must be addressed prior to launch.

### Summary
✅  Validated and meets requirements
❌  Defects found

**Data:**
❌  Conditional logic matches content-build / production
❌  SEO Metadata matches production
✅  Analytics match production

**Interaction / Behavior:**
❌  Interactions / behavior match production (e.g. accordion expansion by default on page load if they do, data IDs on elements / their usage, link behavior, form / input field behaviors, etc)
❌  Lovell Logic: Does each page have the proper System in the alert/URL/Breadcrumbs/Name/Left nav?
❌  VA Manila logic: Does each page have the proper URL/Breadcrumbs/Name/Left nav?

**Accessibility:**
✅  Accessibility experience matches production (voiceover/screen reader behavior, appearance at 400% zoom, params on elements, etc)
✅  Run axe devTools - Confirm the results are the same as prod to make sure we are not introducing new issues
✅  Increase browser font size and verify that everything scales and displays appropriately

**Visual presentation:**
❌  Design system components, prop usage and component versions match production
✅  Design (font size, spacing, Anything else?) matches production
✅  Review all breakpoints
✅  Ensure left/right padding on mobile breakpoints (481px and 320px) is 16px on each side


Closing this QA ticket as complete.
