### ISSUE TITLE
Test AP News Release build and log blockers or approve for launch

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#20060]
## Description
AP team built the template
IIR team reviewed it and compared to content-build / prod, and feels it's ready. 

We need to once-over it, and provide either greenlight or redlight, with notes about blockers. 

## Staging build
To make News release build visible for testing, the CMS Feature Toggle must be set to True in https://github.com/department-of-veterans-affairs/next-build/blob/main/envs/.env.tugboat#L46, which will then allow the Next template to render in Tugboat. 

If the toggle is not yet set to TRUE, follow [Documentation in #accelerated-publishing Slack canvas](https://dsva.slack.com/docs/T03FECE8V/F07UG7EAWTE?focus_section_id=temp:C:CdV845e9862eaa04f0b8c8e6784b) for how to enable. 

If you have trouble or need to modify the process, please help everyone out and update the Slack canvas with accurate steps for future. 

## Areas to verify

**Data:**
* Conditional logic matches content-build / production 
* SEO Metadata matches production
* Analytics match production

**Interaction / Behavior:**
* Interactions / behavior match production (e.g. accordion expansion by default on page load if they do, data IDs on elements / their usage, link behavior, form / input field behaviors, etc) 
* Lovell Logic: Does each page have the proper System in the alert/URL/Breadcrumbs/Name/Left nav?
* VA Manila logic: Does each page have the proper URL/Breadcrumbs/Name/Left nav?

**Accessibility:**
* Accessibility experience matches production (voiceover/screen reader behavior, appearance at 400% zoom, params on elements, etc) 
* Run axe devTools - Confirm the results are the same as prod to make sure we are not introducing new issues
* Increase browser font size and verify that everything scales and displays appropriately

**Visual presentation:**
* https://github.com/department-of-veterans-affairs/va-iir/blob/main/Documents/design-qa-process-accelerated-publishing.md
* Design system components, prop usage and component versions match production
* Design (font size, spacing, Anything else?) matches production
* Review all breakpoints
* Ensure left/right padding on mobile breakpoints (481px and 320px) is 16px on each side

## Acceptance criteria
- [x] Make sure content type is enabled in Dev. (Requires an eng PR to next-build) -  https://github.com/department-of-veterans-affairs/next-build/blob/main/envs/.env.tugboat#L46
- [ ] Review News release next build
- [ ] Create a va.gov-cms ticket to track any findings. 
  - [ ] Include MUST, SHOULD, or CONSIDER in issue title
  - [ ] Include content type in issue title (e.g. MUST: Content type: blah)
  - [ ] set the parent issue to va.gov-cms #19576

**Comment by jilladams** [comment]
Noting: font-scaling is broken in DST, so QA on this will fail that until it's fixed.

**Comment by laflannery** [comment]
I tested this locally because I know how to fix this so I was able to test anyway. Also DST already got a PR for this and it should be fixed soon-ish after code freeze, just depends on when the next release is

**Comment by laflannery** [comment]
I reponded because I think we need to determine if this is ready for launch before we close?

**Comment by jilladams** [comment]
I think it's ok to close this. I'll make a note on the AP epic that we've completed testing and are ready for Product folks to decide Go / No Go.
