### ISSUE TITLE
Manila VA Clinic path reverts to pathauto

### ISSUE THREAD

**Issue by omahane** [department-of-veterans-affairs/va.gov-cms#20086]
## Describe the defect
Manila VA Clinic becomes `/manila-va-clinic/locations/manila-va-clinic` upon update, instead of staying `/manila-va-clinic`.

## To Reproduce
1. Go to Manila VA Clinic
2. Save the page
3. Note that the URL is now `/manila-va-clinic/locations/manila-va-clinic`

## AC / Expected behavior
Manila VA Clinic needs to be at `/manila-va-clinic` on the back-end so that it can be so on the front-end.

## Additional context
This was first reported in [this Slack thread](https://dsva.slack.com/archives/C0FQSS30V/p1733947353783799).

The `va_gov_manila` module, which is handling the manipulation of paths for all Manila content, needs to make an exception for the facility, as it is a unique case where we want it to be a very specific URL which is not accounted for by just setting the first part of the path to `manila-va-clinic`, which satisfies the needs of the other types of content in Manila VA Clinic section.

**Comment by jilladams** [comment]
Verified in prod. Opened Manila clinic to edit, path auto stayed set correctly.
