### ISSUE TITLE
Replace icon for additional info component that was coming from Formation

### ISSUE THREAD

**Issue by randimays** [department-of-veterans-affairs/va.gov-cms#20095]
## Description

A defect was reported where the icon for the additional info component at https://va.gov/manage-va-debt/ was missing. This was caused by the recent [Formation work / import swap](https://github.com/department-of-veterans-affairs/vets-website/pull/32154). There was a component created in [legacy-component-js/additional-info.js](https://github.com/department-of-veterans-affairs/vets-website/blob/f2e094ef33aaf00d74fdd685e0fdc4bdc5d4e530/src/platform/site-wide/legacy-component-js/additional-info.js#L36) that replaced the old Formation implementation, and this component used Font Awesome, which is not supported anymore.

We need to swap out the old icon with a supported `va-icon`. DST will handle the work to completely clean this up a little bit later.

Related Slack thread: https://dsva.slack.com/archives/C52CL1PKQ/p1734052211597919

## Acceptance criteria
- [x] Old Font Awesome icon is replaced with a new supported `va-icon`

**Comment by jilladams** [comment]
This commit is just waiting for prod deploy, but I verified in Staging while I was looking over it:
![Image](https://github.com/user-attachments/assets/637a67b7-e4a9-4723-a1b4-311eb016e57b)

**Comment by randimays** [comment]
Verified it is fixed in production at https://www.va.gov/manage-va-debt/:

<img width="436" alt="Image" src="https://github.com/user-attachments/assets/b4d9b7d5-9a7f-424f-b5f0-48028d931966" />

<img width="773" alt="Image" src="https://github.com/user-attachments/assets/dd846895-b802-48c9-ac2d-a6a86907fc1f" />

Closing as complete.
