### ISSUE TITLE
Rename "master" branch to "main"

### ISSUE THREAD

**Issue by indytechcook** [department-of-veterans-affairs/va.gov-cms#2010]
## Description

Rename "master" branch to "main". 

## Acceptance Criteria

- [ ] Default branch for the CMS has been changed or renamed to "main"

**Comment by ElijahLynn** [comment]
I changed the story to "main". GitLab is changing the default to "main" as well > https://gitlab.com/gitlab-org/gitlab/-/issues/221164.

**Comment by ElijahLynn** [comment]
Also, GitHub already changed their default to "main". Here is a screenshot of a new repository saying that a new "main" branch will be created when initializing the repo with a README.md file. 

![image](https://user-images.githubusercontent.com/1504756/97652388-7720a780-1a1b-11eb-9faf-87eb71ff38a2.png)

**Comment by ElijahLynn** [comment]
* Tugboat Base Builds
* Documentation (all the places)
* Jenkins Jobs and Jenkinsfiles
* GitHub Actions
