### ISSUE TITLE
Update facility locator error messages in Figma with CAIA feedback

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#20134]
## Description

- In #15935  we defined new FL error messages. 
- In [#98598](https://github.com/department-of-veterans-affairs/va.gov-team/issues/98598#issuecomment-2551348510) we got CAIA feedback on error states, in [this Google doc](https://docs.google.com/document/d/1zRbvGpmShiFnkJfP9Eo8gUnTE0-08C17MM5CPQEaWx8/edit).  

We need to now update Figma with the final CAIA-approved copy, in advance of the Q1 facilities work on all the FL things.

## Design

[Error states in Figma](https://www.figma.com/design/GvNVeG9GAXZaBpny7vNxZP/Facility-Locator?node-id=172-16230&t=eJ7uyZGsaXkgXI7N-1)

## Acceptance criteria
- [x] In Figma: update FL error messages with [CAIA's feedback](https://docs.google.com/document/d/1zRbvGpmShiFnkJfP9Eo8gUnTE0-08C17MM5CPQEaWx8/edit)
- [ ] ~Review with UX Lead, Accessibility, and PM (if needed)~
     - Not needed. Changes were minor.

**Comment by jilladams** [comment]
@thejordanwood I guessed this as a 2, but feel free to update.

**Comment by thejordanwood** [comment]
Updates are in the Figma file. The suggested changes were very minor and I don't believe this needs further review. I'm going to close the ticket!
