### ISSUE TITLE
Facility locator detail pages: columns don't fit side by side at desktop breakpoint

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#20133]
## Description
Potentially a regression due to DST changes to use USWDS stylesheets more broadly, not sure. 

To repro: 
* Visit https://www.va.gov/find-locations/facility/vba_345m
* See the right column dropped below the left column

![Image](https://github.com/user-attachments/assets/fac6a4ad-a6df-4757-a264-552ca460f0c4)

### Engineering notes / background
It looks like the definitions for `.usa-width-one-third` and `.usa-width-two-thirds` rules don't play nicely to fit side by side at this breakpoint anymore. Might be due to some padding or something. Switching to `.medium-7` on the left allows them to sit side by side, as does adjusting the width of the one-third rule. 

## Acceptance criteria
- [ ] Left and right columns sit side by side at desktop breakpoint on Facility locator detail pages

**Comment by jilladams** [comment]
@randimays if you are blocked on the AP ticket, this one might be a quickie to look into, potentially.

**Comment by randimays** [comment]
Pulled in for Sprint 19.

**Comment by randimays** [comment]
@eselkin Reported this in #20154 on Friday and has [a PR up](https://github.com/department-of-veterans-affairs/vets-website/pull/33740) for the fix. Closing as a dupe.

**Comment by eselkin** [comment]
@thejordanwood really noted it. Something changed but it's still odd that we're depending on some other app's styles for "columns"
