### ISSUE TITLE
MUST: News Release Listings: Manila pages do not load the page sidebar

### ISSUE THREAD

**Issue by randimays** [department-of-veterans-affairs/va.gov-cms#20144]
### What is the problem?
News Release Listings for Manila do not have the page sidebar (left side). Screenshots from desktop and mobile below.

| Prod | next-build |
| --- | --- |
| https://www.va.gov/manila-va-clinic/news-releases/ | https://web-kqjsor0i3mjdwsy9gojxhhyvdzh0wubb.tugboat.vfs.va.gov/manila-va-clinic/news-releases/ |
| <img width="1037" alt="Image" src="https://github.com/user-attachments/assets/80044df7-89ea-4172-ab75-da7cb808b315" /> | <img width="817" alt="Image" src="https://github.com/user-attachments/assets/aa5f1503-d66b-433c-b3f2-f0a6f9961cac" /> |
| <img width="400" alt="Image" src="https://github.com/user-attachments/assets/eedc2e3d-e85b-4c7f-8592-da72edbc53ac" /> | <img width="401" alt="Image" src="https://github.com/user-attachments/assets/39e57b38-1a2e-4385-b338-9a334670d977" /> | 

### How urgent is the issue?
**Critical** / Major / Minor

```[tasklist]
###
- [ ] The problem as described is fixed
- [ ] The repro steps result in 'expected result'
- [ ] An automated test is written to catch the problem, if appropriate
```

**Comment by timcosgrove** [comment]
This was known and is a consequence of the current Manila architecture, which does away with the VAMC System page. This removes the only data contact that the menus have with a given system.

I'd like to work together w/ Sitewide to resolve this issue in the best way possible, which might involve modifications to Next Build, or might involve making the Manila architecture in CMS more in line with the rest of the CMS Facilities.

**Comment by randimays** [comment]
cc @jilladams: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/20144#issuecomment-2557879851
