### ISSUE TITLE
VA-EXPORT notices

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#2017]
**Describe the defect**
I am seeing a decent number of notices  related to paths on VA-EXPORT
![image](https://user-images.githubusercontent.com/5752113/84399427-d7c75900-abce-11ea-8d46-9c80fcaf1535.png)

I am not fully sure of the cause. Not sure if it is just noise or something serious.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information if relevant, or delete):**

**Additional context**

## Labels
- [/] Issue type (red) (defaults to "Defect")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [/] CMS objective (orange) (not needed for bug tickets)
- [ ] CMS-supported product (black)

**Comment by oksana-c** [comment]
checked logs after today's deployment - this seems to be fixed. closing.
