### ISSUE TITLE
Search discovery

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#2034]

**Comment by jefflbrauer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VAgov-CMS-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/2034?planning-poker) with ZenHub @ElijahLynn @indytechcook @ndouglas @olivereri @timcosgrove

**Comment by jefflbrauer** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VAgov-CMS-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/2034?planning-poker) with ZenHub @cweagans

**Comment by swirtSJW** [comment]
Referencing this to the other epic https://github.com/department-of-veterans-affairs/va.gov-cms/issues/3933

**Comment by EWashb** [comment]
we have so many search epics and issues. This is the oldest so I'm going to close
