### ISSUE TITLE
"Connect with us" block discovery

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#2040]

**Comment by msbtterswrth** [comment]
I've reviewed each bloc instance and compiled the data into a spread sheet here - https://docs.google.com/spreadsheets/d/1yk5IJ-vFbAViTLRrj8NxwL69XGHujYqrSbp4-RCV-x4/edit#gid=0

There are 4 versions which all have a unique newsletter and list of social links. The VA Records page does not have a block.

**Comment by kevwalsh** [comment]
Thanks Lynn, and for updating the epic with findings. Closing this. I've also added the "unplanned work" label cause it wasn't in the sprint plan.
