### ISSUE TITLE
"Connect with us" block front end refactoring

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#2042]
### AC

- [ ] Refactor FE template for Benefits Hub Landing Pages and query to pull the social media media fields out of the Office entity ref
- [ ] Refactor FE template for CLP and query to pull the social media media fields out of the Office entity ref
- [ ] Social media links from unpublished office nodes should still be displayed, despite them being unpublished.

**Comment by kelsonic** [comment]
Duplicate of https://github.com/department-of-veterans-affairs/va.gov-team/issues/33176
