### ISSUE TITLE
Manual Content Deploy does not work

### ISSUE THREAD

**Issue by indytechcook** [department-of-veterans-affairs/va.gov-cms#2046]
When making a request to Jenkins to deploy content  403 error occurs.

There were 2 issues discovered

1. When making the curl request the connection was timing out.
2. When the connection to Jenkins did work then we get `403`

Fixes:

> 1. When making the curl request the connection was timing out.

The connection timeout was caused by a security group change in AWS.  The connection from the vpc the cms prod server was in and the Jenkins server VPC was blocking the request.  @jbritt1 was able to fix this issue.

> 2. When the connection to Jenkins did work then we get `403`

This was caused by a CRSF change in Jenkins.  Our requests get:

```
[root@ip-10-247-32-204 cms]# curl -L -X POST -u va-cms-bot:<removed> -vvv http://jenkins.vfs.va.gov/job/deploys/job/vets-gov-autodeploy-vets-website/buildWithParameters?release_wait=5
*   Trying 172.31.1.100...
* TCP_NODELAY set
* Connected to jenkins.vfs.va.gov (172.31.1.100) port 80 (#0)
* Server auth using Basic with user 'va-cms-bot'
> POST /job/deploys/job/vets-gov-autodeploy-vets-website/buildWithParameters?release_wait=5 HTTP/1.1
> Host: jenkins.vfs.va.gov
> Authorization: Basic <removed>
> User-Agent: curl/7.61.1
> Accept: */*
>
< HTTP/1.1 403 Forbidden
< X-Content-Type-Options: nosniff
< Cache-Control: must-revalidate,no-cache,no-store
< Content-Type: text/html;charset=iso-8859-1
< Content-Length: 610
< Server: Jetty(9.4.27.v20200227)
<
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
<title>Error 403 No valid crumb was included in the request</title>
</head>
<body><h2>HTTP ERROR 403 No valid crumb was included in the request</h2>
<table>
<tr><th>URI:</th><td>/job/deploys/job/vets-gov-autodeploy-vets-website/buildWithParameters</td></tr>
<tr><th>STATUS:</th><td>403</td></tr>
<tr><th>MESSAGE:</th><td>No valid crumb was included in the request</td></tr>
<tr><th>SERVLET:</th><td>Stapler</td></tr>
</table>
<hr><a href="http://eclipse.org/jetty">Powered by Jetty:// 9.4.27.v20200227</a><hr/>

</body>
</html>
* Connection #0 to host jenkins.vfs.va.gov left intact
```

I was able to make a request using the "Jenkins Crumb" token by making one request to `/crumbIssuer/api/xml` or `/crumbIssuer/api/json` to get the token then adding it to the second API request.  It also requires using a cookie jar.

```
[root@ip-10-247-32-204 cms]# export JENKINS_URL=http://jenkins.vfs.va.gov
[root@ip-10-247-32-204 cms]# export JENKINS_USER=va-cms-bot
[root@ip-10-247-32-204 cms]# export JENKINS_TOKEN=<removed>
[root@ip-10-247-32-204 cms]# export COOKIE_JAR=/tmp/cookies
[root@ip-10-247-32-204 cms]# JENKINS_CRUMB=$(curl --silent --cookie-jar $COOKIE_JAR $JENKINS_URL'/crumbIssuer/api/xml?xpath=concat(//crumbRequestField,":",//crumb)' -u $JENKINS_USER:$JENKINS_TOKEN)
[root@ip-10-247-32-204 cms]# echo $JENKINS_CRUMB
Jenkins-Crumb:<removed>
[root@ip-10-247-32-204 cms]# curl --cookie $COOKIE_JAR $JENKINS_URL/job/deploys/job/vets-gov-autodeploy-vets-website/buildWithParameters?release_wait=5 --data-binary @jenkins/config.xml -X POST -H $JENKINS_CRUMB -u $JENKINS_USER:$JENKINS_TOKEN -v
Warning: Couldn't read data from file "jenkins/config.xml", this makes an
Warning: empty POST.
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying 172.31.1.100...
* TCP_NODELAY set
* Connected to jenkins.vfs.va.gov (172.31.1.100) port 80 (#0)
* Server auth using Basic with user 'va-cms-bot'
> POST /job/deploys/job/vets-gov-autodeploy-vets-website/buildWithParameters?release_wait=5 HTTP/1.1
> Host: jenkins.vfs.va.gov
> Authorization: Basic <removed>
> User-Agent: curl/7.61.1
> Accept: */*
> Cookie: JSESSIONID.04a71f63=node01jig0t5nenug89n9v9udhuner2124.node0
> Jenkins-Crumb:<removed>
> Content-Length: 0
> Content-Type: application/x-www-form-urlencoded
>
< HTTP/1.1 201 Created
< Date: Mon, 15 Jun 2020 16:21:47 GMT
< X-Content-Type-Options: nosniff
< Location: http://jenkins.vfs.va.gov/queue/item/157512/
< Content-Length: 0
< Server: Jetty(9.4.27.v20200227)
<
* Connection #0 to host jenkins.vfs.va.gov left intact
```

## Fix Steps
- [x] PR to devops repo for BRD: https://github.com/department-of-veterans-affairs/devops/pull/7116
- [x] PR to devops repo to fix security group issue: https://github.com/department-of-veterans-affairs/devops/pull/7114, https://github.com/department-of-veterans-affairs/devops/pull/7122
- [x] update cms-ci branch for DevShop in devops repo
- [x] PR to CMS repo to use new config: https://github.com/department-of-veterans-affairs/va.gov-cms/pull/2048
- [x] Manually Update `/var/aegir/.drush/va.drush.inc`

**Comment by indytechcook** [comment]
I generated a jenkins token which can be used instead of getting a crumb. I'm putting the token in credstash under `cms.vagov.va_cms_bot.jenkins.token`

**Comment by indytechcook** [comment]
PR number 1: https://github.com/department-of-veterans-affairs/devops/pull/7116

**Comment by indytechcook** [comment]
Created https://github.com/department-of-veterans-affairs/va.gov-cms/issues/2055 as a follow up to make sure this doesn't occur again.

**Comment by ElijahLynn** [comment]
Thanks for taking this on @indytechcook! We had discussed doing this in https://github.com/department-of-veterans-affairs/va.gov-cms/issues/1647 and https://dsva.slack.com/archives/CBU0KDSB1/p1588196351228700.
