### ISSUE TITLE
Recruitment strategy and governance

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#2075]
## Background
Consent forms are sent by A6 via Docusign. A6 has an archive of all consent forms if required for reference.

All research documents are being saved locally (not in the cloud).

Research Data Management process is outlined here - https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/cms/research/research-procedures 

## Acceptance criteria

- [ ] [Research Data Management](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/cms/research/research-procedures) is updated with additional data
- [ ] Research Data Management document is informative enough to use for onboarding new team members

**Comment by EWashb** [comment]
This is no longer needed as the direction of our work has changed
