### ISSUE TITLE
File links on www.va.gov incorrect and inaccessible to public internet

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#2077]
**Describe the defect**
A link to a pdf comes up with this path http://internal-dsva-vagov-prod-cms-2000800896.us-gov-west-1.elb.amazonaws.com/sites/default/files/2020-06/Moving%20Forward%20Notice-003.pdf 

**To Reproduce**
1. Go to https://www.va.gov/pittsburgh-health-care/events/
2. Click on 
![image](https://user-images.githubusercontent.com/5752113/85063961-e5ee1a00-b178-11ea-91ad-3ce373997acf.png)

**Expected behavior**
The link should be:
- accessbile
- on the va.gov domain.

**Screenshots**

**Desktop (please complete the following information if relevant, or delete):**

**Additional context**

## Labels
- [/] Issue type (red) (defaults to "Defect")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [/] CMS objective (orange) (not needed for bug tickets)
- [ ] CMS-supported product (black)

**Comment by ElijahLynn** [comment]
I think this should be moved to the va.gov-team repo and @brandonrapp and/or @cvalarida can help triage. Those links are supposed to be re-written by the build script.

**Comment by ElijahLynn** [comment]
The code that rewrites these is here https://github.com/department-of-veterans-affairs/vets-website/blob/60b27badeee21229da80ce491afdd781749a12ec/src/site/stages/build/drupal/assets.js and https://github.com/department-of-veterans-affairs/vets-website/blob/0f04910e219ab7bc8ebf3d55eea2c31638ff1d48/src/site/constants/drupals.js#L48-L55

**Comment by swirtSJW** [comment]
The ticket has been created here https://github.com/department-of-veterans-affairs/vets-website/issues/13211   so I think we can consider this one done.
