### ISSUE TITLE
Linkit can't see all content types in the link widget

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#2079]
**Describe the defect**
Linkit doesn't know about all the content types
**To Reproduce**
1. In a WYSIWYG field, add a link
2. Try to add a link to Pittsburgh Operating Status
3. You won't see it in the drop down.

**Expected behavior**

You should see it in the dropdown. 

You should also be able to select any of the content types circled in this screenshot

![Edit_Content_matcher___VA_gov_CMS.jpg](https://images.zenhubusercontent.com/5d6e57ad330f64311395f08b/7c1d1d97-d2df-406f-b173-e288e29b4f8a)

**Screenshots**

Current config:

![Edit_Content_matcher___VA_gov_CMS.jpg](https://images.zenhubusercontent.com/5d6e57ad330f64311395f08b/f0f98d59-d9fd-4fd9-812f-707fa1dab426)

**Desktop (please complete the following information if relevant, or delete):**

**Additional context**

## Labels
- [/] Issue type (red) (defaults to "Defect")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [/] CMS objective (orange) (not needed for bug tickets)
- [ ] CMS-supported product (black)

**Comment by kaise-lafrai** [comment]
PR: https://github.com/department-of-veterans-affairs/va.gov-cms/pull/2272

**Comment by kaise-lafrai** [comment]
PR: https://github.com/department-of-veterans-affairs/va.gov-cms/pull/2272
