### ISSUE TITLE
Train Public Websites in user and section administration

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#2090]
## Problem statement

The Public Websites team manages content with ownership dispersed throughout the Sections governance system. For example: 11 benefits hubs throughout 4 top-level sections, VA forms, Homepage and footer, etc. 

As of June 15 2020, CMS team has supported Public Websites with user management, by adding users and editing their sections, and making changes when requests come in, including team members, DEPO POs and staff, and content stakeholders and editors from various administrations, including VBA. 

Ideally, a Public Websites team member with understanding of the content governance of all products in the Public Websites domain would be empowered to 

## ACs 
- [ ] Sections-based governance is documented
- [ ] Several members of Public Websites team are trained in 

## Labels
- [/] Issue type (red) - should default to support request
- [/] CMS practice area (blue) - should default to
- [/] CMS Objective (orange) - should default to O4:
- [ ] CMS-supported product (black)

**Comment by FranECross** [comment]
Closing as obsolete.
