### ISSUE TITLE
Headings in proofing experience reflect semantic logic from VA.gov

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#2103]
## User Story or Problem Statement

VA.gov paragraphs liquid templates contain a lot of logic to drive semantic headings. Drupal proofing does not reflect that logic. 

As a user looking at nested paragraphs, the headings (h2/h3/h4) are conditional based on their nesting. 

## Acceptance Criteria
* Testable_Outcome_X
* Testable_Outcome_Y
* Testable_Outcome_Z

## Implementation steps
<optional>

**Comment by swirtSJW** [comment]
This would actually be an epic on its own with each content type being its own issue.
