### ISSUE TITLE
VA Forms "Owner" field defaults to wrong value

### ISSUE THREAD

**Issue by beeyayjay** [department-of-veterans-affairs/va.gov-cms#2107]
VA Forms should all be owned by 'Forms' but the default value is 'Public Websites'.

**To Reproduce**
1. Go to https://prod.cms.va.gov/node/add/va_form
2. Confirm that 'Owner' field (in Governance section in right rail) is set to 'Public Websites Team'.

**Expected behavior**
The default value for Owner should be 'Forms'

**Comment by timcosgrove** [comment]
This was fixed by https://github.com/department-of-veterans-affairs/va.gov-cms/pull/2116 and can probably be closed.

(Don't mind me leaving this comment; I'm taking a look at va.gov-cms and looking at open issues as a way of getting myself oriented to how work is done on the repo.)
