### ISSUE TITLE
Add Drush 10 and add `drush10` alias

### ISSUE THREAD

**Issue by indytechcook** [department-of-veterans-affairs/va.gov-cms#2117]
## Problem

Drush 10 will not work on Devshop, which requires Drush 8 (Drupal 7). 

Drush 10 is needed for CMS export to work properly because tome:sync is Drush 9+ only. 

Devshop can't use an alias for Drush 8.

## AC

On all environments (local, CI, DEV/STAGING/PROD): 
- [ ] `drush10` alias should be available
- [ ] Existing Yaml tests are functioning
- [ ] Daily and Periodic jobs still work (using the `drush` (Drush 8) command)
- [ ] `drush` (Drush 8) works as expected everywhere

## Implementation

* Change commands to make `drush10` explicit
* Could use a post_install_cmd to curl drush10, put it in /bin and make an alias.

**Comment by indytechcook** [comment]
Drupal migration guide: https://weitzman.github.io/blog/port-to-drush9

**Comment by ElijahLynn** [comment]
This was a workaround option for DevShop, not needing anymore.
