### ISSUE TITLE
Generate schema for transformer team

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#2127]
## User Story or Problem Statement

As a writer of CMS export transformers, i need schema information. 

See threads in #cms-transformer channel, particularly [this one](https://dsva.slack.com/archives/C01512KN35G/p1592981545115700).

## Acceptance Criteria
- [ ] Transformer team has a way of getting dynamic schema information about all CMS entities

## Approach options
1. GraphQL. 

- Whenever Content export is tarred, it includes the GraphQL output about schema in a file in the export (eg put it in sites/default/files/export-content/)  
- This would allow other consumers (eg Lighthouse) to access.

2. JSON API

- not currently "supported" by our team, despite being native

## Related

https://github.com/department-of-veterans-affairs/va.gov-cms/issues/1851

**Comment by swirtSJW** [comment]
I have got a working model using the schema provided by OpenAPI.  I deliverd the output to the FE transformer team for validation and am not working on making it so they can get it.   Then can work on getting the file saved.
