### ISSUE TITLE
Reproduce & diagnose table locks

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#2131]
**Describe the defect**

Database locks are causing errors for CMS users, during migration most likely.  

Editors are running into these locks during save and sometimes not full white screen.
* [Slack thread](https://dsva.slack.com/archives/CDHBKAL9W/p1592841895292900) with a user reporting a number of issues

![image](https://user-images.githubusercontent.com/643678/85884178-35070100-b7b0-11ea-8041-a9401782df86.png)

Working assumption:
* During a migration, table locks occur. 
![image](https://user-images.githubusercontent.com/5752113/85884296-65e73600-b7b0-11ea-8f46-08fd81db4f85.png)

## ACs

- [x] We have a set of reproducible steps

**Comment by ElijahLynn** [comment]
We think this is mostly happening when this job runs every hour http://jenkins.vfs.va.gov/job/cms/job/cms-periodic/

**Comment by ElijahLynn** [comment]
I think pairing might be really useful to reproduce this.

**Comment by jefflbrauer** [comment]
O1-KR1

**Comment by indytechcook** [comment]
Looking over the AWS logs for all of the occurrences over the past week here are all of the items which are running at the same time when the errors occur:

- periodic job (error occurs before cron every time)
- Files Backup
- Database backup
- page load/node save (the actual error)

I'm trying to reproduce the error by running these all at the same time on cms-test

**Comment by indytechcook** [comment]
I was able to reproduce on staging running only the periodic job and trying to load the https://staging.cms.va.gov/section/veterans-affairs page.

The follow was running when I sent to the page.
```
Running test va/background/periodic/migrate/facility_status: Run migrate facility status to run every 15 min as called by Jenkins.
----------------------------------------------------------------------------------------------------------------------------------

 $ drush $DRUSH_ALIAS migrate-reset-status va_node_health_care_local_facility_status && drush $DRUSH_ALIAS migrate-import va_node_health_care_local_facility_status Output:/path/to/file
 ┃ Migration va_node_health_care_local_facility_status reset to Idle    [status]
```

The error message:
```
Drupal\Core\Database\DatabaseExceptionWrapper: SQLSTATE[HY000]: General error: 1205 Lock wait timeout exceeded; try restarting transaction: INSERT INTO {cache_config} (cid, expire, created, tags, checksum, data, serialized) VALUES (:db_insert_placeholder_0, :db_insert_placeholder_1, :db_insert_placeholder_2, :db_insert_placeholder_3, :db_insert_placeholder_4, :db_insert_placeholder_5, :db_insert_placeholder_6) ON DUPLICATE KEY UPDATE cid = VALUES(cid), expire = VALUES(expire), created = VALUES(created), tags = VALUES(tags), checksum = VALUES(checksum), data = VALUES(data), serialized = VALUES(serialized); Array ( [:db_insert_placeholder_0] => last_write_timestamp_cache_config [:db_insert_placeholder_1] => -1 [:db_insert_placeholder_2] => 1594305866.384 [:db_insert_placeholder_3] => [:db_insert_placeholder_4] => 0 [:db_insert_placeholder_5] => d:1594305866.385; [:db_insert_placeholder_6] => 1 ) in Drupal\Core\Cache\ChainedFastBackend->markAsOutdated() (line 306 of /var/www/cms/docroot/core/lib/Drupal/Core/Cache/ChainedFastBackend.php).
```
