### ISSUE TITLE
Wizard builder 🧙‍♂️ 

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#2137]
### User Story or Problem Statement

As a VFS product team, i can build and manage a wizard in Drupal

Use case: 
* Covid Screener
* Health care and other eligibility wizards

From https://design.va.gov/patterns/wizards: 

> Sometimes, the eligibility for a VA benefit or resource is so complex that it has multiple access pathways, depending on a user's specific needs or circumstances. Users may experience consequences (e.g. not getting the benefit or limiting benefit options), if they misunderstand eligibility content or choose the wrong pathway. VA.gov uses a wizard pattern to guide users down an optimal pathway for their circumstances.
>
> - The VA.gov wizard pattern consists of a series of simple questions, written in plain language, used to glean a user’s specific eligibility status, background, or specific needs/goals.
> - Wizards serve up one question at a time.
> - Wizards use conditional logic, whereby the answer to the first question determines the next question to be asked, or answer options that should be made available.
> - Wizards do not submit or store data.

### Affected users and stakeholders

* VFS product teams
* for Covid Screener use case: Possibly VISN or VAMC facility content managers. 
   * @mchelen-gov interested in the [output format](https://dsva.slack.com/archives/C013WDER4FP/p1593443862179100?thread_ts=1593441029.167800&cid=C013WDER4FP) among other aspects

### Hypothesis

_A hypothesis may depend on a spike ticket to be completed._

We believe that _this_solution_ will achieve _this_outcome_. We'll know that to be true when _this measurable outcome occurs._

### Assumptions
* Tk
* Tk

(How will these assumptions be validated?)

## Acceptance Criteria
* Testable_Outcome_X
* Testable_Outcome_Y
* Testable_Outcome_Z

**Comment by mchelen-gov** [comment]
- In "Wizard" pattern https://design.va.gov/patterns/wizards the [How to apply for a discharge upgrade](https://www.va.gov/discharge-upgrade-instructions) ([code](https://github.com/department-of-veterans-affairs/vets-website/tree/master/src/applications/discharge-wizard)) is the best of these to look at. VSP has not published this as a component in Formation, we are coordinating with them to determine approach https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/192
- [VA Forms System](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/forms) (VAFS) - this is the more heavyweight system that involves writing data
- VAFS uses a standard JSONSchema called `react-jsonschema-form` which could be used as a standard data format for drupal to output, either for VAFS or for "Wizard" usage <https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/forms/about-the-schema-and-uischema-objects#understanding-the-uischema-object>
- [Form.io](https://formio.github.io/formio.js/) is a potential 3rd party JS/React form library that is JSON driven. Drupal could output a file in this format for consumption by the frontend
- Here is our current [screener config](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/coronavirus-screener/config/questions.jsx) which is basically a JSON file

**Comment by mchelen-gov** [comment]
Here's the issue for the frontend component: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/192#issuecomment-652027200

**Comment by davidmpickett** [comment]
Removing Facilities label and adding CMS Team as this would be a new core function and there's not a specific Facilities need driving this.

**Comment by EWashb** [comment]
There is no CMS Team need for this functionality. If we decide on a wizard later, that will be on a by-product basis
