### ISSUE TITLE
Document the process for deleting orphan facilities

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#2147]
## Description

related [slack thread](https://dsva.slack.com/archives/C0FQSS30V/p1593044221175800)

## Acceptance Criteria
* the process for deleting orphan facilities in CMS is documented https://github.com/department-of-veterans-affairs/va.gov-cms/blob/master/READMES/migrations-facility.md

**Comment by xiongjaneg** [comment]
covered in [#4865](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/4856)
