### ISSUE TITLE
Respondent Log Master supplement in Drupal

### ISSUE THREAD

**Issue by nickbloom** [department-of-veterans-affairs/va.gov-cms#2149]
Discuss possibilities for integrating data pulled from Drupal (e.g. membership length and date last accessed) into master Respondent Log spreadsheet

**Acceptance Criteria**

- [ ] a table exists in Drupal that has the following information: User ID | Member since | date of last login
- [ ] table is accessible to Administrator role only
- [ ] table is located on a path that is shared with research team only

**Comment by oksana-c** [comment]
@nickbloom, we have an option of exporting this info into a CSV file if that helps

**Comment by EWashb** [comment]
Not currently within scope. We will be looking at LDAP integration
