### ISSUE TITLE
UX Strategy - Content Findability

### ISSUE THREAD

**Issue by nickbloom** [department-of-veterans-affairs/va.gov-cms#2154]
Application of UX Strategy development to the topic of content findability. Sub-issues include:

- conduct internal HCD (discovery, synthesis) with VFS-CMS team to define and scope "findability"
     - e.g. what types of information team members want/need for development, how they want that information delivered, when they want it delivered, etc.
- disseminate findings to team through artifacts and share-outs
- define CMS user "groups/clusters" of interest for UX discovery
- conduct discovery/synthesis with CMS users to define and scope "findability"
- complete "grand" synthesis of team and CMS user perspectives into artifacts and recommendations
- develop prototype
- conduct user feedback on prototype and iterate
- finalize prototype and begin implementation

**Comment by oksana-c** [comment]
closing in favor of #3874
