### ISSUE TITLE
Configure EWA notifications

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#2166]
## Description

EWA notifications need to be configured and validated once admin UI is built.

## Acceptance Criteria

- [ ] EWA notifications are configured on DevShop environment
- [ ] Delivery of EWA notifications is validated on DevShop environment
- [ ] EWA notification configuration is exported and added to version control

**Comment by swirtSJW** [comment]
Closing this as EWA is not the current direction for notifications.
