### ISSUE TITLE
The CMS Notifications Center

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#2171]
## Problem statement

Users want to stay informed about events that may affect their work within the Drupal CMS while they are operating within the system. 

The CMS Notifications Center is designed to be a home base for all notifications that are relevant to the logged-in user within the CMS application where real-time information matters most.

The CMS Notifications Center intends to become a default notification channel that the user cannot opt-out of. The concept is similar to GitHub notifications in GitHub Web app.

## Hypothesis or Bet

* Access to real-time notifications within the CMS will improve the workflow for our authors. They won’t have to check their email through the work day in order to keep on track with editorial and other CMS events.
* Keeping all relevant notifications within the CMS will allow for a faster feedback loop between the system events, editorial workflow events and the CMS users, which will reduce friction caused by disjointed sources of information like Slack, email, etc.

## We will know we're done when... ("Definition of Done")

* CMS Notifications Center experience is designed and validated with CMS users.
* CMS Users can see relevant real-time notifications about various editorial or system events within the CMS UI.

## Known Blockers/Dependencies

* [CMS Notifications Framework](./cms-notification-framework) must be in place to kick off this product.

## User Stories

* As a CMS user, I want to be able to get real-time notifications when events concerning my work happen, so that I don’t have to find the right person to ask or search my emails.
* As a CMS user, I want to be able to get real-time notifications when events concerning CMS tools that support my work happen, so that I can stay informed of new features, system status and other events that can affect my work day.

## va.gov-team product directory

https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/cms/product-outlines/cms-notifications-center

**Comment by EWashb** [comment]
This is not going to be pursued in current state per PO. Closing to clean up backlog
