### ISSUE TITLE
Communication of incremental EWA releases

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#2194]
## User Stories

* As a user, who manages the team, I need to understand the changes and new possibilities of Editorial Workflow & Assignments tools, so that I can establish a workflow specific to my team.
* As a user, who is using the current editorial workflow within the CMS, I need to be reoriented to the new concepts introduced by EWA.
* As a CMS user, I need plenty of advance warning and details about the new EWA workflow so I’m not surprised by the new changes .
* As a CMS trainer, I need to understand concepts introduced by Editorial Workflow & Assignments, so that I feel confident when I train CMS users and responding to support requests.

## Acceptance Criteria

- [ ] A plan and language is developed to communicate incremental releases of EWA features to users.
   - [ ] communication language generates excitement and awareness for the EWA product
   - [ ] release notes are ready for each distinct component of EWA and can be efficiently used when the time is right for the release
   - [ ] integrate EWA announcements as a part of "office hours"

**Comment by sandyisland1** [comment]
@oksana-c : Not clear on what EWA is. Can this ticket be resolved?

**Comment by oksana-c** [comment]
@sandyisland1 , EWA = Editorial Workflow & Assignments. This is a new initiative that has not yet been kicked off. Parent epic has more context https://github.com/department-of-veterans-affairs/va.gov-cms/issues/2049

**Comment by sandyisland1** [comment]
Thank you @oksana-c : Maggie and I are going through and cleaning up help desk cards.

**Comment by stefaniefgray** [comment]
@jilladams Just saw this was recently moved from Icebox to New/Unrefined for Public Websites -- I think it can be closed since the VA Drupal CMS Helpdeskers have a good idea of roles/permissions and they've already been set in stone on the live site. What do you think?

**Comment by jilladams** [comment]
Yep, that change was automagic nonsense from creating a new board where this ticket was originally caught in our net, but now isn't. So feel free to update it as you see fit -- I'm not actually involved in this particular ticket, just management of that other workspace.

**Comment by stefaniefgray** [comment]
Closing out this older ticket to get it off of the User Support ZenHub board once and for all

cc: @EWashb in case this has anything to do with our current Editorial Workflow tickets? I don't think it does, though
