### ISSUE TITLE
[cms-export] Some referenced entities not being exported

### ISSUE THREAD

**Issue by ElijahLynn** [department-of-veterans-affairs/va.gov-cms#2213]
There are a lot (945) of references to taxonomy_term UUID 7d7e2e18-f91e-4af0-bca2-52a9af9a7b3e, but no such file exists. 

Per https://dsva.slack.com/archives/C01512KN35G/p1594067689197000 (internal). 

![image.png](https://images.zenhubusercontent.com/5cdc72c50b7efe3f164150b2/5049a051-e84b-440c-ac9c-a2a17eb124cb)

**Comment by indytechcook** [comment]
Looking at the latest export the file now exists.  Mostly likely it might have been an issue with the initial export which had been fixed.

```
❯ ll *7d7e2e18-f91e-4af0-bca2-52a9af9a7b3e*
8 -rw-rw-r--@ 1 neil.hastings-a  staff   2.8K Jul  7 09:49 taxonomy_term.7d7e2e18-f91e-4af0-bca2-52a9af9a7b3e.json
```
