### ISSUE TITLE
Source of truth for OKR baselines

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#2214]
## Description

The CMS team needs one Source of Truth for tracking metrics that influence our OKRs.

The goal is to make our OKR computing easier for Q4 and on, as well as have a place where we track metrics for certain efforts that are more granular than OKRs.

## Acceptance Criteria
* a shared source of truth for all tracked metrics exists and is communicated / validated with the team

## Implementation 

- spreadsheet in shared drive

**Comment by kevwalsh** [comment]
@oksana-c the content type proofing KPIs are currently stored in the Drupal Spec tool, in the Bundles tab.

**Comment by oksana-c** [comment]
not doing atm
