### ISSUE TITLE
High level research of Public Websites team's needs for parallel revisioning, and document any possible workaround

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#2222]
AC
- [ ] High level overview of Public Websites use case, documented at the super-epic level
- [ ] A workaround and/or documented recommendation for how the Public Websites team might work in the absence of Parallel revisioning.

To do
- [ ] Meet with members of Public Websites team
- [ ] Document their use case for this epic
- [ ] Document a recommended workaround for their use case

**Comment by howardbrande** [comment]
Zoom recording of initial discussion. PW: s@q7tTLg

https://zoom.us/rec/play/v50lcLio_D83SNKUsASDUP57W42-ePis23BNqfNfz0e0ACQLYwH3YrQXY-puJQUtbXuDrz5_f38JeaoX?continueMode=true
