### ISSUE TITLE
CMS Content Menu stops at 3 levels deep

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#2226]
**Describe the defect**
![image](https://user-images.githubusercontent.com/5752113/87095223-59ca9200-c20e-11ea-9e01-83d41380c739.png)
VISN menus are not accessible because they live at 4 levels deep.

Conversation https://dsva.slack.com/archives/CDHBKAL9W/p1594049167379900

**To Reproduce**
1. hover on Content > Menus > VAMC System Menus > VISN 4
2. VISN 4 neither expands nor is it clickable.   

**Expected behavior**
Should be able to get to /admin/structure/menu/manage/pittsburgh-health-care and other menus under VISN 4 (and VISN 19) and others once they are added.

**Additional context**

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Defect")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS objective (orange) (not needed for bug tickets)
- [ ] CMS-supported product (black)

**Comment by oksana-c** [comment]
will be replaced by https://github.com/department-of-veterans-affairs/va.gov-cms/issues/1351
