### ISSUE TITLE
Appointments fields should not be required, for now

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#2228]
**Describe the defect**

**To Reproduce**
* Go to `node/481/edit`
* 3 appointment fields are required.

**Expected behavior**
* 3 dropdown fields should not be required

**Screenshots**

**Comment by davidconlon** [comment]
Please proceed with this.
We're still working this out when to flip this to required, so we can't prevent the current process or force them into these new ones yet.
