### ISSUE TITLE
Release note to Pittsburgh and VAMC upgrade team about new facility health service form

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#2230]
## Description

Existing editors of facility health service nodes need to know about the changes to the forms from #2998

**Comment by rachel-kauff** [comment]
@kevwalsh I'm curious if this is a compliment to other messaging about that Pittsburgh will get wrt collecting health services data, or if the release note might be the first time they're hearing about it.

**Comment by rachel-kauff** [comment]
@kevwalsh can we close this issue? I thought I remember we decided to let Stan's team do the comms + change mgmt for this stuff.
