### ISSUE TITLE
PHPCS does not scan files with `.module` extension

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#2243]
## Description 

phpcs does not scan `.module` files for coding standard errors.

Fixing this would entail fixing a bunch of errors coming from custom code that we have in codebase today.

## To reproduce

1. Open the following file in IDE - `docroot/modules/custom/disable_node_menu_item/disable_node_menu_item.module`
1. Remove space before the parenthesis in one of the `if` statements or make any other edit that would trigger phpcs warning/error
1. Run `lando composer va:test:cs` or `lando ssh` then `composer va:test:cs`

**Current behavior**
_phpcs is not identifying missing space as an error_

**Expected behavior**
_phpcs throws an error_

**Comment by ElijahLynn** [comment]
This is working now: I followed the test case and it is failing as expected. 
![image](https://user-images.githubusercontent.com/1504756/94627560-c6d04f80-0272-11eb-8690-f55da133f513.png)
