### ISSUE TITLE
Replace node_revision_autoclean with node_revision_delete

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#2250]
## Description
[node_revisions_autoclean](https://www.drupal.org/project/node_revisions_autoclean) has been replaced by [node_revision_delete](https://www.drupal.org/project/node_revision_delete)  

We have been having some issues with node_revison autoclean creating locks during migration runs.   Before trying to patch or resolve that, it would be good to replace the module with its successor and re-evaluate the migration issue.

Configuration here https://prod.cms.va.gov/admin/config/content/revisions-autoclean should be used to replicate the available settings in node_revision_delete

### implementation details
- [x] a hook update needs to uninstall node_revisions_autoclean in va_gov_db.install  (see previous patterns in that file)
- [x] install node_revision_delete and configure
- [ ] follow-up PR to remove node_revisions_autoclean from codebase AFTER the update hook as been released to prod.

**Comment by swirtSJW** [comment]
@kaise-lafrai If there are any options availble in the module that were not present before, please raise them so we can discuss what the setting ought to be.

**Comment by kaise-lafrai** [comment]
@swirtSJW Sure will. Thanks.

**Comment by kaise-lafrai** [comment]
@swirtSJW I don't have access to the prod site yet and cannot compare configuration in order to replicate the available settings in node_revision_delete. Is config different in prod then in my local dev?

**Comment by kaise-lafrai** [comment]
@swirtSJW 

The following are the differences between https://www.drupal.org/project/node_revisions_autoclean and https://www.drupal.org/project/node_revision_delete. 

**Node Revision Autoclean** allowed an admin to adjust the number of revisions directly from `/admin/config/content/revisions-autoclean` . It also gave the option to delete old revisions on cron run or on node update. see below.

![image.png](https://images.zenhubusercontent.com/5f04cf76eb6c0026ebd18020/663b336d-1216-4457-b30d-fac3043d3136)

**Node Revision Delete** provides a table with detailed information for every content type. By selecting edit on a specific content type, an admin can adjust node revision delete settings directly on the content type edit page. There are also some additional global settings and cron settings provided on the `/admin/config/content/node_revision_delete` page. see below.

![image.png](https://images.zenhubusercontent.com/5f04cf76eb6c0026ebd18020/0c35d8a5-c15e-43a9-9308-501f69ce98b7)

![image.png](https://images.zenhubusercontent.com/5f04cf76eb6c0026ebd18020/75fb98d5-55e6-49d4-95cf-b23de088069e)

![image.png](https://images.zenhubusercontent.com/5f04cf76eb6c0026ebd18020/485b4025-fdae-43d1-8ca7-69075e7d099e)

**How do we want to handle the actual node revision deletions moving forward?** 

Option 1 : Currently (with node revision autoclean), according to the configuration settings, node revision deletions seem to happen on node updates. With the new node revision delete module we can allow node revision deletions to be handled through system cron runs. Do we want to give this responsibility to system cron? 

If we decide to do this, we can adjust the following settings and hopefully reduce the pressure on the db:
- How many revisions do you want to delete per cron run?
- How often should revisions be deleted when cron runs?

Option 2 : Looks like we have some drush commands that can also delete revisions.

Let's discuss further on a call if needed.

**Comment by kaise-lafrai** [comment]
WIP PR is here https://github.com/department-of-veterans-affairs/va.gov-cms/pull/2290

**Comment by kaise-lafrai** [comment]
@swirtSJW does this ticket need a drupal spec update and a behat test?

**Comment by kaise-lafrai** [comment]
This ticket is ready for review here: https://github.com/department-of-veterans-affairs/va.gov-cms/pull/2290

**Comment by kaise-lafrai** [comment]
@swirtSJW Do we have a ticket for this yet? If not I can create one and get started on it.

**"follow-up PR to remove node_revisions_autoclean from codebase AFTER the update hook as been released to prod."**
