### ISSUE TITLE
GraphQL timeout

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#2252]
GraphQL is exceeding the max_execution time of 190s in Lando and running in to the max on BRD:dev , but not yet staging or prod.

We need to bump this up on CI and BRD to avoid failure to build vetsweb.

**Comment by ElijahLynn** [comment]
I bumped this to 300 on the ALB and app in BRD here https://github.com/department-of-veterans-affairs/devops/pull/7258. 

Working on CI now.

**Comment by ElijahLynn** [comment]
Updated ALB on DevShop from 120 > 300 and also the PHP `max_execution_time` on DevShop and reloaded Apache. Committed here too https://github.com/department-of-veterans-affairs/devops/commit/24a5ebf43126973c6b3b1a788c7eb5fbad36aa60
![image](https://user-images.githubusercontent.com/1504756/88571486-92ca7b00-cff2-11ea-8a66-480f9ab514b8.png)

Next up a PR for Lando.
