### ISSUE TITLE
CLP Stories panel

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#2260]
As a CMS user, i can opt in to add a Stories panel to my Campaign Landing Page

![CLP-Maximal-markup-updated-060320_pdf__1_page_.jpg](https://images.zenhubusercontent.com/5d6e57ad330f64311395f08b/dea4805c-63e8-4f56-9b18-d1b4e769d5f7)

ACs
- [x] ~field_clp_stories_opt_in~ 
- [x] `field_clp_stories_panel`
  - Boolean field labeled "Add a Stories panel" 
  - True label: "Stories panel"
  - False label: "No stories panel"
  - Help text: "Stories panels allow up to two links to blogs or stories."
- [x] `field_clp_stories_header`
  - Plain text single line field
  - Maximum 70 characters
  - Textfield with counter "N characters remaining"
- [x] `field_clp_stories_intro` 
  - Multiline plain text field with label 
  - Maximum 350 characters
  - Textfield with counter widget "Maximum 350 characters, but 120 characters is recommended. X characters, Y characters remaining".
- [x] `field_clp_stories_teasers` 
  - [x] Entity reference revisions (paragraphs) field "Add up to two stories" (with max 2 values)
  - [x] Form configuration: paragraphs classic with pre-loaded entity form. 
  - [x] New paragraph bundle "Link teaser with image" ` 
    - `field_media` enabled for images, field label "Image ~field~", help text suggestion 3:2 aspect ratio. 
    - `Link teaser` entity reference revisions field
    - Let's review 
- [x] `field_clp_stories_cta` 
  - Link field with no link text allowed, label "Add a link to an external blog or other list of stories"
- [ ] All fields are optional, for now.

**Comment by kaise-lafrai** [comment]
@kevwalsh How does this experience look?

![Screen Shot 2020-12-01 at 2.30.22 PM.png](https://images.zenhubusercontent.com/5f04cf76eb6c0026ebd18020/666d2c32-15bd-48b4-bd11-7b129d6d0739)

**Comment by kevwalsh** [comment]
![CLP_Stories_panel_·_department-of-veterans-affairs_va_gov-cms.jpg](https://images.zenhubusercontent.com/5d6e57ad330f64311395f08b/ddcbc22a-3f2d-4552-9a1f-c56284f69d62)

Can you push what you have to a PR so we can fiddle with some of these widget options on a PR environment?

**Comment by kaise-lafrai** [comment]
Those remove buttons should go away once we make the field required but would have to be tested thoroughly since we are handling making fields required with code.

**Comment by kaise-lafrai** [comment]
I am attempting to rebase my branch but running into some composer issues. Hope to push the PR shortly after.
