### ISSUE TITLE
CLP: Contextual help text for content strategy

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#2266]
[Title was: "CLP Form design, UX writing (labels and help text)"]

## User story

As a creator or editor of a campaign landing page
* i understand the purpose and strategy of each part of the content i am creating and editing, clear guidance and guardrails for creating quality content.
* the UI for creating content is intuitive and behaves as expected

## Background 
Designs are posted here for mobile, desktop, including both minimal (4 required panels) and "maximal" (4 required panels plus 7 optional panels) https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/content/tier-2-content-IA-and-design/campaign-landing-page-templates

Latest design spec with some content strategy annotations https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/campaign-landing-page-templates/content-requirements-spec/CLP-Maximal-markup-updated-060320.pdf 

Form URL: prod.cms.va.gov/node/add/campaign_landing_page

Some content design / rigidity specs: 

https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/content/tier-2-content-IA-and-design/campaign-landing-page-templates/content-requirements-spec

and recent decision log

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/campaign-landing-page-templates/content-requirements-spec/cms-content-model-and-rigidity.md

## ACs (pending prioritization through some co-working)

- [ ] The overall form has an MVP intro text, explaining the purpose of campaign landing pages. 
- [ ] Each required "panel" (word TBD) has some guidelines for it purpose. 
- [ ] Stretch: some of the optional panels have guidelines. 

Other thoughts / future priorities
- [ ] The "Opt-in" approach to 7 optional "panels" has clear and consistent labeling and help text. 
- [ ] The CLP page form (/node/add/campaign_landing_page) introduces a new UI pattern to content forms--a set of vertical tabs. Vertical tabs exist elsewhere in the CMS, such as alert block editing forms, but not on node forms for the main content. The UI received good feedback from some experienced CMS users, but is it the right pattern? 
- [ ] How should we handle required/optional? Is this the right time to make "(optional)" the differentiator, instead of "*" (required)? Can we do this just for tabs but not for all the fields. Engineering says yes but is it good UX? Do we want to go down this road here if we're not implementing it anywhere else in the CMS?  
- [ ] Field labels and field help text have been improved for clarity
- [ ] Complex widgets have been reviewed and possibly improved. 
- [ ] TBD

Not in scope (yet, anyway)
- [ ] Content proofing design.

**Comment by kevwalsh** [comment]
Next steps: 

- Rachel will will set up wires in Balsamiq for CLP with text boxes for Natalie. 
- Natalie will schedule 30 minutes followup Wednesday Dec 9 with Rachel

**Comment by rachel-kauff** [comment]
WIP Wireframe setup for this issue: https://balsamiq.cloud/s21kwcm/py46j7t/r48AD

**Comment by nataliedunbarCS** [comment]
Met with Rachel Dec 8 and agreed upon the following approach:
1. Rachel will develop wires and draft microcopy (field labels and field help text) for the four required panels by 12/10 to be shared with Natalie.
2. Natalie will develop draft "macrocopy" to satisfy the first two ACs, for the overall form, and for the four required sections to start.

TBD: Style guide rules and related guidelines for word/character count, where content will be positioned, etc.

**Comment by kevwalsh** [comment]
This was complete in #3798
