### ISSUE TITLE
CLP: Draft training materials (slides) for MVP users 

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#2270]
### User Story
As a VA.gov editor, I need access to training so I know how to use campaign landing pages in Drupal CMS.

Assumption: users will have exposure already to CMS

### Acceptance Criterial
- [x] Training slides are drafted
- [x] Training slides are reviewed

**Comment by xiongjaneg** [comment]
Is a recorded training video desired?

**Comment by xiongjaneg** [comment]
TBD our participation in this, will discuss 2/23/21

**Comment by xiongjaneg** [comment]
Split into draft/finalize stages because they cross sprints. See [#4545](https://app.zenhub.com/workspaces/vagov-cms-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/4545)

**Comment by xiongjaneg** [comment]
Requested review from John via Slack 3/5/21
