### ISSUE TITLE
CLP: New user onboarding for MVP.

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#2271]
### User Story
As a VA editor, I need to be able to use the Drupal CMS to create a campaign landing page (CLP) for time-based marketing or engagement content for Veterans or other audiences.

### Acceptance Criteria

- [ ] The user has access to training/support resources on CMS help center.
- [ ] The user has access to training, live or on-demand.
- [ ] The user has access to the production environment.

**Comment by xiongjaneg** [comment]
Initial training tentatively the week of March 8, 2021

**Comment by xiongjaneg** [comment]
TBD our participation in this, will discuss 2/23/21
