### ISSUE TITLE
Revision counts too high for some facilities 

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#2277]
**Describe the defect**
There are a number of revisions that all have the same timestamp that came in from the migration.   For some reason these old revisions are not being cleaned up by revisions autoclean.   The setting is not supposed to keep more than 500 revisions for a vha facility, but over 3,000 exist for a single node (node 1884).   

This issue is resulting in DB locks during the hourly facility migration.

This query illustrates that there are 5422 revisions witht he same troublesome timestamp.
`select * from node_revision where revision_timestamp=1572551719`

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information if relevant, or delete):**

**Additional context**

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Defect")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS objective (orange) (not needed for bug tickets)
- [ ] CMS-supported product (black)

**Comment by indytechcook** [comment]
Relating to https://github.com/department-of-veterans-affairs/va.gov-cms/issues/2229

**Comment by oksana-c** [comment]
resolved in #2229. closing.
