### ISSUE TITLE
User can't interact with save button when there's multiple site alerts on the screen

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#2289]
## Description

When there’s multiple alerts of low or medium severity, they cover the bottom of the screen so users can’t see/hit the save button.

See [slack thread](https://dsva.slack.com/archives/CT4GZBM8F/p1594839563402300) for implementation ideas

## Acceptance Criteria

- [ ] user can interact with/see save button when there's multiple (2-3) alerts on the screen that are of low or medium severity

**Comment by EWashb** [comment]
We no longer use site alert. It was deprecated with the implementation of sitewide alert.
