### ISSUE TITLE
Test VAMC training and incorporate feedback

### ISSUE THREAD

**Issue by howardbrande** [department-of-veterans-affairs/va.gov-cms#2298]
As the training manager I want to conduct a beta training with 

* one or two members of the CMS team and (include rachel)
* one or two members of the VAMC upgrade team 
* Facilities product owner

to get feedback and dry run the training

AC:
- [ ] Training delivery method is ready to go
- [x] Beta Training is scheduled
- [x] Feedback is recorded
- [ ] Feedback is implemented into training in preparation for actual training to VISN 4

**Comment by daddison48** [comment]
@howardbrande is going to schedule the dry run course for 8/25

**Comment by daddison48** [comment]
@howardbrande to look for 30 mins to provide a "CMS 101" dry run session with David, Rachel, and Kev

**Comment by daddison48** [comment]
https://drive.google.com/drive/folders/1uEQsHy34cOGZxfmzq4d2ucwckw26We1e

**Comment by daddison48** [comment]
Dry run feedback notes: https://docs.google.com/document/d/1vCxox-JNtC8HfIC2b9d1I8cCy5uec_MYqE3_fLqrPso/edit?ts=5f45661c
