### ISSUE TITLE
[LC] Step-by-step content type

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#2299]
# Description

Create Step-by-step content type.

## Acceptance criteria

- [ ] content type "Step-by-step" with machine name `step_by_step` exists and contains the following fields:
   - [ ]  **Intro text** – `field_intro_text` – 1,000 characters max including spaces
   - [ ] meta tag fields - see other content types 
   - [ ]  **CTA component** - `field_buttons` | Label `CTA buttons` (#2303) :
       - [ ] at least 1 required
       - [ ] up to 2 max
   - [ ] **Optional: Repeat same CTA(s)** – boolean field `field_buttons_repeat` | Label `Repeat CTA buttons` |  Example: User can omit repeat if page is short as in a single FAQ page
   - [ ] **Step-by-step component** - `field_steps` (#2323) - required - single cardinality - allows for "Step-by-step" paragraph type only
- [ ] editorial experience does not suffer regressions. Any existing patterns are used. E.g. help text, widget config, etc.
- [ ] Step-by-step content type is included in Editorial workflow
- [ ] spec tool is updated with new content model

**Comment by kaise-lafrai** [comment]
> Intro text – field_intro_text – 1,000 characters max including spaces.

>  CTA component - field_cta field_button.

@oksana-c What should the field labels be for the above fields?

**Comment by oksana-c** [comment]
mornin @kaise-lafrai, see updated ACs.

**Comment by kaise-lafrai** [comment]
@oksana-c  

> CTA component - field_buttons | Label CTA buttons (#2303):

The CTA component will need rework if we want to change the machine name to field_button**s**.

**Comment by kaise-lafrai** [comment]
@oksana-c disregard last comment.

**Comment by oksana-c** [comment]
`field_buttons` is a component/paragraph reference field, not the field within the component.

**Comment by oksana-c** [comment]
👍
