### ISSUE TITLE
[LC] "FAQ - multiple Q&As" content type

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#2313]
## AC

- [ ] content type offers an ability to add Q&A sections | cardinality multiple
- [ ] new paragraph type "Q&A Section (FAQ multiple) contains the following fields
    - [ ] Section header | plain text | required
    - [ ] Section intro | plain text | optional | char limit 300
    - [ ] Q&A | entity reference | required | cardinality - unlimited
- [ ] Authoring experience for attaching Q&A to a section has the following constraints
    - [ ] only existing Q&A can be searched and referenced
    - [ ] authoring experience is similar to alert, where user can look up Q&A they'd like to attach
    - [ ] attached Q&As can be easily reordered

**Comment by jenniferlee-dsva** [comment]
@oksana-c - I think this is closed so probably doesn't matter, but I noticed a couple of mistakes in the content requirements and edited per the requirements template in the product repo. I *think* this was build correctly using the source template documentation, but please confirm.

**Comment by oksana-c** [comment]
@jenniferlee-dsva , thanks for noting this. Page intro will be adjusted to 1000 on prod this afternoon. Section headings live as plain text in the CMS, then converted to H* tags by FE logic. It is currently up to FE templates to define which H tag to render.
