### ISSUE TITLE
Customer service CTA block

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#2320]
[Howie's mockup](https://docs.google.com/presentation/d/1buX6VeEji-Ya7ggP-AvUF2-BBm47DWGE/edit#slide=id.p1)
- Moving admin information out of the default help user experience

![User_guide_strategy_•_Agile_Six_Workspace.jpg](https://images.zenhubusercontent.com/5d6e57ad330f64311395f08b/20ea3c20-8c1f-47e4-9680-f0ed26306e92)

AC:
- We've identified the CTAs for support

- We know where to implement them
-

====

## CTAs

**Contact help desk** - link to a page? form?
 * Direct support as an editor
 * Request an account
 * Request a change of permission
 * Report a bug 
 * Office hours

**Get training** - link to a form?

**Request a new feature** - link to a form?

**Give feedback** - link to a form?

**Help guides** - link to user guides home page

### Other candidates for CTAs

* **Request an account or change of permission**

## CTAs design 

* Sidebar?
*

**Comment by cmaeng** [comment]
This was completed in a previous sprint but just catching it now. Will close in sprint 19 for reporting purposes.
