### ISSUE TITLE
Parent sections fail to show content owned by child sections

### ISSUE THREAD

**Issue by howardbrande** [department-of-veterans-affairs/va.gov-cms#2332]
**Describe the defect**
When a user selects a "Section" when they first log in it shows only the pages owned by that section, in this case Veterans Benefits Administration showing 27 results. When you select a subsection, "VBA Benefits Hub" it lists no results until you select a specific section. https://www.loom.com/share/2dc26abfef564304909e801cd7633027

**Example 1**

1. Go to https://prod.cms.va.gov/section/veterans-health-administration/visn-4
2. You should see all the content owned by all the VAMC systems in VISN 4, but you see 0.
3. Strangely, if you go "up" a level, you'll see 1200+ results at https://prod.cms.va.gov/section/vamc-facilities
4. If you go to the top level (VHA), there is only 1 result https://prod.cms.va.gov/section/veterans-health-administration

**Example 2: VBA**

* [Top level section page](https://prod.cms.va.gov/section/veterans-benefits-administration) shows 27 results, but no content associated with child sections. It should show 474 facilities, and all the content associated with the VBA benefits hubs 
* [VBA benefits hubs](https://prod.cms.va.gov/section/vba-benefits-hubs) shows 0 results, it should show ~250 for all the child sections

**Background**
Taxonomy entity index was being used to make this work, previously.

**Comment by kevwalsh** [comment]
On staging, I tried rebuilding the Taxonomy Entity Index (admin/config/system/taxonomy-entity-index/reindex) but it didn't see to have any effect.

**Comment by kevwalsh** [comment]
Stan noted in [this thread](https://dsva.slack.com/archives/CDHBKAL9W/p1595561789001500) that this is blocking VAMC upgrade team.

**Comment by swirtSJW** [comment]
We should look at a proper install of taxonomy_entity _index rather than the local install of it.  I know Cameron took over maintainership of that module and made some improvements we must not be capturing.
