### ISSUE TITLE
Menu breadcrumb is not enabled for many menus

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#2336]
**Describe the defect**

* Many menus do not have menu breadcrumb enabled, so breadcrumbs are wrong. This may also explain some CMS export issues. 

**To Reproduce**
1. Go to https://prod.cms.va.gov/erie-health-care/mission-and-vision ... 
2. Breadcrumb is missing About us

**Expected behavior**
Breadcrumb should  "About" and the current page name, like on `/pittsburgh-health-care/about

**Screenshots**
![Menu_Breadcrumb___VA_gov_CMS.jpg](https://images.zenhubusercontent.com/5d6e57ad330f64311395f08b/5adb2206-6fb1-4d98-a0da-987fc2615eaa)

**Comment by swirtSJW** [comment]
These are not stored in config so I updated them on prod.  
![image](https://user-images.githubusercontent.com/5752113/87832869-f5828080-c854-11ea-9d8b-2b53996ee959.png)

**Comment by swirtSJW** [comment]
![image](https://user-images.githubusercontent.com/5752113/87833515-0bdd0c00-c856-11ea-84d9-fbd869d5116f.png)

**Comment by swirtSJW** [comment]
Odd thing just discovered.: Making these changes and then running `lando drush cex` created no export.   So the changes were made on prod.   However When exporting other config, the config for this exports too.
