### ISSUE TITLE
[deploy] Deployment message says 4:0 pm today.

### ISSUE THREAD

**Issue by ElijahLynn** [department-of-veterans-affairs/va.gov-cms#2348]
**Describe the defect**
During deployments our deployment message says "Around 4:0 PM ET..."

![image](https://user-images.githubusercontent.com/1504756/87964335-ed059200-ca6e-11ea-8125-0c029be6ac52.png)

## AC

- [ ] deployment time shows two zeros if its at the top of the hour

**Comment by oksana-c** [comment]
already fixed
