### ISSUE TITLE
CMS Export tar endpoint should use basic auth

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#2349]
## Description
Our graphql and open_api endpoints both use basic_auth to restrict access.   Currently our content tar endpoint is open to any request.   It would be good to mitigate DOS risk by enabling basic auth on the endpoint too.
CMS Exort should implement a similar method to 
docroot/modules/custom/va_gov_consumers/src/Routing/RouteSubscriber.php

## Acceptance Criteria
* Update to readme documentation
* Endpoint requires basic auth similar to our other endpoints.
* Rollout is coordinated with FE team so they can have uninterrupted access to the content export.

**Comment by ElijahLynn** [comment]
I don't think we are at risk of a DDoS for this endpoint and would like to keep it open for ease of debugging. This endpoint doesn't make much of a database request and just tars the directory and is mostly just an Apache file request. I would like to discuss it further and consider closing this issue.
