### ISSUE TITLE
Ability to browse content export directory on prod

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#2350]
## Description

Currently trying to browse the content export files is blocked from browsing which makes it more complicated to debug issues.   The content in the content export is open (no sensitive data) .  INstead of being presented with "access denied on trying to see the directory, it would be nice to see the file list and be able to view the content of the file too.
## Acceptance Criteria
* Visit https://prod.cms.va.gov//sites/default/files/cms-export-content and see file listing
* Visit https://prod.cms.va.gov/sites/default/files/cms-export-content/node.a9dfedf2-ed76-43af-82a2-04ec962b453f.json and see the file content.

**Comment by oksana-c** [comment]
closing until we get to working on preview strategy
