### ISSUE TITLE
Was this useful? User guide button UX / design

### ISSUE THREAD

**Issue by rachel-kauff** [department-of-veterans-affairs/va.gov-cms#2353]
# Background
We need a way to gather feedback on individual cms user guides. Possibly in the form of a "was this helpful? yes/no" feedback loop for users.

## Acceptance criteria

- [ ] we know what data we want to collect base on design of "Was this helpful" component 
- [ ] UX / design for "Was this useful?" user guide component is available in a form of an interactive prototype
- [ ] implementation feasibility is assessed w/ an engineer
- [ ] define what user feedback we can get from users before handoff to engineers
- [ ] get user feedback on the prototype

**Comment by kevwalsh** [comment]
closing this in favor of #5811 and #5812
