### ISSUE TITLE
Drupal spec tool character limit constraint blocks content model changes

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#2364]
## Description

we are now hitting character limit constraint in Google Sheets - `Text result of JOIN is longer than the limit of 50000 characters.` which effectively blocks merges for content model changes

## Acceptance Criteria
- [x] character limit workaround is implemented for Drupal spec tool
- [x] behat tests for content model are generated without errors

## Implementation

- see suggestions in https://github.com/acquia/drupal-spec-tool/issues/11

**Comment by swirtSJW** [comment]
I ran into this with fields and bundles, which were all one feature.   I got around the limit by breaking them out  into two separate exports.  I am surprised we hit this so soon.

**Comment by oksana-c** [comment]
[Spec tool](https://docs.google.com/spreadsheets/d/1vL8rqLqcEVfESnJJK_GWQ7nf3BPe4SSevYYblisBTOI) is now refactored to avoid character limit errors.

- Content model "Fields" tab is split into 5 new tabs, each covering one entity type. Behat test scenario that covered all content model fields is now split into 5 separate scenarios.
- Several other tabs within the spec tool spreadsheet have also been refactored to ensure that formulas and references match new content model tabs.
- Custom Behat context for the spec tool is also refactored to support processing of one entity type at a time. See #2363
- Each entity type test now has a corresponding tag that can be used to run tests for a single entity type. E.g. `behat --tags=content_type_fields`
