### ISSUE TITLE
Remove unused modules

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#2388]
## Description
Currently we have several modules that are not enabled and should just be removed from the codebase

- [ ] Acquia Connector
- [ ] Acquia Search
- [ ] Acquia Telemetry
- [ ] autosave_form
- [ ] lightning_contact_form  (contact form)
- [ ] Contact
- [ ] Contact Storage
- [ ] panels
- [ ] Moderation Dashboard

**Comment by ethanteague** [comment]
Contact is a drupal core module, @swirtSJW - thinking you may have added that to the above list inadvertently.

**Comment by ethanteague** [comment]
Increasing estimate on this one - a lot of the above are tied into lightning, and trying to remove is causing a daisy-chain of dependency errors.
