### ISSUE TITLE
Remove Writing of tome sync index.json file 

### ISSUE THREAD

**Issue by indytechcook** [department-of-veterans-affairs/va.gov-cms#2391]
Currently `tome_sync` writes an `index.json` file on every save and entity export.  The `index.json` file is currently only used when tome sync imports.  

## AC
* When a node is saved the index.json file should not be updated or created.
* When build export occurs the index.json file should not be updated or created.

**Comment by ElijahLynn** [comment]
Can you post the before and after export times and the total amount of entities? I think this would be good public knowledge.

**Comment by indytechcook** [comment]
I tested on my local setup with lando/docker the saved time is approx: 1 hr 7 min.

Test setup:
* 2019 16in MBP
* 8 core 2.3 Ghz
* 32 GB memory
* docker VM

commands run: `lando drush tome:export --process-count=8 --entity-count=500`

Using git tag `tags/cms/v0.0.149`
* start time: 9:12:53am
* end time: 10:22:36am
* **total time: 1 hr 9 min 23 sec**

Using git tag `tags/cms/v0.0.150`
* start time: 10:28:10am
* end time: 10:31:38am
* **total time: 3 min 28 sec**

**Comment by ElijahLynn** [comment]
Wow, nice work Neil! :100: and a :star2: for you!
