### ISSUE TITLE
Enable workbench access for all content types

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#2393]
**Describe the defect**
Some content types are missing the workbench access setting, which means some governance is missing. 

**To Reproduce**
* Go to `admin/config/workflow/workbench_access/access_scheme/section/edit`

**Expected behavior**
![Edit_Section___VA_gov_CMS.jpg](https://images.zenhubusercontent.com/5d6e57ad330f64311395f08b/39f0b13b-65aa-4336-8ecb-4db769c662b7)

**Comment by swirtSJW** [comment]
WARNING!!! If we are intentional about wanting to add Full WIdth banner alerts to workflow, we need to alter the govdelivery logic so that we only get notifications sent under the right conditions.

**Comment by ethanteague** [comment]
> WARNING!!! If we are intentional about wanting to add Full WIdth banner alerts to workflow, we need to alter the govdelivery logic so that we only get notifications sent under the right conditions.

cc: @kevwalsh @oksana-c

**Comment by oksana-c** [comment]
@swirtSJW @ethanteague , the PR Ethan opened (#2627) adds banner to editorial workflow. The ask in this issue is to add all content types to Workbench Access config, not to the Workflow. 
Workbench Access config will not affect any govdelivery settings. It only affects access to content editing based on user belonging to Sections.

Here's config page for reference - `/admin/config/workflow/workbench_access/access_scheme/section/edit`

**Comment by ethanteague** [comment]
> /admin/config/workflow/workbench_access/access_scheme/section/edit

Thanks, @oksana-c : https://github.com/department-of-veterans-affairs/va.gov-cms/pull/2684

**Comment by ethanteague** [comment]
Blocked on this one, @oksana-c  @kevwalsh @swirtSJW  = can't resolve the moderation status selector error. Manually testing, it is visible. Updated perms, other config, etc., but can't resolve.
![image.png](https://images.zenhubusercontent.com/5e2b1d8b2f4d80671f879681/55e19fe1-344e-4cdf-b833-44e938df3df1)

**Comment by ethanteague** [comment]
@kevwalsh do you have any insight into this test failure? I've been blocked on this one for a while.
cc: @oksana-c @swirtSJW

**Comment by oksana-c** [comment]
@ethanteague , per our chat in Slack, let's remove `documentation` page from this test. We'll be following up with a more comprehensive test coverage for "Section"  based access.

**Comment by ethanteague** [comment]
> @ethanteague , per our chat in Slack, let's remove `documentation` page from this test. We'll be following up with a more comprehensive test coverage for "Section" based edit access - #2725

Thanks, @oksana-c - done.
