### ISSUE TITLE
Remove RSS icon from Section dashboards

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#2434]
**Describe the defect**
Sections pages shows (eg /section/vba-benefits-hubs) show RSS icons. They should not. 

**To Reproduce**
1. Go to /section/vba-benefits-hubs

**Expected behavior**
No RSS icon should appear. 

**Screenshots**
![image](https://user-images.githubusercontent.com/643678/88600646-c4683400-d03c-11ea-88a1-a8c8fff50fbd.png)

**Comment by oksana-c** [comment]
dashboards will use custom views instead of default taxonomy term view, which will remove rss button without additional effort
