### ISSUE TITLE
[LC] Step-by-step component alert

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#2452]
## Description

As a Content Editor, I need an option of adding an Alert right below the Step WYSIWYG field, so that the Alert can be displayed in the context of a step.

## Acceptance Criteria
- [ ] Alert can be placed below the WYSIWYG and above the optional Image.
- [ ] user can only add one alert within the step | single cardinality
- [ ] Alert is available within the step by step component globally, no need to customize per product.
- [ ] editors cannot add both "reusable" and "not reusable" alert at the same time (the existing component doesn't have the rigidity that we need here)
- [ ] Alert paragraph in Benefits detail page support addition of only one type of alert - reusable or not.
- [ ] spec tool is updated

![Create_Benefits_detail_page___VA_gov_CMS.jpg](https://images.zenhubusercontent.com/5d6e57ad330f64311395f08b/fedf6475-df4b-4980-b3e6-6c294b7411df)

## Implementation

- paragraph form alter hook to target paragraph type `alert`
- add radio button field `field_alert_selection` and expose reusable or non-reusable alert form element based on field option selection

**Comment by kaise-lafrai** [comment]
@oksana-c I want to confirm if the alert should be added to the step-by-step component or the step component. Reason I am asking is because I see this AC: **Alert can be placed below the WYSIWYG and above the optional Image.** and this in the Description: **As a Content Editor, I need an option of adding an Alert _right above the Step WYSIWYG field_, so that the Alert can be displayed in the context of a step.**

Thanks

**Comment by kaise-lafrai** [comment]
@ethanteague https://github.com/department-of-veterans-affairs/va.gov-cms/issues/2452.

Desired functionality below.

- Go to add content > step by step

- Scroll down to 'step by step' > Alert

- Select the 'Reusable' radio button

- Add a 'Reusable' alert 

- Once a 'Reusable' alert is added, the 'Alert' selection radio buttons should become disabled.

- Remove the 'Reusable' alert and confirm the 'Alert' selection radio buttons are now enabled.

**Comment by oksana-c** [comment]
## Updated ACs

_we've learned that in order to achieve desired UX for adding a single Alert [either reusable or non-reusable], we need to change the existing paragraph type structure too drastically, which in turn will require migration of existing alert paragraph data into a new content model. In order to avoid the migration blocker, we've made a decision to introduce a new paragraph type to support "single Alert" UX for the Learning Center templates and take care of migrating existing paragraphs data into a new content model at a later date._

---

- [ ] create a new paragraph type "Non-reusable Alert" | machine name `non_reusable_alert`
   - fields (same fields that are presented for a non-reusable Alert in "Alert" paragraph type):
        - Alert Heading | field_alert_heading
        - Alert Content | field_va_paragraphs
        - Alert Type | field_alert_type

- [ ] create  a new paragraph type "Alert (single)" | machine name `alert_single`
    - fields
          - Alert Selection | field_alert_selection | two options "Reusable
, "Non-reusable". 
          - Reusable alert | field_alert_block_reference
          - Non-reusable Alert | field_alert_non_reusable_reference | reference to "Non-reusable Alert" paragraph

- [ ] add "Alert" `field_alert` to "Step" paragraph, below WYSIWYG. Field can reference only paragraphs of type "Alert (single)"

- [ ] option selected in field_alert_selection should control alert type form presented to user. 
- [ ] when one type of alert is added, the field_alert_selection cannot be switched to a different type of alert until the user deliberately removes data from the alert entity reference field.

**Comment by kaise-lafrai** [comment]
@oksana-c This looks good to me. I will get this setup and let you know if I have any issues or questions.

**Comment by kaise-lafrai** [comment]
This is ready for review.

**Comment by kaise-lafrai** [comment]
Found a bug in the code logic for behaviors. Continuing work on this.

**Comment by kaise-lafrai** [comment]
@oksana-c This is ready for review! To be thorough I updated the testing steps for you. Thanks!
