### ISSUE TITLE
[LC] Media list - images component

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#2453]
## Acceptance criteria

- [x] "Media list - Images" paragraph type exists to support the Learning Center template

## Implementation

- [x] add `field_description` to Image media type | plain text field | Char limit 300 | optional

- [x] create new paragraph type "Media list - Images", machine name `media_list_images`, with the following fields:
    - [x] "Section Header" `field_section_header` | optional
    - [x] "Images" `field_images` | entity reference to Media type "Image" | cardinality - unlimited
    - [x] spec tool / tests update

**Comment by oksana-c** [comment]
removed "Render images as an ordered list" field req.

**Comment by kaise-lafrai** [comment]
@kaise-lafrai, let's adjust a few things:

field description - switch to Text (plain, long). Max char help text should match other text fields we have "Characters remaining: X"
Paragraph display settings: Section heading displayed at the top and images right after.
field_images is required
thank you
