### ISSUE TITLE
[LC] Media list - videos component

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#2454]
## Acceptance criteria

- [x] "Media list - Videos" paragraph type exists to support the Learning Center template

## Implementation

- [x] create new paragraph type "Media list - Videos", machine name `media_list_videos`, with the following fields:
    - [x] "Section Header" `field_section_header` | optional
    - [x] "Videos" `field_videos` | entity reference to Media type "Video" | cardinality - unlimited
    - [x] spec tool / tests update

**Comment by oksana-c** [comment]
In order to create a Video entity in the CMS, we collect the following information:
* Name (video title)
* Video URL (Currently supports YouTube and Vimeo URLs)
* Owner (governance)

"Media list - videos" template in the Learning Center displays the following information about each Video:
* Name (video title)
* Video thumbnail / embedded video
* Duration
* Date
* Description

The duration, date and description are maintained by YouTube. Example video - https://www.youtube.com/watch?v=uTVWeIXgqNs
In order to prevent duplication and maintenance of this information in the CMS, I recommend using [YouTube API - Videos](https://developers.google.com/youtube/v3/docs/videos#resource-representation) to query duration, date and description data at the time the FE page is built instead of adding fields in the CMS to store this data.

@ncksllvn @kelsonic - please review technical feasibility of this approach at your end and let me know if you have any concerns.

FYSA @jenniferlee-dsva

**Comment by ncksllvn** [comment]
The YouTube API seems like a good approach to me. I've never explored it though, so first things that come to mind - 

1. Does it require an API key, and if so, is the API key a secret? If it is, we'd have to build a proxy route in vets-api to conceal the API key if we're planning on querying from the browser. This isn't ideal. I'm seeing "Every request must either specify an API key" in the [docs](https://developers.google.com/youtube/v3/docs) so it seems like it.
    - We _could_ hit the YouTube API during the website build, but that's more overheard in an already complex process.
1. Is it free?

**Comment by oksana-c** [comment]
@ncksllvn 
1. yes, API key is required
2. free with a quota - see [here](https://developers.google.com/youtube/v3/getting-started)

We've entertained some options that may be available to pull this video duration, date and description from Youtube into the CMS instead of during FE build. There are no OOTB solutions. Options we explored require a good amount of engineering.

@jenniferlee-dsva 
To make an informed decision in regards to the source of this data for FE templates, we'll need the following questions answered:

_Youtube API provides a video description as long as it was entered for that video on YouTube._ 
1. Pulling YouTube video description into Drupal or FE will avoid data duplication. E.g. both YouTube and va.gov LC page will have the same consistent content. Is content consistency between Youtube and FE important for the Learning Center?
1. In the scenario where we pull description from YouTube, will there ever be a need for the Content Editor to override it?


FYI, the MVP version for the "Media list - Videos" component is to offer YouTube links for videos without video metadata (duration, date and description). Once we settle on the approach for video metadata management, we'll generate a new user story.

**Comment by jenniferlee-dsva** [comment]
@oksana-c  - answered in-line above. LMK if those answered your Qs completely.

**Comment by oksana-c** [comment]
@jenniferlee-dsva , this is exactly what I needed. Thank you!

**Comment by kaise-lafrai** [comment]
oksana-c left a comment
@kaise-lafrai let's make field_videos required. Otherwise this is good to go. Noting here, that video display config and form widget may need to be adjusted as a part of the related Content Type issue.
