### ISSUE TITLE
[LC] Media list - videos content type

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#2456]
## Acceptance criteria

- [ ] New content type "Media list - Videos" is created to support the Learning Center template

## Implementation

- [ ] content type "Media list - Videos" | `media_list_videos` exists
   - [ ] mimic field structure of the Checklist content type - `node/add/checklist`, with an exception of "Checklist" field `field_checklist`
   - [ ] add field "Alert" `field_alert | entity revisions reference to "Alert (Single)" paragraph only | cardinality single | optional` directly under "Title and introduction" fieldset
   - [ ] add `field_media_list_videos` below CTA buttons field | label "Videos" | entity reference to paragraph type "Media list - Videos" | cardinality - single
  - [ ] editorial / node view experience is using established patterns and does not have UX regressions
  - [ ] spec tool / tests update

**Comment by kaise-lafrai** [comment]
Ready for review. Let me know if you have any questions or concerns.
