### ISSUE TITLE
Update table caption help text

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#2457]
## Description

Table caption states the following `This brief caption will be associated with the table and will help screen reader better describe the content within.` , which suggests that this caption will not be visible on the rendered page.

## Acceptance Criteria
* Table caption help text is updated to indicate that the caption will be visible once page is rendered. Suggested help text: `This brief caption will be associated with the table, rendered as a table heading in bold and will help screen reader better describe the content within.`

## Implementation

Table field widget may require some hard overrides, e.g. via form_alter.

**Comment by oksana-c** [comment]
@rachel-kauff , please review suggested help text before this ticket moves to engineering.

**Comment by rachel-kauff** [comment]
@oksana-c You got it. A few questions: where can I see the UI where this help text will be implemented, for context? Also, is this something we're trying to accomplish this sprint (or sooner?)

**Comment by oksana-c** [comment]
@rachel-kauff Sprint 13/14 . UI can be examined when adding a Table paragraph to Main Content on the Detail page.

**Comment by rachel-kauff** [comment]
@oksana-c Perfect, thanks!

**Comment by oksana-c** [comment]
@rachel-kauff , did you review table caption text before this went out?
