### ISSUE TITLE
Add conditional fields to event content type

### ISSUE THREAD

**Issue by rachel-kauff** [department-of-veterans-affairs/va.gov-cms#2460]
## Description
Lack of conditional fields on the event content type form, especially for the address field group, is making it really confusing to use.

As a user, I only want to see fields that are relevant to my previous choices on the form.

## Acceptance Criteria
* [ ] If `Location type` = `VA facility`, then display `Facility location` field and make it required
* [ ] If `Location type` = `VA facility`, then display the field formerly known as`A human readable label...` soon to be changed to `Building, floor, or room` 
* [ ] If `Location type` = `Online`, display `Location URL` field
- [ ] If `Location` = `Online`, then don't display the `Address` field group and don't make it required.
- [ ] If `Location` = `VA facility` then don't require fields in the `Address` field group (this assumes that the system is managing to provide an address automatically based on the VA facility selected). 
- [ ] If `Location` = `VA facility` and the user opts to add a custom address, use that instead of the one automatically supplied by the facilities locator api.

### Implementation recommendations
1. We have a bunch of work on the horizon related to events that I would like to contain it in a new module `va_gov_events`.   It should be created as a result of this issue and related code should live there.

## Aritfacts
Annotated MURAL for event form help text:
<img width="950" alt="Screen Shot 2020-07-28 at 11 26 18 AM" src="https://user-images.githubusercontent.com/41017988/88706040-2bc9c680-d0c5-11ea-9b1e-1f56a05f7aa9.png">
- [MURAL link](https://app.mural.co/t/vagov6717/m/vagov6717/1595867163702/318273f5fb1166d8fb771da1c63ffbd16ae7073d)

**Comment by ethanteague** [comment]
https://www.figma.com/file/3ysYRmbHbJ2d0auvFDiBgF/Event?node-id=0%3A1 makes this task obsolete.

**Comment by kevwalsh** [comment]
I'm going to reopen this for the work in PR #7305, to keep #7305 separate from #6057
