### ISSUE TITLE
Character limits for events description fields

### ISSUE THREAD

**Issue by rachel-kauff** [department-of-veterans-affairs/va.gov-cms#2461]
## Description
Currently a person can add seemly unlimited amounts of text to the `Full event description` and the `Additional information about registration` fields. It would be wise to set some kind of limits on this. 

## Acceptance Criteria
* needs grooming

**Comment by jilladams** [comment]
Per Dave Conlon: not clear that this is a problem for veterans using Events, so iceboxed until we learn about cases where it's a veteran-facing issue / concern & can quantify impact for priority.

**Comment by FranECross** [comment]
Close this ticket as obsolete. We'll be addressing character limits in Events v2 in 2024.
