### ISSUE TITLE
Variable timezone for events

### ISSUE THREAD

**Issue by rachel-kauff** [department-of-veterans-affairs/va.gov-cms#2470]
## Status
[2024-04-24] Per Events scrub with Dave Conlon: we need to:
- Repro and confirm modern state with new Events date/time handling
- Collect metrics to understand: are editors editing events to modify timezone?

## Description
Currently the time zone for events defaults to ET. As a user managing content for an event in a timezone other than Eastern, I want the time zone to be managed in a way that makes sense for my use.

Could be:
- Time zone defaults to the zone set in user profile
- Time zone defaults to one established for the VAMC system
- (less desirable) Time zone is set manually in the form
- Possibly: the option to override a default time zone setting

## Acceptance Criteria
- [ ] Repro and confirm modern state with new Events date/time handling
- [ ] Collect metrics to understand: are editors editing events to modify timezone?
- [ ] Notify Fran Cross of results so either additional tickets may be created, or this endeavor ice boxed.

**Comment by jilladams** [comment]
Related: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/7285

**Comment by jilladams** [comment]
Per Events scrub with Dave Conlon: we need to: 
- [ ] Repro and confirm modern state with new Events date/time handling
- [ ] Collect metrics to understand: are editors editing editing events to modify timezone? 

If that workflow demonstrates this is a real problem, let's bump up priority. 
If not, Icebox and we can address it when we plan a future enhancement of Events.

**Comment by FranECross** [comment]
Closing as no op per Dave C.
