### ISSUE TITLE
Implement consistent characters remaining pattern across all forms

### ISSUE THREAD

**Issue by rachel-kauff** [department-of-veterans-affairs/va.gov-cms#2472]
## User Stories

As a user, I'd prefer a consistent experience for text that tells me how many characters I can input into a field.

## Acceptance criteria 

- [ ] Audit character limit fields [@rachel-kauff ]
- [ ] Develop a character limit help text pattern and document in [GDrive Design System directory](https://drive.google.com/drive/folders/1XEw8PZOauwLESDeNlsCV-FCWyznhnfXQ) [@rachel-kauff ]
- [ ] All fields identified in the audit are updated w/ new help text pattern [engineer]

**Comment by davidmpickett** [comment]
Closing as duplicate of #16659
