### ISSUE TITLE
Reduce list thrashing on bulk content export

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#2481]
**Describe the defect**
IF a bulk CMS content export is run.  There is a a lot of thrashing as the list is updated each time a list item is exported.   The list itself is already updated by the bulk export.  It should not need to be updated for each list item exported.

**Expected behavior**
When the bulk CMS Export is run, lists should only be updated once, when the list is exported, not when the list items are exported.

However, on individual (non-bulk export) a list item export should cause the related lists to be updated.

### IMplementation details.
- [ ] When the bulk export is run, a flag gets set that is accessible to  docroot/modules/custom/va_gov_content_export/src/ListDataCompiler.php::updateLists()

- [ ]  remove @todo that references this issue.

**Comment by oksana-c** [comment]
closing due to deprecation of cms export
