### ISSUE TITLE
Define product team satisfaction metric(s)

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#2482]
## AC

- [x] meet with the Insights & Analytics(Joanne) and Platform experience (James, Naomi) teams to gain insight on current survey practices
- [x] identify metrics and questions for the CMS team "Product team support" survey
- [x] define survey structure/content and distribution/outreach method + cadence
- [x] schedule first survey

**Comment by kevwalsh** [comment]
See Slack thread https://dsva.slack.com/archives/CBU0KDSB1/p1596044554276100

**Comment by kevwalsh** [comment]
And VSP Analytics team request https://github.com/department-of-veterans-affairs/va.gov-team/issues/11816

**Comment by oksana-c** [comment]
next steps:
- [ ] compile a list of hypothetical survey questions
- [ ] meet with James Chasia and Naomi Marcussen to discuss
