### ISSUE TITLE
Synthesize Q3 product team satisfaction survey responses

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#2484]
## Acceptance criteria

- [ ] Synthesis of product team satisfaction survey responses is performed
- [ ] Findings/recommendations shared w/ the team
- [ ] Results posted in github

**Comment by daddison48** [comment]
@nickbloom I see this is sitting in To Do. Has this been worked?

**Comment by nickbloom** [comment]
Results: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/research/product-user-survey/VFS-CMS%20Product%20Collaboration%20Survey%20Results%20Q3%202020.pdf
