### ISSUE TITLE
[LC] Define Table editorial experience for LC

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#2487]
## ACs

- [x] editorial experience expectations are discussed considering that the Table editorial experience is shared between many content types and products
   - [x] character limit for table cells
   - [x] limit table row/columns
   - [x] HTML in table cells
- [x] follow up stories exist in backlog

**Comment by jenniferlee-dsva** [comment]
A couple clarifications to the AC from our team Tuesday call: 

- character limit for table cells `--> I don't think we covered this at all and it's not something I've requested. What is the current state of table cells character limit for tables used in the benefit hubs?  If there isn't a limit, I'm not sure we should create a limit for LC. `

- limit table ~row/~columns  `--> we confirmed we will use Jennifer Strickland's recommended 12 columns as the maximum. we will not have row limit per current table component. `

- HTML in table cells `--> we confirmed that yes, we would enable basic HTML as we do today in tables (e.g., bolding, ital, hyperlinking, basic formatting like para/line breaks and bullet lists) `

The one thing we discussed on last week's call with larger Interested Committee of Tables People that's missing in the above AC: 
- enabling row and column headers to be sticky ` --> Is that a pure FE thing or something also needing CMS AX? If there's one enhancement that would be helpful, it would be this. What would the CMS LOE on this be if we were to do it for 1.0/1.1 ?`

**Comment by oksana-c** [comment]
@jenniferlee-dsva 

> character limit for table cells

currently there's no limit for characters within cells and we'll keep it that way

> limit table ~row/~columns 

this is a larger effort that we'll be addressing in MVP 1.1 - here's related story #2933 

> HTML in table cells

basic HTML is allowed in cells already. There's a related story #2934 - to improve validation/post-processing of content w/ HTML tags thats entered into table cells. It's not critical to address atm because content in tables is still managed primarily by expert editors on the PW team.

> mobile responsiveness

table markup and responsive styling is a Front-end scope.

please let me know if I can clarify anything.

**Comment by oksana-c** [comment]
table features included in LC MVP1.0 are clarified and follow up stories added to [Table AX](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/2932) epic .

Table component will be added as a part of Learning Center Detail page content type #2895

**Comment by jenniferlee-dsva** [comment]
Thx @oksana-c - this make sense, and I also just got confirmation that mobile responsiveness in tables are still in flight as a global design issue. So we won't tackle that for LC mvp, we'll implement the FE once the design system folks have resolved it.
