### ISSUE TITLE
[LC] Related information implementation

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#2489]
## Description

Related information component design is currently evolving and will differ from what's depicted in [LC template MURAL](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1588167553516/2773c854e8ff3a725a5e3ee03272b78e8519f78b).

Related info component will be broken down into two structural parts:
* VA Benefit Hubs (hub teasers)
* Related information (custom links - Drupal or external pages can be referenced)

## Acceptance criteria

- [x] "VA Benefit Hubs" and "Related links" fields should be added to the following content types: Q&A, FAQ - multiple Q&As, Checklist, Step-by-Step, Media list - Images, Media list - Videos.

### VA Benefit Hubs field

- [x] entity reference field in which only "Benefits Hub Landing Page" content type can be referenced. Form widget "Entity Browser - Table". New view should be created instead of using the existing `/admin/structure/views/view/benefits_hub_list`, since Entity Browser field widget will display the full title of the hub including `VA` prefix and we need parity between selection and display UI.
      -  Spec: `field_lc_benefit_hubs` | label "VA Benefit Hubs" | cardinality - max 3
- [x] referenced Hubs can be reordered via drag and drop
- [x] default Hub is always "VA health care"

### Related links field

- [x] entity reference revisions field to "Link teaser" paragraph, to allow for addition of internal/external links. Spec: `field_related_links` | label "Related links" | cardinality - multiple, max 5

### Form display

- [x] Both new fields are displayed at the bottom of the form above Editorial Workflow field group. "VA Benefit Hubs" fields is displayed above "Related links" field. No field group needed around new fields.

### other ACs

- [x] node display settings are configured for each content type: ensure that fields are displayed in correct order. Both new fields are at the bottom of the page.
- [x] spec tool is updated

**Comment by kaise-lafrai** [comment]
@oksana-c Is this a good ticket to get started with?

**Comment by kaise-lafrai** [comment]
Browse hubs but be able to reorder, no editing, just remove and add. 

Related links: Remove Characters used. Keep characters remaining.

**Comment by oksana-c** [comment]
@kaise-lafrai , I updated the ACs based on the check-in w/ PW team and after exploring WIP widgets/fields in #2835 . Please review the diff .

Main difference is field machine name and label for related benefits + using a new view display for entity browser that shows `VA` prefix for all hubs to have parity in UI once hubs are selected.

I noticed a bug in contrib module `entity_browser` to where it doesn't provide field cardinality validation when more than three options are selected and inserted. I'm opening a separate issue.

**Comment by kaise-lafrai** [comment]
@oksana-c I am having trouble finding your changes here https://github.com/department-of-veterans-affairs/va.gov-cms/issues/2835. I only see the one commit I made.

**Comment by oksana-c** [comment]
@kaise-lafrai by diff, I meant the diff in ACs. Here's how
<img width="518" alt="Screen Shot 2020-09-03 at 9 08 53 AM" src="https://user-images.githubusercontent.com/16477724/92133011-1f701200-edc5-11ea-9b0c-be29445b708d.png">

**Comment by kaise-lafrai** [comment]
@oksana-c Got it thanks.

**Comment by kaise-lafrai** [comment]
@oksana-c field_benefit_categories is already used machine name. Do you have another preference for machine name?

**Comment by kaise-lafrai** [comment]
Ready for review.
