### ISSUE TITLE
[LC] Step-by-step component header field

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#2490]
## Acceptance Criteria
- [x] optional `field_section_header` is added to `step_by_step` paragraph, above `field_step`
- [x] spec tool is updated

**Comment by kaise-lafrai** [comment]
@oksana-c Are we sure we want to add the optional field_section_header to step_by_step paragraph, above field_step? Shouldn't we add the optional field_section_header in the step paragraph component above field_wysiwyg?

**Comment by oksana-c** [comment]
@kaise-lafrai , great feedback and question. Here's a screenshot w/ updated AC

<img width="1029" alt="Screen Shot 2020-08-04 at 12 10 33 PM" src="https://user-images.githubusercontent.com/16477724/89329302-dc970f00-d64b-11ea-92f5-26cca5ed07fe.png">

**Comment by kaise-lafrai** [comment]
@oksana-c In the screenshot that I provided, there is a link in the first step header. The field_section_header located on the step might not work in this case. I am thinking we need a new wysiwyg field called field_section_header_wysiwyg. What do you think?

**Comment by oksana-c** [comment]
yes @kaise-lafrai you are correct. keep the header out of the `step` component per original AC, and only attach to the parent `step-by-step`. thank you for coming back to this.
