### ISSUE TITLE
Remove old blobby content model for Facility health services

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#2509]
The old facility health service data is deprecated by the hardened content model. 

## ACs
- [x] check to see if field_body is still queried in `content-build`, for the facility health service query
- [x] if it is, remove it from the FE query
- [ ] once it is removed, remove field_body from facilty health service content type (`admin/structure/types/manage/health_care_local_health_service/fields/node.health_care_local_health_service.field_body/delete`)

**Comment by kevwalsh** [comment]
This is dependent on the removal of the query in `content-build` repo.

**Comment by swirtSJW** [comment]
@netboss  Please clarify in this issue what you did or did not find in the content-build repo.   I see the ACs checked off, but I don't know what you found.

**Comment by netboss** [comment]
> @netboss Please clarify in this issue what you did or did not find in the content-build repo. I see the ACs checked off, but I don't know what you found.

@swirtSJW 
It seems that `fieldBody` isn't used in the FE (content-build) for the `health_care_local_health_service` content type. At least not in this template `health_care_local_health_service.drupal.liquid`. So I removed the `field_body` field from the "Facility health service" content type in CMS.

**Comment by swirtSJW** [comment]
>At least not in this template health_care_local_health_service.drupal.liquid.

So it  is also not used in the query?  The query will blow up and break the build if a field still exists in the query, even if it is not used  in the template.

**Comment by swirtSJW** [comment]
It will blow up like this   
![image](https://user-images.githubusercontent.com/5752113/157759812-b28825a4-8336-45a0-9d7e-fbcacc38b098.png)


It is not enough to check the templates, you have to check the query too.   GraphQL Fails catastrophically if you ask for a field that does not exist on the content type

**Comment by swirtSJW** [comment]
The details are in the AC.
![image](https://user-images.githubusercontent.com/5752113/157760100-ed4c3b61-4234-496d-89d4-3eaa6c358fd9.png)

**Comment by netboss** [comment]
> The details are in the AC. ![image](https://user-images.githubusercontent.com/5752113/157760100-ed4c3b61-4234-496d-89d4-3eaa6c358fd9.png)

@swirtSJW 
That was my original question in this Slack thread: https://dsva.slack.com/archives/CT4GZBM8F/p1646860791074689

I don't know how to check if the `field_body` is still been used in the FE query. How can I check that?

**Comment by swirtSJW** [comment]
Same answer, search for it with your IDE or in Github.   There is no magic.  It is all in code ;)
