### ISSUE TITLE
Lo-fi prototype of the CMS Help Center homepage

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#2518]
AC

- [x] lo-fi prototype for the CMS Help Center homepage to kick off engineering back log refinement
- [ ] Review for technical feasibility, especially for admin menu design

**Comment by kevwalsh** [comment]
@nickbloom can you add the link to the prototype here?

**Comment by jordanamello** [comment]
@kevwalsh https://xd.adobe.com/view/98e6e8b1-f56e-4a83-bc53-ed075da3fd2d-cdb5/
