### ISSUE TITLE
Establish a baseline that measures the effectiveness of trainings

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#2521]
Q3 OKR: Establish a baseline that measures the effectiveness of trainings

AC
- [ ] Survey questions are designed w/ collab from design pod and is ready to be implemented
- [ ] Mechanism for measuring effectiveness has been designed and prepared in advance of next set of trainings.

**Comment by daddison48** [comment]
https://docs.google.com/document/d/1e5HiaofiwErfH5GKxa0uWb8pK1q5ddfxluOc-lSOC_8/edit
