### ISSUE TITLE
Design iteration on top level admin toolbar menu

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#2525]
## AC
- [x] change color from red to some VA blue (primary-darkest, #112e51, $color-primary-darkest)
   - [x] change color on lower environments from blue to something else. e.g. yellow / orange  
   - [x] account for active state for menu links

## Ideas for AC adjustments

Implemented in #2747
- [x] post only the version number on the top right
- [x] remove the environment switch menu - it's rarely used

Not implemented in #2747: 
- [ ] use icon and show version on hover
- [ ]  move version/env menu from the top level to  "Administration > Reports > Environment" info menu 
- [ ] consider standardizing how this info is exposed on different environments (dev, stage, prod, devshop)
- [ ] Only `administrator` users can see the git branch / environment info on prod

## Implementation (TBD)
* toolbar color change is hardcoded in settings.*.php file(s)
* git branch is controlled in hook_rebuild() in va_gov_backend

**Comment by oksana-c** [comment]
@kevwalsh here's the snippet I screenshared to add an element to the admin toolbar

you'll likely want to tweak some values here and there

```
/**
 * Implements hook_toolbar().
 *
 * Defines Branch component in Admin Toolbar Menu.
 */
function va_gov_backend_toolbar() {
  $items = [];
  $items['branch'] = [
    '#cache' => [
      'contexts' => ['user.permissions'],
    ],
    '#type' => 'toolbar_item',
    'tab' => [
      '#type' => 'html_tag',
      '#tag' => 'div',
      '#value' => \Drupal::state()->get("environment_indicator.current_release", $indicator);  <<--- you may need to tweak things here.
      '#attributes' => [
        'title' => 'TBD',
        'class' => ['toolbar-icon', 'toolbar-icon-branch'],
      ],
    ],
    '#wrapper_attributes' => [
      'class' => ['toolbar-tab', 'branch-toolbar-tab'],
    ],
    '#weight' => 100,
  ];

  return $items;
}

```

**Comment by kevwalsh** [comment]
![Toolbar_menu_design_-_Google_Docs.jpg](https://images.zenhubusercontent.com/5d6e57ad330f64311395f08b/a0c20ce7-0bbe-4838-8a30-0681a575dce2)

Design iteration from Sprint 13.

![kevin_walsh___VA_gov_CMS.jpg](https://images.zenhubusercontent.com/5d6e57ad330f64311395f08b/22001b35-5ef7-4521-bc23-b5331696367d)

**Comment by swirtSJW** [comment]
Looks great over all.  
![image](https://user-images.githubusercontent.com/5752113/91587137-5d33ed00-e924-11ea-9c95-a3e07ad8d048.png)
My crappy eyes will never catch the difference between lando and prod... and that is dangerous.


I'd even be happy with the current electric green on lando.
