### ISSUE TITLE
[cms-test] Create workflow to spin up/down cms-test infrastructure when not in use to save $$$

### ISSUE THREAD

**Issue by ElijahLynn** [department-of-veterans-affairs/va.gov-cms#2531]
## Background

As a devops engineer, I wish to easily turn the `cms-test` environments off when not being actively used, in order to be more cost-efficient (TODO: Estimate the cost/month). (The cms-test environments exactly duplicate the main environments)

## Acceptance Criteria

- [ ] Workflow that can be run by any devops or application engineer
- [ ] All running infrastructure is terminated or suspended
- [ ] Process for starting and stopping infrastructure has been documented

## Implementation
- Spin down or terminate DEV/STAGING/PROD cms-test EC2 instances
- Spin down RDS (not terminate, takes way to long to rebuild)
- check S3 bucket usage, probably not significant
- memcached nodes

**Comment by acrollet** [comment]
This should probably be split into multiple issues when it comes time for implementation.

**Comment by mchelen-gov** [comment]
please provide estimate of current costs before proceeding

**Comment by TheBoatyMcBoatFace** [comment]
No longer applicable.
