### ISSUE TITLE
Config does not always import during build

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#2532]
**Describe the defect**
There seems to be a CI environment config import issue, possibly composer related. On a few environments (always on "demo" project, FWIW, i’ve noticed that config did not import successfully during build. When trying to do it manually via UI, i see 

```
The configuration cannot be imported because it failed validation for the following reasons:
Unable to install the media_entity_generic module since it does not exist.
```
http://facilityhealthservices.demo.ci.cms.va.gov/admin/config/development/configuration

**To Reproduce**
1. Go to http://facilityhealthservices.demo.ci.cms.va.gov/admin/config/development/configuration
2. Click on "Import all" at the bottom.

**Expected behavior**
The config should import successfully during build. 

**Screenshots**

![Synchronize___VA_gov_CMS](https://user-images.githubusercontent.com/643678/89035986-dfbb9380-d309-11ea-8979-f288983695b5.jpg)

**Comment by oksana-c** [comment]
this will likely be resolved during the move to Tugboat. If the issue keeps popping up, we'll revisit.
