### ISSUE TITLE
Establish a #cms-content-admin channel (?)

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#2536]
## Description

Content admins (mostly, Public Websites team members) may need a channel for support and content admin related release notes. For example, they are able to see all our MVP content model work, and we could let them know about it there.

**Comment by sandyisland1** [comment]
@kevwalsh @rachel-kauff : is this for the public website team?

**Comment by oksana-c** [comment]
Our communication of new features that are specific to the power-user group is normally centered around new product development and takes place in product-specific public channels. 

@kevwalsh , please reopen if you think a new channel is still needed.
