### ISSUE TITLE
Bullets not appearing in wysiwyg editor

### ISSUE THREAD

**Issue by rachel-kauff** [department-of-veterans-affairs/va.gov-cms#2538]
**Describe the defect**
Bullets don't appear in wysiwyg content block.

**To Reproduce**
1. Edit a /help page with a bulleted formatting, such as /node/6692
2. Edit the wysiwyg
3. Observe that the bullet formatting that appears on View doesn't show up in the wysiwyg. The functionality seems to be there, it's just not visually displaying the bullets in the text box.

**Expected behavior**
When I apply bullet formatting to text in a wysiwyg, I expect to see bullet points.

**Screenshots**
(https://images.zenhubusercontent.com/5e399cf5446c5b4ca0e31e42/910743cb-e51b-41d4-a3ed-4dd128154378)![Screen Shot 2020-07-30 at 2.24.18 PM.png](https://images.zenhubusercontent.com/5e399cf5446c5b4ca0e31e42/fa61ad78-c44e-4618-8b4a-7049cb71d9ba)

**Kev and Clarence's additional research**

* It seems like `<ol>` appears as bulleted lists in CKeditor, but correctly as ordered lists on Preview. 
* `<ul>` doesn't appear at all in CKeditor. 

I think this regression that happened during the proofing page CSS work on benefits detail pages.

**Comment by cmaeng** [comment]
@cmaeng to notify Ryan Stubblebine once this has been addressed.
