### ISSUE TITLE
Get CMS Export (Tome Sync) working with Drush 8

### ISSUE THREAD

**Issue by ElijahLynn** [department-of-veterans-affairs/va.gov-cms#2541]
This is a intermediate workaround for the more complex #2117 (Drush 10) story. 

AC:
- Get Tome Sync working with Drush 8 so that we can do Automated CMS Exports right after we deploy content model/schema changes and have the CMS Export match what is in the DB.

**Comment by indytechcook** [comment]
I tested this on stage and it ran successfully

**Comment by ElijahLynn** [comment]
Nice pragmatic work on this Neil!
