### ISSUE TITLE
[cms-test] Disable jobs by default so they don't run and so they don't notify Slack

### ISSUE THREAD

**Issue by ElijahLynn** [department-of-veterans-affairs/va.gov-cms#2543]
AC:
- All CMS-TEST jobs are disabled by default when Jenkins Seedjob is run

Notes:
This needs to be done after the loop in the seed job.

**Comment by indytechcook** [comment]
PR: https://github.com/department-of-veterans-affairs/devops/pull/7387

**Comment by indytechcook** [comment]
The code was merged in yesterday and the job are disabled.
