### ISSUE TITLE
[tracking] Dependabot failing on timeout

### ISSUE THREAD

**Issue by ElijahLynn** [department-of-veterans-affairs/va.gov-cms#2560]
Upstream tracking here > https://github.com/dependabot/dependabot-core/issues/2416

**Comment by acrollet** [comment]
There has been some movement on the upstream issue: https://github.com/dependabot/dependabot-core/issues/2416#issuecomment-759480528

**Comment by acrollet** [comment]
Dependabot has been reliable since #3303, closing this.
