### ISSUE TITLE
[LC] Facilitate devshop environment for FE development

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#2561]
## Description

The process of using LC Demo environment on DevShop:
1. PW team adds LC content on Prod in DRAFT state
1. PW team rebuilds DevShop environment every time Prod DB and codebase changes need to be brought in into DevShop environment
   1. PW team publishes LC Draft content in devshop env after it is rebuilt and rebuilds front-end

## Acceptance Criteria
- [x] PW team creates DRAFT content on production (Q&A, FAQs - multiple Q&As, Step-by-step, checklist)
- [x] CMS team creates devshop environment to be used for FE development
- [x] PW team takes over the ownership of the LC demo environment once it is created w/ support from the CMS team if any issues surface

**Comment by cmaeng** [comment]
Dependent on Jen and Randi entering content. We will then need to handoff to Nick and Kelson once our work is complete.

**Comment by jenniferlee-dsva** [comment]
referencing related content ticket on PW board: [#12066](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/12066)

**Comment by oksana-c** [comment]
[Demo environment](http://learningcenter.demo.ci.cms.va.gov/) is ready. @RLHecht is taking over environment / content management.
