### ISSUE TITLE
Caption field not available for adding new images

### ISSUE THREAD

**Issue by rachel-kauff** [department-of-veterans-affairs/va.gov-cms#2571]
**Describe the defect**
When I try to add a caption to an image I'm uploading to the media library, I don't see a field that will help me do that. I know the caption field exists, because I can see captions on the front end for images such as this: https://staging.va.gov/pittsburgh-health-care/stories/everything-usually-comes-back-to-respect-for-lgbt-veteran-care/ 

See this thread on caption issue from the support channel: https://dsva.slack.com/archives/CDHBKAL9W/p1596648672071700

**To Reproduce**
1. Go to /media/add/image
2. Observe the lack of caption field.

![Screen Shot 2020-08-05 at 1.36.51 PM.png](https://images.zenhubusercontent.com/5e399cf5446c5b4ca0e31e42/675f0696-b789-49c7-9daf-c89128ca1b81)

Our editors are currently unable to do what they need to do because of this issue.

**Additional context**

**Comment by cmaeng** [comment]
Needs to pivot to add caption field (detail pages).

**Comment by ethanteague** [comment]
This will require @rachel-kauff 's input

cc: @kevwalsh @cmaeng @oksana-c
