### ISSUE TITLE
Develop plan for collecting facility health service content 

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#2574]
## Problem statement

We don't yet know how to collect data to populate the new structured content for facility health services. 

## Description

Collaborate with Facilities / VAMC Upgrade teams to organize a spreadsheet that will support structured data/blob migration of service locations.

## Implementation

- [ ] Set up a meeting with @SgardnerPMP @mmiddaugh @swirtSJW @kevwalsh @ltrombley  to collaborate to prototype this process
- [ ] Then iterate on it.  

- [ ] Understand current state of data
 

## Constraints 

- [ ] VA network

## Acceptance Criteria
* recommend the format for spreadsheet values
* communicate the format and process to VAMC Upgrade team
* some level of support to answer questions

**Comment by kevwalsh** [comment]
This plan was developed with [this Whimsical ](https://whimsical.com/ACwcwMy4dwcWvKxBybVW12@2Ux7TurymMhKkLF5wkw1)and iterated on throughout the sprint.
