### ISSUE TITLE
Fix ANSI color code log output on BRD deploys for yaml-tasks

### ISSUE THREAD

**Issue by ElijahLynn** [department-of-veterans-affairs/va.gov-cms#2575]
Jenkins cannot parse the ANSI codes for Ansible tasks while being run from within yaml-tests which is run from Ansible which is run from Jenkins. We do have ANSI color support enabled and working for both Jenkins and Ansible and yaml-tasks also has support for this enabled by default but we had disabled it with the option `--no-ansi` a while ago in our post-deploy-tasks.yml file. 

![image](https://user-images.githubusercontent.com/1504756/89466627-05d99d00-d729-11ea-9075-c016f51b7825.png)

![image](https://user-images.githubusercontent.com/1504756/89466613-0114e900-d729-11ea-8c77-840add200986.png)

AC:
* ANSI color codes are displayed as colors, not strings

**Comment by ElijahLynn** [comment]
I think this is all related to Ansible not bubbling up ANSI codes correctly. Because Ansible itself is coloring output correctly. Or maybe it has to do with the fact that ultimately Jenkins is doing the ANSI color rendering.

**Comment by ElijahLynn** [comment]
K, so we run `composer yaml-tests --no-ansi`, which solves one of the ANSI issues we had previously BUT, yaml-tests runs our tests.yml file which runs our test suites AND here is the thing, 3 of these test suites include ANSI output, which is useful for local CLI running and also is rendered correctly in DevShop. 

But Jenkins does not work well with this so we can either fix the ANSI Color Jenkins plugin to render sub-nested ANSI output (maybe contact the maintainer). Or, we could disable the ANSI stuff on BRD by running slightly different commands on Jenkins runs:
1. Composer
Existing: `composer install --dev --no-interaction --no-progress --ansi`
New: `composer install --dev --no-interaction --no-progress --no-ansi`
1. PHPUnit
Existing: `phpunit --exclude-group disabled tests/phpunit --colors=always`
New: `phpunit --exclude-group disabled tests/phpunit` (or is `--colors=never` an option?)
1. Behat
Existing: `behat --colors`
New: `behat`

The challenge here is we have one file that runs everywhere and really need to keep it that way so we don't have drift.

**Comment by olivereri** [comment]
Opened issue with Ansicolor-plugin for Jenkins:
https://github.com/jenkinsci/ansicolor-plugin/issues/206

We've discovered through testing the the Ansible Callback Plugin `yaml` appears to be stripping the escape characters used for ansicolor codes. Switching the callback plugin to `default` the escape chars aren't being stripped. However, the ansi color escape codes are there but not being rendered by Ansicolor-plugin.
