### ISSUE TITLE
Research what the default time zone should be for different date fields

### ISSUE THREAD

**Issue by rachel-kauff** [department-of-veterans-affairs/va.gov-cms#2578]
Use 
- user time zone?
- event list time zone?
- business unit (eg VAMC system or Office) time zone?

**Comment by rachel-kauff** [comment]
From Stan in VAMC upgrade: " per discussion with Dave Conlon, strong Consideration that "Events"  be updated to reflect "Local time",  due to areas like Arizona and Indiana where we have different time zones dependent on Daylight savings.   "Local Time" may be the best catch all.  Thank you,"

**Comment by kevwalsh** [comment]
After a conversation with @davidconlon today, this is getting deprioritized for now.

**Comment by oksana-c** [comment]
per @rachel-kauff , this should be prioritized before VISN19 users onboard.

Implementation to consider: enable users to set their time zone at the time of profile creation. We'll need to think about the current flow of profile creation and potentially show a new user a message on first login about setting their timezone. 

Additionally: include a step of setting a timezone in User Guides and training materials.

**Comment by kevwalsh** [comment]
Summary 

![Create_Event___VA_gov_CMS](https://user-images.githubusercontent.com/643678/91739620-3245d500-eb80-11ea-8471-68b144b96c1f.jpg)

## tzfield

Allows a default value on a field level, no currentl


## datetime_range_timezone

For event time zone selection, we're investigating https://www.drupal.org/project/datetime_range_timezone, which has this UI: 

![image](https://user-images.githubusercontent.com/643678/91733759-fc045780-eb77-11ea-8f4d-02245a18ab83.png)

Doesn't seem to have any "default time zone" behavior OOTB, unfortunately. When i go to create an event with this field, default timezone is Abidjian, and it has this awkward help text: "This should be the timezone you entered the above date in and will also be the timezone in which this event date is displayed

![Create_Event___VA_gov_CMS](https://user-images.githubusercontent.com/643678/91738018-e4c86880-eb7d-11ea-90a1-1d94de3302a7.jpg)
d."

This would require some migration

**Comment by FranECross** [comment]
Closing as a no op; a new ticket will be created if this bubbles up again.
