### ISSUE TITLE
Bulk cms export logs to dblog when completed.

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#2593]
## User Story or Problem Statement

As an engineer it would be nice if the bulk export of content  logged to dblog when it starts and when it ends so that we don't have to ask "Did you run it yet?" in slack.

## Acceptance Criteria
* Log entry appears in dblog that notes that he bulk export has started.
* Log entry appears in dblog that notes that he bulk export has completed.

**Comment by oksana-c** [comment]
closing due to deprecation of cms export
