### ISSUE TITLE
Remove social fields from VAMC facility content type

### ISSUE THREAD

**Issue by rachel-kauff** [department-of-veterans-affairs/va.gov-cms#2632]
## Description
The box that provides social media links at the bottom of each page ("Get updates from VA Pittsburgh health care") is managed at the SYSTEM level, not facility. We need to remove these field to avoid significant confusion for editors.

## Acceptance Criteria
- [ ]  Social media fields are removed from VAMC facility content type
- [ ] spec tool and content model tests are updated
![Screen Shot 2020-08-11 at 11 02 32 AM](https://user-images.githubusercontent.com/41017988/89932485-8c2b2e80-dbc2-11ea-9fe5-e0f03fe40f03.png)

**Comment by kevwalsh** [comment]
Closing this in favour of #2982
