### ISSUE TITLE
Upgrade from Ansible ec2.py inventory to aws_ec2 inventory plugin

### ISSUE THREAD

**Issue by ElijahLynn** [department-of-veterans-affairs/va.gov-cms#2634]
We migrated from ec2.py to aws_ec2 inventory plugin so the cache system is consistent and the META module refresh_inventory worked properly. 

This is a task that is mostly already done as part of https://github.com/department-of-veterans-affairs/va.gov-cms/issues/2494 but needs a formal PR and review process to merge in separately. We still need to do the aws_rds inventory plugin migration too however a bit of a blocker is that the aws_route53 and aws_elasticache inventory plugins don't exist yet.

AC: 
- [ ] Evaluate the need for the aws_route53 plugin
- [ ] Evaluate the need for the aws_elasticache plugin
- [x] Create devops PR with existing work and explain why we need it etc.

**Comment by olivereri** [comment]
We were able to merge this change in without affecting other Applications using BRD. We instead opt to use custom Jenkins deploy jobs to explicitly select and use the new inventory.

https://github.com/department-of-veterans-affairs/devops/pull/7472/files

Still requires an evaluation on the need for Route53 and Elasticache inventories.

**Comment by ElijahLynn** [comment]
Iceboxing this since we are able to use the new aws_ec2 inventory plugin system without affecting other services. And this system is being deprecated so the value isn't as high anymore.
