### ISSUE TITLE
Setup Tugboat trial for evaluation

### ISSUE THREAD

**Issue by cmaeng** [department-of-veterans-affairs/va.gov-cms#2638]

**Comment by indytechcook** [comment]
I'm waiting on a call with tugboat to continue setup.

**Comment by indytechcook** [comment]
I logged https://github.com/department-of-veterans-affairs/github-user-requests/issues/3657 to get tugboat access to the org.

If this approach doesn't work then we have to setup a bot user and user a user token integration.

**Comment by indytechcook** [comment]
The tugboat trail is setup: https://dashboard.tugboat.qa/5f3c015ee565118d47999d5a

tugboat support slack channel can be joined: https://launchpass.com/tugboatqa
document with 1:1 devshop to tugboat: https://docs.google.com/document/d/12ivzu712cA2Rk4hB8dZtxEAtbK3etgDWfUeEhhOhAJk/edit

**Comment by indytechcook** [comment]
I have test running and reporting back to a github PR: https://github.com/department-of-veterans-affairs/va.gov-cms-test/pull/89

**Comment by indytechcook** [comment]
The phpunit failures on tugboat are
* ```POST request is expected to fail with 404 due to incomplete endpoint URL /var/lib/tugboat/tests/phpunit/PostApiQueueTest.php:84```

and

``` ┃ POST request is expected to fail with 404 due to incomplete endpoint URL. ┃ /var/lib/tugboat/tests/phpunit/PostApiQueueTest.php:84```

The `PostApiQueueTest` will fail outside the VA network.  If we have tugboat onsite this will not be an issue.  The test should also be modify to not rely on the external ur.
