### ISSUE TITLE
List upcoming trainings

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#2668]
CMS trainings are currently by assignment by Stan in alignment with content migration. This issue is to address any ad hoc CMS training sessions for content editors that fall outside of the default assignment method.

**Comment by xiongjaneg** [comment]
### Acceptance criteria

- [ ] Prioritize training
- [ ] Define how attendees will be invited/register
- [ ] If Help page is used for registration, post dates

**Comment by xiongjaneg** [comment]
See https://prod.cms.va.gov/help/access-training
