### ISSUE TITLE
tests:phpunit: Test code or tested code did not (only) close its own output buffers

### ISSUE THREAD

**Issue by ElijahLynn** [department-of-veterans-affairs/va.gov-cms#2674]
Seeing this on phpunit runs now, looks like maybe new output with a phpunit upgrade maybe. 

This seems like something in the underlying code that is running `ob_start` (output buffering) and not calling `ob_flush`, we _could_ do that in our test but I don't think that is right. 

Here is a related upstream issue > https://github.com/kenjis/ci-phpunit-test/issues/131

e.g. 

> 
> There were 10 risky tests:                                          
>                                                                     
> 1) tests\phpunit\BulletinQueueTest::testBulletinQueue               
>                                                                     
> Test code or tested code did not (only) close its own output buffers
>

**Comment by acrollet** [comment]
It looks like @indytechcook's commit to phpunit.xml for #2569 fixed this.

Test run with phpunit.xml from [13f0da82a5efb6b0e44d963519ccf0955cfc4ed3](https://github.com/department-of-veterans-affairs/va.gov-cms/commit/13f0da82a5efb6b0e44d963519ccf0955cfc4ed3):

<img width="773" alt="Screen Shot 2020-11-02 at 1 31 36 PM" src="https://user-images.githubusercontent.com/101649/97916440-3624dd80-1d10-11eb-8e01-b9e655d3093a.png">

Test run with phpunit.xml from [25de7089d9af5afae5058af320610934a3782cb3](https://github.com/department-of-veterans-affairs/va.gov-cms/commit/25de7089d9af5afae5058af320610934a3782cb3):

<img width="624" alt="Screen Shot 2020-11-02 at 1 32 45 PM" src="https://user-images.githubusercontent.com/101649/97916481-42a93600-1d10-11eb-880b-2b7e9153256b.png">

**Comment by acrollet** [comment]
@ElijahLynn assigned to you for review/confirmation.

**Comment by ElijahLynn** [comment]
> It looks like @indytechcook's commit to phpunit.xml for #2569 fixed this.

W00t! Thanks both of you!
