### ISSUE TITLE
VAMC system health services migration VISN 4 and 19

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#2676]
- Stan will provide two consolidated CSVs via a github issue by EOD Monday Aug 17
  - System health services for VISN 19
  - Facility health services for VISN 19 (blobby content)
- CMS team will then
  - System services
    - [x] create a PR based on the CSV https://github.com/department-of-veterans-affairs/va.gov-cms/pull/2699
    - [x] Test CSV locally against migration to generator errors
    - [x] PR merged
    - [x] migration run on prod
![image](https://user-images.githubusercontent.com/5752113/92930951-c3366f00-f410-11ea-981d-0c1ea01a213d.png)

------ The following criteria was moved to its own ticket https://github.com/department-of-veterans-affairs/va.gov-cms/issues/2894 ----
  - Facility services
    - [x] CSV received https://dsva.slack.com/archives/CDHBKAL9W/p1599605606042300 9/8 EOD
    - [ ] create a PR based on the CSV
    - [ ] Test CSV locally against migration to generator errors
    - [ ] PR merged
    - [ ] migration run on prod

  - Provide feedback about data 
- VAMC upgrade team cleans up data, if necessary
- Rinse and repeat
- When migration succeeds and PR is merged, CMS team will run migration on prod and let VAMC upgrade team know.

**Comment by swirtSJW** [comment]
This has been run on prod
![image](https://user-images.githubusercontent.com/5752113/92932099-6e93f380-f412-11ea-91ad-17ad3584e4dc.png)
