### ISSUE TITLE
[LC] Pull YouTube metadata for Video entities

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#2677]
## Description

* authors should not have to enter data that already exists on YouTube
* consider maintaining a list of allowed user. E.g. can embed videos only from trusted VA.gov Youtube user.
* potential contrib to DO

## Questions

* should we migrate the whole library from VA YouTube channel? _[This is **not** the business ask.]_
* should users be able to add videos only from the list of authorized YouTube channels (e.g. VA, DoD) or any author on YouTube
* should the title of the video be overriden by information in YouTube? _[For LC, the requirement is to use the source info from YouTube - use the YouTube video title, description, etc. This way, authors are not creating different titles and descriptions for the same videos, just because it is being displayed in a different place.]_
* how often does data change on YouTube - frequency of sync _[not often, many youtube VA videos are uploaded once and not updated unless something happens like the name of the program changes]_

## Acceptance Criteria

- [ ] discovery around final reqs
- [ ] integration w/ YouTube to fetch video entity data
- [ ] youTube data is synced to video entities every 24hrs or so

**Comment by acrollet** [comment]
ref: https://www.drupal.org/project/video_embed_field/issues/3001487

**Comment by jenniferlee-dsva** [comment]
Per today's CMS weekly check in: 
- Video meta data should be pulled in via CMS, not FE. 
- Technical work can be done for LC post 1.1. 

@kevwalsh @cmaeng

**Comment by oksana-c** [comment]
content team had identified ~2 video content pieces that are Veteran-facing.
Identified Video content is expected to be published in Q1 2021.
YouTube integration will happen after MVP 1.1

MVP 1.1:
* videos can be added to the template and include only title, youtube link. 

MVP 1.2:
* sync metadata from YouTube

**Comment by FranECross** [comment]
Ticket can be reopened/recreated if needed in the future. All other tickets on associated epic are completed.
