### ISSUE TITLE
Redirect saving is broken

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#2681]
**Describe the defect**
If you edit a naturally occurring redirect in the UI, it goes from looking like this before save
![image](https://user-images.githubusercontent.com/5752113/90297138-8bf99000-de5b-11ea-92f3-954c2c4cce60.png)

To this after saving:
![image](https://user-images.githubusercontent.com/5752113/90297213-c8c58700-de5b-11ea-90c1-fe17e9da6d99.png)

There was some "custom" logic and handling that was added in this contrib module https://www.drupal.org/project/redirect_options that is likely at play here.   We should revisit what this module is doing and why.
Redirect type and Match Type  
![image](https://user-images.githubusercontent.com/5752113/90297396-50ab9100-de5c-11ea-9596-c769692ee2c9.png)
are added by this module and the purpose is not clear.

Also following the save, the redirect does not actually work.

This defect is a blocker to implementing out proposed redirect strategy with the front end.
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/2297

**Expected behavior**
When editing a redirect,and saving it should not say "Server" in the destination.  It should show the path like it did before editing.

An edited redirect should actually redirect.

**Comment by ndouglas** [comment]
I haven't had any luck reproducing the issue with redirects working.  They continue to work for me, across cache clears, etc.  It seems like the title change behavior was a workaround for an issue with the GraphQL export, so I'm digging into that to understand it better.  I've opened [an issue](https://www.drupal.org/project/redirect_options/issues/3189372) for a (probably unrelated) warning displayed on save.

**Comment by ndouglas** [comment]
Welcome back, @ethanteague !  

>It seems like the title change behavior was a workaround for an issue with the GraphQL export, so I'm digging into that to understand it better.

I've poked into this and `diff`ed a CMS export, and there _are_ changes:

<img width="940" alt="Screen Shot 2021-01-11 at 10 37 52 AM" src="https://user-images.githubusercontent.com/1318579/104202589-1c330580-53f9-11eb-81ff-cdf367eeaee3.png">

But I'm wondering how critical they are -- I've poked into the frontend code and didn't find any that seemed to deal with the internals of redirects, switched on whether they're Template or Server redirects, etc.  Do you remember any of this?

As I see it, my options are to:

1) simply remove the line of code that changes the title of the redirect, which might have unexpected effects
2) edit the view [as you suggest on the module homepage](https://www.drupal.org/project/redirect_options), which is safer but would just result in the codebase accumulating more strangeness if there's no longer any reason for the underlying change

Thanks!

**Comment by ethanteague** [comment]
@ndouglas I didn't work on any of the transformer stuff for redirects, but I think you are going to have to do #2, and then update the transformer.

**Comment by ndouglas** [comment]
Ah, okay, thanks ❤️
