### ISSUE TITLE
Edit content type names in config for capitalization

### ISSUE THREAD

**Issue by rachel-kauff** [department-of-veterans-affairs/va.gov-cms#2698]
Content type names should be considered proper nouns. Need to update the UI to reduce possible confusion for users.

1. Rachel makes updates in config
2. Ethan or someone available saves them from being overwritten

AC
- [ ] Content type names reflect proper noun capitalization

**Comment by swirtSJW** [comment]
Closing this as content types have been created and renamed since this was created.
