### ISSUE TITLE
[LC] MVP product dashboard implementation

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#2706]
## Acceptance Criteria

- [x] R&S content view /admin/content/learning-center is renamed to "Resources and support" + url alias changes to match the new name
- [x] MVP dashboard contain a view of landing pages (filtered by product) and content (already exists)
   - [x] content view should include all R&S content types: Checklist, Step by step, Media list- Images, Media list - Videos, Q&A, FAQ, Learning center detail page
- [x] R&S dashboard is available to the following roles: Content Creator - Resources and support
- [x] Assign "content creator - Resources and support" role to the following users on production: Jen, Randi, Selina, Beth

dashboard MVP wireframe + specs can be found on the attached screenshot

![Product and support MVP dashboard(2)](https://user-images.githubusercontent.com/16477724/96920976-21705c00-146b-11eb-8a74-c8e4dc00f7fc.jpeg)

**Comment by kaise-lafrai** [comment]
@oksana-c what is the name of the view for this?: 

> MVP dashboard contain a view of landing pages (filtered by product) and content (already exists)

**Comment by oksana-c** [comment]
This sprint goal was not complete due to prioritized critical defect #3205 and capacity reduced to take care of family emergency.
Moving this Sprint 17 goal to Sprint 18 - Product Support.

**Comment by kaise-lafrai** [comment]
This is ready for review: https://github.com/department-of-veterans-affairs/va.gov-cms/pull/3282
