### ISSUE TITLE
Create behavioral test to confirm that node reverts work

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#2716]
## User Story or Problem Statement

As an editor, I need to be able to revert to a previous revision of a given piece of content.

## Acceptance Criteria
- [ ] behavioral tests confirm that reverting to an earlier node reversion via the Drupal UI functions correctly

**Comment by jefflbrauer** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VAgov-CMS-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/2716?planning-poker) with ZenHub @cweagans

**Comment by EWashb** [comment]
We implemented a revision log within the past year. I think we are ok to close this.
