### ISSUE TITLE
Anchor links behavior hides page headings

### ISSUE THREAD

**Issue by rachel-kauff** [department-of-veterans-affairs/va.gov-cms#2729]
When I add anchor links to user guides, it doesn’t account for the amount of space the admin toolbar takes up on the page, so when you click on the link it covers the heading that it was supposed to jump to. That's a confusing experience because it disorients users on the page.

This is an issue for users because I've structured user guides with anchor links to help users navigate lengthy or content-heavy pages, and integrated anchor links into the strategy for getting users to the right information. Howie plans to use the anchored links to user guides to provide help desk answers.

![Screen Shot 2020-08-20 at 8.27.29 AM.png](https://images.zenhubusercontent.com/5e399cf5446c5b4ca0e31e42/4cb5ebdf-87fd-4799-a7cb-1e6ed6c1bf0c)![Screen Shot 2020-08-20 at 8.27.35 AM.png](https://images.zenhubusercontent.com/5e399cf5446c5b4ca0e31e42/d19ae333-95a6-4ec0-b7fb-9cc36ac8b4f7) 

## Initial research

There's a rabbit hole of drupal issues related to something similar, starting with this 2009 thread. https://www.drupal.org/project/drupal/issues/546126

**Comment by ElijahLynn** [comment]
Slack discussion here https://dsva.slack.com/archives/CT4GZBM8F/p1597938169005900 [internal].

**Comment by kevwalsh** [comment]
There's a rabbit hole of drupal issues related to something similar, starting with this 2009 thread. https://www.drupal.org/project/drupal/issues/546126

**Comment by swirtSJW** [comment]
Yeesh yah this is a bit of a mess. because it is largely handled by the browser which has not idea the top of the window is blocked from view.  Maybe a js behaviour that if a location has a # in it, it backscrolls the window 50px or whatever the thickness of those two menus are.

**Comment by acrollet** [comment]
@rachel-kauff this will get deployed tomorrow :-)
