### ISSUE TITLE
Make the button creation experience more intuitive

### ISSUE THREAD

**Issue by rachel-kauff** [department-of-veterans-affairs/va.gov-cms#2753]
**Describe the defect**
In order to add a button, i first need to add a link, then _style_ it as a button.  it's not intuitive. 

**To Reproduce**
1. Go to a CMS help page (I experienced this on https://prod.cms.va.gov/help/contact-help-desk
2. Edit a WYSIWYG
3. Try to style something as a button
4. Jump to somewhere else in the text, return to the styles menu to see if your options change.

**Expected behavior**
I expect to always have the same options in the styles menu, including default, primary, and secondary link buttons.

**Screenshots**
![Screen Shot 2020-08-24 at 9.59.00 AM.png](https://images.zenhubusercontent.com/5e399cf5446c5b4ca0e31e42/5a2b07e1-9016-499c-9680-f65a803647b7)![Screen Shot 2020-08-24 at 9.59.06 AM.png](https://images.zenhubusercontent.com/5e399cf5446c5b4ca0e31e42/54ebccf7-fe05-4656-b07a-2ef78b1eb478)![Screen Shot 2020-08-24 at 9.59.16 AM.png](https://images.zenhubusercontent.com/5e399cf5446c5b4ca0e31e42/3fac61d3-d1c3-4269-af30-cd0427d3eb1a)

**Comment by kevwalsh** [comment]
Closing this because we want to remove support for buttons, in #6604
