### ISSUE TITLE
Change default URL alias for User guide to /help/[menu-tree]/[title]

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#2755]
## Acceptance Criteria

- [ ] CMS Help Page content type URL pattern is updated to `/help/[menu-tree]/[title]
   * example: this page `/node/9422/edit`  should have an alias as follows `/help/access-training/session-2-editing-basics` based on its parent menu item, instead of `/help/session-2-editing-basics`
- [ ] aliases for existing CMS help page nodes are regenerated with an exception of `/help` CMS help center homepage
   - [ ] verify a list of custom urls in the help center that shouldn't be regenerated w/ @rachel-kauff @xiongjaneg

**Comment by msbtterswrth** [comment]
@kevwalsh i think this is already done? for example `/help/cms-basics/how-to-log-inout` is the url now for login help.
