### ISSUE TITLE
[R&S] Media list - videos component should allow to create new Videos

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#2763]
## Description

Media list - videos component currently allows selection of existing  Video entities.

This component should also provide UI to create and attach new Video entity without leaving the form.

## Notes
- This was formerly blocked until Drupal 9 was released. We're not at Drupal 10, so this may now be possible.

## Acceptance Criteria
- [ ] Media list - Videos component provides UI for creating and attaching new Video entities without leaving the form in addition to selecting existing entities.

**Comment by ethanteague** [comment]
@oksana-c this isn't going to be easy. https://www.drupal.org/node/3024762

**Comment by ethanteague** [comment]
@oksana-c @kevwalsh what's the approach I should be taking on this task? Still need to figure out how to deal with this issue: https://www.drupal.org/node/3024762

**Comment by ethanteague** [comment]
@oksana-c tried upgrading to drupal 8.9, but the issue remains - there isn't a way to add new media to the media browser.

**Comment by oksana-c** [comment]
Drupal 9 will offer the "create inline" functionality. On hold until then.

**Comment by swirtSJW** [comment]
Since this is labelled LC - Learning Center  I am moving this to Public Websites to establish if this is something that is still desired.

**Comment by wesrowe** [comment]
@swirtSJW, how did it get on your radar this week? "Learning center" hasn't come up for us yet

**Comment by wesrowe** [comment]
demoted to new/unref and "icebox" label because Outreach Materials Library, fka Learning Center, has been deprecated as of Fall 2022.

**Comment by wesrowe** [comment]
@rlhecht, @DanielleThierryUSDSVA – Is the ability to add a video within the R&S Media List component something that would be high value for your team? If so, please share a little context as an input to our prioritization process.

**Comment by FranECross** [comment]
@RLHecht, @DanielleThierryUSDSVA Please take a look at Wes's question above and let us know if this is still needed. I'll then check with Dave on prioritization if so. Thanks a bunch! 🎉 cc @jilladams 

PS: It looks like it was formerly blocked until Drupal 9 was released, and we're not at Drupal 10.

**Comment by FranECross** [comment]
Closing old 2020 ticket; will revisit if it comes up again.
