### ISSUE TITLE
Form detail pages need itself to appear in breadcrumb

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#2770]
**Describe the defect**
A form detail page should include itself in its breadcrumbs
![image](https://user-images.githubusercontent.com/5752113/91315301-879b7400-e785-11ea-9b8a-33c8b68b223f.png)
It should be 
`Home > Find a VA form > About VA Form 10-10CG`

This limitation comes from the fact that we are using menu breadcrumb and it has this setting
![image](https://user-images.githubusercontent.com/5752113/91315395-a26de880-e785-11ea-96bf-55c8b5ca3fc7.png)
So it only gets a link to itself if the page is in the menu.

We need a way for certain content types to not be in a menu but still get proper breadcrumbs.... that don't break all other breadcrumbs.

slack discussion: https://dsva.slack.com/archives/CUB5X5MGF/p1598385246020300

**Comment by kevwalsh** [comment]
@swirtSJW Related: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/1238

**Comment by kevwalsh** [comment]
Closing this in favor of #1238
