### ISSUE TITLE
Reduce log noise from schema generator.

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#2780]
## User Story or Problem Statement
As an engineer, I do not need to know every time the schemata module indexes the content type schema. so that are logs do not fill up every time the content export is requested.  This happens now every time the content export is requested.  It created 3 page of log entries each time.

The logger is called here docroot/modules/contrib/schemata/src/SchemaFactory.php

We have two choices
1) patch contrib to silence it.
2) alter our approach to rebuild the schema on bulk export rather than on download request so that it is not being called so often.

2 is probably the wiser approach now that the bulk export is running after each CMS deploy.

**Comment by oksana-c** [comment]
solved in #3387
