### ISSUE TITLE
Dashboards implementation plan

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#2786]
## Acceptance Criteria

- [x] VAMC and Resources and support product dashboard prototype is reviewed for emerging UI patterns w/ @jordanamello @oksana-c @kevwalsh 
- [ ] recommendation for technical dashboard implementation is composed and covers aspects like custom module development, plugins, views, front-end components ,etc.
  - [ ] Drupal layout framework has been selected
    - [ ] Opportunities for recommended framework have been identified
    - [ ] Risks for recommended framework have been identified
- [ ] implementation recommendation plan is reviewed w/ @indytechcook @oksana-c 
- [ ] technical implementation plan is finalized in a format that other engineers can reference when working on dashboard features/stories (e.g. spreadsheet, etc)

**Comment by jordanamello** [comment]
@acrollet I created a developers version of the XD links. By clicking on _View specs_ (toolbar on the right), you can see css info, along with other data. 
- **Resources and support dashboard**: https://xd.adobe.com/view/5cd15a8f-426d-4356-b81e-82920dd688be-0982/specs/
- **UI cards anatomy**: https://xd.adobe.com/view/d8d9c2fa-1235-4d6e-a72f-4b999f5f27d5-8d8a/

**Comment by acrollet** [comment]
@jordanamello great, thanks!!

**Comment by oksana-c** [comment]
@jordanamello , please add VAMC dashboard prototype link here. Thank you.

**Comment by jordanamello** [comment]
@oksana-c @acrollet here it is: https://xd.adobe.com/view/4837c11c-b5b4-4439-84d7-5867919f9c42-1d64/

**Comment by acrollet** [comment]
@oksana-c @jordanamello @kevwalsh I've made a first pass at capturing the user stories embodied in the prototype. Please review it when you're able and add items I've missed and any clarifications/improvements you have, thanks so much!

**Comment by acrollet** [comment]
@oksana-c @kevwalsh as far as we know, will the CMS admin UI ever need to be translated? (As opposed to content for va.gov)

**Comment by oksana-c** [comment]
@acrollet , not that we know of and not in any near future. We can follow best practices and if any admin functionality we provide needs custom config, we make it eligible for translation by default in a *.schema.yml file

**Comment by acrollet** [comment]
@oksana-c I'm attaching a first pass at an overview document for the technical implementation plan, with two options for routing/layout and their strengths/weaknesses as I see them:

1. custom controller & templates
2. config entities + layout builder

@jordanamello after reviewing the current state of affairs, [Layout Builder](https://www.drupal.org/docs/8/core/modules/layout-builder) is pretty much the only game in town for in-browser page building utilities. Where the above affects our previous discussion re: layout frameworks is that our main choice is between using what layout builder provides and working to limit the choices given to editors, or to provide a bespoke UI for doing things like hiding/re-arranging content cards. (Assuming that's validated as a requirement)

[VAMC Dashboard tech plan.pdf](https://github.com/department-of-veterans-affairs/va.gov-cms/files/5585011/VAMC.Dashboard.tech.plan.pdf)

**Comment by oksana-c** [comment]
whoa! we may need to adopt your template ❤️  making some time to review

**Comment by jefflbrauer** [comment]
Vet Center Dashboard work is a start in the right direction, although not the full suite of features dashboards will ultimately contain.  Core team was consulted and direction is good.
