### ISSUE TITLE
CMS export content from WYSWIG fields is not rendered

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#2787]
**Describe the defect**
when looking at content in wysiwig fields, the export just contains the raw unrendered content so it is 

1. not passed through the filter 
2. links are to node paths `href="/node/989` and not rendered paths like `href="/disability/compensation-rates"`
screenshot comparing export data to graphQL data

**Expected behavior**
Html based fields should be rendered/filtered to get accurately processed html

**Screenshots**

**Comment by indytechcook** [comment]
Submitted PR: https://github.com/department-of-veterans-affairs/va.gov-cms/pull/2793

**Comment by ElijahLynn** [comment]
We had the `processed` field added back at one point so it must have gotten removed somewhere.
