### ISSUE TITLE
[LC] "Need more help?" section (311 OR Benefits Hub contacts)

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#2794]
## Description

"Need more help?" component displays contact information that is maintained in several different places: Support Service nodes, Benefits Hubs Landing Page nodes or custom entered info.

The CMS should provide the UI for selection of predefined contacts and the ability to add one manually curated contact (phone or email).

The scope of this issue is the UI to select either default contact or Benefits Hub(s) contact information. Similar model was created for the Alert (single) paragraph and is currently visible on "Step-by-Step" content type when adding a Step.

<img width="412" alt="Screen Shot 2020-09-04 at 2 20 59 PM" src="https://user-images.githubusercontent.com/16477724/92281934-e6659980-eeb9-11ea-8a3b-c42eb19f7614.png">

**See [lo-fi interactive prototype with expected authoring experience](https://xd.adobe.com/view/7be68cf2-ea37-4b1c-94c7-2caedbb52674-2eb5/).**

NOTE: The optional phone/email component will be addressed in #2790 

## Acceptance Criteria

- [x] new paragraph is created "Contact information" `contact_information`
    - [x] Content editor can switch from the default value to a selection of one or more Benefit Hubs (cardinality unlimited - all hubs can be selected) . Content editor can reorder selected Benefits Hubs to curate the order of contact info on the front-end.
      - [x] field that allows the user to switch between Default and Benefit Hubs contact information | `field_contact_info_switch` | label "Select contacts" | required | radio buttons are limited to two options shown on the prototype
           - [x] the switch field has no "none" option. One contact must be selected - either default or Benefit Hub contact set. Validation of this paragraph should support one required contact. If the user switches to Benefit Hub, but doesn't select any - an error should be thrown.
      - [x] default contact value -> entity reference field prepopulated w/ a reference to `node/61` Support Service node "Call VA311 for help:". `field_contact_default` | label "Default contact" | cardinality - single
      - [x] Benefit Hub selection entity ref field `field_benefit_hub_contacts` | label "Benefit Hub contacts" | cardinality unlimited
      - [x] user can not add duplicate entity references in `field_benefit_hub_contacts`. E.g. if "VA Health care" is selected. the user cannot add another instance of "VA Health care". Related to #2899 

- [x] new Entity Browser view “Benefit Hub Contact Information” is created to support Contacts Selection by Benefit hub. See [entity browser prototype](https://xd.adobe.com/view/7be68cf2-ea37-4b1c-94c7-2caedbb52674-2eb5/screen/71f0705d-9f2a-4156-96c2-78d16f953cd4?fullscreen)
- [x] new view mode "Support Services Listing" is created for "Benefit Hub Landing Page" type nodes to support display of Support Services in an unordered list in the entity browser and on the node view pages where "Contact information" paragraph is used. See ["Contact information" paragraph view prototype](https://xd.adobe.com/view/7be68cf2-ea37-4b1c-94c7-2caedbb52674-2eb5/screen/b2b5d828-fcf5-4ea3-a89d-8ba30f19365a?fullscreen) 

- [x] "Contact information" paragraph is added to the following content types: Q&A, FAQ - multiple Q&As, Checklist, Step-by-Step, Media list - Images, Media list - Videos. Paragraph added via field "Need more help?" `field_contact_information`

**Comment by kaise-lafrai** [comment]
> NOTE: The optional phone/email component will be addressed in #2799

Has the above been addressed? #2799 seems to go to a dependabot pr.

**Comment by kaise-lafrai** [comment]
@oksana-c 

> Paragraph added via field "Need more help?"

Do we want to call the paragraph "Need more help?" or "Contact information" ?

**Comment by oksana-c** [comment]
@kaise-lafrai , field "Need more help?", paragraph "Contact information"

thanks for noting incorrect link, switched it to #2790. phone/email component depends on #2792

**Comment by kaise-lafrai** [comment]
Ready for review here: https://github.com/department-of-veterans-affairs/va.gov-cms/pull/2935

**Comment by kaise-lafrai** [comment]
@oksana-c we're also using here.

>  Benefit Hub selection entity ref field field_lc_benefit_hub_contacts | label "Benefit Hub contacts" | cardinality unlimited

This ticket will need refactoring and additional work if anything is found during QA.

**Comment by oksana-c** [comment]
thanks for noting this @kaise-lafrai 
`field_lc_benefit_hub_contacts` should now be `field_benefit_hub_contacts`. ACs are updated.

**Comment by oksana-c** [comment]
@ncksllvn @kelsonic below please find a flowchart that explains the data structure in "Need more help" component. Let's discuss at 4pm tomorrow if there are any questions. Thanks,

Note, currently `field_benefit_hub_contacts is multivalue on prod, but it will be changed to single value by EOW.

![Need more help component structure](https://user-images.githubusercontent.com/16477724/94498279-ff125800-01b6-11eb-96e0-2ef7ac9d42a3.jpeg)
