### ISSUE TITLE
Quantify usage of embedded images in all existing wysiwyg fields

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#2804]
## Description

we need to provide a unified way of adding Image captions. A part of this effort is removing the ability to add images via wysiwyg (users should only be able to add document entities). Before pull the plug on images embedded in WYSIWYG, we need to know if and how many image entities were embedded in existing WYSIWYG fields.

## Acceptance Criteria

- [ ] run DB queries to quantify how often embedded media of type Image is used in various WYSIWYG fields

**Comment by kevwalsh** [comment]
We can probably grep the cms-export json for this.

**Comment by kevwalsh** [comment]
This was handled in Q4 2020 when Entity Embed was removed.
