### ISSUE TITLE
Redirect governance doc

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#2805]
Our redirect design doc could be supplemented with a shared understanding of the problem space and opportunities for governing URL redirects in CMS.  

Examples:
-  Facility gets renamed in VAST due to legislation passed by congress. URLs in Drupal are updated...

**Comment by jefflbrauer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VAgov-CMS-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/2805?planning-poker) with ZenHub @ElijahLynn @indytechcook @ndouglas @olivereri @timcosgrove

**Comment by jefflbrauer** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VAgov-CMS-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/2805?planning-poker) with ZenHub @cweagans

**Comment by TheBoatyMcBoatFace** [comment]
Closing issue - This is not us in the current incarnation of our team. Reopen if necessary.
