### ISSUE TITLE
Migrate date data to a new field with time zone support

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#2812]
This needs to be process all content types that use the timezone.

Should use this as a basis
https://github.com/department-of-veterans-affairs/va.gov-cms/blob/5196bc72d50c8565cbca4f5082085a3a8f85e9d6/scripts/content/VACMS-2975-update-vamc-service-nodes-2020-10.php
Name it `VACMS-2975-update-timezone-data-2020-10.php`

ACs
- [x] `field_date` in `event` node has been migrated to `field_datetime_range_timezone`
- [x] `field_date_and_time` in `situation_update` paragraph type has been migrated to `field_datetime_range_timezone`
- [x] ~`field_release_date` in `news_release` has been migrated to `field_datetime_range_timezone`~. (removed November 2) 
- [x] Time zone has been to ET by default (assess how it's stored in DB and see if it needs conversion)
- [x] Update ALL revisions to prevent messiness that comes from reverting (revisions will need to be updated without creating new revisions.
- [x] Future events retain their original value, accounting for time changes as well. 

##Post release steps
1. SSH into prod.   run `drush scr ../scripts/content/VACMS-2975-update-timezone-data-2020-10.php`

**Comment by kaise-lafrai** [comment]
lando drush scr ../file name. to run locally.

**Comment by swirtSJW** [comment]
@kevwalsh @ethanteague   Just confirming the end result of this should result in the old datetime field should be hidden in the node form and the new one should be visible?

**Comment by ethanteague** [comment]
This wouldn't cause any issues with the build, @swirtSJW , so I think it's safe to make the new field visible after migration (and obscure the old one).
