### ISSUE TITLE
Smarter default time zones (was: Support time zones for date field(s))

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#2813]
### User Story or Problem Statement

Current datetime field on Event and Situation Update content types don't support time zones. 

The FE assumes everything is ET.

### Affected users and stakeholders

* All CMS users who add/edit events.
* VAMC editors who add/edit situation updates

**Comment by mmiddaugh** [comment]
Transformer for this new field [#15666](https://github.com/department-of-veterans-affairs/va.gov-team/issues/15666)

**Comment by jilladams** [comment]
1 remaining open ticket, moved to #8881 . Closing.
