### ISSUE TITLE
[LC] URL alias & breadcrumb strategy for Learning Center content

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#2818]
## Acceptance Criteria

- [ ] discuss URL alias governance for Learning Center content w/ @jenniferlee-dsva  @mpeterz @mnorthuis 
   - [ ] alias patterns
   - [ ] alias governance and potential for automation
- [ ] discuss breadcrumb IA for Learning Center content
- [ ] refine implementation stories

**Comment by jenniferlee-dsva** [comment]
Hi @oksana-c  - Please include @mnorthuis and @mpeterz in the URL discussion. I'm not sure if both are needed, but we def need Mikki to weigh in.

**Comment by oksana-c** [comment]
thanks @jenniferlee-dsva 
Scheduled a call for us Sep 9th at 10:00am ET. 
cc @mpeterz @mnorthuis @kevwalsh

**Comment by oksana-c** [comment]
@mpeterz @mnorthuis @kevwalsh @jenniferlee-dsva  @johnhashva , scheduled a follow-up call for us Sep 16th at 10:00am ET.
[MURAL](https://app.mural.co/t/vagov6717/m/vagov6717/1599652638055/3fe4f4c4660195aeebc964a03ff6fcfb3723c04b)

**Comment by oksana-c** [comment]
group call to discuss final requirements for URL alias patterns + LC content breadcrumbs was rescheduled from Sep 29th to Oct 7 3:30pmET

**Comment by oksana-c** [comment]
Moving to Sprint 17, since the decision is still being formed.

**Comment by oksana-c** [comment]
thank you @mnorthuis 
I scheduled a call for Jen, you and I on Friday, Oct 16 to go over the spec and considerations you posted.

**Comment by oksana-c** [comment]
final patterns described here https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/websites-learning-center.md 
follow-up work happening in other stories.
Thank you all!
