### ISSUE TITLE
[LC] Research options for tagged content listings on FE

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#2819]
## Acceptance Criteria

- [x] call w/ CMS / PW LC/Search teams to discuss known capabilities of search.gov in relation to structured data in search. Date: 9/8/20 10:00am ET. Attendees: @johnhashva @jenniferlee-dsva @swirtSJW @andaleliz @MickinSahni @ncksllvn @kevwalsh
- [x] call w/ search.gov team to get clarity on available features. Agenda below:
     * Capabilities for additional indexed data - e.g. article type, tags
     * Search result properties - how customizable is returned data?
     * Facet options to generate “tagged by” pages
     * Deprecation timeline for tag filters https://search.gov/manual/filter-tags.html 
- [x] CMS / PW team define path forward after technical options have been explored

**Comment by oksana-c** [comment]
9/8/20
Summary of available options:

<img width="1242" alt="Screen Shot 2020-09-08 at 12 49 48 PM" src="https://user-images.githubusercontent.com/16477724/92516303-3f8f3f00-f1d2-11ea-8623-03bf84716302.png">

_@MickinSahni , thanks for offering a visual reference._

Action items:
- [ ] @johnhashva to schedule a call w/ search.gov team

cc: @johnhashva @jenniferlee-dsva @swirtSJW @ncksllvn @andaleliz @kelsonic @kevwalsh

**Comment by johnhashva** [comment]
Team -- just heard back from Search.gov and their product lead is out this week.  I will work to get our meeting with her and her team early next week.

**Comment by jenniferlee-dsva** [comment]
All - I believe this can be closed, since John organized the call for us last week. Summary from yesterday's follow up with PW team: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/status-and-decisions.md#92320

**Comment by oksana-c** [comment]
@jenniferlee-dsva - yes, we can close this. Per our [last check-in](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/cms/readme.md#tuesday-september-22), @ncksllvn @kelsonic will follow up on the ability to use GraphQL queries to generate "content tagged by X" pages. If any follow up is needed form the CMS team, we'll open an issue in CMS Sprint 16.

**Comment by MickinSahni** [comment]
Here's our discovery ticket: [Discovery] Can we use GraphQL to generate articles list? #13883.
Oksana, I know this is on your repo but taking your last comment as a go-ahead to close :)
