### ISSUE TITLE
Update staff profile help text and proofing.

### ISSUE THREAD

**Issue by rachel-kauff** [department-of-veterans-affairs/va.gov-cms#2827]
There's a piece of help text that really could use updating ahead of training (a really confusing field label), and as I'm heads down on content creation, I could use support from someone to make the change for me. 

AC
- [ ] Changes to help text and field labels, and field group order noted in this wireframe are updated on prod: https://balsamiq.cloud/s21kwcm/py46j7t/r4FA3

**Comment by kevwalsh** [comment]
@rachel-kauff please have a look at https://github.com/department-of-veterans-affairs/va.gov-cms/pull/2829 for the changes i made. i dropped "meta tags" fieldset altogether, it's misleading.
