### ISSUE TITLE
Design account admin service

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#2834]
### User Story or Problem Statement

As a current or prospective CMS user, i want a clear process for applying for accounts, or increased permissions, and clear documentation about what each role can do, so that i can get the access i need to accomplish tasks in the CMS. 

As a user admin, i want tools that help me manage users in the sections i have governance over. 

As a governance stakeholder, i want confidence that permissions are being assigned correctly. 

### Affected users and stakeholders

* All current and future CMS users
* CMS governance stakeholders

**Comment by stefaniefgray** [comment]
Editors could use a form that provides these options and allows users asking for new accounts (for themselves or for someone else) to provide relevant information

Will leave open to discuss at a later date with @TroyA6 

Need to find out where Editors have been getting the "Name: Role: Facility:" ticket format/template from

**Comment by EWashb** [comment]
we need to rethink this within current scope and ecosystem. I suggest that we create an updated epic/issues if this is still a priority.
