### ISSUE TITLE
Behat test to cover FE breadcrumbs

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#2841]
## User Story or Problem Statement

As a developer I need to know when a change to the CMS codebase changes the display of breadcrumbs on some key pages so that I may have confidence in knowing that breadcrumbs are not broken.

candidates:
/pittsburgh-health-care/news-releases
/pittsburgh-health-care/
/pittsburgh-health-care/leadership/

/pension/eligibility/
va forms  (need a stable node from va forms)
more? (other pages where we have had issues with breadcrumbs)

## Acceptance Criteria
Test fail when breadcrumbs change / break
## Implementation steps
Behat test in the decoupled feature to examine breadcrumbs on various content types.

**Comment by ElijahLynn** [comment]
Also maybe enabling the broken links to error out builds? Which would have caught this one too.

**Comment by swirtSJW** [comment]
It would have caught this, but for not the right reasons.   If we don't wan't broken links to fail FE content releases, we don't want to have our own releases dependent on them too.  Content should not fail builds.  In this case the broken link was not content,  but there are plenty of times when it is content.  That's why I'd rather just get tests in place to catch the stuff that is not content, so that we don't have to make builds dependent on good content.
