### ISSUE TITLE
Enable Maintenance mode

### ISSUE THREAD

**Issue by indytechcook** [department-of-veterans-affairs/va.gov-cms#2851]
When a deploy is occurring, a static html page should be show to users who are coming into the site during the deploy.  This page will allow the database to not be touched while the deploy is occurring. 

AC
* When a flag is set in the CMS, all pages should return a static HTML page.
* When a updb, config import is running then a static HTML page should be displayed
* Drush jobs should not run when deploy mode is enabled.
* Design and UI should reflect the site alert version, with these differences:
  * Page refresh every 30 seconds
  * No transparency

**Comment by indytechcook** [comment]
This could follow a similar process as https://github.com/department-of-veterans-affairs/va.gov-cms/issues/1651

**Comment by ElijahLynn** [comment]
Deploy Runbook (manual steps):

1. Go into existing instance (pre-deploy)
1. `sudo -u apache -s; cd /var/www/cms`
1. `git fetch`
1. `git checkout a8f64d577767d389aada2fd8886e785ffbbfe12f -- composer.json docroot/modules/custom/va_gov_backend/src docroot/sites/default/`
1. `source /etc/sysconfig/httpd; PATH=$PATH:/usr/local/bin composer dumpautoload`
1. Run Jenkins deploy job
