### ISSUE TITLE
Email and phone number "label" field required status for more than one paragraph

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#2855]
## User Story or Problem Statement

~When there is more than email or phone number, we need to require the labels. ~

~Eg, When phone and email component are multivalue, we need the form to adapt to how many values. ~

~When there is more than one email, or more than one phone, editors will need to add an additional label that will let end users know the difference between two phone numbers, ~

## Acceptance Criteria
* ~Editors are required to enter a label when there is more than one~ 
* Label for for phone number and email component is required
* Help text for both fields should read: "A label should indicate what office, program, or staff person can be reached here."

This may be dependent on #2825

**Comment by kevwalsh** [comment]
## Candidate ACs

Remove the "Operations" label on _all_ IEF Table View widgets.

![Edit_VAMC_Facility_Health_Service_Intimate_partner_violence_at_VA_Pittsburgh_health_care_-_Beaver_County_VA_Clinic___VA_gov_CMS.jpg](https://images.zenhubusercontent.com/5d6e57ad330f64311395f08b/f5240e98-018b-4df1-8024-2ab04785012e)

**Comment by ethanteague** [comment]
Apologies, @kevwalsh - I'm gonna have to bump the more than one label = set to required thing to next sprint. It's proving to be more challenging to accomplish this than I had hoped. I'm a day in, and still scratching my head.
