### ISSUE TITLE
Remove old date time fields from event and situation update

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#2860]
This follows from #2811, but depends on the FE work being complete. 

ACs
- [x] ~Hide the three **old** date fields from Event, News release nodes and Situation update paragraphs, from their form modes and view modes~
- [x] ~Show the three **new** date fields with time zones on the same form modes and view modes (note multiple view modes!)~
- [x] Old date fields have been removed from `situation_update` and `event` 
- [x] The unused field_datetime_range_timezone for News release (`press_release`) content type is removed (was #3365)

**Comment by kaise-lafrai** [comment]
@kevwalsh Do we still need the following views? 

Date Fields : `/admin/structure/views/view/listing_page_dashboard/edit/default`

Listing Page Dashboard : `/admin/structure/views/view/date_fields?destination=/admin/structure/views`

**Comment by kaise-lafrai** [comment]
@kevwalsh If we do use those views then I need to make updates to use the new field_datetime_range_timezone field.

**Comment by kevwalsh** [comment]
@kaise-lafrai i don't think we need those. i had forgotten about them, the intention was partly to use them as migration QA.
