### ISSUE TITLE
Clarify constraints for interim publishing of new content, pre-CMS export / transformers

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#2882]
## Description

Given the delay on CMS export / transformers, POs want a better understanding of how much content can be published, so that they can plan to launch new products before CMS export.

## Acceptance Criteria
- [ ] DEPO POs have a shared understanding of what the constraints exist for publishing new content from VA.gov (form detail pages, VISN 4 VAMCs, etc)
- [ ] We have established a plan for increasing the runway / capacity, if necessary. 
- [ ] We have a product-by-product audit of how much content is a candidate for publishing during this interim period. 

## Testing notes

Ideal: All of VISN 4?
Minimum: All of Erie

* ignore broken links for now
* 

# Audit 

As of September 15, there are 1062 published nodes, out of 7032 total. 

### VISN 4

Altoona 260
Butler 249
Coatesville 176
Erie 285 (probably a priority)
Lebanon 311
Philadelphia 256
Pittsburgh 487 (already published)
Wilkes-Barre 205 
Wilmington 249

1915 nodes as of September 15, 2020, not including 487 at Pittsburgh VAMC. 

Notes
* Left nav is a react component. 
* Each product can be published from its respective Section page. 

Complexity of templates varies, from 

- simple (events, stories, news releases)
- medium (detail pages, which have lots of paragraphs)
- complex (VAMC system page, Locations page)
- highly complex (health services pages, which could have 50 taxonomy terms, 200 nodes or more) 

### VISN 19

857 nodes as of September 15, 2020, but no facility health services yet (to be migrated soon)

### Learning Center

11 Q&As so far, unpublished.

Waiting to hear back about more.

These pages are nodes with paragraphs,  5 out of 10 on the content complexity scale.

No left nav.

### VA Form detail pages

41 Forms published, out of a total 478 forms. (MVP)

411 are “in review”
22 in draft.

These are set to be published at some point in Q4 2020

1 out of 10 on the content complexity scale.

No left nav.

**Comment by kevwalsh** [comment]
Per @swirtSJW: 
> timeouts were updated on both cms side and FE side... so we need to do another round of testing on staging to see where the new breaking point is.

**Comment by indytechcook** [comment]
VISN 4 numbers (Altoona is an outlier)

The number are cumulative in order.


  | Drupal API (sec) | Total build (sec) | Max Memory (mb)
-- | -- | -- | --
Current | 172 | 260 | 3107
Erie | 215 | 319 | 4011
Altoona | 180 | 381 | 4405
Butler | 287 | 407 | 4738
Coatesville | 308 | 429 | 4637
Lebonon | 306 | 424 | 4995
Philadelphia | 319 | 440 | 5006
Wilkes-Barre | 322 | 443 | 5002
Wilmingon | 327 | 462 | 5002

**Comment by ElijahLynn** [comment]
Current Jenkins instances are "c5d.4xlarge, 32GB ram, 16vCPU with NVME SSD".

**Comment by ElijahLynn** [comment]
Related Slack Discussion (INTERNAL) https://dsva.slack.com/archives/C01512KN35G/p1600355432101700.

**Comment by indytechcook** [comment]
The testing process which occured on http://test.prod.cms.va.gov/

1. Publish content from the section list page. (ex. http://test.prod.cms.va.gov/section/veterans-health-administration/vamc-facilities/va-altoona-health-care)
1. Clear cache
1. Visit home page.
1. Delete any local copy of drupal json `rm -rf /Users/neil.hastings-a/code/va/va-frontend/vets-website/.cache/localhost/drupal/pages.json`
1. Build vets-website `yarn build:content --pull-drupal --drupal-address=http://test.prod.cms.va.gov -v`
1. Record The API response time from the logs: `http://test.prod.cms.va.gov response time: : 346050.529ms`
1. Record the total build time: ```Build finished!
✨  Done in 481.14s.```
1. Record the step with thigh highest memory usage. This is pulled from the `Total Memory Used After Step` column in the build summary.
