### ISSUE TITLE
Create shared understanding for VFS product teams regarding transformer responsibilities 

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#2884]
## Description

VFS product teams developing products with CMS need an understanding of their responsibilities vis-a-vis transformers, for new content types or content model changes. 

## Acceptance Criteria

- [ ] A markdown file exists that explains the division of responsibilities and workflow for new content model changes. 
- [ ] the division of responsibilities and workflow is communicated to CMS Core and Product teams

**Comment by indytechcook** [comment]
Closing since we no longer use transformers
