### ISSUE TITLE
Migrate system health services for VISN 2, 6, 16, 21, 23

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#2896]
Blocked by VAMC upgrade team's CSV

**Comment by swirtSJW** [comment]
Visn 6 content was delivered via slack but has some  data issues.
https://dsva.slack.com/archives/CPQFCQKEH/p1604357179304000

**Comment by swirtSJW** [comment]
I received these csvs last night 
![image](https://user-images.githubusercontent.com/5752113/98420870-21b94b80-2056-11eb-9e38-d55552eca3b6.png)

Will investigate Monday morning

**Comment by swirtSJW** [comment]
Some issues with the data, but pretty minor.  
https://dsva.slack.com/archives/CPQFCQKEH/p1604943524349600

**Comment by swirtSJW** [comment]
2, 6, 16, 21 all check out ok with a couple of easy fixes I could make.

23 is problematic with some bad html and a naming of `St. Cloud` vs `St Cloud`
![image](https://user-images.githubusercontent.com/5752113/98682810-549f6000-2332-11eb-9399-77fa9d8ee3b0.png)

**Comment by swirtSJW** [comment]
THis has been run on prod
![image](https://user-images.githubusercontent.com/5752113/99597712-67670400-29c6-11eb-9a02-274777d3cb8a.png)


![image](https://user-images.githubusercontent.com/5752113/99597727-6cc44e80-29c6-11eb-8dce-4c389ede39b6.png)
