### ISSUE TITLE
Migrate facility health services for VISN 2, 6, 16, 21, 23

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#2897]
Blocked by CSV from VAMC upgrade team

AC
- [ ] Migration script has been updated to create one service location by default. 
- [ ] Facility health services have been migrated for 5 VISNs.
   - [x] VISN-2 CSV error free
   - [ ] VISN-6 CSV error free
   - [x] VISN-16 CSV error free
   - [x] VISN-21 CSV error free
   - [x] VISN-23 CSV error free

References to discussion of data issues

VISN-2 https://dsva.slack.com/archives/CPQFCQKEH/p1607368222046200
VISN-6 https://dsva.slack.com/archives/CPQFCQKEH/p1606775496480700
VISN-16  https://dsva.slack.com/archives/CPQFCQKEH/p1606920653498400  
VISN-21 https://dsva.slack.com/archives/CPQFCQKEH/p1607370262047200
VISN-23 https://dsva.slack.com/archives/CPQFCQKEH/p1607378826050500

**Comment by kevwalsh** [comment]
@swirtSJW  i added the AC "Migration script has been updated to create one service location by default. "... not sure if this means bumping the estimate to 5.

**Comment by swirtSJW** [comment]
THis has been run successfully on production
![image](https://user-images.githubusercontent.com/5752113/99597537-21aa3b80-29c6-11eb-9ef7-b933761c1de8.png)


![image](https://user-images.githubusercontent.com/5752113/99597546-27078600-29c6-11eb-870c-fb323f8c7d2e.png)

**Comment by swirtSJW** [comment]
Reviewing them now.  Rec'd csv for VISN 6 & 16 from Stan on Nov 23, 2020, 2:27 AM

**Comment by swirtSJW** [comment]
References to discussion of data issued

VISN-2 https://dsva.slack.com/archives/CPQFCQKEH/p1607368222046200
VISN-6 https://dsva.slack.com/archives/CPQFCQKEH/p1606775496480700
VISN-16  https://dsva.slack.com/archives/CPQFCQKEH/p1606920653498400   ->Checks out OK and has been added to PR.
VISN-21 https://dsva.slack.com/archives/CPQFCQKEH/p1607370262047200
VISN-23 https://dsva.slack.com/archives/CPQFCQKEH/p1607378826050500

**Comment by swirtSJW** [comment]
VISN 23 data is now correct.

**Comment by swirtSJW** [comment]
VISN 2 data is now confirmed to migrate correctly and has been added to the PR.

**Comment by swirtSJW** [comment]
VISN-21 is now resolved.

**Comment by swirtSJW** [comment]
This was merged based on Dave C's approval on Zoom today.   https://github.com/department-of-veterans-affairs/va.gov-cms/pull/3621  It does not include VISN-6 which still has data issues.

**Comment by swirtSJW** [comment]
Migration for VISN 2,16,21, 23 have been run on prod 
![image](https://user-images.githubusercontent.com/5752113/101961406-abb97e80-3bd7-11eb-9d9e-f15dc9eb4af5.png)

![image](https://user-images.githubusercontent.com/5752113/101961558-f1764700-3bd7-11eb-8597-a38404bd72d1.png)

**Comment by swirtSJW** [comment]
Just added draft PR https://github.com/department-of-veterans-affairs/va.gov-cms/pull/3723   for VISN 6 data.   Needs to be validated, just posting as Friday end of day precaution.

**Comment by swirtSJW** [comment]
VISN 6 tested out and was merged.   It will go out on Monday and I will run it after deployment.

**Comment by swirtSJW** [comment]
VISN 6 has now been migrated on prod 

Before: 
![image](https://user-images.githubusercontent.com/5752113/102144340-4eba0480-3e33-11eb-9d45-417fcccc58da.png)


After: 
![image](https://user-images.githubusercontent.com/5752113/102145462-4367d880-3e35-11eb-9f4a-6973e20655b7.png)

![image](https://user-images.githubusercontent.com/5752113/102145508-5da1b680-3e35-11eb-8d89-9feba5dd1969.png)
