### ISSUE TITLE
Prevent duplication of selected benefit hubs in field_related_benefit_hubs

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#2899]
## Acceptance Criteria

- [x] field `field_lc_benefit_hubs` is replaced with `field_related_benefit_hubs` with the same configuration and is marked as required
- [x]  content editors are not able to duplicate benefit hubs in `field_related_benefit_hubs`
<img width="1089" alt="Screen Shot 2020-09-11 at 9 29 41 AM" src="https://user-images.githubusercontent.com/16477724/92944772-a3ec1180-f411-11ea-89ff-ab1e91722383.png">

**Comment by kaise-lafrai** [comment]
Ready for review here: https://github.com/department-of-veterans-affairs/va.gov-cms/pull/2941

**Comment by oksana-c** [comment]
@kaise-lafrai , we learned on Friday that Learning Center may have a different product name. Based on that information, the name of the field `field_lc_benefit_hubs` no longer makes sense. 
Since no data was entered into this field on prod yet, it is a perfect opportunity to refactor LC content types right now.

That being said, let's expand the scope of this issue to include field refactoring. Please check update ACs. I also updated story points for this issue. Thanks. 

P.S.  I already added `field_related_benefit_hubs` to the new content type in this PR, so please wait until #2952 is merged in order to reuse this existing field.

**Comment by kaise-lafrai** [comment]
@oksana-c Moving this ticket back to IP. Added https://github.com/department-of-veterans-affairs/va.gov-cms/issues/2952 as a blocker.

**Comment by kaise-lafrai** [comment]
@oksana-c Correction. Keeping this in QA incase anything else is found during QA.
