### ISSUE TITLE
Export errors during deploy time

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#2906]
I am seeing ~50 of these that seem to happen during deploy right before the site alert is taken down.
![image](https://user-images.githubusercontent.com/5752113/92967803-e3355500-f447-11ea-9255-2a7e66735b08.png)

![image](https://user-images.githubusercontent.com/5752113/92967860-f811e880-f447-11ea-969d-a18e9297586a.png)

They are all for the same user and path at the same time.

**Comment by indytechcook** [comment]
PR submitted: https://github.com/department-of-veterans-affairs/va.gov-cms/pull/2976
