### ISSUE TITLE
Design content model for react widget blocks

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#2921]
## Content model hypothesis

We believe we can greaty simplify the content model. 

This can all be merged 

### New block type: React widget 

New block type called React widget `react_widget`

Fields
- [ ] Block description (Name of react widget, ideally)
- [ ] Purpose of react widget - single line text field
- [ ] CTA widget boolean, with values 
- [ ] Section field, default owner "OCTO > Sitewide content > React widgets" (will need a new taoxnomy term)

Fields we may don't need, because these can be hardcoded... but we need to validate. 
- Loading message (can this be standardized for all?)
- Timeout 
- Error message
- Defult content fieldgroup
  - Display default link as button
  - Default link link field 

Permissions
- [ ] Can be created by content_admin (but maybe we don't need need to specify this, because they should have bypass block editing permissions)
- [ ] Can be edited by 

Editorial workflow
- None needed, for now?

View of blocks
- TBD

### React widget content block

New field `field_react_widget_reference`
- [ ] Label: `Select the react widget`
- [ ] Reference only react widget block
- [ ] Hidden on form
- [ ] Hidden on view

### Content proofing
- What should a react widget look like when an editor is looking 
  - at node view for a page that has one? 
  - centralized content, like 

Run this on a tugboat environment

## FE updates

1. update graphql query to pull new fields, from new react_widget_reference, deprecating as many fields as possible
2. paragraph template update to pull from new react_widget_reference paragraph type
3. feature flag

**Comment by FranECross** [comment]
Closing as a no op;
