### ISSUE TITLE
Table field data contains broken HTML if editor forgets to close a tag

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#2934]
## Problem statement

Table field does not offer a WYSIWYG for table cells, which forces editors to manually enter basic HTML tags if text needs to be decorated in any way. Most used tags are `<strong>`, `<em>`, `<ul>`, `<a href="">`

Table fields are quite small, especially when more than 3 table columns are added. It is easy for editors to forget to close an HTML tag. There is no feedback to users that some tags may be broken upon table save.

Content export exports table field values in a form of an array that has not been processed by any Drupal text format plugins which may catch and fix broken tags. All broken HTML persists on export. Sample export below:

```
"field_table": [
        {
            "value": {
                "0": [
                    "<strong>test",
                    ""
                ],
                "1": [
                    "<em>test",
                    ""
                ],
                "2": [
                    "<ul><li>list item<\/li>",
                    ""
                ],
                "3": [
                    "",
                    ""
                ],
                "4": [
                    "",
                    ""
                ],
                "caption": ""
            },
            "format": "rich_text",
            "caption": ""
        }
    ]

```

NOTE: this issue was identified by reviewing current function of tablefield  module and there are no known issues with table HTML on production related to broken markup returned by Drupal

Ideas

- [ ] triage FE process for building tables and confirm that FE does not process retrieved data to remove broken tags
- [ ] explore whether the CMS team should do additional preprocessing before generating table JSON  and open follow up story as needed
- [ ] use wysiwygs for individual cells (this approach will handle all of the html tag closing stuff via pre configured tidy library)

## Acceptance Criteria

- [ ] Table cells have individual wysiwygs.
**OR**
- [ ] Constraint violation occurs on save when malformed html is entered in cell

**Comment by swirtSJW** [comment]
Looking into this deeper, we should really be making sure this is run through drupal  as processed html.   Similar to the way we handle WYSIWIG content.   Then the governance of the allowed html elements is still respected.    Otherwise it is just using raw input directly which is not safe and has no governance.

The other issue is that libxml testing does not catch `<strong>test` because non-closed tags are considered valid.

**Comment by swirtSJW** [comment]
Using it processed as drupal does also ensures that our View tab preview is more in line with front end preview/render.
