### ISSUE TITLE
Eval helpdesk software tool

### ISSUE THREAD

**Issue by daddison48** [department-of-veterans-affairs/va.gov-cms#2938]
Ero will help advise on helpdesk software tool evaluation. New tool should meet the following standards:

- [x] scale to support enterprise level helpdesk 
- [x] input and track user support requests
- [x] easily searchable interface for Tier 1 support
- [x] automated communication generation to users for updates and status of helpdesk requests
- [x] API that would support integration into CMS Drupal site
- [x] Easy and intuitive reporting capabilities
- [x] Ability to escalate helpdesk requests to Tier 2/3 engineering support (Zenhub / Github issues)

**Comment by MaggieBrazeau** [comment]
https://docs.google.com/spreadsheets/d/1PFK4309Kqcuiekk_ldGG6skXTVyAq6IvtgVW9FghS7g/edit?usp=sharing

**Comment by daddison48** [comment]
@MaggieBrazeau , need to schedule a meeting with Jeff, Clarence, David, Sandra, ero to go over data and make decision.

**Comment by MaggieBrazeau** [comment]
https://civicactions.zendesk.com/agent/get-started - ZD trial, will screenshare to demo for 10/7 meeting

Created admin and agent demo accounts and a couple macros to demonstrate possible "voice" for the helpdesk.  

ZD videos here: https://www.zendesk.com/demo/ondemand/?variant=243b&demoStep=personal#3 (My reference only, accessing them requires signing up.)

**Comment by MaggieBrazeau** [comment]
Demo'd, decided on Jira Service Desk.  Document ready for VA

.[https://app.zenhub.com/files/154174777/632e61d4-5e94-48dc-80fe-1ddbbe7e0af8/download](https://app.zenhub.com/files/154174777/632e61d4-5e94-48dc-80fe-1ddbbe7e0af8/download)
