### ISSUE TITLE
Establish helpdesk workflow, processes, and procedures

### ISSUE THREAD

**Issue by daddison48** [department-of-veterans-affairs/va.gov-cms#2939]
- [x] Process for users to request support
- [x] Procedure to acknowledge request
- [x] Triage process
- [x] Workflow for routing of user helpdesk requests
- [x] Workflow for routing of support requests to Tier 2/3 (github/zenhub)
- [x] Process for keeping user updated on status of help request (frequency) 
- [x] Determine workflow (epic) for support
- [x] Process of resolving help requests
- [x] define responsible parties

**Comment by daddison48** [comment]
@cmaeng and @daddison48 are removed as assignee but will be monitoring and helping.

**Comment by MaggieBrazeau** [comment]
https://docs.google.com/document/d/1piIkYdFjvcy0_OMlD3oWVj9o6sX3g5ykG0bopGMiHxI/edit?usp=sharing

**Comment by erogray** [comment]
@daddison48 we're unclear on what "define responsible parties" means -- can you help?

**Comment by oksana-c** [comment]
discussed question about responsible parties during backlog refinement. Outline will be included in the [linked document](https://docs.google.com/document/d/1piIkYdFjvcy0_OMlD3oWVj9o6sX3g5ykG0bopGMiHxI/edit?usp=sharing)

**Comment by oksana-c** [comment]
the last AC "define responsible parties" has been described in linked document. This story is done. Review/iteration will take place in #3067
