### ISSUE TITLE
Implementation of helpdesk software tooling

### ISSUE THREAD

**Issue by daddison48** [department-of-veterans-affairs/va.gov-cms#2940]
## Acceptance criteria

- [x] paying and starting the Jira Service Desk instance
- [x] configure to start using
- [x] add user accounts
- [x] workflows

**Comment by cmaeng** [comment]
@daddison48 to create a thread to coordinate communication around this topic.

**Comment by MaggieBrazeau** [comment]
JIRA SD instance is up and running, configuration is underway.

**Comment by erogray** [comment]
It looks like this is blocked by needing to upgrade our subscription level, which I think requires help from @jefflbrauer
