### ISSUE TITLE
VAMC dashboard usage data collection strategy - Analytics

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#2949]
## Problem statement

In order to gauge the effectiveness of dashboards, understand user navigation patterns and other behavior patterns, we need to collect VAMC dashboard usage data asynchronously over the long term.

## Assumptions
* We can collect data via Google Analytics / Google Tag Manager
* We may utilize other SaaS or custom developed software for data collection if we identify metrics that GA/GTM can not capture

## Acceptance criteria

- [x] Goals of VAMC dashboard are defined
- [x] Analytics metrics that will help us track user behavior re: VAMC dashboards are defined
- [x] Discuss w/ a focus group (@jordanamello @oksana-c @kevwalsh @rachel-kauff @hie1 )
- [x] Incorporate feedback and post the strategy in GitHub

[Research strategy document](https://airtable.com/tblP83AVYP9JiRP79/viwAwguUspdsfjZFq?blocks=hide)

**Comment by jordanamello** [comment]
Repository in GH for VAMC dashboard analytics: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/research/analytics/README.md
