### ISSUE TITLE
Refactor Drupal Spec tool to support additional volume of content type fields

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#2954]
## Description
We’ll keep hitting Spec tool 50,000 chars limit as long as our product portfolio grows. We've refactored the spec tool recently to isolate fields per bundle type into their own tabs, which bought us some time.

We're adding more and more new content model fields for various content types as we work on releasing new products. 
It's time to refactor the spec tool again to allow us to scale while supporting our automated testing processes.

## Acceptance Criteria

- [ ] Split content type field tests out by product 
- [ ] Update custom feature context to allow splitting field tests by bundles

**Comment by acrollet** [comment]
Copy with product names automatically pulled into the Content type sheet + CSVS: https://docs.google.com/spreadsheets/d/1deOZuSuC1mZMjUCfPYNdxHkLBj3PCgOhRDWwnkVVklM/edit?usp=sharing
