### ISSUE TITLE
Improve url aliases and node titles for health services

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#2975]
## User Story or Problem Statement

The URL alias and nodes for facility health services should indicate as much as possible about the content, including good breadcrumbs for users. 

## Acceptance Criteria
 * VAMC facility health services have their paths set to `[node:field_facility_location:entity:url:path]/[node:field_regional_health_service:entity:field_service_name_and_descripti]`
* VAMC system health services have their path set to `[node:field_region_page:entity:url:path]/health-services/[node:title]`
* An update hook in va_gov_db module  resaves all existing nodes of these types to use the new URL alias. this will have the added benefit of resaving some of the existing node titles, which are missing the their entity auto label setting. 
  * ideally, this would leave a revision log message, and be performed by "CMS bot" user

**Comment by swirtSJW** [comment]
This will be resolved by https://github.com/department-of-veterans-affairs/va.gov-cms/issues/3287
