### ISSUE TITLE
Helpdesk Support common topics and canned responses

### ISSUE THREAD

**Issue by daddison48** [department-of-veterans-affairs/va.gov-cms#2980]
As we bring on new users that are not power users, we need to predict possible helpdesk requests in order to be prepared to support. This can feed a support FAQ.

## Acceptance criteria
- [x] Review training [air table](https://airtable.com/invite/l?inviteId=invbYVjjNYG0VqWSB&inviteToken=ac6a0ffbb3ba28c52622155d3eb53278dabb617627a1e1a17cd33921acd27588) (Rachel's)
- [x] compile a list of most common helpdesk support topics with canned responses where applicable
- [x] review topics/responses w/ Rachel, David, others
- [x] GDoc w/ initial set of canned answers exists in shared VAGOV drive

**Comment by daddison48** [comment]
@cmaeng and @daddison48 are removed as assignee but will be monitoring and helping.

**Comment by MaggieBrazeau** [comment]
[https://app.zenhub.com/files/154174777/b8c2d917-72ad-4197-afcf-71f4f8623683/download](https://app.zenhub.com/files/154174777/b8c2d917-72ad-4197-afcf-71f4f8623683/download)

Need to compose answers.  This can happen once I can access CMS, after SOCKS is configured sometime today (10/21)

**Comment by MaggieBrazeau** [comment]
Reviewed with Rachel and Jordana

**Comment by oksana-c** [comment]
@MaggieBrazeau will post a link to the doc that represents initial set of canned responses by EOW.
