### ISSUE TITLE
Rename `cms-infrastructure` GitHub team to `VFS-CMS-Infrastructure`

### ISSUE THREAD

**Issue by ElijahLynn** [department-of-veterans-affairs/va.gov-cms#2981]
## Background

Currently there is another GitHub team called Case Management System that has `cms-team` and has other teams with the `cms-` prefix. We should rename `cms-infrastructure` team to `VSP-Operations-CMS` ?. This will definitely need an update in the https://github.com/department-of-veterans-affairs/devops/blob/master/.github/CODEOWNERS (INTERNAL) file. 

![image](https://user-images.githubusercontent.com/1504756/94047657-392ec480-fd87-11ea-8665-973451bb0dd6.png)

## Acceptance Criteria

- [ ] `cms-infrastructure` team has been renamed to `vsp-operations-cms`
- [ ] `CODEOWNERS (INTERNAL)` file has been updated

**Comment by ElijahLynn** [comment]
K, so there already exists a `vfs-cms-team-infrastructure` which isn't technically correct but matches the other CMS team naming patterns. Ideally it would be `vsp-cms-infrastructure` or `vsp-cms-operations` or `vsp-operations-cms` (`vsp-operations` already exists).

**Comment by ElijahLynn** [comment]
We sized this an 8 as there is potentially some risk in breaking something inadvertently.

**Comment by mchelen-gov** [comment]
i suggest using `platform-cms` as "VSP" refers to the contract while "Platform" refers to the OCTO-DE Crew

**Comment by TheBoatyMcBoatFace** [comment]
This is not worth the risk of breaking things. Reopen if warranted.
