### ISSUE TITLE
Set Daily Deployment Job to wait 60 minutes THEN check for passing commit. 

### ISSUE THREAD

**Issue by ElijahLynn** [department-of-veterans-affairs/va.gov-cms#2983]
Feature request per https://dsva.slack.com/archives/CT4GZBM8F/p1600891355040800?thread_ts=1600890906.039500&cid=CT4GZBM8F (INTERNAL). 

> Though can we juggle it so it looks for a passing commit after waiting an hour instead of looking for the commit and then waiting an hour?

**Comment by olivereri** [comment]
Current:
1. Checkout SCM
2. Get last passing commit
3. Notify everyone
4. Obtain virutalenv packages
5. Set Deployment Site Alert
6. Wait to tag release
7. Run Backups
8. Release and deploy
9. All done
10. Post Actions

Proposed:
1. Checkout SCM
3. Notify everyone
4. Obtain virutalenv packages
5. Set Deployment Site Alert
6. Wait to tag release
2. Get last passing commit
7. Run Backups
8. Release and deploy
9. All done
10. Post Actions
