### ISSUE TITLE
Implement Sentry for error handling

### ISSUE THREAD

**Issue by indytechcook** [department-of-veterans-affairs/va.gov-cms#2987]
We should implement the VFS sentry service integration.

Internal: https://dsva.slack.com/archives/CE4304QPK/p1600896861002300

## Acceptance criteria

- [ ] the team is able to review error reports in Sentry

**Comment by ElijahLynn** [comment]
Agreed!

**Comment by oksana-c** [comment]
closing in favor of https://github.com/department-of-veterans-affairs/va.gov-cms/issues/4695
