### ISSUE TITLE
Rebuild taxonomy entity index programmatically on a regular basis

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#2991]
## Description

Occasionally we're seeing cloned pages with edited Section taxonomy terms show up in the wrong /taxonomy/term/TID view 

See [slack thread](https://dsva.slack.com/archives/CDHBKAL9W/p1600971096006900) with VAMC upgrade team who experienced this defect. 

We've found that rebuilding the index seems to fix this. 

This is blocked by updating to drush 10. https://github.com/department-of-veterans-affairs/va.gov-cms/issues/3868

## Acceptance Criteria
- [ ] Rebuild taxonomy entity index on a regular basis.

**Comment by swirtSJW** [comment]
This drush command is written, but drush throws an error because we are using an outdated version of drush.  Looking for a solution, but this could be unblocked by getting off devshop.

**Comment by swirtSJW** [comment]
I created this issue in the contrib module https://www.drupal.org/project/taxonomy_entity_index/issues/3189721 and am working on a solution.

**Comment by swirtSJW** [comment]
I upgraded to Drush 10 and the drush command works fine.  This is blocked until we can get drush updated.
