### ISSUE TITLE
Entity Browser permission updates for Benefit Hub Contact Information & VA Benefit Hubs

### ISSUE THREAD

**Issue by kaise-lafrai** [department-of-veterans-affairs/va.gov-cms#2999]
## Acceptance Criteria

As a user with Content based roles, I should have access to the entity browser selection during content creation for the following:
- [ ] Access Benefit Hub Contact Information pages
- [ ] Access VA Benefit Hubs pages

See Image below for the correct selections marked with a red box

![Screen Shot 2020-09-25 at 1.38.06 PM.png](https://images.zenhubusercontent.com/5f04cf76eb6c0026ebd18020/1ab9ef9c-c469-4084-a9b3-5c1fcd4773fa)

**Comment by cmaeng** [comment]
Ticket to address support issue raise by Randi [here](https://dsva.slack.com/archives/CDHBKAL9W/p1601047189019000). cc; @MaggieBrazeau @sandyisland1

**Comment by kaise-lafrai** [comment]
@cmaeng A PR has been created and moved to 'review' to address this issue: https://github.com/department-of-veterans-affairs/va.gov-cms/pull/3001
