### ISSUE TITLE
Make arguments work with lando behat/phpunit testing commands

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-cms#3004]
## User Story or Problem Statement

As a developer, I need to be able to run individual tests with lando so that I can quickly validate new/updated tests.

## Acceptance Criteria
* lando behat tag arguments work as documented in [testing.md](https://github.com/department-of-veterans-affairs/va.gov-cms/blob/master/READMES/testing.md)
- [ ] The ```lando behat --tags=perms``` command only runs tests tagged with "perms"

**Comment by swirtSJW** [comment]
Interesting.  I don't know when this stopped working.  Not sure if it was with a lando update or behat update.
