### ISSUE TITLE
Phone paragraph form states logic should cover all instances of a paragraph regardless on parent content type

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#3008]
## Description

behavior can be reproduced on any LC content type: Checklist, Step-by-step, etc.

<img width="1066" alt="Phone paragraph form states" src="https://user-images.githubusercontent.com/16477724/94447385-ee39f600-0166-11eb-8b38-9b6d51b946b9.png">

## Acceptance Criteria

- [x] form states apply to phone paragraph regardless of where phone paragraph is used

**Comment by kevwalsh** [comment]
This would be new behavior (doesn't exist anywhere yet). But i agree, should be CMS-wide.

**Comment by oksana-c** [comment]
@ethanteague confirmed that form states have already been implemented for location content model in phone paragraph
