### ISSUE TITLE
[LC] Product identifier field and AX

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#3015]
## Description

Landing Page content type (basic_landing_page) has field_product. The value in this field does not affect any FE output. It is designed to signify the Product to which this landing page belongs.

Authoring experience for this field needs to be improved before basic_landing_page is extended to products other than Resources and support.

## Acceptance Criteria
* Testable_Outcome_X
* Testable_Outcome_Y
* Testable_Outcome_Z

**Comment by swirtSJW** [comment]
This may no longer apply.  Needs checking out.
