### ISSUE TITLE
VAMC system "Contact Us" page content type and governance

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#3045]
ACs 
* TBD
* See sample ACs in #3046 or #3151 

Feature request via help desk
* Police contact info that could be reused on other pages (we may also want to consider a standardized Police content type)

**Comment by mmiddaugh** [comment]
Closing this as a duplicate to [Improve the Contact us page experience for VAMCs #13900](https://app.zenhub.com/workspaces/sitewide-facilities-639f5253e4b702a32376339e/issues/gh/department-of-veterans-affairs/va.gov-cms/13900)
