### ISSUE TITLE
Helpdesk Workflow and Process Review

### ISSUE THREAD

**Issue by daddison48** [department-of-veterans-affairs/va.gov-cms#3067]
- [x] Review with the program team
- [x] Iterate on internal feedback

**Comment by MaggieBrazeau** [comment]
[https://app.zenhub.com/files/154174777/012c4004-c014-48e8-aaed-bd1e82a1ee3f/download]

**Comment by oksana-c** [comment]
re-posting GDoc link from #2939 for easy access - https://docs.google.com/document/d/1piIkYdFjvcy0_OMlD3oWVj9o6sX3g5ykG0bopGMiHxI

**Comment by erogray** [comment]
@oksana-c I'm feeling a little confused by the intended process here. can you help us figure out how to get the workflows/processes reviewed by the program team?

**Comment by oksana-c** [comment]
closing the loop after coordination in Slack: we'll meet today (Nov4) to review w/ the program team.

**Comment by erogray** [comment]
@oksana-c I'm not sure how to get this reviewed and out of the QA column and into Done — can you help?

**Comment by oksana-c** [comment]
DEPO review will take place in #3546
