### ISSUE TITLE
Change default password on lower environments from "drupal8" to something less drupally, and easy to type 

### ISSUE THREAD

**Issue by ElijahLynn** [department-of-veterans-affairs/va.gov-cms#3072]
Change default password on local developer snapshot DB from "drupal8" to "1", or something where it is less keystrokes...

`va`?
`1`?
etc.

## ACs:
- [ ] Change Sanitize job to set default password to "_tbd_" (token) (devops repo)
- [ ] Update HTTP Auth for GraphQL queries from vets-website PRs (devops or vets-website repo)
- [ ] Update docs: https://github.com/department-of-veterans-affairs/va.gov-cms/search?q=drupal8
- [ ] Update references to 'drupal8' in `va_gov_user\EventSubscriber\UserImport` (cf: #3998) (cms repo)

## New Stories when committing:
- [ ] Training material updates
- [ ] Release note / communication to relevant stakeholders

Further discussion: (Internal) https://dsva.slack.com/archives/CT4GZBM8F/p1601495109277200

**Comment by robbiethegeek** [comment]
WeAre1VA :)

**Comment by ElijahLynn** [comment]
> WeAre1VA :)

Thanks, updated!

**Comment by ElijahLynn** [comment]
Changed this to "1" now for maximum developer experience, as it seems easiest to type.

**Comment by kevwalsh** [comment]
I've changed the title of this, i don't think "1" is ideal, and this merits some discussion.

**Comment by ElijahLynn** [comment]
> I've changed the title of this, i don't think "1" is ideal, and this merits some discussion.

K, the goal in my eyes is for the fastest UX and that would be a single character for my vision. Definitely up for discussing!

**Comment by acrollet** [comment]
@kevwalsh could you expand a bit and provide a suggestion? We're now at the point where `drupal8` is inaccurate :-)

**Comment by TheBoatyMcBoatFace** [comment]
Not a priority right now. Reopen if this becomes an issue.
