### ISSUE TITLE
Spike: Application of Product-based taxonomy and permissions

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#3075]
## Problem statement

Content editing permissions are based on section

Editorial workflow (EWA) permissions are based on Content creator, content reviewer, content publisher roles. 

We have two "product" roles "VAMC content creator" and "Benefit hubs content creator" which orient us towards product-based permissions, but they won't scale for supporting 8+ products. 

We have other upcoming functionality that is product specific, such as dashboards, user guides, CMS announcements, and roles and sections are not sufficient on their own to build upon. 

## Hypothesis

We believe that product taxonomy in the CMS will allow us to structure a more granular access to certain products than Sections taxonomy and existing roles allow.

## Acceptance Criteria

- [ ] develop hypothesis and collect use cases _(design, pm : @jordanamello @nickbloom @kevwalsh @oksana-c )_
- [ ] cross-functional colab _(design, engineering, pm: @jordanamello @nickbloom @swirtSJW @kaise-lafrai @kevwalsh @oksana-c )_
   - [ ] socialize developed hypothesis and brainstorm opportunities
   - [ ] discuss potential technical solutions and scalability of product-based access

**Comment by swirtSJW** [comment]
I think the hypotheses is incorrect.  The perms system is scalable.   Closing this as it was a placeholder to form an idea.. that has not been formed.
