### ISSUE TITLE
Quantitative audit of form widgets

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#3077]
## Description

Quantitative audit of existing content model will allow us to collect information that will support component/pattern inventory effort, and subsequently, the prioritization of component/pattern improvements.

## User stories

I want to improve a widget in one place, so I want to know where else it is used.
I want to know which widgets are used most by editors, so that I can prioritize them.
I want to know which products the widget is used for, so that I can assess the number of affected users.

## Acceptance Criteria

- [x] we have the following data 
   - [x] List of all form widgets and the entity types they are used in (Drupal Spec tool)

## Iceboxed ACs

   * Number of field widget instances
       * per entity type (Spec tool)
       * how many entities (Drupal DB)
       * Per product (we can approximate user number based on this) (Spec tool)
   * Entity browsers
       * How many different entity browsers (Spec tool)
       * How often is each entity browser used (?)

**Comment by acrollet** [comment]
@oksana-c I've done a prototype in a copy of the spec tool sheet - could you review and confirm whether this meets the ACs before I put it in the main doc? Thanks!

**Comment by acrollet** [comment]
@oksana-c I've created a new sheet with a different approach to the widget audit here: https://docs.google.com/spreadsheets/d/18Nd89JY7Qpf8gHZJndA0BdJr0vYjBcDwzXQjpsEUxDk/edit?usp=sharing

The data is pulled in from the spec tool, so it should update dynamically.
