### ISSUE TITLE
"Add another" for multivalue fields

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#3093]
### User Story or Problem Statement

On multivalue fields, especially composite fields (eg paragraphs, link fields, etc) buttons are confusing. After adding the first value, it would be great if the button changed from "Add a [thing]" to "Add _another_ [thing]". 

https://www.drupal.org/project/custom_add_another (8.x-1.0-beta1 released 11 February 2016) may work for us. 

This screenshot is an example of what this experience might look like. 

![Facility_health_services_details___2020-22_VA_gov___CivicActions___Balsamiq_Cloud.jpg](https://images.zenhubusercontent.com/5d6e57ad330f64311395f08b/029c0bcd-0e7c-40b4-8d83-ce5b0786d585)

### Affected users and stakeholders

* All CMS editors

### Hypothesis

_A hypothesis may depend on a spike ticket to be completed._

We believe that _this_solution_ will achieve _this_outcome_. We'll know that to be true when _this measurable outcome occurs._

**Comment by EWashb** [comment]
We have functionality like this is many areas in the CMS.
