### ISSUE TITLE
Table editorial experience spike

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#3095]
## Participants

@rachel-kauff, @oksana-c ,  and another designer and a drupal engineer 

## Description

Editorial experience of tables needs more research

## Questions

- should this switch to one big Rich text / WYSIWYGGY field
- add Rich text editors to every cell? 
- remove the text format dropdown? 
- do we want to make it easer to add a lot of html inside table cells, or keep this as an exception (content strategy of the table design component 
- others

## Acceptance Criteria

- [ ] The above questions have been answered
- [ ] Backlog is refined

**Comment by kaise-lafrai** [comment]
https://www.drupal.org/project/w3c_validator

**Comment by kaise-lafrai** [comment]
https://www.drupal.org/project/clientside_validation

**Comment by EWashb** [comment]
This is now accounted for in #8542
