### ISSUE TITLE
Spike: Explore potential solutions for tagged content in colab with FE tools team

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#3096]
participants: @ElijahLynn @indytechcook @swirtSJW @oksana-c @daddison48 

## Acceptance Criteria

- [ ] CMS / FE tools team had a discussion re: solutions for tagged content for Learning Center (Chris V, Rian Fowler, Dror M. (optional))
- [ ]  CMS / FE tools team have a better understanding of whats possible and have enough information to select the best tool for exporting content lists by tag

**Comment by timcosgrove** [comment]
This ticket does not have any actionable information and is not linked to anything which explains what it might be asking for. Closing! Reopen if you need it.
