### ISSUE TITLE
Regroup on content listing by tag approach

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#3097]
## Acceptance Criteria

- [ ] brainstorm solutions based on info received from FE tool team: @swirtSJW @indytechcook @ElijahLynn @oksana-c
- [ ] finalize the approach + refine backlog

**Comment by swirtSJW** [comment]
Closing this as there is not enough here to explain the use case or the issues it is attempting to solve.
