### ISSUE TITLE
PIV Login Broken - Infinite Loop

### ISSUE THREAD

**Issue by ElijahLynn** [department-of-veterans-affairs/va.gov-cms#3112]
Users are unable to login with PIV/Smartcard. The browser loops infinitely between logon.iam.va.gov and prod.cms.va.gov. 

We haven't changed any libraries but did [make a small change in config.php](https://github.com/department-of-veterans-affairs/va.gov-cms/commit/da72a37260b3a0f8480c483653303d65d1f845a6) but that doesn't appear to have caused it in @indytechcook's tests so far. 

I opened an upstream issue in Service Now (SNOW), INC13393541.

**Comment by ElijahLynn** [comment]
Set this to an 8 estimate as this is involving an external team through Service Now that really slows things down.

**Comment by indytechcook** [comment]
Related Error Messages which started occurring yesterday:

```
Could not load state specified by InResponseTo: NOSTATE Processing response as unsolicited.
```

Looking at the code this error only occurs when the `sid` we get back from SAML does not contain a `url`.  

Related code to that error:
* https://github.com/department-of-veterans-affairs/va.gov-cms/blob/master/simplesamlphp-1.17.2/lib/SimpleSAML/Auth/State.php#L412
* https://github.com/department-of-veterans-affairs/va.gov-cms/blob/master/simplesamlphp-1.17.2/lib/SimpleSAML/Auth/State.php#L280
* https://github.com/department-of-veterans-affairs/va.gov-cms/blob/master/simplesamlphp-1.17.2/modules/saml/www/sp/saml2-acs.php#L90

This then causes the redirect.  I do think we should look at the request we are sending to the SSO server.

**Comment by ElijahLynn** [comment]
Resolved in https://github.com/department-of-veterans-affairs/va.gov-cms/pull/3117. The config had to be reverted in two places, which I tested on STAGING and can login there again now.
