### ISSUE TITLE
Enhance site alert UX

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#3119]
### User Story or Problem Statement

We need site alerts to get important info to CMS users, such as upcoming deployment windows, or issues that may be affecting their use of the CMS. 

This work should be done in coordination with the effort to define alerts messaging for our product  [See this issue](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/3114)

![image](https://user-images.githubusercontent.com/643678/95248456-52069380-07e5-11eb-8305-55efe682cf0c.png)

They have a few issues
* These alerts don't stack well
* The typography is limited (hardcoded to be bold!) 
* They are not dismissible (nor should they be, in some cases).
* They do not follow any existing design patterns. 
* They aren't visually appealing
* They don't impose character limits (but they should)

### Affected users and stakeholders

* All CMS users

### Hypothesis

TBD

**Related epic**
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/3885

**Comment by EWashb** [comment]
Site alert was deprecated with the implementation of sitewide alert
