### ISSUE TITLE
Have CMS notify slack if content release fails

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#3124]
## Description
Update failure logic here 
docroot/modules/custom/va_gov_build_trigger/src/Service/BuildFrontend.php
to put the error message as it does, but ALSO have it notify cms-team direclty using the slack API if this is on prod.  There is no reason a human has to notify us of this.

## Acceptance Criteria
- [ ]  When a failure to create a content release on prod happens, slack cms-team should be notified.
- [ ]  No slack notifications from lando, CI or dev, and staging.
- [ ] Content release error message that is displayed in Drupal CMS is updated to fit the new workflow
- [ ] content release error message that is sent to Slack is written to include relevant information

**Comment by indytechcook** [comment]
The change requested here will not notify the cms channel if the content deploy job fails.  It will only notify slack if the CMS can't access the Jenkins API.

**Comment by ndouglas** [comment]
Should this be moved to the devops repo then?

**Comment by indytechcook** [comment]
> Should this be moved to the devops repo then?

We need both.  Probably a follow up issue for the devops team

**Comment by ElijahLynn** [comment]
Moving back to "ready" column right now on a call with @indytechcook and @oksana-c. We can discuss more.

**Comment by acrollet** [comment]
Closing in favor of #5050
