### ISSUE TITLE
Define and document process for onboarding new CMS users

### ISSUE THREAD

**Issue by cmaeng** [department-of-veterans-affairs/va.gov-cms#3128]
## Description
The VFS-CMS team needs to define and document how to onboard new CMS users, specifically for the upcoming addition of VISNs 4 and 19 late October.

## ACs
- [x] Intake of requests process defined and documented
- [x] Who needs to approve defined and documented
- [x] A checklist of steps to complete in the application defined and documented
- [x] Communication of confirmation with links to support resources and training defined and documented
- [x] Documentation in VFS-CMS google drive and Github

**Comment by xiongjaneg** [comment]
See https://docs.google.com/document/d/1t-fBvTLoQk-a7P56l1pmOx2NOCsN9FSYZXuTpsRraGc/edit#heading=h.s5vy91nn0f0j
