### ISSUE TITLE
Content Admin can not get to manage > content

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#3143]
**Describe the defect**
When logged in as a user with "content admin" role, the Manage -> content menu item is not available.
![image](https://user-images.githubusercontent.com/5752113/95499341-24e7eb80-0973-11eb-8924-7efae47105a4.png)

 
**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information if relevant, or delete):**

**Additional context**
Add any other context about the problem here. Reach out to the Product Managers to determine if it should be escalated as critical (prevents users from accomplishing their work with no known workaround and needs to be addressed within 2 business days).

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Defect")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS objective (orange) (not needed for bug tickets)
- [ ] CMS-supported product (black)

**Comment by cmaeng** [comment]
just discovering this issue. reporting its completion in sprint 19.
