### ISSUE TITLE
Update Deployment Drush jobs to work with Drush 10

### ISSUE THREAD

**Issue by indytechcook** [department-of-veterans-affairs/va.gov-cms#3147]
There are drush scripts that currently only work on Drush 8.  This involves adding the Drush10 Classes with annotations.

* ~`va-gov-cms-export-content`~
* ~`va-gov-cms-export-all-content`~
* `va-gov-get-deploy-mode`
* `va-gov-enable-deploy-mode`
* `va-gov-disable-deploy-mode`
* ~`va-gov-cms-export-generate-tar`~

## Acceptance criteria
- [x] custom Drush scripts are compatible with Drush 10
- [x] Tested on all ENVs

**Comment by ndouglas** [comment]
Closed by #4349!
