### ISSUE TITLE
Code review / release processes

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#3157]
## Owner
@indytechcook 

## Description
The VFS-CMS Core Application and Product Support teams need to be aligned in our code review / release process. The defined system of collaboration must enable team members to demonstrate an agile mindset, promote efficiency and ease of process.

Code review / release process is at the heart of how we work day in and out and defines product quality and team productivity. It is important to have clearly defined rules and expectations as we continue to transition toward self-contained team units.

Brainstorming will begin now, as the team will benefit from transparent discussions, inputs from other team members and a series of refinements.

## Background 

According to the [Program defined RASCI chart](https://docs.google.com/spreadsheets/d/1ezikQhrTCsX36j91ACyf4np_StQdRsoQUmRMN3EmDk8/edit?usp=sharing) - the Core Application team is accountable for the following: 
* Review internally contributed code for quality and architectural consistency, and content model updates for consistency and scalability
* Review all third party contributing code for quality and architectural consistency, and content model updates for consistency and scalability
* Owns code quality and technical standards of va.gov-cms codebase

## Acceptance criteria 

- [ ] Code Review and Release rules are reviewed, re-established and documented
- [ ] Code quality standards are revisited, documentation updated with new recommendations and follow-up user stories are opened as needed
- [ ] Recommended rules / standards are reviewed with the Core Application and the Product Support teams
- [ ] Feedback is considered and incorporated
- [ ] Both teams are aligned on the process going forward

**Comment by indytechcook** [comment]
Starting the conversation here.  

## Personas

Let's start the discussion by talking about different personas.  I will try to avoid process descriptions in the personas and focus on responsibilities.

* **Code Owner**
* **Code Reviewer/Tester**
* **Tech Lead**
* **Product Owner**

While the Code Owner has ownership of the changes introduced in the Pull Request, both the Code Owner and Code Reviewer take shared responsibility for the quality of the changes.

### Code Owner

A Code Owner is either the author of the code, the creator of the Pull Request, or another designated person. There should be only a single Code Owner per Pull Request.  A Code Owner can be anyone with a Github account.

The Code Owner will be the person `assigned` to the pull request.

**Code Owner Responsibilities:**

* All changes introduced within the Pull Request
* Responding to questions and requested changes to the Pull Request
* Passing tests
* Adding new tests
* Adding documentation
* Merging the Pull Request on Approval and test passing.
* Validating the changes in the Pull Request fulfill the needs of the Product Owner and related issue
* Communicating any status about deploy process, extra downtime, etc to the appropriate team members and Product Owner.
* Provide notes on how to test and any necessary screenshots of changes.
* Request a review from a Tech Lead if necessary.
* Request a review from a Product Owner on CI if necessary.

### Code Reviewer

A Code Review is one or more people responsible for reviewing all the changes a Pull Request introduces.  There can be multiple Code Reviewers per PR.  A Code Reviewer can be anyone show is part of the `department-of-veterans-affairs/va.gov-cms` group.  If a change introduces from a Pull Request introduces an architectural change or a significant new feature, a Tech Lead should be the Code Reviewer.

A Code Reviewer will self assign or be assigned by the Code Owner as a `Reviewer` on the Pull Request.

*Code Reviewer Responsibilities*

* Review code for quality passed upon _Insert Spec Here?_
* Test Code changes on CI
* Document what was tested providing screenshots if necessary.
* Follow up with questions/feedback from Code Owner in a timely manner
* Approve Pull Request or provide detailed feedback on why the Pull Request was not approved.
* Request a review from a Tech Lead if necessary.
* Request a review from a Product Owner on CI if necessary.

### Tech Lead

The Tech Lead is there the overall owner of the code and architecture for a particular part of the CMS. In respect to the code review process, the tech lead will be added as a Code Reviewer if a change introduces from a Pull Request introduces an architectural change or a significant new feature.  The tech lead also has final authority in a PR approval, denial, and will hand conflict resolution between a Code Owner and Code Reviewer.  

### Product Owner

The Product Owner is the person who makes the request.  The person is normally can be either within the CMS team or part of VA.  The Product Owner is not directly involved in the Code Review process but can be brought in to review changes on the CI environment. The Code Owner will keep the Product Owner up to date on status.

## PR Review process _WIP_

1. A Pull Request is created in Github as a "draft"
1. The Coded Owner is set as the `Assignee` of the Pull Request
1. The Code Owner will test the changes in CI.  When the Code Owner is confident the changes are ready for review, the Code Owner will set the Pull Request to `Ready for Review`
1. If appropriate, the Code Owner will add one or multiple Code Reviews as `reviewers` on the Pull Request.
1.  if a change introduces from a Pull Request introduces an architectural change or a significant new feature, the Tech Lead will take the role as the Code Reviewer and a `reviewers` on the Pull Request.
1. Code Reviewer will look at the code and make comments/suggestions
1. Code Reviewer will test the code in the CI environment to make sure the request features are implemented and no other regressions exist.
1. Code Reviewer will provide feedback on the Pull Request using the `Review Changes` feature.  The feedback should be in a single review and not several individual comments on the Pull Request.
1. The Code Owner will provide changes requested by the Code Review and answer all questions.
1. When Code Reviewer is satisfied the changes introduced by the Pull Request are of high quality, address the related issue and will not introduce new regressions, the Pull Request is approved.
1. The Code Owner merges the Pull Request.


## PR Approval Criteria

_WIP_

**Comment by swirtSJW** [comment]
Looks great Neil.    My only concern is if the code owner is responsible for merging... that is a lot of context switching to constantly rebase and wait for tests on the rebase...rinse repeat..  Even with Tugboat speeding up that process, it is still a lot of context switching and self prioritization.  One code owner merging theirs, means the others have to start back at square zero as far as testing.  With a bunch of developers it kind of gets like survival of the most attententive.  I'm hoping tugboat will resolve this... but our tests will still take 20+ min to run so I am not optimistic.

**Comment by acrollet** [comment]
@indytechcook @swirtSJW would it be possible to have tugboat do an automatic merge before building a PR environment if no conflicts are present?

**Comment by ElijahLynn** [comment]
> @indytechcook @swirtSJW would it be possible to have tugboat do an automatic merge before building a PR environment if no conflicts are present?

I think this will be possible, as long as we really trust our test suite and really trust that all the code is the right type of solution, not introducing hard-to-reverse technical debt.

**Comment by ElijahLynn** [comment]
> Looks great Neil. My only concern is if the code owner is responsible for merging... that is a lot of context switching to constantly rebase and wait for tests on the rebase...rinse repeat.. Even with Tugboat speeding up that process, it is still a lot of context switching and self prioritization. One code owner merging theirs, means the others have to start back at square zero as far as testing. With a bunch of developers it kind of gets like survival of the most attententive. I'm hoping tugboat will resolve this... but our tests will still take 20+ min to run so I am not optimistic.

Our next stage after Tugboat is to get parallelization working on the test suites, the ultimate goal is: "All tests run in under the time that the longest test takes to run". 

So if the longest test is 5 minutes, then all tests would be done in under 5 minutes. 

Martin Fowler's advice is that all functional, end-to-end tests are completed in under 10 minutes and unit tests are done in 1 minute.

**Comment by acrollet** [comment]
> I think this can be possible, as long as we really trust our test suites and really trust that all the code is the right type of solution, not introducing hard-to-reverse technical debt.

Agreed, and final review/approval should still be done on an up-to-date branch, I was just thinking that this would hopefully reduce the effort/context switching load placed on the issue author.

**Comment by indytechcook** [comment]
>  final review/approval should still be done on an up-to-date branch

We need to be careful about taking this as a hard-line stance.  There are risks with testing on non-up-to-date branches but they need to be measured against the risks of not being able to deploy code.

The needed workflow to fulfill always testing on an up to date branch would seem to be something like:

1. The "PR Coordinator" tells which a single developer they can test on CI and tells the Code Reviewer to test/review code.
1. All other PR testing/code review stops until the PR in the previous step is merged.
1. When the PR is merged, the "PR Coordinator" picks the next PR and return to step 1.

This might look a little extreme but it's the logical conclusion to only validation code on an up to date branch.  All testing and code review is invalid otherwise.

We need to have a balance and trust our engineers to make the right decision on when a merge should occur.

**Comment by oksana-c** [comment]
thanks to everyone who contributed to this conversation. Here are my thoughts ahead of our call:

> The Code Owner merges the Pull Request.  

we should be able to trust everyone in performing this action as long as the PR went through a review. We can address any risks by:

* defining github workflows that block merging if no “Approved” reviews are available
* communicating PR dependencies. Let’s add a section in the PR template that covers any dependencies on CMS or other teams. Example: We cannot release new content model to prod until FE is ready w/ updated templates/switches.

Utilizing PR status will help streamline our workflows. E.g. commit to setting PR to Draft if it’s not ready for review. Team-wide agreement to consider PRs ready for review if they are not set to Draft will help streamline our processes.

---

> Review code for quality passed upon Insert Spec Here?  

we need to formulate common standards to keep top of mind when introducing new code (doesn’t apply to config changes). E.g. code comment and code standards beyond common phpcs scans. Code Climate or other tools can be considered  to automate our code quality checks. This should substantially reduce the code review time as well.


---

**On roles:**

> Code owner:

Merging the Pull Request on Approval and test passing needs to read Merging the Pull Request when it's approved, test are passing and the PR meets a Definition of Done.

> Code reviewer

If a change introduced by a Pull Request contains an architectural change or a significant new feature, a Tech Lead and Product Manager (as needed) should be the Code Reviewer.

> Tech lead

The Tech Lead is accountable for the code quality and architecture practices of the CMS application. In respect to the code review process, the tech lead must be added as a Code Reviewer if a change introduced by a Pull Request contains an architectural change or a significant new feature.

> Product Owner

The Product Owner is the person who makes and prioritizes feature requests. This person is normally a part of VA/DEPO organization. The Product Owner is not directly involved in the Code Review process. The Product Manager makes a decision of whether the Product Owner should be brought in to review changes on the CI environment


> Product Manager

The Product Manager is a person on the CMS team who works with the Product Owner on defining feature requests and priorities. The Product Manager can participate in the Code Review process and be brought in to review changes on the CI environment as specified in User Story Acceptance Criteria. The Code Owner will keep the Product Manager up to date on status.

---

Let’s define next steps on our call.

**Comment by oksana-c** [comment]
Noting that this effort will culminate next week once the team had a chance to meet and iterate on the approach.

Removing Planned work label in Sprint 18 and will retag as Planned for Sprint 19.

**Comment by indytechcook** [comment]
Follow up issues to log:

- [ ] Create CodeOwners file with Core, Product and Devops teams.
- [ ] Use Github Actions to add lables/owners and reviewer groups based upon the code owners and created of the PR.

**Comment by indytechcook** [comment]
Follow up issue to evaluate code quality tools: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/3486

**Comment by indytechcook** [comment]
Follow up issue to auto assign reviewers based upon the PR author: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/3493
