### ISSUE TITLE
Update topic and audience term capitalization to sentence case

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#3175]
Capitalization requirements for Topics and Audience tags have changed and need to be reflected on production.

## Acceptance Criteria

- [x] Topics and Audience (Beneficiaries) vocabulary terms on production are updated to match capitalization below

Topics:
- Sign in
- Claims and appeals status
- Payments and debt

Audience - beneficiaries:
- All Veterans
- Former prisoners of war
- Gulf War Veterans
- Incarcerated Veterans
- Korean War Veterans
- LGBTQ Veterans
- Minority Veterans
- Native American Veterans
- Vietnam War Veterans
- Women Veterans
- World War II Veterans
- Family members and caregivers
- Service members

**Comment by oksana-c** [comment]
@bethpottsVADEPO , please confirm. thank you!

**Comment by bethpottsVADEPO** [comment]
This is perfect, thanks! @oksana-c

**Comment by acrollet** [comment]
@oksana-c ready for review.

**Comment by oksana-c** [comment]
confirmed. thank you @acrollet.
