### ISSUE TITLE
Alert paragraph AX improvement: "Remove" button should not be shown

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#3182]
## User story

As a content editor, who edits R&S pages, I should not be able to remove "Alert" paragraph while editing a page or a Step paragraph on the Step-by-step page.

## Description

Alert paragraph default value of "none"/`na` must exist in order for FE templating logic to conclude whether or not the alert component should be rendered.

Currently, the Alert paragraph offers a "Remove" button, where authors are able to remove the paragraph completely along w/ default value. 

It's important to preserve the default "none" for the Alert, so we must remove the "Remove" button on all R&S content types and components where `field_alert_single` is used.

<img width="1094" alt="Screen Shot 2020-10-15 at 7 30 07 AM" src="https://user-images.githubusercontent.com/16477724/96134010-5ce1b800-0eb8-11eb-88ce-3a708cd8fdd0.png">

## Acceptance Criteria

- [x] "Remove" button is not displayed for all instances of `field_alert_single` that reference "Alert (single)" paragraph type

Affected content types:

- [x]  Checklist
- [x]  Step-by-Step + Step paragraph
- [x]  Media list - Images
- [x]  Media list - Videos
- [x]  Q&A
- [x]  FAQ - multiple Q&As
- [x]  Learning Center Detail Page

## Implementation

* review DO Paragraph issue - [Hide "Remove" button if cardinality 1 (required) and only one allowed Paragraph type](https://www.drupal.org/project/paragraphs/issues/2919186) and verify that marking `field_alert_single` field as required, removes the button.
* if the above method failed validation - add custom logic for hiding "Remove" button option

**Comment by kaise-lafrai** [comment]
- Patch applied: https://www.drupal.org/files/issues/2020-05-13/hide_field_required_paragraphs_remove_button_1.patch
- field_alert_single set to required.
- Remove button is now removed.
