### ISSUE TITLE
Helpdesk Service Level Agreement (SLA)

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#3191]
## Description

Helpdesk should operate according to a Service Level Agreement (SLA) which lays out the terms and conditions of Helpdesk customer support efforts.

Under the SLA, the Helpdesk team commits to:
* respond to support requests within a set period of time
* resolve a minimum percentage of tickets within a set period of time
* track Helpdesk performance across key metrics
* other agreements.

## Acceptance Criteria

- [x] Helpdesk SLA is drafted and describes terms for customer support and key metrics that will be used to track [Helpdesk performance](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/3192)
- [x] SLA corresponds w/ our [contract agreement](https://drive.google.com/drive/folders/1s5exhXAdNC9phVlZMdOSZKydJ5myREul)
    - [x] monitoring 8am - 8pm ET
    - [x] resolving critical defects within 2 biz days

**Comment by MaggieBrazeau** [comment]
[https://app.zenhub.com/files/154174777/ef4a3c85-4375-4463-84cf-7b748a613d51/download](https://app.zenhub.com/files/154174777/ef4a3c85-4375-4463-84cf-7b748a613d51/download)

**Comment by MaggieBrazeau** [comment]
This is the current SLA document that needs to be reviewed: 

[https://app.zenhub.com/files/154174777/122a4b0a-de44-4913-bba3-4536daf66747/download](https://app.zenhub.com/files/154174777/122a4b0a-de44-4913-bba3-4536daf66747/download)

**Comment by MaggieBrazeau** [comment]
[https://app.zenhub.com/files/154174777/b930dc28-d60a-4cd9-9809-710775b4b10d/download](https://app.zenhub.com/files/154174777/b930dc28-d60a-4cd9-9809-710775b4b10d/download)
