### ISSUE TITLE
Establish Helpdesk performance tracking and reporting process

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#3192]
## Description

Helpdesk SLA establishes key performance metrics for the Helpdesk team, such as issue resolution rates, time to resolution, response time and others.
Visibility into each of these areas helps support team to identify gaps in knowledge base, processes, etc.

## Acceptance Criteria

- [x] definition, process and cadence for Helpdesk performance tracking and reporting is established and documented based on the [SLA](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/3191) (not actually creating first report)
- [x] reviewed w/ program team

**Comment by erogray** [comment]
I’ve drafted a report template (probably needs some prettifying with the A6 look & feel) and moved it into https://docs.google.com/presentation/d/18CiZDcctoiBaSrZQIsdHo_SIJ9fhU_jkX5SI6N3ajKs/edit#slide=id.p -- I think we can and should generate something like this on a weekly basis, and just export to PDF to provide the client, like: 
[VA-CMS-Drupal Reporting Template.pdf](https://github.com/department-of-veterans-affairs/va.gov-cms/files/5498510/VA-CMS-Drupal.Reporting.Template.pdf)

**Comment by erogray** [comment]
I've created a minimal process doc, https://docs.google.com/document/d/1RFvF90LNVj7S6hx0MRyp6NlijhMhH1gcxJ9oi-WxHAY/edit# — @oksana-c is this helpful?

**Comment by oksana-c** [comment]
@erogray , thank you. I added comments to the process doc. @cmaeng please review the doc and a list of suggested recipients (in a comment).

**Comment by cmaeng** [comment]
Program review has been completed for this. Probably good to do one last once changes have been incorporated before scheduling something with DEPO. cc: @erogray @oksana-c

**Comment by erogray** [comment]
@cmaeng the doc at https://docs.google.com/document/d/1RFvF90LNVj7S6hx0MRyp6NlijhMhH1gcxJ9oi-WxHAY/edit# should be done and ready for DEPO unless we hear otherwise

**Comment by daddison48** [comment]
@oksana-c @MaggieBrazeau should the review by depo be in a different story for next sprint?

**Comment by daddison48** [comment]
Moved DEPO Review and finalization to https://app.zenhub.com/workspaces/vagov-cms-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/3536
