### ISSUE TITLE
Helpdesk workflow for broken link incident resolution

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#3193]
## Description

Broken link incidents are currently handled by the engineering team. The process of triage and escalation reduces the time that the engineering team can spend delivering value. Helpdesk support team can alleviate the strain on the engineering team by taking over the process and only involving engineers when absolutely necessary.

## Acceptance Criteria

- [x] Helpdesk team is able to resolve broken link incidents
   - [x] Ero/Vanessa to schedule knowledge transfer from the engineering to helpdesk team
   - [x] Process for broken link incident tracking, triage, escalation and resolution is established and documented by Helpdesk team
   - [x] reviewed with DM/PM

**Comment by erogray** [comment]
thoughts:
1. can we automate broken-link alerts getting into Jira?
2. tracking in Jira: a broken-link label and report?

**Comment by oksana-c** [comment]
first knowledge transfer session is scheduled for Friday, 1/22

**Comment by erogray** [comment]
Process is drafted in https://docs.google.com/document/d/1s41l8-kQWzfII1QZMprQK5nUe-tArYQLx_2kaDJkjuM/edit#

**Comment by cmaeng** [comment]
The doc looks great! Made a few tweaks for clarity and closing this ticket out.
