### ISSUE TITLE
URL patterns config for R&S content types and taxonomy terms

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#3197]
## Acceptance Criteria

- [x] 1. Resources and support content URL patterns are set per the outline below
- [x] 2. all content that has been assigned new URL alias patterns is re-saved so as to apply new URL patterns without editor intervention
- [x] 3. Once content is published, URLs should not change even if the tag or H1 is modified. Any URL changes will need to be requested through the redirect process to ensure the change is vetted for any issues/conflicts and redirects can be put into place. 
- [x] 4. QraphQL and Content Export provide correct path alias for all entities of specified bundles (nodes and terms)

**Entity type/bundle**  | **URL pattern** |
--- | --- |
Landing page   | [node:title]  |
Checklist, Step-by-step, Media list- Images, Media list - Videos, Q&A, FAQ - multiple Q&As, Learning Center Detail page  | /resources/[node:title]/  |
"Learning Center Category" vocab taxonomy term  | /resources/[term:name]/   | 
Taxonomy terms: Topics, Audience - Beneficiaries, Audience - non-beneficiaries   | /resources/tag/[term:name]/  |

## Implementation

* connect w/ @swirtSJW to discuss AC 3 - locking the alias after first publishing. PW team mentioned that the same criteria was  already applied for VA Forms. Assumptions:
    * once the alias is generated for a node, the checkbox to automatically update alias per entity on save should be unchecked on per node basis
    * the AC 3 req `Once content is published` may not have been implemented for VA Forms - verify w/ @swirtSJW 
* hook_update runs prior to config import, so this task will need to be accomplished in two parts
    * part 1 - update alias config / deploy
    * part 2 - write hook_update to re-save all content of specified entity bundles to apply new alias patterns

**Comment by swirtSJW** [comment]
The  locking criteria of paths was discussed on VA forms but has not been implemented yet.  We will need a solution that can enact if for multiple content types.

**Comment by swirtSJW** [comment]
There are ramifications for taking this approach that need to be accounted for.  Locking these have the potential to create drift as these pages will not get updated if the pattern changes.  This is like a short term control situation that could create maintenance debt down the road.  It would be easy enough to hide the field after it has been published, but making it so it is permanently locked in place is a bit more dramatic.  Likely an unnecessary risk if we could just gain acceptance of treating redirects like content and building them as part of the front end content.

**Comment by ethanteague** [comment]
Per scrum today: 2 step process:
1) Release path pattern for learning center to prod, and then bulk update LC types (only) in alias ui (assuming ui allows for content types restriction, otherwise will need to be an update hook)
2) Create logic after #1 is complete to uncheck the alias update box on lc nodes after first publish.

**Comment by swirtSJW** [comment]
@oksana-c @kevwalsh  I am trying to interpret AC #3

> Any URL changes will need to be requested through the redirect process to ensure the change is vetted for any issues/conflicts and redirects can be put into place.

We don't have a role for that.   Are we just leaving the form widget visible for content-admin and admin?

**Comment by oksana-c** [comment]
> Are we just leaving the form widget visible for content-admin and admin?

👍 yes. Permissions for aliases are already in place.

<img width="1683" alt="Screen Shot 2020-10-30 at 4 50 21 AM" src="https://user-images.githubusercontent.com/16477724/97696612-731c7600-1a6b-11eb-96d8-a51714f38e4a.png">
