### ISSUE TITLE
Framework for running post deploy actions w/ bootstrapped Drupal

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#3202]
### User Story or Problem Statement

As an engineer, who needs to run content updates immediately after new configuration is deployed to production, I need to have a process that allows me to accomplish multi-stage updates in one deployment.

### Affected users and stakeholders

* CMS engineers

Similar need was identified just recently in #3196 

### Hypothesis

We believe that having a process that runs after a successful deployment (post live) will let us cover various use cases that often arise in our engineering practice.

### Assumptions
* Tk
* Tk

(How will these assumptions be validated?)

## Acceptance Criteria
* Testable_Outcome_X
* Testable_Outcome_Y
* Testable_Outcome_Z

## Runbook  
This is particularly relevant for feature launches, or for making changes to the content model that require front end changes as well.
1. Step_to_get_to_production_X  
1. Step_to_get_to_production_Y
1. Step_to_get_to_production_Z

**Comment by jefflbrauer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VAgov-CMS-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/3202?planning-poker) with ZenHub @ElijahLynn @indytechcook @ndouglas @olivereri @timcosgrove

**Comment by jefflbrauer** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VAgov-CMS-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/3202?planning-poker) with ZenHub @cweagans
