### ISSUE TITLE
E2E test coverage

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#3215]
### User Story or Problem Statement

As a CMS Engineer, I need to have comprehensive functional test coverage, so that I can be confident that new functionality I develop does not cause regressions.

### Affected users and stakeholders

* CMS Engineers
* CMS Users (indirectly)

### Hypothesis

_A hypothesis may depend on a spike ticket to be completed._

We believe that _this_solution_ will achieve _this_outcome_. We'll know that to be true when _this measurable outcome occurs._

**Comment by jefflbrauer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VAgov-CMS-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/3215?planning-poker) with ZenHub @ElijahLynn @indytechcook @ndouglas @olivereri @timcosgrove

**Comment by jefflbrauer** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VAgov-CMS-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/3215?planning-poker) with ZenHub @cweagans
