### ISSUE TITLE
Spike: release notes process

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#3219]
## Description

**Goal:** transition away from a single person dependency in our Release notes process.

The release notes process is for the most part shaped. Now we need to think how to incorporate it in day-to-day workflow.

Outcomes: https://docs.google.com/document/d/1B6_RX-imJIGK-XJEBelg3R-h8M3KijDPpjdNvvQw010/edit#

## Acceptance Criteria

- [x] discuss a process for integrating release notes into our day-to-day workflows
- [x] identify any guidelines that need to exist and define how guidelines are shared within the team
- [x] brainstorm and document in user stories any potential integration touchpoints, e.g. automation via PRs, email / CMS notification automation. Epic https://github.com/department-of-veterans-affairs/va.gov-cms/issues/871 is refined
- [x] identify an MVP for release notes process as well as long-term goals
- [x] resulting backlog is documented - refinement is not an expectation

Spike participants:
@ElijahLynn (for automation needs/ideas) @oksana-c @kevwalsh @ndouglas @indytechcook

**Comment by oksana-c** [comment]
scheduled on Oct 27 12pm ET (60mins)

**Comment by rachel-kauff** [comment]
Mostly done, just waiting on Oksana to add the user stories.

**Comment by oksana-c** [comment]
tagged resulting stories in the [outcomes doc](https://docs.google.com/document/d/1B6_RX-imJIGK-XJEBelg3R-h8M3KijDPpjdNvvQw010/edit#)
