### ISSUE TITLE
Submit *.cms.va.gov DNS zone delegation request in Active Directory

### ISSUE THREAD

**Issue by ElijahLynn** [department-of-veterans-affairs/va.gov-cms#3228]
Refactor proposal:

No longer seeking to request VA Gov Domain Infrastructure team create records in VA DNS. Rather, delegate the entire zone to us, and we manage the records in AWS Route 53.

AC:
- [x] Submit [Change Request](https://yourit.va.gov/change_request.do?sys_id=e39fd3d71b8c209419da873fe54bcbbf&sysparm_record_target=change_request&sysparm_record_row=1&sysparm_record_rows=1&sysparm_record_list=active%3Dtrue%5EnumberSTARTSWITHCHG0142686%5EORDERBYDESCnumber) with Domain Infrastructure Team to delegate *.cms.va.gov zone.
- [x] Speak with Dale Lewis (DI Lead) about Zone Delegation
- [x] Create Github Issues to write Terraform Code to manage Route 53 Private Hosted Zone.
  - [x] Migrate existing domain names to R53        https://github.com/department-of-veterans-affairs/va.gov-cms/issues/3363  
  - [ ] Clean up Bind Server records.
  - [x] Create Tugboat/CI DNS records.

**Comment by olivereri** [comment]
Refactor proposal:

No longer seeking to request VA Gov Domain Infrastructure team create records in VA DNS. Rather, delegate the entire zone to us, and we manage the records in AWS Route 53.

AC:
- [ ] Submit Change Request with Domain Infrastructure.
- [ ] Speak with Dale Lewis about Zone Delegation
- [ ] Create Github Issues to write Terraform Code to manage Route 53 Private Hosted Zone.
  - [ ] Migrate existing domain names to R53
  - [ ] Create Tugboat/CI DNS records.

**Comment by ElijahLynn** [comment]
Update: This is currently submitted and Eric has been coordinating with the Active Directory team to execute this soon.
