### ISSUE TITLE
Make it easier to link to a VA form detail page and/or PDF

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#3232]
## User Story or Problem Statement

There are hundreds, possibly thousands, of PDF forms being re-uploaded to the CMS, when there is a single source of truth for Forms at VA (the Form database, which is consumed by the VA Forms product int he CMS)

As a CMS editor, i want to provide a link to an existing form, without having to add it to the CMS and risking it becoming out of date or duplicative, or search through existing PDFs that have been uploaded and renamed by other CMS editors.. 

As a Veteran who prefers online tools, i want to be able to use a digital tool when one exists, instead of a PDF form. 

As a Veteran, i want the official PDF for a form, not an old version.
* Data to support this problem: Variations on form 10-2850 have been uploaded dozens of times as of Feb 2022

<details><summary>Screenshot</summary>

<img width="1030" alt="PDF_Audit___VA_gov_CMS" src="https://user-images.githubusercontent.com/643678/154179096-c53c4339-79fe-42cf-a2a1-e8096354a48d.png">

</details>

As VA, i want Veterans to use digital tools when possible so that we can be more efficient and create better experiences for Veterans.

## How might we solve these user stories?

Some ideas
1. Design a form teaser component (or set of components?) that provides the optimal Veteran experience for a form download, digital tool link. 
2. Provide a means of adding a link to a VA form as a content block, or possibly from a rich text editor.

## ACs

TBD

**Comment by jilladams** [comment]
Online forms now has a contract team. 
PDFs are mastered in the Forms DB and folks should be linking to the Form page, not the pDF itself, wherever possible, per content guidance. I think this is a no-op. Closing.
