### ISSUE TITLE
Spike: E2E testing coverage

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#3245]
## Description

The CMS team is interested in having E2E test coverage to ensure consistent function of our platform.
The Facilities team has E2E testing on their roadmap for Q4. As we discuss the CMS strategy for E2E, we need to consider whether and how we may combine our E2E efforts w/ that of the Facilities team and others and flag any potential points of integration / risks that may arise.

## Acceptance Criteria

- [x] define the meaning of E2E tests for the CMS team [discussion - all] - **[Spike call notes](https://docs.google.com/document/d/1j3jblJSPWx9DK0oZWF0vShw8jhl9JHzTMF1N7ziBfOk)**
- [x] initial brainstorm tools/testing frameworks that we may want to start using and use cases - **separate story #3418** 
- [x] flag any points of overlap / risks when integrating w/ other team's testing suites - **CMS infrastructure and a system of dependencies on other repos/build processes do not yet offer a streamlined method for integrating w/ other teams for E2E testing**
- [x] generate initial backlog if we're at a point in a conversation where we know what next steps we need to take in E2E initiative - **new stories tagged in [doc](https://docs.google.com/document/d/1j3jblJSPWx9DK0oZWF0vShw8jhl9JHzTMF1N7ziBfOk)**

participants:
@ElijahLynn @indytechcook @acrollet @swirtSJW @oksana-c @ndouglas [please add yourself here if interested]

**Comment by ElijahLynn** [comment]
I think @ndouglas is interested too.

**Comment by oksana-c** [comment]
notes doc and follow-up comment are posted inline w/ ACs
