### ISSUE TITLE
Enable Performance based core modules

### ISSUE THREAD

**Issue by indytechcook** [department-of-veterans-affairs/va.gov-cms#3246]
Currently, the `dynamic_page_cache` and `bigpipe` modules are currently not enabled.  We should enable these.

AC
- [ ]  Evaluate the `dynamic_page_cache` and `bigpipe` to see if performance is increased or decreased using blackfire and post results in comments.
  * pages to evaluate: login page, user profile (/user), node view/edit, /content
  * environments: any, as long as before/after is compared on the same env.
- [ ] review dblog and browser console (js) for errors and review most common pages in CMS for any regressions 
- [ ]  Enable and configure `dynamic_page_cache` and `bigpipe` if the evaluation is seen to improve performance.
   - [ ] QA on CI env (2 engineers)
- [ ] Review the user profile PHP unit performance test for improvement

**Comment by ndouglas** [comment]
Recording so that we (mostly I) don't forget how it was that we got authenticated requests working with Siege:

1.  Log in to Lando.  Open the developer console, switch to the Application panel, then Cookies, then take note of the `SESS*` key and value and the SimpleSAMLSessionID key and value.
2.  Use these in the Siege cookie header like so: `siege -c 1 -R ./siegeconfig http://va-gov-cms.lndo.site/node/2/edit --header="Cookie: SESS0c48c374f11807393600f10c3ce1a6a=bGbgZphsKx6-Ws0OYwREDvFxq9Zc6UKucPMVDNi8Pc; SimpleSAMLSessionID=8a3a9591232c939c7cfca61aa4411fe; path=/; HttpOnly" -v`.

**Comment by acrollet** [comment]
Initial results for `/node/2/edit`:

no cache enabled:

```
Transactions:		          25 hits
Availability:		      100.00 %
Elapsed time:		       20.11 secs
Data transferred:	        0.96 MB
Response time:		        0.80 secs
Transaction rate:	        1.24 trans/sec
Throughput:		        0.05 MB/sec
Concurrency:		        1.00
Successful transactions:          25
Failed transactions:	           0
Longest transaction:	        1.40
Shortest transaction:	        0.74
```

Dynamic page cache enabled:

```
Transactions:		          25 hits
Availability:		      100.00 %
Elapsed time:		       12.95 secs
Data transferred:	        0.96 MB
Response time:		        0.52 secs
Transaction rate:	        1.93 trans/sec
Throughput:		        0.07 MB/sec
Concurrency:		        1.00
Successful transactions:          25
Failed transactions:	           0
Longest transaction:	        0.94
Shortest transaction:	        0.47
```

**Comment by acrollet** [comment]
Lighthouse timings for `/node/2/edit` with dynamic page cache, css & js aggregation enabled, 3 runs:

without BigPipe:
```
First Contentful Paint: 0.9,0.9,0.9
Time to Interactive: 0.9,0.9,0.9
```

with BigPipe:
```
First Contentful Paint: 0.9,0.8,0.8
Time to Interactive: 1.0,0.9,0.9
```

**Comment by acrollet** [comment]
Digging into this a bit more, BigPipe makes a huge subjective difference when viewing nodes with un-cached node link reports. (Any page that hasn't been edited or viewed for more than 24 hours) When viewing nodes with BigPipe enabled, the page is viewable and interactive in under a second, vs. 5+. To see this in action, enable BigPipe and view /health-care after removing the node link report cache:

`DELETE FROM cache_default WHERE cid = 'node_link_report_67';`

This difference is also very apparent when editing pages, as the form re-renders within ~3 seconds instead of ~9 seconds. (The node link report is re-generated every time a node is edited)

I've noticed an issue with the admin toolbar, which isn't made 'sticky' until all rendering is complete. Looking into that...

**Comment by acrollet** [comment]
I've created a draft PR with dynamic page cache and BigPipe enabled for other team members to evaluate. I spent some time looking into core patches and contrib solutions for the 'flickering' done on page load, but none provide a complete solution with BigPipe enabled. The flickering does currently exist, but it's exacerbated by the sometimes lengthy wait between when the page is first viewable and when dynamic content finishes loading, at which point the page "jumps". I added some CSS as a workaround that ameliorates the issue, I decided that it wasn't worth spending further time when we're looking to move away from seven.

**Comment by acrollet** [comment]
@hie1 @jordanamello roping you in for a mini UX review on the behavior change this PR introduces.

Previously, rendering for all components on the page had to happen during the main page request, meaning that page loads could take a while when the link check report needs to run. This manifests as a lengthy page load:

![without_bigpipe_optimized](https://user-images.githubusercontent.com/101649/100643933-e843cb00-32f7-11eb-9643-fb8d8bd24b51.gif)

(Yes, that's animated! Wait for it...) You'll also notice the "flicker" as the main page content pushes down after the page fully loads.

With the changes, the page loads quite quickly, and the link report appears several seconds later after it has run:

![with_bigpipe_optimized](https://user-images.githubusercontent.com/101649/100644183-38bb2880-32f8-11eb-960e-2395a1f30783.gif)

You'll notice the toolbar change color at the end as well - I've changed the default color for the toolbar to match prod, so live users won't see that particular behavior.

So, I'm hoping for your input on these changes. My personal preference/assumption is that having the page ready to work with so much more quickly is a significant usability improvement, and we can live with the odd behavior of the link report popping in later. (I am planning on opening a follow-up to improve that UX based on our findings with the Claro evaluations, it would make sense to me to have a placeholder with a loading behavior of some kind while the checker runs) However, I'm deferring to your expertise, and whether we should block this issue on improving the link checker UX. Thanks!

**Comment by acrollet** [comment]
Verifying various custom JS functionality with bigpipe:

**Audience & Topics JS:**

<img width="453" alt="Screen Shot 2020-11-30 at 4 54 14 PM" src="https://user-images.githubusercontent.com/101649/100679453-c4e74300-332c-11eb-9861-697dfe9f529a.png">

**Phone Extension field JS:**

Shown for type "phone":

<img width="371" alt="Screen Shot 2020-11-30 at 4 55 23 PM" src="https://user-images.githubusercontent.com/101649/100679485-d92b4000-332c-11eb-9c60-a45a57996bd4.png">

Hidden for other types:

<img width="306" alt="Screen Shot 2020-11-30 at 4 56 25 PM" src="https://user-images.githubusercontent.com/101649/100679565-fd871c80-332c-11eb-85fb-49c50028b752.png">

**Service Location Address:**

<img width="828" alt="Screen Shot 2020-11-30 at 5 00 07 PM" src="https://user-images.githubusercontent.com/101649/100679795-830acc80-332d-11eb-86a1-26c030883d83.png">

**Comment by acrollet** [comment]
@jordanamello and I just spoke about the "pop-in" behavior of status messages with BigPipe enabled. She believes that it's worth prioritizing a "loading" placeholder for the status messages + link report to lower the surprise factor and avoid users scrolling down and not knowing there are issues with links. I'm researching if a solution is available in contrib.

**Comment by acrollet** [comment]
Here's a look at the placeholder solution I've come up with. (Without looping, reload to "re-play" it...) Please let me know what you think... (For what it's worth the animation looks much nicer on the page than the low frame-rate gif!)

![bigpipe_with_placeholder](https://user-images.githubusercontent.com/101649/100804381-00941280-33ea-11eb-8e18-9323c992e835.gif)

**Comment by acrollet** [comment]
@hie1 @jordanamello @oksana-c here's the updated placeholder:

![bigpipe_drupal_placeholder](https://user-images.githubusercontent.com/101649/100909883-7a7bd880-348a-11eb-80fa-c3cb1ae137b2.gif)
