### ISSUE TITLE
[EPIC] [Events] Ability to create all-day, or multi-day, events

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#3247]
### User Story or Problem Statement

As an event creator and editor, i want to create events that span a full day, or even multiple days, such as conferences. 

### Affected users and stakeholders

* VAMC system editors
* Outreach Hub editors

### Priority 
Recurring events shipped 6/6/22. To determine whether this project is a priority, we should collect data on use cases and needs around all-day events, e.g. how many events would preferably be all day? Dave's direction 6/10/22: Let recurrence bake, do an audit, decide if this is a priority based on data.

**Comment by jilladams** [comment]
Added notes re: priority to ticket body based on today's scrub with Dave.

**Comment by FranECross** [comment]
Removed Frontend fix: Events that cross midnight should show the day & date of the event end time #9377, and am closing as done. The ticket above will be linked with a new epic to be created: [EPIC] [Future State] Events v3
