### ISSUE TITLE
Investigate why Grafana/Prometheus is showing downtime just after deploys

### ISSUE THREAD

**Issue by ElijahLynn** [department-of-veterans-affairs/va.gov-cms#3253]
Current downtime is measured in a once a minute script that returns a failure if prod.cms.va.gov does not return a 200 within 5 seconds. 

Possible issues discussed:
- Could be returning a 503 during/after deploy (if this is true, create a new issue for this) (doesn't seem to be the case, or if it is, the script is still counting it as a success)
- CMS Export is running just after deploy, causing responses to be longer than 5 seconds.

AC:
- [ ] No downtime shown/tracked when site is in deploy mode during a deployment in Grafana.

Tasks:
- [x] Set the User-Agent on request header
- [x] Set the deploy mode to check for a request header of User-Agent: curl.* (User-Agent: curl/7.61.1)

![image](https://user-images.githubusercontent.com/1504756/96786935-cde80a80-13a5-11eb-8b4e-8f37c5ba62a8.png) (the small gaps don't actually say 0, but say 1 (success) and is by design in the chart, this indicating no downtime, the big gap says 0 though which is during the export) This image is for a 15 minute deploy window. 

http://grafana.vfs.va.gov/d/dxf8a-6Zz/cms-dashboard?orgId=1&from=1603308563841&to=1603309484082&var-datasource=Prometheus%20(Utility)&var-environment=prod&var-app_name=cms&var-region=us-gov-west-1

**Comment by ElijahLynn** [comment]
Got some good data on this right now:

I just did a manual "live deploy" job which normally runs after deploy, but failed earlier, so I replayed it around 12:46pm PT. Deploy finished at 12:39pm PT, for reference in the screenshots. I monitored server load through grafana and refreshed the login page (same as uptime check) and throughout all the requests never had a single one take longer than 1 second (and this is through a proxy tunnel too) and the majority where under 50ms. So the hypothesis that the CMS Export process could have been slowing things down is not validated. 

Which leads me to believe that it is something to do with the site being in deploy mode or the site alert functionality, which is still up when the export job (CMS Live) is run. I'll test that now on CMS-TEST. 



![image](https://user-images.githubusercontent.com/1504756/98596683-a1306000-228c-11eb-9c08-ce5ce1d683bc.png)
![image](https://user-images.githubusercontent.com/1504756/98596689-a2fa2380-228c-11eb-94d0-60b13ea35eb9.png)

**Comment by ElijahLynn** [comment]
K, I was mis-reading the chart. It is happening during deploy and the site deploy mode is what causes this, as it returns a proper 503 Service Unavailable response code. 

I think we should do this:
1. Set the deploy mode to check for a request header of `User-Agent: curl.*` (User-Agent: curl/7.61.1)


![image](https://user-images.githubusercontent.com/1504756/98732663-4bbf8600-2354-11eb-9b5c-15db30d9dcf5.png)

**Comment by ElijahLynn** [comment]
[Discussed](https://dsva.slack.com/archives/CT4GZBM8F/p1605041885466300) with @indytechcook and we are going to change the request header to `User-Agent: curl-prometheus-check` and set the deploy mode to look for that header and respond with a 200.

**Comment by indytechcook** [comment]
I'm working on the Drupal side this morning and should have a PR up today.

**Comment by indytechcook** [comment]
PR created: https://github.com/department-of-veterans-affairs/va.gov-cms/pull/3464

**Comment by ElijahLynn** [comment]
This has been deployed on the Prometheus side and we now have the new User-Agent coming in: 
![image](https://user-images.githubusercontent.com/1504756/99122077-8161aa80-25b2-11eb-82d1-187776619f35.png). We discussed on Slack and are going to let the deploy Monday push out #3464 (merged after deploy window) today.

**Comment by ElijahLynn** [comment]
W00t! We now have a 24 hour window that isn't showing scheduled deploy as downtime. 

![image](https://user-images.githubusercontent.com/1504756/99697034-2d3c4780-2a44-11eb-94a4-591bb98314bd.png)
![image](https://user-images.githubusercontent.com/1504756/99697048-3200fb80-2a44-11eb-8a94-84bfb29f3fb2.png)
