### ISSUE TITLE
R&S authors can quickly access article lists by tag [UX]

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#3264]
## User Stories

As an RS editor, I can access a list of all tags and categories pertaining to RS product, so I can have a quick link for accessing "All articles in <tag>" listings.

As an RS editor, I can see the number of articles tagged w/ each tag when I'm viewing tag listings.

other stories related to perusing RS tags TBD

## Description

Currently, users can access article lists by tag only when they are viewing a node page and see a tag link.
Users should be able to find a list of all tags without having to click thru to see an article.

Let's explore options: via dashboard, etc.

We have 3, soon to be 4 different taxonomy vocabularies populated with terms that users are using for tagging R&S articles:
    * Category
    * Topics
    * Audience - beneficiaries
    * Audience - non-beneficiaries

## Acceptance Criteria

- [ ] Problem space is understood.
- [ ] UX for accessing article lists by tag is defined in a prototype.
- [ ] Prototype is validated with stakeholders and feedbacks incorporated.

**Comment by FranECross** [comment]
Closing old iceboxed ticket.
