### ISSUE TITLE
Content model and editorial experience for nationally-controlled VAMC System Policies Page content

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#3276]
### Nationally-standardized VAMC content fields

Policies top task page  https://prod.cms.va.gov/centralized-content/15588/vamc-system-policies-page
- [x] "Intro text" 
- [x] "Top of page content"
- [x] "VA general visitation policy" 
- [x] "Bottom of page content"

### Findability

- [x] Some means of finding and editing this content has been established. 
https://prod.cms.va.gov/admin/content?title=&type=centralized_content&moderation_state=All&owner=All

![image](https://user-images.githubusercontent.com/5752113/104674605-eec4b100-56b1-11eb-8262-3d32dfda7e02.png)

### Governance

- [x] Some means of restricting editing to members of a certain section (eg "Nationally-standardized VAMC content").
![image](https://user-images.githubusercontent.com/5752113/104674811-43682c00-56b2-11eb-99a9-8348d9dc77a7.png)

### Editorial experience

- [x] Some means of providing contextual information that helps editors make good content design decisions.   
   - [x] General guidance structure for the content as a whole.  (specific wording not finalized) 
![image](https://user-images.githubusercontent.com/5752113/104675182-f59ff380-56b2-11eb-8a01-fbb89adcd9c6.png)

   - [x] Content is in the right order. as related to how it will appear on final pages.
   - [x]   Field level guidance exists.  Additional field level guidance will be added. in the future as part of another issue as the text needs refining AND the this guidance needs to be locked for general editors and only editable by admins.  This will be covered here https://github.com/department-of-veterans-affairs/va.gov-cms/issues/4016
![image](https://user-images.githubusercontent.com/5752113/104675329-4dd6f580-56b3-11eb-8e58-26dac452def8.png)

**Comment by swirtSJW** [comment]
I am calling this one done.

**Comment by kevwalsh** [comment]
Removing "and editorial experience" from the title and moving to another issue, we'll need an iteration on that aspect.
