### ISSUE TITLE
Post training video and user guide for VAMC System Policies Page

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#3277]
### User Story
As a VAMC editors, I need to know how to edit Policies to provide a Veteran-centered experience on VA.gov.

### Acceptance Criteria
- [x] materials drafted
- [x] materials PO reviewed
- [x] materials finalized
- [ ] materials posted on CMS help center

**Comment by xiongjaneg** [comment]
Waiting for timing on creation of each system's page. Editors won't be able to practice until they have a page created for their system.

**Comment by xiongjaneg** [comment]
video link for posting on CMS help center: https://youtu.be/Noj9q8uL8RY

**Comment by xiongjaneg** [comment]
waiting for policies pages to be created
