### ISSUE TITLE
Training module for VAMC System Policies Page for VAMC local editors

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#3278]
### User Story
As a VAMC editor, I need to be able to edit policies so Veterans can have consistent, Veteran-centered information.

### Acceptance Criteria
- [x] draft storyboard
- [x] review storyboard

**Comment by xiongjaneg** [comment]
Kev reviewed 3/24/21. Sent to Dave for 3/25/21 for review via Slack.
