### ISSUE TITLE
"Q&A group" paragraph content model update

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#3283]
## Description

Q&A group paragraph content model updates requested by @jenniferlee-dsva on Oct 23rd.

/admin/structure/paragraphs_type/q_a_group/fields

## Acceptance Criteria

- [x] field_section_header is optional
- [x] `field_accordion_display` "Display this set of Q&As as a group of accordions." is added immediately below the section heading. 
   - [x] Field storage settings, form display and node display settings match the same field that is attached to "Q&A Section" paragraph /admin/structure/paragraphs_type/q_a_section/fields
- [x] spec tool is updated

**Comment by jenniferlee-dsva** [comment]
confirming the above ACs - ty! 

clarification - just bc I do not know the technical field structure - the answer wisywig in the LC FAQs must have the 1000 includ spaces character limit and be limited rich text (no tables, no videos, images, number call outs) with the current optional alert capability.   <-- these are different from benefit hub question group component, so wanted to triple confirm that we are only bringing over the `optional section header ` and `enable/not enable accordions `capabilities.

**Comment by oksana-c** [comment]
> wanted to triple confirm that we are only bringing over the `optional section header ` and `enable/not enable accordions `capabilities.

correct

**Comment by kaise-lafrai** [comment]
@oksana-c QA steps coming soon. Ready for review.

**Comment by oksana-c** [comment]
thanks @kaise-lafrai . merged ✅

**Comment by oksana-c** [comment]
@ncksllvn @kelsonic 
heads up - the content model update for Multiple FAQ template that is described in this issue will be deployed in the afternoon tomorrow.
please ensure that the new field `field_accordion_display` has corresponding logic in FE templates.

If `field_accordion_display` = TRUE, Q&As within a group should be rendered in accordion.

<img width="1082" alt="Screen Shot 2020-10-26 at 4 29 24 PM" src="https://user-images.githubusercontent.com/16477724/97235585-c4e1a980-17a8-11eb-8f33-a902e889b0d4.png">

cc @jenniferlee-dsva @brianalloyd
