### ISSUE TITLE
Design a VFS Product debt management process 

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#3286]
## Description

Each product managed in the CMS has some product debt, including technical and UX debt, some more than others. DEPO POs need to understand the tech debt to make prioritization decisions. Some product tech debt cuts across multiple products 

## Acceptance Criteria
- [ ] We have a shared product debt catalog visible to DEPO product owners 
- [ ] We have an a defined objective for tackling debt, and a means of budgeting time to move the needle on that objective.

**Comment by EWashb** [comment]
This is no longer appropriate as VFS CMS is its own platform/team and there are other product teams with their own teams and processes
