### ISSUE TITLE
Audit (and potentially fix) content that has used the Entity Embed WYSIWYG tool

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#3293]
Based on a quick audit October 26, there are only two nodes that contain `data-entity-embed` in their latest revision. They are Node 286 and 777. Both could easily have their pdf links replaced by "Link to file or video" content blocks.

This would allow #3294 to proceed. 

This drupal view (not in code) should show any existing rich text fields that contain  `data-entity-embed` in their latest revision... it does not show older revisions. 
[views.view.audit_embedded_media_in_rich_text_fields.yml.txt](https://github.com/department-of-veterans-affairs/va.gov-cms/files/5438845/views.view.audit_embedded_media_in_rich_text_fields.yml.txt) (remove `.txt` from file name then import)

ACs
- [x] Audit shows all uses of `data-entity-embed` (see first comment below)
- [x] What content types are using this? Event, Detail Page, VAMC System Health Care Service
- [ ] If there are nodes that are not detail pages, do we need to solve for those? recommendations below. 

Possible ACs
- [ ] No nodes have embedded entities in rich text fields in their latest revision
- [x] Stretch: no nodes have embedded entities in rich text fields in their revision history
- [x] If any nodes are outside of Pittsburgh, please note it and we will followup with those editors. 
  - no nodes have this outside of Pittsburgh

**Comment by kevwalsh** [comment]
@davidconlon   

I did some digging with SQL queries for `data-entity-embed`, which shows up when an editor has used the entity embed button. 

All uses were with content with managed by VA Pittsburgh health care

## node/5676 - Introduction to Whole Health (Event)

![__Introduction_to_Whole_Health___Veterans_Affairs.png](https://images.zenhubusercontent.com/5d6e57ad330f64311395f08b/6e5da16c-c9f9-4b50-a8b9-54b14c96c633)

Recommendation: 

1. remove this link (and archive event?) 
2. Consider supporting PDFs in event content types (low priority?)

## node/346 - Vocational rehabilitation and employment programs at VA Pittsburgh health care (System health service)

See Vocational service accordion on https://www.va.gov/pittsburgh-health-care/health-services 

![VA_Pittsburgh_Health_Care___H__John_Heinz_III_Department_of_Veterans_A.png](https://images.zenhubusercontent.com/5d6e57ad330f64311395f08b/01a62382-2c92-442b-9786-16aefc00d055)

Recommendation: 
1. Remove link
2. Work with Pittsburgh PAO to find an alternative to this. A detail page? 

## node/777  - Water Quality monitoring (Detail page)

https://www.va.gov/pittsburgh-health-care/water-quality-monitoring-and-reports/ 

![VA_Pittsburgh_Health_Care___Water_Quality_Monitoring_and_Reports.png](https://images.zenhubusercontent.com/5d6e57ad330f64311395f08b/d25e287c-edb5-4aee-bd6f-f027a5cf2bd7)

Note that this one also links to files at www.pittsburgh.va.gov, which don't work, and just redirect to www.va.gov/pittsburgh-health-care. 

Recommendation: switch to the Downloadable file component for the first two links. Figure out with Pittsburgh PAO what to do about the two links to www.pittsburgh.va.gov




## node/293 - Human research (Detail page)

https://www.va.gov/pittsburgh-health-care/research/safety-security/human-research/

![VA_Pittsburgh_Health_Care___Human_research.png](https://images.zenhubusercontent.com/5d6e57ad330f64311395f08b/49bdcf8f-3e05-4eec-aa60-1864ab18afa3)

Recommendation: switch to the Downloadable file component.

## Recommendation for next steps:

1. We fix this content directly. 
2. Consider working with Pittsburgh PAO on alternatives for Vocational accordion content. 
3. We consider adding PDF support for Events (probably not a high priority, but we can put it in the icebox).

**Comment by davidconlon** [comment]
- Whole health event is old (can be archived?) we can remove PDF
- Voc Rehab flyer PDF can be removed. The information is above in the bullets. This should be replaced by a repeating event but we don't have those yet.
- Human research - we should update page on their behalf.
- Water Quality monitoring we could update ourselves, but I'm not sure what this content is/should be if we're being redirected?

Thoughts?

**Comment by kevwalsh** [comment]
@davidconlon I did some searching and these PDFs on https://www.va.gov/pittsburgh-health-care/water-quality-monitoring-and-reports/  don't see to be around any more on the public web.  and it doesn't look like any other modernized VAMC site has these pages. 

![VA_Pittsburgh_Health_Care___Water_Quality_Monitoring_and_Reports.png](https://images.zenhubusercontent.com/5d6e57ad330f64311395f08b/e17c7578-2e59-45cd-82cb-c20b39a4be33)

Our team can go ahead and fix those first 3.5 issues, this latter one is not really a dependency to finish out this epic. Not sure who should own this.
