### ISSUE TITLE
R&S dashboard subpages - content listings

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#3296]
## Description

R&S dashboard has 7 distinct content types that need to have their own listing pages. 
Q&A listing has been defined [here](https://xd.adobe.com/view/5cd15a8f-426d-4356-b81e-82920dd688be-0982/?fullscreen), but may need to be iterated upon once other content listings are defined.

**Consideration**: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/3264 - articles will have various tags. Tags browsing experience may affect the information presented on content listings.

## Acceptance Criteria

- [ ] Needs and specificities of each subpage are identified. 
- [ ] interactive prototype depicting R&S dashboard subpages (content listings) is available and describes the following components
    - [ ] various content listings with relevant filters and sort defaults
    - [ ] navigation that allows the user to get to other dashboard subpages
    - [ ] "add new" links/buttons
    - [ ] UX writing to inform the user of possible actions or any relevant context
  - [ ] technical feasibility assessed in colab w/ @oksana-c 
  - [ ] initial round of user feedback w/ PW R&S content authors

**Comment by FranECross** [comment]
Closing old iceboxed ticket.
