### ISSUE TITLE
Design: "Where does this Q&A appear on VA.gov?" UX iteration

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#3298]
## Description

It was hoped that Q&A view and edit pages will display all titles where the current Q&A is used - https://xd.adobe.com/view/5cd15a8f-426d-4356-b81e-82920dd688be-0982/screen/581373e3-0d3f-4dc9-ad0c-1d62d56182be?fullscreen
We need to revisit scalability and UX of the titles listing section.

## Additional Information
Danielle T responded (comment below):  I think this would be a very helpful enhancement. It would be helpful for content authors/edits to understand the context in which a Q&A is being used when they go to edit it. And longer-term, it will help us track how much specific Q&As are being used and where to make content strategy decisions. 

## Acceptance Criteria

- [ ] concept for the "Where does this Q&A appear on VA.gov?" is refined: UI + UX writing 
- [ ] technical feasibility is reviewed w/ engineer
- [ ] prototype for the "Where does this Q&A appear on VA.gov?" is finalized

**Comment by wesrowe** [comment]
@DanielleThierryUSDSVA, PW was just made aware of this Editor experience enhancement that was proposed in 2020. Have you seen it before? Do you think it would be a helpful enhancement to your team?

cc: @aklausmeier @thejordanwood @cindymerrill

**Comment by FranECross** [comment]
Fran will follow up with Danielle on this item.

**Comment by FranECross** [comment]
@DanielleThierryUSDSVA I'm reviewing and following up on tickets in our backlog. Will you please review Wes's last comment and give your thoughts? Maybe you and he had a convo outside the ticket.... :) Thanks!

**Comment by DanielleThierryUSDSVA** [comment]
Hi @FranECross! Thanks so much for following up. I think this would be a very helpful enhancement. It would be helpful for content authors/edits to understand the context in which a Q&A is being used when they go to edit it. And longer-term, it will help us track how much specific Q&As are being used and where to make content strategy decisions. Thanks!

**Comment by FranECross** [comment]
@DanielleThierryUSDSVA Wonderful! Thanks so much. I'll continue with prioritization of ticket/work.

**Comment by jilladams** [comment]
Noting: the "Where does this appear" expander does exist in prod: e.g. https://prod.cms.va.gov/resources/what-are-va-health-care-income-limits

![Screenshot 2023-12-11 at 2 06 49 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/85581471/9e938ec5-44fa-4800-ac2f-d53538865a66)

**Comment by FranECross** [comment]
@DanielleThierryUSDSVA No urgent, but I wonder if you can determine if this has actually been implemented? Please see Jill's comment above. Thanks in advance!

**Comment by FranECross** [comment]
From Jill's note this appears to exist in prod; closing. Another ticket can be created if needed in future.
