### ISSUE TITLE
Support latest vets-website in Devshop demo environments. 

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#3301]
## User Story or Problem Statement

PW team needs to rebuild demo environments with the freshest CMS and vets-website branches, to support launch of Resources & Support the week of October 26. 

## Acceptance Criteria
- [x] Master is always available to a rebuild
- [x] When an editor choose master, it builds with latest passing commit status

**Comment by ElijahLynn** [comment]
Working on this today.

**Comment by ElijahLynn** [comment]
I've committed this in this branch https://github.com/department-of-veterans-affairs/devops/commits/ansible/build/cms-ci in https://github.com/department-of-veterans-affairs/devops/commit/9d9d1b5203bfbf1ce5fbd2dab8f5d4ba043244df and pushed and tested on devshop and it is working. 

However, there does seem to be an issue with the latest vets-website build and I do get an error, this file is in fact missing in the latest code and was just removed a few commits ago in https://github.com/department-of-veterans-affairs/vets-website/commit/ad948ceb5afb58df8578e99c33126ca7108131aa and I need help triaging that.
> 
Error: ENOENT: no such file or directory, open '/var/aegir/projects/demo/learningcenter/docroot/vendor/va-gov/web/src/site/includes/related-benefit-hubs.drupal.liquid'

But, this story is done now and there is a 'master' branch in the dropdown.

**Comment by ElijahLynn** [comment]
Oh yeah, the latest passing commit status. Reopening.

**Comment by ElijahLynn** [comment]
K, it is now checking for last passing commit when choosing the `master` branch. It does only get the last 30 commits, so if one isn't passed in there it will throw an exception saying "No passing commit found". 

![image](https://user-images.githubusercontent.com/1504756/97275018-a6080500-17f2-11eb-973d-cc8c176d7285.png)

![image](https://user-images.githubusercontent.com/1504756/97275021-a7d1c880-17f2-11eb-8bb9-a68b381c92c3.png)
