### ISSUE TITLE
GitHub Webhook setup

### ISSUE THREAD

**Issue by ElijahLynn** [department-of-veterans-affairs/va.gov-cms#3313]
GitHub Webhook setup
   - AC:
      - [ ] GitHub UI webhook configuration to point at dev.va.gov/cms-tugboat/github-webhook/
      - [ ] RevProxy endpoint route exists for dev.va.gov/cms-tugboat/github-webhook to tugboat.cms.va.gov balancer (Terraform)

**Comment by oksana-c** [comment]
@olivereri , I see a merged PR attached to this issue. Please advise whether we can consider this one done or move to Sprint 20. Ty

**Comment by ElijahLynn** [comment]
> @olivereri , I see a merged PR attached to this issue. Please advise whether we can consider this one done or move to Sprint 20. Ty

Sprint 19
