### ISSUE TITLE
Build and deploy Tugboat application on EKS/Argo CD/GHA

### ISSUE THREAD

**Issue by ElijahLynn** [department-of-veterans-affairs/va.gov-cms#3314]
**Build and deploy the Tugboat application with Ansible and Jenkins.**
Create a job that runs Tugboat updates.
Configures backups. 

**PIVOT TO EKS/Argo/GHA per Platform Q2 planning**

**Comment by mchelen-gov** [comment]
Can the goal of this epic be fleshed out more, for example how does it help with https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Postmortems/2021-03-03-tugboat-cms-demo-environment-data-reset.md ?

**Comment by ElijahLynn** [comment]
> Can the goal of this epic be fleshed out more, for example how does it help with https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Postmortems/2021-03-03-tugboat-cms-demo-environment-data-reset.md ?

Yes, it helps with that by removing the human element.

**Comment by ElijahLynn** [comment]
> Can the goal of this epic be fleshed out more,

I'll try to get this fleshed out more but can't right now as I am working on some current sprint goals.

**Comment by olivereri** [comment]
> > Can the goal of this epic be fleshed out more,
> 
> I'll try to get this fleshed out more but can't right now as I am working on some current sprint goals.

Bigger question, does it make sense to even continue work on this? Tugboat looks like the first best candidate to integrate into VSP's new CI/CD system.

I suppose the goal is the same regardless of what deployment system we integrate it in to. No handcrafted, unique build or deployment that is demonstrably fragile and expensive when compared to breaking down the build or deployment into it's component parts and having an automated assembly line handle it.

**Comment by ElijahLynn** [comment]
> Bigger question, does it make sense to even continue work on this? Tugboat looks like the first best candidate to integrate into VSP's new CI/CD system.

We should explore this soon as I don't really know how to best put a Docker swarm inside of Kubernetes and that will be very important discovery.

**Comment by mchelen-gov** [comment]
updated title to match roadmap https://lucid.app/lucidchart/9b3d2f36-2e90-4b2a-9676-8edb96e9dd42/edit?shared=true&page=I9Ok25vTgODC#

**Comment by ElijahLynn** [comment]
> updated title to match roadmap https://lucid.app/lucidchart/9b3d2f36-2e90-4b2a-9676-8edb96e9dd42/edit?shared=true&page=I9Ok25vTgODC#

I need to sync with @dginther on this soon to go over how Tugboat is architected to run in a Docker Swarm. Putting a Docker Swarm in K8s, will have unexpected challenges, I think.

**Comment by mchelen-gov** [comment]
@ElijahLynn is the CI migration dependent on that or can we proceed with that portion?

**Comment by ElijahLynn** [comment]
> @ElijahLynn is the CI migration dependent on that or can we proceed with that portion?

Yeah, it is dependent.

**Comment by acrollet** [comment]
Iceboxing per @mchelen-gov - no high present need.

**Comment by jkalexander7** [comment]
Closing - work no longer needed.
