### ISSUE TITLE
Update use of object-path in vagovadmin theme

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#3322]
**Describe the defect**
There are two security issue related to packages that are used in this theme. 

1. object-path https://github.com/department-of-veterans-affairs/va.gov-cms/network/alert/docroot/themes/custom/vagovadmin/package-lock.json/object-path/open
2. http-proxy https://github.com/department-of-veterans-affairs/va.gov-cms/network/alert/docroot/themes/custom/vagovadmin/package-lock.json/http-proxy/open

The packages needs to be updated or replaced.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information if relevant, or delete):**

**Additional context**
Add any other context about the problem here. Reach out to the Product Managers to determine if it should be escalated as critical (prevents users from accomplishing their work with no known workaround and needs to be addressed within 2 business days).

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Defect")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS objective (orange) (not needed for bug tickets)
- [ ] CMS-supported product (black)

**Comment by oksana-c** [comment]
vagovadmin theme is enabled and supports many content proofing upgrades, including some recent ones for LC content. We cannot remove it. Addressing security issues is a prudent course here. Eventually this theme will be replaced, but we're some ways away from that milestone.
