### ISSUE TITLE
Paragraphs can have incorrect default revision

### ISSUE THREAD

**Issue by indytechcook** [department-of-veterans-affairs/va.gov-cms#3324]
**Describe the defect**
The `revision_id` on the `pargraph_item_field_data` is not matching the `revision_id` from the matching field table `node__field_content_block`

The out of sync data causes the incorrect revision of a `paragraph` entity to be used when it's loaded outside the context of the field.  The loading of a `paragraph` entity outside the context of the field is known to occur in `tome_sync and` `content_moderation`.  

The immediate impact is the incorrect `paragraph` entity being used in the cms export as reported here: https://github.com/department-of-veterans-affairs/va.gov-team/issues/15321.

Resaving the node from the node form does resolve the out of sync nature.

**To Reproduce**
* Create a node
* Publish a node
* Create a new draft
* Save a new draft revision
* Set the "Set Current Revision" for a draft revision that occurred after the published revision.
![image](https://user-images.githubusercontent.com/121603/97486464-d7d3b580-1931-11eb-8038-58c8f943c39d.png)

** Related Issues on D.O**

The issue appears to be related to bugs in the `entity_reference_revisions` module but I can't confirm the issue as I can not reproduce.

* https://www.drupal.org/project/entity_reference_revisions/issues/2984027
* https://www.drupal.org/project/entity_reference_revisions/issues/2903928
* https://www.drupal.org/project/paragraphs/issues/2712975

**Expected behavior**
The revision id on the `paragraph_item_revision` should match the revision on the latest published item on the field table.

**Comment by indytechcook** [comment]
The patch for `entity_reference_revisions`: https://www.drupal.org/files/issues/2019-05-17/entity_reference_revisions-default_revision-2984027-7.patch does work.  The patch at comment 10 does not work.  

https://www.drupal.org/project/entity_reference_revisions/issues/2984027

**Comment by meganhkelley** [comment]
Hi @indytechcook could you let us know when you have a moment what your ETA is on a fix for this? We have plenty of other things to work on in the meantime, just checking in.

**Comment by indytechcook** [comment]
Hi @meganhkelley I expected to have it Monday but other meetings got in the way then I was out Tuesday because I was a poll worker.  I don't have any meetings today and expect it to go out today (tomorrow at the latest).

I have the root cause fixed, I'm working on the data migration script.

**Comment by meganhkelley** [comment]
Thanks for the info! That's great :)

**Comment by indytechcook** [comment]
the Code is in Review/testing now.  I expect this to be deployed to Prod on Monday.

**Comment by indytechcook** [comment]
post deploy command: `drush scr ../scripts/content/VACMS-3325_paragraph_revision-2020-10.php`

**Comment by indytechcook** [comment]
Ran on prod:

```
sh-4.2$ sudo -u apache bash -c 'source /etc/sysconfig/httpd; /usr/local/bin/drush scr ../scripts/content/VACMS-3325_paragraph_revision-2020-10.php'
Finding Nodes which need to be updated...
.................................................................................................................................................................................................................................................................................................................................................................................................................................................................
Updating Paragraphs
Updating paragraph 3784 on node 255 to use vid 35659
Updating paragraph 3805 on node 255 to use vid 35660
Updating paragraph 3807 on node 255 to use vid 35661
Updating paragraph 3809 on node 255 to use vid 35662
Updating paragraph 5510 on node 255 to use vid 35663
Updating paragraph 5598 on node 78 to use vid 47011
Updating paragraph 2852 on node 201 to use vid 86961
Updating paragraph 9892 on node 284 to use vid 131971
Updating paragraph 7011 on node 284 to use vid 131972
Updating paragraph 4487 on node 720 to use vid 97105
Updating paragraph 4489 on node 720 to use vid 97106
Updating paragraph 4491 on node 720 to use vid 97111
Updating paragraph 4484 on node 720 to use vid 97113
Updating paragraph 3547 on node 67 to use vid 156524
Updating paragraph 11552 on node 6454 to use vid 161405
Updating paragraph 6984 on node 952 to use vid 80491
Updating paragraph 6986 on node 952 to use vid 80492
Updating paragraph 6988 on node 952 to use vid 80499
Updating paragraph 6979 on node 952 to use vid 80501
Updating paragraph 6981 on node 952 to use vid 80503
Updating paragraph 12572 on node 637 to use vid 157706
Updating paragraph 12575 on node 637 to use vid 157709
Updating paragraph 12578 on node 637 to use vid 157712
Updating paragraph 13477 on node 8471 to use vid 161974
Updating paragraph 13478 on node 8471 to use vid 161975
Updating paragraph 13479 on node 8471 to use vid 161976
Updating paragraph 13481 on node 8471 to use vid 161978
Updating paragraph 14016 on node 8471 to use vid 161979
```
