### ISSUE TITLE
Inline Entity Form Edit button not working

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#3326]
**Describe the defect**
When visiting a page that has an inline entity form, 
/node/1010/edit

Clcik the edit button.  No modal opens.  

![image](https://user-images.githubusercontent.com/5752113/97443743-c1156a80-1901-11eb-8617-f0b395b269b0.png)

Additionally, the "add new banner alert" is also broken.
![image](https://user-images.githubusercontent.com/5752113/97445295-7d236500-1903-11eb-8009-01adc0dc31b7.png)

This has been confirmed on both staging and prod.

There are a significant number of javascript errors
![image](https://user-images.githubusercontent.com/5752113/97444258-5153af80-1902-11eb-92ca-b585dc790677.png)

Upon clicking the edit button these errors appear
![image](https://user-images.githubusercontent.com/5752113/97444410-7e07c700-1902-11eb-9359-d2d8586f06fd.png)

```
Drupal.AjaxError {message: "↵An AJAX HTTP error occurred.↵HTTP Result Code: 20…jax_form=1↵StatusText: parsererror↵ResponseText: ", name: "AjaxError"}
message: "↵An AJAX HTTP error occurred.↵HTTP Result Code: 200↵Debugging information follows.↵Path: /node/1010/edit?ajax_form=1↵StatusText: parsererror↵ResponseText: "
name: "AjaxError"
```
**Expected behavior**
Clicking the button should open a modal to edit the entity.

**Screenshots**

**Desktop (please complete the following information if relevant, or delete):**

**Additional context**
Add any other context about the problem here. Reach out to the Product Managers to determine if it should be escalated as critical (prevents users from accomplishing their work with no known workaround and needs to be addressed within 2 business days).

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Defect")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS objective (orange) (not needed for bug tickets)
- [ ] CMS-supported product (black)

**Comment by acrollet** [comment]
@swirtSJW I'm pretty sure I know the root cause, taking this one. FYI #3289 should catch JS errors in testing when we're able to implement.
