### ISSUE TITLE
Bullets not appearing in wysiwyg editor [follow-up]

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#3327]
**Describe the defect**
Bullets don't appear in wysiwyg content block.

**To Reproduce**
1. Edit a /help page with a bulleted formatting, such as /node/6692
2. Edit the wysiwyg
3. Observe that the bullet formatting that appears on View doesn't show up in the wysiwyg. The functionality seems to be there, it's just not visually displaying the bullets in the text box.

**Browser**
Internet Explorer

**Expected behavior**
When I apply bullet formatting to text in a wysiwyg, I expect to see bullet points.

**Screenshots**
![image](https://user-images.githubusercontent.com/1504756/97904141-f0a6e700-1cf4-11eb-9e90-a4719318a0ad.png)
![image](https://user-images.githubusercontent.com/1504756/97904081-d967f980-1cf4-11eb-9e1d-a327dbc95205.png)

**Kev and Clarence's additional research**

* It seems like `<ol>` appears as bulleted lists in CKeditor, but correctly as ordered lists on Preview. 
* `<ul>` doesn't appear at all in CKeditor. 

I think this regression that happened during the proofing page CSS work on benefits detail pages. 

**Implementation notes**

The issue has been addressed using CSS `revert` value - https://caniuse.com/css-revert-value

 Some users still have issues w/ bullets using Chrome on CAG [Slack thread](https://dsva.slack.com/archives/CDHBKAL9W/p1602597970100700)

Recommendation is to find a different CSS method to address bullet appearance in Rich text fields. See original fix https://github.com/department-of-veterans-affairs/va.gov-cms/pull/2995/files#diff-e4f3fd7c4d937decf42addf632bf551db938580656e4ca0978d4ae5579aa9c1d

**Comment by acrollet** [comment]
@oksana-c I'm not seeing IE mentioned in the slack thread, can you clarify if that's something you saw?

**Comment by oksana-c** [comment]
One of the users using GFE during training noted this bug, their browser was identified as IE. A recommendation was made to use Chrome, although some of our users (slack thread) are still experiencing this issue in Chrome.

**Comment by acrollet** [comment]
@oksana-c thanks for the clarification!

**Comment by acrollet** [comment]
Confirmed fixed by @RLHecht here: https://dsva.slack.com/archives/CDHBKAL9W/p1604671645441400?thread_ts=1602597970.100700&cid=CDHBKAL9W

(Fixed by #2767)
