### ISSUE TITLE
Enterprise Asset Management System / Media library

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#3329]
# Enterprise Asset Management System

## Problem statement

CMS user needs are outgrowing current capabilities of the CMS media library. 

All media added to the CMS can be reused by all Content editors that manage various VFS Products, but that may not be the author's intent.

The assumption is that media management should follow the same or similar governance as other content on the site and the reusability aspect needs to be explored and added. This assumption needs to be validated.

The more products we add to the CMS, the more relevant governance and reusability issues become.

Media management landscape assessment at VA is critical to ensure that the current system of media management in the CMS is scaling in sync with the needs of the growing CMS editor community.

## Hypothesis or Bet

* The practice of media governance and authoring experience in the CMS needs to evolve based on VA’s long-term media management needs.

## We will know we're done when... ("Definition of Done")

* Enterprise asset management system is researched, designed and validated with stakeholders.
* Enterprise asset management system satisfies the needs of various user groups and products.

## Known Blockers/Dependencies

* Landscape assessment of media management at VA

## va.gov-team product directory

https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/cms/product-outlines/enterprise-asses-management-system

**Comment by jefflbrauer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VAgov-CMS-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/3329?planning-poker) with ZenHub @ElijahLynn @indytechcook @ndouglas @olivereri @timcosgrove

**Comment by jefflbrauer** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VAgov-CMS-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/3329?planning-poker) with ZenHub @cweagans

**Comment by EWashb** [comment]
This is extremely out of scope for the current system and will require a lot of work. I'm going to close it for now but we can reopen when/if the time comes.
