### ISSUE TITLE
Rename "root menu" to something else

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#3338]
## Background

Some content types require menu items to get decent breadcrumbs, but don't go into any existing navigation. 

The [Root pages menu](https://prod.cms.va.gov/admin/structure/menu/manage/root-benefits-hub?destination=/admin/structure/menu) was set up during the migration of benefits primarily as a means of creating breadcrumbs. Without menu items, the default pattern for breadcrumbs is a "Home" string, unlinked, and without the title in the URL. Ideally, all pages without menu items, or without [path-based breadcrumbs](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/1238), would default to this "catch-all" pattern: 

[Home](https://www.va.gov/) > [Page title, aka h1]

Slack thread with an example use case: https://dsva.slack.com/archives/CDHBKAL9W/p1603977219253000?thread_ts=1603842876.249100&cid=CDHBKAL9W

### Affected users and stakeholders

* All CMS editors

**Comment by kevwalsh** [comment]
This debt maybe "owned" by PW team, since it's probably 100% FE work, similar to the work Ethan did in #1238.

**Comment by FranECross** [comment]
Closing as obsolete
