### ISSUE TITLE
Design Governance research and documentation process for each product

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#3340]
## Description

"We have to know who the players are before we tell them the rules of the game"

CMS team needs a process for researching, designing, and documenting content governance for each product in the CMS

Use case:
- [x] Campaign Landing Page (Q4 2020)
- [ ] Resource & Support (Q4 (2020)
- [ ] Future products (2021)
- [ ] Existing products (before now)

## Acceptance Criteria
- [ ] We have a standardized way of determining governance: 
  - [ ] Who can edit content (or its parts) 
  - [ ] Who can create content, and what triggers that, if it's governance based. 
  - [ ] Other permissions specific to each product 
- [ ] Product governance is documented somewhere, TBD

**Comment by nataliedunbarCS** [comment]
We have created a preliminary governance model that we will test and iterate upon, with the goal of moving towards alignment with all product owners as new products are developed, as well as retrofitting when appropriate with existing products. 

Documentation for this work can be found at: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/content-governance/design-governance-research-documentation-process.md#design-governance-and-research-documentation-process-for-each-product.
