### ISSUE TITLE
Extend the disabling of automated URL aliases to all nodes types and vocabularies

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#3342]
## User Story or Problem Statement

Until the FE becomes aware of Drupal redirects, we want to prevent the automatic update of an URL alias when H1 gets updated. 

## Acceptance Criteria
- [x] Before starting this work, we've clarified this is desired behavior for all content types. 
- [x] All content types and taxonomy terms have their automatic URL alias updates disabled after the content is created. 
- [x] Generate BEHAT test to cover only a single content type.

**Comment by kaise-lafrai** [comment]
Have we clarified the first AC?

**Comment by kevwalsh** [comment]
Updated issue title and checked off the first AC.

**Comment by kaise-lafrai** [comment]
Added as another AC

> Generate BEHAT test to cover only a single content type.
