### ISSUE TITLE
Resources and Support Dashboard does not include Learning Center detail pages

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#3346]
**Describe the defect**
When I visit the Resources and Support Dashboard https://prod.cms.va.gov/admin/content/resources-and-support 
I do not see any support_resources_detail_page entities.

**To Reproduce**
1. Go to 'https://prod.cms.va.gov/admin/content/resources-and-support '
3. Scroll and look there are no Learning Center Detail pages present.

**Expected behavior**
I should see pages like these
![image](https://user-images.githubusercontent.com/5752113/97635129-3cb00e00-1a0d-11eb-9aeb-eca38d4ac75a.png)

This is likely not a critical bug as people can get to the content through https://prod.cms.va.gov/admin/content

It would also be nice to have some filters on the Resources and Support dashboard.

**Comment by kaise-lafrai** [comment]
@oksana-c Please review this when environment is ready: https://github.com/department-of-veterans-affairs/va.gov-cms/pull/3353
