### ISSUE TITLE
CLP governance design MVP

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#3361]
"We have to know who the players are before we tell them the rules of the game"

AC
- [x] We know what triggers a CLP, what are circumstances that trigger the need
- [x] We know who governs the creation 
- [x] We know who are the editors for the two uses cases
- [x] We know if there is an expiry date for these two use cases
- [x] We know if there is an archival process and/or if these pages will be deleted/sunsetted
- [x] What aspects of governance need to be surfaced in a dashboard
- [x] We know what Sections the new CLPs belong to, and who has access to those. Do we need a new Section?

TBD
- [ ] Where is this all documented?

**Comment by nataliedunbarCS** [comment]
Updated ACs based on learnings from Sprint 19. Drafted CLP governance documentation based on those learnings, and presenting to PO's for review on 11/24.

**Comment by nataliedunbarCS** [comment]
CLP governance documentation draft (form MVP 1.1) was reviewed with PO (John Hashimoto) on 11/25 for accuracy.
Documented at [https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/campaign-landing-page-templates/content-requirements-spec/cms-content-model-and-rigidity.md#governance](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/campaign-landing-page-templates/content-requirements-spec/cms-content-model-and-rigidity.md#governance.)
