### ISSUE TITLE
Migrate Existing DNS Records and Create New Tugboat DNS Records in AWS Route53 Hosted Zone *.cms.va.gov

### ISSUE THREAD

**Issue by olivereri** [department-of-veterans-affairs/va.gov-cms#3363]
AC:

- [x] Create *.cms.va.gov hosted zone in Terraform. 
- [x] Gather all existing DNS Records for *.cms.va.gov
  - [x] Add Records to Terraform Code for private hosted zone.
      - [x] dev                
     - [x] staging             
     - [ ] ~stg~                 
     - [x] prod              
     - [x] test.dev         
     - [x] test.staging   
     - [x] test.prod       
     - [x] devshop        
     - [x] *.ci       
     - [ ] ~cms.va.gov~
- [ ] Add all Tugboat DNS Records to Terraform Code for private hosted zone. 
  - [ ] Prod:
    - [ ] ci.cms.va.gov 
    - [ ] *.ci.cms.va.gov
    - [x] demo.cms.va.gov
    - [x] *.demo.cms.va.gov
    - [x] tugboat.cms.va.gov
    - [x] *.tugboat.cms.va.gov  
  - [ ] Below DNS records point to the STAGING balancer:
    - [ ] staging.ci.cms.va.gov
    - [ ] *.staging.ci.cms.va.gov
    - [x] staging.demo.cms.va.gov
    - [x] *.staging.demo.cms.va.gov
    - [x] staging.tugboat.cms.va.gov
    - [x] *.staging.tugboat.cms.va.gov
  - [ ] Below DNS records point to the DEV balancer:
    - [ ] dev.ci.cms.va.gov
    - [ ] *.dev.ci.cms.va.gov
    - [x] dev.demo.cms.va.gov
    - [x] *.dev.demo.cms.va.gov
    - [x] dev.tugboat.cms.va.gov
    - [x] *.dev.tugboat.cms.va.gov

**Comment by ElijahLynn** [comment]
Splitting the CI records out into #3411.
