### ISSUE TITLE
Validate that R&S product breadcrumbs are rendered as expected on FE

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#3364]
## Acceptance criteria

- [x] R&S breadcrumb defect stories are triaged and fixed OR delegated to the front-end team if the issue is not CMS-related

| Issue | Triage comment |
| --- | --- |
| [#15559](https://github.com/department-of-veterans-affairs/va.gov-team/issues/15559) | will be fixed once #3259 is deployed - ETA 11/02/20 |
| [#15562](https://github.com/department-of-veterans-affairs/va.gov-team/issues/15562) | will be fixed once #3259 is deployed - ETA 11/02/20 |
| [#15565](https://github.com/department-of-veterans-affairs/va.gov-team/issues/15565) | will be fixed once #3259 is deployed - ETA 11/02/20 |
| [#15566](https://github.com/department-of-veterans-affairs/va.gov-team/issues/15566) | will be fixed once #3259 is deployed - ETA 11/02/20 |
| [#15625](https://github.com/department-of-veterans-affairs/va.gov-team/issues/15625) | will be fixed once [#14804](https://github.com/department-of-veterans-affairs/vets-website/pull/14804) is deployed - ETA 11/03/20 |

**Comment by oksana-c** [comment]
@jenniferlee-dsva , please validate all linked breadcrumb issues against [recommended patterns](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/websites-learning-center.md). Thank you.

demo environment - http://devshop.cms.va.gov/hosting/tasks?page=0&order=created&sort=desc

**Comment by jenniferlee-dsva** [comment]
Should I be using the WEB demo? http://learningcenter.web.demo.ci.cms.va.gov/resources/

**Comment by oksana-c** [comment]
@jenniferlee-dsva , my links got mixed. Thanks for catching that. Web it is - http://learningcenter.web.demo.ci.cms.va.gov/resources/

**Comment by jenniferlee-dsva** [comment]
All of the above are resolved. Validated!
