### ISSUE TITLE
Helpdesk SLA review

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#3373]
## Acceptance Criteria
- [x] Helpdesk SLA is reviewed w/ program team
- [x] Iterate on internal feedback
- [x] Helpdesk SLA is reviewed w/ DEPO

**Comment by oksana-c** [comment]
noting that the SLA document needs some edits. Mainly examples of P2 issues. 

https://docs.google.com/document/d/19_Flgolo8GW91EKUKh6qO2WL0tMjh5fB2-yxq3tz2AM/edit#heading=h.k7qshbkgk5x8

**Comment by erogray** [comment]
@oksana-c do we need to update this doc in the meantime? not sure what the next step is

**Comment by cmaeng** [comment]
reviewed and plugged in some P2 examples. this should be ready for DEPO review once those changes are incorporated. cc: @erogray @oksana-c

**Comment by erogray** [comment]
I've made updates to the doc at https://docs.google.com/document/d/19_Flgolo8GW91EKUKh6qO2WL0tMjh5fB2-yxq3tz2AM/edit# accordingly. SLA tiers of hours still feel a little hypothetical, so I've left them highlighted. I don't really have firm opinions about them; we just want to make sure we're meeting requirements.
