### ISSUE TITLE
R&S taxonomy terms MVP 1.1

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#3374]
## Acceptance Criteria

- [x] @jenniferlee-dsva to provide updated R&S term list for MVP 1.1
- [x] R&S Audience non-Beneficiaries, Topics and LC Categories taxonomy vocabularies are populated w/ provided terms on production

**Comment by jenniferlee-dsva** [comment]
**Additional FE topic tags to add:** 
- Guide and service dogs

**Additional FE audience tags to add:** 

- Schools, administrators, and other education professionals
- Career counselors and other employment specialists
- Fiduciaries
- Funeral directors and cemeteries
- Lenders, appraisers, and other real estate professionals
- Veteran service organizations and accredited representatives


**Oksana, do you have a different ticket for additional categories? For post1.0 content, we'll need these additional categories to be added to the CMS fields here:** 

![image](https://user-images.githubusercontent.com/43381063/98143126-b5dcb480-1e96-11eb-84ed-a85c0161fd9c.png)

Burials and memorials
Careers and employment
Decision reviews and appeals
Disability
Education and training
Health care
Housing assistance and home loans
Life insurance
Pension
Records
VA account and profile `<-- done`
Other topics and questions  `<-- done`

**Comment by oksana-c** [comment]
@jenniferlee-dsva , terms you listed are available on production, you can validate terms and their respective URLs by visiting the following admin pages in the CMS:

- [ ] Topics - https://prod.cms.va.gov/admin/structure/taxonomy/manage/topics/overview
- [ ] Categories - https://prod.cms.va.gov/admin/structure/taxonomy/manage/lc_categories/overview
- [ ] Audience - non-Beneficiaries - https://prod.cms.va.gov/admin/structure/taxonomy/manage/audience_non_beneficiaries/overview

At the moment "Audience - non-Beneficiaries" tags cannot be selected for content since we have to make a minor update to tag selection logic to enable non-Beneficiary tags. Let's discuss the priority of https://github.com/department-of-veterans-affairs/va.gov-cms/issues/3494 at our weekly check-in.

**Comment by jenniferlee-dsva** [comment]
validated ^
