### ISSUE TITLE
Spike: measuring user satisfaction

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#3386]
## Description

Let's discuss how we can measure user satisfaction long term based on recommendation outline in [this deck](https://docs.google.com/presentation/d/1SOSGEdU_CoMMZv_IQ_qxqcHkC6mTvvkYGNPc4EYCsWs/edit#slide=id.p).

## Acceptance Criteria

- [x] Team has a shared understanding of the O2
- [x] Team has discussed _quantitative_ methods of measuring user satisfaction
- [x] Team has discussed _qualitative_ research methods recommended in attached deck
- [x] Current survey and process is reviewed for enhancements
- [x] Indicators of satisfaction [(or pointers)](https://docs.google.com/presentation/d/1SOSGEdU_CoMMZv_IQ_qxqcHkC6mTvvkYGNPc4EYCsWs/edit#slide=id.ga6f5cfe096_2_15) are defined
- [x] Methods and processes of data collection to measure user satisfaction beyond Q4 2020 are defined
- [x] Team has agreed on Q3 and Q4 2020 KPIs
- [x] A plan for measuring user satisfaction for Q1 2021 is clear
- [x] Short-term and long-term plan has the POs' buy-in

**Comment by jordanamello** [comment]
@oksana-c I wrote a list of my recommended ACs, but left the original on there for reference.

**Comment by oksana-c** [comment]
@jordanamello thank you. I made some updates. Please take a look. You can see previous versions by clicking on "edited" dropdown  next to the issue author name.

**Comment by jordanamello** [comment]
[OKR 2 Measurement Strategy](https://app.zenhub.com/files/154174777/455723dc-80d3-442a-9f20-c2a88c1df024/download) deck.
