### ISSUE TITLE
Reduce broken link flickers on paginated pages 

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#3394]
## Background

At 10:55am on November 5, an event was published in drupal, around the same time as a vets-website build was kicked off. 

This led to this broken link:

`[2020-11-05T16:04:32.997Z] outreach-and-events/events/page-3,<a href=“/outreach-and-events/events/veteran-entrepreneurship-virtual-conference”>Veteran Entrepreneurship Virtual Conference</a>`

This has happened a couple dozen times over the last few months. These kind of broken link reports usually goes away on its own. 

## Hypothesis

There may be a a race condition during the 4 minute query in which event listing (paginated) pages are queried separately from the individual event pages.

The query could be adapted to query the individual event pages first, then the events list pages later.

This race condition will go away with CMS export.

Possible to dos
- [ ] Investigate changing the order of operations in the query, stitching the fragments together
- [ ] Ignore this because CMS export is coming, because the data is always in sync

This is not necessarily the responsibility of CMS team.

**Comment by acrollet** [comment]
@kevwalsh this might be able to be closed in favor of #5255 ?

**Comment by timcosgrove** [comment]
This was handled in #5255
