### ISSUE TITLE
Helpdesk categories, component and label taxonomy

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#3396]
## Description

For workflow and reporting purposes, it’s important to establish a category/component and labelling taxonomy that will be appropriate for both routing requests (in some case, for building work queues or workflows) and for reporting on them (for instance, the prevalence of a particular type of issue over time).

**Category/component** 
The Category or Component is typically a way of marking which website, feature or set of functionality the request primarily applies to. This will require a discovery process at the time the helpdesk is initially set up, in order to make an initial list to use. More may be added or adjusted later, but typically these are relatively easy to discern at the outset.

**Label**
Labels are usually most useful for deciding a type of request. For instance, labels may include things like the type of request (Enhancement, Information request, Bug report, Change request, Other) or characteristics about the request which are desirable to report on (e.g. Insufficient information provided, Unknown customer, Blocked), etc.  

Labels should also match the Github taxonomy, at least in part, to allow for better organization across platforms.

An approximate labelling taxonomy should be decided at the outset of helpdesk work, but it is to be expected that this set of labels will change as the work progresses and patterns emerge that are desirable to report on or otherwise track. 

## Acceptance Criteria

- [x] Helpdesk category/component/label taxonomy starter is established in GDoc
- [x] Helpdesk taxonomy is reviewed w/ DM/PMs/Engineers
- [x] Helpdesk taxonomy is configured in JIRA Service Desk

**Comment by erogray** [comment]
I've started a doc in https://docs.google.com/document/d/1KRXcR6MZR-3l9FuX09wOsdo_gHtEeo_QAmt-hV10d6M/edit#
@oksana-c — feel free to add Components or Labels there

**Comment by oksana-c** [comment]
Document where Product and CMS Feature taxonomies are described - https://docs.google.com/document/d/1KRXcR6MZR-3l9FuX09wOsdo_gHtEeo_QAmt-hV10d6M/edit#heading=h.fvi4h5cic5a9

@erogray , were these entered in JSD?

**Comment by erogray** [comment]
@oksana-c these are now in JSD's Components and should be showing up in the portal: https://va-gov.atlassian.net/servicedesk/customer/portal/3

**Comment by erogray** [comment]
@MaggieBrazeau has also entered an initial set of all generic Labels into https://va-gov.atlassian.net/jira/servicedesk/projects/VAHELP/queues/custom/11/VAHELP-21 so that they'll be easy to use during initial tickets — the only remaining discussion is what labelling to use specifically in Github/Zenhub.

**Comment by oksana-c** [comment]
complete in #3397 and #3543
