### ISSUE TITLE
More reliable/timely updates of vetsweb.

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#3400]
## User Story or Problem Statement

As a developer I would like our testing to be using more current versions of vetswebsite so that we can be sure our testing is accurate.

We have been relying on dependabot to create updates to our composer for the new versions of vetsweb.

The problem is that these PR's only get created once every few weeks, rather than daily.

We need a more timely solution.

## Acceptance Criteria
* Vetsweb site update prs are created timely (ideally each day after vetsweb deploy, however once per day would suffice).

## Implementation steps
?  Solution not prescribed at this time

**Comment by acrollet** [comment]
This appears to be resolved by the composer upgrade to v2.
