### ISSUE TITLE
Cutover PRs from DevShop to Tugboat

### ISSUE THREAD

**Issue by olivereri** [department-of-veterans-affairs/va.gov-cms#3411]
Currently *.ci.cms.va.gov points to Devshop and should remain so until Devshop is decommissioned in favor of Tugboat. During the transition the below records should be created that point to Tugboat's load balancer. This is also helpful should the *.cms.va.gov zone delegation come through before we're ready to migrate.

AND we need to turn off GitHub polling on DevShop so that it doesn't build PRs and post commit status results to PRs. 

AC:

- [x] Point *.ci.cms.va.gov to utility-tools balancer
- [x] Turn off github polling at http://devshop.cms.va.gov/admin/hosting/queues

**Comment by ElijahLynn** [comment]
This is done and we have PRs fully migrated to Tugboat.
