### ISSUE TITLE
Content model for the CMS announcements content

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#3416]
## Description

All CMS announcements (formerly release notes) are currently posted at https://prod.cms.va.gov/help/support/release-notes in a form of unstructured content.

The CMS needs a method of posting CMS Announcements in a structured manner, where each announcement can be:
* categorized by product, section (see https://github.com/department-of-veterans-affairs/va.gov-cms/issues/3075)
* picked up by the CMS notifications framework and delivered to intended audiences in the selected channels
* other TBD

## Acceptance Criteria
- [ ] Testable_Outcome_X
- [ ] Testable_Outcome_Y
- [ ] Testable_Outcome_Z

**Comment by jefflbrauer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VAgov-CMS-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/3416?planning-poker) with ZenHub @ElijahLynn @indytechcook @ndouglas @olivereri @timcosgrove

**Comment by jefflbrauer** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VAgov-CMS-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/3416?planning-poker) with ZenHub @cweagans
