### ISSUE TITLE
composer va:web:build script mods to cover transition period from GraphQL > Content Export

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#3420]
## Description

Cutover plan - composer va:web:build script to cover transition period from GraphQL > Content Export
va:web:build1
va:web:build2 (--use-cms-export)

## Acceptance Criteria
- [ ] composer va:web:build script is updated to cover transition period from GraphQL > Content Export

**Comment by indytechcook** [comment]
I have a branch up that is doing transformer-based builds: https://github.com/department-of-veterans-affairs/va.gov-cms/tree/cms_export_test.

**Comment by indytechcook** [comment]
Adding some more thought in here.

On top of the web build, we also need a full export as part of the process on tugboat.  These should be separate commands (composer?) and executed as separate steps.
