### ISSUE TITLE
Claro Admin UI Implementation on demo environment

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#3422]
## User story

As a researcher, 
I need to have a demo environment where Claro theme is applied to all content forms,
so that I can elicit user feedback.

## Problem Statement
The CMS team is preparing to switch Drupal Admin UI from Seven theme (soon to be deprecated) to a new `uswds_admin` theme based on modern Drupal Design System - Claro.

Seven and Claro themes are drastically different in the look and feel. The CMS team should conduct usability research around Admin UI updates in order to reduce the risk of releasing UI changes that CMS Content Editors may find jarring and counter-productive. 

In order to support the research effort, the CMS team should apply Claro theme on the demo environment and address any known issues for which public patches exists.

## Acceptance Criteria
- [x] Claro is installed and applied to Admin UI in a PR environment for demo purposes
- [x] Content forms are reviewed for major defects and any existing Claro patches that address identified issues are applied
- [x] demo/PR environment URL is shared and PR has prefix [DO NOT MERGE] in the title

**Comment by acrollet** [comment]
I've created a PR with the Claro theme enabled that will be available at https://pr3462.ci.cms.va.gov once built.

I've additionally created a PR with the [Gin](https://drupal.org/project/gin) theme enabled that will be available at https://pr3462.ci.cms.va.gov once built. Gin is a contributed theme built on Claro with some significant UX/AX improvements, and I believe we should also review it as a potential basis for the `uswds_admin` work.

Claro editing experience:

<img width="1496" alt="Screen Shot 2020-11-12 at 9 28 32 AM" src="https://user-images.githubusercontent.com/101649/98975805-cebb1a80-24d3-11eb-8547-d209c0399ad5.png">

Gin editing experience: (note the sticky header with action buttons and sidebar)

<img width="1496" alt="Screen Shot 2020-11-12 at 9 23 33 AM" src="https://user-images.githubusercontent.com/101649/98975818-d5e22880-24d3-11eb-863c-ffb6a3fc4b03.png">

**Comment by acrollet** [comment]
The demo environments haven't yet been fully installed by devshop, I'll delete this comment once they're ready for review.

**Comment by oksana-c** [comment]
@acrollet @jordanamello @hie1 ,  I'm moving this issue to Done. We have demo environment in a working state. We'll open a separate story if any follow up tweaks are required.

**Comment by acrollet** [comment]
The Claro demo environment is now available [here](https://pr169-uog8pkh31pgvmun6hggow5ocfji6gsz2.tugboat.vfs.va.gov/admin/content).
