### ISSUE TITLE
Spike: Claro Admin UI internal review

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#3423]
## Problem Statement
The CMS team is preparing to switch Drupal Admin UI from Seven theme (soon to be deprecated) to a new `uswds_admin` theme based on modern Drupal Design System - Claro.

Seven and Claro themes are drastically different in the look and feel. The CMS team should conduct usability research around Admin UI updates in order to reduce the risk of releasing UI changes that CMS Content Editors may find jarring and counter-productive. 

A cross-disciplinary team will meet to review Claro UI features that Content Editors use most often and identify areas where user feedback is most needed.

## Acceptance Criteria
- [x] A cross-disciplinary team has met to review demo environment where Claro theme is applied to Admin UI
- [x] The team have identified UI features / pages to include in user research. Special attention should be given to most drastic UI changes.

## Participants

@jordanamello @acrollet @hie1 @rachel-kauff @oksana-c

**Comment by acrollet** [comment]
Links to Claro (and Gin) demo environments are [here](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/3422#issuecomment-726233073) - we should be able to schedule this spike for anytime from tomorrow onwards.

**Comment by oksana-c** [comment]
Focus group met and reviewed OOTB Claro UI. 
Next steps as identified by the group:

- [ ] @jordanamello and @hie1 to perform heuristic review on [Claro demo environment](http://pr3462.ci.cms.va.gov/) and compile a list of recommended adjustments to be made to OOTB Claro before we go into a research cycle
- [ ] @jordanamello @hie1 @acrollet @oksana-c meet to discuss required adjustments, evaluate LOE required and decide whether to proceed w/ a research cycle or redirect the team's energy towards laying the basis for the CMS DS w/ DS tokens

**Comment by oksana-c** [comment]
@jordanamello will open a followup story for Heuristic evaluation. Closing this as Done.
