### ISSUE TITLE
Research plan to evaluate usability of the updated Admin UI

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#3424]
## Description
Create research plan to evaluate usability of the updated Admin UI.

## Problem Statement
The CMS team is preparing to switch Drupal Admin UI from Seven theme (soon to be deprecated) to a new `uswds_admin` theme based on modern Drupal Design System - Claro.

Seven and Claro themes are drastically different in the look and feel. The CMS team should conduct usability research around Admin UI updates in order to reduce the risk of releasing UI changes that CMS Content Editors may find jarring and counter-productive. 

**Research focus:** how can we improve OOTB Claro Admin UI to facilitate comfortable transition for experienced and new content editors in the CMS

**Research participants:**
* 2-3 power users
* 2-3 new users

## Acceptance Criteria
- [x] Research plan is created in GH
	- [ ] Conversation guide for usability study of the updated Admin UI
	- [x] Recruitment communications (@jordanamello  + @rachel-kauff )
- [ ] Research plan is reviewed w/ CMS Design System group (@hie1 @acrollet @oksana-c)
- [ ] Research plan is finalized
- [ ] Research plan is approved by Jeff Barnes

**Comment by jordanamello** [comment]
Research repository in GH: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/research/claro-ds/README.md

**Comment by rachel-kauff** [comment]
@jordanamello I drafted an email template (which can easily be sent as a Slack DM as well) here: https://docs.google.com/document/d/1OSv1_YaV500Pk-OXATRG-BOuE6q_-alnNkxaTEZDBcA/edit

**Comment by jordanamello** [comment]
Thank you so much @rachel-kauff !

**Comment by jordanamello** [comment]
After further elaboration, our group ( @oksana-c @kevwalsh @acrollet @rachel-kauff @hie1 ) concluded that a heuristic evaluation would be a better strategy as a first step. We were able to point out some modifications to Claro and believe that the heuristic evaluation will potentially raise more recommendations.

We'll be documenting the Claro analysis [in this Mural](https://app.mural.co/t/vagov6717/m/vagov6717/1605723749995/8268874d3c3e4547884146f3abb1201fe6ca01f5).
