### ISSUE TITLE
PDF download experience for Help center view pages

### ISSUE THREAD

**Issue by rachel-kauff** [department-of-veterans-affairs/va.gov-cms#3436]
# User story
"As a new user, I'd like to download the slide deck used in training sessions to use as reference."

# Background
The current UI for the View experience on CMS Help center pages wasn't designed for someone who might actually want to use the download links. The "meta" kinds of labels that separate the linked text and the actual file download make this experience confusing. 

![Screen Shot 2020-11-09 at 1.26.18 PM.png](https://images.zenhubusercontent.com/5e399cf5446c5b4ca0e31e42/6dbdc49d-9c1c-4242-823c-86001d811c32)

Is there a way to remove these labels just for the Help Center content type?

## Acceptance criteria

- [ ] "Link to file or video" paragraph display is updated to match attached screenshot 
<img width="1227" alt="Screen Shot 2020-11-30 at 10 57 14 AM" src="https://user-images.githubusercontent.com/16477724/100646120-d9aae300-32fa-11eb-9620-b647c1bc6bf2.png">

- [ ] Link markup includes the following attributes `target="_blank" href="{{url}}" download="{{url}}" aria-label="Download"`

## Implementation notes

* override in twig template / preprocess functions
* see [this FE template logic](https://github.com/department-of-veterans-affairs/vets-website/blob/c58adc54df656ed5cec46bcb22d9a69e603419bc/src/site/paragraphs/downloadable_file.drupal.liquid) for inpiration

SVG icons that need to be added to vagovadmin theme: https://drive.google.com/drive/folders/1hlnNgP6UHV_ZvKHVP6vTvA0kGrq56Hn9

**Comment by oksana-c** [comment]
I have a proposal for how to tackle this for all content types in one swoop.

Below is representation of current content proofing experience for "Link to file or video" component and matching front-end representation on va.gov.

<img width="1241" alt="Screen Shot 2020-11-09 at 6 29 38 PM" src="https://user-images.githubusercontent.com/16477724/98616558-47df2580-22ba-11eb-8ce8-2e4cb3c34a5d.png">

you can see that "Link text" is used on front end w/ an addition of "Download" prefix.

I recall @kevwalsh mentioning that we should remove an option to link a video from this component altogether. So let's assume that we are only dealing w/ files. If we are only dealing w/ files, we should match the front end template logic on all content types for content proofing. See image below for how this would look in CMS

<img width="1087" alt="Screen Shot 2020-11-09 at 6 19 36 PM" src="https://user-images.githubusercontent.com/16477724/98616869-f1261b80-22ba-11eb-96dc-7ccefb749cd9.png">

If we were to proceed w/ this approach, then ACs for this story will be:

- [ ] remove the option to add "Video" from "Link to file or video" paragraph and rename it to "Link to file".
- [ ] introduce a template for "Link to file" paragraph that renders a link to file w/ an icon and using "Link text" as link text and file url as `href` attribute in a link while preserving a file type icon as shown on the image above.

---

@kevwalsh , thoughts on removing video option out of "Link to file or video" paragraph? this would go nicely w/ rethinking the concept of media library. any risks you see?

**Comment by rachel-kauff** [comment]
@oksana-c I love the idea of moving the download syntax into the link itself. In that case, would we still have to display the Link text part of this UI? It seems preferable in this case to omit that part just make it match the FE template so we don't have to display the data from those two fields (link text and file) separately.

**Comment by oksana-c** [comment]
@ndouglas , I scanned draft PR for this real quick and noticed that you incorporated some of the ACs that were discussed in comments. My bad, I needed to clarify that only ACs in the description are relevant and up-to-date. Disregard the convo in the comments since the approach changed since those comment were posted. Current approach + ACs reflected in the issue description.

**Comment by ndouglas** [comment]
Not a problem.  I actually did it both ways because I wasn't sure which we'd go with.  I didn't commit my code for the other approach, but I remember how I did it 😎   Let's see if I still remember Monday 🤔
