### ISSUE TITLE
Improve help for image alt text 

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#3444]
Per feedback from @jenstrickland and @joshkimux, Drupal's OOTB help text for Alt text field could be improved. 

User story: As a CMS editor adding an image, i have guidance for creating good alt text, so that my content is accessible.  

![Create_Benefits_Detail_Page___VA_gov_CMS](https://user-images.githubusercontent.com/643678/98629924-f9488000-22e7-11eb-9dd0-d49292cde6ac.jpg)

Some helpful guidelines are here: https://webaim.org/techniques/alttext/ 

AC
- [ ] Alt text has been rewritten to meet the needs of editors, and aligns with Platform's accessibility recommendations. 
- [ ] Engineers have implemented new help text.

**Comment by jenstrickland** [comment]
I recommend including an example of good alt text, and making it clear that it should not include the words "image" or "photo" since the screen reader will introduce the alt text by saying "image."  For example, good alt text of a photo for a VAMC would say "front entrance of the Pittsburgh VA Medical Center-University Drive".

**Comment by rachel-kauff** [comment]
Update: Did a [draft of this here](https://www.figma.com/file/Bicr5pUbygcToLltOYtD4X/Media-library-UI?node-id=0%3A1), will meet with Kev and Josh Kim next sprint for feedback.

**Comment by rachel-kauff** [comment]
(Moving to Sprint 27 to reflect new timeline)

**Comment by kevwalsh** [comment]
Screenshot from Figma

![Media library UI](https://user-images.githubusercontent.com/643678/123835261-56745e80-d8d6-11eb-9d61-468bfd1d82ec.png)

**Comment by mgifford** [comment]
Some other options posted here https://github.com/department-of-veterans-affairs/va.gov-cms/issues/8750#issuecomment-1208463026

**Comment by laflannery** [comment]
@EWashb I think we can close this?

**Comment by EWashb** [comment]
Yep. I think we can close this. Good catch.

**Comment by EWashb** [comment]
This was done as part of the in-line content guidance component
