### ISSUE TITLE
Paragraphs should have a single parent

### ISSUE THREAD

**Issue by indytechcook** [department-of-veterans-affairs/va.gov-cms#3450]
Currently, due to an issue with entity cloning, there are paragraphs that have multiple nodes.  Paragraphs must only have a single parent.  This issue is to find and fix all of the paragraphs with multiple parents.

Possible fix: https://www.drupal.org/project/entity_clone/issues/3060223#comment-13329512

related to 
* #3449 
* #3324 

**AC**
- [ ] Query to find all paragraphs with multiple parents created.
- [ ] Create a script to fix paragraphs.
- [ ] Query which finds all paragraphs with multiple parents returns 0 rows.
- [ ] downtime announcement for the slack channels #cms-support and #vfs-platform-support

**Comment by ndouglas** [comment]
Note to self: I wanna print the date associated with the revisions of these nodes that created these paragraphs so that we can confirm the cause of the issue.

**Comment by indytechcook** [comment]
The script has been merged.  Here is the run book:

Run book:

`cd /var/www/cms`

1. Turn on site alert for at 7 am EST
```
<strong>Extended downtime today</strong><br>
The CMS will be down from <strong>8:00 a.m. - 00:00 a.m. ET</strong> for maintenance. You won’t be able to use the CMS during this time. We’ll let you know when it’s ok to resume working.
```

1. At 8 AM EST

```
sudo -u apache bash -c "source /etc/sysconfig/httpd; /usr/local/bin/drush site_alert:create 'deploy-alert' '<strong>Extended downtime today</strong><br>The CMS will be down from <strong>8:00 a.m. - 00:00 a.m. ET</strong> for maintenance. You won’t be able to use the CMS during this time. We’ll let you know when it’s ok to resume working.' --severity=high"
```

1. Put the site into deploy mode

```
sudo -u apache bash -c "cp docroot/sites/default/settings/settings.deploy.inactive.php docroot/sites/default/settings/settings.deploy.active.php"
```

1. Run the migration script
```
sudo -u apache bash -c "drush scr ../scripts/content/VACMS-3450-paragraphs-should-have-a-single-parent.php"
```
1. Disable deploy mode

sudo -u apache bash -c "cp docroot/sites/default/settings/settings.deploy.active.php docroot/sites/default/settings/settings.deploy.inactive.php"

1. Remove site alerts

```
sudo -u apache bash -c  "source /etc/sysconfig/httpd; /usr/local/bin/drush site_alert:delete 'deploy-alert'"
```

**Comment by indytechcook** [comment]
test run on cms test:

Start time 6:45 pm EST
End time: 8:27 pm EST

Total time: 1 hrs 42 mins

**Comment by indytechcook** [comment]
Finished Run on production. 

Log: https://gist.github.com/indytechcook/169603b964fe9cf8e7fa7dff07ba4cb8

**Comment by ndouglas** [comment]
@cmaeng Should this be Sprint 19 or Sprint 20?  The vast majority of the work was done in 19, but some final tests and the actual fix was applied in 20.  Just checking.

**Comment by cmaeng** [comment]
@ndouglas sprint 20. reporting for each sprint typically closes on Mon or Tues. not a huge deal that it shifted as it's not a sprint goal (high priority + planned work). i'll go ahead and change the milestone. tx!
