### ISSUE TITLE
Application Performance Enhancements

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#3456]
## Background

this is an ongoing effort

### User Story or Problem Statement

As a CMS user, I want all CMS pages to load in under ~3 seconds, so that I don't have to wait as I navigate the CMS and so I can perform my work efficiently.

### Affected users and stakeholders

* CMS editors

### Hypothesis

We believe that improved application performance will achieve higher user satisfaction score.

**Comment by jefflbrauer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VAgov-CMS-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/3456?planning-poker) with ZenHub @ElijahLynn @indytechcook @ndouglas @olivereri @timcosgrove

**Comment by jefflbrauer** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VAgov-CMS-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/3456?planning-poker) with ZenHub @cweagans
