### ISSUE TITLE
Research session recording / heat map tools

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#3461]
## Description

Insights & Analytics team is open to exploring possibilities to procure a session recording / heat map tool so that it is available to the CMS and other VSP teams.

## Acceptance Criteria

- [ ] formulate the need of the CMS for a session recording / heat map tool
- [ ] compile a list of contenders w/ a summary of features / pricing models (research)
- [ ] discuss w/ the CMS team (@jordanamello @hie1 @oksana-c)

## Follow up story

*  propose options to Insights & Analytics team for vendor analysis

**Comment by oksana-c** [comment]
initial list of contenders to review

- https://www.hotjar.com/
- https://www.inspectlet.com/
- https://cdn.quantummetric.com/features/behavior-analysis 
- https://www.fullstory.com/

**Comment by hie1** [comment]
Quantum Metric demo: https://vimeo.com/398285903
QM with Medallia demo: https://vimeo.com/381221836

**Comment by TheBoatyMcBoatFace** [comment]
No longer applicable. Reopen if there is renewed interest.
