### ISSUE TITLE
CLP video panel, and add two fields to video bundle

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#3467]
ACs
- [x] Video bundle 
  - [x] Video media bundle has optional duration field that will work with Youtube API in the future, eg `"contentDetails": {     "duration": "PT4M13S"`, per https://developers.google.com/youtube/v3/docs/videos
  - [x] Video media bundle has optional description field that will work with Youtube API in the future (text format, length, etc)
  - [x] Order of fields should be Video URL, Name, Duration, Description
- [x] CLP content type has 4 fields in an optional Video field group:
  - [x] Optional `field_clp_video_panel_opt_in` Boolean with field label "Add a video panel."  Help text:  "Displays a YouTube video and an optional link to more videos."   
  - [x] ~Required~ Optional (will be required in a later iteration) "Panel Header" `field_clp_video_panel_header` with help text "This will appear as an H2 for this panel. You may want to use the video title. Or, you might provide additional context about the video that ties it to your campaign."
  - [x] ~Required~ Optional (will be required in a later iteration)  Video entity reference field... "Video" `field_media`, single value.  
  - [x] Optional "Add a link to more videos" `field_clp_video_panel_morevideos`  button component.  Help text `For example: "See more MISSION Act videos"`

Not in scope
- [ ] Behavior of boolean.  (that's happening in #3465)

Risk 
* Youtube compatibility

![CLP-Maximal_png.jpg](https://images.zenhubusercontent.com/5d6e57ad330f64311395f08b/06c72c21-18af-4362-bf5e-3b977fc08260)

**Comment by kaise-lafrai** [comment]
@kevwalsh Can you explain how the boolean field will work from the reqs below. Also the reqs say "CLP content type has 3 fields" I am seeing 4 fields: The boolean field, the Panel Header, the Video Entity Ref, the Optional: Add a link to more videos button. Thanks!


 CLP content type has 3 fields in an optional Video field group:
 -Optional field_clp_video_panel_opt_in Boolean with field label "Add a video panel".
 -Required "Panel Header" field_clp_video_panel_header with help text "This will appear as an H2 for this panel. You may want to use the video title. Or, you might provide additional context about the video that ties it to your campaign."
 -Required Video entity reference field... follow the pattern from Resources & support video list pages.
 -Optional "Add a link to more videos" field_clp_video_panel_morevideos button component. Help text TBD.

**Comment by kevwalsh** [comment]
^ i think we answered all those questions last week in a zoom call.
