### ISSUE TITLE
Wrong revision is published via bulk "Publish latest revision" action

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#3470]
**Describe the defect**

**To Reproduce**
1. Go to /admin/content/bulk?title=Psychology+Internships+and+Fellowships&type=health_care_region_detail_page&moderation_state=All&taxonomy_entity_index_tid_depth=All  
1. Use "Publish latest revision" action on "Psychology Internships and Fellowships" detail page
2. Note Oct 29 revision is published instead of Nov 5 - see "Recent changes" sidebar on the node view page.

<img width="1686" alt="Screen Shot 2020-11-12 at 11 45 01 AM" src="https://user-images.githubusercontent.com/16477724/98982836-36299800-24dd-11eb-92b3-6979c19a5938.png">
<img width="1362" alt="Screen Shot 2020-11-12 at 3 03 40 PM" src="https://user-images.githubusercontent.com/16477724/99001668-7ba78e80-24f8-11eb-8e6d-412fd3ad3e9f.png">

**Expected behavior**
Bulk  "Publish latest revision" action publishes latest revision.

## Acceptance criteria
- [ ] Bulk action "Publish latest revision" publishes latest revision
- [ ] validate that revisions are shown in correct order in "Recent changes" sidebar on nodes. If not -> open a follow up story.

## Implementation Details

The assumption is that reworking the View per notes below may address the defect of publishing the latest revision.

* views that need to show latest revision instead of latest published revision
     * /admin/content/*
     *  /admin/structure/views/view/taxonomy_term/edit/page_1
     *  /admin/content/va-forms

If the bulk action can be fixed without reworking view -> split Views rework into a new story.

**Comment by acrollet** [comment]
This code lives in Drupal\va_gov_bulk\AdminModeration::publish()

**Comment by oksana-c** [comment]
@indytechcook 🎩 off to your persistence to tackle the action issue first. I didn't realize it was a custom one. @acrollet 👏

**Comment by acrollet** [comment]
@daddison48 this ended up being more like a 5 in terms of effort in case it's important for reporting.
