### ISSUE TITLE
Q&A standalone page fields are not hidden when creating new content

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#3485]
**Describe the defect**

When new Q&A node is created, the standalone page field ("Q&A page components" fieldset) should be hidden and should not trigger form validation when Q&A content is saved without "Enable standalone page" field being checked.

**To Reproduce**
1. Go to https://prod.cms.va.gov/node/add/q_a
2. See error: "Enable standalone form" boolean field is unchecked, but "Q&A page components" fieldset is shown

**Expected behavior**
When "Enable standalone form" boolean field is unchecked, the "Q&A page components" fieldset should not be shown to the user and should fields within this fieldset should not trigger form validation errors on node save.

**Screenshots**
<img width="1104" alt="Screen Shot 2020-11-16 at 6 56 25 AM" src="https://user-images.githubusercontent.com/16477724/99260721-00382c80-27d9-11eb-9329-bbc4a3058269.png">

**Additional context**

this logic was added in https://github.com/department-of-veterans-affairs/va.gov-cms/pull/3170

**Comment by kaise-lafrai** [comment]
The code below was probably accidentally removed through another PR...

`/**
 * Implements hook_field_group_build_pre_render_alter().
 */
function va_gov_backend_field_group_form_process_build_alter(array $form, FormStateInterface $form_state, &$element) {
  // Toggle group Q&A component visibility.
  $form['group_q_a_page_components']['#states']['visible']['input[id="edit-field-standalone-page-value"]'] = ['checked' => TRUE];
}`
