### ISSUE TITLE
Post-Migration Cleanup (DevShop)

### ISSUE THREAD

**Issue by daddison48** [department-of-veterans-affairs/va.gov-cms#3503]
Terminate DevShop Instance, balancer, etc.

AC
- [x] Instance (turn off)
- [x] Docs
   -  https://github.com/department-of-veterans-affairs/va.gov-cms/blob/master/READMES/unity.md
   - [x] CMS: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/3503
- [x] Balancers and Target Groups
- [x] Security Groups
- [x] Volumes
- [x] ENIs
- [x] Instances
- [x] AMIs (backups)
- [x] Remove Oauth app
- [x] Remove va-cms-bot application token from GitHub
- [x] DNS (Route53)
- [x] Cleanup Ansible/BRD Code

**Comment by ElijahLynn** [comment]
Deleted DNS manually, wasn't in TF.

**Comment by ElijahLynn** [comment]
Also stopped instance, will do actual deletion next week after we are sure we don't need anything that was left on there.

**Comment by ElijahLynn** [comment]
I removed the Oauth app from the @va-cms-bot account a couple hours ago. :heavy_check_mark:

**Comment by olivereri** [comment]
Want to jump in on this to finish it off.

In the VSP code base I can find only these mentions of DevShop:

![image.png](https://images.zenhubusercontent.com/5f04cf8f49978b1615fee8c2/3a55f270-2f76-4924-9eae-8c08b434bbf5)
So I think the BRD cleanup is about done. The remaining resources are in the `vaec-cms` account, right @ElijahLynn ?

I checked if I still have access and appears that I can't get into the account anymore from VAEC's SSO setup.  I've submitted a support ticket to comsrequests@va.gov to try and gain access again.

**Comment by ElijahLynn** [comment]
> * [ ]  Cleanup Ansible/BRD Code
>         
>       
>   
>       Create an issue with the title Cleanup Ansible/BRD Code. Press Enter to convert to an issue instantly. Press Alt-Enter to open the create new issue form in the current tab. Press Shift-Enter to open the create new issue form.
> *

I think there were two branches pushed up to devops repo that had most of this in it. Also there are a few things around the `cms-ci` app we can look for too.

**Comment by ElijahLynn** [comment]
Deleted these just now:

**Security Group**
![image](https://user-images.githubusercontent.com/1504756/129639228-f4ee8f39-33a7-4dd2-bb8f-a8e63b324e4d.png)
**Instance**
![image](https://user-images.githubusercontent.com/1504756/129639246-7ae9e6d4-7ade-4c8c-88fd-d2665f38d882.png)
**Snapshot**
![image](https://user-images.githubusercontent.com/1504756/129639252-3e0347d3-fbec-4b87-93cb-fe8effc5710e.png)
**AMIs**
![image](https://user-images.githubusercontent.com/1504756/129639274-957dad11-7a28-46de-9e9b-bfd04c566f0a.png)
**ENI**
![image](https://user-images.githubusercontent.com/1504756/129639280-1b1f0575-b242-4bed-9cac-559bac0dd31d.png)
**Balancer**
![image](https://user-images.githubusercontent.com/1504756/129639299-e39bbd21-8286-4492-802a-4c54867f92d7.png)

**Comment by ElijahLynn** [comment]
Source code changes were made in https://github.com/department-of-veterans-affairs/devops/pull/5161 and https://github.com/department-of-veterans-affairs/devops/pull/6218 which were not merged and both those branches have been deleted.

**Comment by ElijahLynn** [comment]
Done :heavy_check_mark: - R53 DNS and remaining code has been removed in https://github.com/department-of-veterans-affairs/devops/pull/9778.
