### ISSUE TITLE
Revert updated publishing workflow and implement an alternative

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#3507]
## Description

Publishing workflow implemented in https://github.com/department-of-veterans-affairs/va.gov-cms/issues/2912 presents cognitive challenges as has been proven by multiple support requests. We need to update it.

## Proposed change 

<img width="1072" alt="Screen Shot 2020-11-17 at 1 21 07 PM" src="https://user-images.githubusercontent.com/16477724/99443353-f1846f00-28d7-11eb-8714-d6f41a5e311f.png">

## Acceptance Criteria
- [x] revert config added in https://github.com/department-of-veterans-affairs/va.gov-cms/pull/3207
   - [x] mod widget is not available on node view pages or Latest version pages for any content types
- [x] node edit moderation widget state is set to Draft as default option when the node's latest revision is Published
- [x] node edit moderation widget "Change to:" label is set to "Save as:"  @rachel-kauff to proofread tomorrow
- [x] user communication is prepared [@rachel-kauff ]
- [x] existing tests are updated

**Comment by acrollet** [comment]
@rachel-kauff just a ping to let you know that I've submitted a PR for this issue. Let me know if we want to update the wording :-)

**Comment by rachel-kauff** [comment]
Thanks @acrollet . Let's move forwards with the `Save as` label!

**Comment by oksana-c** [comment]
@rachel-kauff ,  updated publishing workflow is going out w/ tomorrow's deploy. please queue up the announcement 🚀
