### ISSUE TITLE
Video embeds for CMS help center pages

### ISSUE THREAD

**Issue by rachel-kauff** [department-of-veterans-affairs/va.gov-cms#3509]
"As a new user seeking training in the help center, I want to easily access videos so I can complete my training."

## Assumptions
* Users will be able to access training content more easily if we embed the training videos instead of linking out.
* Embedded videos are more engaging
* It will be easier for users to understand the kind of resource is on offer with a visual cue like an embed
* Users will perceived video content to be more "official" if it is embedded

## Expected outcomes

CMS User guides will utilize existing Paragraph type "Media list - Videos" that allows addition of a Section Heading + multiple videos to the page. In order to add video in that paragraph, the Video entities need to be created in the Media library first if doesnt exist yet - /media/add/video . Fields "description" and "duration" are currently optional.

"Media list - Videos" paragraph display should be customized specifically for CMS User Guides in order to avoid any conflicts with other products.

**Sample preview of Media list - Videos** paragraph rendered on the CMS User Guide page

![videos-on-user-guides](https://user-images.githubusercontent.com/16477724/102371957-f9d5d580-3f7b-11eb-8435-ad9be2c29830.jpg)

**Questions for @rachel-kauff @xiongjaneg:**
1. Section heading is an optional field - the plan is to render it as an H2 on the page. Do you foresee any issues w/ using an H2 tag versus H3?
   - [Rachel]: I don't foresee any issues using an H2. I can structure the page accordingly
2. Video title will be rendered as plain text under the video. We can render it as an H3 based on the Section Heading increment. Do we need to render video title when it's already rendered in the embedded video?
   - [Rachel]: I don't think we need to render the video title again if it's already rendered in the embedded video. Unless it's necessary for accessibility. 
   - [Oksana]: third-party widget may have rendering issues and when they do, the title will serve as a content "placeholder". So let's render it to err on the side of cuation.

Questions for @oksana-c :
- Is this assumption correct: The paragraph type "Media list - Videos" uses video entities that are added to the media library as Youtube links, not uploaded media files.
   - [Oksana]: correct. links to Youtube videos. 

## Acceptance criteria

- [ ] Media:Video has a new view mode enabled "User Guides"
- [ ] Media:Video "User Guides" view mode  is configured as follows:
    * displayed fields:
       * Video URL | Label - hidden | format - Video - embed video responsive
       * Name | Label - hidden | format - plain text
       * Duration | Label - inline | format - Natural human languages + remove the `and` separator
       * Description | Label hidden | Plain text
       
- [ ] Paragraph "Media list- videos" has a new view mode enabled "User guides" w/ following settings:
   * Section Header: Label - hidden; format - plain text
   * Videos: Label hidden; format - Rendered Entity w/ view mode - User Guides

- [ ] new template is added for `paragraph--media-list-videos--user-guides.html.twig` that renders field_section_header as an `h2` heading

- [ ] CMS Help Page content type - field_content_block `/admin/structure/types/manage/documentation_page/fields/node.documentation_page.field_content_block` allows `Media list - Videos` paragraph type as an option

- [ ] @rachel-kauff + @oksana-c to review the functionality on the PR environment and let know if any style tweaks are required before deploy to production.

**Comment by xiongjaneg** [comment]
No opinion on question 1.
Question 2: How does either option affect web accessibility, if at all?

**Comment by oksana-c** [comment]
here's a quick [article](http://web-accessibility.carnegiemuseums.org/content/third-party/) that touches on some accssibility aspects of third-party embeds. 
Video title would serve as a fallback if the video didnt load for whatever reason. It would also be wise to consider linking the title to YouTube URL, for the same reason - if the video didn't load

**Comment by ndouglas** [comment]
<img width="673" alt="Screen Shot 2020-12-21 at 2 55 54 PM" src="https://user-images.githubusercontent.com/1318579/102816829-a5c45a00-439c-11eb-81d1-6d61356a040f.png">

To be clear, the display mode for the video entity is Embedded and not User Guides?

**Comment by oksana-c** [comment]
good catch @ndouglas - it's "User Guides"
