### ISSUE TITLE
Add time zone to date fields in content proofing 

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#3510]
## User Story or Problem Statement

As an editor, i want to review the time zone info on the Node view page. 

## Acceptance Criteria
- [ ] On the proofing page for `situation_update` paragraphs (used on `VAMC system operating status` nodes, eg node 1010) and events (`event` node type, eg node 9350), editors can see the time zone specified for a date field. 

## Implementation steps
- [x] update field display settings on situation update paragraph type and event content type

![Manage_display___VA_gov_CMS](https://user-images.githubusercontent.com/643678/99538659-44633280-297b-11eb-8956-fb81e6e2ee2a.jpg)

**Comment by kevwalsh** [comment]
@kaise-lafrai i just came across this configuration page: /admin/config/regional/smart-date which might be a better implementation approach than configuring the field display each time for each use of “smart date” fields. Worth considering if we want to just add the `T` on all smart date fields this way.

**Comment by kaise-lafrai** [comment]
Good call @kevwalsh That was a much easier way of handling it.
