### ISSUE TITLE
.tugboat.yml setup

### ISSUE THREAD

**Issue by ElijahLynn** [department-of-veterans-affairs/va.gov-cms#3531]
Initial MVP Tugboat Configuration and Setup:

AC:
- [ ] PR automatically is created with a comment posted to environment
- [ ] Base image is created every 24 hours with recent DB and Files
- [ ] Tests run after creation and post back status (don't have to pass, yet)

Tasks:
- [ ] cms-export run before tests (like DEV/STAGING, this is really fast with 20 cores/processes)
- [ ] Test running in online stage
- [ ] Remove yaml-tests `va/deploy/*` steps from tests.yml
- [ ] DB/Files Import

https://github.com/department-of-veterans-affairs/va.gov-cms-test/blob/VACMS-0000_tugboat_pr1/.tugboat/config.yml (existing test config)

**Comment by indytechcook** [comment]
We are blocked on https://github.com/department-of-veterans-affairs/vets-website/pull/15285 to get the vets-website repo to build and install on tugboat.
