### ISSUE TITLE
Tugboat credstash .env setup in "init" stage

### ISSUE THREAD

**Issue by ElijahLynn** [department-of-veterans-affairs/va.gov-cms#3532]
## Acceptance Criteria

- [ ] Get an accurate .env copied into each container runtime (in the Tugboat init stage) 
- [ ] Make sure BEHAT_PARAMS are dynamically generated in .env
- [ ] Make sure the same secrets in DevShop are put into Tugboat .env file

**Comment by ElijahLynn** [comment]
Re-opening and moving to "Ready", this wasn't completed and we just used the faster method of manually adding the variables through the Tugboat UI. If a secret changes in Credstash this won't pick it up and will need to be manually updated. So, we still need to do this.

**Comment by acrollet** [comment]
@ElijahLynn could you add some background and/or a user story when you can get a chance? Thanks!

**Comment by TheBoatyMcBoatFace** [comment]
@ElijahLynn can you provide more backstory to this?

**Comment by ndouglas** [comment]
I believe this is no longer valid.
