### ISSUE TITLE
Rename all mentions of LC to R&S

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#3535]
## User Story

As a CMS user or admin, I would like to see "Resources and support" name used consistently throughout the CMS UI instead of an old product name "Learning center".

## Acceptance criteria

- [ ] Learning Center Categories taxonomy vocab is renamed to "Resources and support Categories" - /admin/structure/taxonomy/manage/lc_categories/overview
- [ ] Learning Center Detail Page content type is renamed to "Resources and support Detail Page" - /admin/structure/types/manage/support_resources_detail_page
- [ ] Lists of links paragraph description is updated to use "Resources and support" product name instead of LC + thumbnail image is updated to the one attached below - /admin/structure/paragraphs_type/lists_of_links   

![three-column-layout](https://user-images.githubusercontent.com/16477724/99722572-11e63200-2a6e-11eb-87b6-b8722684c6a2.jpg)

**Comment by kaise-lafrai** [comment]
@kevwalsh Is this a good one to get started.
