### ISSUE TITLE
All user roles should be able to enter a Revision Log message when adding or editing content

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#3542]
## User Story

As a CMS user, I should be able to enter Revision Log message in content forms that I have access to, regardless of my role.

## Description

The CMS grants the ability to enter Revision Log message via `Enter {Content Type} revision log entry.` permissions to Authenticated users.

Many content types are missing this permission, which prevents content roles besides Content Admins from entering Revision Log message for content they are adding/editing.

<img width="1672" alt="Screen Shot 2020-11-20 at 5 08 15 AM" src="https://user-images.githubusercontent.com/16477724/99799575-22d78780-2af0-11eb-9893-32ae39b423d9.png">

Example: Staff Profile Revision log message field is not available to a user w. a Content Publisher role
<img width="630" alt="Screen Shot 2020-11-20 at 5 32 48 AM" src="https://user-images.githubusercontent.com/16477724/99800903-59ae9d00-2af2-11eb-9536-6d474fed2002.png">

This issue has not been brought up to out team yet. It is likely that some users do not see missing "Revision Log" field as an issue since it is always optional.

**We know that the Revision message is a highly desirable feature because it support content lifecycle papertrail and our power users utilize this feature regularly.**

## Recommendation 

* We need to allow Revision Log field on all content types for Authenticated users in order to promote good habits within the editorial workflow.
* We need to add an automated test that verifies `Enter {Content Type} revision log entry.` is granted to Authenticated User role for all existing content types, so that in the future as we expand our content model w/ new content types, we can identified missing required features immediately.

## Acceptance Criteria

- [x] `Enter revision log entries for all node types` permission is granted to the `Authenticated user` role
- [x] Individual `Enter {Content Type} revision log entry` permissions are removed from the `Authenticated user` role
- [x] Automated test is added that verifies that this permission is enabled for the `Authenticated user` role

**Comment by acrollet** [comment]
@oksana-c I'm proposing the following revised ACs:

- [ ] `Enter revision log entries for all node types` permission is granted to the `Authenticated user` role
- [ ] Individual `Enter {Content Type} revision log entry` permissions are removed from the `Authenticated user` role
- [ ] Automated test is added that verifies that this permission is enabled for the `Authenticated user` role

This should improve the test speed and meet the requirements if I'm not missing anything?

**Comment by oksana-c** [comment]
@acrollet , yes - one permission is definitely better. Didn't know it existed 👍 Updated original ACs.
