### ISSUE TITLE
Facility services disconnected

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#3548]
**Describe the defect**
Upon an internal audit by the CMS team of facility health services,
initiated here https://dsva.slack.com/archives/CPQFCQKEH/p1605811879420400

 there were two defects found
1) The CSV incorrectly referenced `VA Oklahoma health care` as the owner instead of `VA Oklahoma City health care`  causing the owner lookup to fail and not set the owner for these services.
2. The CSV incorrectly referenced `Laramine VA Mobile Clinic` instead of `Laramie VA Mobile Clinic` causing those facility locations to not be set.

This should be resolved by:
- [x] Replace all occurrences of `VA Oklahoma health care` with `VA Oklahoma City health care` in the Owner column
https://github.com/department-of-veterans-affairs/va.gov-cms/blob/master/docroot/modules/custom/va_gov_migrate/data/facility-health-care-service-2.csv#L252-L363
- [x] Replace all occurances of `Laramine` with `Laramie`
https://github.com/department-of-veterans-affairs/va.gov-cms/blob/master/docroot/modules/custom/va_gov_migrate/data/facility-health-care-service-2.csv#L51-L56
- [x] Add skip on empty with message to owner and facility entity lookups.
- [x] add overwrite properties to overwrite the facility and owner fields but NOT field body.
- [x] run migration on prod (not as an update)  the changed rows will re-run the broken content.

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Defect")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS objective (orange) (not needed for bug tickets)
- [ ] CMS-supported product (black)

**Comment by cmaeng** [comment]
Pending a retro with Dave and Stan on Tues, 12/1.
