### ISSUE TITLE
Automate Closed issue milestone w/ GitHub Actions

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#3551]
## Description

As a Deliver Manager, I need to ensure that all issues that are closed in the current sprint have current sprint as a milestone, so that I can have confidence in the data that I am reporting on.

## Acceptance Criteria
- [ ] all issues that are closed in the current sprint have current sprint assigned as a milestone

## implementation notes

Issues that are closed within a current sprint and have no milestone assigned or have a milestone that != current sprint, should be assigned current sprint milestone.

- explore GitHub Actions

**Comment by cmaeng** [comment]
agree, this may be more work than it's worth.
