### ISSUE TITLE
Improve time zone selector

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#3555]
The new time zone selector has a painful dropdown, per user feedback. 

How might we make it easier to select time zones? 

**Assumptions**

* an editor in Arizona knows when to select Denver (for the parts of Arizona that are always MT) and when to select Phoenix, for the parts of Arizona that flip flop between MT and PT.
* an editor in Indiana knows if they should select Chicago or New York. No flip flopping in that region, just a time zone border that bisects the state.

**Not in scope, for now**

The list in the ACs covers all facilities except the ones in Manila, Phillipines. If we were to add support for Manila, it would appear first, on its own, under an Asia grouping.  That means it’s the first value that all editors would see every time, which might feel off. This can be dealt with in a later iteration when there is time to do more research. 

AC
- [ ] Event and situation update fields have a subset of time zones (less than 10) available as options

```
Americas
- Anchorage
- Chicago
- Denver
- Los Angeles
- New York
- Phoenix
Pacific
- Guam
- Honolulu
- Saipan
```

- [ ] This list has been reviewed by @rachel-kauff, @davidconlon and @johnhashva

**Comment by rachel-kauff** [comment]
@kevwalsh Can we also talk about the "duration" field as part of this work? I think this needs more consideration in relation to the datetime fields.

**Comment by kaise-lafrai** [comment]
@kevwalsh I wanted to start work on this ticket but it seems like the AC might change. Do we know what the 10 timezones would be?

**Comment by kevwalsh** [comment]
Relevant slack thread: 

https://dsva.slack.com/archives/C0FQSS30V/p1606761394235300a

**Comment by kevwalsh** [comment]
@kaise-lafrai 

Let's go with this

```Americas
- Anchorage
- Chicago
- Denver
- Los Angeles
- New York
- Phoenix
Pacific
- Guam
- Honolulu
- Saipan```

**Comment by kevwalsh** [comment]
@rachel-kauff 

> @kevwalsh Can we also talk about the "duration" field as part of this work? I think this needs more consideration in relation to the datetime fields.

Let's move that to a separate issue. Can you speak more to your concern with it? One possibility is to remove it entirely, if it isn't helpful.
