### ISSUE TITLE
Introduce new helpdesk workflow to the Core and Product Support CMS team(s)

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#3560]
## User Story

As a CMS team member, I need to understand the protocols of the CMS Helpdesk operation, so that I can focus on my work while Helpdesk takes care of business and also know exactly when my inputs are required.

## Acceptance Criteria
- [x] new helpdesk workflow is introduced to the Core and Product Support CMS team(s) in a meeting
    - help desk processes and tools
    - SLA
    - Tier 2 rotation
- [x] pinnable announcement in Slack that can summarize and/or link documents for easy reference

**Comment by erogray** [comment]
I've checked the first item ("in a meeting") since we've discussed this at length with the teams

**Comment by VanessaLuxen** [comment]
I have reached out to James Hoehn to ask if he would be willing to meet with Ero and I to transfer knowledge of TeamSite/Drupal CMS.
