### ISSUE TITLE
Workflow for managing Helpdesk requests originated in Slack

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#3561]
## User Story

As a Helpdesk rep, I need to have a protocol by which support requests originated in Slack should move and be tracked in JIRA Service Desk.

## Assumptions

* the CMS team will be encouraging all users, including power users, to submit Helpdesk requests via JSD form available in Drupal.

## Acceptance Criteria
- [x] Workflow for managing requests originated in Slack is proposed by @VanessaLuxen and @erogray 
- [x] Reviewed w/ the program team (@oksana-c @kevwalsh @daddison48 @cmaeng )
- [x] feedback incorporated

**Comment by erogray** [comment]
See process docs in https://docs.google.com/document/d/1kkxk6WBwe2YkDMQjaurvv3Tg63Q9tkwjc2aLReT1xpo/edit#
and https://docs.google.com/document/d/11JKy4P4u20fJbw1M-nRDL3K54JqYpBSwwcR6u_L867g/edit#

**Comment by erogray** [comment]
Updated these docs per @daddison48 's comments. Looks like there's some confusion here about whether we're documenting the _existing_ process for Slack and email, or the desired _future_ process that moves folks away from using Slack. (This ticket is also a little unclear about which is intended). We've updated the documents to include both.
