### ISSUE TITLE
Trim node titles on save.

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-cms#3573]
## User Story or Problem Statement

As any user, I need titles to not have trailing or leading white space.

While running the script to fix #3450, I noticed that a large number of nodes have trailing whitespace.  If an autocomplete field is set to find matches beginning with a search string, then leading whitespace can produce some irritating issues.  Trailing whitespace doesn't present these issues, but might present other issues and is simple to remove programmatically.
<img width="680" alt="Screen Shot 2020-11-24 at 8 52 09 AM" src="https://user-images.githubusercontent.com/1318579/100103476-f2b32000-2e32-11eb-912e-c6e16315c197.png">

## Implementation steps
* Implement as an EventSubscriber responding to the preSave event provided by hook_event_dispatcher
  * Use this as a revision message: "The `titlefieldname` was updated  from "`The  original title    `" to "`The new title`" to remove extra spaces. No other changes were made and this change does not affect how the title appears to veterans." 
* Implement a script to update existing nodes; see `scripts/content/` for a starting point
* In the update script, do not modify these content types, as they may trigger undesirable downstream effects:
  * health_care_local_facility
  * nca_facility
  * vba_facility
  * vet_center_cap
  * vet_center_outstation
  * vet_center
  * banner
  * full_width_banner_alert
  * va_form

## Acceptance Criteria
- [x] Leading and trailing whitespace characters are removed from node titles on save
- [x] A test has been created to confirm this behavior

**Comment by acrollet** [comment]
One potential solution: https://www.drupal.org/project/trim

**Comment by timcosgrove** [comment]
https://github.com/department-of-veterans-affairs/va.gov-cms/pull/6496
