### ISSUE TITLE
Apply opt-in boolean form behavior to CLP optional panels

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#3575]
ACs
- [ ] All 7 optional panels in CLP share the same form behavior, where fields are exposed (and potentially, required) only when an editor as opted in to the panel.

**Comment by swirtSJW** [comment]
I connnected the panels that exist as of now, and refined the logic a little bit in this PR https://github.com/department-of-veterans-affairs/va.gov-cms/pull/3581

**Comment by kevwalsh** [comment]
OK closing this as invalid. i've updated the ACs for other panels to ensure they all contain this aspect.
