### ISSUE TITLE
Content Release Job status

### ISSUE THREAD

**Issue by ElijahLynn** [department-of-veterans-affairs/va.gov-cms#3577]
## Description
Currently, when a user triggers a content deploy with the "Deploy content" button they just see a status message and need to refresh the page manually to see the results. 

We need to display real-time user feedback to the user notifying them of completion status and if there are any errors. 

## Acceptance Criteria
- [ ] User sees completion status of content deploy on PR & DEMO (Tugboat) environments (without having to refresh)
- [ ] User has a way to see logs from within the CMS (e.g. simple link to raw logs via Tugboat UI)
- [ ] When a web build status is trigger the job status should say `Pending`
- [ ] When the advanced queue job starts, the job should say `In Progress`
- [ ] When the job complete, the status should say `Sucess` if there are no error or `Error`.

Implementation notes:
- We are using advancedqueue to run the web build jobs in tugboat.  Create a block/view to show the status of the job entities from advanced queue.
- The advanced queue status block/view should auto refresh every 10 seconds
- Use a tugboat env variable to get the build ID which can be used for the link to the logs: https://docs.tugboat.qa/reference/environment-variables/

**Comment by acrollet** [comment]
@indytechcook I can look at this if you're not currently working on it?

**Comment by indytechcook** [comment]
@acrollet all you!
