### ISSUE TITLE
Training content maintenance and updates plan

### ISSUE THREAD

**Issue by rachel-kauff** [department-of-veterans-affairs/va.gov-cms#3583]
What happens when we change something in the CMS and our training content becomes outdated?

# Participants
* @xiongjaneg 
* @rachel-kauff 

# Problem Qs
* What CMS team process prompt us to update training material to accommodate changes to the application?
* How can we ensure we plan/budget for training content maintenance when planning changes to the CMS?
* How does changes to training content fit into a users' training journey? (See some ideas sketched out in the [Training service blueprint](https://app.mural.co/t/vagov6717/m/vagov6717/1605735264080/64a23a4e0bcff45cafebd576db9a787d54127dbc)
* What kinds of content ops processes do we need on our end to ensure we update ALL the affected trainng content? (What is the training and documentation editorial workflow + maintenance plan?)

# User stories
* "As a CMS editor who has already onboarded, I need to be informed of updates to the information I learned without having to re-take training modules."

**Comment by xiongjaneg** [comment]
See also [VAMC Upgrade/CMS Team meeting notes Feb. 5, 2021](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/product-team-support/product-team-weekly-syncs/vamc-upgrade-cms-weekly-sync.md)

VAMC editor training

- Some of our videos and screenshots are getting out of date, for example the navigation for VAMC sections, which editors are asking helpdesk about.
- Should those updates be done first, or should it include other changes to include other types of feedback?
- Dave: What's the impact to the help desk? Find balance between helpdesk effort and effort required for revising training.
- Vanessa: so far it's just been a couple. If it starts to be more, i can bring it to y'alls attention. If it's the same thing repeatedly...
- Dave: Could we bundle in work like Policies? What is the threshold for doing an iteration? To avoid context switching. Other potential changes
- Modularity for VAMC health service.
- Alerts and situation updates - how to write these
- Things that could be reused for CLP and Vet Centers

Platform training
508 training (first up)
Plain language
Broken links

**Comment by oksana-c** [comment]
- [ ] update any training references to Content Release frequency per Slack thread - https://dsva.slack.com/archives/CT4GZBM8F/p1615501894479000

**Comment by xiongjaneg** [comment]
closing, incorporated into quarterly epics and training runbook
