### ISSUE TITLE
Refactor Q&A Standalone boolean field logic

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#3584]
## Description

New pattern for boolean opt-in logic is being introduced in https://github.com/department-of-veterans-affairs/va.gov-cms/pull/3565 

Q&A "Enabled standalone page" boolean field that enables standalone page fields can be refactored to use the new pattern.

## Acceptance Criteria
- [ ] Q&A "Enabled standalone page" boolean field that enables standalone page fields is refactored to use the new pattern introduced in https://github.com/department-of-veterans-affairs/va.gov-cms/pull/3565 
- [ ] Q&A standalone page fields custom logic / functionality has no regressions. E.g. Tagging conditionals work as expected; required fields function as expected.

**Comment by ethanteague** [comment]
Per scrum convo on 1/11, we aren't going to do this - logic for CLP panel toggling is not similar enough to QA toggle logic.
