### ISSUE TITLE
Fix parent and revision ids on paragraphs

### ISSUE THREAD

**Issue by indytechcook** [department-of-veterans-affairs/va.gov-cms#3591]
**Describe the defect**
After the clean up of node and field data on #3450 there is still some data issues with on the paragraphs.

* `revision_id` wrong on `paragraph_item` and `paragraph_item_data`
* `parent_id` wrong on `paragraph_item_data` and `pargraph_item_revision_field_data`

The fix should look at the node/field data and update the paragraph tables accordingly.

**Comment by indytechcook** [comment]
A downtime is not required for this script to run since we are not updated the nodes or fields.

Run book:

1. `cd /var/www/cms`
1. `sudo -u apache bash -c "source /etc/sysconfig/httpd;  /usr/local/bin/drush scr ../scripts/content/VACMS-3591-fix-parent-and-revision-ids-on-paragraphs.php"`
1. `sudo -u apache bash -c 'source /etc/sysconfig/httpd; /usr/local/bin/drush cache:rebuild'`

**Comment by indytechcook** [comment]
Output of script run:

```
35 node items updated: 23, 2523, 2551, 2707, 2757, 2763, 2767, 2768, 2769, 2772, 2773, 2774, 2776, 2779, 283, 2959, 3024, 3063, 780, 779, 6257, 6951, 7015, 7282, 7714, 7769, 8413, 8458, 2356, 2764, 2765, 6255, 6259, 6261, 2803
74 paragraphs_item items updated: 8111, 8133, 8259, 8308, 8980, 8981, 8982, 8983, 8984, 8987, 9082, 9084, 9086, 9087, 9096, 9097, 9098, 9100, 9123, 9124, 9309, 9483, 9396, 9419, 9420, 9421, 9475, 9476, 3835, 8445, 8868, 8869, 8871, 8979, 5344, 5345, 5346, 5347, 5348, 5349, 5350, 5351, 5352, 5353, 5354, 5331, 9482, 11609, 11512, 12929, 12977, 12979, 13746, 13625, 8988, 7792, 8402, 9090, 9092, 9175, 9126, 9313, 9487, 9400, 9425, 9481, 5334, 9307, 9453, 9467, 7790, 8376, 8377, 8378
82 paragraphs_item_field_data items updated: 3179, 3190, 3191, 3208, 3209, 3951, 8111, 8133, 8259, 8308, 8980, 8981, 8982, 8983, 8984, 8987, 9082, 9084, 9086, 9087, 9096, 9097, 9098, 9100, 9123, 9124, 9309, 9483, 9396, 9419, 9420, 9421, 9475, 9476, 3835, 8445, 8868, 8869, 8870, 8871, 8872, 8979, 5344, 5345, 5346, 5347, 5348, 5349, 5350, 5351, 5352, 5353, 5354, 5331, 9482, 11609, 11512, 12929, 12977, 12979, 13746, 13625, 8988, 7792, 8402, 9090, 9092, 9175, 9126, 9313, 9487, 9400, 9425, 9481, 5334, 9307, 9453, 9467, 7790, 8376, 8377, 8378
21 paragraphs_item_revision_field_data items updated: 3179, 3190, 3191, 3208, 3209, 3951, 8111, 8133, 3835, 8868, 8869, 8870, 8871, 8872, 5331, 7792, 5334, 7790, 8376, 8377, 8378
```

**Comment by ndouglas** [comment]
Might be worth running the script twice just to ensure we see the expected output on the second run (0 updated of anything).  Not sure how much functional value there is there, though 🤷

**Comment by indytechcook** [comment]
Output of 2nd run:

```
0 node items updated.
0 paragraphs_item items updated.
0 paragraphs_item_field_data items updated.
0 paragraphs_item_revision_field_data items updated.
```

**Comment by indytechcook** [comment]
Final command to rebuild the CMS export files:

sudo -u apache bash -c 'source /etc/sysconfig/httpd; /usr/local/bin/drush va-gov-cms-export-all-content
--process-count=8 --entity-count=500'`

**Comment by indytechcook** [comment]
CMS re-export complete: 

```sh-4.2$ sudo -u apache bash -c 'source /etc/sysconfig/httpd; /usr/local/bin/drush va-gov-cms-export-all-content --process-count=8 --entity-count=500'
Exported config, content, and files.```

**Comment by indytechcook** [comment]
I have verified that the export content is now correct on prod for `paragraph.ba05df91-d685-495d-a9bb-da2a8919cb97.json`

**Comment by ndouglas** [comment]
Some comments on this to preserve history:

>The `entity_clone` module was installed to facilitate easily cloning large, complex pieces of content.  However, the user interface for the clone form was worded very technically and did not operate in a particularly intuitive fashion.  As a consequence, editors created  a substantial amount of content that shared references to different revisions of the same components; specifically, paragraph entities.  This corruption constituted a critical risk of losing substantial amounts of data, without warning,  as a result of the normal editorial workflow.

>To address this, we created a script that inspected each of the cloned pieces of content and freshly generated new paragraphs for the cloned content.  The original pieces of content were left untouched, with their own original copies of the paragraphs.  Thus, the references from each cloned piece of its content to its paragraphs were made whole.  This resolved a large portion of the problem, but not all of it.

>The content export process uses references that point from the paragraph to its default revision. In the cases of the paragraphs owned by the original content, these references pointed to revisions of the paragraph that were current from the perspective of the cloned piece of content rather than the original piece of content.

>For instance, an article about the Pittsburgh VA might have a link that pointed to a specific page about the Pittsburgh VA.  Then the original page might be cloned for the Altoona VA, and the link updated to point to a page about the Altoona VA.  In the editorial interface for the Pittsburgh article, the link would appear consistent and point to the Pittsburgh VA page.  Similarly, the link in the editorial interface for the Altoona page would appear consistent and point to the Altoona VA page.  However, the content export might show the Pittsburgh VA article linking to the Altoona VA page.

>So we wrote a second script, intended to sift through the original pieces of content, inspect each of their paragraphs, and determine whether their revisions pointed to the correct revision (i.e. the one referred to by the owning piece of content) or some incorrect revision (owned by a clone of the original).  The raw database tables were edited to point to the appropriate revisions.  This should result in a consistent database structure and alleviate the issues experienced in the export process.  Comparisons of the export process before and after script execution indicated that the script had the desired effect.

>However, this process did not fully function as intended.  The source of truth for the operation was the original content’s references to the paragraphs they contained.  Unfortunately, this is not the ultimate source of truth as used by the editorial interface or content export.  In the case of approximately 30 pieces of content, the original pieces of content referred to the wrong revision of their paragraphs and so did not constitute a reliable source of truth.  Consequently, after the script was executed, the original pieces of content would, in both the editorial interface and exported content, contain references to incorrect content.  In our example from earlier, the Pittsburgh VA page might contain references to the Altoona VA.
