### ISSUE TITLE
"Document - external" Media bundle

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#3602]
## User Story or Problem Statement

As an editor, i want to add files that are not hosted by the CMS (CLP).
In the future, as an editor, i want to add files that are not hosted by the CMS, OR files that are managed by CMS, from the same interface. 
As an editor, i don't want to have to entire mimetype into any field. 

As an end user, i want a consistent experience for seeing and interacting with downloadable files, with mimetype displayed in parentheses

## Acceptance Criteria (still WIP)
- [x] `document_external` media bundle "Document - External" label
- [x] `Name` field (title) max 70 characters  with "70 characters remaining"
- [x] `field_description` with field label ~"Short description"~ "_Description_" max 100 characters, textcounter **with "100 characters remaining"** on form widget
- [x] `field_mime_type` MIME type **should not be editable**
- [x] `field_media_external_file` Link field = naming convention required / generated by new file type to make compatible with media **Change field label to "External File URL" and add help text: "PDFs only"**
- [x] `field_owner` `Owner` field
- [x] `Document - External` bundle is enabled in Workbench Access 
- [x] No editorial workflow
- [x] PDFs only form validation on the File type field (for now, for CLP... this may change in the future).

**Comment by ethanteague** [comment]
Logic for this is handled in https://github.com/department-of-veterans-affairs/va.gov-cms/pull/3601
