### ISSUE TITLE
"All articles in: <Tag>" View displays duplicate items

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#3603]
**Describe the defect**

1. Some articles are listed multiple times when displayed in "All articles in: <Tag>" View 
1. The Service member tag should be showing one test article on the dashboard list view (see VetSuccess test article in draft) but it shows nothing: https://prod.cms.va.gov/resources/tag/service-members

**To Reproduce**
1. Go to https://prod.cms.va.gov/resources/tag/sign-in OR https://prod.cms.va.gov/resources/tag/all-veterans
2. see that title "TEST COPY: Emblems of belief for headstones and markers" is listed 3 times

**Expected behavior**
1. each title is listed only once.
1. articles are listed in "All articles by <tag>" listings if they are tagged w/ the corresponding tag

**Screenshots**

![image](https://user-images.githubusercontent.com/16477724/100776814-41783100-33c2-11eb-82c8-e48be5042858.png)

**Additional context**

titles are duplicated on tag views (Topics and Audience vocabs), e.g https://prod.cms.va.gov/resources/tag/sign-in 
but not on the similar category views (Learning Center Category vocab) e.g. https://prod.cms.va.gov/resources/burials-and-memorials

**Comment by jenniferlee-dsva** [comment]
Here is another example showing the same issue above. On this CMS dashboard view for all articles tagged: Vietnam Veterans. 
https://prod.cms.va.gov/resources/tag/vietnam-war-veterans 

![image](https://user-images.githubusercontent.com/43381063/101193702-f9a81280-362a-11eb-9ed4-d1c6836c0dee.png)

**Comment by kevwalsh** [comment]
@ethanteague i think there were two defects here, but possibly only one was fixed. 

See "The Service member tag should be showing one test article on the dashboard list view (see VetSuccess test article in draft) but it shows nothing: https://prod.cms.va.gov/resources/tag/service-members"

node 6950 looks like it should appear on the above URL

![Edit_Media_list_-_Videos_TEST_COPY__Watch_VetSuccess_on_Campus_videos___VA_gov_CMS.jpg](https://images.zenhubusercontent.com/5d6e57ad330f64311395f08b/3824eb11-b670-4481-bb4e-0ba42d67d077)

**Comment by kevwalsh** [comment]
From @ethanteague via Slack:

> So, I looked at this one before and tested by adding Service members to a node, hitting save, and then visiting the term page. Doing so revealed the newly saved node. If I go to node 6950, and just hit the save button, it appears on the term page. This might be related to the revision bugs we had over the last week. Either way, do we have a lot of nodes that have this particular term? If it's just a couple/few, would it suffice to just hit save on the problem nodes, @Kevin Walsh?
