### ISSUE TITLE
Create New CMS Directories in devops/terraform/environments

### ISSUE THREAD

**Issue by olivereri** [department-of-veterans-affairs/va.gov-cms#3604]
https://dsva.slack.com/archives/CBU0KDSB1/p1606841545302500?thread_ts=1606778111.249700&cid=CBU0KDSB1

Purpose:
Isolate and insulate CMS from other project changes in Terraform. This will reduce PR Merge friction for CMS infrastructure changes.

AC:
- [ ] Create new Terraform environments for CMS:
  - [ ] cms-vagov-dev
  - [ ] cms-vagov-staging
  - [ ] cms-vagov-prod
- [ ] Move cms.tf, cms-test.tf and tugboat.tf to those directories.
- [ ] modify input variables to use data resources instead of the direct resource

**Comment by ElijahLynn** [comment]
Thanks for creating this @olivereri. Per the thread, we just decided to backlog for now as @pnwstevan fixed the EKS cluster permission issue.

**Comment by ElijahLynn** [comment]
Closing now as Ops figured out a way to not need IAM EKS cluster permissions which was the original reason (Slack thread above) that this issue was suggested, and trying to solve.
