### ISSUE TITLE
CLP events panel

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#3605]
![CLP-Maximal-markup-updated-060320_pdf__1_page_.jpg](https://images.zenhubusercontent.com/5d6e57ad330f64311395f08b/f0778e1d-3e0d-4125-990a-b0a8bf6a42d1)

ACs
- [x] `field_clp_events_panel`
  - Boolean field labeled "Add an Events panel" 
  - True label: "Events panel"
  - False label: "No events panel"
  - Help text: "Add links to up to two events (these events must already be stored in the CMS)."
- [x] `field_clp_events_header`
  - Plain text single line field, help text: `For example: "Attend a MISSION Act event near you"` 
  - Maximum 70 characters
  - Textfield with counter "N characters remaining"
- [x] `field_clp_events_references` 
  - [x] Field label: `Add up to two events`
  - [x] Only events are allowed, and only two of them.
  - [x] Field widget: autocomplete, for now. 
    - [ ] Stretch: only allow future events (eg, an entity reference view display showing only future events)
    - [x] Extra stretch: Entity browser for events, showing only future events, with search filters for Owner and Title.  
    - [ ] If we don't get to the stretch version, we will create a separate story for this iteration. 
- [x] `field_clp_events_panel` is optional, but once it is selected, the other two fields are required.

**Comment by kaise-lafrai** [comment]
> field_clp_events_panel is optional, but once it is selected, the other two fields are required.

@kevwalsh Should this be moved out to a separate ticket to handle this type of behaviour?

**Comment by kaise-lafrai** [comment]
![image.png](https://images.zenhubusercontent.com/5f04cf76eb6c0026ebd18020/5a72b6fb-66da-449f-9abf-6bef61bcbf94)
