### ISSUE TITLE
Facility health service contact info does not correctly render styling

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-cms#3616]
## What happened?
Facility Health service contact information section does not correctly render styling in devshop and on staging

- Styling for address block is incorrect
- Hours appear in table form

<details>
<summary> Example from Pittsburgh devshop Primary care accordion</summary>

![image](https://user-images.githubusercontent.com/55411834/100918664-05ae9b80-3496-11eb-87e1-97bc23d4ee89.png)

</details>

## Steps to Reproduce
- URL: [Devshop](vamcupgrade.web.demo.ci.cms.va.gov/pittsburgh-health-care/locations/pittsburgh-va-medical-center-university-drive/)

## Desired behavior
Environments reflect correct design spec

## ACs
- [x] Function that cleans up html tags in tablefield has been made specific to tablefields with all filter formats. This has been resolved by https://github.com/department-of-veterans-affairs/va.gov-cms/pull/3617 which is now merged.
- [ ] Any facility health service content and facility nodes  has been updated with a script that is run after code deploy, to strip out any html that had been added 
    - content types -> field to be processed to clean the data.  These should be fixed at the revision level, not at the node level.  So that all revisions are fixed.  (see scripts/content/VACMS-2812-update-timezone-data-2020-11.php for the general approach).
       - health_care_local_facility -> field_facility_hours
       - health_care_local_health_service ->  field_service_location -> service_location  -> field_facility_service_hours
    - strings to remove 
```
$strings_to_remove = [
  '<p>',
  '</p>',
  'p&amp;',
  '/p&amp;',
  '&amp;lt;',
  '&amp;gt;',
  '&amp;',
  'amp;',
  'gt;',
  'lt;',
];
```
- [ ] Times and days are all that remain after strings are removed.

**Comment by swirtSJW** [comment]
https://github.com/department-of-veterans-affairs/va.gov-cms/pull/3617 has been merged.   So that will prevent future data corruption and will allow for manual fixing of pages with issues.  

However, we will need an update script that removes noise like this 
```
&amp;lt;p&amp;gt;&amp;amp;lt;p&amp;amp;gt;&amp;amp;amp;lt;p&amp;amp;amp;gt;&amp;amp;amp;amp;lt;p&amp;amp;amp;amp;gt;&amp;amp;amp;amp;amp;lt;p&amp;amp;amp;amp;amp;gt;&amp;amp;amp;amp;amp;amp;lt;p&amp;amp;amp;amp;amp;amp;gt;&amp;amp;amp;amp;amp;amp;lt;/p&amp;amp;amp;amp;amp;amp;gt;&amp;amp;amp;amp;amp;lt;/p&amp;amp;amp;amp;amp;gt;&amp;amp;amp;amp;lt;/p&amp;amp;amp;amp;gt;&amp;amp;amp;lt;/p&amp;amp;amp;gt;&amp;amp;lt;/p&amp;amp;gt;&amp;lt;/p&amp;gt;
```
from all facility and facility service shedule tablefields.

Updating ACS now

**Comment by swirtSJW** [comment]
Just to be clear.. the content clean-up will have to be done at the revision level to fix all revisions, not the node or paragraph itself.  There should be no entity save as part of the process.  It should resemble scripts/content/VACMS-2812-update-timezone-data-2020-11.php though in that one we were copying data.  This will simply be pulling directly from db, altering and updating directly in the db.

Consult with Kaise, or maybe have him work on this.

**Comment by kevwalsh** [comment]
@swirtSJW `health_care_local_facility` -> `field_facility_hours` is migrated in from VAST. not sure if any data corruption is possible there since the migration doesn't go through the filters, and it's disabled in the UI. Have we verified that it it needs targetting here with the data cleanup step?

**Comment by swirtSJW** [comment]
@kevwalsh That data is corrupted if the node has ever been saved by something other than the migration or any reverse entity reference to that facility.... as in all the migrated facility services.   Yepp   it is a big problem  :(

**Comment by swirtSJW** [comment]
The last of these PR's was merged on Friday.  It will go out with today's release and will need to have the script run on prod after release.  Then this will be considered done.
