### ISSUE TITLE
Hide "Remove" button for all instances of field_tags on RS content types

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#3626]
## User Story

As an editor, I do not want to see the "Remove" button when I add tags since at least 1 Tag is required and the experience of removing and having to add the Tags paragraph back is very confusing.

<img width="1056" alt="Screen Shot 2020-12-03 at 11 20 10 AM" src="https://user-images.githubusercontent.com/16477724/101071530-f98c1200-3559-11eb-8c47-9829eb7b5701.png">

## Acceptance Criteria
- [ ] field_tags is marked as required for all R&S content types in order for "Remove" button to be hidden
- [ ] there are no regressions in Tag selection functionality (min 1, max 4)

R&S content types:
- Checklist
- Step-by-step
- Learning Center Detail Page
- Media list- Images
- Media list- Videos
- Q&A
- FAQ - multiple Q&As

**Comment by FranECross** [comment]
Closing ancient ticket; if this issue crops up again, we'll create a new ticket.
