### ISSUE TITLE
Data points and prioritization criteria for component/pattern inventory

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#3640]
## User story

As a CMS Design System team member, I need to know which data points are useful about each component or pattern, so that I can collect structured data as I take inventory of the CMS component and pattern.

As a CMS Design System team member, I need to understand the criteria that will be used for prioritizing DS design/implementation, so that I can collect any relevant data as a part of the inventory effort.

## Participants

**Prep:** @hie1 @jordanamello 
**Group discussion:** @hie1 @jordanamello @acrollet @rachel-kauff @oksana-c 

## Acceptance Criteria

- [x] data points for component/pattern inventory effort are defined
- [x] criteria that will be used for prioritizing DS design/implementation work for components/patterns are defined
- [x] team has discussed and agreed to defined set of data points and prioritization criteria

## Implementation notes

initial brainstorm notes are collected in the Lucidchart doc "Definition of UI Components, Content Model and UI Patterns"  ([Edit URL](https://lucid.app/lucidchart/3488ef2a-dd3f-48dc-b8ea-dccc14370a47/edit), [Public URL](https://lucid.app/documents/view/3488ef2a-dd3f-48dc-b8ea-dccc14370a47))

**Comment by hie1** [comment]
Per Oksana on 12/8/20: develop at a high level; for example - where it is used, in what context, what variations exist (language) - maybe better as a number of variations; screenshots

**Comment by jordanamello** [comment]
Work is being done here: https://airtable.com/tblfXkiJtDS4sfZFT/viwds33yLpz7VkrL8?blocks=hide
