### ISSUE TITLE
Design tool for creating and maintaining Design System spec

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#3641]
## User Story

As a CMS UX Design or Engineer supporting the CMS Design System, I need access to a Design tool that allows for efficient collaboration on the Design System spec.

## Acceptance Criteria
- [x] tools are reviewed for features and the preference is identified
- [x] licenses are available for the following team members: @jordanamello @hie1 @oksana-c @rachel-kauff 

## Criteria for tool selection

* supports public access to the DS spec
* supports real-time collaboration
* supports versioning
* supports prototyping / addition of micro-interactions (e.g. demonstration of a component interactions/states)
* supports component libraries that can be shared w/ other team members and user for rapid prototyping

**Comment by oksana-c** [comment]
linking Slack thread kicked off by @jordanamello  for reference https://dsva.slack.com/archives/CDKB88PS8/p1606919857263000

**Comment by jordanamello** [comment]
Comparison spreadsheet: https://docs.google.com/spreadsheets/d/11q4jZ-fsv453xKiFkyXMMHJiFz6-7YPH_xv898En-x0/edit?usp=sharing
