### ISSUE TITLE
Revise CMS Rules of Engagement

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#3644]
Now that we've updated the [Content Management System overview page](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/cms), we need to update the [CMS Rules of Engagement](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/working-with-cms-team.md).

## User Story

As someone who is looking to collaborate with the CMS team or simply looking for info on how the CMS team can augment and aid my efforts, I need to understand how to engage relevant CMS team resources in a collaboration cycle and I need to understand what this collaboration cycle may look like before I reach out.

## Acceptance Criteria

- [ ] the CMS Rules of Engagement page contains up-to-date and comprehensive information about:
	- [ ] why/when/how to engage w/ the Core Application or Product Support Teams
	- [ ] CMS collaboration points for VFS and VSP teams building products on the CMS, requesting new features / enhancements or using products that the CMS team already supports (e.g. content export)

## Notes

* written summary of the process
* visual artifact describing CMS collaboration cycle. Perhaps in some ways similar to [VSP Collaboration Cycle artifact](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/working-with-vsp/vsp-collaboration-cycle)

**Comment by jefflbrauer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VAgov-CMS-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/3644?planning-poker) with ZenHub @ElijahLynn @indytechcook @ndouglas @olivereri @timcosgrove

**Comment by jefflbrauer** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VAgov-CMS-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/3644?planning-poker) with ZenHub @cweagans

**Comment by TheBoatyMcBoatFace** [comment]
@EWashb can I close this?

**Comment by EWashb** [comment]
We are reimagining this work as part of the CMS transition to platform. Ok to close this one as not within current scope.
