### ISSUE TITLE
Select CSS Pre / Post-processing Tool

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#3645]
## Description

There are several capable CSS preprocessing/ transformation tools out there. We currently use SASS, but we don't have to stick with it.

## User Story

As a front-end engineer, I want to use a tool that reliably transforms the css I write into cross-browser compatible syntax, is configurable and supports features that make me more efficient (mixins, autoprefixer, etc).

## Considerations during tools review

- highly configurable
- supports variables and mixins
- offers efficiencies
- real time compilation / supports real-time preview
- maintainable
- supports needs of the project without bogging us down w/ extras we don't need

## Tools to review

- Sass
- PostCSS
- Stylus
- Less

## Acceptance Criteria

- [ ] CSS Pre/Post-processing tools are analyzed for supported features and a minimal comparison is available for review w/ a rationale for the best contender
- [ ] tool comparison is peer reviewed (@acrollet @oksana-c )
- [ ] a tool for the `uswds_admin` and subthemes is selected

**Comment by oksana-c** [comment]
Sass, PostCSS, Stylus and Less preprocessor tools have been reviewed. Comparison table is available [here](https://docs.google.com/spreadsheets/d/1eYI-PgiM8V8lj9SXuQ5lY72lVXYGJoH9t4reE6ezpWk/edit#gid=0).

My assessment is that we should use PostCSS in development of uswds_admin and its subtheme. Here's a summary that explains why:

* PostCSS provides flexibility to build our own stack and standard that will deeply improve our CSS. It integrates really well with any build tool of our choice: npm / yarn, gulp/grunt.
* The main benefit PostCSS provides over Sass or Less is the ability to choose our own path, and cherry-pick the features we need. Sass or Less are “fixed”, we get lots of features which you might or might not use, and we cannot extend or disable them.
* The most compelling advantage is in the limitations imposed by writing vanilla CSS. In PostCSS you write CSS (not scss) w/ the use of variables or mixins of choice. This may seem like a disadvantage at first for those who used to write nested Sass rules. The trick here is to find balance of unique classes which we can easily add to markup to reduce long-running list of classes in a rule. Ultimately this _should_ prevent us from writing unnecessary CSS.
* We can enforce best practices when PostCSS is configured correctly. The goal is to write CSS that is DRY, reusable, less specific, no deep nesting, etc (need to resist the urge to include mixins everywhere and set standards to use them sparingly)
* Drupal community (contrib and core) is already working w/ PostCSS.

@acrollet please take a gander at the comparison table and resources linked in it. I'm interested in your take on this.

**Comment by acrollet** [comment]
I've reviewed the comparison table and read the linked resources and I agree with your conclusion. Here are my top points in favor:

- Aligning with the Drupal community
- Readable output (simplifies review of changes and helps ensure we know what we are shipping)
- Ability to tailor the options available and build process to our specific needs
