### ISSUE TITLE
Entities should not allowed to be published if a referenced entity is not published.

### ISSUE THREAD

**Issue by indytechcook** [department-of-veterans-affairs/va.gov-cms#3662]
## Description

When publishing an entity which has an entity reference that is not published, there should be a validation error on the field not allowing the entity to be published.

## Acceptance Criteria
- [ ] validate assumptions made above
- [ ] A new test is created to not allow entities with unpublished references.
- [ ] An entity should not be allowed to be published if there is a referenced entity that is unpublished.

**Comment by oksana-c** [comment]
closing, as we will explore less restrictive methods of avoid unpublished content on prod in this spike https://github.com/department-of-veterans-affairs/va.gov-cms/issues/3692
