### ISSUE TITLE
Services taxonomy discovery 

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#3663]
ACs TBD
- [x] We shared an understanding with Facilites team regarding the opportunities and constraints for forking or iterate on the existing VAMC health service taxonomy (or its terms).

**Comment by nataliedunbarCS** [comment]
12/11 - Met with POs to discuss the health services taxonomy and to identify deltas and potentially problematic terms that might need to be changed for Vet Center use. Reviewed and proposed potential changes to VHA names (column C), and discussed whether to use a "forked approach" to allow for variations, or to allow an "override" function for Vet Centers within the CMS.

Next steps: 

1. Jenny HL to socialize proposed VHA name changes with Vet Center to garner feedback
2. Research - results pending
3. CMS team to look into governance issues that may impact how we decide to “fork” vs “override” in the content model
