### ISSUE TITLE
Block "What's new in the CMS"

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#3680]
## User Story

As a CMS user, who's browsing CMS Help Center, I'd like to have info about when something new happened in the CMS at a glance, so I can decide whether or not I need to dig in for further info.

![whatsnew](https://user-images.githubusercontent.com/16477724/101687912-6dca2800-3a28-11eb-98ee-61848747887f.jpg)

@jordanamello provided block styles spec
<img width="608" alt="Screen Shot 2020-12-17 at 10 14 01 AM" src="https://user-images.githubusercontent.com/16477724/102520344-daf54300-4050-11eb-9132-979557966f1a.png">

Note: event though height and width measurements are marked on the screenshot - the resulting styles should be made acceptably  responsive on smaller screens.

## Acceptance Criteria

- [ ] a block that displays a link to the CMS Announcement page and the date of the latest published revision of this page is placed on all pages that have the following URL pattern `/help/*`

## Implementation steps

- custom block plugin with attached css library
- block is placed in Second Sidebar region and is restricted to pages w/ url pattern `/help/*`
- bullhorn svg icon is here https://drive.google.com/drive/folders/1hlnNgP6UHV_ZvKHVP6vTvA0kGrq56Hn9

**Comment by ndouglas** [comment]
<img width="403" alt="Screen Shot 2020-12-22 at 12 54 15 PM" src="https://user-images.githubusercontent.com/1318579/102922591-43329300-445c-11eb-9904-172afab61333.png">

The design as I work on this is clashing a bit with the CTA block also present on the `/help/*` pages, unless I'm missing something.  (I almost surely am.)

We don't have that precise date format available; not sure whether to add it, #yolo it, or if it was just used for illustration 😄

**Comment by oksana-c** [comment]
resulting pattern short-term: `mm/dd/yy hh:mm am TZ`
