### ISSUE TITLE
Make COVID-19 health service data available to Lighthouse

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#3682]
## Questions 

- do we need to push data, like Facility status or is pull OK? We don't know how often Lighthouse pulls right now. Push would make the data available through Lighthouse immediately. 
- if it's push: 
  - it will be based on node save (when a CMS editor edits a VAMC Facility Health Service, Drupal will push this data to Lighthouse). 
  - We could leverage the same method used by Facility status 
  - for now we would only want to push COVID, but what determines the services that may want to push in the future (are they the same as those that have Health Service API IDs [on this page](https://prod.cms.va.gov/vha-health-services)? 
- ~if it's pull~
   - ~it might follow a similar approach to VA Forms. Should they pulling more than just COVID-19 Facility Health Services?~
   - ~We're not sure what they are pulling now.~
- what's the Health Service API ID for Lighthouse? 

**Next step: get on the phone with Lighthouse folks about the above.** 

ACs
- [ ] Lighthouse gets updated content upon each Facility Health Service status change, when it uses the COVID-19 Vaccines Taxonomy Health Service API ID. 
- [ ] Additional ACs TBD

## Assumption

1. Facility Locator doesn't want content from VHA service taxonomy term or VAMC system health service, and we don't need system-based availability, everything will be facility based)

**Comment by swirtSJW** [comment]
This code is parked in the pr https://github.com/department-of-veterans-affairs/va.gov-cms/pull/3794   and is on hold and depending on finalization of the API by Lighthouse.    Our final steps are defined in the runbook for the epic.  Considering the major lift of this part done.
