### ISSUE TITLE
Improve contextual help for VAMC product

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#3686]
### User Story or Problem Statement

As a VAMC Editor, I need to have clear guidelines within content forms that Im using daily, so I can be confident that I am entering content the right way in the right places and I know where to look for more information if I need it.

### Affected users and stakeholders

* VAMC Editors

### Hypothesis

We believe that improving contextual help within VAMC content entry forms and dashboards will help reduce the amount of questions during training and the amount of CMS Help desk request related to the VAMC product.

We'll know that to be true when:
* we can point to a place in the CMS instead while answering questions live
* the amount of Helpdesk support request about creating/editing/maintaining VAMC content is decreasing

**Comment by kevwalsh** [comment]
Closing this, it will be feature-by-feature (like Hours UX, or Operating Status UX)
