### ISSUE TITLE
As a VAMC Editor, I need better guidance on the difference between System and Facility Health Service when navigating the CMS

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#3687]
## User Story

As a VAMC Editor, I need better guidance on the difference between System and Facility Health Service when navigating the CMS

Feedback from Ryan Stubblebein: As a content editor, I need to know how to find/edit content on the health system health service so that I can make the changes I need quickly and accurately.

## Problem statement

New CMS Users who are onboarded via live training have difficult time differentiating between System and Facility Health Services. As they start using the system, there are several ways for the user to build their mental models around which is a System level content and which is Facility level. 
We can help users build their mental models faster if we provide consistent guidance throughout application in a form of Content Type Labels, Descriptions and contextual help text.

## Acceptance Criteria

- [ ] the CMS UI is reviewed for opportunities where we can provide better guidance for VAMC System Health Service and VAMC Facility Health Service content types. E.g. content type labels, content type descriptions and contextual help text
- [ ] any recommendations resulting from this review are incorporated into the future VAMC dashboard design
- [ ] recommendations for updates in the CMS UI are peer reviewed
- [ ] follow-up implementation backlog items are created

**Comment by erogray** [comment]
Relevant to https://github.com/department-of-veterans-affairs/va.gov-team/issues/19213

**Comment by mmiddaugh** [comment]
Received feedback on this issue from Ryan Stubblebein, Pittsburgh VAMC during a meeting this morning

**Comment by jilladams** [comment]
@stefaniefgray @TroyA6 low priority: do y'all have thoughts on whether this is still an issue for editors?

**Comment by stefaniefgray** [comment]
@jilladams No, it was only an issue with system vs. facility nodes when Top Task Pages were being created, but otherwise, most editors seem to know the difference between system and facility health services

Can close!
