### ISSUE TITLE
Initial migration of Covid 19 Vaccine health service data (which systems and which facilities offer)

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#3688]
This work depends on how certain questions in the parent epic, #3684, are answered.

Dependency: decisions from @davidconlon:

1. what additional values we may want to specify during migration (like appointments, walk-ins accepted, service location fields)
1. who will own the System and Facility Health Service content related to Vaccines? 

Once we have decisions around these, we will work to reduce risk of data integrity problems in source data. 

Risk
- data integrity

AC
- [ ] initial batch of COVID 19 vaccine system and facility health services is saved in Drupal

## Implementation Details
- Enable covid-19 taxonomy term in production: /taxonomy/term/321/edit?destination=/admin/structure/taxonomy/manage/health_care_service_taxonomy/overview

- System health service migration
   - Should follow (copy) docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.regional_health_care_service_region_keyed.yml
   - named: `migrate_plus.migration.regional_health_care_service_covid.yml`
   - Migration dependency on `health_care_region_page`.
  -  change field_service_name_and_descripti: to `field_service_name_and_descripti: 321`   (covid 19 taxonomiy term ID)  No need for entity lookup or skip  on empty.
   - data in CSV named docroot/modules/custom/va_gov_migrate/data/health-care-service-covid.csv
   It will look like this and will be used for BOTH system service and facility service migration.
![image](https://user-images.githubusercontent.com/5752113/102371883-aa4bd580-3f8c-11eb-866b-68a35bcf52bc.png)

Station ID | VAST Facility Name | Health Care System Name | Health Care System ID | facility service description | system service description

    - health care system name column should be the migration key id so duplicates in that will not be repeated.
    - unused columns: 
       - Station ID
       - VAST Facility Name
       - Health Care System ID
       -  facility service description

- Facility health service migration
    - Should follow (copy) docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.facility_health_care_service_2.yml
       - The **MAJOR** difference on this migration is that the `field_facility_location` entity lookup "value_key" will need to be by the field `field_facility_locator_api_id` rather than `title` and a new column will need to be added in the CSV to provide the field_facility_locator_api_id value.
   - - Migration dependency on `regional_health_care_service_covid`.
   - named: `migrate_plus.migration.facility_health_care_service_covid.yml`
   - data in CSV created in system service migaration  ^^^
   - migration key should be station id.
   - for location lookup will need to do concat `vha_`  See system migration for example.  
   - unused columns: 
       - Health Care System ID
       -  system service description

**Comment by swirtSJW** [comment]
I am reworking some of the implementation details based on the data we are getting from Dave.   Already discussed with Kaise.

**Comment by swirtSJW** [comment]
@kaise-lafrai Implementation details have been updated to reflect our discussion from this morning.

**Comment by kaise-lafrai** [comment]
@swirtSJW Will Dave provide the `field_facility_locator_api_id`s?

**Comment by kaise-lafrai** [comment]
@swirtSJW Ready for initial review

**Comment by swirtSJW** [comment]
Testing.   This worked great.  Here is the proof.
![image](https://user-images.githubusercontent.com/5752113/102580893-7cba7580-40cd-11eb-85d7-3a5365ce61c8.png)


![image](https://user-images.githubusercontent.com/5752113/102580906-83e18380-40cd-11eb-9dbf-158ae0ac682f.png)


![image](https://user-images.githubusercontent.com/5752113/102580914-88a63780-40cd-11eb-87cf-a787d79b6979.png)


no errror messages
![image](https://user-images.githubusercontent.com/5752113/102580929-9065dc00-40cd-11eb-842e-fbb7ae833886.png)



![image](https://user-images.githubusercontent.com/5752113/102580948-965bbd00-40cd-11eb-9dab-ec449181a6db.png)



![image](https://user-images.githubusercontent.com/5752113/102580958-9b207100-40cd-11eb-879a-a606727814b2.png)



Also checked on Lovell
![image](https://user-images.githubusercontent.com/5752113/102581098-e175d000-40cd-11eb-9a9c-dd6381ed72d4.png)
  it did not end up with 2.

**Comment by swirtSJW** [comment]
This was merged  https://github.com/department-of-veterans-affairs/va.gov-cms/pull/3819

All of the CMS team work is done.  We are just waiting to update the CSV with the final data from @davidconlon (Phi  zer and Med  erna)

**Comment by swirtSJW** [comment]
We are going to call this part done and create a ticket that is the final runbook that will handle finalized data, finalized lighthouseAPI and running this all on prod.
