### ISSUE TITLE
Managing unpublished entity references [CMS AX and Content API]

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#3691]
## Background

Several unpublished Staff Profiles that were rendered on VA.gov were identified during the transformers work for the Facilities Team: [Slack thread 1](https://dsva.slack.com/archives/C0FQSS30V/p1607006484311200) , [thread 2](https://dsva.slack.com/archives/C0FQSS30V/p1607411003428300)

Unpublished content should not rendered on VA.gov even if it is referenced by the parent page. 
This guideline is upheld by content export, where unpublished entities are not offered as data for FE intake. Although GraphQL which is currently used for all Prod content, does not prevent engineers from forming queries where unpublished content is pulled into templates.

The CMS is not responsible for monitoring FE queries to Content API, therefore cannot guarantee that unpublished content will not be rendered on VA.gov pages. 

Since Content Export will soon replace GraphQL for node content queries and Content Export has already taken care of unpublished content leak risk, any additional work to prevent references to unpublished content or any GraphQL tweaks, may be moot. Although there's still a question of Content Preview and that there may be a potential lack of content parity between prod and preview.

The CMS can improve Authoring Experience to ensure that Content Editors know whether content referenced by other pages is published, so that a layer of editor validation is fully supported while proofing and previewing pages that are about to go to live.

### User Stories

As a Content Editor, I need to know whether entity references that I attached to my page are published, so that I clearly understand which of them will be visible on VA.gov once I publish the page.

As a CMS Content API Maintainer, I need to provide guidance around Published/Unpublished entities to teams who consume Content API, so as to prevent rendering of unpublished content live.

_Other TBD_

### Affected users and stakeholders

* CMS editors
* Engineers who work with Content API (Content Export and GraphQL)

### Hypothesis

_A hypothesis may depend on a spike ticket to be completed._

We believe that _this_solution_ will achieve _this_outcome_. We'll know that to be true when _this measurable outcome occurs._

### Assumptions
* Tk
* Tk

(How will these assumptions be validated?)

## Acceptance Criteria
- [ ] 👀 Needs design review because the work involves changes to labels or other design elements
- [ ] 🙈 Can be implemented without consulting design team members
* Testable_Outcome_X
* Testable_Outcome_Y
* Testable_Outcome_Z

**Comment by EWashb** [comment]
This is currently not in scope. Closing
