### ISSUE TITLE
Collect User Section via GA/GTM

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#3693]
## User Story

As a researcher, I would like to segment GA data by User Section, so that I can analyze the behavior by specific audience, e.g. VAMC users.

## Acceptance Criteria

- [x] a method of collecting User Sections into a concatenated string is defined and accounts for maximum char limit for GA dimensions (officially 150 bytes) [@ndouglas @oksana-c ]
- [x] `userSections` dataLayer value is populated with a concatenated string of User Sections [@ndouglas ]
- [x] GTM container variable for userSection is added in draft container version [@oksana-c ]
- [x] dataLayer value is verified in Preview and Debug GTM mode [@oksana-c]
- [x] a request to publish latest version of the CMS Prod GTM container is submitted to Insights & Analytics team [@oksana-c]
- [ ] UserSection data is reflected in GA reports on production

**Comment by oksana-c** [comment]
@ndouglas 
We have a character limitation for GA dimensions values. Currently it cannot exceed 150 bytes = 150 chars.

We have 192 Section terms.  160 of 190 are VISN / VAMC System terms.
Our challenge is to assign a dimension value using all sections that user has access to, including child sections of top level sections assigned to a user. 

In order to fit the limit, we should use Section term TID concatenated with commas. Although even when we use TIDs, we still run into an issue where we can’t fit all parent+child TIDs for a user that has access to VAMC Facilities term due to it having 160 children - each TID is 2 or 3 digit number. 

We can work around the character issue if we only send those TIDs that are actually checked on the user profile and not its children (most often unchecked). 
In GA we’ll then create custom Segments to create groups of users that have access to certain sections.
Segment is essentially a filter. Segment filter max char limit is 250 -  but we can stack multiple filters to form a segment. So if we need a segment with 160 VAMC TIDs , we can make it no problem.

Here’s my recommendation on how to structure Section values for GTM dataLayer:
* if a user has “Section” (= access to all sections) checked on /user/***/workbench_access page, then we send `all` as a Sections dimension value
* if a user doesn’t have any sections checked but has a role “Content Admin” - we send `all` as a Sections dimension value
* If a user has some Sections checked, we concatenate all term IDs with commas and send a string as a Sections dimensions value

In GA UI, we’ll create segments (a separate story) to give TID values real meaning.
Since we have a limit of 200 Segments, we won’t create a segment for each Section within VAMC Facilities, but we will group most related ones together. E.g. VAMC users will be segmented into the following groups:
* “VISN X” - group for each VISN
* “VAMC Facilities” Segment  - groups all users who have access to one or more VAMC System
All other Sections (~30) will have their own segments in GA.

We will need to revisit this strategy if/when Sections amount starts drastically increasing.

Let’s review all this tomorrow at our scheduled call.

**Comment by ndouglas** [comment]
I was thinking along the same lines, but I hadn't thought of a way to solve the problem that your segments idea solves 😄 

Sounds good to me.  Talk to you tomorrow!

**Comment by ndouglas** [comment]
D'oh, shouldn't've closed this yet.

**Comment by oksana-c** [comment]
Opened a request to QA and publish updated GTM container here - https://github.com/department-of-veterans-affairs/va.gov-team/issues/18885 

Even though last AC here involves verifying data in GA, we won't block this story completion on another team. Closing 👍
