### ISSUE TITLE
Inventory of the CMS UI Component and UI Patterns

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#3700]
## Description

The CMS team needs to audit the CMS for existing UI Components and UI Patterns and compose an inventory documentation that will allow for quick analysis when it comes to prioritizing rework of improvements for each item.

NOTE: documenting Content Model Patterns is not in scope (see #3701)

Auto-generated pattern inventory may be found [here](https://pr3795-ndbltvbrkplrk3d4t4usfofzbipmaq8v.ci.cms.va.gov/admin/appearance/styleguide)

## Related artifacts
[inventory of UI Component and UI Patterns exists](https://airtable.com/tblSKI3lIgLugkSy3/viwzzO2oEyrXeevnK?blocks=hide)

## Acceptance Criteria
- [ ] TBD

**Comment by acrollet** [comment]
@oksana-c @hie1 @jordanamello @rachel-kauff I've added a link to the auto-generated style guide environment to the issue description.

**Comment by cmaeng** [comment]
moving back to the backlog to be reprioritized against other efforts.

**Comment by EWashb** [comment]
This has been completed with the [CMS design system ](https://www.figma.com/file/ScABI31f3MRFEvQ8WitVPa/CMS-Design-System?node-id=0%3A1&t=V2IUdwuCxoWIf3Wm-0)
