### ISSUE TITLE
Port existing Behat tests and functionality to Cypress, PHPUnit, etc.

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#3705]
This will involve a substantial amount of work, including but not limited to:

- evaluating tests for their utility to the project
- evaluating tests for their "fit" with a behavioral testing paradigm
- migrating step definitions from Behat/PHP to Cypress/JS while maintaining consistency and reliability
- creating corresponding features and scenarios within Cypress to replace Behat tests that function best as behavioral tests
- creating corresponding test cases within PHPUnit to replace Behat tests that function best as unit tests, kernel tests, existing site base tests, etc
- (possibly) creating a replacement for some subsets of the functionality of the Behat Drupal Spec Tool module that will allow us to verify consistency between the Drupal config and desired config (e.g. user roles and permissions, date formats)
- creating a GitHub Action or similar function that will allow us to synchronize important aspects of the CMS content model and other artifacts with the AirTable representation so that we can be assured of a 1:1 correspondence

**Comment by ndouglas** [comment]
@oksana-c Can this be closed now, or does this cover transitioning existing Behat functional tests to Cypress?
