### ISSUE TITLE
Spike: Testing with Cypress

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#3706]
## Acceptance Criteria
- [ ] 👀 **Needs design review** because the work involves changes to labels or other design elements 
- [ ] 🙈 Can be implemented without consulting design team members
- [ ] Testable_Outcome_X
- [ ] Testable_Outcome_Y
- [ ] Testable_Outcome_Z

## Labels

(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to task)
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [ ] CMS objective (orange)
- [ ] CMS-supported product (black)

**Comment by acrollet** [comment]
@oksana-c should we close this as a duplicate of #4109 ?
