### ISSUE TITLE
Install DANSE and flag modules.

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#3737]
DANSE and flat are an API-only module - don't do anything by themselves.

https://www.drupal.org/project/danse
https://www.drupal.org/project/flag

## Acceptance Criteria
- [ ] install and enable DANSE contrib module
- [ ] install and enable flag contrib module

**Comment by indytechcook** [comment]
Modules are enabled so closing this issue.  THe PR will stay open as a base PR/branch for more notification work

![image](https://user-images.githubusercontent.com/121603/103363810-113bb500-4a8a-11eb-93db-da55757390ba.png)

![image](https://user-images.githubusercontent.com/121603/103363835-257fb200-4a8a-11eb-94ed-2c2fbc72f4a6.png)
