### ISSUE TITLE
Recipient selection DANSE plugin

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#3740]
## Description

Recipient selection DANSE plugin integrates the flag module which was implemented in #3772.  

## Use Story

When workflow state change event is fired, the users which have a flag for the updated node should have a notification created for them on the next cron run.

## Acceptance Criteria
- [ ] when a DANSE workflow event is fired, a notification entity is generated for ALL users that have a flag for the node updated.
- [ ] user is not notified about their own actions

**Comment by indytechcook** [comment]
This is replaced by https://github.com/department-of-veterans-affairs/va.gov-cms/issues/3760
