### ISSUE TITLE
MVP About Page and How-to Guide for Campaign Landing Page MVP 

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#3745]
## User story

As a potential or current editor of a Campaign Landing Page, I can learn about the CLP product so that i can know what it's for, how to get one, how to manage it, etc. 

## Questions

Is this _the_ CLP playbook? 

Do we have documentation for content admins here? 

Product marketing for CLP product... selling this product to stakeholders. 

- do we need to explain why there are so many constraints / rigidity. 

## AC

- [x] We have a place in the CMS user guide IA for CLP
- [x] Potential or current CLP users have what they need.

**Comment by nataliedunbarCS** [comment]
Created draft content as follows:

Product Playbook (added as draft to CMS help center) - https://prod.cms.va.gov/node/6454/latest
About CLP - https://prod.cms.va.gov/help/about-campaign-landing-pages
How to add CLP (WIP - most content was copied from event how to page) - https://prod.cms.va.gov/help/how-to-add-a-new-campaign-landing-page

Notes

1. The "about" page mentions the four required and seven optional segments.
2. The "how to" page will be high level and address how to add a CLP page only. Segment-specific how-to, including min/max requirements, etc., will be included as field level help text on each segment form.
