### ISSUE TITLE
Scaffolding VAMCs mandatory content pages 

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#3754]
ACs, as of Dec 16
- [ ] VAMC system node has a menu item in the appropriate menu
- [ ] All three `<nolink>` custom menu items
- [ ] All "List" page content types (Health services, Locations, Leadership, Events, News releases, Stories)
- [ ] All associated facilities have menu items with Locations as the parent

=====
[still WIP, and spec should be moved to a spreadsheet]

Ideally, each one of these VAMCs would have a menu built with these nodes

- [node title], VAMC system node, [VAMC system URL path]
  - Services and locations (Custom menu item`<nolink>`)
     - Health services, Health Services List node, [VAMC system URL path]/health-services
        - Caregiver support 
        - Homeless Veteran care
        - Caregiver support (disabled)	
        - Homeless Veteran care (disabled)	
        - LGBT Veteran care (disabled)	
        - Mental health care (disabled)	
        - Minority Veteran care (disabled)	
        - Patient advocates (disabled)	
        - Returning service members (disabled)	
        - Suicide prevention (disabled)	
        - Women Veteran care (disabled)	
     - Locations, Locations List node, [VAMC system URL path]/locations
        - Facility 1
        - Facility 2
        - Facility N
   - News and events (`<nolink>`)
      - Events
      - News releases
      - Stories 
  - About `[VAMC system node title] minus the "health care" string]` (eg "About VA Erie"), `<nolink>`
    - About us	
    - Mission and vision	
    - History

Top task pages, all detail pages with  
- Policies	
- Contact us	
- Billing and insurance 
- Make an appointment
- Pharmacy 
- Register for care 	
-

**Comment by jilladams** [comment]
@davidmpickett for review

**Comment by davidmpickett** [comment]
As I understand it, this is a list of content that should be created when a new VAMC system is created. I'm closing this ticket as a no-op, but I believe this does partially answer to a question that came up during D10 testing with @swirtSJW and @omahane about having a runbook of creating a new VAMC System

**Comment by jilladams** [comment]
Added a link to this ticket to the New VAMC System area of [Flagged Facilities.md > runbooks](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/flagged-facilities.md#runbooks) so we remember that in future.
