### ISSUE TITLE
Notifications log

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#3756]
## User story

As a CMS Administrator, I need access to the notifications log with filters, so I can review notifications usage by user, event type, time/date, etc.

## Acceptance Criteria
- [ ] administrative view for notifications log is available to users with Administrator role
- [ ] notifications log can be filtered by user, type of notification, date range

**Comment by TheBoatyMcBoatFace** [comment]
CMS does not currently have notifications framework. Closing until needed.
