### ISSUE TITLE
Notification entity is created per user based on event data

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#3760]
## User Story

As a CMS engineer, I need to see all registered notifications that would go out when events occur, so that I can analyze the notifications log and see real data describing the volume of expected notifications.

To create the notification, a Recipient selection DANSE plugin integrates the flag module. 

### Refactor the `Drupal\danse\PluginBase::createNotifications`
The current logic within `Drupal\danse\PluginBase::createNotifications` tightly couples code from the `push_framwork`, specially `DirectPushInterface`.  The code to create the notifications should be abstracted out of the DANSE plugins into a manager class.  The manager class should invoke the plugins to create the notification entity object for their respective event.  The code to find the receipts for a particular event should be within this Notification manager class and it should invoke the User Selection plugins.

## Acceptance Criteria
- [ ] when a DANSE workflow event is fired, a notification entity is generated for ALL users that have a flag for the node updated.
- [ ] user is not notified about their own actions
- [ ] Issue submitted to DANSE for `Drupal\danse\PluginBase::createNotifications` refactor.  The refactored code can initially be part of our plugin.

**Comment by indytechcook** [comment]
In this issue follow up on https://www.drupal.org/project/danse_content_moderation/issues/3195394

We should also update to version 2.2 and read up on https://www.drupal.org/project/danse/issues/3194737.
