### ISSUE TITLE
Link summary should be required on CLP What you can do panel

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#3762]
## User Story or Problem Statement

Some link teasers should have required link summaries, some should not. 

For example: 
* Link summary should be required on CLP What you can do panel (and in Promo custom block type across the site)
* Link summary should be required on CLP spotlight panel 
* Link summary should be required on Health Services List "spotlight" component
* Link summary should not be required on Related Links component on `page` content type. 
* Link summary should not be required by default on other instances of the link teaser paragraph

[Audit of link teaser](https://app.mural.co/t/vagov6717/m/vagov6717/1605286751773/8cd1af5cfbc561d2a92949db5a302393615ba352)

## Acceptance Criteria
- [ ] Link summary field should be required on CLP What you can do panel
- [ ] Link summary field should not be required in other places Link Teaser is used on Related Links component on `page` content type 

## Implementation steps

TBD

**Comment by kaise-lafrai** [comment]
@kevwalsh I think this ticket needs additional refining. I am a bit confused between the user story and the acceptance criteria.

**Comment by kaise-lafrai** [comment]
@kevwalsh @swirtSJW @nataliedunbarCS  

The **What you can do panel** has a promo block entity reference field labeled as **WHAT YOU CAN DO PROMOS**. The promo block is referencing the Link Teaser paragraph type where the Link Summary is currently **NOT REQUIRED**. The acceptance criteria states that the _Link summary field should be required on CLP What you can do panel_ which would require updating the **Link Teaser** paragraph type to require the **Link Summary** field. This contradicts the next acceptance criteria _Link summary field should not be required in other places Link Teaser is used on Related Links component on page content type_. This was pointed as a 2 story points and my brain wants to say that it must be something that can easily be done with config - but this seems to be a much more detailed task that would need some additional discussions to iron out. Please let me know if I am missing something here. 

Thank you

**Comment by swirtSJW** [comment]
I agree with what Kaise is asking.  With JS magic I don't think we can adequately alter the behaviour of a promo blocks fields on different content types.   We might need a different approach/plan.

**Comment by EWashb** [comment]
@jilladams @wesrowe I found this ticket with the "Sitewide Crew" label but no current team.

**Comment by wesrowe** [comment]
Thanks @EWashb

**Comment by FranECross** [comment]
Closing old 2020 ticket.
