### ISSUE TITLE
Make some fields required only before Publishing content

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#3768]
### User Story or Problem Statement

**As a content editor**, i sometimes want to save draft content before filling out all required fields, because i don't want to lose any content i've already filled out. 

This is particularly true on longer forms such as Campaign Landing Page, which has 9 required fields, some of which may not have content immediately. 

**As a content admin** spawning a page for another user that they have permission to edit but not create, i don't want to fill out any content. 

### Affected users and stakeholders

* CLP content editors.  
* Content admins for CLP and other content types. 

### Hypothesis

drupal contrib module required_on_publish _may_ help with this scenario, but we would need to test it with the existing content moderation tools.

EWA designs may need an iteration to handle content that is missing required fields.

**Comment by FranECross** [comment]
Closing old epic as obsolete; a new ticket will be opened if this rises up again.
