### ISSUE TITLE
Prepare CMS editorial experience survey for Q4 2020

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#3777]
The goal is to send early in the first week of January and process feedback by the end of Sprint 23 (Jan 15)

## Acceptance Criteria
- [x] current survey is reviewed and any required updates are made
- [x] comms for survey distribution are prepared

**Comment by jordanamello** [comment]
A web link collector was created for Q4 2020.

Comms were adapted and can be found [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/research/user-survey-results/README.md).
