### ISSUE TITLE
PR Environment with Styleguide contrib enabled

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#3781]
## Description

@acrollet found a contrib module that will help in our UI inventory effort - https://www.drupal.org/project/styleguide 

## Acceptance Criteria
- [x] a PR environment where https://www.drupal.org/project/styleguide is enabled
- [x] team can preview generated styleguide for Seven, VAGOVADMIN and Claro themes
- [x] link to PR environment is added to #3700 description

**Comment by acrollet** [comment]
I've locked the tugboat environment, which should keep it from getting deleted even if the PR is closed, if I'm understanding things correctly.

**Comment by msbtterswrth** [comment]
@kevwalsh should this close in favor of the claro work we're about to launch?
