### ISSUE TITLE
Spike: User Admin Service

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#3784]
Facilitator: @oksana-c 

Participants: @daddison48 @cmaeng @kevwalsh @indytechcook @swirtSJW @xiongjaneg @rachel-kauff @oksana-c @erogray @VanessaLuxen 

## Acceptance Criteria

- [x] brainstorming session on the following topics:
   - [x] **high priority**: influx of editors from VAMCs in dual-state is a risk based on our current help desk / training capacity. How might we mitigate this with the resources we have available?
   - [x] user admin experience when creating / managing accounts:
      - [x] in/efficiencies of current processes
      - [x] risk of user error when manually creating accounts and methods to decrease them
      - [x] obsolete accounts audit
   - [x] scalability of user admin service once we start rapidly onboarding new businesses to CMS
   - [x] opportunities for automation
      - [x] user account application form
      - [x] review / approval process / considerations for PIV login
   - [x] management of user roles and opportunities to streamline
      - [x] product / section based roles and effects on content governance
      - [ ] possible monthly audit / report to DEPO

---

- [x] next steps are identified w/ potential backlog items generated

## Resources

* VAMC- CMS onboarding service blueprint and policies- https://app.mural.co/t/vagov6717/m/vagov6717/1605735264080/64a23a4e0bcff45cafebd576db9a787d54127dbc
* User account creation procedures DRAFT - https://docs.google.com/document/d/1t-fBvTLoQk-a7P56l1pmOx2NOCsN9FSYZXuTpsRraGc/edit#heading=h.s5vy91nn0f0j

## Spike Mural

https://app.mural.co/t/vagov6717/m/vagov6717/1611495933092/40b0bfce2e08962822b8535d975f4182b358c8e6

**Comment by xiongjaneg** [comment]
Oksana,

Can we get one or both help desk folks on this? I create training accounts
but they'll create prod accounts in our current workflow.

Thanks,

Jane

**Comment by oksana-c** [comment]
Spike scheduled for Monday, January 18th - 1.5hrs

**Comment by oksana-c** [comment]
Existing processes:

- VA onboarding users to GitHub. Pre-requisite: if you have va.gov email address, you can request to be added to VA org.
- Policy around off-boarding procedures.
- PIV card process: background checks, etc.
   - LDAP
- Informal / manual onboarding to Slack channels (GitHub access request template)

Action items:
- check w/ PO if there are services we need to integrate with

**Comment by oksana-c** [comment]
Confirmed w/ PO - there are no external dependencies for the CMS User Admin Service.

@jordanamello and I will be meeting in Sprint 25 to refine service design backlog.
