### ISSUE TITLE
Help Desk 101 Training

### ISSUE THREAD

**Issue by erogray** [department-of-veterans-affairs/va.gov-cms#3793]
Let's put together training materials for anyone who may need to stand in as Tier 1 help desk in the future, consisting of distilled and easy-to-read documentation/training material for: 

- [x] Jira Service Desk: basic navigation, how to use tickets
- [x] Triage basics
- [x] Incident and critical defect response

**Comment by erogray** [comment]
https://docs.google.com/presentation/d/1nKe1VSauK3b-7m6ahCr3u-CKgsyeaFB_brPtWm1PIGk/edit#slide=id.p is ready for review — I think we should try training someone with it next sprint!

**Comment by oksana-c** [comment]
@erogray I scanned thru the slides and agree, the next step is to train someone based on available material, then iterate if necessary. Please open a story for training. Thanks
