### ISSUE TITLE
Analysis of the notifications log

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#3799]
## Description

In the CMS Notifications framework Release 1.0, the CMS will be generating notification records for each workflow state transition event per user, but will not send emails.

This approach offers the following advantages:
* ability to test notifications content / type, frequency and design before rolling out to real users
* ability to assess the volume of notifications we need to support via VANotify
* quantitative data to optimize the design of opt-in/out UI, email templates and email delivery methods 

## Acceptance Criteria
- [ ] notification reports with at least 2 full weeks of data are generated for analysis
- [ ] notification reports are reviewed with the Research / Design team [@jordanamello @rachel-kauff ]
- [ ] discuss the following topics based on reported data [@jordanamello @rachel-kauff  @oksana-c ]:  
     - [ ] is there any optimization we can and should do to prevent user notification fatigue
     - [ ] are there any aspects of notification content optimization that we need to consider
     - [ ] any considerations while designing the opt-in/out UI
     - [ ] other considerations based on analyzed data
- [ ] generate next steps in backlog
- [ ] an assessment of required email notification volume per month is made and shared w/ PO

**Comment by jefflbrauer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VAgov-CMS-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/3799?planning-poker) with ZenHub @ElijahLynn @indytechcook @ndouglas @olivereri @timcosgrove

**Comment by jefflbrauer** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VAgov-CMS-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/3799?planning-poker) with ZenHub @cweagans

**Comment by TheBoatyMcBoatFace** [comment]
Notifications framework not a priority right now. 

CC: @EWashb
