### ISSUE TITLE
User administration policy for Vet Center MVP editors

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#3801]
## During the MVP phase (10 editors, one for each MVP Vet Center, plus 4 national editors)

Onboarding 
- what are all the touchpoints in the process? eg Training, account creation, etc.
- what triggers onboarding? Currently Michelle or Vet Centers for MVP (Not CMS)
- who is responsible for adding new Vet Center users?
- what are the criteria for adding them (eg is training required first)?
- who approves, and what is the process?
- what roles should they get? Publisher, Content Creator - Vet Center
- what sections should they be added to? TBD District Zone about 20 Vet Centers each, in MVP only at Vet Center level
- What content is required for each touchpoint in the process?
- what might we want to learn through this process that could apply post-MVP phase (see below)?

Permissions changes
- what types of changes might we expect to hear requests for? (Sections, Roles) 
- what triggers this?
- who approves, and what is the process?
- who performs this? 
- what are the touchpoints?
- any content required? 

Offboarding
- what triggers offboarding?
- who is responsible for offboarding?
- what is the process?
- any touchpoints? 
- any content required? 

## Post-MVP (300 editors, 400 facilities + plus Community Access Points)

- What considerations are needed for scaling this process for 300 editors? 
- what might we want to learn during MVP about what could work post-MVP?

## AC

- [x] We have defined an MVP user administration service for Vet Centers to serve both national and local editors. 
- [x] Business stakeholders and product team are aligned on this service for MVP phase
- [x] We have a hypothesis for how we might scale this service post-MVP phase, and a plan to validate this approach _during_ MVP phase.

**Comment by kevwalsh** [comment]
I'm repurposing this to make it more broad (Vet Center user admin, not just Vet Center facility status)

**Comment by kevwalsh** [comment]
@xiongjaneg  Mural stubbed https://app.mural.co/t/vagov6717/m/vagov6717/1615237797572/183827cebccff9456dd79effc50b90bc2a3a7c8b

**Comment by xiongjaneg** [comment]
meeting scheduled 3/11/21
