### ISSUE TITLE
Develop training for facility operating status editors

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#3802]
### User Story

As a Vet Center editor, I need to be able to update the facility status so that Veterans see updated status alerts on the Facility Locator Tool.

- [x] Research process
- [x] Draft presentation for PO review

**Comment by xiongjaneg** [comment]
### User Story

As a Vet Center editor, I need to be able to update the facility status so that Veterans see updated status alerts on the Facility Locator Tool.

- [ ] Research process
- [ ] Draft presentation
- [ ] PO review
- [ ] Finalize presentation

**Comment by xiongjaneg** [comment]
[Draft presentation](https://docs.google.com/presentation/d/1KTmJuKXjOgkaRQs1xe3Q6ZZA8arG7Qbt5SHG25e9eU0/edit#slide=id.ga33f742790_0_830)
