### ISSUE TITLE
Deliver training for facility status editors

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#3803]
### Acceptance Criteria

- [x] Facility Status training delivered to a group selected by @davidconlon 
   - [x] Editors can explain the workflow for changing facility operating statuses.
   - [x] Editors can perform the steps in Drupal to change facility operating statuses.
   - [x] Veterans can see Covid-affected and other facility operating statuses.

**Comment by xiongjaneg** [comment]
Link to slides https://docs.google.com/presentation/d/1KTmJuKXjOgkaRQs1xe3Q6ZZA8arG7Qbt5SHG25e9eU0/edit#slide=id.ga33f742790_0_830

**Comment by xiongjaneg** [comment]
Link to Dave's process Mural https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1595276505275/42814b6e8bf09ad6f70ab41626b03fcbaf6eafca

**Comment by xiongjaneg** [comment]
Scheduled Tuesday, Jan. 26, 3-4pm ET

**Comment by xiongjaneg** [comment]
All four invitees attended Jan. 26, 2021
