### ISSUE TITLE
Announcement of Jira Service Desk to CMS users

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#3815]
## User stories
As a CMS user, I need to understand which channels of CMS support are available to me and the system in which the CMS Helpdesk operates (expected response times, etc), so that I know where to go for help and manage my expectations.

## Participants
- @VanessaLuxen 
- @erogray 

## Acceptance Criteria
- [x] Adjust messaging in training about how to connect w/ help desk [@xiongjaneg ]
- [x] Announcement of Jira Portal to CMS userbase [@rachel-kauff @erogray @VanessaLuxen ]
    - [x] Transition existing users from #cms-support workflow to new Jira SD workflow
    - [x] Transition existing users from cms support email to Jira SD

**Comment by rachel-kauff** [comment]
Update: announcement content is drafted, and feedback is happening in this Slack thread: https://dsva.slack.com/archives/CT4GZBM8F/p1609955201115400

**Comment by rachel-kauff** [comment]
Moving this ticket to next sprint due to the freeze on releasing the JSD widgetywidget.

**Comment by jordanamello** [comment]
Please see recommendations for the announcement and general change management, generated during [CMD Help Center research cycle](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/3817):
- Articulate the different usages of help (Slack resources and CMS resources) and clarify to users when to use what.
- Have different announcements written for email-only users and Slack users.
- Users could benefit from a description (perhaps visual?) of the process to request support - how to get to the help center, in which circumstances, etc.

cc @erogray @rachel-kauff @VanessaLuxen

**Comment by rachel-kauff** [comment]
Ping Vanessa to send email announcement when ready.

**Comment by erogray** [comment]
Widgetywidget is live! The announcement in # cms-support is also: https://dsva.slack.com/archives/CDHBKAL9W/p1611178811034400

Next up: Vanessa will send the email version.

**Comment by VanessaLuxen** [comment]
Email was sent to the VA CMS Support email list at 5:20pm eastern on 1/21/2021.
