### ISSUE TITLE
Improve "VA form" content type help text

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#3816]
## User Story or Problem Statement

Public Websites team has written documentation for creating Form detail landing pages ("VA Form" content type). 

This could work well as help text 

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-va-forms-redesign/form-detail-landing-pages/Publishing%20a%20new%20form%20detail%20landing%20page.pdf

## Acceptance Criteria
- [ ] VA form contains helpful text, guidelines, and possibly some additional guardrails.

**Comment by FranECross** [comment]
Closing this old epic as obsolete
