### ISSUE TITLE
User testing for the CMS Help Center updates and JSD widget

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#3817]
## Description

As a CMS Researcher, I need to conduct usability testing for the updated CMS Help Center UX, so that I know whether or not we've made effective design decisions.

## Acceptance Criteria

- [x] Tests are conducted
- [x] Feedback is discussed internally
- [x] Feedback is incorporated into the prototypes to inform implementation

**Comment by jordanamello** [comment]
Please see remaining implementation notes on [this Mural](https://app.mural.co/t/vagov6717/m/vagov6717/1609273937806/3d49f7ea2ac608614ee38e8052acb4676bcbc18e). Some of the recommendations were implemented on the fly by @erogray as we agreed on the path forward.

I recommend that a separate ticket is created specifically for the release notes and another to discuss how the change management will be operationalized. 

cc @rachel-kauff @oksana-c @VanessaLuxen

**Comment by oksana-c** [comment]
issue for the announcement and transition already exists here https://github.com/department-of-veterans-affairs/va.gov-cms/issues/3815 
if something is missing based on the ongoing conversation, please flag there. thank you!
