### ISSUE TITLE
Support certain webex links in HTML inputs

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#3832]
## User Story or Problem Statement

As an editor, especially of events, i want to copy/paste webex links into the body of events, so that va.gov users can use those links on webex software or hardware. 

Sample webex copy/paste: 

```
[Insert here]
```

## Background

[Slack thread](https://dsva.slack.com/archives/CT4GZBM8F/p1608317133222500)

## Acceptance Criteria
- [ ] Webex links are not treated as broken links, and are preserved.

**Comment by jilladams** [comment]
Events scrub with Dave: what is the problem we are trying to solve here? User story = "As an event attendee I want to..." ? 

Is this a mobile concern re: mailto: , phone: etc types of links?

**Comment by FranECross** [comment]
@FranECross Check to see if this is still an issue...

**Comment by FranECross** [comment]
Closing as obsolete. A new ticket will be created if this comes up again.
