### ISSUE TITLE
Product Briefs for 1. Full site preview and 2. Hyperlinks management (broken links). 

### ISSUE THREAD

**Issue by daddison48** [department-of-veterans-affairs/va.gov-cms#3833]
## User story

As a Product Owner, I need to have product briefs for the Full site preview  and the Hyperlinks management (broken links) in a provided format, so that I can facilitate collaboration between the VSP and CMS teams

## Acceptance criteria

The following product briefs are available:
 - [x] Full site preview
 - [x] Hyperlinks management (broken links)
 
## Implementation notes

Template:

```
Title

Problem statement

Hypothesis or Bet

We will know we're done when... ("Definition of Done")

Known Blockers/Dependencies

```

**Comment by daddison48** [comment]
Test from template:


"Ship it Everywhere" Design System Components
Problem Statement
When VFS teams are creating an application it can exist in one of three different technical approaches: 
as a REACT application
as a liquid template rendered from Drupal content
a hybrid of the two
In order to have a consistent user experience, individual components in applications and content should be identical across the user experience. For example, the user interface of a simple form should not appear or behave differently in different parts of VA.gov. However we currently do not maintain a library of components that is technically agnostic, so teams building in each of the three technical approaches draw from different shared/reusable code bases. 
How might we create a technically agnostic approach to our design system and the components and patterns within it that will allow a team to build a new REACT app, new content, or hybrids without recreating components from a specific technical stack or creating more code that is unique to a single environment or application? 
Hypothesis or Bet
VFS teams will be able to build more consistent applications across different technical environments
VFS teams will break able to experiment and prototype in other technical environments (e.g. Vue.js, etc.)
VSP will be able to maintain a single source of truth for multiple technical environments
We will know we're done when... ("Definition of Done")
REACT applications and web content pull from a single code base of shared components and code
Known Blockers/Dependencies
Ongoing maintenance of the existing specific code bases
Changes of content model
Supporting new application work design system needs

**Comment by oksana-c** [comment]
Product outlines are posted here https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/cms/product-outlines 

We'll keep this issue open until the end of sprint in case any requests for updates come from @JeffBarnesUSDS
