### ISSUE TITLE
Appointments information for health services

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#3840]
## User Story or Problem Statement

As a Veteran, i need nuanced information about appointments for each health service, especially COVID-19 vaccines, but also services like Primary Care, so that i know how to access care. 

As an editor, i need to provide nuanced info about appointments beyond what's contained in the existing structured content. 

## Acceptance Criteria
- [x] `field_hservice_appt_leadin_select` select list with radio buttons (see balsamiq)
  - [x] Field label: `Appointment intro text`
  - [x] values: `default_intro_text`; `custom_intro_text`; `no_intro_text` 
- [x] `field_hservice_appt_leadin`  plain text field. (see balsamiq)
  - [x] Form config: Textfield counter set to 200 characters hard limit. Counter text: `[200] characters remaining.`
- [ ] ~Placeholder value: `Contact us to schedule, reschedule, or cancel your appointment. If a referral is required, you’ll need to contact your primary care provider first.`~
- [x] FE devs have clear implementation guidelines. 
- [x] `Notice: Undefined offset: 0 in _va_gov_backend_unset_fields() (line 631 of modules/custom/va_gov_backend/va_gov_backend.module).` no longer shows in the logs

## Implementation
- Content type and form config
- ~Script to add default value to existing 5000 nodes.~ 
- Document how this should work for FE implementation
- Create followup issues for national standardization of appointment information. 

## Mockup

https://balsamiq.cloud/s21kwcm/py46j7t/rCC1D

**Comment by kevwalsh** [comment]
@mmiddaugh Just met with Dave about this field in the Facility health service content type. We'll aim to have this done by Dec 31 2020.

**Comment by mmiddaugh** [comment]
FYI 2 draft issues (pending AC refinements)
[Transformer issue](https://github.com/department-of-veterans-affairs/va.gov-team/issues/17787)
[FE implementation](https://github.com/department-of-veterans-affairs/va.gov-team/issues/17518)

**Comment by swirtSJW** [comment]
This commit got reverted because it was for the wrong content type.

**Comment by kaise-lafrai** [comment]
@kevwalsh Where should Appointment lead-in text be placed in the form display?

**Comment by kaise-lafrai** [comment]
@swirtSJW @kevwalsh 

Here is what I was thinking of doing. Dave wants control of the appt leadin text in the CMS, to do this and to provide a boolean checkbox to switch between the default appt leadin text and one that the editor wants can be accomplished like this.

We create 3 new fields (see image):

![image.png](https://images.zenhubusercontent.com/5f04cf76eb6c0026ebd18020/13a035e2-5944-4ca8-bebd-45417e40e29c)

If the boolean is checked it will display the default appt leadin text and make it disabled (greyed out) and hide the appt leadin edit field. If the boolean is unchecked it will hide the disabled appt leadin text and show the enabled appt leadin edit field.

I discovered a module that basically deals with default values and can push default values out to existing nodes. If Dave decided to change the verbiage in the future, we can modify the default value, select the checkbox to push out to other nodes and select save. 

Here is a screen shot of what it did:

![image.png](https://images.zenhubusercontent.com/5f04cf76eb6c0026ebd18020/8485b60f-d602-45e7-9bb8-fa920f4921ca)
![image.png](https://images.zenhubusercontent.com/5f04cf76eb6c0026ebd18020/7519786f-ce07-4663-b9a6-715da9f6c7b3)
![image.png](https://images.zenhubusercontent.com/5f04cf76eb6c0026ebd18020/6d1f1a4b-a345-48fb-9eba-3f92016073f4)

Random node to check if it worked:

![image.png](https://images.zenhubusercontent.com/5f04cf76eb6c0026ebd18020/a6b02927-2a50-4b1a-85f8-86b5bd390be7)

Few things that I noticed using the contrib module: 1) It takes a long time 30min++ 2) It craps out if you are messing with config while its running 3) It craps out if your computer sleeps to save energy.

We could use this module or bulk edit. I have not used bulk edit yet.

**Comment by swirtSJW** [comment]
@kaise-lafrai 
1) does the default data show up in the cms export?  (is in the same field and in the same property, or does it move it around)
2) Can the push of new data be done by drush so it is faster and not prone to the same timeouts?

**Comment by kaise-lafrai** [comment]
@swirtSJW 

1)```
         {
            "alias": "\/syracus-health-care\/locations\/syracuse-va-medical-center\/complementary-and-alternative-medicine",
            "langcode": "en",
            "pathauto": 1
        }
    ],
    "field_administration": [
        {
            "target_type": "taxonomy_term",
            "target_uuid": "f08f2375-99da-4bd2-9c79-9b411224bd82"
        }
    ],
    "field_appointment_lead_in": [
        {
            "value": false
        }
    ],
    "field_appointments_help_text": [],
    "field_body": [],
    "field_facility_location": [
        {
            "target_type": "node",
            "target_uuid": "35563e8e-75d5-4b96-ad52-100bfbdf0a21"
        }
    ],
    "field_facility_service_loc_help": [],
    "field_health_service_appt_leadin": [
        {
            "value": "Contact us to schedule, reschedule, or cancel your appointment. If a referral is required, you\u2019ll need to contact your primary care provider first."
        }
    ],
    "field_health_service_apt_li_edit": [],
    "field_online_scheduling_availabl": [
        {
            "value": "1"
        }
    ],
:
```

2) I need to verify if there is a drush command

3) If someone deleted the data, the module can push the default_value back into the field.

**Comment by kevwalsh** [comment]
Moving to Sprint 23.  

ACs changes several times throughout 22, as new information became available.

**Comment by kaise-lafrai** [comment]
Ready for review here: https://pr3912-txpmojlwj4ivzctkkctjyqrxdpz4t0tz.ci.cms.va.gov/

**Comment by indytechcook** [comment]
The PR merged introcued a new error to the log files:

```
Notice: Undefined offset: 0 in _va_gov_backend_unset_fields() (line 631 of modules/custom/va_gov_backend/va_gov_backend.module).
```

@kaise-lafrai be sure to make your code more defensive and us fewer assumptions about the data.  The data returned by the entity API can sometimes be tricky!

Instead of using `->getValue()` directly and messign with array use https://api.drupal.org/api/drupal/core%21core.api.php/group/typed_data/9.0.x.

Something like 

Typed data allows you to use shorthand to get data values nested in the implicit tree structure of the data. For example, to get the value from an entity field item, the Entity Field API allows you to call:
```
$value = $entity->field_hservice_appt_intro_select->value;
```

To get the strig value.  See the section. "Tree handling" in the Typed Data API link above.

**Comment by kevwalsh** [comment]
@kaise-lafrai i've added an AC about this error and moving this back to To do. thanks!

**Comment by kaise-lafrai** [comment]
@indytechcook @kevwalsh Thanks for finding that and for providing a better approach. I will get this fixed today.
