### ISSUE TITLE
COVID-19 vaccine placeholder: Migration, lighthouse, CLP, health service content/data model.

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#3841]
This is a placeholder for unplanned work related to COVID-19.

**Comment by swirtSJW** [comment]
This placeholder accounted for performing this https://github.com/department-of-veterans-affairs/va.gov-cms/issues/3856

**Comment by kevwalsh** [comment]
Closing this, since the work was done in #3856
