### ISSUE TITLE
Tasks outline for testing the updated CMS help desk support UX

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#3842]
## User story

As a CMS Researcher, I need to outline tasks for testing the updated CMS help desk support UX with the CMS users, so that I can conduct research in Sprint 23.

## Acceptance Criteria
- [x] Usability testing goals and tasks are defined 
- [x] Participants are defined
- [x] Sessions are scheduled

**Comment by jordanamello** [comment]
Links in GH:
- [Research Plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/research/cms-help-center/README.md)
- [Conversation Guide](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/cms/research/cms-help-center/conversation-guide)
