### ISSUE TITLE
Product Dashboards

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#3874]
## Problem statement
The VA.gov Drupal CMS was established following an open ethos as it relates to content access. Any user one can find and view any piece of content within the CMS. Edit permissions are determined based on the user’s Section (a method of identifying the user's team).

Many users are coming to Drupal CMS from TeamSite where access is constrained to teams / products by default. User’s expectation is that Drupal CMS will behave in the same manner.

As the user base in the CMS grows, it will be wise to constrain access to content based on the VFS/CMS Product(s) that the user is allowed to manage.
The CMS team has received multiple requests for improving the findability of content within the CMS. We believe that providing Product-based navigation along with 

Product-based dashboards for teams that work in the CMS will significantly improve content findability and instill a sense of confidence that the user is working in the right place within the system.

## Hypothesis or Bet

* Product-based navigation and Product-based dashboards will improve content findability and give users a sense of confidence that they are working in the right place within the CMS.

## We will know we're done when... ("Definition of Done")

* We’ve designed a scalable system of identifying VFS and other Products within the CMS.
* CMS users have access to Product-base dashboards and report higher satisfaction with content findability and overall experience in the CMS.

## Known Blockers/Dependencies
* none

## User Stories

As a CMS user, I want to be able to see the content that I am responsible for managing in one place, so that I don’t have to search through thousands of pages to find the one I am looking for.

As a CMS user, I want to have an intuitive dashboard, so that I can see various aspects of the product that I am working on at a glance.

## va.gov-team product directory

https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/cms/product-outlines/product-dashboards

## Resources

* [VAMC product dashboard prototype (XD)](https://xd.adobe.com/view/4837c11c-b5b4-4439-84d7-5867919f9c42-1d64/?fullscreen)
* [Resources and support product dashboard prototype (XD)](https://xd.adobe.com/view/5cd15a8f-426d-4356-b81e-82920dd688be-0982/?fullscreen)

**Comment by jefflbrauer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VAgov-CMS-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/3874?planning-poker) with ZenHub @ElijahLynn @indytechcook @ndouglas @olivereri @timcosgrove

**Comment by jefflbrauer** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VAgov-CMS-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/3874?planning-poker) with ZenHub @cweagans

**Comment by EWashb** [comment]
Not everyone will get a dashboard. We are only considering this possibly MAYBE for VAMC in the future state.
