### ISSUE TITLE
Structured collaboration - Help desk : UX writing

### ISSUE THREAD

**Issue by rachel-kauff** [department-of-veterans-affairs/va.gov-cms#3876]
# Story
How can UX writing and help desk collaborate to ensure our users experience helpful, consistent, and friendly communications and content when they reach out for help?

## Participants

@rachel-kauff 
@stefaniefgray 
@chriscraiga6 

## Areas

- Communications (announcements, quicktips)
- Help content (help guides, training content, help center pages)
- Research and feedback (Flagging language misalignment)

**Comment by stefaniefgray** [comment]
Meeting planned with UX team for Jan 10th

**Comment by stefaniefgray** [comment]
@rachel-kauff How should we proceed with this epic?

**Comment by rachel-kauff** [comment]
Great question, @stefaniefgray.  Let's set up some time to talk about what the help desk capacity is like these days, then we can identify collaboration points and get them prioritized into Sitewide CMS work. cc: @EWashb

**Comment by stefaniefgray** [comment]
@EWashb Lots of changes since we last addressed this ticket! What shall we do with it at this time? Please let me know your thoughts -- thank you!

**Comment by EWashb** [comment]
@stefaniefgray this sort of goes back to the comment about templated responses- do you think yall have a good handle on the templated comms?

**Comment by stefaniefgray** [comment]
@EWashb FYI closing because this is ancient, and we've already iterated on this with @TroyA6 , @laflannery , and the UI/UX team
