### ISSUE TITLE
Help content orientation for help desk

### ISSUE THREAD

**Issue by rachel-kauff** [department-of-veterans-affairs/va.gov-cms#3880]
## Participants
- @erogray 
- @rachel-kauff 
- @VanessaLuxen 

# Background
Introduce Ero and Vanessa to how to edit and create help center content so they are empowered to update content as needed. Also maybe a chance to show them the announcements page, etc. 

AC
- [ ] One hour help center orientation

**Comment by xiongjaneg** [comment]
incorporated into helpdesk orientation and transition for Stefanie and Chris
