### ISSUE TITLE
2022 Q1 KB Maintenance (Internal KB for Helpdesk)

### ISSUE THREAD

**Issue by rachel-kauff** [department-of-veterans-affairs/va.gov-cms#3881]
## Story
As a CMS user, I want to know that the user guide I'm reading is current so I know I can trust the information I'm reading.

## Background
To ensure CMS user guides are accurate and up to date, we need to conduct regular reviews of the content we have in the help center.

ACs
- [ ] Internal documentation has been audited and is listed in a singular location.
- [ ] All user support internal documentation content available to the VA Drupal CMS Helpdesk has been reviewed, marked with the date last updated, and noted in regards to which updates need to be made.
- [ ] Out of date content has been flagged for revision

**Comment by stefaniefgray** [comment]
Have started Knowledge Base documentation audit: https://docs.google.com/spreadsheets/d/1RDUVAtG9FN6lX6xSgJ2SaPh5uJHvXI47axqfVklxbzA/edit#gid=0

**Comment by stefaniefgray** [comment]
**Is this ticket in reference to the external KB or our internal helpdesk KB?:** For the purpose of not duplicating our colleagues' work, this ticket refers to internal helpdesk documentation

**Where is it located?:** Google Drive and Github, mostly.

**Comment by stefaniefgray** [comment]
Link to new KB audit doc: https://docs.google.com/spreadsheets/d/1V1sQceww-DqpOahPGZdgYOT6elPiJmWMjfZQNbLPj04/edit?usp=sharing

**Comment by stefaniefgray** [comment]
Closing because @msbtterswrth performed full KB audit from separate ticket (unless I should re-open this one or do one for Q2? Thoughts?)
