### ISSUE TITLE
CMS users segmentation

### ISSUE THREAD

**Issue by jordanamello** [department-of-veterans-affairs/va.gov-cms#3886]
_As a UX researcher, I want to have CMS audiences defined, so I can choose the right participants for UX research and design efforts._

**AC:**

- [ ] Participants: @oksana-c @rachel-kauff @nataliedunbarCS @kevwalsh @hie1.
- [ ] Workshop to define audience differentiators (e.g. frequency of use, goal priority, product) and cutoffs.
- [ ] CMS audiences are defined and documented.
- [ ] We have a log of users for each audience defined.
- [ ] Apply cutoffs to GA.

**Comment by EWashb** [comment]
original research intention does not reflect current state. closing.
