### ISSUE TITLE
 Card sort with CMS users - planning

### ISSUE THREAD

**Issue by jordanamello** [department-of-veterans-affairs/va.gov-cms#3887]
_As a UX researcher, I want to uncover CMS users’ mental models about how information is categorized and organized, so that we can make informed design decisions._

AC:
- [ ] Card sort study  is set up (tool: Optimal Sort).
- [ ] Participants are selected.
- [ ] Card sort invitation is sent to participants.

**Comment by EWashb** [comment]
original research intention does not reflect current state. closing.
