### ISSUE TITLE
Card sort with CMS users - synthesis

### ISSUE THREAD

**Issue by jordanamello** [department-of-veterans-affairs/va.gov-cms#3888]
_As a UX researcher, I want to uncover CMS users’ mental models about how information is categorized and organized, so that we can make informed design decisions._

**AC:**
- [ ] Card sort data are analyzed.
- [ ] Synthesis is complete and shared with team members.
- [ ] Synthesis is posted in GH.

**Comment by EWashb** [comment]
original research intention does not reflect current state. closing.
