### ISSUE TITLE
Tree test with CMS users - planning

### ISSUE THREAD

**Issue by jordanamello** [department-of-veterans-affairs/va.gov-cms#3890]
_As a UX researcher, I want to test the proposed IA structure with CMS users, so that we can evaluate the findability of topics in the CMS._

**AC:**
- [ ] Tree test scenarios are defined.
- [ ] Tree test study is set up (tool: Treejack).
- [ ] Participants are selected.
- [ ] Tree test invitation is sent to participants.

**Comment by EWashb** [comment]
original research intention does not reflect current state. closing.
