### ISSUE TITLE
Tree test with CMS users - synthesis

### ISSUE THREAD

**Issue by jordanamello** [department-of-veterans-affairs/va.gov-cms#3892]
_As a UX researcher, I want to test the proposed IA structure with CMS users, so that we can evaluate the findability of topics in the CMS._

**AC:**
- [ ] Tree test responses are analyzed.
- [ ] Synthesis is complete and shared with team members.
- [ ] Synthesis is posted in GH.

**Comment by EWashb** [comment]
original research intention does not reflect current state. closing.
