### ISSUE TITLE
Design proposal for the new navigation

### ISSUE THREAD

**Issue by jordanamello** [department-of-veterans-affairs/va.gov-cms#3893]
_As a UX researcher, I want to convey research findings into a navigation proposal, so that it can be used as CMS users test it._ 

**AC:**
- [ ] UI elements are selected.
- [ ] Navigation is designed.
- [ ] Proposal is shared with team members and feedback is incorporated.
- [ ] Prototype is finalized.

**Comment by EWashb** [comment]
original research intention does not reflect current state. closing.
