### ISSUE TITLE
Usability study to test the navigation proposal - planning

### ISSUE THREAD

**Issue by jordanamello** [department-of-veterans-affairs/va.gov-cms#3894]
_As a CMS UX researcher, I want to test a new navigation proposal with users, so that we can validate if users can find information and functionality._ 

**AC:**
- [ ] Research plan is written and added to GH.
- [ ] Participants are selected.
- [ ] Prototype is adjusted to respond to test scenarios.
- [ ] Sessions with participants are scheduled.

**Comment by EWashb** [comment]
original research intention does not reflect current state. closing.
