### ISSUE TITLE
Design iteration on Content Release status and WEB branch selection component

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#3902]
## Acceptance Criteria
- [x] UX Content Release status and WEB branch selection component is reviewed w/ engineering team to understand technical limitation and component intent
- [x] recommendations for UX improvements are provided in a lightweight mock
   - [x] menu labels and text in the CMS for triggering content release
   - [x] help text on the content release page/form, etc
   - [x] help text for release status: if fails->report to help desk
- [x] technical feasibility is reviewed
- [x] feedback incorporated

**Comment by jordanamello** [comment]
@rachel-kauff here's the [Mural](https://app.mural.co/t/vagov6717/m/vagov6717/1610568308214/461d96649eeee42d44359a9900321fe7e5b02c7c) for our work on Tuesday.

**Comment by oksana-c** [comment]
@rachel-kauff , yes, we didn't get to talk about the various statuses and help text for those on the call yesterday.
The status indicator updates itself without a page refresh in the status table within 60 seconds of triggering the release. The status update may appear within 5, 10, ... 60seconds, so there is a range, but no later than 60 seconds.
If status = Failed, we need a direction for the user to contact help desk using the JSD portal link. This could be a short intro text above the status table.

@indytechcook @acrollet and I briefly talked about two different headers and menu items for prod and demo environment forms and had some feasibility concerns. Let's continue the conversation today - sent an invite. /cc @jordanamello

**Comment by jordanamello** [comment]
Final wireframes can be found [in this Mural](https://app.mural.co/t/vagov6717/m/vagov6717/1610568308214/461d96649eeee42d44359a9900321fe7e5b02c7c), along with some backlog items.
