### ISSUE TITLE
Remove /va/deploy steps from tests.yml

### ISSUE THREAD

**Issue by indytechcook** [department-of-veterans-affairs/va.gov-cms#3904]
## Description

Remove /va/deploy steps from tests.yml as they are not used.  This will speed up with staging deploy/test runs

## Acceptance Criteria
- [ ] Build works and tests pass on lando, tugboat and BRD

**Comment by ElijahLynn** [comment]
Need to do this now as it will make https://github.com/department-of-veterans-affairs/va.gov-cms/issues/4194 easier.

**Comment by ElijahLynn** [comment]
Tests got a bit faster (as expected): 
![image](https://user-images.githubusercontent.com/1504756/108789860-1835ef80-7530-11eb-9b34-496e048be432.png)
