### ISSUE TITLE
Implement CLP collapsible fieldsets with labels and help text

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#3908]
See https://balsamiq.cloud/s21kwcm/py46j7t/r48AD 

ACs
- [x] Vertical tabs have been replaced by collapsible fieldsets
- [x] Hero banner fieldgroup is open by default, the rest are all closed.
- [x] Fieldgroup help text has been added, per the Balsamiq design
- [x] Collapsible fieldset text matches h2, not uppercase text--but only on this form, and not on the right rail
- [x] Boolean TRUE labels all read "Enable this page segment" and have no field description. 

![Screenshot_2021-01-04__4_17_PM.jpg](https://images.zenhubusercontent.com/5d6e57ad330f64311395f08b/e167fd30-fdcb-4fb8-a4ad-11794c7fd966)

Not included
- [ ] Custom visual guide

**Comment by cmaeng** [comment]
@rachel-kauff can you do a design review of this when you get a chance? thanks!

**Comment by rachel-kauff** [comment]
@ethanteague or @cmaeng Where can I find the linky to the PR environment to review?

**Comment by ethanteague** [comment]
> @ethanteague or @cmaeng Where can I find the linky to the PR environment to review?

https://pr3979-y8bzuweqp2giz2yvkn3tu3rlj8ggh44f.ci.cms.va.gov/

**Comment by kevwalsh** [comment]
@rachel-kauff  Your review should go on the PR, which is #3979 ... i assigned it to you for review.

**Comment by rachel-kauff** [comment]
Ah, thank you.  Will take a look there. I just didn't see the PR linked in this ticket.
