### ISSUE TITLE
Improve field labels and field descriptions for text fields on CLP form

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#3916]
ACs
- [ ] Field labels and help text for text fields (WYSIWYG) match the improved specs in https://balsamiq.cloud/s21kwcm/py46j7t/r48AD

Not included in scope: fields in paragraphs.

**Comment by kaise-lafrai** [comment]
@rachel-kauff Hello! Do we have a url for this link? ![image.png](https://images.zenhubusercontent.com/5f04cf76eb6c0026ebd18020/0593cf39-6559-489c-9591-5d158de330a9)
