### ISSUE TITLE
Spotlight panel link teasers: Can add 3, but only 1 gets saved.

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#3921]
**Describe the defect**
When adding 3 link teasers to the Spotlight panel, only 1 gets saved.

**To Reproduce**
1. Edit node 15068
2. Add two more link teasers in the Spotlight panel
3. Save. 
4. See that only 1 is saved. 

**Expected behavior**
I should be able to add 1, 2, 3, but not 4 or 0.

**Screenshots**
![Edit_Campaign_Landing_Page_VA_Solid_Start___VA_gov_CMS.jpg](https://images.zenhubusercontent.com/5d6e57ad330f64311395f08b/17806586-e600-4229-a49b-4f323446226d)

**Comment by cmaeng** [comment]
Putting in PO review for @RLHecht and @johnhashva to validate before closing out.
