### ISSUE TITLE
Entity browser for events only shows a subset of events

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#3922]
**Describe the defect**
When adding an event to a CLP, i should be able to add any future event. But currently i only see two events, when there should be a few dozen. 

**To Reproduce**
1. Go to node/15068/edit
2. In the events panel, remove an event, then add a new one
3. You only see two events

**Expected behavior**
You should see a list of events that includes all those at www.va.gov/outreach-and-events/events, as well as those at VAMC Pittsburgh https://www.va.gov/pittsburgh-health-care/events 

**Screenshots**
This screenshot shows that only 1 of the events from outreach hub is visible in the entity browser.

[Uploading... Edit_Campaign_Landing_Page_VA_Solid_Start___VA_gov_CMS_and_Outreach___Events___Outreach_Events___Veterans_Affairs.jpg ]

**Comment by kaise-lafrai** [comment]
@kevwalsh I am not able to reproduce. I tried logging in as myself and as john.hashimoto@va.gov and both show all future events in the browser. Do we know who reported this?

**Comment by kevwalsh** [comment]
It was reported by @johnhashva . 

I am unable to reproduce on Prod as admin user.
I am unable to reproduce on staging as content admin (john.hashimoto@va.gov) 
I _can_ reproduce locally as admin user (albeit with a slightly dated codebase and database). 

Let's close this as invalid, and reopen if necessary.

**Comment by johnhashva** [comment]
@cmaeng and @kevwalsh confirmed this is now working as expected.
