### ISSUE TITLE
CLP editors should be limited to 2 related benefits

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#3924]
**Describe the defect**
Editors should only be able to select two benefit hubs in the VA benefits panel. Currently they can add unlimited. 

**To Reproduce**
1. Go to node/15051
2. See that there are more than 2. 

**Expected behavior**
Editors should only be able to select 2. 

**Screenshots**
![Edit_Campaign_Landing_Page_TEST_Get_your_flu_shot___VA_gov_CMS.jpg](https://images.zenhubusercontent.com/5d6e57ad330f64311395f08b/8b0545b3-6fe2-4e15-9ce4-db648ab0b9b5)]

**Implementation**
We may need a new field for this. The current field with unlimited values has 15 uses. 

Otherwise, we could provide custom form validation in this specific context. 

![Related_benefits___VA_gov_CMS.jpg](https://images.zenhubusercontent.com/5d6e57ad330f64311395f08b/5e7612fb-4ce6-4977-9112-d7523a67d6d3)

**Comment by cmaeng** [comment]
Putting in PO review for @RLHecht and @johnhashva to validate before closing.
