### ISSUE TITLE
Remove media URLs from broken link check

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#3926]
**Describe the defect**
Media URLs are a false positive in the node link check.  

**To Reproduce**
1. Go to https://prod.cms.va.gov/node/15068
2. Click on the node link report
3. Note the broken media link 

**Expected behavior**
Media links do not get reported as broken. 

**Screenshots**
![VA_Solid_Start___Veterans_Affairs.jpg](https://images.zenhubusercontent.com/5d6e57ad330f64311395f08b/9be5ad3e-b8ea-4f09-be47-247a44dfd1a8)

**ACs**
- [ ] No media references should be rendered as entity references on all entities
  - [ ] Image media should be rendered as images, using settings that match the FE.
  - [ ] Videos should be rendered as videos
  - [ ] File downloads should be rendered as download links (and should be available to anonymous users)

**Comment by kaise-lafrai** [comment]
@kevwalsh MEDIA Links now do not get reports as broken. To fix that I updated the ignore list for the node link checker to ignore the following `/media/*`

Media IMAGES/VIDEO still load as entity references, but I updated the default view for IMAGES/VIDEO Media settings to link back to the media content on node view.

This is ready for review here: https://github.com/department-of-veterans-affairs/va.gov-cms/pull/3966

**Comment by kevwalsh** [comment]
nice work @kaise-lafrai !

**Comment by cmaeng** [comment]
Putting in PO Review for @RLHecht and @johnhashva to validate before closing.
