### ISSUE TITLE
Design: CLP: Clarify required and enabled "page segments"

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#3935]
## User Story or Problem Statement

As a CLP content editor, 
* i can easily see which segments are required, even when a segment is collapsed
* i can easily see which optional segments are enabled, even when a segment is collapsed
* i can enable/disable them in an intuitive way
* i can easily see what segments can and can't be disabled, even when a segment is collapsed (i.e., required or not)
* i can see fields that are disabled before enabling them, so that i know what will be expected of me if i enable the field group. 

### Background

The CLP UI does a very poor job of communicating which "page segments" (i.e., sections of the FE template) are required, and which optional ones are currently selected by the Editor ("enabled").

(Note: in screenshot I have collapsed the Hero banner segment, which is expanded by default when the form opens.)
<img width="428" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/4054752/e4e742c4-a577-4762-a604-9712181c95c8">
- Contrary to the help text, there are no `*` on any segments to indicated required.
- One apparent difference between some panels is the presence or not of an "Enable" checkbox at the bottom of the panel (see screenshot below). 

Each of the optional expandable panels in the CLP UI has a checkbox at the bottom, "Enable this page segment." 
<img width="444" alt="Screenshot 2023-08-28 at 11 07 05 AM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/4054752/4dbccd8a-0919-43ff-a344-675347279021">

## Acceptance Criteria

- [ ] Figma design captures the following (or rationale provided for omitting it)
  - [ ] "Enabled" badge appears on the fieldset `summary` when checked (i.e., is visible when segment UI is collapsed)
  - [ ] Mandatory segments show "This segment is required, and will appear on your campaign's page."
  - [ ] Fields are visible but disabled when boolean is unchecked. 
  - [ ] Boolean has been replaced by a slider. 
  - [ ] Asterisks do not show until a field becomes enabled. 
  - [ ] Textcounters are also greyed out via css .fie (fix this for /node/add/health_care_local_facility too) (`.form-disabled textfield_counter_counter` 
- [ ] Feedback cycles with...

**Comment by TheBoatyMcBoatFace** [comment]
Removing Platform CMS Label due to current team structure.

**Comment by wesrowe** [comment]
@davidconlon, FYSA this design issue would be the place to start for improvements to the CLP UI. The UI doesn't appear to live up to a basic standard of UX that we've tried to enforce on other content types PW has touched recently: what fields are required? That info is pretty hidden in the CLP UI until a user has found their way around.

**Comment by FranECross** [comment]
Old ticket; closing and will either reopen, or create a new ticket if this issue bubbles up again.
