### ISSUE TITLE
Download File Tests

### ISSUE THREAD

**Issue by indytechcook** [department-of-veterans-affairs/va.gov-cms#3937]
## Description

The tests for https://github.com/department-of-veterans-affairs/va.gov-cms/issues/3436 was removed here: https://github.com/department-of-veterans-affairs/va.gov-cms/commit/f6c81497d9842cb7fc85c1c53bd130c07dc6e647.  The old tests had asumed content from prod would not change.

The tests should generate their own test content.

## Acceptance Criteria
- [ ] New download file link behat tests should pass independent of content changes on production.

**Comment by ndouglas** [comment]
The reason I didn't do this initially is because I wasn't able to figure out how to do this intelligently with the Goutte driver, which doesn't interact well with the media library.  Any thoughts on this?  Am I missing something obvious?
