### ISSUE TITLE
Address block styling to R&S rich text fields

### ISSUE THREAD

**Issue by VanessaLuxen** [department-of-veterans-affairs/va.gov-cms#3950]
## User Story or Problem Statement

As an editor of content with Limited rich text fields (such as R&S), i want to add the address block styling to any address in my content, so that i can follow the VA Design System. 

Original Support request from @RLHecht 
> We have an R&S page that lists an address but there is no ability to use the address block on like on regular benefit hub detail pages. Can this be added to the rich text field? I know that the rich text field is more limited for R&S but this seems like a component that might be used on occasion and should be consistent with our style on other pages.

https://va-gov.atlassian.net/browse/VAHELP-217

https://dsva.slack.com/archives/CDHBKAL9W/p1609883030322300
## Acceptance Criteria
- [ ] 👀 **Needs design review** because the work involves changes to labels or other design elements.
- [ ] 🙈 Can be implemented without consulting design team members
* Testable_Outcome_X
* Testable_Outcome_Y
* Testable_Outcome_Z

## Implementation steps
<optional>

**Comment by VanessaLuxen** [comment]
This came into the Slack Support channel on 1/5/2021 entered into Jira and made this ticket for @oksana-c to refine.

**Comment by kevwalsh** [comment]
As posted on Slack: 

The business need to limit the functionality of rich text fields within R&S product came from Public Websites team.  Adding new features to it is not a big lift for us, but i’d want to get the PO for the R&S product to make this decision and prioritize against other needs.  @johnhashva  if you like we can discuss the priority of this at our next meeting, January 20?

**Comment by johnhashva** [comment]
@kevwalsh yes, let's put it on the agenda.  TY.

**Comment by xiongjaneg** [comment]
@stefaniefgray @chriscraiga6 This is a good example to use for the tier 2 process documents see: [#4721](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/4721)

**Comment by RLHecht** [comment]
Is this something that is still planned for the (hopefully near) future? We have a few pages now that have addresses but they are just styled as plain text since we don't have that block option yet.

**Comment by laflannery** [comment]
@RLHecht I was going through our backlog around CKeditor improvements and found this. Are you able to tell me if this is still an issue?

For example I found a resources detail page with a formatted address here: https://www.va.gov/resources/how-to-report-the-death-of-a-veteran-to-va/ So if this is still an issue could you provide a bit more context?

**Comment by RLHecht** [comment]
Thanks for the check on this @laflannery. I think this is still an issue with the single Q&A component. I don't see an option for an address block in the rich text field if I were to create a new one.

**Comment by laflannery** [comment]
Thanks!

Notes for myself - for ckeditor 5, we should have a rich text field option that includes the styles option but does NOT include the format options (something between the current Limited and Full editors)

**Comment by RLHecht** [comment]
@laflannery Someone just pointed out a wonky address on the [How do I notify VA of my intent to file?](https://www.va.gov/resources/your-intent-to-file-a-va-claim/#how-do-i-notify-va-of-my-inten) single Q&A. I keep trying to fix the spacing but it doesn't seem to be working. I thought this was connected to the linkys issue a while back and I reverted to a previous version but that didn't seem to fix it.

**Comment by laflannery** [comment]
@RLHecht I have tested this and it looks like this is occurring on all Limited Rich text editors - I tested multiple content types in staging. So it's not related to this but I'm going to open a separate defect ticket for the CMS team

**Comment by RLHecht** [comment]
@laflannery do you know if this spacing issue is being worked on? Megan is making other edits to the page I referenced above and was hesitant to publish with the spacing the way it is.

**Comment by laflannery** [comment]
@productmike Can you give @RLHecht an update on the status of [this ticket](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13550)?

**Comment by productmike** [comment]
appreciate the follow-up @laflannery! 

@RLHecht the CMS team is in the midst of D10 upgrade, so we haven't had a chance to dig into this. Wondering, if you had to give this a priority between 1-5 (1 --> highest; 5 --> lowest), what would you rank this as? It'll help me negotiate our capacity and goals for the upcoming sprints

**Comment by RLHecht** [comment]
Thanks @productmike . I think I would give it a 2. It definitely looks like an error on the page with the way the spacing is set up.

**Comment by productmike** [comment]
@laflannery since #13550 has been opened to track the remaining defect, can I close out this ticket?

**Comment by EWashb** [comment]
Looks like we've been back and forth on this one for a while, but am I wrong in thinking the R&S product should be with Public Websites? Seems like it gets a little messy though since the ask is for updates to the text editor. Thoughts? @jilladams @wesrowe

**Comment by laflannery** [comment]
@EWashb A lot of the comments actually have to do with an entirely different issue, not what is being requested in this ticket.

My 2 cents on this particular ticket is that we, the CMS team, might want to consider allowing the Style option in the Limited rich text editor. Unlike allowing The format option with headings, I don't think allowing proper address styling would create errors/issues within the content.

**Comment by EWashb** [comment]
Ah, I've got you, Laura. This is larger than R&S itself. Sorry for the noise, Jill and Wes!

**Comment by productmike** [comment]
Moving to prefinement

**Comment by wesrowe** [comment]
it was worth the "noise" to learn that you all use the word "prefinement" – I think I had been tempted in the past but was afraid

**Comment by EWashb** [comment]
This is not going to be addressed in Ckeditor5. We will need to address separately.

**Comment by EWashb** [comment]
Now that D10 has been released I think it is worth it to bring this back in for some discovery. The additional lines are causing an undesired and confusing experience. This might need to be a discovery ticket. @laflannery since this has followed you around...you think it could be worth just recreating a separate CMS ticket for the new team to do some discovery on how to remove those extra lines (at minimum). This has been a recurring ask from @RLHecht 

cc: @michelle-dooley

**Comment by laflannery** [comment]
@EWashb I had already created [a separate defect issue](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13550). I tracked that down, found it closed and that another, [follow up ticket](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16232) was created. However, that second ticket is also closed. Looking at [the PR](https://github.com/department-of-veterans-affairs/va.gov-cms/pull/16266) connected to that final ticket, there are screenshots showing that it was actually resolved so it seems like it might have reverted? 

I think maybe (assuming my investigation got me to the right place) we need to create a ticket to determine why this bug is present again after having been resolved previously. I can go ahead and create that if that makes sense to you.

**Comment by RLHecht** [comment]
@laflannery do you think we need to manually make the change in the pages where it's still occurring? I can try to update in Drupal and see if it's fixed.

**Comment by laflannery** [comment]
@RLHecht It's worth a shot. [This was the page](https://www.va.gov/resources/your-intent-to-file-a-va-claim/#how-do-i-notify-va-of-my-inten) I was looking at, maybe try resaving it or readding the address?

**Comment by RLHecht** [comment]
@laflannery looks like that worked! Amazing!!

**Comment by EWashb** [comment]
Wow @laflannery! Thank you! This is a big win!

**Comment by laflannery** [comment]
So glad we got this done @EWashb @RLHecht

**Comment by EWashb** [comment]
@RLHecht are we good to close this ticket?

**Comment by RLHecht** [comment]
Yep, we are good to close! Thank you again for finally getting this implemented. This might seem tiny but it was HUGE for us!

**Comment by RLHecht** [comment]
Hey @EWashb and @laflannery, do you know if adding the address block style to the limited rich text field in Drupal is still being worked on or discussed? I realized we closed this ticket because the extra spacing was fixed, but we still aren't able to style addresses in R&S like we do on benefit detail pages.

**Comment by laflannery** [comment]
@RLHecht I am not on this any more but am going to tag @gracekretschmer-metrostar as the new PM to follow up on. Grace, if you would like to get any context from me to help get you up to speed on this so you can understand how what this is exactly feel free to ping me!
