### ISSUE TITLE
File permission set error on cms export tugboat 

### ISSUE THREAD

**Issue by indytechcook** [department-of-veterans-affairs/va.gov-cms#3959]
## Description

When saving nodes in Drupal, a new version of the json file used for the cms-export should be created. Currently, there is a file permission error on tugboat.  The files do get created so this is not a blocker.

```

The file permissions could not be set on public://cms-export-content/menu_link_content.c8833fbb-00d4-4d85-9f05-df991ba7b4bd.json.
--
```

## Acceptance Criteria
- [ ] CMS export json files are created when a node is saved.
- [ ] Error message no longer appears when node is saved

**Comment by oksana-c** [comment]
closing as this story becomes deprecated along w/ cms-export 

@indytechcook please reopen if this is a symptom of a different issue.
