### ISSUE TITLE
Create demo environments in Tugboat

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#3975]
## Description

The team has made a decision that any new Demo environments will have to be requested thru CMS help desk.

We need to create all existing and relevant Demo environments in Tugboat prior to introducing the Tugboat to our users.

## Acceptance Criteria
- [x] Verify which ENVs are still needed (check w/ VAMC Upgrade/PW/Facility POs) [@oksana-c ]
- [x] Create environments in Tugboat using the same names/aliases [@oksana-c @VanessaLuxen @erogray  ]
   - naming convention documented for Helpdesk reference
   - check FE branch for each replicated environment

---

### Update 01/25/21

due to cloning defects, all environments have incorrect cms/web URL

- [x] all Demo environments point to correct URLs : CMS / WEB
    
## Implementation notes
- help desk reps need to observe the process in order to learn how to work Tugboat UI in the future, so it is best that environments are created during a live co-working session w/ @VanessaLuxen and/or @erogray

**Comment by oksana-c** [comment]
## Environments to create in Tugboat:
_below is the list of environments from DevShop that need to be created in Tugboat_

### For VAMC Upgrade team
- [ ] Alexandria health care
- [ ] Altoona health care
- [ ] Asheville health care
- [ ] Bay Pines health care
- [ ] Butler health care
- [ ] Central Arkansas health care
- [ ] Cheyenne health care
- [ ] Coatesville health care
- [ ] Durham health care
- [ ] Eastern Colorado health care
- [ ] Eastern Oklahoma health care
- [ ] Fayetteville Arkansas health care
- [ ] Fayetteville Coastal health care
- [ ] Gulf Coast health care
- [ ] Hampton health care
- [ ] Houston health care
- [ ] Jackson health care
- [ ] Lebanon health care
- [ ] Montana health care
- [ ] Oklahoma City health care
- [ ] Philadelphia health care
- [ ] Richmond health care
- [ ] Salem health care
- [ ] Salisbury health care
- [ ] Salt Lake City health care
- [ ] Sheridan health care
- [ ] Western Colorado health care
- [ ] Wilkes-Barre health care
- [ ] Wilmington health care

### Other
- [ ] Resources and support
- [ ] CMS Training
- [ ] Dave Conlon's Sandbox


## Environments in question
_below is the list of environments from DevShop that may no longer be needed_

@kevwalsh / @swirtSJW please strike through (`~x~`) all environments that are no longer needed in the list below. Thank you!

- [ ] Benefit Hubs (updated 6 months ago)
- [ ] CLP (updated 6 months ago)
- [ ] CMS Training (updated 4 months ago)
- [ ] Corona Virus Research (updated 4 months ago)
- [ ] Facility Health Services (updated 5 months ago)
- [ ] Forms (updated 4 months ago)
- [ ] Jesse  (updated 2 months ago)
- [ ] Kev  (updated 7 months ago)
- [ ] MDT (updated 10 months ago)

**Comment by oksana-c** [comment]
New Demo environments - https://tugboat.vfs.va.gov/5ffe2f4dfa1ca136135134f6

**Comment by VanessaLuxen** [comment]
@oksana-c To be clear do these all need new demo environments of did you just reassign this ticket?

**Comment by oksana-c** [comment]
@VanessaLuxen , these will all need to be deleted and then created again. We're just waiting for a go ahead from @ElijahLynn that the platform is ready for us to do that.
