### ISSUE TITLE
Tugboat ENV URL behavior

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#3977]
## Description

As a CMS user, who works with CMS Demo environments, I want to have a stable URL to my Demo environment, so I don't have to fetch it from Tugboat UI every time I need work in that environment.

## Acceptance Criteria
- [x] Test the behavior for ENV URL generation when the environment is rebuilt. 
- [x] Confirm that the token is not changed upon rebuild.  Document finding in this issue and this working [doc](https://docs.google.com/document/d/1ZrTCXbFYUp8qgiqpzVhO2XAMZko2tbJvMVGEIF6oLQ8/edit#)
- [x] Tugboat readme is updated - https://github.com/department-of-veterans-affairs/va.gov-cms/blob/master/READMES/tugboat.md#known-issues

[Slack thread](https://dsva.slack.com/archives/C01A35JDH88/p1610389392282500)

## Scenarios to test

- Rebuild  (build stage; pulls latest commits and latest DB) - slower option
- Refresh (update then build stages; pulls latest public files dir and latest DB + latest code on the preview branch) - faster option
- Reset  (wipes any config, files and content updates; tests are not run; web build needs to be run manually)
- new commit pushed to branch

**Comment by olivereri** [comment]
![image.png](https://images.zenhubusercontent.com/5f04cf8f49978b1615fee8c2/7485c17b-b70d-4796-88ba-3a57c4cfdca7)

# PR Created
Token:
nhlzlt2zjlmbg6fiwokjj90b4mgrahjl
Links:
https://pr4039-nhlzlt2zjlmbg6fiwokjj90b4mgrahjl.ci.cms.va.gov
https://cms-nhlzlt2zjlmbg6fiwokjj90b4mgrahjl.ci.cms.va.gov
https://web-nhlzlt2zjlmbg6fiwokjj90b4mgrahjl.ci.cms.va.gov
Dashboard:
https://tugboat.vfs.va.gov/600774676d2f6ce91e2cc188


# Rebuild
Token:
nhlzlt2zjlmbg6fiwokjj90b4mgrahjl
Links:
https://pr4039-nhlzlt2zjlmbg6fiwokjj90b4mgrahjl.ci.cms.va.gov
https://cms-nhlzlt2zjlmbg6fiwokjj90b4mgrahjl.ci.cms.va.gov
https://web-nhlzlt2zjlmbg6fiwokjj90b4mgrahjl.ci.cms.va.gov
Dashboard:
https://tugboat.vfs.va.gov/600774676d2f6ce91e2cc188

# Refresh
Token:
nhlzlt2zjlmbg6fiwokjj90b4mgrahjl
Links:
https://pr4039-nhlzlt2zjlmbg6fiwokjj90b4mgrahjl.ci.cms.va.gov
https://cms-nhlzlt2zjlmbg6fiwokjj90b4mgrahjl.ci.cms.va.gov
https://web-nhlzlt2zjlmbg6fiwokjj90b4mgrahjl.ci.cms.va.gov
Dashboard:
https://tugboat.vfs.va.gov/600774676d2f6ce91e2cc188

#Reset
No comment sent back to Github.

# New commit
Token:
nhlzlt2zjlmbg6fiwokjj90b4mgrahjl
Links:
https://pr4039-nhlzlt2zjlmbg6fiwokjj90b4mgrahjl.ci.cms.va.gov
https://cms-nhlzlt2zjlmbg6fiwokjj90b4mgrahjl.ci.cms.va.gov
https://web-nhlzlt2zjlmbg6fiwokjj90b4mgrahjl.ci.cms.va.gov
Dashboard:
https://tugboat.vfs.va.gov/600774676d2f6ce91e2cc188

**Comment by olivereri** [comment]
It appears that what Ben Chavet of Tugboat said holds:

```
I guess there is an edge case there. tokens are actually assigned to services, which are identified by name. So, if you add/rename a service, then make it the default service for a preview, then the default preview URL will change
```

The above we require a change to .tugboat/config.yml to the specified sections in the config file.  That seems to be what was observed when Elijah mentioned seeing the token in the URL change. In all cases Rebuild, Refresh, Reset, and a New Commit, the token did not change.

**Comment by olivereri** [comment]
Multiple different commits still doesn't trigger a change in the token:

![image.png](https://images.zenhubusercontent.com/5f04cf8f49978b1615fee8c2/1cbd0053-7200-4c3a-9ce4-41aad395e1d1)

**Comment by olivereri** [comment]
No token change after the base image has been changed/updated:

![image.png](https://images.zenhubusercontent.com/5f04cf8f49978b1615fee8c2/e2cdd4f3-5d4a-4235-9ba7-ed0e490598db)

**Comment by olivereri** [comment]
I made a slew of .tugboat/config.yml changes in an effort to affect a token change that in-turn changes the preview URLs. The very last change was to the name of the `php` service to `php2`. This finally created a change in the token.  This not a change those using or creating Demo environments should not, or will ever make.

![image.png](https://images.zenhubusercontent.com/5f04cf8f49978b1615fee8c2/e8f87239-1326-4ea6-b129-e694a9095acf)
