### ISSUE TITLE
Include Revision ID (vid) in debug info for the FE page

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#3982]
As a CMS engineer, who needs to troubleshoot Content Release, I need to have access to revision ID in node debug info on FE page in addition to node ID.

## Acceptance Criteria
- [ ] Revision ID (vid) is avaialble in debug info for FE pages on staging/dev envs

**Comment by ndouglas** [comment]
I merged department-of-veterans-affairs/vets-website#15742, so this should be visible on dev/stg _soon_...

**Comment by oksana-c** [comment]
confirmed on staging 
<img width="1379" alt="Screen Shot 2021-02-03 at 8 03 53 AM" src="https://user-images.githubusercontent.com/16477724/106765867-8012ad80-65f6-11eb-88af-9e595129625a.png">
