### ISSUE TITLE
Content not deploying

### ISSUE THREAD

**Issue by ElijahLynn** [department-of-veterans-affairs/va.gov-cms#3983]
Expected content is not deploying. 

@RLHecht reported an issue yesterday saying content is not deploying.

https://dsva.slack.com/archives/CDHBKAL9W/p1610407847358300
https://dsva.slack.com/archives/CBU0KDSB1/p1610470935377100

**Comment by acrollet** [comment]
This was resolved by https://github.com/department-of-veterans-affairs/devops/pull/8354

**Comment by acrollet** [comment]
#3984 is a follow-on from this issue.

**Comment by oksana-c** [comment]
also #3982
