### ISSUE TITLE
Announcement prep: Official transition to new Demo environments

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#3990]
#3502 

## Acceptance criteria

- [x] the announcement for the official transition from DevShop to Tugboat is prepared - tentative send ~ February 5th 

## Writer / assignee
Defaults to @rachel-kauff unless she's not available.

## Checklist

- [x] Draft announcement content
  -  If you're new to writing announcements, [review this guide](https://airtable.com/tblulo3XrMLuh4N0l/viwSVSkpseM78xmgw?blocks=hide) 
  - Use the template to draft the announcement content in the [AT announcement log](https://airtable.com/tblulo3XrMLuh4N0l/viwSVSkpseM78xmgw?blocks=hide).
- [x]  Get review: post the drafted release note in #cms-team. Tag the product manager and teammate who worked on it. Work out any clarifications/edits in the thread, and then get 👍🏻 from PM.

**Comment by rachel-kauff** [comment]
Update: draft can be found in this thread: https://dsva.slack.com/archives/CT4GZBM8F/p1611274161091300?thread_ts=1611274106.090300&cid=CT4GZBM8F

**Comment by rachel-kauff** [comment]
Draft updated and ready to roll.
