### ISSUE TITLE
Live training: new CMS Demo environments platform

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#3991]
## Description

Live training session "New CMS Demo environment platform"

## Acceptance Criteria

- [x] Audience for the training is selected
- [x] Live training session is scheduled / invites sent - tentative first week of February
- [x] Live training session is conducted
  - Elijah / Adrian to support training

**Comment by xiongjaneg** [comment]
scheduled for Thurs, Feb. 11, 2021, 12pm-1pm ET
