### ISSUE TITLE
User guide: How to access and manage Demo environments

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#3992]
## User Story

As a CMS user, I need to know how to access and manage CMS Demo environments, so that I don't have to ask for support every time I need to perform a simple operation.

## Acceptance Criteria
- [x] a user guide for accessing and managing Demo environments is available in CMS as a Draft
- [x] the guide is peer reviewed [@rachel-kauff @oksana-c ]
- [x] the guide is published

## Implementation notes

- define a new section in CMS help center

**Comment by xiongjaneg** [comment]
https://prod.cms.va.gov/help/how-to-access-and-manage-demo-environments
