### ISSUE TITLE
User guide: how to release content from the CMS

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#3993]
## User Story

As a CMS User, who has permissions to release content manually, I need to know how to use the updated "Release content" UI.

As a CMS User, who has permissions to release content manually, I need to know how to release content (a.k.a "generate full site preview") using a specific front-end branch.

## Acceptance Criteria
- [x] a user guide is written in draft
- [x] peer reviewed [@rachel-kauff @oksana-c ]
- [x] published

## Implementation notes

Content can be release using a CTA on the Release content page https://prod.cms.va.gov/admin/content/deploy 

Once we migrate to Tugboat, a new feature will be added on Demo environments that will allow users to release content by selecting a specific Front-end branch from `vets-website` repository.

New features also include a content release status display.

**Comment by xiongjaneg** [comment]
https://prod.cms.va.gov/help/how-to-release-content-in-the-demo-environment
