### ISSUE TITLE
On-demand recording: New Demo environments platform

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#3994]
## User Story

As a CMS user, who works in demo environments, I would like to have access to video recording that explains how to access and manage demo environments.

As a Content Publisher or Content Admin, I would like to have access to video recording that explains how to release content.

## Acceptance Criteria
- [x] video recording that explains **how to access and manage demo environments** is available in CMS help center
- [x] video recording that explains **how to release content** is available in CMS help center

## Implementation notes

video about content release should cover:
- content release on production 
- content release on demo environment using a specific front-end branch from `vets-website` repository

**Comment by xiongjaneg** [comment]
Posted Feb 11 
https://prod.cms.va.gov/help/how-to-access-and-manage-demo-environments
https://prod.cms.va.gov/help/how-to-release-content-in-the-demo-environment
