### ISSUE TITLE
bulk CMS user password creation

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#3998]
### User Story
As a CMS administrator, I want to be able to manually set the password for new users when importing via CSV at https://prod.cms.va.gov/migrate_source_ui

### Acceptance criteria

- [ ] Rows should be validated to confirm that the email address ends with `@va.gov`
  - If not, an on-screen message should be displayed to the user running the import: "The user with email address `foo@example.com` was not created, since it is not a va.gov email address."

- [ ] New user accounts should be configured to use SSO for login by default
- [ ] default password is set to `drupal8` if not on BRD + status message is displayed to user running the import "Password was set to `drupal8` for all imported users".
- [ ] Users accounts imported on non-BRD environments are imported as "Active"
   - [ ] a message is displayed to the user importing accounts on BRD "All accounts are created as active."
- [ ] User accounts imported on BRD are created as "Blocked"
    - [ ] a message is displayed to the user importing accounts on BRD "All accounts are created as blocked."

**Comment by oksana-c** [comment]
@acrollet the last two ACs about the SSO and pass need to change based on the 16th min convo we've had this morning.

All users should have SSO enabled by default.

The part around passwords needs a bit more thinking.
We should  _not_ generate random passwords.
User accounts are created in bulk to support training, but also these accounts will stick around on prod.
On prod users should be logging in w/ PIV.
On training environments, passwords are reset anyway, so there is no need to set them at all.

So if we follow the workflow ->> `generate accounts on prod > propagate to training by rebuilding the env` then we should be good without default passwords.

the only need to have default passwords is when we cannot create user account on prod for whatever reason. 
where workflow is reversed ->> `generate accounts on training env > generate them again on prod once users are cleared w/ training` 
Then we probably need to have a column for default passwords where if @xiongjaneg  starts importing on training env instead on prod, she can assign `drupal8` to all imported users. 

The security constraint would be:
* do not set passwords on prod even if they exist in the import file + output the message  "passwords are not set - users will to log in with PIV" and
* allow passwords to be set only on non-prod environments

**Comment by oksana-c** [comment]
@acrollet the last two ACs about the SSO and pass need to change based on the 16th min convo we've had this morning.

All users should have SSO enabled by default.

The part around passwords needs a bit more thinking.
We should  _not_ generate random passwords.
User accounts are created in bulk to support training, but also these accounts will stick around on prod.
On prod users should be logging in w/ PIV.
On training environments, passwords are reset anyway, so there is no need to set them at all.

So if we follow the workflow ->> `generate accounts on prod > propagate to training by rebuilding the env` then we should be good without default passwords.

the only need to have default passwords is when we cannot create user account on prod for whatever reason. 
where workflow is reversed ->> `generate accounts on training env > generate them again on prod once users are cleared w/ training` 
Then we probably need to have a column for default passwords where if @xiongjaneg  starts importing on training env instead on prod, she can assign `drupal8` to all imported users. 

The security constraint would be:
* do not set passwords on prod even if they exist in the import file + output the message  "passwords are not set - users will to log in with PIV" and
* allow passwords to be set only on non-prod environments

What do you think?

**Comment by acrollet** [comment]
@oksana-c thanks for the review, I realize now that I wrote down the logic incorrectly, it now reads `Only if the "Skip SSO" column is positive` rather than `Only if the "Skip SSO" column is not positive` - I further updated the ACs, let me know if they look good to you now?
