### ISSUE TITLE
SE: The CMS Design System

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#4000]
## Problem statement

The Drupal CMS for VA.gov must provide modern, intuitive Authoring Experience (AX) through improvement of visual and functional features and support agile product design and development.

## Background

CMS Design System's current state as of Q3 2022 is based on Drupal Claro OOTB which has provided enhanced accessibility as compared to its Drupal Seven counterpart. 

**Notes from Q1 2021**

Current Drupal CMS authoring experience lacks consistency, does not comply with Section 508 accessibility standards and is built upon outdated technology (open-source theme “Seven” that is soon to be deprecated).

Agile product design is not well supported given the current state of the CMS and Drupal themes in use.

## Hypothesis or Bet

* A Drupal-specific collection of design guidelines and standards will ensure that the Drupal CMS product features are developed in a consistent manner, following latest industry best standards.
* A collection of reusable, well documented and well tested tokens, components and patterns guided by clear standards will ensure consistency in Drupal application UI and support agile product design and development processes not only for the CMS team, but also for VFS Product teams.

## We will know we're done when... ("Definition of Done")

* 100% of the CMS UI has been accounted for in the CMS Design System Figma files and documentation.
* The Drupal CMS UI has transitioned to a new theme based on the modern open-source  Drupal Design System (Claro) and USWDS + VA DS standards and guidelines.
* The VA.gov Drupal CMS Design System documentation is developed using an iterative human-centered approach and is publicly available.
* The Drupal CMS Design System documentation is a go-to source for building and iterating on products for both the CMS and broader VFS teams. 
* Drupal CMS designers and engineers reference and enhance the VA.gov Drupal CMS Design System when building new and iterating on existing CMS products.
* VFS Product designers and content strategists reference the VA.gov Drupal CMS Design System documentation to learn about CMS content model and capabilities when building new and iterating on existing Veteran-facing products.

## Known Blockers/Dependencies

* The CMS Design System should be developed with the idea that product teams should be using this in a collab cycle format. 

## User Stories

As an engineer,
* I don't want to build and maintain numerous variations of one component.
* I have sufficient design guidance (variations, states and other behavioral and stylistic details) and code specs (variables, code examples) to complete a feature build
* I have a clear understanding of how to get specs from Figma prototypes created for the design system.

As a UX Designer/Content Strategist,
* I am able to standardize the CMS content model patterns and components as much as possible so that the CMS users have a consistent, intuitive and pleasant * experience.
* I have a set of design standards that makes my design / prototyping work more efficient

As a CMS Product Manager,
* I have access to in-depth documentation of the existing CMS content model patterns,
   * so that I can efficiently build products for VFS teams.
   * so that I have a formalized platform to advocate for reuse of existing CMS content model features instead of adding unique snowflakes

As a VFS Product Owner / VFS Product Designer,
* I have access to in-depth documentation of the existing CMS content model patterns so that I can build better products faster.

## va.gov-team product directory

https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/cms/product-outlines/cms-design-system (not currently used as of Q3 2022)

## CMS Design System FAQ

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/product-outlines/cms-design-system/FAQ.md (not currently used as of Q3 2022)

----
Copying some old stuff over from the MVP epic:
### Hypothesis 1: We need a new design system

We believe a modern design system will 
* improve the CMS UX 
* improve accessibility within CMS
* facilitate agile product design and iterations that improve the CMS UX

### Hypothesis 2: Claro

We believe that aligning our design system with the Drupal design system will 
* help accomplish Hypothesis 1 quickly
* align us with the future of Drupal open source editorial experience best practices

Assumptions
* Other admin themes are not as widely supported, eg [Material admin theme](https://www.drupal.org/project/material_admin)

### Hypothesis 3: VADS/USWDS

We believe that the VA design system (and to some extent its parent, USWDS)
* provides branding, elements, and other components that can guide the design for a new VA CMS theme. 
* will make it easier to provide a VA.gov content proofing experience 
* will keep CMS team closer to the governance of the broader design system, as CMS-based product teams create new design system components, or variations on existing components.

Assumption
* VA design system provides the best content proofing (node view, diff/compare) experience. This needs validation.

**Comment by EWashb** [comment]
The design system has been launched. I've moved any associated design issues into more appropriate epics.
