### ISSUE TITLE
CLP Hero segment label and help text adjustment

### ISSUE THREAD

**Issue by rachel-kauff** [department-of-veterans-affairs/va.gov-cms#4007]
## Description
I reviewed the initial CLP work from #3908 and found a few things that need adjusting

## Acceptance Criteria
- [ ] Hero banner segment:
   - [ ] Update the label 'Hero blurb' to `Page introduction`
   - [ ] Add help text to the button label field: `Add a button label phrased as a call to action E.g. 'Enroll in VA health care'`

**Comment by kaise-lafrai** [comment]
Related to : https://app.zenhub.com/workspaces/vagov-cms-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/3916
