### ISSUE TITLE
"Why can't i edit this content" contextual help text for centralized content

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#4017]
As an editor of local Policies content, i have contextual help explaining the purpose of national content, and why i can't edit it, on the form page and the view page

![2020_Policies_top_task_forms___2020_VA_gov___CivicActions___Balsamiq_Cloud.png](https://images.zenhubusercontent.com/5d6e57ad330f64311395f08b/46aefa22-fe8c-45b3-9015-3c340fdbab29)

![2020_Policies_top_task_forms___2020_VA_gov___CivicActions___Balsamiq_Cloud.png](https://images.zenhubusercontent.com/5d6e57ad330f64311395f08b/61ec6994-5552-473c-bbf6-ade4dea2e308)

ACs
- [x] "Why can't i edit this" content is visible to editors via a tooltip on the proofing screen and edit screen
- [x] Grey background for centralized content (assuming one color is ok, needs checking on design intent with @rachel-kauff) 
- [x] ~Developer info (paragraph id etc) is hidden on proofing page (eg Source:node 15588 paragraph 7192f5fb-08dd-4401-a863-c5a09cc7de50)~ moved to #4077
- [x] Content type description "Add policies specific to this VA medical center to appear on the Policies page. Local policies will appear alongside national policies that apply to all VAMCs."
- [x] Content type guidelines "`<h2>Policies VAMC top task page*</h2><p>Add policies specific to this VA medical center to appear on the Policies page. Local policies will appear alongside national policies that apply to all VAMCs.</p>`
- [x] ~All field labels on VAMC Policies Top Task are hidden on proofing page.~ moved to #4077
- [ ] "Policies" should look like an h1. 
- [x] Follow USWDS as much as possible
- [x] Tooltips should have speech bubble arrows
- [x] description should get moved to the top, via twig template

Implementation
- [x] Create a fieldset fieldgroup with a description on edit mode and view mode
- [x] Theme description to use the tooltip
- [x] Tooltip implementation approach for fieldgroup, with a class
- [x] Consider including "Why can't i edit this?" to the tooltip itself (needs design review)
-  [x] hide all field labels on VAMC Policies Top Task proofing page

**Comment by kaise-lafrai** [comment]
@kevwalsh @rachel-kauff Question: Do we want the tooltip to display the help text on **hover** or when either the icon or the "Why Can't I Edit This?" is **clicked**?

**Comment by kaise-lafrai** [comment]
@rachel-kauff Is the "Why Can't I Edit This?" text required? Should we just display the icon and put the "Why Can't I Edit This?" text within the help text on hover?

**Comment by rachel-kauff** [comment]
@kaise-lafrai Your question prompted me to reconsider whether we needed the 'Why can't I edit this' label,' so I experimented with removing it. I think we don't need it after all. I revised the OG wireframe, and included a screenshot below.

WRT the behavior of the icon: I think it should display on mouse and keyboard hover.

<img width="818" alt="Screen Shot 2021-01-26 at 8 25 06 AM" src="https://user-images.githubusercontent.com/41017988/105873154-094f3200-5fb0-11eb-826c-c37ca39e252d.png">

**Comment by kaise-lafrai** [comment]
@kevwalsh I am having some difficulty getting things to look right with the "policy" fieldset title.

Do we want all fieldset titles to be an h2 everywhere or only this specific title?

**Comment by kevwalsh** [comment]
@kaise-lafrai it's just the Policies string. 

last week when we talked about this, we also discussed the option of moving the string into a markup field in the content type, displayed as the first field int that fieldset, on the form.

**Comment by kaise-lafrai** [comment]
Let me try that. Thanks

**Comment by kaise-lafrai** [comment]
@kevwalsh H1 is not an allowable option for the markup wysiwyg!

**Comment by rachel-kauff** [comment]
Looking at [USWDS guidance on tooltips](https://designsystem.digital.gov/components/tooltip/) and am wondering if what we have currently is violating this guidance:

> Don’t block content. Use the data-position attribute to prevent the tooltip from covering other page elements.

I recommend having the balloon display on the right side (currently it's on the left, and covers the content).

**Comment by rachel-kauff** [comment]
Like this:
![Screen Shot 2021-01-28 at 4.25.22 PM.png](https://images.zenhubusercontent.com/5e399cf5446c5b4ca0e31e42/8c35750b-bb58-43c0-83cf-e1a784710d16)

**Comment by swirtSJW** [comment]
@rachel-kauff  That is an interesting detail, but I don't think we can completely win with that guideline.  If we move it to the right, it will still block stuff in the right rail.
![image](https://user-images.githubusercontent.com/5752113/106226787-fe65ee80-61b5-11eb-970f-81b391e3f2b0.png)

I'm going to move this forward with what we have and we can iterate if it is important.
