### ISSUE TITLE
CMS account administration service

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#4019]
## Problem statement

The CMS team is a bottleneck  when it comes to creating and updating CMS user accounts.

With an increased number of users and various teams in the CMS it becomes imperative that we have proper tools for managing user accounts at scale and the tools are reliable and stable enough to delegate User Admin responsibilities to VFS or other teams’ User Admins.

## Hypothesis or Bet

* Having access to clear and up-to-date information about roles, permissions and content governance in the CMS when requesting new or updated user accounts will reduce the amount of coordination before the account is created / updated.
* The availability of self-service tools for requesting, creating, managing user accounts is critical for managing CMS users at an enterprise scale and will remove the CMS team bottleneck from the process.
* If the CMS team can delegate User Admin responsibilities to other teams, we will free up our time for delivering value instead of performing clerical tasks.

## We will know we're done when... ("Definition of Done")

* The process for requesting, creating, managing user accounts in the CMS is designed.
* The information about CMS roles, permissions and content governance practices is available for quick reference.
* Self-service tools that support User Admin activities and requests related to the CMS user accounts are available.
* VFS teams are empowered to take upon CMS User Admin responsibilities.

## Known Blockers/Dependencies

* none

## Resources

* VAMC- CMS onboarding service blueprint and policies- https://app.mural.co/t/vagov6717/m/vagov6717/1605735264080/64a23a4e0bcff45cafebd576db9a787d54127dbc
* User account creation procedures DRAFT - https://docs.google.com/document/d/1t-fBvTLoQk-a7P56l1pmOx2NOCsN9FSYZXuTpsRraGc/edit#heading=h.s5vy91nn0f0j

## Spike Mural

https://app.mural.co/t/vagov6717/m/vagov6717/1611495933092/40b0bfce2e08962822b8535d975f4182b358c8e6 

## va.gov-team product directory

https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/cms/product-outlines/user-administration-service

**Comment by stefaniefgray** [comment]
@EWashb Is it okay to close this ticket? It's ancient and it seems like most of the work has been completed -- have not yet examined all the linked tickets, though
