### ISSUE TITLE
Ensure that transpiled JS matches original files

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-cms#4032]
## User Story or Problem Statement

As a developer, I need to be confident that the transpiled and committed JS files functionally match the original (es6) JS files.

## Acceptance Criteria
- [ ] A github action re-transpiles the JS files and fails the build if any changes are detected vs the committed files

**Comment by ElijahLynn** [comment]
I think this can be done in yaml-tests, yah?

**Comment by acrollet** [comment]
@ElijahLynn I'd think so, is that preferable to a gh action?

**Comment by ElijahLynn** [comment]
The main thing is to have parity between tests run on CI with local. I bet others have ran into this and wonder if there is a local GH actions runner.
