### ISSUE TITLE
Sprint 24 tier 2 helpdesk support

### ISSUE THREAD

**Issue by daddison48** [department-of-veterans-affairs/va.gov-cms#4033]
Sprint 24 Tier 2 Engineering Support

**Comment by acrollet** [comment]
**Date:** Jan 19
**Issue:** [Issue removing service locations](https://dsva.slack.com/archives/CDHBKAL9W/p1611073525021900)
**Resolution:** #4035

**Comment by acrollet** [comment]
**Date:** Jan 19
**Issue:** [FE search CTA issue](https://dsva.slack.com/archives/CBU0KDSB1/p1611080161155800)
**Resolution:** Triaged and passed to FE team

**Comment by acrollet** [comment]
**Date:** Jan 20
**Issue:** [Question from FE team about service location addresses](https://dsva.slack.com/archives/CDHBKAL9W/p1611160046028100)
**Resolution:** Researched and responded
**Time spent:** ~1 hour

https://dsva.slack.com/archives/CDHBKAL9W/p1611160046028100

**Comment by acrollet** [comment]
**Date:** Jan 20
**Issue:** [Editor not able to create "Story" content](https://dsva.slack.com/archives/CT4GZBM8F/p1611159806239000)
**Resolution:** 
**Time spent:**

**Comment by acrollet** [comment]
**Date:** Jan 20
**Issue:** [Request to add link attribute to breadcrumb](https://dsva.slack.com/archives/CDHBKAL9W/p1611182002036200)
**Resolution:** Messaged requestor, determined that it was a FE request
**Time spent:** ~30m

**Comment by acrollet** [comment]
**Date:** Jan 21
**Issue:** [Request for GraphQL query support](https://dsva.slack.com/archives/CDHBKAL9W/p1611252634001500?thread_ts=1611080998.024600&cid=CDHBKAL9W)
**Resolution:** Researched and responded
**Time spent:** ~30m

**Comment by acrollet** [comment]
**Date:** Jan 25
**Issue:** [Request for devshop content release error support](https://dsva.slack.com/archives/CDHBKAL9W/p1611601350009300)
**Resolution:** Researched and responded
**Time spent:** ~30m

**Comment by acrollet** [comment]
**Date:** Jan 26
**Issue:** [Possible bug on Q&A node edit form](https://dsva.slack.com/archives/CDHBKAL9W/p1611675997018300)
**Resolution:** Researched
**Time spent:**
