### ISSUE TITLE
Spike: Help desk - Tier 2 triage process

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#4034]
## Acceptance criteria

- [x] (1) the role and responsibilities of the Tier 2 rotation engineer are defined and documented
- [x] (2) process of collaboration between help desk and rotation engineer is defined and documented
- [x] (3) acceptance criteria for the ongoing tier 2 triage issue https://github.com/department-of-veterans-affairs/va.gov-cms/issues/4033 are formulated and serve as a template for all future tier 2 triage issues

#### AC 1: Role and Responsibilities of the Tier 2 rotation engineer

Tier 2 Support Rotation Engineer is a person who is responsible for assisting help desk team in triage of incoming issues within the sprint.

Rotation engineer responsibilities:
* triage the incoming requests as directed by help desk team
* expand an existing GH issue with triage information or create a new GH issue
* identify the issue owner: Core Application Team or Product support Team
* direct the issue to a specific team's backlog
* coordinate resolution with responsible team making sure that the team understands the SLA parameters as applied to that issue

Rotation engineer is not responsible for: 
* fixing all issues that may come in thru help desk intake
* watching Slack or Jira queues for user issue requests
* responding directly to users (in Jira, email or Slack) unless asked by Tier 1

#### Process of collaboration between help desk and tier 2 rotation engineer

TBD

#### AC 3: Draft of Acceptance criteria for the ongoing Tier 2 triage issue

- [x] technical questions that are directed thru help desk are addressed
- [x] critical defect are addressed within the SLA parameters
- [x] defects and enhancements are reviewed and directed to Core Application or Product Support backlog for prioritization based on information collected in triage

**Comment by acrollet** [comment]
Agenda question: are/should things like this be part of tier 2 responsibilities? https://dsva.slack.com/archives/CBU0KDSB1/p1611590647138900

(VA Forms support request made directly to @swirtSJW )

**Comment by VanessaLuxen** [comment]
Document outlining responsibilities for Tier 2 support is here: 
https://docs.google.com/document/d/15oe0wtGI_MdaScYpjJWOgPjBqQWUFURc19HheWswEe4/edit
Document for Tier 2 rotation:
https://docs.google.com/spreadsheets/d/1okLpafY5hJWdt6PFYh4tDUxIJkAAhmYTEYZIiTyrLhk/edit#gid=0
