### ISSUE TITLE
Bump drupal/components from 1.1.0 to 2.1.0

### ISSUE THREAD

**Issue by indytechcook** [department-of-veterans-affairs/va.gov-cms#4047]
## Description

Update components to 2.1.0.  This is a follow up of https://github.com/department-of-veterans-affairs/va.gov-cms/pull/4046

Diff:  https://git.drupalcode.org/project/components/-/compare/8.x-1.1...8.x-2.1

**Comment by oksana-c** [comment]
3 points

**Comment by acrollet** [comment]
`components` was removed in #4326
