### ISSUE TITLE
Spike: Allow different character count limits for components depending on the context in which the are used

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#4053]
Character limits are defined at the paragraph level. 

Occasionally, we want to specify different character limits depending on the context. 

When should we create a new component vs creating a variant of an existing one. 

ACs
- [ ] We have an engineering approach to creating different guardrails for use of the same component
- [ ] We have implemented this for Link teasers inside the promo content used within Stories panel on campaign landing pages.

**Comment by FranECross** [comment]
Old ticket; closing.
