### ISSUE TITLE
Last updated date for centralized content

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#4054]
As an editor of content with centralized content embedded, 
- i can see when the centralized content was last updated. 
- i can click on that date to get to the source content. 

![Screenshot_2021-01-21__1_19_PM.png](https://images.zenhubusercontent.com/5d6e57ad330f64311395f08b/31b6f176-e31f-45e4-86ff-55d1ae140113)

The contrib module has settings that allow us to display a link to source with a "Source" And/OR the date. 

The date looks like content as of today in our theme. 

The Source link does not meet the design spec above. 

![Screenshot_2021-04-01__1_45_PM](https://user-images.githubusercontent.com/643678/113333649-b156e380-92f0-11eb-837e-7358ed093ef9.png)

ACs
- [ ] Need refining with design

Implementation
- [ ] Possible update to EFF module
- [ ] Theming.

**Comment by rachel-kauff** [comment]
@kevwalsh It's important that there is a separate gray box delineating each piece of national content. That box should contextualize/contain the "last updated" link so that if there are two consecutive pieces of national content managed separately, it's clear what they are. In your example screenshot they seem to run together. Maybe that's something we missed in the original implementation?

At any rate, I do want to insist on the lower right corner placement for that link. Otherwise it gets noisy.

**Comment by rachel-kauff** [comment]
Some proposed ACs:
- link appears in lower right corner of the gray box, per the prototype
- Link text reads "Last updated [timestamp]"

**Comment by swirtSJW** [comment]
I merged this in contrib so we can have the date be the url.  https://www.drupal.org/project/entity_field_fetch/issues/3206961  
The text is not configureable and is  "Updated" to keep in alignment core drupal "standards"
![image](https://user-images.githubusercontent.com/5752113/113432018-a6f92000-93aa-11eb-9e41-139eabd63d3b.png)
This allows the common translation to already exist.

**Comment by swirtSJW** [comment]
Here is what it will look like when we pull down the latest contrib.  
![image](https://user-images.githubusercontent.com/5752113/113433078-85009d00-93ac-11eb-80d8-ac987435d03f.png)

It will need styling on our side to get it sized and positioned.

**Comment by swirtSJW** [comment]
It also has a title attribute to give meaning to what the link will actually do.

**Comment by kaise-lafrai** [comment]
@rachel-kauff Steve added some comments above. In summary, Steve made updates to the contrib EFF module to display the updated datetime as a link. In order to keep things aligned with drupal core standards, the text will have to say `Updated:` and not `Last updated:`. The datetime is current using the 'Short' format that we have defined here: `/admin/config/regional/date-time/formats/manage/short?destination=/admin/config/regional/date-time`. We can change the the short date format if needed. Let me know what you think! Thanks

![image.png](https://images.zenhubusercontent.com/5f04cf76eb6c0026ebd18020/4e7f16e3-c80b-432b-8ce8-2aab76bff3b2)

**Comment by kaise-lafrai** [comment]
@kevwalsh 

Do we want to adjust config to display the updated datetime link on all entity field fetch widget’s for all content types?

Here are the content types that are using EFF:
VAMC System Policies Page /admin/structure/types/manage/vamc_system_policies_page/form-display
Vet Center /admin/structure/types/manage/vet_center/form-display

Am I missing anymore?

**Comment by rachel-kauff** [comment]
@kaise-lafrai Thanks for the summary.  Bringing the `Updated:` label and date format into alignment with the existing convention is great. I have a few questions about what is best here for that short date format (The Apr 15 format seems a little awkward), but I don't think that should be a requirement for declaring this done. I'll look into that config you linked and make a separate issue if I think we should adjust. Thanks for your work on this!

**Comment by rachel-kauff** [comment]
Oh shoot, I think I confused something above. The date format I was seeing in the PR environment is the longer one, not the short mm/dd/yyyy - H:m format.

[Here's what I see in the PR environment](https://pr5074-zqscjp49mpbwhzgd9wnpycu37nwh8e3f.ci.cms.va.gov/node/16141/edit). Is there a reason the short format is missing?
 
 ![Screen Shot 2021-04-20 at 1.55.20 PM.png](https://images.zenhubusercontent.com/5e399cf5446c5b4ca0e31e42/4b9fa57d-7472-45ae-908c-c55a24aed5bc)

**Comment by swirtSJW** [comment]
@rachel-kauff  I think Kaise was working toward what was in the design
![image](https://user-images.githubusercontent.com/5752113/115465210-40725f80-a1fc-11eb-8988-c049ad034377.png)

**Comment by swirtSJW** [comment]
Not a ton of guidance from the design system here https://design.va.gov/content-style-guide/dates-and-numbers#dates-and-years

**Comment by rachel-kauff** [comment]
@swirtSJW Thanks for the clarification. Now that I see shortened date format, that does seem to make more sense than what I originally proposed. Plus this part from the DS guidance does apply here:

>  In application form fields, we often use the construction: mm/dd/yyyy

That is to say I'm in favor of using  `mm/dd/yyyy - H:m`

**Comment by swirtSJW** [comment]
> 
> That is to say I'm in favor of using `mm/dd/yyyy - H:m`
Thanks @rachel-kauff  I agree I like that format better.   Should we include `a.m.`  or `p.m.`  at the end to avoid confusion?

**Comment by rachel-kauff** [comment]
@swirtSJW Oh yes, if we can that would be 👌🏻

**Comment by kaise-lafrai** [comment]
@rachel-kauff @swirtSJW Ready for another look :)

**Comment by swirtSJW** [comment]
Sadly there is a php bug that does not support `a.m.` as an available format. and can only do `am` or `AM`   
https://bugs.php.net/bug.php?id=50084
So we can't fully implement design.va.gov guidance. :(

**Comment by rachel-kauff** [comment]
Alas! But `AM` and `PM` are definitely better than nothing.
