### ISSUE TITLE
DB sanitization script modified to set all users to active

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#4057]
## Acceptance Criteria
- [ ] DB sanitization script is modified to set all user accounts to "Active" so that non-BRD environments identify all users as active

**Comment by swirtSJW** [comment]
If it was done at the sanitization level, then it would impact dev and staging too.   This might not be a problem, but just wanted to raise it that that non-BRD and BRD use the same sanitized DBs.

**Comment by ElijahLynn** [comment]
Done, tested, and merged in https://github.com/department-of-veterans-affairs/devops/issues/8458.
