### ISSUE TITLE
CMS team is notified in Slack if the string of concatenated User Sections exceeds 150 characters

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#4062]
## Problem statement

CMS application sends a string of concatenated User Section TIDs to Google analytics dimension in order to provide means for segmenting users by Section membership.

Google Analytics dimension has a limit of 150 characters.

If we start having users that have membership in more than 50 sections, our dimension limit will be reached and reporting data may be skewed.
_math rationale: section IDs are 2 or 3 digit numbers. A string of fifty 2(xx) or 3(xxx) digit numbers separated by commas will amount to ~150 chars._

This scenario is unlikely but still possible.
Current practice is to give users access to top level sections if they need to access all Sections children. If we keep that practice in tact, our limits should be fine. But we need to have some guardrails that will let us know if this practice changes for any reason.

## User Story

As a CMS admin, I need to know when users are assigned an extraordinary large amount of Sections, so that I can verify if the intent if legitimate.

As a CMS admin, I need to know if concatenated string of User Sections exceeds 150 characters, so that I know it's time to revisit GA data collection strategy.

## Acceptance Criteria
- [ ] Slack message is generated in #cms-team channel if a comma-concatenated string of user section IDs exceeds 150 characters when User Sections form is submitted.

## Implementation notes

We already have Slack messaging capability. See example in \Drupal\va_gov_post_api\EventSubscriber\QueueProcessedEventSubscriber::onQueueProcessed()

**Comment by kevwalsh** [comment]
I have a suggestion: this engineering effort might be better spent providing feedback to users (possibly form validation, possibly some data manipuation on save) who are assigning redundant permissions via workbench access. No user should have a child section and an ancestor section checked.  

That would get to the root of the problem and i think would guarantee that we would never get anywhere close to 50 sections per user. Probably never more than 10.
