### ISSUE TITLE
Apply unique content validation to VAMC and Vet Center content types.

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#4075]
Utilize this module https://www.drupal.org/project/allow_only_one and add a properly configured "allow only one" field to each  of the content types listed. 
**Health services**
- [x] Only one facility health service  (health_care_local_health_service) for each service, per VAMC facility
   -  **field name:** Enforce unique combo(field_enforce_unique_combo ) 
   - **unigue on:** field_regional_health_service and field_facility_location
   -  **Manage form display location:**  Just above "Facility"
![image](https://user-images.githubusercontent.com/5752113/119760450-07bb4b00-be78-11eb-8fb7-32486fb915da.png)

- [x] Only one facility service (vet_center_facility_health_servi) for each service, per Vet Center facility 
   -  **field name:** Enforce unique combo(field_enforce_unique_combo ) 
   - **unigue on:** `field_service_name_and_descripti` and `field_office`
   -  **Manage form display location:**  Just above "Vet Center"
![image](https://user-images.githubusercontent.com/5752113/119760767-97f99000-be78-11eb-8878-4fe7e354da44.png)

- [x] Only one system health service (regional_health_care_service_des) per VAMC system
   -  **field name:** Enforce unique combo(field_enforce_unique_combo 
   - **unigue on:** `field_service_name_and_descripti` and `field_region_page`
   -  **Manage form display location:**  Just above "Service"   
![image](https://user-images.githubusercontent.com/5752113/119761579-0ab73b00-be7a-11eb-8194-094e25872d22.png)

**List pages** 
- [x] Only one Events List (event_listing) per VAMC field_office
   - **field name:** Enforce unique combo(field_enforce_unique_combo ) 
   - **unigue on:** field_office and title (case insensitive)
   - **Manage form display location:**  Just above "Office or health care system"
- [x] Only one health services  List (health_services_listing) per VAMC field_office
   - **field name:** Enforce unique combo(field_enforce_unique_combo ) 
   - **unigue on:** field_office
   - **Manage form display location:**  Just above "Office or health care system"
- [x] Only one Locations List (locations_listing) per VAMC field_office
   - **field name:** Enforce unique combo(field_enforce_unique_combo ) 
   - **unigue on:** field_office
   - **Manage form display location:**  Just above "Related office or health care system"
- [x] Only one news releases (press_releases_listing) List per VAMC field_office
   - **field name:** Enforce unique combo(field_enforce_unique_combo ) 
   - **unigue on:** field_office
   - **Manage form display location:**  Just above "Related office or health care system"
- [x] Only one stories (story_listing) List per VAMC field_office
   - **field name:** Enforce unique combo(field_enforce_unique_combo ) 
   - **unigue on:** field_office
   - **Manage form display location:**  Just above "Office or health care system"
- [x] Only one Operating status page (vamc_operating_status_and_alerts)  per VAMC  
   - **field name:** Enforce unique combo(field_enforce_unique_combo ) 
   - **unigue on:** field_office
   - **Manage form display location:**  Just above "VAMC System"
- [x] Only one Locations List (vet_center_locations_list) per Vet Center field_office
   - **field name:** Enforce unique combo(field_enforce_unique_combo ) 
   - **unigue on:** field_office
   - **Manage form display location:**  Just above "Vet Center"

Others TBD
- [x] Only one Policies page (vamc_system_policies_page)  per Vet Center field_office
   - **field name:** Enforce unique combo(field_enforce_unique_combo ) 
   - **unigue on:** field_office
   - **Manage form display location:**  Just above "Related health care system"  Of if placing it in the sidebar is challenging, I t could be placed just below the title.
   
![image](https://user-images.githubusercontent.com/5752113/119764861-2e7d7f80-be80-11eb-9dac-2ef0a3345a86.png)

**Comment by kevwalsh** [comment]
Jenkins output showing these erorrs http://jenkins.vfs.va.gov/blue/organizations/jenkins/testing%2Fcontent-build-integration-testing/detail/content-build-integration-testing/102/pipeline

![jenkins___testing_content-build-integration-testing___content-build-integration-testing____102.png](https://images.zenhubusercontent.com/5d6e57ad330f64311395f08b/e8047a42-d20f-4930-b0d5-2ab209e12c81)

**Comment by swirtSJW** [comment]
@ethan this is now unblocked because `allow_only_one` is available on D.o as a contrib.
