### ISSUE TITLE
Remove field labels centralized content in VAMC polices page form

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#4077]
**Describe the defect**
1. Field labels for centralized content should not show in a content type using Centralized content. 

**To Reproduce**
1. Go to node/add/vamc_system_policies_page
2. You'll see a few bolded labels like "National bottom of page content"

**Expected behavior**
1. You shouldn't see this field scope/description

**Screenshots**
 ![Create_VAMC_System_Policies_Page___VA_gov_CMS.png](https://images.zenhubusercontent.com/5d6e57ad330f64311395f08b/e7bbbd74-6c30-40bc-8059-26be1ad2c07a)

**Comment by kaise-lafrai** [comment]
Hi @rachel-kauff, has there been a decision made on including or not including field labels?
CC: @kevwalsh

**Comment by kevwalsh** [comment]
@kaise-lafrai yeah i discussed this with her yesterday. i've updated the issue to reflect it. 

Also, i split out https://github.com/department-of-veterans-affairs/va.gov-cms/issues/4138 from this issue.

**Comment by swirtSJW** [comment]
I created an issue to be used for adding this feature to the module.  https://www.drupal.org/project/entity_field_fetch/issues/3196322

**Comment by swirtSJW** [comment]
@kaise-lafrai I think this is the guidance needed https://www.drupal.org/docs/creating-custom-modules/creating-custom-field-types-widgets-and-formatters/create-a-custom-0#s-widget-settings

**Comment by kaise-lafrai** [comment]
@swirtSJW Here is the issue that included the merge request and the patch file in a comment. I was unable to get the config cache tag to clear successfully. I added a comment in the readme that describes how to use the new widget setting,

https://www.drupal.org/project/entity_field_fetch/issues/3196322#comment-13988427

**Comment by swirtSJW** [comment]
@kaise-lafrai  I just put in a PR for this that could use your review. #4224
