### ISSUE TITLE
Remove field_nickname_for_this_facility from VAMC facility and VAMC system content types 

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#4081]
## Description

This field is deprecated on FE and should be removed

## ACs

- [x] It has been deemed "safe" to remove, from GraphQL/transformers
- [ ] Data is deleted
- [ ] Field is deleted

**Comment by ethanteague** [comment]
Three step process, @kevwalsh 
1) Remove from vets-web. Once https://github.com/department-of-veterans-affairs/vets-website/pull/15791 (removes from vets-web) is on prod, then:
2) Create pr to remove fields from cms config. Once step two is merged in:
3) Create pr to remove fields from cms db

**Comment by swirtSJW** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/15791
Was released 2 hours ago on vetsweb.
![image](https://user-images.githubusercontent.com/5752113/105918746-712e6880-6002-11eb-8ab7-17af01e97af9.png)

**Comment by swirtSJW** [comment]
Though something seems off as that was tagged 2 hours ago but the last successful deploy message sent to vfs-engineers was more than 24 hours ago.   
![image](https://user-images.githubusercontent.com/5752113/105919102-04679e00-6003-11eb-8f61-d7a5aeada405.png)

**Comment by swirtSJW** [comment]
Calling this one done as the last PR is approved and just waiting on the previous pr to make it to prod release.
