### ISSUE TITLE
Forms flagged as deleted are not being archived by the nightly forms migration.

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#4083]
**Describe the defect**
When a form is flagged in the nightly forms DB data dump  here https://prod.cms.va.gov/sites/default/files/migrate_source/va_forms_data.csv  the form detail page is supposed to be archived by the migration.   The form `21-0790` is flagged as deleted but the form detail page was never archived.   It does not even show as being updated on the date it was deleted.  
https://prod.cms.va.gov/find-forms/about-form-21-0790

**Facts:** 

1. The flag was never updated in the CMS data.  
2. The deleted date field value does not have the date from the CSV.
3. It was was not updated by the migration since the deletion date in the CSV.

This needs some investigation.  https://dsva.slack.com/archives/CBU0KDSB1/p1611590647138900

**Rule Out** 
- [x] Migration not running nightly:  Last run time and Jenkins confirms it is.
- [x] Editorial mishap : No record of any mistake in the revision history.
- [x] Revision reversion: No record of it.
- [x] Bad archive logic:  Tested it by hand.  Worked as expected, and worked as expected with 12 of the 13 nodes that should be archived.  Also no record the node was updated to reflect the deleted flag or the deleted date, which happens in the migration before the archive logic happens.
- [x] Toggle of deleted flag in the CSV:  This caused no errors and worked as expected.
- [x] What if they put in a deleted flag other than 1 (like a string or some other number)? It still archived as expected.
- [x] What if there was bad data on the row and then fixed it later? It fixed it when the correct format was restored to the current state of the row.
- [x] What if they toggled the deleted on and off a few times? It worked as expected.
- [x] What if the archive logic was flawed? I checked it line by line in x-debug AND that would not explain why the deleted date was never updated.
- [x] Row id (the migration key) changed in the CSV and then changed back.  This would have resulted in duplicate nodes.  There are no duplicates for this form.
- [x] destination id (Node id) and sourceid  (rowid from CSV) mismatch?  No that looks fine.
- [x] Duplicate destination ids? No.
- [x] Duplicate sourceid in map table?  No
- [x] Duplicate rowid in CSV?  No
- [ ] The form deleted date is 2020-10-30  So was there anything on that night or the couple nights after that would have been a failure of the site?  
- [ ] Node save happens first and then the migrate_map is updated. What if the node was saved on one instance and the migration map was updated on the new instance? (catastrophic failure of some sort?)  This would cause the migration to think it had made the update and no other changes to the data row would happen.  The migration map would have an updated date that does not correspond to a node save revision.

**Comment by swirtSJW** [comment]
I just confirmed the migration task is running nightly without errors.  http://jenkins.vfs.va.gov/job/cms/job/cms-daily/

I can find a bunch of forms that were updated on Oct 21 but have not found (by eye) any that had revisions from CMS migrator after Oct 21.  I need to look at this in our DB.

**Comment by swirtSJW** [comment]
There are lots of forms that are archived and were archived by the migration 
![image](https://user-images.githubusercontent.com/5752113/105788659-f22c2800-5f4e-11eb-9eba-60208d1a37bf.png)

**Comment by swirtSJW** [comment]
I did an audit comparing the forms DB to the CMS  
Of the 13 forms in in the Forms DB that are flagged as deleted, 12 of them show correctly as "archived" in the CMS.  The form you identified, 21-0790 is the only one that is not correct.

I believe this is a one off event.   It still needs investigating but does not seem like  an ongoing issue.

**Comment by swirtSJW** [comment]
Digging:
On first run of migrate status I see this
![image](https://user-images.githubusercontent.com/5752113/107818907-4a806980-6d46-11eb-8074-e63a069078ef.png)

The -4 unprocessed means that 4 rows in the csv no longer exist that used to exist.  This may have happened before asked the forms db team to stop deleting and to just flag them as deleted.

**Comment by swirtSJW** [comment]
Digging: Ruled out migration not running.  It is running.
![image](https://user-images.githubusercontent.com/5752113/107828762-840da080-6d57-11eb-9e18-0b71133c6d54.png)

**Comment by swirtSJW** [comment]
Digging: I pulled the CSV local and edited the row to set the deleted flag to 0.  It updated the node appropriately when the migration ran.

**Comment by swirtSJW** [comment]
I tested by toggling the value from deleted to not deleted and back repeatedly.  I could not get it to fail.
![image](https://user-images.githubusercontent.com/5752113/107841260-78d26900-6d87-11eb-9bd9-68a6b23cc688.png)

I did add some logic to account for a possible case where the FormsDB could flag it as deleted, then changed their mind and removed the flag.  Even this would not have caused the bug, but it was a possibility I explored.

**Comment by swirtSJW** [comment]
Possible failures I tested:
1. What if they put in a deleted flag other than 1 (like a string or some other number)?   It still archived as expected.
2. What if there was bad data on the row and then fixed it later?  It fixed it when the correct format was restored.
3. What if they toggled the deleted on and off a few times.   It worked as expected.
4. What if the archive logic was flawed.  I checked it line by line in x-debug AND that would not explain why the deleted date was never updated.

**Comment by swirtSJW** [comment]
I checked the migrate map table to see if there was some disconnect.  It checks out fine with the destination id (the node id) and the rowid from the CSV matching
![image](https://user-images.githubusercontent.com/5752113/107842187-4e84a980-6d8f-11eb-8c8b-58df4b609e00.png)

**Comment by swirtSJW** [comment]
Unfortunately my last remaining test to rule out I can not do.  The timing of the update of the migration map can not be compared to the node revision history because migrate module is not tracking the updated times.  They are just all 0
![image](https://user-images.githubusercontent.com/5752113/107843874-b988ad00-6d9c-11eb-8e72-4fbdebd25961.png)

**Comment by swirtSJW** [comment]
The missing migration last updated dates turns out to be a Drupal core bug.   I just put in an issue and provided a core patch.
https://www.drupal.org/project/drupal/issues/3198608

It is not essential for the work on this ticket, but it would be easier to  debug this particular issue.

**Comment by MarciMcGuireGCIO** [comment]
Hi @swirtSJW; checking on open issues on our board.  Are there any updates on this? Thanks!

**Comment by swirtSJW** [comment]
@MarciMcGuireGCIO   From all my testing of possible causes, the system checks out to be working as it should be.    There is no smoking gun but  I have added a method to properly track updates in the migrate map so we could rule in or out the last two possibilities if it ever happens again.  I am considering this closed.

**Comment by MarciMcGuireGCIO** [comment]
Thank you, @swirtSJW!

**Comment by jenniferlee-dsva** [comment]
I am genuinely impressed - just saying. Thank you @MarciMcGuireGCIO and @swirtSJW .
