### ISSUE TITLE
Related information field should be required on Standalone Q&A nodes

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-cms#4090]
**Describe the defect**
When creating a Q&A node and checking the 'Standalone' box, the Related Information field is not required.

**To Reproduce**
1. Go to /node/add/q_a
2. Check `Enable standalone Resources and support page for this Q&A.`
3. Attempt to save without adding a link to the Related Information field

**Expected behavior**

- [x] Field is required when `Enable standalone Resources and support page for this Q&A.` is checked
- [x] A Q&A node can be saved without the field having content when `Enable standalone Resources and support page for this Q&A.` is not checked
- [x] The form widget UI matches other R&S content types (a blank link teaser form should be present)

**Additional context**
This was reported here: https://dsva.slack.com/archives/CDHBKAL9W/p1611675997018300

**Comment by jenniferlee-dsva** [comment]
Confirming above description is accurate.
