### ISSUE TITLE
Create friendly error page when Front End WEB build not started or in progress instead of 403 access denied

### ISSUE THREAD

**Issue by ElijahLynn** [department-of-veterans-affairs/va.gov-cms#4095]
If a WEB build does not exist, this is what a user sees:
![image](https://user-images.githubusercontent.com/1504756/105953723-81f1d500-6028-11eb-9f0c-18c10c338ee3.png)

We need to give more information here.

**Comment by ElijahLynn** [comment]
PR #4096 now shows this message if no build exists yet. 

![image](https://user-images.githubusercontent.com/1504756/105954946-57a11700-602a-11eb-824b-f4b6787ccec1.png)

A new base image will need to built as this runs the Tugboat init stage that copies this vhost config over.

**Comment by rachel-kauff** [comment]
@ElijahLynn [Per our convo in Slack](https://dsva.slack.com/archives/CT4GZBM8F/p1611730915332700) here's the prototypes:
- [Figma](https://www.figma.com/file/6AWSPB0ijeoHQFToF2qsRo/R's-word-playground?node-id=0%3A1)
- Screenshot 
![Screen Shot 2021-01-27 at 2 33 12 PM](https://user-images.githubusercontent.com/41017988/106071566-726f9c00-60bb-11eb-8179-dd2008b651c0.png)

**Comment by rachel-kauff** [comment]
PS. Figma prototype has a few URLs you'll need, plus the specs for the spacing, etc. LMK if you still have trouble loading.

**Comment by ElijahLynn** [comment]
Thanks, I am into Figma now, got everything including links!

**Comment by ElijahLynn** [comment]
I have this your mockup implemented at https://web-qxmwklvc2bmgnkla4x4flu1kpcxoqbw3.ci.cms.va.gov/ and have attached a gif too. I made it a bit responsive too, and used the VA.gov blue color. 

![web-build-403-responsive-error-document](https://user-images.githubusercontent.com/1504756/106104357-30fce200-60f7-11eb-867b-dbae87057aba.gif)

**Comment by rachel-kauff** [comment]
@ElijahLynn Sweet. Thanks for the gif demo. Looks really good. Is it possible for me to send you an updated version of the image file? I'd like to adjust the colors slightly to look better with that blue.

**Comment by rachel-kauff** [comment]
@ElijahLynn 
![Uploading 403-not-found copy.png…]()

**Comment by ElijahLynn** [comment]
> Is it possible for me to send you an updated version of the image file?

Sure thing!

**Comment by rachel-kauff** [comment]
![Uploading 403-not-found copy.png…]()

**Comment by acrollet** [comment]
@rachel-kauff the upload didn't seem to work :-\

**Comment by rachel-kauff** [comment]
![Uploading 403-not-found copy.png…]()

**Comment by rachel-kauff** [comment]
^^^ Definition of crazy is...
