### ISSUE TITLE
Some redirects are apparently broken.

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-cms#4103]
## Description
While working on #3971 , I became aware of some broken redirects (when trying to test against them for QA :weary:).  They seem to be broken because the source URI has a trailing slash, which doesn't seem to work. 

 There are about 220, I think:

## To Reproduce
1. Run the following SQL query: `SELECT * FROM redirect WHERE redirect_source__path LIKE '%/';`

Now, there're a few things we might do to try to fix this:
- [ ] Better documentation for users so they don't create redirects with trailing slashes
- [ ] Validation for that field to ensure no trailing slashes are added
- [ ] Manually fixing the existing problematic redirects

These probably need to be discussed though, so I'm just going to nope out of here now.

## Acceptance Criteria
- [ ] Redirects with trailing slashes are fixed to remove the trailing slashes

**Comment by acrollet** [comment]
We just checked current data, and there are still 220 redirects like this. This suggests that this is not an on-going issue, and we can simply fix the bad data and move on.

**Comment by ndouglas** [comment]
Just need to run this query:

```
MariaDB [drupal8]> SELECT * FROM redirect WHERE redirect_source__path LIKE '%/';
...
220 rows in set (0.00 sec)

MariaDB [drupal8]> UPDATE redirect SET redirect_source__path = TRIM(TRAILING '/' FROM redirect_source__path);
Query OK, 220 rows affected (0.07 sec)
Rows matched: 16438  Changed: 220  Warnings: 0

MariaDB [drupal8]> SELECT * FROM redirect WHERE redirect_source__path LIKE '%/';
Empty set (0.03 sec)
```

I'm going to go ahead and open a PR for this, just because I'm hazy about how this data might be used in content-build and don't wanna #DoItLive and then break content builds.
