### ISSUE TITLE
Update Tugboat to use CMS Export for content release

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#4107]
## Acceptance Criteria
- [ ] Tugboat content release process uses CMS Export Build [v1] to build full site preview

## Implementation notes

- set env vars in settings.tugboat.php - `use_cms_export`

**Comment by indytechcook** [comment]
Composer command to run: `va:web:build:export:content`

**Comment by indytechcook** [comment]
When the `use_cms_export` is set to TRUE, the release content button in the UI runs the full CMS export first.

**Comment by oksana-c** [comment]
closing due to the pivot toward GraphQL Performance and Scalability effort.
