### ISSUE TITLE
Workbench access (Sections) training, documentation, and purging of redundant Section access

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#4115]
## Problem statements

Our user administration service needs a coherent approach to providing access by role and section. 

In the short term, our help desk team needs to understand the way this system works, so that they can respond to access requests, and properly dole out Section access. 

Content strategists need to understand the way that CMS structures governance in the CMS

[this could be split into a separate issue, but it might be good to include this AC as a validation step for the knowledge sharing]:  There is redundant Section access. Content admins have been given Section access that they don't need (users with this role just bypass these access rules). Some users have been given access to parent and child sections, making it harder to manage.  

## AC
- [x] We have documentation on how Sections has been implemented on VA.gov CMS
- [x] User admins and content strategists have an understanding of how content governance is administered.
- [x] Product teams have access to documentation to explain the Sections hierarchy, and it relates to various products. 
- [x] Redundant section access has been removed from user accounts. 
- [ ] Candidate: We have a created a plan for how to routinely purge Sections data of redundant data. (could be manual or potentially automated)

## WIP

https://docs.google.com/document/d/1rd32Hy92Mm9PeEdikTjJhvbHjEJkJ3OAJXpeTcXwwIs/edit 

## Not included
- #1731 (show users on each section page) ... this has been subsumed under VAMC dashboard, but we may want to proceed with this for other Sections that are not candidates for VAMC dashboard treatment.

**Comment by cmaeng** [comment]
Let's bring @xiongjaneg into this.

**Comment by stefaniefgray** [comment]
Love ya Kev ❤️ 

@TroyA6 and I are good to go on this ticket and Section assignments in the CMS, and it can be closed
