### ISSUE TITLE
Table Field module incorrectly saves the values

### ISSUE THREAD

**Issue by indytechcook** [department-of-veterans-affairs/va.gov-cms#4117]
**Describe the defect**
When the table field saves it's data, it is injecting the `caption` field into the `values` field.  This causes the `values` field to be serialized as an object instead of an array.  This causes the output of the JSON created by CMS export to be inconsistent depending on if the caption exists.

With the correct data structure
```
    "field_facility_service_hours": [
        {
           "caption": "caption",
            "value": [
                [
                    "Mon",
                    ""
                ],
                [
                    "Tue",
                    ""
                ],
```

With incorrect data structure:
```
    "field_facility_service_hours": [
        {
            "value": {
                "0": [
                    "Mon",
                    "8:00 a.m. to 4:30 p.m. ET"
                ],
                "caption": "",
                "1": [
                    "Tue",
                    "8:00 a.m. to 4:30 p.m. ET"
                ],
```

The fix requires a patch to the table field module to the file `Drupal\tablefield\Plugin\Field\FieldType\TablefieldItem`

Line 182 inside of the `setValue` method remove the following code:

```
    if (isset($values['caption'])) {
      $values['value']['caption'] = $values['caption'];
    }
```

Related slack discussions:
* https://dsva.slack.com/archives/C01512KN35G/p1611760815169800

AC:
* The caption does not save in the `values` field in the field table
* The default value has the caption in the correct place
* The correct caption shows up on the view and edit pages of the node
* All of the current table fields have fixed content

**Comment by ndouglas** [comment]
12464, 12502, 12571 are the nids of the affected nodes; these need to be resaved before the issue should be considered solved.  Note that the module is broken and captions are not being set correctly and thus can't be retrieved, but as far as I can tell none of these have set captions anyway.
