### ISSUE TITLE
/node/UUID controller 

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#4120]
## Acceptance Criteria
- [ ] /node/<UUID> controller - shows the node based on UUID. Acts the same as /node/id.

**Comment by acrollet** [comment]
This was related to transformers work.

**Comment by timcosgrove** [comment]
See https://www.drupal.org/project/drupal/issues/2353611#comment-13310783 for a possible approach

**Comment by timcosgrove** [comment]
This is no longer needed.
