### ISSUE TITLE
Improve tugboat content release log visibility

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-cms#4126]
## User Story or Problem Statement

As a CMS user or developer, I need to view real-time logs of content release builds on demo environments in order to know the build status and ease debugging of build issues.

## Acceptance Criteria
- [ ] content release logs are viewable in real time on the tugboat log page for that environment
- [ ] The 'Logs' column in the release status table links to the tugboat log page for that environment

## Implementation steps
- use monolog module and send advancedqueue logger channel to `php://stdout`

**Comment by TheBoatyMcBoatFace** [comment]
@olivereri & @ElijahLynn is this an issue/can Datadog handle?
