### ISSUE TITLE
Profile single page preview GraphQL request

### ISSUE THREAD

**Issue by indytechcook** [department-of-veterans-affairs/va.gov-cms#4127]
## Description

The preview page, e.g. http://preview-staging.vfs.va.gov/?nodeid=2362, is taking over a minute to process page and it can timeout. The page and graphql request should be profiled.

## Acceptance Criteria
- [ ] we've identified and documented bottlenecks in single page preview performance
- [ ] next steps backlog exists

**Comment by indytechcook** [comment]
Looking at the the converstaion, the issue might be with feature flags API endpoint of `/flags_list`

**Comment by indytechcook** [comment]
https://dsva.slack.com/archives/CBU0KDSB1/p1611883746472600?thread_ts=1611857007.368600&cid=CBU0KDSB1

**Comment by indytechcook** [comment]
Quick look at the endpoint, we could use `CacheableJsonResponse` instead of `JsonResponse` for the response.

**Comment by ElijahLynn** [comment]
Linked related issue > https://github.com/department-of-veterans-affairs/va.gov-team/issues/19787

**Comment by acrollet** [comment]
We have just discussed pausing this work in favor of pursuing AP (Accelerated Publishing) work that may resolve the preview concern.
