### ISSUE TITLE
Update help text for "Link to file or video" paragraph

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#4133]
## Background

the need to improve contextual guidance for "Link to file or video" paragraph was surfaced by Jen Strickland

## Description

-  Microcopy for linked text field label and help text
   - Mockup: ![Screen Shot 2021-01-28 at 4.02.04 PM.png](https://images.zenhubusercontent.com/5e399cf5446c5b4ca0e31e42/49ec3d07-95f3-49e4-8d43-0e1addc48e14)
- Paragraphs browser thumbnail image file
   - SVG: ![Paragraphs-browser-thumbnail.svg](https://images.zenhubusercontent.com/5e399cf5446c5b4ca0e31e42/18e3d99e-48a9-46ab-85a9-74c86d3cc136)
   - PNG: ![Paragraphs-browser-thumbnail@2x.png](https://images.zenhubusercontent.com/5e399cf5446c5b4ca0e31e42/97d43066-13f0-47fd-bf8e-74ec29e5f57c)
- Microcopy for paragraphs browser - label and description
    - Mockup: ![Screen Shot 2021-01-28 at 4.05.46 PM.png](https://images.zenhubusercontent.com/5e399cf5446c5b4ca0e31e42/100eef1e-8a9c-43d2-931f-55d07185ec8e)
**Artifacts**
- [Prototype file for MVP deliverables](https://www.figma.com/file/6AWSPB0ijeoHQFToF2qsRo/Rachel-Sprint-24?node-id=42%3A2) (Figma)
- [Prototype file with post-MVP proposals](https://balsamiq.cloud/s21kwcm/py46j7t/r9034) (Balsamiq)

## Acceptance Criteria
- [ ] paragraph title, thumbnail and description are updated per spec above
- [ ] linked text field description in the paragraph is updated per spec bove

**Comment by daddison48** [comment]
@rachel-kauff please review
