### ISSUE TITLE
Pager Component for Outreach Event Page 

### ISSUE THREAD

**Issue by VanessaLuxen** [department-of-veterans-affairs/va.gov-cms#4134]
Request came into VA CMS Support email from Jean.Orzechowicz@va.gov on 1-28-2021 at 6:57pm. Her request for a pager component for the outreach even page is below. Sending this ticket to the FE teams for triage.

“As we continue to grow the Outreach Events page, I’m wondering if it is possible to change the number of pages shown at the bottom of the page. It would be fantastic to see the total number of pages of events no matter which page someone is on.  

Requested state: Show 3 pages PLUS the total number of pages
Example: 1 2 3….15 
This way people will get an idea of how many pages of information will be available as they start clicking through.”

**Comment by VanessaLuxen** [comment]
Issue is in Jira here: https://va-gov.atlassian.net/jira/servicedesk/projects/VAHELP/queues/custom/11/VAHELP-354

**Comment by brianalloyd** [comment]
Thanks @VanessaLuxen PW team will take this on for action.  Including our [Slack Convo](https://dsva.slack.com/archives/C01H29ERVJ7/p1611933642007400) on this ticket for reference.

**Comment by kevwalsh** [comment]
@brianalloyd can you transfer this issue to va.gov-team, or close it?

**Comment by brianalloyd** [comment]
Going to close, couldn't figure out how to transfer in support.
