### ISSUE TITLE
 Developer data should not show on proofing page. 

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#4138]
**Describe the defect**
 Developer data should not show on proofing page. 

**To Reproduce**
1. Create a VAMC System Policies Page 
2. See the `Source:node 15588 paragraph b02cd373-7926-4328-9c9f-a26f4d0ae87c`  data for devs

**Expected behavior**
Dev data should only be shown upon inspection of source code. 

## ACs

- [ ] paragraph data should not be visible on VAMC policies page. (this will require a patch to Entity field fetch module to add a class that will allow us to hide this content in CSS)
UPDATE: this has already been fixed in contrib, https://www.drupal.org/project/entity_field_fetch/issues/3195412 we just need to update to use the latest version of that module.  (let Swirt know when you are ready to do this and he will tag a new release on d.o so we don't have to use dev version.

## Screenshots 

![Policies___Veterans_Affairs.png](https://images.zenhubusercontent.com/5d6e57ad330f64311395f08b/a435b9bc-d0d1-4d63-8cf8-b8a2608cd37b)

**Comment by swirtSJW** [comment]
@kaise-lafrai  now that we have a pattern for settings on the form widget it might be best to handle this there instead just a css fix.
https://www.drupal.org/project/entity_field_fetch/issues/3194277
It would bump the estimate from a 2 to a 5.... but it would be the right way to handle it.

@kevwalsh Are you ok with handling that way?

**Comment by swirtSJW** [comment]
I am working on this one.

**Comment by swirtSJW** [comment]
I resolved this with an upstream issue.  https://www.drupal.org/project/entity_field_fetch/issues/3194277   When we bring in the new version as part of #4017, it resolve this.
