### ISSUE TITLE
Identify opportunities and build roadmap for improved IA governance in VAMC system

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#4144]
See #2427 for more background

ACs
- [ ] Opportunities have been circulated to @mnorthuis and @davidconlon for initial review
- [ ] CMS team has created a Q1 roadmap to implement 

## Problem statement

*   There isn't much IA/menu governance for the VAMC System product. It’s too easy to make major changes to the menu structure and IA of VAMC system product 
*   It’s too easy to make unintended IA errors, even for well-trained CMS users (like, adding a root Top task page that the same level as the health care system)
*   The FE menu graphql and liquid templates are highly reliant on a stable menu structure, and choke when menu items are incorrect. This reveals content bugs, but those content bugs shouldn’t exist in the first place. 

The following artifacts were considered.

*   the [Moqup](https://app.moqups.com/Rnc4BDEKrA/view/page/a9e1a59e9) containing the original IA design done for Pittsburgh 
*   existing menu structure from [VA Pittsburgh](http://prod.cms.va.gov/admin/structure/menu/manage/pittsburgh-health-care?destination=/admin/structure/menu), [Erie](http://prod.cms.va.gov/admin/structure/menu/manage/va-erie-health-care), [Coatesville](http://prod.cms.va.gov/admin/structure/menu/manage/va-coatesville-health-care?), Eastern Colorado, Eastern Oklahoma.
*   [An analysis of IA design combined with CMS configuration](https://github.com/department-of-veterans-affairs/va.gov-cms/files/5871323/VAMC.IA.governance.analysis.xlsx) (XLSX, but the source of truth for this is a [google doc](https://docs.google.com/spreadsheets/d/1n6h0NUJmQcFsc90dy14FQrX_0wVPX0AM7NlZoHSFKaA/edit?usp=sharing))
*   [Issues in va.gov-team tagged with “ia” and “vsa-facilities”](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/board?labels=ia,vsa-facilities&repos=133843125) (link to Zenhub)
* **Added Feb 1** [Pittsburgh IA](https://github.com/department-of-veterans-affairs/va.gov-team/issues/9334) and [Erie IA](https://app.zenhub.com/workspaces/vsp---product-support-5f85b91c14d8df0018fac414/issues/department-of-veterans-affairs/va.gov-team/10482#issuecomment-652527300) issues identified by @mnorthuis July 2020.

What was not considered so far

*   Insight from VAMC upgrade team about patterns or intentional IA drift that has arisen, such as where to put DAV vans (that may come in first or second week of February)

Design goals
* IA is consistent across VAMCs _to a degree_, both for Veterans but also for VA and managers of the product. 
* Users of the VAMC system product (CMS editors) understand what parts of the menu structure they can manipulate, and what parts are locked down
  * For example: Editors understand how to add new discretionary Detail pages to the IA, and how to reorganize them.
* Agile: VAMC system product managers can iterate on IA, without egregious technical debt to deal with

### Opportunity 1a: Lock down menu editing for all VAMC content types other than Detail pages

**Shorter term**

The bet: non-Content admin editors of VAMC system content (eg PAOs, etc) should only be able to choose certain parents for “Detail Pages”, but no other content types. 

Editors in the field _do not need to edit menu items for any other content types_.

The CMS could lock down editing permissions and IA for all VAMC-enabled content types other than Detail page. Only users with the Content Admin role would be able to manipulate menu items (and perform “scaffolding” tasks, like setting up a new VAMC). 

### Opportunity 1b: A tool to let content admins lock down _certain_ Detail Page node menu items

**Short-to-medium term**

This is an optional follow-up to Opportunity 1a.

A large portion of detail pages could have menu items locked down, such as Facility map pages, or existing Top task pages.  

Currently, we have no way of identifying these using anything in the content model. CMS team could devise a means to lock down menu items on a node-by-node or other (path-based?) basis.

### Opportunity 1c: Convert as many detail pages to content types, and lock their position

**Medium-to-long term**

Detail pages are "junk drawer" of the CMS. Much of the content contained on Detail pages offer opportunities for hardening in the content model, and by extension (using 1a above), hardening of the IA governance. 

These pages include
*   Top task pages: Policies (currently being "hardened" in the content model), Contact us, Billing and insurance, Make an appointment, Pharmacy, Register for care. 
*   Campus/facility maps
*   Care coordinator pages 
*   Standard "About" section pages (About us, Mission and vision, history, Work with us, Jobs and careers, Internships and fellowships, Volunteer or donate, etc)

*Added Feb 1* How might we help solve for IA drift like that found in https://github.com/department-of-veterans-affairs/va.gov-team/issues/9334?

### Opportunity 2a: Provide an editorial experience for adding and editing menu items on discretionary detail pages "on the fly"

Currently in the CMS UI, editors can add _any parent_ as a menu item to _any page_, as long as they have access to edit that menu. (Each VAMC editor has access to their own VAMC menu, but not others). 

Assuming opportunity 1a is solved, editors would only be able to create and edit menu items for Detail pages (and possibly only _certain_ detail pages, given 1b).

How might we provide these constraints within the content adding/editing experience? 

### Opportunity 2b: Provide an editorial experience for managing each VAMC menu system 

Occasionally, an editor may want to move a few menu items around at once, using the drag and drop tools found on a menu editing page like [the one for VA Erie health care](https://prod.cms.va.gov/admin/structure/menu/manage/va-erie-health-care) 

How might we provide an editorial experience on the menu editing page that both builds in those constraints, but also explains it?  

### Opportunity 2c: Change management and training

For 2a and 2b, we'll want to update existing training materials as well as manage these changes for the existing editor based. 

## Opportunity set 3: Would involve some FE refactoring

These two items are related and probably best accomplished together, but could also happen independently. 

Unclear if this would require any Transformer work, given that menus and breadcrumbs are graphql-only. 

### 3a. Switch to path-based breadcrumbs, instead of one based on CMS menu item hierarchy. 

The VAMC system MVP was built with menu-based breadcrumbs, to allow for some flexibility of creating breadcrumbs that do not match the path structure--flexibility which has never been needed. 

This would be a good time to switch to path-based breadcrumbs, because we could simplify the menu and reduce the risk of build-breaking errors in the Front end, like "ineligible breadcrumbs", which has shown up a few times when bulk publishing VISN 4 content containing bugs that originate in the content layer.

### 3b. Remove the health care system from the menu in Drupal, and remove the dependency on it within the FE build

Each VA health care system has a single parent menu item, with three children (Locations and services, News and Events, and About), plus a number of "root" pages like the top task pages

For example, in VA Pittsburgh health care the top two levels of the menu look like this:  

* VA Pittsburgh health care 
  * Locations and services (_left nav divider_)
  * News and Events (_left nav divider_)
  * About VA Pittsburgh (_left nav divider_)
  * Billing and insurance  _(root page)_
  * Make an appointment  _(root page)_
  * Pharmacy _(root page)_
  * Register for care _(root page)_
  * Policies	_(root page)_
  * Contact us _(root page)_

Those parent menu items don't actually show in the left nav, and as of summer 2020, health care system pages have started acting like home pages in the VAMC system product breadcrumbs. (eg [VA Pittsburgh health care](#) > [Locations](#) > [Pittsburgh VA Medical Center-University Drive](#)

Occasionally, children are incorrectly/accidently added to the parent "VA Pittsburgh health care" (including by Content admins). 

If we switch to path-based breadcrumbs, the homepage menu items in Drupal become even more redundant, and it provides additional incentive to remove this item, because the risk of editor-introduced bugs goes down.

**Comment by kevwalsh** [comment]
Meeting scheduled for 4pm ET Tuesday Feb 2 with @mnorthuis @davidconlon and @mmiddaugh

**Comment by ethanteague** [comment]
@kevwalsh 
3a is doable by us, but will be really sticky / fiddly. 
3b will require a lot of support from Gibran - will require his react menu logic to be refactored.

Transformer work won't be required for 3a. But for 3b, it seems like transformer work would be required (change to content model).

**Comment by kevwalsh** [comment]
For Opportunity set 2, one less expensive approach might be to show menu items that are not eligible as parents, simply by adding `disabled` to the `<option>`  

i mocked it up with my inspector, here. 

![Create_Detail_Page___VA_gov_CMS](https://user-images.githubusercontent.com/643678/106502480-69ebdc80-6492-11eb-930f-6dab308b7980.png)

**Comment by kevwalsh** [comment]
Next up: #4311 (spike to implement 1a through 1c)
