### ISSUE TITLE
Document Policies content model for FE devs, and abstract content model for Centralized content

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#4145]
ACs
- [x] Facilities FE devs have documentation for building the VAMC system policies page, using node 16141 (which has one empty "local" field.
- [x] Ask @mmiddaugh for an issue ID on va.gov-team for where to put this documentation (this is on the agenda for February 3)
- [x] CMS team has documentation for how to build more content types with Centralized content in va.gov-cms repo.

**Comment by swirtSJW** [comment]
This was discussed here https://dsva.slack.com/archives/C0FQSS30V/p1614621167177000

**Comment by kevwalsh** [comment]
More content model documentation added here https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1614800814809/825fd5a0b0360ff42c2470e128d8f35af42579ee
