### ISSUE TITLE
Sprint 25 tier 2 helpdesk support

### ISSUE THREAD

**Issue by daddison48** [department-of-veterans-affairs/va.gov-cms#4148]
Sprint 25 Tier 2 Engineering Support

**Comment by acrollet** [comment]
| Date | Issue | Resolution | Time Spent |
| -- | -- | -- | -- |

**Comment by swirtSJW** [comment]
| Date | Issue | Resolution | Time Spent |
| 1/1| bad help link on training env | Trianing env is outdated, needs updating | :30 |

**Comment by swirtSJW** [comment]
Looks like about 10:45  spent in total.
