### ISSUE TITLE
UX iteration on 403 error page for FE build in Tugboat

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#4150]
## Background

We have developed a friendly 403 page that directs users to (1) Check status of your build or (2) Help desk if the FE has not been built yet, is in progress, etc.
![web-build-403-responsive-error-document](https://user-images.githubusercontent.com/1504756/106104357-30fce200-60f7-11eb-867b-dbae87057aba.gif)

At the end of the Sprint 24, the team has made a technical decision not to build the front-end automatically when environment is cloned/created/refreshed.
This presents new context for the 403 page content, where we may need to amplify the call to action "Check status of your build" in order to direct the user to Release Content page immediately as they see the 403 page.

The goal is to help the user understand that the build may need to be triggered manually for a new environment.

Design iteration on 403 page may include converting "Check status of your build" link into a button/CTA with additional context around it.

## Acceptance Criteria
- [ ] UX guidance/design docs are created to better support updated technical context
- [ ] follow-on issues for implementation have been created

**Comment by jkalexander7** [comment]
Closed, Next Build System work will address.
