### ISSUE TITLE
Establish/Research Current Preview Server Ownership

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#4152]
## Acceptance criteria

- [x] the owner of the Preview Server feature is identified and documented
- [x] the owner of the Single Page Preview feature is identified and documented

## Preview Server / Single Page Preview Owner 

[VSA Public Websites](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/4152#issuecomment-804184179)

**Comment by ElijahLynn** [comment]
Last I know is that FE Tools owns it. Jeff Balboni and @ncksllvn were the ones who built it while on FE Tools team and ownership has not changed since then.

**Comment by ncksllvn** [comment]
At the time I was actually on the now-gone vets.gov team. I haven't been on the FE Tools team. 

I think most folks say my current team, VSA Public Websites owns it. This is fine with us but we do maintain a very large technical landscape so it can sometimes be difficult for us to prioritize effectively.

**Comment by ElijahLynn** [comment]
Thank you @ncksllvn!!! That makes so much more sense now!

**Comment by mchelen-gov** [comment]
hey @jefflbrauer this was tagged for PO review and i was hoping to see more clarity & documentation from CMS perspective. was this ticket AC clear enough or do we need to create a followup?

**Comment by jefflbrauer** [comment]
@mchelen-gov I would think if there was an overall architecture diagram of our build and deploy process that included ownership labels, preview would be one aspect of it. Has OCTO-DE established the source of truth document we will use moving forward for this purpose?  If so, we can create a follow up ticket to add to it the information from the note from Nick above.

**Comment by mchelen-gov** [comment]
@jefflbrauer I agree about build arch & docs, however preview server feature is separate from build process.

**Comment by jefflbrauer** [comment]
OK. I am going to create a new ticket that specifies the ACs as requiring documentation for the preview feature.

**Comment by jefflbrauer** [comment]
Also - here is the documentation for tugboat (preview server)
https://github.com/department-of-veterans-affairs/va.gov-cms-test/blob/a14116c6ff695f59a21fe5f8259c37761e762744/READMES/tugboat.md

**Comment by mchelen-gov** [comment]
followup ticket: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/4864
