### ISSUE TITLE
Implement environment name display

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-cms#4160]
## Description

This is a follow-on for the implementation of #4159

## Acceptance Criteria
- [x] 👀 **Needs design review** because the work involves changes to labels or other design elements 
- [ ] Users on tugboat environments can easily view the human-readable name of the environment they are using

**Comment by ElijahLynn** [comment]
We also discussed that if we can get #4161 implemented for alias generation then we might not need this feature, as the current demo environments just have the URL identifier.
