### ISSUE TITLE
Update demo environment creation documentation to include creating and disseminating human-friendly URLs

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-cms#4161]
## Description

User Story: As a CMS demo environment user, I wish to receive human-friendly URLs for demo environments created for me, in order to help me distinguish different demo environments from one another.

User Story: As a CMS tier 2 support engineer, I wish to see human-friendly URLs for demo environments in screenshots/support requests, in order to help me distinguish different demo environments from one another.

To support these stories, helpdesk documentation and practices should be updated to document the capability for disseminating user-friendly URLs, and ensure that these URLs are shared with end users of demo environments.

For example, when creating the 'Wilmington health care' demo environment, these are the default URLs that tugboat provides:

- `https://cms-kewq6ooqnvg8hzjyzc1luyb4wm8bncmw.demo.cms.va.gov/`
- `https://web-kewq6ooqnvg8hzjyzc1luyb4wm8bncmw.demo.cms.va.gov/`

The format is `{preview_type}-{environment_identifier}.demo.cms.va.gov`. Any alphanumeric characters can be placed between hyphens separating the `preview_type` and `environment_identifier`. So, for example, these URLs could be modified as follows:

- `https://cms-wilmington-kewq6ooqnvg8hzjyzc1luyb4wm8bncmw.demo.cms.va.gov/`
- `https://web-wilmington-kewq6ooqnvg8hzjyzc1luyb4wm8bncmw.demo.cms.va.gov/`

These are the URLs that should be shared with users.

## Acceptance Criteria
- [x] Helpdesk documentation and procedures have been updated

**Comment by ElijahLynn** [comment]
cc @q0rban and @bchavet.

**Comment by oksana-c** [comment]
@oksana-c will document the pattern in tugboat readme.

for broader audience, we'll wait until Tugboat team reviews requested alias enhancement, then socialize with VFS teams that use demo envs.

**Comment by oksana-c** [comment]
documentation added here https://github.com/department-of-veterans-affairs/va.gov-cms/blob/master/READMES/tugboat.md#human-friendly-urls-for-cms-demo-preview-environments
