### ISSUE TITLE
Establish a Figma prototype of most common application pages

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#4163]
As a CMS Designer, I need to have base prototypes of most common pages, so that I am efficient in all tasks that require those.

## Acceptance Criteria
- [ ] Figma prototype that includes structural page elements (navigation, etc):
    - [ ] a node view page
    - [ ] a node edit page
    - [ ] content listing
    - [ ] one of the configuration pages, such as edit content type's form display - https://prod.cms.va.gov/admin/structure/types/manage/page/form-display
    - [ ] user profile page

**Comment by jordanamello** [comment]
@gujacq [link to the Figma file](https://www.figma.com/file/BkwnUQMZ6gzXOoF9c09Tqp/CMS-skeleton?node-id=0%3A1)

**Comment by jefflbrauer** [comment]
Does it make sense to do this before design system is in place?

**Comment by oksana-c** [comment]
@jordanamello and @rachel-kauff are already using some of these prototype templates.

@rachel-kauff and @gujacq please comment on @jefflbrauer's question. thank you

**Comment by cmaeng** [comment]
moving back to the backlog to reprioritize against other initiatives.

**Comment by kevwalsh** [comment]
This has been completed via other design issues.
