### ISSUE TITLE
Monitor HTTP request times

### ISSUE THREAD

**Issue by ElijahLynn** [department-of-veterans-affairs/va.gov-cms#4169]
## Description

As a devops engineer, in order to have actionable data when making infrastructure scaling decisions and troubleshooting performance issues, I need to be able to view the amount of time it takes Apache/PHP to serve HTTP requests.

## Acceptance criteria

- [x] HTTP request time (in ms) is available in Apache logs
- [x] Insights dashboard showing HTTP request times is available
- [x] Insights dashboard showing Concurrent HTTP requests (expressed as requests/second) is available
- [x] Bonus: Create custom metric and make Grafana panel displaying HTTP request times

**Comment by olivereri** [comment]
Just for clarity REQUEST_TIME is a PHP $_SERVER array element that contains the value of the request timestamp, equivalent to mod_log_configs  %t  %{format}t that can be used in Apache logs if the log format is customised.

Is the goal only to include the timestamp of when the request was received/started and have it appear in the log? Or is the goal to try and track the time it took to serve a request with %T or %{unit}T log format?

I'm guessing it's the latter to query logs with Cloud Watch Insights for requests that take over X milliseconds.

**Comment by olivereri** [comment]
The geerlingguy.apache role isn't used to create the vhost files for any CMS environment.

meta/main.yml of the CMS build config uses `apache_create_vhosts: false` with the comment `This is laid down in the deploy config because we lay down the private key there too`

Adding a custom log setup for Apache will be done at build time in vhosts.conf.

**Comment by olivereri** [comment]
This should do the trick. The format comes from `httpd.conf` combined format with ``

> CustomLog "/var/log/httpd/access_log" "%h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\" \*\*%T/%{ms}T/%D**"

**Comment by acrollet** [comment]
> Is the goal only to include the timestamp of when the request was received/started and have it appear in the log? Or is the goal to try and track the time it took to serve a request with %T or %{unit}T log format?
> I'm guessing it's the latter to query logs with Cloud Watch Insights for requests that take over X milliseconds.

@olivereri yes, I'd say the latter. Also, do you feel that these ACs are clear and fully actionable?

**Comment by ElijahLynn** [comment]
> is the goal to try and track the time it took to serve a request

Yes, the total time, which Apache provides for us. I think we should use the milliseconds format, or the seconds, not the microseconds though.

**Comment by olivereri** [comment]
>  yes, I'd say the latter. Also, do you feel that these ACs are clear and fully actionable?

@acrollet Ok, that's what makes most sense to me but the issue description and ACs make that hard to understand. So I'd say that no, the ACs aren't clear enough to be fully actionable without clarification.

> Insights dashboard with Concurrent HTTP requests
I take this one to mean Cloudwatch Insights dashboard will track the number of requests served in a given amount of time? Say a second?

**Comment by olivereri** [comment]
Cloudwatch Insights requires the input logs be in JSON format. In the end it'll look more like this in the virtual host section:

`
LogFormat "{ \"time\":\"%{%Y-%m-%d}tT%{%T}t.%{msec_frac}tZ\", \"process\":\"%D\", \"filename\":\"%f\", \"remoteIP\":\"%a\", \"host\":\"%V\", \"request\":\"%U\", \"query\":\"%q\",\"method\":\"%m\", \"status\":\"%>s\", \"userAgent\":\"%{User-agent}i\",\"referer\":\"%{Referer}i\"}"
`


> CloudWatch Logs Insights automatically discovers fields in logs from AWS services such as Amazon Route 53, AWS Lambda, AWS CloudTrail, and Amazon VPC, and any application or custom log that emits log events as JSON. 


https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/AnalyzingLogData.html

**Comment by olivereri** [comment]
Some interesting results so far:

![image.png](https://images.zenhubusercontent.com/5f04cf8f49978b1615fee8c2/70f33d8d-6a18-4189-932a-f5fab931286c)

**Comment by acrollet** [comment]
> So I'd say that no, the ACs aren't clear enough to be fully actionable without clarification.

@olivereri I've updated the ACs, let me know if you have any further concerns. thanks!

**Comment by olivereri** [comment]
Insights Dashboard visualizing CMS-test Dev HTTP Request Data:

![image.png](https://images.zenhubusercontent.com/5f04cf8f49978b1615fee8c2/5ff3d527-d049-49e0-b4f9-0d949eb881c1)

**Comment by ElijahLynn** [comment]
> Insights Dashboard visualizing CMS-test Dev HTTP Request Data:
> 
> ![image.png](https://camo.githubusercontent.com/ec89ed76e62c5e840a65cac515c62174a6282a276043135dc40b9072722ff303/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3566303463663866343939373862313631356665653863322f35666633643532372d643034392d343965302d623466392d306439343965623838316331)

Oh yeah!!!

**Comment by olivereri** [comment]
Even better, bonus AC is possible through Cloudwatch Metric Filters

![image.png](https://images.zenhubusercontent.com/5f04cf8f49978b1615fee8c2/1412a24b-a648-4929-837a-7b43f299113d)

![image.png](https://images.zenhubusercontent.com/5f04cf8f49978b1615fee8c2/c5e4366d-310c-43f0-af73-ae229e8e5e25)

**Comment by olivereri** [comment]
> However, I need to work on this metric filter because it's querying the entirety of the dsva-vagov-dev/var/log/httpd/access_log log group meaning it doesn't differentiate yet between specific log steams.

While Cloudwatch Metric Filter doesn't provide a way to distinguish between log steams, i.e. CMS and CMS-test we can inject the `app name` into the Apache logs using system environment variables.

Where the metric filter `{ $.request_time_ms = * }` would apply to all apache Access logs ingested by Cloudwatch, even from non-CMS servers, further filtering on the new `cms_app` log field ensures test app data doesn't pollute non-test.  For example `{ ($.request_time_ms = *) && ($.cms_app = "cms") }` will ensure that the generated metric is only pulling HTTP Request time log fields from logs that also include value `cms` in the new field.

**Comment by acrollet** [comment]
ok, cool, closing this out based on that info and the fact that I'm seeing it come across on the cms-test dashboard. Great work!
