### ISSUE TITLE
Scale BRD servers up

### ISSUE THREAD

**Issue by ElijahLynn** [department-of-veterans-affairs/va.gov-cms#4170]
CPU load getting too high on occasion. 

AC:
- [x] Increase instance size in BRD deploy scripts, double the vCPU  
 https://github.com/department-of-veterans-affairs/devops/pull/8558
- [x] Update Grafana query to use the right cores (might be calculated by Prometheus) - NOT NEEDED
- [x] Put a marker in Grafana so we can see when the change happened to correlate with activity decrease
- [ ] ~Setup Grafana Alert if CPU goes about 75%. (Consider using Alert Manager w/Prometheus instead)~ moved to #4397 

![image.png](https://images.zenhubusercontent.com/5cdc72c50b7efe3f164150b2/fc0a0bfb-73b0-428f-adbb-141eb60570d8)

**Comment by indytechcook** [comment]
Cross-linking #4226

**Comment by ElijahLynn** [comment]
Today's deploy has the new instance size in it. I added an annotation in Grafana on the CPU graph:

![image](https://user-images.githubusercontent.com/1504756/108943904-83ee8a00-760e-11eb-99da-a4e59ee35524.png)
