### ISSUE TITLE
Increase Tugboat docker volume size

### ISSUE THREAD

**Issue by ElijahLynn** [department-of-veterans-affairs/va.gov-cms#4171]
We are reaching 75% volume usage of our 1TB docker volume for Tugboat on occasions and would be good to double this volume size. 

See (internal) https://dsva.slack.com/archives/C01A35JDH88/p1611357696005900?thread_ts=1611357109.005600&cid=C01A35JDH88 for instructions.

**Comment by oksana-c** [comment]
closing in favor of #4129
