### ISSUE TITLE
Get Tugboat on PagerDuty

### ISSUE THREAD

**Issue by ElijahLynn** [department-of-veterans-affairs/va.gov-cms#4174]
Get Tugboat to alert on PagerDuty when unscheduled downtime occurs. 

## Implementation

- Use https://tugboat.vfs.va.gov/_status endpoint, see CMS Login Check for pattern.
- Ask tugboat support if we can temporarily override the status endpoint response code to test, otherwise we may need to temporarily put tugboat down to test

## Acceptance Criteria

- [x] Pagerduty alert is sent to "CMS-Engineers-Critical" team if tugboat is down (3 second timeout) for 3 consecutive minutes
- [x] Alert has been demonstrated to function correctly

**Comment by mchelen-gov** [comment]
is #4562 a duplicate of this?

**Comment by acrollet** [comment]
@mchelen-gov I believe this was split out for the Critical Monitoring initiative, updating #4562 to remove the duplicate AC.
