### ISSUE TITLE
502 Bad Gateway errors on FE build in demo envs - GraphQL fails

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#4179]
## Description

there are consistent 502 Bad Gateway errors on FE build in demo envs when a new heath care system is published - GraphQL fails

## Acceptance Criteria
- [ ] GraphQL functions as expected in FE build on demo envs

**Comment by acrollet** [comment]
We believe this is related to the tugboat apache proxy timeout (currently 300s)

cf. https://dsva.slack.com/archives/C01A35JDH88/p1612304853044600

**Comment by ElijahLynn** [comment]
> We believe this is related to the tugboat apache proxy timeout (currently 300s)
> 
> cf. https://dsva.slack.com/archives/C01A35JDH88/p1612304853044600

This was it and specifically `/lib/apache/conf/conf.d/000-preview.conf` from the Tugboat repo root. I updated the ProxyPass directive to 1800 (30m) and ran `tbctl restart apache` to reload the config per guidance from @bchavet and @acrollet got the builds to work consistently now!

Tugboat is going to consider making that ProxyPass directive a configurable option so we don't have to repatch after updates.
