### ISSUE TITLE
CMS-TEST shouldn't trigger a release of vets-website

### ISSUE THREAD

**Issue by indytechcook** [department-of-veterans-affairs/va.gov-cms#4182]
## Description

CMS-TEST shouldn't trigger a release of vets-website

## Acceptance Criteria
- [ ] When triggering a content release in `cms-test` a jenkins job should not be triggered at http://jenkins.vfs.va.gov/job/deploys/job/{content-build-job-name}

**Comment by TheBoatyMcBoatFace** [comment]
No longer valid.
