### ISSUE TITLE
Migrate govDelivery Jenkins task to new job created as a part of a switch to Content-only build

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#4185]
## Acceptance criteria

- [ ] confirm govDelivery sends notification to appropriate distro lists on facility status updates after switch to content-only builds.

## implementation notes

govDelivery send function can be tested on Staging by updating an existing VAMC Facility Operating Status node

related story https://github.com/department-of-veterans-affairs/va.gov-cms/issues/1498

**Comment by ElijahLynn** [comment]
I should note that the current Jenkins task completes successfully on deploys but that the emails are never received so it doesn't currently work. Possible causes are the queue runner isn't getting invoked with the correct timestamp or the govDelivery API is not working correctly. Haven't looked further other than editing a test alert for Pittsburgh on CMS Staging and not getting the email after a content deploy/build.

**Comment by ElijahLynn** [comment]
Based on a Keybase chat, it seems that the STAGING password is likely incorrect. When we use a new Service account that will get updated correctly.

**Comment by oksana-c** [comment]
@indytechcook
seems that this task is no longer needed due to the sunset of cms export. Although wanted to verify w/ you if Content Build separation effort could affect GovDelivery Jenkins job at all, in which case, I'll rephrase this issue.

**Comment by cmaeng** [comment]
@ElijahLynn @indytechcook @swirtSJW looks like this issue may no longer be relevant but could you take a look before we close out? thanks!

**Comment by ElijahLynn** [comment]
I think this may still be needed because the content only build job may not be running it. From looking at http://jenkins.vfs.va.gov/job/builds/job/content-build-content-only-vagovprod/ I don't see it running anymore, but it could be running elsewhere.

**Comment by acrollet** [comment]
@ElijahLynn dug up the Ansible task that has historically been used to trigger govdelivery notifications: https://github.com/department-of-veterans-affairs/devops/blob/92683c4263acbc80b6665a9ee46af152d0971c71/ansible/deployment/roles/deploy-vets-website/tasks/main.yml

**Comment by ElijahLynn** [comment]
Related: 

- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/5545
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/5547

**Comment by ElijahLynn** [comment]
Closing, duplicated by https://github.com/department-of-veterans-affairs/va.gov-team/issues/25883.
