### ISSUE TITLE
Set ProxyPass directive to 1800 (30m) once it is configurable in Tugboat

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#4190]
## Description

See https://github.com/department-of-veterans-affairs/va.gov-cms/issues/4179 for context
> >We believe this is related to the tugboat apache proxy timeout (currently 300s)
> >cf. https://dsva.slack.com/archives/C01A35JDH88/p1612304853044600

> This was it and specifically /lib/apache/conf/conf.d/000-preview.conf from the Tugboat repo root. I updated the ProxyPass directive to 1800 (30m) and ran tbctl restart apache to reload the config per guidance from @bchavet and @acrollet got the builds to work consistently now!
> Tugboat is going to consider making that ProxyPass directive a configurable option so we don't have to repatch after updates.

## Acceptance Criteria
- [ ] ProxyPass directive to 1800 (30m) is set once it is configurable in Tugboat and is not wiped on updates

**Comment by jkalexander7** [comment]
Issue addressed in https://app.zenhub.com/workspaces/vagov-cms-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/7023
