### ISSUE TITLE
Create reports of node counts per VAMC and VISN

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#4191]
## User Story or Problem Statement

As a VAMC product team or CMS team member, i want to be able to count VAMC and VISN nodes so that i can make various decisions, including how some performance/scalability planning. 

Background: this was spurred by an analysis of how many VAMCs we might be able to support with GraphQL

## Acceptance Criteria
- [ ] /admin/content/audit/count-nodes-by-section shows a list of all parent sections, with node counts
- [ ] Clicking on a parent displays all child sections, with node counts
- [ ] going to /admin/content/audit/count-nodes-by-section/all shows all child sections, with node counts.

**Comment by indytechcook** [comment]
This is complete
