### ISSUE TITLE
Alert field is not removing empty values

### ISSUE THREAD

**Issue by indytechcook** [department-of-veterans-affairs/va.gov-cms#4198]
**Describe the defect**
The field `field_alert` is keeping empty values.

Example node: `devel/node/889`
```
            [field_alert] => Array
                (
                    [x-default] => Array
                        (
                            [0] => Array
                                (
                                    [target_id] => 0
                                )

                        )

                )
```

This is causing the cms export to have the following output in `node.78baf533-d7f7-488a-97cc-8a0a6846564b.json`
```
    "field_alert": [
        []
    ],
```

The output should be 

node/13

`node.3ee52459-9378-4de2-bdd5-21701b49804f.json`
```
 "field_alert": [],
```

In the UI it appears as if the node 889 doesn't have an alert.

This isn't a blocker for going live with CMS-Export as the front end has a work around but we need to address this in our data.

**Comment by oksana-c** [comment]
closing due to the pivot toward GraphQL Performance and Scalability effort.
