### ISSUE TITLE
Entity Field Fetch module is compatible with Drupal 9

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#4202]
https://www.drupal.org/project/entity_field_fetch

## Acceptance Criteria
- [x] contributed module Entity Field Fetch is compatible with Drupal 9

**Comment by swirtSJW** [comment]
![image](https://user-images.githubusercontent.com/5752113/107086972-bef85d00-67c8-11eb-9869-d72757cc1510.png)

This issue has been resolved in contrib.   https://www.drupal.org/project/entity_field_fetch/issues/3196854

I will be pulling the latest release in as part of another ticket so calling this one done.
