### ISSUE TITLE
Refactor usages of computed field and remove Computed Field module

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#4203]
## Problem statement

While value of Computed Field module is widely accepted by most site builders, there are many good reasons not to use it (out of scope of this issue).

Computed field add complexity and hides logic in unexpected places.

Current implementation of Computed Field module doesnt seem to be adding any value. All computed field values are currently set to empty.
`$value = '';` 

```
grep -ri computed *
core.extension.yml:  computed_field: 0
field.field.node.full_width_banner_alert.field_banner_alert_computdvalues.yml:    - computed_field
field.field.node.full_width_banner_alert.field_banner_alert_computdvalues.yml:label: 'Computed values for alerts'
field.field.node.full_width_banner_alert.field_banner_alert_computdvalues.yml:field_type: computed_string_long
field.storage.node.field_banner_alert_computdvalues.yml:    - computed_field
field.storage.node.field_banner_alert_computdvalues.yml:type: computed_string_long
field.storage.node.field_banner_alert_computdvalues.yml:module: computed_field
```

[Related internal Slack thread](https://dsva.slack.com/archives/CT4GZBM8F/p1612462925003200)

## Acceptance Criteria
- [ ] Current usage of Computed Fields is reviewed and the fact that is does nothing is validated
- [ ] All computed fields are converted to text fields or fields of appropriate type that matches established data model
- [ ] Change in data/content model is coordinated with appropriate FE team that is responsible for maintaining FE pages and transformers for identified fields
- [ ] Computed Field module is uninstalled and removed from the CMS 
- [ ] no DB tables left behind
- [ ] add tests if feasible

**Comment by kevwalsh** [comment]
Seems like va_gov_govdelivery.module is setting a value for this field behind the scenes.

https://github.com/department-of-veterans-affairs/va.gov-cms/blob/e1bff4cfb9e28621a71a5e94a1dd6e184632248b/docroot/modules/custom/va_gov_govdelivery/va_gov_govdelivery.module#L96 

@swirtSJW can probably speak more to what's dependent on this, for sending emails out through govdelivery.

**Comment by oksana-c** [comment]
@swirtSJW please add any details you have. The Core Application team is planning to work on this in Sprint 26. Thank you,

**Comment by acrollet** [comment]
@swirtSJW can you think of any reasons not to move the logic in [`_va_gov_govdelivery_build_alert_computed_field_data()`](https://github.com/department-of-veterans-affairs/va.gov-cms/blob/ce3df2cf72d91cc647f4b227b6ffaa65d9987cc7/docroot/modules/custom/va_gov_govdelivery/va_gov_govdelivery.module#L65) into a method in [`class ProcessStatusBulletin`](https://github.com/department-of-veterans-affairs/va.gov-cms/blob/ce3df2cf72d91cc647f4b227b6ffaa65d9987cc7/docroot/modules/custom/va_gov_govdelivery/src/Service/ProcessStatusBulletin.php#L10), and call it directly from [`ProcessStatusBulletin::processNode()`](https://github.com/department-of-veterans-affairs/va.gov-cms/blob/ce3df2cf72d91cc647f4b227b6ffaa65d9987cc7/docroot/modules/custom/va_gov_govdelivery/src/Service/ProcessStatusBulletin.php#L48)? I would then remove the computed field entirely. Both things are getting called during a node save, so I don't think there would be a performance hit.

**Comment by swirtSJW** [comment]
> Current implementation of Computed Field module doesnt seem to be adding any value. All computed field values are currently set to empty.
> $value = '';
> 
This premise is not right.   The computed field is being used, and contains data on full width banner alerts.


@acrollet  **History:**  The logic doing the computed field predated our gov delivery implementation.  Originally the front end was going to do all the sending of the bulletins so we had to package the relevant data for them in the computed field.   Then later,  we came up with a better way that had CMS handling the sends, but we used the same data the front end was using going to use from the computed field. You can see in the git history that it formerly lived in va_gov_backend.  

The logic could be removed from computed field and re-worked into a new method called from within ProcessStatusBulletin::processNode()

This is a pretty complex system though, so great care in testing this to make sure we don't break it while we are fixing what is not broken.  ;)
