### ISSUE TITLE
Prevent deletion or unpublishing of content fetched with EFF module 

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#4204]
As JHL or a VHA HQ editor of centralized content leveraged by VAMC content like Policies, i want to be prevented from deleting or archiving content that would break "downstream" content. 

ACs
- [ ] See https://www.drupal.org/project/entity_field_fetch/issues/3193585
- [ ] No one can delete node 15588 if paragraph in it is referenced
- [ ] A content_admin can delete node 15888 it if it contains no paragraphs referenced via EFF.

**Comment by ethanteague** [comment]
Having a tough time making the paragraph constraint method work. Reader's Digest version is that I can't figure out how to target the triggering element (the paragraph delete button) in a constraint. So, what ends up happening is that on node save, validation runs on all paragraphs, and fails on the first on that is ref'd on the page (regardless of whether it was the subject), and throws a message for it. I pushed up all of this to: https://git.drupalcode.org/issue/entity_field_fetch-3193585/-/tree/3193585-prevent-deletion-of

Tagging this as blocked, and hoping that @swirtSJW might have some ideas.
cc: @kevwalsh

**Comment by swirtSJW** [comment]
The EFF module has been updated. It prevents deletion of any node or term that is used as a source by EFF regardless of whether is it via the /delete form or a bulk operation or any other programmatic use of the API.  It will allow operations by CLI (drush) however as a way to resolve issues.

It does not cover prevention of paragraph removal.
