### ISSUE TITLE
Remove Views Tree module

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#4206]
https://www.drupal.org/project/views_tree

## Acceptance Criteria
- [ ] verify that Views tree isn't used anywhere
- [ ] module is removed from codebase
- [ ] no tables left behind
- [ ] no config left behind
- [ ] no state variables left behind
- [ ] no settings.*.php variables left behind

## Context

> Kev: that was still in use until a couple weeks ago. Kaise just updated a view for VHA health services that may have deprecated it

**Comment by acrollet** [comment]
Added views_tree to #4451

**Comment by acrollet** [comment]
@kevwalsh confirmed that the "Sections tree" view can be removed in [this slack thread](https://dsva.slack.com/archives/CT4GZBM8F/p1615819657095700).
