### ISSUE TITLE
CMS Test Coverage Analysis

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#4208]
## Acceptance Criteria

- [ ] team has a comprehensive list of manual test cases (in va.gov-team repo) to run through

## Implementation notes

- [ ] comprehensive list of custom features we've built that don't have test coverage
- [ ] stories created for any critical features that need automated test coverage

**Comment by oksana-c** [comment]
Test cases
*Roles:*
* *Creators*
	* Content creator - Benefits hubs
	* Content creator - Resources and support
	* Content creator - Office
	* Content creator - VAMC
	* Content creator - Vet Center
* Content Editor
* Content Reviewer
* Content Publisher
* Content Admin
* Redirect Admin
* User Admin
* Administrator

*Script:*
1. Claim test case
2. Log in
3. Perform Action(s)
4. Check dblog
5. Check JS console
6. Mark test case as tested

## Global
### Admin Toolbar

- *Confirm Menu items available for Content Editor and adjacent roles*
Home [Drupal] > Log Out
Manage
	* Content
	* Structure > Taxonomy (the only link under structure)
Sections
	* Veterans Affairs
	*  National Cemetery Administration
	*  Veterans Benefits Administration
	*  Veterans Health Administration
	*   DEPO
People [User Admins only]
Help
User Profile
Content Release Time
Branch
New test requirement documented in [Content Admins should not be able to administer media library settings · Issue #4787 · department-of-veterans-affairs/va.gov-cms · GitHub](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/4787) 

### Content Release

- [ ] Content release page is accessible to Content Admins and Content Publisher roles -  /admin/content/deploy
- [ ] Content Release functions without errors on Tugboat environment
- [ ] Content Release functions without errors on BRD environments
- [ ] Content Release catches and displays broken link errors.
    - [ ] Publish a VAMC system, reference an unpublished page in one of the detail pages and run a release.
    - [ ] confirm that broken link is registered in logs and the build is broken


## Products
### Benefits hubs

### Facility Status
Facility Status sync

### Outreach Hub


### Resources & Support
Q&A custom form logic

### VA Common
Centralized Content


### VA Forms


### VAMC

**Comment by jefflbrauer** [comment]
@ndouglas is this something you can pick up as our wizard of testing? :)

**Comment by ndouglas** [comment]
Sure, but I am a mere conjurer of [cheap tricks](https://user-images.githubusercontent.com/1318579/114236680-f792ef00-994f-11eb-8245-96e04e0f57bc.jpg).  (Kevin and Adrian have done a lot of excellent work on this already, it should be noted.)

**Comment by acrollet** [comment]
@kevwalsh and @ndouglas and I met a few days ago and started mapping out test cases on [this mural board](https://app.mural.co/t/vagov6717/m/vagov6717/1617732395516/b367a2c6fcfcb6ea0f71dd89eb8dcc4762839fae). I have it on my list to create stories for 2 mob sessions once d9 is ready to test. The first session will help us identify crucial functionality that needs automated tests and script out manual tests for the second session, which will happen immediately pre-launch. We're also planning on referencing @xiongjaneg's excellent training materials for user journeys and functionality to test.
