### ISSUE TITLE
Ensure that our connections with GovDelivery are working correctly

### ISSUE THREAD

**Issue by cmaeng** [department-of-veterans-affairs/va.gov-cms#4209]
## Background
GovDelivery is the system used by VA.gov to manage email subscriptions on specific websites / VAMCs. The current configuration and workflow does not fully function as intended.

### User Story or Problem Statement
As a va.gov end user, if I subscribe to announcements or notifications for a VAMC I want to get an email from GovDelivery when content changes occur.

The Drupal CMS team needs the ability to log in to GovDelivery (preferably with a generic account to minimize the "hit by a bus" factor) in order to troubleshoot issues.

## Acceptance Criteria
- [ ] Emails from users subscribed to specific VAMCs are going out when they are supposed to
- [ ] The CMS can login and troubleshoot in GovDelivery when needed

**Comment by swirtSJW** [comment]
Related https://github.com/department-of-veterans-affairs/va.gov-cms/issues/1361   We might want to get documented so both sides know what the needs are.
