### ISSUE TITLE
Enable bulk archiving of past events

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#4212]
## Description

There are hundreds of old outreach hub events that are only available via search engines (and in va.gov/sitemap.xml). 

There are performance and content strategy and tech debt (buggy transformer diffs) reasons to remove these from the FE build. 

VAMC System product, which also uses events, may also want the ability to bulk archive. 

Per @johnhashva [in slack](https://dsva.slack.com/archives/C01H29ERVJ7/p1612537017024300), they should be archived. 

We have no good way of identifying events in the past for bulk content moderation (eg archiving)

As a content admin, i can select past events from a certain Section, and archive them, so that they are no longer available on www.va.gov

## Acceptance Criteria
- [x] admin/content/events/past shows a list of all past events
- [x] View page title: "Past events"
- [x] Permissions: only Content admin (for now). 
- [x] Fields: Title, edit button, Moderation status, Date, Bulk operations
- [x] Filters: Moderation status, Owner
- [x] Bulk operations action available to admins: Archive

**Comment by swirtSJW** [comment]
@kevwalsh Are we intentionally not providing a menu for this?
![image](https://user-images.githubusercontent.com/5752113/107532933-64764c80-6b8c-11eb-8e57-31f3cef332a3.png)
