### ISSUE TITLE
Discovery research with business partners: event archiving 

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#4214]
Draft email to send to 
1. VHA Digital Media 
2. Tim Hudak at VEO (business partner for Outreach and Events)

```

Hi [business partner], 

The VA.gov CMS team is considering a policies for archiving events on www.va.gov after they have happened. We have a few questions for you that may help us come up with the best solution for Veterans and editors of events on VA.gov. 

1. Does VEO have any policies about how long to retain content such as events on VA.gov?
3. Do any other web calendar tools used by VEO (including Teamsite) have any built-in event archiving policies? 
4. For events posted to the https://www.va.gov/outreach-and-events/events , do you think Veterans would benefit from having all event content retained, or removed after the event takes place? Or is it more of a case-by-case basis? 
5. If we were to enable an auto-archiving process, what do you think is the appropriate timeline for this? For example, should it be 1 day after the event has taken place? 1 month? 1 year?  etc. 
6. Any other thoughts about the content lifecycle of events posted to VA.gov? 

We should make it clear that any change to implementation will be made in accordance with Federal Records Act (44 U.S.C. 31). 

Thanks in advance for any help with this topic
```

**Comment by nataliedunbarCS** [comment]
**DRAFT Approach**

### Assess current state

1. Are there governance rules for archiving events in place / in use with current CMS?
2. If so, is it automated or does someone have to trigger the process?
3. Is there an events template for _recurring_ events/reuse strategy? 
4. If so how are recurring events distinguished from one and done events?
5. For the >500 past events identified, what VISN/VAMCs are they tied to? 

### Business rules

1. Is there an editorial component to requesting / tracking events (i.e. an editorial calendar)? Who manages?
2. Ballpark # events / year / VAMC that are created/managed?
3. Is there an average number of events / event frequency for each VAMC?
4. Are there events that have to be kept? If so, what types?
5. Are there regulatory or similar rules/policies re keeping/archiving/sunsetting events? Or is it ad hoc?
6. Who manages archiving of events? (might also be good to understand who creates them if a lifecycle model is put in place)
7. Are events tracked in analytics? What can/does the data say? 
8. What rules / guidelines are in place for events migrating from old CMS to Drupal, or as new VISNs onboard to Drupal?
9. Have events been audited on the FE? If so, when?

### User needs

1. Do Veterans need to access past event info? If yes, under what circumstances?
2. Are there other places where event (current or past) is shared with / accessed by Veterans?

### Techical considerations

1. Does current CMS (Teamsite) include technical workflow for past events?
2. If yes - what worked? what didn't? 
3. Any rules/best practices specific to archiving events (or other time/date-specific content types) in Drupal?
4. Will events on Teamsite automatically migrate to Drupal? Is it scripted or does an editor have to manually input each event?
5. Is there a tech solution to exclude events past a certain "freshness date" to prevent old or outdated info from migrating over?
6. How much of event governance can be automated? How much requires a user to trigger?

**Comment by ContentBrewmaster** [comment]
First contact with Andrea Martinez at VA on March 30. Followup sent to her delegate Jose Llamas April 25.

**Comment by cmaeng** [comment]
blocked by no response from stakeholder

**Comment by EWashb** [comment]
@ContentBrewmaster, I'm inclined to go ahead and close this if you've still not had any luck. We can just note what you've attempted thus far.

**Comment by ContentBrewmaster** [comment]
Closing ticket based on lack of stakeholder response after 2 attempts.
