### ISSUE TITLE
Forward email from VACMSSupport@va.gov to external address

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#4229]
As a CMS help desk team member, I need to auto-forward emails sent to `VACMSSupport@va.gov` inbox to `support@va-gov.atlassian.net` inbox, so that I don't spend extra time copying information from the old support email address to Jira Service Desk.

## Acceptance Criteria
- [ ] Emails from `VACMSSupport@va.gov` are forwarded to external address `support@va-gov.atlassian.net`

See also:
- https://dsva.slack.com/archives/CT4GZBM8F/p1612898661201200
- https://dsva.slack.com/archives/CNA780EDN/p1613668292015900
- https://dsva.slack.com/archives/CT4GZBM8F/p1614279674348900

**Comment by ElijahLynn** [comment]
The person to ask for this is Dale Lewis and to either email or ping on MS Teams with CAG/GFE first to see if it is possible.

**Comment by ElijahLynn** [comment]
Sent, see (internal) https://dsva.slack.com/archives/CT4GZBM8F/p1612898661201200.

**Comment by erogray** [comment]
Most recently: waiting on an email response from Griselda Gallegos as of 2/18

**Comment by VanessaLuxen** [comment]
Follow-up email sent to Griselda Gallegos asking for policy exemption.

**Comment by VanessaLuxen** [comment]
Email from Dale Lewis on Feb 9: I believe policy does not let us forward. Technically, it can be done (the external address would need to be added as a Contact object first and then the Contact added to the DG). 

Elijah had written back to Dale that these emails will not contain PII/PHI on Feb 9

Email from Patrice Milfajt on Feb 10: That would need to be run through the project Information System Security Officer (ISSO)

Elijah found out that our ISSO is Griselda Gallegos and she was forwarded the email string and this message on Feb 17: I just discussed an issue with the Active Directory (AD) team and they said we need to get a Policy exemption to do what we want to do. They said that our ISSO is the one to contact next, and that appears to be you.
We have a need to forward email to the distro list VACMSSupport@va.gov to support@va-gov.atlassian.net. Right now we can only add internal email addresses to the distro list. The AD team said it is technically possible and outlined how we would do it, but that it is a policy issue.

Elijah added Faith Owusu-Sekyere Adding Faith Owusu-Sekyere, our System Steward to the email thread on Feb 18:
Both Faith and Griselda stated that the only kind of policy exemption they know of is to create a POAM in eMass and have it go through the workflow and approved. It doesn’t seem like a POAM would be useful for forwarding an external email to our helpdesk. Any guidance you can provide on how to get this approved would be great Patrice. Can they just reply to this email for approval?

Griselda Gallegos wrote this back in an email from Feb 18: I am providing concurrence in this email thread for any help desk ticket that needs to be created.

Elijah replied to Griselda's email on Feb 18: I am not sure what that means. Does that mean we should open a helpdesk ticket to ask for approval? If so, does that mean Service Now or is there a different helpdesk (some teams have different ones).

I reached out to Griselda again on Feb 23 asking for clarification but no response has been received.

**Comment by VanessaLuxen** [comment]
Asking @mchelen-gov for further assistance with getting this approved.

**Comment by ElijahLynn** [comment]
BLOCKED: Our System Steward and ISSO are not responding. Escalation needed.

**Comment by jefflbrauer** [comment]
Next step - @mchelen-gov to call Giselde to understand if we need to create a ticket in order to get an exemption, and if so, in which system does that ticket need to be created?

**Comment by ElijahLynn** [comment]
I am going to jump back on this and schedule a meeting with everyone involved, Mike, Faith, Griselda, Barnes and myself. (anyone else?)

**Comment by ElijahLynn** [comment]
I've sent a meeting invite to a bunch of us for the 27th at 3pm ET to discuss and hopefully get a next step!

**Comment by jefflbrauer** [comment]
Based on the meeting date, I will move this to sprint 31

**Comment by mchelen-gov** [comment]
were there any docs that needed to be updated with this change?
