### ISSUE TITLE
Onboard Va.gov Virtual Agent (Chatbot) team to the CMS

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#4244]
## User Story

As a CMS Engineer, I need to understand technical requirements of the Va.gov Virtual Agent (Chatbot) team, so that I can make informed decisions and recommend best practices for using the CMS Content API.

As a Va.gov Virtual Agent (Chatbot) team member, I need access and information about the CMS Content API and I need to understand the CMS content model, so that I can train the Chatbot.

## Acceptance Criteria
- [x] the CMS team has the information on the use cases / expectations and end goals of the Chatbot initiative and has enough technical details to support the Chatbot team
- [x] the Chatbot team can use GraphQL endpoint & query / explore content model in production and/or Demo environment

**Comment by shefalinayak** [comment]
Context: Drupal will likely be one of the main sources of content for the chatbot. We're looking to understand:
- how to use the CMS Content API
  - We're mainly looking for Q&A content, but may need some other content types
  - We may want to query for recently changed content
- how to explore the Drupal UI, and how the Drupal UI relates to the GraphQL schema

**Comment by oksana-c** [comment]
Action items based on the onboarding conversation with the VA.gov Virtual Agent (Chatbot) team:
* Create a demo environment for the Chatbot team that is updated every time content is released on production to reduce the impact on the CMS Prod infrastructure. Sprint 27 (3/1-12) https://github.com/department-of-veterans-affairs/va.gov-cms/issues/4316 
* Ad-hoc support for the Chatbot team while the product is in the discovery phase. E.g. answer content model questions as they come up.
