### ISSUE TITLE
Spike: Monitoring systems performance

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#4246]
## Owner
@ElijahLynn 

## Description

As a CMS Engineer, I need access to granular reporting on various system performance indicators, so that I have enough information to make informed decisions for maintenance / scaling / enhancements to the CMS infrastructure.

## Acceptance Criteria
- [x] team discussed currently available monitoring tools and reporting options
- [x] team identified gaps in monitoring / reporting
- [x] team discussed options to fill the gaps
- [x] next steps to fill identified gaps are brainstormed / agreed upon

## Notes

First session 1.5hrs: free-form conversation / diverge with ideas
- review what reporting we already have
- brainstorm what else we need

Seconds session: 1.5hrs - converge
- define metrics we need to track
- talk tools

## Additional topics

- uptime monitoring

**Comment by ElijahLynn** [comment]
Some options to discuss that are available for implementation internally:
- Datadog
- Prometheus + Grafana
- Grafana Loki Logs (only in DEV right now)
- Sentry
- Cloudwatch Insights (quasi-Splunk)
- Blackfire

- Logscout Duty

**Comment by indytechcook** [comment]
I'd like to talk about how to know when we hit our limits before our users do.  Basically, a performance test that publishes all content and runs the build job.

**Comment by ElijahLynn** [comment]
https://www.drupal.org/project/prometheus_exporter

**Comment by indytechcook** [comment]
Adding https://www.drupal.org/project/raven for Drupal sentry intergration

**Comment by oksana-c** [comment]
Spikes scheduled on 3/5 and 3/9.

**Comment by oksana-c** [comment]
linking ToT metrics doc (slide 3) for reference to see if there are opportunities to integrate the display of infra + content + user + help desk metrics
https://docs.google.com/presentation/d/1SiJE0j_zLotsYvAmjwLXVw_BlSJrUvoF/edit#slide=id.gc0e28dc14f_0_6

**Comment by oksana-c** [comment]
Spike Notes https://docs.google.com/document/d/1LlxH026S1OPny-FtpokuxHv30v9AuMt2aoWTUUct_lw/edit#

**Comment by ElijahLynn** [comment]
I see evidence that Loki logs can do dashboard panel reports on logs (see the Slow Requests panel):

![image](https://user-images.githubusercontent.com/1504756/110166374-1af2d900-7da9-11eb-856c-6cb9f163c8bd.png)

And also:
> The tool now lets users write queries for alerts directly from within the dashboard — previously this function required configuring alerts with Grafana...

> ...He showed, for example, how it is possible to set rules with Loki that are forwarded to the alert manager. Once an alert is received, he showed how it is possible to analyze the database in such a way that you quickly find the “root cause of the issue,” 


https://thenewstack.io/grafanas-loki-2-0-features-new-log-labels-direct-alerts-and-a-prettier-dashboard/

**Comment by oksana-c** [comment]
Follow-up backlog refinement is scheduled for Mon 3/15.
