### ISSUE TITLE
Change management for current trainees (devshop -> Tugboat)

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#4248]
## Description

How might we reduce the impact on trainees when we move from training.ci.cms.va.gov to https://master-pion6wlxie1t0mckcgwjl4kid1k1haqe.demo.cms.va.gov/ (or one of the other training environments?

- via email? 
- URL redirects? 

## Acceptance Criteria
- [x] New training environment is created on Tugboat.
- [x] Site alert is added regarding regular refreshes. @xiongjaneg 
- [x] Documentation is updated. @xiongjaneg 
- [x] Training users are added to prod with blocked status. @xiongjaneg 
- [x] Email to training users is drafted. @xiongjaneg 
- [x] Email to training users is reviewed. @erogray @VanessaLuxen 
- [x] Email to training users is sent.

**Comment by xiongjaneg** [comment]
Technical redirect solution is currently not recommended.

**Comment by xiongjaneg** [comment]
@oksana-c @kevwalsh We found an issue with bulk user import to prod. The user account creation email automatically went out to users. Need problem-solving on this before using this process for next VISN.

**Comment by oksana-c** [comment]
@xiongjaneg , what do you see as an ideal event sequence here?

I'd rather avoid making one-off logic changes to accommodate  various methods of import, although we should definitely make some corrections to default email templates to set correct expectations. 

Please review email defaults at the bottom of [this page](https://prod.cms.va.gov/admin/content-models/users) and let's see if the granular events that are available to us are sufficient to support the process that's intuitive for all users in all situations. Specific attention to "Welcome (awaiting approval)" email.

Once we review available templates, it would be wise to run tests to ensure that appropriate templates are going out as a part of bulk import process.

**Comment by xiongjaneg** [comment]
@oksana-c @kevwalsh I'm really torn on this one. I agree 100% that we shouldn't have one-off changes and it would be really hard to apply technical logic to when bulk user import is for adding trainees (and therefore no message goes out) or for adding users who don't need training (therefore account activation goes out).

Given this, we'd have to change account creation for people who need training back to bulk import into training environment, complete training, then individual prod account creation.

**Comment by oksana-c** [comment]
opened this story https://github.com/department-of-veterans-affairs/va.gov-cms/issues/4270 

it is likely an 8 pointer and may not be implemented within next sprint. 

I recommend we update the verbiage in the "Welcome (waiting approval)" email as a short-term fix instead of switching to importing users on training instead of prod.

**Comment by xiongjaneg** [comment]
Sent Feb. 10:

Maeng, Clarence (Agile 6 Applications, Inc)
Wed, Feb 10, 4:45 PM
to VA

Dear Drupal CMS editor:

 

You may have mistakenly received an email from us with a link to the Drupal CMS production account. Sorry for the confusion - that email was an error.

 

We also want to let you know that URL for the Drupal CMS training environment is changing. 

 

Starting Monday, February 15, 2021, please use this link for Drupal CMS training activities:

https://cms-training-pion6wlxie1t0mckcgwjl4kid1k1haqe.demo.cms.va.gov/

 

Please update your training environment bookmark if you’ve saved one on your browser.

 

Your training environment account will be set up on the new training environment. You will log in with your VA.gov email address for the username with the default password “drupal8”.

 

The Drupal CMS training environment is temporary. It will be refreshed on a regular basis every Monday at 9:00 a.m. ET with the latest content and code from the production (live) environment. Any content created or edited directly in the training environment will be lost during the refresh.

 

Please reach out with any questions or concerns.

 

Thank you,

 

Clarence Maeng

Delivery Manager, VFS-CMS Team

763-443-1606

Supporting editor-centered management for Veteran-centered content

**Comment by xiongjaneg** [comment]
Bulk user import was tested and verified that users are imported in Blocked status and no automated emails are sent.
