### ISSUE TITLE
Spike: Improve expectations about training environment content stability

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#4249]
[this issue needs an epic]

## User Story or Problem Statement

As a trainee, i want to know about how long i may be able to access any content i've created in a training environment, so that i can plan my training activities accordingly. 

How might we set expectations around the longetivity of content on training environments? 
- Can site alert play a role? 
- Any changes to add to training materials? 

Can we determine a regular cadence for wiping training environments to minimize impact? 

Should it be automatic? 

Should we consider more than one training environment to allow for greater longevity? 

## Acceptance Criteria
- [x] We have policies to govern the refreshing training environments. 
- [x] We have a plan to set expectations with trainees about training environment longevity

**Comment by xiongjaneg** [comment]
Currently, automatic refreshes are not available. As of training sync February 10, 2021, we'll start with a weekly refresh on Monday morning. Reevaluate frequency at a later training sync after gathering some data about new VISNs and impact of erased content on editors.

Adding message to alert on bottom of training environment, something like The Drupal CMS training environment is temporary. It will be refreshed on a regular basis every Monday at 9:00 a.m. ET with the latest content and code from the production (live) environment. Any content created or edited directly in the training environment will be lost during the refresh

**Comment by kevwalsh** [comment]
Followup for implementation: #4271

**Comment by xiongjaneg** [comment]
Site alert for training environments #4271 was successfully tested. After weekly refreshes, the site alert will be activated.
