### ISSUE TITLE
Upgrade Field Formatter

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#4259]
https://www.drupal.org/project/field_formatter

major version upgrade

Field Formatter module provides a collection of generic formatters for entity reference fields that output only a specific field of the referenced entity.

## Acceptance Criteria
- [ ] module is upgraded
- [ ] no regression in field formatter functionality
  - check how entity reference fields display on node view based on formatters provided by this module

**Comment by ndouglas** [comment]
>3.x is based on 8.x-2.x and adds Drupal 9 support. If you're using 8.x-2.x you may want to upgrade! Do not use it in production but please help testing.

😱!  But I'm not sure that we're actually using this module:

<img width="850" alt="Screen Shot 2021-02-23 at 2 13 31 PM" src="https://user-images.githubusercontent.com/1318579/108895249-56d7b280-75e1-11eb-9afe-78f54b6e97cf.png">

It was added in [this commit](https://github.com/department-of-veterans-affairs/va.gov-cms/pull/3985/commits/61e60402a086694e66e8209888b08108602ea9db), but I can't find any code, config, or anything else that seems to depend on the module 🤔  The CLP Q&A's still seem limited to 10 in the form without the module being present.  @ethanteague Can you help clarify?

**Comment by ethanteague** [comment]
> > 3.x is based on 8.x-2.x and adds Drupal 9 support. If you're using 8.x-2.x you may want to upgrade! Do not use it in production but please help testing.
> 
> ! But I'm not sure that we're actually using this module:
> 
> <img alt="Screen Shot 2021-02-23 at 2 13 31 PM" width="850" src="https://user-images.githubusercontent.com/1318579/108895249-56d7b280-75e1-11eb-9afe-78f54b6e97cf.png">
> 
> It was added in [this commit](https://github.com/department-of-veterans-affairs/va.gov-cms/pull/3985/commits/61e60402a086694e66e8209888b08108602ea9db), but I can't find any code, config, or anything else that seems to depend on the module  The CLP Q&A's still seem limited to 10 in the form without the module being present. @ethanteague Can you help clarify?

Yep, @ndouglas , we are using it - we have a custom fieldgroup formatter on clp pages that relies on field_formatter logic.

**Comment by ndouglas** [comment]
After rapping on a Zoom call, consensus seems to be that this isn't in use anymore, as far as we can tell, so I'm going to open a PR to remove it.
