### ISSUE TITLE
Upgrade Linkit

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#4261]
https://www.drupal.org/project/linkit

Upgrade to 6.0.0-beta2 +

## Acceptance Criteria
- [ ] module is upgraded
- [ ] no regression in Linkit functionality

**Comment by ndouglas** [comment]
Not expecting any regressions here:

<img width="830" alt="Screen Shot 2021-02-23 at 2 38 33 PM" src="https://user-images.githubusercontent.com/1318579/108898110-d1ee9800-75e4-11eb-87b5-03c0976cb9b7.png">
