### ISSUE TITLE
Include commit in PROD deploy Slack notification channel message to #cms-team

### ISSUE THREAD

**Issue by ElijahLynn** [department-of-veterans-affairs/va.gov-cms#4263]
As an engineer, the Slack message that says the PROD deploy was successful doesn't tell me what code was deployed. Include commit in PROD deploy Slack notification channel message to #cms-team. Optionally include the commit message description?

![image](https://user-images.githubusercontent.com/1504756/107577642-89c48400-6ba7-11eb-8260-6bfe97403e16.png)

## Acceptance Criteria
- [ ] Message shows short commit SHA
- [ ] SHA is hyperlinked to GitHub release page
- [ ] Commit description summary (not body) is included

**Comment by acrollet** [comment]
Ideally the commit would be linked to github. I'm in favor of showing the truncated commit message as well...

**Comment by ElijahLynn** [comment]
> Ideally the commit would be linked to github. I'm in favor of showing the truncated commit message as well...

Cool, added your suggestions to ACs.

**Comment by TheBoatyMcBoatFace** [comment]
This has been resolved.
