### ISSUE TITLE
Develop a process for handling Broken Link incidents

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#4273]
## Problem statement

We are handling all broken links via ad-hoc processes. As we approach critical user / content mass, it's time to formalize our approach.

## Acceptance Criteria
- [x] we have a public documentation that describes the CMS team process / commitment for handling broken link incidents.  The process outlines the following aspects:
   - [x] Response time when broken links appear during builds
   - [x] Process for identifying the culprit and either (1) forwarding to the author, (2) addressing the issue with CMS team resources
   - [x] Communication template for forwarding incidents to authors + template for a follow up escalation
- [ ] ~process outline is reviewed and accepted by the CMS Core Application Team PO (Mike C)~ will be handled in https://github.com/department-of-veterans-affairs/va.gov-cms/issues/4480
- [ ] ~process outline is reviewed and accepted by the VFS POs (Dave C, John H)~ will be handled in https://github.com/department-of-veterans-affairs/va.gov-cms/issues/4480

**Comment by erogray** [comment]
Made relevant updates to https://docs.google.com/document/d/1s41l8-kQWzfII1QZMprQK5nUe-tArYQLx_2kaDJkjuM/edit#

I'm troubled about proposing hard SLAs for this; there are very likely going to be circumstances in which we just can't fix someone else's content fast enough. But we can discuss.
