### ISSUE TITLE
Remove Mass Password Reset

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#4280]
https://www.drupal.org/project/mass_pwreset

## Acceptance Criteria
- [ ] module is removed from codebase
- [ ] no tables left behind
- [ ] no config left behind
- [ ] no state variables left behind
- [ ] no settings.*.php variables left behind

**Comment by acrollet** [comment]
module disabled in #4456, will be removed in #4451
