### ISSUE TITLE
Upgrade Migration Source CSV

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#4282]
https://www.drupal.org/project/migrate_source_csv

jump from 8.x-2.2 to 8.x-3.4

## Acceptance Criteria
- [ ] module is upgraded
- [ ] no regression in functionality - e.g. bulk user import from CSV + connect w/ @swirtSJW if there are other regular migration jobs that are using CSV

**Comment by acrollet** [comment]
I've blocked this on #4281, I think it'll be best to wait until that's been merged.
