### ISSUE TITLE
Remove OpenAPI, OpenAPI UI, ReDoc for OpenAPI UI, Swagger UI for OpenAPI UI

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#4284]
If we're removing Tome, we should remove all four contribs.

## Acceptance Criteria
- [ ] OpenAPI removed
- [ ] OpenAPI UI removed
- [ ] ReDoc for OpenAPI UI removed
- [ ] Swagger UI for OpenAPI UI removed
- [ ] schemata + json_schemata removed

**Comment by indytechcook** [comment]
Part 1 PR to uninstall: https://github.com/department-of-veterans-affairs/va.gov-cms/pull/4716
Part 2 will be to remove the code.
