### ISSUE TITLE
Remove Schemata module

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#4292]
The schemata module was added as a dependency of the OpenAPI module suite and should be removed in #4805 .

## Acceptance Criteria
- [ ] confirm that there are no further dependencies on schemata
- [ ] schemata module is disabled and slated for removal

**Comment by acrollet** [comment]
This is deprecated by #4463

**Comment by acrollet** [comment]
Re-opened, I was wrong that schemata has already been removed!
