### ISSUE TITLE
Upgrade Taxonomy Menu

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#4293]
https://www.drupal.org/project/taxonomy_menu

8.x-3.x-dev updated 7 Aug 2020 - D9 compatible. If we don't want to switch to dev - we'll need to apply a bunch of patches or connect with maintainers for a new release.

## Acceptance Criteria
- [ ] module is upgraded
- [ ] no regression in functionality
    - Sections menu still works in Admin toolbar and when a new item is added at the top level - it is displayed alongside the five current menu items - /admin/structure/taxonomy/manage/administration/overview
    - /admin/structure/taxonomy_menu - config changes in this form have always broken Sections menu, so I see no point of playing around with config to test this

**Comment by acrollet** [comment]
diff: https://git.drupalcode.org/project/taxonomy_menu/-/compare/8.x-3.4...8.x-3.x
