### ISSUE TITLE
Upgrade Views Bulk Operations

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#4296]
https://www.drupal.org/project/views_bulk_operations

major version jump from 8.x-2.5 to 8.x-3.10

## Acceptance Criteria
- [ ] module is upgraded
- [ ] no regression in functionality
   - [ ]  /admin/content/bulk Bulk Actions are executed without errors
   - [ ] /admin/content/facility-status - Facility status dash - overrides exist in docroot/modules/custom/va_gov_backend/va_gov_backend.module (`_va_gov_backend_vbo_facility_status_form_ui()`)
   - [ ] periodic tasks run without errors
   - [ ] `drush va-gov-enable-deploy-mode` runs without errors

**Comment by acrollet** [comment]
diff: https://git.drupalcode.org/project/views_bulk_operations/-/compare/8.x-3.10...8.x-2.5

**Comment by acrollet** [comment]
diff: https://git.drupalcode.org/project/views_bulk_operations/-/compare/8.x-2.5...8.x-3.10

**Comment by acrollet** [comment]
Waiting on the resolution of #4702 for re-merge
