### ISSUE TITLE
Read-only replica of the database [DevOps]

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#4300]
AC:
- [ ] make read-only replica available to the application
- [ ] Monitoring is in place (Grafana)

TASKS:
- [x] Read replica docs > https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_ReadRepl.html
- [x] Create replica manually in cms-test using UI
- [x] Add to Grafana panel
- [x] Test with CMS code
- [ ] Create replica in Terraform
- [ ] Create deployment runbook (if needed)
  - [ ] Primary is unavailable in "modifying" state for <5 minutes
  - [ ] Replica takes 10+ minutes to create 
- [ ] Apply to all environments

**Comment by ElijahLynn** [comment]
I think the AC might be better phrased as e.g. "All Drupal reads are configured to use Read Replica".

**Comment by ElijahLynn** [comment]
> I think the AC might be better phrased as e.g. "All Drupal reads are configured to use Read Replica".

Oh, I see that is pretty much your second one, nvm.

**Comment by ElijahLynn** [comment]
I just added 3 new Grafana Panels to measure some stats of before and after latency of the Read Replica:

1. Read/WriteThroughput
2. Read/Write IOPS
3. Read/Write Latency

![image](https://user-images.githubusercontent.com/1504756/111853563-be2f0c80-88d8-11eb-879f-987e2073f5ea.png)

**Comment by ElijahLynn** [comment]
In my tests now doing a vets-website build (`composer va:web:build`) with the read replica activated, I am not seeing as much resource consumption as I expected on the read-replica. So I did some digging and it appears much of core is not setup to use the replica and the replica can be used mostly by custom code. https://www.drupal.org/project/drupal/issues/3058019

![image](https://user-images.githubusercontent.com/1504756/112246904-a1fcd980-8c10-11eb-8f2b-55f79e8699d3.png)


If this is the case (and it isn't user error) then we might look specifically at seeing about patching the GraphQL module to do the replica reads to start with.

**Comment by indytechcook** [comment]
This change was supposed to catch all entity queries: https://github.com/department-of-veterans-affairs/va.gov-cms-test/commit/9f8f0e3f7efb55339db2b60b0e059334164604ab. 

So either grarphql isn't using entity queries, that setting isn't being picked up or it's not working right.

**Comment by indytechcook** [comment]
We should enable devel and web profiler, that should tell us where the queries are going.

**Comment by indytechcook** [comment]
I followed up on this and traced down how GraphQL queries data.

It uses the Entity Storage services.  Which will use `SqlContentEntityStorage` to generate the query.  As state in the issue https://www.drupal.org/project/drupal/issues/3058019, `SqlContentEntityStorage` directly injects `$container->get('database')` instead of being defined as a service like `entity.query.sql`.  This means it requires a core patch in order for use to get value from using a replica.

**Comment by jefflbrauer** [comment]
Per hackathon 3/24, the team agreed to stop work on this and switch gears to memcached.

**Comment by ElijahLynn** [comment]
> Per hackathon 3/24, the team agreed to stop work on this and switch gears to memcached.

Further explanation of this is here > https://github.com/department-of-veterans-affairs/va.gov-cms/issues/4461#issuecomment-807096110.

**Comment by mchelen-gov** [comment]
ok to clarify, are we saying we still want to do this at some point in addition to memcache?

**Comment by ElijahLynn** [comment]
> ok to clarify, are we saying we still want to do this at some point in addition to memcache?

I think we can still explore this in the future. It would mostly be to reduce load on the database, not to improve performance. The reads from RDS seem to be pretty fast, it is the writes that are much slower.

**Comment by TheBoatyMcBoatFace** [comment]
No longer needed - Content Build is not having a significant impact on application performance currently.
