### ISSUE TITLE
Migration errors from periodic job should notify slack.

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#4301]
**Describe the defect**
We've had repeated migration failures due to network certificate issues that use to (I am pretty sure) cause the periodic job to fail and alert slack in #cms-notifications.

However, there were multiple failures today (2/11/21) and no notifications came in.
![image](https://user-images.githubusercontent.com/5752113/107828121-2e84c400-6d56-11eb-8d47-d89de5375013.png)

Error
```
Migration failed with source plugin exception: Error message: cURL error 60: SSL certificate problem: unable to get local issuer certificate (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) at https://www.alaska.va.gov/locations/facilities.asp. in /var/www/cms/docroot/modules/contrib/migrate_plus/src/Plugin/migrate_plus/data_fetcher/Http.php l
```
This is a time sensitive system for vets and we need to know when it stops working.

**To Reproduce**
?

## AC

- [ ] if an exception is thrown in a periodic Jenkins job - the Slack is notified

**Comment by indytechcook** [comment]
Linking to #4268

**Comment by ElijahLynn** [comment]
The main issue here is that Drush doesn't output an error status or code. If Drush output the right error status, then it would fail the Jenkins job and the Slack alert would work fine. 

This could also be related to yaml-tests.

**Comment by acrollet** [comment]
@ElijahLynn is this issue still relevant?

**Comment by ElijahLynn** [comment]
I don't think so, I believe we installed the certificate to the Devops BRD deploys for all services and it resolved the issue.

**Comment by ElijahLynn** [comment]
Add DigiCertTLSRSASHA2562020CA1 Intermediate (https://www.alaska.va.gov)  - https://github.com/department-of-veterans-affairs/devops/pull/8516

**Comment by ElijahLynn** [comment]
I suppose the essence of this issue is still not met though, which is to notify Slack if there is an issue, so we may want to re-open for that.
