### ISSUE TITLE
SPIKE: technical implementation of VAMC system menu IA governance

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#4311]
See #4144 for design/governance doc, and see [spreadsheet](https://docs.google.com/spreadsheets/d/1n6h0NUJmQcFsc90dy14FQrX_0wVPX0AM7NlZoHSFKaA/edit#gid=1058557895) with example paths, especially columns C,D and S and T. 

## User Story or Problem Statement

As a product owner (content_admin, or possibly an administrator only, TBD) 
* i can designate which parent items in VAMC system menus are eligible to have children menu items created by non-Content admins, 
* i can designate which paths should have "locked" menu items, meaning that non-content-admins would not be able to edit those menu items, across all VAMCs (such as pittsburgh-health-care/pharmacy AND erie-health-care/pharmacy, and all [health-care-system]/pharmacy)
* i can additionally designate individual URLs at certain VAMCs that should be locked (such as pittsburgh-health-care/dav-vans BUT NOT erie-health-care/dav-vans). 

As a content_editor, content_reviewer, or content_publisher with workbench access to a VAMC menu (eg [Lebanon Health Care menu](prod.cms.va.gov/admin/structure/menu/manage/va-lebanon)) : 

* i shouldn't be able to administer the menu itself (eg go to `admin/structure/menu/manage/va-lebanon` and drag and drop)
* i shouldn't be able to add or edit menu items for content types other than Detail Pages
* i should be able to place individual menu items of Detail Page content type, using the Menu settings in the right rail, but only with certain parents eligible. 
* i should be able to see the whole menu, with some items disabled (those that are not eligible, [see example screenshot](https://app.zenhub.com/workspaces/vagov-cms-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/4144#issuecomment-771067856)

The above behavior should only target VAMC menus (typically, those that have `-health-care` in their machine name, but some of the VISN 4 menus are missing that`) 

## Acceptance Criteria
- [x] We have identified a technical approach that will accomplish the above user stories for ~144 VAMC system menus. 

## Implementation steps
- [ ] TBD

**Comment by shiragoodman** [comment]
@kevwalsh would it be okay to add my teams label to this so we can track the support Mikki is providing on our board?

**Comment by kevwalsh** [comment]
> @kevwalsh would it be okay to add my teams label to this so we can track the support Mikki is providing on our board?

@shiragoodman of course! Just seeing this now. Feel free to do that on any issue on our board.

**Comment by kevwalsh** [comment]
We identified a viable approach to this in Sprint 29. We'll be following it up in Sprint 30 in #4988.

**Comment by swirtSJW** [comment]
Much of the functionality in this has been merged in with https://github.com/department-of-veterans-affairs/va.gov-cms/pull/4894 however most of the action of it has been short circuited to not perform until we get some other issues in the epic resolved first.
