### ISSUE TITLE
Vets Website non-master front end builds should not use prod as the GraphQL API

### ISSUE THREAD

**Issue by indytechcook** [department-of-veterans-affairs/va.gov-cms#4316]
The vets-website non-master Veteran Facing (front-end) builds should not use PROD as the GraphQL API. 

The Chatbot team should have a demo environment that is updated once a day with Prod data to reduce the impact on the CMS prod infrastructure.

## AC:
- [x] a dedicated Tugboat Preview environment with GraphQL data no older that 24 hours exists and is ready to be used in vets-website non-prod builds
- [x] chatbot has a demo environment containing data from GraphQL no older than 24 hours

**Comment by ElijahLynn** [comment]
I set this up as a new project in Tugboat called "CMS PROD Mirrors". This way we can restrict resources to this project if needed. In addition, I setup the repo under the project to rebuild the base preview daily at 12am PT/3am ET and set it to rebuild all environments from that one whenever that happens. So, this alleviates the need for a Jenkins job to do this right now. The URLs are:

* https://cms-vets-website-branch-builds-lo9uhqj18nwixunsjadvjsynuni7kk1u.tugboat.vfs.va.gov/
* https://cms-chatbot-wkqpqcwm8dsm5hxcykskjh9psnjy1wia.tugboat.vfs.va.gov


![image](https://user-images.githubusercontent.com/1504756/110193638-f8cd7b00-7de9-11eb-8fde-a5387b2ed394.png)

**Comment by ElijahLynn** [comment]
> I setup the repo under the project to rebuild the base preview daily at 12am PT/3am ET and set it to rebuild all environments from that one whenever that happens.

I chose 3am ET because there is a downtime while the environments are rebuilt, which is currently about 2 minutes.

**Comment by ElijahLynn** [comment]
I just set the rebuild to hourly to test that the rebuilds did in fact happen on the hour and they did, you can see in this screenshot that the base was updated "11 minutes ago" and the two Previews that came from the base to be newer. This was entirely automatic and not manually triggered or interacted with. 

![image](https://user-images.githubusercontent.com/1504756/110194914-0128b480-7df0-11eb-89e4-dd6814f41a7c.png)

**Comment by indytechcook** [comment]
I'll start to socialize this to the other teams
