### ISSUE TITLE
Spike: Alternative approach to Hours field for Vet Center

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#4320]
Problems: 
* Hours field in VAMC is not well-structured content (it's currently using tablefield with some funky CSS hacks and default content to provide Mon-Sun labels)
* We need hours field on Vet Centers. 

How might we provide better structured content for Lighthouse and other API consumers, while providing the best possible editorial experience, encouraging content style guide compliant content, and including all the diversity required by our content

- Sometimes we specify the hours like "8:00 a.m ET - 4:30 p.m. ET"
- Sometimes the hours are "Closed" on certain days
- Sometimes the hours are "By appointment only"  on certain days
- Sunrise to sunset (Cemeteries)
- Sometimes we don't we use some combination of the above _and_ use the "other" field to say "on call 24/7"
- It's clear how to handle time zones in different circumstances... Can we assume that there's time zone data in the existing context? If not, are there means to ensure that time zone data is correctly entered? 

ACs
- [x] We have investigated contrib module that will support the following ACs
  - [x] Hours can be migrated in from VAST
  - [x] Hours supports all the diversity noted above
  - [x] Hours field supports editorial experience that contains guidelines and guardrails to ensure content style guide compliant content
  - [x] Hours is available in a meaningful way via Content API
- [x] If this seems like a viable path, create issue to replace field_hours on Vet Center content type with this approach.

**Comment by swirtSJW** [comment]
Explore:
https://www.drupal.org/project/office_hours
https://www.drupal.org/project/commerce_shopping_hours

**Comment by cmaeng** [comment]
Will require rewiring of migration in order to implement. Will icebox for now.

**Comment by swirtSJW** [comment]
We have to add hours to vet center migration so we should be acting on it.

**Comment by kaise-lafrai** [comment]
Devel output of office hours structure:

            [field_office_hours] => Array
                (
                    [x-default] => Array
                        (
                            [0] => Array
                                (
                                    [day] => 0
                                    [starthours] => -1
                                    [endhours] => -1
                                    [comment] => Closed
                                )

                            [1] => Array
                                (
                                    [day] => 1
                                    [starthours] => 900
                                    [endhours] => 900
                                    [comment] => 
                                )

                            [2] => Array
                                (
                                    [day] => 5
                                    [starthours] => 100
                                    [endhours] => 115
                                    [comment] => By Appointment Only
                                )

                            [3] => Array
                                (
                                    [day] => 6
                                    [starthours] => -1
                                    [endhours] => -1
                                    [comment] => By Appointment Only
                                )

                        )

                )

**Comment by kaise-lafrai** [comment]
### Recap

Contrib module used: https://www.drupal.org/project/office_hours

The office hours contrib module provides just the right amount of configuration to work as a good replacement to the the current facility hours table. The team determined the following during initial testing and research:

- Hours can be migrated in from VAST: Data from VAST can be massaged to fit into the following data Field Office Hours data structure:                ```
[day] => 6
                                [starthours] => -1
                                [endhours] => -1
                                [comment] => By Appointment Only
```

- [ ] Sometimes we specify the hours like "8:00 a.m ET - 4:30 p.m. ET"
- [ ] Sometimes the hours are "Closed" on certain days: `Field Office Hours provides a text field to enter additional details.`
- [ ] Sometimes the hours are "By appointment only" on certain days: `Field Office Hours provides a text field to enter additional details.`
- [ ] Sunrise to sunset (Cemeteries): `Field Office Hours provides a text field to enter additional details.`
- [ ] Sometimes we don't we use some combination of the above and use the "other" field to say "on call 24/7": : `Field Office Hours provides a text field to enter additional details.`
- [ ] It's clear how to handle time zones in different circumstances... Can we assume that there's time zone data in the existing context? If not, are there means to ensure that time zone data is correctly entered?: `Field Office Hours does not provide Timezone functionality. Existing code from D7 exists but has not been ported to D8. This will require additional research/implementation/testing.`


Hours field supports editorial experience that contains guidelines and guardrails to ensure content style guide compliant content: `The Field Office Hours module provides configuration to style the form and the display of the office hours. If anything specific is required we should track it as an AC and test it out.`

Hours is available in a meaningful way via Content API: Field Office Hours stores information in the following way:
Devel output of office hours structure:

            [field_office_hours] => Array
                (
                    [x-default] => Array
                        (
                            [0] => Array
                                (
                                    [day] => 0
                                    [starthours] => -1
                                    [endhours] => -1
                                    [comment] => Closed
                                )

                            [1] => Array
                                (
                                    [day] => 1
                                    [starthours] => 900
                                    [endhours] => 900
                                    [comment] => 
                                )

                            [2] => Array
                                (
                                    [day] => 5
                                    [starthours] => 100
                                    [endhours] => 115
                                    [comment] => By Appointment Only
                                )

                            [3] => Array
                                (
                                    [day] => 6
                                    [starthours] => -1
                                    [endhours] => -1
                                    [comment] => By Appointment Only
                                )

                        )

                )

**Comment by kaise-lafrai** [comment]
@kevwalsh Do we still want to throw the new field office hours in a tooltip group on all three content types?
