### ISSUE TITLE
Update VAST migration for Vet Center nodes 

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#4325]
## ACs
- [x] Vet Center nodes are updated with `hours`, `address`, `phone`. 
- [x] vc_ facilities ending in `MVC` are migrated to "Vet Center Mobile Vet Centers" content type (similar to Vet Center migration)
- [x] vc_ facilities ending in `OS` are migrated to "Vet Center Mobile Outstation" content type (similar to Vet Center migration)
- [x] TBD: what to do with Operating Status currently being added to Vet Center nodes for MVC and OS facilities. (see #4445)

-----
- [x] For facilities ending in `V`, check to see if a section exists that matches the facility name, and assign `field_administraiton` value to the Section term with that string. If that section does not exist, create it. 
   - [x] `Reno Vet Center` (facilityid `vc_0506V`) should be assigned to Reno Vet Center section (which already exists!). 
   - [x] `Oakland Vet Center` (facility id `vc_0612V`) should be assigned to Oakland Vet Center section (which does not exist!).

For facilities ending in `OS` and `MVC` 
- [x] assign a `field_office` value to its parent Vet Center, and its administration set to its parent Vet Center's section.
   - [x] Reno Mobile Vet Center `vc_0867MVC` should have field_vet_center set to NID 3774, and its section set to TID 393.
   - [x] Saint George Mobile Vet Center `vc_0868MVC` should have field_vet_center set to NID 3807, and its section set to "Saint George Vet Center" (TID TBD)

Sample data for migration

```"properties": {
                "id": "vc_0112V",
                "name": "Bloomfield Vet Center",
                "facility_type": "vet_center",
                "classification": null,
                "website": null,
                "address": {
                    "mailing": {},
                    "physical": {
                        "zip": "07003-2551",
                        "city": "Bloomfield",
                        "state": "NJ",
                        "address_1": "2 Broad Street",
                        "address_2": "Suite 703",
                        "address_3": null
                    }
                },
                "phone": {
                    "fax": "973-743-0380",
                    "main": "973-748-0980"
                },
                "hours": {
                    "friday": "800AM-430PM",
                    "monday": "800AM-430PM",
                    "sunday": "Closed",
                    "tuesday": "800AM-430PM",
                    "saturday": "Closed",
                    "thursday": "800AM-430PM",
                    "wednesday": "800AM-430PM"
                },
                "operational_hours_special_instructions": "Vet Center after hours assistance is available by calling 1-877-WAR-VETS (1-877-927-8387).",
                "services": {},
                "satisfaction": {},
                "wait_times": {},
                "mobile": false,
                "active_status": "A",
                "operating_status": {
                    "code": "NORMAL"
                },
                "visn": "2"
            }
```

**Comment by kaise-lafrai** [comment]
New process plugin for field hours: Reference VATablefieldHours.php

New process plugin to look for MVC or OS in field_facility_locator_api_id

**Comment by kaise-lafrai** [comment]
Notes: Entity generate plugin

**Comment by swirtSJW** [comment]
@kevwalsh THis AC is only loosely attainable with the data we have
```
assign a field_office value to its parent Vet Center, and its administration set to its parent Vet Center's section.
```
The method for this lookup happens like this

1. Take the api id from the thing coming in (in this case vc_0867MVC  or in the case of an outstation vc_0867OS
2. Replace the MVC or OS with V https://git.drupalcode.org/project/migrate_plus/blob/HEAD/src/Plugin/migrate/process/StrReplace.php
3. Then do the entity lookup with the resulting `vc_0867V`

The problem with this numeric assumption is that it assumes each parent can only have a maximum of  1 OS and 1 MVC because a second child could not have the same number as the parent.   

parent:      vc_0867V
M child1:   vc_0867MVC
O child1:   vc_0867OS
Child2 can not differ by prefix or suffix, so it gets a different number that is not related to the parent.

So from the migration point of view, second children will always end up as orphans.  The best we can do is log the failure to identify a parent and provide the list to a human orphanage manager.   This will be easy for all existing on the first runs. but we don't really have a mechanism in place to alert us about the arrival of a new orphan from the Facility API.

**Comment by kaise-lafrai** [comment]
@swirtSJW @kevwalsh I don't think I am getting any matches using the logic Steve mentioned above. 

Also, there isn't a sound solution for finding the Section associated with an MVC. Example Reno Mobile Vet Center should be assigned the section Reno Vet Center. Reno Vet Center term doesn't have a field I can reference to match any data associated with Reno Mobile Vet Center. We are not storing the id on the terms like we are on the nodes. This is a problem.

**Comment by kaise-lafrai** [comment]
Can I recommend we work on the last set of AC's on a separate ticket? It's clear to me now that this needs further research. Moving the following to a follow up ticket:

```
For facilities ending in OS and MVC

 assign a field_office value to its parent Vet Center, and its administration set to its parent Vet Center's section.
 Reno Mobile Vet Center vc_0867MVC should have field_vet_center set to NID 3774, and its section set to TID 393.
 Saint George Mobile Vet Center vc_0868MVC should have field_vet_center set to NID 3807, and its section set to "Saint George Vet Center" (TID TBD)
```

**Comment by swirtSJW** [comment]
OK so they are all orphans  We can't use numeric treatment then.   :(   

We are looking now to see if there are any consistency in naming.

**Comment by cmaeng** [comment]
Base migrations have been completed. With @swirtSJW OOO we will wait until he returns (3/22) to fully merge in.

**Comment by swirtSJW** [comment]
This was merged 
It has deploy steps that will need to be carried out soon after it is released on prod.
