### ISSUE TITLE
Implement improved error message for content release status tooltip

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-cms#4333]
## Description

This is a follow-on from #4331 

## Acceptance Criteria
- [ ] Finalized error message design is implemented
- [x] 👀 **Needs design review** because the work involves changes to labels or other design elements 
- [ ] 🙈 Can be implemented without consulting design team members

**Comment by TheBoatyMcBoatFace** [comment]
_We should close this_ 
❤️  @timcosgrove
