### ISSUE TITLE
Vet Center Community Access Point content type

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#4335]
## User Story or Problem Statement

~Much like VAMC System Facility Health Service content, Local editors of Vet Centers should be able to~

~1. Select what services are available at their Vet Center~
~1. Augment national descriptions of services with descriptions of their services specific to the facility~

The above was mistakenly copied over from another issue. 

User story:

As a Vet Center Outreach Associate, i can add a Community Access Point that helps Veterans access the CAP and its services. 

## Acceptance Criteria

Content type
- [x] "Vet Center Community Access Point" `vet_center_community_access_point` (or `vet_center_cap` if that's too long) 
- [x] Enable in content moderation
- [x] Enable in Sections workbench access
- [x] Permissions: All `content_*` roles can create.
- [x] Governance Details Sidebar fieldgroup fieldset  with Owner field (field_administration)
- [x] URL alias pattern: `[field_vet_center:url_alias]/community-access-point/[title]` 
- [x] Automatic entity title: `[Vet Center Name] - [geographical identifier]`
- [x] Alpha sort the menu item to create new Vet Center Community Access Point in the Administration menu (Content > Add Content > Vet Center Community Access Point should be 2nd from the bottom)

General info fields
- [x] `field_geographical_identifier` "Geographical identifier": to be used in Node title on Header on front end. *Required* **Added Feb 19: (Plain text single line field)**
- [x] "Vet Center" `field_vet_center` *Required* entity reference to Vet Centers. 
- [x] “Image” field `field_media`(Optional) - ~Guidelines about no people / no license plates, iphone ok.~ (no professional photographers like other facility images) **Updated help text, Feb 19: "Provide a photo if possible of the Community Access Point. Take a photo (with your phone is OK!) showing the CAP. Avoid including photos of people, or cars with license plates. Mobile phone photos are OK. Your image will be cropped to 3:2 aspect ratio, so it's best to upload a landscape photo."**

Location fields that may eventually end up in VAST 
- [x] "Located at"? `field_vet_center_cap_location` plain text field  *Required*
- [x] Address `field_address`, same as VAMC facility and Vet Center *Required*
- [x] `field_facility_hours`, same as VAMC facility and Vet Centers 
- [x] For MVP: No phone number field, the data we have so far is that any existing phone lines are not staffed, so they direct folks to main Vet Center.

**Comment by kaise-lafrai** [comment]
@kevwalsh 

> Alpha sort the menu item to create new Vet Center Community Access Point in the Administration menu (Content > Add Content > Vet Center Community Access Point should be 2nd from the bottom)

The Vet Center Community Access Point will belong at the very bottom below Vet Center menu item.

**Comment by kaise-lafrai** [comment]
@kevwalsh Can you explain more about this field: field_geographical_identifier

Is this a plain text field?

**Comment by kaise-lafrai** [comment]
@kevwalsh Initial creation and draft environment here for first pass in the review process: https://github.com/department-of-veterans-affairs/va.gov-cms/pull/4376

**Comment by kaise-lafrai** [comment]
@kevwalsh

**Comment by kevwalsh** [comment]
Hey Kaise, i updated the ACs a bit to clarify some things, and added a user story. This screenshot captures the diffs! 


![Create_Vet_Center_Community_Access_Point___VA_gov_CMS.png](https://images.zenhubusercontent.com/5d6e57ad330f64311395f08b/190eefb0-36be-484f-b867-49da0d9f776f)
