### ISSUE TITLE
[SPIKE] Determine cause of high CPU usage spikes in PROD RDS

### ISSUE THREAD

**Issue by ElijahLynn** [department-of-veterans-affairs/va.gov-cms#4351]
Timeboxed/Spike = 1 day 

![image.png](https://images.zenhubusercontent.com/5cdc72c50b7efe3f164150b2/4c59671d-163f-448b-8172-f63b76d27714)

AC: 
- [ ] Determine cause of high CPU spike so that we can fix it with application or infrastructure changes

Resources:
1. https://www.percona.com/blog/2019/03/07/reducing-high-cpu-on-mysql-a-case-study/ and https://www.percona.com/blog/2020/04/23/a-simple-approach-to-troubleshooting-high-cpu-in-mysql/
2. https://www.percona.com/blog/2020/04/23/a-simple-approach-to-troubleshooting-high-cpu-in-mysql/ for how to look at high CPU and what it means 
3. http://grafana.vfs.va.gov/d/dxf8a-6Zz/cms-dashboard?orgId=1&from=1613507656847&to=1613516851546&var-datasource=Prometheus%20(Utility)&var-environment=prod&var-app_name=cms&var-region=us-gov-west-1

**Comment by indytechcook** [comment]
I spent 5 minutes to look at the innodb queries running and dove deep into a few.  I noticed the amount of data being returned on the query to load route and container information from the cache table is extremely large.  I'm not sure if this is anything yet just something to keep an eye on.

**Comment by ElijahLynn** [comment]
Also of note is that the Link Report checker does a mini-ddos on the site as an anonymous user.

**Comment by ElijahLynn** [comment]
The high spikes appear to be caused by each PR/branch test run for vets-website. They run a DEV/STAGING/PROD CMS build which all point to PROD (as we requested a while ago, this is expected).

We can see a correlation for the branch tests of http://jenkins.vfs.va.gov/blue/organizations/jenkins/testing%2Fvets-website/detail/fix%2Freplace-omit-debug/5/pipeline with the Grafana screenshot (Pacific Time, 6:30am, UTC

Here is 1 vets-website branch build happening at the time of an RDS spike, which correlates to a large increase in RDS CPU and connection count. Each branch build triggers 3 ENV tests which are 15 parallel GraphQL requests at ~181 queries each. So for a single branch build we have 45 parallel requests hitting CMS PROD for 543 queries.  

We can mitigate this short-term by reducing the parallelization limit from 15 to maybe 10 for vets-website CI builds which was a new feature just added by @ncksllvn yesterday in https://github.com/department-of-veterans-affairs/vets-website/pull/16247. Maybe we should consider reducing it for the actual PROD release (all builds) too?

And the long-term mitigation is to remove the above parallelization limit that when we move all the vets-website CI builds to point at a Tugboat instance in https://github.com/department-of-veterans-affairs/va.gov-cms/issues/4316. 


DEV BUILD > PROD CMS:
http://jenkins.vfs.va.gov/blue/rest/organizations/jenkins/pipelines/testing/pipelines/vets-website/branches/master/runs/10286/nodes/97/steps/118/log/?start=0
```
[2021-03-04T15:20:08.212Z] Step 3 of 29 start: Get Drupal content
...
[2021-03-04T15:24:23.619Z] Finished 181 queries in 255s with 2309 pages
[2021-03-04T15:24:23.619Z] http://internal-dsva-vagov-prod-cms-2000800896.us-gov-west-1.elb.amazonaws.com response time: : 4:15.355 (m:ss.mmm)
[2021-03-04T15:24:24.182Z] Total time to load content from GraphQL: 4:15.932 (m:ss.mmm)
```

PROD BUILD > PROD CMS:
http://jenkins.vfs.va.gov/blue/rest/organizations/jenkins/pipelines/testing/pipelines/vets-website/branches/master/runs/10286/nodes/99/steps/120/log/?start=0
```
[2021-03-04T15:24:44.046Z] Step 3 of 29 start: Get Drupal content
...
[2021-03-04T15:25:43.808Z] Finished 181 queries in 59s with 2309 pages
[2021-03-04T15:25:43.808Z] http://internal-dsva-vagov-prod-cms-2000800896.us-gov-west-1.elb.amazonaws.com response time: : 59.873s
[2021-03-04T15:25:44.369Z] Total time to load content from GraphQL: 1:00.436 (m:ss.mmm)
```

STAGING BUILD > PROD CMS:
http://jenkins.vfs.va.gov/blue/rest/organizations/jenkins/pipelines/testing/pipelines/vets-website/branches/master/runs/10286/nodes/98/steps/119/log/?start=0
```
[2021-03-04T15:24:43.138Z] Step 3 of 29 start: Get Drupal content
...
[2021-03-04T15:25:43.817Z] Finished 181 queries in 60s with 2309 pages
[2021-03-04T15:25:43.817Z] http://internal-dsva-vagov-prod-cms-2000800896.us-gov-west-1.elb.amazonaws.com response time: : 1:00.851 (m:ss.mmm)
[2021-03-04T15:25:44.377Z] Total time to load content from GraphQL: 1:01.440 (m:ss.mmm)
```

![image](https://user-images.githubusercontent.com/1504756/109994847-8f9f1800-7cc2-11eb-9924-625fb7427251.png)

**Comment by ncksllvn** [comment]
We can probably reduce it for all vets-website branches, but increase it during actual content deployments

**Comment by ncksllvn** [comment]
Maybe only five parallel requests in vets-website CI, but a whopping _50_ during a content deployment? 😁

**Comment by ElijahLynn** [comment]
> We can probably reduce it for all vets-website branches, but increase it during actual content deployments

This would would be good in the short term. However, once we get to a Tugboat environment the requests will be faster and therefore shorter lived because of lower latency w/local MySQL (not external RDS), and the environment having access to 24 cores vs 8 on the RDS. Therefore I think we would be able to remove the limiting and go back to 15 parallel requests for the Tugboat shift. 

It would be a big load off our PROD server to get something in to reduce to <10 parallel requests now for vets-website branches. Can you make a PR for that @ncksllvn?
