### ISSUE TITLE
Spike: replace spec tool with custom views

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-cms#4357]
## Hypothesis
The business value of the [spec tool](https://docs.google.com/spreadsheets/d/1vL8rqLqcEVfESnJJK_GWQ7nf3BPe4SSevYYblisBTOI/edit#gid=943298572) and [its auto-generated tests](https://github.com/department-of-veterans-affairs/va.gov-cms/tree/master/tests/behat/drupal-spec-tool) can be fully replaced by custom views, eliminating drift between the two sources of truth and reducing on-going developer effort + hassle.

## Acceptance Criteria
- [ ] business value of spec tool is identified
- [ ] business value of auto-generated spec tool tests is identified
- [ ] a decision is taken as to whether to replace the spec tool + auto-generated tests with custom views
  - If yes:
  - [ ] Needed views & fields are defined
  - [ ] Any needed automated tests are defined

## Background
[internal] [slack thread](https://dsva.slack.com/archives/CT4GZBM8F/p1613510922205100)

## Spike participants

**required:**
@nataliedunbarCS @kevwalsh @oksana-c @acrollet @ndouglas 

**optional:**
@swirtSJW @indytechcook @kaise-lafrai @ethanteague @mchelen-gov

**Comment by oksana-c** [comment]
recent user story:

As a VFS Product team engineer, who has access to GraphQL endpoint and has read-only access to Drupal UI (e.g. view nodes, but no access to the technical field structure), I need access to clear description of a content model per content type, so that I know which fields I should query via Content API.

**Comment by kevwalsh** [comment]
> recent user story:
> 
> As a VFS Product team engineer, who has access to GraphQL endpoint and has read-only access to Drupal UI (e.g. view nodes, but no access to the technical field structure), I need access to clear description of a content model per content type, so that I know which fields I should query via Content API.

Related to this user story, not in an epic: 

https://github.com/department-of-veterans-affairs/va.gov-cms/issues/4509

**Comment by ndouglas** [comment]
Might be worth discussing existing tests that could be replaced or augmented by the spec tool or its replacement (see e.g. `va/tests/check-cer`).  `va/tests/revision-log` has requirements that I think can't be expressed in Spec-Tool, but might be expressible in some other form.
