### ISSUE TITLE
Pre-configure environments for GraphQL load testing

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#4362]
As an FE Tools Engineer, I want to have several `pages.json` that reflect various content volume increments, so that I can efficiently test the part of the Content Build that I maintain.

## Acceptance Criteria
- [x] Estimate projected number of nodes per VAMC to understand total number of nodes required over time based on the VAMC upgrade roadmap (COMPLETE - [see estimate here](https://docs.google.com/spreadsheets/d/1pa0EgHuOXINvool4QHjV3lIDyYf-p9JRr8z1AuW4HFE/edit#gid=106613017))
- [x] load testing environments are ready and have hundreds of thousands of nodes to benchmark each content volume increment
- [x] `pages.json` files with several content volume increments are shared with FE Tools team

**Comment by indytechcook** [comment]
The sql fiels and pages.json files are stored in AWS bucket: `dsva-vagov-prod-cms-backup-sanitized`

The follow was communicated to the front end team

> I was able to generate larger node count Drupal environments and pages.json by mass cloning the nodes associated with VISN2 and VISN4
> * 14228 nodes: https://dsva-vagov-prod-cms-backup-sanitized.s3-us-gov-west-1.amazonaws.com/benchmark/14228-pages.json
> * 22410 nodes: https://dsva-vagov-prod-cms-backup-sanitized.s3-us-gov-west-1.amazonaws.com/benchmark/22410-pages.json
> * 50658 nodes: Timed out at GetNodeHealthServicesListingPage__slice35
> I attached the graphql query output (with some additional logging); https://github.com/department-of-veterans-affairs/va.gov-cms/issues/4215#issuecomment-786714598.  The 50658 node run was with a concurrency of 2
> Next Steps
> * Setup the 50K node count on cms-test so we all can hit it.
> * Sync with Nick/Tim/Michael to understand how the pages.json file is used in the templates.  Then evaluate how the queries are being made to see how this can be done more efficiently.

**Comment by mchelen-gov** [comment]
@indytechcook are the datasets and bucket documented somewhere in the READMEs?

**Comment by indytechcook** [comment]
> @indytechcook are the datasets and bucket documented somewhere in the READMEs?

they will be...

**Comment by indytechcook** [comment]
PR: https://github.com/department-of-veterans-affairs/va.gov-cms/pull/4470

**Comment by mchelen-gov** [comment]
to confirm, this ticket is to create the sample datasets and #4215 is to benchmark in cms test env?

**Comment by indytechcook** [comment]
Correct.

**Comment by indytechcook** [comment]
Linking https://github.com/department-of-veterans-affairs/va.gov-cms/blob/master/READMES/scalability.md
