### ISSUE TITLE
Read-only replica of the database [Drupal]

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#4365]
## Acceptance Criteria
- [ ] GraphQL queries during content build process use read-only replica of the database to protect from race conditions and reduce strain on prod infrastructure
- [ ] database query services configured to use read-only replica
- [ ] performance tested

https://elabee.me/drupal-entity-query-db-replica/

**Comment by ElijahLynn** [comment]
> Per hackathon 3/24, the team a> Per hackathon 3/24, the team agreed to stop work on this and switch gears to memcached.

Further explanation of this is here > https://github.com/department-of-veterans-affairs/va.gov-cms/issues/4461#issuecomment-807096110.

**Comment by EWashb** [comment]
this is no longer within scope
