### ISSUE TITLE
SPIKE: How to handle changes in facility data from Lighthouse (name, data removal, etc)

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#4369]
Needs to be added to epic #4856 

## User Story or Problem Statement

Administrators of upstream facility databases (VAST, VBA_facilities database in the CDW) may make changes to facility names, which are migrated on a nightly basis, usually into node titles. 

> This becomes probably a bit more likely in the world of Vet Centers. Jessica is working on stats for me now for how frequently this happens, but generally they are in strip-mall esque rental space and sometimes they need to move b/c of expiration of lease etc. So the "Longmeadow Vet Center" could become the "Palmer Vet Center" because they moved 4 miles down the road and changed towns/cities.

How should the CMS handle facilty name changes? What should change about the content about that facility stored in the CMS, if anything? 

- h1 / Title
- URL alias
- the h1 and and URLs for related content that may leverage Facility name, such as Services, Outstations, CAPs, etc.
- facility disappears from upstream database

Are there any manual processes required, such as

- Review name change
- Update aliases manually
- Add redirect, if URL will change
- Update the Section name for this Vet Center
- etc.

## Acceptance Criteria
-  Spike to understand CMS role in change management of Facility names
  - [x] [identify current risks](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/4369#issuecomment-926194385) 
  - [x] Assess risk of Pathauto rules for published content 
      - Risk of divergence here because VAMC facilities paths are based on menu title so they do not shift with a simple name change, but vet center paths are based on node title.
- Governance and business processes written and agreed to by @davidconlon 
   - https://github.com/department-of-veterans-affairs/va.gov-cms/issues/6523 
   - #6524
   - #6525
   - #6526
- [x] #6527
   - https://github.com/department-of-veterans-affairs/va.gov-cms/issues/6517
   - https://github.com/department-of-veterans-affairs/va.gov-cms/issues/6518
   - https://github.com/department-of-veterans-affairs/va.gov-cms/issues/6519
   - https://github.com/department-of-veterans-affairs/va.gov-cms/issues/6520
   - https://github.com/department-of-veterans-affairs/va.gov-cms/issues/6522
   -  #6528
   -  #6529
   - #6530
   - #6531
- [x] Update documentation in https://github.com/department-of-veterans-affairs/va.gov-cms/blob/master/READMES/migrations-facility.md as needed. https://github.com/department-of-veterans-affairs/va.gov-cms/pull/6516

## Possible short term

- [ ] Create different drupal users for each type of migration to better differentiate operating status changes from Facility API changes
   - Is the current method where CMS migrator does both the data changes and the status changes.?  The revision log messages declare what was done.   
- [x] Evaluate changing the moderation state to draft if migrator detects certain data changes, instead of maintaining existing moderation state.  
   - This solution would lead to confusing issues where there is a change waiting to go but would not go until any editor published the latest revision. ... which could have other impact for sites not in full CMS production because their statuses are updated via different migration... and those can not be held in draft for a published facility.
- [x] Research whether URL alias changes when h1 changes during migration  
   - VAMC facilities do not because the alias is based on menu title which does not change automatically.
   - Vet Centers of all types do, because they have no menu and their paths are name based.

**Comment by kevwalsh** [comment]
Tagging this as "Good first task", assuming it's done with @swirtSJW to help with knowledge transfer on the broader migration approaches.

**Comment by swirtSJW** [comment]
### Current issues related to data changes made in Facility API

1. A title change to a facility will change the title of the node at midnight, which has a cascading problems of:
    1. Nobody knows it changed. - (lack of alert)
    2. The alias for the facility changes only if we intentionally update the alias for that section (by hand).  There is some risk that this could be done inadvertently but it is typically only something we do during dual state.  These paths only impact drupal navigation as VAMC facilities have no sub pages. Vet centers on the other hand would be affected because they are top tier pages that have other pages underneath them. 
       1. When paths are updated Redirects in the CMS are created, but  VA.gov does not know about them so any existing links outside the site fail to work.
    4. Names in the menu for facilities are not updated, so the two titles  will differ.   
2. A removal of a facility from the facility API is not operated on, no action is taken in the CMS and no-one is notified. Removal is done by hand under a request fulfillment.
3. The appearance of a new facility in the facility API creates a new facility in the CMS within 24 hrs.  
   1. No one is notified.  You can only find it if you go looking for it.  
   2. It is not connected to a system as the system affiliation is not in the facility API.

**Comment by cmaeng** [comment]
Closing this ticket out as the research has been completed. #4856 will track the follow-up needed.
