### ISSUE TITLE
Vet Center Dashboard - Local editor

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#4386]
### User Story or Problem Statement

As a Vet Center editor, i have quick access to accomplish tasks in the CMS, and i'm guided to "top tasks" based on various criteria like frequency, Vet-centeredness, etc, TBD.

**Comment by jordanamello** [comment]
[Link to prototype in Figma](https://www.figma.com/file/885DMraAi9V2DLJnrIN7Wv/Vet-Centers?node-id=0%3A1)
