### ISSUE TITLE
Improve help text about aspect ratio and cropping for CLP image

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#4391]
## User Story or Problem Statement

As a Campaign Landing Page editor, i want clear guidelines on creating, uploading, and cropping imagery for my CLP.

![Edit_Campaign_Landing_Page_VA_Solid_Start___VA_gov_CMS](https://user-images.githubusercontent.com/643678/108807401-4fc58b80-7572-11eb-8d00-8bce41a244fb.png)

## Acceptance Criteria
- [ ] TBD, may depend on other Cropping UX issues such as #3969.

## Implementation steps
TBD

**Comment by EWashb** [comment]
closing in favor of #8755
