### ISSUE TITLE
Require or guide consistent use of images in Story panel of CLP

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#4392]
## User Story or Problem Statement

When editors add two stories to the Stories segment: HMW guide editors to add images to both stories, or to neither? 

- form validation? 
- if not, then help text? 

## Acceptance Criteria
- [ ] TBD

## Implementation steps
TBD

**Comment by kevwalsh** [comment]
Decision March 15: deprioritize this for now until we have more info.

**Comment by FranECross** [comment]
Closing old ticket
