### ISSUE TITLE
SE: The CMS Notifications framework

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#4395]
## Background

Previous work on this functionality was addressed as integration with VANotify. It has been determined that MVP for CMS notifications can be implemented with a simpler architect through Messages Stack module from #8721. The scope of this work no longer includes VANotify integration. 

## Problem Statement

Current state as of 2nd quarter 2022 is the email notifications MVP implemented as part of #9097. The path forward includes:

- Setting up slack notification functionality 
- Determining what event triggers what type of notification for which products
- Determining the user stories for this and deciding how best to do research with a beta test group of editors regarding what notifications are needed, when they are needed, and how often they would want them
- Addressing broken links with notifications
- Change management review and RACI to determine when product teams use this tool and the governance around it. 

## 2021 Roadmap (no longer applicable)
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/content-ops/editorial-workflow/notifications/roadmap.md

**Comment by EWashb** [comment]
This will be the new parent epic of current state CMS notifications.

**Comment by EWashb** [comment]
@productmike this super epic is in progress with the implementation of #10477. However, you might find it useful to update the description and other information written above.

**Comment by EWashb** [comment]
Add issues within this epic have been completed!
