### ISSUE TITLE
Content API Scaling and Performance - Q2 2021

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#4396]
## Background

A decision was made to invest into GraphQL performance and scalability - see background in https://github.com/department-of-veterans-affairs/va.gov-team/issues/20165 

The overall goal is to support content build times of less than an hour with 50k published nodes by the end of Q2 2021.

### Problem Statement

Platform teams are aiming to decrease publish times to meet the needs of VFS teams .

The CMS team can contribute to the effort by ensuring that Content API / GraphQL is running on a performant and scalable infrastructure and serve as consultants in the effort to optimize GraphQL queries that currently used in the content build pipeline.

### Definition of Done

- The CMS infrastructure that supports GraphQL is stable and performant
- GraphQL multi-query performance and scalability is assessed by by thorough benchmarking based on the expected influx of content
- CMS builds are adjusted to follow hourly content release processes and all related builds are passing successfully

## Assumptions
- The CMS's contribution to the total build time is roughly 50%, and can be measured using GraphQL query time as a proxy

## Acceptance Criteria
- [ ] Content build GraphQL requests for 50,000 published nodes are always served in 30 minutes or less

## Related
Overall content release time is dependent on ongoing content build scaling work: https://github.com/department-of-veterans-affairs/va.gov-team/issues/22365

**Comment by mchelen-gov** [comment]
AC notes:

node = published node in drupal
gql time = graphql query time in content build

current status:
12500 nodes
76 sec gql time
= 0.00608 sec/node

projected 50k nodes = 304 sec gql time = 5.06 min

target:

maximum time for 50k nodes =  0.036 sec/node

AC = 75% or less of 0.036 sec/node for 2+ weeks
= 0.027 sec/node gql time

**Comment by acrollet** [comment]
Closing this initiative out based on observed performance for the past 2+ weeks in collaboration with @mchelen-gov .
