### ISSUE TITLE
Setup alert if application instance CPU load goes above 70% for 3 minutes

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#4397]
Related to #4170 

## Acceptance Criteria
- [ ] Alert Slack and Pager Duty if application instance CPU load goes above 70% for 3 minutes on PROD

## Implementation notes 

* Consider using Alert Manager w/Prometheus

**Comment by ElijahLynn** [comment]
PR for this is here > https://github.com/department-of-veterans-affairs/devops/pull/8587

**Comment by ElijahLynn** [comment]
This has been merged, deployed and tested! I have tested it with `sudo stress --cpu  14 --timeout 500`on DEV and we now are getting this notification to `#cms-notifications` in Slack: 

![image](https://user-images.githubusercontent.com/1504756/109561654-56806100-7a92-11eb-988d-273c8bf5b3dd.png)

Here is the Grafana load 
![image](https://user-images.githubusercontent.com/1504756/109561718-6b5cf480-7a92-11eb-8729-73c9b9d0cf2a.png).

**Comment by ElijahLynn** [comment]
Just tested manually on PROD at 75% load with `sudo stress --cpu 12 --timeout 300` and it triggered the PagerDuty alert after 4 minutes, which makes sense since it might check on full minute marks. 

![image](https://user-images.githubusercontent.com/1504756/109573459-f7c3e300-7aa3-11eb-8dad-0b4a8aaabd64.png)

![image](https://user-images.githubusercontent.com/1504756/109573424-dd8a0500-7aa3-11eb-8e11-16779c7049e8.png)

**Comment by ElijahLynn** [comment]
We won't get notifications in #cms-notifications for this just yet as we need a PagerDuty admin to re-route the Slack integration from #cms-engineering (old name) to our new team channel #cms-team.

**Comment by ElijahLynn** [comment]
> Going to make upstream ticket now.

https://github.com/department-of-veterans-affairs/va.gov-team/issues/20635

**Comment by ElijahLynn** [comment]
Also, the performance of https://prod.cms.va.gov/admin/content was only marginally affected, maybe tops by ~50ms, during this 75% load test. 
![image](https://user-images.githubusercontent.com/1504756/109574871-90a72e00-7aa5-11eb-9e4f-998efc080737.png)

**Comment by ElijahLynn** [comment]
This is the message that was up during testing: 
![image](https://user-images.githubusercontent.com/1504756/109575193-2e026200-7aa6-11eb-9dbc-5e0eae118233.png)
