### ISSUE TITLE
Update Demo Environments suspension time to 14 days

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#4398]
Related internal Slack threads:
vamc-upgrade-team - https://dsva.slack.com/archives/CPQFCQKEH/p1614097124015800
tugboat-support - https://dsva.slack.com/archives/C01A35JDH88/p1614099897001100

## Acceptance Criteria
- [x] demo environments in Tugboat do not suspend until 14 days have passed since last activity [@ElijahLynn ]
- [x] all demo environments are unsuspended / activated [@oksana-c ]

Also, see @q0rban 's suggestion for a shell script to activate envs within a projects - https://dsva.slack.com/archives/C01A35JDH88/p1614103329007300?thread_ts=1614102359.004000&cid=C01A35JDH88

**Comment by ElijahLynn** [comment]
Looks like we can only increase the "suspend idle previews" option per project and not per repo. So this means all PR environments too.

**Comment by ElijahLynn** [comment]
I ran `tugboat update 5fd3b8ee7b465711575722d5 sleep=20160` to update the project to 2 weeks/14 days/20160 minutes and woke up all the DEMO environments.

**Comment by ElijahLynn** [comment]
Still 30GB of memory left: 
![image](https://user-images.githubusercontent.com/1504756/108944855-71755000-7610-11eb-93a8-1e7845147751.png)

**Comment by oksana-c** [comment]
thanks @ElijahLynn !
not ideal for PRs, but I think we can deal w/ that okay since PRs are short-lived.
curious if you were able to use the shell script that James offered for activating all envs or went manual route?

**Comment by ElijahLynn** [comment]
> curious if you were able to use the shell script that James offered for activating all envs or went manual route?

I just went the manual route, as it was faster than looking up the script I made.

**Comment by acrollet** [comment]
> PRs are short-lived.

"ideally" 😅
