### ISSUE TITLE
Draft Vet Center MVP local editor training

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#4401]
## User Stories

1. As a Veteran, I need to search for services so that I can successfully transition from military to civilian life or find assistance after a traumatic event.
2. As a family member of an active duty service member, I need to find supportive services for issues related to my loved one's military experience.
3. As Vet Center staff, I need to be able to provide information to support the needs of Veterans and their family members.

## Acceptance Criteria

- [x] Draft training slides

**Comment by xiongjaneg** [comment]
Kev reviewed 3/24/21. Sent to Dave for review 3/25/21 via Slack.
