### ISSUE TITLE
Deliver local editor training to national Vet Center staff

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#4402]
## User story
As a local Vet Center editor, I need to be able to provide services and facilities information to Veterans and their families.

## Acceptance Criteria
- [x] Develop training slides
- [x] Review training slides
- [x] Revise training slides
- [x] Deliver training for national editors

**Comment by xiongjaneg** [comment]
completed May 13, noon ET, with 5 national editors, Dave, Michelle, Leyda, and Kev

Notes at https://docs.google.com/document/d/1Y5YquioCKADBXEm8iEolf-awek9bxB6SIxchsfV8dlw/edit?ts=609d5dda
