### ISSUE TITLE
Document Vet Center content model for Facilities team

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#4408]
As a FE developer, i have access to content model documentation to support my development of liquid templates and graphql queries. 

ACs

By March 19th
- [ ] Visual annotation of design (such as in a MURAL) showing fields/field names and or bundles, similar to [CLP content model documentation](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1607363793772/b7f9e809d68ace9c8d75ab649a758ed7653c8461)

By March 22nd
- [ ] Facilities team has reviewed and has enough information to get started.

**Comment by nataliedunbarCS** [comment]
Draft documentation already in progress: https://app.mural.co/t/vagov6717/m/vagov6717/1614274642123/3509c33494d6dbc74e362cfe458dc5f2a517ec39
