### ISSUE TITLE
Nearby Vet Centers field on Locations list

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#4419]
[It might be good to combine this with #4428]

Local editors should be able to choose nearby Vet Centers (but not nearby MVCs or Outstations) to display on the Vet Centers Locations page.

## ACs
- [x] `field_nearby_vet_centers` "Select nearby Vet Centers" entity reference field allowing only Vet Center nodes.
- [x] Allow unpublished entities. 
- [x] Autocomplete form widget.

**Comment by kaise-lafrai** [comment]
@kevwalsh This work is part of this PR: https://github.com/department-of-veterans-affairs/va.gov-cms/pull/4468
