### ISSUE TITLE
Vet Center FAQ (up to 5)

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#4420]
National editors of Vet Center content should be able to create and edit (up to 5?) FAQs that display at the bottom of Vet Center pages

Content structure:
* header or the question
* Limited rich text field for the answer 
* Character counts TBD

 ![Vet_Center_Product_-_UXPin_Preview.png](https://images.zenhubusercontent.com/5d6e57ad330f64311395f08b/dec6029b-8bf2-4fac-96b3-7be5eb8508d5)

## ACs

- [ ] National editors can create and edit up to 5 FAQs on node/16142 
- [ ] Content is displayed in some fashion on Vet Center node with EFF, design TBD

## Possible implementations

1. Reuse R&S Q&A content type. But only "Content creator - Resources and Support" editors can create. 
2. **Reuse the existing, complex Set of Q&A paragraph bundle. But this has way too many options (you can answer a question with a react widget!)** 
3. New, simplified non-reusable Q&A paragraph type.

**Comment by kevwalsh** [comment]
@swirtSJW i've gone with implementation #2, which means no further engineering work for now. 

You can review it at https://prod.cms.va.gov/centralized-content/national-vet-center-content (node 16142).  The biggest risk with this approach is that it would give tools to national editors that we may not want them to have, like using paragraph types that are available as Answer types.  One advantage of this approach is that it already has the Section header and intro fields. 

![Edit_Centralized_Content_National_Vet_Center_content___VA_gov_CMS](https://user-images.githubusercontent.com/643678/109543632-8af51c80-7a94-11eb-979e-9ce4fb621265.png)

Any thoughts about followups here? We could alter the Q&A form for this particular node form, but that seems a bit too "special".

**Comment by swirtSJW** [comment]
I don't think there is any followup here.   The UI cleanup would likely be very specialized for just that node.   I am not sure if it is worth the effort.   Once we go down that road, we'd have to do specialized for all of them.  It would get messy fast.
