### ISSUE TITLE
Investigate why Tugboat load spiked with 70+ previews unsuspended

### ISSUE THREAD

**Issue by ElijahLynn** [department-of-veterans-affairs/va.gov-cms#4434]
## Description
As a result of #4398, unsuspending 70+ environments caused CPU load to spike up to 80 (36 vCPU) and the server became unusable causing tests to fail. Attached is a screenshot of a partial `htop` during the time of peak load:

![image](https://user-images.githubusercontent.com/1504756/109048795-57795300-768c-11eb-964f-726004c480c4.png)

The `command runner` seems to be a likely culprit.

**Comment by acrollet** [comment]
Closing, haven't seen this happen again.
