### ISSUE TITLE
Limit content release tooltip environment to appropriate environments

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-cms#4437]
## Description

This is a follow-on to #4319. 

Without refactoring the service that gives us the FE URL, each environment will show the last content release for that environment. So, when on prod, you would see the last content release to www.va.gov as expected. However, staging would show the last release to staging.va.gov, and so on. Without a fair bit more work, nothing would be shown on tugboat/local environments.

Here are our main choices:

- disable the tooltip on all environments except BRD, and let each of prod/staging/dev show the last content release for that environment. (If this is acceptable, the wording will need to be updated for staging/dev.)
- keep the behavior as it is now, showing the last production content release time on all environments.

ACs:
- [ ] [UX] identify the correct environment(s) on which to show the tooltip
- [ ] [Engineering] limit the tooltip display to that/those environment(s)

**Comment by acrollet** [comment]
Copying @rachel-kauff's comment from the previous issue:

@acrollet cc: @jordanamello I suspect that making this tooltip serve different scenarios/environment could confuse things.

I suspect we should keep it to appear just on prod so that its primary purpose is to answer the question, "when did my content last go live in the world?" (so that might be option 1ish - disable tooltip everywhere except prod)

Without a lot more UI design work to unpack some more of our decoupled concepts, this could get really tricky.

Thoughts?

**Comment by TheBoatyMcBoatFace** [comment]
Not a focus.
