### ISSUE TITLE
VAMC locations UX

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#4440]
This epic needs refining, but will be the home for a number of user stories, including 

As a VAMC system editor, i can select "VAMC facilities" in an intuitive way, in an intuitive context (the Locations List page, not the main system node.

We could align the UX with what was done for Nearby Locations on Vet Center. 

### Current VAMC UI (MVP from original Pittsburgh launch)

On VAMC System content type, but should be done from VAMC System Locations List type (see #3488)

![Edit_VAMC_System_VA_Pittsburgh_health_care___VA_gov_CMS.png](https://images.zenhubusercontent.com/5d6e57ad330f64311395f08b/f755055b-805a-40d8-baaa-50f6d9b3b9f6)

### Vet Center 

On Vet Center Locations List content type .

![Edit_Vet_Center_-_Locations_List_Locations___VA_gov_CMS.png](https://images.zenhubusercontent.com/5d6e57ad330f64311395f08b/7268ee38-e119-446d-8ac2-0c4b459e4628)
![Edit_Vet_Center_-_Locations_List_Locations___VA_gov_CMS.png](https://images.zenhubusercontent.com/5d6e57ad330f64311395f08b/e37b5191-bd38-4d93-9924-faf96e866c61)

**Comment by VanessaLuxen** [comment]
Relates to Jira ticket: https://va-gov.atlassian.net/jira/servicedesk/projects/VAHELP/queues/custom/11/VAHELP-455

**Comment by mmiddaugh** [comment]
Closing in lieu of [#13896 [CONSIDER] Revisit logic governing "Other nearby VA locations" on VAMC pages](https://app.zenhub.com/workspaces/sitewide-facilities-639f5253e4b702a32376339e/issues/gh/department-of-veterans-affairs/va.gov-cms/13896)
