### ISSUE TITLE
Remove un-used modules/packages

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-cms#4451]
## Description

Various modules are being disabled as part of the push to get ready for Drupal 9. Rather than having to create 2 PRs for each module removed, let's remove all unused modules at the conclusion of the process.

### Packages to be removed
- `drupal/computed_field`
- `drupal/field_formatter`
- `drupal/markdown`
- `drupal/mass_pwreset`
- `drupal/openapi`
- `drupal/openapi_ui`
- `drupal/openapi_ui_redoc`
- `drupal/openapi_ui_swagger`
- `drupal/rest_menu_tree`
- `drupal/schemata`
- `drupal/simple_oauth`
- `drupal/views_infinite_scroll`
- `drupal/views_tree`
- `michelf/php-markdown`

## Acceptance Criteria
- [ ] Packages are removed and all tests pass

**Comment by ndouglas** [comment]
One-liner for getting the list of modules required directly in `composer.json` that don't correspond to enabled modules in `core.extension.yml`.  Not an absolutely reliable arbiter of truth, beauty and love, but a good starting point, and one I don't care to figure out again.

```bash
comm -23 <(jq -r '.require | keys[] | select(. | contains("drupal/")) | sub("drupal/";"")' composer.json) <(yq r config/sync/core.extension.yml 'module' -j | jq -r 'keys[]')
```
