### ISSUE TITLE
Content editor/reviewer/publisher can archive anything in their section, but not delete anything

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#4453]
**Describe the defect**

**To Reproduce**
As content_publisher, go to a staff profile. You can delete it.

**Expected behavior**
You shouldn't be able to delete it. 

Other tech debt we can address as part of this.

- [x] content_publisher should not be allowed to delete anything, even their own
- [x] content_admin should have no redundant permissions, nothing that's also part of "bypass content permissions" (create/edit/delete)
- [x] content_admin should have "administer media" 
- [x] content_editor should not have "delete media"
- [x] content_reviewer should not have "delete media"
- [x] Document - External: "editor/reviewer/publisher" should all have "edit any".
- [x] no roles should have "edit own [thing]", that's redundant because they should have "edit any [thing]"

![Screenshot_2021-03-16__12_42_PM](https://user-images.githubusercontent.com/643678/111347130-49986b80-8655-11eb-9245-9c4366074655.png)

**Comment by ethanteague** [comment]
Covered by https://github.com/department-of-veterans-affairs/va.gov-cms/pull/4711
