### ISSUE TITLE
Re-enable Elastic File System (EFS) for Drupal asset storage

### ISSUE THREAD

**Issue by ElijahLynn** [department-of-veterans-affairs/va.gov-cms#4457]
We had removed EFS for Drupal file assets for CMS-Export performance and we were going to solve a complicated file system issue that this caused such as the limitation of horizontally scaling. Now that CMS-Export is removed and we are no longer pursuing that approach we can move back to using EFS for the file assets. 

AC:
- [x] EFS volumes are mounted to instances on deployments
- [x] Volumes have appropriate IOPS allocated
- [ ] Previous asset and cms-export state in S3 is cleaned up

TASKS:
- [x] Get EFS FS mounted again https://github.com/department-of-veterans-affairs/devops/pull/8675
- [x] Create migration job/scripts https://github.com/department-of-veterans-affairs/devops/pull/8675
- [x] Test file backup time, adjust deploy site-alert time appropriately > https://github.com/department-of-veterans-affairs/va.gov-cms/issues/4457#issuecomment-796306202
- [x] Test vets-website CMS asset step fetch time inside network and SOCKS
- [x] Deploy runbook
  - [x] Set 10 minute WARN 'medium' deploy-alert site alert
  > Around 09:45 PM ET today we will be running a system update.
The CMS will be temporarily unavailable for up to 15 minutes. You should plan to save ahead of time, or take a break during the update to avoid losing work.
  - [x] Run migration job (replay, change app_name to cms) (sets another alert to block editing, and deletes alerts on completion) 
  - [x] Merge devops PR https://github.com/department-of-veterans-affairs/devops/pull/8675
- [x] Cleanup old State S3 bucket
- [ ] Cleanup Jenkins job/groovy/seedjobs
- [ ] Cleanup unused Ansible tasks

Notes:
- We still have code for this we never removed in the Ansible playbooks. 
- The Terraform code for this is in some old git commits

**Comment by ElijahLynn** [comment]
Looks like getting us back on EFS should speed up our PROD deploys by about a minute too: 

![image](https://user-images.githubusercontent.com/1504756/110028902-b2dcbe00-7ce8-11eb-8c63-9eb44a917786.png)

**Comment by olivereri** [comment]
EFS asset backup job time:
![image.png](https://images.zenhubusercontent.com/5f04cf8f49978b1615fee8c2/df6bd81b-9717-4599-a851-4fd2b54d4430)

Current back up job time:
![image.png](https://images.zenhubusercontent.com/5f04cf8f49978b1615fee8c2/758137a2-c1ab-4022-bc9a-060f6255f2eb)

**Comment by ElijahLynn** [comment]
Vets-website asset fetch testing with `yarn build:content --pull-drupal --drupal-address=https://prod.cms.va.gov`:

BEFORE (EBS, fastest):
![image](https://user-images.githubusercontent.com/1504756/110876023-8d712680-828b-11eb-9c26-7bd227192fe3.png)

AFTER (EFS, slower, in progress):

**Comment by ElijahLynn** [comment]
Some EFS stats on the load put on EFS during the 1446 asset parallel download from the FE build. Some of this includes an EFS backup job that was running. 

![image](https://user-images.githubusercontent.com/1504756/110879812-75e96c00-8292-11eb-9642-69d74acdcf97.png)
![image](https://user-images.githubusercontent.com/1504756/110879876-90234a00-8292-11eb-8f65-0a73a1bd4f8b.png)

**Comment by ElijahLynn** [comment]
Did verify that it was in fact hitting cms-test for these tests by nuking the files mid-download, see screenshot attached where the dots that each represent a file, turn red mid-stream:
![image](https://user-images.githubusercontent.com/1504756/110881236-daa5c600-8294-11eb-9be9-fb0904aaab2b.png)

**Comment by ElijahLynn** [comment]
Test deploy on PROD 

> ooks like getting us back on EFS should speed up our PROD deploys by about a minute too:

Confirmed on our test deploy, speeds up by about a minute, under 5 minute deploy time now:

![image](https://user-images.githubusercontent.com/1504756/110884265-b698b380-8299-11eb-8b9c-02c49c8ff25e.png)
