### ISSUE TITLE
High Availability for the CMS Application

### ISSUE THREAD

**Issue by ElijahLynn** [department-of-veterans-affairs/va.gov-cms#4459]
Horizontally scale CMS/application instances

## Goals

- support large numbers of active users performing simultaneous actions that are DB heavy
- reduce performance issues that can be addressed w/ additional system resources
- support high availability (HA) for the CMS application

## Acceptance Criteria

- quantify benchmarks we're trying to hit
- Deployment config updated to deploy across 3 availability zones (ensure same vCPU count or higher total)
- Grafana updated to display all instances, automatically
- Ensure deployment process ASG logic works as expected
- Ensure run_once is set on all Jenkins/Ansible playbook runs
- [ ] The drupal application remains accessible despite a single node memcache failure

## Notes:
Currently a 16 core C5 instance
Multi-instance HA deploys supported on BRD already
Deploy shield, needs to be updated on all instances (not run_once)

**Comment by jefflbrauer** [comment]
@olivereri Are there any other stories that belong under this epic or can we close it out?

**Comment by olivereri** [comment]
Not that I know of. It seems like this still needs some refining and attention to fill it out. I think this is a casualty of the pivot to Accelerated Publishing. @ElijahLynn We still want to get this done right? Other epics take priority however.

**Comment by cweagans** [comment]
Closing in favor of https://github.com/department-of-veterans-affairs/va.gov-cms/issues/8734
