### ISSUE TITLE
Use Memcache for Drupal Cache on CMS-TEST [application]

### ISSUE THREAD

**Issue by indytechcook** [department-of-veterans-affairs/va.gov-cms#4460]
## Description

Configure Drupal to use Memcache for cache.

## Acceptance Criteria
- [x] Drupal uses Memcache on all environments (CMS-TEST) for:
    * cache writes and reads
    * semaphore (locks)
    * sessions
- [x] Memcache is configured according to best practices described in drupal.org/project/memcache README
- [ ] Drupal pages function as expected

**Comment by ndouglas** [comment]
Note to Self: I'll need to do some research into my past history to see where specifically I saw issues with serialization/deserialization, CLI execution, etc.
