### ISSUE TITLE
Facilitate CLP beta test with VBA

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#4472]
### User Stories

As a VBA editor, I need to be able to create a campaign landing page to make Veterans and their families aware of a specific, targeted campaign.

### Acceptance Criteria

- [x] Test form created
- [x] Test form reviewed
- [x] Test form finalized
- [x] Test form distributed before test
- [x] Test observed
- [x] Observations collected and synthesized

**Comment by xiongjaneg** [comment]
Test forms shared with John on March 3

**Comment by xiongjaneg** [comment]
Draft user instructions

CLP Beta Test Instructions
 
Thanks for taking time to help us with this beta test of the campaign landing page (CLP). 
 
If it’s OK with you, we’d like to record this session so that we can share observations with the team building this product in the CMS.
 
In our last meeting, you had a brief introduction to the page. During the beta test, you’ll complete the CLP edit form so you can get familiar with the form and give us feedback.
 
There is no correct or incorrect way to do things, just do what you think you should be able to do following the instructions in the form. We’ll be observing you as you use the form so we can identify potential improvements to the form and training needs.
Tips
Let us know if you have a real campaign you want to use for the beta test. If you don’t have one, you can use the sample content on pages 2 and 3.
Talk through your thought process as you use the form.
If you feel stuck, let us know and we can talk about how to proceed.
Ask questions as you have them.
Share any comments you have about the form.
Let us know if you need a break.
 
Closure 
 
Thanks so much for all the insights you shared. We really appreciate your time. We’ll be doing a few more of these sessions with other users in coming days/weeks, and may be making some changes to the form interface as we learn more. 
 
John: anything you want to add? 
 



Sample Content
 
Title: Get your flu shot
Page Introduction: Protect yourself. Protect your family. Protect your community. Get your flu shot today.
Primary Call to Action: https://www.va.gov/find-locations/
Button Label: Find VA Locations
Hero Image: Flu shot hero image
Why this matters Introduction: During flu season, protecting your health with a flu shot is easier than ever, and as close as 1 of more than 60,000 community locations. It's easy for Veterans to receive their flu shot at the right time and the right place.
Audiences: Veterans, Service members, Caregivers
Secondary Call to Action: /health-care/covid-19-vaccine
Button Label: Learn about the COVID-19 vaccine
What you can do Heading: Where you can get your flu shot
Introduction: If you’re eligible, go to an in-network retail pharmacy or urgent care location and present a valid, government-issued identification to receive your flu shot. Eligible Veterans can receive a no-cost, standard-dose or high-dose flu shot.
What you can do Promos: COVID-19 vaccines at VA
Video Heading: Veteran flu shots at community locations
Video: Flu shot video for CLP
Button Link: /health-care/covid-19-vaccine
Button Label: See more flu vaccine videos
Spotlight Heading: Copayments
Spotlight Introduction: Eligible Veterans whose visit to an in-network urgent care location that consists of only a flu shot won't have a copay. In addition, flu-shot only visits to an in-network urgent care location doesn't count toward the first 3 visits per calendar year that determines copay rates based upon the number of visits and your VA eligibility priority group.
Links with Summaries: https://www.va.gov/COMMUNITYCARE/revenue_ops/copays.asp
Link text: VA copays
Link summary: Learn about VA copays for eligible Veterans
Featured Stories URL: Homebound Veterans receive COVID-19 vaccine at home
Downloadable resources Heading: Download our flu shot fact sheet
Introduction: Learn more about the flu vaccine with our fact sheet.
Events Heading: Get your flu vaccine 
Select Events: pick any existing event
FAQs Question: What are the benefits of getting a flu shot at a community retail care pharmacy or urgent care location when I could get it at my local VA medical facility?
Answer: VA medical facilities offer no-cost flu shots to Veterans enrolled in VA health care. You're encouraged to visit your nearest VA medical facility each flu season to receive a flu vaccine. If the distance to your local VA medical facility is too great, you have another option. VA has partnered with more than 60,000 in-network retail pharmacies and urgent care locations to provide flu vaccines—at no cost—to eligible Veterans.
Add a Connect with Us panel: Veterans Health Administration
Select Benefit Hubs: VA health care

**Comment by xiongjaneg** [comment]
Scheduled 3/10/21 and 3/11/21

**Comment by xiongjaneg** [comment]
VBA beta test still to be scheduled - will be next sprint

**Comment by xiongjaneg** [comment]
Bronwyn's beta test to be rescheduled to next sprint

**Comment by xiongjaneg** [comment]
@nataliedunbarCS Anything to add to this before we mark it closed?

**Comment by nataliedunbarCS** [comment]
@xiongjaneg 

Link to Session 1 observation notes: https://docs.google.com/spreadsheets/d/1BTGVU6eY06xN3OseSyFP17j2OVCulELZDEZQl1s_8eI/edit#gid=0

**Comment by xiongjaneg** [comment]
@nataliedunbarCS Thanks. I'll also create an issue for next sprint for the next beta tests.
