### ISSUE TITLE
Spike: Modals for paragraphs and other entity reference forms. 

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#4477]
## Description

A number of form designs including [Vet Center](https://www.figma.com/file/885DMraAi9V2DLJnrIN7Wv/Vet-Centers?node-id=0%3A1) have included paragraphs or other entity referenced forms in modals. 

## Acceptance Criteria
- [ ] TBD

**Comment by swirtSJW** [comment]
Closing this as it was not fully formed enough to proceed with.
