### ISSUE TITLE
Sync Vet Center operating status fields to OS content types

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#4479]
## User Story or Problem Statement

 sync `field_operating_status_facility` and `field_operating_status_more_info` from Vet Center nodes to OS, using `field_facility_locator_api_id` as key. 

## Acceptance Criteria
- [ ] When an editor edits either of the facility status fields node 5626 (old Escanaba Mobile Vet Center), new Escanaba Mobile Vet Center node (NID TBD) is updated.
- [ ] When an editor edits either of the facility status fields node 3916 (old Clarksville Outstation), new Clarksville Outstation node (NID TBD) is updated.

**Comment by kaise-lafrai** [comment]
Create specific VA Vet center module.

**Comment by kevwalsh** [comment]
Closing this because this will be handled with a business process.
