### ISSUE TITLE
Modify data sending of COVID 19 vaccine service date to lighthouse.

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#4484]
## User Story or Problem Statement

As a facility locator engineer I need to have appointment related data from facility services pushed to lighthouse so that I may access it.

data should include.
 "appointment_leadin"
 "appointment_phones": 
 "referral_required"
 "walk_ins_accepted":

It should NOT include "online scheduling available" at this time.

## Acceptance Criteria
- [ ] 👀 **Needs design review** because the work involves changes to labels or other design elements.
- [ ] 🙈 Can be implemented without consulting design team members
- [ ] Testable_Outcome_X
- [ ] Testable_Outcome_Y
- [ ] Testable_Outcome_Z

## Implementation steps
<optional>

**Comment by kevwalsh** [comment]
We probably need a new epic for this. for now, i put it in #1729

**Comment by swirtSJW** [comment]
Lighthouse is going to do a bit of research to see if us sending a burst of over 11,000 services would be supported by the current overlay (endpoint).  If that can support it, we will likely just rely on a CMS side push and bulk push with no Pull operation from the Lighthouse side.  Then we can modify the "field" names on our side without need of maintaining mappings in both systems.

**Comment by swirtSJW** [comment]
Lighthouse update has been made and CMS code is now merged in.   After today's CMS deploy we can run the force push from here   https://prod.cms.va.gov/admin/config/va-gov-post-api/facility-force-queue

**Comment by swirtSJW** [comment]
I just pushed 204  COVID vaccine services to Lighthouse

![image](https://user-images.githubusercontent.com/5752113/113450281-90b08b80-93cd-11eb-9d2c-105783ec70ed.png)


![image](https://user-images.githubusercontent.com/5752113/113450268-8b534100-93cd-11eb-9e89-1fab210536b2.png)
