### ISSUE TITLE
Strip .git metadata on post-install-cmd composer hook

### ISSUE THREAD

**Issue by ElijahLynn** [department-of-veterans-affairs/va.gov-cms#4497]
Too often composer complains about changed files and IDEs ask if they should track git repos installed as part of composer install. I think we should strip .git metadata which is a common practice in the industry. 

AC:
- [ ] After a composer install, no dependencies should have a .git folder present

**Comment by TheBoatyMcBoatFace** [comment]
Other areas need our focus. Reopen if needed.
