### ISSUE TITLE
Use package version of Drupal core (not .git)

### ISSUE THREAD

**Issue by ElijahLynn** [department-of-veterans-affairs/va.gov-cms#4498]
## Background
Once upon a time the great firewall would block Drupal core package from downloading, because of packet inspection, somehow, the .git source version was not subject to the same scrutiny though. And since all of our builds now happen on the public internet, we can switch back to using the package version of Drupal core. 

## Assumptions
- This will speed up our composer installs by 10-30 seconds (I guestimate). 

## Acceptance Criteria
- [ ] Assumption of faster installation has been verified with 2-3 installs of core with & without the change to use the package
- [ ] Use Drupal package source instead of git source if speed improvement is verified

**Comment by indytechcook** [comment]
> And since all of our builds now happen on the public internet

Aren't the AMIs still build on BRD/behind the TIC?

**Comment by ElijahLynn** [comment]
> Aren't the AMIs still build on BRD/behind the TIC?

No, it was just the deploys go through the TIC. DevShop was also going through the TIC, which is the reason not all our builds were on the public internet. Now that we moved Tugboat and got the builds on the public internet, we are free of this restriction.

**Comment by mchelen-gov** [comment]
@ElijahLynn Is this still relevant?

**Comment by ElijahLynn** [comment]
Yes, and actually would improve the developer experience when doing a composer install because it still nags to delete the .git dependencies. We should bring this in, it's like a 1 or 2.

**Comment by TheBoatyMcBoatFace** [comment]
This is resolved with recent process improvements. Reopen if necessary.
