### ISSUE TITLE
Do not show "Login with PIV" link on lower environments for where SAML/PIV/Smartcard is not supported

### ISSUE THREAD

**Issue by ElijahLynn** [department-of-veterans-affairs/va.gov-cms#4503]
## Background

Follow up from https://github.com/department-of-veterans-affairs/va.gov-cms/issues/4502. 

> Getting unable to load private key from file error when I try to login to Tugboat

We need to improve the UX here, currently users see a link with the text:
> Login with PIV or other Smartcard.

![image](https://user-images.githubusercontent.com/1504756/109569892-08715a80-7a9e-11eb-932b-8df588fa3264.png)

Which if clicked goes to a page with this message:
> The website encountered an unexpected error. Please try again later.

> SimpleSAML\Error\Exception: Unable to load private key from file "/certs/cms.va.gov.private.key" in SimpleSAML\Utils\Crypto::loadPrivateKey() (line 220 of vendor/simplesamlphp/simplesamlphp/lib/SimpleSAML/Utils/Crypto.php).

 
![image](https://user-images.githubusercontent.com/1504756/109569918-11fac280-7a9e-11eb-9164-06c935bccdd5.png)

## Acceptance Criteria

- [ ] "Login with PIV or Smartcard" link is not shown on environments without SSO
- [ ] Tests exist to confirm that the correct behavior

**Comment by acrollet** [comment]
@rachel-kauff @nataliedunbarCS could I ask for your help in determining ACs on this issue? Thanks so much!

**Comment by ElijahLynn** [comment]
Some extra context, the UX was _supposed_ to primarily highlight PIV login and minimize user/pass login as the goal was to direct _most_ users to login via PIV.

**Comment by acrollet** [comment]
@ElijahLynn ah ok, I had missed the bit about smartcard login not working on lower environments. Is that just tugboat, or also staging/dev?

**Comment by ElijahLynn** [comment]
> @ElijahLynn ah ok, I had missed the bit about smartcard login not working on lower environments. Is that just tugboat, or also staging/dev?

STAGING and DEV work with PIV, if a user is added to a special allowlist. The PIV infrastructure doesn't allow for more than 4 environments right now. Someday I'd like to investigate/request what it would take to allow a wildcard domain + certificate so we can test on CI.

**Comment by ElijahLynn** [comment]
> Make sense to you?

I suppose. I don't like deviating on lower environments if possible but until we get wildcard SSO login, I think this makes sense.

**Comment by rachel-kauff** [comment]
There's a number of other glaring UX issues here that are likely out of scope, but removing the login w/ PIV link is a good first step!
