### ISSUE TITLE
Guide VAMC editors away from using PDFs

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#4515]
How might we
- guide editors (not just VAMC) use Form detail pages instead of uploading PDFs
- ask editors if they _really_  need a PDF
- encourage adding to Form Database

Questions to ask
- is this a "poster"? 

Ideas
- "PDF wizard"
- split off PDFs in the media library

if a PDF is absolutely necessary
- how to create accessible PDFs 

Related: #7293

**Comment by EWashb** [comment]
We are working on this with the various SiteImprove issues. PDFs are a hot issue and we are addressing it not just from the VAMC perspective, but from a total editorial experience. This work will relate to other work being down for #10477
