### ISSUE TITLE
[tugboat] WEB UI display a pre-deploy warning message at the bottom of the page

### ISSUE THREAD

**Issue by ElijahLynn** [department-of-veterans-affairs/va.gov-cms#4517]
Split from #4432. 

## Acceptance Criteria
- [ ] WEB UI display a pre-deploy warning message at the bottom of the page

**Comment by ElijahLynn** [comment]
Blocked on #4432 because the solution that we end up with for the CMS pre-deploy alerts might be the same core solution we come up with for FE WEB builds as well. Because putting an alert in thousands of HTML pages is not feasable by find/replace/lineinfile, we need something more practical.

**Comment by jefflbrauer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VAgov-CMS-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/4517?planning-poker) with ZenHub @ElijahLynn @indytechcook @ndouglas @olivereri @timcosgrove

**Comment by jefflbrauer** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VAgov-CMS-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/4517?planning-poker) with ZenHub @cweagans

**Comment by TheBoatyMcBoatFace** [comment]
Closing after team discussion. Reopen if necessary.
