### ISSUE TITLE
VSCode + Lando xdebug config

### ISSUE THREAD

**Issue by mchelen-gov** [department-of-veterans-affairs/va.gov-cms#4519]
## Description

Run VSCode debugger with Lando xdebug

## Acceptance Criteria
- [ ] VSCode breakpoints are caught by lando xdebug
- [ ] Docs describe setup and config

**Comment by cweagans** [comment]
Documented here: https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/READMES/debugging.md#xdebug

Docs are being updated for ddev in https://github.com/department-of-veterans-affairs/va.gov-cms/pull/9401
