### ISSUE TITLE
Allow only VHA digital media to edit VAMC system names

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#4522]
## Description

Since VAMC system names are not in VAST, Drupal is the source of truth.  Only VHA digital media should be able to edit them. 

In #4520 we are hiding this field from VAMC editors. But we need to expose it to VHA digital media staff to update. 

## Acceptance Criteria
- [x] Work with Facilities team to document a business process that the CMS can support. **Decision: Only VHA **:
- [ ] Members of VHA digital media have a means to edit VAMC system names. 

## Implementation ideas
1. A dashboard (views-based?) that allows a user to update VAMC system names. Ideally, it would only be visible to members of a given section. 
2. A form mode specific to the node title (could this be used for other products/user stories)
3.

**Comment by ethanteague** [comment]
Covered by https://github.com/department-of-veterans-affairs/va.gov-cms/pull/4532
