### ISSUE TITLE
Extend field_office entity reference permissions to Vet Center content types

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#4541]
## User Story or Problem Statement

As an editor or creator of Vet Center content, i should only be able to add content to the Vet Center that i have access to according to Section permissions. 

As an editor or creator of Vet Center content with access to only one section and vet center, i want fields that have only one option to be pre-populated for me

As a non-content admin, i don't want to see fields that i shouldn't be touching (or can't touch!). 

## Background

`va_gov_user` module has UserPermsService logic to constrain options for `field_office` on VAMC and Outreach Hub content types

###  "Vet Center Community Access Point" or "Vet Center Health Service" content types
- [x] As an content_publisher  assigned to Reno Vet Center section, i can only add a "Vet Center Community Access Point" or "Vet Center Health Service" to field_office Reno Vet Center 
- [x] As an content_publisher assigned to "Vet Centers", i can add content to any Vet Center
- [x] As a content_admin, i can add content to any Vet Center.

Moved to a different issue:

```
### Other content types: hide fields that non-content-admins should be touching

As a non-content admin, i don't want to see fields that i shouldn't be touching (or can't touch!). 

- [ ] Without content_admin or administrator role, i can't see `field_office` on the following three content types. 
  - [ ] Vet Center Locations List 
  - [ ] Vet Center Outstation
  - [ ] Vet Center Mobile Vet Center

Something to consider: should we only hide them when they already have values? (16th minute, with @swirtSJW?) 
```

**Comment by ethanteague** [comment]
Handled by https://github.com/department-of-veterans-affairs/va.gov-cms/pull/4540

**Comment by ethanteague** [comment]
I don't think we are going to be able to make vet center field office section governance work (in it's current iteration). There isn't anything tying individual vet center nodes to section terms. I need this connection to be in place to use the existing user section governance I created last year (that we are using for other places with field_office).

**Comment by kevwalsh** [comment]
Moving this to Sprint 30, i don't think it's working quite right yet. 

My comment from the PR #4541 


1. I made suzanne.middaugh@va.gov a Vet Center content creator, assigned her to Escanaba Vet Center section, and removed her content admin role. 
2. Went to /node/add/vet_center_cap and /node/add/vet_center_facility_health_servi
3. field_adminstration was properly restricted to Escanaba, but field_office was not. 

i think we need to write some automated tests for this too.

**Comment by ethanteague** [comment]
> Moving this to Sprint 30, i don't think it's working quite right yet.
> 
> My comment from the PR #4541
> 
> 1. I made [suzanne.middaugh@va.gov](mailto:suzanne.middaugh@va.gov) a Vet Center content creator, assigned her to Escanaba Vet Center section, and removed her content admin role.
> 2. Went to /node/add/vet_center_cap and /node/add/vet_center_facility_health_servi
> 3. field_adminstration was properly restricted to Escanaba, but field_office was not.
> 
> i think we need to write some automated tests for this too.

I followed your qa steps, and I'm only seeing Escanaba available to both of those fields on both content types, @kevwalsh . Gonna probably need to grab some zoom time with you tomorrow for screenshare.

**Comment by kevwalsh** [comment]
After a screenshare i realized i didn't QA right. closing again!

**Comment by swirtSJW** [comment]
@kevwalsh I am re-opening this since  we reverted the code 
https://github.com/department-of-veterans-affairs/va.gov-cms/pull/5026
that was leading to bad caching for anyone with access to multiple products.

**Comment by kevwalsh** [comment]
Adding to Sprint 51 for evaluation.
