### ISSUE TITLE
Add description to "Content Creator - Vet Center" role and change weight to alpha sort with other Content Creator roles

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#4550]
## Acceptance Criteria
- [ ] When editing any user (eg user/1/edit", the "Content Creator - Vet Center" role appears immediately after "Content creator - VAMC"
- [ ] The description of the role reads: "Can create Vet Center Health Services and CAPs."

**Comment by ethanteague** [comment]
Covered by https://github.com/department-of-veterans-affairs/va.gov-cms/pull/4549
