### ISSUE TITLE
Entity Field Fetch Field should provide entity id and revision ids on the field in addition to uuid.

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#4553]
## User Story or Problem Statement

As a front end developer I should see enitity ids as part of any entity field fetch fields so that we don't have to create a new lookup pattern based on UUID.   UUID was prioritized when Tome Sync was our direction.  That is not longer needed, but can still be providied.

Upstream issue on drupal.org https://www.drupal.org/project/entity_field_fetch/issues/3201718

## Acceptance Criteria
- [ ] graphQL query of a field using EFF returns an Entity ID (?)

## Implementation steps
<optional>

**Comment by cmaeng** [comment]
Don't think that this is an immediate blocker for FE teams, possibly in the next week.

**Comment by swirtSJW** [comment]
This turned out to be much bigger than I had anticipated.   It is resolved enough to unblock the front end team though.

Once this PR https://github.com/department-of-veterans-affairs/va.gov-cms/pull/4681 makes it to prod and policy content pages are re-saved, what used to look like this

```
"field_cc_top_of_page_content": [
        {
            "target_type": "paragraph",
            "target_uuid": "7192f5fb-08dd-4401-a863-c5a09cc7de50",
            "target_field": null
        }
```

will look like this 

```
"field_cc_top_of_page_content": [
        {
            "target_type": "paragraph",
            "target_uuid": "2749",
            "target_field": null
        }
```

The property name says target_uuid but it will actually be an entity id.  I will fix this later to become the more proper 
`target_id`   
My suggestion to @mpelzsherman is to look for `target_id`    but if it does not exist, use `target_uid` .  That way when the contrib module is repaired it will just keep working.
