### ISSUE TITLE
Non-English Localized nodes present an "en" langcode to the frontend.

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-cms#4554]
**Describe the defect**
From @ncksllvn: "Using the Explorer right now... I'm see a langcode on the content model but it appears be `en`, even on the Spanish Corona FAQ page"

I'm not sure if we have any way of indicating programmatically the language of a given node, but if there is, we don't seem to be doing it.

**To Reproduce**

**Expected behavior**

**Additional context**
Add any other context about the problem here. Reach out to the Product Managers to determine if it should be escalated as critical (prevents users from accomplishing their work with no known workaround and needs to be addressed within 2 business days).

**Comment by VanessaLuxen** [comment]
Relates to Jira ticket: https://va-gov.atlassian.net/jira/servicedesk/projects/VAHELP/queues/custom/11/VAHELP-471

**Comment by jefflbrauer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VAgov-CMS-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/4554?planning-poker) with ZenHub @ElijahLynn @indytechcook @ndouglas @olivereri @timcosgrove

**Comment by jefflbrauer** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VAgov-CMS-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/4554?planning-poker) with ZenHub @cweagans

**Comment by TheBoatyMcBoatFace** [comment]
Upcoming translation work makes this no longer valid.
