### ISSUE TITLE
Different localizations of content don't seem to have references to one another.

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-cms#4555]
## Description
@ncksllvn raised this issue: 

>Separate question - Recently we started producing different languages of pages and I'm wondering if there is an indicator of that at all in the content model. Like if the English version of a page may have a property in it to say there is also a Spanish version.

>Here's an example, https://www.va.gov/coronavirus-veteran-frequently-asked-questions/ and the Spanish version, https://www.va.gov/coronavirus-veteran-frequently-asked-questions-esp/.

>I think that URL structure is standardized, as in Spanish-translated pages will have that -esp suffix, so the build could dynamically determine if there is a Spanish version, but the preview server wouldn't be able to do that (bc it'll only have one of the two pages in memory at render time.)

I'm not seeing any indication that we're using the stock Drupal localization functionality, and I'm not seeing any references to different localizations from a given node.

Related to #4554 , and might be closed in the same PR.

**Comment by VanessaLuxen** [comment]
Relates to Jira ticket: https://va-gov.atlassian.net/jira/servicedesk/projects/VAHELP/queues/custom/11/VAHELP-471

**Comment by TheBoatyMcBoatFace** [comment]
A more up-to-date localization initiative taking place in upcoming quarter.
