### ISSUE TITLE
Identify and publicly share data retention policy for Demo environments.

### ISSUE THREAD

**Issue by ElijahLynn** [department-of-veterans-affairs/va.gov-cms#4559]
## Background

As a tugboat demo user, I need to understand how long my environments will last and whether they are backed up, in order to know that I should not store critical data on an ephemeral environment.

## Acceptance Criteria
- [ ] Write and publish policy for Tugboat Demo environment data retention on Confluence
  - Include information about lack of DB backups on tugboat
- [ ] Summarize and link policy page from Tugboat demo environment Drupal login pages
- [ ] Issue public announcement to Tugboat users

**Comment by TheBoatyMcBoatFace** [comment]
This is handled elsewhere. Reopen if necessary.
