### ISSUE TITLE
[tugboat] Determine level of effort for data retention on Demo environments

### ISSUE THREAD

**Issue by ElijahLynn** [department-of-veterans-affairs/va.gov-cms#4561]
Depends on priority of https://github.com/department-of-veterans-affairs/va.gov-cms/issues/4560

AC:
- [ ] Identify possible approaches for data retention on Demo environments
- [ ] Determine level of effort for those approaches

**Comment by mchelen-gov** [comment]
cross posting from https://github.com/department-of-veterans-affairs/va.gov-cms/issues/4560#issuecomment-793888820:
> Data retention
> VAMC Upgrade understands that demo environments are transient in their nature and that our environment retention policy is 30 days of inactivity.
> VAMC Upgrade team stated that coordination of maintenance times that can compromise data is important in their current workflow (VAMC Dual-state launches).
> The CMS Core Application team's process should be as follows - protect the data whenever possible and coordinate maintenance timing with all demo environment stakeholders in the case that the data loss is unavoidable.

Questions for research:
- Data retention approach for planned maintenance
- Data retention approach for unplanned downtime
  - Tugboat guidance about automated backup

**Comment by TheBoatyMcBoatFace** [comment]
This is handled elsewhere. Reopen if necessary.
