### ISSUE TITLE
[tugboat] Monitoring and Alerting Setup

### ISSUE THREAD

**Issue by ElijahLynn** [department-of-veterans-affairs/va.gov-cms#4562]
As a CMS devops engineer, I need to know when Tugboat is experiencing pressure and/or inaccessible, in order to ensure the service's reliability.

## Acceptance Criteria
- [ ] PagerDuty notification (including slack notification) is created when CPU load > 70% for a minimum of 3 minutes
- [ ] PagerDuty notification (including slack notification) is created when disk usage is > 80%
- [ ] Grafana charts are available for the following metrics:
   - Number of demo environments
   - Number of PR environments
   - Memory usage
   - Swap usage
   - CPU usage
   - Disk usage

**Comment by ElijahLynn** [comment]
We might want to get https://github.com/department-of-veterans-affairs/va.gov-team/issues/20548 done first so that we can use the default node alerting feature based on label.

**Comment by acrollet** [comment]
The following AC was moved to #4174:

> - [ ] PagerDuty notification (including slack notification) is created when the Tugboat UI is inaccessible within 5s for 3 consecutive requests
