### ISSUE TITLE
Show number of Vet Centers offering a service on /vha-health-services

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#4569]
## User Story or Problem Statement

As an editor or stakeholder in VHA health services, i can see how many Vet Centers offer each service. 

Related user story, could be a separate issue: 

As an editor or stakeholder in VHA health services, i can click a link from the /vha-health-services board to see the diversity of health service descriptions across Vet Center and VAMC facilities. 

## Acceptance Criteria
- [ ] New column on /vha-health-services that counts number of Vet Center Health Service nodes that reference that taxonomy term, just like the VAMC column seen in screenshot.

![Screenshot_2021-03-04__1_52_PM](https://user-images.githubusercontent.com/643678/110014549-ec192c00-7cf0-11eb-8c8b-d182b697c3de.png)

**Comment by jilladams** [comment]
What we know right now: 
You can see at the Vet Center services view, e.g. https://prod.cms.va.gov/admin/content/facilities/vet-center-services?field_service_name_and_descripti_target_id=54&moderation_state=All&workbench_access_section__section=All, some version. But we think there's an actual view with a count, somewhere in the CMS.

@mmiddaugh has volunteered to look for it.
