### ISSUE TITLE
vets-website FE PR builds use dedicated Tugboat preview environment

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#4570]
background in https://github.com/department-of-veterans-affairs/va.gov-cms/issues/4316 

## Acceptance Criteria
- [x] CMS team communicated technical details to FE team for switching from using Prod CMS to Tugboat preview env for vets-website PR builds 
https://dsva.slack.com/archives/C01512KN35G/p1615211446253600
- [ ] vets-website non-master front end builds use Tugboat environment
- [ ] vets-website DEV, STAGING, PROD builds continue to use PROD CMS for data

## Notes

* CMS open a PR w/ desired change and coordinates w/ FE approval team to merge

**Comment by indytechcook** [comment]
The Tugboat preview has been setup per: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/4316#issuecomment-791854774: https://cms-vets-website-branch-builds-lo9uhqj18nwixunsjadvjsynuni7kk1u.tugboat.vfs.va.gov/

I've communicated in slack in the #content-release-engineering channel: 

> We created a new domain to use for non-master based builds.  The DRUPAL_ADDRESS is https://cms-vets-website-branch-builds-lo9uhqj18nwixunsjadvjsynuni7kk1u.tugboat.vfs.va.gov  This will help remove the the load on production from the vets-website CI

Next I'll create a follow up in the va.gov-team repo.

**Comment by ElijahLynn** [comment]
Some more discussion on getting these switched over here https://dsva.slack.com/archives/C01512KN35G/p1615211446253600.

**Comment by ElijahLynn** [comment]
We are still blocked on this with regards to the VA root cert not being trusted inside the container build. This is only happening now because we are using an `https://` link and the previous, existing ones are all `http://`. I was trying to get to this last sprint/week but didn't finish it, so we need to keep it in this sprint (29).

**Comment by acrollet** [comment]
> We are still blocked on this with regards to the VA root cert not being trusted inside the container build. This is only happening now because we are using an `https://` link and the previous, existing ones are all `http://`. I was trying to get to this last sprint/week but didn't finish it, so we need to keep it in this sprint (29).

@ElijahLynn - @indytechcook just suggested a workaround, which is modifying the build to allow insecure connections:

`NODE_TLS_REJECT_UNAUTHORIZED = 0`

**Comment by mchelen-gov** [comment]
I added https://github.com/department-of-veterans-affairs/va.gov-cms/issues/5163 as a dependency. Loading the VA cert would probably be ideal however it's not sized, so if we need a workaround that's ok.

**Comment by ncksllvn** [comment]
Would using `http` instead of `https` inside of CI fix this?

**Comment by acrollet** [comment]
PR is now ready and waiting for review: https://github.com/department-of-veterans-affairs/vets-website/pull/16327
