### ISSUE TITLE
Distribute CMS editorial experience survey for Q1 2021

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#4572]
The goal is to send early in the week of 3/8 and process feedback by the end of Sprint 28 (Mar 26)

## Acceptance Criteria
- [x] comms for survey distribution are prepared
- [ ] ~Survey is distributed to CMS users~ https://github.com/department-of-veterans-affairs/va.gov-cms/issues/4645

**Comment by jordanamello** [comment]
Survey will be sent out next Monday by @mchelen-gov. Tracking issue: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/4645
- [Survey comms](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/research/user-survey-results/README.md)
