### ISSUE TITLE
CMS BRD container management and orchestration

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#4596]
### User Story / Objective

As a CMS DevOps engineer, I need to provide a fully supported infrastructure for the CMS Application, so that the CMS Application can continue to be secure and performant.

### Problem Statement

* AL1 (Amazon Linux) is EOL - 12/31/22, and does not support PHP 7.3 version required by Drupal 9. We found a temporary workaround (Remi repos), which is not best practice and we are not sure how long this workaround will be supported by third-party.
   * PHP 7.2 included in AL1 is EOL
   * PHP 7.3 is not available
   * AL1 will receive critical support by 6/30/23
* [PHP 7.3 Security support ends on 6 Dec 2021](https://www.php.net/supported-versions.php) - 7 months

#### Dependency on Platform-supported infrastructure:

* OPs is currently instructing - no new apps should be built on Jenkins/Ansible BRD infrastructure
* OPs team is still in the process of establishing updated infrastructure tools and practices.
   * Platform team is blocked on Amazon Elastic Kubernetes Service (EKS) by FedRAMP High (GovCloud) Joint Authorization Board (JAB) Review
   * Overall status is currently unknown to the CMS team.

### Affected users and stakeholders

* CMS Engineers
* CMS Users

### Hypothesis

We believe that migrating to the new EKS BRD container system will satisfy our objective.
   * We'll know that to be true when _this measurable outcome occurs._

### Assumptions
* there are opportunities to embed CMS DevOps engineer into the process of establishing new platform tools, which will increase CMS onboarding efficiency onto the new EKS BRD system
* 

## Acceptance Criteria
- [ ] Testable_Outcome_X
- [ ] Testable_Outcome_Y
- [ ] Testable_Outcome_Z

**Comment by mchelen-gov** [comment]
Reliance on 3rd party RPM packages caused this incident to affect us: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/5987

**Comment by ElijahLynn** [comment]
We can proceed with building out the new infra on the Ops supported K8s + ArgoCD platform. We cannot yet launch it because there are some logging and monitoring bits to work out before launching in PROD though, but I think by the time we migrate those bits will be ready.

**Comment by mchelen-gov** [comment]
it would be good to connect this with https://github.com/department-of-veterans-affairs/va.gov-team/issues/26376

do we know what implementation tickets might go into this epic, like deploy CMS on Dev or another lower env?
