### ISSUE TITLE
Read-only replica of the database

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#4607]
### User Story

As a CMS Engineer, I need to offload strain on the CMS Production infrastructure whenever possible, so that the CMS Production instance remains stable and performant.

### Problem Statement

GraphQL queries that run during the Content Release process utilize large amount of resources, which in turn slows down the editor-facing application.

### Affected users and stakeholders

* CMS Editors
* CMS Engineers

### Hypothesis

We believe that using read-only replica of the CMS Production database for any intensive database query services will:
* improve overall CMS Application performance during frequent Content Releases
* reduce strain on Production infrastructure
* protect queried data from race conditions that cause broken links

### Acceptance Criteria

- [ ] database query services (GraphQL during Content Release) are configured to use read-only replica

**Comment by ElijahLynn** [comment]
> Per hackathon 3/24, the team a> Per hackathon 3/24, the team agreed to stop work on this and switch gears to memcached.

Further explanation of this is here > https://github.com/department-of-veterans-affairs/va.gov-cms/issues/4461#issuecomment-807096110.

**Comment by TheBoatyMcBoatFace** [comment]
No longer needed - Content Build is not having a significant impact on application performance currently.
