### ISSUE TITLE
Refactor centralized content fields on Vet Center to use entity IDs and put _cc_ in their machine name

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#4615]
## User Story or Problem Statement

As a FE dev, i want fields with Centralized content to follow an established naming convention, so i know when treat them a certain way. 

As a FE dev, i want to use entity IDs not UUIDs for Vet Center EFF fields, because i want to use GraphQL not transformers. (This is dependent on #4553). 

## Acceptance Criteria

- [x] `field_non_traditional_hours` has been recreated as `field_cc_non_traditional_hours`, with the same config
  - [x] Entity ID (has been added, per #4553)
- [x] `feld_vet_center_call_center` has been recreated as `field_cc_vet_center_call_center`, with the same config.
  - [x] Entity ID (has been added, per #4553)

![Manage_fields___VA_gov_CMS](https://user-images.githubusercontent.com/643678/110663544-8adfd580-8194-11eb-9535-d99dce2f7068.png)

**Comment by ethanteague** [comment]
Covered by https://github.com/department-of-veterans-affairs/va.gov-cms/pull/4703
