### ISSUE TITLE
Page introduction should be required on both Vet Center and Vet Center Locations List

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#4624]
**Describe the defect**

**To Reproduce**
1. Go to /node/add/vet_center or /node/add/vet_center_locations_list
2. Page intro is not required on either

**Expected behavior**
Page intro should be required on both.

**Comment by ethanteague** [comment]
Covered by: https://github.com/department-of-veterans-affairs/va.gov-cms/pull/4622
