### ISSUE TITLE
Change media entity reference widget on vet_center from "Autocomplete" to "Media Library"

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#4625]
**Describe the defect**
Image fields should use media library widget to allow inline adding of media. 

**To Reproduce**
1. Go to /node/add/vet_center
2. See autcomplete widget

**Expected behavior**
Should be Media Library widget

**Comment by ethanteague** [comment]
Covered by: https://github.com/department-of-veterans-affairs/va.gov-cms/pull/4622
