### ISSUE TITLE
  Remove field_hours and add field_office_hours for Vet Center CAP

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#4627]
## User stories

As an API consumer, i want structured hours data instead of hours data in a table array. 

As an editor, i want to enter content in a structured widget. 

## Acceptance Criteria
- [x] field_hours has been removed from vet_center_community_access_point 
- [x]  field_office_hours has been added to vet_center_community_access_point, following the same field config as vet_center content type.

**Comment by ethanteague** [comment]
Covered by: https://github.com/department-of-veterans-affairs/va.gov-cms/pull/4622
