### ISSUE TITLE
Make revision log mandatory for all vet_center_* content types

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#4628]
## User Story or Problem Statement

As a CMS user of Vet Center products, i want meaningful revision histories that tell me what changed with each edit. 

Per @davidconlon: we may want to extend this across all content types, but for now this could be done for just one product, to avoid the change management that making this change across the CMS would entail. 

## Acceptance Criteria
- [ ] All vet_center content types have a required Revision log field.

**Comment by ethanteague** [comment]
Confirmed that they do.

**Comment by kevwalsh** [comment]
Reopening this. Vet Centers do not yet have required Revision Log fields. 

For example:
https://prod.cms.va.gov/node/3756/edit



![Edit_Vet_Center_Escanaba_Vet_Center___VA_gov_CMS](https://user-images.githubusercontent.com/643678/112788393-cd286400-9028-11eb-958a-8a1bf319a758.png)
