### ISSUE TITLE
Comms about 8x/day content releases

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#4631]
See https://github.com/department-of-veterans-affairs/va.gov-cms/issues/4474 for background.

## Acceptance Criteria
- [x] Comms strategy about 8x/day content releases reviewed and confirmed w/ @davidconlon @johnhashva
- [ ] Communication about 8x/day content releases is distributed to the CMS user base [Slack / Email] - ETA Wed Apr 7
- [ ] Existing documentation updated

**Comment by acrollet** [comment]
Internal communication here: https://dsva.slack.com/archives/C01512KN35G/p1616501984036700
