### ISSUE TITLE
Removing Benefit Hubs is not possible when parent form fails validation.

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-cms#4633]
**Describe the defect**
Defect report from the Support channel:
>I'm creating a single Q&A in R&S that is about burials and memorials. For the benefit hubs section, health care is already chosen. Even if I add burials, it doesn't allow me to remove health care and I get a red error message. See screen shot.

<img width="708" alt="Screen Shot 2021-03-11 at 10 18 09 AM" src="https://user-images.githubusercontent.com/1318579/110811248-85e25b00-8254-11eb-995b-cf820152bfe2.png">

It appears that attempting to remove the paragraph submits the form and triggers validation, but since the form state fails validation, paragraph removal fails.

**To Reproduce**
1. Create an R&S node and leave at least one required field blank
2. Add a Benefit Hub
3. Attempt to remove that Benefit Hub and notice that the attempt fails.

**Expected behavior**
It should be possible to remove the Benefit Hub without the rest of the form being complete.

**Additional context**
Workaround is to correctly fill in the rest of the form, but this is not an ideal experience.

**Comment by jilladams** [comment]
This does not repro in prod today.
