### ISSUE TITLE
Send broken link reports to Slack only for vets-website master branch (and update destination slack channel?)

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#4636]
## User Story or Problem Statement

As a member of CMS or other team concerned about broken links, i want _actionable_ reports of broken links. 

With the addition of content-build repo, we've started to see broken link reports from content-build repo master, which are not actionable. 

Broken link reports currently only go to #cms-helpdesk-bot, which has only 5 slack users. Should these go to #vfs-engineers or #vfs-platform support instead?

## Acceptance Criteria
- [ ] Only vets-webite master triggers slack messages
- [ ] Broken link reports go to [Channel TBD]

**Comment by oksana-c** [comment]
attn: @erogray @VanessaLuxen @mchelen-gov @jefflbrauer @cmaeng

**Comment by mchelen-gov** [comment]
@meganhkelley @timwright12 we want to make sure that only `vets-website` is sending broken link alerts and not https://github.com/department-of-veterans-affairs/content-build until whenever `content-build` cutover occurs

**Comment by meganhkelley** [comment]
Hey @mchelen-gov ! Yep I talked to Kevin a bit about this yesterday, we'll report back today or Monday.

**Comment by timwright12** [comment]
@kevwalsh  I just merged in a PR that removed the slack calls from content-build. If you anymore similar alerts, please let me know. I would give this a few days before closing the ticket just in case, but I think we got it.

**Comment by timwright12** [comment]
@kevwalsh Have you noticed any alerts coming into the channel?

**Comment by timwright12** [comment]
Closing this ticket: https://dsva.slack.com/archives/C01512KN35G/p1615988225003400?thread_ts=1615504033.058200&cid=C01512KN35G
