### ISSUE TITLE
Asset file restoration to lower environment deploys is too slow

### ISSUE THREAD

**Issue by ElijahLynn** [department-of-veterans-affairs/va.gov-cms#4639]
Follow up to #4457

With the move back to EFS from EBS on all of our environments the deploy time on lower environments is 10 minutes slower than with EBS because the write speeds for thousands of files over 2GB on EFS just takes more time. 

## AC:
- [ ] Asset sync to lower environments should take less than 3 minutes (currently 10 minutes)

### CMS Asset file backup
- [x] ~~Use multi-part S3 upload~~ AWS CLI s3 command already uses multipart upload.
### sync-files.sh
- [x] ~~Change asset file download method from `curl` to AWS CLI `s3 cp`~~ Use AWS Transfer manager multi-part download.
- [x] Use `pigz` binary to extract tar `tar --extract --user-compress-program=pigz --file cms-prod-files-latest.tgz --directory extract/dir/`
- [x] Use Parallel rsync per asset file directory `time find -L . -type d | parallel rsync -aR --ignore-existing --update --delete {} $cmsfiles`
### AMI Build
- [x] Install `pigz` dependency `yum install pigz -y`
- https://zlib.net/pigz/
- [x] Install GNU Parallel `yum install parallel`
- https://www.gnu.org/software/parallel/

### Server Deployment
- [ ] Add small Python boto3 S3 download script to CMS deployment files.

Implementation Notes:
- Good ideas here on using rsync > https://devcloud.co.za/improving-efs-performance-part-2/
- Consider not doing a full copy, and just partial copy with parallel rsync (see above link), the data should persist on the EFS volume between deploys/mounts

**Comment by olivereri** [comment]
# File sync time prior to merge of [#8675](https://github.com/department-of-veterans-affairs/devops/pull/8675) March 10th 3:54pm PST

![image.png](https://images.zenhubusercontent.com/5f04cf8f49978b1615fee8c2/d1002e9e-4325-4960-a2ad-fb35c931f41c)

# File sync time after

![image.png](https://images.zenhubusercontent.com/5f04cf8f49978b1615fee8c2/5b0bd222-f603-4314-bf51-bfa099d131d1) March 12th 7:09am PST  

# Can get as bad as 8 minutes or more:

![image.png](https://images.zenhubusercontent.com/5f04cf8f49978b1615fee8c2/eac6c826-0ab5-4466-9ee0-be8111d85111)

**Comment by olivereri** [comment]
## Using AWS API for S3 gets versus reaching out to the HTTPS S3 Endpoint:

@ElijahLynn you had made mention that we have an S3 Gateway Endpoint attached to the VPCs CMS servers run in.  Sync-files.sh uses curl to reach out to the HTTPS endpoint taking a different path. It doesn't appear AWS detects this and uses the Gateway Endpoint when reaching out to the HTTPS Endpoint. However, using the AWS API cuts the download time in half.

![image.png](https://images.zenhubusercontent.com/5f04cf8f49978b1615fee8c2/89ad72e6-7e4a-46f8-b6a8-4b0395337b39)

**Comment by olivereri** [comment]
## Additional potential time savings using S3 Multipart upload & AWS TransferManager for parallel downloads:

Multipart Upload:
https://medium.com/@niyazi_erd/aws-s3-multipart-upload-with-python-and-boto3-9d2a0ef9b085
https://docs.aws.amazon.com/AmazonS3/latest/userguide/mpuoverview.html#distributedmpupload

Parallel Download:
https://aws.amazon.com/blogs/developer/parallelizing-large-downloads-for-optimal-speed/

**Comment by olivereri** [comment]
## Using Parallel Gzip (PIGZ) versus Gunzip to extract asset files:

Using PIGZ for file extraction has been cut in half.

![image.png](https://images.zenhubusercontent.com/5f04cf8f49978b1615fee8c2/8413d38d-969e-40da-8765-5af5bf5fa69f)
