### ISSUE TITLE
Feature documentation for content release build trigger

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#4646]
Closed implementation stories for automatically triggered content releases from Drupal:  

https://github.com/department-of-veterans-affairs/va.gov-cms/issues/1121
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/1654 

## Acceptance Criteria
- [x] Developer-focused documentation has been created for the automatically triggered content build process
- [x] Usage of the Jenkins pipeline for on-demand Content Release is documented
- [x] end-to-end process diagram is created and shown in documentation

**Comment by mchelen-gov** [comment]
custom module: https://github.com/department-of-veterans-affairs/va.gov-cms/tree/master/docroot/modules/custom/va_gov_build_trigger

**Comment by mchelen-gov** [comment]
we might need to start by documenting this feature as a whole, and then specifically call out Jenkins / build pipeline dependency?

**Comment by indytechcook** [comment]
High level flow already exists: https://github.com/department-of-veterans-affairs/va.gov-cms/blob/master/READMES/cms-content-release.md.  Just need to update

**Comment by indytechcook** [comment]
Content release readme has been updated: https://github.com/department-of-veterans-affairs/va.gov-cms/blob/master/READMES/cms-content-release.md

**Comment by indytechcook** [comment]
I updated the readme with details about how to run a release and linked to a folder on the team repo with more information about the build.

**Comment by indytechcook** [comment]
@mchelen-gov please review the readme and let me know if this works.  Most of this has been documented in other places which I linked to from the readme. https://github.com/department-of-veterans-affairs/va.gov-cms/blob/master/READMES/cms-content-release.md

**Comment by mchelen-gov** [comment]
@indytechcook this looks good! can you add a link to where the jenkins job name is configured in drupal?

**Comment by indytechcook** [comment]
@mchelen-gov updated.

**Comment by mchelen-gov** [comment]
@indytechcook i removed some duplicate stuff, if this looks good to you then we are all set! https://github.com/department-of-veterans-affairs/va.gov-cms/commit/dab257e016512d1ec209570ffba0e263cca91d70
