### ISSUE TITLE
Analyze menu_breadcrumb performance in GraphQL

### ISSUE THREAD

**Issue by indytechcook** [department-of-veterans-affairs/va.gov-cms#4668]
## Description

While benchmarking the GraphQL calls in #4215 it was found the menu_breadcrumb module caused most of the performance issues. 

## Acceptance Criteria
- [ ] Find and document the bottle neck with menu_breadcrumb from within GraphQL.

**Comment by indytechcook** [comment]
Look in `MenuBasedBreadcrumbBuilder::build` and how it caches

**Comment by jkalexander7** [comment]
Closing - GraphQL performance is no longer a bottleneck for content build.
