### ISSUE TITLE
Jenkins intermittently Fails to Mount EFS Volume for Backup

### ISSUE THREAD

**Issue by olivereri** [department-of-veterans-affairs/va.gov-cms#4670]
Since recently (3/11/2021) changing infrastructure to use EFS, backup jobs to mount and tar asset files on EFS by Jenkins is failing:

```
10:17:09  TASK [cms-efs-backup : Mount EFS volume] ***************************************
10:17:09  Friday 12 March 2021  18:17:09 +0000 (0:00:00.614)       0:00:00.946 ********** 
10:21:45  fatal: [localhost]: FAILED! => changed=false 
10:21:45    msg: |-
10:21:45      Error mounting /tmp/cms-files-mount: mount.nfs4: Connection timed out
```

AC:
- [x] Investigate why Jenkins fails to mount EFS. 
- [x] Jenkins no longer fails to mount EFS.

**Comment by acrollet** [comment]
@olivereri what is the impact when this error occurs? Thanks!

**Comment by olivereri** [comment]
Mainly it was an issue for lower environments having stale assets and waiting longer for more fresh site assets from prod once the backup works correctly. That and if EFS failed completely for whatever reason, losing all data, the backup wouldn't have the most recent (past 15 minutes) of assets.

However, I already solved this and haven't had a failure since March 18th.  I must have rushed to get the work done and didn't update this ticket:

https://github.com/department-of-veterans-affairs/devops/pull/8730

I think it's safe to close this one.

**Comment by acrollet** [comment]
@olivereri awesome, thanks!
