### ISSUE TITLE
Jenkins intermittently Fails to Mount EFS Volume for Backup

### ISSUE THREAD

**Issue by olivereri** [department-of-veterans-affairs/va.gov-cms#4671]
Since recently (3/11/2021) changing infrastructure to use EFS, the [EFS backup job](http://jenkins.vfs.va.gov/job/cms/job/cms-efs-backup-prod/) to mount and tar asset files on EFS by Jenkins is failing:

```
10:17:09  TASK [cms-efs-backup : Mount EFS volume] ***************************************
10:17:09  Friday 12 March 2021  18:17:09 +0000 (0:00:00.614)       0:00:00.946 ********** 
10:21:45  fatal: [localhost]: FAILED! => changed=false 
10:21:45    msg: |-
10:21:45      Error mounting /tmp/cms-files-mount: mount.nfs4: Connection timed out
```

AC:
- [ ] Jenkins backup job successfully mounts EFS 99% of the time

TASKS:
- [x] Investigate why Jenkins fails to mount EFS
- [ ] Fix issue

**Comment by ElijahLynn** [comment]
One way to fix this is to have the Ansible task do some `retries`. Another way is to contact AWS Support.

**Comment by ElijahLynn** [comment]
We sized it a 2 per https://dsva.slack.com/archives/CJT90C0UT/p1615573640080900?thread_ts=1615573305.080600&cid=CJT90C0UT.

**Comment by olivereri** [comment]
I've figured this out. There errors only occur when the job is executed on a Jenkins worker node. Minor oversight and fix to allow EFS volume inbound Security Group rules to allow work nodes to connect over port 2049
