### ISSUE TITLE
UX prep for Q2 planning

### ISSUE THREAD

**Issue by rachel-kauff** [department-of-veterans-affairs/va.gov-cms#4673]
ACs
UX recommendations/work is reviewed, documented, and prepared for Q2 planning for:
- [x] OKR development
- [x] Major initiatives on the core and product roadmap
- [x] UX areas of focus that aren’t already on the roadmap
- [x] How priorities might scale to an increasing team size/new structure

**Comment by jefflbrauer** [comment]
Roadmap: https://app.lucidchart.com/lucidchart/c349f237-2841-47eb-9283-c533978af85c/edit?page=0_0#
