### ISSUE TITLE
Behat: FE request: "Not acceptable format: static_html "

### ISSUE THREAD

**Issue by ElijahLynn** [department-of-veterans-affairs/va.gov-cms#4674]
## Description

When visiting the URL with the query param `_format=static_html` a PHP Error is created in the logs. 

Backstory on the `_format=static_html` is that it was created as a way to test that the frontend web build that we run actually creates changed output. We build the content on a different web URL, but don't use this URL because we don't actually use that on BRD, only CI. See the va_gov_preview module.

`_format=static_html` gets routed through Drupal and then serves the static content from the docroot/static folder. When loading the URL, the page does load fine. 

e.g. https://pr3148-p3b3hejxgypchlz0qwfqwzvju8pas7c5.ci.cms.va.gov/health-care/about-va-health-benefits/vision-care/blind-low-vision-rehab-services?_format=static_html

```
Symfony\Component\HttpKernel\Exception\NotAcceptableHttpException: Not acceptable format: static_html in Drupal\Core\EventSubscriber\RenderArrayNonHtmlSubscriber->onRespond() (line 30 of /var/lib/tugboat/docroot/core/lib/Drupal/Core/EventSubscriber/RenderArrayNonHtmlSubscriber.php).
```

![image](https://user-images.githubusercontent.com/1504756/111009627-05e9ed00-8349-11eb-922f-b82b5c848f6d.png)

## Acceptance Criteria
- [ ] Determine if it's correct to use `static_html` with  `_format`

**Comment by acrollet** [comment]
Related core issue with patch: https://www.drupal.org/project/drupal/issues/3035589

**Comment by acrollet** [comment]
We are no longer seeing this error on tugboat, closing.
