### ISSUE TITLE
Set value for Vet Center page introduction and country on prod using bulk update 

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#4685]
## Acceptance Criteria

- [x] Existing and Vet Centers nodes have the following page introduction 

```
We offer confidential help for Veterans, service members, and their families at no cost in a non-medical setting. Our services include counseling for needs such as depression, posttraumatic stress disorder (PTSD), and the psychological effects of military sexual trauma (MST). We can also connect you with more support in VA and your community.
```
- [x] Existing Vet Centers have their country set to "None". 

## Implementation

- [x] Modify field values for Vet Center nodes at https://prod.cms.va.gov/admin/content/bulk (practice first on staging)

**Comment by kaise-lafrai** [comment]
@kevwalsh Ready for review here: https://pr4687-iueceep7r8j4amz0y5tinjwjlom6rb8w.ci.cms.va.gov
