### ISSUE TITLE
Clarify logic for frontend build trigger

### ISSUE THREAD

**Issue by mchelen-gov** [department-of-veterans-affairs/va.gov-cms#4690]
## Acceptance Criteria
- [ ] 👀 **Needs design review** because the work involves changes to labels or other design elements 
- [ ] 🙈 Can be implemented without consulting design team members
- [ ] Testable_Outcome_X
- [ ] Testable_Outcome_Y
- [ ] Testable_Outcome_Z

**Comment by indytechcook** [comment]
@mchelen we have some tests already, what sort of tests were you talking about?

**Comment by mchelen-gov** [comment]
@indytechcook oops i meant to update the title, mainly the goal was to refactor this a bit for readability and wanted to make sure it wasn't breaking anything
