### ISSUE TITLE
Drupal Application integration with Sentry

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#4695]
## Acceptance Criteria
- [ ] Drupal Application integration with Sentry is configured using contrib [Raven](https://www.drupal.org/project/raven)
- [ ] PHP Errors, Exceptions, SQL Deadlocks from the Drupal application [DEV, STAGING, PROD] instance are flowing into Sentry

## implementation notes
- look into settings.php to differentiate between environments

**Comment by indytechcook** [comment]
PR for devops: department-of-veterans-affairs/devops#9661

**Comment by indytechcook** [comment]
Anohter Devops PR: https://github.com/department-of-veterans-affairs/devops/pull/9676

**Comment by indytechcook** [comment]
The issue which is being thrown in sentry but not caught anywhere 
```
The option "release" with value Gitonomy\Git\Commit is expected to be of type "null" or "string", but is of type "Gitonomy\Git\Commit".The option "release" with value Gitonomy\Git\Commit is expected to be of type "null" or "string", but is of type "Gitonomy\Git\Commit".```

**Comment by indytechcook** [comment]
PR to do fix: https://github.com/department-of-veterans-affairs/va.gov-cms/pull/5989

**Comment by indytechcook** [comment]
I logged https://github.com/department-of-veterans-affairs/va.gov-cms/issues/5990 as a follow-up to get rid of the silent failure.

**Comment by indytechcook** [comment]
We are getting errors logged into sentry

from migration cron run: http://sentry.vfs.va.gov/organizations/vsp/issues/44283/?project=14&query=is%3Aunresolved

Releases are working: http://sentry.vfs.va.gov/organizations/vsp/projects/vsp-cms-drupal/?project=14

`cms-prod` search: http://sentry.vfs.va.gov/organizations/vsp/issues/searches/66/?project=14&query=is%3Aunresolved+environment%3Acms-prod&statsPeriod=14d
