### ISSUE TITLE
GraphQL Performance Monitoring & Alerts

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#4697]
### User Story or Problem Statement

As a CMS Engineer, I need to know how GraphQL query for content release is performing over time, so that I consider optimization strategies and have data to compare GraphQL performance in context of other system performance indicators.

### Affected users and stakeholders

* CMS Engineers
* CMS POs

## Acceptance Criteria
- [x] CMS team has access to GraphQL Content Release query performance over time
- [x] CMS team is alerted when the query time exceeds 30 minutes

**Comment by mchelen-gov** [comment]
Can we run bash script on Prometheus to pull data from Jenkins? https://github.com/department-of-veterans-affairs/va.gov-cms/pull/5111/files

**Comment by mchelen-gov** [comment]
for GQL query time threshold it would probably be anything that affects:
- hourly content publishing
- [VAMC banner alerts](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/cms/features/vamc-banner-alerts) (idk what our SLO is for this?)

**Comment by acrollet** [comment]
@kevwalsh @swirtSJW @jefflbrauer are any of y'all aware of a specific SLO for VAMC banner alert publishing time?

**Comment by acrollet** [comment]
@mchelen I'm choosing 30 minutes for the GQL alert threshold based on our objective in #4396 and an assumption that a < 30 minute GQL time will allow content builds in < 1 hour.

**Comment by mchelen-gov** [comment]
is this complete?
