### ISSUE TITLE
CMS team is alerted in Slack when the GraphQL query time exceeds certain thresholds

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#4701]
## Description

As a devops engineer, in order to meet our content build performance commitments, I need to receive timely notifications when the GraphQL query time exceeds our commitment threshold.

## Implementation
- Script approach, run every 5 minutes and cache build number. If new build number, check GraphQL query time for this build and alert if over threshold
- Use Prometheus Alert Manager

## Acceptance Criteria
- [ ] A message with "warning" status is posted once per unique build to the #cms-notifications Slack channel when the total GraphQL query time (GQL_Time metric) for the last build exceeds 15 minutes.
- [ ] A message with "critical" status is posted once per unique build to the #cms-notifications Slack channel when the total GraphQL query time (GQL_Time metric) for the last build exceeds 30 minutes.

**Comment by mchelen-gov** [comment]
this refers to query time for content builds "GQL_TIME"
it's currently around 3m, we might want to have a "warning" alert at 15m and "critical" at 30m
