### ISSUE TITLE
CMS Team Pipeline Scope

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#4720]
## User Story

As a CMS Engineers, I need to receive only the pipeline failure notifications that I'm responsible for in the channel that is monitored by the CMS team.

## Problem statement 

CMS team is not responsible for triaging build problems that are unrelated to CMS systems.

**For example, the CMS team does not own the `vets-website` codebase and build system so it is not CMS team responsibility to triage errors from this.**

## Acceptance Criteria
- [x] a process has been established that describes responsibility for triaging content release failures
- [x] Content Release failures that are responsibility of the CMS team to monitor are send to a channel monitored by the CMS team

## Examples of triage performed by CMS, but was outside team scope and root cause was not in CMS

1. https://dsva.slack.com/archives/C0MQ281DJ/p1615903548001300 
2. https://dsva.slack.com/archives/C0MQ281DJ/p1615986172000400

## Implementation notes

- understand which Content Release failures are CMS responsibility
- agree on the channel for monitoring
- update alert logic to send to appropriate channel
- agree on team norms for monitoring Content Release failures
- share team norms w/ other affected teams - FE tools

Related to #4382

**Comment by acrollet** [comment]
Documenting examples of content release build failures that the CMS team does not have the ability to resolve:

| Date | Description | Links/references|
--------------------------------------
| Mar 16 | vets-website build failure failed build | https://dsva.slack.com/archives/C0MQ281DJ/p1615903548001300 |

**Comment by mchelen-gov** [comment]
q: what category should https://dsva.slack.com/archives/CJT90C0UT/p1616079950003300 be in?

**Comment by mchelen-gov** [comment]
@acrollet thanks this is helpful! wasn't the [broken link error](https://dsva.slack.com/archives/C01FMRGRAGY/p1616169829082200?thread_ts=1616165323.072100&cid=C01FMRGRAGY) caused by Drupal content?

**Comment by mchelen-gov** [comment]
@oksana-c probably the AC for this could be tweaked to something like:
- create and document recommendation for what build failure alerts should or should not be triaged by CMS team
- create and document recommendation for what alerts should be directed to which channels
- define escalation path to CMS team for alert types where CMS team does not have triage responsibility
- include examples of each alert type for reference

then i can have a followup ticket to review & confirm with other team leads

**Comment by acrollet** [comment]
> @acrollet thanks this is helpful! wasn't the [broken link error](https://dsva.slack.com/archives/C01FMRGRAGY/p1616169829082200?thread_ts=1616165323.072100&cid=C01FMRGRAGY) caused by Drupal content?

@mchelen this is definitely a gray area, the broken link error occurred because the FE build has an embedded assumption that past events will exist, and breaks if none do. (This shouldn't have to be true when creating a new VAMC)

**Comment by jefflbrauer** [comment]
@acrollet @erogray If we can commit to SLA's regarding content deployment builds in this document, we should be able to satisfy the ACs for this ticket:

https://docs.google.com/document/d/1uc9s6EbHna_ZQXVMwg7qkNvWzw_sbH5xTvqSnSsaXwU/edit#heading=h.u66cnuxhe32l
