### ISSUE TITLE
Establish Process for tickets getting into backlog from HelpDesk Requests

### ISSUE THREAD

**Issue by VanessaLuxen** [department-of-veterans-affairs/va.gov-cms#4721]
## Acceptance Criteria
- [ ] Documentation needs to be created defining this process.
- [ ] Process should be discussed and agreed upon with team.

**Comment by cmaeng** [comment]
tabling until the new helpdesk manager has a chance to onboard.

**Comment by stefaniefgray** [comment]
Started creating mural for triage process: https://app.mural.co/t/agilesix2121/m/agilesix2121/1641231482103/0893b0970b185663a06835536642f7a6555bb936

**Comment by chriscraiga6** [comment]
https://agilesix.slack.com/archives/C01DTUNHFE2/p1645807800864969
