### ISSUE TITLE
Intermittent test failure: "Serialization failure: 1213 Deadlock found when trying to get lock;"

### ISSUE THREAD

**Issue by ElijahLynn** [department-of-veterans-affairs/va.gov-cms#4733]
**Describe the defect**
We are seeing intermittent failures of our test suite on DEV/STAGING with:
> Serialization failure: 1213 Deadlock found when trying to get lock; try restarting   

Here is the latest example:    

```
@BeforeFeature @mock_va_gov_urls #                                                                                 
CustomDrupal\ContentModelContextCustom::enableVaGovBackendHttpClient()

...


SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting                ┃ transaction: INSERT INTO {cache_config} (cid, expire, created, tags, checksum, data, serialized) VALUES    
```  

![image](https://user-images.githubusercontent.com/1504756/111672260-05cd6f80-87d7-11eb-840b-59f13acb263c.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information if relevant, or delete):**

**Additional context**
Add any other context about the problem here. Reach out to the Product Managers to determine if it should be escalated as critical (prevents users from accomplishing their work with no known workaround and needs to be addressed within 2 business days).

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Defect")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS objective (orange) (not needed for bug tickets)
- [ ] CMS-supported product (black)

**Comment by ElijahLynn** [comment]
Possibly related: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/2012

**Comment by ElijahLynn** [comment]
I wonder if it is because the `install()` does a cache rebuild. We have seen other flickers that do a cache rebuild as well causing this too. 

https://github.com/department-of-veterans-affairs/va.gov-cms/blob/0c5a8770fbf72a24254b4f5a8f4b5801a3d6f509/tests/behat/Drupal/ContextBase.php#L26-L33

**Comment by ElijahLynn** [comment]
> We have seen other flickers that do a cache rebuild as well causing this too

Found this > https://dsva.slack.com/archives/CJT90C0UT/p1614897469042800

```
And my workbench access sections are set to "165"                                                                    
14:37:49     ┃ # CustomDrupal\FeatureContext::myWorkbenchAccessSectionsAreSetTo()                                                   
14:37:49     ┃                                                                                                                      
14:37:49     ┃       SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting             ┃ transaction: INSERT INTO {cache_config} (c
```

Which was fixed in https://github.com/department-of-veterans-affairs/va.gov-cms/issues/4586.

**Comment by ElijahLynn** [comment]
Happened again today.

**Comment by ElijahLynn** [comment]
Happen again today.

**Comment by mchelen-gov** [comment]
^ https://dsva.slack.com/archives/CT4GZBM8F/p1617393602279600

**Comment by acrollet** [comment]
I'm not seeing any failures in the build history for the dev or staging job, iceboxing this to re-visit if it crops up again. (We believe that the memcache deployment should also mitigate this issue)

**Comment by ndouglas** [comment]
Closing; this hasn't happened in a looooooong time.
