### ISSUE TITLE
Display VAST data in non-editable display on Vet Center forms

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#4739]
This is a followup from #4531 / #4738

## User Story or Problem Statement

VAST data should be visible but not editable by VHA facility editors (Vet Center, VAMC facility, Vet Center MVC, Vet Center Outstations). 

VAST data should appear just like Centralized content. 

On VAMC facilities, we hide 

<details>
 <summary>See design for Vet Center form</summary>

![Vet_Centers_–_Figma.png](https://images.zenhubusercontent.com/5d6e57ad330f64311395f08b/0e09cb34-3d95-4d47-9b9e-53bacc7d2a41)
</details>

<details>
 <summary>See current implementation for Vet Center (as editable fields)</summary>

![Edit_Vet_Center_Helena_Outstation___VA_gov_CMS.png](https://images.zenhubusercontent.com/5d6e57ad330f64311395f08b/8a394356-692c-412a-a14b-e343a4932edf)
</details>

<details>
 <summary>See current implementation for VAMC facility fields (as disabled fields)</summary>

![Edit_VAMC_Facility_Pittsburgh_VA_Medical_Center-University_Drive___VA_gov_CMS.png](https://images.zenhubusercontent.com/5d6e57ad330f64311395f08b/9057e0c6-f1da-4b99-9913-4d9e2a9ee329)
</details>

Occasionally, we may want content admins and admins to be able to edit this content in an emergency (if VAST data is wrong and cannot be updated). 

## Acceptance Criteria
- [ ] `title`, `field_facility_api_id`, `field_office_hours`, `field_phone_number` and `field_address` are shown in non-editable form on vet_center forms. 
- [x] "Facility Locator API ID" label has been renamed to "Facility ID"

## Implementation ideas

- Disable form fields but display those fields as if it was node view 
- Create a view and embed in a fieldset? eg with `views_embed_view`
- Leveraging centralized content
- Two fields that are synced
- Theme fields to look like content

**Comment by kaise-lafrai** [comment]
docroot/modules/custom/va_gov_consumers/va_gov_consumers.module
_vagov_consumers_modify_va_form_fields
