### ISSUE TITLE
Support Mobile VHA clinic data in CMS

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#4743]
## Background

See https://github.com/department-of-veterans-affairs/va.gov-team/issues/21781

### User Story or Problem Statement

As a Veteran, i want info about mobile VAMCs

As a FE dev on Facility Locator or VAMC templates, i want to be able to distinguish mobile VAMCs in my queries so that i can display them accordingly.  FE issue [insert here]

## Background

* just don't publish the facility node. 
* don't publish the facility node, but use facility service delivery locations for other facilities. (eg xray machines that move around)
* roving facilities that get published. 

We need to wait for Leyda's full analysis and recommendations before moving forward on anything. 

Types of CMS work still coming, Q4 2021
- some content model work (will block FE work): mobile attributes, possibly roving locations. 
- some editorial experience work ("don't publish unless" OR guardrail to prevent publishing for facilities with certain attributes. 
- possibly Facility API -> CMS migration work
- possibly CMS -> Lighthouse 
- training and change management

VAMC team will analyze what VAMC systems may be blocked from full launch until this will be resolved.

### Affected users and stakeholders

* Facilities team

**Comment by mmiddaugh** [comment]
closing this epic as all issues are complete and future work can be captured in #12923
