### ISSUE TITLE
Add mobile flag to VAST facility migration

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#4745]
## User Story or Problem Statement

VAST contains data about what facilities are "mobile" VAMC clinics. 

This should be migrated into the content model developed in #4744

## Acceptance Criteria
- [ ] All VAMC facilities flagged as mobile in VAST are also flagged in the CMS

## Implementation details
- [ ] Add to the migration `migrate_plus.migration.va_node_health_care_local_facility.ym` lto populate field_mobile with TRUE if the "mobile" flag is true in the record in vast. 
- [ ] add the field to the overwrite properties in migration.
![image.png](https://images.zenhubusercontent.com/5dcda45425f6cc0001763cb5/524e9d1e-c4b1-4447-a8ed-20c874828c15)
- vast data can also be null or false.  But baset he true or false of field_mobile ONLY if `mobile: true `   All others get False.

## Deployment Steps 
- Run the migration on prod with an update flag set to true.  
- [ ] visit https://prod.cms.va.gov/admin/structure/migrate/manage/facility/migrations/va_node_health_care_local_facility/execute
![image.png](https://images.zenhubusercontent.com/5dcda45425f6cc0001763cb5/14f9724d-b723-411c-ab92-5bde48ebed21)

Update VAST migration

**Comment by kaise-lafrai** [comment]
I upped the estimated points on this ticket because additional work needed to be done to update other migration scripts based of the changes that were made directly in the sync files.
