### ISSUE TITLE
Accelerated Publishing

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#4746]
### User Story

As a CMS user, I would like content to appear on VA.gov as close to the moment I click the publish button as possible so I have more control over the time my content is live. 

### Problem Statement

- The existing content publishing process is tied to a scheduled FE Tools team build process, originally designed for code deployments. Even though the initiative to separate the content build from the deploy process is underway, the time gains it brings are not sufficient for the VA.gov long-term content publishing strategy.
- Even with optimization and parallelization, the current graphQL benchmarking shows that the retrieval time will increase linearly with an increase in node count.
- OCTO-DE POs estimate the CMS will contain about 50,000 nodes by Q3 2021. Current graphQL benchmarking shows retrieval of this node count to be ~15 minutes. 
- The existing CMS of many products for VA stakeholders (TeamSite) enables publishing within a few minutes of clicking publish. The current publishing delay in the current stack is a disincentive for adopting the modernized va.gov. 

### Affected users and stakeholders

* CMS Editors
* VA Businesses looking to migrate to Drupal CMS
* OCTO-DE
* VFS Product teams (e.g. PW, Facilities)
* VSA Engineers
* CMS DevOps Engineers
* CMS Application Engineers
* CMS Experience
* CMS Training
* CMS Helpdesk
* VSP FE-Tools Engineers
* VSP Ops Engineers

### Hypothesis

We believe that designing and building a content delivery system that enables content publishing to Va.gov within 3 minutes, will:
* increase stakeholder and user confidence in publishing to VA.gov
* encourage VA businesses to join the new modernized VA.gov and subsequently improve Veterans' experience
* increase reliability of VA.gov content release process
* improve Developer Experience (DevEx) in managing content build pipeline and creating content templates and features on VA.gov

We believe that nearly instant publishing will represent a true modernization across the VA for CMS editors.

### Assumptions

* we have a clear expectation from OCTO-DE around maximum publishing time
* we have buy-in across the VA.gov ecosystem to implement recommended solution
* we have sufficient resources to implement recommended solution within the given timeline (End of Q3 2021)
* our ability to hit 3 minutes timeframe is not dependent on the number of published content in the CMS
* we are able to get the information that we need from other teams in an expedient manner
* new pipelines will be built on a new EKS/Argo/GHA infrastructure

## Acceptance Criteria
- [ ] Published content is delivered to VA.gov within 3 minutes

**Comment by jefflbrauer** [comment]
Closing this as it was an original catchall. 

Using now: 
[Initial Discovery Initiative](https://app.zenhub.com/workspaces/vagov-cms-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/4748)

[Future Discovery Initiative](https://app.zenhub.com/workspaces/vagov-cms-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/5657)
