### ISSUE TITLE
Editing Vet Center health services inline on the main Vet Center node. 

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#4747]
## User Story or Problem Statement

As an editor managing the Vet Center main location page, i want to edit or add health services "inline" on a Vet Center form. 

<details>
 <summary>See design for Vet Center form</summary>

![Screenshot_2021-03-19__1_07_PM](https://user-images.githubusercontent.com/643678/111817212-1d2e5a80-88b4-11eb-885c-f411c77fa301.png)
</details>

For this iteration towards MVP, we will not deliver on this entire design, but this gets us partway there. 

## ACs

- [ ] Create `field_health_services` entity reference field, with CER, to Vet Center services. *New March 22: **Label: "Services"***
- [ ] Create Corresponding Entity Reference between `vet_center:field_health_services` and `vet_center:field_office`. Follow the model of VAMC system health services relationship to VAMC system nodes. May need [this patch](https://www.drupal.org/project/cer/issues/3202624) (d9 or php 7.3.x)
- [ ] Form widget for Vet Center field_health_services: Inline Entity Form Table View mode

<details>
 <summary>See config screenshot</summary>

![Manage_form_display___VA_gov_CMS](https://user-images.githubusercontent.com/643678/111808630-91fc9700-88aa-11eb-9130-c39fb60e636e.png)
</details>

- [ ] IEF table view mode show the `field_service_name_and_descripti` and `field_body`, but not node title, and edit link. (enable the IEF table view mode at `/admin/structure/types/manage/vet_center_facility_health_servi/display` then configure visible fields at `/admin/structure/types/manage/vet_center_facility_health_servi/display/ief_table`

<details>
 <summary>See config screenshot</summary>

![Screenshot_2021-03-19__1_03_PM](https://user-images.githubusercontent.com/643678/111816959-cfb1ed80-88b3-11eb-9ba3-857390e547f5.png)
</details>

- [ ] 

## Example node to work with 

Escanaba Vet Center (node/3756/edit)

Facility health services already exist for Escanaba (see /section/veterans-health-administration/escanaba-vet-center), but may need to be bulk resaved for CER to function correctly.

**Comment by kaise-lafrai** [comment]
@kevwalsh Tried setting this up and getting the following error on edit/creation of a vet center node:

`The website encountered an unexpected error. Please try again later.

LogicException: Getting the base fields is not supported for entity type Corresponding reference. in Drupal\Core\Entity\EntityFieldManager->buildBaseFieldDefinitions() (line 209 of core/lib/Drupal/Core/Entity/EntityFieldManager.php).`

Here is a screen grab of the CER I created:

![image.png](https://images.zenhubusercontent.com/5f04cf76eb6c0026ebd18020/e810cb69-844e-4e2c-9e4a-dec06b54e4e0)

**Comment by kevwalsh** [comment]
Hey Kaise, i see that there's a d9 compatibility patch in composer.json

`"3197953 - Make d9 compatible": "https://www.drupal.org/files/issues/2021-02-11/3197953.patch",`

Check out the last comment here: https://www.drupal.org/project/cer/issues/3197953 ... Our d9 patch may be the source of the problem that the patch in https://www.drupal.org/project/cer/issues/3202624 is trying to address. I wonder if it's related to the issues you're seeing.
