### ISSUE TITLE
Accelerated Publishing: Problem space definition workshop

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#4749]
## User story

As an "Accelerated Publishing" team member, I need to understand the problem space in depth before attempting to recommend solutions, so that I can avoid risks and miscommunication down the road.

## Acceptance Criteria

- [x] Problem space definition workshop is designed
- [x] Problem space definition workshop sessions are help by the discovery team
- [x] Problem space is defined
- [x] Success north stars are hypothesized and documented 
- [x] Workshop outcomes are synthesized and the summary document is available for stakeholder reference in github, linked from this issue
   - [x] Final output is available as a markdown document in github
- [x] synthesis is shared w/ creators and decision-makers for feedback

## Notes

workshop is time-boxed to 2 sessions:
- 2hrs - group workshop - initial brainstorm
- 2hrs - group workshop part 2 - review synthesized material for gaps / iterate

Cross-functional team meets to define problem space.
disciplines to be present:
- Application Engineering
- DevOps Engineering
- FE Engineering
- Experience
- Helpdesk
- Training

## What are we trying to achieve / articulate?

* define team touchpoints for the discovery effort
* outline content publishing challenge
* outline effect on editors and their experience
* other stakeholder experience when it comes to publishing or managing groups of publishers
* identify all parties that may be involved in this effort
* knowledge gaps [preliminary list]
* risks / opportunities
* research needs
* other unknowns
* what success looks like?

## Workshop outcomes

   * written problem definition
   * hypothesis / success criteria / methods to validate
   * define stakeholders and decision makers
   * discovery objectives
   * ranked list of priorities for team's focus within given timeline
   * articulate known / unknown / info to be collected
   * etc

**Comment by acrollet** [comment]
@jefflbrauer will synthesize, @acrollet will review and convert to a markdown document in the va.gov-team repo. (new AP folder under https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/cms)

**Comment by jefflbrauer** [comment]
Synthesis Markdown File may be found here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/accelerated_publishing/problem_space_definition

**Comment by indytechcook** [comment]
Use this one instead https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/accelerated_publishing/problem_space_definition.md

**Comment by mchelen-gov** [comment]
can someone add the mural link to sythesis doc?

**Comment by acrollet** [comment]
> can someone add the mural link to sythesis doc?

done!

**Comment by jefflbrauer** [comment]
Synthesis here: 
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/accelerated_publishing/problem_space_definition.md

**Comment by acrollet** [comment]
todos for synthesis:

* cross-link other initiatives/projects (cms export, site-wide alerts, vamc content, increase content release cadence, gql queries)

**Comment by acrollet** [comment]
@mchelen-gov I've updated the problem space definition docs as requested for items where I was able to find relevant docs/PRs.
