### ISSUE TITLE
Details fieldgroups missing the triangle affordance that they are expandable/collapsible

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#4752]
**Describe the defect**

Collapsible fieldgroups lost their triangle on all forms.  Seems to affecting primarily Mac and Linux users of Chrome (eg folks who use SOCKS to access application). 

**To Reproduce**
1. Go to a form with a collapsible or collapsed fieldset, eg node/1010/edit
2. Note triangle is missing. 

**Expected behavior**
A triangle should provide an affordance that fieldgroup is expandable or collapsible.

**Screenshots**
![Edit_VAMC_System_Operating_Status_Operating_status_-_VA_Pittsburgh_health_care___VA_gov_CMS](https://user-images.githubusercontent.com/643678/111855265-45d94300-88fa-11eb-9901-987b8392cc62.png)

**Comment by ElijahLynn** [comment]
Do we know when they last worked? We can bisect a bit easier if we have a last known working date.

**Comment by ElijahLynn** [comment]
Just looked through all the Tugboat envs going back at least a month and they are all missing the collapsible fieldset on node/1010/edit. 

I do see them on your Clairo environment though, which is 3 months old.

**Comment by kevwalsh** [comment]
Thanks for looking through those! i first noticed it a couple days ago on prod, but it took a couples to find out that it wasn't just me. I'm guessing it disappeared Monday or Tuesday this week, as i'm pretty sure i would have flagged this earlier otherwise.

**Comment by kevwalsh** [comment]
I'm guessing this is a browser issue, not a regression in the application, which would explain why you couldn't find these when going back through PR history. 

I can only test on Chrome right now (my current SOCKS setup and a non-functioning local atm) but it's this bit here that is not working as expected. 

Next step: test on other browsers. 

![Edit_VAMC_System_Operating_Status_Operating_status_-_VA_Pittsburgh_health_care___VA_gov_CMS](https://user-images.githubusercontent.com/643678/111857010-0fed8c00-8905-11eb-9ec7-f9375c7b3144.png)

**Comment by kevwalsh** [comment]
Just realized that the user agent stylesheet is working as expected on github.com summaries, like the ones that appear on #4747.  What seems to be the difference is that `::marker` selector appears in the summary tag on github, but not on cms.va.gov. I don't understand how that marker markup gets injected in the dom, i don't think that comes from Drupal but 🤷 .

![Editing_Vet_Center_health_services_inline_on_the_main_Vet_Center_node__·_department-of-veterans-affairs_va_gov-cms](https://user-images.githubusercontent.com/643678/111857306-f0eff980-8906-11eb-8ea7-7d122ca7d121.png)

BTW here's some nice documentation about `<details>` https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details

**Comment by kevwalsh** [comment]
Per slack: this is affecting Chrome Version 89.0.4389.90 on Mac, and Chrome users (version?) on Linux, so only SOCKS users.

**Comment by swirtSJW** [comment]
![image](https://user-images.githubusercontent.com/5752113/112018335-d71c0580-8b04-11eb-8810-74dcf83ddcc2.png)
Toggling this off returns the triangle
![image](https://user-images.githubusercontent.com/5752113/112018377-e307c780-8b04-11eb-886a-89850847bb82.png)

**Comment by ElijahLynn** [comment]
> Per slack: this is affecting Chrome Version 89.0.4389.90 on Mac, and Chrome users (version?) on Linux, so only SOCKS users.

Dang, that is odd!

**Comment by ElijahLynn** [comment]
For me on Linux and SOCKS:
1. Brave | 1.21.77 Chromium: 89.0.4389.90 (Official Build) (64-bit) - NO WORKY :stop_sign: 
1. Firefox 86.0.1 (64-bit) - WORKS!! :heavy_check_mark: 
![image](https://user-images.githubusercontent.com/1504756/112229215-cd230100-8bef-11eb-9956-04a261791011.png)

**Comment by kevwalsh** [comment]
This problem went away for me at some point, not sure when.
