### ISSUE TITLE
Standardize Urgency of Help Desk Tickets

### ISSUE THREAD

**Issue by joshworkscivicactions** [department-of-veterans-affairs/va.gov-cms#4757]
## User Story or Problem Statement

As a Help Desk User, I need to know the urgency and importance of incoming tickets so I can triage it effectively.

or

Problem description. How might we better align the various forms and points of entry for a Help Desk Ticket so that the Urgency and Priority of tickets are aligned with the SLA terms and other documentation that references Defects and Incidents?

## Implementation steps
Review all related documents that contain Urgency or Importance verbiage (priorities, urgency, GitHub _Backlog_ classifications, SLAs, etc)
Align the various terms to conform with SLA verbiage.

**Comment by stefaniefgray** [comment]
Ticket can be closed

Priority levels per SLAs are outlined in https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/helpdesk/service_level_agreement.md
