### ISSUE TITLE
Content Admins should not be able to administer media library settings

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#4787]
**Describe the defect**

when logged in as a Content Admin, the user can gain access to Configuration > Media > Media Library Settings | Media Settings.

<img width="950" alt="Screen Shot 2021-03-24 at 6 33 40 AM" src="https://user-images.githubusercontent.com/16477724/112311737-a6a2ab80-8c6b-11eb-9443-f888830800f2.png">

Content Admins should not be able to administer media library settings.

**To Reproduce**
1. Login as `suzanne.middaugh@va.gov`
2. In Admin Toolbar, hover over "Configuration", see child links.

**Expected behavior**
Content Admins should not be able to administer media library settings or "Configuration" menu.

## Acceptance Criteria
- [x] Validate that this is stil an issue, on staging.
- [x] "Administer Media" permission is removed for Content Admin role
- [x] Content Admins do not see "Configuration" menu when logged in
- [ ] Content Admins have been given permission to edit, create any media type.

Stretch: 
- [x] Tests for permissions per role are updated
- [ ] Test is written to validate that no other roles besides Administrator have access to "Configuration" menu.

**Comment by netboss** [comment]
@kevwalsh 
I already disabled the administer media permission for the "Content admin" role, but there is another permission showing up in the configuration menu and this is requesting that a "Content admin" shouldn't have access to anything under the configuration menu:

> **Expected behavior**
>Content Admins should not be able to administer media library settings or "Configuration" menu.

[permissions.pdf](https://github.com/department-of-veterans-affairs/va.gov-cms/files/8091490/permissions.pdf)

Should I also disable the "Administer cms custom menu access" permission for the "Content admin" role?

**Comment by kevwalsh** [comment]
@netboss yes, let's remove that. should be admin only.
