### ISSUE TITLE
Update User Admin role permissions

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#4790]
## Problem statement

Some permissions that are granted to the User Admin role make no sense and pose content integrity risks.
Even though we have not given the User Admin role to any users without accompanying roles like Content Admin, we still need to ensure that permissions system is reliable.

This issue is currently lower priority until we kick off User Administration Epic.

**Permissions to remove**
- [x] Break content lock
- [x] Access the Files overview page
- [x] Administer content
- [x] Access the Content overview page 
- [x] Notify of Path Changes
- [x] Determines whether or not users are notified.
- [x] Administer menus and menu items
- [x] Use the administration pages and help
- [x] Batch update section assignments for content
- [x] Perform batch section assignments from the content overview page.

**Permission to add** 
- [x] Assign Content creator - Office role
- [x] Assign Content creator - Vet Center role

The advantage of normalizing User Admin permission will also be reflected in an uncluttered admin toolbar.

Resulting menu for a user w/ User Admin role (and no other roles) should look as follows
<img width="1089" alt="Screen Shot 2021-03-24 at 8 29 00 AM" src="https://user-images.githubusercontent.com/16477724/112327827-5f241b80-8c7b-11eb-8a6a-141bf7cea9e3.png">

## Acceptance Criteria
- [ ] User Admin permissions are updated
- [ ] Permissions tests are updated

**Comment by kevwalsh** [comment]
Iceboxing this until we want to extend user_admin permissions to folks in the field.
