### ISSUE TITLE
CLP CX Survey

### ISSUE THREAD

**Issue by cmaeng** [department-of-veterans-affairs/va.gov-cms#4791]
## Description
As CLP is being rolled out, OCTO-DE would like to measure:
- Authoring Experience satisfaction
- Time to generate a CLP (ease of use)
- Time to launch a CLP (from stakeholder to audience)
- Would the user recommend this product to others?
- Was it of value?

## Acceptance Criteria
- [ ] Survey is designed
- [ ] Survey is disseminated
- [ ] Survey results are synthesized and any recommendations put into the backlog

**Comment by cmaeng** [comment]
Met with @johnhashva and @brianalloyd on 3/19/21 to scope out what this would look like. Needs some refinement and then prioritization from OCTO-DE against other initiatives.

**Comment by brianalloyd** [comment]
Posting a draft product survey created as an outline to showcase data points desired to collect from CLP users in order to affect future development a customer satisfaction.  @cmaeng @johnhashva 

![image](https://user-images.githubusercontent.com/70410912/113019265-a3f9f780-913e-11eb-91d9-c633428bbbf7.png)

**Comment by kevwalsh** [comment]
Timing for this, per @johnhashva on April 14: Send after 3 CLPs have been built.

**Comment by cmaeng** [comment]
Looking for CMS UX to scope out lightest way to accomplish this, possibly piggy-backing off of other research efforts. @johnhashva has mentioned that this is highly important to him but it hasn't been prioritized yet across other work. looking to clarify Q2 prioritization by 4/20/21. cc: @rachel-kauff @nataliedunbarCS @gujacq

**Comment by rachel-kauff** [comment]
@kevwalsh How does "after 3 CLPs have been built" translate into calendar time? When do we expect 3 CLPs to have been built?

**Comment by Agile6MSkinner** [comment]
This has been abandoned for a while and doesn't seem all that novel. Closing.
