### ISSUE TITLE
Examine the content build process

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#4794]
## User Story

As an Engineer,
I need to understand the current content build process, any upcoming planned iterations and take an inventory of all content sources and components that form the VA.gov,
so that I have an accurate account of all moving pieces and so that I am able to formulate validation steps for a new Accelerated Publishing solution.

## Acceptance Criteria
- [x] team gained access to latest documentation about
    - [x] the current content build process
    - [ ] upcoming content build separation process
    - [ ] any upcoming planned iteration that may affect the content build. E.g. 508 test suite
- [x] team has collected links to info sources relevant to the process
- [ ] documentation/diagrams list all sources that are used to generate static VA.gov content
- [ ] create diagrams to depict the current process
- [ ] ~any outdated docs are updated if feasible or update tickets created and assigned to current process owners~
    - Moved to https://github.com/department-of-veterans-affairs/va.gov-cms/issues/5082

**Comment by mchelen-gov** [comment]
relevant docs:

- https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/platform/architecture/static-site
- https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/platform/architecture/static-site/urls
- https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/platform/architecture/static-site/templates
- https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/platform/architecture/static-site/collections
- https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/platform/architecture/cms
- https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/platform/architecture/build-deploy-flows
- https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/getting-started/workflow/deploy
- https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/frontend/vets-website/architecture.md
- https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/design-docs/2020-04-09-separate-content-build.md

**Comment by acrollet** [comment]
The following AC has been split into #4975 to allow completion of this issue in this sprint.

- [ ] any outdated docs are updated if feasible or update tickets created and assigned to current process owners

cc @mchelen

**Comment by jefflbrauer** [comment]
@ncksllvn per your slack post, your initial pass at documentation is here:

https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/cms/content-release

**Comment by jefflbrauer** [comment]
@ncksllvn I think you should move those docs for now to 
https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/cms/accelerated_publishing

Also - I found this doc related to banner alerts we should include:
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/banners/banner-alerts.md

**Comment by ncksllvn** [comment]
> @ncksllvn I think you should move those docs for now to
https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/cms/accelerated_publishing

Nice, will do, that directory just didn't exist yet when I made mine.

> Also - I found this doc related to banner alerts we should include:
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/banners/banner-alerts.md

I would rather not do that...that's a Public Websites product and it is a whole thing with many parties involved. The banners described specifically in that doc are also separate technology from the CMS banners. The banners in that doc are either hardcoded in vets-website code or in vagov-content (the homepage banner.)

**Comment by ncksllvn** [comment]
Some documents on this -

1. https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/cms/accelerated_publishing/content-build covers the Content Release as a whole. It summarizes the Content Build but it doesn't zero in on it w/diagrams or anything. I'm still figuring out my approach on that.
1. https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/accelerated_publishing/content-build/menus-widgets-apis.md covers how CMS data is used when the data doesn't represent a page. This document tries to cover the many questions/documentation requests that have come up on Slack that may help us understand the CMS integration as a whole.

**Comment by ncksllvn** [comment]
I moved the requirement for updating outdated docs into its own issue, so that we have a shot at closing this issue in a timely manner. That new issue is here, https://github.com/department-of-veterans-affairs/va.gov-cms/issues/5082.

**Comment by acrollet** [comment]
I updated the "team understands all content sources that are used to generate static VA.gov" AC to be less ambiguous: "documentation/diagrams list all sources that are used to generate static VA.gov content"

**Comment by mchelen-gov** [comment]
> > Also - I found this doc related to banner alerts we should include:
> > https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/banners/banner-alerts.md
> 
> I would rather not do that...that's a Public Websites product and it is a whole thing with many parties involved. The banners described specifically in that doc are also separate technology from the CMS banners. The banners in that doc are either hardcoded in vets-website code or in vagov-content (the homepage banner.)

@ncksllvn  that's sort of what i meant about the AC "documentation/diagrams list all sources that are used to generate static VA.gov content" because i wasn't sure if you were trying to cover `vagov-content` involvement in build process or not

**Comment by ncksllvn** [comment]
Ah okay - I'm covering the homepage banner and mentioned it here too, https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/accelerated_publishing/content-build/menus-widgets-apis.md. I'll try to pull apart what folks are thinking when they say banner alerts.,,

**Comment by ncksllvn** [comment]
Still doing some polishing, but the current illustration is here, https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/accelerated_publishing/content-build/content-build.pdf
