### ISSUE TITLE
Accelerated Publishing: UX Recruitment Strategy Validation and Research Guide Creation

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#4800]
## Acceptance Criteria
- [x] Draft user research guide (based on research plan documented in [4813](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/4813))
- [x] Draft recruitment schedule and email template 

VA research plan template: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/research-plan-template.md

**Comment by nataliedunbarCS** [comment]
Recruitment strategy: 

![image](https://user-images.githubusercontent.com/71678559/116581175-eabb4880-a8c8-11eb-89d6-bc9500bec884.png)

**Comment by nataliedunbarCS** [comment]
Research Guide: https://docs.google.com/document/d/1Y9Hck2pWqTlnfloDmPIayw12ITT2gSnb3ECIN2lp-6Q/edit?usp=sharing

Note that questions/tasks in this version of the guide may be changed or modified as needed depending on final confirmed list of participants.

**Comment by nataliedunbarCS** [comment]
The research plan and recruitment strategy has already been shared with the product owner. 
Acceptance criteria has been met and this issue can be closed.

**Comment by mchelen-gov** [comment]
Another VAMC editor who might be a good backup or for additional rounds would be Lisa Trombley who reported bug with Single Page Preview feature https://github.com/department-of-veterans-affairs/va.gov-cms/issues/5228
