### ISSUE TITLE
AP: Technical Research

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#4803]
## User Story

As an Engineer, I need to research the technical landscape for static site generators, incremental publishing, dynamic drupal / instant publishing, so that I can make informed decisions that will support VA.gov publishing strategy short/long-term.

## Acceptance Criteria
- the following deliverables are produced for each of the top 3 solutions identified in #4810: (Per-page/section builds with current architecture, React/other JS framework client side application with access to live content API and Fully coupled Drupal)
   - [ ] high-level technical description
   - [ ] hypotheses for positives
   - [ ] diagrams
   - [ ] unknowns/pain points identified during discovery are documented
   - [ ] identified and shared/reviewed any case studies / publications / third-party tools / technical docs with the discovery team
- [ ] medium-fidelity design documentation comprising the above items has been created and socialized to OCTODE
- [ ] identified a shortlist of POCs and created issues with firm ACs for evaluation and comparison of each option
   - risks, unknowns and pain points are addressed, in particular the following items identified in #4809:
      - complexity (the current process is extremely difficult to use & update)
      - scalability (high confidence that the proposed solution can scale to 200k+ pages of content)
      - timeline (the current build process has a limited shelf life as the amount of content in the CMS grows rapidly)
      - longevity (developer availability/community support)
      - potential to completely obviate the current build process

**Comment by jefflbrauer** [comment]
@acrollet I think we can close this ticket as we agreed last week we will not be delving into as much detail for each of the three options before making a decision on roadmap (ie - which publishing methodology we will focus on first).
