### ISSUE TITLE
AP: Engineering Survey

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#4804]
## User Story

As an Engineer, I want to gather feedback about the current content build process from DSVA Engineers in an asynchronous manner, so that I can consider all ideas and viewpoints while designing a solution for the Accelerated Publishing.

## Dates for feedback collection 
3/29- 3/30

## Acceptance Criteria
- [x] Survey is designed and created in Google Forms or Survey Monkey depending on questions we want to ask
    - [x] discovery of current pain-points instead of suggested solutions
- [x] Survey comms prepared and shared in #content-release-engineering channel to collect data over 2 days
- [x] Survey results are processed and shared with the team for review/analysis

**Comment by jefflbrauer** [comment]
Survey responses are here:  https://docs.google.com/forms/d/1F-B5YA-02lrbWbJAe88Q5RhacIT9Wx4HsUnZjChFgqs/edit#responses

**Comment by jefflbrauer** [comment]
I've also included the top items engineers believe should be resolved to our problem space definition document.  [https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/accelerated_publishing/problem_space_definition](url)

**Comment by acrollet** [comment]
Attaching survey responses to this issue:

[VA.gov Content Release Process Feedback (Responses) - Form Responses 1.pdf](https://github.com/department-of-veterans-affairs/va.gov-cms/files/6286061/VA.gov.Content.Release.Process.Feedback.Responses.-.Form.Responses.1.pdf)
