### ISSUE TITLE
Add content type descriptions for all Vet Center content types

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#4807]
I'm assigning this to three people, we can determine later who has bandwidth for it. 

## User Story or Problem Statement

As a user on /node/add page, I understand what each content type is for. 
Highest priority: Vet Center CAP and Vet Center Health service, which can be created by local Vet Center editors

## Acceptance Criteria
- [x] All content types have editor-centered descriptions on /node/add

## Implementation steps

- [x] Write descriptions
- [x] Update config

![Add_content___VA_gov_CMS](https://user-images.githubusercontent.com/643678/112488450-ec3aa380-8d53-11eb-8068-3c26cae060f5.png)

**Comment by rachel-kauff** [comment]
@kevwalsh I think these should be written with a holistic view on content type descriptions in general. Since I already started working on content type descriptions, I think it makes sense to have me do it.

**Comment by kevwalsh** [comment]
@rachel-kauff i just saw your last comment 14 days ago _after_ I took a pass at this. This is not a sprint goal and we can just backburner this if you like. The two that matter the most are the Vet Center CAP and Vet Center Health service content types, since they are visible to Vet Center editors.

**Comment by rachel-kauff** [comment]
@kevwalsh At this point I don't think it won't hurt anything is we make further additions, just wanted to flag the need for a full pass on this.

**Comment by rachel-kauff** [comment]
@kevwalsh Some suggested edits based on [that content type description work](https://docs.google.com/document/d/1Pe6IbE-uoqorVYZUntPkHFCfR7PQOdGTovyMoZRjj1s/edit#heading=h.ue8jhn9pdopc) I started:

**Vet Center**
Location and page content for community-based counseling centers.

Vet Center - Community Access Point
Location information for Vet Center services situated in another organization.

**Vet Center - Facility Health Service**
Facility-specific description of a health service available at a Vet Center.

**Vet Center - Locations List**
Page content that lists all facilities associated with a Vet Center, including nearby locations.

**Vet Center - Mobile Vet Center**
Location information for Vet Center services provided out of an RV.

**Vet Center - Outstation**
Location information for remote facilities related to a main Vet Center.
