### ISSUE TITLE
Vet Center form implementation: Outstations, CAPs, Mobile Vet Center content types

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#4808]
## User Story or Problem Statement

As a Vet Center editor, i want all my facility's forms to follow the same patterns: Vet Center (done), Vet Center CAP, Vet Center MVC, Vet Center Outstation.

## Acceptance Criteria
- [x] Add "Editing this content" guidelines and TOCs to match design (screenshot below) on all 4 content types.  (see text and screenshot below)
- [x] Apply "external content" treatment to VAST data, to match Vet Center content type (Outstations and MVCs), for the following fields: `title`, `field_office_hours`, `field_phone_number`, `field_address`, `field_facility_api_id`
- [x] Update CAP form with field labels and field group to match design (screenshot below) as much as possible.
- [x] Update `field_media` on all four facility content types to 
  - [x] use the Media browser widget 
  - [x] order it the same 
  - [x] include the following help text 

```
<strong>Photo guidelines</strong>
✓ Smart phone photos are ok 
✓ Use landscape orientation 
✓ Show the entrance side of the building 
✗ No people 
✗ No car license plates
```

Not in scope
- [ ] Hours field UX (separate issue for that)
- [ ] Image field UX (beyond just the help text)

## Screenshot of design for top of forms, and CAP first fieldgroup

Text for "Editing this content" guideline:

```
Edit basic details about this satellite facility. Some content won’t be editable because it comes from other sources. Learn more by hovering over the “?.” For full guidance, see <a href="/help/vet-centers">How to edit Vet Center pages</a>.
```

![Vet_Centers_–_Figma.png](https://images.zenhubusercontent.com/5d6e57ad330f64311395f08b/fd27dcd4-e616-45df-9a5f-e3746f424156)

**Comment by kaise-lafrai** [comment]
@kevwalsh @rachel-kauff 

In regards to facility photo: I was able to alter the help text from "No media items are selected." to "Add a photo of a facility". I tried altering the button label but that didn't work out the same way the help text did. I timeboxed this work for an hours but can continue tackling media widget related work in future tickets. Please take a look at the preview environment!

**Comment by kaise-lafrai** [comment]
@kevwalsh @rachel-kauff 

Latest push can be found here: https://github.com/department-of-veterans-affairs/va.gov-cms/pull/4878
