### ISSUE TITLE
AP: Solution  Brainstorm [OPEN]

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#4809]
## Description

As an AP Discovery team Engineer, I need to open my mind to new opportunities and hear / consider _all_ ideas for solving Accelerated Publishing problem, so that we leave no stone unturned in researching the technical solution. 

As an Engineer, who touched content release process in any way, I want to share my ideas on how to make it better for everyone, so that the AP Discovery team can consider all possible solutions.

## Acceptance Criteria
- [x] Brainstorm session is designed. e.g. session flow, creative exercises, etc. [@acrollet @oksana-c ]
- [x] Attendees from various teams are invited
- [x] Brainstorm session is held (2hrs)
- [x] Brainstorm session is synthesized and actionable items are pulled into the technical research effort https://github.com/department-of-veterans-affairs/va.gov-cms/issues/4803

**Comment by acrollet** [comment]
Mural board: https://app.mural.co/t/vagov6717/m/vagov6717/1617812135638/dbca59b455f3ea2942bb95dc012b385651788c32

**Comment by acrollet** [comment]
@jefflbrauer  draft of synthesis follows, please review at your convenience.

# Open brainstorming workshop synthesis

## North Star

How might we achieve nearly instant publishing?

## Top voted solutions

### Incremental publishing of static content

#### Pains
- truly instant publishing cannot be achieved
   - not as good of an editor experience
- full site rebuild is still necessary in some instances
   - long builds are still a risk
- dynamic functionality is hard to achieve (search, content listings, etc)
- developer experience issues
   - local development is time-consuming
   - local development stack is complex

#### Gains
- good end user experience
   - fast page loads, downtime/security risk very low
- security
   - no direct access from outside world to content API
- developer workflow does not have to change
- content editor experience does not change
- build process can be architected in a massively parallelizable fashion

### Fully coupled Drupal (Drupal directly produces html content)

#### Pains
- security/downtime risks
- large migration effort required
- many developers would need to be re-trained
- new CMS deployment processes would need to be engineered
- link checking, accessibility testing would need to be re-built
- ATO approval required

#### Gains
- very fast publishing
- simpler tech stack / reduced technical debt / uses industry standard patterns
- preview experience would be much improved
- more control for editors / improved editor experience
- react/vue/other frontend frameworks can still be used in combination with this approach

### Decoupled Dynamic (live content API + JS front-end framework)

#### Pains
- decreased client performance, especially over slow connections (if server-side rendering not used)
- increased security risks
- ATO approval required
- API performance/permissions/rate limiting are a concern
- link checking, accessibility testing would need to be re-built
- caching layers add complexity/technical debt
- increased downtime possible
- global changes (header, menu etc.) need to be taken into account

#### Gains
- dynamic functionality such as search & lists is much easier to build
- publishing will be very quick
- no full-site static build process is necessary
- familiar pattern for modern front-end developers
- improved speed for site preview

## High Level Takeaways

### Opportunities

- Improve the developer experience (reduce onboarding time, increase speed of local development)
- PoCs for proposed solutions can and should be tested with extremely large amounts of content (200,000+ pages) to ensure they are scalable
   - comparable sites (in terms of amount of content & traffic) should be sought for each proposed solution

### Risks

- Timeline
   -  There is considerable risk of not having a new solution ready before the current build process reaches its limits
      - Any solution that requires ATO approval increases this risk
- Complexity (the proposed solution should *reduce* the technical debt & overall complexity)
- Technological preferences could drive the selection of an unproven approach
- A hybrid/incremental approach adds risk that the current build process is still around in some form for years to come

### Unknowns
- what longevity will the proposed solution have? (active support, developer community, etc)
- work ownership

**Comment by acrollet** [comment]
@mchelen please see the [synthesis above](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/4809#issuecomment-815276551). Thanks!
