### ISSUE TITLE
AP: Solution  Brainstorm [INTERNAL] 

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#4810]
## User Story

As an AP Discovery team Engineer, I need to review/discuss ideas from the Open Brainstorming session #4809 with the internal discovery team, so that we can zoom in on the most valuable and feasible approaches. 

## Acceptance Criteria
- [x] Brainstorm session is held (2hrs)
- [x] Up to 10 high-level architectures are identified and given a basic description
   - e.g. "Static site generated using Gatsby and react templates", "Static site with next.js and react templates"
   - [x] high-level changes from the current architecture are identified
- [x] Of the above proposals, top 3 options are selected and documented on #4803
- [x] Above items are added to ACs of #4811

**Comment by acrollet** [comment]
Mural board: https://app.mural.co/t/vagov6717/m/vagov6717/1617892974130/fcba837207d991133ec5111afdcccb7d27997a71

**Comment by acrollet** [comment]
## Potential PoCs (WIP)

### Per-page/section builds with current architecture

### Incremental publishing of static content (Service Bus Architecture)

### React SPA(s) with access to live content API

### Fully coupled Drupal

### React SPA(s) with statically cached content API output

**Comment by acrollet** [comment]
@jefflbrauer I've added high-level summaries in the comment above and I believe we're ready to close this out. Please review at your convenience :-)
