### ISSUE TITLE
AP UX discovery: conduct user interviews

### ISSUE THREAD

**Issue by rachel-kauff** [department-of-veterans-affairs/va.gov-cms#4815]
AC
- [x] Confirm interview sessions with users identified in #4800
- [ ] Conduct interviews with X users schedule in previous sprint.

**Comment by mchelen-gov** [comment]
where does raw or synthesized user interview data get captured?

**Comment by nataliedunbarCS** [comment]
@mchelen-gov Apologies. Meant to add this link to the raw user interview data: https://drive.google.com/drive/folders/1o0aiv9r9deSpDyCsdkNVQsJil-WOaML9

The data hasn't been synthesized yet, but when that happens, we'll create a space on github along with the research plan and similar documentation.

**Comment by acrollet** [comment]
@nataliedunbarCS are there any more interviews to go? Or can this be closed out? Thanks! :-)

**Comment by nataliedunbarCS** [comment]
@acrollet There's one last interview this afternoon at 2 PM PDT.
