### ISSUE TITLE
ElastiCache client is configured for High Availability (auto-discovery)

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#4817]
## Acceptance Criteria
- [ ] ElastiCache client is configured for High Availability

## Tasks

- [ ] AMI setup for ElastiCache auto-discovery client (high-risk, because on old version of PHP)
       * https://docs.aws.amazon.com/AmazonElastiCache/latest/mem-ug/AutoDiscovery.html
       * https://docs.aws.amazon.com/AmazonElastiCache/latest/mem-ug/Appendix.PHPAutoDiscoverySetup.Installing.html 
       * If this is too difficult, can fallback to manual cluster configuration and explore after we are on K8s (new PHP)

**Comment by olivereri** [comment]
https://git.drupalcode.org/project/memcache/commit/9b6bad8

**Comment by timcosgrove** [comment]
Decision was made not to move forward. Closing. https://dsva.slack.com/archives/C02HX4AQZ33/p1661900173643889
