### ISSUE TITLE
Configure Memcache PHP extension

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#4818]
## Acceptance Criteria
- [x] Memcache PHP extension is correctly configured and enabled
- [x] Env variable(s) for Memcache nodes exists for application consumption

**Comment by mchelen-gov** [comment]
is this for a particular environment, terraform script, lando config, etc?

**Comment by olivereri** [comment]
> is this for a particular environment, terraform script, lando config, etc?

Good question. This is aimed at out CMS-TEST Infrastructure that exists as a mirror to CMS Dev, Staging and Prod. We'll be setting this up for our parallel infrastructure in all 3 environments. The current Memcache infrastructure in #4458 is for CMS-TEST only.

**Comment by olivereri** [comment]
@ElijahLynn @indytechcook 

Confused by this AC.
>  Memcache PHP extension is correctly configured and enabled

There are a few parts to make AWS Elasticache using Memcache work on Drupal. First is just the Drupal Memcache Module and its configuration. _Second_ would be AWS's forked version of the pecl php extension for auto-discovery which is covered in #4817, correct?

This issue is just meant to get Memcache working without auto-discovery?

**Comment by ElijahLynn** [comment]
> This issue is just meant to get Memcache working without auto-discovery?
Correct. 

> _Second_ would be AWS's forked version of the pecl php extension for auto-discovery which is covered in #4817, correct?
Correct.

**Comment by olivereri** [comment]
If AWS Elasticache is not used or Auto-discovery is not used this extension should be installed:

`yum install php73-php-pecl-memcache`

**Comment by olivereri** [comment]
memcache.ini based off of extension defaults. Extension path and hash_strategy are the only attributes non-default.

```
extension=/opt/remi/php73/root/usr/lib64/php/modules/memcache.so
memcache.allow_failover=1
memcache.chunk_size=32768
memcache.compress_threshold=20000
memcache.default_port=11211
memcache.hash_function=crc32
memcache.hash_strategy=consistent
memcache.lock_timeout=15
memcache.max_failover_attempts=20
memcache.prefix_host_key=0
memcache.prefix_host_key_remove_subdomain=0
memcache.prefix_host_key_remove_www=1
memcache.prefix_static_key=
memcache.protocol=ascii
memcache.redundancy=1
memcache.session_prefix_host_key=0
memcache.session_prefix_host_key_remove_subdomain=0
memcache.session_prefix_host_key_remove_www=1
memcache.session_prefix_static_key=
memcache.session_redundancy=2
memcache.session_save_path=
```
