### ISSUE TITLE
Provide fetched data directly in EntityFieldFetched fields

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#4822]
## User Story or Problem Statement

As a front end developer, I need fetched content in entity field fetch fields to be provided directly in the field since they are not showing up correctly in graphQL as entity reference fields.

This will need an upstream change that is happening here https://www.drupal.org/project/entity_field_fetch/issues/3205747

Details to come based on some computed field limitations.

## Acceptance Criteria
- [ ] 👀 **Needs design review** because the work involves changes to labels or other design elements.
- [ ] 🙈 Can be implemented without consulting design team members
- [ ] Testable_Outcome_X
- [ ] Testable_Outcome_Y
- [ ] Testable_Outcome_Z

## Implementation steps
<optional>

**Comment by swirtSJW** [comment]
I have this working now locally.  
![image](https://user-images.githubusercontent.com/5752113/114032686-89183900-984a-11eb-90c0-4c7492237c03.png)

I checked with FE people to validate that this will give them what they need.

**Comment by swirtSJW** [comment]
This has been merged on drupal.org.

**Comment by kevwalsh** [comment]
and updated for us via https://github.com/department-of-veterans-affairs/va.gov-cms/pull/5000

**Comment by kevwalsh** [comment]
Reopening this because there's still some work to merge (in #4984)
