### ISSUE TITLE
Alert CMS team when periodic tasks job is disabled

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#4826]
## Description

Periodic tasks job for the CMS application supports several mission-critical processes. E.g. Facility status sync to the Lighthouse.

If the job is accidentally disabled, the Facility status information provided to Veterans at VA.gov is at risk of being outdated.

Related threads:
* https://dsva.slack.com/archives/CDHBKAL9W/p1616612186049200
* https://dsva.slack.com/archives/CT4GZBM8F/p1616612799384500

## Acceptance Criteria
- [ ] #cms-notifications channel or other communication channels (email, PD) is alerted when CMS periodic tasks job becomes disabled

## Implementation notes

Arranging an alert described in ACs will require a creation of a new Jenkins job (that is also at risk of being disabled without notice) or adding new Jenkins plugin. 
The CMS has been instructed not to build any new features on Jenkins, since Jenkins will be deprecated in favor of GHA by the end of 2021. 
As the CMS begins the move to GHA over the next 3 quarters, we should attempt to implement the periodic tasks job in GHA instead of building up Jenkins.

_A temporary solution would be to add a note about re-enabling periodic tasks job to deployment failure docs that we use to troubleshoot failures._

**Comment by acrollet** [comment]
Note has been added to docs: https://github.com/department-of-veterans-affairs/va.gov-cms/blob/master/READMES/devops/deploy-failure-troubleshooting-guide.md#post-tasks

**Comment by acrollet** [comment]
Noting that this is blocked by the migration from Jenkins to GH Actions.

**Comment by ElijahLynn** [comment]
I think that even if we have a way to check that the job is enabled then the job that checks that is at risk of being disabled. So, I think just having better deployment troubleshooting docs is the way forward here.

**Comment by ElijahLynn** [comment]
Might also consider that the job itself, even if enabled, could not work and we might want to put a metric in Prometheus and we can use Alert Manger to alert on that then.
