### ISSUE TITLE
Facilitate CLP beta tests with VHA editor

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#4838]
### User Stories
As a VA editor, I need to be able to create a campaign landing page to make Veterans and their families aware of a specific, targeted campaign.

### Acceptance Criteria
- [x] Tests observed March 31
- [x] March 31 observations collected and synthesized

**Comment by nataliedunbarCS** [comment]
Session 4: Test Observer notes: https://docs.google.com/spreadsheets/d/10GAM-mePTyYcbBixoWeWOaQAPXApK7a-V1s4c94F-hQ/edit#gid=0
