### ISSUE TITLE
CLP beta user synthesis

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#4848]
## User Story or Problem Statement

As a CMS team, we have documented opportunities to improve editorial experience for CLP . 

As a CMS/PW team, we have documented opportunities to improve the CLP product. 

## Acceptance Criteria
- [ ] We have a synthesis of research with CLP users
- [ ] More TBD

## Implementation steps
<optional>

**Comment by nataliedunbarCS** [comment]
Created synthesis template in GitHub: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/cms/research/campaign-landing-page
