### ISSUE TITLE
Vet Center MVP Dashboard implementation

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#4850]
## User Story or Problem Statement

As a Vet Center editor, i want a task-oriented dashboard so that i can edit content quickly.

## Acceptance Criteria

[The design](https://www.figma.com/file/885DMraAi9V2DLJnrIN7Wv/Vet-Centers?node-id=0%3A1) has been implemented as closely as possible in existing theme. 

## Implementation

(Possibly break this up into 3 issues)

Layout builder config for Vet Center dashboard page (@kevwalsh)
- [ ] #4855  

Dashboard switch
- [ ] `hook_entity_view_mode_alter()` to set the view mode based on a Sections product, traverse the parents and find the first parent with an assigned product 

Block types
- [ ] Card with one action, an edit link with anchor, that can detect context to build link
- [ ] Card with two actions View and Edit, that can can detect context to build links
- What to name these? "Content edit task"? 

![Vet_Centers_–_Figma](https://user-images.githubusercontent.com/643678/112855395-bf043300-907c-11eb-9acd-e570d2fa3efb.png)

## Assets

See icons for dashboard [vet-center-dashboard-icons.zip](https://github.com/department-of-veterans-affairs/va.gov-cms/files/6222006/vet-center-dashboard-icons.zip)

**Comment by cmaeng** [comment]
the big picture is to get VC training completed by sprint 30. so if this work is finished by mid-sprint 30 we should be on track.
