### ISSUE TITLE
Create shared understanding of Lighthouse / CMS facility migrations 

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#4857]
## User Story or Problem Statement

As a _____, I need _____ so I can _____.

or

Problem description. How might we _____________ ?

## Acceptance Criteria
- [ ] 👀 **Needs design review** because the work involves changes to labels or other design elements.
- [ ] 🙈 Can be implemented without consulting design team members
- [ ] Testable_Outcome_X
- [ ] Testable_Outcome_Y
- [ ] Testable_Outcome_Z

## Implementation steps
<optional>

**Comment by mmiddaugh** [comment]
Closing as this is a placeholder with zero detail
