### ISSUE TITLE
User admin service discovery 1 - planning

### ISSUE THREAD

**Issue by rachel-kauff** [department-of-veterans-affairs/va.gov-cms#4858]
AC
- [x] Rachel and Natalie have reviewed spike artifact
- [ ] Work has been further defined and roadmapped
- [x] We have prepared for service blueprinting work next sprint
  - [x] Met with Jane to understand current situation
  - [ ] Set up initial mtgs with potential users

**Comment by kevwalsh** [comment]
[Mural with discovery findings](https://app.mural.co/t/vagov6717/m/vagov6717/1617055079025/cf04924ba3ae38a32d2721fed6d2d1d74370b532)
