### ISSUE TITLE
Single Page Preview Technical Documentation

### ISSUE THREAD

**Issue by jefflbrauer** [department-of-veterans-affairs/va.gov-cms#4864]
##As an engineer on the va.gov project, I have documentation to understand how the single page preview is spawned from the Drupal CMS, including ownership over the various components.

## Acceptance Criteria
- [ ] A readme file is included in github for the single page preview feature that outlines :
- - [ ] How the feature works for CMS users
- - [ ] The technical architecture of the system
- - [ ] Team ownership of each component

**Comment by mchelen-gov** [comment]
how does "Single Page Preview" relate to "Preview Server" or [Tugboat](https://github.com/department-of-veterans-affairs/va.gov-cms-test/blob/master/READMES/tugboat.md)? (not sure if "Preview Server" = Tugboat or something else)

**Comment by mchelen-gov** [comment]
hmm i found these docs for Preview Server: https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/platform/architecture/cms

**Comment by mchelen-gov** [comment]
spun off ticket to differentiate from Preview Server: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/4885

**Comment by timcosgrove** [comment]
This is quite old and will be replaced over the coming year by Next Build preview. Closing.
