### ISSUE TITLE
"Preview Server" technical documentation

### ISSUE THREAD

**Issue by mchelen-gov** [department-of-veterans-affairs/va.gov-cms#4885]
## Description
"Preview Server" is https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/platform/architecture/cms

## Acceptance Criteria
- [ ] Preview server integration with CMS is documented internally in GH
- [ ] Preview server team ownership is documented internally in GH

**Comment by TheBoatyMcBoatFace** [comment]
Closing this as it is handled elsewhere. Reopen if necessary.
