### ISSUE TITLE
Iteration on VAMC Facility Health Service form

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#4887]
## User Story or Problem Statement

We have learned a number of things about the complex facility health service 

- "Online scheduling available" could lead to a bad experience if it's misleading Veterans 
- Editors don't know what "Unknown" means in the dropdowns. 
- There are multiple places to put in phone numbers (at the facility service level, and at the Service Location level). How can we make that less confusing. 

There are probably other issues that require research.

## Acceptance Criteria
- [ ] TBD

## Implementation steps
<optional>

**Comment by davidmpickett** [comment]
Proposal for VBA is moving appointment-related information for Facility Services into the Service Location paragraph type: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13128

Once we get closer to implementing the updates to Service Location paragraph type, this ticket can be used to track how that impacts the VAMC product suite
