### ISSUE TITLE
Allow centralized content to be removed in certain situations

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#4896]
## User Story or Problem Statement

In some situations we may require an urgent change to centralized content type, which will be locked down in #4056. 

What happens when we need a rapid change to the content model design? 

How might we create a process to allow national editors to trigger a change to the content model for content using centralized content. 

## Acceptance Criteria
- [ ] TBD

## Implementation steps
<optional>

**Comment by jilladams** [comment]
As of today, we don't know of examples for Vet Centers where have needed or will need to override this at the local level. Closing, and we'll make new with user stories if needed in future.
