### ISSUE TITLE
Drupal sends node count data to Prometheus

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#4898]
## User Story 

As a CMS Engineer, I need to send data from Drupal to Prometheus, so I can collect and display data overtime.

As a CMS Engineer, I need to ensure that Prometheus calls to Drupal application are not too frequent, so as not to add strain on the application infrastructure.

## Acceptance Criteria
- [ ] [Drupal contrib module](https://www.drupal.org/project/prometheus_exporter) is installed on Prod and sends total node count data (published + unpublished) to Prometheus 
- [ ] CMS Application dashboard is created in Grafana and shows a graph of total node count
- [ ]  Prometheus collects Drupal node data once an hour

## Implementation notes

https://www.drupal.org/project/prometheus_exporter

Collection frequency - https://stackoverflow.com/questions/58996273/prometheus-and-node-exporter-architecture

https://dsva.slack.com/archives/CBU0KDSB1/p1617305532177600

**Comment by ndouglas** [comment]
Reducing the estimate to reflect that this was refactored into multiple issues.
