### ISSUE TITLE
Drupal sends published node count to Prometheus

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#4900]
## User Story 

As a CMS Engineer, I need to send published node count from Drupal to Prometheus, so I can collect and display data overtime.

## Acceptance Criteria
- [ ] published node count is sent to prometheus
- [ ] Grafana chart for "Published Node Count" is created in the CMS Application dashboard is created shows a graph of published node count growth overtime
- [x] Plugin written for prometheus_exporter is contributed upstream (doesn't have to merged, just submitted)

## Implementation notes

New plugin is written for https://www.drupal.org/project/issues/prometheus_exporter contrib and contributed upsteam.

**Comment by ndouglas** [comment]
[Patch created and submitted in this issue](https://www.drupal.org/project/prometheus_exporter/issues/3214628).

**Comment by ndouglas** [comment]
Yeah, probably worth splitting it out.  

Elijah, Eric and I worked on the PR on the devops side of this, but it's not merged or deployed and the Grafana stuff can't be done until that's in place, but the Drupal side is all done and ready to be merged once I get another test failure or two identified and fixed.  The Prometheus/Grafana stuff could still get done today/tomorrow, depending on everyone's capacity and things going our way.  

But IMHO the Grafana/Prometheus work is a distinct chunk and should've been split out from the beginning.

**Comment by acrollet** [comment]
Chart AC split into #5407
