### ISSUE TITLE
Drupal sends User count data to Prometheus

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#4902]
## User Story 

As a CMS Engineer, I need to send the number of total / active / blocked users from Drupal to Prometheus, so I can collect and display data overtime.

## Acceptance Criteria
- [ ] Drupal sends the number of total / active / blocked users to Prometheus 
- [ ] Grafana chart for "Active User Count vs Total User Count" is created in the CMS Application dashboard is created shows a graph of total + active + blocked user count overtime
- [ ] Prometheus collects Drupal user data once an hour

**Comment by ElijahLynn** [comment]
Here is the config where we can set the scrape interval and create a new scrap job > ansible/deployment/config/prometheus/prometheus.yml.j2. We probably need to figure out how to "run_once" as eventually we will have more servers horizontally scaled and the data will be the same on all of them.

**Comment by ElijahLynn** [comment]
/metrics is endpoint e.g. https://cms-1znfkzo4zgyx4dnlsgq0cipcdunevfdc.ci.cms.va.gov/metrics

```
# HELP drupal_node_count_total Total node count.
# TYPE drupal_node_count_total gauge
drupal_node_count_total 18713
drupal_node_count_total{status="published"} 12902
drupal_node_count_total{status="unpublished"} 5811
# HELP drupal_user_count_total Total user count.
# TYPE drupal_user_count_total gauge
drupal_user_count_total 367
drupal_user_count_total{status="activated"} 366
drupal_user_count_total{status="blocked"} 1
```
