### ISSUE TITLE
Nested fieldgroups for centralized content and external content should have no stroke

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#4905]
## Description

![Create_Vet_Center_Outstation___VA_gov_CMS](https://user-images.githubusercontent.com/643678/113349806-98592d00-9306-11eb-8150-6b9f3bbcf215.png)

## Acceptance Criteria
- [ ] 👀 **Needs design review** because the work involves changes to labels or other design elements 
- [ ] 🙈 Can be implemented without consulting design team members
- [ ] Testable_Outcome_X
- [ ] Testable_Outcome_Y
- [ ] Testable_Outcome_Z

**Comment by msbtterswrth** [comment]
@kevwalsh i think we're solving this in the design system, should we close this in favor of one of the newer tickets for that?

**Comment by wesrowe** [comment]
This does not seem to be CLP-related. I propose closing it. @jilladams @xiongjaneg, does this mean anything to you?

**Comment by xiongjaneg** [comment]
Goodness, look at the date on that. I'd be in favor of closing given the many changes to centralized content and design system since then.

**Comment by swirtSJW** [comment]
This is no longer an issue
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5752113/4c764062-aab0-4b40-b943-179e8976273b)
