### ISSUE TITLE
A Content Creator does not have the option to logout

### ISSUE THREAD

**Issue by VanessaLuxen** [department-of-veterans-affairs/va.gov-cms#4918]
## Background

A user was changed to a content creator role only and now they do not have access to the logout button in the header and cannot log out of the production site. 

Issue discovered by Help Desk while changing editor roles to block them from publishing content before it should be published.  

## Acceptance Criteria

- [ ] All logged in users have access to view the user actions menu in the admin toolbar, including the "Log out" link

**Comment by acrollet** [comment]
Verified defect 9/20/21

**Comment by netboss** [comment]
@swirtSJW @kevwalsh 
Started looking at this issue. If you guys need me to work on other things please let me know.

To my limited experience with the VA permissions this seems to be a toolbar access/permissions issue with all "Content Creator *" roles. See screen shot.
![VACMS-4918-toolbar-permissions](https://user-images.githubusercontent.com/846871/152553357-e73f663e-43dd-408b-840a-164fa4c5e3f9.png)

@swirtSJW What's the best/correct approach to deal with this?

**Comment by kevwalsh** [comment]
@netboss  i think we should probably give all authenticated users access.  I've updated ACs.

**Comment by kevwalsh** [comment]
Oh, that already is the AC, basically. Authenticated user should have "Use the toolbar".
