### ISSUE TITLE
Add abbr support to WYSIWYG

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#4920]
## User Story or Problem Statement
As an editor, I need to be able to add `abbr`  tag with  a 'title' attribute to paragraphs and headings so that I can attain 508 compliance on my content.

Currently this tag and the title attribute are stripped from the WYSIWYG however this module on CKeditor 5 should solve this: [CKEditor Abbreviation](https://www.drupal.org/project/ckeditor_abbreviation)

I reviewed this module and it does what we want however I was not able to review this in D10, only the previous D9 version so my recommendation is based on that.

Related front end issue https://github.com/department-of-veterans-affairs/va.gov-team/issues/20238

## Acceptance Criteria
- [x] Confirm with PO if CKEditor Abbreviation module is appropriate solution
- [ ] Determine tech feasibility of installing [CKEditor Abbreviation](https://www.drupal.org/project/ckeditor_abbreviation) module in D10
- [x] Create change management ticket for update

**Comment by laflannery** [comment]
Created [change management ticket](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14114)

**Comment by laflannery** [comment]
Talked to Edmund about the tech piece of this:
- We can install the 4.0.0-alpha1 release 
  - There might be a different release by the time we are ready to install but at this time this would be the one
- We will obviously test and install this release in our D10 version to confirm everything is working as expected but neither of us is expecting any issues
