### ISSUE TITLE
Implement memcache data caching in production

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-cms#4929]
## Acceptance Criteria
- [x]  create runbook
- [x] follow runbook and deploy to production
  - [ ] monitor performance post-deploy
- [x] communicate deployment status to team members

**Comment by acrollet** [comment]
Documenting discussion with @mchelen-gov, we may push this deployment to the next sprint if extra time is necessary for intra-team socialization of the changes and/or documentation.

**Comment by olivereri** [comment]
1. Infrastructure
   1. Update Terraform Code
      1.  `devops/terraform/environments/dsva-vagov-dev/cms.tf`  change module `source` version from v1.6.1 to v1.7.0
      1.  `devops/terraform/environments/dsva-vagov-staging/cms.tf`  change module `source` version from v1.6.1 to v1.7.0
      1.  `devops/terraform/environments/dsva-vagov-prod/cms.tf`  change module `source` version from v1.6.1 to v1.7.0
   1. Apply Terraform Changes to:
      1. Dev
      1. Staging
      1. Prod
1. Software Dependencies 
   1. Build
      1.  `devops/ansible/build/roles/cms/meta/main.yml` Add `php73-php-pecl-memcache` package to call for `geerlingguy.php` role
      1.  copy `devops/ansible/build/roles/cms-test/roles/php_setup/tasks/main.yml` to CMS
      1.  copy `devops/ansible/build/roles/cms-test/roles/php_setup/files/memcache.ini` to CMS
   1. Composer
      1. ? Dupal Memcache Module
1. Software Configuration
   1. Dupal Memcache Module
      1.  ?
