### ISSUE TITLE
Vet Center CAPs should support Facility status

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#4933]
## User Story or Problem Statement

As a Vet, i want facility status for CAPs.

As a Vet Center editor, i want to be able to set facility status for CAPs. 

## Acceptance Criteria
- [ ] Fields have been added

![VA_gov_Drupal_Spec_Tool_v2_0_0_-_Google_Sheets](https://user-images.githubusercontent.com/643678/113624807-1763a380-962e-11eb-901b-97c4085f3f12.png)

- [x] Form implementation to follow the patterns from #4808

**Comment by kaise-lafrai** [comment]
#4934 is combined with this ticket
