### ISSUE TITLE
Create Eastern Kansas menu, delete Topeka and Leavenworth.

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#4943]
## Description
In order to have our menu structure reflect the new arrangement in VISN 15 we will need to do the following.

https://dsva.slack.com/archives/CDHBKAL9W/p1617727298116100

## Acceptance Criteria
- [x] Create a new menu `VA Eastern Kansas health care`  with  `VISN 15 | va.gov/eastern-kansas-health-care`
- [x]  Remove `VA Topeka health care` menu in -> #17189
- [x] Remove `VA Leavenworth health care` menu -> #17189

**Comment by mmiddaugh** [comment]
I believe this is complete and can be closed
<img width="688" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOG1NQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--08bd25cd3bc69f48d785643bd6026c47a067af54/image.png" alt="image.png" />

**Comment by swirtSJW** [comment]
This should not have been closed.  The menus were never removed.

**Comment by swirtSJW** [comment]
I am pulling this into my menu reordering work because the empty menus are breaking the re-ordering #16233.

**Comment by swirtSJW** [comment]
/admin/structure/menu/manage/va-eastern-kansas-health-care  was already created way back in april 2021, but the old menus were never removed.
