### ISSUE TITLE
Drupal 9 upgrade - diff static site output between D8 & D9 with same DB

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-cms#4946]
## Description

As a Developer, in order to be confident that the D9 upgrade does not affect the content API or veteran experience, I need to compare the output of the static site build between the current code and a copy of the site upgraded to D9 and ensure there are no differences.

## Acceptance Criteria

- [x] Procedure for comparing output is documented (or ideally scripted) in this repo
- [x] Follow-on issues have been created for identified differences (if any)
- [x] Follow-on issue has been created to re-run comparison after related modifications, if necessary

**Comment by acrollet** [comment]
@indytechcook says that there are scripts in the vets-website repo that can compare the json output.

**Comment by acrollet** [comment]
possibly useful: https://github.com/josephburnett/jd

**Comment by acrollet** [comment]
from vets-website repo, cf. `yarn cms:diff:json`

**Comment by acrollet** [comment]
This effort should be timeboxed, if major differences are seen in the output, please create followups.

**Comment by acrollet** [comment]
@ndouglas please review the ACs and let me know if you think any modifications are useful or necessary.

**Comment by ndouglas** [comment]
I think that's solid.

**Comment by ndouglas** [comment]
I re-synced the DB locally, performed as much of a frontend build as I could, updated to Drupal 9, then performed as much of a frontend build as I could.  

I then took the `pages.json` from D8 (`a.json`) and D9 (`b.json`) and `diff`ed them.  The result was ~1,300,000 differences.  Each file was about 1,800,000 lines long, so this was not my happiest moment.  

<img width="281" alt="Screen Shot 2021-05-14 at 3 14 36 PM" src="https://user-images.githubusercontent.com/1318579/118318245-1cd2ca00-b4c7-11eb-8c43-2f3af04339ab.png">

After playing around with a few different approaches, I found that I could use `jq` to sort entities by their IDs to get an actual entity-level diff, but I'd need to list all of those entity ID paths explicitly.

```bash
jq -S '.data.alerts.entities|=sort_by(.id)' a.json > a2.json
jq -S '.data.alerts.entities|=sort_by(.id)' b.json > b2.json
```

Progress!

<img width="308" alt="Screen Shot 2021-05-14 at 3 17 13 PM" src="https://user-images.githubusercontent.com/1318579/118318503-7b984380-b4c7-11eb-8e28-b857143281e7.png">

But I didn't look forward to doing a bunch more of these.  Nevertheless:

```bash
jq -S '.data.bannerAlerts.entities|=sort_by(.entityId)' a2.json > a3.json
jq -S '.data.bannerAlerts.entities|=sort_by(.entityId)' b2.json > b3.json
```

<img width="315" alt="Screen Shot 2021-05-14 at 3 18 39 PM" src="https://user-images.githubusercontent.com/1318579/118318639-ab474b80-b4c7-11eb-926a-af5f11640203.png">

Eh.

But:

```bash
jq -S '.data.nodeQuery.entities|=sort_by(.entityId)' a3.json > a4.json
jq -S '.data.nodeQuery.entities|=sort_by(.entityId)' b3.json > b4.json
```

<img width="299" alt="Screen Shot 2021-05-14 at 3 19 20 PM" src="https://user-images.githubusercontent.com/1318579/118318723-c4e89300-b4c7-11eb-91ef-26917e00a910.png">

I've uploaded that diff [here](https://gist.github.com/ndouglas/aecef3575f91f47a0a5bba83abcd2fd5).

I went over it with @acrollet and we noticed common denominators. 

- `field_wysiwyg` -> `fieldWysiwyg` -- there are only a few entities using `field_wysiwyg` in current D8 versions of `pages.json`.  They all become `fieldWysiwyg` in D9.  I'm not sure why.  This causes an error in the frontend build:

```
[error]  Error when running "cd /app && COMPOSER_HOME= /usr/local/bin/composer --no-cache va:web:build":<br />
  Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(<br />
> rm -rf docroot/vendor/va-gov/content-build/build/vagovdev<br />
> cd docroot/vendor/va-gov/vets-website && echo "Downloading assets for vets-website for vagovdev" <br />
> cd web && INSTALL_HOOKS=no NODE_ENV=production yarn build --pull-drupal --no-drupal-proxy --buildtype=vagovdev --api=https://dev-api.va.gov<br />
/app/docroot/vendor/va-gov/content-build/src/site/filters/liquid.js:727<br />
            processed: entity?.field_wysiwyg[0]?.processed,<br />
                                            ^<br />
<br />
TypeError: Cannot read property '0' of undefined<br />
    at liquid.filters.processDynamicContent (/app/docroot/vendor/va-gov/content-build/src/site/filters/liquid.js:727:45)<br />
    at exports.Context.callFilter (/app/docroot/vendor/va-gov/content-build/node_modules/tinyliquid/lib/context.js:387:28)<br />
    at /app/docroot/vendor/va-gov/content-build/node_modules/tinyliquid/lib/vm.js:312:15<br />
    at next (/app/docroot/vendor/va-gov/content-build/node_modules/tinyliquid/lib/utils.js:492:9)<br />
    at /app/docroot/vendor/va-gov/content-build/node_modules/tinyliquid/lib/vm.js:95:9<br />
    at /app/docroot/vendor/va-gov/content-build/node_modules/tinyliquid/lib/vm.js:204:9<br />
    at exports.Context.fetchSingleLocals (/app/docroot/vendor/va-gov/content-build/node_modules/tinyliquid/lib/context.js:305:7)<br />
    at getLocals (/app/docroot/vendor/va-gov/content-build/node_modules/tinyliquid/lib/vm.js:192:11)<br />
    at execOpcode.<computed> (/app/docroot/vendor/va-gov/content-build/node_modules/tinyliquid/lib/vm.js:181:3)<br />
    at exports.run (/app/docroot/vendor/va-gov/content-build/node_modules/tinyliquid/lib/vm.js:59:7)<br />
    at /app/docroot/vendor/va-gov/content-build/node_modules/tinyliquid/lib/vm.js:90:5<br />
    at next (/app/docroot/vendor/va-gov/content-build/node_modules/tinyliquid/lib/utils.js:490:9)<br />
    at /app/docroot/vendor/va-gov/content-build/node_modules/tinyliquid/lib/vm.js:95:9<br />
    at /app/docroot/vendor/va-gov/content-build/node_modules/tinyliquid/lib/vm.js:204:9<br />
    at exports.Context.fetchSingleLocals (/app/docroot/vendor/va-gov/content-build/node_modules/tinyliquid/lib/context.js:305:7)<br />
    at getLocals (/app/docroot/vendor/va-gov/content-build/node_modules/tinyliquid/lib/vm.js:192:11)<br />
error Command failed with exit code 1.<br />
Script cd web && INSTALL_HOOKS=no NODE_ENV=production yarn build --pull-drupal --no-drupal-proxy --buildtype=vagovdev --api=https://dev-api.va.gov handling the va:web:build event returned with error code 1<br />
 
```
- `"routed": true` was changed to `"routed": false` in some 30-40 links.
- "length" being removed from attributes of file links like `type=\"application/pdf; length=137205\"`

The differences accumulate quickly with the passage of even quite small amounts of time (a couple of hours).  This comparison really needs to be done from the same initial database.

**Comment by acrollet** [comment]
Awesome work Nate!

**Comment by ndouglas** [comment]
thx, I'm working on adding a README for this information to the repo and then I think we'll be good to close this issue.

**Comment by indytechcook** [comment]
The underscore to camelCase is also talked about here: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/5312

**Comment by ndouglas** [comment]
Good find @indytechcook!

**Comment by acrollet** [comment]
README is [here](https://github.com/department-of-veterans-affairs/va.gov-cms/blob/master/READMES/comparing-graphql-output.md) - looks good, great work on this @ndouglas !
