### ISSUE TITLE
devshop/behat-drupal-extension blocks Drupal 9 Upgrade

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-cms#4950]
## Description
Its dependencies conflict with Drupal 9.  I need to re-attempt upgrading to Drupal 9 with it in place so I can record the details, since I'm ATM just playing whack-a-mole and recording these issues as they arise, and some of the details may be order-dependent, etc.

## Acceptance Criteria
- [ ] `devshop/behat-drupal-extension` no longer blocks D9 upgrade

**Comment by acrollet** [comment]
@ndouglas nice work! can you throw an estimate on this issue?

**Comment by acrollet** [comment]
@ndouglas argh, I was looking on safari, which doesn't show it 🙄  thanks!!
