### ISSUE TITLE
Evaluate drupal/core patches and update, replace, or remove as appropriate. 

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-cms#4951]
## Description
Some of the D8 core patches are not applying cleanly and need to be evaluated, rerolled, or removed as appropriate.

Are they necessary?  Do they still apply? (in at least one case, the answer is "no")  What further actions need to be taken?

## Acceptance Criteria
- [x] `drupal/core` patches applied by Composer no longer block the D9 upgrade

**Comment by jefflbrauer** [comment]
Moved out of the sprint in favor of #5193

**Comment by ndouglas** [comment]
Current Patches and Findings (evaluated against Drupal 9.1.7):

- [2807629](https://www.drupal.org/project/drupal/issues/2807629) – Still open, patch [rerolled](https://www.drupal.org/files/issues/2021-04-13/2807629-34.patch) and [modified](https://www.drupal.org/files/issues/2021-04-19/2807629-35.patch) for Drupal 9. **Applies cleanly.**
- [2894449](https://www.drupal.org/project/drupal/issues/2894449) – Still open, patch not recently rerolled and no other meaningful activity. **Applies cleanly.**
- [3057267](https://www.drupal.org/project/drupal/issues/3057267) – Still open, last comment implies that this patch can be removed entirely and the problematic behavior worked around in custom code. **Latest version applies cleanly, but might be worth removing and implementing in code.**
- [1091852](https://www.drupal.org/project/drupal/issues/1091852) – Still open, recent rerolls, but there are some complicating complaints about patches with lost code so this may take some care. **Applies cleanly.**
- [2859042](https://www.drupal.org/project/drupal/issues/2859042) – Still open, patch still apparently works in its existing form. **Applies cleanly.**
- [2930508](https://www.drupal.org/project/drupal/issues/2930508) – Still open, recent updates but we're still using a 9.1.x-compatible patch according to Adrian's reroll. **Applies cleanly.**
- [2632750](https://www.drupal.org/project/drupal/issues/2632750) – Still open, still at specified patch. **Applies cleanly.**
- [2911932](https://www.drupal.org/project/drupal/issues/2911932) – Still open, no recent rerolls – might apply cleanly.  Patch by Ethan. **Applies cleanly.**
- [3188331](https://www.drupal.org/project/drupal/issues/3188331) – Still open, no recent rerolls – might apply cleanly.  Patch by Ethan.  **Does not apply cleanly.**
- [2893933](https://www.drupal.org/project/drupal/issues/2893933) – Still open, [rerolled](https://www.drupal.org/files/issues/2021-01-14/2893933-40.patch) for Drupal 9.1.x. **Applies cleanly.**
- [3198608](https://www.drupal.org/project/drupal/issues/3198608) – Still open, patch hasn't been rerolled. **Applies cleanly.**
- [3176975](https://www.drupal.org/project/drupal/issues/3176975) – Appears to actually be a non-issue for D9 🎉  **Should be removed.**
- [3205691](https://www.drupal.org/project/drupal/issues/3205691) – Still open, no recent rerolls – might apply cleanly.  Patch by... Ethan. **Applies cleanly.**

So I think I'll inspect the patch for [3188331](https://www.drupal.org/project/drupal/issues/3188331) and see if it just needs to be rerolled or if it needs more dramatic action; otherwise, these look straightforward to update.

**Comment by ndouglas** [comment]
Current content of this section:
```json
                "2807629 - Allow menu items which link to unpublished nodes to be selected in the parent item selector": "https://www.drupal.org/files/issues/2021-04-19/2807629-35.patch",
                "2894449 - Indirect modification of overloaded element with Views responsive table": "https://www.drupal.org/files/issues/2018-10-05/core-indirect-modification-of-overloaded-element-2894449-18.patch",
                "3057267 - User logout during maintenance mode": "https://www.drupal.org/files/issues/2019-09-11/3057267-maintenance-forced-logout-experimental.patch",
                "1091852 - Display Bug when using #states (Forms API) with Ajax Request": "https://www.drupal.org/files/issues/2021-02-19/1091852-128.patch",
                "2859042 - Entity original revision": "https://www.drupal.org/files/issues/2018-07-30/entity_original_revision-2859042-26.patch",
                "2930508 - Seven inactive tabs do not meet WCAG AA 1.4.3 for contrast": "https://www.drupal.org/files/issues/2020-10-15/drupal-seven_inactive_tabs_do_not_meet_wcag_aa-2930508-36.patch",
                "2632750 - Interface previews/skeleton screens through optional preview or placeholder templates": "https://www.drupal.org/files/issues/2020-11-18/2632750-76-do-not-test_0.patch",
                "2911932 - Correct vertical tab does not focus on form validation": "https://www.drupal.org/files/issues/2020-12-12/vertical-tabs--focus-on-onvalid-7b.patch",
                "2893933 - claimItem in the database and memory queues does not use expire correctly": "https://www.drupal.org/files/issues/2021-01-14/2893933-40.patch",
                "3198608 - Migrate does not set set track_lst_updated from config": "https://www.drupal.org/files/issues/2021-02-15/3198608-track-last-updated-6.patch",
                "3205691 - Disallow aria-required on fieldsets": "https://www.drupal.org/files/issues/2021-03-25/disallow-aria-required-fieldsets.patch"
```

**Comment by acrollet** [comment]
D9 is no longer blocked, closing this out. Nice work @ndouglas !
