### ISSUE TITLE
CLP MVP request form

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#4953]
## User Story or Problem Statement

As a campaign team member, i want to request a campaign landing page from the Public Websites team so that i can create my campaign

As a PW content admin, i want to receive a CLP request via email so that i can respond to it. 

## Acceptance Criteria

- [ ] Form has been created in Drupal

### Settings 

URL: `prod.cms.va.gov/request-a-clp`
Access: Anyone on VA network (no CMS account required)

### Intro text: 

```

<h1>Request a Campaign Landing Page</h1>

[insert a screenshot of sample CLP]

A Campaign Landing Page is a single-page template designed to support major benefit-related program and engagement campaigns and awareness.

You can request access to the campaign landing page builder in the VA.gov CMS using this form, and a member of [the _Sitewide product team_] will get back to you [_in 3 to 5 business days_]. 

Questions? Please contact [_the CMS Product Support team at < >_].
```

### Fields on form

----

#### Fieldgroup: "Contact info"

**Your name**
Plain textfield, 60 characters

**Your _VA_ organization**
Plain textfield, 60 characters
Help text: "Eg: VHA Digital Comms"

**Your email address**
Email address field, pre-populate if the user is logged in to CMS.
Help text and/or form validation: "Must be a va.gov email address."

----

#### Fieldgroup: "Campaign info"

**Name _or focus_ of Campaign**
Plain textfield, 60 characters

**Who is the intended audience (or audiences)?**
Plain textfield, 60 characters
Help text: "Eg. "Veterans and caregivers"."  

**What are the goals of the Campaign?**
Long plain text field, 3 lines.
_Help_ text: "Eg. "To provide Veterans and their caretakers with important program information about the MISSION Act"."  

**Campaign timeline**
Plain textfield, 60 characters
Help text: "Approximate dates for the campaign start and end."  

_**Campaign page target launch date**
Plain textfield, 60 characters
Help text: "What is the ideal go live date of page."_  

**Requested URL**
Plain textfield, 60 characters
Help text: "Eg. "www.va.gov/mission-act"."  

**What will you to drive awareness of this campaign and this page?**
Plain textfield, 60 characters
Help text: "Social media, email, etc." 

_**What metrics will you want to know to measure success of the campaign landing page**
Plain textfield, 60 characters
Help text: "Page views, click-throughs, referral sources"_

----

#### Fieldgroup: "Editorial workflow"

_**How familiar are you -- or the team member who will be building the campaign page -- with the VA.gov Drupal content management system**
Plain textfield, 60 characters
Help text: "Page views, click-throughs, referral sources"_

**Who will be building the Campaign landing page?**
Plain long textfield, 3 lines
Help text: "Include name and email address for each person"  

**Who will be reviewing content before it is published?**
Plain long textfield, 3 lines
Help text: "Include name and email address for each person"  

_**Who will be updating/maintaining the content during the campaign?**_
Plain long textfield, 3 lines
Help text: "Include name and email address for each person"  

**What is the expected lifespan for this page?**
Plain textfield, 60 characters
Help text: "Will this be updated regularly? Reused seasonally? Archived on a certain date?"

----

### Form submission settings

Form submission button: "Submit"

Form confirmation page: 

```
<h1>Request received!</h1>

Thank you for submitting a request for a VA.gov Campaign landing page. 

A member of the [Sitewide Product team] will get back to you [in 3 to 5 business days?].

We have emailed you a copy of your request to [sitewide-team@va.gov?]
```

### Email settings

Email form content to 

1. Email address provided on the form
2. [other email address TBD]

## Implementation steps

-[ ] Build webform

**Comment by johnhashva** [comment]
Here is what the Request form looks like in Word format.
[VA.gov_Campaign_Landing_Page_Info_Form.docx](https://github.com/department-of-veterans-affairs/va.gov-cms/files/6318317/VA.gov_Campaign_Landing_Page_Info_Form.docx)

**Comment by johnhashva** [comment]
@kevwalsh and @brianalloyd dropping here an updated version of the Info_Form with additional questions about metadata/keywords and Contact Center support.   This is a complete list -- to this date -- of all the questions we would want to ask on the request form.

[VA.gov_Campaign_Landing_Page_Info_Form.docx](https://github.com/department-of-veterans-affairs/va.gov-cms/files/6360234/VA.gov_Campaign_Landing_Page_Info_Form.docx)

**Comment by wesrowe** [comment]
We instead created a github template for starting up new CLPs with the help of the CMS Help Desk. Closing.
