### ISSUE TITLE
Investigate duplicated site rebuild requests in logs

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-cms#4956]
## Description
While looking into a content deploy request, I noticed that the logs held a number of identical messages concerning the same (supposedly) content deploy request originating from prod:

<img width="1210" alt="Screen Shot 2021-04-07 at 10 24 59 AM" src="https://user-images.githubusercontent.com/1318579/113884198-c918e680-978c-11eb-891f-a740f515d4be.png">

The timing of the entries leads me to suspect that this probably happened invisibly to the user.

This log message is recorded _after_ dispatching a request to Jenkins, so it would seem that Jenkins has debounced these requests.

## Acceptance Criteria
- [ ] Root cause for this behavior has been found
- [ ] Determination has been made whether this poses a threat to the reliability or experience of deploying content
- [ ] Behavior has been altered to fix this or a followup issue for dealing with it has been opened.

**Comment by ndouglas** [comment]
<img width="681" alt="Screen Shot 2021-04-07 at 10 56 06 AM" src="https://user-images.githubusercontent.com/1318579/113887875-dd121780-978f-11eb-9694-69eebd2a7699.png">

**Comment by TheBoatyMcBoatFace** [comment]
This is taken care of by Content Release and is no longer valid.
