### ISSUE TITLE
Discover & document user/content scalability requirements

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-cms#4958]
## Description

In order to select an appropriate content publishing solution, we need to know the expected number of businesses / users / content onboarding to CMS in 2021/22 and projected maximum amount of content over the next 5 years.

## Acceptance Criteria
- [ ] Expected number of business units & users onboarding through 2021 - 2022 is documented on this issue 
- [ ] Projected maximum amount of content over the next 5 years is documented on this issue

**Comment by jefflbrauer** [comment]
Per @davidconlon we should expect a ballpark range of 400,000-500,000 nodes in 5 years if we include tier 3 content. This is very rough estimate based on the number of pages we're aware of today. Likely it will be less.
