### ISSUE TITLE
[SPIKE] Speed up existing tests

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-cms#4963]
## Description

In order to improve developer cycle time, PR tests should run in as little time as possible. The CMS team will assess viable options for reducing overall test time and determine next steps for implementing a solution.

## Acceptance Criteria

- [x] The team has met to discuss short-term opportunities for test parallelization, building on the work done in #4880 
- [x] A decision criteria document is created to compare and weigh approaches
- [x] Follow-on issues for selected option(s) are created

Brainstorming doc: https://docs.google.com/spreadsheets/d/1PenLdmYeVWxwcOFO60TeG8-_H8QeNegRf64-Nj2odKs/edit#gid=0

**Comment by ndouglas** [comment]
One _possibly_ simple approach on this would be a three-way parallelization:
- [ ] split the content build off into a separate task
- [ ] retain Behat tests including a content build and spec-tool tests into a separate task
- [ ] shift other Behat tests to Cypress and perform all behavioral tests (incl. PHPUnit) in that task

The content build is the longest individual task.  We perform two of them, so there's not much benefit to be gained from parallelizing _past_ that, but a substantial benefit to be gained from parallelizing those.  The remaining tests should all take about as much time as the content build.

**Comment by ElijahLynn** [comment]
Notes from refinement:

* Northstar - All tests complete in as long as it takes the longest test to run
* Elijah has a Lucid Chart possible architecture that he worked on with Neil, Elijah will post that here
* Nate has ideas on reducing the content-build time by parallelizing that piece, for a lower effort, large value win
* We switched from yaml-tasks to task because `task` supports parallelization
* Possibly pre-load Tugboat base preview clones (using Tugboat API) so each test in a PR can have it's own DB (local memcache, mysql, fast). Could use the Docker Swarm feature to create PR test nodes etc. Tugboat is designed around  Swarm so this could be really fast and robust.

**Comment by olivereri** [comment]
@ElijahLynn Have you found that Lucid Chart with testing architecture?

**Comment by ElijahLynn** [comment]
> @ElijahLynn Have you found that Lucid Chart with testing architecture?

It is missing context but here it is: https://lucid.app/lucidchart/ccb732b0-a9dc-4e34-998d-f6d3bd3eb5cf/edit?invitationId=inv_bb56a53b-525b-42ff-b844-9326da3dc4f9&page=0_0#

![v3 - VA gov - CMS Infrastructure Architecture - Phase 1](https://user-images.githubusercontent.com/1504756/159369577-67a5d69b-a711-4fef-814f-eb1dceec577e.png)
![v3 - VA gov - CMS Infrastructure Architecture - End Game](https://user-images.githubusercontent.com/1504756/159369572-665f8c82-df8b-48d6-be3c-d1361d60c6c1.png)

**Comment by ElijahLynn** [comment]
Martin Fowler suggests a 10 minute goal as recommended by the XP community. 

https://martinfowler.com/articles/continuousIntegration.html (search 'ten minute').

**Comment by olivereri** [comment]
## Current State of Tests
![image.png](https://images.zenhubusercontent.com/5f04cf8f49978b1615fee8c2/5f270283-73b7-4755-9f31-c4e38b13132c)
Tests took 60 minutes, now down to ~40 minutes.
### Steve Swirt PR Merge to Remove Extra Content-Build.
https://github.com/department-of-veterans-affairs/va.gov-cms/pull/8431

**Comment by olivereri** [comment]
Test improvement brainstorm:
https://docs.google.com/spreadsheets/d/1PenLdmYeVWxwcOFO60TeG8-_H8QeNegRf64-Nj2odKs/edit#gid=0
