### ISSUE TITLE
Make Vet Center field_office_hours dependent on the Hours opt-in boolean TRUE

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#4972]
## User Story or Problem Statement

This is a follow up to #4970 

As a Vet Center editor, i only want to provide hours for CAPs in certain situations. 

![Create_Vet_Center_Community_Access_Point___VA_gov_CMS](https://user-images.githubusercontent.com/643678/114054647-0ac59200-985e-11eb-8f63-02b2d03a37d1.png)

## Acceptance Criteria
- [ ] `field_office_hours` is hidden unless `field_vetcenter_cap_hours_opt_in` is TRUE

## Implementation steps
- [ ] Form state

**Comment by kaise-lafrai** [comment]
Question here: @kevwalsh 

- How do we handle already entered hours fields? Does the data continue to live in the fields even after it is hidden via the new radio buttons?

If YES, then ->
- If the data continues to live in the fields and the radio button that hides the form field is selected, do we want to hide the hours field display on the proofing page?

**Comment by kevwalsh** [comment]
@kaise-lafrai good question. I don't know if there is any data yet for this. there are only 3 CAPs so far.  Can you check to see if there is data? if there is (i _believe_ it's sample (throw-away), and we can work with @mmiddaugh.

**Comment by kaise-lafrai** [comment]
@kevwalsh Thanks! I guess I am trying to cover the case that someone does enter data in the hours, then switches it back to "hidden". I wanna know what we should do with the hours field (data) and (proofing) at that point.

**Comment by kevwalsh** [comment]
@kaise-lafrai ah, great question. My hunch is that the `field_office_hours` should all be NULL. I guess that would mean additional validation. OR, forcing them to be null on save. @swirtSJW may have an idea about this.
