### ISSUE TITLE
Reduce duplicate Vet Center facilities on a Locations list page

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#4983]
## User Story or Problem Statement

In the CMS, It's currently possible for a local Vet Center editor to add a Vet Center facility that is already listed on their Locations page, as a Nearby Vet Center. 

How might we prevent that? 

UX improvements 
- list existing Vet Centers in the Locations List content type form.

Governance improvements: 
- prevent adding duplicate facilities. 

## Acceptance Criteria
- [ ] TBD

## Implementation steps
TBD

**Comment by davidmpickett** [comment]
![Screenshot 2024-07-01 at 5 09 10 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/e927aa42-f24d-42a2-a9ec-425a3a92d9ea)

This is no longer needed as the NearbyVet Center functionality has been removed from editor UI
