### ISSUE TITLE
Implement VAMC menu governance

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#4988]
## User Story or Problem Statement

The spike in #4311 established a viable approach to the user stories below. In this issue we'll finish implementing them. 

**As a product owner** (content_admin or administrator only)

- [x] i can designate which parent items in VAMC system menus are eligible to have children menu items created by non-Content admins,
- [x] i can designate which paths should have "locked" menu items, meaning that non-content-admins would not be able to edit those menu items, across all VAMCs (such as pittsburgh-health-care/pharmacy AND erie-health-care/pharmacy, and all [health-care-system]/pharmacy)
- [x] i can additionally designate individual URLs at certain VAMCs that should be locked (such as pittsburgh-health-care/dav-vans BUT NOT erie-health-care/dav-vans).

As **a content_editor**, content_reviewer, or content_publisher with workbench access to a VAMC menu (eg Lebanon Health Care menu) :

- [x] i shouldn't be able to administer the menu itself (eg go to admin/structure/menu/manage/va-lebanon and drag and drop)
- [ ] i shouldn't be able to add or edit menu items for content types other than Detail Pages
- [ ] i should be able to place individual menu items of Detail Page content type, using the Menu settings in the right rail, but only with certain parents eligible.

Updated since #4311
- in the UI parent item selector, when creating a `health_care_region_detail_page`, i should be able to see:
  - ~the whole menu, with some items disabled~ (decision April 7 to not show the whole menu)
- [ ]  any menu item that is eligible to have children (and its children, which should also be eligible to have children)
- [ ]  the ancestors of any menu item that is eligible to have children (_except the top level_, which is always the Health Care System, and is redundant)

## Acceptance Criteria

**Eligible parent items for detail pages**

```
*-health-care/work-with-us/internships-and-fellowships
*-health-care/work-with-us/doing-business-with-us
*-health-care/work-with-us/jobs-and-careers
*-health-care/work-with-us/volunteer-or-donate
*-health-care/programs
*-health-care/research 
```

The menu should therefore look like this to a content editor (without the "(disabled)" or "(if it exists)" annotation)

```
About VA Pittsburgh (disabled)
- Work With Us (disabled)
  - Internships and fellowships
  - Jobs and careers
  - Doing business with us
  - Volunteer or donate 
- Programs 
- Research
```

**Detail pages with locked menu items**
```
*-health-care/*
```

instead of
```
*-health-care/health-services/*
*-health-care/location*
*-health-care/abou*
*-health-care/work-with-u*
*-health-care/program*
*-health-care/researc*
*-health-care/contact-us 
*-health-care/make-an-appointment
*-health-care/register-for-care
*-health-care/billing-insurance
*-health-care/medical-records-office
*-health-care/pharmacy
*-health-care/dav-vans-transportation-for-veterans
*-health-care/policies
```

**Comment by mnorthuis** [comment]
Adding myself so I can stay up to date on this work.

**Comment by ethanteague** [comment]
Applied, here: https://github.com/department-of-veterans-affairs/va.gov-cms/pull/4894

**Comment by swirtSJW** [comment]
Most of the functional code for this has been merged with https://github.com/department-of-veterans-affairs/va.gov-cms/pull/4894   However the activation of it has been short circuted until other issues in the epic have been addressed.  THen the logic can be further refined.

**Comment by cmaeng** [comment]
VAMC migrations have distracted from completing this within the projected timeframe. With @swirtSJW out of office for the next two weeks, we recommend pushing this to sprint 36.
