### ISSUE TITLE
Clarify "promo" language 

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#4990]
## User Story or Problem Statement

CLP usability research showed some confusion about use of the word promo to describe elements within this segment. Also help text seemed to add to confusion more than help it.

![Create_Campaign_Landing_Page___VA_gov_CMS](https://user-images.githubusercontent.com/643678/114133708-734f5600-98d4-11eb-97be-facb135ecb4f.png)

## Acceptance Criteria
- [ ] TBD

## Implementation steps
<optional>

**Comment by wesrowe** [comment]
@EWashb, do you have any idea where we could find the CLP user research alluded to in the body of this ticket?

cc @thejordanwood @BlakeOrgan @jilladams

**Comment by EWashb** [comment]
Hmm this one is interesting @wesrowe. I don't remember CLP-specific research. however, I know that @joagnitti synthesized all of the past CMS research as a part of her early work when she onboarded. Jo- do you know of/remember seeing anything regarding this?

**Comment by wesrowe** [comment]
Ooh, I just found a link in one of the tickets. [Here's the synthesis](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/research/campaign-landing-page/beta-test-synthesis.md). It was performed before the CLP MVP was released, but nothing about the research methodology was documented in this file. I'll look for a ticket in the repo.

**Comment by wesrowe** [comment]
Per my [issue search](https://github.com/department-of-veterans-affairs/va.gov-cms/issues?q=is%3Aissue+is%3Aclosed+beta+test+clp), @xiongjaneg was present for or may have actually conducted the CLP beta test sessions. 

Notes from 2 beta sessions are in [comments from Jane](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/4317#issuecomment-790722980).

Mystery solved, I guess!

**Comment by EWashb** [comment]
Oh good deal. Thanks for tagging this.

As an aside for @joagnitti, if we don't have the CLP info in our CMS Research Database, can you please make a ticket to include the above items that Wes tagged?

**Comment by FranECross** [comment]
closing old ticket
