### ISSUE TITLE
Make it easier to navigate the long CLP form

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#4992]
## User Story or Problem Statement

[Usability testing ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/research/campaign-landing-page/beta-test-synthesis.md) found that one user found the form long and hard to navigate. 

> Internal navigation - The form is very long, so would be nice to have a way to go from segment to segment without having to scroll/also to help with wayfinding within the form. Also the nesting of forms within forms was confusing (ex. Downloadable Resources segment).

How might we make it easier to navigate such a long form?

- ToC in addition to the fieldgroups?
- Ability to collapse all the fieldgroups?
- Jump back to top links? 
- etc. 

## Acceptance Criteria
- [ ] TBD based on design

## Implementation steps
<optional>

**Comment by FranECross** [comment]
Closing ancient ticket; a new one will be created if needed when this arises again.
