### ISSUE TITLE
Form hypothesis of relevant user segments

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-cms#4996]
## User story
As a CMS Editor, I would like to publish content to VA.gov as quickly and easily as possible so that I can most effectively deliver content to Veterans and the public.

## Business goal
Identify CMS editor objectives and pain points when publishing content in order to understand the implications of a technical solution for AP.

## Research objectives
- Form hypothesis of relevant user segments in collaboration with team members & VA stakeholders as possible (Kev Walsh, Dave Conlon, Jen Lee, Stan Gardner, Public Websites, other stakeholders & "Power Users")

## ACs
- [x] Hypothesized user segments are documented and socialized to project stakeholders
- [x] Points of contact for each user segment have been identified

**Comment by jefflbrauer** [comment]
Per @rachel-kauff 's slack post:

**Research Plan is here:**  https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/research/accelerated-publishing.md

**Recruitment Sheet is attached** [https://app.zenhub.com/files/154174777/25790914-a8f3-48f0-bbba-3130ba659433/download](https://app.zenhub.com/files/154174777/25790914-a8f3-48f0-bbba-3130ba659433/download)
