### ISSUE TITLE
Update content build trigger to work with new content release process

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-cms#5005]
## Description

When the content build separation project is launched, the Drupal-based content build trigger code may need to be updated to point at a different endpoint/process.

## Assumptions
- current process is well understood and documented
- new endpoint/trigger process matches current process and is provided to the CMS team in advance of this work

## Acceptance Criteria
- [x] Communicate with @timwright12 to obtain information about new process and/or endpoint
- [x] Content release page and automatic content releases continue to function after content build separation launch
- [x] Provide packagist token to @timwright12

**Comment by acrollet** [comment]
dupe of #4608

**Comment by acrollet** [comment]
WiP content build release: http://jenkins.vfs.va.gov/blue/organizations/jenkins/releases%2Fcontent-build/activity

**Comment by acrollet** [comment]
@timwright12 is lead dev on the content build separation project, more information can be found in the #content-build-separation slack channel.

**Comment by indytechcook** [comment]
> WiP content build release: http://jenkins.vfs.va.gov/blue/organizations/jenkins/releases%2Fcontent-build/activity

Note, this is not the build job we will be calling.

**Comment by ElijahLynn** [comment]
I sent the token to Tim yesterday, and that AC is done!

**Comment by indytechcook** [comment]
Conversation with Tim regarding new job:

```
Neil Hastings Today at 4:37 PM
:thread: @Tim Wright a few confirmations regarding calling the job from the jenkins api
13 replies
Neil Hastings  4 minutes ago
http://jenkins.vetsgov-internal/job/deploys/job/vets-gov-autodeploy-content-build is the job to call
Neil Hastings  3 minutes ago
do we need to send use_latest_release explicitly as false?
Tim Wright:spiral_calendar_pad:  3 minutes ago
is the current one you’re calling http://jenkins.vetsgov-internal/job/deploys/job/vets-gov-autodeploy-vets-website ?
Tim Wright:spiral_calendar_pad:  3 minutes ago
the use_latest_release setting should be the same as whatever it is currently, we didn’t make any changes
Tim Wright:spiral_calendar_pad:  2 minutes ago
you can feel free to test it, it won’t harm anything
Neil Hastings  2 minutes ago
yes to vets-gov-autodeploy-vets-website
Tim Wright:spiral_calendar_pad:  2 minutes ago
^ then yes to vets-gov-autodeploy-content-build
Neil Hastings  1 minute ago
we all /job/deploys/job/vets-gov-autodeploy-vets-website/buildWithParameters?release_wait=0&use_latest_release=true
Tim Wright:spiral_calendar_pad:  1 minute ago
use_latest_release=true will be a content-only deploy
Neil Hastings  < 1 minute ago
so we just need to change that to vets-gov-autodeploy-content-build and then sunshine will rain down?
Tim Wright:spiral_calendar_pad:  < 1 minute ago
it should, yeah. We tried our best to keep everything the same
```

**Comment by indytechcook** [comment]
PR is ready but merge needs to be coordinated with FE Tools

**Comment by indytechcook** [comment]
Moved work to the PR: https://github.com/department-of-veterans-affairs/va.gov-cms/pull/5199

**Comment by indytechcook** [comment]
Tested on Tugboat:

![image](https://user-images.githubusercontent.com/121603/116892585-f62aae80-abfd-11eb-809f-b404ec486926.png)


![image](https://user-images.githubusercontent.com/121603/116892514-e57a3880-abfd-11eb-8003-fff7715b1a34.png)

**Comment by indytechcook** [comment]
Screenshots from dev/staging:

![image.png](https://images.zenhubusercontent.com/543e76bb7c6ccc6277a54276/bff30819-1a76-4f4d-b144-3782be08289a)

![image.png](https://images.zenhubusercontent.com/543e76bb7c6ccc6277a54276/2d0f6527-7ae5-4744-8662-e48ad3ca65ef)
