### ISSUE TITLE
Split out R&S content into multiple sections under VBA, NCA, VHA, and Public Websites

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#5021]
## Proposed change

**What change to the Sections hierarchy do you want?** 

Move a branch of RS to VBA section hierarchy, so VBA, VHA, and NCA business line stakeholders can create and publish non-Veteran-facing RS articles. 

Example: Tammy Hurley in Education may wish to publish RS articles for school certifying officials and college administrators. Or Lori Hamilton in Life Insurance may wish to update and publish RS rates articles for claim processors. 

**What types of content are associated with this Section?**

Various Resources and Support content types. 

**Include a screenshot or diagram of this proposed change**

Current R&S section hierarchy:  

```
None. All content is currently assigned to "Public Websites". 
```

New R&S section hierarchy

```
VBA
- Resources and support
VHA
- Resources and support
NCA
- Resources and support
DEPO 
- Public Websites
  - Resources and support
```

## Impact on existing users 

**Will anyone _lose_ access to editing content?**

No one will lose access. 

**Will any users _gain_ access?**

Existing CMS users at VBA, NCA and VHA will be able to create content in a Resources and support section in their respective sections. 

## Acceptance Criteria
- [x] New "Resources and support" sections are added under each of the three main Administrations (NCA, VHA, VBA)
- [x] New "Resources and support" section is added under Public Websites
- [ ] All existing Resources and support content is moved to the latter
- [x] No existing RS content is moved to the sections under NCA/VHA/VBA

**Comment by kevwalsh** [comment]
AC #3 is blocked by #4692

**Comment by kevwalsh** [comment]
The relevant part of your request is complete, but i want to move existing RS content out of "Public Websites" into the new child "Resources and support" child, once we address an existing defect with our bulk edit tool (#4692). So i'm keeping this open for that.

**Comment by jenniferlee-dsva** [comment]
This appears closed again. Does that mean all RS content is now moved into the PW > RS child? @kevwalsh
