### ISSUE TITLE
Theming updates to Vet Center dashboard 

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#5031]
## User Story or Problem Statement

This is templating/css work breaking out from #4850 

![Vet_Centers_–_Figma](https://user-images.githubusercontent.com/643678/114649974-702ae000-9caf-11eb-92f3-64206cee3ef9.png)

## Acceptance Criteria
- [ ] Implementing as many design review items from April 13 design review as reasonable. (see [annotated mockup](https://www.figma.com/file/885DMraAi9V2DLJnrIN7Wv/Vet-Centers?node-id=0%3A1) here, or screenshot above)
- [ ] Submit PR to feature branch ethanteague:VACMS-4850-vet-center-dashboard on #4994

## Implementation steps
CSS, template updates.

**Comment by kaise-lafrai** [comment]
@rachel-kauff Should all blocks that have a single link be right justified? 

![Screen Shot 2021-04-15 at 9.57.11 AM.png](https://images.zenhubusercontent.com/5f04cf76eb6c0026ebd18020/825a7a65-2445-4242-81ac-1e8b23d43405)

**Comment by kaise-lafrai** [comment]
@rachel-kauff Here is what the term name looks like wrapped in an H2. Does this satisfy the requirement?

![image.png](https://images.zenhubusercontent.com/5f04cf76eb6c0026ebd18020/46d9541a-9622-47eb-a64d-c16b46d3bbc3)

**Comment by kaise-lafrai** [comment]
@rachel-kauff 
> Card background color
> 
> Either match design or match the lighter hue of Drupal Toupe used in the table heading background  (#F1F1EB) 

The table headers are set to #f5f5f2, will this meet requirements for the card background color?

**Comment by rachel-kauff** [comment]
@kaise-lafrai 
1. Card links: Yes, they should all be right justified (except in the last two cards, where there's two links. Those are good as they are right now.).
2. H2 - That seems right, except the text shouldn't be linked.
3. Ah, yes, I must have sampled the wrong pixel when I made that recc. Thanks for the correction. Let's use #f5f5f2

**Comment by kaise-lafrai** [comment]
@rachel-kauff Thank you. I want to confirm that the name "Escanaba Vet Center" should not be linked?

**Comment by kaise-lafrai** [comment]
@rachel-kauff Should we "un-link" the term name on all taxonomy terms?

**Comment by kevwalsh** [comment]
> @rachel-kauff Should we "un-link" the term name on all taxonomy terms?

I would think yes, because axonomy term pages should not be linking to themselves. FWIW, no other taxonomy term pages don't have a link, because they don't show this h2, eg https://prod.cms.va.gov/section/veterans-health-administration

**Comment by kaise-lafrai** [comment]
@kevwalsh This is what it would look like based on the existing dashboard work: https://pr4994-ktrcnvwibjve1xd1v2cabeky6va0snm5.ci.cms.va.gov/section/veterans-health-administration any thoughts on what it SHOULD look like?

**Comment by kevwalsh** [comment]
![Veterans_Health_Administration___VA_gov_CMS.png](https://images.zenhubusercontent.com/5d6e57ad330f64311395f08b/44033b2e-9507-4388-8706-eb560a67b668)

I see.  That's a regression. this h2, unlinked, should only be showing up the Vet Center dashboard managed by Layout Builder, not on every taxonomy/term/TID page.

**Comment by rachel-kauff** [comment]
@kaise-lafrai Sorry for the delayed response (meetingful day here).  A ++ to what Kev said - we should unlink the H2 text / taxonomy term, but only on VC pages.

**Comment by kaise-lafrai** [comment]
@kevwalsh @rachel-kauff Hi team - Do we have a placeholder image picked out for the vc facilities with no image?

**Comment by kaise-lafrai** [comment]
@kevwalsh @rachel-kauff Here is a screenshot of the dashboard at it's latest state with the work I have done. Please take a look and let me know how this looks. The only part that I think i might have misinterpreted is the following card in figma: 

> 
> > Cards  
> Card size on wide screens is currenlty awkward. 
> 
> Mobile breakpoint: [whatever it’s currently at]
> Max column width: 900 px
> Card width: 284 px ea.
> Center card group
> 
> I think we should keep the card width static at 284, and use the margin allow the space around the cards to expand. Same goes for mobile breakpoint: Keep cards at 284, but scale the space around them.

![image.png](https://images.zenhubusercontent.com/5f04cf76eb6c0026ebd18020/b44a6c56-0ff8-4155-a429-dc427288763b)

**Comment by rachel-kauff** [comment]
@kaise-lafrai It's not you! I'm still learning how to communicate design specs (also what columns even mean). At some point Jacqueline will be back, and she's a real visual designer who we can lean on for this kind of guidance. In the meantime, let's see if I can describe it better:

I reckon we should also keep the distance between cards static. The only thing that should scale up is the space around them. Like this:
![Screen Shot 2021-04-20 at 2.50.11 PM.png](https://images.zenhubusercontent.com/5e399cf5446c5b4ca0e31e42/f4de9bd5-21af-4e91-86fb-63e3c259773e)

Also:
**Placeholder image:** https://prod.cms.va.gov/media/image/2859
I'll double check the ratio on the file, and make a new asset if we need to.

**Comment by rachel-kauff** [comment]
Update: re: placeholder image. It looks like the facilities placeholder file I linked above is pretty close in ratio to the facilities thumbnails currently in there, but I reckon it should match, so here's the same file, but cropped to exactly 4:3. ![Placeholder - facility_4-3ratio.jpg](https://images.zenhubusercontent.com/5e399cf5446c5b4ca0e31e42/55335a42-5be0-47b3-b6fc-e61561c24718)

**Comment by kevwalsh** [comment]
This is subsumed by #4994
