### ISSUE TITLE
Upgrade Tugboat to latest release

### ISSUE THREAD

**Issue by ElijahLynn** [department-of-veterans-affairs/va.gov-cms#5084]
We have a race condition on PRs where if a new commit is pushed too soon after a recent one has started building then Tugboat won't recognize it and the deployment will be a commit behind and tests will also run on a commit behind and a PR can then be merged with tests passing but not on the recent commit, which can allow regressions to be merged. 

## Acceptance Criteria

- [x] Tugboat has been updated to `v2.21.9`
- [x] All current patches have been re-applied
- [ ] No regressions in performance or functionality are identified
- [ ] Confirm that container IDs and instance URLs have not changed
   - [ ] If they do change, ensure that `content-build` is updated to point at the new URL (https://github.com/department-of-veterans-affairs/content-build/blob/master/jenkins/common.groovy)
- [x] Add documentation on how to perform manual tugboat upgrades (because we are paused on new BRD deploys due to migration to K8S)

## Runbook
- [x] Run backup job
- [x] Pre-Smoketest
  - [x] Grab 3 preview environment tokens and also make sure they load for comparison after upgrade
- [x] Announce in `#cms-support` and `#vfs-platform-support` (copy links and repost)
- [x] Upgrade
  - [ ] `git stash`
  - [ ] `git fetch --tags`
  - [ ] `git checkout v2.21.9`
- [x] Re-apply patches
  - [x] ulimit patch to docker (https://github.com/department-of-veterans-affairs/va.gov-cms/issues/4974#issuecomment-815942263) (not needed, not in git)
  - [x] proxy-timeout.patch (gql 5+ minute requests)  (not needed anymore) https://dsva.slack.com/archives/C01A35JDH88/p1621544007004300
- [x] Apply new patch for race condition (https://github.com/department-of-veterans-affairs/va.gov-cms/issues/5084#issuecomment-824799432)
  - [ ] Create `tugboat-race-condition.patch` on server 
  - [ ] `patch -p1 < tugboat-race-condition.patch`
- [ ] Upgrade Tugboat and Reload
  - [x] `make`
  - [x] `tbctl reload`
- [x] Smoketest
  - [x] Verify 3 previews load correctly 
  - [ ] Verify preview tokens haven't changed
  - [x] Check logs
- [ ] ROLLBACK PLAN
  - [ ] See READMES/devops/tugboat-on-premise-installation.md

**Comment by ElijahLynn** [comment]
Patch here > https://dsva.slack.com/archives/C01A35JDH88/p1619007075037900

**Comment by q0rban** [comment]
Here's the patch: 

```patch
diff --git a/lib/server/lib/actions/jobs/create.js b/lib/server/lib/actions/jobs/create.js
index 38a0587c5..34fc4122b 100644
--- a/lib/server/lib/actions/jobs/create.js
+++ b/lib/server/lib/actions/jobs/create.js
@@ -39,6 +39,10 @@ module.exports = async function ({
     }
 
     if (lock) {
+        // If the job is forced, release any extant lock on this object.
+        if (args.force) {
+            await tugboat.locks.findOneAndRemove({ name: objectId }).catch(() => null);
+        }
         // Attempt to acquire a lock on the object. Wait for up to 3 seconds before
         // throwing an error. It would be great if we could have multiple jobs
         // queued up for an object, but that would require a bunch of job management
diff --git a/lib/webhooks/lib/client.js b/lib/webhooks/lib/client.js
index 694a4d072..fa4e84376 100644
--- a/lib/webhooks/lib/client.js
+++ b/lib/webhooks/lib/client.js
@@ -76,7 +76,7 @@ class TugboatClient {
                         target: 'previews',
                         action: 'rebuild',
                         object: preview.id,
-                        args: { preview: preview.id },
+                        args: { preview: preview.id, force: true },
                     });
 
                     // Run the rebuild job

```

**Comment by acrollet** [comment]
From @ElijahLynn Thu evening May 20: 

> Tugboat upgrade complete: Total downtime was under 2 minutes (6:32:20 to 6:33:51 pm ET)
