### ISSUE TITLE
Tasks are not echoing their output to the terminal, making identifying failed tests difficult.

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-cms#5101]
## Description
A couple refactors back, it looks like I managed to misplace the outputting-task-results-to-stdout part of the tasks, so important details were getting lost.

## Acceptance Criteria
- [ ] Tasks output gets passed correctly to the terminal for debugging.

**Comment by cmaeng** [comment]
adding to Core sprint 32 as this one got missed in reporting.
