### ISSUE TITLE
Resource Request from Sitewide Crew

### ISSUE THREAD

**Issue by jefflbrauer** [department-of-veterans-affairs/va.gov-cms#5108]
As a delivery manager for the CMS Core Application team on the Platform Crew, I have the engineering skills and capacity available on the team so that I am able to achieve OCTO-DE Platform Q2 and Q3 objectives. 

**Context**
The CMS team has been given the new high priority initiative, "Accelerated Publishing," in which we are being asked to explore options to vastly speed up the time it takes between an editor clicking the publish button, and the content becoming live on VA.gov. Business units have been wary to migrate to our modernized stack because of the current 1-hour timeframe it could take before content is visible, and OCTO-DE has communicated we will resolve the issue by the end of the fiscal year 2021 (Sept 30).

As part of the discovery effort, the CMS team has been provided the full capacity and skills of Nick Sullivan from the Public Websites team. He is proving to be an invaluable asset for our discovery efforts so far, and the team believes that the success of the implementation relies on Nick being a part of the team through completion of the initiative. 

**Therefore, the CMS Core App team requests the full capacity of Nick Sullivan for the duration of Q2 (4/1-6/30, 2021)**

Note - discovery is still in progress, and an extension of this request for Nick's time is very likely. Additional resource requests may be forthcoming, pending prioritization, expected timelines, and skills required.

**Comment by johnhashva** [comment]
@jefflbrauer thanks for documenting this request.  I'd like to ask that instead of an open ended timeline -- _e.g., the CMS Core App team requests the full capacity of Nick Sullivan until the Accelerated Publishing Initiative is complete and accepted by our OCTO-DE Product Owner._ -- we instead revisit this need/priority at the end of next Quarter (July 1).  That will ensure we are time-boxing and can understand impact.  SO this request would codify approval through June then we revisit in July.  Thoughts?

**Comment by jefflbrauer** [comment]
@johnhashva I think that is a fair ask.  Modified as follows:

Therefore, the CMS Core App team requests the full capacity of Nick Sullivan for the duration of Q2 (4/1-6/30, 2021)

Note - discovery is still in progress, and an extension of this request for Nick's time is very likely. Additional resource requests may be forthcoming, pending prioritization, expected timelines, and skills required.

**Comment by jefflbrauer** [comment]
@johnhashva Are you good with this revised language?

**Comment by johnhashva** [comment]
Thanks @jefflbrauer
