### ISSUE TITLE
Limit menu heirarchy to level 2 for Vet Centers

### ISSUE THREAD

**Issue by rachel-kauff** [department-of-veterans-affairs/va.gov-cms#5116]
VHA menu hierarchy is inconsistent for Vet Centers and VAMCs. We should eliminate level 3 from the admin toolbar menu to avoid confusion about VAMC menu behavior as well as overall usability for Vet Centers. 

![Screen Shot 2021-04-22 at 3.30.57 PM.png](https://images.zenhubusercontent.com/5e399cf5446c5b4ca0e31e42/ce74c860-3764-40ce-8fb4-561e53b63a60)

**Comment by kevwalsh** [comment]
This is a dupe of #4582
