### ISSUE TITLE
Improve user edit form

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#5117]
### User Story or Problem Statement

The existing user edit form is 100% out of the box and has a lot of challenges

* Password policy UX
* useless alias form
* No workbench access field for user admins means having to go to multiple tabs
* Bad help text
* Strange order
* No hierarchy
* etc

In the context of #4997, we've stubbed out some major changes to the user form. 

Some questions for discovery
* What user stories are relevant for non-user admins?
* What user stories are relevant for admins? 
* What are the great pain points for each? 
* What opportunities exist to consolidate? 
* Should we have a revision log?
* What are the necessary difference between /user/add form and the user/UID/edit form?
* What parts of the user admin service may be relavant? 
* What does the history of help desk requests teach us about this?

### Affected users and stakeholders

* User admins
* All users who go to edit their form

<link to any existing research or data supporting this>

### Artifacts

https://www.figma.com/file/HpxCd7YNEVG2Np1wddg6LW/Add-user---WIP

**Comment by EWashb** [comment]
This is outdated. many of the questions in this issue have broken out into their own issues with their own roadmaps.
