### ISSUE TITLE
Remove node-list cache tags from graphql results cache

### ISSUE THREAD

**Issue by indytechcook** [department-of-veterans-affairs/va.gov-cms#5124]
## Description

Remove `node_list` cache tags from graphql results cache.  The `node_list` was intended more for views and is a bit of a bomb approach to cache invalidation when we really want to use a hammer.  We still have the individual node:xxx cache tags which are a more focused approach.

http://karimboudjema.com/en/drupal/20190909/node-list-cache-tag-pitfall-drupal-8-views

> The node_list cache tag is generated automatically when we create a view that displays nodes entity type in Drupal 8. This cache tag will invalidate the cache of all views that list any kind of nodes (page, article, ....) when we make a CUD (create, update, delete) action on any kind of nodes.

## Acceptance Criteria
- [ ] 👀 **Needs design review** because the work involves changes to labels or other design elements 
- [ ] 🙈 Can be implemented without consulting design team members
- [ ] Testable_Outcome_X
- [ ] Testable_Outcome_Y
- [ ] Testable_Outcome_Z

**Comment by indytechcook** [comment]
Code which adds tags: docroot/modules/contrib/graphql/modules/graphql_core/src/Plugin/GraphQL/Fields/EntityQuery/EntityQuery.php

```
  protected function getCacheDependencies(array $result, $value, array $args, ResolveContext $context, ResolveInfo $info) {
    $entityType = $this->getEntityType($value, $args, $context, $info);
    $type = $this->entityTypeManager->getDefinition($entityType);

    $metadata = new CacheableMetadata();
    $metadata->addCacheTags($type->getListCacheTags());
    $metadata->addCacheContexts($type->getListCacheContexts());

    return [$metadata];
  }
```

**Comment by indytechcook** [comment]
Cross posting #5131 and #5125

**Comment by indytechcook** [comment]
PR https://github.com/department-of-veterans-affairs/va.gov-cms/pull/5145

**Comment by indytechcook** [comment]
The risk of cache not getting invalidated is low since we do not use views in our GraphQL and the listing tags are only used in views.

**Comment by indytechcook** [comment]
This is in prod now, RDS usage has gown way down:

![image](https://user-images.githubusercontent.com/121603/116263721-99d01680-a747-11eb-95ea-85177ee42767.png)

**Comment by acrollet** [comment]
> This is in prod now, RDS usage has gown way down:
> 
> ![image](https://user-images.githubusercontent.com/121603/116263721-99d01680-a747-11eb-95ea-85177ee42767.png)

🤩
