### ISSUE TITLE
Change management for new VAMC menu settings (IA hardening) 

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#5135]
## Description 

The new menu settings for VAMC editors (from #4988)  require some change management as they get released.

As a VAMC system editor, i need to understand where pages i create can go in the menu and why. 
* Compared to Teamsite, pages can only be added in certain places. 

## Acceptance Criteria
- [ ] Help guide that explains the settings and why
- [ ] Announcement is written for Dave to supply to VHA HQ. VHA HQ will send it to Pittsburgh PAOs and dual state users
- [x] VAMC upgrade team understands the change
- [ ] Help desk team understands the change
- [x] Added to backlog of training materials

**Comment by rachel-kauff** [comment]
Status: Help guide stubbed out here: https://prod.cms.va.gov/help/how-to-manage-vamc-menus. 

Next steps: Finalize help guide content, draft announcement content by next Weds

**Comment by rachel-kauff** [comment]
Dependency: VAMC upgrade team must make sure the four parent items exist in at least draft state for each VAMC site before this announcement can go out.

**Comment by rachel-kauff** [comment]
**Announcement content:**
----

> Subject line: Menu settings for your VAMC site
> 
> Dear CMS editor/ VAMC site manager,
> 
> As we continue to roll out new sites for VAMCs across the country, and improved Veteran experiences, we have some important information to share about your new site's menu. 
> 
> We've designed the VAMC menu so that it doesn't need much maintenance, except when you need to add new pages under some of the "About us" menu items. 
> 
> Learn more about how VAMC menus work, and how to add pages to a menu in this CMS help guide. 
> 
> [How to manage VAMC menus](https://prod.cms.va.gov/help/how-to-manage-vamc-menus#how-to)
> 
> Questions? Reach out to [where should we direct them?].

**Comment by rachel-kauff** [comment]
@kevwalsh The above is ready for review here, or we can look at it during our checkin today.

**Comment by kevwalsh** [comment]
Looks great. I'll let Dave speak to the announcement content above, which will be coming from VHA HQ, and may need tweaking for their voice. 

About the user guide, specifically #3, 4, and 5

![How_to_manage_VAMC_menus___Veterans_Affairs](https://user-images.githubusercontent.com/643678/118856087-8de9f700-b8a4-11eb-933b-3193b2d741dc.png)


3. By the time this goes out, we will be _requiring menu links_. The URL alias for Detail Pages is going to be dependent on them. (this is new, and comes out of some conversation in #4733 (and will be done in #1268) 
4. It's true this is optional. Not sure if we want to encourage it, but your example is valid, a Program h1 could get _very_ long. Discouraging long h1s and locking this down might be ideal, but that would have to be an iteration, we have no issue for that. 
5. FE doesn't actually use Description, i'd like to hide it. I created #5399 for that. Until it's hidden, let's leave this, or adapt to say it doesn't do anything.

**Comment by rachel-kauff** [comment]
@kevwalsh 

> By the time this goes out, we will be requiring menu links.
 
So will the boolean field `Provide a menu link` disappear from the UI then? Can we provide confirmation that the page _will_ appear in the menu?

> By the time this goes out, we will be requiring menu links. The URL alias for Detail Pages is going to be dependent on them. (this is new, and comes out of some conversation in #4733 (and will be done in #1268)

Does this mean that the menu title will _automatically_ be reflected in the URL alias? If so, can we indicate that impact in the help text?

**Comment by rachel-kauff** [comment]
Publishing the content once the work ready is now in the runbook for #2427, which means the last AC is accounted for, even though we didn't publish it this sprint.

**Comment by kevwalsh** [comment]
oops hadn't seen these comments. 

> @kevwalsh
> 
> > By the time this goes out, we will be requiring menu links.
> 
> So will the boolean field `Provide a menu link` disappear from the UI then? Can we provide confirmation that the page _will_ appear in the menu?

It doesn't disappear, but it shows up checked and disabled.
 
> > By the time this goes out, we will be requiring menu links. The URL alias for Detail Pages is going to be dependent on them. (this is new, and comes out of some conversation in #4733 (and will be done in #1268)
> 
> Does this mean that the menu title will _automatically_ be reflected in the URL alias? If so, can we indicate that impact in the help text?

No, they will still be using the node title (h1) to generate the last bit of the URL alias.  But they are dependent on menu item's position in the menu hierarchy to get the _rest_ of the alias (so, outside the editor's immediate scope when creating a page, and ultimately out of their control anyway).

**Comment by kevwalsh** [comment]
![menu-ui-vamc-detail-page](https://user-images.githubusercontent.com/643678/120378481-7e2ed180-c2ec-11eb-9f91-c17a8e65c227.png)
