### ISSUE TITLE
Improve GraphQL support for Vet Center FAQs centralized content

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#5159]
**Describe the defect**

EFF fields do not support entity references inside fetched paragraphs. Vet Center FAQs contain "nested" paragraphs, fields inside a paragraph that reference another paragraph. 

[April 27 2021 slack thread](https://dsva.slack.com/archives/C0FQSS30V/p1619547618048700?thread_ts=1619473606.017200&cid=C0FQSS30V)

**To Reproduce**
GraphQL query for Vet Center FAQS

See screenshot

**Expected behavior**
Full FAQs should be returned

**Screenshots**
![image](https://user-images.githubusercontent.com/643678/116331252-57d1bf80-a79d-11eb-8c15-426fe5e658e1.png)

**Implementation**
- [x] Add 4 "accordion" paragraphs to https://prod.cms.va.gov/node/16142/edit
- [ ] Update Vet Center content model to point to these paragraphs

**Follow up issue**
Supported nested content in EFF / Centralized Content fields

**Comment by swirtSJW** [comment]
This has been resolved in the contributed module here https://www.drupal.org/project/entity_field_fetch/issues/3211972

**Comment by swirtSJW** [comment]
This release will resolve this issue and #5160   https://www.drupal.org/project/entity_field_fetch/releases/1.0.0-beta7
