### ISSUE TITLE
Supported nested content in EFF / Centralized Content fields

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#5160]
## User Story or Problem Statement

Centralized content often needs to have nested entity references, like a "Set of Q&As". Currently EFF doesn't support GraphQL queries to do that (see #5159 for an example and a workaround used in Vet Centers)

## Acceptance Criteria
- [x] EFF field supports GraphQL queries to nested entity references
- [x] Followup issues are created to add this support to existing EFF fields (such as Vet Center FAQs, essentially undoing the work in #5159)

## Implementation steps
<optional>

**Comment by swirtSJW** [comment]
This  issue and 5159 will be resolved as soon as this release is packaged and can be pulled into our repo.
https://www.drupal.org/project/entity_field_fetch/releases/1.0.0-beta7
