### ISSUE TITLE
Date should be required on event nodes.

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#5167]
**Describe the defect**
Currently we can create an event with no date set.  This causes an error in the front end build because it is tying to sort events by date that may not exist.

On bundle event, field_datetime_range_timezone should be set to required.

![image](https://user-images.githubusercontent.com/5752113/116451468-7fbb3480-a82a-11eb-8274-d10fb5cf8a1e.png)

THis lead to an error in the Front end build that looks like this

` can not get the value of NULL on /var/lib/tugboat/docroot/vendor/va-gov/web/src/site/stages/build/drupal/health-care-region.js:257:47`

**To Reproduce**
1. Go to '/node/add/event' and fill in all required fields.
2. Set status to publish  and click on 'save'
3. Save occurs but the event has no date or time.
4. Trigger front end content release, see error

**AC - Expected behavior**
- [ ] An event that does not have a date set should fail validation on not be saved.
- [ ]  automated testing should pass.

**Comment by swirtSJW** [comment]
Thread of the most recent time this broke the content-release
https://dsva.slack.com/archives/C0MQ281DJ/p1637356668309000

**Comment by kevwalsh** [comment]
I went looking through the git history to see if i could find any intention behind this being left optional. Couldn't find any, but because it's a two line code change i went ahead with it, see #7021.

**Comment by kevwalsh** [comment]
Hmm, i'm seeing a php error that's beyond me... sending this back to Iván, sorry! feel free to close my PR (cherry-pick my commit?) 

I'm also wishing that the end date was optional. I see that this is a [drupal core issue](https://www.drupal.org/project/drupal/issues/2794481), and that there's [a contrib module for it](https://www.drupal.org/project/optional_end_date), but i'm betting it won't work with `smart_date` module that we're using.

**Comment by netboss** [comment]
@kevwalsh @swirtSJW 

- Removed existing patches that were originally dealing with (kind of) the same issue and applied patch referenced in this [drupal.org comment](https://www.drupal.org/project/drupal/issues/3096790#comment-14238361).
- The reported PHP error in the `/node/add/event` form is now gone. See attachment: 
![Screenshot from 2021-11-22 18-57-01](https://user-images.githubusercontent.com/846871/142952500-2a08e17e-772c-44af-af8a-1bfc19bb84c2.png)
