### ISSUE TITLE
Add Manual override to CMS triggered content builds

### ISSUE THREAD

**Issue by indytechcook** [department-of-veterans-affairs/va.gov-cms#5177]
## Description

When build publishing occurs, several content build jobs are triggered.  These build jobs along with the hourly build job creates a scenario where several builds are running one after another.  The build jobs which are being triggered earlier are also taking longer to run all of the GraphQL queries.  We are seeing race conditions where the earlier API calls and the later API calls are inconsistent due to new data being published.  This is causing lots of broken links.

Proposal: Add a checkbox to the content build page which turns off the sending of the content build.  This should also contain a timeout so if someone forgets to uncheck the box, we don't miss urgent content being deployed.

## Acceptance Criteria
- [ ] A new checkbox and timebox dropdown appears on the content build page.  If enabled a content build will not be triggered.
- [ ] When the time passes based upon the timestamp selected, the checkbox will be unchecked and build will be allowed.

**Comment by swirtSJW** [comment]
Recommending building the kill switch around architechture provided by https://www.drupal.org/project/shunt

**Comment by indytechcook** [comment]
I reviewed shunt, it doesn't appear to be maintained in D8.  I like the basic concept and in general the code looks good.  

The only commit since early 2017 was from the D9 bots code.  The tests do not pass on the current release and the d9 compatibility code hasn't been released it.  

I'm apprehensive about adding a module with this maintenance record. 

At it's heart, shunt is just a custom Entity with the UI.  I don't want to make something from scratch, I wonder if we can piggy back off of flag.

**Comment by acrollet** [comment]
> I wonder if we can piggy back off of flag.

I like this idea, it's a well-supported, flexible module and we already have it in the codebase.

**Comment by acrollet** [comment]
@indytechcook should we icebox this in favor of the public content API work, or keep it?

**Comment by jkalexander7** [comment]
Closing - GraphQL performance is no longer a bottleneck for content build.
