### ISSUE TITLE
Term views broken by layout builder

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#5178]
**Describe the defect**
This page is fatal erroring 
/fargo-health-care/health-services/caregiver-support-at-va-fargo-health-care

This is the result of the page using the rendered entity view and it trying to use layoutbuilder.

The solution is to remove layout builder from all vocabularies except sections.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information if relevant, or delete):**

**Additional context**
Add any other context about the problem here. Reach out to the Product Managers to determine if it should be escalated as critical (prevents users from accomplishing their work with no known workaround and needs to be addressed within 2 business days).

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Defect")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS objective (orange) (not needed for bug tickets)
- [ ] CMS-supported product (black)

**Comment by acrollet** [comment]
@cmaeng @kevwalsh I changed the milestone to product support, lmk if I missed something :)
