### ISSUE TITLE
Update guidance for facility editors for how to correct Lighthouse-managed data

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#5180]
## Description

We have some misleading guidance for editors about how to address issues with data that have external sources of truth. 

![Create_VAMC_Facility___VA_gov_CMS](https://user-images.githubusercontent.com/643678/116580073-07637a80-a8e1-11eb-907e-3e76ffc937eb.png)

Since Lighthouse is the "middle man" and has all the stakeholder data, it makes sense for CMS users to reach out to Lighthouse if there are data issues with facility data, instead of managing multiple data resolution paths, such as  VAST or other data source manager. 

A [decision was made April 26](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/product-team-support/product-team-weekly-syncs/lighthouse-cms-weekly-sync.md#monday-april-26-3pm-et) to have Lighthouse API team perform triage on any reported issues with data. 

The suggested change was to email Lighthouse (no webform). Here's a very draft email template, needs improvement

```
To: api@va.gov
Subject line: "Issue with facility data for [insert facility ID or name]"
Bcc: vadrupalcms@va.gov
Body:
Something like: [Describe issue with facility data... which field is wrong and how should it be corrected. ] (the clearer the report, the faster the resolution)
Facility Name
Facility ID: 
```

## Example places that need updating

* https://prod.cms.va.gov/node/add/health_care_local_facility
* https://prod.cms.va.gov/node/add/vet_center_mobile_vet_center
* https://prod.cms.va.gov/node/add/vet_center
* https://prod.cms.va.gov/node/add/vet_center_outstation
* Others? 

## Acceptance Criteria
- [ ] All places that contain misleading guidance have been fixed
  - [ ] Email template has been written, including facilityID
  - [ ] Lighthouse team has reviewed email template
  - [ ] Others TBD
- [ ] CMS Help desk understands this as a Tier 3 triage team
- [ ] `external_content` view mode treatment developed for Vet Center has been applied to VAMC facility content type
- [ ] Announcement has been written and ready to send VAMC and Vet Center editors
- [ ] Design review

**Comment by rachel-kauff** [comment]
@ethanteague cc: @kevwalsh I noodled a bit on your email template. What do you think? Is there anything else the lighthouse team would need to know, or complexities to the types of requests people might need to make?

> To: api@va.gov
> Subject line: "Requested updates to [insert facility ID or name] facility data"
> Bcc: vadrupalcms@va.gov
> Body:
> Please update the system with the following changes:
> 
> **Facility:** 
> The facility name and ID below are auto generated. 
> Facility Name: [auto generated]
> Facility ID: [auto generated]
> 
> **Affected data** 
> What kind of information needs updating?
> [Add your response here, for example: facility name, address, phone number, etc.]
> 
> **Requested Update:**
> Describe how the information should be updated.
> [Add your response here, for example, "change street address from 123 Fake Street to 456 Real Street."]
>

**Comment by ethanteague** [comment]
> @ethanteague cc: @kevwalsh I noodled a bit on your email template. What do you think? Is there anything else the lighthouse team would need to know, or complexities to the types of requests people might need to make?
> 
> > To: [api@va.gov](mailto:api@va.gov)
> > Subject line: "Requested updates to [insert facility ID or name] facility data"
> > Bcc: [vadrupalcms@va.gov](mailto:vadrupalcms@va.gov)
> > Body:
> > Please update the system with the following changes:
> > **Facility:**
> > The facility name and ID below are auto generated.
> > Facility Name: [auto generated]
> > Facility ID: [auto generated]
> > **Affected data**
> > What kind of information needs updating?
> > [Add your response here, for example: facility name, address, phone number, etc.]
> > **Requested Update:**
> > Describe how the information should be updated.
> > [Add your response here, for example, "change street address from 123 Fake Street to 456 Real Street."]

@rachel-kauff looks great to me :+1:
