### ISSUE TITLE
Migrate field_hours to field_office_hours on VAMC facility

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#5188]
![Screenshot_2021-04-29__1_19_PM](https://user-images.githubusercontent.com/643678/116592163-abebb980-a8ed-11eb-8fff-2d38105ac99e.png)

![Screenshot_2021-04-29__1_20_PM](https://user-images.githubusercontent.com/643678/116592235-c6be2e00-a8ed-11eb-839c-60f7dd6203bb.png)

ACs
- [ ] new field_office_hours exists
- [ ] populated by migration (migration updates both `field_hours` and `field_office_hours`)
- [ ] backwards compatibility
  - [ ] old field_hours field is hidden
  - [ ] new field_office_hours field is visible to non-admin editors in view mode on both the edit and view screens
  - [ ] new field_office_hours field is visible to admins in edit mode on edit screen (like on Vet Centers)
- [ ] Design review

Not included
-[ ] Redesign field_office_hours form widget (because this form widget is only visible to admins)

**Comment by ethanteague** [comment]
Apologies for missing something that I have a feeling is probably super obvious, @kevwalsh ......why are we doing this? We are creating a new (table?) field, and using it instead of field_hours (I _think_ you meant `field_facility_hours`)......is it a namespace thing?

**Comment by swirtSJW** [comment]
I believe this is to bring it inline with the hardened hours field we are using on vetcenters.
We will need to change the facility migration to match the handling in the vetcenter migration.   Kaise worked out a new method for importing the hours into the new field.

**Comment by swirtSJW** [comment]
This has been merged.  After it makes it to prod, we'll have to: 
- [ ] run the migration 
- [ ] notify facility team that the field can be swapped out on the front end.

**Comment by swirtSJW** [comment]
It seems like this was not done after the code landed on prod so I just ran it
- [x] run the migration with update flag

![image](https://user-images.githubusercontent.com/5752113/153084332-cc5968d2-d177-4446-b210-c32f8017cacd.png)


![image](https://user-images.githubusercontent.com/5752113/153085358-8fe375c6-1c08-4962-b3d0-3328cf1a3a63.png)
