### ISSUE TITLE
 Update composer.json file in cms repo to use new package

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-cms#5193]
## Description

When the new content build process goes live, (tentatively on Wednesday, May 5 2021) the composer.json file will need to be updated to use https://github.com/department-of-veterans-affairs/content-build instead of https://github.com/department-of-veterans-affairs/vets-website

This is the packagist package:

https://packagist.org/packages/va-gov/content-build

## Acceptance Criteria
- [ ] Content build uses new repo
- [ ] Manual content release succeeds on tugboat
- [ ] All automated tests pass

**Comment by indytechcook** [comment]
I put up a PR to see if tests run: https://github.com/department-of-veterans-affairs/va.gov-cms/pull/5199

**Comment by indytechcook** [comment]
There is an issue with the install repos script.  PR to fix: https://github.com/department-of-veterans-affairs/content-build/pull/94

**Comment by indytechcook** [comment]
Question out to Tim regarding version numbers: 

> do you know if the release number schema will change?  it's currently v0.0.x.  In vets-website it is v0.1.x.

**Comment by indytechcook** [comment]
Tim answered that the releases will stay the same.
