### ISSUE TITLE
Update content release branch/PR build functionality for new content build

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-cms#5194]
## Description

When a user makes a content release on Tugboat or Lando, they are given the option to select a front end branch or PR. This functionality will have to be updated to work with the separated content build.

## Acceptance Criteria
- [ ] Default, Branch & PR builds complete successfully and use the correct Branch

**Comment by indytechcook** [comment]
Speaking with @swirtSJW in Slack.  We don't have a use case for needing to pull in a different `vets-website repo.  Keeping this task focused on `content-build` will be much simplier.

**Comment by indytechcook** [comment]
This appears to be an access issue to the new repo

```
root@php:/var/lib/tugboat/web# git ls-remote --heads origin | cut -f2 | sed 's#refs/heads/##'
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
root@php:/var/lib/tugboat/web# git remote -v
origin	git@github.com:department-of-veterans-affairs/va.gov-cms.git (fetch)
origin	git@github.com:department-of-veterans-affairs/va.gov-cms.git (push)
root@php:/var/lib/tugboat/web#
```
