### ISSUE TITLE
Broken links no longer showing in tugboat

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-cms#5204]
**Describe the defect**

Broken links no longer showing in tugboat.  The following message errors instead

```
Broken links found. See results in /var/lib/tugboat/docroot/vendor/va-gov/web/logs/vagovdev-broken-links.json
```

**To Reproduce**
1. Perform a manual content release on a current branch in tugboat

**Expected behavior**
Displays a list of broken links

## Acceptance Criteria

- [ ] Manual content releases on Tugboat complete successfully
- [ ] Broken link report is displayed in a human-readable format in the log linked from the content release page

**Comment by indytechcook** [comment]
I wasn't able to reproduce this on https://cms-iydimthvd3hrvq7jouivmtvppihrogq6.ci.cms.va.gov/admin/content/deploy/logs

But there broken links are no longer listing out items 

```
Broken links found. See results in /var/lib/tugboat/docroot/vendor/va-gov/web/logs/vagovdev-broken-links.json.
```

**Comment by indytechcook** [comment]
Reminder that the solution also has to work on the content-build repo

**Comment by mchelen-gov** [comment]
was there some other AC here about getting broken links into logs?

**Comment by acrollet** [comment]
> was there some other AC here about getting broken links into logs?

yes thanks, updated

**Comment by ncksllvn** [comment]
i'll open a PR for this

**Comment by acrollet** [comment]
@ncksllvn I think @indytechcook is in progress on this work, please make sure to touch base with him 🙂

**Comment by ncksllvn** [comment]
Hm so the file is successfully writing - it just can't be accessed - is that correct?

**Comment by mchelen-gov** [comment]
do tugboat instances need to be reset?

**Comment by indytechcook** [comment]
> do tugboat instances need to be reset?

No, the normal refresh process will pick up the changes.
