### ISSUE TITLE
Increase size of EC2 Server

### ISSUE THREAD

**Issue by indytechcook** [department-of-veterans-affairs/va.gov-cms#5206]
## Description

Increase size of EC2 Server to handle more content and traffic from editors and GraphQL

## Acceptance Criteria
- [ ] Testable_Outcome_X
- [ ] Testable_Outcome_Y
- [ ] Testable_Outcome_Z
- [ ] Requires design review

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [x] `Core Application Team`
- [ ] `Product Support Team`

**Comment by acrollet** [comment]
@indytechcook do you think this is still relevant/needed?

**Comment by indytechcook** [comment]
Probably Not.
