### ISSUE TITLE
Have tugboat used unless it is a content build or if it master and we are building vagovprod

### ISSUE THREAD

**Issue by indytechcook** [department-of-veterans-affairs/va.gov-cms#5207]
## Description

Have tugboat used unless it is a content build or if it master and we are building vagovprod

## Acceptance Criteria
- [x] The vets-website build uses tugboat for all builds except a content release and vagovprod.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [x] `Core Application Team`
- [ ] `Product Support Team`

**Comment by ncksllvn** [comment]
I merged a PR for this along with another patch for the broken link checker yesterday. https://github.com/department-of-veterans-affairs/vets-website/pull/17044

![image.png](https://images.zenhubusercontent.com/59cb9de1b0222d5de47953d8/2d6b91cf-d552-4826-a321-d89f96e8d95d)

Should be all set on this one
