### ISSUE TITLE
Increase migration http fetcher timeout

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-cms#5217]
## Description

In order to attempt to reduce errors like:

`Error message: cURL error 28: Operation timed out after 30000 milliseconds with 0 bytes received (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) at https://www.northernindiana.va.gov/locations/facilities.asp`

Let's try increasing the timeout.

Background: https://dsva.slack.com/archives/CJT90C0UT/p1620001428152500

## Implementation

https://www.drupal.org/project/migrate_plus/issues/3039210#comment-13109652

## Acceptance Criteria
- [x] `migrate_plus` http fetch timeout is 60 seconds

**Comment by ElijahLynn** [comment]
My concern with this approach is that it will probably still cause a bunch of flickers. I think we should try a backoff retry, and go up to 60 seconds. e.g. Try, wait up to 60 seconds, fail, try again in 10 seconds, wait up to 60 seconds, fail, try again in 20 seconds etc.

**Comment by mchelen-gov** [comment]
let's go ahead and increase this to 60s, then follow up with monitoring to get a better understanding https://github.com/department-of-veterans-affairs/va.gov-cms/issues/5537

**Comment by acrollet** [comment]
Iceboxing bc the root cause is being worked on by the Teamsites team.

**Comment by ElijahLynn** [comment]
> Iceboxing bc the root cause is being worked on by the Teamsites team.

Discussions here:
https://dsva.slack.com/archives/CJT90C0UT/p1625844373153500
https://dsva.slack.com/archives/CJT90C0UT/p1625846584162700
