### ISSUE TITLE
Any periodic task failure prevents remaining tasks from being run

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-cms#5234]
## Description
Periodic tasks are relied upon to do the facility status migration _and_ run cron.  Currently, if there is an error in the facility status migration, then it means that cron will not be executed for as long as that error persists.  Which might, in some cases, be ~8 hours or longer.

## Implementation

This is a good opportunity for an upstream PR, but I'm not exactly sure what form it would take, or how to refer to this sort of pattern.  Coalescing errors?  Aggregating errors?  Agglutinating?

## Acceptance Criteria
- [ ] Task <sub>_n_ + 1</sub> from a list of periodic tasks will executed whether Task <sub>_n_</sub> succeeds or fails.
- [ ] Notifications for any & all failed tasks are delivered to Slack.

**Comment by acrollet** [comment]
@mchelen flagging this for discussion during our sprint priority/roadmapping discussion. Good example of something that doesn't necessarily fit well under an initiative or high level epic but nonetheless should be prioritized.
