### ISSUE TITLE
Benchmark GraphQL performance against Q2 performance requirements

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-cms#5241]
## Description

In order to understand what additional effort (if any) is required to meet our Q2 GraphQL performance goal, (#4396) we should perform benchmarks under simulated worst-case conditions.

## Implementation

Run the current content build against the cms-test production infrastructure with these parameters:
- 50k published nodes
- cold cache
- simulated editor load of 50 simultaneous logged in users, each loading 1 page per minute, 10% of page loads being a node publish

See https://dsva.slack.com/archives/CT4GZBM8F/p1620232996104800?thread_ts=1620232926.104500&cid=CT4GZBM8F for further discussion.

## Acceptance Criteria
- [ ] Benchmarking procedure is scripted to allow re-running after code/infrastructure modifications
- [ ] GraphQL query times for 10 runs under the conditions specified in the Implementation section are posted to this issue

**Comment by mchelen-gov** [comment]
can we calculate real world GQL and build time per page using http://grafana.vfs.va.gov/d/dxf8a-6Zz/cms-dashboard and estimate what that means for 50k nodes?

**Comment by acrollet** [comment]
> can we calculate real world GQL and build time per page using http://grafana.vfs.va.gov/d/dxf8a-6Zz/cms-dashboard and estimate what that means for 50k nodes?

@mchelen to me that depends on a couple of things:

- whether the AC for the parent epic is that we should **usually** or **always** be under 30 minutes GQL time with 50k published nodes (if the AC is a hard requirement, IMO we should benchmark under simulated worst-case conditions)
- whether we can deprioritize this epic for a sprint while we get more data points (we only have about 24 hours of data with most of the non-prod builds not pulling content from our production instance)

**Comment by mchelen-gov** [comment]
@acrollet ah yeah those are good points, maybe we look at real world perf as part of the "monitoring and alerting" epic and keep synth benchmarks here? then decide which to do when

**Comment by acrollet** [comment]
Closing this out in favor of #5420
