### ISSUE TITLE
Improve GraphQL cache invalidation behavior

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-cms#5243]
## Background

The current cache invalidation behavior for GraphQL responses [is not optimal](#5176). This means that editing a single page can invalidate most or all of the cached GraphQL responses, requiring them to be re-generated at the next content build time. The ideal would be for only truly dependent responses to be invalidated when a given page is edited.

### Hypothesis

We believe that updating the GraphQL module to use per-entity type cache tags instead of the global `node_list` cache tag will improve GraphQL response times after nodes are edited. ([demonstrated performance benefits](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/5124))

### Assumptions
- Using per-entity type cache tags will provide a significant percentage of the performance benefits seen when removing the `node_list` cache tag entirely. This will be validated by implementing the solution for one entity type and doing timings for the content build GraphQL queries with and without the solution in place.

## Acceptance Criteria
- [ ] Automated tests have been written to confirm correct behavior for known cross-content type dependencies
- [ ] Per-entity type caching has been implemented for GraphQL queries and benchmarked to show improvement

**Comment by jkalexander7** [comment]
Closing - low value high effort. Not needed unless GraphQL performance degrades significantly.
