### ISSUE TITLE
Update Grafana dashboard to new content build pipeline

### ISSUE THREAD

**Issue by mchelen-gov** [department-of-veterans-affairs/va.gov-cms#5252]
## Description

https://github.com/department-of-veterans-affairs/va.gov-cms/issues/4700 is pointing to old `vets-website` content build pipeline

## Acceptance Criteria
- [ ] http://grafana.vfs.va.gov/d/dxf8a-6Zz/cms-dashboard shows build metrics for `content-build` build pipeline

**Comment by acrollet** [comment]
PR here: https://github.com/department-of-veterans-affairs/devops/pull/9124

**Comment by acrollet** [comment]
PR merged, will close this issue when after confirming that data comes in from the next content build.

**Comment by acrollet** [comment]
<img width="688" alt="Screen Shot 2021-05-06 at 12 00 38 PM" src="https://user-images.githubusercontent.com/101649/117344574-c16b6100-ae62-11eb-8313-9a75b173992a.png">
