### ISSUE TITLE
GraphQL query order in the content build causes race condition issues

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-cms#5255]
## Description

During the content build process, sometimes race conditions can occur when listings are generated with a link to a piece of content that has just been published:

> This was a race condition where the content release did the following in or order:
> 1.  built individual stories pages which did not contain the latest story because it was published just after.
> 2. Built the page at /eastern-colorado-health-care/ which contains the list of stories from a query that ran AFTER the latest story was published. So it included a link to the story which was not part of the stories pages built in # 1

We believe that re-ordering the [queries in the content build](https://github.com/department-of-veterans-affairs/content-build/blob/master/src/site/stages/build/drupal/individual-queries.js#L93) to run listing queries as close to the beginning of the process as possible will help.

## Acceptance Criteria
- [x] queries that build event, stories, staff, and press releases get moved to the bottom of the list
- [x] queries that  generate lists move as high up the list as possible.

**Comment by acrollet** [comment]
Pointed at 2 per @indytechcook

**Comment by acrollet** [comment]
re-estimated to account for risk in changing queries.

**Comment by indytechcook** [comment]
This issue had to be reverted in https://github.com/department-of-veterans-affairs/content-build/pull/424

@acrollet should I repoen this one or create a new issue to redo the work?  There is a new blocking issue with https://github.com/department-of-veterans-affairs/va.gov-team/issues/28292 and any follow up work from that issue.
