### ISSUE TITLE
Granular documentation of current state user admin process for existing products

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#5264]
**ACs**
- [ ] Currrent state service blueprint phases have been applied and documented for each product
- [ ] Documentation can be immediately used by Helpdesk 
- [ ] Documentation can serve conversations with stakeholders and product owners about future state user admin services. 

![User_admin_service_discovery_•_Agile_Six.png](https://images.zenhubusercontent.com/5d6e57ad330f64311395f08b/04b423c0-0723-4c93-848c-9dba99d00e57)

**Comment by EWashb** [comment]
this is not currently within scope. we have various runbooks and helpdesk processes
