### ISSUE TITLE
Use Jenkins step time for "Build Time" metric in Grafana

### ISSUE THREAD

**Issue by mchelen-gov** [department-of-veterans-affairs/va.gov-cms#5276]
## Description

The script to pull "Build Time" from Jenkins should reflect the total time on the "Build" step of Jenkins pipeline, however this info is not available from currently used endpoint or log.

For example the "Build" step took `4m 12s` on http://jenkins.vfs.va.gov/blue/organizations/jenkins/builds%2Fcontent-build-content-only-vagovprod/detail/content-build-content-only-vagovprod/45/pipeline

Which doesn't exist in:
- http://jenkins.vfs.va.gov/job/builds/job/content-build-content-only-vagovprod/45/api/json
- http://jenkins.vfs.va.gov/job/builds/job/content-build-content-only-vagovprod/45/consoleText

@olivereri found this data available in workflow API:

- http://jenkins.vfs.va.gov/job/builds/job/content-build-content-only-vagovprod/wfapi/runs
- http://jenkins.vfs.va.gov/job/builds/job/content-build-content-only-vagovprod/45/wfapi/describe

slack thread: https://dsva.slack.com/archives/CT4GZBM8F/p1620332056181300

## Acceptance Criteria
- [ ] "Build Time" in [Grafana panel](http://grafana.vfs.va.gov/d/dxf8a-6Zz/cms-dashboard?orgId=1&refresh=5s&from=now-2d&to=now&var-datasource=Prometheus%20(Utility)&var-environment=prod&var-app_name=cms) shows time spent on "Build" step in Jenkins [job](http://jenkins.vfs.va.gov/blue/organizations/jenkins/builds%2Fcontent-build-content-only-vagovprod)

**Comment by acrollet** [comment]
@jefflbrauer @mchelen Added this to sprint 32 and bumped #4694
