### ISSUE TITLE
Establish scope and draft "What is the VA.gov CMS" and other basic intro video(s)

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#5288]
* All CMS users need the same basic understanding of the role of the CMS. 
* So too do VFS product team members, Platform members, onboarding CMS team members, and other stakeholders at VA. 
* now that we have created trainings for multiple products, we have an idea of what topics 1) can be covered ahead of time 2) are universal to all products

How might we provide create a product video that introduces basic CMS concepts to all audiences? 

What aspects of the trainings for all products can be done "ahead of time", either in this first video or in followups, without any product-specific training? 

## ACs
- [x] Establish Scope - what's in and what's out
- [x] Establish "budget" - timebox for creation, and how long this video should be, or if there should be more than one. 
- [x] Outline the video(s) and/or a first pass to have something to react to.
- [x] PO review

## Not included

- [ ] Getting feedback from various audiences 

## See also

VAMC video.

**Comment by xiongjaneg** [comment]
See VAMC video as a model https://www.youtube.com/watch?v=H8hndge4wLc

**Comment by xiongjaneg** [comment]
Per Dave, make training front loaded, product agnostic for scalability, 20-30 minute video in advance why we are doing this.
For each product, start with two generic training videos for everyone then go to product specific videos.

1. Overview
2. Editorial workflow
3. Product forms

**Comment by xiongjaneg** [comment]
topic outline at https://docs.google.com/document/d/1iNra8ckZ9JiWU76yO0N74XEfPugj9KfnsR8nBXZeoHY/

reviewed internally, currently being reviewed by Dave and John

**Comment by xiongjaneg** [comment]
See 
https://dsva.slack.com/archives/CT4GZBM8F/p1622728702225800

Recommended: 
Align with help desk issues
Add login
Remove training env
Move help center
