### ISSUE TITLE
Finalize "What is VA.gov CMS" orientation trainings

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#5289]

**Comment by xiongjaneg** [comment]
## User story
As an editor for any product, I need to know the purpose and design behind the CMS that I'll use to communication with Veterans.

## Acceptance criteria
- [ ] storyboard two product-agnostic intro training videos
- [ ] PO review
- [ ] record and caption
- [ ] available on CMS help center
