### ISSUE TITLE
Move CMS documentation to Platform Site

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-cms#5295]
## Background

As a Platform engineer, I need access to CMS documentation in a centralized location, so that I may easily learn how to use the CMS and interact with CMS-provided services.

## Description

CMS docs will need to be moved to confluence, with collaboration between the Core & Product Support teams.

## Acceptance Criteria

- [ ] TBD

**Comment by TheBoatyMcBoatFace** [comment]
This is handled elsewhere. Closing
