### ISSUE TITLE
Add web url to to lighthouse push for vet center facility and variants

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#5308]
## User Story or Problem Statement
(from Facilities call on 5/12/21)
AS a facility locator user I would like to have a link that takes me to published Vet Center variants.

Idea:  when a 

- vet center
- MVC
- Outstation ??
- CAP ??
is published, our push to lighthouse contains a  url parameter lighthouse can use to provide a link if one exists, or a generic detail page if not.

## Acceptance Criteria
- [ ] Testable_Outcome_X
- [ ] Testable_Outcome_Y
- [ ] Testable_Outcome_Z
- [ ] Requires design review

**Comment by jilladams** [comment]
This is a very old ticket. We already send Vet Center path information from CMS via the facility migration: 

https://prod.cms.va.gov/admin/structure/migrate/manage/facility/migrations/va_node_facility_vet_centers/process
![Image](https://github.com/user-attachments/assets/ba2ff0a1-f99e-41de-bac6-e79d5cb7a943)

@omahane I'm gonna close this, but please reopen if I'm wrong about that.
