### ISSUE TITLE
[SPIKE] Determine leading indicators for system performance

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-cms#5322]
## Description

The CMS devops & engineering teams will meet to collaboratively identify leading performance indicators that should be monitored. This will allow the team to proactively identify performance-related issues and scale the CMS infrastructure.

## Acceptance Criteria
- [ ] 1 hour session is held to review [discovery doc](https://docs.google.com/document/d/1LlxH026S1OPny-FtpokuxHv30v9AuMt2aoWTUUct_lw/edit)
- [ ] missing high-value leading performance indicators are identified with issues created and linked from this issue

**Comment by acrollet** [comment]
Related: https://docs.google.com/document/d/1LlxH026S1OPny-FtpokuxHv30v9AuMt2aoWTUUct_lw/edit

**Comment by mchelen-gov** [comment]
closed as out of scope for https://github.com/department-of-veterans-affairs/va.gov-cms/issues/5404
