### ISSUE TITLE
Deleting a staff profile does not remove the empty slot in field_leadership on listing pages.

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#5331]
**Describe the defect**
If a staff profile is referenced in field_leadership and then the staff profile is deleted, the spot where the profile existed is blank in the field_leadership widget.
If the leadership listing page is never opened and saved, we are sending NULL entries via graphQL.
Opening and saving the listing page removes the empty item automatically and solves the problem.

It is possible this removing the empty takes place in JS or in formstate processing that does not fire for a programmatic save.

**Background**

This will have less priority when https://github.com/department-of-veterans-affairs/va.gov-team/issues/24708 is fixed. 

This is may also be resolved by #5334. 

There may also be other examples where deleting referenced content leads to issues with the content that references it. 

**To Reproduce**

**Expected behavior**
When a staff profile is deleted, we are not sending null items for field_leaderhip via graphQL.

**Screenshots**

**Desktop (please complete the following information if relevant, or delete):**

**Additional context**
Add any other context about the problem here. Reach out to the Product Managers to determine if it should be escalated as critical (prevents users from accomplishing their work with no known workaround and needs to be addressed within 2 business days).

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Defect")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS objective (orange) (not needed for bug tickets)
- [ ] CMS-supported product (black)

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [x] `Core Application Team`
- [x] `Product Support Team`

**Comment by Agile6MSkinner** [comment]
Both of the tickets that "might resolve it" are completed and it has been languishing for over three years. Safe to say it's fixed or not a priority.
