### ISSUE TITLE
Remove success messages for content refresh to #cms-notifications

### ISSUE THREAD

**Issue by ElijahLynn** [department-of-veterans-affairs/va.gov-cms#5348]
## Background 

The notifications of e.g. "Web content refresh in vagovstaging completed." are creating unnecessary noise. 

We should follow the [Rule of Silence](http://www.linfo.org/rule_of_silence.html) (thanks @ndouglas) and turn these off, leaving only notifications that have something surprising, interesting or useful to say.  

https://github.com/department-of-veterans-affairs/vets-website/blob/9141a98b44629f0be7be7258882bb7a7b9068dd2/Jenkinsfile.content#L83-L92

## Acceptance Criteria

- [ ] "Web content refresh in vagovstaging completed" notifications have been disabled

**Comment by ElijahLynn** [comment]
Slack thread that I asked if anyone else wanted it > https://dsva.slack.com/archives/C01512KN35G/p1621272451173900

**Comment by ndouglas** [comment]
<img width="448" alt="Screenshot 2023-05-16 at 8 13 48 AM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/1318579/244cb01e-3a93-4a8a-980b-20e9db086d99">

This does not appear to have happened since December 1, 2021.
