### ISSUE TITLE
[Drupal 9 Upgrade] Determine why file length was removed from some download links.

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-cms#5352]
## Description
In the [D8 vs. D9 pages.json diff](https://gist.github.com/ndouglas/aecef3575f91f47a0a5bba83abcd2fd5), one issue that arose on a couple of pages was that `length` was removed from certain links, e.g.

```
<a href=\"http://va-gov-cms.lndo.site/sites/default/files/2020-10/Vocational-Services-Open-Briefing_Webex_Flyer.pdf\" type=\"application/pdf; length=574302\" title=\"Vocational-Services-Open-Briefing_Webex_Flyer.pdf\">Flyer for Vocational Services Open Briefing</a>
```

A quick check hasn't led to any obvious explanation.  The file is indeed present and accessible via the provided URL.  The D8 and D9 versions of pages.json were generated from the same database without any unrelated data changes.

This seems to affect _every_ link of that format:

<img width="387" alt="Screen Shot 2021-05-17 at 9 00 25 AM" src="https://user-images.githubusercontent.com/1318579/118492746-53d6f480-b6ee-11eb-8d3a-5fd59e0192d4.png">

So I'm guessing that it is an innocent change of behavior between 8.9/9.0 and 9.1, but I haven't been able to positively confirm that.

## Acceptance Criteria
- [ ] The cause of the removal of the length sub-attribute (?) has preferably been identified and addressed, or if this is not possible, has been determined to cause no issue.

**Comment by ndouglas** [comment]
This is because of [this patch](https://www.drupal.org/files/issues/2020-07-22/2991219-20-D_9_1_x.patch) to resolve [this issue](https://www.drupal.org/project/drupal/issues/2991219).  I can't see anywhere that this is used in `vets-website`.  @acrollet I can trivially add the file size back, but after reading the referenced issue this appears to be a very intentional (albeit minor) change.

**Comment by acrollet** [comment]
@ndouglas makes sense to me, I don't see any reason to add it back. Nice find!
