### ISSUE TITLE
[Drupal 9 Upgrade] Deal with removed, empty path items in entityUrl.breadcrumb

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-cms#5353]
## Description
[The D8 vs. D9 pages.json diff](https://gist.github.com/ndouglas/aecef3575f91f47a0a5bba83abcd2fd5) seems to indicate some places where items with empty paths have been removed from entityUrl.breadcrumb in some `locations_listing` nodes:

<img width="513" alt="Screen Shot 2021-05-17 at 9 14 40 AM" src="https://user-images.githubusercontent.com/1318579/118494624-5aff0200-b6f0-11eb-8e92-72e7f0c574df.png">

This might be nothing more than a matter of data hygiene that goes unaddressed in Drupal 8.9 but not in Drupal 9.1 -- if so, we should probably just repair the data.

## Acceptance Criteria
- [ ] Removed items have been addressed, either with a PR, followup issue, or by changing (correcting?) the data in the database.

### CMS Team
- [x] `Core Application Team`

**Comment by kevwalsh** [comment]
Some background, but may be already known. 

Based on that screenshot, these are all the `<nolink>` menu items, which should indeed have no path value in the breadcrumb, for creating these groupings 

![VA_Butler_Health_Care___Veterans_Affairs.png](https://images.zenhubusercontent.com/5d6e57ad330f64311395f08b/d1518f2f-474f-4e89-9530-f3d3352aeda0)

This functionality (originally in https://www.drupal.org/project/special_menu_items) was added to core in 8.2.0.

**Comment by ndouglas** [comment]
That's **great** info, @kevwalsh.  That was totally unknown to me but gives me a lot to work with.  Thank you!

**Comment by ndouglas** [comment]
As discussed in #5351, I'm still working on isolating the actual causes of these differences.

As far as their severity, though, it seems as though the frontend as built is continuing to function correctly with regard to these breadcrumbs (minus some CSS issues that I think are unrelated to the D9 upgrade):

<img width="1792" alt="Screen Shot 2021-06-17 at 1 49 54 PM" src="https://user-images.githubusercontent.com/1318579/122459307-c867b200-cf7e-11eb-961c-59c1bd094ed2.png">
<img width="1792" alt="Screen Shot 2021-06-17 at 1 46 15 PM" src="https://user-images.githubusercontent.com/1318579/122459327-cef62980-cf7e-11eb-964d-0bcff0b63ee0.png">
