### ISSUE TITLE
Automatically update content-build nightly (dependabot)

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-cms#5358]
## User Story or Problem Statement

As an engineer, I need updates to `content-build` to be automatically applied, in order to keep the build process/tests current, and avoid spending time on repetitive tasks

## Acceptance Criteria
- [ ] `content-build` updates are applied nightly when all tests pass

## Implementation steps
- https://github.com/marketplace/actions/dependabot-auto-merge (?)
- We may wish to clone & own this action (or another selected for the purpose) for security/stability purposes

**Comment by ElijahLynn** [comment]
#1770 #2234 #2560

**Comment by acrollet** [comment]
Related: #954 and #1973

**Comment by ElijahLynn** [comment]
Note to self: Put rational here, e.g. Dependabot disabled this because <reason>.

**Comment by ElijahLynn** [comment]
Related discussion with workarounds for GitHub dropping native automerge from Dependabot  > https://github.com/dependabot/dependabot-core/issues/1973.

**Comment by ElijahLynn** [comment]
> Note to self: Put rationale here, e.g. Dependabot disabled this because `<reason>`.

> Auto-merge will not be supported in GitHub-native Dependabot for the foreseeable future. We know some of you have built great workflows that rely on auto-merge, but right now, we’re concerned about auto-merge being used to quickly propagate a malicious package across the ecosystem. We recommend always verifying your dependencies before merging them.

source: https://github.com/dependabot/dependabot-core/issues/1973#issuecomment-640918321

> For those of you who have vetted your dependencies, or are only using internal dependencies, we recommend adding third-party auto-merge apps, or setting up GitHub Actions to merge.

source: https://github.com/dependabot/dependabot-core/issues/1973#issuecomment-830660356

**Comment by ElijahLynn** [comment]
I want to throw out the possibility to investigate https://violinist.io/ which specializes in Composer updates specifically, which I heard about from @mglaman.

**Comment by ElijahLynn** [comment]
> I want to throw out the possibility to investigate https://violinist.io/ which specializes in Composer updates specifically, which I heard about from @mglaman.

I don't see any automerge functionality in Violinist's configuration docs > https://docs.violinist.io/.

**Comment by mglaman** [comment]
There is no automerge, as far as I know. I was going to look at what GitHub Actions are available to do this. "If from Violinist and checks passing, merge automatically"

**Comment by TheBoatyMcBoatFace** [comment]
This is done. Closing.
