### ISSUE TITLE
node_link_report module is not fully compatible with Drupal 9

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-cms#5365]
## Description

During #4945 we discovered that `node_link_report` needs updates for full Drupal 9 compatibility. This is a tracking issue for https://www.drupal.org/project/node_link_report/issues/3148239

## Acceptance Criteria
- [ ] `node_link_report` functions without errors on Drupal 9

**Comment by swirtSJW** [comment]
I just update  this upstream and kicked off a dependabot run so expecting a pr to be spun up automatically soon.

**Comment by acrollet** [comment]
Thanks @swirtSJW !
