### ISSUE TITLE
Fieldgroup tooltips act as a form submit button. 

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#5366]
**Describe the defect**

Fieldgroup tooltips (eg node/3756/edit) act as a form submit button. 

**To Reproduce**
1. Go to node/3756/edit
2. Click on question mark icon 
3. Note that the form submits 

**Expected behavior**
There should be no special click behavior.

**Screenshots**
![Edit_Vet_Center_Escanaba_Vet_Center___VA_gov_CMS](https://user-images.githubusercontent.com/643678/118542591-32dbc700-b721-11eb-97cd-04ba245ff3e1.png)

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [x] `Core Application Team`
- [x] `Product Support Team`

**Comment by acrollet** [comment]
@kevwalsh I'm blocking this on the D9 upgrade since tooltips will have some changes.

**Comment by ndouglas** [comment]
Might be related to or solved by #5364 since there was a Tippy upgrade involved.

**Comment by ndouglas** [comment]
Not solved by #5364.  I'll look into this today.
