### ISSUE TITLE
Error in DBLog: 

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-cms#5367]
**Describe the defect**
Error pops up in DBLog under testing D9:

```
Error: Call to undefined method 
Drupal\file\Entity\File::url() 
in va_gov_backend_preprocess_paragraph() 
line 1813 of va_gov_backend.module
```

Not sure what triggered it -- just noticed it after clicking into the log.

## Acceptance Criteria
- [ ] Deprecated `File::url()` method is no longer used in our custom modules

**Comment by acrollet** [comment]
Possibly helpful: https://www.drupal.org/project/image_url_formatter/issues/3164787

**Comment by acrollet** [comment]
I added #5377 as a follow-on.
