### ISSUE TITLE
file storage warning on D9 

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#5368]
## Describe the defect
Seeing this warning on visiting a revision page in D9 test on tugboat.  I saw it when comparing a revision, but could not get it to re-show the warning.  I am not sure it was directly tied to the revision or just happened to coincide with something someone else had done and I just happened to get the warning.

```
Warning: touch(): Utime failed: Operation not permitted in Drupal\Component\PhpStorage\MTimeProtectedFastFileStorage->save() (line 100 of core/lib/Drupal/Component/PhpStorage/MTimeProtectedFastFileStorage.php).
```

This issue is timeboxed
## Acceptance Criteria

- [ ] Attempt to reproduce and resolve defect within the estimate timebox

**Comment by acrollet** [comment]
Related: #2797

**Comment by acrollet** [comment]
This may be specific to Tugboat per @indytechcook

**Comment by acrollet** [comment]
@ethanteague if you have time this sprint, this would be a great issue to pick up. Thanks!!

**Comment by ethanteague** [comment]
@acrollet when saving nodes and visiting revisions for multiple content types in the D9 instance (and just clicking around in general) I'm not able to replicate this behavior. Do we feel okay calling this a one-off / fluke / tugboat related thing?

**Comment by acrollet** [comment]
@ethanteague yes, thanks for looking into it! I think we can close this in favor of #2797
