### ISSUE TITLE
Implement again #4639 Asset file restoration to lower environment deploys is too slow

### ISSUE THREAD

**Issue by olivereri** [department-of-veterans-affairs/va.gov-cms#5369]
#4639 was implemented by https://github.com/department-of-veterans-affairs/devops/pull/8786 but reverted due to failures by 
https://github.com/department-of-veterans-affairs/devops/pull/8816

ACs:

- [ ] Investigate why PR 8786 failed
- [ ] Implement again 8786 with fix

**Comment by acrollet** [comment]
PR here: https://github.com/department-of-veterans-affairs/devops/pull/9663
