### ISSUE TITLE
Add unit tests for UserPermsService

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-cms#5370]
## Description

Unit tests should be created for the `UserPermsService` Service in `va_gov_user`. It may be worth doing #1699 in tandem with this issue while the same code is being worked on.

## Acceptance Criteria
- [ ] Unit tests are created for each method of the service

**Comment by acrollet** [comment]
Moved to AC in #5420

**Comment by mchelen-gov** [comment]
^ should be https://github.com/department-of-veterans-affairs/va.gov-cms/issues/1699 i think

**Comment by acrollet** [comment]
> ^ should be #1699 i think

zenhub strikes again - fixed, thanks!!!
