### ISSUE TITLE
Linkit should not allow entering unknown internal paths

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-cms#5376]
## Background

The [linkit](https://www.drupal.org/project/linkit) module has two pieces of functionality that work together to allow entering stable internal Drupal paths (e.g. `/node/84`) and have them converted to path aliases (e.g. `/pittsburgh-health-care/locations/pittsburgh-va-medical-center-university-drive`) at render time. This is enabled by the JS autocomplete widget inserting metadata in the `a` tag, like so:

`<a data-entity-substitution="canonical" data-entity-type="node" data-entity-uuid="6025ca20-9912-4688-aa2f-508b7a872107" href="/node/16184">`

Occasionally, this does not happen, and the `a` tag is stored with no metadata. This creates broken link errors, because the node path is not converted to an alias, and the node path is unavailable on VA.gov.

## Impact

Editors can unintentionally create broken links that require triage and resolution by CMS help desk.

## How to Reproduce

In general, any manual input will re-create the problem, even for valid paths. For instance:

- type a known node path, e.g. `/node/84`:
<img width="526" alt="Screen Shot 2021-05-18 at 7 19 37 AM" src="https://user-images.githubusercontent.com/101649/118658213-69f5bb00-b7a9-11eb-9691-fb9bf82fe48b.png">

- instead of clicking on "Pittsburgh VA Medical center - University Drive", click above the field. The path will appear identical whether you click there, or on the autocompleted text:
<img width="522" alt="Screen Shot 2021-05-18 at 7 21 30 AM" src="https://user-images.githubusercontent.com/101649/118658498-ad502980-b7a9-11eb-8ce0-15039fa7def5.png">

- However, if you view source, you will see the node path stored without metadata:
<img width="384" alt="Screen Shot 2021-05-18 at 7 22 06 AM" src="https://user-images.githubusercontent.com/101649/118658577-c22cbd00-b7a9-11eb-8a91-19ddf92757e2.png">

- When clicking on the autocompleted path, it will look like this instead:
<img width="775" alt="Screen Shot 2021-05-18 at 7 23 01 AM" src="https://user-images.githubusercontent.com/101649/118658726-e2f51280-b7a9-11eb-876d-ba59df66d27a.png">

## Implementation

There are at least 3 potential places where this might be resolved:
- In the widget itself, by not allowing the user to click 'Save' until a known internal path or fully qualified external URL has been entered
- during form validation, by triggering a form error when internal paths without metadata are detected
- as an input filter, by resolving internal paths without requiring the metadata that linkit uses (This would not resolve unknown paths, e.g. `/node/999999999999999`)

We should prioritize a solution that is contributable upstream if possible.

## Acceptance Criteria
- [ ] It is not possible to enter an internal path in the linkit widget without it being rendered to its canonical alias

**Comment by indytechcook** [comment]
If there are multiple items in the list do we default to selecting the first?

**Comment by acrollet** [comment]
> If there are multiple items in the list do we default to selecting the first?

I'd tend to agree but would love to hear from @kevwalsh and/or @rachel-kauff

**Comment by acrollet** [comment]
Discussing this during dev. story time, an ideal solution should not require additional effort from the editor or interruption to their workflow. When 'Save' is clicked in the linkit modal, we should fix the metadata if at all possible. (Hopefully we have this data already available to us in the javascript cache)

**Comment by acrollet** [comment]
Upstream issue: https://www.drupal.org/project/linkit/issues/3222939
