### ISSUE TITLE
Automated static analysis identifies deprecated class methods

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-cms#5377]
## Description

As an engineer, I would like deprecated class methods to be identified by static analysis, so that I can replace them with current methods and avoid introducing failures on system upgrades.

For instance, we recently identified the fact that [File::url](https://api.drupal.org/api/drupal/core%21modules%21file%21src%21Entity%21File.php/function/File%3A%3Aurl/8.7.x) is deprecated, but have received any warnings from our automated code analysis tools.

## Acceptance Criteria
- [ ] Deprecated class methods are identified in static analysis and trigger a github comment and/or test failure

**Comment by ndouglas** [comment]
assign me, i dare you

**Comment by acrollet** [comment]
> @ndouglas  assign me, i dare you

![7087challenge_accepted](https://user-images.githubusercontent.com/101649/118664761-f9519d00-b7ae-11eb-8193-582a13db725f.jpg)

**Comment by acrollet** [comment]
Closing as duplicate of #4919
