### ISSUE TITLE
Send alert when RDS connection limit is reached

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-cms#5405]
## Description

As a devops engineer, I need to know immediately when the RDS connection limit is reached, so that I can take corrective actions.

## Acceptance Criteria
- [ ] A critical alert is sent to Slack when the configured production RDS connection limit is reached

**Comment by ElijahLynn** [comment]
I think this would be best done in Prometheus Alert Manager.

**Comment by indytechcook** [comment]
We should look up the mysql value

**Comment by ElijahLynn** [comment]
We do have an existing implementation of an alert manager usage for EC2 CPU Usage High already we can model off of.

**Comment by TheBoatyMcBoatFace** [comment]
No longer applicable. Reopen if necessary.
