### ISSUE TITLE
Create Grafana chart for "Published Node Count"

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-cms#5407]
## Description

This is a follow-on from #4900 

As a CMS Product Owner, I wish to monitor the published node count over time, so that I may plan infrastructure scaling efforts.

## Acceptance Criteria
- [ ] Grafana chart for "Published Node Count" is created in the CMS Application dashboard is created and shows a graph of published node counts over time

**Comment by mchelen-gov** [comment]
i think this got taken care of in #5416 however it has a bug #5583

**Comment by acrollet** [comment]
Closed in favor of #5583
