### ISSUE TITLE
Rename VAMC content types and rewrite descriptions

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#5411]
## User Story or Problem Statement

VAMC content types are not well named or well-described on the /node/add/ page.  

A new pattern for product-specific content types was designed for Vet Centers, eg "Vet Center - Health Service".

Possible names
```
VAMC Facility
VAMC Facility - Health Service
VAMC System - Homepage
VAMC system - Detail Page
VAMC System - Health Service
VAMC System - Banner Alert with Situation Updates
VAMC System - Operating Status 
VAMC System - Policies 
```

## Acceptance Criteria
- [ ] VAMC Content types and descriptions are written. 
- [ ] #5412 is updated with ACs.

![Add_content___VA_gov_CMS](https://user-images.githubusercontent.com/643678/115807100-f0d79380-a3b5-11eb-8fbd-943b90535bfa.png)

**Comment by Agile6MSkinner** [comment]
This effort was abandoned years ago. Closing.
