### ISSUE TITLE
Prometheus scrapes Drupal for exported data.

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-cms#5416]
This is split out from #4900, #4898, and #4902.  We were hoping to get this done yesterday, but a version incompatibility thwarted us and so this probably needs to be investigated in more depth, deployed locally in Vagrant, etc.  This is not multiple distinct pieces of work, so far as I can tell.

### Acceptance Criteria
- [ ] Prometheus is configured to scrape all configured data from all BRD Drupal environments at a regular interval.

**Comment by acrollet** [comment]
Duplicate of #5432
