### ISSUE TITLE
Create Grafana chart for "Total Node Count".

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-cms#5417]
## Description

This is a follow-on from #4898.  See #5407 and #5416.

As a CMS Product Owner, I wish to monitor the published node count over time, so that I may plan infrastructure scaling efforts.

## Acceptance Criteria
- [ ] Grafana chart for "Total Node Count" is created in the CMS Application dashboard is created and shows a graph of total node counts over time

**Comment by mchelen-gov** [comment]
duplicate of https://github.com/department-of-veterans-affairs/va.gov-cms/issues/5420 & https://github.com/department-of-veterans-affairs/va.gov-cms/issues/5420
