### ISSUE TITLE
Create Grafana chart for "User Count"

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-cms#5418]
## Description

This is a follow-on from #4902.  See #5416.

As a CMS Product Owner, I wish to monitor the user count over time, so that I may plan infrastructure scaling efforts.

## Acceptance Criteria
- [x] Grafana chart for "User Count" is created in the CMS Application dashboard is created and shows a graph with all users ~and active users over time~
- [x] Grafana chart for "Active User Count" is created in the CMS Application dashboard is created and shows a graph with all active users.

**Comment by olivereri** [comment]
Thanks @ndouglas for getting this started in #4904. Added Total users query on top of this per the issue's AC.

**Comment by olivereri** [comment]
@acrollet Thanks for catching that. My change to the board didn't save. User error.

**Comment by acrollet** [comment]
@olivereri I hate to say it but I think it would be better as two separate charts, it's hard to see useful data on the active user count with so many users in the system.

**Comment by acrollet** [comment]
looks great, thanks @olivereri !!!
