### ISSUE TITLE
Create Grafana graph for GraphQL query rate

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-cms#5420]
## Description

As CMS product owners and devops engineers, I need to know the average query rate for GraphQL, in order to determine whether we are meeting our performance commitment.

We will measure this commitment in terms of published nodes served (via GraphQL) per second. See this comment for further background: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/4396#issuecomment-845184356

## Acceptance Criteria
- [x] Graph showing GraphQL query rate in published nodes per second is available on the Grafana CMS Dashboard
- [x] Bonus, if possible: show threshold lines on the graph
   - [x] warning: 0.027 seconds per published node (75% of commitment)
   - [x] danger: 0.036 seconds per published node (100% of commitment)

**Comment by olivereri** [comment]
One minor concern that may cause us the to refactor the way scrape Drupal metrics:  Using Prometheus' EC2 Service Discovery adds an `instance` label to the metrics

**Comment by olivereri** [comment]
Thresholds are in place but won't be visible until seconds per node starts to trend upward:

![image.png](https://images.zenhubusercontent.com/5f04cf8f49978b1615fee8c2/4d6d9a73-22dc-47a7-8c47-32a4d29e805a)

**Comment by acrollet** [comment]
Nice work @olivereri!

@mchelen you can see the graph on the CMS dashboard now, just need to filter to the past hour:

http://grafana.vfs.va.gov/d/dxf8a-6Zz/cms-dashboard?orgId=1&from=now-1h&to=now
