### ISSUE TITLE
Conversation guide for user admin service stakeholder interviews

### ISSUE THREAD

**Issue by rachel-kauff** [department-of-veterans-affairs/va.gov-cms#5423]
AC
- [ ] Moderation guide is ready for first stakeholder interview in Sprint 33.
- [ ] Reviewed w/ @nataliedunbarCS

**Comment by kevwalsh** [comment]
Guide at https://docs.google.com/document/d/1pxIl6Y-eakvv2DU0YYm6ehz_LbAqoTf5vWunTBOFEYQ/edit#, will be moved to github with the research output.
