### ISSUE TITLE
Single Page Build AWS infrastructure creation

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-cms#5428]
## Description

In order to allow publishing single pages to an S3 bucket, we need to create the necessary AWS infrastructure:

- SQS queue
- Placeholder Lambda function

## Acceptance Criteria

- [x] SQS queue created in terraform
- [x] Placeholder Lamba function created in terraform
   - [x] execution is triggered by the SQS queue
   - [x] has write access to the dev.va.gov S3 bucket
- [x] SQS queue name and any other information needed to write to it is documented on #5430 
- [x] Architecture & usage documentation has been created and linked from this issue

**Comment by indytechcook** [comment]
Example Devops PR which adds lambda: https://github.com/department-of-veterans-affairs/devops/pull/9166

**Comment by indytechcook** [comment]
I have an sqs queue hooked up with the lamba job.  When I manually put the message in the sqs queue the lambda fires without any errors!

Next is to setup the sqs queue in terraform along with the connection and permissions to the lambda.

**Comment by indytechcook** [comment]
Initial documentation: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/accelerated_publishing/single_page_publish.md
