### ISSUE TITLE
Write lambda function

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-cms#5429]
## Description

Let's create a Lambda function in the `content-build` repository that is triggered by SQS and calls out to the preview server to retrieve the html for a single node, using the node ID passed into the queue item. It should then write the rendered HTML to the dev.va.gov S3 bucket at the correct path (retrieved from the SQS queue item).

## Acceptance Criteria

- [ ] Rendered HTML functionally matches production
- [x] Rendered HTML is written to the correct path
- [x] Architecture & usage documentation has been created and linked from this issue

**Comment by indytechcook** [comment]
Example Lambda Function PR: https://github.com/department-of-veterans-affairs/content-build/pull/153

**Comment by indytechcook** [comment]
Initial PR on the `content-build` repo: https://github.com/department-of-veterans-affairs/content-build/pull/177

**Comment by indytechcook** [comment]
Looks like the PR build ok and uploaded to S3.  The failure occurred on updating the lambda function.  The error occurs because the lambda function doesn't exist yet. 

#5428 needs to be worked on now before testing can continue on this code.

**Comment by acrollet** [comment]
> Looks like the PR build ok and uploaded to S3. 

nice!!!

> #5428 needs to be worked on now before testing can continue on this code.

marked it as blocked.

**Comment by indytechcook** [comment]
Follow up to fix missing facility banner alerts:  https://github.com/department-of-veterans-affairs/va.gov-cms/issues/5474

**Comment by indytechcook** [comment]
Documentation has started here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/accelerated_publishing/single_page_publish.md

**Comment by indytechcook** [comment]
> Rendered HTML functionally matches production

There is one known issue: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/5474.

**Comment by ndouglas** [comment]
Seeing pages containing only `Please hold while the preview server is starting - 0.00%`

For instance, https://dev.va.gov/resources/va-debt-management/

Clicking "Publish Now" in the CMS will submit an event, which appears to be processed correctly:

<img width="963" alt="Screen Shot 2021-06-02 at 1 52 46 PM" src="https://user-images.githubusercontent.com/1318579/120529015-0aeb9500-c3aa-11eb-9312-98c32b262b19.png">

and the file is indeed uploaded:
<img width="788" alt="Screen Shot 2021-06-02 at 1 55 21 PM" src="https://user-images.githubusercontent.com/1318579/120529185-353d5280-c3aa-11eb-99e8-823cac6db1a1.png">

but the file is _mostly_ empty:
<img width="820" alt="Screen Shot 2021-06-02 at 1 55 53 PM" src="https://user-images.githubusercontent.com/1318579/120529241-4ab27c80-c3aa-11eb-843c-cc1efa3f2616.png">

I'm going to dig into this to see if I can find and fix the issue prior to demo.

**Comment by ndouglas** [comment]
Preview server's just not running on Dev. The preview server shouldn't return an HTTP 200 if it's starting up. This isn't an issue with the lambda per se -- it checks for `response.ok` -- but an issue with the preview server.

**Comment by ndouglas** [comment]
See [this PR](https://github.com/department-of-veterans-affairs/content-build/pull/210) that addresses the status code issue.
