### ISSUE TITLE
Include 501 and 503 responses in re-scan logic

### ISSUE THREAD

**Issue by cmaeng** [department-of-veterans-affairs/va.gov-cms#5442]
**Describe the defect**
The current broken link checker is incorrectly flagging some urls that it shouldn't. During a VAMC Open Hours call, a user brought some specific examples to our attention and mentioned that the extra noise in the UI undermines the faith users have in the broken link alerts.

**To Reproduce**
1. Go to https://prod.cms.va.gov/northern-california-health-care/locations/sacramento-va-medical-center
2. Check the two broken links identified: https://www.bestwestern.com/en_US/book/hotel-search.html and https://www.hyatt.com/en-US/hotel/california/hyatt-place-sacramento-rancho-cordova/saczr

**Expected behavior**
These two specific links would not trigger broken link alerts.

**Screenshots**
![image (4).png](https://images.zenhubusercontent.com/5e3ad9b2c4b3070f908bf89c/5f47d003-2ff6-4246-9427-a4239031fcd8)

**Implementation**
- [x] https://www.drupal.org/project/node_link_report/issues/3215705

**Additional context**
Based on [this](https://dsva.slack.com/archives/CT4GZBM8F/p1621964309351300) slack convo, [this](https://www.drupal.org/project/node_link_report/issues/3215705) may resolve.

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Defect")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS objective (orange) (not needed for bug tickets)
- [ ] CMS-supported product (black)

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Core Application Team`
- [x] `Product Support Team`

**Comment by swirtSJW** [comment]
The upstream issue has been resolved and is part of this release
https://www.drupal.org/project/node_link_report/releases/8.x-1.16

**Comment by swirtSJW** [comment]
The hyatt result was repaired by the rescan logic.   The bestwestern was not, so it was added to the ignore list
