### ISSUE TITLE
Improve VAMC Status Migration Reliability

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-cms#5461]
## Description

The endpoints used for this migration frequently time out, leading to notification noise and lost engineering time investigating the causes for periodic task failures.

## Acceptance Criteria
- [ ] TBD

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [x] `Core Application Team`
- [x] `Product Support Team`

**Comment by swirtSJW** [comment]
Closing this due to https://github.com/department-of-veterans-affairs/va.gov-cms/issues/7260
