### ISSUE TITLE
Retry status migrations when failures occur

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-cms#5464]
## Description

As an engineer supporting the VAMC Status Migration product, I wish for migrations to be retried if they do not succeed the first time, so that I do not receive a notification unless it is truly important.

## Acceptance Criteria
- [ ] TBD

**Comment by acrollet** [comment]
@swirtSJW I'm hoping you can add some background here in terms of our service commitment - have we committed to updating these within any specific timeframe?

I ask because I'm wondering if we can "retry" by keeping track of the last success and only failing the migration if it hasn't run successfully for X {minutes, hours}.

**Comment by swirtSJW** [comment]
Closing this  due to https://github.com/department-of-veterans-affairs/va.gov-cms/issues/7260
