### ISSUE TITLE
Content API Scaling and Performance

### ISSUE THREAD

**Issue by jefflbrauer** [department-of-veterans-affairs/va.gov-cms#5466]
### Background
A decision was made to invest into GraphQL performance and scalability - see background in https://github.com/department-of-veterans-affairs/va.gov-team/issues/20165

The overall goal is to support content build times of less than an hour with 50k published nodes by the end of Q2 2021.

### Problem Statement
Platform teams are aiming to decrease publish times to meet the needs of VFS teams .

The CMS team can contribute to the effort by ensuring that Content API / GraphQL is running on a performant and scalable infrastructure and serve as consultants in the effort to optimize GraphQL queries that currently used in the content build ### pipeline.

### Definition of Done

- The CMS infrastructure that supports GraphQL is stable and performant
- GraphQL multi-query performance and scalability is assessed by by thorough benchmarking based on the expected influx of content
- CMS builds are adjusted to follow hourly content release processes and all related builds are passing successfully
Assumptions
- The CMS's contribution to the total build time is roughly 50%, and can be measured using GraphQL query time as a proxy

### Acceptance Criteria
- [ ] Content build GraphQL requests for 50,000 published nodes are always served in 30 minutes or less

Related
Overall content release time is dependent on ongoing content build scaling work: https://github.com/department-of-veterans-affairs/va.gov-team/issues/22365

**Comment by jkalexander7** [comment]
Closing - GraphQL performance is no longer a bottleneck for content build.
