### ISSUE TITLE
Banner Alert does not show up on Preview

### ISSUE THREAD

**Issue by indytechcook** [department-of-veterans-affairs/va.gov-cms#5474]
## Description

When viewing a preview a banner alert does not show up.  

This can be seen by viewing the diff: http://preview-prod.vfs.va.gov/diff?nodeId=2578.  Preview URL: http://preview-prod.vfs.va.gov/preview?nodeId=2578

## Acceptance Criteria
- [ ] When viewing a node with a facility banner alert, the alert is shown

**Comment by acrollet** [comment]
Closing in favor of #5530
