### ISSUE TITLE
Contact team for teamsite migration endpoint connection failures

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#5477]
## Description
We are seeing a greatly increased number of connection timeout failures when our facility status migration tries to reach many of the 140 teamsite based asp pages that are serving as our CSV data sources.
Our periodic job runs every 15 minutes  (96 times per day) and we are seeing approximately 30 failures per day.

similar to 
```
11:37:31       [error]  Migration failed with source plugin exception: Error message: cURL error 28: Operation timed out after 30000 milliseconds with 0 bytes received (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) at https://www.albuquerque.va.gov/locations/facilities.asp
```

A failure of one prevents running of the others that follow it.

Tasks:
- [x] Follow-up with the three people identified here  https://dsva.slack.com/archives/CT4GZBM8F/p1622129980480700

## Acceptance Criteria
- [x] Teamsite facility data team is aware of the issue and response is documented on this issue.

**Comment by olivereri** [comment]
> Eric,
> 
> I’m currently looking into this issue.  I have a couple of questions.
> 
> 1. Does the site that the error occurs on seem to be random or is it handful of the same sites where the issue always seems to occur (Albuquerque, Madison, etc)?  I’ve been able to successfully view the script results on both of these sites repeatedly this morning but I have seen the prior errors in the server log.

> 2. Do you have an idea of how long you’ve been dealing with this issue?  Has it gotten worse recently?  The locations/facilities.asp script was last modified in April 2020.  I also checked the files that the script interacts with and in the case of the sites mentioned above, those have files have also not been modified for months.
>  
> This morning I noticed that this error was logged on the MADISON at 8:12 am.  I then successfully viewed the MADISON results numerous times between 8:30-9:00 am.  Unfortunately I just noticed that the error was logged again on the MADISON site at 9:12 am.
> 
> As I mentioned previously I’m currently looking into this issue.
> 
> Respectfully,
> John

**Comment by olivereri** [comment]
> Eric,
> 
> I have one additional question.
> 
> 3.  Does there seem to be a time of day that is more likely than another for the error to occur?
> 
> Respectfully,
> 
> John

**Comment by olivereri** [comment]
> Eric,
> 
> I opened a ticket with VA Web Operations concerning this issue.
> 
> I explained to WebOps on the ticket that the locations/facilities.asp page was last updated in April 2020.  The script/page reads two other local files on the website (locations/facilities.xml and emergency/index.asp).  In the case of the most recent error (1:57 pm this afternoon) on the BOISE website, those pages have also not been updated recently (locations/facilities.xml in January 2021 and emergency/index.asp in April 2020).
> 
> I also explained to WebOps that the page typically renders in 1-2 seconds and calls before and after 1:57 pm today to https://www.boise.va.gov/locations/facilities.asp were successful.
> 
> We are aware of prior similar instances on other VA websites where pages would either fail to render before the timeout or would be very slow to respond.  Not sure yet if this is in anyway related.  I’m waiting to hear back from WebOps on this issue.
> 
> Respectfully,
> John

**Comment by olivereri** [comment]
# Draft Response:

**Comment by mchelen-gov** [comment]
monitoring ticket:  #5537

**Comment by olivereri** [comment]
# Response from John to Elijah

> Elijah,
> 
> Thank you for the information.  I added that date to the support ticket we previously opened with WebOps.  I also added comments to the ticket about an email I had received (attached) that made reference to a fix being put in place on 5/13 to address an issue of a network device blocking web traffic.  I know that issue was a few days prior to the 5/17 date you indicated when the issue spiked but I thought the similarity of the issues was worth mentioning on the ticket.
> 
> Also, I joined DSVA Slack should there be a need for us to communicate there.
> 
> Respectfully,
> John

**Comment by olivereri** [comment]
# WebOps Attached Notification E-mail

> Notification
> 
> On May 4, 2021 an outage occurred impacting websites and applications hosted at the CRRC. The root cause to this outage was related to a network device blocking web traffic.
> 
> The Network and Security teams are planning to implement a permanent fix to the issue tomorrow evening, May 13.
> 
> Action for Site/Application Owners
> 
> We are asking all website and application owners to test their websites and/or applications following the planned maintenance (CHG0199021).
> 
> For your convenience a Teams call has been created. Please dial-in at 8PM EST for updates. The Network team will inform website/application owners when to begin testing.
> 
> Please report any issues during your testing directly to the Security and Network teams using the Teams call.  
> To minimize conversations, if your website/application is working as designed there is no need to report a working status. A non-response will be considered OPS-NORMAL for your website/application.
> Additional Support
> 
> Staff from Web Operations will also be on the Teams call to assist and/or restart any web services as requested.

**Comment by mchelen-gov** [comment]
The fix on May 13 was over a month ago, and we are still seeing timeouts as of 6/12 https://dsva.slack.com/archives/CJT90C0UT/p1623515893088900
```
12:38:13       [error]  Migration failed with source plugin exception: Error message: cURL error 28: Operation timed out after 30001 milliseconds with 0 bytes received (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) at https://www.durham.va.gov/locations/facilities.asp. in 
```
Where is an open SNOW ticket for this issue?

**Comment by ElijahLynn** [comment]
> Where is an open SNOW ticket for this issue?

Not sure if it is open but INC18220099 is the one that _was_ open.

**Comment by mchelen-gov** [comment]
Ah yep, that one's open!  https://yourit.va.gov/nav_to.do?uri=%2Fincident.do%3Fsys_id%3D150f79241ba83c9000580d08ec4bcb50%26sysparm_stack%3D%26sysparm_view%3D

Let's keep updating it for a couple days if the errors still occur, then we can close out this ticket and create followup.

**Comment by mchelen-gov** [comment]
still occurring, looks like https://github.com/department-of-veterans-affairs/va.gov-cms/issues/5217 is the followup
