### ISSUE TITLE
sa-contrib-2021-013

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#5493]
## Description

Graph QL needs a security update.
https://www.drupal.org/sa-contrib-2021-013

## Acceptance Criteria
- [ ] Testable_Outcome_X
- [ ] Testable_Outcome_Y
- [ ] Testable_Outcome_Z
- [ ] Requires design review

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [x] `Core Application Team`
- [ ] `Product Support Team`

**Comment by acrollet** [comment]
The linked SA only affects GraphQL `4.x`. We are running version `3.1`:

<img width="841" alt="Screen Shot 2021-06-02 at 1 47 09 PM" src="https://user-images.githubusercontent.com/101649/120543014-0a063380-c3a9-11eb-901f-787bf4f0e6b9.png">

This version is covered by Drupal security updates:

<img width="644" alt="Screen Shot 2021-06-02 at 1 44 48 PM" src="https://user-images.githubusercontent.com/101649/120543159-4043b300-c3a9-11eb-954c-e2eb43c84b06.png">

Closing to no action.
