### ISSUE TITLE
Create Platform Design Doc

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-cms#5504]
## Description

- As a CMS Product Owner, I need to understand the architectural decisions being made for SPP and their justifications, so that I can approve the architectural approach

## Acceptance Criteria

- [x] Create PR to add a design doc in the `platform/engineering/design-docs` directory in the `va.gov-team` repo
- [x] Design doc has been submitted for feedback to FE Tools, Platform Ops, CMS Product Support, Public Websites and the Platform Architecture Review Group

**Comment by acrollet** [comment]
Making a note that our architecture should account for triggering govdelivery notifications when affected content is published.

**Comment by indytechcook** [comment]
Design Doc: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/design-docs/2021-06-11-small-batch-publishing.md

**Comment by mchelen-gov** [comment]
this is https://github.com/department-of-veterans-affairs/va.gov-team/pull/25956 ?
