### ISSUE TITLE
Create architectural diagram

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-cms#5505]
## Description

As a CMS Engineer, I need a clear architectural diagram of the Single-page Publishing solution, so that I have a clear context while making implementation decisions.

As a CMS PO, I need a draft arch diagram of the SPP solution, so that I can review and approve the initiative's technical architecture.

## Acceptance Criteria

- [x] Architectural diagram is created and published to https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/cms/accelerated_publishing/SBP

**Comment by indytechcook** [comment]
Updated V2 with SNS/SQS Pattern: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/accelerated_publishing/SBP/sbpv2.png
