### ISSUE TITLE
Editor Experience

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-cms#5511]
## Background

As a CMS Editor, I need to know what to expect when publishing content, so that I may be informed when content changes will made live.

## Acceptance Criteria

- [ ] Any necessary research has been conducted and synthesized
- [ ] Updated UX guidance, including wireframes and other artifacts have been made available to the core team

**Comment by jefflbrauer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VAgov-CMS-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/5511?planning-poker) with ZenHub @ElijahLynn @indytechcook @ndouglas @olivereri @timcosgrove

**Comment by jefflbrauer** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VAgov-CMS-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/5511?planning-poker) with ZenHub @cweagans

**Comment by jkalexander7** [comment]
This is related to small batch publishing initiative, does not relate to content API.
