### ISSUE TITLE
Make and record policy decision on broken link/accessibility checks

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-cms#5514]
## Background

As a CMS technical architect, I need to know if broken link and/or accessibility checks will be required for publishing actions on single/multiple page builds, so that I may account for any such needs in the SPP architecture.

## Acceptance Criteria
- [ ] Decision made and recorded on this issue

**Comment by acrollet** [comment]
@mchelen-gov I think the main question here is if any broken link/accessibility checking is required in the context of hourly builds. (We might have to revisit if the full site build interval changes)

**Comment by indytechcook** [comment]
💡  We have an hourly lambda job or GH Action which runs the current link checker code

**Comment by indytechcook** [comment]
This information should also be included in #5504

**Comment by jefflbrauer** [comment]
@mchelen-gov Could you please review @indytechcook 's question above and see if we can resolve this issue?

**Comment by jefflbrauer** [comment]
@mchelen-gov can you please weigh in here if this is good to close?

**Comment by acrollet** [comment]
Descoping until we know if we're proceeding with SBP.
