### ISSUE TITLE
Standalone content pages with attached static assets

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-cms#5526]
## Background

Once #5525 is implemented, we'll be able to move to implementing SPP for standalone content types with attached static assets, such as images.

## Acceptance Criteria
- [ ] Content updates to "Step-by-step" nodes are live within 5 minutes of publishing
- [ ] TBD for other node types

**Comment by timcosgrove** [comment]
This is not in line with the current understanding of AP.
