### ISSUE TITLE
Outstations are missing their "Main Vet Center" value, and Section

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#5564]
**Describe the defect**

Clarksville Vet Center was associated with Yuma, but should have been associated with Nashville. This was fixed manually on June 9 on prod, in time for the MVP launch.

The other 17 outstations have "Vet Centers" for their section, and no "Main Vet Center" value, or Yuma AZ. 

See Slack thread

**To Reproduce**
1. Go to https://prod.cms.va.gov/admin/content?title=&type=vet_center_outstation&moderation_state=All&owner=All
2. See that Outstatoins are mostly set to "Vet Centers" Sectoin
3. Edit them and note that their Main Vet Center is either set to Yuma or nothing

**Expected behavior**
Outstations should have their Main Vet Center and Section set to whichever Vet Center "owns" them, from a governance perspective.

**Implementation**

Update migration?
Or manually fix 17 nodes?

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Core Application Team`
- [x] `Product Support Team`

**Comment by netboss** [comment]
@swirtSJW Clicked on each of the 18 "Vet Center - Outstation" nodes to verify and confirm their sections were correctly assigned.
