### ISSUE TITLE
Publishing batch storage

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-cms#5569]
## Description

As a CMS engineer, I need to implement a publishing batch system, so that I may track batch statuses and store relevant metadata and be able to discover the publishing status of a given node.

## Implementation

This will not use the Drupal Batch API in any way.

This will be implemented as a custom revisionable content entity. Refer back to the SBP design doc for latest specs.

## Acceptance Criteria

- [ ] New batch is created when publishing events for enabled node types occur
- [ ] The following metadata is stored on the batch:
   - [ ] creation time
   - [ ] update time
   - [ ] Batch UUID
   - [ ] {nid, vid, path} of triggering node
   - [ ] dependent nodes [{nid, vid, path}]
   - [ ] state 
      - [ ] Queued 
      - [ ] In Progress 
      - [ ] Complete 
      - [ ] Error
   - [ ] Messages
- [ ] Given a node & revision id, it is possible to retrieve related batches, limited by a given status

**Comment by ElijahLynn** [comment]
https://api.drupal.org/api/drupal/core%21includes%21form.inc/group/batch/9.0.x
