### ISSUE TITLE
Event metatag tokens using non-existent field

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#5580]
**Describe the defect**
The metatag module settings for the event content type are using a token that no longer maps to a field on the event content type.  As such the pattern looks broken

Visit /admin/config/search/metatag/node__event
you will see that  "Page title" is using 
`[node:field_office] | [node:title] | Veterans Affairs`
AND 
OPEN Graph:Title is using 
`[node:title] | [node:field_office] | Veterans Affairs`
AND 
TitterCards: Title
`[node:title] | [node:field_office] | Veterans Affairs`

In both cases `field_office` is not a field on the event content type.  This may need to reference `field_administration`

Using the missing field results in data that looks like this 
![image](https://user-images.githubusercontent.com/5752113/121561148-37c12d00-c9e6-11eb-9f42-52c0b0bc70dc.png)

This was surfaced in this ticket but is not fully related to it.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/23082

**AC**
-  [ ] Clarify which field it should be using as a replacement for `field_office`.
-  [ ] Clarify that OG title, tiwtter card title,  and Page title should or should not use the same order of tokens (right now they differ)
-  [ ]  Implement the correct pattern defined by the previous AC's for title, OG:title, and Twitter Cards:title ^^

**Screenshots**

**Desktop (please complete the following information if relevant, or delete):**

**Additional context**
Add any other context about the problem here. Reach out to the Product Managers to determine if it should be escalated as critical (prevents users from accomplishing their work with no known workaround and needs to be addressed within 2 business days).

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Defect")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS objective (orange) (not needed for bug tickets)
- [ ] CMS-supported product (black)

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Core Application Team`
- [x] `Product Support Team`

**Comment by kevwalsh** [comment]
Jay addressed a number of metatag bugs in November in other issues, including this one.
