### ISSUE TITLE
Refactor Prometheus Configuration for Drupal Node Count Metrics

### ISSUE THREAD

**Issue by olivereri** [department-of-veterans-affairs/va.gov-cms#5583]
Follow on for:
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/5420

## Discontinuity of Data in Graph
One concern that may cause us to refactor the way we scrape Drupal metrics:  Using Prometheus' EC2 Service Discovery adds an `instance` label to the metrics with value being the internal IP address of the CMS server. This presents a problem during prod deploys where there is a discontinuity of data but more importantly bifurcates the metric because there are two different `instance` labels. 

Ultimately this messes up the graph, rendering it unreadable, if the panel time window includes a deployment:
![image.png](https://images.zenhubusercontent.com/5f04cf8f49978b1615fee8c2/94ed671c-c117-43d2-bb07-c30717dba37b)

Other problems using Drupal Node Count Metric:

![image.png](https://images.zenhubusercontent.com/5f04cf8f49978b1615fee8c2/798a98aa-85b8-4440-ae5d-b72bb8379301)

## Implementation Details
`
    static_configs:
      - targets:
        - replace-with-cms-elb-dns-name
`
instead of `ec2_sd_configs: ` in Prometheus Utility's configuration file.

## ACs:
- [ ] Grafana should only show a single "Node Count" in dashboard

**Comment by olivereri** [comment]
To test the implementation before merging updated the Prometheus Utility running config with the new target. This time span covers a deployment. Note that there is no discontinuity around 19:30 UTC:

![image.png](https://images.zenhubusercontent.com/5f04cf8f49978b1615fee8c2/99a89186-4bea-4c62-b5e9-fb1b76a1f662)

**Comment by acrollet** [comment]
looking good to me, nice work! Let's leave this open until tomorrow and check one more time before closing this out.
