### ISSUE TITLE
Unlocking when editing an image doesn't unlock

### ISSUE THREAD

**Issue by cmaeng** [department-of-veterans-affairs/va.gov-cms#5596]
**Describe the defect**
When editing an image and going through the unlock process, it takes you back in to editing the image.

**To Reproduce**
1. Go to 'https://prod.cms.va.gov/media/image/4165'
2. Click on 'the unlock button at the bottom of the screen'
3. Click on `Confirm break lock`
4. See that it confirms the lock break but puts you back into the edit screen for the image, which effectively locks it again

**Expected behavior**
Unlocking when editing an image takes you somewhere else, maybe to the media library?

**Screenshots**
![image](https://user-images.githubusercontent.com/60702623/121741880-1850ff80-cacd-11eb-9ed0-546d0b3b25c1.png)

**Desktop (please complete the following information if relevant, or delete):**

**Additional context**
Add any other context about the problem here. Reach out to the Product Managers to determine if it should be escalated as critical (prevents users from accomplishing their work with no known workaround and needs to be addressed within 2 business days).

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Defect")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS objective (orange) (not needed for bug tickets)
- [ ] CMS-supported product (black)

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Platform CMS Team`
- [x] `Sitewide CMS Team`
  - [x] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Offices`
  - [ ] `⭐️ Product support`
  - [ ] `⭐️ User support`

**Comment by jefflbrauer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VAgov-CMS-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/5596?planning-poker) with ZenHub @ElijahLynn @indytechcook @ndouglas @olivereri @timcosgrove

**Comment by jefflbrauer** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VAgov-CMS-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/5596?planning-poker) with ZenHub @cweagans

**Comment by acrollet** [comment]
@kevwalsh we took a look at this but believe it's more in content ops' perview.

**Comment by EWashb** [comment]
This defect is still happening

**Comment by ndouglas** [comment]
Sure, I can take this on.

**Comment by ndouglas** [comment]
https://github.com/department-of-veterans-affairs/va.gov-cms/pull/10651
