### ISSUE TITLE
S3 path field on media entity

### ISSUE THREAD

**Issue by indytechcook** [department-of-veterans-affairs/va.gov-cms#5600]
## Description

A new field called `field_file_s3_path` will be added to the media entity so that the s3 path can be stored.  

## Acceptance Criteria
- [ ] When a new file entity is created or updated, the s3 file path is updated to `<file_name>-<revision_id>.<file_ext>`
- [ ] The `field_file_s3_path` field only contains the key to the s3 path and not the base path.
- [ ] The base path to the file is stored in a setting.
- [ ] When a the field `field_file_s3_path` is included in a GraphQL request, the full s3 path is output.
- [ ] Audit entities to make sure file entities are only attached to media entities.  Log follow up issues for any for entities which are directly linked to files.

## Technical Notes
* A custom GraphQL field plugin can be used to change the output of the field. Ideally, a custom field would be added also so GraphQL can target the field directly instead of targeting the name of the field.
* A new field will be added to the file entity content type. The new field will be the name of the key on s3 where the file is stored. There will be a Drupal setting that has the base path. The graphql field will prefix the s3 base to the value on request.
* A file will be uploaded to s3 from Drupal on the file entity creation and update. Careful attention needs to be made to make sure this is the last hook/event which runs to allow for other module's file processing to occur. All derivatives of files also need to be updated.
* The name of the files on s3 will contain the revision id. This will create uniqueness for each version for content and make sure file updates on s3 do not override live files. See Drupal\graphql_core\Plugin\GraphQL\Fields\Entity\Fields\Image\ImageDerivative::resolveValues for examples of using image derivatives.
* Tugboat/CI should use a shared s3 bucket with a prefix on the key.  The base path setting for tugboat needs to include as an env variable in the `.env` file.
* Local .env should be updated also.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [x] `Core Application Team`
- [ ] `Product Support Team`

**Comment by indytechcook** [comment]
Changed points to 8 to account for tugboat changes.

**Comment by indytechcook** [comment]
Most field usages are found with media entity references

![image](https://user-images.githubusercontent.com/121603/153056275-bce5cd71-721b-4192-8b22-0dbd9bfb85f1.png)

**Comment by timcosgrove** [comment]
Right. For the purposes of "Audit entities to make sure file entities are only attached to media entities. Log follow up issues for any for entities which are directly linked to files." we care about target_type: file, no?

<img width="774" alt="image" src="https://user-images.githubusercontent.com/203623/153057511-fecb0080-07e4-40b5-b211-67eb7564d9df.png">

**Comment by timcosgrove** [comment]
This ticket is replaced by the following three issues:
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9803
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9804
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9805
