### ISSUE TITLE
Drupal Media Assets uploaded to S3

### ISSUE THREAD

**Issue by indytechcook** [department-of-veterans-affairs/va.gov-cms#5601]
## Description

Drupal assets should be stored on s3 so that va.gov can directly access the files instead of the files being part of the content-build.

S3 will not replace the file storage Drupal.  Drupal will continue to use local file storage (eventually EFS) as the public/private schema.   

## Acceptance Criteria
- [ ] When a file entity is updated or created, the file will be uploaded to s3
  - [ ] All image styles and other publicly accessible derivatives are also uploaded
- [ ] The file name on s3 will contain the revision id
- [ ] Initial state of current published entities and files referenced are pushed to s3 (possibly via a VBO)
- [ ] A button exists on the entity pages which will push related files to s3

**Comment by ElijahLynn** [comment]
I sized as an 8 because there will be some devops IAM and S3 stuff to do as well.

**Comment by timcosgrove** [comment]
> A button exists on the entity pages which will push related files to s3

@indytechcook Why is this necessary? wouldn't any files be pushed to s3 upon creation or update of their associated media entity?

**Comment by timcosgrove** [comment]
This ticket is superseded by https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9810
