### ISSUE TITLE
Front end template are updated to use s3 field

### ISSUE THREAD

**Issue by indytechcook** [department-of-veterans-affairs/va.gov-cms#5602]
## Description

The HTML on va.gov should use the files published by Drupal to s3 instead of downloading the files during the build.  The GraphQL query also needs to include the new field created in #5600 

## Acceptance Criteria
- [ ] The front-end template uses the new s3 field at the path instead of the file path.
- [ ] Images show correctly on front end build.
- [ ] The content-build should not pull down Drupal assets
- [ ] Images work in local builds
- [ ] Images work in preview server

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [x] `Core Application Team`
- [ ] `Product Support Team`

**Comment by indytechcook** [comment]
Set points to 8 due to the front end build risk.

**Comment by acrollet** [comment]
Iceboxed, we probably won't take this on ourselves.

**Comment by timcosgrove** [comment]
I question the sizing on this, but much of the conversion work will probably be on other teams.

**Comment by timcosgrove** [comment]
With the work done in #9810, this should no longer be necessary.
