### ISSUE TITLE
Drupal File Paths in fields should reflect s3 bucket in GraphQL

### ISSUE THREAD

**Issue by indytechcook** [department-of-veterans-affairs/va.gov-cms#5633]
## Description

In the response of a GraphQL call, any reference to Drupal file should reference the S3 version instead of the Drupal version so that the content build does not need to make URL transformations.

## Acceptance Criteria
- [ ] Textual based fields including URL, Text and WYSIWYG must link to the version of the Drupal asset on S3.

**Comment by timcosgrove** [comment]
With the work in https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9810 this should no longer be necessary. The URL output for a given media asset should always point to its publicly available location on S3.
