### ISSUE TITLE
AP Discovery Readout for OCTODE

### ISSUE THREAD

**Issue by mchelen-gov** [department-of-veterans-affairs/va.gov-cms#5639]
As the CMS team PO, I would like the CMS team to present a high level readout for OCTODE summarizing the content publishing problem space, current situation, options to consider, and proposed next steps so that OCTO-DE leadership can make informed decisions about team structure, funding, and architecture for content publishing.

OCTO-DE Stakeholders:
- Rachael
- Dror
- Mike P
- Mike C
- Jen Lee
- Dave Conlon
- John Hashimoto
- Jeff Barnes
- Chris Johnston
- Charles Worthington

*Implementation Details*
- Put github summary of findings into a slidedeck
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/accelerated_publishing/findings_recommendations.md

- Add diagrams
- Be sure to add in UX findings and recommendations

**Comment by jefflbrauer** [comment]
@acrollet @indytechcook @mchelen-gov I have started a draft of the roadshow deck here.  Please review and add anything missing. Mike lemme know if this format overall is looking like you expect or if you need any changes. Also does this represent the level of detail you were hoping to include?

https://docs.google.com/presentation/d/1Kdw5bRYlPmNe0CBu4wR6ZoKIYF-gSmD36KO4x9RDr3A/edit#slide=id.gcd567e2ae4_0_432
