### ISSUE TITLE
Org. Chart

### ISSUE THREAD

**Issue by joshworkscivicactions** [department-of-veterans-affairs/va.gov-cms#5654]
Help Desk is completing an org chart that will include Platform Crew, Sitewide Crew, Core Application, Health Tools Crew, Benefits Tools Crew, Account Experience Crew, and Lighthouse API Teams in order increase the timeliness of information and better triage issues 
with improved communication with stakeholders.

**Comment by joshworkscivicactions** [comment]
Updated Vanessa's Org Chart doc here https://docs.google.com/spreadsheets/d/1HDHl-tisVE5Ah72c5Y0W0ANa66O6H3fiKCC4P5qItcw/edit?usp=sharing

This will be an ongoing process to update.  

*The hierarchical excel file can be imported into X-Mind.

**Comment by joshworkscivicactions** [comment]
Updated org chart, yet again. Disregard previous version. 
 This version focuses more appropriately to the products the helpdesk will directly work with https://docs.google.com/spreadsheets/d/1IUOU5xf2wZvZteCFj-WHgQS2qLoIM1WfSugA-DHecXQ/edit?usp=sharing

**Comment by cmaeng** [comment]
closing to no action
