### ISSUE TITLE
Content Build Ownership & Transfer of Ownership Documentation

### ISSUE THREAD

**Issue by jefflbrauer** [department-of-veterans-affairs/va.gov-cms#5658]
As a member of OCTO-DE I have clarity as to the full content build and small batch content build pipeline architectures, and who owns which components of each so that triage is easier and teams know what parts they need to maintain. 

AC:
- [x] Full and small batch content build pipelines are documented, including ownership notations

(following ACs struck 7/1/21, see: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/5658#issuecomment-872421813)
~~A process is established and documented for transfer of ownership from one team to the other as content types transition between pipelines~~
~~All involved Platform Crew teams and OCTO-DE are aligned on the solution~~

**Comment by indytechcook** [comment]
Ownership Diagram: https://app.mural.co/t/vagov6717/m/vagov6717/1624971030253/f629c0678f9fb44ade15574707e8be4995c1fbed

**Comment by indytechcook** [comment]
I'm giving teams a day to review then I'll put this in va.gov-team

**Comment by indytechcook** [comment]
Content Build Ownership: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/accelerated_publishing/Content-Build-Ownership.png

Preview Ownership: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/accelerated_publishing/preview_ownership.png

**Comment by mchelen-gov** [comment]
RFC: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/request-for-comment/2021-07-01-content-release-ownership.md

**Comment by mchelen-gov** [comment]
the AC for this ticket should be limited to what CMS team can control, which is to create and circulate doc. if there's other decision points or followup needed from OCTODE or other teams lets spin that off

@indytechcook what places have you shared this out so far, such as Team of Teams?

**Comment by acrollet** [comment]
The doc was previously shared in #content-release-engineering, I've just shared it in #platform-team
