### ISSUE TITLE
Define & Document CMS security incident response and dependency security patching protocols 

### ISSUE THREAD

**Issue by ElijahLynn** [department-of-veterans-affairs/va.gov-cms#5659]
Per OKR: 
> CMS team has defined security incident and dependency security patching response protocols & SLAs, approved by OCTO-DE.

AC: 
- [ ] Security incident response protocol is defined and documented
- [ ] Dependency security patching response protocol is defined and documented

**Comment by cmaeng** [comment]
transition this effort to be a regular quarterly check on security protocols

**Comment by TheBoatyMcBoatFace** [comment]
No longer applicable in current roadmap/bandwidth - handled by Drupal packages. Reopen if needed.
