### ISSUE TITLE
Image thumbnail ratio mismatch

### ISSUE THREAD

**Issue by joshworkscivicactions** [department-of-veterans-affairs/va.gov-cms#5660]
When a user uploads an image to a Story, the homepage that hosts a thumbnail of that image is not the same aspect ratio which results in unexpected cropping. 

The page the original is uploaded to (top header image) https://www.va.gov/eastern-colorado-health-care/stories/new-telerehab-program-empowers-veterans-at-home/

The homepage for which the aspect ratio is different:  https://www.va.gov/eastern-colorado-health-care/

Original appears to be 480x240 
Thumbnail 480x320

**Comment by kevwalsh** [comment]
@joshworkscivicactions can you link back to the Help desk ticket where this originates?

**Comment by joshworkscivicactions** [comment]
https://va-gov.atlassian.net/jira/servicedesk/projects/VAHELP/queues/custom/20/VAHELP-1033

**Comment by xiongjaneg** [comment]
not applicable to current image ratio process
