### ISSUE TITLE
Update URL alias pattern for Leadership to include /about-us/ 

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#5669]
ACs
- [ ] Pathauto set to use same token as Detail Page 
- [ ] Rename VAMC Detail page token to "Menu item based"

Consider going broader and applying this to all VAMC content types that have menu_force enabled.

**Comment by ethanteague** [comment]
@kevwalsh I'm gonna limit this task to _just_ leadership_listing type. The reason for this is b/c it's a bit more involved than I originally thought, e.g.: need to update an array of allowed types in va_gov_backend.module, and add an update hook for each content type to allow auto aliasing for each piece of content.
