### ISSUE TITLE
Generate breadcrumbs for nodes that have no menu items (Drupal as source of truth for all breadcrumbs)

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#5677]
## Background

Currently, Drupal is the source of truth for breadcrumbs for Drupal-managed pages that have menu items.

But not all Drupal-managed pages have menu items, and breadcrumbs for those are generated on the FE, often with hyphenation and casing issues (see https://github.com/department-of-veterans-affairs/va.gov-team/issues/17521)

Content types that do not have menu-based breadcrumbs

- Events (VAMCs, Outreach Hub, and beyond)
- Stories (VAMCs, future products)
- News Releases (VAMCs, future products)
- Staff profiles, sometimes (VAMCs, future products)

May have menu items in the future (will need discussion)
- Vet Centers (Vet Centers)
- Vet Center Location Lists (Vet Centers)
- ... possibly others, needs a bit more analsys

We also currently do not _enforce_ menu items on all other content types, but we probalby should be (see department-of-veterans-affairs/va.gov-team#5488). 

## Questions

How might we make Drupal the source of truth for breadcrumbs? 

What breadcrumb variants need to be supported by content type and by product, now and (to some extent) in the future? 

What layer should control the Home link? 
- Benefits Hubs pages (and the "default") is to show **Home >**
- VAMC pages don't show Home, because they 
- Vet Centers show "[VA.gov home](http://www.va.gov/) >"

## Considerations/Notes
- 5/19/22: Design System Team is continuing work on the breadcrumb component, worth looking at. Per Mikki N: "Hi!  I'm not sure which team is responsible for the front end work on facilities sites, so please let me know if there is someone else we should reach out to.  [@Randi Hecht](https://dsva.slack.com/team/U03CGHK4JU9) noticed that the breadcrumbs on the Vet Center sites are not using proper casing.  The breadcrumb segments should match the H1s exactly, that includes how it's cased.  Who can look at this for us?  https://www.va.gov/new-bedford-vet-center/locations/"
  - per Kev, "we should talk about breadcrumb architecture at some point. The current state is that it’s woefully incomplete, and certain content types in the CMS have bad or hacky breadcrumbs on the FE. My sense is that his would be a PW FE problem. The Drupal side could go to SWCMS but could possibly happen within PW."

**Comment by wesrowe** [comment]
Mikki N raised this in a slack thread on 5/19. Adding to main Epic details.

**Comment by kevwalsh** [comment]
this would solve for

https://github.com/department-of-veterans-affairs/va.gov-team/issues/13571
https://github.com/department-of-veterans-affairs/va.gov-team/issues/10030

**Comment by wesrowe** [comment]
@kevwalsh I have a note that Sitewide CMS team is taking this on. I'm not sure what their label is.

**Comment by jilladams** [comment]
@timcosgrove @tjheffner I think it's true that AP's recent breadcrumb work resolved this issue conceptually, yes? (Based on the [Oct slack thread](https://dsva.slack.com/archives/C03LFSPGV16/p1698687904869589) about how crumbs are built.)

**Comment by tjheffner** [comment]
@jilladams I believe so
