### ISSUE TITLE
JIRA help desk label iterations

### ISSUE THREAD

**Issue by joshworkscivicactions** [department-of-veterans-affairs/va.gov-cms#5684]
## Description
The JIRA help desk needs better labeling to drive more meaningful reports.   

- [x] generate reports using current labeling data
- [x] generate reports using new labeling data
- [x] compare old and new labeling reports 

## Acceptance Criteria
- [x] new labeling report provides more meaningful reporting than the old
- [ ] all labels within previous two month period have been updated

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [] `Core Application Team`
- [x] `Product Support Team`

**Comment by joshworkscivicactions** [comment]
Added new components.   

More than one component can be selected.   Assumption is that more granular data can provide more meaningful reports.

A CMS user's Section can now be selected as a component; more than one component can be assigned to any ticket.

**Comment by chriscraiga6** [comment]
Meeting on 12/10 to finalize the labels then the report can be generated.

**Comment by stefaniefgray** [comment]
Marking as Closed since @chriscraiga6 and I co-worked on standardizing labels and components; creating new ticket for next steps, will link
