### ISSUE TITLE
Remove endpoint for Lebanon and Eastern Oklahoma VAMCs going live July 7

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#5696]
## Acceptance Criteria
- [ ] Operating status migration stops on July 6 for 2 VAMCs
- [ ] Create a PR similar to #5628 **for each** of the following, and merge after the prod deploy on July 5. Could be merged EOD July 1st too since the there will be no deploy July 5th. 
  - [ ] Erie health care
  - [x] Lebanon
  - [x] Eastern Oklahoma

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Core Application Team`
- [x] `Product Support Team`

**Comment by ethanteague** [comment]
@kevwalsh the only Oklahoma endpoint we have remaining is https://www.oklahoma.va.gov/locations/facilities.asp (Oklahoma City). We aren't deleting this from the file(s), are we?
