### ISSUE TITLE
Write guidance for PAOs placing detail pages

### ISSUE THREAD

**Issue by cmaeng** [department-of-veterans-affairs/va.gov-cms#5700]
## Description
Between not and when #4988 gets merged (likely in sprint 36), guidance for VAMC editors to fix detail pages will be helpful to add to any canned response. The current messaging is to only choose Programs and Research but we're seeing users go rogue and place elsewhere.

## Acceptance Criteria
- [ ] A page is added to the CMS Help Center with guidance on how to handle detail pages
- [ ] once #4988 is merged that page is removed

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Core Application Team`
- [x] `Product Support Team`

**Comment by kevwalsh** [comment]
This is moot, and documentation is covered in https://prod.cms.va.gov/help/va-medical-centers-vamcs/how-to-manage-vamc-menus
