### ISSUE TITLE
Identify opportunities for linking to Help Center from the editorial experience

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#5715]

**Comment by rachel-kauff** [comment]
Initial models and iterations in this design file: https://www.figma.com/file/PySxm5aQeWCQvYqZpdkYJj/Linking-from-the-editorial-experience?node-id=0%3A1

Next steps: Another discussion w/ Dave so we can prioritize what part of this to implement

**Comment by cmaeng** [comment]
@rachel-kauff i'm shifting this milestone from sprint 38 to 39. if you'd like to reframe this a bit to capture the work you did in 38 that's totally cool, we'd just have to spin up something for 39 that describes the broadened scope. thanks.

**Comment by kevwalsh** [comment]
This was done in sprint 38. Closing.
