### ISSUE TITLE
Perform performance analysis of VAMC menu block on proofing pages

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-cms#5734]
## Description

As a core team engineer, I need to analyze the performance of #5468, so that any required performance improvements may be identified before the code is deployed.

## Acceptance Criteria
- [ ] PR has been reviewed for performance using a blackfire diff
- [ ] Any required modifications have been added as ACs to #5468

**Comment by indytechcook** [comment]
Testing process:

1. Visit page.
2. Clear cache via drush
3. Run profiler in browser 

Pages testing on:

VAMC Facility:
* http://va-gov-cms.lndo.site/pittsburgh-health-care/locations/pittsburgh-va-medical-center-university-drive
* http://va-gov-cms.lndo.site/miami-health-care/locations/key-west-va-clinic
* http://va-gov-cms.lndo.site/houston-health-care/locations/tomball-va-clinic

**Comment by indytechcook** [comment]
@ethanteague I'm unable to find events that have a sidebar menu.  Do you have any examples?

**Comment by indytechcook** [comment]
I spent time reviewing the new call graphs compares to the current call graphs.  In all the cases, the response time was faster in the new code!  Great job @ethanteague !

**Comment by ethanteague** [comment]
> @ethanteague I'm unable to find events that have a sidebar menu. Do you have any examples?



> @ethanteague I'm unable to find events that have a sidebar menu. Do you have any examples?

That's a bug! I'll take a look and let you know what I find. Thanks, @indytechcook !
