### ISSUE TITLE
Update LGBTQ audience tag to LGBTQ+ per new VA policy

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-cms#5736]
## On the `Beneficiary` audience tag labels in Resources and Support

**Not urgent - for triaging as time permits.** 

Please update the `LGBTQ Veterans` audience label in the CMS to `LGBTQ+ Veterans`. This is a VA wide change per this announcement from the Secretary of VA: https://www.va.gov/opa/speeches/2021/06_19_2021.asp

>Additionally, we are changing the name of VHA’s LGBT health program to the LGBTQ`+ `Health Program, language that proudly reflects new community standards of inclusiveness and anticipates future changes in terms.  

**AC:** 
- [x] On RS tags, LGBTQ Veterans audience tag label is changed to `LGBTQ+ Veterans `

![image.png](https://images.zenhubusercontent.com/5bb2975c143b4d2ee7a35ef6/b412fbd2-4ad9-41ae-af52-69a5f52841b0)

FYSA @bethpottsVADEPO @DanielleThierryUSDSVA

**Comment by kevwalsh** [comment]
@jenniferlee-dsva 

Hi Jen, i went ahead and made this edit. 

As a content admin, you are able to make edits like this at https://prod.cms.va.gov/admin/structure/taxonomy/manage/audience_beneficiaries/overview 

At some point the governance of the audience taxonomy (and of the R&S product more generally) should be documented, but it's ad hoc right now. /cc @johnhashva
