### ISSUE TITLE
Verify FE build GraphQL output

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-cms#5738]
## Description

As a FE engineer, I want the processed GraphQL query output to be verified against known good output, so that I can be confident that changes to GraphQL queries do not negatively affect the build.

## Background

We wish to ensure that pages.json output remains good when changes are made to the GraphQL queries.

## Acceptance Criteria
- [ ] GraphQL output on PRs is verified against GraphQL output from the master branch

**Comment by timcosgrove** [comment]
This task was written when there was a different assumption about how AP would proceed.
