### ISSUE TITLE
Operating status: improvements to editorial experience

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-cms#5747]
## Problem(s) to be solved

~@mmiddaugh will clarify these rules for when Facility Status - Additional Info field is required, optional, or disabled/hidden, and if this applies to all Facility content types~ _see Logic decisions below_

- Vet Centers use a new expandable alert to display facility operating status and details. It is designed to expand to show details for `Facility Notice` and `Limited Services and hours`. 
- If the status is `Facility Notice` or `Limited Services and hours` Veterans need additional details to understand what has changed or to prepare for their visit. However, the details field is not required.  
- If the status = `Normal`, no status is displayed on the front end. If details have been entered, they will not be made available to Veterans.  **Disabled or hidden and cleared of content if already had content**
~- If the status = `Closed`, ~the alert does not expand. If details have been entered, they will not be made available to Veterans. Editors may not realize the information has not been communicated.~  Needs clarification~ _See comment below_
- When changing from one status to another, text in the detail field remains unless it is manually removed, causing the potential for confusion. **Needs some UX**

## Screenshots

<details>
<summary> Example from preview of Colorado Springs </summary>

![image.png](https://images.zenhubusercontent.com/5d8a47393ac3440001d1a2ed/3b90a270-dd45-4304-8ce5-e18b1b883ce5)

</details>

## Logic decisions
As of 7/2: 
- details are optional for `Limited services and hours` and `Closed ` (but strongly encouraged by business process)
- details are required for `Facility Notice`
- details cannot be added for `Normal` 
- Logic is consistent across products

**Comment by mmiddaugh** [comment]
@kevwalsh I confirmed with @brangi - for any operating status (except `Normal`, which does not display)  - if details are present, the alert will expand

**Comment by kevwalsh** [comment]
This was solved by #6319, closing as a duplicate
