### ISSUE TITLE
Add "deldot.gov" to ignore list / allow list in broken link check

### ISSUE THREAD

**Issue by cmaeng** [department-of-veterans-affairs/va.gov-cms#5748]
## Description
Need to whitelist a government url: `deldot.gov`. There's currently one on https://prod.cms.va.gov/wilmington-health-care/operating-status

Context **[here](https://dsva.slack.com/archives/CDHBKAL9W/p1625082387248000)**.

## Acceptance Criteria
- [ ] The CMS broken link notification at the top of each node doesn't flag for links to deldot.gov

![image (10).png](https://images.zenhubusercontent.com/5e3ad9b2c4b3070f908bf89c/3e889090-368d-410f-9748-89d9a0b8cc5b)

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [x] `Core Application Team`
- [x] `Product Support Team`

**Comment by kevwalsh** [comment]
Added to prod Dec 20 2021
