### ISSUE TITLE
Investigate adding external participants to a JIRA ticket

### ISSUE THREAD

**Issue by joshworkscivicactions** [department-of-veterans-affairs/va.gov-cms#5770]
## Description
As Help Desk Manager I need to understand the limitations of adding a participant to a ticket.

[ ] Create a new customer in JIRA
[ ] Create a test ticket
[ ] Add content to the ticket
[ ] continue planning...

...[ ] follow up with Ethan and complete the picture for him as it relates to Jim's ticket #1105.

## Acceptance Criteria
- [ ] Help Desk is aware of what content within a ticket a participant is privy to at each step/status of a  ticket

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [] `Core Application Team`
- [x] `Product Support Team`

**Comment by cmaeng** [comment]
I think this issue can be closed.
