### ISSUE TITLE
Update Blackfire to V2 on Lando

### ISSUE THREAD

**Issue by indytechcook** [department-of-veterans-affairs/va.gov-cms#5782]
## Description

Blackfire V1 is being deprecated on Sept, 1st 2022.   Lando currently uses V1 and needs to be upgraded to V2.  In the process of the upgrade, we will need to switch to using the separate lando service to use blackfire instead of installing it on the PHP service.

Links:
* https://blackfire.io/docs/up-and-running/agent-upgrade
* https://blackfire.io/docs/up-and-running/configuration/agent
* https://blackfire.io/docs/up-and-running/docker
* https://github.com/lando/lando/issues/2125#issuecomment-613485293

## Acceptance Criteria
- [ ] Blackfire works on lando

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [x] `Core Application Team`
- [ ] `Product Support Team`
- [ ]

**Comment by ElijahLynn** [comment]
We are using ddev now, not sure if this is still applicable.

**Comment by cweagans** [comment]
It is not. Blackfire support is built into ddev.
