### ISSUE TITLE
Improve friendliness of Behat text pattern matching when verifying a node has been saved.

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-cms#5789]
## Description

In [this commit](https://github.com/department-of-veterans-affairs/va.gov-cms/pull/5667/files/3acd8f939ea6400e0909ea187970d8e7c514d66e#diff-2714ecd674bdfee764400ef64a3078e7b774295867d36f878545c25c2362b350), I had to make a rather hideous change in order to get the test to pass.

Due to a change either in Behat or in Drupal, the text extracted from the status message ceased to be `Benefits detail page VA blind and low vision rehabilitation services - EDITED has been updated.` and became something along the lines of `Benefits detail page <a href="/node/42">VA blind and low vision rehabilitation services - EDITED</a> has been updated.`, but encoded in some awful way.

It might be preferable to add a step definition to verify that a node has been updated, and encapsulate therein some logic for dealing with this nastiness -- whether by checking the status message with a regular expression, or using some programmatic method that doesn't rely on text matching at all.

Or this and similar tests might be replaced with Cypress tests, should those work better.

## Acceptance Criteria

- [ ] Behavioral tests no longer require ugly encoded strings to verify that a node has been successfully updated.

**Comment by acrollet** [comment]
team discussed using cypress as the best option here.

**Comment by ndouglas** [comment]
This is no longer necessary, since these tests are in Cypress now.
