### ISSUE TITLE
New Users on SSOi Lower Env not able to login 

### ISSUE THREAD

**Issue by ElijahLynn** [department-of-veterans-affairs/va.gov-cms#5792]
> I tried on staging and got this, but it could be because I'm not ~white~ allow listed?

yes, you need to be added to the allow list, per instructions in https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/platform/cms/cms-sso-saml-iam-login-braindump.md#testing-tools, however, Adrian did that, was added and still cannot log in, which is the same issue we had last time trying to add Howie and I eventually gave up spending cycles on it as we didn't get anywhere. 

We need to open a ticket as per https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/platform/cms/cms-sso-saml-iam-login-braindump.md#for-issues-in-your-lower-environments-dev-idev-sqa-preprod.

_Originally posted by @ElijahLynn in https://github.com/department-of-veterans-affairs/va.gov-cms/issues/5753#issuecomment-875849865_

**Comment by acrollet** [comment]
Closing in favor of individual issues #5834 #5835 #5836
