### ISSUE TITLE
Implement Application Performance Monitoring

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-cms#5796]
### User Story or Problem Statement

As a CMS engineer, I need access to performance monitoring traces, so that I can have enough information to resolve any performance issues or other bugs occurring on the production environment.

### Affected users and stakeholders

* CMS Engineers

### Hypothesis

We believe that implementing [Datadog APM](https://www.datadoghq.com/product/apm/) / Blackfire APM (https://www.blackfire.io/monitoring) will provide sufficient information to identify the root causes of performance issues on production. We'll know that to be true when a future performance-related issue is resolved using data obtained from the selected tool, without having to provide artificial load on a testing environment. 

### Assumptions
* Sufficient datadog licenses are available for our infrastructure
* We do not wish to wait to implement [Blackfire APM]

(How will these assumptions be validated?)

## Acceptance Criteria
- [ ] The VA Datadog/Blackfire instance is receiving data from the CMS production instance
- [ ] Documentation on how to access the APM tool is available in the CMS docs

**Comment by indytechcook** [comment]
https://app.datadoghq.com/apm/docs?architecture=host-based&framework=apache&language=php

**Comment by jkalexander7** [comment]
New epic will be created if Platform CMS decides to use Blackfire's APM in the future.

**Comment by cweagans** [comment]
I think this one is still valid. We don't have the Datadog APM in place yet.
