### ISSUE TITLE
Update "CMS user guide" and "Help Center" references in codebase and content to use Knowledge Base

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#5805]
ACs
- [ ]  Uses of "user guides" or "help center" have been replaced with "knowledge base" or "kb", where reasonable

It's unclear if we should refactor the entire vagov_help_center module.... maybe?

**Comment by ethanteague** [comment]
@swirtSJW - wondering if you wouldn't mind weighing in.
