### ISSUE TITLE
Track Knowledge Base discoverability

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#5812]

**Comment by jefflbrauer** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VAgov-CMS-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/5812?planning-poker) with ZenHub @cweagans

**Comment by EWashb** [comment]
This doesn't seem like an issue currently.
