### ISSUE TITLE
Draft Knowledge Base content strategy principles

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#5815]
AC
- [x] Shared with Dave. conversation to validate

**Comment by rachel-kauff** [comment]
Principles artifact: https://www.figma.com/file/1onlBLkUw53ZA3zE4aa0v5/Knowledge-base-content-strategy-principles?node-id=0%3A1

**Comment by rachel-kauff** [comment]
Iterated on principles, will present at demo

**Comment by rachel-kauff** [comment]
Done!
