### ISSUE TITLE
Helpdesk manager should understand which product team has ownership of an issue

### ISSUE THREAD

**Issue by joshworkscivicactions** [department-of-veterans-affairs/va.gov-cms#5860]
## Description
As a helpdesk manager I need to be able to triage whether an issue is owned by a product team
## Acceptance Criteria

Can define ownership of:
- [x] Facilities
- [x] Front-end 
- [x] VAMC system
- [x] CMS 
- [x] more to come..

Master one before understanding the next.  
Begin to document process

This will likely be an ongoing process that ultimately Tier 2 may retain ownership of, but discovering if helpdesk can reduce the demand on tier2/3 once more editors on board is important.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [x] `Core Application Team`
- [x] `Product Support Team`

**Comment by chriscraiga6** [comment]
Awaiting to find out the end result for Facilities ownership. Should learn more on April 18th.

**Comment by stefaniefgray** [comment]
Closing now that we know Randi Hecht is owning Vet Center content
