### ISSUE TITLE
Update to correct tooltip text for Vet Centers national content fields

### ISSUE THREAD

**Issue by rachel-kauff** [department-of-veterans-affairs/va.gov-cms#5865]
Tooltip text for two of the national content fields on the Vet Centers form is incorrect, prob left over from the design pattern we developed for the VAMC policies top task page.

ACs
Update tooltips on the following field groups to match [the prototype](https://www.figma.com/file/885DMraAi9V2DLJnrIN7Wv/Vet-Centers?node-id=364%3A222).
- [ ] A. Featured content
- [ ] B. How we're different from a clinic

A. Featured content
Wrong:
![Screen Shot 2021-07-14 at 3.25.32 PM.png](https://images.zenhubusercontent.com/5e399cf5446c5b4ca0e31e42/b29441c2-2acd-49ff-9b4e-a9b7988e4c6a)

Right:

> **Why can’t I edit this?**
> This national feature managed by VHA will display alongside locally-relevant content.

B. How we're different
Wrong:
![Screen Shot 2021-07-14 at 3.32.31 PM.png](https://images.zenhubusercontent.com/5e399cf5446c5b4ca0e31e42/1162461e-2d7a-4cd2-b078-596ef8580301)

Right:

> **Why can’t I edit this?**
> VHA keeps this content standardized to provide consistent messaging for Vet Center sites nationwide.

**Comment by ethanteague** [comment]
Good catch, @rachel-kauff
