### ISSUE TITLE
Health services migration for remaining 6 VISNs

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#5871]
VAMC upgrade team A-Z mapping
* 3 are ready to go as of July 15
* Remaining 3 should be done by Friday July 16
* Internal VAMC upgrade team QA will be required week of July 19

Assumption
* data will be ready for migraition by July 20 EOD

## ACs
-  [ ] Facility and system health services migrated to CMS prod

**Comment by swirtSJW** [comment]
No data has been received as of 5:42PM ET.  Jul 20

**Comment by swirtSJW** [comment]
Data emailed at 8:30pm   Doing initial checks now.

**Comment by swirtSJW** [comment]
![image](https://user-images.githubusercontent.com/5752113/126567654-919c95ac-8f30-4d2f-bf71-75afbc450a99.png)

https://dsva.slack.com/archives/CPQFCQKEH/p1626827662185100

**Comment by swirtSJW** [comment]
![image](https://user-images.githubusercontent.com/5752113/126713836-76800378-4c20-4647-b28a-c39db07250af.png)

**Comment by swirtSJW** [comment]
Duplicate names 


Title of Duplicate | Section | VISN | vha
-- | -- | -- | --
Marion VA Medical Center | VA Northern Indiana health care | 10 | vha_610
Marion VA Medical Center | VA Marion health care | 15 | vha_657A5
Marion VA Clinic | VA Central Ohio health care | 10 | vha_621QB
Marion VA Clinic | VA Mountain Home health care | 9 | vha_757GC
Mountain Home VA Clinic | VA Central Arkansas health care | 16 | vha_598GA
Mountain Home VA Clinic | VA Boise health care | 20 | vha_531GI

**Comment by swirtSJW** [comment]
Facility health services changes.

1. `Massachusets` to `Massachusetts`
2. `Urgent Care` to `Urgent care`

4.

**Comment by swirtSJW** [comment]
5.  Mis-sectioned health care system in name 
![image](https://user-images.githubusercontent.com/5752113/127162090-8482770e-1ab9-4564-9dc4-669a708df109.png)

**Comment by swirtSJW** [comment]
![image](https://user-images.githubusercontent.com/5752113/127184729-3eada1ef-cdf0-48fc-a13c-35487fd48c74.png)

**Comment by swirtSJW** [comment]
https://dsva.slack.com/archives/CPQFCQKEH/p1627402230242700

> vha_523A4  Physical medicine and rehabilitation at VA Boston health care   is not migrating because  there is no system service of Physical medicine and rehabilitation at VA Boston health care, exists in the system migration.  Which should I do:
> 1. add it to the system migration
> 2. remove it fro the facility migration

Stan picked option #2

**Comment by swirtSJW** [comment]
Removed a duplicate from system health services.

**Comment by swirtSJW** [comment]
There was a missing system service for Physical medicine and rehabilitation from VA Boston and some data cleanup issues that VAMC upgrade team will take on by hand
https://dsva.slack.com/archives/CPQFCQKEH/p1627404895245300?thread_ts=1627402230.242700&cid=CPQFCQKEH
 
![image](https://user-images.githubusercontent.com/5752113/127317831-f6e4c2a1-27f3-4961-854b-863d8cbf135f.png)

**Comment by swirtSJW** [comment]
Lovell has been removed from the facility migration until such time that the name is finalized and can be added back to the migration data and run again.

**Comment by swirtSJW** [comment]
These have been run in production:

![image](https://user-images.githubusercontent.com/5752113/127707689-d59a08af-39c6-4bc7-98ce-4d62ca2fb21b.png)

![image](https://user-images.githubusercontent.com/5752113/127710272-238f7018-6601-436d-aa13-7125fddc63c0.png)

![image](https://user-images.githubusercontent.com/5752113/127710441-451d34db-bdb6-4c98-9c78-3e4360ec14d3.png)


I've let the VAMC upgrade team know too.
