### ISSUE TITLE
EPIC: VBA - Business Research

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#5872]
### Team
- David Shannon (lead)
- Denise Eisner
- Dave Conlon

### Methods
- Not a formal research process with a research plan, conversation guide, etc.
- Conversations with VBA employees
- Analytics 

### Timeline / Dependencies
- Began in July 2022 - will be ongoing
- 🛑 Some business research is a blocker for other research processes

### Research Questions

**Meta Project Questions**
- What are the intentional project constraints (things we're intentionally deeming out of scope for MVP)?
  - Some VBA facility types? 
  - Leadership list?
  - Veteran Service Organizations?
- 🛑  Which Regional Offices are going to be the MVP locations?
  - #9984
- Other VBA stakeholders not at MVP facilities
  - Regional oversight similar to VISNs?
  - By benefit business line?
- Is there a VBA-specific veteran journey map?
- What are the content governance pipelines? 
  - For facilities
  - For services / benefits

**Detailed Questions for MVP Definition**
- What other top tasks are available (e.g. Talk to someone online?) 
- How different are the types of facilities? Important to reflect?
- Prepare for your visit - What to bring
  - How does this vary by service?
  - How does this vary by facility?
- What else do Veterans need in order to be prepared for a visit (e.g. link to find a form?)
- What are the questions Veterans want answered by calling the phone number(s)? 
  - Is there a Call Center employee who could provide insight?
- How do we elaborate on the taxonomy structure to better explain the services?
  - How do services relate to benefit hubs?
- Is the service delivery the same across all locations nationally or locally nuanced? (Is the service description hardened nationally?)
- Per service 
  - Is there an online version of this tool? 
  - Are there benefits that Veterans already avail predominantly or entirely online? What tools/sites are these? 
  - Which tools result in work for a local benefits office, vs some central/national office? 
  - Should some benefits (Changing Direct Deposit?) be encouraged/promoted to be done online?
- Are Events National? Local? Hybrid? And what is the maintenance load?
- Are Spotlights National? Local? Hybrid? And what is the maintenance load?
- Is a list of Veteran Service Organizations (VSOs) located at that facility important? 
  - Analytics on how many visits these pages get?

**Comment by davidconlon** [comment]
@kevwalsh Attaching the final spreadsheet that will be the VBA data from the VBA_facilities database that is in Lighthouse.

Important related Facilities team work includes looking at the VBA services to better understanding/alignment to Veteran needs. Would like to understand how this overlaps with Benefits Hub
https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/32819
https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/4865

[https://app.zenhub.com/files/154174777/b84423c5-4031-426e-99ee-956d1a8ec8c9/download](https://app.zenhub.com/files/154174777/b84423c5-4031-426e-99ee-956d1a8ec8c9/download)

**Comment by dsinla** [comment]
Link to google doc for capturing initial ideas around VBA Discovery:
https://docs.google.com/document/d/1FSj42SVHc0flLItUCRXpX7ghcArQuUYAde6OzJSHlnI

**Comment by jcklpe** [comment]
For the Business research I think it might be interesting to perform an [object oriented ux research workshop](https://uxdesign.cc/what-is-object-oriented-ux-19e14c435d18).

**Comment by dsinla** [comment]
We started this as an informal process, but given some of the misalignment, how do we bring this into a more formal structure? The next question here- how best to break this into concrete Issues?

- Identify business contacts at MVP locations. 
  - Is this the person identified by the Tasker? We're unclear if the Tasker-provided name is the current editor, or performs some other role at the RO.
  - Assumption that this person is different than the editor, since that will be part of Editor Research.
  - Is this person the Public Contact Officer, ie the person(s) at the RO who has most direct contact with Veterans receiving benefits.
- Define the goal of this research, ie: _gaining understanding of current processes and pain points with service delivery? with the website? with Veterans'  visits?_  
- Create conversation guide  
- Conduct 1/2 interview with each contact

**Comment by davidmpickett** [comment]
Call with Dave C yesterday helped realign and set criteria for this effort. He is leading this. We created a [mural of stakeholders and roles](https://app.mural.co/t/vagov6717/m/civicactions3117/1661281671544/cb7a2a4a492089c7437bf0b8eaade0dbcea9eb3f?sender=u20829d1b64855e281dde2585)

**Comment by davidmpickett** [comment]
Closing this Epic as it was poorly named and never served as a meaningful locus of tickets.
