### ISSUE TITLE
Site email address is dated

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#5878]
Pending broader discovery of email messages and emails sent by the CMS.

**Describe the defect**

Any email sent by Drupal should use an email address that is active. 

**To Reproduce**
1. Go to https://prod.cms.va.gov/admin/config/system/site-information
2. See that the current email address is vacmssupport@va.gov

**Expected behavior**
Email should go from support@va-gov.atlassian.net

**Screenshots**

![Basic_site_settings___VA_gov_CMS](https://user-images.githubusercontent.com/643678/125990470-ce2b2208-961e-4a07-a126-f2b4914e1d21.png)

- [ ] `Core Application Team`
- [x] `Product Support Team`

**Comment by indytechcook** [comment]
I'm not 100% sure this will work with sending email from our SMTP server.  cc @ElijahLynn

**Comment by ElijahLynn** [comment]
> I'm not 100% sure this will work with sending email from our SMTP server.  cc @ElijahLynn 

Thanks, I'm not sure either, but we can test real quick on DEV and find out.
