### ISSUE TITLE
[SPIKE] Discuss best approach for leveraging Github actions for CI

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-cms#5880]
## Description

As a CMS engineer, I want to minimize the maintenance overhead for CI actions, so that I may focus my development efforts on adding direct value to the CMS.

There are certain challenges with using Github Actions when an existing action does not meet the CMS' needs, see https://dsva.slack.com/archives/CT4GZBM8F/p1626365340185300 for more background.

Let's meet to discuss 

## Acceptance Criteria
- [x] Engineering and Devops staff have met and settled on an approach or identified avenues for further research
   - [x] if the former, this approach is documented in the CMS docs
   - [ ] if the latter, issue(s) have been created to do this research

**Comment by mchelen-gov** [comment]
slack convo asking about errors with current GHA used: https://dsva.slack.com/archives/CU1E4CX9U/p1626382969114700

some relevant info:
> demien: php and composer are available in runner
https://github.com/actions/virtual-environments/blob/ubuntu20/20210712.0/images/linux/Ubuntu2004-README.md

> brett: This is on my radar for this afternoon, to work on the php-actions/composer and get that working in the context of the VA. Whether that means figuring out a way to use it as is, or contributing a modification upstream to make it more usable

**Comment by acrollet** [comment]
Ephemeral doc from spike: https://docs.google.com/document/d/1LKvJYgon_nMtVo4IQZqooyCDBrg-du1hDJJhbgaPcfY/edit?usp=sharing

**Comment by acrollet** [comment]
I've updated https://github.com/department-of-veterans-affairs/va.gov-cms/blob/master/READMES/testing.md with information based on our discussion today.

**Comment by acrollet** [comment]
Throwing the other participants on as assignees so someone can review my changes.

**Comment by ElijahLynn** [comment]
> Ephemeral doc from spike:

Do we want to copy the contents into that content and delete that doc?

**Comment by ElijahLynn** [comment]
Left one comment on https://github.com/department-of-veterans-affairs/va.gov-cms/commit/ab02a1ee3827cc519d21ca31aa10fd534ac1d912 about how to make the forked GitHub Action public/open source.

**Comment by acrollet** [comment]
Meeting notes:

## What are the top level goals?



* Make tests fast
* Have a clear, consistent UI for viewing test results
* Reduce infrastructure maintenance overhead
* Follow VFS/platform(?) best practices / standardization


## What problems are we trying to solve?



* Defining best practices for Github Actions against the CMS repo
* Reducing on-going maintenance overhead/technical debt
    * Scripts vs 3rd party GHA
* Selecting and pulling docker images
* Permissions issues when creating docker images on forked repos
    * Why?
        * Increases performance/reusability
    * Possible to avoid creating the image at all?
* Tugboat vs GHA
    * GH actions are much more parallelizable
* Shared config for GHA (ie version numbers)
    * And project
* CI checks on merge are slow
    * What are the slow parts here


## What possible solutions exist?



* Github action management
    * Order of preference:
        * Use 3rd party GHA actions OOTB
        * Use overrides if needed and attempt to contribute new overrides upstream
        * Fork or create 3rd party action in repo under DSVA
        * Ideally, contribute any custom actions upstream under the reviewdog space
    * Create custom actions under the DSVA github org
        * Elijah says: first create a private repo and then ask Patrick Bateman to make a repo public
        * Work towards contributing to reviewdog space
* Shared cache for composer deps: [https://github.com/actions/cache](https://github.com/actions/cache)
    * Hash on both composer.lock and composer.json, cache vendor dirs and composer cache


## Questions to answer



* Is it possible to use an action from the same repo?
* Do github actions have to be published?
* How best to share actions across org?
    * [https://docs.github.com/en/actions/learn-github-actions/sharing-workflows-with-your-organization](https://docs.github.com/en/actions/learn-github-actions/sharing-workflows-with-your-organization)
