### ISSUE TITLE
Update tugboat to v2.21.11 release

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-cms#5881]
## Description

As a CMS devops engineer, I want to be using the most current release of tugboat, in order to reduce maintenance of custom patches.

See: https://dsva.slack.com/archives/C01A35JDH88/p1626203659047200

## Acceptance Criteria
- [ ] Tugboat is using v2.21.11
- [ ] Upgrade process has been documented in the CMS repo

**Comment by olivereri** [comment]
Previous update issue:
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/5084

This update includes the webhook race-condition patch but we'll still need to re-apply the ulimit and proxy-timeout patches?

**Comment by ElijahLynn** [comment]
Here are some docs on how to do this: https://github.com/department-of-veterans-affairs/va.gov-cms/blob/master/READMES/devops/tugboat-on-premise-installation.md#deployment
