### ISSUE TITLE
Non-admins with access to more than one VAMC menu can't see what menu they are adding to.

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#5884]
**Describe the defect**

See [slack thread](https://dsva.slack.com/archives/CT4GZBM8F/p1626469471282300)

**To Reproduce**
1. Log in as user 1447
2. Go to /node/add/health_care_region_detail_page
3. Under menu settings, choose a parent link
4. Note that all menus in VISN 19 are conflated 

**Expected behavior**
I should be able to see what menu i am adding to

**Screenshots**

![Create_VAMC_Detail_Page___VA_gov_CMS](https://user-images.githubusercontent.com/643678/126089484-a2022dfe-a60c-415d-b1d5-6095c8702171.png)

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Core Application Team`
- [x] `Product Support Team`

**Comment by swirtSJW** [comment]
THe config change has been merged, but not the regex fix.
