### ISSUE TITLE
Design + implement standardized training curriculum template (?)

### ISSUE THREAD

**Issue by rachel-kauff** [department-of-veterans-affairs/va.gov-cms#5899]
## Description
Content design for:
- Individual modules
- product curriculums
- "track my progress" form for individual trainees
   - "As a training user who is returning to my training curriculum after a week away, I need to remember what I've completed so I keep track of my progress." 

## Acceptance Criteria
- [x]  Co-design w/ Jane
- [x] Create a list of elements the template should accomodate
- [ ] If additional design patterns or new content blocks get proposed, they're added to the backlog

**Comment by nataliedunbarCS** [comment]
Content Design Documentation: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/5899
