### ISSUE TITLE
Post-Deploy Tests jenkins job should fail when tests fail

### ISSUE THREAD

**Issue by indytechcook** [department-of-veterans-affairs/va.gov-cms#5908]
## Description

When tests fail the jenkins job which runs the test fails.

Example: http://jenkins.vfs.va.gov/job/testing/job/cms-post-deploy-tests-staging/588/console

## Acceptance Criteria
- [ ] When tests fail the jenkins job which runs the test fails.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [x] `Core Application Team`
- [ ] `Product Support Team`

**Comment by acrollet** [comment]
@indytechcook can you confirm this is done? Thanks!
