### ISSUE TITLE
VAMC banner alerts created on IEF pages are always associated with Pittsburgh Health Care

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#5911]
**Describe the defect**

When a PAO creates a banner alert from within the Operating Status page, it gets associated with Pittsburgh Health Care section.

**To Reproduce**

As user 1625
1. Go node/2370/edit
2. Create a banner alert with IEF
3. Save.
4. Find the node from /admin/content 
5. See that it's assigned to Pittsburgh Health Care section via field_administration

**Expected behavior**

I should be asked what section to assign to OR it should just figure it out from the context i'm in. 

**ACs**

- [ ] Section (`field_administration`) is either filled (and hidden) or filled (and visible) to editors in th eIEF
- [ ] While we're in here: "add existing banner alert" option is removed.

![Edit_VAMC_System_Operating_Status_Operating_status_-_VA_Wilmington_health_care___VA_gov_CMS](https://user-images.githubusercontent.com/643678/126369747-c4211e77-29f8-472f-a249-720f96c1c113.png)

**Comment by kevwalsh** [comment]
I'm not sure what's causing this, since there's no default value for https://staging.cms.va.gov/admin/structure/types/manage/full_width_banner_alert/fields/node.full_width_banner_alert.field_administration

![Section_settings_for_VAMC_System_Banner_Alert_with_Situation_Updates___VA_gov_CMS](https://user-images.githubusercontent.com/643678/126369947-a7a0c6cf-55ac-4de2-9239-e8b89ec494f9.png)

**Comment by kevwalsh** [comment]
Quickest way to solve this (but may not be the best way) might be to unhide the Section field (and set to Select list) on admin/structure/types/manage/full_width_banner_alert/form-display/inline_entity_form

**Comment by swirtSJW** [comment]
We do some js manipulation on that field on node/add that may not be firing... or firing correctly on IEF.   The contexts may not be the same so either the JS is not firing or it does not have all the data it was supposed to have.

**Comment by kevwalsh** [comment]
Another implementation idea: replace the IEF add form with a link to /node/add/full_width_banner_alert (opening in a new window).

**Comment by swirtSJW** [comment]
I think there is something additional at play here.  If I login as a system editor for Albany.   I can not create a banner alert in IEF it will not let me save the node because it can't save the alert.
![image](https://user-images.githubusercontent.com/5752113/126377009-408c54f4-19b0-47de-b311-fd86d492afa3.png)

**Comment by swirtSJW** [comment]
The issue is we have disabled the two fields we need to have showing and they end up with no values on validation.
![image](https://user-images.githubusercontent.com/5752113/126395239-c79c4d69-3ae6-4f6c-b244-51dbbcebb771.png)

**Comment by swirtSJW** [comment]
We either need to reveal them or we need to set values on node save based on the field_administration on the operating status page.
