### ISSUE TITLE
Document process to cancel or delay the automatic code deployment

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-cms#5930]
## Description

As a CMS engineer, I need to know how to delay the production release, in order to allow mission-critical and/or time-sensitive code & security updates to be deployed during the daily release window.

## Acceptance Criteria
- [x] https://github.com/department-of-veterans-affairs/va.gov-cms/blob/master/READMES/brd.md is updated with instructions to cancel/delay the automatic code deployment

**Comment by acrollet** [comment]
Thanks @ndouglas for taking this on! @ElijahLynn could you review the updated doc? Thanks!

**Comment by ElijahLynn** [comment]
I just modified it slightly in https://github.com/department-of-veterans-affairs/va.gov-cms/commit/65374f08375481aa12c0d58b657529829989920f.l Good to go!

**Comment by acrollet** [comment]
Great work folks!
