### ISSUE TITLE
Removing a facility from the Operating status page offers an option to delete the node.

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#5951]
**Describe the defect**

When removing a facility from an operating status page, Lisa was able to delete the facility node
https://dsva.slack.com/archives/C0MQ281DJ/p1627056772010100?thread_ts=1627046040.002000&cid=C0MQ281DJ
![image](https://user-images.githubusercontent.com/5752113/126811993-5bd2114c-de51-4fec-839d-85958e7428a1.png)

https://prod.cms.va.gov/northern-california-health-care/locations/cypress-avenue-va-clinic    no longer exists. as a result.

This may be a new "feature" that Drupal 9 introduced.  But it is an anti-feature for us.

![image](https://user-images.githubusercontent.com/5752113/126812106-b9c4d8a0-27cf-4e2d-ba4e-83efb444c555.png)

The good news is that an ordinary editor is not presented with this option 
![image](https://user-images.githubusercontent.com/5752113/126813786-2fe555de-285e-4fa3-bd5d-258574aea141.png)

**To Reproduce**
1. Go to  an operating status page like `/northern-california-health-care/operating-status`
2. Click on 'edit'
3. Expand the "Facility Operating Statuses" field group.
4. Click the "remove button" one of the facilities.
4. Notice the checkbox that allows for deletion of the facility.

**Expected behavior**
Editors should not be able to delete facilities.

**Screenshots**

**Desktop (please complete the following information if relevant, or delete):**

**Additional context**
Add any other context about the problem here. Reach out to the Product Managers to determine if it should be escalated as critical (prevents users from accomplishing their work with no known workaround and needs to be addressed within 2 business days).

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Defect")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS objective (orange) (not needed for bug tickets)
- [ ] CMS-supported product (black)

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [x] `Core Application Team`
- [x] `Product Support Team`

**Comment by indytechcook** [comment]
Is this something we can manage via permissions?

**Comment by acrollet** [comment]
@swirtSJW it looks like this is no longer an issue - I followed the steps, did not see a checkbox to delete the facility, and after removing a facility, the node it references still exists. Please re-open if I got this wrong :-)
