### ISSUE TITLE
Monitor JSD widget endpoint

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-cms#5959]
## Description

As a CMS team member, I need to be alerted if the Jira Service Desk widget is not working correctly, so that I can be confident that editors are able to contact the help desk.

## Acceptance Criteria
- [ ] JSD widget is monitored for functionality every 15 minutes with 2 retries
- [ ] CMS team receives an alert on Slack if the JSD widget is not functional

**Comment by mchelen-gov** [comment]
i'm not sure JSD is critical for CMS prod so i'm moving this to parent epic

**Comment by olivereri** [comment]
AC asks for slack alert, you can add `@slack-cms-notifications ` to the `Notify your Team` section. It's already integrated and ready to send notifications.

**Comment by acrollet** [comment]
I might consider adding an assertion on the body, maybe looking for something like "Contact CMS help desk" to confirm we're seeing the content we expect? Otherwise looks great.

**Comment by ndouglas** [comment]
unfortunately, can't add assertions on the body

<img width="608" alt="Screen Shot 2021-09-02 at 11 47 14 AM" src="https://user-images.githubusercontent.com/1318579/131875726-13ed6371-b655-4ddb-a1bd-964a65f8588b.png">

https://stackoverflow.com/questions/17154967/is-content-encoding-being-set-to-utf-8-invalid

Content-Encoding UTF-8 is indeed invalid, but I wouldn't hold my breath waiting for Atlassian to fix it 😕

**Comment by acrollet** [comment]
> 
> Content-Encoding UTF-8 is indeed invalid, but I wouldn't hold my breath waiting for Atlassian to fix it 😕

boooooo - thanks for checking into it!
