### ISSUE TITLE
Update http-interop/http-factory-guzzle from 1.1.0 to 1.2.0

### ISSUE THREAD

**Issue by indytechcook** [department-of-veterans-affairs/va.gov-cms#5964]
## Description

Update http-interop/http-factory-guzzle from 1.1.0 to 1.2.0.  See #5962

## Acceptance Criteria
- [ ] http-interop/http-factory-guzzle has been updated from `1.1.0` to `1.2.0`
- [ ] selecting a branch on `content-build` still works

**Comment by ndouglas** [comment]
Looks like this was done in 3c31f51993927f9d4b1b7b7158c73a6165999125
