### ISSUE TITLE
Vet Center services added through IEF bypass allow_only_one_validation

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#5981]
**Describe the defect**
When editing a vet_center it is possible to add/create duplicate services even though duplicate service creation is prevented by the allow_only_one  field on the content type 
![image](https://user-images.githubusercontent.com/5752113/127391781-7c702154-3802-4ef8-9a6f-f0e5161f0506.png)

Saving the service directly prevents the creation of duplicate
![image](https://user-images.githubusercontent.com/5752113/127391827-72636998-fb3e-4bc5-9352-986eb2850e94.png)

However creating using inline entity form does not.
![image](https://user-images.githubusercontent.com/5752113/127391963-5b102712-bbc0-464a-aafa-7bccc6660a4c.png)

It is uncertain at this time if this is a bug with [IEF](https://www.drupal.org/project/inline_entity_form) or with [Allow Only One](https://www.drupal.org/project/allow_only_one). 

There are some validation issues on the IEF issues board that might be related
 
1. https://www.drupal.org/project/inline_entity_form/issues/2926859 (has a patch)
2. https://www.drupal.org/project/inline_entity_form/issues/2780079 (seems similar but no helpful information)
3. https://www.drupal.org/project/inline_entity_form/issues/2821343  (likely the result  of #1, nothing helpful)

I have created this issue on allow_only_one for use IF this is a bug in that module  
https://www.drupal.org/project/allow_only_one/issues/3225757 If it turns out to be an IEF issue that is resolved by the patch, then add a link and note to the allow_only_one issue.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information if relevant, or delete):**

**Additional context**
Add any other context about the problem here. Reach out to the Product Managers to determine if it should be escalated as critical (prevents users from accomplishing their work with no known workaround and needs to be addressed within 2 business days).

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Defect")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS objective (orange) (not needed for bug tickets)
- [ ] CMS-supported product (black)

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [x] `Core Application Team`
- [x] `Product Support Team`

**Comment by kevwalsh** [comment]
Related, will solve this problem in a different way, and improve UX. But also further obscure this defect. https://github.com/department-of-veterans-affairs/va.gov-cms/issues/5888 (fixed in https://github.com/department-of-veterans-affairs/va.gov-cms/pull/5915 )

**Comment by davidmpickett** [comment]
This defect will be resolved once the IEF changes are implemented. Leaving this defect in backlog to confirm and close after https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18003

**Comment by jilladams** [comment]
Can be validated / closed when #18003 ships

**Comment by davidmpickett** [comment]
Verified on Prod
![Screenshot 2024-08-19 at 1 57 28 PM](https://github.com/user-attachments/assets/6568329b-f0a4-430b-9d06-14c5f01f61ce)
