### ISSUE TITLE
Automatically remove unused CI environments

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-cms#5988]
## Description

As a CMS Devops Engineer, I wish for older unused tugboat environments to be automatically removed, so that Tugboat's disk usage will not grow without bounds.

## Acceptance Criteria
- [ ] Environments meeting the following criteria are automatically removed nightly
  - Created > 30 days ago
  - Suspended
  - Not locked
- [ ] This change has been announced to CMS users

**Comment by TheBoatyMcBoatFace** [comment]
Duplicate. Handled by
- #10423
