### ISSUE TITLE
Obtain staging + dev SSOi access

### ISSUE THREAD

**Issue by mchelen-gov** [department-of-veterans-affairs/va.gov-cms#5994]
## Description

As a CMS engineer, I need access to test PIV login on dev & staging, so that I can ensure that mission-critical functionality is functional before deploying new code to production.

## Acceptance Criteria
- [ ] Staging SSOi access tested & working

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [x] `Core Application Team`

**Comment by jefflbrauer** [comment]
@mchelen Is this something we should continue to keep on the board each sprint or can we put it in the backlog until you are sure you will have time for it?

**Comment by cmaeng** [comment]
@mchelen-gov can this be closed?

**Comment by cmaeng** [comment]
pivoting this to obtain access for @timcosgrove and @cmaeng

**Comment by ElijahLynn** [comment]
I swapped out Mike for Tim per our call just now. 

@timcosgrove instructions are here > https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/platform/cms/cms-sso-saml-iam-login-braindump.md#testing-login

**Comment by timcosgrove** [comment]
Access to staging.cms.va.gov via PIV confirmed.
