### ISSUE TITLE
Reduce noisy tugboat messages in #cms-ci

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#5999]
## User Story or Problem Statement

As a CMS team member, i want the #cms-ci channel to be free of noisy updates so that i can find the good stuff. 

Currently, `va-cms-bot` sends this message every hour of every day, on the hour

> Successfully deployed dcb8872 to Tugboat

![Slack___cms-ci___Digital_Service___VA___3_new_items](https://user-images.githubusercontent.com/643678/127870165-03799929-ae2b-47e2-92ce-2f6592fb62ea.png)

## Acceptance Criteria
- [ ] TBD

## Implementation steps
<optional>

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [x] `Core Application Team`
- [ ] `Product Support Team`

**Comment by acrollet** [comment]
@ElijahLynn removed deployment messages and added comments.

**Comment by ElijahLynn** [comment]
Here are the commands that I used: 
![image](https://user-images.githubusercontent.com/1504756/127905891-03770cd6-5143-49de-be24-ae6b4c5935f8.png)

https://dsva.slack.com/archives/CLLM968CB/p1627928157044200
