### ISSUE TITLE
Re-export site config after 9.2 update

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-cms#6019]
## Description

Follow-on from #5936, see https://www.drupal.org/node/3114725

(This may have already happened, but let's confirm)

## Acceptance Criteria
- [ ] Site config has been re-exported and confirmed as functionally equivalent

**Comment by jefflbrauer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VAgov-CMS-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/6019?planning-poker) with ZenHub @ElijahLynn @indytechcook @ndouglas @olivereri @timcosgrove

**Comment by jefflbrauer** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VAgov-CMS-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/6019?planning-poker) with ZenHub @cweagans

**Comment by acrollet** [comment]
@ndouglas verified this is done. (Thanks @ethanteague! 💋 )
