### ISSUE TITLE
Asset file rsync failures

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-cms#6021]
**Describe the defect**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information if relevant, or delete):**

**Additional context**
Add any other context about the problem here. Reach out to the Product Managers to determine if it should be escalated as critical (prevents users from accomplishing their work with no known workaround and needs to be addressed within 2 business days).

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Defect")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS objective (orange) (not needed for bug tickets)
- [ ] CMS-supported product (black)

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [x] `Core Application Team`
- [x] `Product Support Team`

**Comment by olivereri** [comment]
Solution found here.
https://superuser.com/questions/579001/rsync-does-it-create-a-temp-file-during-transfer

**Comment by olivereri** [comment]
Error example:
`08:41:01  TASK [Parallel Rsync files to EFS] *********************************************
08:41:01  Tuesday 03 August 2021  15:40:56 +0000 (0:00:30.315)       0:03:14.456 ******** 
08:41:03  fatal: [ip-10-247-97-32.us-gov-west-1.compute.internal]: FAILED! => changed=true 
08:41:03    cmd: find -L . -type d | parallel rsync -aR --ignore-existing --update --delete {} /var/www/cms/docroot/sites/default/files/
08:41:03    delta: '0:00:06.658550'
08:41:03    end: '2021-08-03 15:41:03.047093'
08:41:03    msg: non-zero return code
08:41:03    rc: 2
08:41:03    start: '2021-08-03 15:40:56.388543'
08:41:03    stderr: |-
08:41:03      rsync: failed to set permissions on "/var/www/cms/docroot/sites/default/files/styles/1_1_square_medium_thumbnail/public/2021-08/.Tara Manis-Healy.jpg.1YSwgj": No such file or directory (2)
08:41:03      rsync: rename "/var/www/cms/docroot/sites/default/files/styles/1_1_square_medium_thumbnail/public/2021-08/.Tara Manis-Healy.jpg.1YSwgj" -> "styles/1_1_square_medium_thumbnail/public/2021-08/Tara Manis-Healy.jpg": No such file or directory (2)
08:41:03      rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1039) [sender=3.0.6]
08:41:03      rsync: failed to set permissions on "/var/www/cms/docroot/sites/default/files/styles/1_1_square_medium_thumbnail/public/2021-08/.Tara Manis-Healy.jpg.WudY17": No such file or directory (2)
08:41:03      rsync: rename "/var/www/cms/docroot/sites/default/files/styles/1_1_square_medium_thumbnail/public/2021-08/.Tara Manis-Healy.jpg.WudY17" -> "styles/1_1_square_medium_thumbnail/public/2021-08/Tara Manis-Healy.jpg": No such file or directory (2)
08:41:03      rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1039) [sender=3.0.6]
08:41:03    stderr_lines: <omitted>
08:41:03    stdout: ''
08:41:03    stdout_lines: <omitted>
08:41:03  ...ignoring`

**Comment by olivereri** [comment]
When testing manually on he server, if an older and a newer asset file backup are sync'd back to back the error is reproducible. This indicates that there may be an issue with EFS and timing of file oeprations.

**Comment by olivereri** [comment]
Important note about `--inplace` from the rsync man page.

WARNING: you should not use this option to update files that are being accessed by others, so be careful when choosing to use this for a copy.

Dev and Staging sites shouldn't be accessible during this time to avoid the above issue.

**Comment by olivereri** [comment]
If problems do persist check this out:
http://arthurguru.users.sourceforge.net/blog/rsync_to_efs.html
