### ISSUE TITLE
VAMC operating status info forms are not the same

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#6027]
**Describe the defect**
On the facility form, the Operating status more info (field_operating_status_more_info) shows a recommended character count of 300.  The inline entity form does not.
![image](https://user-images.githubusercontent.com/5752113/128100616-96c9ba63-ae9d-442f-9007-c51cc8163a70.png)

It would be good if these were in alignment.   Also we may want to get feedback as to whether this should be a hard limit as currently the facility API is blocking us for over 300 chars on the status push.

**Expected behavior**
Both versions of the form should speak the same truth.

**Screenshots**

**Desktop (please complete the following information if relevant, or delete):**

**Additional context**
Add any other context about the problem here. Reach out to the Product Managers to determine if it should be escalated as critical (prevents users from accomplishing their work with no known workaround and needs to be addressed within 2 business days).

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Defect")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS objective (orange) (not needed for bug tickets)
- [ ] CMS-supported product (black)

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Core Application Team`
- [x] `Product Support Team`

**Comment by davidmpickett** [comment]
Would b e resolved by #6849

**Comment by davidmpickett** [comment]
IEF now displays character count
![Image](https://github.com/user-attachments/assets/66b3bcf5-9895-4989-9577-4e3bec6f3ef5)
