### ISSUE TITLE
VAMC Locations pages are broken 

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#6031]
**Describe the defect**

All VAMC locations pages (eg /altoona-health-care/locations) are missing. 

This broke with #5255, reordering of content queries to put list pages first caused different templates to be used. 

This reveals some issues that go back to #1005 

**To Reproduce**
1. Go to /altoona-health-care/locations
2. white screen

**Expected behavior**
Locations list page shows

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [x] `Core Application Team`
- [x] `Product Support Team`

**Comment by indytechcook** [comment]
https://github.com/department-of-veterans-affairs/content-build/pull/424 was merged and deployed yesterday which fixed the issue.

Follow-ups:
* Post Mordem: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/6040
