### ISSUE TITLE
facility selector on facility health services is not reflecting recent changes

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#6037]
**Describe the defect**
WHen trying to add or move a facility health service to  VISN 12 > VA Illiana health care > Bloomington VA Clinic   The facility does not appear as an option.

The root cause is that there are two Bloomington CA Clinics:
1. VISN 12 > VA Illiana health care > Bloomington VA Clinic (node/4393)
2. VISN 10 > VA Indiana health care > Bloomington VA Clinic (node/1620)
Originally both nodes were assigned to Indiana but on Aug 2 node/4393 was correctly reassigned to VA Illiana.

The problem is the facility selector on the facility health services it still using the old assignment and showing both in Indiana
![image](https://user-images.githubusercontent.com/5752113/128356313-a1ffa920-3644-4675-bfea-f7161c39b2c8.png)

![image](https://user-images.githubusercontent.com/5752113/128357282-d1930973-a654-47a1-bb1e-7a7befb94847.png)

A full cache clear did not resolve the issue.

Hunch:  The VIew that is feeding that facility select list is not using the latest revision It is somehow using an older revision (maybe the original revision?).

**To Reproduce**
1. Go to https://prod.cms.va.gov/node/add/health_care_local_health_service
2. For section, select VISN12 > VA Illiana Health Care
3. For facility, try to select Bloomington VA Clinic  and see that it does not appear in the select list.
4. Change the section to VISN 10 > VA Indiana health care
5. In the facility select list, see that Bloomington VA clinic shows up twice.

**Expected behavior**
When a facility's system assignment is changed, the facility select list on facility health services should update to reflect that change.

**Screenshots**

**Desktop (please complete the following information if relevant, or delete):**

**Additional context**
Add any other context about the problem here. Reach out to the Product Managers to determine if it should be escalated as critical (prevents users from accomplishing their work with no known workaround and needs to be addressed within 2 business days).

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Defect")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS objective (orange) (not needed for bug tickets)
- [ ] CMS-supported product (black)

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Core Application Team`
- [x] `Product Support Team`

**Comment by ethanteague** [comment]
This is a weird one - tried just about everything under the sun (in views config, as well as in revisions on the latter Bloomington node). If this is a one off, I _could_ just filter the id out via js. Glad to keep at it, but wanna make sure the time investment doesn't exceed the benefit.
What say you, @swirtSJW @kevwalsh ?
