### ISSUE TITLE
[SPIKE] Determine best practices and implementation approach for hardening prod config

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-cms#6043]
## Description

As a CMS engineer, I need to understand the motivations and best practices for making production configuration non-editable, in order to implement an appropriate, robust solution.

## Acceptance Criteria
- [ ] Spike has been held
- [ ] implementation issues have been created in this epic

**Comment by swirtSJW** [comment]
Closing this as the need is not clarified.
