### ISSUE TITLE
[SPIKE] Strategic planning for monitoring/alerting on external services

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-cms#6050]
## Description

As a CMS Devops Engineer, I need to know when services the CMS depends upon are unavailable, so that I can resolve issues and/or implement workarounds and notify system users.

## Background

This is a follow-on from #5603. The engineering team and Govt PO will meet to review each service listed on the [upstream dependencies doc](https://github.com/department-of-veterans-affairs/va.gov-cms/blob/master/READMES/upstream-dependencies.md) and answer the following questions:

- Does monitoring/alerting already exist?
- If so, can we piggy-back on it to get alerts?
- If not, do we need to implement our own monitoring and/or alerting?

## Acceptance Criteria
- [ ] For each service, a decision is recorded and noted on this issue, (if no-op) or a follow-on issue has been created if further action is required

**Comment by indytechcook** [comment]
Sentry Doc Created: https://github.com/department-of-veterans-affairs/va.gov-cms/blob/master/READMES/sentry.md

**Comment by indytechcook** [comment]
Updated https://docs.google.com/document/d/15oe0wtGI_MdaScYpjJWOgPjBqQWUFURc19HheWswEe4/edit also
