### ISSUE TITLE
Discovery: Recurring events does not observe Phoenix year-round observance of MST

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#6056]
**Describe the defect**
Recurring events set to Phoenix time zone should _not_ have their start times adjusted during Daylight Savings Time.

**To Reproduce**
1. Go to /node/add/event
2. Create a recurring event starting at 9am, repeating weekly, for 1 year, and set time zone to Phoenix.
3. See that your event starts at 9am when DST is active in Eastern time zone, but at 10am when DST is not.

**Expected behavior**
Event should start at 9am MST year-round, when Phoenix is chosen. 

**Screenshots**

![Outreach_and_events___A_Phoenix_recurring_event___Veterans_Affairs](https://user-images.githubusercontent.com/643678/128697663-0b8519d9-1ecc-4f07-9b65-e0ab6771b6c2.png)

## Considerations for path forward
1. We cannot assume that people creating events are seated in the timezone where the event will take place
2. We cannot request Editors set specific browser settings as a solution
3. We need to consider that VA VPN will have an impact on Drupal editor timezones

## Acceptance criteria
- [ ] determine a proposal for path forward, including getting @swirtSJW 's input, that we can propose to Dave
- [ ] Create an implementation ticket

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Core Application Team`
- [x] `Product Support Team`

**Comment by ethanteague** [comment]
The concensus to fix is to upgrade to `smart_date: 3.4.0-rc1` and set default site timezone (`admin/config/regional/settings`) to `UTC` (currently it is set to `NYC`). Tested locally, and this resolves the daylight savings time issue for Phoenix. Is setting the default timezone to UTC acceptable, @kevwalsh ?

**Comment by ethanteague** [comment]
Added this work to https://github.com/department-of-veterans-affairs/va.gov-cms/pull/6065 (last commit). Can drop from pr if we don't go this way.

**Comment by kevwalsh** [comment]
Is your sense that this is issue is unique to smart_date, or is it common to sites that are using only drupal core for date fields? 

Setting the default timezone to UTC may require a bunch of additional work, both now and ongoing. 

I think we'll need to think through the experience for users and audit all the places that times are showing up, to ensure that they are taking user's time zone into account. Also that our users' timezones are set correctly (not sure if they are right now).

**Comment by ethanteague** [comment]
> Is your sense that this is issue is unique to smart_date, or is it common to sites that are using only drupal core for date fields?
> 
> Setting the default timezone to UTC may require a bunch of additional work, both now and ongoing.
> 
> I think we'll need to think through the experience for users and audit all the places that times are showing up, to ensure that they are taking user's time zone into account. Also that our users' timezones are set correctly (not sure if they are right now).

Yeah, this is unique to smart_date, particularly the recurring sub module.

**Comment by jilladams** [comment]
Per 6/10 sync with Dave, this is a priority to resolve if it's still a valid ticket. Added to PW backlog, needs to be refined. @dsasser FYI, probably worth catching up with Ethan on this additional Events piece if you have free time / are looking for work.

**Comment by dsasser** [comment]
🟡
 I have confirmed this issue is still valid. And unfortunately there is no site wide setting that can prevent the issue wholesale.

This issue is observable when:
Users' tz is set to something other than Phoenix or UTC (user 1 admin is set to UTC, so problem is not visible until you change that to something else)
-OR-
Users' tz is unset, but sitewide tz is set to something other than Phoenix or UTC.

Therefore, changing the sitewide default tz will alone not have have the desired affect in all cases. (only 7 users have Phoenix timezone, and none currently are set to UTC other than the admin user 1).

The issue appears to be a bug contained within the Smart Date module and/or its child module Smart Date Recur. I have soured the issue queue for issues related to this but have not yet found a community provided solution.

Further technical sleuthing is needed to determine where in the code the flaw is occurring.

**Comment by dsasser** [comment]
I originally considered this a UX display issue, however it has been determined this is a data integrity problem/bug. For records showing incorrect times, the data is being saved into the database incorrectly. Consider the below table that shows timestamps differ despite the input being identical:
<img width="586" alt="Screen Shot 2022-07-01 at 3 14 09 PM" src="https://user-images.githubusercontent.com/221539/176973413-8cb13d8d-89e6-4e6c-8a15-79bc77f23cff.png">

Here the data entered into the CMS was identical for an event with 3 occurrences. You can see how the timestamps change when the user had the 'New York' timezone. This is wrong: dates in Drupal are stored without timezone offset, and shouldn't change based on the current users' timezone.

Next we need to determine where this is happening in the contrib module or it's php dependency on simshaun/recurr.

**Comment by jilladams** [comment]
Cut https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9684 for follow on work. Closing this ticket based on Daniel's discovery notes.
