### ISSUE TITLE
Editor experience for repeating / recurring events

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#6057]
## User Story or Problem Statement

1. As an event editor, i should only be able to create a recurring event based on a simple pattern (like once a week, or 1st Tuesday of the month, or every M/W/F) 

2. As an event editor, i should only be able to create a single event date, or a single event date repeating pattern. I should not be able to create two "custom" dates, or two custom repeating patterns.

 - Smart date recurring module requires the date field to be multivalue. By default, this adds a "Add another item" button that is confusing. 

<details><summary>Screenshots</summary>

### New config for field_datetime_range_timezone	

From https://master-dzqiprnzpsoj5ifjekygsan9jad6kjdo.demo.cms.va.gov/admin/structure/types/manage/event/fields/node.event.field_datetime_range_timezone

![Date_and_time_settings_for_Event___VA_gov_CMS](https://user-images.githubusercontent.com/643678/128700945-679e9a27-08f8-4293-8aa4-580f209cb95b.png)

### Confusing multivalue UX

![Create_Event___VA_gov_CMS](https://user-images.githubusercontent.com/643678/128697958-7cbc3343-3ca7-4d8c-8127-a0096641a8f6.png)

### Desired permissions

![Permissions_filtered_by_modules___VA_gov_CMS](https://user-images.githubusercontent.com/643678/128700508-3ca3dae5-08e7-4c4b-9553-4dbdad3de57e.png)

</details>

## Acceptance Criteria
- [x] Recurring events are enabled set to max out at 12 months (setting on field)
- [x] Field help text is removed (for now, at least)
- [x] Enabled time zones match the time zones currently seen at /node/add/event, _plus_ Europe/Berlin
- [x] Permissions are set so that content content editors/reviewers/publishers and content admins are able to use the module 
- [x] "Add another item" is hidden on the event form when smart_date_recur is enabled
- [x] If #6055 has shown that we can change cardinality of field_datetime_range_timezone  without impacting existing graphql or FE templates, this can potentially be merged
- [ ] If #6055 has shown that changing cardinality of field_datetime_range_timezone will break the content API, then just create a PR assuming that's been done elsewhere and mark as DO NOT MERGE. 

## Design principles

Which [CMS design principle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/cms-product-design-principles.md) is at play?
- [ ] Purpose-driven: Creates an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [x] Efficient: Removes distractions and create clear, straightforward paths to get the job done.
- [x] Approachable: Offers friendly guidance over authoritative instruction.
- [x] Consistent: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] Empowering: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Core Application Team`
- [x] `Product Support Team`

**Comment by kevwalsh** [comment]
Notes from Jan 13.

**Still to do**

- Repeat every month on the X date of the month
- Manage instances
- Hide all day (if FE doesn’t handle it)
- Is all day boolean available in graphql?
- URL field is external only, should be internal or external. 
- “On the” field group should remain the same distance 
- Show “Edit event series” as disabled before save. 
- Until field should be limited to the next 12 months - in the javascript and in form validation.
- Start date should be limited to the next 12 months - in the javascript and in form validation.
- Error message (need better writing): "you can only create events up to a year in the future. " "You can only repeat events up to a year in the future. "

**Unrelated to dates and recurring events**
Make URL field required if CTA label is not Null.

**Comment by swirtSJW** [comment]
I am pretty sure this should be Closed with the merge of this into integration-recurring-events.
