### ISSUE TITLE
improve team member onboarding process/documentation

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#6064]
## User story
As a new VFS-CMS team member, I need to know what information, processes, and people are important to understand as I onboard.

## Acceptance criteria
- [x] assess current state of onboarding documentation
- [x] make recommendations for improvement
- [x] implement improvements and make available

**Comment by rachel-kauff** [comment]
Adding a comment here to remind myself to add some design onboarding artifacts from last time

**Comment by xiongjaneg** [comment]
steal ideas from https://github.com/CDCgov/prime-reportstream/wiki/CDC-PRIME-New-Team-Member-Onboarding-Hub

**Comment by xiongjaneg** [comment]
Slack etiquette

**Comment by xiongjaneg** [comment]
include product videos https://dsva.slack.com/archives/CT4GZBM8F/p1629140427431700

**Comment by xiongjaneg** [comment]
tempate at https://github.com/department-of-veterans-affairs/va.gov-cms/blob/master/.github/ISSUE_TEMPLATE/cms-team-member-onboarding.md
