### ISSUE TITLE
Create content types for 3 VAMC top task pages

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#6071]
## User Story or Problem Statement

As a Veteran, i want high quality, plain language, proven content to help me accomplish top tasks.

As a VAMC national editor, i want to manage nationally-standardized content in one place and have that be used as source of truth across all VAMC sites.

## Acceptance Criteria

For each of the following three content types: `vamc_system_register_for_care`, `vamc_system_medical_records_offi`, and `vamc_system_billing_insurance`:

- [x] Create content type
- [x] Enable all the VAMC menus for each type
- [x] No authoring information visible on the form
- [x] Force menu item enabled (all nodes of these content types must have menu items)
- [x] Standard fields, as per drupal spec tool
  - [x] Add field_enforce_unique_combo field where so that only one node of each content type can reference the same field_office, or the same field_administration
  - [x] Section (`field_administration`) in a Section fieldset, right sidebar, to match the way this is done on other content types
  - [x] VAMC System (field_office) 
- [x] Enable standard content moderation
- [x] Enable workbench access for Section
- [x] Permissions to match vamc_system_policies_page: Only content_admin can create or delete, but content editor can edit/review/publish/archive (we'll removing archiving later).
- [x] Meta tag config
  - [x] Meta title tag fields (including set to `[node:title] | [node:field_office] | Veterans Affairs`    
  - [x] Meta image fields (og:image, twitter_card:image) set to `[node:field_office:entity:field_media:entity:image:entity:3_2_medium_thumbnail:url]`
  - [x] Meta description specific to each content type (see below)
- [x] Create new pathauto pattern "VAMC root page"
  - [x] Pattern `[node:field_office:entity:url:path]/[node:title]`
  - [x] Apply to these three content types, as well as VAMC System Policies Page
  - [x] Delete VAMC System Polices Page pathauto pattern

Settings specific to each content type
- [x] `vamc_system_register_for_care`
  - [x] auto entity label has been set to "Register for care"
  - [x] Meta description: "You can pay your [node:field_office] bill online, by phone, mail, or in person."
- [x] `vamc_system_medical_records_offi`
  - [x] auto entity label has been set to "Medical records office"
  - [x] Meta description: "Get copies of your VA medical records online, by mail or fax, or in person at our [node:field_office] Release of Information office."
- [x] `vamc_system_billing_insurance`
  - [x] auto entity label has been set to "Billing and insurance"
  - [x] Meta description: "You can pay your [node:field_office] bill online, by phone, mail, or in person."

We'll have followup issues for adding fields (both EFF and non-EFF) to each content type, but this will unblock FE and some other work.

## Design principles

Which [CMS design principle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/cms-product-design-principles.md) is at play?
- [ ] Purpose-driven: Creates an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [x] Efficient: Removes distractions and create clear, straightforward paths to get the job done.
- [ ] Approachable: Offers friendly guidance over authoritative instruction.
- [ ] Consistent: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] Empowering: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Core Application Team`
- [x] `Product Support Team`

**Comment by cmaeng** [comment]
@ethanteague is this blocked or is it blocking something? @kevwalsh mentioned before he left that this was done but further content modeling was blocking "everything else". not sure what everything else entails, FE work? stuff on our side? thanks

**Comment by ethanteague** [comment]
Just recapping what @cmaeng and I discussed on our zoom chat: this will be merged in, today.
