### ISSUE TITLE
[SPIKE] Define notification levels and alerting for each current CMS application notification

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-cms#6075]
## Description

As a CMS devops engineer, I need to be notified when important events occur in a consistent manner, so that I trust notifications that occur and can take immediate appropriate action.

## Acceptance Criteria

- [x] List current notifications and determine [appropriate level](https://richjenks.com/psr-3-log-level-descriptions/) for each notification
- [x] Determine and document appropriate alerting strategy for each notification level
- [x] Tag @mchelen-gov for review of documentation generated
- [x] Follow-on issues have been created for required changes to notifications & alerting

**Comment by acrollet** [comment]
@ElijahLynn @ndouglas @indytechcook @olivereri Hey team! Can you please add your [planning poker estimates with ZenHub](https://app.zenhub.com/workspaces/VAgov-CMS-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/6075?planning-poker)

**Comment by acrollet** [comment]
(Let's map PSR-3 levels to datadog levels during this session)

**Comment by ElijahLynn** [comment]
Another thought - just put them into "critical" and "noncritical" buckets somehow and keep it simple to start with.

**Comment by mchelen-gov** [comment]
Reference: Drupal log levels from https://datatracker.ietf.org/doc/html/rfc5424
```
Numerical              Severity
Code

  0       Emergency: system is unusable
  1       Alert: action must be taken immediately
  2       Critical: critical conditions
  3       Error: error conditions
  4       Warning: warning conditions
  5       Notice: normal but significant condition
  6       Informational: informational messages
  7       Debug: debug-level messages
```

---

@ElijahLynn having 2 buckets would be fine, maybe something like:

critical
```
  0       Emergency: system is unusable
  1       Alert: action must be taken immediately
  2       Critical: critical conditions
```

non-critical
```
  3       Error: error conditions
  4       Warning: warning conditions
  5       Notice: normal but significant condition
  6       Informational: informational messages
  7       Debug: debug-level messages
```


---

if we want to get a little more granular the groups could be:

PD + slack @here
```
  0       Emergency: system is unusable
  1       Alert: action must be taken immediately
  2       Critical: critical conditions
```

slack @here
```
  3       Error: error conditions
```

slack message
```
  4       Warning: warning conditions
  5       Notice: normal but significant condition
```

no alerts
```
  6       Informational: informational messages
  7       Debug: debug-level messages
```

**Comment by indytechcook** [comment]
Ability to set downtimes in datadog: https://docs.datadoghq.com/monitors/downtimes/?tab=bymonitorname

**Comment by acrollet** [comment]
Meeting scheduled for Sep 9 @ 12 ET

**Comment by ElijahLynn** [comment]
https://access.redhat.com/support/policy/severity

**Severity 1 (urgent)**
A problem that severely impacts your use of the software in a production environment (such as loss of production data or in which your production systems are not functioning). The situation halts your business operations and no procedural workaround exists.

**Severity 2 (high)**
A problem where the software is functioning but your use in a production environment is severely reduced. The situation is causing a high impact to portions of your business operations and no procedural workaround exists.

**Severity 3 (medium)**
A problem that involves partial, non-critical loss of use of the software in a production environment or development environment. For production environments, there is a medium-to-low impact on your business, but your business continues to function, including by using a procedural workaround. For development environments, where the situation is causing your project to no longer continue or migrate into production.

**Severity 4 (low)**
A general usage question, reporting of a documentation error, or recommendation for a future product enhancement or modification. For production environments, there is low-to-no impact on your business or the performance or functionality of your system. For development environments, there is a medium-to-low impact on your business, but your business continues to function, including by using a procedural workaround.

**Comment by indytechcook** [comment]
| Level  | Action                                         | Drupal Level               |
|--------|------------------------------------------------|----------------------------|
| Urgent | PagerDuty Critical >> Slack #cms-notifications | Emergency, Alert, Critical |
| High   | @here in Slack                                 | Error                      |
| Medium | Slack                                          | Warning, Notice            |
| Low    | None                                           | Informational, Debug       |

**Comment by indytechcook** [comment]
First iteration:

| Source                         |                                          | Support Severity Level |
|--------------------------------|------------------------------------------|------------------------|
| GraphQL Test                   | Uses a synthetic monitor in Datadog      | High                   |
| JSD Widget                     | Uses a synthetic monitor in Datadog      | Medium                 |
| Drupal Warning                 | Drupal to Sentry to Datadog to Slack     | Medium                 |
| Drupal Error                   | Drupal to Sentry to Datadog to Slack     | High                   |
| Drupal Critical                | Drupal to Sentry To Datadog to PagerDuty | Urgent                 |
| Drupal Info                    | Not Sent to Sentry                       | Low                    |
| Drupal Alert                   | Drupal to Sentry To Datadog to PagerDuty | Urgent                 |
| Drupal Notice                  | Drupal to Sentry To Datadog to Slack     | Medium                 |
| Drupal Debug                   | Not Sent to Sentry                       | Low                    |
| Drupal Emergency               | Drupal to Sentry To Datadog to PagerDuty | Urgent                 |
| TeamSite Facility Status       | Datadog to Slack                         | Medium                 |
| Prod CMS Down                  |                                          | Urgent                 |
| Drupal Post Content Webhook    | GovDelivery                              | High                   |
| Drupal Flag List               |                                          | High                   |
| Content Buidl Fails            |                                          | High                   |
| FormsAPI                       |                                          |                        |
| Health Service Descriptiosn    |                                          |                        |
| Drupal Post Content Webhook    |                                          |                        |
| Tugboat Base Prevew Accessible |                                          |                        |
| Tugoboat Server Resource       |                                          |                        |
| GovDeliveryAPI                 | Trigger Drupal Error                     | High                   |
| Periodic Job in Jenkins        | Jenkins to Slack                         | Medium                 |
| Daily Job in Jenkins           | Jenkins to Slack                         | Medium                 |
| Prod Deploy Failure            | Jenkins to Slack                         | High                   |
| Non-Prod Deploy Failures       | Jenkins to Slack                         | Medium                 |
| Non-Prod CMS Down              |                                          | Medium                 |
| Stage Test Failures            | Jenkins to Slack                         | High                   |

**Comment by indytechcook** [comment]
Logged https://github.com/department-of-veterans-affairs/va.gov-cms/issues/6360 for following up on the `flag_list` endpoint.

**Comment by indytechcook** [comment]
https://github.com/department-of-veterans-affairs/va.gov-cms/blob/master/READMES/notificaiton-levels.md Created

**Comment by indytechcook** [comment]
@mchelen-gov The doc is ready for your review: https://github.com/department-of-veterans-affairs/va.gov-cms/blob/master/READMES/notificaiton-levels.md

**Comment by jefflbrauer** [comment]
@mchelen-gov Based on the convo yesterday, can we move this to accepted?
