### ISSUE TITLE
Entering an event date in the past generates WSOD

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-cms#6078]
**Describe the defect**
Entering an event date before 1970 generates the following error:

```
Drupal\Core\Database\DatabaseExceptionWrapper: SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column 'field_datetime_range_timezone_value' at row 1: INSERT INTO {node__field_datetime_range_timezone} ("entity_id", "revision_id", "bundle", "delta", "langcode", "field_datetime_range_timezone_value", "field_datetime_range_timezone_end_value", "field_datetime_range_timezone_duration", "field_datetime_range_timezone_rrule", "field_datetime_range_timezone_rrule_index", "field_datetime_range_timezone_timezone") VALUES (:db_insert_placeholder_0, :db_insert_placeholder_1, :db_insert_placeholder_2, :db_insert_placeholder_3, :db_insert_placeholder_4, :db_insert_placeholder_5, :db_insert_placeholder_6, :db_insert_placeholder_7, :db_insert_placeholder_8, :db_insert_placeholder_9, :db_insert_placeholder_10); Array ( [:db_insert_placeholder_0] => 33514 [:db_insert_placeholder_1] => 507159 [:db_insert_placeholder_2] => event [:db_insert_placeholder_3] => 0 [:db_insert_placeholder_4] => en [:db_insert_placeholder_5] => -3832653838 [:db_insert_placeholder_6] => -3832563838 [:db_insert_placeholder_7] => 1500 [:db_insert_placeholder_8] => [:db_insert_placeholder_9] => [:db_insert_placeholder_10] => America/New_York ) in Drupal\Core\Entity\Sql\SqlContentEntityStorage->saveToDedicatedTables() (line 1380 of /var/www/cms/docroot/core/lib/Drupal/Core/Entity/Sql/SqlContentEntityStorage.php).
```

**To Reproduce**
1. Create a new `event` node
2. Enter a start or end date in the "Date and time" field that is before 1970
3. WSOD

**Expected behavior**
No WSOD should occur

**Screenshots**

![Screen Shot 2021-08-10 at 11 05 34 AM](https://user-images.githubusercontent.com/101649/128913413-df81f7b3-6c0e-414d-9e88-2158f73fb10a.png)

**Additional context**
Reported [in slack](https://dsva.slack.com/archives/CT4GZBM8F/p1628618845265600)

## Acceptance Criteria

- [ ] Editors cannot cause a WSOD by entering dates in the past
- [ ] Upstream issue is located or created on drupal.org

**Comment by acrollet** [comment]
@ElijahLynn @ndouglas @indytechcook @olivereri Hey team! Can you please add your [planning poker estimates with ZenHub](https://app.zenhub.com/workspaces/VAgov-CMS-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/6078?planning-poker)

**Comment by jilladams** [comment]
Iceboxing. 2 yo issue, no reports ever in Prod. If this arises IRL, we can address.

**Comment by FranECross** [comment]
Closing as a no-op per the above note.
