### ISSUE TITLE
`The "views_block:taxonomy_term-block_1" was not found` Error in Sentry

### ISSUE THREAD

**Issue by indytechcook** [department-of-veterans-affairs/va.gov-cms#6086]
## Description

There is an error in sentry which needs to be investigated.

Details about the error are found on sentry:
http://sentry.vfs.va.gov/organizations/vsp/issues/45313/?project=14&query=is%3Aunresolved+environment%3Acms-prod

`The "views_block:taxonomy_term-block_1" was not found`

## Acceptance Criteria

- [ ] Either fix the root cause of the error within the timebox or create a follow-on issue

**Comment by acrollet** [comment]
@ElijahLynn @ndouglas @indytechcook @olivereri Hey team! Can you please add your [planning poker estimates with ZenHub](https://app.zenhub.com/workspaces/VAgov-CMS-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/6086?planning-poker)

**Comment by acrollet** [comment]
Let's timebox investigation to ~1/2 day, fix if possible in that time and create a follow-on if not.

**Comment by TheBoatyMcBoatFace** [comment]
Issue not found in Sentry. Reopen if discovered.
