### ISSUE TITLE
Error thrown on backend in decoupled Behat test

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-cms#6093]
## Description
A followup to #4676, as part of our newly-minted effort to root out and destroy the sources of spurious errors caused by our automated tests.

<img width="1447" alt="Screen Shot 2021-08-11 at 3 19 55 PM" src="https://user-images.githubusercontent.com/1318579/129090611-1cdc1e10-4cf2-4f9b-99c1-b067af08332f.png">

This error is thrown in response to the test in `decoupled.feature`.

Possibly related to [this](https://www.drupal.org/project/drupal/issues/3035589).

## Acceptance Criteria
- [ ] No PHP errors occur when running this test.

### CMS Team
- [x] `Core Application Team`
- [ ] `Product Support Team`

**Comment by acrollet** [comment]
@ElijahLynn @ndouglas @indytechcook @olivereri Hey team! Can you please add your [planning poker estimates with ZenHub](https://app.zenhub.com/workspaces/VAgov-CMS-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/6093?planning-poker)
