### ISSUE TITLE
Fix sending email on Tugboat and Lando

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-cms#6100]
## Description
See [this Slack thread](https://dsva.slack.com/archives/C01A35JDH88/p1628708956004900).

As a developer, it'd be nifty if I could send email so I could verify that mail can be sent.

Email does not appear to be working on Tugboat or Lando, but does work on BRD.

Email can be sent (and is captured appropriately) from the command line through PHP:
```bash
drush eval 'mail("nathan.douglas@agile6.com", "drush eval", "");'
```

and from calling Drupal services directly:
```bash
drush eval '\Drupal::service("plugin.manager.mail")->mail("nug_doug", "nug_doug_key", "nathan.douglas@agile6.com", "en", ["message" => "", "title" => "service"], NULL, TRUE);'
```

But there seems to be a breakdown at some point that prevents email from being sent for e.g. password-reset requests.  This should be identified and solved.

## Acceptance Criteria
- [ ] Email can be sent (and is captured by Mailhog) when we attempt to send email through Drupal from Lando.
- [ ] Email can be sent (and is captured by Tugboat) when we attempt to send email through Drupal from Tugboat environments.

### CMS Team
- [x] `Core Application Team`
- [ ] `Product Support Team`

**Comment by ndouglas** [comment]
hmm

<img width="844" alt="Screen Shot 2021-08-12 at 11 20 12 AM" src="https://user-images.githubusercontent.com/1318579/129223136-3a1e3524-29d0-464f-bde7-d2c227d01133.png">

**Comment by ndouglas** [comment]
whee, so:

From `_user_mail_notify()` in `user.module`:

<img width="1032" alt="Screen Shot 2021-08-12 at 1 13 39 PM" src="https://user-images.githubusercontent.com/1318579/129239597-1a64ada6-7ddd-490b-902e-59826f1b3dc2.png">

That's gonna fail if the user doesn't have an email address associated with their account.  As mine doesn't.

I injected the following code in `Drupal\Core\Mail\Plugin\Mail\PhpMail::mail(), right before `\mail()` is called:

```php
      \Drupal::logger('lol')->error(json_encode([
        'to' => $message['to'],
        'subject' => $mail_subject,
        'body' => $mail_body,
        'headers' => $mail_headers,
        'additional_headers' => $additional_headers,
      ], JSON_PRETTY_PRINT));
```

Before setting an email address on my account:
<img width="1203" alt="Screen Shot 2021-08-12 at 1 06 40 PM" src="https://user-images.githubusercontent.com/1318579/129239892-ea8ad7d9-8fce-44bc-a7ee-adafdd563009.png">

After setting an email address on my account:
<img width="1177" alt="Screen Shot 2021-08-12 at 1 07 27 PM" src="https://user-images.githubusercontent.com/1318579/129240278-4ac436e3-f439-457f-a8e1-b4e2b3cd6e7b.png">

I'd recommend that we write a script to update all users to set their email address equal to their account name, if it's not already set and the account name is a valid email address, and check to make sure we always set the email address specifically.

**Comment by ndouglas** [comment]
Gonna close this as invalid; @acrollet @ElijahLynn thoughts on where I might document this?  I was thinking about adding a README for gotchas/troubleshooting the local/tugboat dev process.

**Comment by acrollet** [comment]
> Gonna close this as invalid; @acrollet @ElijahLynn thoughts on where I might document this? I was thinking about adding a README for gotchas/troubleshooting the local/tugboat dev process.

@ndouglas what if we add a line on the existing local and tugboat readmes? IMO we already have so many READMEs that it's hard to know what's where...

**Comment by ndouglas** [comment]
Yeah, I think you're right.
