### ISSUE TITLE
Remove operating status endpoint for Salisbury, Salem, Houston, Pacific Islands

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#6151]
## Acceptance Criteria
- [ ] Enpoint removed for Salisbury, Salem, Houston, Pacific Islands
- [ ] Merged for CMS deploy on Tuesday Aug 24. 

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Core Application Team`
- [x] `Product Support Team`

**Comment by cmaeng** [comment]
Fayetteville Coastal, New York Harbor, and Bronx were pushed back per VAMC Upgrade sync on 8/20 and need to be added back in. tbd on dates for those.
