### ISSUE TITLE
`moderationState` is no longer available in GraphQL response

### ISSUE THREAD

**Issue by indytechcook** [department-of-veterans-affairs/va.gov-cms#6177]
## Description

We used to be able to add the `moderationState` field to a GraphQL query.

Field returns on tugboat: https://master-ldij0hdlillzgrlzsgjk8keqbcknof2i.demo.cms.va.gov/graphql/explorer
Example Query:
```
{
  nodeById(id: "736") {
    entityBundle
    entityId
    title
    reverseFieldListingNode(limit: 500, filter: 
      {conditions: 
        [
          {field: "type", value: "event"},
          {field: "moderation_state", value: "archived", operator: NOT_EQUAL}          
        ]},
      sort: {field: "changed", direction: DESC}) {
      entities {
        ... on NodeEvent {
          title
          status
          moderationState
          fieldDatetimeRangeTimezone {
            value
          }
        }
      }
    }
  }
}
```

Previous investigation found that the GraphQL Schema plugin is not seeing the `moderationState` as a field.

Slack discussion https://dsva.slack.com/archives/CT4GZBM8F/p1629236881012800

## Acceptance Criteria
- [ ] Further investigation into the core/contrib functionality is timeboxed to 1/2 day
- [ ] If investigation does not reveal root cause, add this functionality via a plugin
- [ ] `moderationState` should be available to added as a field to a Node query in GraphQL
- [ ] A functional test confirms that the field can be queried via GraphQL

**Comment by acrollet** [comment]
@ElijahLynn @ndouglas @indytechcook @olivereri Hey team! Can you please add your [planning poker estimates with ZenHub](https://app.zenhub.com/workspaces/VAgov-CMS-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/6177?planning-poker)

**Comment by ElijahLynn** [comment]
Would be good to get a timestamp on when this started happening for bisecting.

**Comment by ElijahLynn** [comment]
@indytechcook said he did a bunch of work on this already so make sure to sync with him upon starting.
