### ISSUE TITLE
Remove Aug 31  status endpoints durham, central iowa, iowa city, hampton, fayetteville arkansas 

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#6185]
## Acceptance Criteria
- [ ] endpoints are removed from facility status migration

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Core Application Team`
- [x] `Product Support Team`

**Comment by kevwalsh** [comment]
Closing this even though these VAMCS are not launched, we are adopting a new process to remove endpoints post prod launch because of ever-changing launch dates.
