### ISSUE TITLE
Add monitoring & alerting for cms.va.gov internal DNS

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-cms#6221]
## Description

As a CMS devops engineer, I need to know when internal DNS queries for CMS URLs are failing, so that I can take immediate corrective action.

ref: https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Postmortems/2021-08-23-cms-and-vfs-dns-zones-outage.md

## Implementation

https://www.datadoghq.com/blog/monitor-dns-with-datadog/ may be a useful approach

## Acceptance Criteria
- [x] DNS query for a '.cms.va.gov' URL is checked 1x/minute with 2 retries
- [x] CMS team is alerted on failure with a clear message including information on what likely needs to be fixed

**Comment by ndouglas** [comment]
Created [here](https://app.datadoghq.com/synthetics/details/2va-b5r-txu) and it looks good so far.
<img width="1611" alt="Screen Shot 2021-09-09 at 10 50 47 AM" src="https://user-images.githubusercontent.com/1318579/132708719-6e349799-669b-4240-8cd0-95d3d9c8a24f.png">

Criteria:
<img width="614" alt="Screen Shot 2021-09-09 at 10 50 53 AM" src="https://user-images.githubusercontent.com/1318579/132708531-e0ed244a-c4c1-474f-b268-c8000052ea41.png">

Message:
<img width="543" alt="Screen Shot 2021-09-09 at 10 51 21 AM" src="https://user-images.githubusercontent.com/1318579/132708611-29d24bb5-effe-4c67-bbf4-474d2f980362.png">

I wanted to provide a message IAW the ACs but also not lead anyone down a garden path if the issue's elsewhere.  Happy to rephrase if anyone has any suggestions.

Seems critical, so I marked it critical.

DNS resolution is only from us-gov-west-1, where it succeeds:
<img width="1580" alt="Screen Shot 2021-09-09 at 10 42 11 AM" src="https://user-images.githubusercontent.com/1318579/132708935-ae29f601-4262-45ec-9b26-f6258e752520.png">

and not from outside, where it fails:
<img width="1447" alt="Screen Shot 2021-09-09 at 10 41 50 AM" src="https://user-images.githubusercontent.com/1318579/132709094-b94fac58-fbe0-44f4-9fe2-4300375bfe6f.png">

The criteria seemed reasonable to me -- the first regex check for _every_ A record might be unnecessary.  Happy to change/extend any of this if there are complaints.

**Comment by indytechcook** [comment]
This looks good to me

**Comment by indytechcook** [comment]
though, I'm not great at regex...

**Comment by ndouglas** [comment]
I wrote it for ease of editing more than correctness.  It'd match on a string like "10.999.999.999", which obv isn't a valid IP address, but I figure if something goes wrong it's going to either not have an A record or it's going to be some IP outside 10/8, which ATM anyway would be a sign that something weird has happened.  Actually trying to match 0-255 with a regex is a PITA 😃

**Comment by acrollet** [comment]
👍 👍 👍
