### ISSUE TITLE
Onboarding: Stefanie Gray

### ISSUE THREAD

**Issue by stefaniefgray** [department-of-veterans-affairs/va.gov-cms#6224]
# Welcome to the VFS-CMS Team! 👋
We're thrilled to have you join us on this journey! 🎆🎉🙌

Our vision is to build and maintain a best-in-class Content Management System that meets the needs of editors, application development teams, and consuming applications in order to empower our users to help Veterans.

The onboarding materials below are organized by 1) chronological time to complete (day one, week one, week two, month one); and main category (why, how, who, what). There's a lot to digest but don't worry, your delivery manager will guide you and we'll also pair you up with someone from your workstream to help with specific things related to your discipline (UX, DevOps, Drupal Engineering, etc). In addition, you'll have the support of the entire team, who have all gone through this process before and are eager to answer any questions that arise. Come back to this ticket any time to refresh your knowledge on a specific topic covered below.

Have fun and we look forward to getting to know you! 😊

Projected start date: August 23rd, 2021

### How?
- [x] Read through our [team norms](https://docs.google.com/document/d/1cs5FePhtR0LIJi63b9ZtqT7T6dphgB584UpfEbejSOc/edit#), which will also give an overview of how we apply the [USDS playbook](https://playbook.cio.gov/) and VA.gov platform [code of conduct](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/policies-work-norms/code-of-conduct.md).
### Who?
- [x] Who's on the VFS-CMS team? Discuss with your delivery manager.
### What?
- [x] Contract - Discuss with your delivery manager.
- [x] Read the [VA.gov platform mission and goals](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/onboarding/library/VA.gov%20Platform%20Overview%202021.pdf).
- [x] [Onboarding questionnaire](https://docs.google.com/document/d/17fWcL-5p4T3H7dT2bbw02u_CHEZ0tDlszcoMVLfRqP4/edit) (what do you already know in regards to tooling, context, history, etc)

## Week one
The goals of this week are: 1) get background paperwork completed as quickly as possible and 2) start gaining context for what we're doing and why
### Why?
- [x] Why is VA.gov using Drupal CMS and how is our success measured? Read the [objectives and key results](https://va-gov.atlassian.net/wiki/spaces/VAGOV/pages/96698383/Product+CMS).
- [x] Why are Vet Centers important to Veterans? Watch the [2-minute YouTube video](https://www.youtube.com/watch?v=VMzkZNbKk1I).
- [x] Why are VA Medical Centers changing their websites? Watch the [2-minute YouTube video](https://youtu.be/Xrv5wCv6cKY).
### How?
- [x] [How does the VFS-CMS team work in an agile environment?](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/onboarding/library/sprint-best-practices.md)
- [x] How do Agile 6 and Civic Actions work together on this project? Discuss with your delivery manager or product manager.
- [ ] [How do you get secure access to the VA systems you need?](https://va-gov.atlassian.net/wiki/spaces/VAGOV/pages/491554/Security+onboarding+process) Complete the following paperwork and submit them to the security officer.
  - [ ] Moderate Risk Position Questionnaire- AQFPT
  - [x] Background Investigation Request (BI_REQ)
  - [x] Contractor Rules of Behavior (CROB)
  - [ ] Declaration of Federal Employment (306)
  - [x] NDA Non-Disclosure Agreement
  - [x] PIV Fingerprint Request Form
  - [x] Request for New Special Agreement Check (SAC request)
  - [x] Self-Certification of Continuous Service (SIC Self Verif)
  - [ ] 0710_Release of Information Form
 - [x] A6: How do you charge time or costs to the project? Discuss with your delivery manager or Finance AVP.
### Who?
- [x] Who is on the VFS-CMS team? Read your [team members' user manuals and create your own](https://drive.google.com/drive/u/0/folders/195otsT1IUxi_k8oEU21TUkvEG-6p5YQj?ths).
- [x] Ensure that your info on the [official team roster](https://va-gov.atlassian.net/wiki/spaces/VAGOV/pages/185270337/Team+Roster+2021) is correct.
- [x] Let's start introducing you to the team and key stakeholders. If you're on a meeting where you don't know someone, feel free to kickstart an introduction. Everyone in the ecosystem is friendly and interested in connecting.

## Week two
The goal for this week is to get you set up with the tools you need to be successful. We will pair you up with a buddy on the project that is in your same discipline to help inform which ones are relevant and which aren't. The most important thing is to get set up is SOCKS as it will give you access to our systems so try to prioritize that.
### What products do we support?
The following trainings and additional videos can be found on the Knowledge Base on the Drupal CMS prod and lesser environments that require VA network or SOCKS proxy access. They can be watched without VA network or SOCKS access at the links below.
- [x] [Review the editor onboarding slides](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/onboarding/library/https___prod.cms.va.gov_sites_default_files_2021-07_Welcome%2520to%2520the%2520new%2520VA.gov%2520CMS.pdf).
- [x] [Watch the Drupal CMS editorial experience video for all users](https://youtu.be/ju7EH0F5S4I).
- [x] [Watch the training video that VA Medical Center (VAMC) editors have to complete](https://youtu.be/Sowgt1rOmlE).
- [x] [Watch the training video that Vet Center editors have to complete](https://youtu.be/scuC5lSHZuw).
- [x] [Watch the training video that Campaign Landing Page editors have to complete](https://youtu.be/RcrOLEvL0xQ).
- [x] Read the [product sheets](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/VA-CMS-Product-Sheets.pdf).
#### All users
 - [x] What do I need to know about my discipline on this team (DevOps, Engineering, Helpdesk, ID, UX)? Discuss with the discipline lead.
 - [x] What applications do you need access to? Discuss with the discipline lead.
 - [x] [VA.gov tools overview](https://depo-platform-documentation.scrollhelp.site/getting-started/Request-access-to-tools.969605215.html)
 - [x] [Slack](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/orientation/slack-requests.md) for instant messaging
   - [x] Please use [Slack etiquette](https://slack.com/blog/collaboration/etiquette-tips-in-slack).
 - [x] Github for issue tracking and document sharing
    - [x] [VA.gov request instructions](https://github.com/department-of-veterans-affairs/github-user-requests/issues/new?labels=add-user-to-org%2C+new-user%2C+user-created&template=add-user-to-the-va-organization.md&title=ADD+USER+TO+ORG+-+%5BUSERNAME%5D)
    - [x] [CMS team list](https://github.com/orgs/department-of-veterans-affairs/teams/vfs-cms-team/members) - get added
    - [x] [Zenhub extension instructions](https://www.zenhub.com/extension)
 - [x] [SOCKS proxy request](https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html) to access VA network tools until you get a PIV card
 - [ ] [Citrix Access Gateway instructions](https://www.oit.va.gov/resources/remote-access/index.cfm?) for after you get your PIV card
 - [x] [Confluence](https://va-gov.atlassian.net/wiki/spaces/VAGOV/pages/179765342/2020-2021?NO_SSR=1) for team resources and calendar
 - [x] [Google Drive](https://drive.google.com/drive/u/0/folders/0ADx85_gnl3Y4Uk9PVA?ths=true) for team documents. Generally, VA doesn't use Google products. Use Github or downloadable files when sharing with VA.
 - [x] [Trello](https://trello.com/vacmsteam)
 - [ ] Tugboat

#### Helpdesk
 - [x] [Review the helpdesk Github repo](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/cms/helpdesk).
 - [x] [Review the helpdesk Google Drive](https://drive.google.com/drive/folders/1opC6DgZyBQ6uEVzIz3FWmISMLt-Y91ts).
 - [x] [Jira Service Desk](https://va-gov.atlassian.net/jira/servicedesk/projects/VAHELP)

### When?
- [x] Check your calendar for invitations to team ceremonies.
  - [x] Scrums
  - [x] Planning sessions
  - [x] Refinement sessions
  - [x] Demos
  - [x] Retros
 
## Month one
By this point you should have enough context and access to be able to start contributing. Work with your team to identify specific issues to focus on.
### Who?
- [x] Who are our VA points of contact? Discuss with your delivery manager or product manager.
- [x] Who should we know on the platform teams? Discuss with your delivery manager or product manager.
### What?
- [x] [What is Drupal?](https://docs.google.com/spreadsheets/d/11ppWiIggKJh-YAWia28utZXW48tJZGCEg-sFJ6eIl9c)
- [x] [Google Analytics](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=joanneesteban%2C+bsmartin-ep%2C+jonwehausen&labels=analytics-insights%2C+analytics-request&template=analytics-request-google-analytics-access.md&title=Request+access+to+Google+Analytics)
 - [x] [Opt out](https://www.va.gov/analytics-opt-out.html) of GA collection.
 - [ ] [Learn Drupal from an editor's perspective](https://prod.cms.va.gov/help/get-training).

### What?
- [ ] Mainly for helpdesk folks: [CMS Support distro group](https://mim.va.gov/IdentityManagement/default.aspx)

**Comment by cmaeng** [comment]
@stefaniefgray  this looks pretty much done. feel free to close out if you agree. you can always reference back to it as needed.
