### ISSUE TITLE
[SPIKE] Determine uptime commitments

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-cms#6237]
## Background

As a CMS engineer, I need to know what uptime commitment is required for public VA content, so that I can choose appropriate infrastructure and monitoring solutions

## Implementation

- Match or exceed Lighthouse uptime commitment?
- What does HA mean in our context?
  - no single points of failure?
  - AWS AZ redundancy?
  - ...

## Acceptance Criteria

- [ ] Uptime commitment is documented and linked from this issue
- [ ] Definition of what HA means in the context of the CMS application is determined and documented on #4459

**Comment by jefflbrauer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VAgov-CMS-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/6237?planning-poker) with ZenHub @ElijahLynn @indytechcook @ndouglas @olivereri @timcosgrove

**Comment by jefflbrauer** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VAgov-CMS-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/6237?planning-poker) with ZenHub @cweagans

**Comment by timcosgrove** [comment]
This was written for Public API. We will reopen a similar ticket if/when we plan for a Public API.
