### ISSUE TITLE
[SPIKE] How might we support zero downtime deployments?

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-cms#6238]
## Background

As a CMS devops engineer, I want to be able to deploy code at any time without causing downtime, so that the CMS can continue to serve requests to users during deployments.

## Acceptance Criteria

- [ ] The devops team and other interested participants have met and discussed an optimal approach for zero downtime, read-only deployments
- [ ] Approach is documented and linked from this issue

**Comment by ElijahLynn** [comment]
The main goal here is to have zero downtime for GET requests to the CMS API. Editors may still have downtime and not be able to edit content during the deployment.

**Comment by TheBoatyMcBoatFace** [comment]
Handled by #11839
