### ISSUE TITLE
High availability for RDS

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-cms#6239]
## Background

As a CMS devops engineer, I need the RDS service to be highly available, so that a failure to one RDS instance cannot cause downtime for the CMS.

## Acceptance Criteria

- [ ] Any RDS instance may be disabled without causing CMS downtime

**Comment by jefflbrauer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VAgov-CMS-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/6239?planning-poker) with ZenHub @ElijahLynn @indytechcook @ndouglas @olivereri @timcosgrove

**Comment by jefflbrauer** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VAgov-CMS-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/6239?planning-poker) with ZenHub @cweagans

**Comment by timcosgrove** [comment]
This is not relevant to the current understanding of AP work. It will be revisited when we plan for Public API, or done with the work of moving CMS to EKS.
