### ISSUE TITLE
Create OpenAPI spec and provide to the Lighthouse team

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-cms#6246]
## Background

As a CMS engineer, I need to create an OpenAPI specification for the Drupal JSON Api and provide it to the Lighthouse team, so that a Lighthouse sandbox environment can be provided.

## Acceptance Criteria

- [x] OpenAPI Specification (or documentation on how to generate one if it is automated) is added under https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/cms/public-content-api or the CMS docs folder as appropriate and linked here

**Comment by indytechcook** [comment]
Open API spec is a living document and currently lives in this URL: https://pr6265-lkoslgyagkodlmzq41fgzass01ozbvla.ci.cms.va.gov/openapi/jsonapi

This is documented in the `json-api.md` file in the `READMES` direction in: https://github.com/department-of-veterans-affairs/va.gov-cms/pull/6265

**Comment by indytechcook** [comment]
The OpenAPI module only provides V2 version.  Lighthosue requires V3 so this isn't done yet.

**Comment by indytechcook** [comment]
https://github.com/department-of-veterans-affairs/va.gov-cms/pull/6265 contains code to generate the JSON API and generate OpenAPI spec.

**Comment by indytechcook** [comment]
Documentation to generate the openapi spec is here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/public-content-api/json-api.md
