### ISSUE TITLE
Enable JSON:Api on test instance

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-cms#6247]
## Background

As a CMS Engineer, I need to enable the JSON:API module and any required dependencies on a test instance, so that it can be tested together with a Lighthouse sandbox

## Acceptance Criteria

- [x] Drupal instance on Tugboat with `JSON:API` is accessible by Lighthouse

**Comment by indytechcook** [comment]
JSON API Path: https://pr6265-lkoslgyagkodlmzq41fgzass01ozbvla.ci.cms.va.gov/jsonapi

Open API Spec: https://pr6265-lkoslgyagkodlmzq41fgzass01ozbvla.ci.cms.va.gov/openapi/jsonapi

**Comment by indytechcook** [comment]
See https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/public-content-api/json-api.md for documentation

**Comment by acrollet** [comment]
Thanks!
