### ISSUE TITLE
Collect password login policy from each product.

### ISSUE THREAD

**Issue by rachel-kauff** [department-of-veterans-affairs/va.gov-cms#6256]
## Context: 

https://dsva.slack.com/archives/C02686M6K6X/p1630002934014100

We need clear policies for each product about how to handle user requests for alternate login methods (username and pw).
- Under what circumstances will we allow users to use a username and password to log in?
- Who needs to approve that (if anyone)?
- For how long should we allow alternate log in?

## ACs
- [ ] Alternate login policies are documented within the cms account admin policy for each product
   - [ ] [CLP](https://prod.cms.va.gov/help/clp/clp-cms-account-administration-policy)
   - [ ] [VAMC](https://prod.cms.va.gov/help/vamc/vamc-cms-account-administration-policy)
   - [ ] [Outreach Hub](https://prod.cms.va.gov/outreach-hub-cms-account-administration-policy)
   - [ ] [Vet Centers](https://prod.cms.va.gov/help/vet-centers/vet-center-cms-account-administration-policy)

**Comment by EWashb** [comment]
Currently all users are being asked to use PIV to login. It is highly discouraged to offer editors the ability to use just PW and username.

**Comment by rachel-kauff** [comment]
This ticket *might* not be that relevant any more for this reason, but it seems worth checking who beyond the Sitewide team members currently have a password login option.
