### ISSUE TITLE
Remove slack module from Drupal

### ISSUE THREAD

**Issue by indytechcook** [department-of-veterans-affairs/va.gov-cms#6267]
## Description
Since Drupal now sends logs to sentry and those messages are sent to slack.  Let's remove the direct integration from Drupal to slack.

## Acceptance Criteria
- [ ] Post API error messages should still log to Slack
- [ ] Post API alerts should only be triggered via Datadog/Sentry
- [ ] Slack module remove
- [ ] Custom Slack integration code should be removed

**Comment by swirtSJW** [comment]
Sorry, we have other uses for this related to editor notifications.  Closing this.
