### ISSUE TITLE
Do not send Sentry alert for 301 errors

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-cms#6283]
## Description

As a CMS devops engineer, I do not wish to be alerted when a facility status migration encounters a 301 redirect, so that I do not spend time responding to insignificant alerts.

## Background

https://dsva.slack.com/archives/CJT90C0UT/p1630328082004800

## Acceptance Criteria
- [ ] 301s do not generate slack alerts

**Comment by olivereri** [comment]
DataDog doesn't allow for excluding events from a monitor based on what's in the title or message. However it does allow excluding tags:

![image.png](https://images.zenhubusercontent.com/5f04cf8f49978b1615fee8c2/97075a1a-980e-402d-977c-6d92926d04b7)

To get this to stop flooding #cms-notifications I need to instead prevent the event from even being sent to DataDog in the first place:

![image.png](https://images.zenhubusercontent.com/5f04cf8f49978b1615fee8c2/160b7784-0892-4d8d-8b9a-02c3d2b0649b)

**Comment by olivereri** [comment]
This isn't going to work with `IF any` because there is still one matching filter.

**Comment by olivereri** [comment]
@indytechcook May I get some time with you to go over triggering these events manually as well as how these events are tagged before they are sent to Sentry? I noticed these:

![image.png](https://images.zenhubusercontent.com/5f04cf8f49978b1615fee8c2/f3035b7d-d09a-40b4-9b81-6313fd19a980)

Curious if we can use these to make the tags a bit richer to take advantage to DataDog's Tag Exclusions. I see other events don't have these though.
