### ISSUE TITLE
Implement branch name change

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-cms#6289]
## Background

As a CMS devops engineer, I need to update the default branch from "master" to "main", in order to follow best practices.

## Acceptance Criteria
- [x] Branch name has been updated in all code
- [ ] Nothing breaks
- [x] Documentation updated (local instructions as well)
- [x] Over-Communicated (including Demo)

## Notes
Initial Slack discussion https://dsva.slack.com/archives/CT4GZBM8F/p1591806963404700

**Comment by olivereri** [comment]
# VA.gov-CMS Default Branch Rename

## Purpose

In an effort to use more inclusive language in technology and recognizing that words have meaning and connotation beyond how they are used technically, VA.gov-CMS repository will change the default branch name from `master` to the generally accepted `main`.

## Changes to Tugboat Previews

Once the default branch is renamed the `master` branch will effectively disappear. This will cause the Base Preview built off the `master` branch to fail.

### Pull-Request Previews

### Demo Envrionments

## Local Changes for Developers

Once the default branch is renamed, developers will need to update their local repos as well. Below are steps from [Github's documentation.](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/renaming-a-branch)

OLD-BRANCH-NAME = `master`
NEW-BRANCH-NAME = `main`

```
git branch -m OLD-BRANCH-NAME NEW-BRANCH-NAME
git fetch origin
git branch -u origin/NEW-BRANCH-NAME NEW-BRANCH-NAME
git remote set-head origin -a
```

You may have noticed that the steps assumed that your remote name is `origin`. That may or may not be the case for you.  In a concrete example, I use the remote name `upstream` below. You can determine what remote names you use by changing directory to the va.gov-cms repo and entering the below command

```
git remote -v
```

The out put may look similar to:

```
olivereri       git@github.com:olivereri/va.gov-cms (fetch)
olivereri       git@github.com:olivereri/va.gov-cms (push)
upstream        git@github.com:department-of-veterans-affairs/va.gov-cms.git (fetch)
upstream        git@github.com:department-of-veterans-affairs/va.gov-cms.git (push)
upstream-test   git@github.com:department-of-veterans-affairs/va.gov-cms-test.git (fetch)
upstream-test   git@github.com:department-of-veterans-affairs/va.gov-cms-test.git (push)
```

You can see that my personal fork remote is called `olivereri`, the va.gov-cms repo remote is called `upstream` and the va.gov-cms-test repo is called `upstream-test`. With that in mind these are the commands I would run to update my local:

```
git branch -m master main
git fetch upstream
git branch -u upstream/main main
git remote set-head upstream -a
```
