### ISSUE TITLE
Contact Lighthouse team and begin sandbox setup process

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-cms#6293]
## Background

As a CMS engineer, I need initiate the Lighthouse onboarding process, so that I can discover any unknowns and/or roadblocks in the process

## Acceptance Criteria

- [x] Lighthouse team has been contacted and initial meeting scheduled if required
- [ ] Tickets created under this epic to satisfy any previously unknown requirements

**Comment by indytechcook** [comment]
I had a conversion in Slack and then sent the openapi spec to the lighthouse team to start next steps of setting up a sandbox.

**Comment by indytechcook** [comment]
The updated initial spec has been sent to Carrisa on the lighthouse team.

**Comment by indytechcook** [comment]
Lighthouse team is reviewing the spec and will provide feedback by EOW.

**Comment by indytechcook** [comment]
I created a follow up to create any issues brought up by the Lighthouse team: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/6387
