### ISSUE TITLE
Tugboat preview environment health monitoring & alerting

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-cms#6307]
## Description

As a VAMC upgrade team member, I want previews to be built reliably, so that I can build content for veterans.

As a CMS devops engineer, I want to know when previews are stuck or otherwise cannot build, so that I can take corrective action.

## Acceptance Criteria

- [ ] The CMS team is alerted when any base preview is inaccessible for > 15 minutes

**Comment by TheBoatyMcBoatFace** [comment]
This is done. Closing.
