### ISSUE TITLE
Update Drupal Core to 9.2.5

### ISSUE THREAD

**Issue by indytechcook** [department-of-veterans-affairs/va.gov-cms#6329]
## Description

Update Drupal Core to 9.2.5

https://github.com/department-of-veterans-affairs/va.gov-cms/pull/6321
https://github.com/department-of-veterans-affairs/va.gov-cms/pull/6322

Release Notes: https://www.drupal.org/project/drupal/releases/9.2.5
Diff: https://git.drupalcode.org/project/drupal/-/compare/9.2.4...9.2.5?from_project_id=59858
No new change records in this release.

## Acceptance Criteria
- [ ] Drupal core is updated to version from `9.2.4` to `9.2.5`
- [ ] Diff and release notes reviewed to look for any possible breaking changes
  - [ ] Any items are resolved or blocking issues have been created
- [ ] Manual Testing based upon the changes. TBD

**Comment by ndouglas** [comment]
This was taken care of in #6407  / #6435.
