### ISSUE TITLE
Validation Constraint for links referencing local file paths

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-cms#6330]
## Description
As an editor, I want to know when I link a file on my local machine instead of uploading it, so that my content is deployed as intended.

We've gotten some matches for HTML like the following:
```
<a href="///U:/My%20Documents/COVID-19/Vaccine/Letter%20to%20Veterans%202021.07.09.pdf">here</a>
<a href="///C:/Users/VHABUTKURTZA/AppData/Local/Microsoft/Windows/INetCache/Content.Outlook/AUJLV0UN/www.ReportingOnSuicide.org"><em>www.ReportingOnSuicide.org</em></a>
```

## Acceptance Criteria
- [ ] Validator correctly rejects the URI patterns we've seen referencing local files
- [ ] Validator does not trigger against harmless paths
- [ ] Automated tests have been written

**Comment by acrollet** [comment]
I did a little analysis on the built output, here are the main classes of legit link types that should pass:

- https?://
- /
- #about-cprp
- /alaska-health-care/programs/covid-19-vaccines
- mailto:
- sms://
- tel:

**Comment by ndouglas** [comment]
I think you had the right idea with matching on the Windows drive letter & colon.  I don't expect we'd ever use that pattern to start a path alias.

**Comment by ndouglas** [comment]
I like the idea of keeping these narrow and precise to exclude problems rather than catch everything that is undesirable, since each gives us a case where we're effectively documenting that we might need to provide additional training or retraining, etc.  Costs more development time but seems to retain more information.

**Comment by acrollet** [comment]
> I think you had the right idea with matching on the Windows drive letter & colon. I don't expect we'd ever use that pattern to start a path alias.

I sure hope not 😬
