### ISSUE TITLE
Drupal errors not logging to sentry

### ISSUE THREAD

**Issue by indytechcook** [department-of-veterans-affairs/va.gov-cms#6334]
## Description

Some Drupal / PHP errors are not sending to sentry

Exampels:

```
	RuntimeException: Failed to start the session because headers have already been sent by "/var/www/cms/docroot/vendor/symfony/http-foundation/Response.php" at line 1224. in Symfony\Component\HttpFoundation\Session\Storage\NativeSessionStorage->start() (line 152 of /var/www/cms/docroot/vendor/symfony/http-foundation/Session/Storage/NativeSessionStorage.php)
#0 /var/www/cms/docroot/core/lib/Drupal/Core/Session/SessionManager.php(162): Symfony\Component\HttpFoundation\Session\Storage\NativeSessionStorage->start()
#1 /var/www/cms/docroot/core/lib/Drupal/Core/Session/SessionManager.php(193): Drupal\Core\Session\SessionManager->startNow()
#2 /var/www/cms/docroot/vendor/symfony/http-foundation/Session/Session.php(189): Drupal\Core\Session\SessionManager->save()
#3 /var/www/cms/docroot/core/lib/Drupal/Core/StackMiddleware/Session.php(60): Symfony\Component\HttpFoundation\Session\Session->save()
#4 /var/www/cms/docroot/core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php(47): Drupal\Core\StackMiddleware\Session->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#5 /var/www/cms/docroot/core/modules/page_cache/src/StackMiddleware/PageCache.php(106): Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#6 /var/www/cms/docroot/core/modules/page_cache/src/StackMiddleware/PageCache.php(85): Drupal\page_cache\StackMiddleware\PageCache->pass(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#7 /var/www/cms/docroot/core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php(47): Drupal\page_cache\StackMiddleware\PageCache->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#8 /var/www/cms/docroot/core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php(52): Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#9 /var/www/cms/docroot/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#10 /var/www/cms/docroot/core/lib/Drupal/Core/DrupalKernel.php(717): Stack\StackedHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#11 /var/www/cms/docroot/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#12 {main}
.
```

```
Drupal\Core\Entity\EntityStorageException: SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction: INSERT INTO "taxonomy_entity_index" ("entity_type", "bundle", "entity_id", "revision_id", "field_name", "delta", "tid") VALUES (:db_insert_placeholder_0, :db_insert_placeholder_1, :db_insert_placeholder_2, :db_insert_placeholder_3, :db_insert_placeholder_4, :db_insert_placeholder_5, :db_insert_placeholder_6); Array ( [:db_insert_placeholder_0] => node [:db_insert_placeholder_1] => health_care_region_detail_page [:db_insert_placeholder_2] => 34983 [:db_insert_placeholder_3] => 528931 [:db_insert_placeholder_4] => field_administration [:db_insert_placeholder_5] => 0 [:db_insert_placeholder_6] => 348 ) in Drupal\Core\Entity\Sql\SqlContentEntityStorage->save() (line 810 of /var/www/cms/docroot/core/lib/Drupal/Core/Entity/Sql/SqlContentEntityStorage.php).
```

```
Drupal\simplesamlphp_auth\Exception\SimplesamlphpAttributeException: Error in simplesamlphp_auth.module: no valid "adUPN" attribute set. in Drupal\simplesamlphp_auth\Service\SimplesamlphpAuthManager->getAttribute() (line 284 of /var/www/cms/docroot/modules/contrib/simplesamlphp_auth/src/Service/SimplesamlphpAuthManager.php).
```
## Implementation

@indytechcook hypothesizes that uncaught exceptions are the ones that are not making it to Sentry.

## Acceptance Criteria
- [x] Investigate why these errors aren't making it to Sentry (see #7057, #7218).
- [x] Open up a followup issue or issues to address findings (see #7222, #7224).

**Comment by ndouglas** [comment]
Executed three cases:

<img width="768" alt="Screen Shot 2021-11-16 at 1 59 02 PM" src="https://user-images.githubusercontent.com/1318579/142048437-8b8b15d7-ed56-4550-b777-df85fb4c721c.png">

with the following results in Sentry:


<img width="774" alt="Screen Shot 2021-11-16 at 1 58 26 PM" src="https://user-images.githubusercontent.com/1318579/142048537-8aa98c46-045f-4fc4-b201-0570711506ca.png">

<img width="913" alt="Screen Shot 2021-11-16 at 1 59 45 PM" src="https://user-images.githubusercontent.com/1318579/142048563-6c7e4131-7f58-4491-be2e-d35a64b81880.png">

Definitely does seem as though some classes of errors are not making it through.  Double-checked the configuration and it looks solid.  No related issues that I could find in the Raven queue, or hints in the notes, so nothing left to do but debug 🤷‍♂️

**Comment by ndouglas** [comment]
See #6804.  I'm going to check that to determine whether it's a duplicate or a complication.

**Comment by ElijahLynn** [comment]
I think @dginther mentioned that the timestamps get out of order sometimes and drops them. We discussed possibly moving the Drupal logs to their own file to avoid that situation.

**Comment by ndouglas** [comment]
That's just Loki, though, right?  I'm creating exceptions on the fly and they're not getting to Sentry -- there shouldn't be any issue with timestamps here.

**Comment by ElijahLynn** [comment]
> That's just Loki, though, right? I'm creating exceptions on the fly and they're not getting to Sentry -- there shouldn't be any issue with timestamps here.

I think you are right about that, Loki. Disregard then!

**Comment by ndouglas** [comment]
Unassigned myself because I haven't made a substantial amount of progress other than what I posted above and priorities will change in forthcoming sprints.

**Comment by indytechcook** [comment]
To help figure out what type of errors are not reporting, I added the follow PR with several different types of test errors #7057

**Comment by indytechcook** [comment]
Error that should have been caught on the tugboat instance but wasn't in sentry

![image](https://user-images.githubusercontent.com/121603/143306346-9d7db024-7f0e-461e-9ad7-a43543d3a589.png)

**Comment by ndouglas** [comment]
Opened #7224 as followup.

**Comment by ndouglas** [comment]
Aspects of what I've discovered in this issue are also opened as separate issues in #7222 and #7239.
