### ISSUE TITLE
Admin/content moderation state filter is repeating itself and broken

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#6342]
UPDATE:  THis is impacting all moderation state filters on all Views.
**Describe the defect**
**To Reproduce**
1. Go to /admin/content.
2. Pull down the "moderation state" filter
3. Notice each of the entries is repeated, along with weird text about who can archive.
4. ALso notice that none of the selections (other than "any"return any results). gife defferrent results if you pick the first or the second set of choices.

![image](https://user-images.githubusercontent.com/5752113/132066212-030fe282-ebab-4fc8-884c-d02a7bf2bb00.png)

Selections are giving odd results too.
![image](https://user-images.githubusercontent.com/5752113/132066780-b97e4c34-9913-4388-99a4-11a799d18588.png)

**Expected behavior**
Each moderation state should only appear once.
When a filter is selected, 

**Screenshots**

**Desktop (please complete the following information if relevant, or delete):**

**Additional context**
Add any other context about the problem here. Reach out to the Product Managers to determine if it should be escalated as critical (prevents users from accomplishing their work with no known workaround and needs to be addressed within 2 business days).

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Defect")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS objective (orange) (not needed for bug tickets)
- [ ] CMS-supported product (black)

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [x] `Core Application Team`
- [x] `Product Support Team`

**Comment by cmaeng** [comment]
Slack thread here: https://dsva.slack.com/archives/CT4GZBM8F/p1630704530283500

Probably not a critical defect as it only affected content findability but we addressed within 2 business days regardless.
