### ISSUE TITLE
Upgrade to Drupal 9.3

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-cms#6352]
## Description

Drupal 9.3 will be released in December 2021.

Make sure to review change notices and change records:
https://www.drupal.org/list-changes/drupal/published?keywords_description=&to_branch=9.3.x&version=&created_op=%3E%3D&created%5Bvalue%5D=&created%5Bmin%5D=&created%5Bmax%5D=

## Acceptance Criteria
- [ ] CMS is upgraded to Drupal 9.3
- [ ] Confirm that phpstan reports any deprecated code in use, [such as the `render` function](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/6353)

**Comment by ndouglas** [comment]
The patch for [this issue](https://www.drupal.org/project/drupal/issues/2893933) needs to be updated to the latest, as changes in the 9.3.x branch broke applying the current patch.
