### ISSUE TITLE
"Release content" button should work with GH actions on BRD environments as appropriate

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-cms#6354]
## Description

The FE tools team is working on a gradual migration of the content build from Jenkins to Github Actions. The cutover will be done gradually, starting with the `dev` environment.

## Acceptance Criteria
- [x] The CMS 'Release content' button can trigger a content build on the `dev` environment
- [x] Different deploy systems can be used to trigger the build per environment

**Comment by jefflbrauer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VAgov-CMS-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/6354?planning-poker) with ZenHub @ElijahLynn @indytechcook @ndouglas @olivereri @timcosgrove

**Comment by jefflbrauer** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VAgov-CMS-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/6354?planning-poker) with ZenHub @cweagans

**Comment by indytechcook** [comment]
@Cameron Eagans a few things with my testing on stage:

- The worklow was not triggered when pressing the button
- An error occurred and was shown in watchdog: `Github\Exception\RuntimeException: Not Found in Github\HttpClient\Plugin\GithubExceptionThrower->Github\HttpClient\Plugin\{closure}() (line 123 of /var/www/cms/docroot/vendor/knplabs/github-api/lib/Github/HttpClient/Plugin/GithubExceptionThrower.php).`
- I received a success message in the UI

**Comment by cweagans** [comment]
Followup PR is merged.

**Comment by indytechcook** [comment]
I tested this on staging and say it's ready to close.
