### ISSUE TITLE
Prepare for onboarding process with Ops

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-cms#6357]
## Description

As a CMS Devops Engineer, I need to start the EKS onboarding process, so that the Ops team is aware of our initiative and may provide appropriate support.

## Acceptance Criteria

- [x] [Onboarding template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=operations%2C+kubernetes%2C+devops&template=kubernetes-onboarding-template.md&title=) has been reviewed and issues created under this epic for each requirement not currently satisfied
- [x] Each issue created is listed as a blocker for #6377

**Comment by olivereri** [comment]
[ ] Your application! (Your team)
    Your application should conform to the 12 factor app methodology (https://12factor.net/)
[ ] A Github Repository for your application (Operations or your team)
[ ] A Dockerfile for your application (Your team, Operations can assist if needed)
[ ] Elastic Container Registry Repository for your application (Operations, PRs are welcome: https://github.com/department-of-veterans-affairs/devops/blob/master/terraform/environments/global/ecr.tf)
[ ] Automation to "Release" and "Tag" the application Github Repository with a semantic version number. (Your team, Operations can assist if needed)
[ ] Automation to push the built Docker container to the ECR Repository and tag it with the semantic version number. (Your team, Operations can assist if needed)
    Please do not use 'latest' tags
[ ] Kubernetes Application Manifest in YAML, jsonnet, or Helm Chart (Operations and your team)
    YAML and jsonnet are highly preferred, Helm charts are discouraged
[ ] Automation to update the Kubernetes Application Manifest when a new version of your application container is pushed to ECR (Operations and your team)
[ ] AWS Service account for your team or application (Operations)
[ ] Path/s in AWS SSM Parameter Store created for your team or application (Operations)
[ ] AWS IAM Permissions applied to your team members to allow read/write access to AWS SSM Parameter Store path/s for your application/team (Operations)
[ ] AWS IAM Permissions applied to the service account to allow read access to AWS SSM Parameter Store path/s for your application/team (Operations)
[ ] Secrets and Parameters needed for your application stored in AWS Systems Manager Parameter Store (Your team)

**Comment by olivereri** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/issues/30177

**Comment by olivereri** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/issues/30196
