### ISSUE TITLE
Make staff profile bio and intro text field required, but only show them based on a boolean 

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#6363]
For refining in Sprint 41

## Description

A change was made to the FE that does not create  a staff profile (and a link to it) if the page has no "bio First sentence  text AND Bio.
![image](https://user-images.githubusercontent.com/5752113/132560039-b5fe61cc-41ea-41e7-ba73-47eebffb58ae.png)

https://github.com/department-of-veterans-affairs/va.gov-team/issues/29096

https://dsva.slack.com/archives/C01SR56755H/p1631029274004700 and PR >>> https://github.com/department-of-veterans-affairs/content-build/pull/501/f

The help text needs to be updated to indicate that is the case .   

## Acceptance Criteria

- [ ] Boolean field with label = "Create profile page with biography."
- [ ] Hide bio fields when boolean is unchecked
- [ ] Make first sentence and body text fields required

![image](https://user-images.githubusercontent.com/643678/133656015-34879a2f-266d-42a1-a083-279787390233.png)

## Implementation TBD 

Add boolean along the lines of "Create a page for this profile" which would then require First sentence and Body. 

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Core Application Team`
- [x] `Product Support Team`

**Comment by rachel-kauff** [comment]
Nothing revolutionary to add here! My recommendation/validation of what's suggested in this ticket:
- Yes to the boolean
- Hide bio fields when boolean is unchecked
- Boolean label = "Create profile page with biography." 
- Make first sentence and body text fields required

<img width="802" alt="Screen Shot 2021-09-13 at 2 34 12 PM" src="https://user-images.githubusercontent.com/41017988/133159465-660f84e0-91d8-444b-a92d-728dc561ef5e.png">
