### ISSUE TITLE
Design guidance about Nearby Vet Centers and Outstations (or decide not to provide anything)

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#6373]
## User Story or Problem Statement

Nearby Vet Center field is being removed. What should we replace it with, if anything? See #6371 for some context. 

How might we use this place in the UI to learn about the effectiveness new 80 mile radius rule? 

## Acceptance Criteria
- [x] Reviewed by Michelle M
- [x] Engineers have guidance for what guidance to add, in #6372 

## Design principles

Which [CMS design principle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/cms-product-design-principles.md) is at play?
- [ ] Purpose-driven: Creates an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [x] Efficient: Removes distractions and create clear, straightforward paths to get the job done.
- [x] Approachable: Offers friendly guidance over authoritative instruction.
- [ ] Consistent: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [x] Empowering: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Core Application Team`
- [x] `Product Support Team`

**Comment by rachel-kauff** [comment]
Details from [this related thread in DSVA Slack](https://dsva.slack.com/archives/CT4GZBM8F/p1631639515470700)
- According to Swirt, it's possible to display the nearby Vet Centers in form content. That would look something like this, pending more information about exactly how the FE displays them. 
![Screen Shot 2021-09-15 at 11.16.05 AM.png](https://images.zenhubusercontent.com/5e399cf5446c5b4ca0e31e42/76c2d3b6-907a-4c02-aa4f-c5f37433fc9d)

- Alternate option if the first falls through: Provide a preview link so editors can see what nearby locations the system selected for their VC
![Screen Shot 2021-09-15 at 11.16.12 AM.png](https://images.zenhubusercontent.com/5e399cf5446c5b4ca0e31e42/698eb0c4-ca58-499e-ad71-b1484dc9ea52)

**Comment by rachel-kauff** [comment]
Details to get from Dave during our facilities checkin:
- [ ] Will there/should be any limit to the number of nearbys displayed
- [ ] Who to send feedback to, the email address, and what they need to know

**Comment by rachel-kauff** [comment]
Iteration based on context from Dave
For `contact CMS Help Desk` link, use [the url for the jira service desk portal](https://va-gov.atlassian.net/servicedesk/customer/portal/3/group/8/create/26). 

<img width="739" alt="Screen Shot 2021-09-15 at 3 01 38 PM" src="https://user-images.githubusercontent.com/41017988/133515809-499cf21b-fda4-4ca7-a911-fbb86d0b32db.png">

**Comment by rachel-kauff** [comment]
@kevwalsh This is my latest recommendation. If all looks good to you, we can fold this into the implementation ticket.

**Comment by kevwalsh** [comment]
This is great, i've added the last screenshot to #6372.
