### ISSUE TITLE
Implement CMS login page monitor in Datadog

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-cms#6376]
## Description

As a CMS devops engineer, I wish to migrate the CMS login page monitor off of prometheus, so that I am using platform-recommended monitoring services.

## Implementation

Likely to use a datadog synthetic but TBD.

## Acceptance Criteria
- [ ] ~CMS login page monitor is no longer on prometheus~ (removed so as not to be blocked by #6702)
- [x] Uptime metric continues to be accurate
- [x] Add dashboard in datadog with panel for uptime metric
- [x] monitor & dashboard are created via terraform
- [x] Add uptime alert in datadog and remove from prometheus (pagerduty -> slack) 
- [x] Update documentation  ](https://github.com/department-of-veterans-affairs/va.gov-cms/blob/master/READMES/cms-alerts.md
)

**Comment by ElijahLynn** [comment]
@mchelen I want to hold on this until we have a clear direction on the future of logs also going to Datadog. As right now we have a dashboard in Grafana that has metrics AND logs and if we move metrics to logs, we will have fragmentation. See this discussion with @dginther and friends > https://dsva.slack.com/archives/CJYRZK2HH/p1633553364386300.
