### ISSUE TITLE
Onboard to EKS with Ops

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-cms#6377]
## Description

As a CMS Devops Engineer, I need to start the EKS onboarding process, so that the Ops team is aware of our initiative and may provide appropriate support.

## Acceptance Criteria

- [ ] [Onboarding template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=operations%2C+kubernetes%2C+devops&template=kubernetes-onboarding-template.md&title=) has been filled out and submitted

**Comment by ElijahLynn** [comment]
We paused on this while we are looking into alternative platforms (e.g. Lagoon, Waypoint etc). The reason for this is that Lagoon is already does everything that we need and there is little risk involved. So we started looking at Lagoon and then decided to look at others as well.

**Comment by jkalexander7** [comment]
Decision made to maintain current BRD on Amazon Linux 2 - https://github.com/department-of-veterans-affairs/va.gov-cms/issues/7585.
