### ISSUE TITLE
Address Feedback from Lighthouse team

### ISSUE THREAD

**Issue by indytechcook** [department-of-veterans-affairs/va.gov-cms#6387]
## Description

This is a follow up to https://github.com/department-of-veterans-affairs/va.gov-cms/issues/6293 to address any feedback given by the lighthouse team

## Acceptance Criteria
- [ ] Create tickets to address feedback from lighthouse team

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [x] `Core Application Team`
- [ ] `Product Support Team`

**Comment by TheBoatyMcBoatFace** [comment]
Closed per Platform CMS Team on Dec. 20, 2022

**Comment by TheBoatyMcBoatFace** [comment]
Not pursuing public API path
