### ISSUE TITLE
Train OPIA to use new homepage banner

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#6404]
## ACs

- [x] OPIA team is trained to use homepage banner and access KB article.

**Comment by xiongjaneg** [comment]
Met on Sept. 14, emailed follow-up, Dom and Gary attended

Xiong, Jane G. (Agile 6 Applications, Inc)
2:20 PM (40 minutes ago)
to Joshua, Dominique, Gary, David, clarence.maeng@agile6.com, rachel.kauff@civicactions.com, me, kevin.walsh@civicactions.com

Joshua, Dominique, and Gary,

 

Thanks for attending the alert banner meeting. We hope the information was helpful to you. As of 3:00 p.m. today, Drupal CMS will be the source of the alert banner.

 

Here are some helpful links:

 

Meeting recording on YouTube
 

Knowledge Base article about the alert banner on Drupal CMS (VA network required, but no login required to view it)
 

Orientation video for editing in Drupal CMS (on YouTube)
 

Drupal CMS production environment where you’ll be editing the alert banner after logging in with your PIV card (VA network required)
 

Direct link to the homepage banner on Drupal CMS that you’ll be editing (VA network and PIV login required, you may want to bookmark this)
 

Please email the Drupal CMS Helpdesk at support@va-gov.atlassian.net if you have any questions or follow-up.

 

Thanks for all you do for our Veterans and active duty service members!

 

Jane

 

Jane Xiong

Instructional Designer, VFS-CMS Team

Supporting editor-centered management for Veteran-centered content

Need Drupal CMS help? Email support@va-gov.atlassian.net
