### ISSUE TITLE
Refresh KB article on how to update facility data

### ISSUE THREAD

**Issue by cmaeng** [department-of-veterans-affairs/va.gov-cms#6414]
Access to care wait time data specifically needs to be fleshed out with the LH team.

This will be taken care of by Lighthouse after #6415

**Comment by jefflbrauer** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VAgov-CMS-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/6414?planning-poker) with ZenHub @cweagans

**Comment by kevwalsh** [comment]
This is done, by Lighthouse.
