### ISSUE TITLE
Onboard LH team as KB editors for node 23533

### ISSUE THREAD

**Issue by cmaeng** [department-of-veterans-affairs/va.gov-cms#6415]
ACs
- [x] Governance of this page is determined (~create a child KB section and assign node 23533 to it?~ or give Lighthouse editors KB section access, which is simpler)
- [x] KB editors are identified (waiting on an email response)
- [x] Users are set up, onboarded, and trained in editing https://prod.cms.va.gov/node/23533
- [x] Update the "how to edit a KB article", as needed.

**Comment by xiongjaneg** [comment]
provided live orientation Sept. 13, 2021, followed up with link to meeting recording and links to prod and articles
