### ISSUE TITLE
Create a KB editor specific role

### ISSUE THREAD

**Issue by cmaeng** [department-of-veterans-affairs/va.gov-cms#6416]

**Comment by kevwalsh** [comment]
Per slack, we don't need a KB specific role. We just need to provide access to the KB section to a user with the Content Publisher role. We may want to consider subsections, for each product in the KB, like KB > VAMC, KB > Vet Center, etc. So a VAMC KB editor could only edit content associated with KB > VAMC section.

**Comment by cmaeng** [comment]
Closing to no action as our application can support the need as is.
