### ISSUE TITLE
Accordions should not show twisties, should only apply to use within KB, and should not do text transform

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#6423]
**Describe the defect**

Paragraphs should only be styled as accordions within the KB, not on other content types. 

Accordions should not show twisties.

Case should not be transformed. 

Accordion group should have its own margin, should respect spacing of paragraphs below it

**To Reproduce**

1. Go to https://prod.cms.va.gov/centralized-content/test-design-discovery
1. See that accordions are displayed as accordions, and have twisties.
1. See that case has been transformed to initial case

**Expected behavior**

KB only
1. Accordion paragraphs should not be themed as accordions
1. Go to https://prod.cms.va.gov/node/28318 
1. Accordion paragraphs should be themed as accordions
1. Case should match what was added by the editor. 

No twisties!
1. Go to https://prod.cms.va.gov/node/28318 
1. No twisties on accordions

**Screenshots**
![image](https://user-images.githubusercontent.com/643678/133258210-eeacd0e3-d8ae-4cf1-9268-288f704dba2a.png)

<img width="717" alt="Screen Shot 2021-09-14 at 8 44 30 AM" src="https://user-images.githubusercontent.com/41017988/133290216-3daaeb55-d9ec-4ad8-b8db-53292d4ee689.png">

**Additional context**
Add any other context about the problem here. Reach out to the Product Managers to determine if it should be escalated as critical (prevents users from accomplishing their work with no known workaround and needs to be addressed within 2 business days).

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Defect")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS objective (orange) (not needed for bug tickets)
- [ ] CMS-supported product (black)

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [x] `Core Application Team`
- [x] `Product Support Team`

**Comment by rachel-kauff** [comment]
@kevwalsh Added the spacing issue here, but there might be a more precise way of describing what's going on...

**Comment by rachel-kauff** [comment]
Related to 

> Paragraphs should only be styled as accordions within the KB, not on other content types.

I think we were mostly anticipating this affecting proofing, but I found an example of this in the Vet Centers form. 
I don't think this should change the decision to not theme the proofing experience, just wanted to note the example.

<img width="735" alt="Screen Shot 2021-09-14 at 8 59 33 AM" src="https://user-images.githubusercontent.com/41017988/133292704-372bf26a-67ce-4f7d-babc-1a2e8cacb40d.png">
