### ISSUE TITLE
Update "cron run complete" grafana chart to use loki datasource

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-cms#6426]
## Description

As a CMS devops engineer, I want the "cron run complete" grafana chart to use loki as its datasource, so that it will continue to function after CloudWatch is deprecated.

## Acceptance Criteria
- [ ] ~"cron run complete" grafana chart uses loki as its datasource~
- [x] Demonstrate how "Cron Run Complete" Grafana chart will use Loki as a Datasource with Staging as an example.
- [x] Documentation on setup is added/updated.

**Comment by ElijahLynn** [comment]
Pointed as a 5 as there is some risk as we haven't done anything in Loki yet and it is a new thing for us. We can of course get Ops support though, but that could take some time.

**Comment by olivereri** [comment]
This is based of a CloudWatch Logs `metric filter` applied to to CW Log Group `dsva-vagov-prod/var/log/messages`

![image.png](https://images.zenhubusercontent.com/5f04cf8f49978b1615fee8c2/04498ec0-a386-499e-9b25-19ba90209743)

In the future `CMS-Lock-wait-timeout-exceeded` may need to be pulled from Loki instead of CloudWatch Logs. Now we'll be able to easily find it since this documented or in the DevOps codebase.

**Comment by olivereri** [comment]
`sum by (app) (count_over_time({app="cms",filename="/var/log/messages"} |= "cron"[5m]))`

**Comment by olivereri** [comment]
Documentation:
https://github.com/department-of-veterans-affairs/va.gov-cms/blob/master/READMES/grafana-dashboard-cms.md

**Comment by olivereri** [comment]
Weird behavior I'll need to sort out with VSP Ops.
Loki Logs is catching 2 log entries for  every one "Cron Run Completed" logged:
![image.png](https://images.zenhubusercontent.com/5f04cf8f49978b1615fee8c2/2c7c4f7d-a9c1-443b-b614-7303ad31fadf)

What this will do is show a count of 2 versus 1 in the current Cron Run Completed panel:
![image.png](https://images.zenhubusercontent.com/5f04cf8f49978b1615fee8c2/bf066212-80df-4236-91b7-2fb0d0c1ef5e)

Not terrible, but a little annoying.

**Comment by mchelen-gov** [comment]
> @mchelen-gov Would like a P.O. review since I updated the A.C. for this. We don't currently send our Production logs to Loki, we can't update the current "Cron Run Complete" Grafana Chart to use Loki as a data source. Instead I've demonstrated how this _will_ be completed using the Staging environment that does send logs to Loki.

ok @olivereri can you update title + AC to specify staging and spin off ticket for production?
