### ISSUE TITLE
CMS UI accessibility: Add underlining to linked text 

### ISSUE THREAD

**Issue by rachel-kauff** [department-of-veterans-affairs/va.gov-cms#6439]
## Description
Per [A11y best practices introduced by Angela Fowler and Josh Kim](https://docs.google.com/presentation/d/e/2PACX-1vTKKnFhEMKkjsVR-7dzivJ0QhAXh39sxzjsPSfSuXYkHxFKKhCoNmlmumiimB8rUw6GfrnsgblnayJK/pub?start=false&loop=false&delayms=3000&slide=id.ge89223ffe9_0_203), underline linked text to make it noticeable to people with colorblindness.

We may want to put this on hold for Claro / D9 design system iteration. 

## Acceptance Criteria
- [ ] Further design discovery to identify scope/ what items get underlining
   - [ ] Does this apply to text that's more clearly present itself as an interface function (for example, the labels on tabs, toolbars, menu items....) -- Kauff's instinct says no, this only applies to text that we need to distinguish from other non-linked content
- [ ] Document design guidelines for linked text somewhere (proto cms design system documentation)

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [x] `Core Application Team`
- [x] `Product Support Team`

**Comment by swirtSJW** [comment]
@laflannery I have a feeling this can be closed  because it was addressed.  If you agree, can you close this?

**Comment by laflannery** [comment]
I believe you are correct, closing
