### ISSUE TITLE
Design editorial experience for Vet Center official name field

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#6447]
## User stories

As an admin, i can update the plain language Vet Center name (the node title) but not the Vet Center Official name which is migrated from Facility API. 

As a Vet Center editor, i can see, but not edit, either the official name or the plaing language Vet Center name (the node title).

Other background
- Official name will be shown as the h1, but plain language name will be used for URL and other places on the Veteran experience. 

Questions to consider: 
- if plain language and official name are the same, do we need to show both? 

## Current experience 

For Prescott Vet Center 

![Edit_Vet_Center_Dr__Cameron_McKinley_Department_of_Veterans_Affairs_Veterans_Center___VA_gov_CMS](https://user-images.githubusercontent.com/643678/137323746-3087af84-cb7a-4263-a1e4-e8e61f7794aa.png)

## ACs
- [x] New "Official name" field has a designed label and help text
- [x] Editing experience has been designed
- [x] Proofing experience has been designed
- [ ] Others TBD 

## Artifact
[Figma: Vet Centers prototype](https://www.figma.com/file/QUZpQV5Nf0LhtsrnqqVHas/Vet-Centers-forms?node-id=17%3A23)

(Note that this file contains prototypes for several other pieces of work. The correct frames are labeled with this issue number, and the link should take you directly to the correct area.)

**Comment by rachel-kauff** [comment]
@ethanteague @kevwalsh I've made design recommendations in the Figma file linked under "Artifacts" in the issue description. The prototypes are marked up with annotations, and I *think* it should be pretty straightforward. If there are any follow up questions about this @suzanne-gray and @EWashb should be able to field. Thank you!

**Comment by kevwalsh** [comment]
Erika had a chance to show this off during the Facilities sync, awesome stuff. 

We discussed a couple of very minor changes

1. Making both fields editable in the admin experience
2. Updating the annotation about the logic for exposing the Common name field. Instead of "if there is one" it should say "if it's different". Because all Vet Centers will actually have values in both. It's just that only 1% will have differences between them.

**Comment by EWashb** [comment]
I appreciate it, Kev! I can't take all the credit on this one. It was more of being in the right place at the right time with ears open. The amazingly thoughtful design is all credited to @rachel-kauff.

**Comment by EWashb** [comment]
@kevwalsh should we go ahead and close this one in preparation for Friday demo? Looks like we have what we need for implementation (#6449) on the figma file

**Comment by kevwalsh** [comment]
@EWashb Yes, thanks!! Closing now.
