### ISSUE TITLE
Implement editorial experience design for Official name

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#6449]
See also #6955, which is higher priority, working on the same field. 

AC
- [ ] Implementing design from #6447
- [ ] PR must go through design review (with @EWashb or @suzanne-gray)
- [ ] PR must go through change management review (with @xiongjaneg) to determine if an announcement will be needed, and/or if KB article should be updated.

**Comment by rachel-kauff** [comment]
@ethanteague I've wrapped up design thoughts in #6447 so hopefully that unblocks this one now!.

**Comment by ethanteague** [comment]
> @ethanteague I've wrapped up design thoughts in #6447 so hopefully that unblocks this one now!.

TY @rachel-kauff !
