### ISSUE TITLE
Update migration from Facility API to target Vet Center "Official name" field as well as node title

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#6453]
ACs
- [ ] Update vet_center migration to populate both node title and `field_official_name` for Vet Centers, but not Outstations or MVCs
- [ ] Let facilities/FE team know that they can start using this for h1s.

**Comment by swirtSJW** [comment]
@JayDarnell @kevwalsh  I just ran the migration on prod, so field_official_name should now be populated for vet_centers.

![image](https://user-images.githubusercontent.com/5752113/136108303-a9fa1abc-a68e-41f0-bedd-4a3cf18d2ae5.png)
