### ISSUE TITLE
Create Github Repository for EKS Onboarding

### ISSUE THREAD

**Issue by olivereri** [department-of-veterans-affairs/va.gov-cms#6460]
## Description

As a CMS Devops Engineer, I need to create a new Repository in the department-of-veterans-affairs organization  , so that I can utilize the new EKS hosting and deployment system.

## Acceptance Criteria

- [ ] Github Repository in department-of-veterans-affairs org is created.

## Implementation Details

Operations team has been using this naming pattern for their repos: `vsp-infra-app` e.g. `vsp-infra-grafana`

**Comment by olivereri** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VAgov-CMS-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/6460?planning-poker) with ZenHub @ElijahLynn @indytechcook @ndouglas

**Comment by ndouglas** [comment]
(d'oh)
