### ISSUE TITLE
Create ECR Repository for EKS Onboarding Process with Ops

### ISSUE THREAD

**Issue by olivereri** [department-of-veterans-affairs/va.gov-cms#6462]
## Description
As a CMS Devops Engineer, I need to create an AWS Elastic Container Registry (ECR), so that the team has a place to store built container images retrievable by ArgoCD.

## Acceptance Criteria

- [ ] A new ECR Repository is created in the DSVA AWS Account for CMS container images.

## Implementation Details 

https://github.com/department-of-veterans-affairs/devops/blob/master/terraform/environments/global/ecr.tf

- [ ] Modify ecr.tf to include CMS as a repository.
- [ ] Create a Pull Request, Merge, then Apply changes.

**Comment by olivereri** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VAgov-CMS-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/6462?planning-poker) with ZenHub @ElijahLynn @indytechcook @ndouglas

**Comment by olivereri** [comment]
Good first Terraform Apply for @ndouglas

**Comment by ndouglas** [comment]
<img width="1451" alt="Screen Shot 2021-09-30 at 7 09 27 PM" src="https://user-images.githubusercontent.com/1318579/135541743-d93c5a87-ac40-48f0-b1e5-7121a950ac97.png">
