### ISSUE TITLE
Migrate Release and Tag Automation from Jenkins for EKS Onboarding Process with Ops

### ISSUE THREAD

**Issue by olivereri** [department-of-veterans-affairs/va.gov-cms#6463]
## Description
As a CMS Devops Engineer, I need to migrate CMS Repo tag and release automation from Jenkins, so that release and tag automation works with the new GHA, EKS/ArgoCD build and deployment pipeline.

## Acceptance Criteria

- [ ]  Automation to tag and release CMS application code is migrated from Jenkins to one conforming to the new build /release/deploy system.

## Implementation Details 

Currently during Production deploys a special Jenkins job tags and creates a release in the CMS-VA.Gov repository. This automation will now need to be tied to the new pipeline for building and deploying the CMS application.

**Comment by olivereri** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VAgov-CMS-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/6463?planning-poker) with ZenHub @ElijahLynn @indytechcook @ndouglas

**Comment by jkalexander7** [comment]
No longer needed.
