### ISSUE TITLE
Create Automation to Build and Push new containers to ECR Repository for EKS Onboarding Process with Ops

### ISSUE THREAD

**Issue by olivereri** [department-of-veterans-affairs/va.gov-cms#6464]
## Description
As a CMS Devops Engineer, I need to create automation to build a container image with application code and push it to ECR, so that that the new ArgoCD software can deploy the new image to EKS.

## Implementation Details 

Github Actions can be used to make this happen:
https://github.com/department-of-veterans-affairs/vsp-infra-grafana/blob/master/.github/workflows/ci-cd.yaml

## Acceptance Criteria

- [ ] Automation is created to build and push new containers to ECR
- [ ] Container images are tagged with semantic version number
- [ ] Container image tags DO NOT use `latest`

**Comment by ndouglas** [comment]
```
docker tag dsva/cms-drupal:latest 008577686731.dkr.ecr.us-gov-west-1.amazonaws.com/dsva/cms-drupal:<version>
docker push 008577686731.dkr.ecr.us-gov-west-1.amazonaws.com/dsva/cms-drupal:<version>
```

**Comment by jkalexander7** [comment]
No longer needed.
