### ISSUE TITLE
CMS IAM Service Account for EKS Automation has Permissions to Read from AWS Parameter Store for onboarding process with Ops

### ISSUE THREAD

**Issue by olivereri** [department-of-veterans-affairs/va.gov-cms#6473]
## Description
As a CMS Devops Engineer, I need the CMS IAM Service Account to have AWS IAM Permissions to readparameters in AWS Parameter Store , so that automation scripts can read application, config, and deployment parameters needed for builds and deploys on EKS.

## Acceptance Criteria

- [ ] Create CMS IAM Service Account that has permissions to Read parameters on AWS Parameter Store.

## Implementation Details
- Ops currently defines the EKS service account permissions [here](https://github.com/department-of-veterans-affairs/devops/blob/master/terraform/environments/global/iam_gha_resources.tf)
- CMS already has a Github Actions IAM user as a Service Account and permissions defined here.

**Comment by olivereri** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VAgov-CMS-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/6473?planning-poker) with ZenHub @ElijahLynn @ndouglas

**Comment by jkalexander7** [comment]
No longer needed.
