### ISSUE TITLE
[SPIKE] Secrets and Parameters needed for CMS stored in AWS Systems Manager Parameter Store

### ISSUE THREAD

**Issue by olivereri** [department-of-veterans-affairs/va.gov-cms#6474]
## Description
As a CMS Devops Engineer, I need to input secrets, build, config, and deploy parameters into AWS Parameter Store, so that they are available for the EKS build, release and deploy pipeline.

## Acceptance Criteria

- [ ] Team has met to discuss what secrets and parameters should be stored in AWS Parameter Store.
- [ ] Necessary secrets, build, config, and deploy parameters are added to CMS' AWS Parameter Store name space.

## Implementation Details
- Ops uses this pattern in GitHub Actions.

**Comment by jkalexander7** [comment]
No longer needed.
