### ISSUE TITLE
Create Initial Decision Document for Logic in API vs Front End

### ISSUE THREAD

**Issue by indytechcook** [department-of-veterans-affairs/va.gov-cms#6490]
## Description

Create a Decision Document to be used for evaluation of a Product vs Raw JSON API.  The format should follow the [AP - Solution Options Matrix](https://docs.google.com/spreadsheets/d/1qrXyjnED4aaJuQ0AgqHHFK2RMjjqeAP1GL1hw5lo0tU/edit#gid=0).  

**This decision document should not include technology choices.**  

Criteria should include perspective from Platform CMS Team, Sitewide CMS Teams, Product Teams (public websites and facilities), Lighthouse team, and other platform teams.    Possible artifacts could also include possible workflow diagrams.

## Acceptance Criteria
- [x] Create Google Spreadsheet with Criteria
- [x] Come up with evaluation Criteria
- [x] Review Criteria with team Platform CMS Team
- [ ] PO has Approved Criteria

**Comment by jefflbrauer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VAgov-CMS-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/6490?planning-poker) with ZenHub @indytechcook @timcosgrove @ElijahLynn @ndouglas @olivereri

**Comment by timcosgrove** [comment]
"Logic in API vs Front End": I think it's worth sitting down and digging in on what is different between these approaches:
* What logic are we talking about here? What business logic currently happens, or needs to happen? 
* In the 'Front End' logic case, what does that mean for the Drupal-side API? Is it literally just a no-effort exposure of any and all entities?
* In the Logic in API, where does that logic live? What team or teams are responsible for implementing and maintaining it?

**Comment by timcosgrove** [comment]
Spreadsheet superseded by https://vfs.atlassian.net/wiki/spaces/PCMS/pages/1964670998/CAPI+API+business+logic+location
