### ISSUE TITLE
Add field_fapi_validate field to all facility types

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#6517]
As a facility data manager I need a flag that can be set by hand or by automatic process that flags a facility as needing someone to look at it so that I may raise it with a View/dashboard.

Discuss and decide if this should be
A) ~Boolean checkbox field_fapi_validate - >"Please validate this facility"  (language to be finalized with UX)~
B) ~a multi select that has different values that would describe what needs validating ~
C) Add flag field to all facility nodes
    * empty value (no action needed)
    *  New facility 
    * Title changed
    * ~Needs office~ not needed as it would be covered by "New facility"
    * Needs services  - Could be covered by "New facility"  depends on the workflow.  Would the same person that connects the system and section be the one who is adding services?
    * ~Request to close~  tabling this for its own issue
    * Not in Facility API
    * Closure complete (this is needed so the facility does not keep bubbling up in automated checks).

Visibility rules on this field.
- only visible on edit
- for non-admins all options should be visible but  field should be disabled unless
   - ~field is empty(no action needed) or is Request to close, those should be the only available options~ removed since "Request to close" is not being implemented.   

This flag would be set in cases like (these actions will be defined and built  in another ticket):
1. When the facility is created the "create" event would set it.
2. Whenever a save changes the title
3. on save whenever no field_office is set.

**Comment by jefflbrauer** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VAgov-CMS-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/6517?planning-poker) with ZenHub @cweagans

**Comment by swirtSJW** [comment]
This is being closed in favor of true flags  https://github.com/department-of-veterans-affairs/va.gov-cms/issues/7250
