### ISSUE TITLE
Make view/dashboard to show any facilities or forms that are flagged

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#6518]
As a facility admin or forms admin I need a way to see and work with any facilities that are flagged so that I may efficiently execute the appropriate runbook.

The view should:
1. List of all facilities or forms that are flagged.
2. Show title, facility_locator_id, content type, moderation state, field_administration, edit link, last updated date and user.   Ordering of columns should look like /admin/content  (any column that can be sortable should be).
3. Have exposed filters for section, title, moderation state.  (filters should look like /admin/content.)

See [prototype in this google doc](https://docs.google.com/document/d/12BzNme4eFi-jdVrpoyMVXdfBD700IlD0LyXzrFW2LjA/edit#heading=h.inuamhnjcxlw), although it conflicts with spec below. 

We'll need to create sample content locally and in tugboat that represents each of the flags and a smattering of content types (a couple VA Forms, a few of the 7 Facility types).

## AC

- [x] View name:  Flagged  Content
- [x] path: /admin/content/flagged
- [x] display machine name should not be `default`
- [x]  limit to 0 per page, paginated.
- [x] Show result count in header.
- [x] default sort is last update (newest at top)
- [ ] columns
  - [x] Title (sortable)
  - [x] Edit button
  - [ ] Flags (maybe with pretty colors per flag)
  - [x] Content type (sortable)
  - [x] Moderation State 
  - [x] Section (field_administration) (sortable)
  - [x] Is Locked
  - [x] Last updated  (date time and by user) (sortable) OR Last revision and revision message (see prototype)
- [ ] filters 
  - [x] Type VAMC Facility, NCA Facility, VA Form, VBA Facility, Vet Center, Vet Center - Mobile Vet Center, Vet Center - Outstation
  - [ ] Flagged
  - [x] Contextual filter should only show what sections user has access to.  
  - [ ] Do not show any that are flagged "Removal complete"  
    - [ ] Stretch: being able to make them show with when selected in exposed filter
  - [ ] OR field_ofice is empty (To catch any facilities that are already in, but not assigned to a system)
- [ ] exposed filters (filters should look like /admin/content.)
   - [x] Apply button should say "Filter"
   - [x] reset button says "Reset"
   - [x] Content Type (allow multiple)
   - [ ] Flag
   - [x] Section

**Comment by jefflbrauer** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VAgov-CMS-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/6518?planning-poker) with ZenHub @cweagans

**Comment by swirtSJW** [comment]
Updating the AC's based on a bit of Flags discovery
- [x] View name:  Flagged  Content
- [x] path: /admin/content/flagged
- [x] display machine name should not be `default`
- [x]  limit to 50 per page, paginated.
- [x] Show result count in header.
- [x] default sort is last update (newest at top)
- [x] columns
  - [x] Title (sortable)
  - [x] Edit button
  - [x] Flags (maybe with pretty colors per flag)
  - [x] Content type (sortable)
  - [x] Moderation State 
  - [x] Section (field_administration) (sortable)
  - [x] Is Locked
  - [x] Last updated  (date time and by user) (sortable) OR Last revision and revision message (see prototype)
- [x] filters 
  - [x] Type VAMC Facility, NCA Facility, VA Form, VBA Facility, Vet Center, Vet Center - Mobile Vet Center, Vet Center - Outstation
  - [x] Flagged
  - [ ] ~Stretch: Contextual filter should only show what sections user has access to.~ A user's section is not available contextually. 
  - [x] Do not show any that are flagged "Removal complete"  
    - [x] Stretch: being able to make them show with when selected in exposed filter
  - [ ] ~OR field_ofice is empty (To catch any facilities that are already in, but not assigned to a system)~ Not attainable.  Views does not allow to two groups with an AND and one group with an OR.
- [x] exposed filters (filters should look like /admin/content.)
   - [x] Apply button should say "Filter"
   - [x] reset button says "Reset"
   - [x] Content Type (allow multiple)
   - [ ] ~Flag~  Flag architecture does not allow for this.  Not needed for this use case.
   - [x] Section
