### ISSUE TITLE
Notify CMS facility support of facility changes/flags

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#6520]
When a facility title is changed. People should be notified so they can validate and carry out the changes needed.

~Lowest lift:~
  ~A. Notify slack channel (What channel?, Who should it mention?)~ 
  -  ~link to the revision diff in Drupal would be nice~

~Higher lift because it depends upon email notification queue  system.~
~B: email people   ~
   - ~who? how would we know programmatically who to email?~

**updated 4/29/22**  Now that we have the capability of notifications through the messages stack we should use this system to email CMS support in the event changes are made to facility nodes.  This allows us to eat our own dog food as we would be our own consumers of thes new capabilities

## blockers
1. Can cms send to helpdesk email   (needs va.gov ideally goes to jiraa and autocreates ticket)
2. email text for facility created
3. email text for facility title change
4. email text for facility removed from FAPI
5. merge of https://github.com/department-of-veterans-affairs/va.gov-cms/pull/8841 so the architecture and pattern is present.

## AC
- Email message is sent to CMS user support when:
   - [ ] a new new facility is created
   - [ ] a facility has a name change
   - [ ] a facility is removed from the Facility API.
- Message details include 
  - [ ] What changed
  - [ ] A link to the affected node.
  - [ ] Time/date
  - [ ] Link to the flagged dashboard.

**Comment by EWashb** [comment]
This work seems to be completed through #9097. Unless I'm missing something, I suggest to be closed as I clean up the epic backlog for current message stack MVP.

**Comment by swirtSJW** [comment]
Closed as this was completed in #9097
