### ISSUE TITLE
Remove endpoints for VAMCs getting redirected September 29 / during Sprint 42

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#6532]
## Description

Tentative schedule for September 29 redirects:

- eastern colorado
- fayetteville arkansas
- palo alto
- ~alexandria~
- ~gulf coast~
- ~southeast louisiana~

Week of Oct 6: 
- Montana, Cheyenne, New York harbor, Central Iowa, Augusta, Columbia South Carolina, Charleston, West Texas, Black Hills, Richmond, Hampton

The final list will appear in #vamc-upgrade channel

## Acceptance Criteria
- [ ] Once redirects have been completed, remove endpoints for facilities.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Platform Team`
- [x] `Sitewide CMS Team`

**Comment by swirtSJW** [comment]
Needing removal now.
eastern colorado 
fayetteville arkansas
palo alto

**Comment by swirtSJW** [comment]
Ignore  ^^^ already covered by https://github.com/department-of-veterans-affairs/va.gov-cms/pull/6600
