### ISSUE TITLE
Change logic on staff profile pages to use field_complete_biography_create

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#6549]
## Description

As a CMS editor I would like the front end page to render using the same controls I use in the CMS

**current:** The front end page for staff profiles are only created if both field_complete_biography_create and field_body are populated

future: The front end page for staff profiles are only created if field_complete_biography_create is TRUE.  The addistional logi of required the specific fields should only be handled by the CMS, not the FE.

## Acceptance Criteria
- [ ] The creation of staff profile pages on the FE is dependent on ONLY field_complete_biography_create being TRUE.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Platform Team`
- [x] `Sitewide CMS Team`

**Comment by swirtSJW** [comment]
@ethanteague Can you support Amandeep with setting up his local and working this through to having him submit a PR to the content-build repo.

**Comment by amandeepma** [comment]
@ethanteague I have setup my CodeSpaces workplace on my laptop. I'm now ready to work on this ticket. Can we please do a little KT session on this? Thanks
