### ISSUE TITLE
Design VistA/Cerner field UI and guidance for VAMC system AND VA health connect

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#6572]
See user stories at #6571 

## Background

* VAMC system content type
  * Health Records field
    * VISTA = Veterans Health Information Systems and Technology Architecture 
    * Cerner =  Cerner EHR
    * Cerner - staged = For systems that are going to Cerner soon.
    * Data for this field is coming from the [EHR Modernization effort](https://vww.ehrm.va.gov/)
  * VA Health Connect phone number field
    * just a basic phone number
    * Data comes from OVAC - Office of Veteran Access to Care (VHA)

<details><summary>Screenshot</summary>

<img width="962" alt="Edit_VAMC_System_VA_Eastern_Colorado_health_care___VA_gov_CMS" src="https://user-images.githubusercontent.com/643678/152398544-68fcb86f-5a1c-4de6-b8a2-715d5757db53.png">

Claro, with placeholder for the phone number field.

You can see this at https://main-eyjs0sncpqkjhpxgnkuhzayuve040hg6.demo.cms.va.gov/node/318/edit

<img width="895" alt="Edit_VAMC_System_VA_Pittsburgh_health_care___VA_gov_CMS" src="https://user-images.githubusercontent.com/643678/153068052-4ac48976-6bed-41ed-a983-a98bd0838df0.png">

</details>

## ACs
- [ ] Field should be editable by admins
- [ ] Help text 
  - [ ] that messages "if you see something wrong, contact CMS help text"
  - [ ] Context for what this is. 
- [ ] Should we worry about labels being used? Not necessarily. 
  - [ ] Does Vista make sense?
  - [ ] Can "Cerner - staged" be more clear? "Cerner testing in progress"

## Old notes

- [ ] Validate the names of these systems among editors(Spokane?). Also relevant: Corresponding Veteran names "My HealtheVet" and "My VA Health", which is what PAOs may relate to. 
- [ ] Field label and help text has been written to support the fulfillment request service designed in #6574.
- [ ] Placement on the "VAMC system" content type form has been determined.
- [ ] Default field value is "VistA", but admins can toggle it to "Cerner"
- [ ] Field is disabled but readable to non admins.

**Comment by EWashb** [comment]
First design draft: https://www.figma.com/file/pHiMENf7tRBWNCrONWI1J2/VistA%2FCerner-for-VAMC-%26-VA-Health-Connect?node-id=0%3A1

**Comment by EWashb** [comment]
Passed design to @ethanteague ![Screen Shot 2022-02-17 at 12.46.30 PM.png](https://images.zenhubusercontent.com/614b6cbe05afafb268be4c0b/95a4344e-161d-45c3-85c8-1727cb665228)
