### ISSUE TITLE
Design and document fulfillment request for updating VAMC EHR systsem

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#6574]
See #6571 for context

ACs
- [ ] CMS Helpdesk has a documented workflow for request fulfilment for updating the EHR system for each VAMC system
- [ ] The UX writer for #6572 can reference this as part of the editorial experience.

**Comment by cmaeng** [comment]
Proposed steps:

1. Request comes in to the CMS helpdesk from whoever
2. CMS helpdesk verifies with PO
3. Once verified, CMS team flips the switch
4. CMS helpdesk send confirmation to requestor
