### ISSUE TITLE
Helpdesk onboarding documentation

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#6583]
##
- [x] assess current helpdesk documentation on Github and Google Docs for accuracy, usability
- [x] update outdated documentation
- [x] archive or remove unnecessary/inaccurate documentation
- [x] make documentation available on either Github or Google Docs
- [x] develop a schedule for regular updating of helpdesk documentation

**Comment by xiongjaneg** [comment]
[Google Drive helpdesk folder](https://drive.google.com/drive/folders/1opC6DgZyBQ6uEVzIz3FWmISMLt-Y91ts)

[Github helpdesk folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/cms/helpdesk)

**Comment by chriscraiga6** [comment]
Assessment: 
Current Documentation's varies in accuracy as portions of documents are outdated while others are still accurate. 
This will be an on-going task to update all documentation. 

Archived Outdated Documentation: An Archive has been created and the documentation is being reviewed for accuracy.

Documentation Availability: Documentation is available in both Google Drive and Github however Google Drive will be the home of all day to day process documentation.

Schedule: Once all documentation is updated, the documentation should be reviewed quarterly. Until the documentation is updated though, this will be an everyday task to update our documentation.
