### ISSUE TITLE
Establish regular schedule of helpdesk check-ins

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#6584]
## User story
As a helpdesk team member and delivery manager (and a potentially the product manager), I need to communicate any priorities, concerns, or opportunities and stay in touch with larger CMS team news.

## Acceptance criteria
-  [ ] Determine appropriate frequency (weekly, once per sprint)
- [ ] Determine appropriate length (30 min, 1 hour)
- [ ] Determine meeting structure (scrum, chat, happy hour)
- [ ] Create recurring meeting and add attendees

**Comment by stefaniefgray** [comment]
30 minutes weekly, "How's helpdesk going?" sounds good -- Chris/Clarence/Stefanie
