### ISSUE TITLE
UX team members gain helpdesk context during onboarding

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#6586]
## User story
As a new Drupal CMS team member, I need to understand the customer journey through the Drupal CMS helpdesk process.

@EWashb @rachel-kauff @suzanne-gray

## Acceptance criteria
- [ ] An initial meeting between new UXers and existing helpdesk to overview tickets
  - [ ] Can they access and navigate the KB
  - [ ] Can they submit helpdesk tickets
  - [ ] Is there any feedback on the submission form
- [ ] UXers have an understanding of the kinds of tickets get submitted by users

**Comment by stefaniefgray** [comment]
Rachel has returned from residency program and we've all returned from the holidays; planning new meeting with @EWashb , @suzanne-gray and @rachel-kauff

**Comment by stefaniefgray** [comment]
@xiongjaneg Hi! We've already started having monthly check-ins between the UXers and the helpdesk team, and have discussed in great detail some of the issues faced by users when it comes to UI/UX -- is there anything else that needs to be done regarding this ticket, or can it be closed?

**Comment by stefaniefgray** [comment]
Discussed with Suzanne/Erika of UX team, we realized that this ticket has already been moving along :) ^^

**Comment by xiongjaneg** [comment]
@stefaniefgray Sounds great! Thanks for the follow up.

**Comment by stefaniefgray** [comment]
Closing issue since the UX team has heard quite a bit about helpdesk during our 3-4 meetings so far about it :)
