### ISSUE TITLE
Content API Architecture Update

### ISSUE THREAD

**Issue by indytechcook** [department-of-veterans-affairs/va.gov-cms#6593]
## Description

Update the Content API architecture diagram:

* Add background information of "why"
* Update terms to be "URL" instead of "API"
* Add details around the security (GET ONLY, WAF, Auth)
* Rename SDK to "React Components"
* Remove monorepo
* Versioning
* API Gateway details / Route Proxy
* Abstracting the Drupal API
* How we following Zero Trust

## Acceptance Criteria
- [ ] Content API diagram updated (LucidChart)
- [ ] Updates added to Confluence

**Comment by jefflbrauer** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VAgov-CMS-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/6593?planning-poker) with ZenHub @cweagans
