### ISSUE TITLE
Training for CMS team members to back up helpdesk

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#6594]
## User stories.
- As a Drupal user, I need timely help to provide information to Veterans and other stakeholders.
- As a CMS team member providing back up on helpdesk, I need to understand helpdesk processes to provide timely help to Drupal users.
- As a helpdesk team member, I need to be able to take a vacation.

## Acceptance criteria
- [ ] identify training topics and content
- [ ] identify CMS team members interested in backing up helpdesk
- [ ] prepare training materials
- [ ] present training
- [ ] set up Jira accounts for trained team members

**Comment by jefflbrauer** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VAgov-CMS-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/6594?planning-poker) with ZenHub @cweagans

**Comment by cmaeng** [comment]
audience = volunteers from both Platform CMS and Sitewide CMS teams.

**Comment by stefaniefgray** [comment]
Volunteers = Erika and Suzanne

Now figuring out training times and agenda

**Comment by stefaniefgray** [comment]
Current volunteers:
- Erika Washburn
- Suzanne Gray
- Wesley Rowe

60-minute Tier 1 intro to helpdesk training session planned for January 28th unless otherwise rescheduled

**Comment by stefaniefgray** [comment]
Training took place Mon Feb. 7 with Erika, Suzanne and Wes

Still finishing up Tier 1 helpdesk basic coverage guide: https://docs.google.com/document/d/1cFxxwZg1lsP3EwDWSbfLM9L8EXzZ7WvpfO7aruW1v54/edit?usp=sharing

**Comment by stefaniefgray** [comment]
Finished guide to covering Tier 1 helpdesking: https://docs.google.com/document/d/1cFxxwZg1lsP3EwDWSbfLM9L8EXzZ7WvpfO7aruW1v54/edit?usp=sharing

Needs review

@xiongjaneg Please let me know if this ticket can be closed - thank you!
