### ISSUE TITLE
Test results of new menu query including node data

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#6599]
## Description
A front end PR is going to be created that will add moderation state for entities to the query as needed to solve this issue
https://github.com/department-of-veterans-affairs/va.gov-team/issues/29782

There is a risk to this change to the query since more than 140 menu calls to graphQL will then be loading nodes for each item in the menu.
Prior to merging the FE PR we need to make sure the added node loads will not put the content-build or the CMS at risk.

Related CMS issue that introduced the graphql_menu module to our codebase https://github.com/department-of-veterans-affairs/va.gov-cms/issues/6561

## Acceptance Criteria
- [x] The content build has been evaluated in test.prod.cms.va.gov to evaluate the performance of the content release using the new modified menu queries.
- [x] Approval of the FE PR is either granted or denied based on the results of the testing, consulting the Govt PO if needed.
- [x] Directions for this kind of content build performance testing is documented in the repo (or elsewhere) and linked from this issue.

**Comment by swirtSJW** [comment]
This will block the FE PR being merged.  However this is not urgent as the result of not merging it, is just more broken lnk errors when someone leaves an unpublished node in the menu.

**Comment by jefflbrauer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VAgov-CMS-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/6599?planning-poker) with ZenHub @ElijahLynn @indytechcook @ndouglas @olivereri @timcosgrove

**Comment by indytechcook** [comment]
The performance testing is complete.  Here are the results.

We ran the `content-build` on https://test.prod.cms.va.gov with the current version and again with the the new branch.

|                                       | Cold Cache       | Warm Cache |
|---------------------------------------|------------------|------------|
| Current                               | 3 min 49.967 sec | 8.882 sec  |
| vamc-filter-side-nav-facilities-29782 | 3 min 51.868 sec | 8.938 sec  |

The difference is 1.901 seconds which is in acceptable range.

**Comment by indytechcook** [comment]
Documentation: https://vfs.atlassian.net/wiki/spaces/PCMS/pages/1965031906/Analyzing+Frontend+Build+Performance
