### ISSUE TITLE
FE Template is producing the same heading ID for "Related links" fields

### ISSUE THREAD

**Issue by cmaeng** [department-of-veterans-affairs/va.gov-cms#6603]
**Describe the defect**
It appears that the templates are auto-generating the same heading ID for "Related links" fields when the content is identical. This is tripping the accessibility scans as duplicate h2 id errors.

**To Reproduce**
1. Go to 'https://prod.cms.va.gov/node/7632/edit'
2. Scroll down to see the "Related links" section
3. Notice that the "Title" field and the "Link text" field have the same content
4. Viewing the FE at https://www.va.gov/alexandria-health-care/work-with-us/internships-and-fellowships/ the page generates duplicate h2 & h3 ids for the two fields

**Expected behavior**
If the template is going to auto-assign h2 ids for this content, they ought to be unique.

One possible mitigation is to prefix the id with the template name.

**Screenshots**
In the CMS: ![image (31).png](https://images.zenhubusercontent.com/5e3ad9b2c4b3070f908bf89c/fd1e8374-dad3-43e4-8de1-6d215329743e)

On the FE:
![image.png](https://images.zenhubusercontent.com/5e3ad9b2c4b3070f908bf89c/4e1e9fda-abba-4d70-86ec-90a1f0d3f656)

**Desktop (please complete the following information if relevant, or delete):**
 - OS: Windows 10
 - Browser Chrome

**Additional context**
Slack thread discussing: https://dsva.slack.com/archives/C01RAS1KAQK/p1633101834054100

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Defect")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS objective (orange) (not needed for bug tickets)
- [ ] CMS-supported product (black)

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Platform CMS Team`
- [x] `Sitewide CMS Team`

**Comment by davidconlon** [comment]
@cmaeng I think that this may be more of a problem with the component that can be used site-wide in the CMS and not something that all of our front-ends can protect for - such as I think this is/will be a popular component for the whole of the CMS.

If the intent is this component allows the editor to enter a Title for that section as well as free-text link, then I suspect that may inherently be a problem with any FE application using these types of landmarks and the CMS will need to prevent that from happening.

We likely want to think this through from a BE-to-FE component analysis to protect for this in the CMS rolling forward.

**Comment by cmaeng** [comment]
Update: this applies for any VAMC Detail page with "Related Links". Basically, because the FE auto-assigns heading IDs for the "Title" and "Link text" fields, they all need to be unique in order to pass the daily accessibility scans.

Short term solution might be to draft a KB article explaining to editors.
Medium term solution might be to insert inline help text to let editors know to keep these fields unique.
Long term solution might be to create custom field logic so that these validate as unique before editors are able to publish.

e.g. helpdesk tickets: [VAHELP-2249](https://va-gov.atlassian.net/browse/VAHELP-2249), [VAHELP-2625](https://va-gov.atlassian.net/browse/VAHELP-2625)

**Comment by laflannery** [comment]
Closing as this is no longer an issue - the FE identifies the possible duplicate ID and adds a unique identifier to avoid this issue:
![image](https://user-images.githubusercontent.com/106678594/236859850-90ed46c4-c534-47f6-9999-bfb486777336.png)

![image](https://user-images.githubusercontent.com/106678594/236860010-4a290ebc-c800-4efd-ac7a-0ff4d6f508ac.png)
