### ISSUE TITLE
Existing `a.usa-button*` have been migrated to use `a.vads-c-action-link`, where desired

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#6619]
## Background

As of 6/1/2022 ([slack](https://dsva.slack.com/archives/CT4GZBM8F/p1655474495809019) for context), the Design System Team is deprecating the va-button-primary Design System CSS class and its associated styles. The [button component page](https://design.va.gov/components/button/) offers alternative options. Action links have also been [deployed](https://design.va.gov/components/link/action). 

FE buttons are now marked as "use with caution: candidate." they should not be used for CTAs or non-actions.

Currently 217 uses of usa-button on published nodes, mostly within the non-hardened Billing and Insurance and Register for care Pages. Once those have all been converted to their new content types, there won’t be many left. But we should look at deprecating usa-button in the CMS in Q3

**Context from 10/2021**
from the [design system](https://design.va.gov/experimental-design/action_links) `Note: Action links will be replacing green primary buttons that link to another page.`  This implies a change in some cases but not all.   We will have to audit the existing cases to see that they apply.  

Waiting to flesh this out to see if this level of content alteration is requested.  We also many want to hold off on this until action_links are no longer considered "experimental."

## Things to consider for deprecating the BE Button

- [ ] Change management (changing buttons to actions links) 
- [ ] Announcement block placement or other CM tool to alert the change?
- [ ] auditing places where buttons appear and notate the FE dependency
- [ ] Make the FE changes
- [ ] KB update?

**Comment by EWashb** [comment]
Update from design system team from 6/17: they are deprecating the va-button-primary design system CSS class and its associated styles.

**Comment by laflannery** [comment]
I'm closing this in favor a the more recent and relevant epic mentioned above
