### ISSUE TITLE
Research synthesis 

### ISSUE THREAD

**Issue by rachel-kauff** [department-of-veterans-affairs/va.gov-cms#6627]
## Background
Task of #6553 

## Acceptance Criteria
- [x] Research synthesis completed
- [x] Research readout deck prepared
- [x] Research readout scheduled to be delivered to the following audiences:
   - [x] Product owner
   - [x] Facilities team folks - Michelle
   - [x] Sitewide CMS 
      - [x] Customer service - Jane, helpdeskers
      - [x] Content ops folk
      - [x] All other sitewide cms team members invited but optional

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Platform CMS Team`
- [x] `Sitewide CMS Team`

**Comment by jefflbrauer** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VAgov-CMS-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/6627?planning-poker) with ZenHub @cweagans

**Comment by kevwalsh** [comment]
@EWashb @suzanne-gray can y'all add the research [here](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/cms/research)? Then close this out.

**Comment by EWashb** [comment]
Research added [here](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/cms/research/vet-center)
