### ISSUE TITLE
Governance and editorial experience for full width alerts and promo banners 

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#6643]
## User Story or Problem Statement

Context: MVP full width banners and promo banners had little editorial experience design, and governance research/design. 

[needs further spec'ing]

**Comment by EWashb** [comment]
@jilladams this feels more Facilities to me. Thoughts?

**Comment by jilladams** [comment]
It's our understanding that PW owns the general Promo banner / Full-width alert experience, per @davidconlon . 

If helpful, we whipped up a [Mural of product ownership by team](https://app.mural.co/t/vagov6717/m/vagov6717/1658961045082/cedcb1c5c42489e47be37733c73890ef890070ae?sender=u252e7152800e3981889d1910) awhile ago, for reference.

**Comment by EWashb** [comment]
That's helpful. Thank you @jilladams! I'm just trying my best to clean up old things.
