### ISSUE TITLE
Audit tables in use for their adherence to new guidelines

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#6645]
Quantiative and qualitiative audit of tables placed in CMS managed content to help evaluate how tables have been used so far.

## ACs
- [x] A report qualitiative and quantitiative report presented to sitewide content team and Sitewide CMS product owner, describing current state of table use in CMS-managed content.
- [x] Quantitative
  - [x] Number of tables by content type 
  - [x] Number of tables by field
  - [x] Number of tables by field by content type

Implementation
- [x] Database queries (Drupal view?)  for what nodes have tables, how many tables, what products those nodes belong to
- [x] Ideally, a link to the www.va.gov page for those, otherwise to the URL in Drupal. 
- [ ] Qualitiative audit by a content strategist. 

This could be split into two tickets, one to create an audit tool, another to do the audit.

**Comment by jefflbrauer** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VAgov-CMS-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/6645?planning-poker) with ZenHub @cweagans

**Comment by kevwalsh** [comment]
@jefflbrauer I removed @cweagans from planning poker, this is a Sitewide CMS team issue. We welcome Cameron's involvement, but i have a feeling you meant to put your last comment on a different issue.

**Comment by msbtterswrth** [comment]
Tables are used for several different content components. 

1. Hours information: `/boston-health-care/programs/covid-19-testing`
2. Residency program stats: `/madison-health-care/work-with-us/internships-and-fellowships/madison-va-cardiovascular-and-pulmonary-physical-therapy-residency` 
3. Benefits Rates: `/health-care/copay-rates/past-rates-2021`
4. Resident lists: `/chicago-health-care/work-with-us/jobs-and-careers/jesse-brown-vamc-pgy1-and-pgy2-pharmacy-residency-programs`
5. Non-table content: `/portland-health-care/programs/progressions-program`
6. Columned lists: `/central-arkansas-health-care/programs/john-l-mcclellan-front-entrance-project`
