### ISSUE TITLE
Some logs getting dropped in Loki

### ISSUE THREAD

**Issue by ElijahLynn** [department-of-veterans-affairs/va.gov-cms#6675]
We have some logs getting timestamped out of order in /var/log/messages and Loki is dropping them. One solution is to move Drupal watchdog logs from /var/log/messages its own logfile in /var/log/drupal. See https://dsva.slack.com/archives/CJYRZK2HH/p1634070213478000?thread_ts=1633357270.287200&cid=CJYRZK2HH. 

### AC:
- [ ] All logs should be logged, none should be dropped. 

### CMS Team

- [x] `Platform CMS Team`
- [ ] `Sitewide CMS Team`

**Comment by jhouse-solvd** [comment]
@ElijahLynn - Hey Elijah! This probably isn't mission-critical, but I noticed that these "out of order" messages are still occurring. It does create noise in production for the Loki log ingester. It could be valuable to do sooner than later depending on the level of effort. 

[Here's a query](http://grafana.vfs.va.gov/goto/PX6N8U0nk) that might be useful to see the logs: 

`{app="loki-distributed",component!="querier",component="ingester"} |~ "entry out of order"`

@f1337 @mchelen

**Comment by TheBoatyMcBoatFace** [comment]
Loki is no longer used. Closing.
