### ISSUE TITLE
Inconsistent presentation of "Where Does This Appear" block

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-cms#6698]
**Describe the defect**
https://dsva.slack.com/archives/CDHBKAL9W/p1634217174062200

Original report:

>I am editing the single Q&A Can I get free health care and prescriptions as a Veteran? in R&S in draft mode. At the top it shows where the Q&A appears on VA.gov. It's saying it appears on VA debt management, but it doesn't. I think it's a bug and shouldn't affect anything if I publish the page but I wanted to make you aware.

URL 1: http://prod.cms.va.gov/resources/can-i-get-free-health-care-and-prescriptions-as-a-veteran

URL 2: https://prod.cms.va.gov/resources/does-va-pay-for-veterans-nursing-home-or-assisted-living-care

The "Where Does This Appear" block appears to be presenting different information to different users.  

I see:
<img width="769" alt="Screen Shot 2021-10-14 at 1 59 08 PM" src="https://user-images.githubusercontent.com/1318579/137371813-d945c145-2a69-4404-99cd-3897a637f18a.png">

whereas Randi sees:
<img width="939" alt="Screen Shot 2021-10-14 at 1 58 40 PM" src="https://user-images.githubusercontent.com/1318579/137371839-ef52ce92-344e-4aea-aaa7-9f1c07d1e528.png">

The latter presentation does not appear to be correct.  For instance, if I perform 

```bash
drush eval '$nid=36635; print_r(\Drupal::entityTypeManager()->getStorage("paragraph")->getQuery()->condition("field_q_as", [$nid], "IN")->execute());'
```

I see: 
```
Array
(
)
```

(see [here](https://github.com/department-of-veterans-affairs/va.gov-cms/blob/f4341c29ad8e998de1dac2fca0b749cdef15c923/docroot/modules/custom/va_gov_resources_and_support/src/Plugin/Block/WhereDoesThisAppear.php#L130))

This, along with some interactive SQL REPL poking around, would appear to indicate that the message is in error and that the original node does not appear on the node mentioned in the block.  _Why_ it appears, though, is a bit of a mystery.

**To Reproduce**
1. Go to [this node](http://staging.cms.va.gov/resources/can-i-get-free-health-care-and-prescriptions-as-a-veteran) as Randi.
2. Observe the block, which apparently should not be there, displaying an incorrect message.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information if relevant, or delete):**

**Additional context**
Add any other context about the problem here. Reach out to the Product Managers to determine if it should be escalated as critical (prevents users from accomplishing their work with no known workaround and needs to be addressed within 2 business days).

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Defect")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS objective (orange) (not needed for bug tickets)
- [ ] CMS-supported product (black)

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Platform CMS Team`
- [x] `Sitewide CMS Team`

**Comment by ndouglas** [comment]
As mentioned [here](https://dsva.slack.com/archives/CDHBKAL9W/p1634311281074600?thread_ts=1634217174.062200&cid=CDHBKAL9W), this may have disappeared after a day.  That's... not really reassuring.

**Comment by EWashb** [comment]
Almost two years later, let's confirm this isn't still happening and close if not.
