### ISSUE TITLE
Review and update KB for upcoming VC launches

### ISSUE THREAD

**Issue by cmaeng** [department-of-veterans-affairs/va.gov-cms#6737]
## Description
With new VC users coming on board, helpdesk folks want to make sure that KB articles are sufficient to guide them through what they need.

As a VC editor, I need authoritative guidance on how to use the CMS, so that I can do my job efficiently and effectively.

## Acceptance Criteria
- [ ] All VC KB articles have been reviewed and updated as needed by the helpdesk crew
- [ ] Michelle M. reviews any updates to VC KB articles before publishing for consistency with the VC content deck
- [ ] Solidify internal processes for VC user creation in alignment with Michelle M.'s onboarding process
- [ ] All internal processes for VC user creation matches what's in the KB and aligns with Michelle M.'s onboarding process

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Platform CMS Team`
- [x] `Sitewide CMS Team`

**Comment by cmaeng** [comment]
this may have been already completed.

**Comment by stefaniefgray** [comment]
@xiongjaneg Is this ticket complete? If not, what else needs to be done? Thanks for your help!

**Comment by stefaniefgray** [comment]
Started KB documentation audit - most Vet Center articles were updated pretty recently but will need Claro screenshot updates and possibly new how-to videos for Claro theme once launched: https://docs.google.com/spreadsheets/d/1RDUVAtG9FN6lX6xSgJ2SaPh5uJHvXI47axqfVklxbzA/edit#gid=0

**Comment by xiongjaneg** [comment]
@stefaniefgray Yeah, I think you can close this one. Updates will be coming as part of the [Claro change management epic](https://app.zenhub.com/workspaces/vagov-cms-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/6751).
