### ISSUE TITLE
Mob heuristic session - compare  vagovadminto vagovclaro

### ISSUE THREAD

**Issue by rachel-kauff** [department-of-veterans-affairs/va.gov-cms#6755]
**User story**
As a CMS user, I can see that the look and feel of the CMS has changed, but on the whole those changes have a neutral or positive impact on my satisfaction and ability to use the cms.

We need to identify any changes we need to make in order to deliver a usable, satisfactory new "look and feel" to our users. 

We'll use this AT framework to document our session: https://airtable.com/applHskzNEaJ4qM7R/tblvm17AmjxYtpwWQ/viw51xsCmfmSgXlOj?blocks=hide

# ACs
- [x] We feel that confident that we have explored the UI in its entirety for regressions that do not meet the "neutral or positive impact" 
- [x] We have created backlog items and prioritized them for the vagovclaro launch

**Comment by kevwalsh** [comment]
@rachel-kauff i converted this from the gap analysis to the mob heuristic session.
