### ISSUE TITLE
Remove endpoints for VAMCs going to full prod week of Oct 25 2021

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#6770]
## User Story or Problem Statement

After VAMCs go to full prod launch (redirects removed), remove the operating status endpoint migration for those systems. 

- [x] Batch A that from Oct 20th
www.annarbor.va.gov
www.battlecreek.va.gov
www.bronx.va.gov
www.centraliowa.va.gov
www.detroit.va.gov
www.iowacity.va.gov
www.miami.va.gov
www.tuscaloosa.va.gov

- [x] Batch B from Oct 27
https://www.va.gov/ann-arbor-health-care/
https://www.va.gov/south-texas-health-care/
https://www.va.gov/long-beach-health-care/
https://www.va.gov/augusta-health-care/
https://www.va.gov/north-florida-health-care/
https://www.va.gov/orlando-health-care/
https://www.va.gov/western-colorado/
https://www.va.gov/tampa-health-care/
https://www.va.gov/saginaw-health-care/
https://www.va.gov/bedford-health-care/

- [ ] Batch C from Nov 3
 VA Illiana health care
 VA Boise health care
 VA Kansas City health care
 VA Martinsburg health care
 VA Loma Linda health care
 VA Spokane health care

**Comment by swirtSJW** [comment]
List just arrived 
- [ ] VA Illiana health care
- [ ] VA Boise health care
- [ ] VA Kansas City health care
- [ ] VA Martinsburg health care
- [ ] VA Loma Linda health care
- [ ] VA Spokane health care

**Comment by netboss** [comment]
@swirtSJW 
Removed group C endpoints:
- https://www.boise.va.gov/locations/facilities.asp
- https://www.danville.va.gov/locations/facilities.asp
- https://www.kansascity.va.gov/locations/facilities.asp
- https://www.lomalinda.va.gov/locations/facilities.asp
- https://www.martinsburg.va.gov/locations/facilities.asp
- https://www.spokane.va.gov/locations/facilities.asp
