### ISSUE TITLE
Migrate facility health service data for Lovell

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#6771]
## Acceptance Criteria
- [ ] Lovell health service data is on prod

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Platform CMS Team`
- [x] `Sitewide CMS Team`

**Comment by swirtSJW** [comment]
This one is still blocked by not having data from Facility upgrade team.

**Comment by swirtSJW** [comment]
Just arrived today.
System Health services
[Lovell_federal_health_care_SHS_final.csv](https://github.com/department-of-veterans-affairs/va.gov-cms/files/7500598/Lovell_federal_health_care_SHS_final.csv
Facility Health services.
[VISN_12_Lovell_federal_FACILITIES_final.csv](https://github.com/department-of-veterans-affairs/va.gov-cms/files/7500601/VISN_12_Lovell_federal_FACILITIES_final.csv)
)

**Comment by swirtSJW** [comment]
Looks like a row or two are off.  But it is easy to see how to fix them.

**Comment by swirtSJW** [comment]
Here is a reference to the data error discussion https://dsva.slack.com/archives/CT4GZBM8F/p1636486265008300

**Comment by JayDarnell** [comment]
Items are now in production:
<img width="1632" alt="Screen Shot 2021-11-19 at 10 11 36 AM" src="https://user-images.githubusercontent.com/21045418/142646723-a875a4b2-7379-4097-9511-0e1f329adc58.png">

<img width="849" alt="Screen Shot 2021-11-19 at 10 12 28 AM" src="https://user-images.githubusercontent.com/21045418/142646738-c824f0a7-fe37-406f-99db-10e4a13e9cd9.png">

<img width="900" alt="Screen Shot 2021-11-19 at 10 13 44 AM" src="https://user-images.githubusercontent.com/21045418/142646751-b5e86c20-4f3d-495f-966a-e2234de65232.png">

<img width="1585" alt="Screen Shot 2021-11-19 at 10 14 41 AM" src="https://user-images.githubusercontent.com/21045418/142646765-5f739c79-ba49-4497-b1f1-bc3f219927f4.png">
