### ISSUE TITLE
Add ddev as another local environment system

### ISSUE THREAD

**Issue by cweagans** [department-of-veterans-affairs/va.gov-cms#6789]
## Description

[ddev](https://github.com/drud/ddev/) is a lightweight local development environment for Drupal and other CMSes. I've found it to be a little more approachable than Lando + it has some nice quality of life features (such as a built-in mutagen integration to make macOS users happy with filesystem performance).

For the time being, we shouldn't switch anything critical over to use ddev, but we can start playing with it. PR will be opened shortly.

## Acceptance Criteria
- [x] ddev has been evaluated
- [x] [documentation](https://vfs.atlassian.net/wiki/spaces/PCMS/pages/1956937732/ddev) added to Confluence
- [x] implementation does not break Lando
- [x] all of existing Lando commands are mirrored

**Comment by mchelen-gov** [comment]
Can we pick either DDEV or Lando so that all developers are using matching tooling?

**Comment by mchelen-gov** [comment]
@cweagans please create followup ticket for DDEV/Lando decision

**Comment by cweagans** [comment]
@mchelen-gov 6858 is open now.
