### ISSUE TITLE
Content Build Information Migrated to Github Actions

### ISSUE THREAD

**Issue by indytechcook** [department-of-veterans-affairs/va.gov-cms#6805]
## Description

Currently, the content-build stats on Grafana are being pulled by parsing the Jenkins logs.  With the migration to Github Actions, the Jenkins is being deprecated and the logic need to move to the Github Action.

![image](https://user-images.githubusercontent.com/121603/139082220-52ef2358-43f8-4a93-87b2-49bd35a06c5d.png)

Slack: https://dsva.slack.com/archives/C02HX4AQZ33/p1635268464032000?thread_ts=1635267337.031800&cid=C02HX4AQZ33

Jenkins Job which parsed metrics: http://jenkins.vfs.va.gov/job/cms/job/cms-content-release-metrics/
Parsing Script: https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/Jenkinsfiles/cms/cms-content-release-metrics.sh

## Acceptance Criteria
- [x] Content Build Metrics are being sent to Datadog
	* Metrics can be found here: https://app.datadoghq.com/metric/summary?filter=content_build
	* Individual graphs can be found by clicking into any individual metric, then clicking "Open in Metrics Explorer" (top right corner of the screen), which will take you to a page like this: https://app.datadoghq.com/metric/explorer?exp_metric=dsva_vagov.content_build.overall.duration

**Comment by jkalexander7** [comment]
Can move to Sprint 46 if needed

**Comment by cweagans** [comment]
PR is open in the content-build repo. Note that the instrumentation that was done in that PR will need to be done in three other files. That has _not_ been done as part of this PR in an effort to stay out of the way of the FE tools team a bit. The work done covers the production environment and it's done in a way that will easily extend to the lower environments when some other things have settled in the content-build repo.

**Comment by indytechcook** [comment]
This is waiting on use getting the datadog API key into SSM and then FE Tools approval.

**Comment by indytechcook** [comment]
Linking https://github.com/department-of-veterans-affairs/content-build/pull/798

**Comment by mchelen-gov** [comment]
AC has not been checked, where is the dashboard visible?

**Comment by cweagans** [comment]
PR that needs to be merged:

* https://github.com/department-of-veterans-affairs/content-build/pull/822 -- this has misc bug fixes + updates the metric namespace to what we'll use for the dashboard (instead of just for testing)

Follow up tasks:

* https://github.com/department-of-veterans-affairs/va.gov-cms/issues/7212
* https://github.com/department-of-veterans-affairs/va.gov-cms/issues/7213

**Comment by cweagans** [comment]
AC checked + links provided above.

**Comment by mchelen-gov** [comment]
fysa these links default to 1hr timeframe which is often blank, after selecing a longer timeframe then the data appears!
 - https://app.datadoghq.com/metric/summary?filter=content_build
 - https://app.datadoghq.com/metric/explorer?exp_metric=dsva_vagov.content_build.overall.duration
