### ISSUE TITLE
Identify existing processes and workflows that involve VAMC Upgrade team

### ISSUE THREAD

**Issue by chriscraiga6** [department-of-veterans-affairs/va.gov-cms#6807]
## User story
As a helpdesk team member, I need to know the processes and workflows for how VAMC Upgrade team supports VAMC editors so that editors will continue to be supported after the Upgrade team transition.

As a VHA Digital Media team member, I need to know the process for supporting VAMC editors in partnership with the helpdesk.

Definition of done = identifying existing processes, not necessarily knowing who will pick them up

## Acceptance criteria
- [x] Document the current triage process from VAMC ticket intake to resolution: co-work
- [x] Schedule meeting with Stan and Lisa to discuss transition and future state with VHA Digital Media: @stefaniefgray 
- [ ] Document future state when Upgrade Team transitions tier 3 support to VHA Digital Media: co-work

**Comment by stefaniefgray** [comment]
https://docs.google.com/spreadsheets/d/1DlZ9TtfmyKjH4xLpf5lQ-P75ZnjyUDN4DFCWZTnzLl8/edit#gid=0

**Comment by cmaeng** [comment]
@cmaeng will clarify if we have the green light to schedule a meeting with VAMC Upgrade to sync on this.

**Comment by stefaniefgray** [comment]
See continued ticket tracking spreadsheet: https://docs.google.com/spreadsheets/d/1DlZ9TtfmyKjH4xLpf5lQ-P75ZnjyUDN4DFCWZTnzLl8/edit?usp=sharing
