### ISSUE TITLE
Analyze ticket data that involve VAMC Upgrade Team for VHA DM to collaborate on

### ISSUE THREAD

**Issue by chriscraiga6** [department-of-veterans-affairs/va.gov-cms#6808]
## User story
As a VAMC editor, I need timely support to provide accurate information to Veterans.

As a helpdesk team member, I need to understand what support the VAMC Upgrade Team used to provide to VAMC editors so I can support editors.

As a VHA Digital Media team member, I need to understand how to support VAMC editors after the Upgrade team transitions support to my team.

## Acceptance criteria
- [x] Compile a report of Jira tickets for VAMC product
- [x] Break down VAMC tickets by topic
- [ ] Break down VAMc tickets by tier 3 (which tickets were triaged to Upgrade Team)
- [ ] Share report with Upgrade Team

**Comment by stefaniefgray** [comment]
See https://docs.google.com/spreadsheets/d/1DlZ9TtfmyKjH4xLpf5lQ-P75ZnjyUDN4DFCWZTnzLl8/edit?usp=sharing
