### ISSUE TITLE
Facilities: update training and Knowledge Base to align with "featured" improvements

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#6814]
## User story
As an editor, I need to know how to prioritize featured content to share with Veterans.

Any existing KB articles that mention Featuring should be updated to reflect: 
* Deprecation of the old mechanism
* How to use the new mechanism

This story may need to become an epic to track individual KB edits / approvals / publishing, tbd refinement.

**Relevant KBs:**
* https://prod.cms.va.gov/help/vamc/how-do-i-feature-a-story-on-my-sites-homepage
* https://prod.cms.va.gov/help/known-issues-affecting-editors
* https://prod.cms.va.gov/help/va-medical-centers-vamcs/about-stories-content-for-vamcs/how-to-add-a-story#undefined

**NOT IN SCOPE: KBs related to Featuring on Events**
These will be handled separately by Public Websites as part of deprecating the old functionality.
* https://prod.cms.va.gov/help/vamc/about-events-content-for-vamcs

## Acceptance criteria
- [ ] review updates to "featured"
- [ ] update KB articles to align with updates
- [ ] update training to align with updates
- [ ] caption trainings
- [ ] publish and link to updated trainingis

**Comment by jilladams** [comment]
This should move into the new Facilities epic when it gets made.

**Comment by mmiddaugh** [comment]
I think this issue has been replaced by Update KB: how-do-i-feature-a-story-on-my-sites-homepage #13795
