### ISSUE TITLE
Interaction design for tooltip component

### ISSUE THREAD

**Issue by rachel-kauff** [department-of-veterans-affairs/va.gov-cms#6834]
# Background
Our existing tooltip patterns need a lot of finessing, and we think it's best addressed later in cms design system customization. 

**Problems with our current tooltips:**
- Breakpoints need consideration
- Balloon should appear to the right instead of the left. It's covering the content with the current implementation.
- It's not very pretty - color / icon size needs consideration
- We haven't considered accessibility for these

**Comment by EWashb** [comment]
The tooltip has now been integrated to the right. However, that implementation does not address the other problems listed.

**Comment by EWashb** [comment]
@laflannery, this is really old. I know you have a lot of thoughts. I cannot remember offhand if you have an accessibility ticket covering this same thing, but if so, I can close this, and we can address it as an accessibility concern.

**Comment by laflannery** [comment]
I do:

- #10223
- #10221
- And it was also [suggested ](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10777#issuecomment-1259936549)but the UX team that the new inline guidance component be considered to replace the tooltips so we will want to look at that when we decide to tackle these
