### ISSUE TITLE
Enable GHA for Manual Release in Production

### ISSUE THREAD

**Issue by indytechcook** [department-of-veterans-affairs/va.gov-cms#6844]
## Description

Enable GHA for Manual Release in Production

## Acceptance Criteria
- [ ] Production Manual Release button uses GHA to publish content to va.gov

**Comment by indytechcook** [comment]
Related: https://github.com/department-of-veterans-affairs/va.gov-team/issues/24193

**Comment by indytechcook** [comment]
Follow up documentation ticket: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/6852

**Comment by oseasmoran73** [comment]
@indytechcook @cweagans When you all get opportunity, please review [PR](https://github.com/department-of-veterans-affairs/content-build/pull/498). This contains both the daily-deploy and the content-release flow
