### ISSUE TITLE
Update Documentation for Manual Content Release

### ISSUE THREAD

**Issue by indytechcook** [department-of-veterans-affairs/va.gov-cms#6852]
## Description

The documentation for how a manual content release is manually triggered outside Drupal is changing.   The CMS team should know how to trigger a content release without using jenkins.

### Current State:

Trigger Jenkins Job: http://jenkins.vfs.va.gov/job/deploys/job/vets-gov-autodeploy-content-build/

### New State: 
Run Github Action Workflow: https://github.com/department-of-veterans-affairs/content-build/actions/workflows/content-release.yml

![image](https://user-images.githubusercontent.com/121603/139693668-9963d6cc-a98d-42d0-a364-24339aadb960.png)

## Acceptance Criteria
- [ ] CMS Documentation Update

**Comment by cweagans** [comment]
https://github.com/department-of-veterans-affairs/va.gov-cms/blob/master/READMES/cms-content-release.md

**Comment by indytechcook** [comment]
Main document has been updated: https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/READMES/cms-content-release.md

**Comment by indytechcook** [comment]
Updated https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/READMES/cms-alerts.md for the content release notifications.

**Comment by indytechcook** [comment]
Updated https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/READMES/upstream-dependencies.md

**Comment by indytechcook** [comment]
Still need to be updated:

- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/blob/e533dc8ec282cc12ff973360531ac5d28d7770c2/platform/cms/accelerated_publishing/content-build/readme.md
- [ ] Search confluence

**Comment by indytechcook** [comment]
> https://github.com/department-of-veterans-affairs/va.gov-team/blob/e533dc8ec282cc12ff973360531ac5d28d7770c2/platform/cms/accelerated_publishing/content-build/readme.md

This document was written very specific for how the content release worked on Jenkins so I renamed it to https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/accelerated_publishing/content-build/content-release-old.md and added a not to the top saying it's deprecated.

I stared working on a new document in Confluence for the GHA version but stopped because how the build works is still changing.  Once the changes stabilize I do want to create a new document.  I do not think this will get done this sprint.  @jkalexander7 would you rather spin up a new ticket to create new detailed documentation of the content release process or more this ticket to the next sprint?

**Comment by indytechcook** [comment]
The FE Tools team has been updating the documentation for the build.  The current iteration is stored here: https://vfs.atlassian.net/wiki/spaces/FTT/pages/1844641889/Deployments.

The FE Tools team is documented the change in https://github.com/department-of-veterans-affairs/va.gov-team/issues/28990
