### ISSUE TITLE
Delete inactive GH teams

### ISSUE THREAD

**Issue by mchelen-gov** [department-of-veterans-affairs/va.gov-cms#6853]
## Description

Active
https://github.com/orgs/department-of-veterans-affairs/teams/vfs-cms-team
https://github.com/orgs/department-of-veterans-affairs/teams/vfs-cms-team-infrastructure
https://github.com/orgs/department-of-veterans-affairs/teams/cms-infrastructure

Inactive
https://github.com/orgs/department-of-veterans-affairs/teams/vfs-cms-team-core
https://github.com/orgs/department-of-veterans-affairs/teams/vfs-cms-team-product

## Acceptance Criteria
- [ ] Testable_Outcome_X
- [ ] Testable_Outcome_Y
- [ ] Testable_Outcome_Z
- [ ] Requires design review

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [x] `Platform CMS Team`
- [ ] `Sitewide CMS Team`

**Comment by mchelen-gov** [comment]
i can't find any place where https://github.com/orgs/department-of-veterans-affairs/teams/vfs-cms-team-infrastructure is being used

**Comment by mchelen-gov** [comment]
related: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/2981

**Comment by TheBoatyMcBoatFace** [comment]
This is being handled by larger org. 
- https://github.com/orgs/department-of-veterans-affairs/discussions/1
