### ISSUE TITLE
Request CMS engineer IAM role/group

### ISSUE THREAD

**Issue by mchelen-gov** [department-of-veterans-affairs/va.gov-cms#6854]
## Description

- all perms from `dsva-vfs-developers`
note: bucket permissions need to be updated for the vets-website / content-build separation i think

- SSH access to cms and cms-test servers
- S3 access to cms and content build buckets
- cloudwatch/cloudfront metrics
- ssm for the cms resource tags

## Acceptance Criteria
- [ ] Testable_Outcome_X
- [ ] Testable_Outcome_Y
- [ ] Testable_Outcome_Z
- [ ] Requires design review

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [x] `Platform CMS Team`
- [ ] `Sitewide CMS Team`

**Comment by mchelen-gov** [comment]
probably we want is a user group for cms engineers that includes the policy `arn:aws-us-gov:iam::008577686731:policy/vsp-frontend-tools-s3access`

**Comment by TheBoatyMcBoatFace** [comment]
This work is not executed by our team. If this is still relevant, shouldn't this be done by DevOps COP? If our team needs to handle, please re-open.
