### ISSUE TITLE
Evaluate ddev as a replacement for Lando

### ISSUE THREAD

**Issue by cweagans** [department-of-veterans-affairs/va.gov-cms#6858]
## Description

Followup to #6789 

I would like to solicit feedback from people who are actively running a copy of the VA.gov CMS locally on whether or not we should switch to ddev. I would appreciate feedback prior to the end of next sprint (Friday, November 19) if possible!

To help this process, I've added a ready-to-use ddev configuration to the project and created some basic [documentation in Confluence](https://vfs.atlassian.net/wiki/spaces/PCMS/pages/1956937732/ddev).

The specific information that I'm looking for is:

* Which OS do you use?
* Were you successful in bringing up the environment with ddev using the documentation in Confluence?
* Did you run into any specific problems while running this environment for day-to-day use?
* Anything else you'd like to add!

I would estimate this testing to take no more than an hour (and that's if you're really thorough).

If you run into any problems, please feel free to ping me in the #cms-team channel in the DSVA Slack. I've previously worked on ddev itself and I built the configuration that's currently in the repo, so I should be able to get you situated pretty quickly.

Personally, I would like us to move to ddev for the speed improvement alone (it's substantial and noticeable on macOS), but I also don't want to unilaterally change everyone's workflow. Based on the feedback here between now and November 19, we'll either switch to ddev and remove the Lando configuration or remove the ddev configuration.

Thanks in advance for giving this a try!

**Comment by swirtSJW** [comment]
This seems done :)  Thanks @cweagans for taking this on.
