### ISSUE TITLE
Show related non-clinical services within the Top task edit forms and proofing

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#6873]
## User Story or Problem Statement

As an editor of my Top task page, i can see what related Facility services i already have in my system, from within any of three respective top task edit pages.

## Acceptance Criteria
- [x] A list of facility nonclinical services tagged with Medical records is listed within the VAMC system Medical Records node form and node view
- [x] A list of facility nonclinical services tagged with Register for care is listed within the VAMC system register for care node form and node view
- [x] A list of facility nonclinical services tagged with Billing and insurance is listed within the VAMC system Billing and insurance node form and node view
- [x] Each of these lists shows the following tables
  - [x] Node title with link to node
  - [x] Moderation State
  - [x] Facility 
  - [x] Edit link

### Iterate on `non_clinical_services` view. 

Will need some contextual filter love to list only the Nonclinical service nodes that are associated with that system AND share the same taxonomy term.  The system relationship can be found via field_facility_location -> VAMC facility content type, and from there, via `field_region_page` to VAMC system.  That VAMC system should match the VAMC system in `field_office` on each of the 3 top task content types.

For example, for Sioux Falls Register for care page, we want to show all the non-clincial facility service nodes that have been added to facilities which are in VA Sioux Falls. This is somewhat already. If you add 8135 (The VA Sioux Falls system node ID), it lists all non-clinical services associated with Sioux Falls. But we won’t have 8135 immediately available when editing a Register for care page.  8135 is the value of the `field_office` entity reference on the Register for care node for Sioux Falls. For this, I think we need to add a Views Token Argument to help set the “Provide default value” to 8135, based on the current URL’s field_office:value:NID, or some custom code equivalent. 

### Place within the editorial experience

Placement TBD, probably within a fieldgroup on each of these content type form and view modes. It will be easier to spec placement once the view is built and working

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [x] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [x] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Platform CMS Team`
- [x] `Sitewide CMS Team`

**Comment by cmaeng** [comment]
@JayDarnell will take a look at the view and then circle back with @kevwalsh  on the placement.

**Comment by JayDarnell** [comment]
Evalutating block_field as a possible solution for view placement: https://www.drupal.org/project/block_field

**Comment by JayDarnell** [comment]
block_field got us close. It worked perfectly for the node view (proofing) but not for node edit. Giving viewfield a review now: https://www.drupal.org/project/viewfield

**Comment by JayDarnell** [comment]
I'm currently quite stuck on this implementation and need some assistance from another developer.
