### ISSUE TITLE
Design improved fieldgroups, field labels, content type descriptions, and submission guidelines for 3 Top task content types

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#6877]

**Comment by swirtSJW** [comment]
Adding a known concern 
What troubles me is the flip flopping of language on what we are creating.
![image](https://user-images.githubusercontent.com/5752113/146491835-730b5b50-8c97-483d-9244-56f47bc06d12.png)
Is it an office, or a service?  Trying to refer to it as both... is going to be a nightmare for training and helpdesk, not to mention general understanding.
![image](https://user-images.githubusercontent.com/5752113/146491938-a526838b-3292-468d-a4ff-f3f4174ccb45.png)
Every place else it is a service.

**Comment by suzanne-gray** [comment]
Closing because the issue Steve raised was resolved with #6879
