### ISSUE TITLE
Design improved form for VAMC facility nonclinical services

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#6879]

**Comment by EWashb** [comment]
Figma Design: https://www.figma.com/file/kWXId7MIDBh5ToX5VqJPBK/%236872-Non-clinical-services-editorial-experience?node-id=100%3A78

**Comment by EWashb** [comment]
Design includes the first iteration of:
Billing and insurance
Register for care
Medica records office

**Comment by EWashb** [comment]
Updated design on link above to replicate a real example.

**Comment by suzanne-gray** [comment]
I think this is done! final designs with annotations here: https://www.figma.com/file/kWXId7MIDBh5ToX5VqJPBK/%236872-Non-clinical-services-editorial-experience?node-id=0%3A1
