### ISSUE TITLE
Implement nonclinical services form design from #6879

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#6880]

**Comment by EWashb** [comment]
Figma file: https://www.figma.com/file/kWXId7MIDBh5ToX5VqJPBK/%236872-Non-clinical-services-editorial-experience?node-id=8%3A42

The Billing and insurance design incorporates the following new editorial experiences:

- Field label with help text
- Card design with the facility name and the location name. 

The location will surface hours, the address, location-specific information such as the building number, as well as any special instructions for the location.  Please note that the design uses an example for a facility with two billing and insurance locations at that specific facility. **Most instances will be one facility with one location.** 
 ![Screen Shot 2021-12-23 at 3.08.00 PM.png](https://images.zenhubusercontent.com/614b6cbe05afafb268be4c0b/250d3e09-9816-4037-a47c-2e867f6c0f6b)

**Comment by EWashb** [comment]
Annotations for billing and insurance label and help text:
![Screen Shot 2021-12-23 at 3.07.28 PM.png](https://images.zenhubusercontent.com/614b6cbe05afafb268be4c0b/82517c6c-492c-4930-b2e6-4aff809e489c)

Field label in bold:
Billing and insurance locations
Help text below label: 
Edit your VAMC billing and insurance location information by clicking the **edit** link. The link will open in a new window.

**Comment by EWashb** [comment]
Card design with annotations: 

![Screen Shot 2021-12-23 at 2.32.43 PM.png](https://images.zenhubusercontent.com/614b6cbe05afafb268be4c0b/e213911d-f157-4fad-8176-3b4865fe86fd)

Location Cards will appear for each facility. 

Facility name will be bolded, followed by a bolded location name (like cashier's office, for example)

The following information will be surfaced underneath the location name in regular type no bold:

- Hours
- Address
- Location information
- Location-specific instructions

"Edit" hyperlink will be at the bottom right corner. This link will open to the form view. It will open a new page.

**Comment by EWashb** [comment]
@JayDarnell I just realized this view would differ depending on which nonclinical service you're looking at. Mostly the changes will be text. So, would it make more sense to have one ticket per service? I don't want to bog down the comments here, but I'm ok with whatever you think is best for your process.

**Comment by EWashb** [comment]
Screenshots have been updated to exclude dummy text and include a real example from VA Wilkes-Barre

**Comment by EWashb** [comment]
If no data exists and needs to be added, please use the following text and sub out the type of service. The "add a location record" sentence should link out to the node. For example:

No medical records location information has been added yet. Add a location record.

**Comment by EWashb** [comment]
**Register for care** text:

Register for care locations
Manage your VAMC register for care location information by clicking the **view** link. The link will open in a new window. 

![Screen Shot 2021-12-30 at 11.18.19 AM.png](https://images.zenhubusercontent.com/614b6cbe05afafb268be4c0b/0ae23841-3e2f-45e8-b482-0eaa66ebf2f2)

**Comment by EWashb** [comment]
**Medical records office text changes:**

Medical records office locations
Manage your VAMC medical records location by clicking the **view** link. The link will open in a new window.

![Screen Shot 2021-12-30 at 11.18.19 AM.png](https://images.zenhubusercontent.com/614b6cbe05afafb268be4c0b/5970e172-370a-48e7-9e67-e1b7cd90c591)

**Comment by JayDarnell** [comment]
@kevwalsh @swirtSJW I have several questions around this issue that are difficult to articulate here and would benefit from a 15-30 minute chat. I need to figure out an efficient mechanism for conditionally displaying fields since some values being displayed are dependent on the values in other fields. I found https://www.drupal.org/project/views_conditional but wondered if we have other views elsewhere with complex conditional logic and maybe I don't need another contributed module.

The hours for VAMC Facilities appear to be tracked using the field_office_hours field which uses the field type "Office Hours" - this is great because it does all the lovely concatenation and simplification of the hours data with a few simple configuration options (example: Monday - Friday: 8:30 am - 4:30 pm) The service location paragraph uses a "Table Field" as its hours field which has no such beautiful concatenation option... this strikes me as problematic for our goals in this issue so I wanted to mull this over with someone (could we change the field type, do we have custom code somewhere to concatenate this cleanly, etc)

**Comment by EWashb** [comment]
@JayDarnell here the figma file reflects the new designs. There are slight changes to other areas on the forms as well, like text changes to phone headers, etc: https://www.figma.com/file/kWXId7MIDBh5ToX5VqJPBK/%236872-Non-clinical-services-editorial-experience?node-id=0%3A1

The following screenshots are for each top task page and include annotations. If you have trouble reading the notes from these, it might be better to go to figma. But, I'm always happy to provide additional screenshots!

Register for care:

![Screen Shot 2022-01-06 at 3.28.36 PM.png](https://images.zenhubusercontent.com/614b6cbe05afafb268be4c0b/2226f0a4-5bd4-4ea9-b2b1-a6a5940fe9b2)

Billing and insurance:
![Screen Shot 2022-01-06 at 3.28.21 PM.png](https://images.zenhubusercontent.com/614b6cbe05afafb268be4c0b/8ae25e7b-8c1b-479f-b76f-a0636c4717c9)

medical records:
![Screen Shot 2022-01-06 at 3.28.04 PM.png](https://images.zenhubusercontent.com/614b6cbe05afafb268be4c0b/221e8c0e-b027-443c-accf-614e16dd4286)

**Comment by JayDarnell** [comment]
@EWashb @suzanne-gray The following screenshot contains work that is not possible. In this screenshot we place the Inquiries by phone about copay balance between the pay online, by phone or mail and pay in person sections. However, these two "sections" are actually part of a single field and as a result cannot be split. I've moved this section above the Inquiries about copay balance accordion.

![Screen Shot 2022-01-12 at 5 22 08 PM](https://user-images.githubusercontent.com/21045418/149232509-abab72c2-55a0-45cb-a791-7427b462d2d9.png)

**Comment by JayDarnell** [comment]
@EWashb @suzanne-gray I also feel like we should hold off on editing this section until our move to claro is finalized and we have a consistent design spec for these cases. As is, I'd need to override the styles for this fieldset alone and it seems logical to me that we should wait, nail down how these fieldsets should look and apply the decision across the entire experience. Thoughts?

<img width="1046" alt="Screen Shot 2022-01-12 at 5 30 13 PM" src="https://user-images.githubusercontent.com/21045418/149233540-ecb90a90-8edd-4ec8-bfff-1e01be852f5d.png">
