### ISSUE TITLE
KB article(s) for Register for Care, Medical Records, Billing and insurance pages

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#6882]
## User story
As a VAMC editor, I need to be able to provide timely and accurate care registration, medical records, and billing and insurance information to Veterans.

## Acceptance criteria
- [x] Billing and insurance KB article drafted
- [x] Medical records KB article drafted
- [x] review changes and updates needed to KB article(s)
- [x] update KB articles

**Comment by xiongjaneg** [comment]
Suzanne drafted for beta
[Medical records](https://prod.cms.va.gov/help/vamc/how-to-create-a-vamc-system-medical-records-office-page)
[Billing and insurance](https://prod.cms.va.gov/help/vamc/how-to-create-a-vamc-system-billing-and-insurance-page)

**Comment by suzanne-gray** [comment]
[Register for care](https://prod.cms.va.gov/how-to-create-a-vamc-system-register-for-care-page)
