### ISSUE TITLE
Training for Register for Care, Medical records, and Billing and Insurance

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#6883]
## User story
As a VAMc editor, I need to provide timely and accurate registration, medical records, and billing and insurance information to Veterans.

## Acceptance criteria
-  [x] review changes and updates needed to training materials
- [x] update training video(s)
  - [x] register for care
  - [x] billing
  - [x] medical records
- [x] caption training video(s)
- [x] share video links for KB articles

**Comment by xiongjaneg** [comment]
For process, [see Slack](https://dsva.slack.com/archives/CT4GZBM8F/p1643931159637589)

**Comment by xiongjaneg** [comment]
[Register for care video](https://youtu.be/PyWBfLEJ4Xs)
[Billing and insurance video](https://youtu.be/TRe5_XiTjzM)
[Medical records office video](https://youtu.be/VflMGtQvzj8)

**Comment by xiongjaneg** [comment]
@rachel-kauff When the top task KB articles are ready, here are video links, if needed

**Comment by xiongjaneg** [comment]
on schedule for March 8 launch
