### ISSUE TITLE
Create a backlog of custom vagovadmin code to port to vagovclaro

### ISSUE THREAD

**Issue by rachel-kauff** [department-of-veterans-affairs/va.gov-cms#6887]
## Description

In order to prepare to implement Claro as the admin theme base, we need to understand what could break as a result of turning Claro on. An inventory of the custom code will help us mitigate risk and identify anything we need to do to ensure a smooth launch.

Inventory should answer these questions:
- What's in there?
- What does it do?
- Do we keep it? (most of it probably) or do we get rid of it 
   - (For example, the Benefits Hubs proofing experience)
- If we keep it, should it get refactored, or can we afford to migrate it in as is and change later? 
   - (For example, some of the custom CSS for the Knowledge Base)

## Acceptance Criteria
- [ ] We have an epic backlog for porting custom SASS, Twig, and other custom theming code to a `vagovclaro` theme.
- [ ] Possible: We have adopted a method for annotating code that has been ported (does that sound right?)

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Platform CMS Team`
- [x] `Sitewide CMS Team`

**Comment by kevwalsh** [comment]
I'm going to call this done... we'll still be adding more to the epic #7022 as we come across more.
