### ISSUE TITLE
Remove "Connect with us" fields from Section vocabulary, and swap out fields on CLP and Benefis Hub Landing Pages

### ISSUE THREAD

**Issue by msbtterswrth** [department-of-veterans-affairs/va.gov-cms#6896]
New fields are there on CLP and Benefits Hub landing page, but they are hidden. 

After migrating the content and updating the FE display, we need to remove the old fields.

### AC
- [ ] Un-hide the new fields on CLP and Benefit Hub landing page
- [ ] Check that all CLP and Benefit Hub landing pages have content as needed
- [ ] Hide the old fields on those node types.
- [ ] Delete fields from the Section vocabulary, which are no longer in use by the FE (possibly best done as a separate PR)
- [ ] Create follow-up issue to delete the old fields that have been hidden, and work on it.

**Comment by kevwalsh** [comment]
@msbtterswrth i updated the ACs a bit based on our convo late last week.
