### ISSUE TITLE
Unplanned Outage Messaging Standardization

### ISSUE THREAD

**Issue by chriscraiga6** [department-of-veterans-affairs/va.gov-cms#6897]
## User Story or Problem Statement

As a member of the CMS Team, I need to be able to send e-mail communication to all active CMS Users of both planned and unplanned outages with standardized messages. 

## Acceptance Criteria
- [x] Create E-Mail Template For Unplanned Outages
- [x] UX Review of language
- [x] Requires internal process article update

## Design principles

Veteran-centered
- [x] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [x] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.

Editor-centered
- [x] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [x] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [x] `Approachable`: Offer friendly guidance over authoritative instruction.
- [x] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [x] `Sitewide CMS Team`

**Comment by kevwalsh** [comment]
Should this be expanded to include Site Alert messaging? The one that was put up during the AWS outage could have been more clear. 

Also, how might we involve some of our UX writers in this initiative.

**Comment by chriscraiga6** [comment]
@kevwalsh The site alert messaging could be included in this, yes. 
We have an outdated document that may be a good starting point. It looks like UX Collaborated on this at one point:
https://docs.google.com/document/d/1F_5wOgZ5Ie1suaFn-blHh83sgTe0pv3P_2ykxILNi2c

**Comment by rachel-kauff** [comment]
I'm really glad this is coming up, and would love to collaborate with customer service on the messaging. It's probably time to revisit the copy/approach described in that document, and explore a holistic approach to our voice, tone, and system-wide messaging.
