### ISSUE TITLE
Create documentation for product teams on metatags: Title, Description, Image, and possibly others.

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#6935]
## ACs
Product teams have the information and understanding they need to make decisions about how to iterate on metatags, given
* their current state on va.gov
* what’s possible in the CMS

## Possible implementation approach
Feach content type that has a page equivalent on va.gov, i could imagine a side-by-side of
* What drupal currently has (and what it has to offer that isn’t currently used)
* What’s in the html on the FE

**Comment by msbtterswrth** [comment]
Working on a sheet based on kev's mural: https://docs.google.com/spreadsheets/d/1zI4pD_5sSocbgyB9D-EUZjfLwZb8pzfZEF68IqvxPXw/edit?usp=sharing

**Comment by msbtterswrth** [comment]
Created a slide deck here for presentation: https://docs.google.com/presentation/d/1ngMDgBaPusKCZJ7qblU_sZXTbpgGk-SOs-1E9nr5mec/edit?usp=sharing
