### ISSUE TITLE
Add Feature flag FEATURE_HEALTH_CONNECT_NUMBER

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#6943]
## Description
As a front end developer I need the feature flag `FEATURE_HEALTH_CONNECT_NUMBER` created but set to FALSE so that I may turn it on in a demo environment and develop against it.

implementation steps:
1. Add it on your local.  
2. Config export
3. Commit the exported file.

## Acceptance Criteria
- [x] /admin/config/system/feature_toggle  shows a feature flag `FEATURE_HEALTH_CONNECT_NUMBER` with no checkbox checked.
- [x] Gaida is notified in [this thread](https://dsva.slack.com/archives/C0FQSS30V/p1636394970275600) that the feature flag has been merged.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Platform CMS Team`
- [x] `Sitewide CMS Team`

**Comment by netboss** [comment]
@swirtSJW To which content type (or entity) should this flag be added?
