### ISSUE TITLE
Update helpdesk documentation references from api@va.gov to KB article on facility basic data

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#6945]
## User story
As a VAMC editor or Vet Center editor, I need to know how to update my basic facility data so that I can provide accurate and timely facility information to Veterans.

## Acceptance Criteria
- [ ] Review existing helpdesk documentation for references to VAST administrator or api@va.gov
- [ ] Update helpdesk documentation to refer to the VAMC and Vet Center KB articles on facility basic data

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Platform CMS Team`
- [x] `Sitewide CMS Team`

**Comment by xiongjaneg** [comment]
Per Dave Conlon request on 11/9/21

**Comment by chriscraiga6** [comment]
@xiongjaneg It appears that the two articles that reference api@va.gov were updated by you recently and are accurate, was Dave's request wanting other details or is this complete? 

Two articles are:
Session 4 of the training - https://prod.cms.va.gov/help/get-training/session-4-facilities

Can I change the name of my health care system or clinic - https://prod.cms.va.gov/help/vamc/can-i-change-the-name-of-my-health-care-system-or-clinic

**Comment by xiongjaneg** [comment]
@chriscraiga6 Thanks for sending these two links. Dave's request is newer than these updates so I'll update them.

**Comment by stefaniefgray** [comment]
@xiongjaneg Hi! What else needs to be done for this ticket?

**Comment by xiongjaneg** [comment]
@stefaniefgray Just any canned responses, helpdesk backup training, etc. Once you and Chris have changed an internal documentation, this can close.

**Comment by stefaniefgray** [comment]
See https://docs.google.com/document/d/1Y7TQ_OM1Zn6rfdOHXSGxUrhP4dK2DemXb5q--tLDw6M/edit#

Canned answers are updated

@chriscraiga6 Let me know how this looks (last page of document, added VAMC and Vet Center instructions) and if there's anywhere else I should add this information; closing ticket for now but can re-open if needed
