### ISSUE TITLE
Invalid links between menu link entities and nodes break content release

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#6948]
When a menu link entity does not have a link to another entity and the GraphQL query attempts to get the menu link, it errors out and causes the content release to fail.

The link between the node and the menu link is recreated when saved either via the node form or the menu link form.

Summary of what has been discovered:

* Titles with `-`
* Titles with `&`
* [Titles with hidden / special characters](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/6948#issuecomment-965947024)
* it seems to be tied to a menu item created for a node in draft.
* Saving the affected menu item in the menu ui fixes it.
* > They are items that someone saved directly in the menu UI, not through a node save, because they go to a non-cms app page. So that means the initial save on either a node save->menu item or menu item save directly are allowing in broken data. Only subsequent saves fix it... so the unpacking sanitization of the data and resaving solves it.
* Possible points of failure to try to reproduce.
  * use of the "Save draft and continue editing" button.
  * Placing the menu item beneath a parent that is unusual (not really sure what unusual is)???
  * Something odd in the node title that ends up in the menu title.

## AC

- [ ] Document details on how to reproduce issue
- [ ] Determine root cause
- [ ] Either PR implemented or new issue created to address issue.

**Comment by swirtSJW** [comment]
A second occurance of breaking took place 24 hours later in the same system menu.  
https://dsva.slack.com/archives/C0MQ281DJ/p1636579777187300
This time the culprit was not underscores.
This is the node with the problem  https://prod.cms.va.gov/portland-health-care/programs/lodging-for-oncology-and-transplant-veterans
and it likely would have been copy and pasted from this page
[Lodging for Oncology and Transplant Veterans](https://www.portland.va.gov/services/Lodging_for_Oncology_and_Transplant_Veterans.asp)   but maybe not from the html version of the page, but maybe from within the Teamsite interface.


It had the menu title of "Lodging for Oncology and Transplant Veterans" which looked fine.   However it created an error in the menu query until I deleted out the menu title and retyped it from scratch.

I have two theories:
1.  The text contained an invisible character or multibyte character looked normal but created an error on rendering the menu query.
2. The database entry for the menu title contained something that un-rendered, was flawed, but when rendered within the CMS was removed, and simply saving the title a second time would have cleansed it. But graphQL was uncleansed and broke.



I did perform a rudimentary copy and paste test
```
 » php -a
Interactive mode enabled

php > $bad = "Lodging for Oncology and Transplant Veterans";
php > $good = "Lodging for Oncology and Transplant Veterans";
php > $result = ($good === $bad) ? "same" : "different";
php > echo $result;
same
```
It looks like the rendered text may have been the same, however the test is pretty weak.  Lots of reasons why they could have ended up the "same".


Regardless of  whether it is theory 1 or 2, I think the root cause is the same.

We have JS that on blur of the node title field, populates the menu title field to match.  I think if someone pastes in a bad title from another source like Teamsite, the JS immediately copies it and puts it into the menu_title without adequately making the text safe (encoding wise) and trimmed.

**Comment by swirtSJW** [comment]
here is the query that was breaking
```
query {
      
    vaPortlandHealthCareFacilitySidebarQuery: menuByName(name: "va-portland-health-care") {
      
  name
  description
  links {
    label
    expanded
    description
    url {
      path
    }
    links {
      label
      expanded
      description
      url {
        path
      }
      links {
        label
        expanded
        description
        url {
          path
        }
        links {
          ...MenuItem
          links {
            label
            expanded
            description
            url {
              path
            }
            links {
              label
              expanded
              description
              url {
                path
              }
            }
          }
        }
      }
    }
  }
    }
  
    }
    fragment MenuItem on MenuLink {
    expanded
    description
    label
    url {
      path
    }
    entity {
      ... on MenuLinkContent {
        linkedEntity(language_fallback: true, bypass_access_check: true) {
          ... on Node {
            entityPublished
            moderationState
          }
        }
      }
    }
  }
```

**Comment by swirtSJW** [comment]
@kevwalsh This failure has occurred  3 times in the past two weeks.  We should consider prioritizing it.

**Comment by swirtSJW** [comment]
Another occurrence here https://dsva.slack.com/archives/C0MQ281DJ/p1639516980111200

Still not clear what is causing these failures
What we know:
* it seems to be tied to a menu item created for a node in draft.
* Saving the affected menu item in the menu ui fixes it.

It is not strictly that it is a draft node... if that were the case we would be seeing these in great numbers daily.


Possible points of failure to try to reproduce.
* use of the "Save draft and continue editing" button.
* Placing the menu item beneath a parent that is unusual  (not really sure what unusual is)???  
* Something odd in the node title that ends up in the menu title.

**Comment by swirtSJW** [comment]
I believe there is a process on the menu item form in the menu UI that fixes the bad data, but the form within the node form does not fix the bad data and likely causes the issue.

**Comment by swirtSJW** [comment]
> I believe there is a process on the menu item form in the menu UI that fixes the bad data, **but the form within the node form does not fix the bad data** and likely causes the issue.

This is not quite right either.  The menu form in the node form does fix it **on a subsequent save**.  I believe this is caused by how/when we are taking the node title and pushing it to the menu title.  Something about that process is bypassing a data clean-up and allowing bad chars in.

**Comment by swirtSJW** [comment]
Update to my theory based on these menu items
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/7735#issuecomment-1021434785
They are items that someone saved directly in the menu UI, not through a node save, because they go to a non-cms app page.  So that means the initial save on either a node save->menu item or menu item save directly are allowing in broken data.  Only subsequent saves fix it... so the unpacking sanitization of the data and resaving solves it.

**Comment by ndouglas** [comment]
The Platform CMS team is bringing this into the current sprint because (after discussions with Sitewide), it was determined that:

- this subject principally affects the content build, which is the responsibility of Platform CMS
- this sort of debugging (database tables, core code, etc) requires resources that are substantially scarcer in Sitewide

**Comment by ndouglas** [comment]
This is pretty easy to reproduce but not yet 100% reliable.  Create a VAMC detail page and click "save draft and continue," and in my testing it seems to create a broken menu link item ~80-90% of the time.  Save the node and it's repaired.  

I dumped the DB before and after re-saving the node and diffed the two:

```
drush sql-dump --ordered-dump --skip-tables-list="cache,cache_*"
```

(note, that should've been `cache*` to skip the `cachetags` table as well.  I omitted changes to that table below)

```diff
< INSERT INTO `content_lock` VALUES (43472,'node','*','und',1454,1643721451);
491517c491518
< INSERT INTO `content_moderation_state` VALUES (43344,611586,'b6a72be6-d167-48e9-90f1-813a6c37c8ad','en');
---
> INSERT INTO `content_moderation_state` VALUES (43344,611587,'b6a72be6-d167-48e9-90f1-813a6c37c8ad','en');
533167c533168
< INSERT INTO `content_moderation_state_field_data` VALUES (43344,611586,'en',1454,'editorial','draft','node',43472,611756,1,1);
---
> INSERT INTO `content_moderation_state_field_data` VALUES (43344,611587,'en',1454,'editorial','draft','node',43472,611757,1,1);
1073470a1073472
> INSERT INTO `content_moderation_state_field_revision` VALUES (43344,611587,'en',1454,'editorial','draft','node',43472,611757,1,1);
1073489c1073491
< ) ENGINE=InnoDB AUTO_INCREMENT=611587 DEFAULT CHARSET=utf8mb4 COMMENT='The revision table for content_moderation_state entities.';
---
> ) ENGINE=InnoDB AUTO_INCREMENT=611588 DEFAULT CHARSET=utf8mb4 COMMENT='The revision table for content_moderation_state entities.';
1613763a1613766
> INSERT INTO `content_moderation_state_revision` VALUES (43344,611587,'en',1);
1626534c1626537
< ) ENGINE=InnoDB AUTO_INCREMENT=209764 DEFAULT CHARSET=utf8mb4 COMMENT='The base table for danse_event entities.';
---
> ) ENGINE=InnoDB AUTO_INCREMENT=209765 DEFAULT CHARSET=utf8mb4 COMMENT='The base table for danse_event entities.';
1836304a1836308
> INSERT INTO `danse_event` VALUES (209764,'39cdb0f9-de75-4571-a261-eabf46cd7ba8','content_moderation','draft','content_moderation_state-43344','Test 8:17 AM transitioned to draft','{\"entity\":{\"type\":\"content_moderation_state\",\"bundle\":\"content_moderation_state\",\"id\":\"43344\",\"label\":null,\"uid\":\"1454\"},\"label\":\"\",\"class\":\"Drupal\\\\danse_content_moderation\\\\Payload\"}',1,0,0,0,1643721522,1643721522);
1987927a1987932
> INSERT INTO `history` VALUES (1454,43472,1643721524);
2183392c2183397
< INSERT INTO `menu_link_content` VALUES (10413,10413,'menu_link_content','a7cccd7a-e2dc-4de5-a495-3b6b7ef3e765','en');
---
> INSERT INTO `menu_link_content` VALUES (10413,10413,'va-alaska-health-care','a7cccd7a-e2dc-4de5-a495-3b6b7ef3e765','en');
2192922c2192927
< INSERT INTO `menu_link_content_data` VALUES (10413,10413,'menu_link_content','en',1,'Test 8:17 AM',NULL,'va-alaska-health-care','entity:node/43472',NULL,'a:0:{}',0,0,0,0,'menu_link_content:8a6c847d-aa8c-4365-9772-6a3c6117cfca',1643721448,1,NULL,1);
---
> INSERT INTO `menu_link_content_data` VALUES (10413,10413,'va-alaska-health-care','en',1,'Test 8:17 AM',NULL,'va-alaska-health-care','entity:node/43472',NULL,'a:0:{}',0,0,0,0,'menu_link_content:8a6c847d-aa8c-4365-9772-6a3c6117cfca',1643721522,1,NULL,1);
2202333c2202338
< INSERT INTO `menu_link_content_field_revision` VALUES (10413,10413,'en',1,'Test 8:17 AM',NULL,'entity:node/43472',NULL,'a:0:{}',0,1643721448,1,1);
---
> INSERT INTO `menu_link_content_field_revision` VALUES (10413,10413,'en',1,'Test 8:17 AM',NULL,'entity:node/43472',NULL,'a:0:{}',0,1643721522,1,1);
2303667c2303672
< INSERT INTO `node` VALUES (43472,611756,'health_care_region_detail_page','179bee9b-4d58-40a4-bcb1-88f185d6fb84','en');
---
> INSERT INTO `node` VALUES (43472,611757,'health_care_region_detail_page','179bee9b-4d58-40a4-bcb1-88f185d6fb84','en');
2348849c2348854
< INSERT INTO `node__field_administration` VALUES ('health_care_region_detail_page',0,43472,611756,'en',0,372);
---
> INSERT INTO `node__field_administration` VALUES ('health_care_region_detail_page',0,43472,611757,'en',0,372);
2414578c2414583
< INSERT INTO `node__field_description` VALUES ('health_care_region_detail_page',0,43472,611756,'en',0,'Test');
---
> INSERT INTO `node__field_description` VALUES ('health_care_region_detail_page',0,43472,611757,'en',0,'Test');
2491976c2491981
< INSERT INTO `node__field_intro_text` VALUES ('health_care_region_detail_page',0,43472,611756,'en',0,'Test');
---
> INSERT INTO `node__field_intro_text` VALUES ('health_care_region_detail_page',0,43472,611757,'en',0,'Test');
2561952c2561957
< INSERT INTO `node__field_office` VALUES ('health_care_region_detail_page',0,43472,611756,'en',0,15032);
---
> INSERT INTO `node__field_office` VALUES ('health_care_region_detail_page',0,43472,611757,'en',0,15032);
2668203c2668208
< INSERT INTO `node__field_table_of_contents_boolean` VALUES ('health_care_region_detail_page',0,43472,611756,'en',0,0);
---
> INSERT INTO `node__field_table_of_contents_boolean` VALUES ('health_care_region_detail_page',0,43472,611757,'en',0,0);
2732118c2732123
< INSERT INTO `node_field_data` VALUES (43472,611756,'health_care_region_detail_page','en',0,'Test 8:17 AM',1454,1643721411,1643721448,0,0,1,1);
---
> INSERT INTO `node_field_data` VALUES (43472,611757,'health_care_region_detail_page','en',0,'Test 8:17 AM',1454,1643721411,1643721522,0,0,1,1);
3272006a3272012
> INSERT INTO `node_field_revision` VALUES (43472,611757,'en',0,'Test 8:17 AM',1454,1643721411,1643721522,0,0,1,1);
3272030c3272036
< ) ENGINE=InnoDB AUTO_INCREMENT=611757 DEFAULT CHARSET=utf8mb4 COMMENT='The revision table for node entities.';
---
> ) ENGINE=InnoDB AUTO_INCREMENT=611758 DEFAULT CHARSET=utf8mb4 COMMENT='The revision table for node entities.';
3811890a3811897
> INSERT INTO `node_revision` VALUES (43472,611757,'en',1454,1643721522,NULL,1);
4678948a4678956
> INSERT INTO `node_revision__field_administration` VALUES ('health_care_region_detail_page',0,43472,611757,'en',0,372);
5392138a5392147
> INSERT INTO `node_revision__field_description` VALUES ('health_care_region_detail_page',0,43472,611757,'en',0,'Test');
6777172a6777182
> INSERT INTO `node_revision__field_intro_text` VALUES ('health_care_region_detail_page',0,43472,611757,'en',0,'Test');
8410272a8410283
> INSERT INTO `node_revision__field_office` VALUES ('health_care_region_detail_page',0,43472,611757,'en',0,15032);
9764712a9764724
> INSERT INTO `node_revision__field_table_of_contents_boolean` VALUES ('health_care_region_detail_page',0,43472,611757,'en',0,0);
17206063c17206075
< INSERT INTO `search_api_item` VALUES ('content','entity:node','entity:node/43472:en',1643721448,0);
---
> INSERT INTO `search_api_item` VALUES ('content','entity:node','entity:node/43472:en',1643721522,0);
17223406c17223418
< INSERT INTO `sessions` VALUES (1454,'iRQgJg3-5QjeFzrVGWgS9EvXlOHzX9HebS00HGfo5xE','172.16.17.2',1643721371,'_sf2_attributes|a:1:{s:3:\"uid\";s:4:\"1454\";}_sf2_meta|a:4:{s:1:\"u\";i:1643721371;s:1:\"c\";i:1643644966;s:1:\"l\";s:1:\"0\";s:1:\"s\";s:43:\"lApfeO_dagQH5ihE1LMdKXQqK09wXjzeY95OZwKfCs\";}');
---
> INSERT INTO `sessions` VALUES (1454,'iRQgJg3-5QjeFzrVGWgS9EvXlOHzX9HebS00HGfo5xE','172.16.17.2',1643721523,'_sf2_attributes|a:1:{s:3:\"uid\";s:4:\"1454\";}_sf2_meta|a:4:{s:1:\"u\";i:1643721371;s:1:\"c\";i:1643644966;s:1:\"l\";s:1:\"0\";s:1:\"s\";s:43:\"lApfeO_dagQH5ihE1LMdKXQqK09wXjzeY95OZwKfCs\";}');
17275757c17275769
< INSERT INTO `taxonomy_entity_index` VALUES ('node','health_care_region_detail_page',43472,611756,'field_administration',0,372);
---
> INSERT INTO `taxonomy_entity_index` VALUES ('node','health_care_region_detail_page',43472,611757,'field_administration',0,372);
17360400c17360412
< INSERT INTO `users_field_data` VALUES (16,'en','en','en','api','$S$E8dx2r5lD6QEnlL.DHf4Jj/1ipNkwkK90giLgQLqIOP33teiY8x',NULL,'America/New_York',1,1547583299,1579204526,1643721316,1643063821,'andy.hawks+va-api@civicactions.com',1);
---
> INSERT INTO `users_field_data` VALUES (16,'en','en','en','api','$S$E8dx2r5lD6QEnlL.DHf4Jj/1ipNkwkK90giLgQLqIOP33teiY8x',NULL,'America/New_York',1,1547583299,1579204526,1643721529,1643063821,'andy.hawks+va-api@civicactions.com',1);
17361598c17361610
< ) ENGINE=InnoDB AUTO_INCREMENT=547 DEFAULT CHARSET=utf8mb4 COMMENT='Table that contains logs of all system events.';
---
> ) ENGINE=InnoDB AUTO_INCREMENT=548 DEFAULT CHARSET=utf8mb4 COMMENT='Table that contains logs of all system events.';
17362154a17362167
> INSERT INTO `watchdog` VALUES (547,1454,'content','@type: updated %title.','a:2:{s:5:\"@type\";s:30:\"health_care_region_detail_page\";s:6:\"%title\";s:12:\"Test 8:17 AM\";}',5,'<a href=\"/alaska-health-care/programs/test-817-am\" hreflang=\"en\">View</a>','https://pr7801-yqfzqhz3mkivf7plo7vl8j4xlfrfljy9.ci.cms.va.gov/node/43472/edit','https://pr7801-yqfzqhz3mkivf7plo7vl8j4xlfrfljy9.ci.cms.va.gov/node/43472/edit','172.16.17.2',1643721523);
17362466c17362479
```

I'll look at this more, but nothing immediately jumps out at me as repairing a possible problematic row.  

This change:

```diff
< INSERT INTO `menu_link_content` VALUES (10413,10413,'menu_link_content','a7cccd7a-e2dc-4de5-a495-3b6b7ef3e765','en');
---
> INSERT INTO `menu_link_content` VALUES (10413,10413,'va-alaska-health-care','a7cccd7a-e2dc-4de5-a495-3b6b7ef3e765','en');
```
may seem provocative, but the third column (`bundle`) being set to `menu_link_content` appears independent of whether the menu link functions or not AFAICT.

**Comment by ndouglas** [comment]
Just kidding.  It appears that the bundle in `menu_link_content` does have an impact.

If I create a VAMC detail page and select "save draft and continue":

<img width="1642" alt="Screen Shot 2022-02-02 at 10 00 00 AM" src="https://user-images.githubusercontent.com/1318579/152179109-6b10a773-90f1-4981-bd9a-482b235c2600.png">

This seems to reliably lead to a content build failure.

You can repeat the build and it'll continue to fail.  You can rebuild the cache with Drush and it'll continue to fail.

But if you re-set the bundle on the menu link in question to `va-alaska-health-care`:

```
MariaDB [tugboat]> SELECT * FROM menu_link_content ORDER BY id DESC LIMIT 5;
+-------+-------------+-----------------------+--------------------------------------+----------+
| id    | revision_id | bundle                | uuid                                 | langcode |
+-------+-------------+-----------------------+--------------------------------------+----------+
| 10420 |       10420 | menu_link_content     | 610ff5ff-d8a7-4a09-a460-bcf83d2767be | en       |
| 10419 |       10419 | va-alaska-health-care | f175db7f-eb21-44bf-9c8f-9145ae481763 | en       |
| 10418 |       10418 | va-alaska-health-care | f73bdce7-ba8d-4d73-9262-7089d23a7b58 | en       |
| 10417 |       10417 | va-alaska-health-care | 1d401875-b50b-4578-b5b5-18c87c42d02c | en       |
| 10416 |       10416 | va-alaska-health-care | 1e588dc6-5d76-4505-a0b8-615884415679 | en       |
+-------+-------------+-----------------------+--------------------------------------+----------+
5 rows in set (0.000 sec)

MariaDB [tugboat]> UPDATE `menu_link_content` SET bundle='va-alaska-health-care' WHERE revision_id=10420;
Query OK, 1 row affected (0.001 sec)
Rows matched: 1  Changed: 1  Warnings: 0
```

then (after another `drush cr`), the content build will proceed normally.

If you set it back to `menu_link_content` and `drush cr`, it'll fail again.

Re-setting it back to `va-alaska-health-care` and `drush cr` will cause it to succeed again.

Now, when experimenting yesterday I noticed that some bundles were set incorrectly.  However, some of the menu links with `menu_link_content` as a bundle actually worked!  I think this might be because I saved the menu link in a different location -- under Services and Locations.  I think what's going on there is that a difference in how those two paths are processed might be causing one to work and the other to fail.

So I think this is why re-saving the item or the node will fix the issue -- because, as noted above, it updates the `bundle`.

**Comment by ndouglas** [comment]
The issue appears to be that the "Save Draft and Continue" submissions are not complete.

`\Drupal\menu_link_content\Entity\MenuLinkContent` contains the following:

```php
  /**
   * {@inheritdoc}
   */
  public static function preCreate(EntityStorageInterface $storage, array &$values) {
    $values += ['bundle' => 'menu_link_content'];
  }
```

This appears to be the only code anywhere in the codebase that sets the `bundle` to `menu_link_content`.

On node forms, an additional submit handler is appended here, in `menu_item_extras.module`:

```php
/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function menu_item_extras_form_node_form_alter(array &$form, FormStateInterface $form_state, $form_id) {
  /** @var \Drupal\Core\Extension\ModuleHandlerInterface $moduleHandler */
  $moduleHandler = \Drupal::service('module_handler');
  if ($moduleHandler->moduleExists('menu_ui')) {
    foreach (array_keys($form['actions']) as $action) {
      if ($action != 'preview' && isset($form['actions'][$action]['#type']) && $form['actions'][$action]['#type'] === 'submit') {
        $form['actions'][$action]['#submit'][] = [
          \Drupal::service('menu_item_extras.menu_link_content_helper'),
          'nodeSubmit',
        ];
      }
    }
  }
}
```

That leads to `\Drupal\menu_item_extras\Service\MenuLinkContentService`:

```php

  /**
   * Form submission handler for menu item field on the node form.
   *
   * @param array $form
   *   Form array.
   * @param \Drupal\Core\Form\FormStateInterface $form_state
   *   Form state object.
   *
   * @see menu_ui_form_node_form_submit()
   * @see menu_ui_form_node_form_alter()
   */
  public function nodeSubmit(array $form, FormStateInterface $form_state) {
    /** @var \Drupal\Core\Entity\EntityFormInterface $form_object */
    $form_object = $form_state->getFormObject();
    /** @var \Drupal\Core\Entity\EntityInterface $node */
    $node = $form_object->getEntity();
    if (!$form_state->isValueEmpty('menu')) {
      $values = $form_state->getValue('menu');
      if (!empty($values['enabled']) && trim($values['title'])) {
        // Decompose the selected menu parent
        // option into 'menu_name' and 'parent',
        // if the form used the default parent selection widget.
        if (!empty($values['menu_parent'])) {
          list($menu_name, $parent) = explode(':', $values['menu_parent'], 2);
          $values['menu_name'] = $menu_name;
          $values['parent'] = $parent;
        }
        $link = $this->nodeSave($node, $values);
        $values['entity_id'] = $link->id();
        $form_state->setValue('menu', $values);
      }
    }
  }

  /**
   * Helper function to create or update a menu link for a node.
   *
   * @param \Drupal\Core\Entity\EntityInterface $node
   *   Node entity.
   * @param array $values
   *   Values for the menu link.
   *
   * @return \Drupal\menu_link_content\MenuLinkContentInterface
   *   Menu item.
   *
   * @see _menu_ui_node_save()
   */
  public function nodeSave(EntityInterface $node, array $values) {
    ....
    $entity->set('bundle', $values['menu_name']);
    ....
    return $entity;
  }
```

Now, I suspect the problem is this bit of custom code in `va_gov_backend.module`:

```php

/**
 * Implements hook_form_alter().
 */
function va_gov_backend_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  ....
  // Add to node forms in workflow.
  if (in_array('node_form', (array) $form['#theme'])) {
    $form['actions']['save_continue'] = [
      '#ief_submit_trigger' => TRUE,
      '#ief_submit_trigger_all' => TRUE,
      '#type' => 'submit',
      '#weight' => 10,
      '#value' => 'Save draft and continue editing',
      '#submit' => [  '::submitForm', 'va_gov_backend_form_alter_submit' ],
    ];
  }
  ....
}


/**
 * Submit function for va_gov_backend_form_alter.
 *
 * @param array $form
 *   The form array.
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 *   The form state array.
 */
function va_gov_backend_form_alter_submit(array &$form, FormStateInterface $form_state) {

  // We want to associate our user with the revision.
  $uid = Drupal::currentUser()->id();

  /** @var \Drupal\Core\Entity\EntityFormInterface $form_object */
  $form_object = $form_state->getFormObject();

  // Build the revision info.
  $node = $form_object->getEntity();
  if (!$node instanceof NodeInterface) {
    return;
  }
  $node->setNewRevision(TRUE);
  $node->setRevisionCreationTime(\Drupal::time()->getRequestTime());

  // Save it and associate with user.
  $node->setRevisionUserId($uid);
  $node->set('moderation_state', 'draft');
  $node->save();

  $nid = $node->id();
  $url = 'http' . ((!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] == 'on') ? 's' : '') . '://' . \Drupal::request()->getHost() . '/node/' . $nid . '/edit';

  // Send them to the edit node.
  $response = new RedirectResponse($url);
  $response->send();

}
```

The "Save and Continue" button appears to short-circuit the `menu_link_extras` submission handler, which results in the menu link object not being populated with all of the expected data.  I tried a quick fix by infixing the form submission handler, but it didn't work.

So this might take a substantial amount of work to fix; might involve a rewrite of the "Save and Continue" functionality.  I'll dig into this more as time allows.

**Comment by indytechcook** [comment]
Amazing find!!  I'd see the ideal long term solution to be patching the `menu_link_extras` module to use entity hooks or override the entire entity and controller objects.

Also found: https://www.drupal.org/project/menu_item_extras/issues/3210468

**Comment by ndouglas** [comment]
I think that person has the exact same problem, just with a different specific trigger.

That patch is _exactly_ what I was thinking about for a quick fix (except in `va_gov_backend`), but I think their code is actually right.  Setting the bundle explicitly like that probably stops the issue from appearing, but I think the menu link object is not fully populated and may cause other, more subtle issues or crashes elsewhere in the content build process.  I just don't know.

I can open a couple different PRs to solve this issue, verify they fix the issue, and we can just pick one 😃
