### ISSUE TITLE
Remove endpoints for VAMCs going to full prod week of Nov 8 2021

### ISSUE THREAD

**Issue by JayDarnell** [department-of-veterans-affairs/va.gov-cms#6958]
## User Story or Problem Statement
After VAMCs go to full prod launch (redirects removed), remove the operating status endpoint migration for those systems.

- [x] Batch A from Nov 11th
https://www.va.gov/connecticut-health-care
https://www.va.gov/manchester-health-care
https://www.va.gov/dayton-health-care
https://www.va.gov/northeast-ohio-health-care
https://www.va.gov/tomah-health-care
https://www.va.gov/wichita-health-care
https://www.va.gov/central-texas-health-care
https://www.va.gov/southern-arizona-health-care
https://www.va.gov/san-diego-health-care
https://www.va.gov/clarksburg-health-care
https://www.va.gov/memphis-health-care
https://www.va.gov/tennessee-valley-health-care

- [x] Batch B from Nov 18th
https://www.va.gov/nebraska-western-iowa-health-care/
https://www.va.gov/white-river-junction-health-care/
https://www.va.gov/jackson-health-care/
https://www.va.gov/chicago-health-care/
https://www.va.gov/iron-mountain-health-care/
https://www.va.gov/madison-health-care/
https://www.va.gov/lexington-health-care/
https://www.va.gov/caribbean-health-care/
https://www.va.gov/poplar-bluff-health-care/
https://www.va.gov/southern-oregon-health-care/
https://www.va.gov/portland-health-care/
https://www.va.gov/washington-dc-health-care/
https://www.va.gov/new-mexico-health-care/
https://www.va.gov/chillicothe-health-care/
https://www.va.gov/bay-pines-health-care/
https://www.va.gov/maine-health-care/
https://www.va.gov/dublin-health-care/
https://www.va.gov/atlanta-health-care/
https://www.va.gov/huntington-health-care/
https://www.va.gov/hines-health-care/
https://www.va.gov/west-palm-beach-health-care/
https://www.va.gov/maryland-health-care/
https://www.va.gov/roseburg-health-care/
https://www.va.gov/milwaukee-health-care/
https://www.va.gov/northern-indiana-health-care/

**Comment by swirtSJW** [comment]
Batch A looks good.  Moving this back to ToDO for when the next batch lands next week.

**Comment by swirtSJW** [comment]
Batch A.   https://github.com/department-of-veterans-affairs/va.gov-cms/pull/6959
unlinking this so closing the PR does not close this ticket.

**Comment by swirtSJW** [comment]
Closing this as our 2 removals for this sprint are complete.
