### ISSUE TITLE
Remove endpoints during Sprint 46

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#7016]
## Description

Possibly the last big batch, leaving only Lovell. 

## Acceptance Criteria
- [ ] Endpoints removed from nightly migration for the following
    - https://www.amarillo.va.gov/locations/facilities.asp
    - https://www.beckley.va.gov/locations/facilities.asp
    - https://www.boston.va.gov/locations/facilities.asp
    - https://www.centralwesternmass.va.gov/locations/facilities.asp
    - https://www.columbiamo.va.gov/locations/facilities.asp
    - https://www.columbus.va.gov/locations/facilities.asp
    - https://www.elpaso.va.gov/locations/facilities.asp
    - https://www.indianapolis.va.gov/locations/facilities.asp
    - https://www.leavenworth.va.gov/locations/facilities.asp
    - https://www.losangeles.va.gov/locations/facilities.asp
    - https://www.louisville.va.gov/locations/facilities.asp
    - https://www.marion.va.gov/locations/facilities.asp
    - https://www.mountainhome.va.gov/locations/facilities.asp
    - https://www.northtexas.va.gov/locations/facilities.asp
    - https://www.phoenix.va.gov/locations/facilities.asp
    - https://www.prescott.va.gov/locations/facilities.asp
    - https://www.stlouis.va.gov/locations/facilities.asp
    - https://www.texasvalley.va.gov/locations/facilities.asp
    - https://www.topeka.va.gov/locations/facilities.asp
    - https://www.wallawalla.va.gov/locations/facilities.asp

- [ ] Only  https://www.lovell.fhcc.va.gov/locations/facilities.asp should remain.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Platform CMS Team`
- [x] `Sitewide CMS Team`

**Comment by JayDarnell** [comment]
@kevwalsh @swirtSJW I just created a PR for this. Let me know if Lovell should also be removed and I will update.
