### ISSUE TITLE
Create recurring events feature flag

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#7020]
## Acceptance Criteria
- [x] FEATURE_RECURRING_EVENTS has been added to https://prod.cms.va.gov/admin/config/system/feature_toggle
- [ ] @kelsonic is made aware when this is complete.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Platform CMS Team`
- [x] `Sitewide CMS Team`

**Comment by netboss** [comment]
@kevwalsh Do the `FEATURE_RECURRING_EVENTS` flag checkbox need to be checked?
