### ISSUE TITLE
Track resolution for intermittent 502 bad gateway responses on CI

### ISSUE THREAD

**Issue by jkalexander7** [department-of-veterans-affairs/va.gov-cms#7023]
## User Story or Problem Statement

The investigation is in https://github.com/department-of-veterans-affairs/va.gov-cms/issues/5552.
AWS Issue: https://console.amazonaws-us-gov.com/support/home#/case/?displayId=9221808181&language=en

Our CI environments are seeing intermittent 502 bad gateway responses in the ALB logs which are causing multiple PR failures on vets-website branch build PRs and CMS PRs. 

This is happening to multiple environments and multiple types (GET and POST) requests and multiple MIME types (text/html & image/jpeg). The[ ALB docs ](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-access-logs.html) suggest that in this example below the connection was NOT established to the target and/or the target did not send a response. 

`-1`:  response_processing_time: This value is set to -1 if the load balancer can't send the request to a target. This can happen if the target closes the connection before the idle timeout or if the client sends a malformed request.
`502`: elb_status_code: The status code of the response from the load balancer.
`-`: target_status_code: The status code of the response from the target. This value is recorded only if a connection was established to the target and the target sent a response. Otherwise, it is set to -.
```
40602:https 2021-06-08T22:34:21.038282Z app/dsva-vagov-utility-tools/30a7782e04179703 10.247.142.71:36382 172.31.1.159:443 0.000 0.149 -1 502 - 1470 272 "POST https://cms-vets-website-branch-builds-lo9uhqj18nwixunsjadvjsynuni7kk1u.
i.cms.va.gov:443/graphql HTTP/1.1" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" ECDHE-RSA-AES128-GCM-SHA256 TLSv1.2 arn:aws-us-gov:elasticloadbalancing:us-gov-west-1:008577686731:targetgroup/dsva-vagov-utility-tugboat-h
tps/3041ecf209fb8c7e "Root=1-60bff06c-0a2c04986b2e40940f670ba3" "cms-vets-website-branch-builds-lo9uhqj18nwixunsjadvjsynuni7kk1u.ci.cms.va.gov" "session-reused" 3 2021-06-08T22:34:20.888000Z "forward" "-" "-" "172.31.1.159:443" "-"
"-" "-"
```

I did try a 500 request loop on the CI server itself with `for i in $(seq 1 500); do printf "$i: " ; curl -s -o /dev/null -w "%{http_code}\n" --insecure https://cms-vets-website-branch-builds-lo9uhqj18nwixunsjadvjsynuni7kk1u.ci.cms.va.gov/; done` and it was all good, same 200 response code. 

## Acceptance Criteria
- [x] Track resolution of the issue with AWS support
- [ ] Create followup ticket for resolution if resolution is on our side

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [x] `Platform CMS Team`
- [ ] `Sitewide CMS Team`

**Comment by indytechcook** [comment]
Adding Original AWS ticket logged by @ndouglas 

> Here is a GitHub issue with more detail (including graphs, etc): https://github.com/department-of-veterans-affairs/va.gov-cms/issues/5552 
> 
> For several months -- since June, at least, we've been experiencing a low but fairly consistent background rate of 502's across our ALBs.  
> 
> I'm a developer/devops guy on the Drupal CMS team specifically, but I believe the problem is more widespread than that and affects most if not all of our organization's services.
> 
> The reason we originally took note of the 502's was that they would occasionally disrupt lengthy build processes; our content build process is monolithic and can take 20-30 minutes, depending on various conditions.  As you might expect, it's very frustrating to have that interrupted by a 5XX error.
> 
> We investigated this by dumping the ALB logs into an S3 bucket and poring over them with Athena.  We found that the 502's would have a `response_processing_time` of `-1` and a `target_status_code` of `-`.  This would seem to indicate that there was no corresponding 502 from our backend server, but rather there was some sort of communications failure with that server.  Indeed, we didn't find backend services logs corresponding to those requests.
> 
> We hypothesized that there might be an issue with the idle connection timeouts or other proxy configuration timeouts that would lead to the ELB <-> backend connection timing out and closing while the client <-> ELB connection was still active, or something like that.  In testing this hypothesis with netcat and monotonically increasing intervals between packets, I wasn't able to produce the expected effect.
> 
> We didn't really get anywhere, so we dropped it for a while.
> 
> Recently, after a few particularly frustrating experiences, we resumed trying to diagnose the issue.
> 
> Instead of focusing on the CMS side of things, we cast a broader net and looked to see what other services were experiencing 502's but, for whatever reason, just weren't reporting them.  Looking at LB 502's in Cloudwatch Metrics, we seemed to find that all of our services were experiencing 502's.  A lot more during the week than on weekends and during the day than at night (matching our normal work schedules), but their presence or absence seemed to us to be more like something that would be happening a small percentage of the time rather than something that happened in response to high (or even moderate) load, etc.
> 
> It _does_ seem like most or all of our services are experiencing 502's, but because of the nature of the different tasks performed by these different services, that low incidence might be simply ignored, retried transparently, or lost.  
> 
> I feel like I've troubleshooted this about as far as I can, so I would appreciate some guidance on how to resolve this.
> ELB FQDN(s): 


Here is the response from AWS:

> Greetings VA team,
> 
> Thank you for reaching out to Premium Support - my name is Alistair and I am looking forward to working with you on your case today.
> I understand that multiple Application Load Balancers have been generating HTTP 502 errors and you would like to root cause this behavior.
> Troubleshooting ALB 502s is my bread and butter, so you are in good hands here.
> 
> In order to most accurately identify the behavior causing this "HTTP 502: Bad gateway" error generation, Premium Support would require a sample of ALB Access Logs downloaded and sent to us in the case in order to analyze and then based on the different fields and referencing the ALB's configuration, we would use process of elimination to identify the likely cause out of the following list:
> 
> HTTP 502: Bad gateway [Link 1], Possible causes:
> 
> A.    The load balancer received a TCP RST from the target when attempting to establish a connection.
> B.    The load balancer received an unexpected response from the target, such as "ICMP Destination unreachable (Host unreachable)", when attempting to establish a connection. Check whether traffic is allowed from the load balancer subnets to the targets on the target port.
> C.    The target closed the connection with a TCP RST or a TCP FIN while the load balancer had an outstanding request to the target. Check whether the keep-alive duration of the target is shorter than the idle timeout value of the load balancer.
> D.    The target response is malformed or contains HTTP headers that are not valid.
> E.    The load balancer encountered an SSL handshake error or SSL handshake timeout (10 seconds) when connecting to a target.
> F.    The deregistration delay period elapsed for a request being handled by a target that was deregistered. Increase the delay period so that lengthy operations can complete.
> G.    The target is a Lambda function and the response body exceeds 1 MB.
> H.    The target is a Lambda function that did not respond before its configured timeout was reached.
> I.    The target is a Lambda function that returned an error or the function was throttled by the Lambda service.
> 
> ----
> 
> I read the issue on Github and picked the top most ALB mentioned "app/dsva-vagov-utility-tools/30a7782e04179703" as showing this behavior. 
> I then checked out the metrics and our AWS internal logging and can see that the reason for these 502s for a random hour (2021-11-18T06:00 -> 07:00 UTC), were because the targets the requests were sent to, responded to said request with a RESET packet instead of an HTTP response. This is Cause C in the above list, and the most common cause from my own experience.
> 
> This behavior usually is caused by premature connection closure on the target end, which is most commonly caused by the HTTP Keep-alive Timeout on said targets being set to less than the ELB Idle Timeout value [Link 2]. For this ALB, the HTTP Keepalive Timeout is set to 800 seconds. IF the load balancer tries to reuse a connection, and the back-end closes said connection at the same time just after the request is sent, we can expect such an exception.
> 
> ----
> 
> Next steps here are to:
> 
> 1.) Re-enable ALB Access Logging for ALB "app/dsva-vagov-utility-tools/30a7782e04179703" and wait for some ALB 502s to be generated.
> 
> 2.) Download the ALB Access Logs for the issue period from the S3 bucket, and upload them to me in the case unmodified / parsed. 
> It is important that they are recent so that AWS still has logs to compare with which haven't rotated out yet.
> 
> 3.) Identify which Target Group, and therefore which Application stack the request was destined for, confirm if you have persistent connections (HTTP Keepalives) configured there, and what the timeout is configured to. If < 800 seconds, make it 805 seconds. OR drop the ELB Idle Timeout from 800 seconds down to slightly less time in seconds compared to whatever the target is configured for.
> 
> Please let me know if you have any queries or concerns and I will be happy to help.
> Looking forward to hearing from you soon.
> 
> ---- Reference links ----
> 
> Link 1 - Troubleshoot your Application Load Balancers - HTTP 502: Bad gateway - https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-troubleshooting.html#http-502-issues 
> 
> Link 2 - Application Load Balancers - Connection idle timeout - https://docs.aws.amazon.com/elasticloadbalancing/latest/application/application-load-balancers.html#connection-idle-timeout 
> 
> -------------------------
> 
> We value your feedback. Please share your experience by rating this correspondence using the AWS Support Center link at the end of this correspondence. Each correspondence can also be rated by selecting the stars in top right corner of each correspondence within the AWS Support Center.
> 
> Best regards,
> Alistair P.
> Amazon Web Services

**Comment by olivereri** [comment]
@ndouglas response to AWS Support following Alisair's message:

> Here is a GitHub issue with more detail (including graphs, etc): https://github.com/department-of-veterans-affairs/va.gov-cms/issues/5552 
> 
> For several months -- since June, at least, we've been experiencing a low but fairly consistent background rate of 502's across our ALBs.  
> 
> I'm a developer/devops guy on the Drupal CMS team specifically, but I believe the problem is more widespread than that and affects most if not all of our organization's services.
> 
> The reason we originally took note of the 502's was that they would occasionally disrupt lengthy build processes; our content build process is monolithic and can take 20-30 minutes, depending on various conditions.  As you might expect, it's very frustrating to have that interrupted by a 5XX error.
> 
> We investigated this by dumping the ALB logs into an S3 bucket and poring over them with Athena.  We found that the 502's would have a `response_processing_time` of `-1` and a `target_status_code` of `-`.  This would seem to indicate that there was no corresponding 502 from our backend server, but rather there was some sort of communications failure with that server.  Indeed, we didn't find backend services logs corresponding to those requests.
> 
> We hypothesized that there might be an issue with the idle connection timeouts or other proxy configuration timeouts that would lead to the ELB <-> backend connection timing out and closing while the client <-> ELB connection was still active, or something like that.  In testing this hypothesis with netcat and monotonically increasing intervals between packets, I wasn't able to produce the expected effect.
> 
> We didn't really get anywhere, so we dropped it for a while.
> 
> Recently, after a few particularly frustrating experiences, we resumed trying to diagnose the issue.
> 
> Instead of focusing on the CMS side of things, we cast a broader net and looked to see what other services were experiencing 502's but, for whatever reason, just weren't reporting them.  Looking at LB 502's in Cloudwatch Metrics, we seemed to find that all of our services were experiencing 502's.  A lot more during the week than on weekends and during the day than at night (matching our normal work schedules), but their presence or absence seemed to us to be more like something that would be happening a small percentage of the time rather than something that happened in response to high (or even moderate) load, etc.
> 
> It _does_ seem like most or all of our services are experiencing 502's, but because of the nature of the different tasks performed by these different services, that low incidence might be simply ignored, retried transparently, or lost.  
> 
> I feel like I've troubleshooted this about as far as I can, so I would appreciate some guidance on how to resolve this.
> ELB FQDN(s):

**Comment by olivereri** [comment]
Follow up with AWS:

> Hi Alistair,
> 
> If you don't mind I'd like to put the focus on a different ALB than app/dsva-vagov-utility-tools/30a7782e04179703 and focus on one that is in front of Production servers. Namely:
> 
> arn:aws-us-gov:elasticloadbalancing:us-gov-west-1:008577686731:loadbalancer/app/dsva-vagov-prod-cms/d7503b53a86e3abd
> 
> This is a very difficult issue to catch. I've created a table in Athena to look for elb_status_codes with 502 using the Access Logs bucket. The log sets with 502s in them are hours apart. The attached log file appears to only have one occurrence of a HTTP 502 response.
> 
> This load balancer has an even longer idle timeout of 1800 seconds due to long running PHP processes. On the application side PHP is configured to allow a max_execution_time of 1800 seconds as well. However, Apache appears to be using defaults for TimeOut and KeepAliveTimeout. I believe the default for TimeOut in version 2.4 is 60 seconds. KeepAliveTimeout I believe is 5 seconds.  Even with the default values the long running requests still complete more likely than not. The server does use the default KeepAlive which is set to on.
> 
> I will work on adjusting the Apache settings to match the ALB's idle timeout setting.
> 
> Thank you very much for your time.


Response from AWS:

> Greetings VA team,
> 
> Many thanks for getting back to me; reviewing the ALB "app/dsva-vagov-prod-cms/d7503b53a86e3abd" HTTPCode_ELB_502_Count  metrics, ALB 502s are not as common as the other ALB.
> I checked the sample log file and traced the single failed request (502):
> 
> http 2021-11-23T17:31:58.205552Z app/dsva-vagov-prod-cms/d7503b53a86e3abd 10.247.91.186:47397 10.247.32.10:80 0.000 0.081 -1 502 - 274 272 "GET http://internal-dsva-vagov-prod-cms-2000800896.us-gov-west-1.elb.amazonaws.com:80/sites/default/files/2021-06/CINfacilitymap.pdf  HTTP/1.1" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" - - arn:aws-us-gov:elasticloadbalancing:us-gov-west-1:008577686731:targetgroup/vagov-prod-cms-http/d91911b89fb4281c "Root=1-619d258e-3b0dc1fd59b7c5d67ee1e4cc" "-" "-" 0 2021-11-23T17:31:58.115000Z "forward" "-" "-" "10.247.32.10:80" "-" "-" "-"
> 
> In this case, the ALB dispatched the request to the target IP 10.247.32.10, however the target closed the connection with a FIN after 0.081 seconds instead of responding with an HTTP response.
> 
> request_processing_time = 0.000 seconds, ALB dispatched the request to target IP 10.247.32.10 after this amount of time of receiving said request.
> target_processing_time = 0.081 seconds, target closed the connection after this amount of time of receiving said request on the network stack.
> 
> AWS do not have visibility into the target application internals for privacy / security reasons, but given that the target took a whole 81 milliseconds after receiving the GET request to close the connection, I'm more inclined to think that Apache actually received this request and there should be evidence of it in the Apache access logs. To confirm this next time, inside the Apache LogFormat configuration, I would suggest logging the x-amzn-trace-id header [Link 1 and 2] which ALB appends to each request for ease of request tracing, in this case you could grep the Apache access logs for the x-amzn-trace-id value for example "Root=1-619d258e-3b0dc1fd59b7c5d67ee1e4cc" in this example, to find the request that corresponds to this ALB Access Log entry.
> 
> ----
> 
> Indeed Apache 2.4's default KeepAliveTimeout appears to be 5 seconds [Link 3]. With HTTP Keepalives enabled on Apache, the load balancer will re-use connections to the targets, however if the target closes a connection at the same time ALB tries to use said connection, we can expect HTTP 502 generation, and since the request doesn't make it past the network stack on the target to Apache, Apache wont log that request in its Access Logs.
> 
> Since the ELB Idle Timeout is set to 1800 because of the long running PHP processes, Id suggest setting the Apache KeepAliveTimeout to 1805, providing some padding after the LB Idle Timeout so there is no chance of a race condition of target connection closure creeping in. General rule of thumb is to gradually increase the timeouts the further up the stack you go.
> 
> After committing these changes on the targets, monitor for more 502s.
> 
> Please let me know if you have any queries or concerns and I will be happy to help.
> Looking forward to hearing from you soon.
> 
> ---- Reference links ----
> 
> Link 1 - Request tracing for your Application Load Balancer - https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-request-tracing.html 
> 
> Link 2 - How do I trace an Application Load Balancer request using X-Amzn-Trace-Id? - https://aws.amazon.com/premiumsupport/knowledge-center/trace-elb-x-amzn-trace-id/ 
> * Apache logging implementation example via LogFormat
> 
> Link 3 - https://httpd.apache.org/docs/2.4/mod/core.html#keepalivetimeout  
> 
> -----------------------------------
> 
> We value your feedback. Please share your experience by rating this correspondence using the AWS Support Center link at the end of this correspondence. Each correspondence can also be rated by selecting the stars in top right corner of each correspondence within the AWS Support Center.
> 
> Best regards,
> Alistair P.
> Amazon Web Services
> 
>

**Comment by olivereri** [comment]
Since we've added the `KeepAliveTimeout` directive, querying the Prod CMS ALB access logs in the link below shows no 502s after Nov. 24th.

https://console.amazonaws-us-gov.com/athena/home?region=us-gov-west-1#/query-editor/history/71f41116-e263-4de5-a20e-798e4695ce44

Unfortunately, it appears that the KeepAliveTImeout directive is causing problems for Staging environment tests. The change has been reverted and now Staging tests have passed successfully.

**Comment by olivereri** [comment]
> Hi VA team,
> 
> Many thanks for the status update, I'll hang tight on this end and await further updates.
> 
> Cheers for now.
> 
> We value your feedback. Please share your experience by rating this correspondence using the AWS Support Center link at the end of this correspondence. Each correspondence can also be rated by selecting the stars in top right corner of each correspondence within the AWS Support Center.
> 
> Best regards,
> Alistair P.
> Amazon Web Services
> 
> ===============================================================
> 
> To share your experience or contact us again about this case, please return to the AWS Support Center using the following URL: https://console.amazonaws-us-gov.com/support/cases#/9221808181/en 
> 
> Note, this e-mail was sent from an address that cannot accept incoming e-mails.
> To respond to this case, please follow the link above to respond from your AWS Support Center.
> 
> ===============================================================
> 
> Don’t miss messages from AWS Support when you need help! Update your contact information:
> https://console.amazonaws-us-gov.com/support/cases#/9221808181/en 
> 
> If you receive an error message when visiting the contact information page, visit:
> https://aws.amazon.com/premiumsupport/knowledge-center/iam-billing-access/ 
> 
> AWS Support:
> https://aws.amazon.com/premiumsupport/knowledge-center/ 
> 
> AWS Documentation:
> https://docs.aws.amazon.com/ 
> 
> AWS Cost Management:
> https://aws.amazon.com/aws-cost-management/ 
> 
> AWS Training:
> http://aws.amazon.com/training/ 
> 
> AWS Managed Services:
> https://aws.amazon.com/managed-services/ 
>

**Comment by ndouglas** [comment]
Just re-ran the queries:

<img width="1317" alt="Screen Shot 2021-12-03 at 8 11 18 AM" src="https://user-images.githubusercontent.com/1318579/144608095-ead2750b-f0f0-445b-a195-e2a163cfab3c.png">

It'll be nice to get another day or three of clear logs under our belts, but I think you got it 😃

**Comment by olivereri** [comment]
Agreed. I'm going to create a stub issue for Tugboat and kick it over to Jess for review then close this. We can keep monitoring the ALB logs over next sprint and re-open if we find em.
