### ISSUE TITLE
SSOi SAML certificate in Prod needs replacement

### ISSUE THREAD

**Issue by jkalexander7** [department-of-veterans-affairs/va.gov-cms#7026]
## User Story or Problem Statement

The IAM team will be replacing the SSOi SAML certificate in the Production environment on Thursday, December 9, 2021 at 9:00pm EST. This activity will impact SSOi SAML Partners only (NOT WebAgent Partners). Upon completion of the certificate update, Partners will be required to update the SSOi SAML certificate.

## Acceptance Criteria

- [x] Replace the existing SSOi SAML certificate with new certificate
- [x] Conduct post-replacement testing
- [x] Coordinate with IAM team for partner testing sessions (December 9 and December 10)
- [x] Set up some Slack reminders for before the certificate expires
- [x] Add cert expiration to shared team calendar in Confluence + reminder to update cert a few weeks beforehand

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [x] `Platform CMS Team`
- [ ] `Sitewide CMS Team`

**Comment by olivereri** [comment]
Relevant documentation:
https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/platform/cms/cms-sso-saml-iam-login-how-to.md

**Comment by olivereri** [comment]
It doesn't look like Confluence Calendar allows for reminders.
