### ISSUE TITLE
"Preview" button should not be visible for VAMC System Health Services (or any other "excluded" content type.)

### ISSUE THREAD

**Issue by stefaniefgray** [department-of-veterans-affairs/va.gov-cms#7030]
## Describe the defect
The Health Service content type should not have the Preview button available

Example: https://prod.cms.va.gov/memphis-health-care/health-services/sleep-medicine-at-va-memphis-health-care

This is problematic for editors because when they click the "Preview" button, they expect to see a typical page preview; however, previews are not available for this content type. 

Instead, editors see the error message "This page isn't ready to be previewed yet. This may mean development is still in progress or that there's an issue with the preview server. Make sure the query for this page has been added to src/site/stages/build/drupal/graphql/GetLatestPageById.graphql.js."

## To Reproduce
1. Go to https://prod.cms.va.gov/memphis-health-care/health-services/sleep-medicine-at-va-memphis-health-care
2. Click on Preview
3. Observe error message

## Expected behavior
- If Previews are not available for a certain content type, the Preview button should be hidden.
- No "Preview" button on VAMC system health services

 ## Additional context
Reported in https://va-gov.atlassian.net/browse/VAHELP-2843

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [x] `Platform CMS Team`
- [x] `Sitewide CMS Team`

**Comment by swirtSJW** [comment]
The code lives here 
https://github.com/department-of-veterans-affairs/va.gov-cms/blob/123fd6d94840672103fb2d50bfb329e5021c569e/docroot/modules/custom/va_gov_backend/va_gov_backend.module#L965-L1005

And the content type is listed as an exclusion type so this should not be happening, but it is.
