### ISSUE TITLE
Investigate GraphQL performance 

### ISSUE THREAD

**Issue by jkalexander7** [department-of-veterans-affairs/va.gov-cms#7052]
## User Story or Problem Statement

Following the change to GitHub Actions, GraphQL build request time has increased from an average of 2 minutes to roughly 5 minutes.

## Acceptance Criteria
- [ ] Investigate root cause for build request time increase
- [ ] Document findings within ticket
- [ ] Determine team ownership for resolution/ create followup ticket for resolution

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [x] `Platform CMS Team`
- [ ] `Sitewide CMS Team`

**Comment by ElijahLynn** [comment]
Thoughts: Need to rule out an actual CMS code change, or entity count increase. Next I suspect it could be a network issue with increased latency. Maybe one thing to do is test the request from Jenkins still and see if that is slow.

**Comment by indytechcook** [comment]
Focus the investigation on the performance of the GraphQL queries.  If the GraphQL performance is found to be the same as before then send the information on to the FE Tools team for them to investigate further.

**Comment by TheBoatyMcBoatFace** [comment]
Closing - superseded by later efforts
