### ISSUE TITLE
tables with many columns can break layout in claro

### ISSUE THREAD

**Issue by tjheffner** [department-of-veterans-affairs/va.gov-cms#7075]
## Description
Tables with many columns can get very cramped / breakout of the layout box. 
Potentially fix with a wider overall editing column for content types that have these? Design review would be helpful.

as seen on "VAMC System Operating Status"
<img width="997" alt="Screen Shot 2021-11-26 at 12 03 45 PM" src="https://user-images.githubusercontent.com/11279744/143625881-c7485553-00bb-4d50-a893-83ab5f78b005.png">

## Acceptance Criteria
- [ ] Tables do not break out of the defined layout boxes.
- [ ] Table contents are easy to read.
- [ ] Requires design review

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [] `Platform CMS Team`
- [x] `Sitewide CMS Team`

**Comment by msbtterswrth** [comment]
@tjheffner do you think we should make these 'responsive' tables? Like with a horizontal scroll?

**Comment by EWashb** [comment]
I was not able to replicate this issue as of today. I will check again to be sure.

**Comment by EWashb** [comment]
This is no longer happening. Confirmed with @edmund-dunn.
