### ISSUE TITLE
Update vagovclaro to use VA colors & branding

### ISSUE THREAD

**Issue by tjheffner** [department-of-veterans-affairs/va.gov-cms#7076]
## Description
- blocked by whatever we ultimately land on for design tokens. 

vagovclaro should use VA color schemes whenever possible. Links, alerts, hover states, backgrounds, etc. Let's make this feel like a VA product and not any random drupal admin page.

- Should we tackle various spacings between different text hierarchies in this ticket as well? 
- VA logo in the toolbar, favicon can be added here as well.

## Acceptance Criteria
- [ ] Colors in the admin theme match VA styles.
- [ ] VA favicon for admin page
- [ ] Requires design review

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [] `Platform CMS Team`
- [x] `Sitewide CMS Team`

**Comment by kevwalsh** [comment]
@tjheffner You want to call this one closed? I would think that the #7264 takes care of this. There may be iterations, but we can track those separately?

**Comment by tjheffner** [comment]
I think we can close this is and track further iterations as they are ready... we've got a first pass at VA colors and branding :)
