### ISSUE TITLE
Apply path governance to Promo Banners from Full Width Alerts

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#7087]
ACs
- [ ] The Path field for Promo Banners operates, functionally and permissions-wise, the same as Full Width Alerts.

**Comment by ethanteague** [comment]
Handled by https://github.com/department-of-veterans-affairs/va.gov-cms/pull/7055/commits/d67802b219f84a51b2ca562fe6630158054f7c9e
