### ISSUE TITLE
Deliver training to OPIA (and other users?) for promo banners

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#7093]
## User story
As a VA.gov editor, I need to make visitors aware of announcements of other promotional information.

## Acceptance criteria
This can be almost a perfect mirror of training delivered in September for Full Width Alerts.

- [x] identify users
- [x] schedule training
- [x] deliver training
- [ ] edit recorded training, if requested
- [ ] send follow-up email

**Comment by xiongjaneg** [comment]
Emailed Joshua Tuscher, waiting for response

**Comment by xiongjaneg** [comment]
Sent second email to Joshua Tuscher

**Comment by xiongjaneg** [comment]
Third email sent from help desk VA email on Jan 13

**Comment by xiongjaneg** [comment]
Scheduled via Teams for January 27

**Comment by xiongjaneg** [comment]
met with Joshua Tuscher on Teams and talked through the promo banner content type, watched him update it, provided link to KB article
