### ISSUE TITLE
Remove unused tugboat.cms.va.gov certificate and renew tugboat.vfs.va.gov from Venafi

### ISSUE THREAD

**Issue by ElijahLynn** [department-of-veterans-affairs/va.gov-cms#7109]
AC: 
- [x] Delete the unused cert tugboat.cms.va.gov
- [x] Renew tugboat.vfs.va.gov cert (expires on Dec 26th)
- [x] Set Slack reminder to renew cert

**Comment by ndouglas** [comment]
https://dsva.slack.com/archives/CT4GZBM8F/p1635183210223900

<img width="638" alt="Screen Shot 2021-11-30 at 8 17 59 PM" src="https://user-images.githubusercontent.com/1318579/144154207-e5d8445a-74a9-4898-a04a-ef901a2cb769.png">

We don't need to renew it -- it's no longer in use.

**Comment by ElijahLynn** [comment]
We should delete it from Venafi then. I think only Eric or I have access to do this.

**Comment by ElijahLynn** [comment]
I "retired" it from Venafi, and I also noticed that the cert we do use, tugboat.vfs.va.gov is expiring on Dec 26th:

![image](https://user-images.githubusercontent.com/1504756/144476022-b7c65aa3-cde6-46d2-81dc-b3537a6e9a1d.png)

So I am updating ACs to include renewing that one.

**Comment by olivereri** [comment]
> We should delete it from Venafi then. I think only Eric or I have access to do this.

Doesn't look like that's possible:
![image](https://user-images.githubusercontent.com/31904439/144487101-2a24ef7c-222d-4874-806d-b6b73d157fbf.png)

**Comment by ElijahLynn** [comment]
The tugboat.vfs.va.gov cert is also unused, as we are using a *.vfs.va.gov wildcard cert. So, I am just going to retire this cert too. 
![image](https://user-images.githubusercontent.com/1504756/145449470-bd6021c3-6a1d-4cdc-8020-652bcb814b48.png)

**Comment by ElijahLynn** [comment]
Cert has been renewed and updated in ACM, verified it is working on a Tugboat env here: 
![image](https://user-images.githubusercontent.com/1504756/146266548-c9cfebc2-166a-44ba-be11-f06a9ca1a331.png)


It is good until Jan 8th and I set a slack reminder for #cms-platform for Jan 1 2023.
