### ISSUE TITLE
GovDelivery Callback Not Working from GHA

### ISSUE THREAD

**Issue by indytechcook** [department-of-veterans-affairs/va.gov-cms#7117]
## Description

This issue is to track the issue regarding GHA not calling the GovDelivery callback in the CMS.  The CMS team is providing support and verification to the FE tools team.

The actual work is being done by the FE tools team in this issue: https://github.com/department-of-veterans-affairs/va.gov-team/issues/24193

## Acceptance Criteria

- [x] Assist FE Tools team with debugging, troubleshooting
- [x] Verify the callback is working correctly from GHA
- [ ] Create follow up ticket for resolution if needed
- [ ] Verify A Content Release from Drupal triggers GHA and the GovDelivery callback is hit correctly.

**Comment by oseasmoran73** [comment]
Fix for GovDelivery Callback department-of-veterans-affairs/content-build#802

Confirmed it is successful in this flow https://dsva.slack.com/archives/C0MQ281DJ/p1638394280430000

**Comment by indytechcook** [comment]
PR for Drupal using GHA has been merged and Deployed.  When this is complete and tested I will close this issue.

**Comment by indytechcook** [comment]
I've confirmed Drupal is making calls to GHA.
