### ISSUE TITLE
Implement better content build status monitoring

### ISSUE THREAD

**Issue by jkalexander7** [department-of-veterans-affairs/va.gov-cms#7126]
## User Story or Problem Statement

Currently, we have passive monitoring and failure monitoring, but nothing that provides real-time, urgent updates regard the content build, accessible in one place. Some alerts are provided via Slack, but not for all systems.

As a CMS engineer/editor, I need a better way of monitoring the content build, so that I can see high-level, urgent updates in one place, such as a status page.

## Acceptance Criteria
- [ ] Determine tool to host status page (e.g. Datadog)
- [ ] Identify outputs to display
- [ ] Testable_Outcome_Z

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [x] `Platform CMS Team`
- [ ] `Sitewide CMS Team`

**Comment by mchelen-gov** [comment]
What does "monitoring the content build" consist of?

**Comment by TheBoatyMcBoatFace** [comment]
Covered in #11675
