### ISSUE TITLE
Eliminate the va/web/build within testing stack

### ISSUE THREAD

**Issue by jkalexander7** [department-of-veterans-affairs/va.gov-cms#7130]
## User Story or Problem Statement

As a CMS Engineer, I want to eliminate the `va/web/build` in the testing stack, so that I can reduce the number of build failures.

## Acceptance Criteria
- [ ] Verify ‘va/tests/behat’ is the only build running during tests
- [ ] Document test run time improvement 

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [x] `Platform CMS Team`
- [x] `Sitewide CMS Team`

**Comment by TheBoatyMcBoatFace** [comment]
@ndouglas is this more in your wheelhouse?

**Comment by ndouglas** [comment]
@TheBoatyMcBoatFace This is actually already accomplished.  Good to close 🙂
