### ISSUE TITLE
Investigate whether apache logs are in loki

### ISSUE THREAD

**Issue by jkalexander7** [department-of-veterans-affairs/va.gov-cms#7150]
## User Story or Problem Statement

Investigate whether apache logs are in loki

## Acceptance Criteria
- [ ] Identify if apache access and error logs are in loki
- [ ] Create follow up ticket/work with Ops team to address if not

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [x] `Platform CMS Team`
- [ ] `Sitewide CMS Team`

**Comment by TheBoatyMcBoatFace** [comment]
Apace logs in Datadog. Loki is no longer in use
