### ISSUE TITLE
Implement Fix to Resolve HTTP 502 Errors for Tugboat

### ISSUE THREAD

**Issue by olivereri** [department-of-veterans-affairs/va.gov-cms#7151]
## User Story or Problem Statement

The investigation is in https://github.com/department-of-veterans-affairs/va.gov-cms/issues/5552.
AWS Issue: https://console.amazonaws-us-gov.com/support/home#/case/?displayId=9221808181&language=en

Our CI environments are seeing intermittent 502 bad gateway responses in the ALB logs which are causing multiple PR failures on vets-website branch build PRs and CMS PRs. 

This has been resolved for BRD environments with the support of AWS in the issue referenced above. To fix this for CI we should implement the BRD change for Tugboat Preview environments.

## Acceptance Criteria
- [x] Tugboat no longer responds to requests with HTTP 502
- [x] Validate that the content build no longer fails due to 502 error

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [x] `Platform CMS Team`
- [ ] `Sitewide CMS Team`

### Implementation Details:
- Modifying https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/.tugboat/web-vhost.conf by adding a `KeepAliveTimeout 185` should have the same affect as the fix for BRD hosted CMS sites.

### Reference:

https://github.com/department-of-veterans-affairs/va.gov-cms/issues/7023

**Comment by ndouglas** [comment]
Edited OP to reflect that @olivereri ultimately changed KeepAliveTimeout to 185, not 1805.

**Comment by cweagans** [comment]
As a heads up, this caused a content build failure on Wednesday: https://dsva.slack.com/archives/C02HX4AQZ33/p1639005384217100

**Comment by indytechcook** [comment]
This was merged but we did get a 502 this week on a PR.  The log is gone though.

**Comment by indytechcook** [comment]
One additional thing this did is put a limit to how long request should run in apache.  It actually helped us catch a ineffective GraphQL query in a content_build PR: https://github.com/department-of-veterans-affairs/content-build/pull/864 and allowed me to work with the FE engineer to improve the query.

**Comment by indytechcook** [comment]
I'm happy closing this and just opening new issues if they arise!

**Comment by ndouglas** [comment]
Possibly still happening https://dsva.slack.com/archives/CT4GZBM8F/p1641221706221600 -- I'ma rubberduck it a bit in this thread before I open an issue.

**Comment by olivereri** [comment]
## Reference Links
https://aws.amazon.com/premiumsupport/knowledge-center/trace-elb-x-amzn-trace-id/
