### ISSUE TITLE
PROD outage - 2021.12.03

### ISSUE THREAD

**Issue by ElijahLynn** [department-of-veterans-affairs/va.gov-cms#7153]
We had a prod.cms.va.gov outage for approximately 3 minutes today from 1:58pm to 2:04pm ET. We identified it was a failed ALB healthcheck that removed the instance from the ASG and a new instance was spun back up but stuck in a `pending:wait` state, which I put into an active state with:

```
aws autoscaling complete-lifecycle-action \
          --region us-gov-west-1 \
          --auto-scaling-group-name "dsva-vagov-prod-cms-asg" \
          --lifecycle-hook-name launch-hook \
          --lifecycle-action-result CONTINUE \
          --instance-id i-0daf06df83d13fb29
```

Follow up items:

- [ ] Post-mortem analysis, determine if 502 fix that was merged recently was related
- [ ] Update ALB timeout from 1,800 to something lower (likely not related but we noticed this legacy value)

**Comment by cweagans** [comment]
Related slack thread: https://dsva.slack.com/archives/CT4GZBM8F/p1638558017243600

**Comment by TheBoatyMcBoatFace** [comment]
Too late - no longer an issue
