### ISSUE TITLE
H1 and breadcrumb is wrong for Lovell Federal health care

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#7163]
## To Reproduce
1. Go to https://va.gov/lovell-federal-health-care
2. Note that it reads VA Lovell Federal health care for the h1, and Lovell FHCC for the breadcrumb

## Expected behavior
- [ ] It should read Lovell Federal health care in both places

## Screenshots 
<details><summary>FE</summary>

<img width="1108" alt="VA_Lovell_Federal_Health_Care___Veterans_Affairs" src="https://user-images.githubusercontent.com/643678/144735492-1d74e901-3520-4cb4-8606-88927708f63c.png">

</details>

<details><summary>CMS</summary>

These all need to read "Lovell Federal health care
<img width="596" alt="VA_Lovell_Federal_health_care___Veterans_Affairs" src="https://user-images.githubusercontent.com/643678/144732380-ac07f71c-5f8d-436e-bbac-2dfe2f9dd57c.png">

</details>

 ## Additional context

There may need to be a change on the FE `va-lovell-federal-health-care',`  may need to be `lovell-federal-health-care` in order to change the h1 / VAMC system name [in this file](https://github.com/department-of-veterans-affairs/content-build/blob/32b4170dffa06c4b4cf95d044ca390072e97e273/src/site/stages/build/drupal/graphql/navigation-fragments/facilitySidebar.nav.graphql.js#L90).

This may require a new menu in drupal too, with that machine name, and which will need to be enabled for all VAMC content types. 

This may require some careful change management. 

I did some digging but i could not figure out where the "FHCC" is coming from in the Drupal breadcrumb.

**Comment by swirtSJW** [comment]
Here are the new set of steps needed on this.  
- [ ]  Create new menu in code  -> CMS PR
machine name `lovell-federal-health-care`
title `Lovell Federal health care`
Admin summary `VISN 12 | va.gov/lovell-federal-health-care`
   - [ ] Add that menu to the menu breadcrumbs config through the UI.
   - [ ] Add it to workbench menu access referencing "VA Lovell federal health care`
- [ ]  When CMS PR makes it to CMS.... populate the new menu One item at a time.
- [ ] Add the new menu machine name `lovell-federal-health-care` under VISN 12 in https://github.com/department-of-veterans-affairs/content-build/blob/32b4170dffa06c4b4cf95d044ca390072e97e273/src/site/stages/build/drupal/graphql/navigation-fragments/facilitySidebar.nav.graphql.js   Do NOT REMOVE the old one.  -> content-build PR
- [ ] Once the content-build PR is released on content-build  and it has been updated to the release in our repo  Change the name in a tugboat demo environment change the name of the system (/lovell-federal-health-care) to remove the VA from the name.  Trigger a content release in tugboat.  Validate that the right menu is showing and content build happens correctly.
- [ ] Change the system name to remove the 'VA' on prod https://prod.cms.va.gov/lovell-federal-health-care and publish.  
- [ ] Watch the next content release for failure.
- [ ] Create content-build PR to remove 'va-lovell-federal-health-care', from https://github.com/department-of-veterans-affairs/content-build/blob/32b4170dffa06c4b4cf95d044ca390072e97e273/src/site/stages/build/drupal/graphql/navigation-fragments/facilitySidebar.nav.graphql.js
- [ ] Once that PR has been merged and makes it all the way to the CMS codebase.
- [ ] Delete the old menu VA Lovell Federal health care with CMS PR. (successful testing pipeline run on this PR is all that is needed)

**Comment by netboss** [comment]
@swirtSJW 
PR for the first steps have been created: https://github.com/department-of-veterans-affairs/va.gov-cms/pull/7241

**Comment by netboss** [comment]
@swirtSJW 
As a test, I populated the [prod CMS Lovell Federal health care menu](https://prod.cms.va.gov/admin/structure/menu/manage/lovell-federal-health-care) with all the menu items from the VA Lovell Federal health care menu. Then in my personal tugboat site edited the Lovell Federal health care node and removed the VA from the page title and assigned the new Lovell Federal health care menu to the node, and then created a content release and everything but the menu showed fine. See screen shot.
![tugboat-Lovell-Federal-health-care-page](https://user-images.githubusercontent.com/846871/146273853-3867a0ab-ee92-4376-8a22-2d2d7492e75a.png)

Could it be that the prod CMS content haven't been propagated yet? Not sure why isn't showing.

**Comment by netboss** [comment]
@swirtSJW 
I tried again today. Rebuilt my tugboat site instance, then edited the /lovell-federal-health-care node and updated the page title and reassigned the new menu, then triggered a new content release and then checked the front-end and this time all worked fine. See screen shot.
![tugboat-lovell-page-new-menu](https://user-images.githubusercontent.com/846871/146456930-d1fd6fb0-c137-4ac6-93ae-0d1c65aaa85e.png)

Now, for the next steps:
> [ ] Change the system name to remove the 'VA' on prod https://prod.cms.va.gov/lovell-federal-health-care and publish.
> [ ] Watch the next content release for failure.
Where can I see the content release process and check if there are any failures?

**Comment by swirtSJW** [comment]
> @swirtSJW I tried again today. Rebuilt my tugboat site instance, then edited the `/lovell-federal-health-care` node and updated the page title and reassigned the new menu, then triggered a new content release and then checked the front-end and this time all worked fine. See screen shot. ![tugboat-lovell-page-new-menu](https://user-images.githubusercontent.com/846871/146456930-d1fd6fb0-c137-4ac6-93ae-0d1c65aaa85e.png)
> 
> Now, for the next steps:
> 
> > [ ] Change the system name to remove the 'VA' on prod https://prod.cms.va.gov/lovell-federal-health-care and publish.
> > [ ] Watch the next content release for failure.
> 
> Where can I see the content release process and check if there are any failures?

@netboss  You are worrying me with this question because we can not make that switch until the old menu and new menu are the same.
This step is checked off as done, but it is not done.  
- [ ] When CMS PR makes it to CMS Prod.... populate the new menu One item at a time.

Those menus have to be the same   Otherwise when you make the switch on prod, they aren't going to look or work the same.
![image](https://user-images.githubusercontent.com/5752113/146823535-467a2d98-a6d4-4e4c-afc9-d709e6f3fb76.png)

**Comment by netboss** [comment]
@swirtSJW 
I checked it thinking that by populating the (enabled) menu items was enough. Do I also need to populate the disabled menu items too?

**Comment by swirtSJW** [comment]
Discussed on a call.   The old menu and the new menu need to be the same.  Same items, same order, same states.

**Comment by netboss** [comment]
@swirtSJW 
CMS prod new Lovell menu have been updated. See screen shots.
![lovell-menu-comp-1](https://user-images.githubusercontent.com/846871/146835668-8125999f-0159-4cba-8ae4-45692ffd3c37.png)
![lovell-menu-comp-2](https://user-images.githubusercontent.com/846871/146835673-2baeb65e-a98a-4306-8ada-e11ccbdc84fb.png)
![lovell-menu-comp-3](https://user-images.githubusercontent.com/846871/146835679-263195e6-52c2-49bc-9cd5-8c12dfbcddf1.png)
![lovell-menu-comp-4](https://user-images.githubusercontent.com/846871/146835685-16448720-8d96-405d-a52d-e7eaa572815b.png)

Now rebuilding tugboat instance to run test. Will update later.

**Comment by netboss** [comment]
@swirtSJW 
Updated the `/lovell-federal-health-care` node, changed the page title and reassigned new Lovell menu and all worked fine. See screen shot.
![lovell-federal-health-care-FE](https://user-images.githubusercontent.com/846871/146840492-8f7cebad-59bc-4a9a-bc08-ee667f67c31a.png)

I'll trigger a re-build on this content-build PR: https://github.com/department-of-veterans-affairs/content-build/pull/858

**Comment by netboss** [comment]
@swirtSJW 
As a test, in my tugboat instance, removed the original VA Lovell Federal health care menu and triggered another content release. Then after that tested (almost) all pages in the Lovell menu and all looked and worked fine. See screen shots.

![Screenshot 2021-12-21 at 15-28-56 Lovell Federal health care Veterans Affairs](https://user-images.githubusercontent.com/846871/146997581-e66b6e0c-bfbc-453f-a292-826445eaf6a0.png)

![Screenshot 2021-12-21 at 15-54-18 Health services Lovell Federal health care Veterans Affairs](https://user-images.githubusercontent.com/846871/146997596-a30d19ff-5265-479b-b84b-0cdb87344a24.png)

![Screenshot 2021-12-21 at 15-54-44 Locations Lovell Federal health care Veterans Affairs](https://user-images.githubusercontent.com/846871/146997603-9f0480bf-be9f-4054-895f-dd782b12bfdc.png)

![Screenshot 2021-12-21 at 15-55-07 Events Veterans Affairs](https://user-images.githubusercontent.com/846871/146997615-bff06f7c-a1b7-4dfd-9c25-02d932588b2b.png)

![Screenshot 2021-12-21 at 15-55-21 News releases Lovell Federal health care Veterans Affairs](https://user-images.githubusercontent.com/846871/146997624-acfeddd4-8e26-4eae-8b7c-19fde59ddd12.png)

![Screenshot 2021-12-21 at 15-55-35 Stories Lovell Federal health care Veterans Affairs](https://user-images.githubusercontent.com/846871/146997636-0aea1480-f270-4216-8c9f-77a82e34b1a6.png)

![Screenshot 2021-12-21 at 15-55-54 About us Veterans Affairs](https://user-images.githubusercontent.com/846871/146997658-f7135daa-9381-4db2-bb32-fc7f3b0db5f3.png)

![Screenshot 2021-12-21 at 15-56-12 Mission and vision Veterans Affairs](https://user-images.githubusercontent.com/846871/146997677-bc989acb-85fb-419d-ba47-4020bf80b583.png)

![Screenshot 2021-12-21 at 15-56-27 Work with us Veterans Affairs](https://user-images.githubusercontent.com/846871/146997701-008c2f7a-c700-48af-86f2-e4825406be3a.png)

![Screenshot 2021-12-21 at 15-56-43 Jobs and careers Veterans Affairs](https://user-images.githubusercontent.com/846871/146997721-5687cfdb-52da-4f56-b6f0-7edd1413eb17.png)

![Screenshot 2021-12-21 at 15-57-01 Contact us Veterans Affairs](https://user-images.githubusercontent.com/846871/146997741-be9c1086-c5f9-4398-a788-947e992e29dd.png)

![Screenshot 2021-12-21 at 15-57-16 Lovell Federal Health Care Veterans Affairs](https://user-images.githubusercontent.com/846871/146997763-e9919a51-7d60-4971-808e-150846a34ff1.png)

![Screenshot 2021-12-21 at 15-57-32 Programs Veterans Affairs](https://user-images.githubusercontent.com/846871/146997772-8d003931-ca42-47b7-8c09-8413cbb0e80d.png)
