### ISSUE TITLE
Wireframe for "React Widget" Paragraph

### ISSUE THREAD

**Issue by cjterdi** [department-of-veterans-affairs/va.gov-cms#7200]
## Description
We are making minimal changes to the Claro theme to deliver a usable, satisfactory new "look and feel" to our users. This includes updating the Claro-themed tokens to reflect VA branding and to add visual consistency.

The purpose of wireframing paragraphs:
-  Test for visual consistency across all content configurations
- Provide visual communication between design intent and drupal output

User story: As a CMS user, I can see that the look and feel of the CMS has changed, but on the whole, those changes have a neutral or positive impact on my satisfaction and ability to use the cms.

## Acceptance Criteria
- [ ] Completed wireframe for the "React Widget" paragraph, accessible on Figma
### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [x] `Sitewide CMS Team`

**Comment by cjterdi** [comment]
Build out component in Figma

**Comment by kevwalsh** [comment]
Ideally react widget paragraphs would not only have one field, not the current 6 fields, and they would have a single source of truth. 

They would either reference a CMS entity, like from a dropdown or an entity selector tool. There's an epic #2919  to refactor this. so i've added this issue to that epic too.

**Comment by cjterdi** [comment]
There is a desire to have all components (including paragraphs) as is included in the DS. This is an easy to moderate lift to build out the rest of these, but does not address specific usability issues. I think creating a new epic and then prioritizing them (for Q3?) makes sense.
