### ISSUE TITLE
Build a dashboard to display content build metrics

### ISSUE THREAD

**Issue by cweagans** [department-of-veterans-affairs/va.gov-cms#7212]
Follow-up to https://github.com/department-of-veterans-affairs/va.gov-cms/issues/6805

Now that the metrics are being sent to Datadog, we need to display them. This is what the old dashboard looked like:

![image](https://user-images.githubusercontent.com/101590/145083537-c22b415d-bad7-475a-aa13-e5dbdacd01ef.png)

We do not need to match that dashboard 1:1, but the metrics should be as easy to digest. Note that there are more metrics available now, so we may be able to show more granular timings/statistics.

### Acceptance criteria
* [x] Content Build metrics are displayed on a dashboard in Datadog: https://app.datadoghq.com/dashboard/eb9-ece-f9z/platform-cms-prod-cms?tile_size=xl&from_ts=1640269612971&to_ts=1640874412971&live=true
- [x] Metrics to include: build duration, GQL time, build time, GQL pages, and published node count  (if story is ready: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/7244): https://app.datadoghq.com/dashboard/eb9-ece-f9z/platform-cms-prod-cms?tile_size=xl&from_ts=1640269612971&to_ts=1640874412971&live=true

### CMS Team

- [x] `Platform CMS Team`
- [ ] `Sitewide CMS Team`

**Comment by indytechcook** [comment]
I added widgets to the dashboard: https://app.datadoghq.com/dashboard/eb9-ece-f9z/platform-cms-prod-cms?tile_size=xl&from_ts=1640269612971&to_ts=1640874412971&live=true

**Comment by indytechcook** [comment]
![image](https://user-images.githubusercontent.com/121603/147761905-63c5b194-388c-4237-b19e-ba2dcfe52ec8.png)
