### ISSUE TITLE
Update content build Datadog API key

### ISSUE THREAD

**Issue by cweagans** [department-of-veterans-affairs/va.gov-cms#7213]
Right now, the content build process is using the CMS API key for Datadog. We need to generate a new one for FE Tools and swap it out.

### Acceptance Criteria:
* [x] create DD api key for content build
* [x] store it in parameter store in a path the frontend team service account already has access to following existing naming convention / heirarchy (`/dsva-vagov/content-build/GHA_CONTENT_BUILD_DATADOG_API_KEY`)
* [x] update the github action to use that parameter instead (update should be here: https://github.com/department-of-veterans-affairs/content-build/blob/caafd846d61507938fa94df45d92b7743825230c/.github/workflows/content-release.yml#L707) => https://github.com/department-of-veterans-affairs/content-build/pull/937
* [x] revert the pr that added the cms datadog api key path to the frontend team service account user perms (PR + terraform apply) (https://github.com/department-of-veterans-affairs/devops/pull/10376)

### Resources

* Storing parameter store secrets: https://vfs.atlassian.net/wiki/spaces/pilot/pages/1474595172/Store+a+secret+in+Parameter+Store
* Creating Datadog API and Application keys: https://vfs.atlassian.net/wiki/spaces/OT/pages/1934655507/Get+or+Create+API+and+Application+keys+for+Datadog
* Context for this ticket: https://dsva.slack.com/archives/CBU0KDSB1/p1638562951464800
* Other monitoring work in progress: https://github.com/department-of-veterans-affairs/va.gov-team/issues/32896

### CMS Team

- [x] `Platform CMS Team`
- [ ] `Sitewide CMS Team`

**Comment by indytechcook** [comment]
Given the update in ownership, let's create a new key for the content build repo.

**Comment by ElijahLynn** [comment]
AC 2 and 4 seem conflicting:

> store it in parameter store in a path the frontend team service account already has access to following existing naming convention / heirarchy

> revert the pr that added the cms datadog api key path to the frontend team service account user perms (PR + terraform apply) (Update iam_gha_resources.tf devops#10376)

It seems that we don't need to store it in the same path naming convention if we are removing that access in that PR revert. Yah?

**Comment by cweagans** [comment]
It shouldn't be the same path. Just one that the content build has access to. The specific path doesn't matter that much. Just that we're using a different key.

**Comment by ElijahLynn** [comment]
Ended up putting it at `/dsva-vagov/content-build/GHA_CONTENT_BUILD_DATADOG_API_KEY`. 

PR https://github.com/department-of-veterans-affairs/content-build/pull/937 is ready to merge once approved, then https://github.com/department-of-veterans-affairs/devops/pull/10635 is ready to merge after that.

**Comment by ElijahLynn** [comment]
Both PRs have been merged, this is done :heavy_check_mark:.
