### ISSUE TITLE
Create a report of how many VAMC detail pages are at levels 5, 6 and 7 and beyond

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#7220]
## User Story or Problem Statement

The left nav on the FE of the VAMC websites displays up to 6 levels of depth, but it's not easy to read. 

The only type of content that can be added to the VAMC menu at such a deep level is the VAMC detail page.  The CMS does not limit the depth when editors create VAMC detail pages, depth can be infinite as of now. 

We need some data analysis to see 
* how many pages are at levels 5 and above on VAMC websites 
* which VAMC website (should be implicit based on the URL)

## Acceptance Criteria
- [ ] A report has been created showing how many items are at each level
- [ ] We can make decisions about IA governance and any ensuing change management that may be required. 

## Implementation steps
<optional>

**Comment by Agile6MSkinner** [comment]
I don't plan on ticketing discovery, so this ticket is obsolete. Closing.
