### ISSUE TITLE
Removing a Vet Center service leads to a confusing confirmation message

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#7221]
## Describe the defect
When an editor removes a Vet Center Service, they are asked in a confirmation message ```Are you sure you want to remove %AutoEntityLabel%?```

## To Reproduce
1. Edit a Vet Center (eg /node/3840/edit)
2. Remove a service
3. See bad confirmation message

## Expected behavior
(pending UX writing confirmation) 

Confirmation message should say: ```Are you sure you want to remove [Vet Center service]?``` For example ```Are you sure you want to remove Workshops and classes?```
 
## Screenshots 
![image](https://user-images.githubusercontent.com/643678/145228312-0f6639c6-e8d8-43d9-b62c-ca4d0e13a03f.png)

## Implementation

Worth looking at drupal issue queue for Auto entity label / IEF integration? Some quick googling found this [d.o. issue
](https://www.drupal.org/project/auto_entitylabel/issues/1980652)

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Platform CMS Team`
- [x] `Sitewide CMS Team`

**Comment by davidmpickett** [comment]
![Screenshot 2024-07-01 at 6 04 07 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/28a14c61-99eb-4e80-9f78-da9f962128ad)

This defect is no longer occurring
