### ISSUE TITLE
Define Design System MVP

### ISSUE THREAD

**Issue by MontagnaDave** [department-of-veterans-affairs/va.gov-cms#7227]
Team, below are the list of items we came up with as potential MVP release items.  Please feel free to add items and we will discuss next week

Port Custom Code
Create Design System Tokens
Update Login Page
VA coloring and branding

**Comment by EWashb** [comment]
I think we might have dupe issues. We already have [this one ](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/7225). Thoughts?

Also, just a small thing. I think Denise was added when it should have been @cjterdi  :)

**Comment by MontagnaDave** [comment]
I think Kevin created one like 10 minutes before I did.

**Comment by kevwalsh** [comment]
yeah let's stick to #7225.
