### ISSUE TITLE
[Spike] Investigate which situations environment variables are not being made available to the CMS.

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-cms#7239]
## Description
In some cases, [environment variables](../blob/main/READMES/environment-variables.md) are not actually being provided to the running application.  This is causing Raven to fail to report errors to Sentry, but it might be causing other issues (which are harder to detect because they are not being reported to Sentry).  The cause of this should be diagnosed so that we can determine how to deal with it.

## Acceptance Criteria
- [ ] The circumstances under which environment variables are injected into the application environment have been investigated.
  - [ ] three situations are currently known and deserve to be investigated:
    - [ ] Some SimpleSaml logins seem to be affected by this
    - [ ] A particular user (David G___) appears to trigger this reliably upon login by causing headers to be sent multiple times 
    - [ ] Some database errors appear to trigger it, although this could happen in almost any context
- [ ] Investigation findings have been documented
- [ ] A followup issue has been created to deal with the findings.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [x] `Platform CMS Team`
- [ ] `Sitewide CMS Team`

**Comment by ElijahLynn** [comment]
Made a workaround guide for now: https://vfs.atlassian.net/wiki/spaces/PCMS/pages/2142109819/How+to+recover+from+a+failed+deploy+to+DEV+STAGING
