### ISSUE TITLE
PIV card login failing

### ISSUE THREAD

**Issue by indytechcook** [department-of-veterans-affairs/va.gov-cms#7272]
## Description

The PIV card login is failing due to an issue with validating the certificate

![image (3)](https://user-images.githubusercontent.com/121603/145833961-0af894dd-6978-44c9-a5fb-19e2f211486d.png)

Investigation here: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/7272#issuecomment-992569297

**Root cause**: The new public key was updated in the environment variable.  The environment variable isn't used in production.   Production only uses what's in [git](https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/simplesamlphp-config-metadata/metadata/saml20-idp-remote.php#L50).

**Comment by indytechcook** [comment]
Investigation with @ndouglas 

* Nate and I looked at the code where the error occurred and this is where the simplesaml module is trying to validate the XML based upon the public SSL key.  
* The public SSL key was updated last week in this PR: https://github.com/department-of-veterans-affairs/devops/pull/10368.
* Neil found an old ticket with a similar issue where @olivereri update a key in the va.gov-cms repo: 
* Nate found the devops code which copys the enviornent variable to the configuration file for simpleSAML.  The code does not run for prod.  The PR which was updated to add the new key only updated the environment variable which is only used for non-prod.
* Nate found that the key stored in the `saml20-id-remote.php` did not match what was in the devops PR.
* Nate updated the file on prod manually with the new key and restarted Apache
* Neil tested PIV and it worked.
* CMS Helpdesk tested and it worked.

**Current statue:** The file is manually updated in production and will be blown away with the next deploy.  A key currently seems to be stored in git: 

Next steps:

- [ ] Have prod deploy use the environment variable.

**Comment by ElijahLynn** [comment]
We need to update https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/platform/cms/cms-sso-saml-iam-login-how-to.md too.

**Comment by ElijahLynn** [comment]
> We need to update https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/platform/cms/cms-sso-saml-iam-login-how-to.md too.

Actually, with #10422 merged, the docs above will be accurate.

**Comment by indytechcook** [comment]
The PR is merged, after today's prod, if PIV login still works then I'll close this issue.

**Comment by indytechcook** [comment]
I verified that PIV is working after the deploy.
