### ISSUE TITLE
Do not print media paragraph html wrapper if there is no image

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#7275]
## Describe the defect
Media paragraphs should not be empty. but if they are, do not print the HTML

## To Reproduce
Hard to reproduce, especially after #7274 gets fixed. 

## Expected behavior
media paragraph liquid fragment should check that `img src` value exists before creating HTMl.

## Screenshots 

<details><summary>Screenshot</summary>

​
![image](https://user-images.githubusercontent.com/643678/145837895-750172db-6ec4-4aa4-a6a0-36fb71f4c84d.png)

</details>

 ## Additional context
[Slack thread with broken link](https://dsva.slack.com/archives/C0MQ281DJ/p1639405204059200)
 

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Platform CMS Team`
- [x] `Sitewide CMS Team`

**Comment by swirtSJW** [comment]
Here is the related PR https://github.com/department-of-veterans-affairs/content-build/pull/930

**Comment by netboss** [comment]
@swirtSJW 
Please let me know when this can be closed.
