### ISSUE TITLE
VAMC top level menu links based on nodes should not be output on VAMC menus

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#7287]
## Describe the defect

VAMC menus output menu items at the top level of the menu, whether they have paths associated or not. 

They should only ever output the three "spokes": 
* Services and locations
* News and events
* About [VA system name]

<details><summary>Screenshot</summary>

<img width="387" alt="Cursor_and_Slack___Threads___Digital_Service___VA___5_new_items" src="https://user-images.githubusercontent.com/643678/146037024-9e342a49-5656-45a7-80cf-a31143dfe820.png">

</details>

## To Reproduce

In a tugboat environment

1. Go to https://prod.cms.va.gov/node/add/health_care_region_detail_page
2. Add a menu item title "Test unpublished content" with the parent `-- VA Pittsburgh health care` 
3. Save as draft
4. Trigger content release
5. **Note the menu item shows up as black in the left nav**

## Expected behavior
No menu item with a path should show up on the same level as three spokes "Services and locations". "News and events, "About [VAMC] system". 
(Only `<nolink>` menu items should show in the first level of the VAMC menu).

 ## Additional context
Some work was done to not show menu items for unpublished content, but that logic doesn't seem to apply to the first level labels. 

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Platform CMS Team`
- [x] `Sitewide CMS Team`

**Comment by kevwalsh** [comment]
[Per this slack convo](https://dsva.slack.com/archives/CT4GZBM8F/p1639434637295300), it may be worth looking at benefits hubs too. 

<img width="1177" alt="Edit_menu_Careers___employment_benefits_hub___VA_gov_CMS_and_Veteran_Readiness_And_Employment__VR_E____Veterans_Affairs" src="https://user-images.githubusercontent.com/643678/146102610-ef36fa02-5c09-4f85-a2c8-affbf88a344d.png">

**Comment by Agile6MSkinner** [comment]
No commentary on this for years and likely obsolete. Closing as not planned.
