### ISSUE TITLE
Facility change: Potsdam

### ISSUE THREAD

**Issue by chriscraiga6** [department-of-veterans-affairs/va.gov-cms#7290]
## Intake: Editor Submission to HD
- [ ] Submitter: Susan George
- Change type (select one)
  - [ ] VAMC new facility
  - [ ] VAMC facility closure
  - [x] VAMC facility name
  - [ ] VAMC system name
  - [ ] Vet Center new facility
  - [ ] Vet Center facility closure
  - [ ] Vet Center facility name
- [ ] If the submitter is an editor, send them the link to the CMS Knowledge Base (KB) article on facility basic data for their product (VAMC or Vet Center). Let them know that facility changes can take between 75 days and 4 months after submitting a request, according to VAST administrators.
- [ ] If the change is a facility closure, send the editor a link to the operating status KB article and have them change the status to Facility notice and provide a description of the facility closure so that Veterans are aware of the future closure.
- [ ] Other stakeholders to include on updates, if any: <insert name>
 
## Acceptance criteria 
  

    
- [x] The H1 title change comes from Lighthouse to Drupal.
- [x] CMS engineer makes bulk alias changes to facility service nodes. (https://prod.cms.va.gov/admin/content/bulk?type=health_care_local_health_service)
- [x] CMS engineer bulk saves fixed titles to facility service nodes. (https://prod.cms.va.gov/admin/content/bulk?type=health_care_local_health_service)
- [x] CMS engineer updates menu title.
- [x] Front-end (FE) redirects are set up.
- [ ] HD notifies editor and any other stakeholders.
 
ACs added after [Dec 15 Facilities meeting](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/product-team-support/product-team-weekly-syncs/facilities-cms-weekly-sync.md#vamc). These take the place of `- [ ] Front-end (FE) redirects are set up.` above.
- [ ] [Redirect request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=ia&template=redirect-request.md&title=Redirect+Request) submitted to reflect the new URL pattern to note the h1 has already changed (because VAST) but the URL is still the old URL(before: /syracuse-health-care/locations/massena-va-clinic/ after: /syracuse-health-care/locations/potsdam-va-clinic/ 
  - [ ] cc Dave and Michelle
  - [ ] After submission of redirect request, check with Mikki Northuis about "pre-approving" these types of redirects, and assigning straight to PW team  -- when the h1 has changed due to VAST data change, can we work directly with PW around timing of redirect
  - [ ] Once timing of redirect going live is known, alert CMS engineers to carry out the other steps
- [ ] Update runbook (the github template?) to include these steps

CMS Team
Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.
- [ ] Platform CMS Team
- [X] Sitewide CMS Team

**Comment by chriscraiga6** [comment]
@swirtSJW @JayDarnell The VAMC Massena has changed names to "Potsdam". 

VA Locator shows the facility name has changed in the facility API. 
Prod shows the updated facility name. 
12 items/urls still have reference to "Massena"

**Comment by swirtSJW** [comment]
This is held up waiting on a redirect to be created 
from https://www.va.gov/syracuse-health-care/locations/massena-va-clinic/ 
to:   https://www.va.gov/syracuse-health-care/locations/potsdam-va-clinic/

Following that we need 
- [ ] menu title change
- [ ] Then alias changes to all facility health services
- [ ] bulk save of all facility health services

**Comment by xiongjaneg** [comment]
Initial email to editor: We’re working on getting this resolved and we’ll follow-up when the changes are completed. https://va-gov.atlassian.net/browse/VAHELP-3113

**Comment by xiongjaneg** [comment]
Once redirects are in place, let editor know this part is done and that the Drupal names and URL aliases need to be updated.

**Comment by kevwalsh** [comment]
@xiongjaneg @chriscraiga6 @JayDarnell @swirtSJW  i've updated the issue with some notes from yesterday's Facilities meeting. I'm assigning this to Sprint 48, but knowing that it has dependencies on both PW and Sitewide Content & IA teams for completion. Who should this be assigned to? For now i'm assigning it to a few people, we can figure this out next week.

**Comment by kevwalsh** [comment]
I've [updated](https://github.com/department-of-veterans-affairs/va.gov-cms/commit/a155fd6a2b805d1ec5b8d90813813a07164ffbfa) the [issue template](https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/.github/ISSUE_TEMPLATE/facility-data-change-request.md) a bit but it will need another update after we clarify a couple of the steps.

<details><summary>Screenshot</summary>
<img width="1268" alt="Update_facility-data-change-request_md_·_department-of-veterans-affairs_va_gov-cms_a155fd6" src="https://user-images.githubusercontent.com/643678/146489382-24eb0146-eceb-4702-9fab-86449fbba33d.png">



</details>

**Comment by JayDarnell** [comment]
Is this actionable? @swirtSJW said this was waiting on a redirect and it doesn't appear this redirect has been created yet.

**Comment by JayDarnell** [comment]
Redirect request has been submitted: https://github.com/department-of-veterans-affairs/va.gov-team/issues/34725

**Comment by swirtSJW** [comment]
Reidrect is in place.

**Comment by swirtSJW** [comment]
@chriscraiga6  This is set except for the last step of notifying the editor 
https://www.va.gov/syracuse-health-care/locations/potsdam-va-clinic  is live and https://www.va.gov/syracuse-health-care/locations/massena-va-clinic/ does a proper 31 redirect to postdam.

**Comment by JayDarnell** [comment]
@chriscraiga6 have we notified the editor as Steve mentioned above?
