### ISSUE TITLE
Update help text on vet center facility service body field

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#7298]
## Description
As a content editor I want to see help text that is meaningful in all scenarios and not just node creation.

This help text  guidance seems to only cover node creation but does not seem to apply to editing the node. 
![image](https://user-images.githubusercontent.com/5752113/146183679-89ff9d0d-3d71-42df-8585-d252cb1a0031.png)
"Add another short paragraph and up to six bullet points detailing how your Vet Center provides this service."
config/sync/field.field.node.vet_center_facility_health_servi.field_body.yml

There is only one time they would be **adding**.   The other 95%+ of the time they are not adding.   The add "**another**",  makes the assumption they just added one, which most likely they did not.     Add another is language we use elsewhere for clicking a button to actually add another something.

Would replacing "Add another" with the word "Write" work in this case?
"Write a short paragraph with up to six bullet points detailing how your Vet Center provides this service."  

Or declarative:  "This should be a short paragraph with up to six bullet points detailing how your Vet Center provides this service."

## Acceptance Criteria
- [ ] Hel text guidance for facility services applies to both creation and follow-up edits.
- [ ] Does not give direction "to add" When adding is not really an option.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Platform CMS Team`
- [x] `Sitewide CMS Team`

**Comment by suzanne-gray** [comment]
Please update help text for Vet Center service description to: `Use this short paragraph and up to six bullet points to detail how your Vet Center provides this service.`
