### ISSUE TITLE
Knowledge base content updates for Claro launch

### ISSUE THREAD

**Issue by EWashb** [department-of-veterans-affairs/va.gov-cms#7303]
## Background
Knowledge base content should reflect the new Claro changes and support editors as they orient to the new look

As an editor, I need to understand the new login procedures once the Claro theme is implemented. The existing ["How to log in/out" knowledge base article](https://staging.cms.va.gov/help/cms-basics/how-to-log-inout) will need to include how to troubleshoot PIV card login. 

## ACs
- [ ] Queue up the following updates in draft form:
   - [ ] Update all screenshot content identified in [the KB Claro audit](https://docs.google.com/spreadsheets/d/1vgyLlyj2Eo54TEZjR-25OHQpqURb3AI_YwHLKyCWzYw/edit#gid=1308613015)
   - [ ] Update *at least* top priority training video content (mainly content that explains log in) per [the KB Claro audit](https://docs.google.com/spreadsheets/d/1vgyLlyj2Eo54TEZjR-25OHQpqURb3AI_YwHLKyCWzYw/edit#gid=1308613015)
   - [ ] Update  ["How to log in/out" knowledge base article](https://staging.cms.va.gov/help/cms-basics/how-to-log-inout)  to include how to troubleshoot PIV card login. 
- [ ] Publish content updates on launch day

**Comment by rachel-kauff** [comment]
FYSA: I'm going to broaden this issue a bit to include ALL KB content changes we need to make for the Claro launch. Will include the "how to log in/out article as an AC!

**Comment by cmaeng** [comment]
@rachel-kauff @EWashb was this a sprint goal? if so, for CMS Experience Team? if not, no biggie.
