### ISSUE TITLE
HTML characters should not be counted in Vet Center Featured content text field

### ISSUE THREAD

**Issue by chriscraiga6** [department-of-veterans-affairs/va.gov-cms#7309]
## To Reproduce
1. Go to 'Edit a Vet Center'
2. Click on ''Featured Content"
3. Add "Featured Content"
4. Type more than 240 characters to within the description including a URL
5.See error message of "Description cannot be longer than 240 characters but is currently (number that's greater than 240) characters long
6. Remove characters until you're under 240 characters while keeping the URL intact
7. Continue to see error message of "Description cannot be longer than 240 characters but is currently (number that's greater than 240) characters long

## Expected behavior
The error message of "See error message of "Description cannot be longer than 240 characters but is currently (number that's greater than 240) characters long" should only appear when 240 characters has been exceeded and should disappear when the character limit has not been exceeded. 

## Screenshots 
https://files.slack.com/files-pri/T03FECE8V-F02QH4CQ32B/image.png

 ## Additional context
https://dsva.slack.com/archives/C02730UEZPS/p1639609477228700

## ACs
- [x] All text counters applied to rich text fields have been configured to ignore html characters
- [ ] Stretch: automated test to prevent this misconfiguration in the future. If we don't have time for this, let's spin up an issue in #1969

 

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Platform CMS Team`
- [x] `Sitewide CMS Team`

**Comment by xiongjaneg** [comment]
Without hyperlink
<img width="850" alt="Screen Shot 2021-12-16 at 7 48 33 AM" src="https://user-images.githubusercontent.com/73648238/146393453-eef9ae47-eccb-48c8-8b9a-f5a51115515d.png">

With hyperlink
<img width="820" alt="Screen Shot 2021-12-16 at 7 50 48 AM" src="https://user-images.githubusercontent.com/73648238/146393483-d8c33f32-034a-4878-aaee-030d485204bf.png">
