### ISSUE TITLE
Debug/run script to repair corrupt cloned nodes

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-cms#7313]
## Description
On 11/15, Stefanie [reported an issue with locked paragraph fields on a node for a specific user](https://dsva.slack.com/archives/CT4GZBM8F/p163961148243800).  Kevin recalled that I'd dealt with a similar issue previously and tagged me.  

I read the thread, confirmed that it resembled that previous issue, found the related issue (#5744), and investigated the database on staging.  I checked numerous nodes and paragraphs in the database and found that they had the exact same distinctive symptoms as observed in the affected entities in the original issue.  I ran the script I'd written at that time and monitored its progress.  It completed successfully and I verified by spot-checking entities that it appeared to have resolved the issues on the nodes in question, as well as a few hundred others.

I advised Clarence of my findings and we discussed them with Kevin and Steve.  We agreed I should run the script on production to fix the current issues.

Prior to that, I compared the output from the staging run to that from the last time I'd run the script on production (~July 15).  I found a number of nodes appeared in both runs.  I found this concerning, since the script should repair the node and its component entities permanently.  However, checking a number of those recurring nodes, I found that they had been cloned since July 15.  In other words, the script _does_ appear to repair the issue permanently, but the issue will reappear if and when the node is cloned again.

At that point, I decided I was comfortable executing the script again on production.  See [here](https://gist.github.com/ndouglas/8d8121f3b831e5cb585321eb0afbad72) for the log.  It completed successfully.  One node was locked; after unlocking it, I repaired that node separately.  No errors or other unexpected messages were seen.

I did some monitoring and other sniffing around after running the script, and I saw no unexpected issues or any other fallout.

## Acceptance Criteria
- [x] Script has been run on production and affected nodes and other entities are reported as repaired.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [x] `Platform CMS Team`
- [ ] `Sitewide CMS Team`

**Comment by indytechcook** [comment]
@ndouglas we are good to close this right?

**Comment by ndouglas** [comment]
Yep.
