### ISSUE TITLE
Finish merging and standardizing labels and components

### ISSUE THREAD

**Issue by stefaniefgray** [department-of-veterans-affairs/va.gov-cms#7316]
## Description
**Backstory:** @chriscraiga6 and I (@stefaniefgray ) previously went through all of our current Jira labels and components and determined which ones are worth keeping, which ones need to be updated (i.e. improper wording or capitalization), and which ones should be scrapped entirely (i.e. duplicates or ones that are never used.)

Previous ticket: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/5684

Master spreadsheet: https://docs.google.com/spreadsheets/d/1EwjMbiCBGCie1R1zjhb48nwUFQR-2m0tHPpVeHhb2Tg/edit?usp=sharing

## **Next steps:**

**Labels:**
- [x] Merge labels that we agreed upon merging
- [x] Remove labels that should be removed
- [x] Go back over reports in Jira and make sure new labels aren't affecting existing reports

**Components:**
- [x] Merge VAMC System and VAMC Facilities as "VAMC"
- [x] Write new descriptions for each component
- [x] Come up with a final determination of what is and isn't a component; may need to add new components, per spreadsheet.
- [x] Make sure helpdesk ticket submission form matches new components listing.

## Acceptance Criteria
- [ ] All tasks completed above.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Platform CMS Team`
- [x] `Sitewide CMS Team`

**Comment by cmaeng** [comment]
there were some questions around the "Component" field in JSD. from my knowledge, there is nothing that will break if you change this or tweak some of the components being used.

**Comment by chriscraiga6** [comment]
The labels and components that need to be changed have been identified but we are blocked by a lack of permissions. The needed people to grant these permissions were not available during the majority of the sprint. This has been brought up again today 1/3. Once the permissions are granted this can be completed.

**Comment by chriscraiga6** [comment]
Got with Jeff this morning and we got the permissions situated for both myself and Stefanie so this can be accomplished now :)

**Comment by stefaniefgray** [comment]
Unassigned myself since Chris says he's got the rest from here :) Thank you, Chris!

**Comment by chriscraiga6** [comment]
Removed components from HD Submission form. This has been completed.
