### ISSUE TITLE
KB Update: "Prepare For Your Visit" + Fisher House + Chaplain Services Info

### ISSUE THREAD

**Issue by stefaniefgray** [department-of-veterans-affairs/va.gov-cms#7328]
## Description
Over time, there has been an increased number of tickets from editors asking where to put Fisher House and Chaplain Services support service information on their site. 

Editors seem unsure where to place the information (making suggestions such as putting it under "Programs" or "About Us") and need to know that both of these services, amongst related support services, belong under "Prepare For Your Visit."

However, there is no dedicated "Prepare For Your Visit" page and neither Fisher House nor Chaplain Services are mentioned within the Knowledge Base.

"Prepare For Your Visit" is mentioned in a few places (such as within [the KB article on how to edit a VAMC Facility page](https://prod.cms.va.gov/help/va-medical-centers-vamcs/about-locations-content-for-vamcs/how-to-edit-a-vamc-facility)) but deserves an article of its own, along with clarification of why the Fisher House and Chaplain Services info belongs there.

## Acceptance Criteria
- [ ] "Prepare For Your Visit" gets its own KB article.

- [ ] Information about Fisher House is added to the new Prepare For Your Visit page, using [VA Ann Arbor](https://www.va.gov/ann-arbor-health-care/locations/lieutenant-colonel-charles-s-kettles-va-medical-center/) as an example. Details are provided about how to add Fisher House info as a Detail Page, and how to link the Detail Page beneath the Prepare For Your Visit section on your VAMC facility location page.

- [ ] Information about adding Chaplain Services is added to the new Prepare For Your Visit page.

- [ ] Re: Fisher House and Chaplain Services -- it's clear to site visitors that they are associated with individual facilities and not entire VA systems, since they are only available at specific locations.

- [ ] The new article is linked from the "[how to add a VAMC facility](https://prod.cms.va.gov/help/vamc/about-locations-content-for-vamcs/how-do-i-add-a-facility-to-my-health-care-system)" and "[how to edit a VAMC facility](https://prod.cms.va.gov/help/va-medical-centers-vamcs/about-locations-content-for-vamcs/how-to-edit-a-vamc-facility)" pages, as well as the "[how to add health services to your facility](https://prod.cms.va.gov/help/vamc/how-to-add-a-vamc-facility-health-service)" page (even though Prepare For Your Visit isn't a health service -- it's a related link!).

- [ ] When searching for Fisher House or Chaplain Services within the Knowledge Base, the new Prepare For Your Visit page is readily findable.

- [ ] Fisher House and Chaplain Services how-to text is added to "Canned Answers" documentation for easy reference, and new KB article is linked accordingly.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [x] `Platform CMS Team`
- [x] `Sitewide CMS Team`

**Comment by stefaniefgray** [comment]
@xiongjaneg Do tickets like this need to be run by Dave Conlon before starting the work, or could I create the page and add the info and then run it by him?

**Comment by xiongjaneg** [comment]
@stefaniefgray Please communicate this with VAMC Upgrade team first. They may already be drafting a KB article on this.
