### ISSUE TITLE
Allow editors to upload PDFs to CLP Resources section (not just link to external PDFs)

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#7331]
## User Story or Problem Statement

Editors are confused that they need to host PDFs outside the CMS, to link to them

This [was a decision by the product designer ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/campaign-landing-page-templates/content-requirements-spec/cms-content-model-and-rigidity.md#7-downloadable-resources-optional). But it's not working well, and as Teamsite and other web properties get retired, it will become more difficult.

## Acceptance Criteria
- [ ] Figma design for enabling CLP editors to uplaod PDFs to media library in the Resources panel, instead only linking out to an externally hosted one
- [ ] Review cycles with PM, ....
- [ ] Ticketed next/implementation steps

**Comment by Agile6MSkinner** [comment]
Abandoned years ago. Closing.
