### ISSUE TITLE
Staff profiles with no titles

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#7353]
## Description
Currently staff profiles use the name fields to generate the title.  However, names are not required, so we can end up with nodes with now titles.   Which creates query errors.
![image](https://user-images.githubusercontent.com/5752113/146840819-4b7b3717-a6a9-423b-a6de-3bdbdda40d47.png)

Visit  https://prod.cms.va.gov/admin/content?title=&type=All&moderation_state=All&owner=All&order=title&sort=asc   See the items at the tip of the list with no titles.

## Acceptance Criteria
- [ ] It should not be possible to create a staff profile (person_profile) with an empty title (names  should be required.)
  - [ ] make field_name_first required 
  - [ ] make field_last_name required
  - [ ] Update spectool and related tests to reflect these fields are required.
- [ ] Existing profiles with no titles either have their title restored, or are deleted so they to not create sql time bombs.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Platform CMS Team`
- [x] `Sitewide CMS Team`
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Offices`
  - [x] `⭐️ Product support`
  - [ ] `⭐️ User support`

**Comment by swirtSJW** [comment]
@msbtterswrth this got closed by merging the PR but does this AC still need to be done?


- [ ] Existing profiles with no titles either have their title restored, or are deleted so they to not create sql time bombs.

**Comment by msbtterswrth** [comment]
Oh darn, I thought i created a new ticket for that as a followup. Let me do that now.
