### ISSUE TITLE
Facility change: Crossroads

### ISSUE THREAD

**Issue by chriscraiga6** [department-of-veterans-affairs/va.gov-cms#7359]
## Intake: Editor submission to Helpdesk
- [ ] Submitter: Heather Frebe
- Change type (select one)
  - [ ] VAMC new facility
  - [x] VAMC facility closure
  - [ ] VAMC facility name
  - [ ] VAMC system name
  - [ ] Vet Center new facility
  - [ ] Vet Center facility closure
  - [ ] Vet Center facility name
- [ ] If the submitter is an editor, send them the link to the CMS Knowledge Base (KB) article on facility basic data for their product (VAMC or Vet Center). Let them know that facility changes can take between 75 days and 4 months after submitting a request, according to VAST administrators.
- [ ] If the change is a facility closure, send the editor a link to the operating status KB article and have them change the status to Facility notice and provide a description of the facility closure so that Veterans are aware of the future closure.
- [ ] Other stakeholders to include on updates, if any: <insert name>
 
## Acceptance criteria (delete all instructions except the set that applies to the change requested)
  
 
<details><summary>VAMCs - facility closure</summary>
  
- [ ] CMS team becomes aware that the facility is no longer on the Facility API.
- [ ] CMS engineer bulk archives the facility service nodes. (https://prod.cms.va.gov/admin/content/bulk?type=health_care_local_health_service)
- [ ] CMS engineer edits the facility node, add a revision log to cover who requested the change and change moderation state to archive.
- [ ] CMS engineer finds the menu for the system https://prod.cms.va.gov/admin/structure/menu and deletes the menu item for the closed facility.
- [ ] CMS engineer filters content by the health care system and scans for any events that might be taking place at that facility. Archive if any are found.
- [ ] CMS engineer removes the Section.
- [ ] HD notifies editor and any other stakeholders.
</details>

 
 

CMS Team
Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.
- [x] Platform CMS Team
- [X] Sitewide CMS Team

**Comment by chriscraiga6** [comment]
I'm not finding Crossroads listed in the VA Facility Locator. Here is the screenshot the editor submitted verifying the VAST Deactivation:

![image](https://user-images.githubusercontent.com/90711023/146966859-1bc896cd-61ab-4071-90e4-ead0515765c3.png)

This is for: 
https://www.va.gov/orlando-health-care/locations/crossroads-va-clinic/

**Comment by swirtSJW** [comment]
I just archived the facility in the CMS and all of its facility health services
![image](https://user-images.githubusercontent.com/5752113/146973926-a5b86897-3eba-4a0b-996e-861b6b1e1a0f.png)
