### ISSUE TITLE
Content release: releases cancelled due to existing release requests should not report as failures.

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#7363]
## Describe the defect
When a content release is requested, and a 'higher priority' release is already queued or in progress, the requested content release is cancelled and reported as a failure.

It should not report as a failure. A message would be fine, but it should not alert the channel nor say it is a failure.

## Acceptance Criteria

- [x] no notification when content release is canceled

## Examples
Example "failed" job: https://github.com/department-of-veterans-affairs/content-build/actions/runs/1603506347

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Defect")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [ ] CMS workstream (orange) (not needed for bug tickets)
- [ ] CMS-supported product (black)

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [x] `Platform CMS Team`
- [ ] `Sitewide CMS Team`

**Comment by cweagans** [comment]
I _think_ this is just removing `| cancelled()` from https://github.com/department-of-veterans-affairs/content-build/blob/a658ec8c84eeadc17de4f8e68f1341dfbca5d0b9/.github/workflows/content-release.yml#L598

**Comment by cweagans** [comment]
PR is open for this: https://github.com/department-of-veterans-affairs/content-build/pull/884

**Comment by cweagans** [comment]
PR merged
