### ISSUE TITLE
Vet Center service description doesn't save edit when clicking Save draft and continue editing

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#7373]
## Describe the defect
When an editor edits an existing service description in a Vet Center node and clicks Save draft and continue editing, their edit isn't saved when they go back to that service description.

## To Reproduce
1. Go to https://staging.cms.va.gov/
2. Log in as wesley.landry@va.gov or any Vet Center editor.
3. Click Go to services.
4. Click Edit next to Community engagement or any existing service.
5. Make an edit in the Vet Center service description field.
6. Click Update service.
7. Scroll down to Editorial workflow and enter a Revision log message.
8. Click Save draft and continue editing.
9. Scroll down to Services and find Community engagement or whatever service you edited.
10. Click Edit next to that service.
11. Edit wasn't saved in Vet Center service description field.

## Screenshots 
Edit made: ![Screen Shot 2021-12-22 at 10.55.06 AM.png](https://images.zenhubusercontent.com/5fa07f8cd87c6fff07bee6de/a8640e37-0af8-405a-8af8-56c7f0d49935)
updated service, added revision log message, and clicked save draft and continue editing

Edit gone:
![Screen Shot 2021-12-22 at 10.55.53 AM.png](https://images.zenhubusercontent.com/5fa07f8cd87c6fff07bee6de/39941e0c-a881-4a6d-b882-ed724cbb7476)

 ## Additional context
Add any other context about the problem here. Reach out to the Product Managers to determine if it should be escalated as critical (prevents users from accomplishing their work with no known workaround and needs to be addressed within 2 business days).

 
## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Defect")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS workstream (orange) (not needed for bug tickets)
- [ ] CMS-supported product (black)

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Platform CMS Team`
- [x] `Sitewide CMS Team`

**Comment by xiongjaneg** [comment]
Recommended workaround for the editor affected today, after making the edit, click Save. Then click Edit to open the node again and make the next edit.

**Comment by kevwalsh** [comment]
Looks like this should have been closed when #7374 got merged.
