### ISSUE TITLE
Composer Version 2.2.0 Introduces a Breaking Change

### ISSUE THREAD

**Issue by olivereri** [department-of-veterans-affairs/va.gov-cms#7376]
## Describe the defect
BRD and CI Builds are failing after an update to Composer. Spcifically:

## Expected behavior
Composer packages should install without error and failing BRD and CI builds.

## Screenshots 
```
or additional security you should declare the allow-plugins config with a list of packages names that are allowed to run code. See https://getcomposer.org/allow-plugins
You have until July 2022 to add the setting. Composer will then switch the default behavior to disallow all plugins.

Fatal error: Uncaught Error: Class 'Dotenv\Dotenv' not found in /var/lib/tugboat/scripts/composer/EnvironmentHandler.php:46
Stack trace:
#0 /var/lib/tugboat/scripts/composer/EnvironmentHandler.php(8): VA\Composer\EnvironmentHandler::load()
#1 phar:///usr/local/bin/composer/src/Composer/Autoload/AutoloadGenerator.php(1422): require('/var/lib/tugboa...')
#2 phar:///usr/local/bin/composer/src/Composer/Plugin/PluginManager.php(249): Composer\Autoload\composerRequire('838cc0e9c4c0169...', 'scripts/compose...')
#3 phar:///usr/local/bin/composer/src/Composer/Plugin/PluginManager.php(474): Composer\Plugin\PluginManager->registerPackage(Object(Composer\Package\CompletePackage), false, false)
#4 phar:///usr/local/bin/composer/src/Composer/Plugin/PluginManager.php(102): Composer\Plugin\PluginManager->loadRepository(Object(Composer\Repository\InstalledFilesystemRepository), false)
#5 phar:///usr/local/bin/composer/src/Composer/Factory.php(439): Composer\Plugin\PluginManager->loadInstalledPlugins()
#6 phar:///usr/local/bin/composer/sr in /var/lib/tugboat/scripts/composer/EnvironmentHandler.php on line 46
2021-12-22T18:01:04.071Z - Command Failed (Tugboat Error 1064): Exit code (255)
```

 ## Additional context

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Defect")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS workstream (orange) (not needed for bug tickets)
- [ ] CMS-supported product (black)

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [x] `Platform CMS Team`
- [] `Sitewide CMS Team`

**Comment by indytechcook** [comment]
> When composer update to version 2.2 there were several issues.  See https://github.com/department-of-veterans-affairs/va.gov-cms/issues/7376.  There are also other issues related to version 2.2 in the composer issue queue: https://github.com/composer/composer/issues.

With this information, we pinned version 2.1 to our build scripts and will revisit 2.2 as part of https://github.com/department-of-veterans-affairs/va.gov-cms/issues/7377
