### ISSUE TITLE
Upgrade Composer to 2.2

### ISSUE THREAD

**Issue by indytechcook** [department-of-veterans-affairs/va.gov-cms#7377]
## Description

When composer update to version 2.2 there were several issues.  See https://github.com/department-of-veterans-affairs/va.gov-cms/issues/7376.  There are also other issues related to version 2.2 in the composer issue queue: https://github.com/composer/composer/issues.

With this information, we pinned version 2.1 to our build scripts and will revisit 2.2 later as part of this issue.

## Acceptance Criteria

- [ ] update Composer 2.2.0 to 2.2.1

**Comment by cweagans** [comment]
Related PRs:
* https://github.com/department-of-veterans-affairs/devops/pull/10478
* https://github.com/department-of-veterans-affairs/devops/pull/10479

**Comment by cweagans** [comment]
New settings introduced in 2.2: https://getcomposer.org/doc/06-config.md#allow-plugins

**Comment by cweagans** [comment]
Somebody mentioned having issues with this in the composer-patches issue queue. It's possible that upgrading to 2.2.1 doesn't completely fix this problem. I haven't dug into it more but the issue is here in case it has any useful context: https://github.com/cweagans/composer-patches/issues/387

**Comment by ndouglas** [comment]
There may be complications with Composer 2.2.0 that go a bit deeper and complicate other parts of our flow, see e.g. [this issue](https://github.com/cweagans/composer-patches/issues/387).
