### ISSUE TITLE
help editors understand "Access denied" message when clicking on an admin-only link

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#7381]
## User story
As an editor, I need to know what to do when I click on a link that I don't have access to because of my role.

Scenario: Editor searches for a node that they need to edit. Instead of clicking on the Edit button next to the node in the content search results, they click on the link under Content type. They get an "Access denied" page with the message "You are not authorized to access this page." The editor is confused by this message because they think the message means they don't have access to the node, even though it's in their Section.

To replicate:

1. Go to [staging](https://staging.cms.va.gov/).
2. Log in as kathleen.hider@va.gov or another editor.
3. Under Sections on the home page, click to expand the Sections list.
4. Click on the link to the section VA New York Harbor health care.
5. In the content list, find Visitation Update Due to Omicron or any node.
6. Look under the Content type column and click on that link, such as VAMC System Banner Alert with Situation Updates.
7. View the Access denied message and be confused.
![Screen Shot 2021-12-22 at 3.13.15 PM.png](https://images.zenhubusercontent.com/5fa07f8cd87c6fff07bee6de/a9983429-2377-41a3-9020-75270802dabe)
![Screen Shot 2021-12-22 at 2.57.38 PM.png](https://images.zenhubusercontent.com/5fa07f8cd87c6fff07bee6de/ff161c92-743e-4589-98c9-4ef96b62781f)

## Acceptance Criteria
- [ ] Testable_Outcome_X
- [ ] Testable_Outcome_Y
- [ ] Testable_Outcome_Z
- [ ] Requires design review

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Platform CMS Team`
- [x] `Sitewide CMS Team`
  - [ ] `⭐️ Content ops`
  - [x] `⭐️ CMS experience`
  - [ ] `⭐️ Offices`
  - [ ] `⭐️ Product support`
  - [ ] `⭐️ User support`

**Comment by xiongjaneg** [comment]
See [Slack thread ](https://dsva.slack.com/archives/CT4GZBM8F/p1640198479038900)related to the example.

**Comment by kevwalsh** [comment]
We shouldn't be surfacing links that lead to access denied. This is a defect that we'll resolve in #8329
