### ISSUE TITLE
Dropbuttons in vagovclaro don't always function correctly

### ISSUE THREAD

**Issue by tjheffner** [department-of-veterans-affairs/va.gov-cms#7408]
## Description
Dropbuttons, button that can be clicked or open a menu with further actions, seems to function intermittently on different pages/refreshes. Sometimes the dropdown list closes immediately and automatically. Sometimes it doesn't register clicks on either part of the button. The taxonomy categories & term list pages are places I notice issues consistently.

This drupal issue (opened by @cweagans!) says we may not be getting all of claro's libraries even though we are a sub-theme. Comment #15 has more context.: https://www.drupal.org/project/claro/issues/3085894

## Acceptance Criteria
- [ ] VAgov Claro extends the claro libraries as appropriate.
- [ ] Dropbuttons function correctly on all pages they are found.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [] `Platform CMS Team`
- [x] `Sitewide CMS Team`

**Comment by kevwalsh** [comment]
@tjheffner did #7417 resolve this? If not, do we need to add this to Sprint 49 or is this a backlog thing now?

**Comment by tjheffner** [comment]
7417 did resolve this, though the CSS i added as part of it may have caused regressions elsewhere... probably worth a short backlog task to take that out/clean up appropriately.
