### ISSUE TITLE
Prep D7/Claro analysis tool for mob session

### ISSUE THREAD

**Issue by rachel-kauff** [department-of-veterans-affairs/va.gov-cms#7414]
## Background
Before we launch the Claro implementation, we need to make sure there aren't any outstanding bugs or usability regressions. In preparation for our mob session in January, we need a tool/framework that helps us efficiently evaluate the state of Claro and document any necessary changes. 

This tool is probably an airtable

**Artifacts:**
[2020 Claro evaluation AT](https://airtable.com/appp2jWVUdUHd1IRg/tbltqUzIxw0CawQpA/viwj7R8pHlvcESpkU?blocks=hide)

### Ideas:

**Severity**
- Four-point emoji scale: 😡 🙁 😐 😍
- 😡  so bad it's making me mad
- 😕  could be better (may or may not belong in MVP)
- 😐  Neutral impact "meh"- not better than d7, but not worse
- 😍 "hey that's better"

### Criteria and heuristics

**For accessibility:**
- Meets color contrast guidelines 
- Tags in place 
- Headers / semantic markup 

**For Interaction / usability**
- User control and freedom
- Visibility of system status
- Consistency and standards
- Error prevention
- Recognition rather than recall
- Flexibility and efficiency of use

For visual & aesthetic consistency:
- Aesthetic and minimalist design

### Feasibility
- level of effort
- blockers

### Priority & timeline
- Priority scale: 1234
- Sprint assigned before launch

Other data to gather:
- Recommendation
- Decision: in scope for Claro launch
- Source of problem: Claro theme or something else 

AC
- [x] A framework is set up and ready to use for the Claro mob session
- [x] Reviewed by the CMS experience team

**Comment by rachel-kauff** [comment]
@EWashb @cjterdi I drafted a lil' airtable based on our chat. Check it outtt: https://airtable.com/applHskzNEaJ4qM7R/tblvm17AmjxYtpwWQ/viw51xsCmfmSgXlOj?blocks=hide

I added an example in there to test it out.

**Comment by kevwalsh** [comment]
I think we can call this closed! I'm sure we'll continue to iterate.
