### ISSUE TITLE
Service locations render in confusing ways when no name is provided.

### ISSUE THREAD

**Issue by ryguyk** [department-of-veterans-affairs/va.gov-cms#7416]
## Description
Service locations (for both health services and non-clinical services) render in interesting ways when no name is provided, particularly when multiple service locations exist at a single facility.

Here is an example from production (as it stands currently) with multiple service locations at a single facility:
![image](https://user-images.githubusercontent.com/6863534/147582584-7ab56322-7663-450b-b2dd-52ca3d8cf9ce.png)

And, with annotations:
![image](https://user-images.githubusercontent.com/6863534/147594478-21d651c0-f599-47f1-84d1-0fe342d1153d.png)

Here is the same data as it will appear with the new logic for displaying service location address (or, in this case, _not_ displaying service location address when "use facility address" box is checked. see #7339):
![image](https://user-images.githubusercontent.com/6863534/147595220-1ad70197-bd3e-410c-8242-81b0809162b1.png)

## Acceptance Criteria
On the front end, there should likely be some default header in the case when no name is provided for a service location.  This would have two major outcomes:
1. Would provide visual separation for a service location (so information like hours don't appear to be a continuation of a previous location).
2. Would dictate that all headers (e.g. "Hours") are the same header level (i.e. h5) for all locations.

[It was first discussed whether this name field should be required in the CMS](https://dsva.slack.com/archives/CT4GZBM8F/p1640631116105000), but this feels less than desirable in the scenario where there is only one service location at a given facility, and this scenario seems like it's the rule more than the exception.  This led to the idea that [a FE default might be a good solution, at least temporarily](https://dsva.slack.com/archives/CT4GZBM8F/p1640632587107500?thread_ts=1640631116.105000&cid=CT4GZBM8F).  It would be temporary if it is decided that the best solution is some extended CMS logic that would potentially require names for service locations if, for example, multiple locations exist. It would otherwise be permanent.

https://dsva.slack.com/archives/CT4GZBM8F/p1640632587107500?thread_ts=1640631116.105000&cid=CT4GZBM8F

**Comment by mmiddaugh** [comment]
Related: [Design for Facility health service #34635](https://github.com/department-of-veterans-affairs/va.gov-team/issues/34635)

**Comment by xiongjaneg** [comment]
@davidmpickett To review for current state and what elements of this no longer apply

**Comment by davidmpickett** [comment]
All situations referenced in this ticket have newer more specific tickets addressing them
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17414
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17380
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17488
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17490
