### ISSUE TITLE
Adjustments n' tweaks to Homepage implementation

### ISSUE THREAD

**Issue by rachel-kauff** [department-of-veterans-affairs/va.gov-cms#7422]
Ticket to capture ongoing tweaks to the homepage implementation. Can be rolled into future sprints as needed.

ACs
- [ ] 1. Login page: Position of pencil graphic
- [ ] 2. Login page: Log in button label

**Comment by rachel-kauff** [comment]
1. Login page: Position of pencil graphic

![Uploading Screen Shot 2021-12-29 at 9.20.03 AM.png…]()

**Comment by rachel-kauff** [comment]
2. Login page: Log in button label
<img width="551" alt="Screen Shot 2021-12-29 at 10 02 08 AM" src="https://user-images.githubusercontent.com/41017988/147690864-27841638-5453-4dab-8525-35638dfa1249.png">

**Comment by kevwalsh** [comment]
I'm making this specific to the login/homepage and dropping it in #1269 . Until we have our mob session, i was thinking it might be easier to keep tack track of minor adjustments to Claro stuff in the Airtable. We can generate tickets from there, hopefully in clusters that make Tanner's life easier.

**Comment by rachel-kauff** [comment]
Got it. I moved those two items over to the AT.
