### ISSUE TITLE
Add GraphiQL 'Explorer' button to VA GraphiQL UI

### ISSUE THREAD

**Issue by GcioNapoleon** [department-of-veterans-affairs/va.gov-cms#7428]
## Description

Public GraphiQL UI tools like Spacex and Github have an explore button. I noticed that the "explorer" button is missing from our VA websites. Can we please expose the "Explorer" button on the VA website because it has the potential to increate developer efficiency.

https://api.spacex.land/graphql/

![Screen Shot 2021-12-30 at 2 41 28 PM](https://user-images.githubusercontent.com/95312667/147786776-dea21d4f-c12e-4b8d-8172-e3ff2d317d10.png)

https://docs.github.com/en/graphql/overview/explorer

![Screen Shot 2021-12-30 at 2 48 30 PM](https://user-images.githubusercontent.com/95312667/147787068-5795e206-fe92-40e5-beb8-85bdfc13506a.png)

## Acceptance Criteria
- [ ] add interactive explorer plug-in so that GraphQL 'Explorer' button appears on the console

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [x] `Platform CMS Team`
- [ ] `Sitewide CMS Team`

**Comment by swirtSJW** [comment]
This is tied to the versioning of GraphQL
![image](https://user-images.githubusercontent.com/5752113/147961861-e306f5d4-bb95-4a01-8263-3fef2f78878b.png)

This is a lift that we may or may not want to take on.  Schemas have to be written and I believe FE queries would have to be altered.   It may be worth it but it depends if it pulls away from Accelerated Publishing.

**Comment by indytechcook** [comment]
It appears this functionality is added via https://github.com/onegraph/graphiql-explorer.

**Comment by indytechcook** [comment]
An example implementation: https://github.com/OneGraph/graphiql-explorer-example

**Comment by indytechcook** [comment]
PR https://github.com/department-of-veterans-affairs/va.gov-cms/pull/7758

**Comment by indytechcook** [comment]
Code has been merged and this should be in production today.

**Comment by mchelen-gov** [comment]
we should have made an AC for documentation, let's create a followup issue to create VFS facing docs for this
