### ISSUE TITLE
Draft Q1 OKRs (CMS experience)

### ISSUE THREAD

**Issue by cmaeng** [department-of-veterans-affairs/va.gov-cms#7444]
Based on the projected Q1 roadmap identified in [this mural](https://app.mural.co/t/vagov6717/m/vagov6717/1639112242953/d40312d55d9b59488ae2d7c12c2cc56cf998a867?sender=clarencemaeng1702), what is at least one OKR that we can articulate that is measurable and timeboxed for this quarter? Looking to capture that under its respective objective in [this doc](https://docs.google.com/spreadsheets/d/1NEX4_NwurY6qLLIoeFkGTQ0jYIduG67ncMR3JtsPCGI/edit#gid=406704804).

**Comment by rachel-kauff** [comment]
Objective: The CMS interface has design patterns, features, and branding that creates a cohesive editorial experience that inspires editors.

KRs:
1. Claro is launched and 90% of users report a neutral or positive change to their experience.
2. Tokens and a handful of foundational pieces of design system are defined in Figma. 
3. We have improved in-application components that help inform users of important changes. E.g. announcement alert, site alert improvements, maybe tour.

**Comment by rachel-kauff** [comment]
Added OKRs to the spreadsheet
