### ISSUE TITLE
Draft Q1 OKRs (Offices)

### ISSUE THREAD

**Issue by cmaeng** [department-of-veterans-affairs/va.gov-cms#7446]
Based on the projected Q1 roadmap identified in [this mural](https://app.mural.co/t/vagov6717/m/vagov6717/1639112242953/d40312d55d9b59488ae2d7c12c2cc56cf998a867?sender=clarencemaeng1702), what is at least one OKR that we can articulate that is measurable and timeboxed for this quarter? Looking to capture that under its respective objective in [this doc](https://docs.google.com/spreadsheets/d/1NEX4_NwurY6qLLIoeFkGTQ0jYIduG67ncMR3JtsPCGI/edit#gid=406704804).

**Comment by wesrowe** [comment]
@cmaeng – I'm not nearly as clear about this OKR task as I was about the q1 mission statement & epics task. Can you provide a hint about the deliverable we're shooting for?

**Comment by cmaeng** [comment]
@wesrowe yup, it would probably help to put that in the description of the ticket but, want to walk through with y'all the projected roadmap for Q1 and come up with at least one tangible OKR that we can measure progress against. that OKR ideally would tie to one of the epics we've parsed out.

**Comment by cmaeng** [comment]
draft proposed: "Plot a course for the next set of content to move to [VA.gov](http://va.gov/) in conjunction with OCTO-DE and relevant stakeholders."
