### ISSUE TITLE
Spike:  Evaluate salesforce related contrib modules

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#7472]
## Description

Evaluation should be related to 
* authenticating access to salesforce api.
* pulling/syncing data from Salesforce

https://www.drupal.org/project/salesforce

## Acceptance Criteria
- [ ] Determining whether this gives a clear advantage(s) over using core migrate 
    - [ ] pros documented in this issue.
    - [ ] cons/risks documented in this issue
- [ ] Decision

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Platform CMS Team`
- [x] `Sitewide CMS Team`

**Comment by wesrowe** [comment]
closing due to architecture change
