### ISSUE TITLE
Monthly User Management report

### ISSUE THREAD

**Issue by cmaeng** [department-of-veterans-affairs/va.gov-cms#7485]
## Description
The new CEDAR contract has a requirement for new metrics to be tracked on a monthly basis. The language states:

User Management Report: The Contractor shall provide a monthly report, highlighting data on CMS user onboarding, offboarding, training, and providing detailed helpdesk support data. The specific data points and format of this monthly report shall be determined by the Contractor in collaboration with the Government Product Owner and COR.

The monthly report is due on the 5th of each following month.

## Acceptance Criteria
- [x] New report is drafted
- [x] Approved internally by Clarence
- [x] Approved by Dave Conlon and Mike Chelen

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Platform CMS Team`
- [x] `Sitewide CMS Team`

**Comment by stefaniefgray** [comment]
User management report has been churned out each month since this ticket was created back in January; have not heard any complaints or suggestions

Closing
