### ISSUE TITLE
Split Sitewide CMS assignment check and auto-labeling

### ISSUE THREAD

**Issue by cmaeng** [department-of-veterans-affairs/va.gov-cms#7486]
## Description
Currently our GitHub issue templates have two teams listed that will auto-label. Looking to split out "Sitewide CMS Team" into:
- Content Ops 
![image](https://user-images.githubusercontent.com/60702623/148268902-7b0abb9d-8b47-4a77-b442-acdca679742e.png)
- CMS Experience 
![image](https://user-images.githubusercontent.com/60702623/148268872-096e53b0-4d7b-4fd5-bc49-834425c3bf72.png)
- Offices 
![image](https://user-images.githubusercontent.com/60702623/148269010-1ccac52d-c64d-4e3d-8372-2b663279fa1f.png)
- Product Support 
![image](https://user-images.githubusercontent.com/60702623/148268962-243050e7-df57-42c9-8505-9e14483d09c9.png)
that will also auto-label if checked.

## Acceptance Criteria
- [x] Every relevant CMS GitHub issue template has the above teams sub-listed under "Sitewide CMS Team"
- [x] Every relevant new issue created still defaults with both "Platform CMS" and "Sitewide CMS" teams checked by default
- [x] Every relevant new issue created has the above teams sub-listed under "Sitewide CMS Team" defaulted unchecked

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [x] `Platform CMS Team`
- [x] `Sitewide CMS Team`

**Comment by msbtterswrth** [comment]
Updated and tested in issue #7501
