### ISSUE TITLE
KB bug: breadcrumbs on search link to an old version of /help

### ISSUE THREAD

**Issue by rachel-kauff** [department-of-veterans-affairs/va.gov-cms#7497]
[Related discussion](https://dsva.slack.com/archives/CDKB88PS8/p1641425714149500?thread_ts=1641424697.148000&cid=CDKB88PS8)

Some strange things happening when using breadcrumbs on the search page. See screenshot for steps to reproduce.![Screen Shot 2022-01-05 at 3.29.09 PM.png](https://images.zenhubusercontent.com/5e399cf5446c5b4ca0e31e42/0cdd3ee5-72af-4852-a06b-d24ba08dee1f)

**Comment by rachel-kauff** [comment]
From Tanner: "[link to an archived version of /help] shows up in the breadcrumbs on the search page, which is rendered by a view. i wonder if drupal is doing something under the hood / there's config in the view for that specific node."

**Comment by kevwalsh** [comment]
Fixed, just a menu item out of place. @rachel-kauff please see if we can just delete https://prod.cms.va.gov/help-old so this doesn't happen again
