### ISSUE TITLE
Discovery: Inventory current web presence of Level 2 & 3 Offices in FOM (i.e., top offices and one level down from them)

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#7510]
## Acceptance Criteria

- [ ] 

### CMS Team

Please leave only the team that will do this work selected. 

- [ ] `Platform CMS Team`
- [x] `Sitewide CMS Team`
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS Experience`
  - [x] `⭐️ Offices`
  - [ ] `⭐️ Product Support`

**Comment by jilladams** [comment]
Offices to be deprecated: #14404
