### ISSUE TITLE
Media updates

### ISSUE THREAD

**Issue by tjheffner** [department-of-veterans-affairs/va.gov-cms#7522]
## Description
Mob session airtable raised several issues with media

- errors when uploading video?
- no media preview for docs or pdfs (add icons)
- better cropping indication
- hover state investigation...

## Acceptance Criteria
- [ ] Testable_Outcome_X
- [ ] Testable_Outcome_Y
- [ ] Testable_Outcome_Z
- [ ] Requires design review

### CMS Team

Please leave only the team that will do this work selected. 

- [] `Platform CMS Team`
- [x] `Sitewide CMS Team`
  - [ ] `⭐️ Content ops`
  - [x] `⭐️ CMS Experience`
  - [ ] `⭐️ Offices`
  - [ ] `⭐️ Product Support`

**Comment by rachel-kauff** [comment]
@tjheffner Here's something to try for now. Let me know if you have issues.
![generic-document-icon](https://user-images.githubusercontent.com/41017988/156635228-cf76baf5-5d85-474f-9c97-4630cafab084.svg)

**Comment by EWashb** [comment]
This will be addressed as part of a larger initiative on media, specifically #2415
