### ISSUE TITLE
Remove UI help text that says create a new alert in VAMC detail page

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#7540]
## User story
As a VAMC editor, I should not be told I can create a new alert in VAMC detail page if I really can't do it. 

To replicate:

1. Login to https://staging.cms.va.gov/ as ryan.stubblebine@va.gov
2. Click Manage, hover over Content, hover over Add content, and click VAMC Detail page
3. Scroll down to Include alert
4. In the help text, click the link "create a new alert"
5. Get the "Access denied" page
<img width="666" alt="Screen Shot 2022-01-10 at 1 01 29 PM" src="https://user-images.githubusercontent.com/73648238/148829164-3c0d31c3-5cd7-4c19-95b3-679f6b14e314.png">

## Acceptance Criteria

- [ ] Remove this sentence from the help text in the "Include alert" fieldgroup: "You can [create a new alert](https://prod.cms.va.gov/block/add/alert?destination=/admin/content/alerts), or reuse an existing one."

<details><summary>Screenshot</summary>

<img width="1110" alt="Create_VAMC_Detail_Page___VA_gov_CMS" src="https://user-images.githubusercontent.com/643678/152377735-9189b780-04a3-470b-b0ef-4254bd782f27.png">

</details>

### CMS Team

Please leave only the team that will do this work selected. 

- [ ] `Platform CMS Team`
- [x] `Sitewide CMS Team`
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Offices`
  - [x] `⭐️ Product support`
  - [ ] `⭐️ User support`

**Comment by netboss** [comment]
@swirtSJW 
Started working on this and so far I'm not sure how to accomplish it. This seems to be a role/permissions issue where editors can see the Include alert area which have the add alert link.

Any ideas where to start? I'm looking at the va_gov_vamc custom module, is this the correct place?

**Comment by swirtSJW** [comment]
@xiongjaneg @kevwalsh I am unsure of the desired outcome of this issue.
The title seems like  it is just the help text that needs removing, but I want to make sure before @netboss  removes the help text that we are not masking the problem.   Should an editor like RS be able to create an alert block?

**Comment by netboss** [comment]
@kevwalsh 

> Remove this sentence from the help text in the "Include alert" fieldgroup: "You can [create a new alert](https://prod.cms.va.gov/block/add/alert?destination=/admin/content/alerts), or reuse an existing one."

Do we want to remove this text for all roles or just for the editor role? If it's for all roles it's an easy removal from the field form display settings. If it's just for the editor role then this will need some logic (either back-end or front-end).

**Comment by swirtSJW** [comment]
@netboss the appearance of  the help text should not be dependent on who the user is.  

The question Jane and I raise is whether an editor ought to be able to create an alert or not.  If the answer is:
**NO the editor should not be able to create an alert**, then we need to remove the link from the help text as described in the issue description.
**YES editors should be able to create alerts**, then we need to alter perms to allow that and leave the help text as it is. and alter the  issue to say that.

**Comment by netboss** [comment]
@swirtSJW 
Got it. For now I went with the assumption that editors shouldn't be able to create an alert. If the editors actually need to be able to create alerts then I'll revert and adjust permissions (or whatever needs to be done).
