### ISSUE TITLE
compile Drupal theme styles as part of the overall build process

### ISSUE THREAD

**Issue by tjheffner** [department-of-veterans-affairs/va.gov-cms#7552]
## Description
Right now, our drupal themes (vagovadmin, vagovclaro) commit the compiled .css files directly to the repo. This has the unfortunate side effect of PR churn. Any time multiple PRs are open that change styles, merging one causes conflicts in all the rest, as the styles need to be merged in and recompiled, even if they are changing different parts of the stylesheet.

A better DX would be to still reference them as the libraries to be attached, but .gitignore the compiled stylesheets and have them built & compile as part of the overall build(/deploy?) process. Theme dependencies would also need to be installed as part of this update. Currently, the build ignores theme dependencies entirely (as the compiled files are committed, the build has no need to install these dependencies).

Updating this system would cut down on future PR conflicts, improve review cycles and ease developer friction for theme-related fixes.

## Acceptance Criteria
- [ ] Testable_Outcome_X
- [ ] Testable_Outcome_Y
- [ ] Testable_Outcome_Z
- [ ] Requires design review

### CMS Team

Please leave only the team that will do this work selected. 

- [x] `Platform CMS Team`
- [x] `Sitewide CMS Team`
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Offices`
  - [ ] `⭐️ Product support`
  - [ ] `⭐️ User support`

**Comment by ElijahLynn** [comment]
We might want to consider using a `task` file that we execute during the build process, then devs can update that file easily.
