### ISSUE TITLE
Disable Drupal api current user - communication plan

### ISSUE THREAD

**Issue by olivereri** [department-of-veterans-affairs/va.gov-cms#7562]
### Problem Statement

Drupal user **api** should be disabled per security disclosures linked in related issue #6973. The rollout plan is to communicate to impacted teams 1 month in advance to ensure teams are prepared for change and address any concerns that may arise. 

Target date to disable Drupal api current user: March 1, 2022 (https://github.com/department-of-veterans-affairs/va.gov-cms/issues/7870)

### Acceptance Criteria

- [x] Communicate 1 month in advance to downstream teams before user is disabled:
  - [x] ~~Content Build (Release Tools)~~ _CMS Platform team is handling this_
  - [x] Virtual Agent (chatbot) 
  - [x] Forms API
  - [x] ~~Facilities API~~
- [x] Reminder communication to dependent teams:
  - [x] Content Build (Release Tools)
  - [x] Virtual Agent (chatbot)
  - [x] Forms API
  - [ ] ~~Facilities API~~

### CMS Team

- [x] `Platform CMS Team`

**Comment by mchelen-gov** [comment]
This process should be:
- Set a date when the legacy credentials will be deprecated
- Announce this date to our API users
- Remind them 1 week in advance
- Disable the user on selected date

**Comment by olivereri** [comment]
VA-Forms request communication goes to:
Nichole Harris 
Kevin Cranmer

**Comment by olivereri** [comment]
Forms API Thread:
https://dsva.slack.com/archives/CUB5X5MGF/p1641849569028000

Facilities API Thread:
https://dsva.slack.com/archives/C0FQSS30V/p1641849367042900

Virtual Public Agent Thread:
https://dsva.slack.com/archives/C01KTS3F493/p1641841828002000

Content-build thread:
https://dsva.slack.com/archives/CQH357ZTP/p1641586527011200

**Comment by olivereri** [comment]
- [ ] Downstream and other dependencies notified in #vfs-all-teams 
- [ ] Directly notify virtual-agent team
- [ ] Directly notify VA-forms team
- [ ] Directly notify VA-facilities team

**Comment by olivereri** [comment]
vsa-facilities does not directly pull from Drupal.
