### ISSUE TITLE
Improve editor experience for non-clinical services

### ISSUE THREAD

**Issue by JayDarnell** [department-of-veterans-affairs/va.gov-cms#7595]
## User Story or Problem Statement

- **Group non-clinical service location cards by Facility**
- map user flow to identify UX pain points re: Facility vs location
- Update "Add new location" link language to indicate that this is used to add new non-clinical service location cards for a facility not already displayed. (help avoid the existing content error message if an editor tries to add a service/facility combo already in use)
- Update alert language for when does not yet exist. 
- Update "Edit this location" link language to be per Facility (one edit link per Facility, not per card)
- Be sure the new non-clinical view is displayed properly on node view (we updated it on node edit in #6880)

## Acceptance Criteria
- [x] UX writing is clear about what actions you're about to take
- [x] design review
- [x] pass to engineering

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [x] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes, and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [x] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [x] `Consistent`: Reduce users’ mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected.
- [ ] `Platform CMS Team`
- [x] `Sitewide CMS Team`
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Offices`
  - [x] `⭐️ Product support`
  - [ ] `⭐️ User support`

**Comment by suzanne-gray** [comment]
Passed this to Jay for implementation in #7702
