### ISSUE TITLE
Permit Platform CMS to manage parts of content-build repo

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#7601]
## Description
Platform CMS is responsible for the content release process, and should be able to merge changes to that process. Platform CMS should also have the ability to review and manage code changes to some parts of the content-build repo.

## Acceptance Criteria
- [x] Platform CMS is listed as code owner or co-owner for agreed-upon sections of the content-build repo.

### CMS Team

Please leave only the team that will do this work selected. 

- [x] `Platform CMS Team`
- [ ] `Sitewide CMS Team`
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Offices`
  - [ ] `⭐️ Product support`
  - [ ] `⭐️ User support`

**Comment by timcosgrove** [comment]
@cweagans has already submitted a PR for this: https://github.com/department-of-veterans-affairs/content-build/pull/909

**Comment by mchelen-gov** [comment]
> Platform CMS is responsible for the content release process
This wording is a little ambiguous. Release Tools Team is responsible for CI/CD of `content-build` repo, with Platform CMS supporting.
