### ISSUE TITLE
Create field_va_health_connect_phone but keep it hidden

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#7619]
See #7618 for background. 
## ACs

- [x] VAMC system content type has a new field
  - [x] `field_va_health_connect_phone`  "VA health connect phone number" 
  - [x] Phone number field type
  - [x] Single value
- [x] Form settings
  - [x] Phone number formatter (settings TBD?)
  - [x] Form placement HIDDEN
  - [x] Help text: "To request changes, [contact CMS help desk](http://linktohelpdesk).
```
To request changes, <a href="mailto:support@va-gov.atlassian.net?subject=Inaccurate map thumbnail&amp;body=My VA health connect phone number is incorrect.">Email the CMS Support Team</a>
```
- [x] Node view: hidden.

### CMS Team

Please leave only the team that will do this work selected. 

- [ ] `Platform CMS Team`
- [ ] `Sitewide CMS Team`
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Offices`
  - [x] `⭐️ Product support`
  - [ ] `⭐️ User support`

**Comment by swirtSJW** [comment]
I changed the criteria for the field name from `field_va_health_connect_phone` to `field_health_connect_phone` because it was too long for drupal.

**Comment by netboss** [comment]
@swirtSJW 
Changed back the field machine name to `field_va_health_connect_phone` following up on our Slack conversation:

> Just a note on the field machine name the original field_va_health_connect_phone is fine, it was my mistake that when I copied it and pasted inside the field it was been cut because it was like this field_field_va_health_connect_ph note the field_field so at the end the field machine name length was correct and I kept it.
