### ISSUE TITLE
Runbook for VA health connect phone request fulfillment

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#7620]
Once #7619 gets merged, CMS help desk should be ready to know what to do if requests come in to update the VA health connect field on the VAMC system content type. 

Dave: This will be "talk to the Facilities team"

**Comment by xiongjaneg** [comment]
Currently, this is request fulfillment (a ticket from Michelle from Facilities Team to CMS Helpdesk), trackable in Jira
