### ISSUE TITLE
Lovell discovery

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#7626]
## Background
Lovell has 7 facilities
 - 1 VAMC that is shared (Capt James A Lovell Federal health care center)
 - 3 are Veteran-only (in VAST)
    - Evanston VA Clinic
    - Kenosh VA Clinic
    - McHenry VA Clinic
 - 3-4 are Service-member only (not in VAST) (3 clinics and 1 dental)
    - USS Red Rover
    - USS Tranquility
    - Zachary and Elizabeth Fisher Medical and Dental Clinic
    - USS Osborne Dental Clinic
 
 
Much of the rest of the content is the same, but not all. 

**What should be the same:** Events, News Releases, Stories, services at the VAMC. 
**What is different:** Top task CTAs, some programs, some of the other “About” content, Facilities (and possibly services). 

## Artifacts
[Veteran user flow](https://app.mural.co/t/vsa8243/m/vsa8243/1639752014389/5eeb47259cd9128ac0eef10e483761a6247137e0?sender=michellemiddaugh9063) mural
[Information architecture](https://app.moqups.com/Rnc4BDEKrA/view/page/a38ead751) moqup 
[Mural](https://app.mural.co/t/vsa8243/m/vsa8243/1642708450813/52521c15676970f2db4fcdd8161eb1dcb5ac87f1?sender=michellemiddaugh9063) with research from SMEs from Lovell 
[UXpin mockup](https://preview.uxpin.com/d55fbe11583adc1a1d7b6e2bafde9ef560c7bf36#/pages/148503607/simulate/sitemap?mode=i) 
[Initial notes and brainstorming](https://docs.google.com/document/d/15zfbgdGNXLVrUbP8AMrmZ43eWXMHSTGJIruZ7se1jH4/edit?usp=sharing)

## Goals (in priority order)
1. Seamless experience for Veterans and Service members
2. Not having duplicated content for editors to manage
3. Limited tech debt/snowflake code. 

## Initial FE Design Principle Proposal ([mockup](https://preview.uxpin.com/d55fbe11583adc1a1d7b6e2bafde9ef560c7bf36#/pages/148503607/simulate/sitemap?mode=i) )
- Two different "systems" exist at two slightly different locations.
- Duplicative content lives in both places (two different urls). 
- Two different menus exist.
- Jump tab link jumps you from VA to Tricare and back.
- VA version would be canonical

## CMS Editorial Concerns
- Some editors are VA, and some are Tricare so ownership controls are needed.
- A high percentage of the content will be shared and should not require maintaining multiple copies ([Content Map](https://app.moqups.com/Rnc4BDEKrA/view/page/a38ead751) pink is non-shared content)

## Proposed model for CMS content
- Three sections will be created
![image](https://user-images.githubusercontent.com/5752113/162357993-24259bee-2a0c-4dd5-9bf9-6db1fbcccf95.png)

- FE logic would handle building two pages for the same node if needed.
   - field_administration would be used for FE logic :(.
- Duplicate aliases would be created in CMS on shared content.
- Two separate menus would be maintained (hard to automate this reliably... needs more thought  maybe three menus?)
- Non VA facilities would be accounted for #1939

Backlog can't be built out until after some user and hypothesis testing has been done.

**Comment by swirtSJW** [comment]
Lovell discovery from a technical point of view is done.   There is further discovery needed testing FE hypotheses but that will be covered by a different ticket.

**Comment by swirtSJW** [comment]
The technical approach has been socialized with Jay and Ryan.   It needs to be discussed with the full team and agreed to before Specific supporting issues are created.
