### ISSUE TITLE
"Alexandria Vet Center" becomes "Alexandria, LA Vet Center"

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#7628]
## Intake (assuming editor submission to helpdesk (HD))
- [ ] Submitter: <insert_name>
- Change type (select one)
  - [ ] VAMC new facility
  - [ ] VAMC facility closure
  - [ ] VAMC facility name
  - [ ] VAMC system name
  - [ ] Vet Center new facility
  - [ ] Vet Center facility closure
  - [x] Vet Center facility name
- [ ] If the submitter is an editor, send them the link to the CMS Knowledge Base (KB) article on facility basic data for their product (VAMC or Vet Center). Let them know that facility changes can take between 75 days and 4 months after submitting a request, according to VAST administrators.
- [ ] If the change is a facility closure, send the editor a link to the operating status KB article and have them change the status to Facility notice and provide a description of the facility closure so that Veterans are aware of the future closure.
- [ ] Other stakeholders to include on updates, if any: <insert name>
 
## Acceptance criteria 
  
- [x] The H1 title change comes from Lighthouse to Drupal.
- Is the new official name plain language? 
  - If yes, go to next step. 
  - [x] If no, update the common name (when #6955 Unlock title field on Vet Centers is handled).
- Is the facility published? 
  - If yes, go to next step. 
  - [x] If no, update URLs for all content in that section by bulk operations.
- [ ] ~CMS team submits~ [Redirect request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=ia&template=redirect-request.md&title=Redirect+Request), ~cc'ing Facilities team~  No redirect needed as it is not published.
- [ ] ~Once timing of Redirect going live is known, alert CMS engineers to carry out the other steps~
- [x] CMS engineer bulk updates node titles for services.
- [x] CMS engineer updates URLs.
- Was a Section created?
  - If no, skip to the next step.
  - [ ] If yes, it may need to be updated (pending some migration script updating).
- Is the Vet Center published? 
  - [x] If no, HD notifies Michelle Middaugh to bulk publish.
  - [ ] HD notifies editor and any other stakeholders.

CMS Team
Please leave only the team that will do this work selected. 
- [ ] Platform CMS Team
- [ ] `Sitewide CMS Team`
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Offices`
  - [x] `⭐️ Product support`
  - [ ] `⭐️ User support`

**Comment by JayDarnell** [comment]
11 pieces of content were previously part of the Alexandria Vet Center section. These items were moved to the new Alexandria, LA Vet Center. All node aliases were updated.

![Screen Shot 2022-01-27 at 3 01 52 PM](https://user-images.githubusercontent.com/21045418/151435022-887d64a7-3de7-420b-9c09-77e2e96a2be5.png)
