### ISSUE TITLE
Support discovery for homepage redesign

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#7629]
### User Story or Problem Statement

Public Websites team is leading the redesign of the www.va.gov

During Q1 2022, Content Ops team will be providing some support on the discovery/design process, with eye to governance, editorial experience, adn some of the curation tools that may be needed to support what makes it onto the homepage. 

### CMS Team

Please leave only the team that will do this work selected.
- [ ] `Platform CMS Team`
- [ ] `Sitewide CMS Team`
  - [x] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Offices`
  - [ ] `⭐️ Product support`
  - [ ] `⭐️ User support`

**Comment by jilladams** [comment]
@kevwalsh I think you can close this epic. PW owns now, under #8340

**Comment by EWashb** [comment]
Hey @jilladams. I agree- it was under the Sitewide CMS team label. I see you have it handled in another issue. I'll close.
