### ISSUE TITLE
Vet Center District 3 editor onboarding support

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#7634]
## User story
As a Vet Center editor, I need to know how to use Drupal to provide important information to Veterans and active duty service members.

## Acceptance Criteria
- [ ] Clean up list of editors: modify list from national office for the bulk upload csv, follow [instructions in Github](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/user-administration/bulk-account-upload.md)
- [ ] Bulk upload the formatted list of editors
- [ ] Attend kick off meetings

### CMS Team

Please leave only the team that will do this work selected. 

- [ ] `Platform CMS Team`
- [x] `Sitewide CMS Team`
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Offices`
  - [x] `⭐️ Product support`
  - [x] `⭐️ User support`

**Comment by stefaniefgray** [comment]
See related issue https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9519

96 new users added to Drupal
7 existing users had District 3 sections added, i.e. existing Indianapolis Vet Center user had South Bend Vet Center added to account

**Comment by kevwalsh** [comment]
Moving to Sprint 61 in case there's followup.

**Comment by kevwalsh** [comment]
@stefaniefgray sounds like this can be closed, and any further support is just normal user support.
