### ISSUE TITLE
Create dashboard panel to monitor 502 errors

### ISSUE THREAD

**Issue by ElijahLynn** [department-of-veterans-affairs/va.gov-cms#7641]
### Problem Statement: 

Currently, if a 502 error happens at the balancer, and it wasn't caused or logged by the CMS application, then it won't get logged and we never know about it. We need a dashboard panel to log 502s from the ALB logs so that we know about them and can act on them. 

This is a follow up from/related to #7023, #7459, #5552, #7151. 

### Acceptance Criteria:
- [x] ALB logs are ingested into Datadog on a recurring schedule
- [x] Dashboard panel is created to show the 502s (just 502s for now) 

### Implementation Details:
- Discussed we will not wait until we are on FedRamped Datadog; we will use the commercial Datadog account because it is just paths (no PHI/PII)
- Might want to do do this with a Lambda
- If all 5XX errors can be displayed in one dashboard, ideal
- Followup ticket to refine scheduled timeframe

**Comment by jkalexander7** [comment]
Pre-requisites need to be better hashed out.
