### ISSUE TITLE
Determine what to do about existing Office content type

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#7643]
One "office" exists and is already published: Events & Outreach.

Dave C expressed a preference to create a new content type and figure out how to deal with published content later.

Acceptance criteria:

- [ ] work with affected folks and communicate decision
- [ ] document decision in the appropriate place

**Comment by kevwalsh** [comment]
I have some thoughts about this and would love to chat through it.

**Comment by wesrowe** [comment]
@kevwalsh, We're thinking new content type to avoid change issues – we understand it's possible tech debt but can resolve that later. Where do you currently sit?

**Comment by wesrowe** [comment]
Decision made: re-use existing type. It was wired nicely to some other stuff, and the one published node will be easily worked around.
