### ISSUE TITLE
Discovery: Inventory Community Care office

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#7647]
## Description

[Community Care](https://www.va.gov/COMMUNITYCARE/index.asp) is the first Office we've identified as a likely Pilot Office due to commingled Tiers 1, 2, and 3 content.

The inventory is intended to document what exists for Community Care and the selected Offices. This includes but is not limited to: documents and other media, functionality, anomalies, inconsistencies, and risks.

## Acceptance Criteria

- [x] Site crawl of Community Care
- [x] Complete Airtable inventory

### CMS Team

Please leave only the team that will do this work selected. 

- [ ] `Platform CMS Team`
- [ ] `Sitewide CMS Team`
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [x] `⭐️ Offices`
  - [ ] `⭐️ Product support`
  - [ ] `⭐️ User support`

**Comment by wesrowe** [comment]
@valerierunde - please add a point estimate for this ticket. See [agile docs](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/onboarding/library/sprint-best-practices.md#pointing) for guideline. There's no right or wrong answer, just take a guess.

**Comment by valerierunde** [comment]
Removed summary of findings. Creating a new issue for that since it will extend into the next sprint.

**Comment by valerierunde** [comment]
Airtable was completed for Community Care.
