### ISSUE TITLE
Collection of regression issues identified in claro mob sessions

### ISSUE THREAD

**Issue by rachel-kauff** [department-of-veterans-affairs/va.gov-cms#7649]
ACs
- [x] Timeboxed: Top priority issues identified in the [Claro mob airtable](https://airtable.com/applHskzNEaJ4qM7R/tblvm17AmjxYtpwWQ/viwzhQXynaHLGuAgb?blocks=hide)

**Comment by tjheffner** [comment]
- https://github.com/department-of-veterans-affairs/va.gov-cms/pull/7639
- https://github.com/department-of-veterans-affairs/va.gov-cms/pull/7676
