### ISSUE TITLE
Figure out support processes for non-scheduled content releases

### ISSUE THREAD

**Issue by stefaniefgray** [department-of-veterans-affairs/va.gov-cms#7650]
## Description
As a member of the VA Drupal CMS Helpdesk team, I want to know what to do if there is a failed content release that was triggered manually outside of the regularly scheduled content release hours.

**Example scenario:** Content releases currently go out at the top of the hour every Monday through Friday from 9 AM to 5 PM Eastern. 

However, VA Honolulu has just published a critical banner alert at 6 PM Eastern -- which is only 1 PM, their time. The content release has failed, and their editors are getting nervous. What do we do?

## Acceptance Criteria
- [ ] Meeting with Dave Conlon to clarify what we're on the hook for and ought to be supporting
- [ ] Our team has determined how after-hours coverage is handled. We know exactly who will be helping with failed content releases, and during which times of day.
- [ ] Editors are aware that we will be able to help them within 24 business hours.
- [ ] There is information in the Knowledge Base concerning after-hours coverage.

### CMS Team

Please leave only the team that will do this work selected. 

- [ ] `Platform CMS Team`
- [x] `Sitewide CMS Team`
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Offices`
  - [ ] `⭐️ Product support`
  - [ ] `⭐️ User support`

**Comment by cmaeng** [comment]
next step = meeting with Dave to clarify from his perspective and ours

**Comment by cmaeng** [comment]
i believe where we landed with @davidconlonis that we are on the hook to provide support from 8am-8pm ET (normal support hours) with the wrinkle that we have a 2 business day window to resolve. there is no expectation that i'm aware of for our team to be responsive outside of business hours. let's confirm with Dave and then close out this ticket.

**Comment by stefaniefgray** [comment]
Closing after discussing with @TroyA6
