### ISSUE TITLE
Change management for Care we Provide updates

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#7656]
The change represented by the #4799  will change the VAMC system description of service field to "rich text limited", therefore restricting the use of headings for this section to improve accessibility and consistency in the content structure/design. 
 
**1. Describe the change from the perspective of VA employees, in plain language. What is the employee going to experience with this change?**
After the change is made, the “Care we provide” heading will not be editable and the format options will not include headings within this section. Any existing headings formatted to be bold text will remain as is.

**2. Explain why the change is necessary from a CMS/platform and project goal perspective. Link to screenshots if that helps tell the story.** 
By limiting the use of headings in this field, we can also make this content more reusable in other parts of the Veteran experience.

**3. Select the role(s) impacted by the change.**
- [ ] All CMS users
- [ ] All CMS editors
- [ ] Vet Center editor
- [x] VA Medical Center editor
- [ ] VA Outreach Hub editor
- [ ] VA Benefits Hub editor
- [ ] Campaign landing page editor
- [ ] VA Resources and Support editor
- [ ] Offices editor
- [ ] Supporting roles such as CMS account admin, Facilities or Public websites team member

**4. How will success be defined for this change?**
No more accessibility errors or strange content design in health service accordions.

**5. How will success be measured for this change (audit, survey, other types of research, etc.)?**
No more headings in system health service content. [A search for h3s returns no results.](https://prod.cms.va.gov/admin/content/audit/vamc-system-service-audit?title_op=contains&title=&field_service_name_and_descripti_target_id=All&field_body_value_op=contains&field_body_value=h3)

**6. Does the change require new or updated:**
- [ ] Knowledge Base article(s)
If existing articles, list URLs:
- [ ] Training video(s)
If existing videos, list URLs:
- [ ] CMS UI support

**7. Will the change be tested with users before release?**
- [ ] Yes
- [x] No

**8. Are there any known dependencies?**
Testing

[WIP document](https://airtable.com/appJCOGGJRTAwcH2v/tblPHoElsBWwr83Z0/viwSfROR69D6seBkB/recX1sNbh41EVvl2o?blocks=hide)

## Acceptance Criteria

- [x] Communication sent to impacted editors

### CMS Team

Please leave only the team that will do this work selected. 

  - [x] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Offices`
  - [ ] `⭐️ Product support`
  - [ ] `⭐️ User support`

**Comment by ContentBrewmaster** [comment]
Added CM considerations and revised acceptance criteria.

**Comment by ContentBrewmaster** [comment]
Email sent from VHA Digital Media to VAMC editors May 3, 2022.
