### ISSUE TITLE
Dry run for Care we provide changes

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#7657]
## Acceptance Criteria
- [ ] Runbook on #4799 is performed as a dry run on a tugboat environment

### CMS Team

Please leave only the team that will do this work selected. 

  - [x] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Offices`
  - [ ] `⭐️ Product support`
  - [ ] `⭐️ User support`

**Comment by JayDarnell** [comment]
Using the following tugboat environment for testing: 
https://pr8647-0hzcepf9bqtiqpybtcpvzct2nwgdmvj4.ci.cms.va.gov/

H2 tags found - 21
H4 tags found - 57
H5 tags found - 7

Results of running `drush scr ./scripts/content/VACMS-6456-remove-leading-care-we-provide-h3-tags.php`

[h3_cleanup_script_results.txt](https://github.com/department-of-veterans-affairs/va.gov-cms/files/8592263/h3_cleanup_script_results.txt)
