### ISSUE TITLE
Move Content Release and Broken Link notifications to new Slack Channel

### ISSUE THREAD

**Issue by indytechcook** [department-of-veterans-affairs/va.gov-cms#7664]
## Description
 
The Release tools team is moving (has moved) the notifications for content build CI from `#vfs-platform-builds`  to `#status-content-build`.

## Acceptance Criteria
- [ ] Broken Link notifications go to `#status-content-build `
- [ ] Build messages and failed build messages to go `#status-content-build `
- [ ] CMS Helpdesk has been notified about change.
- [ ] VFS Teams have been notified about change.

### CMS Team

Please leave only the team that will do this work selected. 

- [x] `Platform CMS Team`
- [ ] `Sitewide CMS Team`
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Offices`
  - [ ] `⭐️ Product support`
  - [ ] `⭐️ User support`

**Comment by jkalexander7** [comment]
We have moved broken link notifications to #content-broken-links and content release status and failure notifications to #cms-notifications.
