### ISSUE TITLE
Upgrade Docker from 19 > 20 on Tugboat server

### ISSUE THREAD

**Issue by ElijahLynn** [department-of-veterans-affairs/va.gov-cms#7667]
## Overview
Docker needs to be updated on Tugboat. 

**Reason for Change:** _PHP 7.4-bullseye image doesn't work (see https://github.com/department-of-veterans-affairs/va.gov-cms/issues/6216) and needs Docker 20.10+ to work properly._

We don't have to do this directly with the Tugboat application upgrade in 
- #6306

### Acceptance Criteria:
- [x] DNS & Cert upgrade impact(s) documented on this issue
- [x] Upgrade Docker from 19 > 20 on Tugboat server

### Implementation notes:
Can test Tugboat by creating an AMI and I think we have a test.tugboat.vfs.va.gov DNS entry already, not sure about cert but maybe?

**Comment by ElijahLynn** [comment]
Tugboat images (https://docs.tugboat.qa/reference/tugboat-images/#php) are based on the official PHP images (https://github.com/docker-library/php/tree/master/7.4) and we currently use the tugboatqa/php:7.3.28-apache image which is based on Alpine. (the debian images are -buster and bullseye, https://github.com/TugboatQA/dockerfiles/blob/main/php/TAGS.md)

https://github.com/department-of-veterans-affairs/va.gov-cms/blob/4fbefdd2fcce6291b3f0cb40ceba8f261c10ff49/.tugboat/config.yml#L3-L7

So the comment in the code is still valid.

**Comment by ElijahLynn** [comment]
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/6216#issuecomment-1016688041

> The reason, I think/it seems, for this is that the latest Apache image depends on Alpine Linux which recently introduced a commit from Moby that has a dependency on Docker 20.10.0 AND ibseccomp 2.4.4.

Turns out we aren't actually using Alpine but the -bullseye/debian image but it appears that the Moby <> Docker 20.10 + ibseccomp 2.4.4 issue is still present in the Debian image.

**Comment by q0rban** [comment]
Here's the version we're currently running: 

```
$ dpkg --status docker-ce | grep Version
Version: 5:20.10.12~3-0~debian-buster
```

**Comment by cweagans** [comment]
What happens if we use the `7.4-apache-buster` tag? Buster is older. Maybe it would work with an older docker? We should still definitely do this upgrade, but I'm wondering if we can sidestep it for the time being.

**Comment by ndouglas** [comment]
@cweagans Great idea!  It appears to be working -- it's progressed pretty far in the build past `bullseye`, anyway 😃 

While that's doing its thing, I'm trying to set up the test Tugboat environment to see if we can make progress on the long-term goal.  Elijah got it up and had incoming requests routed correctly, but Tugboat itself doesn't wanna start:

<img width="930" alt="Screen Shot 2022-01-20 at 7 36 59 AM" src="https://user-images.githubusercontent.com/1318579/150340020-1c8d709e-f5d0-4aef-8023-8dc4b0904ff4.png">

The reason would seem to be:

```
sh-4.2$ sudo docker info
...
 Swarm: error
  NodeID: 
  Error: error while loading TLS certificate in /var/lib/docker/swarm/certificates/swarm-node.crt: certificate (1 - qmjbtp5o7ymmrctl7hvzcbpla) not valid after Thu, 15 Apr 2021 23:06:00 UTC, and it is currently Wed, 19 Jan 2022 19:24:54 UTC: x509: certificate has expired or is not yet valid
  Is Manager: false
  Node Address: 172.31.0.56
...
```

```
sh-4.2$ sudo docker swarm leave
Node left the swarm.
sh-4.2$ sudo docker swarm init
Swarm initialized: current node (rvflh9tz77scc1j9gab74ntlt) is now a manager.
...
sh-4.2$ sudo docker info     
...
 Swarm: active
  NodeID: rvflh9tz77scc1j9gab74ntlt
  Is Manager: true
  ClusterID: p4gu64d41uvkgximql7kqt23s
  Managers: 1
  Nodes: 1
  Default Address Pool: 10.0.0.0/8  
  SubnetSize: 24
  Data Path Port: 4789
  Orchestration:
   Task History Retention Limit: 5
  Raft:
   Snapshot Interval: 10000
   Number of Old Snapshots to Retain: 0
   Heartbeat Tick: 1
   Election Tick: 10
  Dispatcher:
   Heartbeat Period: 5 seconds
  CA Configuration:
   Expiry Duration: 3 months
   Force Rotate: 0
  Autolock Managers: false
  Root Rotation In Progress: false
  Node Address: 172.31.0.56
  Manager Addresses:
   172.31.0.56:2377
...
sh-4.2$ sudo tbctl start

Starting Tugboat...

  Checking Docker                                                       [  OK  ]
  Network: tugboat                                                      [  OK  ]
  Service: agent                                                        [  OK  ]
  Service: apache                                                       [  OK  ]
  Service: api                                                          [  OK  ]
  Service: logs                                                         [  OK  ]
  Service: mail                                                         [  OK  ]
  Service: mongo                                                        [  OK  ]
  Service: proxy                                                        [  OK  ]
  Service: puppeteer                                                    [  OK  ]
  Service: redis                                                        [  OK  ]
  Service: registry                                                     [  OK  ]
  Service: scheduler                                                    [  OK  ]
  Service: server                                                       [  OK  ]
  Service: traefik                                                      [  OK  ]
  Service: ui                                                           [  OK  ]
  Service: webhooks                                                     [  OK  ]
```

Unfortunately:

<img width="500" alt="Screen Shot 2022-01-20 at 7 43 53 AM" src="https://user-images.githubusercontent.com/1318579/150340991-e55b211d-f55c-4b24-9bcf-b2361011649e.png">

So something is still not functioning somewhere, and I'ma try and figure it out.

**Comment by jkalexander7** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VAgov-CMS-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/7667?planning-poker) with ZenHub @amponce @cweagans @indytechcook @timcosgrove

**Comment by EWashb** [comment]
Something to consider going forward: infrastructure automation issue written and linked below

**Comment by ElijahLynn** [comment]
I'm creating an AMI to test this on, I chose delete on termination for the two extra volumes. 

![image.png](https://images.zenhubusercontent.com/5cdc72c50b7efe3f164150b2/81730db8-b68f-47e7-b56d-3e56e964c4cd)

**Comment by ElijahLynn** [comment]
Living documentation/progress thread https://dsva.slack.com/archives/CT4GZBM8F/p1675967534648249

**Comment by ElijahLynn** [comment]
Sweet, we have test.tugboat.vfs.va.gov mostly up and running now with https://github.com/department-of-veterans-affairs/devops/pull/12545. 

DNS is working, cert is working, balancer and target group is working!

![image](https://user-images.githubusercontent.com/1504756/218228432-3b271bb0-ff87-4abf-91e2-d47ca891bb7a.png)


Next step is to configure Tugboat to know that it lives at test.tugboat.vfs.va.gov.

**Comment by ElijahLynn** [comment]
test.tugboat.vfs.va.gov is ALIVE!!! Gonna test the system upgrade on Monday!

![image](https://user-images.githubusercontent.com/1504756/218228728-6ae90a4f-7a1f-4e45-85a4-4820251270ae.png)

**Comment by ElijahLynn** [comment]
K, I've tested out the upgrade in depth today and have come to the conclusion that we are going to need to suspend/stop all running previews before the upgrade. We are also going to wait until after demo tomorrow.

So the current upgrade steps are going to be, which I am going to test one more time tomorrow morning:

1. Manually add a 443 balancer listener rule (match hostnames on existing rule)  exiwith top priority to serve a custom response of "Tugboat update in progress from X to X" and I think it should be for at least one hour, possibly 2 hours, during business hours, tomorrow after demo. So that would be from 2-4pm PT/5-7pm ET.  This will serve the following to type of message to all users of Tugboat:
![image](https://user-images.githubusercontent.com/1504756/218644349-b923abdb-1a90-43fb-a298-305edcfccb94.png)
![image](https://user-images.githubusercontent.com/1504756/218644426-40a97b32-67d1-4403-97e6-5db8e00f80f6.png)

1. Then, as root run these two commands in different terminals, they will produce a large amount of output and we basically just want to watch when the activity dies down, which will take minutes:
    1. `tail -f /var/log/messages`
    1. `tail -f /var/log/docker`

1. Loop through all previews and `tugboat suspend <ID>`. Watch the logs above to know when they are all done. 
```
PREVIEWS=$(tugboat list previews -j | grep '"preview":' | awk '{print $2}' | tr -d ',' | tr -d '"')
for PREVIEW in $PREVIEWS; do (tugboat suspend $PREVIEW &) ; done
```
 
1. Then, `yum update -y | tee tugboat-yum-update-2023.02.13.log`. Wait for it to complete and then ~5 minutes for the above logs to die down

1. Lastly, `reboot`.

1. Verify instances start by launching some preview links.

**Comment by ElijahLynn** [comment]
W00t! We are now at:
```
# docker --version  
Docker version 20.10.13, build a224086            
```

I am working on some docs to push to https://github.com/department-of-veterans-affairs/va.gov-cms/tree/main/READMES/devops.

**Comment by ElijahLynn** [comment]
I don't think I am going to get the docs pushed tonight and I think we should make a new issue for cleaning that up. 

FWIW: I do have most everything documented here but it is messy right now, but good news is that it is all there and I won't forget it. 

I will also say that we now have a TLS certs setup and DNS for test.tugboat.vfs.va.gov and a way to reliably test major system updates for Tugboat, even though it is still a manual process for now.
