### ISSUE TITLE
Data entry of the field values from the list provided by lighthouse UX

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#7671]
Lighthouse UX will be providing a list of names to be added to health_care_service_taxonomy terms as in the field_health_service_api_id field.
## ACs
- [x] attach list to this issue.
- [ ] For each term in the attached spreadheet [edit each health service term](https://prod.cms.va.gov/admin/structure/taxonomy/manage/health_care_service_taxonomy/overview) add any  health service API ID from the Machine ID provided in the spreadsheet on prod and saved exactly as given.
   - [ ] DO not enter MachineID from spreadsheet if provided with a name that is different than what is already entered in field_health_service_api_id  (there are ~14 values that already exist that must not be changed.)  Call it out to Lighthouse if they propose changing an existing value.
- [ ] notify in #7557 that the PR is unblocked by data.

blocks: #7557

**Comment by swirtSJW** [comment]
This just in from Lighthouse UX
https://dsva.slack.com/archives/C02BTJTDFTN/p1642693216052000
[Health Services Machine Names.xlsx](https://github.com/department-of-veterans-affairs/va.gov-cms/files/7906627/Health.Services.Machine.Names.xlsx)

**Comment by netboss** [comment]
@swirtSJW 
On my way to start working with this. Can you provide more details about this?

**Comment by netboss** [comment]
@swirtSJW 
All terms are ready in [CMS Prod](https://prod.cms.va.gov/admin/structure/taxonomy/manage/health_care_service_taxonomy/overview) except one. There is one term called “Prosthetics and rehabilitation” in [CMS Prod](https://prod.cms.va.gov/admin/structure/taxonomy/manage/health_care_service_taxonomy/overview), but in the spread sheet it's called "Rehabilitation and prosthetics". Should I update the [CMS Prod](https://prod.cms.va.gov/admin/structure/taxonomy/manage/health_care_service_taxonomy/overview) name to match the name in the spread sheet?
