### ISSUE TITLE
Make node count by content type visible in Datadog

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#7673]
## Description
This ticket made total published node count visible in Datadog: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/7244

We would like to additionally see node count broken down by content type, visible in Datadog.

## Acceptance Criteria
- [x] CMS Prod is configured to send node count broken down by content type to Datadog
- [x] A widget or dashboard which visualizes these counts is created, such that a viewer can see trends over time.
- [ ] Needs an update hook somewhere so that new content types auto-add themselves to the list in the prometheus settings

## Implementation information
- The CMS can be configured in the UI here: https://prod.cms.va.gov/admin/config/system/prometheus_exporter - then export the config
- One question is whether this configuration can be managed such that any new content types that are created are automatically added to this list.
- Write a hook so new content types get automatically added
- Click together the UI component in Datadog, we don't do this in Terraform anymore

### CMS Team

Please leave only the team that will do this work selected. 

- [x] `Platform CMS Team`
- [ ] `Sitewide CMS Team`
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Offices`
  - [ ] `⭐️ Product support`
  - [ ] `⭐️ User support`

**Comment by cweagans** [comment]
Notes:
* Needs config exported
* Needs an update hook somewhere so that new content types auto-add themselves to the list in the prometheus settings
