### ISSUE TITLE
Update cms.va.gov Certificate in Terraform 

### ISSUE THREAD

**Issue by olivereri** [department-of-veterans-affairs/va.gov-cms#7685]
## Description

Context: 
https://dsva.slack.com/archives/CDHBKAL9W/p1642693064060200?thread_ts=1642692975.059900&cid=CDHBKAL9W

## Acceptance Criteria

- [x] ~CMS PEM encoded certificates are updated in terraform from ACM.~
- [x] Remove CMS PEM encoded certificates from terraform

Terraform State was out of sync with resources in AWS. Terraform state indicated that the old replaced certificate from last year is still in place despite the updated certs being merged into code. Suspect the PR was merged but never applied in TF, then the resource was updated manually in the console. Found it easier to just remove the CMS SSL cert from terraform as it doesn't feel like it adds much value to include that management complexity and PR workflow to update a resource in a managed service.

The risk being that TF wants to apply an update to the ACM resource with our certs, even though the certs are the same, I'm concerned about a prod outage just to keep this tracked in TF.
## Implementation Details

* Access certificates from Venafi (requires PIV)
* Terraform environment is dsva-vetsgov-ssl
* Updates to cert files in this path devops/ssl
* files:
  * cms.va.gov.crt
  * cms.va.gov.chained.crt
* Private key is inputted at plan and apply time

### CMS Team

Please leave only the team that will do this work selected. 

- [x] `Platform CMS Team`

**Comment by jkalexander7** [comment]
Blocked: Team members have PIV access issues, Venafi access issues

**Comment by olivereri** [comment]
Some certificate clean up:
https://dsva.slack.com/archives/C02HX4AQZ33/p1647959421907979

**Comment by olivereri** [comment]
Terraform State was out of sync with resources in AWS. Terraform state indicated that the old replaced certificate from last year is still in place despite the updated certs being merged into code. Suspect the PR was merged but never merged, then the resource was updated manually in the console, as a possible reason for sync issues. Found it easier to just remove the CMS SSL cert from terraform as it doesn't feel like it adds much value to include that management complexity and PR workflow to update a resource in a managed service.
