### ISSUE TITLE
KB article for Forms flag

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#7687]
## User Story or Problem Statement

As a Forms editor, I need to know when forms are updated from the forms database.

See [Slack thread](https://dsva.slack.com/archives/CT4GZBM8F/p1642695284271600)

## Acceptance Criteria

- [x] Knowledge Base article is created. 
- [x] Coordinate with instructional designer on posting in KB.

## Design principles

Veteran-centered
- [x] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [x] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [x] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Platform CMS Team`
- [x] `Sitewide CMS Team`

**Comment by swirtSJW** [comment]
This already exists here.  https://prod.cms.va.gov/how-to-know-when-a-va-form-changed-in-the-forms-db  
It does need some refining though.

**Comment by xiongjaneg** [comment]
added step by step
