### ISSUE TITLE
Find (and hopefully fix) the root cause of the Datadog Terraform Provider incompatibility.

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-cms#7690]
## Description
A [recent PR in the DevOps repo](https://github.com/department-of-veterans-affairs/devops/pull/10462) failed because of an incompatibility introduced in a recent version of the Datadog Terraform provider.  It failed on my code, which is strange because I feel like I actually know what I was doing there and the existing deployment has been working fine for some time.

I worked around the issue by pinning the Datadog provider version, but that's only good as a short-term fix.

The root cause of the issue should be found and corrected.

```
module.datadog_monitors.datadog_monitor.default["haproxy-bgs-prod"]: Refreshing state... [id=45201613]

Warning: Argument is deprecated

  on cms.tf line 814, in resource "datadog_dashboard" "cms_tic_monitor":
 814:   is_read_only = false

Prefer using `restricted_roles` to define which roles are required to edit the
dashboard.

(and one more similar warning elsewhere)

Error: object contains unparsed element: map[password:{{ DRUPAL_CMS_API_PASSWORD }} username:{{ DRUPAL_CMS_API_USERNAME }}]

Error: object contains unparsed element: map[password:{{ DRUPAL_CMS_API_PASSWORD }} username:{{ DRUPAL_CMS_API_USERNAME }}]

Releasing state lock. This may take a few moments...
Error: Terraform exited with code 1.
```

## Acceptance Criteria
- [ ] `terraform plan` can be executed successfully with the latest version of the Datadog provider.
- [ ] The Datadog provider version has been unpinned.

### CMS Team

Please leave only the team that will do this work selected. 

- [x] `Platform CMS Team`
- [ ] `Sitewide CMS Team`
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Offices`
  - [ ] `⭐️ Product support`
  - [ ] `⭐️ User support`

**Comment by suresh-buddola** [comment]
Hi Team,

Any updates on this Issue and is there any way to fix this issue i have changed the provider version to updated one and still getting the same error and Terraform plan is getting failed.

 **Error: object contains unparsed element: map[password: xxxxxxx    username:  Admin]**



Regards,
Suresh.

**Comment by ndouglas** [comment]
No longer relevant to us.
