### ISSUE TITLE
Content release: send time between workflow start and first job start to Datadog

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#7725]
## Description
We currently track the time taken for relevant content build steps and send the metrics to Datadog, where they are surfaced here: https://app.datadoghq.com/dashboard/eb9-ece-f9z/platform-cms-prod-cms?from_ts=1642875463020&to_ts=1643048263020&live=true

One duration that is not captured here is time before the first job within the Content release workflow starts. This is relevant because there can be a delay between the scheduled time of the workflow beginning and the first job within the workflow actually starting. This delay can be anywhere between 0 to 25 minutes. This can be seen by looking at specific runs, their workflow start time, and the start time of the first job. For example, this run shows a delay of 17 minutes between workflow 'start' and work actually beginning: https://github.com/department-of-veterans-affairs/content-build/actions/runs/1741125421

![image.png](https://images.zenhubusercontent.com/614213ae32396d2bc1205abd/b4abc557-4abb-4709-a667-951db7430c49)

![image.png](https://images.zenhubusercontent.com/614213ae32396d2bc1205abd/3050ac7f-879c-4edd-86cd-5fedc9f7059a)

We should capture the time between workflow start and first job start and expose that metric in Datadog. Brett Logan provided a potential way to capture this time within a workflow: https://dsva.slack.com/archives/CU1E4CX9U/p1642812529044500?thread_ts=1642797085.041400&cid=CU1E4CX9U

Open question: Should this be added to the existing chart of content release times, or exposed separately? 

## Acceptance Criteria
- [ ] Time between workflow start and first job start is captured and send as a metric to Datadog
- [ ] The time to first job start is visible in Datadog along with the rest of the workflow run
- [ ] Average time to first job start is calculated and visible in Datadog

### CMS Team

Please leave only the team that will do this work selected. 

- [x] `Platform CMS Team`
- [ ] `Sitewide CMS Team`

**Comment by mchelen-gov** [comment]
Our publishing metrics dashboard needs to accurately reflect the entire publishing time, so ultimately any relevant steps or delays should be included.

**Comment by cweagans** [comment]
Tried calculating this in a test dashboard: https://app.datadoghq.com/dashboard/3sb-dhq-dsp?from_ts=1642550365198&to_ts=1643155165198&live=true

Datadog does very strange things to the units on the calculated graph, but it's easy enough to see from the graph of work time vs clock time

**Comment by jkalexander7** [comment]
No longer needed - using self-hosted runners.
