### ISSUE TITLE
Push system's VA health connect phone numbers to Facility API upon system save

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#7726]
Each health care system will (eventually) have a `field_va_health_connect_phone`

Each time that number gets updated, Facilty API should get be notified, probably via the facility status push. 

This depends on Lighthouse team's ability to receive this, to be discussed Feb 1. 

End of March the facilities will be going live. 

It may make sense to combine this with #8565.

## ACs
  - [x] If a VAMC system health connect phone number changes, it needs to trigger a facility push for all facilities in that system (Same looper for system name or url changes)
  - [x] key value  pair to push `va_health_connect_phone` =>  field_va_health_connect_phone added to the `system` portion of the payload.
  - [ ] Push health care records  (Cerner/VistA) data too if Lighthouse wants it.

## Implementation details
*  Move logic from .module to an eventsubscriber in docroot/modules/custom/va_gov_post_api/src/EventSubscriber/EntityEventSubscriber.php ::entityUpdate() ad entityInsert() that calls a method to check the save of  (but uses it by dependency injection.  
 `Drupal::service('va_gov_post_api.queue_facility_status_updates')->queueFacilityStatus($entity);` when  Node save of health_care_region_page with a change of field_va_health_connect_phone results in a queueing of facility status push for all facilities (health_care_local_facility) that are connected to that system by field_region_page
* Adding the system->field_va_health_connect_phone to status push docroot/modules/custom/va_gov_post_api/src/Service/PostFacilityStatus.php in getPayload()
* key value  pair to push `va_health_connect_phone` =>  field_va_health_connect_phone
* Push the health care system for each facility at the same time.

**Comment by JayDarnell** [comment]
Cerner/Vista data mentioned above is not to be included based on Lighthouse call from Monday, April 4th.

**Comment by swirtSJW** [comment]
Based on today's call with lighthouse they are going to be ready for this number before they are ready for other system data.  We may have to reconnect with this and the mental health number.  We can keep all your logic and just comment out the data being added to the payload.

**Comment by JayDarnell** [comment]
@swirtSJW I've added a new commit to the PR for the facilities API work to comment out all new fields except for the health connect phone number: https://github.com/department-of-veterans-affairs/va.gov-cms/pull/8647/commits/5c6e27d995bbfe5c7902b175697e025f3340697f
