### ISSUE TITLE
Refactor environment handling

### ISSUE THREAD

**Issue by cweagans** [department-of-veterans-affairs/va.gov-cms#7727]
## Description

Note: this is a fairly large ticket and might need to be considered a small Epic -- the way that it's written should allow us to do smaller pieces in any given sprint.

### Current state

We have the environment discovery plugin manager in the `va_gov_build_trigger` module. This module is aware of each _type_ of environment (BRD, BRDGHA, Lando, etc) and depending on which environment type is configured in settings.php, there are different behaviors that are triggered e.g. when content builds are triggered through the CMS UI. Additionally, if one environment type is configured, other settings have to be added to settings.php as well (for instance, the Github API key and things like that).  Prior to our datadog metrics support, the environment type was only used to determine how to kick off the content build, but now we have at least one other behavior. It's possible that there are other implicit behaviors scattered across the codebase.

### Future state

Let's create a new module called `va_gov_ops` (so that we can move other devops-y stuff into it down the road). This module should manage two different types of plugins:

* `Environment`: These plugins should detect the tier of environment that the site is running in (local, tugboat, dev, staging, prod) and return that name of that environment + a list of key => value pairs that represent settings names and values for that environment.
* `EnvironmentType`: These plugins should detect what type of environment the site is running in (BRDGHA, Local, Tugboat, etc). For any given type of environment, the plugins should be able to return a list of key => value pairs that represent settings names and values for that environment type. This is roughly analogous to the current environment detection stuff.
* `EnvironmentBehavior`: These plugins should be responsible for the specific behavior that should vary between different environments and environment types. These plugins should know what type of environment they apply to (for instance, sending metrics to datadog can happen on any environment type, but only on prod or environments that have explicitly opted into that behavior for testing purposes). Examples: `abstract class BuildTriggerBase`, `class BRDGHABuildTrigger extends BuildTriggerBase`, `class TugboatBuildTrigger extends BuildTriggerBase`, `abstract class DatadogMetricsBase`, `class ProdDatadogMetrics extends DatadogMetricsBase`.

Next, we should set container params as needed (gathering settings from the correct `Environment`, `EnvironmentType`, and `EnvironmentBehavior` plugins for the current environment). See [CompilerPassInterface](https://api.drupal.org/api/drupal/vendor%21symfony%21dependency-injection%21Compiler%21CompilerPassInterface.php/interface/CompilerPassInterface/9.4.x) for some info on how to do this.

Once all of this stuff is working and tests are passing, we can enable the new module by default and strip the environment detection stuff out of `va_gov_build_trigger`.

The end result of this work is that we should be able to delete most of the environment-specific config from `docroot/sites/default/settings` since those settings will have moved to container params set by the various environment plugins and the compiler pass. This also means that we'll be able to test these plugins more cleanly, since we won't be relying on random entries in `$settings` to configure behaviors.

Here's a rough idea of the class hierarchy I was thinking about:

* [mermaid editor](https://mermaid.live/edit#pako:eNqdV1tr2zAU_ivCrHSDJLDXMAbtEtbBLiXt21KKbJ_YYrLkSXKD2fLfdyQ7jm-yy9I-JD7323eO_wSRjCFYBxGnWm8YTRTN9oLg5-qKbMULU1JkIMwt1UCYJseUGhJRzkHhD8Y5yRXLqGK8JEwYUDQy-Nykq0ZLDAYi8_bdmnyT2iBfoSEmB6mISYF8klnOUNs92scHqF2D0QReQJUmZSIhRY6aHe_mC4mkMJQJUI36BMwDGIOc2tp4TNFLncqCx0SBKZQglGSgErTJmTZEHtpxWWtOllARtwmPZQ4NsW2sx-Oxad3ta8t5kbhIMEia55wBRiwda1QoZb2Bi0jb5i2k9IVJ1TeGJIwurKlnAxih1angdwHaYNzGWv9pM86ENlREsCDXMTU0lslzBkaxSF8_VQZdIwwq_6ci2s-5nJcnnQp0Hg9y1aE2Ub05R_BsPa2ZTm1_7pWMt_3cVKQHQzHoxEPdwIuHcr_zEL5K7O8BrZ-RD3-Xy3G3Rjl9Xo4yjzk9bn_3Or5hSPZvMJ_3zSi7Ea2nrj2hvqnbnSftPGLNWFXdrnCWcojYgUVVyzPdHw9P-1nSf7Vgp39ud5sJc49FEkpqJjj6CezTN3GnZANxBBc5Sh-L1JXM57FXYCoIr5A_rjFK3Z2-WP0i4_E3zeQgLVcypCH23lGKa0MQEIBkRZTaNmTGB041cNiIOgrBdlwFkiFgy-VLjiuF1xCp3foBitodNmLDNiDqGvYI5EiFWdkJr7y6KKOhNm7NOW9ArzqNUKHqtwpUu-612rFgPH5ULElADXnaYWCh7PDYOUSTBeULuwIj3DK4jrOcg80CNUxiTDXu1yH24XPcszbXjxwHaJ4NO_Pz3c1YCCMzNcfmemacaYhnrUzVrTiTbT_9gt9TAc_Jz2Zs0vvpLvBRG3iYLMK09GxxpsVni2ZvR3vAte-Z8wS5wf7xfduhuSm0F5gUbhq3N5_uOgyX8RwDNefaPni_D8hy-bH-NgJ6rxOc66o5eX9du4iH_wrwlC7tJEtlHOCcBXQHcbjFsHqFlvbrMWUIXq0MVQdsP6d2_0Lprs1yNbCuZY12KQj8kUEo49IBnztMG3zBvS7g2NRgUSmNKApZnrLa-hX20Ohs1OqpNn3Y6S10wJ4A9BcQOBxwka9mwP1GCFlhXPsIyIuQ4zWBWGxfEronpIfr5xN5007Z69haGk_eqW75-GG1mgWWeQ3_Ay09FXMYMa9hFifmVXixIlgE-FqWURbj66er6z7AvslgH6zxa0zVr32wFyfkK3J8WYFtzAyKrQ-Ua1gEtDDyoRRR86Diqt9h66enf8MQPJc) -- note: there are comments in the editor that may help with understanding
* [mermaid view](https://mermaid.live/view/#pako:eNqdV1tr2zAU_ivCbHSDJLDXMAZtE7bBLqXtWzOGbJ_YYrLkSXKD6frfdyRf4pvs0rQPic_99p3jpyCSMQTbIOJU6x2jiaLZQRD8vH1L9uKRKSkyEOaKaiBMk1NKDYko56DwB-Oc5IplVDFeEiYMKBoZfG7STaslBgORefd-S75LbZCv0BCTo1TEpECuZZYz1HaD9vEBatdgNIFHUKVJmUhIkaNmx7v7SiIpDGUCVKs-AXMHxiCntjbuU_RSp7LgMVFgCiUIJRmoBG1ypg2Rx25c1pqTJVTEXcJ9mUNL7Bob8HhsWneH2nJeJC4SDJLmOWeAEUvHGhVKWW_gLNK1eQUpfWRSDY0hCaMLa2pjACO0OhX8LUAbjNtY6w8240xoQ0UEK3IRU0NjmfzOwCgW6YtflUHXCKPKP1VE-2nKeX7Sq0Dv8ShXPWob1Zsmgt_W05rpuevPjZLxfpibinRnKAadeKg7ePRQbm49hG8S-3tEG2bk47_1etqtSU6fl5PMU05P2799Gd84JPs3ms-bdpTdiNZT151Q39TdNpPWjFg7VlW3K5ylHCJ2ZFHV8kwPx8PTfpb0qhbs9c_V7W7G3H2RhJKaGY5hAof0Xdwr2UgcwUVO0qcidSXzeewVmAvCK-SPa4pSd6cvVr_IdPxtMzlIy5UMaYi9d5LiwhAEBCBZEaW2DZnxgVMNHDainkKwHVeBZAjYcvma40rhNURqt36AonaHjdiwLYi6hj0BOVFhNnbCK6_OymiojVtzzhvQm14jVKj6vQLVvnuddiwYj-8VSxJQY55uGFgoOzx2DtFkQfnKrsAItwyu4yznYLNADZMYU437dYhD-Jz2rMv1M8cBWmbDzvz85XIqhImZWmJzPTPNNMazTqbqVlzItp9-xu-5gJfkFzM26_18F_ioLTzMFmFeerE48-KLRbO3oz3guvdMM0FusH_-2PdobgrtBSaFm8b95fWXHsN5PKdAzbl2CD4cArJef6q_TYDeywSXumpJ3l_XPuLhvwI8pUs7yVIZBziNgO4hDrcYVq_Q0n49pQzBq5Oh6oAd5tTuXyjdtVluRta1rNEuBYE_MghlXDrgc4dpiy-41wWc2hqsKqURRSHLU1Zbv8IeGjVGrZ5q04e93kIH7AlA_wCB4xEX-WYB3C-FkBXGdY-AvAg5XhOIxfYloX9CergefpE33ZS9jK2j8dk71R0fP242i8CyrOE10DJQsYQRyxoWcWJZhRcrglWAr2UZZTG-frq6HgLsmwwOwRa_xlT9OQQH8Yx8RY4vK7CPmUGxrVEFrAJaGHlXiijYHinX0DDVr7D10-f_iaU8TA)

Ref #8108 - lots of `va_gov_build_trigger` was rewritten. The environment handling refactor is the next step to cleaning that module up.

## Acceptance Criteria
- [ ] Environment specific config files are removed (or aggressively reduced)
- [ ] `Environment`, `EnvironmentType`, and `EnvironmentBehavior` plugins are written and unit tested
- [ ] DI Compiler pass populates the appropriate container params
- [ ] Metrics sending functionality is updated to use the appropriate `EnvironmentBehavior` plumbing
- [ ] Build trigger functionality is updated to use the appropriate `EnvironmentBehavior` plumbing
- [ ] Basic documentation is written for how to write new `EnvironmentBehavior` plugins

### CMS Team

Please leave only the team that will do this work selected. 

- [x] `Platform CMS Team`
- [ ] `Sitewide CMS Team`
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Offices`
  - [ ] `⭐️ Product support`
  - [ ] `⭐️ User support`

**Comment by cweagans** [comment]
At some point, it might be nice to refactor our Environment Indicator config into an `EnvironmentBehavior` as well.

**Comment by cweagans** [comment]
One other thing to include here is to move the URL construction logic out of `Drupal\va_gov_build_trigger\Form\PreviewForm` and into an environment behavior.

**Comment by ndouglas** [comment]
Supplanted by work I'm doing in [this project](https://github.com/orgs/department-of-veterans-affairs/projects/943/views/1).
