### ISSUE TITLE
Facility change: Spotsylvania County VA Clinic is now Massaponax VA Clinic

### ISSUE THREAD

**Issue by stefaniefgray** [department-of-veterans-affairs/va.gov-cms#7730]
## Intake (assuming editor submission to helpdesk (HD))
NODE: https://prod.cms.va.gov/richmond-health-care/locations/spotsylvania-county-va-clinic
- Submitter: Megan Kon
- Confirmation that name change has already taken place within VAST: https://www.va.gov/find-locations/facility/vha_652GI
- Original Jira ticket: https://va-gov.atlassian.net/browse/VAHELP-3344
- Example URL that needs to be updated: https://www.va.gov/richmond-health-care/locations/spotsylvania-county-va-clinic/

- Change type (select one)
  - [ ] VAMC new facility
  - [ ] VAMC facility closure
  - [x] VAMC facility name
  - [ ] VAMC system name
  - [ ] Vet Center new facility
  - [ ] Vet Center facility closure
  - [ ] Vet Center facility name
- [x] If the submitter is an editor, send them the link to the CMS Knowledge Base (KB) article on facility basic data for their product (VAMC or Vet Center). Let them know that facility changes can take between 75 days and 4 months after submitting a request, according to VAST administrators.
- [ ] If the change is a facility closure, send the editor a link to the operating status KB article and have them change the status to Facility notice and provide a description of the facility closure so that Veterans are aware of the future closure.
- [ ] Other stakeholders to include on updates, if any: <insert name>
 
## Acceptance criteria (delete all instructions except the set that applies to the change requested)
  
<summary>VAMC – name change</summary>
    
- [x] The H1 title change comes from Lighthouse to Drupal.
- [x] [Redirect request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=ia&template=redirect-request.md&title=Redirect+Request) submitted to reflect the new URL pattern to note the h1 has already changed (because VAST) but the URL is still the old URL https://github.com/department-of-veterans-affairs/va.gov-team/issues/35858
  - [x] cc Dave and Michelle
  - [x] After submission of redirect request, check with Mikki Northuis about "pre-approving" these types of redirects, and assigning straight to PW team  -- when the h1 has changed due to VAST data change, can we work directly with PW around timing of redirect
  - [x] Once timing of redirect going live is known, alert CMS engineers to carry out the other steps
- [x] Locate the newly renamed VAMC Facility (https://prod.cms.va.gov/admin/content/bulk) Search by new name
- [x] Update URL alias for this Facility
- [x] Resave this Facility
- [x] CMS engineer makes bulk alias changes to facility service nodes. (https://prod.cms.va.gov/admin/content/bulk?type=health_care_local_health_service - filter by old VAMC facility name)
- [x] CMS engineer bulk saves fixed titles to facility service nodes. (https://prod.cms.va.gov/admin/content/bulk?type=health_care_local_health_service - filter by old VAMC facility name)
- [x] CMS engineer updates menu title.
- [x] CMS Engineer removes "Name changed" flag from facility and save it.
- [ ] HD notifies editor and any other stakeholders.
 
CMS Team
Please leave only the team that will do this work selected. 
- [ ] Platform CMS Team
- [x] `Sitewide CMS Team`
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Offices`
  - [ ] `⭐️ Product support`
  - [ ] `⭐️ User support`

**Comment by stefaniefgray** [comment]
Still says Spotsylvania on certain pages, i.e. description box on https://prod.cms.va.gov/richmond-health-care/locations/massaponax-va-clinic

**Comment by JayDarnell** [comment]
Moving forward should a CMS engineer change these meta descriptions? If so we should add that to the rename steps.

**Comment by stefaniefgray** [comment]
@JayDarnell That sounds like a good idea! Unfortunately, the meta descriptions might not be the only place on the site with the old name remaining -- is there any way to scrub the entire site to find all possible instances of it?

If the process can't be automated, Stan and Lisa agree that if we can map the facility names according to where they’re located by page, we could send it to VHA DM and have them send it to the PAOs to update

Either way, the steps should mention getting rid of the old name wherever it's located on the site

**Comment by JayDarnell** [comment]
@stefaniefgray I don't think this is something we would want to automate but I can discuss with @kevwalsh and @swirtSJW. In most cases a find/replace should work but I can imagine a scenario where a reference to an old name may still have value (for example, what if we had a news article about a name change where both names are listed). I do think the CMS engineer should update the metadata on the node itself though. 

I've updated the metadata for this item.

**Comment by JayDarnell** [comment]
@stefaniefgray I lost track of this item. Is this done or does this need more attention from a CMS engineer? I did a quick content search for massaponax and found six nodes: the VAMC Facility itself and five VAMC Facility Health Services. I did a quick check of each node and it looks like the clinic itself has one instance of Spotsylvania in the Parking information while the Primary Care node has one instance of Spotsylvania in the name of the service location address.

I could update both of these instances to Massaponax but I'm still on the fence as to whether or not this should be a CMS engineer task. @swirtSJW should we be editing content as part of a facility rename or should editors be checking their content post rename to make sure everything is squared away?

**Comment by swirtSJW** [comment]
Editors need to update their own name in the content.    Ours work is about updating alias, and service node names.

**Comment by swirtSJW** [comment]
This looks like it is all complete except for this task 
![image](https://user-images.githubusercontent.com/5752113/166972230-1ef4e6c1-835a-4ea4-8871-3ccf17e0996f.png)

If that has been done, this should be closed.

**Comment by stefaniefgray** [comment]
Notified editor back in February (VAHELP-3344). They did not mention whether they were still running into the old name at all.

Closing
