### ISSUE TITLE
Content release timing issues investigation and recommendations

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#7731]
## Summary
Scheduled content releases have been showing a significant amount of variation in time-to-complete, with a total range of 30 - 65 minutes depending on the release.

Upon investigation, we determined the primary reason for the longer releases was a delay in the running of the first job of the workflow due to high traffic at Github Actions making it difficult to provision a runner. 

After discussion with Github support and Release Tools, we have a number of recommendations for ways to mitigate the issue. 

## Recommendations
These are mitigation recommendations. They’re organized by low-to-high level of effort, and are in recommended order of implementation, only if the previous mitigation did not have an effect on the timing. 

<table>
  <tr>
   <td>Action
   </td>
   <td>LOE and ability to control
   </td>
  </tr>
  <tr>
   <td><strong>Shift content release schedule. </strong>Currently most scheduled content releases happen at the top of the hour. This means they are competing with many other GHA workflows trying to run at the top of the hour. Shifting away from that time to slightly earlier might allow the content release workflow to secure a runner before the rush. <strong>This was recommended as our first course of action by Github Support.</strong>
   </td>
   <td>Very low, in our control. 
<p>
 Ticket completed: #7723
   </td>
  </tr>
  <tr>
   <td><strong>Continuous content release on GHA</strong>.This might get content live a bit sooner, but it’s subject wide variance and thus doesn’t allow us to give a good guarantee of release time. It also requires coordination with the content build deploy job in order to prevent rollback of changes to content build. 
   </td>
   <td>Low-medium, in our control
   </td>
  </tr>
  <tr>
   <td><strong>Move content release in its current form back to Jenkins.</strong> Jenkins is controlled by us and is not subject to global resource limitations. Its build times are also somewhat better than GHA. This would require some coordination with the Release Tools around protecting content-build deploy, and also would probably force us to disable manually triggered content release inside of working hours.
   </td>
   <td>Low-medium, in our control
   </td>
  </tr>
  <tr>
   <td><strong>Fully self-hosted runner. </strong>Currently we spin up a self-hosted runner for certain tasks, but the task that spins up the self-hosted runner is itself run by a Github runner, so it is still gated by the availability of a Github runner. One possible solution is to have a small persistent self-hosted runner that is used to run the task of spinning up the larger runner on demand. Then, all jobs would be moved to the large self-hosted runner, taking Github runners out of the equation entirely.
   </td>
   <td>Medium, in our control
   </td>
  </tr>
  <tr>
   <td><strong>Move content release to Jenkins and make it continuous. </strong>This would combine the speedier build times of Jenkins with continuous deployment. It would allow us to guarantee a content maximum time-to-deploy of double the build time on Jenkins, which would come out to a little under an hour for any content. At times, content would become live sooner. This would require much stricter coordination with Release Tools and the content-build deploy.
   </td>
   <td>Medium-high, in our control
   </td>
  </tr>
  <tr>
   <td><strong>Move all content build back to Jenkins. </strong>If it is difficult to negotiate content release moving back to Jenkins due to coordination issues, another path could be moving all content-build deploys to Jenkins. This would almost certainly require Platform CMS taking responsibility for the daily deploy of content build. It would be a large effort, if it was even agreed to.
   </td>
   <td>Last resort. High + ongoing support commitment, in our control (if agreed to)
   </td>
  </tr>
</table>

**Comment by timcosgrove** [comment]
## Background

This was first brought to our attention by Jane Xiong in a Slack thread: https://dsva.slack.com/archives/CT4GZBM8F/p1642690192252400 . She and others were noticing that content release seemed to be taking longer than it had previously and also that the timing seemed to be variable and inconsistent. 

We have problems with running Content Release from Github Actions (GHA). GHA cannot guarantee that a workflow will start when it’s requested, because runners may not be available, depending on global availability. The time between a workflow being triggered and its actual start time can vary between 0 - 30 minutes approximately.

This can be seen by comparing the [Platform CMS Dashboard](https://app.datadoghq.com/dashboard/eb9-ece-f9z/platform-cms-prod-cms?from_ts=1642627458538&to_ts=1642800258538&live=true) and the [CI view for content release](https://app.datadoghq.com/ci/pipelines/lco-5czptsAY/Content%20Release/none/master?query=env%3Anone%20%40git.repository.id%3A%22github.com%2Fdepartment-of-veterans-affairs%2Fcontent-build%22%20%40ci.pipeline.name%3A%22Content%20Release%22%20%40ci.provider.instance%3Agithub-actions%20%40git.branch%3Amaster%20%40ci.status%3Asuccess&index=cipipeline&start=1642195284226&end=1642800084226&paused=false). The Platform CMS Dashboard reflects the total time of sum of the workflow pieces to run, as of this writing 32m on average with variants of up to 5 minutes. 

The CI view shows the total time from the scheduled or triggered beginning of the workflow to the time content is available on VA.gov. It averages about 41m, with wide variance, from as little as 30m (in other words, no additional delay introduced), to over an hour.

* **The Platform CMS Dashboard is a good measure of how well the Platform CMS team is upholding its piece of the content release process.** It’s an indicator of changes in build duration, for those pieces Platform CMS is responsible for and has control over.
* **The CI view of content release represents the editor experience of content release.** If an editor is waiting for content to go live, they generally look for it 30 minutes after the top of the hour, since that’s what they’ve been told. It is a measure of how well the VA Platform as a whole is serving Veterans, with respect to CMS content.

Continuous content release will help this some but not greatly, because great variance is still being introduced by the initial delay in the workflow starting. In a worse case scenario, two back to back releases can take one hour each collectively. This means that we can still only guarantee content is live two hours after it is published in the CMS. 

Manually triggered content release (from banners and the like) help some, but they are cancelled by any other higher priority content release, including a subsequent manually triggered release. Inside business hours, very few manually triggered content releases actually complete and result in content becoming live any sooner than they would otherwise.

**Comment by mchelen-gov** [comment]
Issue to track delays & overall publishing time in our dashboard: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/7725

**Comment by mchelen-gov** [comment]
Slack discussion with Github rep: https://dsva.slack.com/archives/CU1E4CX9U/p1642797085041400

**Comment by cweagans** [comment]
Low hanging fruit: switch off of github hosted runners: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/7776

**Comment by mchelen-gov** [comment]
> Fully self-hosted runner.

Is this the same as "Fully self-hosted runner" as described in OP?

**Comment by cweagans** [comment]
Yes

**Comment by timcosgrove** [comment]
@jkalexander7  @ENeal49  Unsure how to treat this ticket vis-a-vis sprint. I added it to the sprint because it was work I did this sprint. However, it doesn't really feel like an issue that should be open or closed; it's just information and recommendations for paths forward.

If you want to close it please feel free. There won't be any code directly attached to this ticket.

**Comment by jkalexander7** [comment]
Recommendations added to Confluence page for reference: https://vfs.atlassian.net/wiki/spaces/PCMS/pages/2070347842/Content+Release+Timing+Issues
