### ISSUE TITLE
Add Decision Document issue template

### ISSUE THREAD

**Issue by jkalexander7** [department-of-veterans-affairs/va.gov-cms#7742]
## User Story or Problem Statement

A standardized format for documenting decisions should be added to the Github issue templates for better visibility of major project changes and for tracking purposes. See https://github.com/department-of-veterans-affairs/va.gov-cms/issues/7330 for reference.

## Acceptance Criteria

- [ ] Template includes: 
* Authors
* Last updated date
* Status (draft > review > approved)
* Approvers
* Problem Statement
* Recommendation
* Rationale
* Other options considered
* Assumptions
* Risks
* Next Steps

**Comment by TheBoatyMcBoatFace** [comment]
Discussed - I will handle

**Comment by TheBoatyMcBoatFace** [comment]
PR submitted. Closing issue
