### ISSUE TITLE
[Spike] Tour module possibilities

### ISSUE THREAD

**Issue by rachel-kauff** [department-of-veterans-affairs/va.gov-cms#7769]
Related to a broader spike on in-context cms alerts: #7768

# User stories
As a CMS user, I want to **see updates about changes to the CMS in the right context** so I can easily understand the change and take appropriate action.

As a CMS user **I don't want to see tour again once I've understood what it's trying to show me** so it doesn't get in the way of my flow.

As a CMS user I want to be able to **open related links to KB articles from tour content** so I can get more details on what tour is showing me.

A cms team member managing tour content, I want to be able to **set how long the tour stays up** so I know it will remain up for the appropriate amount of time (and prevent notification fatigue).

## Use cases

- **Recurring events** As a CMS user who edits events and has been waiting for the new recurring events feature, I want the CMS to point out the part of the form that lets me make events repeating so I don't have to look for it myself.

## Resources
[Tour module in DO](https://www.drupal.org/project/issues/drupal?text=&status=Open&priorities=All&categories=All&version=All&component=tour.module)

## ACs
- [x] Module is turned on for experimentation
- [ ] Tech approach is defined
- [ ] Decisions are made about how to approach appearance. 
- [x] We've defined it's place in our system in terms of:
   - [x] Governance - who can use it
   - [x] purpose - when to use it
   - [x] behavior - how does it function

Document these technical details in this issue
- [ ] Dismissability
   - Test existing patches to see what meets our needs
- [ ] Custom routes (eg only the event node form)
- [ ] Auto-starting the tour (and hiding the Tour button)

## Notes

MVP requirements
- Pops up when the form opens
- Accessible.
- Can make label and icon changes to tour menu item
- Admin can set how long tour is active (nice to have)
- Dissmissability - users can dismiss permanently (highly desired)
-  Modal background color (anything but dark mode)

Post-mvp ideas
- Users can turn off tours (along with other notifications)
- Disable field functionality during tour (more to explore here)
   - Example: Atlassian's tour design doesn't use modal/background. Works more like a tooltip.

## Design decisions
Purpose:
- Only for new features!
- Other applications: explore later.

Governance
- Anyone who wants to use tour should have CMS experience team review request
- TBD: Request process
- CMS experience team sets up tour
- Kauff writes the UX copy

Behavior
- Appears only for a limited amount of time.
- CMSx team sets cal reminders ^^

## Findings

TBD

**Comment by rachel-kauff** [comment]
Via Kev: Joyride module https://zurb.com/playground/jquery-joyride-feature-tour-plugin

**Comment by msbtterswrth** [comment]
@kevwalsh I found a sandbox module we can potentially use to solve the node/add/[type] issue: https://www.drupal.org/sandbox/mariodan/3015086. We could probably roll a similar approach in house as well. I like the UI this adds though.
