### ISSUE TITLE
Display Level 2 (“top 14 offices”) data from Drupal on screen under appropriate section header

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#7771]
## Description

As a visitor, I want to see the top 14 (level 2) offices so that I have an understanding of the highest level of organization.

Lots of unknowns and possible risks as there is coordination and information sharing that needs to happen, particularly with the Platform CMS team. Meeting with them planned for sprint 51.

Blocker: ~deciding whether to use GraphQL or CAPI.~ See #7815: Next.js/Gatsby going to likely be the way going forward - do we go directly to that, or try to grab data via GraphQL temporarily?

## Acceptance Criteria
- [ ] Top 14 offices are displayed on the front end, without any concern for design system.

### CMS Team

Please leave only the team that will do this work selected. 

- [ ] `Platform CMS Team`
- [ ] `Sitewide CMS Team`
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [x] `⭐️ Offices`
  - [ ] `⭐️ Product support`
  - [ ] `⭐️ User support`

**Comment by cmaeng** [comment]
Unknown where we're at with UX / wireframes on this. are we waiting for specific designs that build on wireframes or can we start building with what we have?

conversations ongoing with Public Websites team for design resources. can start exploring with them on how baked current designs are.. @rtwell is also available to help parse.

**Comment by cmaeng** [comment]
we can do work on how to display without knowing exactly how we're going to grab the data.

**Comment by rtwell** [comment]
we have had [these wires](https://www.sketch.com/s/fe67a951-84d1-4a61-bd7c-e13ab686ac5c/a/JnvK03M) since this project began @cmaeng

**Comment by ryguyk** [comment]
This work is effectively done, but waiting to submit PR until we are certain we are moving forward with this office project as we know it.
