### ISSUE TITLE
Move content build to self hosted runners for everything

### ISSUE THREAD

**Issue by cweagans** [department-of-veterans-affairs/va.gov-cms#7776]
We're experiencing delays of up to 20-30 minutes between when a workflow is queued and when the first job in that workflow actually starts. Github has indicated that this is because we're running stuff at the top of the hour, they have lots of stuff running at that time, etc. We tried not running the build at the top of the hour and that didn't seem to change much of anything. Ref: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/7731

Possible solution:
* Add two new scheduled jobs to the content build repo:
	* The first should create a runner every morning at 7-8am ET
	* The second should tear down that runner ever night at 7-8pm ET
* Change all of the jobs in the content-release workflow that currently use github public runners to use the runner that is created every morning. Maybe also change adjacent jobs (daily release, CI, etc).

### ACs:
- [x] content build (and maybe related jobs) don't use github public runners for anything
- [x] content build completes successfully
- [x] content build reliably starts when we tell it to start

### CMS Team

- [x] `Platform CMS Team`
- [ ] `Sitewide CMS Team`
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Offices`
  - [ ] `⭐️ Product support`
  - [ ] `⭐️ User support`

**Comment by cweagans** [comment]
A thought here for building confidence in the approach is to set up another content build workflow that runs in parallel that doesn't actually publish anywhere. That workflow can be set up to use this small runner to verify that it works before we transition the real prod content build over to this approach.

**Comment by cweagans** [comment]
Opened PR: https://github.com/department-of-veterans-affairs/content-build/pull/949

**Comment by indytechcook** [comment]
Cross referencing: https://github.com/department-of-veterans-affairs/va.gov-team/issues/36310
