### ISSUE TITLE
Collect debug info for Content Release workflow in GHA

### ISSUE THREAD

**Issue by mchelen-gov** [department-of-veterans-affairs/va.gov-cms#7791]
## Description

Add https://github.com/marketplace/actions/debug-action to https://github.com/department-of-veterans-affairs/content-build/blob/master/.github/workflows/content-release.yml workflow to collect debug information.

## Acceptance Criteria
- [ ] Debug logs are collected for Content Release pipeline runs
- [ ] Logs are included for 1 slow (>50m) and 1 fast (<30m) run

### CMS Team

Please leave only the team that will do this work selected. 

- [x] `Platform CMS Team`

**Comment by timcosgrove** [comment]
@mchelen-gov Do you recall what the intention was with this ticket? We can certainly do it, but it would be good to understand what we're hoping to learn from seeing the environment variables.

**Comment by TheBoatyMcBoatFace** [comment]
Closing. @mchelen-gov if this is still desired, please re-open.
