### ISSUE TITLE
training.cms.va.gov

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#7800]
## User stories

As a CMS trainee 
* I can access an easy-to-remember URL 
* I can see a visual distinction between training and prod

As a developer, i can target training.cms.va.gov differently than other environments 
* No automatic wiping upon merge
* No daily deploys 
* Dfiferent `environment_indicator` variables

As a training manager, i can perform all my existing tasks for updating the training site.
* track editor activity (same as in prod)
* activate site alert (same as current process - activating the prod site alert for training env)

## Acceptance Criteria
Needs refining.

### CMS Team

Please leave only the team that will do this work selected. 

- [x] `Platform CMS Team`
- [ ] `Sitewide CMS Team`
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Offices`
  - [ ] `⭐️ Product support`
  - [ ] `⭐️ User support`

**Comment by ElijahLynn** [comment]
We might be able to setup a Lambda proxy to do this to a Tugboat environment. This might be easier than wiring up BRD for this, and still let Tugboat be managed to SSH in, rebuild/refresh, etc.

**Comment by TheBoatyMcBoatFace** [comment]
Closing as a training domain exists.
