### ISSUE TITLE
Review and process feedback from PAOs about VAMC

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#7804]
## Description

VHA Digital Media hosted 4 listening sessions in January 2022. As a cross-disciplinary team, how might we learn from what was expressed in these sessions? 

### Videos and/or transcripts
- Session 1 [video](https://www.youtube.com/watch?v=nFBrLN0wfBQ) 
- Session 2 [video](https://www.youtube.com/watch?v=CuBiXZHxRF8)
- Session 3 [video](https://youtu.be/gbLdhpGyLUE)
- Session 4 [video](https://youtu.be/PTAdKkyPpiA)

## Acceptance Criteria
- [x] Synthesis of feedback
- [ ] Existing backlog updated with specific experiences
- [ ] Possibly new backlog

### CMS Team

Please leave only the team that will do this work selected. 

- [ ] `Platform CMS Team`
- [x] `Sitewide CMS Team`
  - [x] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Offices`
  - [x] `⭐️ Product support`
  - [x] `⭐️ User support`

**Comment by suzanne-gray** [comment]
[Research readout deck](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/research/VAMC%20listening%20sessions%20Jan%202022/VAMC%20upgrade%20listening%20sessions.pdf)

**Comment by suzanne-gray** [comment]
@kevwalsh I posted the readout deck but didn't close the issue because of the backlog AC.

**Comment by xiongjaneg** [comment]
@suzanne-gray Is this the final version? Slide 16 still has Vet Centers separate from VHA, which I think you meant VAMC instead of VHA (Vet Centers is part of VHA)

**Comment by kevwalsh** [comment]
@suzanne-gray i think that's fine. i'm going to close this. i think the synthesis pointed more towards some broader problems to solve in the program rather than specific backlog items.
