### ISSUE TITLE
Revisit Account Admin policies for the Outreach Hub

### ISSUE THREAD

**Issue by cmaeng** [department-of-veterans-affairs/va.gov-cms#7810]
## Description
Outreach Hub admin policies need to be revisited to see if they still resonate or if anything needs to be updated.

## Acceptance Criteria
- [x] Review existing policies with Tim Hudek and Dave Conlon
- [x] Update with any new information that has been gleaned
- [x] Publish changes in KB

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Platform CMS Team`
- [x] `Sitewide CMS Team`
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Offices`
  - [ ] `⭐️ Product support`
  - [X] `⭐️ User support`

**Comment by chriscraiga6** [comment]
Spoke with Dave C and the process is documented within the help desk KB. 

Quarterly Updates of Outreach Hub users will be sent to Tim Hudak to review.
