### ISSUE TITLE
Spike: Determine feasibility of waiting for new build system (Next.js/Gatsby)

### ISSUE THREAD

**Issue by cmaeng** [department-of-veterans-affairs/va.gov-cms#7815]
## Description
Meeting happening between CMS Offices and Platform CMS happening in sprint 51 to help determine path forward.

## Acceptance Criteria
- [ ] Testable_Outcome_X
- [ ] Testable_Outcome_Y
- [ ] Testable_Outcome_Z
- [ ] Requires design review

### CMS Team

Please leave only the team that will do this work selected. 

- [ ] `Platform CMS Team`
- [x] `Sitewide CMS Team`
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [x] `⭐️ Offices`
  - [ ] `⭐️ Product support`
  - [ ] `⭐️ User support`

**Comment by wesrowe** [comment]
Decision on architecture will not impact Directory very much. Keep old archi for directory.
