### ISSUE TITLE
Discovery: Identify Office content on legacy Education Service site (within VBA)

### ISSUE THREAD

**Issue by valerierunde** [department-of-veterans-affairs/va.gov-cms#7826]
Performing a quantitative audit on the Education Office site.

**Comment by wesrowe** [comment]
@valerierunde, FYI, I'm renaming this story to focus on what it delivers – e.g., "Identify Office content on legacy Education Service site." I'm not suggesting this would change what you do or how you do it, it would just be a lot clearer about _why_ and what we'll learn from it.

**Comment by wesrowe** [comment]
Story was put on hold mid-sprint by Product Owner, instead we focused on the FOM data source and how it impacts MVP strategy.
