### ISSUE TITLE
Onboard VHA Pilot users

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#7836]
## User story
As a new Resources and Support editor, I need to provide accurate information to Veterans.

## Acceptance criteria
- [x] add accounts in prod/training
- [x] develop training plan
- [x] schedule training
- [x] invite users
- [x] present training
- [x] record training
- [x] send follow-up email and resources

## CMS Team

Please leave only the team that will do this work selected. 

- [ ] `Platform CMS Team`
- [x] `Sitewide CMS Team`
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Offices`
  - [x] `⭐️ Product support`
  - [ ] `⭐️ User support`

**Comment by xiongjaneg** [comment]
From Danielle:
Chris Cox: chris.cox@va.gov (VHA OCC)
Kelly Farmer: kelly.farmer@va.gov (VHA OCC)
Gabrielle Holak: gabrielle.holak@va.gov (VA Charleston)
Joe Schmieder: allen.schmieder@va.gov (VISN 19)

None have existing prod accounts (Kelly tried)

**Comment by xiongjaneg** [comment]
From Danielle: a joint kick-off meeting with follow up self-service materials

**Comment by xiongjaneg** [comment]
joint kickoff scheduled for March 18

**Comment by xiongjaneg** [comment]
added Sean.Banks@va.gov per Danielle

also, all with have roles: Content creator - Resources and Support and Content editor

section: VHA resources and support

**Comment by xiongjaneg** [comment]
Chris Cox didn't attend. Sent training instructions and request to let us know when he's viewed the recording, so we can active his prod account. cc'd Danielle on this and the email to other with resources.

**Comment by xiongjaneg** [comment]
[pilot survey link](https://www.surveymonkey.com/r/7ZSZKZK)
