### ISSUE TITLE
training for R&S VHA pilot

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#7837]
## User story
As a VHA Resources and Support editor, I know how to provide resources and support content for Veterans.

## Acceptance criteria
- [x] [review content types on R&S landing page](https://prod.cms.va.gov/help/resources-and-support/a-guide-to-resources-and-support-content-types)
- [x] create video for each content type
  - [x] R&S detail page
  - [x] FAQ
  - [x] Checklist
  - [x] Media list images
  - [x] Media list videos
  - [x] Q&A
  - [x] Step-by-step
- [x] caption videos
- [x] post on KB

## CMS Team

Please leave only the team that will do this work selected. 

- [ ] `Platform CMS Team`
- [x] `Sitewide CMS Team`
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Offices`
  - [x] `⭐️ Product support`
  - [ ] `⭐️ User support`

**Comment by xiongjaneg** [comment]
posted links to videos on training page in new R&S pilot section
