### ISSUE TITLE
Add custom route ability to Tour UI module

### ISSUE THREAD

**Issue by msbtterswrth** [department-of-veterans-affairs/va.gov-cms#7838]
## Description
Relates to #7769 

### User Story

As a CMS admin, I want to be able to add custom routes such as `node/add/event` to the Tour UI module.

### Possible Implementation
I found two possible routes to take: https://www.drupal.org/project/drupal/issues/2883096 or https://www.drupal.org/sandbox/mariodan/3015086

## Acceptance Criteria
- [ ] Testable_Outcome_X
- [ ] Testable_Outcome_Y
- [ ] Testable_Outcome_Z
- [ ] Requires design review

### CMS Team

Please leave only the team that will do this work selected. 

- [x] `Platform CMS Team`
- [x] `Sitewide CMS Team`
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Offices`
  - [ ] `⭐️ Product support`
  - [ ] `⭐️ User support`

**Comment by msbtterswrth** [comment]
So @ethanteague let's use this ticket as a spike to determine the right approach to the problem. We don't have to do the implementation just yet :)

**Comment by swirtSJW** [comment]
The ticket referenced up top is closed as a  https://www.drupal.org/project/drupal/issues/2730631 which had patch committed into core for 9.3 

When we update to 9.3 is that going to remove the need for this?
