### ISSUE TITLE
Revert content release back to Jenkins

### ISSUE THREAD

**Issue by jkalexander7** [department-of-veterans-affairs/va.gov-cms#7844]
## User Story or Problem Statement

Content release has been experiencing significant delays, causing a less than ideal editorial experience. Publishing times are varying anywhere from 30 minutes to 2 hours. 

Per the [direction of Platform Leadership](https://vfs.atlassian.net/wiki/spaces/ECP/pages/2073002030/Draft+2022-02-01+Mitigate+Github+Actions+content+publishing+delay+using+Jenkins), content publishing will be reverted back to use Jenkins instead of Github Actions, until proper mitigation steps are taken to address GHA performance issues and stabilize release times.

## Acceptance Criteria

- [ ] Adjust Jenkins job to not trigger during full content-build code deploy window or during CMS deploy; ensure by timing window
- [ ] Revert content release to use Jenkins (https://github.com/department-of-veterans-affairs/va.gov-cms/pull/6906)

## Implementation steps
* Set up Jenkins vets-gov-autodeploy-content-build to operate on current schedule. Need to ensure timing such that content build does not collide with daily production content-build deploy as well as CMS deploy.

* During these break times, "manually" triggered content releases will be dropped.

* Timing of content-build full code deploy to be discussed with Release Tools team. 

Potential timing check:
* always trigger content release from Drupal;
* Drupal gets report that content release has gone out; can confirm total time to deploy.

**Comment by olivereri** [comment]
Content Release documentation:
https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/READMES/cms-content-release.md

**Comment by olivereri** [comment]
[Change Production manual content release to use Github Actions](https://github.com/department-of-veterans-affairs/va.gov-cms/pull/6906)

**Comment by olivereri** [comment]
[Content release daily?](https://github.com/department-of-veterans-affairs/content-build/blob/master/.github/workflows/daily-deploy-production.yml)

**Comment by ElijahLynn** [comment]
The job will notify to `#vfs-platform-builds` in Slack if we end up going back to Jenkins with this story.

**Comment by TheBoatyMcBoatFace** [comment]
No longer applicable with current build process.
