### ISSUE TITLE
Facility change: Wyandotte County VA Clinic to Kansas City Kansas VA Clinic

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#7846]
## Intake (assuming editor submission to helpdesk (HD))
- [ ] Submitter: CMS Migrator https://prod.cms.va.gov/eastern-kansas-health-care/locations/wyandotte-county-va-clinic
- Change type (select one)
  - [ ] VAMC new facility
  - [ ] VAMC facility closure
  - [x] VAMC facility name
  - [ ] VAMC system name
  - [ ] Vet Center new facility
  - [ ] Vet Center facility closure
  - [ ] Vet Center facility name
- [ ] Other stakeholders to include on updates, if any: <insert name>
 
## Acceptance criteria 
  

  <details><summary>VAMC – name change</summary>
    
- [x] The H1 title change comes from Lighthouse to Drupal.
- [ ] Coordinate with Facilities team to have FE redirects set up.
- [ ] CMS engineer makes bulk alias changes to facility service nodes. (https://prod.cms.va.gov/admin/content/bulk?type=health_care_local_health_service)
- [ ] CMS engineer bulk saves fixed titles to facility service nodes. (https://prod.cms.va.gov/admin/content/bulk?type=health_care_local_health_service)
- [ ] CMS engineer updates menu title
- [ ] CMS engineer updates Alt text for facility image, if relevant.
- [ ] CMS engineer updates Meta description (TBD: some backwards compatibility for SEM, by including something like ", formerly known as [previous name]".
- [ ] CMS engineer edit facility node and remove  flag `Changed name` then save node.
- [ ] HD notifies editor and any other stakeholders.
</details>
 

CMS Team
Please leave only the team that will do this work selected. 
- [ ] Platform CMS Team
- [x] `Sitewide CMS Team`
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Offices`
  - [x] `⭐️ Product support`
  - [ ] `⭐️ User support`

**Comment by swirtSJW** [comment]
This change came in from CMS migrator on Jan 30, 2022
![image](https://user-images.githubusercontent.com/5752113/152058328-1cfe7ed1-df1e-40ba-a633-24f47844b6d1.png)

**Comment by JayDarnell** [comment]
According to the revision log here: https://prod.cms.va.gov/node/1669/revisions this work was already performed back in February.
