### ISSUE TITLE
Facility change: Arecibo Vet Center to Hatillo Vet Center

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#7847]
**Note**  This change also included a mobile vet center too
Vet Center: https://prod.cms.va.gov/arecibo-vet-center
Mobile Vet center https://prod.cms.va.gov/arecibo-vet-center/hatillo-mobile-vet-center

SInce the Mobile vet center is underneath the vet center, it needs to be processed first, and then the vet center.

## Intake (assuming editor submission to helpdesk (HD))

- [ ] Submitter: CMS migrator
- Change type (select one)
  - [ ] VAMC new facility
  - [ ] VAMC facility closure
  - [ ] VAMC facility name
  - [ ] VAMC system name
  - [ ] Vet Center new facility
  - [ ] Vet Center facility closure
  - [x] Vet Center facility nameS
- [ ] If the submitter is an editor, send them the link to the CMS Knowledge Base (KB) article on facility basic data for their product (VAMC or Vet Center). Let them know that facility changes can take between 75 days and 4 months after submitting a request, according to VAST administrators.
- [ ] If the change is a facility closure, send the editor a link to the operating status KB article and have them change the status to Facility notice and provide a description of the facility closure so that Veterans are aware of the future closure.
- [ ] Other stakeholders to include on updates, if any: <insert name>
 
### [Mobile Vet Center](https://prod.cms.va.gov/node/17518/edit) – facility name change
  
- [x] The H1 title change comes from Lighthouse to Drupal.
- Is the new official name plain language? 
  - If yes, go to next step. 
  - [x] If no, update the common name (when #6955 Unlock title field on Vet Centers is handled).
- Is the facility published? 
  - If yes, go to next step. 
  - [x] If no, update URLs for all content in that section by bulk operations.
- [ ] CMS team submits [Redirect request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=ia&template=redirect-request.md&title=Redirect+Request), cc'ing Facilities team
- [ ] Once timing of Redirect going live is known, alert CMS engineers to carry out the other steps
- [x] CMS engineer bulk updates node titles for services.
- [x] CMS engineer updates URLs.
- Was a Section created?
  - If no, skip to the next step.
  - [x] If yes, it may need to be updated (pending some migration script updating).
- Is the Vet Center published? 
  - [x] If no, HD notifies Michelle Middaugh to bulk publish.
  - [ ] HD notifies editor and any other stakeholders.
- [x] CMS engineer edit facility node and remove  flag `Changed name` then save node.

### [Vet Center](https://prod.cms.va.gov/node/3686/edit) – facility name change
  
- [x] The H1 title change comes from Lighthouse to Drupal.
- Is the new official name plain language? 
  - If yes, go to next step. 
  - [x] If no, update the common name (when #6955 Unlock title field on Vet Centers is handled).
- Is the facility published? 
  - If yes, go to next step. 
  - [x] If no, update URLs for all content in that section by bulk operations.
- [ ] CMS team submits [Redirect request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=ia&template=redirect-request.md&title=Redirect+Request), cc'ing Facilities team
- [ ] Once timing of Redirect going live is known, alert CMS engineers to carry out the other steps
- [x] CMS engineer bulk updates node titles for services.
- [x] CMS engineer updates URLs.
- Was a Section created?
  - If no, skip to the next step.
  - [x] If yes, it may need to be updated (pending some migration script updating).
- Is the Vet Center published? 
  - [x] If no, HD notifies Michelle Middaugh to bulk publish.
  - [ ] HD notifies editor and any other stakeholders.
- [x] CMS engineer edit facility node and remove  flag `Changed name` then save node.

CMS Team
Please leave only the team that will do this work selected. 
- [ ] Platform CMS Team
- [x] `Sitewide CMS Team`
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Offices`
  - [x] `⭐️ Product support`
  - [ ] `⭐️ User support`

**Comment by swirtSJW** [comment]
THis change came in from the facility API on January 21, 2022
![image](https://user-images.githubusercontent.com/5752113/152060847-4561dd90-f609-4aa8-8418-f57ba8cf59c8.png)

**Comment by JayDarnell** [comment]
<img width="1717" alt="Screen Shot 2022-03-02 at 5 56 55 PM" src="https://user-images.githubusercontent.com/21045418/156463984-79ddfe42-7284-4521-afe1-cb48e0d5e9bb.png">
