### ISSUE TITLE
Disable Drupal api current user

### ISSUE THREAD

**Issue by jkalexander7** [department-of-veterans-affairs/va.gov-cms#7870]
## User Story or Problem Statement

Drupal user **api** should be disabled per security disclosures linked in related issue #6973. 

Target date to disable Drupal api current user: March 1, 2022.

## Acceptance Criteria

- [ ] Disable **api** user in Drupal
- [ ] Provide status update in https://github.com/department-of-veterans-affairs/vsp-security/issues/59
- [ ] Transition API dependent teams to new Drupal user:
  - [ ] Content Build (Release Tools)
  - [x] Virtual Agent (chatbot)
  - [ ] Forms API
 

### CMS Team

Please leave only the team that will do this work selected.
- [x] `Platform CMS Team`

**Comment by indytechcook** [comment]
A note regarding how `content-build` pulls in drupal credentials.  There is an order of overriding the connection information.

This is a list of an order of priority.  The higher items are priority over the lower:

1. Arguments to the CLI
  * `drupal-address`
  * `drupal-user`
  * `drupal-password`
2. [Constants](https://github.com/department-of-veterans-affairs/content-build/blob/master/src/site/constants/drupals.js#L17 )(only prod one is used)

In the [GHA](https://github.com/department-of-veterans-affairs/content-build/blob/master/.github/workflows/content-release.yml#L314), the `DRUPAL_ADDRESS` is provided via a in the[ `set-env` step](https://github.com/department-of-veterans-affairs/content-build/blob/master/.github/workflows/content-release.yml#L100) which is [hard coded here](https://github.com/department-of-veterans-affairs/content-build/blob/master/.github/workflows/content-release.yml#L139).  The user name and password are pulled from the [constants](https://github.com/department-of-veterans-affairs/content-build/blob/master/src/site/constants/drupals.js#L17 )

The quick way to have the content build repo use the new user/password is to update the `set-env` step.
* Add a step to get the Drupal auth info from param store similar to [this](https://github.com/department-of-veterans-affairs/content-build/blob/master/.github/workflows/content-release.yml#L47).
* In the new step, export the variable to `DRUPAL_USER` and `DRUPAL_PASSWORD`
* Update the[ build command](https://github.com/department-of-veterans-affairs/content-build/blob/master/.github/workflows/content-release.yml#L314) to:
```
yarn build --buildtype=${{ needs.set-env.outputs.BUILDTYPE }} --asset-source=local --drupal-address=${{ needs.set-env.outputs.DRUPAL_ADDRESS }} --drupal-user=${{ needs.set-env.outputs.DRUPAL_USER }} --drupal-password=${{ needs.set-env.outputs.DRUPAL_PASSWORD }}--pull-drupal --drupal-max-parallel-requests=15 --no-drupal-proxy --verbose | tee build-output.txt
```

Here are a few other suggestions which aren't required to change the build user/password but are important to address DX.

When the api user is disabled, there will most likely be a users who haven't updated their locals.  The Drupal connection information shouldn't be pulled from a constants file at all.  It should either be pulled in via cli argument or env arguments.  Information directing users to `#cms-support` to get a user if they don't have one one should be included in an error message (along with what env variables and/or cli arguments should be used.  Also, the default URL should be the tugboat url, not prod.
