### ISSUE TITLE
Incorrect URL for VAMC Facility Data KB Article

### ISSUE THREAD

**Issue by chriscraiga6** [department-of-veterans-affairs/va.gov-cms#7871]
## Incorrect URL for VAMC Facility Data
When editing a VAMC Facility, the URL displayed under "Facility Data" has the text of:
"Learn how to correct or update centrally-managed data"
This is pointing to the Incorrect URL:
https://prod.cms.va.gov/vamc/how-do-i-update-my-vamc-facilitys-basic-location-data

We should be pointing to the Correct URL: 
https://prod.cms.va.gov/help/vamc/how-do-i-update-my-vamc-facilitys-basic-location-data

## To Reproduce
1. Go to 'Edit a VAMC Facility'
2. Click on 'Learn how to correct or update centrally-managed data'
3. See "Page not found" 

## Expected behavior
Expectation is to see the relevant knowledge base article on how to update centrally-managed data, specific to VAMC Facilities. 

## AC
- [ ] Link in UI is updated
- [ ] Ideally, we use a link like /node/NID , in case the URL changes again. 

### CMS Team

Please leave only the team that will do this work selected.

- [ ] `Platform CMS Team`
- [x] `Sitewide CMS Team`
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Offices`
  - [x] `⭐️ Product support`
  - [ ] `⭐️ User support`

**Comment by kevwalsh** [comment]
I added a redirect in Drupal, that should take care of this for now. but we should update the UI to use the right URL so no redirect is needed.
