### ISSUE TITLE
[Spike] Set publishing expectations w/ editors in the UI

### ISSUE THREAD

**Issue by rachel-kauff** [department-of-veterans-affairs/va.gov-cms#7873]
## Background
Platform teams are in ongoing discussion about how to speed up content release cycles, and have done some discovery on whether instant/ quick turnaround publishing might be possible in the future. 

Regardless of whether the content release cycle takes 1 minute or two hours, users need clear information on what to expect after they save their content as published. Currently we're relying on training to fill that gap, but [user research done last year](https://docs.google.com/presentation/d/1oo1MXRjF0aGdFKeugCQbciJ6R5BeWnrobL4LZ7Tggeo/edit?usp=sharing) shows that it's not enough.

Basic usability heuristics state that users should have visibility into the system status. Ideally, the interface should be able to tell users when their content will go live, and will reflect that event back to them once the content has successfully released. 

There are a number of technical constraints limiting the extent to which we can provide that feedback, but there are still opportunities to make basic improvements that help set expectations with editors. 

This spike should answer the question: what can we do this quarter to help users understand what's going on? What might we want to explore in a future iteration?

## User stories

- As a CMS editor who is about to save my content as published, I want to know what's going to happen next so I can feel confident about the action I'm about to take.
- As a CMS editor who just saved my content as published, I want to know what will happen next and when I can check VA.gov to confirm that it went live."
- As a CMS editor who has saved multiple pieces of content as published content recently, I want to see which ones are live and which are pending so I can better manage my editorial workflow. (Understand that this story is probably not ever going to be possible in decoupled, but putting it here to show what an idea experience might be like).

**Comment by rachel-kauff** [comment]
From the research readout:
<img width="930" alt="Screen Shot 2022-02-03 at 8 26 47 AM" src="https://user-images.githubusercontent.com/41017988/152384852-60394d48-8d8d-4ad4-860a-45aa24f21c4f.png">

<img width="930" alt="Screen Shot 2022-02-03 at 8 26 54 AM" src="https://user-images.githubusercontent.com/41017988/152384856-4196ba5a-00a4-4fa6-a803-5555e3f0c4c0.png">
<img width="930" alt="Screen Shot 2022-02-03 at 8 26 59 AM" src="https://user-images.githubusercontent.com/41017988/152384857-d4629f22-e725-45c4-9766-0fec759cf75e.png">

<img width="930" alt="Screen Shot 2022-02-03 at 8 26 31 AM" src="https://user-images.githubusercontent.com/41017988/152384840-1d5dff7e-d4ee-4d8f-b23b-6cea7fc12d08.png">

**Comment by EWashb** [comment]
This will no longer be an issue when we get Accelerated Publishing. Closing for now.
