### ISSUE TITLE
UI: Render Search input using design system 

### ISSUE THREAD

**Issue by ryguyk** [department-of-veterans-affairs/va.gov-cms#7878]
## Description
See #7771, which aims to get data on the screen, but without any design details.  This ticket is aimed to bring that initial display in alignment with the design system and with accessibility concerns.

See also: Spike #7808.  We first need some exploration into the existing design system.

### CMS Team

Please leave only the team that will do this work selected. 

- [ ] `Platform CMS Team`
- [ ] `Sitewide CMS Team`
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [x] `⭐️ Offices`
  - [ ] `⭐️ Product support`
  - [ ] `⭐️ User support`

**Comment by allisonlu** [comment]
PR opened: https://github.com/department-of-veterans-affairs/vets-website/pull/20491

**Comment by allisonlu** [comment]
Merged into main branch! https://github.com/department-of-veterans-affairs/vets-website/commit/b6a7a1d09621756faaea2d3e969fa1034c2f52a3
