### ISSUE TITLE
User support runbook for incoming issues related to Cerner

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#7879]
How should user support team respond to inquiries about Cerner? 

Dave: Possibly this will "talk to Lauren", or other areas of VHA

**Comment by EWashb** [comment]
Do we want to recreate the blueprint process that is happening for top task for this?

**Comment by xiongjaneg** [comment]
[created KB article for helpdesk](https://prod.cms.va.gov/electronic-health-records-ehr-system-changes)

**Comment by xiongjaneg** [comment]
closed in favor of [#8146](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/8146)
