### ISSUE TITLE
Update staff profiles with no title

### ISSUE THREAD

**Issue by msbtterswrth** [department-of-veterans-affairs/va.gov-cms#7889]
## Description
Relates to #7353. 
"Currently staff profiles use the name fields to generate the title. However, names are not required, so we can end up with nodes with no titles. Which creates query errors."

The fields are now required, but existing nodes either need to be deleted or updated to have the titles generated. 

## Acceptance Criteria
- [x] Existing profiles with no titles either have their title(names) restored, or are deleted so they do not create sql time bombs.

### CMS Team

Please leave only the team that will do this work selected. 

- [ ] `Platform CMS Team`
- [x] `Sitewide CMS Team`
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Offices`
  - [x] `⭐️ Product support`
  - [ ] `⭐️ User support`

**Comment by netboss** [comment]
@swirtSJW @msbtterswrth 
Updated six Staff Profile nodes titles with first and last names and deleted three that didn't have any names. 

Here is the list:

- FIRST NAME: Lily
    - LAST NAME: Haken
    - URL: https://prod.cms.va.gov/salisbury-health-care/staff-profiles/lily-haken

- FIRST NAME: Ronald J.
    - LAST NAME: Maurer
    - URL: https://prod.cms.va.gov/salisbury-health-care/staff-profiles/ronald-j-maurer

- FIRST NAME: Tina L.
    - LAST NAME: Prince
    - URL: https://prod.cms.va.gov/north-florida-health-care/staff-profiles/tina-l-prince

- FIRST NAME: Fred
    - LAST NAME: Liggett
    - URL: https://prod.cms.va.gov/bay-pines-health-care/staff-profiles/fred-liggett

- FIRST NAME: William
    - LAST NAME: Torio
    - URL: https://prod.cms.va.gov/northport-health-care/staff-profiles/william-torio

- FIRST NAME: Deborah
    - LAST NAME: Cheatham
    - URL: https://prod.cms.va.gov/north-texas-health-care/staff-profiles/deborah-cheatham

**Comment by msbtterswrth** [comment]
Looks good! I ran the report on prod and I didn't see anymore profiles with empty names.

**Comment by netboss** [comment]
@msbtterswrth @swirtSJW 
Please let me know if there is nothing else needed to close this ticket.
