### ISSUE TITLE
Update VAMC list types training for Claro

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#7931]
## User story
As a VAMC editor, I need to share stories, news releases, or events with Veterans.

## Acceptance Criteria
- [x] record list types training
- [x] caption video
- [x] [replace video on KB](https://prod.cms.va.gov/help/get-training/session-2-editing-basics)

### CMS Team

Please leave only the team that will do this work selected. 

- [ ] `Platform CMS Team`
- [x] `Sitewide CMS Team`
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Offices`
  - [x] `⭐️ Product support`
  - [ ] `⭐️ User support`

**Comment by cmaeng** [comment]
@xiongjaneg fyi, shifting this to sprint 53 for reporting purposes. i think it got future-tagged for sprint 54 but completed early?

**Comment by xiongjaneg** [comment]
@cmaeng yup, I'm gonna finish all of these this sprint, though we hadn't planned them for this sprint.
