### ISSUE TITLE
Make content release time between deploys visible in Datadog

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#7939]
## Description
'How soon will my content be live' is the primary concern of many editors. The time from one deploy to the next is the best measure of this interval we currently have. We should send time of deploy completion to Datadog and surface the time between deploys.

## Acceptance Criteria
- [x] Content release workflow's Deploy job time of completion data is available in Datadog
- [x] A graph is available showing time since last deploy for a given deploy, as a rolling average; optionally with a trend line.
- [x] Filters are available to shape the data visible in the chart

## Additional information
Time since last deploy can sometimes be long for reasons that don't reflect editor experience or platform health:
* The first deploy of the day is typically many hours after the last deploy of the previous day
* Deploys triggered by editor activity come at irregular intervals, especially after business hours

There are a couple options to mitigate this:
* Show timing data as a rolling average
* Provide mechanisms for excluding outliers

Filters for excluding outlier data could consist of
* Exclude weekends
* Exclude deploys outside of business hours / scheduled deploy time
* Exclude time between deploys over a certain duration, and or clamp those values to a sensible upper limit (2 hours?)
* Exclude the time since last deploy for the first deploy of the day, since that will always be high.

Possible approach:
* push an event to datadog during every deploy step if it’s during support hours
* also push a metric to datadog with an identical timestamp that is the difference in time between the last event and the current event, minus 15 hours if it’s the first event on a Tuesday, Wednesday, Thursday, or Friday (5pm to 8am next day) or minus 63 hours if it’s the first event on a Monday
* maybe add a line to the status report page in Drupal that requests the last deploy event from datadog and displays the timestamp + a calculated amount of business time since the last event (maybe do this periodically in the background)

## Justification
Total workflow duration is suspect because it often contains wait time at the beginning as the workflow run waits for a previous run to complete. We cannot rely only on successful runs, because many runs that are marked as cancelled actually result in deploys (see https://github.com/department-of-veterans-affairs/va.gov-cms/issues/7919). Meanwhile, many cancelled jobs *are* in fact cancelled after only a few seconds, which makes including them in averages suspect. 

### CMS Team

Please leave only the team that will do this work selected. 

- [x] `Platform CMS Team`

**Comment by cweagans** [comment]
First PR open here: https://github.com/department-of-veterans-affairs/content-build/pull/989

At least two expected followups after this PR is merged.

**Comment by cweagans** [comment]
Dashboard has been updated with this metric: https://app.datadoghq.com/dashboard/eb9-ece-f9z/platform-cms-prod-cms?from_ts=1645819578000&to_ts=1645828578000&live=true
