### ISSUE TITLE
Update Infrastructure Code to Support SystemD Init Daemon

### ISSUE THREAD

**Issue by olivereri** [department-of-veterans-affairs/va.gov-cms#7988]
## Description

As a DevOps engineer, I need to update infrastructure code to support SystemD commands and unit files for installed software, so that errors are fixed and software installs correctly.

Some portions of the Build process that install binaries assumed Upstart as the init daemon. AL2 uses SystemD as its init daemon and requires different app service configuration. Some of the work required to update the install of binaries was completed in [[cms] Fix or add node_exporter and Promtail systemd service files #10702](https://app.zenhub.com/workspace/o/department-of-veterans-affairs/devops/issues/10702).  

There are still sections of configuration code that use old style Upstart init daemon commands that cause errors in the build process, and during the deploy process. Will need to go through the build and deploy code to add support for SystemD commands and unit files for installed binaries. This will help quiet errors and avoid problems like in [#10702](https://app.zenhub.com/workspace/o/department-of-veterans-affairs/devops/issues/10702)
and [#10713](https://app.zenhub.com/workspace/o/department-of-veterans-affairs/devops/issues/10713)

## Acceptance Criteria
- [x] Build and Deploy Infrastructure code that uses Upstart init daemon commands and service files is found and updated to support SystemD.

## Relations
#7777

## Implementation Details
[#10713](https://app.zenhub.com/workspace/o/department-of-veterans-affairs/devops/issues/10713)
[#10702](https://app.zenhub.com/workspace/o/department-of-veterans-affairs/devops/issues/10702)

**Comment by ElijahLynn** [comment]
Main errors in the init logs are:

```
+ bash setup.sh
[   64.360807] cloud-init[3809]: setup.sh: line 6: initctl: command not found
[   64.361594] cloud-init[3809]: setup.sh: line 10: initctl: command not found
[   64.449250] cloud-init[3809]: Redirecting to /bin/systemctl status awslogs.service
[   64.451293] cloud-init[3809]: Unit awslogs.service could not be found.
[   64.460461] cloud-init[3809]: Redirecting to /bin/systemctl start awslogs.service
[   64.462310] cloud-init[3809]: Failed to start awslogs.service: Unit not found.
[   64.464424] cloud-init[3809]: error reading information on service awslogs: No such file or directory
...
[   65.836911] cloud-init[3809]: setup.sh: line 31: initctl: command not found
[   65.837834] cloud-init[3809]: setup.sh: line 35: initctl: command not found
```

So, I am going to add a new deployment process type of `systemd` and refactor the setup.sh file with some conditionals and appropriate execution of `systemctl` instead of `initctl`. 

I'll also update our DEPLOYMENT_OPTIONS.md file with the new `systemd` type. 

And then I need to figure out why `awslogs` package isn't getting installed with `yum` on AL2. Maybe it isn't needed anymore? I don't think we need it anymore as our logs should all be going to Loki now. So at the least just want to get that part silenced by not executing that role.

**Comment by ElijahLynn** [comment]
> And then I need to figure out why `awslogs` package isn't getting installed with `yum` on AL2. Maybe it isn't needed anymore?

New daemon name is appropriately named `awslogsd` on systemd, so gonna keep it for now.

**Comment by ElijahLynn** [comment]
K, the `awslogs` and `datadog-agent` are now enabled and started by systemd (previously they weren't) and the logs are clean now too. I've updated the docs as well. I've tested this in multiple scenarios. Seeking final review/approval now. https://github.com/department-of-veterans-affairs/devops/pull/10872

**Comment by ElijahLynn** [comment]
Here is the new output, showing the `initctl` errors are gone:

```
/configuration/deployment-vagov-dev-cms-20220310-171314/processes /
[   64.020980] cloud-init[3808]: + bash setup.sh
[   64.071652] cloud-init[3808]: Created symlink from /etc/systemd/system/multi-user.target.wants/awslogsd.service to /usr/lib/systemd/system/awslogsd.service.
[   64.171466] cloud-init[3808]: + popd
[   64.171595] cloud-init[3808]: /
[   64.171734] cloud-init[3808]: + for f in '/configuration/deployment-vagov-dev-cms-20220310-171314/*'
```

**Comment by ElijahLynn** [comment]
This is tested, merged and done :heavy_check_mark: !

I left more testing comments in the PR.
