### ISSUE TITLE
Disable Entity Embed module

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#7995]
## Description

This module is no longer in use and can be disabled and removed.

## Acceptance Criteria
- [x] update hook in va_gov_db uninstalls it (see existing pattern)
- [ ] Entity embed is gone

### CMS Team
Please check the team(s) that will do this work. 

- [ ] `CMS Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide CMS Team ` (leave Sitewide unchecked and check the specific team instead)
  - [x] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Offices`
  - [ ] `⭐️ Product support`
  - [ ] `⭐️ User support`

**Comment by netboss** [comment]
@kevwalsh 
After disabling the Entity Embed module all embed buttons will be gone, which is expected. Are we planning to replace them with other buttons? See CMS prod (still have the embed buttons) and local (without the embed buttons) screen shots.

**Local:**
![VACMS-7995-embed-buttons-local](https://user-images.githubusercontent.com/846871/153903502-aa8ffcac-2200-494b-b19e-d3b104e6fd1e.png)

**CMS prod:**
![VACMS-7995-embed-buttons-cms-prod](https://user-images.githubusercontent.com/846871/153903554-92469e4d-bd60-494a-845c-5265cd7c17dd.png)
