### ISSUE TITLE
Provide top task overview to helpdesk team members

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#7998]
## User story
As a helpdesk team member, I need to refer VAMC editors to top task resources.

## Acceptance Criteria
- [x] Provide overview of top task rollout.
- [x] Review top task Knowledge Base resources.

### CMS Team
Please check the team(s) that will do this work. 

- [ ] `CMS Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide CMS Team ` (leave Sitewide unchecked and check the specific team instead)
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Offices`
  - [x] `⭐️ Product support`
  - [ ] `⭐️ User support`

**Comment by ContentBrewmaster** [comment]
Suzanne and Denise met with Stefanie G. on April 28 in advance of May 5 release.
