### ISSUE TITLE
Provide overview of recurrent events change with Helpdesk team members

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#7999]
## Acceptance Criteria
- [x] Provide an overview of the recurring events update
- [x] Review KB resources on recurring events

### CMS Team
Please check the team(s) that will do this work. 

- [ ] `CMS Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide CMS Team ` (leave Sitewide unchecked and check the specific team instead)
  - [x] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Offices`
  - [ ] `⭐️ Product support`
  - [ ] `⭐️ User support`

**Comment by rachel-kauff** [comment]
Will plan to do this as a Loom video and then follow up with a meeting if necessary.

**Comment by rachel-kauff** [comment]
Part 1: https://www.loom.com/share/05f4830d18824afb86243415edfd4c8e

**Comment by rachel-kauff** [comment]
Part 2: https://www.loom.com/share/3a84e792231749318365417ef3474f7e

**Comment by rachel-kauff** [comment]
Summary:

**Intro to the recurring events feature - for helpdeskers**
**Launch date:** ~tentative March 1
**What:** A feature that allows users to make a series of events that repeats automatically
**Affected users:** VAMC and Outreach Hub
**User communications plan:** 
- Source of truth planning is tracked in [the Change Management airtable](https://airtable.com/appJCOGGJRTAwcH2v/tblPHoElsBWwr83Z0/viwSfROR69D6seBkB/rec5PXTt4W2qJAM1e?blocks=hide)
- Email to all VAMC and Outreach Hub editors
- Message includes a link to this [cms announcement](https://prod.cms.va.gov/help/cms-announcements/new-recurring-events)
- Announcement will link to this KB article: [How to edit an event](https://prod.cms.va.gov/help/cms-basics/how-to-add-a-new-event) (it'll be in draft form until launch, so click on "Latest version" tab to see what it'll say)
- Will also include link to a very short feedback survey
Get a video walkthrough from Kauff:
- [Recurring events part 1](https://www.loom.com/share/05f4830d18824afb86243415edfd4c8e)
- [Recurring events part 2](https://www.loom.com/share/3a84e792231749318365417ef3474f7e)
