### ISSUE TITLE
Resources and Support KB article

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#8002]
## User story
As a Resources and Support editor, I need to know how to use the different kinds of pages and paragraphs on Drupal CMS to provide accurate information to Veterans.

## Acceptance Criteria
- [ ] Review [draft R&S KB article](https://prod.cms.va.gov/help/resources-and-support/a-guide-to-resources-and-support-content-types) for gaps
- [ ] Add relevant information to KB article
- [ ] Review changes
- [ ] Publish article

### CMS Team
Please check the team(s) that will do this work. 

- [ ] `CMS Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide CMS Team ` (leave Sitewide unchecked and check the specific team instead)
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Public Websites`
  - [ ] `⭐️ Product support`
  - [ ] `⭐️ User support`

**Comment by wesrowe** [comment]
@xiongjaneg, we found this in our backlog. Should you be assigned to this ticket?

**Comment by xiongjaneg** [comment]
@wesrowe That's where my little orphan went. I'll take care of it. Thank you!

**Comment by xiongjaneg** [comment]
closing in favor of #8566
