### ISSUE TITLE
Investigate content build slowdown due to code changes between 2021-12-23 and 2022-01-04

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#8011]
## Description
Around Jan 3 2022, the average content build time became approximately 5 minutes slower: https://app.datadoghq.com/dashboard/eb9-ece-f9z/platform-cms-prod-cms?fullscreen_end_ts=1642813745148&fullscreen_paused=false&fullscreen_section=overview&fullscreen_start_ts=1640135345148&fullscreen_widget=7727346438800838&from_ts=1640369100921&to_ts=1643047500921&live=true

There does appear to be some change in GraphQL time at this point, but it does not explain the shift. Taking GraphQL time out of total build time shows that the non-GraphQL time has also jumped: https://app.datadoghq.com/dashboard/gm3-xnt-et5?fullscreen_end_ts=1643047588779&fullscreen_paused=false&fullscreen_section=overview&fullscreen_start_ts=1640369188779&fullscreen_widget=8055303753625958&from_ts=1640369184121&to_ts=1643047584121&live=true

The jump almost certainly happened as we came out of code freeze. Therefore, there is a range of work that could be responsible for the change. This is the full range of commits from 12/23 - 1/5, beginning of code freeze until just beyond: https://github.com/department-of-veterans-affairs/content-build/compare/22763456b64f001903126c2cebe2a38b0fe8c561...4b29aa4bb7405a01fb25255811d545da9fe2d934

We should do timeboxed investigation into this to identify the changes that have caused the slowdown. If fixing the problem is more involved than an hour's work, a follow up ticket should be created with the team which owns the code in question to rectify the problem. 

## Acceptance Criteria
- [ ] The change(s) which are responsible for the slowdown have been identified.
- [ ] A follow-up ticket is created with the team that owns the changes, to fix the issue

## Notes
Neil Hastings did some investigation into this in a previous version of this ticket: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/7724

His results were inconclusive, but pointed towards the queries and rendering of Events. There is some useful information in that ticket, but the AC themselves still need to be met. We currently cannot assign a VFS team to investigate the problem.

### CMS Team

Please leave only the team that will do this work selected. 

- [x] `Platform CMS Team`

**Comment by timcosgrove** [comment]
I looked at this by running content build repeatedly on a local instance, using `git bisect` to test different commits in the larger range. I normalized the timing results by doing these content builds on the weekend / after hours, when the CMS was not under use and thus caching state was consistent. 

Timing was recorded after runs, and then graphed, to look for patterns and changes. That data and corresponding chart is collected here: https://docs.google.com/spreadsheets/d/1po5me3BnkCNDXUs_n6cyPl1ugiduw8OySWZznLrfWsk/edit#gid=0

Screenshot of chart: 
<img width="1309" alt="image" src="https://user-images.githubusercontent.com/203623/156249026-39ee4301-f8e1-46ef-b56e-8fab6ef2d3fa.png">

The change in content build time was narrowed down to this range of commits: https://github.com/department-of-veterans-affairs/content-build/compare/2f91ef313fda59f1e589900fdfb19785c344563e...db4d434d6175a6f3787554247f2169eaa2de728d

The timing change was most prominent in the build step `modifyDom`, here: https://github.com/department-of-veterans-affairs/content-build/blob/master/src/site/stages/build/index.js#L223

**Comment by timcosgrove** [comment]
The `modifyDom` build step contains a number of processes that act on each file's generated HTML and makes changes, including adding nonce to script calls, checking for broken links, etc. The great increase in time for this step pointed to either an increase in complexity or size of the HTML files being generated for parts of the build. 

I began by generating HTML files for builds at both of these commits and then diffing them. This required a bit of work. Some URLs in the builds contained a query parameter with a timestamp, which needed to be eliminated. The size of the built files was approximately 7.8 and 10GB respectively, which meant that diff tools had some difficulty with these comparisons. 

The size difference between the two builds was of course notable. With a bit of investigation, it was possible to find the files that had changed. Nearly all the size change was isolated to the `outreach-and-events` section, and specifically to Event listing files contained there. 

<img width="1390" alt="image" src="https://user-images.githubusercontent.com/203623/156251294-7ce097ea-fc15-4c6a-a6b5-5fb0c62e79f0.png">

This shows a comparison of directories at `outreach-and-events/events`, with the earlier commit on the left and the later commit on the right. It is easily seen that index.html (an Event Listing page) increases in size from 2MB to 23MB, and the same holds true for any Event Listing pages, including those for Past Events.

Looking closely at a pair of these files showed that: 

a) Information about many events (approximately 3800) was being output as JSON directly each HTML file
b) the information was very repetitive, with information being identical for every current Events page, and identical for every Past Events page
c) the amount of information being output increased greatly in the later commit
d) this increase in information size accounted for the entire size increase.

**Comment by timcosgrove** [comment]
As noted in @indytechcook 's [investigation of this issue previously](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/7724#issuecomment-1029154668), the queries that generate this information changed greatly in this period, with many new fields queried and output. This is resulting in the size change we see in the previous comment.

While my analysis did not specifically include profiling `modifyDom` as it acted on each of these specific files, before and after, it is reasonable to guess that being required to process an additional 2.2 GB of DOM would slow down the process, especially as this increased data was concentrated in a small number of files (approximately 115), which would present instances of a much more complicated DOM to parse in these instances.

Moreover, the data is extremely duplicative. The same data is output to all current Event listing pages and to all Past Event listing pages. This data consists of information about all Events the system knows about, printed to every single listing page. Reducing this duplication should be our main action in trying to increase content release speed.

**Comment by timcosgrove** [comment]
As noted, each listing page contained information about approximately 3800 Events. I suspected that if we were able to reduce the number of Events in each of these pages, it would increase content release speed, without any additional code changes. 

After looking at what was published on the site, and consulting with @kevwalsh , we determined that there were Events published on va.gov going back as early as July 2020, and that these Events could be safely archived. Kevin archived all events with an end date older than 6 months in the past, as of yesterday (2022-02-28). 

We then ran content release to see if there was any change. We saw an immediate response, with content release speed decreasing by about 5 minutes on average. 

Content release for the previous day, average of 32.07 minutes:
![image](https://user-images.githubusercontent.com/203623/156257836-7af46333-5c3a-41ec-84d5-2cef59ae6fd5.png)

Content release for the current day, average of 26.67 minutes:
<img width="1466" alt="image" src="https://user-images.githubusercontent.com/203623/156258731-ddc1c2b4-17ba-4b7b-9045-d6620478da14.png">

**Comment by timcosgrove** [comment]
Recommended followups:

1. The JSON data that Events v2 needs to function correctly should be written to its own file. Ideally this would be pulled directly from a public API, but we do not have that mechanism. Given that the data needed for each Event Listing page is largely duplicative, it should be externalized to its own file that all listing pages can draw on.

2. Events may benefit from being autoarchived, based on date. [A ticket is open to explore this](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/4214). This does not solve the underlying problem, but it helps mitigate the slowdown caused by the current output of event data directly into individual HTML pages.

2 (autoarchiving) is only a temporary solution, and does not solve the underlying problem. Moreover, if the number of events increases, we will see a corresponding slowdown unless 1 is addressed.

**Comment by ndouglas** [comment]
Great writeup!
