### ISSUE TITLE
CMS- Lighthouse: service data contains cms specific html

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#8042]
## Describe the defect
When we send html to lighthouse for system services, the system service description data may contain links that are drupal specific, that lighthouse is not going to be able to render.
example:
```
<a data-entity-substitution=\"canonical\" data-entity-type=\"node\" data-entity-uuid=\"30d0a3cb-fd75-47c5-944a-932a0a22d22d\" href=\"\/node\/725\">Learn more about VA VR&amp;E programs<\/a>
```

We need to preprocess these to both 
- [ ] render them as normal links `<a  href="https://prod.cms.va.gov/learn-more">Learn more about VA VR&amp;E programs</a>`
- [ ] Convert them to FE links  `<a  href="https://www.va.gov/learn-more">Learn more about VA VR&amp;E programs</a>`

## Expected behavior
Html sent to lighthouse contains links that will work regardless of where they are output. (can't be relative)

## Additional context
Add any other context about the problem here. Reach out to the Product Managers to determine if it should be escalated as critical (prevents users from accomplishing their work with no known workaround and needs to be addressed within 2 business days).

 
## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Defect")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS workstream (orange) (not needed for bug tickets)
- [ ] CMS-supported product (black)

### CMS Team
Please check the team(s) that will do this work. 

- [ ] `CMS Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide CMS Team ` (leave Sitewide unchecked and check the specific team instead)
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Offices`
  - [ ] `⭐️ Product support`
  - [ ] `⭐️ User support`

**Comment by swirtSJW** [comment]
This has been resolved.  
![image](https://user-images.githubusercontent.com/5752113/154621304-625d222f-dfed-44a9-ab92-ae049b55061b.png)


Just waiting to be merged until  the lighthouse is ready to receive.

**Comment by jilladams** [comment]
Work is done, waiting to be closed when Lighthouse is ready to receive.

**Comment by swirtSJW** [comment]
This code went to prod today.
