### ISSUE TITLE
Move Facility related views displays from content view to Facilities view in #7500

### ISSUE THREAD

**Issue by JayDarnell** [department-of-veterans-affairs/va.gov-cms#8049]
## User Story or Problem Statement

The number of displays attached to the content view have grown substantially, to the point where the view is starting to feel a bit crowded. In #7500 a new Facilities view with three displays was created. We should move any displays related to facilities from the content view to this new Facilities view.

**Displays to be moved**

- [x] Facilities: https://prod.cms.va.gov/admin/content/facilities
- [x] Facilities Export (corresponds to the above facilities view display)
- [x] Facility Status: https://prod.cms.va.gov/admin/content/facility-status
- [x] VAMC System Service Audit: https://prod.cms.va.gov/admin/content/audit/vamc-system-service-audit
- [x] VAMC System Service Audit Export (Corresponds to the above view display)
- [x] VAMC EHR: https://prod.cms.va.gov/admin/content/audit/vamc-ehr

**Redirects**

Any displays receiving a new URL will need a redirect created for it so users visiting the old URLs end up at the new one

- [x] admin/content/facility-status => admin/content/facilities/facility-status
- [x] admin/content/audit/vamc-system-service-audit => admin/content/facilities/vamc-system-service-audit
- [x] admin/content/audit/vamc-ehr => admin/content/facilities/vamc-systems

### CMS Team

Please check the team(s) that will do this work. 

- [ ] `CMS Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide CMS Team ` (leave Sitewide unchecked and check the specific team instead)
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Offices`
  - [x] `⭐️ Product support`
  - [ ] `⭐️ User support`

**Comment by JayDarnell** [comment]
Requested changes from #7500 This is rad. 

A few little things
- [ ] Make Facility exposed filter a dropdown, if it's easy.
  - [ ] If not add, change the label for the filter to "Facility name contains"
- [ ] Make as many fields sortable as possible, especially Service Locations 
- [ ] Remove the Content type column from each view, just to reduce noise. 

Ideally, these three tabs would show up as secondary tabs at /admin/content/facilities (much like "Overview" and "Moderated content" show up at /admin/content, but i'd call this a want not a need.

<details><summary>Screenshot</summary>
<img width="445" alt="Content___VA_gov_CMS" src="https://user-images.githubusercontent.com/643678/154333927-c03a0d92-7a21-42d4-93fb-95e7da3a11f9.png">



</details>

**Comment by swirtSJW** [comment]
@JayDarnell  I am not sure how to read your last comment.   Are you going to be adding them to this PR?
