### ISSUE TITLE
Evaluate system capacity for GET requests

### ISSUE THREAD

**Issue by jkalexander7** [department-of-veterans-affairs/va.gov-cms#8050]
## User Story or Problem Statement

As a CMS engineer, I want to know the current system capacity for GET requests, so that I can determine a baseline and an appropriate measure to set for quarterly OKRs.

Ref: CMS team Q2 2022 Key Result - Infrastructure is able to handle 50 anonymous, cached GET requests per second

## Acceptance Criteria
- [x] One content type is selected to use for measurement
- [x] Determine current maximum number of anonymous GET requests per minute, at current node count (~38k)
 [Outcome](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/8050#issuecomment-1132307507) for anonymous, cached GET requests to Benefits Detail Page:
    | measurement | unit       | 
    | ---                    | ---           |
    | 217                 | second |
    | 13,020            | minute  |
    | 781,200          | hour      |
    | 18,748,800     | day       |

### CMS Team
Please check the team(s) that will do this work. 

- [X] `Platform CMS Team`

**Comment by ElijahLynn** [comment]
Might be good to also get the current average response time as well. I almost wonder if we should set this up as a Datadog synthetic, but not sure DD is setup for load testing like that. But the dashboards would be useful and we could just run the test manually from time to time, or on a schedule to look for scalability regressions.

**Comment by ElijahLynn** [comment]
I worked on this a bit today and am tinkering with the new Goose load testing tool by Tag1Consulting. I can always cobble together a bash script to do this but think we need to use a load testing tool so that we can test over time, as revisions could affect the results. 

https://www.tag1consulting.com/blog/jmeter-vs-locust-vs-goose
https://www.tag1consulting.com/blog/using-goose-troubleshoot-quick-edit
https://www.drupal.org/project/drupal/issues/2950869

I will be OOO through Tuesday and back on Wednesday, and feel confident that this will be done on Wednesday/Thursday.

**Comment by ElijahLynn** [comment]
Benefits Detail (warm cache) is 217 requests/second and 13,020 requests/minute (GET)

Tested from utility vpc (not same server though),infra resources on STAGING are identical to PROD. 
```
[root@ip-172-31-2-26 ~]# ab -n 5000 -c 200 https://staging.cms.va.gov/disability/parent-dic-rates/past-rates-2019/ | grep "Requests per second"
...
Finished 5000 requests
Requests per second:    217.64 [#/sec] (mean)
```

![image](https://user-images.githubusercontent.com/1504756/169422197-497b9213-d60b-4746-b53a-740cde5b8964.png)
![image](https://user-images.githubusercontent.com/1504756/169422219-d8adee32-f12f-46a2-bd36-b27b87a8cc67.png)
![image](https://user-images.githubusercontent.com/1504756/169422215-7f220cab-aa72-4117-bf9d-1a656a6cf4c9.png)

![image](https://user-images.githubusercontent.com/1504756/169422235-435b534c-ecfb-48ab-90cb-c555b35f3270.png)
![image](https://user-images.githubusercontent.com/1504756/169422183-2cc5e114-7f74-47dc-bbbe-a03382ad02c2.png)
![image](https://user-images.githubusercontent.com/1504756/169422227-c003a941-fc46-4c79-8f1d-27c6dcc03a65.png)

![image](https://user-images.githubusercontent.com/1504756/169422203-ff1be941-0504-45c3-bba9-8796c73b7982.png)



![image](https://user-images.githubusercontent.com/1504756/169422210-03e2d1e0-9169-4e03-9739-a6c1a4627e14.png)
