### ISSUE TITLE
Document CMS logging and metrics systems in use

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#8051]
## Description
We have a number of logging and metrics systems which have shifted over recent months. We should document information about them in a single place. This includes but may not be limited to:

* Grafana
* Loki
* Datadog
* Sentry
* Prometheus

## Acceptance Criteria
- [ ] Engineers working on CMS systems are able to find logs and metrics systems quickly and know what they're used for
- [ ] Logging and metrics systems are cataloged in a single location in the CMS repo, including how to access them, what information is sent to them, and any transitions

### CMS Team
Please check the team(s) that will do this work. 

- [ ] `CMS Program`
- [X] `Platform CMS Team`
- [ ] `Sitewide CMS Team ` (leave Sitewide unchecked and check the specific team instead)
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Offices`
  - [ ] `⭐️ Product support`
  - [ ] `⭐️ User support`

**Comment by TheBoatyMcBoatFace** [comment]
Dupe - Covered in #11675
