### ISSUE TITLE
PagerDuty alerts for Content release resolve on their own

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#8057]
## Describe the defect
When we receive PagerDuty creates an incident for a content release failure, the incident auto-resolve after a period of time, even if unacknowledged. The incident needs to stay open until it is acknowledged and resolved by an engineer. 

Incidents currently resolve before they can notify a second engineer.

## To Reproduce

This is only seen in action when an alert is triggered by a failed content build; it can't be simulated. The activity can be clearly seen on incident timelines, however.

Incident that was acknowledged and closed by a human:
https://dsva.pagerduty.com/incidents/Q3AWJTUJ0WIR5O/timeline

Incident that was acknowledged by a human, but then closed automatically by 'Integration API':
https://dsva.pagerduty.com/incidents/Q3A7LGFRXLO0TK/timeline

Incident that was not acknowledged and then closed by 'Integration API':
https://dsva.pagerduty.com/incidents/Q04O2RX8PS7HOD/timeline

## Acceptance Criteria

- [ ] An incident should remain open until it is acknowledged and resolved by a human being
- [ ] If an incident is opened and not acknowledged by the primary engineer within 15 minutes, it should alert the secondary engineer.

 ## Additional context
The Datadog monitor that triggers the incident is here: https://app.datadoghq.com/monitors/62075516

This looks for error events sent from content release. If there is one in the past 10 minutes, the alert triggers.

Previously, the monitor checked for the past 5 minutes, and that was also the time period in which PagerDuty would auto-resolve. After changing the monitor's time period to 10 minutes, the time shifted to 10. This points to Datadog being the system initiating the resolution.

### CMS Team

- [X] `Platform CMS Team`

**Comment by timcosgrove** [comment]
I believe this may have been happening because the conditions that trigger the alert - an error event in the last 5 or 10 minutes - pass, which means the monitor is no longer in a bad state.

I've moved this to 1 hour, which should at least give PagerDuty time to notify the secondary. I don't yet know what will happen if more than one event happens within that time period. I.e, given this sequence of events:

1. Content release fails at 10:30, sending a failure event to Datadog.
2. Because a failure event was sent and there was an event in the past hour, PagerDuty is notified.
3. An engineer resolves the event through PagerDuty.
4. At 10:55 there is another failure event, which means it is still within the hour interval that contains the first error.

Will PagerDuty be alerted a second time? The DataDog monitor will not have resolved at this stage.

**Comment by ElijahLynn** [comment]
We discussed just now that maybe the best way to do this is to go straight from GHA to PD, as opposed to GHA to DD to PD. It was worth a try to do what we did but isn't working exactly as we intend so going to GHA to PD is the way to go here.

**Comment by timcosgrove** [comment]
Started a conversation with Infra about getting an account token: https://dsva.slack.com/archives/CBU0KDSB1/p1647024371758689

**Comment by timcosgrove** [comment]
This is currently blocked until an authorization token is found or generated and installed to SSM. I am having a discussion with Infra support about this.

**Comment by timcosgrove** [comment]
Infra will put this in an upcoming sprint, per this comment: https://github.com/department-of-veterans-affairs/va.gov-team/issues/38580#issuecomment-1072756951

**Comment by cmaeng** [comment]
this has been overcome by events
