### ISSUE TITLE
Investigate occasional build failures due to apparent issues with Remi package server.

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-cms#8067]
## Description

We've seen a few issues along these lines:

```
11:22:35  TASK [build/roles/cms/galaxy/geerlingguy.apache : Ensure Apache is installed on RHEL.] ***
11:22:35  Thursday 17 February 2022  16:22:35 +0000 (0:00:00.051)       0:04:49.986 ***** 
11:22:39  fatal: [ec2-52-61-29-112.us-gov-west-1.compute.amazonaws.com]: FAILED! => changed=false 
11:22:39    msg: 'Failure talking to yum: remi-safe: Check uncompressed DB failed'
11:22:39  
```

This appears to me (a `yum` novice) to be a `yum` protocol-level error, which might be due to infrastructure issues, bugs, load etc on Remi's side.  I'm not sure to what degree (if any) we're still using Remi's packages, so it might be that we could bypass the issue.  We might also ignore errors on those specific repositories with `skip-bad-repos` or `skip-unavailable-repos` or whatever.

When this occurs, developers must manually re-run the job, impacting the developer experience.

## Acceptance Criteria
- [ ] Root cause has been discovered.
- [ ] Root cause has been fixed or a followup issue has been opened to address.

### CMS Team
- [x] `Platform CMS Team`

**Comment by ElijahLynn** [comment]
We should submit an upstream patch to this role with a retry. First step is to create an upstream issue, and also check the latest code, maybe it has already been discussed.
