### ISSUE TITLE
Discovery: Collapsible field design pattern for facility API data

### ISSUE THREAD

**Issue by EWashb** [department-of-veterans-affairs/va.gov-cms#8074]
## Description

As a CMS user, I would like less scrolling within forms that contain facility API data. This data is uneditable by editors but is surfaced within forms. Currently, these fields are not collapsed by default. The hypothesis is that collapsing these areas for editors will allow for less scrolling and a better user experience. 

## Acceptance Criteria
- [ ] Determine all situations where there is API data surfaced for areas within the CMS 
- [ ] Determine if all instances have the uneditable tooltip component
- [ ] Recommend a set of design patterns for all or some use cases
- [ ] Requires design review

### CMS Team
Please check the team(s) that will do this work. 

- [ ] `CMS Program`
- [ ] `Platform CMS Team`
- [x] `Sitewide CMS Team ` (leave Sitewide unchecked and check the specific team instead)
  - [ ] `⭐️ Content ops`
  - [x] `⭐️ CMS experience`
  - [ ] `⭐️ Offices`
  - [ ] `⭐️ Product support`
  - [ ] `⭐️ User support`

**Comment by EWashb** [comment]
One instance of a new pattern is being implemented with ticket #6572

**Comment by EWashb** [comment]
Very old ticket I created that is better suited for facilities, @jilladams  @mmiddaugh feel free to close or do what you'd like with it (of course)

**Comment by Agile6MSkinner** [comment]
A year and a half later, I'm closing it
