### ISSUE TITLE
Send announcement email for recurring events

### ISSUE THREAD

**Issue by rachel-kauff** [department-of-veterans-affairs/va.gov-cms#8079]
ACs
- [x] Draft email content 
- [x] Send to VAMC and Outreach Hub users

**Comment by rachel-kauff** [comment]
Draft email content: https://docs.google.com/document/d/12on6tEZWmidTS_sETmc7kkjQ0yiOHi67GGPWa0rOogk/edit

**Comment by cmaeng** [comment]
pushed back due to delayed release

**Comment by ContentBrewmaster** [comment]
Reassigned to parent epic per Kevin.

**Comment by ContentBrewmaster** [comment]
Updated email:
[2022 - Recurring events email content v2.docx](https://github.com/department-of-veterans-affairs/va.gov-cms/files/8862259/2022.-.Recurring.events.email.content.v2.docx)
