### ISSUE TITLE
KB header search form has weird coloring on certain pages

### ISSUE THREAD

**Issue by tjheffner** [department-of-veterans-affairs/va.gov-cms#8124]
## Description
Unpublished KB pages plop the header search into a white space. It shouldn't look like this 🙈 

issue:
<img width="1472" alt="Screen Shot 2022-02-23 at 11 10 59 AM" src="https://user-images.githubusercontent.com/11279744/155391180-ee57eb12-7e3b-4fde-bfaf-86458d1bedd6.png">
https://prod.cms.va.gov/cms-account-admin-policies/content-api-cms-account-administration-policy

expected:
<img width="1335" alt="Screen Shot 2022-02-23 at 11 11 38 AM" src="https://user-images.githubusercontent.com/11279744/155391185-358b7286-8ba0-486c-b477-a58d22d91f85.png">
https://prod.cms.va.gov/help/cms-account-admin-policies

## Acceptance Criteria
- [ ] Search form in the header looks the same on all KB pages
- [ ] Requires design review

### CMS Team
Please check the team(s) that will do this work. 

- [ ] `CMS Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide CMS Team ` (leave Sitewide unchecked and check the specific team instead)
  - [ ] `⭐️ Content ops`
  - [x] `⭐️ CMS experience`
  - [ ] `⭐️ Offices`
  - [ ] `⭐️ Product support`
  - [ ] `⭐️ User support`

**Comment by laflannery** [comment]
Closing in favor of #12693
