### ISSUE TITLE
Replace events training videos with updated recurring events videos

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#8131]
## Description
Coordinate updating events training videos with recurring events rollout, est. March 1

## Acceptance Criteria
- [ ] [Add VAMC training video to session 2](https://prod.cms.va.gov/help/get-training/session-2-editing-basics)
- [ ] Replace Outreach Hub training video on [training landing page](https://prod.cms.va.gov/help/get-training#available-trainings)
- [ ] Rebuild the training Tugboat environment following the [KB instructions](https://prod.cms.va.gov/help/how-to-access-and-manage-demo-environments) - first verify all recent training completions have been noted in the [training runbook](https://docs.google.com/spreadsheets/d/13jx1rhF5oRLXJNky0ff0zBfE0yR_NUTiAB3oS5T2TpQ) (if still in use)

### CMS Team
Please check the team(s) that will do this work. 

- [ ] `CMS Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide CMS Team ` (leave Sitewide unchecked and check the specific team instead)
  - [x] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Offices`
  - [ ] `⭐️ Product support`
  - [ ] `⭐️ User support`

**Comment by xiongjaneg** [comment]
[VAMC Event video link](https://youtu.be/PYU7eSmlZTc)

**Comment by xiongjaneg** [comment]
waiting for FE issue resolution

**Comment by stefaniefgray** [comment]
Reviewed this ticket; this is blocked until recurring events are rolled out on the live site

Will grab this ticket as soon as they are

**Comment by jilladams** [comment]
I hadn't noticed this ticket so didn't remember to notify Stefanie, but: Recurring events are live as of Monday 6/6!

**Comment by rachel-kauff** [comment]
[This knowledge base article](https://prod.cms.va.gov/help/cms-basics/how-to-edit-an-event) has a shorter video covering recurring events feature specifically, so users do have resources that cover this feature.

Wrt the old Events video in question, the new instructional designer should probably make the call on how to handle the entire Events topic as a whole. Until they come on and we have a program-wide strategy for our approach to video content, KB, and training, Here's what I recommend: 

- I don't recommend re-recording this video. It's 10 minutes long, which would be a large effort. (1:33 of video content took me over an hour).
- I think we should be aiming for a strategy that breaks video content into smaller chunks for maintainability, engagement, and strategic relationship to KB. If we do end up trying to cover all the content in this video, we should do it in smaller pieces.
- For now we should kick this issue over to Sitewide CMS for now where we'll decide whether to archive this outdated content and any potential impacts.
cc: @EWashb @jilladams

**Comment by stefaniefgray** [comment]
^^ Was determined after a meeting 6/15/2022 between @rachel-kauff + @jilladams + @stefaniefgray in regards to this ticket

**Comment by stefaniefgray** [comment]
## Acceptance Criteria:
- [ ] [Add VAMC training video to session 2](https://prod.cms.va.gov/help/get-training/session-2-editing-basics) - Still says "Events are being updated. A new video will be coming soon." on Session 2 page. **Incomplete.**

 - [ ] Replace Outreach Hub training video on [training landing page](https://prod.cms.va.gov/help/get-training#available-trainings) - **Incomplete** -- video at https://www.youtube.com/watch?v=NMfDC5NyWhQ is still outdated
 
 - [ ] Rebuild the training Tugboat environment following the [KB instructions](https://prod.cms.va.gov/help/how-to-access-and-manage-demo-environments) - first verify all recent training completions have been noted in the [training runbook](https://docs.google.com/spreadsheets/d/13jx1rhF5oRLXJNky0ff0zBfE0yR_NUTiAB3oS5T2TpQ) (if still in use) **Can be done at any time as long as training runbook is updated**

Will need to discuss next steps with @EWashb 

Good to break video down into bite-sized pieces so it's not overwhelming, super lengthy, or difficult to update in the future (see Rachel's comment above)

**Comment by stefaniefgray** [comment]
Closing in favor of https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12671
