### ISSUE TITLE
Implement Best Method to Continually Deploy Content-Preview Server

### ISSUE THREAD

**Issue by olivereri** [department-of-veterans-affairs/va.gov-cms#8132]
## Description
The Content Preview server was regularly deployed after each successful run of the Jenkins job [**Pipeline Vets.gov Auto-Deploy for content-build**](http://jenkins.vfs.va.gov/job/deploys/job/vets-gov-autodeploy-content-build/). Now that content builds and releases are handled in Github Actions, the Jenkins job only triggers when done so manually. Because of this the Content Preview server has now become stale and causes issues like this:

https://dsva.slack.com/archives/CDHBKAL9W/p1641571751008600
https://dsva.slack.com/archives/C02HX4AQZ33/p1645655416159389?thread_ts=1645648132.829359&cid=C02HX4AQZ33

## Acceptance Criteria
- [x] Content Preview deployments happen after `Daily Production Deploy` content-build occurs.
- [x] Verify Content Preview synced with Production

## Implementation Details
- A successful production content-build needs to trigger a BRD deployment.
- Can a GHA self-hosted runner trigger a Jenkins job to run?
- Can the content preview server deployment be migrated from BRD to GHA?

**Comment by ElijahLynn** [comment]
WIP PR is here https://github.com/department-of-veterans-affairs/content-build/pull/1048.

**Comment by ElijahLynn** [comment]
This is ready for QA and review, it works!

![image](https://user-images.githubusercontent.com/1504756/160098777-9d77e98f-6884-4a7b-aa66-a449f446b5ac.png)


 https://github.com/department-of-veterans-affairs/content-build/pull/1048

**Comment by ElijahLynn** [comment]
I thought there was a duplicated key in SSM but I was wrong and there isn't, it was in credstash, all is well, this is working great and I'm closing now:

![image](https://user-images.githubusercontent.com/1504756/162411417-d8be96e2-1a28-43a7-902b-c535e079dc43.png)
