### ISSUE TITLE
Create KB Article for Cerner Cutover Process

### ISSUE THREAD

**Issue by EWashb** [department-of-veterans-affairs/va.gov-cms#8146]
## User story
As a CMS admin, I need to understand the process for updating the status of my electronic health records system.

## Acceptance Criteria
- [ ] Create new KB article
- [ ] Add relevant information to KB article

### CMS Team
Please check the team(s) that will do this work. 

- [ ] `CMS Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide CMS Team ` (leave Sitewide unchecked and check the specific team instead)
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Offices`
  - [x] `⭐️ Product support`
  - [ ] `⭐️ User support`

**Comment by xiongjaneg** [comment]
[populated just the CMS admin part ](https://prod.cms.va.gov/electronic-health-records-ehr-system-changes)and left in draft, can be modified and published later for editor content
