### ISSUE TITLE
Require hyphens in phone numbers in EHR telephone field

### ISSUE THREAD

**Issue by ethanteague** [department-of-veterans-affairs/va.gov-cms#8167]
## Description
`VA Health connect phone number` needs to require user to insert hyphens on submit
**No: `9419151811`
Yes: `941-915-1811`**
See admin/structure/types/manage/health_care_region_page/fields/node.health_care_region_page.field_va_health_connect_phone

## Implementation:
Constraint to be added to kick hyphen missing numbers back to user on form submit

## Acceptance Criteria
- [ ] User enters phone number without hyphens on node/318/edit
- [ ] Form validation prevents submit and tells user hyphens are required in `VA Health connect phone number`
- [ ] User enters hyphens in said number
- [ ] Form successfully submits

**Comment by kevwalsh** [comment]
i think we would want a solution that applies to all phone number fields, possibly involving https://www.drupal.org/project/telephone_validation. 

We may want to look at https://www.drupal.org/project/mask as well.

**Comment by kevwalsh** [comment]
See also #7963
