### ISSUE TITLE
Time reporting should not be 24hr format

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#8171]
## Describe the defect
Our Drupal default time formats should not be 24 hr 
![image](https://user-images.githubusercontent.com/5752113/155806715-a2011bca-ecd1-4e88-8fde-ea48bd90f283.png)

Because it leads to confusion and weird displays like 
![image](https://user-images.githubusercontent.com/5752113/155806944-6917499f-685a-46ca-ab9d-b5052c1dcaa3.png)

## Expected behavior
Times should be in 12 hr format with proper use of am pm

## Additional context
Add any other context about the problem here. Reach out to the Product Managers to determine if it should be escalated as critical (prevents users from accomplishing their work with no known workaround and needs to be addressed within 2 business days).

 
## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Defect")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS workstream (orange) (not needed for bug tickets)
- [ ] CMS-supported product (black)

### CMS Team
Please check the team(s) that will do this work. 

- [ ] `CMS Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide CMS Team ` (leave Sitewide unchecked and check the specific team instead)
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Offices`
  - [ ] `⭐️ Product support`
  - [ ] `⭐️ User support`

**Comment by kevwalsh** [comment]
This could be turned into an enhancement, which is to "design standard date formats and syntax across CMS"

**Comment by swirtSJW** [comment]
@netboss  I don't think anything is using it and if it was, cloning it would not solve the problem.  It is the fallback for when nothing is specified.  In order to use the clone it would have to be specified.

**Comment by netboss** [comment]
@swirtSJW 
So this means I can skip it, correct? Just confirming before committing and pushing my other changes.

**Comment by cmaeng** [comment]
@netboss could you point this for velocity purposes please? thanks!

**Comment by netboss** [comment]
> @netboss could you point this for velocity purposes please? thanks!

@cmaeng Done! :)
