### ISSUE TITLE
Missing media preview for docs and pdfs

### ISSUE THREAD

**Issue by rachel-kauff** [department-of-veterans-affairs/va.gov-cms#8186]
Surfaced in [a Claro mob airtable issue](https://airtable.com/applHskzNEaJ4qM7R/tblvm17AmjxYtpwWQ/viw96UBoigqYu3xPL/recIYHRVOPm0CbvRC?blocks=hide).

If a true media preview, it is better to have at least an icon there that shows doc or PDF instead of nothing. See Airtable issue for more details.

ACs
- [ ] Add icon for pdf and doc media
- [ ] Uses placeholder icon for now

**Comment by tjheffner** [comment]
ran this snippet locally in the ddev container, and with @ndouglas help also ran it on staging.cms.va.gov to confirm before running it on prod.cms.va.gov. Default icons are back in place.

```
mkdir -p docroot/sites/default/files/styles/thumbnail/public/media-icons/generic
mkdir -p docroot/sites/default/files/media-icons/generic
cp docroot/core/modules/media/images/icons/* docroot/sites/default/files/media-icons/generic
```
