### ISSUE TITLE
Validate Figma design system with UXers

### ISSUE THREAD

**Issue by rachel-kauff** [department-of-veterans-affairs/va.gov-cms#8188]
We need to test the Figma design system library to validate that it's structured in a way that is usable by other designers on the CMS team. 

Things we want people to be able to do:
- Content-only changes (label change, microcopy, etc.)
- State changes of existing components
- Understand when / how to find an existing pattern vs when they need to do a new thing 
- Group several components together for autolayout

**Figma library rollout to designers**
- Publish - March 2
- Kauff will test first by trying to build the edit form of an entire content type 
   - Can I find the right components?
   - What steps do I need to do to configure the component properties?
   - Pay attention to whether I'm break component into instance vs. using as is
   - What is the best way to organize components?
- Set expectations: ready for training and playing, but will take training to start using for prototyping, cindy available for support at any time
- Figma components 101 training part one
   - What is a component
   - Why is a component - guardrails, iteration
   - Dos and don'ts
   - Find and make an instance
   - Detatch instance
   - It's not stable
   - How to make state changes
   - Activity
- Part two
   - A few days before: send us an example of the last wireframe/prototype situation you worked on. 
   - Demo each of the above things with hand-selected examples

ACs
- [x] [specifics tbd]
- [x] We're ready to publish the Figma design system library so others can start using it.

**Followups to consider**
- How might we make sure it's usable for outside / onboarding cms designers? (return to this when we get to documentation)

**Comment by cjterdi** [comment]
Moved draft version of the CMS DS to the CMS design system project folder in Figma
