### ISSUE TITLE
SPIKE: Research Jira -> Github issue migration

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#820]
## Goal
All issues from Jira are migrated into github issues

## Objectives or Key Results this is meant to further
* <OKR>

## Acceptance Criteria
_The requirements that must be met in order to mark this user story as completed_
* Testable Outcome X
* Testable Outcome Y
* Testable Outcome Z

## Required labels
- [ ] "Product support" (for VSA teams) or "CMS platform" (For core CMS functionality), or "VSP collaboration" for Platform
  - [ ] If product support: which product team (CMS team, Public website team, VAMC upgrade team, etc)
  - [ ] Which CMS-supported product, if any (VAMC, Benefits hubs, Outreach Hub, VA.gov homepage, Media library)
  - [ ] For VSP collaboration: which platform team?, (content-ia-team, devops, design, documentation, frontend, etc)
- [ ] Which CMS component (Content model, Content API, Content Governance, Authoring experience, Media library, Login, Documentation, etc)

## Optional
- [ ] Milestone (when will this be completed?)
- [ ] Attached to an Epic (what body of work is this a part of?)

**Comment by cmaeng** [comment]
This was completed in February of 2020. Moving to Done.
