### ISSUE TITLE
Add KISS documentation

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#8203]
As a FE developer I would like some documentation that I can read to tell me how to add or modify data provided in static json files.

AC:
  - [ ] Documentation exists in content-build repo that a developer can use to understand how to create or modify or remove a static json datafile.

**Comment by ryguyk** [comment]
Closing. This will be covered in https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13823.
