### ISSUE TITLE
Facility closed: Grand Traverse VA Clinic

### ISSUE THREAD

**Issue by JayDarnell** [department-of-veterans-affairs/va.gov-cms#8219]
## Background

**Who are the stakeholders for this?**

- **Section/VISN:** VA Saginaw health care, VISN 10
- **Editor(s):** No Jira tickets found but there is one active editor for VA Saginaw as of 3/8/22: Amanda Gilmore (angela.gilmore1@va.gov)
- **VISN web manager (optional):** None listed on https://prod.cms.va.gov/ for VISN 10
- **Product team member:** 
- **CMS Help desk**

**Associated HD issue, if any**
None found.

#### 1. CMS Help desk
- [x] Becomes aware that the facility is no longer on the Facility API, via the "Facility closed" flag, and create github issue  (Future state: Flag autogenerates github issue)
- [x] If we don't already have context (say, via a HD ticket submitted by an editor), check with editor to find out more about the status of the facility [@todo: write sample email... has a new facility replaced it? has the facility switched to a new system and only appears like it was closed? has the facility status been updated with information about this closure?]
- [x] Fill out the stakeholders in github issue. 

#### 2a. If facility has moved to a new system or merged 
- [ ] Can any of the associated content  (eg services, facility map?) be reused? If so
  - [ ] is there a new facility in VAST/Facility API that content should be moved to?
- [ ] Create [redirect request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=ia&template=redirect-request.md&title=Redirect+Request) to point to URL of new facility.
- [ ] When redirect is ready to go out, plan to make these changes immediately after redirect is released. Practice first on staging or a demo environment. 
  - [ ] CMS engineer bulk moves any content to new facility.
  - [ ] CMS engineer finds the menu for the system https://prod.cms.va.gov/admin/structure/menu and deletes the menu item for the merged facility.

#### 2b. If not 
- [x] Determine where should redirect go? to the system? or to the nearest clinic?
- [x] Create [redirect request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=ia&template=redirect-request.md&title=Redirect+Request) accordingly. 
- [x] When redirect is ready to go out, plan to make these changes immediately after redirect is released. Practice first on staging or a demo environment. 
  - [x] CMS engineer bulk archives the facility service nodes. (https://prod.cms.va.gov/admin/content/bulk?type=health_care_local_health_service).
  - [x] CMS engineer finds the menu for the system https://prod.cms.va.gov/admin/structure/menu and deletes the menu item for the closed facility.
  - [x] CMS engineer filters content by the health care system and scans for any events that might be taking place at that facility. Archive if any are found.
  - [x] CMS engineer edits the facility node, removes  flag `Removed from source`, add a revision log that explains the change, with a link to github issue, and change moderation state to archive.
- [x] Let HD know this is complete. 

#### 3. CMS Help desk
- [ ] Notifies editor and any other stakeholders that this is complete. 

### Vet Center – facility closure [this needs work]
- [ ] CMS team becomes aware that the facility is no longer on the Facility API.
- [ ] CMS team submits [Redirect request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=ia&template=redirect-request.md&title=Redirect+Request), cc'ing Facilities team, and referencing this issue.
- [ ] Once timing of Redirect going live is known, alert CMS engineers to carry out the other steps
- [ ] CMS engineer bulk unpublishes the nodes.
- [ ] CMS engineer removes the Section.
- [ ] CMS engineer edit facility node and remove flag `Removed from source`, sets moderation state to archived, then save node.

## CMS Team
Please check the team(s) that will do this work.

- [ ] `CMS Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide CMS Team ` (leave Sitewide unchecked and check the specific team instead)
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Offices`
  - [x] `⭐️ Product support`
  - [x] `⭐️ User support`

**Comment by JayDarnell** [comment]
@kevwalsh there appears to be a single facility service node for Grand Traverse VA clinic. I feel fairly confident we could archive this. Thoughts?
<img width="1721" alt="Screen Shot 2022-03-03 at 1 39 33 PM" src="https://user-images.githubusercontent.com/21045418/156630816-e68ab70f-d266-4f89-9892-3807536e600a.png">

**Comment by stefaniefgray** [comment]
Remaining Grand Traverse nodes:
- https://prod.cms.va.gov/saginaw-health-care/locations/grand-traverse-va-clinic
- https://prod.cms.va.gov/saginaw-health-care/locations/grand-traverse-va-clinic/primary-care

**Comment by JayDarnell** [comment]
Does not currently have a redirect in place.

**Comment by stefaniefgray** [comment]
https://va-gov.atlassian.net/browse/VAHELP-3824

**Comment by stefaniefgray** [comment]
"Grand Traverse and Traverse City were consolidated into one facility…Colonel Demas T. Craw VA Clinic. 

URL redirect should go back to the nearest VA facility. "

She did not specify which one is the nearest, but it sounds like it should go to the URL for the aforementioned location: https://www.va.gov/saginaw-health-care/locations/colonel-demas-t-craw-va-clinic/

**Comment by stefaniefgray** [comment]
Closed Jira ticket https://va-gov.atlassian.net/browse/VAHELP-3859 for now; will re-open when there are new developments

**Comment by JayDarnell** [comment]
Redirect request created: https://github.com/department-of-veterans-affairs/va.gov-team/issues/39782

**Comment by JayDarnell** [comment]
Archived
