### ISSUE TITLE
Add facility field and filter to events view

### ISSUE THREAD

**Issue by JayDarnell** [department-of-veterans-affairs/va.gov-cms#8221]
## User Story or Problem Statement

As an administrator, it would be helpful to see which facility each event is associated with when making modifications to facility content (archiving facility content when a facility is closed or migrating facility content to a new parent item)

## Acceptance Criteria
- [ ] Add the facility field to the events view /admin/content/events
- [ ] Add the ability to filter the events view by facility

## Design principles

Veteran-centered
- [x] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

### CMS Team
Please check the team(s) that will do this work. 

- [ ] `CMS Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide CMS Team ` (leave Sitewide unchecked and check the specific team instead)
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Offices`
  - [x] `⭐️ Product support`
  - [ ] `⭐️ User support`

**Comment by swirtSJW** [comment]
This takes an event view  that is agnostic to facilities and makes it pretty facility specific.     Being able to filter to a facility by partial string match is interesting... but we have no other pattern like this outside of the facilities subset of views.  The only one that is close is the title search (which this this View probably ought to have), but this behaves pretty differently from that.

Do we want to add this as a facility specific View under facilities and keep this more generic one as it was?
