### ISSUE TITLE
Implement editorial experience for VAMC system decorative images.

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#8235]
ACs

- [ ] Step 1: implement existing tooltip fieldgroup. 
  - [ ] Content admin experience is implemented
    - [ ]  Fields are editable
    - [ ] Tooltip on field group
  - [ ] VAMC editor experience is implemented
    - [ ] Fields are shown as they would be on node display 
    - [ ] Tooltip on field group
- [ ] Step 2: Pass to/collaborate with designers for #8234  
- [ ] Step 3: Update experience based on design iteration. 

See #8233

**Comment by Agile6MSkinner** [comment]
This work is stale. Closing as not planned.
