### ISSUE TITLE
Facility closed: Troy VA Clinic

### ISSUE THREAD

**Issue by JayDarnell** [department-of-veterans-affairs/va.gov-cms#8237]
## Background

**Who are the stakeholders for this?**

- **Section/VISN:** VA Albany health care, VISN 2
- **Editor(s):** No Jira tickets found but there is one active editor for VA Albany as of 3/8/22: Peter Potter (Peter.Potter@va.gov)
- **VISN web manager (optional):** None listed on https://prod.cms.va.gov/ for VISN 2 (was Kathleen Hider, now retired)
- **Product team member:** 
- **CMS Help desk**

**Associated HD issue, if any**
None found.

#### 1. CMS Help desk
- [x] Becomes aware that the facility is no longer on the Facility API, via the "Facility closed" flag, and create github issue  (Future state: Flag autogenerates github issue)
- [x] Fill out the stakeholders in github issue. 
- [x] If we don't already have context (say, via a HD ticket submitted by an editor), check with editor to find out more about the status of the facility 

<details><summary>Email template </summary>

SUBJECT: <facility name> removed from VAST
BODY:

Hi [VAMC editor who owns the node in CMS ]

We see that [name of facility] has been removed from VAST. If this facility has been permanently closed or moved, you can now work with us to unpublish the facility from the CMS and remove it from VA.gov.

Because some Veterans may have bookmarked this Facility, external sites may have linked to it, and because it can take a little time for search engines to catch up to web content, we want to help Veterans not get an error or bad web experience. 

In order to do that we have some questions about the nature of this closure so that we can help redirect Veterans to the right place and understand this change.

1. Was this facility replaced with another facility? 
   If yes, which one?
2. Is there a news release or story about this published on your VAMC website? 
3. Anything else we should know about this facility closure? 

If this facility has been removed from VAST in error, please notify our Support Desk as well as your VAST coordinator.

[outro]
[CMS helpdesk signature] 

</details>

#### 2a. If facility has moved to a new system or merged 
- [ ] Can any of the associated content  (eg services, facility map?) be reused? If so
  - [ ] is there a new facility in VAST/Facility API that content should be moved to?
- [ ] Create [redirect request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=ia&template=redirect-request.md&title=Redirect+Request) to point to URL of new facility.
- [ ] When redirect is ready to go out, plan to make these changes immediately after redirect is released. Practice first on staging or a demo environment. 
  - [ ] CMS engineer bulk moves any content to new facility.
  - [ ] CMS engineer finds the menu for the system https://prod.cms.va.gov/admin/structure/menu and deletes the menu item for the merged facility.

#### 2b. If not 
- [x] Determine where should redirect go? to the system? or to the nearest clinic?
- [x] Create [redirect request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=ia&template=redirect-request.md&title=Redirect+Request) accordingly. 
- [x] When redirect is ready to go out, plan to make these changes immediately after redirect is released. Practice first on staging or a demo environment. 
  - [x] CMS engineer bulk archives the facility service nodes. (https://prod.cms.va.gov/admin/content/bulk?type=health_care_local_health_service).
  - [x] CMS engineer bulk archives the facility non-clinical service nodes. (https://prod.cms.va.gov/admin/content/bulk?type=vha_facility_nonclinical_service).
  - [x] CMS engineer finds the menu for the system https://prod.cms.va.gov/admin/structure/menu and deletes the menu item for the closed facility.
  - [x] CMS engineer filters content by the health care system and scans for any events that might be taking place at that facility. Archive if any are found.
  - [x] CMS engineer edits the facility node, removes  flag `Removed from source`, add a revision log that explains the change, with a link to github issue, and change moderation state to archive.
- [x] Let HD know this is complete. 

#### 3. CMS Help desk
- [ ] Notifies editor and any other stakeholders that this is complete. 

### Vet Center – facility closure [this needs work]
- [ ] CMS team becomes aware that the facility is no longer on the Facility API.
- [ ] CMS team submits [Redirect request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=ia&template=redirect-request.md&title=Redirect+Request), cc'ing Facilities team, and referencing this issue.
- [ ] Once timing of Redirect going live is known, alert CMS engineers to carry out the other steps
- [ ] CMS engineer bulk unpublishes the nodes.
- [ ] CMS engineer removes the Section.
- [ ] CMS engineer edit facility node and remove flag `Removed from source`, sets moderation state to archived, then save node.

## CMS Team
Please check the team(s) that will do this work.

- [ ] `CMS Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide CMS Team ` (leave Sitewide unchecked and check the specific team instead)
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Offices`
  - [x] `⭐️ Product support`
  - [x] `⭐️ User support`

**Comment by JayDarnell** [comment]
@chriscraiga6 Troy VA Clinic has a handful of Facility Health Services tied to it. So this is a decent test for our runbook
<img width="1715" alt="Screen Shot 2022-03-03 at 2 17 29 PM" src="https://user-images.githubusercontent.com/21045418/156636779-cdfd7e40-21d7-45c9-ba2b-f861355bda7c.png">
.

**Comment by stefaniefgray** [comment]
Remaining Troy VA Clinic nodes:
- https://prod.cms.va.gov/albany-health-care/locations/troy-va-clinic
- https://prod.cms.va.gov/albany-health-care/locations/troy-va-clinic/pharmacy (Archived)
- https://prod.cms.va.gov/albany-health-care/locations/troy-va-clinic/mental-health-care
- https://prod.cms.va.gov/albany-health-care/locations/troy-va-clinic/primary-care
- https://prod.cms.va.gov/albany-health-care/locations/troy-va-clinic/smoking-and-tobacco-cessation
- https://prod.cms.va.gov/albany-health-care/locations/troy-va-clinic/laboratory-and-pathology

**Comment by JayDarnell** [comment]
Does not currently have a redirect in place.

**Comment by stefaniefgray** [comment]
https://va-gov.atlassian.net/browse/VAHELP-3825

**Comment by stefaniefgray** [comment]
"I’m glad you responded on this. It’s been several months of trying to reach out to someone who can effect a change. We closed our Troy CBOC, with services being absorbed mostly at our main facility (9 mi away) but also to other nearby CBOCs. I have put in IT ticket, reached out to Drupal and tried the email train to get the Troy CBOC eliminated from our page, but ALL to no avail. Everyone seems to think someone else is responsible, leaving me the only solution of putting information of the closure within the page, which is really unacceptable, but the only thing available at this point. 

We need to have the Troy CBOC page completely erased as it no longer exists. We could easily keep the URL and have it go to our main page, or even if we turned the page into a single message (I can draft) explaining that “services have been realigned to the Albany Stratton VA Medical Center, Clifton Park CBOC or any of our other CBOCs based on Veteran choice” then with a link button to the main facility, where they can connect to the various locations. 

Your help is great appreciated with this. It has really been up far too long and confuses Veterans."

**Comment by JayDarnell** [comment]
@stefaniefgray it sounds like we need a redirect from https://www.va.gov/albany-health-care/locations/troy-va-clinic/ to https://www.va.gov/albany-health-care/ Can you verify that this is correct?

**Comment by stefaniefgray** [comment]
Followed up with Peter in https://va-gov.atlassian.net/browse/VAHELP-3860

**Comment by stefaniefgray** [comment]
@JayDarnell Editor has confirmed that the redirect you described is correct, and that it is okay to archive all of the remaining pages linked to the Troy VA Clinic. Thank you for all of your help!

**Comment by stefaniefgray** [comment]
Closing https://va-gov.atlassian.net/browse/VAHELP-3860 for now; will re-open when there are new developments

**Comment by JayDarnell** [comment]
Thank you @stefaniefgray, I'll generate a redirect request for this item today.

**Comment by JayDarnell** [comment]
Redirect request created: https://github.com/department-of-veterans-affairs/va.gov-team/issues/39778

**Comment by JayDarnell** [comment]
Archived
