### ISSUE TITLE
Facility closed: Vigo County VA Clinic

### ISSUE THREAD

**Issue by JayDarnell** [department-of-veterans-affairs/va.gov-cms#8239]
## Background

**Who are the stakeholders for this?**

- **Section/VISN:** VA Indiana health care, VISN 10
- **Editor(s):** No Jira tickets found but there are 3 active editors for VA Indiana as of 3/8/22 -- Vern Minton (Vern.Minton@va.gov) is our main contact and the source of the original ticket, linked below. He notified the VA Drupal CMS Helpdesk on 12/17/21 that it was the last day for this facility.
- **VISN web manager (optional):** None listed on https://prod.cms.va.gov/ for VISN 10
- **Product team member:** 
- **CMS Help desk**

**Associated HD issue, if any**
https://va-gov.atlassian.net/browse/VAHELP-3135

#### 1. CMS Help desk
- [x] Becomes aware that the facility is no longer on the Facility API, via the "Facility closed" flag, and create github issue  (Future state: Flag autogenerates github issue)
- [ ] Fill out the stakeholders in github issue. 
- [ ] If we don't already have context (say, via a HD ticket submitted by an editor), check with editor to find out more about the status of the facility 

<details><summary>Email template </summary>

SUBJECT: <facility name> removed from VAST
BODY:

Hi [VAMC editor who owns the node in CMS ]

We see that [name of facility] has been removed from VAST. If this facility has been permanently closed or moved, you can now work with us to unpublish the facility from the CMS and remove it from VA.gov.

Because some Veterans may have bookmarked this Facility, external sites may have linked to it, and because it can take a little time for search engines to catch up to web content, we want to help Veterans not get an error or bad web experience. 

In order to do that we have some questions about the nature of this closure so that we can help redirect Veterans to the right place and understand this change.

1. Was this facility replaced with another facility? 
   If yes, which one?
2. Is there a news release or story about this published on your VAMC website? 
3. Anything else we should know about this facility closure? 

If this facility has been removed from VAST in error, please notify our Support Desk as well as your VAST coordinator.

[outro]
[CMS helpdesk signature] 

</details>

#### 2a. If facility has moved to a new system or merged 
- [ ] Can any of the associated content  (eg services, facility map?) be reused? If so
  - [ ] is there a new facility in VAST/Facility API that content should be moved to?
- [ ] Create [redirect request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=ia&template=redirect-request.md&title=Redirect+Request) to point to URL of new facility.
- [ ] When redirect is ready to go out, plan to make these changes immediately after redirect is released. Practice first on staging or a demo environment. 
  - [ ] CMS engineer bulk moves any content to new facility.
  - [ ] CMS engineer finds the menu for the system https://prod.cms.va.gov/admin/structure/menu and deletes the menu item for the merged facility.

#### 2b. If not 
- [x] Determine where should redirect go? to the system? or to the nearest clinic?
- [x] Create [redirect request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=ia&template=redirect-request.md&title=Redirect+Request) accordingly. 
- [x] When redirect is ready to go out, plan to make these changes immediately after redirect is released. Practice first on staging or a demo environment. 
  - [x] CMS engineer bulk archives the facility service nodes. (https://prod.cms.va.gov/admin/content/bulk?type=health_care_local_health_service).
  - [x] CMS engineer bulk archives the facility non-clinical service nodes. (https://prod.cms.va.gov/admin/content/bulk?type=vha_facility_nonclinical_service).
  - [x] CMS engineer finds the menu for the system https://prod.cms.va.gov/admin/structure/menu and deletes the menu item for the closed facility.
  - [x] CMS engineer filters content by the health care system and scans for any events that might be taking place at that facility. Archive if any are found.
  - [x] CMS engineer edits the facility node, removes  flag `Removed from source`, add a revision log that explains the change, with a link to github issue, and change moderation state to archive.
- [x] Let HD know this is complete. 

#### 3. CMS Help desk
- [ ] Notifies editor and any other stakeholders that this is complete. 

### Vet Center – facility closure [this needs work]
- [ ] CMS team becomes aware that the facility is no longer on the Facility API.
- [ ] CMS team submits [Redirect request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=ia&template=redirect-request.md&title=Redirect+Request), cc'ing Facilities team, and referencing this issue.
- [ ] Once timing of Redirect going live is known, alert CMS engineers to carry out the other steps
- [ ] CMS engineer bulk unpublishes the nodes.
- [ ] CMS engineer removes the Section.
- [ ] CMS engineer edit facility node and remove flag `Removed from source`, sets moderation state to archived, then save node.

## CMS Team
Please check the team(s) that will do this work.

- [ ] `CMS Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide CMS Team ` (leave Sitewide unchecked and check the specific team instead)
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Offices`
  - [x] `⭐️ Product support`
  - [x] `⭐️ User support`

**Comment by JayDarnell** [comment]
Vigo County VA Clinic has a single Facility Health Service attached to it: 
<img width="1724" alt="Screen Shot 2022-03-03 at 2 25 59 PM" src="https://user-images.githubusercontent.com/21045418/156638113-a0cbf5a6-aea1-430f-8392-f23b0e924ff1.png">

**Comment by stefaniefgray** [comment]
Remaining nodes, both published:
- https://prod.cms.va.gov/indiana-health-care/locations/vigo-county-va-clinic
- https://prod.cms.va.gov/indiana-health-care/locations/vigo-county-va-clinic/mental-health-care

**Comment by JayDarnell** [comment]
Does not currently have a redirect in place.

**Comment by stefaniefgray** [comment]
https://va-gov.atlassian.net/browse/VAHELP-3828

**Comment by stefaniefgray** [comment]
"The Vigo County Clinic has merged with the new [Terre Haute VA Clinic](https://www.va.gov/indiana-health-care/locations/terre-haute-va-clinic/). The Vigo County Clinic is now closed. 

The redirected URL should go to the Terre Haute VA Clinic: https://www.va.gov/indiana-health-care/locations/terre-haute-va-clinic/ 

Thank you for your attention to this need."

@JayDarnell Is there any additional info needed from this editor before we can proceed?

**Comment by JayDarnell** [comment]
@stefaniefgray I think all we need to know at this point is whether the mental health care node for Vigo County VA Clinic (linked above) should be migrated to Terre Haute VA Clinic or if we just archive it.

**Comment by JayDarnell** [comment]
Redirect request created: https://github.com/department-of-veterans-affairs/va.gov-team/issues/39558

**Comment by stefaniefgray** [comment]
Followed up with Vern in https://va-gov.atlassian.net/browse/VAHELP-3862 and asked whether the mental health care node should be migrated to Terre Haute or archived

**Comment by stefaniefgray** [comment]
https://prod.cms.va.gov/indiana-health-care/locations/vigo-county-va-clinic/mental-health-care should be archived, not assigned to Terre Haute

Closing VAHELP-3862 for now and will re-open if needed

**Comment by JayDarnell** [comment]
Archived

**Comment by stefaniefgray** [comment]
Emailed editor https://va-gov.atlassian.net/browse/VAHELP-3862
