### ISSUE TITLE
Facility closed: South Parklane VA Clinic

### ISSUE THREAD

**Issue by JayDarnell** [department-of-veterans-affairs/va.gov-cms#8243]
## Background

**Who are the stakeholders for this?**

- **Section/VISN:** VA Wichita health care, VISN 15
- **Editor(s):** No Jira tickets found but there is one active editor for VA Wichita as of 3/8/22: Jeffrey Herndon (Jeffrey.Herndon@va.gov)
- **VISN web manager (optional):** Eric Hernandez (Eric.Hernandez2@va.gov)
- **Product team member:** 
- **CMS Help desk**

**Associated HD issue, if any**
None found.

#### 1. CMS Help desk
- [x] Becomes aware that the facility is no longer on the Facility API, via the "Facility closed" flag, and create github issue  (Future state: Flag autogenerates github issue)
- [x] Fill out the stakeholders in github issue. 
- [x] If we don't already have context (say, via a HD ticket submitted by an editor), check with editor to find out more about the status of the facility 

<details><summary>Email template </summary>

SUBJECT: <facility name> removed from VAST
BODY:

Hi [VAMC editor who owns the node in CMS ]

We see that [name of facility] has been removed from VAST. If this facility has been permanently closed or moved, you can now work with us to unpublish the facility from the CMS and remove it from VA.gov.

Because some Veterans may have bookmarked this Facility, external sites may have linked to it, and because it can take a little time for search engines to catch up to web content, we want to help Veterans not get an error or bad web experience. 

In order to do that we have some questions about the nature of this closure so that we can help redirect Veterans to the right place and understand this change.

1. Was this facility replaced with another facility? 
   If yes, which one?
2. Is there a news release or story about this published on your VAMC website? 
3. Anything else we should know about this facility closure? 

If this facility has been removed from VAST in error, please notify our Support Desk as well as your VAST coordinator.

[outro]
[CMS helpdesk signature] 

</details>

#### 2a. If facility has moved to a new system or merged 
- [ ] Can any of the associated content  (eg services, facility map?) be reused? If so
  - [ ] is there a new facility in VAST/Facility API that content should be moved to?
- [ ] Create [redirect request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=ia&template=redirect-request.md&title=Redirect+Request) to point to URL of new facility.
- [ ] When redirect is ready to go out, plan to make these changes immediately after redirect is released. Practice first on staging or a demo environment. 
  - [ ] CMS engineer bulk moves any content to new facility.
  - [ ] CMS engineer finds the menu for the system https://prod.cms.va.gov/admin/structure/menu and deletes the menu item for the merged facility.

#### 2b. If not 
- [x] Determine where should redirect go? to the system? or to the nearest clinic?
- [x] Create [redirect request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=ia&template=redirect-request.md&title=Redirect+Request) accordingly. 
- [x] When redirect is ready to go out, plan to make these changes immediately after redirect is released. Practice first on staging or a demo environment. 
  - [x] CMS engineer bulk archives the facility service nodes. (https://prod.cms.va.gov/admin/content/bulk?type=health_care_local_health_service).
  - [x] CMS engineer bulk archives the facility non-clinical service nodes. (https://prod.cms.va.gov/admin/content/bulk?type=vha_facility_nonclinical_service).
  - [x] CMS engineer finds the menu for the system https://prod.cms.va.gov/admin/structure/menu and deletes the menu item for the closed facility.
  - [x] CMS engineer filters content by the health care system and scans for any events that might be taking place at that facility. Archive if any are found.
  - [x] CMS engineer edits the facility node, removes  flag `Removed from source`, add a revision log that explains the change, with a link to github issue, and change moderation state to archive.
- [x] Let HD know this is complete. 

#### 3. CMS Help desk
- [ ] Notifies editor and any other stakeholders that this is complete. 

### Vet Center – facility closure [this needs work]
- [ ] CMS team becomes aware that the facility is no longer on the Facility API.
- [ ] CMS team submits [Redirect request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=ia&template=redirect-request.md&title=Redirect+Request), cc'ing Facilities team, and referencing this issue.
- [ ] Once timing of Redirect going live is known, alert CMS engineers to carry out the other steps
- [ ] CMS engineer bulk unpublishes the nodes.
- [ ] CMS engineer removes the Section.
- [ ] CMS engineer edit facility node and remove flag `Removed from source`, sets moderation state to archived, then save node.

## CMS Team
Please check the team(s) that will do this work.

- [ ] `CMS Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide CMS Team ` (leave Sitewide unchecked and check the specific team instead)
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Offices`
  - [x] `⭐️ Product support`
  - [x] `⭐️ User support`

**Comment by JayDarnell** [comment]
There are 4 services attached to this facility:
<img width="1714" alt="Screen Shot 2022-03-03 at 2 41 16 PM" src="https://user-images.githubusercontent.com/21045418/156640510-2e4e7dc1-86cc-464d-ade8-b81669d923b6.png">

**Comment by stefaniefgray** [comment]
Remaining nodes, as shown above:
- https://prod.cms.va.gov/wichita-health-care/locations/south-parklane-va-clinic
- https://prod.cms.va.gov/wichita-health-care/locations/south-parklane-va-clinic/primary-care
- https://prod.cms.va.gov/wichita-health-care/locations/south-parklane-va-clinic/optometry
- https://prod.cms.va.gov/wichita-health-care/locations/south-parklane-va-clinic/ophthalmology

**Comment by JayDarnell** [comment]
Does not currently have a redirect in place.

**Comment by stefaniefgray** [comment]
https://va-gov.atlassian.net/browse/VAHELP-3831

**Comment by stefaniefgray** [comment]
"I brought this up when our new websites first went live and the only answer was that the CMS pulls the information from VAST. I knew this to be inaccurate because my VAST Coordinator assured me neither of those facilities were in VAST any longer. 

We closed the Liberal CBCOC in November 2020. The South Parklane VA Clinic was never a clinic, as we know it and was not on our old website. I have no idea how it appeared on the new sit because it was only an administrative space our Office of Community Care (OCC) and Home-Based Primary Care (HBPC) staff worked out of. The bottom line, though, is that it is not in the VAST system. 

You’d be my best friend forever if you can get those locations quickly removed from our website. Thank you."

**Comment by stefaniefgray** [comment]
VA Drupal CMS Helpdesk: "If the South Parklane VA Clinic isn’t actually a VA clinic, what is/was the official title of this location? Is it officially closed?" 

Editor: "I don’t know how names get assigned, but that was the name assigned in the VAST system. It is officially closed, the lease was terminated, and patients were never seen in that location because of the nature of the office (admin space)."

VA Drupal CMS Helpdesk: "If someone attempts to access the South Parklane page, where should they be redirected?"

Editor:  " https://www.va.gov/wichita-health-care/ "

**Comment by JayDarnell** [comment]
Redirect request: https://github.com/department-of-veterans-affairs/va.gov-team/issues/39556

**Comment by stefaniefgray** [comment]
Closed https://va-gov.atlassian.net/browse/VAHELP-3865 for now to clear queue but will re-open when there are new developments

**Comment by JayDarnell** [comment]
Archived

**Comment by stefaniefgray** [comment]
Emailed editor https://va-gov.atlassian.net/browse/VAHELP-3865
