### ISSUE TITLE
Facility closed: Lake Avenue VA Clinic

### ISSUE THREAD

**Issue by JayDarnell** [department-of-veterans-affairs/va.gov-cms#8244]
## Background

**Who are the stakeholders for this?**

- **Section/VISN:** VA Central Western Massachusetts health care, VISN 1
- **Editor(s):** No Jira tickets found but only active editor is sarah.robinson1@va.gov
- **VISN web manager (optional):** VISN 1: russell.tippets@va.gov
- **Product team member:** 
- **CMS Help desk**

**Associated HD issue, if any**
None found.

#### 1. CMS Help desk
- [x] Becomes aware that the facility is no longer on the Facility API, via the "Facility closed" flag, and create github issue  (Future state: Flag autogenerates github issue)
- [ ] Fill out the stakeholders in github issue. 
- [ ] If we don't already have context (say, via a HD ticket submitted by an editor), check with editor to find out more about the status of the facility 

<details><summary>Email template </summary>

SUBJECT: <facility name> removed from VAST
BODY:

Hi [VAMC editor who owns the node in CMS ]

We see that [name of facility] has been removed from VAST. If this facility has been permanently closed or moved, you can now work with us to unpublish the facility from the CMS and remove it from VA.gov.

Because some Veterans may have bookmarked this Facility, external sites may have linked to it, and because it can take a little time for search engines to catch up to web content, we want to help Veterans not get an error or bad web experience. 

In order to do that we have some questions about the nature of this closure so that we can help redirect Veterans to the right place and understand this change.

1. Was this facility replaced with another facility? 
   If yes, which one?
2. Is there a news release or story about this published on your VAMC website? 
3. Anything else we should know about this facility closure? 

If this facility has been removed from VAST in error, please notify our Support Desk as well as your VAST coordinator.

[outro]
[CMS helpdesk signature] 

</details>

#### 2a. If facility has moved to a new system or merged 
- [ ] Can any of the associated content  (eg services, facility map?) be reused? If so
  - [ ] is there a new facility in VAST/Facility API that content should be moved to?
- [ ] Create [redirect request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=ia&template=redirect-request.md&title=Redirect+Request) to point to URL of new facility.
- [ ] When redirect is ready to go out, plan to make these changes immediately after redirect is released. Practice first on staging or a demo environment. 
  - [ ] CMS engineer bulk moves any content to new facility.
  - [ ] CMS engineer finds the menu for the system https://prod.cms.va.gov/admin/structure/menu and deletes the menu item for the merged facility.

#### 2b. If not 
- [x] Determine where should redirect go? to the system? or to the nearest clinic?
- [x] Create [redirect request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=ia&template=redirect-request.md&title=Redirect+Request) accordingly. 
- [x] When redirect is ready to go out, plan to make these changes immediately after redirect is released. Practice first on staging or a demo environment. 
  - [x] CMS engineer bulk archives the facility service nodes. (https://prod.cms.va.gov/admin/content/bulk?type=health_care_local_health_service).
  - [x] CMS engineer bulk archives the facility non-clinical service nodes. (https://prod.cms.va.gov/admin/content/bulk?type=vha_facility_nonclinical_service).
  - [x] CMS engineer finds the menu for the system https://prod.cms.va.gov/admin/structure/menu and deletes the menu item for the closed facility.
  - [x] CMS engineer filters content by the health care system and scans for any events that might be taking place at that facility. Archive if any are found.
  - [x] CMS engineer edits the facility node, removes  flag `Removed from source`, add a revision log that explains the change, with a link to github issue, and change moderation state to archive.
- [x] Let HD know this is complete. 

#### 3. CMS Help desk
- [ ] Notifies editor and any other stakeholders that this is complete. 

### Vet Center – facility closure [this needs work]
- [ ] CMS team becomes aware that the facility is no longer on the Facility API.
- [ ] CMS team submits [Redirect request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=ia&template=redirect-request.md&title=Redirect+Request), cc'ing Facilities team, and referencing this issue.
- [ ] Once timing of Redirect going live is known, alert CMS engineers to carry out the other steps
- [ ] CMS engineer bulk unpublishes the nodes.
- [ ] CMS engineer removes the Section.
- [ ] CMS engineer edit facility node and remove flag `Removed from source`, sets moderation state to archived, then save node.

## CMS Team
Please check the team(s) that will do this work.

- [ ] `CMS Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide CMS Team ` (leave Sitewide unchecked and check the specific team instead)
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Offices`
  - [x] `⭐️ Product support`
  - [x] `⭐️ User support`

**Comment by JayDarnell** [comment]
There are three services attached to this facility: 
<img width="1722" alt="Screen Shot 2022-03-03 at 2 44 10 PM" src="https://user-images.githubusercontent.com/21045418/156640970-a563e3b0-8c85-4e26-831a-4e06a4eba447.png">

**Comment by stefaniefgray** [comment]
Remaining nodes (as shown above, all published):
- https://prod.cms.va.gov/central-western-massachusetts-health-care/locations/lake-avenue-va-clinic
- https://prod.cms.va.gov/central-western-massachusetts-health-care/locations/lake-avenue-va-clinic/mental-health-care
- https://prod.cms.va.gov/central-western-massachusetts-health-care/locations/lake-avenue-va-clinic/dermatology
- https://prod.cms.va.gov/central-western-massachusetts-health-care/locations/lake-avenue-va-clinic/cardiology

**Comment by JayDarnell** [comment]
Does not currently have a redirect in place.

**Comment by stefaniefgray** [comment]
https://va-gov.atlassian.net/browse/VAHELP-3832

**Comment by stefaniefgray** [comment]
Closed https://va-gov.atlassian.net/browse/VAHELP-3866 for now, will re-open when there are new developments

**Comment by JayDarnell** [comment]
Redirect request created: https://github.com/department-of-veterans-affairs/va.gov-team/issues/39780
