### ISSUE TITLE
Non-content admins should not be able to access Content Audit Tools view

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#8268]
## Describe the defect
Only content admins should be able to see http://prod.cms.va.gov/admin/content/audit

This is not a security issue, just clutters the UI unnecessarily for non-content admins. 

## To Reproduce
1. As admin, go to /admin/structure/views/view/content/edit/content_audit_page
2. See that Content editor, reviewer, publisher, redirect admin, and account admin all have access

## Expected behavior
Only Content admin and ~CMS account~ admin should have access

## Screenshots 
<img width="715" alt="Content__Content____VA_gov_CMS" src="https://user-images.githubusercontent.com/643678/156864737-d43ab11b-a9f5-4744-8eb6-1d7f5f09906e.png">

### CMS Team
Please check the team(s) that will do this work. 

- [ ] `CMS Program`
- [ ] `Platform CMS Team`
- [x] `Sitewide CMS Team ` (leave Sitewide unchecked and check the specific team instead)
  - [x] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Offices`
  - [ ] `⭐️ Product support`
  - [ ] `⭐️ User support`

**Comment by netboss** [comment]
@kevwalsh 
The screen shot above shows "CMS account admin" as not allowed but then in the "Expected behavior" section is this 

> Only Content admin and **CMS account admin** should have access

Question is, should the **CMS account admin** role have access or not to that **Content Audit Tools** view?

**Comment by kevwalsh** [comment]
@netboss good catch, that's a typo, fixed the AC!

**Comment by netboss** [comment]
@kevwalsh 
This is ready for review, PR: https://github.com/department-of-veterans-affairs/va.gov-cms/pull/8355
