### ISSUE TITLE
Clean up media menu items

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#8274]
## Describe the defect

We have two menu items under the the Content menu that go to the same place: Media and Media Library

We have two menu items under the Content menu with the same label "Media Library", which go to differnet places.

The Files menu item lost its home under Media

## To Reproduce
1. Click on the 3 menu items under Content with the word "media" in them. 

## Expected behavior

We should have only one menu item under Content with the word "media"

Other items should be children of Media. 

Ideally, this is the IA

```
Media
* Add media (with all its children)
* Images
* PDFs
* Files
* Bulk media edit
```

If we can emulate Jay's menu item approach to Facilities, that would be ideal. One differences is that a number of these menu items are defined by Drupal Core (Media, Add media and its children, and Files). 

## Screenshots 

<img width="849" alt="Cursor_and_Media_-_images___VA_gov_CMS" src="https://user-images.githubusercontent.com/643678/157062701-eaccc71a-ceb0-4231-8c99-ca4deca26b31.png">

### CMS Team
Please check the team(s) that will do this work. 

- [ ] `CMS Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide CMS Team ` (leave Sitewide unchecked and check the specific team instead)
  - [x] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Offices`
  - [ ] `⭐️ Product support`
  - [ ] `⭐️ User support`

**Comment by kevwalsh** [comment]
Huh, i have a memory of it in being in a tab.

And the config for the views menu  suggests some tab-like behavior.

<img width="488" alt="Files__File____VA_gov_CMS" src="https://user-images.githubusercontent.com/643678/157084951-55a66f5a-cc9d-4172-b395-c1e9a40971d3.png">

But yeah, i think just tucking in under Media is fine for now.

**Comment by msbtterswrth** [comment]
@kevwalsh I'll move it in! It _is_ currently in a tab under content (since this view existed before media was in core). Thanks for catching this!
