### ISSUE TITLE
Spike: entity revisions

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#829]
We need a spike for this user story: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/830

Explore contrib modules for revisions on non-node entity types. 

Create PR environment with everything enabled for evaluation by Mike C and possibly Randi H.

**Comment by ethanteague** [comment]
Spike was to create the thing - I'm gonna call this done.

**Comment by swirtSJW** [comment]
Re-opened as it solves a need.
