### ISSUE TITLE
User Research Methodology

### ISSUE THREAD

**Issue by valerierunde** [department-of-veterans-affairs/va.gov-cms#8292]
## Acceptance Criteria
- [ ] Research the tools available to the team to determine if we already have licenses.
- [ ] If a tool is available, determine the methodology of user testing.

### CMS Team
Please check the team(s) that will do this work. 

- [ ] `CMS Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide CMS Team ` (leave Sitewide unchecked and check the specific team instead)
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [X] `⭐️ Offices`
  - [ ] `⭐️ Product support`
  - [ ] `⭐️ User support`

**Comment by wesrowe** [comment]
pausing due to pivot to home page work
