### ISSUE TITLE
Taxonomy revisions UI broken for existing taxonomy terms

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#830]
## Background

#829 / #7725 added revision UI for all entity types other than node.  

Per @swirtSJW 's [comment](https://github.com/department-of-veterans-affairs/va.gov-cms/pull/7775#issuecomment-1023628871), looking at revisions for existing terms results in an error. Creating a new term, then looking at revisions, works fine. 

See also [this comment](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/830#issuecomment-1023664939) containing a hunch for how to fix this. 

## Old issue description 

~In D8.7, taxonomy terms became revisionable. But they are not ready for content moderation yet, until [this issue](https://www.drupal.org/project/drupal/issues/3047110) gets completed:~

~As a manager of a taxonomy (Sections, VHA health services, etc), i want to see who made edits to a taxonomy term, so that i can _blame_ them.~ 

## AC: 
 - [ ] As an content_admin  ~editor~ of a taxonomy (Health services taxonomy, VBA services taxonomy, Sections taxonomy etc) i want to 
    - [ ] see the content editing and moderation history 
    - [ ] revert if needed to older versions, just like nodes.
~On cms.va.gov/section/veterans-affairs i see a History and Revisions tab, just like on a node view.~
- [ ]  content_admin needs to be able see and revert revisions on all taxonomies.
- [ ] content_publisher should nto be able to edit, delete, or create health service taxonomy terms (from comment below)

## No longer required
- [ ] ~On taxonomy term revisions pages, a block appears~
```
<h3>Known issues with revisions for taxonomy terms</h3>
<ul>
  <li>Not all revisions created prior to February 2022 will appear here.</li>
  <li>Some older revisions may be missing their timestamp (the date the term was edited).</li> 
  <li>A revision without a timestamp can not compared (diff’ed) to a newer revision.</li>
  <li>It is not possible to revert to revisions that do not have a timestamp.</li>
</ul> 
```
- [ ] ~Design review on taxonomy/term/{tid}/revisions tab~

**Comment by swirtSJW** [comment]
This can and should be handled by drupal/entity_diff_ui and the taxonomy submodule  However there is a problem  https://github.com/department-of-veterans-affairs/va.gov-cms/pull/7775#issuecomment-1023628871

I believe the module makes an assumption about the time being there even though it would not be there for existing terms because revisions were not previously on.   

**hunch without facts:**  Look for  call to createFromTimestamp() within  the module or submodule and see if we can contrib a patch to make it more defensive.   I have not investigated it enough to log an issue on the module page yet.  Needs more investigation I don't have time to perform right now.

**Comment by swirtSJW** [comment]
Moving the goalpost on this ticket slightly as the perms side of this needs adjusting.
- [ ] content_admin needs to be able see and revert revisions on all taxonomies.

Also we need to remove these perms (in red)  from content publisher.
![image](https://user-images.githubusercontent.com/5752113/152039212-d7b8c659-b5e6-4854-b21b-6e04618a746f.png)

**Comment by ethanteague** [comment]
@swirtSJW @kevwalsh updated the role perms, removed the patch, and added an update script that can be fired like so:
`lando drush scr ./scripts/content/VACMS-830-taxonomy_term_revisions_fix.php `
After it runs, term page timestamps / revisions seem to be working as expected (e.g.: `taxonomy/term/73/revisions`) but we will wanna do some more testing.

I'm assuming we no longer need to add a `Known Issues` block, but lemme know if this assumption is incorrect.

**Comment by kevwalsh** [comment]
Amazing. And i like that this means we're not carrying that tech or UX debt forward.

**Comment by swirtSJW** [comment]
@ethanteague  We'll need to get someone with access to run this script on prod, right after the deploy

**Comment by swirtSJW** [comment]
Expected output from running the script  
![image](https://user-images.githubusercontent.com/5752113/153620987-4ba33b21-51e7-484d-bc0a-a9d8b000338b.png)

**Comment by swirtSJW** [comment]
Script has been run on prod 
![image](https://user-images.githubusercontent.com/5752113/153676421-07827d15-e76d-46b3-8bd1-ba268be6f19e.png)

**Comment by ndouglas** [comment]
Output from prod:

```
[cms@ip-<redacted> cms]$ drush scr ./scripts/content/VACMS-830-taxonomy_term_revisions_fix.php
Processed terms... 25 / 144.
Processed terms... 50 / 144.
Processed terms... 75 / 144.
Processed terms... 100 / 144.
Processed terms... 125 / 144.
Term updates complete. 144 / 144
```

**Comment by swirtSJW** [comment]
![image](https://user-images.githubusercontent.com/5752113/153679333-d901be2a-1c10-40a2-ae94-9c04f62c3715.png)
