### ISSUE TITLE
Design improved UX for overriding facility hours within a service location

### ISSUE THREAD

**Issue by EWashb** [department-of-veterans-affairs/va.gov-cms#8302]
## User story

As a VAMC editor of a facility service (health service or administrative service), I need to clearly understand what I can do within the "hours" section. 

We believe this experience is confusing. The field label repeats the first dropdown value, and labels could be improved more generally. And editors may not understand the implications of each option. 

 ![Screen Shot 2022-03-04 at 10.36.13 AM.png](https://images.zenhubusercontent.com/614b6cbe05afafb268be4c0b/0516ddf5-81cf-4542-8fcd-abedefec77cd)

How might we improve this? 
- Improve labels for field and dropdowns
- Show facility hours when "Use facility hours" is selected, possibly reusing pattern from Facility COVID status. 
- Increase the padding for hours and spacing between components to match the CMS DS guidelines
- Match the layout for hours with the front end.

<details><summary>pattern from Facility COVID status</summary>

![image](https://user-images.githubusercontent.com/643678/174661621-c00600da-4fd7-4844-860e-73d301b0aab9.png)

</details>

## Acceptance criteria

- [x] Correct label for "Use facility's hours" to be more accurate for the dropdown
- [x] Replace "Use facility's hours" with "Hours"
- [x] Replace "Additional Hours options" with "Additional Information" and explore better parenthetical information
- [x] Review dropdown text for accuracy
- [x] CMS DS component review
- [x] Dev review

**Comment by EWashb** [comment]
## User story
As a VAMC editor, I need to understand what I can do within the "hours" section more clearly. 

Currently, the following label does not accurately tell you what the action is for the dropdown. ![Screen Shot 2022-03-04 at 10.36.13 AM.png](https://images.zenhubusercontent.com/614b6cbe05afafb268be4c0b/0516ddf5-81cf-4542-8fcd-abedefec77cd)

## Acceptance criteria
- [ ] Correct label for "Use facility's hours" to be more accurate for the dropdown
- [ ] Replace "Use facility's hours" with "Hours"
- [ ] Replace "Additional Hours options" with "Additional Information" and explore better parenthetical information
- [ ] Dev review

**Comment by kevwalsh** [comment]
this has been deprioritized for now, in favour of #9522. Moving back to refined.

**Comment by cjterdi** [comment]
Assigned Suzanne for labels and help text review

**Comment by laflannery** [comment]
@suzanne-gray & @cjterdi I reviewed the Figma files as requested and have a few comments.  Let me know if you would like to discuss any of these:

- The caption text (5b616b) against the white background only has a contrast ratio of 6.23:1.  We are aiming for AAA in this instance so we should hit 7:1 ideally.  I had previously looked at the caption/help text and created [this ticket](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10070) but obviously that was just a suggestion based on the color options I had seen in the DS
- Placeholder text, while not something I would generally recommend, also needs to meet contrast requirements.  Currently in the Figma file the ratio on the time fields is only 1.66:1
- Can you clarify the note in you have in 3 for me, where you say "Remove label and caption heading for radio buttons"?  I don't see anything incorrect with what you have but I also want to be sure that radio buttons always have labels, I'm confused by this note and unsure what is getting removed.

**Comment by laflannery** [comment]
Thanks @cjterdi Pretty sure I understand now. I reviewed the core radio buttons in the List(text) field using my demo Drupal site and those were marked up appropriately

**Comment by suzanne-gray** [comment]
Design review happened on 8/8/22. [Annotated design file](https://www.figma.com/file/i3dqsSu3ZXtDdlGFNVns7G/Facility-hours?node-id=2%3A6947) is ready in figma. 

The improvements to the CMS hours widget that are noted in the design file will be implemented separately in #10092
