### ISSUE TITLE
Investigate CMS Prod Piv Login Issues

### ISSUE THREAD

**Issue by olivereri** [department-of-veterans-affairs/va.gov-cms#8309]
## Description
For the past 2-3 weeks we've been seeing a small increase in PIV Login issues. These have been directed to the Enterprise Service Desk however tickets to the Enterprise Service Desk end up back  in our queue.  We now have two users from VHA Digital Media who are having PIV Login issues.

![image.png](https://images.zenhubusercontent.com/5f04cf8f49978b1615fee8c2/13c189aa-7845-49ae-af3f-dc8fd433fb3b)https://files.slack.com/files-pri/T03FECE8V-F0371BL3WD6/image.png

Slack discussion:
https://dsva.slack.com/archives/CT4GZBM8F/p1646849358029919

## Acceptance Criteria

- [ ] Investigate cause of PIV login issues for specific users:
- Robin.Baker@va.gov
- Elizabeth.Smolder@va.gov

## Tasks

- Investigate root cause of PIV login issues for listed users.
- Fix if possible, otherwise involve external teams that can help resolve and/or create follow-on issues.

**Comment by olivereri** [comment]
Full debug info after Drupal account was deleted and recreated.
![image](https://user-images.githubusercontent.com/31904439/158224709-21772f6e-477e-4cd3-b2f8-bc40d799b4e8.png)

**Comment by stefaniefgray** [comment]
See VAHELP-3895 on Jira re: Elizabeth Smolder

**Comment by olivereri** [comment]
Alerting has been created around this:
https://app.datadoghq.com/monitors/68230394

Monitoring can be seen here:
https://app.datadoghq.com/apm/traces?saved-view-id=864662

**Comment by TheBoatyMcBoatFace** [comment]
Closing. @olivereri reopen if necessary.
