### ISSUE TITLE
Revision history for blocks, media, and taxonomy

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#832]
## User Story or Problem Statement

As an editor of a taxonomy (Health services taxonomy, VBA services taxonomy, Sections taxonomy etc), Media (images, videos, etc) and blocks (alerts, promos, etc) i want to see the content editing and moderation history revert if needed to older versions, just like nodes.

**Comment by swirtSJW** [comment]
It seems like https://github.com/department-of-veterans-affairs/va.gov-cms/pull/7775 will handle all of the issues except Taxonomy - #830
