### ISSUE TITLE
Postmortem: Investigate root cause of CMS outage on March 11 & mitigate problem

### ISSUE THREAD

**Issue by cweagans** [department-of-veterans-affairs/va.gov-cms#8335]
## Describe the defect
CMS went down when the deployment on Friday went out.

## To Reproduce
Deploy the CMS on or after March 11

## Acceptance Criteria
- [x] CMS should not go down
- [x] Post-mortem documented

 ## Additional context
* https://dsva.slack.com/archives/CT4GZBM8F/p1647031793691209
* https://docs.google.com/document/d/1qacI1C8B9Z40ULSYdcGmxlqlGc0wR0JhctDKd_tBRBw/edit

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Defect")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS workstream (orange) (not needed for bug tickets)
- [ ] CMS-supported product (black)

### CMS Team
Please check the team(s) that will do this work. 

- [ ] `CMS Program`
- [x] `Platform CMS Team`
- [ ] `Sitewide CMS Team ` (leave Sitewide unchecked and check the specific team instead)
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Offices`
  - [ ] `⭐️ Product support`
  - [ ] `⭐️ User support`

**Comment by ElijahLynn** [comment]
Yesterday, we successfully deployed with the same CMS code that caused an outage but with revert of systemd code that enabled `awslogsd` and `datadog-agent`. 

There was load just before the deploy that caused the outage so it does seem to be externally caused and had something to do with a cache:rebuild and cache stampede of sorts. So we may still be vulnerable to this scenario again.

**Comment by ElijahLynn** [comment]
Discussed on scrum just now: We are going to do a partial revert of https://github.com/department-of-veterans-affairs/devops/pull/10915 and remove the `awslogsd` process from the defaults for the systemd AMIs. We really only need `datadog-agent`.

**Comment by ElijahLynn** [comment]
Postmortem completed and merged, lives here now > https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Postmortems/2022-03-11-cms-deployment-outage.md

Follow up issue created to handle more load at #8443.
