### ISSUE TITLE
[spike?] Improve responsiveness for small screen sizes

### ISSUE THREAD

**Issue by rachel-kauff** [department-of-veterans-affairs/va.gov-cms#8336]
Several editors mentioned problems with responsiveness for small screen sizes in the Claro survey feedback. 

"The CMS no longer adjusts for smaller screen sizes and you have to scroll side to side to see and entire field."

"can't resize the CMS window for side-by-side editing."

- Set an demo environ to old theme to compare
- How small is small? (~mobile~, tablet, etc?)
- Standard issue gov laptop: Clarence's is 13 in - 1080
- Side by side ~ tablet portrait?
- Suspects:
   - Right rail stacking into one column
- Related: editors missing the required sections field in the right rail because it's hard to find - make decisions about how to place the sections field

ACs
- [ ] Investigate problem elements
- [ ] A fix that's neutral or better than D7

**Comment by tjheffner** [comment]
using this tugboat environment set to the old theme: https://main-bdlgiqihelj9wkr6nz4ighchafpdqltv.demo.cms.va.gov/node/27770/edit
and my local (or any other environment) to compare: 

<img width="757" alt="Screen Shot 2022-03-24 at 11 14 23 AM" src="https://user-images.githubusercontent.com/11279744/159983750-67df3e4e-9fcc-47c1-95ad-7b54ca1abef6.png">
<img width="830" alt="Screen Shot 2022-03-24 at 11 14 33 AM" src="https://user-images.githubusercontent.com/11279744/159983755-c3fa0c79-8fdb-45ee-a959-834759d94c4e.png">
<img width="508" alt="Screen Shot 2022-03-24 at 11 14 47 AM" src="https://user-images.githubusercontent.com/11279744/159983759-7ea7f6d5-302c-47f5-82eb-e68aab942bd3.png">
<img width="1013" alt="Screen Shot 2022-03-24 at 11 15 18 AM" src="https://user-images.githubusercontent.com/11279744/159983766-ed04f6b6-37de-4b8c-a236-cd5c3a49f943.png">
<img width="936" alt="Screen Shot 2022-03-24 at 11 15 31 AM" src="https://user-images.githubusercontent.com/11279744/159983768-ed186bf6-2d8d-45e6-a7dd-52a73bb76f19.png">
<img width="764" alt="Screen Shot 2022-03-24 at 11 15 38 AM" src="https://user-images.githubusercontent.com/11279744/159983773-4ed6b9ae-1fee-4609-893f-c0c917f8312f.png">

screenshots (attempt to) show that claro is forcing the column to wrap ~150px 
larger than the old theme did, likely the source of the issue for editors. The right rail required fields are definitely more apparent when the column is right next to the main content. A lot of fields bust out of their containers at these lower sizes too.

Follow up tasks:
- Fix breakpoint for layout wrapping
- Fix fields busting out of container on lower screen sizes. Look at `node/27770/edit` for example
- Potentially make right rail required fields more obvious at larger screen sizes.

**Comment by rachel-kauff** [comment]
@tjheffner Would you prefer the followup tasks to be in one ticket, or separate?

**Comment by tjheffner** [comment]
@rachel-kauff the first two should be for the same ticket, i think the third is a different issue personally
