### ISSUE TITLE
Home page - hard-code blog Promo with CTA liquid template and component 

### ISSUE THREAD

**Issue by allisonlu** [department-of-veterans-affairs/va.gov-cms#8359]
## Description
For [Steps 2 of Home page iteration](https://www.sketch.com/s/58c718b6-196f-4b6a-a433-fb2a65d7a4d2/a/jgzJvvm), we have a promo "banner" with a CTA link with a blue background. There is currently nothing (that we know of) that is on the website that resembles this component.

The current promo component is only being used on landing pages. See `promo.drupal.liquid` template in **content-build** repo.

Per Ryan Thurlwell:

> the promo component (or molecule) in this orientation might be new, but it is made up of stock components (atoms) and design system utilities (like the flexbox grid). this team will be responsible for building, documenting, and validating it.

- There exists a ["Action link" component](https://design.va.gov/experimental-design/action_links) on design.va.gov, BUT it is currently an experimental design. Caveat emptor. 
- It has been determined that we should build the two-CTA version of the blog CTA component in this round of development. For reference, see the [Sketch file](https://sketch.com/s/3aa40506-4be2-46cc-876b-93f1a9f3a857) artboards "First build" and "First build - mobile." Desktop and mobile versions:
<img width="982" alt="image" src="https://user-images.githubusercontent.com/4054752/165987332-ca627559-3496-47d1-86e3-1025255ae640.png">
<img width="262" alt="image" src="https://user-images.githubusercontent.com/4054752/165987965-9d30dbc7-d681-418f-82a5-3567f1e4e005.png">

NOTE ON IMAGE PROPORTIONS: To minimize the risk of the layout breaking on screens of different widths, usability testing will be done with a 3:4 aspect ratio.

## Assumptions
- Image links will be to images of the correct aspect ratio, using the existing blog aspect ratio ([design decision](https://dsva.slack.com/archives/C52CL1PKQ/p1650311648396159?thread_ts=1650303669.576559&cid=C52CL1PKQ))
  - UPDATE: the VAntage Point blog home page seems to force all images into a 1.82:1 ratio, although actual assets vary greatly. Therefore, Editors should probably have an existing expectation that their images will be cropped to 1.82:1. 
- A single image will be served for all screen sizes
- The person entering text will follow governance for each field (Val provided in sketch file [link tbd])

## Acceptance Criteria
- [ ] Hard-coded (no CMS required)
- [ ] "externalize" actual content and image link to a separate JS file (markdown, json, etc) for simple editing by non-engineer
- [ ] **Images** - blog image of any aspect ratio is cropped to 1.8:1 with no stretching; pixels cropped evenly from left and right or top and bottom as appropriate
- [ ] Develop responsive for desk and mobile (and tablet?) breakpoints
- [ ] Requires design review

### CMS Team
Please check the team(s) that will do this work. 

- [ ] `CMS Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide CMS Team ` (leave Sitewide unchecked and check the specific team instead)
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [x] `⭐️ Offices`
  - [ ] `⭐️ Product support`
  - [ ] `⭐️ User support`

**Comment by wesrowe** [comment]
@davidconlon, please review the Assumptions added above.

**Comment by jilladams** [comment]
Per [discussion](https://dsva.slack.com/archives/C52CL1PKQ/p1650311648396159?thread_ts=1650303669.576559&cid=C52CL1PKQ) with Ryan Thurlwell & Val Rundle, the images in this CTA should  be pulled from blog images from Wordpress, and use the same aspect ratio. When this ticket is assigned, if that direction needs more clarification, please schedule a short meeting with Val and either Jill (if in office) or Wes (if not), to clear it up.

**Comment by wesrowe** [comment]
@allisonlu @ryguyk, Please have a look at the image cropping verbiage under ACs above and check that implementation should be possible.

**Comment by jilladams** [comment]
Design review with Ryan Thurlwell today. 
1. Sketch now uses the 1.81:1 aspect ratio used by VAntage blog images. 
2. Ryan is not married to this aspect ratio, and we could opt to use Facebook sharing image dimensions instead, etc. We can finalize after user testing.
3. We will need to be thoughtful about how text wrap at different breakpoints to the right of the image affects the height of this section (before it stacks on a mobile display)
4. Though text will be hard coded for now, eventually (post user testing) we would ideally survey existing OPIA content and propose a hard limit on character count for text area, using an ~iPad-sized breakpoint, which will help optimize desktop & mobile presentation. 

Notes mapped to design areas on the homepage in[ Homepage design review Mural](https://app.mural.co/t/vagov6717/m/vagov6717/1650408594492/7245d261b15a8a1efc05c2a47e08d6f96cd61871?sender=u252e7152800e3981889d1910)
@wesrowe anything you want to add?

**Comment by mmiddaugh** [comment]
Thank you @wesrowe - looks good given what I know today.

**Comment by allisonlu** [comment]
@jilladams @wesrowe @mmiddaugh do we know where these CTAs link to? (for now)

**Comment by mmiddaugh** [comment]
HGetting these exactly right isn't necessary at this point but we do want them to be functional and reasonably accurate. 
I suggest linking 
- "See all VA news" to VAntage Point at https://blogs.va.gov/VAntage/
- "Get housing assistance now" to VA Homeless Programs website at http://www.va.gov/homeless/

**Comment by allisonlu** [comment]
PR opened on `content-build` repo: https://github.com/department-of-veterans-affairs/content-build/pull/1111

**Comment by allisonlu** [comment]
PR opened on `vets-website`: https://github.com/department-of-veterans-affairs/vets-website/pull/20973

**Comment by allisonlu** [comment]
Both PRs have been approved and ready to be merged into the corresponding Homepage iteration feature branch on each repo.
