### ISSUE TITLE
Home page - Implement Search functionality on new homepage block

### ISSUE THREAD

**Issue by allisonlu** [department-of-veterans-affairs/va.gov-cms#8362]
## Description
For [Step 3 of Home page iteration](https://www.sketch.com/s/58c718b6-196f-4b6a-a433-fb2a65d7a4d2/a/dlP7YYL), we will be replacing top tasks hub links with a condensed list of links, along with a Search input. This issue only involves the functionality of the Search.

- This is a blocker for #8361
- Clarify what user journey will be
   - What will the search results look like? Same as site-wide search
   - Will it redirect users to a new results page? Same as site-wide search
   - Will it act like typeahead and display all matching results as user types? Same as site-wide search

### CMS Team
Please check the team(s) that will do this work. 

- [ ] `CMS Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide CMS Team ` (leave Sitewide unchecked and check the specific team instead)
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [x] `⭐️ Offices`
  - [ ] `⭐️ Product support`
  - [ ] `⭐️ User support`

**Comment by jilladams** [comment]
In case useful, from Napoleon video dump, there's one related to Search functionality: https://drive.google.com/drive/u/1/folders/1g0Hdq3ttHiTSF75XYUMf0jIndPuq-_nu

Video notes on it so far, in line 8: https://docs.google.com/spreadsheets/d/137Cbp9sPriuUnXVY_O16_ASIWMqYdjZL9JBe1xkzuDA/edit#gid=0

**Comment by jilladams** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VAgov-CMS-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/8362?planning-poker) with ZenHub @allisonlu @ryguyk

**Comment by allisonlu** [comment]
PR opened on `vets-website`: https://github.com/department-of-veterans-affairs/vets-website/pull/21136

PR opened on `content-build`: https://github.com/department-of-veterans-affairs/content-build/pull/1138

**Comment by allisonlu** [comment]
PRs are merged into feature branches in both repos
