### ISSUE TITLE
Jenkins content build job fails.

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-cms#8380]
## Description
Jenkins content build does not run; it fails with an access error.

## Acceptance criteria
- [x] `content-build-content-only-vagovprod` job runs without failure
- [x] Running this job results in freshly builtc content deployed to va.gov

## Describe the defect
After a profound and prolonged outage with GitHub Actions, I [requested a content build from within Jenkins](http://jenkins.vfs.va.gov/job/builds/job/content-build-content-only-vagovprod/1940/console).  It however failed:

```
10:32:07  Step 1 of 54 start: Get Drupal content
10:32:07  Drupal content unavailable in local cache: /application/.cache/vagovprod/drupal/pages.json
10:32:07  Attempting to load Drupal content from API at http://internal-dsva-vagov-prod-cms-2000800896.us-gov-west-1.elb.amazonaws.com/
10:32:07  Pulling from Drupal via GraphQL...
....
10:32:07  Error: HTTP error: 403: Forbidden
10:32:07      at Object.query (/application/src/site/stages/build/drupal/****.js:120:13)
10:32:07      at processTicksAndRejections (internal/process/task_queues.js:93:5)
10:32:07      at async Object.getAllPagesViaIndividualGraphQlQueries (/application/src/site/stages/build/drupal/****.js:128:28)
10:32:07      at async getContentViaGraphQL (/application/src/site/stages/build/drupal/metalsmith-drupal.js:218:19)
10:32:07      at async loadDrupal (/application/src/site/stages/build/drupal/metalsmith-drupal.js:261:23)
10:32:07      at async Ware.<anonymous> (/application/src/site/stages/build/drupal/metalsmith-drupal.js:316:20)
10:32:07  npm ERR! code ELIFECYCLE
10:32:07  npm ERR! errno 1
10:32:07  npm ERR! content-build@1.0.0 build: `node --max-old-space-size=5000 --expose-gc script/build-content.js "--verbose" "--buildtype=vagovprod" "--asset-source=eaf3635b70c4804bb887ac150a19f1ffbbb98b48" "--drupal-address=http://internal-dsva-vagov-prod-cms-2000800896.us-gov-west-1.elb.amazonaws.com/" "--pull-drupal" "--drupal-max-parallel-requests=15" "" ""`
```

This would suggest missing or insufficient credentials, perhaps as a result of recent changes to the Drupal API username and password.

The Jenkins job is currently the only practical fallback when content builds cannot be invoked via GitHub Actions.

**Comment by olivereri** [comment]
Checkout what I found in Jenkins!
![image.png](https://images.zenhubusercontent.com/5f04cf8f49978b1615fee8c2/c351b805-64ac-4d97-b967-a68ef28d97b7)

**Comment by olivereri** [comment]
Section of Groovy code Jenkins jobs uses to fetch credentials.
https://github.com/department-of-veterans-affairs/content-build/blob/014a40c3c30ba678603c6155ac206d3420fd683e/jenkins/common.groovy#L197
