### ISSUE TITLE
Build a user journey map for new R&S editors

### ISSUE THREAD

**Issue by suzanne-gray** [department-of-veterans-affairs/va.gov-cms#8385]
## Description
The teamsite migration for Resources and Support is a complex process, and one that will be replicated for many users in the near future. Creating a user journey map based on the pilot program research will:
*  give us a birds-eye view of the whole process
* help us identify pain points and uncover solutions
* offer a road map for the upcoming resources & support migration
* contribute to our overall understanding of the site editor experience. 

The journey map will be based on surveys and interviews with members of the R&S pilot group.   

## Acceptance Criteria
- [ ] Draft user journey map is complete
- [ ] Design review by UX team members
- [ ] Journey map is finalized
- [ ] Final journey map has been shared with PO and Sitewide Content team members

### CMS Team
Please check the team(s) that will do this work. 

- [ ] `CMS Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide CMS Team ` (leave Sitewide unchecked and check the specific team instead)
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Offices`
  - [X] `⭐️ Product support`
  - [ ] `⭐️ User support`

**Comment by FranECross** [comment]
Per Dave Conlon's suggestion, closing:

I recommend that we audit a lot of these issues and close several as "not doing". Instead, I think we need to pivot to a "CLP 2.0", discovery, etc. especially in light of the 21st c. idea act guidance.
