### ISSUE TITLE
Audit rich text fields for use of usa-button

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#8404]
As a Sitewide content team and CMS Content Ops team, i have an understanding of where buttons exist in rich text editors, so that i can make some decisions how and when deprecate them, and which ones should be replaced with action links. 

ACs
- [x] Sitewide content team and CMS Content Ops team we have a shared understanding of where buttons have been used
   - [x] By product (Benefits Hubs, VAMC, etc)
     - [x] By content type

**Comment by msbtterswrth** [comment]
An audit has been created in [airtable](https://airtable.com/appKBH3vnMNXAaBCY/tbloIvQGYN6vq2Ow0/viwbJUIJRYvVu3ok6?blocks=bipJql9fyL6Puf3s6) with views by both section and content type.
