### ISSUE TITLE
Assess APM measurement-driven enhancements

### ISSUE THREAD

**Issue by jkalexander7** [department-of-veterans-affairs/va.gov-cms#8408]
## User Story or Problem Statement

Implementing application performance monitoring in Datadog allows for deeper insights on overall system performance. The CMS team will conduct analysis on the current state of the system and identify areas for improvement.

## Acceptance Criteria

- [x] Review performance tests are conducted to establish baseline state
- [x] Lower-performing sections of code are identified for improvements
- [x] Followup tickets are created to implement performance enhancements
  - #8695
  - #8685

### CMS Team
Please check the team(s) that will do this work. 

- [ ] `CMS Program`
- [x] `Platform CMS Team`
- [ ] `Sitewide CMS Team ` (leave Sitewide unchecked and check the specific team instead)
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Offices`
  - [ ] `⭐️ Product support`
  - [ ] `⭐️ User support`

**Comment by olivereri** [comment]
![image.png](https://images.zenhubusercontent.com/5f04cf8f49978b1615fee8c2/b4cf720e-117c-4b85-a5ac-05d977787d72)

**Comment by olivereri** [comment]
Enabling logs we can do some correlation:
![image.png](https://images.zenhubusercontent.com/5f04cf8f49978b1615fee8c2/1fa7820a-9970-418e-84b3-b9efe7d02764)

**Comment by olivereri** [comment]
Process logging:
https://docs.datadoghq.com/infrastructure/process/?tab=linuxwindows#installation

**Comment by olivereri** [comment]
In the future, Datadog may have the ability to identify lower-performing sections of PHP code.
![image.png](https://images.zenhubusercontent.com/5f04cf8f49978b1615fee8c2/387483d7-bbc2-4724-903f-601f6b3afee0)

**Comment by olivereri** [comment]
Profiler doesn't seem support analysis of PHP code.
![image.png](https://images.zenhubusercontent.com/5f04cf8f49978b1615fee8c2/0ab66c26-8252-451b-afe2-e0a4c1338151)

**Comment by olivereri** [comment]
https://www.datadoghq.com/blog/monitor-php-performance/#auto-instrumented-frameworks-and-libraries
```
Support is coming soon for integration with Wordpress, Magento, Drupal, DynamoDB, RabbitMQ, Doctrine ORM, and many more.
```

**Comment by olivereri** [comment]
Suggested monitors based off of trace data sent:

![image.png](https://images.zenhubusercontent.com/5f04cf8f49978b1615fee8c2/49e08b79-3519-40f4-b295-095ced946766)
[Here](https://app.datadoghq.com/apm/service/vagov-cms/symfony.request?env=brd-prod&monitorPanel=true&topGraphs=latency%3Alatency%2CbreakdownAs%3Aabsolute%2Cerrors%3Acount%2Chits%3Acount&start=1649109730000&end=1649113330000&paused=true)

**Comment by olivereri** [comment]
I think this applies to the `DD_VERSION` variable, which isn't set in config code. Should use latest CMS release tag to populate it:

![image.png](https://images.zenhubusercontent.com/5f04cf8f49978b1615fee8c2/25f960f2-3218-4f02-84e6-8422a523ee66)

**Comment by olivereri** [comment]
![image.png](https://images.zenhubusercontent.com/5f04cf8f49978b1615fee8c2/96f90ec6-8c00-4ba0-a410-9b9fdf2ab80b)

![image.png](https://images.zenhubusercontent.com/5f04cf8f49978b1615fee8c2/20f69a40-db3d-45b9-a64e-92e75a033e7d)

**Comment by olivereri** [comment]
## APM Configuration Improvements:
- Evaluate Datadog APM Database Monitoring. This is on top of Database traces already provided. [Documentation](https://docs.datadoghq.com/database_monitoring/setup_mysql/rds/?tab=mysql56)
- Correlate traces with logs by injecting `trace_id` and `span_id` in to Drupal logs. [Documentation](https://docs.datadoghq.com/tracing/connect_logs_and_traces/?tab=java)
- Correlate traces with server-side processes. [Documentation](https://docs.datadoghq.com/infrastructure/process/?tab=linuxwindows#installation)
- Configure APM to track deployments. Dynamically (deploy time) Configure `DD_VERSION` HTTPd Environment variable to be the `va.gov-cms` release tag of code running on the server.
