### ISSUE TITLE
Rough-draft content governance / guard rails (intent and specs)

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#8409]
## Description
Draft content governance rules for all elements on new Home Page, down through and including the Top Tasks grid.

This rough draft would prepare us for a meeting with the Sitewide Content team (Beth, Danielle, Mikki).

## Acceptance Criteria
- [ ] Draft complete and viewable here: _________ (accessible by VA employees)

### CMS Team
Please check the team(s) that will do this work. 

- [ ] `CMS Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide CMS Team ` (leave Sitewide unchecked and check the specific team instead)
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [x] `⭐️ Offices`
  - [ ] `⭐️ Product support`
  - [ ] `⭐️ User support`

**Comment by valerierunde** [comment]
Access the Mural board here: https://app.mural.co/invitation/mural/vagov6717/1649169375121?sender=u0f6a693f731ee0b19ea13269&key=5779827f-33ae-4977-ac5b-e634afe87ec3

PDF export:
[Homepage Governance and Guidelines.pdf](https://github.com/department-of-veterans-affairs/va.gov-cms/files/8453274/Homepage.Governance.and.Guidelines.pdf)

**Comment by wesrowe** [comment]
@valerierunde, this looks really good for desktop, thank you. I wonder if you could add some context to the Mural board to discuss your methods? I love how you linked out to design system pages, for example, so the design system would be an item under Sources.
Another thing it would be helpful to clarify is your process, especially whether you took the mobile designs into account also. That will save the next person who picks this up a lot of work, as opposed to evaluating the mobile design from scratch for themselves.
