### ISSUE TITLE
Discovery: Architect how to publish a prod mirror with our updated content

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#8412]
## Description

This issue is to get us to the point of understanding how we'll get our experimental site up on a publicly available subdomain of VA.gov. Requirements include:
- Our custom content
- Header, footer, and banners need to mirror prod and be updated in parallel to prod
- All links out to other pages will return user to prod  

## Acceptance Criteria
- [ ] Document the plan at a high level (somewhere accessible by VA employees)

### CMS Team
Please check the team(s) that will do this work. 

- [ ] `CMS Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide CMS Team ` (leave Sitewide unchecked and check the specific team instead)
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [x] `⭐️ Offices`
  - [ ] `⭐️ Product support`
  - [ ] `⭐️ User support`

**Comment by jilladams** [comment]
Prototype was ultimately staged at https://staging.va.gov/homepage-test. Closing. If we need to reopen, holler.
