### ISSUE TITLE
Add type-ahead to Search component (behavior exactly like search in header)

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#8416]
## Description
Enhance the search component with type-ahead. (See other implementations on live site for UX, etc., especially the [Search Results page](https://www.va.gov/search/?query=test&t=false).

## Acceptance Criteria
- [ ] Search works
- [ ] Requires design review

### CMS Team
Please check the team(s) that will do this work. 

- [ ] `CMS Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide CMS Team ` (leave Sitewide unchecked and check the specific team instead)
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [x] `⭐️ Offices`
  - [ ] `⭐️ Product support`
  - [ ] `⭐️ User support`

**Comment by jilladams** [comment]
Allison confirmed that #8362 will resolve this. Closing.
