### ISSUE TITLE
Ops: Publish page to designated public sub-domain

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#8417]
## Description
Take what we learned in the architecture story and do our team's part to get the page live.

**Assumptions**
- Platform Ops team is going to do a lot of this for us, but will need guidance

## Acceptance Criteria
- [ ] Our new version of the Home Page is live on a subdomain

### CMS Team
Please check the team(s) that will do this work. 

- [ ] `CMS Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide CMS Team ` (leave Sitewide unchecked and check the specific team instead)
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [x] `⭐️ Offices`
  - [ ] `⭐️ Product support`
  - [ ] `⭐️ User support`

**Comment by jilladams** [comment]
We staged the page at https://staging.va.gov/homepage-test. I do not think this issue applies to hardening for production, so closing. Reopen if you disagree.
