### ISSUE TITLE
[SPIKE] next-build: front-end documentation

### ISSUE THREAD

**Issue by jkalexander7** [department-of-veterans-affairs/va.gov-cms#8433]
## Problem Statement
Engineers using next-build will need to be able to quickly see the existing component set that exists in next-build and how to use them.

### Documentation
Spike to research how component structure will be exposed to the frontend engineer so that they can see what a component does, and for smaller components, see what data is required to render out that component.

## Acceptance Criteria
- [x] Possibilities for JSON:API documentation are examined, a decision made, and implementation tickets created
  - https://github.com/department-of-veterans-affairs/va.gov-cms/issues/8433#issuecomment-1130568758
  - https://github.com/department-of-veterans-affairs/va.gov-cms/issues/8433#issuecomment-1130580411

### Component documentation
Possibilities to incorporate include:
* Storybook
* React-docgen

### CMS Team
Please check the team(s) that will do this work. 

- [ ] `CMS Program`
- [x] `Platform CMS Team`
- [ ] `Sitewide CMS Team ` (leave Sitewide unchecked and check the specific team instead)
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Offices`
  - [ ] `⭐️ Product support`
  - [ ] `⭐️ User support`

**Comment by timcosgrove** [comment]
For documentation we will leverage [Typedoc](https://typedoc.org/). This will allow us to provide autogenerated repository documentation from our code.

We may leverage [Storybook](https://storybook.js.org/) as well. There was some difficulty with getting Storybook to work with Typescript and with our types. This would need to be resolved as part of implementation.

**Comment by timcosgrove** [comment]
Follow-on tickets:
* https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9138
* https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9137
* https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9135

**Comment by timcosgrove** [comment]
Follow-on tickets have been created.
