### ISSUE TITLE
Dev tooling for CMS design system

### ISSUE THREAD

**Issue by rachel-kauff** [department-of-veterans-affairs/va.gov-cms#8434]
To properly consume & maintain the figma design system in code, we need to set up some sort of component library that can be used by drupal (and potentially other services too). Investigate how this would work in our repo + infrastructure.

**Comment by EWashb** [comment]
@tjheffner could you give any insight on this? Did we come to a good point with this or do we need to explore more?

**Comment by tjheffner** [comment]
this is done, we have the storybook -> drupal pipeline operational

**Comment by EWashb** [comment]
thanks @tjheffner- cleaning up the backlog
