### ISSUE TITLE
Upsize instance, vertical scaling to handle increased load

### ISSUE THREAD

**Issue by ElijahLynn** [department-of-veterans-affairs/va.gov-cms#8443]
## Background

Follow up from outcome of https://github.com/department-of-veterans-affairs/va.gov-cms/issues/8335. 

### Acceptance Criteria

- [ ] CMS servers deploy with an upsized AWS instance

**Comment by ElijahLynn** [comment]
Not fully sure this is going to prevent what happened, but it might.

**Comment by olivereri** [comment]
c5.9xLarge is the next instance size up.

**Comment by ElijahLynn** [comment]
K, I have in my PR here https://github.com/department-of-veterans-affairs/devops/pull/11006 the following:

* CMS-TEST DEV, STAGING, PROD downsized from c5.4xlarge to c5.xlarge
* CMS DEV downsized from c5.4xlarge to c5.xlarge 
* CMS STAGING/PROD upsized from c5.4xlarge to c5.9xlarge

I also added a field on the deploy job that allows us to override the instance type.size on demand so we can upsize other environments for performance or load testing. 

![image](https://user-images.githubusercontent.com/1504756/161787146-37ed27a9-ca82-44eb-9604-dfb414a9bae7.png)

**Comment by ElijahLynn** [comment]
Deploy takes 4 minutes longer on a c5.xlarge (4vCPU) than a c5.9xlarge (36vCPU): 
![image](https://user-images.githubusercontent.com/1504756/161851089-76403f12-e813-46f5-835e-565ee5c5397f.png)

**Comment by ElijahLynn** [comment]
Will save approximately $4,000 year and give us double the cores on STAGING and PROD. Win for now!

Current per year:
![image](https://user-images.githubusercontent.com/1504756/161933028-794fd595-0ea5-4ec6-be55-674cc1a3fe24.png)

Proposed per year:
![image](https://user-images.githubusercontent.com/1504756/161933073-3c753da2-8963-4c02-994b-a18a4909b4d1.png)

**Comment by ElijahLynn** [comment]
Okay, this is all done now. I have attached a few images showing the before and after load for EC2 CPU (user) and Memory Utilitzation, as well as RDS CPU, and one more for request time. We can see that because the EC2 CPU Utililization was more efficient it actually cause the RDS CPU to jump up because it was able to process more requests more quickly and put more strain on RDS. We still only saw a ~12% to 22.5% bump so we are still in a good spot overall. We also see the request frequency increase from about 600 to 800 requests/sec. This also lowers the top end of the avg. response time and response times in general.  

![image](https://user-images.githubusercontent.com/1504756/162082726-58c1d919-ada7-4b15-9dc0-bd3015405b25.png)

![image](https://user-images.githubusercontent.com/1504756/162083130-582f24c4-608c-4ec8-b057-272b3c079c73.png)

We could do more stats on this but overall, this is a great improvement, especially for content-build GQL times.

**Comment by ElijahLynn** [comment]
Looks it may have cut content build time in half based on this job prior to the change at 5m25s https://github.com/department-of-veterans-affairs/content-build/runs/5857127475?check_suite_focus=true and this job after the change at 2m36s https://github.com/department-of-veterans-affairs/content-build/runs/5858894022?check_suite_focus=true.

![image](https://user-images.githubusercontent.com/1504756/162083909-d9d39dff-32f1-43c0-8868-bd3a38869f75.png)

**Comment by ElijahLynn** [comment]
Oh one more, memcache CPUUtilization rose about 7% from 9% to 16% and the burst was shorter during content builds: 
![image](https://user-images.githubusercontent.com/1504756/162085036-111d9bdc-98e8-48ce-b627-d92b84a9faca.png)

**Comment by ndouglas** [comment]
Pleasant surprise for something to scale as we might expect/hope it would 😃
