### ISSUE TITLE
Fieldgroups lost vertical margins

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#8455]
## To Reproduce
1. Go to https://prod.cms.va.gov/node/add/vamc_system_medical_records_offi
2. see that no fieldgroups have pargins

## Screenshots 
<details><summary>Screenshots</summary>

Before claro

<img width="719" alt="146494750-766a2b27-0af6-45ea-9b0f-ced5a5fe7065_png__3192×1560_" src="https://user-images.githubusercontent.com/643678/159824663-cc3882a5-8aa6-480c-ac41-a23e62f16838.png">

After claro

<img width="988" alt="Create_VAMC_System_Medical_Records_Office___VA_gov_CMS" src="https://user-images.githubusercontent.com/643678/159824688-5e41c8cf-b871-4647-8817-57f325457159.png">

</details>

 ## Additional context
Add any other context about the problem here. Reach out to the Product Managers to determine if it should be escalated as critical (prevents users from accomplishing their work with no known workaround and needs to be addressed within 2 business days).

 
## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Defect")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS workstream (orange) (not needed for bug tickets)
- [ ] CMS-supported product (black)

### CMS Team
Please check the team(s) that will do this work. 

- [ ] `CMS Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide CMS Team ` (leave Sitewide unchecked and check the specific team instead)
  - [ ] `⭐️ Content ops`
  - [x] `⭐️ CMS experience`
  - [ ] `⭐️ Offices`
  - [ ] `⭐️ Product support`
  - [ ] `⭐️ User support`

**Comment by rachel-kauff** [comment]
<img width="782" alt="Screen Shot 2022-03-24 at 7 43 37 AM" src="https://user-images.githubusercontent.com/41017988/159941927-f4206a1f-0fdc-46d1-b3ad-68ff7a330595.png">
