### ISSUE TITLE
Discovery: Determine feasibility of subdirectory/path vs subdomain for alternative homepage

### ISSUE THREAD

**Issue by ryguyk** [department-of-veterans-affairs/va.gov-cms#8478]
## Description
Initial idea was to use a subdomain for the alternative homepage (e.g. `preview.va.gov`). See #8412.

Instead, it might make more sense to use a subdirectory - or path (e.g. `va.gov/homepage-preview`).  We need to figure out, first, if this is possible, and, second, if it'd solve our use case.

## Acceptance Criteria

- [ ] Determine whether this path meets requirements for Phases 1a, 1b, and 2
- [ ] Document cons for this path as compared to subdomain

### CMS Team
Please check the team(s) that will do this work. 

- [ ] `CMS Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide CMS Team ` (leave Sitewide unchecked and check the specific team instead)
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [x] `⭐️ Offices`
  - [ ] `⭐️ Product support`
  - [ ] `⭐️ User support`

**Comment by ryguyk** [comment]
### Discovery results

1. First and foremost, using a subdirectory is possible and relatively straightforward. I have successfully rendered a rendition of the homepage at `/homepage-preview`.

1. Pros/Cons of this approach (relative to subdirectory)
    - PROS
      - Entirely in code = Entirely in our control.  Not subjected to anything like DNS, etc.
      - Feature flags can be used to show this page in certain environments (e.g. Tugboat) but not other environments (e.g. production) during development.
      - Wiring homepage links to production content is automatic.  It's free.  A link from `va.gov/homepage-preview` will automatically be wired to `va.gov/page-in-question`. This is to be contrasted with the use of a subdirectory, where this sort of wiring would take some work of unknown complexity.  By default, a link from `preview.va.gov` would be wired to `preview.va.gov/page-in-question` and that is certainly not what we want.  We don't want an entirely separate site.  We just want a separate version of _one page_.
    - CONS
      - Are there any?
      - It _feels_ like this is a separate experience, and I can certainly buy the argument that such a feeling aligns with a separate site (i.e. a subdomain) rather than as a "page" within the existing site.

**Comment by davidconlon** [comment]
Thanks @ryguyk - The way this reads is that we explored the subdirectory, but there aren't any details around what we would need to do in order to do for subdomain. Is there a separate artifact showing that exploration as well?

Part of the consideration we need to make is whether the subdomain may be preferable because it might lend itself to a more scalable use for other teams/experiences beyond just homepage. Therefore the subdirectory path only works for the homepage but would not really scale beyond this one effort.

Also another thing to note is that in order to have /homepage-preview we need to get that URL approved by the Web Governance Board. We currently do not own that subdirectory of va.gov and we would need to ensure that there are not collisions either now or in the future as we don't own all of VA's URLs.

**Comment by ryguyk** [comment]
@davidconlon Thanks for the feedback.  I think syncing on this might be very useful, but below is some added information.

First, I should state explicitly what I might have failed to do when writing this ticket.  That is, simply, that I wrote this ticket from the perspective of a belief that using a subdomain would come with some _significant_ obstacles.  Some initial thought led me quite quickly to the belief that using a subdirectory would be a lot easier, so this ticket was simply intended to prove that it could be done relatively easily within the current constraints of the code base and build system.

That's all to say that this ticket was based on an assumption that the answer to this question:
> ...details around what we would need to do in order to do for subdomain...

is effectively:
> It's _way_ harder.

That said, I do think your desire to see some of the details makes a ton of sense.  Some of the difficulty there is that a lot of those details start to move outside my current familiarity with things, and probably start to implicate some of the folks who are more aligned with platform concerns.  This, in itself, contributes to the angle from which I wrote this ticket (that using a subdomain would come with significant obstacles).  That is to say, even figuring out how to proceed is a significant obstacle, whereas using a subdirectory keeps things easily within our purview.

All that said, here are some thoughts around what I think a subdomain _might_ entail:

### Subdomain Technical Requirements
- Maintain a FE "feature" branch for all code tied to subdomain. This would effectively be a second production branch.
- Separate "production" server to which we can deploy this branch.
- Separate "production" Drupal instance (if there's any CMS-based controls that differ between the two homepages) 
- CI/CD tweaks to treat this "feature" branch as a production branch (i.e. cannot deploy until tests pass, code approved, etc.).
- Link replacement => some process to point links from subdomain back to primary domain (depending on needs of other possible experiences beyond homepage, this process might have to be customized based on each product, each page, or on some other more granular level).
- Likely some others...

**Comment by wesrowe** [comment]
As Github detected above, I just opened an issue with Platform: https://github.com/department-of-veterans-affairs/va.gov-team/issues/39719.

**Comment by ryguyk** [comment]
Closing this issue.  The feasibility of using a subdirectory has become quite clear.  The other related issues in discussion above are captured elsewhere.
