### ISSUE TITLE
Events in Outreach hub not expiring / coming down after event ends date [CMS bug]  

### ISSUE THREAD

**Issue by howardbrande** [department-of-veterans-affairs/va.gov-cms#848]
**Describe the bug**
When an event is added to the Outreach Hub, the event should automatically come down or be unpublished based on the End Date/time. This is not occurring

**To Reproduce**
1. Go to https://prod.cms.va.gov/node/2414/edit
2. See that the end date is January 11, 2020 8:00pm
3. The event is published at https://www.va.gov/outreach-and-events/events/
4. You will see that the event is still listed

**Expected behavior**
That the event will come down off the events page upon the end date / time

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

## Required labels
- [ ] "Product support" (for VSA teams) or "CMS platform" (For core CMS functionality), or "VSP collaboration" for Platform
  - [ ] If product support: which product team (CMS team, Public website team, VAMC upgrade team, etc)
  - [ ] Which CMS-supported product, if any (VAMC, Benefits hubs, Outreach Hub, VA.gov homepage, Media library)
  - [ ] For VSP collaboration: which platform team?, (content-ia-team, devops, design, documentation, frontend, etc)
- [ ] Which CMS component (Content model, Content API, Content Governance, Authoring experience, Media library, Login, Documentation, etc)

**Comment by kevwalsh** [comment]
@howardbrande will check urgency. this ticket could be deprecated if the Events listing refactoring adds the Past events / Future events toggle from VAMC to all events listing.
