### ISSUE TITLE
Engage Security Risk Assessment (secRisk) process with Salesforce DTC

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#8480]
## Description

1. Get permission in Salesforce to put in a request for a riskSec assessment
2. Write and submit request for RSA

Scope Risks:
- It's possible that more work will have to be done to support the RSA, e.g. architecture diagrams.

## Acceptance Criteria
- [ ] RSA submitted

### CMS Team
Please check the team(s) that will do this work. 

- [ ] `CMS Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide CMS Team ` (leave Sitewide unchecked and check the specific team instead)
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [x] `⭐️ Offices`
  - [ ] `⭐️ Product support`
  - [ ] `⭐️ User support`

**Comment by jilladams** [comment]
Sprint 56 planning: long-running issue due to dependency on Salesforce team, so this will last awhile.

**Comment by wesrowe** [comment]
Draft ticket:
Background: VA.gov CMS team has identified the VA hierarchy data in VIEWS CCM as a useful source of truth for an online Offices Directory product. We have worked with the product owner already. We are engaging with DTC about how to programmatically update VIEWS data to keep our Directory current. At DTC office hours, we were instructed to engage DTC through the secRisk assessment.

Method:
- We would like to make a Salesforce report available as a CSV that is accessible via the VA network.

Risks: 
- There is no PII or info that would be considered PII. It is only office names and identifiers. The name/email for the VA point of contact for an office may also be included.
- DDOS vector minimal since the CSV would only be accessible via the VA network.

**Comment by wesrowe** [comment]
Steve and I put the ticket in on 4/21, and a review meeting with DTC was set for 4/27.
