### ISSUE TITLE
Facility closed: Tuscaloosa VA Mobile Clinic

### ISSUE THREAD

**Issue by JayDarnell** [department-of-veterans-affairs/va.gov-cms#8484]
## Background

**Who are the stakeholders for this?**

- **Section/VISN:** VA Tuscaloosa health care, VISN 7
- **Editor(s):** There are 3 active editors for VA Tuscaloosa as of 4/21/22: Stephen Tyler, Michael Harris, April Jones https://prod.cms.va.gov/admin/people?user=&status=1&role=All&workbench_access_section__section=329
- **VISN web manager (optional):** None listed on https://prod.cms.va.gov/ for VISN 7
- **Product team member:** 
- **CMS Help desk**

**Associated HD issue, if any**
None found.

<insert_link>

#### 1. CMS Help desk
- [x] Becomes aware that the facility is no longer on the Facility API, via the "Facility closed" flag, and create github issue  (Future state: Flag autogenerates github issue)
- [x] Fill out the stakeholders in github issue. 
- [x] If we don't already have context (say, via a HD ticket submitted by an editor), check with editor to find out more about the status of the facility 

<details><summary>Email template </summary>

```
FROM: vacms email
SUBJECT: <facility name> removed from VAST
CC: Jeffrey.Grandon@va.gov, Steve.Tokar2@va.gov, Jennifer.Heiland-Luedtke@va.gov, David.Conlon@va.gov
BODY:

Hi [VAMC editor who owns the node in CMS ]

We see that [name of facility] has been removed from VAST. If this facility has been permanently closed or moved, you can now work with us to unpublish the facility from the CMS and remove it from VA.gov.

Because some Veterans may have bookmarked this facility, external sites may have linked to it, and because it can take a little time for search engines to catch up to web content, we want prevent errors and bad web experiences for our Veterans.

   In order to do that we have some questions about the nature of this closure so that we can help redirect Veterans to the right place and understand this change.

1. Was this facility replaced with another facility? 
   If yes, which one?
2. Is there a news release or story about this published on your VAMC website? 
3. Anything else we should know about this facility closure? 

If this facility has been removed from VAST in error, please notify our Support Desk as well as your VAST coordinator.

[outro]

[CMS helpdesk signature] 
```
   
   
</details>

#### 2a. If facility has moved to a new system or merged 
- [ ] Can any of the associated content  (eg services, facility map?) be reused? If so
  - [ ] is there a new facility in VAST/Facility API that content should be moved to?
- [ ] Create [redirect request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=ia&template=redirect-request.md&title=Redirect+Request) to point to URL of new facility.
- [ ] When redirect is ready to go out, plan to make these changes immediately after redirect is released. Practice first on staging or a demo environment. 
  - [ ] In certain, rare situations: CMS engineer bulk moves any content to new facility.
  - [ ] CMS engineer finds the menu for the system https://prod.cms.va.gov/admin/structure/menu and deletes the menu item for the merged facility.

#### 2b. If not 
- [x] Determine where should redirect go? to the system? or to the nearest clinic?
- [x] Create [redirect request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=ia&template=redirect-request.md&title=Redirect+Request) accordingly. 
- [x] When redirect is ready to go out, plan to make these changes immediately after redirect is released. Practice first on staging or a demo environment. 
  - [x] CMS engineer bulk archives the facility service nodes. (https://prod.cms.va.gov/admin/content/bulk?type=health_care_local_health_service).
  - [x] CMS engineer bulk archives the facility non-clinical service nodes. (https://prod.cms.va.gov/admin/content/bulk?type=vha_facility_nonclinical_service).
  - [x] CMS engineer finds the menu for the system https://prod.cms.va.gov/admin/structure/menu and deletes the menu item for the closed facility.
  - [x] CMS engineer filters content by the health care system and scans for any events that might be taking place at that facility. Archive if any are found.
  - [x] CMS engineer edits the facility node, removes  flag `Removed from source`, add a revision log that explains the change, with a link to github issue, and change moderation state to archive.
- [x] Let HD know this is complete. 

#### 3. CMS Help desk
- [ ] Notifies editor and any other stakeholders that this is complete. 

### Vet Center – facility closure [this needs work]
- [ ] CMS team becomes aware that the facility is no longer on the Facility API.
- [ ] CMS team submits [Redirect request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=ia&template=redirect-request.md&title=Redirect+Request), cc'ing Facilities team, and referencing this issue.
- [ ] Once timing of Redirect going live is known, alert CMS engineers to carry out the other steps
- [ ] CMS engineer bulk unpublishes the nodes.
- [ ] CMS engineer removes the Section.
- [ ] CMS engineer edit facility node and remove flag `Removed from source`, sets moderation state to archived, then save node.

## CMS Team
Please check the team(s) that will do this work.

- [ ] `CMS Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide CMS Team ` (leave Sitewide unchecked and check the specific team instead)
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Offices`
  - [x] `⭐️ Product support`
  - [x] `⭐️ User support`

**Comment by JayDarnell** [comment]
Does not currently have a redirect in place.

**Comment by JayDarnell** [comment]
@stefaniefgray @chriscraiga6 this issue needs your attention (this was not in our initial set of facility closures)

**Comment by stefaniefgray** [comment]
"Good morning Stefanie, our TVAMC Mobile Clinic is no longer operational. https://prod.cms.va.gov/tuscaloosa-health-care/locations/tuscaloosa-va-mobile-clinic 

We now have storefront locations in our rural area, I believe my PAO has reached out to have those included on our locations page. Is there something CMS needs us to do on our side? I’m not able to archive the page. 

Mobile Clinic has been discounted at this time.

Would like the old URL to redirect to locations page: https://www.va.gov/tuscaloosa-health-care/locations/ 

Hopefully we can get our storefront locations added, these are the areas that the Mobile Clinic use to service."

**Comment by JayDarnell** [comment]
Redirect request: https://github.com/department-of-veterans-affairs/va.gov-team/issues/40430

For consistency I requested the redirect go to the tuscaloosa health care main page (as we've done with others)
