### ISSUE TITLE
[Fig - > Storybook] Form hierarchy: section labels

### ISSUE THREAD

**Issue by rachel-kauff** [department-of-veterans-affairs/va.gov-cms#8492]
Implementation of design recs from #8342 

Figma: https://www.figma.com/file/ScABI31f3MRFEvQ8WitVPa/CMS-Design-System?node-id=1039%3A30987

ACs
Changes to the following aspects of section label design are added to Storybook for further testing and iteration:
- [ ] Section component exists in Storybook that showcases different
   - [ ] heading type sizing
   - [ ] margin rules
   - [ ] heading background color
- [ ] [stretch] New rules for grouping content and interactivity (& how outline boxes get applied)

**Comment by cjterdi** [comment]
Link to figma file with with heading sizes, margin rules and bg colors. The grouping content is in progress: https://www.figma.com/file/ScABI31f3MRFEvQ8WitVPa/CMS-Design-System?node-id=1039%3A30987

**Comment by EWashb** [comment]
Needs dev hand off

**Comment by EWashb** [comment]
@edmund-dunn can take over this work once we gain knowledge transfer from @tjheffner

**Comment by EWashb** [comment]
@edmund-dunn once you have your Storybook sync with Tanner, this would be good to pick up

**Comment by EWashb** [comment]
This may not reflect the current state of the form hierarchy editorial interface post-accessibility updates. I hesitate to add to the storybook until the figma updates happen in #12362
