### ISSUE TITLE
[Fig - > Storybook] Fontawesome icons

### ISSUE THREAD

**Issue by rachel-kauff** [department-of-veterans-affairs/va.gov-cms#8499]
ACs
- [ ] (Cindy and Kauff) Set of Fontawesome icons is ready for action
   - [ ] Add circle background hover states
- [ ] Icons added to storybook

**Comment by rachel-kauff** [comment]
I made decent headway on setting up a set that can be exported as SVGs for Tanner. Boy was my estimate off though. Fortunately most everything that's in my "to do" pile are more speculative -- icons we might need but don't need yet. 

@cjterdi Could you take a look at the reverse for the ? icon? I also got stuck on the close hover state 😵‍💫

**Comment by rachel-kauff** [comment]
File: https://www.figma.com/file/ZetH9BVazn0PX2EYTPlveV/WIP---icons?node-id=0%3A1

**Comment by tjheffner** [comment]
if we're using fontawesome as a library you won't need to export anything, i just need the names
