### ISSUE TITLE
Remove the "published version" text from all content types. 

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#851]
**Describe the bug**

**To Reproduce**
1. Go to any node edit screen
2. Note the text about previous and next build

**Expected behavior**
You shouldn't see any text about when the content is next built. 

**Screenshots**
![Zoom_Meeting_ID__486-967-3774](https://user-images.githubusercontent.com/643678/72903833-f00c0980-3cfb-11ea-8df3-54d7b3bc91a4.jpg)

**Additional context**
This text is often wrong and confusing.

**Comment by ethanteague** [comment]
PR: https://github.com/department-of-veterans-affairs/va.gov-cms/pull/854
