### ISSUE TITLE
Situation updates and information should only display if there's an active alert with a situation update or situation information.

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#852]
**Describe the bug**
This h2 should not show unless it has content. 

**To Reproduce**
Go to /pittsburgh-health-care/operating-status

**Expected behavior**

**Screenshots**
![VA_Pittsburgh_health_care___Operating_Status_and_Zoom_Meeting_ID__486-967-3774](https://user-images.githubusercontent.com/643678/72905996-75dd8400-3cff-11ea-8a35-6566f3d095c9.jpg)

**Comment by ethanteague** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/11546
