### ISSUE TITLE
Troubleshoot BRD Env (dev,staging) Servers After Deploy 503 Errors

### ISSUE THREAD

**Issue by olivereri** [department-of-veterans-affairs/va.gov-cms#8524]
## Description
BRD Dev and Staging environments can have a successful deployment but soon after fail and respond with HTTP 503 errors.  This can have impacts on external teams that depend on the availability of these servers to respond to requests.  Determine the cause of the failures and determine a fix.

## Acceptance Criteria
- [ ] Investigate the cause of HTTPd failures in BRD after successful deployment.
- [ ] Create follow-on issues, or BRD Environments no longer become unhealthy after a successful deploy.

## Implementation Notes

- Issue appears frequently on BRD Dev, and sometimes on Staging.
- Possible underlying error:
```
The website encountered an unexpected error. Please try again later.
PDOException: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known in Drupal\Component\DependencyInjection\PhpArrayContainer->createService() (line 79 of /var/www/cms/docroot/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php).
```
- Assumption: Environment variables are not being loaded into the HTTPd service. This causes the server to become unhealthy after deployment and then terminated. Ultimately the Load Balancer throws a 503.
- Relevant discussion [here](https://dsva.slack.com/archives/C02HX4AQZ33/p1648515652486079)

**Comment by TheBoatyMcBoatFace** [comment]
No currently happening - reopen if it becomes an issue again
