### ISSUE TITLE
Spike: Broken links

### ISSUE THREAD

**Issue by EWashb** [department-of-veterans-affairs/va.gov-cms#8536]
Relating to #3155 there is a need to create a path forward to address the broken link issue. This spike will be in the form of Opportunity Mapping. The desired outcome of this is fewer broken links.

Related to #4395 

## Current State

Current state only notifies of broken links at migration. 

## Possible Opportunities 

This spike will help determine opportunities that exist to both prevent broken links and alert appropriately. One possible solution would be to explore where other triggers can/should exist to get proper notification of the occurrence of a broken link. 

Opportunity 1: improve archive tools #2833
Opportunity 2: improved broken link notifications #8230
Opportunity 3: Publish linked pages when publishing #6114 (probably needs to be an epic)
Opportunity 4: #7293
Opportunity 5: #7343
Other Opportunities: Stuff we haven’t thought of yet.

**Comment by msbtterswrth** [comment]
[Mural link here](https://app.mural.co/invitation/mural/vagov6717/1654526125251?sender=u0213d96dd8b8c144f1f10284&key=0746e05e-d24c-47df-a4dd-5a928956ad28) for refining

**Comment by EWashb** [comment]
Part 1 of the broken link spike was completed on 6/7. Part 2 will happen on 6/14

**Comment by EWashb** [comment]
From our two-part spike on broken links. It was determined that the best path forward, both feasible and high value are:

- Preventing PDFs in link fields, captured in #7293 
- Designing an improved workflow as a two-part initiative: mapping out the current state #9452 and the evaluation of the 4X entity usage module as a means of tracking broken links #9424 
- Updating the permissions CMS documentation #9462 
- Generate a report on automated broken links over time (longer time and big lift)
- Determine a way to notify editors of broken links in node view and edit screens
