### ISSUE TITLE
Datadog Drupal Error monitors should alert Platform CMS on-call

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#8546]
## Description
The Drupal error notifications for these errors did not trigger PagerDuty. We would have caught this sooner if it had. (example error notification: https://app.datadoghq.com/monitors/44590810?to_ts=1648571830000&from_ts=1648570630000)

## Acceptance Criteria

- [x] Determine appropriate alert level and notification type for Drupal errors
- [x] Document updated alert levels so that engineers are aware of change https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/READMES/cms-alerts.md

## Implementation 

*  Per @olivereri , this is basically just talking about what PHP errors to alert on, in this case it is PHP Exceptions.

### CMS Team
Please check the team(s) that will do this work. 

- [ ] `CMS Program`
- [X] `Platform CMS Team`
- [ ] `Sitewide CMS Team ` (leave Sitewide unchecked and check the specific team instead)
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Offices`
  - [ ] `⭐️ Product support`
  - [ ] `⭐️ User support`

**Comment by ndouglas** [comment]
This should include codifying how we respond to the Sentry issues themselves and include some discussion of duplicate and redundant issues that pop up in Sentry.  It's NBD to silence a particular Sentry issue, but we need some guidelines about when that issue _should_ be silenced -- when a GH issue is opened?  when on-call is actively looking at it?  when it is resolved?  Or does it depend on the severity of the issue?

**Comment by olivereri** [comment]
The outcome of this will definitely trigger some documentation changes. For now on PHP exceptions from Sentry the Pagerduty CMS Critical group will be notified. We can tweak it we don't like it. 

I don't think we necessarily need to have a big discussion about establishing alerts for critical errors. Suppose we need to review [this](https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/READMES/cms-alerts.md) and see where PHP exceptions sit in the linked table. Right now, they're being considered Urgent.

## Alert Levels

| Alert Level  | Action                                   |
|--------|------------------------------------------------|
| Urgent | PagerDuty Critical >> Slack #cms-notifications |
| High   | `@here` in Slack                               |
| Medium | Slack #cms-notifications @cms-alerts-medium    |
| Low    | None                                           |

**Comment by mchelen-gov** [comment]
This would be a great issue for DevOps team to prioritize so we can be quickly informed of CMS issues!

**Comment by olivereri** [comment]
After reviewing the documentation, we had previously spent time and effort thinking about how to stratify and prioritize  then document all of the various alerts. Per the documentation we were treating error alerts as Urgent and grouping it with much more important alert levels. What we should have done (and did) was follow the documentation and adjusting the alerts themselves to conform to this.
