### ISSUE TITLE
KB article for How do I take a health service off my facility page?

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#8552]
## User story
As a VAMC editor, I need to provide accurate information about the services offered at my facility.

## Acceptance Criteria
- [ ] Testable_Outcome_X
- [ ] Testable_Outcome_Y
- [ ] Testable_Outcome_Z
- [ ] Requires design review

### CMS Team
Please check the team(s) that will do this work. 

- [ ] `CMS Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide CMS Team ` (leave Sitewide unchecked and check the specific team instead)
  - [ ] `⭐️ Content ops`
  - [x] `⭐️ CMS experience`
  - [ ] `⭐️ Offices`
  - [ ] `⭐️ Product support`
  - [ ] `⭐️ User support`

**Comment by xiongjaneg** [comment]
low urgency, I think, mostly to divert a few questions coming into help desk

**Comment by rachel-kauff** [comment]
@xiongjaneg There's a similar article in existence already: https://prod.cms.va.gov/help/vamc/how-to-remove-an-existing-facility-health-service-from-a-va-medical-center-or-va-clinic

I haven't inspected closely to see if all those steps are still valid, but think we should work on this one over starting fresh. What do you think.

**Comment by rachel-kauff** [comment]
Gave the title a quick chop, but need to take a closer look at the steps when I return.

**Comment by mmiddaugh** [comment]
Closing this issue as I've added this topic to #12988 Update KB Article: "How to edit an existing VAMC facility health service"](https://app.zenhub.com/workspaces/sitewide-facilities-639f5253e4b702a32376339e/issues/gh/department-of-veterans-affairs/va.gov-cms/12988)
