### ISSUE TITLE
Update or create new KB article for archive vs delete

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#8554]
## User story
As a CMS editor, I want to provide accurate information to Veterans.
As a CMS editor, I want to remove pages from my site.
As a CMS editor, why can't I delete?

[See existing article ](https://prod.cms.va.gov/help/cms-basics/archiving-and-deleting-content)for potential refinement or separate article

## Acceptance Criteria
- [ ] Testable_Outcome_X
- [ ] Testable_Outcome_Y
- [ ] Testable_Outcome_Z
- [ ] Requires design review

### CMS Team
Please check the team(s) that will do this work. 

- [ ] `CMS Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide CMS Team ` (leave Sitewide unchecked and check the specific team instead)
  - [ ] `⭐️ Content ops`
  - [x] `⭐️ CMS experience`
  - [ ] `⭐️ Offices`
  - [ ] `⭐️ Product support`
  - [ ] `⭐️ User support`

**Comment by xiongjaneg** [comment]
low urgency, requested by VHA DM to divert some questions to helpdesk

**Comment by laflannery** [comment]
@EWashb Can we close this? I feel like this is and old request and with the updates to the editorial workflow that might be the answer to this anyway.

**Comment by EWashb** [comment]
We can! I'll close it @laflannery
