### ISSUE TITLE
CMS team onboarding iteration

### ISSUE THREAD

**Issue by cmaeng** [department-of-veterans-affairs/va.gov-cms#8557]
## Description
CMS team internal onboarding process could use a revisit in preparation for a new influx of folks.

[Existing template](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/templates/edit)

## Acceptance Criteria
- [ ] A group of folks have huddled to brainstorm how to enhance our onboarding processes
- [ ] A group of folks have reviewed the onboarding GitHub templated issue with an eye towards improvements
- [ ] Agreed upon improvements are in place before the next round of new folks
- [ ] 2022 OKRs are added to [OKR doc](https://va-gov.atlassian.net/wiki/spaces/VAGOV/pages/96698383/Product+CMS) 

### CMS Team
Please check the team(s) that will do this work. 

- [x] `CMS Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide CMS Team ` (leave Sitewide unchecked and check the specific team instead)
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Offices`
  - [ ] `⭐️ Product support`
  - [ ] `⭐️ User support`

**Comment by xiongjaneg** [comment]
@rachel-kauff Any insight you have would be much appreciated as well!

**Comment by cmaeng** [comment]
some ad hoc feedback gleaned from the Offices team:
- although it's fairly dense, most liked that everything was in one place so they could reference it later
- may be good to review what's in the template and strip out anything that's not absolutely needed
- may be good to put a note for the team member to come back and review at the 1 month and 2 month milestones

**Comment by cmaeng** [comment]
enhanced to include an orientation to change management on the project and updated to reflect new org changes

**Comment by cmaeng** [comment]
marking as closed for this iteration. will revisit after this round of folks in April 2022

**Comment by suzanne-gray** [comment]
Some notes and comments from the first round of new hires:

[VA diagrams](https://app.mural.co/t/vagov6717/m/vagov6717/1646447643431/1cbae3844c54a42877451e7a79706f0be048d740?sender=u0462bdfe88bc3bd6cd013167) could be updated/improved  

**Slack**

confusion about when to use internal slack channel vs cms-team, we may need a better description or process.

Update slack channel list

in Week 2 - "DM to add to appropriate Slack alias groups for the DSVA workspace".  At first I tried to DM those @s before I realized that meant "Delivery Manager to add..." 

**Developer tools**

The week 2 link to  [VA developer tools](https://depo-platform-documentation.scrollhelp.site/getting-started/Request-access-to-tools.969605215.html) is prob too technical for most team members, that could prob go under developers or dev/ops

**Zoom**

re: Zoom settings: I discovered accidentally that by default Zoom has a setting enabled to allow you to dial into multiple concurrent Zoom calls. (At least: this was enabled for me on a new Zoom install.) We should instruct new folks to disable that.
To find / disable:  Zoom > Preferences > View More settings (takes you here: https://us06web.zoom.us/profile/setting?mid=&from=client > search for simultaneously
