### ISSUE TITLE
Implement R&S content type name and description improvements from #7893

### ISSUE THREAD

**Issue by JayDarnell** [department-of-veterans-affairs/va.gov-cms#8569]
Relates to #7893 

## User Story or Problem Statement

[Revised content type names and descriptions](https://docs.google.com/spreadsheets/d/1417vF50e6JtEuqJyNH6QfCH2Y5EDLcUk21GLD3uq_0Y/edit#gid=1274520064) are in this spreadsheet. Changes are highlighted. 

## Acceptance Criteria
- [x] name and description changes outlined in the spreadsheet linked above have been implemented

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [x] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [x] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

### CMS Team
Please check the team(s) that will do this work. 

- [ ] `CMS Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide CMS Team ` (leave Sitewide unchecked and check the specific team instead)
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Offices`
  - [x] `⭐️ Product support`
  - [ ] `⭐️ User support`

**Comment by TyOddballDM** [comment]
#Thanks
