### ISSUE TITLE
Jenkins Uses an Unsupported Version of Python for Jobs with Ansible Tasks

### ISSUE THREAD

**Issue by olivereri** [department-of-veterans-affairs/va.gov-cms#8581]
## Description
Jenkins and Worker nodes run Python virtual environments with an unsupported version of python by the Python core team. The warning comes from a cryptography module and a dependency warning on 2 other modules.  The risk is that Jenkins jobs using Ansible may fail if the next release of `cryptography` is downloaded and installed but no longer supports the installed Python version. Alternatively, updates to the cryptography module, _if it is not pinned_, may fail to download and install also causing jobs that depend on Ansible to fail.

> 13:57:01  + bash -c 'source venv/bin/activate && ansible-playbook --inventory inventory-plugin-upgrade/ -e config=cms-test-vagov-dev -e ref=32d73257ff977fd1f8e65f2618436b2c9ef67197 deployment/create.yml'

> 13:57:01  /instance-storage/jenkins/workspace/deploys/cms-test-vagov-dev/ansible/venv/lib/python2.7/site-packages/ansible/parsing/vault/__init__.py:41: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in the next release.

> 13:57:01    from cryptography.exceptions import InvalidSignature

> 13:57:19  /instance-storage/jenkins/workspace/deploys/cms-test-vagov-dev/ansible/venv/lib/python2.7/site-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.26.5) or chardet (3.0.4) doesn't match a supported version!

## Acceptance Criteria
- [ ] Determine if Jenkins and worker nodes can support updating Python Virtual Environments to a supported version.
- [ ] Determine if Ansible will still function the same using a supported version of Python.
- [ ] If possible, update Jenkins and worker nodes to use a supported version of Python.

**Comment by TheBoatyMcBoatFace** [comment]
Shifting away from Jenkins - reopen if we go back to Jenkins
