### ISSUE TITLE
Sitewide crew backlog transition

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#8585]
# Improve roadmap and backlog and for Sitewide crew

## Background

* The products on VA.gov have code and backlog managed in a number of Github repos, including [content-build](https://github.com/department-of-veterans-affairs/content-build/), [va.gov-cms](https://github.com/department-of-veterans-affairs/va.gov-cms/), and [vets-website](https://github.com/department-of-veterans-affairs/vets-website/), and some content in  [content](https://github.com/department-of-veterans-affairs/content/).
* The Sitewide product portfolio contains 15 Veteran-facing products. The vast majority of the components of those products rely on VA.gov CMS content and functionality, and changes to each repo are often interdependent.
* The Sitewide backlog is split between the [va.gov-team](https://github.com/department-of-veterans-affairs/va.gov-team/issues) repo and the [va.gov-cms](https://github.com/department-of-veterans-affairs/va.gov-cms/issues) repo.
* The `va.gov-cms` repo
  * also contains Platform CMS backlog and roadmap.  
  * has a set of labels specific to Sitewide products, practices, workstreams, etc.
* The `va.gov-team` repo also contains work for a number of other crews.
  * has a universe of labels that go far beyond Sitewide.
  * has no code.
* Other teams have dependencies on Sitewide work, such as Homepage, Cerner (MyVA backlog).   

## Problem statement
* The current github/zenhub setup is not conducive for cross-functional (CMS and FE) teams.
* It has proven difficult to build cross-functional epics with issues in more than one repo.
  * The va.gov-team repo is very large and too slow to reference from va.gov-cms epics, using Zenhub's epic field.
  * Github's native functionality does not work well for multiple repos, for example for linking PRs to issues, looking up issues,  converting todos to tickets, etc.
  * The non-sitewide work tracked in each repo can be a distraction for Sitewide crew members. This is particularly an issue with VA.gov-team repo.
* Issue templates in va.gov-team and va.gov-cms are different.

## Possible solutions to explore

1. Start fresh (eg, use `content-build` repo or a new repo)
2. Transfer Sitewide CMS backlog to va.gov-team backlog or vice versa
3. Investigate ways to optimize use of Zenhub
4. Explore other software or products such as Github Projects, which may facilitate work in multiple repos.

## User stories

As a member of the Sitewide crew, or one of its crossfunctional product teams, I have a singular backlog that operates with multiple code repositories, so that I can work efficiently and in concert with the rest of the Sitewide crew.

Substories, need writing
* Build x-functional epics
* Consistent and efficient issue templates (particularly `content-build` and `va.gov-cms`)
* Ability to easily link PRs to relevant github issues.

### CMS Team
Please check the team(s) that will do this work. 

- [ ] `CMS Program`
- [ ] `Platform CMS Team`
- [x] `Sitewide CMS Team ` (leave Sitewide unchecked and check the specific team instead)
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Offices`
  - [ ] `⭐️ Product support`
  - [ ] `⭐️ User support`

**Comment by cmaeng** [comment]
it was determined to use the va.gov-cms repo / Zenhub board as an interim step for backlog management. removing the sprint 56 designation and keeping open as there may be other aspects to tackle.
