### ISSUE TITLE
Update spec tool behat tests to combine content type fields tests

### ISSUE THREAD

**Issue by msbtterswrth** [department-of-veterans-affairs/va.gov-cms#8586]
## Description
As a developer, I want to run ALL the fields tests at once for content types. Currently there are 12 separate tests for the following 'groups' of content:

1. Benefits Hubs - page, landing_page, basic_landing_page, support_service
2. Campaign landing page - campaign_landing_page
3. VA common - centralized_content
4. LC (Resources and Support) - checklist, faq_multiple_q_a, media_list_images, media_list_videos, q_a, support_resources_detail_page, step_by_step
5. User guides (KB) - documentation_page
6. VAMC - event, event_listing, health_services_listing, leadership_listing, press_release, press_releases_listing, person_profile, story_listing, news_story, health_care_region_detail_page, health_care_local_facility, health_care_local_health_service, vha_facility_nonclinical_service, health_care_region_page, full_width_banner_alert, vamc_system_billing_insurance, regional_health_care_service_des, locations_listing, vamc_system_medical_records_offi, vamc_operating_status_and_alerts, vamc_system_policies_page, vamc_system_register_for_care
7. Alerts - banner, promo_banner
8. NCA facility - nca_facility
9. Outreach hub - office, outreach_asset, publication_listing
10. VA forms - va_form
11. VBA facility - vba_facility
12. Vet Center - vet_center, vet_center_cap, vet_center_facility_health_servi, vet_center_locations_list, vet_center_mobile_vet_center, vet_center_outstation

The tests within the new spec tool in airtable already account for this combined test using the output from the new [spec tool](https://airtable.com/appSg80z9nVWoesxn/tbltV84WALyKvpXuc/viwqLFrgfQleFk9Zp?blocks=hide) (though we'll need to add the intro text and list of content types in, if needed).

## Acceptance Criteria
- [ ] New test for all content type fields is created
- [ ] Test runs successfully using output generated in new spec tool

### CMS Team
Please check the team(s) that will do this work. 

- [ ] `CMS Program`
- [x] `Platform CMS Team`
- [ ] `Sitewide CMS Team ` (leave Sitewide unchecked and check the specific team instead)
  - [x] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Offices`
  - [ ] `⭐️ Product support`
  - [ ] `⭐️ User support`

**Comment by TheBoatyMcBoatFace** [comment]
Removing Platform CMS Team label

Pinging the QA Team: @ndouglas
