### ISSUE TITLE
Discovery: Geolocation for facilities and events

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#8587]
ACs 
- [x] Which content types have lat/long already Facility API?
- [x] Should coords use address or manual entry?
- [x] Build the rest of the issues in the epic (#8627, #8628)

**Comment by swirtSJW** [comment]
Why are we proposing adding this to ?
- health_care_local_facility
- vba_facility
- nca_facility
- vet_center
- vet_center_outstation

There are a pile of recommendations here (which may be good ones) without any questions being asked/answered to gather the requirements.

**Comment by msbtterswrth** [comment]
Some notes from the sync with @swirtSJW and @JayDarnell:

Which geocoding service/forward look up should we use? (Ask Dave)
Who can create/edit Vet Center - CAPs? Is there a workflow? Approvers?
Can editors move the pins manually or are they address based?
If they can manually select a pin location, we should show a map widget in the CMS UI

**Comment by swirtSJW** [comment]
@msbtterswrth  @kevwalsh 
I just got off the Lighthouse call with Dave and while we were discussing needing to push latlon,  I asked him for his take on moving the pin.   He wants only admins to have that capability and we do it by request fulfillment.
