### ISSUE TITLE
Fieldgroups should show help text below fieldgroup label, not below all the fields contained in a fieldgroup

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#860]
## User Story or Problem Statement

As a content editor or creator adding content in a "fieldset" field group, i want help text to show up at the top of the field group, not below all the fields, where i don't see it immediately. 

## Acceptance Criteria
* All existing fieldset fieldgroups show their help text at the top of the field group, not below. 

## Implementation steps 
Theme the fieldset fieldgroup similar to the way that Details fieldgroups are themed--with fieldgroup description before the fields. 

Example: the Editorial workflow fieldset on /node/add/full_width_banner_alert should show the help text below the "Editorial workflow" label, but above the checkbox. 

![Create_VAMC_system_banner_alert_with_situation_updates___VA_gov_CMS](https://user-images.githubusercontent.com/643678/73041181-7292e700-3e2a-11ea-9c98-c96b593063a7.jpg)

**Comment by ethanteague** [comment]
PR: https://github.com/department-of-veterans-affairs/va.gov-cms/pull/907

**Comment by swirtSJW** [comment]
merged https://github.com/department-of-veterans-affairs/va.gov-cms/pull/907
