### ISSUE TITLE
When broken links prevent content release, broken links Slack channels are not informed

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#8602]
## Describe the defect
* This build failed due to excessive broken links: https://github.com/department-of-veterans-affairs/content-build/actions/runs/2096970971
* That was reported as a build failure per the normal mechanisms: https://dsva.slack.com/archives/CJT90C0UT/p1649172448351709
* However, that failure was not reported into #content-broken-links: https://dsva.slack.com/archives/C030F5WV2TF/p1649173415434709
* The workflow run did attempt to send notification to the channel, but this failed: https://github.com/department-of-veterans-affairs/content-build/runs/5836038162?check_suite_focus=true#step:27:31

## Expected behavior
Broken link reports should always send to #content-broken-links without fali.

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Defect")

### CMS Team
Please check the team(s) that will do this work. 

- [ ] `CMS Program`
- [X] `Platform CMS Team`
- [ ] `Sitewide CMS Team ` (leave Sitewide unchecked and check the specific team instead)
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Offices`
  - [ ] `⭐️ Product support`
  - [ ] `⭐️ User support`

**Comment by cweagans** [comment]
https://github.com/department-of-veterans-affairs/content-build/pull/1069 is open now
