### ISSUE TITLE
Create Automation to Run Ad-Hoc Scripts on Production CMS Server

### ISSUE THREAD

**Issue by olivereri** [department-of-veterans-affairs/va.gov-cms#8604]
## Description
Sometimes CMS DevOps engineers are asked run scripts on CMS Production. These scripts may be required for a data migration, other post deploy data manipulation, or to fix data.  The current method DevOps engineers use to run these scripts is to manually log in to CMS Prod, change to the appropriate user, run the scripts, and report output if any.

Ideally we want to reduce cases where we log directly into Production. It should be a rare case. For better repeatability, security, and auditability running Ad-Hoc scripts should be orchestrated and executed by a dedicated automated pipeline.

## Implementation Details
This pipeline could be created in Jenkins, GHA, or other tool to deliver and run the script. Could become a self-service tool for developers with access to the job orchestration tool, provided adequate trust that this feature won't be abused to run arbitrary scripts.

## Supporting Documentation
https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/READMES/brd-login.md

## Acceptance Criteria
- [ ] Provided an Ad-Hoc/Post-Deployment script an automated job orchestration runs it against CMS Production.
  - [ ] Automated job orchestration can return script output if required.
- [ ] Appropriate user permissions are in place to authorize execution.
- [ ] CMS DevOps Engineers no longer need to access Prod Servers directly (login shell) to run Ad-Hoc scripts.
- [ ] Automation prepares CMS before script run, e.g. Database Backup.

**Comment by TheBoatyMcBoatFace** [comment]
This could be handled by Lagoon Tasks. Closing. Reopen if needed. 
- #11839
