### ISSUE TITLE
No route found for "NESSUS /": Method Not Allowed (Allow: GET, POST, HEAD)

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-cms#8623]
See [this Sentry issue](http://sentry.vfs.va.gov/organizations/vsp/issues/64171/?project=14&referrer=webhooks_plugin).

There's not a substantial amount of information about this.  I assume that this is related to the Nessus vulnerability scanner, and that it is attempting to elicit information from our servers that depends upon some server-side module or something that we don't have installed.  So all it's doing is throwing errors in our system because it's an unknown method.

(It's also possible that it's simply trying to determine how the server responds to various methods [PUT, DELETE, NESSUS, FNORD, FROBOZZ] to determine our vulnerability to HTTP tampering attacks.  In this case, blocking unrecognized methods is not harmful and is generally A Good Thing™)

The easiest way to fix this is probably just to throw this in the `.htaccess`:

```html
    <Limit NESSUS>
    Order Deny,Allow
    Deny from All
    </Limit> 
```

Maybe throw it in just prior to the request getting passed to `index.php`.

Another possibility would be to use `LimitExcept` to restrict methods to methods we know are legitimate (GET/PUT/POST/PATCH/DELETE/HEAD/OPTIONS and possibly others).  IIRC Drupal doesn't use PUT, even in core REST, but I could be mistaken.

**Comment by ElijahLynn** [comment]
Similar alert today with:

> Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException: No route found for "PROPFIND /media/image/4112": Method Not Allowed (Allow: GET, POST, HEAD) in Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest() (line 140 of /var/www/cms/docroot/vendor/symfony/http-kernel/EventListener/RouterListener.php).

http://sentry.vfs.va.gov/organizations/vsp/issues/64171/?project=14&referrer=webhooks_plugin

**Comment by TheBoatyMcBoatFace** [comment]
Sentry issue not found. Reopen if found.
