### ISSUE TITLE
Design new Q&A component

### ISSUE THREAD

**Issue by msbtterswrth** [department-of-veterans-affairs/va.gov-cms#8635]
**Design**: 
- How to add reusable Q&As from various content types.
- How to handle the “inline” Q&A editing experience in various situations, including in “Content block” (paragraph) fields. How would that work for editors with access to editing the original, vs not having access.

## Acceptance Criteria
- [ ] Testable_Outcome_X
- [ ] Testable_Outcome_Y
- [ ] Testable_Outcome_Z
- [ ] Requires design review

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Sitewide program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide crew ` (leave Sitewide unchecked and check the specific team instead)
  - [x] `⭐️ Content ops`
  - [x] `⭐️ CMS experience`
  - [ ] `⭐️ Public websites`
  - [ ] `⭐️ Facilities`
  - [ ] `⭐️ User support`

**Comment by chri5tia** [comment]
I thought it may be a good idea to reuse and refine one of the content types (Q&A) but for migration and deploy reasons, it might be better to create a brand new content type and views, and retired all the other entities and display methods.

**Comment by jilladams** [comment]
Thinking evolved here & we exposed existing Single Q&A nodes for re-use on R&S, with improvements to the "Place Q&A mechanism." Closing this. 

If we opt to COPE-ify Q&As onto additional content types, we can open new tickets to evaluate the experience for each, as needed.
