### ISSUE TITLE
Upgrade GraphQL to 8.x-3.1

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#864]
## User Story or Problem Statement

As a developer, I need to have graphql updated to its full release so I can be certain that our most critical access point is stable and protected by Drupal's security team.

It was discovered during our drupal update that switching from 3.0.0-rc3 to 3.0.0 broke our phpusnit tests and behat tests of the endpoint,  with the endpoint returning a 500 response.    Queries run by hand still worked, so something about the request method seems to have changed and will need a change both in our tests and the front end build method.   This will require a bit of investigation.

Additionally, there are some security risks related to a method of patch application - described in this [internal Slack thread](https://dsva.slack.com/archives/CT4GZBM8F/p1613426759118400).
**Note: patch mentioned in Slack thread is merged in 8.x-3.1**

## Goal
* Stable codebase with as much as possible being covered by Drupal security team coverage.

## Acceptance Criteria

- [ ] The site running the most recent full release of the GrapQL module - 8.x-3.1 https://www.drupal.org/project/graphql . _**NOTE: Upgrade to 4.0 is not in scope as it will require (re)definition of custom GraphQL schema for the project.**_
- [x] phpunit tests passing
- [x] behat tests passing
- [ ] any FE code updates are coordinated with relevant FE teams to allow content builds to work as they currently do.

**Comment by indytechcook** [comment]
Diff: https://git.drupalcode.org/project/graphql/-/compare/8.x-3.0-rc3...8.x-3.1

**Comment by indytechcook** [comment]
PR is passing tests.  I'm going to do a before/after of the pages.json to make sure they are the same.
