### ISSUE TITLE
IE is squishing story photos, and resolution is not optimized.

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#865]
**Describe the bug**

1. IE is squishing some photos on Stories, and possibly on Events. See screenshot. 
2. We have no minimum file size on these images so they get pixelated on all browsers.

See screenshot for more info

![Story_photos_-_kevin_walsh_civicactions_com_-_CivicActions_Mail](https://user-images.githubusercontent.com/643678/73083133-9c82f280-3e98-11ea-97b6-c2771d17f7bf.jpg)

**Comment by ethanteague** [comment]
Per scrum convo on 2/5, we are only going to address image squishing in ie in this task. New tasks will be created (along with discovery) to address other issues.
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/11658
