### ISSUE TITLE
Spike: research security scanning tools

### ISSUE THREAD

**Issue by cweagans** [department-of-veterans-affairs/va.gov-cms#8663]
### Description

The CMS team will investigate the appropriate tool to incorporate into our workflow so that we are informed of any relevant security disclosures as they arise.

Note: May overlap with #8626

## Acceptance Criteria 
- [ ] Identify a tool that supports: 
  - [ ] static analysis that we can add to our testing pipeline
  - [ ] continuous scanning of our servers
  - [ ] testing on a live application (so we can run it against dev or staging, for example)
- [ ] Create new ticket(s) to configure the selected tool(s)

### CMS Team
Please check the team(s) that will do this work.

- [x] `Platform CMS Team`
- [ ] `Sitewide crew `
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Public websites`
  - [ ] `⭐️ Facilities`
  - [ ] `⭐️ User support`

**Comment by cweagans** [comment]
https://github.com/mortenson/psalm-plugin-drupal looks interesting.

**Comment by TheBoatyMcBoatFace** [comment]
Handled by 
- #8213
