### ISSUE TITLE
Auto-merge dependabot PRs

### ISSUE THREAD

**Issue by cweagans** [department-of-veterans-affairs/va.gov-cms#8664]
## Description

Enable auto-merge for the daily dependabot "va-gov/content-build" pull requests.

## Acceptance Criteria 
- [ ] PR is automatically merged if the test suite passes 

## Implementation steps

* see comments

### CMS Team
Please check the team(s) that will do this work.

- [x] `Platform CMS Team`
- [ ] `Sitewide crew `
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Public websites`
  - [ ] `⭐️ Facilities`
  - [ ] `⭐️ User support`

**Comment by ElijahLynn** [comment]
We had attempted to do this a year or so ago but Dependabot removed the feature for security purposes. 

https://github.com/dependabot/dependabot-core/issues/1973

https://github.com/dependabot/dependabot-core/issues/1973#issuecomment-640918321

> Thanks for the feedback and sorry for the confusion here.
>
> Auto-merge will not be supported in GitHub-native Dependabot for the foreseeable future. We know some of you have built great workflows that rely on auto-merge, but right now, we’re concerned about auto-merge being used to quickly propagate a malicious package across the ecosystem. We recommend always verifying your dependencies before merging them.

**Comment by ElijahLynn** [comment]
Workaround: https://github.com/marketplace/actions/dependabot-auto-merge

**Comment by ElijahLynn** [comment]
But... https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions#enable-auto-merge-on-a-pull-request

**Comment by ElijahLynn** [comment]
related: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/910, https://github.com/department-of-veterans-affairs/va.gov-cms/issues/5358

**Comment by olivereri** [comment]
Wonderful context for this issue in a blog post.
https://blog.somewhatabstract.com/2021/10/11/setting-up-dependabot-with-github-actions-to-approve-and-merge/

**Comment by olivereri** [comment]
This worries me, and could add complexity:

> Do not enable auto-merging on a branch used for CD. It really is a bad idea and a big security risk. Packages do get hacked sometimes and tidying up after a malicious publish is not easy. To avoid security issues in your releases, make sure that there is a manual QA (quality assurance) step somewhere between any automated update and an actual release of the updated code. For example, you could do this by having Dependabot operate on a branch that is a copy of the CD branch and then have a process for merging the Dependabot updates across to your main branch before a release.

**Comment by olivereri** [comment]
https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions#enable-auto-merge-on-a-pull-request

**Comment by olivereri** [comment]
![image.png](https://images.zenhubusercontent.com/5f04cf8f49978b1615fee8c2/029da2e0-d262-4c5b-9ad4-75f0c0aaebc7)
https://dsva.slack.com/archives/CU1E4CX9U/p1650307570780389
```
Run gh pr review --approve "$PR_URL"
failed to create review: Message: GitHub Actions is not permitted to approve pull requests., Locations: [{Line:1 Column:66}]
Error: Process completed with exit code 1.
```

**Comment by mchelen-gov** [comment]
> This worries me, and could add complexity:
> 
> > Do not enable auto-merging on a branch used for CD. It really is a bad idea and a big security risk. Packages do get hacked sometimes and tidying up after a malicious publish is not easy. To avoid security issues in your releases, make sure that there is a manual QA (quality assurance) step somewhere between any automated update and an actual release of the updated code. For example, you could do this by having Dependabot operate on a branch that is a copy of the CD branch and then have a process for merging the Dependabot updates across to your main branch before a release.

@olivereri How was this concern addressed?

**Comment by olivereri** [comment]
> How was this concern addressed?

@mchelen-gov Addressed the concern by implementing an allow-list. That list is read by the Github Action and will only approve and merge dependencies that are on the list. Currently the only dependency we are allowing for auto-merge is `va-gov/content-build`. We sufficiently trust that dependency enough and its importance is high enough to allow it to be merged as soon as possible.

**Comment by mchelen-gov** [comment]
> > How was this concern addressed?
> 
> @mchelen-gov Addressed the concern by implementing an allow-list. That list is read by the Github Action and will only approve and merge dependencies that are on the list. Currently the only dependency we are allowing for auto-merge is `va-gov/content-build`. We sufficiently trust that dependency enough and its importance is high enough to allow it to be merged as soon as possible.

Great, thank you for explaining! Where is this documented?
