### ISSUE TITLE
Create a procedure to keep other parts of the BRD system up to date

### ISSUE THREAD

**Issue by cweagans** [department-of-veterans-affairs/va.gov-cms#8666]
### Tasks:
Ansible version updates, Jenkins security/version updates, etc. Python 2 is EOL, but BRD installs it. We need to know when those components are out of date + how to include/prioritize that work in our sprints.

### CMS Team
Please check the team(s) that will do this work.

- [x] `Platform CMS Team`
- [ ] `Sitewide crew `
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Public websites`
  - [ ] `⭐️ Facilities`
  - [ ] `⭐️ User support`

**Comment by TheBoatyMcBoatFace** [comment]
No longer applicable. Reopen if still needed.
