### ISSUE TITLE
Dump watchdog log entries and current DOM when a Cypress test fails.

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-cms#8669]
## Description
Current Behat functionality includes performing two additional actions after a test fails to aid debugging:
- dumping the last few entries from the Drupal watchdog log to stdout
- saving the current DOM to an HTML file and recording the file path to stdout

This functionality should be added to Cypress to achieve feature parity.

## Acceptance Criteria
- [ ] The last few entries from the Drupal watchdog log are added to the test output after a failure.
- [ ] The current DOM is dumped when a test fails and a downloadable file is made available to the developer.

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Sitewide program`
- [x] `Platform CMS Team`
- [ ] `Sitewide crew ` (leave Sitewide unchecked and check the specific team instead)
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Public websites`
  - [ ] `⭐️ Facilities`
  - [ ] `⭐️ User support`

**Comment by BerniXiongA6** [comment]
In SPrint 92, completed 3 points! What's left is 2 points. This can be a stretch issue in Sprint 93 if bandwidth to work on wrapping this work up.
