### ISSUE TITLE
Subsection National Health Care Service Descriptions has nothing under it and isn't used

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#8677]
## Description
From Kev in [Slack](https://dsva.slack.com/archives/CT4GZBM8F/p1649351676047219),  subsection [National health care service descriptions](https://prod.cms.va.gov/section/national-health-care-service-descriptions) should be removed as it is confusing to VHA editors

## Acceptance Criteria
- [ ] Testable_Outcome_X
- [ ] Testable_Outcome_Y
- [ ] Testable_Outcome_Z
- [ ] Requires design review

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Sitewide program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide crew ` (leave Sitewide unchecked and check the specific team instead)
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Public websites`
  - [x] `⭐️ Facilities`
  - [ ] `⭐️ User support`

**Comment by kevwalsh** [comment]
Done
