### ISSUE TITLE
Should coords be overwritten manually for adjustment?

### ISSUE THREAD

**Issue by msbtterswrth** [department-of-veterans-affairs/va.gov-cms#8678]
## Description
If the map pin is located in the incorrect spot, should the pin be adjustable? When asked, Michelle responded "possibly they'd need the ability to fine tune those...we see requests like that every now and then for VAST locations...if the lat/long is slightly off, it can make a difference on the map". Should we add it at a launch blocker or a phase two addition?

## Acceptance Criteria
- [x] Requires design review

### CMS Team
Please check the team(s) that will do this work. 

- [ ] `CMS Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide CMS Team ` (leave Sitewide unchecked and check the specific team instead)
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Offices`
  - [x] `⭐️ Product support`
  - [ ] `⭐️ User support`

**Comment by JayDarnell** [comment]
A related comment to shed light on the ultimate decision here: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/8587#issuecomment-1095481266
