### ISSUE TITLE
Change taxonomy for Spinal cord injury and disorders

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#8679]
## Description
Taxonomy request change from Steve Tokar:
For Spinal cord injury and disorders  

I would like to change the title to:  

Spinal cord injuries and disorders 

This new title matches the name of the program office, the program itself, and the text running along the top of [their website](https://www.sci.va.gov/). It’s in accordance with the wishes of the program office, and Jenny approves. Plus it makes sense from the perspective of syntax and plain language—that is, two plural nouns.  

Thanks, 

Steve

See Jira [ticket 3889](https://va-gov.atlassian.net/jira/servicedesk/projects/VAHELP/queues/custom/12/VAHELP-3889)

## Acceptance Criteria
- [ ] Testable_Outcome_X
- [ ] Testable_Outcome_Y
- [ ] Testable_Outcome_Z
- [ ] Requires design review

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Sitewide program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide crew ` (leave Sitewide unchecked and check the specific team instead)
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Public websites`
  - [x] `⭐️ Facilities`
  - [ ] `⭐️ User support`

**Comment by kevwalsh** [comment]
I went ahead and updated this at https://prod.cms.va.gov/health-care/spinal-cord-injury-and-disorders
