### ISSUE TITLE
[Fig - > Storybook] Finalized input styles + states

### ISSUE THREAD

**Issue by EWashb** [department-of-veterans-affairs/va.gov-cms#8682]
Implementation of design recs from #8497 

Figma: https://www.figma.com/file/ScABI31f3MRFEvQ8WitVPa/CMS-Design-System?node-id=1178%3A109613 

ACs
Changes to the following aspects of section label design are added to Storybook for further testing and iteration:
- [ ] Section input styles exist in Storybook that showcases different input styles and states:
   - [ ] 
   - [ ] 
   - [ ]

**Comment by cmaeng** [comment]
will need updates on how this relates to other storybook issues. removing from sprint 56 for now
