### ISSUE TITLE
Spike: images, image styles and JSON API

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#8690]
## Description
We need to be able to retrieve images via JSON:API. This is not as simple as shipping all images to S3, because image styles are built more or less on-demand.

Currently Metalsmith/content-build handles this by reading every generated HTML, finding all references to file assets, literally retrieving them at that time, and packaging them up to ship.

Note that in order to maintain existing system functionality, we need to expose a way for Next to retrieve images with identified Drupal image styles. There are a few paths here. Notes on modules and approaches:
* https://www.drupal.org/project/jsonapi_image_styles
* https://www.drupal.org/project/consumer_image_styles
* https://www.drupal.org/project/drupal/issues/2825812
* https://www.lullabot.com/articles/decoupled-drupal-hard-problems-image-styles

There is also the larger question of whether Drupal should be computing image styles at all, but addressing that question is outside the scope of this ticket. We simply need a way for Next to retrieve image style URLs via JSON API.

## Acceptance Criteria
- [ ] Testable_Outcome_X
- [ ] Testable_Outcome_Y
- [ ] Testable_Outcome_Z
- [ ] Requires design review

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Sitewide program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide crew ` (leave Sitewide unchecked and check the specific team instead)
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Public websites`
  - [ ] `⭐️ Facilities`
  - [ ] `⭐️ User support`

**Comment by jkalexander7** [comment]
Closing - duplicate ticket
