### ISSUE TITLE
Update readmes to reference airtable spec tool

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#8705]
## Description

/vagov/READMES/testing.md
/vagov/READMES/workflow.md

## Acceptance Criteria
- [x] All existing spectool links point to the new location
- [x] Reference directions are updated if needed.
- [x] Old spec tool has a new sheet with a message about it being depricated and has link to new version.

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Sitewide program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide crew ` (leave Sitewide unchecked and check the specific team instead)
  - [x] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Public websites`
  - [ ] `⭐️ Facilities`
  - [ ] `⭐️ User support`

**Comment by msbtterswrth** [comment]
@swirtSJW I have updated the two readmes above which were the only two place _I_  know of that linked to the spec tool, do you know of others or how I might reverse search for links to it?
