### ISSUE TITLE
Remove `field_facility_service_hours` from paragraph type `service_location`

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#8709]
## ACs
- [ ] field_facility_service_hours has been removed from paragraph: service_location
- [ ] Proper field data delete has been run in hook_update_n

**Comment by JayDarnell** [comment]
Attempting to delete the field from the paragraph (after running an update hook to delete the data for the field) results in a slew of warnings

`Warning: array_key_exists() expects parameter 2 to be array, string given in Drupal\tablefield\Plugin\Field\FieldType\TablefieldItem->setValue() (line 175 of modules/contrib/tablefield/src/Plugin/Field/FieldType/TablefieldItem.php).
Warning: count(): Parameter must be an array or an object that implements Countable in Drupal\tablefield\Plugin\Field\FieldType\TablefieldItem->setValue() (line 178 of modules/contrib/tablefield/src/Plugin/Field/FieldType/TablefieldItem.php).
Warning: count(): Parameter must be an array or an object that implements Countable in Drupal\tablefield\Plugin\Field\FieldType\TablefieldItem->setValue() (line 179 of modules/contrib/tablefield/src/Plugin/Field/FieldType/TablefieldItem.php).
Warning: Invalid argument supplied for foreach() in Drupal\tablefield\Plugin\Field\FieldType\TablefieldItem->setValue() (line 186 of modules/contrib/tablefield/src/Plugin/Field/FieldType/TablefieldItem.php).
Warning: array_key_exists() expects parameter 2 to be array, string given in Drupal\tablefield\Plugin\Field\FieldType\TablefieldItem->setValue() (line 175 of modules/contrib/tablefield/src/Plugin/Field/FieldType/TablefieldItem.php).
Warning: count(): Parameter must be an array or an object that implements Countable in Drupal\tablefield\Plugin\Field\FieldType\TablefieldItem->setValue() (line 178 of modules/contrib/tablefield/src/Plugin/Field/FieldType/TablefieldItem.php).
Warning: count(): Parameter must be an array or an object that implements Countable in Drupal\tablefield\Plugin\Field\FieldType\TablefieldItem->setValue() (line 179 of modules/contrib/tablefield/src/Plugin/Field/FieldType/TablefieldItem.php).
Warning: Invalid argument supplied for foreach() in Drupal\tablefield\Plugin\Field\FieldType\TablefieldItem->setValue() (line 186 of modules/contrib/tablefield/src/Plugin/Field/FieldType/TablefieldItem.php).
Warning: array_key_exists() expects parameter 2 to be array, string given in Drupal\tablefield\Plugin\Field\FieldType\TablefieldItem->setValue() (line 175 of modules/contrib/tablefield/src/Plugin/Field/FieldType/TablefieldItem.php).
Warning: count(): Parameter must be an array or an object that implements Countable in Drupal\tablefield\Plugin\Field\FieldType\TablefieldItem->setValue() (line 178 of modules/contrib/tablefield/src/Plugin/Field/FieldType/TablefieldItem.php).
Warning: count(): Parameter must be an array or an object that implements Countable in Drupal\tablefield\Plugin\Field\FieldType\TablefieldItem->setValue() (line 179 of modules/contrib/tablefield/src/Plugin/Field/FieldType/TablefieldItem.php).
Warning: Invalid argument supplied for foreach() in Drupal\tablefield\Plugin\Field\FieldType\TablefieldItem->setValue() (line 186 of modules/contrib/tablefield/src/Plugin/Field/FieldType/TablefieldItem.php).
Warning: array_key_exists() expects parameter 2 to be array, string given in Drupal\tablefield\Plugin\Field\FieldType\TablefieldItem->setValue() (line 175 of modules/contrib/tablefield/src/Plugin/Field/FieldType/TablefieldItem.php).
Warning: count(): Parameter must be an array or an object that implements Countable in Drupal\tablefield\Plugin\Field\FieldType\TablefieldItem->setValue() (line 178 of modules/contrib/tablefield/src/Plugin/Field/FieldType/TablefieldItem.php).
Warning: count(): Parameter must be an array or an object that implements Countable in Drupal\tablefield\Plugin\Field\FieldType\TablefieldItem->setValue() (line 179 of modules/contrib/tablefield/src/Plugin/Field/FieldType/TablefieldItem.php).
Warning: Invalid argument supplied for foreach() in Drupal\tablefield\Plugin\Field\FieldType\TablefieldItem->setValue() (line 186 of modules/contrib/tablefield/src/Plugin/Field/FieldType/TablefieldItem.php).
Warning: array_key_exists() expects parameter 2 to be array, string given in Drupal\tablefield\Plugin\Field\FieldType\TablefieldItem->setValue() (line 175 of modules/contrib/tablefield/src/Plugin/Field/FieldType/TablefieldItem.php).
Warning: count(): Parameter must be an array or an object that implements Countable in Drupal\tablefield\Plugin\Field\FieldType\TablefieldItem->setValue() (line 178 of modules/contrib/tablefield/src/Plugin/Field/FieldType/TablefieldItem.php).
Warning: count(): Parameter must be an array or an object that implements Countable in Drupal\tablefield\Plugin\Field\FieldType\TablefieldItem->setValue() (line 179 of modules/contrib/tablefield/src/Plugin/Field/FieldType/TablefieldItem.php).
Warning: Invalid argument supplied for foreach() in Drupal\tablefield\Plugin\Field\FieldType\TablefieldItem->setValue() (line 186 of modules/contrib/tablefield/src/Plugin/Field/FieldType/TablefieldItem.php).
Warning: array_key_exists() expects parameter 2 to be array, string given in Drupal\tablefield\Plugin\Field\FieldType\TablefieldItem->setValue() (line 175 of modules/contrib/tablefield/src/Plugin/Field/FieldType/TablefieldItem.php).
Warning: count(): Parameter must be an array or an object that implements Countable in Drupal\tablefield\Plugin\Field\FieldType\TablefieldItem->setValue() (line 178 of modules/contrib/tablefield/src/Plugin/Field/FieldType/TablefieldItem.php).
Warning: count(): Parameter must be an array or an object that implements Countable in Drupal\tablefield\Plugin\Field\FieldType\TablefieldItem->setValue() (line 179 of modules/contrib/tablefield/src/Plugin/Field/FieldType/TablefieldItem.php).
Warning: Invalid argument supplied for foreach() in Drupal\tablefield\Plugin\Field\FieldType\TablefieldItem->setValue() (line 186 of modules/contrib/tablefield/src/Plugin/Field/FieldType/TablefieldItem.php).
Warning: array_key_exists() expects parameter 2 to be array, string given in Drupal\tablefield\Plugin\Field\FieldType\TablefieldItem->setValue() (line 175 of modules/contrib/tablefield/src/Plugin/Field/FieldType/TablefieldItem.php).
Warning: count(): Parameter must be an array or an object that implements Countable in Drupal\tablefield\Plugin\Field\FieldType\TablefieldItem->setValue() (line 178 of modules/contrib/tablefield/src/Plugin/Field/FieldType/TablefieldItem.php).
Warning: count(): Parameter must be an array or an object that implements Countable in Drupal\tablefield\Plugin\Field\FieldType\TablefieldItem->setValue() (line 179 of modules/contrib/tablefield/src/Plugin/Field/FieldType/TablefieldItem.php).
Warning: Invalid argument supplied for foreach() in Drupal\tablefield\Plugin\Field\FieldType\TablefieldItem->setValue() (line 186 of modules/contrib/tablefield/src/Plugin/Field/FieldType/TablefieldItem.php).
Warning: array_key_exists() expects parameter 2 to be array, string given in Drupal\tablefield\Plugin\Field\FieldType\TablefieldItem->setValue() (line 175 of modules/contrib/tablefield/src/Plugin/Field/FieldType/TablefieldItem.php).
Warning: count(): Parameter must be an array or an object that implements Countable in Drupal\tablefield\Plugin\Field\FieldType\TablefieldItem->setValue() (line 178 of modules/contrib/tablefield/src/Plugin/Field/FieldType/TablefieldItem.php).
Warning: count(): Parameter must be an array or an object that implements Countable in Drupal\tablefield\Plugin\Field\FieldType\TablefieldItem->setValue() (line 179 of modules/contrib/tablefield/src/Plugin/Field/FieldType/TablefieldItem.php).
Warning: Invalid argument supplied for foreach() in Drupal\tablefield\Plugin\Field\FieldType\TablefieldItem->setValue() (line 186 of modules/contrib/tablefield/src/Plugin/Field/FieldType/TablefieldItem.php).
Warning: array_key_exists() expects parameter 2 to be array, string given in Drupal\tablefield\Plugin\Field\FieldType\TablefieldItem->setValue() (line 175 of modules/contrib/tablefield/src/Plugin/Field/FieldType/TablefieldItem.php).
Warning: count(): Parameter must be an array or an object that implements Countable in Drupal\tablefield\Plugin\Field\FieldType\TablefieldItem->setValue() (line 178 of modules/contrib/tablefield/src/Plugin/Field/FieldType/TablefieldItem.php).
Warning: count(): Parameter must be an array or an object that implements Countable in Drupal\tablefield\Plugin\Field\FieldType\TablefieldItem->setValue() (line 179 of modules/contrib/tablefield/src/Plugin/Field/FieldType/TablefieldItem.php).
Warning: Invalid argument supplied for foreach() in Drupal\tablefield\Plugin\Field\FieldType\TablefieldItem->setValue() (line 186 of modules/contrib/tablefield/src/Plugin/Field/FieldType/TablefieldItem.php).
Warning: array_key_exists() expects parameter 2 to be array, string given in Drupal\tablefield\Plugin\Field\FieldType\TablefieldItem->setValue() (line 175 of modules/contrib/tablefield/src/Plugin/Field/FieldType/TablefieldItem.php).
Warning: count(): Parameter must be an array or an object that implements Countable in Drupal\tablefield\Plugin\Field\FieldType\TablefieldItem->setValue() (line 178 of modules/contrib/tablefield/src/Plugin/Field/FieldType/TablefieldItem.php).
Warning: count(): Parameter must be an array or an object that implements Countable in Drupal\tablefield\Plugin\Field\FieldType\TablefieldItem->setValue() (line 179 of modules/contrib/tablefield/src/Plugin/Field/FieldType/TablefieldItem.php).
Warning: Invalid argument supplied for foreach() in Drupal\tablefield\Plugin\Field\FieldType\TablefieldItem->setValue() (line 186 of modules/contrib/tablefield/src/Plugin/Field/FieldType/TablefieldItem.php).`

**Comment by JayDarnell** [comment]
@swirtSJW do you think I need to be concerned with the above? They disappear on the next refresh so maybe its just the field cached in the render process when the page first reloads?
