### ISSUE TITLE
Audit of phone number appearances

### ISSUE THREAD

**Issue by EWashb** [department-of-veterans-affairs/va.gov-cms#8718]
## Problem Statement

Before discovery can be done of the possible solutions to provide consistency for phone numbers across the CMS, we need to do an audit of all the places. The audit should include rich text fields that encourage phone number additions. 

Also related to #1964

**Comment by msbtterswrth** [comment]
The fields in this [airtable view](https://airtable.com/shriA7I1QcXasmb4k) look to be the only ones explicitly storing phone number data. I'm not sure if you want me to manually search though all the rich text fields for phone numbers as part of this ticket? I'm not even sure how feasible that would be...

**Comment by EWashb** [comment]
There are a few different ways phone numbers are appearing, as found in this [airtable audit](https://airtable.com/shriA7I1QcXasmb4k/tblPdSdScGDeV1Y6f). 

However, auditing rich text fields will need to be done via regex in order to capture the correct data. We need to address whether the information we have is sufficient to implement the CKeditor option or another approach for rich text fields since so much variation exists. There is also an accessibility issue since there is no consistent implementation of ARIA labels.

Many variations of phone numbers exist with the preliminary audit for rich text. This may be sufficient data to justify a unified approach for rich text fields without learning each variant @kevwalsh
