### ISSUE TITLE
Instrument content build with Datadog APM

### ISSUE THREAD

**Issue by cweagans** [department-of-veterans-affairs/va.gov-cms#8724]
## Description

Content build timing is something that we spend a lot of brain cycles on. We should monitor specific timing info with Datadog's APM product. In theory, Datadog APM should automatically instrument Node.js applications, but I'd really like to see individual spans for each metalsmith plugin + info about all of the individual transformations that happen inside of the plugins so that we can see where build time is spent.

The Datadog tracing functionality is useful, but the _profiling_ functionality is what we really want.

I already took a crack at this in https://github.com/department-of-veterans-affairs/content-build/pull/1063 and https://github.com/department-of-veterans-affairs/content-build/pull/1064 . I wasn't able to get it to actually send data to Datadog, but there were a couple of interesting things that came out of it:

* The self hosted runners have a datadog agent running already, but it appears to not have the apm components enabled. To work around that, I started up a separate datadog agent in a docker container [here](https://github.com/department-of-veterans-affairs/content-build/pull/1064/files#diff-82ac6be184baa66c2f185b7a0a6ec80a6f5e0bea60cd69ee94715c243cdbd61bR159-R161) and configured the datadog library to use the new agent [here](https://github.com/department-of-veterans-affairs/content-build/pull/1064/files#diff-82ac6be184baa66c2f185b7a0a6ec80a6f5e0bea60cd69ee94715c243cdbd61bR182-R190). Either of those things might be incorrect, but it's a starting point at least.
* The datadog agent may not send data to the DD API immediately. A lot of the APM stuff for Node.js appears to be tailored to long-running process (like Express.js applications that start up once and run forever). It's possible that we'll need to figure out how to force the datadog agent to send APM data immediately. It's also possible that an easier path would be to use Datadog's [OpenTelemetry](https://docs.datadoghq.com/tracing/setup_overview/open_standards/) support to send metrics instead of the datadog agent. That might be a more predictable path forward, especially since we want tracing and profiling on every content build run.

## Acceptance Criteria

- [ ] Verify with Datadog team whether a DD agent can send data to the DD API immediately

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Sitewide program`
- [x] `Platform CMS Team`
- [ ] `Sitewide crew ` (leave Sitewide unchecked and check the specific team instead)
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Public websites`
  - [ ] `⭐️ Facilities`
  - [ ] `⭐️ User support`

**Comment by TheBoatyMcBoatFace** [comment]
Not an immediate focus. Reopen if necessary.
