### ISSUE TITLE
Gain experience / understanding of URL redirects 

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#8726]
## ACs

- [x] Members of Public Websites team are ready to respond to a URL redirect request from Mikki
- [x] Mikki knows who to assign a request to
- [x] A redirect request has been processed through completion (a Vet Center or other facility redirect)

Existing facilities redirect requests as of April 14, 2022:
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/39781
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/39552
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/39780
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/39556
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/39558
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/39778
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/39782

**Comment by kevwalsh** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VAgov-CMS-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/8726?planning-poker) with ZenHub @allisonlu @ryguyk

**Comment by jilladams** [comment]
4/11 meeting with Mikki, Jay, Ryan, Allison, Jill: 

Decoupled nature of our Drupal instance means Drupal redirects don't work for front-end pages.

Current process: 
* Redirects have a Github issue template, auto-assigned to Mikki. 
* Jay creates redirect requests for Facilities.
* To date, all redirects go through Mikki for Quality control (sometimes even direct via email). Mikki vets the request (often redirect requests are from / to incorrect URLs, or request vanity URLs that are unapproved). Mikki will reject invalid / unapproved asks.
* If request is valid, Mikki reviews, tags with Public Websites, and removes herself as Assignee.
* Some redirects for Drupal pages require coordination with other teams re: timing. (Facilities pages, Content pages).
    * Content pages redirects may now be coordinated internally within Public Websites team since we now own front end as well as CMS.
* Redirects for modernized pages must be documented. Mikki manages the spreadsheet / sitemap for this.
* 2 week SLA to respond to / fulfill requests. Redirect process itself takes a couple of hours. Helpful to batch them. SLA timeframe can be updated if we need to, with discussion/approval.
* Redirects must be validated in Staging prior to Prod. (Redirects have been wrongly directed before.)

New world: 
* Mikki would like to offload review of Facilities redirects. Not settled completely, TBD. In the near-term: Mikki will pass Facilities requests on quickly. Mid-term: Jay can cut Facilities redirects directly to Public Websites team.
    * Longer-term: ideally Facilities will handle their own requests.
* For non-Facilities redirects: Near-term, Mikki will continue to vet the requests. Longer-term: Mikki might be able to move to "informed" and not a blocker.
* Mikki will assign issues to Jill for air traffic control purposes. If we need to update that process in future, include Mikki in the discussion.

We'll start with the existing Facilities closures redirects that Jay has opened (6-7).

**Comment by jilladams** [comment]
Technical side: makign the change is a key pair entry in a yaml file.
