### ISSUE TITLE
Install Cypress Front-end Testing Tool on BRD

### ISSUE THREAD

**Issue by olivereri** [department-of-veterans-affairs/va.gov-cms#8728]
## Description
#8675 when complete will port over Behat tests to Cypress.  Critically important is that Cypress is installed on BRD to execute tests. This issue blocks 8675.

## Acceptance Criteria
- [x] Cypress Front-end testing software/dependencies is installed on BRD AMI.
- [x] Ported Cypress tests function as intended on BRD STAGING.

**Comment by olivereri** [comment]
Thinking about `Ported Cypress tests function as intended on BRD STAGING.`  again makes me want to come up to a 5.

**Comment by ndouglas** [comment]
It should be a 3, but, y'know...

**Comment by ndouglas** [comment]
Note that Cypress itself is installed on-demand in `scripts/tests/cypress.sh`, so this probably will just involve installing the platform prerequisites.
