### ISSUE TITLE
Create audit for "Why can't I edit this" tool tips

### ISSUE THREAD

**Issue by ContentBrewmaster** [department-of-veterans-affairs/va.gov-cms#8732]
## Description
The CMS gives authors information via a clickable tool tip about nodes where content is automatically updated from centralized databases. To ensure we have considered change management for these areas, product teams need to be able to audit the CMS for placement of this particular tool tip. 

[Example](https://cms-training-qtpbfivdfzrlrlyiqwmanznaobpek1ca.demo.cms.va.gov/syracuse-health-care/locations/syracuse-va-medical-center)

## Acceptance Criteria
- [ ] Product teams can identify the presence of the tool tip via an audit report

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Sitewide program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide crew ` (leave Sitewide unchecked and check the specific team instead)
  - [x] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Public websites`
  - [ ] `⭐️ Facilities`
  - [ ] `⭐️ User support`

**Comment by msbtterswrth** [comment]
Audit of existing fields using this pattern can be found here: https://airtable.com/shr50Po4f0ccueRNY
