### ISSUE TITLE
Inline guidance: prototype

### ISSUE THREAD

**Issue by rachel-kauff** [department-of-veterans-affairs/va.gov-cms#8750]
## Background

See the epic-level information for more on the design intent. Summary is:

- Mock up of how inline content guidance could be used to support better alt text (ideation in collab w/ Josh Kim): [Figma: Media Library UI](https://www.figma.com/file/Bicr5pUbygcToLltOYtD4X/Media-library-UI?node-id=0%3A1)
- [An ancient treatise on help text](https://app.mural.co/t/vagov6717/m/vagov6717/1586882180337/415aa0adba23f935239d291d83fda234b16f1957)
- [VA design system: "Additional info" component](https://design.va.gov/components/additional-info)

ACs
- [ ] Inline guidance pattern is designed in alignment with the design system 
- [ ] Component guidance content is adapted from guidelines established in (#ticket)
- [ ] Tech handoff with developer

**Comment by rachel-kauff** [comment]
After discussion with @suzanne-gray and Sitewide content folks, we decided this initiative would benefit from gathering some data first. Will be creating a separate ticket for that and pushing this one back into the 'log. cc: @EWashb

**Comment by mgifford** [comment]
This is the current alt text for an image field:

![Screen Shot of Drupal default](https://user-images.githubusercontent.com/116832/183487261-c848d19b-74f9-400a-a2bf-a6877ca3e950.png)

And an alternative:
![Screen Shot with modified description text](https://user-images.githubusercontent.com/116832/183487403-037e492c-1e9a-4fdd-a354-718ce5d23ab2.png)

This is would look for CKEditor:
![Screen Shot of CKEditor interface in Drupal with modified text](https://user-images.githubusercontent.com/116832/183487490-670ec586-2321-4743-a294-2336394eb847.png)

**Comment by EWashb** [comment]
Thank you @mgifford! This is very helpful as we explore alt text guidance.

**Comment by EWashb** [comment]
@mgifford is this an OOTB drupal module?

**Comment by EWashb** [comment]
@cjterdi there have been some changes to the original prototype scope. @valerierunde @laflannery and I will be meeting with the 508 office to confirm guidance and then we will pass over the correct guidance to you.

This is not going to be tested with users, but the developers will need a prototype to use for development.

**Comment by EWashb** [comment]
Sorry @mgifford. Out of the box

**Comment by mgifford** [comment]
That should be what Drupal comes with OOTB. :)

No extra modules required.  I think someone at some point decided to disable the requirement for alt text in the VA's content types. It should be something that can just be enabled for every content type (which is how it was set up by default when they were created).

**Comment by EWashb** [comment]
Ahh. Thank you @mgifford :) That is extremely helpful. We plan to implement this very soon and I'll pass this info over to our dev team!

**Comment by EWashb** [comment]
After further review, we will not require a complete prototype because we are launching a boiled-down version of extended help text for alt text. However, @cjterdi's refined designs have been reflected in the figma and once the twig templates are created, we will launch those designs.
