### ISSUE TITLE
Inline guidance: conduct usability research

### ISSUE THREAD

**Issue by rachel-kauff** [department-of-veterans-affairs/va.gov-cms#8751]
Process steps
- Find a note taker for each session
- Take verbatim notes or capture a refined audio transcript using the [session notes template](https://docs.google.com/document/d/1G1j2xZEQDrTJQ7fAYTIlE9mR4d4yXc2oiGgH0kWXYuw/edit#)
- [If required] : prepare a session report using the [VA session report template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/synthesis/session-report-template.md)
- Send a thank you follow up 1-3 days after session

ACs
- [ ] Usability sessions are conducted with X participants
- [ ] Sessions are documented with verbatim notes

**Comment by valerierunde** [comment]
Direction has changed and no research will be done on this. Instead, we will implement changes and re-audit in a few months time to check progress on alt-text quality.
