### ISSUE TITLE
Media field widget changes for test

### ISSUE THREAD

**Issue by EWashb** [department-of-veterans-affairs/va.gov-cms#8754]
## Background

In order to alleviate confusion with the media library upload functionality, it has been determined that a good place to begin is to swap out the current facility media field with the Inline Entity Form- Complex widget on the "Create Vet Center" content type. 

See [this mural](https://app.mural.co/t/vagov6717/m/vagov6717/1649873410710/17d9646cd15635d87459332dfe1caa49de1c1831?sender=ud7d3055567694e54f0133356) about the Vet Center editor experience for screenshots. 

Current WIP [design doc](https://www.figma.com/file/azAMnMED4F8W0nvoHpvQGe/WIP---Vet-Center-media-upload?node-id=21%3A19229). 

## Acceptance Criteria
- [ ] Inline Entity Form-Complex widget is applied to the media field in test
- [ ] Hide the "name" and "description" sections
- [ ] Add a thumbnail option for uploaded photos
- [ ] Remove "add a photo of the facility"
- [ ] Remove table heading 
- [ ] Handoff for UX writing updates and design review

**Comment by rachel-kauff** [comment]
See discussion here: https://dsva.slack.com/archives/CDKB88PS8/p1650290742360679

**Comment by rachel-kauff** [comment]
Updated design file with clickable prototype: https://www.figma.com/file/azAMnMED4F8W0nvoHpvQGe/WIP---Vet-Center-media-upload?node-id=0%3A1

**Comment by msbtterswrth** [comment]
folded this into a bigger #3969 so i'm closing in favor of that one.
