### ISSUE TITLE
Determine FE cropping options and dependencies

### ISSUE THREAD

**Issue by EWashb** [department-of-veterans-affairs/va.gov-cms#8756]
## Background

Before a final cropping experience can be determined across media types, we need to understand what the FE dependencies and guidelines are for the various images. In order for the CMS team to make an educated decision on how to surface cropping to CMS editors, we must figure out all of the FE dependencies. 

Related to #3969

## Assumptions

In doing an audit, we can first determine what would work for Vet Center facilities and get an understanding of what the other media requirements are. 

From a dev and design sync, some options for cropping are:

1. Hide the UI field altogether
2. Only show the cropping options that pertain to the specific use case
3. Integrate focal point

## Acceptance Criteria

- [x] audit of FE crop ratios for each media type
- [x] review of FE media cropping options with CMS dev and design 
- [x] recommend technically feasible option(s) for the Vet Center facility page

**Comment by msbtterswrth** [comment]
did a little review of field_media (or field_image) in drupal and put the aspect ratios in the 'notes' column [here](https://airtable.com/shroCd6M54E2khmZ4). Looks like most fields use 3:2, with the exception of banners and events (which use 7:2) and profiles (which use square).
