### ISSUE TITLE
Outreach events have bad breadcrumbs

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#877]
**Describe the bug**
Bad breadcrumb on Outreach events

**To Reproduce**
1. Create an event and add to outreach and events calendar (may apply to other calendars)
2. Build front end or click preview.
3. See bad breadcrumb, including "node".

(currently on prod preview at http://preview-prod.vfs.va.gov/preview?nodeId=2545)

**Expected behavior**

**Screenshots**

![Outreach_events___Rock_Hill__South_Carolina_Veteran_Resources_Seminar___Veterans_Affairs](https://user-images.githubusercontent.com/643678/73667943-0eb2be80-4673-11ea-86a8-219fa53f7273.jpg)

**Comment by ethanteague** [comment]
@kevwalsh - fix pr here: https://github.com/department-of-veterans-affairs/va.gov-cms/pull/879
