### ISSUE TITLE
CMS-CI WEB builds are failing

### ISSUE THREAD

**Issue by ElijahLynn** [department-of-veterans-affairs/va.gov-cms#878]
https://dsva.slack.com/archives/CT4GZBM8F/p1580507634250900

cc @ethanteague @swirtSJW - can you add any relevant info here. 

Updated Task List:

- [x] Submit PR for build code to also look for *.ci.cms.va.gov (currently only *.cms.va.gov)
https://github.com/department-of-veterans-affairs/vets-website/pull/11638
- [x] Revert the revert at https://prod.cms.va.gov/node/296/revisions
- [x] Trigger new backup
- [x] Run `cms-db-download` on CI to get new DB
- [ ] Create postmortem of incident

**Comment by jonpugh** [comment]
On it.

**Comment by jonpugh** [comment]
![Screenshot from 2020-02-03 13-19-59](https://user-images.githubusercontent.com/106420/73681882-39117580-468d-11ea-8856-4f949ef556a1.png)

This is happening across environments since #867 was merged.

@swirtSJW and I talked it through... PHPUnit now tests alerts, which is triggering remote builds.

PHPUnit is only testing that the build request was received. It is not testing the output of the remote build.
## Solution?

### Disable remote builds:
  1. [ ] During Behat tests, in any environment. Behat tests run WEB build themselves so they will wait until ready to continue testing.
  1. [ ] During PHPUnit tests, in CI. The PHPUnit tests are now responsible for Alerts testing. 
So in DevShop, it doesn't have to do anything: the rebuild request can be mocked, since the `va:web:build` command is run by behat tests and the output is checked.
### Enable remote builds:
  1. [ ] In BRD dev & staging to confirm BRD Jenkins compatibility.

### Implementation  
- [x] Add a Drupal setting to block remote builds: `va_gov.build.web.build.disable_triggers'
- [ ] Add

**Comment by jonpugh** [comment]
As for the actual error, it seems this is on the WEB site:

```
 cd web && npm run build -- --pull-drupal  --no-drupal-proxy
/var/aegir/projects/cms/pr876/docroot/vendor/va-gov/web/src/site/stages/build/index.js:245
    if (err) throw err;
             ^

TypeError: Cannot read property 'data' of undefined
    at formatHeaderData (/var/aegir/projects/cms/pr876/docroot/vendor/va-gov/web/src/site/stages/build/drupal/menus.js:267:31)
    at Ware.<anonymous> (/var/aegir/projects/cms/pr876/docroot/vendor/va-gov/web/src/site/stages/build/plugins/create-header-footer.js:88:34)
    at Ware.<anonymous> (/var/aegir/projects/cms/pr876/docroot/vendor/va-gov/web/node_modules/wrap-fn/index.js:45:19)
    at next (/var/aegir/projects/cms/pr876/docroot/vendor/va-gov/web/node_modules/ware/lib/index.js:85:20)
    at /var/aegir/projects/cms/pr876/docroot/vendor/va-gov/web/node_modules/wrap-fn/index.js:121:18
    at Ware.<anonymous> (/var/aegir/projects/cms/pr876/docroot/vendor/va-gov/web/node_modules/wrap-fn/index.js:83:42)
    at Ware.<anonymous> (/var/aegir/projects/cms/pr876/docroot/vendor/va-gov/web/node_modules/wrap-fn/index.js:57:27)
    at next (/var/aegir/projects/cms/pr876/docroot/vendor/va-gov/web/node_modules/ware/lib/index.js:85:20)
    at /var/aegir/projects/cms/pr876/docroot/vendor/va-gov/web/node_modules/wrap-fn/index.js:121:18
    at Ware.<anonymous> (/var/aegir/projects/cms/pr876/docroot/vendor/va-gov/web/node_modules/wrap-fn/index.js:83:42)
    at Ware.<anonymous> (/var/aegir/projects/cms/pr876/docroot/vendor/va-gov/web/node_modules/wrap-fn/index.js:57:27)
    at next (/var/aegir/projects/cms/pr876/docroot/vendor/va-gov/web/node_modules/ware/lib/index.js:85:20)
    at /var/aegir/projects/cms/pr876/docroot/vendor/va-gov/web/node_modules/wrap-fn/index.js:121:18
    at Ware.<anonymous> (/var/aegir/projects/cms/pr876/docroot/vendor/va-gov/web/src/site/stages/build/plugins/create-feature-toggles.js:33:5)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by jonpugh** [comment]
│ Step 2 start: Get Drupal content
      │ Drupal content unavailable in local cache: /var/aegir/projects/cms/pr880/docroot/vendor/va-gov/web/.cache/localhost/drupal/pages.json
      │ Attempting to load Drupal content from API at http://pr880.ci.cms.va.gov
      │ http://pr880.ci.cms.va.gov response time: : 53968.392ms
      │ Drupal successfully loaded!
      │ TypeError: Cannot read property '0' of null
      │     at Node.doc.each (/var/aegir/projects/cms/pr880/docroot/vendor/va-gov/web/src/site/stages/build/drupal/assets.js:60:6)

**Comment by jonpugh** [comment]
>    │   480493  03/Feb 14:39  php       error     Symfony\Component\HttpKernel\Exception\UnauthorizedHttpException: No authentication credentials provided. in Drupal\basic_auth\Authentication\Provider\BasicAuth->challengeException() (line

**Comment by ElijahLynn** [comment]
#880 and #886 are part of this.

**Comment by ElijahLynn** [comment]
Seems like the initial issue might be fixed with #886 merged. However, we have a single & small package update in #888 that is failing with a similar error still so going to keep this open and rubber duck here. 
> TypeError: Cannot read property '0' of null

**Comment by jonpugh** [comment]
Rescoping this to the WEB build failures.

Debugging info coming now

**Comment by jonpugh** [comment]
```
tree --du -h .npm
 6.4M used in 502 directories, 280 files
```
```
tree --du -h .yarn
8.0K used in 1 directory, 0 files
```
```
tree --du -h .cache
....
```

**Comment by jonpugh** [comment]
# 882M used in 30797 directories, 122310 files

**Comment by jonpugh** [comment]
Interesting...
Found a file in .config that appears to be a way to not update NPM?

```
aegir@devshop ~ $ cat .config/configstore/update-notifier-npm.json 
{
	"optOut": false,
	"lastUpdateCheck": 1580829736903
}
```

**Comment by jonpugh** [comment]
```
/var/aegir/projects/cms/pr903/docroot/vendor/va-gov/web/src/site/stages/build/index.js:245
    if (err) throw err;
             ^

TypeError: Cannot read property 'data' of undefined
    at formatHeaderData (/var/aegir/projects/cms/pr903/docroot/vendor/va-gov/web/src/site/stages/build/drupal/menus.js:267:31)
    at Ware.<anonymous> (/var/aegir/projects/cms/pr903/docroot/vendor/va-gov/web/src/site/stages/build/plugins/create-header-footer.js:88:34)
    at Ware.<anonymous> (/var/aegir/projects/cms/pr903/docroot/vendor/va-gov/web/node_modules/wrap-fn/index.js:45:19)
    at next (/var/aegir/projects/cms/pr903/docroot/vendor/va-gov/web/node_modules/ware/lib/index.js:85:20)
    at /var/aegir/projects/cms/pr903/docroot/vendor/va-gov/web/node_modules/wrap-fn/index.js:121:18
    at Ware.<anonymous> (/var/aegir/projects/cms/pr903/docroot/vendor/va-gov/web/node_modules/wrap-fn/index.js:83:42)
    at Ware.<anonymous> (/var/aegir/projects/cms/pr903/docroot/vendor/va-gov/web/node_modules/wrap-fn/index.js:57:27)
    at next (/var/aegir/projects/cms/pr903/docroot/vendor/va-gov/web/node_modules/ware/lib/index.js:85:20)
    at /var/aegir/projects/cms/pr903/docroot/vendor/va-gov/web/node_modules/wrap-fn/index.js:121:18
    at Ware.<anonymous> (/var/aegir/projects/cms/pr903/docroot/vendor/va-gov/web/node_modules/wrap-fn/index.js:83:42)
    at Ware.<anonymous> (/var/aegir/projects/cms/pr903/docroot/vendor/va-gov/web/node_modules/wrap-fn/index.js:57:27)
    at next (/var/aegir/projects/cms/pr903/docroot/vendor/va-gov/web/node_modules/ware/lib/index.js:85:20)
    at /var/aegir/projects/cms/pr903/docroot/vendor/va-gov/web/node_modules/wrap-fn/index.js:121:18
    at Ware.<anonymous> (/var/aegir/projects/cms/pr903/docroot/vendor/va-gov/web/src/site/stages/build/plugins/create-feature-toggles.js:33:5)
    at process._tickCallback (internal/process/next_tick.js:68:7)

npm
 ERR! code ELIFECYCLE

npm
 ERR! errno
 1

npm
 ERR! vets-website@1.0.0 build: `node --max-old-space-size=4096 script/build.js "--pull-drupal" "--no-drupal-proxy"`
npm
 ERR!
 Exit status 1

npm
 ERR!
 

npm 
ERR!
 Failed at the vets-website@1.0.0 build script.

npm 
ERR!
 This is probably not a problem with npm. There is likely additional logging output above.



npm
 ERR!
 A complete log of this run can be found in:

npm 
ERR!
     /var/aegir/.npm/_logs/2020-02-04T16_51_25_642Z-debug.log

Script cd web && npm run build -- --pull-drupal  --no-drupal-proxy handling the va:web:build event returned with error code 1
```

**Comment by jonpugh** [comment]
aegir@devshop ~ $ cat /var/aegir/.npm/_logs/2020-02-04T16_51_25_642Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/var/aegir/projects/cms/pr903/docroot/vendor/nodejs/nodejs/bin/node',
1 verbose cli   '/var/aegir/projects/cms/pr903/docroot/vendor/nodejs/nodejs/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build',
1 verbose cli   '--',
1 verbose cli   '--pull-drupal',
1 verbose cli   '--no-drupal-proxy' ]
2 info using npm@6.4.1
3 info using node@v10.15.3
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle vets-website@1.0.0~prebuild: vets-website@1.0.0
6 verbose lifecycle vets-website@1.0.0~prebuild: unsafe-perm in lifecycle true
7 verbose lifecycle vets-website@1.0.0~prebuild: PATH: /var/aegir/projects/cms/pr903/docroot/vendor/nodejs/nodejs/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/var/aegir/projects/cms/pr903/docroot/vendor/va-gov/web/node_modules/.bin:/var/aegir/projects/cms/pr903/bin/../docroot/vendor/nodejs/nodejs//bin:/var/aegir/projects/cms/pr903/bin:$PATH:/usr/local/bin:/usr/bin:/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin
8 verbose lifecycle vets-website@1.0.0~prebuild: CWD: /var/aegir/projects/cms/pr903/docroot/vendor/va-gov/web
9 silly lifecycle vets-website@1.0.0~prebuild: Args: [ '-c', 'node script/prebuild.js' ]
10 silly lifecycle vets-website@1.0.0~prebuild: Returned: code: 0  signal: null
11 info lifecycle vets-website@1.0.0~build: vets-website@1.0.0
12 verbose lifecycle vets-website@1.0.0~build: unsafe-perm in lifecycle true
13 verbose lifecycle vets-website@1.0.0~build: PATH: /var/aegir/projects/cms/pr903/docroot/vendor/nodejs/nodejs/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/var/aegir/projects/cms/pr903/docroot/vendor/va-gov/web/node_modules/.bin:/var/aegir/projects/cms/pr903/bin/../docroot/vendor/nodejs/nodejs//bin:/var/aegir/projects/cms/pr903/bin:$PATH:/usr/local/bin:/usr/bin:/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin:/usr/share/devshop/bin
14 verbose lifecycle vets-website@1.0.0~build: CWD: /var/aegir/projects/cms/pr903/docroot/vendor/va-gov/web
15 silly lifecycle vets-website@1.0.0~build: Args: [ '-c',
15 silly lifecycle   'node --max-old-space-size=4096 script/build.js "--pull-drupal" "--no-drupal-proxy"' ]
16 silly lifecycle vets-website@1.0.0~build: Returned: code: 1  signal: null
17 info lifecycle vets-website@1.0.0~build: Failed to exec build script
18 verbose stack Error: vets-website@1.0.0 build: `node --max-old-space-size=4096 script/build.js "--pull-drupal" "--no-drupal-proxy"`
18 verbose stack Exit status 1
18 verbose stack     at EventEmitter.<anonymous> (/var/aegir/projects/cms/pr903/docroot/vendor/nodejs/nodejs/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
18 verbose stack     at EventEmitter.emit (events.js:189:13)
18 verbose stack     at ChildProcess.<anonymous> (/var/aegir/projects/cms/pr903/docroot/vendor/nodejs/nodejs/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
18 verbose stack     at ChildProcess.emit (events.js:189:13)
18 verbose stack     at maybeClose (internal/child_process.js:970:16)
18 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
19 verbose pkgid vets-website@1.0.0
20 verbose cwd /var/aegir/projects/cms/pr903/docroot/vendor/va-gov/web
21 verbose Linux 4.14.123-86.109.amzn1.x86_64
22 verbose argv "/var/aegir/projects/cms/pr903/docroot/vendor/nodejs/nodejs/bin/node" "/var/aegir/projects/cms/pr903/docroot/vendor/nodejs/nodejs/bin/npm" "run" "build" "--" "--pull-drupal" "--no-drupal-proxy"
23 verbose node v10.15.3
24 verbose npm  v6.4.1
25 error code ELIFECYCLE
26 error errno 1
27 error vets-website@1.0.0 build: `node --max-old-space-size=4096 script/build.js "--pull-drupal" "--no-drupal-proxy"`
27 error Exit status 1
28 error Failed at the vets-website@1.0.0 build script.
28 error This is probably not a problem with npm. There is likely additional logging output above.
29 verbose exit [ 1, true ]

**Comment by jonpugh** [comment]
Moved only .cache, and rebuilt.  It still failed.

**Comment by jonpugh** [comment]
Now moved all .npm, .yarn .cache folders.

Lets see if rebuild works again.

**Comment by ElijahLynn** [comment]
A bit of a postmortem here, with the context of this PR. 
https://github.com/department-of-veterans-affairs/vets-website/pull/11638

So what happened was that the frontend build script had some logic in it to replace `href` element attributes for the `*.cms.va.gov` pattern, which can take any number of sub.sub.domains. This logic only hit if it detected that pattern in the CMS `processed` output, and until the failure, we never had that. So when an editor used Entity Embed to embed a file, it resolved the URL in the `processed` output to be like the below, with pr888.ci.cms.va.gov in it. 

![2020-02-05_15-35](https://user-images.githubusercontent.com/1504756/73893014-45cccf80-482d-11ea-8852-6656a6397b07.png)

![image](https://user-images.githubusercontent.com/1504756/73892702-73fddf80-482c-11ea-81f2-a453b26ff46b.png)

So now this code path was followed, when it never had before (at least since our CI domains had been in play). It followed that path and then there was more logic to only work for a single sub.domain, of only `*.cms.va.gov` e.g. `dev.cms.va.gov` and then failed there. 

In addition to my above PR, the local domains (va-gov-cms.lndo.site) are still not executing this code path because they don't match. So locally there is no path swapping happening and we likely need a PR for that too.

Next steps now that https://github.com/department-of-veterans-affairs/vets-website/pull/11638 is merged is to revert the revert of the change on PROD. Trigger a new backup, then get it on CI for consumption and then tests should not fail because of this anymore.

**Comment by jonpugh** [comment]
@ElijahLynn You reopened?

**Comment by ElijahLynn** [comment]
> @ElijahLynn You reopened?

Yeah, I still have checkboxes that need doing. It was dependent on us fixing https://github.com/department-of-veterans-affairs/va.gov-cms/issues/916 first. I am completing remaining tasks/checkboxes now that CI is stable again.
