### ISSUE TITLE
Improve broken link KB articles. 

### ISSUE THREAD

**Issue by rachel-kauff** [department-of-veterans-affairs/va.gov-cms#8783]
## Description
Broken links are our hottest topic. The KB articles on broken links have a number of content quality issues. A rewrite will provide better support for editors and ensure KB content is accessible and useful.

## Acceptance Criteria
- [x] Articles [How to fix broken links and redirects](https://prod.cms.va.gov/node/44792/latest) and [Why broken links happen](https://prod.cms.va.gov/node/26968) are rewritten in draft
- [x] Peer reviewed by @xiongjaneg 
- [x] Published

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Sitewide program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide crew ` (leave Sitewide unchecked and check the specific team instead)
  - [ ] `⭐️ Content ops`
  - [x] `⭐️ CMS experience`
  - [ ] `⭐️ Public websites`
  - [ ] `⭐️ Facilities`
  - [x] `⭐️ User support`

**Comment by rachel-kauff** [comment]
@xiongjaneg These are ready for your eyes! 
- [How to fix broken links and redirects](https://prod.cms.va.gov/node/44792/latest)
- [Why broken links happen](https://prod.cms.va.gov/node/26968)

A brief summary of what I've changed:
- Reformatted to make more effective use of headings
- Rewrote for plain language
- Broke content into two distinct articles. My thinking is when people need a 'how to' they just want the steps, not lengthy explanations because they're looking for the shortest route to resolution. One article is 'how to' the other is more of an 'about' / shows the why behind things. I'd love your feedback on this approach.

**Comment by xiongjaneg** [comment]
@rachel-kauff Looks good, thanks for your work on these.
 
One thing in [How to fix broken links and redirects](https://prod.cms.va.gov/node/44792/latest), the first anchor link doesn't go to that paragraph (heading ID missing).t.

Wasn't sure if we're making the Veteran-centered lede standard on KB articles, since these and a number of articles don't have that. Your thoughts?

**Comment by rachel-kauff** [comment]
@xiongjaneg I've pivoted to trying to leaving off the "Veteran-centered purpose" in order to keep articles as short as possible, based on some analysis of other KB examples and best practices. Once we've done some more KB development of the content templates, I think we'll be able to put it back in without compromising that principle.
