### ISSUE TITLE
README for running teamsites locally is out of date & requires updates

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#8794]
## Describe the defect
https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/proxy-rewrite/README.md#local-dev describes the process for running / testing TeamSite locally. 

@ddzz helped resolve a recent issue, #8782, and flagged that the readme is out of date. Items to update -- all of these need verified, and final changes should be best practices updates, so these exact lines may change:
* Using yarn, not npm
* `npm watch --` is incorrect
* Steps to run legacy sites locally, per Darius, for verifying:
    * Copy the attached `headerFooter.json` file to `vets-website/build/localhost/generated/`. Per Ryan, `headerFooter.json` should be generated by running a build on content-build.
    * Start vets-website with `yarn watch --env local-proxy-rewrite`
    * Navigate to a legacy page as described in the proxy-rewrite README, such as http://localhost:3001/?target=https://www.va.gov/health/

 ## Additional context
Legacy pages use TeamSite CMS. Now, the modern header and footer are injected into those pages, which is the primary work / responsibility for the Public Websites team. This README is used to verify fixes for that injection.

There is an open question here to confirm: which team should own this README file / process for managing TeamSite writ large, moving forward? And if the answer is Public Websites team, is anyone available to do more training about the context / building blocks? @wesrowe this may be a question to discuss with you.

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Defect")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [ ] CMS workstream (orange) (not needed for bug tickets)
- [ ] CMS-supported product (black)

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Sitewide program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide CMS Team ` (leave Sitewide unchecked and check the specific team instead)
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [X] `⭐️ Public websites`
  - [ ] `⭐️ Facilities`
  - [ ] `⭐️ User support`

**Comment by allisonlu** [comment]
This change has been merged: https://github.com/department-of-veterans-affairs/vets-website/pull/20987
