### ISSUE TITLE
Re-enable content releases on BRD dev and staging

### ISSUE THREAD

**Issue by cweagans** [department-of-veterans-affairs/va.gov-cms#8797]
Content releases were disabled in https://github.com/department-of-veterans-affairs/va.gov-cms/pull/8795 because the content release workflow doesn't support deploying to dev or staging.

We should consider fixing the workflow so that it supports a dev and staging deploy, then re-enable build dispatch from dev and staging.

## Acceptance Criteria
- [ ] 

### CMS Team
Please check the team(s) that will do this work.

- [x] `Platform CMS Team`
- [ ] `Sitewide crew `
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Public websites`
  - [ ] `⭐️ Facilities`
  - [ ] `⭐️ User support`

**Comment by TheBoatyMcBoatFace** [comment]
Closing - BRD is going away. Reopen if necessary.
