### ISSUE TITLE
Stage homepage design refresh for user testing

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#8811]
## Description
_As a Veteran, I want to be able to visit the proposed new home page on a non-production version of VA.gov, so that I can try it out and share my thoughts without the risk of stumbling upon it outside of the context of usability testing._

This issue is to actually build the framework where we can stage VA.gov home page changes for user testing. See "Background" below for avenues that led us to this recommendation. This recommendation was finalized in a discussion with Mikki N about IA governance in general and our needs in particular.

## Acceptance Criteria
- [ ] Only avail on Dev, controlled by a flag (NOT Flipper. Besides it being flaky, Flipper doesn't work in content-build process)
- [ ] 
- [ ] Requires design review
### Recommendation: 
* use a random subdirectory path for the page initially, which can be shared with usability testing participants – e.g. va.gov/dy9td
* limit the path's exposure to Dev & Staging (as needed) using Flipper
* (optional) use a redirect to add a vanity url if needed for any testing scenario in the future

### Steps to finalize issue as ready for dev
- [x] Dave review and approve Staging/flipper plan - @davidconlon 
- [x] Provide proposed URL path for staging - `/homepage-test`
- [x] Decide re: vanity URL now or later, and what URL to use if now - @davidconlon (& @wesrowe ?)

### Acceptance Criteria
- [ ] Homepage preview access in the staging and/or dev environments is controlled by a flag
- [ ] Homepage preview path is not accessible in prod to authed or unauthed users 
- [ ] Homepage preview path is not accessible to web crawlers
- [ ] Homepage preview path is not present on xml sitemap
- [ ] When flag is changed, homepage preview becomes accessible to unauthed users 

### Background

We have researched a few options: 
1. Use a subdomain,  e.g. preview.va.gov -- ruled out because it requires web governance involvement. We may pursue this long term, but not for this particular use.
2. Use a subdirectory, e.g. va.gov/homepage-preview -- #8478 - no web governance required, and is technically feasible. However, Mikki had some concerns around discoverability. If we were to go this route, must prevent the path from being indexed by site search or web crawlers.
3. Use staging for user testing -- #8668 - can be achieved by using conditionals in the code, and/or (?) putting the page behind a flipper. Natively, the page will receive a Drupal path. We can opt to add a vanity path for user testing phase, or at a later date. Technically, this approach introduces tech debt, but is the preferred path forward due to other concerns around subdirectories exposed in prod. 
 
### CMS Team
Please check the team(s) that will do this work.

- [ ] `Sitewide program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide crew ` (leave Sitewide unchecked and check the specific team instead)
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [X] `⭐️ Public websites`
  - [ ] `⭐️ Facilities`
  - [ ] `⭐️ User support`

**Comment by wesrowe** [comment]
Our "pencils down" discussion in backlog refinement meeting 4/28 basically led to executing this story. So I've updated the main issue, which now qualifies as Ready. Moving it to Next sprint.

**Comment by allisonlu** [comment]
cc: @mmiddaugh

**Comment by allisonlu** [comment]
PR opened: https://github.com/department-of-veterans-affairs/content-build/pull/1081

**Comment by allisonlu** [comment]
PR on `content-build` is merged! https://github.com/department-of-veterans-affairs/content-build/pull/1081

You can check out the HTML structure now: https://staging.va.gov/homepage-test/

Still waiting on one more approval from the code owner on `vets-website`: https://github.com/department-of-veterans-affairs/vets-website/pull/21061

**Comment by allisonlu** [comment]
`vets-website` PR merged!: https://github.com/department-of-veterans-affairs/vets-website/pull/21061

All changes are now on staging: 
https://staging.va.gov/homepage-test/
