### ISSUE TITLE
[Spike] Investigate defects in Sentry

### ISSUE THREAD

**Issue by cweagans** [department-of-veterans-affairs/va.gov-cms#8815]
## Describe the defect

We get paged for defects that are identified in Sentry. It's annoying and per [RFC 9225](https://www.rfc-editor.org/rfc/rfc9225.html), we should not have those defects sitting around.

## Acceptance Criteria 

- [ ] Review pre-sorted list of issues: https://sentry.vfs.va.gov/organizations/vsp/issues/?project=14&query=is%3Aunresolved&sort=freq&statsPeriod=14d and investigate root cause for incidents
- [ ] Create followup tickets for resolution

**Comment by ndouglas** [comment]
At this point, this is addressed on-the-fly as these things emerge as part of ongoing QA work.
