### ISSUE TITLE
Horizontal lines not appearing in rich text editor

### ISSUE THREAD

**Issue by rachel-kauff** [department-of-veterans-affairs/va.gov-cms#8833]
## Background
Horizontal lines aren't showing up in the rich text editor, but do appear after node save.

Lynn+Kev think it's probably a Claro issue: "it's prob just a style that's not adding the right css" ([see this thread for context](https://dsva.slack.com/archives/CT4GZBM8F/p1650476483115259?thread_ts=1650475109.790699&cid=CT4GZBM8F))

## Steps to reproduce
1. Open a content type with rich text editor
2. Add body content above and below a horizontal line
3. Observe that the horizontal line isn't visible
4. Save node and notice that the horizontal line does appear on View.

## Screenshots
![Screen Shot 2022-04-20 at 11.38.23 AM.png](https://images.zenhubusercontent.com/5e399cf5446c5b4ca0e31e42/a41892ef-986b-46be-bd30-3e50923d6bbb)
Horizontal line that appears on View for a CMS Knowledge Base Article.

![Screen Shot 2022-04-20 at 11.38.42 AM.png](https://images.zenhubusercontent.com/5e399cf5446c5b4ca0e31e42/bea12a62-f00c-4e99-9d2f-974d2bf9e36b)
The same content as it appears on Edit in the rich text editor.

**Comment by msbtterswrth** [comment]
duplicates #8834, closing.
