### ISSUE TITLE
Horizontal rules not appearing in rich text editor

### ISSUE THREAD

**Issue by rachel-kauff** [department-of-veterans-affairs/va.gov-cms#8834]
## Background
Horizontal lines aren't showing up in the rich text editor, but do appear after node save.

Lynn+Kev think it's probably a Claro issue: "it's prob just a style that's not adding the right css" ([see this thread for context](https://dsva.slack.com/archives/CT4GZBM8F/p1650476483115259?thread_ts=1650475109.790699&cid=CT4GZBM8F))

## Steps to reproduce
1. Open a content type with rich text editor
2. Add body content above and below a horizontal line
3. Observe that the horizontal line isn't visible
4. Save node and notice that the horizontal line does appear on View.

## Screenshots
![Screen Shot 2022-04-20 at 11.38.23 AM.png](https://images.zenhubusercontent.com/5e399cf5446c5b4ca0e31e42/a41892ef-986b-46be-bd30-3e50923d6bbb)
Horizontal line that appears on View for a CMS Knowledge Base Article.

![Screen Shot 2022-04-20 at 11.38.42 AM.png](https://images.zenhubusercontent.com/5e399cf5446c5b4ca0e31e42/bea12a62-f00c-4e99-9d2f-974d2bf9e36b)
The same content as it appears on Edit in the rich text editor.

**Comment by RLHecht** [comment]
hey @rachel-kauff Just found this ticket and was curious if there was any movement on this. We were adding lines to a page on Friday and noticed that they still aren't showing.

**Comment by rachel-kauff** [comment]
Thanks for checking in @RLHecht . I'll run it by @EWashb and see if we can get this moving.

**Comment by RLHecht** [comment]
@rachel-kauff I didn't mean to jump into this ticket but I just noticed that the same issue is happening when I select the Address block component—it indents my text but I don't see the vertical blue line in the rich text editor. Once I preview the address block is showing correctly though.

**Comment by rachel-kauff** [comment]
@RLHecht Thanks for raising this! @msbtterswrth will probably be able to tell whether those are related problems. If they're not, we'll split it off into a separate ticket.

**Comment by msbtterswrth** [comment]
These are indeed the same issue! I found the root cause and have fixed it. We're just waiting for tests to pass and hopefully it'll go out today!
