### ISSUE TITLE
UX module review for "Was this helpful?" widget

### ISSUE THREAD

**Issue by EWashb** [department-of-veterans-affairs/va.gov-cms#8842]
## ACs

- [x] Design review of the chosen drupal contrib module
- [x] Evaluate proper workflow of UI 

- Break into a separate issue: MVP plan for data review and governance

**Comment by rachel-kauff** [comment]
[Notes from module review](https://docs.google.com/document/d/1c2ISeF9oCBRrQsGsbhKTtuaxAsknGNTEjoOn7UNED0Y/edit) w/ Lynn and Cindy

**Comment by rachel-kauff** [comment]
Posting the initial decisions and action items here for transparency

**Decisions**

- No cookies
- Need to accommodate use cases where editors return to an article multiple times. Low chance of folks spamming an article with feedback
- Skip validation for freeform feedback box- not needed yet bc we’re not using it
- Turn off freeform feedback box to start
- Add helpdesk link for no responses - (need to validate with dave)
- Use Admin_feedback module - aligns with our needs, meets security reqs
- Style as secondary icon buttons (stretch - omit if we run out of time)
- Position of last updated - pull out into a separate issue - (position at top?, very bottom?)
- Left align for MVP - Centering would need more consideration. Let’s wait.

**Action items**

- [ ] Cindy and Kauff to provide button style reqs (size)
- [ ] Cindy to migrate new icons from allergy hand into real DS doc
- [ ] Lynn spinning it up for review

**Comment by EWashb** [comment]
@rachel-kauff is this one good to close?
