### ISSUE TITLE
Fix CI failure on April 18

### ISSUE THREAD

**Issue by cweagans** [department-of-veterans-affairs/va.gov-cms#8847]
## Description

Ticketing for time spent on debugging and fixing CI failure on Monday.

Slack thread: https://dsva.slack.com/archives/CT4GZBM8F/p1650307817571779

## Acceptance Criteria
- [ ] Testable_Outcome_X
- [ ] Testable_Outcome_Y
- [ ] Testable_Outcome_Z
- [ ] Requires design review

### CMS Team
Please check the team(s) that will do this work.

- [x] `Platform CMS Team`
- [ ] `Sitewide program`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by TheBoatyMcBoatFace** [comment]
Additional detail needed. Please add info and reopen if still concerned.
