### ISSUE TITLE
Update Lovell IA artifact

### ISSUE THREAD

**Issue by suzanne-gray** [department-of-veterans-affairs/va.gov-cms#8863]
## Description

Update the IA artifact to represent syndicated vs unique content and assist with designing CMS editor workflow.

Look at the Lovell content on VA.gov and on [teamsite](https://www.lovell.fhcc.va.gov/index.asp) to get a basic sense of which content can be shared and which is different enough that there needs to be two versions. 

Goal: remove the ?s on the [content model mural](https://app.mural.co/t/vagov6717/m/vagov6717/1649871147127/79a626dd43195096acc64653f15b4a7fcc039458?sender=u0462bdfe88bc3bd6cd013167)

Any more detailed content planning will need to be done in concert with Lovell site editors. 

## Acceptance Criteria
- [ ] Content model reflects our best understanding of what content goes where
- [ ] Results have been discussed with Facilities team

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Platform CMS Team`
- [ ] `Sitewide program`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public websites`
- [X] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by davidmpickett** [comment]
Closing as redundant with #9850
