### ISSUE TITLE
Update Mapbox token to domain-restricted token

### ISSUE THREAD

**Issue by ryguyk** [department-of-veterans-affairs/va.gov-cms#8876]
## Description
Originally discussed here: https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/454

Initial solution discussed here: https://dsva.slack.com/archives/C0FQSS30V/p1650660997660989

This initial solution boils down to creating a new token and updating the code to use it. The new token is restricted to these domains:
```
https://www.va.gov/
https://staging.va.gov/
https://dev.va.gov/
http://preview-prod.vfs.va.gov/
http://preview-staging.vfs.va.gov/
http://preview-dev.vfs.va.gov/
http://*.review.vetsgov-internal
```

Additional steps are on the horizon to grab parameters from AWS rather than storing in code.

## Acceptance Criteria
- [ ] Token has been updated in `vets-website`
- [ ] Maps function as expected on front end

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Platform CMS Team`
- [ ] `Sitewide program`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by RWEagans** [comment]
This did not complete if Sprint 57 due to a change in priorities. Moving to Sprint 58 to complete. @ryguyk looked in to it. We need to get a status update and understand who will take up the work going forward.

**Comment by ryguyk** [comment]
https://dsva.slack.com/archives/C0FQSS30V/p1681839525678179?thread_ts=1681838317.961279&cid=C0FQSS30V

The solution we implemented months back utilizes the dev (sensitive) key on review instances (they are not visible to the public). So, I had Nancy remove that URL from the token and the allowed URL list is now:
```
http://preview-dev.vfs.va.gov/
http://preview-prod.vfs.va.gov/
http://preview-staging.vfs.va.gov/
https://dev.va.gov/
https://staging.va.gov/
https://www.va.gov/
```
