### ISSUE TITLE
Homepage hero veteran images: Design system: approval and updates for background colors

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#8878]
## Description
In new homepage: when no V2 Home page benefit promo custom block is published to the Home page benefit promo entity queue, a series of veteran images will show: 
https://www.sketch.com/s/3aa40506-4be2-46cc-876b-93f1a9f3a857/a/WKW7xVA

During prototype build, the background colors for images in that space were hard coded. 

Those colors are not in the design system and are unique to this homepage design. We need to move them into the design system (assuming the same colors are final in the design for production).

Note: low priority, as the page will launch with benefit promo content and veteran images won't be visible. 

## Acceptance Criteria
- [ ] Testable_Outcome_X
- [ ] Testable_Outcome_Y
- [ ] Testable_Outcome_Z
- [ ] Requires design review

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Platform CMS Team`
- [ ] `Sitewide program`
- [ ] `⭐️ Sitewide CMS`
- [X] `⭐️ Public websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by jilladams** [comment]
@mmiddaugh we created this ticket after the 1st homepage prototype round, based on the design at the time. Ryan has changed the veteran image gradient a bit -- I'm not clear if this work is still needed re: the design system. But if so, we should get this rolling. Assigning to you for now for review with Ryan, and we can help as needed, just let us know?

**Comment by jilladams** [comment]
@thejordanwood this may be a thing we could talk to you about now that we have you. Not urgent, so sometime if you're looking for tasks in free time, let's chat about it.

**Comment by thejordanwood** [comment]
I created [ticket 52365](https://github.com/department-of-veterans-affairs/va.gov-team/issues/52365) to submit a design system update for this. The background colors were changed to #0071BB (color-primary), #003e73 (color-primary-darker), and #005EA2 (blue-60v) to align with our system and the USWDS color system. The first 2 colors are from our system and the last color is from the USWDS system. 

The design team suggested this solution for now: _"We will be adding those colors but it's in the roadmap right now. You can go ahead and use the 2 tokens that already exist and hard-code the one that doesn't exist."_

**Comment by jilladams** [comment]
@thejordanwood can you confirm if these are updated in the Sketch file as well? (I don't know how to tell, with my type of user.)
