### ISSUE TITLE
Homepage hero veteran images: add snapshot / unit tests 

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#8879]
## Description
#8360 created a new homepage hero component. This component needs unit tests. Two types of tests involved here: 
1. Snapshot / visual regression testing
2. Functional testing for image randomizing

## Acceptance Criteria
- [ ] all unit tests pass

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Platform CMS Team`
- [ ] `Sitewide program`
- [ ] `⭐️ Sitewide CMS`
- [X] `⭐️ Public websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by jilladams** [comment]
@apisandipas We made this ticket after Allison did V1 of the prototype, and I'm not certain if this is still relevant based on current code / design, since the hero area has changed. Could you take a look and validate whether this should close or we do need to write tests?  We should pull this into next sprint if we still need to do the work.

**Comment by wesrowe** [comment]
Moved back to new/unrefined. Hero portraits are not part of MVP homepage and therefore no unit tests required pre-launch.

**Comment by jilladams** [comment]
@randimays would you mind taking a look at this older ticket and validate whether we still need this in light of your recent work?

**Comment by randimays** [comment]
@jilladams We don't need them; all the code was tested/covered in the recent work. I'll close!
