### ISSUE TITLE
Merge to feature branch: changes for #8358, #8360 #8384, #8361 for homepage design updates

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#8880]
## Description
#8358, #8360 #8384 are code complete but need to merge to the feature branch.
* https://github.com/department-of-veterans-affairs/content-build/pull/1089 - should first merge to the feature branch

The feature branch will merge to main under #8811.

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Platform CMS Team`
- [ ] `Sitewide program`
- [ ] `⭐️ Sitewide CMS`
- [X] `⭐️ Public websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by wesrowe** [comment]
@ryguyk, does this story need to go into the same sprint as #8811?

**Comment by ryguyk** [comment]
@wesrowe They should, yes.

**Comment by jilladams** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VAgov-CMS-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/8880?planning-poker) with ZenHub @allisonlu @kind-claudio @ryguyk

**Comment by allisonlu** [comment]
PR on `content-build`: https://github.com/department-of-veterans-affairs/content-build/pull/1081

PR on `vets-website`: https://github.com/department-of-veterans-affairs/vets-website/pull/21061

**Comment by allisonlu** [comment]
All the mentioned branches are merged to feature branch; closing ticket
