### ISSUE TITLE
Design: display timezone on va.gov facilities

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#8885]

**Comment by davidmpickett** [comment]
@swirtSJW I'm reviewing everything tagged Design in the backlog. Is this effort still ongoing or can we add icebox label?

**Comment by davidmpickett** [comment]
@thejordanwood addressed this in the [FE design for VBA](https://www.sketch.com/s/891d33ae-152d-471c-ab5d-9aedf89cf6ff)

![Screenshot 2023-10-30 151507](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/015817d6-b1f3-4543-90d9-3bb129b8930d)
