### ISSUE TITLE
SPIKE: tech design for JSON version of Cerner widgets

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#8888]
## Details

Finalize the architecture and API between the CMS and front-end. This will be done when all questions holding up development of the JSON story #7860.

**Major considerations:** 
- Dependencies - identify any other teams/applications that rely on the `index.js` hard-code implementation.
- Does CMS design need to change at all?

## Acceptance Criteria
- [ ] All doubts resolved
- [ ] All dependencies understood
- [ ] Design includes #8199 as part of path forward

**Comment by wesrowe** [comment]
@ryguyk, just wanted to invite you to add a note/comment if you like as we close this issue.
