### ISSUE TITLE
Node history tab is broken

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#889]
**Describe the bug**
The node history tab hasn't worked for awhile, and is 

**To Reproduce**
1. Go to any node and click on history (eg https://prod.cms.va.gov/node/318/moderation-history)

**Expected behavior**
Either the tab should work, or be removed altogether.  For now, let's remove it. 

**Screenshots**
![Moderation_History___Veterans_Affairs](https://user-images.githubusercontent.com/643678/73707257-0ab18b80-46c9-11ea-98ca-946b9c2aa4d8.jpg)

**Comment by swirtSJW** [comment]
Merged https://github.com/department-of-veterans-affairs/va.gov-cms/pull/908
