### ISSUE TITLE
Coordinate account administration and onboarding for R&S and Benefit Hub folks

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#8891]
## Description
Randi and new team members need access to Drupal. This will need coordination with Danielle and Beth and updates to existing policies listed below.

Per Dave in [Slack](https://dsva.slack.com/archives/CDHBKAL9W/p1650903671867859), "we probably want to take this as an opportunity to revisit/document the onboarding and auth process for the different areas.I (likely) don't need to be the contact person for a lot of this stuff in the future."

See existing policies on Drupal KB
[Resources and Support policy](https://prod.cms.va.gov/help/cms-account-admin-policies/resources-and-support-cms-account-administration-policy)

Notes about current state:
Danielle, Beth, and Randi have the Content Admin role, which gives them editing and publishing access to all Drupal sections.
Training has generally been provided by the content team, but the Drupal CMS team is available for training support as well.

Aspects to consider:
- Clarify what policy "owner" means
- Confirm who should be contacted (currently it's Beth and Danielle) to verify Drupal access and permissions level for R&S and Sitewide content editors 
- Define rules for sections and permissions for onboarding team members (e.g. VBA, VHA, or both? How to ensure access to necessary tier 1 content?)
- Define who provides training for new team members (Sitewide CMS or Sitewide Content)
- Define training topics
- Consider whether content admin role is still appropriate for certain Bene hubs/ R&S editors
- Do team members still need the ability to perform manual content releases?
- Consider whether to split into two different scenarios: access needed for content purposes vs access needed for devs (in which case we'd want a different approver)
- Will want to maintain separate policies R&S and Bene Hubs
- What might we need to consider in terms of future scaling?
- How does offboarding work?

## Folks involved
- Beth, Danielle, [possibly] Randi
- Dave
- Leading: [sitewide cms facilitator]

## Acceptance Criteria
- [ ] Account admin policy for relevant products (Resources and Support, maybe also Benefits Hubs?) has been reviewed and updated with any necessary adjustments
- [ ] Approach to training for new R&S and Sitewide content team members is defined in the relevant account admin policies
   - [ ] If CMS needs to make new training -- split into another issue
- [ ] Helpdesk documentation is updated according to policy changes

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Platform CMS Team`
- [ ] `Sitewide program`
- [x] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by xiongjaneg** [comment]
Please see previous [accidental deletion issue for consideration of appropriate roles](https://dsva.slack.com/archives/CDHBKAL9W/p1648589299632689?thread_ts=1648585496.344939&cid=CDHBKAL9W)

**Comment by rachel-kauff** [comment]
[Thread](https://dsva.slack.com/archives/CDHBKAL9W/p1651163743760349?thread_ts=1650903671.867859&cid=CDHBKAL9W) with Va.gov email addresses of a few of the onboarding team members

**Comment by xiongjaneg** [comment]
current training is that the content team does their own training, but for this most recent request, the [general Drupal editing overview video link was provided](https://youtu.be/_Y58IJajCwU)

**Comment by stefaniefgray** [comment]
@EWashb Closing because I'm pretty sure most of this work was done already, but please let me know if there's anything we ought to carry forward from this ticket
