### ISSUE TITLE
Button links do not show correctly in WYSIWYG

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#8894]
## Describe the defect
When choosing button style links in the WYSIWIG, they immediately become invisible during node edit.
![image](https://user-images.githubusercontent.com/5752113/165294205-cd4c638b-d8c8-44df-a524-e50c64793537.png)

They display correctly on node View 
![image](https://user-images.githubusercontent.com/5752113/165294274-90b5a36d-4a49-4159-a48b-01d89e098986.png)

and on the preview server
![image](https://user-images.githubusercontent.com/5752113/165294332-7762557e-b4c9-4fbd-a287-6b3070d33e89.png)

## To Reproduce
1. Go to (https://staging.cms.va.gov/node/add/page)
2. Add a wywiwyg content block
3. Make a link,
4. Assign the class for default button link
5. Observe that the link disappears.

## Expected behavior
Should see the button in the WYSIWIG exactly as it appears on node view.

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Defect")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS workstream (orange) (not needed for bug tickets)
- [ ] CMS-supported product (black)

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Platform CMS Team`
- [ ] `Sitewide program`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by laflannery** [comment]
@EWashb and @BerniXiongA6 I'm going to close this because 1. it's not happening on Prod and 2. we are removing these styles with D10 so it's not relevant even if it does start to happen again.
