### ISSUE TITLE
VHA Digital Media needs a downloadable report of VAMC new top task pages

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#8899]
## User story
As VHA Digital Media staff, I need to be able to review the status of VAMC top task page updates so that I can follow up with and provide support to VAMC editors updating these pages.

Current state:
VHA DM staff have the Content Publisher role. They can filter Content by each top task content type and view the results ([see Register for Care example](https://prod.cms.va.gov/admin/content?title=&type=vamc_system_register_for_care&moderation_state=All&owner=All)). However, the results aren't currently downloadable, so VHA DM staff would have to go from page view to page view.

Potential solutions with varying degrees of engineering or manual effort.

- Engineering solution to add a csv download to Content for all editors in Drupal.
- Manual solution for a CMS team member to download the Content or Content audit reports and email to VHA DM.

## Acceptance Criteria
- [ ] Testable_Outcome_X
- [ ] Testable_Outcome_Y
- [ ] Testable_Outcome_Z
- [ ] Requires design review

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Platform CMS Team`
- [ ] `Sitewide program`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public websites`
- [x] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by xiongjaneg** [comment]
Per Dave, icebox for now. VHA DM has access to Content and need instructions on how to filter Content by each of the content types.

**Comment by kevwalsh** [comment]
Closing this on account of last comment, and ongoing success with that.
