### ISSUE TITLE
Analyze existing node types for design and editorial workflow improvements

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#891]
## Background ##

As the design system is evolving post-Claro launch, there is a need to determine the current design and form display patterns within the various products. The design system team, along with a theme engineer, will conduct a series of spikes to understand what configs already exist within our CMS that can be used to enhance design and editorial workflow patterns. 

A [tugboat environment ](https://tugboat.vfs.va.gov/62214d76bb10f917f942bf4c)has been set up for this initiative. 

## Additional Context ##
Notes from Feb 3, 2020: We have a mural that shows screenshots of all the variations of editorial workflow widgets between these and within

* Edit screens
* View screens
* /admin/content dashboard 

Entity types
* Node types (possibly with Product implications)
* Block type (which is weird, has no block view)
* Taxonomy (which is missing) 

## ACs ##

Consider desirable variation vs undesirable. 

Examine 
* plain language vs drupalspeak (don't judge!)
* UI 
* functionality
* IA

**Comment by EWashb** [comment]
capacity was limited for Sprint 58 due to team support for covid status

**Comment by EWashb** [comment]
not within scope currently
