### ISSUE TITLE
Remove field_facility_hours from vha facility

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#8918]
## Description
Remove field_facility_hours from VHA facilities

The data has already been cut over.  The field just needs to go.

## Acceptance Criteria
- [ ] field field_facility_hours no longer exists on https://prod.cms.va.gov/admin/structure/types/manage/health_care_local_facility/fields
- [ ] Field data is removed with an hook_update_n
- [ ] field is removed from migration
- [ ] Remove plugin va_table_field_hours from codebase.

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Platform CMS Team`
- [ ] `Sitewide program`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public websites`
- [x] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by kevwalsh** [comment]
This is a dupe.
