### ISSUE TITLE
Update OpenSSL on BRD Environments

### ISSUE THREAD

**Issue by olivereri** [department-of-veterans-affairs/va.gov-cms#8928]
## Description
The current version of OpenSSL installed on CMS BRD Servers is `OpenSSL 1.0.2k-fips  26 Jan 2017` and does not support TLS v1.3. See the related discussion regarding this. Additionally, the current version of OpenSSL available is `3.0.2`.

## Acceptance Criteria
- [ ] OpenSSL v3.X is installed on BRD and is configured to run in FIPS compliant mode.
- [ ] CMS BRD Servers can now communicate using TLS v1.3 protocol.
- [ ] PIV Authentication and other services/processes that use OpenSSL function as intended.

## Related Discussion
https://dsva.slack.com/archives/CT4GZBM8F/p1651187105128769

## Implementation Details
I got through the installation on dev.cms.va.gov, PIV auth untested after installation.

### Verifying OpenSSL Version
```
[root@server bin]# openssl version
OpenSSL 1.0.2k-fips  26 Jan 2017
```

### BRD Build OpenSSL Installed Version
Where is OpenSSL installed?
`./roles/common/ansible/tasks/main.yml:9:      - openssl-devel`

What is openssl-devel?

```
[root@server bin]# yum install openssl-devel
Loaded plugins: extras_suggestions, langpacks, priorities, update-motd
amzn2-core                                                                      | 3.7 kB  00:00:00
236 packages excluded due to repository priority protections
Resolving Dependencies
--> Running transaction check
---> Package openssl-devel.x86_64 1:1.0.2k-24.amzn2.0.4 will be installed
```

### Uninstall previous versions of OpenSSL
?
mv /usr/bin/openssl /usr/bin/opensslv1.0.2

### Install OpenSSL v3.0
yum install perl-Digest-SHA
yum install perl-IPC-Cmd
yum isntall perl-Test-Most
./Configure enable-fips
make
make install
ldconfig /usr/local/lib64
cd /usr/bin
ln -s /usr/local/bin/openssl openssl

### Enable FIPS
openssl fipsinstall -module /usr/local/lib64/ossl-modules/fips.so -out /usr/local/ssl/fips.cnf -provider_name fips

cat <<EOF > /usr/local/ssl/openssl.cnf
.include /usr/local/ssl/fips.cnf

[provider_sect]
fips = fips_sect
base = base_sect

[base_sect]
activate = 1
EOF

**Comment by td-usds** [comment]
From https://www.openssl.org/news/secadv/20221101.txt

For both reported issues:
> OpenSSL versions 3.0.0 to 3.0.6 are vulnerable to this issue.
> OpenSSL 1.1.1 and 1.0.2 are not affected by this issue.

**Comment by TheBoatyMcBoatFace** [comment]
@olivereri closing due to team moving away from BRD. Reopen if necessary.
