### ISSUE TITLE
CTA arrow for "visited" links also changing to visited color (instead of staying blue)

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#8932]
## Description

Reported by Robin Garrison.

Example page: [Find-a-form detail page](https://staging.va.gov/find-forms/about-form-21-686c/) (there are probably others)
Note the purple icon: ![image.png](https://images.zenhubusercontent.com/61a671f5fc46c2a311655f75/ba750f25-8499-4e0e-86a2-e264868b951a)

The icon itself should stay the original color even after it has been visited.

### Notes on occurrences

- The example above is a find-a-form detail page
- This does **not** occur on resources & support pages like [Change your address](https://www.va.gov/resources/change-your-address-on-file-with-va/). 
<img width="115" alt="image" src="https://user-images.githubusercontent.com/4054752/166505275-995b3251-ef6b-41c2-a1dc-9727d185402a.png">

## Resources:
- [Storybook](https://design.va.gov/storybook/?path=/docs/components-action-link--primary#secondary)

## Acceptance Criteria
- [ ] Icon for visited CTA links stays blue
- [ ] Requires design review

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Platform CMS Team`
- [ ] `Sitewide program`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by allisonlu** [comment]
PR merged: https://github.com/department-of-veterans-affairs/content-build/pull/1178
