### ISSUE TITLE
Add PW team members to Flipper-access configuration

### ISSUE THREAD

**Issue by ryguyk** [department-of-veterans-affairs/va.gov-cms#8938]
## Description
Need to add emails to [`/vets-api/config/settings.yml`](https://github.com/department-of-veterans-affairs/vets-api/blob/master/config/settings.yml) for all users on team who need access.

## Acceptance Criteria
- [ ] Appropriate members are able to access Fliipper in production

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Platform CMS Team`
- [ ] `Sitewide program`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by jilladams** [comment]
Verified my account access today, and I can get in and adjust flipper settings. I'm gonna move this to closed.
