### ISSUE TITLE
Facility COVID status: work through details of Lighthouse connections

### ISSUE THREAD

**Issue by cmaeng** [department-of-veterans-affairs/va.gov-cms#8947]
From [slack thread here](https://dsva.slack.com/archives/C02BTJTDFTN/p1651690247312359):

The need for display a Covid status of Red, Green or Yellow across facility locator and [va.gov](http://va.gov/).  The initial request on this is in the "next week" ballpark but we are trying to get confirmation of that.
My initial take on how to get this out the door quickly without a whole slew of dependencies on the trinity (CMS, FAPI (facility locator explicitly), [va.gov](http://va.gov/)) is to add values to the existing status options
* Normal services and hours
* Facility Notice
* Limited Service and hours
* Facility Closed

Would become something like
* Normal services and hours
* Normal services and hours - Covid Green
* Normal services and hours - Covid Yellow
* Facility Notice
* Limited Service and hours
* Limited Service and hours - Covid Red
* Facility Closed

**^^** **Data approach abandoned 5/4/22.**   See first comment below for new approach.
  

## To Do
- [ ] Negotiate the shape of the data with Lighthouse team (conversation in this issue)
- [ ] #8987

**Comment by swirtSJW** [comment]
Initial take on this was abandoned for a number of reasons.  Largely the need to keep covid status separate from operating status and have it trigger various displays both in the CMS, Facility Locator and va.gov.

The new approach is to push a separate status to the Facility API.  In the CMS we are going to use a little bit more generic field naming of `field_supplemental_status` to allow for use beyond covid if needed, so some question for the lighthouse team

- What key would you like us to use when we push to you?   supplemental_status or covid_status
- Would you like it as part of the operating status  like this
```
operating_status' => [
          'code' => Normal,
          'additional_info' => "Some string stuff.",,
          'supplemental_status' => VALUE,
        ],
```
OR separate from it like this

```
operating_status' => [
          'code' => NORMAL,
          'additional_info' => "Some string stuff.",
        ],
'supplemental_status' => VALUE,
```



Finally what would you like the VALUE to be?
- The human friendly label of the status  like `COVID - high`, knowing that the human friendly label might change to align with facility signage or Veteran user data.  (example...might be later changed to `COVID Strict`
- An api id that would not drift once created (similar to the service id field we created) that is still semi-readable, but may not exactly match the label like `covidHigh`    and even if the label changed to `Covid Strict` we would still be sending you `covidHigh`
- An array containing both label and id.
```
'supplemental_status' => [
   'label' =>  "Covid Strict",
  "id" => "covidHigh"
],
```

**Comment by swirtSJW** [comment]
Asked ^^ [in slack](https://dsva.slack.com/archives/C02BTJTDFTN/p1651804426005869)

**Comment by swirtSJW** [comment]
Thinking supplemental status should be an array of values in case more than one is allowed. (future framework planning)

**Comment by swirtSJW** [comment]
From today's lighthouse call this is the agreed upon format we will be pushing and they will be receiving

```JSON
"operating_status": { 
   "code": "NORMAL", 
   "additional_info": "This is text...", 
   "supplemental_status": {
          "COVID_HIGH" : { "label": "This is high Covid" }, 
          "EBOLA_LOW": { "label": "This is low Ebola" } 
    } 
 } 
```

**Comment by swirtSJW** [comment]
Now that we have the shape of the data defined, we can close this an work on the implementation

**Comment by JayDarnell** [comment]
Starting on implementation now

**Comment by JayDarnell** [comment]
Updated format: `"operating_status": {
	"code": "NORMAL",
	"additional_info": "This is text...",
	"supplemental_status": [
		{
			"id": "COVID_HIGH",
			"text": "This is high Covid"
		},
		{
			"id": "EBOLA_LOW",
			"text": "This is low Ebola"
		}
	]
}`

**Comment by swirtSJW** [comment]
```JSON
"operating_status": {
	"code": "NORMAL",
	"additional_info": "This is text...",
	"supplemental_status": [
		{
			"id": "COVID_HIGH",
			"label": "This is high Covid"
		},
		{
			"id": "EBOLA_LOW",
			"label": "This is low Ebola"
		}
	]
}
```
