### ISSUE TITLE
Add covid status field to VAMC Facilities

### ISSUE THREAD

**Issue by cmaeng** [department-of-veterans-affairs/va.gov-cms#8949]
Blocked by #8960 
Blocked by #8956
Blocked by #8993 

## ACs
- Add to VAMC Facility (health_care_local_facility)

![image](https://user-images.githubusercontent.com/5752113/167221068-476b8f45-e477-431c-9a8b-d7e3bbc85335.png)

   - [ ] New fieldset  
      - [x] Label COVID-19 safety guidelines
      - [x] description: "Help Veterans understand COVID-19 protocols at this facility. This will show up on the facility's location page as well as on the Operating Status page."
       - [x] Location Above the "Operating status" fieldset
       - [x] not required
   - [ ] Field `field_supplemental_status` 
      - [ ] Visibility: normal for all editors
      - [ ] Label "COVID-19 status"
      - [ ] description   -
      - [ ] help text "Select the status that most closely matches your facility's protocols <a>Learn more about COVID statuses.</a>"  Link goes to some knowledgebase article?  or a FE landing page?
      - [ ] type:  entity reference to facility supplemental status taxonomy.
      - [ ] Widget   entity reference select widget  
      - [ ] required: True
      - [ ] cardinality 1
      - [ ] Selector values is a concatenation of  {term name} - {term guidance}  Ideally with a support for limited html in the guidance  Maybe needs a View based  Entity reference selector?
      
![image](https://user-images.githubusercontent.com/5752113/167221309-2bc639a0-e208-4d90-a4a1-6de8783bab4d.png)

   - [ ] Updates to existing operating status fieldset and fields
![image](https://user-images.githubusercontent.com/5752113/167221171-6e85c33c-3d59-4e43-b23e-28051af60e95.png)

## Ongoing questions / decision points

1. Is the status field going to be editor controlled OR migrated from a source?
   - Answer: 5/5/22 It will be editor controlled.  No migration.
2. Is it by system or by facility?
   - Answer: 5/5/22  facility level

## discussion things
1.  Possible solution Use a vocabulary to provide the values and the description.  That way the description could be centralized AND controlled by an editor without hardcoding it on the front end.   Approved 5/22

**Comment by swirtSJW** [comment]
Design from #8960 is in 
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/8960#issuecomment-1120024726  

Updating AC's now

**Comment by swirtSJW** [comment]
Copyable for help and descriptions exists here https://github.com/department-of-veterans-affairs/va.gov-cms/issues/8993

**Comment by swirtSJW** [comment]
Field label is intentionally specific to COVID as that is the current use case, but field machine name is related to facility supplemental status because 
A: that is the vocabulary being referenced and
B: it may be leveraged for ebola, shmovid, wildfire air quality ...

**Comment by swirtSJW** [comment]
Assigning to Jay and Ethan... whoever is ready willing and able come Monday morning.  :)
