### ISSUE TITLE
Google analytics research spike

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#896]
To do 
- [x] Install google analytics and get it up on a PR environment, possibly with some of the configuration mentioned below. 
- [x] Which property to use? Collaborate with analytics platform team 
  - [x] Fill out request form ([done](https://github.com/department-of-veterans-affairs/va.gov-team/issues/5673))  
- [x] A designer and a developer should meet to think about what additional data might we track 
    - [ ] User session (eg Role) 
    - [ ] Should any users be excluded (eg Admin)
    - [ ] User section 
    - [ ] Content metadata (field_owner (section), moderation state, content type, field_office 
- [ ] Context: View tab / Content proofing page
  - [ ] Number of clicks on the left navigational panel.
  - [ ] Number of clicks on the breadcrumb. We want to understand if people are using it for navigation.
  - [ ] Number of clicks on the "Preview" button.

reference, etc) 
- [ ] How can make sure to only track prod? 
- [ ] Who should have access this analytics data, and how should they gain access?
- [ ] Are there any funnels we may want to track?
- [ ] Where should this setup be documented?
- [ ] What's the MVP for this? What can be added to the backlog?

**Comment by kevwalsh** [comment]
I've started the process for requesting the GA property, here: https://github.com/department-of-veterans-affairs/va.gov-team/issues/5673

**Comment by kevwalsh** [comment]
Meeting scheduled for this Thursday 12:30pm ET with VSP Analytics team

Objectives:
1. Receive walkthrough of CMS 
2. Understand in Drupal where code can be customized for GA implementation

**Comment by kevwalsh** [comment]
@jordanamello Can you add any data points you can think to the list in this issue? Under "A designer and a developer should meet to think about what additional data might we track". If you want to meet about it with Ethan or i to talk through that works too.

**Comment by jordanamello** [comment]
@kevwalsh Sure thing. @rachel-kauff please feel free to add more.

_Context: View tab / Content proofing page_
- Number of clicks on the left navigational panel.
- Number of clicks on the breadcrumb. We want to understand if people are using it for navigation.
- Number of clicks on the "Preview" button.

If possible, also map out these data points per user role.

**Comment by rachel-kauff** [comment]
I think that covers it for proofing.
