### ISSUE TITLE
Spike: next-build testing strategy

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#8970]
## Description
We should determine what sorts of testing we want to implement in next-build and plan for implementation.

## Acceptance Criteria
- [x] Determine what testing strategies and libraries are appropriate for next-build
- [ ] This information is documented in the repo in such a way that a developer knows what tests they need to implement and how (see also #9194)
- [x] Tickets are created for any retroactive test creation needed
  - #9180 
  - #9181 
  - #9184 
  - #9185 
  - #9186
  - #9188 
  - #9189 
  - #9190 
  - #9191 
  - #9192 
  - #9193  
- [x] Tickets are created for ensuring that tests can be run both locally and on CI

### CMS Team
Please check the team(s) that will do this work.

- [x] `Platform CMS Team`
- [ ] `Sitewide program`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by timcosgrove** [comment]
Visual diffing, static, unit, integration, e2e?

**Comment by ndouglas** [comment]
Copied Testing Strategy doc into Confluence [here](https://vfs.atlassian.net/wiki/spaces/PCMS/pages/2206236677/Testing+Strategy).

**Comment by ndouglas** [comment]
Working on documenting contribution requirements [here](https://github.com/department-of-veterans-affairs/next-build/blob/main/READMEs/testing.md).

**Comment by ndouglas** [comment]
^ I created a bunch of issues, but not for `src/pages/demo` because that seems like more transitory stuff to me.  Not sure if that's correct.

**Comment by ndouglas** [comment]
Created #9187 to refine how mock fixtures are created and maintained over time.
