### ISSUE TITLE
Change management for facility COVID status

### ISSUE THREAD

**Issue by ContentBrewmaster** [department-of-veterans-affairs/va.gov-cms#8971]
The change represented by the epic [8946](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/8946) will require action by some or all users by a specific deadline.
 
**1. Describe the change from the perspective of VA employees, in plain language. What is the employee going to experience with this change?**
VHA now has 3 levels of standard COVID-19 health protection guidelines. Editors will need to select the initial level for their locations by a deadline set by VA leadership. The current deadline for the data to appear in prod is May 23, 2022.

**2. Explain why the change is necessary from a CMS/platform and project goal perspective. Link to screenshots if that helps tell the story.**
The new facility COVID-19 level status will: 
- Help Veterans understand what to expect so they can plan their visit
- Increase consistency in how facility information is presented

**3. Select the role(s) impacted by the change.**
- [ ] All CMS users
- [ ] All CMS editors
- [ ] Vet Center editor
- [x] VA Medical Center editor
- [ ] VA Outreach Hub editor
- [ ] VA Benefits Hub editor
- [ ] Campaign landing page editor
- [ ] VA Resources and Support editor
- [ ] Offices editor
- [ ] Supporting roles such as CMS account admin, Facilities or Public websites team member

**4. How will success be defined for this change?**
COVID-19 health protection levels are visible on all VAMC facility pages.
[Audit tool](https://prod.cms.va.gov/admin/content/facilities/facility-status)

**5. How will success be measured for this change (audit, survey, other types of research, etc.)?**
The percentage of COVID-19 health protection levels visible on all VAMC facility pages.

**6. Does the change require new or updated:**
- [x] Knowledge Base article
How to edit COVID-19 levels for a VAMC facility
https://prod.cms.va.gov/help/vamc/about-locations-content-for-vamcs/about-alerts-and-operating-statuses/how-to-edit-covid-19-levels-for-a-vamc-facility 
If existing articles, list URLs:
How to edit a VAMC facility operating status
https://prod.cms.va.gov/help/vamc/about-locations-content-for-vamcs/about-alerts-and-operating-statuses/how-to-edit-a-vamc-facility-operating-status 
About VAMC alerts and operating statuses
https://prod.cms.va.gov/help/vamc/about-locations-content-for-vamcs/about-alerts-and-operating-statuses 

- [x] Training video(s)
To come.

- [x] CMS UI support

**7. Will the change be tested with users before release?**
- [x] Yes
- [ ] No

**8 Are there any known dependencies?**
- decision on whether existing operating status will be set to normal, which will erase all published statuses

**Comment by kevwalsh** [comment]
I'm closing this, we can open new issues as needed in epic #8946, including #9195
