### ISSUE TITLE
Spike: Editorial workflow config options for VAMC

### ISSUE THREAD

**Issue by EWashb** [department-of-veterans-affairs/va.gov-cms#8973]
## Details

Use [this tugboat](https://main-bdlgiqihelj9wkr6nz4ighchafpdqltv.demo.cms.va.gov) to experiment with patterns currently available in the CMS. 

This spike should first start with async investigation of the content types for VAMCs. After each participant has the chance to look at the current config options and make notes, we will attend a mob coworking session to discuss the path forward.

## Acceptance Criteria
- [x] Determine async what modules you prefer for VAMC content types before mob session and note what worked and what didn't
- [x] Attend mob-style coworking to determine preference for product 
- [x] Ensure patterns are accessible on all screen sizes
- [ ] Make additional tickets for implementation

**Comment by msbtterswrth** [comment]
Started playing with VAMC detail pages and tabs. There's a couple of things i'd like to look into, like getting the menu stuff out of the sidebar and into the tabs and possibly putting the revision message down under the editorial workflow like it is on some other content types.  
![image](https://user-images.githubusercontent.com/8375335/167663527-e46821a8-c940-45cf-b362-8989da79156d.png)

**Comment by EWashb** [comment]
This had to be bumped due to limited capacity this sprint from covid status support.

**Comment by EWashb** [comment]
ACs have been refined. First mob session is scheduled for 6/1/22

Participants should work on this async before the mob session in order to have a productive meeting.

**Comment by EWashb** [comment]
I am putting this on hold as we explore other priorities for Q3.

**Comment by EWashb** [comment]
this is no longer within scope
