### ISSUE TITLE
Google analytics product documentation

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#898]
## ACs

the team has access to the following info 
- [x] background on current implementation decisions - embedded snippet vs Drupal module, etc
- [x] how do we collaborate w/ Insights and Analytics team
- [x] how do we request access to GA for new users
- [x] what are we currently sending to GA

**Comment by daddison48** [comment]
@ethanteague good morning. Can you provide an update to this issue as to why it was moved to icebox please?

**Comment by ethanteague** [comment]
> @ethanteague good morning. Can you provide an update to this issue as to why it was moved to icebox please?

You bet, @daddison48 - we just keep bumping it from sprint to sprint, so it has effectively been iceboxed.

**Comment by oksana-c** [comment]
described the process here https://github.com/department-of-veterans-affairs/va.gov-cms/blob/master/READMES/analytics.md 

@ethanteague @kevwalsh , thanks for the background
