### ISSUE TITLE
FE implement covid status for facility, location and situation update pages

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#8986]
This issue can be done iteratively with multiple PRs (one per page).

The general look is going to be to use the [experimental alert-expandable](https://design.va.gov/components/alert-expandable)

Data source:  https://pr9028-sjpg4ebinnl4eooevngpwufok19n4akk.ci.cms.va.gov/
system with data: [VISN 4 -> Pitttsburgh](https://pr9028-sjpg4ebinnl4eooevngpwufok19n4akk.ci.cms.va.gov/admin/content?title=&type=health_care_local_facility&moderation_state=All&owner=12)

## AC s
- [ ] Covid status matches design for facility page (health_care_local_facility)
https://www.va.gov/pittsburgh-health-care/locations/belmont-county-va-clinic/
- [ ] Covid status matches design for system location page (locations_listing)
https://www.va.gov/pittsburgh-health-care/locations/
- [ ] Covid status matches design for operating status page (vamc_operating_status_and_alerts)  
https://www.va.gov/pittsburgh-health-care/operating-status/#facility-operating-statuses
- [ ] recordEvent() click function is added to track widget more info open and close clicks.

**Comment by kevwalsh** [comment]
Pending approval of designs by Dave on May 10
