### ISSUE TITLE
Write VA.gov page for describing covid statuses

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#8998]
Assumption:  There will be a veteran facing page on VA.gov that will be linked to by all statuses that fully describe the various statuses.

## Things to determine
- [ ] Whos is going to write it?
- [ ] What is the Url where it will live?
- [ ] Artwork?

**Comment by kevwalsh** [comment]
Danielle and Beth are working on this
