### ISSUE TITLE
Containerize the CMS

### ISSUE THREAD

**Issue by cweagans** [department-of-veterans-affairs/va.gov-cms#9004]
## Description

We need a Docker container for the CMS. This may be used locally or on BRD or on some orchestration system (EKS, ECS, etc).

## Acceptance Criteria
- [ ] Testable_Outcome_X
- [ ] Testable_Outcome_Y
- [ ] Testable_Outcome_Z
- [ ] Requires design review

### CMS Team
Please check the team(s) that will do this work.

- [x] `Platform CMS Team`
- [ ] `Sitewide program`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by TheBoatyMcBoatFace** [comment]
Closing. Lagoon handles this.
