### ISSUE TITLE
Investigate getting a CMS-specific VPC

### ISSUE THREAD

**Issue by cweagans** [department-of-veterans-affairs/va.gov-cms#9005]
## Description
Our needs don't overlap a lot with the rest of the platform. If we had our own CMS-specific environment to work in, we can move faster.

## Acceptance Criteria
- [ ] Testable_Outcome_X
- [ ] Testable_Outcome_Y
- [ ] Testable_Outcome_Z
- [ ] Requires design review

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Platform CMS Team`
- [ ] `Sitewide program`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by olivereri** [comment]
Closing this after discussions and this comment:
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9007#issuecomment-1122713684
