### ISSUE TITLE
[SPIKE] RFC for hosting pivot

### ISSUE THREAD

**Issue by cweagans** [department-of-veterans-affairs/va.gov-cms#9007]
## Description

See writeup on https://github.com/department-of-veterans-affairs/va.gov-cms/issues/8734#issuecomment-1119290107 for details

This RFC should explore/get feedback on the things that @mchelen mentioned here: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/8734#issuecomment-1119866490 + any other topics that would be useful to the decision making process.

Ref other tickets:
* https://github.com/department-of-veterans-affairs/va.gov-cms/issues/8734
* https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9004
* https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9005
* https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9006
* https://github.com/department-of-veterans-affairs/va.gov-cms/issues/8848
* https://github.com/department-of-veterans-affairs/va.gov-cms/issues/8962

## Acceptance Criteria
- [x] Determine approach for re-platforming CMS (for running Sorry-Cypress in support of test improvement effort)
  - [x] Create RFC outlining approach as needed 

### CMS Team
Please check the team(s) that will do this work.

- [x] `Platform CMS Team`
- [ ] `Sitewide program`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by olivereri** [comment]
#8848 I think really was more of a spike than a "get something done" ticket. It sparked a couple of discussions about how to host Sorry-Cypress dashboard and ultimately post-BRD CMS. We first discussed a major departure from the platform provided solution. Here's a analogy:

1. Working together in the same building, same office, same floor at the same desk.
2. Working beside each other in the same building, same office, same floor at different desks.
3. Working in an entirely different building all together.

Point 3 is what leads to this RFC. The idea to host the CMS in its own VPC and take on all the challenges that come with it. After more conversation/discussion that seems unfeasible and doesn't best serve who we serve.  Point 2 is more likely what we want to do for the CMS. We will likely want to work beside the Platform Team with the EKS solution, but we may not want to follow their interpretation of GitOps using ArgoCD. Instead we can design and implement a GitOps pipeline that deploys to the EKS cluster that works best for the CMS team.

Point 1 is the direction we feel is best for Sorry-Cypress. Cypress is used for tests by several teams in the ecosystem so it could benefit us all. Implementing it in the way documented by Platform Operations ensures it has broad support for all teams.

Concretely what that means is that we should close #9005 and #9006, then repurpose #8848 as a Spike that is the genesis for the other listed issue tickets.
