### ISSUE TITLE
Create event listeners for release state transitions for logging and metrics

### ISSUE THREAD

**Issue by cweagans** [department-of-veterans-affairs/va.gov-cms#9009]
## Description

Create an event listener that watches for release state transitions to identify any state changes that may need attention. When the state is changed:
* Log a message (maybe remove the logging from the queue workers if the logging we can do through the event listener is good enough)
* Push events to datadog

Ref #8108

## Acceptance Criteria
- [ ] Release state transition events are sent to Datadog 
- [ ] Document where to find new events 
- [ ] Create followup ticket to display above metrics in dashboard

### CMS Team
Please check the team(s) that will do this work.

- [x] `Platform CMS Team`
- [ ] `Sitewide program`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by TheBoatyMcBoatFace** [comment]
Datadog monitors Content Release. Issue resolved.
