### ISSUE TITLE
Update the release status block in the toolbar

### ISSUE THREAD

**Issue by cweagans** [department-of-veterans-affairs/va.gov-cms#9010]
## Description

Current release status block only shows the last build time. Additional metrics to be added for better visibility into content build.

* Move the related code from `va_gov_backend` to `va_gov_build_trigger`
* Update the block so that it reports the current release state + the last deploy time (state key to look at is `va_gov_build_trigger.last_release_complete`)
* Maybe show estimated next release/"when will my content go out" prediction for editors

Ref #8108

## Acceptance Criteria
- [ ] Release status block is updated to reflect more useful metrics
 - e.g. last build time, expected time to release, current content release state

## Implementation

- discuss approach with Sitewide 

### CMS Team
Please check the team(s) that will do this work.

- [x] `Platform CMS Team`
- [ ] `Sitewide program`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by TheBoatyMcBoatFace** [comment]
prov.cms.va.gov now does this.
