### ISSUE TITLE
Content release metrics and alerting

### ISSUE THREAD

**Issue by cweagans** [department-of-veterans-affairs/va.gov-cms#9012]
## Description

Metrics to export (potentially on a per-minute basis, rather than every 15 minutes):
* Content Release request Queue lengths (advanced queue, not Drupal core queue)
* Time since last release state transition (any)
* Time since last release state (for each possible release state: ready, requested, dispatched, starting, in progress, complete)

Alerts to consider:
* Content Release request Queue length is increasing
* Time since last release state transition is out of the ordinary
* Time since last `complete` event is over some threshold

Ref #8108

## Acceptance Criteria
- [ ] Ensure the above metrics are tracked and displayed in Datadog 
- [ ] Determine appropriate thresholds for alert triggers and implement in PagerDuty

### CMS Team
Please check the team(s) that will do this work.

- [x] `Platform CMS Team`
- [ ] `Sitewide program`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by TheBoatyMcBoatFace** [comment]
Moving to New Epic
- #11928

**Comment by TheBoatyMcBoatFace** [comment]
Closed per Platform CMS discussion on Dec. 19, 2022

**Comment by timcosgrove** [comment]
We discussed this in sprint planning. These metrics would be in service of surfacing time since last release, which we already have via other means. 

If we specific need to diagnose issues with the content release dispatch queueing, we can reopen this.
