### ISSUE TITLE
Add a mechanism to link to the build log

### ISSUE THREAD

**Issue by cweagans** [department-of-veterans-affairs/va.gov-cms#9013]
## Description

When the build is starting, it would be nice for the CMS to be informed of where a user should go to watch the build output. For Github Actions, we can send a link to the workflow output when the state is transitioned to `starting`. For local/tugboat/ddev builds, we can link to the build.txt file.

Ref #8108

## Acceptance Criteria
- [ ] CMS is aware of the link to the workflow output when state is updated 
- [ ] Link to workflow output is displayed on a status page (https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9014)

### CMS Team
Please check the team(s) that will do this work.

- [x] `Platform CMS Team`
- [ ] `Sitewide program`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by ndouglas** [comment]
I don't believe this is necessary given our current anticipated strategy, team size, content-build status, etc.
