### ISSUE TITLE
Add a content release status page (for internal use)

### ISSUE THREAD

**Issue by cweagans** [department-of-veterans-affairs/va.gov-cms#9014]
## Description

After #8108, the CMS has a lot of info about the state of content release. We should expose _all_ of it on a developer-facing status page.

Things to include:
* All timestamps recorded by `ReleaseStateManager`
* Current release state
* Link to last build log (if #9013 is done)
* All calculated metrics from #9012

The info being sent to Datadog should cover most of this, but it's important to be able to view instantaneous snapshots of the release state (rather than e.g. a rolling average like you'd see in Datadog).

## Acceptance Criteria
- [ ] Status page exists in the CMS for internal consumption

### CMS Team
Please check the team(s) that will do this work.

- [x] `Platform CMS Team`
- [ ] `Sitewide program`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by TheBoatyMcBoatFace** [comment]
Datadog is recording this for developer use. Reopen if additional functionality desired.
