### ISSUE TITLE
Implement MVP product tags for KB to increase findability

### ISSUE THREAD

**Issue by EWashb** [department-of-veterans-affairs/va.gov-cms#9018]
## Background ##

As a knowledge base user, I would like to see KB articles labeled in an obvious way to determine what is relevant for my tasks. 

## Assumptions ##

KB article tags empower the editor to help themselves troubleshoot and find the information they need to produce high-quality content
![image (4).png](https://images.zenhubusercontent.com/614b6cbe05afafb268be4c0b/ad72a9e0-091e-41cd-9054-684ec5d37b61)

## Acceptance Criteria ##

- [x] UX design and writing review before implementation

Revised ACs as of 5/17/22

-[ ] Review process and feasibility for linking the product tags
-[ ] determine if it is best practice to link only those that have a landing page to go to or if it is best to wait until all are create

**Comment by msbtterswrth** [comment]
Approved design screenshot is below. First tag is a non-linked tag, second is linked. 
![image](https://user-images.githubusercontent.com/8375335/169098247-8af839f7-a194-48f0-81c5-7a95402be716.png)

**Comment by EWashb** [comment]
We are going to put this on hold for Sprint 58 to determine the proper workflow. Some things to consider:

1. Should these be visible if they aren't taking to anywhere since the functionality appears to be a link
2. Should this go out with no links?
3. Should this go out with some linked and some not (since we don't have product landing pages for all tags)

**Comment by rachel-kauff** [comment]
@EWashb I reckon we should kick this back into the icebox for now until we do a focused effort on KB stylin'

**Comment by msbtterswrth** [comment]
Worked with cindy to refine the MVP design: 
![image](https://user-images.githubusercontent.com/8375335/180301680-c85dd7db-cb67-49d8-bf93-dd8e50c0dbca.png)
