### ISSUE TITLE
[spike] Inventory phpunit tests and identify candidates for converting to unit tests

### ISSUE THREAD

**Issue by cweagans** [department-of-veterans-affairs/va.gov-cms#9020]
## Description
Many of our "unit" tests are actually integration(-ish) tests. They operating on a real Drupal site with a real database and all that. They don't necessarily need to do that though: we can mock a lot of things and our unit tests can be _blazing_ fast as a result. We need to figure out which tests can be converted to unit tests, and then open (relatively small) tickets for converting each of them.

## Acceptance Criteria
- [ ] Testable_Outcome_X
- [ ] Testable_Outcome_Y
- [ ] Testable_Outcome_Z
- [ ] Requires design review

### CMS Team
Please check the team(s) that will do this work.

- [x] `Platform CMS Team`
- [ ] `Sitewide program`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by TheBoatyMcBoatFace** [comment]
Unclear. Please add additional detail and reopen if still needed.
