### ISSUE TITLE
Events v2: discovery/onboard PW engineering

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#9024]
## Description
PW engineer to get up to speed and work with Ethan to ~~formulate QA plan for recurring events and date filtering~~ get familiar with technical aspects of Events, in order to be ready for future support.

QA for Events V2 / Recurring events is covered separately under #9141 .

## Collateral
Compiled 5/13
* [Outreach Events Calendar Product Outline (1.0)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/outreach-events/product-outline.md) in va.gov-team
* [Events notes Google Doc](https://docs.google.com/document/d/1bU3QMCFBkE3BcDyKrhHCCcZQpPEBhH2zyVE8ndkAv9M/edit#) -- 5/13 summary of open epics / tasks, Questions for 5/18 sync with Events folks from Facilities team
* [#28918 - Outreach & Events Hub - 2021 Enhancements](https://github.com/department-of-veterans-affairs/va.gov-team/issues/28918) - Big picture V2 overview of requested features / updates, in progress. 
* [#1956 Recurring (repeating) events](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/1956) - In progress
* [#1605 Event form UX](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/1605) - Several open items, unclear whether prioritized / in progress, or what must be resolved for "Events V2"

## Acceptance Criteria

- [x] meet with Facilities for knowledge transfer
- [x] get demo
- [x] understand local setup

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Platform CMS Team`
- [ ] `Sitewide program`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by jilladams** [comment]
Jill to: 
* Find existing research / documentation and add to ticket
* Schedule Wed 5/18 sync with Ethan / Max / PW FE team for knowledge share about state of the world. In that meeting, determine next steps and add points here.

**Comment by jilladams** [comment]
Ticket body updated -- unassigning from me, and we can reassign for next steps in Sprint 59 planning, or after 5/18 sync with Facilities.

**Comment by jilladams** [comment]
This ticket ended up covering the immediate Events V2 / Recurring events QA needs. Not so much with the actual code-level onboarding to support this work once it's shipped and Facilities hands it to us to maintain. I'd like to suggest a separate technical timeboxed SPIKE ticket, with Daniel and Allison, to get into the code review / technical side onboarding. 

Does that make sense to @allisonlu  / @wesrowe ?

**Comment by allisonlu** [comment]
`content-build`
* Check out events-v2 branch
* `yarn preview` - should be enough to get it up and running

`vets-website` 
* Checkout events-v2 branch
* `yarn watch`
* Enable feature flag
    * Commenting out is easiest
    * Applications/static/events/components/index.js

Main files to check:
* Events/components/app.jsx
* Events/helpers - helper functions
