### ISSUE TITLE
Draft CMS portion of Facility COVID status emails to PAOs for May 13-18 delivery

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#9035]
## Description

- [x] Draft 2 emails (announcement and launch) May 11-12
- [x] Send to VHA DM and Sitewide Content on May 12 for review
- [x] Update emails as needed in preparation for VHA Digital Media delivery to editors

[WIP](https://docs.google.com/document/d/1haUKbabO5QvB4d9cXWZ7lTRNBoiSVB9LRZlJNxi-oW4/edit#)

## Acceptance Criteria
- [ ] Emails reflect latest information about what editors will experience when facility COVID status is available in the CMS

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Platform CMS Team`
- [ ] `Sitewide program`
- [x] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by ContentBrewmaster** [comment]
Drafts sent to Jeff Grandon and Danielle Thierry Thursday at 11:40 am ET for review and input. This version did not capture Suzanne's comments.
