### ISSUE TITLE
next-build: Implement Google Analytics

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#9037]
## Description
Components that were built for next-build all have Google Analytics built in. We need to continue tracking the associated events in the new system. 
Ref: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9255
* Include library in appropriate manner
* Set up Environment variable(s) with appropriate GA property ids

## Acceptance Criteria
- [ ] 

### CMS Team
Please check the team(s) that will do this work.

- [x] `Platform CMS Team`
- [ ] `Sitewide program`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by jkalexander7** [comment]
Closing - no longer needed
