### ISSUE TITLE
Outreach events should be sorted by date ASC

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#904]
**Describe the bug**
Outreach events are sorted by date ASC

**To Reproduce**
https://www.va.gov/outreach-and-events/events

**Expected behavior**
Outreach events should be sorted by date ASC

**Comment by ethanteague** [comment]
This task is subsumed by logic in this pr: department-of-veterans-affairs/vets-website#11608

**Comment by kevwalsh** [comment]
This is a dupe of #1220 at this point.
