### ISSUE TITLE
CMS Announcement block

### ISSUE THREAD

**Issue by msbtterswrth** [department-of-veterans-affairs/va.gov-cms#9042]
## Description
As a CMS admin, sometimes I need to create an announcement within the CMS. We're currently using the 'alert' block on the login page to accomplish that, but we want to create a specific, reusable block type that we can place on any arrangement of pages/sections/roles.

Existing styling on alert block
![image](https://user-images.githubusercontent.com/8375335/167715021-0c0befab-43e7-4cd2-81dc-ff79d02d6dcf.png)

## Acceptance Criteria
- [ ] title field
- [ ] limited rich text body field
- [ ] design/ux review
- [ ] icon selector?
- [ ] severity level? (info, warning, emergency, could come pre-populated with an icon instead of selector)
- [ ] dismissible for post-mvp?

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Platform CMS Team`
- [ ] `Sitewide program`
- [x] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by EWashb** [comment]
We will set up the basic config to explore with UX either later in sprint 58 or thereafter, depending on other priorities.
