### ISSUE TITLE
All "listing" pages need no results behavior

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#905]
## User Story or Problem Statement

New content listing pages should still work when they have no content. 

## Acceptance Criteria
The following content listing pages have no result behavior. (this syntax should be double checked against what we already have on the Events listing)
* Event - No events at this time.
* Stories - No stories at this time.
* News releases - No news releases at this time.
* Health services - No health services at this time. 
* Locations - No locations at this time.

**Comment by ethanteague** [comment]
This task is subsumed by logic in this pr: https://github.com/department-of-veterans-affairs/vets-website/pull/11608
