### ISSUE TITLE
Add Covid schema.org markup

### ISSUE THREAD

**Issue by msbtterswrth** [department-of-veterans-affairs/va.gov-cms#9052]
As a Veteran, I want to get information about Covid alerts or closures in google/search engine results when searching for my facility. 

We can use the special schema google has provided for covid-19 statuses [found here](https://developers.google.com/search/docs/advanced/structured-data/special-announcements) to display an alert in search snippets. This uses the [SpecialAnnouncement](https://schema.org/SpecialAnnouncement) data type from schema.org

An example would looks something like 
```<script type="application/ld+json">
    {
      "@context": "https://schema.org",
      "@type": "SpecialAnnouncement",
      "name": "Shelter-in-place for 3 California counties",
      "text": "As of 11:59 pm on March 17, 2020, all individuals in the 3 counties must strictly follow the provisions in this new Order. This new Order will be in effect through March 30, 2020.",
      "datePosted": "2020-03-17T08:00",
      "expires": "2020-03-24T23:59",
      "quarantineGuidelines": "https://example.org/california/shelter-in-place/",
      "diseasePreventionInfo": "https://example.org/california/prevention-tips/",
      "spatialCoverage": [
        {
          "type": "AdministrativeArea",
          "name": "San Francisco County, CA"
        },
        {
          "type": "AdministrativeArea",
          "name": "Marin County, CA"
        },
        {
          "type": "AdministrativeArea",
          "name": "Santa Clara County, CA"
        }
      ]
    }
    </script>
```

An example of what this may look like in google search: 
![image](https://user-images.githubusercontent.com/8375335/167876832-b0623b79-5c10-4d12-934e-38f1e3128881.png)

**Comment by EWashb** [comment]
@swirtSJW am I right in thinking this is no longer within scope since we are retiring the separate covid status? I propose we close this

**Comment by jilladams** [comment]
Closing re: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13681
