### ISSUE TITLE
Move content build triggering logic to the CMS

### ISSUE THREAD

**Issue by jkalexander7** [department-of-veterans-affairs/va.gov-cms#9062]
## Background

Coordinating build requests, manual builds, and scheduled builds across two systems is complicated and error prone. Moving the triggering logic into the CMS would make the build process more stable and enable more frequent builds. Ref: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/8108

### Problem Statement

As a CMS Engineer, I want to move the triggering logic out of the content build workflow and into the CMS so that Drupal is entirely in control of when content build is triggered.

### Affected users and stakeholders

* CMS Engineers

## Acceptance Criteria
- [ ] Responsibility for kicking off content build is entirely on the CMS

### CMS Team
Please check the team(s) that will do this work.

- [x] `Platform CMS Team`
- [ ] `Sitewide program`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by timcosgrove** [comment]
Closing out with the close of Q3. Unfinished issues are added to #10896
