### ISSUE TITLE
Pager broken in Facility Locator on page 4 for searches with many results

### ISSUE THREAD

**Issue by RWEagans** [department-of-veterans-affairs/va.gov-cms#9067]
## Describe the defect
Users are finding the system ([VA.gov](http://va.gov/) under the provider locator) gives an error "Find VA locations isn't working right now" after about page 3 or 4 of search results. Once the error occurs it requires closing that browser and starting another one. It happens pretty much anytime users have a large provider group and have multiple pages to look through.

https://dsva.slack.com/archives/C0FQSS30V/p1652367495652749

## To Reproduce
1. Use [this search](https://www.va.gov/find-locations/?page=1&address=52002-2840&facilityType=provider&serviceType=111N00000X&latitude=42.508855&longitude=-90.733438&radius=10&bounds%5B%5D=-91.483438&bounds%5B%5D=41.758855&bounds%5B%5D=-89.983438&bounds%5B%5D=43.258855&context=Dubuque%2C%20Iowa%2052002%2C%20United%20States) in a browser (Zip code 52002-2840, Facility Type = Community Providers, Service type = Chiropractor) CAREFUL: your browser may crash due to this defect, so save any work.
2. Click through the pager to Page 4
3. See error

## Expected behavior
Pager should work as expected.

## Screenshots

<img width="1136" alt="Find_VA_Locations___Veterans_Affairs" src="https://user-images.githubusercontent.com/643678/170509624-8d3b73d1-e0c1-4a97-9559-c006a236e380.png">

 ## Additional context
Add any other context about the problem here. Reach out to the Product Managers to determine if it should be escalated as critical (prevents users from accomplishing their work with no known workaround and needs to be addressed within 2 business days).

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Defect")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS workstream (orange) (not needed for bug tickets)
- [ ] CMS-supported product (black)

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Platform CMS Team`
- [ ] `Sitewide program`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by jtmst** [comment]
@kevwalsh  verified in prod.  new throttle limit caps at 8 requests per minute
