### ISSUE TITLE
VA Erie Health services showing up in VA Eastern Oklahoma. Cloning issue.

### ISSUE THREAD

**Issue by RWEagans** [department-of-veterans-affairs/va.gov-cms#9068]
## Describe the defect

https://dsva.slack.com/archives/CT4GZBM8F/p1652211082198759

## Additional context
Add any other context about the problem here. Reach out to the Product Managers to determine if it should be escalated as critical (prevents users from accomplishing their work with no known workaround and needs to be addressed within 2 business days).

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Defect")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS workstream (orange) (not needed for bug tickets)
- [ ] CMS-supported product (black)

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Platform CMS Team`
- [ ] `Sitewide program`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by JayDarnell** [comment]
@stefaniefgray I have manually recreated all the offending nodes. Please verify all is well and if so please close this issue.

**Comment by stefaniefgray** [comment]
Author notified in https://va-gov.atlassian.net/browse/VAHELP-4160
