### ISSUE TITLE
Remove isCerner hard coded data source feature toggle from Cerner React Widgets (only)

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#9078]
## Description

"Cerner react widgets" = the 5 widgets that Public Websites maintains. When logged in (using Cerner test users), the buttons on these widgets will direct users, using deeplinks, into the proper Electronic Medical Health Records (EMHR) system, either VistA or Cerner. 

We previously cut these widgets over to use the new Drupal data source. They are using a feature flag, `pw_ehr_cta_drupal_source_of_truth`, which is enabled in Staging & Prod. 

This ticket is to: 
* Switch default behavior so that these widgets are "always on" to use Drupal data, and no longer need the feature toggle
* Remove that feature flag
* Remove references to the "Hard-coded API" **within these 5 widgets** 
  * #9307 tracks completely removing the Hard-coded API from the code-base. Please keep these two pieces of work separate for easier code review

## Acceptance Criteria
- [ ] Drupal SSOT is still used for Cerner widgets (reading fetched vamc-ehr.json data in redux store)
- [ ] Hard coded mechanism and feature toggle are removed from Cerner Widget code.
- [ ] The feature toggle itself is removed, `pw_ehr_cta_drupal_source_of_truth`
- [ ] QA 
  - [ ] Test all 5 Cerner-related widgets using Cerner test users
    - [ ] [Refill and track your prescriptions](https://www.va.gov/health-care/refill-track-prescriptions)
    - [ ] [Send a secure message to your health care team](https://www.va.gov/health-care/secure-messaging)
    - [ ] [Schedule and manage health appointments](https://www.va.gov/health-care/schedule-view-va-appointments)
    - [ ] [View your lab and test results](https://www.va.gov/health-care/view-test-and-lab-results)
    - [ ] [Apply now for VA health care](https://www.va.gov/health-care/apply/application)
~~- [ ] Consider automated tests? (Ryan input)~~ Broken out into # (tbd ticket)

NOTE: We have access to test user data: https://agilesix.slack.com/archives/C04GEA1LB4Z/p1671556481732549
* My VA Health = Cerner
* My Health eVet = Vista

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Platform CMS Team`
- [ ] `Sitewide program`
- [ ] `⭐️ Sitewide CMS`
- [X] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by apisandipas** [comment]
Status Update 12/29 - This issue has a PR up but is currently block by required review by @ryguyk

**Comment by jilladams** [comment]
Merged today, in Review / QA and can close after we verify all is well in prod after deploy tomorrow.
