### ISSUE TITLE
[SPIKE] Build a VA SOCKS desktop client prototype

### ISSUE THREAD

**Issue by cweagans** [department-of-veterans-affairs/va.gov-cms#9091]
## Description

I've been doing quite a bit of support for SOCKS issues on the various CMS and CMS-adjacent teams. I'm happy to keep doing that if needed, but I think there's a better way.

I've noticed that there are several common sticking points with our current SOCKS onboarding process. In particular, _requiring_ using a command line utility is a pain point for people who don't regularly use the command line. This is _especially_ true for Windows users, who are currently required to install an entire Linux distro via WSL first.

This is slightly outside of our area of responsibility, but I would like to suggest that we don't continue doing this and instead build a quick, cross-platform SOCKS client for Mac, Linux, and Windows. I've started prototyping this with Flutter already and I've gotten pretty far in not a lot of time. The list of things to do to get this working well on all platforms is pretty short (mostly cosmetic things).

If I can spend a sprint on this, the process of getting somebody onboarded to SOCKS would be roughly as follows (on all platforms):
* Download the app and install it
* Click through the onboarding wizard
* Wait for ops to approve/close the Github ticket

At that point, connecting to SOCKS is a matter of opening the app and clicking connect. No WSL, no command line, etc.

Here's what the mac UI looks like right now:

https://user-images.githubusercontent.com/101590/168644580-48cf72dd-2e6a-4792-8653-e0460ded6445.mp4

Video notes:
* The UI isn't pixelated like it appears in some places in the video - that's my video recording software doing something funky.
* The "Get Access" tab has some placeholder statuses for the time being. It's not actually checking anything yet. When I clicked the "Recheck" button, it's just assigning random statuses to each item in the list. In the real version of the app, each item will reflect the actual state. As you click the buttons on the right side, it'll perform the appropriate action and update the status. Additionally, the state will be checked as the application starts up so that it doesn't just show question marks when you open that page.
* My intent is for the settings page to include yes/no options for "Start SOCKS client on login" and "Connect to SOCKS when the app starts" (or something along those lines), defaulting both of them to yes.
* Backup/restore would be a quick way for people to package up their keys and config and move them to a new machine (I'm thinking a zip file with ~/.ssh and the application settings file in it, which would simply be copied into place on restore). I'm not sure if this is desirable or not. The alternative is going through the onboarding steps again on the new machine and having to ask ops to swap out the key.
* The app should probably minimize to the system tray, rather than exiting. I have two different ways to do that ([option a](https://pub.dev/packages/system_tray) and [option b](https://pub.dev/packages/tray_manager)) - I just haven't done it yet.
* Ideally, there would be an endpoint inside the VA network that the app can send requests to once every 10-15 seconds to test the connection. If the connection has died for whatever reason, I'd like for the app to automatically reconnect. This is relatively straightforward as long as there's an endpoint that can handle the load of however many users regularly sending HTTP requests to it. `vtk` currently uses Sentry as the test endpoint, but `vtk` only tests the connection occasionally.

My intent is to use widget toolkits that match each platform. The macOS toolkit is shown in the video. There are also corresponding themes for [Windows](https://github.com/bdlukaa/fluent_ui) and [Linux](https://github.com/gtk-flutter/adwaita) that make the app not seem out of place.

## Acceptance Criteria
- [ ] SOCKS onboarding process is automated

### CMS Team
Please check the team(s) that will do this work.

- [x] `Platform CMS Team`
- [ ] `Sitewide program`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by olivereri** [comment]
No longer needed. Closing.
