### ISSUE TITLE
Node packages necessary for content-build should be moved from devDependencies to dependencies

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#9116]
## Description
Content-build's primary build process requires several packages that are defined in devDependencies for the project. A `yarn install` in a production environment will not install these dev packages, and so the build fails in that situation. 

All packages necessary for a production build should be in non-dev dependencies. Example packages in this situation include but are not limited to:

* semver
* chokidar
* chalk

## Acceptance Criteria
- [ ] All packages required for a content-build production build are moved from devDependencies to depdencies.
- [ ] The command below runs without error.

The following command can be used to test this and should run without error (NB may need adjustment: basically we are testing that `yarn install` in a production environment installs all the packages necessary for a production build to run successfully):
```
NODE_ENV=production yarn install
NODE_ENV=production yarn build --buildtype=vagovprod --asset-source=local --pull-drupal --drupal-max-parallel-requests=15 --verbose
```

### CMS Team
Please check the team(s) that will do this work.

- [x] `Platform CMS Team`
- [ ] `Sitewide program`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by TheBoatyMcBoatFace** [comment]
@timcosgrove if this is still needed, please reopen.
