### ISSUE TITLE
Create the CMS announcement block as design system component

### ISSUE THREAD

**Issue by EWashb** [department-of-veterans-affairs/va.gov-cms#9124]
## Background

During sprint 58, the CMS announcement block was implemented on prod as a new component for CMS alerts. In order to provide consistency in the CMS, designers will need to create this new component in the design system.

## Acceptance Criteria
- [x] Design component in the figma library:  https://www.figma.com/file/ScABI31f3MRFEvQ8WitVPa/CMS-Design-System?node-id=1644%3A87725
- [x] Provide design governance documentation: https://va-gov.atlassian.net/wiki/spaces/VAGOV/pages/1773371393/Announcement+alert 
- [x] Dev handoff for implementation in storybook

**Comment by cjterdi** [comment]
We can close this. The Component in Figma contains design constraints and Rachel had added purpose, usage governance and process in confluence.
