### ISSUE TITLE
Determine tech sustainability for current CMS announcement block config

### ISSUE THREAD

**Issue by EWashb** [department-of-veterans-affairs/va.gov-cms#9128]
## Background

Tech lead or dev, with guidance of tech lead, should determine how to handle the config for this announcement and if it is sustainable for reusability and all use cases. Also, tech lead should investigate options to leverage the site alert options related to dismissability. 

Current state is requiring manual placement and export config. 
Process is: 
Dev pulls the db locally, re-place the block on the block layout page, and export config. Then commit / push the config to the repo.

## Acceptance Criteria

- [ ] Current config is reviewed with priority for reusability, ease of use, and sustainability
- [ ] Determine automatic placement options
- [ ] If deficiencies are determined with current technical process, new tickets are made and backlogged for appropriate next steps to make the block more usable for product teams.

**Comment by msbtterswrth** [comment]
There's a [sandbox module](https://www.drupal.org/sandbox/marcus_w/config_ignore_custom_blocks) which we could maybe investigate that ignores custom block placements.

**Comment by EWashb** [comment]
After syncing with @dsasser @tjheffner and @swirtSJW it was determined that Sitewide Alert would be the best path forward. It provides a better option for the announcement block and site alert. We will be transitioning to that via #9509
