### ISSUE TITLE
Documentation: implement Typedoc

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#9137]
## Description
In https://github.com/department-of-veterans-affairs/va.gov-cms/issues/8433 we determined Typedoc to be a useful tool for generating documentation of the next-build codebase. We need to do some implementation to support this, and make some decisions on what should be documented.

## Acceptance Criteria
- [ ] A yarn command exists to build docs with Typedoc
- [ ] Typedoc documentation is made available for the local development at a separate local HTTP server (i.e. possibly [http-server](https://www.npmjs.com/package/http-server))
- [ ] Some guidelines are decided on regarding what level of documentation we will implement, i.e. potentially types, components, etc, and what that documentation should contain
- [ ] Tickets are written to apply these guidelines to existing code

### CMS Team
Please check the team(s) that will do this work.

- [x] `Platform CMS Team`
- [ ] `Sitewide program`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by tjheffner** [comment]
Completed in https://github.com/department-of-veterans-affairs/next-build/pull/267
