### ISSUE TITLE
New KB article: changing text links to action links or buttons

### ISSUE THREAD

**Issue by rachel-kauff** [department-of-veterans-affairs/va.gov-cms#9142]
## Background context
Person requesting the article: 
- Randi Hecht (Sitewide Content)

Associated SMEs/ stakeholders: 
- [name them here]

Audience: 
- [name product or type of editor]

Related KB articles: 
- [link them here]

Associated source of truth documentation: 
- [for example, could be the VA content style guide]

This article addresses:
- [ ] A business-driven need
- [x] A user-driven need

Does this article have a deadline?
- [ ] Yes: [name the deadline here]
- [x] No

Is the article associated with change management initiatives
- [ ] Yes
- [x] No

What parts of the interface will link to the article, if any? 
- [list them here]

## Process
1. Refine and prioritize
2. Identify content needs
3. Draft article content 
4. Get peer review and/or stakeholder review (if necessary)
5. Publish

ACs
- [ ] Article is reviewed by [assigned peer reviewer] and/or [SME/stakeholder]
- [ ] Article follows documented content style for the knowledge base
- [ ] Article is assigned to a parent 
- [ ] Impacts on other KB articles have been considered and any necessary changes have been made
- [ ] Help desk has been made aware of the new article
- [ ] (If appropriate) once published, the person requesting the article has been notified

**Comment by EWashb** [comment]
@laflannery do you know if we ever created an article about this? Or is this still needed?

**Comment by laflannery** [comment]
@EWashb I can't find anything but also this seems unclear, there's not much in the description - the request is for an article about how to add [action links](https://design.va.gov/components/link/action) and [buttons](https://design.va.gov/components/button/) in rich text editors? 

If that's the case I'm not entirely sure that's possible, but I can at least investigate

**Comment by laflannery** [comment]
I did confirm that we can add action links and "buttons" (fake buttons) into rich text editors but I do want to discuss this before we add a KB article promoting this, especially the button thing since we should not be styling links like buttons because that's an inaccessible experience.

**Comment by EWashb** [comment]
@laflannery, apologies for the very late response. I agree that we should only promote guidance around the preferred experience. I do not know the original request situation, but I see it was from Randi.

**Comment by EWashb** [comment]
I agree @laflannery. I'll close it.
