### ISSUE TITLE
Track real-world usage of AWS admin permissions & create plan to reduce privileges

### ISSUE THREAD

**Issue by cweagans** [department-of-veterans-affairs/va.gov-cms#9144]
See https://github.com/department-of-veterans-affairs/devops/pull/11207 for context (in particular, https://github.com/department-of-veterans-affairs/devops/pull/11207#issuecomment-1130635339). Also https://dsva.slack.com/archives/CJYRZK2HH/p1652714486314709

### CMS Team
Please check the team(s) that will do this work.

- [x] `Platform CMS Team`
- [ ] `Sitewide program`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by TheBoatyMcBoatFace** [comment]
No longer active/needed/applicable
