### ISSUE TITLE
Redirect Request for: San Diego VA Medical Center

### ISSUE THREAD

**Issue by JayDarnell** [department-of-veterans-affairs/va.gov-cms#9149]
### Instructions
- This issue will be used from initial request through implementation to ensure all individuals working on this are notified of status updates.  Please do not create multiple issues to track different steps.
- It is your responsibility to notify VA stakeholders as appropriate.
- Be sure to link the related facility closure / rename issue.

### Implementation date
When does this request need to be live: as soon as possible

### Redirects 
| Current URL  |  Redirect Destination or New URL |
| /san-diego-health-care/locations/san-diego-va-medical-center  |  /san-diego-health-care/locations/jennifer-moreno-department-of-veterans-affairs-medical-center |
| current URL | new URL |

## CMS Team
Please check the team(s) that will do this work.

- [ ] `Platform CMS Team`
- [ ] `Sitewide program`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [x] `⭐️ User support`

**Comment by cmaeng** [comment]
@JayDarnell could you throw a rough point estimation on this for velocity tracking purposes please?

**Comment by JayDarnell** [comment]
Sorry for the delay @cmaeng points added
