### ISSUE TITLE
Discovery: Sitewide CMS Collaboration Cycle Framework 

### ISSUE THREAD

**Issue by EWashb** [department-of-veterans-affairs/va.gov-cms#9151]
## Description

As the Sitewide CMS team evolves, we should look to establish a collaboration cycle process similar to the platform team for review and "pseudo approval" for the design system, CMS governance, and content modeling. 

The Platform's Collab Cycle [process and documentation](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/) can serve as an example to research and explore. The Platform Collab Cycle provides a series of touchpoints for VFS to receive guidance on things like design, content, info architect, and quality assurance (among other things). 

In order to sure up our content model and provide clarity to CMS teams, we should do the same. The Sitewide CMS team should determine what a collab cycle should look like for the Sitewide Crew. 

## Acceptance Criteria
- [x] Research Platform Teams collab cycle
- [x] Work with Sitewide CMS team to create mural with process ideas
- [x] Document findings 
- [x] PM shares info with PO

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Platform CMS Team`
- [ ] `Sitewide program`
- [x] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by msbtterswrth** [comment]
I started a [mural](https://app.mural.co/invitation/mural/vagov6717/1652978287230?sender=u0213d96dd8b8c144f1f10284&key=b82146c2-4f12-49e0-9492-cfecf6ae1ace) for us to start to gather our ideas in.

**Comment by EWashb** [comment]
Per conversations with Dave today- our framework should not only include an intake process for collecting requests from other teams/"customers" (such as the request for a content audit from the Sitewide Content team) but also the already noted review process for external teams (PW and facilities, etc.)

 Some context here in this [slack thread](https://dsva.slack.com/archives/CT4GZBM8F/p1653334103646839).

**Comment by EWashb** [comment]
Some ideas for request intake process:

- Github template
- Jira/helpdesk
- dedicated slack channel

However, we will need a documented process to share with both internal and external teams

-

**Comment by EWashb** [comment]
Next steps: will go over with Dave during our 1:1 on 6/7

**Comment by EWashb** [comment]
Next steps: create a RACI chart for Sitewide CMS review points, such as design and content model changes.

**Comment by EWashb** [comment]
Discovery has been completed but may overlap with current design/dev process. Will pivot to a Sitewide CMS RACI to start the framework of collaboration across sitewide crew teams.

**Comment by EWashb** [comment]
It has been determined with PO that we should start a collab cycle "lite" approach and the first step will be RASCI. This documentation will still help us figure out a path forward after touchpoints with our team are determined.
