### ISSUE TITLE
[cms-ci] Reinstall DevShop

### ISSUE THREAD

**Issue by ElijahLynn** [department-of-veterans-affairs/va.gov-cms#916]
Current instance is very slow for some reason (30+ second page loads), not obvious but likely SQL query optimization needed, which will take some time. Discussed with @jonpugh and it is faster to just run playbook to create a new instance.

**Comment by jonpugh** [comment]
The new instance has been up since this morning. 

Once I resolve composer dependency issues tests should run.

**Comment by jonpugh** [comment]
Something with the server must get overloaded because everything, even calls to `drush uli` take FOREVER.

**Comment by ElijahLynn** [comment]
Things we had to do manually, that need to be automated. 

1. Setup Hyrid Auth w/GitHub
    1. credstash the ID and SECRET
    2. changed “Or log in with GitHub by clicking the icon below ...”
    3. “who can create accounts” visitors can 
    4. “dont require email verification”
    5. “user name pattern” [user:hybridauth:displayName]
    6. library configuration - symlink 
    7. ~/devmaster-1.x/sites/all/libraries/hybridauth/hybridauth/Hybrid/Providers/GitHub.php -> ../../../additional-providers/hybridauth-github/Providers/GitHub.php
    8. assign admin roles to devops engineers
    9. redirect after login <front>
1. GitHub Integration setup (credstash, BRD)
    1. va.drush.inc file credstash
    1. credstash and vset the Drupal vars
1. Composer issue, require, process, symfony
    1. rm /usr/share/devshop/bin/composer symlink
1. SQL Import method - delete and recreate the mirror
1. skip site backup on destroy, turn off backups globally
    1. http://devshop.cms.va.gov/admin/hosting/backup_manager
    1. “backup sites by default”
1. Set “always” auto delete backups
    1. http://devshop.cms.va.gov/admin/hosting/settings
1. Uncheck debug logs on hosting settings page
    1. http://devshop.cms.va.gov/admin/hosting/settings
    1. debug
    1. debugnotify
1. Logo

**Comment by ElijahLynn** [comment]
This is done for now.
