### ISSUE TITLE
New CLP for Mission Act / VA Health Connect

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#9169]
## Description
CLP request file attached:
[Mission Act - 5.19.2022.docx.pdf](https://github.com/department-of-veterans-affairs/va.gov-cms/files/8744853/Mission.Act.-.5.19.2022.docx.pdf)

- Your name: Abby Harlow
- Your VA organization: Office of Integrated Veterans Care
- Your email address: Abigail.Harlow@VA.gov / Abigail.Harlow@nationalcoordinationcenter.com
- About Your Campaign Name or focus of Campaign: VA Health Connect
- Target audience(s) [up to 3]: [e.g., "Veterans, caregivers, VSOs"]: All Veterans enrolled in VA healthcare, Family Members and Caregivers
- Goals of the Campaign: [e.g. “To provide Veterans and their caretakers with important program information about the MISSION Act.”]:  Provide Veterans with a central location to access healthcare services through VA Health Connect
- Campaign start and end dates: This is an ongoing, nationwide VA program.
- Campaign page target launch date: Monday, June 13, 2022
- Preferred URL: [e.g. www.va.gov/mission-act Note: We will not support sub-domains, e.g. www.mission-act.va,gov ]:  www.va.gov/healthconnect
- How familiar are you -- or the person who will build the campaign page -- with the VA.gov Drupal content management system:  I do not have experience working within the Drupal platform, but I do have front-end web development experience on similar platforms. I have also reviewed the “Drupal CMS: Campaign Landing Page” YouTube video.
- Who will build the campaign landing page in the VA.gov CMS? Abby Harlow
- Who will review and give approval to publish the page?:  Richard (Rick) Fox – Richard.Fox2@va.gov
- Who will update/maintain the landing page during the campaign?: Abby Harlow
- At the end of your campaign, when the page is removed from VA.gov, where do you want to re-direct users? We will want to redirect users to an associated Resources & Support page.

## Steps
- [x] Dave Conlon approval to execute
- [ ] IA (@mnorthuis) approval of vanity URL path
- [ ] Create CLP from [CLP template node](https://prod.cms.va.gov/node/16512) 
- [ ] If a new editor is needed, Helpdesk or any Drupal admin can create them and assign proper permissions according to [CLP CMS account administration policy](https://prod.cms.va.gov/help/cms-account-admin-policies/clp-cms-account-administration-policy)
- new Drupal CMS admin. accounts for Abigail.Harlow@va.gov and Kaitlin.Easterday@va.gov if they don’t already exist. Note that both Abigail and Kaitlin should ONLY have access to edit/update the new CLP. They should not have access to any other VHA assets/pages.

- [ ] New editor training:  send new editors the [How to manage campaign landing pages](https://prod.cms.va.gov/help/campaign-landing-pages/how-to-manage-campaign-landing-pages) link to the self-service training while CC'ing the associated requestor. (VHA, VBA, NCA, VEO, etc)

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Platform CMS Team`
- [ ] `Sitewide program`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by jilladams** [comment]
Slack thread: https://dsva.slack.com/archives/CT4GZBM8F/p1649709432332419

**Comment by jilladams** [comment]
@mnorthuis new Campaign landing page request here to use [www.va.gov/healthconnect](http://www.va.gov/healthconnect) ongoing (not time limited).  Can you let me know if you have any concerns or if this URL is ok to proceed?  (Also: if we need a more formal process around this sort of ping, moving forward?

**Comment by jilladams** [comment]
@mnorthuis (and @davidconlon ) FYI that we've created this Campaign Landing Page at the proposed URL, in draft mode, to unblock editing and page creation. I'll wait to close this issue til we hear back re: /healthconnect is approved. If not, we can edit the URL path.

The editors have been created in the system as well. 
The page now exists as an unpublished draft, and we've asked Abigail to hold off on publishing until URL is approved.

FYI @stefaniefgray

**Comment by mnorthuis** [comment]
@jill can you add the draft page here for reference?

**Comment by jilladams** [comment]
Draft page: https://prod.cms.va.gov/healthconnect

**Comment by mnorthuis** [comment]
Recommending a slight tweak to the requested URLs to meet our URL formatting standards (adding dashes between words) and utilize the service branding ("VA Health Connect").

CLP canonical URL: [www.va.gov/initiatives/va-health-connect/](http://www.va.gov/initiatives/va-health-connect/)

Vanity URL: [www.va.gov/va-health-connect/](http://www.va.gov/va-health-connect/) (which redirects to the above URL)

**Comment by jilladams** [comment]
@mnorthuis we let Abigail know the final answer on the URLs, and she asked: Is there any way to remove the “va” part so it just reads, [www.va.gov/health-connect](http://www.va.gov/health-connect)?

You had noted we should use the service branding ("VA Health Connect"), which I can pass along -- is the logic that having that in the URL helps more clearly tie it to the service in things like SEO, etc?

**Comment by jilladams** [comment]
Adding Mikki to email thread with Abigail, in order to close loop while I'm out of office later this week.

**Comment by stefaniefgray** [comment]
Confirming that Drupal URL is https://prod.cms.va.gov/va-health-connect

**Comment by jilladams** [comment]
Point of clarity, per Mikki's note above: 
CLP canonical URL = should be set in Drupal (and is now) = [www.va.gov/initiatives/va-health-connect/](http://www.va.gov/initiatives/va-health-connect/)

Vanity URL = needs to be configured as a redirect & requires a follow up ticket = [www.va.gov/va-health-connect/](http://www.va.gov/va-health-connect/) (which redirects to the above URL)

Follow up ticket = https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9597
