### ISSUE TITLE
Test: Expand tests for Footer component

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-cms#9184]
## Description
The Footer component (`src/components/footer/index.tsx`) has some tests (see #8970), but they should probably be expanded to more thoroughly cover its functionality.

## Acceptance Criteria
- [ ] The `Footer` component has automated tests written per [guidelines](https://github.com/department-of-veterans-affairs/next-build/blob/main/READMEs/testing.md).

**Comment by TheBoatyMcBoatFace** [comment]
Is this still an issue @ndouglas? It looks like everything in #8970 is done but this
- #8970

**Comment by ndouglas** [comment]
@TheBoatyMcBoatFace This is fine to close 🙂
