### ISSUE TITLE
[tentative] Support an audit facility operating status for COVID content, and selective wiping if desired

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#9195]
## Description

TBD who should be involved in greenlighting this. 

## Acceptance Criteria
- [ ] 1350 Facility Operating Statuses have been audited for COVID content (by VHA DM)
- [ ] Decision has been made about whether to selectively wipe
- [ ] If yes, selectively wipe COVID content from Facility Operating Status fields, with support by a content engineer

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Platform CMS Team`
- [ ] `Sitewide program`
- [x] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by EWashb** [comment]
@dsinla seems like the work being done in #10842 makes this basically void. I propose we close this one since it is no longer within scope

**Comment by jilladams** [comment]
Closing re: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13681
