### ISSUE TITLE
Audit and document current CMS modules

### ISSUE THREAD

**Issue by EWashb** [department-of-veterans-affairs/va.gov-cms#9197]
## Background

As part of the design system, we need to map out what modules are currently being used in our system to enhance the mental model for the team.

## Acceptance Criteria

Documentation on: 
- [x] What Drupal modules are currently being used in the CMS
- [x] A link to Drupal description
- [x] Description of the module 
- [x] Notation of if it is custom to our system
- [x] Column for module category
- [x] Additional notes that technical and non-technical people should know

**Comment by msbtterswrth** [comment]
Audit of the currently installed modules can be found in [this airtable](https://airtable.com/shrJqCvs5jdJUfDwt).

**Comment by msbtterswrth** [comment]
@EWashb not sure who needs to review this, but I think we're good to review!

**Comment by EWashb** [comment]
@msbtterswrth did you want to add a column for if it was a UX-centric module? I added that AC during our discussion yesterday.

**Comment by msbtterswrth** [comment]
@EWashb i did! i just forgot to add an AC for that :) 

https://snipboard.io/pBtvLq.jpg

**Comment by EWashb** [comment]
New ticket created for next steps: #9285
