### ISSUE TITLE
Document VA design system components to the CMS content model

### ISSUE THREAD

**Issue by EWashb** [department-of-veterans-affairs/va.gov-cms#9201]
## Background

Across the VA ecosystem, there is a need for both internal and external teams to understand the CMS content model related to the front-end VA design system. The Sitewide CMS often receives questions from ecosystem customers that require explaining the decoupled content model. 

See this [slack thread](https://dsva.slack.com/archives/CT4GZBM8F/p1653319471617409) for one example and context. 

## Assumption 
A documented content model as it relates to the VA design system could help alleviate the need to educate teams across the ecosystem on the why and how of CMS current state. 

## Acceptance Criteria 

- [x] An airtable that maps the content model to the VA Design System
- [x] Review with Sitewide CMS product manager
- [x] Set up meeting with Katie/VADS to review

## Possible Next Steps

Determine if the content model documentation can be added to the VA design system

**Comment by msbtterswrth** [comment]
Airtable created with all the VADS components [here](https://airtable.com/appSg80z9nVWoesxn/tblgf7VtGeCcEISYk/viwvT1LiPTljvjk4Q?blocks=bipz2F2iCJ6xlOlNM). 

This is just a first iteration of this documentation. We suspect it may make more sense to house this information in the VADS itself, to reduce duplicative content.
