### ISSUE TITLE
Behavioral Tests ensuring all node/add pages open and finish loading in a reasonable amount of time.

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-cms#9202]
## Description
We've recently had a fairly high-profile issue where two node/add forms were aggravating editors by being unusually slow; spinning for upward of 50+ seconds.  See #9115 

We should add test coverage to ensure that page loads complete within a reasonable amount of time.

## Acceptance Criteria
- [ ] All node/add forms have test coverage ensuring that they complete loading in ~15 seconds.
  - [ ] Failures can be marked as "allowed to fail"
- [ ] Followup issues are opened as needed to address performance issues on specific forms.

**Comment by ElijahLynn** [comment]
For future: Blackfire tests would be good for this, then we get a profile link on failure to figure out what the issue is to fix it.

**Comment by ndouglas** [comment]
I think this is actually implicitly covered by #9921.  I've added all of the node/add forms there, and the accessibility testing implies checking timeouts here, so there's no real need to open each of those pages again.  Closing in favor of #9921. 

@dawnpruitt @EWashb
