### ISSUE TITLE
Engage Collab cycle process for IE11 warning

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#9210]
## Description
#9075 requires collab cycle. Need to:
* propose design component / placement
* request content from Sitewide Content

## Acceptance Criteria
- [x] SiteWide Content ticket
- [x] Collab cycle ticket

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Platform CMS Team`
- [ ] `Sitewide program`
- [ ] `⭐️ Sitewide CMS`
- [X] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by jcklpe** [comment]
Copying over my comments from Zoom:

> "putting it between the nav and the content on the page probably seems like the best approach.
> but that's just off the top of my head.
> 
> the alert component does seem like the right component to use IMO. 
> 
> my reason for saying below nav, before content, is just so that the nav bar, alert, and content, can collapse responsively in a simple way. Putting the component in the nav might be complicated on mobile. Putting the alert before the nav could also work but I don't think the difference is going to be that huge, as long as there's clear segmentation for the mobile view."

**Comment by jcklpe** [comment]
Writing out some notes on this:

Storybook link for Alert component can be found here: 
https://design.va.gov/storybook/?path=/docs/components-va-alert--default

Judging by the existing props, I think some relevant non-default values are going to be:

```
status: warning
closeable: true
full-width: true
```

Questions we need answered: by what time do they need to switch to using IE11? Is there a firm cut off date? 

Here's a quick preview of the alert that I mocked up in the browser:
![image](https://user-images.githubusercontent.com/9451726/170101236-468926c2-cd47-471f-aa06-a36cefbd0c2f.png)

And here's a quick mockup of it how it would look on the homepage:
![image](https://user-images.githubusercontent.com/9451726/170102337-30c6a2f7-0c0f-4422-8916-5da7107ec8f9.png)


Copy is just a placeholder.

**Comment by wesrowe** [comment]
@jcklpe, a couple quick thoughts/responses:
- there's no deadline to switch, my understanding is the message is "do this now"
- do you feel pretty confident the banner will go full window width? as opposed to the width of the header...
- can you add a microsoft browser to your list? Edge

**Comment by wesrowe** [comment]
I just engaged the Collab Cycle using this kickoff ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/41829.

**Comment by jcklpe** [comment]
@wesrowe : Good call on adding Edge. 

Personally I like full width. I'm actually a little surprised the nav header isn't full width but I think it is okay if they aren't both the same width.

**Comment by wesrowe** [comment]
Collab cycle recommended touchpoints for ie11 don't include Design Intent. They are:

- [Sitewide Content and IA intake request](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Sitewide-Content-and-IA-intake-request.2124906551.html)
- [Staging review](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Staging-review.1810137181.html)
- [Privacy, security, infrastructure readiness review](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Privacy-and-security-review.1782317101.html)
