### ISSUE TITLE
Redirect Request for Vet Centers live as of 5/17/22

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-cms#9218]
### Type of request
- [x] We are retiring or taking down a page and need to redirect the URL (complete redirect section)
- [ ] We are changing the URL of an existing page (complete redirect section)
- [ ] We need a custom vanity URL (complete vanity URL section)

### Implementation date
When does this request need to be live: 

No specific date - at your earliest convenience

### Redirects 
Current URL  |  New URL
---  |  ---
| https://www.va.gov/find-locations/facility/vc_0829MVC | https://www.va.gov/billings-vet-center/ | 
| www.va.gov/find-locations/facility/vc_0509V | https://www.va.gov/billings-vet-center/ |
| www.va.gov/find-locations/facility/vc_0708V | https://www.va.gov/fort-worth-vet-center/ |
| www.va.gov/find-locations/facility/vc_0133V | https://www.va.gov/harlem-vet-center/ |
| www.va.gov/find-locations/facility/vc_0879MVC | https://www.va.gov/mcallen-vet-center/ |
| www.va.gov/find-locations/facility/vc_0715V | https://www.va.gov/mcallen-vet-center/ |
| www.va.gov/find-locations/facility/vc_0731V | https://www.va.gov/spring-vet-center/ |

#### Blocked
These URLs will **not** be implemented within scope of this ticket. They are now documented in https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9640, which will track resolution.
Current URL  |  Redirect Destination or New URL
---  |  ---
| https://www.va.gov/directory/guide/facility.asp?ID=618&dnum=1 | https://www.va.gov/billings-vet-center/ |
| https://www.va.gov/directory/guide/keystaff.cfm?id=618 | https://www.va.gov/billings-vet-center/ |
| https://www.va.gov/directory/guide/facility.asp?ID=5462&dnum=1 | https://www.va.gov/fort-worth-vet-center/ |
| https://www.va.gov/directory/guide/keystaff.cfm?id=5462 | https://www.va.gov/fort-worth-vet-center/ |
| https://www.va.gov/directory/guide/facility.asp?ID=5487&dnum=All | https://www.va.gov/harlem-vet-center/ |
| https://www.va.gov/directory/guide/keystaff.cfm?id=5487 | https://www.va.gov/harlem-vet-center/ |
| https://www.va.gov/directory/guide/facility.asp?ID=5464&dnum=1 | https://www.va.gov/mcallen-vet-center/ |
| https://www.va.gov/directory/guide/keystaff.cfm?id=5464 | https://www.va.gov/mcallen-vet-center/ |
| https://www.va.gov/directory/guide/facility.asp?ID=5940&dnum=1 | https://www.va.gov/spring-vet-center/ |
| https://www.va.gov/directory/guide/keystaff.cfm?id=5940 | https://www.va.gov/spring-vet-center/ |

**Link to campaign landing page request issue:**

## CONTEXT
SPIKE: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9175
There are 4 URL patterns being handled here, and each is treated slightly differently in redirects.yml:

1. directory/guide/facility.asp?ID=XXX - already redirect to https://www.va.gov/find-locations/?facilityType=vet_center via a redirect managed by the Facilities & Leadership directory.
2. directory/guide/keystaff.cfm?id=XXX -- do not redirect already, and point to legacy pages
3. find-locations/facility/vc_XXXXMVC -- redirect to specific vet center pages, but without resolving to the correct modernized URL
4. find-locations/facility/vc_XXXXV -- redirect to specific vet center pages, but without resolving to the correct modernized URL

The code contains comments that point to other similar requests that were performed by the old Public Websites team. Use those previous changes for context on how to handle the various URL patterns, e.g. 
* ticket - https://github.com/department-of-veterans-affairs/va.gov-team/issues/38716
* PR - https://github.com/department-of-veterans-affairs/devops/pull/10988 

## Acceptance Criteria

- [ ] After deploy, check original URLs on production to confirm that each properly redirects and resolves to the requested URL before closing ticket

### Process, Roles and Responsibilities
- [ ] Requesting team: Above information is provided
- [ ] Requesting team: All appropriate VA stakeholders are notified as appropriate
- [x] IA: Request is vetted and documented and implementation plan is clear 
- [x] IA: Request is assigned to appropriate team for implementation 
- [ ] Implementation team: Work is complete
- [ ] Implementation team: Validated in production
- [ ] Requesting team: Validates everything is correct in production and closes ticket

**Comment by wesrowe** [comment]
@jilladams I just came across this in the backlog, can we close?

**Comment by jilladams** [comment]
No - this is blocked by our SPIKE in #9175

**Comment by jilladams** [comment]
@mnorthuis progress reporting in https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9175 for how these work. There's another team involved, and they're working on update to let us know how these work / how to overwrite them.

**Comment by mnorthuis** [comment]
@jilladams I thought we determined that the work in #9715 did not need to block this redirect request?  Or did you determine differently?

**Comment by jilladams** [comment]
Apologies - at the time we thought this wasn't blocked, we assumed we knew
all the locations where redirects are controlled. We were wrong about that,
and because these redirects originate from somewhere within the Facilities
& Leadership Directory, we do want to understand that. If we don't hear
back from Kevin Reid by mid-week, we'll revisit.

**Comment by jilladams** [comment]
Can be implemented at the same time as https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9515

**Comment by allisonlu** [comment]
PR opened on `devops` repo: https://github.com/department-of-veterans-affairs/devops/pull/11528

**Comment by allisonlu** [comment]
PR merged to `master`! I'll have to confirm the redirects are in place once this gets deployed today.

**Comment by allisonlu** [comment]
All redirects are happening on prod!
