### ISSUE TITLE
Content audit: Mentions of Direct Upload and its url on VA.gov pages

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-cms#9219]
## Describe the request
Content audits are performed by searching the codebase and compiled site for specific terms. 
Please provide any context for the audit, and any related terms / alternate spellings, that could return content you are interested in.

* Context: QuickSubmit is launching and will replace the use of Direct Upload on 6/30/22. In order for Sitewide Content to update our pages, we need to know all the places where Direct Upload is currently mentioned as well as the url it's currently linking to: https://eauth.va.gov/accessva/?cspSelectFor=dmhs 

We already know it appears on these pages:
- https://www.va.gov/disability/upload-supporting-evidence/
- https://www.va.gov/pension/survivors-pension/
- https://www.va.gov/burials-memorials/memorial-items/headstones-markers-medallions/
- https://www.va.gov/burials-memorials/eligibility/burial-in-private-cemetery/

* Terms of interest: Direct Upload, https://eauth.va.gov/accessva/?cspSelectFor=dmhs 
* Alternate spellings / terms: direct upload
* Any Content types to specifically include or exclude? We need benefit pages (detail pages and hub landing pages), resources and support, root level pages. You can exclude all VAMC

### Implementation date
When does this request need to be complete?: 6/14 (we need to go live with the changes by 6/30)

Please submit all engineering requests **at least 1 full sprint in advance** (so we can work it into our next sprint).

## CMS Team
Please check the team(s) that will do this work.

- [ ] `Platform CMS Team`
- [ ] `Sitewide program`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by wesrowe** [comment]
@ethanteague, you mentioned in slack that "All instances of https://eauth.va.gov/accessva/?cspSelectFor=dmhs appear to be coming from cms. It's not anywhere to be found in content-build or vets-website." Could you say how you determined that – was it a search of those two repos?

**Comment by ethanteague** [comment]
> @ethanteague, you mentioned in slack that "All instances of https://eauth.va.gov/accessva/?cspSelectFor=dmhs appear to be coming from cms. It's not anywhere to be found in content-build or vets-website." Could you say how you determined that – was it a search of those two repos?

That's right, @wesrowe. I did an all files search for the url string in both of my local repos using VsCode.

**Comment by jilladams** [comment]
1 point

**Comment by jilladams** [comment]
Meeting scheduled with Tanner on Mon 6/6 to confirm my local setup to grep for results.

**Comment by jilladams** [comment]
@RLHecht  I searched for the phrase "direct upload" and the eauth URL: 
`grep -Rli "Direct Upload" build/localhost > directupload.txt`
`grep -Rli "https://eauth.va.gov/accessva/?cspSelectFor=dmhs" build/localhost > ~/Downloads/directupload2.txt`

And that returned this set of pages:
```/pension/survivors-pension/index.html
/burials-memorials/eligibility/burial-in-private-cemetery/index.html
/burials-memorials/memorial-items/presidential-memorial-certificates/index.html
/burials-memorials/memorial-items/headstones-markers-medallions/index.html
/disability/dependency-indemnity-compensation/index.html
/disability/upload-supporting-evidence/index.html
```
The only new path besides the ones you mentioned already are these: 
```
/burials-memorials/memorial-items/presidential-memorial-certificates/index.html
/disability/dependency-indemnity-compensation/index.html
```

I sanity checked against a Google search, and I do see several additional VBA forms that include the URL in the form itself via google (e.g. https://www.vba.va.gov/pubs/forms/vba-21-22a-are.pdf). Our audit can't check for contents of files, as far as I know - if those forms are concerns here, let us know and I can see if there is any way to check file contents.

I'll let you close this ticket if you're satisfied here. Thanks!

**Comment by RLHecht** [comment]
Thanks so much @jilladams We don't need to make updates to forms pages but I can let the stakeholders who asked us to make updates to our pages that there are other mentions of this out there. I can close this ticket.
