### ISSUE TITLE
New Facility: Northern Colorado VA Clinic

### ISSUE THREAD

**Issue by stefaniefgray** [department-of-veterans-affairs/va.gov-cms#9229]
## Background

*What triggered this runbook?*
Reported by Brandy Sims @ VISN 19 in VAHELP-4189

## Acceptance criteria
Northern Colorado VA Clinic in Loveland, CO is added to live site

Proof that it has been added to VAST: https://www.va.gov/find-locations/facility/vha_442GE
VAST ID: vha_442GE
Parent system: VA Cheyenne ( https://www.va.gov/cheyenne-health-care/locations/cheyenne-va-medical-center/ )

Address:
4575 Byrd Drive
Loveland, CO 80538

### VAMC

CMS help desk steps
- [x] 1. Become aware that the new facility is now on the Facility API (typically, via a Flag).
- [x] 2. Check with VHA digital media what section and VAMC it belongs to. [@todo write sample email.]
- [x] 3. Updates the Section (default is "VAMC facilities", but it should be a VAMC system in a VISN) and VAMC system field accordingly.
- [x] 4. Communicate with editor (cc VHA Digital Media) to give them go-ahead to complete the content, with this [KB article](https://prod.cms.va.gov/help/vamc/about-locations-content-for-vamcs/how-do-i-add-a-facility-to-my-health-care-system). [@todo write sample email.]
- [x] 5. When editor has prepared content and let help desk know, reassign this issue to appropriate CMS engineer on Product Support team, for bulk publishing.

CMS engineer
- [x] 6. CMS engineer bulk publishes nodes and facility.
- [x] 7. CMS engineer edit facility node and remove `New facility` flag and save node.
- [x] 8. Let help desk know this has been done.

CMS Help desk
- [x] 9. HD notifies editor and any other stakeholders.

## CMS Team
Please check the team(s) that will do this work.

- [ ] `Platform CMS Team`
- [ ] `Sitewide program`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [x] `⭐️ User support`

**Comment by stefaniefgray** [comment]
Waiting on editors to write back that new facility steps are complete

**Comment by stefaniefgray** [comment]
Editor went ahead and published the facility: https://va-gov.atlassian.net/browse/VAHELP-4189

Am unsure how to proceed given that the new facility runbook states that the editor must submit this page back to our team as a draft; waiting on engineering team for next steps. Leaving page as-is for now. 

No VAMC facility health services added at this time, but have advised editor to add them: https://prod.cms.va.gov/cheyenne-health-care/locations/northern-colorado-va-clinic

**Comment by stefaniefgray** [comment]
Assigning to @JayDarnell for review, and also because he knows Northern Colorado pretty well :)

**Comment by TroyA6** [comment]
Site Confirmed - verified; Done
