### ISSUE TITLE
Content guidance discovery: alt text

### ISSUE THREAD

**Issue by rachel-kauff** [department-of-veterans-affairs/va.gov-cms#9237]
## Background
Before we can figure out the best way to help editors follow content guidance and increase content quality, we need to do some discovery to set a baseline for content quality. 

### Identify improvement goals
For example standards we want to focus on might be:
- Avoid "image of..." type prefaces
- Text should focus on the information/ meaning / content of the image 
- Succinct (I cannot discern an enforced character limit for these in our system already, but ideally they wouldn't be more than 125 characters or so.)

Other things to consider
- Figure out if decorative images are even a thing

### Audit for content quality
- Quantitative: # of form validation errors?
- Qualitative: audit randomized sample of images in the media library and rate quality based on x factors.

## Processes and governance
Governance
- Document how inline content guidance content will treat source of truth guidelines. For example, how will we ensure that content style guidance remains the canonical source? When to point to style guide vs. KB.
- Who approves new usages of inline guidance?
- When to use / not use inline guidance?

ACs
- [x] Alt text quality goals identified
- [x] Audit performed on a randomized sample of 300 media library items based on identified goals
- [x] Biggest opportunity areas identified to inform inline guidance effort.

**Comment by EWashb** [comment]
Possible solution includes some part of this Drupal module. We may be able to use some of this functionality https://www.drupal.org/project/better_field_descriptions

**Comment by rachel-kauff** [comment]
@EWashb I updated this issue based on what we discussed. I think this is probably ready for me to start running with.

**Comment by EWashb** [comment]
Feel free to run (or even frolic)!

**Comment by rachel-kauff** [comment]
WIP docs:
- [Audit notes](https://docs.google.com/document/d/13QcZN2p0SSeIdHsdjTSO-4iYILcejslHY2iJfbA12_Y/edit)
- [Airtable audit](https://airtable.com/appYsyEZFDJmwbGjP/tblJuFKENYIIDMiPQ/viw7GRiR0ynspxqq7?blocks=hide)

**Comment by rachel-kauff** [comment]
Content discovery for inline content guidance ([#9237](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9237))
[Loom demo / overview](https://www.loom.com/share/6ac78965d12441189192e23acac2ade0)

[Findings deck - google slides (use for commenting)](https://docs.google.com/presentation/d/1wuJiR-RKajiis8TV72-3vtDtfj0topXYHZ93YYbAXJo/edit#slide=id.gcd567e2ae4_0_432)

[Findings deck - Github repo ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/research/inline-guidance/alt-text-quality-audit/Alt%20text%20audit%20for%20inline%20content%20guidance%20discovery-findings.pdf)

[Audit data in Airtable](https://airtable.com/invite/l?inviteId=invKuUJOJMy5hB4l2&inviteToken=2148e3e97b4de643f600521032c2fb5baf14491102e382e35bf50acda7a483aa&utm_medium=email&utm_source=product_team&utm_content=transactional-alerts)

[Audit data as CSV - Github repo](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/research/inline-guidance/alt-text-quality-audit/alt-text-quality-audit-jun-2022.csv)

**Comment by mgifford** [comment]
I hadn't actually heard of https://www.drupal.org/project/better_field_descriptions but something like this could definitely help to guide authors. Mind you, it would only work for images which are added using the image field, if you are using CKEditor it wouldn't be visible.

There is a great example here https://accessibilitycluster.com/main-results/text-alternative-feature-%E2%80%93-presentation of how authors can be better supported. Two Drupal issues related to this:
- https://www.drupal.org/project/drupal/issues/3171916
- https://www.drupal.org/project/drupal/issues/3171918

Some other related resources on writing alt text:
- https://webaim.org/techniques/alttext/
- https://www.sc.edu/about/offices_and_divisions/digital-accessibility/guides_tutorials/alternative_text/step-by-step-instructions-alt-text/index.php
- https://accessibility.huit.harvard.edu/describe-content-images
- https://www.w3.org/WAI/tutorials/images/decision-tree/

**Comment by mgifford** [comment]
Updating broken link to https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/research/inline-guidance/alt-text-quality-audit/Alt%20text%20audit%20for%20inline%20content%20guidance%20discovery.pdf
