### ISSUE TITLE
Document Mapbox token storage and environment approach

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#9238]
## Description

As an engineer who may have to change, add and/or work with Mapbox tokens I would like to have documentation so I know what to do.

The process that needs to be documented ultimately boils down to two steps:
1. Storing the Mapbox tokens in AWS Parameter Store. [This document](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1474595172/Store+a+secret+in+Parameter+Store) will be a good link.
2. Retrieving the tokens from AWS Parameter Store for use in the application.

## Acceptance Criteria
- [x] Identifies the security approach (why is this safe)
- [x] Describes the token pair (one private with no url restriction, one public with url restrictions) approach
- [x] Points to where in the code this is handled
- [x] Calls anything else that needs to come into play

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Platform CMS Team`
- [ ] `Sitewide program`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by ryguyk** [comment]
Documentation [here](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/facilities/mapbox/).
