### ISSUE TITLE
Determine site alert positioning 

### ISSUE THREAD

**Issue by EWashb** [department-of-veterans-affairs/va.gov-cms#9240]
## Background

As a spin-off of #8299, a dismissable site alert's design and technical aspects require more investigation related to the design and technical interactions with the existing toolbar. Because the existing site alert sits outside of the content container and will alter the behavior of other containers on the page.

Figma files:

1.[ Site alert component](https://www.figma.com/file/ScABI31f3MRFEvQ8WitVPa/CMS-Design-System) in the system feedback section of the CMS design system
2. [Initial drafts](https://www.figma.com/file/0vQ3KtDeQZBlQulxZFPRj3/Site-alert-component) of the site alert component

## Acceptance Criteria

- [x] Designers create site alert options 
- [ ] Designers review with dev for technical feasibility
- [ ] Dev implementation
- [ ] Storybook integration

**Comment by EWashb** [comment]
This is on hold in favor of #3119- the implementation of Sitwide Alert module

**Comment by tjheffner** [comment]
This can probably be closed with the new sitewide alert module. it places alerts higher on the page and takes the toolbar into consideration (alerts print below)

**Comment by EWashb** [comment]
Agreed @tjheffner
