### ISSUE TITLE
Document new Cerner API for other product teams to consume

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#9248]
## Description

Once we have validated our new Cerner facility API in production, we will need to create developer-facing documentation about what it is, how to use it, how it's triggered, who can trigger it etc. The audience for this documentation will be engineers on other app teams who will need to switch their code over to the new asynchronous API as we deprecate the old hard-coded/synchronous API.

We'll want to work with **Leah Bannon** (OCTO-DE on health portfolio) to find the right home for this stuff.

### Possibly outdated documentation to remove/replace (partial list):

- [This page](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/public-websites/Cerner-Support/how_to_set_up_vamc_cerner_within_va_health_care_portals.md)
- The Kelson runbook, if it's different from above

## Acceptance Criteria
- [ ] Documentation created and available at location approved by Leah
- [ ] QA: run documentation by another team to see if it makes sense to them and provides the right level of detail (suggest someone on Profile/My VA)

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Platform CMS Team`
- [ ] `Sitewide program`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by ryguyk** [comment]
Blocker: need to know where to document this. My feeling is to add/edit [this page](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/public-websites/Cerner-Support/how_to_set_up_vamc_cerner_within_va_health_care_portals.md) as suggested in the ticket.

**Comment by jilladams** [comment]
That seems reasonable, as long as the updates won't contain anything that should be considered Sensitive, and should go in the [Cerner sensitive runbook](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/teams/vsa/teams/public-websites/cerner.md) instead.

**Comment by jilladams** [comment]
Added a pointer in the new file to the old runbook. Closing!

**Comment by jilladams** [comment]
Re: hosting this long-term for other teams to consume: https://vfs.atlassian.net/wiki/spaces/AP/pages/1474461889/Create+a+new+Platform+website+documentation+page. We need to follow that documentation. Looking into that.
