### ISSUE TITLE
Component: paginated listings

### ISSUE THREAD

**Issue by jkalexander7** [department-of-veterans-affairs/va.gov-cms#9254]
## Description

Story_listing pages present a model we need to account for: listings of items which are paginated. We need to consider strategies for implementing these in next-build

For the current situation: 
* See for example, bottom of page: https://www.va.gov/northern-california-health-care/stories/
* Example template: https://github.com/department-of-veterans-affairs/content-build/blob/main/src/site/layouts/story_listing.drupal.liquid
* Pagination template: https://github.com/department-of-veterans-affairs/content-build/blob/main/src/site/includes/pagination.drupal.liquid
* Pagination 'filter': https://github.com/department-of-veterans-affairs/content-build/blob/main/src/site/filters/liquid.js#L926

We should consider approaches for handling this data in next-build. In a public API world, we would pass a page argument to the API request for the content collection. Possible approaches:
* generate a static page per 'page' of the listing (this is what content-build does)
* generate a listing page with all items attached as JSON, and paginate within a single static page (more like what we'd like to see, but potentially problematic for large listings

![Screen Shot 2022-05-19 at 12 30 56 PM](https://user-images.githubusercontent.com/3916436/169387929-d7f36b9f-f611-40df-8088-6df895333969.png)

## Acceptance Criteria

- [ ] Pagination is implemented using the approach determined in https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9120
- [ ] Appropriate tests are written for pagination

### CMS Team
Please check the team(s) that will do this work.

- [x] `Platform CMS Team`
- [ ] `Sitewide program`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by amponce** [comment]
Acceptance criteria has been met for the pagination task. Additionally, I attempted to take things a step further and implement pagination on a slug path which ended up highlighting some routing issues that need to be investigated in a spike. We decided that a new routing specific issue needs to be open in place of trying to solve the problem during this sprint.
