### ISSUE TITLE
New KB article: TeamSite Legacy Files/Who to Contact

### ISSUE THREAD

**Issue by stefaniefgray** [department-of-veterans-affairs/va.gov-cms#9258]
## Background context
**Topic**
Every few weeks or so, the VA Drupal CMS Helpdesk receives requests pertaining to the former VA.gov CMS, TeamSite.

The legacy files are stored on SharePoint and access must be requested through the VA Drupal CMS Helpdesk.

As for current TeamSite files/matters -- these issues must be directed to VAWebCMSSupport@va.gov

Jira tickets of this nature have the label `wrong-cms`

**Person requesting the article:** 
- Stefanie Gray requesting self to write it, based on 5/11/2022 VHA Digital Media check-in meeting 

Agenda: https://docs.google.com/document/d/1JdeiEpk1nXRppbQrdDaO5KY-2h6TRbkAM58LX4Gk6n4/edit

**Associated SMEs/ stakeholders:** 
- VHA Digital Media
- VA.gov VAMC editors

**Audience:** 
- VA.gov VAMC editors

**Related KB articles:** 
- None found

  
**Associated source of truth documentation:** 
- N/A

**This article addresses:**
- [ ] A business-driven need
- [x] A user-driven need

**Does this article have a deadline?**
- [ ] Yes: [name the deadline here]
- [x] No

**Is the article associated with change management initiatives?**
- [x] Yes, I think?
- [ ] No

**What parts of the interface will link to the article, if any?** 
- Link not needed

## Process
1. Refine and prioritize
2. Identify content needs
3. Draft article content 
4. Get peer review and/or stakeholder review (if necessary)
5. Publish

## ACs
- [ ] Article is reviewed by [assigned peer reviewer] and/or [SME/stakeholder]
- [ ] Article follows documented content style for the knowledge base
- [ ] Article is assigned to a parent 
- [ ] Impacts on other KB articles have been considered and any necessary changes have been made
- [ ] Help desk has been made aware of the new article
- [ ] (If appropriate) once published, the person requesting the article has been notified

**Comment by rachel-kauff** [comment]
Stellar ticket! Thanks for test driving the new KB article template. If you want to go ahead and draft an article @stefaniefgray I'd be happy to review and refine where it goes in the IA (such as it is). 
Some resources:
- [KB content style](https://va-gov.atlassian.net/wiki/spaces/VAGOV/pages/1771831299/Knowledge+Base+content+style) (not complete by any means, but there's some good stuff in there)
- I want to call out this point:
> Create a new content block for every H2 in your article. This helps create better spacing between content items, and also makes it easier to add other content block types, such as screenshots.

- It's definitely awkward, but it's what we're working with for now, and makes articles so much easier to read. 
Let me know if you need anything else to get started!

**Comment by stefaniefgray** [comment]
Closing because TeamSite migration happened long ago and we receive very few tickets about this subject -- it does not need a separate KB article
