### ISSUE TITLE
Improve KB article(s) on VAMC banner alerts

### ISSUE THREAD

**Issue by suzanne-gray** [department-of-veterans-affairs/va.gov-cms#9291]
## Description
As a Veteran, I want to quickly understand alerts about my VAMC so that I can make decisions about my care. 

As a VAMC editor, I want to know how to create an effective alert so that I can communicate effectively with Veterans. 

### Background
As part of the ongoing effort to improve the way VAMCs use banner alerts, Steve from VHA DM has drafted a [KB article about banner alert best practices](https://www.google.com/url?q=https://prod.cms.va.gov/help/vamc/about-locations-content-for-vamcs/about-alerts-and-operating-statuses/best-practices-for-vamc-system-banner-alerts&sa=D&source=calendar&ust=1654616483491054&usg=AOvVaw0gclHRn8-X6AM-_TqJCPCI). 

This content advice needs to be edited to conform to the CMS KB style. It also may be more effective if combined into the main [banner alert how-to article](https://prod.cms.va.gov/help/vamc/about-locations-content-for-vamcs/about-alerts-and-operating-statuses/how-to-add-a-system-banner-alert).  

## Acceptance Criteria
- [ ] Banner alert style guidance has been edited to conform to KB style. 
- [ ] Banner alert article has either been published or added to the main how-to article 
- [ ] Article reviewed by Sitewide CMS
- [ ] Article reviewed by Helpdesk
- [ ] Article published to KB

**Comment by jilladams** [comment]
@omahane @davidmpickett this may be close-able after our recent efforts?

**Comment by xiongjaneg** [comment]
closing due to subsequent updates of the content type
