### ISSUE TITLE
New Facility: Butte VA Clinic

### ISSUE THREAD

**Issue by stefaniefgray** [department-of-veterans-affairs/va.gov-cms#9301]
## Background

*What triggered this runbook?*
Helpdesk ticket https://va-gov.atlassian.net/browse/VAHELP-4305

Please see https://www.va.gov/find-locations/facility/vha_436GO from the Facility Locator

https://prod.cms.va.gov/montana-health-care/locations/butte-va-clinic

### VAMC
Please refer to the Knowledge Base article titled "How do I add a facility to my health care system?" for more information: https://prod.cms.va.gov/help/vamc/about-locations-content-for-vamcs/how-do-i-add-a-facility-to-my-health-care-system

#### CMS help desk steps
- [x] 1. Become aware that the new facility is now on the Facility API (typically, via a Flag, but this may come in as a helpdesk ticket).
- [x] 2. If the editor has followed the steps from the above Knowledge Base article and included which section and VAMC the facility belongs to (i.e. VA Pittsburgh), great! Proceed to step 3. If not, please check with the editor or VHA digital media regarding what section and VAMC it belongs to.
- [x] 3. Updates the Section (default is "VAMC facilities", but it should be a VAMC system in a VISN) and VAMC system field accordingly.
- [x] 4. Communicate with editor (cc VHA Digital Media) to give them go-ahead to complete the content, with this [KB article](https://prod.cms.va.gov/help/vamc/about-locations-content-for-vamcs/how-do-i-add-a-facility-to-my-health-care-system).
- [ ] 5. When editor has prepared content and let help desk know, reassign this issue to appropriate CMS engineer on Product Support team, for bulk publishing.

    #### Sample notification email:
    Hello! You should now both be able to edit the currently un-published draft page for this facility, located at https://prod.cms.va.gov/montana-health-care/locations/butte-va-clinic

    Important: Please make sure that all relevant steps listed within the “How do I add a facility to my health care system?” Knowledge Base article have been completed. Once finished, please save this page as a “Draft”, and do not save it as “Published”: https://prod.cms.va.gov/help/vamc/about-locations-content-for-vamcs/how-do-i-add-a-facility-to-my-health-care-system

    Please let us know once your draft is complete, so that we can wrap up the technical process from our end and ensure that the new facility publishes to the live site as intended. Thanks!

#### CMS engineer
- [ ] 6. CMS engineer bulk publishes nodes and facility.
- [ ] 7. CMS engineer edit facility node and remove `New facility` flag and save node.
- [ ] 8. Let help desk know this has been done.

#### CMS Help desk
- [ ] 9. HD notifies editor and any other stakeholders.

## CMS Team
Please check the team(s) that will do this work.

- [ ] `Platform CMS Team`
- [ ] `Sitewide program`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [x] `⭐️ User support`

**Comment by stefaniefgray** [comment]
@JayDarnell @christianmburk Editor went ahead and published everything regardless -- does this look good to go, and do you think we can close this ticket? Thank you!

**Comment by stefaniefgray** [comment]
Followed up in https://va-gov.atlassian.net/browse/VAHELP-4305 

Ticket can likely be closed but just triple-checking with Editors from VISN 19

**Comment by JayDarnell** [comment]
I was checking into this yesterday @stefaniefgray and got sidetracked. I removed the "New Facility" flag and resaved the facility.
