### ISSUE TITLE
Remove "Hard-coded API" from codebase

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#9307]
**STATUS 7/31: PR is prepared, VAOS still has code dependency**

## Description

Once all teams' apps/widgets have moved to Drupal as source of truth for Cerner cutovers, remove the hard-coded "API" and any associated dead code.

## Acceptance Criteria
- [x] No code left over from hard-code/synchronous method
- [x] References to removed code are mitigated
- [x] QA steps include:
  - [x] Test all 5 Cerner-related widgets
- [x]  Unit tests passing
- [x]  Build completes

### CMS Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [x] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`

**Comment by apisandipas** [comment]
Status Update 12/29 - This issue has a PR up but is currently block by required review by @ryguyk

**Comment by wesrowe** [comment]
@apisandipas, I notice this one needs points. Also, is it the one that's blocked by dependent teams? I suggest labeling "blocked" if that's the case.

**Comment by jilladams** [comment]
With @ryguyk and @apisandipas we identified 2 teams with work required to complete before this old method can be completely removed: 
1. VAOS - https://dsva.slack.com/archives/CMNQT72LX/p1673026289887489
2. Personalization - https://dsva.slack.com/archives/C52CL1PKQ/p1672939719325459
  * Work completed via https://github.com/department-of-veterans-affairs/va.gov-team/issues/51517#issuecomment-1380684589

This ticket is in PR and blocked from merging until VAOS work is complete.

**Comment by jilladams** [comment]
Made changes to incorrect ticket - this should be open, in Review/QA, blocked by 51630.

**Comment by jilladams** [comment]
Updated notes: https://github.com/department-of-veterans-affairs/vets-website/pull/23036#issuecomment-1448615887

The review here is tricky because not every code reference is as straightforward as `isCerner`. The old data was referenced throughout the codebase in various functions. Some of those functions are further referenced, so we have to: remove the old data, update functions that need updated or remove them, and ensure that all mentions of _all_ of that are _also_ updated. 

So: in a review today, we identified 2 pieces of work on our side that need to be done, as well as 3 other teams that are not completely finished removing old references. (VAOS and Personalization, who we've been in contact with, and a Health Products team that we haven't). 

Will update here re: that outreach as it moves along. Meanwhile, we should prioritize the remaining work we can complete ourselves, as possible.

**Comment by jilladams** [comment]
1. **Health products**
codeowner: [@department-of-veterans-affairs/va-cto-health-products](https://github.com/orgs/department-of-veterans-affairs/teams/va-cto-health-products)
file: `src/applications/coronavirus-vaccination/components/SelectFacilityWidget/index.jsx`
reachout: https://dsva.slack.com/archives/C52CL1PKQ/p1677629202007359 - Stephen Barrs

2. **Personalization**
codeowner: [@department-of-veterans-affairs/vsa-authd-exp-frontend](https://github.com/orgs/department-of-veterans-affairs/teams/vsa-authd-exp-frontend) [@department-of-veterans-affairs/benefits-team-1-frontend](https://github.com/orgs/department-of-veterans-affairs/teams/benefits-team-1-frontend) (personalization/profile)
files: 
`src/applications/personalization/profile/components/notification-settings/NotificationChannel.jsx`
`src/applications/personalization/profile/components/notification-settings/NotificationSettings.jsx`
Reachout: TBD

3. **VAOS**
codeowner: [@department-of-veterans-affairs/vfs-vaos-fe](https://github.com/orgs/department-of-veterans-affairs/teams/vfs-vaos-fe)
file: `src/applications/vaos/components/EnrolledRoute.jsx`
reachout: TBD

**Comment by jilladams** [comment]
Pinged threads re: whether tickets have been filed to track this work.

**Comment by jilladams** [comment]
Last outstanding blocker here is https://github.com/department-of-veterans-affairs/va.gov-team/issues/49612. I've pinged that ticket to see if last week's Health apps update to load the static data via the header means this will close soon, or if that team has any estimated timing.

**Comment by jilladams** [comment]
Update! We might be unblocked. 
https://github.com/department-of-veterans-affairs/va.gov-team/issues/49612 is still open, but Patrick Bateman shipped this change:  https://github.com/department-of-veterans-affairs/vets-website/pull/24354, which might remove the last barrier to deprecating the old data method. Will note on PR as well. It would be very smart of us to try and get this completed while Ryan is still around on Sitewide, if we can rereview / try for that in Sprint 86 or 87, @wesrowe @davidconlon .

**Comment by randimays** [comment]
I took a look at the deprecation PR. All of Ryan's comments are addressed fully except for [this one](https://github.com/department-of-veterans-affairs/vets-website/pull/23036#discussion_r1061926816). One of the selectors in his list is still being used by the Appointments team. [I posted a Slack message](https://dsva.slack.com/archives/CMNQT72LX/p1690834106763749?thread_ts=1673026289.887489&cid=CMNQT72LX) on the existing thread to ask them to have a look.

I tried testing the Cerner widgets in the meantime, but the build is blocked on those two compile errors (they are referencing a selector that has already been removed from this branch).

**Comment by jilladams** [comment]
THANK YOU.

**Comment by jilladams** [comment]
Pulled in Sprint 89 opportunistically, discovered still blocked, punting back out of Sprint until Appointments team issue is resolved.

**Comment by wesrowe** [comment]
Wes edit: I think the slack thread said that #61301 in the Teams repo is the thing that will unblock us. I think 25036 is our PR...

**Comment by jilladams** [comment]
yep, sorry, was just cross-linking to my same comment on our PR. Updated my comment to make that more clear

**Comment by randimays** [comment]
Update: I feel confident we are ready to get this PR merged. There are a handful of other teams involved in the code changes (but they're minor changes). I requested all the reviews and hopefully we'll be able to get this over the line before sprint end.

**Comment by randimays** [comment]
Pinged everyone today to have a look at the PR. Working on addressing any feedback.

**Comment by randimays** [comment]
Still waiting on some reviews. This will carry over to the next sprint.

**Comment by randimays** [comment]
This PR now has all the approvals it needs, but since we missed the prod deploy today (and we don't want to deploy on a Friday), this will be merged Monday morning.

**Comment by randimays** [comment]
Validated unauthed and authed (Cerner and Vista) in Staging. Only able to validate unauthed in Prod. Looks good! Closing.
