### ISSUE TITLE
Defects in deployed redesigned VA.gov home page

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-cms#9308]
## Issue description
This issue covers defects found during the validation of the redesigned home page as deployed to [staging](https://staging.va.gov/homepage-test/) for [Epic #8340: Iterate VA.gov changes for demo/testing in publicly accessible environment](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/8340). 

## Validation against Sketch

**Checks indicate deployment passes validation against [Sketch (first build)](https://www.sketch.com/s/3aa40506-4be2-46cc-876b-93f1a9f3a857/a/PGEaJDr)**

### Sign in/sign up
- [x] Veteran portraits are visible below the header
- [x] Veteran portraits display randomly with reload
- [x] Sign-up/sign-in CTA title "Access and manage your VA benefits and health care" is displayed in new prominent location below the header. 
- [ ] Login link is functional and points to production url
- [ ] Login button **in header** is functional and points to production url
- [ ] My VA link **in header** is functional and points to production

<details>
<summary> Expected behavior based on Sketch </summary>

![image.png](https://images.zenhubusercontent.com/5d8a47393ac3440001d1a2ed/6304e6a1-7121-483d-abae-43b543ff8385)

</details>

### Search
- [x] Search field and button to submit are present below new sign-in/sign-up CTA
- [x] Links listed under "Other search tools" are displayed as two unbulleted columns  
- [x] Search functionality is comparable to Production behavior. 
- [ ] Links are functional and point to production urls

<details>
<summary> Expected behavior based on Sketch </summary>

![image.png](https://images.zenhubusercontent.com/5d8a47393ac3440001d1a2ed/aaaab5ea-b221-4abe-84a7-f4b3300aef82)
</details>

### Common tasks
Functional links are available for the following common tasks
- [x] Check your claim or appeal status
- [x] View your payment historyva.gov/va-payment-history)
- [x] Download your benefit letters
- [x] Get Veteran ID cards
- [x] File a claim for compensation
- [ ] Links are functional and point to production urls

### VAntage point blog
- [x] Single promo and photo are displayed
- [x] Links are functional ~and point to production urls~ _(per Dave, staging urls are fine)_

### Benefit hubs
- [ ] "Learn about and apply for VA benefits and health care" heading is displayed immediately above the hub blurbs
- [x] Hub headings, icons and blurb are present, consistent with production
- [ ] Links are functional and point to production urls
- [ ] The four top task boxes and legacy "Access and manage your VA benefits and health care" heading are no longer displayed
- [ ] Facility Locator, Crisis line and sign in call out boxes are no longer displayed below benefit hubs
- [ ] Promos for State Veteran Affairs Offices, "Support for those who served" and VAntage Point are no longer displayed below benefit hubs
- [ ] Row of Veteran portraits are no longer displayed above footer

<details>
<summary> Expected behavior based on Sketch </summary>

![image.png](https://images.zenhubusercontent.com/5d8a47393ac3440001d1a2ed/46755da5-33df-4056-bc25-606fdf27c78e)

</details>
<details>
<summary> Actual version deployed </summary>

![screencapture-staging-va-gov-homepage-test-2022-06-03-13_45_17.png](https://images.zenhubusercontent.com/5d8a47393ac3440001d1a2ed/a06a1a57-878b-4a97-bf28-1fff59511689) 
</details>

## Expected behavior
Validation was performed against [Sketch (first build)](https://www.sketch.com/s/3aa40506-4be2-46cc-876b-93f1a9f3a857/a/PGEaJDr)

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Platform CMS Team`
- [ ] `Sitewide program`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by mmiddaugh** [comment]
Observations for the Sign-in/sign up and Search areas were resolved by the recent merge. 🎉

**Comment by mmiddaugh** [comment]
While testing search functionality, I noticed this odd search behavior in staging deployment. Moving to the second page of results did not honor my search entry and seemed to start over with the first page of results. This behavior isn't seen on production and we'll want to use the production url for search when it is time for usability and stakeholder validation. 
https://www.loom.com/share/9ffc061e1efc430da558389e17db2265

**Comment by allisonlu** [comment]
@mmiddaugh While looking into making the Sign in and My VA buttons in the **header** points to production, I think this may be out of scope since this would require editing the header template (which the actual home page also shares).

Also the Sign in button in the hero is using the same function as the Sign in button in the header. This requires editing existing code, which introduces risk. 

Will users be able to sign in via the staging link for usability testing?

**Comment by allisonlu** [comment]
^ that also applies to the Hub links (where the URL path is controlled in the CMS)

**Comment by mmiddaugh** [comment]
For the purpose of usability testing, my understanding is that task completion will be defined as taking the user to the point of sign-in and so accessing the prod environment will not be necessary. 
There may be other use cases outside of usability where production links are needed.  @davidconlon?

**Comment by mmiddaugh** [comment]
Per Dave Conon: in [Slack](https://dsva.slack.com/archives/C52CL1PKQ/p1655138640100409)

> At this point, everything is in staging so we don't need to worry about whether it gets to prod or no to prod.
> That has been out of scope as part of this build.
> Because the whole "point to prod" issue becomes moot when we release the page on Prod as /homepage-test/ after we've done more testing.

**Comment by allisonlu** [comment]
> While testing search functionality, I noticed this odd search behavior in staging deployment. Moving to the second page of results did not honor my search entry and seemed to start over with the first page of results. This behavior isn't seen on production and we'll want to use the production url for search when it is time for usability and stakeholder validation. https://www.loom.com/share/9ffc061e1efc430da558389e17db2265

@mmiddaugh This is also happening in production. I wrote a new issue for this because this will take some time to debug: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9425

**Comment by allisonlu** [comment]
PR opened: https://github.com/department-of-veterans-affairs/content-build/pull/1171

Just a note: links are all relative (so none of them point to prod)

**Comment by allisonlu** [comment]
Oh nevermind! Looks like all the changes made it onto staging: 

https://staging.va.gov/homepage-test/

@mmiddaugh
