### ISSUE TITLE
Discovery: Document current-state UX for verifying eligibility/Income Limits

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#9312]
## Description
Income Limits AKA "Means-test Thresholds" for medical eligibility – tooling that helps veterans understand if they qualify for benefits, based on inputs like:
- income
- location
- number of dependents
- anything else?

Current tools: 
* https://www.va.gov/healthbenefits/apps/explorer/AnnualIncomeLimits/HealthBenefits
* https://www.va.gov/healthbenefits/apps/explorer/AnnualIncomeLimits/LegacyGMTThresholds?FiscalYear=2021&PriorityGroupLevel=8

Project is to understand these tools, how they're used, and how we can pull this functionality under VA.gov & make it more usable. 

Iteration could be web-app ish, e.g. allowa a veteran to enter data such as: This is where I live, how many dependents I have, my income. Then receive a determination re: whether they are / aren't  eligible for VA healthcare.

Would also like to create an easy way to make the data itself usable / maintainable. 

Not a requirement to tie into the CMS.

**Time box:** 1/2 day

## Acceptance Criteria
- [x] Gather URLs on va.gov (modernized and/or legacy) that touch this topic
- [ ] Hypothesize what is the happy-path existing user flow among these pages
- [ ] meet with SMEs/stakeholders if appropriate

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Platform CMS Team`
- [ ] `Sitewide program`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by fmccaf1** [comment]
### Current Experience URLS

- [Annual Income Limits - Health Benefits ](https://www.va.gov/healthbenefits/apps/explorer/AnnualIncomeLimits/HealthBenefits)
- [Income Limits Table: 2021 VA National and Priority Group 8 Income Thresholds for Cost-Free Health Care, Medications, and/or Beneficiary Travel Eligibility](https://www.va.gov/healthbenefits/apps/explorer/AnnualIncomeLimits/LegacyVAThresholds?FiscalYear=2021)
- [Geographic-Based Financial Assessment (2022)](https://www.va.gov/healthbenefits/apps/explorer/AnnualIncomeLimits/LegacyGMTThresholds/Index?FiscalYear=2022&PriorityGroupLevel=8)
- [Most or all of the above links can be found on this modernized page](https://www.va.gov/health-care/about-va-health-benefits/cost-of-care/)
