### ISSUE TITLE
Remove content announcement block placement for recurring events

### ISSUE THREAD

**Issue by EWashb** [department-of-veterans-affairs/va.gov-cms#9319]
## Description 

As mentioned in #9309, the announcement block will need to be taken down when we are ready to stop announcing the release. The timeline is still TBD with change management.

## Acceptance Criteria
- [x] Change management determines when the announcement block is ready to be removed
- [x] Content strategist removes the block and informs dev to start the manual db process

**Comment by rachel-kauff** [comment]
@ContentBrewmaster I'm thinking a good timeline for things like this could be 3-4 weeks. That accounts for people who don't log in frequently or don't edit events very often. What do you think?

**Comment by ContentBrewmaster** [comment]
@rachel-kauff judging from when editors last accessed the system, I think 4 weeks is a good interval.

**Comment by rachel-kauff** [comment]
@ContentBrewmaster Great! I'll update our documentation to suggest that as a place to start. For this initiative, that puts us at 7/5 / top of sprint 62.

**Comment by rachel-kauff** [comment]
@EWashb I'm updating the sprint for this one accordingly -- we don't need to remove this block until sprint 62

**Comment by EWashb** [comment]
@rachel-kauff does this still seem ready to take down for sprint 62?

**Comment by EWashb** [comment]
hold for sprint 63 after talking with Jill at PW.

**Comment by EWashb** [comment]
@jilladams is this ready to be removed in sprint 63?

**Comment by jilladams** [comment]
I believe so! Best to confirm with Dave in your sprint planning, but from
PW perspective: yes, is good to go.

**Comment by EWashb** [comment]
@rachel-kauff would you be able to take care of this?

**Comment by rachel-kauff** [comment]
@EWashb Done!
