### ISSUE TITLE
Post-mortem for Facility Locator defect 9320

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#9321]
## Acceptance Criteria
- [ ] Post-mortem is created and submitted

**Comment by swirtSJW** [comment]
WIP https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/pull/501/files  Fine tuning it after our post mortem call.

**Comment by kevwalsh** [comment]
@swirtSJW the PR has been sitting approved for 10 days with no changes AFAICT. Can this ticket be closed? If not please assign to 61.
