### ISSUE TITLE
CMS design system research study

### ISSUE THREAD

**Issue by EWashb** [department-of-veterans-affairs/va.gov-cms#9339]
## Purpose

The user/designer will complete a usability study coordinated by the Sitewide CMS team to determine what gaps exist in the documentation and can be improved prior to the kickoff of the Sitewide CMS collab cycle launch. The study will be associated with an assigned task that uses both the Figma design system and Confluence documentation.

## Acceptance Criteria

- [ ] Sitewide CMS Interaction designer schedules research time with user
- [ ] Usability study is completed
- [ ] Findings are documented and shared with PM to determine how best to improve the documentation process

**Comment by jcklpe** [comment]
I can get started on this today. Is this just a general "look at stuff" ticket or is there any deliverables I should be sure to make? (even if those deliverables are just something like documentation or an article with my notes in it etc. I find that sometimes even if the ticket is a general research thing, it can be helpful to have something concrete)

**Comment by EWashb** [comment]
This will be pivoted into a collab cycle research plan.
