### ISSUE TITLE
Update Cerner runbooks to add CM notes

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#9340]
## Description
We maintain 2 runbooks for Cerner cutovers: 
1. hard coded version: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/public-websites/Cerner-Support/how_to_set_up_vamc_cerner_within_va_health_care_portals.md
2. Drupal SSOT version: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/public-websites/Cerner-Support/cms-source-of-truth/opt-in-drupal-source-of-truth.md

Update both:
1. Add: Create a CM task to contact editors to notify them that their system is now on Cerner

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [X] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by jilladams** [comment]
Added: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/public-websites/Cerner-Support/how_to_set_up_vamc_cerner_within_va_health_care_portals.md#task-3-trigger-change-management-email

Follow up needs: 
* @ContentBrewmaster to follow up re: who should be sending these emails moving forward
* @ContentBrewmaster to provide the definitive final text of the email, to add to https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9338#issuecomment-1204434889, for public reference (vs a Word doc)

**Comment by jilladams** [comment]
@ContentBrewmaster just checking in re: the point of contact who should send these emails in future, to add to runbook. Let me know once you have a sense of that yet or if it's blocked on input from other people?

**Comment by ContentBrewmaster** [comment]
@jilladams answer is blocked on input from VHA Digital Media. Have in follow-up this week.

**Comment by jilladams** [comment]
Thank you! Updated in runbook. 

Closing.
