### ISSUE TITLE
Content Audit: Veteran-facing references to developer.va.gov

### ISSUE THREAD

**Issue by careyotto** [department-of-veterans-affairs/va.gov-cms#9341]
## Describe the request
The support team for developer.va.gov (which is part of the VA Lighthouse program) have consistently been receiving support requests from Veterans over the last couple of years. In our efforts to discover how Veterans are finding us, we discovered that [the API docs](https://developer.va.gov/explore/vaForms/docs/vaForms?version=current) are being recommended at the bottom of https://www.va.gov/find-forms/.

What we'd like is a content audit run across all of VA.gov to determine if there are other referring links to developer.va.gov pages or content.

* Context: 
* Terms of interest: developer.va.gov/* URLs
* Alternate spellings / terms: developer, API, VA API Platform, VA API, Lighthouse

### Implementation date
When does this request need to be complete?: This is an ongoing issue for us, so as soon as you can fit it in would be great!

Please submit all engineering requests **at least 1 full sprint in advance** (so we can work it into our next sprint).

## CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [x] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by jilladams** [comment]
@davidconlon This is a 2 part request from Lighthouse program UX lead, Carey Otto, and we'll plan to review during refinement 6/9: 
1. Content audit for references to developer.va.gov, in order for Lighthouse team to review if it's appropriate for those references to be Veteran-facing.
2. Remove the existing link at the foot of [Find a Form](https://www.va.gov/find-forms/) that points to [VA forms API for states and Veteran organizations](https://developer.va.gov/explore/vaForms/docs/vaForms?version=current) (or, get it removed by Content team): 
<img width="630" alt="image" src="https://user-images.githubusercontent.com/85581471/172434439-177d3a7e-68ba-4068-a7f0-4b14be4c8eaa.png">

From Carey in Slack:
> Our developer support team continually receives support requests from Veterans. We’ve been trying to track down how they are finding us. One theory is that they may be arriving to our developer focused pages through the “more information” link on the [Forms You Can Use](https://www.va.gov/find-forms/) page (and potentially other pages).

Related slack thread: https://dsva.slack.com/archives/C0NGDDXME/p1654208769874479

**Comment by DanielleThierryUSDSVA** [comment]
Thanks, @jilladams! I'll ask the content team to remove the link in Drupal.

**Comment by jilladams** [comment]
@careyotto I ran this audit and just found one additional reference to `developer.va.gov`, on this page: https://www.va.gov/altoona-health-care/news-releases/va-health-app-now-available-to-veterans-across-all-mobile-and-web/index.html

For developer reference:  
`grep -Rli "developer.va.gov" build/localhost > ~/Downloads/developer.txt`
returns:
```
/find-forms/index.html
/altoona-health-care/news-releases/va-health-app-now-available-to-veterans-across-all-mobile-and-web/index.html
```

**Comment by careyotto** [comment]
Great find, thanks Jill! I'm going to take this to my team and see if our Outreach team knows the source of the content.

- Do you happen to have analytics set up to track how many folks are clicking from that news release to the developer portal?
- Would it be possible to remove the link in this press release?

**Comment by careyotto** [comment]
@jilladams I believe that press release was originally published by OPA:

https://www.va.gov/opa/pressrel/pressrelease.cfm?id=5430#:~:text=Need%20Viewer%20Software%3F-,VA%20health%20app%20now%20available%20to%20Veterans%20across%20all%20mobile,their%20health%20care%20data%20online.

And it looks like it might be VA Altoona's only press release? Curious...
https://www.va.gov/altoona-health-care/news-releases/

**Comment by wesrowe** [comment]
@careyotto, that press release has had only one visitor this year per Google Analytics _in total_. And it was in the last few days – "the call is coming from inside the building." (Ie, one of us.)

**Comment by jilladams** [comment]
@careyotto found info re: owners of this Press release: 
* original person to have published this page in April 2020, [Khalea.lester@va.gov](mailto:Khalea.lester@va.gov), is no longer listed as an active user on https://prod.cms.va.gov/
* there are two editors listed for VA Altoona who have editing permissions — [Evan.Hinkley@va.gov](mailto:Evan.Hinkley@va.gov) and [christopher.lemke@va.gov](mailto:christopher.lemke@va.gov)

You should be able to reach out to them about getting that content modified!
