### ISSUE TITLE
Add QA steps section to PR templates  on content-build and vetswebsite

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#9343]
## Description
In order to help foster a culture of improved QA on PRs we should have guidance on our PRs for content-build and vetswebsite the same way we do for CMS

![image](https://user-images.githubusercontent.com/5752113/172304922-9f1c42af-dc3a-47ea-b820-24444bdfe7a3.png)

[Outcome of postmortem](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/pull/501)

## Acceptance Criteria
- [ ] Consensus with affected teams achieved.
- [x] QA steps section added to content-build pr template  PR here https://github.com/department-of-veterans-affairs/content-build/pull/1269
- [ ] QA steps section added to vetswebsite pr template

**Comment by jilladams** [comment]
AMAZING. Just saw this ticket, and we had this very conversation in retro today. Thanks Steve!  Let us know if you need help with the vets-website version.

**Comment by swirtSJW** [comment]
Removing CMS label as this unrelated to CMS team and relates to people with their hands in the FE repos.

**Comment by jilladams** [comment]
Interesting find. The team list in ticket body is old and I'm scraping it out everywhere I find it. Labels are the real Team owner indicator now -- so from that angle: sure, PW could work on this. 

However: this dates back a ways to when we didn't really grok how the FE worked on this contract. Nowadays, big picture: 

## vets-website
the Platform FE COP owns the repo and PR templates. If we modify the template, the changes would need to get sign off from Platform, and would apply to everyone in the ecosystem who submits code there. 

## content-build
Is owned by the CMS team, even though it's a FE repo. So it's in a netherworld between the CMS team and the Platform FE COP. But same here: we could propose PR template edits, and they'd need CMS team signoff, and would affect anyone who contributes to content-build. 

I'd be interested to hear @randimays @chriskim2311 (as well as @eselkin and @maxx1128 's ) thoughts about what we might want to do here. 

One thing I might suggest covering came up based on a Facilities issue today: [VA browser support](https://depo-platform-documentation.scrollhelp.site/developer-docs/browser-support-policy) and related testing. e.g. what's our baseline for cross-browser testing? (we found a Facilities bug where FF acts different than Chrome, and that highlighted that if we dont explicitly name browser testing in ACs, it might be easy to forget.)

**Comment by jilladams** [comment]
(Also I haven't looked at the existing PR templates ever, so that might already be covered.)

**Comment by randimays** [comment]
I have made adjustments to the PR templates before (including this PR: https://github.com/department-of-veterans-affairs/content-build/pull/1773/files where I changed the content-build template to match the vets-website template). I think making edits to the templates would be great, but our problem stems from discipline across the teams and Platform folks thoroughly reading & reviewing PRs. 

In addition to making those template updates, I think it's important for us to ask Platform to communicate (and enforce) expectations around PR thoroughness and QA (including completely filling out the template).

**Comment by Agile6MSkinner** [comment]
@jilladams @davidmpickett @randimays @omahane @FranECross This issue was raised over two year ago. Is it still a problem?

**Comment by randimays** [comment]
The [current PR template](https://github.com/department-of-veterans-affairs/vets-website/blob/main/.github/PULL_REQUEST_TEMPLATE.md) is the same for both vets-website and content-build and covers the requirements of this ticket. [I commented in Slack](https://dsva.slack.com/archives/C04868KS69L/p1718215674000889) that VFS teams as a whole aren't filling out the template completely and Platform is not enforcing it when approving PRs. I don't think continued edits of the PR template is a productive use of our time until we can improve these checks and balances.
