### ISSUE TITLE
Back-end ramp up on Events

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#9346]
## Description
Recurring events will launch today, 6/7. Ethan Teague on the Facilities team has built the backend changes to get recurring events going. The Public Websites team will own Events content moving forward, so we should get Drupal engineers ramped up on the changes / implications here. Specifically, getting familiar with the backend changes that are launching now is the top priority. 

FYI @ethanteague 

## Acceptance Criteria
- [x] Document any findings
- [x] Learn the problems we have encountered / may yet encounter

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [X] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by dsasser** [comment]
I have done a code review as well as a knowledge share with Ethan. I don't feel additional technical documentation is needed at this time.
