### ISSUE TITLE
"Tables" a11y error on events pages reported by Cypress

### ISSUE THREAD

**Issue by tjheffner** [department-of-veterans-affairs/va.gov-cms#9348]
## Describe the defect
The past two days the a11y report run has reported errors on all `/events/` pages on va.gov with an interesting error message.

The error message in question:
```
https://www.va.gov/alaska-health-care/events/ 5.7s

Error: Table data must not contain control characters.
    at validateTableData (http://localhost:3002/__cypress/tests?p=src/platform/testing/e2e/cypress/support/index.js:31557:23)
    at table (http://localhost:3002/__cypress/tests?p=src/platform/testing/e2e/cypress/support/index.js:31208:47)
    at eval (http://localhost:3002/__cypress/tests?p=src/platform/testing/e2e/cypress/support/index.js:31858:114)
    at Context.eval (http://localhost:3002/__cypress/tests?p=src/platform/testing/e2e/cypress/support/index.js:31858:97)

const localURL = url.replace(`https://www.va.gov`, `http://localhost:${Cypress.env('CONTENT_BUILD_PORT')}`);
cy.visit(localURL);
cy.get('body').should('be.visible', {
  timeout: normal
}); // eslint-disable-next-line cypress/no-unnecessary-waiting
cy.wait(3000);
cy.injectAxe().axeCheck({
  exclude: [['.loading-indicator'], ['div[data-widget-type="facility-map"]']]
});
```

## To Reproduce
A11y reports (hit the red x to filter by errors only):
https://testing-tools-testing-reports.s3-us-gov-west-1.amazonaws.com/a11y-reports/ca2b447a-c1ce-45c4-bfb5-472320871f08.html
https://testing-tools-testing-reports.s3-us-gov-west-1.amazonaws.com/a11y-reports/46e6a3d7-c0d8-4bdf-a497-1e295934bacf.html

See this slack thread for initial mention: https://dsva.slack.com/archives/CT4GZBM8F/p1654551765780429?thread_ts=1654551167.275559&cid=CT4GZBM8F

## Expected behavior
Cypress works properly on events pages and reports no errors.

## Screenshots
<img width="1283" alt="Screen Shot 2022-06-07 at 10 31 14 AM" src="https://user-images.githubusercontent.com/11279744/172446494-43a38015-ebb5-4648-bb12-cd645e9d6dee.png">

 ## Additional context
This is extra confusing because the pages in question do not appear to have a table in them. Searching the dom on https://www.va.gov/albany-health-care/events/ only returns two instances of the word "table", both in css styles.
<img width="1919" alt="Screen Shot 2022-06-07 at 10 34 31 AM" src="https://user-images.githubusercontent.com/11279744/172446651-43021804-b2db-4648-84d8-9cf524ff142b.png">

<img width="645" alt="Screen Shot 2022-06-07 at 10 32 19 AM" src="https://user-images.githubusercontent.com/11279744/172446368-aa002185-76c5-4d1a-881b-80d42ee33811.png">

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Defect")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS workstream (orange) (not needed for bug tickets)
- [ ] CMS-supported product (black)

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by jilladams** [comment]
This is old. We need to work out if it's still real, and close if not. Prob not.

**Comment by FranECross** [comment]
@laflannery Is this something you'd be able to check to determine if it's still an issue, or do we need a dev to take a look?  TIA!

**Comment by laflannery** [comment]
I can't find any tables as Tanner mentioned above so I can't see how this would have been an issue (which is also what confused them at the time) but I also can't run cypress so I can't confirm that this isn't still happening

**Comment by FranECross** [comment]
Closing as a no op; a new ticket will be created of anything like this crops up in the future.
