### ISSUE TITLE
Bug: Events header jumps out of alignment during page load on VAMC & Outreach events listing pages

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#9374]
## Description

After release of Events v2 filters, the header and page body contents do not correctly left align on [main Outreach and Events page](https://www.va.gov/outreach-and-events/events/) or VAMC events pages. 

### Outreach & Events
 looks like this after page load:

![image.png](https://images.zenhubusercontent.com/61a671f5fc46c2a311655f75/50917df1-3106-4507-91a1-0c7f4c17d552)

You can see it start in the correct place and then jump.

### VAMC Events pages
e.g. https://www.va.gov/boston-health-care/events/

![Screen Shot 2022-06-10 at 2 33 25 PM](https://user-images.githubusercontent.com/85581471/173154252-1afaeec9-9fa5-40f0-b520-acad5b2891be.png)

## Acceptance Criteria
- [ ] Header and page body contents left align correctly on /outreach-and-events/events/
- [ ] Header and page body contents left align correctly on VAMC events pages, e.g. /boston-health-care/events/46953

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by jilladams** [comment]
FYI @maxx1128. 
This isn't an emergency, and @kevwalsh  thought Max has capacity. Not sure if you all want to pull this into sprint as an injection or leave it til next sprint? Adding Facilities label so it shows up in your board.
