### ISSUE TITLE
[Events] Frontend fix: Events that cross midnight should show the day & date of the event end time

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#9377]
## Status
**[2024-08-13] [Fran]** Amanda has asked AP if this formatting is possible, unknown at this time, but it may be on Sitewide engineers to determine tech feasibility once the Events AP template is officially handed off.
**[2024-08-05] [Fran]** Amanda K has confirmed via Medalia surveys that this is NOT a common pain-point for veterans, so I'm demoting it to be looked at again during Events V3 work.

## Description
Events list day, date, start time - end time, e.g. `Sun. Aug 14, 2022, 11:30 am – 12:30 am ET`
For events that span midnight they should list day, date, start time - day, date, end time, e.g. `Sun. Aug 14, 2022, 11:30 am – Mon. Aug 15, 2022, 12:30 am ET`

## Acceptance Criteria
- [ ] day, date appear on crossing-midnight event end times in event listing
- [ ] day, date appear on crossing-midnight event end times on a single event

**Comment by jilladams** [comment]
Priority-wise: could fix this as stretch, or could hold it til we do bigger picture all-day events. Per Dave, we don't have any evidence that this is an issue, but basic alignment on how we present am/pm info is smart regardless.

**Comment by jilladams** [comment]
@FranECross There will be some cost to making Events FE changes during the time period while we wait for AP to launch (double changes in content-build & AP, and maybe again later in the new React app) -- so same priority question on this one: do we want to fix this in content-build now, AP when it launches, or in the updated React app when we build it?

**Comment by FranECross** [comment]
@jilladams Thanks for surfacing this! @aklausmeier @thejordanwood  If I wanted to see if there are any/a bunch of Veteran complaints or comments regarding confusion around this issue, would I look at Medalia data? And if so, I'm not sure where that is.... Thanks in advance!

**Comment by aklausmeier** [comment]
@FranECross I've reviewed the past two years of Medallia synthesis for Events and this is not a common pain point. 

There could be instances where it does go past midnight and we should accommodate for that, likely online events that are available across time zones. 

**Use case to support:** Online event in PST ends at 10pm PT and equates to 1am ET. 

Note: For the future, prior Medallia summaries/synth are typically in the GitHub product > research folder and spreadsheets are also in the team's Sharepoint folders.

**Comment by aklausmeier** [comment]
AP is implementing a [timezone localization feature](https://dsva.slack.com/archives/C01SR56755H/p1723492678549359?thread_ts=1723476807.939299&cid=C01SR56755H) that may solve for this use case.

**Comment by aklausmeier** [comment]
Prod today https://www.va.gov/pacific-islands-health-care/events/64414/

<img width="618" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd1JQQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cdebc0272bb56f71b30c78a9d0c1213d629c4bf0/Screenshot%202024-08-12%20at%202.03.26%20PM.png" alt="Screenshot 2024-08-12 at 2.03.26 PM.png" />

**Comment by aklausmeier** [comment]
Prod today: https://www.va.gov/pacific-islands-health-care/events/64414/

![Screenshot 2024-08-12 at 2 03 26 PM](https://github.com/user-attachments/assets/fcee996f-71e5-4fc2-a852-fad6511dcccf)

**Comment by aklausmeier** [comment]
AP version of same page with timezone localization: https://dev.va.gov/pacific-islands-health-care/events/64414/

![Screenshot 2024-08-12 at 2 04 46 PM](https://github.com/user-attachments/assets/ae6a07ab-7c8e-4e1b-b29d-97fcd63b673d)


Note: I am seeing MST which is my personal timezone

**Comment by FranECross** [comment]
Thanks for this info, @aklausmeier!  Do you feel that we don't need to be concerned that the 1:00AM doesn't indicate that it's on Sunday?

**Comment by aklausmeier** [comment]
I have asked AP if this formatting is possible, unknown at this time, but it may be on Sitewide engineers to determine tech feasibility once the Events AP template is officially handed off.

**Comment by aklausmeier** [comment]
@FranECross **AP will not implement** the inclusion of showing the day/date when an event crosses midnight and the date is now different. I confirmed with AP that if this becomes a priority that Sitewide want to implement, we will own the enhancement.

**Comment by FranECross** [comment]
@aklausmeier Thanks so much for checking! I'm going to close this as a no op at this time, and if feedback indicates it's a confusion point in the future, we (or whichever team owns events) can create a new ticket.
