### ISSUE TITLE
Update content for Get Medical Records detail page (react widget)

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#9387]
## Description

A lot of the content on [this page](https://www.va.gov/health-care/get-medical-records/) is hard-coded inside a react widget. That content is being updated by the SW Content team and needs to be live by ~~July 1~~.

Per @RLHecht, 6/29 ([Slack](https://dsva.slack.com/archives/C52CL1PKQ/p1656533663299089)): 
>  We are going to hold off on publishing these Medical Records pages tomorrow. Our VA partners would like us to wait for people from DoD to weigh in on their page and we won't hear back from them in time for this to be completed tomorrow. Rather than making changes to these pages twice, we will publish all at once when we get the go-ahead next week. As soon as I hear from them and know whether we'll have changes you'll need to make in these files, I'll let you know. In the meantime, I'll keep commenting in the ticket for the work Allison is currently doing in this. Thanks so much for your flexibility with this. FYSA 

## Acceptance Criteria
- [ ] Testable_Outcome_X
- [ ] Testable_Outcome_Y
- [ ] Testable_Outcome_Z
- [ ] Requires design review

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by wesrowe** [comment]
per @davidconlon this will be a sprint goal for sprint 61

**Comment by allisonlu** [comment]
@wesrowe @jilladams can you remind me where the new content is?

**Comment by jilladams** [comment]
@wesrowe I _think_ the content we're talking about is the 'Main "Get your records" page' content mentioned here,  https://github.com/department-of-veterans-affairs/va.gov-team/issues/41796#issuecomment-1152789350 , but I don't see that Danielle has signed off on it yet. Do you have notes somewhere about another source for final copy?

**Comment by RLHecht** [comment]
@jilladams Here is the non-Cerner content. Just note that there may be changes from stakeholders. We gave them 6/21 as a deadline and haven't heard back. I followed up today. The one section that you'll see still has a question for stakeholders could be published as is and we could always make changes afterward (though I know that's not ideal since we need to send this to you again). 

[Get your medical records_Non-Cerner version_for SME team.docx](https://github.com/department-of-veterans-affairs/va.gov-cms/files/8960464/Get.your.medical.records_Non-Cerner.version_for.SME.team.docx)

I will post the Cerner version in a bit but waiting on a cleaned up version of it.

**Comment by jilladams** [comment]
Thanks! Content is now final. I'm going to unassign Allison here, to make clear that whoever has capacity first on Front end can pick this up, until she's back from being sick, since it's a sprint goal.

**Comment by jilladams** [comment]
Code treats the distinctions as: 
* unauthenticated
* Cerner

Copy does:
* Cerner 
* non-Cerner

In this case: non-Cerner / unauthed are synonymous. That's not always true.

Our test users aren't working today. WOrking with Allison on a TUD user, and will ping Anthony if none work.

SHipping: 
R&S articles must be published before we ship, to prevent broken links. Randi will manage publishing, but we need to notify her when we're ready to merge, so she can publish. Should target merge after 29th daily deploy, for deploy on the 30th.

**Comment by allisonlu** [comment]
Caveats:
- Changing the Sign In CTA copy will apply FOR ALL pages that use this CTA component
- I've left the [dynamic facility name] alone, since this would take more time than expected to figure out how to pull in the current facility name.

**Comment by jilladams** [comment]
Nice! And we still don't have a means of getting eyes on the Cerner version in staging, without a test user, correct?

**Comment by jilladams** [comment]
Cerner testing was done - disabling CORS browser setting enabled using TUD users, and screenshots are added to the PR. 

This ticket will cross sprint boundary due to publishing delay from Sitewide Content, signed off by Dave in Slack.

**Comment by jilladams** [comment]
@RLHecht do you have any info about the possible timeline for publishing these changes?

**Comment by RLHecht** [comment]
Unfortunately we're still in a holding pattern waiting for the go-ahead from stakeholders. We haven't gotten approval yet to publish one of the pages we are linking too from this medical records page. As soon as I hear something I will let you know. Is everything now set on your end for when we are ready? I know there was still an issue with one part of the dynamic content.

**Comment by jilladams** [comment]
Yes, content is ready to merge/deploy when we get the greenlight, with the exception of dynamic facility name. That requires a bigger technical lift because the content here is all hard-coded. We've ticketed discovery around whether / how to do this under https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9854.

**Comment by jilladams** [comment]
Ticket is unblocked, added to Sprint 65, notes on https://github.com/department-of-veterans-affairs/vets-website/pull/21510#issuecomment-1212364288.

**Comment by allisonlu** [comment]
Get Medical Records page is now live on prod! 

https://www.va.gov/health-care/get-medical-records/
