### ISSUE TITLE
WYSIWYG for Benefits Detail page intro text

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#939]
## User Story or Problem Statement

As a editor, I need a way to safely use html in the intro text so I can make the intro text full featured and valid html.

The current use has a plain text field with help text about allowed tags, however the plain text is field is not validated on the way in, it is only filtered at render time, however GraphQL is not a render, it is data, so nothing is preventing the field from containing all kinds of html tags as well as faulty html.
HTML "allowed" via current help text
```<em> <strong> <br> <p> <a>```

HTML tags allowed by field settings 
```<a> <b> <big> <code> <del> <em> <i> <ins> <pre> <q> <small> <span> <strong> <sub> <sup> <tt> <ol> <ul> <li> <p> <br> <img>```

## Acceptance Criteria

1. On content type page (benefit detail page) `field_intro_text`  is replaced with `field_intro_text_limited_html` 
2. All contents of the field_intro_text are moved to field_intro_text_limited_html  (roughy 233 nodes)
3. The field field_intro_text_limited_html uses a WYSIWIG that applies a limited html filter. 
4.  The allowed html tags should be `<em> <strong> <br> <p> <a>`
5.  Behat tests updated and passing
6.  Update the frontend query to  use the new field. (timing critical)
7. Collab w/ Rachel on helptext

## Implementation details

1. A hook_update_n should be added to the va_gov_db module to load all the nodes and copy the data from the old field to the new and save the data. 
2. This will have to go out in **FOUR** releases:
    1. CMS - Add the new field and make it hidden on node view and node edit.
    2. CMS - Update hook moves the content and hides the old field from node edit but not node view. Make new field visible on node edit and node view.
    3. VAWEB - update GraphQL query and template
    4. CMS remove field_intro_text from the `page` content type

## Labels
- [/] Issue type (red) (defaults to Enhancement)
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [ ] CMS Objective (orange)
- [ ] CMS-supported product (black)

**Comment by swirtSJW** [comment]
@kevwalsh  Can you update the AC item to list what tags we do want to allow.  There is a disconnect between the help text and what is currently "allowed"

**Comment by kevwalsh** [comment]
@swirtSJW updated! sorry i missed this on Friday.
