### ISSUE TITLE
Update Cerner link in Get Lab Results react widget

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#9393]
## Description

An external Health Care testing team (associated with Tony Diaz) notified us that the Cerner link in the Get Lab Results react widget is wrong. Wes is waiting for Donna's team to confirm that the key difference is that the redirect URL has an extra `%2Flabs`  before the query param starts (at %3F).

Donna sent a Prod URL:
`https://patientportal.myhealth.va.gov/clear-session?to=https%3A%2F%2Fpatientportal.myhealth.va.gov%2Fpages%2Fhealth_record%2Fresults%3Fauthenticated%3Dtrue`

This is the current (wrong) link on the Lab Results widget in Staging:
`https://staging-patientportal.myhealth.va.gov/clear-session?to=https%3A%2F%2Fstaging-patientportal.myhealth.va.gov%2Fpages%2Fhealth_record%2Fresults%2Flabs%3Fauthenticated%3Dtrue1`

## Test data
Grab a user from [this file](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-cerner.md) in the sensitive repo.

## Issue as reported

**Scenario:**

On VA.gov testing the Healthcare redirect links to My VA Health. The medications, messaging, and appointments redirects worked; however, the lab and test results redirect took me to a page that loaded as this:
<img width="795" alt="image" src="https://user-images.githubusercontent.com/4054752/175195134-b49752e8-2e20-4b0e-a310-9506ca12cf4d.png">
The only solution was to enter a different page in the My VA Health portal and maneuver back to the “View Lab Results and Vitals” tab. 

**Recommendation:** Use this Redirect URL for the Lab and test results,[ https://patientportal.myhealth.va.gov/clear-session?to=https%3A%2F%2Fpatientportal.myhealth.va.gov%2Fpages%2Fhealth_record%2Fresults%3Fauthenticated%3Dtrue](https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fpatientportal.myhealth.va.gov%2Fclear-session%3Fto%3Dhttps%253A%252F%252Fpatientportal.myhealth.va.gov%252Fpages%252Fhealth_record%252Fresults%253Fauthenticated%253Dtrue&data=05%7C01%7CDonna.Alexander%40Cerner.com%7C1a161b67b7264ed663e408da4fc2d34c%7Cfbc493a80d244454a815f4ca58e8c09d%7C0%7C0%7C637909995434267842%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=aVItLA5FoTtycDvLpNNpVv0nnaCmVS89wBFOpEK4CKc%3D&reserved=0) .

## Wes's Exploration 6/22/22

It's not exactly clear what's wrong with the "wrong" screen above, but probably the tester didn't expect it to be blank. (It appears to hang while loading, with the blue rectangle first pulsing in color.)

I was able to see what the "better" state is supposed to be by clicking around to get back to lab and test results (as in the scenario above provided by the testing team). Note: it still took a really long time to get anything to load. Eventually a "loading" screen actually shows in the blank spot, followed by an error-ish message:
<img width="445" alt="image" src="https://user-images.githubusercontent.com/4054752/175198570-4fb3783a-d3be-4349-98e1-53db074f60b2.png">
<img width="736" alt="image" src="https://user-images.githubusercontent.com/4054752/175198617-cd134990-c4c2-46bc-8b46-8073b550a67c.png">

This seems "better", and possibly just bad user data. But how can we verify without talking to Cerner testing team?

**User I used above:** ssoissoetesting+mhvcss3@gmail.com

## A successful experiment: changing the href using dev tools

I tried altering the link on the CTA button using browser tools – i.e., to remove the `/labs` part of the href. It seemed to work! I got the same "better" screen above.

## Acceptance Criteria
- [ ] URL correct on button in Staging
- [ ] clicking button deep links to the correct screen in Cerner

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by jilladams** [comment]
@wesrowe this is showing in sprint, but without the sprint label -- I have forgotten: was this an injection? It's not assigned so not likely to get completed currently. If this was high priority from Dave, let's find someone to work on it tomorrow.

**Comment by jilladams** [comment]
Wes has email out to Donna with no response as of yet, looking for confirmation that 

Breaking these down to try to identify the differences other than staging/prod base urls:

For https://patientportal.myhealth.va.gov/, path = 
clear-session?to=https%3A%2F%2F        patientportal.myhealth.va.gov%2Fpages%2Fhealth_record%2F**results**%3Fauthenticated%3Dtrue

For https://staging-patientportal.myhealth.va.gov/, path = 
clear-session?to=https%3A%2F%2F**staging-**patientportal.myhealth.va.gov%2Fpages%2Fhealth_record%2F**results%2Flabs**%3Fauthenticated%3Dtrue

No response yet, since 6/9.

**Comment by wesrowe** [comment]
@ryguyk, since we can't get an email back from the original person reporting the issue to us, I went back into Staging to try to reproduce the issue. I was somewhat successful. I've added some screen shots in details above.
@jilladams, since I'll be on PTO could I ask you to reach out to Donna again?

**Comment by ryguyk** [comment]
@wesrowe This all makes sense. It seems pretty clear that `/pages/health_record/results/labs` isn't a meaningful URL. It should be `/pages/health_record/results`. Your exploration seems to demonstrate this, and I just poked around with similar findings. I think we can likely change this without much risk because, as you point out, it's not working currently anyway.

**Comment by jilladams** [comment]
I'm going to remove the high priority label, as this wasn't marked as a sprint goal during sprint planning, and that makes a difference for sprint reporting.

**Comment by jilladams** [comment]
(I realized I think it got added in the first place, by dragging into In Progress, above another sprint goal. That auto-adds the High Priority flag. TIL)

**Comment by ryguyk** [comment]
@jilladams Status Update: this should ship without concern.
