### ISSUE TITLE
Fix regression on the "Related" section of KB

### ISSUE THREAD

**Issue by EWashb** [department-of-veterans-affairs/va.gov-cms#9396]
## Background 

[Slack thread](https://dsva.slack.com/archives/CT4GZBM8F/p1654791227237299) for context. 

The "related links" at the bottom of the KB articles suffered a minor styling regression at the onset of Claro. 

Current state:
![Screen Shot 2022-06-09 at 1 50 47 PM](https://user-images.githubusercontent.com/90111970/172922350-be01df09-b268-4fe5-8966-9ed83511ec6c.png)

Some solutions to the design could include the examples listed in the [Link Collection Components ](https://design.va.gov/components/link/collection)of the VA design system. 

## ACs

- [ ] Create [Link Collection](https://design.va.gov/components/link/collection) equivalent in CMS Design system
- [ ] Implement Link Collection component in "related" section of Knowledgebase artciels node view.
- [ ] Change "Related" to "Related Articles"
- [ ] Move the last saved by an editor field to the left nav

**Comment by EWashb** [comment]
@EWashb find the link in the design sys

**Comment by laflannery** [comment]
Couple notes:

- "Related" should remain an H2 for accessibility considerations.
- If possible, could we include an ID on this heading as well? When I redid the formatting for KB articles I wanted to include Related articles in the "In this guide" ToC but couldn't since I didn't have ID to create and anchor link.

**Comment by EWashb** [comment]
@edmund-dunn see if this takes you directly to the [links](https://www.figma.com/file/ScABI31f3MRFEvQ8WitVPa/CMS-Design-System?node-id=1738%3A87787&t=s4um5an1sYgmGYxp-1)

**Comment by EWashb** [comment]
Change "Related" to "Related Articles"

And move the last saved by an editor block to the right nav. It shouldn't be stuck at the bottom
