### ISSUE TITLE
IE11: Track KPIs to determine when Alert can be removed

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#9398]
## Acceptance Criteria
- [ ] Track change from baseline in GA as % of desktop visitors - https://analytics.google.com/analytics/web/#/report/visitors-browser/a50123418w177519031p176188361/

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by jilladams** [comment]
went with an arbitrary date of 9/29. Closing.
