### ISSUE TITLE
Define plan to address LH facility service audit

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#9406]
## Description
[Slack Discussion](https://dsva.slack.com/archives/C02BTJTDFTN/p1654864140104429)

[atc_cms_service_comparison.xlsx](https://github.com/department-of-veterans-affairs/va.gov-cms/files/8879126/atc_cms_service_comparison.xlsx)

## Acceptance Criteria
- [ ] Plan on what to do with discrepancy

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by swirtSJW** [comment]
https://docs.google.com/spreadsheets/d/19Gihg32Fifu3FW4y0nMIeVUUbjcXYIzsbV7-B34JzsE/edit#gid=1839316337

**Comment by davidmpickett** [comment]
Converted the Google sheet into an Excel doc for future-proofing this ticket
[ATC _ DST _ CMS service comparison.xlsx](https://github.com/department-of-veterans-affairs/va.gov-cms/files/15167927/ATC._.DST._.CMS.service.comparison.xlsx)

**Comment by mmiddaugh** [comment]
Work to audit this data is in progress - closing this issue now in favor of any tasks which result
