### ISSUE TITLE
Conditional field values on events call to action can create weird state

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#9410]
## Describe the defect
This bug is one of those things that has a low occurrence  and is actually two bugs in one.
First reported by the [Link checker in slac](https://dsva.slack.com/archives/C030F5WV2TF/p1654885592430089)k 

## To Reproduce
1. Go to https://staging.cms.va.gov/node/add/event
2. Fill out all required fields
3. Click the box for "Include registration information" 
4. Select an option other than "none" for Call to action.
5. Put in a url
![image](https://user-images.githubusercontent.com/5752113/173142677-562beea1-636e-4ea5-a0b8-2920a1c07a95.png)

6. Change your mind and select `- None -` for "Call to action link"
The url field goes away, but it still has a value in it.
7.  (Defect 1)  Save the node and notice that the value even though there should be no call to action link, is still there.
8. (Defect 2) if this page were published and were followed by a content release, the link would show up as a button link used on the FE.
![image](https://user-images.githubusercontent.com/5752113/173143478-15cf7c3a-e382-496f-847e-3119f77f120c.png)

## Expected behavior
When you change your mind on conditionals, they remove the other field values.
![image](https://user-images.githubusercontent.com/5752113/173144319-c03d872e-a93d-429e-b2fb-2c488e77eed6.png)

 ## Additional context
If the changes are made at the CMS level then no changes should be needed on the FE.   The other possibility is to have the logic to track the conditionals more accurately, BUT that would lead to an odd editorial experience.

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Defect")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS workstream (orange) (not needed for bug tickets)
- [ ] CMS-supported product (black)

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by swirtSJW** [comment]
This bug has been present for a long time and has not surfaced before today.  So it is a low occurrence.   However it does highlight a FE defect that the FE is using the presence of values rather than the conditional logic to determine whether to show the link.

**Comment by jilladams** [comment]
Need a front end ticket to follow up and adopt the change out ofthis ticket.

**Comment by dsasser** [comment]
🟢  - Issue is well understood and conditional code has been located. I expect this to close this sprint.
