### ISSUE TITLE
Update "Content React Widgets" to drupal SSOT for Cerner cutover

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#9415]
## Description

(It turns out that) The content on the same benefit detail pages where the Cerner React Widgets live _is also in a react widget_. Documented [here](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/static-pages/health-care-manage-benefits).

These widgets currently consume the hard-coded API.

The benefits detail pages are the same ones where the widgets reside:
- refill prescription
- make appointment
- get VA medical records
- send secure message
- view lab or test results

## Timing

These widgets should continue to consume the hard-code API. So we can wait to switch them to the async API until that's stable in Prod.

### Some text to locate:

1. **get-medical-records-page**
    - Cerner:  "What are My HealtheVet and My VA Health, and which will I use?"
    - VistA: "What is VA Blue Button, and how can it help me manage my health care?"
2. **refill-track-prescriptions-page**
    - Cerner: "If you’re refilling and tracking prescriptions on My VA Health"
    - VistA: (above text does not appear)
3. **schedule-view-va-appointments-page**
    - Cerner: "How can these appointment tools help me manage my care?"
    - VistA: "How can the VA appointments tool help me manage my care?"
4. **secure-messaging-page**
    - Cerner: "Send or receive a secure message" (at very top, above CTA)
    - VistA: (above text does not appear)
5. **view-test-and-lab-results-page**
    - Cerner: "What are My HealtheVet and My VA Health, and which will I use?"
    - VistA: "How can this tool help me manage my health care?"

## Acceptance Criteria
- [ ] Content widgets consume the new Drupal-driven API for Cerner facility data.

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by ryguyk** [comment]
This functionality will switch over to Drupal source of truth at the same time as the CTA. If we want to not do that, we'll need to restructure some things.

**Comment by jilladams** [comment]
We need to confirm we know the proper content and verify that it appears correctly.
