### ISSUE TITLE
[SPIKE] Rework use of task, composer scripts, npm scripts, random shell scripts

### ISSUE THREAD

**Issue by cweagans** [department-of-veterans-affairs/va.gov-cms#9416]
## Description

We have lots of neat little bits of automation. Unfortunately, they are all scattered across different methods of actually running them. Let's put together one or more taskfiles to handle various tasks, remove one off scripts from composer.json, remove one off scripts from various package.json files, etc, and integrate with `.env` directly in our taskfile (so that we don't need things like `scripts/composer/EnvironmentHandler.php`.

We can also use task to download specific versions of dependencies like `node`, unpack them into a specific place, and put them into `$PATH` for any tasks defined in those task files.

The end goal here would be that the answer for "How do I _____?" (as related to doing development work on the CMS) would be "Run `task foo`".

Want to toggle xdebug for your local? `task local:xdebug:on` or `task local:xdebug:off`

Want to run cypress tests? `task test:cypress`

Want to refresh your local environment? `task local:refresh`

Want to run content build? `task frontend:build`

There are many, many more tasks that we expose through composer.json or other mechanisms, but we should boil them down a little bit, make the names descriptive, and make the commands environment-independent where possible (so that you can run `task frontend:build` (or whatever) on any environment and it'll just work).

## Acceptance Criteria
- [ ] Determine and document best approach forward
- [ ] Create followup tickets for implementation

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [x] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by cweagans** [comment]
If anyone takes this on, please feel free to reach out. I've got a ton of info that might be helpful.

**Comment by ndouglas** [comment]
This falls into the weird area of overlap between DevOps and QA and DX, but I'm guessing that this is gonna be me.  Which is fine because I created the taskfile nightmare and it bothers me. I'll be in contact 😎
