### ISSUE TITLE
SPIKE: Search Results pagination shows results for previous search

### ISSUE THREAD

**Issue by allisonlu** [department-of-veterans-affairs/va.gov-cms#9425]
## Describe the defect
After arriving on the Search Results page of VA.gov (via the Search drop-down in header), entering a different search query, then navigating to any page after 1, user will be redirected to a previous search query.

**Likely Front-end fix required,** though Drupal folk may be able to opine about some pieces. Tagged with both for now.

## To Reproduce
1. Go to VA.gov and enter any keyword/s (e.g. **message doctor**) in Search drop-down in the header. Note you will arrive at the Search Results page with no issues.
2. Enter a different keyword in the search field on the current Search Results page (e.g. **refill prescription**). Note you will arrive at page 1 with no issues. 
3. Scroll down and click on any page after 1. 
4. Note that you will be redirected to page 1 of the previous search (i.e. **message doctor**)

## Acceptance Criteria
- [ ] Backend / Frontend exercise to figure out ownership
- [ ] A new search query should produce new search results on all pages. 

## Screenshots

_Originally posted by @mmiddaugh in https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9308#issuecomment-1149158271_

https://www.loom.com/share/9ffc061e1efc430da558389e17db2265

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by chri5tia** [comment]
I was able to reproduce this issue.

1. Enter a search word in the text box and then enter the next search word on the page.
OR 2. Go directly to the search page, enter a key word and click another page, shows a blank page (like when you first go to it.)
![Screen Shot 2022-08-12 at 3 41 58 PM](https://user-images.githubusercontent.com/22764938/184453600-598ae254-bb31-4447-a372-a22ebff0da16.png)

Observations:
- no browser console errors
- search.gov product implementation
https://search.gov/developer/

-

**Comment by chri5tia** [comment]
- https://www.drupal.org/project/usasearch search.gov drupal module which is no longer supported, I don't see that this is being used though

- Webinar for getting started with search.gov: https://search.gov/get-started/training.html
- We need access to the search.gov account settings (who controls that?) It looks like a lot of the settings, customizations and even the URL va.gov/search are controlled by the account settings.

- Div container that the search results appear in, e2e:
<img width="566" alt="Screen Shot 2022-08-31 at 11 44 44 AM" src="https://user-images.githubusercontent.com/22764938/187756843-396cd81a-7121-4842-b201-54ab9f0378f6.png">

**Comment by allisonlu** [comment]
# Search pagination bug

During discovery, Christia and I have pinpointed that this bug has something to do with the React state not being updated correctly when the query changes.

However, Allison unable replicate bug locally.

## Steps to replicate (to make sure Allison isn't the only one experiencing this)

1. On your local `vets-website` repo, go to the following file: **src/platform/utilities/api/index.js**
1. Change line 57 from:
    ``` const baseUrl = `${environment.API_URL}/${apiVersion}`; ```
  to
    ``` const baseUrl = `https://api.va.gov/${apiVersion}`; ```
1. After spinning up your local server, perform a search and try to replicate the bug

## Relevant files

### `src/applications/search/containers/SearchApp.jsx`

lines 130–136:
```
  updateQueryInfo = options => {
    this.setState({
      currentResultsQuery: options?.query,
      page: options?.page,
      typeaheadUsed: options?.typeaheadUsed,
    });
  };
```

lines 250–254:
```
  handleInputChange = event => {
    this.setState({
      userInput: event.target.value,
    });
  };
```

### `src/applications/search/reducers/index.js`

lines 15–76
```
function SearchReducer(state = initialState, action) {
  switch (action.type) {
    case FETCH_SEARCH_RESULTS: {
      return {
        ...state,
        loading: true,
        results: undefined,
        recommendedResults: undefined,
      };
    }
    ...
  }
}
```

## Relevant issues + PRs

 - Very very similar issue to what we're dealing with now (fix search page number): https://github.com/department-of-veterans-affairs/vets-website/pull/9003
 - Add repeat search tracking PR: https://github.com/department-of-veterans-affairs/vets-website/pull/16513
 - General analytics request for Search & Discovery issue: https://github.com/department-of-veterans-affairs/va.gov-team/issues/20889
   - a lot of good QA notes

**Comment by jilladams** [comment]
@allisonlu @chri5tia do I understand right that this should be a front-end ticket to take it to next step / get a repro, and then fix?

**Comment by chri5tia** [comment]
This should be a front-end ticket, however, I want to know what team and what type of engineer is responsible for implementing search.gov? I would still be more comfortable being able to dig into our search.gov account and see how it's configured, how we tap into it etc, in order to understand the react state and rule out if it's on our end or search.gov. Is there a search.gov issue queue we can look at? Thoughts to put in the FE ticket.

**Comment by jilladams** [comment]
Filed #10819 for FE, and the overall Search.gov discovery now ticketed in #10768 should cover the BE description Christia provided.
