### ISSUE TITLE
[Events] Create an event that occurs on multiple days and times for a single event

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#9430]
## Description
As an event planner, I need to create an Event in the CMS that occurs on multiple days and times for a single event, as opposed to creating multiple versions of the same event (Requestor: VEO)

TO DO: 
- [ ] Collect use cases / example event parameters

## Acceptance Criteria
- [ ] Testable_Outcome_X
- [ ] Testable_Outcome_Y
- [ ] Testable_Outcome_Z
- [ ] Requires design review

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [X] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by FranECross** [comment]
Per Dave, there are workarounds and this is likely an expensive effort. If it bubbles up again, we can revisit.

**Comment by FranECross** [comment]
Closing old ticket; may resurrect as part of events v3 initiative, and if so, a new ticket will be created.
