### ISSUE TITLE
UX Discovery: Pull together any thinking about "Events near me" filter/tool for Veterans

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#9432]
## Description
The original VEO request is to: Add ability for user to filter events by location

TODO: 
- [ ] Determine: should this ticket be a part of #7490 effort?
- [ ] Determine: is this location filter envisioned on the Outreach Events page, where events only show if they are online? If not, on what page would this filter take place? 

## Acceptance Criteria
- [ ] Testable_Outcome_X
- [ ] Testable_Outcome_Y
- [ ] Testable_Outcome_Z
- [ ] Requires design review

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [X] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by jilladams** [comment]
I think this is a dupe of #9922 and can be closed. @fmccaf1  agree?

**Comment by fmccaf1** [comment]
Yes, I think you're right @jilladams
