### ISSUE TITLE
[Events] Add social media sharing platforms

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#9434]
## Description
Add social media sharing options on single event.

PM TODO: 
- [ ] Determine which social media outlets
- [ ] Verify/ modify scope / convert to epic once prioritized

DRAFT Scope: 
* Frontend design - placement on event pages
* Frontend eng

## Acceptance Criteria
- [ ] Testable_Outcome_X
- [ ] Testable_Outcome_Y
- [ ] Testable_Outcome_Z
- [ ] Requires design review

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [X] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by FranECross** [comment]
Closing per Dave C.
