### ISSUE TITLE
[Other] No VA.gov Experience Standard for the issue found. (00.00.1)

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-cms#9441]
#### VFS team name
Public Websites

#### VFS product name
Outreach & Events Enhancements

#### Point of Contact/Reviewers
Brian DeConinck (@briandeconinck) - Accessibility

---

### Platform Issue
No VA.gov Experience Standard for the issue found.

### Issue Details
When following a pagination link, the page scrolls back to the top but focus does not go back to the top. The next [Tab] stop is the footer, and users would need to tab backwards through the event list to move through the events.

### Link, screenshot or steps to recreate
1. Navigate to https://staging.va.gov/outreach-and-events/events/?selectedOption=past (filtering to display past events to ensure there are enough for pagination)
2. Use [Tab] to move keyboard focus through the list of events, and stop at the last event in the list.
3. Click a pagination link to move to another page.
4. Note that the page has scrolled back to the top.
5. Press [Tab]. Note that keyboard focus has stayed at the bottom of the page. The first tab stop is a link in the footer, forcing an unexpected change in view and context.

### VA.gov Experience Standard
[Category Number 00, Issue Number 00](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/VA.gov-experience-standards.1683980311.html)

### Other References

---

### Platform Recommendation
When clicking a pagination link, the page should set focus to "Displaying X of Y results" text with `tabindex="-1"`.

### VFS Team Tasks to Complete

- [ ] Comment on the ticket if there are questions or concerns
- [ ] Close the ticket when the issue has been resolved or validated by your Product Owner. If a team has additional questions or needs Platform help validating the issue, please comment in the ticket.

**Comment by laflannery** [comment]
[CMS Repo ticket here](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14755), when that ticket is closed, we can close this

**Comment by laflannery** [comment]
This has been resolved, closing
