### ISSUE TITLE
VAMC events listing & detail page: events location does not include Facility location

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#9442]
## Description
On VAMC Events, the location includes the Facility location itself.
On VAMC Event listings, the location does _not_ include the Facility, and should. 
When ticket was filed 6/14/22, the Location link appeared on event detail pages but not event listings.
On 6/28 test, the Location link no longer appears on event detail pages: 

**6/14 VAMC Event list:** 
https://www.va.gov/boston-health-care/events/?selectedOption=past
![Screen Shot 2022-06-13 at 6 01 21 PM](https://user-images.githubusercontent.com/85581471/173471857-61fd27f6-3845-4910-9ebb-7b7ba5c3f264.png)

**6/ 14 Single event:** 
https://www.va.gov/boston-health-care/events/46953/
![Screen Shot 2022-06-13 at 6 01 25 PM](https://user-images.githubusercontent.com/85581471/173471846-4eb4b213-35e1-4dac-81e2-7db9b6e3fee3.png)

**6/28 Single event:** 
https://www.va.gov/minneapolis-health-care/events/47378/
![detail page, location](https://user-images.githubusercontent.com/85581471/176322862-f8eb46e2-de51-4a3f-865a-fb95a19c077f.png)

![Screen Shot 2022-06-29 at 7 23 03 PM](https://user-images.githubusercontent.com/9059428/176572705-cfe1b51f-c011-47a3-a093-8b496001b0c2.png)

![Screen Shot 2022-06-29 at 7 01 00 PM](https://user-images.githubusercontent.com/9059428/176572722-3feacc92-e01d-42bc-a88a-d9b438822bf2.png)

![Screen Shot 2022-06-29 at 7 01 15 PM](https://user-images.githubusercontent.com/9059428/176573228-99df7c55-4d29-4d43-a43c-486b376c16c1.png)

## Live examples where this is happening across multiple VAMCs:
- **VA Bedford:** 
     - https://prod.cms.va.gov/bedford-health-care/events/47391
     - https://www.va.gov/bedford-health-care/events/47391/
     
- **VA Loma Linda:** 
     - https://prod.cms.va.gov/loma-linda-health-care/events/47421
     - https://www.va.gov/loma-linda-health-care/events/47421/
     
- **VA Tuscaloosa:** 
     - https://prod.cms.va.gov/tuscaloosa-health-care/events/47418
     - https://www.va.gov/tuscaloosa-health-care/events/47418/

## Acceptance Criteria
- [ ] Facility location appears on Event detail pages
- [ ] Event location on list matches single event

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [X] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by jilladams** [comment]
This has been further regressed somehow, and now facility link is not showing up on Event detail pages:

![detail page, location](https://user-images.githubusercontent.com/85581471/176322686-5ac9df1f-0f1b-4833-99a8-aa05a2c33c8e.png)

![cms location](https://user-images.githubusercontent.com/85581471/176322697-0dd34a6a-bc7f-4b6d-9159-7fe02ea4c8c9.png)
 
Updating ticket body.

**Comment by kevwalsh** [comment]
@jilladams I'm not sure if this fits in the geodata epic. Seems like it's actionable regardless of geodata.

**Comment by jilladams** [comment]
Noted. moving to Events generic epic.

**Comment by jilladams** [comment]
Also reported in https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9647, closed as a dupe.

**Comment by jilladams** [comment]
@maxx1128 the code changes here didn't surface the Facility info on Event listings:

![Screen Shot 2022-07-01 at 12 49 08 PM](https://user-images.githubusercontent.com/85581471/176960230-01c7ea0c-f2d5-4e27-b85d-24905f0e5ed3.png)

Not sure if I should reopen or cut a new ticket - thoughts?

**Comment by maxx1128** [comment]
@jilladams Event listings is a different code repo and likely a different solution, so I think it's better to cut a new ticket.

**Comment by jilladams** [comment]
thanks - done:
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9681

**Comment by stefaniefgray** [comment]
Author of ticket VAHELP-4350 wrote in wondering about this today
