### ISSUE TITLE
Create Collaboration Cycle RASCI

### ISSUE THREAD

**Issue by EWashb** [department-of-veterans-affairs/va.gov-cms#9446]
## Background

To begin the pseudo review and collab cycle process, we must formalize the checkpoints and levels of responsibility within the Sitewide CMS team. 

[WIP](https://docs.google.com/spreadsheets/d/1Nmd_tCpisJrxBYVYGtbU8UPgWOcy8hGY/edit#gid=1182457863)

## Acceptance Criteria

- [x] RASCI chart is created
- [x] Review with Program PM and PO for next steps

**Comment by ContentBrewmaster** [comment]
Google Sheet for RASCI created

**Comment by EWashb** [comment]
RASCI was mentioned to PO at Q3 planning. This should be turned into a larger initiative for a Collab cycle pilot program. This work will help inform the touchpoints during the pilot.
