### ISSUE TITLE
Recurring events: Add full recurring series to calendar

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#9451]
## Description
As a user, I want to add a recurring event series to my calendar.

Top level add to calendar link creates a single instance calendar item for next upcoming recurrence

## Current behavior
TBD whether this is expected behavior or a bug.

Event detail page w/ recurrences: Each recurrence detail page includes an Add to Calendar link. 
<details>
![Screen Shot 2022-06-14 at 1 24 32 PM](https://user-images.githubusercontent.com/85581471/173682036-a626686f-b914-47f0-8a39-afd06b6d75c7.png)
</details>

When [#9450](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9450) is resolved, the Recurrences pane will show each recurrence in the series, and an Add to Calendar link, as well. 
<details>
![Screen Shot 2022-06-14 at 1 09 24 PM](https://user-images.githubusercontent.com/85581471/173682428-078be96e-fda8-4159-b7ba-61a0d7c72c27.png)
</details>

Each of those Add to calendar links can be used to download an .ics file for importing the event into your calendar. Each will be the calendar item for a single instance of the recurring event. 

There is currently no mechanism in place to allow a user to Add the entire event series, with all recurrences, into calendar. 

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Defect")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS workstream (orange) (not needed for bug tickets)
- [ ] CMS-supported product (black)

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [X] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by jilladams** [comment]
Per Dave review during S61 planning, needs data to prove this is a user ask.

**Comment by jilladams** [comment]
Also: Per @swirtSJW , there is not a concept for this in the data in order to hand that to the front-end. Recurrences are data bits on a single event node, that can be modified after node creation. So if an editor makes an event, a user adds the recurring series to calendar, then the editor modifies an event instance, there is no effective way for the user with downloaded .ics to know of those changes. 

Additionally, the front-end doesn't have access to any sort of recurrence information -- it's all rendered out to standalone event date / times in the front end. 

If this is needed, we need deeper technical thinking around how to solve, and it is likely an XL effort.  @swirtSJW pls tack on any other notes we should have for future. (Or correct if I've misstated anything.)

**Comment by FranECross** [comment]
Closing as a no op.
