### ISSUE TITLE
Map the current state workflow for broken links

### ISSUE THREAD

**Issue by EWashb** [department-of-veterans-affairs/va.gov-cms#9452]
## Background

As surfaced in the broken links spike #8536, it is imperative for workflow improvements that we actually track the current state of the broken links within the editor workflow. The spike identified two ways to address broken links: presentation and detection. However, from a UX standpoint, it is challenging to address either without gaining empathy for the holistic editor workflow. 

Once the workflow is mapped, we can look at areas of opportunity to improve the experience, prevent editors from introducing broken links, and determine ways to surface the broken links when they occur. 

[Google slides](https://docs.google.com/presentation/d/1ZD2JEODG4z3zz_qHH--BSsz2EbhLdPyf/edit#slide=id.g107eb1bd42e_0_0) for VAMC context as of March 2022.

[2021 proposal for triage](https://docs.google.com/document/d/1K0D2226J9_WT3faDXQvn67khGUUWe6s3mhREdI5Am6c/edit#heading=h.2t4y4wgdl3ti)

[2019 broken links during prod deployments ](https://docs.google.com/document/d/1wCXkG1q_BnqfhHbjvkC9Qc9GE1QAamTiZELIkoGvigA/edit)

## User Story

As a CMS designer, I need to understand the editor's experience around broken links so that I might enhance and improve the editorial workflow process and provide guardrails to prevent errors in the CMS.
 

## Acceptance Criteria

- [x] UX spike on current state (include dev or info architect to assist) 
- [x] Map scenarios where broken links happen such as archiving content, publishing content with links to other content in draft, external links no longer valid, etc. 
- [x] Document the workflow
- [x] Identify areas of opportunity for UX improvements

**Comment by EWashb** [comment]
Some work has already been done in this [mural](https://app.mural.co/t/vagov6717/m/vagov6717/1654526125251/39f95935ad77b0e10723c701556de4ed2127f80f?invited=true&sender=ud7d3055567694e54f0133356).

**Comment by rachel-kauff** [comment]
[WIP flow sketched out in this MURAL](https://app.mural.co/t/vagov6717/m/vagov6717/1654526125251/39f95935ad77b0e10723c701556de4ed2127f80f?sender=rachelkauff7163)

**Comment by EWashb** [comment]
After determining what's possible to update the workflow, the entity usage module work being done in #9424 will give us some OOTB options for archival confirmation screens. 

Also, there are some low-hanging fruit options for updating entity usage messaging. We have determined a path forward and will pursue in early Q3.
