### ISSUE TITLE
Events Listing: Using Past events or custom date range filters for dates in the past shows duplicate event recurrences 

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#9454]
## Describe the defect
Listing: Using Past events or custom date range filters for dates in the past shows duplicate event recurrences 

e.g. 
https://www.va.gov/minneapolis-health-care/events/?endDateDay=19&endDateMonth=06&endDateYear=2022&selectedOption=custom-date-range&startDateDay=13&startDateMonth=06&startDateYear=2022

e.g.
https://www.va.gov/minneapolis-health-care/events/?endDateDay=14&endDateMonth=06&endDateYear=2022&selectedOption=custom-date-range&startDateDay=08&startDateMonth=06&startDateYear=2022

## To Reproduce
* Go to Outreach & Events listing, or a VAMC Event listing page (currently only seeing recurrences on VAMC events listings), e.g. https://www.va.gov/minneapolis-health-care/events/
* Custom date range: enter at least one date in the past, or filter by Past events
* See that events will appear with the same Title / date / time.
* Cross-check with the CMS node for that event, and see only a single instance of that event date / time, e.g. https://prod.cms.va.gov/minneapolis-health-care/events/42754

## Expected behavior
Past events or date filters showing past events should only show each recurrence one time.

## Screenshots

![Screen Shot 2022-06-14 at 1 54 28 PM](https://user-images.githubusercontent.com/85581471/173687228-adcaef8e-2d8d-4090-8c6c-49983f809165.png)

 ## Additional context
This example can be a little confusing, as the MN editors have worked around a recurrence limitation by creating 2 of the same events, with weekly recurrences on different days (Mon vs. Wed).
* Mon recurrence = https://prod.cms.va.gov/minneapolis-health-care/events/42754
* Thurs recurrence = https://prod.cms.va.gov/minneapolis-health-care/events/46932

You can test this in Staging for a more clear cut example of what happens for events with recurrences in the past, when using filters.

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Defect")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS workstream (orange) (not needed for bug tickets)
- [ ] CMS-supported product (black)

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [X] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by jilladams** [comment]
Per Dave review in S61 planning, low priority.

**Comment by jilladams** [comment]
This may also be resolved by #9456

**Comment by jilladams** [comment]
This was not resolved by #9456 
Repro: https://www.va.gov/central-iowa-health-care/events/?selectedOption=past
![Screen Shot 2022-07-06 at 11 31 44 AM](https://user-images.githubusercontent.com/85581471/177618959-b0b1c58e-84d0-42f4-91f1-6337cbc172b9.png)

Moving to stretch / next sprint as an option for FE people to pick up who are looking for work.

**Comment by maxx1128** [comment]
@jilladams I'm checking this locally and it's resolved for me. Is it possible the fix wasn't fully pushed to production?

<img width="1336" alt="Screen Shot 2022-07-06 at 2 39 59 PM" src="https://user-images.githubusercontent.com/10790736/177620339-360df860-12ad-4353-a0b0-3c1a05a33b8d.png">

**Comment by jilladams** [comment]
Yep, correct -- just confirmed and I had tested right before deploy completed. No longer repros for me - thanks for verifying! Sorry for churn. CLosing.
