### ISSUE TITLE
Remove unused field_facility_hours fields from facility migration

### ISSUE THREAD

**Issue by JayDarnell** [department-of-veterans-affairs/va.gov-cms#9465]
## Describe the defect

We recently replaced the old tablefield office hours solution on the VAMC Facility content type with a new office hours field. However, we neglected to remove the old field from the migration files we use to pull this data from Lighthouse. 

## To Reproduce

Open up docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_node_health_care_local_facility.yml and check lines 154-159. Anything referencing field_facility_hours should be removed as this field no longer exists.

## Expected behavior
- [ ] I expect to remove fields from the migration that no longer exist in the CMS
- [ ] I expect the migrations are run to validate the field removal 

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [x] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by kmariepat-cityfriends** [comment]
@jilladams this is a stretch sprint addition for sprint 80
