### ISSUE TITLE
Moderation state filter don't work as expected VAMC System Banner Alerts

### ISSUE THREAD

**Issue by JayDarnell** [department-of-veterans-affairs/va.gov-cms#9468]
## Describe the defect
If you attempt to view published **VAMC System Banner Alert with Situation Updates** on the Content or Content audit view, no results are returned. This is due to the fact this content type does not follow the typical editorial workflow of content elsewhere in VA.gov CMS:

<img width="859" alt="Screen Shot 2022-06-15 at 1 57 26 PM" src="https://user-images.githubusercontent.com/21045418/173893899-6dfcf1f6-814f-4f2c-88bd-305eed25d7c6.png">

## To Reproduce
1. Go to `/admin/content/audit`
2. Select **VAMC System Banner Alert with Situation Updates** for the Content type filter
3. Select **Published** for the Moderation state (Any selection here will actually break the results)
4. Click the Filter button
5. No results are returned

## Expected behavior
As a site user I would expect the **VAMC System Banner Alert with Situation Updates** content type to work with this view when a Moderation state is selected - like all other content types. However, due to the fact this content type doesn't use a typical workflow this cannot be. We already have a separate view specifically for alerts and statuses here: `/admin/content/vamc-alerts-and-statuses`

## Screenshots
![Screen Shot 2022-06-15 at 8 18 02 AM](https://user-images.githubusercontent.com/21045418/173868906-664dd0af-f6bd-4b38-93c9-13b23b96376e.png)

## Proposed resolution

1. Remove the option to select **VAMC System Banner Alert with Situation Updates** from this view

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [x] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by JayDarnell** [comment]
@kevwalsh @swirtSJW - while investigating this with help from @msbtterswrth I learned that we already have a separate view for alerts and statuses here: /admin/content/vamc-alerts-and-statuses

Should this view be moved within the admin navigation to display alongside the main content audit view: `/admin/content/audit`?

**Comment by kevwalsh** [comment]
Per [this slack thread](https://dsva.slack.com/archives/C0FQSS30V/p1655306480658889), i'm iceboxing this. 

* It's only really affecting admins (most editors are not using the Moderation State filter for their content. 
* the real solution is to apply content moderation to VAMC banner alerts, which should happen via #1392 epic

**Comment by Agile6MSkinner** [comment]
Closing since there's a better option available per comments.
