### ISSUE TITLE
VAMC system content model roadmapping

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#947]
## Description

Based on content research and content design for VA Pittsburgh health care, the VA.gov CMS team anticipates the need to add additional content model and governance structure to the VAMC system product in order achieve the following:

1. Ensure a **consistent end user experience across multiple VAMCs**
2. Provide additional **content governance** mechanisms, elevating certain reusable content to VHA HQ ownership, instead of expecting each VAMC to rewrite the same content repeatedly. 
3. Improve the **editorial experience**, making it faster to create content (with reusable content and some predefined structure)
4. Help **automate** the creation of new VAMC systems, by auto-generating additional pages required by each VAMC. 

This document is intended to serve as a roadmapping tool for cross-team collaboration between the VAMC upgrade team, VSA facilities team, and CMS team, with contributions from the VSP Content/IA team. 

## Background

We did some roadmapping in [Confluence and Jira](https://va-gov.atlassian.net/wiki/spaces/VAGOV/pages/145621071/VAMC+scaleability+extensibility), but our role has since changed. 

## Acceptance Criteria
* Various teams have a document that provides a shared understanding of possible enhancements to the VAMC system content model, so that they can prioritize and collaborate.

**Comment by kevwalsh** [comment]
@cmaeng @jefflbrauer @swirtSJW  I'd love to get your eyes on this before we share more widely https://docs.google.com/document/d/1UeJs_bZ5_9z4067ttsN7kVP-9R13COgjSpGRKVYh2iI/edit#

**Comment by jefflbrauer** [comment]
@kevwalsh This is an awesome document/roadmap. I think before we are able to begin on any of this, we need to resolve a major epic - - how content model changes are handled across the platform. We need to either expand/harden the feature flag process or come up with a completely new one (as you suggest manage 2 parallel models), AND document it completely. I think this needs to be its own epic, and something that has cross-platform prioritization and dependency mapping from @JeffBarnesUSDS and @KevinMHoffmanUSDS

**Comment by kevwalsh** [comment]
[Preparing VAMC system content model to scale - 2020-02-11.pdf](https://github.com/department-of-veterans-affairs/va.gov-cms/files/4198939/Preparing.VAMC.system.content.model.to.scale.-.2020-02-11.pdf)

This was shared with #vsa-faacilities slack on Feb 11th.
