### ISSUE TITLE
Events v2 filters: Update wording for Custom date range filter empty state

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#9477]
## Description
https://github.com/department-of-veterans-affairs/va.gov-team/issues/38157 created language for filter empty states: 

`vets-website/src/applications/static-pages/events/components/Results/index.js`
`No Events listed because filters are applied that exclude events from view` - appears when no events meet the Custom date range filter criteria
Per @cindymerrill  this language is not typical for how we talk to editors, and was likely created by the prior PW team, and not subject to Sitewide Content review. We should get it reviewed. 

In contrast, empty text for Specific date range shows as `No results found for **Specific date**`

### Possible solution
Logically, we could show `No results found for **Custom date range**` here instead.

### Screenshot

See small font at bottom of image.

<img width="528" alt="image" src="https://user-images.githubusercontent.com/4054752/173930197-380824ab-b4bc-4117-bd45-e2e24cd4d441.png">

## TO DO: copy approval

- [ ] Open Sitewide Content intake ticket
- [ ] Provide final copy on this ticket

## Acceptance Criteria
- [ ] Filtering by date range with no available events displays new empty text

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by jilladams** [comment]
@davidconlon would like to revisit this empty text, and confirm if you feel it warrants Sitewide Content review (If so, we'll cut ticket) or we can/should follow convention: 

- Current Specific date empty text = No results found for **Specific date**
- Current Custom date range empty text = No Events listed because filters are applied that exclude events from view
- Proposed update to Custom date range empty text = No results found for **Custom date range**

Reminder that current Custom date range empty text came from https://github.com/department-of-veterans-affairs/va.gov-team/issues/38157 where we previously said in Events scrub: it was likely language provided by Sitewide Content and we should keep it. Cindy questioned that assessment and felt it likely was _not_ reviewed by Sitewide Content and came direct from engineering, hence the new ticket.

**Comment by wesrowe** [comment]
@rlhecht, do you think this needs an intake ticket for your team? It seems maybe too small for the overhead. But LMK.

**Comment by jilladams** [comment]
Per Dave review, not a priority for Sitewide Content. (FYI @cindymerrill )

**Comment by cindymerrill** [comment]
@jilladams So just change it to "No results found for Custom date range"?

**Comment by wesrowe** [comment]
I would support that. Maybe Max could add it to one of his other PRs to limit exertion.

**Comment by cindymerrill** [comment]
Is this error message wording going to be changed to "No results found for Custom date range"? Just noticed that it's still "No events listed because filters are applied that exclude events from view" @jilladams

**Comment by wesrowe** [comment]
It hasn't yet been prioritized @cindymerrill.

**Comment by cindymerrill** [comment]
Oh, OK. Such a minor wording change that would really help users...

**Comment by allisonlu** [comment]
@wesrowe @jilladams assigning to myself

**Comment by allisonlu** [comment]
PR opened: https://github.com/department-of-veterans-affairs/vets-website/pull/21808

**Comment by allisonlu** [comment]
PR approved, let me know if we should merge in today (Friday) or wait until next sprint

**Comment by jilladams** [comment]
It can merge today after daily deploy.

**Comment by allisonlu** [comment]
PR merged!
