### ISSUE TITLE
Document Accelerated Publishing Journey

### ISSUE THREAD

**Issue by jkalexander7** [department-of-veterans-affairs/va.gov-cms#9488]
## User Story or Problem Statement

Consolidate all documentation pertaining to Accelerated Publishing, including phased approach, decision points, and ADRs, at request of Jeff Barnes.

## Acceptance Criteria
- [x] Create an updated, comprehensive guide detailing the AP journey is published in Confluence
  - Include phased approach, decision points, FAQs and relevant takeaways from ADRs. Consider audience in document voice
  - https://vfs.atlassian.net/wiki/spaces/PCMS/pages/1939931137/Accelerated+Publishing+Initiative
- [x] Include an executive summary of current state
  - See top of document above.

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [x] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by ENeal49** [comment]
Details on the ask from the Demo recording:
1. high level decision document
2. how we got to this decision
3. why better than what we have
4. how does it solve our problem
5. this will specifically be for Jeff Barnes as well as being able to point others to something for more information

**Comment by timcosgrove** [comment]
Collecting links to existing AP documentation here for the moment: https://vfs.atlassian.net/wiki/spaces/~489383718/pages/2240708838/Accelerated+Publishing+documentation

There is quite a lot of it in varying states.

**Comment by timcosgrove** [comment]
The overview and Journey is published here: https://vfs.atlassian.net/wiki/spaces/PCMS/pages/1939931137/Accelerated+Publishing+Initiative

Documents relating to AP are scattered in several places. These will be pulled into Confluence and organized. That collection is here: https://vfs.atlassian.net/wiki/spaces/PCMS/pages/2240708838/Accelerated+Publishing+documentation+collection
