### ISSUE TITLE
Create repeatable report of accessibility issues within Sitewide Crew products

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#9493]
## Description

In order to ensure we are making improvements to accessibility within the Sitewide crew portfolio, we need to establish a consistent approach to reporting errors.

There are a variety of reports already available to us, but none currently match perfectly to the scope of the Sitewide Crew's responsibility

- Axe testing performed during the content build 
- Siteimprove (may be limited to VAMC websites?)
- Crawls performed by Mike G
- others

Other things tha tmay be useful
- www.va.gov/sitemap.xml, which corresponds loosely to what content is modernized, but also includes products that are not in Sitewide Crew portfolio. (Although, 90%+ of the URLs are managed by Sitewide Crew)

## Acceptance Criteria
- [ ] We've analyzed various reporting tools available to us and found a means to regularly reproduce reports that are can be used for tracking changes to accessibility of products within the Sitewide product portfolio

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [x] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by EWashb** [comment]
Will need further refining with PO

**Comment by EWashb** [comment]
This should be backend focus. The FE is already being handled. We need some sort of check (post-deploy each day?) that validates the interface is compliant with 508.

**Comment by EWashb** [comment]
close this one and create 2 tickets:

- CMS is 508 compliant
- how do we ensure editors are creating accessible FE experiences

**Comment by laflannery** [comment]
Closing issue and replacing with 2 new ones:
- #10273 
- #10274
