### ISSUE TITLE
Notices on Vet Center (and maybe elsewhere)

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#9496]
## Describe the defect
Multiple pairs of Notices appear on vet center pages
```
Notice: Undefined index: #description_display in template_preprocess_fieldset() (line 219 of core/includes/form.inc).
Notice: Undefined index: #description_display in template_preprocess_fieldset() (line 220 of core/includes/form.inc).
```

![image](https://user-images.githubusercontent.com/5752113/174138072-05ab35ab-b867-4f5b-a302-86aafe6bbe80.png)

Slack [conversation here](https://dsva.slack.com/archives/CT4GZBM8F/p1655336560212579)
## To Reproduce
1. Go to '[/northern-maine-vet-center](https://dev.cms.va.gov/node/3615)` on local, tugboat or dev  (notices are not displayed visibly on staging or prod) 
2. Click on on the edit tab.
3. Save the node 
4. see notices.

OR 

1.  Go to https://dev.cms.va.gov/node/3615/latest
2. See notices

## AC / Expected behavior

Notices are never good.   We should not have them.

 ## Additional context
Anecdotal but I see 4 sets of notices and 4 accordion paragraphs.  Not necessarily related.

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Defect")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS workstream (orange) (not needed for bug tickets)
- [ ] CMS-supported product (black)

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by amonoxia** [comment]
Looks like a preprocess hook is firing for something that is no longer in the database schema. Have we run database updates (drush updb)?

**Comment by amonoxia** [comment]
Are we using Migrate Tools? https://www.drupal.org/project/migrate_tools
Patch or update module: https://www.drupal.org/project/migrate_tools/issues/3272434

Role Expose? 
Patch: https://www.drupal.org/project/role_expose/issues/3268099

Did this start happening after upgrading drupal core version?

**Comment by swirtSJW** [comment]
The migrate tools is an interesting find.   I am not sure that's the cause as we migrated these in years ago and have not seen the message until now.  xdebug will likely tell us specifically where its coming from.

**Comment by JayDarnell** [comment]
I believe this is actually a bug with the field group module. After doing some testing locally I found that the offending items were the **Prepare for your visit** and **Featured Content** field groups. Walking through the code, the issue is caused by the fact that these two field groups are displayed as field sets with descriptions provided. The template_preprocess_fieldset() function in docroot/core/includes/form.inc expects the form element to have a #description_display array index anytime a #description array index is provided but field_group using the fieldset display does not. 

I'm testing this patch now: https://www.drupal.org/project/field_group/issues/3053242

**Comment by JayDarnell** [comment]
Local testing shows the patch I rerolled as fixing the error but there are built-in tests within the module that probably need to be updated as well for it to pass testing on D.O. I'm not sure if I should be tackling that now or if we leave that for the module maintainer to address. I guess I'll wait to see what our local tests show.
