### ISSUE TITLE
Define roles and responsibilities of Sitewide Crew accesssibility lead

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#9498]
## Description

As a Sitewide accessibility lead, I need an understanding of the accessibility landscape
- at VA
- within OCTO-DE
- within the Sitewide crew

so that i know who's who, and understand the scope of the Sitewide vs other teams with respect to improving accessibility of VA.gov

As a member of the OCTO-DE accessibility practice area (team?), i want to understand the role and responsibilities of the Sitewide Crew accessibility lead, so that i know how to include them in various initiatives. 

## Acceptance Criteria

TBD
- [ ] Maybe: A RACI chart showing roles and responsibilites of various VA.gov accessibility team members, with respect to Sitewide Crew products? 

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [x] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by laflannery** [comment]
I have a document where I have gathered my notes regarding the accessibility landscape but I probably need assistance in how best to present this.  I do not know what a RACI chart is, but I could also potentially edit [this mural](https://app.mural.co/t/vagov6717/m/vagov6717/1655383090408/4d4957dbe9fc3a31ce45f280b1188fa8cdf7dc24?sender=kevinwalsh8610) as well

**Comment by laflannery** [comment]
I created a [new mural](https://app.mural.co/invitation/mural/vagov6717/1656428782190?sender=u7b64a74b9cf6665b97aa3816&key=f8dced74-6c15-4964-a3d0-276a8850fa74) to visually display the various accessibility teams & resources within the ecosystem

**Comment by EWashb** [comment]
This looks good @laflannery! We can share with the PO at our next call. Also, we can decide if it is worth demoing once we chat with him
