### ISSUE TITLE
Get access to various accessibility testing tools as needed

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#9500]
## Description

We think there are certain pro accounts including [axe DevTools Pro](https://axe.deque.com/axe-devtools/plans) that will help moving forward with Sitewide accessibility needs. 

## Acceptance Criteria
- [ ] Laura (anyone else?) has access to all tools and as needed

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [x] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by EWashb** [comment]
@laflannery do you have what you need as specified in this ticket?

**Comment by laflannery** [comment]
I do for now, so we can close this
