### ISSUE TITLE
[airtable-config-sync] GitHub Actions Workflow is created to sync the "VA.gov CMS content model documentation" Airtable Base on an hourly basis"

### ISSUE THREAD

**Issue by ElijahLynn** [department-of-veterans-affairs/va.gov-cms#9506]
## Description
See parent epic at https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9497.

## Acceptance Criteria
- [ ] GHA workflow is created to sync the CMS configuration from the `main` branch to the "VA.gov CMS content model documentation" Airtable Base on an hourly basis

## Implementation Notes
* Will need an Airtable API key
* API key needs to be available in GHA, from Param Store
* The first story to do when this is ready is here https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9505

**Comment by EWashb** [comment]
This will likely not be needed once #12240 is completed
