### ISSUE TITLE
Add drush commands for create and delete

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#9510]
**Background**
We use drush to automatically manage site alerts & shields around deployment messaging.

- [pre-deploy alert](https://github.com/department-of-veterans-affairs/devops/blob/793326c6d6a6075ecaee746a129203da6f0a2dfe/ansible/cms-test/cms-site-alert.yml#L33)
- [site shield during deployment](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/cms-test/tasks/pre-deploy-tasks.yml#L17)
- [post-deploy alert](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/cms/cms-deploy-live.yml#L28)

Before we can use the Sitewide Alert module instead of Site Alert, we need feature parity on the drush commands.

Upstream issue on D.o [created here](https://www.drupal.org/project/sitewide_alert/issues/3290964). 

**ACs**
- [ ] Patch available on the issue above that adds drush commands to create & delete, enable and disable sitewide alerts.

**Comment by tjheffner** [comment]
Initial patch added here: https://www.drupal.org/project/sitewide_alert/issues/3290964#comment-14583559
