### ISSUE TITLE
Alter devops process to use Sitewide Alert commands

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#9511]
- [pre-deploy alert](https://github.com/department-of-veterans-affairs/devops/blob/793326c6d6a6075ecaee746a129203da6f0a2dfe/ansible/cms-test/cms-site-alert.yml#L33)
- [site shield during deployment](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/cms-test/tasks/pre-deploy-tasks.yml#L17)
- [post-deploy alert](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/cms/cms-deploy-live.yml#L28)

The maintenance page will also likely need to be updated to match class names that have changed. https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/docroot/sites/default/maintenance.html

[Details about the process originally posted here](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/7436)

**Comment by tjheffner** [comment]
PR for the devops changes is here: https://github.com/department-of-veterans-affairs/devops/pull/11537
