### ISSUE TITLE
Uninstall site alert module

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#9513]
After #9512 and #9511 are done and sitewide alerts are taking the place of existing site alert, we should uninstall the site alert module.

**Comment by ndouglas** [comment]
Unassigning Tanner and assigning myself per discussions 🙂

**Comment by ndouglas** [comment]
After confirming that the new sitewide-alerts are working on prod and the training environments, I zapped the existing site alerts so we won't run into an issue at deployment.  I'll open a PR now.
