### ISSUE TITLE
Remove site alert module from codebase

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#9514]
After the site alert module has been uninstalled, we should remove it from composer and any references to site alert config/functionality should be updated as appropriate for the new module. Much of the information is likely to be relevant still, maybe a slightly different admin path or two for actually adding or managing alerts.

**Comment by ndouglas** [comment]
Unassigning Tanner and assigning myself per discussions 🙂
