### ISSUE TITLE
Prep for Facility COVID status research

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#9522]
## Description

What challenges are VAMC facilities facing rolling out the Facility COVID status with nationally standardized language?

### Approach
- interview VAMC Public Affairs Officers and others responsible for editing facility information
- coordinate effort with VHA Digital Media

Questions we want to understand:
- do PAOs (and by extension, their leadership) understand the goals of the national initiative
- solicit feedback about the three standardized messages
  - what are the challenges they have with the text, and what's good about it 
  - what impact is this having on staff, like increased call volume, confusion
  - what's missing from the messages
  - does the field understand what VHA national is trying to achieve
  - what feedback have they received from Veterans
- how does the level of effort relate to this experience for PAOs? 

## Scope and outcomes
The scope of this research will focus on the digital aspect of this initiative and the content governed in Drupal, not the UI for editors. We may hear about other related aspects of the Facility COVID status initiative, such as the posters required for building points of entry. 
- We also will capture any editor comments as additional findings related to the broader editorial experience using the approach used for the [harassment tool research](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/harassment-reporting/research/static-landing-page/research-findings.md#key-findings)
### Outcomes
- We have a broad understanding of the issues created by the COVID-19 facility status messaging introduced in May 2022 for editors
- We have context for future features on products with editors in the field

## Acceptance Criteria
- [ ] Research plan is approved by PO
- [ ] Research plan is posted to github
- [ ] Conversation guide is approved by PO
- [ ] Conversation guide is posted to github

**Comment by valerierunde** [comment]
@kevwalsh Some thoughts on this, per our conversation:

6/21 - 6/24: Suzanne to refine editor research process (can probably lift much of already-established Veteran process)
6/27 - 6/28: Suzanne and Denise co-work on research plan (recommend unmoderated studies due to timeline).
6/29: Plan to be approved by Dave
6/30 - 7/1: Unmoderated research study goes out.
7/5 - 7/8: Suzanne and Denise co-work on synthesis and readout deck
W/O 7/10: Denise leads readout, Suzanne helps to refine where editor research lives in the long term

Note that both Juneteeth and July 4th fall within this window of time so we're losing two days, plus Denise's normal days off. In total, this research would take ~13 working days (1.5 sprints)

**Comment by davidmpickett** [comment]
Per slack thread yesterday, I am on-call to assist with interviews

**Comment by ContentBrewmaster** [comment]
Updated timeline per Research Plan:
June 28:  
CMS Facilities research team to share research plan with OCTO-DE and OHT for input 
VHA DM to identify 12 potential participants for interviews 
June 29: CMS Facilities research team to start scheduling participants for interviews while starting conversation guide draft 
July 1 - 8: Interviews with PAO participants 
July 11-15: Synthesis of research findings, including data from help desk, and development of readout deck and recommendations for discussion with OCTO-DE Product Owner Dave Conlon 
July 21: readout of research findings and recommendations with Dave Conlon, Danielle Thierry, and representatives from VHA Digital Media and OHT

**Comment by kevwalsh** [comment]
@ContentBrewmaster @suzanne-gray  now that this is 3 sprints, i wonder if this should be 3 different tickets. 

this one for writing the plan. 
Sprin 62: interviews and and synthesis
Sprint 63: readout.

**Comment by suzanne-gray** [comment]
made this a prep-only ticket and updated ACs.

**Comment by kevwalsh** [comment]
I'm closing this, because prep is very much done.
