### ISSUE TITLE
Update cookie to always activate injected header on VA Enterprise Architecture Home

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#9525]
## Description
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9524 adds http://ea.oit.va.gov/ to allow lists that gate the injected header. When the VA Enterprise Architecture Home team confirms their testing is complete, we will need to 

- [ ] update [proxy-rewrite-whitelist.json](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/proxy-rewrite/proxy-rewrite-whitelist.json) code to `cookieOnly: false ` to permanently display the header 

## Acceptance Criteria
- [ ] Devops PRs from #9524 to add non-www domain have merged
- [ ] VA EA team (Sagar Patel)  has signed off that they're ready to publish
- [ ] On http://ea.oit.va.gov the global header is injected on page load, with no cookie updates required

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [X] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by jilladams** [comment]
VA EA are still testing / Sagar Patel hasn't confirmed prod-readiness. May not launch in S62. Will flag in mid-sprint checkin.

**Comment by jilladams** [comment]
Sagar approved via email just now.

**Comment by allisonlu** [comment]
PR opened: https://github.com/department-of-veterans-affairs/vets-website/pull/21709

**Comment by allisonlu** [comment]
Changes merged! Will confirm that injected header is showing up when deploy goes out today

**Comment by allisonlu** [comment]
Injected header is showing up on both https://www.ea.oit.va.gov/ and https://ea.oit.va.gov/ !
