### ISSUE TITLE
Connection between Vet Center satellite locations in FL search results and Vet Center pages

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-cms#9534]
## Issue Description
Vet Center MVP pages are designed intentionally lean and have only two pages: Main and Locations. Affiliated satellites are available in VAST, are included in FLocator search results but do not have dedicated pages. They are displayed on the Locations page of the main Vet Center with which they are affiliated. 

This is relevant to published Vet Centers only (although all Vet Centers will be published by end of Q3 2022)

Problem: When a Veteran clicks on the name of an outstation in FLocator search results, they are connected to the Main Vet Center page which may be disorienting. 
For example, [a search for Vet Centers in Clarksville](https://www.va.gov/find-locations/?page=1&address=clarksville&facilityType=vet_center&serviceType&latitude=36.5286&longitude=-87.3099&radius=28&bounds%5B%5D=-88.0599&bounds%5B%5D=35.7786&bounds%5B%5D=-86.5599&bounds%5B%5D=37.2786&context=Clarksville%2C%20Tennessee%2C%20United%20States) returns the Clarksville Outstation. Clicking on the name takes the Veteran to the [Nashville Main Vet Center page](https://www.va.gov/nashville-vet-center/). A better flow might be to direct them to the [Nashville Vet Center _**Locations**_ page](https://www.va.gov/nashville-vet-center/locations/), where the Clarksville Outstation is displayed. A bonus to this is that other locations, such as Community Access Points are also displayed, such as the Bowling Green location, which is closer to Clarksville than Nashville and could be the most convenient location for the searching Veteran to receive services. 

This will also be important when CAPS are _(eventually)_ included in FLocator search results. 

<details>
<summary> Screenshots </summary>

![image](https://user-images.githubusercontent.com/55411834/149205478-d4aa5cae-50d5-469a-b089-ded0da7d4543.png)

![image](https://user-images.githubusercontent.com/55411834/149205581-ce931769-034c-4c99-8594-deba725fabfe.png)

![image](https://user-images.githubusercontent.com/55411834/149205704-37a28ef9-dd7c-4043-84d8-ab0f26774482.png)

</details>

_Question: are we able to add deep links/anchor links so we can take the Veteran straight to the location chosen from the search results, rather than just to the Locations page?_ 

---
## Tasks
- [x] ~~Adjust redirects for affiliated outstations of published Vet Centers~~ (Christian): Change the canonical URLs for published outstations to deep link to the outstation on the locations page of a published Vet Center page
## Acceptance Criteria
- [x] When a Veteran clicks on the name of a satellite Vet Center Location, they are directed to the Locations page of the affiliated Vet Center.

**Comment by omahane** [comment]
I have made this request of Lighthouse via Slack: https://app.zenhub.com/workspaces/vagov-sitewide-product-team-6645154188a81a1f7a0a9464/issues/gh/department-of-veterans-affairs/va.gov-cms/9534

**Comment by jilladams** [comment]
Convo that led to adding this to sprint 7: https://dsva.slack.com/archives/C02730UEZPS/p1719585916276039

**Comment by jilladams** [comment]
CSV changes haven't been deployed yet. 

To verify Solano once LH says CSV is updated:  
* Go to https://www.va.gov/find-locations/?page=1&address=94534&facilityType=vet_center&serviceType&latitude=38.258344&longitude=-122.067489&radius=16&bounds%5B%5D=-122.817489&bounds%5B%5D=37.508344&bounds%5B%5D=-121.317489&bounds%5B%5D=39.008344&context=Fairfield%2C%20California%2094534%2C%20United%20States
* Click "Solano" title
* Before change, it pointed to facility locator detail page: https://www.va.gov/find-locations/facility/vc_6021OS
* After deploy, should point to: https://www.va.gov/concord-vet-center/locations/#solano-county-vet-center-outst

**Comment by jilladams** [comment]
Noting: that's also being tracked sort of in #17797 so if this ticket gets verified to close, we can close that one too
