### ISSUE TITLE
Improve display of, and user flow for, Vet Center Satellite Locations in Facility Locator

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#9535]
### User Story or Problem Statement

As a Veteran, I want to see satellite locations, including Community Access Points, where VA services are offered, so that I can visit the location closest/most convenient to me.

If i want more information than what is visible in Facility Locator, i want to be able to find it on VA.gov  (#9534)

**Comment by davidmpickett** [comment]
Here's an example. The Princeton Vet Center in West Virginia has [4 satellite locations](https://www.va.gov/princeton-vet-center/locations/). When searching on Facility Locator, only the main location shows up:
![facility locator](https://user-images.githubusercontent.com/51967950/209989865-c015951d-fd09-491a-ace2-1546130da5fe.png)

But if the data sources for the satellite locations were connect to Facility Locator, you be able to see 5 locations in that region (made with a [quick google map list](https://goo.gl/maps/k9QQvhKJ8DWwq6xeA))
![with_satellite](https://user-images.githubusercontent.com/51967950/209989988-d8f8bc21-da87-4e00-9ce0-07728cbd34e0.png)

**Comment by davidmpickett** [comment]
@JQuaggles added a quick example of what I think the goal is here. Not sure where this falls on the long-term product roadmaps for Vet Centers & Facility Locator. 

It has not been a priority during my time here. It's possible that Kev was spinning this up epic during Q3 planning conversations but then the stars align for VBA and this never got fleshed out.

**Comment by davidmpickett** [comment]
@Agile6MSkinner I suggest moving remaining tickets into #15712 and closing this epic

**Comment by Agile6MSkinner** [comment]
Done
