### ISSUE TITLE
Update cms.va.gov TLS certificate

### ISSUE THREAD

**Issue by jkalexander7** [department-of-veterans-affairs/va.gov-cms#9538]
## User Story or Problem Statement

The cms.va.gov TLS certificate expires Aug 1, 2022. 
Ref: https://dsva.slack.com/archives/C37M86Y8G/p1654530979771929

The second portion of this needs to wait until we can get on the horn with the IAM team and update our certs with them.

## Acceptance Criteria
- [ ] TLS certificate is updated by Jul 31, 2022 11:59p EST.

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [x] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by ElijahLynn** [comment]
docs on how to do this are here >> https://vfs.atlassian.net/wiki/spaces/OT/pages/1787953328/Venafi%3A+Create+and+download+TLS+certificates

**Comment by ndouglas** [comment]
Needs this too (surprise!): https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/platform/cms/cms-sso-saml-iam-login-how-to.md

**Comment by ndouglas** [comment]
The SSO side of things will be handled separately, in #9728.
