### ISSUE TITLE
System page shows featured event that isn't featured

### ISSUE THREAD

**Issue by ethanteague** [department-of-veterans-affairs/va.gov-cms#9549]
## Description
https://www.va.gov/minneapolis-health-care/ shows a featured event that is not featured

## Acceptance Criteria
- [ ] Go to https://www.va.gov/minneapolis-health-care/ and visually verify featured events section no longer appears (no featured events, so expected outcome is for this section to go away)

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by jilladams** [comment]
Decision to close this / background: https://dsva.slack.com/archives/CT4GZBM8F/p1656014625552849?thread_ts=1655835746.501589&cid=CT4GZBM8F

**Comment by swirtSJW** [comment]
@kevwalsh  @jilladams  This PR is still hanging out. https://github.com/department-of-veterans-affairs/content-build/pull/1181   Should we close it?

**Comment by jilladams** [comment]
Yes. We determined that's not the right fix.
