### ISSUE TITLE
MVP CMS Notifications Research

### ISSUE THREAD

**Issue by EWashb** [department-of-veterans-affairs/va.gov-cms#9551]
## Background

Reevaluation of CMS notifications in Q3 2022 has determined that outdated content notifications would serve as a better starting point than broken links. This stems from VA directive 6102. While the specific notification type has changed from broken links to outdated content, the baseline research to determine notification preferences of editors is still valid.

~Through CMS notification emails, we will look into how broken links can be surfaced to editors in a way that allows them to fix the issue, but also learn how to rectify the issue going forward. The MVP audience for this research has been determined in #9552 as a small subset of editors (4-5)~

Some other things to consider as we conduct the research, while not MVP, could be helpful to gauge clarity through research questions:

- How editors prefer to get notified
- Their thoughts are on emails

Because of the variety of unknowns in the current state, we should do some preliminary research to establish a baseline understanding of notifications for editors. 

## Assumptions

- We assume that the notification needs will be different across products.
- We assume that editors will have preferences for frequency.
- We assume that too many CMS notifications defeat the purpose of having them and we should be judicious with their use. 

## Definition of Done
- The Sitewide CMS team understands how editors use email notifications
- The Sitewide CMS team determines that outdated content is being review as a result of notifications
- Lessons learned are curated, synthesized, and shared with PO
- The Sitewide CMS team can use notifications to inform editors on the types of things to complete as a review of their content
- The Sitewide CMS team understands how to iterate on the notifications MVP

**Comment by EWashb** [comment]
Survey about how people would like to be notified and when. Need to refine the hypotheses and validation of assumptions.

**Comment by rachel-kauff** [comment]
> Need to refine the hypotheses and validation of assumptions

^^ assumptions about notifications being effective at helping editors resolve broken links

**Comment by EWashb** [comment]
Feedback from PO- Email needs to be MVP

**Comment by EWashb** [comment]
Further refinement has determined the best editor group will be Health Hubs.

**Comment by EWashb** [comment]
This pilot program is not currently within scope. We are pivoting our pilot program away from broken links and into compliance with directive 6102. I am going to close this epic focused on broken links in favor of a new epic on the new MVP.

**Comment by EWashb** [comment]
I'm going to reopen and refine for current scope of outdated content (not broken links)

**Comment by EWashb** [comment]
Research is now complete and added to the research repo
