### ISSUE TITLE
Discovery: MVP audience for CMS notifications pilot

### ISSUE THREAD

**Issue by EWashb** [department-of-veterans-affairs/va.gov-cms#9552]
## Background

The Sitewide CMS team should determine an MVP group of editors to test CMS notifications. There are various products and editor groups that could serve as MVP. However, we should discuss the strategy with our PO and determine the best path forward. 

## Acceptance Criteria

- [x] Schedule meeting with PO to discuss MVP notifications group
- [x] Determine MVP audience for notifications pilot

**Comment by rachel-kauff** [comment]
Actionable vs passive notifications
- Actionable = broken (need to fix)
- Passive = a thing is published (need to be aware)


Ideas of things people might want:
- when something is published
- when something gets archived
- when a new editor gets added to my section
- when when something goes live on va.gov
- when something is moved to in review
- when I need to complete a task that has been set by a higher authority (e.g. covid status / VHA)

[something] I've...
- edited
- authored

**Comment by rachel-kauff** [comment]
[WIP ideas sketched out in this mural](https://app.mural.co/t/vagov6717/m/vagov6717/1640279128158/2e77b10c5839bdce1d76a2d975dd93b146aff288?sender=rachelkauff7163)

**Comment by EWashb** [comment]
Meeting with PO scheduled for 7/13

**Comment by EWashb** [comment]
next steps:

-shortlist of VAMC systems for the pilot (aim for 2-4 VAMCs for the pilot)
-Shortlist reps across VISNS
-PO approval
-VHADM approval (have them participate in the selection of the shortlist and make sure the people have the capacity and buy to be successful) 
- run through CM RASCI
- Github integration for the RASCI chart
