### ISSUE TITLE
CMS Notifications Research: Research Plan

### ISSUE THREAD

**Issue by EWashb** [department-of-veterans-affairs/va.gov-cms#9553]
## Background

MVP for CMS notifications will be email to a pre-selected editor base. The research plan for this pilot program will include a prototype and user interviews to determine how editors prefer to be communicated with and what sorts of notifications they would like to see in future state notifications. We will need to create a prototype of the email for the research.

## Acceptance Criteria

- [x] Identify duration of study and the milestones
- [x] Research plan written
- [x] Research plan added to research repo

**Comment by EWashb** [comment]
Need the prototype to block this.

**Comment by EWashb** [comment]
Also, we need to think through the scenarios that we will be presenting. Would also like to understand from the research- what's the smoothing process, how do we not overwhelm them with a lot of outdated content

**Comment by BlakeOrgan** [comment]
The research plan for CMS Notifications is complete and can be found [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/research/CMS%20Notifications/Notifications-Research-Plan.md).

A couple of notes to address the AC and updates to the comments @EWashb made above.

- Prototype/mockup of emails is no longer a blocker for this ticket. The mockup and conversation guide will be completed next sprint and Dave C. is okay with that.
- We're planning on conducting interviews during Sprint 73 (December 5-16, 2022).
