### ISSUE TITLE
CMS Notifications Research: Conversation Guide

### ISSUE THREAD

**Issue by EWashb** [department-of-veterans-affairs/va.gov-cms#9554]
## Description

Create a conversation guide to use during CMS notifications research. 

- [Editor-facing Conversation Guide Template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/research/editor-moderation-guide.md)

Suggested workflow:
- [x] Create your initial drafts in Google Docs for collaborative editing
- [x] Solicit feedback on artifacts from Design Team and Product Manager
- [x] Schedule a 1-hour meeting with the Product Owner to review artifacts (also invite Product Manager) 

## Acceptance Criteria
- [x] Identify Moderator(s), Notetaker(s), and Obeserver(s) 
- [x] Identify timeslots for research sessions (should be 2 times as many slots as # of desired participants)
- [x] Convert artifacts to markdown format and store in github Research Folder

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [x] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by davidmpickett** [comment]
@EWashb @BlakeOrgan I copy and pasted the content of the "Draft Research Plan & Conversation Guide" template here and just removed the stop that was specific to the research plan. Not sure if you've confirmed with Dave C if he wants to review the Research Plan & Conversation Guide separately or together. The working review meetings for those documents are a relatively new addition to the process

**Comment by BlakeOrgan** [comment]
The conversation guide is complete and can be found in the research repo [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/research/CMS%20Notifications/Moderated-Interviews-Conversation-Guide.md).

Next steps are to complete the email mockup needed in this ticket (https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11440) and schedule the chosen research participants for this ticket (https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11582)

A meeting to review the research plan, this conversation guide, and the email mockup are scheduled with Dave C to allow for any updates needed before research sessions start.
