### ISSUE TITLE
CMS Notifications Research: Hi-Fi prototype creation

### ISSUE THREAD

**Issue by EWashb** [department-of-veterans-affairs/va.gov-cms#9555]
## Background

The Sitewide CMS team should create a prototype to assist in the research plan. Some preliminary sketches have been added to the comments section of this ticket. These may suffice for the hi-fi prototyping that will be presented to editors during the CMS notifications research sessions.

## Acceptance Criteria

- [ ] tech feasibility review on low-fi
- [ ] Consider entity usage modules OOTB feature in the design
- [ ] Craft language presented in the "notify content owner" section (see below)
- [ ] Consider the process end to end such as receives email > fixes link

**Comment by rachel-kauff** [comment]
There's some low-fi ideas sketched out in the [Broken link spike mural](https://app.mural.co/t/vagov6717/m/vagov6717/1654526125251/39f95935ad77b0e10723c701556de4ed2127f80f)


<img width="803" alt="Screen Shot 2022-07-14 at 1 37 02 PM" src="https://user-images.githubusercontent.com/41017988/179078686-d40f7aff-ef70-4ce7-ac28-c026389b9285.png">


<img width="650" alt="Screen Shot 2022-07-14 at 1 37 23 PM" src="https://user-images.githubusercontent.com/41017988/179078747-b2a2a5aa-22d3-40f4-bf5e-fb45979eccdb.png">

**Comment by EWashb** [comment]
This is not in scope any longer. CMS notifications pilot will be in regard to directive 6102- not broken links.
