### ISSUE TITLE
CMS Notifications Research: Identify Pilot Participants

### ISSUE THREAD

**Issue by EWashb** [department-of-veterans-affairs/va.gov-cms#9556]
## Background 

Before we begin CMS notifications research, the Sitewide CMS team should identify different levels of engagement and skill that exists in the VAMC systems. This work should be done with the support of VHA Digital Media.

Considerations to be aware of:

- Consult w/ help desk
- ~Check MS teams office hours channel~
-Editor # months active in the CMS (we want a variety of experience and skill levels)
- ~Must work with VHADigital Media to distribute among appropriate channels~ DONE

We will attempt to source:

- approximately 6 editors from Vet Centers and VAMC
- Unique locations
- Varying time working with the VA
- Varying comfort level

## Acceptance Criteria

- [x] Work with stakeholders to distribute editor feedback opt-in [survey](https://www.surveymonkey.com/r/R5TNFVX)
- [x] Review editor list of opt-ins in Survey Monkey

**Comment by EWashb** [comment]
meeting scheduled for 7/20

**Comment by davidconlon** [comment]
This issue is placed on hold as we identified an opportunity documented in #9865 that will, inherently block this issue until that's resolved. So we're swapping that effort out for this on as part of sprint 63 with the understanding that the size of the two issues may not be comparable.

**Comment by EWashb** [comment]
Further refinement has determined that Health Hubs would be the best audience for this pilot. It would allow us to learn more with a controlled group of editors before a change is introduced to the larger VAMC editor group.

**Comment by EWashb** [comment]
Let's make sure to think through who we are recruiting and if they are compliant with other tasks.

**Comment by EWashb** [comment]
include VHA dig media as optional observers.

**Comment by EWashb** [comment]
We have a spreadsheet we will be working off of. VAMC and Vet Center editors have been identified.
