### ISSUE TITLE
CMS Notifications Research: Conduct editor interviews

### ISSUE THREAD

**Issue by EWashb** [department-of-veterans-affairs/va.gov-cms#9557]
## Description

**Guidelines**
- [Moderator guidelines](https://depo-platform-documentation.scrollhelp.site/research-design/conducting-research-sessions)
  - [Research Safety guidelines](https://depo-platform-documentation.scrollhelp.site/research-design/research-safety-and-emergency-exit-strategies) 
- [Notetaker guidelines](https://depo-platform-documentation.scrollhelp.site/research-design/observer-guidelines#Observerguidelines-Howtobeagoodnotetaker)
  - For Veteran-facing research, Perigean can provide a notetaker
  - For Editor-facing research, the Product Manager or a member of the Design Team should take notes
- [Observer guidelines](https://depo-platform-documentation.scrollhelp.site/research-design/observer-guidelines)

**Recruitment Trackers**
- Veteran-Facing research should follow [Platform guidance](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/accessibility/research/recruitment.md#Maximum-Variation-Sampling) on recruitment tracking
  - [VA recruitment checker spreadsheet on Microsoft Excel teams](https://governmentcio.sharepoint.com/:x:/r/sites/VSATeam/Shared%20Documents/Accessibility/RecruitmentChecker.xlsx?d=we0ffb06d5bac4cd5902c5f8b23fe988c&csf=1&web=1&e=FzYt5t)
  - [Google Sheets version of the recruitment checker](https://docs.google.com/spreadsheets/d/1pq7TSHZonfpzAQBJj6B2geGHlNUwZEs4DzEvxcRgu0o/edit?usp=sharing)
- Editor-Facing research should track participants in the [VA.gov CMS UX research base](https://airtable.com/invite/l?inviteId=inv9nYvS8HoNGoZpu&inviteToken=7d5d76876f2b9f45c44a18ad316f6989c54017e5504ef23742f4153d8b658df3&utm_medium=email&utm_source=product_team&utm_content=transactional-alerts)

**No-shows and rescheduling**
- If a participant hasn't shown up within 5 minutes of the scheduled start time, they should be contacted as a reminder
  - In Veteran-facing research, the Perigean Notetaker will handle contacting the participant by phone and email
  - In Editor-facing research, the Moderator should contact the participant through email or Microsoft Teams
- If the participant hasn't shown up within 15 minutes of the start, consider it a no show
  - Contact the participant to see if they can reschedule for a different available slot 
  - If unable to reschedule, mark them officially as a no show in the recruitment tracker 
- Keep the PM and PO in the loop about no-shows in case additional sessions need to be scheduled

## Acceptance Criteria

**Before 1st session**
- [x] Pilot session has been conducted and any relevant edits have been made to research protocol
- [x] Moderator(s), Notetaker(s), & Observer(s) have reviewed guidelines for their role(s)

**After sessions**
- [x] Observers and Notetakers have shared their notes with Research Lead
- [x] All notes are stored in the research folder
- [x] Update the recruitment tracker with participant demographics daily
- [x] Download all session recording to your local machine for synthesis
- [x] You have conducted enough sessions to satisfy our intended demographics from research plan 
  - [ ] OR Product Owner has signed off that you've done enough to move forward

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [x] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by davidmpickett** [comment]
@BlakeOrgan @EWashb FYI I just copy and pasted in the Research Runbook markdown for this ticket. You can delete the Veteran-facing research bits when it's refinement time

**Comment by EWashb** [comment]
Work estimated to begin in Sprint 73 and will continue into Sprint 74

**Comment by BlakeOrgan** [comment]
We have met our goal of 6 user research sessions. Closing out this ticket and I will begin on the findings synthesis and topline report ticket next.

https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9558
