### ISSUE TITLE
IE11: Remove old "incompatible browser" warning (tech debt)

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#9561]
## Description

<img width="765" alt="image" src="https://user-images.githubusercontent.com/4054752/175078431-14788cd9-9d92-486b-8f03-eb81ca748aa0.png">
<img width="288" alt="image" src="https://user-images.githubusercontent.com/4054752/175078462-ea5d12b8-4e91-4c58-bc10-2b9881f2f9ce.png">

Document:

- How it's triggered?
   - This gets triggered from the file `content-build/src/site/includes/header.html`
   - Triggers logic which lives in the file `content-build/src/site/assets/js/incompatible-browser.js`
      - This logic detects IE10 and below, only.

**Trigger logic:**
```
<script nonce="**CSP_NONCE**" type="text/javascript">
  (function () {
    var module = {};
    {% include "src/site/assets/js/incompatible-browser.js" %};
    checkBrowserCompatibility();
  })();
</script>
```
- Whether it's present in mobile or just desktop header?
   - The related DOM element exists as markup within 3 files: `vets-website/src/applications/proxy-rewrite/partials/header.js`, `vets-website/src/platform/landing-pages/dev-template.ejs`, & `content-build/src/site/includes/top-nav.html`.
      - but could be displayed only in a "modern" page w/ an active tablet/desktop layout (screen-size) due to when/where the `checkBrowserCompatibility()` function gets called (see 1st question ^.)

**HTML-related markup**:
```
<div class="incompatible-browser-warning">
  <div class="row full">
    <div class="small-12">
      Your browser is out of date. To use this website, please <a href="https://browsehappy.com/">update your browser</a> or use a different device.
    </div>
  </div>
</div>
```

## Acceptance Criteria
- [ ] Remove all references to "incompatible-browser"-related code/logic.
- [ ] Confirm in production on sites with injected header to confirm no unexpected behavior:
  - [ ] IE banner is not affected in MS Edge
  - [ ] https://www.va.gov/health - IE11 banner appears in MSEdge
  - [ ] https://www.va.gov/health - IE11 banner does not appear in Chrome, no other banner issues or problems with the injected header
  - [ ] https://benefits.va.gov/benefits/ - IE11 banner does not appear in Chrome, no other banner issues or problems with the injected header

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by wesrowe** [comment]
Injecting into sprint since ie11 is the highest priority for FE engineering.

**Comment by jilladams** [comment]
In PR from Claudio. Since he's left the team, have reassigned to Ryan, flagged with Dave, and will roll into Sprint 62.

**Comment by jilladams** [comment]
Will merge after daily deploy today (Fri), for deploy on Monday. Ticket should resolve before sprint planning on Monday.

**Comment by jilladams** [comment]
Did basic sanity checks for the IE11 banner on staging (not appearing in non-IE, appears in IE).
