### ISSUE TITLE
AskVA + Login.gov: Assist testing of LOA in Staging

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#9567]
### Blocked reason
8/12/22 We are waiting to hear back from Chris Clemens if we need to assist any testing. 

## Description

Necessary changes are pretty limited; documented in #9140.

We want to plan this carefully because we have been asked to get the AskVA react widgets ready for the new attributes _before Login.gov is integrated by the Platform team_.

## Acceptance Criteria
- [ ] Add Login.gov attributes to conditional logic in react widget
- [ ] Limit code to Staging using environment flag
- [ ] Also implement Flipper(?)
- [ ] Figure out a way to test (assuming Login.gov is not yet implemented)

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by wesrowe** [comment]
@kind-claudio pls add implementation details

**Comment by allisonlu** [comment]
## Some other useful information and context:
- Getting Started with Identity: https://github.com/department-of-veterans-affairs/va.gov-team/blob/ca03da79e7da473abe3ccfa263a8de16b74370ea/products/identity/login/gettingstartedidentity.md
- Technical Diagram of LOA3 Identity Verification: https://github.com/department-of-veterans-affairs/va.gov-team/blob/901ecc94ad1096bf4d7b74c3392c715d1fd35458/products/identity/login/reference-documents/auth/authentication-and-authorization-simplified.md#technical-diagram-of-loa3-identity-verification

## Definition of LOA3
  
| LOA 1 on VA.gov  | LOA 3 on VA.gov   |
| ---------------- | ----------------- |
| MHV Basic        |                   |
| MHV Advanced     |                   |
|                  | MHV Premium       |
| DS Logon Level 1 |                   |
|                  | DS Logon Level 2  |
| ID.me LOA1       |                   |
|                  | ID.me LOA3        |

> LOA3 users are more trusted, and will often have more information and access to services. UAT is required for any new product or feature leveraging identity to ensure that user is able to connect to the correct MPI record and that the personal information being served up by MPI and displayed by [VA.gov](http://va.gov/) is correct. If the user is not found in MPI, and they should be found or would like to be added to MPI, they need a way to correct this. If the user is connected to the correct MPI account, but the information shown is incorrect, the user needs a way to correct their information.
> 
> LAO1 users have the most restricted access to digital services, since we can't be confident in the trustworthiness of their identity. As a result, we provide additional, minimal-risk services to the user such as saving in-progress applications, and editing pre-filled form information pulled from the identity provider.

**Comment by allisonlu** [comment]
@wesrowe Do you know what exactly the Login.gov team is making to the LOA3 definition? (as mentioned in https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9140)

**Comment by wesrowe** [comment]
@allisonlu, good question – I just realized that the notes from the meeting with login.gov folks didn't make it from a google doc into github. I just updated the details section of #9140 with the findings from the meeting, along with a recommended approach.

**Comment by jilladams** [comment]
@ryguyk @wesrowe based on findings from #9573 re: LOA: we don't have any changes to make, but _do_ need to plan to test when they launch, correct? We want to keep this ticket?

**Comment by ryguyk** [comment]
@jilladams My understanding is that the change in question has already been launched. It's been in place for a while. Are you familiar with the original communication that led us to believe this was something happening in the future? I want to make sure we are all on the same page here. I don't think there's anything to do, but I want to all confirm that together.

**Comment by jilladams** [comment]
Yep, that's my understanding as well. When we let Dave know, he just flagged: once Login.gov is fully integrated upstream, we'll want to test. (Unless we're saying _that's also_ already shipped. I thought it was still in progress, just folks have already prepared for the LOA bit.)

**Comment by ryguyk** [comment]
Login.gov is available as an identity provider (that is to say, folks can already log in with login.gov). I don't know what else there is to ship. I'm not saying there's nothing more. I'm just saying that I don't know.

**Comment by wesrowe** [comment]
Per Dave's suggestion, I emailed Chris Clemens around 8/1 to ask if his team wants to test, and I offered support if he can provide test users. Got a quick clarification request but silence since then. I'll bump that email.
