### ISSUE TITLE
Usability audit: Event location experience for Editors and Veterans

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#9568]
## Description

We (Dave) have heard from Editors (VEO and others) that the process of specifying an event's location is cumbersome or worse.

Related issues/epics:
- Epic around CMS pushing lat/long data to Lighthouse: #7490.
- Other issues in this epic, #9427

For this issue, we want to get our arms around what use cases are poorly supported or hard to use right now, **from both Veteran and Editor perspectives.**

### Veteran perspective

E.g., [this example](https://www.va.gov/boston-health-care/events/46953/): 
![image.png](https://images.zenhubusercontent.com/61a671f5fc46c2a311655f75/26d9c64b-2fef-42d1-8bea-140f23e2c90b)
- "Outside building 4" would be hard to find and can't be put on a map

Editors want to _easily_: 
- Locate an event at 1 or more VA facilities 
- Specify that an event is online, or a hybrid of located and online
- What if it’s not at a VA facility, what info would be needed to lookup lat/long?

## Acceptance Criteria
- [ ] documentation (mural, notes, etc)

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by wesrowe** [comment]
removed "high priority" pin, it got set accidentally during refinement

**Comment by fmccaf1** [comment]
### Meeting 6/23 w/ Rachel Kauff on Editors' Experience
- Editors creating an event choose between radio buttons: at a VA facility or at a non-VA facility
- If choose at a VA facility: User starts by looking up the name of the facility, then can enter free form in field "building, floor, or room"
- If choose at a non-VA facility: Can enter free form in filed the street address, and there is also a field for "building, floor, or room"
- In future, likely to need option for events that are both in-person and online. Current experience requires editors to choose one or the other. These radio buttons will likely need to change to checkboxes (to allow selection of one or more)
[Link to meeting notes](https://docs.google.com/document/d/104MitPRtu7OmURl4O53XRzaPgyHxArgGrU6CZr1ge2E/edit?usp=sharing)

**Comment by fmccaf1** [comment]
### Meeting 6/24 w/ Cindy Merrill on Veterans' Experience

- Cindy conducted research months ago. [Research report here.](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/public-websites/outreach-and-events/research/research-findings.md)
- Conversation covered needs for better options for filtering events, as well as the wide discrepancy between event location information within different events at va.gov

[Link to meeting notes](https://docs.google.com/document/d/1dAktpNUaMWD-Dno_HKF8kuJutjy8TU5CbHl0KjU1oLQ/edit#)

**Comment by fmccaf1** [comment]
### Discovery Complete

I reviewed: 
- Both outreach events area of va.gov and VAMC-specific events.
- The CMS side (what editors see when creating event) for both outreach events and VAMC-specific events
- Audits for all upcoming events (all audits completed today, 6/28/22

[Here is a Mural document illustrating the 4 biggest issues I found.](https://app.mural.co/t/vagov6717/m/vagov6717/1656340710767/01f84c9481db4086d9e00fdffd9d89047a3b3ca3?sender=ua604735c5cf1162b042a4310)

**Comment by jilladams** [comment]
@fmccaf1 Nice work, and definitely some potential bugs floating in here. Could you update the mural to point to URL for the Event Audit tool in your Mural screenshots? I haven't seen that before and would like to poke at it.

And thanks for flagging the ties to #9442. When that ticket is ready to review, I think the outcomes there will maybe require a minor refresh of the Mural doc you've made -- I can let you know when that's done.

Otherwise: it seems to me like the right next step is to create a new ticket assigned to Wes to review these findings with you next sprint and cut any resulting tickets, and then you can close this out.
