### ISSUE TITLE
IE11 Deprecation Copy: Cleanup static text (hard-coded) to be DRY

### ISSUE THREAD

**Issue by kind-claudio** [department-of-veterans-affairs/va.gov-cms#9572]
## Description
- The same copy (text) is set in 4 files.
- We should follow the DRY principle where possible.
- ~~Eventually, the copy will get populated by the CMS, but for now, we just want to clean it up so it's not repeated multiple times.~~ _probably incorrect assumption_

## Acceptance Criteria
- [ ] The same copy shall be stored in one place, if possible - dependent on technical limitations.

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by jilladams** [comment]
We will not take this on, as the banner copy will be removed shortly.
