### ISSUE TITLE
Determine request method for CMS collab cycle kickoff

### ISSUE THREAD

**Issue by EWashb** [department-of-veterans-affairs/va.gov-cms#9592]
## Background 

As we move into a CMS collab cycle we should determine how best to receive requests for collaboration and/or review.

## User Story

As a team with dependencies on the CMS, I want an intake process to engage with the Sitewide CMS collaboration cycle so that I know I am following proper design and governance standards. 

## Acceptance Criteria

- [x] A process for submitting a collab cycle request to the Sitewide CMS team
- [x] Guidelines for how the request process works and what requestors can expect after they request.

**Comment by msbtterswrth** [comment]
I have created a new github intake form here: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/new?assignees=ewashb%2Cdawnpruitt&labels=%E2%AD%90%EF%B8%8F+Sitewide+CMS&template=cms-collab-intake.yml&title=%5BCMS+COLLAB+CYCLE+INTAKE%5D+%28Team+Name%2C+Product+Name%2C+Feature+Name%29

Also created a [confluence document](https://va-gov.atlassian.net/wiki/spaces/VAGOV/pages/1791098881/Sitewide+CMS+Collaboration+Cycle+Kickoff) to mirror Platform's with more information about the Sitewide CMS collab cycle process. Partially based on the mural work we did [here](https://app.mural.co/t/vagov6717/m/vagov6717/1652978287230/4b9fa47e15a26a5185b2fba06569f925d24e9e16?invited=true&sender=u0213d96dd8b8c144f1f10284).
