### ISSUE TITLE
Redirect Request: CLP vanity url for /va-health-connect

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#9597]
## Status
- **[2024-03-20] Ticket to remain in Blocked bucket:**
  - Mikki is looking into this.
  - Jill looked at the CLP node and it looks like a new editor, Jill Essex, has made edits to it as recently as March 15. Not sure if she's been in touch with anyone about the destiny of publishing, though.

## Context
A new CLP is going to publish, that requires a vanity URL redirect.

- CLP creation ticket: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9169
- Mikki's note re: redirect: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9169#issuecomment-1136368754
- CLP node: https://prod.cms.va.gov/initiatives/va-health-connect - still in draft as of 6/27/22

### Implementation date
When does this request need to be live: TBD CLP is not yet published
Abigail E. Harlow [Abigail.Harlow@va.gov](mailto:Abigail.Harlow@va.gov) will provide publish date to drive our timing.

### Redirects 
| Current URL  |  Redirect Destination or New URL |
| /initiatives/va-health-connect/  |  /va-health-connect/ |

## CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [X] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by jilladams** [comment]
Notified Abigail E. Harlow <Abigail.Harlow@va.gov> that we need 2-3 days to turn this around, and she agreed to provide as much notice as possible when CLP launch date is clear. Still TBD timing.

**Comment by mnorthuis** [comment]
@DanielleThierryUSDSVA Do you know if this is still a valid initiative?

**Comment by FranECross** [comment]
@mnorthuis @DanielleThierryUSDSVA Just circling back around on this item to see if it's still viable, or can be closed. Thanks!

**Comment by FranECross** [comment]
@mnorthuis @DanielleThierryUSDSVA Wondering if this ticket work is still needed and should stay in our Blocked bucket, or it can be closed? Thanks in advance!

**Comment by mnorthuis** [comment]
The last information I got on this, is that they were going to publish info on this program via the facility site that they are piloting it at.  Once the pilot expands, they may come back around to this.  So this may be on hold for awhile.

**Comment by FranECross** [comment]
Thanks, @jilladams and @mnorthuis !! Appreciate the info and quick responses!

**Comment by mnorthuis** [comment]
My apologies, I mixed this one up with the Childcare assistance one.  I am not sure of the status on this one, but will follow up.

**Comment by mnorthuis** [comment]
I have no idea about this one, its quite old.

**Comment by FranECross** [comment]
Closing as a no op;
