### ISSUE TITLE
Discovery: Banners used with injected header / styles

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#9608]
## Description
When we launched the IE11 deprecation banner, on legacy pages with injected header, the banner had style problems. Different font renderings, a yellow outline, a different color on the dismiss button: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9599.    For IE, it's deprecated and we opted not to try and fix. 

For future: if we opt to use a banner that will appear via the injectable header again, would this stylistic difference appear? 
For example, if we displayed a banner to indicate VAOS is down, that should appear across the entirety of the VA.gov world, how would it display? Filing this ticket to record the known previous issue, in case a campaign / project like this arises. 

To test/understand: 
* In Chrome / Safari / FF: is a banner that appears on a legacy page styled correctly? Can use cookies to test, maybe. https://depo-platform-documentation.scrollhelp.site/developer-docs/teamsite-overview

## Acceptance Criteria
- [ ] Document findings

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [X]  `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by FranECross** [comment]
Closing as a no op
