### ISSUE TITLE
Bump drupal/node_revision_delete

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#9611]
## Description
https://github.com/department-of-veterans-affairs/va.gov-cms/pull/8977#issuecomment-1169508509

This just needs two things to be done
1) remove the patch ` https://www.drupal.org/files/issues/2022-02-21/3249493-9.patch` from composer.json
2) ddev composer update drupal/node_revision_delete

## Acceptance Criteria
- [ ] Remove patch https://www.drupal.org/files/issues/2022-02-21/3249493-9.patch from composer.json
- [ ] Update node_revision_delete

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [x] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by edmund-dunn** [comment]
Closing in favor of #18781
