### ISSUE TITLE
Fix Vet Center CAPs in Puerto Rico with un-geocodable address 

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#9616]
## Description

<details><summary>8 CAPs with addresses that are not able to  be geocoded.</summary>

```
Unable to geocode 'Barrio Santa Rosa, Km 1.7 LAJAS, PR 00667 US'.
Unable to geocode 'Carretera 704, Km. 1.6 Interior Barrio Cuyón COAMO, PR 00769 US'.
Unable to geocode 'Callejon Los Fas Casa 9 CABO ROJO, PR 00623 US'.
Unable to geocode 'Urb. Villa del Rosario 6 Street A VEGA BAJA, PR 00693 US'.
Unable to geocode '1 Herrera St. UTUADO, PR 00641 US'.
Unable to geocode 'Pr-3, Kilometers 54.9, Lot 3 Pueblo Ward CEIBA , PR 00735 US'.
Unable to geocode '1000 Recreational Drive MINDEN, LA 71055 US'.
Unable to geocode 'Bldg. 312 on 9th Street DUBLIN, CA 94568 US'.
```

![image](https://user-images.githubusercontent.com/5752113/176482196-3bc88c54-11a2-492e-9ba6-405ea160e568.png)
</details>

## Acceptance Criteria
- [x] Meet with Jess S to discuss what to do about these addresses.
- [x] Nodes are edited and updated to have lat lon.
   - [x] fix 'Barrio Santa Rosa, Km 1.7 LAJAS, PR 00667 US'.
   - [x] fix 'Carretera 704, Km. 1.6 Interior Barrio Cuyón COAMO, PR 00769 US'.
   - [x] fix 'Callejon Los Fas Casa 9 CABO ROJO, PR 00623 US'. 
   - [x] fix 'Urb. Villa del Rosario 6 Street A VEGA BAJA, PR 00693 US'.
   - [x] fix '1 Herrera St. UTUADO, PR 00641 US'.
   - [x] fix 'Pr-3, Kilometers 54.9, Lot 3 Pueblo Ward CEIBA , PR 00735 US'.
   - [x] fix '1000 Recreational Drive MINDEN, LA 71055 US'.  (fixed by Swirt July 5)
   - [x] fix  'Bldg. 312 on 9th Street DUBLIN, CA 94568 US'.(fixed by Swirt July 5)
- [x] List specific nodes that were edited.

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by omahane** [comment]
After running the [bulk edit on the Vet Center CAP](https://prod.cms.va.gov/admin/content/bulk?moderation_state=All&taxonomy_entity_index_tid_depth=All&title=&type=vet_center_cap):

Unable to geocode 'Barrio Santa Rosa, Km 1.7 LAJAS, PR 00667 US'.
Unable to geocode 'Carretera 704, Km. 1.6 Interior Barrio Cuyón COAMO, PR 00769 US'.
Unable to geocode 'Callejon Los Fas Casa 9 CABO ROJO, PR 00623 US'.
Unable to geocode 'Urb. Villa del Rosario 6 Street A VEGA BAJA, PR 00693 US'.
Unable to geocode '1 Herrera St. UTUADO, PR 00641 US'.
Unable to geocode 'Pr-3, Kilometers 54.9, Lot 3 Pueblo Ward CEIBA , PR 00735 US'.
Unable to geocode '1000 Recreational Drive MINDEN, LA 71055 US'.
Unable to geocode 'Bldg. 312 on 9th Street DUBLIN, CA 94568 US'.

**Comment by kevwalsh** [comment]
It's great to get these fixed, but we should also come up with some business process for events like this.

**Comment by kevwalsh** [comment]
[Some background](https://www.census.gov/library/stories/2020/01/street-addresses-are-simple-not-in-puerto-rico.html) on why services like Mapbox have trouble geolocating these

**Comment by swirtSJW** [comment]
1000 Recreational Drive Minden LA does not geocode because the road is not named in mapbox data.
![image](https://user-images.githubusercontent.com/5752113/177364301-4dff3000-6127-4ac3-a244-33b857e04335.png)

I was able to geocode to 400 Hillside Ln, Minden, LA 71055 then move the pin by hand.

**Comment by swirtSJW** [comment]
I changed `Bldg. 312 on 9th Street DUBLIN, CA 94568 US` to `Bldg. 312 on 9th Street DUBLIN, CA 94568 US`  and it geocoded fine.   https://prod.cms.va.gov/peninsula-vet-center/community-access-point/peninsula-vet-center-us-army-camp-parks-training-facility

**Comment by kevwalsh** [comment]
Next steps
1. Discuss with Jessica S (business partner for Vet Centers) about next steps for PR
2. Spin out a separate epic for flagging failed geodata lookups for facilities, and a business process for managing those flags.
3. Consider how #9448 might help

**Comment by kevwalsh** [comment]
I've spun out #9750, and referenced #9448 from there.

And updated the ACs here strictly for the meeting with Jessica S regarding the PR situation.

**Comment by dsinla** [comment]
This is removed from Sprint 62 in discussion with @davidconlon . This will now be an agenda item in the next meeting with Dave C, David S, and Jessica. No specific date at this time.

**Comment by omahane** [comment]
@dsinla and I met with PR VA directors today, tracked the work in this Google Sheet:
https://docs.google.com/spreadsheets/d/1Hv6RjgKwJSPCvLwzBQGtZrv8FHpfGzmH8iEekZmKnxY/edit#gid=0

After the meeting, the only Vet Center CAP needing geocoding is in Rapid City, per this content view:
https://prod.cms.va.gov/admin/content/facilities/addresses?Title=&type_op=in&type%5B%5D=vet_center_cap&moderation_state=All&workbench_access_section__section=All&lat_op=%3D&lat%5Bvalue%5D=&lon_op=empty&lon%5Bvalue%5D=&a1_op=contains&a1=&a2_op=contains&a2=&city_op=%3D&city=&state_op=in&state=All&zip_op=contains&zip=

**Comment by omahane** [comment]
![Screen Shot 2022-08-26 at 1 39 53 PM](https://user-images.githubusercontent.com/766573/186970656-13c09dcd-4dd5-4a05-9025-c63dbedc8709.png)

**Comment by omahane** [comment]
All PR Vet Center CAPs have been geocoded.
