### ISSUE TITLE
[Events] Add address and lat/long to events audit view

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#9618]
## User stories

1. As a content manager, I want to review address and geodata for events. 
2. As an FE team working on event filters for Veterans, I want to see data 

## ACs
- [ ] admin/content/events shows lat, long, and address fields, like the one delivered via #9615
- [ ] Consider showing address field from facility via the entity reference, for events that are located at a facility. 
- [ ] Consider filters that might match the Veteran user stories on the FE, like search by zip code or state or lat/long ... this could be split out into a separate issue, to support user story 2

**Comment by mmiddaugh** [comment]
@jilladams is this still valid? If so, should it belong to Facilities or Public Websites?

**Comment by jilladams** [comment]
IMO, from discussions with @davidconlon Public Websites acts sort of as a platform owner for Events. PW owns higher level strategic initiatives, and may develop features that benefit Facilities. Facilities also has the bulk of Event editors, and use cases. So Facilities may want / need sometimes to extend Event functionality, with Public Websites as stakeholders / code reviewers / keepers of the flame. 

If you and Dave both agree on that way of thinking about it: we can remove the Facilities label from anything re: Events that doesn't seem strategically important to Facilities team / editors / stakeholders.

**Comment by FranECross** [comment]
@jilladams I think this ticket belongs in the 'transfer to other teams', since it has to do with Events. True? Thanks!

**Comment by FranECross** [comment]
Close per Dave C. We're not sure there is a demand for this. If one comes up in the future, we'll create a new ticket.
