### ISSUE TITLE
Add lat/long field to event content type to support events at Non-VA locations 

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#9619]
ACs
- [ ] Needs refining, but we should probably follow the patterns from Facility implementation.

**Comment by dsinla** [comment]
NOTE: Events can occur at a Facility (in which case lat/long is provided, can be online, or can be listed as occurring at "non-VA location"

**Comment by jilladams** [comment]
Yeah. Once we get around to an event map / proximity filters, this may come back around, but we can rewrite it with details at that time. Closing / removing from epic.
