### ISSUE TITLE
Discovery: Homepage iteration: Design ramp up for Q3 iteration

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#9621]
## Description
Sitewide crew owns a project to iterate on the VA.gov homepage. In Q2, PW team implemented a prototype for the update. The prototype was released in ~May 2022 for user testing. 

- Prototype: https://staging.va.gov/homepage-test/ -- this path is not available on production
- Epic #8340 tracks previous tickets for this effort. 

Goal of this ticket is to get up to speed with the state of the project, review the previous design iteration, and be ready to implement a design rev in Q3 based on Q2 user feedback.

(Context: The prototype was built during a window of time where the current Public Websites team was called the Offices team. References to Offices team can be interpreted as our PW team.)

### Q3 goal
Round 1 user research on the prototype concludes in ~July 2022. 
In Q3, our team will integrate feedback and produce a new design iteration, and implement that in the prototype for 2nd round research.

## Stakeholders / contributors: 

- **Ryan Thurlwell**, VA-side designer -- implemented original design for the current prototype in testing. Ryan was formerly a designer on VA side working with Dave, but has since moved on to other projects. He is available for consult, if we have questions about the original designs.
- **Val Rundle**, Design lead, Sitewide Program team -- modified the original designs as former member of PW team, to finalize for prototyping
- @allisonlu, FE Eng on PW team -- implemented the prototype in the front end
- @mmiddaugh, Product manager of the updated Homepage effort, Ad Hoc team -- Her team will own decision making around what should happen, and pass to us for design / implementation. 
- @cindymerrill, User Experience researcher, Ad hoc team -- is now part of Michelle's team, and is running user testing on the design/prototype.

## Q2 iteration artifacts

- [Homepage design - Sketch comps](https://www.sketch.com/s/58c718b6-196f-4b6a-a433-fb2a65d7a4d2/a/zxR2RKM)
- [Mural with grid layout](https://app.mural.co/t/vagov6717/m/vagov6717/1650408594492/7245d261b15a8a1efc05c2a47e08d6f96cd61871?sender=u252e7152800e3981889d1910) - **TODO**: Confirm with @wesrowe and @valerierunde that this Mural was a follow on artifact that we developed to support the Sketch comps. 
- [Homepage governance & guidelines Mural](https://app.mural.co/t/vagov6717/m/vagov6717/1649169375121/a40d9658465b82a8a338d948e383024ff68cf41d?invited=true&sender=u252e7152800e3981889d1910) - developed by Val.  [PDF export version](https://github.com/department-of-veterans-affairs/va.gov-cms/files/8453274/Homepage.Governance.and.Guidelines.pdf)
- [V1 design / collab cycle feedback](https://docs.google.com/document/d/1P6Phnqe8ZE5dG16uyxfyew8L2D9MsHFEDkByUDBR5vI/edit#heading=h.glvc5hg6iexn) - valuable to review just for context on requirements we've encountered before
- Previous design intent cycle - https://github.com/department-of-veterans-affairs/va.gov-team/issues/39038
- Github folder for the home page redesign, which currently contains only a research plan: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/public-websites/home-page/research/redesign-usability

### V1 research that fed into prototype
These docs are listed for reference, but not necessarily required reading: 

- [Full written research report](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/public-websites/research/202104-baseline-wayfinding/research-report.md)
- [Research findings presentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/public-websites/research/202104-baseline-wayfinding/research-readout-full-June8.pdf)
- [Research recommendations presentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/public-websites/research/202104-baseline-wayfinding/recommendations-summary-for-VA-sitewide-crew.pdf)
- [Home page wish list](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/public-websites/research/202104-baseline-wayfinding/home-page-wish-list.md)

## Acceptance Criteria
- [ ] Read / review Q2 iteration docs above
- [ ] Introduce yourself to Cindy & Michelle in Slack. Feel free to make yourself available for user research readouts, etc.

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [X] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by mmiddaugh** [comment]
Other relevant issues: 
- [[Epic] VA.gov Home page redesign #40845](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/40845)
- [[Research epic] Veteran Top Task Research (moderated and unmoderated) #40857](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/40857)
- [[Research epic] Usability of redesigned VA.gov home page #41578](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/41578)

We have begun tracking options for Q3 iteration in [Updates to VA.gov home page redesign deployment#43137](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/43137) - this is purely a heads up - this issue is a draft only at this time. 

An [Accessibility spot check review for redesigned VA.gov home page](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/42860) has been requested - issues are forthcoming.

**Comment by fmccaf1** [comment]
I've read through the above but will continue to refer back to this ticket. Aslan, feel free to close when you're finished here.

**Comment by jcklpe** [comment]
Closing ticket as done. Excellent research here, and lots of good idea. I did an independent pass over the homepage when I was onboarding, just writing my notes on things that stood out to me as not ideal and much of the research and provided designs align with those instincts on things that could be improved.
