### ISSUE TITLE
FE Discovery: Translation research, how it works today / existing research

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#9629]
## Description
In Q3, the Sitewide Content team has a goal to add Spanish translations to new content.

Translations are already in effect in some areas of the site (e.g. https://www.va.gov/health-care/covid-19-vaccine/).
We need to understand: if we need to continue implementing translations in the same way, what are the limitations / processes to do it.
Also: gather info on research / other translation mechanisms. To support this effort, we need to understand: 

1. What we know / what we don’t -- this is not the first time Translation has come up in the CMS context, so we can start by talking to experts on the Program team (Kev / Swirt) to understand what ground has been covered before
    - We need to understand where it exists already
    - Can it extend to additional pages / content types 
    - Can we find the existing research already performed (addressed Drupal translations, performance concerns, etc) -- Danielle Thierry may know / be able to point us to this research.
3. how to maintain -- Any notes on existing mechanisms
4. how to extend -- Spanish will not be the only language, and Benefit Hub / Detail pages will not be the only content types to be translated, after MVP. We should be mindful of extensibility across content types / languages, as we develop solutions

## Acceptance Criteria
- [ ] Discuss history with Swirt / Danielle Thierry. Include Wes / Jill as optional in any scheduled meetings.
- [ ] Document in ticket: already installed modules / mechanisms, links to historical tickets / epics, any analysis
- [ ] Document in ticket: any remaining questions that require follow up SPIKE tickets
- [ ] Document in ticket: proposed path forward to maintain / extend, when we know enough to propose one

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [X] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by allisonlu** [comment]
See @dsasser 's #9623 ticket, which contains all the info about translation support on frontend.

**Comment by jilladams** [comment]
Closable, imo
