### ISSUE TITLE
Implement lat/long fields for facilities

### ISSUE THREAD

**Issue by JayDarnell** [department-of-veterans-affairs/va.gov-cms#9637]
## User Story or Problem Statement

We want a single source of truth for facility lat/long information.  We've already added lat/long fields for Vet Center CAPS with #8627 - Now we need to add these fields for the following content types as well:

- VAMC Facility: health_care_local_facility
- ~VAMC System Medical Records Office: vamc_system_medical_records_offi~
- VBA Facility: vba_facility
- NCA Facility: nca_facility
- Vet Center: vet_center
- ~Vet Center Mobile Vet Center: vet_center_mobile_vet_center~
- Vet Center Outstation: vet_center_outstation

## Acceptance Criteria
- [ ] Lat/long fields are now available for each of the content types listed above
- [ ] Visibility/Access for these fields should be consistent with the implementation used for Vet Center CAPs (admins only)

## Design principles

Veteran-centered
- [x] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by swirtSJW** [comment]
These migrations have been run on prod as update migrations which forceed in the values.
![image](https://user-images.githubusercontent.com/5752113/181647483-707c8602-d820-473a-a49f-e5f7181b96ad.png)

![image](https://user-images.githubusercontent.com/5752113/181647580-843a0360-4d00-4283-9afa-192400bfdf33.png)

![image](https://user-images.githubusercontent.com/5752113/181648234-e30b8063-e33d-4b18-b9c3-e59a6b62ebe5.png)

![image](https://user-images.githubusercontent.com/5752113/181659255-bd6a2b3f-5e51-4378-9883-26c324ad410b.png)

**Comment by swirtSJW** [comment]
![image](https://user-images.githubusercontent.com/5752113/181659709-a3d393b0-2ba5-457b-a889-17135210987d.png)

**Comment by swirtSJW** [comment]
![image](https://user-images.githubusercontent.com/5752113/181660923-09044459-79fc-4faf-b140-7dddffee41ca.png)
