### ISSUE TITLE
Event location: review Usability audit findings and cut tickets

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#9641]
## Description
Review outputs of https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9568, cut bug tickets (or hand to Jill to cut), and synthesize results toward Q3 Events location work.

## Acceptance Criteria
- [x] Meet with Florence (Jill optional)
- [x] Bug tickets cut
- [x] Q3 Events Location epic updated for changes

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [X] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by fmccaf1** [comment]
@wesrowe I think we can call this done. Let me know if you disagree.
