### ISSUE TITLE
Change management for Facility COVID status launch

### ISSUE THREAD

**Issue by ContentBrewmaster** [department-of-veterans-affairs/va.gov-cms#9652]
The change represented by the epic #[9096](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9096) will be a site-wide change to appearance or key functionality, and change the front end and be highly visible to the public.
 
**1. Describe the change from the perspective of VA employees, in plain language. What is the employee going to experience with this change?**
VAMC editors will have a new way of customizing COVID-19 facility operating status to reflect a facility's policies for visitation and making appointments.

**2. Explain why the change is necessary from a CMS/platform and project goal perspective.** 
The implementation of COVID-19 facility operating status requires editors to select a status that correlates to nationally-standardized language. During the roll-out/adoption in May 2022, some facilities expressed concern that their local policies don’t align with the national language. This resulted in some facilities not adopting the new messaging protocol. In addition, for those that did adopt the messaging, the visitor policy directing Veterans to "ask your care team who can visit" has resulted in an increase of calls to local facilities.

![image](https://user-images.githubusercontent.com/92043982/176717014-536447f5-fec3-46d3-897c-6cb1b45daa9e.png)

**3. Select the role(s) impacted by the change.**
- [ ] All CMS users
- [ ] All CMS editors
- [ ] Vet Center editor
- [x] VA Medical Center editor
- [ ] VA Outreach Hub editor
- [ ] VA Benefits Hub editor
- [ ] Campaign landing page editor
- [ ] VA Resources and Support editor
- [ ] Offices editor
- [ ] Supporting roles such as CMS account admin, Facilities or Public websites team member

**4. How will success be defined for this change?**
The CMS gives editors the ability to customize their facility COVID-19 facility status content while giving Veterans a consistent and useful user experience when they plan their visit.

**5. How will success be measured for this change (audit, survey, other types of research, etc.)?**
- [x] No help desk support is needed, as measured through help desk tickets
- [x] The content adheres to VA policies and standards for VA.gov, as measured through a dashboard tool and/or audit

**6. Does the change require new or updated:**
- [x] Knowledge Base article
https://prod.cms.va.gov/help/vamc/about-locations-content-for-vamcs/about-alerts-and-operating-statuses/how-to-edit-covid-19-status-for-a-vamc-facility
- [x] Training video
https://www.youtube.com/watch?v=BYwHFXa61C8
- [x] CMS UI support
- [ ] Announcement block

**7. Will the change be tested with users before release?**
- [x] Yes
- [ ] No

**8. Are there any known dependencies?**
FE

## Key Dates (pre-event communications, preview with User Support, launch date, post-event tasks)
TBD

**Comment by ContentBrewmaster** [comment]
Created ticket and assigned @rachel-kauff as editor and producer for KB article and video.

**Comment by rachel-kauff** [comment]
You got it @ContentBrewmaster. Can we build in a trigger that helps me understand when to go in and make the changes? It'll be hard for me to pick up on that otherwise, since I'm not on facilities.
