### ISSUE TITLE
Editorial experience for managing site alerts

### ISSUE THREAD

**Issue by rachel-kauff** [department-of-veterans-affairs/va.gov-cms#9663]
## Description
The new approach to structuring site alerts and CMS announcements in Drupal needs review/tweaks to the editorial experience to ensure people who are managing this content are:
- Following established standards
- See config options in language that's consistent with cms design system work and documentation

tldr; need to make sure the ed ex makes sense.

## Acceptance Criteria
- [x] Wireframe for editorial experience is drafted and reviewed w/ devs
- [x] Adjustments are implemented

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [x] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by rachel-kauff** [comment]
WIP mockup of ed ex: https://www.figma.com/file/zRhcoa0ckXCpb9Xdrm4DP0/Config-UI-for-announcement-blocks?node-id=0%3A1

**Comment by EWashb** [comment]
editorial experience passed off to dev for implementation in #9511
