### ISSUE TITLE
Design review on new site alert work

### ISSUE THREAD

**Issue by rachel-kauff** [department-of-veterans-affairs/va.gov-cms#9664]
## Description
We want to make sure the design intent of the old site alert and cms announcement blocks gets fully translated into the new module

## Acceptance Criteria
- [x] New work made available to designers in a pr environment
- [x] Meet with design/dev to identify any tweaks
- [x] Implement changes

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [x] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by EWashb** [comment]
@tjheffner could you provide a PR environment for this work, please?
