### ISSUE TITLE
Craft error message language for absolute link errors

### ISSUE THREAD

**Issue by rachel-kauff** [department-of-veterans-affairs/va.gov-cms#9670]
## Description
The system currently throws a form validation error when editors try to add urls from prod or a demo environment, which is helpful in preventing broken links. The error message itself needs revision in order to be plain language/ editor-friendly.

Current error message:
`"The link "link text" contains an absolute CMS URL (https://prod.cms.va.gov/health-care)`

Updated message:
`"Link text" uses a URL that's only available on the VA network. Update the link to a valid public-facing page.`

## Acceptance Criteria
- [x] UX writing for form validation message
- [x] Hand off to dev for new copy implementation
- [x] Form validation message is updated in drupal

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [x] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by rachel-kauff** [comment]
<img width="698" alt="Screen Shot 2022-07-14 at 1 39 43 PM" src="https://user-images.githubusercontent.com/41017988/179079115-ff3fcb47-e17f-4781-b266-dfd78b8d37ca.png">

**Comment by tjheffner** [comment]
this error message is currently found here: `docroot/modules/custom/va_gov_backend/src/Plugin/Validation/Constraint/PreventAbsoluteCmsLinks.php` should be a simple rewrite of the copy. I'll do this tomorrow

**Comment by tjheffner** [comment]
including the URL in the error message still per this slack conversation:
<img width="1430" alt="Screen Shot 2022-07-15 at 9 33 50 AM" src="https://user-images.githubusercontent.com/11279744/179267798-bdab82a1-ffd0-4701-971c-e2507adea9f0.png">
