### ISSUE TITLE
VAMC events listing: events location does not include Facility location

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#9681]
## Description
On VAMC Event listings, the location does not include the Facility, and should. 

### 6/14 VAMC Event list:
https://www.va.gov/boston-health-care/events/?selectedOption=past
![Screen Shot 2022-06-13 at 6 01 21 PM](https://user-images.githubusercontent.com/85581471/173471857-61fd27f6-3845-4910-9ebb-7b7ba5c3f264.png)

### Vs Design comps
![177844823-e56b08e4-d7cb-4356-9fa8-b5df22828754-1](https://user-images.githubusercontent.com/85581471/177874700-01638bfa-6a5a-4ab9-aa6c-cd495ee6d38a.png)

### Vs Single event:
Related to #9442 , where we partially fixed this on single event detail pages

<details>

https://www.va.gov/boston-health-care/events/46953/
![Screen Shot 2022-06-13 at 6 01 25 PM](https://user-images.githubusercontent.com/85581471/173471846-4eb4b213-35e1-4dac-81e2-7db9b6e3fee3.png)
</details>

## Acceptance Criteria
- [ ] Event location on list matches single event
- [ ] Event location lists linked facility location 
- [ ] Location lists "Building, floor or room" data
- [ ] Location lists "street address" data

## Additional context
Related tickets: 
- #9442
- #9681  (this ticket)
- #9719
- #9718

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [X] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by stefaniefgray** [comment]
Author of ticket VAHELP-4350 wrote in wondering about this today

Here is the Github ticket that this editor inspired: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9647

**Comment by jilladams** [comment]
@stefaniefgray Added a summary to the VAHELP ticket as internal note - what is true in prod today: 

**VA facility event:**  
- Event listings: 
  - does not show Facility link ([#9681](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9681) will fix)
  - shows “Building, floor or room”
- Event detail page: 
  - shows Facility link  (fixed by [#9442](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9442) )
  - shows “Building, floor or room”

**Non-VA location:** 
- Event listings:
  - shows “Building, floor or room”
  - shows Street address 
- Event detail page: 
  - does not show “Building, floor or room” ([#9719](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9719) )
  - shows Street address

**Outreach events (online):** 

- Event listings: 
  - does not show “Where:”, only register link ([ #9718](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9718) will fix)
- Event detail page: 
  - does not show “Where:”, only register link ([ #9718](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9718) will fix)
