### ISSUE TITLE
Root cause/discovery: timestamp data is being saved incorrectly / modified based on CMS user time zone

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#9684]
## Description

https://github.com/department-of-veterans-affairs/va.gov-cms/issues/6056

> I originally considered this a UX display issue, however it has been determined this is a data integrity problem/bug. For records showing incorrect times, the data is being saved into the database incorrectly. Consider the below table that shows timestamps differ despite the input being identical:
Screen Shot 2022-07-01 at 3 14 09 PM

> Here the data entered into the CMS was identical for an event with 3 occurrences. You can see how the timestamps change when the user had the 'New York' timezone. This is wrong: dates in Drupal are stored without timezone offset, and shouldn't change based on the current users' timezone.

> Next we need to determine where this is happening in the contrib module or it's php dependency on simshaun/recurr.

## Acceptance Criteria
- [ ] Origin of the timestamp saving bug is identified
- [ ] Scope is verified to confirm if it applies to Recurring events only, or all Events
- [ ] Ticket is cut for implementation of fix OR have a convo with PM to review why it's not our ticket to file/fix and determine next steps

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [X] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by dsasser** [comment]
I reported this bug on d.o here: https://www.drupal.org/project/smart_date/issues/3294350

**Comment by jilladams** [comment]
Thank you! For my own understanding: that module seems like it's actively
maintained. Is this a case where we might consider contributing a fix, or
where we would be wiser to wait for module maintainers to handle?

**Comment by dsasser** [comment]
The module is actively maintained, but this is a situation where we can contribute a patch to fix the issue if we can find the change that needs to be made.
