### ISSUE TITLE
[cms-ci] some SERVER variables are missing

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#969]
**Describe the defect**
Since the move of devshop to a new instance (#916), the new devshop instance does not have any of the environment variables (devshop api key, gov delivery keys...)   All the values are empty so things like the frontend build trigger is not working.

**To Reproduce**
1. On any PR environment go to phpinfo page an see that the values are missing.
2. Go to /admin/content/deploy and trigger a rebuild. Nothing happens.

**Expected behavior**
Build trigger functions
Other environment variable dependent items function correctly.

## Labels
- [/] Issue type (red) (defaults to "Defect")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [/] CMS objective (orange) (not needed for bug tickets)
- [ ] CMS-supported product (black)

**Comment by ElijahLynn** [comment]
Just manually ran `drush @hm variable-set devshop_tasks_api_key 12345678987987987987` (not real key) and it is working again. 

![image](https://user-images.githubusercontent.com/1504756/74291684-8bd0da00-4cea-11ea-9639-62f338630e96.png)

**Comment by swirtSJW** [comment]
Rebuilding the frontend works.   I am not sure about other items.    Has documentation been created for the next time we deloy a new CI server to make sure these items are covered?

**Comment by swirtSJW** [comment]
I added a bit of code to make sure the rebuild FE does not fail silently if missing ci data  #981

**Comment by ElijahLynn** [comment]
> Rebuilding the frontend works. I am not sure about other items. Has documentation been created for the next time we deploy a new CI server to make sure these items are covered?

We don't plan on doing a manual deploy of the CI server again, and future deploys will be 100% automated. We have the items documented that need to be added to our automated CI server deploys https://github.com/department-of-veterans-affairs/va.gov-cms/issues/916#issuecomment-583172970. If we do a manual deploy by chance, those steps will cover getting them added.
