### ISSUE TITLE
Refine next steps for Lovell

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#9690]
ACs
- [ ] Roadmap is added to #9656

**Comment by davidmpickett** [comment]
@kevwalsh Not sure if there is additional Lovell refinement you wanted to do from an engineering perspective in addition to the design refinement i closed out

**Comment by davidmpickett** [comment]
@swirtSJW - per conversation today, I will let you close this when you have stubbed out the dev tasks

**Comment by davidmpickett** [comment]
Dev backlog stubbed out here: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9656
