### ISSUE TITLE
New KB article: adding React widgets to CMS content pages

### ISSUE THREAD

**Issue by rachel-kauff** [department-of-veterans-affairs/va.gov-cms#9693]
## Background context
**Topic**
Sitewide Content could use a KB article on adding react widgets. 

**Person requesting the article:** 
- Randi Hecht, Sitewide Content Team

**Associated SMEs/ stakeholders:** 
- [name them here]

**Audience:** 
- Sitewide Content team editors

**Related KB articles:** 
- [Video demo](https://dsva.slack.com/archives/CDHBKAL9W/p1657034671951049?thread_ts=1652889551.131349&cid=CDHBKAL9W) showing how they use react widgets

  
**Associated source of truth documentation:** 
- [for example, could be the VA content style guide]

**This article addresses:**
- [ ] A business-driven need
- [x] A user-driven need

**Does this article have a deadline?**
- [ ] Yes: [name the deadline here]
- [x] No

**Is the article associated with change management initiatives?**
- [ ] Yes
- [x] No

**What parts of the interface will link to the article, if any?** 
- none

## Process
1. Refine and prioritize
2. Identify content needs
3. Draft article content 
4. Get peer review and/or stakeholder review (if necessary)
5. Publish

## ACs
- [ ] Article is reviewed by [assigned peer reviewer] and/or [SME/stakeholder]
- [ ] Article follows documented content style for the knowledge base
- [ ] Article is assigned to a parent 
- [ ] Impacts on other KB articles have been considered and any necessary changes have been made
- [ ] Help desk has been made aware of the new article
- [ ] (If appropriate) once published, the person requesting the article has been notified

**Comment by jilladams** [comment]
Note: Content team has this guidance around using the react widgets in CMS pages: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/sitewide-content/processes/dynamic-content-process.md

**Comment by FranECross** [comment]
@jilladams Looking at your note above, if the CMS has info on this already, and this was in the Icebox, do we really need to do it, or can I close? Thanks!

**Comment by jilladams** [comment]
Yep, probably ok to close this since CAIA is carrying the torch for this documentation.
