### ISSUE TITLE
Content Audit: Veteran Crisis Line 

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#9696]
## Describe the request
Content audits can be performed by searching the codebase and compiled site for specific terms ur using an audit tool within drupal. 
Please provide any context for the audit, any related terms or alternate spellings, or and related components that could return content you are interested in.

Context: 
* Terms of interest: "Veteran Crisis Line phone number ([800-273-8255](tel:8002738255))" - specifically the phone  number. Mid-to-end of July, this number will be changing. The old number will still be working, but switching to "tel:988".
* Alternate spellings / terms: 
* Related components or text formats (such as tables, buttons, italic or linked text):
  - [ ] rich text
  - [ ] phone number links
  - [ ] alerts
  - [ ] etc 
* Othering things we'd like to know if possible
  * content type
  * component
  * which product the content is connected to 
  * which sections the content belongs to
  * how many of these are linked as phone numbers, or just stored as text

Who needs to see the results of this audit? 
- [ ] Public websites team (for things like the header)
- [ ] VA services taxonomy owner (eg Dave / Facilities)
- [ ] Sitewide contenrt team 

Possible followups: TBD.

### Implementation date

When does this request need to be complete?: 

Sprint 62 - July 15th.

Please submit all engineering requests **at least 1 full sprint in advance** (so we can work it into our next sprint).

## CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [x] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by msbtterswrth** [comment]
I've done an initial audit of all *rich text fields* in every drupal entity (paragraphs, nodes, alerts, blocks) and have exported my findings [here](https://github.com/department-of-veterans-affairs/va.gov-cms/files/9048971/crisis-hotline.csv). The _vast_ majority of these are stored as links, like maybe +95%. 

I need to do a separate audit of phone number fields specifically which I'll include here when it's ready.

**Comment by msbtterswrth** [comment]
There are 329 instances of this phone number found in CMS content fields. Houston and Wilmington sections both have the high number of uses at 18, followed by Puget Sound, Charleston and Northern CA at 8. 

Crisis line phone number appears in these fields:
![image](https://user-images.githubusercontent.com/8375335/177615724-45a761ef-d9ab-41e9-9e72-6fb3c6afe305.png)

And these content types: 
![image](https://user-images.githubusercontent.com/8375335/177615590-a7b8daf2-7beb-414b-9383-6e74dc309ad9.png)


Full data can be found in this [airtable](https://airtable.com/shrngt7aaXoIwAenS).
