### ISSUE TITLE
Kick off Collab Cycle for Income Limits App

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#9702]
## Acceptance Criteria
- [x] - Create [product brief](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/income-limits-app)
- [x] - Write collab cycle kickoff issue
- [x] - Draft [user research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/income-limits-app/research/research-plan.md) - _Note: does not include Conversation Guide (linked from plan)_
- [x] - Any other documentation needed for collab cycle kickoff

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by wesrowe** [comment]
@jilladams, note that this issue is at risk if we can't get more info from Dave soon. 🟡

**Comment by jilladams** [comment]
[slack](https://dsva.slack.com/archives/C52CL1PKQ/p1657307733405549?thread_ts=1657288822.445519&cid=C52CL1PKQ)
Ticket was created out of S62 planning discussion, & should be tagged S62.

**Comment by jilladams** [comment]
From Dave - technical topic for kickoff meeting: we need to consider where is the data now (the tables, databases, other sources of truth) vs. a future system we can use to store the data in future, in terms of support/maintenance, etc. Don't know if we need to build a solution or if we can follow an existing model. Data needs to be relatively easy to maintain.

**Comment by wesrowe** [comment]
note: I removed stakeholder contacts/scheduling from the ACs since they're not under the team's control. (originally listed as optional)

**Comment by wesrowe** [comment]
Kickoff issue submitted, https://github.com/department-of-veterans-affairs/va.gov-team/issues/44321
