### ISSUE TITLE
[Events] Filters: audit for next rev

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#9705]
## Description
Events V2 filters shipped in Q3 2022. The current scope of the filters is: 

- **Upcoming events**
  - All upcoming single events, after now. (Events scheduled on today's date before the current hour will not show as Upcoming.)
  - The nearest 1 upcoming recurrence of a recurring event. e.g. a recurring event with instances today tomorrow and the day after will only show today's recurrence.
- **Specific date**
  - All single events on that date
  - All recurrences of recurring events on that date
- **Custom date range**
  - All single events on those dates
  - All recurrences of recurring events on those dates
- **Past events**
  - All past single events, before today. (Events scheduled on today's date before the current hour will not show as Past.)
  - All recurrences of a recurring event before today

For the next rev of events, we want to revisit this scope, identify any user-reported issues or inconsistencies, and revise the behavior if/as needed. 

Related conversation: https://dsva.slack.com/archives/C52CL1PKQ/p1656683606887089

## Acceptance Criteria
- [ ] Editor and veteran reported issues with filters are analyzed for recurring themes or bugs / edge cases in filter logic
- [ ] Thorough UX review is performed on current prod events / filters to identify any inconsistencies
- [ ] CONFIRM: Veteran user research is done to identify usability.
- [ ] Findings are summarized in a comment on ticket before closing, including recommendations for path forward.

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [X] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by FranECross** [comment]
Filters will be revisited in Events v3 and a new ticket created. Closing per Dave C.
