### ISSUE TITLE
Event listing is showing the wrong time 

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#971]
**Describe the defect**

Report from a content creator on Outreach Hub
```Good evening Howie,

Question for you. on the https://www.va.gov/outreach-and-events/events/ site.

Leesburg, Virginia Community Veterans Engagement Board (https://www.va.gov/outreach-and-events/events/events)

When:

April 15, 2020
12:30 AM – 2:00 AM

However, if you click on this shortcut Leesburg, Virginia Community Veterans Engagement Board (https://www.va.gov/outreach-and-events/events/events) it says.

Tuesday, Apr 14
8:30 p.m. – 10:00 p.m. ET

Which actually still isn’t correct, because in the CMS portal when I entered the information I entered:

CONTENT

DATE AND TIME

Tue, 04/14/2020 - 19:30 - Tue, 04/14/2020 - 21:00

And since this was posted in the east coast the time it should stay 7:30pm-9:00pm or 19:30-21:00 not 8:30-10:00pm.  

Is this a glitch in the system or part of the patch code, if so is there anything on my end that I need or can do to correct these ? Also, do you have an update or time frame on the order of the events being corrected.

I know there are a lot a lot of moving parts to this system, and I appreciate all the time you have put into keeping me in the loop.
```

**To Reproduce**
See above.

**Expected behavior**
The event should be posted with the same times as what's entered in the CMS, not have any time zone conversion.

**Screenshots**
CMS
![Edit_Event_Leesburg__Virginia_Community_Veterans_Engagement_Board___VA_gov_CMS.jpg](https://images.zenhubusercontent.com/5d6e57ad330f64311395f08b/63cfa6ea-59f0-4d95-a9b5-bd113cb1e1e2)

Event listing
![Outreach___Events___Outreach_Events___Veterans_Affairs.jpg](https://images.zenhubusercontent.com/5d6e57ad330f64311395f08b/cd47b16f-ff9c-4240-adb4-3cbc3a56f457)

Event node

![Outreach_events___Leesburg__Virginia_Community_Veterans_Engagement_Board___Veterans_Affairs.jpg](https://images.zenhubusercontent.com/5d6e57ad330f64311395f08b/1db6b517-522e-4f51-ac45-ca2281d32592)

**Comment by ethanteague** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/11681 @kevwalsh

**Comment by ethanteague** [comment]
@kevwalsh at present, time formatting works like this:
1) user enters time in drupal
2) time is displayed in ET in front end build (with `ET` appended to end time)

**Comment by kevwalsh** [comment]
@howardbrande can you validate that the times are displayed as expected, then move this to Done?

**Comment by howardbrande** [comment]
@kevwalsh this is validated
