### ISSUE TITLE
Change management for Veterans Crisis Line

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#9716]
The change represented by the epic #9715. 

**1. Describe the change from the perspective of VA employees, in plain language. What is the employee going to experience with this change?**

CMS editors will see a new phone number for the Veteran Crisis line on VA.gov. The number will have been programmatically changed from 800-273-8255 to 988 by the CMS team. Editors will be told:
- phone number is changing
- we've done this for you 
- if your content is in draft, we've left it in draft
- we didn't touch News releases, Stories, or Events (pending)
- you can validate

**2. Explain why the change is necessary from a CMS/platform and project goal perspective.**
On July 16, 2020, the FCC [adopted rules](https://www.fcc.gov/document/designating-988-national-suicide-prevention-lifeline-0) to establish 988 as the nationwide, easy-to-remember 3-digit dialing code for Americans in crisis to connect with suicide prevention and mental health crisis counselors.  

This change will impact what Veterans see when they click _Talk to the Veterans Crisis Line now_ link in the global header on VA.gov:
![image](https://user-images.githubusercontent.com/92043982/178823902-5a44aaf5-ec4a-4e27-a119-dbf47b71004e.png)

**3. Select the role(s) impacted by the change.**

[Audit](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9696)

- [ ] All CMS users
- [ ] All CMS editors
- [ ] Vet Center editor
- [x] VA Medical Center editor
- [ ] VA Outreach Hub editor
- [x] VA Benefits Hub editor
- [ ] Campaign landing page editor
- [ ] VA Resources and Support editor
- [ ] Offices editor
- [ ] Supporting roles such as CMS account admin, Facilities or Public websites team member

**4. How will success be defined and measured for this change?**
- [x] No help desk support is needed, as measured through help desk tickets
- [ ] The content adheres to VA policies and standards for VA.gov, as measured through a dashboard tool and/or audit

**5. Does the change require new or updated:**
- [ ] Knowledge Base article(s)
If existing articles, list URLs:
- [ ] Training video(s)
If existing videos, list URLs:
- [ ] CMS UI support
- [ ] Announcement block

**6. Will the change be tested with users before release?**
- [ ] Yes
- [x] No

**7. Are there any known dependencies?**

## Key Dates
- July 13: pre-event communication at VHA Digital Media Office Hours with VAMC editors
- July 16: script invoked to change 800-273-8255 to 988
- July 18: VHA DM sends email to VAMC editors while CMS team sends email to Benefit Hub editors.
- July 30: reporting of any help desk tickets to VHA Digital Media

**Comment by dsinla** [comment]
@ContentBrewmaster  - Can you confirm any comms are on hold?

**Comment by ContentBrewmaster** [comment]
They are, pending notification from the CMS team that the change is complete. Is it?
