### ISSUE TITLE
Event detail page & Event listing: Ensure Online events indicate that they are online

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#9718]
## Description

Currently in production, online events sometimes fail to display a location. 
Designs show that online events should show text: **Where**: This is an online event

**In Production:**
![image.png](https://images.zenhubusercontent.com/61a671f5fc46c2a311655f75/a6bd9b50-a8a8-4e42-9d7c-2877dece45de)

**Vs. design for online events**
https://www.sketch.com/s/8ec18b80-a905-47fb-a217-5720450befa1/a/L0Q1K7L
![Screen Shot 2022-07-07 at 2 21 17 PM](https://user-images.githubusercontent.com/85581471/177873725-3da68c61-a5dc-439c-9c52-51d3e4f8790e.png)

## Acceptance Criteria
- [x] Event detail page: Online events show "**Where**: This is an online event"
- [x] Outreach & Event listing: Online events show "**Where**: This is an online event" https://www.va.gov/outreach-and-events/events/
- [x] VAMC Event listing: Online events show "**Where**: This is an online event"  https://www.va.gov/minneapolis-health-care/events/
- [x] Requires design review - @fmccaf1 (in staging or local env)
- [ ] Verify in prod before we close & notify @jilladams when it's live

## Additional context
Related tickets: 
- #9442 - DONE
- #9681 
- #9719
- #9718 (this ticket)

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by wesrowe** [comment]
May be solved by #9681, so wait till that's deployed to attempt reproducing.

**Comment by jilladams** [comment]
I don't think #9681 is tied in here. Per @maxx1128 , Event detail pages (like this bug) are managed in content-build, and event listings (#9681) are managed in vets-website, so I think this issue is not blocked by that work.

**Comment by jilladams** [comment]
@wesrowe e.g. https://prod.cms.va.gov/outreach-and-events/events/47174  Virtual events offer the URL field, and confirmed it's not required. 

This is probably a design intent and/or Editor experience question. In that example, if I click the Register link on https://www.va.gov/outreach-and-events/events/47174/, I'm taken to https://us02web.zoom.us/meeting/register/tZUtc-6urDgvH9OIsa3a3PB7RiNdMAIhU8Rj where I register. Presumably that registration process ends in a calendar invite / link to attend. (Didn't want to submit test data.) I don't know if it's valid that editors know the event link when they create the CMS event? But we could maybe ask Kenny Kimbrell (author of the example event) to find out.

**Comment by fmccaf1** [comment]
Here are screenshots of the sketch designs mentioned and linked above ^ 

![image](https://user-images.githubusercontent.com/106624475/177844635-abf46549-75a1-4d0a-a987-6548c4b4b97d.png)

![image](https://user-images.githubusercontent.com/106624475/177844702-574ff7bd-9b82-45b3-a037-19ae2ce2bc02.png)

**Comment by jtmst** [comment]
https://github.com/department-of-veterans-affairs/content-build/pull/1213
https://github.com/department-of-veterans-affairs/vets-website/pull/21642
