### ISSUE TITLE
Event detail page: Display "Room/building" field on FE for non-VA location events

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#9719]
## Description

As a Veteran, I want to see the data entered by an Editor into the "Building, floor, or room" field, so that I can have all the info available to find the event.

Currently, non-VA location events allow editors to fill "room" field, but veterans can't see the data. 

**In production**
Front end: https://www.va.gov/central-iowa-health-care/events/47347/
CMS: https://prod.cms.va.gov/node/47347/edit

![image.png](https://images.zenhubusercontent.com/61a671f5fc46c2a311655f75/1b4e0899-dff8-44c5-9ecd-36f18d9d7676)

**Vs. Design comps**

## Acceptance Criteria
- [x] Events with Location type: non-VA facility display building/floor/room data, if available.
- [x] Requires design review
- [ ] Verify in prod before we close & notify @jilladams when it's live

## Additional context
Related tickets: 
- #9442
- #9681 
- #9719 (this ticket)
- #9718

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by wesrowe** [comment]
May be solved by #9681, so wait till that's deployed to attempt reproducing.

**Comment by jilladams** [comment]
I don't think #9681 is tied in here. Per @maxx1128 , Event detail pages (like this bug) are managed in content-build, and event listings (#9681) are managed in vets-website, so I think this issue is not blocked by that work.

**Comment by jilladams** [comment]
Discovered that some editors are entering non-VA location street address data to work around #9681, e.g. in comments on https://va-gov.atlassian.net/browse/VAHELP-4350
> Our hospital is holding an event at a Vet Center. I added the Event and tried to pull up the Vet center as a “VA facility” but it didn’t exist. Do they not count as VA facilities? 
> My workaround was easy, I just added it as a non-VA facility…no biggie. So I was just wondering. The Vet Center does exist in the Drupal platform, so i figured they can’t connect because Vet Centers aren’t medical? 
> I added the locations as free text using the address formatting option as a workaround. Doesn’t look too bad but you have to open the event to see it.

It sounds like:
- If VAMC location: then VAMC Facility link should show, with Room / Building info. (Treated in comps)
- If not a VAMC location: then street address should show. 
  - Should Room / building info should show for non-VAMC location events? 
   
Comps do not treat that case. I think that's something to confirm with @davidconlon and designers before we assign this ticket

**Comment by wesrowe** [comment]
> Our hospital is holding an event at a Vet Center. I added the Event and tried to pull up the Vet center as a “VA facility” but it didn’t exist. Do they not count as VA facilities?

@jilladams, it sounds to me like the Editor was talking about a CMS-side issue – i.e., their Vet Center wasn't an option for the location of an event in the CMS. 

@kevwalsh, are Vet Centers supposed to be select-able as event locations?

> Comps do not treat that case. I think that's something to confirm with @davidconlon and designers before we assign this ticket

Regarding whether to display room/building (aka "free text" per Editor) on non-VA event listings, Dave confirmed in a meeting the other day that the answer is: Yes, we should display all the data that an Editor enters. So this issue is valid and should be assigned if it's not solved by another fix.
