### ISSUE TITLE
Document collab cycle 508 review standards

### ISSUE THREAD

**Issue by msbtterswrth** [department-of-veterans-affairs/va.gov-cms#9734]
As a Sitewide Crew member, I need documented standards for proposed changes to the CMS editorial interface so that I know when to kick off a CMS collab cycle review.

ACs
- [x] Create touch point review standards for accessibility/508 compliance within the collaboration cycle

**Comment by laflannery** [comment]
Borrowed from Platform  - added [Staging review for accessibility](https://va-gov.atlassian.net/wiki/spaces/VAGOV/pages/1802633217/Staging+Review+-+Accessibility)

**Comment by EWashb** [comment]
looks good.
