### ISSUE TITLE
Document collab cycle change management standard/review process

### ISSUE THREAD

**Issue by msbtterswrth** [department-of-veterans-affairs/va.gov-cms#9735]
As a Sitewide Crew member, I need documented standards for proposed changes to the CMS editorial interface so that I know when to kick off a CMS collab cycle review.

ACs
- [x] Create touch point review standards for change management within the collaboration cycle

**Comment by EWashb** [comment]
@ContentBrewmaster do you have the CM standards documented anywhere? Or should we just look at the CM Github template? I wanted to account for CM in our collab cycle but would love to get your feedback on how to make it the most appropriate for the need.

**Comment by ContentBrewmaster** [comment]
The CM documentation set includes:
- [CM template in Git](https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/.github/ISSUE_TEMPLATE/change-management.md)
- [CM playbook](https://docs.google.com/document/d/1TpxMGKlkiuU4rPGs4NIY19NyCPN6y3crzg8mvQqaT_I/edit#heading=h.nz7728aj67w0)
I'm looking to put these in Confluence at some point.

**Comment by EWashb** [comment]
Require product teams to bring about the CM plan to kickoffs. PMs will need to drive.

**Comment by EWashb** [comment]
Denise added these to the confluence before she offboarded
