### ISSUE TITLE
[Spike] Audit CMS Build and Deployment Tasks

### ISSUE THREAD

**Issue by olivereri** [department-of-veterans-affairs/va.gov-cms#9765]
## Description
As a DevOps engineer, I need to review the configuration tasks that occur during BRD™ Build and Deploy stages, so that I can determine if these tasks are executed in the appropriate stage. Additionally, I need to determine which tasks are critical to the functioning of the website, so that the server image is pre-configured to run the site immediately after boot-up.

### Example
For example, SSOi IAM Team's public certificates are configured in two places. In the va.gov-cms repo and devops repo. Configuring this **only** in the va.gov-cms repo will ensure that the Production server image is always ready to communicate with the SSOi servers.

## Acceptance Criteria
- [x] A list of tasks is generated that collects what is executed and configured during Build and Deploy
- [x] Determination made on tasks that must be pre-run so that CMS works immediately after boot
- [x] Create follow-on tickets to move any identified tasks between stages

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [x] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by olivereri** [comment]
## Deployment Tasks
### cms Deploy Live Steps for prod

## Runtime Tasks
### CMS every-minute tasks run on prod
### Report CMS Content Release Metrics to Prometheus
### CMS periodic tasks run on prod
### Sanitize database on prod.cms.va.gov
### Backup database on prod.cms.va.gov
### META pipeline DB/EFS backup and sanitize
### Backup EFS sites/default/files/ on prod.cms.va.gov
### CMS daily-0800 tasks run, stored in va.gov-cms repo.
### CMS daily tasks run, stored in va.gov-cms repo.

**Comment by ndouglas** [comment]
I preëmptively added the every-month task that's anticipated to be added to Jenkins and CMS this sprint (sprint 82).
