### ISSUE TITLE
Change management for Reusable Q&A Groups on R&S Detail Pages

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#9774]
The change represented by the epic # will `Be a site-wide change to appearance or key functionality (such as log-in process)`.
 
**1. Describe the change from the perspective of VA employees, in plain language. What is the employee going to experience with this change?**

Editors will gain the ability to 
- Add a "Q&A Group" content block to Resources & Support Detail Pages.
- Search for existing reusable Q&A content to add to the Q&A Group.

> Example: Editors visiting prod.cms.va.gov will see a new screen directing them to log in with PIV. Once logged in they will experience a new look and feel to the CMS interface.

**2. Explain why the change is necessary from a CMS/platform and project goal perspective. Link to screenshots if that helps tell the story.**

Editors & Sitewide Content Team are excited to be able to reuse Q&As in more places, makes content more maintainable and helps efficiency.

**3. Select the role(s) impacted by the change.**
- [ ] All CMS users
- [ ] All CMS editors
- [ ] Vet Center editor
- [ ] VA Medical Center editor
- [ ] VA Outreach Hub editor
- [ ] VA Benefits Hub editor
- [ ] Campaign landing page editor
- [x] VA Resources and Support editor
- [ ] Offices editor
- [ ] Supporting roles such as CMS account admin, Facilities or Public websites team member

**4. How will success be defined for this change?**

SW Content team Editors will provide feedback in case of issues – they're really driving this.

**5. How will success be measured for this change?**
- [ ] No help desk support is needed, as measured through help desk tickets
- [ ] The content adheres to VA policies and standards for VA.gov, as measured through a dashboard tool and/or audit

**6. Does the change require new or updated:** _I don't know_
- [ ] Knowledge Base article(s)
If existing articles, list URLs:
- [ ] Training video(s)
If existing videos, list URLs:
- [ ] CMS UI support
- [ ] Announcement block

**7. Will the change be tested with users before release?**
- [x] Yes - SWContent team editors will kick the tires on CMS side. No expected changes to FE experience.
- [ ] No

**8. Are there any known dependencies?**

## Key Dates (pre-event communications, preview with User Support, launch date, post-event tasks)

None set; release timing will depend on FE development, as Drupal will be developed first.

**Comment by ContentBrewmaster** [comment]
Removing dupe for issue #9775.
