### ISSUE TITLE
Change management for Reusable Q&A Groups on R&S Detail Pages

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#9775]
The change represented by the epic #8630 will `Be a site-wide change to appearance or key functionality (such as log-in process)`.
 
**1. Describe the change from the perspective of VA employees, in plain language. What is the employee going to experience with this change?**

Editors will gain the ability to: 
- Add a "Q&A Group" content block to Resources & Support Detail Pages.
- Search for existing reusable Q&A content to add to the Q&A Group.
![image](https://user-images.githubusercontent.com/92043982/178831844-5b0ec58b-611c-4425-848b-0b5432a88ac1.png)

**2. Explain why the change is necessary from a CMS/platform and project goal perspective. Link to screenshots if that helps tell the story.**

Editors & Sitewide Content Team are excited to be able to reuse Q&As in more places. This change will make content easier to maintain and improve efficiency.

**3. Select the role(s) impacted by the change.**
- [ ] All CMS users
- [ ] All CMS editors
- [ ] Vet Center editor
- [ ] VA Medical Center editor
- [ ] VA Outreach Hub editor
- [ ] VA Benefits Hub editor
- [ ] Campaign landing page editor
- [x] VA Resources and Support editors (Sitewide Content team)
- [ ] Offices editor
- [ ] Supporting roles such as CMS account admin, Facilities or Public websites team member

**4. How will success be defined for this change?**
Content team editors can create Q&A content blocks in the CMS.

**5. How will success be measured for this change?**
- [x] No help desk support is needed, as measured through help desk tickets (User Support to inform Public Websites team via Slack)
- [ ] The content adheres to VA policies and standards for VA.gov, as measured through a dashboard tool and/or audit

**6. Does the change require new or updated:** _I don't know_
- [ ] Knowledge Base article(s)
If existing articles, list URLs:
- [ ] Training video(s)
If existing videos, list URLs:
- [x] CMS UI support
- [ ] Announcement block

**7. Will the change be tested with users before release?**
- [x] Yes - Sitewide Content team editors will test new Q&A Group content block on Resources and Support detail page in Tugboat. There are no expected changes to FE experience.
- [ ] No

**8. Are there any known dependencies?**
FE development

## Key Dates (pre-event communications, preview with User Support, launch date, post-event tasks)

None set; release timing will depend on FE development, as Drupal will be developed first.

**Comment by jilladams** [comment]
@ContentBrewmaster this change will ship fully in our next sprint. Let me know if you have questions / want to chat about it.

**Comment by ContentBrewmaster** [comment]
Thanks for the update @jilladams. I do have a couple of questions:
- Would you need support to craft any email messages announcing the change to the sitewide content team, or is that being handled less formally by your team?
- is there any guidance being written for this change and if so, where will it be kept?

**Comment by jilladams** [comment]
We are handling SWC rollout informally. 
We haven't drafted any guidance, because of ^, but will likely need to do that at the point that it gets prioritized to roll R&S development out to more editors. That's been mentioned as a future project, but isn't a priority right now afaik. 

Takeaway: I'm not sure what there is for you to do here, but we have this epic! Maybe that means no-op, if we confirm with  Danielle next week that this will stay an SWC capability for the near term?

**Comment by jilladams** [comment]
Launched: https://dsva.slack.com/archives/C01K37HRUAH/p1661898819583139
