### ISSUE TITLE
Create Platform Feature Request ticket to release Cerner "API" to dependent teams via DEPO Platform docs

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#9786]
## Description

Once the Drupal-driven cerner flag is available and validated in Prod, we would like to publish API docs within the Plat DEPO documentation, similar to https://depo-platform-documentation.scrollhelp.site/developer-docs/teamsite-overview. Teams should also find the data in `vamc-ehr.json` useful for enhancing their UX with system names (eg, Central OH instead of Chalmers P Wylie).

Docs drafted under #9248 are here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/public-websites/Cerner-Support/cms-source-of-truth/opt-in-drupal-source-of-truth.md

### **RISK:** Per Shira Goodman: 
> I'm not sure if we have a policy for allowing non-Platform teams to add content to Platform Website. I'd recommend you follow the guidance for [Submitting a feature request](https://depo-platform-documentation.scrollhelp.site/support/submitting-a-feature-request), and detail the page you'd like to add and why. Platform will follow up and hopefully be able to connect you with a team that can help.

There's a chance that the Platform team won't allow this doc to be published in their space, so the Acceptance Criteria stop with FR to request it. If declined, we'll need a new ticket to work out how / where to publish.

## slack threads
How to add the page: https://dsva.slack.com/archives/CBU0KDSB1/p1657152841413799
request for perms: https://dsva.slack.com/archives/CBU0KDSB1/p1657824692753929 - final answer: Platform teams are only teams to create Platform docs

## Acceptance Criteria
- [ ] Documentation is up to date with the final state of the code. Verify with @ryguyk 
- [ ] Create feature request to add the doc
- [ ] Cut any follow up tickets needed for prod verification once feature req ticket is resolved

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by jilladams** [comment]
Swirt convo: https://dsva.slack.com/archives/C03LFSPGV16/p1659020653893159

**Comment by jilladams** [comment]
Requests reviewed monthly: https://dsva.slack.com/archives/CBU0KDSB1/p1660139523094139?thread_ts=1657824692.753929&cid=CBU0KDSB1 
> Hi Jill, thanks for letting us know that there hasn't been a response to your submitted request.  I've now posted it in the proper evaluation channel so the platform crew teams will be made aware.
For reference, these requests are currently reviewed on a monthly interval.  Please reach out on the platform-service-design channel with any other questions.  Thanks!

**Comment by jilladams** [comment]
Final published doc: https://depo-platform-documentation.scrollhelp.site/developer-docs/how-to-opt-in-to-drupal-as-the-source-of-truth-for
