### ISSUE TITLE
Income limits: Prep for Design Intent meeting (collab cycle)

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#9793]
## Description

The Design Intent meeting requests a user flow artifact. We should document our ideas before requesting a DI meeting.

- [x] Discussion guide draft - 3hrs remaining
- [x] Research plan draft - done
- [ ] Review/revisions

## Acceptance Criteria
- [x] Create [user flow hypothesis](https://app.mural.co/t/vagov6717/m/vagov6717/1657807571797/ee2497db0a9c637538f51e38546ffe3eaea508c0?sender=ua604735c5cf1162b042a4310)
- [x] Seek input from SW Content team
- [x] (optional) Schedule DI meeting (optional because Dave PTO might affect scheduling)
- [x] Draft discussion guide(s)

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by fmccaf1** [comment]
At this point, drafts are completed and this issue is blocked, waiting on hearing back from content team and Dave.

**Comment by jilladams** [comment]
Noted to Dave in email that this ticket may span sprint boundary due to dependency on both Danielle and Dave's time.

**Comment by fmccaf1** [comment]
Everything but scheduling of DI meeting is done here.

**Comment by fmccaf1** [comment]
Design intent scheduled. Closing ticket.
