### ISSUE TITLE
Send broken link metrics from the CMS to Datadog

### ISSUE THREAD

**Issue by cweagans** [department-of-veterans-affairs/va.gov-cms#9800]
## Description

After https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9799 is done, we should send segmented metrics to Datadog.

## Acceptance Criteria
- [ ] CMS sends metrics to Datadog for
	- [ ] Total number of broken links
	- [ ] Number of broken links by section
	- [ ] Number of broken links by publishing status

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [x] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by swirtSJW** [comment]
[slack thread discussing the three ACs](https://dsva.slack.com/archives/CT4GZBM8F/p1663725118084639)

**Comment by timcosgrove** [comment]
Closing as not needed; customer (Sitewide Crew) does not desire the information in Datadog.
