### ISSUE TITLE
File names save revision information upon save.

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#9803]
## Description
Media asset filenames will be updated to include revision information. This is necessary to support content-release, since S3 file assets will publish immediately but the content pointing to the new version of an asset would not be in sync with it for some time.

## Acceptance Criteria
- [ ] When a new file entity is created or updated, the file path is updated to `<file_name>-<revision_id>.<file_ext>`
- [ ] There is no disruption to CMS asset usage or content release referencing file assets.

## Implementation notes
There is no need to modify existing assets. If they are updated, they will be modified.

The filename parsing should be done with care. We do not want to see a propagation of revision IDs, i.e. `<file_name>-<revision_id>.<file_ext>` should not become `<file_name>-<revision_id>-<new_revision_id>.<file_ext>` upon updating. This may involve validating that the existing ID on the filename corresponds to an existing revision ID. Some cases to consider and account for:
* existing revision id
* filenames that fit the pattern `<something>-<somenumbers>.<file_ext>` where `<somenumbers>` is part of the proper filename, rather than the revision id
* filenames with multiple dots

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [x] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by cmaeng** [comment]
when someone saves an image change they will become public. since the html that references them will not become public, we want to make sure that these are in sync.

**Comment by timcosgrove** [comment]
In discussion with engineers on our teams, we realized that files themselves are not revisionable in the way described here. If a file name already exists in the CMS, and something of the same name is added, _0.jpg or similar will be added to it. This is true even if the file is deleted from the entity it is attached to.

In the future, if we do treat files in a 'source of truth' way, they will need to become revisionable. Doing that is beyond the scope of the current effort.

**Comment by timcosgrove** [comment]
Closing as not needed.
