### ISSUE TITLE
Files are uploaded to S3 upon save

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#9804]
## Description
As part of intermediate work, files should be saved to both S3 and to the local file system, until we feel secure that the S3 filesystem is stable and have converted all file storage to S3. 

## Acceptance Criteria
- [x] Upon save/upload of a 'local' filesystem file, a copy of that file will also be saved to its equivalent location on S3. 

## Implementation details
Careful attention needs to be made to make sure this is the last hook/event which runs to allow for other module's file processing to occur. All derivatives of files also need to be updated; any derivative generation should result in the same derivative being uploaded to S3.

* We talked about using a single stream wrapper that writes to both the `public://` and `s3://` stream wrappers. In the short term, the only extra thing this should do is write the file data to s3 in addition to public, but down the road we should be able to start flipping things from public to s3. Eventually, when everything in this intermediate stream wrapper is pointing to s3, we should be able to remove this intermediate stream wrapper so that files are written directly to s3.

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [x] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by cmaeng** [comment]
With #11130 also in this sprint and a higher priority, we will try to get as much of this done as we can but are expecting this to carry over.

**Comment by cmaeng** [comment]
This was not started in sprint 69 due to support around the Linky implementation and troubleshooting issues that arose.

**Comment by timcosgrove** [comment]
This is taken care of by DataSync. Closing.
