### ISSUE TITLE
Convert media fields to use S3 file wrapper

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#9810]
## Description
Existing media entities should be modified to use the S3 file wrapper, rather than the local file system.

## Acceptance Criteria
- [ ] Media entity file fields are updated to use the S3 file wrapper
- [ ] A queue worker or otherwise recurring job is created to convert individual media entities to use the new file field
- [ ] Any reference to a media asset using an S3 file wrapper should output a complete S3-compatible URL to 
- [ ] File references output by GraphQL and JSON:API reference the full URL to S3 for any converted media entities
- [ ] There is no disruption to media usage on the CMS or in content builds from that CMS

## Implementation details
Despite the CMS's warnings, the existing file field on a media entity can in fact be updated to use the new wrapper. This will not immediate affect existing media entities, but new ones will use the new wrapper.

Existing media entities will need to be updated to point to the new location. Because each saving of an entity generates a new revision of a file as well, it *may* be enough to simply load the file and save it, triggering a new revision and therefore that new revision's file being uploaded to S3. This needs to be tested, however.

There are over 15000 media entities, and so this cannot be done as part of an update hook. It should be set up as a recurring job or queue worker that operates on a reasonable subsection of remaining media entities that have not been updated. 

Care should be taken that updating a media entity directly causes entities *referencing* that media entity to point to the correct entity.

As part of this work, Media entities that have been converted to S3 should continue to save files to the local filesystem, as they did before. This is analogous to the work done for https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9804.

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [x] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by TheBoatyMcBoatFace** [comment]
@timcosgrove with S3 transition, this all looks applicable, but too much work for a single issue. I'm closing so that we can more easily break down the S3 To-Dos once we finalize the  transition plan.

Reopen if necessary.
