### ISSUE TITLE
CMS editorial accessibility audit for the Vet Center Product

### ISSUE THREAD

**Issue by EWashb** [department-of-veterans-affairs/va.gov-cms#9811]
## Background

As the Accessibility Lead for Sitewide CMS is doing audits of specific products across the CMS. The Vet Center product needs full auditing after work completed in #9679.  

## Acceptance Criteria

- [x] consult with helpdesk for best editor to log in as
- [x] audit on staging
- [x] Vet Center specific-content types are reviewed
- [x] Similar content areas/defects documented across products

**Comment by laflannery** [comment]
This was discussed with Dave last week that we wouldn't be moving forward with this immediately after completing the VAMC product audit - we established new steps we wanted to complete first.

**Comment by EWashb** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VAgov-CMS-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/9811?planning-poker) with ZenHub @laflannery

**Comment by laflannery** [comment]
Issues added to google sheet and github
