### ISSUE TITLE
CMS accessibility audit for the Resources and Support product

### ISSUE THREAD

**Issue by EWashb** [department-of-veterans-affairs/va.gov-cms#9812]
## Background

As the Accessibility Lead for Sitewide CMS is doing audits of specific products across the CMS. The R&S product needs full auditing after work completed in #9679.  

## Acceptance Criteria

- [x] log in as R&S on all environments 
- [x] R&S specific-content types are reviews
- [x] Services are reviewed
- [x] Similar content areas/defects documented across products

**Comment by laflannery** [comment]
Issues documented in google sheet and added to related GitHub tickets
