### ISSUE TITLE
Readout for Facility COVID status

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#9826]
## ACs

 - [x] High-level topline readout early in Sprint 64
   - [x] JHL, Jeff G, Dave C, members for our team

[COVID Facility Status - Topline.pdf](https://github.com/department-of-veterans-affairs/va.gov-cms/files/9294836/COVID.Facility.Status.-.Topline.pdf)

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by ContentBrewmaster** [comment]
@suzanne-gray are we able to close this ticket as no further readout is necessary? I removed the AC related to a full readout.

**Comment by ContentBrewmaster** [comment]
Sent topline readout deck as PDF to VHA Digital Media Aug. 4, 2022.

**Comment by suzanne-gray** [comment]
@ContentBrewmaster I think so. Based on what Dave C. said in the meeting today, this effort can move forward without the full readout.
