### ISSUE TITLE
CMS Non-admins should not be able to edit titles for select content types

### ISSUE THREAD

**Issue by JayDarnell** [department-of-veterans-affairs/va.gov-cms#9827]
## Describe the defect
Summary incoming, in the meantime here is the slack conversation where this was brought up: https://dsva.slack.com/archives/C02730UEZPS/p1657242290495069

- VAMC System Locations List
- Vet Center - Locations List
- Leadership List
- Health Services List
- Stories List
- Events List
- New Releases List

Note: we want to check the entire list above to be sure the intended behaviour is honoured. It is likely some of these are already done and the code for those items could be reused for the others.

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Defect")
- [x] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [ ] CMS workstream (orange) (not needed for bug tickets)
- [ ] CMS-supported product (black)

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by omahane** [comment]
@JayDarnell 
I looked into this one, and it looks like the work was done by Ethan 9 months ago, as seen on line 269ff of `docroot/modules/custom/va_gov_backend/src/EventSubscriber/EntityEventSubscriber.php`

Nevertheless, I checked this out with a handful of users, and found that they were unable to edit the title, hence the ✅.

As daniel.kuester@va.gov, checked out
- VAMC System Locations List ✅
As Mark.Johnson3@va.gov, checked out
- Vet Center - Locations List ✅
As Luke.Johnson6@va.gov, checked out
- Leadership List ✅
As Emily.Smallwood1@va.gov, checked out
- Health Services List  ✅
As Shane.Suzuki@va.gov, checked out
- Stories List ✅
As Rika.Brown@va.gov, checked out
- Events List ✅
As mark.mccann1@va.gov, checked out
- New Releases List ✅

**Comment by JayDarnell** [comment]
Based on your findings above it seems like this is done. Thanks @omahane
