### ISSUE TITLE
Full CMS editorial audit for VAMC Product 

### ISSUE THREAD

**Issue by EWashb** [department-of-veterans-affairs/va.gov-cms#9828]
## Background

The Accessibility Lead for Sitewide CMS is doing audits of specific products across the CMS. The VAMC product needs full auditing after work completed in #9679.  

## Acceptance Criteria

- [x] consult with helpdesk for best editor to log in as
- [x] audit on staging
- [x] VAMC specific-content types are reviewed
- [x] Similar content areas/defects documented across products

**Comment by EWashb** [comment]
Audit completed for the product and issues added to the WIP doc

**Comment by laflannery** [comment]
Link to [audit](https://docs.google.com/spreadsheets/d/1kduP98QBltqtFG8sIB-h-vLXkEoZNPFJ14lEfT6icus/edit#gid=729584628)

Notes:

- Issues in purple are items that I think could possibly be prioritized for next sprint
- There are still a few items in red that I just need to dig further into and document
- I also continue to try and find the issue origin (core, contrib, va) of more issues
