### ISSUE TITLE
Get updated diagrams for CMS/BRD added to README

### ISSUE THREAD

**Issue by ElijahLynn** [department-of-veterans-affairs/va.gov-cms#983]
Get updated diagrams for CMS/BRD added to README.

cc @robbiethegeek-usds 

2 types of diagrams: 1 for ops, 1 for application

## AC:

- [ ] Simple enough diagram to incorporate map of system dependencies

**Comment by oksana-c** [comment]
@ElijahLynn , I have a hunch that a diagram describing CMS/BRD system dependencies may already exist somewhere. What say you? do we need to resurface this issue?

**Comment by ElijahLynn** [comment]
There are various diagrams around, but not in the README yet. We should probably still keep this and prioritize. We are doing a full rebuild of CI and BRD (with ECS) though, so they will be outdated soonish. But still valuable for new engineers I think.

**Comment by ElijahLynn** [comment]
Pausing on this right now as we are moving to EKS + ArgoCD etc.
