### ISSUE TITLE
User support for Income Limits Web App

### ISSUE THREAD

**Issue by cmaeng** [department-of-veterans-affairs/va.gov-cms#9831]
## Description
User support workstream needs to know details of this effort in order to support from a helpdesk and training perspective.

## Acceptance Criteria
- [ ] Launch date has been verified with User Support crew
- [ ] Training has been set up a week prior to launch date

**Comment by stefaniefgray** [comment]
@wesrowe @jilladams Trying to close out and clean up ye olde User Support tickets from our ZenHub board -- should we keep this ticket and the linked ticket #9832 open for now as frameworks for upcoming support and training needs?

Alternatively, could they be replaced or consolidated into a newer ticket?

cc: @TroyA6 -- also we would need to be briefed on all things Income Limits before proceeding, so I'm filing this under "Blocked" for now

**Comment by jilladams** [comment]
It's probably worth keeping open as blocked, until we're closer to building / getting a launch timeframe (at this rate, early/mid-Q2 2023).
