### ISSUE TITLE
Create CMS Accessibility Audit Intake Process

### ISSUE THREAD

**Issue by EWashb** [department-of-veterans-affairs/va.gov-cms#9834]
## Description

As we receive accessibility audits across the Sitewide Crew and Platform teams we need a process to receive requests.

## Acceptance Criteria

We need a GitHub template that:
- [ ] allows audit requesters to detail their needs
- [ ] manages expectations on the sitewide accessibility lead's turnaround time
- [ ] consider how to manage slack asks for audits

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [x] `Sitewide Crew`
- [x] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by laflannery** [comment]
I added a form here: https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/.github/ISSUE_TEMPLATE/accessibility-audit.md @EWashb if you wanted to review and see if you had comments. Also maybe @msbtterswrth if you wanted?

**Comment by EWashb** [comment]
This does look good! We need to make sure to socialize this across teams now. Possibly even post in the vagov accessibility channel
