### ISSUE TITLE
Lovell UI exploration

### ISSUE THREAD

**Issue by davidmpickett** [department-of-veterans-affairs/va.gov-cms#9846]
- [x] Aslan to create wireframes of different UI design options
- [x] Dave and Val to review wireframes for initial feedback 
- [x] Aslan makes updates to wireframes based on feedback
- [x] Present updated wireframes to David S & Roger
- [x] Present to Dave C 
- [x] Possible additional edits before Collaboration cycle

**Comment by davidmpickett** [comment]
@valerierunde @jcklpe I think we should use some time during sprint planning on Monday to refine the acceptance criteria for this. Also would be good to map out if there are specific check in meetings we want to have throughout the sprint and get those on the calendar.

**Comment by jcklpe** [comment]
Previous ticket: #9845

Has relevant research to remember

**Comment by jcklpe** [comment]
Research here: [https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/facilities/medical-centers/product/lovell](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/facilities/medical-centers/product/lovell)

Previous UXpin stab at it: https://preview.uxpin.com/d55fbe11583adc1a1d7b6e2bafde9ef560c7bf36#/pages/148503607/simulate/sitemap?mode=i  
  
Brainstorming alternatives approaches: 

*   [modal](https://preview.uxpin.com/93cf67f26d2b936504ffc415de7cf97fcb8d8e1c#/pages/145465846/simulate/no-panels?mode=i)
*   switching the alert location
*   toggle
*   tab
*   two buttons
*   have a primary (VA) and then pop up a modal for DoD or perhaps give DoD a frame that signals it's different

**Comment by jcklpe** [comment]
Some useful research stuff here: #9850

**Comment by jcklpe** [comment]
Current website (without Tricare stuff) can be found here: https://www.va.gov/lovell-federal-health-care/

**Comment by jcklpe** [comment]
From the IA moqups: https://app.moqups.com/Rnc4BDEKrA/view/page/a38ead751  
  
![](https://user-images.githubusercontent.com/9451726/182718118-ddf63cb0-7fb2-44d0-931d-213c9e404e74.png)  
  
After a lot of futzing around, my understanding is we don't have the latitude for the single system level site. I was hoping we could forgo the split until going to the individual location level but it looks like that decision has already been made.

**Comment by jcklpe** [comment]
Some thoughts on alternative approaches:  
 

*   Modal (seems complicated to implement (requires the browser to remember that the user has dismissed the modal on multiple pages)
*   toggle (weird pattern that we don't see anywhere else on the website. Design System doesn't have any kind of toggle in it either)
*   tabs (doesn't really work because we have a mandate to make these separate pages at the system level and tabs would go against that. Also I personally hate tabs as a solution because they're too often just a way to shove stuff in a junk drawer)
*   Two buttons (I think this is pretty much only applicable as a modal)
*   Having a primary and then popping up the thing later doesn't work with the two system mandate
*   Switching the alert location: not a big change but maybe? That's what I've made so far.

**Comment by jcklpe** [comment]
This is what I'm thinking we should test:  
  
![](https://user-images.githubusercontent.com/9451726/182952892-48c1c3df-11af-44ad-863d-726a49b48064.png)

**Comment by jcklpe** [comment]
alright, I've made three different approaches: toggle, modal, and the alternative location alert.

**Comment by jcklpe** [comment]
quick button sketch to illustrate @dsinla suggestion 

<img width="858" alt="image" src="https://user-images.githubusercontent.com/9451726/183518386-00c18da4-d0a4-4876-b7e1-a78546afd6cf.png">

**Comment by jcklpe** [comment]
also worth noting that [the VA design system does have example patterns that have buttons in the alert](https://design.va.gov/components/alert). USWDS also does not though. 

on the action versus notification distinction, I think it's sort of arguable either way.

**Comment by jcklpe** [comment]
@dsinla , @valerierunde : I'm not clear on if there are specific action items expected of me following our design review call?

**Comment by dsinla** [comment]
@jcklpe Thanks for mocking up the button in the alert. In my opinion (and it is just that, an opinion) I think it addresses the issue of people who are likely to overlook the all-text-based alerts. The button will catch more eyes as a potential CTA. And it doesn't have the negative of the redundant text block.

For next steps, I am going to talk to Shira G about re-inserting into the Collab Cycle, and I thought we agreed we'd get our recommendations in front of Dave C before then. Would it make sense to give Dave C 3 mockups like

**Highest recommendation:** Alert with CTA button

- Addresses potential to be overlooked
- Button more clearly communicates an action can be taken
_ie Why is this our top reco?_

**Recommendation alternative 1 ** Toggle

- More development overhead
- Somewhat ambiguous expression of action

**Recommendation alternative 1 ** Modal

- Forces user acknowledgement
- Largest dev effort, how to track dismissal 

I'm not saying those are the 3 suggestions (I think Val's text block with CTA button can be floated here was well), but I;m saying we should present it in a form like this, like a 3-pager, with simple graphics. We can post in slack, or I can bring to my sync meeting on Wed.

ALSO - you're going to make sure TRICARE is capitalized ;) 

And @valerierunde @davidmpickett do we want to have any mention of how we might measure the success of the new design at this point- what clicks we're going to track? We're going to need something along those lines for the Collab Cycle. Val you had an interesting aside about how to track google metrics and what a visitor does when she reaches our site. Can we quantify that and have a convo with analytics folks this week? (Without taking on Another Big Project).

**Comment by jcklpe** [comment]
Okay as I see it we have 3 layers of options:

# Solution level 1

## Solution 1: Toggle

![](https://user-images.githubusercontent.com/9451726/183698038-4c77e9fc-3114-4328-8f3f-fc870b3b1f0c.png)

This option honestly doesn't really make sense. Toggles are supposed for be boolean values: 0 and 1, true or false, and this really more 2 coequal enumerated categories: TRICARE and VA. Even if we try to think about this as VA as the default I would not recommend this path. 

## Solution 2: Move the alert, change semantic to "warning", and make sitewide banner style

![](https://user-images.githubusercontent.com/9451726/183699194-849cd457-14d6-4bcd-b040-87ebabd55d9d.png)  
This isn't a very big change but it's the most reasonable I can see.   
  
The banner that was tested is smaller, placed under the h1, and uses the less noticeable "informational alert" semantic:  
  
![](https://user-images.githubusercontent.com/9451726/183698971-6cf3fa41-a330-4c17-b849-fb72edca8a62.png)

I believe the yellow warning alert, it's full page width, and it being above the h1 makes it significantly easier to find. This is the solution I would recommend. 

# Solution level 2

There are two ways to approach solution 2

## Solution 2.A: Use link text to switch to the new page

![](https://user-images.githubusercontent.com/9451726/183699194-849cd457-14d6-4bcd-b040-87ebabd55d9d.png)

Pros:

*   arguably this is adhering better to [web semantics (links for navigation, buttons for actions)](https://medium.com/@h_locke/links-vs-buttons-e8b523660fb3#:~:text=According%20to%20good%20old%20best,the%20state%20of%20the%20website).)

Cons:

*   Basically like the old solution so may not be as visible to users. 

## Solution 2.B: Use button to switch to new page

![](https://user-images.githubusercontent.com/9451726/183702690-ac248d13-9ec6-4b04-b76b-cb56a773bc5f.png)

Pros:

*   Arguably easier to see
*   Also "switching to a different mode" could be perceived as adhering to web semantics. It really depends on how you look at things and it's not a huuuuuge issue. There's plenty of controversy in UI circles about how to draw the line on these things. 

Cons:

*   maybe could be argued as being less web semantic but not really that big a con IMO

Notes: It's worth noting that the USWDS does not allow for buttons in alerts. The VA design system [DOES](https://design.va.gov/components/alert) though, so we have existing patterns we can point to for this. 

# Solution level 3

Changing the location and visual semantics of the Alert may still not work. There could be deeper problems that we need to explore on how veterans/servicemen understand their coverage. Without further context and understanding on that, I think we can propose an additional "if this doesn't work, we don't know what will" solution 

## Solution 2.x.alpha: Modal

![](https://user-images.githubusercontent.com/9451726/183703559-bb22a5eb-5a91-41d4-83ba-5be8c7c517d9.png)

This is basically a last resort solution. If this doesn't work, I don't know what will. This FORCES the user to pay attention to the issue. It is also not a solution on it's own, this will only work in addition to whatever solution we decide on the other 2 solution layers. 

Pros:

*   Can't be missed

Cons:

*   Maybe requires some extra engineering. 
*   Could be kind of annoying. Will def need to make sure this only pops up the first time the user enters the page

## Solution 2.x.beta: no modal

Basically just what we have right now.

**Comment by jcklpe** [comment]
nearly forgot to attach this: https://app.mural.co/t/vagov6717/m/vagov6717/1649871147127/79a626dd43195096acc64653f15b4a7fcc039458?sender=u4a3aab4befc428f9f54f8092

**Comment by jcklpe** [comment]
Here's a mural presentation of the above recs: https://app.mural.co/invitation/mural/vagov6717/1660068163050?sender=u4a3aab4befc428f9f54f8092&key=5614196f-c548-4b75-934a-70caa6cc37ee

**Comment by davidmpickett** [comment]
@dsinla @RWEagans - How do y'all want to take this to Dave C for review? Does he need to see it before demo? Let me know how I can help while Aslan is out

**Comment by davidmpickett** [comment]
Per @dsinla Dave C saw this and gave it a thumbs up. Said we should just bring our top recommendation to Collab cycle.

**Comment by jcklpe** [comment]
@davidmpickett What's our top rec of the 3 levels of solutions?
