### ISSUE TITLE
Flag / Notifications for Facility Services pulled from lighthouse

### ISSUE THREAD

**Issue by JayDarnell** [department-of-veterans-affairs/va.gov-cms#9848]
## User Story or Problem Statement

Converted to epic. Possible sub-issues within this epic:

- creating a flag (label TBD)
- flagging content by sniffing the data during migration,
- writing a notification email for editors,
- triggering the notification from the flag,
- change management (letting editors know about this new process),
- possibly: creating a listing, like on the Section dashboard, showing all facility health services that are out of sync with other sources of truth. We’ve been discussing some similar approaches for other “content issues” like broken links, a11y errors, etc.

Slack conversation: https://dsva.slack.com/archives/C0FQSS30V/p1658242349607959
Services comparison sheet: https://docs.google.com/spreadsheets/d/19Gihg32Fifu3FW4y0nMIeVUUbjcXYIzsbV7-B34JzsE/edit#gid=1839316337

Once we have fully implemented push/pull integration between the Drupal CMS and lighthouse for facility services we need to have a mechanism in place for marking facility services added to the CMS from lighthouse. In other words, if the nightly migration runs and a new facility service is added to the CMS from lighthouse we want to mark it so we can follow up as the CMS should be the source of truth for facility services at the time of this implementation.

## Acceptance Criteria
- [ ] Facility services (for a given facility) added by a nightly migration from lighthouse are flagged (Label: Added Service)
- [ ] Email section owners for the facility so they can follow up 

Rough Email message: 

Hello `<section owner>`, 

ATC and/or DST says your facility: `<facility name>` has this service: `<newly added service name>`. If you do in fact have that service, please add/publish it to your facility and provide details so that all of our information is accurate and in sync However, If you don't have that service, please let ATC or DST as appropriate, otherwise we will have incorrect service listings reported on things like the Facility Locator.

## Possible approach with issues

- creating a flag (label TBD)
- flagging content by sniffing the data during migration,
- writing a notification email for editors,
- triggering the notification from the flag,
- change management (letting editors know about this new process),
- possibly: creating a listing, like on the Section dashboard, showing all facility health services that are out of sync with other sources of truth. We’ve been discussing some similar approaches for other “content issues” like broken links, a11y errors, etc.

**Comment by davidmpickett** [comment]
@omahane @swirtSJW Is this still relevant based on your recent v1 work? Is this finally actionable?

**Comment by Agile6MSkinner** [comment]
No tickets were ever added and it's old. Closing.
