### ISSUE TITLE
PM: Establish lines of communications with Lovell stakeholders

### ISSUE THREAD

**Issue by davidmpickett** [department-of-veterans-affairs/va.gov-cms#9849]
As a designer, I need to connect with stakeholders at Lovell (web editors), so I can gather content details and build a path for change management when it's time to roll out the new site.

- [ ] Dave P to liaison with VHA Digital Media to get contact information for Lovell SMEs
- [ ] VHA Digital Media to appoint a Lovell point-of-contact in August

**Comment by davidmpickett** [comment]
@ContentBrewmaster tagging you for visibility

**Comment by davidmpickett** [comment]
Communicated this need during biweekly sync with VA Digital Media today. Jeff Grandon agreed to take it to Jenny HL for possible assignment to Justin (didn't catch last name).

**Comment by ContentBrewmaster** [comment]
@davidmpickett It's Justin Warren.

**Comment by davidmpickett** [comment]
@ContentBrewmaster Any update on this in yesterday's VHA DM meeting?

**Comment by davidmpickett** [comment]
@davidconlon to discuss with Jenny HL tomorrow

**Comment by dsinla** [comment]
From Dave C this morning:
Contact for Lovell via VHA Digital Media: [Justin.Warren@va.gov](mailto:Justin.Warren@va.gov)

**Comment by davidmpickett** [comment]
Messaged Justin to set up a first call

**Comment by davidmpickett** [comment]
Meeting will take place tomorrow.
