### ISSUE TITLE
Determine and document any ATO related to static assets being publicly available on S3. 

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#9858]
## Description
> Any ATO implications have been documented on this issue

We should confirm our assumptions re ATO and static assets being in a dedicated S3 bucket. Currently static assets are made available on a dedicated public S3 bucket, which is not behind the TIC. 

## Acceptance Criteria
- [ ] Documentation of our ATO re: static assets is discovered and documented

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [x] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by jkalexander7** [comment]
Closing - ticket is not needed because assets being put into public S3 bucket are already being deployed into public content S3 bucket.
