### ISSUE TITLE
Spike: "On this page" header text should translate to Tagalog & Spanish on translated COVID pages

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#9868]
## Describe the defect
The "On this page" header appears on COVID 19 pages that have been translated to Spanish / Taglog, but is regressed and appears in English. e.g.

https://www.va.gov/health-care/covid-19-vaccine-esp/
![Screen Shot 2022-07-20 at 12.55.40 PM.png](https://images.zenhubusercontent.com/624dd6bb7d958ceb206d043b/29fdb257-87c5-49bb-ba0e-71f94566b1f0)

This work was done previously and regressed: 
- Spanish - https://github.com/department-of-veterans-affairs/va.gov-team/issues/19407
- Tagalog - https://github.com/department-of-veterans-affairs/va.gov-team/issues/20860

### Expected Translations
On this page should be translated.
- [ ] Spanish pages = En esta página
- [ ] Tagalog = Sa pahinang ito

## Acceptance Criteria

- [ ] Document in ticket how to fix

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Defect")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS workstream (orange) (not needed for bug tickets)
- [ ] CMS-supported product (black)

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [X] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by allisonlu** [comment]
still WIP, last updated 8/5/2022

## Issue
- switched to VA Design System web component 


## Solution

### short-term
1. update the setOnthisPageText function (getElementById) on this file: src/applications/static-pages/i18Select/utilities/helpers.js
1. when all components finish loading, hide the current english "on this page", replace with translation is listed in translation.json file
1. create own OnThisPage component with prop to handle translation

### long-term
1. file ticket with Design system team 
1. collab to ensure the va-on-this-page web component can be used for translated pages in the future


## Relevant files

- [On this page component - VA design system](https://design.va.gov/components/on-this-page)
  - [ ] file ticket w team for translation

- there exists a "Spanish tralsnation summary" entity for additional Info content on Benefit pages

https://github.com/department-of-veterans-affairs/content-build/commit/0e25f2c8bda8dc31fcce94300a1a57602da0d649#diff-601e6e0446e9bd5287cbdc5edca501a5ff9d9a9a95fff4a3e00ffb173021fcd2


- logic for translation toggles:
src/applications/static-pages/i18Select/createI18Select.js

- toggle link component: src/applications/static-pages/i18Select/I18Select.js
  - setOnThisPageText function is imported

**Comment by jilladams** [comment]
@allisonlu  Is the implication here that the previous work to translate On this Page to Spanish / Tagalog got regressed because they did the work outside the design system? And we should use / translate the design system component instead?

**Comment by allisonlu** [comment]
@jilladams from what I've dug up last week, we **currently** use the design system On This Page component and that's why it's hard-coded in English. 

I'm going to look deeper into this today and iron out my original notes

**Comment by jilladams** [comment]
Per scrum: 
* Closable with action items
* Allison, if you can help cut the follow up ticket to the Design System, and port your options for implementation into a new ticket, Wes or I can review that ticket and make sure it's tagged up so we can refine it today.

**Comment by allisonlu** [comment]
Closing this spike ticket. I created issue #10177 10177 on our board (needs refining), and filed an issue with the Design System team: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1100
