### ISSUE TITLE
Injected header/footer: Publish to prod: m.va.gov

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#9871]
## Description

Original request to set up new site for injected header/footer: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9870
_Updates in this ticket should be made to the domain(s) listed / code updated in the original ticket._

This ticket adds new domain(s) to allowlists that gate the injected header. When the requsting team confirms their testing is complete, Public Websites will 

- [ ] update [proxy-rewrite-whitelist.json](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/proxy-rewrite/proxy-rewrite-whitelist.json) code to `cookieOnly: false ` to permanently display the header 

## Acceptance Criteria
- [ ] Devops PRs to add www & non-www domain(s) have merged
- [ ] Requesting team has signed off that they're ready to publish
- [ ] On requested domain(s) the global header is injected on page load, with no cookie updates required

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [X] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by jilladams** [comment]
Blocked until m.va.gov team tests & greenlights for prod.

**Comment by wesrowe** [comment]
Brett Lee confirmed today that he doesn't see the image url issue as a blocker for their launch of the injected header.

**Comment by allisonlu** [comment]
PR opened on `vets-website`: https://github.com/department-of-veterans-affairs/vets-website/pull/22005

**Comment by allisonlu** [comment]
PR merged! Will confirm that it's on prod and close ticket after daily deploy

**Comment by allisonlu** [comment]
Injected header is now live on https://m.va.gov/!
