### ISSUE TITLE
Discovery: content strategy for Benefit Details Content Model Hardening

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#9879]
## Description

Assumptions:
- Editors of BD pages are on SW Content team
- Background will be provided by Danielle T on Monday, 7/25

## Acceptance Criteria
- [x] Attend meeting
- [x] Discuss internally next steps
- [x] Write at least one ticket for follow-up work

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by jilladams** [comment]
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9910 is created for Drupal dive. Could use a onceover from Wes & Christia's feedback (in refinement) re: whether product should own any portions of that. 

Also Danielle's Mural is now accessible, but I'm not sure what to make of it? We should prob review this with Christia too. https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1636828859943/fce7f7349e5a7f0221d081bf0f314bf68feb052d?sender=b876d612-b48e-465a-967a-2aa7f31e0440

**Comment by jilladams** [comment]
Extracted from #9910, these pieces feel more like Product work that can live here:


**Templates**
Benefit Detail pages are used to manage 4 types of Benefit eligibility content right now, listed in 2 docs: 

- https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/structured-content/core-benefit-content-page-templates.md 
- https://design.va.gov/patterns/benefit-applications#eligibility-hierarchy

Sitewide Content wants to harden the form to account for those 4 types of pages. We need to articulate: 
- what fields manage the data for each type of page
- can / should a single form continue to manage that data
  - if so: what updates are required to achieve it
  - if not: should these be split into 4 separate content types / templates, and how are those defined

We should factor FE, Backend, data effort & maintenance into that thinking. e.g.
- One content type = more conditional logic in the front end to manage
- Multiple content types = more templates to manage / more Drupal definitions / configs to manage
