### ISSUE TITLE
Set up a standardized local development environment for next-build

### ISSUE THREAD

**Issue by cweagans** [department-of-veterans-affairs/va.gov-cms#9880]
## Description

next-build currently requires installing a lot of software on the host machine. Let's set up an environment like we have for the CMS where people can set up minimal host dependencies and then run an automated setup.

## Acceptance Criteria
- [ ] List of needed tools is identified
- [ ] next-build has a standardized local dev setup with all necessary tools included
- [ ] local next-build dev server should be accessible over https; see #9888 for some detail

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [x] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by timcosgrove** [comment]
They are not strictly interdependent or blocking of each other, but https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9886 (next-build dev server per CMS environment) should be considered in the context of this ticket or vice-versa.

**Comment by TheBoatyMcBoatFace** [comment]
No longer applicable. Handled by
- #11839
