### ISSUE TITLE
[SPIKE] Draft a Testing/Quality Assurance Strategy document for the CMS product

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-cms#9882]
## Description
I drafted a Testing Strategy document for the Next Build project, and that went over reasonably well.  I think it would be worth doing this for the CMS project as well.  It might go better, since I _sort of_ know what I'm doing re: Drupal.

A lot has changed since this project was started, and it's worth investigating changes in recent versions of Drupal, new tools in the PHP space, etc, to see what has emerged.  It's possible, for instance, that writing tests for Drupal is no longer an eye-gouging nightmare.

As always, the guiding principle is to try to identify best practices and adopt them wherever possible, identify and ameliorate the pain points, and find ways to improve developer buy-in.

## Acceptance Criteria

- [x] strategy is drafted and added to CMS confluence (see [here](https://va-gov.atlassian.net/wiki/spaces/CMSQA/pages/1814724630/Quality+Assurance+and+Testing+Strategy)).

**Comment by EWashb** [comment]
@ndouglas I think this will be ready to close once you add the link to the confluence!
