### ISSUE TITLE
Fix Failing Jenkins Job "Pipeline Sanitize database on prod.cms.va.gov"

### ISSUE THREAD

**Issue by olivereri** [department-of-veterans-affairs/va.gov-cms#9883]
## Description
Changes to site alert module are affecting the Bash script that sanitizes the database. The script is trying to remove deploy-alerts from the site_alerts table, but it no longer exists. Must fix the sanitize script.
https://github.com/department-of-veterans-affairs/va.gov-cms/pull/9863

Revisit if this is still necessary:
https://github.com/department-of-veterans-affairs/devops/pull/8610

## Acceptance Criteria
- [ ] Testable_Outcome_X
- [ ] Testable_Outcome_Y
- [ ] Testable_Outcome_Z
- [ ] Requires design review

## Implementation details

Quick solution.

 Remove all 'deploy-alert' site alerts
mysql \
    "${MYSQL_CONNECTION_ARGS[@]}" \
    --execute "DELETE from sitewide_alert_field_data where name = 'deploy-alert';" \
    "${MYSQL_SANITIZE_DB_NAME}"

mysql \
    "${MYSQL_CONNECTION_ARGS[@]}" \
    --execute "DELETE from sitewide_alert_field_ where name = 'deploy-alert';" \
    "${MYSQL_SANITIZE_DB_NAME}"

**Comment by olivereri** [comment]
```
SELECT id FROM sitewide_alert_field_data WHERE name = 'deploy-alert';
# capture the above values
DELETE FROM sitewide_alert WHERE id IN <captured values>
DELETE FROM sitewide_alert_revision WHERE id IN <captured values> 
DELETE FROM sitewide_alert__field_alert_title WHERE entity_id IN <captured values> 
DELETE FROM sitewide_alert_revision__field_alert_title WHERE entity_id IN <captured values> 
DELETE FROM sitewide_alert_field_data WHERE id IN <captured values> 
DELETE FROM sitewide_alert_field_revision WHERE id IN <captured values> 
```

**Comment by ndouglas** [comment]
This done?
