### ISSUE TITLE
Next-build preview server running for one BRD environment

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#9886]
## Requirements

Each BRD CMS instance will need a Next.js preview server associated with it, so that users of the CMS can preview their content appropriately.

```[tasklist]
### Acceptance criteria
- [x] For staging-test.cms a preview server is available at a domain
- [x] The domain routes to a running Next.js server process
- [ ] The domain can be reached via https, using the same cert setup that is used by CMS or else one that does not require special setup
- [ ] The container or server is able to be directly or indirectly orchestrated from Github actions such that new code can be checked out and the Next.js server restarted - this does not include the orchestration workflow itself
- [ ] The restart process is as close to invisible to the CMS user as possible - instant or as close as possible. - this does not included the restart process itself
- [ ] Updating the Next Build code running on the preview server should not require manual git operations
- [ ] Any steps or lessons learned from this work are documented
```

## Background & implementation details

This does **not** mean the preview servers run ON BRD. They're adjacent/associated. 
Domain:
* preview-staging-test.cms.va.gov

The domains are internal to the VA network, as CMS is also.

As part of the server/container, a `yarn dev` server will be stood up. This creates a persistent web server process that can be reached via the web. This is what the above domains should resolve to.

The domains should be able to be reached via https, and that should not require additional setup on the part of the user. 

On a daily basis, or else following any Next-Build code deploy, the server will need to be able to be updated and restarted automatically. **Note that this ticket does not ask for this update mechanism to be implemented, only that the infrastructure be capable of supporting the update.**

The sequence is roughly:

1. A new Next-Build tag is designated for production use ("production deploy") via a Github Action workflow
2. A downstream job is triggered by the above workflow which is responsible for updating the preview server
3. The preview server is stopped.
4. The production tag from 1. is checked out to the preview server.
5. The preview server process is started with the new code.

The above process should not result in several minutes of downtime for the preview server. Note that the container does not need to be restarted necessarily: it is enough to stop the process, do the checkout, and restart the process.

If EKS can provide a 'seamless' container swap deploy, that is preferred. (i.e. Containers 1-4 are currently running and the LB resolves traffic to them; Containers 5-8 are spun up with the new code; when they're ready, traffic is diverted to containers 5-8 and 1-4 are retired. 

```[tasklist]
### Implementation tasks
- [ ] Use this if it helps you or feel free to delete.
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16857
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16861
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16863
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16866
```

**Comment by timcosgrove** [comment]
It is not strictly blocking, but #9880 should be considered together with this ticket.

**Comment by timcosgrove** [comment]
We will return to this once #16187 is complete.

**Comment by timcosgrove** [comment]
Just noting that this may take multiple sprints.

**Comment by olivereri** [comment]
## Core Documents for On-boarding Applications in Platform EKS:

- https://vfs.atlassian.net/wiki/spaces/OT/pages/1474594142/Onboard+a+new+application+to+EKS
- https://vfs.atlassian.net/wiki/spaces/OT/pages/2350645620/Build+a+Helm+chart+for+EKS
- https://vfs.atlassian.net/wiki/spaces/OT/pages/2390655043/Set+up+deployment+automation+for+ArgoCD+to+EKS

## Previous Issues
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/6357
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/6377
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/30177
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/30196

## Supporting Confluence Docs:
- https://vfs.atlassian.net/wiki/spaces/TT4/pages/2416935044/Research+Preview+Environments+in+EKS
- https://vfs.atlassian.net/wiki/spaces/CUI/pages/2104688835/Post-Mortem+-+EKS+Onboarding

**Comment by olivereri** [comment]
I want to explicitly state that we should definitely strive to keep Next-Build's [runtime immutable](https://12factor.net/build-release-run). The issue body in the implementation section describes updating the running code on the running container via a git checkout. That really should be a last resort failing all other methods to package the current code into a container image and only ever updating Next-Build's runtime container via the build process.

Before Next-build reaches Production we should trial https://argoproj.github.io/argo-rollouts/features/bluegreen/ deployments to ensure the code update is swift, resulting in minimal downtime.
