### ISSUE TITLE
next-build dev server runs as secure server

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#9888]
## Description
Next.js's provided web server for development & preview is over a basic insecure http connection. However, for preview to work correctly, both the server initiating the request (Drupal) and the request domain (next-build) need to be running over valid https connections.

## Implementation details
There are multiple routes for generate valid certs. next-build will need to be provisioned with a custom server in order to make use of the cert and to serve over https. See https://nextjs.org/docs/advanced-features/custom-server for documentation and examples.

## Acceptance Criteria
- [ ] Any running next-build dev server can be accessed over https.
- [ ] The certs in use are valid and do not trigger warnings or failure either in the browser or in node processes that query the server.

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [x] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by timcosgrove** [comment]
Local will be done as part of #9880; we will follow up with this for other environments further on.

**Comment by jkalexander7** [comment]
Closing - scope is covered in https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9880

**Comment by jkalexander7** [comment]
Closing - scope is covered in https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9880
