### ISSUE TITLE
Next-drupal configuration per environment

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#9889]
## Description
Both config and config entities are needed for next-drupal to perform preview functionality correctly. These need to be created in code or in the CMS UI, as is appropriate for each type of config. Additionally, some of the values will be secrets provided by SSM, so the config needs to be set up to read those values from the appropriate sources.

## Acceptance Criteria
- [ ] The 3 config items are committed to the va.gov-cms repo as code.
- [ ] Once the config is committed to the va.gov-cms repo, the two entities (user and consumer) are created, and continue to function after sync to lower environments.
- [ ] Config overrides are established for each of the items listed in implementation details
- [ ] Overrides which need to be secret are provided to config override via a standard secrets mechanism, and are appropriate for each environment

## Implementation details
There are 5 pieces of config that are necessary for Drupal to see Next-drupal and for Next-Drupal to be able to authenticate to Drupal.

These can be configured in code:
* A user role with the required permissions:
  * Bypass content access control
  * Issue subrequests
  * View user information
* A Next.js 'site'
* Simple Oauth

These are entities that must be configured in the UI and sync'd down from prod to other environments:
* Nextjs user (with the user role defined above)
* A consumer (to allow the above user protected access to the Drupal instance in question)

A number of properties of these entities need to be configurable from code, i.e. they are able to be overridden per environment and potentially provided by a secrets mechanism. Some of them may not strictly be secrets that need to be secure, but they should be shared between next-build and Drupal, and so it is probably best to provide them via the secrets -> environment variable mechanism. 
```
$config['next.next_site.nextjs']['uuid'] = <value>; // This may need provided to next-drupal as DRUPAL_SITE_ID
$config['next.next_site.nextjs']['base_url'] = <value>; // This should match wherever the preview server will be located
$config['next.next_site.nextjs']['preview_url'] = <value>; // base_url + /api/preview
$config['next.next_site.nextjs']['preview_secret'] = <value>; DRUPAL_PREVIEW_SECRET in next-drupal
$config['simple_oauth.settings']['public_key'] = <location>; // This is a file location; see below
$config['simple_oauth.settings']['private_key'] = <location>; // This is a file location; see below
$config['next.settings']['site_previewer'] = <previewer id>; // defaults to iframe; should be our custom SitePreviewer plugin

// These are config entities on the Drupal site, part of the consumer setup. The values of these need to somehow be provided to next-drupal as well.
DRUPAL_CLIENT_ID= <uuid of the consumer>
DRUPAL_CLIENT_SECRET= <secret specified in the consumer>
```

Ideally these would both be overridden in code so that they can provided by a secrets mechanism rather than set in the Drupal database. 

Any config overrides should be appropriate to the environment they're situated in.

### Notes on Oauth
The public and private key are currently required to be files. They cannot be provided as environment variables.

There is some discussion of this in issue queues, but no solution at this time:
https://www.drupal.org/project/simple_oauth/issues/3133698
https://github.com/thephpleague/oauth2-server/issues/1007

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by ElijahLynn** [comment]
Notes from refinement: Oauth needs to be in file(s), Tugboat needs them too.

**Comment by timcosgrove** [comment]
This has been broken out into several other tickets. Closing.
