### ISSUE TITLE
Facility name change: Former Palm Harbor VA Clinic is now North Pinellas VA Clinic

### ISSUE THREAD

**Issue by stefaniefgray** [department-of-veterans-affairs/va.gov-cms#9890]
## Intake
- [x] Submitter: Medina Ayalalo (Medina.ayalalo@va.gov)
- [x] If the submitter is an editor, send them the link to the CMS Knowledge Base (KB) article on facility basic data for their product (VAMC or Vet Center). Let them know that facility changes can take between 75 days and 4 months after submitting a request, according to VAST administrators. **Already changed in VAST**
- [x] If the change is a facility closure, send the editor a link to the operating status KB article and have them change the status to Facility notice and provide a description of the facility closure so that Veterans are aware of the future closure.
- [x] Other stakeholders to include on updates, if any: <insert name>

## Background info:
**Current name:** “North Pinellas VA Clinic”
**Former/outdated name:** “Palm Harbor VA Clinic” 

**VAMC:** VA Bay Pines
**VISN:** VISN 8

Main facility page: https://prod.cms.va.gov/bay-pines-health-care/locations/palm-harbor-va-clinic
Menu editing page for VA Bay Pines: https://prod.cms.va.gov/admin/structure/menu/manage/va-bay-pines-health-care

## Acceptance criteria

- [x] The H1 title change comes from Lighthouse to Drupal.
- [x] Coordinate with Facilities team to have FE redirects set up.
- [x] CMS engineer locates the newly renamed VAMC Facility (https://prod.cms.va.gov/admin/content/bulk) Search by new name
- [x] CMS engineer updates URL alias for this facility
- [x] CMS engineer resaves this facility
- [x] CMS engineer makes bulk alias changes to facility service nodes. (https://prod.cms.va.gov/admin/content/bulk?type=health_care_local_health_service)
- [x] CMS engineer bulk saves fixed titles to facility service nodes. (https://prod.cms.va.gov/admin/content/bulk?type=health_care_local_health_service)
- [x] CMS engineer updates menu title for facility
- [x] CMS engineer updates Alt text for facility image, if relevant.
- [x] CMS engineer updates Meta description (TBD: some backwards compatibility for SEM, by including something like ", formerly known as [previous name]".
- [x] CMS engineer edit facility node and remove flag `Changed name` then save node.
- [x] HD notifies editor and any other stakeholders.
</details>

## CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [x] `⭐️ User support`

**Comment by JayDarnell** [comment]
@stefaniefgray redirect request created here: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9900

**Comment by JayDarnell** [comment]
Redirect request has been merged. Once the change has gone live I'll finish addressing this issue.

**Comment by stefaniefgray** [comment]
Resolved: https://va-gov.atlassian.net/browse/VAHELP-4470
