### ISSUE TITLE
Next-drupal content type entities

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#9891]
## Description
Next-drupal provides an entity type which specifies that a given entity type should use a method for SiteResolver (typically 'Site Selector'), and a Next.js Site that should be the target of the Site resolver. This is primarily used to manage preview. 

We should set up these entities and have them ready. However, they should not be activated on any environment which is not being built by next-build. 

## Acceptance Criteria
- [x] Next-drupal config entities exist for any Drupal content types which can be output by next-build
- [x] These config entities are managed with config split so that they are only active on demand on local environments.

## Implementation notes
It is possible this may be able to be left as a go-live task for next-drupal. However, these entities will need to be temporarily created in order to test that the SitePreviewer plugin is working correctly.

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [x] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by tjheffner** [comment]
I did not put these in config split because they are effectively no-op for all environments if the feature flag is disabled.

**Comment by timcosgrove** [comment]
This is approved but will merge after the holiday. Moving to done.
