### ISSUE TITLE
FE: display form revision & issue dates as Month YYYY

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#9899]
## Description
re: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/7392

The data from FormsDB only includes month and year for the revision_date. Drupal doesn't allow dates without a day so populates a "day" as today's date.

We need to match the display to the valid data we have and follow guidance from https://design.va.gov/content-style-guide/dates-and-numbers

The data supplied to the frontend is in the format YYYY-MM-DD. However, both revision and updated dates on Forms content should display as Month YYYY, e.g. "March 2021"

## Screenshots for context

Forms search results, e.g. https://www.va.gov/find-forms/?q=10-10

![Screen Shot 2022-07-25 at 12.05.00 PM.png](https://images.zenhubusercontent.com/624dd6bb7d958ceb206d043b/473992e9-5935-4054-80bb-f7ec8d35e7cc)

Form detail page, e.g. https://www.va.gov/find-forms/about-form-10-10065/

![Screen Shot 2022-07-25 at 12.05.08 PM.png](https://images.zenhubusercontent.com/624dd6bb7d958ceb206d043b/3d86e23e-1c7b-4bda-b457-9678bc60a85a)

## Acceptance Criteria
- [ ] On Forms search results, dates are listed as Month YYYY
- [ ] On Form detail page, dates are listed as Month YYYY
- [ ] Both revision date and issue date are handled to display as Month YYYY (because either date may show in these locations, per https://github.com/department-of-veterans-affairs/content-build/blob/main/src/site/layouts/va_form.drupal.liquid#L61)

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [X] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [X] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by dsasser** [comment]
PRs:
https://github.com/department-of-veterans-affairs/vets-website/pull/21784
https://github.com/department-of-veterans-affairs/content-build/pull/1234
