### ISSUE TITLE
Reusable Q&A on R&S: GraphQL query

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#9901]
## Description
For #9737 / #9755, we need a graphql query to expose the Q&A fields that are now present on Resources & Support, for front-end implementation. This work was previously scoped into #9737 as a backend task, but: actually happens in a separate repo from Drupal changes, and rides the BE / FE line, so: broken into separate ticket.

## Acceptance Criteria
- [ ] FE eng has the data required from a GraphQL perspective to be able to fully execute #9755 

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [X] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [X] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by jilladams** [comment]
Per refinement: @chri5tia to add the query to this ticket, @jtmst to pull into content-build code along with FE changes.

**Comment by chri5tia** [comment]
GraphQL query to expose content model changes made in #9737 :

```
query GetNodeSupportResourcesDetailPage($onlyPublishedContent: Boolean!) {
    nodeQuery(limit: 100, filter: {
      conditions: [
        { field: "status", value: ["1"], enabled: $onlyPublishedContent },
        { field: "type", value: ["support_resources_detail_page"] }
      ]
    }) {
      entities {
				... on NodeSupportResourcesDetailPage {
					fieldContentBlock {
					  targetId
					  targetRevisionId
            entity {
              entityId
              ... on ParagraphQAGroup {
                fieldSectionHeader
                fieldRichWysiwyg {
                  value
                  format
                  processed
                }
                queryFieldQAs {
                	entities {
                    entityId
                    entityLabel
                    moderationState
                    ... on NodeQA {
                      fieldAnswer {
                        targetId
                        targetRevisionId
                        ... on FieldNodeQAFieldAnswer {
                          entity {
                            entityId
                            entityLabel
                            
                          }
                        }
                      }
                    }
                  } 
                }
              }
            }
	 }
        }
      }
    }
  }
```

**Comment by jtmst** [comment]
The work for this is done and in the process of being tested. The query has been verified as working in graphQL explorer, but needs verified with CMS data.  Provided there are no issues with should be ready for Monday's release

**Comment by chri5tia** [comment]
This ticket doesn't represent any actual code changes, and this work is done, [per Jill's comment](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9901#issuecomment-1197134976). Closing.
