### ISSUE TITLE
[CMS COLLAB CYCLE INTAKE] Public Websites, Benefit Hub content model hardening

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#9912]
### What type of request are you making?

- [X] Update to an existing CMS feature (including product iterations, updating DS components or page layouts and nav changes)
- [ ] New CMS feature (New content types, DS components, workflows or products)
- [ ] Content audit (either one time audits or resuable tools)
- [ ] Change Management review (for any visible changes to the CMS, workflow or content model)
- [ ] Other

### Please choose the team that is requesting the Collab Cycle kickoff.

Public Websites

### When did/will you start working on this product/feature?

Q3 2022

### When will your feature need to launch?

TBD, Q4? Maybe earlier, since our team likely has capacity in Q3

### Are you doing research with VA.gov users or editors?

No

### Will your work involve changes to...?

CMS content model

### Please add a link to your product outline issue.

https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9628

### Additional Information

The product outline issue provided is the epic driving the effort. We haven't created an outline for this project, and are open to doing it, but would love to discuss which pieces of the outline are most relevant for CMS folks.

More information in the Sitewide Content ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/44807. This project will primarily modify the content model for Benefit hubs, maybe (tbd) add new content types or entity references.  Affected users will be Sitewide Content editors (not VAMC editors). We'd like to consult to make sure we are operating with all the known CMS factors, and get input on things to consider while deciding whether or not to add new content types, etc.

This is our first round on the CMS collab cycle, so let us know who should schedule the kickoff. 

### Notify the Sitewide CMS team of this ticket in the cms-support Slack channel.

- [X] I acknowledge that I must notify `#cms-support` after submitting this issue.

**Comment by EWashb** [comment]
@jilladams I would like to set up a kickoff meeting. For your priorities, are you looking into this for next sprint? I would be glad to get the conversation started in our sprint 64.

**Comment by jilladams** [comment]
Yes please! Attendees should be me, Wes, Christia, and then Florence
optional.

**Comment by EWashb** [comment]
Collab cycle kickoff set for 8/4/22

**Comment by EWashb** [comment]
We may need to reschedule this. Waiting for @wesrowe to confirm the need. We absolutely can look at other times if necessary.

**Comment by EWashb** [comment]
Collab cycle kickoff held 8/9. It was determined that content modeling help may be needed. @cjterdi and @swirtSJW will attend meeting with PW to hear more about the needs and provide resources as needed.

**Comment by EWashb** [comment]
@dawnpruitt we will need to account for this as unplanned work in our sprint

**Comment by jilladams** [comment]
Ok! @wesrowe @fmccaf1 are working on next steps from design perspective here after a workshop meeting with Danielle on Friday. @fmccaf1 are you comfortable owning the next step of pinging me/Wes or direct here on ticket when we have wireframes or design docs ready for next steps / review?  (I wonder if we could collapse that with a review with Danielle? That may be overly ambitious / not right for her time. But if that doesn't smell bad to others, maybe it's an option?)

**Comment by fmccaf1** [comment]
Works for me, @jilladams

**Comment by wesrowe** [comment]
FYI we're meeting Monday 8/22 with Steve W to refine some issues for a rapid, iterative approach to finalizing an MVP design. Paired with some discovery. Mainly this is to say, Steve will be somewhat embedded with PW.

**Comment by EWashb** [comment]
Awaiting next steps from Sitewide Content Team

**Comment by EWashb** [comment]
@jilladams I see that we have something scheduled for 1/26/23. Do you have what you need for this? We would be interested in a product overview, the Drupal editorial experience changes, and the alternatives you have considered for the proposed solution. Also, we need to make sure that Dave C. is invited as optional on the kickoff.

**Comment by wesrowe** [comment]
@EWashb, Dave C is invited (via VA calendar) to the kickoff this Thursday.

**Comment by jilladams** [comment]
Noted. 
* Product outline/ brief: @wesrowe was working on last week and can provide a link when he has it up.
* Drupal editor experience changes: this will amount to a new content type. @davidmpickett is working on Airtabling the content model, which we may not have in hand for this Thurs meeting, but is a goal for end of sprint, that will help with demonstrating the proposed changes. 
* Alternatives: interesting question. I'm not sure how to frame this, but essentially: the Sitewide Content team did analysis of existing Benefit Detail page content last year and boiled those findings down to a proposal for how to harden this content model in order to make the content more usable for COPE (forgot the new term), and in general. Effort is to limit the "junk drawer"-ness of the current content type. 

We can discuss more on the call.

**Comment by EWashb** [comment]
Next steps from the CMS Team perspective:

- Next review will be needed once MVP is determined. CMS Team will await the timeline from Public Websites on when that will be needed.
- CMS Team is here for advice as PW goes through the process.
- Once the design starts, we need a touchpoint and design intent review.
- Drupal engineering may need a separate touchpoint.

**Comment by EWashb** [comment]
Additional tickets may need to be created by the CMS Team on what those steps are once we get confirmation of MVP and the associated timeline

**Comment by EWashb** [comment]
We will not need to be involved with this until PW is ready for a design review so placed this in the blocked pipeline and blocked by the design for this.

**Comment by jilladams** [comment]
Design review happened 3/21. 
Next step: CMS design and CMS build, both hopefully kicking off next week in Sprint 81.

**Comment by jilladams** [comment]
The initial build was reviewed and shipped. The "V2"ish follow on to this project is Codename MAGICHEAD, aka Magical headers, aka "headers without levels":  a structured way for editors to indicate they need a header without specifically setting the level. Related tickets:
* #13143 
* #13572 
* #13756

**Comment by productmike** [comment]
@jilladams @wesrowe I can't recall when the next scheduled meet on this is -- I don't see it on my calendar anymore, though it could be my own doing if it was a conflict, etc. That said, there's two options the CMS team is happy to support: 

(1) Erika's suggestion re: https://dsva.slack.com/archives/C03LFSPGV16/p1686154149418059?thread_ts=1685980804.154689&cid=C03LFSPGV16. A world in which PW runs a small scale iteration, but keeps PRs running through our team.

(2) Putting the proverbial toothpaste back in the collab cycle tube to a small extent to spend a little more time on the definition of the problem space and the outcomes. I think what #13756 was originally getting at, but with more focused assistance from the CMS team. If option #2, happy to work with y'all on the specifics of how to get that on the best rails. Let me know and I'll assist in next steps.

**Comment by wesrowe** [comment]
@productmike, you declined the meeting tomorrrow at 4:30 ET but it is still on the calendar. It's design-focused, with Blake and Laura contributing from CMS team.

**Comment by wesrowe** [comment]
And to respond to the process question, @productmike, I think we're pretty comfortably on path 1 now – i.e., running an experimental design that could be mainstreamed into the CMS design system later if it's successful.

**Comment by jilladams** [comment]
For reference: Magic Headers V1 was deployed to prod in last sprint (S90). This is now live on the VA Benefit taxonomy, for use by the Sitewide Content / a11y / IA team, where we'll collect feedback / make improvements to see if this might be a candidate to expand to further use.

**Comment by EWashb** [comment]
@jilladams do we still need this ticket?

**Comment by wesrowe** [comment]
It seems to me that this cycle resulted in the MVP Benefits Taxonomy, which has launched to CAIA. This can close.
