### ISSUE TITLE
Implement PACT Act translation toggles

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#9918]
## Description

WAITING on translation pages to be created in Drupal by SW Content team.

As a Veteran or family member with limited English proficiency, I want to read PACT Act pages in Spanish or Tagalog so that I can better understand what the law means for me.

How it all works, documented in https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9772

## Acceptance Criteria
- [ ] Toggles appear on PACT pages of all three languages

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by jilladams** [comment]
Per Randi, it would be just one FAQs page to start BUT: the English version is an FAQ page with individual Q&A nodes in Drupal. So we need to probably revisit effort here to confirm how we're gonna achieve that? (@allisonlu @dsasser @wesrowe )

**Comment by wesrowe** [comment]
@jilladams, do you mean that the English version of PACT content is reusing reusable Q&A content?

**Comment by jilladams** [comment]
Sounds like it: https://github.com/department-of-veterans-affairs/va.gov-team/issues/44612#issuecomment-1197265837

So far I see 2 pages re: Pact & sounds like the FAQ will be translated:

1. FAQ page w reusable Q&A:  https://staging.cms.va.gov/resources/the-pact-act-and-your-va-benefits
2. Benefit detail page w static Q&As: https://staging.cms.va.gov/the-pact-act-and-your-va-benefits

**Comment by jilladams** [comment]
Blocked by knowing the destination URLs for the translated pages (Spanish, Tagalog). Could prep PR, but wouldn't publish until pages are published if/when PACT passes.

@RLHecht @mnorthuis we understand that the final URLs for these translated pages may be blocked by the translations themselves. Once you know URLs, could you let us know?  (re: #44612)

**Comment by RLHecht** [comment]
@jilladams for our COVID translated pages, the urls stayed the same as the English version of the page but with an -esp or -tag added on to the end. Because this is an R&S page, the url will match the H1 so it would be /resources/the-pact-act-and-your-va-benefits.for the English page. @DanielleThierryUSDSVA can you confirm?

**Comment by jilladams** [comment]
Tagalog work followed this ticket, without its own sprint ticket: 
https://github.com/department-of-veterans-affairs/vets-website/pull/21971
https://dsva.slack.com/archives/C52CL1PKQ/p1660845368389879
