### ISSUE TITLE
Update the main CMS toolbar to meet accessibility standards

### ISSUE THREAD

**Issue by cjterdi** [department-of-veterans-affairs/va.gov-cms#9920]
## Description
To update the Drupal toolbar to meet accessibility requirements, the following design changes have been approved:

See approved designs: https://www.figma.com/file/s28sd5bJbHtc8oXxlu80Os/Tool-bar?node-id=32%3A301
- Add titles to each environment: Production environment, Staging environment, Dev environment and PR/Demo environment
- For the tugboat environment divide out title for "PR environment" and "Demo environment"
- Change Tugboat tool bar color to color-blue-bright 
- Enable the branch number link for admin accounts. Remove branch number for editors
- Fix font and icon color: Use: Gray base and white

Reference ticket  [9819](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9819) 

## Acceptance Criteria
- [ ] Implement the design changes listed above
- [ ] Design and accessibility review
- [ ] QA

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [x] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by EWashb** [comment]
@cjterdi are the decisions from this [slack thread](https://dsva.slack.com/archives/CT4GZBM8F/p1660317120227299) updated in the file and ready for Edmund?

**Comment by cjterdi** [comment]
Yes. Design is updated for @edmund-dunn to drupalize

**Comment by EWashb** [comment]
@edmund-dunn this is ready for you. Please make sure to point it as well. @dawnpruitt

**Comment by edmund-dunn** [comment]
@cjterdi I need all of the icons in the new gray as SVGs please.

**Comment by edmund-dunn** [comment]
@cjterdi Can you please update the comps with the additional environments, dev and test, and make sure all of the iconography is correct in the compost too. I can provide any or all existing assets if you need them.

**Comment by cjterdi** [comment]
I updated the icons in the comps and added them to the style guide. I am using the Claro-themed icons but don't have a copy of the sections icon. 

Comps
https://www.figma.com/file/s28sd5bJbHtc8oXxlu80Os/Tool-bar?node-id=32%3A301

Style guide
https://www.figma.com/file/ScABI31f3MRFEvQ8WitVPa/CMS-Design-System?node-id=2052%3A92744

**Comment by dawnpruitt** [comment]
@edmund-dunn please move to Closed. Thank you!

**Comment by laflannery** [comment]
@edmund-dunn & @ndouglas I had been checking to see when this actually went live and today realized my confusion was because the training environment was missed:
![image](https://user-images.githubusercontent.com/106678594/187914428-af298010-9d62-46f7-a917-e57a0f0b3b4e.png)

I was told that this was the same as PR/Demo and would be the bright blue color. I'm not sure if that was an incorrect assumption on our part or not.  Can you let me know if
1. Should I create a new ticket to get training updated or would we repeon this issue?
2. Does design need to choose a new color for this environment (if it is in fact separate from PR/Demo)?

**Comment by ndouglas** [comment]
Er... that environment hasn't been rebuilt in three months:

![Screen Shot 2022-09-01 at 8 47 16 AM](https://user-images.githubusercontent.com/1318579/187917358-002b489c-cd44-4a31-99f7-636fdae56799.png)

It's outrageously outdated and definitely does not include Edmund's work.

This should be rebuilt regularly, shouldn't it @stefaniefgray ?  Is this done manually?  I suppose I'm not aware of any automated processes to do this, so it would have to be manual.

**Comment by ndouglas** [comment]
According to Slack it looks like it should be rebuilt every Monday morning, but hasn't been... recently.  I think I understand why now, but I'd like some confirmation from someone who deals with the training environment at least more than I do (which is essentially never).

<img width="688" alt="Screen Shot 2022-09-01 at 8 55 12 AM" src="https://user-images.githubusercontent.com/1318579/187918809-e8133a1e-7fb1-47ef-97d5-dddda4d437d8.png">
<img width="738" alt="Screen Shot 2022-09-01 at 8 55 23 AM" src="https://user-images.githubusercontent.com/1318579/187918825-f28da178-9f85-4145-bb21-42735d0ed4bc.png">
