### ISSUE TITLE
CMS: Lovell sub-sections show in user section block

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#9923]
## Describe the defect
After logging in, a user is taken taken to their user page which displays a user-section-block.  Since the subsections under Lovell were added
![image](https://user-images.githubusercontent.com/5752113/181384199-69ec2d9b-22ce-4ac3-a346-58170ecbf394.png)

The block displays the subsections separately
![image](https://user-images.githubusercontent.com/5752113/181384273-6e643f97-d02b-4d0b-acb3-fdac9b91a760.png)

## To Reproduce
1. Login as admin (admins have access to all sections)
2. See the user section block.  Notice two entries for Lovell.

## AC / Expected behavior
Lovell and its subsections should only show under VHA not as their own sections unless an editor is only assined to those explicitly.

 ## Additional context
This is likley only affecting true admins and content admins who are assigned to VHA at the upper level, not on a VAMC system level.

**Comment by JayDarnell** [comment]
Looks like I found the root of the problem. From docroot/modules/custom/va_gov_user/src/Plugin/Block/UserSections.php line 114:

```
// Sections vocabulary is 4 levels deep. If it grows over 5, this logic
// must be expanded.
```
