### ISSUE TITLE
New Facility: Pike County VA Clinic

### ISSUE THREAD

**Issue by stefaniefgray** [department-of-veterans-affairs/va.gov-cms#9927]
## Background

*What triggered this runbook?*
Help desk ticket filed by VA Atlanta

*Please attach Facility Locator link and https://prod.cms.va.gov/ link to this ticket*
https://prod.cms.va.gov/atlanta-health-care/locations/pike-county-va-clinic
https://www.va.gov/find-locations/facility/vha_508GS

*Please also include link to Jira help desk ticket, if applicable*
https://va-gov.atlassian.net/browse/VAHELP-4500

### VAMC
Please refer to the Knowledge Base article titled "How do I add a facility to my health care system?" for more information: https://prod.cms.va.gov/help/vamc/about-locations-content-for-vamcs/how-do-i-add-a-facility-to-my-health-care-system

#### CMS help desk steps
- [x] 1. Become aware that the new facility is now on the Facility API (typically, via a Flag, but this may come in as a helpdesk ticket).
- [x] 2. If the editor has followed the steps from the above Knowledge Base article and included which section and VAMC the facility belongs to (i.e. VA Pittsburgh), great! **Proceed to step 3.** If not, please check with the editor or VHA digital media regarding what section and VAMC it belongs to.
- [x] 3. Updates the Section (default is "VAMC facilities", but it should be a VAMC system in a VISN) and VAMC system field accordingly.
- [x] 4. Communicate with editor (cc VHA Digital Media) to give them go-ahead to complete the content, with this [KB article](https://prod.cms.va.gov/help/vamc/about-locations-content-for-vamcs/how-do-i-add-a-facility-to-my-health-care-system).
- [ ] 5. When editor has prepared content and let help desk know, reassign this issue to appropriate CMS engineer on Product Support team, for bulk publishing.

    #### Sample notification email:
    Hello! You should now be able to edit the currently un-published draft page for this facility, located at [LINK TO NEW FACILITY DRAFT PAGE ON PROD]

    Important: Please make sure that all relevant steps listed within the “How do I add a facility to my health care system?” Knowledge Base article have been completed: https://prod.cms.va.gov/help/vamc/about-locations-content-for-vamcs/how-do-i-add-a-facility-to-my-health-care-system
    
    Once finished, please save this page as a “Draft”, and do not save it as “Published.”

    Please let us know once your draft is complete, so that we can wrap up the technical process from our end and ensure that the new facility publishes to the live site as intended. Thanks!

#### CMS engineer
- [x] 6. CMS engineer bulk publishes nodes and facility.
- [x] 7. CMS engineer edit facility node and remove `New facility` flag and save node.
- [x] 8. Let help desk know this has been done.

#### CMS Help desk
- [x] 9. HD notifies editor and any other stakeholders.

### Vet Center

CMS help desk steps
- [ ] 1. Become aware that the new facility is now on the Facility API (typically, via a Flag).
- [ ] 2. Check with RCS(?) what district it belongs to.
- [ ] 3. Move the section to the appropriate district.
- [ ] 4. Communicate with editor (do they need to be onboarded) @todo write sample email.
- [ ] 5. When editor has prepared content and let help desk know, reassign this issue to appropriate CMS engineer on Product Support team, for bulk publishing.

CMS engineer
- [ ] 6. CMS engineer bulk publishes nodes and facility.
- [ ] 7. CMS engineer edit facility node and remove `New facility` flag and save node.
- [ ] 9. Let help desk know this has been done.

CMS Help desk
- [ ] 9. HD notifies editor and any other stakeholders.

## CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [x] `⭐️ User support`

**Comment by stefaniefgray** [comment]
@JayDarnell Here's a new clinic that my uncle in Atlanta has already visited! He was telling me about it this weekend.

Looks like the draft homepage is ready and health services have been added -- please let me know if there's anything else we need from the Editor

**Comment by JayDarnell** [comment]
![Screen Shot 2022-08-05 at 11 54 21 AM](https://user-images.githubusercontent.com/21045418/183115002-2cf04ca6-690c-41b4-a8c7-76db94ba8514.png)

New facility and related health services have been published @stefaniefgray

**Comment by dsinla** [comment]
Hello for my education, has @JayDarnell completed the necessary Facilities Dev work? Seems like this is an interesting case, where ownership progresses from XX to YY back to XX. I see Jay added this to the sprint.  @RWEagans and I are talking a bit about how this should be reflected in sprint tracking/reports.  Seems like a small blip in a sprint that has value in being reported.

**Comment by stefaniefgray** [comment]
@dsinla Yep, there are a few different ticket types where this happens -- let's discuss sometime! :)

**Comment by RWEagans** [comment]
@stefaniefgray Is this issue complete? Can you add an estimate to it and close it if it is ready? Thank you!!!!!

**Comment by stefaniefgray** [comment]
@JayDarnell Please let me know if an 8 is appropriate!

@RWEagans Done! 😃
