### ISSUE TITLE
DB Sanitize script should reset the content-release state.

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-cms#9933]
## Description
Followup to #9930 and #9932.  I think the content release state can be "dirty" when the snapshot is taken.  I added code in #9930 to make the Cypress tests more defensive about this, but it might be good to reset this in the sanitize script too.  Judgment call, I suppose.  I don't care whether I do it or Platform CMS does it or if it doesn't get done at all.

## Acceptance Criteria
- [ ] Sanitize script resets content-release state.

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [x] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [x] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by ndouglas** [comment]
Related to #10019.

**Comment by swirtSJW** [comment]
Marking this as a defect as it can jam up our pipeline as well as create a bad experience for partners who are using demo environments to test and QA content.

**Comment by ndouglas** [comment]
This was mooted by #10019, as I recall.
