### ISSUE TITLE
Topline Readout of Facility COVID status

### ISSUE THREAD

**Issue by davidmpickett** [department-of-veterans-affairs/va.gov-cms#9935]
- [ ] Readout happens on Aug 4

**Comment by davidmpickett** [comment]
The readout went well. Jenny Heiland-Luedtke & Lauren Alexanderson will be communicating the recommendations to stakeholders at OHT and let us know by next week if additional steps are needed.

**Comment by suzanne-gray** [comment]
[Readout deck](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/research/2022-5-COVID-status-editor-feedback/Topline_research_readout-COVID-Facility-Status.pdf)
