### ISSUE TITLE
Finalize script to create Linky links.

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-cms#9936]
## Description
Somewhat copied from/replacing #9818.

We [have a script](https://github.com/department-of-veterans-affairs/va.gov-cms/pull/9575#issuecomment-1196913848) that creates a substantial number of Linky links from existing content, but so far it has been written in an iterative fashion purely for benchmarking purposes.

It should be rewritten with more attention paid to safety, reliability, error recovery, etc.  We should spot-check modified nodes to confirm that they have not been incorrectly modified and that the content on the frontend has not been altered unexpectedly.

## Acceptance Criteria
- [ ] The create-linky-links script has been reviewed and found to be in a form suitable for execution on production.

**Comment by EWashb** [comment]
For capacity, we need to focus on the defect in #9585 first before devs can continue with final linky script

**Comment by EWashb** [comment]
This was a stretch ticket for Sprint 64. I have updated it to be looked at in sprint 65

**Comment by edmund-dunn** [comment]
I am removing the `health_care_region_detail_page` from the array of content types. There were only 37 linky entities created out of 5340 links. When these were saved, they sent facility service data to the Facility Locator, which led to a `PHP Fatal error:  Allowed memory size of 4294967296 bytes exhausted (tried to allocate 266240 bytes) in /var/www/html/docroot/core/lib/Drupal/Core/Cache/CacheTagsChecksumTrait.php on line 131
Failed to run drush scr scripts/content/VACMS-9818-write-linky-script-to-create-lots-of-linkies.php: exit status 255` . After discussing with @ndouglas we decided the the cost-benefit ratio was in favor of including it. If it is ABSOLUTELY necessary to include this content type we can finagle the script to just save the 37 linky links.
