### ISSUE TITLE
Adjust readout deck based on feedback from Topline readout

### ISSUE THREAD

**Issue by davidmpickett** [department-of-veterans-affairs/va.gov-cms#9938]
## Acceptance Criteria
- [x] Deck is updated to incorporate feedback from Topline readout

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by suzanne-gray** [comment]
We updated the recommendations in the [readout deck](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/research/2022-5-COVID-status-editor-feedback/Topline_research_readout-COVID-Facility-Status.pdf) per Dave.
