### ISSUE TITLE
Execute Linky link creation runbook on staging and production environments.

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-cms#9939]
## Description
Following the creation of the runbook as specified in #9937, we should schedule an appropriate time for the runbook to be executed on staging and production and execute it.  This should be minimally disruptive, but as it's a long-running script it'll take some strategizing.

## Acceptance Criteria
- [x] Runbook has been executed on BRD.
- [x] Script output has been reported for posterity.
- [x] Followup issues have been opened to deal with any resulting discrepancies, disasters, or hellscapes.

**Comment by EWashb** [comment]
@ndouglas do you know if this has been completed yet?

**Comment by ndouglas** [comment]
Whoops, yes, this was completed.
