### ISSUE TITLE
Work with VHADM to schedule full readout

### ISSUE THREAD

**Issue by davidmpickett** [department-of-veterans-affairs/va.gov-cms#9940]
## Description
Participants to be decided in conjunction with Dave C and others at topline readout
Multiple schedules need to be coordinated 

## Acceptance Criteria
- [ ] Meeting is scheduled

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by davidmpickett** [comment]
In sprint planning today, Dave C indicated that he wants VHA DM to lead the process of scheduling the full readout with other VA partners.

**Comment by davidmpickett** [comment]
Based on the conversation at the readout #9935 it seems like an additional readout will not be necessary. We should have clarity on this by early next week

**Comment by dsinla** [comment]
Confirmed - no larger readout is necessary.
