### ISSUE TITLE
DSN: Document research findings

### ISSUE THREAD

**Issue by davidmpickett** [department-of-veterans-affairs/va.gov-cms#9941]
## Acceptance Criteria
- [x] Findings are written up in markdown file (see [template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/sharing-research/research-findings-template.md))
- [x] All research added to [CMS research database](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/cms/research)
- [x] Ensure the CMS UX research [AirTable](https://airtable.com/appmAWA5qxKq9qxFX/tblgnx8tSgmrgNuWl/viwuWSAbDyCeoCfPd?blocks=hide) is updated
- [x] Present a high level summary of findings in a sprint Demo

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by davidmpickett** [comment]
Might be a good candidate for #10584

**Comment by ContentBrewmaster** [comment]
[Research findings in markdown](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/research/2022-5-COVID-status-editor-feedback/final-topline-readout.md)

**Comment by ContentBrewmaster** [comment]
Suzanne Gray presented the findings in Sprint 64 on August 12, 2022.
