### ISSUE TITLE
Design Front End VBA Regional Office Site 

### ISSUE THREAD

**Issue by jcklpe** [department-of-veterans-affairs/va.gov-cms#9953]
## Description

Background: 
Unlike the Vet Centers, Regional Offices have existing websites (e.g. Baltimore Regional Office). MVP design should largely follow the VAMC and Vet Center template and design components with minimal deviation. As with other areas of VA.gov, these sites are task-based sites that 1/ empower Veterans to know enough information about a specific location and the services offered there to be able to be prepared to make an appointment and 2/ funnel Veterans into online alternatives should they choose Veteran self-service.

This round of design should produce high fidelity wireframes though the information and how its presented is understood to be a first pass ahead of waiting for a finalized content model. Once a finalized content model is determined at the conclusion of Sprint 80, a new card will be made to make a complete prototype for use in usability testing 

Note this analysis of the 2019 wireframes: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10252
Existing [Sketch file](https://www.sketch.com/s/891d33ae-152d-471c-ab5d-9aedf89cf6ff) to start from.

The initial 7 ROs we are focusing on:

https://www.benefits.va.gov/ROSANJUAN
https://www.benefits.va.gov/ROBOSTON
https://www.benefits.va.gov/ROHOUSTON
https://www.benefits.va.gov/ROWASHINGTON
https://www.benefits.va.gov/ROHONOLULU
https://www.benefits.va.gov/ROALBUQUERQUE
https://www.benefits.va.gov/ROANCHORAGE

## Acceptance Criteria
- [x] Build in the accepted design tool for front end work on this team using design system
- [x] Review with @kmariepat-cityfriends and iterate if necessary 
- [x] @kmariepat-cityfriends to scedule a review with Dave Conlon when Jordan reports this work as done
- [x] I expect the design includes `How to Find Us` information: 
- Address
- Parking 
- Hours
- Directions and Map
- Public Transit Options
- Photo of the facility
- Phone Numbers
- Nearby satellite offices

- [x] I expect the design includes `Show available services` information (see video below for example):
- Location of service at that facility
- Hours of service (if different than facility)
- Contact info for that service (if different than facility)
- How a Veteran can make an appointment for that service
- Is there an online version of the service/tool
- What to bring (for this service) 

- [x] I expect the design includes `Top Tasks` 
- Make an appointment (VERA)
- Ask VA (AVA) funnel
- A third placeholder 
- [x] I expect there are banners, which I understand to be announcements

---

**Video example of show available services, pulled from Vet Center:**

https://images.zenhubusercontent.com/154174777/79ed7b1d-bb66-43f4-8959-df09b6aed8c2/va_facilities_team_workflow_and_roadmap___google_slides___28_february_2023.mp4

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [x] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by kmariepat-cityfriends** [comment]
@thejordanwood I can, thank you!

**Comment by kmariepat-cityfriends** [comment]
Notes from Review (changes needed):

- breakout nearby satellite locations 
- Add blobby information within services accordions for service region 
- introduce iconography for service modality (in person vs. virtual) within the service accordion
- add centralized content; VBA national will want to put some information to show up on every regional page. There is an existing pattern for how this is handled for VAMC and Vet Centers

Note: @davidmpickett will share over some example copy for the blobby service region content and the virtual vs. in person copy examples

**Comment by kmariepat-cityfriends** [comment]
@thejordanwood 

Feedback from Design Review w/ PM CM, Dave C. and DEV (changes needed):
- grab in the spotlight content from Boston or Denver
- appointments is a required accordian on all of the benefits; there is national content and local content in each service type
- 3rd top task `check your claim status` (this text may be long for a button)
- consider changing the iconography for virtual appointment, we don't want to imply that a camera is required 
- there might be multiple blocks of hours 
- use the design system pattern to show time zone aligned to the hours displayed

**Comment by kmariepat-cityfriends** [comment]
All AC on this card have been satisfied, for sprint report purposes this ticket will be closed and next round iteration tracked on this card https://app.zenhub.com/workspaces/sitewide-facilities-639f5253e4b702a32376339e/issues/gh/department-of-veterans-affairs/va.gov-cms/13227
