### ISSUE TITLE
EPIC: VBA - CMS editor experience Design

### ISSUE THREAD

**Issue by jcklpe** [department-of-veterans-affairs/va.gov-cms#9954]
## Description

For each Drupal entity that VBA editors will interact with, we need to thoroughly review the UI and make sure it follows the CMS Design System. 

We also want to think holistically about the editorial experience across content types and look for opportunities to make things clear and usable

**Comment by xiongjaneg** [comment]
moving remaining tickets to Pilot MVP initiative level for better tracking
