### ISSUE TITLE
CMS Lovell menu items should be identified as Lovell, Tricare, or both

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#9956]
~~When an an item is saved for Lovell, any node that is assigned to section "Lovell Federal health care"
AND added to the Lovell Federal health care menu should have an additional menu entry added to the Lovell Tricare menu so that editors don't have to add it to both.~~
![image](https://user-images.githubusercontent.com/5752113/182256409-45c107a6-504f-4397-806f-36af0c9a65ab.png)

~~Weighting of menu items is going to be challenging.   Ideally it is probably best to mimic the weight and parenting of the menu item saved in the main Lovell menu.   There are going to be challenges to this if the parent is not one that exists in both menus.  This should be rare and may just require a hand correction by an admin when it occurs, or we look up the parent name in the one menu and try to find the equivalent in the second menu.~~

After some discussion, @swirtSJW and I have come up with a new solution. Menu items are fieldable in Drupal 9 just like nodes, blocks and other entities. As such, we are proposing we add a new field to the Lovell Federal health care menu: /admin/structure/menu/manage/lovell-federal-health-care

This field should be called Menu Section, should be a list field and should allow for 3 values:
- main
- tricare
- both

When a node is saved, and a corresponding menu item is also saved, we check the section for the node the menu item points to. If that section is Lovell - VA the menu section for the menu item will be set to va. If that section is Lovell - Tricare the menu section will be set to tricare. If that section is Lovell Federal health care then the menu section will be set to both.

Additional work will be needed on the front end to read these values in the appropriate graphQL queries to show the appropriate menu items:

- The Lovell Tricare page should show menu items for tricare and both while the Lovell VA page should show menu items for va and both. 

## AC's
- [ ] Code lives in new vamc_lovell module, menu presave function
- [ ] When a menu item is saved check what menu it lives in.
- [ ] If the menu item is being saved in the Lovell Federal health care menu see if the menu item is a link
- [ ] If it is a link and it points to a drupal entity, load that entity and check the value of field_administration
- [ ] Set the field_menu_section value for the menu item based on the value in field_administration on the node.
- [ ] ~~When an item is saved for Lovell, any node that is assigned to section "Lovell Federal health care"
AND added to the Lovell Federal health care menu should have an additional menu entry added to the Lovell tricare menu so that editors don't have to add it to both.~~
- [ ] ~~Menu items added to both, end up in the right spot in the Tricare menu.~~
- [ ]  ~~When parents can't be found, people are notified that placement in Lovell Tricare failed and to contact cms help desk ???~~

**Comment by JayDarnell** [comment]
May need this as a reference for our ultimate solution: https://drupal.stackexchange.com/questions/287104/how-to-update-a-field-on-menu-link-content-added-using-menu-item-extras-module
