### ISSUE TITLE
CMS Create Lovell tricare facilities by hand

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#9957]
There are several facilities that are DoD (Tricare only)  
- [USS Osborne Dental Clinic](https://www.lovell.fhcc.va.gov/locations/USSOsborne.asp) 
- [USS Red Rover](https://www.lovell.fhcc.va.gov/locations/USSRedRover.asp)
- [USS Tranquillity](https://www.lovell.fhcc.va.gov/locations/USS_Tranquillity.asp)
- [Zachary and Elizabeth Fisher Medical and Dental Clinic](https://www.lovell.fhcc.va.gov/locations/FisherMedicalDentalClinic.asp)
That will need to be created by hand:

## AC's
- [ ] Gather address and hours from existing page links above.
- [ ] Assign to section Lovell - Tricare
- [ ] Create detectable facility ids that could be used to prevent pushing data to lighthouse.
  example: tricare_01, tricare_02 ....
- [ ] save as draft, include revision note to show where the data came from.

**Comment by swirtSJW** [comment]
Data may not fit into our existing fields.  Raise cases like that in this issue.

**Comment by swirtSJW** [comment]
These can not be created on prod until #9943 has been completed and hits prod.

**Comment by omahane** [comment]
That didn't take long.
<img width="940" alt="Screen Shot 2022-08-04 at 3 20 25 PM" src="https://user-images.githubusercontent.com/766573/183097520-6afa9105-53f6-4feb-9161-89c20a8f12b0.png">

**Comment by omahane** [comment]
From Slack:
1. Name of facility will be hand-entered
2. Facility Locator API ID must be hand-created. I'm using "tricare_01", per @swirtSJW 
3. Classification depends on the facility (making my best guess)

**Comment by omahane** [comment]
@swirtSJW @JayDarnell In looking at out facility descriptions, they do not seem to have the same amount of color commentary about the facility as you see on the [USS Osborne page](https://www.lovell.fhcc.va.gov/locations/USSOsborne.asp) or any [of](https://www.lovell.fhcc.va.gov/locations/USSRedRover.asp) [the](https://www.lovell.fhcc.va.gov/locations/USS_Tranquillity.asp) [others](https://www.lovell.fhcc.va.gov/locations/FisherMedicalDentalClinic.asp):
![Screen Shot 2022-08-05 at 4 30 34 PM](https://user-images.githubusercontent.com/766573/183212052-644f19fd-b663-4ec8-bdb8-c7ddf56fbd18.png)

What will we end up doing with this information (if anything)?

**Comment by swirtSJW** [comment]
Nice work @omahane
