### ISSUE TITLE
Solidify VA Drupal CMS Helpdesk Support Incident Response Plan

### ISSUE THREAD

**Issue by stefaniefgray** [department-of-veterans-affairs/va.gov-cms#9964]
## Description
The VA Drupal CMS Helpdesk Support team does not have an updated helpdesk-specific incident response plan for issues such as failed content releases.

Most recent documents:
- https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/helpdesk/incident-response.md
- https://docs.google.com/spreadsheets/d/1RiqpHVipfQEjPmkOAhe1coy_wL__49MLLIF6b5Th2xI/edit#gid=0 (Very outdated!)

Previous ticket regarding failed content releases:
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/7116

## Acceptance Criteria
- [x] Team has solid plan for handling serious incidents, failed content releases past 2 hours, and Editor emergencies.
- [x] Incident response materials are updated within Github and are visible to entire team

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [x] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [x] `⭐️ User support`

**Comment by EWashb** [comment]
Is this ok to close now @TroyA6 and @stefaniefgray?

**Comment by TroyA6** [comment]
Hi Erika,
The IRP is well underway, but technically, still in progress -- processing
feedback from the Platform team.
Should be able to wrap it up over the next sprint, then present the
following sprint.
I think that follows the Q4 goal documentation.
Does that make sense?
Thank you,
Troy

**Comment by stefaniefgray** [comment]
Spin-off ticket: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12673

**Comment by TroyA6** [comment]
@stefaniefgray @EWashb @laflannery  [Github Location](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/cms/helpdesk/incident-response-planurl)
