### ISSUE TITLE
[CMS COLLAB CYCLE INTAKE] (Facilities, VAMC, Lovell edge cases)

### ISSUE THREAD

**Issue by davidmpickett** [department-of-veterans-affairs/va.gov-cms#9967]
### What type of request are you making?

- [X] Update to an existing CMS feature (including product iterations, updating DS components or page layouts and nav changes)
- [ ] New CMS feature (New content types, DS components, workflows or products)
- [ ] Content audit (either one time audits or resuable tools)
- [ ] Change Management review (for any visible changes to the CMS, workflow or content model)
- [X] Other

### Please choose the team that is requesting the Collab Cycle kickoff.

Facilities

### When did/will you start working on this product/feature?

Design began Dec 2021 under previous Facilities team

### When will your feature need to launch?

Q3

### Are you doing research with VA.gov users or editors?

Yes

### Will your work involve changes to...?

CMS content model

### Please add a link to your product outline issue.

https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9655

### Additional Information

- Lovell [content model](https://airtable.com/appojvgFB7lvqgArz) is the latest artifact I created and would like to get your feedback on so we can plan next steps

- Lovell [product folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/facilities/medical-centers/product/lovell)
- Lovell Super Epic: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9655
- UI design epic: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9842
- Content design epic: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/7622
- Development epic: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9656

### Notify the Sitewide CMS team of this ticket in the cms-support Slack channel.

- [X] I acknowledge that I must notify `#cms-support` after submitting this issue.

**Comment by davidmpickett** [comment]
Myself & David Shannon at a minimum. Depending on how much we'll need to drill into technical constraints, Steve Wirt could be another rep.

**Comment by EWashb** [comment]
Collab cycle kickoff meeting held 8/4. Next steps for Sitewide CMS to support the Facilities team are:

- Content model review
- Drupal design system introductions and drupal training for UX team
- Facilities is on the right track for following content model (there should not be any extensive editorial workflow changes with the proposed design/drupal build)

**Comment by EWashb** [comment]
@davidmpickett and @dsinla Apologies for the delayed response on this. We do recommend a midpoint review for this work.

The deliverable for this review would be any prototypes, wireframes, etc. These design review docs can be delivered async

A tech review may need to be conducted as well at midpoint if you have a handle on the content model or architectural changes within the CMS. However, I know that you're working closely with Swirt and this may be optional as long as the design review is conducted.

**Comment by davidmpickett** [comment]
@EWashb - Talking with @dsinla and @swirtSJW in Facilities Prefinement today, I think we might be approaching the time for a Midpoint Review. The CMS parts of Lovell are getting finalized, and KB articles may start to be drafted as early as Sprint 70.

A lot has changed from a staffing perspective since our last touchpoint here, so might be worth scheduling a short state of the project meeting just to make sure we're all on the same page.

**Comment by dsinla** [comment]
@EWashb @davidmpickett Following up on this ticket - Do we need to schedule a midpoint review here?

**Comment by EWashb** [comment]
Yes! this will need a midpoint review @dsinla

**Comment by EWashb** [comment]
@dsinla I noticed you added this to your sprint, but we didn't get around to it. I'm going to remove the sprint label and we can prioritize when you're ready

**Comment by JQuaggles** [comment]
@EWashb What do we actually need for this ticket? Let's chat.

**Comment by EWashb** [comment]
@JQuaggles honestly probably nothing at this point. The build is already too far gone to do a proper collab cycle. I'm ok to close this if you are.

**Comment by JQuaggles** [comment]
Thanks @EWashb, We can sync about what's there this week and discuss any concerns. 
Will set up that call and closing this ticket.
