### ISSUE TITLE
Change management for continual content releases

### ISSUE THREAD

**Issue by ContentBrewmaster** [department-of-veterans-affairs/va.gov-cms#9968]
The change represented by the epic #[7600](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/7600) will improve the speed of content getting published to VA.gov.
 
**1. Describe the change from the perspective of VA employees, in plain language. What is the employee going to experience with this change?**

> Example: Editors visiting prod.cms.va.gov will see a new screen directing them to log in with PIV. Once logged in they will experience a new look and feel to the CMS interface.

**2. Explain why the change is necessary from a CMS/platform and project goal perspective. Link to screenshots if that helps tell the story.**
We want to change content release behavior so that a new content release will be triggered upon completion of a previous one, within business hours. Outside of business hours, content releases will happen as they currently do, either manually triggered from the CMS or else triggered via other CMS actions (i.e. saving an alert).

**3. Select the role(s) impacted by the change.**
- [x] All CMS users
- [ ] All CMS editors
- [ ] Vet Center editor
- [ ] VA Medical Center editor
- [ ] VA Outreach Hub editor
- [ ] VA Benefits Hub editor
- [ ] Campaign landing page editor
- [ ] VA Resources and Support editor
- [ ] Offices editor
- [ ] Supporting roles such as CMS account admin, Facilities or Public websites team member

**4. How will success be measured for this change?**
- [x] No help desk support is needed, as measured through help desk tickets
- [ ] The content adheres to VA policies and standards for VA.gov, as measured through a dashboard tool and/or audit

**5. Does the change require new or updated:**
- [x] Knowledge Base article
[When will my content be published live on VA.gov?](https://prod.cms.va.gov/help/cms-basics/when-will-my-content-be-published-live-on-vagov)
- [ ] Training video(s)
If existing videos, list URLs:
- [ ] CMS UI support?
- [ ] Announcement block

**6. Will the change be tested with users before release?**
- [ ] Yes
- [x] No

**8. Are there any known dependencies?**
Sitewide CMS changes

**Comment by cweagans** [comment]
Additional info here if it helps! https://github.com/department-of-veterans-affairs/va.gov-cms/issues/7600#issuecomment-1202986200

**Comment by ContentBrewmaster** [comment]
Per @davidconlon on #7600, closing this ticket.
