### ISSUE TITLE
PACT Act Redirect Request

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-cms#9971]
### Instructions
- Requests must be submitted **AT LEAST** 2 weeks in advance.  Some requests take a significant amount of time and coordination to implement, so start the process as soon as you know you will need one. 
- This issue will be used from initial request through implementation to ensure all individuals working on this are notified of status updates.  Please do not create multiple issues to track differnt steps.
- It is your responsibility to notify VA stakeholders as appropriate.  

### Type of request
- [ ] We are retiring or taking down a page and need to redirect the URL (complete redirect section)
- [ ] We are changing the URL of an existing page (complete redirect section)
- [X] We need a custom vanity URL (complete vanity URL section)

### Implementation date
When does this request need to be live: 
Timing is completely dependent on when the law passes, but we need to be prepared asap so I'm putting this request in now. We were going to wait to do a vanity url until we had a campaign landing page in place, but it looks like we may need to temporarily use it for the resources and support page.

### Redirects 
Current URL  |  Redirect Destination or New URL
---  |  ---
current URL | new URL

### Vanity URLs 
Vanity URL  |  Landing page
--- | ---
www.va.gov/pact **and** www.va.gov/PACT **and** www.va.gov/pact-act (3 URLs total)  |  va.gov/resources/the-pact-act-and-your-va-benefits

**Note:** We need to point the vanity URL to the resources and support page to start until we have a campaign landing page ready. @mnorthuis noted that we may want to start with a 302 temporary redirect for this vanity url to make it easier to switch to the campaign landing page when it's ready.

**Link to campaign landing page request issue:** This will come today once we talk with OPIA more.

### Process, Roles and Responsibilities
- [x] Requesting team: Above information is provided
- [ ] Requesting team: All appropriate VA stakeholders are notified as appropriate
- [x] IA: Request is vetted and documented and implementation plan is clear 
- [x] IA: Request is assigned to appropriate team for implementation 
- [ ] Implementation team: Work is complete
- [ ] Implementation team: Validated in production
- [ ] Requesting team: Validates everything is correct in production and closes ticket

**Comment by jilladams** [comment]
Makes sense. I don't know that we've done temporary 302s yet, so frontend folks will need to take a look at what's different about that from other redirects & confirm. Queued up for next sprint, starting Monday.

**Comment by DanielleThierryUSDSVA** [comment]
Hi @jilladams. Checking in on a few things here:

1. We need this to be ready to go live as early as **on Monday**. I want to make sure that's clear from the messages above. Apologies for the last-minute nature of the request. The original plan has shifted and this is a high priority request. Please let me know if/how @mnorthuis and I can help support. To this point, a question - does a vanity url rely on the daily deploy?
2. @mnorthuis has noted that the 302 shouldn't add complexity. But if it does or you're worried about that, we can go with the 301.

**Comment by jilladams** [comment]
Sprint planning: 
* don't publish in advance, in case act doesn't pass = tech debt
* Just needs code approval.
