### ISSUE TITLE
Follow up on VA.gov collab cycle for Lovell

### ISSUE THREAD

**Issue by davidmpickett** [department-of-veterans-affairs/va.gov-cms#9976]
## Description

To what extent is the collaboration cycle opened by Facilities v.1 still open? Or in what way does this need it's own collab cycle?

- Previous team's [design intent](https://github.com/department-of-veterans-affairs/va.gov-team/issues/38196) 
- Previous team's [IA feedback](https://github.com/department-of-veterans-affairs/va.gov-team/issues/37835)
- Collaboration cycle [documentation](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/)

## Acceptance Criteria
- [ ] Understand what parts of the collab cycle are needed for Lovell
- [ ] The appropriate meetings for the collab cycle are selected and scheduled

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by davidmpickett** [comment]
@dsinla This came up briefly in Sprint Planning today. I believe this was the meeting/process Dave C said we might need special pants for. 

A lot of the collab cycle documents refer to the product manager initiating meetings. While I've been happy handling some PM duties for Lovell, this seems like something that should come from you.

**Comment by davidmpickett** [comment]
I think this also falls under the category of work that can be completed in a single sprint, but crosses the boundary of the current sprint.

**Comment by dsinla** [comment]
Thanks @davidmpickett for calling this out. Let me get clarification from Dave C on his expectations.

**Comment by dsinla** [comment]
Create an issue with the platform team
Submit artifacts for review
Provide mockup from Sprint 64 - new wireframes front end "site switcher" 
Likely schedule Collab Cycle toward the end of next sprint

**Comment by dsinla** [comment]
After a bit more discussion with Dave C today, we want to bring Lovell (_as well as VBA_) into the collaboration cycle. My next step is to  to get a bit of a education from @cmaeng (meeting scheduled) and determine what artifacts are required to be brought to the kickoff (?) 
I think it's still reasonable this can happen within this sprint, but there are dependencies.

**Comment by dsinla** [comment]
Exploring and familiarizing for next steps.
We'll need to create a [Collaboration Cycle Request ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=collab-cycle-review%2Ccollaboration-cycle%2CCC-Request&template=collaboration-cycle-request.yml&title=Collaboration+Cycle+for+%5BTeam+Name%2C+Product+Name%2C+Feature+Name%5D)to kickoff the effort 

Are these the already existing Github 
- GitHub label for product - Facilities / Facility Locator
- GitHub label for feature - ? 

Do we need to create a [product outline template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/product-management/product-outline-template.md)?
Given the one-off nature of Lovell, and the fact that it's a variation of our already existing Facilities product,  do we use the [Iterative Brief Template ](https://bit.ly/initiative-brief-template)

**Comment by mmiddaugh** [comment]
looks like links were broken during some reorganization efforts - [Lovell Initiative brief is available here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/medical-centers/product/lovell/lovell-initiative-brief.md)

**Comment by dsinla** [comment]
Platform support ticket created: https://github.com/department-of-veterans-affairs/va.gov-team/issues/45628
Midpoint review scheduled for **Thursday Aug 25, 2022 ⋅ 10:30am – 11am (Pacific Time - Los Angeles)**
