### ISSUE TITLE
SPIKE Review and synthesize existing research and documentation on Services Taxonomy

### ISSUE THREAD

**Issue by davidmpickett** [department-of-veterans-affairs/va.gov-cms#9978]
## Very relevant
- [x] [VBA Benefits Services Taxonomy](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/facilities/regional-offices/services-taxonomy)
- [x] [VBA Facility Sites](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/facilities/regional-offices)
- [x] [MVP definition](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/facilities/regional-offices/design)
- [x] https://github.com/department-of-veterans-affairs/va.gov-research-repository/issues/90
- [x] https://github.com/department-of-veterans-affairs/va.gov-research-repository/issues/75
- [x] [VA Facilities Naming Schema](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/facilities/naming-schema)
- [x] [Compensation Final Presentation 20230120.pdf](https://github.com/department-of-veterans-affairs/va.gov-cms/files/10788083/Compensation.Final.Presentation.20230120.pdf)

## Somewhat relevant
- [x] https://github.com/department-of-veterans-affairs/va.gov-research-repository/issues/64
- [ ] https://github.com/department-of-veterans-affairs/va.gov-research-repository/issues/85
- [ ] [Facilities Taxonomy](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/facilities/taxonomy)
- [ ] [Vet Center Services taxonomy](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/facilities/vet-centers/services-taxonomy)
- [ ] [Vet Center Services Unmoderated Taxonomy Study](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/facilities/vet-centers/services-taxonomy/taxonomy-study)
- [x] [April 16 - May 10, 2019: Facility - Health services IA](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/facilities/medical-centers/pittsburgh-pilot/research/Facility%20research%20-%20health%20services%20IA%20-%20May%202019)

## Relevant?
- [ ] https://github.com/department-of-veterans-affairs/va.gov-research-repository/issues/16
- [ ] https://github.com/department-of-veterans-affairs/va.gov-research-repository/issues/140
- [ ] [Va.gov.Education.Application.Updates.UT.pdf](https://github.com/department-of-veterans-affairs/va.gov-cms/files/10788063/Va.gov.Education.Application.Updates.UT.pdf)
- [ ] https://github.com/department-of-veterans-affairs/va.gov-research-repository/issues/232
- [ ] https://github.com/department-of-veterans-affairs/va.gov-research-repository/issues/176
- [ ] https://github.com/department-of-veterans-affairs/va.gov-research-repository/issues/209
- [ ] https://github.com/department-of-veterans-affairs/va.gov-research-repository/issues/213

## Acceptance Criteria
- [ ] Document and present findings to VBA team / Facilities team

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by davidmpickett** [comment]
Did a little mapping between VBA services and benefits hubs in Airtable: https://airtable.com/invite/l?inviteId=invAIs7a1njCU7qzd&inviteToken=de033298ffe7b8c8e7b6c5865e3d96fd29dafcb532532e904a24559954a96076&utm_medium=email&utm_source=product_team&utm_content=transactional-alerts

**Comment by RWEagans** [comment]
@dsinla @davidmpickett Is this going to complete in Sprint 64 or will it for sure move to Sprint 65?

**Comment by davidmpickett** [comment]
> @dsinla @davidmpickett Is this going to complete in Sprint 64 or will it for sure move to Sprint 65?

@RWEagans I don't think I'll finish every piece here by Friday. I'm going to prioritize the aspects that are necessary for #10024. Let me know if you want me to break it into separate tickets

**Comment by RWEagans** [comment]
Should be ok. I'll leave it up to @dsinla to decide whether to break into smaller tickets. As of now I will let Dave C know that it will carry over into Sprint 65 as well. But moving ahead. Thanks for the update!

**Comment by davidmpickett** [comment]
Per conversations in refinement, I split the first chunk off of this as #10234

**Comment by davidmpickett** [comment]
Scoping this SPIKE to the duration of this sprint

**Comment by davidmpickett** [comment]
Completed my review of 2022-01 Testing the Naming Conventions of Current VBA Services - https://app.mural.co/t/vagov6717/m/vagov6717/1677277602711/74cecb64b6eeb9558aa868240cd726b54fcb93a7?wid=0-1677282206885&outline=open

**Comment by davidmpickett** [comment]
Also created this new part of the Content Model mural just for the service taxonomy https://app.mural.co/t/vagov6717/m/vagov6717/1658937741729/88cc653ce1bed251e60940c147867eb061496070?wid=0-1677268614480&outline=open

**Comment by davidmpickett** [comment]
Also created this new part of the Content Model mural just for the service taxonomy https://app.mural.co/t/vagov6717/m/vagov6717/1658937741729/88cc653ce1bed251e60940c147867eb061496070?wid=0-1677268614480&outline=open

**Comment by davidmpickett** [comment]
Closing this as complete since the scope was review as much as possibly during the sprint. I may revisit the items I didn't get to at a later date as we continue to work on the Service Taxonomy
