### ISSUE TITLE
Drupal landscape research / assessment for editorial workflow notifications

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#999]
https://app.mural.co/t/vagov6717/m/civicactions3117/1541020087963/dacc0207e712268bbc95dab96a08e5c587667776

**Comment by indytechcook** [comment]
My research is here: https://docs.google.com/document/d/1Ot-xoYzSTRoEdmvYa7hu3QZMeubOodEvuQCee7FHWyg/edit?usp=sharing

**Comment by indytechcook** [comment]
Moving this to done.  #1131 was created for next steps
