### ISSUE TITLE
Create Accessible Hover States in the CMS

### ISSUE THREAD

**Issue by EWashb** [department-of-veterans-affairs/va.gov-cms#9994]
## User Story

As a CMS editor, I need a CMS experience that is accessible and 508 compliant and includes hover states that meet color contrast and are easily supported by assistive technology.

## Background

From a Q3 accessibility audit of the CMS, many accessibility defects were found in the form of hover states. 

## Description of Work

The CMS experience team including the accessibility lead, interaction designer, and developer, should work to design and implement accessible hover states throughout the CMS.

## Acceptance Criteria
- [ ] all CMS hover states meet accessibility guidelines

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [x] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by laflannery** [comment]
@EWashb can I close this?  I wasn't aware of this epic but both issues inside it are closed so I think it would be ok to close now?

**Comment by laflannery** [comment]
@EWashb I'm going to close this - it's happening lol
