### ISSUE TITLE
Retarget Sentry notifications to target CMS Quality Assurance team.

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-cms#9995]
## Description
(Obviously, this is pending [the creation of a CMS QA Slack group](https://github.com/department-of-veterans-affairs/va.gov-team/issues/45690))

Currently, Sentry dumps incoming error monitor messages into `#cms-notifications`, where they are largely ignored.  They used to target `@here`, but that was viewed as disruptive.  So now they target no one, and no one pays attention.

The proper target for this sort of notification is a CMS QA Slack group.  I need to rap with Clarence and possibly others about creating that group.  Then I need to rap with Platform CMS DevOps about this change -- which I think they'll be positive toward.

## Acceptance Criteria
- [x] Rapped with the relevant folks about this, and they've either shot me down or capitulated to my grasping, grubby fingers.

**Comment by ndouglas** [comment]
@olivereri do you have any problem with me doing this?  My thinking is that I'll get yelled at constantly with the Sentry issues, I'll open up GitHub issues to deal with them and silence the Sentry issue for 4 weeks, I'll get the GitHub issues prioritized and fixed in that or the next sprint, and then Sentry will never ping me (or anyone else) for that issue again and #cms-notifications will be a nice quiet place to hang out.

**Comment by ndouglas** [comment]
Group name is `@cms-qa-engineers`.  I don't think this is in Terraform yet so I can throw that in there.  I think.

**Comment by olivereri** [comment]
> @olivereri do you have any problem with me doing this? My thinking is that I'll get yelled at constantly with the Sentry issues, I'll open up GitHub issues to deal with them and silence the Sentry issue for 4 weeks, I'll get the GitHub issues prioritized and fixed in that or the next sprint, and then Sentry will never ping me (or anyone else) for that issue again and #cms-notifications will be a nice quiet place to hang out.

No problem at all. I remember this is what we discussed awhile ago and has been in the back of my mind since. I even went into Sentry and modified the alert rules to silence those "Drupal Error Handler" exceptions. With that in mind this is very welcome.

**Comment by ndouglas** [comment]
Wait, hol' up, you silenced the Sentry errors?  That might explain why the widget on my dashboard went silent a few days ago:

![Screen Shot 2022-08-25 at 8 01 18 AM](https://user-images.githubusercontent.com/1318579/186659028-7a9c7ad4-59aa-42d5-8b42-d64256ace44e.png)

😂 😭 💀

**Comment by olivereri** [comment]
I didn't mean to silence all of them, but maybe that's what happened when I added a rule for the Drupal Handler? I thought that was just one specific error.

![image](https://user-images.githubusercontent.com/31904439/186704624-aaf0a301-e719-48d1-941a-acc19d6277ee.png)

**Comment by ndouglas** [comment]
nah, I think that'll nuke all of 'em

**Comment by ndouglas** [comment]
I think

**Comment by olivereri** [comment]
I deleted the rule, we'll see. I'll stop making changes like a cowboy.

**Comment by ndouglas** [comment]
okay, I'ma make the change in Datadog to target the Slack group, then we should start seeing these errors gradually decrease 😎
